### ISSUE TITLE
[REQ] Make all URLs modifiable

### ISSUE THREAD

**Issue by blindpet** [Jackett/Jackett#10]
Due to a new law in the EU for domain registrars to give up personal information it is likely domains will continue to change even for private trackers. To nip this in the butt, I'd make all trackers have a URL that is modifiable.

**Comment by Inrego** [comment]
I think it makes more sense to just make it configurable on the affected indexer. Just like some indexer have different configuration requirements than others (username/password)

**Comment by blindpet** [comment]
I respectfully disagree but if you want smaller incremental updates when other trackers change then that is of course up to you, the devs. I am just saying if you do an update that allows the URL to be configured for all trackers it will save you time in the long run.

**Comment by Inrego** [comment]
Only some indexers are affected by changing domains. It wouldn't make sense to roll this out to all other indexers in my opinion. But hey, we're allowed to disagree :smile:

**Comment by raspdealer** [comment]
We can mix.
Integrate a way to configure the url (to avoid users to be blocked) and push this modifications on the next version (for future users or users which can wait

**Comment by blindpet** [comment]
It is of course up to you on how best to implement it. The tracker I'm referring to has changed 3 times in the last few months and it is likely any trackers with EU owners will have similar issues.

@raspdealer if you are talking about some sort of advanced setting to toggle I think that sounds good.

**Comment by raspdealer** [comment]
yes exactly like in sonarr

**Comment by twistedroutes** [comment]
I totally missed this issue/enhancement when I posted #134.

https://github.com/Jackett/Jackett/issues/134

In there I wanted to have this discussion.  I have made some modifications to an indexer I was working on, but there are other options too, such as a new item type (radio selection, or a drop down selection) or even completely freeform text.  My current version has a text entry that validate against a list of allowable due URLs.

**Comment by twistedroutes** [comment]
https://cloud.githubusercontent.com/assets/2973320/11969870/ebbb6d26-a8ee-11e5-8ee3-a49d73a7c1ce.png

**Comment by raspdealer** [comment]
May be you should discuss about that with @JigSawFr because he wants to improve the jackett core.
It can be a good idea to make all url editable.

**Comment by marcstyles** [comment]
@raspdealer any chance this feature will be made available soon?

**Comment by marcstyles** [comment]
oops meant to nudge @JigSawFr

**Comment by kaso17** [comment]
Base URLs are now configurable for all indexers in pre-release v0.7.841, please try it
