### ISSUE TITLE
Encryption seed for tracker passwords not stored in config?

### ISSUE THREAD

**Issue by lox** [Jackett/Jackett#100]
I'm running Jackett in a docker container, when I stop it and start it again, I need to reconfigure my indexers. Is this by design?

**Comment by flightlevel** [comment]
You'd have to ask whoever created the docker container. We don't support docker directly. Jackett saves the config file in the Application Data folder. Linux folder example here https://ibboard.co.uk/Programming/mono-special-folders.html

**Comment by lox** [comment]
Right. I created the Docker container, and what I'm trying to figure out is if there is an encryption seed or key material stored outside of the Application Data folder. The symptom I'm seeing is after moving my config to a new host I get this error:

```
62659Z 12-19 04:19:09 Error Failed loading configuration for xxxxx, you must reconfigure this indexer System.Security.Cryptography.CryptographicException: Data unprotection failed. ---> System.Security.Cryptography.CryptographicException: Invalid data.
jackett-1 | 2015-12-19T04:19:09.582465824Z   at Mono.Security.Cryptography.ManagedProtection.Unprotect (System.Byte[] encryptedData, System.Byte[] optionalEntropy, DataProtectionScope scope) [0x00299] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/mcs/class/System.Security/Mono.Security.Cryptography/ManagedProtection.cs:231 
jackett-1 | 2015-12-19T04:19:09.582493252Z   at System.Security.Cryptography.ProtectedData.Unprotect (System.Byte[] encryptedData, System.Byte[] optionalEntropy, DataProtectionScope scope) [0x00030] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/mcs/class/System.Security/System.Security.Cryptography/ProtectedData.cs:91 
jackett-1 | 2015-12-19T04:19:09.582524037Z   --- End of inner exception stack trace ---
jackett-1 | 2015-12-19T04:19:09.582553877Z   
```

**Comment by JigSawFr** [comment]
What docker image do you use ? I've no problem in my side, all my apps are dockerized :)
I'm using arch-jackett:latest

**Comment by lox** [comment]
The issue was the keys are stored in `~/.config/.mono`, I was only persisting `~/.config/Jackett`. Solved! Thanks all.
