### ISSUE TITLE
[req] add SkyTorrentsClone2 https://skytorrents.to/

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#10000]
https://skytorrents.to/ is another skytorrents clone, from a different provider of the one at https://www.skytorrents.lol/

**Comment by garfield69** [comment]
\o/ 10000 issues milestone

**Comment by garfield69** [comment]
Jackett 0.16.1922

**Comment by ilike2burnthing** [comment]
https://www.skytorrents.to/ - Doing some maintenance

**Comment by garfield69** [comment]
back online
