### ISSUE TITLE
[New Tracker REQ] LibGen

### ISSUE THREAD

**Issue by dreazin** [Jackett/Jackett#1000]
Indexer Name>> LibGen

Type>> eBooks/Comics/Magazines

Indexer URL>> http://gen.lib.rus.ec/ (among others)

Tracker Language>> English

Invite>> Public

**Comment by zductiv** [comment]
Do any of libgen's torrents actually have any seeders? None of the ones I checked did.

Or are you planning to just use the details link to grab from one of the mirrors?

**Comment by dreazin** [comment]
Personally I'd use the details page to grab a mirror, but I would think that returning the torrent link wouldn't be much extra work even if it didn't have seeders.

**Comment by RoloSoze** [comment]
+1 for this tracker.

**Comment by garfield69** [comment]
cannot be supported with a cardigann definition, will require a c# indexer to support multi-download links on result details page.

**Comment by ProNoob333** [comment]
so has this been added?

**Comment by garfield69** [comment]
>so has this been added?

Nobody has volunteered to code this indexer so far. When the indexer is made available this ticket will be closed with a comment revealing the Jackett version that begins support for this site.

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
