### ISSUE TITLE
UI Unresponsive

### ISSUE THREAD

**Issue by OFark** [Jackett/Jackett#10015]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Unraid

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.1933.0

**Last Working Jackett Version**: Didn't look/Can't remember - a few days ago. 

**Are you using a proxy or VPN?** yes

### Description

I'm using the DyonR Docker for UNRAID, Last Commit Sept 12th.

A couple of days ago Jacket UI stopped responding to requests. Nothing. Chrome reports "ERR_CONNECTION_RESET", Firefox doesn't load and other machines on my LAN cannot load the UI. 

There is nothing in the Logs that I can see, that reveals an error, it all looks clean. 

Interestingly my Docker is running on a custom network, and with a Static IP or a DHCP IP it will not work. However, if I bridge the network connection it works just fine. Now, I immediately went to DyonR as he created the Docker template, but he hasn't changed it since September, and Jackett was working just fine a few days ago, I think it was fine last weekend. 

I've removed the Docker Image and reinstalled, I've removed the config folder, I cannot get it to work on a custom network.

Anything you can suggest?

**Comment by ilike2burnthing** [comment]
I think you'll have better luck there, as it's a likely an issue with that specific setup, rather than Jackett itself. However, any chance you're using PIA?

**Comment by OFark** [comment]
> I think you'll have better luck there, as it's a likely an issue with that specific setup, rather than Jackett itself. However, any chance you're using PIA?

Not any more. Privado on that Docker.

**Comment by ngosang** [comment]
I'm closing because there is not enough information. If the UI is not working is because something changed in the network or because Jackett process or Docker is dead. We have thousands of users and I'm pretty sure the UI is fine.
