### ISSUE TITLE
[Tracker REQ] T411 on jackett ?

### ISSUE THREAD

**Issue by dardano** [Jackett/Jackett#1001]
Is there possible to add back T411 http://www.t411.li/ back to jacket ?

As there is now some public trackers, I would like to have T411 back online :)

Thanks

**Comment by maxcore** [comment]
again for the 100000 times ask , check cardigann github

**Comment by kaso17** [comment]
the most recent versions of jackett contains public indexers (including T411) again.

**Comment by liversal** [comment]
@dardano , is it possible to provide me a invite for ethor.net tracker. Thank you in advance my friend ^^
