### ISSUE TITLE
[cpasbienclone] Exception (cpasbienclone): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /spksrc/spk/mono/work-aarch64-6.1/mono-5.20.1.34/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by skrodu10000** [Jackett/Jackett#10017]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS*synology DSM 6.2.3-25426 Update 2 *:

**.Net Runtime**: [.Mono]

**.Net Version*5.20.1.34.16*:

**Jackett Version*.16.1340.0*:

**Last Working Jackett Version*???*:

**Are you using a proxy or VPN?** [no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
If you can run Docker, I'd suggest you use the Jackett image.

If not, can you try downgrading using the following method? https://github.com/SynoCommunity/spksrc/issues/3946#issuecomment-612562594 (see bottom half of the comment)

**Comment by skrodu10000** [comment]
no i have synology ds 218

________________________________
De : ilike2burnthing <notifications@github.com>
Envoyé : samedi 31 octobre 2020 17:14
À : Jackett/Jackett <Jackett@noreply.github.com>
Cc : skrodu10000 <mijer10@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Jackett/Jackett] [cpasbienclone] Exception (cpasbienclone): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /spksrc/spk/mono/work-aarch64-6.1/mono-5.20.1.34/external/boringssl/ssl/handshake_client.c:1132: An error oc...


If you can run Docker, I'd suggest you use the Jackett image.

If not, can you try downgrading using the following method? SynoCommunity/spksrc#3946 (comment)<https://github.com/SynoCommunity/spksrc/issues/3946#issuecomment-612562594> (see bottom half of the comment)

**Comment by skrodu10000** [comment]
ok i try thx you


________________________________
De : ilike2burnthing <notifications@github.com>
Envoyé : samedi 31 octobre 2020 17:14
À : Jackett/Jackett <Jackett@noreply.github.com>
Cc : skrodu10000 <mijer10@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Jackett/Jackett] [cpasbienclone] Exception (cpasbienclone): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /spksrc/spk/mono/work-aarch64-6.1/mono-5.20.1.34/external/boringssl/ssl/handshake_client.c:1132: An error oc...


If you can run Docker, I'd suggest you use the Jackett image.

If not, can you try downgrading using the following method? SynoCommunity/spksrc#3946 (comment)<https://github.com/SynoCommunity/spksrc/issues/3946#issuecomment-612562594> (see bottom half of the comment)

**Comment by skrodu10000** [comment]
how to do for synology ds218 i don't understand sorry :'(

________________________________
De : ilike2burnthing <notifications@github.com>
Envoyé : samedi 31 octobre 2020 17:14
À : Jackett/Jackett <Jackett@noreply.github.com>
Cc : skrodu10000 <mijer10@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Jackett/Jackett] [cpasbienclone] Exception (cpasbienclone): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /spksrc/spk/mono/work-aarch64-6.1/mono-5.20.1.34/external/boringssl/ssl/handshake_client.c:1132: An error oc...


If you can run Docker, I'd suggest you use the Jackett image.

If not, can you try downgrading using the following method? SynoCommunity/spksrc#3946 (comment)<https://github.com/SynoCommunity/spksrc/issues/3946#issuecomment-612562594> (see bottom half of the comment)

**Comment by ilike2burnthing** [comment]
Use something like PuTTY to access your NAS and then run those commands - https://www.synology.com/en-global/knowledgebase/DSM/tutorial/General_Setup/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet

**Comment by skrodu10000** [comment]
Ok thank you for Help !!!! <3 Jackett is good ! radarr now don't launch can you help me  ? I'm sorry ....

**Comment by garfield69** [comment]
>radarr now don't launch

explain what you mean in more detail

**Comment by ngosang** [comment]
If Jackett is good I think we are done 😄
