### ISSUE TITLE
[desitorrents] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by razlaan** [Jackett/Jackett#10014]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Seedbox(Linux)

**Jackett **Version**: 0.16.770.0

**Last Working Jackett Version**: 0.16.770.0

**Are you using a proxy or VPN?** No

### Description

It seems like the login is failing however I am using the same user name and password to login to the website and it works.

### Logged Error Messages

Login Failed, Redirected Parse Error

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![error](https://user-images.githubusercontent.com/73673020/97641094-58141c80-19ff-11eb-9023-585f58b70362.png)

**Comment by garfield69** [comment]
Update to the latest Jackett (currently at 0.16.1933 at the time of this post) and try again.
