### ISSUE TITLE
[SkTorrent] search broken

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#10011]
https://sktorrent.eu/torrent/torrents.php
```
Not Found
The requested URL /torrent/torrents.php was not found on this server.
```
Not sure if it's just down or has been removed. 

https://sktorrent.eu/torrent/torrents_v2.php is up, but doesn't work with the current .yml

v3 is also down

**Comment by garfield69** [comment]
Jackett 0.16.1933
