### ISSUE TITLE
[rarbg] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by r1b1n** [Jackett/Jackett#10029]
rarbg is extremely unreliable

**Comment by garfield69** [comment]
and there is nothing we can do about it.
the problem is at the web site's api and not jackett.

**Comment by taylorcox75** [comment]
How are you searching?  I found rarbg to be very finicky. Even if you use an entirely different indexing method through radarr or sonarr with a different IP, I find the same issues tend to occur. 

Example of finickyness

Jackett Mass Manual Search while selecting Rarng:

`Manual search for "Better call saul" on rarbg with 0 results`

If I click the magnify glass by the individual indexer rarbg and search I get

`Manual search for "Better call saul" on rarbg with 100 results`

Searching sonarr

`Found 8 releases from RARBG for: Better Call Saul S05E10`

Back to the  manual jackett search and get 

https://pastebin.com/eDZCAJ8M


But in Sonarr disabling jackett and using their default

https://torrentapi.org

I'll either get results back, or nothing will be returned. So rarbg's end point is having the oroblems

**Comment by garfield69** [comment]
The RARBG operator does not want us using the web site with Jackett's HTML scraping.
we are obliged to use the API provided by RARBG at https://torrentapi.org/
docs at https://torrentapi.org/apidocs_v2.txt?app_id=Jackett
