### ISSUE TITLE
[REQ] ZonaQ.pw

### ISSUE THREAD

**Issue by RicardoVelaC** [Jackett/Jackett#10022]
Private Spanish tracker since 2016

Movies: BD, DVD, MKV
TVShows: BD, DVD

[www.zonaq.pw](https://www.zonaq.pw/)

Open signup during Halloween October 30 to November 2

Apply for signup in their emergency [forum](https://qqqueros.com/)

**Comment by RicardoVelaC** [comment]
@ngosang Maybe you're interested

**Comment by ngosang** [comment]
Applied and waiting for response.

**Comment by garfield69** [comment]
v0.24.457
