### ISSUE TITLE
[iptorrents] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by WastedMoment** [Jackett/Jackett#10055]
Hello,

Using Unraid V 6.9.0-beta30
Docker version: 0.16.1937.0 

Issues with trying to test with IPTorrents, was working fine last night. this morning it fails to test. The only message I get is:
 " An error occurred while testing this indexer
Found no results while trying to browse this tracker"

All I know is Iptorrents this morning updated their website, its different.... could this be related? Iptorrents also is no longer in the manual or add indexer.

**Comment by garfield69** [comment]
upgrade your Jackett to 0.16.1999
