### ISSUE TITLE
[REQ] HD-Only

### ISSUE THREAD

**Issue by itdaboyz** [Jackett/Jackett#1005]
Hi,

Could you add this tracker : 

Indexer Name>> HD-Only

Type>> Movies/TV Shows

Indexer URL>> https://hd-only.org/

Tracker Language>> French

Invite>> Private but I can request an invite for the dev who can add this tracker

For information, this tracker is based on Gazelle.

Thank you!

**Comment by kaso17** [comment]
Please send an invite to kaso1717 -at- gmail.com

**Comment by itdaboyz** [comment]
Ok, I sent this to the staff, you should get one soon.

**Comment by kaso17** [comment]
got the invite, thank you

**Comment by kaso17** [comment]
Added with 18908be38f507e6fa5b3d629fed659e0d291a118

**Comment by itdaboyz** [comment]
That was really fast!
Thank you

**Comment by kaso17** [comment]
Note: Due to extremely high security level of their HTTPS connection it won't work on Windows versions below 10.

**Comment by itdaboyz** [comment]
Is that why my Jackett keeps crashing (every few hours) on Linux?
It started happening after I added Hd-Only.

**Comment by kaso17** [comment]
Potentially yes, you might be running an openssl/libcurl version which might contain bugs causing connections using these relatively crypto algorithms to crash jackett. Mono most likely will crash with a segmentation fault. Do you have the error output in case of the crash?

**Comment by itdaboyz** [comment]
Ok, I see.
In Jackett's logfile I have nothing when it crash. Here it's when I saw Jackett crashed and restarted it : 

```
2017-02-09 00:43:09.2856 Info Found 63 (21 new) releases from HD-Only 
2017-02-09 09:32:15.4588 Info redirecting to /Admin/Dashboard 
```
I don't know if Mono log errors somewhere.

I have mono 4.6.2 and curl 7.44.0 (i686-asustor-linux-gnu) libcurl/7.44.0 OpenSSL/1.0.2j zlib/1.2.8 libidn/1.25 if that matters.

**Comment by kaso17** [comment]
If there's no error in the jackett log it's most likely a low level mono crash. If you're using systemd as init system you should be able to see the error using journalctl, otherwise you've to adjust your init script or start jackett manually in the foreground.

**Comment by seedforlife** [comment]
Hello, is there any way that someone invite me to this tracker please?!
Thanks a lot!
Regards

**Comment by ilike2burnthing** [comment]
https://hd-only.org/ - Site en maintenance

**Comment by ilike2burnthing** [comment]
back up
