### ISSUE TITLE
[iptorrents] Your cookie did not work: Parse error (Config)

### ISSUE THREAD

**Issue by BanditTech** [Jackett/Jackett#10050]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 16.1989

**Last Working Jackett Version**:16.1989

**Are you using a proxy or VPN?** [yes/no] yes

### Description

IPTorrents updated their website this morning at midnight, and the tracker is now having issues being added. 

### Logged Error Messages

```
Error on 20201101013131 for IPTorrents.txtSystem.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at AngleSharp.Common.ObjectExtensions.GetItemByIndex[T](IEnumerable`1 items, Int32 index)
   at AngleSharp.Dom.HtmlCollection`1.get_Item(Int32 index)
   at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 239
```

[log.txt](https://github.com/Jackett/Jackett/files/5470650/log.txt)

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ngosang** [comment]
Jackett v0.16.1996
