### ISSUE TITLE
[iptorrents] Your cookie did not work: Found 0 results in the tracker (Config)

### ISSUE THREAD

**Issue by strmch8ser** [Jackett/Jackett#10064]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Unraid Docker, Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.1937.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Attempting to add IPTorrents indexer.  When adding cookie, it returns the above error.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
[log.txt](https://github.com/Jackett/Jackett/files/5471489/log.txt)

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

![image](https://user-images.githubusercontent.com/62220148/97810801-7b7bd900-1c44-11eb-90a2-6df283d97b20.png)

**Comment by garfield69** [comment]
upgrade your Jackett to 0.16.1999
