### ISSUE TITLE
[torrentleech] Exception (torrentleech): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s). (Test)

### ISSUE THREAD

**Issue by Mouchoir** [Jackett/Jackett#10063]
### Environment

**OS**: QNAP 

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:  0.16.1996.0

**Last Working Jackett Version**: 0.16.1996.0

**Are you using a proxy or VPN?** Yes

### Description

I don't know when started having this exception for all my trackers (TorrentLeech, IPTorrents & YGGtorrents), but it was working three days ago.

### Logged Error Messages

I'm not sure where to find the logs.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/TroubleShooting#clearance-failed-after-10-attempts
