### ISSUE TITLE
[IPTorrents not searching anymore] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by JourneyOver** [Jackett/Jackett#1006]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.7.952.0
Mono version (if not using Windows):  

-------------------------------

IPTorrents keeps erroring out constantly producing 0 search results in return.. Dunno really how long this has been going on for as I just noticed it today but I copied the error and threw it up on hastebin as it had a bunch of stuff to it and idk what was important and what wasn't...

https://hastebin.com/hifadelebi.xml

the `Error on 20170130120044` spot the number keeps changing to a different number every time the error happens.

**Comment by kaso17** [comment]
Working fine for me.

Please enable enhanced logging and post a full log.
https://github.com/Jackett/Jackett#troubleshooting

**Comment by JourneyOver** [comment]
So I restarted my computer and the error seems to have gone away, dunno what the cause of it was exactly... but for now it seems to be gone, so I'm going to go ahead and close this..
