### ISSUE TITLE
jackett wont start. i randomly came to my computer to see jackett not working, when i try to start the service i get this error message

### ISSUE THREAD

**Issue by raiders04** [Jackett/Jackett#10067]
i randomly came to my computer to see jackett not working, when i try to start the service i get this error message

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
windows 10
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
latest
**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]
purevpn
### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Jackett.Common, Version=0.16.1873.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Jackett.Common, Version=0.16.1873.0, Culture=neutral, PublicKeyToken=null'
   at Jackett.Server.Program.Main(String[] args)

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
seems you are missing a module.
Use the task manager to kill any leftover Jackett tasks (service, tray, whatever) and 
manually upgrade your Jackett to 0.16.1999 from https://github.com/Jackett/Jackett/releases/download/v0.16.1999/Jackett.Installer.Windows.exe
