### ISSUE TITLE
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Logger.Error' not found.

### ISSUE THREAD

**Issue by mfrelink** [Jackett/Jackett#1007]
Jackett version:  commit of Jan 30
Mono version:  Mono JIT compiler version 4.4.1 (Nightly 4.4.1.0/4747417 Wed Jun 22 11:14:49 UTC 2016)

-------------------------------

I cannot start Jackett anymore, /usr/bin/mono --debug /opt/jackett/JackettConsole.exe is giving me: Unhandled Exception:
System.MissingMethodException: Method 'Logger.Error' not found.
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Logger.Error' not found.

**Comment by kaso17** [comment]
Please try upgrading mono to 4.6.2.
If that doesn't fix it please post the complete log.

**Comment by mfrelink** [comment]
I upgraded mono to 4.6.2, the error has changed, now it complains of missing something else.
`System.MissingMethodException: Method 'NLog.Logger.Error' not found.
`

What log are you looking for? There's no log being created in /opt/jackett (where my install of Jackett resides) and syslog is being awfully quiet.

**Comment by kaso17** [comment]
please post the complete output (from start to crash)

**Comment by drmarconi** [comment]
I too am seeing this issue. Have upgraded to mono 4.6.2. Here is my log:

[jackett-log.txt](https://github.com/Jackett/Jackett/files/751507/jackett-log.txt)

Thanks

**Comment by drmarconi** [comment]
Actually, my issue is resolved by using latest stable Jackett release v0.7.983.

Thanks

**Comment by kaso17** [comment]
I assume this has been fixed by updating mono/jackett.
