### ISSUE TITLE
[iptorrents] Your cookie did not work: Parse error (Config)

### ISSUE THREAD

**Issue by alchemy88** [Jackett/Jackett#10077]
Hey guys, this just started happening to me as of a day ago. IPTorrents rejected my current login with Jackett and when I went to add the cookie line it keeps saying this error. I've followed the directions exactly, I'm positive I've found the right line of code for the cookie as well. Not really sure what to do. Any help would be greatly appreciated thank you!
![sdfasf](https://user-images.githubusercontent.com/73815285/97838472-41dfb800-1cae-11eb-8ac2-8fd827d06502.PNG)

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
yeah, the web site changed their torrent search page layout, and the files column gave several version of the indexer fits.
but it has all been fixed now, so update your Jackett to 0.16.2010 and you should be good to go.

**Comment by alchemy88** [comment]
just saw that, thank you so much for the reply! All working now!
