### ISSUE TITLE
Error performing update

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#10086]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: windows 10 LTSC

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 

**Jackett Version**: 0.16.1964.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [no] 

### Description

check for update showing error,

### Logged Error Messages

```
Error performing update. System.Threading.Tasks.TaskCanceledException: The operation was canceled.  ---> System.IO.IOException: The read operation failed, see inner exception.  ---> System.ObjectDisposedException: Cannot access a disposed object. Object name: 'SslStream'.    at System.Net.Security.SslStream.ThrowIfExceptional()    at System.Net.Security.SslStream.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)    at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)    --- End of inner exception stack trace ---    at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)    at System.Net.Http.HttpConnection.FillAsync()    at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)    at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 165    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in D:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 174    at Jackett.Common.Services.UpdateService.DownloadRelease(List`1 assets, Boolean isWindows, String version) in D:\a\1\s\src\Jackett.Common\Services\UpdateService.cs:line 248    at Jackett.Common.Services.UpdateService.CheckForUpdates() in D:\a\1\s\src\Jackett.Common\Services\UpdateService.cs:line 139
--
```

### Screenshots

[Place any screenshots of the issue here if needed]
![image](https://user-images.githubusercontent.com/19517680/97880504-d5b78f80-1d53-11eb-81ba-95ca4330e5f9.png)

**Comment by garfield69** [comment]
Oops, sorry closed wrong ticket

**Comment by garfield69** [comment]
this looks a lot like #9331
use your browser and try to fetch https://github.com/Jackett/Jackett/releases/download/v0.16.2040/Jackett.Installer.Windows.exe
if it works, then shut down your Jackett service and system tray, and install this Jackett as a service and see if you get the issue tomorrow when the next auto-update kicks off.

**Comment by 3xploiton3** [comment]
> this looks a lot like #9331
> use your browser and try to fetch https://github.com/Jackett/Jackett/releases/download/v0.16.2040/Jackett.Installer.Windows.exe
> if it works, then shut down your Jackett service and system tray, and install this Jackett as a service and see if you get the issue tomorrow when the next auto-update kicks off.

now its working again
