### ISSUE TITLE
[New Tracker REQ] torrentHR

### ISSUE THREAD

**Issue by Pixa1** [Jackett/Jackett#1008]
Indexer Name>> torrentHR

Type>>Moovies/TV Shows/books/music...

Indexer URL>>https://www.torrenthr.org/

Tracker Language>> Croatian (I can help with translate)

Invite>> Private (i have invite for developer)

**Comment by kaso17** [comment]
Please send an invite to kaso1717 -at- gmail.com.

**Comment by kaso17** [comment]
added with 87c0792be046a6af8dbec63060beba78a4c37c3e
