### ISSUE TITLE
no usable version of libssl was found

### ISSUE THREAD

**Issue by charbelsako** [Jackett/Jackett#10089]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: void linux

**.Net Runtime**: none

**.Net Version**: none

**Jackett Version**: 0.16.2010

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

Tried installing jackett as a service on my void linux desktop but it doesn't start and says no version of libssl was found even though I have libssl 

### Logged Error Messages

11-02 18:34:39 Info Starting Jackett v0.16.2010.0 
No usable version of libssl was found
Aborted

**Comment by ngosang** [comment]
Install `openssl` package

**Comment by charbelsako** [comment]
Installed it but I get the same error

**Comment by garfield69** [comment]
just posing the obvious question here, after installing the openssl did you reboot the machine?
might be required in order to ensure shell patsh and environment vars get reloaded fresh.

**Comment by charbelsako** [comment]
@garfield69 yes I did.

**Comment by ngosang** [comment]
I think this is not a Jackett issue. You can try to install Jackett with Docker. There is a working openssl library in the Docker image.
https://hub.docker.com/r/linuxserver/jackett

**Comment by charbelsako** [comment]
thanks @ngosang
