### ISSUE TITLE
BitHumen: Tracker login problem

### ISSUE THREAD

**Issue by Noorbertt** [Jackett/Jackett#1009]
hi
I have a problem with https://bithumen.be tracker. I can not login at all from Jackett. In Chrome I do with no   problem.

**Comment by armani316** [comment]
@Noorbertt BitHumen is working fine for me. Please enable enhanced logging in Jackett, and post the log here. 

Make sure you mention which Jackett version you're running, and Mono version (if you're not using Windows).

**Comment by Noorbertt** [comment]
http://pastebin.com/3SswH95m
I changed my password to easyone but no helps me out
linux and lastest

**Comment by kaso17** [comment]
That's a normal log, please enable enhanced logging first.

**Comment by Noorbertt** [comment]
I know what is the problem.
I changed the address from https://bithumen.be/ to https://bithumen.be/login.php
Now its working.

**Comment by Noorbertt** [comment]
I got this with my url: http://pastebin.com/h0y7NUqS
this is the original: 	http://pastebin.com/TusDNDne

**Comment by kaso17** [comment]
The log with the original URL doesn't have enhanced logging enabled

**Comment by Noorbertt** [comment]
OK I going to reinstall jackett and will see.

**Comment by Noorbertt** [comment]
http://pastebin.com/79UZxWBk
I guess this is what you need. 
ctrl+f bithumen

**Comment by kaso17** [comment]
ok, I can reproduce this now. Only libcurl/linux is affected.

**Comment by kaso17** [comment]
should be fixed with a6c24a6c408d04df372d5f0533ec27c1567c02f1
