### ISSUE TITLE
Private Indexer

### ISSUE THREAD

**Issue by Fill1234** [Jackett/Jackett#10098]
Please add the private indexer : https://film-paleis.me as Jackett keep saying it failed to login.
Previous it was a semi pivate tracker.

Jackett Version 0.16.2040.0

Thanks

**Comment by garfield69** [comment]
- the film-paleis indexer was set to private in feb 2020
- the indexer was switched to using the cookie method on oct 2020

the indexer is working for me so this suggests any problems are happening at your end.
remember that the cookies expire, the duration is set by the web site.
So you need to regularly need to fetch a fresh cookie whenever the indexer starts to fail doing a search.
