### ISSUE TITLE
{"Message":"An error has occurred."} after starting Jackett on SYnology

### ISSUE THREAD

**Issue by Ic3Nine** [Jackett/Jackett#101]
Hey all,
Getting - {"Message":"An error has occurred."} when i navigate to the url after i start jackett. Pastebin from the log file below. What am i missing here.

http://pastebin.com/Ybxaxmwz

Thanks

Ic3

**Comment by gres147679** [comment]
Getting the same error on a Pi2 device running Mono 3.2.8

http://pastebin.com/BwXgRdpL

This happened after upgrading from 0.6.6 to 0.7.57. I can't access the webUI but everything else (I have several indexes on Sonarr, they all seem to be workig if I run the tests on them) seems to be working

**Comment by WhatFox** [comment]
See if 0.7.58 helps

**Comment by raspdealer** [comment]
Any news? Can we close it @WhatFox @Azerelat  after 1 month without news ?
