### ISSUE TITLE
[sportscult] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by mytvpro** [Jackett/Jackett#10116]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: linux

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:  Version 0.16.2076.0

**Last Working Jackett Version**: it is working ust not this indexer

**Are you using a proxy or VPN?**  no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

2020-11-05 13:51:07 | Error | System.Exception: Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 282    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
-- | -- | --
2020-11-05 13:51:07 | Info | Found 0 releases from SportsCult

### Screenshots

![image](https://user-images.githubusercontent.com/47206457/98283991-741f3d00-1f6e-11eb-9014-85a2eea2a314.png)

**Comment by mytvpro** [comment]
ok so i changed https://sportscult.org to https://sportscult.org/index.php?page=torrents/ and now it passes jacket test but does not allow search.

**Comment by mytvpro** [comment]
`Torznab error detected: sportscult does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported.`

**Comment by mytvpro** [comment]
i think its this t=movie in feed url. sportscult doesnt have movies. but they do have the ufc i want to fill in that was added to radarr

**Comment by garfield69** [comment]
the sportscult indexer does not currently have any search modes other than for the Jackett dashboard.
I will add a tv-search mode which should allow Sonarr to use the indexer.
but all the cats on sportscult are classifies as TV

the UFC matches are in the MMA (Mixed Martial Arts) cat, and these are not movies, so there seems little point adding a movies-search?

**Comment by mytvpro** [comment]
right im not looking to add a movies search but im looking to search for ufc that are added in radarr...

**Comment by mytvpro** [comment]
> the sportscult indexer does not currently have any search modes other than for the Jackett dashboard.
> I will add a tv-search mode which should allow Sonarr to use the indexer.
> but all the cats on sportscult are classifies as TV
> 
> the UFC matches are in the MMA (Mixed Martial Arts) cat, and these are not movies, so there seems little point adding a movies-search?

so unable to use sports cult with radarr then?

**Comment by garfield69** [comment]
why would you want to use sportscult with Radarr (a movies app)?
Are you using other Jackett sports indexers with Radarr currently, if so which ones?

**Comment by garfield69** [comment]
>but im looking to search for ufc that are added in radarr...

oh, just found this comment, missed it earlier.

OK then, I will add a movies-search mode so you can use it with Radarr too.

**Comment by mytvpro** [comment]
why would you want to use sportscult with Radarr (a movies app)?

while its a movies app all the ufc are listed and added and some are downloaded from iptorrents which is all i have used until now. but looking to fill in these missing ufc titles and sportscult seems the way to do it. which someone would make a sonarr fork for sports...

![image](https://user-images.githubusercontent.com/47206457/98298646-565cd280-1f84-11eb-8c6a-50ef7233a33e.png)

**Comment by mytvpro** [comment]
> > but im looking to search for ufc that are added in radarr...
> 
> oh, just found this comment, missed it earlier.
> 
> OK then, I will add a movies-search mode so you can use it with Radarr too.

ohh awesome!

**Comment by garfield69** [comment]
You are going to have to replace the default Radarr indexer cats 2000-2060 with either 5000 or 5060 to make it work.
The updated indexer will be available in the next Jackett release due out in approximately 8 hours or so.

**Comment by mytvpro** [comment]
> You are going to have to replace the default Radarr indexer cats 2000-2060 with either 5000 or 5060 to make it work.
> The updated indexer will be available in the next Jackett release due out in approximately 8 hours or so.

are the default cats usually fine? i have been removing them in favor or the categories as reported by jackett. should i use 5000/5060 or what jacket reports for sportscult categories?

**Comment by garfield69** [comment]
use what Jackett reports. 
in the case of sportscult, it will be 5060(TV/Sport) or the catch all cat 5000(TV) (you dont really need both but you can add them if you want).
see http://127.0.0.1:9117/api/v2.0/indexers/sportscult/results/torznab/api?t=caps&apikey=yourjackettapikeyhere
OR use the dashboard config for the sportscult indexer.

**Comment by garfield69** [comment]
you can use the custom cats 100000+ if you really want to fine grain filter the results, but be aware that this does not always work for all sites' indexers, depending on what the web sites search engine is capable and how the indexer has been set up to use it.

**Comment by mytvpro** [comment]
sorry maybe a little off topic now but seems to be no general category like this for iptorrents right? to make sure to get everything i want ive compiled this list:

`2000,2030,2040,2050,2070,5000,5010,5030,5040,5060,5070,5080,6000,6050,6070,100060,100026,100095,100076,100058,100077,100096,100048,100054,100062,100068,100020,100100,100007,100072,100055,100073,100078,100023,100066,100065,100083,100079,100022,100005,100099,100004,100088,100008,100081,100091`

**Comment by garfield69** [comment]
Yes pretty much. The main Torznab parent categories 2000(Movies) 5000(TV) and 6000(XXX) would cover most of the custom 100000+ categories that you specified.
But if you are only after UFC, then the IPtorrents web site seems to have them all in the TV/Sports cat, so if that is all you are using that site for, then the 5060 cat gets the job done.
If you are using Radarr in a more general way then cats
`2000,2010,2030,2040,2045,2050,2060,2070,5000,5010,5020,5030,5040,5060,5070,5080,8000`
would cover the more likely cats. You could add `,6000,6050,6070` if you wanted to include Adult cats too.

**Comment by mytvpro** [comment]
yes! its working! thank you so much. i am confused about why this release was rejected though i wonder if there is still some tweaking needed?

![image](https://user-images.githubusercontent.com/47206457/98338144-b4ff6c00-1fd7-11eb-8c75-3501efd785eb.png)

**Comment by mytvpro** [comment]
this one more clearly due to "main card" distinction

![image](https://user-images.githubusercontent.com/47206457/98338672-8635c580-1fd8-11eb-8f90-9bee0a4c9b96.png)

**Comment by mytvpro** [comment]
last one:

![image](https://user-images.githubusercontent.com/47206457/98338964-fc3a2c80-1fd8-11eb-80c7-7a10cb18de6d.png)

![image](https://user-images.githubusercontent.com/47206457/98339000-0bb97580-1fd9-11eb-8a0c-97173ff891db.png)

**Comment by garfield69** [comment]
Nothing to do with Jackett.

I'm guessing that Sonarr is expecting exact matching of the sequence of words in the title

So `ufc 240 prelims` matches, but `ufc 240 lots of stuff prelims` does not.
The `ufc 254` rejection is even more clear cut, the `main card` in the title means it not accepted as a match by Sonarr
As for `ufc 209`, Jackett was asked by Sonarr to look for `UFC 209 Woodley vs Thompson 2 2017` for which there is no match on the web site. You can only get results if you look for `ufc 209`

The title matching issues are nothing that can be done from Jackett side of things.
The titles are what they are on the website, and its not practical to try to get the jackett indexer to customise only some of the titles to rearrange the order of some parts so that they fit just one apps' definitions of what is an acceptable match.
We can apply general rearranging for all titles, such as moving the year, or massaging a season/episode scheme, but looking for `prelim` and moving it about is not within the scope of a Jackett's indexer job.

Explore the Sonarr settings and see if there is some way to customise the matching process to be more flexible, or if there is some way to edit its title after its been added (or during the add-a-movie step).
I'm not a Sonarr user so am not familiar with the app, other than to use if for basic testing for Jackett issues.

If it really bugs you contact Sonarr support and talk with them about it.

But if you cant find any Sonarr options, then you just have to accept that its not possible to automate some title downloads, and you have to manually kick off the download.

**Comment by mytvpro** [comment]
thank you for the detailed explanations!
