### ISSUE TITLE
[iptorrents] Your cookie did not work: Found 0 results in the tracker (Config)

### ISSUE THREAD

**Issue by jamolina5** [Jackett/Jackett#10113]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]
No

### Description

I am trying to add IPTorrents and I get an error. It used to work before but now stopped working. I have followed the steps to add the cookie but I get the below error in screenshot.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]
https://d.pr/i/EJpxol

**Comment by garfield69** [comment]
upgrade your jackett to the latest (currently 0.16.2076) to pick up the iptorrents fix
