### ISSUE TITLE
[Bug] RARBG: Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1011]
I think this has to do with RARBG redirecting my access attempts. Log attached. Thanks.
[log.txt](https://github.com/Jackett/Jackett/files/741006/log.txt)

Jackett version:  0.7.962
Mono version (if not using Windows):  N/A

**Comment by kaso17** [comment]
https://rarbg.to/threat_defence.php?defence=1&r=29217902 
I just learned they've an API so I can understand why they're blocking HTML scraping attempts...

**Comment by kaso17** [comment]
Should be fixed with d703488ccc2278ad49dc77fa513eae7faa3c1cb9

**Comment by armani316** [comment]
@kaso17 Working fine with 0.7.969.0! Thanks!

**Comment by armani316** [comment]
@kaso17 Links for RARBG's direct torrent download are all broken.

**Comment by kaso17** [comment]
With the API rarbg only provides magnet links.
The webinterface didn't support magnet links, fixed with d92c6977942a9bf02bb307ef250ad2c3b93e0c05
