### ISSUE TITLE
[hdspain] Error: ERROR: No se ha podido verificar que eres humano. (Config)

### ISSUE THREAD

**Issue by TuGeek** [Jackett/Jackett#10119]
### Environment

**OS**: "Ubuntu 16.04.5 LTS"

**.Net Runtime**: Mono

**.Net Version**: unknown

**Jackett Version**: 0.16.2080.0

**Last Working Jackett Version**: unknown

**Are you using a proxy or VPN?** no

### Description

Try to add HD-Spain indexer fails

### Logged Error Messages
Error: ERROR: No se ha podido verificar que eres humano.

### Screenshots

![hd-spain_error](https://user-images.githubusercontent.com/28299153/98360847-d8073b80-202a-11eb-8711-91aa7023d0a6.png)

**Comment by garfield69** [comment]
looks like hd-spain have enabled reCAPTCHA on login
![image](https://user-images.githubusercontent.com/6933240/98403254-8d8acb00-20cd-11eb-8933-84db1878a78d.png)

will need to switch the indexer login from method=form to method=cookie.

**Comment by garfield69** [comment]
Jackett 0.16.2096
