### ISSUE TITLE
jackett docker

### ISSUE THREAD

**Issue by titi69lpb** [Jackett/Jackett#10117]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: docker

**.Net Runtime**: 

**.Net Version**:

**Jackett Version**: latest

**Last Working Jackett Version**: latest

**Are you using a proxy or VPN?** [no]

### Description

Unable to connect to indexer. gktorrent does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported
### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
Unable to connect to indexer. gktorrent does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Which app (and its version) are you using to attempt to add the gktorrent indexer to?
also, for confirmation you are using the latest Jackett, please access your Jackett dashboard, scroll to the bottom and quote the version at the bottom of the page.

**Comment by titi69lpb** [comment]
Thx for your reply.
I found a solution i have delete all categories already check. I select again the good category and it works.
