### ISSUE TITLE
Jackett find the release TV episode and season pack but sonarr cant grabb it

### ISSUE THREAD

**Issue by valantislevas** [Jackett/Jackett#1012]
i put correct the search in sonarr from jackett and when tried to download season pack but doesnt grabb anything from jacket

http://IP:9117/torznab/magico/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100

if manually search it works and also it works with couchpotato.. sonarr finds 0 results.. :s

thanks

**Comment by valantislevas** [comment]
what is categories 5030 / 5040 ?

**Comment by kaso17** [comment]
Try setting the caps to 5000 in sonarr (you've to enable advanced settings first).
If it's still not working please provide a log.

**Comment by valantislevas** [comment]
17-1-31 10:24:36.6|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)
17-1-31 10:24:36.8|Debug|Api|[GET] /api/log/file: 200.OK (2 ms)
17-1-31 10:24:36.8|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)
17-1-31 10:24:36.8|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)
17-1-31 10:24:36.9|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)
17-1-31 10:24:36.9|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)
17-1-31 10:24:37.0|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (1 ms)
17-1-31 10:24:37.1|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (1 ms)
17-1-31 10:24:37.1|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (2 ms)
17-1-31 10:24:37.2|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (2 ms)
17-1-31 10:24:37.2|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (1 ms)
17-1-31 10:24:38.8|Debug|Api|[GET] /api/episodefile??seriesId=105: 200.OK (10 ms)
17-1-31 10:24:38.8|Debug|Api|[GET] /api/episode??seriesId=105: 200.OK (58 ms)
17-1-31 10:24:42.2|Debug|Api|[POST] /api/command: 201.Created (37 ms)
17-1-31 10:24:42.2|Info|NzbSearchService|Searching 2 indexers for [Grey's Anatomy : S10]
17-1-31 10:24:42.2|Debug|Torznab|Downloading Feed http://ip:9117/torznab/magico/api?t=tvsearch&cat=5000,5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Greys%20Anatomy&season=10
17-1-31 10:24:42.2|Debug|Torznab|Downloading Feed http://ip:9117/torznab/magico/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&q=Greys%20Anatomy&season=10
17-1-31 10:24:44.5|Debug|NzbSearchService|Total of 0 reports were found for [Grey's Anatomy : S10] from 2 indexers
17-1-31 10:24:44.5|Info|DownloadDecisionMaker|No results found
17-1-31 10:24:44.5|Info|SeasonSearchService|Season search completed. 0 reports downloaded.
17-1-31 10:24:49.4|Debug|DiskScanService|Scanning '/home/seeder/torrents/watched/' for video files
17-1-31 10:24:49.4|Debug|DiskScanService|0 video files were found in /home/seeder/torrents/watched/
17-1-31 10:24:49.6|Debug|Api|[GET] /api/queue??sort_by=timeleft&order=asc: 200.OK (5 ms)
17-1-31 10:24:54.0|Debug|Api|[GET] /api/health: 200.OK (1 ms)
17-1-31 10:24:54.1|Debug|Api|[GET] /api/diskspace: 200.OK (33 ms)
17-1-31 10:24:54.2|Debug|Api|[GET] /api/health: 200.OK (1 ms)
17-1-31 10:24:54.2|Debug|Api|[GET] /api/diskspace: 200.OK (29 ms)
17-1-31 10:24:55.0|Debug|Api|[GET] /api/log??page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (2 ms)
17-1-31 10:24:55.1|Debug|Api|[GET] /api/log??page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (5 ms)
17-1-31 10:24:55.9|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)

**Comment by valantislevas** [comment]
but on manuall search on jackett it works i see the torrent result from magico provider

**Comment by valantislevas** [comment]
for some reason on series new girl it works.. is very strange.. i will check other series to see again :S

**Comment by flightlevel** [comment]
When you manual search, does including the apostrophe in Grey's make in any difference to the results, try both both ways Greys and Grey's

**Comment by valantislevas** [comment]
yes i think about that but i write it like Grey's and on jacket the release is ok

**Comment by kaso17** [comment]
Yes, the apostrophe is the problem.
Sonarr searches for (see logs) "Greys Anatomy".
Try searching for that directly on magico, you won't get any results as it's called "Grey's Anatomy" there.
Added a workaround for Grey's Anatomy with 3bef41aeb6a6cf8af4d67075bc5f775f6ce617a0
Any other series with a ' probably will need the same kind of workaround
#893 would be the cleaner solution in this case.

Do you know if Magico somehow support searching by IMDB id (They have proper imdb information for almost all torrents but it seems like you can't for IMDB ids).

**Comment by armani316** [comment]
A number of trackers (in Jackett) have an issue with apostrophes as mentioned in #982. Since the solution has to be implemented on a per-tracker level, I'll try to test a few of them in the next few weeks. @kaso17 should this issue be closed?
