### ISSUE TITLE
[BakaBT] Category strings need to be changed

### ISSUE THREAD

**Issue by NGRichter** [Jackett/Jackett#10121]
Hi, someone changed the categories for BakaBT.
Right now it is:

            AddCategoryMapping(1, TorznabCatType.TVAnime, "Anime/Series")  
            AddCategoryMapping(2, TorznabCatType.TVAnime, "Anime/OVA")  
            AddCategoryMapping(3, TorznabCatType.AudioOther, "Audio/Soundtrack")
            AddCategoryMapping(4, TorznabCatType.BooksComics, "Books/Manga");
            AddCategoryMapping(5, TorznabCatType.TVAnime, "Anime/Movie");
            AddCategoryMapping(6, TorznabCatType.TVOther, "TV/Live Action");
            AddCategoryMapping(7, TorznabCatType.BooksOther, "Books/Artbook");
            AddCategoryMapping(8, TorznabCatType.AudioVideo, "Audio/Music Video");
            AddCategoryMapping(9, TorznabCatType.BooksEBook, "Books/Light Novel");

This should be different. @jellofishi correctly did the category names in commit 0bc64c6 which are the following

            AddCategoryMapping(1, TorznabCatType.TVAnime, "Anime Series");
            AddCategoryMapping(2, TorznabCatType.TVAnime, "OVA");
            AddCategoryMapping(3, TorznabCatType.AudioOther, "Soundtrack");
            AddCategoryMapping(4, TorznabCatType.BooksComics, "Manga");
            AddCategoryMapping(5, TorznabCatType.TVAnime, "Anime Movie");
            AddCategoryMapping(6, TorznabCatType.TVOTHER, "Live Action");
            AddCategoryMapping(7, TorznabCatType.BooksOther, "Artbook");
            AddCategoryMapping(8, TorznabCatType.AudioVideo, "Music Video");
            AddCategoryMapping(9, TorznabCatType.BooksEbook, "Light Novel");

![BakaBT Category Names](https://user-images.githubusercontent.com/22129925/98399534-cf325c00-2062-11eb-8064-8009ebf7f799.png)

_Originally posted by @NGRichter in https://github.com/Jackett/Jackett/pull/9227#issuecomment-723019967_

**Comment by garfield69** [comment]
does the change to the descriptions cause a problem?

**Comment by NGRichter** [comment]
I did a little research into the bakabt file and don't know much about Jackett in general, but I thought that this caused all torrents to be labeled as TV/Anime instead of the right categories
![Jackett BakaBT Search Query](https://user-images.githubusercontent.com/22129925/98399713-22a4aa00-2063-11eb-81f0-a0ef831fb21e.png)

**Comment by garfield69** [comment]
Hmm.
It does appear that the BakaBT indexer is sensitive to the **description** of the categories
https://github.com/Jackett/Jackett/blob/e3982e4a9d93d4fd208786b7cb44295da4ba4987/src/Jackett.Common/Indexers/BakaBT.cs#L246-L249
using MapTrackerCatDescToNewznab, where as most other use MapTrackerCatToNewznab, using the **catid**.

Anyway, I'll revert the description update for BakaBT and this will be available in the next release of Jackett due out in approx. 12 hours.
Thanks for reporting.

**Comment by NGRichter** [comment]
Thanks for the quick reply and action!

**Comment by garfield69** [comment]
Jackett 0.16.2096
