### ISSUE TITLE
alpharatio: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#10128]
They changed a lot of categories

![image](https://user-images.githubusercontent.com/10577978/98422293-96f34380-208b-11eb-8b9d-c8ee5d6b9107.png)

**Comment by garfield69** [comment]
my bad. did not realize gazelletracker abstract used cat descriptions as a matching for cats MapTrackerCatDescToNewznab()
I'll reverse out 570f422de1dca4fb362f1d219f7c8361d3667d5b for gazelletracker dependants.
