### ISSUE TITLE
[abnormal] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by arowan02** [Jackett/Jackett#10144]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Debian10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:  0.16.2106.0

**Last Working Jackett Version**: freshinstall

**Are you using a proxy or VPN?** [yes/no] no

### Description

when I try to add Abnormal tracker

### Logged Error Messages

An error occurred while updating this indexer: Object reference not set to an instance of an object.

### Screenshots

![image](https://user-images.githubusercontent.com/5852116/98466654-1b031380-21d1-11eb-8436-eac8a6bf4382.png)

![image](https://user-images.githubusercontent.com/5852116/98466684-687f8080-21d1-11eb-9852-ad2894398c59.png)

**Comment by ngosang** [comment]
Provide enhanced log
https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
