### ISSUE TITLE
[Bug] Searching CHDBits returns partial or no results

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1015]
It seems like this issue is category-dependent, for example:

Search CHDBits in Jackett for **Jack Reacher** - 0 results 
Search the tracker directly - 17 results

Search CHDBits in Jackett for **Game of Thrones** - 6 results 
Search the tracker directly - 28 results

Other categories may be affected as well, but I haven't checked.

Jackett version: 0.7.969.0
Mono version (if not using Windows):  N/A

**Comment by kaso17** [comment]
I'm getting the expected 17/28 results any chance there's a search filter left?

**Comment by armani316** [comment]
@kaso17 No there's nothing in the search filter. Tried the same keywords again, same 0/6 results.

**Comment by armani316** [comment]
Here's the enhanced log. Looks like the results are found but not returned? @kaso17 
[log.txt](https://github.com/Jackett/Jackett/files/745582/log.txt)

**Comment by kaso17** [comment]
Should be fixed with 0695ee90d6fd84c7f72fdcfc276c524805a41f47
You've some fancy mouseover effect instead of the full title, but then you don't get the full title in case the title was cut off for very long torrent names.
I've no idea which option is responsible for that.

**Comment by armani316** [comment]
@kaso17 Works fine now, thanks! Not sure about the mouseover effects to be honest, cause I don't think I have any special ones enabled. I'll look into it, but yeah the issue's been fixed now. Thanks!
