### ISSUE TITLE
[REQ] New Public Tracker tvsplurge.io

### ISSUE THREAD

**Issue by GordonHannan** [Jackett/Jackett#10158]
Hello,

I would like to request that the public tracker tvsplurge.io gets added to the list if possible.

Thanks!
Gordon

**Comment by garfield69** [comment]
you cannot search for an episode `the simpsons S32E01` only a series title `the simpsons`
this takes you to another page that has the seasons.
which in turn takes you to a single season page that has episodes
each episode takes you to a page that has multiple torrents/magnets.

similar behaviour in the latest page, which at first appears to list episodes but once a title is clicked leads to a page with multiple torrents.

the site is not suitable for yaml. will need a C# indexer if it has any change of being supported by Jackett.

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
