### ISSUE TITLE
Golang SDK for Jackett

### ISSUE THREAD

**Issue by vintikzzz** [Jackett/Jackett#10164]
Hi!

I have implemented Golang SDK for Jackett and opensourced it recently. 
Here it is [webtor-io/go-jackett](https://github.com/webtor-io/go-jackett).
If you like it, just notice it at README.md in right place if you wish.

**Comment by garfield69** [comment]
Not sure if/where to put this in our readme.
We currently list some Apps that can interface with Jackett, but dont have any SDK.
@ngosang  @ilike2burnthing  thoughts?

**Comment by ilike2burnthing** [comment]
Between the paragraphs beginning `Jackett works as a proxy server:` and `Developer note:`? Or beneath the `Installation on Synology` section?

Something along the lines of:
A third-party Golang SDK for Jackett is available from [webtor-io/go-jackett](https://github.com/webtor-io/go-jackett).

**Comment by ngosang** [comment]
Eventually we have to simplify the readme with less content and more links to other files/wiki.
By now I think we should include the SDK somewhere in the readme.

**Comment by vintikzzz** [comment]
I think this move can encourage other people to do some SDK for other languages. Appreciate!
