### ISSUE TITLE
[gfxpeers] site's server suspended

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#10161]
https://gfxpeers.net/ returning 
![image](https://user-images.githubusercontent.com/6933240/98625275-293d6500-2374-11eb-8f8c-1ccec15e6749.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/10161#issue-739545473

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/10161#issue-739545473

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://gfxpeers.net/ returning
> ![image](https://user-images.githubusercontent.com/6933240/98625275-293d6500-2374-11eb-8f8c-1ccec15e6749.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://gfxpeers.net/ retuning https://github.com/Jackett/Jackett/issues/10161#issuecomment-860080999

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
server suspended

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://gfxpeers.net/ returning ERR_CONNECTION_TIMED_OUT
https://www.uptrends.com/tools/uptime reporting TCP Connection Failed for all 43 checkpoints worldwide

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
server suspended

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
suspended

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
suspended

**Comment by ilike2burnthing** [comment]
https://gfxpeers.net/ - ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
back to the suspended page.

**Comment by ilike2burnthing** [comment]
> We’ll be back soon!
Sorry for the inconvenience but we’re performing some maintenance at the moment. We’ll be back online shortly!
— GFXPeers Team —

**Comment by ilike2burnthing** [comment]
> https://gfxpeers.net/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://gfxpeers.net/ - `Something was wrong with your request, and the server is refusing to fulfill it.`

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
scratch that, there are zero torrents on the site

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://gfxpeers.net/ returning
```html
Something was wrong with your request, and the server is refusing to fulfill it.
```
what a PITA

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://gfxpeers.net/ returning https://github.com/Jackett/Jackett/issues/10161#issue-739545473

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://gfxpeers.net/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/10161#issue-739545473

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/10161#issue-739545473

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://gfxpeers.net/ returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://gfxpeers.net/ returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://gfxpeers.net/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://gfxpeers.net/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
I don't know why we bother really. Its a niche site with no *arr relevance, so lets just delete it and forget it.

**Comment by ilike2burnthing** [comment]
[v0.20.3011](https://github.com/Jackett/Jackett/releases/v0.20.3011)

**Comment by iken98** [comment]
Cgpeers and forum are far better than gfxpeers.
![forum](https://github.com/Jackett/Jackett/assets/102949601/103e0921-dfd5-4345-a8b6-08ebcb0e1f58)
![site](https://github.com/Jackett/Jackett/assets/102949601/5f14dfb3-1cf1-49a2-b919-0b8f2567f030)

**Comment by garfield69** [comment]
cgpeers indexer is already defined on jackett
cgpersia is pending an invite so that an indexer can be created  #14695
