### ISSUE TITLE
[corsarored] Parse error: Additional text encountered after finished reading JSON content: p. Path '', line 1, position 4. (Config)

### ISSUE THREAD

**Issue by hvoid** [Jackett/Jackett#10173]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

Trying to add the tracker, returns the error and fails.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by hvoid** [comment]
Sorry.
OS: Windows 10
Jackett version  0.16.2131.0
When trying to add "Corsaro.red" indexer, I get following error:
"An error occurred while configuring this indexer
Parse error: Additional text encountered after finished reading JSON content: p. Path '', line 1, position 4."
Hope this is enough.

**Comment by garfield69** [comment]
the web site has been broken since 21 oct.
monitor #3593 for news.
closing as a duplicate.
