### ISSUE TITLE
[New Tracker REQ] Insane Tracker

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1017]
**Indexer Name**
Insane Tracker

**Type**
Movies, TV, Audio, XXX, PC/Mobile, Books, Console

**Indexer URL**
https://newinsane.info/

**Indexer Language**
Hungarian

**Invite**
Registration is now open for a limited time:
https://newinsane.info/signup.php

**Note**
This is a fairly large general Hungarian tracker with almost 94K torrents

**Comment by kaso17** [comment]
added with c60b35058dfc5f08e20e61a8e8399b82f2284d45

**Comment by armani316** [comment]
@kaso17 Thanks for adding this tracker. It seems like Jackett is displaying the wrong torrent size in the search results. They're all much larger than the actual size.

**Comment by kaso17** [comment]
fixed with 4bf97c83

**Comment by garfield69** [comment]
https://newinsane.info/ > Http Timeout

**Comment by garfield69** [comment]
online
