### ISSUE TITLE
[iptorrents] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Largehawiian** [Jackett/Jackett#10172]
### Environment

**OS**:
Debian 8 - jessie
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
Mono
**.Net Version**:

**Jackett Version**:
Jackett Version 0.16.1340.0
**Last Working Jackett Version**:
Jackett Version 0.16.1340.0
**Are you using a proxy or VPN?** [yes/no]
yes
### Description
IPTorrents updated their website and Jackett hasn't returned results since. I believe the category numbers may have been changed based on forum conversations.

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

An error occurred while testing this indexer
Found no results while trying to browse this tracker

**Comment by garfield69** [comment]
your Jackett 0.16.1340  has an out dated iptorrents indexer.
Update Jackett to 0.16.2139
