### ISSUE TITLE
Possible to copy over from different os's? 

### ISSUE THREAD

**Issue by droopified** [Jackett/Jackett#10170]
I have jackett on windows and want to install it on my unraid. Would it be possible to just transfer the config so I don't need to readd all the indexers?

**Comment by garfield69** [comment]
Yes, I believe you can copy all the indexer's configs by copying the folder `%ProgramData%\Jackett\Indexers`
However, any private indexers have encrypted passwords, the keys for which are stored in the folder `%ProgramData%\Jackett\DataProtection` 
but I recall seeing tickets in the past that stated that the keys are built using the local machine's credentials, so I don't think they will decrypt on another machine.
So I expect that you will need to use the Jackett dashboard on the target machine to edit each of the private configs and refresh the passwords.
