### ISSUE TITLE
[REQ] AnimeClipse.com

### ISSUE THREAD

**Issue by budgetfermium** [Jackett/Jackett#10171]
AnimeClipse is a Greek public ~~semi-private~~ tracker for anime.
Link: [http://www.animeclipse.com](http://www.animeclipse.com)

It has a working search engine. The site only offers .torrent files, no magnet links.

**Comment by garfield69** [comment]
Seems like the tracker page allows searching and clicking on the torrents yield a .torrent. 
So from a Jackett perspective this is Public. 
May need to have an a/c for posting comments on the forum, but Jacket does not need this.
Do you know if there a reason for Jackett to login?

**Comment by garfield69** [comment]
>AnimeClipse is a Greek semi-private tracker for anime

semi-private indicates that an account is required before access is granted to services.
but if a user does not have to login in order to search and download .torrents then as far as Jackett is concerned, the site is public.
If I set the Jackett's indexer to semi-private then we will be requiring all users to login before searching and download .torrents, and this does not appear to be necessary.

**Comment by garfield69** [comment]
Jackett 0.16.2142

**Comment by ilike2burnthing** [comment]
http://www.animeclipse.com/ - 403 Forbidden

**Comment by garfield69** [comment]
The indexer works for me.
You may need a VPN to change your region.

**Comment by ilike2burnthing** [comment]
> http://www.animeclipse.com/ - 403 Forbidden

**Comment by ngosang** [comment]
http://www.animeclipse.com/ - 403 Forbidden

**Comment by ilike2burnthing** [comment]
Works so long as you use a VPN. Don't know why it's necessary, but 🤷

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/182004050-0b09c331-d8f7-4d38-a7dd-2efbd92d3a4e.png)

**Comment by garfield69** [comment]
the indexer is working for me which suggest you might be IP blocked?

**Comment by ngosang** [comment]
Probably region block

**Comment by garfield69** [comment]
Jackett and browser get 403 forbidden with
http://www.animeclipse.com/index.php?ind=btitracker&search=&category=0&active=0&tor_page=50&order=added&by=DESC
But using browser web site search which generates 
http://www.animeclipse.com/index.php?ind=btitracker&search=&category=0&active=0&tor_page=100
succeeds. may need Referer, Host or some other Headers?

**Comment by garfield69** [comment]
dropping the order and by keywords and bumping tor_page to 100 is working.
I will experiment with options and do some testing.

**Comment by ilike2burnthing** [comment]
http://www.animeclipse.com/index.php?ind=btitracker&search=&category=0&active=0&tor_page=49&order=added&by=DESC
and
http://www.animeclipse.com/index.php?ind=btitracker&search=&category=0&active=0&tor_page=51&order=added&by=DESC
both work, it just seems to be `50` is the issue.  Even changing the `Torrents/Page` search setting to `50` in browser results in the same `403 Forbidden` error.

Just change it to 100?

**Comment by garfield69** [comment]
>Just change it to 100?

Yeah, I'll do that then. See how long that lasts ;-)

**Comment by garfield69** [comment]
As expected, the site is Returning Forbidden again
Time to look at the headers maybe?

**Comment by ilike2burnthing** [comment]
Damn :/ this looks purposeful, as now `50` is working again.

By all means try, but I'm not sure headers will make a difference, as it's not working on the site either.

Specifically, it's the combination of `&category=0&active=0&tor_page=100`. Change or remove any of those and it works again.

If you can't find a way to make it work, and want a test, remove `category` and `active` and change `tor_page` to `101`. If that's blocked by this time tomorrow, we know they don't want us around.

**Comment by garfield69** [comment]
Nah I can't be bothered. The site has 192 torrents, and nothing new since Aug 2020.
I'm going to remove it and call it a day.

**Comment by garfield69** [comment]
v0.20.3063
