### ISSUE TITLE
[DivTeam] search doesn't show right results

### ISSUE THREAD

**Issue by RicardoVelaC** [Jackett/Jackett#10196]
### Environment

**OS**: [https://hub.docker.com/r/linuxserver/jackett](https://hub.docker.com/r/linuxserver/jackett)

**Jackett Version**: 0.16.2152.0

**Last Working Jackett Version**: ----

**Are you using a proxy or VPN?** NO

### Description

1. When you search in Divteam, Jackett doesn't show the right results
e.g. if you search `Nasdrovia` you get 0 results but it appears in web trackers under `category 20`

`https://divteam.com/index.php?page=torrents&category=20`

2. If you do a blank search, Jackett only show 30 results and for this definition Jackett show pinned torrents and usually the tracker pins more than 30 torrent so Jackett always show the same results.

Maybe both are the same problem with categories but it's so confusing for this tracker

### Logged Error Messages

**No errors**

2020-11-14 12:30:39 | Info | Manual search for "" on divteam with 30 results.
-- | -- | --

**Comment by garfield69** [comment]
I cannot replicate your first report about searching for `Nasdrovia`
Jackett returns
![image](https://user-images.githubusercontent.com/6933240/99153866-4a091000-2710-11eb-82f4-c0d6852b8c47.png)
by using https://divteam.com/index.php?page=torrents&category=&search=Nasdrovia&active=0&options=0&order=3&by=2

which matches the web site search
![image](https://user-images.githubusercontent.com/6933240/99154037-a0c31980-2711-11eb-84db-b57530be8fac.png)

as for keywordless searching, I will see if I can get the indexer to ignore the pinned results, it should not have been including these in the first place, possibly an oversight in the original indexer creation.

**Comment by garfield69** [comment]
BTW, I get 100 results when I do a keywordless search. 
access your a/c on the web site and bump the torrents per page to 100.
This is recommended in the indexer config in an info box close to the OKAY button..

**Comment by garfield69** [comment]
Oh, just realised this is probably why you are not getting results for your searches, the combination of your torrents-per-page set to 30 and the number of pinned results. perfect storm. ;-)

**Comment by RicardoVelaC** [comment]
@garfield69 You're right was my fault, I set default number of torrent to 30 and the number of pinned torrent grew to almost 30. I changed to 100 result per page and fix my issue.

Thanks!! @garfield69

**Comment by garfield69** [comment]
Re-opened, because I still want to look into dropping the pinned results from the searches.

**Comment by garfield69** [comment]
Jackett 0.16.2157
