### ISSUE TITLE
[yggtorrent] Clearance failed after 10 attempt(s). (Config)

### ISSUE THREAD

**Issue by 3th3r** [Jackett/Jackett#10193]
yggtorrent, not wokring again

Environment
cenos 8:

.Net Runtime: unkown

.Net Version: unknow

Jackett Version: 0.16.2148

Last Working Jackett Version: 0.16.2148

Are you using a proxy or VPN? NO

Description
ERROR message:
An error occurred while updating this indexer
Clearance failed after 10 attempt(s).
Click here to open an issue on GitHub for this indexer.

couldn't set yggtorrent, even after, deleting & recreating Indexer.

Logged Error Messages
An error occurred while updating this indexer
Clearance failed after 10 attempt(s).
Click here to open an issue on GitHub for this indexer.

Screenshots
[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/10192#issuecomment-727054032
