### ISSUE TITLE
[yggtorrent] Clearance failed after 10 attempt(s). (Config)

### ISSUE THREAD

**Issue by 3th3r** [Jackett/Jackett#10192]
yggtorrent, not wokring again

### Environment

cenos 8:

**.Net Runtime**: unkown

**.Net Version**: unknow

**Jackett Version**: 0.16.2148

**Last Working Jackett Version**: 0.16.2148

**Are you using a proxy or VPN?** NO

### Description

ERROR message:
An error occurred while updating this indexer
Clearance failed after 10 attempt(s).
Click here to open an issue on GitHub for this indexer.

couldn't set yggtorrent, even after, deleting & recreating Indexer.

### Logged Error Messages

An error occurred while updating this indexer
Clearance failed after 10 attempt(s).
Click here to open an issue on GitHub for this indexer.

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by 3th3r** [comment]
pleasem fix the bot< This isn t a duplicate

**Comment by Bastien42** [comment]
yes it's YGG just brought back cloudflare because they are undergoing DDOS they will remove it when those that do DDOS them will stop

**Comment by garfield69** [comment]
And while the YGG cloudflare DDoS protection is active, there is nothing you can do with the standard Jackett.
so in the meantime, until the protection is lefted, either use your browser or look into experiment #9029 if you're able/willing to try it.

**Comment by aguillem** [comment]
It looks like YGG cloudflare DDoS protection is disabled again :)

**Comment by cmateo** [comment]
"An error occurred while testing this indexer
Exception (yggtorrent): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s)."
Still there

**Comment by Ionniz** [comment]
can you fix that please

**Comment by Bastien42** [comment]
> can you fix that please

No they can't it's on ygg to stop using cloudflare

**Comment by Ionniz** [comment]
They can fix with that https://github.com/Jackett/Jackett/pull/9028

**Comment by ilike2burnthing** [comment]
Announcement from @ngosang regarding Cloudflare bypass:

---

Fresh news!
* **Jackett v0.17.50 is out** and it includes this feature. If you are using a custom build, you can install the official release and enable auto-updates. [Documentation](https://github.com/Jackett/Jackett#configuring-flaresolverr)
* **FlareSolverr v1.2.0 is out**. It includes all features from CloudProxy and we have [new Docker images and documentation](https://github.com/FlareSolverr/FlareSolverr#docker)

Current workarounds are still working but I recommend you to install latest releases from Jackett and FlareSolverr. If we all use the same versions it is easier to provide support. If you have any issue with CloudFlare, YGG, etc open the issues in [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr).

---

v0.17.50 is out for Docker as well - https://github.com/linuxserver/docker-jackett/releases/tag/v0.17.50-ls9

**Comment by ngosang** [comment]
You have to configure FlareSolverr
