### ISSUE TITLE
Request: Cycle alternative URLs when set URL fails

### ISSUE THREAD

**Issue by Weggy** [Jackett/Jackett#10197]
Could an option be provided to enabling cycling through alternative URLs if the current set URL fails to connect. This option would be useful if an URL goes down so manually interaction wasn't required. It could also be useful from a testing point of view to discover which URL you should use for your setup. Although perhaps thats a different request which could be worked into the config section, effectively as test all URLs within a indexer so you need which works without have to try each one at a time.

**Comment by ilike2burnthing** [comment]
See https://github.com/Jackett/Jackett/issues/9618
