### ISSUE TITLE
jackett fails to start on ubuntu 18.04 when non-root user is used

### ISSUE THREAD

**Issue by froggy500** [Jackett/Jackett#10190]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by froggy500** [comment]
I'm installing jackett under ubuntu 18.04 (actually problem is in any version of gnu/linux), and using init.d/jackett service system.  Here's the snippet demonstrating the problem:

## Username to run jackett under, make sure you have a .jackett.rc in the
## home directory of this user!
USER="SXjackett"

## Absolute path to the jackett binary.
RJACKETT="/opt/jackett/jackett"

start)
  ...       start-stop-daemon --start --background --oknodo \
         --pidfile "$PIDFILE" --make-pidfile \
         --chuid $USER \
         --exec $RJACKETT

should be:
      start-stop-daemon --start --background --oknodo \
         --pidfile "$PIDFILE" --make-pidfile \
         --chuid $USER \
         --exec $RJACKETT -- --DataFolder="${JACKDAT}"
 because setup is not determining home folder of $USER; so you need to specify it explicitly.

This is not a bug; simply an exercise in hair loss.

**Comment by garfield69** [comment]
You need root permissions to install the Jackett as a service.
https://github.com/Jackett/Jackett#install-on-linux-amdx64
any other variation is not supported.
