### ISSUE TITLE
[REQ] Torrenting.me

### ISSUE THREAD

**Issue by UnR34L** [Jackett/Jackett#102]
https://torrenting.me

Registration is open, supports RSS feeds with direct download.

**Comment by raspdealer** [comment]
https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker

**Comment by twistedroutes** [comment]
I'm working on this tracker now.

**Comment by JigSawFr** [comment]
@twistedroutes nice to see that my new provider could help you ! I'm thinking to add some function to Jackett Core for all indexers. What do you plan to re-use for your's ?

**Comment by twistedroutes** [comment]
visually, the extra options should be in a separate "advanced config", with sensible/working defaults being selected by the developer.  I began the implementation of one with this indexer but abandoned it to go play with my kids!  I was hacking it in with javascript from the bespoke config, but it would be better handled in the content building.

Many of the functions could be put into a shared class - and then we can standardize how the indexers are built (and probably a wiki page to guide indexer developers).  THe template could simply allow for us to enable or disablle:
pagination handling
rss handling (and when to use rss vs something else)
multiple url handling
etc,

what you have laid out is most of the bones of a useful template (as I was trying to do with those I'd written so far, albeit with little experience).

**Comment by twistedroutes** [comment]
So the code was rejected due to the tracker being: open, part of IPT.
