### ISSUE TITLE
New Tracker Kapaki.info

### ISSUE THREAD

**Issue by valantislevas** [Jackett/Jackett#1020]
Hello i want to help to make it work with tracker kapaki.info also and is the same exactly with https://github.com/Jackett/Jackett/commit/12c421b6dbc037e602f13158df2caf0228e4a4e9
is possible to do something to help you if is possible to make it work?

thanks @kaso17 

Registrations open at this moment.

**Comment by kaso17** [comment]
Added with 57d117e4d02331b717dd60f3769da5a691c357e7
I copied the categorie ID mappings from magico, please double check them (magic categories need checking too).

And one more question regarding their search pagination.
When I access https://kapaki.info/?&p=torrents&pid=32&keywords=&search_type=name&searchin=title
I currently only get 4 results (on the following pages i get more results). How can i change the number of torrents shown on the first page?

**Comment by valantislevas** [comment]
as i see when i search from the page with all torrent i have many results i will check it further.. as i see the categories on kapaki.info is different from magico i will post here the categories and ids to update ..
thanks a lot !!

**Comment by valantislevas** [comment]
Main Categorys and ID's
-------------------------------------
Greek Movies = 61 
-CAM/TS/TVRIp = 62
-WebRip/Wp/R5/TC = 67
-DVDRip = 63
-BDRip/BRRip/HD/ = 69
-Packs = 77
-Philmography = 78

Foreign Movies= 1
-CAM/TS/TVRIp = 16
-WebRip/Wp/R5/TC = 59
-DVDRip = 14
-BDRip/BRRip/HD/ = 17
-Packs = 79
-Philmography = 31

Anime = 50
-CAM/TS/TVRIp = 64
-WebRip/Wp/R5/TC = 66
-DVDRip = 65
-BDRip/BRRip/HD/ = 68
-Packs = 80

Greek TV Series = 32
-Series = 79
-Packs = 81
-Documentarys = 51

Foreign TV = 58
-Series = 79
-Packs = 81 
-Documentarys = 84
 
Thanks.
@kaso17

**Comment by kaso17** [comment]
Can you convert them to the format used in the definition file please?

**Comment by valantislevas** [comment]
---
  site: kapaki
  name: Kapaki
  language: el-gr
  type: private
  encoding: UTF-8
  links:
    - https://kapaki.info/

  caps:
    categories:
      1: Movies # Movies
      16: Movies # N ees (2016, 2017)
      17: Movies/SD # DVDRip-BDRip-BRRip (e?? 2015) FREE
      59: Movies/SD # WebRip
      44: Movies # E English Movies
      84: Movies # N tokimanter
      79: Movies # Movies Packs

      58: TV # series
      79: TV/SD # , O Enes
      81: TV/Packs # E English
      84: TV/Documentarys # O Enes Complete Seasons

      55: Movies # Children
      38: Movies # M etaglotismena (Movies)
      39: Movies # M e Subtitled (Movies)
      93: Movies # M etaglotismena (Series)
      94: Movies # M e Subtitled (Series)
      45: Movies # I absent Anime
      98: Movies # M etaglotismena 3D
      64: Movies # M music for Children

      61: GRMovies # Greek movies
      62: GRMovies/CAM/TS # N ees Releases
      67: GRMovies/WEBRip # P. Alai Releases
      63: GRMovies/DVDRip # D. iskografies
      69: GRMovies/BDRip # In ylloges
      77: GRMovies/Packs # M AGICO Radio

is that ok ? i think isnt nessesary other categories

**Comment by dimqua** [comment]
It seems, it's dead: https://isitup.org/kapaki.info
