### ISSUE TITLE
[REQ] New public tracker alt-torrent.com

### ISSUE THREAD

**Issue by damianxd** [Jackett/Jackett#10204]
Hello,

I'm sorry if this is not the way to request for a new tracker to be added but I couldn't find any other way. I would like, if it's possible, to add https://alt-torrent.com as a tracker. It's public but the way the search works doesn't seem to be compatible with yaml, so a C# indexer is needed. I don't have any experience with that language.

Thanks for the help in advance!

**Comment by damianxd** [comment]
@garfield69 why did you removed this one from the New Public Trackers list while leaving 4 for JAV only and 4 more for more adult content and most of them are only just recently requested :/

**Comment by garfield69** [comment]
> why did you removed this one from the New Public Trackers list while leaving 4 for JAV only and 4 more for more adult content and most of them are only just recently requested :/

Check the labels and projects on the right of this ticket.
It was moved to the **New C# indexers** queue because the indexer cannot be written in yaml to support that web site.

**Comment by damianxd** [comment]
Thanks for the answer @garfield69
El 22 de mar. de 2021 14:29 -0300, garfield69 ***@***.***>, escribió:

why did you removed this one from the New Public Trackers list while leaving 4 for JAV only and 4 more for more adult content and most of them are only just recently requested :/

Check the labels and projects on the right of this ticket.
It was moved to the New C# indexers queue because the indexer cannot be written in yaml to support that web site.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/13178#issuecomment-1101877247
