### ISSUE TITLE
[New Tracker REQ] CGPeers

### ISSUE THREAD

**Issue by ShahadatRD** [Jackett/Jackett#1021]
**Indexer Name**>> CGPeers  (CGP)

**Type**>> CG/VFX/Art 

**Indexer URL**>> https://www.cgpeers.com/

**Tracker Language**>> English

**Invite**>> open signups is currently enabled at>> https://www.cgpeers.com/register.php

**Comment by kaso17** [comment]
added with CGPeers

**Comment by garfield69** [comment]
Since the recent tracker maintenance on CGPeers, the indexer needs updating.
related: #16710

**Comment by garfield69** [comment]
cgpeers: migrate c# to yaml. update for luminance #16190
