### ISSUE TITLE
[torrentdownloads] keywordless search (TEST) returns 0 results

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#10228]
the web sites today page is not producing results causing the indexer to fail a TEST or keywordless searches.
![image](https://user-images.githubusercontent.com/6933240/99476547-9e80e980-29b5-11eb-8d27-21e640ea7077.png)

**Comment by ilike2burnthing** [comment]
This seems to happen every few days around midnight, usually for a few minutes to a few hours. Seems they just have a very strict definition of 'today' - using the date rather than a rolling 24hrs.
https://github.com/Jackett/Jackett/issues/9595

Currently it's up.
