### ISSUE TITLE
[hd-forever] System.Exception: BencodeParser failed

### ISSUE THREAD

**Issue by RazorDarkAMG** [Jackett/Jackett#10225]
### Environment : Docker

**OS**: Raspbian64

**Jackett Version**: 0.16.2173.0

**Last Working Jackett Version**: I don't know maybe the one before, i use Watchtower for update contenair

**Are you using a proxy or VPN?** For Jackett NO

Hello, I have a problem with Jackett since yesterday, I can no longer download with, when I perform a search on a tracker, I find the results, but when I launch the download, I have an error : 

```
2020-11-18 01:02:34.5556 Error Error downloading. indexer: hdforever path: https://hdf.world/torrents.php?action=download&id=28768&authkey=XXXXXXXXXXXXXXXXXXXX&torrent_pass=XXXXX7XXXXXXXXXXXXX&usetoken=1
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 85 
```

I tried with other tracker and other torrent I have the same mistake, I don't understand because I didn't change anything to my settings and it work very well before...

Thank's for your help !

**Comment by garfield69** [comment]
To be clear, are you saying you have this issue only when downloading a torrent from the hd-forever indexer, 
or are you saying this problem occurs with **ALL** your Jackett indexers?

**Comment by RazorDarkAMG** [comment]
> To be clear, are you saying you have this issue only when downloading a torrent from the hd-forever indexer, 
> or are you saying this problem occurs with **ALL** your Jackett indexers?

With ALL Jackett indexers. Sorry for my bad english.

**Comment by garfield69** [comment]
@ilike2burnthing  would you like to tackle this one or pass it on to @ngosang ;-) ?

**Comment by ilike2burnthing** [comment]
I'll get this same error if I try to download an iTorrents .torrent which doesn't actually exist, as it redirects to LimeTorrents.

Can you provide an enhanced log reproducing the failed download? https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

Are you able to download magnet links?

Can you give some examples of the other indexers you have tried? You can share a screenshot if it's easier.

If GloDLS and Torlock aren't amongst them, try those as well as a quick check.

**Comment by RazorDarkAMG** [comment]
Hello, after several attempts on other trackers, indeed, the problem is only on HD-F, I show you a screen of the error.

https://res.cloudinary.com/razordarkamg/image/upload/v1605843235/Sans_titre_pewye7.png

I don't understand because my account at HD-F is well active with a positive ratio, I have no problem to download directly through the tracker at : https://hdf.world/

**Comment by ilike2burnthing** [comment]
Thanks for that clarification. Can you provide an enhanced log of the issue?

**Comment by garfield69** [comment]
@vlevas or @foXaCe Can either of you please check that you can start a download with the HD-Forever indexer?
@RazorDarkAMG  It may be that the site has changed their download links
I see that the indexer has two download link choices, the regular download, and one that uses the freeleech token.
This is controlled in the config via the **Always try to use the FreeLeech Token** checkbox.
Do you have this box ticked or not?

**Comment by garfield69** [comment]
@RazorDarkAMG  for instructions regarding the enhanced log see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by RazorDarkAMG** [comment]
@garfield69 you were right, I always tried to use FreeLeech token, and the problem is that, I didn’t have a FreeLeech token anymore ! I thought jackett would automatically pass on the ratio quota if we no longer had FreeLeech token or that’s not the case, thank you very much!

**Comment by garfield69** [comment]
the config switch simply appends `&usetoken=1` to the download link.
Some sites ignore it if the user does not qualify, but it looks like hd-forever actually complains.
this is why the download fails, because instead of getting a .torrent you end up getting a html page with a bessage, and that is the source of the benCodeParser failure you were seeing.

**Comment by garfield69** [comment]
@vlevas or @foXaCe Cancel the download test request, it is no longer required. Thank you.
