### ISSUE TITLE
[New Tracker REQ] Carpathians

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1022]
**Indexer Name**
Carpathians

**Type**
Movies, TV, Audio, XXX, PC/Mobile, Books, Console

**Indexer URL**
https://mycarpathians.net/

**Indexer Language**
Hungarian

**Invite**
Application signup is available through their IRC channel. IRC details are as follows:

Server: irc2.hu
Channel: #carp-invite
Port: 6667
SSL: Off 

You can use KiwiIRC web client:
https://kiwiirc.com/client

**Note**
Carpathians is a medium-sized general Hungarian tracker with almost 43K torrents

**Comment by armani316** [comment]
@kaso17 Any luck apply on their IRC?

**Comment by armani316** [comment]
@kaso17 If you haven't applied yet, I might be able to send you an invite. Let me know if it's required.

**Comment by kaso17** [comment]
I've been asking for an invite in their IRC for several days now, maybe they don't speak English there?
Sending an invite might be easier.

**Comment by armani316** [comment]
@kaso17 An invite will be sent to you shortly. Please confirm when you receive it.

**Comment by kaso17** [comment]
got it, thank you

**Comment by kaso17** [comment]
added with 178aceef52d580c1a2c1e046b1114b5f2d3e65dc
missing details:
* It doesn't detect freeleech torrents (how to identify them in the search results???)
* torrents with an age < 1 minute probably will cause an error. I need an example of the time ago string (Feltöltve: 123 ??? |) to fix it

**Comment by armani316** [comment]
@kaso17 I'll get back to you on these two points.

**Comment by armani316** [comment]
@kaso17 Initially, I managed to configure this tracker successfully, but now it doesn't pass the test. Enhanced log attached.
[log.txt](https://github.com/Jackett/Jackett/files/806990/log.txt)

**Comment by kaso17** [comment]
don't know why, but you're getting a bonus space.
Should be fixed with c08498d75cbbfd56ccd7e17f61381fc738cfd79a
