### ISSUE TITLE
Xtreme Zone, SceneFZ and Ice Torrent have merged into SpeedApp at https://SpeedApp.io

### ISSUE THREAD

**Issue by Esormit88** [Jackett/Jackett#10226]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Unraid

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.2139.0

**Last Working Jackett Version**: 0.16.2139.0

**Are you using a proxy or VPN?** [yes/no] No

### Description

XtremeZone converted to SpeedApp.io, I am no longer able to use Xtreme Zone from Jackett. When I go to Edit it, it flashes for a half second and quickly reports the error: {"error":true,"message":"Authentication Required"}. Normally, I would be able to edit the address, but the error pops up so quickly, I cannot access the settings window.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by time9x** [comment]
Icetorrent.org and scenefz.me are redirected to the same domain, I can edit the domain from settings and it works after.

**Comment by garfield69** [comment]
IceTorrent, MyXZ and SceneFZ have all merged into SpeedApp according to the web page intro at that domain.
I only had an account for IceTorrent,, so I changed the config to use the new domain and can access the site with that indexer.
This effectively makes the MyXZ and SceneFZ indexers redundant.

@ngosang  your opinion please:
How best to approach this merge?
The issue here is that it is possible that a Jackett user may have 3 uniquely named accounts, one on each of the three sites and potentially has now ended up with three accounts on SpeedApp.

So do we continue with the 3 current indexers (and configs) and just change the indexers code internally to all use a clone of the IceTorrent code,
or come up with something else?

**Comment by garfield69** [comment]
Note: all 3 of the current C# indexers use the same abstract XtremeZoneTracker
All 3 have the same category ids, albeit IceTorrents has slightly different descriptions, whereas MyXZ and SceneFZ are identical. I will update IceTorrent to match current SpeedApp category descriptions.

**Comment by hellcry37** [comment]
up

**Comment by garfield69** [comment]
@hellcry37  wrote:
>up

by this I suppose you mean you can now access speedapp via whichever indexer (XZ, SFZ or IT) you've been using?

**Comment by hellcry37** [comment]
No man, sry, up = I have the issue also. It was usually used on forums to up a topic (to get more attention for a fix).
Have a great day.

**Comment by garfield69** [comment]
In that case, update your jackett to the latest release (currently 0.16.2199)
If contains updates to all 3 indexers that I have made which auto-update the sitelink to speedapp.io
I have tested IceTorrent, and using my IT credentials confirmed that the XZ and SFZ indexers work too.

**Comment by garfield69** [comment]
Note, under the hood, all 3 indexers are exactly the same, and the sitelink points obviously just the one web site.
So you really only need one of the 3 indexers.
The only reason you might use more than 1 is if you used to have different credentials on each indexer, in which case you can continue to use them individually.

**Comment by hellcry37** [comment]
Idd it seem to work OK, choose one of them changed URL to new site URL, put in my user pass and all good. Thanks for your work

**Comment by garfield69** [comment]
Jackett 0.16.2229

**Comment by ilike2burnthing** [comment]
@ngosang / @garfield69 
Notification shown when logging into the site with your username:
```
Logging in with a username is deprecated and will be removed in the future. Please login using your email address.
```

**Comment by garfield69** [comment]
jackett 0.17.11

**Comment by hellcry37** [comment]
thanks for your work

**Comment by garfield69** [comment]
https://speedapp.io/ returns
![image](https://user-images.githubusercontent.com/6933240/152452027-5d752cb7-a33a-4ef2-94ed-899d1ef738d4.png)

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://speedapp.io/ cloudflare Gateway time-out Error code 504

**Comment by ilike2burnthing** [comment]
back up
