### ISSUE TITLE
[arenabg] Exception (arenabg): Relogin failed: Parse error (Test)

### ISSUE THREAD

**Issue by firebull81** [Jackett/Jackett#10234]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.2184.0

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?**: no

### Description

Just stop working.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
The site has changed - https://github.com/Jackett/Jackett/issues/3989#issuecomment-727880109

Make sure you can login to the new site. If not, create a new account, log out and back in again, and re-enter your new details in Jackett.

**Comment by Alexandro77** [comment]
Logged out and logged back in. No change

**Comment by garfield69** [comment]
use the dashboard to trashbin the coinfig.
shutdown and restart the jackett server
then add the config afresh with an edit to update your login credentials anew and click okay.
should be good to go.

**Comment by Alexandro77** [comment]
Dear garfield69, thank you. I have followed your advice, unfortunately no change. The message is the same.

**Comment by garfield69** [comment]
@Alexandro77 Please access your Jackett dashboard and scroll to the bottom and report the version of Jackett you are using.

**Comment by Alexandro77** [comment]
@garfield69  
Jackett Version 0.16.2168.0

**Comment by garfield69** [comment]
The arenaBG indexer update to support the new web site at https://arenabg.com/ was added beginning with v0.16.2173
So 0.16.2168 that you are using is out of date.
Please update your Jackett to the latest version, v0.16.2199 at the time of this post.
