### ISSUE TITLE
Request - Profiles?

### ISSUE THREAD

**Issue by dairefagan** [Jackett/Jackett#10235]
There is something I would like to search for that my normal indexers have not been able to find, so as a once off I would like to enable every index, but there are other use cases for this also, say when a user might want to search for a specific category they only do occasionally.

It seems to do this now after I enable everything using the script - I think I used a script for this before - I will afterwards have to manually disable everything but my favourite indexers which will take some time.

Could you please consider adding this feature, and for the moment is the best solution to manually copy some files and restore them afterwards?

**Comment by ilike2burnthing** [comment]
There are a few open requests along a similar line:
groups - https://github.com/Jackett/Jackett/issues/8884 
tags - https://github.com/Jackett/Jackett/issues/7170
profiles - https://github.com/Jackett/Jackett/issues/4787 (includes a current workaround)
groups - https://github.com/Jackett/Jackett/issues/2185

You can follow these and add your thoughts to one of more of them if you think there's something missing from their suggestions.
