### ISSUE TITLE
Login redirects from https to http

### ISSUE THREAD

**Issue by onionhammer** [Jackett/Jackett#10236]
# Environment

**OS**:
Ubuntu

**Jackett Version**:
Jackett Version 0.16.2173.0

from linuxserver/jackett:latest

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** yes

### Description

When going to /dashboard on https, if the user is not logged in, jackett redirects to http for the login page

**Comment by garfield69** [comment]
Are you talking about try to access the jackett dashboard via the http://127.0.0.1:9117/UI/Dashboard?
Jackett does not support using https for this, as there is no certificate to validate the secure channel.

**Comment by onionhammer** [comment]
@garfield69 I have it behind a reverse proxy for tls termination. The redirect should be a relative path rather than an absolute url

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Reverse-Proxy

**Comment by onionhammer** [comment]
@garfield69 thanks,

This line did it:

```
proxy_set_header   Upgrade $http_upgrade;
```
