### ISSUE TITLE
[req] add torrentproject https://torrentproject.to/ public

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#10239]
torrentproject https://torrentproject.to/ public

**Comment by garfield69** [comment]
#10231

**Comment by garfield69** [comment]
https://torrentproject.to/ returning Doing some maintenance
also need to fix https://github.com/Jackett/Jackett/commit/06cae85ebe0d31885f5591e3eb42e13b0d5167fa#commitcomment-44329856

**Comment by garfield69** [comment]
back online, but still using cloudflare DDoS protection.

**Comment by ilike2burnthing** [comment]
https://torrentproject.to/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrentproject.to/ - ERR_NAME_NOT_RESOLVED
