### ISSUE TITLE
[arenabg] Exception (arenabg): Login failed: No form found on https://arenabg.ch/ using form selector form[action=

### ISSUE THREAD

**Issue by Alexandro77** [Jackett/Jackett#10238]
An error occurred while testing this indexer
Exception (arenabg): Login failed: No form found on https://arenabg.ch/ using form selector form[action="/users/"]: Parse error

Could you please check,
Thank you.

**Comment by Alexandro77** [comment]
Sorry, already reported.

**Comment by garfield69** [comment]
and you followed https://github.com/Jackett/Jackett/issues/10234#issuecomment-729835589 and got it working for you?
