### ISSUE TITLE
[New Tracker REQ] Awesome-HD

### ISSUE THREAD

**Issue by sumofatguy** [Jackett/Jackett#1024]
Indexer Name
awesome-hd

Type
Movies, TV

Indexer URL
https://awesome-hd.me/

Indexer Language
English

Invite
The invite system is currently closed

Note
Awesome-HD is a small HD tracker with 9,500 users

**Comment by armani316** [comment]
@sumofatguy This one will be particularly tough since invites are closed, like you said. Is there a chance you could start a conversation with an Admin/Mod about directly sending an invite to a developer in order to add support in Jackett?

**Comment by sumofatguy** [comment]
I will definitely try! If there is anything else I can do to help, please let me know

**Comment by armani316** [comment]
@sumofatguy Could you get in touch with me on dripdropdeep -at- gmail- dot- com? Might be useful to discuss a couple of things before you approach AHD's staff.

**Comment by kaso17** [comment]
In case you're successful please send the invite to kaso1717 -at- gmail.com and I'll add it.
In case they need whatever kind of proof let me know.

**Comment by Metigoth** [comment]
Radarr has support for Awesome-HD already can you look at its code and implement it?
I can test it for you.

**Comment by kaso17** [comment]
It's limited to search by imdb id and also missing various other parts needed by jackett.

**Comment by RoloSoze** [comment]
@adamwinn Not sure if you're on AHD, but if you are, maybe you could help out with this one.

**Comment by adamwinn** [comment]
@RoloSoze No, I'm not, but I heard they're doing applications soon so hopefully I will be

**Comment by RoloSoze** [comment]
@adamwinn I've been hearing the same for over a month but nothing happened. If they start recruiting somewhere, please let us know. Thanks!

**Comment by adamwinn** [comment]
I can do this one now

**Comment by adamwinn** [comment]
Fixed by #1352
