### ISSUE TITLE
RARBG indexer: no new torrents update

### ISSUE THREAD

**Issue by vichetmam** [Jackett/Jackett#10245]
So long, I use RARBG indexer as it has IMDb, TMDb id along with torrent file. But it looks like there is no new torrent update in feed since yesterday. I hope this is temporary

**Comment by vtruong68** [comment]
I've been experiencing this as well. I can only see cached results from a few days before, but none of the newer results in the last day or so.

**Comment by garfield69** [comment]
We are obliged by the sysop at RarBG to use their API at https://torrentapi.org/ instead of web scraping the web site directly at https://rarbg.to/
If the API server is not getting updated then feel free to contact admit at support@rarbg.to and report.
This is not an issue Jackett can .
