### ISSUE TITLE
[RarBG] the API server is down

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#10247]
Request to https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=jackett_v0.16.2199.0 failed (Error 521) - The tracker seems to be down

**Comment by zeroclash** [comment]
I am having the same issue as well

**Comment by ilike2burnthing** [comment]
Seems to be back up (just its usual rate of failures). Anyone else?

**Comment by garfield69** [comment]
yes, online, and intermittently unable to return search results. (took 5 attempts just to get a keywordless search and 4 to get a mandalorian search returned).
