### ISSUE TITLE
[MTV] Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by just-an-alt** [Jackett/Jackett#10243]
### Environment

**OS**: Debian Linux

**Jackett Version**: Linuxserver.io docker

**Are you using a proxy or VPN?** yes

### Description
When trying to add the MoreThanTV indexer, I get the error "Object reference not set to an instance of an object."

### Logged Error Messages
Full error: https://paste.debian.net/hidden/087d5642/

**Comment by garfield69** [comment]
MTV moved to a new engine but have not completed the transition.
follow #9670 for progress on this topic.
