### ISSUE TITLE
Version number to match repository tag version

### ISSUE THREAD

**Issue by snakyjake1** [Jackett/Jackett#10249]
Can the version number output match the Github repository release version tag?

Expected:
If the GitHub repository tag is "v0.16.2199"
Then `jackett --version` should output `Jackett v0.16.2199`

Not the actual below...

Actual:
`jackett --version` outputs `Jackett v0.16.2199.0`

### Environment

**OS**:
Linux

**Jackett Version**:
v0.16.2199.0

### Description

Version Output:
\# jackett --version
Jackett v0.16.2199.0

Repository Version:
v0.16.2199

**Comment by ngosang** [comment]
I will fix this soon.

**Comment by garfield69** [comment]
Jackett 0.16.2347
