### ISSUE TITLE
Jackett UI not reachable

### ISSUE THREAD

**Issue by Olivier-Levasseur** [Jackett/Jackett#10259]
### Environment

**OS**: MacOS BigSur 11.0.1

**.Net Version**: ??

**Jackett Version**: 0.16.2207

**Are you using a proxy or VPN?**: No

### Description:

Hi guys, I have a problem with Jackett. I cannot access http://127.0.0.1:9117/UI/Dashboard#

I installed Python 3.9 and the last Jackett but I cannot reach the Jacket UI anymore, so I can't view the API Key to put it in the Jackett.json.
Please help, I've tried a lot but I can't solve the problem; when I install Jackett it said "service running", but I cannot reach the Jackett UI on the browser.
If, after installing it, I try to launch "Jackett" file I get this error: "Failed to create CoreCLR, HRESULT: 0x80004005
don't know how to check if it's currently running"

**Comment by garfield69** [comment]
I presume you installed the macos Jackett on BigSur using the instructions at https://github.com/Jackett/Jackett#installation-on-macos ?
I have it running on my win10 Virtualbox BigSur image, so the problem is likely something at your end that is gone astray.

- Jackett does not need Python, it is not a pre-requisite, so not sure why you mentioned it in your report.

- to check if it is running launch your **Activity Monitor** and in its search box type `jac` and if Jackett is active you should see an entry.
![image](https://user-images.githubusercontent.com/6933240/99864200-f5313200-2c06-11eb-9010-7065244d92e1.png)

- logs are usually in the `~/.config/Jackett` folder, so to view the log launch finder, set it to view hidden, with the Cmd + Shift + . (dot), and navigate there to find the `log.txt`
![image](https://user-images.githubusercontent.com/6933240/99864663-928d6580-2c09-11eb-9dd4-7f976b18d953.png)

**Comment by garfield69** [comment]
BTW, I am not a regular macos user, I only start it up rarely to test Jackett on that platform.
A quick google of `Failed to create CoreCLR, HRESULT: 0x80004005` suggests this is a fairly general error which makes it difficult for me to provide a direct answer.
But in general the errors seem to be related to either .NET or a lack of memory.
@thebluepotato  you helped with a macos ticket in the past, can you cast your eye on this one? thanks.

**Comment by thebluepotato** [comment]
Hi! I'd suggest trying to follow the install instructions again. If the script succeeds, then Jackett is running. Keep in mind that on the first launch it might take a little more time to launch fully. To start/stop Jackett manually, you should also check the instructions for macOS. What do you mean exactly by "unreachable"?

**Comment by Olivier-Levasseur** [comment]
> I presume you installed the macos Jackett on BigSur using the instructions at https://github.com/Jackett/Jackett#installation-on-macos ?
> I have it running on my win10 Virtualbox BigSur image, so the problem is likely something at your end that is gone astray.
> 
> * Jackett does not need Python, it is not a pre-requisite, so not sure why you mentioned it in your report.
> * to check if it is running launch your **Activity Monitor** and in its search box type `jac` and if Jackett is active you should see an entry.
>   ![image](https://user-images.githubusercontent.com/6933240/99864200-f5313200-2c06-11eb-9010-7065244d92e1.png)
> * logs are usually in the `~/.config/Jackett` folder, so to view the log launch finder, set it to view hidden, with the Cmd + Shift + . (dot), and navigate there to find the `log.txt`
>   ![image](https://user-images.githubusercontent.com/6933240/99864663-928d6580-2c09-11eb-9dd4-7f976b18d953.png)

Thanks Garfield, so I just found out that I don't have it running :(

But I don't know why, because when I launch "install_service_macos", this is what I got in Terminal:

Last login: Mon Nov 23 23:15:58 on ttys001
home@MacBook-Pro-**** ~ % /Users/home/Archivio\ Apps/Web\ Download\ \&\ co./Jackett/install_service_macos ; exit;
Removing Jackett executable and all .dylib and .dll files from quarantine...
Agent successfully installed and running!
Jackett location: /Users/home/Archivio Apps/Web Download & co./Jackett
Jackett agent:
	path = /Users/home/Library/LaunchAgents/org.user.Jackett.plist
	state = running
	working directory = /Users/home/Archivio Apps/Web Download & co./Jackett
	pid = 56776
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Processo completato]

**Comment by Olivier-Levasseur** [comment]
Thanks Garfield, so I just found out that I don't have it running :(

But I don't know why, because when I launch "install_service_macos", this is what I got in Terminal:

Last login: Mon Nov 23 23:15:58 on ttys001
home@MacBook-Pro-**** ~ % /Users/home/Archivio\ Apps/Web\ Download\ &\ co./Jackett/install_service_macos ; exit;
Removing Jackett executable and all .dylib and .dll files from quarantine...
Agent successfully installed and running!
Jackett location: /Users/home/Archivio Apps/Web Download & co./Jackett
Jackett agent:
path = /Users/home/Library/LaunchAgents/org.user.Jackett.plist
state = running
working directory = /Users/home/Archivio Apps/Web Download & co./Jackett
pid = 56776
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Processo completato]

**Comment by garfield69** [comment]
I don't know much about macos file structure, but I think the spaces between `Web Download & co` and possibly even the `&` may be breaking the script installation attempt.
Can you try creating a folder called `Web_Download_&_co` and seeing if you can installing into that instead?
and if that does not work, drop the ampersand too.

**Comment by Olivier-Levasseur** [comment]
You're Goddamn right. I just put the installation folder on the desktop and now jackett is running and the jacket UI page is reachable again.
Thanks a lot! I was lost, and, as often, the solution was so simple

**Comment by Olivier-Levasseur** [comment]
do you still recommend to keep Python 3.9 installed or I can delete it since on MacOS there's Python 2.7 installed as default?

**Comment by garfield69** [comment]
Could not say, as I don't personally use Python for anything.
If you installed Python 3.9 as a mistaken pre-requisite for installing Jackett then remove it, since Jackett does not need or use Pyhton for anything.

**Comment by Olivier-Levasseur** [comment]
ok, thanks ;)

Since you don't use Python, maybe there's someone else that can help me with this other problem: 
I've now tried to completely delete Python vers 3.9 (following the instructions I found online) but when I try to delete the symbolic links through Terminal I get the error "Permission denied".

This is the string I've used in Terminal: find /usr/local/bin -lname '../../../Library/Frameworks/Python.framework/Versions/3.9/*' -delete
