### ISSUE TITLE
[REQ]jav.so

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#10254]
Public JAV(Japan Adult Video) porn share torrent site.

Search engine and torrent working.

İt have big database and seeding.

https://jav.so

**Comment by garfield69** [comment]
if you search for a dvdid then you get a single result and the details has one magnet, which is good.
but if searching for an actress then you get results that then lead you to the actress's details which has multiple magnets.
which makes this unsuitable for using yaml indexer. it will need to be coded as a c# indexer.

**Comment by ilike2burnthing** [comment]
Error 522 - Connection timed out
