### ISSUE TITLE
1337x is giving magnet links as torrent file

### ISSUE THREAD

**Issue by MichelBaie** [Jackett/Jackett#10263]
It shows a download button and open a magnet uri. Gives problems with some of my services using jackett api, they think they got a torrent file but it's a magnet uri.

**Comment by garfield69** [comment]
Edit your Jackett 1337x config and set the **Download Link** to one of the magnet-to-torrent converters in the pulldown.

But be aware of this caveat: 1337x is using external web services to provide alternates to magnets, and these services can be subject to cloudflare DDoS protection, or other web site events that may prevent the torrent being returned.
Some of these service can return a not-found error for brand new torrents whose magnets were uploaded within the first 4 hours of release.
