### ISSUE TITLE
[yggtorrent] Clearance failed after 10 attempt(s). (Config)

### ISSUE THREAD

**Issue by RAR98** [Jackett/Jackett#10265]
**OS**:
Win10
**Jackett Version**:
0.16.2215.0
**Last Working Jackett Version**:
Don't know
**Are you using a proxy or VPN?** 
No

Just can't the indexer anymore 
" An error occurred while updating this indexer
Clearance failed after 10 attempt(s).
Click here to open an issue on GitHub for this indexer."
the indexer is yggtorrent

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/10192#issuecomment-727054032
