### ISSUE TITLE
implement support for re-captcha on remote servers

### ISSUE THREAD

**Issue by kaso17** [Jackett/Jackett#1026]
Currently the re-captchas can be solved only when accessing jackett via http://127.0.0.1:9117 . For remote access or access using localhost as hostname it doesn't work.
**Update: As of ~24.10.2017 solving captchas via 127.0.0.1 doesn't work either.**

We would have to proxy all re-cpatcha requests through jackett to fix this. Additionally we would have to rewrite the obfuscated javascript code to use the correct host instead of window.location. In order to do that we would have to rewrite the initial request domains to (as we would have to break up HTTPS connection). Not sure if Origin policies or similar might cause bonus trouble too. Overall it looks like a very nasty task.

~~A different approach would be to implement a simple HTTP proxy in Jackett so users could configure it and access a remote jackett instance via the proxy using 127.0.0.1. That might be an easier workaround for the problem.~~

**Comment by kaso17** [comment]
Using a standalone proxy to easily solve the captchas works already: https://github.com/Jackett/Jackett/wiki/Remote-access-via-proxy

**Comment by kaso17** [comment]
Google apparently just disabled the 127.0.0.1 loophole, It's no longer possible to easily solve recaptchas for other sites. Disabled via 3eb7534dddf7104c72fe48e2631a2b0e6c895794

**Comment by Reinhardtwb** [comment]
Any update on this?

**Comment by kaso17** [comment]
I've no plans to work on this anytime soon and I'm not aware of someone else planning so.

**Comment by ldexterldesign** [comment]
https://github.com/Jackett/Jackett/issues/3818

**Comment by garfield69** [comment]
closed. Superseded by connecting to flaresolverr.
