### ISSUE TITLE
Win32/Wacatac.C!ml

### ISSUE THREAD

**Issue by Adduce0x01** [Jackett/Jackett#10271]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.16.2220

**Last Working Jackett Version**: ?

**Are you using a proxy or VPN?** [yes/no]

### Description

Win32/Wacatac.C!ml detected within latest release of windows build:
See: https://www.virustotal.com/gui/file/10abfffec06b0a46c47c8c632767a33b7f6178a7021197dbf85a8fac5e17cbd7/detection

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Clearly a false positive when 1 of 69 reports a trojan.
Safe to ignore.
