### ISSUE TITLE
Add option to send torrents directly to a client

### ISSUE THREAD

**Issue by kaso17** [Jackett/Jackett#1027]
Currently Jackett only allows us to download the torrent locally or to a blackhole directory.

If there are multiple clients it would be nice if we could configure them in Jackett and send them torrents directly.

**Comment by sgmihai** [comment]
+1 would be really nice to have

**Comment by dantebarba** [comment]
+1 this is really needed. I have my transmission client running remotely and I have to copy-paste the magnet link or upload the torrent file to get it to work.

**Comment by garfield69** [comment]
closing as state.

**Comment by YurikaL** [comment]
> closing as state.

Should there be regularly scheduled messages like "+1, still relevant" just to keep issues from being considering stale?

So take this: "+1, still relevant, would be really nice to send torrents directly to the clients via their API"

At least this clients:
Transmission API: https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md
qBittorrent API: https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)
Deluge API: https://deluge.readthedocs.io/en/latest/reference/webapi.html

**Comment by garfield69** [comment]
Its been open since **2017** and no one has contributed a solution to interfacing to torrent clients directly.
The reality is that it is extremely unlikely that it will ever get done.
