### ISSUE TITLE
[Bug] PreToMe not working, Configuration failed: Failed

### ISSUE THREAD

**Issue by Purged** [Jackett/Jackett#1028]
As title says i get this error when trying to add the site, have never had problems before. Hopefully its an quick and simple fix.

Best Regards

**Comment by armani316** [comment]
@Purged It's working fine for me at the moment. Can you enable enhanced logging and post the full log here? Thanks.

**Comment by Purged** [comment]
I am running Jackett Version 0.7.923.0

Feb 03, 2017 09:03:46 PM	Error	Exception in test_indexer

**Comment by kaso17** [comment]
It's redirecting you to https://pretome.info/index.php?page=home&msg=login_locked
(Error: You have exceeded maximum login attempts, therefor your ip address ('XXXX') has been banned.)

**Comment by Purged** [comment]
still not solved.

Feb 05, 2017 07:30:19 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
Feb 05, 2017 07:30:19 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Feb 05, 2017 07:30:19 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Feb 05, 2017 07:30:19 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Feb 05, 2017 07:30:19 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Feb 05, 2017 07:30:19 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Feb 05, 2017 07:30:19 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Feb 05, 2017 07:30:19 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Feb 05, 2017 07:30:19 PM	Info	
ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Feb 05, 2017 07:30:19 PM	Info	
ApiControllerActionSelector SelectAction 
Feb 05, 2017 07:30:19 PM	Info	
AdminController ExecuteAsync 
Feb 05, 2017 07:30:19 PM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Feb 05, 2017 07:30:19 PM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Feb 05, 2017 07:30:19 PM	Info	
DefaultHttpControllerActivator Create 
Feb 05, 2017 07:30:19 PM	Info	
HttpControllerDescriptor CreateController 
Feb 05, 2017 07:30:19 PM	Info	
DefaultHttpControllerSelector SelectController Admin
Feb 05, 2017 07:30:19 PM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Feb 05, 2017 07:30:19 PM	Info	
  http://127.0.0.1:9117/Admin/GetLogs?_=1486318408336
Feb 05, 2017 07:30:13 PM	Info	
AdminController Dispose 
Feb 05, 2017 07:30:13 PM	Info	
AdminController Dispose 
Feb 05, 2017 07:30:13 PM	Info	
  Content-type='application/json; charset=utf-8', content-length=598
Feb 05, 2017 07:30:13 PM	Info	
AdminController ExecuteAsync 
Feb 05, 2017 07:30:13 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync 
Feb 05, 2017 07:30:13 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()'
Feb 05, 2017 07:30:13 PM	Info	
ApiControllerActionInvoker InvokeActionAsync 
Feb 05, 2017 07:30:13 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
Feb 05, 2017 07:30:13 PM	Debug	
IWebClient: Returning OK => 28813 bytes
Feb 05, 2017 07:30:13 PM	Debug	
IWebClient.GetBytes(Url:https://pretome.info/index.php?page=home&msg=login)
Feb 05, 2017 07:30:13 PM	Debug	
IWebClient: Returning Redirect => https://pretome.info/index.php?page=home&msg=login 
Feb 05, 2017 07:30:12 PM	Debug	
IWebClient.GetString(Url:https://pretome.info/takelogin.php)
Feb 05, 2017 07:30:12 PM	Debug	
updating Cookies  => __cfduid=d093df106858d95e4182543038f4e9e5f1486319416
Feb 05, 2017 07:30:12 PM	Debug	
IWebClient: Returning OK => 
Feb 05, 2017 07:30:11 PM	Debug	
IWebClient.GetString(Url:https://pretome.info/takelogin.php)
Feb 05, 2017 07:30:11 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Configure()'
Feb 05, 2017 07:30:11 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='Configure()'
Feb 05, 2017 07:30:11 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Feb 05, 2017 07:30:11 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Configure()'
Feb 05, 2017 07:30:11 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Feb 05, 2017 07:30:11 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Feb 05, 2017 07:30:11 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Feb 05, 2017 07:30:11 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Feb 05, 2017 07:30:11 PM	Info	
ApiControllerActionSelector SelectAction Selected action 'Configure()'
Feb 05, 2017 07:30:11 PM	Info	
ApiControllerActionSelector SelectAction 
Feb 05, 2017 07:30:11 PM	Info	
AdminController ExecuteAsync 
Feb 05, 2017 07:30:11 PM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Feb 05, 2017 07:30:11 PM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Feb 05, 2017 07:30:11 PM	Info	
DefaultHttpControllerActivator Create 
Feb 05, 2017 07:30:11 PM	Info	
HttpControllerDescriptor CreateController 
Feb 05, 2017 07:30:11 PM	Info	
DefaultHttpControllerSelector SelectController Admin
Feb 05, 2017 07:30:11 PM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'

@kaso17
