### ISSUE TITLE
Search only private trackers or only public

### ISSUE THREAD

**Issue by wieluk** [Jackett/Jackett#10289]
Is it possible to categorise indexers ? Or is it somehow possible to change http://localhost:9117/torznab/all to for example http://localhost:9117/torznab/public or http://localhost:9117/torznab/private to only get public or private trackers. Might be a good feature for sonarr/radarr/lidarr users who would like to use jackett as only indexer but also would like to split private and public indexers.

**Comment by ilike2burnthing** [comment]
There are a few open requests along a similar line, most closely #4787 (which includes a current workaround), but also #8884, #7170, and #2185.

You can follow these and add your thoughts to one of more of them if you think there's something missing from their suggestions.
