### ISSUE TITLE
php+curl and accents fail

### ISSUE THREAD

**Issue by diegargon** [Jackett/Jackett#10292]
### Environment

**OS**: Linuix

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.2229.0

**Last Working Jackett Version**:  yes

**Are you using a proxy or VPN?** [no]

### Description
I am developing a app with php that use jacket and sending a request  width php/curl and accents fail.
Without accents works fine.

### Logged Error Messages
Example: Puñales
 Debug Connection id "0HM4G3E2O2M47" bad request data: "Invalid request target: '/api/v2.0/indexers/mejortorrent/results/torznab/api?apikey=THE_KEY&t=search&extended=1&cat=2000&q=pu\xC3\xB1a...'" Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request target: '/api/v2.0/indexers/mejortorrent/results/torznab/api?apikey=THE_KEYc&t=search&extended=1&cat=2000&q=pu\xC3\xB1a...'

Example: Ataúd
Debug Connection id "0HM4G3E2O2M4D" bad request data: "Invalid request target: '/api/v2.0/indexers/mejortorrent/results/torznab/api?apikey=THE_KEY&t=search&extended=1&cat=2000&q=ata\xC3\xBA...'" Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request target: '/api/v2.0/indexers/mejortorrent/results/torznab/api?apikey=THE_KEY&t=search&extended=1&cat=2000&q=ata\xC3\xBA...'

**Comment by diegargon** [comment]
closing investigate more deep probably my fault

**Comment by garfield69** [comment]
yup, `&q=pu\xC3\xB1a...` is clearly not a valid query parm value

**Comment by diegargon** [comment]
yeah my bad sorry.
