### ISSUE TITLE
Newpct indexer fails to tag Spanish Latino Movies

### ISSUE THREAD

**Issue by diegargon** [Jackett/Jackett#10293]
**Jackett Version**: Latest

### Description
Hello

Newpct it's a spanish indexer, but provide media in Spanish Latino 
The indexer
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/NewPCT.cs
(language tag begin on line 554)

Jackett Ignore/Omit the word  Latino in the title, and mark the torrent as  SPANISH when must add
SPANISH LATINO if Latino word found

That cause we download/search a movie/show tagged in Spanish and language is Spanish Latino

**Comment by garfield69** [comment]
The next release of  Jackett due out in about 5 hours or so, will contain a fix. I'll post the version when I publish it.

**Comment by garfield69** [comment]
jackett 0.16.2236

**Comment by diegargon** [comment]
thanks
