### ISSUE TITLE
[rarbg] Could not find releases from this URL (Config)

### ISSUE THREAD

**Issue by gh0sti** [Jackett/Jackett#10294]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:xubuntu

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:0.16.2233.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

adding rarbg gives an error could not find releases for this url

### Screenshots

https://media.discordapp.net/attachments/383688189941907459/780987786060496906/Screenshot_2020-11-24_20-46-09-746.jpg

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/9688#issuecomment-715620689
