### ISSUE TITLE
[zooqle] Exception (zooqle): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s). (Test)

### ISSUE THREAD

**Issue by sbeaudoin** [Jackett/Jackett#10306]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.2240.0

**Last Working Jackett Version**: First time using this indexer.

**Are you using a proxy or VPN?** [yes/no] No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
- Add indexer.
- Click test.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
If you are seeing a cloudflare DDoS protection page when you access the standard Zooqle domain, then use your Jackett dashboard to edit the config and select one of the alternate sitelink proxies, they may work for you.
If none work, then while the Zooqle cloudflare DDoS protection is active, there is nothing you can do with the standard Jackett.
So until the protection is lifted, either use your browser or look into experiment #9029 if you're able/willing to try it.
