### ISSUE TITLE
HD-Only: Scraping language info

### ISSUE THREAD

**Issue by foXaCe** [Jackett/Jackett#1031]
@kaso17 hello, good job thanks

it possible the scraper read the lang info ?

http://imgur.com/a/V15HW

**Comment by itdaboyz** [comment]
That would be awesome!

**Comment by kaso17** [comment]
The API (https://hd-only.org/ajax.php?action=browse&order_by=time&order_way=desc) doesn't include these information. I suggest you ask the hd only site op to include these tags in the API, then it should be easy to add.
