### ISSUE TITLE
[yts] The SSL connection could not be established, see inner exception.: Authentication failed because the remote party has closed the transport stream. (Config)

### ISSUE THREAD

**Issue by shivanand-shetti** [Jackett/Jackett#10319]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:Ubuntu 20.10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono

**.Net Version**: 6.12

**Jackett Version**:0.16.2256.0

**Last Working Jackett Version**:NA

**Are you using a proxy or VPN?** [yes/no] yes

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
on adding indexer yts.mx i get error "The SSL connection could not be established, see inner exception.: Authentication failed because the remote party has closed the transport stream."
[New Text Document (7).txt](https://github.com/Jackett/Jackett/files/5611212/New.Text.Document.7.txt)

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Are you really using a mono Jackett on ubuntu?
Switch to the .net version. far more reliable than mono which can stumble on ssl certs especially the new ones.
Also check you are not being blocked. Open a browser on the same machine as jackett, and access https://yts.mx/api/v2/list_movies.json
You should get a response that start something simimlar to
```json
{"status":"ok","status_message":"Query was successful","data":{"movie_count":23690,"limit":20,"page_number":1,"movies":[{"id":24234," etc etc etc
```

**Comment by garfield69** [comment]
oh, and use the same proxy/vpn when doing the browser test. 
its possible the vpn/proxy is the issue.
