### ISSUE TITLE
[SportsCult] Not yielding any results

### ISSUE THREAD

**Issue by whitesnakeftw** [Jackett/Jackett#10321]
SportsCult doesn't yield any results whatsoever.

Jackett version: 0.16.2269.0

**Comment by garfield69** [comment]
The indexer works for me, so the issue would appear to be at your end.
Please provide a full **enhanced** log with the debug and HTML included and maybe we can figure out what is going on.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
Thanks.

**Comment by whitesnakeftw** [comment]
@garfield69 Yes, problem was on my end. Fixed it by logging in again through Jackett.

Thing is I would have expected a "SportsCult (**Error**)" rather than a "SportsCult (0)" in the "Your search was done using" section, that's what threw me off. In fact, upon testing the tracker, it immediately gave me a login error, so I'm guessing a tracker test is not automatically performed upon searching for something. Not sure if something should be done about this, either way I'm closing the issue. Thanks :)
