### ISSUE TITLE
[extratorrent-it] down - Connection timed out

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#10332]
https://extratorrents.it/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://extratorrents.it/ - Error 503 - Backend fetch failed

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://extratorrents.it/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://extratorrents.it/ - Error 502 - Bad gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://extratorrents.it/ - working
https://extratorrents.it/home (and searches) - SQL Query Error.

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://extratorrents.it/ - working
> https://extratorrents.it/home (and searches) - SQL Query Error.

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://extratorrents.it/ - Error 522 - Connection timed out

**Comment by garfield69** [comment]
https://extratorrent.unblockit.uno/ now redirects to https://extratorrent.st/
however this is a clone with similar skin, but with no home/ page and different internal html

**Comment by garfield69** [comment]
v0.18.432

**Comment by ilike2burnthing** [comment]
https://extratorrents.it/ looks to be back (again) with new torrents being uploaded, but search is broken. Will keep an eye on it to check if it's working (note to self: use a proxy - https://extratorrent.nocensor.work/).

Labelling as down just for ease of remembering to check.

**Comment by garfield69** [comment]
returning SQL Query Error.

**Comment by mrgravy20** [comment]
adding this here to see if this is the same issue as https://extratorrent.st seems to be up and alive

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/10332#issuecomment-879672127

**Comment by 3227122137** [comment]
Hy Sir please check now extratorrent.it not working from one week plz Sir Problem solve Now Thank You

**Comment by 3227122137** [comment]
Hy Sir please check now extratorrent.it not working from one week plz Sir Problem solve Now Thank You

**Comment by ilike2burnthing** [comment]
*.it has been dead for a while, do you mean *.st? If so, it's working fine here.

**Comment by 3227122137** [comment]
Plz sir new domain send me plz thanks alot

**Comment by 3227122137** [comment]
Sorry Sir https://extratorrent.st/ not working pleasae sie extratorrent.it The Real Soloution Now Thank You So much

**Comment by ilike2burnthing** [comment]
Again, *.it is dead, there's just *.st now. If you can't access it, use a proxy or VPN. There are several alternate domains provided in Jackett for *.st, try those, though you may need FlareSolverr installed to use them with Jackett.
