### ISSUE TITLE
[filelist] Error calling provider filelist: Clearance failed after 10 attempt(s). (Config)

### ISSUE THREAD

**Issue by superpsych0** [Jackett/Jackett#10349]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker/Linux

**.Net Runtime**: Mono

**.Net Version**:

**Jackett Version**: 0.16.2284.0

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?** no

### Description

Input the proper login credentials for filelist.io, hit "Test" and was greeted with the error in the subject.

**Comment by garfield69** [comment]
While the filelist cloudflare DDoS protection is active, there is nothing you can do with the standard Jackett.
So in the meantime, until the protection is lifted, either use your browser or look into experiment #9029 if you're able/willing to try it.
