### ISSUE TITLE
[thepiratebay] Request to https://apibay.org/precompiled/data_top100_recent.json failed (Error BadGateway) - The tracker seems to be down. (Config)

### ISSUE THREAD

**Issue by whtdrgn** [Jackett/Jackett#10340]
Anyone else getting this error message this morning?  According to my log started about 6 hours ago.  I have updated Jackett to the latest version but error message is still there.

**Comment by whtdrgn** [comment]
Search didn't pull up the other posts about this issue.

**Comment by garfield69** [comment]
The TPB API server is offline
https://github.com/Jackett/Jackett/issues/9447#issuecomment-736376241
