### ISSUE TITLE
[Bibliotik] Results do not include file type (epub, azw3, mp3, m4b, etc)

### ISSUE THREAD

**Issue by Ayfteyd7Od** [Jackett/Jackett#10342]
### Environment

**OS**:
LSIO Docker Container

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
N/A

**.Net Version**:
N/A

**Jackett Version**:
 Jackett Version 0.16.2274.0 

**Last Working Jackett Version**:
Unknown

**Are you using a proxy or VPN?** [yes/no]
no

### Description
When searching, results are returned without file type. For example a search for "Example Book" might return:
Example Book by Author [2020]
Example Book by Author [2020]
Example Book by Author [2020] [Retail]
Example Book by Author [2020] [Retail]
Example Book by Author [2020]
Example Book by Author [2020] [Retail]

I would instead expect it to return something like:
Example Book by Author [2020] [M4A]
Example Book by Author [2020] [M4B]
Example Book by Author [2020] [EPUB] [Retail]
Example Book by Author [2020] [AZW3] [Retail]
Example Book by Author [2020] [MP3]
Example Book by Author [2020] [MOBI] [Retail]

### Logged Error Messages
No errors in logs. Can provide details logs if required.

### Screenshots
N/A

**Comment by garfield69** [comment]
No one on the team has an account on the site so we cannot improve the indexer without your help.
If you send an invite to garfieldsixtynine -at- gmail.com I can work on this.
If that is not an option, then the next best thing would be for you to supply a dump of the web sites search page HTML.
Its not ideal but better than nothing.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source for details.

**Comment by Ayfteyd7Od** [comment]
Unfortunately, invites are closed.
I saw in a previous issue that @takosine offered to maintain the Bibliotik code. 

I'll see about getting the HTML source. Thanks.

**Comment by garfield69** [comment]
the indexer code does have a filetype selector, but clearly the web sites layout has changed and the selector is no longer pulling out that detail.

**Comment by Ayfteyd7Od** [comment]
Here's an example search that has several formats for a title:
[BiB_Search.txt](https://github.com/Jackett/Jackett/files/5624552/BiB_Search.txt)

**Comment by garfield69** [comment]
yeah, nah. That file does not contain the HTML. Did you follow the instructions in the wiki link?

**Comment by Ayfteyd7Od** [comment]
Yeah, sorry. I'll get you a new one. Thanks again.

**Comment by Ayfteyd7Od** [comment]
[BiB_Search02.txt](https://github.com/Jackett/Jackett/files/5624705/BiB_Search02.txt)
OK. This will hopefully be what you're looking for.

**Comment by garfield69** [comment]
yes, good job. I should be able to use this to update the indexer. I'll post when I'm done.

**Comment by garfield69** [comment]
strange. the html lines up with the selectors in the indexers. you should be seeing the filetype in the titles 
something similar to `Little Fires Everywhere by Celeste Ng [2017] [AZW3] [Retail]`

the only discrepancy I can spot is the sort method, where the indexer by default uses `relevance` but the web site appears to use `@relevance`, and `files` instead of `file_count`

I'll update the sort list in the indexer config section.

In the mean time, as a cross check, can you access your Jackett dashboard, edit the bibliotik config and select `added` as the sort method, then use the indexer and see if you get the expected results?

**Comment by Ayfteyd7Od** [comment]
I changed it to sort: added & tried both asc & desc for order. Result is the same:

Little Fires Everywhere by Celeste Ng [2017] [Retail] |
Little Fires Everywhere by Celeste Ng [2017] 
Little Fires Everywhere by Celeste Ng [2017] 
Little Fires Everywhere by Celeste Ng [2017] [Retail]

**Comment by garfield69** [comment]
Then that suggests that the Jackett indexer is not getting the same html that you see when you access the site with your Browser.
Please turn on the **enhanced** logging, and repeat the test with the Jackett indexer. drag/drop the log.txt file here.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
Thanks.

**Comment by Ayfteyd7Od** [comment]
Here's that debug:
[bib_debug_01.txt](https://github.com/Jackett/Jackett/files/5625331/bib_debug_01.txt)

**Comment by Ayfteyd7Od** [comment]
Here's that debug:
[bib_debug_01.txt](https://github.com/Jackett/Jackett/files/5625356/bib_debug_01.txt)

**Comment by Ayfteyd7Od** [comment]
The debug looks as expected to me, I guess:
```
    <td>
                <span class="title"><a href="/torrents/586160">Little Fires Everywhere</a></span> by <a class="authorLink" href="/creators/136158">Celeste Ng</a>, narrated by <a class="narratorLink" href="/creators/255881">Jennifer Lim</a> (<a class="publisherLink" href="/publishers/504">Penguin Audio</a>) <span class="torYear">[2017]</span>  <span class="torFormat">[M4B]</span> [64 kbps]  [Unabridged]    <br />&nbsp;&nbsp;<span class="taglist"><a class="tagLink" href="/tags/26">fiction</a>, <a class="tagLink" href="/tags/132">literature</a></span>    </td>
```

Forgive me if I have no idea what I'm talking about, but is there a syntax error here in bibliotik.yml?
There's a space between the curly brackets `{ {` in the else statement for `.Result._year`. Is that relevant?

```
    title:
      text: "{{ .Result.booktitle }}"
      filters:
        - name: append
          args: "{{ if .Result.author }} by {{ .Result.author }}{{ else }}{{ end }}{{ if .Result._year }} {{ .Result._year }}{{ else }}{ {end }}{{ if .Result._filetype }} {{ .Result._filetype }}{{ else }}{{ end }}{{ if .Result._retail }} {{ .Result._retail }}{{ else }}{{ end }}"
```

**Comment by garfield69** [comment]
Thanks.

Hmm, the debug log shows the data is there.
```html
<td>
    <span class="title"><a href="/torrents/652063">Little Fires Everywhere</a></span> by 
    <a class="authorLink" href="/creators/136158">Celeste Ng</a>
     (<a class="publisherLink" href="/publishers/97">Penguin Group</a>) 
    <span class="torYear">[2017]</span>  
    <span class="torFormat">[AZW3]</span>       
    <span class="torRetail" title="Retail">[Retail]</span>
    <br />&nbsp;&nbsp;<span class="taglist"><a class="tagLink" href="/tags/26">fiction</a>, <a class="tagLink" href="/tags/132">literature</a></span>    </td>
<td>
```

So given that the indexer has always had the selector for the filetype since the day the indexer was created,
https://github.com/Jackett/Jackett/blob/2cf3c3d101cdd8c8850d65a537a09123573cb7af/src/Jackett.Common/Definitions/bibliotik.yml#L94-L106
(which eliminates the possibility your indexer for some reason was not up to date), then that leaves only changes made by the C# devs to the cardigann processor.

Which may necessitate adjusting the way the indexer is written to handled the optional selectors.
I'll do some research and see if I can figure out what is going on.

**Comment by Ayfteyd7Od** [comment]
So, I was able to fix it by cleaning up the syntax from:
```
       args: "{{ if .Result.author }} by {{ .Result.author }}{{ else }}{{ end }}{{ if .Result._year }} {{ .Result._year }}{{ else }}{ {end }}{{ if .Result._filetype }} {{ .Result._filetype }}{{ else }}{{ end }}{{ if .Result._retail }} {{ .Result._retail }}{{ else }}{{ end }}" 
```
to:
```
       args: "{{ if .Result.author }} by {{ .Result.author }}{{ else }}{{ end }}{{ if .Result._year }} {{ .Result._year }}{{ else }}{{ end }}{{ if .Result._filetype }} {{ .Result._filetype }}{{ else }}{{ end }}{{ if .Result._retail }} {{ .Result._retail }}{{ else }}{{ end }}" 
```

**Comment by garfield69** [comment]
I don't see what has  changed, did you past the same code twice?

**Comment by Ayfteyd7Od** [comment]
There's a space in the wrong place (before `end`):
`{{ if .Result._year }} {{ .Result._year }}{{ else }}{ {end }}`
to:
`{{ if .Result._year }} {{ .Result._year }}{{ else }}{{ end }}`

**Comment by garfield69** [comment]
Oh well spotted!!!

**Comment by garfield69** [comment]
Isn't it funny how the eyes see what the want to see and not what is there.
I cant tell you how many times I read that line and still did not spot that syntax error until you pointed it out ;-D

**Comment by garfield69** [comment]
Jackett 0.16.2284
