### ISSUE TITLE
[New Tracker REQ] FullMixMusic

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#1034]
**Indexer Name**
FullMixMusic

**Type**
Audio

**Indexer URL**
http://fullmixmusic.org/

**Indexer Language**
Hungarian

**Invite**
Sent

**Note**
FullMixMusic is a Hungarian music tracker with over 20K torrents

**Comment by kaso17** [comment]
didn't get the invite

**Comment by armani316** [comment]
@kaso17 Nothing in Spam either?

**Comment by kaso17** [comment]
no

**Comment by armani316** [comment]
@kaso17 Please check your other email now.

**Comment by kaso17** [comment]
received it

**Comment by kaso17** [comment]
added with 69e5f7a59f1dbaaef3eb1c66e5d473f96c4fab97

**Comment by kaso17** [comment]
I hope I translated the rules correct, it's ratio free, isn't it?

**Comment by armani316** [comment]
@kaso17 Yes, it's ratio-free.

**Comment by ilike2burnthing** [comment]
https://fullmixmusic.org/ - Plesk login page

**Comment by ilike2burnthing** [comment]
https://fullmixmusic.org/ showing content of (and using cert for) http://megamixtracker.hu/

@RoloSoze I'm assuming that's not normal?
