### ISSUE TITLE
[mejortorrent] Clearance failed after 10 attempt(s). (Config)

### ISSUE THREAD

**Issue by kaiserssosse** [Jackett/Jackett#10351]
Using Jackett in ubuntu 64bits

**Jackett Version**: 0.16.2284.0

**Last Working Jackett Version**: 0.16.2284.0

**Are you using a proxy or VPN?** no

### Description

Testing error. What I see URL is fine and I test it with http and https but nothing works.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/10322#issuecomment-735423453
