### ISSUE TITLE
[fouducinema] Error: Vous avez oublié d'ajouter les deux nombres! (Config)

### ISSUE THREAD

**Issue by gvigroux** [Jackett/Jackett#10352]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
you need to access your Jackett Dashboard and edit the indexer config and answer the captcha challenge.
The session cookie expired at regular intervals (set by the web site) and so you have to login afresh.

**Comment by gvigroux** [comment]
In fact I cannot create the indexer. During the creation process, i can see the captcha but there is no field to enter the response

**Comment by garfield69** [comment]
You wot?
you see the image in the config but do not have the text box below?
![image](https://user-images.githubusercontent.com/6933240/100936789-eb88c200-3556-11eb-8d79-8976d2e754f9.png)
Something broken?
Here are a few things to try:
- make sure you are on the latest version of Jackett (at the time of this post its  0.16.2284)
- so scroll down to the bottom of your Jackett Dashboard and check your version
- if out of date manually install the latest version over the top
- still not seeing it?
- try flushing your chrome browser cache and refresh (Ctrl + F5)
- still not seeing it?
- use the Jackett dashboard to trash-bin the config
- shutdown and start-up the Jackett service 
- add the indexer afresh

**Comment by gvigroux** [comment]
I was using the 0.16.227X. After an update it's working again!
Thanks a lot
