### ISSUE TITLE
How to change the password CLI

### ISSUE THREAD

**Issue by vipera7** [Jackett/Jackett#10350]
Hello,
I'm trying to change the password using linux commands. I tried the following : 

```
curl 'http://127.0.0.1:PORT/jackett/api/v2.0/server/adminpassword' -H 'Content-Type: application/json' -H 'Accept: application/json, text/javascript, */*; q=0.01' --data-binary '"changeme"'
```

but it does no change. `AdminPassword `is still `null`
The commands return the following (using -v) : 

> 
> * About to connect() to 127.0.0.1 port PORT(#0)
> *   Trying 127.0.0.1...
> * Connected to 127.0.0.1 (127.0.0.1) port PORT(#0)
> > POST /api/v2.0/server/adminpassword HTTP/1.1
> > User-Agent: curl/7.29.0
> > Host: 127.0.0.1:PORT
> > Content-Type: application/json
> > Accept: application/json, text/javascript, */*; q=0.01
> > Content-Length: 13
> >
> * upload completely sent off: 13 out of 13 bytes
> < HTTP/1.1 302 Found
> < Date: Wed, 02 Dec 2020 15:19:36 GMT
> < Server: Kestrel
> < Content-Length: 0
> < Location: http://127.0.0.1:PORT/UI/Login?ReturnUrl=%2Fapi%2Fv2.0%2Fserver%2Fadminpassword
> <
> * Connection #0 to host 127.0.0.1 left intact

Version: v0.16.2284

**Comment by ngosang** [comment]
You need to set the Cookie header in cURL to change the password. Try to use Network tools in the browser (F12) to see the requests when you change the pass. You will see you are sending the cookie (generated when you logged in)
