### ISSUE TITLE
[New Tracker REQ] Majomparádé

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1035]
**Indexer Name**
Majomparádé

**Type**
Movies, TV, Audio, XXX, PC, Books, Console, Other

**Indexer URL**
https://majomparade.eu/

**Indexer Language**
Hungarian

**Invite**
Sent

**Note**
Majomparádé is a fairly large ratioless general Hungarian tracker with almost 60K torrents

**Comment by kaso17** [comment]
invite received

**Comment by kaso17** [comment]
It has 3 different torrent search pages?
What's the difference between "Letöltés" and "Turkáló"?
When do we have to search which (XXX is obvious)?

**Comment by kaso17** [comment]
Added with 621ae19c7da5d5940a2cb5abcb2f306aec9c869c, for now it searches only the "Letöltés" (letoltes.php?tipus=1) page.

**Comment by armani316** [comment]
@kaso17 Letöltés is the list of main/normal torrents. Turkáló is a list of torrents that does not necessarily meet the quality rules/criteria defined by the tracker. They have relaxed the rules to allow users to upload such torrents, but have separated them from the main torrents. I'd say Letöltés & XXX should still be searched by Jackett for the sake of completeness.

This is similar to what GForceTracker #420 #662 does. Some premium torrents - mostly season & series packs known on GFT as Gems - are listed separately from the main/normal list of torrents. It's good that you brought up this point cause I just realized Jackett only searches the main list on GFT, not the Gems list. Can this be fixed?

**Comment by kaso17** [comment]
bf9027f6edd04d077e29e1dec27f9c0a51e20177 adds search across all 3 pages of Majomparádé.
Will fix GFT too.

**Comment by kaso17** [comment]
GFT gems search has been added with 6ec5e11218be471b79a4af59987ebc4c62bea34a
