### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by hotio** [Jackett/Jackett#1036]
The Jackett readme says that mono-devel is a required dependencie, if not using mono-devel, you'll get a warning when starting Jackett. Is it really a requirement? What's in mono-devel that Jackett requires?

Perhaps libmono-cil-dev is also sufficient, like for Sonarr and Radarr?

**Comment by kaso17** [comment]
At some point I tracked down some exceptions to the mono-devel package on debian/ubuntu systems (Some dynamics/reflections stuff seems to be included in that package itself). If you remove it, try using a cardigann definitions tracker (See https://github.com/Jackett/Jackett/tree/master/src/Jackett/Definitions) or a cloudflare javascript challenge protected tracker (e.g. xspeeds). In both cases I got exceptions without having the mono-devel package itself (but all it's dependencies) installed.
On rpm based distributions the mono packaging seems to be slightly different, so results may vary.
