### ISSUE TITLE
[yggtorrent] Clearance failed after 10 attempt(s). (Config)

### ISSUE THREAD

**Issue by Mikl1800** [Jackett/Jackett#10376]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Ultraseedbox
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
Version de Jackett 0.16.2294.0
**Last Working Jackett Version**:
Version de Jackett 0.16.2294.0
**Are you using a proxy or VPN?** [yes/no]
mo
### Description

la connexion fonctionnais très bien, mais après avoir dépassé le ratio, j'ai fait un don de 25euro pour pouvoir reprendre, mais depuis connexion failled donc payement pour rien sur les 2 jours de leech...

### Logged Error Messages

Une erreur s'est produite lors de la mise à jour de cet indexeur. L'
effacement a échoué après 10 tentatives.

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/10192#issuecomment-727054032
