### ISSUE TITLE
encoding issues Ethor

### ISSUE THREAD

**Issue by maxcore** [Jackett/Jackett#1038]
am alone with this problem?

![capture d ecran 2017-02-05 09 35 59](https://cloud.githubusercontent.com/assets/4043787/22626981/e9742716-eb86-11e6-930a-1c57bdbcfcfc.png)

i cant download with sickrage with this name file 

the real name is : Planète Techno S03E14 FRENCH 720p HDTV x264-QuebecRules

**Comment by kaso17** [comment]
they changed to UTF-8
fixed with 36ea355250a6317d9cf6b06d25cd76455f854640

**Comment by maxcore** [comment]
@kaso17 thx for you fast fix ;)
