### ISSUE TITLE
core: improve search cache

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#10382]
The current search cache is useless, it's just wasting memory and it's not solving the issue of making less requests.

I have to think a bit but the main idea is to cache `query + response + timestamp`. The same query (indexer + search term + categories..) should return the same response. The only exception is if the indexer return an error. In that case the result is not cached.

Make it configurable:
* MaxAge / TTL => How long the results are in the cache (eg 15 min). That means if you make the same request to Jackett several times you will make just 1 request each 15 minutes.
* Max records => How much results could be in the cache at maximum (limit memory usage)
* Disable cache => To reduce memory usage and for development

Nice to have:
* Show in the response if the results come form the cache or a live request. This can be helpful for debug/development.
* Disable cache if enhanced log is enabled?
* Make configurable cache strategy. You can choose to keep the cache memory as low as possible or keep as many results as possible in the cache (to use the "cache search" feature in the web UI).

Related #7069

**Comment by ngosang** [comment]
@xfouloux fyi

**Comment by ilike2burnthing** [comment]
Would we want to have Jackett clear the cache as a whole when making a change to the proxy settings? Basically to see if the proxy changes are causing new failures.

**Comment by xfouloux** [comment]
I guess this would be a good thing to do it yeah, of have a force clean cache button next to the proxy box ?

**Comment by ilike2burnthing** [comment]
In `View cached releases`, do we want to keep the 300 releases per indexer limit?

**Comment by xfouloux** [comment]
Also, if not too much trouble,

have a clean cache button right after the test button for each indexer, with a hover info bubble giving the number of cached torrent for this indexer, and if clicked clearing only this indexer cache

instead of clearing the whole cache, would be a great addition (visible only if cache if checked ?)

**Comment by ilike2burnthing** [comment]
@ngosang any thoughts on these?
> Would we want to have Jackett clear the cache as a whole when making a change to the proxy settings? Basically to see if the proxy changes are causing new failures.

> In `View cached releases`, do we want to keep the 300 releases per indexer limit?

**Comment by ngosang** [comment]
> Would we want to have Jackett clear the cache as a whole when making a change to the proxy settings? Basically to see if the proxy changes are causing new failures.

I can fix that.

> In View cached releases, do we want to keep the 300 releases per indexer limit?

This limit is due to Jackett UI does not have pagination and it's not able to show all results in the browser. There are 2 limits in the code:
* Max 300 results per indexer
* Max 3000 results in total
I have a lot of ideas for the UI but I'm not a frontend developer.

**Comment by ngosang** [comment]
Proxy thing is fixed in #10484
About the other question, what do you want to do?

**Comment by ilike2burnthing** [comment]
Thanks.

As for the 300 releases per indexer limit, I thought this might have been a previously set artificial limit which we could change to match those now set by the user (so if the default of 1000 was used, 1000 would be shown). I'm not sure it will really make much of a difference to the average user, and 300 seems like plenty, so I don't think it needs changed unless you have an easy fix in mind.

**Comment by ngosang** [comment]
There is not an easy fix. Anyway I think the cache view in the UI is pretty useless.

**Comment by ilike2burnthing** [comment]
```
- Disable cache if enhanced log is enabled?
```
@ngosang was this implemented? Just asking so I know whether to tell users to disable cache during troubleshooting.

**Comment by ngosang** [comment]
> @ngosang was this implemented? Just asking so I know whether to tell users to disable cache during troubleshooting.

No, cache and enhanced logs are different things. I can't disable cache in debug mode because if I do it I can't debug the cache issues. :smile: 
We should update the WIki => https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
In most cases the user will have to disable the cache + enable enhanced login. If the issue is in the cache, could be interesting to get the logs with and without cache (but that is an exception).

**Comment by ilike2burnthing** [comment]
added - https://github.com/Jackett/Jackett/wiki/Troubleshooting/_compare/aaaf58428c404521968e0fa11f357444f3ceba4c...a5f1f6b454d803de6ce1b1dde48dba871fe537c0

**Comment by ngosang** [comment]
thanks!
