### ISSUE TITLE
Copy feed buttons do not work on FF or Chrome (tested on Linux)

### ISSUE THREAD

**Issue by salimfadhley** [Jackett/Jackett#1039]
Jackett version:  0.7.983.0
Mono version (if not using Windows):  0.7.983.0

When I click on either button no feed is copied. There is nothing in the Javascript console to indicate that the button actually did anything. The clipboard content is unmodified.

**Comment by kaso17** [comment]
I tested it on Archlinux with firefox/google-chrome/chromium and all are working fine.
Can you please try it with an empty profile (no plugins/extensions)?
I changed the buttons to links with 75d8ba0bf24cf184cd4c71139728d670dcbf4171 anyway so you should be able to use the context menu/copy link feature of your browser as a workaround.

**Comment by armani316** [comment]
@kaso17 Should we close this issue since you've fixed it with a workaround?

**Comment by salimfadhley** [comment]
Thanks @kaso17 - the Seedbox service I use will update the version of Jackett shortly. If that doesn't fix the problem I will reopen.
