### ISSUE TITLE
[REQ] New tracker request: Digital Hive

### ISSUE THREAD

**Issue by altrhombus** [Jackett/Jackett#104]
Greetings!
Could I request adding https://www.digitalhive.org as a tracker? I can provide an invite upon request.

Thank you so much!

**Comment by raspdealer** [comment]
https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker

**Comment by conihorse** [comment]
Site uses reCapcha validation, so automated access not viable

**Comment by JigSawFr** [comment]
I've seen some trackers with ReCapatcha validation integrated in Jackett, so in my mind it could be possible.

**Comment by ipsq** [comment]
I'd love this! They use the same authentication scheme as BeyondHD.

**Comment by ipsq** [comment]
The login can be completely copied from BeyondHD. Only the search needs to be implemented. I don't have a Windows PC at hand so I can't implement this with IDE support but maybe I can just try and see if it compiles.

**Comment by ipsq** [comment]
#171

**Comment by Riz0** [comment]
@kaso17 @chibidev   I can't add this indexer at all, when selecting the configure icon in the indexer submenu it just redirects to Jackett's homepage but doesn't present any dialog box to enter login details. No issues logging into the actual site and enhanced logging doesn't provide any telling errors. 

I'm on latest pre-release version 0.8.190.0. Any ideas?

**Comment by kaso17** [comment]
should be fixed via 634a860f5c423e1b1920c851dd635d63b3a07289
Seems like they made the recaptcha optional or removed it completely.

**Comment by ilike2burnthing** [comment]
https://www.digitalhive.org/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
```
Well, it's been a really good run. We are 1 month shy of our 15th birthday. Last
month, we received $70 in donations, which we are grateful for, but obviously it
wasn't enough. This is the end of our journey. We would like to thank all of our
users over the last 15 years for their support and patronage and donations.

One of our members has offered to set up a discord server so everyone who wants
to, can keep in touch. We'll update this with the link to that shortly.

From the Staff at DH, we wholeheartedly will miss everyone and maintaining the
site and interacting with everyone involved. Thank you!
```
https://torrentinvites.org/f31/digitalhive-dh-news-site-shutting-down-569397/

**Comment by garfield69** [comment]
Jackett 0.16.1709
