### ISSUE TITLE
[New Tracker REQ]  Torrentz2

### ISSUE THREAD

**Issue by lukasmrtvy** [Jackett/Jackett#1040]
Indexer Name
Torrentz2

Type
Movies, TV, Audio, XXX, Programs (PC/Mobile/Mac), Books, Console, Other

Indexer URL
https://torrentz2.eu/

Indexer Language
Eng

Invite
Public

Note
Look at all indexed tracker, all you need is add this https://torrentz2.eu/help and maybe karcr.co

**Comment by armani316** [comment]
I am also aware of the following meta indexer. I think it indexes slightly fewer public trackers, but it might also be worth looking at, Both Torrentz2 & TorrentzEU are successors of the old Torrentz.

https://torrentzeu.to/

**Comment by muhahacz** [comment]
https://torrentzeu.to/ does not support functionality of torrentz2.eu, has smaller db. 
Python example of using torrentz2:
https://github.com/SickRage/SickRage/blob/4cc00e51a62cb2a19ff9ddea2390c1cde16efc3b/sickbeard/providers/torrentz.py

**Comment by kaso17** [comment]
Added with 2b7f9c610ed972cb006a5c5f149075ac8a06495a

Thank you @zductiv (#1042) and @scambra

**Comment by kaso17** [comment]
For now this indexer will only generate a magnet link with the infohash. No trackers are included, it fully relies on DHT. If someone can provide a list of the most popular trackers used by the indexers crawled by torrentz2 we can add them all.

**Comment by armani316** [comment]
I see that the only categories that have been added in Jackett are Movies, Movies HD & TV. Torrentz2 indexes all types of torrents, and I'm actually able to find torrents that belong to other categories if I search Torrentz2 in Jackett. Is there a plan to add other categories?

**Comment by kaso17** [comment]
If you collect the missing category mappings it can be added. It's based on the string after the torrent name, see the caps/categories section in the definition for an example.

**Comment by kaso17** [comment]
@zductiv added more categories with #1047

**Comment by muhahacz** [comment]
Iam using Docker file from LinuxServer.io

Request
`http://192.168.0.251:9876/potato/torrentz2?imdbid=tt2404435&search=The+Magnificent+Seven+2016&user=&passkey=rn353aaizbs35dzavyurm1sqcla75ura`

Response
```
{
  "results": [],
  "total_results": 0
}
```

Log
`Found 11 torrentpotato releases from Torrentz2 for: The Magnificent Seven 2016`

**Comment by kaso17** [comment]
The torrentz2 indexer only provides magnet links, but these are filtered by the couch potato provider with the comment "Only accept torrent links, magnet is not supported". Does CouchPotato support magnet links by now?

**Comment by muhahacz** [comment]
Well, you can access torrent like this:
http://itorrents.org/torrent/{hash}.torrent

**Comment by kaso17** [comment]
This doesn't seem to work for all torrents.
I tried e.g. http://itorrents.org/torrent/5D1EC66291A7156B890157F822D8FD314B0AF688.torrent and get redirected to limetorrents. Not going to implement it if it's not working 100%. Couch Potato would have to do implement the magnet to torrent file conversion.

**Comment by muhahacz** [comment]
This is another service, but it might not be working for all torrents.. 
https://thetorrent.org/5D1EC66291A7156B890157F822D8FD314B0AF688.torrent

**Comment by kaso17** [comment]
Seems to be incomplete too.
Anyway, I added optional (must be enabled in the settings first) download links for itorrents via c923055bbf0526f98b9b08d1d8232fc38b14e64c

**Comment by muhahacz** [comment]
Another caching services:
http://torrage.info/torrent.php?h=5D1EC66291A7156B890157F822D8FD314B0AF688

Torrent Not found
http://btcache.me/torrent/5D1EC66291A7156B890157F822D8FD314B0AF688

Is possible to add these as alternatives ? Is it hard to implement?

**Comment by kaso17** [comment]
You could implement it like I did for itorrents, but then you would have to decide for one (can return only one link).
I've opened #1063 for a more generic approach.

**Comment by muhahacz** [comment]
Can you please try GET to http://192.168.0.251:9117/potato/torrentz2?search=Felon&user=&passkey=jgxui4mvci6ucpfcviy6o1ok0u6h2qxp on latest version?

I get 0 returns in response in browser

```
{
"results": [],
"total_results": 0
}
```

Jackett logs:
```
Feb 16, 2017 12:59:02 PM	Info	
Found 13 torrentpotato releases from Torrentz2 for: Felon
```

**Comment by kaso17** [comment]
With "Add download links via itorrents.org" enabled I'm getting 13 releases, without 0 (due to magnet links)

**Comment by muhahacz** [comment]
Couchpotato should handle magnet url:
https://couchpota.to/forum/viewtopic.php?f=5&t=51391

manget url in download_url in json response should be OK.

**Comment by kaso17** [comment]
With c3c8ec980196fac8a6ff07e545e9bdaed942fa65 manget URLs are now enabled for potato feeds

**Comment by garfield69** [comment]
https://torrentz2.eu/ offline

**Comment by garfield69** [comment]
back online.

**Comment by jeff15110168** [comment]
offline for me

**Comment by ilike2burnthing** [comment]
https://torrentz2.is/ and proxies - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrentz2.is/ https://torrentz.pl/ https://torrentsmirror.com/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrentz2.is/ https://torrentz.pl/ https://torrentsmirror.com/ - Error 503 - Service Unavailable

**Comment by ilike2burnthing** [comment]
https://torrentzwealmisr.onion.ly/ - ERR_CONNECTION_REFUSED

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrentzwealmisr.onion.ly/ - Error 503 - Service Unavailable

**Comment by ilike2burnthing** [comment]
back up (but slooooow)

**Comment by ilike2burnthing** [comment]
https://torrentzwealmisr.onion.ly/ - Error 504 - Gateway Time-out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://torrentzwealmisr.onion.ly/ returning Error accessing resource: 503 - Service Unavailable

**Comment by garfield69** [comment]
alternate link https://torrentz.unblockit.buzz/ is also broken.

note: the indexer's third and last alternate link is for https://torrentz2.unblockninja.com/ 
however, this is for a torrentz2eu clone, which uses a different search engine and results html.
https://torrentz2.unblockninja.com/data.php?q=simpsons

in the event that this indexer's primary and secondary site links does not come back, I guess we can always switch to this clone at some point.

**Comment by ilike2burnthing** [comment]
The unblockninja proxy is for https://torrentzeu.org/ - https://github.com/Jackett/Jackett/issues/10959

I'll remove this indexer (along with several others which have now been down for 30 days), and then if someone wants to create an indexer for the clone, see the issue for it above.
