### ISSUE TITLE
xthor: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#10407]
![image](https://user-images.githubusercontent.com/10577978/101291725-3a5e8200-380b-11eb-8c3e-89764fc238cc.png)

**Comment by garfield69** [comment]
you're the only one of the team that has an account, so this one is yours ;-b

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/112058402-d910b380-8b5a-11eb-8130-6acad2894959.png)

**Comment by garfield69** [comment]
you're the only one of the team that has an account, so this one is yours ;-b

**Comment by garfield69** [comment]
v0.17.788
