### ISSUE TITLE
TV-Vault No Results

### ISSUE THREAD

**Issue by Paul5656** [Jackett/Jackett#10412]
When searching TV-Vault from Jackett no results are found if you select 5000 (TV) category for shows posted as TV/​SD Category.  Therefore no results from sonarr for any show posted on TVV as TV/​SD.

**Comment by ilike2burnthing** [comment]
@RoloSoze can you confirm this issue?

**Comment by garfield69** [comment]
the indexer only has two categories defined 2000(movies) and 5000(tv)
if the web site has added new categories then we need to see a dump of the torrent search page so we can update.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source for details.

**Comment by RoloSoze** [comment]
> 
> 
> @RoloSoze can you confirm this issue?

Apologies for the late response. I cannot seem to replicate this problem on my end. @Paul5656 Are you able to provide an enhanced log showing this issue?

**Comment by Paul5656** [comment]
@RoloSoze @garfield69
https://thesungod.xyz/AQySL_O-.jpeg
https://thesungod.xyz/Illdqtdt.jpeg
Take a look at the screenshot in the links provided. The tracker recognizes files posted as (XXX/YYY/ZZZ/**DVD**) as TV/SD. All other files appear as TV Category just not DVD sourced files.

**Comment by garfield69** [comment]
@Paul5656  No one on the team has an account on the site.
Please provide a full **enhanced** log with the debug and HTML included and maybe we can figure out what is going on.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
Thanks.

**Comment by RoloSoze** [comment]
> 
> 
> @Paul5656 No one on the team has an account on the site.
@garfield69 Actually, @ngosang does! Would you be able to help with this issue?

**Comment by garfield69** [comment]
Does he! Well dang, looks like its about time he reviewed the indexer-accounts spreadsheet and brought it up to date ;-).

**Comment by Paul5656** [comment]
@garfield69 does jackett have a discord support channel. I was trying to avoid posting logs on git incase I fail to redact all personal details, username, password, passkey, hashes, IP address etc. from them. If ngosang doesn't come through then I'll post them.

**Comment by garfield69** [comment]
If you prefer, once you get tired of waiting, just send the log direct to  garfieldsixtynine -at- gmail.com ;-)

**Comment by Paul5656** [comment]
@garfield69 I just sent them. If you need additional info from me you can just ask via email. Thanks. :)

**Comment by garfield69** [comment]
Try out Jackett v0.17.87 and report if that helps.

**Comment by Paul5656** [comment]
Works perfectly now. Thanks for your service.
