### ISSUE TITLE
[yggtorrent] Clearance failed after 10 attempt(s). (Config)

### ISSUE THREAD

**Issue by starcraft04** [Jackett/Jackett#10428]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:v0.16.2347

**Last Working Jackett Version**:v0.16.2347

**Are you using a proxy or VPN?** [yes/no]no

### Description

trying to test YGGTorrent

### Logged Error Messages

Clearance failed after 10 attempt(s).

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/10192#issuecomment-727054032
