### ISSUE TITLE
No index  - No data available in table 

### ISSUE THREAD

**Issue by Oz246** [Jackett/Jackett#10442]
Hello,

when i do an index search i have no results with the message:

No data available in table

I did a test with the last 5 versions and the result is identical

I tested the mono, x64 and 32 version.

the logs load indexers well

An idea ?

Thank You 

OS : 

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

![Jackett](https://user-images.githubusercontent.com/25376126/101454136-c4543b00-3930-11eb-8b3d-7d0830d98648.JPG)

**Comment by ngosang** [comment]
You have to configure some indexers first. Click "Add indexer"
![image](https://user-images.githubusercontent.com/10577978/101478600-36d51300-3951-11eb-9bd1-f0f1496393e9.png)

**Comment by Oz246** [comment]
I confirm that the screen corresponds to an add indexer click

**Comment by ngosang** [comment]
Ok. If you can see the indexers are loaded in the logs, this must be a browser thing.
Which browser do you have? You have ad-blockers or browser plugins? Disable the plugins for Jackett or try to investigate in the browser console F12

**Comment by Oz246** [comment]
shame on me I didn't even think of doing a test in this direction.

I close the file thanks to your solution a very very very big thank you to you !!
