### ISSUE TITLE
[yggcookie] Exception (yggcookie): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s). (Test)

### ISSUE THREAD

**Issue by xyko0** [Jackett/Jackett#10446]
Hello,
Thanks for your help. I didn't find any other issue from last days :( 

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 

**Jackett Version**: v0.16.2374

**Last Working Jackett Version**: idk

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

My conf just goes down a few days ago. I tried to re-configure from scratch but still display " An error occurred while testing this indexer
Exception (yggcookie): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s)."

### Logged Error Messages
Exception (yggcookie): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s)."

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots
![image](https://user-images.githubusercontent.com/52315700/101489958-f6ca5c00-3961-11eb-8c89-524fd49d9887.png)

[Place any screenshots of the issue here if needed]

**Comment by xyko0** [comment]
Hi,

Thanks for quick reply, but I dont think this is the same issue because it worked like last week :/
Are you sure you don't mean yggtorrent ?

**Comment by garfield69** [comment]
While the YGG cloudflare DDoS protection is active, there is nothing you can do with the standard Jackett.
So in the meantime, until the protection is lifted, either use your browser or look into experiment #9029 if you're able/willing to try it.

**Comment by xyko0** [comment]
Cloudflare protection was active last week but it worked ...
Using the cookie was allowing us to make research with the indexer yggcookie
I'll wait then
Thnks
