### ISSUE TITLE
[New Tracker REQ] arabafenice.me

### ISSUE THREAD

**Issue by memnos** [Jackett/Jackett#1044]
Indexer Name
Arabafenice

Type
Movies, TV, Anime, Books, Games, Software

Is the indexer private or public? If private, can you provide an invite?
Private, i can provide invitation

Indexer URL
w*w.arabafenice.me

Indexer language
Italian

**Comment by kaso17** [comment]
please send an invite to kaso1717 -at- gmail.com

**Comment by memnos** [comment]
Invite sent

**Comment by fbrassin** [comment]
Hi, can you tell me if you received invitation?
Tnx

**Comment by memnos** [comment]
@kaso17 
Can you tell me if you received invitation?
Tnx

**Comment by kaso17** [comment]
got it, thank you

**Comment by memnos** [comment]
Well, i hope it can help

**Comment by kaso17** [comment]
added with 08efe3c6b5cbb8490ca587a728871047d20119c4

**Comment by dpmdiego** [comment]
@memnos ,
Could you send me an invitation too? Thank you very much.

imdiegodpm@gmail.com

**Comment by ilike2burnthing** [comment]
yes, though this isn't the place to ask
