### ISSUE TITLE
[film-paleis] Login failed: Selector

### ISSUE THREAD

**Issue by thoogveldHU** [Jackett/Jackett#10450]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: UnRaid (Linux)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] x

**.Net Version**: x

**Jackett Version**:  v0.17.11

**Last Working Jackett Version**: None

**Are you using a proxy or VPN?** yes

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Open Jackett
Add Indexer -> Film-Paleis.me (Dutch private Tracker)
Add (w or w/o coockie)
Error

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

An error occurred while updating this indexer
Login failed: Selector "a[href="logout.php"]" didn't match

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
The indexer works for me which suggest the problem is at your end.
Have a good read of https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work, and in particular check the notes in case it applies to you.
