### ISSUE TITLE
Torznab link not working for search on YTS indexer

### ISSUE THREAD

**Issue by cmcmillan77** [Jackett/Jackett#10453]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker/linux

**Jackett Version**:  v0.17.11

**Are you using a proxy or VPN?** no

### Description

Using the Torznab link for YTS in radarr, the search function throws an error.  Curling the search link directly throws the same error.  Manual search is fine within jackett, and if I alter the url the search works.  

http://xxx.xxx.xxx.xxx:9117/api/v2.0/indexers/yts/results/torznab/api?t=movie&cat=2000&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=0085936

### Logged Error Messages

`<error code="900" description="Jackett.Common.IndexerException: Exception (yts): API error, movies missing ---> System.Exception: Parse error ---> System.Exception: API error, movies missing at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query, Int32 attempts) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/YTS.cs:line 127 --- End of inner exception stack trace --- at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 686 at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query, Int32 attempts) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/YTS.cs:line 199 at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/YTS.cs:line 76 at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 394 --- End of inner exception stack trace --- at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 394 at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 663 at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 447"/>`

**Comment by garfield69** [comment]
The YTS Jackett indexer works me for me with Radarr, so the issue appears to be at your end.
Try accessing your Radarr indexer with the **show advanced** option enabled, and changing the categories list to `2000,2040,2045,2060` which is all the movie cats that the YTS web site supports.

**Comment by cmcmillan77** [comment]
Ok, Strange.  It seems like it is broken when searching for the movie I was looking for, but not others.  Try adding Mickey's Christmas Carol (1983) and then searching for it.  It breaks and causes radarr to say the indexer is unavailable.

**Comment by garfield69** [comment]
So Sonarr sends this query to Jackett
https://yts.mx/api/v2/list_movies.json?sort=date_added&limit=50&query_term=tt0085936
and the YTS API responds with
```JSON
{"status":"ok","status_message":"Query was successful","data":{"movie_count":1,"limit":50,"page_number":1},"@meta":{"server_time":1607538110,"server_timezone":"CET","api_version":2,"execution_time":"0 ms"}}
```
So the issue is with the YTS API, which states it found a movie (movie_count=1) but then does not deliver the movie details.
So this is a YTS API server issue and there is nothing Jackett can do about it.
The indexer was promised 1 movie result, and then was not given that movie detail, so the indexer rightly claims an error occurred.

**Comment by cmcmillan77** [comment]
Thanks!
