### ISSUE TITLE
Synology DS220j Ssl error:0f000078:elliptic curve routines:OPENSSL_internal:POINT_IS_NOT_ON_CURVE  at /spksrc/spk/mono/work-rtd1296-6.2.2/mono-6.8.0.105/external/boringssl/crypto/ec/ec.c:835: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by Colezy09** [Jackett/Jackett#10451]
### Synology DS220j

**OS**:DSM 6.2.3-25426 Update 2

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono 6.8.0.105-14

**Jackett Version**:0.16.1340-12

**Are you using a proxy or VPN?** [yes/no] Tired with and without the VPN

### Description

Clean install of Mono and Jacket. Any index added shows the error.

**Comment by garfield69** [comment]
Previous tickets with the *eliptic* error show that this is usually a mono issue.
Either upgrade (or downgrade) your version of mono.
