### ISSUE TITLE
[thepiratebay] The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject]  CN=*.prod1.shp.mcafee.com, OU=Enterprise SSL Pro Wildcard, OU=Hosted by McAfee Inc., OU=Engineering, O=

### ISSUE THREAD

**Issue by LXCRD** [Jackett/Jackett#10456]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Your mcafee anti-malware app is blocking your access to the API server for TPB.
So white list https://apibay.org/ on whatever security app your running and you should be good to go.
