### ISSUE TITLE
[REQ] New public tracker - madeintorrent

### ISSUE THREAD

**Issue by alceasan** [Jackett/Jackett#10455]
I'd like to have this public tracker on Jackett for Spanish content (we have so few working :( ).

- Site address: [https://www.madeintorrent.com](https://www.madeintorrent.com)
- Site type: public
- Contents: films, TV series, games, music, ...
- Language: Spanish (es-es)
- Additional notes: multiple torrents per title (different qualities), provide direct link to .torrent file (no magnet).

**Comment by garfield69** [comment]
The one-poster-many-torrents means this indexer will need to be written on C# as cardigann can only handle 1-to-1 results.
As an added bonus, this site is sooooo slow. its probably going to time out the await-results timer.

**Comment by XYZJR** [comment]
I'm getting lots of 500 Internal Server Errors on this site.

**Comment by 97carmine** [comment]
It should be closed, the website redirects at https://www.reinventorrent.com/ #11648

**Comment by garfield69** [comment]
okely dokely.
