### ISSUE TITLE
Tracker request: Extratorrent

### ISSUE THREAD

**Issue by zductiv** [Jackett/Jackett#1046]
Now that jackett is supporting public trackers, it would be good to add extratorrent.cc. Javascript obfuscation of results might make this a little more difficult. Not sure if jackett already has something to deal with this.

Previously closed: #852, #544.

Related: cardigann/cardigann#281, cardigann/cardigann#9 + others

**Comment by kaso17** [comment]
It's AES encrypted with an obfuscated key.
I tried just using anglesharp with jint for javascript but it doesn't seem to handle the JS very well.
Will continue looking into this. Worst case we've to re implement CryptoJS AES decoding in c#

**Comment by armani316** [comment]
@kaso17 For public trackers that are indexed by Torrentz2 (see #1040), do we really need to add Jackett support for them separately? If Torrentz2 scans them already, wouldn't adding ExtraTorrent - which is already indexed by Torrentz2 - result in duplicate search results in Jackett? 

List of public trackers indexed by Torrentz2 (TorrentProject #897 #1045 is also included):
https://torrentz2.eu/help#indexed

**Comment by zductiv** [comment]
Torrentz2.eu says that it indexes extratorrent, but from the searches I've tested it doesn't work.

Perhaps it was from before extratorrent added the encryption.

**Comment by armani316** [comment]
@zductiv Makes sense! That could be the reason.

**Comment by kaso17** [comment]
I'm able to get the necessary decryption key without JS now and generate JS code which decrypts the table. Just need to replace the cryptoJS AES implementation with a native c# one now.

**Comment by kaso17** [comment]
I've a working decryption (without having to run JS) for their ajax_checker key obfuscation method. But they just changed the key obfuscation method to key construction from inline obfuscated JS which is very easy to circumvent with JS parser but I'm not yet ready to add that dependency to jackett at this time. Will continue to observe the situation for now.

**Comment by RoloSoze** [comment]
@kaso17 Any updates on this one?

**Comment by jeramie72** [comment]
would be a great one to add if possible, too bad they are making it a pita

**Comment by kaso17** [comment]
since I last checked (a long tie ago) it definitely changed again. Looks like we need a full blown JS interpreter to deal with the constant changes. I'm not yet ready to put that much effort into it yet.

**Comment by zductiv** [comment]
Extratorrent is closed for good.
