### ISSUE TITLE
Idea: Indexer Groups?

### ISSUE THREAD

**Issue by STaRDoGG** [Jackett/Jackett#10467]
No idea how "possible" this is currently, as far as how difficult it would be to add, but what if:

1. We could create "indexer groups" in Jackett
2. Add any number of indexers to the group
3. Then in other software, (radarr, sonarr, hydra, etc.) we could just add a single link to the "indexer group", and any searches sent to that link will automatically search any indexers added to that group.

This would make indexer management _much_ easier than having to 1-by-1 add each indexer individually to each *arr, and since indexers seem to die constantly, and new ones pop up, we have to go into all of those and again individually manage them.

With the suggested Indexer Groups, we would never have to manage all the indexers in the other software once the group link was added to them; we'd just hop into the Jackett UI and manage the indexers in the group there.

It may or may not also require all of those other software to make changes to accompany the results as well, but the (the authors) may also find it a welcome change.

Of course, also keep the current ability to link to individual indexers as well if the user wants to do so.

**Comment by ilike2burnthing** [comment]
There are a few open requests along a similar line:
groups - #8884
tags - #7170
profiles - #4787 (includes a current workaround)
groups - #2185

You can follow these and add your thoughts to one of more of them if you think there's something missing from their suggestions.

**Comment by STaRDoGG** [comment]
> There are a few open requests along a similar line:
> groups - #8884
> tags - #7170
> profiles - #4787 (includes a current workaround)
> groups - #2185
> 
> You can follow these and add your thoughts to one of more of them if you think there's something missing from their suggestions.

Sounds good. Just curious though; how does the idea sound to you? ;)

**Comment by ilike2burnthing** [comment]
Sounds good, users will just need to be aware that when using multiple indexers in a group (e.g. Public, Spanish, My Favourites, etc.), not all of them will have the same categories, so if trying to use something like Sonarr, setting it to just use TV (5000) is going to be a lot safer than trying to search for TV/HD or something specific.

Whether that's done just by adding a note to the UI, or limiting available categories, will need to be decided when implemented.
