### ISSUE TITLE
[iptorrents] Your cookie did not work: Found 0 results in the tracker (Config)

### ISSUE THREAD

**Issue by Paradoxum** [Jackett/Jackett#10461]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Freenas Version:
  FreeNAS-11.3-U5

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Version 0.16.1038.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] yes

### Description

added cookie:
uid=14xxxx78; pass=0dxxxxxxxxxxxxxxxxxxx0b; hideTop=1; __cfduid=d36445xxxxxxxxxxxxxxxxxxxxxxx160xxxxxx254; hideCats=0

### Logged Error Messages

An error occurred while updating this indexer
Your cookie did not work: Found 0 results in the tracker
Click here to open an issue on GitHub for this indexer.

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Before you try anything else upgrade your Jackett to the latest version (currently 0.17.11), because there has been several releases since 0.16.1038 came out that have fixes for layout changes at the iptorrents web site that address no-results-found issues.

**Comment by Freisgd** [comment]
Using Jackett Ver 0.17.213.  
cfuid did not work
cf_clearance did not work
pass did not work
uid did not work
Those are the only items listed under cookies, what am I doing wrong?

**Comment by ilike2burnthing** [comment]
Use the whole cookie, not the individual parts of it.

**Comment by Freisgd** [comment]
Copied and pasted the whole thing and it is still not working
"__cfduid": "xxxxxxxxxxxxxxxxxxxxx"; "cf_clearance": "xxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxx-x-xx"; "pass": "XXXXXXXXXX"; "uid": "xxxxxx"

also did a version where the keywords were not in "", same result. (Depended on how you selected the cookie info if here were "'s).  
Sorry for not getting this, I'm fairly intelligent, I swear.  Thanks in advance for your help.

**Comment by ilike2burnthing** [comment]
Open a new issue with the requested information and an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
