### ISSUE TITLE
[REQ]javbus.com

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#10479]
Public Japan Adult Video share torrent site.

Search engine and magnet working.

https://www.javbus.com

İt have many content and big database.

**Comment by garfield69** [comment]
needs to written as a C# indexer, as one poster goes to a details page that has multiple magnets, which makes it unsuitable as a cardigann yml indexer.

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing

**Comment by vsin123** [comment]
> 由于不适合索引而关闭。参考https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
But JAV-Torrent cannot be added to radarr! !
Tip: Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.

**Comment by ilike2burnthing** [comment]
Both trackers are XXX only, you would never be able to use them with Radarr.

**Comment by vsin123** [comment]
> 两个你都无法将它们与 Radar 永远一起使用。

Thanks for the answer! What should XXX fit in?

**Comment by ilike2burnthing** [comment]
Never used it, but https://github.com/Whisparr/Whisparr

**Comment by vsin123** [comment]
> 没用过，但是https://github.com/Whisparr/Whisparr

Thanks, I'll look into it

**Comment by vsin123** [comment]
> 没用过，但是https://github.com/Whisparr/Whisparr

Why can't jackett make XXX a custom category?

**Comment by ilike2burnthing** [comment]
We can and do, see 1337x for example.

Custom categories are those which are mapped to the categories on a tracker. In the case of JAV-Torrent and others, there are no categories on the tracker and we just use a text dummy category for all results (e.g. XXX).
