### ISSUE TITLE
Anidex does not actually support TV Search with season and episode numbers

### ISSUE THREAD

**Issue by reconman** [Jackett/Jackett#10488]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker-Container

**.Net Runtime**: The one in docker-jackett, don't know which one.

**.Net Version**: The one in docker-jackett, don't know which one.

**Jackett Version**: 0.17.29

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description
1. Add Anidex as indexer
2. Go to http://localhost:9117/api/v2.0/indexers/anidex/results/torznab/api?t=caps&apikey=removed
3. `<tv-search available="yes" supportedParams="q,season,ep" />` is listed, even though season and episode search are not supported

If Attack on Titan is added as a "Standard" show in Sonarr, then the TV Search is triggered, which returns all episodes, no matter the season and episode number, because the URL parameters are ignored by Anidex.

URL to test that Anidex really doesn't support it: http://localhost:9117/api/v2.0/indexers/anidex/results/torznab/api?t=tvsearch&cat=5070&extended=1&apikey=removed&offset=0&limit=100&q=Shingeki%20no%20Kyojin&season=3&ep=13

Only S03E13 should show up.

By the way, after correcting the capabilities, Sonarr will not trigger any Jackett searches anymore since it checks for the season and episode search capabilities first. If the indexer does not support it, no search is triggered. I'm only providing this info in case someone tries to debug the new Jackett behavior with Sonarr.

### Logged Error Messages
No error messages

**Comment by ngosang** [comment]
@reconman I can't fix this is Jackett because episode search is not supported in the site. Filtering results is tricky and it's not going to work. What do you prefer?
* Keep it as is. Season and Episode is ignored and we return all results.
* Remove Season and Episode from capabilities. Sonarr will not search.

**Comment by reconman** [comment]
I would personally choose the second option.

And I already created an issue in Sonarr to support seasonal searches for any tracker, even if they don't support season and episode URL parameters. But it's not clear when and if that feature will be implemented.

**Comment by 6cUbi57z** [comment]
Just tested this and it looks like Sonarr will include the episode and season number in the query string when the Season and Episode capabilities are removed. I'll open a PR to remove them.

**Comment by garfield69** [comment]
v0.17.699
