### ISSUE TITLE
Add indexer button does not work with Chrome

### ISSUE THREAD

**Issue by andrewfraley** [Jackett/Jackett#1048]
Tested on v0.7.1006.  When clicking the Add Indexer button nothing happens.  It does work with MS Edge, however.  

May be related to the JS error seen in the Chrome console:
"You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined"

**Comment by kaso17** [comment]
Please try clearing your cache

**Comment by andrewfraley** [comment]
It indeed was the cache as I had switched from a different Jackett repo.
