### ISSUE TITLE
DSM 7 Beta and Jackett?

### ISSUE THREAD

**Issue by Sjonnie2018** [Jackett/Jackett#10496]
### Environment

**OS**: Synology DSM 7 Beta

**.Net Runtime**: Mono

**.Net Version**: ??

**Jackett Version**: TBD

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** No

### Description

I upgraded to DSM 7 Beta and found there is no package for Mono and hence Jackett. Is there a timeline to support DSM 7 Beta?

### Logged Error Messages

N/A

[Make sure you attach the full logs with your personal information removed in case we need more information]

N.A

Thanks in advance!

Greetz,

Sjonnie

**Comment by garfield69** [comment]
>I upgraded to DSM 7 Beta and found there is no package for Mono and hence Jackett. Is there a timeline to support DSM 7 Beta?

No, this repo does not support DSM directly, we do not maintain any Syno packages.
The [SynoCommunity](https://synocommunity.com/) ported/created a Jackett beta for this platform, so you would need to get in touch with that group to see if some one volunteers to build a package.
From a previous ticket, I think @defaultsecurity seemed to have a finger on the pulse, they might be able to advise.

An alternate is to use Docker, as I believe (from previous tickets) that a Docker Jackett works on DSM.
See https://github.com/Jackett/Jackett#installation-using-docker for details.

**Comment by defaultsecurity** [comment]
@Sjonnie2018 
You will find a package download link in the issue thread below, one that does not require mono. Still untested with DSM 7 beta.
https://github.com/SynoCommunity/spksrc/issues/3697

**Comment by Sjonnie2018** [comment]
Tx @defaultsecurity,

I had a look but I fear I have a 32-bit processor (ANNAPURNALABS Alpine AL212) (DS215+). The linked package is only valid for 64-bit.
