### ISSUE TITLE
Torrentz

### ISSUE THREAD

**Issue by damwthomas** [Jackett/Jackett#105]
I'd like to know why torrentz.eu was removed

**Comment by piluc88** [comment]
because it's a public tracker and all public tracker has been remove

**Comment by damwthomas** [comment]
So how am I supposed to add it to Sonarr now?

**Comment by piluc88** [comment]
i'm not a dev a just saying what they said to me when i ask to add t411

**Comment by raspdealer** [comment]
May be you can ask to Sonarr to integrate it? (The code already exists in Jackett repo)

**Comment by damwthomas** [comment]
I know it exists, I added it... Not too sure why it's being deleted.
Deleting features seems like a weird thing to do.

**Comment by flightlevel** [comment]
Reason = https://github.com/Jackett/Jackett/issues/93#issuecomment-159041208
You can download an older version or create your own fork.
