### ISSUE TITLE
core: add flaresolverr note in some indexers

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#10500]
FlareSolverr / CloudFlare integration is done and the following indexers require the service to work.
Should we add a tag in the indexer name? For example YGG [FlareSolver]
Or it's better to add in a configuration note?

Indexers with CloudFlare ATM (surely more private and semi-private indexers too):
* cpasbien
* dmhy
* epizod
* ext
* hddolby
* mejortorrent
* mypornclub
* pirateiro
* prostylex
* torrentbomb
* torrentkitty
* torrentproject
* torrentz2k
* ygg

@garfield69 @ilike2burnthing ping

**Comment by ilike2burnthing** [comment]
I think a config note. Something to the effect of:

---

This site may use Cloudflare DDoS Protection, and therefore Jackett requires [FlareSolver](https://github.com/FlareSolverr/FlareSolverr) to be able to access it.

---

Not sure if we want more information than that, users can just click the link to find out more. We can add links in config notes, right?

**Comment by ngosang** [comment]
Point to this section instead => https://github.com/Jackett/Jackett#configuring-flaresolverr
