### ISSUE TITLE
Sonarr and Jackett error

### ISSUE THREAD

**Issue by naggert** [Jackett/Jackett#1050]
EDIT:
I found the error. All series in Sonarr was added under the "any" profile. Only quality added there was BlueRay-2160p.
I had tried to delete it previously. 

It was a dumb error on my part and took like 6 hours to figure out.

**Comment by naggert** [comment]
This is the log from Sonarr
EpisodeSearchService	Episode search completed. 0 reports downloaded.	8:58pm
DownloadDecisionMaker	Processing 14 releases	8:58pm
NzbSearchService	Searching 1 indexers for [New Girl : S06E15]	8:58pm

**Comment by kaso17** [comment]
Based on the error it looks like you're using jackett-public from @Raspdealer.
Please get the latest version from this project and try again.

**Comment by raspdealer** [comment]
Correct. It's an old fork, now public trackers are back in master, please use it.

**Comment by naggert** [comment]
Public trackers are back in master? Well! That might just solve my problem.
I've been using Jackett-public because I didn't have access to any private trackers. They all require invites before you're allowed in and since I don't have any friends...

I'll try and install the latest version right away.

**Comment by naggert** [comment]
Thanks! I'm down to a new error tho.
I'll try and reinstall qbittorrent.

QBittorrent	Failed to connect to qBitTorrent, please check your settings.: Failed to connect to qBitTorrent, please check your settings.	12:50pm
QBittorrent	Failed to connect to qBitTorrent, please check your settings.: Failed to connect to qBitTorrent, please check your settings.	12:48pm
TaskExtensions	Task Error: Failed to connect to qBitTorrent, please check your settings.	12:48pm
