### ISSUE TITLE
FlareSolverr input : Invalid URI: The URI scheme is not valid.

### ISSUE THREAD

**Issue by Abbo44** [Jackett/Jackett#10515]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.17.50

**Last Working Jackett Version**: 0.17.50

**Are you using a proxy or VPN?** [yes/no]

### Description

I put my local URI in flaresolverr (172.17.42.1:8191) without https or http and when I clicked on the blue button "Apply settings"), the application crashed and i'm not able to launch app anymore.

### Logged Error Messages

Unhandled exception. Autofac.Core.DependencyResolutionException: An exception was thrown while activating Jackett.Server.Services.ServerService -> Jackett.Common.Services.IndexerManagerService -> Jackett.Common.Utils.Clients.HttpWebClient2.
14/12/2020 23:03:52 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient2'.
14/12/2020 23:03:52 ---> System.UriFormatException: Invalid URI: The URI scheme is not valid.
14/12/2020 23:03:52   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
14/12/2020 23:03:52   at System.Uri..ctor(String uriString)
14/12/2020 23:03:52   at FlareSolverrSharp.Solvers.FlareSolverr..ctor(String flareSolverrApiUrl)
14/12/2020 23:03:52   at FlareSolverrSharp.ClearanceHandler..ctor(String flareSolverrApiUrl)
14/12/2020 23:03:52   at Jackett.Common.Utils.Clients.HttpWebClient2.CreateClient() in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 57
14/12/2020 23:03:52   at lambda_method66(Closure , Object[] )
14/12/2020 23:03:52   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
14/12/2020 23:03:52   --- End of inner exception stack trace ---
14/12/2020 23:03:52   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
14/12/2020 23:03:52   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
14/12/2020 23:03:52   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
14/12/2020 23:03:52   --- End of inner exception stack trace ---
14/12/2020 23:03:52   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
14/12/2020 23:03:52   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__8_0()
14/12/2020 23:03:52   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
14/12/2020 23:03:52   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
14/12/2020 23:03:52   at Autofac.Core.Resolving.InstanceLookup.Execute()
14/12/2020 23:03:52   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
14/12/2020 23:03:52   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
14/12/2020 23:03:52   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
14/12/2020 23:03:52   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
14/12/2020 23:03:52   at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
14/12/2020 23:03:52   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
14/12/2020 23:03:52   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
14/12/2020 23:03:52   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
14/12/2020 23:03:52   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
14/12/2020 23:03:52   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
14/12/2020 23:03:52   at Jackett.Server.Helper.get_ServerService() in /home/vsts/work/1/s/src/Jackett.Server/Helper.cs:line 62
14/12/2020 23:03:52   at Jackett.Server.Helper.Initialize() in /home/vsts/work/1/s/src/Jackett.Server/Helper.cs:line 39
14/12/2020 23:03:52   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services) in /home/vsts/work/1/s/src/Jackett.Server/Startup.cs:line 100
14/12/2020 23:03:52   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
14/12/2020 23:03:52   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
14/12/2020 23:03:52   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
14/12/2020 23:03:52   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
14/12/2020 23:03:52   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
14/12/2020 23:03:52   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
14/12/2020 23:03:52   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
14/12/2020 23:03:52   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
14/12/2020 23:03:52   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
14/12/2020 23:03:52   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
14/12/2020 23:03:52   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
14/12/2020 23:03:52   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
14/12/2020 23:03:52   at Jackett.Server.Program.Main(String[] args)

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Ok. 
So the first lesson is: next time add the `http://` in front of the address ;-b

Secondly, to fix:
- stop the Jackett service,
- access your file manager, 
- find the Jackett config folder (for windows `%ProgramData%\Jackett`, and usually for linux/macos  `~/.config/Jackett`),
- edit with a plain text editor `ServerConfig.json`,
- find `FlareSolverrUrl` and correct the address,
- save,
- restart your Jackett service. 

And you should be good to go ;-)
