### ISSUE TITLE
[yggtorrent] Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address.

### ISSUE THREAD

**Issue by LucaDeslot** [Jackett/Jackett#10512]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.17.50

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

I'm trying to use it on an ultraseedbox server

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
When you access Jackett from your dashboard, what address do you use?
So for example, if you are using `http://127.0.0.1:9117/` to get to Jackett, then try loading on the Jackett dashboard **FlareSolverr API URL:** box `http://127.0.0.1:8191`
Does that work?

**Comment by LucaDeslot** [comment]
My bad I was typing the wrong API URL, thank you !
