### ISSUE TITLE
[New Tracker REQ] HDPter

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1051]
**Indexer Name**
HDPter

**Type**
Movies, TV, Audio, Other

**Indexer URL**
http://www.hdpter.net/

**Indexer Language**
Mandarin, some English

**Invite**
HDPter is currently open for signups for a very limited time:
http://www.hdpter.net/signup.php

**Note**
As with most Chinese trackers, there's an assessment that you need to pass within 30 days of signing up in order to keep your account. You'll find the assessment details on your homepage once you sign in.

**Comment by kaso17** [comment]
registered but not getting the confirmation mail. Do they have some kind of IRC, etc. to contact them?

**Comment by armani316** [comment]
@kaso17 I don't think they do. but I just sent their staff a PM asking them to manually confirm your account. I'm assuming you're using the same username I know (starting with an s)?

**Comment by kaso17** [comment]
yes, thank you

**Comment by kaso17** [comment]
when trying to resent the confirmation email I'm getting "Unable to send mail. Please report this error to the administrator."

**Comment by armani316** [comment]
I'll report it now. Also, let me know what email address you signed up with (you can email it to me if you wish). Admin just asked me for it.

**Comment by armani316** [comment]
@kaso17 Your account should be activated now. Please confirm.

**Comment by kaso17** [comment]
yes it's working, thank you

**Comment by kaso17** [comment]
added with bb989c22c60509361df6463cdf60e0429b012171
