### ISSUE TITLE
T411

### ISSUE THREAD

**Issue by foXaCe** [Jackett/Jackett#1052]
Hello.

Why the T411 scraper can not find all files ?

missing release but is they are present on the site.

**Comment by armani316** [comment]
@foXaCe I think you're referring to the issue that I described in #975. Jackett only displays the search results that appear on the first page of the tracker’s website. This applies to all trackers, not just T411. There's a plan to fix this in the future.

**Comment by foXaCe** [comment]
Ok thanks for the info
