### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid (Test)

### ISSUE THREAD

**Issue by FLAFLALEBG** [Jackett/Jackett#10520]
### Environment

**OS**: Raspberry pi os lite

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Jackett Version v0.17.50

**Are you using a proxy or VPN?** [yes/no] no

### Description

I installed cloudflare to bypass the capatcha on ygg torrent but I don't think I installed it correctly here is the error The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid (Test)

### Logged Error Messages

Error | Jackett.Common.IndexerException: Exception (yggtorrent): The cookies provided by FlareSolverr are not valid  ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 166    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 207    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 485    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1278    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 379    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 379    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 648    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 147    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
-- | --

### Screenshots

![image](https://user-images.githubusercontent.com/33604967/102212777-06075780-3ed6-11eb-8176-d7b90799b302.png)

**Comment by ilike2burnthing** [comment]
Try YGGcookie with FlareSolver. It's working for me, whereas YGGtorrent currently isn't. Let us know if that works.

**Comment by FLAFLALEBG** [comment]
Thanks for your answer @ilike2burnthing but I have the same error with YGGcookie.
![image](https://user-images.githubusercontent.com/33604967/102389641-ac855280-3fd3-11eb-8127-9cdf3944c92b.png)

**Comment by FLAFLALEBG** [comment]
I'm not sure if the problem could come from here but I passed a step of the Wiki because I'm stuck to this error.
![image](https://user-images.githubusercontent.com/33604967/102390140-4ea53a80-3fd4-11eb-8058-4276d4eba450.png)

**Comment by ilike2burnthing** [comment]
Are both Jackett and FlareSolverr on the same device?

**Comment by FLAFLALEBG** [comment]
of course

**Comment by ilike2burnthing** [comment]
Are any other indexers working with FlareSolverr? You can find a list of those sites known to use Cloudflare here - https://github.com/FlareSolverr/FlareSolverr/issues/25

**Comment by FLAFLALEBG** [comment]
> Are any other indexers working with FlareSolverr? You can find a list of those sites known to use Cloudflare here - [FlareSolverr/FlareSolverr#25](https://github.com/FlareSolverr/FlareSolverr/issues/25)

None of the cited links work with cloudsolverr

**Comment by FLAFLALEBG** [comment]
after making some modifications on flaresolverr I received this error message but I couldn't tell if I was going forward or backward?
![image](https://user-images.githubusercontent.com/33604967/102404825-81f1c480-3fe8-11eb-9837-0b43ac45c3a0.png)

**Comment by ilike2burnthing** [comment]
Well that's a new one!

Please open a new issue in https://github.com/FlareSolverr/FlareSolverr/issues (you can link to this one to save having to repeat yourself). 

Set `LOG_LEVEL=debug` and `LOG_HTML=true` for FlareSolverr, restart it, repeat a search with YGGcookies (or another indexer, given that none are working), and post the logs in that new issue (just make sure to remove any personal information).
