### ISSUE TITLE
Anime release

### ISSUE THREAD

**Issue by michaelgeorgeattard** [Jackett/Jackett#1053]
I am trying to search for a particular anime release. Sonarr is querying using Season x Episode number.

I am getting no search results from a particular tracker (piratebay).

Any ideas what could be going on?

**Comment by kaso17** [comment]
Please provide a log/example.

**Comment by armani316** [comment]
@michaelgeorgeattard It would be great if you could provide examples or an enhanced log to help @kaso17 with this issue.

**Comment by RoloSoze** [comment]
@michaelgeorgeattard I'm closing this for now since there's no response. Post the enhanced log later when you see this, and feel free to reopen the issue.
