### ISSUE TITLE
[req] LemonHD

### ISSUE THREAD

**Issue by tuningman9790** [Jackett/Jackett#10533]
Hello,

So LeagueHD.com transformed into LemonHD.org. Same site just new domain.

**Comment by ilike2burnthing** [comment]
Changed. Will be out in the next release in ~14hrs

**Comment by garfield69** [comment]
Jackett 0.17.100

**Comment by garfield69** [comment]
https://lemonhd.org/ DNS_PROBE_FINISHED_NXDOMAIN (domain not found)

**Comment by garfield69** [comment]
v0.21.364
