### ISSUE TITLE
[REQ]oncesearch.com

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#10539]
Public porn torrent search engine.
http://oncesearch.com

Search engine and torrents working.

**Comment by garfield69** [comment]
v0.17.605

**Comment by ilike2burnthing** [comment]
http://oncesearch.com/ - Error Page - status code 500

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
http://oncesearch.com/ - redirects to best-sexy-dreams[dot]life

**Comment by garfield69** [comment]
v0.20.266

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
[v0.20.1208](https://github.com/Jackett/Jackett/releases/tag/v0.20.1208)

**Comment by garfield69** [comment]
http://oncesearch.com/ redirects to https://findallmoneysurvey.top/finance-survey.html?z=blahblah&offer_id=blah&var=blah&ymid=crapcrapcrap

**Comment by garfield69** [comment]
v0.20.1406
