### ISSUE TITLE
[ilcorsaronero] Exception (ilcorsaronero): Request to https://ilcorsaronero.link/browse/0 failed (Error BadGateway) - The tracker seems to be down.: Request to https://ilcorsaronero.link/browse/0 failed (Error BadGateway) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by sasagr** [Jackett/Jackett#10532]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
linux armh7
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
v0.17.64

**Are you using a proxy or VPN?** [yes/no]
no
### Description
Error BadGateway with all the links in setup

**Comment by ilike2burnthing** [comment]
site is down - https://github.com/Jackett/Jackett/issues/986#issuecomment-745652357
