### ISSUE TITLE
[NNC] Noname club not authorised to DL non-freeleech files

### ISSUE THREAD

**Issue by MGlants** [Jackett/Jackett#10531]
Hello there,
Are there any chances to get NNM club indexer with authentication cause torrent can't download anything without freelech mark due to Error: Host not found (authoritative)

Thank you

**Comment by garfield69** [comment]
Please provide a torrent name I can search that is not freeleech so I can check what is required. Thanks.

**Comment by MGlants** [comment]
Фарго / Fargo (2020) WEB-DL 1080p [H.264/1080p-LQ] (сезон 4, серии 1-11 из 11)

That title is gold (download not counting) but upload is. So it requires seed id.

**Comment by MGlants** [comment]
> Please provide a torrent name I can search that is not freeleech so I can check what is required. Thanks.

Фарго / Fargo (2020) WEB-DL 1080p [H.264/1080p-LQ] (сезон 4, серии 1-11 из 11)

That title is gold (download not counting) but upload is. So it requires seed id.

**Comment by garfield69** [comment]
next release due out in about 12 hours or so from the time of this post will have an indexer available called `NoNaMe ClubL` which is the `NoNaMe Club` indexer with a login in the config.

**Comment by MGlants** [comment]
> next release due out in about 12 hours or so from the time of this post will have an indexer available called `NoNaMe ClubL` which is the `NoNaMe Club` indexer with a login in the config.

Awesome, thank you for your time

**Comment by garfield69** [comment]
Jackett 0.17.100
