### ISSUE TITLE
Wrong admin password should return 401 instead 200

### ISSUE THREAD

**Issue by JorTurFer** [Jackett/Jackett#10542]
The problem here is that the wrong password result is the same that the first page load, so it is imposible to detect the fail error to apply any security action.

### Environment
Docker with last image

[List steps to reproduce the error and details on what happens and what you expected to happen]
Run container -> create admin paswsword -> try to login with wrong password

### Logged Error Messages
Not any error

**Comment by garfield69** [comment]
To clarify, you are talking about the Jackett dashboard admin password?

**Comment by JorTurFer** [comment]
Sorry :(
Yes, I am talking about admin password.
I am trying to use fail2ban in my proxy server to prevent attacks, and jackett is imposible to protect

**Comment by ilike2burnthing** [comment]
related: https://github.com/Jackett/Jackett/issues/3903

**Comment by JorTurFer** [comment]
> related: https://github.com/Jackett/Jackett/issues/3903

I am not sure if this is 100% related. In theory a REST API should return the corrwct HTTP status code.

I want use the code to manage fail2ban, but it is a consecuence and not the origin

**Comment by ngosang** [comment]
@JorTurFer You are right. We should return 401 but we can't because the WebUI uses the HTTP code 302 to follow the redirect. We will have change too much things in the UI to make the API REST compliant.

**Comment by rrrevin** [comment]
> By now you can use a secure password with more than 14 characters. It's *improbable* to crack by bruteforce.

Fixed it for you.

**Comment by JorTurFer** [comment]
Okey, this is just a question, I can live with strong password and without fail2ban.
Thanks for your work! :)
