### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by buhtig176** [Jackett/Jackett#10545]
### Environment

**OS**: Win7 x64

**.Net Runtime**: [.Net-Framework]

**.Net Version**:4.8

**Jackett Version**:0.17.64

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes]

### Description

Can we do something to avoid flare solver?

### Logged Error Messages

Not needed

### Screenshots

Not needed

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
