### ISSUE TITLE
Alpine Startup ./jackett: not found

### ISSUE THREAD

**Issue by hydazz** [Jackett/Jackett#10555]
### Environment

**OS**:
Alpine Edge
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
?
**.Net Version**:
?
**Jackett Version**:
v0.17.101
**Last Working Jackett Version**:
N/A
**Are you using a proxy or VPN?** [yes/no]
No
### Description
I'm trying to install jackett in an alpine edge docker image (if this is possible?). I installed all the [listed dependencies](https://github.com/Jackett/Jackett#install-on-linux-amdx64), but when I try start jackett it says ./jackett: not found. which I'm pretty sure is a missing package, but I'm not sure which package is missing.

installed packages (apk info):
```
musl
busybox
alpine-baselayout
alpine-keys
libcrypto1.1
libssl1.1
ca-certificates-bundle
libtls-standalone
ssl_client
zlib
apk-tools
scanelf
musl-utils
libc-utils
xz-libs
xz
ca-certificates
libacl
ncurses-terminfo-base
ncurses-libs
readline
bash
libattr
skalibs
s6-ipcserver
utmps
coreutils
libintl
libproc
procps
linux-pam
shadow
tzdata
brotli-libs
nghttp2-libs
libcurl
curl
libgcc
libstdc++
icu-libs
krb5-conf
libcom_err
keyutils-libs
libverto
krb5-libs
userspace-rcu
lttng-ust
numactl
```
What am I missing?

[Dockerfile](https://github.com/hydazz/docker-jackett/blob/main/Dockerfile)

**Comment by ngosang** [comment]
You are installing the Mono release. I recommend you to install the .net core release.
Example => https://github.com/linuxserver/docker-jackett/blob/master/Dockerfile

**Comment by hydazz** [comment]
> You are installing the Mono release. I recommend you to install the .net core release.

Sorry, I was seeing if the mono version of Jackett ran without problems (in which it ran without errors). I have since switched it back to the .net release. Still Trying to start Jackett via jackett_launcher.sh errors out; `line 10: /app/Jackett/jackett: not found`. I can't really see why it won't start, the .net version of radarr starts without issues

**Comment by ngosang** [comment]
It looks like you are extracting Jackett in a different folder. Try with `/app/Jackett/Jackett/jackett`
It should be possible to run Jackett in Alpine Docker but we can't give the kind of support. Use the Official Docker from => https://hub.docker.com/r/linuxserver/jackett

**Comment by hydazz** [comment]
Fixed by manually building Jackett for musl. Updated [Dockerfile](https://github.com/hydazz/docker-jackett/blob/ba570f58222cfee0eb5da5f3ae280ece30853a5f/Dockerfile#L7-L20) for others reference. It would be nice if there was a prebuild musl release available in the release assets, as Radarr has

**Comment by ngosang** [comment]
Just for my curiosity. What is the difference is size between your image and LinuxServer image?

**Comment by hydazz** [comment]
> Just for my curiosity. What is the difference is size between your image and LinuxServer image?

Linuxserver uncompressed size is 263.64 MB and my uncompressed image is 91.88 MB so 171.76 MB is savings

**Comment by ngosang** [comment]
Nice and expected. Anyway we don't have enough people to maintain Docker images, we relay on LinuxServer for that.

LinuxServer images are a bit heavy, but they relay in sharing the base image across all images. For example, if you have Sonarr/Radarr/Jackett/Deluge... all of them share the same base image so the first image is heavy but the others are super-optimized in size, just the software. If they build ALL packages with Alpine you can save 100-200MB in the base image but some of the packages can't be shipped with Alpine and you have 2 different base images losing that advantage. Anyway I think they should publish Alpine images when possible.

**Comment by radumamy** [comment]
> Fixed by manually building Jackett for musl. Updated [Dockerfile](https://github.com/hydazz/docker-jackett/blob/ba570f58222cfee0eb5da5f3ae280ece30853a5f/Dockerfile#L7-L20) for others reference. It would be nice if there was a prebuild musl release available in the release assets, as Radarr has

Hi @hydazz. Thank you for your suggestion on building this manually. I've built it using an aarch64 Alpine 3.14 LXD container, but unfortunately I'm getting the same result as the official build. 

`
/opt/Jackett $ ./jackett
ash: ./jackett: not found
/opt/Jackett $ /bin/sh jackett                       
jackett: line 1: syntax error: unexpected "("         /opt/Jackett $ /bin/bash jackett
jackett: jackett: cannot execute binary file
`

Steps taken:
Downloaded SDK 5.0.402 from Ms website (Alpine arm64), extracted it and created a simlink for `dotnet` executable to `/usr/local/bin/dotnet`. 
Downloaded source code for latest jackett release, extracted and installed deps. 
I've then used your instructions to build jacket adjusting release to `linux-musl-arm64`
The build was successful but it won't run. 

Do you have any advice on how to get it working? 

Thank you.
