### ISSUE TITLE
[generationfree] Category issue

### ISSUE THREAD

**Issue by saitoh183** [Jackett/Jackett#10559]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.17.101

**Last Working Jackett Version**: n/a

**Are you using a proxy or VPN?** [yes/no] no

### Description

Doing a manual search for a TV show and the category for the TV show is Movies instead of one of the TV Show categories. Upon further digging i discovered that GF changed there category system and lots of shows that where once under Autre Emission: TV 
![image](https://user-images.githubusercontent.com/1534197/102645636-c38d8700-4130-11eb-9d66-3accb38c6a3c.png)
are now under Series with the word Allocine crossed out 
![image](https://user-images.githubusercontent.com/1534197/102645649-cab49500-4130-11eb-8e18-eafb8017795a.png)

because of this, Jackett manual search shows that new category as Movie (2000)
![image](https://user-images.githubusercontent.com/1534197/102645805-094a4f80-4131-11eb-896f-2a5b88fcbdac.png)

unfortunately, applications like Medusa cannot add the Movie (2000) category as it doesnt appear in the list. I posted this same problem on the GF forum because i do not know where the correction can be made.

 

### Logged Error Messages

No error messages

**Comment by garfield69** [comment]
Jackett 0.17.103
