### ISSUE TITLE
[desireleasers] down - Service Unavailable

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#10566]
https://desireleasers.be/ - Error 503 - Service Unavailable

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://desireleasers.be/ - Error 502 - Bad Gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://desireleasers.be/ - working
https://desireleasers.be/torrents (and all searches) - blank page, HTML shows `SQLSTATE[42S02]: Base table or view not found`

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://desireleasers.be/ - Error 503 - Service Unavailable

**Comment by garfield69** [comment]
If there is no signs of an alternate domain for this site then it's time to remove the indexer.

**Comment by garfield69** [comment]
v0.20.78
