### ISSUE TITLE
btdigg: no results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#10579]
I made different searches in Jackett and none of them return results.
Maybe they changed the layout.

**Comment by TuxNuX** [comment]
I confirm no result in jackett, and work well on the website

many results on website
https://btdig.com/search?q=android

no result in jackett
![Screenshot_20201220_154251](https://user-images.githubusercontent.com/17123357/102716115-0b9bdd80-42da-11eb-979d-f0c59c5e931e.png)

**Comment by garfield69** [comment]
the website is presenting a captcha whenever jackett does a query, text content below:
```
Attention Required!
One more step
Please complete the security check to access
Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.
What can I do to prevent this in the future?
If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.
 If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.
```

**Comment by ngosang** [comment]
Yep, they are detecting us but I don't know how.

**Comment by ngosang** [comment]
I talked with the big boss and they are blocking Jackett requests. If they don't provide a solution in a couple of weeks we should remove the tracker.

**Comment by ilike2burnthing** [comment]
BTDigg started working for me a few days ago (having almost never worked since I added it, in Jackett or browser, due to what I assume was an IP block).

Still working:
![btdigg](https://user-images.githubusercontent.com/59480337/105769491-c95b6100-5f55-11eb-9c54-ec27dc8d00d1.png)

Though if I try to access the site in browser I get redirected to https://community.cloudflare.com/t/revoke-and-prevent-the-issuing-of-certificates/235478

**Comment by RoloSoze** [comment]
The website itself is up & running, and returns results, but it still does not work in Jackett. I imagine it's the same for you guys?

@garfield69 @ngosang @ilike2burnthing

**Comment by ilike2burnthing** [comment]
Still working ok here with VPN.

**Comment by RoloSoze** [comment]
> 
> 
> Still working ok here with VPN.

Tried it with 2 different VPNs. Still does not work in Jackett.

**Comment by TuxNuX** [comment]
always no work 
![Screenshot_20210223_140604](https://user-images.githubusercontent.com/17123357/108847733-58ed4180-75e0-11eb-971a-c3948e1218d2.png)

**Comment by ilike2burnthing** [comment]
onion proxies have resolved this issue
