### ISSUE TITLE
[REQ] anime-free

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#10576]
Semi-private 3D/2D video, manga mix content torrent site.

Must register for download torrent file. 
Site is updating and seeding.

Thank you for your all job. Many website add from jackett.

https://anime-free.biz/

**Comment by garfield69** [comment]
https://anime-free.one/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.21.1897
