### ISSUE TITLE
Torznab search for certain indexers not working

### ISSUE THREAD

**Issue by LTWood** [Jackett/Jackett#10574]
### Environment

**OS**: Ubuntu 20.04

**.Net Runtime**: Mono

**Jackett Version**: v0.17.103

**Are you using a proxy or VPN?** Yes

### Description

I have two indexers on Jackett; Rarbg and The Pirate Bay. When I test these indexers in Jackett, they succeed in pulling some releases. I added the Rarbg torznab feed to Radarr and that works perfectly fine. However, when I add the pirate bay torznab feed to radarr, it says that it can connect, but it can't find any releases. So I looked at the API calls that Radarr was making and called them manually in my browser. The API call for the Rarbg feed works fine and I can see in the file that there are a bunch of releases in it. When I do the same for the pirate bay feed however, it is empty apart from the following

```<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://10.0.1.4:9117/jackett/" rel="self" type="application/rss+xml" />
    <title>The Pirate Bay</title>
    <description>Pirate Bay (TPB) is the galaxy’s most resilient Public BitTorrent site</description>
    <link>https://www.tpbay.win/</link>
    <language>en-us</language>
    <category>search</category>
    <image>
      <url>http://10.0.1.4:9117/jackett/logos/thepiratebay.png</url>
      <title>The Pirate Bay</title>
      <link>https://www.tpbay.win/</link>
      <description>The Pirate Bay</description>
    </image>
  </channel>
</rss>
```

### Logged Error Messages

Log file is attached. 
[log.txt](https://github.com/Jackett/Jackett/files/5720099/log.txt)

**Comment by ilike2burnthing** [comment]
Is this still happening? TPB's API is often down.
