### ISSUE TITLE
[torrentz2k] Exception (torrentz2k): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by batuhankrmn** [Jackett/Jackett#10594]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured

**Comment by Kenshin9977** [comment]
> https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured

This section olny says "Also" and does not help in troublshooting the issue.

**Comment by garfield69** [comment]
@Kenshin9977 

> > https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
> This section olny says "Also" and does not help in troublshooting the issue.

:-D

![image](https://user-images.githubusercontent.com/6933240/103157755-4abab900-481b-11eb-8498-5f08421e0795.png)

English dictionary definition of also. adv. 1. **In addition**. 2. **Likewise**,

Hint: read the text in the **next** section  ...

Merry Xmas and Happy New years.

**Comment by Kenshin9977** [comment]
Likewise / In addition / Also are used following the thing you're referring to, not before.
You can also (see I know the word) use hypertext link to redirect your "Also" sections to the corresponding sections.
Exemple : [Also](https://github.com/Jackett/Jackett/wiki/Troubleshooting#exception-indexer-no-such-host-is-known)
Merry christmas and happy new yearS to you too.
