### ISSUE TITLE
[REQ] New Tracker - Blu-Evolution

### ISSUE THREAD

**Issue by sider1681** [Jackett/Jackett#106]
I'd like to request the indexer http://blu-evolution.org/ be added for Couchpoato. They've got great HD content that doesn't always make it to the other indexers.

**Comment by raspdealer** [comment]
https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker

**Comment by sider1681** [comment]
Thanks for the info @raspdealer. I have an invite ready, however I do have a slight concern about handing one out without any type of proof or assurances that my account status won't be compromised. What are your thoughts on that?

**Comment by conihorse** [comment]
Choices: a) Learn to code b) Learn to trust someone kind enough to do work you are unable/unwilling to do. Pick one.
