### ISSUE TITLE
Becoming a contributor

### ISSUE THREAD

**Issue by griddoz92** [Jackett/Jackett#1060]
hi guys i have modified your UI to ad better mobile support and would like to contribute

![apple-touch-icon](https://cloud.githubusercontent.com/assets/25756500/22916177/04fbed56-f2d1-11e6-8aaa-c3d54048a878.png)
![apple-touch-icon-57x57](https://cloud.githubusercontent.com/assets/25756500/22916179/05002844-f2d1-11e6-9d67-b509cd7d2002.png)
![apple-touch-icon-72x72](https://cloud.githubusercontent.com/assets/25756500/22916178/04ffa018-f2d1-11e6-8ec1-0be7d24cf4ac.png)
![apple-touch-icon-76x76](https://cloud.githubusercontent.com/assets/25756500/22916180/05077342-f2d1-11e6-8bd0-d5b1805f36b4.png)
![apple-touch-icon-114x114](https://cloud.githubusercontent.com/assets/25756500/22916181/05087f4e-f2d1-11e6-9fcc-f575e8c90e94.png)
![apple-touch-icon-144x144](https://cloud.githubusercontent.com/assets/25756500/22916183/054e6ed2-f2d1-11e6-815a-3016625f9ef7.png)
![apple-touch-icon-152x152](https://cloud.githubusercontent.com/assets/25756500/22916185/0559b12a-f2d1-11e6-8421-1c22ea822213.png)
![apple-touch-icon-180x180](https://cloud.githubusercontent.com/assets/25756500/22916184/0558cabc-f2d1-11e6-954e-95bb2566f0f6.png)

**Comment by kaso17** [comment]
Can you please open a pull request with your changes so we can have a look at them?

**Comment by griddoz92** [comment]
done
