### ISSUE TITLE
[yggcookie] Exception (yggcookie): The operation was canceled.: The operation was canceled. 

### ISSUE THREAD

**Issue by nini57** [Jackett/Jackett#10601]
### Environment

**OS**:Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.145

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]no

### Description

I've an error when I test yggtorrent indexer. I've an other docker wither FlareSolverr 

### Logged Error Messages
Jackett.Common.IndexerException: Exception (yggcookie): The operation was canceled.

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Please follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#the-operation-was-canceled

If none of that helps, the provide an enhanced log of the issue.
