### ISSUE TITLE
[7torrents] Exception (7torrents): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#10603]
7torrents indexes is broke.

My log: [log.txt](https://github.com/Jackett/Jackett/files/5730324/log.txt)

**Comment by ilike2burnthing** [comment]
They've implemented Cloudflare DDoS Protection. A note in the configuration panel was added in the last release. Install and use FlareSolverr to allow Jackett to bypass it - https://github.com/Jackett/Jackett#configuring-flaresolverr
