### ISSUE TITLE
[ilcorsaroblu] Login failed: No form found on https://ilcorsaroblu.org/index.php?page=login

### ISSUE THREAD

**Issue by dawez** [Jackett/Jackett#10613]
It seems that is not possible to login to the website.

I used a valid account on the tracker.

Jackett Version v0.17.153

**Comment by dawez** [comment]
mistake

**Comment by ilike2burnthing** [comment]
Working fine here. If you'd care to provide the requested information we might actually be able to help.

**Comment by dawez** [comment]
@ilike2burnthing  thank you for your message. I tried again and it worked as expected. Maybe last time were some net issues. 

Sorry for the noise.
