### ISSUE TITLE
Tracker arabafenice.me gives me no matches

### ISSUE THREAD

**Issue by memnos** [Jackett/Jackett#1061]
I enable this tracker indexer, and seems to log.
When i press search botton and look for any word i have nothing found.

Here is a log with an example with word american:
[log.txt](https://github.com/Jackett/Jackett/files/773405/log.txt)

Jackett Version 0.7.1018.0
Mono version: Stable  #4.6.2.7/08fd525  

-------------------------------

**Comment by kaso17** [comment]
Caused by new users (me) having an additional column in the search results (wait time).
Fixed with 3992cbdc413270b057591fc9fed4a9ebb55c01a5

**Comment by memnos** [comment]
I can confirm now all seems ok.
Tnx
