### ISSUE TITLE
excluding during searches

### ISSUE THREAD

**Issue by nydave69** [Jackett/Jackett#10622]
I've searched everywhere and cannot find out how to exclude in manual or RSS searches.
can add a list of search criteria using the + but how would I exclude say DD5..
the normal ways don't seem to work.. 

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
You can filter returned search results using negative filtering `-keyword` - https://github.com/Jackett/Jackett/pull/8048

However, doing so for an actual search isn't possible for most indexers as the sites themselves don't support it.
