### ISSUE TITLE
MagDL disappeared in indexers (http://magnetdl.nl)

### ISSUE THREAD

**Issue by corcoranmam** [Jackett/Jackett#10626]
**OS**: Ubuntu Server 18

**Jackett Version**: v0.17.159

**Last Working Jackett Version**: v0.17.159

**Are you using a proxy or VPN?** No

### Description

My radarr indexers started failing on MagDL and I could not re add on Jackett. Is it likely they have change something on their end or is it missing from my list for a reason? http://magnetdl.nl

### Screenshots

<img width="936" alt="Screenshot 2020-12-25 at 13 08 40" src="https://user-images.githubusercontent.com/71404312/103135753-71111500-46b2-11eb-8517-d8b6fd6dc848.png">

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/pull/10347

**Comment by corcoranmam** [comment]
could you delete the issue please

**Comment by garfield69** [comment]
>could you delete the issue please 

Unable to delete, as GitHub does not provide this feature.
