### ISSUE TITLE
pttime.org private tracker get banned after add by jackett. test 2 time same result get banned

### ISSUE THREAD

**Issue by plsharevme** [Jackett/Jackett#10624]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
@tantao700 can you confirm?

**Comment by plsharevme** [comment]
Yup, I can confirm. 
1st now it open application for sign up, then I sign up successfully, I use to login for surf around also no problem. Then I add into jackett test is also okay, inside jackett I use manual search also OK, but within 10 minutes, the test is fail, I also cannot login,..... I use 2 email register pptime also get banned.

**Comment by ilike2burnthing** [comment]
That was for another user, not you. We need a second person to confirm, as there are plenty of reasons why accounts can be banned, and the timing may just be a coincidence in your case.

**Comment by tantao700** [comment]
@plsharevme 

Sorry for reply so late, i ensured that add pttime indexer CAN NOT been banned by jackett。

can you provide more detail about your environment and action to us to trace it ,
i known that you can been banned if you Identified as web Web Crawler
