### ISSUE TITLE
Add support for torrent file downloads via hash/magnet link

### ISSUE THREAD

**Issue by kaso17** [Jackett/Jackett#1063]
It might be useful to have a generic endpoint which would try to grab a torrent file from torrent caches based on the hash.

Example download URL:
127.0.0.1:9117/hashdl/magnet:?xt=urn:btih:b8aaaaaaa6cef87215eae46436982fe613edd8e3&dn=example.torrent

Known caches:
http://torrage.info/
http://itorrents.org/
http://btcache.me/
https://thetorrent.org/

**Comment by firedomain** [comment]
I feel this is a vital feature to allow all links to be sent to the server blackhole as a torrent file.
Currently it is very inconvenient  for me to copy links & have to paste them into my torrent client web ui.
I was disappointed when i set a blackhole dir to find out that i rarely see links that let me use it.

**Comment by minitoine** [comment]
Quite old topic, but shouldn't be possible to only save magnets in the blackhole directory as a .magnet file with the link in it ?

**Comment by Farsons** [comment]
These sites are not a lot of seeds. I know that www.bthub.org has a full database site, but it is difficult to apply for api. Does anyone know how to apply for api access correctly?

**Comment by kaso17** [comment]
note:
https://hash2magnet.com seems to do this

**Comment by sizzlingkenny** [comment]
https://hash2magnet.com changed to [https://hashtomagnet.xyz/](https://hashtomagnet.xyz/)
it is now providing quick magnet generate via hash key and giving current seed + leech + completed list of the given info hash, its quite useful tool.

**Comment by swannie-eire** [comment]
+1 for me. I often come across magnet links that never seem to be able to download the metadata of the torrent and as a result the torrent never starts. In those cases i usually just copy the hash and download it from itorrent. it would be great if there was an option from within jackett that would allow me to download the torrent from itorrent using the hash.

**Comment by garfield69** [comment]
closing as stale.
