### ISSUE TITLE
[1337x] Exception (1337x): Ssl error:0f000078:elliptic curve routines:OPENSSL_internal:POINT_IS_NOT_ON_CURVE  at /spksrc/spk/mono/work-aarch64-6.1/mono-5.20.1.34/external/boringssl/crypto/ec/ec.c:835: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by vincederot** [Jackett/Jackett#10639]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:DSM 6.2.3-25426 Update 2

**.Net Runtime**: Mono

**.Net Version**:

**Jackett Version**:v0.16.1340.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

Cannot add and use indexer

### Logged Error Messages
Exception (1337x): Ssl error:0f000078:elliptic curve routines:OPENSSL_internal:POINT_IS_NOT_ON_CURVE at /spksrc/spk/mono/work-aarch64-6.1/mono-5.20.1.34/external/boringssl/crypto/ec/ec.c:835: An error occurred while sending the request

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by vincederot** [comment]
This issue is detailed

**Comment by ilike2burnthing** [comment]
If you can run Docker, I'd suggest you use the Jackett image.

If not, you can try downgrading mono using the following method - https://github.com/SynoCommunity/spksrc/issues/3946#issuecomment-612562594 (see bottom half of the comment)

The naming scheme has seemingly changed slightly on SynoCommunity, but the one mentioned `5.8.0.108-11 [6.1 rtd1296]` seems to be https://packages.synocommunity.com/mono/11/mono.v11.f15047[rtd1296-armada37xx-aarch64].spk

You can try some of the relevant, more recent versions there as well - https://packages.synocommunity.com/mono
