### ISSUE TITLE
How exactly the api works?

### ISSUE THREAD

**Issue by rodrigo-sys** [Jackett/Jackett#10632]
I know that with this I can get all the results of the search term;

curl http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=$api_key&Query=$search_term

But if i want filter by tracker , or sort by seeders?
how achive that?

for example in the web interfance I can filter by tracker in this way

http://localhost:9117/UI/Dashboard#search=shingeki+no+kyojin&tracker=anidex&category=

how do something like that in the api?

**Comment by ilike2burnthing** [comment]
Replace `all` with the id of the indexer:
.../indexers/all/results?...
.../indexers/1337x/results?...
.../indexers/rarbg/results?...
.../indexers/torrentdownloads/results?...

What is it you're trying to do with the raw API results?

**Comment by rodrigo-sys** [comment]
> Replace `all` with the id of the indexer:
This don't work

That don't work for me

this
.../indexers/all/results
and this
.../indexers/1337x/results

show me the same results

> What is it you're trying to do with the raw API results?

sort by seeders
filter  by category
show the size in human readable
things like that

I do that with a json processor but I thought that could be done directly from the api

**Comment by ilike2burnthing** [comment]
Apologies, wasn't playing close enough attention.

_Jackett:_
/api/v2.0/indexers/all/results?apikey=$api_key&Query=$search_term&Tracker%5B%5D=**1337x**

_Torznab:_
/api/v2.0/indexers/**1337x**/results/torznab?apikey=$api_key&Query=$search_term`

_RSS:_
/api/v2.0/indexers/**1337x**/results/torznab/api?apikey=$api_key&q=$search_term`

As for qualifiers:
- https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Models/DTO/TorznabRequest.cs
- https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Models/TorznabQuery.cs
- https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/CardigannIndexer.cs

I'm not sure if there is an API developer readme. @garfield69 or @ngosang may have a better idea, or at least fuller resources.

To my (limited) knowledge, any sorting is done either in the indexer's config (so it's requested in that order from the site), or in the results table in our webUI, it's not something which can be appended to the URL.
