### ISSUE TITLE
[REQ]141jav.com public jav torrent

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#10648]
Public japan adult video share torrent site.

https://www.141jav.com

Search engine and torrents working.
Add new content everyday. 
![1](https://user-images.githubusercontent.com/36575395/103248241-df87f880-497a-11eb-80d9-85e5404e6c9e.JPG)
![2](https://user-images.githubusercontent.com/36575395/103248245-e1ea5280-497a-11eb-8324-901e8a0a25f8.JPG)

**Comment by garfield69** [comment]
the search on this site appears to only find the dvd id, for instance https://www.141jav.com/search/WAAA043
there are not categories, just tags, which require its own search method, for example https://www.141jav.com/tag/Toy
and you cant combine tag and search.

this site is not suitable for indexing with Jackett.

**Comment by berat1397** [comment]
So when we call DVD codes? Example: Search "JUFE270"

People know jav id and search direkt it's id. 
![232321111](https://user-images.githubusercontent.com/36575395/112620531-b839ae00-8e39-11eb-8400-f3b2793fe589.JPG)
![2321312](https://user-images.githubusercontent.com/36575395/112620536-ba037180-8e39-11eb-8780-5a8d069868f8.JPG)
