### ISSUE TITLE
YGGTorrent Connection refused/Network is unreachable

### ISSUE THREAD

**Issue by Shibiz** [Jackett/Jackett#10640]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] 5.20.1.34-16

**.Net Version**:

**Jackett Version**: 0.17.159

**Last Working Jackett Version**: 0.17.159

**Are you using a proxy or VPN?** [yes/no] NO

### Description

Hello everyone

Issue to connect Jackett with FlareSolverr
When adding YGGTORRENT indexer in Jackett and testing it seems that it can't reach my FlareSolverr container (see logs captured)

I know that FlareSolverr is running because when i go look at logs, and i go to the URL of the container (http://ip:8191)
i have the message which says that it's working, and i see my requests in FlareSolverr's logs

I tried to change the FlareSolverr API URL with : 
http://localhost:8191/ -> Gives me connection refuses
http://127.0.0.1:8191/ -> Gives me Network is unreachable 
http://*myipserver:8191/ -> Gives me Network is unreachable 

### Screenshots

[Place any screenshots of the issue here if needed]
 
Test with http://127.0.0.1:8191/
<a href="https://ibb.co/7JBQskq"><img src="https://i.ibb.co/XZ6DcYq/127001.jpg" alt="127001" border="0"></a>

Test with http://localhost:8191/ 
<a href="https://ibb.co/NmK07dv"><img src="https://i.ibb.co/b2X47M0/localhost.jpg" alt="localhost" border="0"></a>

Thanks to any answers =)

**Comment by ilike2burnthing** [comment]
Use the local IP of your device on the network, e.g. `http://192.168.0.2:8191` and let us know the result.

**Comment by Shibiz** [comment]
Hello, thanks for your answer

I tried with my ip advice and it gives me **The operation was canceled**

Test with http://192.168.1.36:8191/
<a href="https://ibb.co/NL2WYvK"><img src="https://i.ibb.co/THMPhft/192-168-1-36.jpg" alt="192-168-1-36" border="0"></a><br /><a target='_blank' href='https://fr.imgbb.com/'>hébergé une image</a><br />


I have reinstalled Jackett, Flaresolverr but no changes (both are running in docker)
I tried with my firewall down too
I really think that Jackett can't communicate with Flaresolverr..

**Comment by ilike2burnthing** [comment]
That is actually an improvement. Have a look at the troubleshooting steps and see if any of them help - https://github.com/Jackett/Jackett/wiki/Troubleshooting#the-operation-was-cancelled

Are other indexers working when using FlareSolverr? e.g. https://github.com/Jackett/Jackett/search?q=%22name%3A+flaresolverr%22&type=

**Comment by EmaldIsBack** [comment]
Hello. I have exactly the same problem, i tried the troubleshooting steps and none of them solved the issue.
And yes, other Flaresolverr indexes work (i tried episod.tv for example, i know it uses FS aand i worked fine)

**Comment by Shibiz** [comment]
Exactly the same as @EmaldIsBack 

You think that i should continue to test using the link with my ip server ? (http://192.168.1.36:8191/)

**Comment by ilike2burnthing** [comment]
Can you provide your Docker run command or compose file for FlareSolverr (or if using Portainer, screenshots of the container's settings)?

Depending on your setup, you could use the container's Docker URI (e.g. http://172.17.0.2:8191), or just the container's name (e.g. http://flaresolverr:8191).

Feel free to try those in advance of replying; it won't break anything, there just might not be any need.

**Comment by EmaldIsBack** [comment]
I am not using docker container, i installed Jackett and FS on a Ubuntu server, so, it's not z docker issue

**Comment by Enohriel** [comment]
You have an issue with your container port exposition. You can't reach the proxy.
I managed to fixed this issue, but now i'm facing a new issue : `Exception (yggtorrent): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid`.
It does the same with YggCookie.

**Comment by Shibiz** [comment]
Is this the run command you asked for @ilike2burnthing ?

<a href="https://ibb.co/vVYHZXV"><img src="https://i.ibb.co/4Kd7P1K/docker1.jpg" alt="docker1" border="0"></a>
<a href="https://ibb.co/FnY460Z"><img src="https://i.ibb.co/SJmwNdY/docker2.jpg" alt="docker2" border="0"></a>

**Comment by EmaldIsBack** [comment]
@Shibiz i fixed it, not running on docker, yet, it looked like we had the same problem)
the problem was that Flaresolverr was not running so it find the port trying to reach closed (for a reason i can't explain), anyway, i removed completely FS and installed it again and tadaaa, it works now, wish you luck with that :)

**Comment by Shibiz** [comment]
@EmaldIsBack Niiice !
I'm gonna look at another way to run it to try without docker
Bien ouej mec !

**Comment by ilike2burnthing** [comment]
For whatever reason the local port being used is 32797. Either change it to 8191 or use 32797 - http://192.168.1.36:32797 (you may need to port forward that as well).

**Comment by ngosang** [comment]
> For whatever reason the local port being used is 32797. Either change it to 8191 or use 32797 - http://192.168.1.36:32797 (you may need to port forward that as well).

Another Synologic user had the same issue => https://github.com/FlareSolverr/FlareSolverr/issues/54#issuecomment-756357002
I fixed the port in the documentation too => https://github.com/FlareSolverr/FlareSolverr/commit/66fe775d27783f2b79a07670ac5fb17fe4d8bacf

I think there are enough information to configure FlareSolverr.

**Comment by Shibiz** [comment]
I'm still stuck with the same issue..

Tried to remove all my containers :

docker stop flaresolverr 
docker rm flaresolverr
docker stop jackett
docker rm jackett


Tried to reinstall Jackett/Flaresolverr with both latest versions using this commands :

FOR Jackett

docker run -d \
  --name=jackett \
  -e PUID=1028 \
  -e PGID=100 \
  -e TZ=Europe/London \
  -e AUTO_UPDATE=true \
  -p 9117:9117 \
  -v /volume1/docker/:/config \
  -v /volume1/docker/:/downloads \
  --restart unless-stopped \
  ghcr.io/linuxserver/jackett

FOR Flaresolverr

docker run -d \
  --name=flaresolverr \
  --network=bridge \
  -p 8191:8191 \
  -e LOG_LEVEL=info \
  -e CAPTCHA_SOLVER=harvester \
  -e HARVESTER_ENDPOINT=https://127.0.0.1:5000/token \
  --restart unless-stopped \
  ghcr.io/flaresolverr/flaresolverr:latest
  
  Ending the same point : 
  
 When i visit Flaresolverr URL : 

http://192.168.1.36:8191/
{"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1610298513790,"endTimestamp":1610298513790,"version":"v1.2.3"}
 
When i try to add YGGTorrent Indexer in Jackett trying this 3 differents links in Flaresolverr URL fiel :

http://localhost:8191/ -> Gives me connection refuses
http://127.0.0.1:8191/ -> Gives me Network is unreachable
http://192.168.1.36:8191/ -> Gives me Network is unreachable

**Comment by ilike2burnthing** [comment]
http://192.168.1.36:8191/ is the correct one, but we'll continue this over on https://github.com/Jackett/Jackett/issues/10708
