### ISSUE TITLE
720pier cookies method doesn't work

### ISSUE THREAD

**Issue by balaustrada** [Jackett/Jackett#10643]
### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 

**Jackett Version**: v0.17.159

**Last Working Jackett Version**: (previous method worked for some time)

**Are you using a proxy or VPN?** [yes/no] yes

### Description

Hello everyone,

I'm unable to login to 720pier.ru using the new cookies method. The login failed with error:
`Login failed: Selector ":has(a[href^="./ucp.php?mode=logout&"])" didn't match`

This new method was implemented here:
https://github.com/Jackett/Jackett/commit/3c09866dc2df79890f6ed65ac807c982546253c0

### Screenshots
![Screenshot 2020-12-28 132133](https://user-images.githubusercontent.com/57346222/103214118-e62d5600-490f-11eb-98bd-9ec1892846ff.png)
![Screenshot 2020-12-28 132309](https://user-images.githubusercontent.com/57346222/103214120-e88fb000-490f-11eb-9df1-60c72fde04a4.png)

**Comment by burkasaurusrex** [comment]
+1 here. Worked through all the cookie troubleshooting, etc. and still getting the same error as above.

**Comment by ilike2burnthing** [comment]
Post an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by balaustrada** [comment]
Switched to a Windows machine (without VPN) as the configuration of the docker stack was complex. Even though the error stays there, please find attached the full log.
[log.txt](https://github.com/Jackett/Jackett/files/5747387/log.txt)

**Comment by ilike2burnthing** [comment]
Please ensure enhanced logging is enabled and try again. For some reason the first time it is ticked and applied on a fresh install, it doesn't actually enable, works after that though. Normal logs will have Info, Warn, and Error lines. Enhanced logs will also include Debug lines.

**Comment by honelnik** [comment]
same issue
[log.txt](https://github.com/Jackett/Jackett/files/5756576/log.txt)

**Comment by ilike2burnthing** [comment]
Thanks. I don't know if the site is actually semi-private, or just temporarily open for new registrations, but I made an account.

Seems I can add 720pier to Jackett, search and download, but if I try to reconfigure the indexer (and presumably if I waited for long enough), it fails. Not sure if this is an issue with the indexer or if the site is just really strict about cookies.

Adding the User-Agent option didn't make any difference (it was 'working' on my NAS anyway, so wasn't expecting it to), and using login details isn't an option as the site requires JavaScript.

I tried [v0.16.1204](https://github.com/Jackett/Jackett/releases/tag/v0.16.1204) (last release with the C# indexer), but it can't login either.

**Comment by bearsandbears** [comment]
I have this issue as well.  SSH into server to get cookie with same results.

**Comment by merqwury** [comment]
Any workaround for this? When I first set this up, everything was working fine, and now I'm getting the same issue as OP since last night

**Comment by 1ColdAssHonkey** [comment]
This error just hit me today when I was trying to setup a new instance of Jackett on Docker.  Up until today, the website accepted by cookie from my Windows' Jackett just fine.  It was only after I tried to copy the cookie from my Windows'  Jackett to the Docker install did this error message occur.  I went ahead and tried to refresh the cookie from the website, but that did not work either.  Now neither the Windows or the Docker installs work.  This website comes in real handy for Lakers games too!!!!

[log.txt](https://github.com/Jackett/Jackett/files/6006638/log.txt)

**Comment by ajarora** [comment]
Just to add to the above experiences, I'd installed Jackett for the first time ~12 January 2021 — and 720pier was working flawlessly here on my Mac until the other day (exactly 90 days, though this is probably coincidental as the cookies appear to be set to expire 1 year out).

**Comment by ilike2burnthing** [comment]
No matter what way I try configuring the credentials login for the indexer I get:
```
Ошибка отправки формы. Попробуйте ещё раз. Проверьте, включён ли JavaScript в вашем браузере.
```
```
A form submission error. Try again. Check to see if JavaScript is included in your browser.
```
So either I'm doing something wrong (very possible) and the error is just misleading, or it requires JavaScript.

**Comment by garfield69** [comment]
I have no issued using my cookie with the 720pier indexer to search and to download.

**Comment by merqwury** [comment]
Doesn't seem to be working once again.

 An error occurred while updating this indexer
Login failed: Selector ":has(a[href^="./ucp.php?mode=logout&"])" didn't match

**Comment by ilike2burnthing** [comment]
Log into the site again and get a new cookie for Jackett.

**Comment by merqwury** [comment]
> 
> 
> Log into the site again and get a new cookie for Jackett.

I've tried that already thru different browsers (and different IPs to match my Jackett's proxy) but none seems to have worked.

**Comment by 1ColdAssHonkey** [comment]
I also have tried several different ways and have not been able to get the tracker to work with Jackett.  I have tried three different accounts and three different computers and still get the same error message.  I have copied the cookie to notepad to make sure there is nothing added and even tried three different browsers, Firefox, Brave, and Edge.  I would really LOVE to get 720 working with Jackett, all of the other 36 sites I use work flawlessly with it.

**Comment by ilike2burnthing** [comment]
Does your cookie follow this pattern - `phpbb3_h6m7i_u=nnnnn; phpbb3_h6m7i_k=xxxxxxxxxxxxxx; phpbb3_h6m7i_sid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`?

**Comment by 1ColdAssHonkey** [comment]
No, both browsers are missing the "k=" value.  

Firefox:phpbb3_h6m7i_u=nnnnn; phpbb3_h6m7i_k=; phpbb3_h6m7i_sid= xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Brave:phpbb3_h6m7i_k=; phpbb3_h6m7i_u=nnnnn; phpbb3_h6m7i_sid= xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; 

Is there somewhere else I could get that value and plug it into the cookie?
Thanks for getting back to me,

   On Thursday, June 17, 2021, 11:11:28 AM PDT, ilike2burnthing ***@***.***> wrote:  
 
 


Does your cookie follow this pattern - phpbb3_h6m7i_u=nnnnn; phpbb3_h6m7i_k=xxxxxxxxxxxxxx; phpbb3_h6m7i_sid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?

**Comment by ilike2burnthing** [comment]
Odd... you could try the `cookies` tab `instead of the `headers` tab.

You could also try logging in using a private/incognito window with no addons/extensions enabled.

**Comment by 1ColdAssHonkey** [comment]
Just tried with private windows with all add-ons disabled and get the same results.  You can see the attached images of the cookies tab in both Brave and FF.


    On Thursday, June 17, 2021, 10:59:08 PM PDT, ilike2burnthing ***@***.***> wrote:  
 
 


Odd... you could try the cookies tab instead of the headers` tab.

You could also try logging in using a private/incognito window with no addons/extensions enabled.

**Comment by ilike2burnthing** [comment]
Attachments only work when post directly on GitHub's site unfortunately, but I don't doubt that's the case.

Seemingly `_k` is the session key, and is only used when the `remember me` box is ticked at login (for 720pier this is the first box `Запомнить меня`). So try that and see if it works in Jackett.

**Comment by honelnik** [comment]
Today after i tried copying the portion of the cookie following the template  @ilike2burnthing posted, it works

**Comment by 1ColdAssHonkey** [comment]
Yea......It works for me also!!!!!
This is the first time I have been able to automatically search 720 with Hydra2/Jackett in over 8 months!

Here are the steps I had to take:

1. Removing the old "remember me" keys and then logging out.
2. Logging back in and checking the "remember me/Запомнить меня" box.
3. Verify that the key was created in your 720pier user profile.  
4. Get the cookie from your browser.
5. Truncate the cookie to make sure it only has the following keys: u= k= sid= (in that order)  My cookie had a track= attached   as the first variable.
6. Copy that cookie into Jackett and test.

Thank you for all the support @ilike2burnthing !!  Jackett is truly a FANTASTIC program!!

**Comment by balaustrada** [comment]
> 
> 
> Yea......It works for me also!!!!!
> This is the first time I have been able to automatically search 720 with Hydra2/Jackett in over 8 months!
> 
> Here are the steps I had to take:
> 
>     1. Removing the old "remember me" keys and then logging out.
> 
>     2. Logging back in and checking the "remember me/Запомнить меня" box.
> 
>     3. Verify that the key was created in your 720pier user profile.
> 
>     4. Get the cookie from your browser.
> 
>     5. Truncate the cookie to make sure it only has the following keys: u= k= sid= (in that order)  My cookie had a track= attached   as the first variable.
> 
>     6. Copy that cookie into Jackett and test.
> 
> 
> Thank you for all the support @ilike2burnthing !! Jackett is truly a FANTASTIC program!!

This also works for me. Thank you all for your help. Closing this.

**Comment by keithcq71** [comment]
I still get this error . 

Login failed: Selector ":has(a[href^="./ucp.php?mode=logout&"])" didn't match

**Comment by balaustrada** [comment]
Did you follow the steps above? Setting the remember me option + truncating the cookie. For me it still works.

**Comment by keithcq71** [comment]
Yes . I have my cookie like this : 
track=xxxx;k=xxxxx; sid=xxxxxxxxxxx . I tried it without track as also .

**Comment by keithcq71** [comment]
I am not sure how to verify step 3 on the site .

**Comment by keithcq71** [comment]
This is not my cookie . This is a version where I changed the numbers. Here is what Im posting:  track=u=63311; phpbb3_h6m7i_k=uq4zzfbgklqb0ynz; phpbb3_h6m7i_sid=f8f123e1809fd09fd86ec4a81d8834f7fd86ec4a81d8834f7

**Comment by balaustrada** [comment]
You need to remove the track part of the cookie and keep the formatting, you'll start with something like this:

phpbb3_h6m7i_track=blabla; phpbb3_h6m7i_u=somenumbers; phpbb3_h6m7i_k=blabla; phpbb3_h6m7i_sid=blabla

But what you'll have to insert in jackett is:

phpbb3_h6m7i_u=somenumbers; phpbb3_h6m7i_k=blabla; phpbb3_h6m7i_sid=blabla

**Comment by keithcq71** [comment]
That worked. It seems the issue was my seedbox . When I tested it on Jackett on my PC ,it worked . Thanks . Next do I input this info in Sonarr ?

**Comment by ilike2burnthing** [comment]
Nothing special needs to be added to Sonarr, just add the Jackett information for that indexer like you would for any other indexer.

**Comment by keithcq71** [comment]
under Jackett indexer setting in sonarr?

**Comment by ilike2burnthing** [comment]
Sonarr > Settings > Indexers > + > Torznab

Name: 720pier
URL: click the `Copy Torznab Feed` button in Jackett for 720pier and paste it here
API Key: copy and paste it from the top of Jackett
Categories: TV (or be specific about which ones you want to search)

Then click Save and you're done.

**Comment by keithcq71** [comment]
I can add it on my Sonarr locally but cant add a download client . On 2 seedboxes , I cant instal the indexers . Thanks for everyones help

**Comment by ilike2burnthing** [comment]
Do you have Jackett running on your seedboxes too? You'll have to add 720pier on them as well, then use those Jacketts' info to add the 720pier indexers to your respective seedboxes.

As for download clients - https://wiki.servarr.com/en/sonarr/settings#download-clients

If you need further help with Sonarr, see https://forums.sonarr.tv/

**Comment by keithcq71** [comment]
Thanks . I was able to install it one seedbox but Im still waiting to hear back from the provider for the main one . Now that I have this set up , will it grab the new content for categories I have selected?

**Comment by ilike2burnthing** [comment]
Assuming you set up the shows you want to be monitored in Sonarr, yes.

**Comment by keithcq71** [comment]
I set up categories but did not think I could have sports games monitored

**Comment by ilike2burnthing** [comment]
Really depends. Live games probably not, but regular programs, yea. If TVDB has it, then yes, e.g. https://thetvdb.com/search?menu%5Btype%5D=series&query=nfl

**Comment by garfield69** [comment]
v0.20.2679
