### ISSUE TITLE
[REQ]jmvbt.com public JAV

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#10650]
Public jav movie share torrent site.

Search engine and torrents working.

https://jmvbt.com

![1](https://user-images.githubusercontent.com/36575395/103248591-48bc3b80-497c-11eb-967f-417c097bde8e.JPG)
![2](https://user-images.githubusercontent.com/36575395/103248593-4bb72c00-497c-11eb-93ad-3b16fe89ca5a.JPG)

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
