### ISSUE TITLE
[mejortorrent] System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by MrAldisaADS** [Jackett/Jackett#10659]
### Environment

**OS**: Ubuntu Server (LinuxServer's Docker Image)

**Jackett Version**: 0.17.159

**Are you using a proxy or VPN?** No

### Description

Try to download any torrent file from this tracker, from Jackett itself, or from other application (like Sonarr or Radarr).

I think it's the same issue of #6988 or #9296, so I think the download links have changed again. The torrent file downloads from the link on the trackers website, and it works. (I I haed to comment on those issues instead of opening a new one, sorry, this is my first issue).

### Logged Error Messages

```
Error downloading. indexer: mejortorrent path: https://www.mejortorrents.net/peli-descargar-torrent-13515-Men-in-Black-Hombres-de-negro-4K.html
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.MejorTorrent.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MejorTorrent.cs:line 140
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 56
```

**Comment by MrAldisaADS** [comment]
I tried reverting the changes of 700e309405955d23ff5a6baf13746d9b46aac42e and it started working again, and I think I know the reason . This tracker sometimes returns a .zip in the download link with a virus (I noted it happens with Windows NOT using TOR):

`Pincha <a href='#' onclick="post('MALICIOUS_URL_REDACTED_FOR_SAFETY', {table: 'peliculas', name: 'sed de venganza_2019es.torrent'});"><b>aqui</b></a> para descargar el torrent.</font>`

But sometimes (always when using Linux or TOR), it returns the webpage with the correct download link:
`<a href='/tor/peliculas/sed de venganza_2019es.torrent'><b>aqui</b></a> para descargar el torrent.`

The code fixed in 700e309405955d23ff5a6baf13746d9b46aac42e  contemplates second scenario, and the older one, first scenario, so the code should be able to identify this two scenarios. (I'm not a C# developer, so I can't try but I don't know if it will work or I will have it "quick enough".

**Comment by ilike2burnthing** [comment]
See also: https://github.com/Jackett/Jackett/issues/10616

**Comment by MrAldisaADS** [comment]
I read it, and it says that happens with the .es domain, this is happening with .net domain (since I know this tracker the vbs stuff has always been an issue for me, before using Jackett), so I'm trying to parse both so we don't have this problem again. (Or I'm missing something here?)

**Comment by MrAldisaADS** [comment]
So, I tried quick and dirty with this:
`            try
            {
                // Try to parse <a href='/tor/peliculas/sed de venganza_2019es.torrent'><b>aqui</b></a>
                downloadUrl = SiteLink + dom.QuerySelector("a[href^=\"/tor/\"]").GetAttribute("href");
            } catch (NullReferenceException ex)
            {
                // Try to parse <a href='#' onclick="post('MALICIOUS_URL_REDACTED_FOR_SAFETY', {table: 'peliculas', name: 'sed de venganza_2019es.torrent'});">
                var onClickParts = dom.QuerySelector("a[onclick*=\"/torrent\"]").GetAttribute("onclick").Split('\'');
                downloadUrl = $"{SiteLink}tor/{onClickParts[3]}/{onClickParts[5]}";
            }`

and the tracker works fine, first trying the non .vbs link, and if fails, the other one. I'm sure the asignee will come with a better solution tho :P

**Comment by ilike2burnthing** [comment]
Yea, different domain (one we don't use and looks dodgy), but same issue and some more info for @ngosang to work with.
