### ISSUE TITLE
[REQ]javhoo.com

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#10651]
Public jav movie share torrent site.

Search engine and torrent working.

https://www.javhoo.com/

![1](https://user-images.githubusercontent.com/36575395/103248721-faf40300-497c-11eb-8956-600bb29f9a6f.JPG)
![2](https://user-images.githubusercontent.com/36575395/103248726-fdeef380-497c-11eb-85eb-cc6ad2b3bc6f.JPG)

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
