### ISSUE TITLE
[cinemamovies] Exception (cinemamovies): Login Failed, got redirected.: Parse error (Test)

### ISSUE THREAD

**Issue by plsharevme** [Jackett/Jackett#10652]
Open Media Vault, Docker jackett ..Jackett Version v0.17.159 

cinemamovies was successful add into jackett, and test passed. but after few hour the test well eventually fail, seem like the cookies was expired after each few hour .

Tried 2 time with same result.

I have save the auto login at chrome, after revisit the website, it dun need asking for login detail. Auto login with no problem
here the server log.

https://pastebin.com/H3ynxukR

**Comment by ilike2burnthing** [comment]
The cookie is IP dependent. Are you using a VPN or proxy which would cause your IP address to change every few hours?

If not, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
