### ISSUE TITLE
all my tracker found 0 results!!

### ISSUE THREAD

**Issue by thenamelessthing** [Jackett/Jackett#1065]
On jackett version: 0.7.1025.0
Mono version:  Mono JIT compiler version 4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan  3 11:48:26 UTC 2017)

-------------------------------
Since a couple of day ( I don't know when exactly) Jackett doesn't find any result on all of my tracker.

I deleted the tracker et added them again without any change.

Here is the log:
[log.txt](https://github.com/Jackett/Jackett/files/775849/log.txt)

**Comment by kaso17** [comment]
make sure mono-devel is installed

**Comment by thenamelessthing** [comment]
@kaso17 

It was not installed, so after installed and restarted jackett service everything seem working properly

 dpkg -s mono-devel
Package: mono-devel
Status: install ok installed
Priority: optional
Section: cli-mono
Installed-Size: 58971
Maintainer: Debian Mono Group <pkg-mono-group@lists.alioth.debian.org>
Architecture: all
Source: mono
Version: 4.6.2.16-0xamarin1
