### ISSUE TITLE
[req] new korean public trackers

### ISSUE THREAD

**Issue by plsharevme** [Jackett/Jackett#10663]
torrentbomb https://torrentb.site/ is down already 2 day .

now jackett index only left 1 public korean tracker " torrentview"
just ask can weather add more of korean public tracker, couse now only left 1. It pain for korean drama & movies lover.

i found a list of public tracker maybe can add into the indexer some of them? and i tested the speed very good.

One | Mr. Torrent | https://torrentsee43.com ▶ | ★★★ⓚ TOP10
-- | -- | -- | --
2 | Torrent QQ | https://torrentqq65.com ▶ | ★★★ ⓣ ⓚⓢ Weekly B
3 | Torrent Tips | https://torrenttip16.com ▶ | ★★★ⓒⓚ TOP10
4 | Torrent diamond | https://torrentdia.com ▶ | ★★★ⓒⓚ Popular data
5 | Todawa | https://todawa.com ▶ | ★★ⓒ Popular data
6 | See again | https://ttobogo.net ▶ | ★★ⓒ Popular data
7 | Torrent | https://torrentsir27.com ▶ | ★★ ⓣ ⓚ popular data
8 | Torrent Whiz | https://torrentwiz16.me ▶ | ★★ ⓒⓚ Weekly B
9 | Chanto | https://jjangto.com ▶ | ★★ ⓣ ⓚ popular data
10 | Torrent Max | https://torrentmax12.com ▶ | ★★ ⓣ ⓢ Day/Week/Month B

i tested number 4 the seeder is average alot ,with decent speed. other i no test yet.

appreciate.!

**Comment by Quentin-M** [comment]
That would be much appreciated~~

**Comment by RemyRobert** [comment]
Nice request, following the issue !

**Comment by adan89lion** [comment]
Torrent QQ (토렌트큐큐) changes its domain very frequently, so it requires to update the URL frequently.
Torrent Dia (토렌트디아) is down for several days too (perhaps CloudFlare misconfiguration).

There are several blogs to index and test these website often and it is recommended to check them out.
- https://ts.devbj.com/371
- http://jaewook.net/archives/2613

**Comment by ilike2burnthing** [comment]
@alamia442
> http://www.torrentreel33.com/home.php or www.토렌트릴.com
>
> https://www3.torrentzoa.com/

**Comment by garfield69** [comment]
In order to track the progress of implementing each of these indexers, it is far easier to have a separate ticket for each.
This way, they can be assigned to separate contributors if any, track their progress separately, and if any go offline or get abandoned/closed/removed then the relevant ticket can be closed.

In future, please raise separate tickets for any new site requests.

**Comment by garfield69** [comment]
as a spurious side note, I detest the epilepsy inducing strobing adverts predominant on Korean sites. That flashing rubbish is giving me a headache.
