### ISSUE TITLE
[New Tracker REQ] The-Torrents

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1066]
**Indexer Name**
The-Torrents

**Type**
Movies, TV, Audio, XXX, PC, Console

**Indexer URL**
http://the-torrents.org/

**Indexer Language**
Romanian, English

**Invite**
Signup is open for a limited time:
http://the-torrents.org/signup.php

**Note**
The-Torrents is a medium-sized general Romanian tracker with almost 17K torrents. It's a good replacement for SceneFZ which seems to be gone for good.

**Comment by kaso17** [comment]
joined

**Comment by kaso17** [comment]
added with 22b66e913dc1c7df300f7537f3d2b37392bce2d0
