### ISSUE TITLE
[nyaasi] Exception (nyaasi): An existing connection was forcibly closed by the remote host.: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by nareshn1323** [Jackett/Jackett#10669]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: windows 10

**.Net Runtime**: 4.7.03190 [.Net-Core/.Net-Framework/Mono]

**.Net Version**:  classic

**Jackett Version**: v0.17.166

**Last Working Jackett Version** :v0.17.166

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Can you access the site from the same device and IP? https://github.com/Jackett/Jackett/wiki/Troubleshooting#an-existing-connection-was-forcibly-closed-by-the-remote-host

**Comment by nareshn1323** [comment]
Yes, I can access site normally.

**Comment by ilike2burnthing** [comment]
Whoops, this one slipped me by. Apologies for the delay.

Try upgrading .NET Framework to 4.8. What Windows 10 version number are you on, as that should be done automatically?

Also, if you're on Windows 10 Pro, try running a fresh install of Jackett in Windows Sandbox.

If none of that sheds any light, please post an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by nareshn1323** [comment]
I'm using windows 10 LTSC.

**Comment by ilike2burnthing** [comment]
Ah, well that would explain why it hasn't updated. Not sure if you can manually update .NET Framework, but give it a try - https://dotnet.microsoft.com/download/dotnet-framework/net48

Either way, are you happy to close this issue?

**Comment by nareshn1323** [comment]
Upgraded .NET to 4.8 and its working again. Thanks.
You can close the issue.
