### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid (Test)

### ISSUE THREAD

**Issue by Enohriel** [Jackett/Jackett#10661]
Hello there.

I'm trying to make Jackett work again with YGG since the cloudflare protection.

I have an issue with FlareSolverr/Jackett.

FlareSolverr is running on Docker.
Jackett is running as a linux service.

It's doing this, either with YggCookie or Yggtorrent :

![image](https://user-images.githubusercontent.com/50456985/103298376-7b0c7e00-49fa-11eb-91d6-8ba512f5a49f.png)

**Comment by Enohriel** [comment]
There is no solution in #10520.

**Comment by ilike2burnthing** [comment]
Is the cause of your issue described here? https://github.com/Jackett/Jackett/wiki/Troubleshooting#the-cookies-provided-by-flaresolverr-are-not-valid

**Comment by Enohriel** [comment]
No proxy, No VPN and same device, same network indeed.

**Comment by ilike2burnthing** [comment]
Seems like I can't get yggtorrent/cookie to work either, not sure if it's a Jackett issue or FlareSolverr.

yggcookie is letting me search, but can't download because it isn't actually logged in (and all the results are duplicated, which I can't figure out either).

**Comment by ngosang** [comment]
@ilike2burnthing could you test again?

**Comment by ilike2burnthing** [comment]
Working, just still dealing with https://github.com/Jackett/Jackett/issues/10655#issuecomment-756892534 when trying to download using yggcookie
