### ISSUE TITLE
Doesn't work on M1 MacBook Air

### ISSUE THREAD

**Issue by FatSandwich** [Jackett/Jackett#10668]
I get this error every time I click on install_service_macos
```
ERROR: Jackett already seems to be running as a service. Please stop it before running this script again.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

When I try to unload it, it says 
`Unload failed: 5: Input/output error`

When I check in LaunchAgents there is no file called org.user.Jackett.plist

Also, when I go to 127.0.0.1:9117
It doesn’t show anything

Any Fix???

Do I create the plist file?

**Comment by ilike2burnthing** [comment]
Can you run it without installing as a service? https://github.com/Jackett/Jackett#installation-on-macos

Apologies, I have next to no experience with MacOS, so I'll have to pass this on.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/10755
