### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): FlareSolverr was able to process the request, but a captcha was detected. Message: Captcha detected but no automatic solver is configured.: FlareSolverr was able to process the request, but a captcha was detected. Message: Captcha detected but no automatic solver is configured. (Test)

### ISSUE THREAD

**Issue by charlesb11** [Jackett/Jackett#10662]
Hello,

I'm getting an issue with yggtorrent in jackett, I'm using flaresolverr but still get this error message:

Jackett.Common.IndexerException: Exception (yggtorrent): FlareSolverr was able to process the request, but a captcha was detected. Message: Captcha detected but no automatic solver is configured.

Proxy type is disabled
and I input the FlareSolverr API URL

**Comment by Hakujou** [comment]
You've encountered a captcha when FlareSolverr was passing CloudFlare check.
If you can open YggTorrent from a browser using the same IP than Jackett, it often helps.

You can also configure a captcha solver through FlareSolverr.

This is not a Jackett issue.

**Comment by charlesb11** [comment]
> You've encountered a captcha when FlareSolverr was passing CloudFlare check.
> If you can open YggTorrent from a browser using the same IP than Jackett, it often helps.
> 
> You can also configure a captcha solver through FlareSolverr.
> 
> This is not a Jackett issue.

can you please explain to me in simple words how to configure a captcha solver through FlareSolverr ?

**Comment by ilike2burnthing** [comment]
Just add the env `CAPTCHA_SOLVER` with the value `hcaptcha-solver` - https://github.com/FlareSolverr/FlareSolverr#captcha-solvers
