### ISSUE TITLE
[REQ][NEW][PRIVATE] New tracker "Trackeros"

### ISSUE THREAD

**Issue by IvanpAEG** [Jackett/Jackett#10670]
Private spanish (es-es) tracker for tv shows and movies.

Link https://trackeros.tk/

Same interfae as "https://purovicio.in/" so maybe its indexer can work with "Trackeros".

**Comment by xexu1974** [comment]
Por favor quita este tracker de aquí y más la captura. 
Creo que tendrías q haber preguntado a los administradores del tracker.

**Comment by ilike2burnthing** [comment]
@xexu1974 does the site have a policy against 3rd-party integration, or any discussion of it outside of the site itself?

**Comment by xexu1974** [comment]
No tenemos ninguna política de no integración pero el usuario lo ha hecho sin consultar al staff y además ha puesto una captura del contenido de un server privado.

**Comment by ilike2burnthing** [comment]
Completely understandable. I've removed the screenshot and edit history.

I'll leave this post open for now, to let the user discuss this with the site staff. It will close in 7 days if @IvanpAEG doesn't reply.

**Comment by xexu1974** [comment]
Gracias por quitar la captura, era importante para el staff que no salga ningún contenido del tracker.

**Comment by IvanpAEG** [comment]
> Gracias por quitar la captura, era importante para el staff que no salga ningún contenido del tracker.

Cierro el issue, perdón por las molestias, no sabia que era necesario consultarlo ni lo de la imagen.
