### ISSUE TITLE
[New Tracker REQ] torrent9.biz

### ISSUE THREAD

**Issue by foXaCe** [Jackett/Jackett#1067]
Hello , please add http://www.torrent9.biz/ tracker

**Comment by D4rk56** [comment]
+1

**Comment by bidulle95** [comment]
+1

**Comment by Nerwysh** [comment]
+1

**Comment by bentux** [comment]
+1

**Comment by D4rk56** [comment]
For help : https://raw.githubusercontent.com/SickRage/SickRage/8634d3730c1015c653dcdc4de888cd08355239e8/sickbeard/providers/torrent9.py

**Comment by D4rk56** [comment]
Thanks @ChibiTomo 👍

**Comment by adamwinn** [comment]
Added with #1250.  Thanks @ChibiTomo

**Comment by RoloSoze** [comment]
@adamwinn It might be a good idea to remove the username & password fields since the tracker is open/public and doesn't require registration.

**Comment by adamwinn** [comment]
@RoloSoze the definition file doesn't have username and password fields.  I think I asked @kaso17 a while ago why I was getting the username/password fields for another public tracker and he said to just press the Okay button.  I'm not sure why they're not present for TPB tho

**Comment by RoloSoze** [comment]
@adamwinn Yes, you can leave the username & password fields blank & press Okay - that'll work for any public tracker. It just makes more sense to remove them altogether since they're not needed. Case in point, TPB, RARBG, EZTV, KAT, Lime Torrents, Sky Torrent, Torrentz2, etc. Let's see if @kaso17 is able to help out with this when he's back. It's just a cosmetic / usability feature, nothing to do with functionality :)

**Comment by kaso17** [comment]
to remove them just set settings to an empty array, if it's not set at all it defaults to username/password. See 60b9a34ceae3c155316ce9559873cce2440c5550

**Comment by ilike2burnthing** [comment]
https://www.oxtorrent.me/ - Error 522 - Connection timed out
Proxies still working

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://www.oxtorrent.me/ - Error 522 - Connection timed out
> Proxies still working

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrent9.to/ - working
https://torrent9.to/search_torrent/2021.html (or any single word search) - working

https://torrent9.to/search_torrent/2021-720p.html (or any multi-word search) - blank page or `STORAGE_WRITE_ERROR`

**Comment by garfield69** [comment]
fully functional again.
