### ISSUE TITLE
[pirateiro] Exception (pirateiro): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by renechavez55** [Jackett/Jackett#10686]
Environment
OS: Windows 8.1

.Net Runtime: [Net-Framework]

.Net Version: .NET 4..8

Jackett Version: Version v0.17.166

Last Working Jackett Version:

Are you using a proxy or VPN? [no]

Description
1. start the tracker test
2. gives an error message

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

An error occurred while testing this indexer
Exception (pirateiro): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured

### Screenshots

 
![image](https://user-images.githubusercontent.com/66539244/103432245-7be81000-4bb2-11eb-8278-6b9f31725019.png)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
