### ISSUE TITLE
[yourbittorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by renechavez55** [Jackett/Jackett#10689]
Environment
OS: Windows 8.1

.Net Runtime: [Net-Framework]

.Net Version: .NET 4..8

Jackett Version: Version v0.17.166

Last Working Jackett Version:

Are you using a proxy or VPN? [no]

Description
1. start the tracker test
2. gives an error message

### Logged Error Messages

An error occurred while testing this indexer
Found no results while trying to browse this tracker

### Screenshots

 
![image](https://user-images.githubusercontent.com/66539244/103432349-dfbf0880-4bb3-11eb-8a90-d117a3e4c688.png)

**Comment by ilike2burnthing** [comment]
Blank search no longer working:
https://yourbittorrent.com/?v=&c=&q=
```
Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be 
of type mysqli_result, bool given in /home/yb/core/search.php:197 Stack trace: #0 
/home/yb/core/search.php(197): mysqli_num_rows() #1 /home/yb/index.php(59): 
include('...') #2 {main} thrown in /home/yb/core/search.php on line 197
```
