### ISSUE TITLE
The copy Torznab feed button doesn't work. 

### ISSUE THREAD

**Issue by BLX-S** [Jackett/Jackett#1068]
I succesfully installed Jackett on my windows server but the buttons in the WebGUI didn't work in the included IE browser so I installed chrome to activate external access. After this I tried to press the button copy torznab feed but it didn't work. My browser isn't blocking any JS or other weird stuff like that. Don't know if I'm doing anything wrong or not. 

I copied the general logs here for any additional info send a reply thanks in advance:

Feb 15, 2017 05:34:58 PM	Info	
redirecting to /Admin/Dashboard
Feb 15, 2017 05:31:49 PM	Info	
Service started
Feb 15, 2017 05:31:49 PM	Info	
set HttpListener.IgnoreWriteExceptions = true
Feb 15, 2017 05:31:49 PM	Info	
Starting web server at http://*:9117/
Feb 15, 2017 05:31:49 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\xtremezone.yml
Feb 15, 2017 05:31:49 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\worldofp2p.yml
Feb 15, 2017 05:31:49 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\utorrents.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\ultrahdclub.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\uhdbits.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\trancetraffic.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\totheglory.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torviet.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrentz2.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrentsmd.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrentsectorcrew.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrentproject.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrenting.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrenthr.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrentbd.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\theshinning.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\thepiratebay.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\thehorrorcharnel.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\tenyardtracker.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\t411.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\skytorrents.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\shellife.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\sharespacedb.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\shareisland.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\secretcinema.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\sdbits.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\rodvd.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\rockhardlossless.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\rapidetracker.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\qctorrent.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\polishsource.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\newretro.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\nethd.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\nachtwerk.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\myspleen.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\mteamtp.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\mononokebt.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\majomparade.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\magico.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\losslessclub.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\linkomanija.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\limetorrents.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\leparadisdunet.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\kickasstorrent.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\kickasstorrent-kathow.yml
Feb 15, 2017 05:31:48 PM	Info	
Loading Cardigann definition C:\ProgramData\Jackett\Definitions\kapaki.yml

**Comment by kaso17** [comment]
Related to #1039
Please let me know the exact browser versions where the copy button doesn't work.
As a workaround you should be able to use "right click/Copy link address".

**Comment by BLX-S** [comment]
I'm on chrome Version 56.0.2924.87 (64-bit) 
I tried right clicking as you said but it doesn't give me copy link address. Out of sheer desperation I also tried to inspect element but there was nothing there as well.

**Comment by kaso17** [comment]
If the buttons are still a <button> element in the inspector view you're running an old jackett version, it should be an <a> element with corresponding href set.

**Comment by BLX-S** [comment]
Just updated. Still doesn't work

**Comment by kaso17** [comment]
Are they links now?
It should look like this:
https://image.ibb.co/dLDsAa/copylink.png

**Comment by BLX-S** [comment]
Thanks for your help. I solved the problem. I used another PC with firefox and it worked.

**Comment by JulianFRL** [comment]
In 2020 this has not been solved as well, Tried Chromium Edge, FireFox and Google chrome but still the 'Copy Torznab Feed' button does not work. And I am on the latest version.....
