### ISSUE TITLE
  Exception (7torrents): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by renechavez55** [Jackett/Jackett#10684]
### Environment

**OS**: Windows 8.1

**.Net Runtime**: [Net-Framework]

**.Net Version**: .NET 4..8

**Jackett Version**:  Version v0.17.166

**Last Working Jackett Version**:  

**Are you using a proxy or VPN?** [no]

### Description

1. start the tracker test
2. gives an error message

### Logged Error Messages

An error occurred while testing this indexer
Exception (7torrents): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured

### Screenshots

[Place any screenshots of the issue here if needed]
![image](https://user-images.githubusercontent.com/66539244/103432090-47735480-4bb0-11eb-859d-ed9aa92d3bfa.png)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
