### ISSUE TITLE
[nebulance] Exception (nebulance): Invalid URI: The format of the URI could not be determined.: Parse error (Config)

### ISSUE THREAD

**Issue by NiNiyas** [Jackett/Jackett#10691]
### Environment

**OS**: Windows 7

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:  N/A

**Jackett Version**: v0.17.166

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?** [yes/no] : No

### Description

I am unable to configure Nebulance. No 2FA enabled.

### Logged Error Messages

`Jackett.Common.IndexerException: Exception (nebulance): Invalid URI: The format of the URI could not be determined.`
### Screenshots

Not needed

**Comment by ilike2burnthing** [comment]
Are you using FlareSolverr? If so, check it is correctly configured - https://github.com/Jackett/Jackett/wiki/Troubleshooting#error-connecting-to-flaresolverr-server

If not, please provide an enhanced log of the failed login - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by NiNiyas** [comment]
Hi. I am using FlareSolverr. When I visit the URL I see this: `{"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1609482664909,"endTimestamp":1609482664910,"version":"v1.2.1"}`

[log.txt](https://github.com/Jackett/Jackett/files/5758680/log.txt)

**Comment by ilike2burnthing** [comment]
FlareSolverr looks ok then if you're using that same link in Jackett.

I need the full enhanced log of the issue, not just the individual error.

**Comment by NiNiyas** [comment]
Sorry. Here you go.
[log.txt](https://github.com/Jackett/Jackett/files/5758715/log.txt)

**Comment by ilike2burnthing** [comment]
Error:
```
Error Jackett.Common.IndexerException: Exception (nebulance): Invalid URI: The format of the URI could not be determined.
 ---> System.Exception: Parse error
 ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Jackett.Common.Indexers.Nebulance.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\Nebulance.cs:line 131
```
Refers to:
https://github.com/Jackett/Jackett/blob/1712f3ca810b8de83c5de6c6d6c15e50e85c5bb0/src/Jackett.Common/Indexers/Nebulance.cs#L130-L131
Which relates to:
```
<!--td class="center">
    <div title="Episode">
        <a href="torrents.php?filter_cat[1]=1"><img src="static/common/caticons/episode.png" /></a>
    </div>
</td-->
<td class="center banner_col">
  
    <a href="/torrents.php?action=show&showid=20219">
     
       <img class="banner_col" src="https://images.nebulance.io/images/betrayed-2016.jpg" />
    </a>
</td>
```
So I think it's picking up the category icon rather than the banner, and unable to process it. They say a little knowledge is a dangerous thing, but hey 😋 

I don't have an account, so I'll need you to check this for me. Download this .zip, extract the Windows installer, and update Jackett with it. Run a search and let me know if it's successful and if the posters are displayed when you hover over the result names.
https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/2557/artifacts?artifactName=drop&api-version=6.0&%24format=zip

**Comment by NiNiyas** [comment]
It's working now, but the posters are not displayed.

**Comment by ilike2burnthing** [comment]
Were posters ever displayed?

**Comment by NiNiyas** [comment]
I don't know honestly. I use it for Sonarr.

**Comment by ilike2burnthing** [comment]
Ah kk. Well I'll push the 'fix' as it least it's in a functional state now, but I'll leave this issue open for someone else to have a look at.

You can just continue to use that build until the next one is published in ~14hrs.

**Comment by NiNiyas** [comment]
OK. Thanks for fixing this.
