### ISSUE TITLE
Load failed: 5: Input/output error OR Load failed: 119: Service is disabled | macOS 11.1

### ISSUE THREAD

**Issue by frykauf** [Jackett/Jackett#10692]
I don’t think it relates to the issue #8329 sgarroo had since his LaunchAgent at least loads.
When I check apps where I can see what Launch Agents are enabled, it shows Jacket as enabled.

Could you please tell me what would be the right way to fix this so everything works properly?

1st run by opening in finder

```
/Users/Anon/Downloads/Jackett/install_service_macos ; exit;
Load failed: 5: Input/output error
ERROR: Agent could not be loaded. Please open an issue on https://github.com/Jackett/Jackett/issues and paste the output.
*Jackett directory*: /Users/Anon/Downloads/Jackett
*LaunchAgents permissions*:
drwx------   10 Anon  staff   320 Jan  1 08:31 .
drwx------+ 140 Anon  staff  4480 Dec 22 21:07 ..
-rw-r--r--@   1 Anon  staff  6148 Oct 24  2018 .DS_Store
-rw-r--r--    1 Anon  staff   704 Jan  1 08:31 org.user.Jackett.plist
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

1st run with sudo
```
sudo /Users/Anon/Downloads/Jackett/install_service_macos 
Password:
Could not print domain: 125: Domain does not support specified action
Could not print domain: 125: Domain does not support specified action
ERROR: Agent was loaded but is not running. The installation might have failed.
Please open an issue on https://github.com/Jackett/Jackett/issues and paste following information:
*Jackett directory*: /Users/Anon/Downloads/Jackett
*launchctl info*:

*LaunchAgents permissions*:
drwx------   10 Anon  staff   320 Jan  1 03:19 .
drwx------+ 140 Anon  staff  4480 Dec 22 21:07 ..
-rw-r--r--@   1 Anon  staff  6148 Oct 24  2018 .DS_Store
-rw-r--r--    1 root    staff   704 Jan  1 08:06 org.user.Jackett.plist
```

2nd run with sudo
```
sudo /Users/Anon/Downloads/Jackett/install_service_macos 
/Users/Anon/Library/LaunchAgents/org.user.Jackett.plist: Service is disabled
Load failed: 119: Service is disabled
ERROR: Agent could not be loaded. Please open an issue on https://github.com/Jackett/Jackett/issues and paste the output.
*Jackett directory*: /Users/Anon/Downloads/Jackett
*LaunchAgents permissions*:
drwx------   10 Anon  staff   320 Jan  1 08:07 .
drwx------+ 140 Anon  staff  4480 Dec 22 21:07 ..
-rw-r--r--@   1 Anon  staff  6148 Oct 24  2018 .DS_Store
-rw-r--r--    1 root    staff   704 Jan  1 08:08 org.user.Jackett.plist
```

**Comment by ilike2burnthing** [comment]
Related? https://github.com/Jackett/Jackett/issues/10668

Unfortunately, as I said there, I'm not much help when it comes to MacOS.

Can you run it without installing as a service? https://github.com/Jackett/Jackett#installation-on-macos

Are you able to install other programs in a similar manner?

**Comment by frykauf** [comment]
Tried launching it manually. Works perfectly.

Don’t know why the install as service script doesn’t work, but many mac users posted their issues with the launch service as well.

**Comment by frykauf** [comment]
[Temporary fix]
Automatically launch the binary file in terminal on login.

Goto: System Preferences>Users & Groups>Choose your account (current user)>Login Items

Drag & drop the „jacket“ executable file into the window.

----
Only downside - now the terminal window has to stay open.

**Comment by ilike2burnthing** [comment]
@garfield69 I'm assuming you use the install service option on your MacOS VM. Any reason it wouldn't be working in this case?

**Comment by garfield69** [comment]
No idea. Mine worked first time out of the box. And the updater keeps on updating without issue too. Tested on my Big Sur and Mojave images.
I'm not a regular Mac user, I just start the image to test once in a while. If stuff goes wrong I'm in the dark as any noob.
We really need a OSx expert.
@majorsl @thebluepotato We could use your help here Thanks.

**Comment by majorsl** [comment]
Maybe try:

launchctl load -w /Users/Anon/Library/LaunchAgents/org.user.Jackett.plist

If it complains, put sudo in front of that.  You may be asked for your password.  That should load (re-enable) a disabled launchd item that was marked disabled for whatever reason.

**Comment by Poseidon8707** [comment]
> launchctl load -w /Users/Anon/Library/LaunchAgents/org.user.Jackett.plist

It works! Thank you.
