### ISSUE TITLE
Xthor

### ISSUE THREAD

**Issue by foXaCe** [Jackett/Jackett#1070]
xthor contains error

IWebClient.GetString(Url:https://api.xthor.bz/?passkey=x&search=&category=): No encoding detected, defaulting to UTF-8

IWebClient.GetString(Url:https://api.xthor.bz/?passkey=xe&search=&category=): Got header without charset: https://api.xthor.bz/?passkey

**Comment by kaso17** [comment]
It's a non critical error but should be fixed with 0490ef5bb446963d366df607c7b04588fb804e71
