### ISSUE TITLE
[exttorrents] Exception (exttorrents): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by AlienProber** [Jackett/Jackett#10702]
An error occurred while testing this indexer
Exception (exttorrents): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured
Click here to open an issue on GitHub for this indexer.

**Comment by AlienProber** [comment]
Thanks

**Comment by ilike2burnthing** [comment]
You also didn't provide the requested information, but as I posted there - https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured

**Comment by AlienProber** [comment]
I gave you everything there was.  That said thanks for the link. I will take a look at it and see if it solves the issue. will let you know either way. Thanks again.

**Comment by ilike2burnthing** [comment]
You deleted the issue template and didn't provide the requested information within it:
>**OS**:
>**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
>**.Net Version**:
>**Jackett Version**:
>**Last Working Jackett Version**:
>**Are you using a proxy or VPN?** [yes/no]

Though as of the the most recent release (v0.17.405), EXT doesn't require FlareSolverr.
