### ISSUE TITLE
[yggtorrent] Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: An error occurred while sending the request.

### ISSUE THREAD

**Issue by silveralextv** [Jackett/Jackett#10708]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: ubuntu server

**Jackett Version**: v0.17.181

**Last Working Jackett Version**: v0.17.181

**Are you using a proxy or VPN?** no

### Description

Unable to make working Yggtorrent indexer. FlareSolverr run on the latest version with docker-cli.

### Logged Error Messages

`Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException (104): Connection reset by peer --- End of inner exception stack trace --- at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) at System.Net.Http.HttpConnection.FillAsync(Boolean async) at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed) at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken) at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<b__0>d.MoveNext()`

**Comment by ilike2burnthing** [comment]
Check if FlareSolverr is configured correctly in Jackett, and is accessible in browser on the same device - https://github.com/Jackett/Jackett/wiki/Troubleshooting#error-connecting-to-flaresolverr-server

Also, 'latest' is not a version. You can scroll to the bottom of the Jackett UI and find the version number there.

**Comment by silveralextv** [comment]
@ilike2burnthing Flaresolverr is correctly configured in Jackett. It is not accessible on my browser.
curl
`curl: (7) Failed to connect to 127.0.0.1 port 8191: Connection refused`
wget
`--2021-01-02 14:58:04--  http://127.0.0.1:8191/
Connecting to 127.0.0.1:8191... failed: Connection refused.`

**Comment by ilike2burnthing** [comment]
Use the local IP of the device it's installed on (e.g. 192.168.0.2), not 127.0.0.1

**Comment by silveralextv** [comment]
The same
curl
`curl: (7) Failed to connect to 192.168.3.23 port 8191: Connection refused`
wget
`--2021-01-02 15:04:29--  http://192.168.3.23:8191/
Connecting to 192.168.3.23:8191... failed: Connection refused.`

**Comment by Ionniz** [comment]
What is your install method ?

**Comment by silveralextv** [comment]
Docker

**Comment by ilike2burnthing** [comment]
Can you provide your Docker run or compose for FlareSolverr, or screenshots of the container settings if you're using Portainer?

**Comment by silveralextv** [comment]
For jackett : https://hub.docker.com/r/linuxserver/jackett
For FlareSolverr : https://hub.docker.com/r/flaresolverr/flaresolverr

**Comment by Ionniz** [comment]
Okay but the command is docker run or docker compose ?

**Comment by silveralextv** [comment]
I use docker cli, the command is docker run.

**Comment by Ionniz** [comment]
Okay yesterday I have the same error. Use docker compose.

**Comment by Ionniz** [comment]
Je vais en profiter que tu sois français pour t'expliquer où cela cloche. Tu peux voir lorsque tu exécutes un docker ps les redirections de ports sont affichées. 
![image](https://user-images.githubusercontent.com/46867479/103489754-dc778700-4e16-11eb-9d9b-60652186741c.png)
Ci-dessous ce que tu devrais avoir pour que cela fonctionne.
Cependant avec docker cli tu n'as que la partie après la flèche donc la redirection est mal faite. Je n'ai pas trop chercher à résoudre le pb mais par contre j'ai fait un ré-installe avec docker compose et ça marche.
Si tu as d'autre soucis pendant l'installation de (je suppose ) ta seedbox on pourra continuer sur discord car j'ai fini la mienne hier

**Comment by Shibiz** [comment]
J'ai le meme soucis que lui et la meme methode d'installation, il faut utiliser Docker Compose pour FlareSolverr ou Jackett ?

**Comment by Ionniz** [comment]
Pour FlareSolverr

**Comment by silveralextv** [comment]
Merci beaucoup @Ionniz ! Je vais essayer ça dans cette fin de matinée 😉

**Comment by silveralextv** [comment]
`Creating flaresolver ... error

ERROR: for flaresolver  Cannot start service flaresolverr: driver failed programming external connectivity on endpoint flaresolver (d27789d3bc5396719b22303c519164ccd6ab2c02681044ba5db87de120b418cd): Error starting userland proxy: listen tcp 0.0.0.0:8191: bind: address already in use

ERROR: for flaresolverr  Cannot start service flaresolverr: driver failed programming external connectivity on endpoint flaresolver (d27789d3bc5396719b22303c519164ccd6ab2c02681044ba5db87de120b418cd): Error starting userland proxy: listen tcp 0.0.0.0:8191: bind: address already in use
ERROR: Encountered errors while bringing up the project.`

**Comment by Ionniz** [comment]
Oulah pas normal , si tu as discord ajoute-moi on va résoudre ça rapidement car je ne suis pas souvent sur github 
Ionniz#0001

**Comment by Ionniz** [comment]
le problème ici c'est que tu n'as pas delete ton ancien container flaresolverr

**Comment by Shibiz** [comment]
En essayant d'installer Flaresolverr par docker compose j'ai le meme soucis, j'ai essayé via Portetainer et également en ligne de commande toujours pareil =(
Je dois avoir la poisse

**Comment by Ionniz** [comment]
Mauvaise utilisation de docker ;) il faut que tu rm totalement ton container docker rm le nom de ton image

**Comment by ilike2burnthing** [comment]
If you're testing a new container, you have to remove the original first, or at least change the port binding and container name.

As for my earlier request, please post the Docker run command you're using, e.g:
```
docker run -d \
  --name=flaresolverr \
  -e LOG_LEVEL=info \
  --restart unless-stopped \
  ghcr.io/flaresolverr/flaresolverr:latest
```

**Comment by Shibiz** [comment]
Yes this is what i did before creating the new container 

docker stop flaresolverr
docker rm flaresolverr

And after that 

docker run -d \
  --name=flaresolverr \
  --network=bridge \
  -p 8191:8191 \
  -e LOG_LEVEL=info \
  -e CAPTCHA_SOLVER=harvester \
  -e HARVESTER_ENDPOINT=https://127.0.0.1:5000/token \
  --restart unless-stopped \
  ghcr.io/flaresolverr/flaresolverr:latest

**Comment by ilike2burnthing** [comment]
Remove `HARVESTER_ENDPOINT` and change `CAPTCHA_SOLVER` to `none`, as currently none of the solvers are working. See if that makes any difference.

I take it any relevant port forwarding has been done, that Jackett and FlareSolverr are on the same device, and neither are behind a VPN or proxy?

**Comment by nukten** [comment]
Hi,
I have a same problem. 
Have you got solved it ?

**Comment by ilike2burnthing** [comment]
Open a new issue and provide the information requested.
