### ISSUE TITLE
Indexer (AvistaZ) Error during searching for Movie

### ISSUE THREAD

**Issue by wakhaiha** [Jackett/Jackett#10719]
### Environment

**OS**: Debian GNU/Linux 9.12

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.166

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] NO

### Description

I am having a problem with Jackett v0.17.166 used in Radarr v3.0.1.4259. AvistaZ Indexer keeps produced an error during the movie search in Radarr. this error message has gone after I clicked "Test All" in Radar System>Health Setting. But then, the same error occurred each time I search for the movie. this happened to all the movies searched. I have checked the Indexer Setting in both Radarr and Jacket, both tested with no fail.

I tried troubleshooting by visiting the URL provided in the error message for one of the movies as below. The same error message is shown in the browser. But when I removed the `&imdbid=8108274` parameter, the error is gone.

`https://(removed).usbx.me/jackett/api/v2.0/indexers/avistaz/results/torznab/api?t=movie&cat=2000,2030,2040,2045&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=8108274`

### Logged Error Messages

Below is Radarr log
https://pastebin.com/1x7xDDHZ

And below is Jackett Log
https://pastebin.com/AqRD1uie

**Comment by plsharevme** [comment]
i also use avistaz , but seem it working very well for me.

**Comment by ilike2burnthing** [comment]
Did you follow this instruction as well?
```
You have to check 'Enable RSS Feed' in 'My Account', without this configuration 
the torrent download does not work.
You can find the PID in 'My profile'
```
If so, please post an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
