### ISSUE TITLE
[morethantv] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by nphil** [Jackett/Jackett#10718]
### Environment

**OS**: Ubuntu 18.10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.159

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

Used to work fine until recently.

### Logged Error Messages

Object reference not set to an instance of an object

Cannot add the tracker due to above error message.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/9670
