### ISSUE TITLE
[New Tracker REQ] PolishTracker

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#1072]
**Indexer Name**
PolishTracker

**Type**
Movies, TV, Audio, XXX, PC, Books, Console, Other

**Indexer URL**
https://polishtracker.net/

**Indexer Language**
Polish, English, German

**Invite**
An invite is needed. It would be appreciated if someone can supply one.

**Note**
PolishTracker is a medium-sized general Polish tracker with over 28K torrents

**Comment by armani316** [comment]
@kaso17 I should be able to provide an invite within the next few days. Please confirm when you receive it.

**Comment by kaso17** [comment]
will do

**Comment by armani316** [comment]
@kaso17 Please confirm when you receive the invite.

**Comment by kaso17** [comment]
didn't receive one yet

**Comment by bunius** [comment]
@kaso17 
just sent an invitation

**Comment by RoloSoze** [comment]
@bunius Thank you, but @kaso17 had already received an invite before you sent him one. Please feel free to cancel the invite you sent. Sorry for the confusion.

**Comment by kaso17** [comment]
@bunius thank you, let me know if I should send the invite somewhere else.

**Comment by bunius** [comment]
there's no need. If it not used then invite return back to me.

**Comment by kaso17** [comment]
Added with cbbcf5dc0d07053cbc5adee8bc49bca43b55e848
Please test, it feels a little fragile.

**Comment by RoloSoze** [comment]
@kaso17 It's working fine for me. Fragile how?

**Comment by kaso17** [comment]
they've some extra cookie checks, had some issues with automatic logoffs (not sure if they support multiple sessions).

**Comment by RoloSoze** [comment]
Not sure about the extra cookie checks but you're right about the tracker not supporting multiple concurrent sessions. The same thing's happening over here, but everything else seems to be working fine so far.

**Comment by bunius** [comment]
unfortunately it doesn't work :( Found 0 torrentpotato releases from PolishTracker for: ....
When you press "view cached releases" then in a column "Name" is a category name instead a release name.

**Comment by kaso17** [comment]
please share an enhanced log, might be some profile settings affecting the search result table

**Comment by bunius** [comment]
@kaso17
I hope you find this information helpful. Thank you.
 
[logPolishTracker.txt](https://github.com/Jackett/Jackett/files/859472/logPolishTracker.txt)
![obraz](https://cloud.githubusercontent.com/assets/26360350/24167516/4f58bfac-0e77-11e7-895e-4d9a3f4ff559.png)
