### ISSUE TITLE
Jackett ignores -j (ProxyConnection) CLI flag 

### ISSUE THREAD

**Issue by mkrupczak3** [Jackett/Jackett#10734]
Duplicate of #9467 and #10711 because these two issues were improperly closed without resolution.

A change in Jackett's command line arguments has been made where it now ignores the -j or --proxyconnection flags from the CLI. 

Unfortunately, this breaks many existing Docker configs and removes pre-existing functionality from the Jackett app. 

In addition, it is inadvisable to allow this breaking change to remain on the stable Jackett branch when it may break existing users' current configs and running instances. Especially when no acceptable fix has yet been implemented. 

Removing functionality and breaking configs on a "stable" version release, especially when unnecessary for development, is generally regarded as poor software stewardship. 

> **OS**: docker container (https://hub.docker.com/r/linuxserver/jackett)
> 
> **Jackett Version**: CoreLinuxAmdx64 v0.16.1082.0
> 
> **Are you using a proxy or VPN?** yes
> ### Description
> 
>     * Run Jackett from CLI with argument `-j, --ProxyConnection` specifying a valid HTTP proxy. Tested `http://proxyhost:3128`, `proxyhost:3128`, etc
> 
>     * See in console:
> 
> 
> ```
> 09-07 20:50:12 Info Proxy enabled. http://proxyhost:3128 (cli arg successfully passed)
> ...
> 09-07 20:50:13 Info Using Proxy: No (but proxy setting not applied)
> ```
> 
>     * Try to make some request, e.g. test indexer
> 
>     * See error:
>       ` An error occurred while testing this indexer Exception (rutracker): Authentication failed because the remote party has closed the transport stream.: The SSL connection could not be established, see inner exception.`
> 
>     * Setup same proxy but with Web UI
> 
>     * Check that same test works
> 
> 
> Not familiar with C# but look like there is no code in project that would use this variable:
> https://github.com/Jackett/Jackett/search?q=ProxyConnection&unscoped_q=ProxyConnection

**Comment by mkrupczak3** [comment]
@ngosang @ilike2burnthing

**Comment by mkrupczak3** [comment]
Awesome

**Comment by ilike2burnthing** [comment]
I'm replying to you on the original issue. Please don't open duplicates.

**Comment by mkrupczak3** [comment]
Thanks. Could you re-open those issues?
