### ISSUE TITLE
Request to Jackett server failed when trying to add Lostfilm Tracker

### ISSUE THREAD

**Issue by Mavrag** [Jackett/Jackett#10737]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker linuxserver/jackett

**.Net Runtime**: 
**.Net Version**: 

**Jackett Version**: v0.17.197

**Last Working Jackett Version**: haven't tried adding it before

**Are you using a proxy or VPN?** [yes/no]: Yes

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Try to add Lostfilm tracker

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
If you can access the site from the same proxy or VPN IP, and are able to use other indexers in Jackett, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Mavrag** [comment]
Here is the log file
[jacket-log.txt](https://github.com/Jackett/Jackett/files/5771613/jacket-log.txt)

**Comment by ilike2burnthing** [comment]
Thanks.
```
The SSL connection could not be established [...] certificate validation failed [...]
[Issuer]
  O=Internet Widgits Pty Ltd, S=Some-State, C=AU
```
That's a default cert, so something is going wrong (the site and indexer are working fine for me).

Disable your proxy/VPN and try again. Let us know if it works.

Re-enable the proxy/VPN, then from the container run `curl -v https://www.lostfilm.run/` and `openssl s_client -connect https://www.lostfilm.run/` and post the responses here.

**Comment by Mavrag** [comment]
# curl -v https://www.lostfilm.tv
*   Trying 185.85.121.13:443...
* Connected to www.lostfilm.tv (185.85.121.13) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

# openssl s_client -connect https://www.lostfilm.tv
22424554247552:error:2008F002:BIO routines:BIO_lookup_ex:system lib:crypto/bio/b_addr.c:726:Servname not supported for ai_socktype
connect:errno=0

**Comment by Mavrag** [comment]
I'll try a different VPN server and let you know.

**Comment by Mavrag** [comment]
@ilike2burnthing so I've changed my VPN server and the issue is no more. Still don't know what was the problem with the other server. Thanks for the help.
