### ISSUE TITLE
feature request: extend search results size column to two decimal places

### ISSUE THREAD

**Issue by fejjj** [Jackett/Jackett#10732]
example: instead of showing 9.7GB torrent size, show 9.67GB.

**Comment by ilike2burnthing** [comment]
Can you explain why you're requesting this?

**Comment by ilike2burnthing** [comment]
@ngosang any chance it is as simple as changing this to 2?
https://github.com/Jackett/Jackett/blob/a9a101b9468312382873b2051f0545e6a1d99f98/src/Jackett.Common/Content/libs/handlebarsmoment.js#L35-L36

**Comment by ngosang** [comment]
Yes, that's it. You are becoming a ninja! :smile:

**Comment by ilike2burnthing** [comment]
Ha! 😉

**Comment by ilike2burnthing** [comment]
[v0.17.311](https://github.com/Jackett/Jackett/releases/tag/v0.17.311)
