### ISSUE TITLE
Api returns empty, logs say various matches have been found

### ISSUE THREAD

**Issue by hugochinchilla** [Jackett/Jackett#1074]
~~~
curl http://192.168.82.5:9117/potato/thepiratebay?imdbid=tt3263904&search=Sully+2016&user=&passkey=oyspd51qhqtclqozjpfwy08hhx26kbj2

{
  "results": [],
  "total_results": 0
}
~~~

Logs:
~~~
02-17 19:27:38 Info Found 30 torrentpotato releases from The Pirate Bay for: Sully 2016 
~~~

Jackett version:  0.7.1035.0
Mono version (if not using Windows):  docker linuxserver/jackett:latest

**Comment by kaso17** [comment]
TPB returns only magnet links which were filtered (old couch potato versions apparently didn't support it).
With the next version magnet links will be exported to couchpotato.
See the discussion in #1040

**Comment by hugochinchilla** [comment]
@kaso17 thanks for the new release, it's working properly now
