### ISSUE TITLE
Flaresolver timeout too short

### ISSUE THREAD

**Issue by shaavik** [Jackett/Jackett#10747]
I use Flaresolver on some site, but the timeout is too short, the response takes 400 s while the timeout is 60s. Please add a way to change the default Flaresolver timeout parameter.

**Comment by xfouloux** [comment]
it's a flaresolverr parameter, you better open an issue there, and not in jackett =)

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr#-requestget
Otherwise open an issue there.
