### ISSUE TITLE
[tlfbits] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by skygunner** [Jackett/Jackett#10749]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Linux docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
Jackett Version v0.17.197

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]
no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by skygunner** [comment]
It seems it error out while trying to parse the category, full log attached. 

System.Exception: Error while parsing field=category, selector=a[href^="?cat="], value=440: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1522 
2021-01-07 19:08:38.5170 Info Test search in TLFBits => Found 0 releases 
2021-01-07 19:08:38.5237 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 2466.042ms 
2021-01-07 19:08:38.5248 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' 
2021-01-07 19:08:38.5267 Error System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 307
[log.bak.txt](https://github.com/Jackett/Jackett/files/5780609/log.bak.txt)

**Comment by ilike2burnthing** [comment]
Yep, looks like they've added new categories.

I don't have an account and registration is closed, so I'll need you to provide a partial HTML dump for the search page (presumably https://pt.eastgame.org/torrents.php) - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

Either upload the whole thing, or just the category block. Using BTSCHOOL as a similar example, it should be near the top and contain a list of `id="cat4##`.
Looks something like this:
![html](https://user-images.githubusercontent.com/59480337/103878152-f1317480-50cd-11eb-8c6c-2af1a277274d.png)

**Comment by skygunner** [comment]
Cool mate.

**Comment by ilike2burnthing** [comment]
Can you confirm that the categories have actually completely changed, none of the old ones exist?
https://github.com/Jackett/Jackett/blob/a983537cc90fd4e95b6c94969ff72e816ae37821/src/Jackett.Common/Definitions/tlfbits.yml#L11-L35
The names used on the site are those after `desc:`, e.g. `TLF-MiniSD`.

**Comment by skygunner** [comment]
Looks like most of its categories have been changed , but hold on with this, let me confirm with the admin. Maybe my account is new so I can't see the other cats. However I don't think this is the case. 

For E-Learning category it is supposed to be videos about learning things, for example, Python programming or financial stuff. However this cat has mostly been abandoned, only 38 torrents in this cat and some of them are not related to E-Learning at all. You can consider this cat as other/misc or just ignore this one. 

TLF was a big site in the past days when pub ftp, eDonkey/emule was popular. Now it is mostly in archived state, registration closed, site (forum/pt) is mostly for the old members to live with and continue, totally under the radar. I might able to get you an account later so anything needed for developing could be easier.

**Comment by ilike2burnthing** [comment]
Thanks, will hold off on making any changes for now.

Note to self:
```
caps:
  categorymappings:
    - {id: 438, cat: Movies, desc: "电影 (Movie)"}
    - {id: 440, cat: TV, desc: "电视剧(TV series)"}
    - {id: 441, cat: TV, desc: "综艺 (TV Show)"}
    - {id: 442, cat: TV/Anime, desc: "动漫 (Anime)"}
    - {id: 443, cat: TV/Documentary, desc: "纪录片 (Documentary)"}
    - {id: 444, cat: TV/Sport, desc: "体育 (Sport)"}
    - {id: 445, cat: Audio/Video, desc: "音乐视频 (Music Video)"}
    - {id: 446, cat: Audio, desc: "音乐(Music)"}
    - {id: 447, cat: PC/Games, desc: "游戏 (Game)"}
    - {id: 448, cat: PC/0day, desc: "软件 (Software)"}
    - {id: 449, cat: Books/Other, desc: "资料（E-Learning）"}
    - {id: 450, cat: Other, desc: "其它 (Other)"}
```

**Comment by skygunner** [comment]
Hi mate, I've got confirmation from the admin, yes the categories have been changed a lot, all the old categories have either been deleted or disabled and won't be used.  

So yes you can commit that change. Cheers,
