### ISSUE TITLE
Supporting SSL

### ISSUE THREAD

**Issue by Arefu** [Jackett/Jackett#10741]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Arch GNU/Linux

**.Net Runtime**: .Net-Core

**.Net Version**: 5.0.101

**Jackett Version**: Any

**Last Working Jackett Version**: Any

**Are you using a proxy or VPN?** No, I will not do this either.

### Description
Let's Encrypt has made it super easy to obtain certificates these days, Jackett should support the ability to add a certificate since it's starting it's own web-server.

### Logged Error Messages
N/A

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots
N/A

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/1411
