### ISSUE TITLE
Missing results in Sonarr

### ISSUE THREAD

**Issue by leafsfan525** [Jackett/Jackett#10753]
Running the latest version (v0.17.197) on Windows 10. No VPN

Sonarr is not showing any results even though they show in Jackett, for certain shows. The main indexers I am using are all public: 1337x, ETTV, EZTV, TPB

Here are some examples:

![jackett 2](https://user-images.githubusercontent.com/16564608/103894255-a65b3100-50bc-11eb-98f6-0666ea8c506a.png)
![jackett 1](https://user-images.githubusercontent.com/16564608/103894259-a6f3c780-50bc-11eb-9833-c608fb5cdade.png)

**Comment by ilike2burnthing** [comment]
A question for https://forums.sonarr.tv/

What jumps to mind for Jeopardy though is whether you have it set in Sonarr as standard series type instead of daily.

Check that other searches are working and have a look at the logs for both applications:
- Jackett - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
- Sonarr - https://github.com/Sonarr/Sonarr/wiki/Logging-and-Log-Files

**Comment by leafsfan525** [comment]
I posted in the Sonarr forums as well, but it seems something is up on the Jackett side as well. Specifically looking at the Days of our Lives results. It doesn't seem to find anything when the episode is specified even though the result is clearly there as you can see from the season only search.

![jackett](https://user-images.githubusercontent.com/16564608/104187271-9063ae00-53e5-11eb-9d18-1b130ce16fac.png)

[jackett log.txt](https://github.com/Jackett/Jackett/files/5795920/jackett.log.txt)
[sonarr.trace.txt](https://github.com/Jackett/Jackett/files/5795921/sonarr.trace.txt)

**Comment by ilike2burnthing** [comment]
Looks like you got it fixed with https://github.com/Sonarr/Sonarr/commit/8bc0ab981c0d9a4a147bb3ac78824dcf5d3c0e9d over on https://forums.sonarr.tv/t/not-finding-indexer-results-from-jackett/27418/12

And DoOL seems to be as a result of the extra `0` in the episode numbering - E**0**77

**Comment by leafsfan525** [comment]
Yes the Jeopardy issue was a bug with Sonarr that has been resolved in the most recent version.

For DoOL and the extra 0 in the episode numbering, is there any way to fix that?

**Comment by ilike2burnthing** [comment]
I'm not sure if this would be something for Sonarr to fix, or thexem.de

**Comment by leafsfan525** [comment]
Ok appreciate the info. It's on the Sonarr forums too so maybe they will see it there and determine if it can be fixed with Sonarr.

I've never heard of thexem.de so not sure if I can do anything about that.
