### ISSUE TITLE
Missing Results

### ISSUE THREAD

**Issue by leafsfan525** [Jackett/Jackett#10756]
Running the latest version (v0.17.197) on Windows 10. No VPN

The Pirate Bay indexers not showing results, but they are shown on the site itself.

Example:
![jackett 3](https://user-images.githubusercontent.com/16564608/103917455-a1f24080-50db-11eb-82cb-7120803d1ca4.png)

**Comment by ilike2burnthing** [comment]
What URL are you using for TPB? The indexer uses their API, which returns the same results as in Jackett - https://apibay.org/q.php?q=the%20bachelor

**Comment by leafsfan525** [comment]
I was using pirate-bay.net, and I put that in the settings on Jackett too. Maybe that doesn't matter. Sounds like that is the issue. Is it something that can be fixed for that indexer on Jackett or is it something on the API end that is out of your control?

**Comment by ilike2burnthing** [comment]
That redirects to tpbpirateproxy.org for me, which doesn't use the API. Use one of the ones from the config, or https://proxybay.github.io/

The API has the same results as thepiratebay.org, so if you've come across a site which claims to be a TPB proxy, but doesn't match, then it's a bad clone and shouldn't be used.

**Comment by leafsfan525** [comment]
Ok thanks, good to know. Seems weird the most recent results on any of the official proxies is from 9 years ago. Oh well, other indexers seem to have the more recent results.

**Comment by ilike2burnthing** [comment]
The recent list for those proxies (in other words, the API) are all from today, many within the last few minutes.

**Comment by leafsfan525** [comment]
Ya I see that now. I guess just the specific show isn't on there.

**Comment by ilike2burnthing** [comment]
The Bachelor? Ah yea, seems so, bit weird. I'd recommend RARBG, TGx, ETTV, and EZTV for reliable public trackers for TV shows.

**Comment by leafsfan525** [comment]
Yup I use those ones as well. Thanks again!
