### ISSUE TITLE
[New Tracker REQ] Audiobook Torrents

### ISSUE THREAD

**Issue by neilicious** [Jackett/Jackett#1075]
**Indexer Name**
Audiobook Torrents

**Type**
Audio

**Indexer URL**
https://abtorrents.me/

**Indexer Language**
English

**Invite**
Invite sent via email

**Comment by kaso17** [comment]
didn't receive an invite at kaso1717 -at- gmail.com

**Comment by neilicious** [comment]
I've just re-sent the invite

**Comment by kaso17** [comment]
got it, registered, do you have to confirm my account?
I can't login yet and didn't receive an activation email.

**Comment by neilicious** [comment]
Should now be confirmed

**Comment by kaso17** [comment]
added with 901693d6de50e18b27de2f70d8c5f86a68c39862

**Comment by kevinpawsey** [comment]
There appears to be an issue with this tracker at the moment, login verifies, but test is failing
