### ISSUE TITLE
Doesn't work for me on my Mac

### ISSUE THREAD

**Issue by FatSandwich** [Jackett/Jackett#10755]
I did everything the Readme said. I downloaded the Jackett.Binaries.macOS.tar.gz. Then I opened install_service_macos. But then I get this when I go to localhost:9117

![image](https://user-images.githubusercontent.com/63752541/103910931-6b182c80-50d3-11eb-9463-1470e4e636dd.png)

**Comment by ilike2burnthing** [comment]
Try http://127.0.0.1:9117 instead. Any errors on install? If not, have a look at your logs.

**Comment by FatSandwich** [comment]
Thanks, but it gives me the same error. But, where do I check my logs
On Jan 7, 2021, 10:59 AM -0500, ilike2burnthing <notifications@github.com>,
wrote:

Try http://127.0.0.1:9117 instead. Any errors on install? If not, have a
look at your logs.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Jackett/Jackett/issues/10755#issuecomment-756205976>,
or unsubscribe

**Comment by ilike2burnthing** [comment]
Logs are stored as usual under `~/.config/Jackett/log.txt`
https://github.com/Jackett/Jackett#installation-on-macos

Does it work if you don't install as a service?

**Comment by FatSandwich** [comment]
It says

2021-01-07 10:38:56.1748 Info Starting Jackett v0.17.197

In the log

And installing it without installing it as a service doesn’t work either. I detailed guide of how to Jackett on Mac would be great! Thanks!

**Comment by ilike2burnthing** [comment]
Please don't open duplicate issues, especially if the other one is your own, is open, and only a few days old.

**Comment by NinjaLikesCheez** [comment]
I believe this issue may be caused by a case-insensitive file system. I reformatted a mac recently that had been running Jackett fine previously, and had the same a successful agent install message when running the `install_service_macos`, but Jackett wasn't running. 

When run manually I got the following: 

```
ninji$ ./jackett
02-24 21:33:58 Info Starting Jackett v0.0.0
Unhandled exception. System.Exception: Could not create settings directory. The file '/Users/ninji/Desktop/Jackett/Jackett' already exists.
   at Jackett.Common.Services.ConfigurationService.CreateOrMigrateSettings()
   at Jackett.Common.Services.ConfigurationService..ctor(ISerializeService s, IProcessService p, Logger l, RuntimeSettings settings)
   at Jackett.Server.Program.Main(String[] args)
Abort trap: 6
```

Changing the value of `DataFolder` in the `RuntimeSettings.cs` file and rebuilding `Jackett.Common.dll` fixed the issue: 
```
ninji$ ./install_service_macos
Agent successfully installed and running!
Jackett location: /Users/ninji/Desktop/Jackett
Jackett agent:
	path = /Users/ninji/Library/LaunchAgents/org.user.Jackett.plist
	state = running
	working directory = /Users/ninji/Desktop/Jackett
	pid = 3666
ninji$ ps aux | grep jackett
ninji             3666  66.3  1.8  6882832  73548   ??  R     9:37pm   0:04.34 /Users/ninji/Desktop/Jackett/jackett --NoRestart 
```

Will experiment a little more with changing the LaunchAgent invocation to use the data folder option, or writing something to migrate the data folder for existing installations.

**Comment by ilike2burnthing** [comment]
Could you create a PR once you've finished? Thanks.

**Comment by NinjaLikesCheez** [comment]
Just to loop back from the PR, the issue is caused by the `~/.config` directory not existing when Jackett runs. 

You can fix this in current versions by running `mkdir ~/.config` before running Jackett.

**Comment by garfield69** [comment]
v0.17.627
