### ISSUE TITLE
Delay beetwen RSS Yggtorrent and RSS on Jackett

### ISSUE THREAD

**Issue by rjulie95** [Jackett/Jackett#10761]
### Environment

**OS**: Docker / Ubutun 18.04

**Jackett Version**: 0.17.207

**Last Working Jackett Version**: 0.17.207

**Are you using a proxy or VPN?** no

### Description

When I search on yggtorrent, I always have a delay of about 1 hour between my search and the time of publication on ygg.

Is this normal?

### Logged Error Messages

No error

**Comment by ilike2burnthing** [comment]
What are your cache settings? https://github.com/Jackett/Jackett#search-cache
