### ISSUE TITLE
[REQ]www.zhuixinfan.com

### ISSUE THREAD

**Issue by SuperNG6** [Jackett/Jackett#10786]
Public Japanese television drama share torrent site.
Please add this tracker.
Thank you

Link: http://www.zhuixinfan.com

![LgCvgN](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/LgCvgN.png)

**Comment by garfield69** [comment]
looks like http://www.zhuixinfan.com/ is gone?

**Comment by SuperNG6** [comment]
> looks like http://www.zhuixinfan.com/ is gone?

Their acceleration service expired and the site is currently under maintenance (they decided to rewrite the site code), this situation will be restored by the end of the month at the latest
