### ISSUE TITLE
Results Limit to the Provider First Page

### ISSUE THREAD

**Issue by tproenca** [Jackett/Jackett#1078]
Hi,

When searching stuff using only the media name, usually the results from the provider span several pages. However, Jackett parses only the first page, what usually contains 30 matches.

Radarr for example uses movie names to search, and later considers the results that match your criteria (quality, tags, etc). Most of the time, what matches my criteria are in page 2 or 3 of the provider and is left out because Jackett considers just the first page.

Ideally Jackett should paginate the results from the provider until a "Minimum Seeders" option is match. I believe this is what CouchPotato does.

**Comment by armani316** [comment]
@tproenca Thank you for raising this issue. I recently opened an issue for the same topic in #975
