### ISSUE TITLE
[Dark-Shadow] Finds the right results in Jackett but not in Radarr

### ISSUE THREAD

**Issue by Winblackka** [Jackett/Jackett#10788]
**OS**: Docker

**Jackett Version**:  v0.17.231

Hello,

its the same issue like this one: https://github.com/Jackett/Jackett/issues/9752
Searching it with the imdb search term tt7286456

Here are the logs:
[jackett_log.txt](https://github.com/Jackett/Jackett/files/5794577/jackett_log.txt)
[radarr_log.txt](https://github.com/Jackett/Jackett/files/5794579/radarr_log.txt)

**Comment by ilike2burnthing** [comment]
Looks like they've removed the option to search by IMDB ID:
```
<select name="blah" class="stand_select" style="width:120px;">
  <option value="0">Name</option>
  <option value="1">Beschreibung</option>
  <option value="2">Beides</option>
</select>
```
There should also be an option `<option value="4">IMDB</option>`.

Can you search on the site itself using `tt7286456` to confirm it does find results correctly, and also that the specific 'search by IMDB ID' function has been removed?

If you can also test this in Jackett, that would be great. You'd need to change the line in dark-shadow.yml to `blah: 0` and restart Jackett, then run the search:
https://github.com/Jackett/Jackett/blob/dda103e4630898164817e5fad03407c642c95f17/src/Jackett.Common/Definitions/dark-shadow.yml#L141

**Comment by Winblackka** [comment]
If im using the tt7286456 for the search i find nothing - i think they have removed the IMDB ID search. 

Sorry, i cant change the blah:0 string. Im not able to edit the dark-shadow.yml. I dont know how to get there running jackett in a docker container, i have just access to the /config part.

**Comment by ilike2burnthing** [comment]
That's fine, it was basically just to double check, but if it's not working on the site then it's not going to work in Jackett. I'll get that fixed.

Bit of an aside, but you can create a sub-folder in `config` named `cardigann`, and a sub-folder in that called `definitions`, so `.\config\cardigann\definitions\`. From there you can test out whatever indexer edits you like (you just have to change the name and id too, so they don't conflict with the originals e.g. `dark-shadow-edit`).

**Comment by Winblackka** [comment]
First off all: Thanks for you great work!

Ah, i will give it a try, maybe i can save you some work next time :)

**Comment by ilike2burnthing** [comment]
[v0.17.242](https://github.com/Jackett/Jackett/releases/tag/v0.17.242) (better late than never)
