### ISSUE TITLE
[Speedmaster HD] Finds the right results in Jackett but not in Radarr

### ISSUE THREAD

**Issue by Winblackka** [Jackett/Jackett#10787]
**OS**: Docker

**Jackett Version**:  v0.17.231

Hello,

its the same issue like this one: https://github.com/Jackett/Jackett/issues/9752
Searching it with the imdb search term tt7286456

Here are the logs:

[radarr_log.txt](https://github.com/Jackett/Jackett/files/5794546/radarr_log.txt)
[jackett_log.txt](https://github.com/Jackett/Jackett/files/5794547/jackett_log.txt)

**Comment by ilike2burnthing** [comment]
Can you disable the cache in Jackett, apply server settings, and rerun the tests with debug logs please? That shouldn't be necessary, but it looks like there's a separate issue with the cache.

**Comment by Winblackka** [comment]
Here you are.

[jackett_tt7286456_log.txt](https://github.com/Jackett/Jackett/files/5795034/jackett_tt7286456_log.txt)
[jackett_joker_log.txt](https://github.com/Jackett/Jackett/files/5795035/jackett_joker_log.txt)
[radarr_log.txt](https://github.com/Jackett/Jackett/files/5795036/radarr_log.txt)

**Comment by ilike2burnthing** [comment]
Yep, IMDB search has been removed here as well.

**Comment by Winblackka** [comment]
Fast and perfect support as usual. Thank you!

**Comment by ilike2burnthing** [comment]
[v0.17.242](https://github.com/Jackett/Jackett/releases/tag/v0.17.242) (better late than never)
