### ISSUE TITLE
manual search succeeds wilst Couch API result is empty

### ISSUE THREAD

**Issue by daanvandevliet** [Jackett/Jackett#10791]
### Environment

**OS**: Arch Linux

**.Net Runtime / version**: Not sure. How do I find this? Mono/dotnet-sdk all not installed. Jackett runs fine.

**Jackett Version**: v0.17.213

**Last Working Jackett Version**: Not a;;icable

**Are you using a proxy or VPN?** no

### Description

Thank you for creating this awesome tool, love it! I wanted to share this potential issue as I am researching it.

Here's the peculiar behavior I am finding:
1. In Jackett, enable Avistaz.to (Private) as a tracker.
2. Manual search for a series with the combination 'Mr. Queen'. (a tv show)
3. Observe results. (In my case 60)
4. API (Potato as I need JSON result) request with: http://x.x.x.x:9117/api/v2.0/indexers/avistaz/results/potato?search=Mr.+Queen&user=&passkey=redacted
5. No results for API search for this term.

#### Manual (From ### :9117/UI/)
````
2021-01-11 22:20:10 | Info | Manual search in avistaz for Mr. Queen => Found 60 releases
-- | -- | --
2021-01-11 22:20:10 | Debug | CACHE IsCacheEnabled => false
2021-01-11 22:20:10 | Debug | WebClient(HttpWebClient2): Returning OK => 54058 bytes {"current_page":1,"data":[{"id":160716,"url":"https:\/\/avistaz.to\/torrent\/160716-mr-queen-s01e10-1080p-web-dl-aac-h264-kmx","download":"https:\/\/avistaz.to\/rss\/download\/{Redacted}\/160716-acd39db343b3286f30d8d4fbdc524a30793088f4.torrent","type_id":2,"type":"TV-Show","info_hash":"acd39db343b3286f30d8d4fbdc524a30793088f4","file_name":"Mr. Queen S01E10 1080p WEB-DL AAC H.264-KMX","file_size":1645444763,"file_count":1,"seed":12,"leech":1,"completed":13,"downloaded":23,"upload_multiply":1,"download_multiply":1,"adult":false,"video_quality_id":3,"video_quality":"1080p"
[...]
:100,"prev_page_url":null,"to":60,"total":60}
2021-01-11 22:20:04 | Debug | WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://avistaz.to/api/v1/jackett/torrents?in=1&type=0&search=Mr.+Queen)

````
#### API
````
2021-01-11 22:27:44 | Info | Potato search in AvistaZ for Mr. Queen => Found 0 releases
-- | -- | --
2021-01-11 22:27:44 | Debug | CACHE IsCacheEnabled => false
2021-01-11 22:27:44 | Debug | WebClient(HttpWebClient2): Returning OK => 396 bytes {"current_page":1,"data":[],"first_page_url":"https:\/\/avistaz.to\/api\/v1\/jackett\/torrents?type=1&in=1&search=Mr.+Queen&page=1","from":null,"last_page":1,"last_page_url":"https:\/\/avistaz.to\/api\/v1\/jackett\/torrents?type=1&in=1&search=Mr.+Queen&page=1","next_page_url":null,"path":"https:\/\/avistaz.to\/api\/v1\/jackett\/torrents","per_page":100,"prev_page_url":null,"to":null,"total":0}
2021-01-11 22:27:43 | Debug | WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://avistaz.to/api/v1/jackett/torrents?in=1&type=1&search=Mr.+Queen)

````

To add as this might be a follow-up question, potato API searching for just the word 'queen' (no 'Mr.+') succeeds:

````

  | Potato search in AvistaZ for Queen => Found 59 releases
-- | --

````

Please let me know if I can check something to help debug.

### Screenshots

![Screenshot from 2021-01-11 22-28-52](https://user-images.githubusercontent.com/67875201/104240518-7b763180-545c-11eb-8c6b-24df5f7596ba.png)
![Screenshot from 2021-01-11 22-30-19](https://user-images.githubusercontent.com/67875201/104240589-9ba5f080-545c-11eb-979e-1bdb4fac550b.png)

**Comment by ilike2burnthing** [comment]
@RoloSoze / @ngosang can you confirm?

**Comment by ilike2burnthing** [comment]
See also: https://github.com/Jackett/Jackett/issues/10807

This seems to affect many (all?) indexers - multi-keyword searches show no or fewer results, and some single keyword searches show fewer results.

A few quick tests:
**1337x**
[dark](http://192.168.0.2:9117/Jackett/api/v2.0/indexers/1337x/results/potato?passkey=apikey&offset=0&limit=100&search=dark) - Jackett shows 60, Potato shows 9
[dark materials](http://192.168.0.2:9117/Jackett/api/v2.0/indexers/1337x/results/potato?passkey=apikey&offset=0&limit=100&search=dark%20materials) - Jackett shows 60, Potato shows 0
**zooqle**
[dark](http://192.168.0.2:9117/Jackett/api/v2.0/indexers/zooqle/results/potato?passkey=apikey&offset=0&limit=100&search=dark) - Jackett shows 30, Potato shows 30
[dark materials](http://192.168.0.2:9117/Jackett/api/v2.0/indexers/zooqle/results/potato?passkey=apikey&offset=0&limit=100&search=dark%20materials) - Jackett shows 30, Potato shows 1

I'll try a few more indexers and post if there's anything new, but @ngosang this needs your eyes I think.

**Comment by ilike2burnthing** [comment]
@daanvandevliet / @iz8mbw does that solve your issue?

**Comment by iz8mbw** [comment]
That confirms the issue :-)
Movies results seems to be OK, for example TV Series are not found.

**Comment by iz8mbw** [comment]
@ilike2burnthing I also needs JSON output format, this is why I use Potato API.
If there is a way to obtain JSON format also with torznab I can switch to torznab.
In other words I need the same results of Jackett in JSON.

**Comment by daanvandevliet** [comment]
> > it's returning movie results only, like it's meant to
> 
> @daanvandevliet / @iz8mbw does that solve your issue?

Wow that's interesting! Same as @iz8mbw ; Any way to get tv shows as well with JSON?

**Comment by ilike2burnthing** [comment]
Potato API is for CouchPotato, hence only returning movies - https://github.com/CouchPotato/CouchPotatoServer/

Try using the results direct from Jackett - 
```
http://192.168.0.2:9117/Jackett/api/v2.0/indexers/all/results?apikey=APIKEY&Query=KEYWORDS&Tracker%5B%5D=INDEXERID
```
or for all indexers, remove `&Tracker%5B%5D=...`

Just be aware that we advise against using the aggregate 'all' indexer - https://github.com/Jackett/Jackett#aggregate-indexers

You can also search by a specific category by adding `&Category%5B%5D=5000` (5000 being TV). The supported categories for each indexer can be found in their configuration panels (click the relevant spanner icon).

If you turn on enhanced logging in Jackett's settings and run a search with the settings you want, you can find the URL used in the logs by searching for `Request finished HTTP/1.0 GET`.

**Comment by daanvandevliet** [comment]
Initial check: All good here! Thank you very much @ilike2burnthing

**Comment by iz8mbw** [comment]
@ilike2burnthing @daanvandevliet 
I obtain "HTTP 404", this is my curl:

```
root@odroidc2:~# curl -v "http://192.168.147.4:9117/Jackett/api/v2.0/indexers/all/results?apikey=MY_API_KEY&Query=his+dark+s02e07"
*   Trying 192.168.147.4:9117...
* TCP_NODELAY set
* Connected to 192.168.1.4 (192.168.1.4) port 9117 (#0)
> GET /Jackett/api/v2.0/indexers/all/results?apikey=MY_API_KEY&Query=his+dark+s02e07 HTTP/1.1
> Host: 192.168.1.4:9117
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Thu, 14 Jan 2021 10:29:31 GMT
< Server: Kestrel
< Content-Length: 0
<
* Connection #0 to host 192.168.1.4 left intact
```

where I wrong?
Thank you.

**Comment by ilike2burnthing** [comment]
Try changing or removing `/Jackett` if your base path override is different or not set in Jackett's settings.

If you're trying to create a generic template, that might be best removed anyway.
