### ISSUE TITLE
[iptorrents] Your cookie did not work: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings. (Config)

### ISSUE THREAD

**Issue by SilverCory** [Jackett/Jackett#10795]
As of the past few days I was using iptorrents.eu, turns out the URL was changed to iptorrents.me. This redirects in a browser however jackett fails to follow the redirect.

This may also be caused by the fact I was using a HTTP proxy?

**Comment by ilike2burnthing** [comment]
Change the domain manually and try a new cookie. The next build will include the change of domain.

**Comment by SilverCory** [comment]
I guess my issue is why wasn't it following the redirect?

**Comment by ilike2burnthing** [comment]
In YAML indexers we can add `followredirect, I'm not sure about C#. @ngosang ?

**Comment by ilike2burnthing** [comment]
[v0.17.261](https://github.com/Jackett/Jackett/releases/tag/v0.17.261)

**Comment by ngosang** [comment]
> In YAML indexers we can add `followredirect, I'm not sure about C#. @ngosang ?

Yes, its possible but in this case each domain has different cookies. The user will have to change the cookies anyway.
