### ISSUE TITLE
IPTorrents- Configuration failed: Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by gasde1** [Jackett/Jackett#1080]
Attempting to get into IPT and get this, confirmed login working fine and using version 0.7.1043.  Any suggestions?  I've tried reinstalling jackett and disabling / renabling the service.  

Exception in Configure
Found 0 releases from IPTorrents
Error on 20170219094347 for IPTorrents.txtSystem.NullReferenceException: Object reference not set to an instance of an object
  at Jackett.Indexers.IPTorrents+<PerformQuery>c__async2.MoveNext () [0x003df] in C:\projects\jackett\src\Jackett\Indexers\IPTorrents.cs:269 

Followed by very long html code starting with <!DOCTYPE html><html><head><title>Torrents - IPTorrents - #1 Private Tracker</title><meta http-equiv="Content-Type"

**Comment by kaso17** [comment]
dupe #1041
