### ISSUE TITLE
No seeders?

### ISSUE THREAD

**Issue by leafsfan525** [Jackett/Jackett#10800]
Is there a reason this results shows 0 seeders? When I manually click the magnet link to download it, there are several peers and it downloads extremely fast. I get that it may not be a Jackett issue but just trying to understand. Is it something on the api or indexers end?

![jeopardy](https://user-images.githubusercontent.com/16564608/104331082-ab552180-54bc-11eb-91d7-bb895060e84a.png)

**Comment by ilike2burnthing** [comment]
No seeders reported by the API
