### ISSUE TITLE
API: potato queries does not return same results as torznab

### ISSUE THREAD

**Issue by iz8mbw** [Jackett/Jackett#10807]
Hello.
It seems that "potato" query does not provide the same results of "torznab" query.

For example i tried to search "his dark materials s02e07 ita" and "potato" does not give me any results, but "torznab" is able to return results.
See these curl for the same search string.

"potato" (no results):

```
root@server:~# curl "http://192.168.1.4:9117/api/v2.0/indexers/all/results/potato?passkey=API_KEY&offset=0&limit=100&search=his%20dark%20materials%20s02e07%20ita"
{"results":[],"total_results":0}
```

"torznab" (this CURL return results):

```
root@server:~# curl "http://192.168.1.4:9117/api/v2.0/indexers/all/results/torznab?apikey=API_KEY&q=his%20dark%20materials%20s02e07%20ita"
```

From the Jackett web UI I have:

```
2021-01-13 16:14:30 | Info | Torznab search in AggregateSearch for his dark materials s02e07 ita => Found 13 releases
```
```
2021-01-13 16:11:37 | Info | Potato search in AggregateSearch for his dark materials s02e07 ita => Found 0 releases
```

Where I wrong?
Or is it a bug?

Thanks.

**Comment by iz8mbw** [comment]
ping @ilike2burnthing

**Comment by ilike2burnthing** [comment]
Head over to https://github.com/Jackett/Jackett/issues/10791 and I'll pick this up there
