### ISSUE TITLE
New to Jackett - Eoror with iptorrents

### ISSUE THREAD

**Issue by Freisgd** [Jackett/Jackett#10811]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu 20.04.1 LTS

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono, I think

**.Net Version**: ??

**Jackett Version**: v0.17.261

**Last Working Jackett Version**: Just started using Jackett

**Are you using a proxy or VPN?** [yes/no] No
[saved_log.zip](https://github.com/Jackett/Jackett/files/5811023/saved_log.zip)

### Description Keep getting an error when trying to setup iptorrents

[List steps to reproduce the error and details on what happens and what you expected to happen]
Add indexer
Choose IPtorrents
Get cookie from Firefox
Paste cookie
Okay
\\\ERROR\\\
An error occurred while updating this indexer
Your cookie did not work: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
Click here to open an issue on GitHub for this indexer.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Were you signed into IPTorrents (specifically iptorrents.com) when you got the cookie? This was on the same device and from the same IP as Jackett? Did you copy the whole cookie or just part of it?

**Comment by Freisgd** [comment]
Yes I was signed into IPTorrents (specifically iptorrents.com) when you got the cookie.
Yes it is the same device, just different tabs in Firefox.
I copied the parts of the cookie and pasted them together. 
From #10461 

> Using Jackett Ver 0.17.213.
cfuid did not work
cf_clearance did not work
pass did not work
uid did not work
Those are the only items listed under cookies, what am I doing wrong?
@ilike2burnthing
Collaborator
ilike2burnthing commented 4 days ago

> Use the whole cookie, not the individual parts of it.
> @Freisgd
> Freisgd commented 3 days ago
> 
> Copied and pasted the whole thing and it is still not working
> "__cfduid": "xxxxxxxxxxxxxxxxxxxxx"; "cf_clearance": "xxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxx-x-xx"; "pass": "XXXXXXXXXX"; "uid": "xxxxxx"
> 
> also did a version where the keywords were not in "", same result. (Depended on how you selected the cookie info if here were "'s).
> Sorry for not getting this, I'm fairly intelligent, I swear. Thanks in advance for your help.

**Comment by ilike2burnthing** [comment]
Just to triple check, as I'm a bit confused by what you've actually done here:
- Select and Copy the whole cookie string (everything after the `cookie:` )

https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work

You aren't using the browser extension [Trace](https://absolutedouble.co.uk/trace/) (or anything else which spoofs your IP)?

**Comment by Freisgd** [comment]
This is where I got the cookie information.  It is not a single string and it says requested cookies.  Not sure what I'm doing wrong, but this is the way it appears every time I access it from any computer.

![cookie](https://user-images.githubusercontent.com/77239181/104634842-265e3980-566f-11eb-804a-2d767fd76d1a.png)

**Comment by ilike2burnthing** [comment]
Use the Headers tab - https://raw.githubusercontent.com/Jackett/Jackett/master/.github/cookies-firefox.png

**Comment by Freisgd** [comment]
That would do it. Things are in a different order.  Sorry for the stupidity. ;)

**Comment by ilike2burnthing** [comment]
S'all good
