### ISSUE TITLE
Changes to PassTheHeadphones - Name & Site Link

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1081]
PTH has been renamed to 'Redacted' and the new URL is https://redacted.ch/

I updated the 'Site Link' in Jackett and everything seems to be working fine, The rebranding doesn't seem to have any effects on functionality.

Might be useful to rename PTH and update the Site Link in the next update.

**Comment by kaso17** [comment]
fixed with 6ff50e942ccba3be30074c690e3354f102a3196e
