### ISSUE TITLE
[REQ] Fix Crazy Spirit categories.

### ISSUE THREAD

**Issue by processor83** [Jackett/Jackett#10826]
Hello, its not to report a bug but there is missing catégories like.

https://www.crazyspirits.com/torrents.php?cat=130

I dont know exactly how torrent tracker work i cannot tell you what should be modified but im not able to serach for toute la vie in jacket but its there on the tracker.

thank you

**Comment by ilike2burnthing** [comment]
Please provide an HTML dump of the search page - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

Alternatively, if you have an invite available, I can fix it myself.
