### ISSUE TITLE
[yggtorrent] The cookies provided by FlareSolverr are not valid vps

### ISSUE THREAD

**Issue by powatt** [Jackett/Jackett#10828]
im on debian 10 on a vps jackett and flaresolverr are installed on the same vps ther is a response: "Successful response in 7.412 s"
and i got this error with cookies if you can help me that would be extra gentle have a great day

**Comment by powatt** [comment]
ii forgot to say that i tried both ygg torrent cookies and login

**Comment by ilike2burnthing** [comment]
FlareSolverr version v1.2.3? If not, update.

May be related to the problems identified in https://github.com/Jackett/Jackett/issues/10824

See if the issue consistently occurs after multiple attempts over the next day.

**Comment by powatt** [comment]
all on the last version i got this pb constently happen so i reinstall and update and i still got the pb

**Comment by powatt** [comment]
![s1](https://user-images.githubusercontent.com/77250316/104793412-bbae1a80-57a2-11eb-908a-f1f3c0b4d28a.PNG)
![s2](https://user-images.githubusercontent.com/77250316/104793415-bd77de00-57a2-11eb-851f-ad1e72b704c7.PNG)

**Comment by ilike2burnthing** [comment]
Does this only happen with YGG? If you haven't already, try some of the other indexers which use FlareSolverr - https://github.com/Jackett/Jackett/search?q=flaresolverr

**Comment by powatt** [comment]
after trying with other torrent site it's the same thing

**Comment by ilike2burnthing** [comment]
From within each container (Jackett and FlareSolverr) run:
`curl -v https://api.ipify.org/`
and confirm that the IP addresses match.

**Comment by blackmessor** [comment]
Hi got the same issue since 2 days
I'm not able to run the `curl -v https://api.ipify.org/` command line from the FlareSolver container as Curl is not available

**Comment by ilike2burnthing** [comment]
@ngosang can curl be added to the Docker container, or is there a better method for doing this (or is it pointless and not likely to be the issue)?

**Comment by ngosang** [comment]
You can use FlareSolverr from any computer instead of cURL inside the container:
```
curl -L -X POST 'http://flaresolverr_ip:8191/v1' --data-raw '{"cmd": "request.get", "url":"https://api.ipify.org/"}'
```
I will add a this feature in FlareSolverr in the future => https://github.com/FlareSolverr/FlareSolverr/issues/71

**Comment by louia** [comment]
not working for me, yggtorrent or yggCookie with FlareSolverr

**Comment by blackmessor** [comment]
I try what you ask and i got the same IP adress for both containers

**Comment by blackmessor** [comment]
Ok, i find the issue after you talk about IP adress.
When i try you're commande line, i got the same Ip adress .... but, on my jacket i have a proxy settings
When i disable it, it works. 

This is strange as it was working before. Did you change something recently ?

**Comment by ilike2burnthing** [comment]
If you were using a proxy in one and not the other, it never should have worked.

**Comment by ilike2burnthing** [comment]
There have been a few recent changes to the indexer and the site is currently not using Cloudflare DDoS Protection. Please try [v0.17.348](https://github.com/Jackett/Jackett/releases/tag/v0.17.348) and see if your issue is resolved.
