### ISSUE TITLE
No MagnetUri or InfoHash using 1337x

### ISSUE THREAD

**Issue by Jakobohrnell** [Jackett/Jackett#10829]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**Jackett Version**: v0.17.284

**Last Working Jackett Version**: None

**Are you using a proxy or VPN?**: No

### Description

How come 1337x doesn't return magnet links or infohashes and only the jackett redirect links? 

Attached a screenshot as example. 

The InfoHash and MagnetUri are both empty and I must instead get the magnet link through another request to the "link" url.

### Screenshots

![image](https://user-images.githubusercontent.com/26467980/104798285-561b5780-57bd-11eb-9f4f-38d7dd5275f4.png)

**Comment by ilike2burnthing** [comment]
Because there are no magnet or torrent links in the results page, and no way to create one from the information available.
