### ISSUE TITLE
Add support for proxy configuration to the GUI [$50]

### ISSUE THREAD

**Issue by kaso17** [Jackett/Jackett#1083]
proxy support should be configurable via the webgui (command line args are not available for the windows service).

**Comment by 00Asgaroth00** [comment]
Hi,

Would this include socks5 with authentication as a proxy option? My vpn provider has a scoks5 service which I would like jackett to make use of. However, I'm, currently, not sure how to configure jackett to use a socks 5 proxy with authentication.

**Comment by kaso17** [comment]
The .NET httpclient doesn't support socks proxies. It probably would require significant low level workarounds to make it work. I won't implement it. I suggest you ask your VPN provider to provide a HTTP proxy.

**Comment by IBeRamen** [comment]
@kaso17 Running Jackett as a Windows Service. So at the moment from what I understand Jackett does not work with HTTP Proxies on Windows with authentication? Currently running this in console:

`JackettConsole.exe -j username:password@host:port` which didn't work.

I also tried `JackettConsole.exe -j host:port` but that returns a System.net.WebException error (407) authentication required.

**Comment by kaso17** [comment]
authentication is definitely not implemented for the httpclient.
Shouldn't be hard to add. Example: http://stackoverflow.com/questions/29856543/httpclient-and-using-proxy-constantly-getting-407
But I don't have a proxy and I'm currently to lazy to set one up for testing.

**Comment by macbean101** [comment]
if using Linux, should a socks proxy with authentication work?

**Comment by atwright147** [comment]
An alternative could be to implement a scraper to automatically get alternative URLs from a ProxyPortal site if a request fails.

**Comment by kaso17** [comment]
@atwright147 can you explain a little bit more? what's a proxy portal site?

**Comment by atwright147** [comment]
This: https://proxyportal.org

**Comment by moarf56** [comment]
Hey !

I hope proxy will be configurable via the webgui

**Comment by lawrenceadams** [comment]
This would be really cool - is there any news regarding this?

**Comment by Martins2759** [comment]
I would also like to show my interest in this.
@atwright147 suggestion works for those of us in countries where the sites are blocked, but is definately not optimal.

**Comment by Smalfinn** [comment]
Definitely support this!

**Comment by moarf56** [comment]
I hope we can use it soon !

**Comment by Smalfinn** [comment]
I have upped the bounty to $50 🗡

**Comment by n1nj4888** [comment]
I’ve upped the bounty on this to $65. 

Would be great to have SOCKS5 and/or HTTPS proxy support configurable in the web GUI and option to configure proxy server, port, username and password...

**Comment by IBeRamen** [comment]
I will begin work on this. Hopefully I can get it working.

**Comment by Smalfinn** [comment]
Awesome, thanks IBeRamen

**Comment by moarf56** [comment]
Yes :d thx IBeRamen

**Comment by IBeRamen** [comment]
Can anyone suggest a site that has free proxies I can test it on? Preferably with a password.

**Comment by Smalfinn** [comment]
Shall I message you my TorGuard details to test?

**Comment by lawrenceadams** [comment]
I can lend you my PIA proxy login if you would like?

**Comment by IBeRamen** [comment]
If possible that would be great!

**Comment by flightlevel** [comment]
A big thanks to @sv01a who has now implemented proxy settings the UI 
Proxy settings are now available in pre-release https://github.com/Jackett/Jackett/releases/tag/v0.8.349
Please try it out

**Comment by evilvibes** [comment]
This don't support SOCKS5 ?

**Comment by sv01a** [comment]
Yes, only http proxy supports for now. Will try to add socks tomorrow.

**Comment by Smalfinn** [comment]
HTTP proxy enabled causes time out errors with sonarr

`Zooqle (Jackett) server is currently unavailable. http://localhost:9117/api/v2.0/indexers/zooqle/results/torznab/api?t=tvsearch&cat=4000,8000,4050,2000,3000,7010,5000,5070&extended=1&apikey=(removed)&offset=0&limit=100 The request was aborted: The operation has timed out.`

**Comment by sv01a** [comment]
Are you sure that proxy is working? Do you try Jackett manual search?

**Comment by Smalfinn** [comment]
Yes, manual search works perfectly

**Comment by sv01a** [comment]
Manual search also work through proxy.  By the error message: request took much time and aborted by time out. You can try another proxy?

**Comment by Smalfinn** [comment]
Horriblesubs, the pirate bay and RARBG seem to work okay, just zooqle that is showing this error:
`Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings.`

**Comment by flightlevel** [comment]
SOCKS support now in pre-release thanks to @sv01a 
Please try it out and provide feedback

**Comment by evilvibes** [comment]
SOCKS5 is working! Nice work @sv01a 

Thanks

**Comment by n1nj4888** [comment]
Great work @sv01a !!! 

SOCKS proxy seems to work great. Has anyone tested HTTP/HTTPS (if supported) proxy?

Many thanks once again!

**Comment by Mavrag** [comment]
Hey guys could you recommend me a proxy server that will work with jackett now, pretty please.

**Comment by flightlevel** [comment]
Now available with general release

**Comment by nickpaul41** [comment]
Thanks for implementing this!!!!
