### ISSUE TITLE
Easy issue with Elite-tracker

### ISSUE THREAD

**Issue by blackmessor** [Jackett/Jackett#10836]
Hi 

Is this possible to add the option :

"Enhance sonarr compatibility with anime by renaming episode (xxx to exxx). Works only if episode is at the end of the query. Can disturb movies search. (back to the future 3 -> back to the future e3)"

on the Elite-tracker torrent. This tracker has the same issue with Animes.
Great Thx

**Comment by JigSawFr** [comment]
As tracker is now definitely down, it will be removed from jackett.

**Comment by garfield69** [comment]
Usual to leave ticket open until the remove is complete ;-)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/11245 already open for this tracker being down
