### ISSUE TITLE
[polishsource] Login failed: Selector

### ISSUE THREAD

**Issue by jendru214** [Jackett/Jackett#10834]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: newest

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

This happens when trying to add the indexer and typing in the correct capacha

### Logged Error Messages

Login failed: Selector "a[href^="logout.php"]" didn't match

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Version number of Jackett please, 'newest' does not help. Your OS may also be helpful to know here.

I briefly recreated this issue by trying to sign back in. I removed the indexer from Jackett, restarted Jackett and added it again without issue. That doesn't really help you here though, as there's nothing to remove, but try restarting Jackett, see if it helps.

If not, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by jendru214** [comment]
Windows server Jackett Version v0.17.284
For now it started working for me as well but randomly from time to time it shows as not working and when I try to check the settings and reenter the capatcha I get the error above in a popup window.

**Comment by jendru214** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/5826468/log.txt)
Here are the logs

**Comment by ilike2burnthing** [comment]
Please follow the instructions in the the link above to provide an **enhanced** log, but it looks like their `anti-flood script` is the issue.
