### ISSUE TITLE
[animeworld] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by IITuxtmuxII** [Jackett/Jackett#10832]
### Environment

**OS**: docker (linuxserver)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.231
 
**Are you using a proxy or VPN?** no

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/10578#issuecomment-761725205

**Comment by ilike2burnthing** [comment]
Can you login to the site in browser from the same device and IP?

If so, remove the indexer from Jackett, restart Jackett, and try to re-add animeworld. If that fails, post an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by ChiefORZ** [comment]
@IITuxtmuxII i had to login and accept some Terms and add seed-times, as well as dsl speed in the settings - after these preperations i was able to add to it to jackett
