### ISSUE TITLE
Retroflix API Implementation 

### ISSUE THREAD

**Issue by costyglx** [Jackett/Jackett#10838]
Retroflix is getting some refactoring and redesign and the changes broke Jackett and will probably break Jackett frequently.

To mitigate that, Retroflix added an API implementation that is almost identical to SpeedApp's API (there's some new fields in Retroflix's API, but I don't think they are meaningful for Jackett).

Adding support in Jackett would probably mean refactoring SpeedApp's implementation to use the download_volume_factor and upload_volume_factor that SpeedApp's API now provides and then creating a new Retroflix API class that inherits SpeedApp's class, but sets a different category mapping.

Since Retroflix has 8 kinds of torrent promotions (normal, free, 2x_up, free_2x_up, half_down, half_down_2x_up, 30pct_down, free_3x_up) we added support for upload_volume_factor and download_volume_factor (in both, Retroflix and SpeedApp) so we compute those values server-side so that you don't have to check 8 different booleans or 1 integer with 8 possible values.

Can you please add support for Retroflix's API?

**Comment by ngosang** [comment]
Easy peasy. Nice API by the way. I hope other trackers follow you.

**Comment by costyglx** [comment]
Thank you very much :)

**Comment by ilike2burnthing** [comment]
[v0.17.311](https://github.com/Jackett/Jackett/releases/tag/v0.17.311)

**Comment by garfield69** [comment]
retroflix login is using username not email, which is the default login mode for the speedAppTracker abstract that retroflix is using to access the similar API that the speedApp indexer is using.

So the retroFlix indexer needs to have an override added to get it to present and use the username in the indexer's config

**Comment by garfield69** [comment]
I am not able to use the speedapp indexer ATM. When I try to login with the indexer I get 
`System.ArgumentNullException: Value cannot be null. (Parameter 'source')`

anyone else?

**Comment by ngosang** [comment]
The API has been working fine for me for months.

**Comment by garfield69** [comment]
https://speedapp.io/ returning Error 502 Bad gateway
this applies also to retroflix which is a dependent fo the speedapp abstract
https://retroflix.club/ returning Error 502 Bad gateway
https://www.uptrends.com/tools/uptime reports Website is available got 11 of its worldwide checkpoints, and Http Protocol Error for the other 32 checkpoints.

**Comment by garfield69** [comment]
online.
