### ISSUE TITLE
[REQ] yestorrent.net

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#10859]
Spanish public tracker of movies and TV

https://yestorrent.net/

**Comment by garfield69** [comment]
the site has many downloads that are cloud-based links, that is, they take you to an alternate service that requires further clicking and you might get a .torrent, or a direct download. (this site prefers https://salaload.me/ as its 3rd party file provider).
Jackett cannot support direct downloads, only ones that provide links to magnets or .torrent without intervening steps.
For this reason I think it very unlikely this site get an indexer written.

Additionally, the site has a one-title-many-torrents layout.
no links are available on the main search results page, but on the each titles details page.
this would require an indexer written in C#
I'll shift this to the C# stack, maybe some one can come up with something.

**Comment by garfield69** [comment]
https://yestorrent.net/ returns ERR_CONNECTION_REFUSED

**Comment by 97carmine** [comment]
Consider reopening, the new domain is [yestorrent.cx](https://yestorrent.cx/)

**Comment by ilike2burnthing** [comment]
Individual episodes are on the details page rather than results page, meaning users could be making dozens of requests to the site at once, a quick way to get their IP banned for bot activity if also teamed with automation software like Sonarr and Radarr.
