### ISSUE TITLE
[bjshare] Exception (bjshare): The operation was canceled.: The operation was canceled. (Test)

### ISSUE THREAD

**Issue by timartinelli** [Jackett/Jackett#10854]
### Environment

**OS**: Ubuntu 20.4

**.Net Runtime**: Mono

**.Net Version - MONO**: 6.12.0.107

**Jackett Version**:

**Last Working Jackett Version**: v0.17.311

**Are you using a proxy or VPN?** [yes/no] no

### Description
Apparently bj-share stopped working, it was normal these days. I put the log down.

### Logged Error Messages

Fulllog https://pastebin.com/hSnTcnfH

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
See if these troubleshooting steps help - https://github.com/Jackett/Jackett/wiki/Troubleshooting#the-operation-was-cancelled

If not, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by timartinelli** [comment]
without me having to do anything like that it worked again.

good better like that.
