### ISSUE TITLE
[DivxTotal] Current SiteLink is a scam

### ISSUE THREAD

**Issue by danimart1991** [Jackett/Jackett#10864]
Current site link for DivxTotal: https://www.divxtotal.one/ is a scam and links downloads a .zip file with a Visual Basic Script inside it.

This URL must be changed or deleted. I don't know the current DivxTotal official site.

**Comment by ilike2burnthing** [comment]
@ngosang I can't replicated this, but presumably it's similar to https://github.com/Jackett/Jackett/issues/10659

**Comment by danimart1991** [comment]
It seems that I don't explain well. But you are right.

If you download a torrent manually from the current link for DivxTotal: https://www.divxtotal.one it downloads a wrong .zip file. But the strange thing here. Is that Jackett actually downloads the .torrent right 🤔

It's a bug and the web is broken to infect with virus? Maybe.

**Comment by ilike2burnthing** [comment]
No, you explained it fine 🙂 there was a similar issue with mejortorrent, where the download link would be a zipped .vbs file, see this comment specifically - https://github.com/Jackett/Jackett/issues/10659#issuecomment-752202793

So does Jackett already avoid this problem and only download the torrent files (so we don't need to fix anything)? Another reason to use Jackett! 😉

**Comment by danimart1991** [comment]
You are right. There is no issue in Jackett then.

Maybe this issue could be closed in any case
