### ISSUE TITLE
[yggcookie] Exception (yggcookie): The operation was canceled.: The operation was canceled. (Test)

### ISSUE THREAD

**Issue by nini57** [Jackett/Jackett#10867]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:v0.17.324

**Last Working Jackett Version**: I don't know
![Capture](https://user-images.githubusercontent.com/55365340/105053952-c81bc700-5a71-11eb-8056-07709724e13f.JPG)

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Switch to yggtorrent and let us know if that solves things for you, yggcookie currently doesn't work.

**Comment by nini57** [comment]
> Switch to yggtorrent and let us know if that solves things for you, yggcookie currently doesn't work.

I've the same problem

**Comment by ilike2burnthing** [comment]
See if these troubleshooting steps help - https://github.com/Jackett/Jackett/wiki/Troubleshooting#the-operation-was-cancelled

If not, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
