### ISSUE TITLE
[Bug] Kat.how - Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1087]
Enhanced log attached.
[log.txt](https://github.com/Jackett/Jackett/files/788699/log.txt)

Jackett version:  0.7.1043.0
Mono version (if not using Windows):  N/A

**Comment by kaso17** [comment]
https://kat.how/search.php?&q=

```
E_WARNING: [2] file_put_contents(/home/domains/kat.how/db/rewrite/t0/17/90/t0-[UNCENSORED]Tokyo-Hot_n1225-tt17162390.json): failed to open stream: No space left on device
string 'functions.php' (length=13)
int 212
```

Probably will fix itself once they fix their storage problem.
