### ISSUE TITLE
MononokeBT loose cookies after redirect happen when downloading torrent file (no download possible)

### ISSUE THREAD

**Issue by xfouloux** [Jackett/Jackett#10875]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: docker

**Jackett Version**: Jackett Version v0.17.311

**Last Working Jackett Version**: never used the indexer before

**Are you using a proxy or VPN?** no

### Description

listing the torrents work fine, then downloading results in an issue, redirecting the download to the login page, i tried to change the login to a form and it doesn't help.
I tried to add a download: bloc, to force a relogin before downloading, no luck too :/
If someone has an idea ^^

some changes i made to test
```
---
...
...
settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: vostfr
    type: checkbox
    label: Add VOSTFR to titles
    default: false
  - name: IMPORTANT_FR
    type: info
    label: (FR) Informations Importantes
    default: Avant de pouvoir télécharger un torrent depuis Jackett, allez dans la <a href="https://mononoke-bt.org/faq.php" target="_blank">FAQ</a> et cliquer tous les 'Lu et Approuvé' de la page , ensuite téléchargez manuellement un torrent pour désactiver la page intermediaire.
  - name: IMPORTANT_EN
    type: info
    label: (EN) Importortant infos
    default: Before you can even begin to download anything you need to go to the <a href="https://mononoke-bt.org/faq.php" target="_blank">FAQ</a> and click every 'Lu et Approuvé' present on the page , then download manually one torrent to permanentely deactivate the intermediate download page.

login:
  path: login.php
  submitpath: takelogin.php
  form: form[action="takelogin.php"]
  method: form
  inputs:
    username: "{{ .Config.username }}"
    password: "{{ .Config.password }}"
  error:
    - selector: td.embedded:has(h2:contains("l'authentification"))
  test:
    path: browse2.php

download:
  method: get
  before:
    path: takelogin.php
    method: post
    inputs:
      username: "{{ .Config.username }}"
      password: "{{ .Config.password }}"

....
....
```

you need to do this steps in order to be able to download first :
Before you can even begin to download anything you need to go to the <a href="https://mononoke-bt.org/faq.php" target="_blank">FAQ</a> and click every 'Lu et Approuvé' present on the page , then download manually one torrent to permanentely deactivate the intermediate download page.

### Logged Error Messages

[mononokebt_trace.txt](https://github.com/Jackett/Jackett/files/5840487/mononokebt_trace.txt)

**Comment by ilike2burnthing** [comment]
Adding the info note should be sufficient as it's a requirement of the site. Can you make a PR for it?

**Comment by xfouloux** [comment]
unfortunately, adding the note isn't sufficient, i'm unable to download any torrents, even after doing the 'Lu et Approuvé' in the FAQ. In the logs you can see you get redirected following the download link, then another redirect, and at this point jackett is redirected to the login page instead of downloading the torrent.

**Comment by xfouloux** [comment]
being redirected to https://mononoke-bt.org/gettorrent.php?torrent=%5B-SeT-%5D_Clannad_After_Story_Saison_2_11-15.torrent&id=19975&r=1%22%3E[-SeT-]_Clannad_After_Story_Saison_2_11-15.torrent

in the debug you get 

```
01-20 06:12:51 Debug WebClient(HttpWebClient2): Returning Redirect => http://mononoke-bt.org/gettorrent.php?torrent=%5B-SeT-%5D_Clannad_After_Story_Saison_2_11-15.torrent&id=19975&r=1">[-SeT-]_Clannad_After_Story_Saison_2_11-15.torrent 2430 bytes
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
 <script type="text/javascript" src="js/general.js"></script>
 <style type="text/css">
 div.box  {  border: 1px solid #396a98;  background: #cfe8ff;   }
 div.title  {  background: #396a98;    color: white;        }
 div.title  {  font-size: 20px;       padding: 5px 5px 5px 5px; }
 div.content {  padding: 5px 5px 5px 5px; }
 .clickable {  cursor:pointer;cursor:hand;    text-decoration: underline;  }
</style>
</head>
<body>
 <div class="box">
  <div class="title">Téléchargement : <b>Clannad: After Story 11 -> 15 [BD 1080p 10bit]</b> par <b>SeedTeam</b></div>
  <div class="content">
  <table border=0><tr><td valign="top"><img src="/pic/icons/cadeau2-large.png"></td><td><b>Torrent privé hors ratio (promo)</b><br />Accessible uniquement aux membres inscrits.<br />
Seul l'Upload compte dans le ratio.<br />
Aucun temps d'attente ni restriction.</td></tr></table><br /><br />  Tu vas télécharger un torrent <b>personnalisé</b> qui contient une clé d'identification permettant de le relier à ton compte sur ce site.
<br /> Cette clé permet au tracker de savoir exactement qui download quoi sans avoir à se baser sur l'adresse IP :
<ul>
 <li><b>Plus de problèmes avec les IP dynamiques</b>
  <br />Puisque ce torrent porte ta clé, le tracker sait d'où viennent les connexions même si ton IP change.
</li><li><b>Plus besoin de s'authentifier sur le site</b>
  <br />Tu peux te connecter sur le site depuis une autre IP que celle depuis laquelle tu fais tourner ton BitTorrent, sans que celà dérange le tracker.
  <br />Tu n'as pas besoin de te loguer sur le site avant de lancer bittorrent puisque l'information est dans le torrent.
</li><li><b>Comme les fichiers .torrent sont personnalisés, si tu donnes à tes amis un fichier .torrent downloadé ici, les téléchargements qu'il effectuera seront reportés sur ton ratio. De même, si tu mets un fichier .torrent downloadé ici dans un répertoire partagé par emule.</b>
</li>
</ul>
<br />
<div id="xhtarget"><span class=clickable onclick="XHLoadInto('xmlhttp.php?action=prefs_hide_torrent_popup','xhtarget');">Ne plus afficher ce message</span></div>
<div align="right">
 Télécharge [ <a href="/gettorrent.php?torrent=%5B-SeT-%5D_Clannad_After_Story_Saison_2_11-15.torrent&id=19975&r=1">[-SeT-]_Clannad_After_Story_Saison_2_11-15.torrent</a> ]
</div>
  </div>
 </div>
01-20 06:12:51 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: http://mononoke-bt.org/gettorrent.php?torrent=%5B-SeT-%5D_Clannad_After_Story_Saison_2_11-15.torrent&id=19975&r=1">[-SeT-]_Clannad_After_Story_Saison_2_11-15.torrent)
01-20 06:12:52 Debug WebClient(HttpWebClient2): Returning Redirect => http://mononoke-bt.org/login.php?returnto=%2Fgettorrent.php%3Ftorrent%3D%255B-SeT-%255D_Clannad_After_Story_Saison_2_11-15.torrent%26id%3D19975%26r%3D1%2522%253E%5B-SeT-%5D_Clannad_After_Story_Saison_2_11-15.torrent 0 bytes
01-20 06:12:52 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: http://mononoke-bt.org/login.php?returnto=%2Fgettorrent.php%3Ftorrent%3D%255B-SeT-%255D_Clannad_After_Story_Saison_2_11-15.torrent%26id%3D19975%26r%3D1%2522%253E%5B-SeT-%5D_Clannad_After_Story_Saison_2_11-15.torrent)
```

so i tried to do this :

```
download:
  method: get
  selector: a[href^="/gettorrent.php?torrent="]
  attribute: href
  before:
    path: takelogin.php
    method: post
    inputs:
      username: "{{ .Config.username }}"
      password: "{{ .Config.password }}"

```
but seems to not work :/ i get a big blob of data and jackett crash.

**Comment by ilike2burnthing** [comment]
If you paste `http://mononoke-bt.org/gettorrent.php?torrent=%5B-SeT-%5D_Clannad_After_Story_Saison_2_11-15.torrent&id=19975&r=1` into your browser does it download?

If yes, if you open a private/incognito browser window, sign into the site and try the link again, does it still download?

If no (actually, either way) try changing the login to cookies rather than credentials, see if that makes any difference.

**Comment by xfouloux** [comment]
Hey,

it works in normal and private mode

Indeed i was afraid it would need to be cookie mode, but i wanted to avoid this, i'll do a test in cookie mode and let you know, it's just weird jackett isn't able to reuse the cookie it gets from login.

**Comment by ilike2burnthing** [comment]
@xfouloux ping

**Comment by xfouloux** [comment]
oops didn't had time these past weeks to do stuff oustide of work ! i'll get some time this week end to complete this =) Thanks for the ping

**Comment by xfouloux** [comment]
Can someone test the PR ? And confirm it works out of the box ?

Maybe i should still include this block of infos in case ?

```
  - name: IMPORTANT_FR
    type: info
    label: (FR) Informations Importantes
    default: Avant de pouvoir télécharger un torrent depuis Jackett, allez dans la <a href="https://mononoke-bt.org/faq.php" target="_blank">FAQ</a> et cliquer tous les 'Lu et Approuvé' de la page.
  - name: IMPORTANT_EN
    type: info
    label: (EN) Importortant infos
    default: Before you can even begin to download anything you need to go to the <a href="https://mononoke-bt.org/faq.php" target="_blank">FAQ</a> and click every 'Lu et Approuvé' present on the page.
```

**Comment by ilike2burnthing** [comment]
I think you're the only one with an account, so if it works for you I'm happy to publish.

Feel free to add the info sections too.

Can you also test if https is working? Their certificate appears to be valid now. If so, add the http URL as a legacylink.

Not sure if there's an issue with the pipeline, but the build has failed. Doesn't seem to be anything to do with your PR.

**Comment by xfouloux** [comment]
HTTPS won't work for downloading unfortunatelly, so i've put it in legacylinks
added information blocks, sending commit now

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/blob/1c130a1e846400cda03df55850620afb864ccb85/src/Jackett.Common/Definitions/zamundanet.yml#L126-L127

Just had to use this for an indexer. Don't know if it would help you get credentials login working with downloads (obviously a different cookie), but thought I'd mention it in case there's something specific missing.
