### ISSUE TITLE
webUI: FIX torrent Name column in search results has unusably narrow width

### ISSUE THREAD

**Issue by allanlaal** [Jackett/Jackett#10872]
![Screenshot_2021-01-19 Jackett](https://user-images.githubusercontent.com/740826/105081600-109baa80-5a9b-11eb-9f3b-6b4708f57012.png)

### Environment

Jackett Version v0.17.294 
Firefox 85.0b8 (64-bit) (zoom is at 100%)
window width: 1680px

**Comment by ilike2burnthing** [comment]
Other than the Tracker and Category columns, are any of the values overly long e.g. one result supposedly have 41767534526 seeds?

@ngosang would it be worth us trimming some of the indexer names (e.g. `Torrent9 clone (torrent9.ch)`) so they don't eat into the width of the Name column? For the same reason, would be possible (and also desirable) to break categories on `/` to put the subcategory on a second line)?

**Comment by xfouloux** [comment]
You could get rid of the 'ago' displayed in Published too, because well torrent can't be published ahead of time ;) ! you gain a few pixels =p
All tags like FREELEECH and such could also benefit going into a break line if let say Torrent title name longer than XX characters ?

**Comment by ngosang** [comment]
Well I think the issue is the user display is too small. I never had this problem but anyway we can improve a bit.

>  would it be worth us trimming some of the indexer names (e.g. Torrent9 clone (torrent9.ch)) so they don't eat into the width of the Name column? 

Yes I agree. Feel free to change the names but be careful with the ids ;)

About the other changes I have to think about because each torrent will take 2 lines instead of 1 and we have to scroll more... If this issue is only in small screens I don't want to bother most users...

**Comment by ilike2burnthing** [comment]
I take it there's no reason why a different aspect ratio would mess with things, e.g. 1680x1050 (16:10) from above?

I'll have a crack at trimming some of the names now.

**Comment by ilike2burnthing** [comment]
[v0.17.370](https://github.com/Jackett/Jackett/releases/tag/v0.17.370)

**Comment by garfield69** [comment]
we could make more room on the table by reducing the column headers for Seeds -> S, and similar for Files -> F, Grabs ->G, Leechers ->L, DL Factor -> DLF, UL Factor -> ULF and Download -> DL, and adding a tooltip hover that expands those column headers to their full name for those seeking info. 
IMO this would expand the area for the Name columns by some margin. I shall play with the template and see how it looks.

**Comment by garfield69** [comment]
example:
![image](https://user-images.githubusercontent.com/6933240/185366456-dffe8b5f-590a-4c1a-af69-02ead226e1f0.png)

**Comment by garfield69** [comment]
v0.20.1743
