### ISSUE TITLE
Search trackers both in names and URLs

### ISSUE THREAD

**Issue by helperman** [Jackett/Jackett#10870]
I search tracker by its URL and nothing found:
https://i.imgur.com/1u85GFG.png

I search tracker by its name and it is found:
https://i.imgur.com/Wqq52Wb.png

I would be better to show results for URLs and names.

**Comment by ilike2burnthing** [comment]
A minor inconvenience, but is this doable @ngosang?

**Comment by swannie-eire** [comment]
+1 for me

**Comment by garfield69** [comment]
v0.20.363
