### ISSUE TITLE
Retroflix "[REQUESTED]" in title 

### ISSUE THREAD

**Issue by ghost** [Jackett/Jackett#10883]
### Description

Lots of searches on the tracker have [REQUESTED] in the title and Sonarr and Radarr "Failed to find movie title in release name [REQUESTED] MovieName". So maybe the [REQUESTED] part can be removed or something so that the titles can be determined?
Separate issue tracker doesn't return actual filenames so the Arrs can't determine year, resolution, etc

**Comment by ngosang** [comment]
@costyglx I removed the "[REQUESTED]" tag in out side but it's still causing problems with Sonarr.
Could you change the value of the field "name" in the RetroFlix API to return the movie name in the Scene format?
title + year + format

Current:
name = Affair in Trinidad
Expected:
name = Affair in Trinidad 1952 1080p

Or even better, you can return the torrent name (without retroflix and extension)
![image](https://user-images.githubusercontent.com/10577978/106382707-a996c380-63c1-11eb-92d7-eeee54074ae6.png)

**Comment by costyglx** [comment]
Thanks, we have new 2 new fields for every torrent: #1 torrent_filename, it's the name of torrent taken from the info dictionary
#2 p2p_release_name it's autogenerated, based on the imdb name, country (if it's not american), year and info from mediainfo (resolution, codec). Those new were added only for api, the existing ones needed to remained unchanged. There are a lot of movies from p2p sources from users that didn't know "the scene way", so I hope the new changes will help.

**Comment by ilike2burnthing** [comment]
[v0.17.437](https://github.com/Jackett/Jackett/releases/tag/v0.17.437)

**Comment by Paul5656** [comment]
Ping @ilike2burnthing @ngosang . Just making sure we didn't forget to push the update based on @costyglx update.

**Comment by garfield69** [comment]
v0.18.317
