### ISSUE TITLE
.click sites should use Exact searching and Titles only

### ISSUE THREAD

**Issue by adamwinn** [Jackett/Jackett#10887]
### Environment

**Jackett Version**:
v0.17.333

**Last Working Jackett Version**:
n/a

**Are you using a proxy or VPN?** [yes/no]
no

### Description

The .click sites (https://theplace.click https://thevault.click https://theoccult.click https://thegeeks.click https://theshow.click https://theempire.click) use Fuzzy matching and dont search Titles only by default.  This leads to some wildly inaccurate search results.

I believe the search that Jackett performs should use the Exact filter and search Titles only.

### Screenshots

Default:
![Screen Shot 2021-01-20 at 8 18 08 PM](https://user-images.githubusercontent.com/3028964/105275889-76506b00-5b5d-11eb-9c3b-31ab48c6ce56.jpg)

Suggested:
![Screen Shot 2021-01-20 at 8 18 23 PM](https://user-images.githubusercontent.com/3028964/105275901-7cdee280-5b5d-11eb-98d2-5fc17752a09f.jpg)

**Comment by ilike2burnthing** [comment]
theempire and theplace are using an `andmatch` filter as a workaround for this, but certainly if there's a way to do it via the site then all the better.

I don't have an account for any of the sites, so I'd need an HTML dump of the search area of one of the sites (or the whole search page if you're unsure) - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

I'd also need a few answers from you:
1) is this code shared between all the sites? (if you're unsure I can tell you what to look for later)
2) I take it `exact` search doesn't take keyword order into consideration? (e.g. searching for `doctor who 720p` would still find `Doctor.Who.S10E01.720p...`)
3) you up for being a guinea pig? 😋

**Comment by adamwinn** [comment]
`andmatch` might work.  I can run a few tests on theempire or theplace to try it out.

Search result for "Seeing Things"
[TheEmpire __ Search results for _Seeing Things_.txt](https://github.com/Jackett/Jackett/files/5846807/TheEmpire.__.Search.results.for._Seeing.Things_.txt)

1.  I assume so.  They all look identical and the search area is identical to the images in my first post (as far as Fuzzy/Title Only.  Search categories listed on each are obviously different)
2.  Ya I dont know if `exact` is the right one or just checking the checkbox for Title Only would be enough.  Or even if using the `andmatch` code used for the other sites would work too.  All I know is I searched for "Seeing Things" and got like 800 pages of pure crap.
3. I've been a guinea pig my whole life

Search options available:
![Screen Shot 2021-01-20 at 9 20 26 PM](https://user-images.githubusercontent.com/3028964/105279779-8704df00-5b65-11eb-9479-1ec5ca110aee.jpg)

**Comment by ilike2burnthing** [comment]
Thanks. Yep, that would be simple enough to add.

Go to the search page for each of the sites, press `Ctrl+U` (it will open the source in a new tab), then `Ctrl+F` and search for `Fuzzy`. You should see this:
```
    <select name=nonboolean>
        <option value=1>Fuzzy</option>
        <option value=0>Exact</option>
        <option value=3>Parsed</option>
        <option value=4>Simple</option>
        <!--<option value=2>Pure</option>-->
    </select>&nbsp;&nbsp;		
<input style="padding:0px;margin:0px;margin-right:3px;" name="titleonly" id="titleonly" type="checkbox" value=1 ><label for="titleonly">Title Only</label>&nbsp;
```
What I need to confirm is if the number values for each of the options is the same across the sites (probably are, but best not to guess), and the same for the name `titleonly` and its value of 1 when ticked.

Can you try a few different searches using those different options and `Title Only`, see if you can find a 'best' combination? I'll trust your judgement.

I'd also need to check that an empty/keywordless search with those options doesn't affect the results. So, for example, `https://theempire.click/browse.php?search=&nonboolean=0&titleonly=1` returns at least roughly (if not exactly) the same as `https://theempire.click/browse.php?search=`

The issue with `andmatch` is that the search would still return those 800 pages of crap, Jackett would get the first one, and then only select the results which matched the keywords (could be 23, could be 5, could be 0).

>I've been a guinea pig my whole life

It has its perks, can't beat that fresh straw bedding 😉 
**DISCLAIMER: Jackett makes no guarantees about the freshness of the straw provided**

**Comment by adamwinn** [comment]
Yes, the number values for that select list are the same across the sites.  Same for the value for `titleonly` too

I think `titleonly` needs to be checked by default.  That'll cut down on a lot of the noise.  The type of search can be up for debate.  If you think `Exact` will be too strict, then just leaving it at the default of `Fuzzy` (with `titleonly` selected) cuts down the noise considerably. 

Using the search term of "Seeing Things" and `titleonly` checked, `Fuzzy` and `Parsed` yield the same results. ('The Nature of Things' and 'Seeing Things').   `Exact` and `Simple` also yield the same results ('Seeing Things').

`https://theempire.click/browse.php?search=&nonboolean=0&titleonly=1` and `https://theempire.click/browse.php?search=` return the exact same listings.

**Comment by ilike2burnthing** [comment]
Great! So, last steps:
- Download and unzip - [theempire.zip](https://github.com/Jackett/Jackett/files/5850539/theempire.zip)
- Replace the `theempire.yml` in the `Definitions` folder in your installation directory with the new one (if you're using Docker, see https://github.com/Jackett/Jackett/issues/10646#issuecomment-751949776 instead)
- Restart Jackett
- Run a few searches with The Empire
- Profit?

**Comment by adamwinn** [comment]
It works perfectly! Thanks a lot!

**Comment by ilike2burnthing** [comment]
Thanks for all the testing. Fix for all of the .click indexers will be out in the next release (~4hrs).

**Comment by ilike2burnthing** [comment]
[v0.17.343](https://github.com/Jackett/Jackett/releases/tag/v0.17.343)
