### ISSUE TITLE
No results on cinecalidad Indexer

### ISSUE THREAD

**Issue by coldiak** [Jackett/Jackett#10880]
`###` Environment Raspbery Pi

**OS**: Raspbian (Diet-Pi)

**Jackett Version**: v0.17.333

its a spanish Bittorent Tracker, it happens with some movies on radarr, i think it´s with the translated titles of movies.
example: ifi search manually the movie Avengers: Age of Ultron on the tracker i get 1 result and if i search the transtlated version Avengers: Era de ultron  i got the same result but if i search on the search button of Jackett with this Avengers: Age of Ultron i got no result but with the second  got 1.

can you fix this? thanks!!!

https://i.imgur.com/smYX49P.png
https://i.imgur.com/smYX49P.png

https://i.imgur.com/usRaQFq.png
https://i.imgur.com/Y373XXr.png

**Comment by ilike2burnthing** [comment]
@ngosang I take it this is because the keywords don't match the result title? Can that be removed? The results on the site seem to be accurate.

As an aside, looks like there's a new official proxy *.li

**Comment by coldiak** [comment]
if i remove Age of Ultron shows me all the avengers movies in the jackett search, but in the manual search of Radarr  doesn't shows me the movie from this tracker

**Comment by diegargon** [comment]
I got 0 results searching manually "Avengers" in Cinecalidad and i think that ok. Why?

The indexer have configurable language, Spanish and Latino, the movie is in Latino, then if you have the indexer in spanish
the result must be 0.

I don't known why radarr show you 1 result ¿perhaps from other indexer?

i doing a alternative app for radarr/sonarr check my repo (trackerm) if you want try (need testers :P).

**Comment by coldiak** [comment]
sorry, its no my first language english maybe i didnt express ok,
i use the the Latino indexer, and with Latino avengers shows me 4 results

https://i.imgur.com/mTQK3wh.png

 the difference between Latino and Spanish is the translation of the movie titles names, that why in the latino indexer the movie titles is Avengers :Era de ultron and in spanish is Vengadores: Era de Ultron

i don´t know how Radarr send the name ( i think is sended in English) but in the Jackett search doesn´t find the movie title in english and find it in spanish and Latino

but if i search in the Tracker Site (https://www.cinecalidad.is/?s=Avengers%3A+Age+of+Ultron) finds it in the 3 languages.

if you need Testers Count me on

**Comment by diegargon** [comment]
oh ok now understand and see the problem.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/blob/dda5549e209a17506eecfec0574472e2f3ee6320/src/Jackett.Common/Indexers/Cinecalidad.cs#L175-L177
As far as I can tell the issue is that the result's title doesn't match the search term, and so is rejected by Jackett. The indexer is written in C# which is outside of my knowledgebase, so I've asked someone else to have a look when they're free.

**Comment by coldiak** [comment]
Thanks!!

**Comment by ngosang** [comment]
As @ilike2burnthing has found, I'm removing the results that don't contain the search terms. That is to avoid unrelated results.
For example, if you search "avengers" in the site, you get 4 avengers films and one unrelated SpiderMan film.
I can't fix both issues and I prefer to return more acurate results. Try to search other terms like "soul" in the website and you will realize why I'm removing results.
Sonarr/Radarr make several searches with the tile in english and spanish. It could fail for some movies but it's working well most of the time.

**Comment by coldiak** [comment]
yes, it works well, just saying that jackett doesn´t find the movie when the search is in english but when you search on the website it does, with all the words, if i try Avengers Age of Ultron on the jackett search  no results but in the website 1 result and if o try Avengers Era de ultron on jackett 1 result and in the website 1 result but the radarr search is in english.

**Comment by Dark-Yox** [comment]
The tracker is down. I wonder if it's dead.

**Comment by garfield69** [comment]
yes, or maybe they changed domain, but without an auto-redirect we don't know what it is until someone in the know provides it.

**Comment by coldiak** [comment]
> yes, or maybe they changed domain, but without an auto-redirect we don't know what it is until someone in the know provides it.

they changed to https://www.cinecalidad.im/

**Comment by ilike2burnthing** [comment]
Pretty sure that's just an out of date, unofficial proxy - https://github.com/Jackett/Jackett/issues/6081#issuecomment-816307547

**Comment by manolodf** [comment]
> Pretty sure that's just an out of date, unofficial proxy - [#6081 (comment)](https://github.com/Jackett/Jackett/issues/6081#issuecomment-816307547)

It does seem out of date.  I posted it I think erroneously on another thread for the Spanish Version of the indexer. 
But it seems that cine-calidad.com is an updated indexer, although perhaps its a clone or a restore of an older backup they had since it uses the path /protect/v.php instead of /protect/v2.php so the download fails currently even if you manually enter the url, although the search succeeds.

**Comment by ngosang** [comment]
#12676
