### ISSUE TITLE
[BUG] Speed.cd Stopped Working

### ISSUE THREAD

**Issue by AlphaLink4** [Jackett/Jackett#1089]
Speed.cd appears to have stopped working.  The logon PHP file being referenced appears to have removed (or changed) according to the following error upon adding the tracker:

File Not Found No page exists at your destination address, http://speed.cd/takeElogin.php but the Speed.cd home page should help you to find what you need. Return to Speed.cd Home Page

After doing a bit of digging, I believe the working page is at the following page: https://speed.cd/take_login.php

Attached is my detailed log:
[log.txt](https://github.com/Jackett/Jackett/files/788920/log.txt)

**Comment by kaso17** [comment]
changed the url with 04844d6cb2afb7a14499d6dfaaeb29f6fb113a4c
Not sure if there are more errors to come.
I've no account at SpeedCD, do you have an invite available? It's missing a few features too.

**Comment by armani316** [comment]
@kaso17 Is an invite still required?

**Comment by kaso17** [comment]
just got one. I can confirm after changing the URL it's working again. Make sure you're using version v0.7.1072.
