### ISSUE TITLE
[REQ] Beyond-HD new API

### ISSUE THREAD

**Issue by ende124** [Jackett/Jackett#10898]
Beyond-HD has released a proper API for searching torrents.
Using this seems more robust and practical than todays yaml config file.

Documentation is on their forums: https://beyond-hd.me/forums/topic/torrents-api-overview-beyondhd.3721

**Comment by ilike2burnthing** [comment]
Is there any public documentation?

**Comment by ende124** [comment]
Not that I am aware of.
I could make a copy of it if needed.

**Comment by ilike2burnthing** [comment]
You may need to ask permission from the site admins, or see if they can make a copy available to us/public.

**Comment by BrianVia** [comment]
@ilike2burnthing I've attached a copy of the API docs from the forum.  Admin were happy to see the API used. 
[BeyondHD_API.pdf](https://github.com/Jackett/Jackett/files/6070128/BeyondHD_API.pdf)

**Comment by ilike2burnthing** [comment]
Thanks Brian. It will need a C# volunteer with access, as none of the maintainers have an account.

@seeyabye / @XYZJR / @dm3ch don't suppose any of you have an account and would be able to try this?

**Comment by dm3ch** [comment]
@ilike2burnthing I haven't got account on this site and as far as I can see it requires invitation.

**Comment by zepx** [comment]
@ilike2burnthing sorry, but I don't have an account either.

**Comment by seeyabye** [comment]
@ilike2burnthing sorry, I don't have an account.

**Comment by XYZJR** [comment]
Unfortunately, that's 3 for 3. If we can get an invite, I'd love to help.

**Comment by ilike2burnthing** [comment]
Thanks all. I've added a request for help in the issue above.

**Comment by 0wnageRufer** [comment]
I guess I can help. I have an account and programming experience. I am not familiar with your code base, so I better test for you.

**Comment by ilike2burnthing** [comment]
[v0.17.1027](https://github.com/Jackett/Jackett/releases/tag/v0.17.1027)
