### ISSUE TITLE
Tracker renamed [Magico.fun] to [Trellas.info] 

### ISSUE THREAD

**Issue by vlevas** [Jackett/Jackett#10893]
Jackett: Jackett Version v0.17.337

Please the tracker change his name/domain from magico.fun to trellas.info can we update the tracker ?

Thanks a lot !

**Comment by ilike2burnthing** [comment]
https://magico.fun/ still loads for me, but with a 'work in progress' note.

Is https://trellas.info/ a temporary site while work is done, or are they moving there permanently?

In Jackett, open the configuration panel for Magico (click the spanner button), change the `Site Link` to https://trellas.info/, click `Okay`, and let me know if it logs in fine and you're able to search and download with it.

**Comment by vlevas** [comment]
hello thanks for the fast reply.. they will move permantly to trellas.info 1-2 days they let magico.fun to redirect to trellas.info..

yes i can try it when you change the url to see if it works.. as they say that will be the same but other domain.

Thanks.

**Comment by ilike2burnthing** [comment]
Thanks. I'll change the URL.

Is the name changing to Trellas or is it still Magico?

**Comment by vlevas** [comment]
as i know tracker just change their name full... to trellas.info

**Comment by ilike2burnthing** [comment]
Will be changed in the next release (~1 hour)

**Comment by ilike2burnthing** [comment]
[v0.17.343](https://github.com/Jackett/Jackett/releases/tag/v0.17.343)
