### ISSUE TITLE
[hdtorrents] The SSL connection could not be established, see inner exception.: Authentication failed, see inner exception. (Config)

### ISSUE THREAD

**Issue by MCT80** [Jackett/Jackett#10901]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Unraid Version: 6.9.0-rc2

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.348

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** No

### Description

Jackett on unraid docker has SSL errors for most private trackers I add.
Jackett in Windows works fine as a test, but that is of no use to me as I need it running on unraid

### Logged Error Messages

This appears in log after trying to add HD-Torrents

https://jpst.it/2oQhr

### Screenshots

![jackett-error](https://user-images.githubusercontent.com/49670915/105571326-3e3a6980-5da3-11eb-8ec8-fc765713ae8f.PNG)

**Comment by ilike2burnthing** [comment]
Not the same error, but see if the troubleshooting steps help here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#authentication-failed-because-the-remote-party-has-closed-the-transport-stream

**Comment by MCT80** [comment]
> Not the same error, but see if the troubleshooting steps help here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#authentication-failed-because-the-remote-party-has-closed-the-transport-stream
> 
> If you're behind a reverse proxy, try just using the IP and port instead as a test.

Thanks. I'm not behind a reverse proxy or any vpn.
It will authenticate just fine using jackett on windows PC (same jacket version), but just won't on unraid. I can't see anything in those topics which I can change in unraid. It's odd.

Leads me to believe it's an unraid issue, but I'm having no luck chasing that.

**Comment by ilike2burnthing** [comment]
What are the 4 trackers, and which one is working?

**Comment by ilike2burnthing** [comment]
DNS can be set per container, in case you want to try using Google (8.8.8.8 and 8.8.4.4) or Cloudflare (1.1.1.1 and 1.0.0.1) servers.

**Comment by MCT80** [comment]
Tasmanites is working
HD-torrents, rutracker and HDBITS are not. I haven’t really persisted with HDBITS as I’m not really interested in having that one in jackett.

I’ll try some different DNS’s thanks



________________________________

**Comment by MCT80** [comment]
Changing DNS to cloudflare got it! Thank you!



________________________________
