### ISSUE TITLE
Indexer returning results for other series 

### ISSUE THREAD

**Issue by jpichie** [Jackett/Jackett#1091]
Hello,
I am using the latest sonarr, jackett 0.7.1043 (used for torrentday) and jacket pubic 0.6.45.2 for TPB.
This setup has been working for a while now, and is technically still working as it is correctly pulling shows on a nightly basis.
The issue though is when I do a manual search from within sonarr, it is returning results for tons of other shows for the same season and episode.
IE - bones S12E07 also returns many other shows with a Season 12 and Episode 7 (see attached).
This issue started late last week, around Feb 16th.
![indexerissue](https://cloud.githubusercontent.com/assets/22221256/23176038/6e26a1b4-f82f-11e6-8682-89c39a491355.jpg)
[log.txt](https://github.com/Jackett/Jackett/files/790889/log.txt)

**Comment by jpichie** [comment]
This can be closed, looks like the issue was on sonarr's end.
auto updated to version 2.0.0.4613 last night and issue has been resolved.

**Comment by kaso17** [comment]
Yes, in your log sonarr didn't include the series title (only the season/episode.
Btw. the official Jackett version supports public trackers again Jackett-Public isn't needed anymore.
