### ISSUE TITLE
Filelist.ro - Manual search returning no results

### ISSUE THREAD

**Issue by speknet** [Jackett/Jackett#1092]
Filelist.ro returning no results on manual search, however when looking at the debug log there are clearly results in there so it could be an issue with the parsing.
Can someone else check if they have the same issue?

[filelist_log.txt](https://github.com/Jackett/Jackett/files/791361/filelist_log.txt)

**Comment by kaso17** [comment]
They changed something a few days ago. 
Please make sure you're running jackett v0.7.1072

**Comment by abpostelnicu** [comment]
I think there could be the same issue here: https://github.com/Jackett/Jackett/issues/1094

**Comment by speknet** [comment]
Is jackett v0.7.1072 fixing these issues?

**Comment by abpostelnicu** [comment]
I'm trying to update to the latest version, but it seems that also the auto-update is broken, or is something wrong with it. I'll come back with more details shortly.

**Comment by abpostelnicu** [comment]
I an confirm that the latest version works!

**Comment by speknet** [comment]
How did you make the auto update work?

**Comment by kaso17** [comment]
Yes v0.7.1072 should fix it. The version isn't a regular release yet, you've to enable the pre-release update checkbox in jackett to automatically update.
