### ISSUE TITLE
[speedcd] Exception of type 'System.Exception' was thrown. (Config)

### ISSUE THREAD

**Issue by ciasis** [Jackett/Jackett#10924]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu 16.04.7 LTS (I'm with SeedHost)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.17.354

**Last Working Jackett Version**: 0.17.354

**Are you using a proxy or VPN?** [yes/no] no

### Description

I wanted to add my Speed.cd account to my tracker list, put in my username and password but got this error message.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![speed](https://user-images.githubusercontent.com/50784424/105715438-e6743d80-5f1d-11eb-8a91-355ffb5c19a2.JPG)

**Comment by ilike2burnthing** [comment]
Working ok here.

Please provide an **enhanced** log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by ciasis** [comment]
Here are the logs: 
[speedcd.txt](https://github.com/Jackett/Jackett/files/5873430/speedcd.txt)

**Comment by ilike2burnthing** [comment]
Please don't trim your logs, just redact anything sensitive. I need to see from the point you click `Okay` to when the error appears on screen.

**Comment by ciasis** [comment]
Sorry for the late reply. I reinstalled Jackett, ticked _enhanced logs_, tried to add _speed.cd_ and _st-tracker.eu_, and cleaned the log file by redacting personal information. Hope this helps.

[log.txt](https://github.com/Jackett/Jackett/files/5903770/log.txt)

**Comment by ilike2burnthing** [comment]
Your username and password are visible in the file, so you'll want to change your password anyway, but try something much simpler (~8 English alphanumeric characters). If that works, you know the password is the problem and can go from there (making it longer and more complex, but avoiding special characters).

You should also check the security tab for your profile on speed.cd to make sure there's nothing enabled which would cause issues.

**Comment by ciasis** [comment]
Thank you for answering. I just changed the password to a less complex one and adding the tracker to Jackett succeeded.
