### ISSUE TITLE
[polishtracker] New categories not recognized

### ISSUE THREAD

**Issue by chaostheory22** [Jackett/Jackett#10927]
There's new category on Polishtracker that is not recognized by Jackett: TV UHD. 

This is probably connected to new Reaper Engine: 

> In the new version o‌﻿​﻿​﻿​﻿‌﻿‌﻿​﻿​﻿‍﻿‌﻿​﻿​﻿‌﻿​﻿‌﻿‌﻿‌﻿‍﻿‌﻿​﻿​﻿​﻿​﻿‌﻿‌﻿‌﻿‍﻿‌﻿​﻿​﻿‌﻿​﻿‌﻿‌﻿‌﻿‍﻿‌﻿‌﻿​﻿​﻿‌﻿‌﻿‌﻿‌﻿‍﻿‌﻿‌﻿​﻿​﻿‌﻿‌﻿‌﻿​f the engine, 3 new categories have been added: TV-UHD, Audiobook and MusicVideo. (by KoKoo). Matching torrents will be gradually moved to these new categories.
> From now on, Ebooks and audiobooks will receive descriptions together with their covers in the same convention as for movies and series. (by Anirion1)

![image](https://user-images.githubusercontent.com/35978420/105739492-72935e80-5f38-11eb-89da-d312234919ec.png)

**Comment by ilike2burnthing** [comment]
Please provide an HTML dump of the search page - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by chaostheory22** [comment]
[PolishTracker-expanse.txt](https://github.com/Jackett/Jackett/files/5868606/PolishTracker-expanse.txt)

**Comment by ilike2burnthing** [comment]
Thanks. Unfortunately that didn't have all the information I needed (or I'm blind, definitely possible).

If you search by category on the site the URL should have `cat[]=11` (TV HD). I need to know what the category values are for TV-UHD, Audiobook and MusicVideo.

**Comment by chaostheory22** [comment]
TV-UHD is 14.
Audiobook is 15.
Music Video is 2.

**Comment by ilike2burnthing** [comment]
Thanks! I'll make those changes. Fix will be out in the next release (~4hrs).

**Comment by ilike2burnthing** [comment]
Oh, sorry, last question. Is cat 2 styled as `Music Video` or `MusicVideo`? In other words, space or no space?

**Comment by chaostheory22** [comment]
It's "Music video".

**Comment by ilike2burnthing** [comment]
[v0.17.370](https://github.com/Jackett/Jackett/releases/tag/v0.17.370) - if there any issues let me know
