### ISSUE TITLE
[ilcorsaronero] new domain

### ISSUE THREAD

**Issue by bGr3m** [Jackett/Jackett#10926]
Jackett Version v0.17.354 

i report that italian public torrent site _"Il Corsaro Nero"_ changed its domain from **https://ilcorsaronero.link/** to **https://ilcorsaronero-it.cz/**

thank you for your work!

**Comment by ilike2burnthing** [comment]
This was previously mentioned here - https://github.com/Jackett/Jackett/issues/986#issuecomment-756713053

It appears to be a clone rather than a change of domain, there are many features missing from the site.

*.link is currently down

**Comment by shiner66** [comment]
Hello,
It seems to be reachable at ```https://www.ilcorsaronero.in/``` but Jackett isn't able to pull results from it, I can't understand why.
