### ISSUE TITLE
[speedtorrentreloaded] Login failed: No form found on https://st-tracker.eu/sessioncheck.php?session=1 using form selector form (Config)

### ISSUE THREAD

**Issue by ciasis** [Jackett/Jackett#10923]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu 16.04.7 LTS (I'm with SeedHost)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.17.354

**Last Working Jackett Version**: 0.17.354

**Are you using a proxy or VPN?** [yes/no] no

### Description

I wanted to add Speed-Torrent Reloaded to my list, put in my username and password, but got this error message.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![st](https://user-images.githubusercontent.com/50784424/105714027-1cb0bd80-5f1c-11eb-8223-17fad8805339.JPG)

**Comment by ilike2burnthing** [comment]
Please provide an **enhanced** log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by ciasis** [comment]
Here is the log: 
[st-tracker.txt](https://github.com/Jackett/Jackett/files/5873456/st-tracker.txt)

**Comment by ilike2burnthing** [comment]
Please don't trim your logs, just redact anything sensitive. I need to see from the point you click `Okay` to when the error appears on screen.

**Comment by ciasis** [comment]
Sorry for the late reply. I reinstalled Jackett, ticked _enhanced logs_, tried to add _speed.cd_ and _st-tracker.eu_, and cleaned the log file by redacting personal information. Hope this helps.

[log.txt](https://github.com/Jackett/Jackett/files/5903766/log.txt)

**Comment by ilike2burnthing** [comment]
When it tries to redirect to https://st-tracker.eu/login.php#tologin you get:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at musik.st-tracker.eu Port 443</address>
</body></html> 
```
Not sure why that is happening, as it's working here. It shouldn't have anything to do with password complexity, as it hasn't even been submitted at that point, though feel free to try changing it.

As a test, install Jackett on a local computer and try adding speedtorrentreloaded.

**Comment by ciasis** [comment]
Ok, this is weird: I changed my password to a less complex one, tried to add the tracker again, but it failed.
Fortunately, I have a second seedbox with SeedMonster (SM), so I made a fresh installation of Jackett on my SM box and was able to add speedtorrentreloaded to Jackett. But on SeedHost, I experience this error. Has this something to do with the vendor's servers?

**Comment by ilike2burnthing** [comment]
Sounds like it, yea, though I'm not sure what.

Ok to close this issue?

**Comment by ciasis** [comment]
Yeah, it's not a big deal with this tracker. Still weird, but yeah..  it's fine. Gonna close this issue.
