### ISSUE TITLE
[lemonhd] Login failed: No form found on https://lemonhd.org/login.php using form selector form[action=

### ISSUE THREAD

**Issue by finikium** [Jackett/Jackett#10939]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
I'm assuming they've either disabled the login page or are performing maintenance, because if you try to access the site at the moment, you get to play Fruit Ninja instead.

**Comment by finikium** [comment]
Thanks friend I'm going to play Ninja instead haha :) 
Its something about cookies but i could not  understand Chinese :( 
They had announced 2 weeks ago that there will bea new method for logging in the site
I Think that you'll find a solution
Many thanks
Greetings from Greece



    Στις Τρίτη, 26 Ιανουαρίου 2021, 11:45:27 π.μ. EET, ο χρήστης ilike2burnthing <notifications@github.com> έγραψε:  
 
 


I'm assuming they've either disabled the login page or are performing maintenance, because if you try to access the site at the moment, you get to play Fruit Ninja instead.

**Comment by ilike2burnthing** [comment]
@skygunner have they disabled the login page, or is there another way to access the site now?

**Comment by finikium** [comment]
Yes! Another way to access the site now.
You have to write the passkey:https://lemonhd.org/login.php?passkey=YOUR PASSKEY
Many thanks
   Στις Τρίτη, 26 Ιανουαρίου 2021, 12:20:10 μ.μ. EET, ο χρήστης ilike2burnthing <notifications@github.com> έγραψε:  
 
 


@skygunner have they disabled the login page, or is there another way to access the site now?

**Comment by ilike2burnthing** [comment]
Switched to using cookies to login. Will be available in the next release (~5hrs).

**Comment by finikium** [comment]
Great!
Many thanks :) 


    Στις Τρίτη, 26 Ιανουαρίου 2021, 9:02:17 μ.μ. EET, ο χρήστης ilike2burnthing <notifications@github.com> έγραψε:  
 
 


Switched to using cookies to login. Will be available in the next release (~5hrs).

**Comment by skygunner** [comment]
Due to the copyright issues happened recently in China, most of the Chinese PT sites went hiddening in the cave.
Most of them are based on NexusPHP. 
Many of them now use a temporary login url which will expires in minutes instead of the normal login.php or need some extra parameters for the request. 
Some can only login with the saved cookie. 
It is not a good idea to adopt Jackett for their temporary login meathods. 
But cookie method should always work. 
When it will go back to normal is unkown, maybe never. 
So if Jackett want to crack this problem, maybe support both login page and cookie, if one fails, try use the 2nd way.

**Comment by ilike2burnthing** [comment]
[v0.17.383](https://github.com/Jackett/Jackett/releases/tag/v0.17.383)

**Comment by tjxme** [comment]
> Switched to using cookies to login. Will be available in the next release (~5hrs).

they wont return results because they have changed their web category. 

caps:
  categorymappings:
    - {id: 300, cat: Movies/UHD, desc: "Movies UHD-4K"}
    - {id: 301, cat: Movies/UHD, desc: "Movies 2160p"}
    - {id: 420, cat: Movies/UHD, desc: "Movies 2160p REMUX"}
    - {id: 401, cat: Movies/BluRay, desc: "Movies Blu-ray"}
    - {id: 410, cat: Movies/HD, desc: "Movies 1080p"}
    - {id: 415, cat: Movies, desc: "Movies 1080p REMUX"}
    - {id: 416, cat: Movies/3D, desc: "Movies 3D"}
    - {id: 411, cat: Movies/HD, desc: "Movies 720p"}
    - {id: 412, cat: Movies/WEB-DL, desc: "Movies WEB-DL"}
    - {id: 413, cat: TV/HD, desc: "Movies HDTV"}
    - {id: 417, cat: Movies, desc: "Movies iPad"}
    - {id: 414, cat: Movies/DVD, desc: "Movies DVD"}
    - {id: 402, cat: TV, desc: "TV Series(电视剧)"}
    - {id: 403, cat: TV, desc: "TV Shows(综艺)"}
    - {id: 404, cat: TV/Documentary, desc: "Documentaries(纪录片)"}
    - {id: 405, cat: TV/Anime, desc: "Animations(动画片)"}
    - {id: 406, cat: Audio/Video, desc: "Music Videos(MV)"}
    - {id: 408, cat: Audio, desc: "HQ Audio(音乐)"}
    - {id: 500, cat: Audio, desc: "Music(无损)"}
    - {id: 409, cat: Other, desc: "Video Portray(写真视频)"}

  modes:
    search: [q]
    tv-search: [q, season, ep, imdbid]
    movie-search: [q, imdbid]
    music-search: [q]
    book-search: [q]

this one works for searching can you push into next release please???

**Comment by ilike2burnthing** [comment]
That's what is currently being used:
https://github.com/Jackett/Jackett/blob/70b14a375f1b749a20e642f972f44cfe59df93cd/src/Jackett.Common/Definitions/lemonhd.yml#L13-L41

**Comment by tjxme** [comment]
> That's what is currently being used:
> https://github.com/Jackett/Jackett/blob/70b14a375f1b749a20e642f972f44cfe59df93cd/src/Jackett.Common/Definitions/lemonhd.yml#L13-L41

no result showing 
01-28 22:00:20 Error CardigannIndexer (lemonhd): Error while parsing row '
then their whole website is published on my log

**Comment by tjxme** [comment]
sorry for your reference, a sample of their first website response

<td class="rowfollow nowrap" valign="middle" style='padding: 0px'><img class='cat_movie' src='pic/cattrans.gif' alt='' title='' style='background-image: url(pic/ico_20210201222.png);' /></td>
<td class="rowfollow" width="100%" align="left"><table class="torrentname" width="100%"><tr><td class="embedded" style="padding-right: 40px;"><a href="details_movie.php?id=204968"><b>The Four Final Battle 2014 HKG BluRay 1080p x264 AC3 2Audios-CMCT</b></a> <img class="pro_free" src="pic/trans.gif" alt="Free" onmouseover="domTT_activate(this, event, 'content', '&lt;b&gt;&lt;font class=&quot;free&quot;&gt;Free&lt;/font&gt;&lt;/b&gt; will end in &lt;b&gt;&lt;span title=&quot;2021-01-31 10:06:37&quot;&gt;1 day 22 hours&lt;/span&gt;&lt;/b&gt;', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);" />&nbsp;( will end in <b><span title="2021-01-31 10:06:37">1 day 22 hours</span></b>)<br /><span class='tag tag_gy'>国语</span><span class='tag tag_yy'>粤语</span><span class='tag tag_zz'>中字</span>四大名捕大结局 (港版) | 导演: 陈嘉上/秦小珍 主演: 邓超 刘亦菲 郑中基 邹兆龙 国粤双语 国配/简繁中字</td><td class="embedded" style='width: 45px'><a href='https://movie.douban.com/subject/10604893/' target='_blank'><img style='display: inline-block;margin-bottom: -3px' src='/pic/icon-douban.png' height='16px' width='16px' alt=''> 5.0</a></td><td class="embedded" style='width: 45px'><a href='https://www.imdb.com/title/tt3919278/' target='_blank'><img style='display: inline-block;margin-bottom: -3px' src='/pic/icon-imdb.png' height='16px' width='16px' alt=''> 5.6</a></td><td width="20" class="embedded" style="text-align: right; " valign="middle"><a href="download.php?https=1&id=204968"><img class="download" src="pic/trans.gif" style='padding-bottom: 2px;' alt="download" title="Download&nbsp;Torrent" /></a><br /><a id="bookmark1" href="javascript: bookmark(204968,1);"><img class="delbookmark" src="pic/trans.gif" alt="Unbookmarked" title="Bookmark" /></a></td>
</tr></table></td><td class="rowfollow nowrap"><a href="details_movie.php?id=204968#startcomments" title="Add&nbsp;comment">0</a></td><td class="rowfollow nowrap"><span title="2021-01-29 10:06:37">1 hour<br />3 mins</span></td><td class="rowfollow">9.01<br />GB</td><td class="rowfollow" align="center"><b><a href="details_movie.php?id=204968&amp;hit=1&amp;dllist=1#seeders"><font color="#ee0000">1</font></a></b></td>
<td class="rowfollow"><b><a href="details_movie.php?id=204968&amp;hit=1&amp;dllist=1#leechers">39</a></b></td>
<td class="rowfollow">0</td>
<td class="rowfollow "><b> -- </b></td>
<td class="rowfollow"><i>Anonymous</i></td>

**Comment by tjxme** [comment]
"<td class="rowfollow nowrap" valign="middle" style='padding: 0px'><img class='cat_movie' src='pic/cattrans.gif' alt='' title='' style='background-image: url(pic/ico_20210201222.png);' /></td>
<td class="rowfollow" width="100%" align="left"><table class="torrentname" width="100%"><tr><td class="embedded" style="padding-right: 40px;"><a href="details_movie.php?id=204968"><b>The Four Final Battle 2014 HKG BluRay 1080p x264 AC3 2Audios-CMCT</b></a> <img class="pro_free" src="pic/trans.gif" alt="Free" onmouseover="domTT_activate(this, event, 'content', '&lt;b&gt;&lt;font class=&quot;free&quot;&gt;Free&lt;/font&gt;&lt;/b&gt; will end in &lt;b&gt;&lt;span title=&quot;2021-01-31 10:06:37&quot;&gt;1 day 22 hours&lt;/span&gt;&lt;/b&gt;', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);" />&nbsp;( will end in <b><span title="2021-01-31 10:06:37">1 day 22 hours</span></b>)<br /><span class='tag tag_gy'>国语</span><span class='tag tag_yy'>粤语</span><span class='tag tag_zz'>中字</span>四大名捕大结局 (港版) | 导演: 陈嘉上/秦小珍 主演: 邓超 刘亦菲 郑中基 邹兆龙 国粤双语 国配/简繁中字</td><td class="embedded" style='width: 45px'><a href='https://movie.douban.com/subject/10604893/' target='_blank'><img style='display: inline-block;margin-bottom: -3px' src='/pic/icon-douban.png' height='16px' width='16px' alt=''> 5.0</a></td><td class="embedded" style='width: 45px'><a href='https://www.imdb.com/title/tt3919278/' target='_blank'><img style='display: inline-block;margin-bottom: -3px' src='/pic/icon-imdb.png' height='16px' width='16px' alt=''> 5.6</a></td><td width="20" class="embedded" style="text-align: right; " valign="middle"><a href="download.php?https=1&id=204968"><img class="download" src="pic/trans.gif" style='padding-bottom: 2px;' alt="download" title="Download&nbsp;Torrent" /></a><br /><a id="bookmark1" href="javascript: bookmark(204968,1);"><img class="delbookmark" src="pic/trans.gif" alt="Unbookmarked" title="Bookmark" /></a></td>
</tr></table></td><td class="rowfollow nowrap"><a href="details_movie.php?id=204968#startcomments" title="Add&nbsp;comment">0</a></td><td class="rowfollow nowrap"><span title="2021-01-29 10:06:37">1 hour<br />3 mins</span></td><td class="rowfollow">9.01<br />GB</td><td class="rowfollow" align="center"><b><a href="details_movie.php?id=204968&amp;hit=1&amp;dllist=1#seeders"><font color="#ee0000">1</font></a></b></td>
<td class="rowfollow"><b><a href="details_movie.php?id=204968&amp;hit=1&amp;dllist=1#leechers">39</a></b></td>
<td class="rowfollow">0</td>
<td class="rowfollow "><b> -- </b></td>
<td class="rowfollow"><i>Anonymous</i></td>"

**Comment by tjxme** [comment]
> That's what is currently being used:
> https://github.com/Jackett/Jackett/blob/70b14a375f1b749a20e642f972f44cfe59df93cd/src/Jackett.Common/Definitions/lemonhd.yml#L13-L41

this is the typical error, seems like the crawler is not working properly

System.Exception: Error while parsing field=category, selector=a[href*="?cat_"], value=<null>: Selector "a[href*="?cat_"]" didn't match 
<tr>
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<img class="cat_tv" src="pic/cattrans.gif" alt="" title="" style="background-image: url(pic/ico_20210201222.png);">
	</td>
	<td class="rowfollow" width="100%" align="left">
		<table class="torrentname" width="100%">
			<tbody>
				<tr>
					<td class="embedded" style="padding-right: 40px;">
						<a href="details_tv.php?id=204865">
							<b>CCTVHD Ganga 2007 Complete HDTV 720p x264 AC3-CMCT</b>
						</a>
						<img class="pro_free" src="pic/trans.gif" alt="Free" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;free&quot;>Free</font></b> will end in <b><span title=&quot;2021-01-30 17:32:47&quot;>1 day 5 hours</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);">&nbsp;( will end in
						<b>
							<span title="2021-01-30 17:32:47">1 day 5 hours</span>
						</b>)<img class="check check_ok" alt="Check Ok!" title="Check Ok!" src="pic/trans.gif">
						<br>
						<span class="tag tag_gy">国语</span>
						<span class="tag tag_zz">中字</span>央视高清：恒河 全3集 BBC 出品 国语中字</td>
					<td class="embedded" style="width: 45px">
						<a href="https://www.imdb.com/title/tt1307922/" target="_blank">
							<img style="display: inline-block;margin-bottom: -3px" src="/pic/icon-imdb.png" height="16px" width="16px" alt="">
							7.9</a>
					</td>
					<td width="20" class="embedded" style="text-align: right; " valign="middle">
						<a href="download.php?https=1&amp;id=204865">
							<img class="download" src="pic/trans.gif" style="padding-bottom: 2px;" alt="download" title="Download&nbsp;Torrent">
						</a>
						<br>
						<a id="bookmark99" href="javascript: bookmark(204865,99);">
							<img class="delbookmark" src="pic/trans.gif" alt="Unbookmarked" title="Bookmark">
						</a>
					</td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow nowrap">
		<a href="details_tv.php?id=204865#startcomments" title="Add&nbsp;comment">0</a>
	</td>
	<td class="rowfollow nowrap">
		<span title="2021-01-28 17:32:47">18 hours<br>0 min</span>
	</td>
	<td class="rowfollow">3.60<br>GB</td>
	<td class="rowfollow" align="center">
		<b>
			<a href="details_tv.php?id=204865&amp;hit=1&amp;dllist=1#seeders">18</a>
		</b>
	</td>
	<td class="rowfollow">0</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=204865">
			<b>28</b>
		</a>
	</td>
	<td class="rowfollow ">
		<b>
			--
		</b>
	</td>
	<td class="rowfollow">
		<i>Anonymous</i>
	</td>
</tr>
