### ISSUE TITLE
[dmhy] Exception (dmhy): FlareSolverr was unable to process the request

### ISSUE THREAD

**Issue by plsharevme** [Jackett/Jackett#10937]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

open media vault , docker jackett version v0.17.354
FlareSolverr v1.2.3 

### Description

before that i using dmhy with no problem , but this 2 day have this error message when testing ping 
 An error occurred while testing this indexer
Exception (dmhy): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: Error: net::ERR_CONNECTION_REFUSED at https://share.dmhy.org/topics/list?keyword=&sort_id=0&order=date-desc&team_id=0: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: Error: net::ERR_CONNECTION_REFUSED at https://share.dmhy.org/topics/list?keyword=&sort_id=0&order=date-desc&team_id=0
Click here to open an issue on GitHub for this indexer.

Thanks .

**Comment by ilike2burnthing** [comment]
Can you access dmhy from the same device and IP? Do you get a captcha challenge? I take it you're not using a VPN or proxy?

Not the same error, but try the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#authentication-failed-because-the-remote-party-has-closed-the-transport-stream

**Comment by plsharevme** [comment]
i can surf https://share.dmhy.org/ with no problem, and i no get any captcha challenge, ...yup  i no using any proxy and vpn.

**Comment by plsharevme** [comment]
i followed all the step from the link you give me, but seem i can access https://share.dmhy.org/ with no problem using browser.

anyway thanks for your reply.

**Comment by ilike2burnthing** [comment]
Please post the enhanced logs of your issue:
- https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket
and
- https://github.com/FlareSolverr/FlareSolverr#environment-variables
