### ISSUE TITLE
[AniDex] does not filter by lang_id

### ISSUE THREAD

**Issue by XCDX** [Jackett/Jackett#10930]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: .Net-Framework

**.Net Version**: 5

**Jackett Version**: v0.17.354

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

Everything works correctly, but it doesn't filter correctly by lang_id placed in the indexer configuration.

### Screenshots

- Config

![vivaldi_tfDUO6Y445](https://user-images.githubusercontent.com/310351/105772509-e416e100-5f27-11eb-9fb2-bb68faf3055f.png)

- Search

![vivaldi_N5kNCgrRXo](https://user-images.githubusercontent.com/310351/105772310-9a2dfb00-5f27-11eb-9bc8-a022fd8e124c.png)

- AniDex search

![vivaldi_x0yDaFOmV4](https://user-images.githubusercontent.com/310351/105772408-ba5dba00-5f27-11eb-9d9f-b5d21a546af0.png)

**Comment by ilike2burnthing** [comment]
[v0.17.370](https://github.com/Jackett/Jackett/releases/tag/v0.17.370)
