### ISSUE TITLE
Is there a way to use custom feeds from jackett with an rss aggregator, not torrent client?

### ISSUE THREAD

**Issue by googleitffs** [Jackett/Jackett#10936]
Sorry if it's not the appropriate place to ask, but I don't know where else to go. I want to use Jackett with my rss aggregator (Feedly) to not download but to see the links to webpages in the feed, but it doesn't work. Is there a way to do so?

**Comment by ilike2burnthing** [comment]
When you say it doesn't work, what have you tried to do?

I'll see if I can get it to work myself, but it would be useful to know what it is you're doing.

**Comment by googleitffs** [comment]
> When you say it doesn't work, what have you tried to do?
> 
> I'll see if I can get it to work myself, but it would be useful to know what it is you're doing.

I tried to paste the link of the rss-feed to Feedly and it doesn't recognize it.

**Comment by ilike2burnthing** [comment]
Well I just tried QuiteRSS, clicked the `Copy RSS Feed` button for the indexer I wanted, pasted it into QuiteRSS as new feed, and it worked straight away. So yea, it should work unless there's something particularly different about Feedly.

**Comment by ilike2burnthing** [comment]
Just tested with Feedly (didn't realise it was purely a website). So long as you enable `External access` in Jackett's settings, and you're using a reverse proxy or your public IP address, it works.

**Comment by googleitffs** [comment]
> Just tested with Feedly (didn't realise it was purely a website). So long as you enable `External access` in Jackett's settings, and you're using a reverse proxy or your public IP address, it works.

I don't have a public IP address, so that's probably why it doesn't work for me :(.

**Comment by ilike2burnthing** [comment]
https://api.ipify.org/ - your public IP address

Replace 127.0.0.1 or 192.168.*.* or whatever else Jackett currently uses with that instead.

**Comment by googleitffs** [comment]
> https://api.ipify.org/ - your public IP address
> 
> Replace 127.0.0.1 or 192.168... or whatever else Jackett currently uses with that instead.

Still, doesn't work.

**Comment by ilike2burnthing** [comment]
You've enabled `External access` in Jackett's settings and are using a link which fits this format?
`http://123.45.67.890:9117/api/v2.0/indexers/1337x/results/torznab/api?apikey=APIKEY&t=search&cat=&q=`

**Comment by googleitffs** [comment]
> You've enabled `External access` in Jackett's settings and are using a link which fits this format?
> `http://123.45.67.890:9117/api/v2.0/indexers/1337x/results/torznab/api?apikey=APIKEY&t=search&cat=&q=`

Yes, even the same tracker. Feedly can't find the feed and says this: "We were not able to find an RSS feed for http://..."

**Comment by ilike2burnthing** [comment]
Have a look at port-forwarding, as well as your router and software firewall.

I'm not sure what else could be the issue, so I'll leave this open in case anyone else has a better idea.
