### ISSUE TITLE
[New Tracker REQ] ShowRSS

### ISSUE THREAD

**Issue by TimoVerbrugghe** [Jackett/Jackett#1093]
Indexer Name
ShowRSS

Type
TV

Indexer URL
http://showrss.info/

Indexer Language
English

Invite
Free registration

Note
ShowRSS used to be in the earlier versions of Jackett, up until public trackers where removed. The old source code is still available in the repository of Zone177x (https://github.com/zone117x/Jackett/blob/master/src/Jackett/Indexers/ShowRSS.cs).

**Comment by kaso17** [comment]
Not sure what's the point of the old implementation It just proxies their feed, it doesn't support searching.
I'll re-add it soon.

**Comment by kaso17** [comment]
re-added with d6fd4be73db959037890526ab9076ee2895e2fca
It's still a little pointless for me, even if we would fetch the correct feed for a TV show it seems to only include the most recent episodes (no old season packs or similar).

**Comment by TimoVerbrugghe** [comment]
Yeah, I mostly use it for daily talk shows, that appear to be showing up first through this feed in comparison with other trackers.

**Comment by epheterson** [comment]
Is this in the latest release (0.7.1090.0)? I have ShowRSS enabled but always get zero results.

**Comment by kaso17** [comment]
Are you searching for a specific show? That doesn't work. Otherwise please provide a log.

**Comment by epheterson** [comment]
Thanks, that's my issue. I'll disable search in Sonarr, I thought you could search.

**Comment by kaso17** [comment]
While it could try to fetch the corresponding show page and get the torrents from it. It's a little point less beacause of the very short history on ShowRSS.

**Comment by RoloSoze** [comment]
Looks like ShowRSS has now become a Semi-Private tracker. Registration is required, and this needs to be reflected in Jackett. Currently, there are no fields to add the username & password since it used to be a Public Tracker.

**Comment by kaso17** [comment]
this should be working (again) by now

**Comment by ilike2burnthing** [comment]
https://showrss.info/other/all.rss - The response ended prematurely: Error while copying content to a stream.

**Comment by ilike2burnthing** [comment]
back up
