### ISSUE TITLE
[Req] torrentz2eu

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#10959]
torrentzeu.org

![image](https://user-images.githubusercontent.com/19517680/106163485-ca8dc780-61bb-11eb-8c7f-45b84c648e6a.png)

**Comment by ilike2burnthing** [comment]
A very loose Indian clone of Torrentz2. If Torrentz2 finally dies, this is a possibility. Though their beta search seems to have abandoned any similarity to Torrentz2 other than the name.

**Comment by garfield69** [comment]
https://torrentz2eu.org/ presents a different looking page than https://torrentz2.unblockninja.com/
I'll take a look at the former and see if I can code a yaml indexer for it.

**Comment by garfield69** [comment]
Hah. and the beta page is back! I hope they are not going to be switching from one to the other regularly because that will be a pain in the ass.
original search path when I first looked at this an hour ago:
https://torrentz2eu.org/index.html?q=2021
current path for searches:
https://torrentzeu.org/kick.php?q=2021
https://torrentz2.unblockninja.com/data.php?q=2021

**Comment by garfield69** [comment]
bad news https://torrentz2eu.org/index.html?q=2021 generates results using JS, this would require a C# indexer to process.
good news: https://torrentzeu.org/kick.php?q=2021 generates full HTML results, I'll try code a yaml indexer for this.

**Comment by garfield69** [comment]
#$@! back to index.html again which we can't yaml for.
fine. I'll switch to using the proxy only, at least that seems to be constant.

**Comment by garfield69** [comment]
#$@! cloudflare is on the proxy for me, and flaresolverr is hitting maxTimeout
I'll load it as a PR and ask for volunteers to test

**Comment by garfield69** [comment]
https://torrentzeu.org/kick.php?q=rebels returning Curl error: Failed to connect to 65.108.89.61 port 3005: Connection refused

**Comment by garfield69** [comment]
https://torrentz2.pics/data.php?q=2022 returns
```
Curl error: Failed to connect to 65.108.89.61 port 3005: Connection refused
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://torrentz2.pics/ returns 
`Curl error: Failed to connect to 65.108.89.61 port 3005: Connection refused`
when searching

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://torrentz2.pics/data.php?q=alien returns `Curl error: Failed to connect to 65.108.89.61 port 3005: Connection refused`

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://torrentz2.pics/data.php?q=mandalorian returns
```
Sorry, unfortunately no torrent is available Here.
Try our [Beta Search](https://torrentz2.pics/beta1). You can find 100% results!
```
however, using https://torrentz2.pics/beta1 returns 404 not found

**Comment by garfield69** [comment]
this works
https://torrentz2.pics/beta2/search.php?torrent-query=mankind
will wait to see if this becomes the new engine before committing to updating the indexer for the new layout

**Comment by garfield69** [comment]
v0.20.2280

**Comment by garfield69** [comment]
https://torrentz2.pics/ returns 500 Internal Server Error

**Comment by garfield69** [comment]
https://2torrentz2eu.in/beta2/search.php?torrent-query=m3gan nothing found
https://2torrentz2eu.in/data.php?q=2023 Curl error: Connection timed out after 7000 milliseconds

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://2torrentz2eu.in/ 500 Internal Server Error
uptime 35 CP failed, 8 passed

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://torrentz2.nz/ cloudflare Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://torrentz2beta.asia/search.php?q=test Curl error: Failed to connect to 65.109.230.225 port 3002 after 0 ms: Connection refused

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
only applies to 2023 keyword, other searches work fine. 
in addition to the new domain the indexer paths need updating.
but given .today.year is being blocked I don't see the point of updating, we should probably just delete.

**Comment by ilike2burnthing** [comment]
https://www.torrentz2beta.pro/search.php?q=+ seems to work if you want to try that

**Comment by garfield69** [comment]
https://www.torrentz2beta.pro/ Error GatewayTimeout

**Comment by garfield69** [comment]
v0.21.1344

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/10959#issuecomment-1849021170

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
browser https://torrentz2beta.in/beta/search.php?q=%2B Curl error: Failed connect to 65.109.230.225:3002; Connection refused
jackett https://torrentz2beta.in/search.php?q=%2B Curl error: Failed connect to 65.109.230.225:3002; Connection refused

**Comment by garfield69** [comment]
v0.21.1730
