### ISSUE TITLE
nCore tracker URL change

### ISSUE THREAD

**Issue by colethegamer123** [Jackett/Jackett#10957]
Dear Devs,

nCore hungarian tracker changed host, the url was changed from

ncore.cc to ncore.pro

Please refresh it. Thank you!

**Comment by colethegamer123** [comment]
Workaround for users until waiting next release:

Go to jackett/config/Jackett/Indexers
Vim ncore.json
Change Sitelink Value to this: "value": "https://ncore.pro/"

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/10956
