### ISSUE TITLE
Running as system user with no /home/jackett directory (Systemd w/ Helper Script)

### ISSUE THREAD

**Issue by bakerboy448** [Jackett/Jackett#10953]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment
Agnostic - Linux

### Description

The current readme instructions do not work when using the systemd file with the helper script.

```
home directory
If you want to run it with a user without a /home directory you need to add Environment=XDG_CONFIG_HOME=/path/to/folder to your systemd file, this folder will be used to store your config files.
```

Does seem to apply/work

### Logged Error Messages

No logs related to jackett even attempting to use that; just a normal boot

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

None apply

**Comment by ilike2burnthing** [comment]
Download and unzip [testindexer.zip](https://github.com/Jackett/Jackett/files/5882838/testindexer.zip), place testindexer.yml in the subfolder `/cardigan/definitions/` of your set path (you may need to create those folders), re/start Jackett, and check if `TEST INDEXER` is available to be added in Jackett (`testindexer` should also be in your logs).

**Comment by bakerboy448** [comment]
well looks like the initial issue may have been permissions, as per logs the redir did work.

BUT it did not pick up test indexer

https://pastebin.com/KVPLFByz

**Comment by ilike2burnthing** [comment]
I've never used the xdg folder before, just the equivalent of your `/data/media/.config/Jackett_Test/cardigann/definitions/` (feel free to try that one out). I'll see if I can figure out how to get it to work (mostly out of curiosity), but if Jackett is now working for you (?) then it shouldn't be necessary.

**Comment by ilike2burnthing** [comment]
I'm using Docker, so this will need a little translation, but here are my relevant settings:
- `XDG_CONFIG_HOME` set to `/config`
- `/config` mapped to `/volume1/Docker/Jackett-test/config`

`testindexer.yml` placed in `/volume1/Docker/Jackett-test/config/cardigann/definitions/` (so from Jackett's point of view `/config/cardigann/definitions/`) works fine.

Apologies for the mix up, I think I saw xdg and focused in on that. You'll never need to use `/config/cardigann/definitions/` unless you want to test out new or modified indexers.

Anyway, if the permissions change solved your problem then you can close this issue.
