### ISSUE TITLE
XSpeeds results showing wrong categories & requires frequent reconfiguration

### ISSUE THREAD

**Issue by SWu** [Jackett/Jackett#1095]
Searching for movie names in XSpeeds returns all results as in the TV/SD category instead of their correct movie categories.

Jackett version:  0.7.1072.0
Mono version (if not using Windows):  4.6.2.7-8

**Comment by kaso17** [comment]
In the log you searched for "2016 1080p", with that search I'm getting the expected results (bluray and HD only releases).
Can you please provide a specific example of search string and incorrect result?
Please also include the surrounding lines of the log (not just the HTML dump).

**Comment by SWu** [comment]
That is the full log file.

Here's a screenshot showing another example, where every result is TV/SD category even though on the website they are all under BluRay.
![jackett_xspeeds](https://cloud.githubusercontent.com/assets/199065/23240801/757e7c5c-f93d-11e6-818a-2a4e1d356f4d.jpg)

**Comment by SWu** [comment]
Here's another log file from the above search. I turned on debug logging which is why there's the html dump.
[log.txt](https://github.com/Jackett/Jackett/files/795316/log.txt)

**Comment by armani316** [comment]
@kaso17 Aside from the categories, I believe XSpeeds has just made a change to their CloudFlare settings. It now requires reconfiguration every few hours.

**Comment by kaso17** [comment]
@SWu I'm getting proper category mappings when searching for Moana. But I'll have a look at the logs and try to reproduce it later.

CloudFlare shouldn't require a reconfigure. It's working fine for me.

**Comment by armani316** [comment]
Here's the error message I get.
[log.txt](https://github.com/Jackett/Jackett/files/797400/log.txt)

**Comment by SWu** [comment]
I also started getting errors with cloudflare, but removing and re-adding the account appears to have solved those issues at least for now. I'm still getting the bad categories when doing manual search. Note that RSS pulls the correct categories, it's just the manual search which returns all TV/SD.

**Comment by kaso17** [comment]
should be fixed with 3b3420086fa939c1de3a4c7a7fdf46220433dce8 (cloudflare issues) and 0408b7212636723d4337770d135fd641c88fb125 (category parsing)
