### ISSUE TITLE
[pleasuredome] Exception (pleasuredome): certificate validation failed.

### ISSUE THREAD

**Issue by 1ColdAssHonkey** [Jackett/Jackett#10988]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 7

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Framework

**.Net Version**: 4.8

**Jackett Version**: 0.17.401

**Last Working Jackett Version**: 0.17.401

**Are you using a proxy or VPN?** [yes/no] No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

Hello, I noticed that one of the changes on release 0.17.405 was ignoring an expired cert on sktorrent-org.
Pleasuredome seems to be throwing up a failed cert since the end of December.  Is there any way we could ignore this one too? 
**Thank you for writing such a FANTASTIC  program!**  

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

2021-01-31 14:54:11.8248 Error Jackett.Common.IndexerException: Exception (pleasuredome): certificate validation failed: [Subject]
  E=newuzer@pleasuredome.org.uk, CN=www.pleasuredome.org.uk, OU=Certificate Authority, O=Pleasuredome, S=Noord Holland, C=NL

[Issuer]
  E=newuzer@pleasuredome.org.uk, CN=Pleasuredome CA, OU=Certificate Authority, O=Pleasuredome, L=Amsterdam, S=Noord Holland, C=NL

[Serial Number]
  1C

[Not Before]
  12/30/2020 8:13:40 AM

[Not After]
  12/28/2030 8:13:40 AM

[Thumbprint]
  50BC58CBC5B822A879E14EF59BA8EC0B92F63F2B

 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Exception: certificate validation failed: [Subject]
  E=newuzer@pleasuredome.org.uk, CN=www.pleasuredome.org.uk, OU=Certificate Authority, O=Pleasuredome, S=Noord Holland, C=NL

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![Pleasuredome Error](https://user-images.githubusercontent.com/66453120/106401361-8f1c1480-63d8-11eb-9894-979dd5b73265.JPG)

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
[v0.17.437](https://github.com/Jackett/Jackett/releases/tag/v0.17.437)
