### ISSUE TITLE
Jackett stripping resolution and source data for AnimeTorrents

### ISSUE THREAD

**Issue by v3n** [Jackett/Jackett#1098]
`Jackett Version 0.7.1043.0`

This one is fairly reproducible simply by searching for anything on this tracker.

**Input From Tracker:**

`Some AnimeVid [HorribleSubs] [10-bit] [BRRip] [1080p]`

**Actual Output To TorNazb:** 

`Some AnimeVid [HorribleSubs]`

**Expected Output:**

`Some AnimeVid [HorribleSubs] [10-bit] [BRRip] [1080p]`

Seems like Jackett is truncating after the first [] block. This breaks most anything from this website and completely breaks Sonarr if you choose any quality profile but 'any'. This formatting is the standard for the website as well.

It looks like this website is possible formatting the title+sub source with a `<strong></strong>` block, breaking parsing of the `<a></a>` tag?

**Comment by kaso17** [comment]
it's working fine for me, can you please provide a specific example.

**Comment by kaso17** [comment]
never mind, confused it with AB.
fixed with cf1a6ff39d0f359114d27473db959ac8441a1756
