### ISSUE TITLE
[REQ] bigtower

### ISSUE THREAD

**Issue by memnos** [Jackett/Jackett#1099]
Hi all,
I'd like to know if there is the possibility to create a Jackett definition if you have a couchpotato searcher provider.
If yes is it possible to have some hints?
I'd like to have this provider https://github.com/neothematrix/bigtower-cp-provider in Jackett.

Tnx for your answers.

**Comment by kaso17** [comment]
The linked provider just scraps the HTML from the tracker website.
Jackett works in the same way.
From the code the tracker looks like a standard tracker. I suggest you look at the definition files in the Jackett Definition directory. You'll have to get the proper selectors. Have a look at the blubits or eotforum yml files, you probably can reuse most of the selectors.

**Comment by armani316** [comment]
@memnos Did @kaso17's reply answer your question?

**Comment by memnos** [comment]
I've just came home from mountains.
I'll try to follow what Kaso17 told. 
I hope i can do something?

**Comment by memnos** [comment]
I started to make some test creating new definition for the tracker.
I started from arabafenice definition that is quite similar, but it has little difference in columns.
I don't know how to set them in the definition.
Can someone give me a hint?

Here is the log when i test definition:
[log.txt](https://github.com/Jackett/Jackett/files/812977/log.txt)

**Comment by kaso17** [comment]
You're current problem is the download link:
Error while parsing field=download, selector=a[href^="index.php?page=downloadcheck&id="], value=<null>: Selector "a[href^="index.php?page=downloadcheck&id="]" didn't match

I couldn't find a DL link in the HTML output. If they don't show it in the search results you've two options:
Convert another link containing the torrent id (e.g. the details page link) to a download link using a replace filter. e.g. replace "page=torrent-details" with "page=torrent-download".

If the download link can't be build from the information available you've to use the toplevel download block for additional instructions. If you've set the download link to the details page in the search block Jackett will fetch that page and use the selector from the download block to fetch the actual download link. If you've to say thank you before being able to download the file use the before section of the download block (see arabfernice for an example).

**Comment by memnos** [comment]
From what i can see browsing through arabafenice and bigtower. Sites are almost equal.
Also download link. The only difference is the order and number of columns.
Can this cause the problem in download?
Are those columns setted in definition file?

**Comment by kaso17** [comment]
The download link selector doesn't care about columns.
It simply looks for a <a> tag with an href attribute starting with "index.php?page=downloadcheck&id=".
But based on the error from the log the search result rows simply don't contain a download link.

You probably have to construct it using filters or grab it from the details page.

Some other attributes are selected based on the column number, e.g. "td:nth-last-child(4)" essentially means "column 4"

**Comment by memnos** [comment]
I think i'm really not able to solve this.
Here is what i have in definition.
Any suggestion on what i can try to change?
Unfortunately i don't have an invitation to send, but i can give access with my account if someone wants to try to add this tracker.


[bigtower.txt](https://github.com/Jackett/Jackett/files/814206/bigtower.txt)

**Comment by memnos** [comment]
I'm sorry, i've got no invite, but if you tell me i can give you my account  credential to enter the site.
If you give me your mail i'll send to you.

**Comment by dpmdiego** [comment]
@memnos Could you send me an invitation to the Arabafenice? I would love to be a part of this community, but it is very difficult to find members ...
Thank you very much in advance if you can send me the invitation ...
imdiegodpm@gmail.com

**Comment by memnos** [comment]
@bonny1992 : as i see you are italian, if you want i can give you access to my account so that you can create definition.
You can use my account whenever you want with no problem. i have i very good ration :-)

**Comment by memnos** [comment]
Inscription are open 'till june the 30th.
So if anyone would like to add this tracker it can be make.

**Comment by bonny1992** [comment]
@memnos

Darn, sorry, I saw only now your tag =/
Sadly I don't have much time to try new definitions, but I will as soon as I will have some spare time.

**Comment by memnos** [comment]
@bonny1992 
I don't know if inscriptions are open at the moment.
In case i can give you access with my credentials?

**Comment by garfield69** [comment]
f7bf8fba40b6ec81561d4e196879f5d941f9ada1 via #3689 on 26 Aug 2018

**Comment by ilike2burnthing** [comment]
http://bigtower.info/ - ERR_CONNECTION_TIMED_OUT
