### ISSUE TITLE
[xBytessV2] Error with some category

### ISSUE THREAD

**Issue by RicardoVelaC** [Jackett/Jackett#10993]
### Environment

**OS**: [Docker LinuxServer Dev](https://registry.hub.docker.com/r/linuxserver/jackett/)

**Jackett Version**: Version v0.17.437

**Are you using a proxy or VPN?** NO

### Description

When search in xBytessV2 log shows some warn in categories
I checked the categories in Jackett's definition and it's everything OK except the last one marked after that comment:

`# internal cats not provided in search category dropdown !?! `
`# found by fishing`
`- {id: 19, cat: Movies/HD, desc: "Video - 720p"}`

I don't know if that is correct or we can delete this cat

### Logged Error Messages

`Warn | Some of the categories provided are unsupported in XbytesV2: 2080`

**Comment by ilike2burnthing** [comment]
`2080` is `Movies/WEB-DL` - https://github.com/Jackett/Jackett/wiki/Jackett-Categories

If you have tried to search using that category (e.g. with Radarr), it will give the error above because there is no `Movies/WEB-DL` category for that indexer:
https://github.com/Jackett/Jackett/blob/b1ea8c64e398f37d9af51804cf438589c89359d5/src/Jackett.Common/Definitions/xbytes2.yml#L13-L24

**Comment by RicardoVelaC** [comment]
Maybe we can consider _category 16_ like a WEB-DL because the big part of these are WEB-DL and all of them are MKV 4-6GB
`http://xbytesv2.li/index.php?page=torrents&category=16`

**Comment by ilike2burnthing** [comment]
If the MicroHD and M-UHD categories are majority WEB-DL then yeah. I don't have an account, so let me know.

**Comment by RicardoVelaC** [comment]
Yes all of them are MicroHD, I show here a little preview of the site: 

<img width="982" alt="cat-xbytes" src="https://user-images.githubusercontent.com/6016812/106576271-3ca83880-653d-11eb-932f-3da529e62144.png">

They have at least 3 MicroHD categories, for TV, Movies and 4k

If you can consider MicroHD like a Web-DL let me know and I propose the respective changes

**Comment by ilike2burnthing** [comment]
WEB-DL seems to be the minority there (at least from that screenshot), so it's best to leave the categories as they are. Just remove 2080 from your list of searched categories.
