### ISSUE TITLE
[bjshare] <!DOCTYPE html PUBLIC

### ISSUE THREAD

**Issue by NinguemLPJ** [Jackett/Jackett#10991]
### Environment

**OS**: Windows

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 5.0.102

**Jackett Version**: v0.17.437

**Are you using a proxy or VPN?** [no]

### Description

add new tracker (BJ-Share)

i'm not enabled to add any characters.

### Screenshots

https://imgur.com/Ud3XavW

**Comment by ilike2burnthing** [comment]
You don't have 2 factor authentication (2FA) enabled on your account?

If you sign into bjshare in a browser on the same computer (sign out first if needed), it doesn't ask for a 2FA code?
