### ISSUE TITLE
Command sequence

### ISSUE THREAD

**Issue by poplolnman** [Jackett/Jackett#11]
Could someone tell me the exact commands (in full steps) on how to download and get jackett working on ubuntu? thank you in advance!

**Comment by blindpet** [comment]
I have posted guides for [Ubuntu 14.x](http://www.htpcguides.com/install-jackett-on-ubuntu-14-x-for-custom-torrents-in-sonarr/) and [Ubuntu 15.x](http://www.htpcguides.com/install-jackett-ubuntu-15-x-for-custom-torrents-in-sonarr/) which the devs are welcome to add links to in the wiki (or I can if they give me permission).

**Comment by flightlevel** [comment]
Thanks @blindpet I've added your guides to the install section
