### ISSUE TITLE
[Question] Jackett Tracker Login 

### ISSUE THREAD

**Issue by HDVinnie** [Jackett/Jackett#11003]
I have a question for the devs of Jackett. When a user has a tracker loaded in Jackett and its working fine. However then they change there tracker password and forget to update it on Jackett. How often does Jackett try to reconnect/login to the tracker. As it seems like its every 3s which is problematic. I can explain in more detail why if need be.

**Comment by ilike2burnthing** [comment]
On its own, never. If you run a test, once. If you have something using the indexer (e.g. Sonarr/Radarr/*arr), however often it makes a request (e.g. 30mins). Nothing I know of, short of an intentionally written script, should be trying to connect every 3 seconds.

That help you find the cause?

**Comment by HDVinnie** [comment]
Going to do more digging. Hoping soon Jackett can move all UNIT3D based trackers to use UNIT3D's {JSON} API. 

Can close this though as its clearly not directly linked to Jackett. Thanks.
