### ISSUE TITLE
filelist.ro problem.

### ISSUE THREAD

**Issue by masterpae** [Jackett/Jackett#1100]
They have added recently a onHover image for all the results. 

So now, Jacket still works when you test it, but the result is all messed up becouse instad the torrent name, now the results are all links to the image used for onHover. So Sonarr for exemple even it seems to comunicate with jackett he gets no usable results from the tracker.

Thank you for this amasing tool! :)

**Comment by kaso17** [comment]
this is already fixed in the latest version
