### ISSUE TITLE
[hdspace] Exception (hdspace): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by napei** [Jackett/Jackett#11009]
### Description

HD-Space has added a challenge to their site recently, or they've enabled it.

### Logged Error Messages

![image](https://user-images.githubusercontent.com/8946502/106841979-407fba80-66f7-11eb-8361-aa843a78f2bc.png)

### Environment

**OS**: `Windows 10 Pro`

**.Net Runtime**: `.net framework`

**.Net Version**: `v4.8`

**Jackett Version**: `v0.17.449`

**Last Working Jackett Version**: `v0.17.449`

**Are you using a proxy or VPN?** no

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured

**Comment by ilike2burnthing** [comment]
[v0.17.456](https://github.com/Jackett/Jackett/releases/tag/v0.17.456)
