### ISSUE TITLE
UFW firewall and Jackett

### ISSUE THREAD

**Issue by jonstoate** [Jackett/Jackett#11006]
An issue, a workaround and followup from Raspberry pi 3 (Raspbian) : Use Jackett over the internet? #9402

### Environment
Raspberry Pi 4 Model B Rev 1.4

uname -a
Linux remotepi 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux

**Jackett Version**: v0.17.437 - arm-32 bit

**Are you using a proxy or VPN?** yes

### Description
I am running OpenVPN to connect to my VPN provider (NordVPN) - with
$ sudo ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), deny (outgoing), disabled (routed)

I add the following rules - which allows a connection to the vpn server to establish the VPN and directs all traffic to use the VPN
sudo ufw allow out to xxx.xxx.xxx.xxx port 1194 proto udp
sudo ufw allow out on tun0 from any to any
sudo ufw allow in on tun0 from any to any

With these rules in place other apps work - deluge for example, but jackett fails (for example on a manual search) with a time out.

Looking at the firewall logs Jackett seems to be binding to a specific network interface - in my case eth0

I added the following rules
sudo ufw allow out https
sudo ufw allow out http
sudo ufw allow out 53

which allows outgoing traffic over any interface and all is working now.

**Comment by ilike2burnthing** [comment]
Apologies if I'm misunderstanding, but are you providing a solution for others, or are you continuing to have one?
