### ISSUE TITLE
nyaa.si searches containing 01 do not properly find S01E01

### ISSUE THREAD

**Issue by kittydoor** [Jackett/Jackett#11019]
### Environment

**OS**: Linux

**.Net Runtime**: LinuxServer.io image

**.Net Version**: LinuxServer.io image

**Jackett Version**:  v0.17.449

**Last Working Jackett Version**: unknown

**Are you using a proxy or VPN?** no

### Description

Sonarr will by default search for `<Series Name> <Episode Count>`.
This maps to examples such as:
- Jujutsu Kaisen 01
- Jujutsu Kaisen 02
- Jujutsu Kaisen 10
- Jujutsu Kaisen 11

If you are searching for a torrent which includes episode in format of SXXEXX, such as S01E01, nyaa.si will successfully find any episode greater than and equal to 10, and fail to find any results for episodes equal to and less than 9.

This appears to be due to their search/indexing implementation in elastic and based on the IRC is not likely to be remedied anytime soon (if ever).

A workaround which seems to work, as suggested on nyaa irc, is to trim the leading 0s, and search for 1, 2, etc. This will find the relevant torrent (and a lot more), after which Sonarr can deal with parsing the SXXEXX to figure out the correct one.

Reproduce:

1. In Jackett, with the nyaa.si provider search for "[Judas] Jujutsu Kaisen 02"
2. See that there are no torrents found
3. In Jackett, with the nyaa.si provider search for "[Judas] Jujutsu Kaisen 2"
4. See that the correct torrent, among all the other episodes of the series is found (unsure why)

Expected:
1. In Jackett, with the nyaa.si provider search for "[Judas] Jujutsu Kaisen 02", have Jackett trim the leading zeros
2. See that the correct torrent is found
3. In Jackett, with the nyaa.si provider search for "[Judas] Jujutsu Kaisen 2"
4. See that the correct torrent is found

This issue was raised with Jackett due to @markus101's response to Sonarr/Sonarr#4069 in relation to a similar special cases.

**Comment by ilike2burnthing** [comment]
Side effect of this potential fix:
- search for `dr stone 04` returns relevant results
- search for `dr stone 4` returns mixed results, also matching `mp4` and `480p` in the title

**Comment by kittydoor** [comment]
Probably better to get too much, and sieve through it, rather than not get the thing you want in the first place, right?

Things like mp4 and 480p can easily be detected as they are very common terms on Sonarr's side (or any other tool utilizing Jackett).

**Comment by ilike2burnthing** [comment]
Depends on how many results we're getting it could have a negative impact, e.g. we now get 300 results instead of 60, 50 of which are relevant, and are spread across multiple pages (Jackett only gets the first page), so now Jackett has 10 relevant results instead of all 50.

**Comment by kittydoor** [comment]
Hmm, I mean the alternative is to try all variations as separate searches. When Jackett gets a search including "01", also try  "E01", "S01E01" and maybe even more?

I must say I'm not sure what would be a good approach, but to me a Sonarr search not being able to find 1-9th episodes of any release that uses S0XE0X format is an important bug I would like to find a resolution one way or another.

**Comment by ilike2burnthing** [comment]
Agreed, it's an issue, I just don't want to fix by breaking something else.

To my knowledge, in Jackett only one indexer performs multiple, slightly tweaked searches, and that's yggtorrent - a fix no one likes for an indexer no one likes, and it causes most or all results to be duplicated.

I'll have a play about with some of the above to see if I can come up with a workable solution.

**Comment by ilike2burnthing** [comment]
Removing a preceding `0`:
```
search:
  paths:
    - path: /
  inputs:
    # remove 0 preceding episode number #11019
    q: "{{ re_replace .Keywords \" 0(\\d{1})\" \" $1\" }}"
    f: "{{ .Config.filter-id }}"
    c: "{{ .Config.cat-id }}"
    s: "{{ .Config.sort }}"
    o: "{{ .Config.type }}"

  rows:
    selector: tr.default,tr.danger,tr.success
    filters:
      - name: andmatch
```

`dr stone 04` gives 55 results, 54 relevant
`dr stone 4` gives 351 results, 36 relevant on the first page (what Jackett gets)
So basically we lose 18 results.

I was having a look at their search operators, but I can't find a good combination - https://nyaa.si/help#using-search
`dr. stone 04|4` gives 1000 results, 2 relevant on the first page
`"dr. stone" 04|4` gives 248 results, 34 relevant on the first page
`"dr stone" 04|4` (no `.`) gives only 13 results, so using exact phrases is an issue itself

Let me know if you or those on the IRC can find a better solution. Preventing partial word matches (`dr` finds `DrachenFansub`, `4` finds `480p`) would be great, but then would obviously prevent `2` finding `S01E02`, that's not not even an option on their end.

Using a similar method to yggtorrent:
```search:
  paths:
    - path: "?q={{ .Keywords }}&f={{ .Config.filter-id }}&c={{ .Config.cat-id }}&s={{ .Config.sort }}&o={{ .Config.type }}"
    - path: "?q={{ if .Keywords }}{{ re_replace .Keywords \" 0(\\d{1})\" \" $1\" }}{{ else }}&p=2{{ end }}&f={{ .Config.filter-id }}&c={{ .Config.cat-id }}&s={{ .Config.sort }}&o={{ .Config.type }}"

  rows:
    selector: tr.default,tr.danger,tr.success
    filters:
      - name: andmatch
```
`dr stone 04` gives 91 results, 25 of which are duplicates
`dr stone` gives 150 results, half of which are duplicates (that will always be the case for a search term which doesn't include `0X`)

Short of finding a solution via their search operators, that might be the 'best' (read: least bad) option.

**Comment by ilike2burnthing** [comment]
@kittydoor were you or those on the IRC able to come up with any better solution?

**Comment by ilike2burnthing** [comment]
[v0.18.345](https://github.com/Jackett/Jackett/releases/tag/v0.18.345)
