### ISSUE TITLE
[Question] Image size in dashboard

### ISSUE THREAD

**Issue by danimart1991** [Jackett/Jackett#11015]
A little question here. 

I'm updating some indexers and see that in some of them the service https://images.weserv.nl/ is used to crop the images. 

Is this necessary?
What is the best size to use?

**Comment by ilike2burnthing** [comment]
It was added by @garfield69 in https://github.com/Jackett/Jackett/commit/8d6d56bc67facdcfa643c4a408d37857bd598fd6 for UNIT3D trackers to standardise the size of the posters. Not sure if it's therefore only intended to be used for UNIT3D trackers.

Only size used is w=180 h=270.

**Comment by danimart1991** [comment]
Thanks for your answer.

**Comment by ilike2burnthing** [comment]
Ok to close this?

**Comment by danimart1991** [comment]
Totally.

Sorry, I usually bring the repo owner the last word on close Issues.

Thank you for your answer. 😉

Daniel Martín González

________________________________
