### ISSUE TITLE
[divxtotal] only showing first page of search results

### ISSUE THREAD

**Issue by heroku-miraheze** [Jackett/Jackett#11027]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: .Net-Runtime

**.Net Version**: Unknown

**Jackett Version**: Unknown

**Last Working Jackett Version**: Unknown

**Are you using a proxy or VPN?** no

### Description

Add a feature to show all search results in all pages. In divxtotal.se shows 400 torrents and in Jackett shows 15.

### Logged Error Messages

No log.

**Comment by ilike2burnthing** [comment]
For most indexers Jackett will only fetch the first page of results, possibly a second, to get up to ~100 results (the max used by applications such as Sonarr and Radarr, and in general a good number of results for any search).

This also avoids spamming sites with pointless requests, and potentially getting IPs or accounts blocked.

Some indexers will use more where necessary, one of which (I think) is supposed to be DivxTotal, however it doesn't seem to be working. @ngosang first page is fetched fine, but pages 2 and 3 are never requested.

**Comment by XYZJR** [comment]
The code to check if we're looking at the results of the last page is a bit simplistic and fails at the first page. `isLastPage = rows.Length - 1 <= MaxResultsPerPage;`

It would be better to check if the page has an <a> tag that links to the next page.
`<ul class="pagination"><li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li><li><a href="https://www.divxtotal.se/page/2/?s">2</a></li><li><a href="https://www.divxtotal.se/page/3/?s">3</a></li><li><a href="https://www.divxtotal.se/page/2/?s"><span aria-hidden="true">›</span></a></li><li><a href="https://www.divxtotal.se/page/1506/?s"><span aria-hidden="true">»</span></a></li></ul>`

I'll look into it tomorrow.

**Comment by heroku-miraheze** [comment]
All trackers, please.

**Comment by ilike2burnthing** [comment]
See my initial response. Such a feature won't be added. If you need to see >100 results you'll have to use the relevant site.

If there are particular indexers which are returning irrelevant or too few results, let us know.

**Comment by ilike2burnthing** [comment]
[v0.17.532](https://github.com/Jackett/Jackett/releases/tag/v0.17.532)
