### ISSUE TITLE
[New Tracker REQ] ArcheTorrent

### ISSUE THREAD

**Issue by seb972** [Jackett/Jackett#1102]
Indexer Name
Archetorrent

Type
Movies, TV, Anime, Books, Games, Software

Is the indexer private or public? If private, can you provide an invite?
Private, don't need invitation

Indexer URL
https://www.archetorrent.com

Indexer language
French

**Comment by nikogaug** [comment]
Hello, I see that RoloSoze add Archetorrent as new tracker, but I didn't find it in the list of Jackett. Am I missing something ?

**Comment by nikogaug** [comment]
If it could help : 
\\Appl Linux, Appl PC
AddMultiCategoryMapping(TorznabCatType.PC, 55, 18, 38);
\\Appl Mac
AddCategoryMapping("19", TorznabCatType.PCMac);
\\E-Books, Ebooks XXX
AddMultiCategoryMapping(TorznabCatType.BooksEbook, 36, 56);
\\Images
AddCategoryMapping("37", TorznabCatType.Other);
\\Films 3D
AddCategoryMapping("23", TorznabCatType.Movies3D);
\\Adultes
AddCategoryMapping("25", TorznabCatType.XXX);
\\Films Animé, Films BdRip, Films BrRip, Films Docs, Films DVDRIP, Films Manga, Films Retro, Films Releases TAT, Films VostFr, Films WebRip
AddMultiCategoryMapping(TorznabCatType.Movies, 47, 52, 53, 48, 2, 57, 69, 68, 23, 59);
\\Films Bluray
AddCategoryMapping("22", TorznabCatType.MoviesBluRay);
\\Films Cam-TS, Films R5
AddMultiCategoryMapping(TorznabCatType.MoviesSD, 4, 51);
\\Films DVD, Films DVD Pack
AddMultiCategoryMapping(TorznabCatType.MoviesDVD, 1, 55);
\\Films HD 1080, Films HD 720, Films M-HD, UHD 4K
AddMultiCategoryMapping(TorznabCatType.MoviesHD, 3, 42, 63, 70);
\\Spectacles
AddCategoryMapping("49", TorznabCatType.TVOTHER);
\\Jeux DS
AddCategoryMapping("45", TorznabCatType.ConsoleNDS);
\\Jeux PC
AddCategoryMapping("10", TorznabCatType.PCGames);
\\Jeux PS 2
AddCategoryMapping("11", TorznabCatType.ConsoleOther);
\\Jeux PS 3
AddCategoryMapping("43", TorznabCatType.ConsolePS3);
\\Jeux PSP
AddCategoryMapping("12", TorznabCatType.ConsolePSP);
\\Jeux Wii
AddCategoryMapping("44", TorznabCatType.ConsoleWii);
\\Jeux XBox 360
AddCategoryMapping("14", TorznabCatType.ConsoleXbox360);
\\Musique Clips Video
AddCategoryMapping("27", TorznabCatType.AudioVideo);
\\Musique Flac, Music Releases TAT
AddMultiCategoryMapping(TorznabCatType.Audio, 58, 71);
\\Musique MP3
AddCategoryMapping("26", TorznabCatType.AudioMP3);
\\TV Anime
AddCategoryMapping("73", TorznabCatType.TVAnime);
\\TV DvdRip, Pack TV, TV 1080 P, TV 720 P, TV BdRip, TV VostFr, TVRip
AddMultiCategoryMapping(TorznabCatType.TV, 5, 60, 66, 65, 62, 64, 61);
\\TV HD, TV Pack HD
AddMultiCategoryMapping(TorznabCatType.TVHD, 41, 67);
\\TV Sports
AddCategoryMapping("72", TorznabCatType.TVSport);

**Comment by kaso17** [comment]
Added via #1334

**Comment by nikogaug** [comment]
Great thanks Kaso17 !
