### ISSUE TITLE
YGG search works, but can not download any torrent

### ISSUE THREAD

**Issue by EmaldIsBack** [Jackett/Jackett#11037]
### Environment

**OS**: Ubuntu 20.04

**.Net Runtime**: .Net-Core

**.Net Version**:  3.1.10

**Jackett Version**: v0.17.474

**Last Working Jackett Version**: 4 or 5 days ago (always up to date)

**Are you using a proxy or VPN?** no

### Description

search works fine on radarr/sonarr, but i get an error while trying to download

### Logged Error Messages

https://ghostbin.com/paste/sIeru

**Comment by ilike2burnthing** [comment]
YGGtorrent or YGGcookie? I'm assuming the latter. Try the other to see if the issue continues. If it was YGGcookie, try a new cookie.

**Comment by EmaldIsBack** [comment]
i tried both, even tried a new cookie, both give the same error

**Comment by ilike2burnthing** [comment]
Can you download the same torrent in browser from the same device and IP? For some reason it's redirecting you to the homepage (signed in) instead of downloading the .torrent file.

**Comment by EmaldIsBack** [comment]
thanks man, you just gave me the clue of what's going on! :D i changed the url before to make i work by adding /?attempt=1 (it fixed logging for a period), now just removed it and it works fine, thanks and sorry for distubing

**Comment by ilike2burnthing** [comment]
S'all good, glad you got it resolved.
