### ISSUE TITLE
xspeeds not working, version 1079

### ISSUE THREAD

**Issue by manderss99** [Jackett/Jackett#1104]
test fails, get some message to turn on javascript. 
a search returns 0 results.
ubuntu 16.04. this has worked previously but it seems something changed on xspeeds end.

Jackett version:  1079
Mono version (if not using Windows):  

-------------------------------

**Comment by manderss99** [comment]
Test failed for xspeeds: Please turn JavaScript on and reload the page. Checking your browser before accessing xspeeds.eu. This process is automatic. Your browser will redirect to your requested content shortly. Please allow up to 5 seconds…

**Comment by manderss99** [comment]
Feb 25, 2017 09:42:15 AM	Error	
Exception in test_indexer
Feb 25, 2017 09:42:14 AM	Info	
UnixLibCurlWebClient: received CloudFlare clearance cookie: __cfduid=d17688a328c00548f2703ad9a243f2b2c1488012134;
Feb 25, 2017 09:42:09 AM	Info	
UnixLibCurlWebClient: CloudFlare clearanceUri: https://www.xspeeds.eu:443/cdn-cgi/l/chk_jschl?jschl_vc=59a86142941ef1ddf8d04c9afb2a7147&pass=1488012133.248-49+xA05mLX&jschl_answer=34
Feb 25, 2017 09:42:09 AM	Info	
UnixLibCurlWebClient: Received a new CloudFlare challenge

**Comment by manderss99** [comment]
Feb 25, 2017 09:42:15 AM	Error	
Exception in test_indexer
Feb 25, 2017 09:42:14 AM	Info	
UnixLibCurlWebClient: received CloudFlare clearance cookie: __cfduid=d17688a328c00548f2703ad9a243f2b2c1488012134;
Feb 25, 2017 09:42:09 AM	Info	
UnixLibCurlWebClient: CloudFlare clearanceUri: https://www.xspeeds.eu:443/cdn-cgi/l/chk_jschl?jschl_vc=59a86142941ef1ddf8d04c9afb2a7147&pass=<pass>&jschl_answer=34
Feb 25, 2017 09:42:09 AM	Info	
UnixLibCurlWebClient: Received a new CloudFlare challenge

**Comment by kaso17** [comment]
working fine for me with Jackett Version 0.7.1079.0 on ubuntu 16.04 (using libcurl)
.
Please post the complete log with enhanced logging enabled.

**Comment by Metigoth** [comment]
Only one out of my set working with 1079 is BTN.
All others failed due to cookie errors. Rolled back to 1072 and most of them work again.  
MTV,UHDBits,MaM in 1072 Found no results.
UHDBits and MTV work in cardigann.

Debian Jessie 64Bit.

Error on 20170225122727 for UHDBits.txtJackett.ExceptionWithConfigData: Login Failed, got redirected
  at Jackett.Indexers.CardigannIndexer+<TestLogin>c__async1.MoveNext () [0x000ed] in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:700 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f712f98eb8e445c8918edaf595bbe465>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <f712f98eb8e445c8918edaf595bbe465>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <f712f98eb8e445c8918edaf595bbe465>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <f712f98eb8e445c8918edaf595bbe465>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f712f98eb8e445c8918edaf595bbe465>:0 
  at Jackett.Indexers.CardigannIndexer+<PerformQuery>c__async5.MoveNext () [0x0083b] in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:1124

**Comment by manderss99** [comment]
08:55:01 AM	Info	
  Content-type='application/json; charset=utf-8', content-length=29
Feb 26, 2017 08:55:01 AM	Info	
AdminController ExecuteAsync 
Feb 26, 2017 08:55:01 AM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync 
Feb 26, 2017 08:55:01 AM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Feb 26, 2017 08:55:01 AM	Info	
ApiControllerActionInvoker InvokeActionAsync 
Feb 26, 2017 08:55:01 AM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]'
Feb 26, 2017 08:55:01 AM	Debug	
Saving new config file: /home/manderss99/.config/Jackett/Indexers/xspeeds.json.56b6af34e68a4a89b51b52bb7fbac357.tmp
Feb 26, 2017 08:55:01 AM	Error	
Exception in test_indexer
Feb 26, 2017 08:55:01 AM	Debug	
IWebClient: Returning Redirect => https://www.xspeeds.eu/login.php?returnto=%2Fbrowse.php 0 bytes
Feb 26, 2017 08:55:01 AM	Debug	
IWebClient.GetBytes(Url:https://www.xspeeds.eu/browse.php)
Feb 26, 2017 08:55:01 AM	Debug	
IWebClient: Returning Redirect => https://www.xspeeds.eu/login.php?returnto=%2Fbrowse.php 0 bytes
Feb 26, 2017 08:55:00 AM	Debug	
IWebClient.GetBytes(Url:https://www.xspeeds.eu/browse.php)
Feb 26, 2017 08:55:00 AM	Debug	
IWebClient: Returning Redirect => https://www.xspeeds.eu/login.php?returnto=%2Fbrowse.php 0 bytes
Feb 26, 2017 08:55:00 AM	Debug	
IWebClient.GetBytes(Url:https://www.xspeeds.eu/browse.php)
Feb 26, 2017 08:55:00 AM	Debug	
IWebClient: Returning Redirect => https://www.xspeeds.eu/login.php?returnto=%2Fbrowse.php 0 bytes
Feb 26, 2017 08:55:00 AM	Debug	
IWebClient.GetBytes(Url:https://www.xspeeds.eu/browse.php)
Feb 26, 2017 08:55:00 AM	Debug	
IWebClient: Returning Redirect => https://www.xspeeds.eu/login.php?returnto=%2Fbrowse.php 0 bytes
Feb 26, 2017 08:55:00 AM	Debug	
IWebClient.GetBytes(Url:https://www.xspeeds.eu/browse.php)
Feb 26, 2017 08:55:00 AM	Debug	
IWebClient: Returning Redirect => https://www.xspeeds.eu/login.php?error=2&username=manderss99 
Feb 26, 2017 08:55:00 AM	Debug	
UnixLibCurlWebClient: Posting username=manderss99&password=fgHC9900
Feb 26, 2017 08:55:00 AM	Info	
UnixLibCurlWebClient: received CloudFlare clearance cookie: __cfduid=d226fea6c9f16747e78f7e6bbe68990441488095700; cf_clearance=774e753103e3f3d26d95e8d669d7e8a9c09cdcee-1488095700-3600;
Feb 26, 2017 08:54:54 AM	Info	
UnixLibCurlWebClient: CloudFlare clearanceUri: https://www.xspeeds.eu:443/cdn-cgi/l/chk_jschl?jschl_vc=d0b606efd94999bb4b3bb4265f3d9e8f&pass=1488095698.603-icBUIkqZfo&jschl_answer=106
Feb 26, 2017 08:54:54 AM	Info	
UnixLibCurlWebClient: Received a new CloudFlare challenge
Feb 26, 2017 08:54:54 AM	Debug	
UnixLibCurlWebClient: Posting username=manderss99&password=fgHC9900
Feb 26, 2017 08:54:54 AM	Debug	
IWebClient.GetString(Url:https://www.xspeeds.eu/takelogin.php)
Feb 26, 2017 08:54:54 AM	Debug	
Saving new config file: /home/manderss99/.config/Jackett/Indexers/xspeeds.json.cf649a1366d74edc82087ca01cb0bc61.tmp
Feb 26, 2017 08:54:54 AM	Debug	
updating Cookies __cfduid=d6aaf5b4ce5c01bbf85a291624557b2791488012024; cf_clearance=9e1d076d3ce2c718aca113986ce0948adc4578a1-1488012024-3600; c_secure_uid=deleted; c_secure_pass=deleted; acqu=Mg%3D%3D => __cfduid=d6aaf5b4ce5c01bbf85a291624557b2791488012024; cf_clearance=12a3d86400e8f1fc9142e81a2775f861e3ead561-1488095694-3600; c_secure_uid=deleted; c_secure_pass=deleted; acqu=Mg%3D%3D
Feb 26, 2017 08:54:54 AM	Debug	
IWebClient: Returning Redirect => https://www.xspeeds.eu/login.php?returnto=%2Fbrowse.php 
Feb 26, 2017 08:54:54 AM	Debug	
UnixLibCurlWebClient: Posting do=search&keywords=&search_type=t_name&category=0&include_dead_torrents=no
Feb 26, 2017 08:54:54 AM	Info	
UnixLibCurlWebClient: received CloudFlare clearance cookie: cf_clearance=12a3d86400e8f1fc9142e81a2775f861e3ead561-1488095694-3600;

**Comment by manderss99** [comment]
attaching enhanced log:

[xspeeds.txt](https://github.com/Jackett/Jackett/files/801787/xspeeds.txt)

**Comment by manderss99** [comment]
I did reconfigure xspeeds and now it seems to be working again, thanks

**Comment by kaso17** [comment]
Methigoth: if you you're running mono 4.8 please try version v0.7.1084
@manderss99: please try removing/adding xspeeds again (not just reconfigure it), an update to mono 4.8 might also fix it.

**Comment by kaso17** [comment]
and also change your password (it's part of your log)

**Comment by Metigoth** [comment]
Yes, I was running mono 4.8 from xamarin repo. Jackett 0.7.1084 fixed cookie issues.
