### ISSUE TITLE
"Spaces" in Title search for YTS breaks results and causes Radarr to stop searching.

### ISSUE THREAD

**Issue by bigdant** [Jackett/Jackett#11040]
Hi,

I'm running Jackett on Unraid with Radarr.

When i run a search with a space in the title i get the following error:-

`<error code="900" description="Jackett.Common.IndexerException: Exception (yts): API error, movies missing ---> System.Exception: Parse error ---> System.Exception: API error, movies missing at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query, Int32 attempts) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/YTS.cs:line 138 --- End of inner exception stack trace --- at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 682 at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query, Int32 attempts) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/YTS.cs:line 210 at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/YTS.cs:line 87 at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390 --- End of inner exception stack trace --- at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390 at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 659 at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 427"/>`

Its probably YTS but if you search for a movie that isnt availabale with a space in the title is comes back with an error, which in turn breaks Radarr and stops it from continuing its search, so if you are looking for 25+ movies it will stop the search once this error is recieved.

And exmaple API serach is as follows:-

http://192.168.1.44:9117/api/v2.0/indexers/yts/results/torznab/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(API Key)&offset=0&limit=100&q=Land2021

The above will come back with a proper response (Even though the movie is missing)

<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://192.168.1.44:9117/" rel="self" type="application/rss+xml" />
    <title>YTS</title>
    <description>YTS is a Public torrent site specialising in HD movies of small size</description>
    <link>https://yts.mx/</link>
    <language>en-us</language>
    <category>search</category>
  </channel>
</rss>

Where are this:-

http://192.168.1.44:9117/api/v2.0/indexers/yts/results/torznab/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(API Key)&offset=0&limit=100&q=Land%202021

Will cause the above error (Due to the space between Land 2021)

I hope this makes sense ??

Thanks again for your amazing app !

**Comment by bigdant** [comment]
OK, for clarity ive found a work around in Radarr by removing year from search. however this still feels like a bug somewhere as the results coming back for the above submitted title shouldnt cause that kind of crash.

**Comment by ilike2burnthing** [comment]
`Land%20and%20freedom` works and returns results, as does `Land%201995`, `Land%202020` or any other year which has results.

`Land%20gvjguyb` returns:
```
<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://REMOVED/Jackett/" rel="self" type="application/rss+xml" />
    <title>YTS</title>
    <description>YTS is a Public torrent site specialising in HD movies of small size</description>
    <link>https://yts.mx/</link>
    <language>en-us</language>
    <category>search</category>
  </channel>
</rss>
```
(no results)

But if the year is used, and there are no results (e.g. 2021, 1921), it freaks out with that error.

@XYZJR or @ngosang

**Comment by bigdant** [comment]
Phew! Not just me or my set-up then !! thanks

**Comment by XYZJR** [comment]
https://yts.mx/api/v2/list_movies.json?sort=date_added&limit=50&query_term=Land+2021

This is what the code asks for, and as you can see, `"movie_count":49`, but it's empty. Do you want us to return an empty result, instead of the error?

**Comment by ilike2burnthing** [comment]
Please, yea.

**Comment by ilike2burnthing** [comment]
[v0.17.532](https://github.com/Jackett/Jackett/releases/tag/v0.17.532)
