### ISSUE TITLE
[sktorrent] An error occurred while sending the request: Error: TrustFailure (Authentication failed, see inner exception.) (Config)

### ISSUE THREAD

**Issue by devforpeople** [Jackett/Jackett#11043]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Synology

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.474

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description
Can't add sktorrent.
[List steps to reproduce the error and details on what happens and what you expected to happen]
I've try to add sktorrent, filled out the credentials.
I've got the jackett from https://synocommunity.com/package/jackett

### Logged Error Messages

An error occurred while updating this indexer
An error occurred while sending the request: Error: TrustFailure (Authentication failed, see inner exception.)

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
If you can run Docker, I'd suggest you use the Jackett image.

If not, you can try downgrading mono using the following method - https://github.com/SynoCommunity/spksrc/issues/3946#issuecomment-612562594 (see bottom half of the comment)

The naming scheme has seemingly changed slightly on SynoCommunity, but the one mentioned `5.8.0.108-11 [6.1 rtd1296]` seems to be https://packages.synocommunity.com/mono/11/mono.v11.f15047[rtd1296-armada37xx-aarch64].spk

You can try some of the relevant, more recent versions there as well - https://packages.synocommunity.com/mono
