### ISSUE TITLE
All tracker dont work: Jackett.Common.IndexerException: Exception (gktorrent): Cannot assign requested address

### ISSUE THREAD

**Issue by kestouf** [Jackett/Jackett#11042]
### Environment

**OS**: Doker (NAS Synology)

**.Net Runtime**: Mono

**.Net Version**:

**Jackett Version**: v0.17.464

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

All my trackers have the same error message:
Jackett.Common.IndexerException: Exception (gktorrent): Cannot assign requested address

I try to remove en cretate tracker... Same probleme

Can you help me?

### Logged Error Messages

https://pastebin.com/UesZrkup

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Not the same error, but try the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

Try adding the indexer Newstudio and let me know if you get the same issue.
