### ISSUE TITLE
[New Tracker REQ] PTF

### ISSUE THREAD

**Issue by snooptodd** [Jackett/Jackett#1105]
Indexer Name
PTFiles

Type
Movies, TV, Audio, XXX, PC, Books, Console, Other

Indexer URL
https://ptfiles.net

Indexer Language
English

Invite 
I have some available.

**Comment by kaso17** [comment]
Please send an invite to kaso1717 - at - gmail.com

**Comment by snooptodd** [comment]
invite sent.

**Comment by kaso17** [comment]
got it

**Comment by kaso17** [comment]
added with eee7c7d8438a5f95c806aaf95699d6d3712172c4

**Comment by garfield69** [comment]
https://ptfiles.net/ > TCP Connection Failed (Times out)

**Comment by ilike2burnthing** [comment]
back up
