### ISSUE TITLE
[abtorrents] Exception (abtorrents): Login Failed, got redirected.: Parse error (Test)

### ISSUE THREAD

**Issue by mtae** [Jackett/Jackett#11055]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:v0.17.496

**Last Working Jackett Version**: v0.17.474 (I think, went straight from that one to this one)

**Are you using a proxy or VPN?** no

### Description

Ran the test

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
From the config panel:
```
If you are getting the error Login Failed, got redirected then access the site with your browser and mark as read all PMs.
```
