### ISSUE TITLE
[anidex] Connection refused (check.ddos-guard.net:443): Connection refused (Config)

### ISSUE THREAD

**Issue by RunningBottom** [Jackett/Jackett#11056]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux Mint 20.04

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.496

**Last Working Jackett Version**: Unknown

**Are you using a proxy or VPN?** [yes/no] yes

### Description

Tried to add Anidex as an indexer via 127.0.0.1:9117

### Logged Error Messages

   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by ilike2burnthing** [comment]
Can you access the site in browser from the same device and IP?

Try without your VPN/proxy, or a different server.
