### ISSUE TITLE
[torrentz2k] Exception (torrentz2k): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by Arkitecton** [Jackett/Jackett#11051]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10 pro 64-bit

**.Net Runtime**: Latest update of Microsoft

**.Net Version**: Latest update of Microsoft

**Jackett Version**:  Jackett Version v0.17.213 

**Last Working Jackett Version**:  Jackett Version v0.17.213 

**Are you using a proxy or VPN?** no

### Description

When I add torrent site to jacket and want to test the error comes with warning sign beside test but the torrentz2k site working fine.

### Logged Error Messages

Don't have any!

### Screenshots

![image](https://user-images.githubusercontent.com/19477961/107551346-c74cff80-6bef-11eb-97d8-af2823c00d5f.png)

**Comment by Arkitecton** [comment]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10 pro 64-bit

**.Net Runtime**: Latest update of Microsoft

**.Net Version**: Latest update of Microsoft

**Jackett Version**:  Jackett Version v0.17.213 

**Last Working Jackett Version**:  Jackett Version v0.17.213 

**Are you using a proxy or VPN?** no

### Description

When I add torrent site to jacket and want to test the error comes with warning sign beside test but the torrentz2k site working fine.


### Logged Error Messages

Don't have any!

### Screenshots

![image](https://user-images.githubusercontent.com/19477961/107551346-c74cff80-6bef-11eb-97d8-af2823c00d5f.png)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
