### ISSUE TITLE
[yggtorrent] Cloudflare Error: No challenge selectors found, unable to proceed

### ISSUE THREAD

**Issue by foux** [Jackett/Jackett#11058]
### Environment

**OS**: Linux / Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.496

**Are you using a proxy or VPN?** no

### Description

Here we are again with YGGTorrent and Cloudflare... This time FlareSolver tells it didn't find any challenge.

**Comment by ilike2burnthing** [comment]
https://www2.yggtorrent.si/ - YggTorrent est en maintenance

**Comment by foux** [comment]
Oups, thanks @ilike2burnthing

**Comment by saitoh183** [comment]
The url is now yggtorrent.li

**Comment by ilike2burnthing** [comment]
Currently getting 502 Bad Gateway

**Comment by saitoh183** [comment]
It is going to be up and down till optimisation is done based on twitter post

**Comment by CyberPoison** [comment]
I still see issues on my side, as well with the new URL / Docker Image .

https://github.com/Jackett/Jackett/issues/11069

**Comment by ilike2burnthing** [comment]
Closing in favour of https://github.com/Jackett/Jackett/issues/11069 as more relevant.
