### ISSUE TITLE
[request] add acrossthetasman.com

### ISSUE THREAD

**Issue by dregin** [Jackett/Jackett#11062]
I've a PR ready for this.

**Comment by ilike2burnthing** [comment]
Closing in favour of https://github.com/Jackett/Jackett/issues/1628

**Comment by dregin** [comment]
huh, did search - sorry about that. Will update my PR description to link that issue instead.

**Comment by ilike2burnthing** [comment]
No worries, it's from 2017, easy to miss something that far back
