### ISSUE TITLE
Error while trying to add a tracker: Configuration failed: Could not load type 'CloudFlareUtilities.ClearanceHandler' 

### ISSUE THREAD

**Issue by scratchpxg** [Jackett/Jackett#1107]
Configuration failed: Could not load type 'CloudFlareUtilities.ClearanceHandler' from assembly 'CloudFlareUtilities, Version=0.4.0.0, Culture=neutral, PublicKeyToken=null'.

Jackett version:  0.7.1072.0
Mono version (if not using Windows):  Mono JIT compiler version 4.8.0 (Stable 4.8.0.495

-------------------------------

**Comment by flightlevel** [comment]
Can you try the latest 1079 and running 1079 with libcurl eg. `mono JackettConsole.exe --UseClient libcurl`

**Comment by kaso17** [comment]
You're missing mono-devel. Please read the install instructions in the README again.
