### ISSUE TITLE
[demonoid] Exception (demonoid): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by mongoosc5** [Jackett/Jackett#11074]
### Environment

**OS**:UNRAID Docker

**Jackett Version**: v0.17.513

**Are you using a proxy or VPN?** no

### Description

Attempted to test connection to demonoid.is

### Logged Error Messages

 An error occurred while testing this indexer
Exception (demonoid): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
