### ISSUE TITLE
[film-paleis] Login failed: Selector

### ISSUE THREAD

**Issue by 1985kasper** [Jackett/Jackett#11072]
This tracker used to work and now it doesn't. It's still listed as supported. Clearly it isn't supported.

I contacted tracker staff they couldn't help me as they say they don't support automation. 

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu/docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.513

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

How to get the Cookie

    Login to this tracker with your browser
    Open the DevTools panel by pressing F12
    Select the Network tab
    Click on the Doc button (Chrome Browser) or HTML button (FireFox)
    Refresh the page by pressing F5
    Click on the first row entry
    Select the Headers tab on the Right panel
    Find 'cookie:' in the Request Headers section
    Select and Copy the whole cookie string (everything after 'cookie: ') and Paste here.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
An error occurred while testing this indexer
Exception (film-paleis): Login failed: Selector "a[href="logout.php"]" didn't match: Parse error
[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by eljejer** [comment]
I just did a manual search for an item from within Jacket and results from RuTracker were given. So I don't know what might be wring on your end?

**Comment by ilike2burnthing** [comment]
Please provide an **enhanced** log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by 1985kasper** [comment]
@ilike2burnthing Thanks. I got it to work by going through the steps on the actual computer jackett is running on (VNC). So i can now run a succesfull test in Jackett.

However results are still not showing in sonarr. I guess this is not necessarily a jackett issue. But not sure. The category the series are in is "FP-release". Not sure if this might be the issue?

**Comment by ilike2burnthing** [comment]
Run a search for the series in Jackett using just film-paleis, with enhanced logs enabled (see link above).

If it doesn't find results (but the same search on the site does), then you can stop reading the rest of the instructions here and upload the logs (redact any sensitive information such as your username and cookies).

If the search in Jackett does find results, then run an interactive (manual) search in Sonarr using only film-paleis (if you have other indexers, you'll first need to go into the indexers section of Sonarr's settings, click into each of the other indexers apart from film-paleis, untick `Interactive Search` and then save). Upload the enhanced Jackett log for the Sonarr search and the earlier one above.
