### ISSUE TITLE
[AcrossTheTasman] Indexer Code Needs Cleaning Up

### ISSUE THREAD

**Issue by dregin** [Jackett/Jackett#11075]
As per @garfield69's comments on https://github.com/Jackett/Jackett/pull/11063
Working on a second PR now.

**Comment by dregin** [comment]
Just realize @ilike2burnthing already made these fixes [here](https://github.com/Jackett/Jackett/commit/67ca941f01c90cffc0e81bbabb767fda1950514c). Thanks!

**Comment by ilike2burnthing** [comment]
Is there a minimum ratio (MR) for accounts?

Is there an MR and/or minimum seed time (MST) for torrents?

Is there anything which affects the download or upload volume factor (e.g. freeleech, 2x upload, etc.)?

These would need to be added as well. For example:
https://github.com/Jackett/Jackett/blob/763b54f1c139b5057ce6d80241e7a227db1e0165/src/Jackett.Common/Definitions/greekdiamond.yml#L175-L187
