### ISSUE TITLE
[montorrent] Exception (montorrent): Ssl error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION  at /spksrc/spk/mono/work-aarch64-6.1/mono-5.20.1.34/external/boringssl/ssl/tls_record.c:462: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by aymericgug** [Jackett/Jackett#11086]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: Mono

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
If you can run Docker, I'd suggest you use the Jackett image.

If not, you can try downgrading mono using the following method - https://github.com/SynoCommunity/spksrc/issues/3946#issuecomment-612562594 (see bottom half of the comment)

The naming scheme has seemingly changed slightly on SynoCommunity, but the one mentioned `5.8.0.108-11 [6.1 rtd1296]` seems to be https://packages.synocommunity.com/mono/11/mono.v11.f15047[rtd1296-armada37xx-aarch64].spk

You can try some of the relevant, more recent versions there as well - https://packages.synocommunity.com/mono
