### ISSUE TITLE
OneJAV - Broken Links

### ISSUE THREAD

**Issue by telix5000** [Jackett/Jackett#11090]
OneJAV appears to be broken after their site update. It is showing available files via RSS, however, connecting the actual RSS does not grab anything. I tried this on two different clients and the same result(s). It was last functional on 2/10/2021, which appears to be when the site was changed dramatically.

**Comment by ilike2burnthing** [comment]
They're using Cloudflare DDoS Protection, so you'll have to install and configure [FlareSolverr](https://github.com/Jackett/Jackett#configuring-flaresolverr).

If you have issues downloading, perform a manual search first, downloads should work from then on.

**Comment by ilike2burnthing** [comment]
[v0.17.538](https://github.com/Jackett/Jackett/releases/tag/v0.17.538)
