### ISSUE TITLE
unable to add ncore.cc tracker

### ISSUE THREAD

**Issue by a1888** [Jackett/Jackett#1109]
hi!

I just installed Jackett on raspberry pi 2 (running jessie), and tried to add ncore.cc tracker, but unfortunately got the following error message:

Configuration failed: Could not load type 'CloudFlareUtilities.ClearanceHandler' from assembly 'CloudFlareUtilities, Version=0.4.0.0, Culture=neutral, PublicKeyToken=null'.

Could you please check what can be the issue?
Tried kickass tracker as well, but that works fine.

Thanks.

**Comment by flightlevel** [comment]
you are probably missing mono-devel
https://github.com/Jackett/Jackett#installation-on-linuxosx

**Comment by flightlevel** [comment]
@kaso17 
Do you think we should have something in the UI
eg. Mono 4.8 recommended if lower
Warning mono-devel is missing etc

**Comment by kaso17** [comment]
added server side notices with 1f97d543df5336ccdf5c7b50cc519fba3f03220c
