### ISSUE TITLE
"Only 'http' and 'https' schemes are allowed."  trying to get magent linl

### ISSUE THREAD

**Issue by angel-lizander** [Jackett/Jackett#11092]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Xubuntu 20.04

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Net-core

**.Net Version**:

**Jackett Version**: v0.17.538

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] No

### Description
I'm trying to consuming URL from Jackett to add torrent to Transmission, but Httpclient got me " : 'Only 'http' and 'https' schemes are allowed." dont know why, the URL it's okay. 
### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Related? https://github.com/Jackett/Jackett/issues/10976
