### ISSUE TITLE
InternalServerError when adding Cookie Tracker TD

### ISSUE THREAD

**Issue by screamer21** [Jackett/Jackett#111]
12-03 12:42:26 Debug UnixLibCurlWebClient:GetString Returning InternalServerError =>
12-03 12:42:26 Error Exception in Configure System.Exception: Your cookie did not work: Your cookie did not work
  at Jackett.Indexers.TorrentDay+<ApplyConfiguration>c__async1.MoveNext () <0x80d0e7930 + 0x008d0> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x80d0f52a0 + 0x00038> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x80d0f4da0 + 0x00118> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x80d0f4cd0 + 0x000b3> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x80577f8a0 + 0x00042> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x80d0f4c90 + 0x0001a> in <filename unknown>:0
  at Jackett.Controllers.AdminController+<Configure>c__async4.MoveNext () <0x80d0e62b0 + 0x006dd> in <filename unknown>:0
12-03 12:42:26 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
12-03 12:42:26 Info ApiControllerActionInvoker InvokeActionAsync
System.Web.Http.Action: ApiControllerActionInvoker InvokeActionAsync
12-03 12:42:26 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()'
System.Web.Http.Filters: JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()'
12-03 12:42:26 Info JackettAPINoCacheAttribute OnActionExecutedAsync
System.Web.Http.Filters: JackettAPINoCacheAttribute OnActionExecutedAsync
12-03 12:42:26 Info AdminController ExecuteAsync
System.Web.Http.Controllers: AdminController ExecuteAsync
{"name":"TorrentDay","result":"error","error":"Your cookie did not work: Your cookie did not work"}
12-03 12:42:26 Debug Response: {"name":"TorrentDay","result":"error","error":"Your cookie did not work: Your cookie did not work"}
12-03 12:42:26 Info WebAPIRequestLogger SendAsync

**Comment by flightlevel** [comment]
Is the recaptcha appearing?
https://github.com/Jackett/Jackett/issues/35#issuecomment-155349820

**Comment by screamer21** [comment]
When adding TD I get a window saying this site requires captcha. (Username password and captcha box doesn't show up as per the referenced comment) I add my cookie from browser and that's the error i get in the log.

**Comment by screamer21** [comment]
Reading further on the attached comment, will my cookie changed based on my NAT LAN IP? Jackett is in a jail (192.168.1.x) and the cookie was from my PC browser (192.168.1.y). Will this be rejected?

**Comment by screamer21** [comment]
Set up X11 forwarding. Ran from localhost:9117/Admin/Dashboard on Jackett 0.7.42.0. Using UnixLibCurlWebClient, I click on Setup on TD and the window disappears. I tried with safecurl and I get 'invalid response'.

**Comment by screamer21** [comment]
12-04 12:44:36 Debug UnixLibCurlWebClient:GetString(Url:https://tdonline.org/login.php)
12-04 12:44:36 Debug UnixLibCurlWebClient:GetString Returning InternalServerError =>
12-04 12:44:36 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'

**Comment by screamer21** [comment]
Is there any follow up or ideas? Captcha does not appear because an exception is thrown when clicking setup.

**Comment by screamer21** [comment]
Is the InternalServerError thrown by a null sitekey?

**Comment by raspdealer** [comment]
Have you tried with the last version?
What is your cookie format?

**Comment by flightlevel** [comment]
This issue is more than a year old. If the issue still exists, please reopen and include full logs https://github.com/Jackett/Jackett#troubleshooting
