### ISSUE TITLE
rutracker.org : move everyting between [] and () found at the begin of a release file name.

### ISSUE THREAD

**Issue by Mrpink200** [Jackett/Jackett#11109]
### Environment

**OS**: Docker Linux

**.Net Runtime**: ?

**.Net Version**: ??  i use the https://registry.hub.docker.com/r/linuxserver/jackett/ version dev

**Jackett Version**: v0.17.546

**Last Working Jackett Version**: v0.17.546

**Are you using a proxy or VPN?** No

### Description

Music releases titles often starts with GENRE or FORMAT not compatible with LIDARR or other applications.
For example : 
[TR24][OF][192kHz] Aerosmith - Pump - 1989/2014 (Hard Rock)
Here lidarr says : wrong album

My idea would be to add an option in the rutracker.org torent setup to move at the end of a release name everything between [] or () that starts a release name (like it is for years inmovie release on some trackers like ygg)
in my example, it would give : 
Aerosmith - Pump - 1989/2014 (Hard Rock) [TR24][OF][192kHz]
and it would fix the search

**Comment by ilike2burnthing** [comment]
@XYZJR could you have a look at this? (you're in high demand)

**Comment by XYZJR** [comment]
@Mrpink200 
Not exactly as requested, but all tags are moved to the end of the release title. It's just that they remain in the same order as they are found, so your example would be:

**[TR24][OF][192kHz]** Aerosmith - Pump - 1989/2014 **(Hard Rock)**
Aerosmith - Pump - 1989/2014 **[TR24][OF][192kHz](Hard Rock)**

**Comment by Mrpink200** [comment]
> 
> 
> @Mrpink200
> Not exactly as requested, but my code does move all tags to the end of the release title. It's just that they remain in the same order as they are found, so your example would be:
> 
> **[TR24][OF][192kHz]** Aerosmith - Pump - 1989/2014 **(Hard Rock)**
> Aerosmith - Pump - 1989/2014 **[TR24][OF][192kHz](Hard Rock)**

It's perfect. So damn long i was hoping to have this to catch the rutorrent releases. You made my day. A huge thx to you !!!

**Comment by XYZJR** [comment]
@Mrpink200 I'll look into improving it some more. There's some more logic I can write that only moves the tags that are in front of the actual title. I think it would be best if tags such as `[2-CD]` and `(tracks+.cue)` in example `(live, house, electronica) [CD] Daft Punk - Alive 2007 + Alive 1997 [2-CD], FLAC (tracks+.cue), lossless` stayed where they are.

@ngosang You said you wanted me to add you as a reviewer for core changes, but should I also keep adding you for these kinds of indexer-specific issues? I need an approval from someone before it can be merged and I think you're the only other active C# dev, am I correct?

**Comment by Mrpink200** [comment]
@XYZJR , i guess that what you ve done do the trick without others improvments.

**Comment by XYZJR** [comment]
I've added a second config option. You'll now have the option to choose between moving all tags or just the first ones.

'First' is defined as whatever comes before the actual title. To detect that, I'm checking if the tags are at the start of the title, and may only be separated from each other by whitespace. Once there's more than whitespace in between them (like a word) then we stop moving tags to the end.

@Mrpink200 I've searched for Aerosmith Pump and there's a result that has a tag with curly brackets. Should I search for [all four types of brackets](https://en.wikipedia.org/wiki/Bracket) when detecting tags?

Give it a try and let me know what you think.

**Comment by Mrpink200** [comment]
i d like to test but your input is mot merged :(

**Comment by garfield69** [comment]
@Mrpink200  which platform package do you require?

**Comment by garfield69** [comment]
never mind, I see you are on docker, so you can use the test packages from 0.17.564 ;-(

**Comment by Mrpink200** [comment]
got it, thx man. But on hotio or linux server, testing version ends to 0.17.562 ... feels like sync has not been done yet.
my main jackett is on linuxserver/developpement 0.17.562

**Comment by Mrpink200** [comment]
please help validate :)

**Comment by Mrpink200** [comment]
I got .568 now but the change is not yet included :(

**Comment by XYZJR** [comment]
As long as this PR is open and not merged, you won't see this change in any release, as far as I know.

@garfield69 Can you tell me more about those test packages you were talking about? There's no development or test branch where we could make test packages from, and all PRs go straight to the master branch.

**Comment by garfield69** [comment]
>Can you tell me more about those test packages you were talking about?

The PR generates a full set of artifacts that can be downloaded and installed over the top of the Jackett binaries for testing.
For example, for PR #11125 the packages are at https://dev.azure.com/Jackett/Jackett/_build/results?buildId=2948&view=artifacts&pathAsName=false&type=publishedArtifacts

you get there by clicking on the details link of the PR checklist
![image](https://user-images.githubusercontent.com/6933240/108604414-aae06c80-7412-11eb-855f-10fa644cbc55.png)

then by clicking on the Azure Pipelines details link
![image](https://user-images.githubusercontent.com/6933240/108604444-e54a0980-7412-11eb-9aca-591551a58e22.png)

and then on the pipelines published link
![image](https://user-images.githubusercontent.com/6933240/108604514-3f4acf00-7413-11eb-9d14-ae9a8bf00456.png)

and finally expand the artifacts drop list
![image](https://user-images.githubusercontent.com/6933240/108604555-8042e380-7413-11eb-9ef6-553816af0048.png)

there is probably a shorter way of getting there but this is what I've been used to doing.
You will need an Azure account and maybe need to be added to the jackett azure development team or something, one of the other team members can chime in with corrections or better instructions for these details ;-)

**Comment by ilike2burnthing** [comment]
Yea, that's what I do, though I don't have an account so presumably that's why I don't get the drop down for the `drop` folder, instead:
![drop](https://user-images.githubusercontent.com/59480337/108607335-a470d700-73b7-11eb-93e2-1a502152148d.png)
and then just extract what I need from it.

**Comment by Mrpink200** [comment]
any update ?
i see multiple updates commited but not this one ... feel so sad ;)

**Comment by ilike2burnthing** [comment]
Waiting for review. You'll be notified when it's merged.

**Comment by garfield69** [comment]
0.17.580

**Comment by Mrpink200** [comment]
it works perfectly. Many thx to you all, especially to @XYZJR  for the fix.
