### ISSUE TITLE
[pornolab] Exception (pornolab):  Received an unexpected EOF or 0 bytes from the transport stream.: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by googleitffs** [Jackett/Jackett#11100]
### Environment

**OS**: Windows 10

**Jackett Version**: 0.17.538

**Are you using a proxy or VPN?** [yes/no] Yes, tor.

When I'm trying to do search, there's just an "error" notification. When I test the tracker, there's this error. I don't know what that means. 

### Logged Error Messages

https://pastebin.com/6V44Xh5g

**Comment by ilike2burnthing** [comment]
Repeat without tor to see if the issue continues.

**Comment by googleitffs** [comment]
> Repeat without tor to see if the issue continues.

Works fine without tor.

**Comment by ilike2burnthing** [comment]
That would seem to be your issue then.

Does the same issue happen with other indexers when using tor?

Can you access the site in browser when using tor?

**Comment by googleitffs** [comment]
> That would seem to be your issue then.
> 
> Does the same issue happen with other indexers when using tor?
> 
> Can you access the site in browser when using tor?

There isn't such issue with some other trackers (kinozal for example). I can access the site through tor normally.

**Comment by ilike2burnthing** [comment]
Try changing the site link to http rather than https. Not a great solution, but probably more desirable to you than dropping tor.

**Comment by googleitffs** [comment]
> Try changing the site link to http rather than https. Not a great solution, but probably more desirable to you than dropping tor.

I can't edit or add the tracker again anymore, I get the error, "Request to Jackett server failed".

**Comment by ilike2burnthing** [comment]
That's most likely because Jackett isn't running. If it is, restart it and refresh the webpage.

**Comment by googleitffs** [comment]
> That's most likely because Jackett isn't running. If it is, restart it and refresh the webpage.

I tried restarting - didn't help.

**Comment by ilike2burnthing** [comment]
Does the webpage load at all? Did you change any settings in Jackett? Have you tried with and without tor?

**Comment by googleitffs** [comment]
> Does the webpage load at all? Did you change any settings in Jackett? Have you tried with and without tor?

The site loads fine with tor, I didn't change any settings. 

Now I tried adding the indexer again without tor, and there's this capcha you need to solve, but the capcha doesn't load. I still managed to add the indexer, tried "http" this time, but it didn't help.

**Comment by ilike2burnthing** [comment]
The captcha only appears if you've had a failed login attempt.

If the issue only occurs when using tor then the solution is to just not use tor for that indexer. I'm not familiar enough with tor to troubleshoot unfortunately.

I'll close this issue, but if you find a solution, feel free to comment in case others have the same issue.
