### ISSUE TITLE
[feature request] Download several torrents at once

### ISSUE THREAD

**Issue by tchirou** [Jackett/Jackett#11102]
Hi
I searched in the issues but I couldn’t find this request
Would it be possible to consider adding checkboxes to download several results at once ? 
Thanks a lot

**Comment by tchirou** [comment]
Got your answer on the other post
Thanks

**Comment by ilike2burnthing** [comment]
For future readers - https://github.com/Jackett/Jackett/issues/11098#issuecomment-779380032
