### ISSUE TITLE
Error loading Jackett settings, request to Jackett server failed is server running>

### ISSUE THREAD

**Issue by valgert** [Jackett/Jackett#11108]
Hello,

FreeBSD 12.1-release-p12
Mono-6.8.0.105
Jackett v0.17.546
0.16.2142
Tested with and without vpn

Classic jail in TrueNAS with port forwarding in NAT. Further routing goes through VM pfSense in Proxmox.
Bypass pfssense also gave no results.
A couple of times it turned out to get around the error Ctrl+Shift+P, after which the error returns forever.
Perhaps someone has built a similar configuration and knows where to look.

Log file: [log.txt](https://github.com/Jackett/Jackett/files/5989040/log.txt)

**Comment by ilike2burnthing** [comment]
No experience using TrueNAS, so all I can offer is the generic, 'backup anything you need, and try a clean install'. Hopefully someone (or searching past issues) can give you something more constructive.

**Comment by ilike2burnthing** [comment]
May be relevant - https://github.com/Jackett/Jackett/issues/7349#issuecomment-749461490
