### ISSUE TITLE
RuTor: add IMDB support

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#11107]
Could you please implement IMDB IDs support for the RuTor indexer? For example:
http://rutor.info/search/0/0/010/0/tt10288566
http://rutor.is/search/0/0/010/0/tt9016974

**Comment by ilike2burnthing** [comment]
As far as I can tell, this would require https://github.com/Jackett/Jackett/issues/3388.

I'll try looking at it again later to see if I can find a way round it (or if anyone else wants to, feel free).

**Comment by garfield69** [comment]
v0.20.1043

**Comment by garfield69** [comment]
Note: this really only applies to Radarr or manual movie searches with the imdb tt number as a query.
The tv imdb is globally disabled on jackett so Sonarr does not get to see imdbid as a caps, but if this does ever get enabled, then the yaml logic I coded for this indexer with the current cardigann conditionals, will not support a tv search using a combination of imdbid and season/episode.
