### ISSUE TITLE
How get number version installed without access on api

### ISSUE THREAD

**Issue by ricain59** [Jackett/Jackett#11110]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: last

**Last Working Jackett Version**: last

**Are you using a proxy or VPN?** [yes/no]

### Description

Hi,

I am not member for access api of jackett, but it's possible with get/post or other get the number version installed?

Thank you

**Comment by ilike2burnthing** [comment]
What's the purpose of this?

**Comment by ricain59** [comment]
Hi,

The purpose is check new update. I check version local vs version on github.

Thank you.

**Comment by ilike2burnthing** [comment]
Why can't you enable updates in Jackett?

**Comment by ricain59** [comment]
It's possible on docker ?

**Comment by ilike2burnthing** [comment]
Yea, though personally I use Watchtower to update on Docker - https://hub.docker.com/r/containrrr/watchtower

Let me know if that solves things for you.

**Comment by ricain59** [comment]
Hi, 

The watchtower it's fine, but i prefer done update manually. If it's possible get current version from an url it's fine, example: http://jacket:9117/version

**Comment by ilike2burnthing** [comment]
https://containrrr.dev/watchtower/arguments/#without_updating_containers
and
https://containrrr.dev/watchtower/notifications/
