### ISSUE TITLE
[yggcookie] Exception (yggcookie): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [Jackett/Jackett#11114]
Hi, my main indexer now needs FlareSolverr, but I'm on Raspberry Pi (arm). It looks like Flaresolverr is not available on ARM, so my installation is now completely stuck. Is there a way to get an ARM build somewhere ?

Thanks in advance.

**Comment by ilike2burnthing** [comment]
ARM support is available through Docker - https://github.com/FlareSolverr/FlareSolverr#docker

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> ARM support is available through Docker - https://github.com/FlareSolverr/FlareSolverr#docker

I don't use Docker. Is there no way to use it natively without Docker ?

**Comment by ilike2burnthing** [comment]
Not to my knowledge, though you'll get a clearer answer over on FlareSolverr.
