### ISSUE TITLE
[solidtorrents] The SSL connection could not be established, see inner exception.: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. (Config)

### ISSUE THREAD

**Issue by NomaanMalick** [Jackett/Jackett#11121]

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#an-error-occurred-while-sending-the-request-error-trustfailure-ssl-errorssl-routinesopenssl_internalcertificate_verify_failed
