### ISSUE TITLE
[SemeandoCC] new private tracker

### ISSUE THREAD

**Issue by helperman** [Jackett/Jackett#11133]
Please add a new tracker: https://semeando.cc/torrents

Semeando is a Private Torrent Tracker for e-Learning Courses and e-books.

**Comment by garfield69** [comment]
registration is closed. invitations only.
If you send an invite to garfieldsixtynine -at- gmail.com I will add this indexer to Jackett.

notes to self: 
judging from login page the site appears to be using a UNIT3D engine.
language: PT

**Comment by helperman** [comment]
You check messages too late.
When I posted the message registration was opened for everyone.

**Comment by garfield69** [comment]
c'est la vie
I went on holiday at the start of the week you posted, and I'm only now working through the backlog.

Unit3D is very standard, so I can easily create an indexer for this web site with your help.
All I need is for you to provide an HTML dump of the site's **torrent search** page, by following the instructions at https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

Also useful is if you read the rules/faq and find any Hit&Run or download rules, such as the minimum seed ratio the site expects you to keep, and the minimum seed time (usually in hours or days) that you are expected to seed a download.

Cheers.

**Comment by garfield69** [comment]
https://semeando.cc/ returning DNS_PROBE_FINISHED_NXDOMAIN
is there a new domain or is the site gone or broken?

**Comment by ilike2burnthing** [comment]
https://semeando.cc/ - ERR_CONNECTION_REFUSED
https://semeando.cc/ - redirects to https://brsociety.club/

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/12233
