### ISSUE TITLE
FlareSolverr always gives a cookie error

### ISSUE THREAD

**Issue by Lily971** [Jackett/Jackett#11132]
### Environment

**OS**: Windows 10 Pro

**Jackett Version**: 0.17.562

**FlareSolverr Version**: 1.2.3 running on Docker

**Are you using a proxy or VPN?** No

### Description

FlareSolverr always shows a cookie error for any indexers that has Cloudflare detection

![image](https://user-images.githubusercontent.com/48997987/108421879-2f14d300-720c-11eb-88cd-6429edef2ce9.png)

**Comment by garfield69** [comment]
please raise this ticket on the flaresolverr support https://github.com/FlareSolverr/FlareSolverr/issues, this site is for Jackett. Thanks.
