### ISSUE TITLE
Trackers missing from tracker list

### ISSUE THREAD

**Issue by rsgabriel** [Jackett/Jackett#1114]
I just updated to the latest version of Jackett using the windows installers on the releases page.

When I select "Add Tracker" I only see a list of 27 trackers and not the 300+ that are supported by Jackett.

How can I add these trackers not in the list of 27 to jackett?

Seems to be some kind of UI/UX issue

**Comment by kaso17** [comment]
Please post the log showing the startup of jackett

**Comment by rsgabriel** [comment]
Log here:

http://pastebin.com/vzJk7bbZ

When I select "Add" these are the only trackers I see:

http://imgur.com/a/wmNl5

...is there supposed to be some kind of pagination or search function for trackers that is missing?

there does not seem to be any other UI options for this:

http://imgur.com/a/UainX

**Comment by kaso17** [comment]
You're running an ancient version and the update process doesn't seem to work. Can you please post the update.txt log file too?

**Comment by rsgabriel** [comment]
http://pastebin.com/jRxaPYd1

If I do an uninstall and re-install of the latest, will my currently added trackers be preserved through this process?

**Comment by kaso17** [comment]
Very odd, please try to manually reinstall jackett (deinstalling should keep your settings)

**Comment by rsgabriel** [comment]
Uninstalled Jacket from the Programs applet, it correctly showed the current 1084 version and removed from the list...  I saw an error in the console that said the service was already stopped. Suspicious I saw  Jackett was still running after uninstallation.

Upon closer inspection, I saw in services.msc that one of two services named Jackett was running, specifically the exe for the running service was: C:\Windows\system32\nssm.exe

I now recall setting up the jackett service manually (perhaps when this wasn't automated by the installer) which allowed me to remove the service with nssm.

That said, after installation of the new Jackett I've lost my configuration and was not able to locate it among the files in the old service directory. 

Can you recommend a way for me to migrate to the new version?

Thanks for all your help on this.

**Comment by rsgabriel** [comment]
Oddly I see my api key has not changed

Additionally, clicking "add indexer" does nothing in the UI.

Here is the latest log.txt from the new install

**Comment by rsgabriel** [comment]
I enabled enhanced logging and after the redirect I saw my indexers populate. I was able to use the Test All button to confirm all are working. 

The add indexer button is now working also and I am able to search and add trackers from the expanded list.

Thank you, okay to close.

**Comment by kaso17** [comment]
Probably was a browser caching issue
