### ISSUE TITLE
[btdb] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by landim** [Jackett/Jackett#11147]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: diet v6.33.3

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono

**.Net Version**: 6.12.0.107

**Jackett Version**: v0.17.354

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] NO

### Description

After adding BTDB as tracker, the test fails for it

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Working ok here. If other indexers are working, and another test for BTDB fails, please provide an **enhanced** log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
