### ISSUE TITLE
[TeamHD] Login failed, got redirected (Config)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#11159]
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: v0.17.570

**Last Working Jackett Version**: Not sure

**Are you using a proxy or VPN?**No

### Description
Unable to configure TeamHD

### Logged Error Messages
`Login Failed, got redirected.`
[log.txt](https://github.com/Jackett/Jackett/files/6027475/log.txt)

### Screenshots
Not required

@garfield69 I realize you don't have access to this tracker, so I'm not sure whether you'll be able to help.

**Comment by garfield69** [comment]
Sorry cannot help. The indexer is using the cookie method, so clearly the session cookie is not being accepted by the web site. There is nothing in the logs I can see that helps determine why it was rejected.

**Comment by waldens** [comment]
This issue can be closed. Check #6970.
