### ISSUE TITLE
[anidex] Add option for Spanish and Latam combined

### ISSUE THREAD

**Issue by viseniv** [Jackett/Jackett#11155]
Add an option on languages to search on Spanish and Spansish LATAM combined

**Comment by garfield69** [comment]
essentially the indexer would have to generate 
```
https://anidex.info/?q=&s=upload_timestamp&o=desc&lang_id=29,15&group_id=0
```
which should be doable , but the indexer config menu would need to be changed to allow multi-selection.
This requires a C# dev to volunteer.

**Comment by XYZJR** [comment]
I've added a PR.
The selected languages are used to perform search queries, however, the search result titles don't always show which languages they're in. We could probably fetch this from the AniDex web result. Should we add the language to the release title as a tag, such as [English] or [Arabic]?

**Comment by garfield69** [comment]
v0.17.882
