### ISSUE TITLE
All trackers failing tests

### ISSUE THREAD

**Issue by thejacer87** [Jackett/Jackett#1115]
Just today sonarr stopped being able to find any releases. Tracked it down to Jackett failing to talk to my trackers.

Jackett version:  0.7.1079.0
Mono version (if not using Windows):  
```
$ mono --version
Mono JIT compiler version 4.8.0 (Stable 4.8.0.495/e4a3cf3 Wed Feb 22 18:30:58 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

[log.20170226.00000.txt](https://github.com/Jackett/Jackett/files/802854/log.20170226.00000.txt)
[log.20170226.00001.txt](https://github.com/Jackett/Jackett/files/802855/log.20170226.00001.txt)
[log.20170226.00002.txt](https://github.com/Jackett/Jackett/files/802856/log.20170226.00002.txt)
[log.20170226.00003.txt](https://github.com/Jackett/Jackett/files/802857/log.20170226.00003.txt)
[log.20170226.00004.txt](https://github.com/Jackett/Jackett/files/802858/log.20170226.00004.txt)

**Comment by kaso17** [comment]
From the log:
2017-02-26 21:58:32.0266 Error The ca-certificates-mono package is not installed, HTTPS trackers won't work. Please install it.

**Comment by thejacer87** [comment]
so i installed with `apt-get install ca-certificates-mono`. no issues. But when i restarted the server, it still failed, with a different message (in the webUI). Something along the lines of bad uri format. I'm just confused as jackett was working just fine with all these trackers
[log.txt](https://github.com/Jackett/Jackett/files/804751/log.txt)
[log1.txt](https://github.com/Jackett/Jackett/files/804750/log1.txt)

**Comment by kaso17** [comment]
the logs still show TLS errors.
The last entry is from 2017-02-27 06:49:07.9791
 is that correct?

**Comment by thejacer87** [comment]
ah probably not. sorry i forgot to do this in the morning when i was still home, i ssh'd into my server to get the log, but it must have been the wrong one... it'll have to wait til i get home. thanks for the help

**Comment by thejacer87** [comment]
k so i got home and jackett seems to have removed 2 of 4 of my trackers. both still failing
[log.txt](https://github.com/Jackett/Jackett/files/805462/log.txt)

**Comment by kaso17** [comment]
please update to the latest version.
0.7.1079.0  with mono 4.8 is broken

**Comment by thejacer87** [comment]
yep, looks like updating worked.
thanks
