### ISSUE TITLE
Echec de connexion. Vérifiez vos identifiants. Login error

### ISSUE THREAD

**Issue by VadeInPace** [Jackett/Jackett#11169]
### Environment

**OS**: Linux Opensuse Leap 15.2 MATE desktop
Browser: Firefox 78.0.2esr 64bit
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] ????
**.Net Version**: I thing NO ???
**Jackett Version**: ???
**Last Working Jackett Version**: ???
**Are you using a proxy or VPN?** NO

### Description
Sorry this is my first issue log. Please be indulgent, Thanks.
I try this 2 days ago and still the same.
Connected to https://yggtorrent.li , click on "S'identifer" up right. A small window pop up where I can enter my user name and password. After that, I click "CONNEXION" and an error message in red appears "Echec de connexion. Vérifiez vos identifiants."

### Logged Error Messages
[Place any relevant error messages you noticed from the logs here.]
I can't find how to get a log
Echec de connexion. Vérifiez vos identifiants.

### Screenshots

![Screenshot at 2021-02-24 18-50-13](https://user-images.githubusercontent.com/49396694/109050724-9e3d6c00-76d1-11eb-9e06-af7af958d04f.png)

**Comment by garfield69** [comment]
You have opened a ticket are on the wrong support site. 
This site is for the Jackett app, and issues related to that app only.
It is not a support site for the YGGTorrent web site, or a general help forum for problems with Linux, Firefox, or login problems.
Please look elsewhere.
