### ISSUE TITLE
Fix release year of re-release albums in rutracker.org

### ISSUE THREAD

**Issue by Mrpink200** [Jackett/Jackett#11161]
**Environment**

OS: Docker Linux
.Net Runtime: ?
.Net Version: ?? i use the https://registry.hub.docker.com/r/linuxserver/jackett/ version dev
Jackett Version: v0.17.580
Last Working Jackett Version: v0.17.580
Are you using a proxy or VPN? No

**Description**

Lots of reissued albums, especially in high raised are tagged with the initial album years in four digits  / the re release years.
On of the most usefull trackers for thoses releases are rutracker.org

For example :
[TR24][OF][192kHz] Aerosmith - Pump - 1989/2014 (Hard Rock)

Is now fixed with release v0.17.580 to 
Aerosmith - Pump - 1989/2014 [TR24][OF][192kHz] (Hard Rock)
but lidarr still says  : wrong album

My idea would be to add an option in the rutracker.org torent setup to to replace the years format 4digits/4digits to 4digits only.
I guess that this change would only impact release files.

The result would be :
Aerosmith - Pump - 1989 [TR24][OF][192kHz] (Hard Rock)

and it would fix the search

**Comment by ilike2burnthing** [comment]
What would work better?
- Aerosmith - Pump - 1989
- Aerosmith - Pump - 1989 (Remastered)
- Aerosmith - Pump - 2014

Or would some altered combination like `Aerosmith - Pump - 1989 (Remastered 2014)` work with Lidarr?

**Comment by Mrpink200** [comment]
For me 
Aerosmith - Pump - 1989
Aerosmith - Pump - 1989 (Remastered)

i do not know if lidarr would accept a second 4 digit between ( ) 
I suggest 
Aerosmith - Pump - 1989 (Remastered)
to be 50/50 between lidarr working and providing extra information about the release

**Comment by ilike2burnthing** [comment]
I'm assuming most if not all rereleases listed this way are remasters rather than special editions or something similar.

@XYZJR wanna do a follow up?

**Comment by XYZJR** [comment]
Can we get one of the Lidarr devs to comment on this? Are we certain this would fix the problem for Lidarr?

**Comment by Mrpink200** [comment]
@ta264 : Could you have a look

**Comment by Mrpink200** [comment]
Could you move forward without lidarr team confirmation. ?

**Comment by Mrpink200** [comment]
i also found the same kind of release types with space 👍

**Comment by ilike2burnthing** [comment]
@Qstick could you advise?

**Comment by Mrpink200** [comment]
@ilike2burnthing as lidarr team seems busy on other topics, could it be possible to add it on a nightly build and i could confirm the fix within 24hours

**Comment by ilike2burnthing** [comment]
I'll leave that up to @XYZJR as they'll be the one putting in the time and effort.

**Comment by XYZJR** [comment]
I'm of the opinion that if we're adding functionality to Jackett specifically for Lidarr (or any other program that uses Jackett's output) that we should be certain that what we're doing is the correct answer for the problem. Having someone of their team confirm our guesswork as being a helpful fix would give me more confidence in this solution instead of it feeling like we're trying to patch things up as they come.

I might be able to work on this tonight, but I'm not certain of the requirements. Is it the second year in the release title that has to be moved, or removed, or replaced with (Remastered)? Can someone link me their 'album title recognition' code? I might be able to find the answer I'm looking for there.

**Comment by ilike2burnthing** [comment]
Bit of a (uneducated) guess - https://github.com/lidarr/Lidarr/blob/develop/src/NzbDrone.Core/IndexerSearch/Definitions/AlbumSearchCriteria.cs

Seems they already do some handling of rutracker oddities (pretty sure that's for files though, not search results) - https://github.com/lidarr/Lidarr/blob/develop/src/NzbDrone.Core/Parser/Parser.cs

**Comment by Qstick** [comment]
I'll try and have a look at this later today or tomorrow.

**Comment by Mrpink200** [comment]
Hi. Have you been able to have a look ?

**Comment by Mrpink200** [comment]
no updates :(

**Comment by ta264** [comment]
We have added a `!parse` command to our [discord server](https://lidarr.audio/discord).  For example you can run 
```
!parse lidarr "Aerosmith - Pump - 1989 (Remastered)"
```
and get back
```
Lidarr Parse Result
Attempted Release Title
Aerosmith - Pump - 1989 (Remastered)
Artist Name
Aerosmith
Album Title
Pump
Release Date
1989
Discography
False
Quality
Unknown
Proper
-
Real
-
Repack
-
Release Group
-
Lidarr Version 0.8.0.2075 | Branch Nightly
```

Hopefully that will allow you to do the testing yourself @Mrpink200 

A quick test suggests `Aerosmith - Pump - 1989 [TR24][OF][192kHz] (Hard Rock)` should work.  At the moment we don't detect TR24 as flac so the quality comes as unknown, but eg `Aerosmith - Pump - 1989 [FLAC][OF][192kHz] (Hard Rock)` parses correctly.

It's still not quite clear to me why TR24 is flac...

**Comment by Mrpink200** [comment]
!parse lidarr "Aerosmith - Pump - 1989/2014 [TR24][OF][192kHz] (Hard Rock)"

```
Lidarr Parse Result
Attempted Release Title
Aerosmith - Pump - 1989/2014 [TR24][OF][192kHz] (Hard Rock)
Artist Name
Aerosmith
Album Title
Pump - 1989/2014
Release Date
0
Discography
False
Quality
Unknown
Proper
-
Real
-
Repack
-
Release Group
-
Lidarr Version 0.8.0.2075 | Branch Nightly
```

=> it confirmas it s not taking the right release year

**Comment by ilike2burnthing** [comment]
I'm not on Discord at the moment, could you try `Aerosmith - Pump - 1989 (Remastered 2014)` as well?

**Comment by Mrpink200** [comment]
just did it :) it fails, it shows 2014 as release date

**Comment by Mrpink200** [comment]
i m afraid, ont 4 digit is accepted per release

**Comment by Mrpink200** [comment]
"ta264: 
I think it's unlikely lidarr will ever care about whether / which remaster it is
it's just trying to find the musicbrainz release group
all the pump versions are lumped together
I'd suggest it would be good to add remaster to the title so you could set a release profile to favour remasters if you want
definitely keep the [TR24][...]"

**Comment by Mrpink200** [comment]
@XYZJR , do you have the time to apply the gix now that we agree what to fo ?

**Comment by XYZJR** [comment]
As I read it, if we find a second year in the release title, we remove it and add "(remastered)" to the end?

**Comment by Mrpink200** [comment]
Yes ! :)

**Comment by XYZJR** [comment]
What should happen with `Mad Season  - LP  - 1995 / 2015, 2016, FLAC  (Alternative Rock, Blues Rock)[6LP][24/192](Pearl Jam + Alice In Chains + Screaming Trees)(image+.cue)`? This looks like a discography, but I'm not sure. [Here's its link.](https://rutracker.org/forum/viewtopic.php?t=5199959)

**Comment by ilike2burnthing** [comment]
This seems to be an outlier, so I'd just ignore it. All(?) other collections list the start and end date (e.g. 1973-1992) - search `Коллекция` to see other examples.

I'm not sure what Lidarr's criteria is for detecting discographies, though the [link](https://github.com/lidarr/Lidarr/blob/develop/src/NzbDrone.Core/Parser/Parser.cs) from earlier might help. Doesn't look like `Коллекция` is included. @Qstick / @ta264 would that need to be added to Lidarr rather than translated by the indexer?

**Comment by Mrpink200** [comment]
From a user pount of view, using lidarr for full discographies is really tricky as there s absolutely non standard in the releases names. If i m looking for somexsometimes i go on a simple manual search in jackett

**Comment by Mrpink200** [comment]
Even renaming i use musicbrainz. Lidarr is perfect to search single albums, minitors new releases and really great upgrading qualities in the release

**Comment by Mrpink200** [comment]
any nightly build on its way to test the option ? 👍

**Comment by Qstick** [comment]
> This seems to be an outlier, so I'd just ignore it. All(?) other collections list the start and end date (e.g. 1973-1992) - search `Коллекция` to see other examples.
> 
> I'm not sure what Lidarr's criteria is for detecting discographies, though the [link](https://github.com/lidarr/Lidarr/blob/develop/src/NzbDrone.Core/Parser/Parser.cs) from earlier might help. Doesn't look like `Коллекция` is included. @Qstick / @ta264 would that need to be added to Lidarr rather than translated by the indexer?

Sorry, been a bit tied up last week and have not really had an opportunity to look at this. Will see if I can make some time.

**Comment by garfield69** [comment]
v0.17.699
