### ISSUE TITLE
[TorrenTech] The SSL connection could not be established, see inner exception

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#11160]
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 

**Last Working Jackett Version**: 0.17.570

**Are you using a proxy or VPN?**: No

### Description

I am unable to configure TorrenTech. It seems like a certificate issue.

### Logged Error Messages

`The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject] O=Internet Widgits Pty Ltd, S=Some-State, C=AU [Issuer] O=Internet Widgits Pty Ltd, S=Some-State, C=AU [Serial Number] 4ECAE2A3C18B89C829BB31E9AA53F5085BAF78DD [Not Before] 1/14/2021 2:35:22 AM [Not After] 1/14/2022 2:35:22 AM [Thumbprint] 22E3C9896A1207EFF97599FE12B9DBB2AF8EC0CA` 

[log.txt](https://github.com/Jackett/Jackett/files/6027445/log.txt)

### Screenshots
No needed

**Comment by ilike2burnthing** [comment]
Welcome back @kaso17!

**Comment by ilike2burnthing** [comment]
[v0.18.155](https://github.com/Jackett/Jackett/releases/tag/v0.18.155)

**Comment by talondnb** [comment]
Exception (torrentech): error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure: The SSL connection could not be established, see inner exception.

I'm getting this issue again, anyone else?
