### ISSUE TITLE
Unable to run on MacOS

### ISSUE THREAD

**Issue by 0ghj04hjyg9045** [Jackett/Jackett#11179]
I wanted to install Jackett, install_service_macos said completed but it seems like it's not running

**OS**: MacOS Sierra

**Jackett Version**: v0.17.584

### Description

I wanted to install Jackett, install_service_macos said completed but it seems like it's not running

### Logged Error Messages

`MacOS-Server:~ macbook$ /Applications/Jackett/install_service_macos ; exit;
Removing Jackett executable and all .dylib and .dll files from quarantine...
Agent successfully installed and running!
Jackett location: /Applications/Jackett
Jackett agent:
	path = /Users/macbook/Library/LaunchAgents/org.user.Jackett.plist
	state = running
	working directory = /Applications/Jackett
	pid = 78371
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.`

When manually trying to run Jackett:

`MacOS-Server:~ macbook$ /Applications/Jackett/jackett ; exit;
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libSystem.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibSystem.Native, 1): image not found
   at Interop.Sys.IsATty(SafeFileHandle fd)
   at System.Console.<get_IsOutputRedirected>g__EnsureInitialized|35_0()
   at System.Console.get_IsOutputRedirected()
   at CommandLine.ParserSettings.GetWindowWidth()
   at CommandLine.ParserSettings..ctor()
   at CommandLine.Parser..ctor(Action`1 configuration)
   at Jackett.Server.Program.Main(String[] args)
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

`

**Comment by garfield69** [comment]
it would appear that your sierra is missing the .NET libraries
try installing from https://dotnet.microsoft.com/download?initial-os=macos then reboot and try jackett again.

**Comment by 0ghj04hjyg9045** [comment]
Thanks, I need MacOS v10.13 for .NET and I'm currently running on v10.12.6. I had an old version of Jackett running but uninstalled it and decided to download the newest version.

**Comment by garfield69** [comment]
how come you installed .NET 3.1, is .NET 5 not available?

**Comment by ilike2burnthing** [comment]
If this is still an issue please comment and reopen.
