### ISSUE TITLE
Film Paleis indexer not working correctly

### ISSUE THREAD

**Issue by timmarinus** [Jackett/Jackett#11170]
Hello,

I tried to connect to Film-Paleis.me private indexer with Jackett. The connection is working and the provided manual is correct.

When i search manually for an serie it works if you only search for a part of the full name.

For example 
Serie and eppisode that i am trying to download is 
Temptation Island Love or Leave S01 E14

When i type the following text in the manual search field: **Temptation Island Love or Leave S01 E14** it displays: No data available in table

When i type the following text in the manual search field: **Temptation Island Love or Leave S01**  it displays: **a list of eppisodes in cluding E14**

i tried different formats with spaces without spaces capitals without capitals you name it, nothing seems to work. 
The issue is exactly the same with Sonarr but i think if the manual search will go as expected Sonarr wil find its way,

The logging From Jackett:

### Environment

**OS**: Synology Docker System

**Jackett Version**: v0.17.584

**Last Working Jackett Version**: New install never worked as exptected

**Are you using a proxy or VPN?** [yes/no] no

### Logged Error Messages

2021-02-24 20:38:43 | Info | Manual search in film-paleis for Temptation Island Love or Leave S01E14 => Found 0 releases
-- | -- | --
2021-02-24 20:38:39 | Info | Manual search in film-paleis for Temptation Island Love or Leave S01 => Found 13 releases
2021-02-24 20:38:34 | Info | Manual search in film-paleis for Temptation Island Love or Leave => Found 13 releases
2021-02-24 20:38:09 | Info | Torznab search in AggregateSearch for Temptation Island Love or Leave S01E14 => Found 0 releases

### Screenshots
![image](https://user-images.githubusercontent.com/50841438/109057507-1dd33700-76e2-11eb-970a-a3b0779e23fa.png)

![image](https://user-images.githubusercontent.com/50841438/109057496-190e8300-76e2-11eb-9bf5-7e839937975e.png)

**Comment by ilike2burnthing** [comment]
The indexer is using an `andmatch` filter to return only those results that have a title which matches the entered keywords (removing irrelevant results). It is also changing the titles after they're found, to be readable by Sonarr/Radarr (e.g. `seizoen 01 aflevering 01` > `S01E01`).

https://github.com/Jackett/Jackett/blob/7c99d0ffe53c57cd20b1c4f6075220e0b2df553a/src/Jackett.Common/Definitions/film-paleis.yml#L89-L103

This means that the naming scheme the tracker is using will cause difficulties when searching using `SxxExx`.

Is the `seizoen xx aflevering xx`/`seizoen xx afl. xx` naming scheme used for all results, or are there are also results which use `SxxExx`? If they use a mix, then unfortunately there's nothing we can change which wouldn't negatively affect other results.

**Comment by timmarinus** [comment]
Hello Thanks for the response, 

as far as i can tell all of the uploaders are using the SxxExx format latley, but it is a community and some people may choose to upload it in a different naming context.
![image](https://user-images.githubusercontent.com/50841438/109394197-0a181280-7926-11eb-8b27-88a4281fc156.png)

Is it possible to change it myself only for my installation, i do not want disrupt other users that maybe use Seizoen xx adl. xx format with the uploaders community. 

Is it not possible to look fist for the current format and if no results have come up that there is a search for the SxxExx format. 

But for my knowledge, for now it is when i type in the search field SxxExx that in the background it is translated to SxxAxx and this is nog visible in the logs?

Thanks in advance

**Comment by ilike2burnthing** [comment]
Download and unzip [film-paleis-alt.zip](https://github.com/Jackett/Jackett/files/6055346/film-paleis-alt.zip).

You should have the volume `/config` mapped for Jackett's container (it has the sub-folder `Jackett` with the logs, config file, indexers, etc.). If not, do so, e.g. `/volume1/Docker/Jackett/config` - not sure about Synology's folder structure, so that might need changing.

Navigate to that folder (for me, that's just via a mapped network drive on my computer), create a sub-folder `cardigann`, and a sub-folder within that one `definitions` (so ultimately, `/config/cardigann/definitions`).

Copy and paste the `film-paleis-alt.yml` file to the `definitions` folder, restart the Jackett container, and add `Film-Paleis Alt` (if it's not available, check the steps above). You can use this along side the normal Film-Paleis indexer.

This means that the following searches will all be translated to `Test seizoen 1 afl 2`:
- Test S01E02
- Test S1E2
- Test S01 E02
- Test S1 E2

(also lowercase `s` and `e` for all of those)

This assumes that searching `afl` on the site also finds results using `aflevering`. If not, one will have to be used, so let me know which is more common.

Based on your screenshot, I also added a fix for results with `seizoen 1 tot 4` (and `t/m` which I'm guessing is the same), changing it to `S1-4` (or any numbers up to 99). I want to add this to the main indexer as well, so if you could test this by searching in Jackett for `het huis anubis` and see if that same 50.43GB result is displayed as `het huis anubis S1-4 *verzoekje*`. Searching for the `3%` result may not work using it's title, so try `2016-2019 1080p NF DD5.1 NL`.

**Comment by timmarinus** [comment]
Thanks for trying,

I followed the steps as sugested but i dont see any difference, Still when i search for test S01E02 an serie with the title on film-paleis.me is displayed as S01E02. But the changes as you sugested is it suppose to translate or is the ALT just taking the input as the search field sugested. 

I tried the searches suggested by you and the results are displayed in the screenshots
![image](https://user-images.githubusercontent.com/50841438/109401577-cb974d80-794f-11eb-9b95-76fad203b3af.png)

![image](https://user-images.githubusercontent.com/50841438/109401579-d05c0180-794f-11eb-9e09-e6790d326220.png)

![image](https://user-images.githubusercontent.com/50841438/109401584-d651e280-794f-11eb-9eda-50e2a273435c.png)

My own searches i tested it with - i selected both the normal and the alt one and exact same results
![image](https://user-images.githubusercontent.com/50841438/109401610-f7b2ce80-794f-11eb-9105-756232e18726.png)

![image](https://user-images.githubusercontent.com/50841438/109401621-fe414600-794f-11eb-818e-8a5c5a2269ad.png)
****

**Comment by ilike2burnthing** [comment]
Good to know the other fix worked at least.

If you search on the site itself, how are results for `Mocro Maffia S03` and `Temptation Island Love or Leave S01` titled?

**Comment by timmarinus** [comment]
In Film-paleis website are this the results
![image](https://user-images.githubusercontent.com/50841438/109402284-f506a800-7954-11eb-9bc6-2b132f581827.png)
![image](https://user-images.githubusercontent.com/50841438/109402286-f8019880-7954-11eb-9a35-e57d591bcd31.png)

I do see that the search results are different on the site then on jackett.

**Comment by ilike2burnthing** [comment]
Unzip [film-paleis-alt.zip](https://github.com/Jackett/Jackett/files/6056377/film-paleis-alt.zip) and replace your current `film-paleis-alt.yml` with this new one, restart the container, and see if that works when searching `Mocro Maffia S03E04`.

If there are still issues, open the file in a text editor such as Notepad, and where you see:
```
  rows:
    selector: table.mainouter
    filters:
      - name: andmatch
```
remove the lines:
```
    filters:
      - name: andmatch
```
Save, restart the container, and test again. That will allow irrelevant results, but if its needed, then obviously something isn't matching up, and I cant really test that without an account, or sending you 50 different zip files.

**Comment by timmarinus** [comment]
Thanks for the new file, but it does not work. I understand that troubleshooting is a bit difficult this way,
I tried without the filter section and then a bunch of results came in to the table but a lot of faulty results. so this is not the way to go. 
I checked for you but it was not possible to create an account so you can test it yourself, but maybe we can contact eachother and can we help each other to fix this issue.

**Comment by ilike2burnthing** [comment]
The part I added was:
```
search:
  keywordsfilters:
    - name: re_replace # S01E02 to seizoen 01 afl 02
      args: ["(?i)\\bS(\\d{2})\\s*E(\\d{2})\\b", "seizoen $1 afl $2"]
    - name: re_replace # S1E2 to seizoen 01 afl 02
      args: ["(?i)\\bS(\\d{1})\\s*E(\\d{1})\\b", "seizoen 0$1 afl 0$2"]
```

You could try changing both `"seizoen $1 afl $2"` to `"- seizoen $1 afl. $2"`, but I wouldn't have thought it needed it.

If that doesn't work, go back to using the last one I sent you and an provide enhanced log for the search `Mocro Maffia S03E04` - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

That will allow me to see what results are actually being retuned by the site.

Sorry, not on Discord at the moment.

**Comment by timmarinus** [comment]
I tried the change, but unfortunately it is not working, 
I tried it again with the orginal file you send and the following log is the result.
I hit the 2 differnt searches with the orginal film-paleis indexer and the ALT version so you can compare.

[log.txt](https://github.com/Jackett/Jackett/files/6059986/log.txt)
![image](https://user-images.githubusercontent.com/50841438/109469566-7dc53700-7a6e-11eb-9f21-df532b084404.png)
![image](https://user-images.githubusercontent.com/50841438/109469581-8158be00-7a6e-11eb-9778-17d4e39751dc.png)

**Comment by timmarinus** [comment]
The end goal is to use this with sonarr, radarr and perhaps lidarr but I thought it was the same as a manual search for testing purposes. Do I deed to provide logs when sonarr runs a search for the Mocro Maffia eppisoedes or is the provided logging enough.

Van: ilike2burnthing <notifications@github.com>
Verzonden: maandag 1 maart 2021 10:06
Aan: Jackett/Jackett <Jackett@noreply.github.com>
CC: timmarinus <tim-zeddam@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Jackett/Jackett] Film Paleis indexer not working correctly (#11170)


Ah kk, I had assumed the andmatch was done before the results were renamed, but apparently not.

If you're only using manual searches in Jackett (not something like Sonarr, which relies on the SxxExx format), you can remove the title filters from the last Alt version:

  fields:

    title:

      selector: a[href^="details.php?id="]

      filters:

        - name: re_replace

          args: ["(?i)seizoen\\s*(\\d{1,2})\\s*(tot|t\/m)\\s*(\\d{1,2}<file://d%7b1,2%7d)/s*(tot|t/m)/s*(/d%7b1,2%7d>)", "S$1-$3"]

        - name: re_replace

          args: ["(?i)(seizoen\\s*)(\\d{1,2}<file://d%7b1,2%7d>)", "S$2"]

        - name: re_replace

          args: ["(?i)(afl.\\s*|aflevering\\s*)(\\d{1,2}<file://d%7b1,2%7d>)", "E$2"]

        - name: re_replace

          args: ["(?i)compleet", "Complete"]

becomes:

  fields:

    title:

      selector: a[href^="details.php?id="]

**Comment by ilike2burnthing** [comment]
The current indexer supports Sonarr, but as you saw the naming scheme is inconsistent on the tracker, so not all results are found when using `SxxExx`.

The Alt version translates `SxxExx` to `seizoen xx afl xx`, however as we just discovered, unless you want irrelevant results to be included, the only option is to not translate `seizoen xx afl xx` back to `SxxExx` for the titles, meaning Sonarr can't use them.

There's a different option, which I think works with andmatch, but you will lose IMDB ID searching (unless https://github.com/Jackett/Jackett/issues/3388 ever gets implemented) - [film-paleis-alt.zip](https://github.com/Jackett/Jackett/files/6060851/film-paleis-alt.zip)

**Comment by timmarinus** [comment]
Thanks for trying a different approach to the issue, but i dont se a change, i tried with the new yaml file
[log.txt](https://github.com/Jackett/Jackett/files/6060989/log.txt)

in the above logfile i ran a manual search to an eppisode and i tried a manual search with sonarr, both no results. If sonarr isnt posible at this thime then we have to let that part go, and i can test with only a manual search function, 

Is the IMDB ID mandatory for use with sonarr? 

Or hopefully the torreting community in The Netherlands will upload in an more standard uniform naming scheme

**Comment by ilike2burnthing** [comment]
If IMDB ID is available, Sonarr and Radarr will use it, if not then they will use the name of the show or film.

Have you tried using Sonarr with the proper indexer?

**Comment by timmarinus** [comment]
Yes i tried using it with the proper indexer but the same results there

**Comment by ilike2burnthing** [comment]
Sorry then, it's just a shortcoming of the tracker. Even if we were able to rename the results, Sonarr still wouldn't import the files as they wouldn't have SxxExx either.

**Comment by garfield69** [comment]
v0.20.1466

**Comment by ilike2burnthing** [comment]
@timmarinus searching by `S01E02` or `S01` now works. Only took me a year... 😉
