### ISSUE TITLE
[New Tracker REQ]Horrible Subs

### ISSUE THREAD

**Issue by robertsm85** [Jackett/Jackett#1117]
Indexer Name:
Horrible Subs

Type:
Anime

Indexer URL:
http://horriblesubs.info/

Indexer Language:
English

Invite:
Unnecessary

**Comment by Eisa-AlAwadhi** [comment]
HorribleSubs torrent indexer is Nyaa.se
However, Sonarr already supports Nyaa but perhaps you use Jackett with a different service.
Then it will make more sense to request Nyaa.se even though Sonarr supports it already.

https://www.nyaa.se/

**Comment by bonny1992** [comment]
I am currently doing Nyaa.se and it kinda works.
My only issue is when the status of the torrent is unknown, the "seeders" and "leechers" cell of the table is just not present.
How can I fix this? Is there any if statement I can run to check if a td with a determined class is present and then return 0 or something else?
@kaso17

**Comment by kaso17** [comment]
You can make fields optional like this:
```
      seeders:
        selector: td:nth-child(5)
        optional: true
```
If you want to have a default use it like this (define it twice), the optional will override the first one if the selector matches:
```yaml
      seeders:
        text: 9999
      seeders:
        selector: td:nth-child(5)
        optional: true
```

**Comment by bonny1992** [comment]
Added Nyaa.se thanks to @kaso17 with #1161

**Comment by kaso17** [comment]
thank you

**Comment by waldnercharles** [comment]
Nyaa has been shut down permanently. Can we reopen this issue?

**Comment by evq** [comment]
I have a indexer definition I'm using with Cardigann if someone wants to test and PR it:
https://github.com/evq/cardigann/blob/master/definitions/horriblesubs.yml

**Comment by kaso17** [comment]
Added with c4caa62f8bdfc0b5f610321a056b196977accc7d, thankk you @evq

**Comment by kevingriffin** [comment]
It seems like it's still not showing up in the pre-release version—does `Jackett.csproj` need to be updated to include the file in the build, as it was here?

https://github.com/Jackett/Jackett/pull/1338/files

**Comment by kaso17** [comment]
yes, it was missing. Fixed with 16c2e5521a111be8cc7e5db4a1fd645b1c0c2aaa

**Comment by ignoremenow** [comment]
When I attempt to add in horriblesubs into sonarr I receive this error message

"No results were returned from your indexer, please check your settings."

When watching the log files for jackett I do see the releases come in though

Just a small chunk of the log
May 09 13:00:2 host mono[20662]: 05-09 13:00:22 Info <div class="release-links monster-hunter-stories-ride-on-31-480p"><table class="release-table" cellpadding="0" border="0" cellspacing="0"><tbody><tr><td class="dl-label"><i>Monster Hunter Stories Ride On - 31 [480p]</i></td><td class="dl-type hs-magnet-link"><span class="dl-link"><a title="Magnet Link" href="magnet:?xt=urn:btih:GIAF2GNEUWA654XDV4TDWGJMCW7252WW&amp;tr=udp://tracker.coppersurfer.tk:6969/announce&amp;tr=udp://tracker.internetwarriors.net:1337/announce&amp;tr=udp://tracker.leechers-paradise.org:6969/announce&amp;tr=http://tracker.internetwarriors.net:1337/announce&amp;tr=udp://tracker.opentrackr.org:1337/announce&amp;tr=http://tracker.opentrackr.org:1337/announce&amp;tr=udp://tracker.zer0day.to:1337/announce&amp;tr=udp://tracker.pirateparty.gr:6969/announce&amp;tr=http://explodie.org:6969/announce&amp;tr=http://p4p.arenabg.com:1337/announce&amp;tr=http://mgtracker.org:6969/announce">Magnet</a></span></td><td class="linkless dl-type hs-torrent-link">Torrent</td><td class="dl-type hs-ddl-link"><span class="dl-link"><a title="Download from FileFactory" href="http://www.filefactory.com/file/48z9zel8dptz">FF</a></span></td><td class="dl-type hs-ddl-link"><span class="dl-link"><a title="Download from Uploaded.net" href="http://uploaded.net/file/acgv1nnz">UL</a></span></td><td class="dl-type hs-ddl-link"><span class="dl-link"><a title="Download from UploadRocket.net" href="http://uploadrocket.net/0azi175r9hn3">UR</a></span></td></tr></tbody></table></div>
May 09 13:00:22 host mono[20662]: 05-09 13:00:22 Info <table class="release-info" cellpadding="0" border="0" cellspacing="0"><tbody><tr id="monster-hunter-stories-ride-on-31" data-currentdisplay=""><td class="rls-label">(05/06) <a title="See all releases for this show" href="/shows/monster-hunter-stories-ride-on">Monster Hunter Stories Ride On</a> - 31</td><td class="linkful res-label link-480p" id="monster-hunter-stories-ride-on-31-480p"><span class="res-link"><a href="#">480p</a></span></td><td class="linkful res-label link-720p" id="monster-hunter-stories-ride-on-31-720p"><span class="res-link"><a href="#">720p</a></span></td><td class="linkful res-label link-1080p" id="monster-hunter-stories-ride-on-31-1080p"><span class="res-link"><a href="#">1080p</a></span></td></tr></tbody></table>
May 09 13:00:22 host mono[20662]: 05-09 13:00:22 Info Found 59 (0 new) releases from Horrible Subs

**Comment by au5ton** [comment]
I am also getting what @ignoremenow has and that's why I'm here. I'm not sure if this is a bug with Sonarr or Jackett. I would think Jackett because a size isn't being provided or is being incorrectly provided. Could you please reopen this issue?

**Comment by RadBrad87** [comment]
As a workaround, is it possible for Jacket to give some bullshit size value to Sonarr?

**Comment by au5ton** [comment]
I agree with @RadBrad87. I think this is what SickRage uses. (Don't quote me on that.)
