### ISSUE TITLE
[REQ] The Leach zone

### ISSUE THREAD

**Issue by Blurple3333** [Jackett/Jackett#11185]
https://tlz.digital/index.php
private : a registered account is required to access site.

I am the owner of this site and many people are requesting jackett could not find any info on how to do this so here i am lol 
Blue
Bluedeath2013.ca@gmail .com

**Comment by garfield69** [comment]
v0.17.598

**Comment by garfield69** [comment]
site is online but accessing the torrents page generates a timeout https://tlz.digital/browse.php

**Comment by Blurple3333** [comment]
Fixed was a server issue thanks .

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/11185#issuecomment-1666950073

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
TLZ -> unit3d on new domain https://tlzdigital.com/

**Comment by garfield69** [comment]
v0.21.2628

**Comment by garfield69** [comment]
https://tlzdigital.com/ > TCP Connection Failed (Timed out)

**Comment by Blurple3333** [comment]
was some weird OHV lack of notifying me of server contract all is good now .

**Comment by garfield69** [comment]
online
