### ISSUE TITLE
[lesaloon] Exception (lesaloon): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by dan3805** [Jackett/Jackett#11186]
the saloon now uses cloudflare, since that day it seems that the connection is no longer possible

<img width="431" alt="Capture d’écran, le 2021-02-27 à 18 20 16" src="https://user-images.githubusercontent.com/35934387/109403001-86135a00-7928-11eb-85ee-783769fa277d.png">

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
