### ISSUE TITLE
[bluebird-hd] Add IMDB support

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#11198]
Please consider to implement IMDB IDs support for the BlueBird-HD indexer? 
For example: https://bluebird-hd.org/browse.php?dsearch=tt5363618

**Comment by garfield69** [comment]
The site registration is still set to invite only.
If you send an invite to garfieldsixtynine -at- gmail.com I can complete this request.

**Comment by garfield69** [comment]
v0.21.1025
