### ISSUE TITLE
[New Tracker REQ] CZTeam

### ISSUE THREAD

**Issue by vulpasin** [Jackett/Jackett#1119]
Please add new tracker CZTeam https://czteam.club/

Thank you

**Comment by armani316** [comment]
@vulpasin Looks like an invite is required? Would you be able to send an invite if a team member is willing to add this tracker?

**Comment by vulpasin** [comment]
Yes, i can send an invite. I need an email adress.

Thank you.

**Comment by kaso17** [comment]
please send it to kaso1717 -at- gmail.com

**Comment by vulpasin** [comment]
I send invitation.

The Tracker is very old and it has been down for 4-5 months. 
Now they get it back online.

![image](https://cloud.githubusercontent.com/assets/17246066/23394040/65f3e104-fd8f-11e6-85ad-b14c62fe3523.png)

**Comment by kaso17** [comment]
got it, thank you

**Comment by kaso17** [comment]
added with f8686d0c02e6283359a53aa0af27c2061376b5d6
Unfortunately I couldn't use the gazelle API as they don't include the category in the output

**Comment by kaso17** [comment]
removed (tracker shutdown according to http://torrentinvites.org/f36/czteam-club-general-2017-review-226056/)
