### ISSUE TITLE
Periodically cleanup broken trackers

### ISSUE THREAD

**Issue by sirinath** [Jackett/Jackett#11193]
With update periodically clean up broken non functioning trackers.

**Comment by garfield69** [comment]
We regularly test all public and semi-private indexers, and after 30 days of downtime they are removed from Jackett.
Private trackers are a different set, as only a few of them have team members have accounts and can login with Jackett to test.
For the rest we rely on feedback from users to highlight issues.

Are you speaking generally, or do you have a list of indexers in mind that you want us to look at?

**Comment by sirinath** [comment]
I am speaking generally about public trackers. Many of them regularly fail tests. So was wondering if there many outdated trackers.

**Comment by ilike2burnthing** [comment]
Last thorough review was https://github.com/Jackett/Jackett/issues/10586 in December. Last quick test by me was two days ago.

All currently known down trackers are here - https://github.com/Jackett/Jackett/labels/Down%20%2F%20Waiting%20for%20removal

If the trackers themselves are down (you've checked in browser, not just Jackett), let us know which ones.

If the trackers are up, your Jackett is up to date, but you're having issues with them in Jackett, check [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for a solution. If you still have problems, let us know.
