### ISSUE TITLE
Torznab search queries in logs no longer present

### ISSUE THREAD

**Issue by agneevX** [Jackett/Jackett#11195]
### Environment

**OS**: `Ubuntu 20.04`
**.Net Runtime**: `.Net-Core`
**.Net Version**: `?`
**Jackett Version**: `0.17.598`
**Last Working Jackett Version**: `?`
**Proxy or VPN?** : `Not Present`

### Description

A couple of versions before, the search query for torznab searches would be printed in non-debug logs which made it very helpful in diagnosing issues like disparity of search results.

It would be nice if this feature was brought back, as I'm at a loss as to why Radarr shows less search results than a similar search on the indexer's website. 

### Logged Error Messages

N/A

### Screenshots

N/A

**Comment by garfield69** [comment]
the torznab search query will only be posted in enhanced jackett logs.
the removal from the non-debug logs was deliberate and will not be restored in future releases.

**Comment by agneevX** [comment]
Right, so for one extremely simple line of query, one must scour through hundreds of obfuscated lines of log?

**Comment by agneevX** [comment]
Can you at least link me to the commit?

**Comment by garfield69** [comment]
>Can you at least link me to the commit?

Nope. That involves hours of my time looking back into github change history for a line of code I don't even know where its lives.
I'm not a C# dev, and did not make that particular change. I would ask @ngosang (the author of the change) about it, except he has not been available recently so you are not going to get a quick turn around on this request.
