### ISSUE TITLE
[blutopia] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by batuhankrmn** [Jackett/Jackett#11202]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows10 Home

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 3.5

**Jackett Version**: Jackett Version v0.17.605

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description  

When I test this tracker, I get "An error occurred while testing this indexer
Found no results while trying to browse this tracker" It was working before.

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 312
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 147
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61

CardigannIndexer (blutopia): Error while parsing row '
<tr>
	<td style="width: 1%;">
		<div class="torrent-poster pull-left"></div>
	</td>
	<td style="width: 1%;">
		<a href="https://blutopia.xyz/categories/2">
			<div class="text-center">
				<img src="https://blutopia.xyz/files/img/category-5e1ce662c84e1.png" data-toggle="tooltip" data-original-title="TV Show torrent" style="padding-top: 10px;" alt="TV Show">
			</div>
		</a>
	</td>
	<td style="width: 1%;">
		<div class="text-center" style="padding-top: 15px;">
			<span class="label label-success" data-toggle="tooltip" data-original-title="Type">
				Encode
			</span>
		</div>
		<div class="text-center" style="padding-top: 8px;">
			<span class="label label-success" data-toggle="tooltip" data-original-title="Resolution">
				720p
			</span>
		</div>
	</td>
	<td>
		<a class="text-bright" style="font-size: 16px;" href="https://blutopia.xyz/torrents/17485">
			Steins;Gate 0 - E18 720p 10-bit WEB Dual-Audio AAC2.0 x264-LostYears
		</a>
		<br>
		<span class="badge-extra">
			<i class="fas fa-upload" data-toggle="tooltip" data-original-title="Uploader"></i>
			<a href="https://blutopia.xyz/users/Rukus">
				Rukus
			</a>
		</span>
		<span class="badge-extra">
			<span class="text-gold movie-rating-stars">
				<i class="fas fa-thumbs-up" data-toggle="tooltip" data-original-title="Rating"></i>
			</span>
			7.8/10 (36 Votes)
		</span>
		<span class="badge-extra text-pink">
			<i class="fas fa-heart" data-toggle="tooltip" data-original-title="Thanks Given"></i>
			1
		</span>
		<a href="https://blutopia.xyz/torrents/17485#comments">
			<span class="badge-extra text-green">
				<i class="fas fa-comment" data-toggle="tooltip" data-original-title="Comments"></i>
				0
			</span>
		</a>
		<span class="badge-extra">
			<i class="fas fa-tachometer text-red" data-toggle="tooltip" title="" data-original-title="High Speeds"></i>
		</span>
		<br>
		<span class="badge-extra">
			<i class="fas fa-tag" data-toggle="tooltip" title="" data-original-title="Genre"></i>
			Animation
		</span>
		<span class="badge-extra">
			<i class="fas fa-tag" data-toggle="tooltip" title="" data-original-title="Genre"></i>
			Sci-Fi &amp; Fantasy
		</span>
	</td>
	<td>
		<a href="https://blutopia.xyz/torrents/download/17485">
			<button class="btn btn-primary btn-circle" type="button" data-toggle="tooltip" data-original-title="Download">
				<i class="fas fa-download"></i>
			</button>
		</a>
	</td>
	<td>
		<span data-toggle="tooltip" data-original-title="Bookmark" id="torrentBookmark17485" torrent="17485" state="0" class="torrentBookmark"></span>
	</td>
	<td>
		<time>2 years ago</time>
	</td>
	<td>
		<span class="badge-extra text-blue">485.87 MiB</span>
	</td>
	<td>
		<a href="https://blutopia.xyz/torrents/17485/peers">
			<span class="badge-extra text-green">
				68
			</span>
		</a>
	</td>
	<td>
		<a href="https://blutopia.xyz/torrents/17485/peers">
			<span class="badge-extra text-red">
				0
			</span>
		</a>
	</td>
	<td>
		<a href="https://blutopia.xyz/torrents/17485/history">
			<span class="badge-extra text-orange">
				169 Times
			</span>
		</a>
	</td>
</tr>':

System.Exception: Error while parsing field=title, selector=a.view-torrent, value=<null>: Selector "a.view-torrent" didn't match 
<tr>
	<td style="width: 1%;">
		<div class="torrent-poster pull-left"></div>
	</td>
	<td style="width: 1%;">
		<a href="https://blutopia.xyz/categories/2">
			<div class="text-center">
				<img src="https://blutopia.xyz/files/img/category-5e1ce662c84e1.png" data-toggle="tooltip" data-original-title="TV Show torrent" style="padding-top: 10px;" alt="TV Show">
			</div>
		</a>
	</td>
	<td style="width: 1%;">
		<div class="text-center" style="padding-top: 15px;">
			<span class="label label-success" data-toggle="tooltip" data-original-title="Type">
				Encode
			</span>
		</div>
		<div class="text-center" style="padding-top: 8px;">
			<span class="label label-success" data-toggle="tooltip" data-original-title="Resolution">
				720p
			</span>
		</div>
	</td>
	<td>
		<a class="text-bright" style="font-size: 16px;" href="https://blutopia.xyz/torrents/17485">
			Steins;Gate 0 - E18 720p 10-bit WEB Dual-Audio AAC2.0 x264-LostYears
		</a>
		<br>
		<span class="badge-extra">
			<i class="fas fa-upload" data-toggle="tooltip" data-original-title="Uploader"></i>
			<a href="https://blutopia.xyz/users/Rukus">
				Rukus
			</a>
		</span>
		<span class="badge-extra">
			<span class="text-gold movie-rating-stars">
				<i class="fas fa-thumbs-up" data-toggle="tooltip" data-original-title="Rating"></i>
			</span>
			7.8/10 (36 Votes)
		</span>
		<span class="badge-extra text-pink">
			<i class="fas fa-heart" data-toggle="tooltip" data-original-title="Thanks Given"></i>
			1
		</span>
		<a href="https://blutopia.xyz/torrents/17485#comments">
			<span class="badge-extra text-green">
				<i class="fas fa-comment" data-toggle="tooltip" data-original-title="Comments"></i>
				0
			</span>
		</a>
		<span class="badge-extra">
			<i class="fas fa-tachometer text-red" data-toggle="tooltip" title="" data-original-title="High Speeds"></i>
		</span>
		<br>
		<span class="badge-extra">
			<i class="fas fa-tag" data-toggle="tooltip" title="" data-original-title="Genre"></i>
			Animation
		</span>
		<span class="badge-extra">
			<i class="fas fa-tag" data-toggle="tooltip" title="" data-original-title="Genre"></i>
			Sci-Fi &amp; Fantasy
		</span>
	</td>
	<td>
		<a href="https://blutopia.xyz/torrents/download/17485">
			<button class="btn btn-primary btn-circle" type="button" data-toggle="tooltip" data-original-title="Download">
				<i class="fas fa-download"></i>
			</button>
		</a>
	</td>
	<td>
		<span data-toggle="tooltip" data-original-title="Bookmark" id="torrentBookmark17485" torrent="17485" state="0" class="torrentBookmark"></span>
	</td>
	<td>
		<time>2 years ago</time>
	</td>
	<td>
		<span class="badge-extra text-blue">485.87 MiB</span>
	</td>
	<td>
		<a href="https://blutopia.xyz/torrents/17485/peers">
			<span class="badge-extra text-green">
				68
			</span>
		</a>
	</td>
	<td>
		<a href="https://blutopia.xyz/torrents/17485/peers">
			<span class="badge-extra text-red">
				0
			</span>
		</a>
	</td>
	<td>
		<a href="https://blutopia.xyz/torrents/17485/history">
			<span class="badge-extra text-orange">
				169 Times
			</span>
		</a>
	</td>
</tr>
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1522
[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
next release of Jackett with fix for this is due out in a couple hours.
