### ISSUE TITLE
UHDBits: Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by Metigoth** [Jackett/Jackett#1120]
Jackett version:  0.7.1090
Mono version (if not using Windows):4.8
Debian Jessie
It works in Cardigann 1.9.10  

-------------------------------
[log.txt](https://github.com/Jackett/Jackett/files/805554/log.txt)

**Comment by kaso17** [comment]
Please try unchecking "Display Uploader column in the torrent browse page" and "Display Comment column in the torrent browse page" in your profile. These options don't work for me but it seems like they work for you, breaking the parsing. I'll try to find a solution which works in both cases later.

**Comment by Metigoth** [comment]
That fixed it.

**Comment by kaso17** [comment]
With 758b00b567c310767c8957d538ebe2e2a89ec7d6 you can turn them on again.
