### ISSUE TITLE
[req] See again https://ttobogo.net public Korean

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#11212]
See again https://ttobogo.net public Korean
spawned from #10663

**Comment by garfield69** [comment]
https://ttobogo.net/ returns Error 1020 Access denied

**Comment by ilike2burnthing** [comment]
same

**Comment by ilike2burnthing** [comment]
Site is region blocked. Korean VPN server works. Redirects to https://www1.ttobogo.net/

**Comment by garfield69** [comment]
I don't know of a **free** vpn that provides a korean server. do you?

**Comment by ilike2burnthing** [comment]
No, unfortunately not (Proton and Windscribe both paywall their Korean servers).

You could use a proxy instead. Just tested with 112.169.9.162:80 and it works - https://www.proxynova.com/proxy-server-list/country-kr/

**Comment by ilike2burnthing** [comment]
Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up, doesn't appear to be region blocked any more - https://www8.ttobogo.net/

**Comment by garfield69** [comment]
v0.18.372

**Comment by garfield69** [comment]
https://www8.ttobogo.net/ returning Error 522 Connection timed out

**Comment by garfield69** [comment]
https://torrentrank.net/torrentrank showing ttobogo is gone so I'm removing it early.

**Comment by garfield69** [comment]
v0.18.463
