### ISSUE TITLE
[req] Tjangto https://www.jjangtorrent.com/ public Korean

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#11216]
Tjangto ~~https://jjangto.com~~ https://www.jjangtorrent.com/ public Korean
spawned from #10663

looks like this site changes its domains regularly, will need followredirect to auto update configs.

**Comment by garfield69** [comment]
same engine as torrentsir with same caveats.

**Comment by garfield69** [comment]
v0.17.627

**Comment by ilike2burnthing** [comment]
https://www.jjangt.com/ - Error 522 - Connection timed out
