### ISSUE TITLE
kickasstorrents.to number of results

### ISSUE THREAD

**Issue by entryb** [Jackett/Jackett#11213]
Currently when using the site itself it returns some 1500 results for the keyword movie, in jackett it returns only 20 manual search, for other known movie titles which returns 150 some results in the movie category at the site, only got 9 results in jackett movie category manual search?

**Comment by garfield69** [comment]
the web site returns only 20 results per page, and jackett only fetches the first page.
this is the search request that jackett generates for a search q=movie
https://kickasstorrents.to/usearch/movie/?sortby=time&sort=desc

of the 20 results for that search, only 12 are classifies as category movies (2000) which is what Jackett also returns.

We generally try to aim for about 100 results, but we also try to avoid posting multiple http requests to fetch additional pages, especially in these times where sites have become very sensitive to ddos attacks attempts, and simultaneous http request for multiple pages (such as 5 http requests to fetch pages 1 to 5 for a search query.

**Comment by entryb** [comment]
Think i misread abit here, i was thinking category button movies on the site was the same as using category(2000) in jackett, or does jackett use the general search and sort by the tags on that very first page?

**Comment by garfield69** [comment]
>Think i misread abit here, i was thinking category button movies on the site was the same as using category(2000) in jackett, or does jackett use the general search and sort by the tags on that very first page?

jackett use the general search and sort by the tags on that very first page

**Comment by garfield69** [comment]
actually, it depends on the web site and how they manage categories.
If the sites support multi-category queries, we add the cats to the query request
http://sitewqhatever/search/q=atitle,c1=1,c2=1,c3=1
and let the site return the results

but id the site has categories but only allows one category to be specified in  searches , then we do a cat=all search and then apply the category filter over the top of what is returned.
http://sitewqhatever/search/q=atitle
followed by filter for c=1 etc.

**Comment by entryb** [comment]
In any case, is there a possibility to increase the number of sites fetched so it might return more results?

9 results for my search, then considering there might be some non real torrents amongst there aswell leaves not many results though?

**Comment by garfield69** [comment]
I'll take a look.
what is the search you are doing, and are you filtering with categories?

**Comment by entryb** [comment]
I was filtering by category2000 in jackett, though for most popular movie searches it returns seems always way over 50 results in the movie category each time i dont think its my spesific search term thats the problem, if it would just lookup one or two more pages that should be ok i guess.

Challenge is though that jackett does it sort of general search, so many of those results wont be relevant or if filter by category will get much few results even if it did one more request or so, i guess it would have to be some sort of trade one or more request for some more relevant result.

Also i dont think kickasstorrents.to is a proper successor to the one we had earlier so might question how much fiddling aournd with it its worth, there was some talk of the real site being put online again but didnt hear anything since then and nothing seems to have happen.

I think if its much work to improve this might just let it be altogether, maybe we should just resort to use other indexers aswell until and if the real one ever surface again, thanks for looking into this though and compliments for an awesome tool

**Comment by garfield69** [comment]
All the kickasstorrent sites are poor clones/copy cats of the original. There is not longer an official KAT site.
Most clones are click bait sites, but some still provide real torrents even if they are often uploaded from elsewhere.
Many of this KAT clones actually fetch torrents by bot from TPB or other sources, then present the results using the KAT skin as if they are original uploads. But when you try to use the web sites search you get mixed results.

Each indexer that Jackett has for a web site is tailored to use what ever the sites engines will deliver. Some web sites have proper search engines with good categories and sorting options, and others are just basic. Like this one.

Regardless, I will look into adding an additional fetch or two of the results pages, and see what happens.

**Comment by garfield69** [comment]
next release of Jackett due out tomorrow will have this indexer fetch 5 pages.

**Comment by garfield69** [comment]
v0.17.627
