### ISSUE TITLE
[Bug] HDHome - No captcha image available 

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1121]
I'm trying to configure HDHome, which requires a captcha image to log in, but Jackett cannot seem to read the captcha image, I'm getting a 'No image available' message instead of the image itself.
 
Jackett version:  0.7.1090.0
Mono version (if not using Windows):  N/A

**Comment by kaso17** [comment]
fixed with 59d8b5cb02ef5a4be6ce3f75d28cae8ee83d6186

**Comment by kamikazechaser** [comment]
Kindly bump this as a minor release!

**Comment by kaso17** [comment]
will push a new release soon (it will be a pre-release)

**Comment by kaso17** [comment]
v0.7.1115 is released
