### ISSUE TITLE
Allow users to filter out trackers that fail the test

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1122]
Occasionally, I'd use the 'Test All' function to see which trackers are not working properly. I typically have to keep scrolling to manually find those which fail the test & examine why this happened. 

I think it would be helpful if users could filter out trackers which fail their respective test instead of having to manually search for them. One way of doing this is through a drop-down box on top of the Test column, which could have the following entries:

-All Trackers
-Test Successful 
-Test Failed

Or something along those lines... The drop-down box should ideally default to All Trackers every time Jackett starts.

**Comment by kaso17** [comment]
added with c561a55b6862f43bc44fb9adc65562cfca091ae7
clicking on the actions table header will sort the list by the error message.
additionally the search box will search in the error message too.

**Comment by armani316** [comment]
I'm using pre-release 0.7.1115 but I can't sort indexers by action (action isn't clickable), nor can I search or filter them by error message. Is it working for you, @kaso17?

**Comment by kaso17** [comment]
Probably was a caching issue
