### ISSUE TITLE
[1337x] Exception (1337x): Connection refused: Connection refused (1337x.to:443) (Test)

### ISSUE THREAD

**Issue by edfield** [Jackett/Jackett#11229]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
1337x was down but is now back up. If you continue to have issues, check that the site link is set correctly and that you can access in browser from the same device and IP. If not, try one of the proxies.

**Comment by edfield** [comment]
Jacket sent me to git hub, and I mistakenly thought it was directed to the search. Didn't intend to make a report, and couldn't figure out how to delete. After that I figured out 1337x was down. 
Thanks for answering.

    On Thursday, March 4, 2021, 06:57:25 AM CST, ilike2burnthing <notifications@github.com> wrote:  
 
 


1337x was down but is now back up. If you continue to have issues, check that the site link is set correctly and that you can access in browser from the same device and IP. If not, try one of the proxies.
