### ISSUE TITLE
Add option to force IPv4 connections to indexers (To fix this issue)

### ISSUE THREAD

**Issue by alpe12** [Jackett/Jackett#11224]
I'm having _The cookies provided by FlareSolverr are not valid_ errors.
Flaresolverr is runing on docker, and Jackett is running nativelly.
From what I searched docker uses IPv4 only by default.
So my guess is that Flaresolverr is using IPv4 and Jackett is using IPv6 and that's why it fails.
I used tcptrack and it shows access to both IPv4 and IPv6 of the Indexer.
So it's possible that my guess is right.

If this is the case, it would be nice if there was a checkbox on Jackett **configuration to force it to use IPv4 only, so that the public IP used by Jackett match the one used by FlareSolverr.**

**Comment by garfield69** [comment]
Jackett has no control over whether it uses IPv4 or IPv6, it uses whatever the network is configured to do.
If you are using docker, then you could try adding  `network_mode: host` to your docker-compose.yml file or add to your docker create `--network host` (info from #7942).

**Comment by Aloki** [comment]
Actually it is possible. You need to add a line to the _x.runtimeconfig.json_ file (where _x_ is JackettConsole, JackettService or JackettTray, depending on how you run it):
```
"configProperties": {
  ...
  "System.Net.DisableIPv6": true,
  ...
}
```

**Comment by amorcayReal** [comment]
@Aloki It worked for me, thanks
