### ISSUE TITLE
Api question

### ISSUE THREAD

**Issue by diegargon** [Jackett/Jackett#11222]
is there any way to request/ask  Jackett if certain indexer is working before request results? 

I building a small app that use Jackett and  i must wait for the timeout. I was wondering if there is a more effective way. I look at related apis and not found anything

thanks.

**Comment by garfield69** [comment]
No there is not. Each indexer will make a http GET or POST and deals with the response individually. 
There is not overall monitoring or management of the indexers performance, no tracking of successes or failures, so there will not be any API query that returns such info.
So the only time you know if an indexer is working or not is when you try to use it.
