### ISSUE TITLE
[lesaloon.yml] Issue with login

### ISSUE THREAD

**Issue by simlaf** [Jackett/Jackett#11235]
It looks like this indexer changed their login form, and it now fails.  It now includes a random string in the form:

form action="login_ab0be8fb822a364d68310bef61667d21.php?page=login" name="login"

in file lesaloon.yml, line 123:
  form: form[action^="index.php?page=login"]

I was able to get it working by manually editing lesaloon.yml, line 123 to:

 form: form[name^="login"]

**Comment by ilike2burnthing** [comment]
This was changed back in January - https://github.com/Jackett/Jackett/issues/10873

You need to update Jackett.
