### ISSUE TITLE
Impossible to add Xthor indexer

### ISSUE THREAD

**Issue by nabot93** [Jackett/Jackett#1123]
Hello,

I am using Jackett under Linux: 
Jackett version = 0.7.1090.0
Mono version = 4.8.0

I cannot managed to have this indexer works. Here is the error I got:
`Error Exception in test_indexer System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
`

Thanks for your help

**Comment by kaso17** [comment]
Please confirm that the ca-certificates-mono package is installed.
Are other https indexers working?

**Comment by nabot93** [comment]
I saw that ca-certificates-mono was missing this morning, so I installed it.
The Jackett test of IPTorrents is working.

**Comment by kaso17** [comment]
please run `curl -v https://api.xthor.bz/` as the same user as jackett

**Comment by nabot93** [comment]
Here the result:

```
$ curl -v https://api.xthor.bz/
* Hostname was NOT found in DNS cache
*   Trying 104.28.30.89...
* Connected to api.xthor.bz (104.28.30.89) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni252254.cloudflaressl.com
* 	 start date: 2017-02-20 00:00:00 GMT
* 	 expire date: 2017-08-06 23:59:59 GMT
* 	 subjectAltName: api.xthor.bz matched
* 	 issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
* 	 SSL certificate verify ok.
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: api.xthor.bz
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 28 Feb 2017 16:40:10 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=da7a863f8cb4cd735ab7f3bb1959b504c1488300010; expires=Wed, 28-Feb-18 16:40:10 GMT; path=/; domain=.xthor.bz; HttpOnly
< Vary: Accept-Encoding
< X-Powered-By: PHP/5.6.27-0+deb8u1
* Server cloudflare-nginx is not blacklisted
< Server: cloudflare-nginx
< CF-RAY: 3385511bfc393c53-CDG
< 
{
    "error": {
        "code": 1,
        "descr": "Passkey not found"
    }
* Connection #0 to host api.xthor.bz left intact
```

**Comment by kaso17** [comment]
ok, what's the outout of `csharp -e 'Console.WriteLine(new System.Net.WebClient().DownloadString("https://api.xthor.bz/"))'`

**Comment by kaso17** [comment]
Also try to re import the certificates:
`cert-sync /etc/ssl/certs/ca-certificates.crt`

If that doesn't fix it please try running jackett without validation (`--IgnoreSslErrors true` command line argument)

**Comment by nabot93** [comment]
It seems I do not hqve csharp executable. How should I run your command?

When I run `cert-sync`, I got a lot of errors like this:
`Warning: Could not import C=PL, O=Krajowa Izba Rozliczeniowa S.A., CN=SZAFIR ROOT CA2
System.DllNotFoundException: /usr/lib/../lib/libmono-btls-shared.so
  at (wrapper managed-to-native) Mono.Btls.MonoBtlsX509:mono_btls_x509_from_data (intptr,int,Mono.Btls.MonoBtlsX509Format)
  at Mono.Btls.MonoBtlsX509.LoadFromData (System.Byte[] buffer, Mono.Btls.MonoBtlsX509Format format) [0x0002a] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at System.Security.Cryptography.X509Certificates.X509Helper2.GetNativeInstance (System.Security.Cryptography.X509Certificates.X509CertificateImpl impl) [0x00025] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at System.Security.Cryptography.X509Certificates.X509Helper2.GetSubjectNameHash (System.Security.Cryptography.X509Certificates.X509CertificateImpl impl) [0x00000] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at System.Security.Cryptography.X509Certificates.X509Helper2.GetSubjectNameHash (System.Security.Cryptography.X509Certificates.X509Certificate certificate) [0x00006] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at Mono.Security.X509.X509Store.ImportNewFormat (Mono.Security.X509.X509Certificate certificate) [0x0000c] in <59bcb3a41e31492f91d9513566444e88>:0 
  at Mono.Security.X509.X509Store.Import (Mono.Security.X509.X509Certificate certificate) [0x00019] in <59bcb3a41e31492f91d9513566444e88>:0 
  at Mono.Tools.CertSync.ImportToStore (Mono.Security.X509.X509CertificateCollection roots, Mono.Security.X509.X509Store store) [0x00054] in <e14d5123bc22484f8e0510200156fa93>:0 
`

**Comment by kaso17** [comment]
Which distribution are you using?
Did you install `mono-devel`? It should pull `mono-runtime-common` which includes libmono-btls-shared.so, which seems to be missing.

**Comment by nabot93** [comment]
`mono-devel` is installed and I am using a raspberry pi:
```
$ uname -a
Linux osmc 4.4.27-7-osmc #1 SMP PREEMPT Tue Jan 24 03:38:31 UTC 2017 armv7l GNU/Linux
```

**Comment by kaso17** [comment]
Then you should open a bug report with the distribution/source of the mono packages and let them know that they're missing libmono-btls-shared.so (Post the error from the cert-tool).

**Comment by kaso17** [comment]
in the mean time you might want to run jackett with libcurl as httpclient (`-c libcurl`).

**Comment by nabot93** [comment]
Thank you! It works using libcurl. 

What is the best choice between libcurl and mono as htppclient?

**Comment by kaso17** [comment]
httpclient should be much faster (supports parallel http requests), with libcurl requests are serialized making it slower. libcurl support might be dropped in the futures (no plans yet).

Please report the cert-tool bug to the package maintainer.

**Comment by rodti** [comment]
I'm having the same issue. It appears that BTLS is deprecated in Mono 4.8.x

**Comment by nabot93** [comment]
I did not found this information. Where did you find it?

**Comment by rodti** [comment]
[While Googling the issue yesterday, found this.](http://stackoverflow.com/questions/41837397/where-is-btls-cert-sync-on-osx-for-mono-4-8)

**Comment by kaso17** [comment]
The core problem is `System.DllNotFoundException: /usr/lib/../lib/libmono-btls-shared.so` the underlying btls library is missing.

**Comment by nabot93** [comment]
They do not seem to think that the library is missing. https://bugzilla.xamarin.com/show_bug.cgi?id=53015

**Comment by kaso17** [comment]
`You are not authorized to access bug #53015.`

**Comment by nabot93** [comment]
'''
Jo Shields 2017-03-04 19:10:53 UTC
Alex, this seems to be a broken assumption in cert-sync that the BTLS store is always available (right now it's only on x86/amd64)? We should be checking for availability before calling `ImportToStore (roots, X509StoreManager.NewLocalMachine.TrustedRoot);`
[reply] [−] Comment 2 Alexander Köplinger 2017-03-05 15:59:35 UTC
Thanks. I sent a pull request with the fix: https://github.com/mono/mono/pull/4475

You can ignore the error for now, at the point where it happens cert-sync already imported the certs into the legacy certificate store so everything should be OK.
'''

**Comment by kaso17** [comment]
Seems like btls is simply not supported on the generic arm platform. I wonder why (it's supported on android)?. But you'll have to use libcurl on ARM for now.

**Comment by akoeplinger** [comment]
> I wonder why (it's supported on android)?. But you'll have to use libcurl on ARM for now.

The reason is simple: we didn't test BTLS on ARM outside of Android so we decided to only enable it for that platform for now :)

**Comment by kaso17** [comment]
@akoeplinger thank you for letting us know. It would be great if you still could include it in the ARM build. Just don't use it by default? That way some early adopters could provide some real world compatibility feedback. The legacy TLS implementation is missing to much in order to be useful.

**Comment by kaso17** [comment]
With 4823e610155da295c4c42dc368a0acc6823b2ab3 Jackett should automatically fall back to libcurl if btls is not available. Please try pre-release version v0.7.1127.

**Comment by akoeplinger** [comment]
> It would be great if you still could include it in the ARM build. Just don't use it by default?

That's a bit difficult given the current setup because afaik we can't make that decision based on the platform.

> That way some early adopters could provide some real world compatibility feedback

Our hope was that enthusiasts would just build Mono themselves and enable BTLS :)

**Comment by kaso17** [comment]
Ok, would have assumed that simply making the "MONO_TLS_PROVIDER" env var default to "legacy" on arm would be possible.

To anyone using an ARM platform: Please compile mono yourself and enable BTLS support. The extra work will reward you with a general faster Jackett (With libcurl no parallel requests are supported).

**Comment by nabot93** [comment]
Ok, I will try to compile mono. Where did you see we should set MONO_TLS_PROVIDER to legacy?

**Comment by kaso17** [comment]
I assume btls support is some kind of option of the configure script, see http://www.mono-project.com/docs/about-mono/supported-platforms/arm/
There's no need to set MONO_TLS_PROVIDER

**Comment by raspdealer** [comment]
Hi
Using -c libcurl Xthor is back but not the others...
Any updates?
Thanks!!

**Comment by kaso17** [comment]
Which others? libcurl should work with all indexers.

**Comment by raspdealer** [comment]
2f4y, cinemaz, paradisdunet, privatehd, rapidetracker,...
may be few of them are dead? :(

**Comment by kaso17** [comment]
rapidtracker is gone (removed from the latest release already).
The other ones are working fine for me, please try to reconfigure. If that does't fix them please post an enhanced log in a new issue
