### ISSUE TITLE
[newstudiol] Error: The confirmation code you entered was incorrect (Config)

### ISSUE THREAD

**Issue by demon-goxa** [Jackett/Jackett#11231]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Ubuntu Docker
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
0.17.611
**Last Working Jackett Version**:
0.17.611
**Are you using a proxy or VPN?** [yes/no]
no
### Description
Can't auth with login pass
[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
use your browser to login afresh to newstudio, resolving any requests for additional security confirmations, and once logged in, then logout of the web site.
Then edit your newstudioL indexer config from your dashboard, replace your password and save. 
See if that works for you.
