### ISSUE TITLE
[elite-tracker] https://elite-tracker.net/ returning ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#11245]
[elite-tracker] https://elite-tracker.net/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/11245#issue-823301421 again

**Comment by garfield69** [comment]
v0.17.972
