### ISSUE TITLE
[1337x] Exception (1337x): No route to host: No route to host (1337x.to:443) (Test)

### ISSUE THREAD

**Issue by ranjeet2805** [Jackett/Jackett#11247]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Asustor 6404t -3.5.4.RE11

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:  Jackett Version v0.17.638 

**Are you using a proxy or VPN?** [yes/no] no

### Description
add indexer-> add 1337x -> test

### Logged Error Messages
 An error occurred while testing this indexer
Exception (1337x): No route to host: No route to host (1337x.to:443)

### Screenshots

[Place any screenshots of the issue here if needed]
![image](https://user-images.githubusercontent.com/24996508/110198311-ac477580-7ea5-11eb-9e44-2f06f91221e4.png)

**Comment by ilike2burnthing** [comment]
Make sure you can access the site in browser from the same IP. If not, use one of the several proxies.
