### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by kevincork** [Jackett/Jackett#1124]
Hi,

I think I did a correct install, when I enter my IP: 9117 is redirect me to http://10.0.0.95:9117/Admin/Dashboard, which the icons of Jackett next to the URL, however, the page remain blank.

**Comment by kaso17** [comment]
please check the log file

**Comment by desimaniac** [comment]
I am having the same issue. I have Synology DSM 6. 

 ash-4.3# /var/packages/Mono/target/usr/local/bin/mono JackettConsole.exe
03-03 21:42:07 Info App config/log directory: /root/.config/Jackett 
03-03 21:42:07 Info Starting Jackett 0.7.1090.0 
03-03 21:42:07 Info Environment version: 4.0.30319.42000 (/volume1/@appstore/Mono/usr/local/lib/mono/4.5) 
03-03 21:42:07 Info OS version: Unix 3.10.77.0 (64bit OS) (64bit process) 
03-03 21:42:07 Info ThreadPool MaxThreads: 400 workerThreads, 400 completionPortThreads 
03-03 21:42:07 Info mono version: 4.6.2 (Stable 4.6.2.16/ac9e222 Wed Feb  8 17:04:51 CST 2017) 
03-03 21:42:07 Info Using HTTP Client: UnixLibCurlWebClient 
03-03 21:42:08 Info Loading Cardigann definitions from: /root/.config/cardigann/definitions/ 
03-03 21:42:08 Info Loading Cardigann definitions from: /etc/xdg/cardigan/definitions/ 
03-03 21:42:08 Info Loading Cardigann definitions from: /volume1/@appstore/jackett/share/jackett/Definitions 
03-03 21:42:08 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/2fast4you.yml 
03-03 21:42:08 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/acidlounge.yml 
03-03 21:42:08 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/alphareign.yml 
03-03 21:42:08 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/aox.yml 
03-03 21:42:08 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/apollo.yml 
03-03 21:42:08 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/arabafenice.yml 
03-03 21:42:08 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/asiandvdclub.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/bithq.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/bithumen.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/bitspyder.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/blubits.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/bluebird.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/btnext.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/carpathians.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/chdbits.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/datascene.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/diablotorrent.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/dreamteam.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/eotforum.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/estone.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/ethor.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/eztv.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/fanoin.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/freedomhd.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/fullmixmusic.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/funkytorrents.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/gfxpeers.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/gods.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/gormogon.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/hdclub.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/hdhome.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/hdme.yml 
03-03 21:42:09 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/hdpter.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/hdsky.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/hon3yhd.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/hyperay.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/icetorrent.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/infinityt.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/inperil.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/insanetracker.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/isohunt.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/jpopsuki.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/kapaki.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/kickasstorrent-kathow.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/kickasstorrent.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/leparadisdunet.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/limetorrents.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/linkomanija.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/losslessclub.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/magico.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/majomparade.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/mononokebt.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/mteamtp.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/myspleen.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/nachtwerk.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/nethd.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/newretro.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/polishsource.yml 
03-03 21:42:10 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/qctorrent.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/rapidetracker.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/rockhardlossless.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/rodvd.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/sdbits.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/secretcinema.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/shareisland.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/sharespacedb.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/shellife.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/skytorrents.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/tenyardtracker.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/thehorrorcharnel.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/thepiratebay.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/theshinning.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/thetorrents.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/torrentbd.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/torrenthr.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/torrenting.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/torrentproject.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/torrentsectorcrew.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/torrentsmd.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/torrentz2.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/torviet.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/totheglory.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/trancetraffic.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/uhdbits.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/ultrahdclub.yml 
03-03 21:42:11 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/utorrents.yml 
03-03 21:42:12 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/worldofp2p.yml 
03-03 21:42:12 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/xtremezone.yml 
03-03 21:42:12 Info LibCurl init Ok 
03-03 21:42:12 Info LibCurl version libcurl/7.50.3 OpenSSL/1.0.2j zlib/1.2.8 libssh2/1.7.0 
03-03 21:42:12 Info Starting web server at http://*:9117/ 
03-03 21:42:12 Info set HttpListener.IgnoreWriteExceptions = true 
ash-4.3#

**Comment by kaso17** [comment]
Please run jackett with the "-t -l" arguments to get more debug output.

**Comment by kevincork** [comment]
mono /opt/jackett/JackettConsole.exe -t -l
03-06 17:42:11 Info Logging enabled. 
03-06 17:42:11 Info Tracing enabled. 
03-06 17:42:11 Info App config/log directory: /home/odroid/.config/Jackett 
03-06 17:42:11 Info Starting Jackett 0.7.1084.0 
03-06 17:42:11 Info Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5) 
03-06 17:42:11 Info OS version: Unix 3.10.104.133 
03-06 17:42:11 Info ThreadPool MaxThreads: 800 workerThreads, 800 completionPortThreads 
03-06 17:42:11 Info issue: Ubuntu 16.04.2 LTS \n \l 
03-06 17:42:11 Info mono version: 4.8.0 (Stable 4.8.0.495/e4a3cf3 Wed Feb 22 18:27:02 UTC 2017) 
03-06 17:42:11 Info Using HTTP Client: HttpWebClient 
03-06 17:42:12 Info Loading Cardigann definitions from: /home/odroid/.config/cardigann/definitions/ 
03-06 17:42:12 Info Loading Cardigann definitions from: /etc/xdg/cardigan/definitions/ 
03-06 17:42:12 Info Loading Cardigann definitions from: /opt/jackett/Definitions 
03-06 17:42:12 Info Loading Cardigann definition /opt/jackett/Definitions/2fast4you.yml 
03-06 17:42:12 Info Loading Cardigann definition /opt/jackett/Definitions/alphareign.yml 
03-06 17:42:12 Info Loading Cardigann definition /opt/jackett/Definitions/aox.yml 
03-06 17:42:12 Info Loading Cardigann definition /opt/jackett/Definitions/apollo.yml 
03-06 17:42:12 Info Loading Cardigann definition /opt/jackett/Definitions/arabafenice.yml 
03-06 17:42:12 Info Loading Cardigann definition /opt/jackett/Definitions/asiandvdclub.yml 
03-06 17:42:12 Info Loading Cardigann definition /opt/jackett/Definitions/bithq.yml 
03-06 17:42:12 Info Loading Cardigann definition /opt/jackett/Definitions/bithumen.yml 
03-06 17:42:12 Info Loading Cardigann definition /opt/jackett/Definitions/bitspyder.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/blubits.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/bluebird.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/btnext.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/chdbits.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/datascene.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/diablotorrent.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/dreamteam.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/eotforum.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/estone.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/ethor.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/eztv.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/fanoin.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/freedomhd.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/fullmixmusic.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/funkytorrents.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/gfxpeers.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/gods.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/gormogon.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/hdclub.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/hdhome.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/hdme.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/hdpter.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/hdsky.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/hon3yhd.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/hyperay.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/icetorrent.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/infinityt.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/inperil.yml 
03-06 17:42:13 Info Loading Cardigann definition /opt/jackett/Definitions/insanetracker.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/isohunt.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/jpopsuki.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/kapaki.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/kickasstorrent-kathow.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/kickasstorrent.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/leparadisdunet.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/limetorrents.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/linkomanija.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/losslessclub.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/magico.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/majomparade.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/mononokebt.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/mteamtp.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/myspleen.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/nachtwerk.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/nethd.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/newretro.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/polishsource.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/qctorrent.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/rapidetracker.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/rockhardlossless.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/rodvd.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/sdbits.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/secretcinema.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/shareisland.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/sharespacedb.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/shellife.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/skytorrents.yml 
03-06 17:42:14 Info Loading Cardigann definition /opt/jackett/Definitions/tenyardtracker.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/thehorrorcharnel.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/thepiratebay.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/theshinning.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/thetorrents.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/torrentbd.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/torrenthr.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/torrenting.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/torrentproject.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/torrentsectorcrew.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/torrentsmd.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/torrentz2.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/torviet.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/totheglory.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/trancetraffic.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/uhdbits.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/ultrahdclub.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/utorrents.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/worldofp2p.yml 
03-06 17:42:15 Info Loading Cardigann definition /opt/jackett/Definitions/xtremezone.yml 
03-06 17:42:15 Info Starting web server at http://*:9117/ 
03-06 17:42:15 Info set HttpListener.IgnoreWriteExceptions = true 
03-06 17:42:16 Error Address already in use: Most likely Jackett is already running. 

I'll try to grab the log and post asap.

**Comment by kevincork** [comment]
Here is the full log :  https://app.box.com/s/2cw4hjcs1os1kt95jm1pudn9getjdd0a

**Comment by kaso17** [comment]
`Unhandled exception: Message = Access to the path "/opt/jackett/Content/index.html" is denied.`
Check your file system permissions

**Comment by RoloSoze** [comment]
@kevincork @desimaniac Does assigning the correct file system permissions solve this issue for you guys?

**Comment by desimaniac** [comment]
@RoloSoze Hi. I uninstalled the Synology package and installed a docker instead ([link](https://hub.docker.com/r/linuxserver/jackett/)). That fixed everything.

**Comment by kevincork** [comment]
sudo chmod -R 755 /opt/jackett/Content/index.html but same issue

**Comment by kaso17** [comment]
Check the permissions of the Content directory too.
You should chown the directory to the corresponding user running jackett:
`chown -R jackett /opt/jackett/`
Otherwise the build in update mechanism won't work either.

If that doesn't fix it there might be some extra security policies (apparmor/selinux) preventing access.

**Comment by kevincork** [comment]
Resolved, thank you !
