### ISSUE TITLE
I am getting more less results than the actual result number. [gtorrent]

### ISSUE THREAD

**Issue by batuhankrmn** [Jackett/Jackett#11260]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:  Jackett Version v0.17.655

**Last Working Jackett Version**: Unknown

**Are you using a proxy or VPN?** [yes/no] No

### Description

I get just one result from jackett while the actual result number is 103. 

### Logged Error Messages

No error, just missing results

### Screenshots

![03 07 21 (17 38)](https://user-images.githubusercontent.com/57859656/110243658-66091980-7f6c-11eb-91b3-c8957ae13380.png)
![03 07 21 (17 37)](https://user-images.githubusercontent.com/57859656/110243659-673a4680-7f6c-11eb-8326-f805d7954c1c.png)

**Comment by ilike2burnthing** [comment]
The indexer uses the `andmatch` filter to remove irrelevant results.

That's the only downloadable result with `Avengers` in the title (without translating them), hence why it's the only one returned in Jackett.

**Comment by batuhankrmn** [comment]
Oh I see. The problem is caused by Cyrillic letters. Thanks!
