### ISSUE TITLE
[pier720] Login failed: Selector

### ISSUE THREAD

**Issue by 1ColdAssHonkey** [Jackett/Jackett#11269]
I know someone opened up a ticket about this a couple of weeks ago and never followed through ( #10913).  I was hoping to get it fixed also.  I have attached the enhanced logging for trying to add the tracker to Jackett.  Please let me know if you need anything else.

### Environment

**OS**: Windows 7 & Linux

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] .Net Frameword

**.Net Version**: 4.8

**Jackett Version**: v0.17.655

**Last Working Jackett Version**: About a month ago.

**Are you using a proxy or VPN?** [yes/no] No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
The error first started with my Windows 7 system over a month ago.  I was going to migrate over to Linux soon so I just dismissed the error.  After getting Jackett installed as a docker on the new Unraid box, I setup all of my trackers and tried it again with the same error. If happens whether I use the cookie while logged into the site or not.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
[Jacket Log for 720pier.txt](https://github.com/Jackett/Jackett/files/6101915/Jacket.Log.for.720pier.txt)

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]
#https://i.imgur.com/TAVkDyT.jpg

**Comment by garfield69** [comment]
are you using a cookie fetched from a browser session logged into pier720 on the same machine/os that is running Jackett?
are you copying the cookie string from the correct session?
Login to pier720 and access the search page at https://720pier.ru/search.php
If you are logged in properly you will see your username on the right hand side.
then open the devtools and grab the cookie from the network tab as described.
make sure you select the session with the name `search.php` to be sure you have the cookie from a logged in session.

**Comment by 1ColdAssHonkey** [comment]
1. Same machine.
2. Yes
Followed the instructions exactly as described and still getting the same error.  I verified that the search.php session was selected too.

**Comment by garfield69** [comment]
The indexer works for me on my win10 which I run without vpn.
cookie keys include 
```
_ym_d=redacted; _ym_uid=redacted; dbl=redacted; fco2r34=redacted; phpbb3_h6m7i_track=redacted; phpbb3_h6m7i_u=redacted; phpbb3_h6m7i_k=redacted; phpbb3_h6m7i_sid=redacted
```
do you have the same keys?

**Comment by garfield69** [comment]
@ilike2burnthing your input welcomed. Thanks.

**Comment by ilike2burnthing** [comment]
Immediately after signing in, there's no `phpbb3_h6m7i_track`, and I've signed in with Jackett fine without it. However, if you move around the site for a bit (there might be something specific that triggers it, but I couldn't work out what), it eventually gets added.

How you copy the cookie can cause issues for Jackett though.

If you highlight the cookie and press Ctrl+C, or right-click the highlighted text and click `Copy`, you get this which works with Jackett:
```
phpbb3_h6m7i_track=tf%3A%28xx%3A%28xxx%3A1%3B%29%3B%29%3Bt%3A%28xxx%3Axxxxxx%3B%29%3B;
```
if you instead right-click the cookie click `Copy value`, you get this which doesn't work with Jackett:
```
phpbb3_h6m7i_track=tf:(xx:(xxx:x;););t:(xxx:xxxxxx;);
```
