### ISSUE TITLE
TVV search

### ISSUE THREAD

**Issue by ghost** [Jackett/Jackett#11278]
**OS**: Linux

**Jackett Version**: 0.17.665

**Are you using a proxy or VPN?** [yes/no] No

### Description

Lots of inconsistencies in naming such that lots of shows can't be found in sonarr. Some shows will be ShowName - Series X, sometimes ShowName - MiniSeries, etc

### Logged Error Messages

`Torznab search in TV-Vault for ShowName S01 => Found 0 releases`

The above torrent couldn't be found because the show is posted as ShowName - Series X
This happens for almost all British shows and I was proposing getting rid of the season number search and just search the show name only.

**Comment by 07416** [comment]
posted later in 2021, the tracker is blocking Jackett requests: https://github.com/Jackett/Jackett/issues/12447#issuecomment-956251653

TVV is not on the list of 'supported private trackers' (see [the readme](https://github.com/Jackett/Jackett))

@garfield69 Will you close this issue?
