### ISSUE TITLE
[torrentland] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by DonTomate24** [Jackett/Jackett#11276]
### Environment

**OS**: Docker

**.Net Runtime**: N/A
**.Net Version**: N/A

**Jackett Version**: v0.17.656

**Last Working Jackett Version**: Not sure

**Are you using a proxy or VPN?** No

### Description

Unable to configure Torrentland. The web has been migrated to UNIT3D and the configuration no longer works. Before migrating the web, it did work.

### Logged Error Messages

 An error occurred while updating this indexer
Login Failed, got redirected.

### Screenshots

Not required

**Comment by garfield69** [comment]
I will convert the indexer to the unit3d template.

Note that existing users (like myself) who have not logged onto the new engine since the upgrade, have to use the did-you-forget-your-password option on the login page to refresh their credentials and thus subsequently be able to login.

Site on UNIT3D 5.1.0

**Comment by DonTomate24** [comment]
Thanks for the quick reply!
Glad to hear you are updating the indexer, great news.
Greetings friend.

**Comment by garfield69** [comment]
I've carried over the "change Sxx to Txx" and the "if title has VOSE its English else its Spanish" from the previous indexer.
Will need feedback if that needs to be removed and amended, not enough torrent samples to determine if its still valid or not.

**Comment by garfield69** [comment]
v0.17.665

**Comment by Deibiz4** [comment]
So how can we help?

**Comment by garfield69** [comment]
@Deibiz4  wrote:
>So how can we help?

1. ensure you are on a version of Jackett at or newer than 0.17.665 
2. login to torrentland with your browser to confirm your credentials.
3. I personally had to use the forgot-your-password on their login page to renew my account, but maybe that was just me.
4. use those credentials on the torrentland indexer
5. the indexer works for me.
