### ISSUE TITLE
[limetorrents] Exception (limetorrents): Ssl error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER  at /spksrc/spk/mono/work-evansport-6.1/mono-5.20.1.34/external/boringssl/ssl/tls_record.c:217: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by arrkaye** [Jackett/Jackett#11273]
I used the latest mono release from synocommunity and the manually updated to the latest mono release from github. I noticed a version of openssl is packaged with the synocommunity release, so is it possible there's a mismatch there?

Is there a mono spk package of the latest version?

thanks.

**Comment by ilike2burnthing** [comment]
Try
https://github.com/Jackett/Jackett/wiki/Synology-installation
or
https://github.com/Jackett/Jackett/issues/10922#issuecomment-767007261
