### ISSUE TITLE
Automatic Scheduled Test or Run Test All From API?

### ISSUE THREAD

**Issue by Colorado4Wheeler** [Jackett/Jackett#11271]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: MacOS

**.Net Runtime**: Mono

**.Net Version**: 6.12.0.107

**Jackett Version**: 0.17.655

**Last Working Jackett Version**: 0.17.655

**Are you using a proxy or VPN?** no

### Description

Is there a way to run the Test All functionality from the API?  I have some scripts that parse the configured indexers and would like to manually test them periodically since part of my scripts is reading the associated indexer JSON file to see if there was an error during its last test.  

### Logged Error Messages

No errors.

### Screenshots

No screenshots.

**Comment by ilike2burnthing** [comment]
It's not specifically the test function (perhaps someone else can direct you to that), but an empty/keywordless search will accomplish the same thing - https://github.com/Jackett/Jackett#aggregate-indexers

**Comment by garfield69** [comment]
I think you can test an indexer using the torznab api with a http.post.
(http.get is unsupported, returns 405)
construct your url similar to `http://127.0.0.1:9117/api/v2.0/indexers/0daykiev/test` (replacing 0daykiev with the name of the indexer you are testing).
returns an error if it fails.
cant remember if the apikey is required or not.
just experiment for yourself and see.
