### ISSUE TITLE
Increase the size of the Query search box in Manual Search | UPDATED: 'Search trackers' button spills over to the next line

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1127]
Prior to the current pre-release version (0.7.1115.0), the Query-Category-Tracker line used to spill over to the next line, even when the Jackett webpage is at normal zoom (100% on Firefox). I think this started when longer category names were added, and as such the Category drop-down box needed to be enlarged. 

 It's not doing that anymore, which is great, but the Query search box has now become too small. 

There's a bit of extra space after the 'Search trackers' button that could be used to enlarge the Query search box without having to spill things over to the next line. If need be, the button can be renamed 'Search' as its function is self-explanatory. 

I liked it much more before when I could see my entire search string in the Query search box. Thoughts on this?

UPDATE: It seems that I had a temporary glitch in Jackett on Firefox after updating to 0.7.1115.0. The problem I explained above is no longer relevant, but the 'Search trackers' button spillover issue is now back (see screenshot) even though I have the zoom set at 100%. Does this happen to anyone else?

![jackett](https://cloud.githubusercontent.com/assets/23747425/23487283/0f9f4e5c-fef6-11e6-9a98-fadaaf32c55f.jpg)

Jackett version:  0.7.1115.0 (Pre-release)
Mono version (if not using Windows): N/A

**Comment by kaso17** [comment]
Will filter the tracker specific categories if all trackers have been selected.

**Comment by armani316** [comment]
@kaso17 But I suppose if 'All Trackers' is selected, this will continue to be an issue since the Category drop-down list will still have to accommodate the longest category name.

**Comment by kaso17** [comment]
should be fixed with 39833dcb02dcf5309cdf5f35d59be116ed247c4d

**Comment by RoloSoze** [comment]
@kaso17 Works fine now! Thanks! 

On a side note, do you think it's a good idea to swap the positions of the 'Category' & 'Tracker' drop-down boxes? I think it makes more sense for Tracker to come before Category since the user will likely choose the tracker first, and then choose the required Category - if any - within the selected tracker. At least that's what I do personally. 

Thoughts?

**Comment by kaso17** [comment]
@RoloSoze makes more sense.
Swapped with f6bbb0cf9ef2ff1d97b4e8a1da8cfd0a174ea6c5
Also removed the "Search trackers" text from the search button
