### ISSUE TITLE
Jackett does not run on Synology DSM

### ISSUE THREAD

**Issue by midianmt** [Jackett/Jackett#11270]
### Environment

**OS**: DSM 6.2.3-25426 Update 3

**.Net Runtime**: Mono

**.Net Version**: 5.20.1.34.16

**Jackett Version**: 0.17.568-13

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** No

### Description

Open Package Centre
Locate Jackett
Press run
Nothing happens

### Logged Error Messages

No errors

**Comment by ilike2burnthing** [comment]
Can you provide Jackett's logs so we can get an idea of what's happening?

Have you tried reinstalling?

**Comment by midianmt** [comment]
I have tried removing it and installing it, but nothing changed.

Can you guide me from where I can get logs as I cannot find them on synology.

**Comment by ilike2burnthing** [comment]
Going off old issues, try `volume1/@appstore/jackett/` and its subfolders.

**Comment by midianmt** [comment]
Hi, I have uploaded the logs that I found in @appstore here: https://drive.google.com/drive/folders/1nbvVx24liCxNxpwHEeB51UK07QHK1BfP?usp=sharing

**Comment by midianmt** [comment]
I could not find such file in the @appstore/jackett folder :/

**Comment by ilike2burnthing** [comment]
Looks like Jackett isn't starting and then failing, it's just not starting at all.

You could have a look at reinstalling, upgrading, or downgrading mono, but the easiest thing may be using Docker instead, if your NAS supports it.

**Comment by publicarray** [comment]
@midianmt I'm attempting to move jackett to .NET on the NAS. Depending on the CPU architecture you may have more success with https://github.com/SynoCommunity/spksrc/pull/4485 What NAS model do you have?

**Comment by midianmt** [comment]
@ilike2burnthing I tried uninstalling and re-installing mono, but still doesn't work. Couldn't find Docker in the package centre

@publicarray my NAS is DS415Play

**Comment by publicarray** [comment]
@midianmt Yea Docker is not available on that NAS model unfortunately.

We just published the fix I mentioned above: https://synocommunity.com/package/jackett

**Comment by midianmt** [comment]
So I re-install everything (mono, jackett, sonarr) restarted the NAS and it works now. Thanks for your help. Now I'm just having trouble re-adding jackett indexers on sonarr, but will do some more troubleshooting before I open a new ticket for that. Thanks for your help :)
