### ISSUE TITLE
[yggtorrent] Error connecting to FlareSolverr server

### ISSUE THREAD

**Issue by Mihank1** [Jackett/Jackett#11281]
### Environment

**OS**: QNAP Container Station 

**Jackett Version**: Jackett Version v0.17.668

**FlareSolver Version**: Last available on Docker

**Are you using a proxy or VPN?** [yes/no] NO

### Description

Hi all,

I try to add Yggtorrent with FlareSolver but it's look like it can connect

On Qnap ContainerStation, I install FlareSolver with a redirecting of port 8191 to 8191 (TCP)
On Jackett, i add FlareSolver url : https://localhost:8191

But it's not working...

### Logged Error Messages

Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:8191) ---> System.Net.Sockets.SocketException (99): Cannot assign requested address at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken) at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, C

**Comment by ilike2burnthing** [comment]
I'm assuming the `https` was a typo and you were using `http`.

Try the local IP of the NAS, the Docker container's IP, or the container's name if you have one set.

**Comment by Mihank1** [comment]
When I check the Docker FlareSolver :
`> flaresolverr@1.2.3 start                                                                                                                                                                                                                                  
> node ./dist/index.js                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                            
2021-03-10T10:07:12.426Z INFO REQ-0 FlareSolverr v1.2.3 listening on http://0.0.0.0:8191                                                                                                                                                                    
npm ERR! path /home/node/flaresolverr                                                                                                                                                                                                                       
npm ERR! command failed                                                                                                                                                                                                                                     
npm ERR! signal SIGKILL                                                                                                                                                                                                                                     
npm ERR! command sh -c node ./dist/index.js                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                            
npm ERR! A complete log of this run can be found in:                                                                                                                                                                                                        
npm ERR!     /home/node/.npm/_logs/2021-03-10T11_04_42_716Z-debug.log                                                                                                                                                                                       
                                                                                                                                                                                                                                                            
> flaresolverr@1.2.3 start                                                                                                                                                                                                                                  
> node ./dist/index.js                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                            
2021-03-10T11:17:51.414Z INFO REQ-0 FlareSolverr v1.2.3 listening on http://0.0.0.0:8191                                                                                                                                                                    
npm ERR! path /home/node/flaresolverr                                                                                                                                                                                                                       
npm ERR! command failed                                                                                                                                                                                                                                     
npm ERR! signal SIGKILL                                                                                                                                                                                                                                     
npm ERR! command sh -c node ./dist/index.js                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                            
npm ERR! A complete log of this run can be found in:                                                                                                                                                                                                        
npm ERR!     /home/node/.npm/_logs/2021-03-10T11_18_26_087Z-debug.log                                                                                                                                                                                       
                                                                                                                                                                                                                                                            
> flaresolverr@1.2.3 start                                                                                                                                                                                                                                  
> node ./dist/index.js                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                            
2021-03-10T11:21:54.171Z INFO REQ-0 FlareSolverr v1.2.3 listening on http://0.0.0.0:8191`

**Comment by Mihank1** [comment]
> I'm assuming the `https` was a typo and you were using `http`.
> 
> Try the local IP of the NAS, the Docker container's IP, or the container's name if you have one set.

Hi,

Thanks for your reply,

I tried both method, but i think it's come from my Flaresolver

**Comment by Mihank1** [comment]
Hi all, 

I've deleted all version of Flaresolver + reinstall and it's now working !
