### ISSUE TITLE
[req] movietorrent

### ISSUE THREAD

**Issue by xplorer990** [Jackett/Jackett#11284]
**Tracker request**

movietorrent.co

Public tracker

Content = Indian movies with many native languages

 https://movietorrent.co/

**Comment by garfield69** [comment]
Its not an idea site for processing by a Jackett indexer
the search results page only has the title and date, all other details such as size, files, grabs, seeders, leechers are on the torrent details page.
magnet link on details page do not have dn or tr.
will need `Torrent Magnet Full Movie Download` and similar removed from results titles
there is no category listed in title cards, so everything will have to be cat=movies
search query is basic, just s= , no sorting, filtering or much else.

**Comment by ilike2burnthing** [comment]
[v0.17.671](https://github.com/Jackett/Jackett/releases/tag/v0.17.671)

**Comment by garfield69** [comment]
https://movietorrent.co/ returning Error 522 Connection timed out
https://www.uptrends.com/tools/uptime reports Http Timeout across all 43 checkpoints worldwide

**Comment by ilike2burnthing** [comment]
Error 521 - Web server is down

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://movietorrent.co/
```
Index of /
  | Name | Last modified | Size | Description
-- | -- | -- | -- | --
  | cgi-bin/ | 2021-11-21 13:38 | - |  
  | download/ | 2023-01-01 14:49 | - |  
  | new-site/ | 2023-10-24 08:57 | - |  
  | old-backup/ | 2020-02-06 07:33 | - |  
  | wp-content/ | 2023-10-27 18:34 | - |  
```

**Comment by garfield69** [comment]
back online but new requires indexer update for new search paths and/or layout

**Comment by garfield69** [comment]
site has switched to a one title many magnets format, which cardigann cannot process.
I will remove the current indexer, and maybe some volunteer will code a C# indexer to handle the new search engine.

**Comment by garfield69** [comment]
v0.21.1096

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
