### ISSUE TITLE
How login works?

### ISSUE THREAD

**Issue by bolach** [Jackett/Jackett#11290]
Hello
How logins to trackers work on jackett? 
Im asking this because some trackers requires login after some X days or the account is disabled.

Jackett will prevent this too?
What trackers will see as login on my account? (without jackett they will see that i use chromium based browser)

**Comment by garfield69** [comment]
>How logins to trackers work on jackett?

It depends on how the indexer is set up, which is based on what the web site is enforcing.
In simplest terms:
In the act of using an indexer (either from the dashboard or via a torznab app), a login may take place if the site request it.
For indexer set up with the cookie method, there is no login. Jackett effectively tries to reuse a session as if it never disconnected.
Some sites have a remember-me checkbox on their login pages. Jackett will used the login cookies saved from the previous successful login, to access the site first, and if the site requests re-login then Jackett initiates a login using whatever the site login method requires.

>Jackett will prevent this too?

No. There is not automated scheduler that logs into all the private indexers regularly.

>What trackers will see as login on my account?

They will see the IP address and the user-agent and whatever other header parms a required to establish a session to the site, as well as whatever cookies the site requested be saved during the session.
