### ISSUE TITLE
[7torrents] Exception (7torrents): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by halorocks982009** [Jackett/Jackett#11291]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [Net-Framework]

**.Net Version**:V4 528372

**Jackett Version**: v0.17.671

**Last Working Jackett Version**: NIL

**Are you using a proxy or VPN?** [no]

### Description

It is in the same directory as chrome but the message still pops up

### Logged Error Messages

Exception (7torrents): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
