### ISSUE TITLE
jackett can't update the latest version 

### ISSUE THREAD

**Issue by vampywiz17** [Jackett/Jackett#1130]
Hi there,

If i try to update, i get this:

Corrent version is:  0.7.1090.0

I don't affect this problem with older releases...

![image](https://cloud.githubusercontent.com/assets/14281430/23503622/cd0f8f10-ff3c-11e6-8d7c-34232cf8e367.png)

**Comment by kaso17** [comment]
That shouldn't be a problem. Fixed it with 6d02e6ab1a0589516c2f272fcf388e17cfa1e8c1.

1090 is the latest stable release, in order to update to 1115 you've to enable "Update to pre-release" in the settings.
