### ISSUE TITLE
Jackett Directs Users to Report FlareSolverr Issues via the Jackett Github Repo

### ISSUE THREAD

**Issue by johnnyxmas** [Jackett/Jackett#11307]
Any errors generated by FlareServerr (and popped-up in the UI) contain instructions to file issues on the Jackett repo. Perhaps add a line with "If this is a FlareServerr Issue. . .?"

Environment
OS: Windows 10 x64 19042

.Net Runtime: [.Net-Core/.Net-Framework/Mono] 4.0.40804

.Net Version: 4.8

Jackett Version: 0.17.671

Last Working Jackett Version: unknown

Are you using a proxy or VPN? [yes/no] yes, PIA

Description
[List steps to reproduce the error and details on what happens and what you expected to happen]

Cause any error to occur via FlareServerr
<img width="1174" alt="Screen Shot 2021-03-13 at 9 16 35 AM" src="https://user-images.githubusercontent.com/6288329/111034903-5874e900-83dd-11eb-8868-7bf00246c01e.png">

**Comment by garfield69** [comment]
good point.
I'll add a test for "check FlareSolverr logs" and redirect to the flaresolverr/flaresolver repo when matched.

**Comment by ilike2burnthing** [comment]
[v0.17.684](https://github.com/Jackett/Jackett/releases/tag/v0.17.684)
