### ISSUE TITLE
[twilight] Login failed: Selector

### ISSUE THREAD

**Issue by gviscardi** [Jackett/Jackett#11303]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Debian Buster / Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.677

**Last Working Jackett Version**: Never tried on another version  

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Attempted to add twilightdreams.com tracker, but it gave an error about Selector.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
Login failed: Selector "a[href="logout.php"]" didn't match

[Make sure you attach the full logs with your personal information removed in case we need more information]

[jackett.log.txt](redaxcted)

**Comment by garfield69** [comment]
It appears you are using a theme (probably the **work in progress Redwood**) that does not have the standard logout href on the browse.php page.
Try using your browser to login to the site and switch the **Theme** to any other and then logout.
The try Jackett again.
Let me know how you go.
P.S. I've removed your log, it contained exposed credentials :-( Remember to edit those out next time to preserve your privacy/security).

**Comment by gviscardi** [comment]
You were absolutely right. Thank you so much for pointing this out!
And thank you about the config, I tried to edit out the details, but I guess I missed some.
