### ISSUE TITLE
[newpct] down 

### ISSUE THREAD

**Issue by diegargon** [Jackett/Jackett#11310]
Newpct url are down
https://pctmix1.com/ works

**Comment by ilike2burnthing** [comment]
https://pctmix.com/ is currently working, but https://pctreload.com/ is redirecting to https://pctreload1.com/

I'll add `mix1` and replace `reload` with `reload1`.

**Comment by ilike2burnthing** [comment]
[v0.17.684](https://github.com/Jackett/Jackett/releases/tag/v0.17.684)
