### ISSUE TITLE
[New Tracker REQ] TorrentCCF

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1131]
**Indexer Name**
TorrentCCF

**Type**
Movies, TV, Audio, XXX, PC, Books, Console, Other

**Indexer URL**
http://et8.org/

**Indexer Language**
Chinese, English

**Invite**
An invite is needed. It would be appreciated if someone can supply one.

**Note**
TorrentCCF is a medium-sized general Chinese tracker with over 20K torrents

**Comment by kaso17** [comment]
added with f4e788f77abcd318d08f92cecc58045d7a716ed5
