### ISSUE TITLE
[torlock] Exception (torlock): certificate validation failed: [Subject]  CN=www.tvicb.com, OU=Telstra Operations, O=Telstra Corporation Limited, L=Melbourne, S=Victoria, C=AU[Issuer]  CN=QuoVadis Global SSL ICA G2, O=QuoVadis Limited, C=BM[Serial Number]  5A5B55982F3BD259BA4F3B1DF21B8E0B6C308217[Not Before]  6/1/2016 12:54:51 PM[Not After]  6/1/2019 12:54:48 PM[Thumbprint]  C1F1745CB17D0D7A270814F70F9DB3A349B99920: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by HiccupHater** [Jackett/Jackett#11315]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Looks like an ISP block. Use one of the indexer's proxies or a VPN.
