### ISSUE TITLE
freshon.tv indexer issue?

### ISSUE THREAD

**Issue by b0r0mir** [Jackett/Jackett#1132]
Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.7.1115.0
Mono version (if not using Windows):  4.6.2

I'm using Jackett with Sonar and it works great with morethan.tv and other tracker. However, freshon.tv is getting crazy results because Sonarr is using TvRageID (rid) which seems to be causing problems.

This is what Sonar sends as query: http://192.168.1.77:9117/torznab/freshon/api?t=tvsearch&cat=5000,5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&rid=33759&season=3

**Comment by flightlevel** [comment]
Can you post the results of http://192.168.1.77:9117/torznab/freshon/api?t=caps&apikey=PUT_YOUR_API_HERE

**Comment by b0r0mir** [comment]
Here it is:
[code]
<caps>
<searching>
<search available="yes" supportedParams="q"/>
<tv-search available="yes" supportedParams="q,season,ep"/>
<movie-search available="no" supportedParams="q"/>
</searching>
<categories>
<category id="5000" name="TV">
<subcat id="5010" name="TV/WEB-DL"/>
<subcat id="5020" name="TV/FOREIGN"/>
<subcat id="5030" name="TV/SD"/>
<subcat id="5040" name="TV/HD"/>
<subcat id="5050" name="TV/OTHER"/>
<subcat id="5060" name="TV/Sport"/>
<subcat id="5070" name="TV/Anime"/>
<subcat id="5080" name="TV/Documentary"/>
</category>
<category id="5030" name="TV/SD"/>
<category id="5040" name="TV/HD"/>
</categories>
</caps>
[/code]

**Comment by flightlevel** [comment]
https://forums.sonarr.tv/t/sonarr-jackett-odd-results-no-hits/13876

Have added comments to your forum post
