### ISSUE TITLE
[req] dontorrents Spanish Public https://dontorrents.net/

### ISSUE THREAD

**Issue by ralinov** [Jackett/Jackett#11322]
[req] dontorrents Spanish Public https://dontorrents.net/

**Comment by ilike2burnthing** [comment]
https://dontorrent.net/ redirects to https://dontorrents.net/ so I'm guessing it's the same as https://github.com/Jackett/Jackett/issues/6214

**Comment by garfield69** [comment]
closing as a duplicate.
