### ISSUE TITLE
[anthelion] Two-factor authentication failed. (Config)

### ISSUE THREAD

**Issue by twizt3dkitty** [Jackett/Jackett#11320]
### Environment

**OS**:  Windows Server 2019 Standard with GUI

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] 4.8

**.Net Version**: 4.8

**Jackett Version**: v0.17.684

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?** no

### Description

Jackett does not support the 2fa when logging into Anthelion if enabled by the end user.  You should be able to use the same code from Nebulance for the 2FA

### Logged Error Messages
N/A doesnt allow you to login

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
I'll try matching the 2fa code from nebulance and see if I can get this to work.

**Comment by garfield69** [comment]
I've added the 2fa code, but I don't have a 2fa-client so I have not tested this.
However I checked that the regular login with the new code still works, which it does, so I'll sub the commit and close.
If someone later uses the 2fa and it does not work, then this ticket can be re-opened to wait for a proper c# dev to fix.

**Comment by garfield69** [comment]
v0.20.1047
