### ISSUE TITLE
[cinemamovies] Specified method is not supported. (Config)

### ISSUE THREAD

**Issue by FloydKulis** [Jackett/Jackett#11338]
### Environment

**OS**: Qnap

**.Net Runtime**: Apache

**Jackett Version**: 0.17.724

**Last Working Jackett Version**: ???

**Are you using a proxy or VPN?** NO

### Description

Unable to log into the website, after entering the cookie, he gets an error.

### Logged Error Messages

 An error occurred while updating this indexer
Specified method is not supported.
Click here to open an issue on GitHub for this indexer.

### Screenshots

![image](https://user-images.githubusercontent.com/37215675/111527721-81d8a080-8760-11eb-9439-004f622c9edf.png)

**Comment by ochidoris** [comment]
Hi,
Try with Jackett Version: 0.17.710

**Comment by garfield69** [comment]
Upgrade your Jackett to version v0.17.728 for fix.
