### ISSUE TITLE
[REQ]pornotorrent.net

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#11346]
Russian public adult torrent sites. 
İt's have big database.

Search engine and torrents working.

http://pornotorrent.net

![3333](https://user-images.githubusercontent.com/36575395/111679845-a0a76780-8832-11eb-96d1-e251bd73d077.JPG)
![4444](https://user-images.githubusercontent.com/36575395/111679852-a1d89480-8832-11eb-8e1b-bbbbe439bc15.JPG)

**Comment by berat1397** [comment]
This two site is friend website but its have different content. Uploading torrent different time. 

![22222ewew](https://user-images.githubusercontent.com/36575395/111699302-fdae1800-8848-11eb-92ca-f3a03db17cae.JPG)
![Uploading 22223232323.JPG…]()

**Comment by berat1397** [comment]
![2223121](https://user-images.githubusercontent.com/36575395/111699605-65646300-8849-11eb-9b50-dee32594ff22.JPG)
![2112](https://user-images.githubusercontent.com/36575395/111699642-76ad6f80-8849-11eb-910a-3c5ba070f6e8.JPG)

erzsebet.nl is new website.

**Comment by ilike2burnthing** [comment]
Error 523 - Origin is unreachable
