### ISSUE TITLE
[REQ]erzsebet.nl

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#11345]
Public russian porn torrent sites
Search engine and torrent working

http://erzsebet.nl

![11](https://user-images.githubusercontent.com/36575395/111679151-0c3d0500-8832-11eb-9a82-c77d78e65592.JPG)
![22](https://user-images.githubusercontent.com/36575395/111679157-0e06c880-8832-11eb-9a80-81221946b44c.JPG)

**Comment by garfield69** [comment]
this appears to be a clone of *.pl, run by the same people, using the same engine and content.

**Comment by berat1397** [comment]
.pl and .nl domains is friend website. They are different website. Erzebet.nl is new website. 

![2112](https://user-images.githubusercontent.com/36575395/111704363-1241de80-8850-11eb-9daf-e4ba1ba3c827.JPG)
![22222ewew](https://user-images.githubusercontent.com/36575395/111704368-140ba200-8850-11eb-8ae6-de5e68784728.JPG)
![2223121](https://user-images.githubusercontent.com/36575395/111704369-14a43880-8850-11eb-905d-14acf9344d68.JPG)
![22223232323](https://user-images.githubusercontent.com/36575395/111704372-153ccf00-8850-11eb-8fc2-ece81bad2aca.JPG)

**Comment by ilike2burnthing** [comment]
Error 523 - Origin is unreachable
