### ISSUE TITLE
[mejortorrent] Exception (mejortorrent): certificate validation failed: [Subject]  CN=www.mejortorrents1.net[Issuer]  CN=

### ISSUE THREAD

**Issue by LechuckThePirate** [Jackett/Jackett#11349]
### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core]

**.Net Version**: 3.1

**Jackett Version**: v0.17.738

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

Mejortorrent not working

### Logged Error Messages

Exception (mejortorrent): certificate validation failed: [Subject] CN=www.mejortorrents1.net [Issuer] CN="allot.com/emailAddress=info@allot.com", OU=Allot, O=Allot, L=Madrid, S=Madrid, C=ES [Serial Number] 0094412C6000000000D016000000000000 [Not Before] 12/16/2016 2:07:49 PM [Not After] 12/16/2026 2:07:49 PM [Thumbprint] 0E93E5DF953C40A7E01F6010800207B1F17F2B0A : The SSL connection could not be established, see inner exception.

### Screenshots
![image](https://user-images.githubusercontent.com/4067255/111757209-60300400-889b-11eb-9708-02f4d84bf771.png)

**Comment by ilike2burnthing** [comment]
Working ok here, but in browser I get a completely different certificate.

Try removing the indexer, restarting Jackett, and then re-adding the indexer.

**Comment by garfield69** [comment]
Mejortorrent use cloudflare services so the legitimate certificate is issued to sni.cloudflaressl.com
The cert the OP is seeing is issued to Allot Madrid
Either the ISP or a security app on windows is blocking access to mejortorrent and redirecting to a black hole.

The OP needs to either whitelist the address in their security app or use a VPN or proxy or try switching DNS from the ISP provided one to a public one such as cloudflare's 1.1.1.1 or Google's 8.8.8.8

**Comment by LechuckThePirate** [comment]
Thanks ... I'll try to remove and add againç

**Comment by LechuckThePirate** [comment]
Didn't work.. I assume the government must be blocking the dns then ... thanks anyway
