### ISSUE TITLE
AlphaRatio Tracker Missing

### ISSUE THREAD

**Issue by sudoalias** [Jackett/Jackett#1134]
Jackett version: 0.7.1090
Mono version (if not using Windows):  4.7.0

I am not seeing AlphaRatio in the list to add tracker.  It used to be there a few months ago, but I just did a fresh install and am not seeing it.  I see that the tracker is still in the Indexers folder, and listed as supported on the site, but I don't see a Definition file for it, so maybe that is why it isn't showing up, I am not sure.

**Comment by flightlevel** [comment]
Most likely a cache issue
Try opening in a private/incognito window and try a different web browser as well to determine
It only needs to be in indexers OR definitions

**Comment by kaso17** [comment]
If the definition file is missing something went wrong with the installation. please check your permissions.
The Indexers folder contains only the config files.

**Comment by RoloSoze** [comment]
@sudoalias Did @flightlevel's or @kaso17's suggestions solve this issue for you?

**Comment by sudoalias** [comment]
Flightlevel's did, although Kaso brings up an interesting point.
