### ISSUE TITLE
[torrent9] Exception (torrent9): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by Whisper40** [Jackett/Jackett#11350]
Torrent9 est bugged, connection sometimes broken, and search is bugged
Version : latest (Version v0.17.737)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured

**Comment by Whisper40** [comment]
No, i don't speak about ygg but torrent click here : https://torrent9.to/search_torrent/Dr-Harrow.html
You just can't access the page because torrent9 is bugged, so Jackett is bugged too because of Torrent9

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/1067#issuecomment-802765632
