### ISSUE TITLE
MoreThanTV requires frequent reconfiguration

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#1135]
I believe MoreThanTV has made a change over the past couple of days. The site now logs me out every few hours (on the browser as well), and as such, I frequently need to reconfigure it in Jackett. I think auto re-login might be necessary. 

Jackett version:  0.7.1115.0
Mono version (if not using Windows):  N/A

**Comment by kaso17** [comment]
added with 2561415847c4d5a6aef50f89c440d18afe96cadb
