### ISSUE TITLE
torrentz2k: search is not working as expected

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#11365]
* Do an empty search => ok
* Search with 1 word => ok
* Search with 2 words => ko

Example search: Zack Snyders

**Comment by garfield69** [comment]
the web site is auto-redirecting some searches from https://torrentz2k.xyz/ to https://torrentz2is.me/search/ which has a slightly different HTML

I'll dig deeper and see if the indexer can cope with results from both .xyz and *is.me

**Comment by garfield69** [comment]
cant be done. 
since *.xyz wants to use *is.me then I propose switching to using *is.me full time.
