### ISSUE TITLE
No redirect with changed base url

### ISSUE THREAD

**Issue by fryfrog** [Jackett/Jackett#1136]
At initial setup, if you visit http://localhost:9117/ it redirects to http://localhost:9117/Admin/Dashboard and works great. After you add a base url, going to http://localhost:9117/ works still and redirects to http://localhost:9117/jackett/Admin/Dashboard nicely.

But if you go to http://localhost:9117/jackett, it doesn't redirect.

So reverse proxy to it doesn't work super nicely, instead of using /jackett you actually have to use the full /jackett/Admin/Dashboard.

Would be nice if / and /base_url did the same redirection. :)

**Comment by kaso17** [comment]
cdf11067a281fcc826accd4e394afa7b3bf2942c might fix it

**Comment by RoloSoze** [comment]
@fryfrog Did cdf1106 fix the problem for you?

**Comment by RoloSoze** [comment]
@fryfrog Please feel free to reopen this issue if cdf1106 hasn't fixed it for you.

**Comment by fryfrog** [comment]
It mostly works. If I go to ./jackett/, the redirect works. But if I go to ./jackett it doesn't. I'll accept that, but it'd be nice if that got fixed too. Re-close if wontfix.

**Comment by kaso17** [comment]
@fryfrog is this still a problem in the latest version?

**Comment by fryfrog** [comment]
It still behaves as last described, requires a `/` at the end of the URL for redirect to work. That is far better than at the start and wouldn't be the only daemon that needs the `/` at the end to work.

**Comment by kaso17** [comment]
I tried this using apache:
`ProxyPass /jackett http://127.0.0.1:9117/`
Jackett Base Path Override option: /jackett

http://127.0.0.1/jackett works for me as expected.
Can you please share your configuration?

**Comment by fryfrog** [comment]
```
  <Location /jackett>
    ProxyPass http://10.0.1.2:9117/jackett
    ProxyPassReverse http://10.0.1.2:9117/jackett
  </Location>
```
