### ISSUE TITLE
oncesearch: unrelated results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#11376]
"query": "silicon valley"
"query": "Harry Potter"

**Comment by ilike2burnthing** [comment]
Site is matching content of description as well, rather than just title. Do we want to remove those with andmatch?

**Comment by ngosang** [comment]
I'm not sure. Wait for @garfield69 

Some download links are missing too:
![image](https://user-images.githubusercontent.com/10577978/111914283-a939b100-8a71-11eb-83f7-2232fb93f52e.png)
