### ISSUE TITLE
[empornium] down - ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#11372]
https://empornium.me/ - ERR_CONNECTION_TIMED_OUT

**Comment by Tmp341** [comment]
Found alternative url, don't know if they are same: [https://www.empornium.sx](https://www.empornium.sx)

**Comment by ilike2burnthing** [comment]
Do you have an account? Are you able to login?

**Comment by Tmp341** [comment]
> 
> 
> Do you have an account? Are you able to login?

No, i don't. 😐

**Comment by garfield69** [comment]
I have an account, however it was disabled for inactivity so I cant complete the login.
BUT
I tested both https://empornium.sx and https://www.empornium.is and both domains responded that my a/c was disabled, so the fact that both domains knew who I was implies that these domains are legitimate alternates to the *.me domain.
So I will add them to the indexer. 
Thanks.

**Comment by garfield69** [comment]
v0.17.797
