### ISSUE TITLE
Can't add Redacted since name was changed

### ISSUE THREAD

**Issue by fana13** [Jackett/Jackett#1137]
Hi,

Since PTH changed to RED name, i can't add it.
When i want to add it i've got this message : 

`Configuration failed : Something went wrong. You have 5 attemps remaining. WARNING: You will be banned for 6 hours after your login attempts run out!`

Obviously i'm sure to my id/pwd.
I've enable the 2FA, do you think that may cause errors here ?

**Comment by kaso17** [comment]
2FA is not supported
