### ISSUE TITLE
torrentqq: invalid download links

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#11389]
![image](https://user-images.githubusercontent.com/10577978/111915367-31ba5080-8a76-11eb-956c-54f6052f6107.png)

**Comment by garfield69** [comment]
This is a known issue. The config for this indexer has a warming about this site download links.

I know of no way to avoid the issue ATM.

Site's results page does not have magnets or .torrents or infohash
The details page has no magnets or infohash, but a single download href.

Essentially we look for `a[href^="/torrent/download/"]` on the details page, which matches for example, `https://torrentqq79.com/torrent/download/304966`,  and this in turn it may delivers a 3rd party redirect, for example to  `https://www.filetender.com/kru3W2`.
If the 3rd party does not return a .torrent, but instead presents a HTML page with a `Invalid URL, Filename: file not found` error message, or an HTML with a a countdown `You can download the file in XX seconds.` then Jackett's download breaks.

**Comment by ngosang** [comment]
We can do a trick.

Details => https://torrentqq79.com/torrent/med/419131.html
Torrent (not working redirect) => https://torrentqq79.com/torrent/download/304966
Magnet => https://torrentqq79.com/torrent/magnet/304966

If you can replace the word download => magnet it should work for all torrents.

Btw, there is an infohash => 
![image](https://user-images.githubusercontent.com/10577978/112378395-2a4dae00-8ce7-11eb-85d5-668e046ea6ec.png)

**Comment by garfield69** [comment]
does not work :-(
https://torrentqq79.com/torrent/magnet/304966 returns 
```html
<script>document.location.href="magnet:?xt=urn:btih:df26a0a25737eb4fdef27df651e9cc221835a51e";</script>
```
which the cardigann download processor is not expecting.

Also, while the infohash may be available on the details page, the cardigan processor's details-page-download block does not have that function.

**Comment by garfield69** [comment]
note:  d2906b4 is untested, as I get a flaresolverr timeout on the cloudflare check when I attempt to use the indexer.

**Comment by garfield69** [comment]
v0.18.666
