### ISSUE TITLE
when adding Torrentday, jackett gives error: Exception in GetConfigForm

### ISSUE THREAD

**Issue by ArjenD** [Jackett/Jackett#1138]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
works for me, please prove an enhanced log

**Comment by RoloSoze** [comment]
@ArjenD Could you please post an enhanced log showing this issue so that @kaso17 can work on resolving it? Thank you.

**Comment by ArjenD** [comment]
sorry for the late post. the system (orange pi) where jackett was running on, crashed.... and an install on antoher system ( synology ) works like a charm.
so, ignore this issue.
