### ISSUE TITLE
ebooks-shares: add an option to exclude vip torrents

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#11387]
Torrents in VIP categories can't be downloaded by regular users. There are several possibilities:
1) Add an option to exclude results with the word `VIP:` in the category name
2) Add the word VIP in the title. The user will be able to filter

![image](https://user-images.githubusercontent.com/10577978/111915018-abe9d580-8a74-11eb-8bf2-99ab2500974c.png)

**Comment by garfield69** [comment]
you are the only one with an a/c

**Comment by garfield69** [comment]
v0.20.363
