### ISSUE TITLE
[REQ] TheMixingBowl (TMB)

### ISSUE THREAD

**Issue by Czechball** [Jackett/Jackett#11399]
URL: [themixingbowl.org](https://tmb.dj/) or [tmb.dj](https://tmb.dj)
Type: semi-private, open registration

**Comment by garfield69** [comment]
v0.17.790

**Comment by garfield69** [comment]
https://tmb.dj/ returns
![image](https://user-images.githubusercontent.com/6933240/166133761-0b915f79-6a1d-4966-8a82-dcabd3979d5d.png)

**Comment by Czechball** [comment]
Site is back online, both domains

**Comment by Czechball** [comment]
Both domains are back up.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/11399#issuecomment-1114139180

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://tmb.dj/ > cloudflare  Origin is unreachable Error code 523   OR cloudflare  Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up
