### ISSUE TITLE
[kickasstorrents-ws] Exception (kickasstorrents-ws): The response ended prematurely.: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by ChrisHook** [Jackett/Jackett#11391]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
the indexer works for me so the problem is likely at your end. Your ISP may be blocking your access.
Access your Jackett dashboard, edit the indexer config and try any of the alternate site links and see if any of them work for you.
If none work then provide the details requested in the first post, or forget about it.

**Comment by ChrisHook** [comment]
Thanks, sorry didn't mean to submit an error.
I reset my docker container and all is working now.
