### ISSUE TITLE
Error while parsing on M-Team - TP tracker

### ISSUE THREAD

**Issue by testarea1** [Jackett/Jackett#1139]
Jackett version:  0.7.1115.0
Mono version (if not using Windows):  4.8.0
-------------------------------
Receiving multiple errors when Jackett searches M-Team - TP tracker: 
`CardigannIndexer (mteamtp): Error while parsing row '<tr> <td class="rowfollow nowrap" valign="middle" style="padding: 0px">` 
or
`System.Exception: Error while parsing field=date, selector=td.rowfollow:nth-child(4) > span[title], value=<null>: Selector "td.rowfollow:nth-child(4) > span[title]" didn't match <tr> <td class="rowfollow nowrap" valign="middle" style="padding: 0px">`

They all seem to end with:
`at Jackett.Indexers.CardigannIndexer+<PerformQuery>c__async5.MoveNext () [0x0136c] in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:1353`

No results are being added to jackett for me because of these errors.

**Comment by kaso17** [comment]
working for me, please enable enhanced logging and post alog

**Comment by testarea1** [comment]
Here is an enhanced log
[log.20170305.00146.txt](https://github.com/Jackett/Jackett/files/819736/log.20170305.00146.txt)

**Comment by kaso17** [comment]
fixed wtih 3b0cfa4aba361572fa0849cde768e5c21afb39fb
