### ISSUE TITLE
[elitetracker] The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject]  CN=elite-tracker.net[Issuer]  CN=R3, O=Let's Encrypt, C=US[Serial Number]  03D27C42B719E4E918E95C9ED5FEF05EB0BB[Not Before]  12/23/2020 8:02:09 AM[Not After]  3/23/2021 8:02:09 AM[Thumbprint]  0A56D83ECFB42F8968C08E0D081AC881F6347F62 (Config)

### ISSUE THREAD

**Issue by thiryjer** [Jackett/Jackett#11400]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Looks like their certificate lapsed, but it's fine now.
