### ISSUE TITLE
[REQ] POTUK

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#11402]
**potuk.net** - https://www.potuk.net uses XenForo forum software as far as I know.

**private**  - I have an invite ready just let me know the email address to send it to.

The site provides both .torrent or magnet.

**Comment by garfield69** [comment]
Not written an indexer for XenForo so we will see if we can code one for yaml or if we have to resort to C#

before you send me an invite, check out the site and answer these:
does the site's torrent search engine return one torrent title for one torrent file, or does it have a one-title-many-torrents structure?

If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by swannie-eire** [comment]
> Not written an indexer for XenForo so we will see if we can code one for yaml or if we have to resort to C#
> 
> before you send me an invite, check out the site and answer these:
> does the site's torrent search engine return one torrent title for one torrent file, or does it have a one-title-many-torrents structure?
> 
> If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
> But if the site turns out to require a native c# indexer then I will not be able to complete the task.

So if you search for a specific torrent you will get a result of the threads matching that search string. within the thread there is the option to download the torrent or the magnet link.

Below is a screenshot of the result of searching for the string "Snowfall s04e01".
https://imgur.com/a/jKTDg6K

Below is a screenshot of one of the results from the previous screenshot thread. 
https://imgur.com/Bp83GTf


Being honest with you I would be surprised if you were able to create an indexer since the site is basically a forum and not a  torrent site like we see so many others use.

invite sent.

**Comment by garfield69** [comment]
Registration and login successful. Thank you. 
Right, lets take a looksee and see what I can cook up.

**Comment by garfield69** [comment]
v0.17.794

**Comment by swannie-eire** [comment]
@garfield69 

Just want to say thanks. Can't believe you manage to get it done so quickly.

I tested and it works like a dream with qbittorrent plugin.

**Comment by swannie-eire** [comment]
It was fine earlier.

I will say it to the staff

**Comment by garfield69** [comment]
https://www.potuk.net/ (once logged in) Sorry, we're currently unavailable. Looking into a database corruption which cant leave the board open until I can fix. Will be looking into a fix and repair in about 12 hours from now. Fingers Crossed

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.potuk.net/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.potuk.net/ Sorry, we're currently unavailable. Looking into some gremlins.. will be back soon.

**Comment by garfield69** [comment]
v0.22.735
