### ISSUE TITLE
torrentday/torrentleech/torrenting not grabbing x265

### ISSUE THREAD

**Issue by aser007** [Jackett/Jackett#1140]
torrentday/torrentleech/torrenting not grabbing x265 in Sonarr
it shows in Jakett but Sonarr doesnt grab it:
TorrentDay	Taken 2017 S01E01 1080p HEVC x265-MeGusta	423 MB		TV/HD

**Comment by kaso17** [comment]
please provide a log showing the search query from sonarr

**Comment by aser007** [comment]
Sonarr doesnt grab Jackett´s x265 Files
Example Jackett search 4 "Taken x265":

2d ago TorrentDay Taken 2017 S01E01 1080p HEVC x265-MeGusta 423 MB TV/HD 24 0 1 1
4d ago TorrentDay Taken S01E01 720p HEVC x265-MeGusta 209 MB TV/HD 124 6 1 1
82d ago TorrentDay The First 48 S16E02 Taken for a Ride 720p HEVC x265-MeGusta 268 MB TV/HD 6 0 1 1
2y ago TorrentDay Taken 3 (2014) BRRip x265 HEVC HQ-CPG 748 MB Movies/HD 2 0 1 1

if it try to grab the Taken 2017 S01E01 1080p HEVC x265-MeGusta in sonarr i only get the non x265 Releases:

Taken 2017 S01E01 1080p HDTV x264-CRAVERS Torrentday 1.5 GB 4 / 1 HDTV-1080p
Taken 2017 S01E01 1080p HDTV x264-CRAVERS Torrenting 1.5 GB 4 / 1 HDTV-1080p

**Comment by aser007** [comment]
Sry 4 the^Fuckup  i just fixed it^^ i falsely put in the torrenting Torznab Feed into torrentday with the torrentday feed all works great now opps;)
