### ISSUE TITLE
Additional option in MVGroup to strip "CH5." from front of torrent name

### ISSUE THREAD

**Issue by thunderousleader10** [Jackett/Jackett#11414]
Basically the same as #2367 but for Channel 5 which is prefixed at the start of a torrent's name as CH5. It would be great to have an option that removed this prefix from a search. While we're here it might be a good idea to put in a similar option for other channels such as Channel 4 (CH4) etc. Thanks!

**Comment by garfield69** [comment]
found BBC, PBS, Ch5, Ch4, DC, DW, HC, RTE, ITV, HBO, NHK, UKTV, NOVA, TV5Monde, Al-Jazeera

if there are any others please specify here at any time and I will add them to the code.

**Comment by garfield69** [comment]
v0.17.790
