### ISSUE TITLE
Config Disappeared after Plex Update

### ISSUE THREAD

**Issue by ROODAY** [Jackett/Jackett#11425]
### Environment

**OS**: Ubuntu 20.04.2 LTS

**.Net Runtime**: Mono

**.Net Version**: 6.12.0.122

**Jackett Version**: 0.17.794

**Last Working Jackett Version**: 0.17.794

**Are you using a proxy or VPN?** no

### Description

So for context, I had a setup involving Plex and Jackett working fine for a long time, but I would have to manually update Plex (as in the Web UI would say I have an update, I'd download the deb file, transfer to my server, then run `sudo dpkg -i filename`). Eventually I got tired of the manual updates and looked into setting up auto update, so I followed the Plex instructions on getting the source setup and ran `sudo apt-get upgrade plexmediaserver`, and it went through pretty much the same process as the manual installation. But after the apt-get upgrade, my Jackett config was gone (i.e. all the trackers were missing and I had to add them back).

Since then I've just been manually installing Plex updates again (because even with the sources setup it's not updating itself automatically, not sure if that's something I have to enable elsewhere), and I haven't had issues with Jackett. But I'd like to get to the bottom of this so I can automate the updating without worrying about Jackett, so is this an issue someone else has run into before? Are there any steps I should take to debug?

### Logged Error Messages

Don't have any at the moment since this happened a while ago and I've been avoiding the Plex apt upgrades until I figure out the cause.

**Comment by garfield69** [comment]
you may have something similar to #11313
take a look at your Jackett folders and see if any contains the two folders `DataProtection` and  `Indexers` and the file `ServerConfig.json`
and if you find them then do the following:

shutdown the jackett service
copy those folders and file to `/home/jackett/.config/Jackett`
startup the service.
see if that helps.

**Comment by ROODAY** [comment]
Hmm so I have jackett installed in `/home/jackett` (`/home/jackett/Jackett` and `/home/jackett/,config` are there). Inside `/home/jackett/.config/Jackett` I see the `DataProtection` and `Indexers` folders as well as the `ServerConfig.json` file. However, inside `/home/jackett/Jackett/Jackett` I see those same folders and files. Is this due to an old misconfiguration? Can I delete `/home/jackett/Jackett/Jackett` so that there's only one source?

**Comment by garfield69** [comment]
yes, some miss-config occurred in the past, its not clear how that came about.
I would first copy and confirm that the official config path restores your api key and active indexers, and after that feel free to delete the old files in the old path.
let me know how you go so I can close the ticket if all is well.

**Comment by ROODAY** [comment]
Just tried and it worked! I moved the official config path `Jackett` folder and my settings were wiped, so I deleted the weird path `Jackett` folder and put the official one back and it's all good! Going to back up that folder moving forward just in case, thanks!
