### ISSUE TITLE
System.Exception: BencodeParser failed ( lesaloon )

### ISSUE THREAD

**Issue by dan3805** [Jackett/Jackett#11420]
lesaloon , ( after cloudflare ddos protection setting change ) 

first message says 
''you are not allowed to download new torrents due to your hits and run, to unlock downloads you will need to either share what you have already downloaded or refund your hits and run! ''

but it has no hit and run on my account (checked with the staff) (and anyway I cannot have a hit and run on this site with my rank)
<img width="1169" alt="Capture d’écran, le 2021-03-28 à 01 35 52" src="https://user-images.githubusercontent.com/35934387/112743511-fe8c2b80-8f65-11eb-99b4-3d2ea276baab.png">

(in radarr / sonarr ) sometimes it work perfectly after the first manual attempt or automatic attempt ,sometimes after 5-6 tries, sometimes after 30-40 tries

<img width="801" alt="Capture d’écran, le 2021-03-28 à 01 12 08" src="https://user-images.githubusercontent.com/35934387/112743139-af90c700-8f62-11eb-8964-efc0bd4da2f4.png">
<img width="1168" alt="Capture d’écran, le 2021-03-28 à 00 58 02" src="https://user-images.githubusercontent.com/35934387/112743527-182d7300-8f66-11eb-969c-09c5b3e53d23.png">

**Comment by dan3805** [comment]
the staff informs me that for a very long time they have problems of "ghost torrent" with jackett. 

users get hit and run from torrents they never downloaded and it's only with jackett users

maybe there is a problem with jackett? 

maybe it would be better to communicate with them. I can put you in contact if you need

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/10287

**Comment by EricG66** [comment]
@garfield69 I have this problem since couple of days:

![msedge_pT4VS6HV4r](https://github.com/Jackett/Jackett/assets/7593272/a616be43-eac0-43ed-8b3d-1a1ff6a159a8)

**Comment by ilike2burnthing** [comment]
See the linked issue.
