### ISSUE TITLE
EXT Torrents [exttorrents] Exception (exttorrents): certificate validation failed: [Subject]  CN=protected-browsing-enabled, OU=Engineering, O=Shaw Communications, L=Calgary, C=CA[Issuer]  CN=protected-browsing-enabled, OU=Engineering, O=Shaw Communications, L=Calgary, C=CA[Serial Number]  00A54B7749C530676E[Not Before]  2/5/2019 8:13:41 AM[Not After]  2/2/2029 8:13:41 AM[Thumbprint]  EE2D0CF9A56B920F540E637C1B2729A6F00CF859: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by alperreault** [Jackett/Jackett#11431]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
The official certificate for EXT Torrents is from cloudflare, where as you are seeing one issued by Shaw Communications.
This means that your ISP is blocking access to the site. 
Consider using a VPN or switching your DNS from the one your ISP provides to a public one , such as 1.1.1.1 from Cloudflare or 8.8.8.8 from Google.
