### ISSUE TITLE
[req] TNT Village fork https://www.tntfork.it/ public Italian

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#11430]
mirror for the archive published by tntvillage

**Comment by ftruzzi** [comment]
Thanks for wanting to work on this, but please consider a different source for the TNT Village DB, as TNTFork hashes/magnet links can be "censored" forever just by clicking "censura" next to every link which means the DB is already incomplete.

Example: https://www.tntfork.it/index.php?titolo=star+wars&descr=&cat=

Here's a full DB dump https://archive.org/details/dump_release_tntvillage_2020-05-06 -- if you don't want to support static archives maybe we should think about hosting it somewhere else in a way that's easy for Jackett to parse.

**Comment by garfield69** [comment]
Jackett indexer logic deals with web sites, and are only capable of processing HTML, or an API that returns JSON, or XML.
We will not support anything else.
If you feel creating this indexer for tntfork is a waste of time then I will close the ticket.

**Comment by garfield69** [comment]
the tntfork  presents html content for censored magnets as
```html
    <tr>
        <td>2019-08-14T15:33:29</td>
        <td>
            <a href="magnet:?xt=urn:btih:FAC3809C3B0749E04F3908FE7A66FF354742A2C5&dn=&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopentor.org%3A2710&tr=udp%3A%2F%2Ftracker.ccc.de%3A80&tr=udp%3A%2F%2Ftracker.blackunicorn.xyz%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969">FAC3809C3B0749E04F3908FE7A66FF354742A2C5</a>
        </td>
        <td>Elementary S07e08 Versione 720p</td>
        <td>[Mux 720p - H264 - Ita Mp3] DLMux - IperB [CURA] Sherlock Holmes</td>
        <td>Serie TV</td>
        <td>0.45</td>
        <td>
            <button onclick="showconfirm('FAC3809C3B0749E04F3908FE7A66FF354742A2C5')">Censura</button>
        </td>
    </tr>
```
as you can see the magnet is there, so I don't see any problems.

**Comment by ftruzzi** [comment]
> Jackett indexer logic deals with web sites, and are only capable of processing HTML, or an API that returns JSON, or XML.
> We will not support anything else.

I understand, makes sense!

> If you feel creating this indexer for tntfork is a waste of time then I will close the ticket.

I don't think it's a waste of time, as it would be very useful even with a few censored links. My concern would be the fact that the number of "censored" links can only increase over time.

> as you can see the magnet is there, so I don't see any problems.

Is that a censored link? Here's what I see for the first "star wars" entry:

```html
<tr>
  <td>2019-06-23T23:54:37</td>
  <td>
    <a
      href="magnet:?xt=urn:btih:Censurato&amp;dn=&amp;tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&amp;tr=udp%3A%2F%2Fopentor.org%3A2710&amp;tr=udp%3A%2F%2Ftracker.ccc.de%3A80&amp;tr=udp%3A%2F%2Ftracker.blackunicorn.xyz%3A6969&amp;tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&amp;tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969"
      >Censurato</a
    >
  </td>
  <td>Star Wars Resistance S01e01-21</td>
  <td>
    [Mux 720p - H264 - Ita Eng Ac3] WEB-DL - Fantascienza - Stagione Completa
    [CURA] Star Wars
  </td>
  <td>Cartoni</td>
  <td>11.74</td>
  <td><button onclick="showconfirm('Censurato')">Censura</button></td>
</tr>
```

I found another website hosting the full dump, maybe it can be considered as well. The drawback is that is doesn't show file sizes. http://tntvillage2.altervista.org/index.php

**Comment by garfield69** [comment]
Are you using the **view source page** option **Ctrl-U** on chrome browser?
Then you are seeing the HTML after it has been processed by JS.
Instead, open the development tools with **F12**, click on the **Network**, refresh the page with **F5**, click on the `index.php?` in the name column, click on the **response** tab, and view the HTLM as it is presented to the browser raw.
This is the HTML that Jackett sees.

**Comment by ftruzzi** [comment]
I see, but I think you looked at the HTML of an uncensored link. Censored links have `Censurato` in the second column and the related magnet link is invalid (has no hash)

https://www.tntfork.it/index.php?titolo=Elementary+S07&descr=&cat=

You posted HTML for line 4 (highlighted in the screenshot), but that is an uncensored link. Line 2 is censored and has an invalid magnet link even in the raw HTML response.

![image](https://user-images.githubusercontent.com/461133/112906400-6a989c00-90ec-11eb-8bf5-dd3fdb452983.png)

**Comment by garfield69** [comment]
OK, I see that now.
So there are two kinds of censored magnets in the DB, one which is cosmetically censored but yields a good magnet when you click the link, and onother that has actually had its infohash replaced. 

Well, the tntfork indexer is ready, so I either publish it, or wait for you to find a better site.

**Comment by ftruzzi** [comment]
> Well, the tntfork indexer is ready, so I either publish it, or wait for you to find a better site.

If it's ready, then by all means please go ahead and publish it! And thank you :)

**Comment by garfield69** [comment]
v0.17.815

**Comment by Fieel** [comment]
Thank you @garfield69 for this! Any plans on using a different database in the future given how volatile TNTfork is (the ability to freely remove links is frightnening)

**Comment by garfield69** [comment]
@Fieel wrote: 
>Any plans on using a different database in the future

If you can find a TNT DB that has a minimum of:
title, category, size, magnet (full URL or just the infohash),
and optionally one or more of date, files, grabs (completed), seeders and leechers
then I will look at creating an indexer for it.
Anything less is just not worth the time to implement as you will not get any benefits displaying the results on the Jackett dashboard.

**Comment by garfield69** [comment]
https://www.tntfork.it/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://www.tntfork.it/ returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.tntfork.it/ returning ERR_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://tntfork.it/ is returning ERR_CONNECTION_RESET or ERR_CONNECTION_CLOSED

**Comment by ElDavoo** [comment]
DNS_PROBE_FINISHED_NXDOMAIN :(

**Comment by garfield69** [comment]
v0.18.887

**Comment by Fieel** [comment]
offline forever?

**Comment by ElDavoo** [comment]
yes, domain hasn't been renewed

**Comment by Fieel** [comment]
Do we have any kind of fallback for the TNTVillage library? Or can we donate to keep up the domain?
