### ISSUE TITLE
REQ TheScenePlace.com

### ISSUE THREAD

**Issue by nexus382** [Jackett/Jackett#11433]
*Hi there. I am an owner of the tracker, TheScenePlace (TSP) I was hoping that we could get on the jacket list. I had you guys add another site I ran about a month ago, TheLeachZone.Digital. We are a Privatetracker, Doors are opened at the moment, and if there is anything else you need, please let me know, but loads of our members have been asking for us to get on the JACKETT list

If there is any more you need feel free to email me at A91Ant@gmail.com 

Thank you very much I hope you have a great day!

**Comment by garfield69** [comment]
TheScenePlace (TSP) https://www.thesceneplace.com/ Private MR 1.0 MST 72h ENGINE xbtitFM v3.1.00

**Comment by garfield69** [comment]
v0.17.815

**Comment by garfield69** [comment]
v0.17.952

**Comment by garfield69** [comment]
https://www.thesceneplace.com/ returning ERR_CONNECTION_TIMED_OUT or ERR_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.thesceneplace.com/ returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/11433#issuecomment-1236048714

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/11433#issuecomment-1236048714

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/11433#issuecomment-1236048714

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/11433#issuecomment-1236048714

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/11433#issuecomment-1236048714

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/11433#issuecomment-1236048714

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/11433#issuecomment-1076653464

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/11433#issuecomment-1076653464

**Comment by garfield69** [comment]
@nexus382  any news on the state of theScenePlace, is the site GONE, just BROKEN, or moved to a new DOMAIN?
In about a week we will remove this indexer from Jackett if there are no updates.

**Comment by garfield69** [comment]
v0.22.1074
