### ISSUE TITLE
Impossible to launch a manual update with prerelease

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#1143]
It tryin to call 2017-03-05 22:00:13.9172 Error IWebClient.GetString(Url:https://api.github.com/repos/Jackett/Jackett/releases): No encoding detected, defaulting to UTF-8 

which send a request to https://api.github.com/repos/Jackett/Jackett/releases): 
instead of https://api.github.com/repos/Jackett/Jackett/releases

**Comment by kaso17** [comment]
The encoding error isn't critical and was already fixed.
These are the same URLs, it should work perfectly fine.
Please post the following log lines.

**Comment by raspdealer** [comment]
Ok related to #1123
But even after, back to old update issues on rpi :(
