### ISSUE TITLE
[Req]: Greek Team

### ISSUE THREAD

**Issue by valantislevas** [Jackett/Jackett#1144]
https://www.greek-team.cc/
Greek Team is a GREEK Private site for TV / MOVIES / GENERAL

Hello is possible to make it work with these tracker? because i cant send invite for it.. if @kaso17 want i can send you on your mail my informations to get test for it..

thnx and this tracker is very big.. i also cant see atm what template is using but i think if you check it you will find it..

thanks

**Comment by kaso17** [comment]
I assume account sharing is not allowed. So an invite is required.

**Comment by valantislevas** [comment]
can you tell me your mail? to send invite?

**Comment by dpmdiego** [comment]
Guys, someone has an invitation to arabafenice?

**Comment by kaso17** [comment]
got the invite, thank you

**Comment by dpmdiego** [comment]
@kaso17  Nothing arrived in my email.
Confirming my email, imdiegodpm@gmail.com
If you want, I can send you one from a Brazilian community.
Thanks man.

**Comment by valantislevas** [comment]
thanks also i think the file are using is TorrentStrike template

**Comment by kaso17** [comment]
added with 0f639d23442aa40cf7098ebcf32f5227c0b20427

**Comment by kaso17** [comment]
in 2-3 hours

**Comment by aka-charos** [comment]
Not working here (Jackett Version 0.7.1197.0) . Test fails with 

> Found no results while trying to browse this tracker

Also manual search queries give no result

**Comment by RoloSoze** [comment]
@aka-charos Please post an enhanced log showing this issue.

**Comment by aka-charos** [comment]
[log pastebin](http://pastebin.com/raw/Df1Z8x2i)

I can see errors related to DateTime

**Comment by kaso17** [comment]
@aka-charos is this still a problem?

**Comment by valantislevas** [comment]
mine is working.. 
Jackett Version 0.8.409.0

**Comment by aka-charos** [comment]
@kaso17 yes, it works now.

**Comment by jgatis** [comment]
Hello, is there any chance that you have a spare invite for greek-team.cc, i can't manage to find one, i had an account before but for some reason is disabled, my e-mail is jgatis@gmail.com, thank you

**Comment by CFSpy** [comment]
Hello there,
Please is it possible for someone, to send me also an invite for greek-team tracker? Thank you!

**Comment by garfield69** [comment]
https://www.greek-team.cc/ DNS_PROBE_FINISHED_NXDOMAIN (DNS Lookup Error)

**Comment by garfield69** [comment]
@valantislevas do you have any news about GreekTeam, is the site gone, just broken, or moved to a new domain?
The indexer will be removed in about 4 days.

**Comment by ilike2burnthing** [comment]
Do your login credentials work for https://www.greek-team.eu/ ? No idea if it's even related, just came up on google.

**Comment by ilike2burnthing** [comment]
I applied an hour ago to see if I could work out what the site even is, but it's just been 'awaiting validation' since, and no email through yet.

**Comment by ilike2burnthing** [comment]
Account was approved, aaaaaaand it's DDL. So close.

**Comment by garfield69** [comment]
v0.21.1560
