### ISSUE TITLE
[BUG]: Every search results is duplicated

### ISSUE THREAD

**Issue by movianlost** [Jackett/Jackett#11450]
When I do a search using Yggtorrent, every search results is duplicated as shown in this screenshot; 
https://i.imgur.com/j8YgIS5.png

Is this because Jackett is calling Yggtorrent multiple times?

**Comment by garfield69** [comment]
Probably.
Either the site has changed the way they present results and the indexer needs updating,
OR
Whoever last updated the indexer did not do a very good job testing their changes ;-D

@ilike2burnthing  I am not interested in maintaining this indexer, so do you want to have a look at it? thanks.

**Comment by ilike2burnthing** [comment]
It was the least bad fix for a bad indexer for a worse site - https://github.com/Jackett/Jackett/pull/9114

The site uses inconsistent naming schemes for seasons, a mix of both `Sxx` and `Saison xx`. To get Sonarr to work properly with it, it searches for both of those. If a keywordless (empty) search is performed, it instead pulls the second page of results. But if you search for something which doesn't contain `Sxx` (e.g. Matrix), then unfortunately you get duplicate results.

The only way I can see to resolve it would be to make the re_replace conditional on the keywords containing `Sxx`, and otherwise getting the second page of results, e.g.:
```
{{ if .Keywords contains X }}{{ re_replace .Keywords \"X"  \"Y"}}{{ else }}{{ .Keywords }}&page=50{{ end }}
```
but so far as I'm aware, there's no way to do something like that using YAML in Jackett at the moment.

I'm happy to be corrected, or for someone with the knowhow to make it work, but it's been like that for almost a year and there's been no better alternative, so I'll close this issue. If anyone has an idea, feel free to comment.

**Comment by movianlost** [comment]
@ilike2burnthing I too suspected Jackett was doing multiple calls to Yggtorrent, which in my case slows down the results and make unnecessary calls to Yggtorrent that may result in IP ban.

Since I don't use Sonarr or any other similar software, I use my own script that adapts the query depending on the indexers and on the content type (anime, season, etc), I don't want Jackett to modify my query when searching in torrent Inderxers.

What code should I modify to prevent Jackett from changing my query? so for example, I don't want Jackett to change E20 when searching Anime to E020, or S01 to Saison 1, etc, I want Jackett to search the query I specify without any change.

For example, in example of Yggtorrent, can I delete that line that you referenced and this will prevent Jackett from calling Yggtorrent two times?

**Comment by ilike2burnthing** [comment]
People have been using it this way, many with Sonarr, Radarr, and other apps, for nearly a year, and there haven't been any reports of account bans.

Episode numbers aren't changed, just the letter S in Sxx to Saison xx

If you want to remove the second search, you'd have to remove:
https://github.com/Jackett/Jackett/blob/58736bd4aa92c628c8b5eda86886f776946a603b/src/Jackett.Common/Definitions/yggtorrent.yml#L226-L228

**Comment by movianlost** [comment]
Thank you. I was reading that file you linked, is it safe to delete anything under filters: and keywordfilters: if I want Jackett to not modify the query?

Also, the Yggtorrent supports both, category and sub_category, but in the yggtorrent.yml I only see parameter passed to category but not to sub_category.

`engine/search?category={{ .Config.category }}&name={{ .Keywords }}&description=&file=&uploader=&sub_category=&do=search&order={{ .Config.type }}&sort={{ .Config.sort }}`

Am I missing something here?

One last question, I know this is offtopic but I don't want to open newer issue for a simple question. I know Jackett scrapes 100 results, if the indexers have only say for example 50 results per page, it will go to the 2nd page, is there any variable inside .yml file that will tell Jackett don't scrape the second page?

**Comment by ilike2burnthing** [comment]
The last keyword filter you'd probably want to keep, as it resolves an issue with the site's own search, but you can probably remove the rest without issue.

The title_normal filters can all be removed if you're doing your own thing. The other title filters can be ignored if you're not enabling those options for the indexer in Jackett.

Subcategories open issue - https://github.com/Jackett/Jackett/issues/10822

Jackett will typically only request the first page of results, whether that's 5, 50, 500, or whatever. This can be increased by adding a second search path that uses the link for the second page, and so on. In the case of YGG, the site has 50 results per page, so by removing the second search path, you will always have a maximum of 50 results.

**Comment by movianlost** [comment]
Thank you, now I have a better understanding.

Regarding subcategories open issue, has there been any progress toward solving this issue?
Using the categories/subcategories to filter the results rather than to sending them with the request to the indexers doesn't use full potential of Jackett, this basically just reduces the amount of results.

I'm not a C# developer so I can't read the code, but I suppose the solution is to just add two parameters for cat and sub_cat and reference them in the provider .yml file like the query is referenced.

**Comment by ilike2burnthing** [comment]
No progress as of yet, just what you see there. You can subscribe to the issue to get notifications of updates.
