### ISSUE TITLE
[yts] Connection refused (yts.mx:443): Connection refused (Config)

### ISSUE THREAD

**Issue by C-Fu** [Jackett/Jackett#11454]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Synology DSM + Linuxserver docker, default setting

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.828

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?** [yes/no] no

### Description

1. Add YTS
2. Connection refused

**Comment by garfield69** [comment]
have a read and try out some of the suggestions in https://github.com/Jackett/Jackett/wiki/TroubleShooting#a-connection-attempt-failed and see if that helps.
