### ISSUE TITLE
[New Tracker Request] YTS [Formally Yify] [$15]

### ISSUE THREAD

**Issue by twilightrazor** [Jackett/Jackett#1145]
Please add [https://yts.ag/]  as a tracker as they have small movie files PERFECT for streaming, they do have an api! The same people that run EZTV run YTS!!

**Comment by oscarteg** [comment]
Little of topic but I would not use Yts.

[https://torrentfreak.com/yts-ag-wants-to-be-the-new-yify-on-popular-torrent-sites-151113/](https://torrentfreak.com/yts-ag-wants-to-be-the-new-yify-on-popular-torrent-sites-151113/)

**Comment by twilightrazor** [comment]
I know but they still provide reliable movies in a small file size. Plus (as far as I know) the people that run this YTS are the same people that run EZTV which is already supported.

**Comment by NagWolf** [comment]
Hi Guys

Can you please add https://yts.ag/ tracker  as this is also where I download my movies from .

**Comment by delphiactual** [comment]
yts.ag has a RSS feed so this should be really easy

https://yts.ag/rss-guide
https://yts.ag/rss/0/all/all/0

**Comment by madjunk** [comment]
Can you please add https://yts.ag/ tracker as this is also where I download my movies from.

RSS is already setup but like to use jacket to search movies and add it automatic. thanks!

**Comment by delphiactual** [comment]
https://yts.ag/api/v2/list_movies.json?query_term={imdbid/tmdbid}

**Comment by madjunk** [comment]
delphiactual, I know how to use their RSS to setup for the movies but by using jacket it might be best when I like to search for example with Couchpotato and add the movie I'm missing from my list and download automatic to my cloud. Thank you I do appreciate the feedback.

**Comment by marc0nline** [comment]
@Oscarteg That article you were referencing is from Nov. 2015 and made since because YIFY/YTS had just been taken down, but no one has been having any issue with the current owners it been business as usual.  I have been using since Jan. 2016 without issue.  I use YTS exclusively for my movies and like the others on this post would like Jacket to add as a tracker so I can search from it. on Radarr

**Comment by ghost** [comment]
+1 for YTS.AG. Consistent quality and decent availability. 6,164 title catalog (at time of writing) with a good mix of classics and new releases.

**Comment by kaiatkins** [comment]
I put $5 Bounty on it at  https://www.bountysource.com/issues/42796709-new-tracker-request-yts-formally-yify

**Comment by madjunk** [comment]
Ok I also posted my $5 Dollars also @ https://www.bountysource.com/issues/42796709-new-tracker-request-yts-formally-yify

**Comment by ghost** [comment]
+$5 https://www.bountysource.com/issues/42796709-new-tracker-request-yts-formally-yify

**Comment by nayab9** [comment]
Hi! I installed radarr yesterday and noticed a lack of yts.ag, so I added! Pull request here:

https://github.com/Jackett/Jackett/pull/1579

**Comment by JigSawFr** [comment]
Thank you @nayab9, you can now claim your bounty.

**Comment by garfield69** [comment]
https://yts.mx/ returning This site can’t be reached
https://torrentfreak.com/registrar-suspends-domain-of-popular-torrent-site-yts-210726/

https://yts.unblockit.uno/ appears to be working albeit without posters, with the latest torrent 2 hours old atm

can't test the other two alternate domains in the config due to the flaresolverr cookies invalid issue

**Comment by garfield69** [comment]
note that yts.ge, yts.cz, yts.rs, yts.zone are clones and none have the API that the Jackett indexer requires.
to pass the test use `https://yts.<yourdomainhere>/api/v2/movie_details.json`

**Comment by garfield69** [comment]
back online.

**Comment by ilike2burnthing** [comment]
https://yts.bz/ - Gateway time-out Error code 504 (the rest still redirect to .bz)
https://torrentfreak.com/torrent-giant-yts-suffers-extended-downtime/

**Comment by garfield69** [comment]
online

**Comment by V0latyle** [comment]
YTS.BZ now redirecting to YTS.GG

**Comment by garfield69** [comment]
TY
