### ISSUE TITLE
[aither] 2FA enhancement request

### ISSUE THREAD

**Issue by gouthamravee** [Jackett/Jackett#11459]
aither needs 2FA support please.

**Comment by garfield69** [comment]
It is not clear to me how 2FA works on aither, not having ever used a 2FA with a additional device before.
The current aither login page does not have a 2fa field.
And I don't have a android or ios platforms so I can not test the google authenticator or discover the complete process.
But presumably you first login with the usual credentials, and then the 2fa page comes after, and pauses the login until you type in the 2FA authentication.
If what I have described is correct, then the current aither yaml indexer cannot support it.
We would have to re-write the indexer in C#, and that is not going to happen any time soon.

If you know how the aither 2FA process works and its different from what I assume, please elaborate. Thanks.

**Comment by gouthamravee** [comment]
You are correct, the 2fa comes up after login. 
aither also has an API from what I can see, could that be used instead? 

Trying to find more info on the API, will update once I do.

**Comment by garfield69** [comment]
To use an API we would also need to re-write the indexer in C#.

**Comment by gouthamravee** [comment]
Understood, I would love to contribute but I need to find time. For now I'll leave the two links below for more info about the either API. 

https://hdinnovations.github.io/UNIT3D-Community-Edition-Docs/api_endpoints.html

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/8ef0446933d12a03512ddbe16cf742a6d22ac966/app/Http/Controllers/API/TorrentController.php

**Comment by ilike2burnthing** [comment]
Switched to API only - https://github.com/Jackett/Jackett/issues/8682#issuecomment-1006985200
