### ISSUE TITLE
[cinemamovies] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by FloydKulis** [Jackett/Jackett#11458]
### Environment

**OS**:
Qmono/Qnap

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
Mono v.6.8.0.105

**Jackett Version**:
Version v0.17.828

**Last Working Jackett Version**:
?

**Are you using a proxy or VPN?** [yes/no]
no.

### Description

Hi, when I try to connect to CM I get the message:
![image](https://user-images.githubusercontent.com/37215675/113442807-0417c480-93f1-11eb-8cc8-8b1e932c9f6c.png)

I have the same problem in both .Net and Mono versions.

**Comment by garfield69** [comment]
Read https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work for suggestions on this topic.

**Comment by FloydKulis** [comment]
@garfield69 Hi, I think I'm doing everything right. I do the same as in polistsource and it still doesn't work. He adds his log. If necessary, I will show you step by step how to add a tracker.
[log.txt](https://github.com/Jackett/Jackett/files/6267257/log.txt)

**Comment by ilike2burnthing** [comment]
Please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/TroubleShooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by FloydKulis** [comment]
Log file:
[log.txt](https://github.com/Jackett/Jackett/files/6273987/log.txt)

**Comment by ilike2burnthing** [comment]
That's not an enhanced log, please see the link.

**Comment by FloydKulis** [comment]
Mayby now, step by step:
scroll down to the bottom of the Jackett Dashboard, tick the enhanced Logging checkbox, and untick the Cache enabled checkbox
![image](https://user-images.githubusercontent.com/37215675/114082337-e7c2ce80-98ad-11eb-8483-c966310e5e76.png)
scroll up a bit and click on the apply server settings button
![image](https://user-images.githubusercontent.com/37215675/114082504-1ccf2100-98ae-11eb-93a2-64035f8623ff.png)
perform the test with the relevant indexer (avoid using any other indexers to prevent log clutter)
![image](https://user-images.githubusercontent.com/37215675/114083014-c7474400-98ae-11eb-9239-6d6d46916383.png)

find the log.txt file (linux ~/.config/Jackett/, windows %ProgramData%\Jackett)
edit it with a plain text editor, redacting any personal details, username, password, passkey, hashes, IP address etc.
save, then drag-drop the text file into the body of the ticket for us to take a look at.
when finished, untick the enhanced Logging checkbox, tick the Cache enabled checkbox, and click on the apply server settings button
![image](https://user-images.githubusercontent.com/37215675/114083141-ec3bb700-98ae-11eb-9951-bdf9b76d1c3d.png)
[log.txt](https://github.com/Jackett/Jackett/files/6280939/log.txt)

**Comment by garfield69** [comment]
OK that log looks good. Thanks.
Are you using a Chrome Browser on the same Qnap machine that is running Jackett to fetch your cookie?

**Comment by ilike2burnthing** [comment]
A web browser on a computer on the same network as the NAS should be fine, that's what I'm using. So long as the public IP address is the same, it shouldn't make a difference.

Yea, I'm not sure where those extra elements of the cookie are coming from either, I just have uid, pass, and hashv. Try signing out of the site in browser and sign in again, then take the cookie from /index.php or /browse.php making sure there are no unread messages, announcement, etc..

**Comment by ilike2burnthing** [comment]
If this is still an issue please comment and reopen.
