### ISSUE TITLE
Jackett cant be found in package centre on NAS

### ISSUE THREAD

**Issue by RobKie** [Jackett/Jackett#11460]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
We are only responsible for the Jackett packages found at https://github.com/Jackett/Jackett/releases

Any 3rd party ports of Jackett, such as Docker, Synology, etc, are the responsibility of the party that is supporting them at their respective support sites.

**Comment by RobKie** [comment]
Thanks for that,
Im really struggling trying to download Jackett back onto my NAS,  any help would be greatly appreciated
Cheers Rob


-----Original Message-----

**Comment by garfield69** [comment]
Rob, start by specifying what flavour of NAS you are using so the team can try to make suggestions relevant to your platform.

@ilike2burnthing this linux-y type of thing is more your cup of tea, can you assist? Thanks.

**Comment by ilike2burnthing** [comment]
Yea, your NAS brand, and preferably also model, is going to be needed.

If your NAS supports it though, I'd suggest installing Docker and use the Jackett container.

**Comment by RobKie** [comment]
Apologies,Nas is a Synology DS416playYou may have guessed that I'm totally computer illiterate and thanks for thisSent from my Galaxy
-------- Original message --------From: ilike2burnthing ***@***.***> Date: 8/4/21  2:36 pm  (GMT+10:00) To: Jackett/Jackett ***@***.***> Cc: RobKie ***@***.***>, Mention ***@***.***> Subject: Re: [Jackett/Jackett] Jackett cant be found in package centre on NAS (#11460) 
Yea, your NAS brand, and preferably also model, is going to be needed.
If your NAS supports it though, I'd suggest installing Docker and use the Jackett container.

**Comment by ilike2burnthing** [comment]
I don't think Jackett is in Synology's own repository, you'll need to add SynoCommunity (instructions here - https://synocommunity.com/#easy-install), and then search for Jackett.

**Comment by garfield69** [comment]
https://synocommunity.com/package/jackett
