### ISSUE TITLE
Problem with Ztracker

### ISSUE THREAD

**Issue by vampywiz17** [Jackett/Jackett#1146]
Hi!

I i try to search something in "Ztracker" (it added the latest release, thanks :) ) it only work if i search the part of the title:

![02](https://cloud.githubusercontent.com/assets/14281430/23721366/c2a09ed4-0441-11e7-86c4-ab7753c45a63.jpg)

If i search full title, not  found:

![01](https://cloud.githubusercontent.com/assets/14281430/23721392/dcaa6e40-0441-11e7-8ddd-7ceebcb9730a.jpg)

Same thing happened, if i try to search with Radarr:

![image](https://cloud.githubusercontent.com/assets/14281430/23721431/04b93286-0442-11e7-8724-66c86ca35a59.png)

**Comment by kaso17** [comment]
fixed with 23d49cdb53c6b59d683885eb0f7558904fe93c4c
