### ISSUE TITLE
[cinematik] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by sz-sketch** [Jackett/Jackett#11466]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: W1O

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:  Latest at time of writing

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [no]

### Description

My credential are fine, but getting an error ms when trying to login through jackett

### Logged Error Messages

Login Failed, got redirected

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#login-failed-got-redirected
