### ISSUE TITLE
Reverse proxy with nginx not working after update to v0.17.838

### ISSUE THREAD

**Issue by hariseldon99** [Jackett/Jackett#11472]
### Environment

**OS**: Ubuntu 18.04.5 LTS

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
Mono JIT compiler version 6.12.0.122 (although this shouldn't matter anymore, right?)

**Jackett Version**: v0.17.838

**Are you using a proxy or VPN?** no

### Description

Update broke the reverse proxy with nginx. All other reverse proxies (radarr, sonarr, lidarr, etc.) are fine.

### Config:

```
admin@MediaServer:~$ cat /etc/nginx/conf.d/apps/jackett.conf 
location /jackett {
    proxy_pass http://127.0.0.1:9117;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_redirect off;
}
admin@MediaServer:~$ cat /var/lib/jackett/Jackett/ServerConfig.json 
{
  "Port": 9117,
  "AllowExternal": true,
  "APIKey": "BLAHBLAHBLAH",
  "AdminPassword": null,
  "InstanceId": "BLAHBLAHBLAH",
  "BlackholeDir": null,
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": null,
  "CacheEnabled": true,
  "CacheTtl": 2100,
  "CacheMaxResultsPerIndexer": 1000,
  "FlareSolverrUrl": null,
  "OmdbApiKey": null,
  "OmdbApiUrl": null,
  "ProxyType": 0,
  "ProxyUrl": null,
  "ProxyPort": null,
  "ProxyUsername": null,
  "ProxyPassword": null,
  "ProxyIsAnonymous": true
}
```

### Screenshots

[Place any screenshots of the issue here if needed]
![image](https://user-images.githubusercontent.com/10812394/113505356-def39500-955b-11eb-8919-7765835c9874.png)

**Comment by ilike2burnthing** [comment]
There's nothing in [v0.17.838](https://github.com/Jackett/Jackett/releases/tag/v0.17.838) which would have broken your reverse proxy, it was just updates to indexers.

What is the last version you can run (now) and your reverse proxy still work?

**Comment by hariseldon99** [comment]
Hi,

Thanks for your attention. I rolled back to v0.17.655 and the same problem seems to happen. Nginx reverse proxy not working, but direct access using bare url works...

Here is my /etc/nginx/conf.d/apps/jackett.conf 
```
location /jackett {
    proxy_pass http://127.0.0.1:9117;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_redirect off;
}

```
Here is my /var/lib/jackett/.config/Jackett/ServerConfig.json 
```
{
  "Port": 9117,
  "AllowExternal": true,
  "APIKey": "BLAHBLAH",
  "AdminPassword": null,
  "InstanceId": BLAHBLAH,
  "BlackholeDir": "",
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": null,
  "CacheEnabled": true,
  "CacheTtl": 2100,
  "CacheMaxResultsPerIndexer": 1000,
  "FlareSolverrUrl": "",
  "OmdbApiKey": "",
  "OmdbApiUrl": "",
  "ProxyType": -1,
  "ProxyUrl": "",
  "ProxyPort": null,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true
}
```
Is this right?

**Comment by ilike2burnthing** [comment]
Can you confirm this is still an issue with v0.17.848?

In Jackett change the `Base path override` to `/jackett`, apply server settings, and try accessing it from the reverse proxy again.

**Comment by hariseldon99** [comment]
Hi,

Strange! This seems to have worked! 

Confirmed reverse proxy working with v0.17.848 with base path override set to "/jackett" via the webpage config. Oddly enough, I had tried this before by directly editing "/var/lib/jackett/.config/Jackett/ServerConfig.json" but it didn't work then....


Anyways, thanks for the attention. I guess I'll close the issue now.
