### ISSUE TITLE
[Indexer] PassioneTorrent

### ISSUE THREAD

**Issue by bonny1992** [Jackett/Jackett#1147]
Indexer Name
PassioneTorrent

Type
Mostly italian HD/SD movies/tv series and some games

Indexer URL
http://www.passionetorrent.info/

Indexer Language
Italian

Definition url:
http://pastebin.com/ZRvbtR0S

That one was quite easy, since it's quite similar to the "arabafenice" one.

**Comment by kaso17** [comment]
Thank you.

Added with f2bcc654f1347bb09b01b17edf0289daf9294346
Converted to the new category mapping schema and enabled movie search with 98f32bfadd48b8a4f3b2cc4fd5d65dd6288eab95

**Comment by garfield69** [comment]
http://www.passionetorrent.info/ returning ERR_NAME_NOT_RESOLVED
just me, or is site broken, gone or moved to a new domain?

**Comment by garfield69** [comment]
http://www.passionetorrent.info/ returning ERR_NAME_NOT_RESOLVED
anyone have any news?
