### ISSUE TITLE
[req] Oasis https://oasis-fun.club/ French Private

### ISSUE THREAD

**Issue by tony77682** [Jackett/Jackett#11483]
Please to add tracker: https://oasis-fun.club 

Oasis https://oasis-fun.club/ French Private
engine TTV3
MR 1.0
MST 48h

uses reCaptcha challenge at login, will require cookie method.

**Comment by garfield69** [comment]
v0.17.855

**Comment by tony77682** [comment]
thanks

**Comment by ilike2burnthing** [comment]
now Bitnami HORDE page

**Comment by ilike2burnthing** [comment]
https://oasis-fun.club/ - ERR_CONNECTION_REFUSED
http://oasis-fun.club/ - Index page

**Comment by garfield69** [comment]
@tony77682  do you have any info on the state of oasis, is it broken, gone or moved to a new domain?

**Comment by ilike2burnthing** [comment]
The founder and uploader apparently died, so it looks like the site has followed - 
https://planete-warez.net/topic/430/oasis/76?lang=en-US&page=2
https://planete-warez.net/topic/836/disparition?_=1635403385588

**Comment by garfield69** [comment]
v0.20.68
