### ISSUE TITLE
polishsource Added recognition of the PL language in the movie category

### ISSUE THREAD

**Issue by FloydKulis** [Jackett/Jackett#11486]
Can You add functionality for polishsource as in polishtraker? It is precisely this parameter:
![image](https://user-images.githubusercontent.com/37215675/113772241-b9fe4e00-9724-11eb-81d5-4e59f7006b9d.png)

**Comment by ilike2burnthing** [comment]
Should just be a case of replacing `PL` and `MULTi`, though a quick look at some of the software torrents, it may have the quirk of changing their names to `.POLISH.POLISH` as they often use `.MULTI.PL`.

**Comment by ilike2burnthing** [comment]
Not quite as bad as I thought, `.MULTI.PL` just becomes `.POLISH.PL`. That could be cleaned up if it causes any issues, but should be file as is. Will be included in the next release in ~7hrs.

**Comment by ilike2burnthing** [comment]
[v0.17.856](https://github.com/Jackett/Jackett/releases/tag/v0.17.856)

**Comment by FloydKulis** [comment]
I have the version: Version v0.17.1006
and I see in Radarr all the time:
![image](https://user-images.githubusercontent.com/37215675/117070358-eca06400-ad2d-11eb-845d-3035b5965b7d.png)

Do I need to remove the tracker and add it again?

**Comment by garfield69** [comment]
use your Jackett dashboard to edit the polishsource indexer config to set your preference.
![image](https://user-images.githubusercontent.com/6933240/117072259-49c70480-ad84-11eb-9440-ef9305fc6b45.png)

**Comment by ilike2burnthing** [comment]
Open the configuration panel for PolishSource, tick `Replace MULTI & PL by another language in release name`, and select one of the options in `Replace MULTI & PL by this language`. Enter the new captcha text from the image and click Okay. Try searching again and it should no longer display 'MULTI`.

**Comment by FloydKulis** [comment]
It works! You are awesome!
