### ISSUE TITLE
[Bug] HoundDawgs' search results direct to the tracker's homepage

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#1149]
Clicking on any torrent from HoundDawgs directs to the tracker's homepage instead of the torrent's page.

Jackett version: 0.7.1150.0
Mono version (if not using Windows):  N/A

**Comment by kaso17** [comment]
works fine for me, got a log?

**Comment by RoloSoze** [comment]
Attached, @kaso17 
[log.txt](https://github.com/Jackett/Jackett/files/834985/log.txt)

**Comment by kaso17** [comment]
looks fine to me, the download request is never sent to jackett in your log.
Can you paste the link of the download button from the search results please?

**Comment by RoloSoze** [comment]
Clicking on the download button works fine, the torrent downloads successfully. Here's an example: 

http://127.0.0.1:9117/dl/hounddawgs/z2utsv9iqidtox0dqmsn2lo0sb81j8vm?path=aHR0cHM6Ly9ob3VuZGRhd2dzLm9yZy90b3JyZW50cy5waHA_YWN0aW9uPWRvd25sb2FkJmlkPTQwMzgxJmF1dGhrZXk9anNzbG9wYm9xaGNnc3VwYnRvNmk2MjRra3NtaTBrMWQmdG9ycmVudF9wYXNzPWFuZDY4ZGp5emd6dDloeHRpYW9mYW00bXN3OXRwcTAz0&file=Game.Of.Thrones.S01.COMPLETE.BLURAY-HiQ.torrent

However, clicking on the torrent itself leads to the homepage. See the hyperlink in the status bar, screenshot attached. This applies to all torrents links.
![hd](https://cloud.githubusercontent.com/assets/23747425/23811915/11ecf43a-05e9-11e7-832d-9846eb04f422.jpg)

**Comment by kaso17** [comment]
fixed with 6f3127d36c492ff3d330390249dabe010cf812c1
