### ISSUE TITLE
Torrentproject: "&amp;" appears in definition search paths but is taken literally

### ISSUE THREAD

**Issue by FolkSong** [Jackett/Jackett#11490]
### Environment

**OS**: Win 10

**Jackett Version**: 0.17.855

### Description

I noticed that sorting by "latest" wasn't working for torrentproject (becomes obvious when searching for something that returns far more than 100 hits, such as "720p"). In the enhanced logs I noticed this line:

`WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://torrentproject.to/?t=720p&amp;orderby=latest)`

The `&amp;` looked suspicious so I tried editing torrentproject.yml to change every instance of `&amp;` to just `&`. Sure enough, after restarting Jackett the search results gave me the actual 100 latest hits.

**Comment by ilike2burnthing** [comment]
[v0.17.864](https://github.com/Jackett/Jackett/releases/tag/v0.17.864)
