### ISSUE TITLE
Sceneaccess Manual search don't work with more then one search string

### ISSUE THREAD

**Issue by luxus** [Jackett/Jackett#115]
Example:
Go to the jackett app
When I search for Bones I got the correct results
When I search for bones s11e07 the results shows me the latest torrents. Looks like it search for * instead of the search strings. But it just happens if I enter more then 1 word. This behavior is just on sceneaccess.. Other sites work as expected when I search for bones s11e07

**Comment by luxus** [comment]
Looks like i am The only one with this Problem :D 
It's better then before. Now my series gots downloaded when they got released.. But I can't manual search via sonarr or in jackett itself

**Comment by JigSawFr** [comment]
I noticed that search with SCC is not very good. i've a ton of results not related to media searched.

**Comment by WhatFox** [comment]
Are you on the latest release? bones s11e07 gives only two expected results.

**Comment by TouchMyBox** [comment]
Yeah, running the latest release as of right now and I even tried readding SCC. Searching "Steven Universe" just shows a bunch of recent torrents, whereas just searching "Steven" shows an actual search for the show. Kind of makes jackett useless with SCC.

**Comment by raspdealer** [comment]
@luxus is that fixed now? If yes, can you close this issue please?
Thanks!

**Comment by luxus** [comment]
fixed by https://github.com/Jackett/Jackett/commit/173e26c05457b04056f6b25723abd33e69fcd4c6
