### ISSUE TITLE
[newpct] The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject]  CN=pctmix.com[Issuer]  CN=

### ISSUE THREAD

**Issue by diecristher** [Jackett/Jackett#11505]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Working fine here, may be an ISP block on your end. Try the other site links in the indexer's config panel (click the relevant wrench button).

**Comment by Toneti10** [comment]
Use https://pctmix1.com/ instead of https://pctmix.com/

**Comment by charlotron** [comment]
seems that as @Toneti10 noticed the url changed to pctmix1.com could you fix it please? 🙏

**Comment by ilike2burnthing** [comment]
This was added a month and a half ago - https://github.com/Jackett/Jackett/commit/752c5856ea9df9dc52c1bd31ec25909a1ce3d355#diff-cb4b950388f1f7365b0e7ab66c84cd6d0608bb434e64190391b163bd9d2c0cb8

Open the configuration panel for NewPCT (blue spanner button) and change the sitelink there.

**Comment by charlotron** [comment]
wow Im so noob, thank you!! And sorry!! xD
