### ISSUE TITLE
[rarbg] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by lukesturgis** [Jackett/Jackett#11502]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: linuxserver/jackett:latest

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.864

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

Have rarbg listed as a public tracker in jackett but it is not returning any results. I believe this has been happening for some time now.

### Logged Error Messages
```
04-09 09:41:27 Error System.Exception: Found no results while trying to browse this tracker               at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 312                                                at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132                                                              at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)                               at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)                                                                                          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)                                                                                               at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)                                                                       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)                                                                                               at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)                            
```

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
The problem is with the RarBG API server at https://torrentapi.org which intermittently fails to return results. By repeating the request the results suddenly appear again. 
We have added a retry request option to the indexer and that is about all that we can do to improve the situation.
If RarBG is the main indexer that you use the most, then consider turning the cache OFF on the Jacket dashboard. The Indexer works for me better this way.
However, be aware that if you use apps like Sonarr that make requests on a timed basis (see the Sonarr indexer RSS Sync Interval setting), then turning the cache OFF on Jackett could cause some of the other indexer's web sites to complain about too-many-requests and block you.
So either disable the Sonarr RSS sync interval (0 minutes) or set it to as large a value as you can put up with (60, 120, 360 minutes or more).

**Comment by lukesturgis** [comment]
Cool, I'll give that a shot. Thanks @garfield69 !
