### ISSUE TITLE
[arm32] Updater breaks Jackett

### ISSUE THREAD

**Issue by pkreuzt** [Jackett/Jackett#11508]
Last three automatic updates (up to v0.17.865) resulted on broken installation unable to start. Manually downloading compressed archive and copying files (with proper owner and permissions) makes it work again, so issue seems to be the updater.

### Environment

**OS**: RaspberryOS, 32bit

**Jackett Version**: v0.17.865

**Are you using a proxy or VPN?** [yes/no]: No

Using a manual install from Jackett.Binaries.ARM32. I suppose this is a .Net Core static version. Automatic upgrades are enabled.

### Logged Error Messages

```

Apr 10 01:15:07 Jelly jackett[22518]:    at Jackett.Server.Program.Main(String[] args)
Apr 10 01:15:07 Jelly jackett[22518]: Unhandled exception. Autofac.Core.DependencyResolutionException: An exception was thrown while activating Jackett.Server.Services.ServerService -> Jackett.Common.Services.IndexerManagerService -> Jackett.Server.Services.ProtectionService -> λ:Microsoft.AspNetCore.DataProtection.IDataProtectionProvider -> Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider -> Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager -> Microsoft.Extensions.Options.OptionsManager`1[[Microsoft.AspNetCore.DataProtection.KeyManagement.KeyManagementOptions, Microsoft.AspNetCore.DataProtection, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]] -> Microsoft.Extensions.Options.OptionsFactory`1[[Microsoft.AspNetCore.DataProtection.KeyManagement.KeyManagementOptions, Microsoft.AspNetCore.DataProtection, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]] -> λ:Microsoft.Extensions.Options.IConfigureOptions`1[[Microsoft.AspNetCore.DataProtection.KeyManagement.KeyManagementOptions, Microsoft.AspNetCore.DataProtection, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]][] -> Microsoft.AspNetCore.DataProtection.Internal.KeyManagementOptionsSetup -> Microsoft.Extensions.Logging.LoggerFactory -> λ:Microsoft.Extensions.Logging.ILoggerProvider[] -> λ:Microsoft.Extensions.Logging.ILoggerProvider.
Apr 10 01:15:07 Jelly jackett[22518]:  ---> System.BadImageFormatException: Could not load file or assembly 'System.Runtime.Extensions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
Apr 10 01:15:07 Jelly jackett[22518]: File name: 'System.Runtime.Extensions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Apr 10 01:15:07 Jelly jackett[22518]:    at NLog.Extensions.Logging.NLogLoggerProvider.RegisterHiddenAssembliesForCallSite()
Apr 10 01:15:07 Jelly jackett[22518]:    at NLog.Extensions.Logging.NLogLoggerProvider..ctor(NLogProviderOptions options, LogFactory logFactory)
Apr 10 01:15:07 Jelly jackett[22518]:    at NLog.Web.AspNetExtensions.CreateNLogLoggerProvider(IServiceProvider serviceProvider, IConfiguration configuration, NLogAspNetCoreOptions options, LogFactory logFactory)
Apr 10 01:15:07 Jelly jackett[22518]:    at NLog.Web.AspNetExtensions.CreateNLogLoggerProvider(IServiceProvider serviceProvider, IConfiguration configuration, NLogAspNetCoreOptions options)
Apr 10 01:15:07 Jelly jackett[22518]:    at NLog.Web.AspNetExtensions.<>c__DisplayClass11_0.<AddNLogLoggerProvider>b__0(IServiceProvider serviceProvider)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.Extensions.DependencyInjection.AutofacRegistration.<>c__DisplayClass3_0.<Register>b__0(IComponentContext context, IEnumerable`1 parameters)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
Apr 10 01:15:07 Jelly jackett[22518]:    --- End of inner exception stack trace ---
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.Core.Resolving.InstanceLookup.<Execute>b__8_0()
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.Core.Resolving.InstanceLookup.Execute()
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
Apr 10 01:15:07 Jelly jackett[22518]:    at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
Apr 10 01:15:07 Jelly jackett[22518]:    at Jackett.Server.Helper.get_ServerService() in /home/vsts/work/1/s/src/Jackett.Server/Helper.cs:line 62
Apr 10 01:15:07 Jelly jackett[22518]:    at Jackett.Server.Helper.Initialize() in /home/vsts/work/1/s/src/Jackett.Server/Helper.cs:line 39
Apr 10 01:15:07 Jelly jackett[22518]:    at Jackett.Server.Startup.ConfigureServices(IServiceCollection services) in /home/vsts/work/1/s/src/Jackett.Server/Startup.cs:line 100
Apr 10 01:15:07 Jelly jackett[22518]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
Apr 10 01:15:07 Jelly jackett[22518]:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Apr 10 01:15:07 Jelly jackett[22518]:    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
Apr 10 01:15:07 Jelly jackett[22518]:    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
Apr 10 01:15:07 Jelly jackett[22518]:    at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
Apr 10 01:15:07 Jelly jackett[22518]:    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
Apr 10 01:15:07 Jelly jackett[22518]:    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
Apr 10 01:15:07 Jelly jackett[22518]:    at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
Apr 10 01:15:07 Jelly jackett[22518]:    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
Apr 10 01:15:07 Jelly jackett[22518]:    at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
Apr 10 01:15:07 Jelly jackett[22518]:    at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
Apr 10 01:15:07 Jelly jackett[22518]:    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
Apr 10 01:15:07 Jelly jackett[22518]:    at Jackett.Server.Program.Main(String[] args)
Apr 10 01:15:07 Jelly jackett[22518]: Aborted

```

**Comment by garfield69** [comment]
You are the first to post an updater issue for arm32, so we cant exclude the possibility that this is restricted to just your machine at this stage.
The updater on my windows has been working as usual.
Please find the updater*.txt files in your config folder and drag/drop them here. They may provide a clue to what is going on.

**Comment by garfield69** [comment]
Oh, and meanwhile, use your Jackett dashboard to disable auto-updates ;-)

**Comment by ngosang** [comment]
I have an ARM machine and it's working fine.
Please, follow the install instructions closely => https://github.com/Jackett/Jackett#install-as-service-1
The systemd unit must run the `.sh` script, not the Jackett executable. That is causing your issue

**Comment by pkreuzt** [comment]
@ngosang systemd service is fine, installed through provided script. It runs "/opt/jackett/jackett_launcher.sh":

[jackett.service.txt](https://github.com/Jackett/Jackett/files/6290273/jackett.service.txt)


@garfield69 

[updater.txt](https://github.com/Jackett/Jackett/files/6290257/updater.txt)
[updater.txt.20210318.00000.txt](https://github.com/Jackett/Jackett/files/6290258/updater.txt.20210318.00000.txt)
[updater.txt.20210329.00000.txt](https://github.com/Jackett/Jackett/files/6290260/updater.txt.20210329.00000.txt)
[updater.txt.20210408.00000.txt](https://github.com/Jackett/Jackett/files/6290261/updater.txt.20210408.00000.txt)


Meanwhile I have noticed a particular setting of my installation that could be related. Jackett has its own user, program files are on /opt/jackett but user home is /var/lib/jackett (where config is stored). This makes settings resistant to some problems and more easily portable. Could this be causing the issue?

**Comment by garfield69** [comment]
how are you telling jackett that  the config directory is at /var/lib/jackett ?
I don't see anything in the systemd jackett.service file to point to this.
If you want to run it with a custom config directory you are going to need to add `Environment=XDG_CONFIG_HOME=/var/lib/jackett` to your systemd file.
.

**Comment by pkreuzt** [comment]
I specified HOME for jackett user when creating it, so systemd always report `HOME=/var/lib/jackett/` for any process of this user. Settings are stored on /var/lib/jackett/.config/Jackett. No need for aditional config. Is this a problem?

**Comment by garfield69** [comment]
@pkreuzt wrote:
>I specified HOME for jackett user when creating it, so systemd always report HOME=/var/lib/jackett/ for any process of this user. Settings are stored on /var/lib/jackett/.config/Jackett. No need for aditional config. Is this a problem?

@NinjaLikesCheez how does #11465 handle this scenario?
Its an ARM32 platform and user is seeing the Jackett updater break the service.
@ilike2burnthing  this is all linux-y stuff which as you know is not my scene. Your input is welcome. Thanks.

**Comment by ilike2burnthing** [comment]
The timing of this would trace back to #11479 but I'm not sure how it would affect it. @KaiSforza?

**Comment by KaiSforza** [comment]
@ilike2burnthing no idea how my changes would break this. This isn't the same error as #11463 so I kind of doubt it's related. I'm seeing the main part of the error and thinking it's probably some kind of new dependency stuff?

```
System.BadImageFormatException: Could not load file or assembly 'System.Runtime.Extensions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
```

@pkreuzt What is currently in `/var/lib/jackett`? What's in `/opt/jackett`?

Just in case, could you run the following?
```
ls -lah /var/lib/jackett /opt/jackett
```
and post the output?

**Comment by KaiSforza** [comment]
@pkreuzt It does look like you were running 0.17.826 at some point, so it might be that since you were running from the directory that jackett was installed in, any kind of restart during that time would have caused the directory to get wiped. If you had a reboot or service restart between 31/3 and 6/4, it might have erased everything, depending on your current setup.

```
2021-03-31 19:49:40.8151 Info Jackett Updater v0.17.826 
2021-04-06 03:48:36.7959 Info Jackett Updater v0.17.848 

```

**Comment by pkreuzt** [comment]
[var_lib_jackett.txt](https://github.com/Jackett/Jackett/files/6291855/var_lib_jackett.txt)
[opt_jackett.txt](https://github.com/Jackett/Jackett/files/6291856/opt_jackett.txt)

I haven't lost settings at any moment. But I see /var/lib/jackett/.config/Jackett is full of what appear to be old libs and binaries. Should these be there?

[var_lib_jackett_config_Jackett.txt](https://github.com/Jackett/Jackett/files/6291884/var_lib_jackett_config_Jackett.txt)

**Comment by KaiSforza** [comment]
@pkreuzt sorry for the slow response. 

You shouldn't have lost any settings, it might have deleted your `/opt/jackett` directory at some point after copying it to `/var/lib/jackett`, though. That was a bug with the .826-.848 releases, especially if your workdir was set to `/opt/jackett`. I ran into that problem for that exact reason (the start directory being the install directory) in #11465 since my docker started in `/Jackett`

**Comment by KaiSforza** [comment]
Those files there will not cause any problems though.

**Comment by pkreuzt** [comment]
I am running v0.17.889 now. Yesterday I gave the autoupdater a chance and it worked flawlessly, as it did today again. I missed a couple updates in the middle, but seems to be working now. If you didn't change anything yet, the problem must have been on my setup somewhere. Only issue I can think is Monit service restarting Jackett too early (or, more properly, Jackett taking too much time to update, since it didn't fail before and the configured timeout seemed adequate). Maybe some soft freeze that made Jackett take more time than usual to update? I don't know, but I'll keep an eye on it on following updates.

**Comment by ilike2burnthing** [comment]
Feel free to reopen if the issue returns.
