### ISSUE TITLE
[beyond-hd-oneurl] Resource temporarily unavailable (beyond-hd.me:443): Resource temporarily unavailable (Config)

### ISSUE THREAD

**Issue by adrian-alexander** [Jackett/Jackett#11509]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu 20.04

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.865

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

I added BeyondHD OneURL, put in my OneURL, and press okay, and I got this error. I configured FlareSolverr, got the OK from it, and pasted/tried localhost:8191 and myip:8191 into the FlareSolverr API URL input, but neither worked.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

https://pastebin.com/PYFbr7K2

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
I take it the resource became available again ;-)

**Comment by adrian-alexander** [comment]
Haha yeah I just restarted my PC and it worked.
