### ISSUE TITLE
[REQ] infomaniakos.net

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#11517]
Spanish public tracker of movies, TV and music

https://infomaniakos.net/

**Comment by garfield69** [comment]
Site has a one-title-many-torrents structure so will require an indexer written in C#

**Comment by ilike2burnthing** [comment]
ERR_TOO_MANY_REDIRECTS

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
