### ISSUE TITLE
[REQ] pasateatorrent.net

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#11516]
Spanish public film and series tracker.

https://pasateatorrent.net

**Comment by garfield69** [comment]
the sites has a one-title-many-torrents structure which means the indexer will need to be written in C#

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
