### ISSUE TITLE
[HD-Olimpo] Parsing issue with non leading zero on seasons

### ISSUE THREAD

**Issue by elpedriyo** [Jackett/Jackett#11519]
### Environment

**OS**: Ubuntu 20.10

**.Net Runtime**: [Mono]

Jackett Version v0.17.865

**Are you using a proxy or VPN?** [no]

### Description

One of the TV Shows I was searching for with Sonarr, was not showing, because the name of the file in the tracker was S1E02 S1E03, intead of S01E02 and so on...
So the issue was being cause because of a 0 missing.

Could you please solve that, so that episodes are also being taken even if 0 is missing?
### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![image](https://user-images.githubusercontent.com/3207791/114281545-3653a280-9a3f-11eb-80ea-602c483c6d9f.png)

**Comment by garfield69** [comment]
Please identify the Jackett indexer you want improved.

**Comment by elpedriyo** [comment]
I am using it with HD-olimpo

**Comment by garfield69** [comment]
questions: on the web site, if you search for S01E01 do you get matches for S1E01 ?
or if you search for s1e01 do you get matches for s01e01 ?
Does the site also have torrents with S01E01 or are all of them loaded as s1e01?

We are not going to do two searches, once for S1E01 and another for S01E01.

Does the site support masking such as a % or other special character?

**Comment by garfield69** [comment]
Oh, I see from the screenshot you provided from the site that it has both s1e01 and s01e01, so you have already answered that question. thank you.

**Comment by elpedriyo** [comment]
I have talked with the portal managers, and it has been corrected from their side. And no more is happening, so I guess this issue should be solved :D
