### ISSUE TITLE
tvvault: returns 0 results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#11515]
the site is working fine. maybe there are some changes in the layout

**Comment by garfield69** [comment]
Since you have an account which I do not have, either post a html dump of the search page so I can take a look or fix it yourself ;-)

**Comment by MistOrDew** [comment]
> Since you have an account which I do not have, either post a html dump of the search page so I can take a look or fix it yourself ;-)

Hi I am experiencing the same issue on this tracker. How do I go about making a html dump of the search page so that you can diagnose?

**Comment by garfield69** [comment]
@MistOrDew wrote:
>Hi I am experiencing the same issue on this tracker. How do I go about making a html dump of the search page so that you can diagnose?

See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source. Thanks.

**Comment by MistOrDew** [comment]
@garfield69 Is there an email where I can send the txt file?

**Comment by garfield69** [comment]
garfieldsixtynine -at- gmail.com

**Comment by MistOrDew** [comment]
@garfield69 Sent the file to the above email

**Comment by garfield69** [comment]
wen you did that search, did you have the option disablegrouping turned on?

**Comment by garfield69** [comment]
the indexer is expecting results with the grouping option disabled so that it gets individual torrents in the rows.
the dump you provided appears to be a grouped set, with the first row for the title, and subsequent rows with the details of each torrent.
there should be an option on the search page, just after the sort options, called **Disable grouping**
please try again with that checkbox ticked.
thanks.

**Comment by MistOrDew** [comment]
@garfield69 Sent

**Comment by garfield69** [comment]
OK, I think I see what is going on.
Previously the indexer was expecting to see the details href to begin with `torrents.php?id=`
But now that href begins with `https://tv-vault.me/torrents.php?id=` so the matching fails.

I will amend the indexer, and after the release is published (in about 23 hours from now) you can test and see if I have it right or if there is more to fix.
I'll post here the release version when published so you know when to update and test.
Thanks.

**Comment by ilike2burnthing** [comment]
[v0.17.934](https://github.com/Jackett/Jackett/releases/tag/v0.17.934)

**Comment by MistOrDew** [comment]
@garfield69 @ilike2burnthing Still doesnt seem to work, I get the error as "Found no results while trying to browse this tracker".

I have sent the error log to the email above.

**Comment by garfield69** [comment]
posted your stack trace here
```
	
System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 312
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 101
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
```
I've no idea what is going on here, none of the pointers are within the indexer!
That's the problem with not being able to debug with an account, its all hit or miss.
This is likely going to need a proper C# dev to fix.

**Comment by garfield69** [comment]
for anyone that wants a html to work with here is the relevant redacted snippet that should be enough to work with
```html
<table class="torrent_table" id="torrent_table">
	<tbody><tr class="colhead">
		<td class="small"><div style="width:64px"></div></td>
		<td width="100%"><a href="https://tv-vault.me/torrents.php?order_by=s1&amp;order_way=ASC&amp;disablegrouping=1&amp;searchstr=king">Name</a> / <a href="https://tv-vault.me/torrents.php?order_by=s2&amp;order_way=DESC&amp;disablegrouping=1&amp;searchstr=king">Year</a></td>
		<td>Files</td>
		<td><a href="https://tv-vault.me/torrents.php?order_by=s3&amp;order_way=ASC&amp;disablegrouping=1&amp;searchstr=king">Added</a></td>
		<td><a href="https://tv-vault.me/torrents.php?order_by=s4&amp;order_way=DESC&amp;disablegrouping=1&amp;searchstr=king">Size</a> / <a href="https://tv-vault.me/torrents.php?order_by=s8&amp;order_way=DESC&amp;disablegrouping=1&amp;searchstr=king"><img src="./Browse Torrents __ TVVault_files/comments.png" style="vertical-align:text-top;" alt="Comments" title="Comments"></a></td>
		<td class="sign"><a href="https://tv-vault.me/torrents.php?order_by=s5&amp;order_way=DESC&amp;disablegrouping=1&amp;searchstr=king"><img src="./Browse Torrents __ TVVault_files/snatched.png" alt="Snatches" title="Snatches"></a></td>
		<td class="sign"><a href="https://tv-vault.me/torrents.php?order_by=s6&amp;order_way=DESC&amp;disablegrouping=1&amp;searchstr=king"><img src="./Browse Torrents __ TVVault_files/seeders.png" alt="Seeders" title="Seeders"></a></td>
		<td class="sign"><a href="https://tv-vault.me/torrents.php?order_by=s7&amp;order_way=DESC&amp;disablegrouping=1&amp;searchstr=king"><img src="./Browse Torrents __ TVVault_files/leechers.png" alt="Leechers" title="Leechers"></a></td>
	</tr>
	<tr class="torrent ">
		<td class="center" style="padding: 0"><img src="./Browse Torrents __ TVVault_files/scifi.png" alt="Sci-Fi" title="Sci-Fi" width="64" height="28"></td>
		<td>
			<span>
			</span>
			<a href="https://tv-vault.me/torrents.php?id=19684&amp;torrentid=77532" title="View Torrent">Basilisk: The Serpent King - TV Movie</a>			(2006) (MKV/H.264/AC3/DVD)			<br><div class="tags"><a href="https://tv-vault.me/torrents.php?searchtags=00s">00s</a>, <a href="https://tv-vault.me/torrents.php?searchtags=action">action</a>, <a href="https://tv-vault.me/torrents.php?searchtags=scifi">scifi</a>, <a href="https://tv-vault.me/torrents.php?searchtags=fantasy">fantasy</a>, <a href="https://tv-vault.me/torrents.php?searchtags=tv.movie">tv.movie</a>, <a href="https://tv-vault.me/torrents.php?searchtags=cleavant.derricks">cleavant.derricks</a>, <a href="https://tv-vault.me/torrents.php?searchtags=yancy.butler">yancy.butler</a>, <a href="https://tv-vault.me/torrents.php?searchtags=stephen.furst">stephen.furst</a>, <a href="https://tv-vault.me/torrents.php?searchtags=jeremy.london">jeremy.london</a></div>		</td>
		<td>1</td>
		<td class="nobr">4d18h</td>
		<td class="nobr">1.7179 GB<br><div class="center">(0)</div></td>
		<td>2</td>
		<td>2</td>
		<td>0</td>
	</tr>
```

**Comment by qhello** [comment]
I have a TVV account to share, if any dev. needs it to debug.

**Comment by garfield69** [comment]
If you send credentials to garfieldsixtynine -at- gmail.com I'll have another go at this one. Thanks.

**Comment by qhello** [comment]
> If you send credentials to garfieldsixtynine -at- gmail.com I'll have another go at this one. Thanks.

Sent

**Comment by garfield69** [comment]
Interesting.
In response to Jackett sending a keywordless search
`https://tv-vault.me/torrents.php?order_by=s3&order_way=desc&disablegrouping=1&searchstr=`
tv-vault replied with
```
Error
Browse quota exceeded
Automated query detected. You should not use scraping tools to attack the site. Use RSS feeds instead.
```
which leads to the _found 0 releases_ result.
```
https://tv-vault.me/torrents.php?order_by=s3&order_way=desc&disablegrouping=1
```
appears to work, so I'll jig to code to drop the searchstr parm when there are no keywords and see if I can make progress in that direction.

**Comment by garfield69** [comment]
v0.17.972

**Comment by Orangile** [comment]
This seems to be broken. I have had Jackett for a week now (that's on 24/7 with automatic updates) and the search has not worked for me. Current Jackett version v0.18.523.

**Comment by garfield69** [comment]
@Orangile if you want us to help with anylising this then provide a full enhanced log (see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket)
the most recent issue iwth the inder was a user getting `Excessive automated queries detected` errors. see https://github.com/Jackett/Jackett/issues/12096#issuecomment-889802261
