### ISSUE TITLE
Request: Psytorrents

### ISSUE THREAD

**Issue by seanvree** [Jackett/Jackett#1152]
Requesting support for PSYtorrents

https://psytorrents.info

I have invites available if needed.

Thanks for the hard work!!!

**Comment by kaso17** [comment]
please send the invite to kaso1717 -at- gmail.com

**Comment by seanvree** [comment]
@kaso17  sent!

**Comment by kaso17** [comment]
turns out that I already had an account, you can reuse the invite.
added with 7211dfe07d890c965ec75cc058a5ce2421b33a02

**Comment by seanvree** [comment]
THANKS!

**Comment by seanvree** [comment]
Hey, I updated to the latest branch, and I have psytorrents.cs in the jackett\src\jackett\indexers dir, but I'm not seeing it when I try to add it from the WebUI?

Currently on ver: 0.7.1150.0

**Comment by kaso17** [comment]
it's not yet included in a release. You'll have to build it yourself or wait a few hours.

**Comment by raspdealer** [comment]
if the invite is still pending, let me know @seanvree

**Comment by seanvree** [comment]
@raspdealer  - Yes, the invite is still pending acceptance by @kaso17  - Do you want me to delete it?

**Comment by kaso17** [comment]
@seanvree I already have an psytorrents account. You can cancel/reuse your invite.

**Comment by seanvree** [comment]
@kaso17  - THX!

**Comment by kaso17** [comment]
@seanvree is this one dead/gone?

**Comment by seanvree** [comment]
@kaso17 I think so. No more PLUR. lol

**Comment by kaso17** [comment]
removed via f6e37d0b8332657f6f0ea5711cc3a7f62ebc1284

**Comment by ilike2burnthing** [comment]
https://psytorrents.info/ - 404 Not Found
