### ISSUE TITLE
[REQUEST] Private Tracker - ROFD https://rofd.me/

### ISSUE THREAD

**Issue by Winblackka** [Jackett/Jackett#11520]
Type: German general private tracker
Name: Road of fantastic dream
Website: ~~www.rofd.me~~ https://rofd.me/

I would like to get this one added.
I can provide an invite.
Thank you!

engine: xbtitFM v3.0.00
MR 1.0
MST 48h

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by Winblackka** [comment]
Thank you. Check your mails. :)

**Comment by garfield69** [comment]
Registration and Login successful. Thank you.

**Comment by garfield69** [comment]
v0.17.872

**Comment by garfield69** [comment]
https://rofd.me/ returning ERR_CONNECTION_CLOSED

**Comment by virusperfect** [comment]
Seems to be down.

**Comment by ilike2burnthing** [comment]
https://rofd.me/ is giving ERR_CONNECTION_CLOSED for me as well, but out of interest I checked http://rofd.me/ which gives a GoDaddy 'get this domain' page.

**Comment by garfield69** [comment]
v0.18.502
