### ISSUE TITLE
[REQ] [MTV] Support additional search modes

### ISSUE THREAD

**Issue by Xalaxis** [Jackett/Jackett#11527]
Jackett version: Latest

The MoreThanTV indexer does not currently support any search modes other than "q". This means that tools such as Sonarr cannot use the indexer, because they require a minimum of "q,season,ep" support to function. I do not understand enough about the implementation of the indexer to know whether this is a simple change to advertised functionality, or requires deeper modification to the indexing code.

Tagging @ryanm352 as I know you've been involved in the rewrite efforts (thanks!)

**Comment by ryanm352** [comment]
Hi! Thanks for the feedback! The site is currently under a rewrite so this functionality is set to change whenever they launch their full update. There isn't much I can do as this rewrite addresses what the site currently supports.

**Comment by Xalaxis** [comment]
Thanks for the update, I had a sad feeling that might be the case. Thank you for your work on the API, I saw you were donating time in another thread ❤️ .

Should I leave this issue open to track implementation when it becomes possible?

**Comment by Xalaxis** [comment]
Sonarr is saying that it's Jackett's responsibility to do the season, episode to raw search string conversion until the full API is available. Do you/Jackett have an opinion on that?

**Comment by Taloth** [comment]
> I'm actually in the process of writing an API package for gazelle-ish sites so we don't have to deal with this in the future.

That's rather nice. :smile:

I tried to get another tracker engine codebase maintainers to implement an api, but they didn't want to back port it from a site admin that implemented it.

**Comment by ryanm352** [comment]
> Sonarr is saying that it's Jackett's responsibility to do the season, episode to raw search string conversion until the full API is available. Do you/Jackett have an opinion on that? I'm wondering what the old indexer did, which did support season,ep AFAIK.

I can definitely implement the minimum requirements so that it at least pulls results, though, it will essentially ignore these parameters during search. Would that work?

**Comment by ryanm352** [comment]
> > I'm actually in the process of writing an API package for gazelle-ish sites so we don't have to deal with this in the future.
> 
> 
> 
> That's rather nice. :smile:
> 
> 
> 
> I tried to get another tracker engine codebase maintainers to implement an api, but they didn't want to back port it from a site admin that implemented it.


Gazelle/hybrids seem to be a nightmare to maintain, so I don't blame em! My solution will be a simple package with an extra page to add to allow users to generate/disable their own keys. 

Right now, I have to target the DOM to get dat, ugh!

**Comment by Taloth** [comment]
> I can definitely implement the minimum requirements so that it at least pulls results, though, it will essentially ignore these parameters during search. Would that work?

Technically yes, coz Sonarr parses the results anyway and rejects wrong episodes. But if you return all releases of one series then you're likely to return more than 1000 results. Still, better then no results at all.

> Gazelle/hybrids seem to be a nightmare to maintain, so I don't blame em!

It wasn't Gazelle though, and the site admin implemented it completely. They just considered an rss feed 'good enough'. hdaccess (no longer exists) was actually the site that gave birth to torznab which was later used in Jackett too.

**Comment by Xalaxis** [comment]
> I can definitely implement the minimum requirements so that it at least pulls results, though, it will essentially ignore these parameters during search. Would that work?

I'd definitely prefer that to no results, although obviously the API is the end-goal.  Perhaps you could add the value of the season field to the `q` search string in the S`season` format? @Taloth, would this be preferable to just all the seasons and doing the sorting Sonarr-side?

**Comment by ryanm352** [comment]
> > I can definitely implement the minimum requirements so that it at least pulls results, though, it will essentially ignore these parameters during search. Would that work?
> 
> 
> 
> I'd definitely prefer that to no results, although obviously the API is the end-goal.  Perhaps you could also add the value of the season field to the `q` search string in the "S`season`" format? @Taloth, would this be preferable to just all the seasons being returned and doing the sorting Sonarr-side?

Do me a favor and gather up the requirements in this thread and I'll implement it this week or next. I don't have sonarr, so I might need you to test thoroughly if that's okay with you!

**Comment by ryanm352** [comment]
@garfield69 -- you can assign this to me.

**Comment by ryanm352** [comment]
Sorry for the delay! been busy with work stuff!

@Xalaxis: https://github.com/Jackett/Jackett/pull/11666

**Comment by garfield69** [comment]
v0.17.996

**Comment by Xalaxis** [comment]
@ryanm352 I've tested the integration and can confirm it worked. Thanks Ryan!

Tagging @Taloth so they're aware.
