### ISSUE TITLE
[REQ] OpenCD https://open.cd/ Chinese Private

### ISSUE THREAD

**Issue by vindevil** [Jackett/Jackett#11524]
Full address: https://open.cd/index.php
Site type: private
Content type: music

It's not open for invitation but only paying to join right now. You can use my account to set up.

**Comment by garfield69** [comment]
If you send credentials to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by vindevil** [comment]
I have sent you the information needed from vchen365 -at- gmail.com. Thank you for your effort no matter this site would be added successfully or not.

**Comment by garfield69** [comment]
engine: NexusPHP Standard v1.5 Beta 4
MST: 36h
MR: 1.0

**Comment by garfield69** [comment]
v0.17.876

**Comment by vindevil** [comment]
Thank you so much. It works like a charm. I will keep the password unchanged in case you need to log in to update this site in the future.

**Comment by garfield69** [comment]
For your own security and peace of mind, its best if you change your password. 
In the event you discover the indexer needs maintenance then raise a new ticket and if necessary we can arrange access.

**Comment by vindevil** [comment]
Okay, then I'll reset the password and report if this site needs any updates.
