### ISSUE TITLE
[nyaasi] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by gillon123** [Jackett/Jackett#11530]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker container on DSM6 

**.Net Runtime**: .Net-Core (I believe)

**.Net Version**: Unsure - I'm running the CoreLinuxAmdx64 variant

**Jackett Version**: v0.17.876

**Last Working Jackett Version**: Jackett is working, but with other indexers. Nyaa suddenly stopped returning any results, not sure as to why.

**Are you using a proxy or VPN?** Yes.

### Description

Add Nyaa.si indexer with default settings (tried others as well) - test/triggered via Sonarr and no results.

Other indexers work just fine, Nyaa worked just fine as well up to at least 1 week ago, because I know it found releases and sent them to Sonarr at that point.

### Logged Error Messages

System.Exception: Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 312    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
--

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by gillon123** [comment]
Just to provide closure to my issue for anyone who stumbles upon it; it was proxy related. For whatever reason nyaa (and only nyaa) doesn't like my proxy anymore.

**Comment by IshanArya** [comment]
How did you fix it? @gill0n

**Comment by ilike2burnthing** [comment]
Check that you can access the site from the same device and IP. If not, you'll need to use a proxy or VPN (or change it, as in gill0n's case). See also -https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

**Comment by gill0n** [comment]
> How did you fix it? @gill0n

Like @ilike2burnthing mentioned I simply disabled my proxy for my Jackett instance. The issue isn't jackett related, basically - it was a just a tracker (nyaa) that for w/e reason didn't like traffic from my proxy anymore.

Worked fine as soon as I disabled it.
