### ISSUE TITLE
[New Tracker REQ] HDTorrents.it

### ISSUE THREAD

**Issue by rafuz** [Jackett/Jackett#1153]
Indexer Name
HDTorrents.it

Type
Movies, TV, Audio

Indexer URL
https://hdtorrents.it

Indexer Language
Italian

Invite
An invite is needed.
I can provide one in a few days

Note
Recently has removed geo-blocking from website. 
Please check if it can be added.

**Comment by RoloSoze** [comment]
@rafuz HDTorrents.it has already been requested in #1043 so I'm closing this and I'll mention your name there to specify that you can provide an invite.
