### ISSUE TITLE
[req] RedBits https://red-bits.com/ Spanish Private

### ISSUE THREAD

**Issue by SonGoku69** [Jackett/Jackett#11540]
Hello. There is a new es-es private tracker and it is not available in Jackett to add. Is it possible that it can be added in the future? Many thanks for your work.

https://red-bits.com/

**Comment by garfield69** [comment]
engine: Unit3D 5.1.0
MR: 1.0
MST: 96h

**Comment by garfield69** [comment]
v0.17.886

**Comment by waisenflix** [comment]
Thanks!

**Comment by garfield69** [comment]
https://red-bits.com/ returning ERR_CONNECTION_REFUSED

**Comment by RicardoVelaC** [comment]
They posted few days ago that they'll migrate to a big server but I don't know more information.

**Comment by ilike2burnthing** [comment]
```
ESTAMOS DE MANTENIMIENTO
VOLVEREMOS EN CUANTO PODAMOS
```
```
WE ARE ON MAINTENANCE
‎WE'LL BE BACK AS SOON AS WE CAN.‎
```

**Comment by waisenflix** [comment]
They are back. Please don't remove this tracker.

**Comment by ilike2burnthing** [comment]
Indexers are only removed if they're down or otherwise unusable for 30 days, or if there's an official announcement that they've shut down. The label is just there so we can track its progress.

**Comment by garfield69** [comment]
https://red-bits.com/ returning ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
redbits appear to have upgraded to unit3d 6.0.0 but their conversion is not complete.
If I try to access the web sites torrents I get a Error 500: Internal Server Error!

I was going to prepare a API indexer but now I think I will wait until they sort out their issue.

**Comment by garfield69** [comment]
fully functional. preparing api indexer switch.

**Comment by faileador1** [comment]
RedBits dissapeared from trackers list. Please add it again.

**Comment by ilike2burnthing** [comment]
`RedBits` was replaced with `RedBits (API)` 9 months ago, which still exists as an indexer, you'll just need to add it again.

**Comment by garfield69** [comment]
https://redbits.xyz/ 502 Bad Gateway nginx/1.18.0 (Ubuntu)

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
To close soon - https://www.reddit.com/r/trackers/comments/1g6ngom/redbits_tracker_closure/

**Comment by AARON8888** [comment]
Tracker is running for me many days ago, but I use out of Jackett.

**Comment by garfield69** [comment]
>Tracker is running for me many days ago, but I use out of Jackett.

Irrelevant. 
this ticket was marked as waiting for removal because the web site has a notice that the site plans to close, and this ticket label remind us that when the indexer stops working it's most likely because the site is gone.

**Comment by garfield69** [comment]
https://redbits.xyz/ > ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
https://redbits.xyz/ > ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.22.1052
