### ISSUE TITLE
[danishbytes] Login failed: No form found on https://danishbytes.org/login using form selector form[action$=

### ISSUE THREAD

**Issue by mplys3** [Jackett/Jackett#11551]
Hey Guys, tracker suddenly stopped working!

Could somebody explain why, is it the tracker or jackett messing up?

**Comment by ilike2burnthing** [comment]
Working ok here. Check the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/TroubleShooting#login-failed-no-form-found-on-url

If those don't resolve you issue, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

Also provide the information originally requested that you deleted:
**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]
