### ISSUE TITLE
[sharewood] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by freMea** [Jackett/Jackett#11562]
### Environment

**OS**: Windows 10 1909

**Jackett Version**: 0.17.897

**Last Working Jackett Version**: ?

**Are you using a proxy or VPN?** NO

### Description

Sharewood test error.

### Logged Error Messages

[Log](https://paste.ubuntu.com/p/gQSFGSrSYQ/)

**Comment by ilike2burnthing** [comment]
Also affects sharewoodapi. Testing done on Docker container, with and without VPN/proxy. Able to access the site fine, even when changing the user-agent to Jackett's. Not really sure what's going on.

@Zioury, any idea?

**Comment by Zioury** [comment]
The site is under attack.
I have details why the site is OK but not tracker and jackett but I can not communicate, this info is too valuable.

**Comment by ilike2burnthing** [comment]
Thanks, that's understandable. Marked as down as, from Jackett's point of view, it is, but also so I remember to check this.

**Comment by Zioury** [comment]
Jackett works fine now, could you confirm ?

**Comment by garfield69** [comment]
yup, no issues for me with either the sharewood indexer or the sharewoodAPI indexer.

**Comment by freMea** [comment]
Yes it works. Thanks
