### ISSUE TITLE
1337x Exceptions - Failing on multiple urls.

### ISSUE THREAD

**Issue by DrakeJones** [Jackett/Jackett#11565]
An error occurred while testing this indexer
Exception (1337x): Got redirected to another domain. Try changing the indexer URL to https://go.unblocksource.org/. Updated site link, please try again.: Parse error

 An error occurred while testing this indexer
Exception (1337x): certificate validation failed: [Subject] E=none@vmware.com, CN=VMware, OU=VMware, L=Palo Alto, C=US [Issuer] E=none@vmware.com, CN=VMware, OU=VMware, L=Palo Alto, C=US [Serial Number] 00F136335893D02B53 [Not Before] 1/12/2016 11:27:21 PM [Not After] 1/11/2017 11:27:21 PM [Thumbprint] A25A977571B5C0B1D3CB95E83EE4322097B7A150 : The SSL connection could not be established, see inner exception.

Exception (1337x): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=60000 (ms): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=60000 (ms)

_**Using FlareSolverr...**_

**Comment by ilike2burnthing** [comment]
Please provide the information actually requested:
>**OS**:
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
**.Net Version**:
**Jackett Version**:
**Last Working Jackett Version**:
**Are you using a proxy or VPN?** [yes/no]

1337x.unblocked.monster - down, https://github.com/Jackett/Jackett/issues/11379

1337x.unblockit.club - working fine here with FlareSolverr, are other indexers which require FlareSolverr working (e.g. 7torrents)?

the rest - check if you can access them in browser from the same device and IP

**Comment by DrakeJones** [comment]
Sorry for the delay.  Putting the challenge cookie directly into the 1337x  json didn't work.  7 torents - same problem, but these others all work:
ETTV public 	
EZTV public 	
IBit public 	
LimeTorrents public 	
RARBG public 	
Speed.cd private 	
The Pirate Bay public

OS: Windows 7
.Net Runtime: .Net-Framework
.Net Version: v4.0.30319
Jackett Version: Version v0.17.931 
Last Working Jackett Version: ?
Are you using a proxy or VPN? No

Still getting this error: "An error occurred while testing this indexer
Exception (1337x): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=60000 (ms): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=60000 (ms)"

**Comment by ilike2burnthing** [comment]
For 1337x please try the new nocensor.space proxy. Are you able to access any of the site links in browser?

Which site links are you using for ETTV, EZTV and LimeTorrents? Depending on which ones you use, they may or may not need FlareSolverr. If you want some more to try - https://github.com/Jackett/Jackett/search?l=YAML&q=flaresolverr

For your .NET verson, doublecheck by going to `C:\Windows\Microsoft.NET\Framework\v4.0.30319`, right-click `Accessibility.dll`, click 'Properties`, and then look at the version number under the Details tab.

How do you have FlareSolverr installed, the binaries folder from https://github.com/FlareSolverr/FlareSolverr/releases or the Docker container? Have you tried the other?

If you open the FlareSolverr API URL (that you have added in Jackett's settings) in a web browser, what do you see?

**Comment by DrakeJones** [comment]
I signed up for an account with 7Torrents and it works fine.  I think this is the first time I've used an API key with a torrent site.  I'm using Jackett with NZBHydra2.  

1) I can pull up  nocensor.space with Firefox & Chrome, but 1337x isn't a listed there.

2) ETTV, EZTV and LimeTorrents: https://ettv.unblockit.club/, https://eztv.yt/, https://limetor.com/

3) C:\Windows\Microsoft.NET\Framework\v4.0.30319, right-click Accessibility.dll, click 'Properties` gives **v4.0.30319**

4) FlareSolverr installed from https://github.com/FlareSolverr/FlareSolverr/releases 

5) FlareSolverr API URL (http://localhost:8191) yields: {"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1619117283229,"endTimestamp":1619117283230,"version":"v1.2.3"}

I'll do more work and report back to you.

**Comment by ilike2burnthing** [comment]
7torrents is a public tracker, you don't need an account for it. Did it work in Jackett?

1) I meant in Jackett (and it is on the site)
2) OK, so none of those need FlareSolverr, so I'll need you to try some of those in the link I provided earlier - https://github.com/Jackett/Jackett/search?l=YAML&q=flaresolverr
3) Somehow your .NET install is 11 years old, not entirely sure how, Windows should have updated it. Install 4.8 - https://dotnet.microsoft.com/download/dotnet-framework
4) Update to v1.2.5 - https://github.com/FlareSolverr/FlareSolverr/releases

**Comment by DrakeJones** [comment]
### Thanks for the follow up.

1. Updated/upgraded per your suggestions.
2. I'm testing everything in Jackett.
3. 1337x still dosen't work.
4. Tried some of your suggested links:
- Torrentz2k works 
- SkyTorrents.to no joy
- TorrentProject works
- idope error certificate validation failed
- btdb works.

I have enough indexers for now, but I'm happy to continue troubleshooting if it will help other people.  And, I'm sure you'd like to know what's going on, too.

**Comment by ilike2burnthing** [comment]
Only other thing I can suggest would be running (or at least testing) FlareSolverr in Docker instead (or upgrading to Windows 10, seeing as Windows 7 isn't even supported by Microsoft anymore).

@ngosang are there any expected incompatibilities for FlareSolverr on Windows 7?

**Comment by DrakeJones** [comment]
I don't answer to question, but we can close the issue.
