### ISSUE TITLE
[rarbg] Could not find releases from this URL (Config) https://rarbg.to/

### ISSUE THREAD

**Issue by ttuuxxeerr** [Jackett/Jackett#11561]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

 An error occurred while updating this indexer
Could not find releases from this URL
Click here to open an issue on GitHub for this indexer.

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/11141
