### ISSUE TITLE
[gktorrent] https://www.gktorrent.cc/ returns not-found

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#11576]
https://www.gktorrent.cc/ not found
old domains all redirect to this one which appears to have disappeared from DNS

**Comment by ilike2burnthing** [comment]
I get `Error 522 - Connection timed out` after refreshing from CloudFlare's 'Always Online' snapshot.

**Comment by garfield69** [comment]
Switched back to using cloudflare 1.1.1.1 instead of quad9 9.9.9.9 and now I see 522 too.

**Comment by garfield69** [comment]
online
