### ISSUE TITLE
[req] MagicHeaven

### ISSUE THREAD

**Issue by apoorv569** [Jackett/Jackett#11587]
Please add https://magic-heaven.info/ in private torrent list. Registration is open and free right now.

**Comment by garfield69** [comment]
engine TS Special Edition v.7.5
MST 24h
MR ?

**Comment by garfield69** [comment]
v0.17.933

**Comment by garfield69** [comment]
https://magic-heaven.info/ Please wait while you are being redirected to the correct URL...
loops with http 200 but tag title has Fatal Error

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
@apoorv569 Do you have any news for MagicHeaven, is the site gone, just broken, or moved to a new domain?

**Comment by apoorv569** [comment]
> @apoorv569 Do you have any news for MagicHeaven, is the site gone, just broken, or moved to a new domain?

I don't, I tried the URL and it doesn't load for me either. I get a `NS_ERROR_UNKNOWN_HOST` (on Firefox).

**Comment by ilike2burnthing** [comment]
https://torrentinvites.org/f37/open-magic-heaven-info-general-621331/#post1615495

Site got sold, came back as https://magic-heaven.net/, but that now times out.

**Comment by garfield69** [comment]
v0.21.860
