### ISSUE TITLE
Can't download from sonarr/radarr: HTTP request failed: [404:NotFound] [GET] 

### ISSUE THREAD

**Issue by seanvree** [Jackett/Jackett#1159]
In the past couple days, I've noticed I can't DL anything from jackett via Sonarr/radarr:

Jackett ver: 0.7.1158.0
Windows 10E

The indexers can connect fine. 

Downloading torrent file for episode 'The Matrix Revolutions 2003 1080p Blu-ray VC-1 TrueHD 5.1-FGT' failed (http://192.168.1.20:9117/jackett/dl/nethd/yta2gs8jaetdm4atln6nxabhcqt9uemd?path=aHR0cDovL25ldGhkLm9yZy9kb3dubG9hZC5waHA_aWQ9MTA0ODEy0&file=The+Matrix+Revolutions+2003+1080p+Blu-ray+VC-1+TrueHD+5.1-FGT.torrent): HTTP request failed: [404:NotFound] [GET] at [http://192.168.1.20:9117/jackett/dl/nethd/yta2gs8jaetdm4atln6nxabhcqt9uemd?path=aHR0cDovL25ldGhkLm9yZy9kb3dubG9hZC5waHA_aWQ9MTA0ODEy0&file=The+Matrix+Revolutions+2003+1080p+Blu-ray+VC-1+TrueHD+5.1-FGT.torrent

NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://192.168.1.20:9117/jackett/dl/nethd/yta2gs8jaetdm4atln6nxabhcqt9uemd?path=aHR0cDovL25ldGhkLm9yZy9kb3dubG9hZC5waHA_aWQ9MTA0ODEy0&file=The+Matrix+Revolutions+2003+1080p+Blu-ray+VC-1+TrueHD+5.1-FGT.torrent]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 186
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteEpisode, String torrentUrl) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 222

**Comment by kaso17** [comment]
It's working fine for me. Please post the corresponding jackett log.

**Comment by seanvree** [comment]
@kaso17 

Failed download response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="NetHD.org" />
<meta name="description" content="" />
<meta name="generator" content="NetHD.org" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noarchive" />
<meta property="og:title" content="NetHD.org"/>
<meta property="og:image" content="pic/logo1.png"/>
<meta property="og:site_name" content="NetHD.org"/>
<meta property="og:description" content="" />
<title>NetHD.org</title>
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="search" type="application/opensearchdescription+xml" title="NetHD.org Torrents" href="opensearch.php" />
<link rel="stylesheet" href="styles/DarkPassion/theme.css?201408080048" type="text/css" />
<link rel="stylesheet" href="styles/DarkPassion/bootstrap.min.css?201408080048" />
<link rel="stylesheet" href="styles/DarkPassion/social.css?201408080048" type="text/css" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
<link rel="alternate" type="application/rss+xml" title="Latest Torrents" href="torrentrss.php" />
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>

<script src="js/common.js?201408080048"></script>
<script src="js/jquery.min.js?201408080048"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.lazyload.js"></script>
<script src="http://ads.hosting.vcmedia.vn/js.ashx" type="text/javascript"></script>


<script type="text/javascript">
function CJHide(){
jQuery("div[id^=\'CJ-button-wrapper\']").hide();
}
function CJShow(){
jQuery("div[id^=\'CJ-button-wrapper\']").show();
}
</script>
</head>
<body>
<div class="stickyz-container ">
<div class='col-md-12 hidden-xs hidden-sm'>
		<ul class="stickyz">
			<li>
				<a href=https://www.facebook.com/NetHD.org target=blank><img width="32" height="32" title="Facebook" alt="Facebook" src="pic/facebook.png" /></a>
			</li>
			<li>
				<a href=http://nethd.org/cinema.php target=blank><img width="32" height="32" title="NetHD Cinema" alt="NetHD Cinema" src="pic/cinema.png" /></a>
			</li>
			<li>
				<a href=http://www.utorrent.com/ target="_blank"><img width="32" height="32" title="Window/Mac/Linux" alt="Window/Mac/Linux" src="pic/utorrent.png" /></a>
				
			</li>
			<li>
				<a href=https://play.google.com/store/apps/details?id=com.vuze.torrent.downloader target="_blank"><img width="32" height="32" title="Vuze Android" alt="Vuze Android" src="pic/vuze.png" /></a>
				
			</li>
			<li>
				<a href=http://nethd.org/forums.php?action=viewforum&forumid=33 target="_blank"><img width="32" height="32" title="Support" alt="Support" src="pic/supportericon.png" /></a>
			</li>
			<li>
				<a href=#top><img width="32" height="32" title="Top" alt="Top" src="pic/topicon.png" /></a>
			</li>
		</ul>
</div></div>

<div id="user-bar">
        <div class="pagewidth">
            <div id='user-info' class='dropdown'><div data-toggle='dropdown' class='top-menu'><span class='hidden-xs'><dl><dt>ID:</dt><dd><a>481708</a></dd><dt>Rank:</dt><dd><a>Not Rank</a></dd><dt>VDP:</dt><dd><a>0</a></dd><dt>Point:</dt><dd><a>0.0</a></dd><dt>Uploaded:</dt><dd><a>10.00 GB</a></dd><dt>Downloaded:</dt><dd><a>0.00 KB</a></dd></dl></span><span class='nowrap'><a  data-target='#'  href='thanh-vien-so-481708-seanvree.html' class='User_Name'><b>seanvree</b></a></span>  <span class='caret'></span></div><div class='dropdown-menu multi-columns dropdown-menu-right col-md-12' role='menu'><div class='col-md-4 clearfix user-info-extend'><dl><dt>Connectable:&nbsp;</dt><dd>Unknown</dd><dt>Ratio:</dt><dd>Inf.</dd><dt>SLR:</dt><dd>99</dd><dt>Active Torrents: </dt><dd><span class='inline arrowup'></span>0</span><span class='inline arrowdown'></span>0</dd></dl></div><ul class='dropdown-menu col-md-4'>
					<li><a title='Change Password' href='usercp.php?action=security'>Change Password</a></li>
					<li><a title='User Detail' href='userdetails.php?id=481708'>Users Detail</a></li>
					<li><a title='Manage Bonus Point' href='mybonus.php'>Manage Point</a></li>
					<li><a title='Manage VDP' href='mybonus3.php'>Manage VDP</a></li>
					<li><a title='Donate' href='http://nethd.org/thanhtoan'>Donate</a></li>
					<li><a title='VIP Register' href='mybonus2.php'>VIP Register</a></li>
					<li><a title='Active User' href='activeuser.php'>Active User</a></li></ul>
				<ul class='dropdown-menu col-md-4'>
					<li><a title='Inbox' href='messages.php'>Inbox</a></li>
					<li><a title='Get RSS' href='getrss.php'>Get RSS</a></li>
					<li><a title='My Bookmarks' href='torrents.php?inclbookmarked=1&amp;allsec=1&amp;incldead=0'>Bookmarks</a></li><li><a href='logout.php'>Logout</a></li></ul></div></div>            <div class="clearfix"></div>
        </div>
        
    </div>
    <header>
        <div class="pagewidth">            
            <div class="logo">
                <a href="index.php">
                    <img src="pic/logo1.png" alt="NetHD.org" title="NetHD.org - Share to be shared more..." />                    
                </a>
            </div>
            <div id="main-menu">
                <span class='menu-toggle sprite'></span><ul class='menu menu-box'><li><a title='Home Page' href='index.php'>Home</a></li><li><a title='Torrent Page' href='torrents.php' target='blank'>Torrents</a></li><li><a title='Forums Page' href='forums.php' target='blank'>Forums</a></li><li><a title='Upload Page' href='upload.php'>Upload</a></li><li><a title='Subtitle Page' href='subtitles.php'>Subtitles</a></li><li><a title='User Control Panel Page' href='usercp.php'>User CP</a></li><li><a title='Top Ten Statistics Page' href='topten.php'>Top 10</a></li><li><a title='Rules Page' href='rules.php'>Rules</a></li><li><a title='Frequent Answer Question Page' href='faq.php'>FAQ</a></li><li><a title='Support' href='forums.php?action=viewforum&forumid=33'>Support</a></li></ul>            </div>
            <div class="clearfix"></div>
        </div>
    </header>
    <div class="container-fluid pagewidth">
<ul class='breadcrumb menu'><li itemscope itemtype='http://data-vocabulary.org/Breadcrumb'><a itemprop='url' href='index.php'><span itemprop='title'>Home</span></a></li><li itemscope itemtype='http://data-vocabulary.org/Breadcrumb'><a itemprop='url' href='download.php'><span itemprop='title'>Download</span></a></li></ul><h1>Error</h1>
<p>Permission denied!</p></div><div id='toolbar'><ul class='center-block'><li class='category-icons'><div class='category-icons-inner'><a href='torrents.php?cat=401' title='Movie'><span class='sprite movie'></span></a><a href='torrents.php?cat=402' title='Music'><span class='sprite music'></span></a><a href='torrents.php?cat=403' title='Game'><span class='sprite game'></span></a><a href='torrents.php?cat=404' title='Software'><span class='sprite software'></span></a><a href='torrents.php?cat=405' title='Image'><span class='sprite image'></span></a><a href='torrents.php?cat=406' title='Book'><span class='sprite book'></span></a></div></li><li class='category-icons'><div class='category-icons-inner'><a href='#' title='Top torrents' onclick='return openTopTorrent();'><span class='sprite top-torrent'></span></a><a href='torrents.php?sort=seeders&amp;type=desc' title='Best sharers'><span class='sprite best-sharers'></span></a></div></li><li><form method='GET' class='col-md-12 searchbox' action='torrents.php'><span class='glyphicon glyphicon-search in-textbox'></span><input type='text' name='search' placeholder='Search' /></form></li></ul></div><footer><div class='pagewidth clearfix'><div class='col col-xs-6 col-md-3'><h4>Game</h4><ul class='menu'><li><a href='cado.php'>Soccer</a></li><li><a href='landiep2.php'>Lottery</a></li></ul></div><div class='col col-xs-6 col-md-3'><h4>VDP, Point</h4><ul class='menu'><li><a href='mybonus.php'>Manage Point</a></li><li><a href='mybonus3.php'>Manage VDP</a></li></ul></div><div class='col col-xs-6 col-md-3'><h4>Torrent</h4><ul class='menu'><li><a href='torrents.php?sort=seeders&amp;type=desc'>Best sharers</a></li><li><a href='#' onclick='return openTopTorrent();'>Top torrents</a></li></ul></div><div class='col col-xs-6 col-md-3'><h4>Links</h4><ul class='menu'><li><a title='Users List Page' href='users.php'>Users</a></li><li><a title='Staffs Page' href='staff.php'>Staff</a></li></ul></div><div class='clearfix'></div><div class='credit'>
	(c)  <a href='https://nethd.org' target='_self'>NetHD.org</a>. Designed by <a href='index.php'>NothingIsImpossible</a><br /><span></span><br> 	
	[page created in <b> 0.002969 </b> sec with <b>8</b> db queries, <b>7</b> reads and <b>4</b> writes of memcached and <b>491.66 KB</b> ram]<br><br><br><br></div>
</div></footer><div id='myModal' class='modal fade'>
              <div class='modal-dialog'>
                <div class='modal-content'>
                  <div class='modal-header'>
                    <button type='button' class='close' data-dismiss='modal'><span aria-hidden='true'>&times;</span><span class='sr-only'>Close</span></button>
                    <h4 class='modal-title'></h4>
                  </div>
                  <div class='modal-body'>        
                  </div>
                  <div class='modal-footer'>        
                  </div>
                </div>
              </div>
            </div>    <script>
        $(document).ready(function(){
            $('.menu-toggle').click(function(){
                $(this).next().toggle();
            });
        });
        $(window).load(function(){
            $(".carousel img.lazy").each(function(){
                $(this).attr('src', $(this).attr('data-original'));
            });            
            $("img.lazy").lazyload();
        });
    </script>
    </body></html>
Mar 15, 2017 03:39:27 PM	Error	
Failed download cookies: c_secure_uid=NDgxNzA4; c_secure_pass=ef9a988ecee9081a77ce8797f2e55a87; c_secure_ssl=eWVhaA%3D%3D; c_secure_tracker_ssl=bm9wZQ%3D%3D; c_secure_login=bm9wZQ%3D%3D

**Comment by kaso17** [comment]
It's returning a "Permission denied!" error.
Please try downloading the torrent file via the nethd website, does that work?
Also change your password and logoff/login again (cookies are included in the log)

**Comment by RoloSoze** [comment]
NetHD's membership expires every six months. You'll need to send an email to the address mentioned on the website to have it renewed. You can still access the website but it won't let you download torrents.

**Comment by seanvree** [comment]
@kaso17 , @RoloSoze , thanks!
