### ISSUE TITLE
Turn on/off available categories in Jackett

### ISSUE THREAD

**Issue by ATor69** [Jackett/Jackett#1160]
This enhancement request is for the provided tracker "categories" to be able to be turned on/off at the user's discretion.  This will reduce the amount of unwanted/incorrect search results that could be returned for trackers that are not quality specific (Ex: Books v Audiobooks).  Since not all software this interfaces with supports category selection, being able to disable/enable categories on Jackett would be ideal.

-------------------------------

**Comment by kaso17** [comment]
I don't like the idea, it shouldn't be hard to make one more argument configurable in the client software. Do you have an example of such a client software (which doesn't support category selection)?

**Comment by ATor69** [comment]
LazyLibrarian

**Comment by RoloSoze** [comment]
@kaso17 Are any further actions required here?

**Comment by kaso17** [comment]
I'm planning to check out lazylibrarian. But I've very little available time for Jackett currently.
