### ISSUE TITLE
[hdbits] request 2FA support

### ISSUE THREAD

**Issue by xpliz** [Jackett/Jackett#11607]
Error: Login Failed! Two-Step password failed. Please try again. Username Password Two-step passcode Only required if you enabled two-step verificationMake sure your passcode generating device is time-synced properly. Recover password

It would be nice to have 2FA option for HDBits or HDBits API neither work when user has 2FA enabled

**Comment by xpliz** [comment]
[hdbits-api] response

An error occurred while updating this indexer
HDBits returned an error with status code 5: Invalid authentication credentials

**Comment by mekarawr** [comment]
it works for me, i have 2fa enabled and i use hdbits api in jackett. 
i do not use vpn nor seedbox so my torrent client, my browser and jacket all come from the same ip, i don't know if that could be a factor. is there something i can do to help provide more information to this use case?

**Comment by xpliz** [comment]
Indeed I can confirm HDBits API works with 2FA. @mekarawr I was using password instead of passkey. When I realized what I did and changed password for passphrase it started to work. Plain HDBits outputs error:

```
An error occurred while updating this indexer
Error: Login Failed! Two-Step password failed. Please try again. Username Password Two-step passcode Only required if you enabled two-step verificationMake sure your passcode generating device is time-synced properly. Recover password
Click here to open an issue on GitHub for this indexer.
```

**Comment by garfield69** [comment]
So we can close this ticket then, as using the API indexer works with 2FA enabled, and that is a working alternative to the standard indexer for non-2FA users.
