### ISSUE TITLE
[piratadigital] Change login method to cookie.

### ISSUE THREAD

**Issue by a-nunes** [Jackett/Jackett#11608]
### Environment

**OS**: Debian

**.Net Runtime**: Docker LinuxServer

**Jackett Version**: 0.17.946

### Description

Pirata Digital has updated its login system using CloudFlare captcha. I've tried to use FlareSolverr but it was unsuccessful.

Would it be possible to change it's login form to cookie method? Using this we can access without passing through the captcha.

**Comment by garfield69** [comment]
v0.17.952
