### ISSUE TITLE
[torrentleech-pl] Challenge detected but FlareSolverr is not configured (Config)

### ISSUE THREAD

**Issue by PrzemekSkw** [Jackett/Jackett#11613]
Hello, I think torrentleech.pl is not actuall. There's capcha when login to page. 

regards,
Przemek

**Comment by garfield69** [comment]
The indexer's config does not login to the web site. It uses the cookie method to resume the session you started by login onto the web site via your browser.
This allows for bypassing the cloudflare anti-ddos page as well as the login captcha page.
If you are having issues with your cookie read https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work

**Comment by PrzemekSkw** [comment]
@garfield69  Thanks for answer, I put wright cookie but I noticed that they ban when I use VPN. It's possible to bypass that?

Regards.

**Comment by garfield69** [comment]
>I noticed that they ban when I use VPN. It's possible to bypass that?

if you are able to use your VPN to login to the web site, but the cookie from there does not work with Jackett then that probably means that the web site is checking much more than a session id, but also the platform and possibly other signature details that differentiate the VPN server from your Jackett platform.
So no, it is unlikely you can bypass that. 
Sometimes some web sites lock the IP address with the session ID, and some VPN services allocate different IPs for each session, so you get a mismatch.
You could check if you can lock your VPN IP down to one, or perhaps try a different VPN service.

**Comment by PrzemekSkw** [comment]
No no, I cannot login and I cannot download torrents with VPN from that site.
Thanks for answer.
Regards.
