### ISSUE TITLE
[thesceneplace] Login Failed, got redirected. Try changing the indexer URL to https://www.thesceneplace.com/. (Config)

### ISSUE THREAD

**Issue by pipopablo** [Jackett/Jackett#11622]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker UnRaid  Linux 5.10.28-Unraid x86_64

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.946

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?** No

### Description

Attempting to add the tracker as a new indexer results in a Login Failed, got redirected error. The suggested step of altering the URL fom the default 'http' to include 'https' results in the same error.
PS. I only somewhat know what I'm doing here so apologies if there is missing or incorrect information

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Update to v0.17.952 where this was resolved.
