### ISSUE TITLE
Indexer Puntotorrent connection with Sonarr issue

### ISSUE THREAD

**Issue by carlosrc1990** [Jackett/Jackett#11620]
Hello, 
First at all, I want to apologize about my poor English. I noticed that the Puntotorrent Indexer showed no results in Sonarr. I posted it in Sonarr forums and they asked me that:
This is an issue with that tracker’s configuration in Jackett, it lacks the season and ep parameters Sonarr requires for searching:

Here is the link with the post where they said me where is the problem in the yaml.
https://forums.sonarr.tv/t/total-of-0-reports-were-found-for/28162

Thank you!

**OS**:DSM Synology

**.Net Runtime**: 5.20.1.34

**.Net Version**:

**Jackett Version**:v0.17.952

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** NO

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
[v0.17.954](https://github.com/Jackett/Jackett/releases/tag/v0.17.954)
