### ISSUE TITLE
[1337x] Exception (1337x): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (1337x.to:443) (Test)

### ISSUE THREAD

**Issue by mohammadfaran** [Jackett/Jackett#11626]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows Server 2019 Standard

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 

**Jackett Version**: v0.17.954

**Last Working Jackett Version**: just installed

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

iam unable to add most of the public indexers
![Jackett](https://user-images.githubusercontent.com/31722608/116429311-64b8e680-a863-11eb-80f6-81f587f5f9e5.PNG)

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
the 1337x indexer using the https://1337x.to/ domain works fine for me which suggests the issue is at your end.
the most likely explanation is that you are being blocked by your ISP.
try using your jackett dashboard to edit the 1337x config and select any of the alternate domains and see if they work for you.

**Comment by sinjinsmythe** [comment]
I can confirm I had the same issue, my ISP was blocking this site, I was able to get around it by enabling the socks 5 proxy option in jackett and routing my searches through a free socks5 web proxy.  Working fine for me now.  The other way is to set up a VPN container and route traffic through this, but haven't quite figured this out for my VPN provider yet.
