### ISSUE TITLE
[ilcorsaroblu] Login failed: No form found on https://ilcorsaroblu.online/index.php?page=login

### ISSUE THREAD

**Issue by Bazzu85** [Jackett/Jackett#11635]
Hi, the indexer changed from
https://ilcorsaroblu.org/
to 
https://ilcorsaroblu.online/

the login doesn't work anymore..

**Comment by ilike2burnthing** [comment]
[v0.17.963](https://github.com/Jackett/Jackett/releases/tag/v0.17.963)

**Comment by Bazzu85** [comment]
works, thx!
