### ISSUE TITLE
[yggtorrent] Challenge detected but FlareSolverr is not configured (Config)

### ISSUE THREAD

**Issue by 53212** [Jackett/Jackett#11631]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: MacOS 11.2.2 with Safari 14

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: The one released before 28th April 2021

**Last Working Jackett Version**: The same

**Are you using a proxy or VPN?** [yes/no] no

### Description

I only tried to add https://www4.yggtorrent.li/ as an indexer and my login  and passwords are correct

### Logged Error Messages

 An error occurred while updating this indexer
Challenge detected but FlareSolverr is not configured

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![Image 28-04-21 à 23 34](https://user-images.githubusercontent.com/62363262/116475671-76f24f00-a87a-11eb-9e6e-967540d30f5d.jpg)
![Image 28-04-21 à 23 35](https://user-images.githubusercontent.com/62363262/116475680-79ed3f80-a87a-11eb-85a4-d60f2fe71e35.jpg)

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
