### ISSUE TITLE
[sktorrent-org] The SSL connection could not be established, see inner exception.: Authentication failed, see inner exception. (Config)

### ISSUE THREAD

**Issue by tomasbulva** [Jackett/Jackett#11639]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
The indexer works for me so this suggest the problem is at your end.
Since you have given us nothing to work with, you will just have to figure out the problem on your own ;-b

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#authentication-failed-because-the-remote-party-has-closed-the-transport-stream

**Comment by AARON8888** [comment]
Hello @garfield69
Please check my case and try to get a solution (see attached .txt file).
[Nuevo documento de texto.txt](https://github.com/Jackett/Jackett/files/13665014/Nuevo.documento.de.texto.txt)

HTTP client: HttpWebClient in Windows 10.
Proxy: yes (HTTP)
Docker: No

**Comment by garfield69** [comment]
I'm getting 
[v0.21.1366.0] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'.
on my win10 jackett.
@ilike2burnthing  working for you on docker or ubuntu and breaking on windows or is it global?

**Comment by ilike2burnthing** [comment]
Working fine for me in Docker but not Windows 10 Sandbox. They're only using TLS 1.3, so it's that stupid Windows 11-only dotNET thing again. I'll try getting in contact with admins.

**Comment by AARON8888** [comment]
Now, Search and Test is ok.
