### ISSUE TITLE
[Bit-Titan] Wrong torrent sizes returned

### ISSUE THREAD

**Issue by Ticardy** [Jackett/Jackett#11643]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Unraid / linuxserver Docker image
**Jackett Version**: v0.17.963
**Are you using a proxy or VPN?** [yes/no] yes VPN

### Description

When searching for a media on Radarr or Sonarr (v3) through Torznab indexers from Jackett, results from Bit-Titan tracker are returned with a wrong size usually over 200 GB (for a movie and up to 60 GB for a tv episode) which prevent Radarr / Sonarr to grab it as it's over size limit depending on user settings. Looks like any file size is multiplied by 10 or something.

**Comment by garfield69** [comment]
It used to be the case that the browse.php page on Bit-Titan's Web site would display the **size** in European format, eg. `1.002,15 MB`, so the Jackett indexer would first remove the dot and replace the comma with a dot, returning the English `1002.15 MB` presentation.
It appears the Web site has now switched to using the English presentation, so now the indexer is incorrectly returning `100215 MB`
I'll submit a fix shortly.

**Comment by garfield69** [comment]
v0.17.966
