### ISSUE TITLE
[REQUEST] Public Tracker - www.reinventorrent.com

### ISSUE THREAD

**Issue by mankalan** [Jackett/Jackett#11648]
Type: Spanish and english Tv and Movie, Programs and games
Name: reinventorrent
Website: www.reinventorrent.com https://www.reinventorrent.com/
I would like to get this one added.
Im sure, this is a very good page
Thanks in advance.

**Comment by ilike2burnthing** [comment]
Search for TV series returns a result for each quality, and then has each episode on the details page (e.g. `Bruja Escarlata Y Visión`).

Films can have their own results or be included as part of collections.

Anyone who want's to give it a go, use an ad blocker, the pop ups are terrible. It also detects ad blockers, so you'll need to block the anti-adblock element too.

**Comment by luckkmaxx** [comment]
This web is currently moved at www.eltorpe.com
