### ISSUE TITLE
[ShizaProject] Exception (ShizaProject): Value cannot be null. (Parameter 'node'): Value cannot be null. (Parameter 'node') (Test)

### ISSUE THREAD

**Issue by dm3ch** [Jackett/Jackett#11659]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
access your Jackett dashboard and edit the shizaproject config
change http to https and save.

**Comment by dm3ch** [comment]
@garfield69 Yep I already found the reason of issue.

The problem caused cause during login flow `RequestLoginAndFollowRedirect` function handles redirect but sends redirected request with `GET` http method.

I think it would be better to solve this issue in newer version. But if I right understand fix you have done will help only new users, while users who already configured shizaproject indexer will need to reconfigure jackett manually, cause sitelink const is only used as a default value during configuration. Am I right?

Maybe we can somehow patch sitelink configuration value automatically (if it equals to old one default)?

**Comment by garfield69** [comment]
>But if I right understand fix you have done will help only new users

No. 324abe9 auto corrects existing configs as well as default to https for new users.
Fix will be included in the next published release, due out in about 9 hours or so.

**Comment by garfield69** [comment]
v0.17.996
