### ISSUE TITLE
Jackett not downloading from piratebay proxy

### ISSUE THREAD

**Issue by mrmrmrmr1** [Jackett/Jackett#1165]
[log.txt](https://github.com/Jackett/Jackett/files/848682/log.txt)
Hi,

I am using Jackett to download torrent files from Piratebay proxy with CouchPotato.
I am also using it with Sonarr.
With Sonarr , I have no issues but with CouchPotato, I can't download recently.

CouchPotato log shows :

`03-12 23:24:01 INFO
[hpotato.core.plugins.base] Opening url: get http://192.168.254.3:9117/dl/thepiratebay/0zxqrbto4omjw49z1wr53mvc5klg74fk?path=aHR0cHM6Ly91a3BpcmF0ZXByb3h5Lnh5ei90b3JyZW50LzE1Mzg5NjM1L0hpZ2hsYW5kZXJfKDE5ODYpXzEwODBwX0JyUmlwX3gyNjRfLV9WUFBW0&file=Highlander+(1986)+1080p+BrRip+x264+-+VPPV.torrent, data: []
03-12 23:24:02 ERROR
[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last): File "C:\Program Files (x86)\CouchPotatoServer\couchpotato\core\media\_base\providers\base.py", line 207, in download return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False) File "C:\Program Files (x86)\CouchPotatoServer\couchpotato\core\plugins\base.py", line 227, in urlopen response.raise_for_status() File "C:\Program Files (x86)\CouchPotatoServer\libs\requests\models.py", line 837, in raise_for_status raise HTTPError(http_error_msg, response=self) HTTPError: 404 Client Error: Not Found for url: http://192.168.254.3:9117/dl/thepiratebay/0zxqrbto4omjw49z1wr53mvc5klg74fk?path=aHR0cHM6Ly91a3BpcmF0ZXByb3h5Lnh5ei90b3JyZW50LzE1Mzg5NjM1L0hpZ2hsYW5kZXJfKDE5ODYpXzEwODBwX0JyUmlwX3gyNjRfLV9WUFBW0&file=Highlander+(1986)+1080p+BrRip+x264+-+VPPV.torrent`

when I call the link on my browser, Jackett does not show anything on 

`http://192.168.254.3:9117/dl/thepiratebay/0zxqrbto4omjw49z1wr53mvc5klg74fk?path=aHR0cHM6Ly91a3BpcmF0ZXByb3h5Lnh5ei90b3JyZW50LzE1Mzg5NjM1L0hpZ2hsYW5kZXJfKDE5ODYpXzEwODBwX0JyUmlwX3gyNjRfLV9WUFBW0&file=Highlander+(1986)+1080p+BrRip+x264+-+VPPV.torrent`

but `http://192.168.254.3:9117` is reachable.

Jackett log shows 👍 

`2017-03-16 18:55:45.3135 Info Starting web server at http://*:9117/ 
2017-03-16 18:55:46.0155 Info Service started 
2017-03-16 19:07:45.5947 Info Found 3 (1 new) releases from The Pirate Bay 
2017-03-16 19:23:15.5949 Info Found 9 (9 new) releases from The Pirate Bay 
2017-03-16 19:38:46.7581 Info Found 18 (18 new) releases from The Pirate Bay 
2017-03-16 19:54:18.1844 Info Found 16 (11 new) releases from The Pirate Bay 
2017-03-16 20:09:49.8457 Info Found 8 (7 new) releases from The Pirate Bay 
2017-03-16 20:25:21.4630 Info Found 9 (9 new) releases from The Pirate Bay 
2017-03-16 20:40:52.9302 Info Found 4 (1 new) releases from The Pirate Bay 
2017-03-16 20:56:25.1926 Info Found 5 (4 new) releases from The Pirate Bay 
2017-03-16 21:11:56.5158 Info Found 7 (3 new) releases from The Pirate Bay 
2017-03-16 21:15:08.2408 Info redirecting to /Admin/Dashboard 
2017-03-16 21:22:42.5718 Error Error downloading thepiratebay https://ukpirateproxy.xyz/torrent/15389635/Highlander_(1986)_1080p_BrRip_x264_-_VPPV MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
   konum: MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(RawReader reader)
   konum: Jackett.Controllers.DownloadController.<Download>d__4.MoveNext() C:\projects\jackett\src\Jackett\Controllers\DownloadController.cs içinde: satýr 56`

so, what is the issue here ?

I will also attache full log.

thanks.

Jackett version:    0.7.1167.0
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
It seems like they removed the download link for torrent files, only magnet links are supported now.
Jackett should no longer report a download link and CP should use the magnet link.

**Comment by mrmrmrmr1** [comment]
ok. so where should be the solution ?
jackett or Couchpotato ?

**Comment by kaso17** [comment]
If you're still getting this error the proxy site might be rewriting the links. Please share which proxy you're using.

**Comment by mrmrmrmr1** [comment]
what do you mean by "still getting" ?
nothing has changed , so I am still getting the error. Has anything changed on code ?

I am using Piratebay proxy as: https://ukpirateproxy.xyz/

**Comment by kaso17** [comment]
yes, the proxy site is to blame. They change the download link to the details page (I assume to show one more round of popup adds). I can't find the torrent hash in the result page, so there's no good way to fix it. I suggest you use another proxy page.

**Comment by mrmrmrmr1** [comment]
ok. but if you close this thread how can I find a solution ?
you say "try another proxy page" , you mean another piratebay proxy ?
I tried that with similar result. so what can I try now ?

**Comment by mrmrmrmr1** [comment]
btw, how does it work with Sonarr ?
I have the same settings on Sonarr and Couchpotato. there is no problem with Sonarr+Jackett 
and why are we dealing with download link when there is the magnet link ?

**Comment by kaso17** [comment]
yes, I mean another piratebay proxy.
If you compare the link of the magnet symbol of the search result page you'll see that it's not a magnet link on https://ukpirateproxy.xyz/ while it's on the official piratebay. That's the problem.
In order to get the magnet link we would have to get each detail page when https://ukpirateproxy.xyz/ is used. That would significantly increase the load and make the search much slower.

What do you mean with "no problem with Sonarr+jackett". using https://ukpirateproxy.xyz/ it shouldn't work at all for Sonarr or couchpotato.

**Comment by mrmrmrmr1** [comment]
hi,

I tried a few other piratebay proxies but all of them produced same results. I can't find a proxy site with proper download button. Do you have a working example ?
and what do you mean by "magnet link is not actually a magnet link"
I get this link under magnet link of an example:

> magnet:?xt=urn:btih:145bbee8591eec41c1d743c2dbe18bd7386a319d&dn=Passengers.2016.HC.HDRip.XViD.AC3-ETRG&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fpublic.popcorn-tracker.org%3A6969

it seems decent...

> What do you mean with "no problem with Sonarr+jackett". using https://ukpirateproxy.xyz/ it shouldn't work at all for Sonarr or couchpotato.

I mean , I use Jackett+SOnarr for TV series and Jackett+Couchpotato for movies.
I have no issues with this setup on Sonarr. it successfully catches the files.

now, what do I have to do ?

thx

**Comment by kaso17** [comment]
that magnet link looks fine, but that's not the one I'm getting from https://ukpirateproxy.xyz/

**Comment by mrmrmrmr1** [comment]
well , all I do is search for a movie and copy the link from magnet symbol.
anyway, what do you suggest for me  considering following : 

1. with sonarr I have no issues
2. with couchpotato+Jackett , using several different piratebay proxy servers, I can't succeed
3. magnet url seems ok, but looks like couchpotato is using download instead of magnet url

**Comment by mrmrmrmr1** [comment]
hi,

what can I do ?

**Comment by mrmrmrmr1** [comment]
am I the only one having this issue on Jackett ?

**Comment by mmarquezs** [comment]
@mrmrmrmr1 
The magnet icon from https://ukpirateproxy.xyz/ doesn't not provide a magnet, only a link to the details page as kazo17 said. 

I'm using http://ahoy.one/ and this one has a magnet and it should work fine.

**Comment by mrmrmrmr1** [comment]
thanks. I chnaged to that one now. but it still fails. I see this log when I try to download something : 
03-25 00:57:19 INFO
```
[hpotato.core.plugins.base] Opening url: get http://192.168.254.3:9117/dl/thepiratebay/0zxqrbto4omjw49z1wr53mvc5klg74fk?path=aHR0cHM6Ly91a3BpcmF0ZXByb3h5Lnh5ei90b3JyZW50LzE3MTMzNDgzL01vYW5hXzIwMTZfMTA4MHBfQmx1UmF5X3gyNjRfRFRTLUpZSw2&file=Moana+2016+1080p+BluRay+x264+DTS-JYK.torrent, data: []
03-25 00:57:21 ERROR
[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last): File "C:\Program Files (x86)\CouchPotatoServer\couchpotato\core\media\_base\providers\base.py", line 207, in download return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False) File "C:\Program Files (x86)\CouchPotatoServer\couchpotato\core\plugins\base.py", line 227, in urlopen response.raise_for_status() File "C:\Program Files (x86)\CouchPotatoServer\libs\requests\models.py", line 837, in raise_for_status raise HTTPError(http_error_msg, response=self) HTTPError: 404 Client Error: Not Found for url: http://192.168.254.3:9117/dl/thepiratebay/0zxqrbto4omjw49z1wr53mvc5klg74fk?path=aHR0cHM6Ly91a3BpcmF0ZXByb3h5Lnh5ei90b3JyZW50LzE3MTMzNDgzL01vYW5hXzIwMTZfMTA4MHBfQmx1UmF5X3gyNjRfRFRTLUpZSw2&file=Moana+2016+1080p+BluRay+x264+DTS-JYK.torrent
```

**Comment by mrmrmrmr1** [comment]
any ideas ?

**Comment by mrmrmrmr1** [comment]
please, I really need help.
I don't understand why I am the only one who requires help on this matter.
it should be a common problem.
I am not able to use CouchPotato with Jackett on piratebay proxy servers.
Similar setup on Sonarr works. 
SO it should note be a problem on my network or configuration...

**Comment by ractive74** [comment]
I can verify this same problem. Same setup... jackett + sonarr works fine, jackett + couchpotato does not grab magnet links.
