### ISSUE TITLE
Getting 404 error in my torrent client

### ISSUE THREAD

**Issue by CodeAbuser** [Jackett/Jackett#11664]
### Environment
Windows VM
**OS**:
Windows 10
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
unknown
**.Net Version**:
unknown
**Jackett Version**:
v0.17.972
**Last Working Jackett Version**:
N/A
**Are you using a proxy or VPN?** [yes/no]
No proxy.  Yes VPN
### Description

In my torrent client I have an RSS feed set up to autodownload from the Jackett rss feed.

It retreives the list from the feed but when it tries to download the file it gives me this error in my torrent client:  "server responded with code 404".

If I open the Jackett RSS feed in the browser and copy/paste one of the link values into a new tab and press enter it does prompt me to open my torrent client and it appears that the new torrent starts downloading correctly.

this is only not working in my torrent client's rss feed.

### Logged Error Messages

I don't have any logs to share.  If there are Jackett logs that would help I can get them.

### Screenshots

**Comment by ilike2burnthing** [comment]
Which torrent client, and what version of it?

Have you tried other clients?

Does this affect multiple indexers? Which ones? If any work, which ones?

Jackett logs can be found in the installation directory (default is C:\ProgramData\Jackett). Enable enhanced logging in Jackett's settings (bottom of the page), and apply server settings, and wait for the page to refresh. Make sure it has applied (if not, do so again), delete or move your current logs, access your client's RSS feed, attempt to download a torrent, and when the error occurs copy your new logs elsewhere. Redact any sensitive information (IP address, cookies, credentials, etc.) and post it here with your response.

You can then disable enhanced logging.

**Comment by CodeAbuser** [comment]
Thanks for the response. I will try some of this out and respond with logs
if needed.
