### ISSUE TITLE
[piratadigital] Searching for tvdbid + season over returning

### ISSUE THREAD

**Issue by a-nunes** [Jackett/Jackett#11660]
### Environment

**OS**: Debian

**.Net Runtime**: Docker LinuxServer

**Jackett Version**: v0.17.972

### Description

When searching just with tvdbid it returns properly results, but when combining tvdbid + season, it's returning all files that match only with season (seems that it's treated as 'OR' not 'AND'), when searching only with query (q param) + season, it returns the proper results again. Is it possible to remove the tvdbid option?

Thanks

**Comment by garfield69** [comment]
Please detail how you instigate a search with tvdbid + season so I can check if the indexer can be improved rather than simply drop tvdbid support in the indexer altogether.  Thanks.

**Comment by a-nunes** [comment]
1) I've got Sonarr search link in its trace log. When removing the "&season" tag, it returned all tvdbid series seasons correct (All 12 seasons of Bones)
2) Then I made a manual search on the site and it returns same values.
3) Used &season tag again with season=4, it returned random series that have s04 on title (including single episode ones)
4) Changed URL with q=Bones&season=4, it returned only the 4th season correctly;
5) Changed URL to q=Bones S04, it returned only 4th season correctly again.

Going Further) When looking series with tvdbid + season + episode, wrong results are shown too.

I deduced, with all this tests, that tvdbid with season or episode is get as 'OR' because it returns non sense series just because it have sXXeYY on release name.

Maybe the best setting for this tracker should be using only 'q' for search...

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/blob/324abe94a32e1022e0b934424b49517574b633ef/src/Jackett.Common/Definitions/piratadigital.yml#L61-L68
I'm thinking that if I expand line 63 to 
```yaml
    search: "{{ if or .Query.IMDBID .Query.TVDBID .Query.TMDBID }}{{ else }}{{ .Keywords }}{{ end }}"
```
this might solve the issue

**Comment by a-nunes** [comment]
I've made the try:

It returned the correct serie, but all seasons instead of only the searched one.

**Comment by garfield69** [comment]
ok so that means that it is the web site that is screwing up the search.
can you test this directly on the site to confirm?

**Comment by a-nunes** [comment]
Sure, what kind of search do you want me to try?

**Comment by garfield69** [comment]
yes, so you searched on the web site and confirmed that using a tvdbid plus adding s04 to the keywords  returns assorted s04 series and not just the series for the tvdbid?

**Comment by garfield69** [comment]
and so we should turn
https://github.com/Jackett/Jackett/blob/de6c365865f7e55bba33cf182e15adfbfdf9bbdd/src/Jackett.Common/Definitions/piratadigital.yml#L21
into 
```yaml
    tv-search: [q, season, ep, imdbid]
```
to give best results?

**Comment by garfield69** [comment]
looks like its a unit3d 2.7.0 design choice (as you said right at the start its an OR instead of an AND).
on other sites that use unit3d 5.2.0 (Blutopia for instance) the tvdbid + S01 yields only that series + season 1

I'll drop the tvdbid on piratadigital, but please keep an eye on when/if they upgrade their unit3d engine, because then it will be possible to use the tvdbid+season again.

**Comment by garfield69** [comment]
v0.17.996
