### ISSUE TITLE
[Bug] Chinese trackers do not return dead torrents in Manual Search

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#1168]
The following Chinese trackers do not return dead torrents in Jackett. It would be great if this can be fixed. Thanks you.

- [x] HDHome
- [x] HDSky
- [x] CHDBits
- [x] TorrentCCF
- [x] Ourbits (HDPter)
- [x] M-Team TP 

They're all based on NexusPHP and follow the same design, more or less. In order to view dead torrents on the trackers' websites, you'll need to expand the Search Box (at the top of the torrent browsing page), and on the far right you'll find a Show Dead/Active? drop-down box. Make sure it's set on 'including dead'. The tracker will remember this option. 

P.S. It would be great if the category mapping is checked as well. In rare cases, Jackett did return one or two dead torrents, which made me think the issue could be a combination of ignoring dead torrents + incomplete category mapping, 

Jackett version:  0.7.1176.0
Mono version (if not using Windows): N/A

**Comment by garfield69** [comment]
all these trackers have incldead: "1" now.
