### ISSUE TITLE
[REQ]sharefiles.ro

### ISSUE THREAD

**Issue by onlytanmoy** [Jackett/Jackett#11704]
Please add this private torrent tracker

https://sharefiles.ro/

Romanian
MST 3 days
MR 1000
Engine n/a

**Comment by garfield69** [comment]
v0.18.22

**Comment by garfield69** [comment]
https://sharefiles.ro/ returning Error 522 Connection timed out

**Comment by garfield69** [comment]
@onlytanmoy  do you know what has happened to sharefiles?
https://sharefiles.ro/ is still returning 522
We will be removing this indexer in a couple days which will mark 30 days offline.
If you find its moved to a new domain or is back up let us know and we will restore.

**Comment by alexdinu05** [comment]
Hi to all.
I have opened this thread just to inform you that there is a new beautiful site out there
the address is: https://scenelinks.io/
The most important feature of this tracker, other than the fact that is using tbdev is that
PRE times are EXTREMELY FAST...We win most tracers where we got traced.
This is what you can expect from us :)

Tracker Name: SceneLinks if you see it in tracers is under ScL
Tracker's URL: https://scenelinks.io/
Signup URL : https://scenelinks.io/signup.php
Tracker Type : It is a general tracker.
