### ISSUE TITLE
IPTorrents Freeleech Category

### ISSUE THREAD

**Issue by soulvoid86** [Jackett/Jackett#1171]
Not sure if it's possible to include the Freeleech category for IPTorrents to Jackett. That's the only feature it's missing for me!

Thanks :)
Sage

**Comment by soulvoid86** [comment]
Not sure if it helps, but this is the URL to the cat.

https://iptorrents.com/t?free

**Comment by kaso17** [comment]
What's your use case?
"Only download freeleech"?

**Comment by soulvoid86** [comment]
Yes, then fall back on non freeleech if possible. If not, I can just go in and manually search.

**Comment by kaso17** [comment]
The proper way of handling this is in Sonarr/Jackett. The corresponding attributes (See https://github.com/Sonarr/Sonarr/pull/1464) are already available for most indexers (including IPtorrents). They've been added exactly for this use case but Sonarr/Rararr currently ignores them in their download decision. In the Jackett manual search you can already sort by "DL factor". 

I suggest you open a new feature request at Sonarr/Radarr for this.

**Comment by soulvoid86** [comment]
Great, thank you!

**Comment by RoloSoze** [comment]
Closing this since the issue will be opened in the Sonarr issues page.

**Comment by sgtsquiggs** [comment]
Was this issue opened for Sonarr? Link?

**Comment by soulvoid86** [comment]
Nope, I never made the request. I was able to get my accounts ratio to a good point that I didn't need to worry about Freeleech anymore. I'd still like the feature, so feel free to open a feature request with them and share a link to this.

**Comment by sgtsquiggs** [comment]
It looks like support is already there, we've just got to set the parameters correctly. Not sure how to do that. https://github.com/Sonarr/Sonarr/pull/1464/commits/ae059b8b579028bf533563ae321447c4076f7ef8#diff-296846349176c449de176f079e98e6b8R78

**Comment by soulvoid86** [comment]
Yea, I tried researching it, but I'm not one for coding. I'm not sure where you set that, or what values actually mean anything. Seems like it's more of a guessing game with no info.

**Comment by soulvoid86** [comment]
That seems it's more of a, how much to download/upload, rather than a search feature. It's not very clear and I wasn't able to find much info on it. That's why I gave up for the time being.

**Comment by sgtsquiggs** [comment]
I just want to filter freeleech only. I can do this via RSS feeds in sonarr/radarr easily but no search!

**Comment by max01986** [comment]
I don't know if it could help you, but I just wrote a simple powershell script in order to download freeleech from my private tracker trough Jackett.. 
[](https://github.com/max01986/Jackett_RSS_Auto_Downloader)
