### ISSUE TITLE
[sharewoodapi] The SSL connection could not be established

### ISSUE THREAD

**Issue by EVOTk** [Jackett/Jackett#11716]
Hello,
I can't connect Sharewood to my jackett.

### Environment
**OS**: DSM 6.2.3
**Jackett Version**:  Jackett Version v0.18.31 
**Are you using a proxy or VPN?** YES Windscribe

### Description
I fill in my passkey and validate

### Logged Error Messages
An error occurred while updating this indexer
The SSL connection could not be established, see inner exception.: Cannot determine the frame size or a corrupted frame was received.

### Screenshots
![2021-05-12 16_47_32-Window](https://user-images.githubusercontent.com/45015615/117995858-f33c6600-b341-11eb-9584-fb6bc880a0cd.png)

Thx

**Comment by ilike2burnthing** [comment]
Do other indexers work?

Does sharewoodapi work if you disable your VPN?

**Comment by EVOTk** [comment]
> Do other indexers work?
>
Thank you for your reply.
Yes, I've been using Jackett for a while now.
I wanted to add Sharewood, but it doesn't work.

> Does sharewoodapi work if you disable your VPN?
>
My current setup doesn't allow me to do without a VPN, but I don't mind other indexers, and I have also tried changing VPN servers without success.

**Comment by EVOTk** [comment]
After that, I tried again without changing anything in my configuration and it works.
Maybe a temporary problem at Sharewood?
Thank you very much, it is solved for me (unfortunately without real explanation)

![2021-05-13 19_12_39-Jackett](https://user-images.githubusercontent.com/45015615/118161017-5e0f9f00-b41f-11eb-9451-a6cee0902831.png)
