### ISSUE TITLE
Jackett keeps restarting itself - Loses its connection to sonarr radarr 

### ISSUE THREAD

**Issue by GOODBOIXD** [Jackett/Jackett#11714]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Desbian 10 x64

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
v0.18.22

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]
no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

I installed jackett as a docker container along with other items such as sonarr and radarr for my jellyfin setup. Also have portainer installed. Jackett keeps restarting itself and hence loses its connection to sonarr and radarr from time to time. When I checked on portainer, everything else was running but jackett's health check showed as unhealthy or starting -  I have posted a screenshot of the said error below. I have tried reinstalling jackett and the whole setup twice but nothing seems to work. 

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

full log - https://0bin.net/paste/jh8ZUYVQ#fBnI42JoVlf9x48PKGixwC3ndBp83cFkx7jP4HegxaL

### Screenshots

https://imgur.com/a/4rutdJY

**Comment by ilike2burnthing** [comment]
LS.io's Jackett image doesn't have a health check, so have you added one? Specifically have you added one which uses netstat? From the error it seems like that's not part of the image either.
