### ISSUE TITLE
Ability to set RARBG Torrentapi URL

### ISSUE THREAD

**Issue by agneevX** [Jackett/Jackett#11723]
### Environment

**OS**: N/A
**.Net Runtime**: N/A
**.Net Version**: N/A
**Jackett Version**: N/A
**Last Working Jackett Version**: N/A
**Are you using a proxy or VPN?**: N/A

### Description

Would be nice if this URL could be changed or set to HTTP/HTTPS instead of just using HTTPS.

https://github.com/Jackett/Jackett/blob/6a213c6eabd0264392c48564ff16a9035fd13ca4/src/Jackett.Common/Indexers/RarBG.cs#L25

I have found in my experience that accessing via HTTPS often gets blocked because of ISP's SNI filtering. HTTP works most of the time.

### Logged Error Messages

N/A

### Screenshots

N/A

**Comment by ilike2burnthing** [comment]
@garfield69 what do you think about adding something like [AniLibria](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/AniLibria.cs)'s bespoke [config](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataAniLibria.cs) for RARBG?

**Comment by ilike2burnthing** [comment]
Well it works at least... - https://github.com/Jackett/Jackett/pull/11724

**Comment by garfield69** [comment]
these days we seems to be using the dynamic method, a la torrentnetwork for example:
define:
https://github.com/Jackett/Jackett/blob/6a213c6eabd0264392c48564ff16a9035fd13ca4/src/Jackett.Common/Indexers/TorrentNetwork.cs#L72
fetch:
https://github.com/Jackett/Jackett/blob/6a213c6eabd0264392c48564ff16a9035fd13ca4/src/Jackett.Common/Indexers/TorrentNetwork.cs#L129

there are probably better examples in other C# indexers.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/blob/b07543bff61dce8b59bc58d99a45c817b45b7d79/src/Jackett.Common/Indexers/Xthor.cs is probably a more recent example with better dynamic config examples

**Comment by garfield69** [comment]
Oh, you've gone ahead with the standard config. Well and good, if it works then merge it in. :-)

**Comment by ilike2burnthing** [comment]
Currently trying the dynamic method, so we'll see how that goes 😋

**Comment by garfield69** [comment]
v0.18.59
