### ISSUE TITLE
[trackeros] Fix season/chapter issues

### ISSUE THREAD

**Issue by diegargon** [Jackett/Jackett#11720]
Hello. Season/Chapters identifications are wrong (non standard).
File:
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/trackeros.yml

Replace:  S01 E01
To: S01E01
Example: El cuento de la criada (2017) S04 E05 

Multi episode
Replace: S01 E01 E02 E03
To: S01E1-E3?

Other naming styles:
Manifest (2018) S03 E07 E08 AMZN WEB-DL 
Los secretos de Sulphur Springs (2021) S01 E07 E08 E09 E10 E11
Equipo Danger T1 E8-11 (2020)
los hombres de paco T10 E01-02

**Comment by diegargon** [comment]
Another problem is Jackett not got/send the poster:
Poster Line:
<img src="https://images.weserv.nl/?url=https://image.tmdb.org/t/p/original/6psPEKu03UCiLqBxzeSy7wRQOVN.jpg&amp;w=325&amp;h=485" class="movie-poster img-responsive hidden-xs">

**Comment by garfield69** [comment]
v0.18.205
