### ISSUE TITLE
[Fuzer] Please add missing category

### ISSUE THREAD

**Issue by BuSHari** [Jackett/Jackett#11731]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment
Docker
**OS**:
Unraid
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
v0.18.59
**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

Can you please add the missing category for "סדרות UHD" as TVUHD type, the category id is 100.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
v0.18.67

**Comment by BuSHari** [comment]
Thanks! its working...
