### ISSUE TITLE
[BakaBT] General Improvements

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#1173]
I believe BakaBT has not been brought up to speed with the latest Jackett features & enhancements. Among those are the following:

1. Mark the tracker as Semi-Private. I believe registration is always open at https://bakabt.me/signup.php

2. The Manual Search results table is incomplete - Needs freeleech / discount rules, number of files, category (not sure if these are up to date), grabs, and DL & UL factors. 

3. Allow the display of adult content, provided that the corresponding option is enabled in user profile settings. 

If anyone uses BakaBT often and has other improvement areas or bugs to highlight, please feel free to comment.

Jackett version:  0.7.1176.0
Mono version (if not using Windows):  N/A

**Comment by kaso17** [comment]
fixed via a0d0b2cb4047b821c3d0c1964cfe1f106ed60a42

**Comment by advancedslicedbanana** [comment]
I'd like to add a general improvement comment if it's appropriate here.

When using BakaBT with Radarr (using anime category 5070) Jackett appends "Season 1" to all movie releases causing Radarr to not recognize the release. BakaBT has no mention of "Season 1" in the movie releases, rather, it seems that Jackett adds that to all movie releases.
