### ISSUE TITLE
Jackett service, updater tray and console constantly blocked by Kaspersky

### ISSUE THREAD

**Issue by element4l** [Jackett/Jackett#11744]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 7 SP1

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Latest

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] No

### Description

Because Jackett always uses new temporary files to do its bidding, there is no way to change the detection for Kaspersky. I can add these to exceptions, but it never works because jackett never uses the same file to perform its actions. 

Let me be clear, I understand this is a false positive. What I don't understand is why, out of every single program I use on my computer (hundreds), Jackett is the single larget nuisance when it comes to this. I literally don't have to deal with this problem anywhere else. And I've been using Kaspersky for years. 

To be clear, these are warnings that the apps are trying to modify other processes and create keys etc, and I can manually allow them, but this happens at least once a day, where I have to individually approve ten or so popups from Kaspersky just because Jackett's updating. Even if I select the options to apply to all of the series/trust the application. 

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Try manually adding Jackett's executables as `Trusted Applications` in Kaspersky, with the settings:
- do not scan files before opening
- do not monitor application activity
- do not inherit restrictions from the (application's) parent process
- do not monitor the activity of child applications (and apply exclusion recursively)
- do not scan all traffic

Not all of those may be needed, so feel free to play about with them, but if you add them all to start you can be certain it's working.

**Comment by element4l** [comment]
Seems to have worked so far. Many many thanks. It was a hassle to find
Kaspersky's Trusted Applications section, which is in an entirely different
location than its Application Manager section for some reason.

**Comment by ilike2burnthing** [comment]
Trusted Applications are basically an extension of its exclusions, whereas Application Manager is its HIPS component - similar names, but completely different functions.
