### ISSUE TITLE
Anidex Torznab search returns no results via the API when using cat instead of category in search query

### ISSUE THREAD

**Issue by tom7980** [Jackett/Jackett#11755]
### Environment

**OS**: Windows 10

**.Net Runtime**: .Net Framework

**.Net Version**: 4.8

**Jackett Version**: v0.18.88

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?** no

### Description

When trying to use Jackett with Sonarr to scrape the Anidex Tracker Sonarr will send Jackett an API request with the category option set to cat i.e. `http://127.0.0.1:9117/api/v2.0/indexers/anidex/results/torznab/api?t=tvsearch&apikey=(key removed)&offset=0&limit=100&cat=5070
`
This provides no results from the torznab API that Jackett provides for this tracker however. 

If I replace **cat** with **category** i.e. `http://127.0.0.1:9117/api/v2.0/indexers/anidex/results/torznab/api?t=tvsearch&apikey=(key removed)&offset=0&limit=100&category=5070`

This starts to return results from the API, however I can't manually tell Sonarr to expand it's url parameters to the full word & this issue doesn't exist on other trackers.

### Logged Error Messages

Logs only show that no results were found on the tracker

### Screenshots

[Image of API response when using cat only](https://imgur.com/a/JU54j16)

[image of API response when expanding to category](https://imgur.com/a/Yvjpwvs)

**Comment by ilike2burnthing** [comment]
`cat` is correct, all changing it to `category` does is ignore searching by category:

cat - `https://anidex.info/?q=&s=upload_timestamp&o=desc&group_id=0&id=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16&lang_id=`

category - `https://anidex.info/?q=&s=upload_timestamp&o=desc&group_id=0&lang_id=`

catsNdogs - `https://anidex.info/?q=&s=upload_timestamp&o=desc&group_id=0&lang_id=`

There is a problem with searching by category though - https://github.com/Jackett/Jackett/issues/9727

**Comment by ilike2burnthing** [comment]
Fix will be out in the next release.
