### ISSUE TITLE
iptorrents: missing category

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#11751]
![image](https://user-images.githubusercontent.com/10577978/118406818-d5db0500-b67d-11eb-9def-f6af85ac78bc.png)

**Comment by garfield69** [comment]
how about providing the html so that we can add the missing category?
you are the only one in the group with a working account, mine was disabled in January :-(

**Comment by ngosang** [comment]
@garfield69 I can invite you again if you provide another email address.

**Comment by garfield69** [comment]
Perhaps better to pass the invite to @ilike2burnthing 
I expect whatever reason the site had for disabling my account would only repeat on any new a/c since I am not active enough to satisfy their minimum requirements :-D

**Comment by ilike2burnthing** [comment]
If they need regular seeding to keep the account active, then the invite will be wasted on me, but if accessing the site a few times a month is enough then I'll be happy to take it.

**Comment by ngosang** [comment]
I'm not sure, we can try. Gimme the email.

**Comment by ilike2burnthing** [comment]
jacketttest(at)gmail(dot)com

**Comment by ngosang** [comment]
Sent
