### ISSUE TITLE
erai-raws: add details link

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#11750]
I don't know if it's possible for this indexer but it's a god idea to provide a details links. The link must be unique.

**Comment by garfield69** [comment]
@6cUbi57z can you look into this?
If available, the details link is a url that points to the details page of a torrent, and the field in your erai-raws indexers ReleaseInfo list is `Details` 
Thanks.

**Comment by 6cUbi57z** [comment]
Unfortunately the page URL for the details isn't included in the RSS feed but I'll have a look see if there's a common format that it uses to see if it can be calculated.

On the point of "The link must be uniquie", I believe erai-raws uses one page for a release which then has links on that release page for each quality. So the details link would be shared by all qualities of a given episode. Is this a Jackett requirement or some downstream app?

**Comment by garfield69** [comment]
Hmm. Not sure what @ngosang  meant here.
I think its based on the fact that many of the C# indexers use `Guid = details`, but it's the Guid that must be unique.
So IMO your Details just needs to point to the common group page for the related torrents, and as long as you don't assign your Details link to the Guid, but keep it unique (the current magnet URI should be fine) then you are good to go.

**Comment by Ansem93** [comment]
Can confirm, on version v0.18.106 it works.
Not sure what change broke/fixed it since I can't fine anything in the changelog :/

**Comment by garfield69** [comment]
@Ansem93  what are you confirming?
To test do a Jackett dashboard manual search with the  erai-raws indexer, and click on the name of one of the titles in the rest. If working, it should take you to the torrent details page for that torrent on the web site.

**Comment by Ansem93** [comment]
ooops, wrong issue!

**Comment by garfield69** [comment]
v0.18.145
