### ISSUE TITLE
[New Tracker REQ] HDBits.org

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#1175]
**Indexer Name**
HDBits

**Type**
Movies & TV in HD

**Indexer URL**
https://hdbits.org/

**Indexer Language**
English

**Invite**
- It would be ideal if a current HDBits member is willing to start a conversion with the staff about providing an invite to a Jackett developer to add support for HDBits. 

- Otherwise, if a current HDBits member is willing to implement Jackett support themselves and submit a pull request for review, that would work too. 

**Note**
HDBits is a large HD-only TV & movie tracker with around 195K torrents.

**Comment by adamwinn** [comment]
I can probably create a pull request for this

**Comment by RoloSoze** [comment]
@kaso17 @flightlevel Would you guys be willing to review @adamwinn's pull request for HDBits?

**Comment by RoloSoze** [comment]
@adamwinn Given your recent pull requests, any interest in adding **I Love Classic**?

**Comment by adamwinn** [comment]
@RoloSoze I'm working on getting an invite as we speak

**Comment by adamwinn** [comment]
I'm going to have to pass on doing this one.  They use a csrf token during login.  Also, you get redirected and logged in again with a separate hash, pass, and uid that seems system generated.  I don't want to risk getting banned trying to figure it out.

**Comment by RoloSoze** [comment]
@adamwinn Are you willing to speak to the admins & developers about this? They may be able to help if they knew the purpose is adding Jackett support.

**Comment by adamwinn** [comment]
No, I'm brand new there

**Comment by RoloSoze** [comment]
@adamwinn No problem at all. We may be able to sort this out some other way in the future. 

Thank you for your tremendous contributions so far. Any other trackers would be welcome :)

**Comment by kaso17** [comment]
Without having access you'll have to use form based login "method: form" with "path: /login"
The CSRF part should be handled fine. If there are multiple redirects setting cookies it might be a problem.

**Comment by adamwinn** [comment]
Actually, is this even needed since they have an API?  I figured that's why Jackett didn't have support for hdbits and BTN since they have an API and have native support in Sonarr.

**Comment by RoloSoze** [comment]
@adamwinn Jackett actually supports BTN but none of the current developers is a member of BTN, so the features for this tracker are outdated as far as I understand.

**Comment by adamwinn** [comment]
I used 
```
path: /login
method: form
form: form
```
as @kaso17 suggested.  It works great.  I'll have this ready soon

**Comment by adamwinn** [comment]
@RoloSoze @kaso17 Since HDBits has a proper API, is there a need to scrape the site with Jackett?  Any info needed from HDBits can just come from the API.  They don't like site scraping and it's actually against their rules

**Comment by adamwinn** [comment]
Fixed with #1235

**Comment by koushik-sen-vst-au4** [comment]
I wish someone could add me.I also want to help.
And please someone invite me.
