### ISSUE TITLE
[xspeeds] Exception (xspeeds): String 'Pre Release Time: 25-04-2021 15:00  Uploaded: 3 Weeks, 2 Days, 23 Hours, 53 Minutes, 39 Seconds after Pre' was not recognized as a valid DateTime.: Parse error (Config)

### ISSUE THREAD

**Issue by invisiblelightx1** [Jackett/Jackett#11767]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
I don't get this doing a keywordless search. What were you searching for?

**Comment by garfield69** [comment]
never mind. found the culprit
![image](https://user-images.githubusercontent.com/6933240/118904621-5c3d6280-b96e-11eb-89d1-d5d60fbe3c30.png)
not sure if this is a results of the torrent being a *request* or if this is just the one user generating these strange date strings, but I'll see if I can update the indexer to cope with these anomalous date strings which are usually just dd-MM-yyyy HH:mm

**Comment by garfield69** [comment]
v0.18.96
