### ISSUE TITLE
JackettUpdater.exe Malware Detection (Win32:MdeClass)

### ISSUE THREAD

**Issue by solojourner** [Jackett/Jackett#11764]
![SnapCrab_NoName_2021-5-19_8-43-14_No-00](https://user-images.githubusercontent.com/7097019/118836127-d4c5f580-b880-11eb-8b3e-87c2a1e61ab1.png)
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Framework]

**.Net Version**: v4.0.30319

**Jackett Version**: v0.18.95

**Last Working Jackett Version**: v0.18.95

**Are you using a proxy or VPN?** [no]

### Description

JackettUpdater.exe and JacketService.exe moved to Avast virus chest as being identified with Win32:MdeClass malware. This happened on three different machines while updating Jackett. First machine was on auto-update, and the other two on manual update.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
It's a false positive, probably based on the behaviour of downloading files, extracting them to temp, overwriting existing, and running them (also setting it to run at startup if that's how you have Jackett configured).

You can confirm this by downloading the latest [binaries](https://github.com/Jackett/Jackett/releases/download/v0.18.95/Jackett.Binaries.Windows.zip), exacting them in your download folder, and manually scanning them with Avast; it shouldn't trigger the same detection.

Create an exclusion for Jackett's executables (not sure if Avast has the option to also exclude child processes but, if so, do that), and restore the quarantined file or reinstall Jackett.

If you want you can report the false positive to Avast - https://www.avast.com/en-us/false-positive-file-form.php

Let us know how you get on.

**Comment by solojourner** [comment]
All's well!
