### ISSUE TITLE
[yggtorrent] FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: Error: net::ERR_NAME_NOT_RESOLVED at https://www.yggtorrent.li/ (Config)

### ISSUE THREAD

**Issue by yblis** [Jackett/Jackett#11777]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
your site link is out of date.
use your Jackett dashboard to edit the yggtorrent config and update your site link to `https://www4.yggtorrent.li/`

**Comment by yblis** [comment]
it's same with this link :

An error occurred while updating this indexer
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: Error: net::ERR_NAME_NOT_RESOLVED at https://www4.yggtorrent.li/

**Comment by garfield69** [comment]
@ilike2burnthing  what do you think? Seems something is wrong with the OP's DNS?

**Comment by ilike2burnthing** [comment]
Yea, seems like the most likely option for it not resolving.

@yblis try changing your DNS (e.g. Cloudflare - 1.1.1.1 and 1.0.0.1 or Google - 8.8.8.8 and  8.8.4.4). If that doesn't work, please provide the requested information in the original post. If you're using a VPN, try without it as well.

**Comment by JigSawFr** [comment]
I can confirm that's working as expected on my side
