### ISSUE TITLE
Jackett Dev Help

### ISSUE THREAD

**Issue by silverbullettruck2001** [Jackett/Jackett#1177]
I am trying work on some changes for Jackett but when I try to debug the Jackett solution VS 2015 gives me an error of "A project with an Output Type of Class Library cannot be started directly.  In order to debug this project, add an executable project to this solution which references the library project.  Set the executable project as the startup project".  Can someone provide some pointers on how to successfully do what this is asking?  I just figured it would start up with the standard Jackett webpage as if I was debugging a normal MVC site in VS2015.  Any assistance on getting started with Jackett dev would be appreciated.  Thanks in advance!

**Comment by kaso17** [comment]
You've to change the Executed project (drop down next to the the start button) to "JackettConsole.exe".

If you're planning to add a new tracker I suggest to use a Cardigann Definition if possible (Have a look at the Definitions directory for some examples). It doesn't require recompiling Jackett.

**Comment by RoloSoze** [comment]
@silverbullettruck2001 Has @kaso17's response answered your question?

**Comment by RoloSoze** [comment]
@silverbullettruck2001 Feel free to reopen this if you still need help.

**Comment by silverbullettruck2001** [comment]
Sorry for not responding sooner.  I have been able to get the project to build now, but in takining @kaso17's suggestion I was looking at the Cardigann Definitions and I am trying to understand them better.  Are there any resources you could point me to that would help understand what I need to do to make my own definitions?
