### ISSUE TITLE
jackett is not handling sonarr's query correctly for cartoonchaos

### ISSUE THREAD

**Issue by Junkbite** [Jackett/Jackett#11775]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:docker unbuntu

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: latest

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
anything i search in sonarr doesnt come back with any results from cartoonchaos but when i search in jackett the results do come back. I ran debug log and looked through them and saw nothing that stuck out. I do see it searched on cartoonchaos but didnt see any logs about something coming back. I have all categories and all anime categories selected. if i remove `&season=4` from the jackett api call and call it manually, then results do come back.

### Logged Error Messages
```
http://192.168.1.76:9117/api/v2.0/indexers/cartoonchaos/results/torznab/api?t=tvsearch&cat=5000,100014,100015,100016,100017,100020,100021,100023,100024,100026,100028,100029,100030,100041,100042,100043,100045,2000&extended=1&apikey=(removed)&offset=0&limit=100&q=Scooby%20Doo%20and%20Scrappy%20Doo&season=4
```

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
yup, the default processing for a torznab request is to take the `&season=4` parm and turn it into a `S04`, and a `&ep=2` parm  into `E02` generating a search for `Scooby Doo and Scrappy Doo S04E02`

the torznab parm `&season=4` on its own generates  `Scooby Doo and Scrappy Doo S04` and not `Scooby Doo and Scrappy Doo season 4` as you were expecting.

We will need to investigate if the indexer can be modified to detect a season without episode search and see if it can generate `Scooby Doo and Scrappy Doo season 4`

**Comment by garfield69** [comment]
found an example from another yaml indexer
https://github.com/Jackett/Jackett/blob/6a213c6eabd0264392c48564ff16a9035fd13ca4/src/Jackett.Common/Definitions/uhdbits.yml#L84-L87
so we can try this on CC and see if that works.

**Comment by ilike2burnthing** [comment]
[v0.18.100](https://github.com/Jackett/Jackett/releases/tag/v0.18.100)
