### ISSUE TITLE
[acgrip] Exception (acgrip): Request to https://acg.rip/?term= failed (Error BadGateway) - The tracker seems to be down.: Request to https://acg.rip/?term= failed (Error BadGateway) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by allanpk716** [Jackett/Jackett#11772]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
use linuxserver/jackett:latest docker
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
use linuxserver/jackett:latest docker
**.Net Version**:
use linuxserver/jackett:latest docker
**Jackett Version**:
v0.18.98
**Last Working Jackett Version**:
no one
**Are you using a proxy or VPN?** [yes/no]
yes
### Description

press ACG.RIP Test Button then show BadGateway message. I can visit ACG.RIP website by my vpn.

### Logged Error Messages

```
05-21 16:24:19 Error Jackett.Common.IndexerException: Exception (acgrip): Request to https://acg.rip/?term= failed (Error BadGateway) - The tracker seems to be down.
, ---> System.Exception: Request to https://acg.rip/?term= failed (Error BadGateway) - The tracker seems to be down.
,   at Jackett.Common.Indexers.BaseWebIndexer.CheckSiteDown(WebResult response) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 618
,   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 574
,   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1327
,   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 395
,   --- End of inner exception stack trace ---
,   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 738
,   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 308
,   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
,   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
,   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
,   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
,   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
,   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
,   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
,   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
,   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
,   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
,   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 Jackett.Common.IndexerException: Exception (acgrip): Request to https://acg.rip/?term= failed (Error BadGateway) - The tracker seems to be down.
,   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
,   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
I can TEST acg.rip on my win10 Jackett without a VPN without issues.
I am not clear on your report. 
Are you saying that Jackett going through the VPN fails, but that a browser going through the VPN succeeds?
Can you access the site on a browser running on the same machine as Jackett without a VPN? 
Can the Jackett indexer TEST the site without a VPN active?

**Comment by allanpk716** [comment]
> Are you saying that Jackett going through the VPN fails, but that a browser going through the VPN succeeds?

Yes.

> Can you access the site on a browser running on the same machine as Jackett without a VPN?

I can't. I'am in China...

> Can the Jackett indexer TEST the site without a VPN active?

with out VPN, it will show the err message :

`Exception (acgrip): Network is unreachable: Network is unreachable (acg.rip:443)`

**Comment by allanpk716** [comment]
Other Indexer Test through VPN is OK, just ACG.RIP is error.

**Comment by garfield69** [comment]
@ilike2burnthing  any insights for this topic, its out of my area of expertise. Thanks.

**Comment by ilike2burnthing** [comment]
Do you have DNS set for your container? If so, what? Have you tried others?

If your VPN separate from Jackett, or are you using Jackett's proxy settings?

**Comment by allanpk716** [comment]
> Do you have DNS set for your container? If so, what? Have you tried others?
> 
> Is your VPN separate from Jackett, or are you using Jackett's proxy settings?

This DNS Problem, thank you for helping me.
