### ISSUE TITLE
[RuTracker.org] Missing "+" symbol for Rutracker.org

### ISSUE THREAD

**Issue by DarrenPIngram** [Jackett/Jackett#11778]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: MacOS

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.18.98

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?** [yes/no]no

### Description
When using Jackett there is no "+" icon for Rutracker.ORG (when brought up with the search index). There IS a "+" icon for another Rutracker (Rutracker.ru) but that is a different site.

[List steps to reproduce the error and details on what happens and what you expected to happen]
I would expect a "+" icon be present so that the tracker can be added.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
This is because rutracker.org is **semi-private** which means that you have to add a username and password before you can use the indexer.
Only **public** indexers get a **plus** to add the indexer to your active page without additional user input.
rutracker is semi-private because you cannot access https://rutracker.org/forum/tracker.php without registration.

**Comment by DarrenPIngram** [comment]
Thank you for the information and prompt response, and my apologies for any
misunderstanding!
‌
