### ISSUE TITLE
[bit-titan] Login failed: No form found on https://bit-titan.net/login.php using form selector form[action=

### ISSUE THREAD

**Issue by Ticardy** [Jackett/Jackett#11787]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Unraid / linuxserver Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.18.100

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** yes

### Description

Trying to add this Indexer. Worked perfect till yesterday. Also captcha is no longer shown in Jackett. 

### Logged Error Messages

Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://bit-titan.net/login.php using form selector form[action="takelogin.php"]

**Comment by garfield69** [comment]
Yes, the site has enabled what they are calling **spam** protection, so the login has changed.
I will try to amend the indexer to use the new login layout.

**Comment by garfield69** [comment]
v0.18.145
