### ISSUE TITLE
[limetorrents] Exception (limetorrents): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (www.limetorrents.info:443) (Test)

### ISSUE THREAD

**Issue by madhit397** [Jackett/Jackett#11789]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 4.8.04084

**Jackett Version**: v0.18.106

**Last Working Jackett Version**: my first use

**Are you using a proxy or VPN?** no

### Description

When I search anything on the manual search field most search indexes say "error" next to it.  And when I test any of those indexes, the test fails. I am new to using this so may be I messed up something while setting it up.

### Screenshots
![image](https://user-images.githubusercontent.com/84627498/119264642-a4c07e80-bc01-11eb-93e8-1611288478ca.png)

![image](https://user-images.githubusercontent.com/84627498/119264594-7a6ec100-bc01-11eb-9d56-47f13cb08f4c.png)

**Comment by garfield69** [comment]
We can assume that whatever is causing the error on one indexer also applies to the others.
Pease read and action https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
test just one indexer and post the log here. Hopefully there will be more info in the enhanced log about the error.
