### ISSUE TITLE
No documentation whatsoever on ca-certificates-mono

### ISSUE THREAD

**Issue by shenanigans12** [Jackett/Jackett#1179]
The instructions for OS X say to install ca-certificates-mono, but there are no instructions on where to find that package or how to install it.  I've been googling for an hour and theres no information here, on the Mono site, or anywhere else. Please advise!

**Comment by kaso17** [comment]
Check which package provides the "cert-sync" tool, if the command is already working it should work.

**Comment by shenanigans12** [comment]
These are the steps I was able to complete:

- [√] Install Mono 4 or better (version 4.8 is recommended)

- [√] Follow the instructions on the mono website and install the mono-devel (the instructions simply say to install Xamarin, so I did that)

- [ ] Follow the instructions on the mono website and install the ca-certificates-mono packages. (the only reference to this package is on the linux page, and none of the commands can be run in os x terminal.  It appears that there is no "browser-accessible" package, but only one buried somewhere in the repository.  Since I can't add the repository to my source list, or use apt-get or any of the other commands on the page, these instructions don't work for me :(

- [ ] Install libcurl (as far as I can tell, OS X ships with this)

- [√] Download and extract the latest Jackett.Binaries.Mono.tar.gz release from the releases page and run Jackett using mono with the command mono --debug JackettConsole.exe.

**Comment by adamwinn** [comment]
I had this same issue too and @kaso17 helped me figure it out.

Here's how I think I remember solving it:

Download this pem file:  
```https://curl.haxx.se/ca/cacert.pem```

Then run:  
```sudo cert-sync ~/Downloads/cacert.pem```

The output should contain a "Importing into BTLS system store:" line (I think I ran it a couple of times)

**Comment by ZacCoffman** [comment]
You're a life saver @adamwinn!

**Comment by shenanigans12** [comment]
Thank you @adamwinn, that was a hell of a journey.  To any other poor laymen that comes along and gets completely lost like I did, there are a few more steps to do before you can successfully add these certificates:

If you try to do this in OS X 10.11 or newer, you'll likely receive the error, "Warning: Could not import C=US, O=Amazon, CN=Amazon Root CA 4 System.UnauthorizedAccessException: Access to the path "/usr/share/.mono" is denied."

As of OS X 10.11, El Capitan, Apple has introduced System Integrity Protection, also known as "rootless", a security protocol to protect against malware.  This feature, however, also prevents you from changing folder permissions to things like /usr/share.

In order to fix this, you need to boot into the recovery partition (cmd-r at startup), launch terminal, and run csrutil disable.  Then restart.

I highly recommend adding all of the info from this thread to the OS X install instructions.

**Comment by RoloSoze** [comment]
@adamwinn @shenanigans12 Thank you guys for resolving this issue! I think we'll be referencing this quite often as many users will like raise similar issues.

**Comment by DamnedFacts** [comment]
Replace:
`sudo cert-sync ~/Downloads/cacert.pem`

with:
`cert-sync --user ~/Downloads/cacert.pem`

and you avoid any issues with SIP.

**Comment by olsonpm** [comment]
@shenanigans12 - @DamnedFacts solution is the correct one.  You shouldn't be modifying SIP as cert-sync shouldn't even be installing into that directory.  Per some blog post, files that were manually placed there as a result of disabling SIP will be deleted during the next major OS update.  Granted, that doesn't happen very often, but `--user` will not give you issues moving forward.
