### ISSUE TITLE
[blutopia] Access to the path 'C:\ProgramData\Jackett\Indexers\blutopia.json.bak' is denied. (Config)

### ISSUE THREAD

**Issue by finikium** [Jackett/Jackett#11790]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Please provide as much info as you can manage by editing the first post and answering the questions. You have given us nothing to work with.
All I can surmise is that you are on a windows platform, and most likely your anti-malware product is blocking access.

**Comment by finikium** [comment]
It's ok now friend i downloaded the last Jackett release and it works perfect!
Many thanks.

Greetings from Athens

    Στις Κυριακή, 23 Μαΐου 2021, 10:38:00 μ.μ. EEST, ο χρήστης garfield69 ***@***.***> έγραψε:  
 
 


Please provide as much info as you can manage by editing the first post and answering the questions. You have given us nothing to work with.
All I can surmise is that you are on a windows platform, and most likely your anti-malware product is blocking access.
