### ISSUE TITLE
[zooqle] Exception (zooqle): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /SRC/mono-6.8.0.105/external/boringssl/ssl/handshake_client.c:1132: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by Cheezmania** [Jackett/Jackett#11798]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#an-error-occurred-while-sending-the-request-error-trustfailure-ssl-errorssl-routinesopenssl_internalcertificate_verify_failed

If you're using a Synology NAS, you can try downgrading mono using the following method - https://github.com/SynoCommunity/spksrc/issues/3946#issuecomment-612562594 (see bottom half of the comment)

The naming scheme has seemingly changed slightly on SynoCommunity, but the one mentioned `5.8.0.108-11 [6.1 rtd1296]` seems to be https://packages.synocommunity.com/mono/11/mono.v11.f15047[rtd1296-armada37xx-aarch64].spk

You can try some of the relevant, more recent versions there as well - https://packages.synocommunity.com/mono
