### ISSUE TITLE
[iptorrents] Your cookie did not work: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings. (Config)

### ISSUE THREAD

**Issue by trugenx** [Jackett/Jackett#11801]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: windows server 2019

**.Net Runtime**: .NET Framework 4.6.2

**.Net Version**: .NET Framework 4.6.2

**Jackett Version**: 0.18.145.0

**Last Working Jackett Version**: 0.18.145.0

**Are you using a proxy or VPN?** [yes/no] yes

### Description

cannot add cookies needed to jackett as needed. looks like they have implemented something to ensure only browsers can login

### Logged Error Messages

only thing i can find:
Your cookie did not work: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.

(I used to have IPTorrents setup a couple of years ago, so i know it worked at one point. the cookies look completely different now)

**Comment by ilike2burnthing** [comment]
Check the troubleshooting steps, in particular the Notes section - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work

@40Cakes / @TheFlath / @Codebreaker101 any of you having the same issue.

**Comment by 40Cakes** [comment]
My IPT indexer is working fine right now.

I had this same issue a few weeks back except in a container and found that disabling IPv6 on Jackett resolved the issue - does your network or VPN provide IPv6?
