### ISSUE TITLE
BitHUmen and Carpathians are ratioless trackers but Jackett doesnt see them as FreeLeech

### ISSUE THREAD

**Issue by batuhankrmn** [Jackett/Jackett#11818]
### Environment

**OS**: win 10

**Jackett Version**: Jackett Version v0.18.169

**Are you using a proxy or VPN?** [yes/no] NO

### Description

BitHUmen and Carpathians are ratioless trackers, So Jackett should see results from these trackers as FreeLeech tagged but It doesnt. I noticed that when I check Radarr, I prioritized freeleech releases at Radarr, since Jackett does not tagged BitHUmen and Carpathians results with FreeLeech flag, radarr wont grab releases from these two.

**Comment by garfield69** [comment]
yes, those indexer currently default to DLVF=1
I will update the indexers to default to DLVF=0 instead.

**Comment by ilike2burnthing** [comment]
[v0.18.171](https://github.com/Jackett/Jackett/releases/tag/v0.18.171)
