### ISSUE TITLE
[newpct/maxitorrent] download torrent fail

### ISSUE THREAD

**Issue by diegargon** [Jackett/Jackett#11817]
Seems maxitorrent change the behavior to download the torrent link (check on page) you must do click "Descargar" and then "Descargar Torrent", this break the indexer on Jacket.

They not seems change this on other mirrors pctmix1. (banned anyway check through VPN)

**Comment by garfield69** [comment]
If maxitorrent  is the only site that behaves differently from the other newpct sites, then will will have to remove the maxitorrent site link from the list in the next Jackett update.. Thanks for the info.

**Comment by ilike2burnthing** [comment]
[v0.18.171](https://github.com/Jackett/Jackett/releases/tag/v0.18.171)

**Comment by DAVIZINH0** [comment]
witch is the url for the newpct indexer? maxitorrent not works and pctmix1 need vpn? :-(

**Comment by garfield69** [comment]
https://pctmix.com/

**Comment by DAVIZINH0** [comment]
> https://pctmix.com/

ARR_CONNECTOIN_RESET
with movistar :-(

thanks!

**Comment by garfield69** [comment]
only one more alternate address to try https://pctreload1.com/

**Comment by DAVIZINH0** [comment]
> https://pctreload1.com/

same problem. i think the problem is with all domains of the group and maybe only movistar?

**Comment by viseniv** [comment]
It'a not only Movistar i'm on Orange and i have the same problem. 
None of the mirrors work.

**Comment by diegargon** [comment]
the big teleco companies are blocking it 
newpct/pctereload are in his banned list you all better connect throw a vpn/proxy to deal for censorship. But this url works fine.

Maxitorrent works and its no banned in Movistar yet (probably the will ban in the future), don't known if is banned a DNS level (change it to 8.8.8.8).
But Jackett drop it maxitorrent because they change the behavior for downloading.

Perhaps they can copy the indexer, rename to maxitorrent and fix the problem, and we can select [maxitorrent] or [newpct], but they decide.

**Comment by diegargon** [comment]
i create a request for https://unblockit.onl
https://github.com/unblocked-pw/unblocked-pw.github.io/issues/23

if they add we can use the unblockit.onl url in jackettt

**Comment by garfield69** [comment]
> i create a request for https://unblockit.onl
> [unblocked-pw/unblocked-pw.github.io#23](https://github.com/unblocked-pw/unblocked-pw.github.io/issues/23)
> 
> if they add we can use the unblockit.onl url in jackettt

absolutely. once you confirm that the unblockit have implemented it, let us know the address and we will add it to the the newpct indexer's alternate sites table.

**Comment by viseniv** [comment]
I can confirm if you use https://pctmix1.unblockit.li/ it works perfectly in web explorers and jackett.

**Comment by ilike2burnthing** [comment]
added with https://github.com/Jackett/Jackett/commit/d952679313668cac81bf1928391b63a935d09310

**Comment by diegargon** [comment]
they update the mirrors, and now the download problem of the maxitorrent site its in the mirrors. open or new?

**Comment by garfield69** [comment]
no, we can apply the same code to the rest, as long as you test each alternate site to confirm ALL are using the  maxi download method.
I do NOT want to have to go back later and exceptions for some mirrors.
Please reply with a go or no-go. Thanks.

**Comment by garfield69** [comment]
okely dokely

**Comment by garfield69** [comment]
v0.18.273
