### ISSUE TITLE
[yggtorrent] The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [Jackett/Jackett#11816]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: DietPi

**.Net Runtime**: Not applicable

**.Net Version**: Not applicable

**Jackett Version**: 0.18.155

**Last Working Jackett Version**: (never worked before)

**Are you using a proxy or VPN?** No

### Description

Install Jackett directly on the Pi
Install Docker + Portainer
Deploy the FlareSolverr image on Docker
Run Flaresolverr
Connect Jackett to flaresolverr
Try to add yggtorrent as indexer

FlareSolverr says the following on localhost:8191:
{"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1622107173615,"endTimestamp":1622107173615,"version":"v1.2.5"}

So I assumed it was correctly set up. Maybe there is further configuration to do, if yes I didn't find any tutorial.

### Logged Error Messages

An error occurred while updating this indexer
The cookies provided by FlareSolverr are not valid

Here is my logs:

[log.txt](https://github.com/Jackett/Jackett/files/6552809/log.txt)

### Screenshots

![image](https://user-images.githubusercontent.com/64923542/119802142-9793e000-bede-11eb-99ce-255471c89d66.png)

**Comment by ilike2burnthing** [comment]
Does your ISP support IPv6? If so, it could be that Jackett is using IPv4 and FlareSolverr IPv6, or vice versa, so you'd need to disable IPv6, either for the containers or for your device.

There have been a few similar issues for different indexers, and there's an open issue for ygg on FlareSolverr's repo - https://github.com/FlareSolverr/FlareSolverr/issues/127

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> Does your ISP support IPv6? If so, it could be that Jackett is using IPv4 and FlareSolverr IPv6, or vice versa, so you'd need to disable IPv6, either for the containers or for your device.
> 
> There have been a few similar issues for different indexers, and there's an open issue for ygg on FlareSolverr's repo - [FlareSolverr/FlareSolverr#127](https://github.com/FlareSolverr/FlareSolverr/issues/127)

Thanks for your answer.
Yes, my ISP supports ipv6. But I don't know if jackett or flaresolverr are using it. How can I know that ? If it's not different, how do I change it ?

Thanks in advance for your answer.

**Comment by ilike2burnthing** [comment]
For Docker, see the last note - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work

**Comment by LeVraiRoiDHyrule** [comment]
Thanks. I just tried, and I have no html request in my network tab when reloading the page:
![image](https://user-images.githubusercontent.com/64923542/119852025-39cbbc00-bf0f-11eb-886b-ca4eb05ad596.png)

Do you know what could cause this ?

**Comment by LeVraiRoiDHyrule** [comment]
Thanks. I just tried and got the cookie from ygg, but at step 10 it says "In the Jackett indexer config cookie box Delete anything already there".

There is no cookie box for yggtorrent settings in Jackett.

**Comment by ilike2burnthing** [comment]
Sorry, by 'last note' I meant under the `Notes` section, i.e.:
> Some web sites generate cookies that are IP locked to the users current IP address. If you are using a VPN service then make sure that the VPN is allocating the same server for your Browser as it does for Jackett, otherwise your cookie will not work. If you are using a Docker container you may need to disable IPv6 in your run command with --sysctl net.ipv6.conf.all.disable_ipv6=1, or in your compose file with:
> ```
>    sysctls:
>      net.ipv6.conf.all.disable_ipv6: 1
> ```

**Comment by LeVraiRoiDHyrule** [comment]
Thanks. I would like to try this, but when I try to execute this command, I get an error "read only file system":
![image](https://user-images.githubusercontent.com/64923542/119910550-ab2f5d00-bf57-11eb-8f88-80ef73300ac0.png)

I'm a begginer in Docker (Installed it today, along with Portainer, just for Flaresolverr on my pi as it's the only way to install it currently). I searched on that error but didn't find how to pass it. Do you know how I can change the file system to read write ?

**Comment by ilike2burnthing** [comment]
It's a setting you need to add when creating the container, you can't send the command to FlareSolverr. Either change your compose file or run command.

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> It's a setting you need to add when creating the container, you can't send the command to FlareSolverr. Either change your compose file or run command.

Hi,

Sorry I know I am answering a bit late but I hadn't the time to take care of this earlier.
I tried recreating the container, with the ipv6 setting. It looks like it worked correctly, as the setting appears in Portainer:

![image](https://user-images.githubusercontent.com/64923542/120920861-3d0a3900-c6c1-11eb-94b0-1ab86d5ae9f2.png)

Flaresolverr seems to be running correctly too:
![image](https://user-images.githubusercontent.com/64923542/120920872-4abfbe80-c6c1-11eb-9821-8401cf4ea256.png)

But I'm still getting the same error in Jackett when trying to add yggtorrent:
![image](https://user-images.githubusercontent.com/64923542/120920922-8bb7d300-c6c1-11eb-8d83-3029026639ea.png)

Is there something else I could try ?
Thanks in advance for any answer or help

**Comment by ilike2burnthing** [comment]
Did you add that to both Jackett and FlareSolverr?

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> Did you add that to both Jackett and FlareSolverr?

I did that to flaresolverr as it is in a docker container, by my Jackett install is not. I installed it directly on the Pi using dietpi-software (that I use for most of my other softwares). Is there a way to disable Jackett's ipv6 on my current install, or do I need to install it in Docker too ? (I would prefer the 1st option)

**Comment by ilike2burnthing** [comment]
Disabling IPv6 for your Pi as a whole (no idea how, so I'll leave the googling for that to you).

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> Disabling IPv6 for your Pi as a whole (no idea how, so I'll leave the googling for that to you).

Done ! It's very easy to do with dietpi. AND IT WORKS !!! I successfully added yggtorrent to my Jackett.

But I don't like having to disable ipv6 on my whole pi. Is there a way to tweak Jackett so that just jackett doesn't use ipv6 ?
Also, is there no way to use flaresolverr with ipv6 ?

**Comment by ilike2burnthing** [comment]
FlareSolverr works fine with IPv6, the issue is that if FlareSolverr uses it, but Jackett uses IPv4, or vice versa, the cookies won't be valid. While you'd like to think IPv6 would be preferred, and then default back to IPv4 on failure, it just seems to be completely random. So if you knew every site you use had an IPv6 address, you could disabled IPv4 instead and everything would work exactly the same.

The only way I'm aware of to restrict specific applications from using IPv6 is through something like Docker.

**Comment by LeVraiRoiDHyrule** [comment]
Ok, I finally decided to install Jackett through Docker, using the LinuxServer image. And I applied the same ipv6 setting. And it works without having to block ipv6 on the whole pi.
But I would have a question:
Why does it work in Jackett when I input http://192.168.1.31:8191/ as the Flaresolverr URL, but not when I set http://localhost:8191/ ??

**Comment by ilike2burnthing** [comment]
As far as I'm aware any program will use whichever address IPv4 or IPv6 it gets first, this isn't unique to Jackett or FlareSolverr. The same thing happened with my torrent client.
