### ISSUE TITLE
[hdspain] Login failed: Selector

### ISSUE THREAD

**Issue by Giakin** [Jackett/Jackett#11823]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux Ubuntu 20.04

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Working on latest docker

**.Net Version**:

**Jackett Version**:0.18.169

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

I follow steps to take cookie from navigator and doesn't work

### Logged Error Messages

Login failed: Selector ".tcabecera" didn't match

**Comment by garfield69** [comment]
Selector ".tcabecera" is the last part of the cookie test.
So its Jackett's way to check that the session cookie worked, in that this selector is meant to exist only if you have been able to establish a session to the web site that is logged in to the web site.

There are two possibilities: 
1. the cookie failed to provide the correct session credentials and the web site rejected it, so the site want you to login again, hence the selector .tcabecera is not found.
2. the cookie worked, but the web site changed their index.php page and the selector .tcabecera does not exist.

Uunfortunately none of the team members have an account on this site so we cannot investigate independently.
Lets see if an enhanced log can provide more details. 
Please read and action https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket to provide a full enhanced log
Thanks.
