### ISSUE TITLE
The q parameter search in the rarbg is not the latest torrent

### ISSUE THREAD

**Issue by cnstephen** [Jackett/Jackett#11833]
The q parameter search in the rarbg is not the latest torrent，it is only the latest if the q parameter is removed. Have you guys encountered this?
![1](https://user-images.githubusercontent.com/81022834/120088469-56d8d880-c123-11eb-8639-37df38ab4a10.png)
![2](https://user-images.githubusercontent.com/81022834/120088471-58a29c00-c123-11eb-992f-d593b44db38c.png)

**Comment by ilike2burnthing** [comment]
This seems to be a difference in how results are presented between `mode=list` (which we use for keywordless searches) and `mode=search` (which we use for keyword searches) in their API.
https://github.com/Jackett/Jackett/blob/2ee6104c461552ab13c13738296e8098157f1d1b/src/Jackett.Common/Indexers/RarBG.cs#L258-L269

Looks like it was first added in [2015](https://github.com/Jackett/Jackett/commit/324bb485434fa6810bcac9c47bcae548b3a48ebb), but not sure why.

It's a one word change in the code (`list` > `search`), as `search_string` can't be empty.

@garfield69 I can't see anything in the API documentation which either explains how `list` is meant to be different, or that it must be used in certain circumstances (or that `search` shouldn't be used without `search_string`). Are you aware of anything like that? If not, you ok with that being changed?

**Comment by garfield69** [comment]
>Are you aware of anything like that? If not, you ok with that being changed?

The RarBG API does not support a `mode=search` with a search_string set to `""`, it returns `"error":"No results found","error_code":20` which is why we have to use `mode=list`.
And `mode=list` does not support sorting, returning the same code=20

**Comment by ilike2burnthing** [comment]
`mode=search` without using `search_string` works though, so it would be:
> `https://torrentapi.org/pubapi_v2.php?token=xxxxxxxxxx&format=json_extended&app_id=jackett_v0.18.181&limit=100&ranked=0&sort=last&mode=search&category=44`

**Comment by garfield69** [comment]
If that is the case then publish it ;-)

**Comment by ilike2burnthing** [comment]
Why I thought changing the format of the keywordless search would solve an issue about keyword searches, I have no idea... 🤦 too many tabs open and I got them mixed up, that's my excuse.

This seems to be an issue with the API, no matter what way I structure the parameters, what I search, or in what categories, I end up with the same results; but it doesn't look like they're ordered wrongly, rather it's only fetching results >2 days old.

**Comment by mkolassa** [comment]
How do we go about letting the people behind torrentapi about the issue?

**Comment by ilike2burnthing** [comment]
support[at]rarbg[dot]to

Might be worth tracking the issue for another day or few to see if it's a consistent 2 day buffer, or if it's stuck at the 28th.

**Comment by cnstephen** [comment]
> support[at]rarbg[dot]to
> 
> Might be worth tracking the issue for another day or few to see if it's a consistent 2 day buffer, or if it's stuck at the 28th.

![20210531235510](https://user-images.githubusercontent.com/81022834/120218570-85ae9600-c26c-11eb-9866-8a03964e021f.png)
![20210531235606](https://user-images.githubusercontent.com/81022834/120218569-85ae9600-c26c-11eb-8c7e-d9cbf9e49234.png)
![20210531235650](https://user-images.githubusercontent.com/81022834/120218572-86472c80-c26c-11eb-8365-7341915063b0.png)


Do your api's have the problem I have?

**Comment by cnstephen** [comment]
Just updated to Jackett Version v0.18.205
Still the same data as the picture

**Comment by mkolassa** [comment]
Yes, the feed is stale at this point.  As it is still stuck with Boogie as the latest result in mode=list (and mode=search is showing Cruella from 2021-05-28), I have gone ahead and emailed the address mentioned by @ilike2burnthing earlier.

**Comment by cnstephen** [comment]
> Yes, the feed is stale at this point. As it is still stuck with Boogie as the latest result in mode=list (and mode=search is showing Cruella from 2021-05-28), I have gone ahead and emailed the address mentioned by @ilike2burnthing earlier.

Now without search parameters, it is not the latest data. 24h ago

**Comment by leadwolf** [comment]
Is there a workaround for now?

**Comment by garfield69** [comment]
>Is there a workaround for now?

nope. The issue is with the RarBG torrentAPI, so there is nothing can be done from the Jackett end.
