### ISSUE TITLE
v0.7.1191197 Windows EXE Installer not working

### ISSUE THREAD

**Issue by DrSeussFreak** [Jackett/Jackett#1183]
For Windows, I grab the latest (v0.7.1191197) exe installer and it won't run, nothing happens.   Tried the previous release (v0.7.1176) at works fine.ine.

**Comment by RoloSoze** [comment]
@DrSeussFreak Once you have 0.7.1176 installed, try upgrading from within Jackett instead of running the .exe installer. Does that work?

**Comment by DrSeussFreak** [comment]
It didn't before, I had tried to get it to do so, but it seems that after manually upgrading to 1176 it triggered the update feature and it is now on 1197
