### ISSUE TITLE
[ilcorsaroblu] Login failed: No form found on https://ilcorsaroblu.online/index.php?page=login

### ISSUE THREAD

**Issue by Bazzu85** [Jackett/Jackett#11840]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10 PRO

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.18.171

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

The login doesn't work anymore.
Even modifying the site link to https://ilcorsaroblu.org/ , Jackett seems to try always the https://ilcorsaroblu.online

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
yes, the indexer will need to be updated to swap out *.online for *.org in the legacylinks section.
Will submit a fix shortly.

**Comment by garfield69** [comment]
v0.18.205

**Comment by Bazzu85** [comment]
works, thx
