### ISSUE TITLE
How is the title being generated?

### ISSUE THREAD

**Issue by elpedriyo** [Jackett/Jackett#11844]
Hello,

Just wanted to know how are the titles generated from tracker HDO.

![image](https://user-images.githubusercontent.com/3207791/120123570-dad8a200-c1af-11eb-9be5-11fbcb2bd66d.png)

It shows "MULTi/SPANiSH" but when I get into the TV show in the tracker, the names does not show equal:

![image](https://user-images.githubusercontent.com/3207791/120123590-fa6fca80-c1af-11eb-8831-054871dd33b4.png)

Kind regards

**Comment by garfield69** [comment]
Title for HDO is generated with this code
https://github.com/Jackett/Jackett/blob/5ca84bd064613f424de9abbbb02b5019c1b6bdfa/src/Jackett.Common/Definitions/hdolimpo.yml#L103-L151
The language support was added by danimart1991 with PR #10808

**Comment by elpedriyo** [comment]
Could you please make a replacement for E-AC-3 to EAC3, or just take it out, so that the title looks nicely. It seems guessit confuses E-AC-3.5.1 with episode 3 and that breaks all the entire WF :(

**Comment by elpedriyo** [comment]
I was wondering, am I able to touch the config .yml file myself , then restart jackett, and will it work?

**Comment by garfield69** [comment]
> am I able to touch the config .yml file myself , then restart jackett, and will it work?

absolutely. Its the way I test all my changes before submitting a commit :-)

**Comment by elpedriyo** [comment]
great!! Then that way I can personalize the way I want my tracker information to be translated for sonarr, radarr, etc, etc :D

**Comment by garfield69** [comment]
Do remember that whenever the Jackett updater runs, it will replace the indexer with the same *.yml name with the one from github source.
so if you are going to want to keep your changes, save your indexer under a unique name, for example  myhdo.yml and update the ID and NAME in the yml to match, so you can tell it apart from the original.

**Comment by garfield69** [comment]
v0.18.210
