### ISSUE TITLE
[rarbg] search and rss empty

### ISSUE THREAD

**Issue by Bazzu85** [Jackett/Jackett#11848]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10 PRO

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.18.205

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

tried the search function and the rss feed..both are always empty..
last working...I don't know..maybe yesterday?
any feedback?

edit1: after a while some releases are grabbed.
but zero releases from certain category like 6000 or 100004 (impossible case) even using search in jackett

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by mkolassa** [comment]
torrentapi is having issues, and is currently reporting a 521 error through Cloudflare.

**Comment by mkolassa** [comment]
torrentapi is now responding to my requests, and appears to be delivering the latest results again.

**Comment by Bazzu85** [comment]
> torrentapi is now responding to my requests, and appears to be delivering the latest results again.

I have a 423 forbidden to https://torrentapi.org/ so is not resolved..
hope they fix soon

**Comment by mkolassa** [comment]
> > torrentapi is now responding to my requests, and appears to be delivering the latest results again.
> 
> 
> 
> I have a 423 forbidden to https://torrentapi.org/ so is not resolved..
> 
> hope they fix soon

You cannot access it directly, it requires a token that you have to request first. 

Go ahead and check your Jackett feed.  You will see that it is populated with results.

**Comment by garfield69** [comment]
a 423 is usually the result of a request to the API without including the app_id= parm.

The Jackett RarBG indexder is working for me ATM.

there is nothing Jackett can do about this, the provider's server has been janky for over a year now.

**Comment by Bazzu85** [comment]
The problem I think is in jackett..
using the default rss I have many releases.
Filtering the category 6000 or 100004 -> 0 releases.
on the site there are many releases for the 2 categories
check screens: https://imgur.com/a/QnwT8RY

**Comment by garfield69** [comment]
no, it is not jackett. The RarBG API is not delivering any 3x torrents.
for instance, posting a query directly to the server to search for any titles with kiara
https://torrentapi.org/pubapi_v2.php?token=xxxxxxxx&format=json_extended&app_id=jackett_v0.18.210&limit=100&ranked=0&sort=last&mode=search&search_string=kiara
returns just two tv episodes
```
{"torrent_results":[{"title":"Catfish.The.TV.Show.S08E22.Jeanette.Kiara.and.Patrick.HDTV.x264-CRiMSON[rartv]","category":"TV Episodes","download":"magnet:?xt=urn:btih:c93e0fb5dc496ded4237f9b6cbdb9ed7efe6ccff&dn=Catfish.The.TV.Show.S08E22.Jeanette.Kiara.and.Patrick.HDTV.x264-CRiMSON%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2760&tr=udp%3A%2F%2F9.rarbg.to%3A2760","seeders":0,"leechers":0,"size":343487438,"pubdate":"2020-11-05 04:21:55 +0000","episode_info":{"imdb":"tt2498968","tvrage":"32713","tvdb":"262754","themoviedb":"46910","airdate":"2020-11-04","epnum":"22","seasonnum":"8","title":"Jeanette, Kiara & Patrick"},"ranked":1,"info_page":"https:\/\/torrentapi.org\/redirect_to_info.php?token=xxxxxxxx&p=2_3_4_1_0_0_0__c93e0fb5dc"},{"title":"Catfish.The.TV.Show.S08E22.Jeanette.Kiara.and.Patrick.720p.HDTV.x264-CRiMSON[rartv]","category":"TV HD Episodes","download":"magnet:?xt=urn:btih:d19a2f5b8e66b03de8df53ca97f42d88f2625167&dn=Catfish.The.TV.Show.S08E22.Jeanette.Kiara.and.Patrick.720p.HDTV.x264-CRiMSON%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2780&tr=udp%3A%2F%2F9.rarbg.to%3A2780","seeders":0,"leechers":0,"size":1036013524,"pubdate":"2020-11-05 04:18:49 +0000","episode_info":{"imdb":"tt2498968","tvrage":"32713","tvdb":"262754","themoviedb":"46910","airdate":"2020-11-04","epnum":"22","seasonnum":"8","title":"Jeanette, Kiara & Patrick"},"ranked":1,"info_page":"https:\/\/torrentapi.org\/redirect_to_info.php?token=xxxxxxxx&p=2_3_4_0_9_9_5__d19a2f5b8e"}]}
```
whereas the web site https://rarbg.to/torrents.php?search=kiara returns many 3x torrents

**Comment by garfield69** [comment]
And in addition, the moment I add the categories to my direct API query and include category 4 (the 3x category) I get no results, but if I remove cat4 and leave the other cats I get the two tv shows again.
https://torrentapi.org/pubapi_v2.php?token=xxxxxxxx&format=json_extended&app_id=jackett_v0.18.210&limit=100&ranked=0&sort=last&mode=search&search_string=kiara&category=14;17;18;23;25;27;28;32;33;35;40;41;42;44;45;46;47;48;49;50;51;52;53;54
returns two tv shows
https://torrentapi.org/pubapi_v2.php?token=xxxxxxx&format=json_extended&app_id=jackett_v0.18.210&limit=100&ranked=0&sort=last&mode=search&search_string=kiara&category=4;14;17;18;23;25;27;28;32;33;35;40;41;42;44;45;46;47;48;49;50;51;52;53;54
returns error=20 (no results found).

**Comment by garfield69** [comment]
I'm going to remove the 3x cats from the indexer as this is clearly not supported by the API.

**Comment by Bazzu85** [comment]
> I'm going to remove the 3x cats from the indexer as this is clearly not supported by the API.

maybe is a temporary problem?
or is definitive that rarbg dropped this support?

**Comment by Bazzu85** [comment]
@garfield69 are you sure to remove the categories from the indexers?
accessing to their rss feed with category 4
https://rarbg.to/rssdd.php?categories=4
works..
is so a torrentapi problem? or what?

**Comment by garfield69** [comment]
>is so a torrentapi problem?

YES

**Comment by Bazzu85** [comment]
> > is so a torrentapi problem?
> 
> YES

so I don't undestand why you want to remove the categories..
why are you saying that torrentapi won't resolve this issue? can you provide a link or something?

**Comment by garfield69** [comment]
My testing https://github.com/Jackett/Jackett/issues/11848#issuecomment-851915516 shows that https://torrentapi.org breaks when using cat=4.
If the site ever fixes this issue we can always add it back.
In the mean time, to prevent regular non-3x searching failing, by dropping cat=4 the API returns results.
Not big deal.

**Comment by Bazzu85** [comment]
> My testing [#11848 (comment)](https://github.com/Jackett/Jackett/issues/11848#issuecomment-851915516) shows that https://torrentapi.org breaks when using cat=4.
> If the site ever fixes this issue we can always add it back.
> In the mean time, to prevent regular non-3x searching failing, by dropping cat=4 the API returns results.
> Not big deal.

but if you test using only the categories, without the search string..it works
https://torrentapi.org/pubapi_v2.php?token=xxxxxxxxxx&format=json_extended&app_id=jackett_v0.18.210&limit=100&ranked=0&sort=last&mode=search&category=4;14;17;18;23;25;27;28;32;33;35;40;41;42;44;45;46;47;48;49;50;51;52;53;54

no release from category 4 are grabbed but I think the question is deeper that "doesn't work"..

**Comment by garfield69** [comment]
The point is that the problems are all on the torrentAPI side of the fence and there is nothing that can be done in Jackett about it.
We are already bodging to finagle the API to get results. For instance, due to #4146 we have to add all the categories to searches.
But right now, torrentapi does not deliver any 3x torrents when cat=4 is used.
So I go for the solution that currently provides the most reliable results.

And I have spent enough time on this topic. If anyone else has a better solution raise a PR.
