### ISSUE TITLE
[bit-titan] Exception (bit-titan): Login failed: No form found on https://bit-titan.net/login.php using form selector form[action$=

### ISSUE THREAD

**Issue by Ticardy** [Jackett/Jackett#11849]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:Unraid / linuxserver Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.18.145

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?** [yes/no] yes

### Description

Trying to add this Indexer. Also captcha is no longer shown in Jackett. Same as https://github.com/Jackett/Jackett/issues/11787#issue-898953644

Seems they are working something on this site that breaks login 

### Logged Error Messages

Jackett.Common.IndexerException: Exception (bit-titan): Login failed: No form found on https://bit-titan.net/login.php using form selector form[action$="login.php"]
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://bit-titan.net/login.php using form selector form[action$="login.php"]

**Comment by wieluk** [comment]
I am getting the same error now ... there used to be a captcha but it is gone now.

**Comment by garfield69** [comment]
@weiuk the indexer is working for me, and I still see a captcha image when I edit the config.
IF there is no capcha image when you edit your config make sure the capcha text is empty before saving.
If you are still getting this issue then please provide an full **enhanced** log so I can see what the site is sending you during Jackett's login attempt.
Read and action https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by wieluk** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/46672054/133139880-e73a5850-5a55-478f-bf21-f509644018d0.png)

for me it looks like this since I updated to v0.18.746

**Comment by wieluk** [comment]
here is a log: 
[log.txt](https://github.com/Jackett/Jackett/files/7156767/log.txt)

**Comment by wieluk** [comment]
oh i see the problem in the log ... Ip is banned but I can login with the same IP from my computer
