### ISSUE TITLE
[yggtorrent] Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Connection refused (172.17.0.231:8191) ---> System.Net.Sockets.SocketException (111): Connection refused   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)   --- 

### ISSUE THREAD

**Issue by protectxme** [Jackett/Jackett#11846]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:Debian

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.18.196

**Last Working Jackett Version**: v0.18.196

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken) at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancel

**Comment by garfield69** [comment]
Start by upgrading your flaresolverr to 1.2.6 and rebooting your machine to reset your ports.

**Comment by cnstephen** [comment]
> Start by upgrading your flaresolverr to 1.2.6 and rebooting your machine to reset your ports.

hi.The question I asked earlier. About rarbg search is not the latest data, it does not exist anymore. Is it solved? please reply when you have time, thanks!

**Comment by garfield69** [comment]
>The question I asked earlier. About rarbg search is not the latest data, it does not exist anymore.

it exist, nothing on GitHub is ever lost :-D
The ticket is closed. You are probably looking on the open tickets page.
Either switch your view to closed tickets, or just click on this link #11844

**Comment by Mihank1** [comment]
Hi Same error here with flaresolverr 1.2.6

**Comment by garfield69** [comment]
the issue is on your platform someplace.
can you access from your browser on the same machine that is running Jackett this address
http://172.17.0.231:8191
and do you get back something like
```
{"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1622458714176,"endTimestamp":1622458714176,"version":"v1.2.6"}
```
?

**Comment by Mihank1** [comment]
> the issue is on your platform someplace.
> can you access from your browser on the same machine that is running Jackett this address
> http://172.17.0.231:8191
> and do you get back something like
> 
> ```
> {"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1622458714176,"endTimestamp":1622458714176,"version":"v1.2.6"}
> ```
> 
> ?

{"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1622462986722,"endTimestamp":1622462986722,"version":"v1.2.6"}

Maybe it's on my Sonar config

**Comment by garfield69** [comment]
>Maybe it's on my Sonar config

unlikely. Sonarr sends its request to Jackett and Jackett sends its traffic to the flaresolverr server.

So your Jackett is not able to talk to the flaresolverr server.
Are you running a Docker images or is Jackett and Flaresolverr running native?

**Comment by garfield69** [comment]
@ilike2burnthing  another linux platform.  any thoughts?

**Comment by ilike2burnthing** [comment]
172.17.0.0/16 is the subnet for Docker containers.

Try changing your network mode for the containers (e.g. host > bridge). If that doesn't work, try using the local IP of device instead.

**Comment by louia** [comment]
On flaresolverr side I've got this log : 2021-06-01T11:58:25+00:00 INFO REQ-29 Cloudflare Error: Captcha detected but no automatic solver is configured.

**Comment by ilike2burnthing** [comment]
None of the captcha solvers currently work, so adding one won't help anyway. You can try accessing the site in browser, complete the captcha challenge and then retry in Jackett, or switch to yggcookie.

**Comment by Jamyz** [comment]
I have the same issue!
