### ISSUE TITLE
[New Tracker REQ] Zooqle.com

### ISSUE THREAD

**Issue by crafty35a** [Jackett/Jackett#1185]
Could you please add support for Zooqle (API info here: https://zooqle.com/help/api.html)

Thanks!

**Comment by RoloSoze** [comment]
@JigSawFr I don't think an invite is needed for this one. I'm able to download torrents without registering. There is an option to register, without an invite, to receive RSS feeds and set up subscriptions.

**Comment by JigSawFr** [comment]
@RoloSoze Thank you, it's not a private tracker but a beautiful / clear torrent website (with api !) which seems to scrape many other public trackers.

**Comment by RoloSoze** [comment]
@JigSawFr Agreed. Allowing Jackett to re-support Public & Semi-Private trackers was a good decision. I believe it'll work best when pagination #975 is supported, since public trackers typically display more results than private trackers, so returning results from the 1st page only might be not sufficient. 

This might be especially true for this one (Zooqle) & Torrentz2 #1040 since both return many results from multiple public trackers.

**Comment by zero77** [comment]
thanks

**Comment by garfield69** [comment]
https://zooqle.com/ returning cloudflare 502 bad gateway.

**Comment by garfield69** [comment]
back online

**Comment by garfield69** [comment]
offline again, returning cloudflare Error 522 Connection timed out

**Comment by garfield69** [comment]
back online

**Comment by ilike2burnthing** [comment]
https://zooqle.com/ - Error 522 - Connection timed out

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
> https://zooqle.com/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://zooqle.com/ - Error 524 - A timeout occurred (intermittent issue)

**Comment by zero77** [comment]
It works for me:

![image](https://user-images.githubusercontent.com/16563034/95601618-9c894980-0a4b-11eb-9bab-a6706c57c71d.png)

**Comment by ilike2burnthing** [comment]
short lived, back up

**Comment by garfield69** [comment]
https://zooqle.com/ returning:
This page isn’t working zooqle.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by garfield69** [comment]
interestingly, `https://zooqle.com/search?q=*` does return a results page, even if the latest dates are all set to `yesterday`, but clinking on the details for any rows returns Error 404

**Comment by garfield69** [comment]
operational.

**Comment by garfield69** [comment]
Error 524 A timeout occurred from https://zooqle.com/

**Comment by garfield69** [comment]
v0.20.1062
