### ISSUE TITLE
[danishbytes] Exception (danishbytes): Login failed: No form found on https://danishbytes.org/login using form selector form[action$=

### ISSUE THREAD

**Issue by mplys3** [Jackett/Jackett#11857]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Jackett Docker Image

**.Net Runtime**: 

**.Net Version**:

**Jackett Version**:v0.18.225

**Last Working Jackett Version**: :/

**Are you using a proxy or VPN?** No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

Stopped Working today, when i updated jackett to newest version.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![image](https://user-images.githubusercontent.com/24764206/120548608-d4863800-c3f2-11eb-8a87-c7a6dae6fd74.png)

**Comment by garfield69** [comment]
The site has upgraded their engine, so we will need to update our indexer to match.

**Comment by garfield69** [comment]
The site has stopped using a standard plain HTML for results, and switched to using a dynamically generated result page which uses JS to process a JSON string of results.
The indexer will need to be rewritten in C# as the current yml processor only processes HTML.

**Comment by skafte1990** [comment]
When do you think its up again ?

**Comment by piratkongen** [comment]
We can also make an API to use specifically with jackett. Which would be the fastest?

**Comment by garfield69** [comment]
The limiting factor ATM is the lack of C# dev volunteers to contribute a PR.
From a performance point of view I believe most sites prefer we use an API, as it is less impactful on their site's services, but JSON processing is also popular, and still a better performance option as compared to the resources used by a typical Jackett HTML scraping indexer.

**Comment by seeyabye** [comment]
@piratkongen if you can build an API, it would ease the implementation and support on Jackett's end. I encourage this approach rather than a login-based approach. It would also increase the chances for a C# implementation to be implemented.

**Comment by piratkongen** [comment]
There is actually already an API available. But it depends on your requirements. Anything else needs to be implemented?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by seeyabye** [comment]
I currently do not have a danishbytes account, is there any chance you can send me an invitation? My email is seeyabye91 [at] gmail.com.

If you can also provide me the necessary documentation for the API, it would be helpful. I can write a C# tracker for this site.

**Comment by piratkongen** [comment]
The API /api/torrents/filter already contains category and resolution search.
By sending input array containing the ids of categories or resolutions.

categories
resolutions

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by CandiMiiS** [comment]
Any ETA / whats missing?

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/pull/11929 has been 'working' for the last 10 days, but we are waiting on @piratkongen to reply as there needs to updates on the site's API side to make it usable.

**Comment by piratkongen** [comment]
@ilike2burnthing
Sry for late reply, as I'm on vacation.

But what do you need exactly?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ilike2burnthing** [comment]
Oh nice, enjoy.

When you're back have a look at https://github.com/Jackett/Jackett/pull/11929.

The sorting issue has been resolved in https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/1803, you just need to update things on you end.

The only other issue is that results are limited to 15 with filters or 25 without, ideally we want 100 results, or as close to it as possible.

**Comment by piratkongen** [comment]
Sorting by latest has now been introduced, and the limit has been increased to 100.

**Comment by piratkongen** [comment]
I have also now released a better endpoint to filter.
**/api/torrents/v2/filter**

It uses the same functions and logic as the official website browser version, which has better performance than the old logic.
All sorting and filters apply the same way, as they're streamlined.

Basically **/api/torrents/v2/filter** and **/torrents/filter** returns the exact same data, only difference is one confirms authentication by API key (by using parameter **api_token**) and the other by Basic Login Auth.

I am hoping that you will update the Cs code to use the version 2 instead.

**Comment by ilike2burnthing** [comment]
@seeyabye

**Comment by garfield69** [comment]
v0.18.394

**Comment by garfield69** [comment]
Now that the Jackett Cardigann processor is capable of handling JSON API, and given that DanisBytes is using a customised version of Unit3d API 5.3.0 which we already support, I'm going to convert this C# back to yaml.
Yaml support is more direct and available, while C# devs are irregularly available these days.
See #13010  to track progress.
