### ISSUE TITLE
[iptorrents] Exception (iptorrents): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by invisiblelightx1** [Jackett/Jackett#11853]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by majorpaynedof** [comment]
I have the same issue using a docker, What I have found on other places is you have to install flaresolver cause iptorrent uses clodflare to protect against ddos.

A Jackett indexer attempted to access a web site that is protected by Cloudflare's DDoS protection.
This error can occur when either:
a) You have not installed and configured FlareSolverr
or
b) you have set up Jackett to use FlareSolverr, but the FlareSolverr server is not running, or has not been configured yet, or has been incorrectly configured.

Use your Jackett Dashboard to edit that indexer's config. See if there are alternate site links available, and try them out. If all the alternates are using Cloudflare then either:
a) Wait for the site to drop their Cloudflare protection,
or
b) Install and configure FlareSolverr.

If you have FlareSolverr installed and are receiving this message, check that the Jackett Dashboard FlareSolverr API URL is correctly set, e.g. http://127.0.0.1:8191
To test, access the FlareSolverr API URL in a browser, and you should see something similar to:

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
