### ISSUE TITLE
[1337x] Exception (1337x):  Received an unexpected EOF or 0 bytes from the transport stream.: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by lyynx88** [Jackett/Jackett#11866]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10 pro

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:
.NET SDK (reflecting any global.json):
 Version:   5.0.300

**Jackett Version**: **Version v0.18.231**

**Last Working Jackett Version**: Unknown

**Are you using a proxy or VPN?** No

### Description

Unable to add/test any tracker. 

### Logged Error Messages
Exception (1337x): Received an unexpected EOF or 0 bytes from the transport stream.: The SSL connection could not be established, see inner exception.
![image](https://user-images.githubusercontent.com/85384925/120882431-88efac00-c5f5-11eb-817b-9b21855c8e55.png)

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
If you cannot add ANY indexers then something is clearly wrong at your end, whether that be ISP blocking, a firewall block or an Anti-Malware app that is preventing connections.
In any case this is not a Jackett issue but a network problem.
Have a read of https://github.com/Jackett/Jackett/wiki/TroubleShooting#a-connection-attempt-failed and see of any of the suggestions there help you figure out what may be going on.
