### ISSUE TITLE
[animeworld.cx] switched to UNIT3D

### ISSUE THREAD

**Issue by FallenLeave91** [Jackett/Jackett#11862]
Hi guys,

https://animeworld.cx/ switched to UNIT3D, wich breaks the integration.

**Comment by garfield69** [comment]
Yup, and the indexer was updated 2 days ago. So upgrade your Jackett. Latest version is currently v0.18.231
If your indexer is not working, remember that they did not carry over the old accounts, so you will need to update your indexer credentials by editing the indexer config.
And if you still have problems then provide a full enhanced log and we will re-open this ticket and try to help you figure out what is going on.
