### ISSUE TITLE
[eztv] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#11861]
https://eztv.yt/
https://eztv.wf/
https://eztv.tf/
https://eztv.yt/
all returning Error 522 Connection timed out

https://eztv.nocensor.space/ returning Error 504 Gateway time-out

However these proxies are still working
https://eztv.unblockninja.com/
https://eztv.unblockit.onl/

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://eztv.re/ and mirrors - Error 502 - Bad Gateway

**Comment by garfield69** [comment]
https://eztv.re/ and all proxies: cloudflare Bad gateway Error code 502

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/11861#issuecomment-1212989569

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://eztv.re/ Bad gateway Error code 502
https://eztv.wf/ Bad gateway Error code 502
https://eztv.tf/ Bad gateway Error code 502
https://eztv.yt/ Bad gateway Error code 502
https://eztv1.xyz/ online
https://eztv.unblockninja.com/  online
https://eztv.mrunblock.bond/ online
https://eztv.nocensor.cloud/ online
https://eztv.unblockit.foo/ online

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://eztv.re/ DNS_PROBE_FINISHED_NXDOMAIN (DNS Lookup Error)
https://eztv.wf/ https://eztv.tf/ https://eztv.yt/ https://eztv1.xyz/ https://eztv.unblockninja.com/  https://eztv.unblockit.foo/ ok
https://eztv.mrunblock.bond/  https://eztv.nocensor.cloud/ Could not resolve host: eztv.re

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/11861#issuecomment-1212989569

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/11861#issuecomment-1212989569

**Comment by ilike2burnthing** [comment]
back up
