### ISSUE TITLE
[yggtorrent] Banned user-agent ?

### ISSUE THREAD

**Issue by yaborije2** [Jackett/Jackett#11864]
### Environment

**OS**: Ubuntu 20.04

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Not relevant

**.Net Version**: Not relevant

**Jackett Version**: 0.18.231

**Are you using a proxy or VPN?** [yes/no] No

### Description

While trying to setup FlareSolverr with Jackett for yggtorrent, I figured the hardcoded user-agent passed to FlareSolverr might have been banned by ygg.

I tried to use this user-agent in chrome devtools, I landed on the CloudFlare page, resolved the captcha, and have been redirected once again to the CloudFlare captcha page. Seems like there is a loop of some sort.
When I switch back to other user agents, it seems to work fine.

This won't resolve the captcha issue, but it's a start.

**Comment by ilike2burnthing** [comment]
Both yggtorrent and yggcookie are working fine here, so definitely not a UA issue.
