### ISSUE TITLE
support for proaudiotorrents.org ?

### ISSUE THREAD

**Issue by kobe2458** [Jackett/Jackett#11876]
Hello, I really like jackett so far. But can there be support added for proaudiotorrents.org? Thank you!

**Comment by garfield69** [comment]
We added this indexer 2 years ago!

**Comment by kobe2458** [comment]
really? I tried to search it. I may have typed it wrong.

**Comment by kobe2458** [comment]
weird, typed the exact name didnt pop up. but when scrolling down it does. Thanks man! my apologies

**Comment by garfield69** [comment]
no worries.
