### ISSUE TITLE
[lostfilm] SSL cert expired for lostfilm.run

### ISSUE THREAD

**Issue by kekal** [Jackett/Jackett#11879]
`
Exception (lostfilm): certificate validation failed: [Subject] CN=*.lostfilm.run [Issuer] CN=RapidSSL RSA CA 2018, OU=www.digicert.com, O=DigiCert Inc, C=US [Serial Number] 01406818B1CFDE89F65111CF631D21DF [Not Before] 6/5/2020 12:00:00 AM [Not After] 6/6/2021 12:00:00 PM [Thumbprint] 25234600906DF82792DE9F4AA75A5AED2F226577 : The SSL connection could not be established, see inner exception.
`

Actual cert through the browser:
`
CN = Cloudflare Inc ECC CA-3
O = Cloudflare, Inc.
C = US
`

Jackett Version v0.18.234

**Comment by kekal** [comment]
Tried rerun container with `RUN_OPTS="-IgnoreSSLErrors true"`
Got:
```
06-06 22:04:22 Info Starting Jackett v0.18.169
06-06 22:04:22 Error ReserveUrls and service arguments only apply to Windows, please remove them from your start arguments
```

**Comment by garfield69** [comment]
If you are getting an invalid certificate on this site, this can only mean that the lostfilm server provider is blocking your access.
If you use your browser to access www.lostfilm.run you will see that you are being redirected to http://blocked.mts.ru/?host=www.lostfilm.run who are using an invalid certificate.
your page will look something like this
![image](https://user-images.githubusercontent.com/6933240/120942248-c8480500-c77b-11eb-8008-8c31ca5cb3ee.png)

there is no point trying to circumvent the certificate since you are not going to be able to access the lostfilm web site anyway.

To get around this problem you will need to use a VPN or proxy that can assign you a different IP address, preferably one not it the blocked list. I find Canadian IPs work, but I'm sure there are others.

**Comment by garfield69** [comment]
Oops, I see that lostfilm does indeed have an invalid certificate too.
I will add an exception for this.

**Comment by kekal** [comment]
![image](https://user-images.githubusercontent.com/13663141/120942389-5054ed00-c731-11eb-9401-1650e7cf4c88.png)

**Comment by garfield69** [comment]
The next release of Jackett due out on about 8 hours or so will include the fix.

>How can I force to use a second indexer address?

open the config, replace the site link with the new address.
However, if the new site also has a text challenge, then the attempt will fail.
So you should be able to close the config, open it again, as if the site link has not changed then the new challenge should be from the new domain and you will be good to go.

IF you let me know what the alternate domain is I can add it to the config as a alternate.

**Comment by garfield69** [comment]
If you see "Request to Jackett server failed" then there is a back door method that may work for you.
1. shutdown the Jackett service.
2. locate the indexers folder in your config path, tipically `~/.config/Jackett` for linux or `%ProgramData%\Jackett` for windors
3. edit the lostfilm.json file with a plain text editor and update the sitelink value
4. start up the jackett service and you should be good to go

**Comment by kekal** [comment]
> IF you let me know what the alternate domain is I can add it to the config as a alternate.

I don't know other mirrors, but lostfilm.tv is under Cloudflare, which is inconvenient.
And  lostfilm.uno has a correct cert and can be used well as I understand:
![image](https://user-images.githubusercontent.com/13663141/120942817-f86bb580-c733-11eb-9951-49e8e7232582.png)


> If you see "Request to Jackett server failed" then there is a back door method that may work for you.

Sorry, in a paroxysm of testing, I removed the indexer, and now I cannot add it back for the same reason :)

I will wait for a fix. 
Thanks a lot.

**Comment by kekal** [comment]
Update.
I found other ones.

|||
|-|-|
|Correct one https://www.lostfilm.win|![image](https://user-images.githubusercontent.com/13663141/120943106-8e541000-c735-11eb-8ebc-6352a9f0893d.png)|
|Expired https://lostfilm.tw|![image](https://user-images.githubusercontent.com/13663141/120943132-b6dc0a00-c735-11eb-9384-ce885abeed35.png)|
|Expired https://lostfilm.site|redirecting to https://lostfilm.tw|

**Comment by Zloi78** [comment]
Here is another working resource: https://www.lostfilmtv.site/

**Comment by garfield69** [comment]
v0.18.259

**Comment by kekal** [comment]
Tested succesfully
Thanks a lot
