### ISSUE TITLE
xspeeds test fails

### ISSUE THREAD

**Issue by manderss99** [Jackett/Jackett#1187]
xspeeds has recently stopped working, result from test:

Test failed for xspeeds: The 'meta' start tag on line 7 position 2 does not match the end tag of 'head'. Line 20, position 3.

version 1197

**Comment by kaso17** [comment]
I had to reconfigure it but besides that it'w working fine for me, please post a complete enhanced log

**Comment by manderss99** [comment]
started working again without any change from my part ... closing
