### ISSUE TITLE
Unable to start Jacket on debian

### ISSUE THREAD

**Issue by hkpanchani** [Jackett/Jackett#11888]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Debian 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

`jackett[524]: /opt/Jackett/jackett_launcher.sh: 10: /opt/Jackett/jackett_launcher.sh: /opt/Jackett/jackett: Exec format error`

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
> Read and complete in full with information about your setup and issue before submitting.
Do not delete the template.

**Comment by hkpanchani** [comment]
I downloaded ARM64 instead of AMD64. Sorry my bad.
