### ISSUE TITLE
Enable 'Enhanced logging' by default & add a 'Clear log' button

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#1188]
I think it might be a good idea if 'Enhanced logging' is enabled by default. This should reduce the back and forth communication with users who raise issues which require posting an enhanced log. Instead of them posting a basic log, and us having to ask them for the enhanced one, they'll directly post the enhanced log when opening a new issue.

I also think a 'Clear log' button might be useful. Users can utilize it to clear the log right before reproducing the issue in question. This would ensure that only the relevant parts of the log are copied & posted, without any missing or extra lines.

Thoughts?

**Comment by JigSawFr** [comment]
Hum, enhanced logging by default will produce a ton of useless logs (and space usage) until a potential problem encountered by a user. They just need to be smart or read how to report a problem in an issue ?

**Comment by RoloSoze** [comment]
@JigSawFr Maybe logging can be configured to get auto deleted every x days or so? You're right, but unfortunately, most users do not read the instructions, and just provide a basic log, which adds the extra step of us having to ask them for the enhanced log. In many cases, they never get back to us, so we're left with no option but to close the issue and ask them to reopen it if they're able to provide the enchained log in the future. 

My intention is to just shorten this whole ordeal and make enhanced logging the default option in Jackett. Notice how I also suggested a 'Clear log' button to be added to Jackett's interface. When the user encounters a problem, they would clear the log first, reproduce the problem, and then copy the log to paste it under their issue. This would ensure that no missing or additional parts of the log are included, and would help the developers to potentially solve problems more quickly. 

Thoughts?

**Comment by JigSawFr** [comment]
Why not auto prune logs but with manual activation.
Other ways could be:

- Auto send issue from jackett app (by a log viewer and user action on it).
- Add a GitHub template for issue (so users will be forced to read / autocomplete issue and follow guidelines)

**Comment by RoloSoze** [comment]
@JigSawFr I'm OK with both, whichever works best to make problem solving easier & faster while eliminating unnecessary back & forth with the users. 

@kaso17 Thoughts?

**Comment by JigSawFr** [comment]
Or something like https://sentry.io/

**Comment by RoloSoze** [comment]
@JigSawFr Looks really promising! The 'Hobbyist' option is actually free!

**Comment by RoloSoze** [comment]
I don't think this is necessary anymore. I'll close it for now!
