### ISSUE TITLE
[lostfilm] Exception (lostfilm): certificate validation failed: [Subject]  CN=*.lostfilm.run[Issuer]  CN=RapidSSL RSA CA 2018, OU=www.digicert.com, O=DigiCert Inc, C=US[Serial Number]  01406818B1CFDE89F65111CF631D21DF[Not Before]  6/5/2020 3:00:00 AM[Not After]  6/6/2021 3:00:00 PM[Thumbprint]  25234600906DF82792DE9F4AA75A5AED2F226577: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by nahornyy** [Jackett/Jackett#11880]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Duplicate of #11879
