### ISSUE TITLE
Jackett stopped working since upgrading to mono 4.8

### ISSUE THREAD

**Issue by manderss99** [Jackett/Jackett#1189]
updated since I got a warning that jackett has issues with 4.2. Seems like a bad move.
followed instructions on mono site and had to do apt-get dist-upgrade to get it installed.

Now I get this message on every indexer:

 Test failed for alpharatio: An error occurred while sending the request: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED)

Ubuntu 16.04 / Jackett 1197

**Comment by shenanigans12** [comment]
This may or may not be related, but I'm getting the same error for ticket #1179

**Comment by manderss99** [comment]
This solved it on Ubuntu (from #1179):

Download this pem file:
https://curl.haxx.se/ca/cacert.pem

Then run:
sudo cert-sync ~/Downloads/cacert.pem

many thanks @shenanigans12 !
