### ISSUE TITLE
[film-paleis] Login failed: Selector

### ISSUE THREAD

**Issue by tyhawk** [Jackett/Jackett#11894]
### Environment

**OS**: Linux (openSUSE Leap 15.2

**.Net Runtime**: unknown

**.Net Version**: unknown

**Jackett Version**: v0.18.225

**Last Working Jackett Version**: unknown

**Are you using a proxy or VPN?** [yes/no] no

I'm using the Jackett docker container ghcr.io/linuxserver/jackett:latest

### Description

When trying to add this tracker and after following all instructions I got this error andf was asked to create this ticket.

### Logged Error Messages

```
Login failed: Selector "a[href="logout.php"]" didn't match
```

**Comment by ilike2burnthing** [comment]
See the troubleshooting for this error - https://github.com/Jackett/Jackett/wiki/TroubleShooting#login-failed-selector
and the Notes section here - https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work

If those don't help, please provide an **enhanced** log of the issue - https://github.com/Jackett/Jackett/wiki/TroubleShooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
