### ISSUE TITLE
[1337x] rss and search not working with only category (no keyword filter)

### ISSUE THREAD

**Issue by Bazzu85** [Jackett/Jackett#11899]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10 PRO

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Jackett Version v0.18.273

**Last Working Jackett Version**: don't know

**Are you using a proxy or VPN?** [yes/no] no

### Description

- Grab the 1337x rss feed and check the content -> many results
ex. link: [http://127.0.0.1:9117/api/v2.0/indexers/1337x/results/torznab/api?apikey=5rd34sm73z8m74wz9cjw5lcabvki7nqy&t=search&cat=&q=](url)
- Add only the 6000 category to filter -> no results
ex. link: [http://127.0.0.1:9117/api/v2.0/indexers/1337x/results/torznab/api?apikey=5rd34sm73z8m74wz9cjw5lcabvki7nqy&t=search&cat=6000&q=](url)
- Add the 1080p keyword to the query -> many results
ex. link: [http://127.0.0.1:9117/api/v2.0/indexers/1337x/results/torznab/api?apikey=5rd34sm73z8m74wz9cjw5lcabvki7nqy&t=search&cat=6000&q=1080p](url)

same behaviour with manual search
check screenshots

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![image](https://user-images.githubusercontent.com/7345587/121642344-ae1a6980-ca90-11eb-8148-c29dc48354e1.png)
![image](https://user-images.githubusercontent.com/7345587/121642363-b5417780-ca90-11eb-9265-2f26f00bfeae.png)
![image](https://user-images.githubusercontent.com/7345587/121642389-bd011c00-ca90-11eb-981e-500ec3158ca7.png)
![image](https://user-images.githubusercontent.com/7345587/121642443-cee2bf00-ca90-11eb-8a9d-9ce0624712b8.png)
![image](https://user-images.githubusercontent.com/7345587/121642461-d609cd00-ca90-11eb-8fb3-77e7c29776ad.png)
![image](https://user-images.githubusercontent.com/7345587/121642577-ff2a5d80-ca90-11eb-91df-bcc7282a9f91.png)

**Comment by garfield69** [comment]
yup. this is due to limitations on the 1337x web site, which does not support a search= without a keyword of at least 3 chars.
as a circumvention, the indexer for a keywordless search does 3 separate page fetches the `cat/movies` page, the `cat/tv` page and the `cat/music`page, and these pages do not support category filtering.
I do not think there is anything we can do to improve the indexer.
