### ISSUE TITLE
[HD-Only] Jackett doesn't grab language info

### ISSUE THREAD

**Issue by itdaboyz** [Jackett/Jackett#1190]
Hi,

On HD-Only, when searching for a release, the language and subtitle info seem not to be parsed : 
Jackett search
http://i.imgur.com/K8yvJh1.png

HD-O search
http://i.imgur.com/MrJ7Yol.png

I think because of this, Radarr assumes every release are in english.

Thank you.
______________________________
Jackett version: 0.7.1197.0
Mono version : 4.6.2

**Comment by kaso17** [comment]
These language flags are not available via the gazelle API. The site ops have to add them to their API first before we can support them.
