### ISSUE TITLE
Don't include dead torrents (seeders=0) in api/v2.0/indexers/all/results/torznab

### ISSUE THREAD

**Issue by Spykerwolf** [Jackett/Jackett#11902]
Hey guys.

When I do a manual search I can tick 'hide dead torrents'.
Is there a way to specify this in a RSS url feed?

For example:
/api/v2.0/indexers/all/results/torznab ONLY include seeders with at least 1.

**Comment by garfield69** [comment]
no, currently the torznab specs does not support any filters related to seeders on search queries.
