### ISSUE TITLE
[abnormal] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by thiryjer** [Jackett/Jackett#11906]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: synology

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.18.290

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

since site changed to abnormal.ws to abn.lol

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by antoineguilbert** [comment]
Same problem for me

**Comment by garfield69** [comment]
@JigSawFr can you take a look at this please? As well as the domain change there may be login and torrent browser path changes too. Thanks.

**Comment by antoineguilbert** [comment]
Login URL : https://abn.lol/Home/Login
Search torrent URL : https://abn.lol/Torrent
Detail torrent URL : https://abn.lol/Torrent/Details?ReleaseId=XXXXX

It may be helpful :)

**Comment by JigSawFr** [comment]
Oh my ... this is the new version. I need to recode it 😅

**Comment by thiryjer** [comment]
@JigSawFr i know your are the best coder , you can do it !

**Comment by JigSawFr** [comment]
I've implemented the login part. (Now with a CSRF token !). So we need to get it before sending login data.
Next time i will work on torrent search, but now it's swimming pool time !

**Comment by thiryjer** [comment]
thanks , good bath

**Comment by JigSawFr** [comment]
Configuration -> Success
Test -> Success
Mapping of torrents rows in progress.

**Comment by JigSawFr** [comment]
Mapping -> Success
Multi-Page Search -> Success
Categories Mapping -> Success (_there is less categories than before, only main categories are available as TV / Movies / etc_)
Search (no results, few results, lot of results) -> Success

Todo:
- Search Params
- Web Request delay implementation

**Comment by ilike2burnthing** [comment]
[v0.18.354](https://github.com/Jackett/Jackett/releases/tag/v0.18.354)

**Comment by Adelscott** [comment]
@JigSawFr there's a problem on the size of the files : for example when it should be 310,85 MB in Jackett it's listed as 30.36 GB
