### ISSUE TITLE
[desitorrents] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by geek-baba** [Jackett/Jackett#11904]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

They recently moved their site to Gazelle and updated their API's, now when I connect and test it says "Found no results while trying to browse this tracker". Let me know if you need anything from the dev team and I can get the information as needed.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
@ilike2burnthing  youve an a/c on this site, wanna take a look?

**Comment by ilike2burnthing** [comment]
I would, but it seems I can't sign in. Trying to reset my account doesn't work, and their IRC is offline. Looks like I'm not the only one - https://torrentinvites.org/f31/desitorrents-news-592251/

@geek-baba is there a contact email for them?

**Comment by geek-baba** [comment]
> I would, but it seems I can't sign in. Trying to reset my account doesn't work, and their IRC is offline. Looks like I'm not the only one - https://torrentinvites.org/f31/desitorrents-news-592251/
> 
> @geek-baba is there a contact email for them?

Ok - let me see if I can get it reset, whats your ID?

**Comment by ilike2burnthing** [comment]
nahik9937

**Comment by LokiThor2021** [comment]
@ilike2burnthing reset your password

**Comment by ilike2burnthing** [comment]
No luck. What's your email?

**Comment by LokiThor2021** [comment]
LokiThor2021@protonmail.com

**Comment by ilike2burnthing** [comment]
sent

**Comment by geek-baba** [comment]
> sent

Were you able to access the site?

**Comment by ilike2burnthing** [comment]
Yes. There's an open PR in which I've rewritten the indexer for the Gazelle abstract, but run into two stumbling blocks on DT's side - https://github.com/Jackett/Jackett/pull/11909

Just waiting to hear back from @LokiThor2021

**Comment by garfield69** [comment]
v0.18.329

**Comment by ilike2burnthing** [comment]
poster fix - [v0.18.345](https://github.com/Jackett/Jackett/releases/tag/v0.18.345)
