### ISSUE TITLE
Jackett search doesn't return all results on TorrentDay

### ISSUE THREAD

**Issue by element4l** [Jackett/Jackett#11910]
**OS**: W7SP1

**Jackett Version**: Latest

**Are you using a proxy or VPN?** no

### Description

Some jackett searches don't return results that are available on the website itself. E.g. Search for "the apprentice" on TorrentDay, returns season 1-9 pack (56gb), but this result doesn't appear in the jackett search for TorrentDay. Note that there are still other results from TorrentDay and other trackers, it's just this pack that's not included. 

More details: I can find the pack by adding s01-09 to the search, but it won't turn up in any of the results if I just search for "the apprentice." I've tried increasing the results to 200 in my TD settings and choosing to display "All" results in the jackett search, and sorting by size. Still nothing. Although jackett is showing only "(100)" results for the tracker. I am guessing that it's not able to load enough results to get the pack. I did not expect jackett to have such a limitation, and am wondering if there's a way around this, or if I should just forget about using it altogether. Because I have to be honest, if it can't return all the results for a search, I don't quite understand the point of using this software. That kind of defeats the purpose.

**Comment by garfield69** [comment]
yup, Jackett generally aims to return the first 100 results from a web site, as this is usually all that torznab apps like Sonarr will process anyway.
So if your target search falls outside the first 100 results then you usually refine your search.
Clearly this tool is not for you so find another.

**Comment by element4l** [comment]
Lazy bastard. You have no vision. Pathetic.
