### ISSUE TITLE
[The-Torrents] Configuration failed: Login Failed, got redirected

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#1192]
I'm getting redirected whenever I try to configure The-Torrents in Jackett. It was working fine until a few hours ago. I'm able to access the website normally. Enhanced log attached,

Error message: Configuration failed: Login Failed, got redirected

Jackett version: 0.7.1197.0
Mono version (if not using Windows): N/A

[log.txt](https://github.com/Jackett/Jackett/files/868637/log.txt)

**Comment by adamwinn** [comment]
@RoloSoze I can take a look if you have an invite

**Comment by RoloSoze** [comment]
@adamwinn Unfortunately I do not have an invite at the moment.

**Comment by kaso17** [comment]
seems like they did some kind of cleanup/inactivity pruning, my account got deleted.

**Comment by RoloSoze** [comment]
@kaso17 No invites at the moment, but check your email.

**Comment by kaso17** [comment]
They enabled the useless simple captcha. They changed their layout too. Will have to fix it later.
If you enable "include dead torrents" in the searhc options there's an error too, can you pleae report it to the admins.

**Comment by RoloSoze** [comment]
@kaso17 Error reported to one of the Admins. Take your time with this one. Thanks a lot!

**Comment by kaso17** [comment]
fixed via d866758a0d7cc9c2dd9405dcdd289019ced0ae9d
