### ISSUE TITLE
Jackett / FlareSolver / Ygg Torrent 

### ISSUE THREAD

**Issue by lan7ium** [Jackett/Jackett#11928]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

Bonjour, en essayant de configurer Jackett avec Flaresolver (la dernière version) j'ai cette erreur qui vient quand je clique sur OKAY pour ajouter le tracker à l'indexer.

Je précise que ma configuration est toute neuve (installer cette nuit) mais j'avais mis en pause à cause cette erreur 

### Logged Error Messages

> [yggtorrent] Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:8191) ---> System.Net.Sockets.SocketException (99): Cannot assign requested address   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)   --- End of inner exception stack trace ---   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, C (Config)

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Try `http://127.0.0.1:8191` instead.

If you have further issues, please complete the requested information above.

**Comment by lan7ium** [comment]
Environnement

OS : Ubuntu 20.04 LTS

Jackett Version : la dernière version (j'utilise docker avec docker-compose pour les mise à jour, j'utilise l'image : 

image: linuxserver/jackett:latest

Dernière version de la veste de travail  :  Jackett comme indiqué en bas de la page web :  Jackett Version v0.18.345 

Utilisez-vous un proxy ou un VPN ? [Oui Non] Non serveur dédié hébergé en DC

Petite précision, j'ai monté Jackett / Sonarr / Radarr / Ombi  sous docker avec Traefik  en guise de reverse proxy pour avoir l'accès via mon nom de domaine au lieu de l'adresse IP

**Comment by ilike2burnthing** [comment]
Depending on how you have your containers set up you can use `http://flaresolverr:8191` (your container's name), `http://172.17.0.2:8191` (your container's IP), `http://192.168.0.2:8191` (your server's local device IP), `http://142.251.33.110:8191` (your server's public IP), or `https://ian7ium.noip/flaresolverr` (your DDNS address).
