### ISSUE TITLE
[REQ] Torrent-Syndikat.org Release-Type filter on API call

### ISSUE THREAD

**Issue by Krytos** [Jackett/Jackett#11934]
Hi dear Jackett team, 

I was wondering if it would be able to filter the release type for torrent-syndikat.org. They have P2P, Scene and O-Scene (rar'd releases) and I would like to exclude the O-Scene releases, since it's a hassle with Sonarr and Radarr.  

I tried adding "&releasetype_p2p=1&releasetype_scene=1" to the additional parameters in Torznab, since it's what's used when browsing for torrents on TS but that sadly did not work. 

After opening a thread on the TS forum, they recommended to open a request here, since it would have to be filtered with the API call. 

Hope this is not too much trouble and thanks for all your efforts and time!

**Comment by ilike2burnthing** [comment]
None of the maintainers have an account. @hashworks you worked on the API last, could you have a look to see if this is possible to add?

**Comment by hashworks** [comment]
As far as I see it, there is no way for me to retrieve additional GET parameters. The `TorznabQuery` class has `QueryStringParts` but it's protected. @ilike2burnthing is there any way to receive additional custom parameters?

Instead, I can add additional config options for the whole tracker:
![](https://fb.hash.works/GKy0HpwU/)

However, you can only create *one* TS-Tracker config in Jackett. This means *ALL* searches are limited to those options. 
@Krytos would that be acceptable?

**Comment by Krytos** [comment]
Yeah, that would be great actually! Thanks :)

**Comment by ilike2burnthing** [comment]
@Krytos you can download hashwork's fix [here](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/3803/artifacts?artifactName=drop&api-version=6.0&%24format=zip), extract the installer/binaries archive you need, install and test whether it's working ok for you. If so we can add it to the next release.

**Comment by Krytos** [comment]
Seems to be working fine! Thanks for your work :)

**Comment by ilike2burnthing** [comment]
Thanks @hashworks!

**Comment by ilike2burnthing** [comment]
[v0.18.372](https://github.com/Jackett/Jackett/releases/tag/v0.18.372)
