### ISSUE TITLE
[Nyaa] Fails

### ISSUE THREAD

**Issue by zhdenny** [Jackett/Jackett#1194]
[Latest Windows Jackett Version]
Nyaa successfully added in Jackett Web Interface. Manual Search test also successful. Sonar fails to add it though.

I successfully added IP Torrents to Jackett and then into Sonarr just fine. I would think this would be no different. Same API Key, just different Torznab Feed.

Not sure why Sonarr isn't seeing Nyaa though. Help?

**Comment by Kusaha** [comment]
I can second this, having the same exact issue

**Comment by CodeMonkey626** [comment]
Since nyaa.se is now gone (😢), we can close this issue. /cc @kaso17
