### ISSUE TITLE
[thepiratebay] The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject]  E=none@vmware.com, CN=VMware, OU=VMware, L=Palo Alto, C=US[Issuer]  E=none@vmware.com, CN=VMware, OU=VMware, L=Palo Alto, C=US[Serial Number]  0090B8CE43ACE5B563[Not Before]  9/1/2018 9:45:35 PM[Not After]  9/1/2019 9:45:35 PM[Thumbprint]  3E764E6197B803D6C623D226D45FE78D258288A6 (Config)

### ISSUE THREAD

**Issue by FrankTheTank908** [Jackett/Jackett#11946]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

**Comment by FrankTheTank908** [comment]
I would like to update you guys, I fixed the issues. Some program edited my windows hosts file to block most torrent sites. I edited it and fixed all the connection issues. Hope this helps others.

**Comment by ilike2burnthing** [comment]
https://arstechnica.com/gadgets/2021/06/newly-discovered-vigilante-malware-outs-software-pirates-and-blocks-them/

**Comment by FrankTheTank908** [comment]
Wow look at that, haha. It’s not persistent either. me editing my host file was the literal fix for that. for the past 20 years I’ve been very careful. I guess my time was due haha.

**Comment by FrankTheTank908** [comment]
I know what file caused it, dr phone toolkit. In his tweet it’s listed there. I needed a complete iPhone backup and fix. touché
