### ISSUE TITLE
[aither] Search freeleech only not working

### ISSUE THREAD

**Issue by darkknight6722** [Jackett/Jackett#11947]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux using Docker Linuxserver.io version:  v0.18.364-ls33

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.18.364

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

Search freeleech only option in Aither.cc is not working. It includes both freeleech and non-freeleech torrents.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]
N/A

### Screenshots

[Place any screenshots of the issue here if needed]
N/A

**Comment by garfield69** [comment]
yes. when they upgraded to unit3d 5.3.0 the `freeleech=1` parameter became `free=1`
I'll update the indexer shortly.

**Comment by garfield69** [comment]
v0.18.367
