### ISSUE TITLE
Transfer indexers to seedbox install of jackett?

### ISSUE THREAD

**Issue by element4l** [Jackett/Jackett#11945]
This is just a question... I'm not sure how the template makes any sense here. I have a few dozen indexers I'd like to transfer over to a new install of jackett on a seedbox. Would be nice not to have to go through each and do them all again manually.

**Comment by garfield69** [comment]
Assuming your source Jackett is on a linux platform then the usual native install should have a  `~/.config/Jackett/` directory.
Copy the `Indexers` and `DataProtection` folders across.

**HOWEVER**

The password encryption for indexer configs is machine specific, so it is very likely that none of the passwords in any of your private or semi-private indexer configs will be decrypted properly by your seedbox. 
So you will need to access the dashboard on your seedbox Jackett and edit to re-enter and save your passwords.
