### ISSUE TITLE
[ImmortalSeed] "Value cannot be null" error when no results are found

### ISSUE THREAD

**Issue by adamwinn** [Jackett/Jackett#1195]
Jackett Version 0.7.1197.0  
Mono version (if not using Windows):  4.8.0

-------------------------------

Searching with a string that will return no results for ImmortalSeed, will cause a "Value cannot be null" error.

Steps to Reproduce:
1)  Select ImmortalSeed as the tracker for a manual search
2)  Search for "asdasdasd"
3)  Jackett will show "Value cannot be null" in the logs

Full logs:
http://pastebin.com/uwHEV6pW

**Comment by tryax** [comment]
I'm having a very similar issue to this today in Jackett Version 0.11.115.0. Getting Exception (immortalseed): Value cannot be null. Parameter name: uriString: Parse error no matter what I search for.

I tried the fixes in the new issue screen as well.

Thanks.

**Comment by garfield69** [comment]
try jackett pre-release v0.11.141

**Comment by tryax** [comment]
v0.11.141 fixed it. Thanks!
