### ISSUE TITLE
[REQ] Extend NewPCT to include current webpage https://www.newpct.me

### ISSUE THREAD

**Issue by kaizokumcc** [Jackett/Jackett#11966]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10
**.Net Runtime**:
**.Net Version**:
**Jackett Version**: last one
**Last Working Jackett Version**: last one
**Are you using a proxy or VPN?** no

### Description

Could it be possible to extend current description of the tracker NewPCT to include the webpage https://www.newpct.me ? It runs the following error if I try to add it with the current tracker: 

`An error occurred while updating this indexer
Found 0 releases!
Click here to open an issue on GitHub for this indexer.`

Thank you in advance!

**Comment by garfield69** [comment]
no, it is not possible as this clone does not use the same search engine as the others.
