### ISSUE TITLE
Jackett not attempting to bind to 9117 on Alpine 3.13/Core 5.0.7

### ISSUE THREAD

**Issue by rootwyrm** [Jackett/Jackett#11969]
### Environment

**OS**: Alpine 3.13

**.Net Runtime**: Core, no SDK

**.Net Version**: 5.0.7 556582d964

**Jackett Version**: 0.18.379

**Last Working Jackett Version**: 0.18.98

**Are you using a proxy or VPN?** N/A

### Description

Jackett is not opening the listening socket on 9117. No error messages are emitted. `strace` shows no attempt to open a socket, so it looks like Jackett just is not even attempting to start correctly. Other applications running in an identical environment continue to work normally. Removing all of the data including the cache and ServerConfig.json has no impact. Specifying the port with `-p 9117` also has no impact. 

[The symptomatic container is available here](https://hub.docker.com/r/rootwyrm/tc_jackett) or `docker pull docker.io/rootwyrm/tc_jackett`. Interactive inspection with `docker exec -it $ContainerName /bin/bash` is possible. (All volumes optional except /sys and /etc/localtime.)

### Logged Error Messages

No errors whatsoever.
```
2021-06-27 20:39:03.3386 Info Starting Jackett v0.18.379
2021-06-27 20:39:03.3832 Info Tracing enabled.
2021-06-27 20:39:03.3832 Info Jackett Data will be stored in: /talecaster/config
2021-06-27 20:39:05.3019 Info Overriding external access to False
2021-06-27 20:39:05.3294 Debug Creating web host...
2021-06-27 20:39:05.3297 Debug Content root path is: /opt/Jackett/Content
```

ServerConfig.json:
```
{
  "Port": 9117,
  "AllowExternal": true,
  "APIKey": "REDACTED",
  "AdminPassword": null,
  "InstanceId": "REDACTED",
  "BlackholeDir": "/talecaster/blackhole",
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": "/jackett",
  "CacheEnabled": true,
  "CacheTtl": 2100,
  "CacheMaxResultsPerIndexer": 1000,
  "FlareSolverrUrl": "http://172.16.100.12:8191",
  "OmdbApiKey": "",
  "OmdbApiUrl": "",
  "ProxyType": -1,
  "ProxyUrl": "",
  "ProxyPort": null,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true
}
```

**Comment by garfield69** [comment]
needless to say, all the standard releases from this repo (https://github.com/Jackett/Jackett) are working, as are the docker releases from the linuxServer.io team at https://hub.docker.com/r/linuxserver/jackett/
so the issue is either a set up problem at your end (port blocking?) or with this rootwyrm version you are using.
please note that we do not support any versions other than what is released from https://github.com/Jackett/Jackett/ so your best bet is to contact the rootwyrm provider
@ilike2burnthing anything you would like to add?

**Comment by rootwyrm** [comment]
@garfield69 ... maybe read the username or commit history next time before saying someone doesn't know what they're doing. Or even look at the container. (And you probably should have checked what groups I'm a member of.)

It is not a setup problem. Same exact configuration works with Mono 6.12.0.122 and worked with .NET official 5.0.3, [but 5.0.3 should not be used under any circumstances](https://github.com/dotnet/announcements/issues/188). Jackett is doing something that is not playing nice with the 5.0.7 service release under Alpine 3.13. And this is a setup that has been working since before Jackett 0.18.98.

What I can tell you for fact is that Jackett is simply not trying to open a socket on port 9117. Which is reproducible and has not been previously observed behavior in 2+ years and does not reproduce with Mono 6.12.0.122 and the exact same configuration. Maybe I am missing something, but even if I am, that doesn't explain the lack of attempt to open the socket.

**Comment by garfield69** [comment]
Hah, Oops, my bad. Sorry.

**Comment by rootwyrm** [comment]
> 
> 
> Hah, Oops, my bad. Sorry.

Ha, it's fine. I'm on a bit of a hair trigger because people are always arguing with me because I'm not a Microsoft employee so what do I know, right? ;P

But I really am at a loss here, because try as I might, I cannot get Jackett to even *attempt* to open a socket on 0.0.0.0:9117 or to produce any error message. Which from my perspective as much as yours makes NO sense. You see "valid config, weird container, must be user error" and I see "valid config, worked before, works on Mono, must be Jackett."

To be clear, `tc_jackett` is part of a comprehensive suite that I've been maintaining a number of years, TaleCaster. It's part of a comprehensive suite (Sonarr, Radarr, Lidarr, Plex, etc.) which is obviously heavily .NET biased. (Actually significantly predates linuxserver.io, heh.) And honestly up till now, Jackett's been one of the most (relatively) bulletproof pieces. So I'm really scratching my head. I've never had a no-error failure condition before. i.e. leave out libicu, it errors. But this failure, it gives me no clue what is broken at all. Not even digging into strace produced any helpful output other than "I see no attempt to open the socket." I'm honestly wondering if it isn't the ASP.NET stuff (which I don't know) or possibly build platform incompatibility (which I do know.)

**Comment by ilike2burnthing** [comment]
Was v0.18.98 working with .NET 5.0.7? Does v0.18.379 work with .NET 5.0.3? I'd assume the answers are no and yes respectively, but just want to double check.

**Comment by rootwyrm** [comment]
Just to be sure, I retested with 0.18.98 and same behavior. Doesn't attempt to bind, and no error, even with trace. Similarly, retested 0.18.379 with 5.0.3, and it's now behaving the same - no attempt to bind, no error. However, as mentioned, many other .NET applications are working with the exact same base. 

So I went ahead and added the 5.0.301 SDK, no dice there either.

So, cranked it up to 11 and rebuilt locally as: `dotnet publish Jackett.Server -f net5.0 -r linux-musl-x64 -c Debug` - note the `-r linux-musl-x64`. **This works.** As dreaded, `-r linux-x64` does NOT work. 
The issue occurs much, much earlier than I expected in fact. Whereas `-r linux-musl-x64` spits out lots of information when run with trace enabled, `-r linux-x64` does not even make it to "Debug Autofac container built" or printing any of the environment information.

That tells me that it's (another) glibc vs. musl thing. So definitely not entirely on Jackett, and also not entirely on .NET. It can be made more insensitive to the glibc stuff, but the fact that it's not even making it to environment tells me that'd be a lot of heavy lifting. Obviously I can work around that by doing my own build in the containers, but then we're talking about a non-supported build outside of releases.

What I would propose therefore is to add an additional build to the Azure pipelines to build `linux-musl-x64` for x64 and arm64 (non-arm64 is known broken) and packaging it as `Jackett.Binaries.$ARCH-musl.tar.gz`. Unfortunately I'm not familiar enough with Azure pipelines to offer a pull request. Though my inclination would be to use the `mcr.microsoft.com/dotnet/sdk:5.0-alpine-amd64` and `mcr.microsoft.com/dotnet/sdk:6.0-alpine3.13` containers to do the build. (There isn't an official arm64 for 5.0, but 6 preview should be fine.)

**Comment by ilike2burnthing** [comment]
@ngosang could you give this a look if you're free this weekend?

**Comment by rootwyrm** [comment]
Any progress on this? I've validated that `mcr.microsoft.com/dotnet/sdk:5.0-alpine-amd64` can be used to build a working Jackett for musl and I've had limited success in using Docker to generate an artifact, but it's... very not straightforward regardless of the CI platform. And unfortunately also generates a ton of garbage in addition to the release (which is the usual bad design of Docker problems,) but is at least workable.

The TL;DR version is, this works:
```
FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine-amd64 AS build

WORKDIR	/artifact
RUN		apk update && apk upgrade && apk add git bash build-base curl curl-dev linux-headers && \
	cd /artifact && \
	git clone https://github.com/Jackett/Jackett.git && \
	cd Jackett/src && \
	dotnet publish Jackett.Server -f net5.0 --self-contained -r linux-musl-x64

FROM docker.io/alpine:latest AS package
COPY	--from=build /artifact/Jackett/src/Jackett.Server/bin/Debug/net5.0/linux-musl-x64/* /package/
RUN		tar cf /Jackett.test.tar /package/ && \
	gzip /Jackett.test.tar

FROM docker.io/alpine:latest AS release
COPY --from=package /Jackett.test.tar.gz /Jackett.test.tgz

docker buildx build --target=release --output type=local,dest=$(pwd)/artifact/ .
```

Which will drop a file called `Jackett.test.tgz` in `$(pwd)/artifact/`, but also the entire contents of the Docker image. (Like I said: terrible design decision come home to roost.) However, said tarfile is a musl-compatible CLR that Just Works(TM). So the intent would be to ONLY take `artifact/Jackett.test.tgz` rather than the entire output. But as you can see, requires jumping through many hoops. And there is no Alpine-native image on Azure (or any other CI that I'm aware of.)

**Comment by rootwyrm** [comment]
@ngosang @ilike2burnthing any update on this? At this point, I have somewhat of an inkling as to how to do what's needed with Azure pipelines. However, I'm not sure how to test the Azure pipelines themselves.

**Comment by ilike2burnthing** [comment]
You can submit a PR for https://github.com/Jackett/Jackett/blob/master/azure-pipelines.yml (or anything else) to see if it builds correctly.

**Comment by ngosang** [comment]
I don't like the idea of releasing/maintaining more binaries for Alpine.
If you want to build a Docker image there are 2 alternatives:
1) Compile Jackett from source code. You are already doing it in your previous comment but it can be done much better. Base Alpine image, in one line RUN (install .net for alpine, download jackett, compile jackett, remove .net, remove .zip, uninstall packages, etc..). You will end with a lightweight image. Just Alpine + Jackett size.
2) Use Alpine Edge, install Mono package and test Jackett Mono release.

**Comment by rootwyrm** [comment]
> I don't like the idea of releasing/maintaining more binaries for Alpine.

Why?
There are literally no changes beyond the workflow.

**Comment by ngosang** [comment]
1. Alpine is not a widely used distribution.
2. Jackett has an updater service that has to download the right version. This requires some changes in the code and testing.
3. Another important reason is related to maintenance. Azure Pipelines have to be configured and updated frequently due to deprecation and security issues. We are only 3 developers for this huge project and other contributors are not familiar with *nix. We don't even maintain the Docker images for this reason.

Please, understand the limitations and build your own image with "auto-update" feature disabled.

**Comment by rootwyrm** [comment]
@ngosang which is exactly why I proposed addressing it the way I did.

1. Alpine is one of the fastest growing distributions, particularly in the container space, due to it's small size and high out of the box security. Which is why it is actively being invested in, and promoted as a target for ASP.NET and CLR containers. Bear in mind, we (as in .NET Foundation folks) have a specific objective of ensuring that runtime should be as insensitive to the host as possible. Meaning .NET applications should run identically regardless if the host is musl, glibc, or any other supported libc.
2. I certainly agree this adds some minor overhead, and I'm happy to look at it. Realistically speaking, the assumption should be that users on musl-based distributions (there's a few) should already be using an external update mechanism such as `apk` or as a container. So my thought is to detect musl-based distributions and simply inform rather than try to update. I don't think it'd be a heavy lift for me to add musl to the update routine though.
3. The point of using the official Microsoft .NET SDK image was to not maintain the actual Docker image itself which also covers any security concerns as they arise (usually within hours,) and the output would not and should not be a self-contained binary. 

But now that I've had a bit of time to dig in a little further, I realized, there actually is an easy way.
```
  - task: DotNetCoreCLI@2
            displayName: Build Jackett Server for musl libc
            inputs:
              command: publish
              projects: 'src/Jackett.Server/Jackett.Server.csproj'
              publishWebProjects: false
              zipAfterPublish: false
              arguments: '-r linux-musl-x64 --configuration $(buildConfiguration) --runtime $(runtime) --framework $(framework) --output $(Build.BinariesDirectory) /p:AssemblyVersion=$(jackettVersion) /p:FileVersion=$(jackettVersion) /p:InformationalVersion=$(jackettVersion) /p:Version=$(jackettVersion)' 
```

No, really. It didn't occur to me that `DotNetCoreCLI@2` is just `dotnet`. And `-r linux-musl-x64` **does not** require it be run on a musl-based host, only that you need a musl-aware SDK (which is anything post-3.1.0 as I recall. It may go back further.) You only need to be native for a self-contained build. This means that it doesn't actually incur any significant maintenance - or really any. It can simply be handled as part of the existing matrix.

I need to play around with that portion some more, but I'm very confident this can be a basically zero future maintenance, near zero impact change now.

**Comment by rootwyrm** [comment]
@ngosang @ilike2burnthing so I took a look at the Updater, and I realized there's something that actually complicates the Updater a bit unnecessarily. It also looks like it hasn't been updated in a long time.

https://github.com/Jackett/Jackett/blob/d9cc5e733ff8089b296971326f771f707ae841dd/src/Jackett.Updater/Program.cs#L46

The proposal I would make here is to instead use RID mapping based on the [.NET 6.0 catalog](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json). Yes, this looks way more complicated on the surface. But it actually isn't. It would instead be implemented with `RuntimeInformation.RuntimeIdentifier` [(docs here)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.runtimeidentifier?view=net-5.0) and only consider *supported platforms*. So `linux-arm`, `linux-arm64`, `linux-x86`, `linux-musl-x86`, `linux-musl-arm64`, `osx-x64`, and `win-x64`. (Also note that this does work on Mono.) This should actually be easier to maintain long term since adding/subtracting support would simply be a matter of adding/subtracting RIDs.

Would there be any objections to this approach?

**Comment by ngosang** [comment]
I'm not opposed. It will be merged you do the work, help with the testing in Alpine and you maintain the musl binary/flavor in case of errors.
* Open a PR with the changes in the Azure Pipelines and the Updater. The code to detect the OS is in bad shape and it's duplicated across all modules. If you can move related functions to the Commons and refactor the code it will be appreciated. Be really careful with the changes in the updater. It could affect 20k daily updates...
* The PR will be reviewed and tested before merging. It should not affect other artifacts.
* We do not maintain Docker images and will not do so in the future. The LinuxServer team does not build images with Alpine. Docker images are your thing.

**Comment by ilike2burnthing** [comment]
@rootwyrm do you want to submit a PR for this?
