### ISSUE TITLE
Add Xthor impossible

### ISSUE THREAD

**Issue by fana13** [Jackett/Jackett#1197]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.7.1197
Mono version (if not using Windows):  4.8

-------------------------------

Hi,
Impossible to add Xthor, I have this issue when I want to add it
`Test failed for xthor: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.`

I'd tried to lunch jackett like this : mono /opt/jackett/JackettConsole.exe -c libcurl (hope was the good syntax) and same thing issue for me.

Thanks :)

**Comment by RoloSoze** [comment]
@fana13 Can you check if it's related to #1123?

**Comment by fana13** [comment]
Yes I'm starting to read this before post my issue and nothing works for me.
But for triying, I do a test with Xthor and it works like a charm !
Don't understand how but it works !
Thanks for reply, I close ;)
