### ISSUE TITLE
[bjshare] Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by andrerxavier** [Jackett/Jackett#11976]
### Environment

Debian GNU/Linux 9.13 (stretch)

**Mono JIT compiler version 6.12.0.122

Jackett Version v0.18.385

I don't use VPN

### Description

I'm entering my credentials and it shows the error reported in the image.

### Logged Error Messages

[log.txt](https://github.com/Jackett/Jackett/files/6733769/log.txt)

### Screenshots
![Captura de tela 2021-06-29 104322](https://user-images.githubusercontent.com/6371188/123808144-de526c80-d8c6-11eb-8527-01e2c159adfc.jpg)

**Comment by ilike2burnthing** [comment]
Please provide enhanced logs of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by andrerxavier** [comment]
[log2.txt](https://github.com/Jackett/Jackett/files/6734337/log2.txt)

**Comment by ilike2burnthing** [comment]
`Seu endereço IP foi banido.`
`Your IP address has been banned.`

Try logging into the site in browser from the same device and IP and see if you get the same error.
