### ISSUE TITLE
[REQ]javdb.com(Adult-JAV)

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#11977]
Public Adult jav torrent sites
https://javdb.com/

Search engine and torrents working.

![5345346575687](https://user-images.githubusercontent.com/36575395/124002174-16000800-d9de-11eb-8b85-02bc9d0fd818.JPG)

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
