### ISSUE TITLE
[ncore] The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.: The operation was canceled. (Config)

### ISSUE THREAD

**Issue by miberecz** [Jackett/Jackett#11980]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux ARM64

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 

**Jackett Version**: Version v0.18.386

**Last Working Jackett Version**: first install

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[ncore] The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.: The operation was canceled. (Config)

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Any other indexers working or failing?

Are you able to access the site in browser from the same device and IP?

@cadatoiva / @RoloSoze / @morpheus133 any of you having the same issue?

**Comment by morpheus133** [comment]
For me its working both on windows and linux.

**Comment by mqmq0** [comment]
Its working from my PC on the same network, but now I noticed from the Pi I'm running jackett on I cannot ping ncore.pro 

opi@opi:~$ ping ncore.pro
PING ncore.pro(80.78.23.168 (2a0a:3840:8078:23:0:504e:17a8:1337)) 56 data bytes

the name gets resolved, but no ping answer. 
Strange thing is, its worked for couple days, and stopped now.

**Comment by ilike2burnthing** [comment]
Thanks @morpheus133.

@miberecz that's definitely odd, though at least it explains the error. I take it other indexers are working fine?

**Comment by miberecz** [comment]
Yes, I have Bithumen also, and its working.

**Comment by miberecz** [comment]
> 
> 
> Thanks @morpheus133.
> 
> @miberecz that's definitely odd, though at least it explains the error. I take it other indexers are working fine?

Yes, I have Bithumen also, and its working.

**Comment by ilike2burnthing** [comment]
@garfield69 any idea what could cause this?

**Comment by garfield69** [comment]
ipv6?

**Comment by ilike2burnthing** [comment]
@miberecz have you tried disabling IPv6 on your Pi?
