### ISSUE TITLE
[lemonhd] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by horseytr** [Jackett/Jackett#11985]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by Uzibird** [comment]
![image](https://user-images.githubusercontent.com/40909658/126435791-3f153c82-3305-425d-aadb-63af169951d5.png)
![image](https://user-images.githubusercontent.com/40909658/126435798-e2fdbc49-ea27-44f7-ac23-c2f8e2d8f9b9.png)


"[lemonhd] Found no results while trying to browse this tracker (Test)"
    I can save this indexer configuration, but it will notice me that after test.

## jackett version:
    Jackett Version v0.18.455
## Environment:
    linuxserver/jackett

**Comment by garfield69** [comment]
is it possible that there are no freeleech results in the first page of torrents?

**Comment by Uzibird** [comment]
It won't work even if I cancel it

**Comment by garfield69** [comment]
then please provide an enhanced log to I can take a look at the results.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by ilike2burnthing** [comment]
Possibly related to - https://github.com/Jackett/Jackett/issues/11829#issuecomment-882174558

**Comment by Uzibird** [comment]
> is it possible that there are no freeleech results in the first page of torrents?



> 那么请提供一个增强的日志，以便我可以查看结果。
> 见https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

[log.txt](https://github.com/Jackett/Jackett/files/6854698/log.txt)

**Comment by Uzibird** [comment]
> Possibly related to - [#11829 (comment)](https://github.com/Jackett/Jackett/issues/11829#issuecomment-882174558)

I think so.  many error is this, perhaps ther were modified the html structure.
    "CardigannIndexer (lemonhd): Error while parsing row "

**Comment by garfield69** [comment]
v0.18.459

**Comment by Uzibird** [comment]
> v0.18.459

thx , it work now, have a good day everyone.
