### ISSUE TITLE
[Bug]IceTorrent

### ISSUE THREAD

**Issue by VadVoci** [Jackett/Jackett#1198]
I have the following error in the ICETorrent Jackett:

"Found no results while trying to browse this tracker"

Please fix it when you have time
Jackett Version 0.7.1197.0

-------------------------------

**Comment by RoloSoze** [comment]
I can confirm this issue as well. Here's an enhanced log. 
[log.txt](https://github.com/Jackett/Jackett/files/870566/log.txt)

**Comment by adamwinn** [comment]
I can probably fix this if I can get an invite to test with

**Comment by VadVoci** [comment]
@adamwinn  give me an gmail address ..

**Comment by adamwinn** [comment]
@VadVoci, winnadam -at- gmail
Thanks

**Comment by VadVoci** [comment]
@adamwinn
ICETorrent Invite Sent!

**Comment by adamwinn** [comment]
I'll get working on it now

**Comment by adamwinn** [comment]
This is fixed by #1211
