### ISSUE TITLE
[anidex] The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject]  CN=catchit.wbroadband.net.au[Issuer]  CN=R3, O=Let's Encrypt, C=US[Serial Number]  048BEE7025E23B4CD1AAA4757DD613684128[Not Before]  6/18/2021 1:19:31 AM[Not After]  9/16/2021 1:19:30 AM[Thumbprint]  CA25409DC88778F06F2C7173FBABF08326214118 (Config)

### ISSUE THREAD

**Issue by richardwaters-gh** [Jackett/Jackett#11986]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
the official anidex certificate thumbprint is 6536cf0cd1e376057264a09f9eaabbdcc52f8fcc
you are getting CA25409DC88778F06F2C7173FBABF08326214118  so you are most likely being blocked by your ISP and redirected to a black hole.
try switching DNS from the one provided by your ISP to one of the public ones like cloudflare 1.1.1.1 or google 8.8.8.8
or use a VPN.
