### ISSUE TITLE
Can't Access Jackett Externally

### ISSUE THREAD

**Issue by UnPossible-Me** [Jackett/Jackett#11983]
### Environment

**OS**: Raspbian (Debian 10)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.18.390 

**Last Working Jackett Version**: 0.18.390

**Are you using a proxy or VPN?**: Nope

### Description
In reference to this issue [Issue 9402](https://github.com/Jackett/Jackett/issues/9402)

I too am trying to get access to jackett externally rather than though my network.
Now, I've got a dynamic IP setup with Duckdns, and a SSL certificate from LetsEncrypt.
Attempting to put those two together with my other services like Nextcloud and Deluge, isn't great.. 
So I'm trying to use an Apache2 proxy so all my services are secured with the cert.

Unfortunately ever time I try to access jackett, _[Domain]/jackett_, it returns Error 404, the requested URL could not be found.
This is currently my setup:
```
ProxyPass /jackett http://localhost:9117/

<Location /jackett>
    ProxyPassReverse /
    ProxyPassReverseCookiePath / /jackett
    RequestHeader set X-Jackett-Base "/jackett/"
    Order allow,deny
    Allow from all
</Location>
```
This is most likely where the problem is, as:
1. I can access jackett just fine using my external IP
2. I can access jackett locally, i.e. 192.168.1.2:9117

So what's going wrong?

**Comment by ilike2burnthing** [comment]
Haven't used Apache2 before, but - https://github.com/Jackett/Jackett#running-jackett-behind-a-reverse-proxy

**Comment by UnPossible-Me** [comment]
https://github.com/Jackett/Jackett#running-jackett-behind-a-reverse-proxy

I can't really tell the difference in functionally between the two, nevertheless, I've updated my configuration on the apache.conf file to:
```
<Location /jackett>
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
    ProxyPass http://127.0.0.1:9117
    ProxyPassReverse http://127.0.0.1:9117
</Location>
```
I don't really know what to put in Request_Scheme so that's remained as is.
Unfortunately, there's no change so far, I'm now stuck at:
` The requested URL was not found on this server`

Which leads me to believe it's not redirecting properly.
/jackett ---> /UI/Dashboard, which fails.

Currently I can only access jackett through http, (local and external IP)
Using https, leads to a Secure Connection Failed (both locally and on my domain), so it at least seems to find jackett correctly.

Finally, I haven't made any changes to the Base Path, it's still the greyed out /jackett, which I assume is the default.
I tried going through the logs, but there's nothing.

**Comment by ilike2burnthing** [comment]
You'll need to set the base path override to `/Jackett` in Jackett's settings. You'll then be able to access Jackett from http://192.168.1.2:9117/Jackett/UI/Dashboard whereas right now you can't. That's needed for the reverse proxy.

> I don't really know what to put in Request_Scheme...

Use this instead - `RequestHeader set X-Forwarded-Proto "https"`.

**Comment by UnPossible-Me** [comment]
Alright, while that didn't fix the problem, I think I've found the root cause of it:

The jackett server, (after your changes) is accessible from `192.168.1.2:9117/jackett/UI/Dashboard`, well it's also present from `192.168.1.2:9117/UI/Dashboard`, but that it should be?
It's the same for the external IP as well.

Now when using my domain, it redirects to `[Domain].com/jackettUI/Dashboard`, the backslash is missing leading to the incorrect URL.
If I modify it to `[Domain].com/jackett/UI/Dashboard` it should redirect me to the login page, which it tries.

I'm sent to `[Domain].com/UI/Login?ReturnUrl=%2FUI%2FDashboard` whereas attempting to login using my IP, it should be: `192.168.1.2:9117/jackett/UI/Login?ReturnUrl=%2Fjackett%2FUI%2FDashboard`

So I'm dropping certain parts, which I think has to do with the configuration in the apache2.conf file, any thoughts?

**Comment by ilike2burnthing** [comment]
Yes, when using the base path override it work with and without the override.

Try `Location /jackett/`

**Comment by UnPossible-Me** [comment]
> Try `Location /jackett/`

Location as in?
If you mean URL, `[Domain].com/jackett/` does redirect me properly, but
1. It doesn't fix the second problem of the sign in page
2. What's the difference between manually doing it afterwards then?

If it's it in the base path, I edited the `ServerConfig.json` from cli, cause I can't do it from the web UI, but it doesn't make a difference anyways. Still the same results.

**Comment by ilike2burnthing** [comment]
```
<Location /jackett/>
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"
    ProxyPass http://127.0.0.1:9117
    ProxyPassReverse http://127.0.0.1:9117
</Location>
```

**Comment by UnPossible-Me** [comment]
Well Damm that works.

So basically integrating adding the backslash at the beginning rather than after it failed?

**Comment by ilike2burnthing** [comment]
Both are required. Glad you got it sorted. Happy Jacketting 😉

**Comment by UnPossible-Me** [comment]
Huh, curious why some services like Jackett need it, but others like Deluge-web don't.
But anyways, many, many thanks for the support and helping me resolve the issue. :)
