### ISSUE TITLE
Jackett Manual Search - how to include OR expression?

### ISSUE THREAD

**Issue by Spykerwolf** [Jackett/Jackett#11999]
Hey guys. When doing a manual search query, is it possible to search for 2 things at the same time? For example I want to display 'Breaking Bad' & 'Better Call Saul' in the same search. Thanks!

**Comment by ilike2burnthing** [comment]
This isn't possible, as each trackers' search works differently, so while it might be possible on one particular tracker to search `+"breaking bad" +"better call saul"`, it won't be possible on nearly all others. You'll have to run two different searches.
