### ISSUE TITLE
[bug] ptn

### ISSUE THREAD

**Issue by petercontact** [Jackett/Jackett#1199]
ptn changed address and it is not working now, i tried changing piratethe.net to http://piratethenet.org/login.php or http://piratethenet.org/ and it isn't working

**Comment by RoloSoze** [comment]
@petercontact I'm using http://piratethenet.org/ and it's working fine for me. Can you post an enhanced log showing this error?

**Comment by petercontact** [comment]
this is going to sound stupid but  http://piratethenet.org works
 http://piratethenet.org/  still shows me Configuration failed: Login Failed
who knew an / could make a difference
