### ISSUE TITLE
Wrong season pack query

### ISSUE THREAD

**Issue by ouraios** [Jackett/Jackett#12008]
### Environment

**OS**: Debian 10

**.Net Runtime**: Mono

**.Net Version**: 5.18.0.240

**Jackett Version**: 3.0.6.1196

**Last Working Jackett Version**: 3.0.6.1196

**Are you using a proxy or VPN?** no

### Description

Hello,

When Sonarr is requesting Jackett to search for a season pack (through the `season` attribute in the API) Jackett compute a wrong query.

Example : I want `<anyshow> Season 3` jackett API receive from sonarr the following attributes : `q = <anyshow>` and `season = 3`

Then Jackett is going to request the indexer with following query : `<anyshow>.season.3`

But the indexer only have season pack with the following format : `<anyshow>.S03` how can i tell Jackett to format the season on the `SXX` format instead of `Season X` format ??

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/11668

**Comment by ouraios** [comment]
@ilike2burnthing i already saw this issue but this is the opposite here, on my issue i want `season x` to become `sxx` on the issue you linked its the opposite the author want `sxx` to become `season x`

**Comment by ilike2burnthing** [comment]
What indexer are you using which does this?

**Comment by ouraios** [comment]
i'm using `xthor-api` i went in the indexer file (https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/Xthor.cs) but saw nothing about a specific season format

**Comment by ilike2burnthing** [comment]
What is the full URL being used when Sonarr does a search?

**Comment by ouraios** [comment]
Example : `/api/v2.0/indexers/xthor-api/results/torznab/api?t=tvsearch&cat=5000,5030,5040,100013,100014,100015,100016,100017,100032,100098,100104,100110,100123&extended=1&apikey=(removed)&offset=0&limit=100&q=Lucifer&season=3`

**Comment by ilike2burnthing** [comment]
That's to Jackett's API, which will translate `season=3` to `s03`.

Enable enhanced logs and run the search again. This time look at the URL for Xthor's API which should show `s03`.

**Comment by ouraios** [comment]
it's working great, maybe i've mistaken 2 lines of log, if so my bad and sorry for disturbing and thanks a lot for maintaining this amazing tool !
