### ISSUE TITLE
[hdspain] Login failed: Selector

### ISSUE THREAD

**Issue by tulkarxxx** [Jackett/Jackett#12003]
Getting following error after introducing cookie value:

An error occurred while updating this indexer
Login failed: Selector ".tcabecera" didn't match
Click here to open an issue on GitHub for this indexer.

### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
You will get this error when Jackett tries to access the index.php page on hdspain's web site, and the cookie you provided was not accepted.
Read https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work to check you are using the correct method of getting the cookie string, and also check the **notes** section to see if any of it applies to you.
Also a useful tip: when using your browser to access hdspain for the cookie, first access the torrent search page on the web site, to ensure the web site is not blocking your access by requiring you to first read PM, or respond to site alerts or anything else like that.
