### ISSUE TITLE
[REQ] angietorrents.cc

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#12007]
Public site of movies and TV shows: https://angietorrents.cc

**Comment by garfield69** [comment]
https://angietorrents.cc/ have changed their search results HTML.
However, the problem is that the torrent details link the new HTML is generating is invalid, with both the details and download href causing a 404 `File not found.` error on the site.

**Comment by garfield69** [comment]
torrent search page now presenting
```
Search Engine is Down at the moment. We are currently performing maintenance on search engine.
Feel free to use other parts of the site.
Sorry for the inconvenience.
```

**Comment by garfield69** [comment]
there is little point in keeping a indexer if the web site does not have a working search engine.
we can always add it back if anyone discovers it operational again.

**Comment by garfield69** [comment]
v0.18.767
