### ISSUE TITLE
[yggtorrent] Name or service not known (www4.yggtorrent.li:443): Name or service not known (Config)

### ISSUE THREAD

**Issue by FLAFLALEBG** [Jackett/Jackett#12005]
### Environment

**OS**: Raspberry PI

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Jackett Version v0.18.402

**Last Working Jackett Version**: no

**Are you using a proxy or VPN?** [yes/no] no

### Description

Just don't worked i'm using docker

**Comment by ilike2burnthing** [comment]
Can you access the site in browser from the same IP? Can you ping it from within the container?

**Comment by garfield69** [comment]
recent upsurge in similar tickets raised for ygg pretty much all turn out to be ISP blocking. Most were solved by switching DNS from the one provided by your ISP to a public one from cloudflare 1.1.1.1 or google 8.8.8.8

**Comment by FLAFLALEBG** [comment]
![image](https://user-images.githubusercontent.com/33604967/125157612-555fee80-e16c-11eb-80bd-263527d9507a.png)

**Comment by ilike2burnthing** [comment]
See garfield69's comment, see if that makes a difference.

**Comment by FLAFLALEBG** [comment]
Yes,
I've add   --dns="1.1.1.1" \ to my command for start container and it's worked !!

Thanks so much @garfield69
