### ISSUE TITLE
Dmhy indexer error: Challenge detected but FlareSolverr is not configured

### ISSUE THREAD

**Issue by francochau** [Jackett/Jackett#12010]
An error occurred while testing this indexer
Exception (dmhy): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
