### ISSUE TITLE
[REQ] t.ceskeforum.com

### ISSUE THREAD

**Issue by zendiik** [Jackett/Jackett#12018]
Could you add https://t.ceskeforum.com/ to Jackett, please?

**Comment by garfield69** [comment]
I get
![image](https://user-images.githubusercontent.com/6933240/125356201-fee7ef80-e3b9-11eb-9628-ce701b62c487.png)
what is this?

**Comment by zendiik** [comment]
This is weird, because I got this 
![image](https://user-images.githubusercontent.com/10212768/125356946-38433f80-e367-11eb-97b3-3a5f691d6b1b.png)

**Comment by garfield69** [comment]
Ah. ok then, I'll try a vpn and see if I get something different.

**Comment by garfield69** [comment]
yes, an IP from a different region is required.

**Comment by garfield69** [comment]
v0.18.432

**Comment by zendiik** [comment]
Thank you

**Comment by garfield69** [comment]
https://t.ceskeforum.com/ ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/12018#issuecomment-1741825810

**Comment by garfield69** [comment]
online
