### ISSUE TITLE
[gazellegames] Your cookie did not work: Found 0 results in the tracker (Config)

### ISSUE THREAD

**Issue by devilismyfriend** [Jackett/Jackett#12019]
### Description

Trying to add a cookie from GazelleGames, tried from Firefox and Chrome, not getting a query back, the cookie syntax I'm getting:
PHPSESSID=examplePass; session=exampleSession==

Any ideas are welcome!

**Comment by garfield69** [comment]
Read https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work to confirm you are extracting the correct cookie string, and especially read the Notes section to see if anything there applies to you.

**Comment by devilismyfriend** [comment]
> Read https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work to confirm you are extracting the correct cookie string and especially read the Notes section to see if anything there applies to you.

Thanks for the help, I guess I need to access it from the seedbox in order to obtain a proper key (which isn't possible due to their rules), seems like they just implemented an api interface, would that be added?

**Comment by garfield69** [comment]
>seems like they just implemented an api interface, would that be added?

You could raise a new ticket `[req] gazellegames add api feature` and in the body erase the standard template and provide as much details / links to docs for the  api as you can find.

To use the API the new indexer will need to be written in c# so turn around will depend on a c# dev volunteer being available.
None of the team have an account on the site so most likely some other volunteer will need to raise a PR.
But given this site is focused only on games there may not be a lot of interest.
