### ISSUE TITLE
[REQ] https://www.tvboxnow.com/index.php?gid=2

### ISSUE THREAD

**Issue by xiNeRoar** [Jackett/Jackett#12011]
Public site of Hong Kong TV shows: https://www.tvboxnow.com/index.php?gid=2

**Comment by garfield69** [comment]
does this site have a **single** inhouse torrent search page where a search term can find all results across all the forums?
IF there is not a single inhouse search engine (not the general yahoo 3rd party search I see in the top right corner) then this site will not be suitable for use with Jackett.
