### ISSUE TITLE
[REQ] swarmazon.club

### ISSUE THREAD

**Issue by rationalflaneur** [Jackett/Jackett#12015]
Swarmazon is a new invite-based tracker. Could we [add it to Jackett](https://swarmazon.club/forum/d/33-jackett-indexer-list), please?

**Comment by garfield69** [comment]
v0.18.425

**Comment by garfield69** [comment]
Now that the Jackett Swarmazon API is bedded in and proven, I shall be removing the old Swarmazon HTML indexer shortly.

**Comment by garfield69** [comment]
v0.20.2614

**Comment by garfield69** [comment]
using https://swarmazon.club/api/search.php?api_key=(removed)&limit=100 via Jackett fails with a timeout,
but using the browser returns results.

**Comment by garfield69** [comment]
typical. intermittent error. worked on the fourth try.
