### ISSUE TITLE
[REQ] peerjunkies.com

### ISSUE THREAD

**Issue by rationalflaneur** [Jackett/Jackett#12016]
Could we add https://www.peerjunkies.com to Jackett, please?
MR 0.3 (MR 0.4 to avoid warnings)

**Comment by garfield69** [comment]
the f'ing security code is a nightmare. may need to try again tomorrow, i've reached a user limit during registration for getting the code wrong too many times.

**Comment by garfield69** [comment]
so for next time, 
![image](https://user-images.githubusercontent.com/6933240/125224107-0e672a00-e321-11eb-9474-c426a149f792.png)
is the code 
1e4jejSjrj1a
or
14eSr1ejjja
or something else?

**Comment by rationalflaneur** [comment]
The first, ithink. I had to try a couple of times before I could get in too

**Comment by garfield69** [comment]
v0.18.432

**Comment by garfield69** [comment]
https://www.peerjunkies.com/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
v0.20.2189
