### ISSUE TITLE
RARBG IMDb torznab search does not yield any result

### ISSUE THREAD

**Issue by agneevX** [Jackett/Jackett#12017]
### Environment

**OS**: Ubuntu 20.04
**.Net Runtime**: .Net-Core
**.Net Version**:
**Jackett Version**: v0.18.413
**Last Working Jackett Version**:
**Are you using a proxy or VPN?**: No

### Description

Using torznab API, this query doesn't return search results:

`http://jackett:9117/api/v2.0/indexers/rarbg/results/torznab/api?t=search&extended=1&apikey=xx&q=tt7335184`

However manual search works. 

When IMDb ID is present, does it search by that?

![C22E8B1A-89A3-464C-B1F7-1D49A6AB9071](https://user-images.githubusercontent.com/19761269/125236953-7ce8bf80-e302-11eb-96ac-d26c7a71e96b.jpeg)

**Comment by garfield69** [comment]
works for me using 
http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?t=tv&cat=5000,5030,5040,5045&extended=1&apikey=myapikey&offset=0&limit=100&imdbid=7335184

**Comment by garfield69** [comment]
and this works for me too
http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?t=search&cat=5000,5030,5040,5045&extended=1&apikey=myapikey&offset=0&limit=100&query=tt7335184

**Comment by garfield69** [comment]
oops no the t=search did not work, what I got was a default result list. sorry.

**Comment by agneevX** [comment]
Ok, so is there something wrong with the URL I'm using?

**Comment by garfield69** [comment]
I don't know, I'm not a C# dev. But I expect that the RarBG indexer which is written in C# may not have the logic code in place to handle your variation of the torznab query. We will need a C# dev volunteer to examine and/or code a fix.
In the mean time, the other two queries I've provided will allow you to get the results you were looking for.
