### ISSUE TITLE
Jackett doesn't preserve "alternative URL" settings when upgrading

### ISSUE THREAD

**Issue by pkreuzt** [Jackett/Jackett#12020]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: 

RaspberryOS Linux

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] 

.Net-Core

**.Net Version**:

**Jackett Version**: 

v0.18.413

**Last Working Jackett Version**:

Not sure

**Are you using a proxy or VPN?** [yes/no] 

No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

Having auto-upgrade activated, every time it is triggered I have to re-set some indexers' alternative URL to bypass censorship, since this is not preserved. The new version always uses default URL, which can be blocked in some places.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
if the alternative url you were using were from the *.unblockit.* domains, then when the provider switches to a new domain level (such as *.li to *.uno) then jackett will default back to the primary site link for the indexer.

same for any other alternate links that get their domains changed.
what was the alt site link you were using?

**Comment by pkreuzt** [comment]
This has happened on EpubLibre (alt site is epublibre.unblockit.uno), NewPCT (this has several alt sites, including pctmix1.unblockit.uno) and MejorTorrent (mejortorrent.nocensor.space). It is possible their domains have changed, but I hadn't noticed errors until Jackett upgraded itself

**Comment by garfield69** [comment]
Yes, so when we get notified that any site links have been replaced by a new domain we update the indexer.
And for any indexers whose current active site link happens to be the obsolete site link, then Jackett will update that  indexer's active site link to the first domain in the indexer's site link list.
So this would seem to be the case for you.
