### ISSUE TITLE
ARM64 - OSMC - jackett.service fails on startup

### ISSUE THREAD

**Issue by jberbissbd** [Jackett/Jackett#12043]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: OSMC (Debian Buster) - Raspberry pi 4 B (arm64)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: unknown

**Jackett Version**: 0.18.441

**Last Working Jackett Version**: none

**Are you using a proxy or VPN?** [yes/no] no

### Description

Fresh OSMC install on Raspberyy pi 4 B. Installed without issues following official instructions. [Requirements](https://github.com/dotnet/core/blob/master/Documentation/linux-prereqs.md) installed. Jackett service fails seconds after started, constantly restarting.
**edit**: I've checked and the file is already where it's supposed to be (see logs). System installed from [here](http://download.osmc.tv/installers/diskimages/v19testing/OSMC_TGT_rbp4_20210414.img.gz) 

### Logged Error Messages

output from "systemctl status jackett.service":
`● jackett.service - Jackett Daemon`  
`Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: enabled)` 
`Active: activating (auto-restart) since Sat 2021-07-17 07:36:52 CEST; 405ms ago`  
`Process: 1468 ExecStart=/bin/sh /opt/Jackett/jackett_launcher.sh (code=exited, status=0/SUCCESS)`  
`Main PID: 1468 (code=exited, status=0/SUCCESS)`

output from journalctl -u jackett.service:

`de jul. 17 07:38:24 osmc systemd[1]: jackett.service: Service RestartSec=5s expired, scheduling restart.`
`de jul. 17 07:38:24 osmc systemd[1]: jackett.service: Scheduled restart job, restart counter is at 3.`
`de jul. 17 07:38:24 osmc systemd[1]: Stopped Jackett Daemon.`
`de jul. 17 07:38:24 osmc systemd[1]: Started Jackett Daemon.`
`de jul. 17 07:38:24 osmc jackett[683]: /opt/Jackett/jackett_launcher.sh: 10: /opt/Jackett/jackett_launcher.sh: /opt/Jackett/jackett: not found`

content of /etc/systemd/system/jackett.service:

`[Unit]`
`Description=Jackett Daemon`
`After=network.target`

`[Service]`
`SyslogIdentifier=jackett`
`Restart=always`
`RestartSec=5`
`Type=simple`
`User=osmc`
`Group=osmc`
`WorkingDirectory=/opt/Jackett`
`ExecStart=/bin/sh "/opt/Jackett/jackett_launcher.sh"`
`TimeoutStopSec=30`

`[Install]`
`WantedBy=multi-user.target`

### Screenshots
None

**Comment by jberbissbd** [comment]
Solved, my bad.

Turns out that, despite being in 64 bit architecture, apps must be 32 bit to work. So, I tried the 32 bit version and it works like a charm.

I hope this will be useful for somebody looking for the same problem.

**Comment by djiang** [comment]
> I hope this will be useful for somebody looking for the same problem.

Yes, I started accidentally on AMD64 (after mixing it up with ARM64), then tried ARM64 version, came across this issue, then finally tried ARM32. Works now!! Thanks!!
