### ISSUE TITLE
[polishsource] Login failed: No form found on https://polishsource.cz/login.php using form selector form[action=

### ISSUE THREAD

**Issue by PrzemekSkw** [Jackett/Jackett#12059]
Hello,  polishsource.cz tracker don't work because no capcha to login.

Regards.

**Comment by garfield69** [comment]
the indexer presents a captcha if one is present on the login page when Jackett tries to login in.
when you use the jackett dashboard to edit the config you have two choises:
1. if the captcha image is present then enter the required captcha text along with your credentials
2.  if the image is not present ensure the captcha text field is empty

remember that the login cookies expire after what ever interval the site sets, so if the jackett indexer starts to fail to prsent browser results you will need to edit he config and enter the new captcha challenge.

**Comment by PrzemekSkw** [comment]
Hi, this capcha was gone when I login to Jackett today. Now I see that and it works.
Thanks.
