### ISSUE TITLE
[Arabafenice] works after several attempts, displays errors

### ISSUE THREAD

**Issue by gandalf764** [Jackett/Jackett#12057]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux 18.04

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.18.455

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

For some time, rtorrent has struggled to communicate with jackett about the "Arabafenice" host.
He downloads the torrents after several attempts.
I did a test on jackett and I noticed that it displays many errors, I don't know if this is the reason.
Power to control? thank you.

### Logged Error Messages

[log.txt](https://github.com/Jackett/Jackett/files/6856084/log.txt)

### Screenshots

![2021-07-21 15_21_31-Window](https://user-images.githubusercontent.com/41706025/126495697-1b2865e8-27d5-458f-88a2-e60bf114f0cd.png)

**Comment by ilike2burnthing** [comment]
You'll need to provide enhanced logs as none of the maintainers have an account - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by gandalf764** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/6858312/log.txt)

here full log
thanx

**Comment by ilike2burnthing** [comment]
Ok, that resolves the categories:
<details>
<summary>categories</summary>

```
    # HRS
    - {id: 34, cat: Movies/HD, desc: "1080p HRS x264"}
    - {id: 47, cat: Movies/UHD, desc: "2160p 4K UHD HRS"}
    - {id: 35, cat: TV, desc: "Serie TV HRS"}
    - {id: 36, cat: Movies/SD, desc: "DVDRip HRS"}
    - {id: 41, cat: Movies/SD, desc: "BDRip 576p HRS"}
    - {id: 39, cat: Movies/HD, desc: "1080p HRS x265 HEVC"}
    # AREA SuperVip
    - {id: 33, cat: Movies/HD, desc: "[DD] Film 720p MP4"}
    - {id: 54, cat: Movies/HD, desc: "[DD] 1080p V.U. MKV"}
    - {id: 55, cat: Movies/BluRay, desc: "[DD] FULL BluRay"}
    - {id: 57, cat: Movies/UHD, desc: "[DD] 4K FULL BluRay"}
    - {id: 58, cat: XXX, desc: "[DD] XXX 1080p"}
    - {id: 59, cat: XXX, desc: "[DD] XXX 4K 2160p"}
    - {id: 60, cat: XXX, desc: "[DD] XXX 720p"}
    # VIDEO
    - {id: 1, cat: Movies, desc: "News Cinema"}
    - {id: 40, cat: TV/UHD, desc: "4K Video Untouched"}
    - {id: 2, cat: Movies/SD, desc: "BD-DVDRip"}
    - {id: 3, cat: Movies/DVD, desc: "DVD 5"}
    - {id: 50, cat: Movies/UHD, desc: "4K 2160p UHD"}
    - {id: 6, cat: Movies/BluRay, desc: "BluRay Full"}
    - {id: 4, cat: Movies/HD, desc: "1080p 3D x264"}
    - {id: 7, cat: Movies/HD, desc: "1080p x264"}
    - {id: 46, cat: Movies/HD, desc: "1080p VideoUntouched"}
    - {id: 44, cat: Movies/HD, desc: "1080p x265 HEVC"}
    - {id: 5, cat: Movies/DVD, desc: "DVD 9"}
    - {id: 9, cat: TV/Anime, desc: "Cartoons"}
    - {id: 8, cat: TV/Anime, desc: "720p x264"}
    - {id: 12, cat: TV, desc: "Stagioni Concluse"}
    - {id: 13, cat: TV, desc: "Stagioni in Onda"}
    - {id: 14, cat: TV, desc: "TV Show"}
    - {id: 42, cat: TV, desc: "Serie Tv Sub Ita"}
    - {id: 15, cat: TV/Documentary, desc: "Documentari"}
    - {id: 53, cat: TV/HD, desc: "VIDEO MP4 720p"}
    - {id: 38, cat: XXX, desc: "xXx"}
    - {id: 43, cat: Other, desc: "Araba per il sociale"}
    # MUSICA
    - {id: 17, cat: Audio, desc: "Musica Italiana"}
    - {id: 45, cat: Audio, desc: "Discografie"}
    - {id: 18, cat: Audio, desc: "MusicaInternazionale"}
    - {id: 19, cat: Audio, desc: "Compilation"}
    # PDF
    - {id: 21, cat: Books, desc: "Ebook"}
    - {id: 22, cat: Books/Comics, desc: "Comics"}
    - {id: 23, cat: Books, desc: "Newsstand"}
    - {id: 56, cat: Books/Mags, desc: "Riviste"}
    - {id: 48, cat: XXX/Other, desc: "Riviste xXx"}
    - {id: 49, cat: XXX/Other, desc: "Fumetti xXx"}
    # GAMES
    - {id: 25, cat: Console/PS4, desc: "Sony Games"}
    - {id: 26, cat: Console/XBox, desc: "XboX Games"}
    - {id: 27, cat: Console/Other, desc: "Nintendo Games"}
    - {id: 28, cat: PC/Games, desc: "PC Games"}
    # SOFTWARE
    - {id: 30, cat: PC/ISO, desc: "Windows APP"}
    - {id: 31, cat: PC/Mobile-iOS, desc: "Apple APP"}
    - {id: 32, cat: PC/Mobile-Android, desc: "Android APP"}
```
</details>

Your enhanced was missing the failed download attempt though.

**Comment by gandalf764** [comment]
ooops... 
i try again..
now: failed rss update in rtorrent..
[log.txt](https://github.com/Jackett/Jackett/files/6858737/log.txt)

**Comment by garfield69** [comment]
the log shows that you are getting this error when you try to download
`Error OOppss.Non sei autorizzato a scaricare... `

**Comment by gandalf764** [comment]
That torrent tracker message comes out when I try to download the same torrent 2 times.
If I press on download, the first time it downloads it, if I press again on download that message comes out.
I don't know why it prevents jackett from doing rss updates, and sometimes even downloading torrents.
here an example link:
https://www.arabafenice.me/download.php?id=f1f93d93125c50bbe169785798e63dae75b4912f&f=The.Father.Nulla.E.Come.Sembra.2020.ITA.MD.AC3.ENG.AC3.1080p.BluRay.x264-HRS. mkv.torrent & key = 311f9469

**Comment by garfield69** [comment]
maybe the site keeps track of the number of active downloads and restrict a user to a certain number?
check the FAQ or Rules for such restrictions.

**Comment by gandalf764** [comment]
no, i know the admin..
i think is the site problem.
I did some testing and found that sometimes it generates a KEY (final in the download address) which is sometimes invalid.
I tried to remove that key and the download starts without problems.
Is it possible to make Jackett delete that key generated for the download link? I believe that this can be resolved.

**Comment by garfield69** [comment]
>Is it possible to make Jackett delete that key generated for the download link? I believe that this can be resolved.

I think so, by adding a regexp to capture the DL url up to the `&key=`
but I'm not going to publish this until you have tested the change to verify, so you will need to download the artifact from https://dev.azure.com/Jackett/Jackett/_build/results?buildId=3894&view=artifacts&pathAsName=false&type=publishedArtifacts and install the appropriate package for your platform and see if the indexer works as you intended.
Don't forget to turn on the enhanced logging during the test just in case there is an error.

**Comment by gandalf764** [comment]
It works!
I installed the version of jackett with the modification and there are no more errors!
I'm reinstalling the official version for now and waiting for an official update.
I attach the log file so that you can check for other errors.
Thank you!
[log.txt](https://github.com/Jackett/Jackett/files/6861364/log.txt)

**Comment by garfield69** [comment]
v0.18.463

**Comment by gandalf764** [comment]
Although very frequently than before, I still get some errors from this tracker.
This time it doesn't look like the same error as before, I saved a full log, the error should be there.
Basically rutorrent tells me:

[07/24/2021 12:01:59] Error loading torrent. (Http://[hidden]:9117/dl/arabafenice/?jackett_apikey=[hidden]&path=Q2ZESjhQZ3Z1NS1PVFpKS3JWRmQ5cFhOTHJsZXNxM2Frd2JpaEtVUDNfV0NhTjVlS0M4R2RpOUpfX2ZFX2ZKUlpQbjBNeU5takZfRGIxem9OMXJ3ZWNOX3lHaU56UjVSWmdmT00wX1M4eGR0cU5WSjcwTlFwRTdFREhNdVhLLUw2WEFLaDc5b1h2V3EteHZTV2x1b3B4V3ltdnZKNDBza2o4Rzl4OUZpSWxvR3hOemNiZDQ1MkZOT2pWSzdmTzMxLXFMY0ZIbWNTS1VCVGMxRjEzVk1FcmZVVERZTnNGbU1xLXdHWmZTd1JPbFZBdVdIcWNqbmpLVHhmZHNKWUtBRlhvWjBaUQ&file=Io+Sono+Nessuno+2021+ITA+ENG+AC3+Subs+1080p+BluRay+x264+HRS+mkv)
[07/24/2021 12:02:46] Error loading torrent. (Http://[hidden]:9117/dl/arabafenice/?jackett_apikey=[hidden]&path=Q2ZESjhQZ3Z1NS1PVFpKS3JWRmQ5cFhOTHJuNTJkelN5djJLOGR4MElPUmdHZk5kNTJ2amh5SWJqbmR0QUdUbnh4TjJxd0o3MDNjVmZXTmxXWWtPVWtCNVE5RFZESnBaRndrTk4xSjF3VDJLd0F6T1BNR0h2N3Rra3VQNkNlSzhGMkFmZmJ1cEVRU2JGLUdDLTVjTFk5WDI5WWtoTXZlM2R6UGQwRHM4WkN4UjY5eHN0SFdYanFQazE2aGJXZWd6OHhZMmJsT3JvQ3NodmFrYmM2b0ZnbHpuWUdZdlM0d0pEeWpOZTNQM2lYSVJiZ3ZGVzNiR1RSTGtkTURzLUtrVXBsREJPZw&file=Luca+2021+ITA+ENG+AC3+Subs+1080p+WebRip+x264+HRS+mkv)

[log.txt](https://github.com/Jackett/Jackett/files/6872271/log.txt)

**Comment by garfield69** [comment]
unfortunately the log you provided does not contain an example of the failed dl attempt so there is no clue why the indexer could not find a matching dl link to use after the downloadcheck page was fetched and the thank you was posted.

you will need to run jackett in enhanced logging until you get a dl error and then stop activity so that you do not overflow the logs and loose the event.

**Comment by gandalf764** [comment]
Ok, I thought I had "caught" the error.
At the moment that kind of error is no longer coming out, maybe it was a temporary problem, if it happens again, I'll make sure to capture it with a full log, and update this post.
For the moment, thank you very much.
