### ISSUE TITLE
[glodls] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Sapkotazz** [Jackett/Jackett#12064]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by AARON8888** [comment]
Same problem. See attached full log.
I tried also with other url site included in Jackett with same or similar problem.
[full log.txt](https://github.com/Jackett/Jackett/files/14432207/full.log.txt)

**Comment by ilike2burnthing** [comment]
Site search is down. Check the site before posting, and in future for generic issues like this open a new issue rather than resurrecting a years-long closed issue.
