### ISSUE TITLE
[New Tracker REQ] BIGTorrent

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#1206]
**Indexer Name**
BIGTorrent

**Type**
Movies, TV, Audio, Games, Software, XXX

**Indexer URL**
http://www.bigtorrent.eu/

**Indexer Language**
Hungarian

**Invite**
Registration is now open for a very limited amount of time:
http://www.bigtorrent.eu/signup.php

_Please note:_ 
Registration seems to be open only for certain countries. Europe & North America are the ones I'm sure of, so make sure your IP address is from one of the approved countries, or you won't be able to access the signup page. However, once you register, the website is open to all IPs.

**Note**
BIGTorrent is a medium-sized ratio-free Hungarian tracker with over 49K torrents.

**Comment by adamwinn** [comment]
Fixed by #1213
