### ISSUE TITLE
[req] HappyFappy

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12069]
HappyFappy https://www.happyfappy.org/ Private 3x 
ratio is based on amount DL but using the max values is probably safest, so
MR 0.5
MST 72 hours

**Comment by garfield69** [comment]
v0.18.475

**Comment by ilike2burnthing** [comment]
https://www.happyfappy.org/ - ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
https://www.happyfappy.org/torrents.php no results
forum states its being worked on

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/12069#issuecomment-1925407347

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.happyfappy.org/ Bad Gateway

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/12069#issuecomment-1925407347

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.happyfappy.org/login > We're upgrading our systems. Back shortly

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.happyfappy.org/ > DNS Lookup Error

**Comment by ilike2burnthing** [comment]
back up as https://www.happyfappy.net/ - indexers updated
