### ISSUE TITLE
[req] Haitang

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12068]
Haitang https://www.htpt.cc/ Chinese Private for Opera and Crosstalk
NexusPHP 1.0
MR 1
MST 24 hours

**Comment by garfield69** [comment]
v0.18.475

**Comment by garfield69** [comment]
https://www.htpt.cc/ cloudflare Connection timed out Error code 522

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.htpt.cc/ > cloudflare Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up
