### ISSUE TITLE
[tvvault] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by ronoray** [Jackett/Jackett#12074]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
Oh, and from previous tickets with this indexer, a dump of the browser page in action will be extremely useful.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by garfield69** [comment]
And if you can send an invite to garfieldsixtynine -at- gmail.com then this will make diagnosing the error and testing the fix so much quicker.

**Comment by j2los** [comment]
Hi, I'm not the original creator of this ticket, but I got here because of the same issue. I added the clip of my log when trying to search

[j2los_jackett_tvv_log_20210728.txt](https://github.com/Jackett/Jackett/files/6894542/j2los_jackett_tvv_log_20210728.txt)
