### ISSUE TITLE
 Unable to communicate with OxTorrent. And torrent download not possible

### ISSUE THREAD

**Issue by yoanndelattre** [Jackett/Jackett#12076]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker Linuxserver image https://hub.docker.com/r/linuxserver/jackett

**Jackett Version**: 0.18.475

**Last Working Jackett Version**: 0.18.475

**Are you using a proxy or VPN?** [yes/no] no

### Description

Jackett can no longer communicate with OxTorrent.

And downloading Torrent files from Jackett no longer works from public trackers.

### Screenshots

![image](https://user-images.githubusercontent.com/32218722/126984737-c080c572-1200-4c0c-a522-06b18a028994.png)
![image](https://user-images.githubusercontent.com/32218722/126984839-20d97a6c-34ab-4b35-af89-44ca7b116a1d.png)

**Comment by ilike2burnthing** [comment]
OxTorrent will be resolved in the next release.

Please provide an enhanced log of your failed download - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by yoanndelattre** [comment]
Here is the log file
[log.txt](https://github.com/Jackett/Jackett/files/6881246/log.txt)

**Comment by ilike2burnthing** [comment]
That's not showing any failed downloads, just successful ones.

What is happening when you try to download that you are deeming to be a failure?

Where downloads previously working?

**Comment by yoanndelattre** [comment]
Before the download works on all trackers, now they only work on private or semi private trackers.  And when I go to download a new torrent file nothing happens.  The web page is just reloaded.

**Comment by yoanndelattre** [comment]
But you can also try to reproduce the error.  Run Jackett on docker with the version of Linuxserver, add a French public tracker like GkTorrent and try to download the torrent.

**Comment by ilike2burnthing** [comment]
GkTorrent is working fine for me in my LS.io Docker Jackett container.

There is no reason why downloads would only fail for public trackers, though it could be that magnet downloads are failing, whereas .torrent downloads are fine.

Are you able to use magnet downloads from the sites directly?

**Comment by garfield69** [comment]
v0.18.481

**Comment by yoanndelattre** [comment]
For OxTorrent the problem is solved with the latest version (v0.18.481).
For the torrent file download problem, I made a private video to show you the problem.

https://www.youtube.com/watch?v=yVXbj5IqefA

**Comment by garfield69** [comment]
you problem with magnets is unlikely to have anything to do with jackett.
open your browser (the one you used to access the jackett dashboard), and navigate to https://www.oxtorrent.pe/torrent/6876/skyfall-french-hdlight-1080p-2012 scroll down to the **telecharger le torrent** 
 section and click on the **magnet link** icon.
does your browser pass the magnet to your torrent client?

**Comment by yoanndelattre** [comment]
When I go directly to the site everything works fine I can download the torrent file and use the magnet link. But I can't download anything from jackett. And when I want to download a movie from Radarr I get the following error in the logs:

![image](https://user-images.githubusercontent.com/32218722/127292226-fd1f6f21-3cbf-4a80-8d55-8a02636dfd0d.png)

**Comment by garfield69** [comment]
I give up it is out of my area of expertise. you need a docker expert or a linux one or a c# dev and that is not me.

**Comment by yoanndelattre** [comment]
But I wonder if the problem only happens to me.

**Comment by ilike2burnthing** [comment]
I'm at a loss here as well. Have you tried a local Windows install of Jackett to see if your issue is Docker-specific?

Are you using Windows 10 Pro? If so, run Windows Sandbox, install your torrent client of choice, install Jackett, and see if magnets are still affected.

**Comment by yoanndelattre** [comment]
I just tried to install Jackett with Windows Sandbox but the problem is still there. I cannot download the torrent file from Jackett.

**Comment by ilike2burnthing** [comment]
What client are you using?

**Comment by yoanndelattre** [comment]
On my seedbox I use transmission with Radarr. With Windows Sandbox I just tried to download the torrent file from Jackett, I didn't have a download client. But if I can't get the torrent file from Jackett, I can't see how it can be transmitted to the download client.

**Comment by ilike2burnthing** [comment]
It's not downloading a .torrent file, it's using a magnet link, therefore you need a torrent client installed for anything to happen. Install one in your sandbox, then install Jackett, and see if you can open it successfully.

**Comment by yoanndelattre** [comment]
I did not fully understand the principle of torrent. I thought it was necessary to download a .torrent file. I have tried installing a torrent client and Jackett in Windows Sandbox, everything works fine. This position may be closed. Thanks a lot.
