### ISSUE TITLE
Manual search not opening - Uncaught TypeError: p.nTHead is null

### ISSUE THREAD

**Issue by quickdry** [Jackett/Jackett#12088]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Mac OS client, Windows server 2012 server

**.Net Runtime**: .Net-Framework

**.Net Version**: 4.0.30319

**Jackett Version**: 0.18.496

**Last Working Jackett Version**: 0.18.496

**Are you using a proxy or VPN?** [yes/no] no

### Description

Click "manual search" in Firefox, nothing happens, error is logged in firefox console. All top row buttons have same problem (Add indexer, view cached releases), except "Test All"

Error does not happen in Chrome and Jackett UI works as expected.

### Logged Error Messages

Errors logged to FIrefox console

Uncaught TypeError: p.nTHead is null

jquery.dataTables.min.js:83:310

    jQuery 5
    updateSearchResultTable http://SERVERNAME:9117/custom.js?changed=PR11721:1210
    showSearch http://SERVERNAME:9117/custom.js?changed=PR11721:1131
    bindUIButtons http://SERVERNAME:9117/custom.js?changed=PR11721:1469

Address replaced with SERVERNAME

**Comment by garfield69** [comment]
working ok on my win10 firefox 90.0.2 (64bit)
have you tried a force-reload?
Press "Ctrl + F5" or press "Ctrl + Shift + R" (Windows,Linux)
Press "Command + Shift + R" (Mac)

**Comment by quickdry** [comment]
yes, this is on Mac Firefox. I've done force reload, and cleared cache. Also tried clearing everything via developer tools. no dice.

Found it is working in incognito/private mode but not regular mode.

**Comment by garfield69** [comment]
>Found it is working in incognito/private mode but not regular mode.

erm. going to need a specialist for this one. I've no idea what is going on or how to go about analysing this one.

**Comment by garfield69** [comment]
FWIW tested jackett 0.18.502 gui on my win10 VirtualBox BigSur image with firefox 90.0.2 and it works fine, no need for incognito mode.

**Comment by ilike2burnthing** [comment]
My guess would be your browser extensions (unless you've enabled them all to run in private windows as well). Disable them gradually and see if it has an effect.

If you track down one causing it, or one setting in one extension, or a conflict between several extensions, let us know for any future cases.
