### ISSUE TITLE
[REQ] Tracker Request - https://tamilblasters.bz/

### ISSUE THREAD

**Issue by drkathirpi** [Jackett/Jackett#12095]
contains lot of content for tamil language. kindly add it to jackett will help a lot for tamilians all over the world

**Comment by garfield69** [comment]
public forum-style site. it has no standard torrent listing search page
I think this:
https://tamilblasters.bz/index.php?/search/&q=loki&type=forums_topic&search_and_or=or&search_in=titles
is about as close as we can get to a regular torrent listing search page, we might be able to get the size off the title, but it does not have the usual seeders, leechers, flies, grabs, posters, etc

forum posts can however have many torrents for one topic, (such as the loki season one with 6 episode torrents) so this site will not be suitable for coding with a yaml indexer, it will require one written in C#.
as such I expect a very long wait time as c# dev volunteers for new c# indexers are in short supply :-(

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing

**Comment by KarthiSurfer** [comment]
mediafusion stremio addon indexes this site for content, the code is aldready there you can just use it to implement this - https://github.com/mhdzumair/MediaFusion
