### ISSUE TITLE
T411 Domain

### ISSUE THREAD

**Issue by lucasboulouys** [Jackett/Jackett#1209]
Hi 

the domain of T411 is now   T411.ai   
please change the domaine of T411.li to T411.ai

Thanks

**Comment by JigSawFr** [comment]
@lucasboulouys already done by https://github.com/Jackett/Jackett/pull/1196
Please wait a new release, you can change domain manually until update

**Comment by JigSawFr** [comment]
@lucasboulouys now fixed since https://github.com/Jackett/Jackett/releases/tag/v0.7.1207 release.
