### ISSUE TITLE
[REQ] RevolutionTT.me Tracker

### ISSUE THREAD

**Issue by slowbiz** [Jackett/Jackett#121]
I have several invites ready, I just need an email address to send them to.  I've been using RevTT for ages now and I am sad to see it hasn't been integrated yet.  I'm available to help, though I don't have much development experience.

Here's my best attempt at the category mapping:

//AddCategoryMapping("624", TorznabCatType.Console);
AddCategoryMapping("35", TorznabCatType.ConsoleNDS);
AddCategoryMapping("34", TorznabCatType.ConsolePSP);
AddCategoryMapping("40", TorznabCatType.ConsoleWii);
//AddCategoryMapping("309", TorznabCatType.ConsoleXbox);
AddCategoryMapping("39", TorznabCatType.ConsoleXbox360);
//AddCategoryMapping("307", TorznabCatType.ConsoleWiiwareVC);
AddCategoryMapping("39", TorznabCatType.ConsoleXBOX360DLC);
AddCategoryMapping("39", TorznabCatType.ConsolePS3);
//AddCategoryMapping("239", TorznabCatType.ConsoleOther);
//AddCategoryMapping("245", TorznabCatType.ConsoleOther);
//AddCategoryMapping("246", TorznabCatType.ConsoleOther);
//AddCategoryMapping("626", TorznabCatType.ConsoleOther);
//AddCategoryMapping("628", TorznabCatType.ConsoleOther);
//AddCategoryMapping("630", TorznabCatType.ConsoleOther);
AddCategoryMapping("35", TorznabCatType.Console3DS);
//AddCategoryMapping("308", TorznabCatType.ConsolePSVita);
AddCategoryMapping("40", TorznabCatType.ConsoleWiiU);
AddCategoryMapping("39", TorznabCatType.ConsoleXboxOne);
AddCategoryMapping("16", TorznabCatType.ConsolePS4);
//AddCategoryMapping("631", TorznabCatType.Movies);
//AddCategoryMapping("631", TorznabCatType.MoviesForeign);
//AddCategoryMapping("455", TorznabCatType.MoviesOther);
//AddCategoryMapping("633", TorznabCatType.MoviesOther);
AddCategoryMapping("11", TorznabCatType.MoviesSD);
AddCategoryMapping("12", TorznabCatType.MoviesHD);
//AddCategoryMapping("631", TorznabCatType.Movies3D);
AddCategoryMapping("10", TorznabCatType.MoviesBluRay);
AddCategoryMapping("20", TorznabCatType.MoviesDVD);
//AddCategoryMapping("631", TorznabCatType.MoviesWEBDL);
AddCategoryMapping("6", TorznabCatType.Audio);
AddCategoryMapping("6", TorznabCatType.AudioMP3);
AddCategoryMapping("29", TorznabCatType.AudioVideo);
AddCategoryMapping("29", TorznabCatType.AudioVideo);
//AddCategoryMapping("405", TorznabCatType.AudioAudiobook);
AddCategoryMapping("8", TorznabCatType.AudioLossless);
//AddCategoryMapping("403", TorznabCatType.AudioOther);
//AddCategoryMapping("642", TorznabCatType.AudioOther);
//AddCategoryMapping("1", TorznabCatType.AudioForeign);
AddCategoryMapping("1", TorznabCatType.PC);
AddCategoryMapping("1", TorznabCatType.PC);
//AddCategoryMapping("1", TorznabCatType.PC0day);
AddCategoryMapping("1", TorznabCatType.PCISO);
AddCategoryMapping("2", TorznabCatType.PCMac);
//AddCategoryMapping("627", TorznabCatType.PCPhoneOther);
AddCategoryMapping("4", TorznabCatType.PCGames);
//AddCategoryMapping("625", TorznabCatType.PCPhoneIOS);
//AddCategoryMapping("625", TorznabCatType.PCPhoneAndroid);
AddCategoryMapping("42", TorznabCatType.TV);
AddCategoryMapping("41", TorznabCatType.TV);
AddCategoryMapping("42", TorznabCatType.TVWEBDL);
AddCategoryMapping("41", TorznabCatType.TVWEBDL);
AddCategoryMapping("42", TorznabCatType.TVFOREIGN);
AddCategoryMapping("41", TorznabCatType.TVFOREIGN);
AddCategoryMapping("41", TorznabCatType.TVSD);
AddCategoryMapping("41", TorznabCatType.TVSD);
AddCategoryMapping("42", TorznabCatType.TVHD);
AddCategoryMapping("42", TorznabCatType.TVHD);
//AddCategoryMapping("635", TorznabCatType.TVOTHER);
//AddCategoryMapping("636", TorznabCatType.TVSport);
//AddCategoryMapping("637", TorznabCatType.TVAnime);
//AddCategoryMapping("634", TorznabCatType.TVDocumentary);
//AddCategoryMapping("1", TorznabCatType.XXX);
//AddCategoryMapping("1", TorznabCatType.XXXDVD);
//AddCategoryMapping("1", TorznabCatType.XXXWMV);
//AddCategoryMapping("1", TorznabCatType.XXXXviD);
//AddCategoryMapping("1", TorznabCatType.XXXx264);
//AddCategoryMapping("1", TorznabCatType.XXXOther);
//AddCategoryMapping("1", TorznabCatType.XXXImageset);
//AddCategoryMapping("1", TorznabCatType.XXXPacks);
//AddCategoryMapping("340", TorznabCatType.Other);
//AddCategoryMapping("342", TorznabCatType.Other);
//AddCategoryMapping("344", TorznabCatType.Other);
//AddCategoryMapping("391", TorznabCatType.Other);
//AddCategoryMapping("392", TorznabCatType.Other);
//AddCategoryMapping("393", TorznabCatType.Other);
//AddCategoryMapping("394", TorznabCatType.Other);
//AddCategoryMapping("234", TorznabCatType.Other);
//AddCategoryMapping("638", TorznabCatType.Other);
//AddCategoryMapping("629", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.OtherMisc);
//AddCategoryMapping("1", TorznabCatType.OtherHashed);
AddCategoryMapping("36", TorznabCatType.Books);
AddCategoryMapping("36", TorznabCatType.BooksEbook);
AddCategoryMapping("36", TorznabCatType.BooksComics);
AddCategoryMapping("36", TorznabCatType.BooksComics);
AddCategoryMapping("36", TorznabCatType.BooksComics);
AddCategoryMapping("36", TorznabCatType.BooksMagazines);
AddCategoryMapping("36", TorznabCatType.BooksTechnical);
AddCategoryMapping("36", TorznabCatType.BooksOther);
AddCategoryMapping("36", TorznabCatType.BooksForeign);

**Comment by JigSawFr** [comment]
@slowbiz Please add mapping in a code balise :+1:

**Comment by some-guy-23** [comment]
I'd also love to see support for this tracker, and am happy to help get it integrated by providing any info needed.

**Comment by some-guy-23** [comment]
Currently working on the Indexer class for this, I can post the code when done.

**Comment by some-guy-23** [comment]
Believe this should be all that is needed @JigSawFr , let me know if I missed anything. Like I said, I haven't tested it out yet. Hopefully @slowbiz was able to provide you with an invite for testing it  - https://gist.github.com/some-guy-23/e561c2558e5af1bbb88c

**Comment by some-guy-23** [comment]
Actually got a chance to test this out today, running into a problem with the login, the response seems to be just a page that says - "Session Timedout, work quicker next time."

Not sure if this is possibly related to the tracker using CloudFlare? Since the response seems to have a cookie with just CloudFlare info on it...

**Comment by armani316** [comment]
I see RevolutionTT on the list of supported trackers. If it's supported already, this should be closed.

**Comment by kaso17** [comment]
closing (already supported)
