### ISSUE TITLE
[1337x] Exception (1337x): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (1337x.to:443) (Test)

### ISSUE THREAD

**Issue by Bazzu85** [Jackett/Jackett#12101]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10 PRO

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Jackett Version v0.18.502

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

Testing the indexers reported the problem. Accessing via web page using the same link works..

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Can you access the site in browser? If not, try the proxies.

See also: https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

**Comment by Bazzu85** [comment]
> Can you access the site in browser? If not, try the proxies.
> 
> See also: https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

Hi, yes. As reported in description the same link using browser works..
