### ISSUE TITLE
illegal Char translation is wrong depending on the language.

### ISSUE THREAD

**Issue by ced455** [Jackett/Jackett#12105]
**Last Working Jackett Version**:

v0.18.505

### Description

When searchin for movie via radarr with title :

> Astérix & Obélix : Mission Cléopâtre

Jackett is searching  : 

> Asterix and Obelix Mission Cleopatre 2002

This return 0 results 

It does that bechause & in french mean "and" 

It should be "et". 

Am I able to change this anywhere ?

### Screenshots

When searching manualy and changing and to et i found results :
![image](https://user-images.githubusercontent.com/26870023/127647299-3401de94-aca4-4835-91eb-2e9d313287dd.png)

**Comment by ced455** [comment]
Same issue for 

" ' " transformed into nothing while a space give results

**Comment by garfield69** [comment]
>When searchin for movie via radarr with title :
>Astérix & Obélix : Mission Cléopâtre
>Jackett is searching :
>Asterix and Obelix Mission Cleopatre 2002
>This return 0 results
>It does that bechause & in french mean "and"
>It should be "et".
>Am I able to change this anywhere ?

Radarr sends Jackett the following:
http://127.0.0.1:9117/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=2000&extended=1&apikey=myapikey&offset=0&limit=100&q=Asterix%20and%20Obelix%20Mission%20Cleopatre%202002

there is nothing Jackett can do about this. Look for Radarr options or raise a request with the Radarr developers if you want to.
