### ISSUE TITLE
[yggtorrent] movie search is no longer working

### ISSUE THREAD

**Issue by almottier** [Jackett/Jackett#12100]
### Description

With Jacket v0.18.502:

```
Torznab search in YGGtorrent for Man from Earth 2007 => Found 0 release
```

With Jackett v0.18.481:

```
Torznab search in YGGtorrent for Man from Earth 2007 => Found 18 releases
```

I think the MR #12084 introduced a bug searching for movies with Radarr as it always ends with movies' year. 

The regex is wrong and should be fixed.

**Comment by ilike2burnthing** [comment]
@abdel-m Quick fix is:
`["(.*)(\\.| |\\-)(\\d{2,3})(.*)", "$1 E$3 $4"]`
`["(.*)(\\.| |\\-)(\\d{2,3})(\\.| |\\-)(.*)", "$1 E$3 $4"]`

I'd prefer this was rolled into the `enhancedAnime` config option instead though if you're up for trying that.

**Comment by damien2405** [comment]
Hello, ive the same problem. Where Can i change thé settings ? Thanks !

**Comment by garfield69** [comment]
@damien2405  if you want to apply the fix for yourself rather than wait for another 9 hours when we will publish the fix officially, then do the following:
1. shut down the Jackett service
2. edit the yggtorrent.yml (or yggcookie.yml) file with a plain text editor
3. replace line 216 for yggtorrent (or replace line 208 for yggcookie) with
```yaml
      args: ["(.*)(\\.| |\\-)(\\d{2,3})(\\.| |\\-)(.*)", "$1 E$3 $5"]
```
4. startup jackett.

**Comment by damien2405** [comment]
Hi ! @garfield69 If i need to wait few hours, then, no problem ! 

Nice work, and have a nice day !

**Comment by garfield69** [comment]
v0.18.505

**Comment by damien2405** [comment]
Hello, 

Update done. Same issue. Didnt work with the year.

**Comment by damien2405** [comment]
@almottier Work for u?

**Comment by garfield69** [comment]
working for me.
![image](https://user-images.githubusercontent.com/6933240/127623919-6ab84c6e-2a49-44fb-a6a5-61cb4383d921.png)

**Comment by damien2405** [comment]
![image](https://user-images.githubusercontent.com/88164999/127624106-51020c13-7953-4a12-ab47-f89bac44c994.png)


See ? With the same movie ? that weird

**Comment by damien2405** [comment]
![image](https://user-images.githubusercontent.com/88164999/127625315-be853102-4d41-4241-97f9-59916e431a0e.png)

**Comment by ilike2burnthing** [comment]
Open Jackett and scroll to the bottom to confirm it definitely says v0.18.505 - if not, you'll need to run the update again.

**Comment by almottier** [comment]
@damien2405 yes it is working for me with v0.18.505, thanks @garfield69

**Comment by abdel-m** [comment]
Thank you for the fix but what about anime search with ending by episode number ? Actually, it doesn't work with Boruto for exemple

**Comment by garfield69** [comment]
v0.18.537
