### ISSUE TITLE
[badasstorrents] & [rarbg] Found no results while trying to browse these trackers (sort results by seeders)

### ISSUE THREAD

**Issue by psi5asp** [Jackett/Jackett#12113]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Debian GNU/Linux 10 (buster)

**.Net Runtime**: .Net-Core

**.Net Version**:

**Jackett Version**: v0.18.515

**Last Working Jackett Version**: v0.18.515

**Are you using a proxy or VPN?** No

### Description

Failing to get any results, even if all Categories are selected when "SEARCH RESULTS BY SEEDERS" is selected.  Other search options work (Created, leechers).

This is the same failure for RARBG - when selecting "Search by Seeders". Other search options work (Created, leechers).

The websites are accessible via browser just fine, and produce results on website searches fine. The RSS feed pages also is fine. 

1337x Public _works fine_     
kickasstorrents.ws Public _works fine_
LimeTorrents Public	_works fine_
The Pirate Bay Public _works fine_
Torrent Downloads Public _works fine_

### Logged Error Messages

> | Error | System.Exception: Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 312    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
>

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![image](https://user-images.githubusercontent.com/41772110/127772164-112dd54e-7eab-4aea-a91b-c03b58970536.png)

![image](https://user-images.githubusercontent.com/41772110/127772627-df192ecd-4372-407f-868f-f25b3707289e.png)

**Comment by garfield69** [comment]
yes the badasstorrents seeders sort is in error because of an indexer typo. it is specifying `seeders` instead of `seeds`. I will fix this shortly.

**Comment by garfield69** [comment]
for RARBG we are obliged to use the provided API server and bot the web site for fetching results.
The API documentation specifies
```
Sorting :
sort parameter will sort the results by seeders,leechers,last. Default is last uploaded
mode=search&search_imdb=tt123456&sort=last&token=xxxx
```
and this does work, I have tested it. And the RARBG Jackett indexer correctly uses these parms.

However the API server is notoriously unreliable and will often return error=20 instead of results
We already have a retry in place, but sometimes this still fails to prompt a result.
There is nothing we can do from the Jackett side of the fence about this.

**Comment by garfield69** [comment]
v0.18.518 for badasstorrents fix
