### ISSUE TITLE
newstudio: download links are not working

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#12116]
search: any

**Comment by garfield69** [comment]
the download link is in the primary search page.
however some links do not deliver a .torrent file unless you are logged in.
we currently have newstudioL to provide this option.
there does not appear to be a way to detect if a login is required from the data in the search results.
its only when you get to the details page that you see the .torrent link is missing and links for 
`How to Download? · For What is a torrent? · Ratings has and Limitations` are present instead.
there is no yml fix for this, not sure how to proceed.
