### ISSUE TITLE
[REQ] Tracker request - Fantastiko.space

### ISSUE THREAD

**Issue by element4l** [Jackett/Jackett#12115]
Fantastiko is a GREEK Private Torrent Tracker for SCI-FI / FANTASY / HORROR MOVIES / TV / GENERAL
currently open registration, pending membership admin approval.
MR 1.1
MST 72hours
Powered by TSUE 2.1

**Comment by element4l** [comment]
Guys, the template is irrelevant for tracker requests. Why do you insist it's used?

**Comment by garfield69** [comment]
v0.18.518
