### ISSUE TITLE
torrenting returns error

### ISSUE THREAD

**Issue by roddyrodman** [Jackett/Jackett#1212]
hi 

if we test the torrenting setup we always get this error:

Mar 28, 2017 09:57:58 AM	Error	
Exception in test_indexer
Mar 28, 2017 09:57:58 AM	Info	
Found 0 releases from Torrenting
Mar 28, 2017 09:57:58 AM	Error	
CardigannIndexer (torrenting): Error while parsing row '<tr class="torrentsTableTR"> <td class="browse" style="padding: 0px;" align="center">
		<a onclick="change('cata=yes&amp;cat=40'); return false;" href="browse.php?cat=40">
			<img width="73" border="0" src="/pic/XXX.png" alt="XXX">			
		</a>
	</td> <td class="browse" align="left">
		<a href="details.php?id=710323" class="nameLink">PrimeCups 17 03 28 Angel Wicky And Stella Cox XXX XviD-iPT Team</a> <span style="background: #ffba25 none repeat scroll 0 0;border-radius: 3px;font-size: 11px;font-weight: bold;padding: 0px 5px; color:#000">New!</span>
		<div style="float: right;" class="uploaded">1 hour and 25 minutes ago</div>
	</td>
	<td class="browse" align="center">
		<a href="download.php/710323/PrimeCups.17.03.28.Angel.Wicky.And.Stella.Cox.XXX.XviD-iPT%20Team.torrent">
			<i class="fa fa-floppy-o fa-2x" aria-hidden="true" style="color:#000" title="Download">			</i>
		</a>
	</td>
	<td class="browse" align="center">
		<font color="#000">0</font>
	</td>
	<td class="browse" align="center">495 MB</td>
	<td class="browse" align="center">
		<b>1</b>
	</td> <td class="browse" align="center">
		<b>0</b>
	</td> </tr>':

System.Exception: Error while parsing field=leechers, selector=td:nth-child(8), value=<null>: Selector "td:nth-child(8)" didn't match <tr class="torrentsTableTR"> <td class="browse" style="padding: 0px;" align="center">
		<a onclick="change('cata=yes&amp;cat=40'); return false;" href="browse.php?cat=40">
			<img width="73" border="0" src="/pic/XXX.png" alt="XXX">			
		</a>
	</td> <td class="browse" align="left">
		<a href="details.php?id=710323" class="nameLink">PrimeCups 17 03 28 Angel Wicky And Stella Cox XXX XviD-iPT Team</a> <span style="background: #ffba25 none repeat scroll 0 0;border-radius: 3px;font-size: 11px;font-weight: bold;padding: 0px 5px; color:#000">New!</span>
		<div style="float: right;" class="uploaded">1 hour and 25 minutes ago</div>
	</td>
	<td class="browse" align="center">
		<a href="download.php/710323/PrimeCups.17.03.28.Angel.Wicky.And.Stella.Cox.XXX.XviD-iPT%20Team.torrent">
			<i class="fa fa-floppy-o fa-2x" aria-hidden="true" style="color:#000" title="Download">			</i>
		</a>
	</td>
	<td class="browse" align="center">
		<font color="#000">0</font>
	</td>
	<td class="browse" align="center">495 MB</td>
	<td class="browse" align="center">
		<b>1</b>
	</td> <td class="browse" align="center">
		<b>0</b>
	</td> </tr>
  at Jackett.Indexers.CardigannIndexer+<PerformQuery>c__async5.MoveNext () [0x01578] in <f5a0aaf923584a88a05083e6b91e2a9a>:0 

Jackett version:   0.7.1197.0
Mono version (if not using Windows):  4.6.2

-------------------------------

**Comment by adamwinn** [comment]
Fixed by #1214

**Comment by roddyrodman** [comment]
wow fast fix!!! thank you - works great now!
