### ISSUE TITLE
[yggtorrent] Connection refused (www4.yggtorrent.li:443): Connection refused (Config)

### ISSUE THREAD

**Issue by Nakda** [Jackett/Jackett#12131]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: `Linux raspberrypi 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux`

**.Net Runtime**: `Embedded I guess?`

**.Net Version**: `Embedded I guess?`

**Jackett Version**:  `v0.18.523`

**Last Working Jackett Version**: `N/A`

**Are you using a proxy or VPN?** `no`

### Description

I just installed Jackett on my system, and while trying to add the Yggtorrent indexer I got the following error message:

```
An error occurred while updating this indexer
Connection refused (www4.yggtorrent.li:443): Connection refused
Click here to open an issue on GitHub for this indexer.
```

1. Download and install latest version of Jackett on your system.
2. Access the web dashboard and try to add the Yggtorrent indexer.
3. After configuring the indexer, click `Okay`

### Logged Error Messages

[jackett_logs.txt](https://github.com/Jackett/Jackett/files/6937071/jackett_logs.txt)

### Screenshots

![image](https://user-images.githubusercontent.com/25755503/128312720-043cc1e6-c425-4cb1-bbe8-6f412c966d86.png)

![image](https://user-images.githubusercontent.com/25755503/128312744-68fb6deb-b664-4e88-b827-a048318b8903.png)

![image](https://user-images.githubusercontent.com/25755503/128312778-2ab1c2da-5c08-471a-b910-f3c4ebf4a88d.png)

**Comment by garfield69** [comment]
the indexer is working for me.
have a read of 
https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed
or
https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work-the-ssl-connection-could-not-be-established
and see if that helps you figure out what is wrong with your set up.

**Comment by garfield69** [comment]
might also want to try other public indexers, trying a mix of http ones and https to see if there is a trend.
use your browser to test the indexers site links by clinking on the indexer name on the jackett dashboard.
Using any kind of adblocking solution like pi-hole? If so, you may need to add the site to your whitelist.

**Comment by Nakda** [comment]
I completely forgot this indexer is blocked by my ISP. Changing the DNS fixed it. Thanks
