### ISSUE TITLE
[YggTorrent] new domain name

### ISSUE THREAD

**Issue by Balykoo** [Jackett/Jackett#12134]
Hello,

Ygg has just changed his domain name, this is the new one : https://www.yggtorrent.nz/

source:
![image](https://user-images.githubusercontent.com/39174035/128599052-0ceb59ec-e93b-4a91-b013-b6fcce4b5b5e.png)

Thanks for your work

**Comment by s20coeur** [comment]
yggtorrent] Found no results while trying to browse this tracker (Test) with Jacket with this new domain :( any idea ?

**Comment by garfield69** [comment]
v0.18.531

**Comment by garfield69** [comment]
https://www3.yggtorrent.nz/ returning 500 Internal Server Error

**Comment by ilike2burnthing** [comment]
back up
