### ISSUE TITLE
Issue downloading torrent from RARBG

### ISSUE THREAD

**Issue by Skelton-code** [Jackett/Jackett#12136]
Any advice?
![qBitt](https://user-images.githubusercontent.com/63185925/128620539-623761ce-8d1c-45c3-8197-525e2b567e8c.png)

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
looks like your qBt did not like the magnet .
I used my jackett rarbg indexer to search for this torrent and upon clicking the magnet button my uTorrent had no issues processing the magnet URI
Are you using the Jackett dashboard to search for the torrent and manually clicking on the magnet icon in the results page, and letting your browser pass the magnet to qBt or are you using some other method?

**Comment by vinchi007** [comment]
could have been IDS intercepted. it would be interesting to see an actual payload that was returned.
