### ISSUE TITLE
[ebookparadijs] Login failed: Selector

### ISSUE THREAD

**Issue by wonder24** [Jackett/Jackett#12159]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Asustor NAS Docker CE

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:0.17.738.r01

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]YES

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
 An error occurred while updating this indexer
Login failed: Selector "a[href="logout.php"]" didn't match
Click here to open an issue on GitHub for this indexer.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Are you using the same VPN server as Jackett when pulling your cookie?

**Comment by wonder24** [comment]
I have removed the VPN settings from My NAS and my PC and tried again, but with the same result, it is not possible to create jackett for ebookparadadijse

**Comment by wonder24** [comment]
installed  versionv0.18.613 and copied next info into the cookie

UID=422..; pass = 32 ......; ct_anti_ddos_key=d......
Use brave as browser to get the the coookie
VPN was disabled both on NAS and PC

**Comment by garfield69** [comment]
the indexer works for me on my win10
please provide an enhanced log and maybe we will get lucky and see in the debug and HTML what may be going on.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
ebookparadisj use a DDoS protection service which requires cookies to allow Jackett to access the site.
have a read of https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work in particular the Notes: section about docker.
