### ISSUE TITLE
SSL connection can't be established when adding indexer

### ISSUE THREAD

**Issue by Thumper333** [Jackett/Jackett#12151]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment 

**OS**: Ubuntu 20.04

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Fresh download

**Last Working Jackett Version**: First Install

**Are you using a proxy or VPN?** [yes/no] No

### Description

I can't seem to add an indexer.  I'm trying to add iptorrents, and when it hit the "Okay" button it fails saying that it can't make the SSL connection.  I've had SSL working before, but it's likely a system wide issue best I can tell.  I've tried to troubleshoot for days to no avail.  I can connect to the jacket gui via SSL and the cert looks valid, but maybe it's not?  Not sure where to go from here.  Help is sincerely appreciated. 

### Logged Error Messages

2021-08-05 18:28:16.7613 Error Error checking for updates.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Exception: certificate validation failed: [Subject]
  CN=*.github.com, O="GitHub, Inc.", L=San Francisco, S=California, C=US

[Issuer]
  CN=DigiCert High Assurance TLS Hybrid ECC SHA256 2020 CA1, O="DigiCert, Inc.", C=US

[Serial Number]
  0168D575F1CE8728AD95A8F11EF1598B

[Not Before]
  3/24/2021 6:00:00 PM

[Not After]
  3/30/2022 5:59:59 PM

[Thumbprint]
  968407DF0B1CF65814DFD7333557519B154D8CE7

   at Jackett.Common.Utils.Clients.HttpWebClient2.ValidateCertificate(HttpRequestMessage request, X509Certificate2 certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 50
   at System.Net.Http.ConnectHelper.<>c__DisplayClass3_0.<EstablishSslConnectionAsync>b__0(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertificateValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
   at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 185
   at Jackett.Common.Services.UpdateService.CheckForUpdates() in /home/vsts/work/1/s/src/Jackett.Common/Services/UpdateService.cs:line 106
2021-08-06 18:28:16.7754 Info Checking for updates... Jackett variant: CoreLinuxAmdx64
2021-08-06 18:28:17.2294 Error Error checking for updates.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by Thumper333** [comment]
I couldn't figure out how to try the site on the same machine.  It's headless, command line only, and I would need to test under the same user which is specifically set up for anything that I only want to access the internet via a VPN.  That user doesn't have a login, so I can't login as them and ping something.  

I tried pinging https://iptorrents.com from another machine which can access the site fine, and it can't ping that site when I have the https on it.   So the fact that it's failing a ping doesn't tell me anything.  Any thoughts on another way to test from that same machine?

**Comment by Thumper333** [comment]
I found a big clue... I just realized that even thought I can access jacket and all my other sites from a browser while on my network, I can't access any of them when I'm outside the network.  I have a hunch that my port forwarding is not working for some reason.  It's an asus router and I'm pretty sure I have them set up properly, in fact I'm pretty sure it used to work fine.  Is there a program that will tell me (or some other way to know) if my requests are being blocked by the router, firewall, or how far they're makking it?  I've heard of wireshark, but never used it.  Will that do it?

**Comment by ilike2burnthing** [comment]
Is this device on your local network?

Is Jackett's data going through the VPN?

Easiest way to test if your hardware firewall is the issue is to put the device concerned into the DMZ and test again. If everything then works, you've found your problem and you need to check your port forwarding.

**Comment by Thumper333** [comment]
okay, I did make a little headway but still haven't fixed the issue.  

I found that my vpn split tunneling wasn't working properly and now have that resolved.  The port forwarding is fixed as well.  

I can access the server from outside my network.  

Jacket's data is going through a vpn split tunnel based on the user.  The vpn user and group have ownership of jackett.  

I'm still getting a cookie / SSL error when trying to add iptorrents. 

![image](https://user-images.githubusercontent.com/26166649/129410379-671bb064-f35d-4996-9c9e-c592aae6c6b1.png)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work-the-ssl-connection-could-not-be-established

**Comment by Thumper333** [comment]
I can't remember what exact download I used to do the installation.  How do I know if I'm a "mono user".  I know I have mono installed and used it for other apps, but I don't know for sure if I'm using it here.

**Comment by garfield69** [comment]
@Thumper333  Start up Jackett and then access the Jackett dashboard and look at the first 10 lines or so.
there should be a reference to mono, I think its in the `Jackett variant:` message.
Or just paste that log snippet here and we can take a look and see if we can figure it out.

**Comment by Thumper333** [comment]
Here is the startup info.  It doesn't look like mono....

<html>
<body>


2021-08-22 01:03:23 | Info | Using HTTP Client: HttpWebClient2
-- | -- | --
2021-08-22 01:03:23 | Info | Using FlareSolverr: No
2021-08-22 01:03:23 | Info | Using proxy: Disabled
2021-08-22 01:03:23 | Info | App config/log directory: /home/vpn/.config/Jackett
2021-08-22 01:03:23 | Info | ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-08-22 01:03:23 | Info | Running in Docker: No
2021-08-22 01:03:23 | Info | File /etc/issue: Ubuntu 20.04.3 LTS \n \l
2021-08-22 01:03:23 | Info | Jackett variant: CoreLinuxAmdx64
2021-08-22 01:03:23 | Info | OS version: Unix 5.4.0.81 (64bit OS) (64bit process)
2021-08-22 01:03:23 | Info | Environment version: 5.0.8 (/opt/Jackett/)
2021-08-22 01:03:20 | Info | Starting Jackett v0.18.441


</body>
</html>

Maybe more helpful is a snippet of an error log when it's trying to update.  It looks to me like it's trying to use an incorrect SSL cert.  I'm not sure how to read that, or how it is even set up, but I do have an SSL cert for my domain that I just renewed.  I had issues renewing it at first, but eventually was able to get it renewed.  I had found that all of my outgoing traffic was sent to the VPN, so my cert wouldnt' authenticate.  I'm definitely intending to send my outbound traffic through my vpn for jackett, is there something special I have to do for my cert to carry the original ip so it matches the cert?   ...or something like that?  just brainstorming.  

Here is the latest error log, from when jackett tries to update.  Notice that the cert says something about github.  I wonder if it has the wrong cert, or that's a default, or something odd like that.  How can I tell jacket what cert to use?

![Screenshot 2021-08-23 163301](https://user-images.githubusercontent.com/26166649/130527942-d5e24d07-41a9-4e77-928a-8fbf7697606a.png)

**Comment by garfield69** [comment]
your Jackett CoreLinuxAmdx64 is not using mono, its a .NET variant.
you don't tell Jackett what CA to use, that comes from the site you are contacting.
yes, so the Jackett updater tries to fetch the latest update package from our github repository at https://api.github.com/repos/Jackett/Jackett/releases which has a  CA forwith a  thumbprint of 968407DF0B1CF65814DFD7333557519B154D8CE7
which matches the thumbprint in your first post.

so the issue is not that you are getting an invalid CA, but that your platform for whatever reason, is unable to process that    CA correctly.

the error states that the inner exception contains the reason for the CA failure, but I cant interpret that stack trace to determine that the reason for the error is. @ilike2burnthing  can you see in the inner exception stack trace a pointer to a reason?

Does this linux user have to update or degrade their version of OpenSSL perhaps?

**Comment by ilike2burnthing** [comment]
No, it's just as unclear to me. OpenSSL seems like a good next step.

If that doesn't work, I'd suggest trying Jackett without the VPN to see if that's causing the issue.

**Comment by Thumper333** [comment]
I'm looking for an OpenSSL specific log and I can't seem to find anything.  What log should I be looking for, and where would it be?  

I'm not sure if this helps, but here is my openssl config file in case there is anything glaring there.  I read through and the only thing I can see is that it all looks generic.  Does it need location information filled in a such in the [ req_distinguished_name ] section?

Below is the output from:   /usr/lib/ssl$ cat openssl.cnf 

`# Note that you can include other files from the main configuration
# file using the .include directive.
#.include filename

# This definition stops the following lines choking if HOME isn't
# defined.
HOME                    = .

# Extra OBJECT IDENTIFIER info:
#oid_file               = $ENV::HOME/.oid
oid_section             = new_oids

# To use this configuration file with the "-extfile" option of the
# "openssl x509" utility, name here the section containing the
# X.509v3 extensions to use:
# extensions            =
# (Alternatively, use a configuration file that has only
# X.509v3 extensions in its main [= default] section.)

[ new_oids ]

# We can add new OIDs in here for use by 'ca', 'req' and 'ts'.
# Add a simple OID like this:
# testoid1=1.2.3.4
# Or use config file substitution like this:
# testoid2=${testoid1}.5.6

# Policies used by the TSA examples.
tsa_policy1 = 1.2.3.4.1
tsa_policy2 = 1.2.3.4.5.6
tsa_policy3 = 1.2.3.4.5.7

####################################################################
[ ca ]
default_ca      = CA_default            # The default ca section

####################################################################
[ CA_default ]

dir             = ./demoCA              # Where everything is kept
certs           = $dir/certs            # Where the issued certs are kept
crl_dir         = $dir/crl              # Where the issued crl are kept
database        = $dir/index.txt        # database index file.
#unique_subject = no                    # Set to 'no' to allow creation of
                                        # several certs with same subject.
new_certs_dir   = $dir/newcerts         # default place for new certs.

certificate     = $dir/cacert.pem       # The CA certificate
serial          = $dir/serial           # The current serial number
crlnumber       = $dir/crlnumber        # the current crl number
                                        # must be commented out to leave a V1 CRL
crl             = $dir/crl.pem          # The current CRL
private_key     = $dir/private/cakey.pem# The private key

x509_extensions = usr_cert              # The extensions to add to the cert

# Comment out the following two lines for the "traditional"
# (and highly broken) format.
name_opt        = ca_default            # Subject Name options
cert_opt        = ca_default            # Certificate field options

# Extension copying option: use with caution.
# copy_extensions = copy

# Extensions to add to a CRL. Note: Netscape communicator chokes on V2 CRLs
# so this is commented out by default to leave a V1 CRL.
# crlnumber must also be commented out to leave a V1 CRL.
# crl_extensions        = crl_ext

default_days    = 365                   # how long to certify for
default_crl_days= 30                    # how long before next CRL
default_md      = default               # use public key default MD
preserve        = no                    # keep passed DN ordering

# A few difference way of specifying how similar the request should look
# For type CA, the listed attributes must be the same, and the optional
# and supplied fields are just that :-)
policy          = policy_match

# For the CA policy
[ policy_match ]
countryName             = match
stateOrProvinceName     = match
organizationName        = match
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

# For the 'anything' policy
# At this point in time, you must list all acceptable 'object'
# types.
[ policy_anything ]
countryName             = optional
stateOrProvinceName     = optional
localityName            = optional
organizationName        = optional
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

####################################################################
[ req ]
default_bits            = 2048
default_keyfile         = privkey.pem
distinguished_name      = req_distinguished_name
attributes              = req_attributes
x509_extensions = v3_ca # The extensions to add to the self signed cert

# Passwords for private keys if not present they will be prompted for
# input_password = secret
# output_password = secret

# This sets a mask for permitted string types. There are several options.
# default: PrintableString, T61String, BMPString.
# pkix   : PrintableString, BMPString (PKIX recommendation before 2004)
# utf8only: only UTF8Strings (PKIX recommendation after 2004).
# nombstr : PrintableString, T61String (no BMPStrings or UTF8Strings).
# MASK:XXXX a literal mask value.
# WARNING: ancient versions of Netscape crash on BMPStrings or UTF8Strings.
string_mask = utf8only

# req_extensions = v3_req # The extensions to add to a certificate request

[ req_distinguished_name ]
countryName                     = Country Name (2 letter code)
countryName_default             = AU
countryName_min                 = 2
countryName_max                 = 2

stateOrProvinceName             = State or Province Name (full name)
stateOrProvinceName_default     = Some-State

localityName                    = Locality Name (eg, city)

0.organizationName              = Organization Name (eg, company)
0.organizationName_default      = Internet Widgits Pty Ltd

# we can do this but it is not needed normally :-)
#1.organizationName             = Second Organization Name (eg, company)
#1.organizationName_default     = World Wide Web Pty Ltd

organizationalUnitName          = Organizational Unit Name (eg, section)
#organizationalUnitName_default =

commonName                      = Common Name (e.g. server FQDN or YOUR name)
commonName_max                  = 64

emailAddress                    = Email Address
emailAddress_max                = 64

# SET-ex3                       = SET extension number 3

[ req_attributes ]
challengePassword               = A challenge password
challengePassword_min           = 4
challengePassword_max           = 20

unstructuredName                = An optional company name

[ usr_cert ]

# These extensions are added when 'ca' signs a request.

# This goes against PKIX guidelines but some CAs do it and some software
# requires this to avoid interpreting an end user certificate as a CA.

basicConstraints=CA:FALSE

# Here are some examples of the usage of nsCertType. If it is omitted
# the certificate can be used for anything *except* object signing.

# This is OK for an SSL server.
# nsCertType                    = server

# For an object signing certificate this would be used.
# nsCertType = objsign

# For normal client use this is typical
# nsCertType = client, email

# and for everything including object signing:
# nsCertType = client, email, objsign

# This is typical in keyUsage for a client certificate.
# keyUsage = nonRepudiation, digitalSignature, keyEncipherment

# This will be displayed in Netscape's comment listbox.
nsComment                       = "OpenSSL Generated Certificate"

# PKIX recommendations harmless if included in all certificates.
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid,issuer

# This stuff is for subjectAltName and issuerAltname.
# Import the email address.
# subjectAltName=email:copy
# An alternative to produce certificates that aren't
# deprecated according to PKIX.
# subjectAltName=email:move

# Copy subject details
# issuerAltName=issuer:copy

#nsCaRevocationUrl              = http://www.domain.dom/ca-crl.pem
#nsBaseUrl
#nsRevocationUrl
#nsRenewalUrl
#nsCaPolicyUrl
#nsSslServerName

# This is required for TSA certificates.
# extendedKeyUsage = critical,timeStamping

[ v3_req ]

# Extensions to add to a certificate request

basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment

[ v3_ca ]


# Extensions for a typical CA


# PKIX recommendation.

subjectKeyIdentifier=hash

authorityKeyIdentifier=keyid:always,issuer

basicConstraints = critical,CA:true

# Key usage: this is typical for a CA certificate. However since it will
# prevent it being used as an test self-signed certificate it is best
# left out by default.
# keyUsage = cRLSign, keyCertSign

# Some might want this also
# nsCertType = sslCA, emailCA

# Include email address in subject alt name: another PKIX recommendation
# subjectAltName=email:copy
# Copy issuer details
# issuerAltName=issuer:copy

# DER hex encoding of an extension: beware experts only!
# obj=DER:02:03
# Where 'obj' is a standard or added object
# You can even override a supported extension:
# basicConstraints= critical, DER:30:03:01:01:FF

[ crl_ext ]

# CRL extensions.
# Only issuerAltName and authorityKeyIdentifier make any sense in a CRL.

# issuerAltName=issuer:copy
authorityKeyIdentifier=keyid:always

[ proxy_cert_ext ]
# These extensions should be added when creating a proxy certificate

# This goes against PKIX guidelines but some CAs do it and some software
# requires this to avoid interpreting an end user certificate as a CA.

basicConstraints=CA:FALSE

# Here are some examples of the usage of nsCertType. If it is omitted
# the certificate can be used for anything *except* object signing.

# This is OK for an SSL server.
# nsCertType                    = server

# For an object signing certificate this would be used.
# nsCertType = objsign

# For normal client use this is typical
# nsCertType = client, email

# and for everything including object signing:
# nsCertType = client, email, objsign

# This is typical in keyUsage for a client certificate.
# keyUsage = nonRepudiation, digitalSignature, keyEncipherment

# This will be displayed in Netscape's comment listbox.
nsComment                       = "OpenSSL Generated Certificate"

# PKIX recommendations harmless if included in all certificates.
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid,issuer

# This stuff is for subjectAltName and issuerAltname.
# Import the email address.
# subjectAltName=email:copy
# An alternative to produce certificates that aren't
# deprecated according to PKIX.
# subjectAltName=email:move

# Copy subject details
# issuerAltName=issuer:copy

#nsCaRevocationUrl              = http://www.domain.dom/ca-crl.pem
#nsBaseUrl
#nsRevocationUrl
#nsRenewalUrl
#nsCaPolicyUrl
#nsSslServerName

# This really needs to be in place for it to be a proxy certificate.
proxyCertInfo=critical,language:id-ppl-anyLanguage,pathlen:3,policy:foo

####################################################################
[ tsa ]

default_tsa = tsa_config1       # the default TSA section

[ tsa_config1 ]

# These are used by the TSA reply generation only.
dir             = ./demoCA              # TSA root directory
serial          = $dir/tsaserial        # The current serial number (mandatory)
crypto_device   = builtin               # OpenSSL engine to use for signing
signer_cert     = $dir/tsacert.pem      # The TSA signing certificate
                                        # (optional)
certs           = $dir/cacert.pem       # Certificate chain to include in reply
                                        # (optional)
signer_key      = $dir/private/tsakey.pem # The TSA private key (optional)
signer_digest  = sha256                 # Signing digest to use. (Optional)
default_policy  = tsa_policy1           # Policy if request did not specify it
                                        # (optional)
other_policies  = tsa_policy2, tsa_policy3      # acceptable policies (optional)
digests     = sha1, sha256, sha384, sha512  # Acceptable message digests (mandatory)
accuracy        = secs:1, millisecs:500, microsecs:100  # (optional)
clock_precision_digits  = 0     # number of digits after dot. (optional)
ordering                = yes   # Is ordering defined for timestamps?
                                # (optional, default: no)
tsa_name                = yes   # Must the TSA name be included in the reply?
                                # (optional, default: no)
ess_cert_id_chain       = no    # Must the ESS cert id chain be included?
                                # (optional, default: no)
ess_cert_id_alg         = sha1  # algorithm to compute certificate
                                # identifier (optional, default: sha1)
`

**Comment by ilike2burnthing** [comment]
@Commissar0617 see https://github.com/Jackett/Jackett/issues/12341

**Comment by garfield69** [comment]
closing as stale
