### ISSUE TITLE
[nyaasi] Manual search shows duplicate results

### ISSUE THREAD

**Issue by pkreuzt** [Jackett/Jackett#12161]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Debian 11 Bullseye ARM64

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] .Net-Core

**.Net Version**: 

**Jackett Version**:  v0.18.541

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] No

### Description

Using manual search on this tracker yields duplicate results. This happens only for this site.

### Logged Error Messages

No error messages, just normal ones:

2021-08-13 21:57:21.5358 Info Manual search in nyaasi for test => Found 150 releases (from cache) 

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![2021-08-13-215941_934x967_scrot](https://user-images.githubusercontent.com/6936840/129412352-cbfd6181-4c35-4183-9bca-edc9a0833bf3.png)

**Comment by garfield69** [comment]
this is a direct result of #11019 and is expected.
@ilike2burnthing  anything to add?

**Comment by ilike2burnthing** [comment]
Nope.
