### ISSUE TITLE
[New Tracker Request] PSArips

### ISSUE THREAD

**Issue by rob1998** [Jackett/Jackett#1216]
website: ~~http://psarips.com~~ ~~https://psarips.org/~~ https://psa.pm/
This is a really hard one, since they don't provide an rss feed with magnet links.
It's a really nice release group because they provide high quality x265 movies and tv shows.

if it's not possible: is it possible to create a new tracker for ThePirateBay/KickAssTorrents search results (for example "psa 1080p")?

**Comment by RoloSoze** [comment]
@rob1998 Is this a torrent tracker or a direct download website?

Also, Jackett already supports both TBP & KAT. Can't you just search these two trackers in Jackett for PSA releases?

**Comment by JigSawFr** [comment]
@RoloSoze It's a direct download site
@rob1998 sorry, Jackett implement only torrents trackers

**Comment by rob1998** [comment]
@RoloSoze it's both, you can download the torrent or direct download the file, but you download .torrent files and their locations (url) can only be accessed after seeing an ad and solving a captcha.
I know I can search for PSA releases but I want to search in the psa releases, let me explain:
I'm using Jackett in combination with Sonarr. Let's say I want the newest episode of Game of Thrones. Sonarr looks for it in an indexer from jackett, which is already filtered for PSA files.

**Comment by JigSawFr** [comment]
@rob1998 my bad, i've just seen that there is also some torrents files, but i doubt that site will be incorporated in the future, as Jackett need to follow a redirector & solve a captcha.

**Comment by rob1998** [comment]
that's what I thought, because of that I asked for the possibility to create a second indexer for tpb or kat with an extra filter on it for psa, because most of psa's files are on tpb/kat.
But I'm a programmer myself, so I knew it was not the easiest thing to do.

**Comment by JigSawFr** [comment]
@rob1998 I think filtering results must be done in apps which use Jackett, for example Sonarr with a required word "PSA".

**Comment by rob1998** [comment]
Yeah, problem with that is that if it's required and an episode is not released by psa it won't automatically download it, but I think I have to wait untill the preferred option from Radarr is implemented in Sonarr, cause then it would work.

**Comment by cjLGH** [comment]
@rob1998 as @JigSawFr has mentioned about "filtering results." I currently have an RSS indexer in Sonarr that searches for PSA using the following. Haven't had many RSS Sync issues with obtaining PSARips, but you will need to create an RSS indexer in Sonarr per Jackett indexer. * Unless there is a way to perform an all tracker search as performed in Jacketts manual search.

> http://localhost:9117/jackett/api/v2.0/indexers/INDEXER/results/torznab/api?apikey=APIKEY&t=search&cat=&q=PSA

**Comment by kaso17** [comment]
@cjLGH there's an "all" indexer which you can use but I still recommend to use individual indexers instead of all.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/5127#issue-437367989

**Comment by garfield69** [comment]
this site does not returns results in a one-title-one torrent format.
search results for a title require accessing the torrent details page, where one or more torrent links are available.
as such this site is not suitable for processing by the Cardigann yaml engine.
an indexer for this site will have to be coded in C#.

**Comment by hannsen** [comment]
This site would be problematic. 

The search only works for the title, e.g. "Ford v Ferrari (2019)", but the actual release title which you want to show the user in the end ("Ford.V.Ferrari.2019.720p.WEBRip.2CH.x265.HEVC-PSA") cannot be searched. So there would be a disconnect between what the user searches and what they get as a result.

This site is actually a lot like a [Gazelle](https://github.com/WhatCD/Gazelle) tracker, having a group page and many releases on that page. Main difference being that you cannot search for single release names, just group names.

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing

**Comment by zzzealed** [comment]
Use idope(.se) tracker instead. They reupload the PSA torrents.

**Comment by dtristany** [comment]
idope.se is gone
I believe Jackett could bypass all the ads and captchas by setting an accessibility cookie and using this script https://github.com/cyan-n1d3/PSAbypass
