### ISSUE TITLE
[1337x] Exception (1337x): failed (Error 522) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by MaddDogg98** [Jackett/Jackett#12160]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Win 10 Pro

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] .NET-Framwork

**.Net Version**: 4.8.04084

**Jackett Version**: v0.18.539

**Last Working Jackett Version**: v0.18.538

**Are you using a proxy or VPN?** [yes/no] Yes

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Jackett appears to be using https://1377x.to/cat/Movies/time/desc/1/ when the new URL after going to 1377x website is https://www.1377x.to/cat/Movies/time/desc/1/

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
1377x is a fake copy of 1337x

Change the sitelink back and it should work. If not, try one of the proxies.

**Comment by MaddDogg98** [comment]
i have not changed the settings on Jackett. I guess they are just down right now. This is what loaded when I clicked on 1337x in Jackett. 
![image](https://user-images.githubusercontent.com/22988798/129373723-3667b169-8cdb-40b7-8f04-3a8ce78fbd8a.png)

**Comment by MaddDogg98** [comment]
![image](https://user-images.githubusercontent.com/22988798/129380714-fa4837bd-9855-4d0e-87e7-8b262b0a785b.png)
this is a screenshot of what Jackett says after testing the connection

**Comment by ilike2burnthing** [comment]
Then you aren't using 1377x as you previously linked to and the site is just down.
