### ISSUE TITLE
Permanent word added

### ISSUE THREAD

**Issue by elpedriyo** [Jackett/Jackett#12166]
Hello,

I am used to do my personal replaces on hdolimpo.yml, for making radarr work correctly with HDO.
Now I am facing the issue, radarr is identifying a % of the movies in other languages, while that tracker is 100% spanish. I am aiming to force SPANISH word on all title movies, but I can see only the re_replace option on the yml file, is there anyway I can force that word at the name of all searches?

Kind regards

**Comment by garfield69** [comment]
you could add your word at the end of the title with
```yaml
        - name: append
          args: "SPANISH "
```
