### ISSUE TITLE
[newpct] The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject]  CN=pctmix.com[Issuer]  CN=

### ISSUE THREAD

**Issue by xeviff** [Jackett/Jackett#12164]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment
Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
v0.18.541

**Last Working Jackett Version**:

** steps
Add newpct indexer

**Are you using a proxy or VPN?** [yes/no]
no
### Description
 An error occurred while configuring this indexer
The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject] CN=pctmix.com [Issuer] CN="allot.com/emailAddress=info@allot.com", OU=Allot, O=Allot, L=Madrid, S=Madrid, C=ES [Serial Number] 69FE0E6100000000E600000000000000 [Not Before] 12/16/2016 2:07:49 PM [Not After] 12/16/2026 2:07:49 PM [Thumbprint] 867929DA01A1FFAF09218731BC53EB4AFC774921

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots
![image](https://user-images.githubusercontent.com/73612508/129453776-60fc1603-6000-44c2-8173-ff9b2b21361e.png)

[Place any screenshots of the issue here if needed]

**Comment by xeviff** [comment]
hi, I'm sorry.
I edited the message few seconds later and provided the further information

**Comment by garfield69** [comment]
the official certificate from pctmix.com is issued from cloudflare with a thumbprint of cb557df2e532723973ec19c86439727dcac9cbef
the one you are getting came from allot with a thumbprint of 867929DA01A1FFAF09218731BC53EB4AFC774921

your ISP is blocking your access to the newpct site.
Have a read of https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed any try out some of the options to resolve your issue.
