### ISSUE TITLE
[exttorrents] Exception (exttorrents): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by Hotrod369** [Jackett/Jackett#12176]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: [Windows 10 Home]

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] 

**.Net Version**:[.NET 5.0]

**Jackett Version**:[Version v0.18.547]

**Last Working Jackett Version**: [First Install]

**Are you using a proxy or VPN?** [yes/no] [VPN Y]

### Description [[exttorrents] Exception (exttorrents): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)]

[List steps to reproduce the error and details on what happens and what you expected to happen]
Got this error after adding EXT Torrents

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots
![image](https://user-images.githubusercontent.com/72291352/129727555-fcb946d9-75c6-4cff-a86c-90862c6523e0.png)
![image](https://user-images.githubusercontent.com/72291352/129727697-b66fec04-ac37-4ee7-86ba-6e3a407267b9.png)

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured

however, in this case flaresolverr is not going to help because EXT are using cloudflares Hcaptcha for which there is no current automated solcution.
So until EXT lift their DDoS protection you will just have to use the EXT web site manually or use another public jackett indexer.
