### ISSUE TITLE
[REQ] New private Italian tracker http://www.icv-crew.com/forum/index.php?action=forum

### ISSUE THREAD

**Issue by Zhoth** [Jackett/Jackett#12177]
Hi guys, there is a very good private (it requires only a registration) Italian tracker that would be nice to have:  
`http://www.icv-crew.com/forum/index.php?action=forum`
It has a forum style with different sections for movies, tv series, anime, music and so on based on their quality.

If it's useful, it has a global RSS feed: `https://www.icv-crew.com/forum/index.php?type=rss;action=.xml `

Thanks a lot for your work!

**Comment by garfield69** [comment]
duplicate of #3189
