### ISSUE TITLE
Feature request: HTTP "keep alive" login facility

### ISSUE THREAD

**Issue by DarrenPIngram** [Jackett/Jackett#12187]
FEATURE REQUEST FOR ALL PLATFORMS ETC.

Would you consider the following feature?

Situation: Many trackers require a login and keep an account only valid for a certain time IF no logins are made. The use of the application can mean that one often doesn't log into all trackers installed, especially if they are viewed as "secondary" venues.

Proposal: A button (to fire off) and/or automatic option set on a preference (every X days) that would OPEN in a browser (new tabs) all of the stored trackers, using credentials provided (if ordinarily it does not log in with the same web credentials then offer a place to save the credentials).

Benefit: Trackers remain enabled, even if one was forgetful or even sick.

**Comment by garfield69** [comment]
do you know that if you use the TESTALL button on the dashboard you are effectively performing a keyword-less search on all your active indexers, and for those whose session cookies are expired the indexer will login again?
For any indexers that fail the login (whether it be due to DDoS checking, or other login simple captchas and so forth), the test will fail so that would be the time to edit the relevant configs and revalidate your credentials.

I am not suggesting your enhancement is not practical or possible (I will leave that to other members with more knowledge of C# and app design), but I wondered if the above might partially meet your request.

**Comment by DarrenPIngram** [comment]
Thanks. I didn't know that. I was under the impression that trackers only
counted HTTPS logins rather than just API or cookie access, but I don't
proclaim to be an expert. My proposal would be a preference option (I
forsee) and, of course, be automated to stop the user forgetting...



‌

**Comment by ilike2burnthing** [comment]
You could use something like Sonarr to automate this, or schedule a script to run every X hours/days, seems unnecessary to add it to Jackett. Is there something I'm missing that wouldn't be covered by these alternatives?

**Comment by DarrenPIngram** [comment]
Thanks for the response. Maybe I am missing the idea in Sonarr, but I thought it only automatically checks the trackers on a search (but is that enough to keep an account live, e.g. API access instead of HTTP login?). As for writing a script to open lots of web pages, enter credentials, wait and close sounds rather complex for a non-programmer. If the feature was in Jackett it could also perhaps contribute to the healthcare checking in some way (at least the trackers would continue to work, as the account wouldn't be closed!).

**Comment by ilike2burnthing** [comment]
By default Sonarr will run a keywordless search for each indexer every 15mins (the timing can be changed), which will basically do the same as the `Test` function in Jackett - run a search and relogin if needed.

The suggestion of scheduling a script was in reference to Jackett, essentially doing the same as Sonarr (making a call to Jackett's API every X hours for each indexer), not setting up something completely from scratch.

Jackett never make requests to trackers on its own, it either has to be done manually (configuration, search, or test) or using automation software such as Sonarr.

**Comment by DarrenPIngram** [comment]
OK thank you. I was not aware of that behaviour in Sonarr. I use both Sonarr and Jackett in any case, so my "problem" can be managed well. I appreciate your assistance and clarification.
