### ISSUE TITLE
Add Indexer Blank Ubuntu Ver 0.7.1225

### ISSUE THREAD

**Issue by H4ckey** [Jackett/Jackett#1218]
Mono JIT compiler version 4.2.1 

Jackett Version 0.7.1225.0

Add indexer shows the following:

![image](https://cloud.githubusercontent.com/assets/24574362/24435217/87807950-1490-11e7-8f43-11030d41cf9f.png)

Started doing it after a update from 0.7.806(or 896 or something)

**Comment by RoloSoze** [comment]
@H4ckey Try upgrading Mono to the latest version. Does it solve the issue?

**Comment by kaso17** [comment]
looks like a caching issue,try cleaning you cache.

**Comment by flightlevel** [comment]
re-open if still an issue
