### ISSUE TITLE
[erai-raws] not able to process RSS data from site

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12183]
the erai-raws indexer is returning 0 results.
the log is full of the following warnings:
```
2021-08-19 08:35:01 Warn  Could not parse Erai-Raws RSS item '[Magnet]Shin Chuuka Ichiban! - 01 ~ 12 [1080p][us][br][mx][es][sa][fr][de][it][ru][Batch]magnet:?xt=urn:btih:3fc6831036b3fc6a15970ebbd6bcc9e31a6d90cd&dn=%5BErai-raws%5D%20Shin%20Chuuka%20Ichiban%21%20-%2001%20~%2012%20%5B1080p%5D%5BMultiple%20Subtitle%5D&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=http%3A%2F%2Fanidex.moe%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.anirena.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=http%3A%2F%2Fopen.acgnxtracker.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2820%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2980%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fretracker.lanta-net.ru%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.acgnx.se%2FannounceMon, 16 Aug 2021 00:57:44 +00001080pMagnet16.56GB3fc6831036b3fc6a15970ebbd6bcc9e31a6d90cd[us][br][mx][es][sa][fr][de][it][ru][Batch]<a href="https://beta.erai-raws.info/batches/shin-chuuka-ichiban-01-12/">[Erai-raws] Shin Chuuka Ichiban! - 01 ~ 12 [1080p][Multiple Subtitle]</a> \| Subtitles: [us][br][mx][es][sa][fr][de][it][ru]  \| Size: 16.56GB \| InfoHash: 3fc6831036b3fc6a15970ebbd6bcc9e31a6d90cd \| Categories: [Batch] '
```
@6cUbi57z as the last volunteer to contribute a PR for this indexer, would you be able to take a look please?
Thanks.

**Comment by garfield69** [comment]
v0.18.563

**Comment by garfield69** [comment]
Darn. Looks like there has been another change to the RSS feed.
The erai-raws indexer is returning 0 results with the logs showing
```
Could not parse Erai-Raws RSS item '[Magnet]Shin Chuuka Ichiban! - 01 ~ 12 [720p][us][br][mx][es][sa][fr][de][it][ru][Batch]magnet:?xt=urn:btih:0b2c4b0e53a544baea803c6fc1f1b7678114e3b0&dn=%5BErai-raws%5D%20Shin%20Chuuka%20Ichiban%21%20-%2001%20~%2012%20%5B720p%5D%5BMultiple%20Subtitle%5D&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=http%3A%2F%2Fanidex.moe%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.anirena.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=http%3A%2F%2Fopen.acgnxtracker.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2820%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2980%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fretracker.lanta-net.ru%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.acgnx.se%2FannounceMon, 16 Aug 2021 00:57:44 +0000720pMagnet8.41GB0b2c4b0e53a544baea803c6fc1f1b7678114e3b0[us][br][mx][es][sa][fr][de][it][ru][Batch]<a href="https://beta.erai-raws.info/batches/shin-chuuka-ichiban-01-12/">[Erai-raws] Shin Chuuka Ichiban! - 01 ~ 12 [720p][Multiple Subtitle]</a> \| Subtitles: [us][br][mx][es][sa][fr][de][it][ru]  \| Size: 8.41GB \| InfoHash: 0b2c4b0e53a544baea803c6fc1f1b7678114e3b0 \| Categories: [Batch] '
```
@6cUbi57z  would you be so kind as to investigate? Thanks.

**Comment by 6cUbi57z** [comment]
> Darn. Looks like there has been another change to the RSS feed.
> The erai-raws indexer is returning 0 results with the logs showing
> 
> ```
> Could not parse Erai-Raws RSS item '[Magnet]Shin Chuuka Ichiban! - 01 ~ 12 [720p][us][br][mx][es][sa][fr][de][it][ru][Batch]magnet:?xt=urn:btih:0b2c4b0e53a544baea803c6fc1f1b7678114e3b0&dn=%5BErai-raws%5D%20Shin%20Chuuka%20Ichiban%21%20-%2001%20~%2012%20%5B720p%5D%5BMultiple%20Subtitle%5D&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=http%3A%2F%2Fanidex.moe%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.anirena.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=http%3A%2F%2Fopen.acgnxtracker.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2820%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2980%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fretracker.lanta-net.ru%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.acgnx.se%2FannounceMon, 16 Aug 2021 00:57:44 +0000720pMagnet8.41GB0b2c4b0e53a544baea803c6fc1f1b7678114e3b0[us][br][mx][es][sa][fr][de][it][ru][Batch]<a href="https://beta.erai-raws.info/batches/shin-chuuka-ichiban-01-12/">[Erai-raws] Shin Chuuka Ichiban! - 01 ~ 12 [720p][Multiple Subtitle]</a> \| Subtitles: [us][br][mx][es][sa][fr][de][it][ru]  \| Size: 8.41GB \| InfoHash: 0b2c4b0e53a544baea803c6fc1f1b7678114e3b0 \| Categories: [Batch] '
> ```
> 
> @6cUbi57z would you be so kind as to investigate? Thanks.

Had a quick look but can't see anything obvious to be causing this. I've just formatted my computer so have no dev environment at the moment but I'll take a look when I can.

**Comment by garfield69** [comment]
ok thanks.
I've tried to figure out what's going on, but its beyond me. All I can tell is that the code is not finding the `erai:size` and `erai:resolution` elements anymore but I don't understand why. :-(

**Comment by 6cUbi57z** [comment]
> ok thanks.
> I've tried to figure out what's going on, but its beyond me. All I can tell is that the code is not finding the `erai:size` and `erai:resolution` elements anymore but I don't understand why. :-(

Ah it's a problem with the xml namespace: 
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/EraiRaws.cs#L115

Looks like the beta and production sites both match so it should just be a case of updating the URL on that line to `https://www.erai-raws.info/rss-page/` so that it matches the namespace on the very first line of the rss feed.

**Comment by garfield69** [comment]
YES! that works. I'll post a fix shortly. Thanks.

**Comment by garfield69** [comment]
v0.18.582

**Comment by codevski** [comment]
I know this is an old issue but still getting this... The fix updating the URL in jacket to the answer above throws an error...

**Comment by ilike2burnthing** [comment]
Do you mean the occasional warning in the logs? Do you still get results?

**Comment by garfield69** [comment]
The current warning from the indexer about not being able to parse one of the torrents is a genuine warning, as that torrent does not have a size value so cannot be accepted as a good torrent.
