### ISSUE TITLE
[BIGTorrent] Multiple issues: No results, no categories defined

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#1219]
I'm getting the following issues for BIGTorrent:

1. Test failed for BIGTorrent: Found no results while trying to browse this tracker. Enhanced log attached.
[log.txt](https://github.com/Jackett/Jackett/files/877838/log.txt)

2. There doesn't seem to be any defined categories. None are mentioned in the 'Add Indexer' window next to BIGTorrent, and none seems to have been defined for the tracker after it's been added.

Jackett version:  0.7.1225.0
Mono version (if not using Windows):  N/A

**Comment by adamwinn** [comment]
Ya, this one was a lil harder since it's in Hungarian.  I'll see what I can do.

For #1, they require at least a 2 character search string.  When you hit "test" in Jackett, it does a blank test (ie. &search=) so it fails.  I didn't know how to specify a fake, hard coded search string.  Running your own manual search should work tho.

For #2, It was hard to get the English translation for the category mappings.  I'll work on it.

**Comment by RoloSoze** [comment]
@kaso17 Are you able to help with point no. 1 regrading the failed test?

@adamwinn I can provide you with the translations for the categories & alive/dead torrent search options. I'll send those in a few hours.

**Comment by RoloSoze** [comment]
@adamwinn Here are the category translations, in the order in which they appear in the drop-down list. Notice that some of them are in English or self-explanatory. For everything else, I added the English translation after the = sign.

- 3D
**- Egyéb = Other**
- Film DVD English
- Film DVD Hungarian 
- Film HD English
- Film HD Hungarian 
- Film SD English
- Film SD Hungarian 
- Games ISO
- Games Rip
**- Hangoskönyvek = Audiobooks**
**- Képek = Picture**
**- Klipp = Video**
**- Konzol jatek = Video Game Console**
**- Könyvek/Eng = English Books**
**- Könyvek/Hun = Hungarian Books**
- Lossless
**- Mobil = Mobile**
**- Programok = Programs**
**- SorozatHD/Eng = English HD Series** 
**- SorozatHD/Hun = Hungarian HD Series** 
**- SorozatSD/Eng = English SD Series** 
**- SorozatSD/Hun = Hungarian SD Series** 
- XXX
**- Zene = Music**
**- Zene/Hun = Hungarian Music**

**Comment by adamwinn** [comment]
Added categories with #1253

Specifying a search string with more than 2 chars when the Test button is pressed is still outstanding tho

**Comment by kaso17** [comment]
Regarding the character minimum: do they support wildcard characters (typically * or %)? What happens if you search for "  " (two spaces)? maybe the limit can be "tricked"? is there some other "latest torrents" page?

**Comment by garfield69** [comment]
no reply. closing.

**Comment by RoloSoze** [comment]
I think this is related to the issue I just opened for the same tracker. If someone is willing to work on this, I'm willing to give them temporary access to my account. This tracker is fine with that.

**Comment by garfield69** [comment]
send login details to  garfieldsixtynine @ gmail.com and I'll see what I can do.

**Comment by RoloSoze** [comment]
@garfield69 Done. Check your email (including Spam). Thank you!
