### ISSUE TITLE
[cgpeers] Exception (cgpeers): Value cannot be null. (Parameter 's'): Parse error (Config)

### ISSUE THREAD

**Issue by Code5linger** [Jackett/Jackett#12198]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:Win 10 64bit

**.Net Runtime**:Net-Framework

**.Net Version**:80ff4

**Jackett Version**:v0.18.551

**Last Working Jackett Version**:v0.18.551

**Are you using a proxy or VPN?** [yes/no]No

### Description

Cant log in 

### Logged Error Messages

 An error occurred while updating this indexer
Exception (cgpeers): Value cannot be null. (Parameter 's'): Parse error
Click here to open an issue on GitHub for this indexer.

### Screenshots

https://ibb.co/s3xny3K

**Comment by garfield69** [comment]
None of the team have an account on this site so we cannot test/debug independently.
An additional complication is that the indexer is written in c# and uses the gazelletracker abstract.

To start with it will be more useful if you can repeat the event but first turn on the Jackett enhanced logging
Maybe with the full html and debug messages in the log there will be a clue to what is going on.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

Also, if you have an invite available, then this will help any C# dev volunteer immensely.

**Comment by Code5linger** [comment]
Unfortunately, the invite system is down, just checked. I'll keep an eye out for you. 

There's a lot of trackers that are not listed in the jacket, can you please tell me what is the process of adding a new tracker? also, can I help?

**Comment by garfield69** [comment]
>There's a lot of trackers that are not listed in the jacket, can you please tell me what is the process of adding a new tracker? 

first check https://github.com/Jackett/Jackett/projects/5 to see if the site you want to add has not already been requested and is stalled for what ever reason.
if not already requested, then read https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker to make a request. 

We generally try to write the indexer in yaml as long as the site requirements fit the one-title-one-torrent scheme, in which case the yaml indexer syntax is covered by https://github.com/Jackett/Jackett/wiki/Definition-format and you can use any of the existing yaml indexers that closely match the sites search engine as a template
If you are not into yaml coding then leave it to me, I specialise in the yaml indexer area.

If the site has a one-title-many-torrents scheme or some other quirk that prevents using yaml then the indexer will need to be written in C# by a C# dev volunteer.

>also, can I help?

absolutely. We are lacking in C# developers (see #8180) so if you are a C# dev then pick any of the stalled indexer projects and have at it.
I'm not a C# dev so I cant advise on best practice, but in general, you can pick the closest matching existing indexer to use a template and customise it to fit the new indexer requirements.

**Comment by Code5linger** [comment]
I know a bit of JSON but YAML looks great. I know c and am learning c++. Haven't got to c# yet. 
I specialize in web-related tech like react and stuff. 

But I believe in what you are creating here and even though I am a noob I'd love to help out in any other way possible.

**Comment by garfield69** [comment]
just reposting this in case you missed it the first time:
To start with it will be more useful if you can repeat the event but first turn on the Jackett enhanced logging
Maybe with the full html and debug messages in the log there will be a clue to what is going on.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
