### ISSUE TITLE
[1337x] Exception (1337x): certificate validation failed: [Subject]  CN=191.234.203.33, OU=DTIC, O=MJSP, L=BRASILIA, S=DF, C=BR[Issuer]  CN=191.234.203.33, OU=DTIC, O=MJSP, L=BRASILIA, S=DF, C=BR[Serial Number]  07544A869781A59A737C8566BE073DDFA5A74B37[Not Before]  10/30/2020 3:27:29 PM[Not After]  10/30/2021 3:27:29 PM[Thumbprint]  5AF6B4A086480412E65D0449CCCF8A6F80F17698: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by MightyFlix** [Jackett/Jackett#12206]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Win10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: Latest

**Jackett Version**: v0.18.582

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Click Test or Test All and indexer fails

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by MightyFlix** [comment]
Tried to create a new Issue since bot closed first one automatically.

**Comment by garfield69** [comment]
the official CA from https://1337x.to/ is issued by cloudflare with a thumbprint of 51d60b1d6b77636a0268cab0be54ae20cb445f9f
the one you are seeing was issued by 191.234.203.33 with a thumbprint of 5AF6B4A086480412E65D0449CCCF8A6F80F17698

what this tells me is that your ISP is blocking your access to 1337x and routing you down a blackhole that has at its end an invalid CA.

Have a read of https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed and try out some of the possible solutions that may help you out.
