### ISSUE TITLE
Internet Archive: Magnet not working

### ISSUE THREAD

**Issue by heroku-miraheze** [Jackett/Jackett#12209]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] .Net-Framework

**.Net Version**: Latest version.

**Jackett Version**: Latest version.

**Last Working Jackett Version**: Latest version.

**Are you using a proxy or VPN?** [yes/no] no

### Description
I have qBitTorrent installed, and this client gives me a magnet instead of torrent file in Internet Archive, so, please, fix it as soon as possible.
### Logged Error Messages

I don't have logged error messages.

### Screenshots

![Captura4](https://user-images.githubusercontent.com/61781343/130469187-b18c0ad7-3909-49a3-9ab0-f8ac438f37e5.PNG)

![Captura5](https://user-images.githubusercontent.com/61781343/130469522-fc97fbc2-3d0d-4957-b26e-0e3f4ad9cec0.PNG)

**Comment by garfield69** [comment]
This C# indexer currently generates a magnet URI when it finds the btih field in the returned JSON/XML feed but .torrents appear to be the primary download link on the site.
I think we can add an indexer config option to allow users to choose not to be provided with magnets, which should provide some flexibility regarding which download link the user prefers their torrent client to use.

**Comment by garfield69** [comment]
v0.18.599
