### ISSUE TITLE
Indexing issue on supported tracker swarmazon.club

### ISSUE THREAD

**Issue by protocolprowler** [Jackett/Jackett#12217]
Hello jackett support.

I'm a concerned admin on this tracker and it appears that some of our users worked with Jackett to get swarmazon listed as a supported tracker. However, we are seeing Jackett skill users reporting issues, see image below. I would like to help coordinate the effort of getting Jackett working. Please let me know how I can help.

![unknown](https://user-images.githubusercontent.com/6018001/130912492-54c3c354-c9b2-4f44-8ddd-1d54d81f80cf.png)

Thank you in advance for your time.

**Comment by protocolprowler** [comment]
Follow up: Hello jackett support! I'm happy to report that our devs have just finished publishing an update that enabled long-life cookies on swarmazon. We expect this fix will also fix the majority of issues users were having with jackett. As time allows please test this out and let us know how we did. Thanks!

**Comment by protocolprowler** [comment]
> > ... presenting authentication with a PSK. Have you guys seen any sites do something like that successfully?
> 
> yes, there are several indexers on our app that use an alternate login method using forms for passkeys.

Follow up: Hello jackett support! I'm happy to report that our devs have just finished publishing an update that enabled long-life cookies on swarmazon. Not sure if it was needed for jackett but we're also experimenting with disabling the captcha. 

We're hopeful this might also fix the majority of issues users were having with jackett. As time allows please test this out and let us know how we did. Thanks!

**Comment by garfield69** [comment]
Thanks for the heads up.
I'll update the indexer to drop the captcha support, shortly.
The next release of Jackett due out in about 2.5 hours should include the updated indexer.
Then I'll monitor daily over the next week and see how it goes, but I expect that without the captcha the indexer should be able to re-login whenever the cookie expires without user intervention. :-)

**Comment by protocolprowler** [comment]
> Thanks for the heads up.
> I'll update the indexer to drop the captcha support, shortly.
> The next release of Jackett due out in about 2.5 hours should include the updated indexer.
> Then I'll monitor daily over the next week and see how it goes, but I expect that without the captcha the indexer should be able to re-login whenever the cookie expires without user intervention. :-)

Awesome! This is greatly appreciated. Provided the Remember Me tick-box is activated a long-life cookie should be generated so users shouldn't have to re-authenticate nearly as often. fyi, when and if a logout is performed all remember me cookies for that user will be revoked.

**Comment by garfield69** [comment]
v0.18.641

**Comment by garfield69** [comment]
LGTM
