### ISSUE TITLE
Jackett doesn't start anymore

### ISSUE THREAD

**Issue by chrisvdgeld** [Jackett/Jackett#1221]
Jackett doesn't seem to start anymore. 

Mono version 4.8.0 and latest git commit

https://puu.sh/v26SH/b9f2582f68.png
(cant ctrl c, ctrl v due to esxi. SSH not installed for security issues)

Update:

My server monitor says

"Warning, cannot assign requested address"
domain:port
localhost:9117

**Comment by kaso17** [comment]
check journalctl/log.txt for the error output.

**Comment by kaso17** [comment]
according your update message it looks like it's already running? Check netstat for the port usage.

**Comment by chrisvdgeld** [comment]
journalctl said exactly the same as status. After a reinstall everything seems to work peachy! Thank you anyway!
