### ISSUE TITLE
[req] FileListing

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12214]
FileListing https://filelisting.com/ public torrent search engine

**Comment by garfield69** [comment]
v0.18.606

**Comment by garfield69** [comment]
https://filelisting.com/ returning 
![image](https://user-images.githubusercontent.com/6933240/171969757-0b1faab2-cb7e-407f-a62a-4e4880a9beed.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://filelisting.com/ - Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://filelisting.com/ - Origin is unreachable Error code 523

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://filelisting.com/ Server shut down forever.

**Comment by garfield69** [comment]
v0.21.1138
