### ISSUE TITLE
Feature request: tracker buffer display per result

### ISSUE THREAD

**Issue by element4l** [Jackett/Jackett#12212]
Again, I'm going to re-iterate the issue with the instruction not to delete the template. Guys, you know by now that this is confusing people and causing issues because not every issues is an actual issue.

Whatever.

This is going to land on deaf ears after that, but I have a suggestion. It would be great if we could see our buffer for any given private tracker displayed beside the results so we could get a better idea of where we want to get the file from. As it stands, we have to manually go and check.

Anyway, cheers. 

Thanks for the terrific software.

**Comment by ilike2burnthing** [comment]
duplicate - https://github.com/Jackett/Jackett/issues/656
