### ISSUE TITLE
How to manually install update on synology

### ISSUE THREAD

**Issue by badbonez** [Jackett/Jackett#1222]
Synology DS 1515+
DSM 6.1-15047 Update 2
Mono ver: 1.7.0-2810
Jackett ver: 0.7.806-3

I am having the issue where Jackett quits daily.  Issue #185 says that d071f19 should fix it.  However, on Synology the current version is 0.7.806-3, there is no update from the synocommunity packages.  I would  like to install this current release.  Is there a way to install this manually on the Synology DS?  I have downloaded the current release, where in the synology OS do I copy these files?

Thank you.

**Comment by kaso17** [comment]
don't know the location, did you try clicking on "check for updates"?

**Comment by badbonez** [comment]
There is no 'check for updates' in the DSM system.  If you look at https://synocommunity.com/package/jackett you will note that the current release is 0.7.806-3 which is what I have installed, so as far as my Diskstation is concerend, this is the most up-to-date package.  The problem is that the synocommunity package has not been updated.

Having said that, I was able to find the location of the files in /var/packages/jackett/target/share (for those that might be looking).  However, when I replaced those files with the current version, the package would not start.  So there is more to the synocommunity package than just these files.  Any help appreciated!

**Comment by silentmiles** [comment]
@badbonez, Jackett crashes regularly for me as well (also on Synology). However, I have 0.7.1225.0 installed, and the problem is not fixed. I'm not sure why your version would be so old. You don't need to manually install anything. Just go to the Jackett admin page and click on the "Check for updates" button in the configuration section. Jackett uses its own update manager, instead of the standard Synology updater (I wish they'd fix this as well -- all packages should just use the standard system).

**Comment by silentmiles** [comment]
Ah... Yes, I see now that my Synology package manager also reports v0.7.806-3. I think this was the version when I first installed the package. But, as I said above, Jackett updates itself (if that option is enabled), so the actual version may be different to what Synology reports (again, another reason Jackett should not be using its own mechanism). Have a look at the very bottom of your Jackett admin page and you'll find the actual version number there. 

Of course, it sounds like your install is now broken. Probably best to just uninstall and reinstall using the Synology package manager, and then go to the Jackett admin page to get an update.

**Comment by badbonez** [comment]
OK, I see that in the Jackett web page, the version is 0.7.1242.0.  Yes, I was confused between updating the synology package center or the actual app.  So far, it has not crashed today.  Thanks for the help.
