### ISSUE TITLE
[tvchaosuk] Resource temporarily unavailable (tvchaosuk.com:443): Resource temporarily unavailable (Config)

### ISSUE THREAD

**Issue by rafeeJ** [Jackett/Jackett#12226]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu Server 20.04 Server

**.Net Runtime**: Mono 6.12.0.122

**.Net Version**:

**Jackett Version**: 0.18.613

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?**: No

### Description

Add TVChaosUK with credentials to Jackett.

### Logged Error Messages

An error occurred while updating this indexer
Resource temporarily unavailable (tvchaosuk.com:443): Resource temporarily unavailable

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by rafeeJ** [comment]
Issue with my DNS, whoops.

**Comment by caio-vinicius** [comment]
Please, leave a comment saying what steps you take to solve the issue, could help someone.
