### ISSUE TITLE
[BIT-HDTV] Configuration failed: Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#1223]
I believe the tracker has just been updated, so certain things have changed. It doesn't work in Jackett anymore. Enhanced log attached.
[log.txt](https://github.com/Jackett/Jackett/files/880196/log.txt)

Jackett version:  0.7.1225.0
Mono version (if not using Windows): N/A

**Comment by adamwinn** [comment]
I can take a look at this one

**Comment by RoloSoze** [comment]
Closed via #1232
