### ISSUE TITLE
[req] BrSociety https://brsociety.club/ Private Brazilian

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12233]
BrSociety https://brsociety.club/ Private Brazilian
BrSociety (SemeandoCC) is a BRAZILIAN Private Torrent Tracker for E-LEARNING
engine: unit3d 5.3.0
MST 48 hours

**Comment by garfield69** [comment]
v0.18.632

**Comment by garfield69** [comment]
v0.20.4141

**Comment by ilike2burnthing** [comment]
https://brsociety.club/ - Origin is unreachable Error code 523

**Comment by garfield69** [comment]
v0.22.56
