### ISSUE TITLE
[enhancement] cardigann size parsing

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12241]
currently some of the yaml indexers have to have a **filters** clause to handle a size string retuned from a web site with a format of 1.023.4MB or 1,023.4MB
looking at the cardigann c# I find 
https://github.com/Jackett/Jackett/blob/fe91e268ee2bbdd5e94a2518277425a31423d037/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1482-L1485
and in the ReleaseInfo model I find
https://github.com/Jackett/Jackett/blob/6a213c6eabd0264392c48564ff16a9035fd13ca4/src/Jackett.Common/Models/ReleaseInfo.cs#L77-L100

example of existing yaml indexers that use filters to fix the size
https://github.com/Jackett/Jackett/blob/0b376faf2d8b00fe22edc20cefe03f4a656c5403/src/Jackett.Common/Definitions/torrentproject2.yml#L108-L112
https://github.com/Jackett/Jackett/blob/6a213c6eabd0264392c48564ff16a9035fd13ca4/src/Jackett.Common/Definitions/insanetracker.yml#L136-L142
[edit] Albeit the insanetracker example should not be implemented globally the same way as this assumes all size have commas. Probably the torrentproject2 example but with the dot replaced with a comma might be a better global fix to implement.

Can a C# dev volunteer add the necessary logic to the ReleaseInfo.GetBytes procedure to implement what we currently have to code some yaml indexers to do?  
I'll take care of subsequently updating any of the impacted yaml indexers, and some C# indexers that also may use the routine.
Thanks.

**Comment by austinwbest** [comment]
Where is 1.023.4 even a thing?

1023.4
1,023.4
1.023,4
1 023,4

These I'm familiar with but I can't place the other.

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/131606751-31834414-5ae0-478e-a099-dbeab32a3317.png)

**Comment by mikeoscar2006** [comment]
What if we just replace the commas with dots and only consider the last dot in the string since it'll be the only one representing the decimal part of size?
So 1,024.5 => 1.024.5 => 1024.5
This takes care of all variants I believe. If it's fine, I can implement it or any other suggestions are welcome.

**Comment by garfield69** [comment]
Okely Dokely. Thanks.

**Comment by garfield69** [comment]
list of yaml and c# indexers that can be cleaned up after ReleaseInfo.GetBytes is enhanced:
- [ ] greekdiamond
- [ ] torrenthr
- [ ] 0daykiev
- [ ] Bittorrentfiles
- [ ] coastalcrew
- [ ] dark-shadow
- [ ] dragonworldreloaded
- [ ] fantasticheaven
- [ ] fouducinema
- [ ] insanetracker
- [ ] mnv
- [ ] puntotorrent
- [ ] selezen
- [ ] speedmasterhd
- [ ] speedtorrentreloaded
- [ ] spiritofrevolution
- [ ] teracod
- [ ] thefallingangels
- [ ] torrent-explosiv
- [ ] torrentsectorcrew
- [ ] unionfansub
- [ ] woot
- [ ] Abnormal
- [ ] BitCityReloaded
- [ ] ZonaQ
- [ ] torrentz2eu
- [ ] isohunt2
- [ ] racingforme

**Comment by garfield69** [comment]
- [ ] torrentproject2
- [ ] kickasstorrents-ws

**Comment by garfield69** [comment]
v0.18.648
