### ISSUE TITLE
[HDClub] Broken search strings

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#1224]
This issue is very similar to BeyondHD's issue in #835. Basically, if you search for anything other than the title, the tracker will return no results. Things like year, resolution, etc. will break your search. 

E.g. Search for Mad Max - 8 results, one of which is the 2015 movie. Search for Mad Max 2015, 0 results.
E.g. Search for The Silence of the Lambs - 4 results. Add 1080p to the search string. 0 results.

Can this be fixed? I was wondering why HDClub hasn't been returning any results despite its relatively large database - Broken searches! This also happen when searching the tracker directly, just like with BHD in #835.

Jackett version: 0.7.1225.0
Mono version (if not using Windows): N/A

**Comment by kaso17** [comment]
"*mad*max*2015*" or "%mad%max%2015%" dosn't work either. I suggest to raise this as an issue/feature request on the tracker forum. I don't see a generic way to fix it.
For the special case of movie search we could remove the year from the search and filter the results using andmatch.

**Comment by RoloSoze** [comment]
Tracker shut down permanently. Issue is now irrelevant.
