### ISSUE TITLE
Base Path Override: - small one

### ISSUE THREAD

**Issue by roddyrodman** [Jackett/Jackett#1225]
Dear beloved development heroes,

I just came across a small one but found others people seem to make the same mistake.
(and think something is wrong with the application)

If you enter in the Base Path Override: a path that end with a \ the result of the "copy torznab feed" will have a \\ after the path. 

maybe it makes sense to enter a default volume in the Base Path Override: or check the entry?

Cheers

**Comment by kaso17** [comment]
Can you provide a more complete example?
The feature is designed for usage with reverse proxies and paths in URIs shouldn't contain backslashes. The defualt value (if not configured) "/jackett/" should be a good example.

**Comment by kaso17** [comment]
should be fixed with 1689c46c919fa8ab6154ea103072e6750a7a9e10
