### ISSUE TITLE
[req] grantorrents public Spanish  https://grantorrents.org/

### ISSUE THREAD

**Issue by nomascashtv** [Jackett/Jackett#12259]
Can you add the https://grantorrents.org/ website to jackett?

**Comment by garfield69** [comment]
this site uses the one-title-many-torrents scheme which means that we will have to code the indexer in C#

**Comment by Lyuu17** [comment]
it has "link protector" #12820

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
