### ISSUE TITLE
[muziekfabriek] Login failed: Selector

### ISSUE THREAD

**Issue by Ewoodss** [Jackett/Jackett#12254]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment
Docker Environment
https://hub.docker.com/r/linuxserver/jackett

**OS**:
Linux

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
idk

**.Net Version**:
idk

**Jackett Version**:
v0.18.643

**Last Working Jackett Version**:
unknown

**Are you using a proxy or VPN?** [yes/no]
no
### Description
after entering the cookie i get an error message telling me to make this issue, 
this error is probloby because something changed on the website where the cookie is from.
the site is, https://www.muziekfabriek.org/

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
[log.txt](https://github.com/Jackett/Jackett/files/7108889/log.txt)

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/12234#issuecomment-907766073
I tested just now and the indexer is working for me after I fetched and saved a new cookie.

**Comment by Ewoodss** [comment]
i am using a docker container, so it must be problem with my setup, i am now trying to generate a ddos key for my server wich is headless, so i use a different computer for the cookie

**Comment by Ewoodss** [comment]
> 
> 
> [#12234 (comment)](https://github.com/Jackett/Jackett/issues/12234#issuecomment-907766073)
> I tested just now and the indexer is working for me after I fetched and saved a new cookie.

i am using a docker container, so it must be problem with my setup, i am now trying to generate a ddos key for my server wich is headless, so i use a different computer for the cookie

**Comment by garfield69** [comment]
If you do manage to get this working I would appreciate some instructional steps documented here so I can include them in the wiki for others, as I think this will be very useful. Thanks.

**Comment by Ewoodss** [comment]
> 
> 
> If you do manage to get this working I would appreciate some instructional steps documented here so I can include them in the wiki for others, as I think this will be very useful. Thanks.

i will do my best, if i get it working i will send some instruction to you

**Comment by Ewoodss** [comment]
i found a method that works, but its very abstract, 
the just of it is
i created this docker container, on the same machine that runs jackett
https://hub.docker.com/r/browserless/chrome

this makes a headless chrome, but puts the 'head' on a web interface,
so you can controll the browser instance remotely
via this instance i captured the cookie and it worked.

i dit this manually but this tool could also automate it using pupeteer, but i dont have time to configure that right now
