### ISSUE TITLE
[danishbytes] Error code: Redirect (Config)

### ISSUE THREAD

**Issue by sickoo0** [Jackett/Jackett#12260]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![image](https://user-images.githubusercontent.com/11561313/132120454-ac9fef07-1334-4ad1-9ec4-8f291da13e5c.png)

**Comment by garfield69** [comment]
Please provide a full enhanced log so we can take a look at the full traffic, debug and HTML exchanged. 
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
Thanks.

**Comment by garfield69** [comment]
@seeyabye  Heads up.

**Comment by garfield69** [comment]
The indexer is working for me. So the issue does appear to be at your end.
Is there a chance that your API key is no the current one in your web site account?
I hope the enhanced log you will provide can shed some light.

**Comment by seeyabye** [comment]
I can confirm that it's working on my end too. As what garfield pointed out, there's a possibility that the API key has been invalidated.
