### ISSUE TITLE
[dmhy] Test search in dmhy => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by wunyee** [Jackett/Jackett#12261]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Unraid 6.9.2

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.18.656

**Last Working Jackett Version**: no

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

test dmhy failed.

https://share.dmhy.org/
I guess dmhy change their format?

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
`System.Exception: Error while parsing field=seeders, selector=td:nth-child(6), value=-: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1585`

[Make sure you attach the full logs with your personal information removed in case we need more information]
[log.txt](https://github.com/Jackett/Jackett/files/7111344/log.txt)

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
v0.18.666
