### ISSUE TITLE
[REQ] MaxiTorrent

### ISSUE THREAD

**Issue by EddieKnight1** [Jackett/Jackett#12272]
Requesting new indexer:

Address: https://maxitorrent.com/
Type: Public

Main language: es-ES

**Comment by ilike2burnthing** [comment]
It's an alt site for NewPCT:
https://github.com/Jackett/Jackett/blob/151f0aa41a0230050c00b0d6140ea0dbb0407b4e/src/Jackett.Common/Indexers/NewPCT.cs#L101-L105
