### ISSUE TITLE
[cardigann] Code Quality Enhancement

### ISSUE THREAD

**Issue by mikeoscar2006** [Jackett/Jackett#12281]
With the recent changes in the Cardigann Indexer and Indexer Definitions, I think there is a bit of redundancy and overall the code quality can be improved a lot. I know many C# devs who have contributed are busy these days but even some suggestions will be appreciated. Till then, I'll try to improve it however I can.

PS: Thank you @garfield69 for the invitation. I hope I can give some valuable contributions.

**Comment by garfield69** [comment]
v0.18.755
