### ISSUE TITLE
API Documentation for /api/v2.0/indexers/all/results

### ISSUE THREAD

**Issue by justinrush** [Jackett/Jackett#12296]
Can someone point me to documentation on what query parameters are allowed in this api?
`/api/v2.0/indexers/all/results`

I'm using [go-jacket](https://github.com/webtor-io/go-jackett) and would like to be able to limit my query by publish date. I'm happy to modify the library, but I can't find documentation on what parameters exist.

**Comment by garfield69** [comment]
there is no Jackett specific doc on this, the original C# team never developed one.
the closes you can get is what is pointed to by the readme. which I've included below:
Developer note: The software implements the [Torznab](https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer) (with hybrid [nZEDb](https://github.com/nZEDb/nZEDb/blob/b485fa326a0ff1f47ce144164eb1f070e406b555/resources/db/schema/data/10-categories.tsv)/[Newznab](https://newznab.readthedocs.io/en/latest/misc/api/#predefined-categories) [category numbering](https://github.com/Jackett/Jackett/wiki/Jackett-Categories)) and [TorrentPotato](https://github.com/RuudBurger/CouchPotatoServer/wiki/Couchpotato-torrent-provider) APIs.

the Jackett supported categories are described https://github.com/Jackett/Jackett/wiki/Jackett-Categories

**Comment by justinrush** [comment]
I was looking at torznab API and don't see anything that gets me what I want - ultimately I want something to poll for "new" releases. Given your response I'm guessing I can't really use Jackett to do this? Any suggestion for other options?

**Comment by garfield69** [comment]
It all dependent on what the web site is capable of providing.
in general, depending on the web site in question, a Jackett indexer will be set up such that a torznab keywordless search will provide either the web sites new-releases page if it is available on the web site, or a search without keywords sorted (by default) by date if that is available on the web site, or if the web site does not support sorting, then just a search using a default keyword (such as the current year or something similar).
Other than that I have no suggestions.
