### ISSUE TITLE
[totheglory] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by waldens** [Jackett/Jackett#12302]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
- OS: Windows 7 x264
- .Net Runtime: .Net-Framework
- .Net Version: 4.8
- Jackett Version: v0.18.755
- Last Working Jackett Version: Unknown
- Are you using a proxy or VPN? No
```

#### Repro Steps

1. Cancel 2FA on ToTheGlory website, if there's one.
2. Remove the current configured ToTheGlory indexer, if there's one.
3. Open Jackett Dashboard, click "Add indexer", choose "ToTheGlory", click "config"
4. Input Username and Password, leave all other options blank
5. Click OK
**Expected Result**: configured indexer added successfully
**Actual Result**: "An error occurred while updating this indexer. Login Failed, got redirected. Click here to open an issue on GitHub for this indexer."

#### Checklist

* Jackett version is the latest? Yes
* Can I login to ToTheGlory website with my browser successfully? Yes
* Using the same Credentials in Jackett and browser? Yes, same username and password. (I do not use F2A and Security Question) working in browser, Jackett not.
* Site has expired the session cookie? This index is not using cookie method, but the username and password method.
* Web Site is online? Yes
* I have a good ratio? Yes, 5.2
* No outstanding alerts, notices or unread PM? Yes, [all checked and clear](https://i.imgur.com/oKBswpT.png).
* Have I recently changed password? No
* Have I tried "remove the existing indexer config, add a fresh one, and reenter credentials"? Yes, issue still.
* Am I 100% sure that when accessing with browser versus Jackett, I am on the same machine with the same ISP and same source IP and destination IP? Yes! Manual hosts `'totheglory.im': 104.26.15.154` ensure the same DNS resolution result and same destination IP. ~~However, I highly suspect that the request wasn't sent at all, because when clicking other indexer's test button in Jackett, the request in traffic analyzer tool can be seen, but when adding ToTheGlory indexer, I cannot see the related request.~~ (I'm not sure now)
* Firewall or Anti-Malware software or Router is blocking Jacket's traffic? No, I dont have all these.
* VPN or Proxy issue? No, I dont use these. Direct connection to website.
* Any similar issue describing this problem before? Only issue #9220 but its solution totheglorycookie is no longer available under the current Jackett version.

### Logged Error Messages

Pardon me to put log in external link to make it easier to delete the private info in case:
[edit] redacted for security

The `D:\a\1\s\src` in last part is strange because nothing under this path. seems hard coded?

### Screenshots

<details>
  <summary>Click to expand!</summary>
  
![](https://i.imgur.com/6fLBarY.png)
</details>

**Comment by garfield69** [comment]
have you tried using the toTheGloryCookie indexer? It is a clone of the toTheGlory indexer but uses the cookie method to access the web site. Does this work for you?

Looking at the enhanced log you provided I see that the toTheGlory indexer is not identifying the form it should be using on the login page, so this could be the source of the problem. I will see if I can improve that for the next Jackett release.

also unrelated to the toTheGlory issue, I see the log includes errors at start up for some indexers. You may want to shutdown and start up the Jackett service afresh, to ensure everything is up to date. Check the log after the restart to see if you still get `Error while parsing Cardigann definition` for about 7 indexers.

**Comment by waldens** [comment]
@garfield69 Thanks for reminder, no idea why I didn't notice existence of ToTheGloryCookie. Just tested ToTheGloryCookie. Works like a charm!

I have restarted Jackett many times before submitting this issue in order to test (not service, but JackettTray.exe. I don't use service). After you mentioned this point, I restarted JackettTray.exe (including its subprocess JackettConsole.exe) again. These 7 indexers failed while parsing Cardigann definition every time. Fortunately I don't use them. Here's the log this time in case:
https://p.teknik.io/Simple/HDVpE

**Comment by garfield69** [comment]
Thanks.
On closer inspection I see that these 7 are indexers that were removed from the Jackett stable, so they are not supposed to be there any longer. The Jackett Updater has a delete unwanted indexers step, but clearly this is not working on your system, I don't know why. 
Anyway, I'll keep working on the toTheGlory Indexer and see if I can get this going properly.
Glad the toTheGloryCookie is working for you, so you can carry on.

**Comment by waldens** [comment]
@garfield69 Oh, my fault. Because I'm using the portable version (Jackett.Binaries.Windows.**zip**) and directly overwriting existing folders each time upgrade (so the old indexers not being removed). Later on, after I learn how to backup Jackett's config files, I'll probably switch to the install version, this issue will no longer exist then. (or maybe I should run JackettUpdater.exe to update, instead of downloading Jackett.Binaries.Windows.**zip** each time?)

BTW, thanks for your continued contributions and letting more people use such a great tool!

**Comment by garfield69** [comment]
v0.18.761
Give toTheGlory another go after you upgrade and see if it is any better.
Hopefully, it should at the very least give you an error rather than a mystery redirect.

**Comment by waldens** [comment]
`Successfully configured ToTheGlory` Works perfectly! Thank you!

BTW, this time I wanna use `JackettUpdater.exe` instead of overwriting all files to upgrade, but what are the acceptable values for the option "-t, --Type     Install type"? `Jackett.Updater/Program.cs` says "WindowsService" is an acceptable value, but what if want a portable upgrade(install), without touching any services/registry/system stuff/etc?

**Comment by garfield69** [comment]
I don't know if you can run the jackettupdater program as you intend, I've never personally used jackett in non-service mode.
- try just clicking on the **check for updates** button on the dashboard, and then check the **updater.txt** file on the `%programdata%/jackett` folder to see if it worked.
but I would not be surprised if you run into authorisation issues or some other problem.
