### ISSUE TITLE
[req]: DiscFan

### ISSUE THREAD

**Issue by ImageOnly** [Jackett/Jackett#12307]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Tracker details

```markdown
- Name: DiscFan
- URL: http://discfan.net/
- Description: DiscFan is a private tracker that focuses on Hong Kong movies/TV
- Public, Semi-private, or Private: Private
- Minimum Seeding Time and Minimum Ratio (if Private): No Minimum Seeding Time. Minimum Ratio is 0.9
- Additional Comments: NexusPHP tracker, born at 2011 June. Formerly known as GZTown. Not a big famous tracker but pretty distinctive and useful for Cantonese content fans.
```
[edit]
engine: Standard v1.5 Beta 4

**Comment by garfield69** [comment]
Registration is closed ATM.
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.

**Comment by garfield69** [comment]
Invite Received, Thank you,
Registration and login completed.

**Comment by garfield69** [comment]
v0.18.789
