### ISSUE TITLE
torrentland.li it only shows the title when you search

### ISSUE THREAD

**Issue by j0shii** [Jackett/Jackett#12309]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
- OS: Windows 10
- .Net Runtime: [.Net-Core/.Net-Framework/Mono]
- .Net Version:
- Jackett Version: v0.18.755
- Last Working Jackett Version: v0.18.755
- Are you using a proxy or VPN? no
```

### Description

A few weeks ago it was going well, I don't know if they touched anything on the tracker. When you search for a series or a movie from jacket, it only shows the title and not the chapter number etc ... So programs like medusa, radarr etc ... cannot identify them.
When you click on the search link it takes you to the similar torrent page in the tracker instead of the archive page as it does with any other tracker.
The url it takes you to is this: https://torrentland.li/torrents/similar/2.104877
And it should be this: https://torrentland.li/torrents/55248
Sorry for my bad English, I put screenshots of the problem

### Logged Error Messages

No error

### Screenshots

https://i.gyazo.com/e664f2f5c84075670de02a3a6e31587f.png
https://i.gyazo.com/32e802ab798f1859c45b098740af3e54.jpg
https://i.gyazo.com/8b97155ed3a487ea51f6ee596d4e3213.png
https://i.gyazo.com/a98c466ab8b94539e7ad172a4ea18934.jpg

**Comment by ilike2burnthing** [comment]
@garfield69 can you have a look at this? I don't have an account and registration is closed.

**Comment by j0shii** [comment]
> @garfield69 can you have a look at this? I don't have an account and registration is closed.

They just opened singup free

**Comment by ilike2burnthing** [comment]
Well timed. Thanks, I'll take a look.

**Comment by garfield69** [comment]
v0.18.767

**Comment by j0shii** [comment]
Thx!
