### ISSUE TITLE
[req]: HD.Ai

### ISSUE THREAD

**Issue by nigelwarning** [Jackett/Jackett#12304]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Tracker details

```markdown
- Name: HDAI
- URL: https://www.hd.ai
- Description: General Chinese Tracker
- Public, Semi-private, or Private: Private
- Minimum Seeding Time and Minimum Ratio (if Private): Can't find in FAQ & Rules
- Additional Comments: It is now open for sign-up. Don't know until when
```
engine: NexusPHP v1.5.beta5.20120707

**Comment by garfield69** [comment]
unfortunately this web site generates search results dynamically via JS
so it is not suitable for processing by Cardigann as a yml indexer.
The indexer will have to be written in C#

**Comment by garfield69** [comment]
With the upcoming json feature for cardigann on Jackett, I should be able to code this indexer in yml.
Currently creating the indexer to work in the beta cardigann json (to test that beta implementation), so we shall see if I can get it to work :-)

**Comment by garfield69** [comment]
v0.19.8

**Comment by garfield69** [comment]
HDAI returning
```JSON
{
  "ret": 500,
  "data": {},
  "msg": "服务器运行错误: 数据库db_master连接失败"
}
```
msg google translated: Server operation error: database db_master connection failed

**Comment by garfield69** [comment]
v0.20.3004
