### ISSUE TITLE
Search on lostfilm tracker works partially

### ISSUE THREAD

**Issue by DeadMozay** [Jackett/Jackett#12317]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
- OS:
- .Net Runtime: [.Net-Core/.Net-Framework/Mono]
- .Net Version:
- Jackett Version: 0.18.767
- Last Working Jackett Version:
- Are you using a proxy or VPN? [no]
```

### Description

Search on lostfilm tracker works partially.
Not all TV shows are searched, for example, searching for the series Lucifer does not return any results, or Star Trek: Lower Decks. And the series Rookie, for example, finds it without problems

### Logged Error Messages

<details>
  <summary>Complete log file</summary>
  
[log.txt](https://github.com/Jackett/Jackett/files/7177796/log.txt)

</details>

**Comment by ilike2burnthing** [comment]
Search - Star Trek: Lower Decks
`Exception (lostfilm): String '0.04.2019' was not recognized as a valid DateTime.`
Result is actually for Star Trek: Discovery S02E14 Ru: 20.04.2019 Eng: 18.04.2019
(There are also results for basically every Star Trek series as searching for `star trek lower decks` and `star trek lower` both return no results, so `star trek` is used instead.)

Search - Lucifer
`Exception (lostfilm): String '0.08.2016' was not recognized as a valid DateTime.`
Lucifer S01E13 Ru: 10.08.2016 Eng: 25.04.2016

A limited dataset, but seemingly Russian dates starting with `10` or `20` (and presumably `30`) are having their first digit trimmed for some reason.

**Comment by garfield69** [comment]
Notes to self to keep track and make sense of this C# spaghetti.
my previous fix dealt with **episode** releases.
but here we are dealing with **season packs** which is a different section of code that does not use the fix I added for #12290.

ok so we come in at 
```C#
                    // Fetch season pack releases if no episode filtering is required.
                    // If seasonButton implements "inactive" class there are no season pack available and each episode should be fetched separately.
                    if (string.IsNullOrEmpty(query.Episode) && string.IsNullOrEmpty(filter) && seasonButton != null && !seasonButton.ClassList.Contains("inactive"))
                    {
                        var lastEpisode = season.QuerySelector(rowSelector);
                        var dateColumn = lastEpisode.QuerySelector("td.delta");
                        var date = DateFromEpisodeColumn(dateColumn);

                        var details = new Uri(url); // Current season(-s) page url

                        var urlDetails = new TrackerUrlDetails(seasonButton);
                        var seasonReleases = await FetchTrackerReleases(urlDetails);

                        foreach (var release in seasonReleases)
                        {
                            release.Details = details;
                            release.PublishDate = date;
                        }

                        releases.AddRange(seasonReleases);

                        if (query.Season > 0)
                        {
                            break; // Searched season was processed
                        }

                        // Skip parsing separate episodes if season pack was added
                        if (seasonReleases.Count() > 0)
                        {
                            continue;
                        }
                    }
```
which fetches the date column at td.delta,  and extracts a date using DateFromEpisodeColumn and crashes
```C#
        private DateTime DateFromEpisodeColumn(IElement dateColumn)
        {
            var dateString = dateColumn.QuerySelector("span").TextContent;
            dateString = dateString.Substring(dateString.IndexOf(":") + 2); // 'Eng: 23.05.2017' -> '23.05.2017'
            var date = DateTime.Parse(dateString, new CultureInfo(Language)); // dd.mm.yyyy
            return date;
        }
```
time to poke around and add some logger debug to see if I can see that is being fetched and why the date its truncated

**Comment by garfield69** [comment]
so here is the trouble
```html
                    <td class="delta" onClick="goTo('/series/Lucifer/season_1/episode_13/',false)" title="Перейти к серии">
                        Ru: <span data-released="10.08.2016">10.08.2016</span>
                        <br/>
                        <span class="gray-color2 small-text">Eng: 25.04.2016</span>
                    </td>
```
the code finds the first `:` and grabs the date starting +2 which returns `0.08.2016`
I think we need to be fetching the `Eng:` since that is what we do for episodes, and fall back to `Ru:` when its not available
So that is what I'm going to try to code.

**Comment by garfield69** [comment]
v0.18.773

**Comment by DeadMozay** [comment]
The error in the logs disappeared, but unfortunately Star Trek: Lower Decks still does not appear in the search result, but there are all other Star Trek series, even the Star Trek: The Next Generation - S7E15 - Lower Decks series was found, 
![изображение](https://user-images.githubusercontent.com/39763483/133744517-0c6e1f4b-6b7b-404e-bc16-6e51ed4124b0.png)

but the Star series itself Trek: No Lower Decks, now there are no errors in the logs. 
![изображение](https://user-images.githubusercontent.com/39763483/133745432-b13c8022-c5be-4cdc-941e-d78a6ef7c77f.png)

With the TV series Lucifer, the bug seems to be fixed.

**Comment by ilike2burnthing** [comment]
> There are also results for basically every Star Trek series as searching for `star trek lower decks` and `star trek lower` both return no results, so `star trek` is used instead.

https://github.com/Jackett/Jackett/issues/12317#issuecomment-921071348

It's a site issue, nothing we can do to fix it. You can manually search for `lower decks` and it will find just it.

**Comment by DeadMozay** [comment]
> > There are also results for basically every Star Trek series as searching for `star trek lower decks` and `star trek lower` both return no results, so `star trek` is used instead.
> 
> [#12317 (comment)](https://github.com/Jackett/Jackett/issues/12317#issuecomment-921071348)
> 
> It's a site issue, nothing we can do to fix it. You can manually search for `lower decks` and it will find just it.

Unfortunately, this does not work in conjunction with sonarr, or I did not find how to implement search for individual words there.

**Comment by ilike2burnthing** [comment]
No it won't, you'd have to download past episodes yourself and manually import them, though new episodes would be added fine.
