### ISSUE TITLE
[req]: PuTao

### ISSUE THREAD

**Issue by ImageOnly** [Jackett/Jackett#12312]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: PuTao
- URL: https://pt.sjtu.edu.cn/
- Description: PuTao is a private general tracker, founded by students of Shanghai Jiao Tong University in May 2009, with internal release group PuTao. Members: 21,772, Torrents: 90,203
- Minimum Seeding Time and Minimum Ratio (if Private): Minimum Seeding Time - None. Minimum Ratio - 0.7
- Additional Comments: NexusPHP tracker. No English interface is offered.
```
[edit] 
engine: Standard v1.0 beta 2

**Comment by garfield69** [comment]
Registration is closed ATM
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by garfield69** [comment]
v0.19.275

**Comment by garfield69** [comment]
https://pt.sjtu.edu.cn/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://pt.sjtu.edu.cn/ returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://pt.sjtu.edu.cn/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online
