### ISSUE TITLE
[lostfilm] Exception (lostfilm): Length cannot be less than zero. (Parameter 'length'): Parse error (Test)

### ISSUE THREAD

**Issue by ViktorsBaikers** [Jackett/Jackett#12310]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
- OS: Ubuntu 20.04
- .Net Runtime: .Net-Core
- .Net Version: 5.05
- Jackett Version: v0.18.761
- Last Working Jackett Version: v0.18.755
- Are you using a proxy or VPN? No
```

### Description

Pressing "Test" button and getting this error :)

### Logged Error Messages

https://pastebin.com/1HBWmmyt

**Comment by garfield69** [comment]
2f111e5
