### ISSUE TITLE
[req]: CrypticHaven - standup comedy tracker

### ISSUE THREAD

**Issue by ClandestineClout** [Jackett/Jackett#12324]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: CrypticHaven
- URL: http://www.cryptichaven.org
- Description: Standup Comedy
- Minimum Seeding Time and Minimum Ratio (if Private): MST 14d, Ratioless
- Additional Comments: 

p.s. Absolutely love this new feedback/request form. Super well done. Whoever came up with this deserves a medal. This kind of thing was very confusing in the past.
```

**Comment by garfield69** [comment]
The site's registration is invite only.

If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by element4l** [comment]
Is there any way to know if it would require a native c# indexer? I may be able to get an invite in the near future.

**Comment by garfield69** [comment]
@sirloinofbeef Registration and login successful. Thank you.

**Comment by garfield69** [comment]
v0.18.911

**Comment by sirloinofbeef** [comment]
> v0.18.911

Confirmed to be working as of this version. Thanks again for your amazingly prompt and efficient work.

**Comment by garfield69** [comment]
http://www.cryptichaven.org/ returning ERR_CONNECTION_TIMED_OUT
https://www.uptrends.com/tools/uptime reports either TCP Connection Failed (40), Http Connect Failure (2), Http Timeou (1) across 43 checkpoints worldwide.

is the site gone, broken or moved to a new domain?

**Comment by garfield69** [comment]
back online.

**Comment by garfield69** [comment]
v0.20.2218
