### ISSUE TITLE
[req]: DataTalli (Finnish tracker)

### ISSUE THREAD

**Issue by rollecode** [Jackett/Jackett#12327]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: DataTalli
- URL: https://datatalli.net/
- Minimum Seeding Time and Minimum Ratio (if Private): 1.05
```

**Comment by garfield69** [comment]
DataTalli is a FINNISH Private Torrent Tracker for MOVIES / TV / GENERAL

registration at http://datatalli.net/members.php?action=reg is closed ATM

If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by ronilaukkarinen** [comment]
@garfield69 Sent an invite.

**Comment by garfield69** [comment]
@ronilaukkarinen  nothing has arrived, checked my spam and bin too.
if gmail is being blocked by the datatalli mail service then you can try garfieldsixtynine -at- protonmail.com

**Comment by ronilaukkarinen** [comment]
@garfield69 Yeah Gmail might be blocked. Sent it manually to your protonmail just now. Please check it.

**Comment by garfield69** [comment]
Registration completed, pending your confirmation. Thanks.

**Comment by ronilaukkarinen** [comment]
Confirmed. ✅

**Comment by ronilaukkarinen** [comment]
That was fast, thank you so much!

**Comment by garfield69** [comment]
v0.18.805

**Comment by garfield69** [comment]
http://datatalli.net/ omnis park page
https://datatalli.net/ ERR_SSL_PROTOCOL_ERROR

**Comment by garfield69** [comment]
@ronilaukkarinen  do you have any info on the status of DataTalli, is the site gone, just broken, or moved to a new domain?

**Comment by ronilaukkarinen** [comment]
> @ronilaukkarinen do you have any info on the status of DataTalli, is the site gone, just broken, or moved to a new domain?

The site has been permanently shut down.

**Comment by garfield69** [comment]
Thanks.

**Comment by garfield69** [comment]
v0.21.763
