### ISSUE TITLE
[NEWPCT] Issue with rss feed

### ISSUE THREAD

**Issue by viseniv** [Jackett/Jackett#12339]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
- OS: Windows 10
- .Net Runtime: [.Net-Core/.Net-Framework/Mono]
- .Net Version:
- Jackett Version: v0.18.812
- Last Working Jackett Version:
- Are you using a proxy or VPN? [yes/no] No
```

### Description

When i manual search for some new uploads on the web (ex: Foundation) it finds the entry correctly, but whe i load the rss this ntry doesn't appear and it doesn't download automatically.
Also if i use the url to search directly (http://127.0.0.1:9117/api/v2.0/indexers/newpct/results/torznab/api?apikey=xxxxxxxxxxxxxxxxxxxxxxxx&t=search&cat=&q=foundation) it founds the entries.

### Logged Error Messages

[flexget.log](https://github.com/Jackett/Jackett/files/7232349/flexget.log)

### Screenshots

![image](https://user-images.githubusercontent.com/2190005/134825578-679b365a-095d-414e-904f-78159be1c9ff.png)
![image](https://user-images.githubusercontent.com/2190005/134825601-ebbf5c32-38e9-4a79-bbd0-54d08ca07491.png)

**Comment by garfield69** [comment]
when you copy the rss feed link you need to add your search query, otherwise you will only get the latest torrents list 
http://127.0.0.1:9117/api/v2.0/indexers/newpct/results/torznab/api?apikey=myapikey&t=search&cat=&q=foundation
returns for me
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://127.0.0.1:9117/" rel="self" type="application/rss+xml" />
    <title>NewPCT</title>
    <description>NewPCT - Descargar peliculas, series y estrenos torrent gratis</description>
    <link>https://pctreload1.com/</link>
    <language>en-US</language>
    <category>search</category>
    <item>
      <title>Foundation Temporada 1 SPANISH BluRay 2160p x265</title>
      <guid>https://pctreload1.com/descargar/serie-4k/fundacion/temporada-1/capitulo-02/</guid>
      <jackettindexer id="newpct">NewPCT</jackettindexer>
      <comments>https://pctreload1.com/descargar/serie-4k/fundacion/temporada-1/capitulo-02/</comments>
      <pubDate>Sat, 25 Sep 2021 00:00:00 +1200</pubDate>
      <size>5261335040</size>
      <description />
      <link>http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhYOWg4aGw5MEJjWjh2aEVVWnFhdWNmWDRVcHlyaUJVMEVtX3ZjNjNkWmo1X1BhYkk5SFJWVDkwRFFCY1dWRTNxUUUyUGZldjdGcHN5YTZjRFhtZVBlUVhwUl80YUswdVBTUm51enA4eHZzb2k2MHJ1Vng1ZG56b1dMMU5JaG1IOF9NR0xvZjVJUklnMVBXTUg4SXJseGhtc3paQ3M0VjhhWGlfeXR5QzAxSElGazQzdFNfV29oajFmc1Z4TWVHUVA4&amp;file=Foundation+Temporada+1+SPANISH+BluRay+2160p+x265</link>
      <category>2000</category>
      <enclosure url="http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhYOWg4aGw5MEJjWjh2aEVVWnFhdWNmWDRVcHlyaUJVMEVtX3ZjNjNkWmo1X1BhYkk5SFJWVDkwRFFCY1dWRTNxUUUyUGZldjdGcHN5YTZjRFhtZVBlUVhwUl80YUswdVBTUm51enA4eHZzb2k2MHJ1Vng1ZG56b1dMMU5JaG1IOF9NR0xvZjVJUklnMVBXTUg4SXJseGhtc3paQ3M0VjhhWGlfeXR5QzAxSElGazQzdFNfV29oajFmc1Z4TWVHUVA4&amp;file=Foundation+Temporada+1+SPANISH+BluRay+2160p+x265" length="5261335040" type="application/x-bittorrent" />
      <torznab:attr name="category" value="2000" />
      <torznab:attr name="seeders" value="1" />
      <torznab:attr name="peers" value="2" />
      <torznab:attr name="downloadvolumefactor" value="0" />
      <torznab:attr name="uploadvolumefactor" value="1" />
      <torznab:attr name="coverurl" value="https://pctreload1.com/pictures/f/thumbs/" />
    </item>
    <item>
      <title>Foundation Temporada 1 SPANISH BluRay 2160p x265</title>
      <guid>https://pctreload1.com/descargar/serie-4k/fundacion/temporada-1/capitulo-01/</guid>
      <jackettindexer id="newpct">NewPCT</jackettindexer>
      <comments>https://pctreload1.com/descargar/serie-4k/fundacion/temporada-1/capitulo-01/</comments>
      <pubDate>Sat, 25 Sep 2021 00:00:00 +1200</pubDate>
      <size>5261335040</size>
      <description />
      <link>http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhYWUFsU0UwVHdIV01BWTJDUkdveV95S3VxTTBhZVhVX2RTTXlUYkl3THUxa2J3YmlxUFhhaGhESGR3Mzl2OHBvZkkzZzRvTldORmNNTEl6c3RFWnVOMl9GRXJTOTJoY3JXZTNfeFRRUVdTYU95MjhNSklLNjZZVVF2eVh5UU1mcG9OcHRXLXU3anpEdWZDdHMzSXZkSzloTzUxOE5hLW93NGx5ay1jSmJKT0dPamdyT1pZYlNUTkVfS0lRUHBVWjRB&amp;file=Foundation+Temporada+1+SPANISH+BluRay+2160p+x265</link>
      <category>2000</category>
      <enclosure url="http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhYWUFsU0UwVHdIV01BWTJDUkdveV95S3VxTTBhZVhVX2RTTXlUYkl3THUxa2J3YmlxUFhhaGhESGR3Mzl2OHBvZkkzZzRvTldORmNNTEl6c3RFWnVOMl9GRXJTOTJoY3JXZTNfeFRRUVdTYU95MjhNSklLNjZZVVF2eVh5UU1mcG9OcHRXLXU3anpEdWZDdHMzSXZkSzloTzUxOE5hLW93NGx5ay1jSmJKT0dPamdyT1pZYlNUTkVfS0lRUHBVWjRB&amp;file=Foundation+Temporada+1+SPANISH+BluRay+2160p+x265" length="5261335040" type="application/x-bittorrent" />
      <torznab:attr name="category" value="2000" />
      <torznab:attr name="seeders" value="1" />
      <torznab:attr name="peers" value="2" />
      <torznab:attr name="downloadvolumefactor" value="0" />
      <torznab:attr name="uploadvolumefactor" value="1" />
      <torznab:attr name="coverurl" value="https://pctreload1.com/pictures/f/thumbs/" />
    </item>
    <item>
      <title>Foundation Temporada 1 SPANISH BluRay 1080p</title>
      <guid>https://pctreload1.com/descargar/serie-1080p/fundacion/temporada-1/capitulo-02/</guid>
      <jackettindexer id="newpct">NewPCT</jackettindexer>
      <comments>https://pctreload1.com/descargar/serie-1080p/fundacion/temporada-1/capitulo-02/</comments>
      <pubDate>Fri, 24 Sep 2021 00:00:00 +1200</pubDate>
      <size>5261335040</size>
      <description />
      <link>http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhWQlZLdjAyR3hBNUgwUS1ET2dGSE9SNDhsRDFWMXcySGNxbG1LRXU1LVcwdFVLMWlPSlBxZ0Focm5wS3QtSnprUzY5RnBkT3J3UWhURDhVVWFsVGtIcVhhVVpnOTNjUDR1dE14bTVkYVBpd0w4QlVNV1FLQXFMTHNGT2hueDVQSU4wXzZDYzZqQTd6dlk2aVNWd3ZMQzFhcUpmekotRzdaMzNQZjdHR2Y5elYwcTBTVVZYSVgyMlAxYWRTZzlWT3pV&amp;file=Foundation+Temporada+1+SPANISH+BluRay+1080p</link>
      <category>2000</category>
      <enclosure url="http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhWQlZLdjAyR3hBNUgwUS1ET2dGSE9SNDhsRDFWMXcySGNxbG1LRXU1LVcwdFVLMWlPSlBxZ0Focm5wS3QtSnprUzY5RnBkT3J3UWhURDhVVWFsVGtIcVhhVVpnOTNjUDR1dE14bTVkYVBpd0w4QlVNV1FLQXFMTHNGT2hueDVQSU4wXzZDYzZqQTd6dlk2aVNWd3ZMQzFhcUpmekotRzdaMzNQZjdHR2Y5elYwcTBTVVZYSVgyMlAxYWRTZzlWT3pV&amp;file=Foundation+Temporada+1+SPANISH+BluRay+1080p" length="5261335040" type="application/x-bittorrent" />
      <torznab:attr name="category" value="2000" />
      <torznab:attr name="seeders" value="1" />
      <torznab:attr name="peers" value="2" />
      <torznab:attr name="downloadvolumefactor" value="0" />
      <torznab:attr name="uploadvolumefactor" value="1" />
      <torznab:attr name="coverurl" value="https://pctreload1.com/pictures/f/thumbs/" />
    </item>
    <item>
      <title>Foundation Temporada 1 SPANISH BluRay 1080p</title>
      <guid>https://pctreload1.com/descargar/serie-1080p/fundacion/temporada-1/capitulo-01/</guid>
      <jackettindexer id="newpct">NewPCT</jackettindexer>
      <comments>https://pctreload1.com/descargar/serie-1080p/fundacion/temporada-1/capitulo-01/</comments>
      <pubDate>Fri, 24 Sep 2021 00:00:00 +1200</pubDate>
      <size>5261335040</size>
      <description />
      <link>http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhWaTVCLUZacUdacFEyNmZDWmI3cHEtcHNqczlCMUdPSE9vR0FUcEtfLWp5dmJ5NkZNdEFMX0l6Qkd3NXIwdmttcTVUNDZ1NV80UnB0RWxmSlZHSndIU2pGc08tbjlsR1h5OFhhSHJwRXgxS2hjcFlwNUV4OENUYjIxRFNoQUNjYVI2dlhJMTJXV2hkZkFvVGxxYTlEaXZGRzR1TDFTS2ZyNUdJZVRNSy1Cb05naTVwa1g3cTJqNnVGUmtMVjZESjV3&amp;file=Foundation+Temporada+1+SPANISH+BluRay+1080p</link>
      <category>2000</category>
      <enclosure url="http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhWaTVCLUZacUdacFEyNmZDWmI3cHEtcHNqczlCMUdPSE9vR0FUcEtfLWp5dmJ5NkZNdEFMX0l6Qkd3NXIwdmttcTVUNDZ1NV80UnB0RWxmSlZHSndIU2pGc08tbjlsR1h5OFhhSHJwRXgxS2hjcFlwNUV4OENUYjIxRFNoQUNjYVI2dlhJMTJXV2hkZkFvVGxxYTlEaXZGRzR1TDFTS2ZyNUdJZVRNSy1Cb05naTVwa1g3cTJqNnVGUmtMVjZESjV3&amp;file=Foundation+Temporada+1+SPANISH+BluRay+1080p" length="5261335040" type="application/x-bittorrent" />
      <torznab:attr name="category" value="2000" />
      <torznab:attr name="seeders" value="1" />
      <torznab:attr name="peers" value="2" />
      <torznab:attr name="downloadvolumefactor" value="0" />
      <torznab:attr name="uploadvolumefactor" value="1" />
      <torznab:attr name="coverurl" value="https://pctreload1.com/pictures/f/thumbs/" />
    </item>
  </channel>
</rss>
```

**Comment by viseniv** [comment]
i run without the search every hour and flexget didn't find that result but older results are appearing

**Comment by viseniv** [comment]
> when you copy the rss feed link you need to add your search query, otherwise you will only get the latest torrents list
> http://127.0.0.1:9117/api/v2.0/indexers/newpct/results/torznab/api?apikey=myapikey&t=search&cat=&q=foundation
> returns for me
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
>   <channel>
>     <atom:link href="http://127.0.0.1:9117/" rel="self" type="application/rss+xml" />
>     <title>NewPCT</title>
>     <description>NewPCT - Descargar peliculas, series y estrenos torrent gratis</description>
>     <link>https://pctreload1.com/</link>
>     <language>en-US</language>
>     <category>search</category>
>     <item>
>       <title>Foundation Temporada 1 SPANISH BluRay 2160p x265</title>
>       <guid>https://pctreload1.com/descargar/serie-4k/fundacion/temporada-1/capitulo-02/</guid>
>       <jackettindexer id="newpct">NewPCT</jackettindexer>
>       <comments>https://pctreload1.com/descargar/serie-4k/fundacion/temporada-1/capitulo-02/</comments>
>       <pubDate>Sat, 25 Sep 2021 00:00:00 +1200</pubDate>
>       <size>5261335040</size>
>       <description />
>       <link>http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhYOWg4aGw5MEJjWjh2aEVVWnFhdWNmWDRVcHlyaUJVMEVtX3ZjNjNkWmo1X1BhYkk5SFJWVDkwRFFCY1dWRTNxUUUyUGZldjdGcHN5YTZjRFhtZVBlUVhwUl80YUswdVBTUm51enA4eHZzb2k2MHJ1Vng1ZG56b1dMMU5JaG1IOF9NR0xvZjVJUklnMVBXTUg4SXJseGhtc3paQ3M0VjhhWGlfeXR5QzAxSElGazQzdFNfV29oajFmc1Z4TWVHUVA4&amp;file=Foundation+Temporada+1+SPANISH+BluRay+2160p+x265</link>
>       <category>2000</category>
>       <enclosure url="http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhYOWg4aGw5MEJjWjh2aEVVWnFhdWNmWDRVcHlyaUJVMEVtX3ZjNjNkWmo1X1BhYkk5SFJWVDkwRFFCY1dWRTNxUUUyUGZldjdGcHN5YTZjRFhtZVBlUVhwUl80YUswdVBTUm51enA4eHZzb2k2MHJ1Vng1ZG56b1dMMU5JaG1IOF9NR0xvZjVJUklnMVBXTUg4SXJseGhtc3paQ3M0VjhhWGlfeXR5QzAxSElGazQzdFNfV29oajFmc1Z4TWVHUVA4&amp;file=Foundation+Temporada+1+SPANISH+BluRay+2160p+x265" length="5261335040" type="application/x-bittorrent" />
>       <torznab:attr name="category" value="2000" />
>       <torznab:attr name="seeders" value="1" />
>       <torznab:attr name="peers" value="2" />
>       <torznab:attr name="downloadvolumefactor" value="0" />
>       <torznab:attr name="uploadvolumefactor" value="1" />
>       <torznab:attr name="coverurl" value="https://pctreload1.com/pictures/f/thumbs/" />
>     </item>
>     <item>
>       <title>Foundation Temporada 1 SPANISH BluRay 2160p x265</title>
>       <guid>https://pctreload1.com/descargar/serie-4k/fundacion/temporada-1/capitulo-01/</guid>
>       <jackettindexer id="newpct">NewPCT</jackettindexer>
>       <comments>https://pctreload1.com/descargar/serie-4k/fundacion/temporada-1/capitulo-01/</comments>
>       <pubDate>Sat, 25 Sep 2021 00:00:00 +1200</pubDate>
>       <size>5261335040</size>
>       <description />
>       <link>http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhYWUFsU0UwVHdIV01BWTJDUkdveV95S3VxTTBhZVhVX2RTTXlUYkl3THUxa2J3YmlxUFhhaGhESGR3Mzl2OHBvZkkzZzRvTldORmNNTEl6c3RFWnVOMl9GRXJTOTJoY3JXZTNfeFRRUVdTYU95MjhNSklLNjZZVVF2eVh5UU1mcG9OcHRXLXU3anpEdWZDdHMzSXZkSzloTzUxOE5hLW93NGx5ay1jSmJKT0dPamdyT1pZYlNUTkVfS0lRUHBVWjRB&amp;file=Foundation+Temporada+1+SPANISH+BluRay+2160p+x265</link>
>       <category>2000</category>
>       <enclosure url="http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhYWUFsU0UwVHdIV01BWTJDUkdveV95S3VxTTBhZVhVX2RTTXlUYkl3THUxa2J3YmlxUFhhaGhESGR3Mzl2OHBvZkkzZzRvTldORmNNTEl6c3RFWnVOMl9GRXJTOTJoY3JXZTNfeFRRUVdTYU95MjhNSklLNjZZVVF2eVh5UU1mcG9OcHRXLXU3anpEdWZDdHMzSXZkSzloTzUxOE5hLW93NGx5ay1jSmJKT0dPamdyT1pZYlNUTkVfS0lRUHBVWjRB&amp;file=Foundation+Temporada+1+SPANISH+BluRay+2160p+x265" length="5261335040" type="application/x-bittorrent" />
>       <torznab:attr name="category" value="2000" />
>       <torznab:attr name="seeders" value="1" />
>       <torznab:attr name="peers" value="2" />
>       <torznab:attr name="downloadvolumefactor" value="0" />
>       <torznab:attr name="uploadvolumefactor" value="1" />
>       <torznab:attr name="coverurl" value="https://pctreload1.com/pictures/f/thumbs/" />
>     </item>
>     <item>
>       <title>Foundation Temporada 1 SPANISH BluRay 1080p</title>
>       <guid>https://pctreload1.com/descargar/serie-1080p/fundacion/temporada-1/capitulo-02/</guid>
>       <jackettindexer id="newpct">NewPCT</jackettindexer>
>       <comments>https://pctreload1.com/descargar/serie-1080p/fundacion/temporada-1/capitulo-02/</comments>
>       <pubDate>Fri, 24 Sep 2021 00:00:00 +1200</pubDate>
>       <size>5261335040</size>
>       <description />
>       <link>http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhWQlZLdjAyR3hBNUgwUS1ET2dGSE9SNDhsRDFWMXcySGNxbG1LRXU1LVcwdFVLMWlPSlBxZ0Focm5wS3QtSnprUzY5RnBkT3J3UWhURDhVVWFsVGtIcVhhVVpnOTNjUDR1dE14bTVkYVBpd0w4QlVNV1FLQXFMTHNGT2hueDVQSU4wXzZDYzZqQTd6dlk2aVNWd3ZMQzFhcUpmekotRzdaMzNQZjdHR2Y5elYwcTBTVVZYSVgyMlAxYWRTZzlWT3pV&amp;file=Foundation+Temporada+1+SPANISH+BluRay+1080p</link>
>       <category>2000</category>
>       <enclosure url="http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhWQlZLdjAyR3hBNUgwUS1ET2dGSE9SNDhsRDFWMXcySGNxbG1LRXU1LVcwdFVLMWlPSlBxZ0Focm5wS3QtSnprUzY5RnBkT3J3UWhURDhVVWFsVGtIcVhhVVpnOTNjUDR1dE14bTVkYVBpd0w4QlVNV1FLQXFMTHNGT2hueDVQSU4wXzZDYzZqQTd6dlk2aVNWd3ZMQzFhcUpmekotRzdaMzNQZjdHR2Y5elYwcTBTVVZYSVgyMlAxYWRTZzlWT3pV&amp;file=Foundation+Temporada+1+SPANISH+BluRay+1080p" length="5261335040" type="application/x-bittorrent" />
>       <torznab:attr name="category" value="2000" />
>       <torznab:attr name="seeders" value="1" />
>       <torznab:attr name="peers" value="2" />
>       <torznab:attr name="downloadvolumefactor" value="0" />
>       <torznab:attr name="uploadvolumefactor" value="1" />
>       <torznab:attr name="coverurl" value="https://pctreload1.com/pictures/f/thumbs/" />
>     </item>
>     <item>
>       <title>Foundation Temporada 1 SPANISH BluRay 1080p</title>
>       <guid>https://pctreload1.com/descargar/serie-1080p/fundacion/temporada-1/capitulo-01/</guid>
>       <jackettindexer id="newpct">NewPCT</jackettindexer>
>       <comments>https://pctreload1.com/descargar/serie-1080p/fundacion/temporada-1/capitulo-01/</comments>
>       <pubDate>Fri, 24 Sep 2021 00:00:00 +1200</pubDate>
>       <size>5261335040</size>
>       <description />
>       <link>http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhWaTVCLUZacUdacFEyNmZDWmI3cHEtcHNqczlCMUdPSE9vR0FUcEtfLWp5dmJ5NkZNdEFMX0l6Qkd3NXIwdmttcTVUNDZ1NV80UnB0RWxmSlZHSndIU2pGc08tbjlsR1h5OFhhSHJwRXgxS2hjcFlwNUV4OENUYjIxRFNoQUNjYVI2dlhJMTJXV2hkZkFvVGxxYTlEaXZGRzR1TDFTS2ZyNUdJZVRNSy1Cb05naTVwa1g3cTJqNnVGUmtMVjZESjV3&amp;file=Foundation+Temporada+1+SPANISH+BluRay+1080p</link>
>       <category>2000</category>
>       <enclosure url="http://127.0.0.1:9117/dl/newpct/?jackett_apikey=****redacted*****&amp;path=Q2ZESjhBamhjRFhlWGlGQnJhT2hlb01WVXhWaTVCLUZacUdacFEyNmZDWmI3cHEtcHNqczlCMUdPSE9vR0FUcEtfLWp5dmJ5NkZNdEFMX0l6Qkd3NXIwdmttcTVUNDZ1NV80UnB0RWxmSlZHSndIU2pGc08tbjlsR1h5OFhhSHJwRXgxS2hjcFlwNUV4OENUYjIxRFNoQUNjYVI2dlhJMTJXV2hkZkFvVGxxYTlEaXZGRzR1TDFTS2ZyNUdJZVRNSy1Cb05naTVwa1g3cTJqNnVGUmtMVjZESjV3&amp;file=Foundation+Temporada+1+SPANISH+BluRay+1080p" length="5261335040" type="application/x-bittorrent" />
>       <torznab:attr name="category" value="2000" />
>       <torznab:attr name="seeders" value="1" />
>       <torznab:attr name="peers" value="2" />
>       <torznab:attr name="downloadvolumefactor" value="0" />
>       <torznab:attr name="uploadvolumefactor" value="1" />
>       <torznab:attr name="coverurl" value="https://pctreload1.com/pictures/f/thumbs/" />
>     </item>
>   </channel>
> </rss>
> ```

also tryed now again this is one of the latest movies uploaded on the web. Again it finds it if you add the search query but not if you don't add anything
![image](https://user-images.githubusercontent.com/2190005/134829469-f0495e94-6bc6-40e8-bf4d-0b772c181418.png)
![image](https://user-images.githubusercontent.com/2190005/134829494-e31502e9-820b-4409-aaf3-86f38e7b5151.png)
![image](https://user-images.githubusercontent.com/2190005/134829574-3a32a5ea-5d24-480d-8f7f-0485a14cf329.png)
The movies on the last capture are uploaded before the previous ones.

**Comment by garfield69** [comment]
I think its down to the design of the web site you are monitoring.
the newpct indexer is written in C#, and for the keywordless searches (which is what the RSS feed is essentially doing), it fetches all the results from the web sites' `ultimas-descargas/` page.
If the web site does not return your expected results, then that most likely means that the web site is not including some of the results in between the times your are fetching that page with your rss keywordless query.
It may be the case that for newpct you may need to poll more frequently, perhaps try once every half hour instead of hourly?

**Comment by viseniv** [comment]
> I think its down to the design of the web site you are monitoring.
> the newpct indexer is written in C#, and for the keywordless searches (which is what the RSS feed is essentially doing), it fetches all the results from the web sites' `ultimas-descargas/` page.
> If the web site does not return your expected results, then that most likely means that the web site is not including some of the results in between the times your are fetching that page with your rss keywordless query.
> It may be the case that for newpct you may need to poll more frequently, perhaps try once every half hour instead of hourly?

Ok.
I try with 15min poll frequency and post the results here.
Thanks
