### ISSUE TITLE
[req]: pornoslab

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#12336]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name:pornoslab
- URL:https://pornoslab.com
- Description:pornoslab is a public torrent tracker for adult content
```

**Comment by garfield69** [comment]
v0.18.815

**Comment by garfield69** [comment]
https://pornoslab.com/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.21.983
