### ISSUE TITLE
[req]: Extremlymtorrents.ws Categories UPDATE ?

### ISSUE THREAD

**Issue by extremlymtorrents** [Jackett/Jackett#12333]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

some updates on XTR pls ! 

### Describe the solution you'd like

We have added new categories https://extremlymtorrents.ws/torrents.php?cat=52

and huge import https://extremlymtorrents.ws/xsearch.php

**Comment by garfield69** [comment]
I'll take a look shortly and update the indexer as needed. Thanks for the report.

**Comment by garfield69** [comment]
We will not be using the external search, but continue to use the regular https://extremlymtorrents.ws/torrents.php

**Comment by extremlymtorrents** [comment]
ok thx 

i have over 100.000 downloads per week from Jacket

**Comment by extremlymtorrents** [comment]
i have made the downloads public for this script !

**Comment by garfield69** [comment]
v0.18.805
