### ISSUE TITLE
[req]: add same indexer more than once

### ISSUE THREAD

**Issue by TalKashi** [Jackett/Jackett#12359]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I would like to have in sonarr/radarr two indexers, one for freeleech torrents and the other to the rest. If I would be able to configure it I can give different priority to each indexer on sonarr/radarr (prefer a freeleech torrent than non-freeleech one or vice versa).
I was not able how I can do it with my favorite torrent site (torrentleech) which in Jackett has a checkbox if to search for freeleech only torrents.

### Describe the solution you'd like

I think it will be great if I will be able to add the same indexer more than once and give an appropriate tag (as today I can use tags within sonarr/radarr)

### Describe alternatives you've considered

The only solution I have ATM is to have two processes of Jackett and I don't like this approach.

**Comment by ilike2burnthing** [comment]
Radarr allows you to prefer freeleech in their Custom Format settings. As for Sonarr - https://github.com/Jackett/Jackett/issues/11707#issuecomment-838227929

As for the feature request - https://github.com/Jackett/Jackett/issues/10525 (see also for manual workaround)
