### ISSUE TITLE
[nyaa-pantsu] Exception (nyaa-pantsu): Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: No route to host (192.168.0.111:8191)

### ISSUE THREAD

**Issue by MozkaTeacher** [Jackett/Jackett#12364]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
- OS:
- .Net Runtime: [.Net-Core/.Net-Framework/Mono]
- .Net Version:
- Jackett Version:
- Last Working Jackett Version:
- Are you using a proxy or VPN? [yes/no]
```

### Description

I tried to add nyaa.lol on jackett 

### Logged Error Messages

Cancellation token

### Screenshots

![AB7C4F79-DB20-4EBB-98F2-B41D23117F09](https://user-images.githubusercontent.com/43102748/135778821-1e0a7ffb-a069-4719-a18a-d940550b3b2d.jpeg)

**Comment by ilike2burnthing** [comment]
The nyaa.lol proxy was [removed](https://github.com/Jackett/Jackett/issues/12211#issuecomment-926078385), update your Jackett install and try again.

**Comment by garfield69** [comment]
nyaa.net is down, follow  #8484 for updates on this site.
and we are not allowed to use nyaa.lol.
closing.
