### ISSUE TITLE
[isoHunt] Silently Fails in Sonarr

### ISSUE THREAD

**Issue by cron410** [Jackett/Jackett#1236]
I have looked at the previous issues here with isoHunt. Using the Download Locally button in Jackett saves the .torrent files just fine. Sonarr will sometimes save the .torrent file.

http://imgur.com/a/CtktZ the torrent circled worked fine. The torrents with a red line work fine in Jackett with Download Local.

Jackett version:  0.7.1242.0
Mono version (if not using Windows):  Windows

-------------------------------

**Comment by cron410** [comment]
Enhanced Log: https://pastebin.com/YJVnz0Ju

**Comment by PaintPauller** [comment]
i am having this exact problem as well !!!
only happens with isoHunt 
Jackett Version 0.7.1310.0
Sonarr Version 2.0.0.4689

**Comment by kaso17** [comment]
Is isohunt still alive?
Currently it seems like search and latest torrents don't work.

**Comment by krin-san** [comment]
Yep, just installed Jackett today and IsoHunt failed testing. I also failed to link it in Sonarr/Radarr.
I found slightly website with similar url: https://isohunts.to Is it a mirror?

**Comment by kaso17** [comment]
I removed it (ecc438b21e4aab8781e0b9ba37e806e9ffafedbc) as the website is now starting to distribute a "binary client" (malware).
