### ISSUE TITLE
[alpharatio] https://alpharatio.cc/ offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12365]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
n/a
```

### Description

site returning the Apache2 Ubuntu default page

### Logged Error Messages

n/a

### Screenshots

![image](https://user-images.githubusercontent.com/6933240/135787855-838a930c-984d-4028-b9ef-d2c49425d23e.png)

**Comment by garfield69** [comment]
now returning Error 521 Web server is down

**Comment by ilike2burnthing** [comment]
Login page is back up if you wanna check the rest of the site.

**Comment by garfield69** [comment]
online.
