### ISSUE TITLE
[LimeTorrents][ETTV][ISOHunt2][Kickasstorrents-to] Problem with torrent download URL

### ISSUE THREAD

**Issue by Wolvverine** [Jackett/Jackett#12368]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: RSS,Firefox,Asustor Download Center
Using FlareSolverr: Disabled
Using proxy: Disabled
Running in Docker: Yes
OS version: Docker 2.10.2 (64bit)
Jackett Version v0.18.896
```

### Description

rss:
http://jacket-node:19117/api/v2.0/indexers/all/results/torznab/api?apikey=xxxxxxx&t=search&cat=&q=

Downoads url for torrents:

http://jackett-node:19117/dl/limetorrents/?jackett_apikey=xxxxxxxn&path=Q2ZESjhHVGxVc1RyZWtoSXQ1V1R2Ql9oOGJVeXZoSUlXOGhzTElvcGQ1N1YtYmx1alNnQ1pCTW42ajc0X0trcmp2Z2lma21qZklaVTVXWEZxNVlBMVRndXdYQ1NLSjhwVTBjekVUaERTcFQ3WkZWSkw0cEV2NjNLbzNFN0pOWkdzOHpiY0dKMGJuR1FaX081aHVZcUxlaXhmQUc3NG5YRUt5TE5mMFBtX05heGo0Wm01QkttX2Z2U3hhUTBTeTBCQUVTQW1RaEhMcHlaXzlIRUpaTUNtbE5DU2lLUzdfd3poYjduRi12U1FjT3lVOXdEOXc2ZFczUU1waVMzclAyaF9NTzBHVjVrZ3NBMjNISmloVTRLMHhpTFVvcw&file=Big+Sky+2020+S02E01+Wakey+Wakey+1080p+AMZN+WEBRip+DDP5+1+x264

http://jackett-node:19117/dl/kickasstorrents-to/?jackett_apikey=xxxxxxxn&path=Q2ZESjhHVGxVc1RyZWtoSXQ1V1R2Ql9oOGJVVmYtMktKX3BWdE9Ia25MRjZsbC15NG02VkNoeGVpRmlNX3R3SVU2cjFjYl9TMnVYa0lpZjVyVUExOFRlN2FTWkJIckVRSTJ2UVBNYmFWU09JYlZJU0lidzR6dlRqZFItcC1tTk5ORHNaeS1rWTdQTXRvVGtFSHoxVTEyUWd1N19nX3Q3eFFuLURUZmNRNm9vclBPbmxGUnFFTkhoQ2xVOHgwdC1OdWE3c3k0Y01SUmtQRmV1UkhuQ2J2azJRWjRz&file=Day+13+(2021)+1080p+WEBRip+2+0+YTS+YIFY

http://jackett-node:19117/dl/ettv/?jackett_apikey=xxxxxxxn&path=Q2ZESjhHVGxVc1RyZWtoSXQ1V1R2Ql9oOGJXSDd0WGd3M1dhRmVmdlU2MGVwU1hPc3lwd205TDlNV0k5eDN5OVdpcEs3MUVXVGVhRHZoMFNwTGxQZnUxa3Zfb3Y4WERNSVh3YldCUVQxSXRaUzgtQXo4OWRDbVoya2NJR0pkSFdqZldFem1LT1ZYQl80ZEJ6NXpXcEtMN09ualRRTGJpbHp4VFFNVXRpRjRsRVoyOGhfQjRpcnlqQ2xMQVBuN0VOaWFUOFU2bGo2bEpoaEM4QXZRdGl1ME1qaGpWOVZaay1qbnpHZklGOF9TZnFJZTVn&file=As+the+Village+Sleeps+(2021)+%5B1080p%5D++%5BWebRip%5D+%5BYTS%5D

Result:
Unable to add torrent download URL

### Logged Error Messages

nothing

**Comment by ilike2burnthing** [comment]
These indexers all use the download block, so when you click the download button Jackett has to request the torrent's details page to get the .torrent or magnet link, therefore you can't just copy this into a torrent client.

If your client supports it, look into using the blackhole directory instead.
