### ISSUE TITLE
problem JSON

### ISSUE THREAD

**Issue by lucasboulouys** [Jackett/Jackett#1237]
i can't search, and when i test the indexer, i have this error message
on T411

Additional text encountered after finished reading JSON content: ). Path '', line 1, position 2.

i have try to delete t411 indexer
and when i add again, i have this message

Configuration failed: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

Jackett version:   0.7.1256.0

**Comment by lucasboulouys** [comment]
i have delete t411 indexer 
and when i add again, i have this message 

Configuration failed: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by Blackdixxa** [comment]
It's a problem on their side :)

https://api.t411.li/discussion/comment/680387#Comment_680387

they'll resolve it asap.

**Comment by lucasboulouys** [comment]
thx @Blackdixxa   it's ok    i wait for

**Comment by Blackdixxa** [comment]
Yeah I was wondering if it was the last update and no traces of changes on jackett side so I dug in t411 forums and saw this :)
You're welcome !

Regards,
