### ISSUE TITLE
[req]: megapeer

### ISSUE THREAD

**Issue by Nuke142** [Jackett/Jackett#12371]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: MegaPeer
- URL: http://megapeer.ru http://alt.megapeer.ru
- Description: Popular open russian torrent-tracker with Movies/TV
- Additional Comments: http://megapeer.ru/search.php
```

**Comment by garfield69** [comment]
v0.18.901

**Comment by wpresident** [comment]
This tracker gives unexpected results - i search "Sonic the Hedgehog 2 (2022)" film - in search i paste "Соник 2" (russian letters) but in results i see "Соник (2020)".
This problem only with this tracker.

**Comment by ilike2burnthing** [comment]
The site doesn't use 1 character keywords (I'll resolve that shortly), but even if it did it also does partial word matching, so searching `sonic 2` would match `Sonic the Hedgehog 2` but also `Infrasonic Spring Selection 2021`.

**Comment by garfield69** [comment]
v0.20.1005

**Comment by wpresident** [comment]
> v0.20.1005

ok i think this tracker is suxx, will not use it because partial word matching

![image](https://user-images.githubusercontent.com/19406558/166430254-ee6fa74b-9dea-4a0d-8714-3a5326a30086.png)

![image](https://user-images.githubusercontent.com/19406558/166430196-23f3334e-918f-4ce3-be13-c1b9135e3e96.png)

**Comment by garfield69** [comment]
http://megapeer.ru/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
http://alt.megapeer.ru/ online

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
@Nuke142  v0.20.1907 for update indexer which does andmatch on row results to reduce collateral pickup

**Comment by ilike2burnthing** [comment]
https://megapeer.vip/ - working
https://megapeer.vip/browse.php?search= - `Sorry, maintenance work is being carried out.`

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
megapeer search no longer returns results for keyword `%%`.

**Comment by garfield69** [comment]
https://megapeer.vip/ > Cloudflare Connection timed out Error code 522

**Comment by garfield69** [comment]
online
