### ISSUE TITLE
Jackett is not detecting latest update

### ISSUE THREAD

**Issue by desimaniac** [Jackett/Jackett#1238]
Jackett is not detecting the latest version (v0.7.1256).

Logs: https://gist.github.com/desimaniac/6a9bb9c45a2bfb3892e5ee85517b4b56

Jackett Version 0.7.1242.0
Mono JIT compiler version 4.6.2

**Comment by raspdealer** [comment]
Can you test with the one released in the last 24 hours?
If you want to update to pre-release, you need to check it in your settings.

**Comment by kaso17** [comment]
I assume this is no longer a problem.
