### ISSUE TITLE
[ourbits] Test search in Ourbits => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by TiarnanRedmond** [Jackett/Jackett#12386]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: Firefox
Using FlareSolverr: Disabled
Using proxy: Disabled
App config/log directory: folder path
Running in Docker: No
Jackett variant: Version v0.18.911
OS version: Debian GNU/Linux 10 (buster) (64bit)
Environment version: n.n.nn (folder path)
Starting Jackett vn.nn.nn
```

### Description

I logged out and logged in then changed the cookies but it still doesn't work. Could you please help me?

Thank you

### Logged Error Messages

I couldn't paste all logs it doesn't allow more than 65536 characters so I paste to a gist from update request for jackett to test ourbits. Here: https://gist.github.com/TiarnanRedmond/6adb79104c2694aed1a457a7e8892193

**Comment by garfield69** [comment]
the indexer appears to be hardcoded to handle only one of the two possible date layouts.
I will add the second date format to the indexer shortly.
In the mean time, you should be able to get your indexer going by accessing the ourbits website, accessing the **control panel** and navigating to the **web settings**, and changing the **time display type** from **time elapsed** to **time added**.

**Comment by TiarnanRedmond** [comment]
> the indexer appears to be hardcoded to handle only one of the two possible date layouts. I will add the second date format to the indexer shortly. In the mean time, you should be able to get your indexer going by accessing the ourbits website, accessing the **control panel** and navigating to the **web settings**, and changing the **time display type** from **time elapsed** to **time added**.

It was already on **Time Added** and I changed to **Time Elasped** now it works. Thank you

**Comment by garfield69** [comment]
v0.18.925
