### ISSUE TITLE
Jacket give empty in Rutracker.org manual search and rss feed

### ISSUE THREAD

**Issue by Ratiboriy** [Jackett/Jackett#12397]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
OS: Windows 10

.Net Runtime: .Net-Framework

.Net Version: 4.5

Jackett Version: v0.18.940

Last Working Jackett Version: issue in all version

Are you using a proxy or VPN? [yes/no] I use 8.8.8.8 DNS Server on my router - this way i get access to Rutracker.org without any VPN or Proxy
```

### Description

Jackett give zero torrent both in manual search and in RSS feed with cat=100115 for example, but if i use Search on Rutracker.org - i see many torrents!  

### Logged Error Messages

There no Error Messages, just zero torrent in manual search and rss feed 

### Screenshots

![image](https://user-images.githubusercontent.com/89318857/136929682-46dcaf4a-1bad-46a8-8a24-30f02ea17678.png)
![image](https://user-images.githubusercontent.com/89318857/136930423-cbc657e3-c35f-47aa-98d8-2fe905062f99.png)
![image](https://user-images.githubusercontent.com/89318857/136930684-4dd05d5c-7fe1-465d-bb0d-426cfc1c977f.png)

**Comment by garfield69** [comment]
v0.18.984
