### ISSUE TITLE
[req]: extratorrent.st

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12390]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: ExtraTorrent-st
- URL: https://extratorrent.st/
- Description: clone of extratorrent.si
- Additional Comments: given the other extratorrent flavours are all broken ATM, (extratorrents.it search not working, extratorrent.si offline), might as well add this one to the pot.
the following proxies are available:
  - https://extratorrent.unblockit.kim/
  - https://extratorrent.nocensor.work/
```

**Comment by garfield69** [comment]
v0.18.940

**Comment by ilike2burnthing** [comment]
https://extratorrent.st/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://extratorrent.st/ - Gateway time-out Error code 504

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://extratorrent.st/ have added cloudflare but its not working on my chrome browser 115 and Edge 115
However it is working on opera 100, vivaldi 6.1 and firefox 116

**Comment by ilike2burnthing** [comment]
uBlock Origin was blocking the Cloudflare 'verify you are human' box, not sure why. Disabled uBO and it's working fine in Edge and Chrome.

**Comment by garfield69** [comment]
https://extratorrent.st/ , https://extratorrent.ninjaproxy1.com/ ,  https://extratorrent.proxyninja.org/ : cloudflare Gateway time-out Error code 504

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://extratorrent.st/ > cloudflare Connection timed out Error code 522

**Comment by garfield69** [comment]
online
