### ISSUE TITLE
[vizuk] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12395]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
n/a
```

### Description

https://torrent.vizuk.li/ returning ERR_CONNECTION_TIMED_OUT
https://www.uptrends.com/tools/uptime reports TCP Connection Failed across all 43 checkpoints worldwide.

### Logged Error Messages

n/a

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/171793580-a435dced-1a94-4ee2-8b68-67946476f6ef.png)

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://torrent.vizuk.li/ domain not found

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/12395#issuecomment-1145604023

**Comment by ilike2burnthing** [comment]
@garfield69 do you expect this to reopen?

**Comment by garfield69** [comment]
Meh, no clue. But its been a month and nothing has changed so lets blow it away, I doubt anyone will miss.

**Comment by garfield69** [comment]
v0.20.1814
