### ISSUE TITLE
[REQ] UK TorrentDay tracker

### ISSUE THREAD

**Issue by LFFPicard** [Jackett/Jackett#124]
TorrentDay on Jackett links to the general site.
The UK required connecting through a different URL https://tdonline.org/
Therefore anyone in the UK trying to add TD on jackett will not be able to add this.

**Comment by flightlevel** [comment]
Are you on an old version, this got changed 6 weeks ago. https://github.com/Jackett/Jackett/commit/058c12175de3c5fcaecf2e50e2f18f62a038e7db
