### ISSUE TITLE
[Hon3yHD] not working with Jackett

### ISSUE THREAD

**Issue by kdizzay** [Jackett/Jackett#1240]
I am also facing this issue on since 1242 when I first installed and now after updating to 1256 for hon3yhd. Here are my logs:

Observations from logs :

Query that Jackett makes : IWebClient.GetString(Url:https://hon3yhd.com/browse.php?search=Akira&incldead=1)

Result from query :

IWebClient: Returning OK =>

<title>MySQL Error</title> <style>P,BODY{ font-family:arial,sans-serif; font-size:11px; }</style>
MySQL Error

There appears to be an error with the database.
You can try to refresh the page by clicking here. 

Error Returned
<textarea rows="15" cols="60"> SQL error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1 SQL error code: 1064 Date: Wednesday 05th of April 2017 11:00:07 PM</textarea>
We apologise for any inconvenience
Now if I try the same query (https://hon3yhd.com/browse.php?search=Akira&incldead=1) from browser I get the same syntax error message as above.

Now when I do a manual search on the website itself here is what the query looks like :

https://hon3yhd.com/browse.php?search=Akira&searchin=all&incldead=1 (with 'all')
https://hon3yhd.com/browse.php?search=Akira&searchin=title&incldead=1 (with 'name')
https://hon3yhd.com/browse.php?search=Akira&searchin=descr&incldead=1 (with 'description')

Seems like they have changed the search function where a mandatory additional parameter 'Name' 'Description' or 'All' is added to all searches which is the &searchin= part of the call. So if I plug in the new link now in the browser I get proper results.

Looks like the code in Jackett for Hon3yHD has to be changed to modify to the new call.

Again, I am not a tech heavy user, this was just my observations so hope it helps in fixing this issue.

Jackett version: 0.7.1256.0
Mono version (if not using Windows): Windows

Thanks.

**Comment by adamwinn** [comment]
It looks like the website is having issues.  There's a mysql error.  It'll probably be fixed soon or you can contact the admins about it

```
MySQL Error
There appears to be an error with the database.
```

**Comment by kdizzay** [comment]
The error is saying though that the syntax of the query is wrong rather than the call not going through (from what I can tell). I have been having this issue for 2-3 months now.

SQL error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1 SQL error code: 1064

**Comment by adamwinn** [comment]
That error is on their side.  It's saying that the database query they coded has a syntax error.  I'm a web developer and have seen millions of these.  You should be able to reproduce it via the website too.  It is possible they changed their search functions so now the old way fails and Jackett would need to be updated to the new way that doesn't produce an error.  If you have an invite, I can look into it.

**Comment by kdizzay** [comment]
Yeah, I was able to reproduce it on the website. I think as you said they changed the search functions so the Jackett code will need to be changed for this tracker to query with the new correct syntax as I posted above in the difference between the two, namely the addition of '&searchin=' in the query Jackett makes. Can you try to make the change for the call in your local repo and let me know? I can also change it in mine and try to see if it works. The problem regarding invite is that it is not allowing me to create an invite code since their 'user limit reached' as of now. 

I am pretty sure that the above change will work , where we add the '&searchin=' in the query. I verified this on the website. If I had the knowledge to change the code locally and test I'd have done so. Again, if you can give me the changes to make in the requisite files, I can do so and test and get back to you. Thanks for looking into it.

**Comment by kdizzay** [comment]
Hi, I have fixed the issue and verified that I get results properly from Hon3yHD. 

File changed : /src/Jackett/Definitions/hon3yhd.yml   (Added new line 72)
 
69     inputs:
70       $raw: "{{range .Categories}}c{{.}}=1&{{end}}"
71       search: "{{ .Query.Keywords }}"
**72       searchin: "title"**
73       incldead: "1"

I understand that the dev can't just port a change on my word alone, but unfortunately I have no way of giving an invite and it's a hassle for me to setup a Linux machine with git to fork and ultimately submit a pull request. But I hope this helps any other person with the issue on this tracker since they have changed their query syntax.

**Comment by desimaniac** [comment]
@kdizzay you dont need a linux machine for a minor change. just fork it and make the change right on github and send pull request back.

**Comment by kaso17** [comment]
Thank you for debugging it. 
Added with 478595594101a80e1752d8c10b9bf5b67ee14706
For such simple changes you could just use the github online editor (pen icon when looking at files), no need to install anything.
