### ISSUE TITLE
[Hush] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12414]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
n/a
```

### Description

https://team-hush.org/ returns ERR_CONNECTION_TIMED_OUT
https://www.uptrends.com/tools/uptime reports TCP Connection Failed across 42 checkpoints worldwide.

@pipopop @kcgthb is the indexer working for you?
do you know if the site is gone, broken or moved to a new domain?

### Logged Error Messages

n/a

**Comment by pipopop** [comment]
@garfield69 : no the site is dead since this summer.

**Comment by garfield69** [comment]
v0.18.992
