### ISSUE TITLE
Discard on jackett side torrent links

### ISSUE THREAD

**Issue by elpedriyo** [Jackett/Jackett#12422]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hello,

I am used to do my personal replaces on trackers.yml, for making radarr work correctly with some of my trackers.
Now I am facing the issue, medusa doesn't have a quality category for FULL BLURAYS or BRDISKs.
I see there is a replace option for FULLs to be converted to BRDISK, just because of radarr.
Is there any -name: XXXX so that I can make Jackett to discard them, and do not pass them through to medusa/radarr/whatever, as I am not interested in those?

Kind regards

### Describe the solution you'd like

find a -name: XXXX to match FULLs and discard them on jackett side. Not to be passed to whatever scrapper software I am using

**Comment by elpedriyo** [comment]
Yes, I do not want to replace FULLs by BRDISK. I want directly jackett not passing that torrent to medusa.
So if I have the TV show called The flash full bluray. I want directly that torrent not to be passed at any time. Directly if jackett would have not detected any tv show

**Comment by garfield69** [comment]
so you could try this:
```yaml
  rows:
    selector: table > tbody > tr:not(:has(a.view-torrent:contains("Full BluRay")))
```
