### ISSUE TITLE
[NEWPCT] some series identifies them as movies 

### ISSUE THREAD

**Issue by diegargon** [Jackett/Jackett#12426]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.18.1001
```

### Description

Some series identifies them as movies in "latest", i think is because they add a new
category 'serie-4k'
Poster link is broken too

Example:
https://pctmix1.unblockit.kim/descargar/serie-4k/the-good-fight/temporada-5/capitulo-10/

### Logged Error Messages

none

### Screenshots

![jackettbug](https://user-images.githubusercontent.com/6043996/137587335-91868551-bf36-43d6-bb0c-f7fbe3d43aff.png)

**Comment by garfield69** [comment]
BTW broken poster are as given by the web site, nothing can be done about this.

**Comment by diegargon** [comment]
true, I had not noticed

**Comment by garfield69** [comment]
I give up.
This indexer is the most complicate spaghetti I've ever had the misfortune to look at and having spent the last 9 hours trying to understand the logic I'm only partially successful in adding the UHD support.
Very frustrating,  the indexer has had so many cooks in that kitchen that the soufflé is more like a pizza.
This needs a proper C# dev to fix.

**Comment by diegargon** [comment]
A fast look of a non c# programmer seems the indexer looks for 'hdtv' for catalog as a show if not catalog as movie
L543
L633-636

And that new categories haven't 'hdtv'  have 4KWebRip but there shows without hdtv/4KWebRip 

If that that true the logic its use the words 'Temp.' 'Temporada'

**Comment by garfield69** [comment]
v0.20.440
