### ISSUE TITLE
Torrentland not reporting the season

### ISSUE THREAD

**Issue by elpedriyo** [Jackett/Jackett#12427]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/pedro/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 20.10 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.8.0.63 (64bit OS) (64bit process)
Environment version: 5.0.11 (/opt/jackett/)
Starting Jackett v0.18.995
```

### Description

I am currently trying to search in tracker torrentland this TV show: El juego del calamar S01
If I do it in the tracker, it shows the result:
![image](https://user-images.githubusercontent.com/3207791/137593439-825685f7-8353-4c0d-8687-ec97d016b0db.png)

but if I do it in jackett, I get 0 results:

![image](https://user-images.githubusercontent.com/3207791/137593460-9c455e67-583f-4b75-82e3-8954c0d4ed27.png)

### Logged Error Messages

N/A

**Comment by elpedriyo** [comment]
Any idea on why this is happening?

**Comment by vinanrra** [comment]
IMO the best it's to be able to get new series and old search manually because if the have changed the format all new should be like that.

**Comment by garfield69** [comment]
v0.18.1008
