### ISSUE TITLE
[sharewood] Test search in Sharewood => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by TheoDemarque** [Jackett/Jackett#12428]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Dernière version de Jackett sans proxi et sans flarre solveur
```

### Description

Je ne peut plus récupérer les infos de ce site en particulier

### Logged Error Messages

Test search in Sharewood => Found no results while trying to browse this tracker

**Comment by ilike2burnthing** [comment]
> Please provide the details of the system Jackett is running on. The best way to do this is to restart Jackett, access the dashboard, view the log, and copy/paste replacing the example below with the last 10 Info lines at the bottom of the log.

Also provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
