### ISSUE TITLE
[req]: Slosoul.net

### ISSUE THREAD

**Issue by ClandestineClout** [Jackett/Jackett#12435]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Slosoul
- URL: https://slosoul.net
- Description: General Slovenian site that has torrents with many seeders
- Minimum Seeding Time and Minimum Ratio (if Private): ?
- Additional Comments: ~~TS Special Edition v.8.0~~ TSUE 2.2
```
engine and domain changed

**Comment by garfield69** [comment]
slosoul upgraded engine to TSUE 2.2. Need to upgrade the indexer.

**Comment by garfield69** [comment]
will need to check tomorrow for date processing, as currently there are only 17 torrents onsite, spanning today and yesterday.
and freeleech is untested since there are none atm.
still need to find MR and MST, the faq and rules does not cover it yet.

**Comment by garfield69** [comment]
v0.19.275

**Comment by ilike2burnthing** [comment]
[v0.20.53](https://github.com/Jackett/Jackett/releases/tag/v0.20.53)

**Comment by garfield69** [comment]
seems they have downgraded back to TSSE v8.0 !?!?
reverting indexer upgrades.

**Comment by garfield69** [comment]
v0.20.74

**Comment by garfield69** [comment]
https://slosoul.net/ is running so slow  the operation gets cancelled.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://slosoul.net/ redirect to https://slosoul.net/cgi-sys/suspendedpage.cgi

**Comment by garfield69** [comment]
online.
Note: one of the notices states that the site will be migrating to the dark net by the and of September so if true expect to have to remove this indexer if the *onion.pet or *onion.ws does not work.
no word on what the new dark net address will be yet.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/12435#issuecomment-1260348312

**Comment by garfield69** [comment]
@ClandestineClout  do you know the state of the slosoul site? 
last I read on the site when it was still up, was that they were considering moving to the darknet.
has the site gone, moved to a new domain or just broken?

**Comment by garfield69** [comment]
v0.20.2210

**Comment by ilike2burnthing** [comment]
Looks to be back on the clearnet, though I still can't register.

**Comment by garfield69** [comment]
Hmm. for me the main domain redirects to https://slosoul.net/ts_error.php?errorid=5 and ends with ERR_TOO_MANY_REDIRECTS

**Comment by ilike2burnthing** [comment]
Oh, weird. Maybe it's because you're logged in? Any luck in a private/incognito window? If so, can you sign in there?

**Comment by garfield69** [comment]
no, incognito window behaves the same way. :-(
so then I tried hide.me and got a login page and was able to login. :-)
I'll test the old indexer and reinstate it if it works, or amend it as needed.

**Comment by garfield69** [comment]
v0.20.3063

**Comment by garfield69** [comment]
https://slosoul.net/ cloudflare Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://slosoul.net/ ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://slosoul.net/ Http Timeout

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/12435#issuecomment-1736099616

**Comment by garfield69** [comment]
http://slosoul.net/ nginx set up landing page

**Comment by garfield69** [comment]
v0.22.507
