### ISSUE TITLE
TV-Vault is blocking Jackett requests

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#12447]
TV-Vault is detecting Jackett requests and they are responding with "automated tools are not allowed". Since they don't want us, we should remove the indexer at some point. The indexer is not working in Jackett anyway.

They have RSS feeds but they look incomplete to me, for example the size of the torrent and number of peers is not available.
They don't have (or at least I can't found it) a RSS feed with search support.

Maybe someone can reach the site's staff and do some changes in the RSS for us. Wait a few weeks before removing the site.

**Comment by ngosang** [comment]
I had some words with the sysadmin and they are not interested in making changes for Jackett. We should remove this site.

**Comment by garfield69** [comment]
v0.19.124
