### ISSUE TITLE
[New Tracker REQ] CCFBits

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#1244]
**Indexer Name**
CCFBits

**Type**
Movies, Audio, TV, XXX

**Indexer URL**
http://ccfbits.org/

**Indexer Language**
Mandarin Chinese, some English

**Invite**
An invite is required. If someone can supply one, that would be great.

**Note**
CCFBits is a medium-sized Chinese tracker with over 80K torrents

**Comment by kaso17** [comment]
added via 4dc07fbc2605962ee933bbc836b671008d9f32cc
