### ISSUE TITLE
[nyaasi] Exception (nyaasi): certificate validation failed: 

### ISSUE THREAD

**Issue by LordMedric** [Jackett/Jackett#12441]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Synology Jacket and Synology Sonarr
```

### Description

Nyaa.si certificate issue.

### Logged Error Messages

 An error occurred while testing this indexer
Exception (nyaasi): certificate validation failed: [Subject] CN=nyaa.si [Issuer] CN=R3, O=Let's Encrypt, C=US [Serial Number] 0350C7FB065FF367723770E8895C4A96815D [Not Before] 10/4/2021 6:44:34 AM [Not After] 1/2/2022 5:44:33 AM [Thumbprint] 2FC28E1A6ACCEFF94C09827624216D4971DDB86C : The SSL connection could not be established, see inner exception.

### Screenshots

![image](https://user-images.githubusercontent.com/87255710/138142629-b61b751a-325c-48c8-9de9-514283d1ebba.png)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/12341
Switch to Docker installs if possible.

**Comment by LordMedric** [comment]
Telling someone to run it in another system is not a fix.
I have resolved this issue of certificate validation failed due to SSL this is an issue where Synology does not have the updated Intermediate and Root Certificate in its store.

1st This updates the system will all new CA good for systems running Synology DSM 6.2.3 and oldersystems
sudo -i && cp /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt.ORIG && curl -k "https://letsencrypt.org/certs/isrgrootx1.pem" >> /etc/ssl/certs/ca-certificates.crt && synoservice --restart DSM

2nd This adds Lets encrypt the Cert store for checking.
download 
https://letsencrypt.org/certs/isrgrootx1.pem
https://letsencrypt.org/certs/lets-encrypt-r3.pem
and copy them to /etc/ssl/certs

sudo -i && curl -k "https://letsencrypt.org/certs/isrgrootx1.pem" >> /etc/ssl/certs && curl -k "https://letsencrypt.org/certs/lets-encrypt-r3.pem" >> /etc/ssl/certs && synoservice --restart DSM

this worked for me after a few weeks of bagging my head against the wall

**Comment by ilike2burnthing** [comment]
Agreed, hence why I linked to the issue which had a fix that was working for several users.
