### ISSUE TITLE
[req]: 24rolika adult tracker

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#12479]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name:24rolika
- URL:http://24rolika.ru/
- Description: Russian adult content torrents
- Minimum Seeding Time and Minimum Ratio (if Private): no
- Additional Comments: Site have big database and torrent file download directly.
```
Engine: DataLife but with different row selectors

**Comment by garfield69** [comment]
v0.19.100

**Comment by ilike2burnthing** [comment]
Not all results have torrents, and those that do their download links just redirect to the details page.

**Comment by ilike2burnthing** [comment]
Some results still won't have torrents, but they are now a minority.

**Comment by garfield69** [comment]
v0.20.136

**Comment by garfield69** [comment]
http://24rolika.ru/ returns 500 Internal Server Error

**Comment by garfield69** [comment]
v0.20.1101
