### ISSUE TITLE
[feature request] Add a combined torznab feed for all of your added trackers

### ISSUE THREAD

**Issue by zductiv** [Jackett/Jackett#1247]
A combined torznab feed that combines all of the indexers you have added makes maintaining your list of indexers easier rather than having to test/remove/add them in Sonarr/Radarr and whatever else people are using them for.

**Comment by JigSawFr** [comment]
This could be great, but with some problems:
- Some apps haven't implemented pagination
- You will not be able to prioritize sources in apps
