### ISSUE TITLE
Trackers returning no result due to Sonarr search title.

### ISSUE THREAD

**Issue by helenclarko** [Jackett/Jackett#12483]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled	
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads	
Running in Docker: Yes (image build: v0.19.96-ls48)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l	
Jackett variant: CoreLinuxAmdx64	
OS version: Unix 4.19.0.0 (64bit OS) (64bit process)	
Environment version: 5.0.11 (/app/Jackett/)
Jackett v0.19.96
```

### Description

I found this issue with both Dark Shadows and with The Torrent Network.

Sonarr seems to send over the main title and the Alternative titles for searching.
However in my case, the title includes "DE" at the end which prevents me from getting any results from these indexers.

Is it possible to simply have "DE" removed if it is the last thing in the title for these two indexers?

### Logged Error Messages

2021-10-29 15:49:46.0|Debug|Torznab|Downloading Feed (REMOVED)/jackett/api/v2.0/indexers/dark-shadow/results/torznab/api?t=tvsearch&cat=5030,5040,100057,100059,100060,100122,100123&extended=1&apikey=(removed)&offset=0&limit=100&q=Bachelor%20in%20Paradise%20DE&season=3

**Comment by garfield69** [comment]
There is no way that Jackett is going to get involved in auto-correcting an incoming torznab search request by selectively removing parts of the title because of some language differences.
It is the app that is making the requests that has to do the work in these cases.
