### ISSUE TITLE
[erairaws] link can be empty

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12486]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

Usually EraiRaws provides a magnet in the Link field in the xml response,
for example
```xml
<item>
	<title>[Magnet]Isekai Shokudou 2 - 01 [SD][us][br][mx][es][sa][fr][de][it][ru][Airing]</title>
	<link>magnet:?xt=urn:btih:1715F923F383B0AA8555470818356A71118D98F0&amp;dn=%5BErai-raws%5D%20Isekai%20Shokudou%202%20-%2001%20%5B480p%5D%5BMultiple%20Subtitle%5D%5B6D163629%5D.mkv&amp;tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&amp;tr=http%3A%2F%2Fanidex.moe%3A6969%2Fannounce&amp;tr=http%3A%2F%2Ftracker.anirena.com%3A80%2Fannounce&amp;tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&amp;tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&amp;tr=wss%3A%2F%2Ftracker.openwebtorrent.com&amp;tr=http%3A%2F%2Fopen.acgnxtracker.com%3A80%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&amp;tr=udp%3A%2F%2F9.rarbg.to%3A2820%2Fannounce&amp;tr=udp%3A%2F%2F9.rarbg.me%3A2980%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&amp;tr=udp%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&amp;tr=udp%3A%2F%2Fretracker.lanta-net.ru%3A2710%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&amp;tr=http%3A%2F%2Ftracker.acgnx.se%2Fannounce</link>
	<pubDate>Fri, 29 Oct 2021 08:45:04 +0000</pubDate>
	<erai:resolution>SD</erai:resolution>
	<erai:linktype>Magnet</erai:linktype>
	<erai:size>363.84MB</erai:size>
	<erai:infohash>1715f923f383b0aa8555470818356a71118d98f0</erai:infohash>
	<erai:subtitles>[us][br][mx][es][sa][fr][de][it][ru]</erai:subtitles><erai:category>[Airing]</erai:category>	<description>
		<![CDATA[<a href="https://beta.erai-raws.info/episodes/isekai-shokudou-2-01/">[Erai-raws] Isekai Shokudou 2 - 01 [480p][Multiple Subtitle][6D163629].mkv</a> | Subtitles: [us][br][mx][es][sa][fr][de][it][ru]  | Size: 363.84MB | InfoHash: 1715f923f383b0aa8555470818356a71118d98f0 | Categories: [Airing] ]]>
	</description>
</item>
```
But recently some titles return an empty link
for example
```xml
<item>
	<title>[Magnet]Isekai Shokudou 2 - 03 [SD][us][br][mx][es][sa][fr][de][it][ru][Airing]</title>
	<link></link>
	<pubDate>Fri, 29 Oct 2021 09:10:02 +0000</pubDate>
	<erai:resolution>SD</erai:resolution>
	<erai:linktype>Magnet</erai:linktype>
	<erai:size>364.23MB</erai:size>
	<erai:infohash>e9dbc1d4907282e9d7727b8989bd8060f9715280</erai:infohash>
	<erai:subtitles>[us][br][mx][es][sa][fr][de][it][ru]</erai:subtitles><erai:category>[Airing]</erai:category>	<description>
		<![CDATA[<a href="https://beta.erai-raws.info/episodes/isekai-shokudou-2-03/">[Erai-raws] Isekai Shokudou 2 - 03 [480p][Multiple Subtitle][6670348F].mkv</a> | Subtitles: [us][br][mx][es][sa][fr][de][it][ru]  | Size: 364.23MB | InfoHash: e9dbc1d4907282e9d7727b8989bd8060f9715280 | Categories: [Airing] ]]>
	</description>
</item>
```
Fortunately the infohash is provided, so in these cases we need to use the infohash and call the InfoHash routine to auto-build a magnet to replace the Link.

I took a look at the code and could not figure out the best place to do a if-link-is-empty-build-a-magnet-using-infohash procedure.

### Logged Error Messages

```
2021-10-30 17:10:27 | Warn | Could not parse Erai-Raws RSS item '<item><title>[Magnet]Saihate no Paladin - 02 [720p][us][br][mx][es][sa][fr][de][it][ru][Airing]</title><link></link><pubDate>Fri, 29 Oct 2021 10:24:51 +0000</pubDate><erai:resolution xmlns:erai="https://www.erai-raws.info/rss-page/">720p</erai:resolution><erai:linktype xmlns:erai="https://www.erai-raws.info/rss-page/">Magnet</erai:linktype><erai:size xmlns:erai="https://www.erai-raws.info/rss-page/">703.54MB</erai:size><erai:infohash xmlns:erai="https://www.erai-raws.info/rss-page/">a8721110f9d91c1a2c9daaec7b6b812016aebbd8</erai:infohash><erai:subtitles xmlns:erai="https://www.erai-raws.info/rss-page/">[us][br][mx][es][sa][fr][de][it][ru]</erai:subtitles><erai:category xmlns:erai="https://www.erai-raws.info/rss-page/">[Airing]</erai:category><description><![CDATA[<a href="https://beta.erai-raws.info/episodes/saihate-no-paladin-02/">[Erai-raws] Saihate no Paladin - 02 [720p][Multiple Subtitle][5F781E26].mkv</a> \| Subtitles: [us][br][mx][es][sa][fr][de][it][ru]  \| Size: 703.54MB \| InfoHash: a8721110f9d91c1a2c9daaec7b6b812016aebbd8 \| Categories: [Airing] ]]></description></item>'
```

BTW this warning is generated from my recent commit d2afdae which  will be published in the next release in about 30 minutes from this post.
If you are using v0.19.96 you'll see 
```html
2021-10-30 17:31:15 | Warn | Could not parse Erai-Raws RSS item '[Magnet]Isekai Shokudou 2 - 02 [SD][us][br][mx][es][sa][fr][de][it][ru][Airing]Fri, 29 Oct 2021 09:08:52 +0000SDMagnet363.55MB716d7bcd723445c0242ca7de0ce440a89e5718d9[us][br][mx][es][sa][fr][de][it][ru][Airing]<a href="https://beta.erai-raws.info/episodes/isekai-shokudou-2-02/">[Erai-raws] Isekai Shokudou 2 - 02 [480p][Multiple Subtitle][BFDBD619].mkv</a> \| Subtitles: [us][br][mx][es][sa][fr][de][it][ru]  \| Size: 363.55MB \| InfoHash: 716d7bcd723445c0242ca7de0ce440a89e5718d9 \| Categories: [Airing] '
```
which I don't find particularly useful. At least my version has the xml tags which I think is an improvement.

**Comment by garfield69** [comment]
@6cUbi57z Could you take a look at this please?
Thanks.

**Comment by garfield69** [comment]
BTW, to make use of the auto-magnet builder all one has to do is load the releaseInfo with the infohash,
as shown in this example:
https://github.com/Jackett/Jackett/blob/da340ed952b3c60bbf6829c7bfca2fe62a746207/src/Jackett.Common/Indexers/DarmoweTorrenty.cs#L182-L197

And obviously the MagnetUri is not required in this case, and the Guid will need a new unique key, perhaps a concatenation of the Details and the Infohash should be unique enough.
https://github.com/Jackett/Jackett/blob/63024a39db486ccc56ff74598318965408303df3/src/Jackett.Common/Indexers/EraiRaws.cs#L186-L201

**Comment by garfield69** [comment]
In addition, some titles can contain .torrents instead of magnets. For example https://beta.erai-raws.info/episodes/isekai-shokudou-2-02/
We should be able to process these as well.

**Comment by 6cUbi57z** [comment]
PR created for supporting magnets without links via info hash.

> In addition, some titles can contain .torrents instead of magnets. For example https://beta.erai-raws.info/episodes/isekai-shokudou-2-02/ We should be able to process these as well.

The one linked has both magnets and torrents. I'm not sure if there are any releases which are torrent only. Do you have an example?

**Comment by garfield69** [comment]
>The one linked has both magnets and torrents. I'm not sure if there are any releases which are torrent only. Do you have an example?

Hah!
When I looked at this 2 days ago there was only the torrent showing.
A random sampling just now seems to show that all now have both. Perhaps it was an aberration.
If I catch it again I will dump the html so we have something to work with next time.
Thanks.

**Comment by 6cUbi57z** [comment]
I checked both of the feeds and they both list the same publish date but the could easily be incorrect. If it does happen again it's also worth looking at both the RSS feeds. It could just be the HTML which isn't displaying it.

https://www.erai-raws.info/feed/?type=magnet
https://www.erai-raws.info/feed/?type=torrent

**Comment by garfield69** [comment]
v0.19.124
