### ISSUE TITLE
[1337x] Error connecting to FlareSolverr server: ... Cannot assign requested address (localhost:8191)

### ISSUE THREAD

**Issue by sportsziggy** [Jackett/Jackett#12485]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett version v0.19.84
FlareSolverr version v2.0.1
No proxy
Default log location
Docker
```

### Description

1337x fails verification for error logged below.

### Logged Error Messages

Exception (1337x): Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:8191) ---> System.Net.Sockets.SocketException (99): Cannot assign requested address at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken) at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequ

**Comment by garfield69** [comment]
Are you using a Jackett docker image  to connect to a Falresolverr docket image?
If this is so, then you need to use the Flaresolverr docker external ip address in your Jackett docker dashboard.
`localhost` from within a docker image is an internal address and you need to reference an external address.
Find your flaresolverr docker external address by using the docker inspect command, something like
`sudo docker container inspect container_name_or_ID`
@ilike2burnthing  Please correct me if I have this wrong or if there is a better way. Thanks.

**Comment by sportsziggy** [comment]
> 
> 
> Are you using a Jackett docker image to connect to a Falresolverr docker image? If this is so, then you need to use the Flaresolverr docker external ip address in your Jackett docker dashboard. `localhost` from within a docker image is an internal address and you need to reference an external address. Find your flaresolverr docker external address by using the docker inspect command, something like `sudo docker container inspect container_name_or_ID` @ilike2burnthing Please correct me if I have this wrong or if there is a better way. Thanks.

I am, yes.
I am now getting a 
`Exception (1337x): Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Connection refused (172.17.0.2:8191)`
[ip address reference from docker command](https://i.imgur.com/XRI5NCI.png)

**Comment by garfield69** [comment]
can you get a flaresolverr response from your browser using http://172.17.0.2:8191 ?

**Comment by ilike2burnthing** [comment]
You wouldn't be able to access http://172.17.0.2:8191 in browser, you'd have to curl it from within the container. 

You can try the local address of the device it is on, e.g. http://192.168.0.2:8191, in browser.

**Comment by garfield69** [comment]
@ilike2burnthing I think it might be useful if I add an error-connecting-to-docker-flaresolverr to the troubleshooting wiki, if you could provide a basic how-to-connect-docker-jackett-to-docker-flaresolverr breakdown including methods on how to check when there are connections issues?
Because clearly I should not be providing support for docker stuff, I just don't use them.
Thanks.

**Comment by garfield69** [comment]
Oh wait, there is already one at https://github.com/Jackett/Jackett/wiki/Troubleshooting#error-connecting-to-flaresolverr-server
@ilike2burnthing  can you give it a one over and see if it need additional material? Thanks.

**Comment by ilike2burnthing** [comment]
Made some changes - https://github.com/Jackett/Jackett/wiki/Troubleshooting/_compare/9bd24660f86178316a623a26c09f7746f7340e58...2d6c8ed597898c621517433e6c24ca5e0e6db6bb

**Comment by garfield69** [comment]
@sportsziggy  sorry, got side-tracked improving the support wiki.
Have a read of [this wiki](https://github.com/Jackett/Jackett/wiki/Troubleshooting#error-connecting-to-flaresolverr-server) and see if that helps you sort out your problem.

**Comment by sportsziggy** [comment]
Thank you both @ilike2burnthing and @garfield69, it took a bit longer to do test so it seemed like it was getting past where it was failing immediately before.
However still getting a 
`Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Connection refused (192.168.0.2:8191)`

**Comment by sportsziggy** [comment]
I can get a successful connection to flaresolverr on the GET on my htt://local-ip:8191, so I know that it is working at the very least.

**Comment by sportsziggy** [comment]
Ah, just switching to use my http://local-ip:8191 fixed it. Don't know if you let contributors open a PR to the wiki but I can with this info.

**Comment by sportsziggy** [comment]
> 
> 
> Ah, just switching to use my http://local-ip:8191 as the flaresolverr api url in jackett fixed it. Don't know if you let contributors open a PR to the wiki but I can with this info.

[I did it.](https://github.com/Jackett/Jackett/wiki/Troubleshooting/_compare/b6515d29972a02f6b124f588e6a9ce83746ae049...ddf2a0560f3fddbb33dff2f6e169c9a80b27f1ba)

**Comment by garfield69** [comment]
Glad you got it working, and thanks for the wiki update.
