### ISSUE TITLE
[req]: Document settings migration

### ISSUE THREAD

**Issue by ev-dev** [Jackett/Jackett#12491]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I recently did a clean install of Windows 11 on a new drive and when I tried to setup Jackett, I wanted to use all the public/private trackers I had previously setup which I assumed where stored somewhere in my previous installation on my old drive

### Describe the solution you'd like

Quick docs on how to properly use the --MigrateSettings flag to transfer over configured tracker settings to a new install/data path

### Describe alternatives you've considered

I've used the --MigrateSettings command flag with the path to my old configs but it didn't work as expected and only worked when also using the --DataFolder set to my new install's config path

I expected the configs to be actually migrated over to my current drive but it doesn't which means I actually have to stop jackett from running and run the JackettService command with those flags to get my previous setup live. For some reason even adding the addition --Start flag to get it into the background doesn't get the old configs working.

PS much thanks to all the contributors! jackett is def one of the staple tools in the torrenting community

**Comment by garfield69** [comment]
I didn't even know we had a migrate option, I have not idea if it works.

In the past I just copied over the old %programdata%/Jackett/Indexers and the old %programdata%/Jackett/DataProtection folders over to their respective location on the new drive, as well as the %programdata%/Jackett/ServerConfig.json file to carry over the dashboard settings and apikey.

its likely that the saved passwords in your active config may not work and need re-saving, as the encryption is machine/platform/OS specific.

**Comment by ilike2burnthing** [comment]
I'm not sure this actually does anything, it only exists in the readme and console options - https://github.com/Jackett/Jackett/search?q=MigrateSettings&type=code (`IgnoreSslErrors` for comparison - https://github.com/Jackett/Jackett/search?q=IgnoreSslErrors&type=code).

**Comment by garfield69** [comment]
v0.20.36
