### ISSUE TITLE
Error downloading "iptorrents" torrent

### ISSUE THREAD

**Issue by uscgmatthew** [Jackett/Jackett#125]
Hey everyone. Firstly, thank you so much for all the hard work you guys do!! Hopefully i can join the team in the future. 

I have tried multiple releases and i am on Windows 10.

Basically when i try to download any torrent from IPTorrents (manually through jackett or from sonarr) It fails.  I found the issue to be an incorrect url path it's pointing to. there is an extra forward slash. 

Example:        https://iptorrents.com//download.php/634572/The.Big.Bang.Theory.S09E10.INTERNAL.AAC.MP4-Mobile.torrent

In the above example, after iptorrents.com there are two slashes. removing one fixes the issue.

thank you!

**Comment by flightlevel** [comment]
Should be fixed in latest release
