### ISSUE TITLE
[NEWPCT] Domain for this indexer changed

### ISSUE THREAD

**Issue by KaZaCeN** [Jackett/Jackett#12506]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 682 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19043.0 (64bit OS)
Environment version: 5.0.11 (C:\ProgramData\Jackett\)
Starting Jackett v0.19.147
```

### Description

The domain for this indexer have changed, the new one is https://atomixhq.one/

### Logged Error Messages

None

**Comment by garfield69** [comment]
thanks. the new domain will be the default in the next release of jackett.

**Comment by garfield69** [comment]
*.com has not expired yet, I can still use is to search and get details
https://atomixhq.com/ultimas-descargas/pg/1
https://atomixhq.com/descargar/peliculas-castellano/el-buen-patron-2021-/ts-screener/
so I'll just add *.one as an alternate.

**Comment by garfield69** [comment]
v0.19.162

**Comment by KaZaCeN** [comment]
> *.com has not expired yet, I can still use it to search and get details https://atomixhq.com/ultimas-descargas/pg/1 https://atomixhq.com/descargar/peliculas-castellano/el-buen-patron-2021-/ts-screener/ so I'll just add *.one as an alternate.

Sorry about writing in a closed one, but I think .com is maybe ISP capped here in Spain, cause I can't enter trought 2 different ISP.

**Comment by garfield69** [comment]
That is why we have the alternate sitelinks list, so you can try other domains without having to resort to using a VPN/Proxy.
but if all are blocked then VPN/Proxy may be your only option.
v0.19.162 has the *.one you asked for.
Just use your Jackett dashboard to edit the newpct config and click the alternate link to load it into the sitelink box and save.

**Comment by KaZaCeN** [comment]
I know, I've been using the new one before the update, I manually added it. Just saying that maybe the .com domain is actually working, but in Spain at least is blocked.
