### ISSUE TITLE
[req]: Indietorrents

### ISSUE THREAD

**Issue by growwithlogan** [Jackett/Jackett#12502]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Indietorrents
- URL: https://www.indietorrents.com/
- Description: IndieTorrents (IT) is a private Music tracker for independent music only with lots of hard to
 find music stuffs. Only lossy content is allowed, if you want lossless support the artist buying the album.
 Indie Torrents is a great site if you are looking for those hard-to-find releases.
 Indie used to mean the independent rock genre, but they have expanded now, and have opened it to
 really any kinds of independent music. 
They got around 5.6K+ registered members with 11.6K+ uploaded torrents IT community isn’t big but they are
 very active but they got many dead torrents due to lack of leechers/seeders as per their small user-database.
 As for the speeds, they are quite decent but not bad at all.
- Minimum Seeding Time and Minimum Ratio (if Private): Standard
- Additional Comments:
```
engine: Project Gazelle
MR is proportional to what has been downloaded so far. Going to use the max 100+GB = MR 0.60

**Comment by garfield69** [comment]
registration is currently invite only.
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by garfield69** [comment]
I've restricted the search to Audio only. To support Video would required a C# indexer because the results page HTML is different and yaml prefers a single layout.

**Comment by growwithlogan** [comment]
Nice!! Thanks so much, audio is all that is needed for me personally. Cheers

**Comment by garfield69** [comment]
v0.19.147
