### ISSUE TITLE
[p2pbg] Test search in P2PBG => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by firebull81** [Jackett/Jackett#12519]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient/HttpWebClient2
Using FlareSolverr: Disabled or a url
Using proxy: Disabled or HTTP/SOCKS4/SOCKS5
App config/log directory: folder path
Running in Docker: No/Yes
Jackett variant: CoreWindows/FullFrameworkWindows/CoreMacOs/CoreLinuxAmdx64/CoreLinuxArm32/CoreLinuxArm64/Mono
OS version: platform n.nn (32bit/64bit)
Environment version: n.n.nn (folder path)
Starting Jackett vn.nn.nn
```

### Description

The tracker P2PBG was down for a while. But currently is alredy up and runnig. And there is still error about.

### Logged Error Messages

An error occurred while testing this indexer
Test search in P2PBG => Found no results while trying to browse this tracker

**Comment by garfield69** [comment]
The indexer is working for me. Are you using http://p2pbg.com/ as the sitelink?
In any case, if you want to research your issue you are going to need to provide a full enhanved log, perhaps the debug and HTML included will give a clue to your problem.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by firebull81** [comment]
Sure, here is log file
[log.txt](https://github.com/Jackett/Jackett/files/7495551/log.txt)

**Comment by garfield69** [comment]
looks like we are getting quite a few mismatches between date fields and other columns.
I'll see if I can figure out how to cope with your search results and update the indexer.

BTW, what language have you set for the web site, and are you an elevated user (which is to say a user with additional privileges as opposed to a regular user) ?

**Comment by garfield69** [comment]
Oh, and the theme, are you using BASE or another?

**Comment by firebull81** [comment]
Hi, the lang setted is Bulgarian, theme is Frosted, and I'm regular user.

**Comment by garfield69** [comment]
Hmmm. I think the staff are playing around with the layout and JS on the torrents page, because right now, I can only get TVBG results, I cannot find movies or music and anything else using the browser with the site directly.
Is it working for you ATM?

**Comment by garfield69** [comment]
I've changed the way the indexer finds the columns which should cope with the way some rows are missing info based on type.
and the date parsing needed refreshing as they appear to have changed the capitalisation of words for the Bulgarian  today, yesterday and now.
and finally, also corrected the posters which were not working.
Unfortunately I cannot test the changes properly because right now I am only seeing TVBG category %-/
But the updates will be included in the next Jackett release (due out in about 10 hours or so) so you can test and report after that. Thanks.

**Comment by firebull81** [comment]
Sure, tomorrow I'm gonna update it, and after test, I’ll let you know.Thank you. На 8.11.2021 г. 20:52 garfield69 ***@***.***> написа:
I've changed the way the indexer finds the columns which should cope with the way some rows are missing info based on type.
and the date parsing needed refreshing as they appear to have changed the capitalisation of words for the Bulgarian  today, yesterday and now.
and finally, also corrected the posters which were not working.
Unfortunately I cannot test the changes properly because right now I am only seeing TVBG category %-/
But the updates will be included in the next Jackett release (due out in about 10 hours or so) so you can test and report after that. Thanks.

**Comment by garfield69** [comment]
v0.19.215

**Comment by firebull81** [comment]
Yes, everything is fine!Thank you. Best Regards. На 9.11.2021 г. 7:01 garfield69 ***@***.***> написа:
v0.19.215

**Comment by lapd87** [comment]
I have same problem "Found no results while trying to browse this tracker" now.
[Jackett] Version v0.20.1845

**Comment by ilike2burnthing** [comment]
In browser, sign out of the site and back in, then make sure you can access http://p2pbg.com/index.php?page=torrents

Reconfigure the indexer in Jackett to make sure it is able to sign in as well, then perform another test. If it still fails, let me know what language and style (e.g. Base) you are using, and provide an enhanced log of your issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by lapd87** [comment]
theme softdark was the problem. Changed back to base and all is good. Can you verify for all themes?

**Comment by ilike2burnthing** [comment]
Feel free to test the other themes if you like, see which work and which don't. If they all make slight changes beyond colour, then I'm not going to start making tweaks to accommodate 7 different styles.

**Comment by lapd87** [comment]
ok maybe if it fails add a warning message to check under Base theme?

**Comment by lapd87** [comment]
thnx you can close this

**Comment by AARON8888** [comment]
Site on sale? Redirected to this site automatically: https://www.godaddy.com/en-uk/domainsearch/find?checkAvail=1&domainToCheck=p2pbg.com

**Comment by ilike2burnthing** [comment]
Use a proxy or VPN. Please don't comment on unrelated issues which have been closed for a year.

**Comment by AARON8888** [comment]
Sorry, I use proxy and VPN and no possible to connect to tracker site.
By the way, I want to contact to you by DM, but I can´t. How can I do?

**Comment by AARON8888** [comment]
Ohh, you´re right. Site is running in some countries. Thanks for your explanation.

Regarding DM to you, I thought that it was not allowed to ask my question in this closed issue. That´s why I considered to send you DM.
