### ISSUE TITLE
[req]: Reload indexers without restarting Jackett.

### ISSUE THREAD

**Issue by jawlkumuna** [Jackett/Jackett#12510]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Writing indexers is a bit tedious right now. Every time I make changes I have to restart the Jackett process to test them out.

(or am I doing something wrong?)

### Describe the solution you'd like

Put a button on the web interface that makes Jackett reload the indexers in the **Definitions** directory.

Or perhaps have Jackett monitor that directory for changes and automatically reload indexers as necessary.

**Comment by ilike2burnthing** [comment]
I think this req would accomplish the same thing - https://github.com/Jackett/Jackett/issues/7851
