### ISSUE TITLE
[divxtotal] Could not find releases from this URL (Config)

### ISSUE THREAD

**Issue by igomezl** [Jackett/Jackett#12518]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
11-07 10:29:41 Info Environment version: 5.0.11 (/app/Jackett/)
11-07 10:29:41 Info OS version: Unix 5.10.0.0 (64bit OS) (64bit process)
11-07 10:29:41 Info Jackett variant: CoreLinuxAmdx64
11-07 10:29:41 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l
11-07 10:29:41 Info Running in Docker: Yes (image build: v0.19.192-ls50)
11-07 10:29:41 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
11-07 10:29:41 Info App config/log directory: /config/Jackett
11-07 10:29:41 Info Using proxy: Disabled
11-07 10:29:41 Info Using FlareSolverr: http://flaresolverr:8191
11-07 10:29:41 Info Using HTTP Client: HttpWebClient2
```

### Description

Divxtotal indexer is not working. I changed in the configuration the URL from https://www.divxtotal.li/ (which was blocked by my ISP) to https://www.divxtotal.cc/, which is working right now, but the UI still shows the error message "Could not find releases from this URL". Please, find attached the enhanced log file.

Thanks a lot for your work, really appreciated!!!

### Logged Error Messages

[jackett-divxtotal.cc.log](https://github.com/Jackett/Jackett/files/7492015/jackett-divxtotal.cc.log)

**Comment by garfield69** [comment]
While the *.cc domain may share similarities with the *.li, these are not run by the same people.
Under the skin the html is different.
The Jackett indexer is set up to support the *.li site, and cannot be used to access the *.cc site.

**Comment by garfield69** [comment]
follow #12527 for progress on this topic.
