### ISSUE TITLE
[elitetorrent-biz] Exception (elitetorrent-biz): Got redirected to another domain. Try changing the indexer URL to https://elitetorrent.app/.: Parse error (Test)

### ISSUE THREAD

**Issue by JMVS** [Jackett/Jackett#12526]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Starting Jackett v0.19.210 
Environment version: 5.0.11 (/app/Jackett/) 
OS version: Unix 4.15.0.161 (64bit OS) (64bit process) 
Jackett variant: CoreLinuxAmdx64 
File /etc/issue: Ubuntu 18.04.6 LTS \n \l 
Running in Docker: Yes (image build: v0.19.210-ls50) 
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
App config/log directory: /config/Jackett 
Using proxy: Disabled 
Using FlareSolverr: http://localhost:<removed>/
```

### Description

EliteTorrent changed it's URL to: https://elitetorrent.app/
![imagen](https://user-images.githubusercontent.com/7751148/140802306-374a4621-126e-42f9-8977-3388bdeccb8a.png)

Can't update the Site Link manually
![imagen](https://user-images.githubusercontent.com/7751148/140802458-9a1f06a8-1b5f-43a2-8772-b4930cb52a2d.png)

### Logged Error Messages

Error on 20211108160720 for EliteTorrent.biz.txtJackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://elitetorrent.app/.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult Result, IHtmlDocument document) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 847
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1470

<!DOCTYPE html>
<html style="height:100%">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<title> 301 Moved Permanently
</title></head>
<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
<div style="height:auto; min-height:100%; ">     <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
        <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">301</h1>
<h2 style="margin-top:20px;font-size: 30px;">Moved Permanently
</h2>
<p>The document has been permanently moved.</p>
</div></div></body></html>

**Comment by garfield69** [comment]
v0.19.215
