### ISSUE TITLE
[req]: Support channel - Slack, Discord etc..

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#12528]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Is there somewhere to go ask basic questions such as a slack or discord channel.

I have noticed some behaviour such as missing results but i am not sure is this expected behaviour or not. 

for example https://github.com/Jackett/Jackett/issues/12323

I dont want to open up issues for little things like this as i am not sure if they are expected.

### Describe the solution you'd like

A slack or discord channel is created so basic questions can be answered or issue can be confirmed before issues are open in github

**Comment by jawlkumuna** [comment]
There already is a Discord server with a support channel although it doesn't seem to be very active.

**Comment by swannie-eire** [comment]
> There already is a Discord server with a support channel although it doesn't seem to be very active.

thanks for the response.

can you provide the link to it as i dont see it mentioned anywhere.

**Comment by jawlkumuna** [comment]
It's the last badge at the top of the README...

**Comment by swannie-eire** [comment]
> It's the last badge at the top of the README...

thanks no wonder i missed it before when you search for Discord in a browser it doesnt find it. Thanks

**Comment by ilike2burnthing** [comment]
As mentioned, there's a Discord, but it isn't monitored. Same for the [Reddit page](https://www.reddit.com/r/Jackett/). Our human resources are few and far between, so concentrate our attention here.

If you have a problem or question you can post it here as a new issue. We do get questions and will respond - https://github.com/Jackett/Jackett/labels/Question

**Comment by swannie-eire** [comment]
@ilike2burnthing 

fyi there is someone called Qstick telling everyone on the discord channel to use Prowlarr instead.

https://discord.com/channels/346581245821714433/346581434305347584/905618230129864705

**Comment by Qstick** [comment]
> @ilike2burnthing
> 
> fyi there is someone called Qstick telling everyone on the discord channel to use Prowlarr instead.
> 
> https://discord.com/channels/346581245821714433/346581434305347584/905618230129864705

Thanks for the callout. Indeed we recommend Prowlarr to many people whom join looking for help and getting no answers. Most get no response to their questions.

**Comment by ilike2burnthing** [comment]
While it's definitely a little less snappy than 'use Prowlarr', I would suggest pointing them to https://github.com/Jackett/Jackett/issues instead, that way they get their issue handled and you won't come across as proselytising.

If you come across someone who only wants to use software which has an active Discord support channel, then by all means suggest Prowlarr as an alternative.

**Comment by Qstick** [comment]
@ilike2burnthing for sure... Even better let's go at this together. We are going for the same goal here, let's make the best software we can.
