### ISSUE TITLE
90 trackers that don't have an indexer yet

### ISSUE THREAD

**Issue by jawlkumuna** [Jackett/Jackett#12531]
Sorry if an issue is not the proper way to submit this.

I assembled this list by extracting the links from https://torrent-empire.me/tracker_lista2.php, filtering out the ones that are no longer online and subtracting those that already have an indexer.

Some of these trackers might be small and redundant to write indexers for and I could have omitted or unnecessarily included some trackers, but anyways, here is the list:

420project.org
~abn.lol~
alleenretail.org
~amigos-share.club~
~animetorrents.me~
~anthelion.me~
appzuniverse.org
aystorrent.ro
~bB~
~bakabt.me~
bd25.eu
bdixtorrent.com
bigbbs.eu
bitgamer.ch
bitpalace.cc
bitporn.eu
bitsite.us
blues-brothers.biz
broesteam.nl
bt.mdan.org
candy-on.si
central-torrent.eu
cheggit.me
cherrykiss.org
datascene.net
dreamingtree.org
drugari.org
elitetorrent.pl
exigomusic.org
fantasy-tracker.tk
feedurneed.xyz
filmvilag.cf
fluxzone.org
freehardmusic.com
fuzer.me
~Seals~
hdmayi.com
hdmonkey.org
hqmusic.info
huntorrent.eu
icetorrent.org
jamtothis.com
joyhd.net
kraytracker.com
krazyzone.net
kufirc.com
lesbians4u.org
lztr.me
m2g.link
masters-tb.com
megatorrent.pl
metalguru.me
mojblink.si
moviesite.info.hu
musebootlegs.com
music-vid.com
nebulance.io
noviteti.net
nt4h.org
ntelogo.org
oscarworld.xyz
panda.cd
partis.si
party-tracker.info
peeratiko.org
pron4.me
pt.hdpost.top
pt.itzmx.com
releasezone.org
satclubbing.club
scenefz.me
scenetime.com
secret-cinema.pw
seedfile.ro
s-f-p.dyndns.dk
shnflac.net
siamsmile.org
speed.cd
tigers-dl.net
tigris-t.net
tophos.org
torrent.janemusic.org
torrentkings.xyz
tracker.fenyarnyek.com
trackermk.com
tracker.ztuga.com
truegear.net
tv-vault.me
vipers-nest.me
yggtorrent.is
yubraca.net

**Comment by ilike2burnthing** [comment]
Going to save you a lot of hassle here, a lot of these already exist (I got though A and B and then stopped), and we're not going to take on a mass request like this. Certainly if there are individual indexers you want added then request them separately or make a PR for them.
