### ISSUE TITLE
[req]: limetorrentsclone

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#12532]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name:limetorrent
- URL:https://www.limetorrents.to
- Description: Mix content, tv, music, game, movie, adult
- Minimum Seeding Time and Minimum Ratio (if Private):no
- Additional Comments: This indexer different from limetorrents.pro. limetorrent.pro haven't all torrent original site.
```

**Comment by ilike2burnthing** [comment]
As far as I can see *.to is a very similar clone but with some quirks.

Some searches return exactly the same results (e.g. `star wars`), whereas others will be completely different (e.g. `720p`).

The `latest100` page on *.to shows 6hr old torrents (as opposed to a few minutes on *.pro).

Some results on *.to will show different ages depending on your search term (e.g. search `720p` and the result `Trishas Southern Kitchen S17E06 Bowled Over for Pizza 720p WEBRip x264-KOMPOST` is 17mins old, whereas if you search for `kitchen S17E06` the same result is 5 days old).

@garfield69 what do you think? Create a separate but identical indexer for this clone, or just add the URL as a new sitelink, but with a comment beside it?

**Comment by garfield69** [comment]
According to the official LimeTorrents Home Page, the valid alternate domains for *.pro are
```
Official Proxy Domains are : LimeTorrents .asia .co .zone and Limetor.com
NEW Official Proxy Domain Added on site : LimeTor.Pro Please Note it.
```

Anything else is a clone and should not be included in this indexer.

If you feel like adding a clone for limetorrents it should get its own indexer and `clone` should feature in its title

**Comment by garfield69** [comment]
v0.19.225

**Comment by garfield69** [comment]
https://www.limetorrents.to/ returns Error 502 Bad gateway

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.limetorrents.to/ redirects to https://limetorrents.so/
however, limetorrents.so is a shell whose every link points back to www.limetorrents.to so catch22

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
broken again

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.limetorrents.to/ cloudflare A timeout occurred Error code 524

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
search returns empty https://www.limetorrents.to/search/all/reservation-dogs-s03e08/
latest works fine https://www.limetorrents.to/latest100

**Comment by garfield69** [comment]
v0.21.2335
