### ISSUE TITLE
[casatorrent] An error occurred while sending the request: Error: TrustFailure (One or more errors occurred.) (Config)

### ISSUE THREAD

**Issue by gaetan-31** [Jackett/Jackett#12538]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Running on TrueNas 12.2 in JAIL 11.4 Relase p13
```

### Description

After update, indexer not respond.
Remove this and not possible to resave config.

### Logged Error Messages

An error occurred while updating this indexer
An error occurred while sending the request: Error: TrustFailure (One or more errors occurred.)

**Comment by garfield69** [comment]
>After update, indexer not respond.

what did you update?
when did you last successfully use the casatorrent indexer?

**Comment by garfield69** [comment]
It looks like on ‎the 2nd of ‎October ‎2021 casatorrent updated their CA using R3,Let's Encrypt,US

There is a know issue with R3 certificates and certain platforms, such as TrueNAS, something to do with certificate libraries and encryption mismatching/incompatibilities.
Its all linux crap I don't understand, but @ilike2burnthing has been in the thick of it so perhaps he can point you in the right direction if a solve is available.

**Comment by ilike2burnthing** [comment]
Yea, it could be related to https://github.com/Jackett/Jackett/issues/12341, check the last few comments for solutions that worked for others.

**Comment by gaetan-31** [comment]
Thank you.
Let's Encrypt it's a big problem in this moment ^^
