### ISSUE TITLE
[req]: torrentapi.org info add to README

### ISSUE THREAD

**Issue by hl2guide** [Jackett/Jackett#12537]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

app needs a firewall exception.

### Describe the solution you'd like

Add to the readme something like:
"This app uses torrentapi.org for queries and must be allowed in your system firewall software/hardware."

**Comment by garfield69** [comment]
Not practical.
The fact a user may have a firewall active and blocking that domain is not something that is relevant to all users of Jackett on their various different platforms (Windows, linux, MacOSx, docker, etc).
And only users that add the RARBG indexer to Jackett (which is just 1 of over 500 other indexers available) use the torrentapi.org domain, and this is readily visible when users edit the RARBG config with the Jackett dashboard.
