### ISSUE TITLE
BrokenStones no support for 2FA?

### ISSUE THREAD

**Issue by onthecliff** [Jackett/Jackett#12547]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.19.207-ls50)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
Environment version: 5.0.12 (/app/Jackett/)
```

### Description

I have 2FA enabled in BrokenStones. The BrokenStones config in Jackett does not account for 2FA. Is there a way to update it to account for 2FA?

### Logged Error Messages

 An error occurred while updating this indexer

**Comment by ilike2burnthing** [comment]
Download this test version, extract the version you need, and check that 2FA is working for you - https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/4741/artifacts?artifactName=drop&api-version=6.0&%24format=zip

Note that we don't make Docker images, so you'll need to run a local version for this.

**Comment by onthecliff** [comment]
> 
> 
> Download this test version, extract the version you need, and check that 2FA is working for you - https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/4741/artifacts?artifactName=drop&api-version=6.0&%24format=zip
> 
> Note that we don't make Docker images, so you'll need to run a local version for this.

Ok, thanks, it works! Do you know if this will be implemented in future updates?

**Comment by ilike2burnthing** [comment]
Will be included in the next release, out in ~6hrs time

**Comment by garfield69** [comment]
v0.19.260
