### ISSUE TITLE
Jackett notifies update but version stays the same

### ISSUE THREAD

**Issue by RiccardoBarbieri** [Jackett/Jackett#12555]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: no
UsingProxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 682 workerThreads, 1000 completionPortThreads
Running in Docker: No
JackettVariant: CoreWindows
OS Version: Microsoft NT 10.0.19042.0 (64bit OS)
Environment version: 5.0.11 (C:\ProgramData\Jackett
Starting Jackett v0.19.8
```

### Description

Every time a new release is published on this github repo Jackett sends a Windows notification saying that it has updated to x.x.x version.
The problem is that, upon checking the actual version on the dashboard and the logs it is the same as the first time I installed it, it's not actually updating. 

### Logged Error Messages

No relevant error noticed in the logs.

**Comment by garfield69** [comment]
Clearly something is going wrong with the updater.
I run windows10 Jackett as a service and have not had any problems getting daily automated updates.
 
Find the updater.txt log in %ProgramData%\Jackett and see if you can spot signs that the update was interrupted or failed to complete.

Did you install Jackett as a Windows Service? Non-service installation of Jackett can have trouble updating if the user starts Jackett while the update is in progress. The service installation does not suffer from this as the service is shutdown and started up with automation.

Could the system security (anti-malware protection, firewall, whatever) be interfering?
Some security software can silently prevent file updates and the only way you know is to check the security logs for activity or check the virus-chest for Jackett modules having been quarantined. Could this apply to you?

**Comment by adem4ik** [comment]
I have the same problem for a long time https://github.com/Jackett/Jackett/issues/8975 Jacket is installed as non-service
