### ISSUE TITLE
[req]: The Devil's Lounge

### ISSUE THREAD

**Issue by ClandestineClout** [Jackett/Jackett#12552]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: The Devil's Lounge
- URL: https://the-devils-lounge.xyz
- Description: 
- Minimum Seeding Time and Minimum Ratio (if Private):
- Additional Comments: Open reg
```

Engine: FMEDition 3, MR 1.0, MST 24h

**Comment by garfield69** [comment]
v0.19.275

**Comment by ilike2burnthing** [comment]
https://the-devils-lounge.xyz/torrents.php - site is up, but deeming as down because there are zero torrents - has to be a first

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/209f9d511a7d72fa561a5d1c7af47496d8e19089

**Comment by ilike2burnthing** [comment]
[v0.20.105](https://github.com/Jackett/Jackett/releases/tag/v0.20.105)

**Comment by ilike2burnthing** [comment]
https://the-devils-lounge.xyz/ - ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.20.470

**Comment by garfield69** [comment]
Appears to be back online. My old account is good. I will restore the indexer.

**Comment by garfield69** [comment]
v0.20.703

**Comment by garfield69** [comment]
well, that did not last long.
https://the-devils-lounge.xyz/ returns
![image](https://user-images.githubusercontent.com/6933240/158912115-5775ed3c-6cff-44ca-acae-de5a1bcf21c5.png)

**Comment by ilike2burnthing** [comment]
default Plesk webpage

**Comment by garfield69** [comment]
Back online. However the login page did not recognise my username.
I registered afresh using my old creds and was accepted.
Going to need to add a CA ignore as the site is still using the default Plesk self signed CA.

**Comment by garfield69** [comment]
v0.20.740

**Comment by ilike2burnthing** [comment]
https://the-devils-lounge.xyz/torrents.php - zero torrents

**Comment by garfield69** [comment]
Bah. this is a waste of our time to check and maintain. Going to remove it.

**Comment by garfield69** [comment]
v0.20.790
