### ISSUE TITLE
[req]: Alleen Retail

### ISSUE THREAD

**Issue by deku-m** [Jackett/Jackett#12557]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Alleen Retail
- URL: http://www.alleenretail.org/
- Description: A dutch private tracker.
- Minimum Seeding Time and Minimum Ratio (if Private): min. time: Ratio of 1.2
- Additional Comments:
```

**Comment by garfield69** [comment]
http://www.alleenretail.org/ returning ERR_CONNECTION_REFUSED
just me or is the site broken, gone or moved to a new domain?

**Comment by deku-m** [comment]
The site went down last night, they have problems with their server/ISP.

**Comment by garfield69** [comment]
back online. Continuing with indexer build and testing.

**Comment by garfield69** [comment]
v0.20.78

**Comment by garfield69** [comment]
http://www.alleenretail.org/ returning ERR_CONNECTION_REFUSED

**Comment by deku-m** [comment]
You can remove it, site has gone offline. Doesnt look like it will come back either.

**Comment by ilike2burnthing** [comment]
Was there an announcement that they were shutting down the site?

Having a look at a couple of forum posts about the site, there seems to have been some infighting among site admins, and missed payments, but no confirmation that the site is dead:
https://www.duken.nl/forums/topic/38670-alleen-retail-werkt-niet/
https://www.duken.nl/forums/topic/38513-alleenretailorg-weer-offline/#comment-349416

**Comment by deku-m** [comment]
No there wasnt a announcement but the site is offline since beginning of december almost a month.
Yes i have read that, but there is no outcome after a month.

**Comment by ilike2burnthing** [comment]
@garfield69 has it been working for you up until now, or was this the first you've tested it since the start of December? If the latter, just remove it then?

**Comment by garfield69** [comment]
remove it thanks.

**Comment by garfield69** [comment]
v0.20.222

**Comment by deku-m** [comment]
Hi,
Sorry to ask but can you add this again they just got back again.
I didnt expect it :). Not sure if it is too much of work..?

**Comment by garfield69** [comment]
v0.20.285

**Comment by garfield69** [comment]
https://www.alleenretail.org/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.20.1196
