### ISSUE TITLE
Open torrent link in new tab

### ISSUE THREAD

**Issue by Eisa01** [Jackett/Jackett#1255]
Hello,
Currently, after we search for a torrent and we want to visit the torrent link, tapping on the link redirects to the torrent website redirecting our Jackett and we have to search again (unless we open in new tab)

I believe it would be useful if by default tapping on a link opens the site in a new tab.
Thanks (^ ^)

**Comment by flightlevel** [comment]
Good call, will be available in the next release

**Comment by Eisa01** [comment]
@flightlevel 
Amazing!
Can this be applied also to the torrent download? Because if the download fails then Jackett will be directed to an error page and we have to search once again. 
Awaiting your response!
Thanks!

**Comment by flightlevel** [comment]
now in current release
