### ISSUE TITLE
Agent was loaded but is not running. The installation might have failed.

### ISSUE THREAD

**Issue by valdupin** [Jackett/Jackett#12572]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
*Jackett directory*: /Users/valdupin/Jackett
*launchctl info*:
gui/501/org.user.Jackett = {
	active count = 1
	path = /Users/valdupin/Library/LaunchAgents/org.user.Jackett.plist
	state = xpcproxy

	program = /Users/valdupin/Jackett/jackett
	arguments = {
		/Users/valdupin/Jackett/jackett
		--NoRestart
	}

	working directory = /Users/valdupin/Jackett

	inherited environment = {
		SSH_AUTH_SOCK => /private/tmp/com.apple.launchd.StP0E6ng02/Listeners
	}

	default environment = {
		PATH => /usr/bin:/bin:/usr/sbin:/sbin
	}

	environment = {
		PATH => /usr/bin:/bin:/usr/sbin:/sbin
		XPC_SERVICE_NAME => org.user.Jackett
	}

	domain = gui/501 [100877]
	asid = 100877
	minimum runtime = 10
	exit timeout = 5
	runs = 1
	pid = 48462
	immediate reason = speculative
	forks = 0
	execs = 0
	initialized = 1
	trampolined = 0
	started suspended = 0
	proxy started suspended = 0
	last exit code = (never exited)

	spawn type = daemon (3)
	jetsam priority = 4
	jetsam memory limit (active) = (unlimited)
	jetsam memory limit (inactive) = (unlimited)
	jetsamproperties category = daemon
	submitted job. ignore execute allowed
	jetsam thread limit = 32
	cpumon = default

	properties = keepalive | runatload | inferred program
}
*LaunchAgents permissions*:
drwxr-xr-x   9 valdupin  staff   288 16 nov 20:47 .
drwx------@ 97 valdupin  staff  3104 11 nov 16:49 ..
-rw-r--r--@  1 valdupin  staff  6148 16 nov 20:42 .DS_Store
-rw-r--r--   1 valdupin  staff   688 16 nov 20:47 org.user.Jackett.plist
```

### Description

I have installed Jackett on my M1 Mac, first time it works but stop running for unknown reason. I tried to relaunch it but impossible...
So I removed it with the uninstall script and tried to reinstall but this time it doesn't work.

### Logged Error Messages

ERROR: Agent was loaded but is not running. The installation might have failed.

**Comment by valdupin** [comment]
Just tried for the 3rd time and it works... I don't understand ^^

**Comment by ilike2burnthing** [comment]
Is this still working for you if you stop and restart Jackett?

Could you also try the new M1 native test version and report if it works? - https://github.com/Jackett/Jackett/issues/12372#issuecomment-970627966

**Comment by valdupin** [comment]
Yeah it works (stop/restart)

**Comment by janacm** [comment]
I'm getting the same issue, except Jackett is not starting at all:

*Jackett directory*: /Users/janac/Downloads/Jackett
*launchctl info*:
gui/501/org.user.Jackett = {
	active count = 0
	path = /Users/janac/Library/LaunchAgents/org.user.Jackett.plist
	state = spawn scheduled

	program = /Users/janac/Downloads/Jackett/jackett
	arguments = {
		/Users/janac/Downloads/Jackett/jackett
		--NoRestart
	}

	working directory = /Users/janac/Downloads/Jackett

	inherited environment = {
		SSH_AUTH_SOCK => /private/tmp/com.apple.launchd.31bX80BTA5/Listeners
	}

	default environment = {
		PATH => /usr/bin:/bin:/usr/sbin:/sbin
	}

	environment = {
		PATH => /usr/bin:/bin:/usr/sbin:/sbin
		XPC_SERVICE_NAME => org.user.Jackett
	}

	domain = gui/501 [100017]
	asid = 100017
	minimum runtime = 10
	exit timeout = 5
	runs = 1
	successive crashes = 1
	last terminating signal = Trace/BPT trap: 5

	spawn type = daemon (3)
	jetsam priority = 4
	jetsam memory limit (active) = (unlimited)
	jetsam memory limit (inactive) = (unlimited)
	jetsamproperties category = daemon
	jetsam thread limit = 32
	cpumon = default

	properties = keepalive | runatload | inferred program
}
*LaunchAgents permissions*:
drwxrwxrwx@  23 janac  staff   736 27 Feb 13:46 .
drwxrwxrwx@ 106 janac  staff  3392 27 Feb 11:11 ..
-rw-r--r--    1 janac  staff   702 27 Feb 14:48 org.user.Jackett.plist

**Comment by ilike2burnthing** [comment]
Open a new issue, provide the information requested.
