### ISSUE TITLE
[HD4Free] returns empty releases

### ISSUE THREAD

**Issue by Baraddon** [Jackett/Jackett#1257]
The HD4Free tracker returns empty releases. See screenshot:
<img width="1513" alt="unbenannt2" src="https://cloud.githubusercontent.com/assets/25466451/24837415/cd200650-1d33-11e7-83c3-6e82275990d1.PNG">

Other trackers work fine.

[log.txt](https://github.com/Jackett/Jackett/files/908186/log.txt)

Jackett version:  0.7.1272.0 and 0.7.1256
Mono version (if not using Windows):  4.8.0 (Stable 4.8.0.524/9d74414 Wed Apr 5 17:57:04 UTC 2017)

**Comment by Baraddon** [comment]
This is still a problem in 0.7.1422.0. Do you guys need more information to fix this? Can I help somehow?

**Comment by kaso17** [comment]
works for me, please provide an enhancedlog

**Comment by Baraddon** [comment]
Works for me now to with version 0.7.1469.0
