### ISSUE TITLE
[req]: TorrentLatino

### ISSUE THREAD

**Issue by l1ttlegreenman** [Jackett/Jackett#12575]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: TorrentLatino
- URL: https://torrentlatino.cc/
- Description: TorrentLatino is a publick tracker for movies and TV shows in Latin American Spanish
- Minimum Seeding Time and Minimum Ratio (if Private):
- Additional Comments:
```

**Comment by garfield69** [comment]
the site has a one-poster-many-torrents format, which means that the poster details page can have multiple torrents/magnets associated (for example, individual episode torrents for multiple seasons for a single series title).
This means the indexer will need to be written on C# as the yaml cardigann indexers only handle a 1-title-1-torrent format.

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
