### ISSUE TITLE
Notification for download failure

### ISSUE THREAD

**Issue by Eisa01** [Jackett/Jackett#1258]
Hello,
When we download a torrent via Jackett it works smoothly, however if the download fails because the torrent web is down or something then Jackett will redirect our current page to the error page, and we lose our search results and have to search again.

I believe it would be useful if instead of redirecting to the error page we receive a small notification down in Jackett web interface , or a pop-up that displays that the download has failed (personally I prefer notifications since they are less intrusive and doesn't require user interaction).
Thanks (^ ^)

**Comment by kaso17** [comment]
I agree that it's annoying. Unfortunately I'm not aware of any magic flag/status code which tells a link to be a download/avoids the error page.
Adding a target="_blank" to the download links opens them in a new tab. If it's a successful download the tab get's closed immediately. In case of an error the new tab shows the error and the old one is still available. But I'm not a big fan of it as it causes white flashes (new newly opened tab get's the focus).
A solution would be to do the download via javascript. See http://johnculviner.com/jquery-file-download-plugin-for-ajax-like-feature-rich-file-downloads/ for details.
My personal workaround for this is to just use the middle mouse button to open the download links (opens the link in a new background tab).

**Comment by garfield69** [comment]
closing as stale.
