### ISSUE TITLE
Some of the categories provided are unsupported in RARBG

### ISSUE THREAD

**Issue by anonyme123** [Jackett/Jackett#12589]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://185.38.14.185:8192
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.43-ls51)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.19.0.0 (64bit OS) (64bit process)
Environment version: 6.0.0 (/app/Jackett/)
Starting Jackett v0.20.43
```

### Description

Warning in the logs: "Some of the categories provided are unsupported in RARBG:"

### Logged Error Messages

Some of the categories provided are unsupported in RARBG:

### Screenshots

<img width="687" alt="Screen Shot 2021-11-21 at 14 32 37" src="https://user-images.githubusercontent.com/19681420/142763974-2c043af4-a753-4546-bda1-13dd1252267b.png">

**Comment by garfield69** [comment]
Your Sonarr, Radarr, Lidarr, Readarr or other app that you are using, is sending requests to Jackett using category filters that the Jackett RarBG indexer no longer support.
For example, the RarBG web site recently removed the book category from their torrent search page, and the Jackett indexer was update to reflect that change.
So open your torznab apps indexer settings page, edit the torznab indexer for the Jackett RarBG indexer that you have defined there, and refresh the categories you are asking that app to send to Jackett when making searches.
If you need to cross check what categories are currently available in the Jackett RarBG indexer, just use the Jackett dashboard to edit the RarBG config and all the supported categories are listed.

**Comment by anonyme123** [comment]
I'm using Sonarr and Radarr. I followed your instructions and crossed-checked everything:

In Sonarr, RARBG is configured with:
5000         - checked OK (is present in Jackett's listed supported categories)
5030         - checked OK (is present in Jackett's listed supported categories)
5040         - checked OK (is present in Jackett's listed supported categories)
5045         - checked OK (is present in Jackett's listed supported categories)
100018      - checked OK (is present in Jackett's listed supported categories)
100041      - checked OK (is present in Jackett's listed supported categories)
100049     - checked OK (is present in Jackett's listed supported categories)

In Radarr,  RARBG is configured with:
2030         - checked OK (is present in Jackett's listed supported categories)
2040         - checked OK (is present in Jackett's listed supported categories)
2045         - checked OK (is present in Jackett's listed supported categories)
2050         - checked OK (is present in Jackett's listed supported categories)
100017      - checked OK (is present in Jackett's listed supported categories)
100042     - checked OK (is present in Jackett's listed supported categories)
100044     - checked OK (is present in Jackett's listed supported categories)
100045     - checked OK (is present in Jackett's listed supported categories)
100046     - checked OK (is present in Jackett's listed supported categories)
100050     - checked OK (is present in Jackett's listed supported categories)
100051      - checked OK (is present in Jackett's listed supported categories)
100052      - checked OK (is present in Jackett's listed supported categories)
100054      - checked OK (is present in Jackett's listed supported categories)

Jackett page for RARBG says:
Category	Description
1000	Console
1050	Console/XBox 360
1080	Console/PS3
1180	Console/PS4
2000	Movies
2030	Movies/SD
2040	Movies/HD
2045	Movies/UHD
2050	Movies/BluRay
2060	Movies/3D
3000	Audio
3010	Audio/MP3
3040	Audio/Lossless
4000	PC
4020	PC/ISO
4050	PC/Games
5000	TV
5030	TV/SD
5040	TV/HD
5045	TV/UHD
100027	Games/PC ISO
100028	Games/PC RIP
100040	Games/PS3
100053	Games/PS4
100032	Games/XBOX-360
100046	Movies/BD Remux
100042	Movies/Full BD
100049	Movies/TV-UHD-episodes
100017	Movies/x264
100044	Movies/x264/1080
100047	Movies/x264/3D
100050	Movies/x264/4k
100045	Movies/x264/720
100054	Movies/x265/1080
100051	Movies/x265/4k
100014	Movies/XVID
100048	Movies/XVID/720
100052	Movs/x265/4k/HDR
100025	Music/FLAC
100023	Music/MP3
100033	Software/PC ISO
100018	TV Episodes
100041	TV HD Episodes
100049	TV UHD Episodes

**Comment by garfield69** [comment]
Well, if you are still getting the warning, then the next thing to do is to tie it down to the query that is generating it.
Simplest way to do this is to enable the Jackett enhanced logging by using the Jackett dashboard, clicking on **enhanced logging** check box and the **apply server settings** button.
Then access your torznab apps and edit their respective indexers and do a test.
Check the Jackett log to see which is generating the warning.

FYI there is not point in adding both the custom cats and the torznab cats to your indexers, use one set or the other.
In general, you only want to use the custom cats if you want to drill down to filtering specific categories, but if you are just filtering for all movies or all tv then just use the torznab cats.
(In case you are not clear what I'm talking about, the custom cats are the ones in the 100000 range).

**Comment by garfield69** [comment]
OH, just remembered, the torznab apps may need restarting to ensure they flush out old cached command on build fresh queries using their indexer definitions. I've seen this in the past.

**Comment by anonyme123** [comment]
Ok the issue seems to be coming from Radarr:
<img width="688" alt="Screen Shot 2021-11-21 at 19 40 21" src="https://user-images.githubusercontent.com/19681420/142774800-3d312912-e498-4e83-a4d3-69b264db7673.png">

I updated the RARBG indexer settings in Radarr to only have the following categories: 
2030 
2040 
2045 
2050 

I restarted Radarr.
I tested the new indexer settings.

In Jackett's enhanced logs, the query is:
Request finished HTTP/1.1 GET http://127.0.0.1:15629/jackett/api/v2.0/indexers/rarbg/results/torznab/api?t=movie&cat=2030,2040,2045,2050&extended=1&apikey=*************&offset=0&limit=100 - - - 200 500 application/rss+xml;+charset=utf-8 12.5913ms

**Comment by anonyme123** [comment]
Ok so sorry I figured it out, I need to make sure that the parent torznab category is checked
<img width="701" alt="Screen Shot 2021-11-21 at 19 52 42" src="https://user-images.githubusercontent.com/19681420/142775171-ce3e9d7e-ae7a-4dac-87dc-ffcc93ae048d.png">

**Comment by garfield69** [comment]
\o/

**Comment by chenks** [comment]
> \o/

hi, can i just check what you did? 
i have getting the same rarbg warning as you and one for 1337x
`Some of the categories provided are unsupported in 1337x: 2020,2050`]

however, when checking both radarr and sonarr 2020 and 2050 are not listed as categories, and in rarbg my categories look the same as yours.

**Comment by garfield69** [comment]
Sonarr does not refresh its indexer configs once they have been created, it has a cache its keeps referring to.
So try deleting the indexer from Sonarr, and then shut Sonarr down (not just close the web page, but use the systray and right click and select exit.
then start Sonarr afresh and add the indexer, and hopefully it will populate the available cats once you have entered the path and apikey.

**Comment by chenks** [comment]
> Sonarr does not refresh its indexer configs once they have been created, it has a cache its keeps referring to. So try deleting the indexer from Sonarr, and then shut Sonarr down (not just close the web page, but use the systray and right click and select exit. then start Sonarr afresh and add the indexer, and hopefully it will populate the available cats once you have entered the path and apikey.

it's a fresh install or sonarr and radarr, so not sure that will make any different, but will do it anyway.
and both are docker instances so have been completely rebooted only a day or so ago.

**Comment by chenks** [comment]
> Sonarr does not refresh its indexer configs once they have been created, it has a cache its keeps referring to.
> So try deleting the indexer from Sonarr, and then shut Sonarr down (not just close the web page, but use the systray and right click and select exit.
> then start Sonarr afresh and add the indexer, and hopefully it will populate the available cats once you have entered the path and apikey.

ok that made no difference
removed both rarbg and 1337, re-added, restarted both radarr and sonarr.

waited a few minutes, checked the jackett logs

```
Some of the categories provided are unsupported in RARBG: 2010,2020
Some of the categories provided are unsupported in 1337x: 2020,2050
```

**Comment by garfield69** [comment]
The RarBG indexer does not support 2010 and 2020
![image](https://user-images.githubusercontent.com/6933240/186612198-5f72f4dc-7b97-4fd0-8115-15ec27ec31f6.png)
so on your Radarr indexer, if the list includes 2010 and 2020 then untick the movies checkbox, and tick it afresh.
this will leave you with the valid list and the 2010 and 2020 will be gone.
![image](https://user-images.githubusercontent.com/6933240/186612951-6cffe405-4bc1-483d-abcf-5544a125620b.png)

**Comment by chenks** [comment]
> The RarBG indexer does not support 2010 and 2020

this is all i have ticked
![Screenshot 2022-08-25 091810](https://user-images.githubusercontent.com/11945919/186613275-669316ff-6058-46a3-ae41-ca6d35316631.jpg)

**Comment by garfield69** [comment]
yes, untick the movies and then tick it again.

**Comment by chenks** [comment]
> yes, untick the movies and then tick it again.

strange, so even though the list didn't contain 2010 and 2020 it adds them anyway?
and you have to untick and retick for it to not include them?

**Comment by garfield69** [comment]
works for me.

**Comment by 3xploiton3** [comment]
Some of the categories provided are unsupported in 1337x: 2020,2050

**Comment by garfield69** [comment]
>Some of the categories provided are unsupported in 1337x: 2020,2050

@3xploiton3  are you making an observation or asking for help?

**Comment by 3xploiton3** [comment]
> >Some of the categories provided are unsupported in 1337x: 2020,2050
> 
> @3xploiton3  are you making an observation or asking for help?

Ups sorry, problem fixed by uninstalling sonarr & bazarr
