### ISSUE TITLE
[req]: Wiki Updates - Definition format - Better Markdown

### ISSUE THREAD

**Issue by bakerboy448** [Jackett/Jackett#12582]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I didn't want to go ahead and make a major change to the page without your input.

Request is to update the [Definition Format Page](https://github.com/Jackett/Jackett/wiki/Definition-format) to match some markdown best practices.  This includes changing the logs to be proper markdown among various other formatting and cleanup.

Please review the latest revision in this gist for the difference between existing and proposed.  If acceptable, feel free to overwrite the existing page with it.

https://gist.github.com/bakerboy448/76bb78457f13c8fee5d74f8b20427549/revisions?diff=split#diff-bd03d1e6d8716098284940618f372214844e270bc9f012c25de5339d73bfcd29

### Describe the solution you'd like

See above

### Describe alternatives you've considered

n/a

**Comment by ilike2burnthing** [comment]
This looks good to me. The wiki is open to everyone, so feel free to make changes as and when you see the need.

@garfield69 the wiki is largely your baby, any thoughts? It consists of fixes to spacing, trailing spaces (our old friend lol), link formatting, a couple of typos, and using `none` when no markdown syntax highlighting is needed in code blocks.

**Comment by garfield69** [comment]
Go for it. It's only been mine because no one else has bothered contributing. All relevant updates welcome.

**Comment by bakerboy448** [comment]
Cool - Thanks guys!

landed it:
https://github.com/Jackett/Jackett/wiki/Definition-format/251db735954d8ba07f966e5f7f99dc79a67ab2d2

> because no one else has bothered contributing.

Relatable with the servarr wiki man
