### ISSUE TITLE
[req]: Modify the xThor api index

### ISSUE THREAD

**Issue by moussetik** [Jackett/Jackett#12583]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

First of all, sorry for my bad English.
I also specify, that I use Jackett without using Radarr / Sonarr.

Currently, the xThor api index allows you to search with a string or pass an id tmdb. But not both at the same time. Therefore, when we search for a serial id (example 60574), we find the results available on xThor. Since there are many seasons and episodes, the maximum 128 results are reached. However, if we are looking for a particular season, for example season 05, we cannot find the relevant results.

Example request: jackett/api/v2.0/indexers/xthor-api/results/torznab/api?apikey=***&t=search&cat=&tmdbid=60574

### Describe the solution you'd like

Insofar as the API allows it, I suggest adding the possibility of entering an id tmdb AND searching by string. This would make it possible to obtain more relevant results.

Example request: jackett/api/v2.0/indexers/xthor-api/results/torznab/api?apikey=***&t=search&cat=&tmdbid=60574&q=S05

### Describe alternatives you've considered

Here is what I think should be changed in the code:
Jackett/src/Jackett.Common/Indexers/Xthor.cs > BuildQuery()

Currently :
```
if (query.IsTmdbQuery)
{
    logger.Info("\nXthor - Search requested for movie with TMDB ID n°" + query.TmdbID.ToString());
    parameters.Add("tmdbid", query.TmdbID.ToString());
}
else
{
    if (!string.IsNullOrWhiteSpace(term))
    {
        // Add search term
        logger.Info("\nXthor - Search requested for movie with title \"" + term + "\"");
        parameters.Add("search", WebUtility.UrlEncode(term));
    }
}
```

After the changes:
```
if (query.IsTmdbQuery)
{
    logger.Info("\nXthor - Search requested for movie with TMDB ID n°" + query.TmdbID.ToString());
    parameters.Add("tmdbid", query.TmdbID.ToString());
}
if (!string.IsNullOrWhiteSpace(term))
{
    // Add search term
    logger.Info("\nXthor - Search requested for movie with title \"" + term + "\"");
    parameters.Add("search", WebUtility.UrlEncode(term));
}
```

**Comment by ilike2burnthing** [comment]
Similar issue - https://github.com/Jackett/Jackett/issues/8107

**Comment by garfield69** [comment]
the xthor C# indexer was replaced with the xthor-api yaml indexer back in march.
I will amend xthor-api to allow the use of both the tmdb and search keywords together.
Note this only applies to torznab queries, since manual search using the Jackett Dashboard does not support tmdb query.

**Comment by garfield69** [comment]
v0.20.1047
