### ISSUE TITLE
[req]: add huge public torrent tor.lafa.site

### ISSUE THREAD

**Issue by sentryalex** [Jackett/Jackett#12594]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Tor.lafa
- URL: https://tor.lafa.site/
- Description: Giant collection of movies, shows, music, games. constant updates and lots of quality options
- Minimum Seeding Time and Minimum Ratio (if Private):
- Additional Comments:
```

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
