### ISSUE TITLE
[Torrent Network] - Jackett isnt finding the searched Released

### ISSUE THREAD

**Issue by DryTi** [Jackett/Jackett#12590]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Starting Jackett v0.20.44 
Jackett Data will be stored in: /config 
Environment version: 6.0.0 (/app/) 
OS version: Unix 4.15.0.162 (64bit OS) (64bit process) 
Jackett variant: CoreLinuxAmdx64 
File /etc/issue: Ubuntu 20.04.3 LTS \n \l 
Running in Docker: Yes (image build: unknown) 
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
App config/log directory: /config 
Using proxy: Disabled 
Using FlareSolverr: No 
Using HTTP Client: HttpWebClient2
```

### Description

i added the tracker "Torrent Network", add my login credentials and test the connection -> works flawless
but since a few days i cant find any releases that are releated to my search phrases. Jackett shows me only the last cached releases but is not searching for the entered query. 
Also the same issue while looking via Sonarr or Radarr, i attachd some screenshots.  

### Logged Error Messages

no errors in the .log

### Screenshots

![image](https://user-images.githubusercontent.com/70238427/142779105-94453931-1c79-45aa-9a0e-300901db2982.png)
![image](https://user-images.githubusercontent.com/70238427/142779130-0b3c58a3-13bf-4ce3-8d64-6d8063fe7652.png)
![image](https://user-images.githubusercontent.com/70238427/142779138-9a3427ac-b74f-4007-90fd-5f1b37f81cc0.png)

**Comment by garfield69** [comment]
It's a C# indexer that has not been directly updated since Dec 2017. 
Unfortunately none of the team currently have an account on the site, and this will most likely require access to an a/c to debug and fix.
If you have an invite let us know otherwise we wait for a C# dev volunteer to contribute.

**Comment by DryTi** [comment]
i could send you an invite, that should bw that big deal

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine -at- gmail.com I can take a look. Thanks.

**Comment by garfield69** [comment]
Actually, better not use garfieldsixtynine -at- gmail.com, it may still be disabled and blocked.
Please use garfield69 -at- outlook.com instead.

**Comment by DryTi** [comment]
send a invite to garfield69 -at- outlook.com

**Comment by garfield69** [comment]
Registration and login successful. Thank you.

**Comment by garfield69** [comment]
I think the web site has switched from using http.POST to http.GET
the issue I have ATM is that within the last week the team upgraded Jackett to .NET 6.0 and no one warned me that this would make my VisualStudio 2019 incapable of building my test compilations in my sandbox.
I've upgraded to VS 2022 but its not working, so resolving this ticket is going to be delayed. Thanks @ngosang for the head ache ;-b

**Comment by DryTi** [comment]
allright, i hope its no a big struggle, because its my only german Tracker atm :-/ :-D

**Comment by garfield69** [comment]
While my VS2022 is out of action, I've resorted to use an alternate method of updating the code and testing. It's tedious but it gets the job done.
Anyway, the fix should be included in the next Jackett release due out in about 11 hours or so.

**Comment by DryTi** [comment]
Perfect, Thanks!

**Comment by garfield69** [comment]
v0.20.63
