### ISSUE TITLE
[ilcorsaronero] Exception (ilcorsaronero): certificate validation failed: [Subject]  CN=domainwithoutjackett.org[Issuer]  CN=R3, O=Let's Encrypt, C=US[Serial Number]  04ADF9340F558B5C44FCE57589BD312C3C63[Not Before]  11/21/2021 7:22:28 PM[Not After]  2/19/2022 7:22:27 PM[Thumbprint]  B37FB4E413C89C8E3FE835CA162F34738D8FB534: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by bosci9** [Jackett/Jackett#12591]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2

Using FlareSolverr: No

Using proxy: Disabled

App config/log directory: /config/Jackett


ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads


Running in Docker: Yes (image build: v0.20.43-ls50)


File /etc/issue: Ubuntu 18.04.6 LTS \n \l

Jackett variant: CoreLinuxAmdx64

OS version: Unix 5.4.0.90 (64bit OS) (64bit process)

Environment version: 6.0.0 (/app/Jackett/)

Starting Jackett v0.20.44
```

### Description

I have two domains on my home server, one of which redirects to my Jackett instance. Each domain have its separate SSL certificate issued via certbot. 
The problem is that, while I can still access `https://mydomainwithjackett.org` (meaning that the certificate is valid and working), when I try to connect to an indexer i get an error that hints that Jackett is picking the certificate from the other domain.
I tried to check the Nginx configuration, but certbot seems to have done its job correctly.

Is there a config file to edit in order for Jackett to pick the right certificate?

### Logged Error Messages

Exception (ilcorsaronero): certificate validation failed: [Subject] CN=domainwithoutjackett.org [Issuer] CN=R3, O=Let's Encrypt, C=US [Serial Number] 04ADF9340F558B5C44FCE57589BD312C3C63 [Not Before] 11/21/2021 7:22:28 PM [Not After] 2/19/2022 7:22:27 PM [Thumbprint] B37FB4E413C89C8E3FE835CA162F34738D8FB534 : The SSL connection could not be established, see inner exception.

**Comment by ilike2burnthing** [comment]
You could try volume mapping to the right certs, but that has nothing to do with Jackett, it's just Docker configuration, and also shouldn't be necessary (I'm using a reverse proxy and DDNS with my Docker setup, not needed to specify certs).

**Comment by bosci9** [comment]
I'm running Nginx as a reverse proxy and DuckDNS as dynamic DNS.
I noticed that my browser was also picking the wrong certificate somehow, so I deleted and reinstalled both the certificates.
Now the browser shows the right one, but in Jackett the error is still there

**Comment by ilike2burnthing** [comment]
Try restarting the Jackett container now that you've applied that fix. Otherwise see the above suggestion.

**Comment by bosci9** [comment]
Tried restarting, but it still isn't working.
I'm afraid I'm not able to do the volume mapping in the docker-compose file.
Could you please post a template?

**Comment by ilike2burnthing** [comment]
```
    volumes:
      - <path to data>:/config
```
https://github.com/linuxserver/docker-jackett#usage

**Comment by bosci9** [comment]
Ok that didn't work either. 
Now I tried to migrate my Jackett installation on the other domain, and also tried to disable IPv6 using this [link](https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work-the-ssl-connection-could-not-be-established), but it still isn't working

**Comment by ilike2burnthing** [comment]
Do you have Sonarr or Radarr on your system? Try adding their internal RARBG and Nyaa indexers, see if searching with them results in a similar problem.

**Comment by bosci9** [comment]
Yes I have both and their indexers work

**Comment by ilike2burnthing** [comment]
Please provide your full compose file.

**Comment by bosci9** [comment]
version: '3.7'
services:
  deluge:
    image: binhex/arch-delugevpn:latest
    container_name: deluge
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 8112:8112
      - 8118:8118
      - 58846:58846
      - 58946:58946
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VPN_ENABLED=yes
      - VPN_PROV=airvpn
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=${LAN_NETWORK}
      - NAME_SERVERS=209.222.18.222,37.235.1.174,8.8.8.8,209.222.18.218,37.235.1.177,8.8.4.4
      - UMASK=000
      - DEBUG=false
    volumes:
      - /home/user/deluge/config:/config
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_MEDIA}:/data
   jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Rome
      - RUN_OPTS=<net.ipv6.conf.all.disable_ipv6=1>
    volumes:
      - /home/user/jackett/config:/config
      - /etc/localtime:/etc/localtime:ro

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Rome
    volumes:
      - /home/user/sonarr/config:/config
      - ${PATH_MEDIA}:/data

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Rome
    volumes:
      - /home/user/radarr/config:/config
      - ${PATH_MEDIA}:/data

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Rome
    volumes:
      - /home/user/lidarr/config:/config
      - ${PATH_MEDIA}:/data

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 32400:32400
    environment:
      - VERSION=latest
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Rome
    volumes:
      - /home/media/config:/config
      - ${PATH_MEDIA}:/data

**Comment by ilike2burnthing** [comment]
Try deploying Jackett separately, rather than using your current stack/swarm.

**Comment by bosci9** [comment]
Maybe I found what's the problem. I tried deploying it separately, and now I get this error:
`Exception (ilcorsaronero): Connection refused: Connection refused (ilcorsaronero.link:443)`
I searched it and this [post](https://github.com/Jackett/Jackett/issues/5687) said to run  `curl -vvv https://ilcorsaronero.link`.
I did it and this was the output:

> *   Trying 127.0.0.1:443...
> * TCP_NODELAY set
> * Connected to ilcorsaronero.link (127.0.0.1) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /etc/ssl/certs/ca-certificates.crt
>   CApath: /etc/ssl/certs
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
> * TLSv1.3 (IN), TLS handshake, Certificate (11):
> * TLSv1.3 (IN), TLS handshake, CERT verify (15):
> * TLSv1.3 (IN), TLS handshake, Finished (20):
> * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.3 (OUT), TLS handshake, Finished (20):
> * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
> * ALPN, server accepted to use http/1.1
> * Server certificate:
> *  subject: CN=mydomain
> *  start date: XXXXXXX (censored by me)
> *  expire date: XXXXXXXX
> *  subjectAltName does not match ilcorsaronero.link
> * SSL: no alternative certificate subject name matches target host name 'ilcorsaronero.link'
> * Closing connection 0
> * TLSv1.3 (OUT), TLS alert, close notify (256):
> curl: (60) SSL: no alternative certificate subject name matches target host name 'ilcorsaronero.link'
> More details here: https://curl.haxx.se/docs/sslcerts.html
> 
> curl failed to verify the legitimacy of the server and therefore could not
> establish a secure connection to it. To learn more about this situation and
> how to fix it, please visit the web page mentioned above.

I understood that it's trying to connect via localhost, which is obviously not the right way.
But if I try to connect to the same site via another pc connected to the same network it works just fine, and if I try to run (for example) `curl https://github.com` it works.

There seems to be some kind of block on my server for some sites, but I can't understand where, or how it got there

**Comment by ilike2burnthing** [comment]
Ah, that's interesting. Do you have any kind of anti-malware, firewall, ad blocker, pi-hole, or custom DNS set on your device? Is Jackett's traffic passing through an external VPN or proxy (e.g. your Deluge container)?

**Comment by ilike2burnthing** [comment]
Which part were you asking how to check?

You can add DNS servers per container, e.g.:

```yaml
---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    dns:
      - 8.8.8.8
      - 4.4.4.4
    environment:
[...]
```

**Comment by bosci9** [comment]
Great that worked.

Thank you very much for your patience and for wasting your time

**Comment by ilike2burnthing** [comment]
No worries, glad you got it sorted.
