### ISSUE TITLE
[kickasstorrents-to] Exception (kickasstorrents-to): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by Locutus64** [Jackett/Jackett#12607]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-11-26 10:15:56	Info	
Loading Native indexers ...
2021-11-26 10:15:56	Info	
Using HTTP Client: HttpWebClient2
2021-11-26 10:15:56	Info	
Using FlareSolverr: No
2021-11-26 10:15:56	Info	
Using proxy: Disabled
2021-11-26 10:15:56	Info	
App config/log directory: /var/lib/jackett
2021-11-26 10:15:56	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-11-26 10:15:56	Info	
Running in Docker: No
2021-11-26 10:15:56	Info	
File /etc/issue: Manjaro Linux \r  (\n) (\l)
2021-11-26 10:15:56	Info	
Jackett variant: CoreLinuxAmdx64
2021-11-26 10:15:56	Info	
OS version: Unix 5.15.4.1 (64bit OS) (64bit process)
2021-11-26 10:15:56	Info	
Environment version: 6.0.0 (/usr/lib/jackett/)
2021-11-26 10:15:55	Info	
Jackett Data will be stored in: /var/lib/jackett
2021-11-26 10:15:55	Info	
Starting Jackett v0.20.64
```

### Description

I noticed the issue in Radarr that indexers failed because of kickasstorrents.to. I just opened Jackett and tested it and it failes with the below message.

` An error occurred while testing this indexer
Exception (kickasstorrents-to): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured
Click here to open an issue on GitHub for this indexer.`

### Logged Error Messages

`
2021-11-26 10:04:56 
| Error | Jackett.Common.IndexerException: Exception (kickasstorrents-to): Challenge detected but FlareSolverr is not configured  ---> FlareSolverrSharp.Exceptions.FlareSolverrException: Challenge detected but FlareSolverr is not configured    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.<SendAsync>g__Core\|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/main-builder/pkgwork/src/Jackett-0.20.64/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/main-builder/pkgwork/src/Jackett-0.20.64/src/Jackett.Common/Utils/Clients/WebClient.cs:line 185    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/main-builder/pkgwork/src/Jackett-0.20.64/src/Jackett.Common/Indexers/BaseIndexer.cs:line 590    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/main-builder/pkgwork/src/Jackett-0.20.64/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1374    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/main-builder/pkgwork/src/Jackett-0.20.64/src/Jackett.Common/Indexers/BaseIndexer.cs:line 401    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/main-builder/pkgwork/src/Jackett-0.20.64/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/main-builder/pkgwork/src/Jackett-0.20.64/src/Jackett.Common/Indexers/BaseIndexer.cs:line 755    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/main-builder/pkgwork/src/Jackett-0.20.64/src/Jackett.Common/Services/IndexerManagerService.cs:line 306    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/main-builder/pkgwork/src/Jackett-0.20.64/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/main-builder/pkgwork/src/Jackett-0.20.64/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
-- | -- | --

`

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
