### ISSUE TITLE
[ilcorsaroverde] Name or service not known (www.icv-crew.com:443): Name or service not known (Config)

### ISSUE THREAD

**Issue by fulviocapone** [Jackett/Jackett#12608]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
linux docker image of jackett with the same docker-compose 
version: "2"
services:
    jackett:
        image: linuxserver/jackett
        container_name: jackett
        dns:
        - 1.1.1.1
        - 8.8.8.8
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Rome
        volumes:
        - /home/Docker/jackett/config:/config
        - /transmission/downloads/complete:/downloads
        ports:
        - 9117:9117
        restart: unless-stopped
```

### Description

Configuration of the indexer IlCorsaroVerder (icv-crew.com) does'nt work. probably a dns problem.
how can we check it and if it needs a different dns we can change it?
jackett as linuxserver.io docker image

### Logged Error Messages

An error occurred while updating this indexer
Name or service not known (www.icv-crew.com:443): Name or service not known

### Screenshots

![image](https://user-images.githubusercontent.com/10253792/143679208-7feaac33-48ac-400b-a3a2-3c441880784f.png)

**Comment by ilike2burnthing** [comment]
Are you able to access the site in browser from the same device and IP? If not, and changing DNS doesn't resolve your issue, see the other options - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#exception-indexer-no-such-host-is-known
