### ISSUE TITLE
[rutracker] Exception (rutracker):  Received an unexpected EOF or 0 bytes from the transport stream.: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by Ratiboriy** [Jackett/Jackett#12603]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
OS: Windows 10

.Net Runtime: .Net-Framework

.Net Version: 4.5

Jackett Version v0.20.53

Last Working Jackett Version: v0.18.940

Are you using a proxy or VPN? [yes/no] I use 8.8.8.8 DNS Server on my router - this way i get access to Rutracker.org without any VPN or Proxy
```

### Description

Have error while ger rss

### Logged Error Messages

 An error occurred while testing this indexer
Exception (rutracker): Received an unexpected EOF or 0 bytes from the transport stream.: The SSL connection could not be established, see inner exception.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#connection-reset-by-peer-the-ssl-connection-could-not-be-established
OR
https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

If the *.org address is failing, try the *.net instead. Failing that, delete the indexer, restart Jackett, re-add with default settings.

Why is there such a massive gap between the last working version and this one?
