### ISSUE TITLE
[FreshOnTv] Error when adding Indexer

### ISSUE THREAD

**Issue by FusionAge** [Jackett/Jackett#1260]
When adding FreshOnTv as an indexer, I receive the following errors:

Error Message Appears: "Input string was not in a correct format"

From the Logs:
[Debug] IWebClient.GetString(Url:https://freshon.tv/browse.php)
[Debug] IWebClient: Returning OK => 
---------------------------------
[ERROR] Exception in Configure
---------------------------------	
[ERROR] Error on 20170409203938 for FreshOnTV.txtSystem.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Jackett.Utils.ParseUtil.CoerceInt(String str) in C:\projects\jackett\src\Jackett\Utils\ParseUtil.cs:line 50
   at Jackett.Indexers.Freshon.<PerformQuery>d__11.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\Freshon.cs:line 130

[Freshon Website HTML Here -- it appears to be the "Main Page" of the website after login, so I know the credentials are correct]
---------------------------------
Jackett version:  0.7.1272.0
-------------------------------

**Comment by FusionAge** [comment]
Just wanted to add, this is a brand new install, and I was able to add MoreThanTv without a problem. Also seeing this for TehConnection.EU, I'll add a new Issue for that.

**Comment by flightlevel** [comment]
Please try again, working perfectly here. If it fails again, a full enhanced log will be needed

**Comment by FusionAge** [comment]
Just tried -- same issue. Attached the full enhanced log (PII redacted) and screenshot of the UI error.

![image](https://cloud.githubusercontent.com/assets/1923210/24878007/5aa5063a-1dff-11e7-81d4-cef03951893a.png)

[jlog.txt](https://github.com/Jackett/Jackett/files/911166/jlog.txt)

**Comment by flightlevel** [comment]
@FusionAge You must have super powers, no one else has been able to click on the snatched column values by the looks of it, when the next release comes out, see if this fixes the issue

**Comment by FusionAge** [comment]
I'm an admin, that's true. I'll try with a non-admin account and see.

**Comment by kaso17** [comment]
@FusionAge is it working (with your admin account) in the latest release?

**Comment by theCheek** [comment]
I was getting this issue also, even after updating to Version 0.7.1310.0.

However I solved it by deleteting the config file for freshon located in /home/,config/Jackett/Indexers/ 
I removed both files freshon.json and freshon.json.bak then added the indexer to Jackett from scratch and now its all good :) Hope this helps.
