### ISSUE TITLE
[Il Corsaro Verde] tracker problems

### ISSUE THREAD

**Issue by Bazzu85** [Jackett/Jackett#12619]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19043.0 (64bit OS)
Environment version: 6.0.0 (C:\ProgramData\Jackett\)
Starting Jackett v0.20.78
```

### Description

Trying to use the "Il corsaro verde" indexer there are some problems.

1. The search queries.
When searching for example "Star Trek Discovery s01" nothing is returned
On site the release are listed usually with the standard "Show name - Stagione x"
The query need to be translated to "Star Trek Discovery stagione 1" to work

Jackett already translate the release name to the Sxx standard before showing her..
![image](https://user-images.githubusercontent.com/7345587/144013955-b78263fa-e88d-4238-89a6-d6c59b66ede3.png)

Prowlarr guys already made this fix if you check his yml

2. The release size and seed/pees

All release are 512mb and seed/peers fixed to 1

![image](https://user-images.githubusercontent.com/7345587/144118544-bf83849f-f99c-4ff7-8bc3-143ce32acce0.png)

3. Download doesn't work and app like Sonarr/Radarr and from jackett itself

![image](https://user-images.githubusercontent.com/7345587/144118981-ac402657-70ba-451e-a7ae-95104f909a08.png)

in jackett no error showed but none torrent is downloaded..

I think part of the problem is the site structure about tv shows..
- The releases are season release that contain multiple magnets
this is the content of the release 
The Walking Dead - World Beyond - Stagione 2 (2021 ITA/ENG) [08/10][1080p][WEB]
(in jackett The Walking Dead -​ World Beyond -​ S02 (2021 ITA/​ENG) [08/​10][1080p][WEB])
![image](https://user-images.githubusercontent.com/7345587/144119992-dc80ba39-ee80-4289-b86c-fad43296a957.png)

- In every release the first post need to be thanked to show the season magnet
![image](https://user-images.githubusercontent.com/7345587/144119745-428e9def-f637-4d1f-927b-bac4958bb0eb.png)

if you need additional infos or test feel free to ask

### Logged Error Messages

Nothing works exept for some searches

### Screenshots

Check description

**Comment by bakerboy448** [comment]
PR for the season search fix is up https://github.com/Jackett/Jackett/pull/12613

for the other stuff - they'll probably want the enhanced logs from one of the searches

**Comment by ilike2burnthing** [comment]
1) see above
2) files, size, seeds, peers, and completed are all hidden behind the `say thanks` button on the details page, so we have to use stand in values instead
3) downloads are working ok here, including the film in your example, however multiple magnets for a single result is definitely a problem

If no downloads are working for you at all then as mentioned above, please provide enhanced logs of a failed download - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Bazzu85** [comment]
here's a test downloading the movie from radarr
[log.github 20211201 1644.txt](https://github.com/Jackett/Jackett/files/7635281/log.github.20211201.1644.txt)

**Comment by Bazzu85** [comment]
here' a test of a movie from jackett interface
[log.github 20211201 1647.txt](https://github.com/Jackett/Jackett/files/7635291/log.github.20211201.1647.txt)

**Comment by Bazzu85** [comment]
about the multiple magnets any simple solutions?

**Comment by ilike2burnthing** [comment]
The Jackett log for the Radarr download attempt is actually a search using girotorrent, and the Jackett download attempt shows a magnet link being found and used. Is there any visible error when you attempt to download through Jackett? It's not shown in the log.

No simple solution I'm afraid, the indexer will have to be rewritten in C# - https://github.com/Jackett/Jackett/issues/3189

**Comment by Bazzu85** [comment]
So for the radarr log..

I didn't find the log from new tests and found I was using prowlarr.

Using the jackett indexer for movies worked. Using prowlarr not so I'm posting today on his discord.. so for the moment sorry!

I'm now occurring on a different problem with a movie..
using the jackett search:
![image](https://user-images.githubusercontent.com/7345587/144384233-359e2769-954f-43db-bdb0-1771720f12b4.png)
![image](https://user-images.githubusercontent.com/7345587/144384335-a65c0b8e-b874-4110-b765-2fe317839977.png)

using the radarr search:
![image](https://user-images.githubusercontent.com/7345587/144384376-4165080f-fabf-48c8-9f78-dcbfa46a7ade.png)

I think this is because there's the 30 seconds problem and the second search return always zero results... @bakerboy448 what do you think?

**Comment by ilike2burnthing** [comment]
Yea, the only way to solve that would be to enforce 30s delays for every interaction with the tracker (we can't limit delays to just searches without rewriting in C#), but that results in massive delays when adding or reconfiguring the indexer, and when trying to download.

**Comment by shiner66** [comment]
> Yea, the only way to solve that would be to enforce 30s delays for every interaction with the tracker (we can't limit delays to just searches without rewriting in C#), but that results in massive delays when adding or reconfiguring the indexer, and when trying to download.

So, if someone wants to accept such delays, how would I go about implementing them? (Using docker atm)

**Comment by ilike2burnthing** [comment]
If you haven't already, volume map the container folder `/config` to somewhere accessible on your host, e.g. `/volume1/Docker/Jackett/config`.

Access `/volume1/Docker/Jackett/config` (or wherever you've set) and create a new folder in it called `cardigann` then a new folder within that one called `definitions` (so you end up with `/volume1/Docker/Jackett/config/cardigann/definitions`).

Download https://github.com/Jackett/Jackett/raw/master/src/Jackett.Common/Definitions/ilcorsaroverde.yml (you can right-click and 'save link as') and rename it to `ilcorsaroverde-custom.yml`. Open it in a text editor and change the name and id to `ilcorsaroverde-custom` (or anything different than just `ilcorsaroverde`). Then create a new line below `encoding: UTF-8` and above `links:` with the text `requestDelay: 30.`

Save and copy that file to your newly created `/volume1/Docker/Jackett/config/cardigann/definitions` and restart the Jackett container.

You can then add `ilcorsaroverde-custom` in Jackett. Any future changes made to https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/ilcorsaroverde.yml you will have to manually make to your version.
