### ISSUE TITLE
Can't install jackett on Ubuntu 20.04

### ISSUE THREAD

**Issue by victoroos** [Jackett/Jackett#12618]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Ubuntu 20.04
```

### Description

Hi all,

I'm trying ot install Jackett via the SH script.
I do it like this, which pops out this in the terminal:

```
root@vicsserver:~# bash /home/victoroos/Jackett/install_service_systemd.sh
Checking if the service 'jackett.service' is running ...
Service 'jackett.service' is not running
Jackett will be installed in '/home/victoroos/Jackett'
Jackett will be executed with the user 'victoroos'
Creating Jackett unit file in '/etc/systemd/system/jackett.service' ...
Installing Jackett service ...
Service successfully installed and launched!
```

But, it isn't reachable via ip + :9117

When I rerun the script, it says teh same as above (including that the service isn't running, which explains why it isn't accessible.
I did open the port

When I try to run the launcher.sh, it says:
`
root@vicsserver:~# /home/victoroos/Jackett/jackett_launcher.sh
bash: /home/victoroos/Jackett/jackett_launcher.sh: Permission denied
`
Even though it is in the normal user place.. I guess I know what is/clould be wrong but not how to fix it. 

Any tips?
Cheers
Vic

### Logged Error Messages

non unfortunately

**Comment by ilike2burnthing** [comment]
Is https://github.com/Jackett/Jackett#install-on-linux-amdx64 of any help? Also try running it without installing as a service.

**Comment by garfield69** [comment]
You need root permissions to install the service. prefix your script exec with sudo as per https://github.com/Jackett/Jackett#install-as-service
