### ISSUE TITLE
"Copy Torznab/Potato/RSS Feed" button not working on Chrome/Firefox/Safari

### ISSUE THREAD

**Issue by DeadParadise** [Jackett/Jackett#12614]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
Running in Docker: Yes (image build: v0.20.74-ls51)
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.4.59.0 (64bit OS) (64bit process)
Environment version: 6.0.0 (/app/Jackett/)
Starting Jackett v0.20.74
```

### Description

When following the guides on Jackett's dashboard, clicking any of the "Copy" buttons do nothing. Right clicking on the bottom does NOT provide me with a "Copy Link Address" option.  I've disabled all extensions and tried a new private window in Chrome (Version 96.0.4664.55 (Official Build) (x86_64)), as well as the latest versions of Firefox and Safari without any luck. I've also tried a mobile device on the same network without any luck. 

As possible feature request, I would recommend moving away from a button to copy the address and instead display the full address in a code block with the option to copy it. As is, I am not able copy the feed needed for Sonarr/Radarr.

 

### Logged Error Messages

Checking the logs, no errors are reported as this appears to be an issue with the element.

**Comment by garfield69** [comment]
When users set up one or more indexers on the Jackett dashboard, they are presented with rows of activbe indexers.
Use the copy button on the row that corresponds to your indexer, not the example provided at the bottom of the dashboard page ;-)
