### ISSUE TITLE
[rarbg] Parse error: Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by drippyer** [Jackett/Jackett#12612]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19042.0 (64bit OS)
Environment version: 6.0.0 (C:\ProgramData\Jackett\)
Starting Jackett v0.20.74
```

### Description

Confirmed several times over that Jackett was up to date.

RARBG tracker no longer produced results upon a search.
Attempting to add RARBG or search for a query produces the above error.
The recommendation was to provide advanced logs as well as the html to a search on the site directly.

HTML source: [rarbg.txt](https://github.com/Jackett/Jackett/files/7621331/rarbg.txt)

As the Jackett error lists, the issue is a token expiration, however I can't seem to find a way to manually refresh the token.

### Logged Error Messages

2021-11-29 15:44:01
Error
Jackett.Common.IndexerException: Exception (rarbg): Object reference not set to an instance of an object.  ---> System.Exception: Parse error  ---> System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Indexers.RarBG.PerformQueryWithRetry(TorznabQuery query, Boolean retry) in D:\a\1\s\src\Jackett.Common\Indexers\RarBG.cs:line 168    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 781    at Jackett.Common.Indexers.RarBG.PerformQueryWithRetry(TorznabQuery query, Boolean retry) in D:\a\1\s\src\Jackett.Common\Indexers\RarBG.cs:line 221    at Jackett.Common.Indexers.RarBG.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\RarBG.cs:line 134    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 401    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 413    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 755    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 306    at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26

2021-11-29 15:44:01
Error
Error on 20211129154401 for RARBG.txtSystem.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Indexers.RarBG.PerformQueryWithRetry(TorznabQuery query, Boolean retry) in D:\a\1\s\src\Jackett.Common\Indexers\RarBG.cs:line 168
{"error":"Invalid token. Use get_token for a new one!","error_code":4}

### Screenshots

![jackett_error](https://user-images.githubusercontent.com/6970779/143948095-3bc5f573-500b-477c-8c11-86ff9ee89888.png)

**Comment by drippyer** [comment]
I do see that there are other similar issues that have been dealt with and are therefore closed, but I figured a new one for RARBG might be useful

**Comment by garfield69** [comment]
yes, the RarBG API server appears to be broken.
Direct testing of the API with first fetching a new token and then using it in a general query returns
`{"error":"Invalid token. Use get_token for a new one!","error_code":4}`
We just have to wait to see if the owner fixes the issue.

**Comment by VitruxPT** [comment]
Experiencing the same thing, I guess we can only wait at this point since it's a problem on the api side

**Comment by jackharvest** [comment]
Thanks for being so quick on this. Here I am, about to report it and its been talked about for an hour already. 😎

**Comment by garfield69** [comment]
sent a message to support@rarbg.to

**Comment by garfield69** [comment]
RarBG api server is now down.
Owner responded to my email with
```Multiple cluster failure.
Everything fucked up. Trying to fix.
```

**Comment by garfield69** [comment]
RarBG API online.

**Comment by foremtehan** [comment]
@garfield69 are you sure? i still see :  "Invalid token. Use get_token for a new one!"

How to use `get_token` in uri to get new token ?
