### ISSUE TITLE
[req]: movie-torrentz

### ISSUE THREAD

**Issue by AlanKellyEire** [Jackett/Jackett#12628]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name:movie-torrentz
- URL:m2g.link
- Description: private tracker for tv and movies
- Minimum Seeding Time and Minimum Ratio (if Private): 1:1
- Additional Comments: Invite is required and unfortunely i dont have one if i get one ill let ye know.
```
Movie-Torrentz is a Private Torrent Tracker for MOVIES / TV
engine TorrentTrader
MR 0.5

**Comment by garfield69** [comment]
v0.20.159

**Comment by garfield69** [comment]
https://m2g.link/ DNS_PROBE_FINISHED_NXDOMAIN (domain not found)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://m2g.link/ ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
v0.22.119
