### ISSUE TITLE
Check box instead of ddl for selecting/filtering tracker, and category

### ISSUE THREAD

**Issue by Eisa01** [Jackett/Jackett#1262]
Hello,
Currently when we select/filter trackers and categories we have to either select all or select one because of drop-down-list limitation (ddl).

I believe it would be useful if tracker/category selection was via check boxes, then we could select for example 3 sources to search from without having to search all then filter one by one which causes search to be slower.
And the same could be applied for filtering, we could search for all then easily filter to for example 3 sources we desire with the use of check boxes.

(Same concept exactly for category as well)

**I thought of different aspects on how this can be implemented:**

First: Integrating it with the current ddl
Same ddl but has check boxes:
................
[x] Select All > choosing it will tick all the sources including select all, and de-ticking select all will clear all tick from all sources (so we can easily pick what we want simply by clearing the tick from select all)
[x] Source 1 
[x] Source 2 
[x] Source 3

................
[ ] Select All
[x] Source 1
[ ] Source 2
[ ] Source 3

---------------------------------------------
Second: A popup appears to select sources with check box on each source, and a select all, deselect all radio buttons on the top
|............................................................................|
|. ( ) Select All, (x) Deselect All..................|
|. [ ] Source 1 ..................................................|
|. [ ] Source 2 ..................................................|
|. [ ] Source 3 ..................................................|
|....................................................[btnClose]....|
|.............................................................................|

---------------------------------------------
Edited: added category to the suggestion.

**Comment by rene453** [comment]
this is a must needed feature for Jackett I believe. My idea is the same with checkbox and Tracker groups.

I want to label the trackers in the main index and also search just within the labels. Like labeling ipt td ar ncore bB as "General Trackers" and just search within them. Also checkbox system will let me to do more customized search. Hope the devs will look into this features soon :)

**Comment by kaso17** [comment]
multiselect support for the manual search has been added via 00027a41c1471a9c6a8ecd004b51a8869610c962

**Comment by mueslo** [comment]
Was this removed again at some point? I don't see it currently

**Comment by garfield69** [comment]
>Was this removed again at some point? I don't see it currently

Nope, check-boxing categories or trackers using the jackett dashboard manual search is available.
If your browser is not showing this then perhaps you have an active  browser extension that is interfering?
Or perhaps you are using a browser that is in dire need or an update or a full restart.
What platform are your running Jackett and browser and version are on?

**Comment by mueslo** [comment]
Ah, I just misunderstood, i.e. I was tunnel-visioning for what I was looking for: a way to modify/deselect category capabilities from trackers on a global level.
