### ISSUE TITLE
Request indexer for vacatorrent.com

### ISSUE THREAD

**Issue by umoraes** [Jackett/Jackett#12635]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Vacatorrent
- URL:www.vacatorrent.com
- Description:torrent site for Movies and TV Shows with Dual Audio in English and Brazilian Portuguese
- Minimum Seeding Time and Minimum Ratio (if Private):
- Additional Comments:
```

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing

**Comment by ilike2burnthing** [comment]
^ likely scam

**Comment by umoraes** [comment]
Thanks ..... But I'm not using jackett anymore...

**Comment by ilike2burnthing** [comment]
Definitely a scam then.
