### ISSUE TITLE
[req]: I would like to have an invite for the site  https://u2.dmhy.org/portal.php

### ISSUE THREAD

**Issue by raphcool12** [Jackett/Jackett#12636]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Raphael
- URL: https://u2.dmhy.org/portal.php
- Description:
- Minimum Seeding Time and Minimum Ratio (if Private):
- Additional Comments: 
```

**Comment by raphcool12** [comment]
you can sent me the invite code at my e-mail  adress raphcool12@gmail.com as I mention above thanks in advance ;)

**Comment by ilike2burnthing** [comment]
This is not an invite forum, do not use it as one.
