### ISSUE TITLE
[T411] Error config account in jackett

### ISSUE THREAD

**Issue by hiro45** [Jackett/Jackett#1264]
Jackett Version: 0.7.1272.0

Error in jackett, can not add T411:
Configuration failed: Unexpected character encountered while parsing value: o. Path '', line 0, position 0.

Not Error in log

**Comment by raspdealer** [comment]
Same for me.

**Comment by flightlevel** [comment]
Are they still having server issues ?
https://github.com/Jackett/Jackett/issues/1237

**Comment by XavierTolza** [comment]
Same problem here :)

**Comment by JigSawFr** [comment]
T411 API is currently offline, we have no ETA.
https://forum.t411.ai/discussion/45826/bugs-informations-demandes#Item_55
