### ISSUE TITLE
Cannot add newpct-me indexer to Sonarr

### ISSUE THREAD

**Issue by pkreuzt** [Jackett/Jackett#12649]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-12-06 22:45:31	Info	
Using HTTP Client: HttpWebClient2
2021-12-06 22:45:31	Info	
Using FlareSolverr: http://127.0.0.1:8191
2021-12-06 22:45:31	Info	
Using proxy: Disabled
2021-12-06 22:45:31	Info	
App config/log directory: /var/lib/jackett/.config/Jackett
2021-12-06 22:45:31	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-12-06 22:45:31	Info	
Running in Docker: No
2021-12-06 22:45:31	Info	
File /etc/issue: Debian GNU/Linux 11 \n \l
2021-12-06 22:45:31	Info	
Jackett variant: CoreLinuxArm64
2021-12-06 22:45:31	Info	
OS version: Unix 5.10.0.9 (64bit OS) (64bit process)
2021-12-06 22:45:31	Info	
Environment version: 6.0.0 (/opt/jackett/)
2021-12-06 22:45:26	Info	
Starting Jackett v0.20.95
```

### Description

When trying to add this indexer to Sonarr, it throws an error on "Test" step:

`
No rss feed query available. This may be an issue with the indexer or your indexer category settings.`

Same indexer works in Radarr without issues. I believe this is related to the categories on Jackett indexer' config, since it has only "Movies" available. This website provides series too.

### Logged Error Messages

No errors logged.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/12284#issuecomment-917217052
