### ISSUE TITLE
IPTorrents, AlphaRatio and TorrentLeech all return extraneous single episodes when a season pack is searched

### ISSUE THREAD

**Issue by newadventure079** [Jackett/Jackett#12642]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-12-05 00:24:27	Info	Using HTTP Client: HttpWebClient2
2021-12-05 00:24:27	Info	Using FlareSolverr: No
2021-12-05 00:24:27	Info	Using proxy: Disabled
2021-12-05 00:24:27	Info	App config/log directory: /config/Jackett
2021-12-05 00:24:27	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-12-05 00:24:27	Info	Running in Docker: Yes (image build: v0.20.83-ls51)
2021-12-05 00:24:27	Info	File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2021-12-05 00:24:27	Info	Jackett variant: CoreLinuxAmdx64
2021-12-05 00:24:27	Info	OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
2021-12-05 00:24:27	Info	Environment version: 6.0.0 (/app/Jackett/)
2021-12-05 00:24:26	Info	Starting Jackett v0.20.93
```

### Description

When I search for "Orange Is The New Black S07" on IPT, AR and TL, I get numerous single episode results returned.

Some examples are in the screenshot and the details should be in the debug log attached too.  The AR results didn't fit in my screenshot but it also returns single episodes

### Logged Error Messages

Debug logs
[log.txt](https://github.com/Jackett/Jackett/files/7655415/log.txt)

### Screenshots

![Screen Shot 2021-12-05 at 12 27 13 AM](https://user-images.githubusercontent.com/84156407/144737844-7e8ea8f0-98e9-454a-aeff-53b1ff8a3221.jpg)

**Comment by ilike2burnthing** [comment]
I can only confirm IPT and TL, I don't have an account for AR, but this is exactly the same as the tracker returns, and is to be expected given that `S07E01` contains `S07`.

Unless I'm missing something, this isn't an issue.

**Comment by newadventure079** [comment]
I thought that Jackett knew that I searched for a full season since I didn't include any `EXX` and therefore would only return full season results.  I thought I remembered seeing that in the code or reading about it here in the past.  I could be wrong tho.

**Comment by ilike2burnthing** [comment]
If available you can search in season pack categories:
https://github.com/Jackett/Jackett/blob/605967d2127478d021c46f2c3ef8fc1afb48cfc3/src/Jackett.Common/Indexers/AlphaRatio.cs#L46-L49
https://github.com/Jackett/Jackett/blob/605967d2127478d021c46f2c3ef8fc1afb48cfc3/src/Jackett.Common/Indexers/IPTorrents.cs#L113-L115
https://github.com/Jackett/Jackett/blob/605967d2127478d021c46f2c3ef8fc1afb48cfc3/src/Jackett.Common/Indexers/IPTorrents.cs#L118-L119
https://github.com/Jackett/Jackett/blob/605967d2127478d021c46f2c3ef8fc1afb48cfc3/src/Jackett.Common/Definitions/torrentleech.yml#L31

After a search is complete you can filter the results by entering something like
`-e0 -e1 -e2` into the secondary search box just above the results, which would remove any results which contain `e0`, `e1`, or `e2` (in other words, episodes between `00` and `29`.

Generally speaking, this would not be desirable default behaviour, as if a user just wants all single episode results for a season, or a tracker doesn't have season packs, they would get no appropriate results.

Any way of doing this would just be filtering results after they're returned, so we may as well return all results and let users decide whether they want to filter them or not.
