### ISSUE TITLE
[morethantv] Test search in MoreThanTV => Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by newadventure079** [Jackett/Jackett#12644]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-12-05 00:24:27	Info	Using HTTP Client: HttpWebClient2
2021-12-05 00:24:27	Info	Using FlareSolverr: No
2021-12-05 00:24:27	Info	Using proxy: Disabled
2021-12-05 00:24:27	Info	App config/log directory: /config/Jackett
2021-12-05 00:24:27	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-12-05 00:24:27	Info	Running in Docker: Yes (image build: v0.20.83-ls51)
2021-12-05 00:24:27	Info	File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2021-12-05 00:24:27	Info	Jackett variant: CoreLinuxAmdx64
2021-12-05 00:24:27	Info	OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
2021-12-05 00:24:27	Info	Environment version: 6.0.0 (/app/Jackett/)
2021-12-05 00:24:26	Info	Starting Jackett v0.20.93
```

### Description

I cant add MoreThanTV to Jackett because of an error

### Logged Error Messages

[log.txt](https://github.com/Jackett/Jackett/files/7656775/log.txt)

**Comment by ilike2burnthing** [comment]
Have you customised anything for your account which would change how the site or results are displayed (e.g. themes, layout settings, enabled/disabled features)?

@ryanm352 / @dwp4ge / @Xalaxis can any of you confirm this issue? Has something with the site changed recently?

**Comment by ryanm352** [comment]
I can look into this. I'm not sure the status of their site upgrade. I'm sure the results display has changed.

**Comment by newadventure079** [comment]
@ilike2burnthing  I hadn't added MTV in some years due to it being down and all the other changes.  I had 2FA enabled and it didn't work so I turned off 2FA and it still didn't work.  Other than 2FA (which is now off for my account), I haven't done any customization

**Comment by ta391993** [comment]
There were a number of changes made to torrents.php according to the latest announcement on 23/12/21, and currently MTV isn't working correctly via Jackett, search terms aren't actually returning search results, rather just the unfiltered first page of torrents.

**Comment by ilike2burnthing** [comment]
@ryanm352 ping

**Comment by LennyPenny** [comment]
would be cool if 2FA was supported

**Comment by garfield69** [comment]
@newadventure079 
This indexer is working for me.
I can add it as a new indexer with my credentials, do a TEST, a free form search and get results, and start a download.
I've tested all the stylesheets and the all work with this indexer, but I use the `Genaviv` stylesheet.
I can get the indexer to cause errors if I turn on the profile setting for `time style` to `display times as date and time`, so only the `display times as time since` is supported by the indexer.

Also, I can get no results if the profile setting for `hover info window` is enabled.
This causes 0 results. So make sure you do NOT have this option ticked.
Please check your profile and see if this makes a difference for you.

**Comment by newadventure079** [comment]
Thanks @garfield69!  I had all of those same settings already except my `Hover info window` was checked. I unchecked it and now it works

**Comment by garfield69** [comment]
\o/
