### ISSUE TITLE
Hd-torrents not replacing "Full Stops" with white spaces so not returning all results

### ISSUE THREAD

**Issue by AlanKellyEire** [Jackett/Jackett#12654]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
os version: freebsd jail 12.2 release
Jackett version: v0.20.105
```

### Description

Im not sure if this would be considered a feature request or defect as it works the same on the site but means that you have to do multiple searches to find the torrent on multiple sites. e.g one with full stops for Alpharatio and another with fullstops replaced for HD-torrents.

If you do a search for a torrent to cross seeed it in many cases you are going to copy the name from the torrent client so it will more than likely have full stops instead of spaces like this "That.Vitamin.Movie.2016"

If you do a search on Hd-torrents with fullstops as delimiters you will get not results back but if you use white spaces instead of full stops you will get results.

It looks like we just need to replace full stops with white spaces on HD-torrents to get it working correctly if you use a string that contains full stops. The behaviour is the same on the HD-torrent site as they do not allow full stops in torrent names unless its for audio. e.g DD+ 5.1. Most sites dont have audio info in the torrent name and i dont search for torrents with the audio info so i think its best to by default replace any full stop with a white space when using the HD torrents indexer.

### Logged Error Messages

```
2021-12-07 14:25:54.0960 Info Manual search in hdtorrents for That.Vitamin.Movie.2016 => Found 0 releases

2021-12-07 14:26:05.9084 Info Manual search in hdtorrents for That Vitamin Movie 2016 => Found 1 releases
```

### Screenshots

torrent site
https://imgur.com/DH4vYdA

search results
https://imgur.com/JIOiS3E
https://imgur.com/y10JUh1

**Comment by ilike2burnthing** [comment]
If you search on the site for a torrent which has `DD+ 5.1` in the title by instead using `DD+ 5 1` in the search term, does HD-Torrents return that result?

**Comment by AlanKellyEire** [comment]
> If you search on the site for a torrent which has `DD+ 5.1` in the title by instead using `DD+ 5 1` in the search term, does HD-Torrents return that result?

Yes it does and as this site can be it inconsistent when it comes to names you will also find that many of the torrent name contain `DD+5 1` instead of `DD+5.1` so searching for DD+5.1 means you will miss results.

here is a video of the results and the querys in the URL - 

for "dd+5 1"
search=dd%2B5+1&active=1&options=0
for "dd+5.1"
search=dd%2B5.1&active=1&options=0

https://imgur.com/z4Pgey0

**Comment by ilike2burnthing** [comment]
Please download this test build, extract the version you need (doesn't have to be on your freebsd machine), and confirm that searching with and without full stops between words return the same results (you can also enable enhanced logs and confirm that the search paths are exactly the same) - https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/4904/artifacts?artifactName=drop&api-version=6.0&%24format=zip

**Comment by AlanKellyEire** [comment]
Yes it works as expected now. Thank you

![Screenshot 2021-12-08 at 16 31 43](https://user-images.githubusercontent.com/22172144/145246681-7b6a654c-fc57-4bff-acc9-9c8d960ec2ab.png)
![Screenshot 2021-12-08 at 16 32 00](https://user-images.githubusercontent.com/22172144/145246673-26224edb-3c4c-4275-bba3-5f466e3bc3c9.png)

I have noticed this issue for other indexers. Should i open up tickets for each one individually or all the ones i find in one ticket.

**Comment by ilike2burnthing** [comment]
So long as they're all basically the same thing, open a single new issue with all those you find, I'll tick them off as I work through them.

**Comment by AlanKellyEire** [comment]
I could probably fix these myself for ye. Its been a while since i used C# but i assume all i need is to open the repo in Visual Studio or is there more to it than that?

**Comment by ilike2burnthing** [comment]
Contributions are always welcome.

Normally I would just link to the [contributing guide](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md#setting-up-your-environment), however we recently updated to .NET 6.0 and have had some issues in getting a new environment working.

In theory it should just need VS 2022 and .NET 6.0 SDK, and everything else should be the same, but...

If you're up for trying it, by all means, and if you get it working, let us know if there was something specific you had to do.

**Comment by garfield69** [comment]
v0.20.136
