### ISSUE TITLE
[solidtorrents] Exception (solidtorrents): Error Parsing Json Response: Status=NotFound Response=<!DOCTYPE html><html lang=

### ISSUE THREAD

**Issue by toxic0berliner** [Jackett/Jackett#12650]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Runnking Jackett 0.19.249 from hotio/jackett on my docker host with portainer & watchtower, FlareSolverr enabled and working
```

### Description

testing the Solid Torrent always fails with the JSON parsing error above, below is the full log

### Logged Error Messages

Jackett.Common.IndexerException: Exception (solidtorrents): Error Parsing Json Response: Status=NotFound Response=<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" />
    <title>Bitsearch | #1 torrent search engine</title>

    <meta name="description" content="Bitsearch is #1 Torrent Index ever."/>
    <noscript id="deferred-styles">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    </noscript>
    <link rel='stylesheet' href='/stylesheets/style.css' />
    <link rel="preconnect" href="https://fonts.gstatic.com">

    <link rel="preload" as="image" href="/icons/category-movies.svg">
    <link rel="preload" as="image" href="/icons/category-video.svg">
    <link rel="preload" as="image" href="/icons/category-software.svg">
    <link rel="preload" as="image" href="/icons/category-music.svg">
    <link rel="preload" as="image" href="/icons/category-ebook.svg">
    <link rel="preload" as="image" href="/icons/category-games.svg">
    <link rel="preload" as="image" href="/icons/download-torrent.svg">
    <link rel="preload" as="image" href="/icons/download-magnet.svg">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="/scripts/autocomplete.min.js" type="a7fa30b76b81530f84def6da-text/javascript"></script>
    <script async defer src="/scripts/script.js" type="a7fa30b76b81530f84def6da-text/javascript"></script>
</head>

<body>
    
    <header>
        <div class="container r row">

            
            <div class="col header-links nexp-on-mobile nexp-on-tablet">
                <a href="/">
                    <img class="logo-1 show-on-large" src="/logo-navbar.svg" alt="Logo" width="200px"/>
                    <img class="logo-1 hide-on-large" src="/logo-round.svg" alt="Logo" width="60px"/>
                </a>
            </div>

            
            <div class="col center-flex nexp-on-desktop nexp-on-mobile">
                <form action="/search" class="search-form autocomplete" id="autocomplete">
                    <img src="/icons/search.svg" alt="">
                    <input name="q" class="autocomplete-input" type="text"
                        placeholder="Search Your Desired Item here..." value="">
                    <ul class="autocomplete-result-list"></ul>
                    <button type="submit">Search</button>
                </form>
            </div>

            
            <div class="col header-links w3-right-align show-on-large nexp-on-mobile nexp-on-tablet">
                <a href="#">Categories</a>
                <a href="#">Sign Up</a>
                <a href="#" class="login-button">Login</a>
            </div>
            <div class="col header-links w3-right-align hide-on-large nexp-on-mobile nexp-on-tablet">
                <a href="#" class="sidebar-trigger"><img src="/icons/menu.svg" alt="Menu"></a>
            </div>

        </div>
    </header>
    
    <div class="sidebar-overlay overlay">
        <div class="w3-sidebar">

            <br><br><br>

            <div class="collection">
                <div class="collection-item"><a href="/trending">Trending</a></div>
                <div class="collection-item"><a href="#">Latest</a></div>
                <div class="collection-item"><a href="#">Login</a></div>
                <div class="collection-item"><a href="#">Sign Up</a></div>
            </div>

            <div class="w3-bar-item w3-button">
                <div class="w3-col">
                    <div class="w3-col s6"></div>
                    <div class="w3-col s6"></div>
                </div>
            </div>
        </div>
    </div>
    <h1>Not Found</h1>
    <div class="overlay" style="z-index:3; display: none;" id="ad-block-popup">
	<div class="outer adblock-pop">
		<div class="middle">
			<div class="inner">
				<div class="container">
                    <div class="view-box relative" style="display: table">
                        <button onclick="if (!window.__cfRLUnblockHandlers) return false; closeAdblockPop()" class="close-button" data-cf-modified-a7fa30b76b81530f84def6da-="">Close</button>
                        <h2>😐😐You are using Ad-blocker!😐😐</h2>
                        <p>Help us pay the Bills by disabling your Ad-Blocker.</p>
                        <p>We never place any intrusive Ads or Pop-Ups which effects user experience. But as you have enabled Ad-blocker, We've decided to show you this Pop-Up. </p>
                        <p>I Promise You'll get much better Browsing experience With your Ad-Blocker turned off. 😁😁</p>
                        <p>We never place any Pop-up ads.</p>
                        <div id="timer">Wait 30 Sec</div>
                        <div style="display: none;" id="actual-link"><a id="your-link">Click Here To Continue.</a></div>
                    </div>
                </div>
			</div>
		</div>
	</div>
</div>
    <footer>
        <div class="container w3-row">
            <div class="w3-col s12 m6 footer-links">
                <a href="/about">About</a>
                <a href="/donate">Donate</a>
                <a href="/dmca">DMCA</a>
                <a href="/privacy-policy">Privacy Policy</a>
                <a href="/add-torrent">Add Torrent</a>
            </div>
            <div class="w3-col s12 m6 copyright">BitSearch © 2021 | All Rights Reserved</div>
        </div>
    </footer>

<script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="a7fa30b76b81530f84def6da-|49" defer=""></script></body>
<script async data-domain="bitsearch.to" data-api="/stats" src="/stats.js" type="a7fa30b76b81530f84def6da-text/javascript"></script>

</html>
 ---> System.Exception: Error Parsing Json Response: Status=NotFound Response=<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" />
    <title>Bitsearch | #1 torrent search engine</title>

    <meta name="description" content="Bitsearch is #1 Torrent Index ever."/>
    <noscript id="deferred-styles">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    </noscript>
    <link rel='stylesheet' href='/stylesheets/style.css' />
    <link rel="preconnect" href="https://fonts.gstatic.com">

    <link rel="preload" as="image" href="/icons/category-movies.svg">
    <link rel="preload" as="image" href="/icons/category-video.svg">
    <link rel="preload" as="image" href="/icons/category-software.svg">
    <link rel="preload" as="image" href="/icons/category-music.svg">
    <link rel="preload" as="image" href="/icons/category-ebook.svg">
    <link rel="preload" as="image" href="/icons/category-games.svg">
    <link rel="preload" as="image" href="/icons/download-torrent.svg">
    <link rel="preload" as="image" href="/icons/download-magnet.svg">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="/scripts/autocomplete.min.js" type="a7fa30b76b81530f84def6da-text/javascript"></script>
    <script async defer src="/scripts/script.js" type="a7fa30b76b81530f84def6da-text/javascript"></script>
</head>

<body>
    
    <header>
        <div class="container r row">

            
            <div class="col header-links nexp-on-mobile nexp-on-tablet">
                <a href="/">
                    <img class="logo-1 show-on-large" src="/logo-navbar.svg" alt="Logo" width="200px"/>
                    <img class="logo-1 hide-on-large" src="/logo-round.svg" alt="Logo" width="60px"/>
                </a>
            </div>

            
            <div class="col center-flex nexp-on-desktop nexp-on-mobile">
                <form action="/search" class="search-form autocomplete" id="autocomplete">
                    <img src="/icons/search.svg" alt="">
                    <input name="q" class="autocomplete-input" type="text"
                        placeholder="Search Your Desired Item here..." value="">
                    <ul class="autocomplete-result-list"></ul>
                    <button type="submit">Search</button>
                </form>
            </div>

            
            <div class="col header-links w3-right-align show-on-large nexp-on-mobile nexp-on-tablet">
                <a href="#">Categories</a>
                <a href="#">Sign Up</a>
                <a href="#" class="login-button">Login</a>
            </div>
            <div class="col header-links w3-right-align hide-on-large nexp-on-mobile nexp-on-tablet">
                <a href="#" class="sidebar-trigger"><img src="/icons/menu.svg" alt="Menu"></a>
            </div>

        </div>
    </header>
    
    <div class="sidebar-overlay overlay">
        <div class="w3-sidebar">

            <br><br><br>

            <div class="collection">
                <div class="collection-item"><a href="/trending">Trending</a></div>
                <div class="collection-item"><a href="#">Latest</a></div>
                <div class="collection-item"><a href="#">Login</a></div>
                <div class="collection-item"><a href="#">Sign Up</a></div>
            </div>

            <div class="w3-bar-item w3-button">
                <div class="w3-col">
                    <div class="w3-col s6"></div>
                    <div class="w3-col s6"></div>
                </div>
            </div>
        </div>
    </div>
    <h1>Not Found</h1>
    <div class="overlay" style="z-index:3; display: none;" id="ad-block-popup">
	<div class="outer adblock-pop">
		<div class="middle">
			<div class="inner">
				<div class="container">
                    <div class="view-box relative" style="display: table">
                        <button onclick="if (!window.__cfRLUnblockHandlers) return false; closeAdblockPop()" class="close-button" data-cf-modified-a7fa30b76b81530f84def6da-="">Close</button>
                        <h2>😐😐You are using Ad-blocker!😐😐</h2>
                        <p>Help us pay the Bills by disabling your Ad-Blocker.</p>
                        <p>We never place any intrusive Ads or Pop-Ups which effects user experience. But as you have enabled Ad-blocker, We've decided to show you this Pop-Up. </p>
                        <p>I Promise You'll get much better Browsing experience With your Ad-Blocker turned off. 😁😁</p>
                        <p>We never place any Pop-up ads.</p>
                        <div id="timer">Wait 30 Sec</div>
                        <div style="display: none;" id="actual-link"><a id="your-link">Click Here To Continue.</a></div>
                    </div>
                </div>
			</div>
		</div>
	</div>
</div>
    <footer>
        <div class="container w3-row">
            <div class="w3-col s12 m6 footer-links">
                <a href="/about">About</a>
                <a href="/donate">Donate</a>
                <a href="/dmca">DMCA</a>
                <a href="/privacy-policy">Privacy Policy</a>
                <a href="/add-torrent">Add Torrent</a>
            </div>
            <div class="w3-col s12 m6 copyright">BitSearch © 2021 | All Rights Reserved</div>
        </div>
    </footer>

<script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="a7fa30b76b81530f84def6da-|49" defer=""></script></body>
<script async data-domain="bitsearch.to" data-api="/stats" src="/stats.js" type="a7fa30b76b81530f84def6da-text/javascript"></script>

</html>
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1385
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 759
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/4751#issuecomment-986171021
