### ISSUE TITLE
[Xthor] No categories for some anime

### ISSUE THREAD

**Issue by hbooo** [Jackett/Jackett#1265]
Jackett Version 0.7.1272.0

Hello, 

It seems than some anime anime doesn't have categories in Xthor
![capture d ecran 2017-04-10 a 08 52 34](https://cloud.githubusercontent.com/assets/242125/24849265/36527e54-1dcb-11e7-8d80-8f90ca3df102.png)
When I check on the website, the episode is in the correct categorie but not on Jackett

**Comment by flightlevel** [comment]
@hbooo please provide the missing categories as per https://github.com/Jackett/Jackett/blob/master/src/Jackett/Indexers/Xthor.cs#L55

**Comment by hbooo** [comment]
@flightlevel  Categories are 101 and 110, here is the code that should be present I think

`    // Anime
            AddCategoryMapping(31, TorznabCatType.TVAnime);             // MOVIES ANIME
            AddCategoryMapping(32, TorznabCatType.TVAnime);             // SERIES ANIME
            AddCategoryMapping(110, TorznabCatType.TVAnime);             // ANIME VOSTFR
            AddCategoryMapping(101, TorznabCatType.TVAnime);             // PACK ANIME

`

**Comment by kaso17** [comment]
added with 77bc342ce93b2f57d68b2da2893063870b214925, thank you.
