### ISSUE TITLE
mikan: empty search returns old results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#12663]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
.
```

### Description

Empty search in mikan
* Old results
* Some results have size = 0

### Logged Error Messages

.

**Comment by ilike2burnthing** [comment]
10 pages of results are being fetched, going back ~6mths, some of which don't have a listed size.
