### ISSUE TITLE
epublibre: bad domain

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#12661]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
.
```

### Description

https://epublibre.unblockit.bz/ redirects to https://epublibre.unblockit.tv/

### Logged Error Messages

.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/12659
