### ISSUE TITLE
internetarchive: text search is not working

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#12675]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
.
```

### Description

Empty search is working but text search is not

### Logged Error Messages

```
Jackett.Common.IndexerException: Exception (internetarchive): Error Parsing Json Response: Status=ServiceUnavailable Response=<div style="margin:0 20px;text-align:center;font-weight:bold">We apologize but we cannot presently sort by: descpublicdate</div>
        </div><!--/.container-->
              </main>
    </div><!--/#wrap-->
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/12487#issuecomment-955533484
