### ISSUE TITLE
trackers not replacing "Full Stops" with white spaces so not returning all results

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#12689]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

os version: docker container

### Description

  
Issue #12654 can also be found on these sites.

Trackers i noticed with this issue.
- [x] PotUK - when you search the website with the fullstop it seems to remove it so does find all results but jackett does not.
- [x] bB - you wont get results on this site if full stops are in the search string. full stops are rarely used in torrent names on this site.
- [x] blutopia - you wont get results on this site if full stops are in the search string as full stops can only be in audio. if you search with or without full stops for audio it comes back. e.g "westworld s01 TrueHD 7 1" and "westworld s01 TrueHD 7.1" return the same results where as there are no results with "westworld.s01 TrueHD 7 1" or "westworld.s01 TrueHD 7.1" 
- [x] skipthecommericals - you wont get results on this site if full stops are in the search string as full stops can only be in audio. same as blutopia
- [x] uhdbits - you wont get results on this site if full stops are in the search string as there never is full stops in the torrent names.
- [x] crazyhd - you wont get results on this site if full stops are in the search string as there never is full stops in the torrent names.

### Logged Error Messages

   
replacing "." with full stops like you did for HD-torrents should fix all. 

### notes

if i find any more ill update this if its still open

### Screenshots

![uhdbits2](https://user-images.githubusercontent.com/57441681/145419705-7b86d2d5-5005-4ad3-995b-7d59f8d5a868.png)
![uhdbits1](https://user-images.githubusercontent.com/57441681/145419726-9c642aad-3753-45a7-968d-9b3bc5f3d2d5.png)
![skipthec2](https://user-images.githubusercontent.com/57441681/145419733-42faf810-545a-4816-8dc0-9c7e17635b60.png)
![skipthc1](https://user-images.githubusercontent.com/57441681/145419734-9296ad24-d22a-4ece-acb4-3dedd6714389.png)
![crazyhd2](https://user-images.githubusercontent.com/57441681/145419739-dc3e24dc-a2c4-4a3b-b26b-8737ab5d5b33.png)
![crazyhd1](https://user-images.githubusercontent.com/57441681/145419741-9081188b-fb8c-4b1b-b584-7a14ea9ceb3f.png)
![blutopia2](https://user-images.githubusercontent.com/57441681/145419743-cd4ff7ab-86fa-4cab-bc8a-6613597be94a.png)
![blutopia1](https://user-images.githubusercontent.com/57441681/145419747-b8352458-9eee-4f84-9a91-f638b21ebe99.png)
![bB2](https://user-images.githubusercontent.com/57441681/145419751-cbd5e23b-aec9-488c-919b-3b891ef43e1c.png)
![bB1](https://user-images.githubusercontent.com/57441681/145419758-d76431c6-e11a-468a-b370-791a4ac4b2ad.png)
![pot2](https://user-images.githubusercontent.com/57441681/145419761-34ad2fb8-53c1-4291-8ba6-63cb7c66bfc8.png)
![pot1](https://user-images.githubusercontent.com/57441681/145419768-b82074e1-2f52-4ec2-9957-e30a36dd8c05.png)

**Comment by ilike2burnthing** [comment]
STC has been added, the rest I don't have an account for, and while I don't foresee any problems, you might as well verify they're working without issue.

yml indexers - https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/4955/artifacts?artifactName=drop&api-version=6.0&%24format=zip

bB - https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/4956/artifacts?artifactName=drop&api-version=6.0&%24format=zip

**Comment by garfield69** [comment]
v0.20.159 for STC

**Comment by swannie-eire** [comment]
i tested and all 6 seem to be working as expected.

https://imgur.com/PDIeSR3 https://imgur.com/fc6RAfe

thanks.

if i find anymore ill open another ticket

**Comment by garfield69** [comment]
v0.20.170
