### ISSUE TITLE
[req]: hdmonkey

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12688]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: hdmonkey
- URL: https://hdmonkey.org/
- Description: hdmonkey is a Private ROMANIAN site for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): MST 24h MR 1.0
- Additional Comments: Registration is currently invite only.

I received an invite in the mail for this site with the following message:

Hi there, I send this invite for you and maybe you can help us for our site also appears in your database in the indexing section.
```

**Comment by garfield69** [comment]
v0.20.141

**Comment by garfield69** [comment]
https://hdmonkey.org/ returns This domain name expired on 2022-07-09 14:20:50

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
Not Found
The requested URL was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/12688#issuecomment-1179785933

**Comment by garfield69** [comment]
v0.21.314
