### ISSUE TITLE
kickasstorrents-to / kickasstorrents-ws: add title match

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#12683]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
.
```

### Description

kickasstorrents-to / kickasstorrents-ws

Search "silicon valley" => "The Age of Surveillance Capitalism: The Fight for a Human Future at the New Frontier of Power AudioBook"
Search "Harry Potter" =>  "Twilight (2008) 1080p BluRay Multi AV1 Opus AV1D"

### Logged Error Messages

.

**Comment by ilike2burnthing** [comment]
I can recreate this issue for *-to but not *-ws

**Comment by ngosang** [comment]
yep, it's fine
