### ISSUE TITLE
Error using Sharewood 

### ISSUE THREAD

**Issue by batitou81** [Jackett/Jackett#12681]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jacket version 0.20.105 on a raspberry pire
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

### Description

Hello, 
I can t add sharewood to my jackett. Jackett is already working with another tracker, the passkey's passkey is the right one... 
I tried using the "Sharewood API" And the "Sharewood" Entry on jackett, same result. 
Can you help me ? 

### Logged Error Messages

TrustFailure error 

### Screenshots

![original_ccd5966e-1077-49a9-b1d5-bb479d639a9f_Screenshot_2021-12-08-12-27-12-439_com android chrome](https://user-images.githubusercontent.com/22175623/145202736-6fa14b0f-1e80-4fff-a327-e4cacb8bac23.jpg)

**Comment by batitou81** [comment]
Jackett log

![Uploading Screenshot_2021-12-08-12-48-08-560_com.android.chrome.jpg…]()

**Comment by batitou81** [comment]
![Screenshot_2021-12-08-12-48-08-560_com android chrome](https://user-images.githubusercontent.com/22175623/145204422-d6c37baf-a436-457c-9281-92d3a94ae4e2.jpg)

**Comment by ilike2burnthing** [comment]
There seems to be an issue with the site at the moment:

```text
Site & Tracker instables. Merci de patienter. Inutile de refresh vos torrents, ça reviendra tout seul.
```

```text
‎Unstable site & tracker. Please be patient. No need to refresh your torrents, it will come back on its own.‎
```

I got numerous errors using both indexers, from the login form not being found to not being able to connect to the site at all. It also initially failed in browser for me.

Not sure whether switching to http and then back to https actually helped, or whether it was a case of just trying enough times (~20), but I've eventually gotten it working, so try that and see if you get anywhere with it.
