### ISSUE TITLE
Alpharatio returning extra results

### ISSUE THREAD

**Issue by newadventure079** [Jackett/Jackett#12693]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-12-10 13:41:50	Info Using HTTP Client: HttpWebClient2
2021-12-10 13:41:50	Info Using FlareSolverr: No
2021-12-10 13:41:50	Info Using proxy: Disabled
2021-12-10 13:41:50	Info App config/log directory: /config/Jackett
2021-12-10 13:41:50	Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-12-10 13:41:50	Info Running in Docker: Yes (image build: v0.20.95-ls51)
2021-12-10 13:41:50	Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2021-12-10 13:41:50	Info Jackett variant: CoreLinuxAmdx64
2021-12-10 13:41:50	Info OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
2021-12-10 13:41:50	Info Environment version: 6.0.0 (/app/Jackett/)
2021-12-10 13:41:49	Info Starting Jackett v0.20.95
```

### Description

This is the exact same issue as #12631 but with Alpharatio.  It might be related to #8327

When I search for `Brooklyn Nine-Nine S04` in Jackett, I get results for all sorts of other seasons.  However, when I put the exact same search into Alpharatio's search on their site, I get results for only S04.

Looking at the logs, it does look like the season is being stripped off the search.  `https://alpharatio.cc/ajax.php?action=browse&order_by=time&order_way=desc&searchstr=Brooklyn+Nine-Nine`  I'm not sure why #8327 was introduced because it looks like you can search by season on Alpharatio

### Logged Error Messages

[log.txt](https://github.com/Jackett/Jackett/files/7695373/log.txt)

### Screenshots

![Screen Shot 2021-12-10 at 1 40 12 PM](https://user-images.githubusercontent.com/84156407/145638691-2eb6ec12-985c-40c8-8f42-4e1f760437a9.jpg)

![Screen Shot 2021-12-10 at 1 40 26 PM](https://user-images.githubusercontent.com/84156407/145638722-aa967ab5-cdc8-40ca-88c5-0d0e6789267b.jpg)

**Comment by ilike2burnthing** [comment]
It's easy enough for us to revert #8327, but @triesmon can you confirm that this is also the case for you on AR now? Or has the site just changed? Just want to make sure there's not some setting which means different users are affected differently.

@garfield69 and/or @ngosang can you double check this as well?

**Comment by newadventure079** [comment]
I agree completely.  Let's see what others say first

**Comment by garfield69** [comment]
I can't double check this because net6 and my vs2022 are not generating a debug code so I cant test the code revert to prove AR is working with Sonarr using the original code prior to 8327.
Why don't you submit a PR and I can test and compare the results using that method.

**Comment by ilike2burnthing** [comment]
Oh sorry, I just meant check that you can search by season on the site itself, but I'll submit a PR now so you can verify with it as well.

**Comment by garfield69** [comment]
LGTM

**Comment by ilike2burnthing** [comment]
@triesmon if this results in any issues for you, let us know

**Comment by garfield69** [comment]
v0.20.147
