### ISSUE TITLE
[yggtorrent] FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=55000 (ms) (Config)

### ISSUE THREAD

**Issue by DoryanChaigneau** [Jackett/Jackett#12692]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
NAS
```

### Description

Jackett end loading... why ?

### Logged Error Messages

An error occurred while updating this indexer
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=55000 (ms)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/12634
