### ISSUE TITLE
[req]: freshmeat.io

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#12698]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: freshMeat
- URL: freshmeat.io
- Description: Public torrent search engine
- Minimum Seeding Time and Minimum Ratio (if Private):
- Additional Comments:
```

**Comment by garfield69** [comment]
v0.20.170

**Comment by ilike2burnthing** [comment]
https://freshmeat.io/ - HTTP ERROR 500

**Comment by garfield69** [comment]
https://freshmeat.io/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://freshmeat.io/ returns HTTP ERROR 500 (Internal Server Error)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://freshmeat.io/ returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/12698#issuecomment-1305001338

**Comment by garfield69** [comment]
v0.21.356
