### ISSUE TITLE
TorrentBytes is broken in the newest release

### ISSUE THREAD

**Issue by sethwarsh** [Jackett/Jackett#127]
It worked fine in last nights (the release from about a week ago .55) but in the new release (.57) you can't log in any longer.  Can you please resolver this ASAP.

Thanks
Seth

**Comment by flightlevel** [comment]
Duplicate https://github.com/Jackett/Jackett/issues/120
Can't do much without logs or invite

**Comment by sethwarsh** [comment]
I’ll send you an invite now.

Do you prefer the invite or logs?

Thanks

Seth

**Comment by sethwarsh** [comment]
I don’t have any invites to this site, tell me where and what to get from the logs (in OSX). In the mean time I sent a pretty compelling request to the sites admin to get you an invite.

Much appreciated,

Seth

**Comment by flightlevel** [comment]
enable logging https://github.com/Jackett/Jackett#troubleshooting
get log from folder it will be in applicationdata folder or commonapplicationdata folder https://www.jimrich.sk/2015/01/18/environment-specialfolder-on-windows-linux-and-os-x/

**Comment by sethwarsh** [comment]
Ok will do when I get home from physical therapy in 2 hrs. I already enabled logging.

Best
Seth

I think you should be getting an invite too.

**Comment by sethwarsh** [comment]
You know what it worked now, it must have been some weird fluke with the site or something,

BTW did they send you an invite? I made a pretty compelling case, I’d like to know if they sent you one or not?

Thanks

Seth

**Comment by flightlevel** [comment]
No invite yet, might have been something on their end as nothing has changed with this indexer recently

**Comment by duramato** [comment]
TorrentBytes has open signups atm..
