### ISSUE TITLE
Request new tracker: CynicalGen

### ISSUE THREAD

**Issue by Krambaek** [Jackett/Jackett#12707]
- Name: CynicalGen
- URL: https://cynicalgen.org/
- Description: Another danish tracker
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: UNIT3D base

signup closed, invitation only.

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.

**Comment by Krambaek** [comment]
Thiers invitation system is not currently working. But I keep trying :)

**Comment by Krambaek** [comment]
They closed
