### ISSUE TITLE
Potuk substring search not returning results

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#12717]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
os version: docker container
Jackett version: v0.20.170
```

### Description

if you search for a substring along with a string on the PotUK indexer you wont get results. If you search for the same thing on the PotUK website you do get results.

if you search for just the substring you will get results but won if you also add in string.

I dont see this issue occurring with any other indexer i tested.

url query from search on site.
https://www.potuk.net/index.php?search/11111/&q=gomorrah+playweb&o=date

### Logged Error Messages

none

### Screenshots

https://i.imgur.com/MMDUahJ.png
https://i.imgur.com/aiTEVG1.png

**Comment by ilike2burnthing** [comment]
This is the current search path:
https://github.com/Jackett/Jackett/blob/c3620780e6d47159bfff3652cd5ac1b4bbe9366e/src/Jackett.Common/Definitions/potuk.yml#L118-L121
That's obviously from the example you've posted above.

**Comment by garfield69** [comment]
you are using the general forum search on the web site which does not return a torrent results page but a forum titles page.
We cannot use this page because embedded in the search query is your userid which is not available to jackett. (12345 in the example below that I made up)
https://www.potuk.net/index.php?search/12345/&q=gomorrah+playweb&c[title_only]=1&o=date

the torrent search page is at https://www.potuk.net/index.php?torrents/
feel free to enter partial matches in the filename field on the web site on this page and see if you can figure out what the masking is for separate keywords.
I've not been able to find it so far.

**Comment by ilike2burnthing** [comment]
We can get torrents-only results from the forum search by using:
https://www.potuk.net/index.php?search/12345/&q=2021+1080p&t=post&c[child_nodes]=1&c[nodes][0]=7&c[title_only]=1&o=date&g=1
and we could add the userid as a login credentials field so this would actually work.

However, we'd lose all torrent information other than title, date, and category, we could no longer search by freeleech-only (we couldn't even filter by it), and we'd have to switch to using the download block so would lose the choice of torrent or magnet.

@swannie-eire Unless there is some way of searching using multiple keywords that aren't in the precise order of an existing title, I would suggest instead asking the site staff to change the torrent search from the strict `filename` field they currently have, to the same flexible `keyword` field they use for their forum search. That's not just for the benefit of Jackett users, as it currently makes searching on the site itself more difficult.

**Comment by swannie-eire** [comment]
i have brought it to the staff attention before about the search and they were not open to the idea of changing it. 

Now that we know the issue is with the site. its best to close this.

Thanks for the investigation into the issue. now i know the cause ill just make sure not to use substrings in the future.
