### ISSUE TITLE
[req]: SpiderTK

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#12718]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: SpiderTK
- URL: https://spidertk.xyz/
- Description: SpiderTK is a FRENCH Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): 0.8
- Additional Comments: signup currently open, IP locked, NexusPHP Standard v1.5 Beta 4 (?)
```

**Comment by garfield69** [comment]
v0.20.188

**Comment by ilike2burnthing** [comment]
Working ok here. I think the DDoS protection screen is only when your IP address hasn't been whitelisted yet. You also can't download if you haven't been whitelisted.

There was an issue about this, which was resolved when they switched to a whitelisted IP (their seedbox) - https://github.com/Jackett/Jackett/issues/12732

If there is some other issue though, try switching to the cookie method and confirm downloads work.

**Comment by Innursery** [comment]
the captcha code always time out
![Jack](https://user-images.githubusercontent.com/426016/147505518-925fb23b-44ba-4d98-a98e-8931f39bcae5.png)

**Comment by ilike2burnthing** [comment]
That doesn't show the captcha timing out, just being wrong. If you get it wrong, close the config panel, reopen it, and enter the new captcha.

**Comment by Innursery** [comment]
yes but it's just work a few minutes, after I have to redo (enter new captcha)

**Comment by ilike2burnthing** [comment]
Open a new issue and provide the requested information.

**Comment by ilike2burnthing** [comment]
@garfield69 still getting the DDoS screen? Do downloads work in browser?

**Comment by garfield69** [comment]
>still getting the DDoS screen?

yes, both my browser and Jackett get this intermediate screen.
![image](https://user-images.githubusercontent.com/6933240/148483118-65b1c917-e2be-4842-a7a6-51ce90ee6989.png)

but since I am still logged in, afterwards I am back at the torrent page

> Do downloads work in browser?

yes, I can initiate a download from my browser. I have not taken the time to code a cookie version to test the indexer access in that manner yet. 
I'll try on my next free time slot.

**Comment by garfield69** [comment]
yes, using the cookie method lets my indexer search for torrents and initiate a download.

note that for first time users, the first download invokes a first-time-rules page before download is started, after which further downloads are direct.

So I take it that it is just me getting the DDoS check?
Do we want to permanently switch to cookie method, or provide an alternate indexer for cookie?

**Comment by ilike2burnthing** [comment]
Yea, switch to cookies. If it's affecting you it will likely affect someone else. Or who knows, maybe you're just special ;P

**Comment by garfield69** [comment]
v0.20.256

**Comment by ilike2burnthing** [comment]
https://spidertk.xyz/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
According to the site they've dropped their DDoS protection and IP whitelist. Can you check if that's definitely the case for you? Then we can revert to credentials login.

**Comment by garfield69** [comment]
Yes, standard login with text captcha works, I can login ,search and initiate a download.
I'll revert the indexer.

**Comment by garfield69** [comment]
v0.20.319

**Comment by garfield69** [comment]
https://spidertk.xyz/ returning Error 502 Bad gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://spidertk.xyz/ - `Spiders at work`

**Comment by garfield69** [comment]
v0.20.1047

**Comment by garfield69** [comment]
https://spidertk.top/ returns Error 502 Bad gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://spidertk.top/  returns Le site est en maintenance, veuillez réessayer plus tard... merci

**Comment by garfield69** [comment]
online

**Comment by silkyclouds** [comment]
Sorry gents but did anyone figure out how to snatch a torrent from the tracker ? 

here is what I'm getting : 

08-18 12:45:37 Error Error downloading. indexer: spidertk path: https://spidertk.top/download.php?id=XXXXX
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 85

**Comment by ilike2burnthing** [comment]
Try to download a torrent from the site, you will be presented with a page with a tick box. Leave this box ticked and click to download your torrent. Now you can download any torrent through Jackett.

**Comment by silkyclouds** [comment]
Damn !!! It was that obvious! I never downloaded anything from the site. and that checkbox is needed to accept the rules. Thanks for the tip dude ! :)

**Comment by ilike2burnthing** [comment]
https://spidertk.top/ - Le site est en maintenance, veuillez réessayer plus tard... merci

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://spidertk.top/login.php returns 
```
Site is down for maintenance, please check back again later... thanks
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://spidertk.top/
![image](https://user-images.githubusercontent.com/6933240/217411195-75d6d38d-9ab5-4636-8615-f1a9e9fc425a.png)

**Comment by garfield69** [comment]
online

**Comment by silkyclouds** [comment]
just my to cents but I could not connect the tracker using prowlarr for several weeks (again). 

this tracker is a damn pain in the back and the devs are not willing to implement an API. 

So what now ?

**Comment by ilike2burnthing** [comment]
Other that the times mentioned above, the tracker has been fine. Any API would run on the same servers, so it would make no difference if they were down for maintenance.

If you're having issues with the indexer in Prowlarr, I suggest discussing it with them on their Discord.

**Comment by garfield69** [comment]
https://spidertk.top/ ERR_CONNECTION_TIMED_OUT

**Comment by simardwtf** [comment]
This site can’t be reachedspidertk.top took too long to respond.
Try: Checking the connection

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://spidertk.top/ ERR_CONNECTION_TIMED_OUT

**Comment by OrpheeGT** [comment]
SpiderTK is dead and won't come back :

![image](https://github.com/Jackett/Jackett/assets/8038551/95abc9c9-6280-487a-ab0b-69992a09ac9e)

**Comment by ilike2burnthing** [comment]
> Morally, physically and financially, we're tired, so we're not starting from scratch, so SpiderTK is closing its doors for good.

Where is this from?

**Comment by OrpheeGT** [comment]
From another french tracker where SpikerTK's admin is registered too.

**Comment by ilike2burnthing** [comment]
Thanks for letting us know. We'll probably continue to monitor this for the usual month that we give all trackers, as we've seen some be resurrected before, including one earlier today - https://github.com/Jackett/Jackett/issues/5635.

**Comment by garfield69** [comment]
v0.21.662
