### ISSUE TITLE
Cannot download torrents from within Jackett [NewPCT]

### ISSUE THREAD

**Issue by pkreuzt** [Jackett/Jackett#12736]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /var/lib/jackett/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Debian GNU/Linux 11 \n \l
Jackett variant: CoreLinuxArm64
OS version: Unix 5.10.0.10 (64bit OS) (64bit process)
Environment version: 6.0.1 (/opt/jackett/)
Starting Jackett v0.20.197
```

### Description

Seems the download links cannot be reached if you don't browse through the shitload of intrusive ads this site has. So Sonarr/Radarr always fail when trying to get torrents after search gives results. 
Even the links when searching right through Jackett are unusable, since accesing the site and pressing download link on the site reports "NO SE PUEDE DESCARGAR POR AHORA" (_"cannot be downloaded yet"_). But if you visit the website and go through all the search process with a ton of emergent tabs and crap, then content is reachable.

### Logged Error Messages

`Error | Error downloading. indexer: newpct path: https://atomixhq.one/descargar/serie-en-hd/the-expanse/temporada-6/capitulo-03/ System.Exception: Download link not found!    at Jackett.Common.Indexers.NewPCT.Download(Uri linkParam) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/NewPCT.cs:line 197    at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 56`

**Comment by ilike2burnthing** [comment]
Were you able to download a torrent file from the site? Even if I disable ad blockers for the site (which I don't recommend anyone do, it makes the site unusable) I still couldn't get it to work, looking at both old and new uploads.

**Comment by pkreuzt** [comment]
Site is truly a PIA to browse. I'll answer with an example. Searching The Expanse S06E03 in Sonarr it shows some results, one of them (and preferred in my config) being this:

(https) atomixhq.one/descargar/serie-en-hd/the-expanse/temporada-6/capitulo-03/

But from Sonarr or Jackett this torrent cannot be downloaded or sent to torrent client. Opening the link right on browser shows "cannot download yet" error. However, navigating the site and searching manually I reach same exact page. After some attempts (site is too loaded with ads) I get redirected to another link:

(https) atomtt.com/download/164930_-1640321376-The-Expanse---Temporada-6--HDTV-720p-AC3-5-1/

where i can finally download the torrent file.

**Comment by ilike2burnthing** [comment]
[v0.20.198](https://github.com/Jackett/Jackett/releases/tag/v0.20.198)
