### ISSUE TITLE
[spidertk] Login failed: No form found on https://spidertk.xyz/login.php using form selector form[action=

### ISSUE THREAD

**Issue by maxcore** [Jackett/Jackett#12732]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-12-24 15:23:58	Info	
Loading Native indexers ...
2021-12-24 15:23:57	Info	
Using HTTP Client: HttpWebClient2
2021-12-24 15:23:57	Info	
Using FlareSolverr: http://192.168.2.124:8191
2021-12-24 15:23:57	Info	
Using proxy: Disabled
2021-12-24 15:23:57	Info	
App config/log directory: /config
2021-12-24 15:23:57	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-12-24 15:23:57	Info	
Running in Docker: Yes (image build: unknown)
2021-12-24 15:23:57	Info	
File /etc/issue: Ubuntu 20.04.3 LTS \n \l
2021-12-24 15:23:57	Info	
Jackett variant: CoreLinuxAmdx64
2021-12-24 15:23:57	Info	
OS version: Unix 5.10.28.0 (64bit OS) (64bit process)
2021-12-24 15:23:57	Info	
Environment version: 6.0.1 (/app/)
2021-12-24 15:23:57	Info	
Jackett Data will be stored in: /config
2021-12-24 15:23:57	Info	
Starting Jackett v0.20.197
```

### Description

cant add to jackett

### Screenshots

--

**Comment by maxcore** [comment]
[log (1).txt](https://github.com/Jackett/Jackett/files/7775123/log.1.txt)
Full log here

**Comment by ilike2burnthing** [comment]
Have you just joined SpiderTK? Has the IP address of the device Jackett is on been added to their whitelist?

**Comment by maxcore** [comment]
@ilike2burnthing thx ! i install on my seedbox and the problem was gone thx for you time
