### ISSUE TITLE
[req]: New "SiteRip's 2022 (HD Video)" category to PornoLab indexer

### ISSUE THREAD

**Issue by TheMiracleExpress** [Jackett/Jackett#12731]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

New category "Сайтрипы 2022 (HD Video) / SiteRip's 2022 (HD Video)" with ID=1857 has been added to PornoLab website, but it's still not available to use in related indexer: "Warn | Some of the categories provided are unsupported in PornoLab: 1857"

Same result for ID=101857

### Describe the solution you'd like

Please add new category "Сайтрипы 2022 (HD Video) / SiteRip's 2022 (HD Video)" with ID=1857 to PornoLab indexer

**Comment by garfield69** [comment]
the new cats will be available in the next Jackett release due out in about 11 hours or so.

**Comment by garfield69** [comment]
v0.20.197
