### ISSUE TITLE
[req]: GPW - Great Poster Wall

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#12743]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: GPW - Great Poster Wall
- URL: https://greatposterwall.com
- Description: Chinese Movie tracker
- Minimum Seeding Time and Minimum Ratio (if Private): n/a
- Additional Comments: Open for sign up now. not sure how long sign up will be open for.

https://greatposterwall.com/register.php
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/Seals.cs

**Comment by swannie-eire** [comment]
is there some way to search the indexers better. 

A lot of the indexers i only find jackett supports them when i search for them in github. for example this one. it would be great to be able to search the URLs, the indexer names, descriptions etc..

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/10870
