### ISSUE TITLE
[Question] custom indexers persist after updates?

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#12747]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Docker container.
```

### Description

at the moment every time i update it removes all the custom indexers i have in `jackett/Definitions/`. I assume this is because it just downloads and extracts the updated version to the same dir. Currently after each update i have to copy, set the correct permissions on all the custom/modified indexers i use and then restart jackett and add the custom indexers back.

the only related ticket i can find is https://github.com/Jackett/Jackett/issues/2656 but it does not actually say how to have the custom indexers persist after updates.

is it possible to have custom indexers persist after updates?

### Logged Error Messages

none

**Comment by ilike2burnthing** [comment]
If you haven't already, volume map the container folder `/config` to somewhere accessible on your host, e.g. `/volume1/Docker/Jackett/config`.

Access `/volume1/Docker/Jackett/config` (or wherever you've set) and create a new folder in it called `cardigann` then a new folder within that one called `definitions` (so you end up with `/volume1/Docker/Jackett/config/cardigann/definitions`).

Add your custom indexers to that folder.

**Comment by swannie-eire** [comment]
thanks for the prompt response. 

I created the folder by following you instructions and i can see the docker can see those yaml files by logging into the container but when i go to search for the indexers in jackett they are not there like they are when i add them manually to `jackett/Definitions/`.

I did a restart of the container and the custom indexers are not there.

**Comment by ilike2burnthing** [comment]
The path within the container should be `/config/cardigann/definitions`

**Comment by swannie-eire** [comment]
thanks that worked like a dream.

For anyone else who wants custom indexers to persist, you can see the location where the custom indexers are supposed to be saved from the logs. You should see a line like this `2021-12-30 16:02:43.9624 Info Loading Cardigann indexers from:` with the paths to the indexer ymls.
