### ISSUE TITLE
Incorrect Name sent to Sonarr/Radarr

### ISSUE THREAD

**Issue by fevkalbeser** [Jackett/Jackett#1274]
When trying to search for a movie using Radarr/Sonarr via Jackett, the letter "I"(capital i) is not grabbed from Jackett, resulting in erroneous importing of the movie and failure to download.

I am using Jackett to search from indexers such as IPTorrents and Katcr. The search from within the app itself lists correct results. However, when I use Radarr/Sonarr to search, the "I" (if it is at the beginning of the word) is deleted from the movie/tv show name and therefore Radarr/Sonarr says it does not match the wanted movie/episode and cannot download. 

![radarr3](https://cloud.githubusercontent.com/assets/26334331/24909286/f9584a86-1ecb-11e7-8bd7-6f76601f57bb.JPG)

![radarr4](https://cloud.githubusercontent.com/assets/26334331/24909331/25954cfc-1ecc-11e7-88e2-f6121db31b73.JPG)

First opened the issue in Radarr page but was told the problem is probably in Jackett, since both Radarr and Sonarr are acting the same way. Also another user was not able to reproduce the issue, which made me think maybe it is a localization issue (the display language is English, but the localization settings are Turkish on the computer running Jackett)

Any ideas?

Jackett version:  0.7.1272.0

**Comment by fevkalbeser** [comment]
As I suspected, the issue was caused by system language. Changed the format to United Kingdom and the problem was solved. Not the perfect solution but it works nonetheless.

**Comment by kaso17** [comment]
Can you please let us know more about your environment (operation system, and which language settings exactly are causing the problem)

**Comment by fevkalbeser** [comment]
Operating system is Windows 8.1. Windows display language was English and date, time and number formatting were all in Turkish. I changed all of them to English (UK) and that sloved the problem. However, now I am having trouble viewing Turkish charachters in .srt files, so I hope you come up with a fix.

**Comment by fevkalbeser** [comment]
@kaso17 Now I made some changes and noticed the problem in the .srt files are caused by the change I made in language for non-unicode programs. I changed it back to Turkish and now I can view the characters correctly and also search correctly using Jackett. It seems that date, time and number formatting is the culprit here.

**Comment by kaso17** [comment]
Unfortunately I can't reproduce this on my windows 7 system by setting the Format to Turkish.
if this is still a problem with the latest jackett version can you please post the result of the following query with turkish and UK format configurations?
http://127.0.0.1:9117/torznab/iptorrents/api?t=search&q=kong:%20skull%20island&apikey=YourApiKey

**Comment by ngosang** [comment]
@fevkalbeser Is this problem still present in the latest version? Can I close?

**Comment by fevkalbeser** [comment]
I just checked again and it seems the problem is resolved. You can close.

**Comment by shotwn** [comment]
Having same problem on versions: 0.12.1795.0 and 0.12.1815.0 with Sonarr. 
- Releases with name starting Air Crash Investigation (Mayday) at season 20 had this problem.
- I did not try it with an another release, since it is hard to make Sonarr target something specific.
- Changing system language, non unicode language preferences and region/format to English did not help.

![image](https://user-images.githubusercontent.com/2876361/74572379-15550600-4f90-11ea-9744-4e5433e2f8e3.png)

[systemnfo.txt](https://github.com/Jackett/Jackett/files/4207077/systemnfo.txt)

**Comment by ngosang** [comment]
The search in Jackett is working, but I didn't test in Sonarr
![image](https://user-images.githubusercontent.com/10577978/74588935-2c800c00-5001-11ea-8631-99605dcefeb8.png)

**Comment by garfield69** [comment]
closing as stale.
