### ISSUE TITLE
BJ-Share no support for 2FA?

### ISSUE THREAD

**Issue by IgorMCesar** [Jackett/Jackett#12746]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.22000.0 (64bit OS)
Environment version: 6.0.1 (C:\ProgramData\Jackett\)
```

### Description

I have 2FA enabled in BJ-Share. The BJ-Share config in Jackett does not account for 2FA. Is there a way to update it to account for 2FA?

### Logged Error Messages

An error occurred while updating this indexer

### Screenshots

![image](https://user-images.githubusercontent.com/5064518/147653119-28098b92-58d3-4215-8511-7504c4465d8a.png)

**Comment by ilike2burnthing** [comment]
@christianfds or @uilton-oliveira would either of you be able to either add this to the current indexer, or create a separate 2FA version of it?

**Comment by ilike2burnthing** [comment]
#12756

**Comment by garfield69** [comment]
v0.20.222
