### ISSUE TITLE
[req]: make Flaresolverr timeout configurable : 55sec is not enough

### ISSUE THREAD

**Issue by lstalens** [Jackett/Jackett#12750]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Running FlareSolverr on a Synology (DS220+, not ARM processor), I most of the time run into a timeout when loading FlareSolverr...

### Describe the solution you'd like

Adding an option to manually configure the FlareSolverr maxTimeout value that is hardcoded to 55000 msec 

### Describe alternatives you've considered

FlareSolverr forced timeout value - refused by the developper as set per parameter to the in request

**Comment by garfield69** [comment]
v0.20.280

**Comment by lstalens** [comment]
Hi guys,

Many thanks for the implementation of this feature, helped me to resolve the timeout issue 👍
