### ISSUE TITLE
[req]: GreatPosterWall

### ISSUE THREAD

**Issue by ablakers** [Jackett/Jackett#12758]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: GreatPosterWall
- URL: https://greatposterwall.com
- Description: Chinese Gazelle-based movie tracker
- Minimum Seeding Time and Minimum Ratio (if Private): MST 48hrs, MR up to 0.6
- Additional Comments: More details on ratio requirements here. Site is currently open signup
```

**Comment by garfield69** [comment]
already available under the alias Seals.
PS rules on the site forbid mentioning its official name, use the alias if you need to reference.
