### ISSUE TITLE
[req] TorrentSeeds

### ISSUE THREAD

**Issue by Mouton99** [Jackett/Jackett#12751]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
N/A
```

### Description

TorrentSeeds.org now uses UNIT3D; was using a custom backend before.

### Logged Error Messages

N/A

**Comment by garfield69** [comment]
v0.20.216

**Comment by garfield69** [comment]
https://torrentseeds.org/ cloudflare A timeout occurred Error code 524

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
torrentseeds api returning Server Error 500
web site torrent browsing working ok.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://torrentseeds.org/ cloudflare Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://torrentseeds.org/ cloudflare Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up
