### ISSUE TITLE
[req]: Scrape RarBG site?

### ISSUE THREAD

**Issue by SmartBoy84** [Jackett/Jackett#12768]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Currently when querying RarBG's APIs the search request can not be as ambiguous as it can be when searching on the rarbg site (one has to be more specific), on top of that the API only returns the first 100 results

### Describe the solution you'd like

Ideally, provide an option to query the actual site rather than the API with the downside of that, evidently, being slower.

**Comment by garfield69** [comment]
The owner expressly forbid us to scrape the web site and requires us to use the provided api only.
