### ISSUE TITLE
[redacted] Your API Key did not work: Found 0 results in the tracker (Config)

### ISSUE THREAD

**Issue by Bearmancer** [Jackett/Jackett#12765]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-01-03 05:32:49 	Info 	

Using HTTP Client: HttpWebClient2

2022-01-03 05:32:49 	Info 	

Using FlareSolverr: No

2022-01-03 05:32:49 	Info 	

Using proxy: Disabled

2022-01-03 05:32:49 	Info 	

App config/log directory: C:\ProgramData\Jackett

2022-01-03 05:32:49 	Info 	

ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads

2022-01-03 05:32:49 	Info 	

Running in Docker: No

2022-01-03 05:32:49 	Info 	

Jackett variant: CoreWindows

2022-01-03 05:32:49 	Info 	

OS version: Microsoft Windows NT 10.0.19044.0 (64bit OS)

2022-01-03 05:32:49 	Info 	

Environment version: 6.0.1 (C:\ProgramData\Jackett\)

2022-01-03 05:32:48 	Info 	

Starting Jackett v0.20.233
```

### Description

I used an API generated by RED but got the error described in the title above.

### Logged Error Messages

[redacted] Your API Key did not work: Found 0 results in the tracker (Config)

**Comment by Qstick** [comment]
Red is having issues currently with torrent search

**Comment by emi-rii** [comment]
I'm having the same issue

**Comment by Qstick** [comment]
They are back to normal now

**Comment by Bearmancer** [comment]
Ok the issue is fixed. I can add Redacted now.
