### ISSUE TITLE
[req]: Always serve requests directly from Jackett and proxy all requests

### ISSUE THREAD

**Issue by budgetfermium** [Jackett/Jackett#12761]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Images shown during mouseover are not proxied.

To replicate:
1. Open Jackett.
2. Enable the logger in uBlock Origin.
3. Search JPopsuki for any torrent.
4. Hover your mouse over the name of the torrent.
5. Observe there is a request to https://jpopsuki.eu/static/images/torrents/*.th.jpg.

### Describe the solution you'd like

Always serve requests directly from Jackett. Proxy all requests (including images shown during mouseover) if the proxy option is enabled.

### Describe alternatives you've considered

Allow users to disable image previews on mouseover.

**Comment by ngosang** [comment]
This should be implemented.

**Comment by garfield69** [comment]
v0.20.363
