### ISSUE TITLE
[req]: Mediamaatjes

### ISSUE THREAD

**Issue by sembeek** [Jackett/Jackett#12767]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Mediamaatjes
- URL: https://www.mediamaatjes.org/
- Description: Mediamaatjes is a DUTCH Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): MR 1.0
- Additional Comments: Open registration at http://www.mediamaatjes.org/signup.php
```

**Comment by garfield69** [comment]
v0.20.244

**Comment by ilike2burnthing** [comment]
https://www.mediamaatjes.org/
- Web server is returning an unknown error - Error code 520
- Web server is down - Error code 521

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.mediamaatjes.org/ returns ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
v0.20.2122
