### ISSUE TITLE
t411.ai error

### ISSUE THREAD

**Issue by thenamelessthing** [Jackett/Jackett#1276]
Since a couple of days maybe week, I now obtain this error

![image](https://cloud.githubusercontent.com/assets/10235448/24937009/9ed3e892-1efb-11e7-8153-064b12049ce6.png)

Jackett version:  Jackett Version 0.7.1287.0
Mono version (if not using Windows):  Mono JIT compiler version 4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan  3 11:48:26 UTC 2017)

-------------------------------

**Comment by raspdealer** [comment]
Same for me, they probably changed something

**Comment by JigSawFr** [comment]
@raspdealer @thenamelessthing please search before post an issue, t411 API is down for the moment

cf. https://github.com/Jackett/Jackett/issues/1264
