### ISSUE TITLE
[bjshare] Exception (bjshare): The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings. (Test)

### ISSUE THREAD

**Issue by timartinelli** [Jackett/Jackett#12778]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
An error occurred while testing this indexer
Exception (bjshare): The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
Click here to open an issue on GitHub for this indexer.
```

### Description

the site is working normal, now stopped.

It was working and stopped, from a weird cookie error, the torrent site now has a captha.

### Logged Error Messages

 An error occurred while testing this indexer
Exception (bjshare): The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
Click here to open an issue on GitHub for this indexer.

### Screenshots

https://i.imgur.com/5xgyRAx.png

**Comment by ilike2burnthing** [comment]
The indexer recently switched to using the cookie login method, so make sure to reconfigure the indexer with a fresh cookie (click the relevant blue spanner button).

If you're still having issues, see the discussion here - https://github.com/Jackett/Jackett/issues/12756

**Comment by timartinelli** [comment]
I'm looking, I couldn't resolve it, I don't really know what to do.
:(

**Comment by timartinelli** [comment]
put this in line PHPSESSID=mycookieidforbj; ipsconnect_63ad9c=1; more_stuff=etc;

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work

**Comment by garfield69** [comment]
this may be relevant to you:
https://github.com/Jackett/Jackett/issues/12756#issuecomment-1007736589

**Comment by raphaelmaria** [comment]
Mine worked in this method until today, but it stopped, I did the analysis following the [guidance](https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work) of this community link, but still, it didn't come back.
Besides that:
-I've already cleared history in ALL DATA mode.
-Already I redid the login in 3 different machines to make sure that the Cookie copy is valid.
Still no chance, copying the entire line that has the model:
cookie: __cfbbid=[Value]; PHPSESSID=[Value]; session=[Value]%3D%3D

The ticket that guided me before #[12756](https://github.com/Jackett/Jackett/issues/12756)

**Comment by ilike2burnthing** [comment]
Tried enabling MFA? - https://github.com/Jackett/Jackett/issues/12756#issuecomment-1007736589

**Comment by raphaelmaria** [comment]
My MFA module is disabled for using it with Jackett in the past, I couldn't have MFA active.

![Screen Shot 2022-01-12 at 16 45 58](https://user-images.githubusercontent.com/26657697/149210917-af6af5bf-e6cf-436c-864a-dcf8a9802572.png)

**Comment by ilike2burnthing** [comment]
Now you can because we've switched to the cookie method.

**Comment by raphaelmaria** [comment]
But I was already using the method via Cookies even without MFA enabled, but now Jackett started to point out the connection error and when I run it again, I end up getting the print message below:

![Screenshot_373](https://user-images.githubusercontent.com/26657697/149219416-31950713-5339-4f83-8475-7eba38784d1e.png)

**Comment by ilike2burnthing** [comment]
> [...] when I run it again [...]

Does 'it' here mean 'with MFA enabled'? If not, try that.

**Comment by VozDeOuro** [comment]
im getting the same error 

what happens is that when we are inactive on the site or we close the browser the site disconnects the account, causing the session cookie to change, so we have to get the cookie every time.
there is a different login option that can be implemented?
If not, is there a way to prevent the cookie from expiring?

**Comment by VozDeOuro** [comment]
if you guys want more information i can provide

**Comment by ilike2burnthing** [comment]
They added a ReCaptcha challenge on their login page, so you can no longer just use credentials.

The advice from https://github.com/Jackett/Jackett/issues/12756#issuecomment-1006055237 was to get the cookie from a browser you don't use.

**Comment by VozDeOuro** [comment]
> They added a ReCaptcha challenge on their login page, so you can no longer just use credentials.
> 
> The advice from [#12756 (comment)](https://github.com/Jackett/Jackett/issues/12756#issuecomment-1006055237) was to get the cookie from a browser you don't use.

my account has MFA enabled and I tried to log in in another browser, as recommended above, but as soon as I close the browser it seems that the account disconnects, because I start getting jackett errors

**Comment by ilike2burnthing** [comment]
Not sure if MFA locks you to one instance of being signed in, so therefore using more than 1 browser causes problems. When you just used 1 browser with MFA enabled, were you at least able to continue using the indexer in Jackett after you closed the browser?
