### ISSUE TITLE
[blutopia] Parsing row error

### ISSUE THREAD

**Issue by key-str0ke** [Jackett/Jackett#12775]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.250-ls54)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
Environment version: 6.0.1 (/app/Jackett/)
Starting Jackett v0.20.250
```

### Description

When testing blutopia, I'm receiving the following error:

System.Exception: Test search in Blutopia => Found no results while trying to browse this tracker

Seem's there is a parsing row error.  

Checked manually the rss feed is working.

### Logged Error Messages

CardigannIndexer (blutopia): Error while parsing row '
<tr>
	<td class="torrent-listings-poster" style="width: 1%;">
		<div class="torrent-poster pull-left"></div>
	</td>
	<td class="torrent-listings-format" style="width: 5%; text-align: center;">
		<div class="text-center">
			<i class="fal fa-film-alt torrent-icon" style=" padding-top: 1px;  font-size: 24px;"></i>
		</div>
		<div class="text-center">
			<span class="label label-success" style="font-size: 13px">
				WEB-DL
			</span>
		</div>
		<div class="text-center" style="padding-top: 5px;">
			<span class="label label-success" style="font-size: 13px">
				720p
			</span>
		</div>
	</td>

**Comment by garfield69** [comment]
yes, it appears the site has changed the html for the torrents page, dropping the categories ids. 
we will need to parse the icon labels by the looks of things.

**Comment by HDVinnie** [comment]
Hello @garfield69,

Please drop support for the scraper implementation of jackett on Blutopia. We have a fully functioning api that replicates the scraper functionality that can be used instead. Allowing the scraper causes unnecessary load as well increased potential for the user's account to be compromised.

Thanks,
Blutopia Staff

PS: This should really go for any UNIT3D tracker running v5.3.0 or newer.

**Comment by garfield69** [comment]
Please switch to using the **Blutopia (API)** indexer instead.

At the request of the unit3d provider we will be dropping support for the HTML scraper version of these indexers where we have an API equivalent available. See #8682
