### ISSUE TITLE
[Aither] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12786]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not applicable
```

### Description

Site is offline

### Logged Error Messages

https://aither.cc/ returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://aither.cc/ returns ERR_CONNECTION_TIMED_OUT

**Comment by mikeoscar2006** [comment]
They had a DNS Migration. There IP Adress also changed. Try flushing DNS Caches.

**Comment by garfield69** [comment]
online
