### ISSUE TITLE
[selezen] Test search in seleZen => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by arashtotti88** [Jackett/Jackett#12787]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-01-08 09:08:58	Info	
Using FlareSolverr: http://192.168.50.173:8191/
2022-01-08 09:08:58	Info	
Using proxy: Disabled
2022-01-08 09:08:58	Info	
App config/log directory: /root/.config/Jackett
2022-01-08 09:08:58	Info	
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-01-08 09:08:58	Info	
Running in Docker: No
2022-01-08 09:08:58	Info	
File /etc/issue: Raspbian GNU/Linux 11 \n \l
2022-01-08 09:08:58	Info	
Jackett variant: CoreLinuxArm32
2022-01-08 09:08:58	Info	
OS version: Unix 5.10.63.7
2022-01-08 09:08:58	Info	
Environment version: 6.0.1 (/home/pi/Downloads/Jackett/)
2022-01-08 09:08:55	Info	
Starting Jackett v0.20.266
```

### Description

i cant use it

### Logged Error Messages

<html>
<body>

System.Exception: Test search in seleZen => Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 310    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 147    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
--

</body>
</html>

### Screenshots

![Screenshot 2022-01-08 153435](https://user-images.githubusercontent.com/45925072/148650221-0db8dfac-f9b2-4fc7-a0ea-a05c64352427.jpg)

**Comment by garfield69** [comment]
Because the seleZen web site does not have a **recent uploads** page, and its torrent search page does not allow an empty search query, The TEST performs a search for the **current year**, which is usually a reliable way to get some torrents to prove the site is online.
However, this early into the new year, seleZen still does not have any torrents with 2022 in the title so the search fails.
Nothing to be done from a Jackett point of view other than wait.
