### ISSUE TITLE
Categories used for Nyaa.si are not working properly

### ISSUE THREAD

**Issue by jacktheripper19** [Jackett/Jackett#12782]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.193-ls54)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.4.0.92 (64bit OS) (64bit process)
Environment version: 6.0.1 (/app/Jackett/)
```

### Description

The categories used by nyaa.si are not the same as in jackett. because of this, queries for some categories give results in the website but not in jackett.  
For example, If a user want to find the raw version of the anime named "demon slayer", in the website, he would specify the category 'Anime - Raw' translated in the queries to the filter 'c=1_4', then execute the query with the keyword "demon slayer" and would find results.  
In the other hand, in jackett, the naming of the categories is different, the closest one is 'Raw animes' with a different category filter 'category=134634', when executing the query, the user won't get any results.

### Logged Error Messages

.

**Comment by ilike2burnthing** [comment]
Search categories can only be set for nyaa.si in the indexer config panel (click the relevant blue spanner button), as the site only allows searching by single categories.

Selecting categories to search by in Jackett's search will just use whatever you have configured for the nyaa.si indexer and then filter the returned results for those matching your selected categories.

At no point is `category=134634` being sent as part of the search URL to nyaa.si.

**Comment by jacktheripper19** [comment]
If that is the solution, then the user should be able to have multiple customized instances of an indexer, for example one instance of nyaa.si with the single category 'Anime - Raw', then add another instance with the single category 'Audio - Lossless' , so that when using the api with sonarr, he would use the first one, and the second one when using lidarr.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/10525
