### ISSUE TITLE
720pier is labeled as a private tracker when it should be labeled as semi-private

### ISSUE THREAD

**Issue by newadventure079** [Jackett/Jackett#12785]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
n/a
```

### Description

720pier is labeled as a private tracker when it should be labeled as semi-private

### Logged Error Messages

n/a

**Comment by garfield69** [comment]
Thanks for the update.

**Comment by garfield69** [comment]
v0.20.266

**Comment by newadventure079** [comment]
@garfield69 It's still listed under the `Supported Private Trackers` of the README.md

**Comment by garfield69** [comment]
oh, forgot to move it in the readme, just did the indexer. Thanks for the reminder.

**Comment by newadventure079** [comment]
Thanks :)
