### ISSUE TITLE
Support HEAD requests

### ISSUE THREAD

**Issue by nicdumz** [Jackett/Jackett#12784]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
This is a docker env (linuxserver image)



2022-01-08 01:03:39	Info	
Using FlareSolverr: No
2022-01-08 01:03:39	Info	
Using proxy: Disabled
2022-01-08 01:03:39	Info	
App config/log directory: /config/Jackett
2022-01-08 00:34:56	Info	
Loading Native indexers ...
2022-01-08 00:34:56	Info	
Using HTTP Client: HttpWebClient2
2022-01-08 00:34:56	Info	
Using FlareSolverr: No
2022-01-08 00:34:56	Info	
Using proxy: Disabled
2022-01-08 00:34:56	Info	
App config/log directory: /config/Jackett
2022-01-08 00:34:56	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-01-08 00:34:56	Info	
Running in Docker: Yes (image build: v0.20.222-ls54)
2022-01-08 00:34:56	Info	
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2022-01-08 00:34:56	Info	
Jackett variant: CoreLinuxAmdx64
2022-01-08 00:34:56	Info	
OS version: Unix 5.15.0.2 (64bit OS) (64bit process)
2022-01-08 00:34:56	Info	
Environment version: 6.0.1 (/app/Jackett/)
2022-01-08 00:34:55	Info	
Starting Jackett v0.20.222
```

### Description

```
$ curl -I http://localhost:9117
HTTP/1.1 301 Moved Permanently
Date: Sat, 08 Jan 2022 00:12:04 GMT
Server: Kestrel
Location: /UI/Dashboard
$ curl -I http://localhost:9117/UI/Dashboard
HTTP/1.1 405 Method Not Allowed
Date: Sat, 08 Jan 2022 00:12:16 GMT
Server: Kestrel
Allow: GET, POST
```

Some projects use `HEAD` as a way to check if a server is available. Could a HEAD request on `/` return a 200 OK when the server is happy? Or is there a way that we want to provide a simple unauthenticated API endpoint on `/api/status` to return a happy response (including to a HEAD request) when the server is up?

I found this using https://github.com/bastienwirtz/homer -- it "pings" servers via a HEAD request to see if they're happy. There's a way to specify an alternate health-check endpoint so an API endpoint would work too.

Thanks a lot.

### Logged Error Messages

N/A

**Comment by ilike2burnthing** [comment]
Feel free to submit a PR with your suggested fix and use the test build to check if it's working.

**Comment by nicdumz** [comment]
Alright, I got to the bottom of this. CORS is completely unrelated, sorry for the confusion.

What actually happens is that @bastienwirtz 's [bastienwirtz/homer](https://github.com/bastienwirtz/homer) actually issues `HEAD` requests when trying to figure out if a host is up or not (and using `Ping` service type).

I've edited the initial report to remove my incorrect assumption / context, and reframed it to request either `HEAD` support on `/` or an health-check API endpoint.

Unfortunately my own attempts to simply sparkle `[HttpHead]` in a few places in code result in:

```
$ curl -I -L http://jackett.host
[...]
HTTP/1.1 302 Found
Access-Control-Allow-Origin: *
Date: Sat, 08 Jan 2022 14:57:08 GMT
Location: http://jackett.host/UI/Login?ReturnUrl=%2FUI%2FDashboard
Server: Kestrel
Vary: Origin

HTTP/1.1 302 Found
Access-Control-Allow-Origin: *
Cache-Control: no-cache,no-store
Content-Length: 1369
Content-Type: text/html
Date: Sat, 08 Jan 2022 14:57:08 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Last-Modified: Sat, 08 Jan 2022 13:36:01 GMT
Location: /UI/Dashboard
Pragma: no-cache
Server: Kestrel
Set-Cookie: Jackett=[redacted]; expires=Sat, 22 Jan 2022 14:57:08 GMT; path=/; samesite=lax; httponly
Vary: Origin

curl: (47) Maximum (50) redirects followed
```

So I do not have a trivial way to add `HEAD` support. (My unfamiliarity with .NET doesn't help)

**Comment by ilike2burnthing** [comment]
@ngosang could you take a look at the feasibility of this if/when you're free?

**Comment by ngosang** [comment]
Added new endpoint:
* GET /health
* HEAD /health

It will be included in the next release (tomorrow).

**Comment by garfield69** [comment]
v0.20.280

**Comment by nicdumz** [comment]
Much appreciated, thank you!

For Homer users something like this config snippet works as of 0.20.280:
```
      - name: jackett
        subtitle: Torrent indexer
        url: http://jackett.local
        endpoint: http://jackett.local/health
        type: Ping
```
