### ISSUE TITLE
[req] [meta] Cardigann YML Schema

### ISSUE THREAD

**Issue by bakerboy448** [Jackett/Jackett#12793]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Currently there is no true standard to validate the Cardigann YML definitions to. These creates minor inconsistencies and opportunity for human error.

### Describe the solution you'd like

Create a YML Schema based on the Cardigann definition to allow eventual automation and validation of definition files

this should include:
- entities and attributes including ensuring only valid and supported attributes are entered 
- Categories against a supported list of categories
- General YML Standards

### Describe alternatives you've considered

None

**Comment by bakerboy448** [comment]
Started a very very rough draft here to build from

https://gist.github.com/bakerboy448/cfce101ef97ff3e0eae4580f5308258b

Generated using a YML and Hackolade

**Comment by bakerboy448** [comment]
https://github.com/Jackett/Jackett/commit/42aba7044aca744ad856e50440a2aeca743af130

**Comment by garfield69** [comment]
docs: https://github.com/Jackett/Jackett/wiki/Definition-format#schema

**Comment by garfield69** [comment]
v0.20.1426
