### ISSUE TITLE
[REQ] nextorrent.net

### ISSUE THREAD

**Issue by XavierTolza** [Jackett/Jackett#1279]
Next torrent is a french open tracker
-------------------------------

https://www.nextorrent.net/torrent

**Comment by ploufs** [comment]
Aussi demandé dans : https://github.com/Jackett/Jackett/issues/1435

**Comment by ploufs** [comment]
https://github.com/Jackett/Jackett/pull/1523

**Comment by garfield69** [comment]
this ticket can be closed since #1523 has been implemented.
