### ISSUE TITLE
cpasbien clone: text search is not working

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#12791]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
latest
```

### Description

Empty search is working.
Text search is not working. Tested with `many` word for example.

### Logged Error Messages

*

**Comment by garfield69** [comment]
@ngosang  please **STOP** reporting you are on the *latest* version.
You know as well as I do that this is useless information when it comes to cross-checking whether or not a user is on the latest indexer or not.

The web site has changed the path when searching for keywords
used to be 
`https://cpasbien.to/search_torrent/boba%20fett?trie-date-d`
now is
`https://cpasbien.to/search_torrent/boba%20fett.html,trie-date-d`

I'll update the indexer.

**Comment by ngosang** [comment]
@garfield69 noted. Don't need to be rude, just ask next time.

**Comment by garfield69** [comment]
>noted. Don't need to be rude, just ask next time.

Sorry about that. Woke up grumpy this morning.
