### ISSUE TITLE
[Secret Cinema] Jackett returns bad title on Search with tracker

### ISSUE THREAD

**Issue by wiloudaki** [Jackett/Jackett#12799]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/piracetam/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: 
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.61.0 (64bit OS) (64bit process)
Environment version: 6.0.1 (/usr/share/jackett/)
```

### Description

n,b,: I have no experience with C# and little with programming in general but will try to be as descriptive and accurate as possible. 

Secret Cinema is implemented as a native tracker at https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/SecretCinema.cs and you can see that it inherits the GazelleTracker class:
https://github.com/Jackett/Jackett/blob/bd13e1256f2d16dece92c6f9e30f274863d0617c/src/Jackett.Common/Indexers/SecretCinema.cs#L15

The issue is that GazelleTracker.cs seems to be implemented for Music trackers rather than movie trackers. 

https://github.com/Jackett/Jackett/blob/bd13e1256f2d16dece92c6f9e30f274863d0617c/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs#L220-L249

I use Jackett with the Torznab API through Radarr. Radarr can't automatically map a movie if the director's name is in the title. However the title includes the 'Artist' prior to anything else. See lines 229-232:

https://github.com/Jackett/Jackett/blob/bd13e1256f2d16dece92c6f9e30f274863d0617c/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs#L229-L232

You see that it follows format of [Artist] - [groupName] [groupYear] [releaseType]. This causes an error where Radarr cannot map the file as it expects [groupName] to be the first thing returned. 

Solution would be to have the Secret Cinema tracker inherit a different class or to modify the GazelleTracker class to not append the artist name prior to groupName. 

### Logged Error Messages

I give the radarr debug log to demonstrate that Radarr can't map the movie, but this isn't an issue on Radarr's side but with the way Jackett returns results. 

[radarr.debug.txt](https://github.com/Jackett/Jackett/files/7836119/radarr.debug.txt)

### Screenshots

Here's an example of a manual search on Jackett:

<a href="https://ibb.co/W3nY33k"><img src="https://i.ibb.co/6ZYfZZH/jandj-tracker-example.png" alt="jandj-tracker-example" border="0" /></a>

**Comment by garfield69** [comment]
Amended the SecretCinema indexer to drop artist from the start of titles, using the same method that the Seals indexer uses (which also is a gazelleTracker engine.)

**Comment by garfield69** [comment]
v0.20.280
