### ISSUE TITLE
[Trackeros] switch to unit3d 5.3.0 api

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12808]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

somehow broke issue #12807
@Nonii07 please repeat that source page capture, but this time save it into a plain text file and post the file here.
dumping the raw capture into the ticket broke github :-)
thanks.

### Logged Error Messages

trackeros have moved from unit3d 4.0.0 to 5.3.0

**Comment by garfield69** [comment]
urg. @Nonii07 may have gotten suspended or something, his profile page is not-found. :-( I hope he can sort it out with github admin.

**Comment by garfield69** [comment]
v0.20.299

**Comment by ilike2burnthing** [comment]
@diegargon / @ngosang can either of you confirm the indexer is working and the categories are correct?
https://github.com/Jackett/Jackett/blob/e19e3e820bcfe751d884674eac4e8aa6b55769e4/src/Jackett.Common/Definitions/trackeros-api.yml#L13-L21

**Comment by garfield69** [comment]
v0.20.314

**Comment by ngosang** [comment]
It's working well.

**Comment by RicardoVelaC** [comment]
[Trackeros] The staff announced that closed permanently the tracker because heath issues.
Closed on 2022-04-19.

**Comment by garfield69** [comment]
v0.20.929
