### ISSUE TITLE
Error when adding T411 indexer

### ISSUE THREAD

**Issue by bOOm-X** [Jackett/Jackett#1280]
I get an error when I try to add T411 indexer.

The answer is below (from the http request):

{"indexer":"t411","name":"T411","config":[{"id":"sitelink","value":"https://t411.ai"},{"id":"apitoken","value":"*****"},{"id":"lasttokenfetchdate","value":"1491418809"},{"id":"username","value":"****"},{"id":"password","value":"****"},{"id":""},{"id":"cookieheader","value":""},{"id":"lasterror","value":"Unexpected character encountered while parsing value: o. Path '', line 0, position 0."}]}
They are no error in the log

Jackett version:  0.7.1287.0
Mono version (if not using Windows): 4.6.2.7 (Synology packet)
-------------------------------

**Comment by JigSawFr** [comment]
Please search before create an issue.
cf. https://github.com/Jackett/Jackett/issues/1276
