### ISSUE TITLE
BTN doesn't seem to search via API

### ISSUE THREAD

**Issue by austinwbest** [Jackett/Jackett#12814]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows 10
Jackett Version v0.20.299
```

### Description

Add BTN to jackett and it tests fine (and yes the IP is allowed to access the API, but that should be known based on the fact that jackett internally does return results)
RSS seems to work fine via Sonarr
Manual search returns nothing, so to check the source....

Do same search inside of jackett and it finds results
Do same search from the torznab link and it no longer works

URL: `http://127.0.0.1:9117/api/v2.0/indexers/broadcasthenet/results/torznab/api?t=tvsearch&cat=5000,5030,5040&extended=1&apikey=<key-here>&offset=0&limit=100&q=PJ%20masks&season=5&ep=18`

This URL returns 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://127.0.0.1:9117/" rel="self" type="application/rss+xml" />
    <title>BroadcasTheNet</title>
    <description>BroadcasTheNet (BTN) is an invite-only torrent tracker focused on TV shows</description>
    <link>https://broadcasthe.net/</link>
    <language>en-US</language>
    <category>search</category>
  </channel>
</rss>
```

### Logged Error Messages

No results i guess is the error message? There isn't one from jackett.

**Comment by austinwbest** [comment]
```
&season=<int>&ep=<int>
``` 

This is your issue... remove that and it gets results for `q=`

**Comment by ilike2burnthing** [comment]
Does that episode exist on BTN? If you search for that episode exactly in browser, does BTN return it?

If yes to both of those, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

Is this the case for all episode searches? If you search by season (so just remove `ep=18`), does that return results?

**Comment by austinwbest** [comment]
> Does that episode exist on BTN? If you search for that episode exactly in browser, does BTN return it?
> 
> If yes to both of those, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
> 
> Is this the case for all episode searches? If you search by season (so just remove `ep=18`), does that return results?

I tried a few episodes and it finds none of them. I guess because they are multi episodes `S05E18E19` however if i remove the episode and search for just season 5 it also returns no results. To answer if they exist, yes.

This becomes quite an issue when sonarr season searches always add the season and episode searches always add the season & episode.

If it is a single season with single episode it works but it simply cant handle multiple episode files and returns nothing. Problematic when a huge majority of kids shows are multiple episode files.

Searching on the site `?searchstr=pj+masks+S05E18&action=basic` and `?searchstr=pj+masks+S05E19&action=basic` returns episodes that are multi part (both of those found the S05E18E19 entries). It would almost have to try a query only search if no results are found or something to resolve it i think

**Comment by ilike2burnthing** [comment]
In the mean time, can you post an enhanced log anyway, it would be interesting to see what is being returned for that search.

**Comment by austinwbest** [comment]
> In the mean time, can you post an enhanced log anyway, it would be interesting to see what is being returned for that search.

Yea bud, i'll get you a log. They have not even responded to the question about it so i dont have a lot of faith they will do much about it.

**Comment by austinwbest** [comment]
> Does that episode exist on BTN? If you search for that episode exactly in browser, does BTN return it?
> 
> If yes to both of those, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
> 
> Is this the case for all episode searches? If you search by season (so just remove `ep=18`), does that return results?

Is there supposed to be a log directory or something in `ProgramData/Jackett/` as there isn't

**Comment by austinwbest** [comment]
> In the mean time, can you post an enhanced log anyway, it would be interesting to see what is being returned for that search.

On the site, searched for `/torrents.php?searchstr=paw+patrol+s08e01&action=basic` and it yields 5 results
In sonarr clicked the search icon next to episode 1 and it gets 0 results, log below

[jackett.txt](https://github.com/Jackett/Jackett/files/7942910/jackett.txt)

**Comment by ilike2burnthing** [comment]
Presumably BTN is doing exact matches. When searching just for the season it will only return matching season packs, not individual episodes from that season, and when searching for episodes it will only match that exact episode. So if searching `S08E01` and there exists a torrent for `S08E01-02` (or `S08E01E02` or whatever they name it), it won't be returned.

We already know single episode results work fine, but to confirm the same for seasons, find a single season pack on BTN (e.g. `Paw Patrol S07`), then perform a search for it in Jackett and then in Sonarr; both should return that result, but Jackett will include individual episodes, whereas Sonarr will only have the season.

I take it they haven't responded to you? If not, or if they're not willing to change how their search functions, we'd have to resort to a 'dumb' search.

**Comment by austinwbest** [comment]
Yea, that is kinda what i said in the OP :) Basically if no results are returned, it would need to do a query search instead.

And no, they have no responded to confirm the issue, deny fixing it, agree to fix it, nothing..

**Comment by ilike2burnthing** [comment]
Download this test build, extract and run the Windows installer, run tests for 'name only', 'name and season', and 'name, season, and episode' in both Jackett and Sonarr, confirm that results are relevant and complete - https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/5262/artifacts?artifactName=drop&api-version=7.0&%24format=zip

**Comment by austinwbest** [comment]
> Download this test build, extract and run the Windows installer, run tests for 'name only', 'name and season', and 'name, season, and episode' in both Jackett and Sonarr, confirm that results are relevant and complete - https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/5262/artifacts?artifactName=drop&api-version=7.0&%24format=zip

Yes, results are showing now and match jackett native and the site for that paw patrol search.

**Comment by garfield69** [comment]
v0.20.466

**Comment by Enissay** [comment]
I am trying to add BTN as indexer, but after pasting the ApiKey and applying, I get: 

```
An error occurred while updating this indexer
Testing returned no results!
[Click here to open an issue on GitHub for this indexer.](https://github.com/Jackett/Jackett/issues/new?template=bug_report.yml&title=[broadcasthenet]%20(updating)%20Testing%20returned%20no%20results!)
```

![image](https://user-images.githubusercontent.com/794673/185746220-5f15a992-7762-4bac-b9ff-82296062b7e5.png)

**Comment by ilike2burnthing** [comment]
Please open a new issue, providing the information requested and an enhanced log of your problem - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
