### ISSUE TITLE
Bypassing the "Link Protector" (DivxTotal, GranTorrent...)

### ISSUE THREAD

**Issue by Lyuu17** [Jackett/Jackett#12820]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
2022-01-12 23:43:08	Info	
Using FlareSolverr: http://flaresolverr:8191
2022-01-12 23:43:08	Info	
Using proxy: Disabled
2022-01-12 23:43:08	Info	
App config/log directory: /config/Jackett
2022-01-12 23:43:08	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-01-12 23:43:08	Info	
Running in Docker: Yes (image build: v0.20.294-ls55)
2022-01-12 23:43:08	Info	
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2022-01-12 23:43:08	Info	
Jackett variant: CoreLinuxAmdx64
2022-01-12 23:43:08	Info	
OS version: Unix 5.14.0.0 (64bit OS) (64bit process)
2022-01-12 23:43:08	Info	
Environment version: 6.0.1 (/app/Jackett/)
2022-01-12 23:43:05	Info	
Starting Jackett v0.20.294
```

### Description

So some torrents sites like DivxTotal and one I'd like to implement has "link protectors" in their download links. They direct to different sites like divxtotal.site, ddtorrent.live with their torrent ID appended(?). Those new pages makes the user to disable adblock, open an ad and wait 30s. 

Once it opens the site it executes and obfuscated JS which looks like [this](https://pastebin.com/raw/BJAn0Epa). It uses Gibberish.AES to decrypt the torrent ID(?) with a common password(??, GranTorrent and DivxTotal have the same one, fee631d2cffda38a78b96ee6d2dfb43a). The torrent URL can be retrieved typing 'DYykkzwP' in the browser console.

I tried to find a way to bypass it but the probably only way is using JavaScript and I dunno if it's gonna be implemented in Jackett somehow or it has it already.

### Logged Error Messages

```text
.
```

### Screenshots

![image](https://user-images.githubusercontent.com/14199521/149407594-47d8fefc-14f8-4347-9117-78aa7cc4987f.png)
![image](https://user-images.githubusercontent.com/14199521/149407702-856f8e83-3dee-49b3-96fd-bb4f0599b0c8.png)
![image](https://user-images.githubusercontent.com/14199521/149407716-656ca100-6f7c-4e83-9a9f-191c97ee9992.png)

**Comment by ilike2burnthing** [comment]
DivxTotal, click the link beneath `Opcion 2`.

GranTorrents, click the long green `DESCARGAR TORRENT` button towards the top.

Ignore the other download buttons.

**Comment by Lyuu17** [comment]
> DivxTotal, click the link beneath `Opcion 2`.
> 
> GranTorrents, click the long green `DESCARGAR TORRENT` button towards the top.
> 
> Ignore the other download buttons.

did you even check it in the website itself before saying bs

**Comment by ilike2burnthing** [comment]
Apologies, got the GranTorrents one mixed up, fixed now.

**Comment by Lyuu17** [comment]
try downloading a torrent from divxtotal in jackett

**Comment by ilike2burnthing** [comment]
Done that too, working fine here.

**Comment by detyso** [comment]
> try downloading a torrent from divxtotal in jackett

use this script to skip those shortlinks 


https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated
