### ISSUE TITLE
RARBG app_id

### ISSUE THREAD

**Issue by wthueb** [Jackett/Jackett#12828]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://localhost:8191/
Using proxy: Disabled
App config/log directory: /var/lib/jackett/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 20.04.3 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.11.0.43 (64bit OS) (64bit process)
Environment version: 6.0.1 (/opt/Jackett/)
Starting Jackett v0.20.314
```

### Description

RARBG has been a constant issue with this project, with just one example being #12800. I'm pretty sure this has to do with the app_id that is being passed to https://torrentapi.org.

As seen here, https://github.com/Jackett/Jackett/blob/861b71034611039bb171cfc32fa39cfe42a8e843/src/Jackett.Common/Indexers/RarBG.cs#L109 everyone (that is on the same Jackett version) is using the same app_id, which is what torrentapi.org uses to generate statistics to rate limit people to 1 request/2 seconds (https://torrentapi.org/apidocs_v2.txt?app_id=jhfguf).

All of the people using RARBG on Jackett are fighting for the same rate limit. I'm pretty sure this is the case through some primitive testing with a little Python script, however it's hard to tell since the docs for torrentapi kinda suck and the issue isn't always present on Jackett.

### Logged Error Messages

```text
none
```

**Comment by ilike2burnthing** [comment]
Maybe switch from Jackett version to Jackett API key?

I didn't think app_id was linked to rate limiting, it was just for monitoring behind the scenes.

**Comment by wthueb** [comment]
Hm, it appears my testing method was inaccurate. Disregard this.
