### ISSUE TITLE
[torrentfunk] keywordless search fails

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12825]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

performing a TEST or doing a keywordless search returns error

searching with keywords works ok

### Logged Error Messages

```text
https://www.torrentfunk.com/all/torrents/.html

Warning: Undefined variable $firstcatid in /home/tf/core/search.php on line 289

Warning: fopen(/home2/tf/data/recent2-.txt): Failed to open stream: No such file or directory in /home/tf/core/search.php on line 290

Warning: filesize(): stat failed for /home2/tf/data/recent2-.txt in /home/tf/core/search.php on line 291

Fatal error: Uncaught TypeError: fread(): Argument #1 ($stream) must be of type resource, bool given in /home/tf/core/search.php:291 Stack trace: #0 /home/tf/core/search.php(291): fread() #1 /home/tf/index.php(47): include('...') #2 {main} thrown in /home/tf/core/search.php on line 291
```

**Comment by ilike2burnthing** [comment]
3afd31ea1c82a984cf9252bef3a2c1ed88f35000
