### ISSUE TITLE
[REQ] Newpct

### ISSUE THREAD

**Issue by surmail** [Jackett/Jackett#1282]
**Indexer Name**
NewPct

**Type**
Public provider
Movies, TV Shows

**URL**
http://www.newpct.com/

**Indexer Language**
Spanish

**Comment by RmG152** [comment]
**Main URL** 
http://www.newpct.com

**Query**
index.php?l=doSearch&q=FILMORSHOWTOSEARCH&category_=CATEGORY&idioma_=1&bus_de_=All

// Games
AddMultiCategoryMapping( TorznabCatType.PCGames, 47);
// Software
AddMultiCategoryMapping( TorznabCatType.PC, 125);
//Tv-HDTV, ERIE-ES-ES-HDTV, SERIE-VOSTES-ES-SD, SERIE-ES-ES-WEB, SERIE-ES-ES-WEB-RIP
AddMultiCategoryMapping(TorznabCatType.TVSD, 767,924);
//Tv-HDTV-720p, SERIE-ES-ES-HDTV-720p, SERIE-ES-ES-DVDrip, SERIE-ES-ES-BDrip, SERIE-ES-ES-MHD, SERIE-ES-ES-BluRay, SERIE-ES-ES-DVD, SERIE-VOSTES-ES-HD, SERIE-ES-ES-WEB-720p, SERIE-ES-ES-WEB-1080p, SERIE-ES-ES-WEB-RIP-720p, SERIE-ES-ES-WEB-RIP-1080p
AddMultiCategoryMapping(TorznabCatType.TVHD,1469);
//DVDRIP, DVDR-PAL, DVDR-NTSC, DVDR-FULL
AddMultiCategoryMapping(TorznabCatType.MoviesDVD,757,1921);
//BDRIP, HD-BLURAY
AddMultiCategoryMapping(TorznabCatType.MoviesBluRay, 1027);
//mHD-720p, mHD-1080p, HDRIP-720p, HDRIP-1080p
AddMultiCategoryMapping(TorznabCatType.MoviesHD, 1027);
//3d
AddMultiCategoryMapping(TorznabCatType.Movies3D, 1599);
//OtherFilms
AddMultiCategoryMapping(TorznabCatType.MoviesOther, 1921,3049,1527);
//DOCUMENTAIRES, DOCUMENTAIRES-HD
AddMultiCategoryMapping(TorznabCatType.TVDocumentary, 780);
//SERIE-VOSTES-ES-PACK, SERIE-ES-ES-PACK, VOSTES-ES, SUBPACK
AddMultiCategoryMapping(TorznabCatType.TV, 775);
//FILM-VOSTES-ES-PACK, FILM-ES-ES-PACK, FILM-ES, SUBPACK
AddMultiCategoryMapping(TorznabCatType.Movies, 778);
//TVSport
AddMultiCategoryMapping(TorznabCatType.TVSport, 822);
//Other
AddMultiCategoryMapping(TorznabCatType.OtherMisc, 827);

@JigSawFr

**Comment by josel2000** [comment]
esto es informacion de unos archivos que hacen que funcionen los RSS de Newpct igual pueden ayudar a realizar el motor de busqueda para  jackett
--------------------------------------------------------------------------------------------------------------------
his is information of some files that make that the RSS of Newpct same can help to realize the search engine for jackett
--------------------------------------------------------------------------------------------------------------------
<?php

/*
    This file is part of SynDsEsTorrent.

    SynDsEsTorrent is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    SynDsEsTorrent is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SynDsEsTorrent.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace modules\newPct1\dlm;

class SynoDLMSearchNewPct1
{
    private $qurl = 'http://www.newpct1.com/index.php?page=buscar&q=%s&categoryIDR=%s&idioma=%s&pg=%u';
    private $purl = 'http://www.newpct1.com/';
    private $query = '';
    private $cat = '';
    private $lang = '';

    public function __construct()
    {
    }

    /**
     *
     * @param curl   $curl  objeto curl
     * @param string $query cadena a buscar
     */
    public function prepare($curl, $query, $category = '', $lang = '')
    {
        $this->query = iconv('UTF-8', 'ISO-8859-1', $query);
        $this->cat = $category;
        $this->lang = $lang;
        curl_setopt($curl, CURLOPT_COOKIE, "language=es_ES");
        curl_setopt($curl, CURLOPT_FAILONERROR, 1);
        curl_setopt($curl, CURLOPT_REFERER, $this->purl);
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($curl, CURLOPT_ENCODING, '');
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_TIMEOUT, 20);
        //curl_setopt($curl, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows; U; Windows NT 5.1;
        //en; rv:1.9.0.4) Gecko/2008102920 AdCentriaIM/1.7 Firefox/3.0.4');
        curl_setopt($curl, CURLOPT_URL, sprintf($this->qurl, rawurlencode($this->query), $this->cat, $this->lang, 1));
    }

    /**
     *
     * @param  plugin $plugin   contendrÃ¡ los resultados ya extraÃ­dos de la pÃ¡gina
     * @param  string $response respuesta html de la pÃ¡gina
     * @return int    nÃºmero de resultados
     */
    public function parse($plugin, $response, $maxPages = 10)
    {
        $regexResultados = '<ul.*class="buscar-list".*>(?<resultados>.*)<\/ul>';
        $regexInfo = '<li.*>.*<div.*class="info">.*<a.*href="(?<enlace_pagina>.'
                . '*)".*.*<h2.*>(?<titulo>.*)<\/h2>.*<\/a>.*<span.*>(?<dia>\d+)'
                . '-(?<mes>\d+)-(?<anyo>\d+)<\/span>.*<span.*>(?<tamanyo>\d+?('
                . '\.\d*?)??) (?<tipo_tamanyo>[KMGT]B).*<\/span>.*<\/div>.*<\/li>';
        $numRes = 0;
        $pagActual = 1;
        do {
            $resultados = $this->regexp($regexResultados, $response);
            if ($resultados === null) {
                break;
            }
            $resultadosInfo = $this->regexp($regexInfo, $resultados['resultados'], true);
            if ($resultadosInfo === null) {
                break;
            }
            $numRes += $this->procesarResultados($plugin, $resultadosInfo);
            $response = $this->obtenerSiguientePagina($response, $pagActual);
            $pagActual++;
        } while ($pagActual <= $maxPages && $response !== null);

        return $numRes;
    }

    private function obtenerSiguientePagina($html, $pagActual)
    {
        $res = $this->regexp('<ul.*class="pagination".*>.*<a href="(?<enlace_pag_sig>[^>]*)">Next<\/a>.*<\/ul>', $html);
        $ret = null;
        if ($res !== null) {
            $pagUrl = sprintf($this->qurl, rawurlencode($this->query), $this->cat, $this->lang, $pagActual + 1);
            $curl = curl_init();
            curl_setopt($curl, CURLOPT_COOKIE, "language=es_ES");
            curl_setopt($curl, CURLOPT_FAILONERROR, 1);
            curl_setopt($curl, CURLOPT_REFERER, $this->purl);
            curl_setopt($curl, CURLOPT_FOLLOWLOCATION, 1);
            curl_setopt($curl, CURLOPT_ENCODING, '');
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($curl, CURLOPT_TIMEOUT, 20);
            //curl_setopt($curl, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en; rv:1.9.0.4) Gecko/20
            //08102920 AdCentriaIM/1.7 Firefox/3.0.4');
            curl_setopt($curl, CURLOPT_URL, $pagUrl);
            $ret = curl_exec($curl);
        }

        return $ret;
    }

    private function procesarResultados($plugin, $resultados)
    {
        $res = 0;
        foreach ($resultados as $resultado) {
            $fecha = "{$resultado['anyo']}-{$resultado['mes']}-{$resultado['dia']}";
            $titulo = str_replace('&nbsp;', ' ', strip_tags(iconv('ISO-8859-1', 'UTF-8', $resultado['titulo'])));
            $hash = md5($titulo);
            $enlacePagina = $resultado['enlace_pagina'];
            $tamano = $this->obtenerTamanyo($resultado['tamanyo'], $resultado['tipo_tamanyo']);
            $plugin->addResult(
                $titulo,
                $enlacePagina,
                $tamano,
                $fecha,
                $enlacePagina,
                $hash,
                -1,
                -1,
                "Sin clasificar"
            );
            $res++;
        }

        return $res;
    }

    private function obtenerTamanyo($tamano, $tipoTamano)
    {
        $tamanoCalculado = $tamano;
        switch ($tipoTamano) {
            case 'KB':
                $tamanoCalculado *= 1024;
                break;
            case 'MB':
                $tamanoCalculado *= 1024 * 1024;
                break;
            case 'GB':
                $tamanoCalculado *= 1024 * 1024 * 1024;
                break;
            case 'TB':
                $tamanoCalculado *= 1024 * 1024 * 1024 * 1024;
                break;
        }

        return $tamanoCalculado;
    }

    private function regexp($regexp, $texto, $global = false)
    {
        $res = array();
        if ($global) {
            if (!preg_match_all("/$regexp/siU", $texto, $res, PREG_SET_ORDER)) {
                $res = null;
            }
        } else {
            if (!preg_match("/$regexp/siU", $texto, $res)) {
                $res = null;
            }
        }

        return $res;
    }
}

**Comment by josel2000** [comment]
`"name": "newPctAuth",
"hostprefix": "newpct.com",
"displayname": "NewPCT",
"version": "1.2.13",
"authentication": "no",
"module": "SynoFileHostingNewPct.php",
"class": "modules\\newPct\\host\\SynoFileHostingNewPct",
"description": "Sitio de Torrents muy popular en EspaÃ±a, anteriormente PcTorrent. Hecho por Luskaner. Modify by eldire. Modify by xucosp" 


/*
    This file is part of SynDsEsTorrent.

    SynDsEsTorrent is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    SynDsEsTorrent is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SynDsEsTorrent.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace modules\newPct\host;

class SynoFileHostingNewPct
{
    private $url;

    /**
     *
     * @param string $Url      URL a descargar (no el fichero directo)
     * @param string $Username Usuario
     * @param string $Password ContraseÃ±a
     * @param array  $HostInfo InformaciÃ³n del host
     * @link http://ukdl.synology.com/download/ds/userguide/Developer_Guide_to_File_Hosting_Module.pdf
     */
    public function __construct($url)
    {
        $this->url = $url;
    }

    /**
     *
     * @return string URL de la descarga
     * @link http://ukdl.synology.com/download/ds/userguide/Developer_Guide_to_File_Hosting_Module.pdf
     * @SuppressWarnings(PHPMD.CamelCaseMethodName)
     */
    public function GetDownloadInfo()
    {
        $result[DOWNLOAD_URL] = '';
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, 1);
        //curl_setopt($curl, CURLOPT_VERBOSE, true);
        curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($curl, CURLOPT_USERAGENT, DOWNLOAD_STATION_USER_AGENT);
        curl_setopt($curl, CURLOPT_HEADER, true);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($curl, CURLOPT_URL, $this->url);

        $result[DOWNLOAD_URL] = $this->getTorrentUrlNewpct($curl);

        return $result;
    }


    private function getTorrentUrlNewpct($curl)
    {
        $result = '';

        $dlPage = curl_exec($curl);
        $matchesUrl = array();
        if (preg_match('/<span.*id=\'content-torrent\'.*>.*<a.*href=\'(.*tumejor.*)\'/siU', $dlPage, $matchesUrl)) {
            $result = $matchesUrl[1];
        }

        return $result;
    }
}`

**Comment by josel2000** [comment]
if anyone knows how to insert the NEWPCT RSS into jackett please publish it

**Comment by Aokromes** [comment]
https://github.com/Jackett/Jackett/commit/ef22d43f463a94b7b1a9ec90f846fe64881ac05a

**Comment by ilike2burnthing** [comment]
https://descargas2020.org/ - Error 522 - Connection timed out
https://pctnew.org/ - working
https://pctreload.com/ - working

**Comment by Aokromes** [comment]
the 1st was working few hours ago, only temp down.

**Comment by ilike2burnthing** [comment]
Oh I know. We mark them when they go down, check regularly, and only if they haven't come back up after 30 days do they actually get removed.

**Comment by Aokromes** [comment]
works again :)

**Comment by ilike2burnthing** [comment]
> https://descargas2020.org/ - Error 522 - Connection timed out
> https://pctnew.org/ - working
> https://pctreload.com/ - working

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://descargas2020.org/ - Error 522 - Connection timed out
> https://pctnew.org/ - working
> https://pctreload.com/ - working

**Comment by garfield69** [comment]
https://pctreload.com/ returning ERR_CONNECTION_REFUSED
https://pctnew.org/ returning ERR_CONNECTION_REFUSED
https://descargas2020.org/ redirecting to https://pctnew.org/

so none of the available sitelinks are working for me.
https://descargas2020.com/ (a previous legacylink) redirects to https://dontorrent.org/ but this domain generates a **Clearance failed after 10 attempt(s)** error for me.

**Comment by ilike2burnthing** [comment]
All 3 current domains are back up now

**Comment by ilike2burnthing** [comment]
https://descargas2020.org/ - se encuentra en mantenimiento !!!! Puede descargar en nuestras otras webs de descarga gratis.
`is in maintenance !!!! You can download it on our other free download websites.`

https://pctnew.org/ - working
https://pctreload.com/ - working

**Comment by ilike2burnthing** [comment]
https://descargas2020.org/ - redirects to https://pctmix.com/
https://pctnew.org/ - working
https://pctreload.com/ - working

**Comment by ilike2burnthing** [comment]
https://descargas2020.org/ - redirects to https://pctmix.com/
https://pctnew.org/ - redirects to https://pctfenix.com/
https://pctreload.com/ - working

**Comment by ilike2burnthing** [comment]
https://descargas2020.org/ultimas-descargas/pg/1 - 404 Not Found
https://pctnew.org/ultimas-descargas/pg/1 - works
https://pctreload.com/ultimas-descargas/pg/1 - works
https://pctmix.com/ultimas-descargas/pg/1 - works

https://pctfenix.com/ultimas-descargas/pg/1 - Los links de descarga directa y ver online no estan disponibles por ahora !!!!
`Direct download links and view online are not available for now !!`

**Comment by garfield69** [comment]
so are you going to move descargas2020.org to the legacylinks?

**Comment by ilike2burnthing** [comment]
I was waiting for the 30 day mark, was assuming it was just down temporarily

**Comment by garfield69** [comment]
the 30 days applies only to the whole indexer getting removed.
for domains that are problematic, where there are plenty of working optional links, feel free to move suspect domains to the legacylinks section so as to get the indexer working asap.

dont forget, with the c# indexer, the descarga2020 link is also coded in a separate link statement near the id and name block, so if you are moving a primary domain to the legacylink section then load the link with the next alternative link.

**Comment by ilike2burnthing** [comment]
Oh, ok. Yea, I'll sort that then.

**Comment by ilike2burnthing** [comment]
All down with Error 522 - Connection timed out
https://pctmix.com/
https://pctfenix.com/
https://pctreload.com/
https://pctnew.org/ultimas-descargas/pg/1

**Comment by ilike2burnthing** [comment]
https://pctreload.com/ultimas-descargas/pg/1 - working
https://pctnew.org/ultimas-descargas/pg/1 - ERR_NAME_NOT_RESOLVED
https://pctmix.com/ultimas-descargas/pg/1 - displays homepage content (Jackett - Found 0 releases!)

**Comment by ilike2burnthing** [comment]
https://pctmix.com/ultimas-descargas/pg/1 - working again

https://pctmix.com/ - working, tested with v0.16.1057

**Comment by ilike2burnthing** [comment]
https://pctreload.com/ - Connection refused
https://pctmix.com/ - Connection refused

**Comment by ilike2burnthing** [comment]
both back up

**Comment by ilike2burnthing** [comment]
https://pctreload.com/ -
```
PctReload se encuentra en mantenimiento !!!!
Puede descargar en nuestras otras webs de descarga gratis.
```
```
PctReload is in maintenance !!!!
You can download it on our other free download websites.
```
https://pctmix.com/ - working

**Comment by ilike2burnthing** [comment]
https://pctmix.com/ - working
https://pctmix.com/ultimas-descargas/pg/1 - working

https://pctreload.com/ - working
https://pctreload.com/ultimas-descargas/pg/1 - blank page, no HTML

**Comment by ilike2burnthing** [comment]
back up

**Comment by diegargon** [comment]
> 
> 
> every legacy link either redirects to https://atomixhq.com/ which no longer has .torrent or magnets, or to https://dontorrent.rip/ #6214
> 
> so we might as well remove this indexer.

Have torrents, they change again how...

Example:
https://atomixhq.com/descargar/torrent/peliculas-x264-mkv/el-viaje-i-onde-dager--2021-/bluray-microhd/
When click open new window with
https://atomtt.com/download/159843_-1634325135-El-viaje--I-onde-dager---2021---BluRay-MicroHD/

Click on "Descarga tu archivo gratis" and works

**Comment by ilike2burnthing** [comment]
Details page:
https://atomixhq.com/descargar/torrent/peliculas-x264-mkv/el-viaje-i-onde-dager--2021-/bluray-microhd/
Download page:
https://atomtt.com/download/159843_-1634325135-El-viaje--I-onde-dager---2021---BluRay-MicroHD/
Torrent link:
https://atomixhq.com/download/159843_-1634325135-El-viaje--I-onde-dager---2021---BluRay-MicroHD.torrent

So from the details page we can take the download page link and replace `atomtt` with `atomixhq` and the final `\` with `.torrent`. How you'd go about that for this indexer I'm not sure.

I'd assume either here (L78):
https://github.com/Jackett/Jackett/blob/e9bc740cb6d4db127db27f41722341e23046863e/src/Jackett.Common/Indexers/NewPCT.cs#L76-L80
or here (after L213):
https://github.com/Jackett/Jackett/blob/e9bc740cb6d4db127db27f41722341e23046863e/src/Jackett.Common/Indexers/NewPCT.cs#L199-L218

**Comment by ilike2burnthing** [comment]
I've spent the last hour staring at it and am no closer, so by all means give it shot, I could be here a while ;P

**Comment by garfield69** [comment]
v0.18.1001
