### ISSUE TITLE
[torrent9.biz] Issue with search

### ISSUE THREAD

**Issue by thebest28** [Jackett/Jackett#1283]
Hello,
I use radarr with jackett  for  french movies on torrent9 but the issue is the title  movie in  torrent9 .
They use the  year of the create  torrent and not the  year of the movie and radarr  search with the  year movie Also jackett  return 0 result..
The  year is good  in  the torrent name but not in  the  title  movie for  the  search :(
Is There a solution for  this issue?
Thanks you

**Comment by adamwinn** [comment]
@thebest28 Please post a sample movie you're searching for

**Comment by thebest28** [comment]
For  exemple  : Fantastic Beasts 
i can  see  in  the  jackett  log : 
	
Found 0 releases from Torrent9 for: les animaux fantastiques 2016 (this is a radarr  search)
Found 3 releases from Sky torrents for: les animaux fantastiques 2016 (this is a radarr  search )

If i search manually in  torrent9 indexer : les animaux fantastiques 2016 ( i have 0 return)
If i search : les animaux fantastiques 2017 or just  les animaux fantastiques ( i have : 
Les Animaux fantastiques FRENCH BluRay 720p 2017
You can  see  at the  adress  : http://www.torrent9.biz/torrent/les-animaux-fantastiques-french-bluray-720p-2017
There  is 2017 to the  title  name and the file name is : Fantastic.Beasts.and.Where.to.Find.Them.2016.FRENCH.720p.BluRay.x264-NLX5.

Thanks you :)

**Comment by adamwinn** [comment]
I see what's going on here.  I don't know how to solve it tho.  Maybe you could write the mods and ask them why they're putting 2017 in the name, when he movie was released in 2016.

**Comment by thebest28** [comment]
Ok i will do it .
Thanks :)

**Comment by kaso17** [comment]
closing this one as it's not a jackett problem

**Comment by Nerwysh** [comment]
Hi, I have the same issue...

`May 05, 2017 03:52:43 PM 	Info 	
Manual search for "Joe 2014" on Torrent9 with 6 results.
May 05, 2017 03:49:48 PM 	Info 	
Found 0 torrentpotato releases from Torrent9 for: Joe 2014`

Manual search works fine with same string : "Joe 2014" 

Any idea ?
