### ISSUE TITLE
[feature request] add warning missing results

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#12853]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
docker container.
Jackett Version v0.20.371
```

### Description

not sure if this is a bug or is considered a feature request. I had a check and couldnt find anything similar open or closed.

i noticed sometimes the results that come back from IPT are missing results compared to using their website.

One search string you will notice this with is "spooks" as you can see from the screenshots attached. the reason for this appears to be due to more results than what is specified in your settings so for example if you you search for something with 500 results and you have specified 255 per page on IPT settings(255 is max) then jackett will only be able to show 255 results and you will be missing 245 results. if you have your settings set to 100 then you will be missing 400 results.

to reduce this occuring as often it should be suggested in jackett to increase torrent per page to the max 255 currently jackett suggests 100 
```
For best results, change the 'Torrents per page' option to 100 and check the 'Torrents - Show files count' option in the website Settings.
``` 

It would be a good idea if this can not be remedied that if there are more results than jackett can handle that it should show a warning on the indexer list with the indexer missing results. see attached screenshot.

### Logged Error Messages

```text
nothing of note even with enhanced logging enabled.

2022-01-18 16:29:05.9466 Info Manual search in iptorrents for spooks => Found 100 releases
```

### Screenshots

![Screenshot 2022-01-18 at 16 21 49](https://user-images.githubusercontent.com/57441681/149979816-2f27cdab-999c-4e58-aa9b-5a1c03f1b9f8.png)
![Screenshot 2022-01-18 at 16 22 07](https://user-images.githubusercontent.com/57441681/149979828-0365e2bb-1190-46e9-af45-04cff641efbd.png)

if this can not be resolve it would be a good idea to add a warning some results are missing
![Screenshot 2022-01-18 at 16 51 56](https://user-images.githubusercontent.com/57441681/149982095-e9cdf99f-5fea-484e-abf6-f9500496c338.png)

**Comment by ilike2burnthing** [comment]
If you want to set the torrents per page for your account to 255 by all means, but apps like Sonarr et al. only use the first 100, hence the recommendation.

I don't really see any need to show `+ missing`. Jackett is not meant to completely replace websites, if you need more than 100 results (or 255 for that matter) per indexer per search term, maybe you need to narrow your search.

As for IPT, I can look at adding a `sort by` setting if that'll help you.

**Comment by swannie-eire** [comment]
I don't actually use sonarr or radarr. 

I agree with narrowing the search but in some cases it's not really possible. For example with spooks I'm looking for a specific tv show and I'm looking for as many episodes as possible hence why filtering by size. In the case with spooks if I try to narrow the filter with let's say "spooks complete" or "spooks s01-s10" I will miss many results as some sites for compete series require the nameing to be "<name> <season> <source> etc.." while others have "<name> COMPLETE <source> etc.." for spooks since it's an relativity old show I was not expecting many results but unfortunately there is a release group called that hence why so many results in this case. I don't really want to have to do multiple searches for each possible naming convention per site hence why my search string was so broad. 

If you could add the sort that would be great.

**Comment by garfield69** [comment]
v0.20.399
