### ISSUE TITLE
[ebookparadijs][film-paleis] Login failed: Selector

### ISSUE THREAD

**Issue by bruvv** [Jackett/Jackett#12858]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
01-19 11:15:08 Info Starting Jackett v0.20.371 
01-19 11:15:10 Info Environment version: 6.0.1 (/app/Jackett/) 
01-19 11:15:10 Info OS version: Unix 5.10.88.0 (64bit OS) (64bit process) 
01-19 11:15:10 Info Jackett variant: CoreLinuxAmdx64 
01-19 11:15:10 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l 
01-19 11:15:10 Info Running in Docker: Yes (image build: v0.20.371-ls55) 
01-19 11:15:10 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
01-19 11:15:10 Info App config/log directory: /config/addons_config/Jackett 
01-19 11:15:10 Info Using proxy: Disabled 
01-19 11:15:10 Info Using FlareSolverr: No 
01-19 11:15:10 Error Jackett is running with root privileges. You should run Jackett as an unprivileged user. 
01-19 11:15:10 Info Using HTTP Client: HttpWebClient2 
01-19 11:15:10 Info Loading Native indexers ...
```

### Description

Ebookparadijs and film-paleis are not working anymore.

### Logged Error Messages

```text
Exception (ebookparadijs): Login failed: Selector "a[href="logout.php"]" didn't match: Parse error
Exception (film-paleis): Login failed: Selector "a[href="logout.php"]" didn't match: Parse error
```

**Comment by ilike2burnthing** [comment]
I don't have an account with Film-Paleis but EbookParadijs is working fine here.

Given that both are cookie logins, try pulling a fresh cookie for both, see if that helps. If not, see these troubleshooting steps - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-selector

**Comment by bruvv** [comment]
It was working fine for the past year and I did pull a fresh cookie. This is not the first time that I had to redo the cookie part. Now I did it again, made sure all the steps are followed but still the same issue.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

As for what Jackett expects after login:
https://github.com/Jackett/Jackett/blob/0cd4eb2b69e3432638fded1ce343106d8b816290/src/Jackett.Common/Definitions/ebookparadijs.yml#L70-L72
https://github.com/Jackett/Jackett/blob/0cd4eb2b69e3432638fded1ce343106d8b816290/src/Jackett.Common/Definitions/film-paleis.yml#L64-L66

**Comment by bruvv** [comment]
Thanks for explaining @ilike2burnthing I just updated to v0.20.399 and now it is working again.
