### ISSUE TITLE
[req]: UHD-HEAVEN.xyz

### ISSUE THREAD

**Issue by RikT** [Jackett/Jackett#12855]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: UHD-HEAVEN
- URL: https://uhd-heaven.xyz
- Description: Movies and TV 1080p/3150p only
- Minimum Seeding Time and Minimum Ratio (if Private): 7 Days Ratio Free
- Additional Comments: Permanant freeleech
```
engine: unit3d 5.3.0

**Comment by garfield69** [comment]
v0.20.399

**Comment by garfield69** [comment]
Nope, mine has gone too. I presume it happemed when they upgraded to unit3d 6.0.0 yesterday

**Comment by ilike2burnthing** [comment]
> You will need to go to discord and apply for an invites, the admin lost all the data when the server crashed .... so only way is by discord

> https://discord.gg/Rq9PhRKv

https://torrentinvites.org/f37/open-uhdheaven-hd-hd-600431/index2.html

**Comment by ilike2burnthing** [comment]
Jackett error:

```text
Exception (uhd-heaven):
Error Parsing Json Response: Status=NotFound Response=Not Found
The requested URL was not found on the server.
If you entered the URL manually please check your spelling and try again.
```

https://uhd-heaven.xyz/login - page is titled `swizzin login`

Entering credentials presents you with a browser login prompt.

This fails with `Could not verify your access level for that URL. You have to login with proper credentials`.

Fail 5 times and you error out with `429 Too Many Requests`.

**Comment by garfield69** [comment]
[v0.20.723](https://github.com/Jackett/Jackett/releases/tag/untagged-47af126ef822c9bee2b0)
