### ISSUE TITLE
[1337x] Test search in 1337x => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by saturday92** [Jackett/Jackett#12859]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Test search in 1337x => Found no results while trying to browse this tracker
```

### Description

We got to add this adress: https://www.1337xx.to/
This one works

### Logged Error Messages

```text
Test search in 1337x => Found no results while trying to browse this tracker
```

**Comment by ilike2burnthing** [comment]
Jackett finds no results because the site is a fake copy, don't use it.

Try the provided alternative site links. If none of them work, see https://github.com/Jackett/Jackett/wiki/TroubleShooting/#a-connection-attempt-failed
