### ISSUE TITLE
SSL Handshake error on all indexers using SSL

### ISSUE THREAD

**Issue by ajslater** [Jackett/Jackett#1285]
http urls work fine but https fails

```
HandleCore(): unhandled exception: Message = An error occurred while sending the request
Data = System.Collections.ListDictionaryInternal
InnerException = System.Net.WebException: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED) ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00054] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 
```

Jackett version:   0.7.1287.0
Mono version (if not using Windows):  Mono JIT compiler version 4.8.0 (Stable 4.8.0.524/9d74414 Thu Apr  6 19:26:41 BST 2017) (via homebrew, macOs 10.12.4)

I think this issue started around Jacket version: v0.7.1176 but am not sure.

**Comment by flightlevel** [comment]
Seems like the certificates haven't been imported when you installed Mono 4.8

From a terminal

run
`cert-sync`

If version is 4.8 then continue

Go to a directory you have write access eg. Downloads

```
brew install wget
wget https://curl.haxx.se/ca/cacert.pem
cert-sync --user ./cacert.pem
```

Don't have a mac to test on, but can't see why this shouldn't work

Otherwise have a read of https://github.com/Jackett/Jackett/issues/1179#issuecomment-289180922 

You can also try running Jackett with
`mono JackettConsole.exe -c libcurl` 

Or via docker

**Comment by ajslater** [comment]
That's it man, Thanks, makes perfect sense. 
I'm a Mono/.Net novice.
```158 new root certificates were added to your trust store.
```

Everybody should just run everything from containers.  No guessing.

**Comment by kaso17** [comment]
@ajslater 
Which commands exactly did you need on macos? I would like to update the readme.

**Comment by ajslater** [comment]
`brew install wget
wget https://curl.haxx.se/ca/cacert.pem
cert-sync --user ./cacert.pem`

(although I already had wget installed, it'll be good for the README)

**Comment by flightlevel** [comment]
I wonder if installing the Mono way http://www.mono-project.com/download/#download-mac would have added the certs automatically and its just something missing via the homebrew method ???

**Comment by ajslater** [comment]
It worked before and then stopped working
 I'll bet homebrew upgraded mono, but something went kind of wrong and I didn't notice it.

**Comment by KillerdogKD** [comment]
Hi,

i have the same problem, i'm running it on Libreelec. have mono 5.0.1 installed and jackett installed with https://github.com/thoradia/thoradia

make the update with mannual copy of new file (0.8.59.0) with ssh access.

i primary have the access bug, doing shift+F5 for refill cache.

but can't connect to yygtorrent and to other indexer (kickasstorrent, nextorrent,t411v2) i have this error.
Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED).

really don't know why and what to do to solve this issus.

**Comment by ajslater** [comment]
i think for me it was a permissions error, which meant that updating jackett didn't get updated certs for some reason.

@flightlevel's solution would work for me, but i'd have to do it every time. eventually i fixed my ownership issue with my jackett install and it went away.

**Comment by KillerdogKD** [comment]
I disable the addons and install it via Docker (https://hub.docker.com/r/linuxserver/jackett/)

It solve my issue.

**Comment by kaso17** [comment]
From the troubleshooting section of the readme:
try running
`wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
