### ISSUE TITLE
restart of service or of the computer new port required.

### ISSUE THREAD

**Issue by edege81** [Jackett/Jackett#1286]
After each restart of service or of the computer, I need to Change the port before all starts to work again
then i need to update couch potato with the new port, so far the only fix for this is to leave the computer running.

Jackett Version 0.7.1287.0
Mono version (if not using Windows):  Stable 4.8.1.0

-------------------------------

**Comment by flightlevel** [comment]
What OS, that shouldn't happen after a restart

If you run `sudo netstat -lpn |grep :9117` where 9117 is port Jackett is running on, it will tell you what is using the port (probably another instance of Jackett)

and you can run
`sudo kill $(sudo lsof -t -i:9117)`
to kill the process that is stopping Jackett from starting so you don't have to change ports

**Comment by edege81** [comment]
even on windows 10 64 bit dose this same thing.

after a restart,

when  couch potato or sonarr trys to index jackett it gives error

Failed opening url in TorrentPotato:
http://localhost:5056/potato/torrentprojectimdbid=tt3228088&search=Spark%3A+A+Space+Tail+2017&user=&passkey=xxx


i can get sonarr error log later. i have it off line atm

but that port is open i can gui to it but as for indexing it it fails. less
I move to a new port.

root@jackett:~# netstat -lpn |grep :5056

cp        0      0 0.0.0.0*:5056*            0.0.0.0:*
LISTEN      6200/mono

root@jackett:~# netstat -lpn |grep :5057

tcp        0      0 0.0.0.0*:5057*            0.0.0.0:*
LISTEN      6200/mono

**Comment by flightlevel** [comment]
Can you confirm the URL its failing on, as the one above will definitely fail `torrentprojectimdbid`
Can you try it from you web browser as well

**Comment by edege81** [comment]
there is the error log on couch potato 
Failed opening url in TorrentPotato: http://localhost:5056/potato/rarbg?imdbid=tt3228088&search=ubuntu&user=&passkey=xxx

Failed opening url in TorrentPotato: http://localhost:5056/potato/thepiratebay?imdbid=tt3228088&search=ubuntu&user=&passkey=xxx

Failed opening url in TorrentPotato: http://localhost:5056/potato/limetorrents?imdbid=tt3228088&search=ubuntu&user=&passkey=xxx

Failed opening url in TorrentPotato: http://localhost:5056/potato/kickasstorrent-kathow?imdbid=tt3228088&search=ubuntu&user=&passkey=xxx

Failed opening url in TorrentPotato: http://localhost:5056/potato/torrentproject?imdbid=tt3228088&search=ubuntu&user=&passkey=xxx

Failed opening url in TorrentPotato: http://localhost:5056/potato/torrentz2?imdbid=tt3228088&search=ubuntu&user=&passkey=xxx

once I move it to a new port it starts to work

04-16 00:23:13 INFO
[hpotato.core.plugins.base] Opening url: get http://localhost:5057/potato/rarbg?imdbid=tt1212428&search=ubuntu&user=&passkey=xxx
04-16 00:23:15 INFO
[hpotato.core.plugins.base] Opening url: get http://localhost:5057/potato/thepiratebay?imdbid=tt1212428&search=ubuntu&user=&passkey=xxx
04-16 00:23:17 INFO
[hpotato.core.plugins.base] Opening url: get http://localhost:5057/potato/limetorrents?imdbid=tt1212428&search=ubuntu&user=&passkey=xxx
04-16 00:23:19 INFO
[hpotato.core.plugins.base] Opening url: get http://localhost:5057/potato/kickasstorrent-kathow?imdbid=tt1212428&search=ubuntu&user=&passkey=xxx
04-16 00:23:21 INFO
[hpotato.core.plugins.base] Opening url: get http://localhost:5057/potato/torrentproject?imdbid=tt1212428&search=ubuntu&user=&passkey=xxx
04-16 00:23:23 INFO
[hpotato.core.plugins.base] Opening url: get http://localhost:5057/potato/torrentz2?imdbid=tt1212428&search=ubuntu&user=&passkey=xxx


works when i call for it on the jackett wegpage

Apr 17, 2017 09:13:07 AM	Info	
Manual search for "ubuntu" on TorrentProject with 50 results.
Apr 17, 2017 09:13:00 AM	Info	
Manual search for "test" on TorrentProject with 50 results.
Apr 17, 2017 09:11:53 AM	Info	
Manual search for "windows" on TorrentProject with 50 results.
Apr 17, 2017 09:11:45 AM	Info	
Manual search for "windows" on KickAssTorrent (kat.how) with 30 results.

![utest](https://cloud.githubusercontent.com/assets/26398530/25093186/4f30ed1a-234e-11e7-9a9e-3ce8189d8d62.png)


I hope this helps flightlevel

**Comment by kaso17** [comment]
Please try a `curl -v http://localhost:5057/potato/...` while it's not working and post the output.
And please also post the jackett log content during the failed requests.

**Comment by edege81** [comment]
root@thebox:~# *   Trying ::1...
* connect to ::1 port 5057 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5057 (#0)
> GET /potato/torrentz2?imdbid=tt2527336 HTTP/1.1
> Host: localhost:5057
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Cache-Control: no-store, private
< Content-Type: application/json; charset=utf-8
< Server: Mono-HTTPAPI/1.0
< Date: Fri, 21 Apr 2017 22:01:28 GMT
< Transfer-Encoding: chunked
< Keep-Alive: timeout=15,max=100
<
* Connection #0 to host localhost left intact
root@thebox:~#
[1]   Done                    curl -v http://localhost:5057/potato/torrentz2?imdbid=tt2527336
[2]-  Done                    search=ubuntu
[3]+  Done                    user=

**Comment by ngosang** [comment]
@edege81 Is this problem still present in the latest version? Can I close?

**Comment by garfield69** [comment]
closing as stale.
