### ISSUE TITLE
API not returning status of indexers

### ISSUE THREAD

**Issue by Frooodle** [Jackett/Jackett#12866]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /opt/jackett/Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No	
File /etc/issue: Raspbian GNU/Linux 10 \n \l
Jackett variant: CoreLinuxArm32	
OS version: Unix 5.10.63.7
Environment version: 6.0.1 (/opt/jackett/)
Starting Jackett v0.20.417
```

### Description

I am trying to get the status of all running indexers yet when i run the below command
http://192.168.1.216:9117/api/v2.0/indexers/all/Results?apikey={key}&query=Indexers
All indexers are returned with status 2, results 0 even though 3 of them are failing tests etc 
example here:
![image](https://user-images.githubusercontent.com/77850077/150636207-15f42100-f66f-4af6-bed3-7f3088880b74.png)

Is this an error or am I using wrong endpoint for this

### Logged Error Messages

```text
{
    "Results": [],
    "Indexers": [
        {
            "ID": "rarbg",
            "Name": "RARBG",
            "Status": 2,
            "Results": 0,
            "Error": null
        },
        {
            "ID": "animetosho",
            "Name": "Anime Tosho",
            "Status": 2,
            "Results": 0,
            "Error": null
        },
        {
            "ID": "tokyotosho",
            "Name": "Tokyo Toshokan",
            "Status": 2,
            "Results": 0,
            "Error": null
        },
        {
            "ID": "dmhy",
            "Name": "dmhy",
            "Status": 2,
            "Results": 0,
            "Error": null
        },
        {
            "ID": "animeclipse",
            "Name": "AnimeClipse",
            "Status": 2,
            "Results": 0,
            "Error": null
        },
        {
            "ID": "bangumi-moe",
            "Name": "Bangumi Moe",
            "Status": 2,
            "Results": 0,
            "Error": null
        },
        {
            "ID": "anisource",
            "Name": "AniSource",
            "Status": 2,
            "Results": 0,
            "Error": null
        },
        {
            "ID": "thepiratebay",
            "Name": "The Pirate Bay",
            "Status": 2,
            "Results": 0,
            "Error": null
        },
        {
            "ID": "nyaasi",
            "Name": "Nyaa.si",
            "Status": 2,
            "Results": 0,
            "Error": null
        },
        {
            "ID": "1337x",
            "Name": "1337x",
            "Status": 2,
            "Results": 0,
            "Error": null
        }
    ]
}
```

**Comment by ilike2burnthing** [comment]
> http://192.168.1.216:9117/api/v2.0/indexers/all/Results?apikey={key}&query=Indexers

The above performs searches all indexers using the keyword `Indexers`. Is that your intention?

> "Results": [],

Did you trim the results? If not, they're missing.

A failure should look like:

```json
{
   "ID": "rarbg",
   "Name": "RARBG",
   "Status": 1,
   "Results": 0,
   "Error": "Jackett.Common.IndexerException: Exception (rarbg): The operation was canceled.\n ---> System.OperationCanceledException: The operation was canceled. [...]"
},
```

**Comment by Frooodle** [comment]
Edited post to provide full API response and also screenshot state of  indexers when query was ran.
I am wanting to get the health of all indexers and this was only command I could see which would return only indexers list and nothing else.

**Comment by ilike2burnthing** [comment]
To be clear, using http://192.168.1.216:9117/api/v2.0/indexers/all/Results?apikey={key)&query=Indexers returns nothing in the `Results` field, just `Indexers`? Is that instantaneous or after a certain amount of time?

Why are you wanting the status of your indexers through the API?

**Comment by Frooodle** [comment]
Yes nothing in results only Indexers but without their status updating as expected. Regardless of wait time

I am wanting to get a count of total indexers working against total indexers 
Something along the lines of 7/10 indexers are working. So that I can monitor those indexers better. (Integrating into a dashboard tool heimdall)

**Comment by ilike2burnthing** [comment]
Something is very wrong then. Does anything appear in Jackett's logs when you use that link? (e.g. searches for 'Indexers' being performed for all indexers)

**Comment by Frooodle** [comment]
![image](https://user-images.githubusercontent.com/77850077/150648645-8a1faa98-3691-46ef-9e49-06321c66b52b.png)

**Comment by ilike2burnthing** [comment]
Try removing `&query=Indexers`, should give you results.

AniSource is down currently down, but it's still returning error text so Jackett just finds no results, thus the test will fail but there's no error.

RARBG is likely being its usual temperamental self and returning 0 results for no reason (you may need to retest it several time to get it to work, and you may need to disable the cache temporarily).

As for Nyaa.si, it's working for me, not sure why it's failing for you, I'd suggest retrying it.

**Comment by Frooodle** [comment]
I understand the reasons why they might fail, I am just trying to found a api endpoint which i can query to get the status of those indexers so was confused why the status is always '2' even when it errors.
I removed the query indexers and now many results along with

"Indexers": [
        {
            "ID": "rarbg",
            "Name": "RARBG",
            "Status": 2,
            "Results": 100,
            "Error": null
        },
        {
            "ID": "animetosho",
            "Name": "Anime Tosho",
            "Status": 2,
            "Results": 75,
            "Error": null
        },
        {
            "ID": "tokyotosho",
            "Name": "Tokyo Toshokan",
            "Status": 2,
            "Results": 75,
            "Error": null
        },
        {
            "ID": "dmhy",
            "Name": "dmhy",
            "Status": 2,
            "Results": 80,
            "Error": null
        },
        {
            "ID": "animeclipse",
            "Name": "AnimeClipse",
            "Status": 2,
            "Results": 100,
            "Error": null
        },
        {
            "ID": "bangumi-moe",
            "Name": "Bangumi Moe",
            "Status": 2,
            "Results": 30,
            "Error": null
        },
        {
            "ID": "anisource",
            "Name": "AniSource",
            "Status": 2,
            "Results": 0,
            "Error": null
        },
        {
            "ID": "thepiratebay",
            "Name": "The Pirate Bay",
            "Status": 2,
            "Results": 50,
            "Error": null
        },
        {
            "ID": "nyaasi",
            "Name": "Nyaa.si",
            "Status": 2,
            "Results": 0,
            "Error": null
        },
        {
            "ID": "1337x",
            "Name": "1337x",
            "Status": 2,
            "Results": 60,
            "Error": null
        }
    ]
    
    
    I guess to get the result I want I can see if the indexer is working based on result != 0 looking at this..

**Comment by Frooodle** [comment]
Only downside is i don't really need to grab all this other torrent result data when i only care about indexer health

**Comment by ilike2burnthing** [comment]
If the indexers are failing the test because they found no results, there is no error to report, thus the status doesn't change. So yes, `result !=0` would work, or `error != null`.

Not sure if the `!status:failing` filter would be of use to you here - https://github.com/Jackett/Jackett#filter-indexers

Ok to close this issue?

**Comment by Frooodle** [comment]
yeah i was unaware that no results counts as error during the test but as a actual error in api so there was some confusion
