### ISSUE TITLE
Exception (xyz): Resource temporarily unavailable: Resource temporarily unavailable (xyz:443) (Test)

### ISSUE THREAD

**Issue by Durantz** [Jackett/Jackett#12879]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
01-23 22:16:28 Info Starting Jackett v0.20.428 
01-23 22:16:30 Info Environment version: 6.0.1 (/app/Jackett/) 
01-23 22:16:30 Info OS version: Unix 5.4.72.7 
01-23 22:16:30 Info Jackett variant: CoreLinuxArm32 
01-23 22:16:30 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l 
01-23 22:16:30 Info Running in Docker: Yes (image build: v0.20.428-ls55) 
01-23 22:16:30 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
01-23 22:16:30 Info App config/log directory: /config/Jackett 
01-23 22:16:30 Info Using proxy: Disabled 
01-23 22:16:30 Info Using FlareSolverr: No 
01-23 22:16:30 Info Using HTTP Client: HttpWebClient2
```

### Description

All the "arr" application give me this error "Resource temporarely unavailable".
I've checked the solution proposed related to Docker DNS but still not working.
I can reach any of the indexer without problem from my PC.
Tried also changing docker container network from bridge to host.
Disabled IPV6 for the interface rasperry is using.

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (xyz): Resource temporarily unavailable: Resource temporarily unavailable (xyz:443)
```

**Comment by garfield69** [comment]
>I can reach any of the indexer without problem from my PC.

Is this the same pc that is running docker?
Did you try accessing the docker image via your terminal and doing a curl and openssl from within the image for any of the addresses that are failing?
```
docker exec -it jackett /bin/bash
and see what you get from the following:
openssl s_client -connect xyz.domain:443
and
curl -vvv https://xyz.domain/
```

**Comment by garfield69** [comment]
similar to #12871

**Comment by Durantz** [comment]
Just to add additional information: I've already tried solution you suggested in the latest post on #12871 (executing container with sysctl net.ipv6.conf.all.disable_ipv6=1) without any success!

**Comment by Durantz** [comment]
> > I can reach any of the indexer without problem from my PC.
> 
> Is this the same pc that is running docker? Did you try accessing the docker image via your terminal and doing a curl and openssl from within the image for any of the addresses that are failing?
> 
> ```
> docker exec -it jackett /bin/bash
> ```
> 
> and see what you get from the following:
> 
> ```
> openssl s_client -connect xyz.domain:443
> ```
> 
> and
> 
> ```
> curl -vvv https://xyz.domain/
> ```

Hi @garfield69 ,
thanks for helping me out. :)

No, docker is running on Raspberry Pi 4 with Raspbian.
Please find below the result of openssl command 
```
openssl s_client -connect https://www.7torrents.cc/
3069685776:error:2008F002:BIO routines:BIO_lookup_ex:system lib:../crypto/bio/b_addr.c:704:Servname not supported for ai_socktype
connect:errno=2
```
and this is from curl
```
curl -vvv  https://www.7torrents.cc/
*   Trying 83.224.65.79...
* TCP_NODELAY set
* connect to 83.224.65.79 port 443 failed: Connection timed out
* Failed to connect to www.7torrents.cc port 443: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to www.7torrents.cc port 443: Connection timed out
 ```

**Comment by garfield69** [comment]
@ilike2burnthing  out of my depth here. Any clues what to do next with rasp pi docker?

**Comment by ilike2burnthing** [comment]
`83.224.65.79` is showing as a Vodafone Italy IP, whereas I'm getting `104.244.76.154`, a Cloudflare IP, for 7torrents. Are you with Vodafone Italy? If so, it would look like the site is being blocked.

**Comment by ilike2burnthing** [comment]
A previous Pi DNS issue resolution - https://github.com/Jackett/Jackett/issues/12595#issuecomment-987306684

**Comment by Durantz** [comment]
Hi @ilike2burnthing ,
checked for dhcpd and it's disabled. I've set my /etc/network/interfaces dns_nameservers as "1.1.1.1" and my /etc/resolv.conf is now showing

```
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 1.1.1.1
nameserver 192.168.1.1
```
but still no luck on reaching those websites.
If it can help you, this link [Pirate Bay](https://piratebayo3klnzokct3wt5yyxb2vpebbuyjl7m623iaxmqhsd52coid.onion.ly/) is not reached by Jackett but I can definetly reach it.

**Comment by garfield69** [comment]
Are you using pihole or some other service that blacklists/whitelists addresses?

**Comment by ilike2burnthing** [comment]
Can you reply to https://github.com/Jackett/Jackett/issues/12879#issuecomment-1019590816 too please?

TPB uses apibay.org to search, the site you select is just for details links.

**Comment by Durantz** [comment]
@garfield69 no, none of these services
@ilike2burnthing yes, I'm a Vodafone consumer. Here is another website [Badass Torrents](https://badasstorrents.com/) that works like a charm from my desktop pc but it gives me "Resource is temporarily unavailable" from Jacket on Raspi.
If I try to curl from Raspi forcing ipv4 it works as well.

**Comment by ilike2burnthing** [comment]
Change the nameserver `192.168.1.1` to `1.0.0.1`. Also try setting `1.1.1.1` and `1.0.0.1` for DNS for the Jacket container.

Failing that, try curling those sites on your Pi, rather than in the Jackett container. Could be a case of the second point here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

**Comment by Durantz** [comment]
> Change the nameserver `192.168.1.1` to `1.0.0.1`. Also try setting `1.1.1.1` and `1.0.0.1` for DNS for the Jacket container.
> 
> ~Failing that, try curling those sites on your Pi, rather than in the Jackett container.~ Missed your last line. If you don't force IPv4 does it fail? If you force IPv6 does it work?
> 
> Could be a case of the second point here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

Hi @ilike2burnthing,
just added ip 1.0.0.1 and removed the 192.168.1.1 from the raspi resolvconf and nothing changed.
I've already setup dns in the /etc/docker/daemon.json with the following values
```
{
  "dns": ["1.1.1.1", "1.0.0.1"]
}
```
Restarted the docker service and tried again testing websites from Jackett with no luck, still Resource temporarily unavailable.

I'm checking the solution you linked. I'll let you know.
Thanks for the help until now :) :)

**Comment by ilike2burnthing** [comment]
That curl is returning a 522 timed out error.

You mentioned if you curl with IPv4 forced on the host, it works. If you don't force IPv4 does it fail? If you force IPv6 does it work?

With your DNS changes, have you also kept IPv6 disabled for the container? If not, try that.

When you try these sites in browser, is your browser using DNS over HTTPS (DoH)? If so, try again with it disabled.

**Comment by Durantz** [comment]
Hi @ilike2burnthing,
sorry for that! Actually didn't check the return. I've tried right now and it is working forcing IPv4 and without forcing it. Meanwhile it fails if I force IPv6.
```
root@e209dbd47bc5:/# curl -g -6 -v https://badasstorrents.com/
*   Trying 2606:4700:3032::ac43:970a...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:3032::ac43:970a: Cannot assign requested address
*   Trying 2606:4700:3031::6815:4084...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:3031::6815:4084: Cannot assign requested address
* Closing connection 0
curl: (7) Couldn't connect to server
```
I've kept IPv6 disabled on the container with the `sysctl net.ipv6.conf.all.disable_ipv6=1`

I'm using DoH on my browser (Microsoft Edge) and the site is reachable. Disabling it is not affecting the navigation: the site is still reachable from Edge.

**Comment by ilike2burnthing** [comment]
And no indexers are working (with a sample size of ~20)?

Can you curl badass from within another container without issue?

Please post your Docker run command or compose file for the Jackett container.

**Comment by Durantz** [comment]
Hi @ilike2burnthing ,
I've tried on 14 indexers (randomly chosen) and none of these are working.
I've tried Curl on an Nginx container and it was working (http 200) either forcing IPv4 or not (IPv6 is still getting issue as I disabled at host level).

Finally, I've used the docker run command from LinuxServer.io on which I've added the sysctl option to disable ipv6. Not created the /download folder mapping as it was optional.
```
docker run -d \
  --name=jackett \
 --sysctl net.ipv6.conf.all.disable_ipv6=1
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Rome\
  -p 9117:9117 \
  -v <path to data>:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/jackett
```

**Comment by ilike2burnthing** [comment]
I very much doubt this makes any difference, but the indentation of your sysctl entry is off by one, and is missing a space and `\` at the end. Similarly the timezone is missing a space between `Rome` and `\`.

I assume you've actually set your volume map, and `<path to data>` is just you censoring it here?

If you haven't updated the container to v0.20.444, does clicking the `Check for updates` button work?

Can you curl google.com?

**Comment by Durantz** [comment]
Hi @ilike2burnthing ,
yes those are typos.
`<path to data>` is actually a volume yes!
I've version 0.20.428, clicked on Check updates and I got this from the logs

```
Error checking for updates.
System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.github.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Services.UpdateService.CheckForUpdates() in /home/vsts/work/1/s/src/Jackett.Common/Services/UpdateService.cs:line 110
```

**Comment by ilike2burnthing** [comment]
I'm at a loss. Other than deleting the container and image, and starting again from scratch, I'm not sure what else to suggest.

**Comment by Durantz** [comment]
Trying to delete everything and recreating from scratch. Thanks for the great support @ilike2burnthing. you are very kind!

Antonio

**Comment by ilike2burnthing** [comment]
@ngosang anything Pi related we might have missed here?

**Comment by Durantz** [comment]
Hi all,
I've done some fixes on my Raspberry Pi 4.
First of all, I've setup DNS using resolvconf (CloudFlare DNS) and passed the same to Docker via docker daemon.json. Checked on container and they were correctly set.
Configured container to use host network.
Changed iptables setting Chain FORWARD as ACCEPT policy.

None of the above solved my issue so I tried installing Jackett as service on my raspi and it is working fine.
The container still have issue connecting to anything. Neither using bridge network nor host.

I don't know if this ca be useful for future troubleshooting.

**Comment by Durantz** [comment]
Hi all,
I found the issue.
For the containers released by Linuxserver.io there are two environment variables that should be passed:
PUID and PGID
I wrongly set those two with my main user instead of docker user. Once set to the correct one the container started to work but I weren't able to make it work on bridge network so switched to host.

Thank you all for the support!
