### ISSUE TITLE
[hdtorrents] The cookies provided by FlareSolverr are not valid (Config)

### ISSUE THREAD

**Issue by ThePieMonster** [Jackett/Jackett#12888]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Client: Chrome v97
OS: Windows Server 2016
Flarsolverr v2.1.0
```

### Description

https://hd-torrents.org/
Looks like the challenge completes but the cookie is bad. 

### Logged Error Messages

```text
2022-01-28T02:07:48+00:00 INFO REQ-3 Cloudflare detected
2022-01-28T02:08:00+00:00 INFO REQ-3 Challenge solved
2022-01-28T02:08:02+00:00 INFO REQ-3 Response in 17.846 s
```

**Comment by ThePieMonster** [comment]
Both Jackett and FlareSolverr are on the same machine. The machine does have NordVPN running at the OS level. I have split tunneling enabled tho so only the download client is going through the vpn. Any further suggestions? @ilike2burnthing 
![image](https://user-images.githubusercontent.com/11359134/151479547-fefc6bc5-d75d-4ae8-ba4c-f7cacdbccfa7.png)
![image](https://user-images.githubusercontent.com/11359134/151480283-14ec0d08-88fb-4dbd-8b99-5b0e8a849559.png)

**Comment by ThePieMonster** [comment]
Disabling NordVPN solves the cookie problem. However, NordVPN needs to be running so a proxy is required to make use of FlareSolverr in my case. Are there any working solutions with a VPN in place?

**Comment by ilike2burnthing** [comment]
If you have Jackett and FlareSolverr both either using or not using the VPN, then it should work fine. The invalid cookies issue should only arise if you have just one using the VPN.
