### ISSUE TITLE
Exception (iptorrents): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured

### ISSUE THREAD

**Issue by SmoothAdmin** [Jackett/Jackett#12897]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows Server 2019
```

### Description

I have following the installation steps outlined on here for installing and accessing FlareSolverr but what I do after that isn't clear and I don't see any other information on Google (reddit/etc). With it running if I run a test on the torrent site I use it come back with the same error. 

### Logged Error Messages

```text
None
```

**Comment by brianbilly1** [comment]
I have the same issue with iptorrents with Jackett running in a docker on Unraid.

**Comment by Bizarre955** [comment]
Same issue suddenly started over night here as well, never had any need for FlareSolverr before so i assume something has changed on iptorrents' side?

**Comment by Bizarre955** [comment]
> Same issue suddenly started over night here as well, never had any need for FlareSolverr before so i assume something has changed on iptorrents' side?

Solved by changing the URL used in Jackett to one of the alternate addresses.

**Comment by brianbilly1** [comment]
I suppose so, I just tried to configure Prowlarr but it doens't seem to connect either, I think iptorrents changed something about the website.

**Comment by brianbilly1** [comment]
> > Same issue suddenly started over night here as well, never had any need for FlareSolverr before so i assume something has changed on iptorrents' side?
> 
> Solved by changing the URL used in Jackett to one of the alternate addresses.

Oh wow, I just configured prowlarr with flaresolverr which works too, but your solution is a hell of a lot quicker

**Comment by SmoothAdmin** [comment]
@Bizarre955 

Where do I get the alternate URL address from?

**Comment by brianbilly1** [comment]
In the end I just kept the same url and added flaresolver to Jackett, saved me from switching over my complete setup. I recommend to use the docker container, it's a very quick install and has the browser built-in

**Comment by brianbilly1** [comment]
> @Bizarre955 
> 
> Where do I get the alternate URL address from?

Alternative Url in iptorrents.me instead of iptorrents.com for example

**Comment by Bizarre955** [comment]
@SmoothAdmin 

![image](https://user-images.githubusercontent.com/25324153/151683883-edffa071-8890-4af0-9478-9d86696f089e.png)

**Comment by garfield69** [comment]
you have two choices while IPTorrents has the cloudflare anti DDoS Challenge active:
- The simplest option is to use your Jackett dashboard to edit the IPTorrents indexer config and select any of the alternate domains available in the config. Try them all one at a time until you find a winner.
- If all fail, the next option is to install the FlareSolverr service from https://github.com/FlareSolverr/FlareSolverr and configure Jackett to use that service to attempt to solve the challenge.
- If that does not work for you then do without IPTorrents for now, they will eventually drop the protection once the threat is deemed over.
