### ISSUE TITLE
Jackett can no longer connect to IPTORRENTS

### ISSUE THREAD

**Issue by nafeasonto** [Jackett/Jackett#12890]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-01-28 20:30:34	Info	
Loading Native indexers ...
2022-01-28 20:30:34	Info	
Using HTTP Client: HttpWebClient2
2022-01-28 20:30:34	Info	
Using FlareSolverr: http://localhost:8191/
2022-01-28 20:30:34	Info	
Using proxy: Disabled
2022-01-28 20:30:34	Info	
App config/log directory: C:\ProgramData\Jackett
2022-01-28 20:30:34	Info	
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-01-28 20:30:34	Info	
Running in Docker: No
2022-01-28 20:30:34	Info	
Jackett variant: CoreWindows
2022-01-28 20:30:34	Info	
OS version: Microsoft Windows NT 10.0.14393.0 (64bit OS)
2022-01-28 20:30:34	Info	
Environment version: 6.0.1 (C:\ProgramData\Jackett\)
2022-01-28 20:30:33	Info	
Starting Jackett v0.20.470
```

### Description

Jackett can no longer contact IPTORRENTS. 

### Logged Error Messages

```text
Your cookie did not work: Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:8191) ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it. at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean
```

### Screenshots

None

**Comment by nafeasonto** [comment]
This just stopped working for me today, I tried re-doing the cookie, and they match. So I don't know what is going on.

**Comment by garfield69** [comment]
it looks like your flaresolverr server is not active.
Ensure you are on the latest flaresolverr version (currently 2.1.0 at the time of this post) or download from https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.1.0
use your browser to test that the flaresolverr server is responding. Read https://github.com/Jackett/Jackett/wiki/Troubleshooting#error-connecting-to-flaresolverr-server

**Comment by nafeasonto** [comment]
It's not responding, and I forgot how to install it, it's been so long.

**Comment by garfield69** [comment]
find the active cli windows and ctrl c to kill it.
then read https://github.com/FlareSolverr/FlareSolverr#precompiled-binaries

**Comment by nafeasonto** [comment]
I see no CMD process running, and when I try to run the EXE, it opens up the CMD line and that shutsdown

**Comment by garfield69** [comment]
start a cmd window and cd to the flaresolverr directory and run the program from there.

**Comment by nafeasonto** [comment]
This is the error I am getting: 2022-01-28T21:11:30-05:00 ERROR TimeoutError: Navigation timeout of 30000 ms exceeded
    at C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\LifecycleWatcher.js:100:111
  -- ASYNC --
    at Frame.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\Page.js:485:53)
    at Page.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:95:27)
    at testWebBrowserInstallation (C:\snapshot\FlareSolverr\dist\services\sessions.js:75:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by yochaigal** [comment]
I installed flaresolver and configured jackett to connect to it at http://127.0.0.1:8191 and the problem was resolved.

**Comment by garfield69** [comment]
\o/

**Comment by nafeasonto** [comment]
> \o/

That wasn't me.  When I run the latest Flaresolvrr that's the error message I get.

**Comment by nafeasonto** [comment]
That was a different guy that said it was solved

**Comment by garfield69** [comment]
sorry, wasn't paying attention.

**Comment by garfield69** [comment]
looks like you found the correct ticket on flaresolverr github, and there is nothing further we can do from the jackett side. I'm closing this one, in favour of https://github.com/FlareSolverr/FlareSolverr/issues/251
