### ISSUE TITLE
[MoreThanTV] Configuration failed: Couldn't find category.

### ISSUE THREAD

**Issue by mtr2014** [Jackett/Jackett#1289]
Jackett version:  0.7.1287.0
Mono version (if not using Windows):  4.8.1

-------------------------------

When I try to setup MoreThanTV in jackett i just get a little pop up box on the bottom saying in red: "Configuration failed: Couldn't find category." 

It shows 2000 for Movies and 5000 for TV as categories. How can I see which are the correct categories and then change them in jackett?

Thank you!

**Comment by mtr2014** [comment]
It upgraded to 0.7.1296.0 but now it just says "Configuration failed"

**Comment by flightlevel** [comment]
Their website is down
`<title>www.morethan.tv | 521: Web server is down</title>`

**Comment by mtr2014** [comment]
Oops, my bad!

Von: flightlevel [mailto:notifications@github.com]
Gesendet: Dienstag, 18. April 2017 10:18
An: Jackett/Jackett <Jackett@noreply.github.com>
Cc: Mario Thiel <mario_thiel@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [Jackett/Jackett] [MoreThanTV] Configuration failed: Couldn't find category. (#1289)


Their website is down
<title>www.morethan.tv<http://www.morethan.tv> | 521: Web server is down</title>
