### ISSUE TITLE
[iptorrents] Your cookie did not work: The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by Alauraa** [Jackett/Jackett#12893]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://IP:8191/
Using proxy: Disabled
App config/log directory: /home/iburn36360/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No	
Jackett variant: CoreLinuxAmdx64	
OS version: Unix 5.10.52.0 (64bit OS) (64bit process)
Environment version: 6.0.1 (/usr/share/jackett/)
Starting Jackett v0.0.0
```

### Description

1. I try to add the indexer IPTorrents as a indexer.
2. I put in my cookie
3. I get a error: 

> An error occurred while updating this indexer
> Your cookie did not work: The cookies provided by FlareSolverr are not valid
> Click here to open an issue on GitHub for this indexer.

### Logged Error Messages

```text
2022-01-28 23:23:49	Error	
System.Exception: Your cookie did not work: The cookies provided by FlareSolverr are not valid
   at Jackett.Common.Indexers.IPTorrents.ApplyConfiguration(JToken configJson)
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext)
2022-01-28 23:23:34	Warn	
Request to IPTorrents failed with exception 'The cookies provided by FlareSolverr are not valid'. Retrying in 1s... (Attempt 2 of 2).
2022-01-28 23:23:17	Warn	
Request to IPTorrents failed with exception 'The cookies provided by FlareSolverr are not valid'. Retrying in 0.5s... (Attempt 1 of 2).
```

**Comment by Alauraa** [comment]
This is a different issue, This is with a configured FlareServerr configured, and still getting 
> System.Exception: Your cookie did not work: The cookies provided by FlareSolverr are not valid

So definitely a different issue.

**Comment by garfield69** [comment]
Are you running the flaresolverr server on the same machine that is running Jackett?
Are you on the 2.1.0 version of flaresolverr?
Did you fetch the cookie using a browser on the same machine as Jackett?
You cannot have used `http://IP:8191/` as the address for flaresolverr... is this a redacted post or an error?
Something left field to try: use the firefox browser to fetch the cookie, its the same browser that flaresolverr uses, it may work.

**Comment by Alauraa** [comment]
> Are you running the flaresolverr server on the same machine that is running Jackett? Are you on the 2.1.0 version of flaresolverr? Did you fetch the cookie using a browser on the same machine as Jackett? You cannot have used `http://IP:8191/` as the address for flaresolverr... is this a redacted post or an error? Something left field to try: use the firefox browser to fetch the cookie, its the same browser that flaresolverr uses, it may work.

1. I am using FlareSolverr on the same machine that is running Jackett.
2. I am using the latest release as of 2 or so hours ago.
3. I fetched the cookie from the IPTorrents site as i've done numerous times in the past.
4. IP is redacted, as i don't or would not like people seeing what i have hosted on the box that hosts FlareSolverr.
5. I will try with the firefox browser, and will report back if it does the same thing.

**Comment by Alauraa** [comment]
> > Are you running the flaresolverr server on the same machine that is running Jackett? Are you on the 2.1.0 version of flaresolverr? Did you fetch the cookie using a browser on the same machine as Jackett? You cannot have used `http://IP:8191/` as the address for flaresolverr... is this a redacted post or an error? Something left field to try: use the firefox browser to fetch the cookie, its the same browser that flaresolverr uses, it may work.
> 
> 1. I am using FlareSolverr on the same machine that is running Jackett.
> 2. I am using the latest release as of 2 or so hours ago.
> 3. I fetched the cookie from the IPTorrents site as i've done numerous times in the past.
> 4. IP is redacted, as i don't or would not like people seeing what i have hosted on the box that hosts FlareSolverr.
> 5. I will try with the firefox browser, and will report back if it does the same thing.

And i have tried Firefox with the cookie, and it does the same exact thing.

**Comment by jaw1994** [comment]
I can also agree, I'm getting the same error on my setup.

`Your cookie did not work: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_UNKNOWN_HOST at https://www.iptorrents.com/t?free=on&o=time`

**Comment by ilike2burnthing** [comment]
@jaw1994 that's a different error. Please open a new issue and provide the requested information.

**Comment by ilike2burnthing** [comment]
@Alauraa question 2 was in relation to what version of FlareSolverr you're using, not Jackett. Is it v2.1.0?

It's strange that the environment details you provided show you starting `Jackett v0.0.0`, which obviously isn't correct. Is there a reason that would be the case for you?

If you use the FlareSolverr API URL (as you have entered it in Jackett) in a web browser on the same device as Jackett and FlareSolverr, what is the response you get?

If they're on the same device though, you should just be able to use `http://127.0.0.1:8191` instead of specifying a local or public IP, so try that.

Are you using a VPN or proxy? If so, try disabling it.

Try disabling IPv6 for the device, restart both Jackett and FlareSolverr, and try again.

**Comment by Alauraa** [comment]
> @Alauraa question 2 was in relation to what version of FlareSolverr you're using, not Jackett. Is it v2.1.0?
> 
> It's strange that the environment details you provided show you starting `Jackett v0.0.0`, which obviously isn't correct. Is there a reason that would be the case for you?
> 
> If you use the FlareSolverr API URL (as you have entered it in Jackett) in a web browser on the same device as Jackett and FlareSolverr, what is the response you get?
> 
> If they're on the same device though, you should just be able to use `http://127.0.0.1:8191` instead of specifying a local or public IP, so try that.
> 
> Are you using a VPN or proxy? If so, try disabling it.
> 
> Try disabling IPv6 for the device, restart both Jackett and FlareSolverr, and try again.

1. Jacket Version: v0.20.477
2. Will try the localhost for FlareSolverr 
3. I am not using a VPN
4. Will look at the guide if you have one for disabling IPV6.

**Comment by ilike2burnthing** [comment]
Again, what is the version of FlareSolverr?

You missed a couple of other questions there.

https://www.techrepublic.com/article/how-to-disable-ipv6-on-linux/

**Comment by Alauraa** [comment]
> Again, what is the version of FlareSolverr?
> 
> You missed a couple of other questions there.
> 
> https://www.techrepublic.com/article/how-to-disable-ipv6-on-linux/

I said latest version as of 4 hours ago now, which would've been V2.1.0

**Comment by machetie** [comment]
Switched to a different domain (https://ipt.findnemo.net)

**Comment by ilike2burnthing** [comment]
We need version numbers, 'latest' is not helpful as we have no idea how the user is defining that.

Let me know about the rest of those answers. If you still get nowhere, see @machetie's suggestion.

**Comment by Alauraa** [comment]
> Are you running the flaresolverr server on the same machine that is running Jackett? Are you on the 2.1.0 version of flaresolverr? Did you fetch the cookie using a browser on the same machine as Jackett? You cannot have used `http://IP:8191/` as the address for flaresolverr... is this a redacted post or an error? Something left field to try: use the firefox browser to fetch the cookie, its the same browser that flaresolverr uses, it may work.

To this one, on the second question. I do not have FlareSolverr nor Jackett on my localhost no. This is on a external seedbox server.


> @Alauraa question 2 was in relation to what version of FlareSolverr you're using, not Jackett. Is it v2.1.0?
> 
> It's strange that the environment details you provided show you starting `Jackett v0.0.0`, which obviously isn't correct. Is there a reason that would be the case for you?
> 
> If you use the FlareSolverr API URL (as you have entered it in Jackett) in a web browser on the same device as Jackett and FlareSolverr, what is the response you get?
> 
> If they're on the same device though, you should just be able to use `http://127.0.0.1:8191` instead of specifying a local or public IP, so try that.
> 
> Are you using a VPN or proxy? If so, try disabling it.
> 
> Try disabling IPv6 for the device, restart both Jackett and FlareSolverr, and try again.


To this one, on the second question. I do not have FlareSolverr nor Jackett on my localhost no. This is on a external seedbox server. The same question is on the Second question about the API URL, as it is on a seedbox and i don't have browser access on that box as its only CLI. 

Tho to the localhost, i have set it, and still get the same error, tho @machetie's suggestion fixed my problem. 

Tho to recap from all the questions. 

1. I am using FlareSolverr on the same machine that is running Jackett.
2. I am using the latest release as of 2 or so hours ago. Which was V2.1.0 at time of using FlareSolverr. Jackett is on Version v0.20.477
3. I fetched the cookie from the IPTorrents site as i've done numerous times in the past.
4. IP is redacted, as i don't or would not like people seeing what i have hosted on the box that hosts FlareSolverr.
5. I will try with the firefox browser, and will report back if it does the same thing.
6. Once i refreshed on the Enviroment URL, it corrected itself to Jackett v0.20.477
7. I'm not using a VPN or Proxy, straight connect to Jackett and FlareSolverr, tho FlareSolver is connecting to localhost as said on the seedbox.
8. To the IPV6, i do not own the box, so i can not disable IPV6, as i am a local user, not root, and do not have sudo access. 
9. Using Localhost does not fix the problem either, tho it could be related to the IPV6 which i do not have any control over as i do not have sudo access to fix that.

I do not see any other questions, if i missed one, please point it out or reply to me with it.

**Comment by ilike2burnthing** [comment]
Are you able to use Docker on your seedbox? If so, you you could attempt to disable IPv6 for both containers - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work-the-ssl-connection-could-not-be-established

Otherwise, if you're happy with your solution then feel free to close this.

**Comment by Alauraa** [comment]
> Are you able to use Docker on your seedbox? If so, you you could attempt to disable IPv6 for both containers - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work-the-ssl-connection-could-not-be-established
> 
> Otherwise, if you're happy with your solution then feel free to close this.

Ill try the docker solution, will get back to you if it works.

**Comment by maleduc** [comment]
> > Are you able to use Docker on your seedbox? If so, you you could attempt to disable IPv6 for both containers - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work-the-ssl-connection-could-not-be-established
> > Otherwise, if you're happy with your solution then feel free to close this.
> 
> Ill try the docker solution, will get back to you if it works. Otherwise will close it. Docker won't work, so the mirror for IPTV should be working.

Did you find the problem ? I have the exact same issue.
