### ISSUE TITLE
[hdme] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12907]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

https://hdme.eu/ is offline

### Logged Error Messages

```text
https://hdme.eu/ returning DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by garfield69** [comment]
v0.20.497

**Comment by garfield69** [comment]
https://hdme.eu/ returns Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://hdme.eu/ returns Error 522 Connection timed out

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/12907#issuecomment-1145606300

**Comment by ilike2burnthing** [comment]
Using browser where I was logged in:

> Warning: mysql_num_rows() expects parameter 1 to be resource, boolean given in /home/hdme/public_html/include/bittorrent.php on line 247

Then refreshed and eventually the site loaded.
Clicked the `Browse` button - Error 524 - A timeout occurred

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/12907#issuecomment-1145606300

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://hdme.eu/ returns Error 522 Connection timed out

**Comment by garfield69** [comment]
v0.20.1406
