### ISSUE TITLE
[req]: AvGv - Chinese XXX Tracker

### ISSUE THREAD

**Issue by angelfire76** [Jackett/Jackett#12903]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: AvGv
- URL: https://avgv.cc/
- Description: Private Chinese XXX Tracker / Invite Only
- Minimum Seeding Time and Minimum Ratio (if Private): MR 0.2, MST N/A.
- Additional Comments: There is no 2FA settings.
(c) AvGv 2019-2022 Powered by NexusPHP.

**Login pages:** https://avgv.cc/login.php | http://avgv.cc/login.php
**Browse Page:** https://avgv.cc/torrents.php
**Search Page:** https://avgv.cc/torrents.php?incldead=1&spstate=0&inclbookmarked=0&search=Jackett&search_area=0&**search_mode=0
**Torrent Page:** https://avgv.cc/details.php?id=XXXX
**Download Link:** https://avgv.cc/download.php?id=XXXX&passkey=XXXX
**RSS Link:** https://avgv.cc/getrss.php

**Generated RSS Links:**
_Use the following URL in your RSS reader, e.g. Google Reader:_
https://AvGv.Cc/torrentrss.php?rows=10

_Use the following URL in BitTorrent clients that support RSS Feed, e.g. uTorrent:_
https://AvGv.Cc/torrentrss.php?rows=10&linktype=dl&passkey=XXXX

Thanks in advance.
```

engine NexusPHP Standard v1.5 Beta 4

**Comment by garfield69** [comment]
Registration is currently closed, invite only. We cannot use the links you provided without an account.
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.

**Comment by angelfire76** [comment]
I don't have any right now. The task can be in the idle for now. I'll add another comment after we have another open sign up.
Thanks for your time.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
If you are unable to provide an invite, then an alternate way to progress this, would be for you to login to the web site, access the torrents page and dump the HTML.
Given that the site is a standard nexus 1.5b4 then I should be able to use the HTML dump to build a standard nx15b4 indexer.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by garfield69** [comment]
returns Error 522 Connection timed out
