### ISSUE TITLE
[iptorrents] Exception (iptorrents): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by johnaston86** [Jackett/Jackett#12908]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
lsio docker image, no changes to standard
```

### Description

Tested existing Jackett IPT Indexer, stopped working 6 hours ago.

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (iptorrents): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured
```

**Comment by garfield69** [comment]
[#12897 (comment)](https://github.com/Jackett/Jackett/issues/12897#issuecomment-1025061929)
