### ISSUE TITLE
Changing settings doesn't work. Value null error is shown.

### ISSUE THREAD

**Issue by bighi** [Jackett/Jackett#1290]
I recently installed Jackett in my Arch Linux PC.

Problem: Changing settings doesn't work. It doesn't matter what I put in the input fields, whenever I try to save settings it shows this message: `Error: Value cannot be null. Parameter name: value`.

(Also nothing else works, but let's fix one thing at a time. If I go back to a 0.5.xxx version, things work)

Jackett Version 0.7.1207.0
Mono JIT compiler version 4.8.0

**Comment by JigSawFr** [comment]
Seems to be duplicate of https://github.com/Jackett/Jackett/issues/1288

**Comment by bighi** [comment]
Not exactly. The message shows up on the web page, not in a debug log. And it's not while trying to use Torznab or any other service.

I am completely unable to save any changes to the settings.

**Comment by kaso17** [comment]
@bighi please make sure to clear your browser cache after the update, that's usually the problem.

**Comment by fryfrog** [comment]
Did you install by hand or w/ the [AUR package](https://aur.archlinux.org/packages/jackett/)?

**Comment by bighi** [comment]
I used the AUR package.

**Comment by kaso17** [comment]
is this still a problem?

**Comment by bighi** [comment]
I gave up on Jackett. But I'll try again in a few hours.

**Comment by flightlevel** [comment]
Re-open if still an issue, no one else seems to be getting this error, so likely re-install and cache clear should fix it
