### ISSUE TITLE
[film-paleis] Change back to cookie usage

### ISSUE THREAD

**Issue by bruvv** [Jackett/Jackett#12912]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Latest version
```

### Description

Why did film-paleis switch to login? Now flaresolver is needed although it was working fine with the cookie method.
For some reason the PR leades to a 3 year old thread: https://github.com/Jackett/Jackett/issues/2651 with 0 explanation.
Same goes for:
- ebookparadijs
- muziekfabriek
- puurhollands

When using cookie method the 'ddos' isn't need because I already logged in and skipped that part at least that is how far my knowledge goes. Would love to see this explained. Thanks

### Logged Error Messages

```text
nbt
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/12902#issuecomment-1025202611
