### ISSUE TITLE
[1337x] Test search in 1337x => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by 0x729000** [Jackett/Jackett#12915]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: unknown)
File /etc/issue: Debian GNU/Linux 10 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.0.10 (64bit OS) (64bit process)
Environment version: 6.0.1 (/opt/Jackett/)
Starting Jackett v0.20.485
```

### Description

Added https://www.1377x.is/ as a tracker, tried all URLS aside this official one to no avail.

### Logged Error Messages

```text
Test search in 1337x => Found no results while trying to browse this tracker
```

**Comment by ilike2burnthing** [comment]
Jackett finds no results because the site is a fake copy, don't use it.

Try the provided alternative site links. If none of them work, see https://github.com/Jackett/Jackett/wiki/TroubleShooting/#a-connection-attempt-failed
