### ISSUE TITLE
[newpct] Cant download any release

### ISSUE THREAD

**Issue by pelagrellas** [Jackett/Jackett#12914]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-02-03 13:07:39	Info	
Using HTTP Client: HttpWebClient2
2022-02-03 13:07:39	Info	
Using FlareSolverr: No
2022-02-03 13:07:39	Info	
Using proxy: Disabled
2022-02-03 13:07:39	Info	
App config/log directory: /config/Jackett
2022-02-03 13:07:39	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-02-03 13:07:39	Info	
Running in Docker: Yes (image build: v0.19.147-ls49)
2022-02-03 13:07:39	Info	
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2022-02-03 13:07:39	Info	
Jackett variant: CoreLinuxAmdx64
2022-02-03 13:07:39	Info	
OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
2022-02-03 13:07:39	Info	
Environment version: 6.0.1 (/app/Jackett/)
2022-02-03 13:07:37	Info	
Starting Jackett v0.20.500
```

### Description

Newpct tracker cant download anythig, yesterday was working but today in not download again

### Logged Error Messages

```text
Error downloading. indexer: newpct path: https://atomixhq.art/descargar/cine-alta-definicion-hd/blade-runner-2049/fulluhd4k/
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 85
```

### Screenshots

<img width="370" alt="image" src="https://user-images.githubusercontent.com/85077900/152340436-38e7723f-4f5d-4c5f-99c9-66ce4ebf3b3e.png">

**Comment by pelagrellas** [comment]
Is not the same issue

**Comment by jorgeface** [comment]
same problem here

**Comment by garfield69** [comment]
Oh what a PITA
seems the site has changed the way they build the download path once again.

**Comment by garfield69** [comment]
@ngosang looks like we now need to do a POST with to.php to build a download link. 
Can you code a solve please?

**Comment by gamingtech-es** [comment]
Same problem 
[log.txt](https://github.com/Jackett/Jackett/files/8002740/log.txt)

**Comment by malomehi** [comment]
This is an example of a link I have been inspecting.

For this link: `https://atomtt.com/t_download/167631/sharkwater--the-requin---2022-/`

The button there has this code on `click` event which generates the download link:
```
var tid = parseInt("167631");

var btn = document.getElementById("btntor");
btn.addEventListener("click", function() 
{
	 
	var link = "https://www.linkonclick.com/jump/next.php?r=5302219";
	window.open(link);
	
	var values = {"t":tid};
	 $.ajax({
	        url: "/to.php",
	        type: "post",
	        data: values ,
	        success: function (response) 
	        {
	        		//console.log('https://atomixhq.art'+_0x3138[0]+response+_0x1f3c[0]);
	        		window.location.href = 'https://atomixhq.art'+_0x3138[0]+response+_0x1f3c[0];
	           // You will get response from your PHP page (what you echo or print)
	        },
	        error: function(jqXHR, textStatus, errorThrown) {
	           console.log(textStatus, errorThrown);
	        }
    });
});
```
I am not an expert on web servers nor php but my understanding is that this makes a POST request to `/to.php` passing the data `{"t": 167631}` for this specific case in the request.
Based on the response the download link is built.
But I also think that `/to.php` is a url that is internal to the server so not something we can directly reach from our machines.
So the only way to run the php code would be to click the button. This might be achievable with selenium or similar (maybe) but even if this was possible it would be very slow and would consume much resources.

I hope there is an easier solution. And please correct me if I am wrong on the above, as I said I am not a web/php guru :)

**Comment by egrueda** [comment]
@malomehi is right.
There's a POST to https://atomtt.com/to.php

These TWO headers are mandaory:
content-type: application/x-www-form-urlencoded; charset=UTF-8
referer: https://atomtt.com

Finally, body RAW sends "t" parameter with the id of the episode:
t=167596

Full CURL request like:
```
curl 'https://atomtt.com/to.php' \
  -H 'authority: atomtt.com' \
  -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'referer: https://atomtt.com/' \
  --data-raw 't=167596' \
```

Response is the name of the torrent file 
167596_-1643984219-Reacher---Temporada-1--HDTV-720p-AC3-5-1

So it makes a request to:
https://atomixhq.art/t_download/{POST_RESPONSE}.torrent
https://atomixhq.art/t_download/167596_-1643984219-Reacher---Temporada-1--HDTV-720p-AC3-5-1.torrent

Hope it helps

**Comment by malomehi** [comment]
A valid user agent is also needed as a header in the request, otherwise the response will return `403 Forbidden`.
User agent from any known browser should work. I use the user agent of my firefox browser and it works.

If using curl it should be something like this: `-H 'User-Agent: <your_user_agent_here>'`

**Comment by garfield69** [comment]
Thank you

**Comment by garfield69** [comment]
v0.20.521

**Comment by garfield69** [comment]
@ngosang  can you check that you can still DL from this indexer?
I'm getting failures, it may be possible that they have changed their site code again!?!?

**Comment by egrueda** [comment]
Same behavior here:
Search string "walker s01e02" brings back 3 results:
 - HDTV -> works
 - HDTV 720p -> works
 - HDTV 1080p -> Failed!

Those are 3 links:
```
https://atomixhq.art/descargar/serie/walker/temporada-1/capitulo-02/
https://atomixhq.art/descargar/serie-en-hd/walker/temporada-1/capitulo-02/
https://atomixhq.art/descargar/serie-1080p/walker/temporada-1/capitulo-02/

```
The last one is not wven working in the website, so maybe problem is from the website itself

And in your sample:
`https://atomixhq.art/descargar/torrent/cine-alta-definicion-hd/4kultrahd/jack-reacher-/4kultrahd/`
Download link is:
`https://atomtt.com/t_download/109279/jack-reacher/`
Torrent link:
`https://atomixhq.art/t_download/109279_-1530470521-jack-reacher--4kultrahd.torrent`

When clicking from the website, it fails too, so might be an error in the website

**Comment by ngosang** [comment]
I think only recent torrents are working. The site is broken if you try to download old movies.

**Comment by garfield69** [comment]
In that case I'm closing this ticket since there is nothing we can do about it from the Jackett side.
