### ISSUE TITLE
[amigosshare] Test search in Amigos Share Club => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by ronilson177** [Jackett/Jackett#12919]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
An error occurred while testing this indexer
Test search in Amigos Share Club => Found no results while trying to browse this tracker
```

### Description

alguem pode me ajudar??

### Logged Error Messages

```text
Ocorreu um erro ao testar este indexador
Testar pesquisa no Amigos Share Club => Não foram encontrados resultados ao tentar navegar neste rastreador
```

### Screenshots

nao

**Comment by ilike2burnthing** [comment]
From the indexer config:
> Set `Exibição De Torrents` to `Lista` in your `Minhas Configurações`.
Using `Capas` is not supported and will return 0 results.

If that isn't the issue, try reconfiguring the indexer (blue spanner button), make sure to manually enter your login credentials, even if they autofill.

You can see some other troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#login-failed-selector

If none of that resolves your issue, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
