### ISSUE TITLE
[req]: TurkTracker.net | New Turkish Private Tracker Request | Category: General

### ISSUE THREAD

**Issue by batuhankrmn** [Jackett/Jackett#12923]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: TurkTracker
- URL: https://turktracker.net
- Login URL: https://turktracker.net/login.php
- Description: TurkTracker is a new general Turkish private tracker
- Minimum Seeding Time and Minimum Ratio (if Private): mst 24hrs mr 1.0
```

engine: TS Special Edition v.8.0

**Comment by batuhankrmn** [comment]
Can I ask why this request of mine closed? @garfield69

**Comment by ilike2burnthing** [comment]
Because it's been added as shown above - https://github.com/Jackett/Jackett/commit/f05228fec472854dd9a7eb71e2344d81fe7fafc1

It will be available in the next release.

**Comment by garfield69** [comment]
v0.20.535

**Comment by garfield69** [comment]
v0.20.567

**Comment by garfield69** [comment]
https://turktracker.net/ returns Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
@batuhankrmn can you confirm that TurkTracker is dead?

**Comment by garfield69** [comment]
v0.20.1908
