### ISSUE TITLE
ETTV is officially gone

### ISSUE THREAD

**Issue by rrrevin** [Jackett/Jackett#12927]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
-
```

### Description

ETTV is officially closed and gone and won't be coming back.
See here : https://torrentfreak.com/piracy-icon-ettv-officially-shuts-down-due-to-a-lack-of-funds-220206/

### Logged Error Messages

```text
-
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/2052#issuecomment-1030887495
