### ISSUE TITLE
Rutracker.org returns "empty" category for UHD animations. 

### ISSUE THREAD

**Issue by vetas** [Jackett/Jackett#12925]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.20.514 running in Docker
```

### Description

Rutracker is returning "empty category for UHD animations. 
However for HD animations or UHD movies, Rutraker returns correct category "Movies/UHD"

### Logged Error Messages

```text
No logs
```

### Screenshots

<img width="1428" alt="Screenshot 2022-02-07 at 02 14 11" src="https://user-images.githubusercontent.com/12799762/152774889-b8d2d8c1-102f-47a5-9730-e69e0eb7d6b5.png">

**Comment by ilike2burnthing** [comment]
Working ok here, and that category has existed for as long as the indexer has. 

Can you perform a keywordless (blank) search with category 101346? Do all results show no category?

**Comment by vetas** [comment]
Hi there! Well, it looks like the issue is with UDH animations that are inside this " Кино, Видео и ТВ » Мультсериалы » Мультсериалы (HD Video)" category on tracker.
I've tried to search inside 101346, but it seams it is missing from the drop down. See screenshot. 
<img width="1373" alt="Screenshot 2022-02-07 at 15 06 24" src="https://user-images.githubusercontent.com/12799762/152794984-dd18fb9a-8f41-48f2-a69e-bb88f0571db2.png">

Also category "Мультсериалы (HD Video)" is missing in YML mapping here https://github.com/Jackett/Jackett/blob/78034f77b60d0f8c65fad7cd51119473f1996e47/src/Jackett.Common/Definitions/rutracker-ru.yml maybe it is related.

**Comment by vetas** [comment]
And as a mentioned before, category "Movies/UHD" works fine for movies in " Кино, Видео и ТВ » HD Video » UHD Video"
<img width="1360" alt="Screenshot 2022-02-07 at 15 08 00" src="https://user-images.githubusercontent.com/12799762/152798790-eca4a733-a1a8-4b86-9b50-4fe4a36e3531.png">

**Comment by ilike2burnthing** [comment]
Just noticed you aren't using rutracker.ru, but rather *.org, which does have at least one missing category.

**Comment by vetas** [comment]
Oh yeah... sorry about that, you are right It's rutracker.org.
I've updated the issue title as well. Thank you.

**Comment by garfield69** [comment]
v0.20.529
