### ISSUE TITLE
[req]: pausing trackers

### ISSUE THREAD

**Issue by jsmdy** [Jackett/Jackett#12926]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

As some trackers have ratio limitations, i'm frustrated to can't pausing tracker for a ratio optimization delay.

### Describe the solution you'd like

it will be perfect to easily pausing/activating trackers with a simple button for each tracker

### Describe alternatives you've considered

I can do it by delete/add trackers manually but the configuration is a pain to do each time. And I can't identify the tracker from sonarr or radarr

**Comment by rrrevin** [comment]
This is probably something for your torrent program, not Jackett. You can try assigning categories to each tracker, and set ratios based on that. Implementation is left as an exercise for the reader.

**Comment by ilike2burnthing** [comment]
Can be achieved with filters and indexer tags - https://github.com/Jackett/Jackett#filter-indexers

Or you can disable them in Sonarr and Radarr if you set up indexers individually.

See also: https://github.com/Jackett/Jackett/issues/661

**Comment by jsmdy** [comment]
for infos, I test prowlarr and there is the simple button I dream on, just an "enable/disable" by tracker. The filters indexers tag is a little bit too much to me as I'm a "simple user", I don't use Sonarr/Radarr because it duplicate files on seedbox. I use jackett directly with qbittorent on seedbox, manual and basic usage ;)
