### ISSUE TITLE
[iptorrents] Exception (iptorrents): Error connecting to FlareSolverr server

### ISSUE THREAD

**Issue by Buster14** [Jackett/Jackett#12931]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://0.0.0.0:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.17763.0 (64bit OS)
Environment version: 6.0.1 (C:\ProgramData\Jackett\)
Starting Jackett v0.20.529
```

### Description

Yesterday it was working fine, today it throws this error. Trie re-adding it manually but it also throws similar flaresolver issue

### Logged Error Messages

```text
Exception (iptorrents): Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'hostName') (0.0.0.0:8191) ---> System.ArgumentException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'hostName') at System.Net.Dns.GetHostEntryOrAddressesCoreAsync(String hostName, Boolean justReturnParsedIp, Boolean throwOnIIPAny, Boolean justAddresses, AddressFamily family, CancellationToken cancellationToken) at System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e, Boolean userSocket, Boolean saeaCancelable) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket) at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, Canc
```

### Screenshots

https://imgur.com/zAH6uwJ

**Comment by ilike2burnthing** [comment]
As it says in the error you can't use `http://0.0.0.0:8191`, change to `http://127.0.0.1:8191` instead.

**Comment by Buster14** [comment]
Okay i changed it to that address at the bottom of the jackett. But when i apply iptorrents it throws this error :

`Exception (iptorrents): Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (127.0.0.1:8191) ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it. at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean asyn`

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#error-connecting-to-flaresolverr-server

**Comment by Buster14** [comment]
Looks like it's not easily installed for windows?
There's a c version but i dont see any build, it means i have to use compiler correct?
How long do i have to wait until this over and cloudflare open its ban btw?

**Comment by garfield69** [comment]
>Looks like it's not easily installed for windows?

I use flaresolverr on my windows 10. It's easy to install.
- download the windows zip file https://github.com/FlareSolverr/FlareSolverr/releases/download/v2.2.1/flaresolverr-v2.2.1-windows-x64.zip
- unpack it to a temp location
- move the folder `flaresolverr` to `%programdata%`
- start a cmd shell
- `cd %programdata%/flaresolverr`
- run the flaresolverr program
- use your browser to confirm the server is active
- test with jackett

you can create a shortcut and drag it to your windows startup folder to auto start the server at boot.

>There's a c version but i dont see any build, it means i have to use compiler correct?

don't bother, not worth the effort

>How long do i have to wait until this over and cloudflare open its ban btw?

how long is a piece of string? The anti-DDoS protection will remain active for however long cloudflare decides the protection against those attack bots is needed. Can be weeks, can be months, may remain permanently. Who knows.

**Comment by Buster14** [comment]
Thanks, but oddly it's still showing same error after this

C:\ProgramData\flaresolverr>flaresolverr.exe
2022-02-09T11:43:29+07:00 INFO FlareSolverr v2.2.1
2022-02-09T11:43:29+07:00 INFO Testing web browser installation...
2022-02-09T11:43:32+07:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
2022-02-09T11:43:32+07:00 INFO Test successful
2022-02-09T11:43:32+07:00 INFO Listening on http://0.0.0.0:8191

Flaresolver it's already set back to http://0.0.0.0:8191 in jacket..
I even restarted jackett service, but i'm still getting same error when testing iptorrent. What else am i missing?

**Comment by garfield69** [comment]
to access flaresolverr use `http://127.0.0.1:8191` as mentioned in a post previously.

**Comment by Buster14** [comment]
Finally works thanks @garfield69 !
Just one more thing, why wont it run as service ?
It says "not responding in timely fashion"
address is already correct

**Comment by garfield69** [comment]
>Just one more thing, why wont it run as service ?

Probably because the author built the program as a executable. Queries of that nature are best directed at the flaresolverr support site https://github.com/FlareSolverr/FlareSolverr
