### ISSUE TITLE
[hdchina] Login Failed, got redirected. Try changing the indexer URL to https://hdchina.org/. (Config)

### ISSUE THREAD

**Issue by AmazingYan-1** [Jackett/Jackett#12934]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
02-09 07:42:27 Info Starting Jackett v0.20.529 
02-09 07:42:28 Info Environment version: 6.0.1 (/home/jack/Jackett/) 
02-09 07:42:28 Info OS version: Unix 5.4.0.26 (64bit OS) (64bit process) 
02-09 07:42:28 Info Jackett variant: CoreLinuxAmdx64 
02-09 07:42:28 Info File /etc/issue: Ubuntu 20.04.2 LTS \n \l 
02-09 07:42:28 Info Running in Docker: No 
02-09 07:42:28 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
02-09 07:42:28 Info App config/log directory: /home/jack/.config/Jackett 
02-09 07:42:28 Info Using proxy: Disabled 
02-09 07:42:28 Info Using FlareSolverr: No 
02-09 07:42:28 Info Using HTTP Client: HttpWebClient2
```

### Description

HDchina is giving this error very often - 

 Login Failed, got redirected. Try changing the indexer URL to http://hdchina.org/. 

If i change the url to http then it's showing this error

 Login Failed, got redirected. Try changing the indexer URL to https://hdchina.org/. 

### Logged Error Messages

```text
Login Failed, got redirected. Try changing the indexer URL to http://hdchina.org/.
```

**Comment by garfield69** [comment]
The site is protected by reCaptcha, so the cookie is likely to expire frequently.
If you change the sitelink from https to http or back again you need to fetch a new cookie too.

**Comment by AmazingYan-1** [comment]
Ah okay, that makes sense @garfield69 i can get a new cookie now but any other permanent solution?

**Comment by garfield69** [comment]
No other permanent solution is possible.
The indexer would normally be configured to use a username/password, which is the ideal set up in normal times.
But when the site enables DDoS protection by enabling reCaptcha, then with the site in this heightened security mode, and Jackett being unable to automatically solve these particular reCaptchas, then we have to resort to using a session cookie. However the session cookies expire at the whim of the site so whenever that happens you need to refresh the Jackett indexer cookie.

**Comment by AmazingYan-1** [comment]
Thanks for the explanation @garfield69 I appreciate it. 

I've updated the session cookie and its working now. You can close this bug report.

Cheers

**Comment by garfield69** [comment]
@AmazingYan-1  is hdchina working for you? 
I'm seeing
```
温馨提示：该网站暂时无法进行访问
原因一：根据工信部相关法规，您尚未进行备案；
原因二：根据工信部相关法规，您当前的接入商不是本司；
原因三：您的网站可能存在不适宜传播的信息，请联系网站管理员。
本页面为默认提示页面，如网站存在以上问题请及时进行处理。
谢谢合作！
```
