### ISSUE TITLE
Red-Bits don't working correctly since you update to API

### ISSUE THREAD

**Issue by Nonii07** [Jackett/Jackett#12933]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not needed
```

### Description

Sice you do the update to API, tracker dont work correctly, the tracker run on 5.2.0 version, and both tracker yml files got incorrect file versions, one of them was 5.1.0 and another one 5.3.0.

Also category's doesn't match with tracker correct one's

since you update thats the problem
![redbits1](https://user-images.githubusercontent.com/97574134/153132409-86e9a930-5e63-4ca6-ad68-9ab43fdbd9ed.JPG)
![redbits2](https://user-images.githubusercontent.com/97574134/153132428-dceed856-2b98-438b-921d-ac8c79c8c2ad.JPG)

[red-bits.source.page.txt](https://github.com/Jackett/Jackett/files/8029999/red-bits.source.page.txt)

### Logged Error Messages

```text
not needed
```

**Comment by garfield69** [comment]
Darn.
I'll revert back to the old indexer in the next release of Jackett. The API only works properly from 5.3.0 onwards.
Determining which version a site is on is difficult on unit3d, with admin able to load and run different modules (front end, torrent search, api, etc) at different versions ;-(

**Comment by Nonii07** [comment]
ok, thank you, btw also tracker got some new categories and on old indexer and new one they dont work correctly, can you do a check please?

**Comment by garfield69** [comment]
yes, I'll incorporate the update cats when I do the reversal.

**Comment by Nonii07** [comment]
thank you alot

**Comment by garfield69** [comment]
the prior indexer using html scraping has these cats  
```
    - {id: 1, cat: Movies, desc: "Películas"}
    - {id: 2, cat: TV, desc: "Series"}
    - {id: 6, cat: TV/Documentary, desc: "Documentales"}
    - {id: 7, cat: TV/Sport, desc: "Deportes"}
    - {id: 8, cat: Movies, desc: "Hagbard"}
    - {id: 9, cat: Movies, desc: "Studio Ghibli"}
```
which appear correct to me?

**Comment by Nonii07** [comment]
thats correct right

**Comment by garfield69** [comment]
v0.20.539

**Comment by garfield69** [comment]
redbits have upgraded to 6.0.0 follow #11540 for progress
