### ISSUE TITLE
Option to disable root privileges warning (for rootless container)

### ISSUE THREAD

**Issue by cryobry** [Jackett/Jackett#12938]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I would like a config setting to disable the "Jackett is running with root privileges. You should run Jackett as an unprivileged user" warning. I run Jackett in a rootless container as UID 0 so it matches my current user outside of the container.

### Describe the solution you'd like

Config setting to disable this warning.

### Describe alternatives you've considered

Change container UID and map to desired user in /etc/subuid.

**Comment by ilike2burnthing** [comment]
Slightly confused here. I've not come across the concept of 'rootless containers' before, but some basic google foo (e.g. https://rootlesscontaine.rs/) makes it seem pretty self-explanatory. However, that leads me to the question, why would you run a rootless container with UID=0 (root)?

**Comment by cryobry** [comment]
The process is run with UID 0 inside of the container which maps to the unprivileged user on the host. If you set a non-root UID in the container then it will be mapped to uid + 1, which is great if you have a proper /etc/subuid (so that the non-privileged user has access to a namespace range) but hurts portability (permissions will break on other systems).

See https://www.redhat.com/sysadmin/rootless-podman-makes-sense for more info.

**Comment by ilike2burnthing** [comment]
So from the container's perspective Jackett is running as root, but any file permissions on the host are actually for a non-root user? Is this like port mapping or volume mapping, but for UID and therefore also permissions?

@garfield69 are you aware of why the root warning was implemented, other than just general security concerns? I would guess because it can create other permissions issues, but https://github.com/Jackett/Jackett/commit/05d57980465265fa42c349df1c5b1acf28000ba0 doesn't give any information, and I can't see any relevant issues from around that time.

**Comment by garfield69** [comment]
>are you aware of why the root warning was implemented, other than just general security concerns?

Nope, at the time I joined I only dealt with yaml. All the  code designs and decisions choices were made by the author of Jackett.
Clearly @kaso17  thought running as root was a significant security risk as indicated by comments on #35 and #2625 and those attached to 05d57980465265fa42c349df1c5b1acf28000ba0

**Comment by ilike2burnthing** [comment]
I'd be open to an environment variable being added for Docker et al. users to supress root user warnings, as making it a UI setting for everyone seems pointless. There would also need to be documentation for it explaining that this is the sole intended use for it, and Jackett should never actually be run as root.

However, this will be reliant on a contributor (you or someone else) implementing it, as we only have one partially active C# dev.

@ngosang can you see any reasons for or against this?

**Comment by ngosang** [comment]
I'm against this for several reasons:
* Jackett should not be run as root under any circumstance. Even if it's running inside a container, a jail or a virtual environment the user can make a mistake mounting the filesystem volume and Jackett will have root access to the files.
* We do not maintain Docker images. The Docker images provided by LinuxServer allow to configure any user / group id even if they don't exist in the host. You can choose any number but root => https://github.com/linuxserver/docker-jackett#docker-compose-recommended-click-here-for-more-info
* I like to keep things simple and this won't be used by many users.

**Comment by cryobry** [comment]
> * Jackett should not be run as root under any circumstance. Even if it's running inside a container, a jail or a virtual environment the user can make a mistake mounting the filesystem volume and Jackett will have root access to the files.

Are we in the business of protecting users? Coming from the Linux world this is a foreign concept to me, but perhaps .NET is rooted in a different philosophy, I'm honestly not familiar with its core concepts. With that said, this is fundamentally a Docker problem (rootful as default), not a container problem.
 
> * We do not maintain Docker images. The Docker images provided by LinuxServer allow to configure any user / group id even if they don't exist in the host. You can choose any number but root => https://github.com/linuxserver/docker-jackett#docker-compose-recommended-click-here-for-more-info

I do not use LinuxServer's images as they are closely tied to the Docker philosophy and do not work well in rootless environments, so I create my own. I believe rootless containers are the path forward and Docker itself is the security vulnerability, not the containers.

> * I like to keep things simple and this won't be used by many users.

That's an OK point if this requires documentation and adds to cognitive load, and if that's the case I will just keep future changes in my own fork. Thanks for reviewing.

**Comment by navels** [comment]
I find this to be a weird stance as well and more so because you can't permanently dismiss the nag.  Wrote a Tampermonkey script if anyone comes here looking for help:
```
(async function() {
    const sleep = (delay) => new Promise((resolve) => setTimeout(resolve, delay));
    let element;
    while (true) {
        const xpathExpression = '//div[contains(string(), "Jackett is running with root privileges")]';
        element = document.evaluate(xpathExpression, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
        if (element) {
            break;
        }
        await sleep(500);
        }
    element.firstElementChild.click();
})();
```

**Comment by depler** [comment]
> * Jackett should not be run as root under any circumstance. Even if it's running inside a container, a jail or a virtual environment the user can make a mistake mounting the filesystem volume and Jackett will have root access to the files.

So your logic is "jackett with windows administrator is ok, but linux root is dangerous"? Root is default and the only one user on many linux environments, especially containers and VPS servers. Creation of another user is just useless additional operation which does nothing, except spending time. Some crazy paranoia of root security. Learn how AdGuard Home (https://github.com/AdguardTeam/AdGuardHome/releases) run service in linux for example.

**Comment by Anutrix** [comment]
> I'm against this for several reasons:
> 
>     * Jackett should not be run as root under any circumstance. Even if it's running inside a container, a jail or a virtual environment the user can make a mistake mounting the filesystem volume and Jackett will have root access to the files.
> 
>     * We do not maintain Docker images. The Docker images provided by LinuxServer allow to configure any user / group id even if they don't exist in the host. You can choose any number but root => https://github.com/linuxserver/docker-jackett#docker-compose-recommended-click-here-for-more-info
> 
>     * I like to keep things simple and this won't be used by many users.

Single root user is a very common scenario in unprivileged LXCs. Maintaining another set of user credentials on an LXC whose only job is to run Jackett is not helpful.

Regardless, if Jackett Team doesn't want to support giving power users control in the way they want, I understand but in that case, **why doesn't the section at https://github.com/Jackett/Jackett#installation-on-linux-amdx64 state that a non-root user needs to be created/present.**
The command in that section of the Readme just gives the command and assumes:
1. Its run by non-root user.
2. Non-root users exists in linux environment by default.
3. sudo is installed by default.

At the least, creating a Debian 13 LXC in Proxmox machine does not create a non-root users. In fact, sudo is not even installed there.

@ilike2burnthing @garfield69 Any thoughts on this matter?

**Comment by garfield69** [comment]
I'm a windows platform user and do not have much experience on linux platforms to formulate an opinion on this subject matter.

**Comment by cryobry** [comment]
> I'm a windows platform user and do not have much experience on linux platforms to formulate an opinion on this subject matter.

This seems to be the fundamental problem with the response to this issue. Since I first opened this the popularity of rootless containers has continued to grow exponentially. The fact that the reviewers were not even aware of the concept at the time was telling, but it's not my project, so I deferred. Jackett is a perfect example of something that _should_ be run in a rootless container so this warning butts up against its intended use IMO. 

In any case, users should be able to run Jackett however they wish without it throwing non-configurable and incorrect warnings, perhaps some users even wish to run it as root natively and control access with a firewall, etc. It's not within the scope of an application to prevent/warn this, and if it does, it should be configurable. Incorrect or misapplied warnings can be just as detrimental as incorrect configuration because they are misleading and train users to ignore them.

**Comment by Anutrix** [comment]
> I'm a windows platform user and do not have much experience on linux platforms to formulate an opinion on this subject matter.

No problem at all. Thx for the response and to you and Jackett team for this amazing software.

-----

For other LXC users coming here after facing same confusion, this is what I did to avoid installing sudo or remembering another set of credentials. Hope it helps.
**IMPORTANT: Please understand and verify what each command does before you run it.**

1. As root user, create a non-root user with disabled password. Change name and home directory if required.
```
adduser --system --shell /bin/bash --gecos 'Jackett' --group --disabled-password --home /home/jackett jackett
```
(Inspired by a command at https://forgejo.org/docs/latest/admin/installation/binary/#install-forgejo-and-git-create-git-user to create git user)

2. Download and extract Jackett (same as official command):
```
cd /opt && f=Jackett.Binaries.LinuxAMDx64.tar.gz && wget -Nc https://github.com/Jackett/Jackett/releases/latest/download/"$f" && tar -xzf "$f" && rm -f "$f" && cd Jackett*
```

3. Change Jackett directory permission to newly created user explicitly(slightly modified from official command):
```
chown jackett:jackett -R "/opt/Jackett"
```

3.optional. **(Warning: May want to skip this)** Inexperienced users may want to skip this step as it is not present in official command. Also, not sure if this breaks anything. It remove all permissions for Jackett directory for other non-root accounts:
```
chmod -R o-rwx "/opt/Jackett"
```
I believe it is more secure but don't take my word for it.

4. Run install script and be done with it(same as official command):
```
./install_service_systemd.sh && systemctl status jackett.service && cd - && echo -e "\nVisit http://127.0.0.1:9117"
```

**Comment by cryobry** [comment]
That approach doesn't address the rootless LXC issue, it just causes UID mismatches, which is pertinent to the bind mounts necessary for storing configs on the host.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/49591b1b25245b163247f82dadbc2d73457e83bc
