### ISSUE TITLE
[MoreThanTV] Test search in MoreThanTV => Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#12935]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Irrelevant
```

### Description

MTV cannot be used in Jackett, and this has been an issue for a while with MTV irrespective of the Environment. MTV's website received a major update last week, I'm not sure if this would help solve the issue.

### Logged Error Messages

```text
`An error occurred while updating this indexer
Test search in MoreThanTV => Found no results while trying to browse this tracker`
```

### Screenshots
Not needed

**Comment by garfield69** [comment]
The indexer is working for me, I can do search and start a DL.
![image](https://user-images.githubusercontent.com/6933240/153270537-aa7fa245-00f8-4fd1-85db-161b5a4a7015.png)

please provide a full enhanced log and maybe we can figure out why it is not working for you.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by RoloSoze** [comment]
Problem solved. It turns out I needed to change my password on MTV even though the website itself was working fine with the old password. Thanks!
