### ISSUE TITLE
[SolidTorrents] Indexer Solid Torrents doesn't work properly; can not find any films

### ISSUE THREAD

**Issue by Th0masDB** [Jackett/Jackett#12943]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.1.247:8191/
Using proxy: Disabled
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: unknown)
File /etc/issue: Debian GNU/Linux 11 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.28.0 (64bit OS) (64bit process)
Environment version: 6.0.2 (/opt/Jackett/)
Starting Jackett v0.20.539
```

### Description

If you try to search for a film using Solid Torrents there are no results. But Solid Torrents do got films.

### Logged Error Messages

```text
Manual search in solidtorrents for joker => Found 0 releases

Manual search in solidtorrents => Found 0 releases
```

**Comment by ilike2burnthing** [comment]
It is not possible to search by multiple categories on this tracker, so Jackett can't search by categories either. Instead, returned results are filtered to only display results matching that category.

Currently, neither a keywordless search nor a search for `joker` returns any results for the category `Movies`, so filtering by it will show no results. You can confirm this for yourself by not selecting any categories, performing a search, and seeing the categories of the the returned results.
