### ISSUE TITLE
“System.IO.Pipes.dll” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by cellulosa** [Jackett/Jackett#12944]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://localhost:8191
Using proxy: Disabled
App config/log directory: /Users/cellulosa/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreMacOs
OS version: Unix 12.2.0 (64bit OS) (64bit process)
Environment version: 6.0.2 (/Applications/Jackett/)
Starting Jackett v0.20.546
```

### Description

The system (MacOS Monterey 12.2) somesimtes opens a window saying: “System.IO.Pipes.dll” cannot be opened because the developer cannot be verified.

### Logged Error Messages

```text
Jackett does not produce any error.
```

**Comment by ilike2burnthing** [comment]
See if solution provided here resolves your issue - https://support.apple.com/HT202491

@garfield69 MacOS isn't really my thing. Anything needed here beyond the solution above?

**Comment by garfield69** [comment]
>MacOS isn't really my thing. Anything needed here beyond the solution above?

Same here. I run a win10 virtualbox image of bigsur for testing Jackett but I don't use the OS regularly, I'm a windows user.
@majorsl @thebluepotato can you assist?

**Comment by majorsl** [comment]
My advice is to always run Jackett (and similar apps that are not .app compiled ones) in Docker on the macOS. Apple is way down the "lock up the macOS" path like they do phones and iPads. I only see it getting "worse". Not that security is a bad thing, but when you make it difficult/impossible for the user to use software they trust, that is where I part ways with them. The instructions in the link above are usually to launch an .app and then exclude it.

Docker on the Mac is really stable. You simply won't run into these security prompts/macOS annoyances when using a container.  If I were the devs, I'd really make that the preferred way to use Jackett on the Mac.

Sorry if that was a little ranty. It's only my opinion.

**Comment by cellulosa** [comment]
> See if solution provided here resolves your issue - https://support.apple.com/HT202491

This did the trick, thanks @ilike2burnthing 

![Screenshot 2022-02-15 at 21 15 06](https://user-images.githubusercontent.com/1758593/154150457-a4d1ad37-352d-4cf7-9a9b-e7ac77be825e.png)
