### ISSUE TITLE
[audiobookbay] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12945]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

all the audiobookbay domains are offline

### Logged Error Messages

```text
http://audiobookbay.fi/ returning ERR_CONNECTION_TIMED_OUT
```

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
http://audiobookbay.fi/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
> http://audiobookbay.fi/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
http://audiobookbay.fi/ - never loads
Other sitelinks working.

**Comment by garfield69** [comment]
*.fi online
