### ISSUE TITLE
[Dontorrent] Cant download torrent file

### ISSUE THREAD

**Issue by pelagrellas** [Jackett/Jackett#12959]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-02-17 16:52:14	Info	Using HTTP Client: HttpWebClient2
2022-02-17 16:52:14	Info	Using FlareSolverr: http://192.168.2.4:8191
2022-02-17 16:52:14	Info	Using proxy: Disabled
2022-02-17 16:52:14	Info	App config/log directory: C:\ProgramData\Jackett
2022-02-17 16:52:14	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-02-17 16:52:14	Info	Running in Docker: No
2022-02-17 16:52:14	Info	Jackett variant: CoreWindows
2022-02-17 16:52:14	Info	OS version: Microsoft Windows NT 10.0.17763.0 (64bit OS)
2022-02-17 16:52:14	Info	Environment version: 6.0.2 (C:\ProgramData\Jackett\)
2022-02-17 16:52:13	Info	Starting Jackett v0.20.574
```

### Description

Indexer find releases but fail when try to download torrent file from a show, some of them work

### Logged Error Messages

```text
Error downloading. indexer: dontorrent path: https://blazing.network/torrents/series/Chicago-PD---Temporada-9--HDTV-720p-AC3-5-1.torrent
System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Jackett.Common.Indexers.DonTorrent.Download(Uri link) in D:\a\1\s\src\Jackett.Common\Indexers\DonTorrent.cs:line 158
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in D:\a\1\s\src\Jackett.Server\Controllers\DownloadController.cs:line 56
```

### Screenshots

![image](https://user-images.githubusercontent.com/85077900/154520546-d469352c-f353-4f23-9b3e-4f6a5af450c6.png)

**Comment by mikeoscar2006** [comment]
Can't reproduce. Is it the same for you on every torrent or just this one?

**Comment by pelagrellas** [comment]
I think that is with all in TV category

This test is recently made it

![image](https://user-images.githubusercontent.com/85077900/154815856-89071a59-6ecd-4c0b-aa98-554e2dbd8f94.png)

![image](https://user-images.githubusercontent.com/85077900/154815859-85cb4ff7-0857-4369-bbfc-f8afc7082fff.png)

**Comment by garfield69** [comment]
v0.20.674

**Comment by luiscajl** [comment]
Hi, the problem come again to another url

```
Error downloading. indexer: dontorrent path: https://container765-deploy-static.cdndelta.com/torrents/series/174529-Ozark---Temporada-4--HDTV-720p-AC3-5-1-cap-11.torrent System.UriFormatException: Invalid URI: The URI is empty.    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)    at System.Uri..ctor(String uriString)    at Jackett.Common.Indexers.DonTorrent.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/DonTorrent.cs:line 184    at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 56
```

this cdndelta.com is not registered on the code https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/DonTorrent.cs line 163, can anyone add it? i don´t have windows to test it, sorry

**Comment by garfield69** [comment]
v0.20.1575

**Comment by maricard5** [comment]
![image](https://user-images.githubusercontent.com/99802441/203790274-05d1b5d3-6ea3-41f5-abd7-848fa4358b7f.png)

Not work, it fail with Show, only works in movies

Server: Dontorrent

**Comment by garfield69** [comment]
for the primary domain https://dontorrent.click/ the download for audio/movie/tv are all ok.
for the alternate domains, https://todotorrents.net/ , https://tomadivx.net/ , https://seriesblanco.one/ , https://verdetorrent.com/  and https://naranjatorrent.com/ , downloading Audio/Movie are ok. 
But TV fails.

**Comment by garfield69** [comment]
v0.20.2288

**Comment by alexx-ftw** [comment]
Happening for me on v0.21.2335

**Comment by ilike2burnthing** [comment]
Please give a specific example of a torrent this is affecting.

**Comment by PoKeRGT** [comment]
<html>
<body>

Error downloading. indexer: dontorrent path: https://dontorrent.directory/torrents/series/aida-10-17.torrent System.UriFormatException: Invalid URI: The URI is empty.    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)    at System.Uri..ctor(String uriString)    at Jackett.Common.Indexers.DonTorrent.Download(Uri link) in ./Jackett.Common/Indexers/DonTorrent.cs:line 183    at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 99
--



</body>
</html>

**Comment by alexx-ftw** [comment]
> Please give a specific example of a torrent this is affecting.

Any torrent at all from that site is bugged. You can use anything at all

**Comment by ilike2burnthing** [comment]
Looks like the issue is limited to TV torrents, whereas movies and audio work fine.

From enhanced logs, the torrent file is downloaded using the correct URL, and it is the same size as I can download in browser, but Jackett errors out as shown above.

**Comment by garfield69** [comment]
downloading tv needs extra parsing because the details page is not just a single download link in a div block like audio and movies, but is a table with one or more hrefs, one href for each seasons episodes.
we cant just pick the first href because this would only yield the first season episode for every tv search.
so the code that builds the download link needs to include the episode number in the href so that the download block can spot which href needs to be used.
I'll see if I can come up with something, its a rainy indoor day and I've time on my hands.

**Comment by alexx-ftw** [comment]
@garfield69 man you are incredible . thank you SO much for fixing it so fast. How can i get the fix without building by myself?

**Comment by ilike2burnthing** [comment]
https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/11387/artifacts?artifactName=drop&api-version=7.1&%24format=zip

Or wait ~5hrs.

If you're using Docker, then just wait.

**Comment by garfield69** [comment]
v0.21.2354
