### ISSUE TITLE
[req]: Top Indexers?

### ISSUE THREAD

**Issue by rrrevin** [Jackett/Jackett#12957]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Would be great if there was a way to see which Indexers everyone is using/configured for use. This would also help the devs focus on Indexers that are heavily used, and perhaps drop support for those that no one uses. Perhaps a one page summary on this site on "top configured indexers by count"? All meta-data would be removed?

This would probably be an opt-in thing?

**Comment by ilike2burnthing** [comment]
No, we're not collecting telemetry on users for obvious reasons.
