### ISSUE TITLE
1337x has a new adress

### ISSUE THREAD

**Issue by saturday92** [Jackett/Jackett#12951]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
I'm using chrome and Brave.
```

### Description

1337x has added new domains and they are working:
https://www.1337xx.to/
and 
https://www.1337xxx.to/
and the newest alternative is:
https://www.1337x.tw/

So please can you add them? Thanks a lot

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in 1337x => Found no results while trying to browse this tracker
Click here to open an issue on GitHub for this indexer.
```

### Screenshots

![2022-02-14_00h31_20](https://user-images.githubusercontent.com/25355466/153780497-1d279101-45c5-40aa-9bf6-f79350985a82.jpg)

**Comment by garfield69** [comment]
the following are the only official domains for 1337x
![image](https://user-images.githubusercontent.com/6933240/153780874-e28014e5-6166-46c1-8084-e3c87bde1738.png)

any other domains belong to copycats and clones that are not supported by the official site.
Use at your own risk. 
We will not add those domains to the Jackett 1337x indexer.
