### ISSUE TITLE
RARBG finds results on their site but RARBG indexer doesn't find the results because of case sensitivity.

### ISSUE THREAD

**Issue by batuhankrmn** [Jackett/Jackett#12956]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.20.567
Windows 10 Pro x64
No FlareSolverr, no Proxy
```

### Description

I can find results for the same phrase on RARBG site but the results doesn't come out when I search via Jackett's RARBG indexer. 

To reproduce this bug: search How I Met Your Father S01E06 with Jackett's RARBG indexer. There will be no search result. Do the same search with RARBG site itself, you will get the correct results for that episode. 

So this is also valid for most of the search on RARBG indexer. My theory is RARBG indexer doesn't like some uppercase/lowercase letters and misses the results but you never miss the results with RARBG site search even If you search it with uppercase or lowercase, doesn't matter. I'll leave screenshots to clarify this situation.

### Logged Error Messages

```text
There is no error messages, it's just Jackett doesn't provide correct search results while they're available.
```

### Jackett

![image](https://user-images.githubusercontent.com/57859656/154132429-36d4e601-4764-4055-b029-59f2ae652dfc.png)

![image](https://user-images.githubusercontent.com/57859656/154132520-1d78e633-fa92-493f-8d72-5779081a2a04.png)

![image](https://user-images.githubusercontent.com/57859656/154132604-d3c1ac77-6483-4d32-bded-135c632fcde1.png)
**(See, Jackett only gave me the right results when I search by typing all letters in lower case)** 

### RARBG site

![image](https://user-images.githubusercontent.com/57859656/154133170-10580125-0be9-44b0-83d0-50855c187151.png)

![image](https://user-images.githubusercontent.com/57859656/154133384-6371237d-136c-4d52-a9d6-0c5afc6a8e07.png)

![image](https://user-images.githubusercontent.com/57859656/154133417-70e57384-fa2b-4d55-85cf-bb0011b40455.png)

It never misses the results

**Comment by garfield69** [comment]
works for me
![image](https://user-images.githubusercontent.com/6933240/154135532-bf08ab39-c06a-4f5c-8ce3-3821322d9c74.png)

the issue is not case sensitivity.
the issue is that the RarBG API (which we are obliged to use because RarBG does not want up to do HTML scraping off their main web site) is temperamental and will regularly return no results.
The only solution is to try again until it works.

**Comment by batuhankrmn** [comment]
@garfield69 you're right It works for me too when I try again. It's unfortunate that the top public tracker has such a problem.
