### ISSUE TITLE
[New Tracker REQ] https://hdf.world/

### ISSUE THREAD

**Issue by maxcore** [Jackett/Jackett#1295]
new french tracker , invite was open and if is close i can give invitation !

thx !

**Comment by eyotiste** [comment]
+1
Gazelle tracker :)

**Comment by maxcore** [comment]
@JigSawFr @kaso17  who want the invitation ?

**Comment by krowawo** [comment]
@maxcore can you give me an invite ?

**Comment by nikogaug** [comment]
Did you got an invite ?

**Comment by maxcore** [comment]
I wait for my awnser hehe

**Comment by krowawo** [comment]
@maxcore i didn't get an invite, can you send me one

**Comment by maxcore** [comment]
I give to dev first

**Comment by maxcore** [comment]
@JigSawFr @kaso17 ?

**Comment by kaso17** [comment]
If it's standard gazelle with the API enabled I can add it quickly. If it needs more custom work I don't know when I'll have time for it.
E-Mail: kaso1717 -at- gmail.com

**Comment by maxcore** [comment]
@kaso17 done !
big thx advance :)

**Comment by kaso17** [comment]
@maxcore didn't get any email

**Comment by maxcore** [comment]
i do it again, let me know

**Comment by kaso17** [comment]
still nothing (I checked spam)

**Comment by maxcore** [comment]
Let me ask to the staff

________________________________

**Comment by maxcore** [comment]
@kaso17 the trackers was in maintenance

**Comment by raspdealer** [comment]
@maxcore if you have something for me too :) raspdealer - gmail com

**Comment by kaso17** [comment]
Has open registrations currently.
Added via 213f8114ba397dfc51c068100283fe895dfd1f6e

**Comment by maxcore** [comment]
Thx man you are fast !

**Comment by pmelopereira** [comment]
Hi, I had received an invitation but sadly the email was on my spam folder and now it has expired. Any chance I can speak to someone in the staff ? tks
