### ISSUE TITLE
Configuring Jackett under a domain without subpath redirects to http://ui/Dashboard, ignoring base URL

### ISSUE THREAD

**Issue by tjakubo2** [Jackett/Jackett#12954]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/[user]/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: \S
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.18.0.240 (64bit OS) (64bit process)
Environment version: 6.0.2 (/home/[user]/Jackett/)
```

### Description

The issue is that under Nginx w/ reverse proxy, when hosting Jackett under a domain directly (without subpath), opening that URL redirects to `http://ui/Dashboard`, ignoring any base URL set. Maybe it's misconfiguration on my part, so I'm listing steps that I've done here.

Worth noting: 
Jackett works, as in responds to requests. Accesing the Web UI under `http://subdomain.mydomain.com/ui/dashboard` also works. It's just accessing `http://subdomain.mydomain.com` that redirects to a malformed address `http://ui/Dashboard` without prefixing it with set base URL (`subdomain.mydomain.com`)

Steps:
1. Installed Jackett as a service (CentOS 8)
2. Configured my domain `subdomain.mydomain.com`
3. Configured Jackett to run under localhost setting these lines in `ServerConfig.json`
```
  "Port": 9117,
  "AllowExternal": true,
  "BasePathOverride": "",
  "BaseUrlOverride": "subdomain.mydomain.com",
```
(other lines left default)
4. Set up a reverse proxy on it under Nginx with this config file, following <https://github.com/Jackett/Jackett/wiki/Reverse-Proxy>
```
server {
    listen 80;
    server_name subdomain.mydomain.com;

    location / {
        proxy_pass         http://127.0.0.1:9117;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Host $http_host;
    }
}
```
5. Restarted nginx and jackett services

Expected result:
 - Jackett responds to queries
 - Opening `http://subdomain.mydomain.com` redirects me to Jackett Web UI
 
Observed result:
 - Jackett responds to queries
 - Opening `http://subdomain.mydomain.com` redirects me to `http://ui/dashboard`
 - Opening `http://subdomain.mydomain.com/ui/dashboard` opens Jackett Web UI

### Logged Error Messages

```text
No error logged
```

**Comment by ilike2burnthing** [comment]
Base URL override is purely for use for Docker users, and should only affect the `Copy * Feed` buttons. Try removing that from the config file, restarting Jackett, and seeing if your issue continues.

I'll edit https://github.com/Jackett/Jackett/wiki/Reverse-Proxy to clarify the wording.

**Comment by tjakubo2** [comment]
It seems that changing `BaseUrlOverride` property to both empty string and `null` doesn't change anything.
Same with `BasePathOverride`, which I also tried because why not.

Would there be any verbose logging for me to enable and post there?

BTW. If I open the problematic URL unauthorized, it correctly redirects to `http://subdomain.mydomain.com/UI/Login?ReturnUrl=%2FUI%2FDashboard`. But then, like `ReturnUrl` suggests, it redirects to `http://ui/Dashboard` after entering the password.

**Comment by ilike2burnthing** [comment]
If you use `\jackett` (and change your nginx config file), does that resolve your issue?

@Zamana you had an issue with getting a subdomain reverse proxy to work in https://github.com/Jackett/Jackett/issues/8872#issuecomment-923200202, did you manage to resolve it? Anything here jumping out to you as an issue?

**Comment by tjakubo2** [comment]
Yes, with `location /jackett` in Nginx config and `"BasePathOverride": "/jackett"`, it works great. 

As in, opening `http://subdomain.mydomain.com/jackett` correctly redirects to `http://subdomain.mydomain.com/jackett/ui/Dashboard` and it all works.

**Comment by ilike2burnthing** [comment]
And is that an acceptable solution; can this issue be closed?

**Comment by tjakubo2** [comment]
I mean, sure, as I noted in the first post, I got the system working in general. It's just that there seems to be a bug, workable around, but kinda annoying to debug because none of the Jackett config seems to affect it at all.

If you decide it's not worth dev time, or we simply should be using a subpath, feel free to close this issue.

**Comment by ilike2burnthing** [comment]
I'll see if @Zamana found a solution that I'm missing first.

I'm happy to mark this as a feature request, it's just not something I'd have the knowhow to work on.

**Comment by Zamana** [comment]
Hi!

I'm not quite sure that I understood the issue properly, so I'm sorry if this is irrelevant to the question... Anyway...

In my environment, I have a local DNS and all my "*arrs" (and jackett and plex and qbittorrent etc) are behind an Nginx reverse proxy, in such a way that I access all of them like radarr.local, sonarr.local, jackett.local and so on.

Specifically, the Jackett reverse proxy is configured like this:

```
server {
        listen       80;
        server_name  jackett.local;

        location / {
                proxy_pass http://192.168.0.105:9117;
                proxy_http_version 1.1;
                proxy_set_header   Upgrade $http_upgrade;
                proxy_set_header   Connection keep-alive;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   X-Forwarded-Host $http_host;
        }
    }
```

Where 192.168.0.105 is the IP of the jackett's jail.

**Comment by tjakubo2** [comment]
@Zamana 
Thank you, it seems to be the same config as mine.
Could you check if opening `http://jackett.local` does open the web UI dashboard for you?

**Comment by Zamana** [comment]
Yes. Automagically:

![rproxy](https://user-images.githubusercontent.com/6900313/154170816-464d995b-8b6c-49e9-9eb0-fafc88dea740.png)

**Comment by tjakubo2** [comment]
Okay, this is some isolated issue of mine then. I'd appreciate if you could post relevant parts of your `ServerConfig.json`, and I'll just get to more detailed troubleshooting on my side.

Since this does not seem to be a straight up reproducible issue, I'm closing the issue; will reopen/comment if I nail it down :)

**Comment by Zamana** [comment]
```
{
  "Port": 9117,
  "AllowExternal": true,
  "APIKey": "j0i3tj7soayayrxfvktcrhkt5iddc8ns",
  "AdminPassword": null,
  "InstanceId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "BlackholeDir": "",
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": "",
  "CacheEnabled": true,
  "CacheTtl": 2100,
  "CacheMaxResultsPerIndexer": 1000,
  "FlareSolverrUrl": "http://192.168.0.103:8191",
  "OmdbApiKey": "",
  "OmdbApiUrl": "",
  "ProxyType": -1,
  "ProxyUrl": "",
  "ProxyPort": null,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true
}
```

**Comment by matvey00z** [comment]
Hi, I am experiencing similar issue here, with jackett in docker behind nginx.

1. Open jackett.mydomain.com for the first time.
Request: jackett.mydomain.com, Response: 301, Location: /UI/Dashboard
Request: jackett.mydomain.com/UI/Dashboard, Response: 302, Location: http://jackett:9117/UI/Login?ReturnUrl=%2FUI%2FDashboard
And I end up with an 'error loading page' (no surprise)

1. Open jackett.mydomain.com/UI/Login?ReturnUrl=%2FUI%2FDashboard (change jackett:9117 to the correct domain)
Request: https://jackett.mydomain.com/UI/Login?ReturnUrl=/UI/Dashboard, Response: 302, Location: /UI/Dashboard
The UI loads properly

1. Open jacket.mydomain.com
Request: jackett.mydomain.com, Response: 301, Location: /UI/Dashboard
The UI loads properly


So that reproduces only once, when the site is opened for the first time (e.g. in a private tab), then it works properly.
Also, it doesn't matter if the BasePath is set or not.

**Comment by wilfriedarma** [comment]
Good morning,
I had the same problem...
To resolve this problem, you must not forget the target in the proxy destination, because "Base path override" by default is still authorized after modification...
 proxy_pass http://<ip-server>:9117/jackett
