### ISSUE TITLE
filter to pause indexers by disable/enable tags doesn't work from seedbox jackett control, qbit still refreshes all feeds

### ISSUE THREAD

**Issue by greeneryAO** [Jackett/Jackett#12952]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.20.562 installed on seedbox via swizzin
```

### Description

I installed jackett on my seedbox from swizzin, I control it from there, I would like to pause or disable certain tracker indexers as has been asked many times I've seen.

if I don't want results from all of them at once for example but qbit cannot do this individually without deleting rss feeds and readding and that is pretty sucky.

I added a disabled tag to one of my private trackers, set the filter to disabled, it shows only one indexer in jackett but qbit still picks them all up, how can I set it from the jackett control page? I tried apply server settings, restarting jackett and qbit, didn't work,t the filter doesn't actually do anything other than aesthetically filter the list for me on the page which is of no use.

if it's not possible can someone please implement this feature a simple on off switch for indexers.

### Logged Error Messages

```text
no log errors
```

**Comment by ilike2burnthing** [comment]
What's the URL you are using in qbit?

**Comment by greeneryAO** [comment]
for the feeds?

from qbit they are formatted like an example tracker

http://127.0.0.1:myport/jackett/api/v2.0/indexers/privatesite/results/torznab/api?apikey=privatekey=&q=

unfortunately I can't edit it once it's sync'd with jackett I don't think.

all I can do is rename the feed name not url, delete it, copy the url.

**Comment by greeneryAO** [comment]
maybe I have to re-add the feeds in qbit after I've tagged? I'll try that and if not I guess I can set up a quick copy paste queue with their addresses to delete and add them, I only need to work one or two sites at once to be honest. But I will ask for the feature request too 😬

**Comment by ilike2burnthing** [comment]
You haven't used the tag filter then. Jackett has no way to know what your tags mean.

Instead of setting up individual indexers, you'd just use one. For example, this would use all indexers using the `enabled` tag:
http://127.0.0.1:myport/jackett/api/v2.0/indexers/tag:enabled/results/torznab/api?apikey=privatekey=&q=

You can also use multiple filters:
http://127.0.0.1:myport/jackett/api/v2.0/indexers/tag:enabled,!status:failing+lang:en/results/torznab/api?apikey=privatekey=&q=

See instructions here: https://github.com/Jackett/Jackett#filter-indexers
