### ISSUE TITLE
trackers not replacing "Full Stops" with white spaces so not returning all results 

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#12965]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
os version: docker container
```

### Description

Same as issue #12689 

string used to search "star.trek"

Trackers i noticed with this issue.
- [x] Torrentdb - on their site you will get some results if you search the site with full stops but wont get all the results. 
- [x] Anthelion - you wont get results on this site if full stops are in the search string. full stops are rarely used in torrent names on this site.
- [ ] seals/[removed] - you wont get results on this site if full stops are in the search string. full stops are rarely used in torrent names on this site.
- [x] tellytorrents - you wont get results on this site if full stops are in the search string as there never is full stops in the torrent names.
- [x] thesceneplace - on their site you will get some results if you search the site with full stops but wont get all the results
- [x] bitsearch - you wont get results on this site if full stops are in the search string
- [x] hd-space - on their site you will get some results if you search the site with full stops but wont get all the results

### Logged Error Messages

```text
replacing "." with spaces like you did for HD-torrents should fix all.
```

**Comment by ilike2burnthing** [comment]
@garfield69 can you check if OppaiTime, Redacted and AlphaRatio also have this issue?

Seals is the only Gazelle-based tracker I have access to, so don't want to make a change to the abstract if it's just specific to Seals (nor waste time making a change to Seals if it's more general).

**Comment by garfield69** [comment]
alpharatio already has override to replace dots
https://github.com/Jackett/Jackett/blob/22efff93e7f1df858b341b3c2756d8204cae6f4a/src/Jackett.Common/Indexers/AlphaRatio.cs#L75-L76
oppaitime and redacted cannot handle dots 

so IMO a global dot replacement will benefit all. Dont forget tot then remove the redundant alpharatio overide. ;-)

**Comment by garfield69** [comment]
v0.20.590
