### ISSUE TITLE
[req]: Checkbox for multiple selection

### ISSUE THREAD

**Issue by helperman** [Jackett/Jackett#12960]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

It takes time to add many indexers clicking each checkbox.
A checkbox for multiple selection could be appropriate.

### Describe the solution you'd like

I suggest to add a new checkbox for selecting all indexers presented on the webpage after filtering:
![00002728](https://user-images.githubusercontent.com/8351863/154541754-10179e9b-085c-4d49-bfd8-7661fa30727b.gif)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/12143
