### ISSUE TITLE
[req]: switch Generation-free to unit3d API 5.3.0

### ISSUE THREAD

**Issue by EricG66** [Jackett/Jackett#12982]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Generation-free (GF-Free)
- URL: https://generation-free.org/
- Description: French private tracker for French (VFF/VFQ) movies,TV and others
- Minimum Seeding Time and Minimum Ratio (if Private): MST 48hrs, MR no ratio
- Additional Comments: Generation-free is currently moving to a brand new website with a new url and completely redesigned UI

The transition to the new site is not completed yet, both are still available.
```
Engine: unit3d API 5.3.0
related: #5279

**Comment by garfield69** [comment]
Since the new site is using unit3d 5.3.0 we will create a generationfree-api indexer to use the unit3d API.
Please notify us here when the old site is closed so we can delete the old indexer.

**Comment by garfield69** [comment]
v0.20.629

**Comment by EricG66** [comment]
Do this is possible to add the setting for VFQ  or a replace in the yml for changing VFQ to FRENCH?

VFQ mean French canadian

Do you I have to post a new issue for this?

Thank

**Comment by pipopop** [comment]
Is it possible to add a delay between 2 searchs or some delay between 2 requests ?

**Comment by garfield69** [comment]
>changing VFQ to FRENCH?

done 2949773ea0dccf9171e64f030f1976385b599189

**Comment by garfield69** [comment]
>Is it possible to add a delay between 2 searchs or some delay between 2 requests ?

why?

**Comment by EricG66** [comment]
> > Is it possible to add a delay between 2 searchs or some delay between 2 requests ?
> 
> why?

Enable the use of cache(Cache enabled and Cache TTL (seconds) in Jackett) or change the sonarr/radarr interval (delay RSS Sync Interval)

No?

**Comment by pipopop** [comment]
> > Is it possible to add a delay between 2 searchs or some delay between 2 requests ?
> 
> why?

Because for some sites, the number of requests from software such as radarr, sonarr or sickbeard have the effect of saturating server resources.

> Enable the use of cache(Cache enabled and Cache TTL (seconds) in Jackett) or change the sonarr/radarr interval (delay RSS Sync Interval)
> 
> No?

Indeed, I had forgotten the cache TTL option in jackett which is already activated.
I will also configure Radarr for RSS sync. But I don't use Sonarr, I find that it doesn't work very well for series with non-English titles. But I can also set a longer delay in Medusa. I'll test that.

Anyway, thank you for your work and for your help.

**Comment by garfield69** [comment]
v0.20.631

**Comment by EricG66** [comment]
@garfield69 The old site is still on but there is no new torrents posted anymore, so all the people are posting on the new site.

So I think you can remove the old site

**Comment by garfield69** [comment]
Okely Dokely.

**Comment by bob1321** [comment]
I have this error, I dont know what to do

An error occurred while testing this indexer
Exception (generationfree-api): Error while parsing field=downloadvolumefactor, selector=freeleech, value=0%: Input string was not in a correct format.: Error while parsing field=downloadvolumefactor, selector=freeleech, value=0%: Input string was not in a correct format.

**Comment by garfield69** [comment]
@bob1321  you must be using a version of Jackett at v0.20.715 or earlier. Upgrade to a newer version to pickup the updated indexer that handles GE's refresh to unit3d 6.0.4
