### ISSUE TITLE
[KickAss / KatCr] Downloads failing

### ISSUE THREAD

**Issue by JonathonSunshine** [Jackett/Jackett#1298]
Sorry if I'm not posting this properly, but I can't download anything from Kickass / katcr.co.

They turn up fine in the search but Sonarr fails to download them and I can't download them direct from Jackett either.

[log.txt](https://github.com/Jackett/Jackett/files/945479/log.txt)
[updater.txt](https://github.com/Jackett/Jackett/files/945480/updater.txt)

Jackett version:  0.7.1308.0
Mono version:  4.8.1

OS: Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-72-generic x86_64
-------------------------------

**Comment by kaso17** [comment]
fixed with a85e00f236391a71c6af531e63bd1b28e67329c8
will push a new pre release soon
