### ISSUE TITLE
[beyond-hd-oneurl] to be removed on 1st March 2022.

### ISSUE THREAD

**Issue by GlitzSmarter** [Jackett/Jackett#12993]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

BeyondHD is removing their oneurl on March 1st 2022 because they have had a number of incidents (over the past few months) with accounts being compromised.

The BeyondHD indexer (that requires a username and password) currently doesn't support 2fa.

### Describe the solution you'd like

I would love to be able to use the BeyondHD indexer with 2fa on my account or have another BeyondHD indexer that did support 2fa.

**Comment by garfield69** [comment]
Have you tried beyond-hd (API) instead of oneurl? Should not be impacted by you using 2fa with your browser session.

**Comment by GlitzSmarter** [comment]
I just tried it @garfield69 and it works great. Thanks for the reminder of that.

For anyone who uses the site and wants to use beyond-hd (API) you will find the api and rss key's under your security settings (your profile picture -> my security).

**Comment by ilike2burnthing** [comment]
We'll keep this open for now so as to remember to remove beyond-hd-oneurl at the start of March.

**Comment by garfield69** [comment]
Added Config Info about finding keys with 0d6188029e062196169fd01a925254ef465ff061

**Comment by garfield69** [comment]
v0.20.654
