### ISSUE TITLE
[req]: lesaloon: option vfq->french

### ISSUE THREAD

**Issue by EricG66** [Jackett/Jackett#12990]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Can you implement the same option to change VFQ to FRENCH like the commit https://github.com/Jackett/Jackett/commit/2949773ea0dccf9171e64f030f1976385b599189

### Describe the solution you'd like

Add the option to change VFQ to FRENCH  in the yml config

**Comment by garfield69** [comment]
v0.20.631

**Comment by Tristan-2i** [comment]
i can't find where i can modify it in v0.20.1307 ?

**Comment by ilike2burnthing** [comment]
Open config for LeSaloon (blue wrench button), tick the `Replace VFQ with FRENCH in release name` option, click Okay.

**Comment by Tristan-2i** [comment]
I thought that this option was on all indexers, I search this option for "yggtorrent" and replace VFQ with other than FRENCH.
Should I open a new Issue ?
For exemple a file like MULTI.VFQ is transformed like FRENCH.VFQ but I don't want VFQ files only VFF, what should I do ?

**Comment by ilike2burnthing** [comment]
See https://github.com/Jackett/Jackett/issues/11014#issuecomment-1186545976
