### ISSUE TITLE
[req]: LRepacks.net

### ISSUE THREAD

**Issue by Obegg** [Jackett/Jackett#12996]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: LRepacks
- URL: https://lrepacks.net/
- Description: Cracked PC Programs.
- Additional Comments: It's not really a tracker, since it's doesn't provide torrent files.
But, it provides URLs to download from, such as OxyCloud, Turbobit, Katfile, Up-load, Uploadrar.
Just thinking that even though it's not a tracker, it might be still useful to use with Jackett.
```

**Comment by garfield69** [comment]
Jackett is only useful for web sites that provide .torrent or magnet links.
Sites that list files stored at 3rd party repositories for direct download are not supported.
