### ISSUE TITLE
localhost URL when downloading .torrent

### ISSUE THREAD

**Issue by Qwatuz** [Jackett/Jackett#1299]
I have Jackett linked up to Sonarr on my dedicated server and when I do a manual search on Jackett and click download torrent, it directs me to a URL like this one:

http://localhost:9117/jackett/dl/tvchaosuk/ee5yhethe3cxy8vm?path=aHR0cHM6Ly93d3cudHZjartjhnrfjD.torrent

As Jackett and Sonarr are installed on my seedbox, a localhost URL does not load on my remote PC.

Is Jackett supposed to send this URL to Sonarr?

Thanks!

**Comment by JigSawFr** [comment]
How did you install jackett on your server ?
If apps are on the same host, localhost urls are functional,
Otherwise, you need to use your server IP / domain.
If you use a seedbox provider, please contact them as soon as possible to solve this problem.

**Comment by flightlevel** [comment]
Like jigsaw says replace localhost in Sonarr or your web browser address bar with the reachable IP address

**Comment by Qwatuz** [comment]
Thanks for your replies.

I am running a Hetzner dedicated server with Quickbox installed. I used the Quickbox installer for Jackett and Sonarr.

I have tried replacing localhost for my server's IP address but nothing will allow me to manually download .torrent links when using the Jackett manual search. Here are some screenshots if it helps understand my issue. Thanks!

[https://i.imgur.com/ONODUc2.png](url)
[https://i.imgur.com/mL73SVb.jpg](url)
[https://i.imgur.com/shJsuOC.jpg](url)

**Comment by flightlevel** [comment]
Suspect its https://plaza.quickbox.io/t/jackett-download-issue/2930 , not very good with apache sorry

**Comment by Qwatuz** [comment]
Aha! Some how it is now working. It allows me to download the .torrent file by clicking (and supplies the proper URL). 

I used "http://localhost:9117/jackett/torznab/tvchaosuk" as the URL. No httpS. I'm 99% sure I tried this once before but now it is working!

Is Jackett supposed to download the torrent file after a manual search to my PC or send it to Sonarr to then take care of?

Thanks for replying!

**Comment by Qwatuz** [comment]
In case anyone comes upon this, Type the command while in root: **nano /etc/apache2/sites-enabled/jackett.conf**

Change what is in bold. Remember no httpS!

to
<Location /jackett>
ProxyPass **http://<URL to box>:9117/jackett**
ProxyPassReverse **http://<URL to box>:9117/jackett**
AuthType Digest
AuthName "rutorrent"
AuthUserFile '/etc/htpasswd'
Require user _USERNAME_
</Location>


Sonarr settings remain as URL: http://localhost:9117/jackett/torznab/<name>
