### ISSUE TITLE
Help: Development and Testing setup for new Indexers

### ISSUE THREAD

**Issue by twistedroutes** [Jackett/Jackett#130]
I am new to Visual Studio but want to develop some indexers.

Need help on setting up the environment in VS to develop and test.  Is there perhaps a wiki page that could be created (or someone to help and I'll create a wiki page)

**Comment by WhatFox** [comment]
Install VS, grab copy of code preferably using git, open .sln with visual studio.  Click build and it does the rest.

**Comment by gjeremia** [comment]
so being a VS noob....did that but now how to debug a specific indexer?  Tried the (seemingly) obvious Debug menu, but that just tells me I'm an idiot because I'm building a Class Library !

**Comment by WhatFox** [comment]
Set the console as a startup project and breakpoints in the relevant places.  Plenty of tuts on debugging in vs out there

**Comment by JigSawFr** [comment]
Console.WriteLine can be helpfull but prefer breakpoints ;)

**Comment by gjeremia** [comment]
Thanks all.  I have it running and I have added a new indexer for xspeeds (mostly basde on TVChaosUK code)- it is front-ended by CloudFlare DDoS so I had to decide to either 
1. implement a c# javascript parse to respond to the cloudflare challenge OR
2. wait the timeout value in the refresh header (with 503 code)

This meant a number of things had to be changed to get this to work:
1. handling of the 503 as a redirect header
2. parsing the refresh header and implementing a delay if it is found
3. remembering cookies (the current code looses cookies received in redirects, or over-writes the originals, so I made them additive instead)

before I submit the code, is there any reason the cookies were not additive in the first place?
I have tested a few of the existing indexers with my code and they work fine, but I only have 2 that I can really test.

**Comment by JigSawFr** [comment]
@twistedroutes interesting ! I'm building a new indexer too, and the tracker is protected by CloudFlare. But I've no encountered any problemes at the moment (captcha or other)

**Comment by twistedroutes** [comment]
Which site ? I'd love to look at their ddos protection (I don't need an
account). They may use a very simple version of cloudflare or use more
appropriate

**Comment by twistedroutes** [comment]
how do I share what I've done ?
(I did mention I was new with VS right?)

I assume someone will check if it's acceptable to the project?

**Comment by twistedroutes** [comment]
Nevermind...RTFM!!!!  I have submitted a pull

**Comment by joelstitch** [comment]
I am interested in learning how to add other trackers, right now I would like to learn how to add metal-tracker.com to Jackett. What exactly is VS?
