### ISSUE TITLE
[req]: Remove year from search string when needed

### ISSUE THREAD

**Issue by ClandestineClout** [Jackett/Jackett#13000]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I'm always frustrated when I search for a movie and the year messes the search up.

### Describe the solution you'd like

Can we have the year removed from search strings specifically for trackers that struggle with it like Radarr can? For example, HD-Only requires us to remove the year from the search, but that seems like a fairly simple thing to do on the backend, is it not?

**Comment by garfield69** [comment]
IF you are using Radarr to send search request to a Jackett indexer, and the search needs the year removed from the query, you use the Radarr Indexer definition setting to prevent it. That is why the setting is there.
For Jackett to remove the year from incoming search request at the indexer level is not practical, as it has no way of knowing if the 4 digit number in the search string is a year for a movie that needs removing, or the actual name of a movie title, or some other 4 digit number as part of legitimate tv, book, program searches from other apps or manual searches at the dashboard.

**Comment by ClandestineClout** [comment]
I see. Am I imagining things or does it possibly auto-search the IMDb
number when inputting movies? If so maybe that could be referenced
somehow... Forgive my ig orange of how this all works I just sometimes see
things and wonder.

**Comment by garfield69** [comment]
If an incoming torznab request (such as might be sent by Radarr or Sonarr or other torznab app) contains an imdbid parm, and the requested Jackett indexer contains the support code to process the imdbid and add it to the web site search parameters, then yes.
But this is not a global feature, or exclusive to movies, it  all depends on whether the web site supports searches with imdbid in the first place and the Jackett indexer is coded to support it.
