### ISSUE TITLE
Broken download link in Results response

### ISSUE THREAD

**Issue by darki73** [Jackett/Jackett#13005]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Socks5
App config/log directory: /config/Jackett
Running in Docker: Yes (image build: v0.20.639-ls56)
File /etc/issue: Ubuntu 18.04.6 LTS
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.28.0 (64bit OS) (64bit process)
Environment version: 6.0.2 (/app/Jackett/)
Jackett version: 0.20.639
```

### Description

I've encountered strange issue with Jackett lately.  
Whenever I want to download something using Sonarr/Radarr, I am getting "No results found" message.
![image](https://user-images.githubusercontent.com/1318627/155895440-23af75fd-9be3-46e1-b3bb-564516a060d8.png)

Problem is, Jackett is reporting number of results just fine.
![image](https://user-images.githubusercontent.com/1318627/155895448-51ec2b35-0077-47e8-aa62-8f3a7f305173.png)

Then I've decided to look what exactly API is returning and found one part that might be broken for some reason:
![image](https://user-images.githubusercontent.com/1318627/155895518-6b3dc318-0d20-4c48-9a30-833286c289a1.png)

So obviously `/://jackett.domain.ru:/` is not valid URL, hence whenever I try to download same file from the Jackett UI, i am redirected to 404 page.

### Logged Error Messages

```text
There are no error message, as Jackett can get the results, but for some reason messes up the download link.
```

**Comment by ilike2burnthing** [comment]
Is this the same for all indexers?

Does this occur if you just use the IP and port to connect rather than reverse proxy?

My DDNS is currently down, so can't test this exact scenario, but it previously worked fine.

Please post a redacted copy of your `ServerConfig.json` Jackett settings file.

**Comment by darki73** [comment]
Here is the contents of my `ServerConfig.json` file:
```json
{
  "Port": 9117,
  "AllowExternal": true,
  "APIKey": "here_is_not_so_long_api_key_string",
  "AdminPassword": null,
  "InstanceId": "here_is_a_long_instance_identifier_string",
  "BlackholeDir": "",
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": "",
  "BaseUrlOverride": "https://jackett.domain.ru",
  "CacheEnabled": true,
  "CacheTtl": 2100,
  "CacheMaxResultsPerIndexer": 1000,
  "FlareSolverrUrl": "",
  "FlareSolverrMaxTimeout": 55000,
  "OmdbApiKey": "here_is_a_short_omdb_api_key",
  "OmdbApiUrl": "",
  "ProxyType": 2,
  "ProxyUrl": "proxy.domain.ru",
  "ProxyPort": 9999,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true
}
```

Just tested with other trackers, and unfortunately problem persists through all of them.
Same issue, `Link` is interpreted as `/://jackett.domain.ru:/dl/tracker`

However, if I am to access Jackett via IP:PORT, there is no such problem
![image](https://user-images.githubusercontent.com/1318627/156026032-f08976bd-e42e-4ffc-b890-e60c65c2b725.png)

All the necessary headers are being passed to the instances trough Traefik (as far as I know, as I am able to see their contents while using the `whoami` container provided by Traefik team)
![image](https://user-images.githubusercontent.com/1318627/156026163-542bf053-0353-4e94-b234-a42205d5a038.png)

**Comment by darki73** [comment]
And I've spotted the issue.
While migrating from Traefik 1 to Traefik 2 I've accidentally set `X-Forwarded-Proto:` to `/` instead of `https`.

Sorry for bringing up this question, it was an issue on MY side only.

Love Jackett, it is an amazing project! Always pitching it whenever I can to friends!
❤️🤘
