### ISSUE TITLE
Indexer Definitions

### ISSUE THREAD

**Issue by silverbullettruck2001** [Jackett/Jackett#1301]
I was looking at the Cardigann Definitions and I am trying to understand them better. Are there any resources you could point me to that would help understand what I need to do to make my own definitions?  I tried looking at the other definitions but since each one is specific to each site and each one seems to do things differently it is hard to identify the pattern and capabilities.

**Comment by JigSawFr** [comment]
@silverbullettruck2001 sorry, you need to study some trackers definitions / jackett code to create your own definitions as we have no documentation on this yet. We are thinking to create a convention for definitions. But if you need help on creating your definition, don't hesitate to create an issue and expose your question ;)

**Comment by kaso17** [comment]
I'll try to write some documentation for the definition format soon.

**Comment by dennisrpnw** [comment]
I have a yml definition that worked in Cardigann. How would I procede to add it into Jackett? I copied the yml file into the definitions folder and restarted Jackett, but it doesn't appear in the list.

**Comment by kaso17** [comment]
@dennisrpnw Check the log file during jackett startup for errors (and locations where it looks for definition files).
I started documenting the definition format here: https://github.com/Jackett/Jackett/wiki/Definition-format
But I've very little time, might take me longer to complete.
