### ISSUE TITLE
[torrentgalaxy] The SSL connection could not be established, see inner exception.: Cannot determine the frame size or a corrupted frame was received. (Config)

### ISSUE THREAD

**Issue by tejsohi** [Jackett/Jackett#13013]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
OS version: Microsoft Windows NT 10.0.22000.0 (64bit OS)
Environment version: 6.0.2 (C:\ProgramData\Jackett\)
Starting Jackett v0.20.662
```

### Description

Tried adding TorrentGalaxy as an indexer

### Logged Error Messages

```text
An error occurred while configuring this indexer
The SSL connection could not be established, see inner exception.: Cannot determine the frame size or a corrupted frame was received.
```

### Screenshots

![image](https://user-images.githubusercontent.com/57041117/156667018-9e44dc0c-1e50-4042-b920-ee904d6e2e7f.png)

**Comment by tejsohi** [comment]
> The indexer is working for me which suggests the problem is at your end. Have you tried using the Dashboard to edit the config and selecting the other alternate domains one at a time? Do they all fail with this error? IF they fail , can you access those domains with your browser running on the same PC as Jackett?
Yes I tried all the other domains and they all had the same error.
I did notice that I can no longer access those domains on my browser without connecting to a VPN, or using the Ultrasurf browser extension. I was able to access the domains before

**Comment by garfield69** [comment]
This suggests that your ISP may be blocking your access.
Have you tried switching your router DNS from the one provided by your ISP to one of the public ones from Couldflare 1.1.1.1 or Google 8.8.8.8 ?
Otherwise you are going to need to set Jackett up to use your VPN

**Comment by tejsohi** [comment]
> This suggests that your ISP may be blocking your access. Have you tried switching your router DNS from the one provided by your ISP to one of the public ones from Couldflare 1.1.1.1 or Google 8.8.8.8 ? Otherwise you are going to need to set Jackett up to use your VPN

I have just tried this and unfortunately it didn't work. I don't want to bother connecting the VPN so I will find another indexer. Thank you for your help
