### ISSUE TITLE
[Skipthecommericals][STC]: incorrect download, upload factor, minimumseedtime and freeleech status

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#13016]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
docker container running  Jackett Version v0.20.662
```

### Description

On STC everything is freeleech but none of them are being idenfied as freeleech.

Am i correct in assuming any torznab result that has 0 downloadvolumefactor is freeleech?

go to this torrent https://skipthecommericals.xyz/torrents/1821 and then do a search with jackett. you will see it does not pick up the correct download and upload factor and i assume there is not a dedicated field for freeleech. Am i correct in assuming any torznab result that has 0 downloadvolumefactor is freeleech?

also the minimumseedtime is incorrect the site [FAQ](https://skipthecommericals.xyz/pages/2) state 3 days seed time while (604800/86400) = 7 days

jacket result
    <item>
      <title>redacted</title>
      <guid>https://skipthecommericals.xyz/torrent/download/1821.bfe536b67044d44329ff63f38ea66bb5</guid>
      <jackettindexer id="skipthecommercials-api">SkipTheCommercials (API)</jackettindexer>
      <type>private</type>
      <comments>https://skipthecommericals.xyz/torrents/1821</comments>
      <pubDate>Thu, 20 Jan 2022 12:35:04 +0000</pubDate>
      <size>124470673408</size>
      <files>15</files>
      <grabs>2</grabs>
      <description />
      <link>redacted</link>
      <category>5000</category>
      <category>100002</category>
      <enclosure url="redacted" />
      <torznab:attr name="category" value="5000" />
      <torznab:attr name="category" value="100002" />
      <torznab:attr name="imdb" value="5171438" />
      <torznab:attr name="imdbid" value="tt5171438" />
      <torznab:attr name="tvdbid" value="328711" />
      <torznab:attr name="tmdbid" value="67198" />
      <torznab:attr name="seeders" value="3" />
      <torznab:attr name="peers" value="3" />
      <torznab:attr name="minimumseedtime" value="604800" />
      <torznab:attr name="downloadvolumefactor" value="1" />
      <torznab:attr name="uploadvolumefactor" value="1" />
      <torznab:attr name="coverurl" value="http://192.168.0.61:9117/img/skipthecommercials-api/?jackett_apikey=ppocpie7a6c4wd6txw3vxbbm3g40spme&amp;path=Q2ZESjhMR0lXZGRCNHZGSHJ1d0w2d0MzUTgzVmdGdTFqRE5lMkJvSDY2TE1ZUHpMVnkxYmNHc0JaaDJ0VU5kbWJJZnluY2hNRFBLOU9XMlozUWZHcGJWMDlFTmE2bXZKNGNPLWxhdkJHRnY1dVRlRE5GVW93ZXJKVklqWHZWRXZaRWdhQ1JEaFBjVjIzOHYyRzdVcWNUMjQwTExDNzZRbDNnNU13RlFOY3FJcVRUNkF0MS10ck1vUUZCWXFKMEotT2FMd0h3&amp;file=poster" />
    </item>

### Logged Error Messages

```text
none
```

### Screenshots

![Screenshot 2022-03-04 at 11 38 45](https://user-images.githubusercontent.com/57441681/156756933-6700b8ad-11f6-44b6-adc1-d5cb99426a0a.png)

**Comment by ilike2burnthing** [comment]
Check your inbox on the tracker, the site has switched to 7 days MST.

The site has a temporary global freeleech enabled, but this isn't reflected in the API.

If you search for 'picard' this will return one result which correctly shows a DLF of 0 and ULF of 2.

**Comment by swannie-eire** [comment]
> Check your inbox on the tracker, the site has switched to 7 days MST.
> 
> The site has a temporary global freeleech enabled, but this isn't reflected in the API.
> 
> If you search for 'picard' this will return one result which correctly shows a DLF of 0 and ULF of 2.

your correct.

so temporary global freeleech are not detected only staff applied freeleech is detected?

In regards to freeleech if a torrent has a torznab downloadfactor of 0 does that mean it freeleech or is there a separate field for torznab for freeleech i am missing

**Comment by ilike2burnthing** [comment]
Yes.

It's freeleech.
