### ISSUE TITLE
DanishBytes Sonarr issue

### ISSUE THREAD

**Issue by mkgeeky** [Jackett/Jackett#13023]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Server LogsDate	Level	Message
2022-03-06 14:45:00	Info	
Jackett startup finished in 27857.141 s
2022-03-06 14:45:00	Info	
Adding filter indexer ('type:semi-public' indexer) ...
2022-03-06 14:45:00	Info	
Adding filter indexer ('type:private' indexer) ...
2022-03-06 14:45:00	Info	
Adding filter indexer ('type:public' indexer) ...
2022-03-06 14:45:00	Info	
Adding aggregate indexer ('all' indexer) ...
2022-03-06 14:45:00	Info	
Loaded 581 indexers in total
2022-03-06 14:45:00	Info	
Loaded 496 Cardigann indexers: byrutor, pornleech, sugoimusic, limetorrents, cinemageddon, aussierules, torrentsectorcrew, asiancinema, peerjunkies, ebooks-shares, alleenretail, tjupt, toros, ydypt, trancetraffic, piratbitl, scenepalace, sktorrent-org, losslessclub, speedtorrentreloaded, thefallingangels, nyaasi, 1ptbar, kisssub, bithumen, zetorrents, movietorrent, mesevilag, isohunt2, tellytorrent-api, resurrectthenet, animeclipse, btdigg, torrentv, torrentz2eu, underversel, mypornclub, noname-club, lat-team-api, audionews, rgfootball, dariustracker, torrent9clone, desitorrents-api, nethd, 24rolika, spidertk, totheglorycookie, torrentleech-pl, madsrevolution, underverse, ibit, film-paleis, extremetorrents, superbits, mteamtp, sporthd, kickasstorrents-to, theoccult, ehentai, crnaberza, pterclub, filelisting, xwtclassics, gktorrent, moviesdvdr, femdomcult, turktracker, themixingbowl, 52pt, torrent-turk, prostylex, torrentleech, pornotorrent, mvgroupforum, gamestorrents, cpasbien, torrentview, immortuos, kinorun, concen, soulvoice, byrbt, beitai, lesaloon, torrentccf, karagarga, woot, legacyhd, anime-free, mononokebt, 1337x, 3dtorrents, tokyotosho, redbits-api, pornotor, ourbits, solidtorrents, megapeer, iv-torrents, teamos, p2pelite, backups, hdbitscom, kinonavse100, rptorrents, digitalcore, torrentmax, microbit, racingforme, mikan, torrentdb, turktorrent, gfxpeers, animeworld-api, leech24, hdturk, haidan, sktorrent, pornoslab, arabafenice, bitsexy, xxxtor, hdatmos, gigatorrents, torrentwhiz, finelite, empornium, vsthouse, piratbit, keepfriends, kinozal, bestcore, mactorrentsdownload, aidoruonline, torrentoyunindir, vsttorrents, jptv, nipponsei, snowpt, bwtorrents, diablotorrent, torrentsir, riperam, crackingpatching, beyond-hd, bitcityreloaded, newpct-me, darktracker, mousebits, gtorrentpro, hdhouse, lepornoinfo, Bittorrentfiles, newretro, thevault, netcosmo, hdtorrentsit, mircrew, theshinning, bitded, brasiltracker, learnbits, magicheaven, fantastiko, metaltracker, hdspain, btschool, opencd, torrentdownload, aftershock, cryptichaven, hdzone, unlimitz, pornbits, comicat, blutopia-api, skipthecommercials-api, nitro, nntt, shareisland-api, ptfiles, redstartorrent, korsar, ilcorsaroblu, ebookparadijs, firebit, tribalmixes, showrss, greekdiamond, newstudio, jpopsuki, hdbits, megamixtracker, boxingtorrents, amigosshare, mixtapetorrent, teracod, 3changtrai, crazyspirits, zamundanet, pwtorrents, mteamtp2fa, dmhy, sportscult, dxp, dark-shadow, bit-titan, torrent-pirat, totheglory, xxxtorrents, abtorrents, hellastz, arabp2p, cathoderaytube, torrentby, esharenet, aither-api, yggtorrent, carpathians, tasmanit, rintornet, eztv, hddolby, greekteam, twilight, oshenpt, torrentdownloads, puurhollands, finvip, girotorrent, puntotorrent, hawke-uno, acidlounge, rapidzona, mma-torrents, brsociety-api, thepiratebay, yourbittorrent, internetarchive, sharewood, pornbay, sdbits, btnext, aniRena, torrentsurf, hdcztorrent, gaytorrentru, broadcity, soundpark, insanetracker, acrossthetasman, thesceneplace, glodls, uniondht, learnflakes, bibliotik, elitetorrent-biz, estone, torrentbd, peeratiko, trezzor, xbytesv2, dimeadozen, theempire, rus-media, dragonworldreloaded, kickasstorrents-ws, sexypics, indietorrents, hdcenter, crazyhd, arenabg, tvchaosuk, scenerush, theplace, proporno, linuxtracker, falkonvisionteam, cinematik, deildu, torlook, totallykids, demonoid, bitspyder, rutor, krazyzone, yggcookie, lemonhd, anisource, bangumi-moe, torrent-explosiv, speedmasterhd, torlock, bluesbrothers, thehorrorcharnel, catorrent, tvroad, happyfappy, r3vwtf, gay-torrents, classix, muziekfabriek, docspedia, animelayer, sukebeinyaasi, datatalli, magico, itorrent, bitru, empornium2fa, pornolive, frozenlayer, pier720, ztracker, 2fast4you, pussytorrents, gay-torrentsorg, parnuxi, tekno3d, torrentmasters, teamhd, extratorrent-st, bluebirdhd, ilcorsaroverde, u2, torrentseeds-api, wihd, xbit, vizuk, 4thd, romanianmetaltorrents, booktracker, fanoin, pttime, hdu, discfan, spiritofrevolution, rutracker-ru, theaudioscene, bitsearch, uniongang, hdarea, hdroute, noname-clubl, bitbr, whiteangel, huntorrent, cinemamovies, torrenting, bitbazis, myspleen, springsunday, mediamaatjes, ilcorsaronero, fouducinema, eniahd, carphunter, libranet, torrent9, legittorrents, zooqle, hdme, rintor, casatorrent, piratadigital, limetorrentsclone, badasstorrents, anilibria, chdbits, xxxadulttorrent, sosulki, mvgroupmain, anaschcc, rustorka, hdonly, hdolimpo-api, hdhome, proaudiotorrents, punkshorror, 0magnet, torrentfunk, btetree, seedfile, omgwtftrackr, newstudiol, hdtime, ftuapps, RockBox, crt2fa, oxtorrent, ceskeforum, torrentgalaxy, majomparade, torrentqq, racing4everyone-api, torrentslocal, extremebits, bitturk, zomb, rainbowtracker, acgsou, opensharing, concertos, pornforall, theleachzone, coastalcrew, btsow, mnv, hdforever, unionfansub, danishbytes-api, genesismovement, netlab, linkomanija, cartoonchaos, audiobookbay, pthome, hdc, torrentproject2, reelflix-api, bt4g, freshmeat, exttorrents, bootytape, hdcity, purovicio, theshow, lastfiles, zelkaorg, xwtorrents, idope, bithorlo, ptmsg, hamsterstudio, polishsource, turkseed, sexxi, portugas, funkytorrents, fantasticheaven, swarmazon, torrentkitty, tlfbits, pctorrent, ttsweb, onejav, potuk, siambit, torrentland-api, peersfm, putao, torrentlt, trackeros-api, uhdbits, borgzelle, slosoul, milkie, bigfangroup, selezen, uhd-heaven, cpasbienclone, moviesite, generationfree-api, hdchina, extremlymtorrents, torrenthr, nbtorrents, baibako, thegeeks, ptsbao, ccfbits, hd4fans, haitang, trupornolabs, hdai, movietorrentz, 0daykiev, twilightszoom, torrentparadise, acgrip, hdsky, datascene-api, divteam, xiteme, wdt, p2pbg, nbytez, chilebt, hdmonkey, hqsource, marinetracker, pixelcove, tapochek, yts, exkinoray
2022-03-06 14:44:58	Info	
Loading Cardigann indexers from: /home/mkg/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /home/mkg/Jackett/Definitions
2022-03-06 14:44:58	Info	
Loaded 85 Native indexers: abnormal, alpharatio, anidex, anidub, animebytes, Animedia, animetorrents, anthelion, avistaz, bakabt, bb, beyond-hd-api, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, darmowetorenty, divxtotal, dontorrent, epublibre, erai-raws, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, greatposterwall, hdbitsapi, hdspace, hdtorrents, hebits, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, morethantv, myanonamouse, ncore, nebulance, newpct, norbits, oppaitime, orpheus, partis, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, secretcinema, sharewoodapi, shazbat, ShizaProject, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentmafya, torrentnetwork, torrentscsv, torrentsyndikat, tvstore, xspeeds, xthor-api, zonaq, animetosho
2022-03-06 14:44:58	Info	
Loading Native indexers ...
2022-03-06 14:44:58	Info	
Using HTTP Client: HttpWebClient2
2022-03-06 14:44:58	Info	
Using FlareSolverr: No
2022-03-06 14:44:58	Info	
Using proxy: Disabled
2022-03-06 14:44:58	Info	
App config/log directory: /home/mkg/.config/Jackett
2022-03-06 14:44:58	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-03-06 14:44:58	Info	
Running in Docker: No
2022-03-06 14:44:58	Info	
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-03-06 14:44:58	Info	
Jackett variant: CoreLinuxAmdx64
2022-03-06 14:44:58	Info	
OS version: Unix 5.4.0.86 (64bit OS) (64bit process)
2022-03-06 14:44:58	Info	
Environment version: 6.0.2 (/home/mkg/Jackett/)
```

### Description

When I try to add Jackett to Sonarr IT fails (see error messages)
I have exactly the same information added to Radarr with no problems 
Both Jackett and Sonarr is updated to lastest version

### Logged Error Messages

```text
HTTP Error - Res: [GET] https://XXX/jackett/api/v2.0/indexers/danishbytes-api/results/torznab/api?t=caps&apikey=(removed) 401.Unauthorized
Unable to connect to indexer: HTTP request failed: [401:Unauthorized] [GET] at [https://XXX/jackett/api/v2.0/indexers/danishbytes-api/results/torznab/api?t=caps&apikey=API]
```

**Comment by ilike2burnthing** [comment]
Remove the indexer from Sonarr, restart Sonarr, add the indexer from scratch.

**Comment by mkgeeky** [comment]
> Remove the indexer from Sonarr, restart Sonarr, add the indexer from scratch.

Did not help.
Same errors 🤔

**Comment by ilike2burnthing** [comment]
Are other indexers working in Sonarr?

**Comment by mkgeeky** [comment]
> Are other indexers working in Sonarr?

Yes all other works fine 
I have SuperBits and IPT added

**Comment by ilike2burnthing** [comment]
Odd...

Enable enhanced logging in Jackett, try to add DB to Sonarr, see if anything is added to the Jackett logs (if so, post it here).

**Comment by mkgeeky** [comment]
Server Logs
Date	Level	Message
2022-03-06 18:40:06	Debug	
Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett)
2022-03-06 18:40:06	Debug	
Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett)
2022-03-06 18:40:06	Debug	
Authorization was successful.
2022-03-06 18:40:06	Debug	
Execution plan of result filters (in the following order): None
2022-03-06 18:40:06	Debug	
Execution plan of exception filters (in the following order): None
2022-03-06 18:40:06	Debug	
Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter
2022-03-06 18:40:06	Debug	
Execution plan of resource filters (in the following order): None
2022-03-06 18:40:06	Debug	
Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2022-03-06 18:40:06	Info	
Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing controller action with signature System.Collections.Generic.List`1[Jackett.Common.Models.CachedLog] Logs() on controller Jackett.Server.Controllers.ServerConfigurationController (jackett).
2022-03-06 18:40:06	Info	
Executing endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)'
2022-03-06 18:40:06	Debug	
Request matched endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)'
2022-03-06 18:40:06	Debug	
Endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)' with route pattern 'api/v2.0/server/Logs' is valid for the request path '/api/v2.0/server/logs'
2022-03-06 18:40:06	Debug	
1 candidate(s) found for the request path '/api/v2.0/server/logs'
2022-03-06 18:40:06	Debug	
AuthenticationScheme: Cookies was successfully authenticated.
2022-03-06 18:40:06	Debug	
The request path /api/v2.0/server/logs does not match a supported file type
2022-03-06 18:40:06	Debug	
Request is continuing in applying rules. Current url is https://XXX/jackett/api/v2.0/server/logs?_=1646588318307
2022-03-06 18:40:06	Debug	
Request is continuing in applying rules. Current url is https://XXX/jackett/api/v2.0/server/logs?_=1646588318307
2022-03-06 18:40:06	Debug	
Request is continuing in applying rules. Current url is https://XXX/jackett/api/v2.0/server/logs?_=1646588318307
2022-03-06 18:40:06	Info	
Request starting HTTP/1.1 GET http://XXX/jackett/api/v2.0/server/logs?_=1646588318307 - -
2022-03-06 18:40:06	Debug	
Connection id "0HMFV6QM8S0B5" started.
2022-03-06 18:40:06	Debug	
Connection id "0HMFV6QM8S0B5" accepted

**Comment by ilike2burnthing** [comment]
That doesn't look like it has anything to do with the issue. Try waiting a minute so it's obvious what is what, e.g. enable enhanced logging at 18:40, try adding DB to Sonarr at 18:41.

Try adding a new public indexer as well, see if you get the same issue. If so, try adding it to Radarr as well.

Are you using just the IP and port, or reverse proxy and DDNS?

**Comment by garfield69** [comment]
Before all that, I suggest accessing the Jackett dashboard and TEST the DanishBytes (API) indexer to confirm it is configured and working properly.

**Comment by mkgeeky** [comment]
I tried to added KickAss to Sonarr. Same error.
Then i tried to add it to Radarr, no problem 🤔

I use reverse proxy to access.

Maybe it is Sonarr there is the problem?

DB is working just fine in Radarr and in Jackett webinterface

**Comment by garfield69** [comment]
Earlier you stated that you had superbits and ipt working on sonarr with these Jackett indexers.
Perhaps the url you have set up for those is different from the one you get from the jackett dashboard copy-torznab-feed button.
So try editing the sonarr ipt indexer and copy its url. and then use it to add to a new sonarr DBy indexer, replacing `iptorrents` in the url with `danishbytes-api` and see if that gets through to jackett.

**Comment by mkgeeky** [comment]
Hmm wierd..
That worked 🤔

**Comment by garfield69** [comment]
\o/

**Comment by ilike2burnthing** [comment]
Compare the new URL to the old, see if you can spot the difference, may be something very simple. Could be that you've made some change to your reverse proxy.

Check against - https://github.com/Jackett/Jackett#running-jackett-behind-a-reverse-proxy

Also make sure you aren't using `Base URL override`.
