### ISSUE TITLE
[req]: Sonarr and 1337x with "&" and "and"

### ISSUE THREAD

**Issue by tivolimeister** [Jackett/Jackett#13026]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

According to Sonarr, trackers are expected to accept both "&" and "and" as equivalents and return results of both. This doesn't seem to be the case with 1337x.

When you search 1337x it seems like "&" is omitted from the search; "x & y" becomes a search for "x y", so that kind of works. While "x and y" on the other hand becomes a search for "x and y". This creates problems because Sonarr replaces titles containing "&" with "and".

Let's say we have a show called "War & Peace". There is a torrent for that show on 1337x called "War & Peace S01E01". Sonarr will default to using "and" instead of "&" and perform the search as "War and Peace S01E01" which 1337x will not match.

### Describe the solution you'd like

Ideally the search result would include both "&" and "and".

**Comment by ilike2burnthing** [comment]
I don't see why this would be specific to 1337x.

Try the series `Miraculous: Tales of Ladybug & Cat Noir`. 1337x has results for both `and` and `&` variants. Jackett does not include the special characters in the titles, including `&`. Sonarr finds these results just fine.
