### ISSUE TITLE
Jackett does not stop attempted indexer logins after receiving "account disabled" response

### ISSUE THREAD

**Issue by siraht** [Jackett/Jackett#13025]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.598-ls56)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.28.0 (64bit OS) (64bit process)
Environment version: 6.0.2 (/app/Jackett/)
Starting Jackett v0.20.667
```

### Description

I'm not sure how to reproduce the error since I did not ever see errors myself. However, I logged into a tracker to find my account disabled, talked to their support staff, was told my account was disabled for inactivity, and that afterwards, their system was being hammered by login requests, the only application which I have running that could be to blame being Jackett. The support staff told me they've had this issue before with Jackett, and requested I share the issue with the devs.

### Logged Error Messages

```text
I have none from Jackett, only from the tracker staff.
```

**Comment by ilike2burnthing** [comment]
Are you using Jackett with automation software like Sonarr et al.? If not, Jackett does not perform searches on its own, so cannot be the cause.

Typically a relogin attempt is made once, if it fails it returns an error and doesn't try again.

What indexer is this in relation to?

**Comment by siraht** [comment]
> Are you using Jackett with automation software like Sonarr et al.? If not, Jackett does not perform searches on its own, so cannot be the cause.
> 
> Typically a relogin attempt is made once, if it fails it returns an error and doesn't try again.
> 
> What indexer is this in relation to?

Ahhh I see. This would be in relation to Radarr, then. My apologies if this is not relevant for the Jackett project.

**Comment by ilike2burnthing** [comment]
No no, it's still relevant to Jackett, I was just making sure it was definitely the cause.

If everything was functioning normally, and you were using default settings, the first time it failed it would have retried once, then Radarr would have tried again 2hrs later, then several hours later again, and further apart each time until it was only retrying once a day. Unless the site admins were being dramatic, there wouldn't (shouldn't) have been any hammering of logon attempts.

So to make sure there's not some specific issue with the indexer, we'd need to know which one you're referring to here.

**Comment by siraht** [comment]
> No no, it's still relevant to Jackett, I was just making sure it was definitely the cause.
> 
> If everything was functioning normally, and you were using default settings, the first time it failed it would have retried once, then Radarr would have tried again 2hrs later, then several hours later again, and further apart each time until it was only retrying once a day. Unless the site admins were being dramatic, there wouldn't (shouldn't) have been any hammering of logon attempts.
> 
> So to make sure there's not some specific issue with the indexer, where it will just endlessly try to login again and again, we'd need to know which one you're referring to here.

Karagarga

**Comment by ilike2burnthing** [comment]
I don't have an account, but that doesn't really matter to test a failed login attempt. It tries once, presents an error, and that's it. It doesn't try again, and it certainly doesn't hammer the site. Either the site admins were being overdramatic or you had some other issue.
