### ISSUE TITLE
[oxtorrent] Exception (oxtorrent): certificate validation failed: [Subject]  CN=*.oxtorrent.re[Issuer]  CN=E1, O=Let's Encrypt, C=US[Serial Number]  03439E51AB0B77E3244A08B113E4105F8B67[Not Before]  2/15/2022 4:21:18 PM[Not After]  5/16/2022 5:21:17 PM[Thumbprint]  4B9F0857D92B5AC4C2F334D427E3134A89EF973E: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by kraus8** [Jackett/Jackett#13022]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Docker
```

### Description

certificate validation failed (Let's encrypt)

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (oxtorrent): certificate validation failed: [Subject]
  CN=*.oxtorrent.re

[Issuer]
  CN=E1, O=Let's Encrypt, C=US

[Serial Number]
  03439E51AB0B77E3244A08B113E4105F8B67

[Not Before]
  2/15/2022 4:21:18 PM

[Not After]
  5/16/2022 5:21:17 PM

[Thumbprint]
  4B9F0857D92B5AC4C2F334D427E3134A89EF973E

 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Exception: certificate validation failed: [Subject]
  CN=*.oxtorrent.re

[Issuer]
  CN=E1, O=Let's Encrypt, C=US

[Serial Number]
  03439E51AB0B77E3244A08B113E4105F8B67

[Not Before]
  2/15/2022 4:21:18 PM

[Not After]
  5/16/2022 5:21:17 PM

[Thumbprint]
  4B9F0857D92B5AC4C2F334D427E3134A89EF973E
```

**Comment by ilike2burnthing** [comment]
Try updating the certificates of your host system.

You could also try disabling IPv6 for your Jackett container - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work-the-ssl-connection-could-not-be-established

**Comment by kraus8** [comment]
> Working ok here. Try updating the certificates of your host system.
> 
> You could also try disabling IPv6 for your Jackett container - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work-the-ssl-connection-could-not-be-established

is there any method to update the certs ? ubuntu OS
the second method did not work by the way

**Comment by ilike2burnthing** [comment]
https://manpages.ubuntu.com/manpages/xenial/man8/update-ca-certificates.8.html

**Comment by kraus8** [comment]
> https://manpages.ubuntu.com/manpages/xenial/man8/update-ca-certificates.8.html

same error, tried with update-ca-certificates, --fresh, empty certs folder and update again, no hope

**Comment by garfield69** [comment]
Are you accessing oxtorrent directly from your platform via jackett, or are you going though a proxy/VPN ?
If it's the latter, then its not your platform that needs the CA updated but the servers provided by the proxy/VPN.

**Comment by garfield69** [comment]
Also, since you are using docker, the CA store is on the docker Jackett image.
You have not provided in the environment section which version of Jackett you are using, but if your image is prior than 16 Feb, then you may need to update your docker image to the latest version, hopefully the Docker builds have the latest CA store on them.
