### ISSUE TITLE
[lat-team-api] Exception (lat-team-api): Error while parsing field=categorydesc, selector=category, value=E-Books: Object reference not set to an instance of an object.: Error while parsing field=categorydesc, selector=category, value=E-Books: Object reference not set to an instance of an object. (Test)

### ISSUE THREAD

**Issue by Reynieri** [Jackett/Jackett#13036]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
03-10 01:50:31 Info Starting Jackett v0.20.684
03-10 01:50:31 Info Environment version: 6.0.3 (/app/Jackett/)
03-10 01:50:31 Info OS version: Unix 5.10.28.0 (64bit OS) (64bit process)
03-10 01:50:31 Info Jackett variant: CoreLinuxAmdx64
03-10 01:50:31 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l
03-10 01:50:31 Info Running in Docker: Yes (image build: v0.20.684-ls58)
03-10 01:50:31 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
03-10 01:50:31 Info App config/log directory: /config/Jackett
03-10 01:50:31 Info Using proxy: Disabled
03-10 01:50:31 Info Using FlareSolverr: No
03-10 01:50:31 Info Using HTTP Client: HttpWebClient2
03-10 01:50:31 Info Loading Native indexers ..
```

### Description

when i try to add the indexer lat-team.com with the api token, works i  just got an error when testing 

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (lat-team-api): Error while parsing field=categorydesc, selector=category, value=E-Books: Object reference not set to an instance of an object.: Error while parsing field=categorydesc, selector=category, value=E-Books: Object reference not set to an instance of an object.
Click here to open an issue on GitHub for this indexer.
```

### Screenshots

![screencapture-192-168-1-54-9117-UI-Dashboard-2022-03-10-01_27_09](https://user-images.githubusercontent.com/20679916/157633050-ca28a0ca-6986-4171-b88e-f1b734480ae2.jpg)

**Comment by ilike2burnthing** [comment]
None of the maintainers have an account for this tracker, so you'll need to provide information about it so we can update it.

These are the current categories we have:
https://github.com/Jackett/Jackett/blob/59208fcf44f82d6d8a10ef70ca7a6caa6793bdaf/src/Jackett.Common/Definitions/lat-team-api.yml#L12-L19

`E-Books` is missing, hence your error, however we'd also need to know the category ID number for it and if there are any other missing categories. The easiest way to do this is to provide an HTML dump of the tracker's search page - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by Reynieri** [comment]
[Torrents - Lat-Team.txt](https://github.com/Jackett/Jackett/files/8224366/Torrents.-.Lat-Team.txt)
please let me know if this work for you i'm kinda dumb doing this kind stuff

**Comment by garfield69** [comment]
>please let me know if this work for you

Yup, all good. Next Jackett release due out in about 12 hours will have the updated categories. Thanks.

**Comment by garfield69** [comment]
v0.20.689

**Comment by Reynieri** [comment]
thank you very much, now works perfectly
