### ISSUE TITLE
[req]: Hidden-Palace

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13042]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Hidden-Palace
- URL: https://hidden-palace.xyz/
- Description: Hidden-Palace is a Private torrent site for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): MST 24h MR 1.0
- Additional Comments:
```
Engine: FMEDition

**Comment by garfield69** [comment]
v0.20.703

**Comment by ilike2burnthing** [comment]
Your account still active? I can't login (says password is wrong), recovery never sends an email, and a previously seeding torrent says there's no user with my passkey.

Looks like sign up is still open, but ugh...

**Comment by garfield69** [comment]
Same here.
Jackett fails with 
```html
Error on 20220318144703 for Hidden-Palace.txtJackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href$="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 834
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1507
File not found.
```

my guess is that the the **file not found** is the password file, since that would match the symptoms. 
Using the browser to log in I too get the wrong password, and the **recover** knew my email address but nothing has arrived yet.
%-/

**Comment by garfield69** [comment]
also noticed that the login page that is now being used has the FMEDition v3 tag so the H-P indexer will need updating with the code from the similar the-devils-lounge engine, if/when it comes back online.

**Comment by garfield69** [comment]
v0.20.728

**Comment by swannie-eire** [comment]
sorry didnot want to open another issue for this when i think they are the same site.

looks like their is another site with the same name. I think they are migrating from the old site as the old one is still up but not sure. The new site is using unit3d now.

https://hidden-palace.net/

sign-ups are open.
Description: Hidden-Palace is a Private torrent site for MOVIES / TV / GENERAL
seeding rules: 24 hours or 1:1 ratio

**Comment by garfield69** [comment]
v0.20.770

**Comment by garfield69** [comment]
https://hidden-palace.net/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.20.1088

**Comment by ilike2burnthing** [comment]
Site is back up, though I can't log in, my email isn't recognised, registration is closed, and they seem to have switched to U-232 V5.

**Comment by garfield69** [comment]
returns ERR_CONNECTION_TIMED_OUT
