### ISSUE TITLE
[Xthor] - Always getting the same results (same issue #1202)

### ISSUE THREAD

**Issue by amuteau** [Jackett/Jackett#1304]
still not working.
Jackett Version 0.7.1310.0

http://jackett.XXXX.com:9117/potato/xthor?imdbid=tt2261287&search=Ballerina+2016&user=Admin&passkey=XXX
There is no result.

Debug :
API call with category there is always same results.
https://api.xthor.bz/?passkey=XXXXXX&search=Ballerina+2016&category=6+7+95+5+4+100+94+1+2+3+8+9

API call with no category, it seem's good :
https://api.xthor.bz/?passkey=XXXX&search=Ballerina+2016

**Comment by raspdealer** [comment]
I have may be a related issue.
Query made by Radarr for Unbreakable (2000):
http://192.168.1.116:9118/torznab/xthor/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=unbreakable%202000

Results are garbage. As soon as I remove categories, results are good.

Xthor was working fine before. Any recent changes?

**Comment by amuteau** [comment]
The probleme seems to be on Xthor, il a category is define , it seem's to return alway the same result .
The solution should be to remove the categories in the request :
https://api.xthor.bz/?passkey=XXXXXX&search=toto

**Comment by kaso17** [comment]
42d8c3014748714b93812968fbda27688f364323 removes the categories until we've time to investigate the source

**Comment by thenamelessthing** [comment]
@amuteau Je t'envie tellement, Xthor... J'en rêve!

**Comment by JigSawFr** [comment]
@amuteau is this problem solved ? Or need more investigation ?

**Comment by hbooo** [comment]
All categories before (4000) returns 0 results
![image](https://user-images.githubusercontent.com/242125/28580088-0ab14db2-714e-11e7-83af-85193bc93f81.png)

**Comment by JigSawFr** [comment]
I will reintroduce categories, I've now test, and it's working successfully. Please open a new issue if the problem reappear.

**Comment by jaydee99** [comment]
Hi,

The problem seems to be still there...

When i perform a search on jackett interface, everything is fine, results are accurate.

However, the same search from radarr/sonarr will give garbage results, nothing matching the initial search...

Thanx for helping !
