### ISSUE TITLE
[req]: verdetorrent

### ISSUE THREAD

**Issue by vadorrey** [Jackett/Jackett#13050]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: verdetorrent
- URL: https://verdetorrent.com/
- Description: web tv and film in spanish
- Minimum Seeding Time and Minimum Ratio (if Private): no 
- Additional Comments:
```

**Comment by ilike2burnthing** [comment]
See DonTorrent. Change the site link to verdetorrent if you want, they're all the same.
