### ISSUE TITLE
[fouducinema] Become private tracker (config)

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#13052]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Not a problem but a modification of tracker type

### Describe the solution you'd like

[Fou-Du-Cinema](https://fou-du-cinema.net/) became a private tracker site.
Is it possible to change it ?
Great thanks for all !

**Comment by garfield69** [comment]
v0.20.709
