### ISSUE TITLE
[moviesite] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13059]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

moviesite is offline

### Logged Error Messages

```text
http://moviesite.info.hu/ returns DNS_PROBE_FINISHED_NXDOMAIN (Domain not found)
uptrends reports site available?
Just me with my cloudflare dns?
```

**Comment by garfield69** [comment]
yup, just me. using hide.me I get through.

**Comment by ilike2burnthing** [comment]
http://moviesite.info.hu/ - ERR_NAME_NOT_RESOLVED

Down for majority of Uptrends checkpoints.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://moviesite.info.hu/ ERR_CONNECTION_TIMED_OUT
all uptime checkpoints return TCP Connection Failed except Prague with Request Times out

**Comment by antivirtel** [comment]
They confirmed it's closed down: https://www.facebook.com/movieite/ as of 30th July. Can be removed.

**Comment by garfield69** [comment]
Thanks for the info.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13059#issuecomment-1662787021

**Comment by garfield69** [comment]
v0.21.718
