### ISSUE TITLE
[req]: Configure all indexers (Sort requested from site)

### ISSUE THREAD

**Issue by Obegg** [Jackett/Jackett#13069]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Some indexers may be missing some results due to misconfiguration.
The only option to configure indexers is to do it one by one.

### Describe the solution you'd like

Option to configure all indexers in one go (much like windows select all - CTRL+A).
Specifically speaking, the option to change the value "Sort requested from site".

**Comment by ilike2burnthing** [comment]
Do you mean having a way to set `Sort requested from site` for all indexers all at once?

If so, not all indexers have this setting, and those that do don't all have the same options. Even if they did, the way these settings are applied is by reconfiguring the indexer as a whole, so in the case of a semi-/private indexer that has a captcha image, this couldn't just be filled automatically.

If that's not what you were suggesting then please explain further.

**Comment by Obegg** [comment]
> Do you mean having a way to set `Sort requested from site` for all indexers all at once?
> 
Yes

> If so, not all indexers have this setting, and those that do don't all have the same options.
>
It's ok if there are some indexers that don't have this, at least give me the option to change ```Sort requested from site``` for indexers that do have.

**Comment by ilike2burnthing** [comment]
Again, even those that have `sort` and `order` settings don't all have the same options, so you couldn't just set them all to `size` and `ascending` for example. It would not be possible to implement something like this.
