### ISSUE TITLE
[Req]: SkipTheTrailers

### ISSUE THREAD

**Issue by InfernoGRiMM** [Jackett/Jackett#13066]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: SkipTheTrailers
- URL: https://skipthetrailers.xyz
- Description: SkipTheTrailers is a Private Torrent Tracker for Movies ONLY.
- Minimum Seeding Time and Minimum Ratio (if Private): MST 7 days (168hrs), MR 1.0
- Additional Comments: API can be found in Security settings
```
Engine: Unit3d 6.0.4

**Comment by garfield69** [comment]
The site's registration is closed ATM, invitation only.
If you send an invite to garfieldsixtynine -at- gmail.com I will create the indexer.

**Comment by InfernoGRiMM** [comment]
> The site's registration is closed ATM, invitation only. If you send an invite to garfieldsixtynine -at- gmail.com I will create the indexer.

Invite is sent, thank you very much

**Comment by garfield69** [comment]
Registration and login completed. Thanks.

**Comment by InfernoGRiMM** [comment]
You are welcome

**Comment by InfernoGRiMM** [comment]
Thank you, appreciate this :)

**Comment by garfield69** [comment]
The next release of Jackett due in about 20 hours will have the indexer.

**Comment by InfernoGRiMM** [comment]
thats great!! Thanks

**Comment by garfield69** [comment]
v0.20.736

**Comment by InfernoGRiMM** [comment]
thank you :)

**Comment by garfield69** [comment]
https://skipthetrailers.xyz/ returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://skipthetrailers.xyz/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://skipthetrailers.xyz/ returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://skipthetrailers.xyz/ HTTP ERROR 500

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13066#issuecomment-1350552161

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13066#issuecomment-1370400134

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://skipthetrailers.xyz/ Error 500: Internal Server Error

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
Closure notice posted on the site. Expect to be offline within the fortnight.

**Comment by garfield69** [comment]
- https://skipthetrailers.xyz/ Oops! An Error Occurred The server returned a "503 Service Unavailable".

**Comment by ilike2burnthing** [comment]
No longer closing.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13066#issuecomment-1350552161

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13066#issuecomment-1350552161

**Comment by garfield69** [comment]
v0.22.275

**Comment by garfield69** [comment]
https://skipthecommericals.xyz/ Error 503: Service Unavailable!  Sorry, we are doing some maintenance. Please check back soon.

**Comment by ilike2burnthing** [comment]
Does this need to be open still?

**Comment by garfield69** [comment]
Nope, forgot to close ;-)
