### ISSUE TITLE
Nyaa.si - Duplicated Results

### ISSUE THREAD

**Issue by Obegg** [Jackett/Jackett#13061]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Latest.
```

### Description

Duplicated Results.

### Logged Error Messages

```text
I don't think there's a need for logs, right?
```

**Comment by garfield69** [comment]
this is a direct result of https://github.com/Jackett/Jackett/issues/11019 and is expected.
