### ISSUE TITLE
[req]: The-New-Fun

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13060]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: The-New-Fun (TNF)
- URL: https://the-new-fun.spdns.eu/
- Description: The-New-Fun (TNF) is a GERMAN Private tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): tbd
- Additional Comments: 
Engine: similar to H-O-D
```

**Comment by garfield69** [comment]
WTF.
yesterday I registered, but today I cannot login, getting username or password incorrect.
There is no recover link, and registering with the same email is rejected, so my a/c is still there but clearly the password is not what I saved :-(

**Comment by ilike2burnthing** [comment]
```text
Anmeldung ist leider geschlossen!
```

```text
Registration is unfortunately closed!
```

**Comment by garfield69** [comment]
Registration appears open again

**Comment by garfield69** [comment]
v0.20.811

**Comment by garfield69** [comment]
https://the-new-fun.spdns.eu/ returns DNS_PROBE_FINISHED_NXDOMAIN (DNS domain not found)

**Comment by garfield69** [comment]
v0.20.2134

**Comment by garfield69** [comment]
https://the-new-fun.com/ > ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online
