### ISSUE TITLE
[req]: Double click tray icon to open webUI

### ISSUE THREAD

**Issue by klepp0906** [Jackett/Jackett#13067]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Unsure if its a problem.  Don't think so though.  I just reinstalled windows and with it jackett.  I assumed that double clicking the tray icon always opened the webUI.   Either its not working now, or im remembering incorrectly and that was never the case.   If it's the latter, this is a feature request :)

otherwise, more of a bug report situation :P 

### Describe the solution you'd like

To be in keeping with the overwhelming majority of other windows applications in that clicking the tray icon opens the application or in the "arr" realms case, the webui.

**Comment by garfield69** [comment]
v0.20.2158
