### ISSUE TITLE
[TeamCTgame] CASA-torrent has changed engine AND address

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#13071]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett version v0.20.728
```

### Description

Old address: https://tctg.in/
New address: https://tctg.pm
Architecture (or script, or aspect. I don't know the real word) change. Now it's the same as SpiderTK.

### Logged Error Messages

```text
No log error
```

**Comment by garfield69** [comment]
v0.20.740

**Comment by garfield69** [comment]
https://tctg.pm/ returns 
![image](https://user-images.githubusercontent.com/6933240/197316875-217a9b61-a160-4275-99f1-9ff4af3b5862.png)

**Comment by garfield69** [comment]
online.
