### ISSUE TITLE
No results when sending query to torznab API including Season/Episode code

### ISSUE THREAD

**Issue by malomehi** [Jackett/Jackett#13075]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.736-ls58)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.16.0.4 (64bit OS) (64bit process)
Environment version: 6.0.3 (/app/Jackett/)
```

### Description

Including Season/Episode code in the search query when calling the torznab API generates no results:
```
~ $ curl "http://192.168.0.2:9117/api/v2.0/indexers/all/results/torznab/api?apikey=<api_key_redacted>&extended=1&t=search&q=Carnival+Row+S01E06"
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://192.168.0.2:9117/" rel="self" type="application/rss+xml" />
    <title>AggregateSearch</title>
    <description>This feed includes all configured trackers</description>
    <link>http://127.0.0.1/</link>
    <language>en-US</language>
    <category>search</category>
  </channel>
~ $
````
However, using the same query from the UI works:

![imagen](https://user-images.githubusercontent.com/1456960/159338759-ff5e06b5-426a-49cd-87d0-85e1f42076ff.png)

API call from terminal works just fine if Season/Episode code (in this example `S01E06`) is not included in the query (e.g. `curl "http://192.168.0.2:9117/api/v2.0/indexers/all/results/torznab/api?apikey=redacted&extended=1&t=search&q=Carnival+Row"`)

### Logged Error Messages

Log messages when using `curl "http://192.168.0.2:9117/api/v2.0/indexers/all/results/torznab/api?apikey=redacted&extended=1&t=search&q=Carnival+Row+S01E06"`:
```text
Torznab search in AggregateSearch for Carnival Row S01E06 => Found 0 releases
```
When using the same query from the UI (`Carnival Row S01E06`):
```
Manual search in DivxTotal, DonTorrent, EpubLibre, EliteTorrent.biz, MoviesDVDR, GamesTorrents, NewPCT.me, Frozen Layer for Carnival Row S01E06 => Found 1 releases (from cache)
```
```


### Screenshots

_No response_

**Comment by garfield69** [comment]
apart from divxtotal, the other indexers in your collection (dontorrents, epublibre, elitetorrents.biz, moviesdvdr, gamestorrents, newpct.me, frozenlayer) do not return any results for `carnival row S01E06` on their respective web site search engines.
as for divxtotal, I sometimes get no results from this site, and at other times I do.
so there is no mystery here.

**Comment by malomehi** [comment]
I am trying to understand why the search works on the manual search on the UI but not querying the api.

The above query is just an example, I think you can try any other recent series/episode, like `Raised by wolves S02E08` for instance or `Superman and Lois S02E07` and some others.
Those alwasy return some results from the manual search in the UI but nothing from the api call.
I tried a few queries like that and I never got a result from the api, only from the manual search in the UI.

**Comment by garfield69** [comment]
then what you can do is turn on the enhanced logging on the jackett dashboard and click the apply server settings button.
now do a manual dashboard search and then view the log and look for the tornab search string that is generated.
compare that url with the one you have been building yourself that is not working, and you should get your answer.

**Comment by malomehi** [comment]
ok, I did that. the manual search uses a different API endpoint, not torznab, like:
`http://192.168.0.2:9117/api/v2.0/indexers/all/results?apikey=<redacted_api_key>&Query=Raised%20by%20wolves%20S02E08&_=1647891238607`

So I guess the `torznab` api is somehow broken when season/episode code is added to the query or it just does not work as well as the `indexers` one does.

**Comment by malomehi** [comment]
Just for general interest, the torznab queries that I posted are built by flexget when its plugin is used: https://flexget.com/Searches/torznab

That is not related to the issue, but mentioning here in case more people is trying to use the torznab plugin in flexget to query against jackett. It might not work for series episodes as in my case.

**Comment by garfield69** [comment]
FYI
`http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab/api?apikey=myapikey&t=search&q=Raised+by+wolves+S02E08`
works for me using different indexers
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://127.0.0.1:9117/" rel="self" type="application/rss+xml" />
    <title>AggregateSearch</title>
    <description>This feed includes all configured trackers</description>
    <link>http://127.0.0.1/</link>
    <language>en-US</language>
    <category>search</category>
    <item>
      <title>Raised by Wolves 2020 S02E08 1080p WEB H264-CAKES</title>
      <guid>https://kickasstorrents.to/raised-by-wolves-2020-s02e08-1080p-web-h264-cakes-t5185314.html</guid>
      <jackettindexer id="kickasstorrents-to">kickasstorrents.to</jackettindexer>
      <type>public</type>
      <comments>https://kickasstorrents.to/raised-by-wolves-2020-s02e08-1080p-web-h264-cakes-t5185314.html</comments>
      <pubDate>Sat, 19 Mar 2022 11:45:05 +1300</pubDate>
      <size>3006477056</size>
      <description />
      <link>http://127.0.0.1:9117/dl/kickasstorrents-to/?jackett_apikey=redacted&amp;path=Q2ZESjhKLXgzNHkzZGhaRWx4RE5iOVhJTFcyV3BsclJ0YXpFT1BzNDgzX0NTb3NqOVhjbTlkaDBMUGYwa25qUkE0V0czMG9KaFNKUWVwbVRRUFQ4ODkzX2s0bTROdTNiOW5oSHVFTmlHV0RmUjhKN1RfSktWSUI3Xzl6RkdfSEZzTDE2aVdnMGRXOGNpTGtDbF9USlhxVlJacjJRNzctRDRubzQyRzkzbzdXQjY3UVdJNG83Z0ZOSURBMDYzSGlrVEVvR3JpX2dsclRpdXByNjJTQmRXOWU2YUNaUVFPaHpPcjVocm42NkYzd0lFVVho&amp;file=Raised+by+Wolves+2020+S02E08+1080p+WEB+H264-CAKES</link>
      <category>5000</category>
      <category>103583</category>
      <enclosure url="http://127.0.0.1:9117/dl/kickasstorrents-to/?jackett_apikey=redacted&amp;path=Q2ZESjhKLXgzNHkzZGhaRWx4RE5iOVhJTFcyV3BsclJ0YXpFT1BzNDgzX0NTb3NqOVhjbTlkaDBMUGYwa25qUkE0V0czMG9KaFNKUWVwbVRRUFQ4ODkzX2s0bTROdTNiOW5oSHVFTmlHV0RmUjhKN1RfSktWSUI3Xzl6RkdfSEZzTDE2aVdnMGRXOGNpTGtDbF9USlhxVlJacjJRNzctRDRubzQyRzkzbzdXQjY3UVdJNG83Z0ZOSURBMDYzSGlrVEVvR3JpX2dsclRpdXByNjJTQmRXOWU2YUNaUVFPaHpPcjVocm42NkYzd0lFVVho&amp;file=Raised+by+Wolves+2020+S02E08+1080p+WEB+H264-CAKES" length="3006477056" type="application/x-bittorrent" />
      <torznab:attr name="category" value="5000" />
      <torznab:attr name="category" value="103583" />
      <torznab:attr name="seeders" value="1905" />
      <torznab:attr name="peers" value="2383" />
      <torznab:attr name="downloadvolumefactor" value="0" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>
[etc etc etc]
```
so its simply a case of the indexers you have selected not providing the results. this is not a jackett issue.

**Comment by brainstormi** [comment]
@malomehi could you try to relaunch your query replacing the query parameter by:
q=Carnival%20Rowq&season=1&ep=6

`http://192.168.0.2:9117/api/v2.0/indexers/all/results/torznab/api?apikey=<api_key_redacted>&extended=1&t=search&q=Carnival%20Rowq&season=1&ep=6`

I bet it will works. This is the format Sonarr uses to pass torznab query to Jackett and it works for these same indexers. I found the same "wrong" behaviour from Medusa app, using SxxEyy for manual search in torznab searches that Jackett or these indexers don't like it. What should be the right format? Why it fails for these and works the others ... don't know.
