### ISSUE TITLE
[demonoid] Test search in Demonoid => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by b1gd4ve90** [Jackett/Jackett#13073]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Core Windows 64bit
Not running in Docker
Proxy Disabled using TorGuard VPN with WireGuard
Have Flaresolverr running on Windows
Using Demonoid from Edge
```

### Description

I have recently just signed up to Demonoid, and i am trying to use Jackett to add the torrent, i have added the cookie but when i test i get an error message. I can search on the Demonoid website and find torrents.

### Logged Error Messages

```text
"An error occurred while testing this indexer. Test search in Demonoid => Found no results while trying to browse this tracker.
```

### Screenshots

![image](https://user-images.githubusercontent.com/101995485/159184889-b5a6f372-8eec-4475-b32d-045faec39e16.png)

![image](https://user-images.githubusercontent.com/101995485/159184904-8782ef43-4643-48c6-8a74-bb80ff4582d2.png)

**Comment by garfield69** [comment]
For Demonoid specifically, make sure you are using the v5 theme, not v3. You can find that in your control panel/account settings.
