### ISSUE TITLE
[REQ] Deildu.net (Icelandic tracker)

### ISSUE THREAD

**Issue by gustinn** [Jackett/Jackett#1308]
Icelandic tracker, semi private. It has a few different domains. For example:
https://deildu.net/
https://icetracker.org/
and more. So if it would be great if it were possible to have it like the Piratebay where users can enter their own url.

The categories:
AddCategoryMapping(15, TorznabCatType.TVAnime);
AddMultiCategoryMapping(TorznabCatType.Movies, 5, 6);
AddCategoryMapping(12, TorznabCatType.MoviesHD);
AddCategoryMapping(9, TorznabCatType.TVDocumentary);
AddCategoryMapping(11, TorznabCatType.Audio);
AddCategoryMapping(8, TorznabCatType.TVSD);
AddCategoryMapping(12, TorznabCatType.TVHD);
AddMultiCategoryMapping(TorznabCatType.TV, 8, 12);
AddCategoryMapping(3, TorznabCatType.PCMac);
AddCategoryMapping(10, TorznabCatType.PCGames);
AddCategoryMapping(14, TorznabCatType.PC);
AddCategoryMapping(1, TorznabCatType.Other);
AddCategoryMapping(4, TorznabCatType.XXX);
AddCategoryMapping(7, TorznabCatType.TVOTHER); //Cartoons
AddCategoryMapping(2, TorznabCatType.TVSport);

**Comment by gustinn** [comment]
I will do it myself

**Comment by kaso17** [comment]
thank you
