### ISSUE TITLE
xthor indexer not working

### ISSUE THREAD

**Issue by Adelscott** [Jackett/Jackett#13083]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Info Starting Jackett v0.20.756 ,
Info Environment version: 6.0.3 (/app/Jackett/) ,
Info OS version: Unix 3.10.105.0 (64bit OS) (64bit process) ,
Info Jackett variant: CoreLinuxAmdx64 ,
Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l ,
Info Running in Docker: Yes (image build: v0.20.756-ls59) ,
Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads ,
Info App config/log directory: /config/Jackett ,
Info Using proxy: Disabled ,
Info Using FlareSolverr: No ,
Info Using HTTP Client: HttpWebClient2 ,
```

### Description

Not working for me since the update, I get this when clicking on Test button 

>  An error occurred while testing this indexer
Exception (xthor-api): Error Parsing Json Response: Status=NotFound Response= : Error Parsing Json Response: Status=NotFound Response=
: Error Parsing Json Response: Status=NotFound Response= (Test)" target="_blank">Click here to open an issue on GitHub for this indexer.

Working OK on Prowlarr

### Logged Error Messages

```text
Debug	
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://xthor.tk/https%3A%2F%2Fapi.xthor.tk%2F?passkey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&category=&search=&tmdbid=&freeleech=)

==> Problem is the Url is not OK
```

### Screenshots

![image](https://user-images.githubusercontent.com/10946454/160021627-598025c1-9e6c-4410-b888-b8b80bf47fd8.png)

![image](https://user-images.githubusercontent.com/10946454/160021739-1071bc4f-c2c9-41a0-bdf7-bfbf3747ac0f.png)

**Comment by garfield69** [comment]
The updated indexer should be available with the next Jackett release due out in about 6 hours or so.
IF you get additional issues after that, then kindly just update this ticket with a fresh enhanced log and I'll re-open the ticket and try to fix asap.
Thanks.

**Comment by garfield69** [comment]
v0.20.761

**Comment by garfield69** [comment]
I will also be interested in whether or not you see posters on the dashboard search results for this indexer. Thanks.

**Comment by Adelscott** [comment]
URL is good now, it retrieves JSON. But there's another error

![image](https://user-images.githubusercontent.com/10946454/160115593-7abbbd9c-9ebf-4b97-80d2-cfd5b02f7820.png)

**Comment by garfield69** [comment]
Could either of you drag/drop the enhanced log file here so I can see the returned json please?
I don't suppose either of you has a invite so I can properly debug this indexer?
Send to garfieldsixtynine -at- gmail.com if you are able.

**Comment by neogames68** [comment]
022-03-25 15:12:20 Error

Sorry i'm not English, i do my best

2022-03-25 14:05:46 Info

Jackett is already updated. Current version: v0.20.761



Jackett.Common.IndexerException: Exception (xthor-api): Object
reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an
instance of an object.
   at Jackett.Common.Models.TorznabQuery.MatchQueryStringAND(String
title, Nullable`1 limit, String queryStringOverride) in
/home/vsts/work/1/s/src/Jackett.Common/Models/TorznabQuery.cs:line 181
   at Jackett.Common.Indexers.CardigannIndexer.ParseRowFilters(List`1
Filters, ReleaseInfo release, TorznabQuery query, Dictionary`2
variables, Object Row) in
/home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line
2083
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery
query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line
1463
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery
query, Boolean isMetaIndexer) in
/home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line
415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery
query, Boolean isMetaIndexer) in
/home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line
415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery
query, Boolean isMetaIndexer) in
/home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line
771
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String
name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line
307
   at Jackett.Server.Controllers.IndexerApiController.Test() in
/home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line
132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper
mapper, ObjectMethodExecutor executor, Object controller, Object[]
arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker
invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker
invoker, Task lastTask, State next, Scope scope, Object state, Boolean
isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed
context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&
next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker
invoker, Task lastTask, State next, Scope scope, Object state, Boolean
isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker
invoker, Task lastTask, State next, Scope scope, Object state, Boolean
isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker
invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker
invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint
endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext
context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext
httpContext) in
/home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line
61


Le ven. 25 mars 2022 à 14:54, garfield69 ***@***.***> a
écrit :

**Comment by neogames68** [comment]
![image](https://user-images.githubusercontent.com/35151283/160149072-48ae19c9-8ade-4064-b439-215aad149bac.png)

**Comment by ilike2burnthing** [comment]
**Enhanced** log please - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
looking at the old C# xthor indexer I don't see an andmatch for rows, so I don't get why this yml import from prowlerr has one.
As it is, the Jackett yml json processor does not handle an andmatch on rows  (I tested this with an experiment on blutopia yml json and get the same null reference error) so I'm going to drop the andmatch on xthor and see what happens next.
If it turns out that the xthor api generates a lot of unrelated results during queries, then we will need to look into fixing andmatch support for json.

**Comment by Besur** [comment]
Hi guys, i have the issue, i re installed jackett, and now when i add xthor i can't see it on my list anymore, i had the same issue as [Adelscott](https://github.com/Adelscott) about parse, but not anymore, i try the manual search but nothing too.

[screen](https://i.imgur.com/cDsQCNq.png)

Thanks a lot for your work.

**Comment by garfield69** [comment]
@Besur  check your add-indexer page
but you might as well wait for the next jackett update to get the next fix

**Comment by Besur** [comment]
[Screen](https://i.imgur.com/2nw2Ujc.png)
I will wait for the next update sir, thanks a lot

**Comment by thegrunge36** [comment]
I will wait the next update.
Thank you!

**Comment by garfield69** [comment]
Try out v0.20.763 and if there are problems please provide an enhanced log here. Not a snippet of the error stack trace, or a one line message, but the debug and JSON et.al. Please! Difficult to resolve issues when I'm working blind. see  https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details. Thanks.

**Comment by neogames68** [comment]
Hye, i try v0.20.763 everything is working fine again ! thanks you very much.

**Comment by garfield69** [comment]
are posters working on the dashboard search using the indexer?
do you get results for just what you search or are you getting extra unrelated titles?

**Comment by neogames68** [comment]
![image](https://user-images.githubusercontent.com/35151283/160228011-92cd9461-0459-4355-995a-0c86572e64f6.png)

seems OK even on page 2

**Comment by garfield69** [comment]
OK, closing the ticket. can always re-open again is some one discovers something new.
