### ISSUE TITLE
[Q/req]: list of parameters supported by each indexer?

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#13087]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Is there a easy way to know what indexers can use what parameters. e.g tvdbid, imdbid, season etc.. 
https://newznab.readthedocs.io/en/latest/misc/api/#predefined-categories

e.g
http://<JACKET-URL>/api/v2.0/indexers/torrentgalaxy/results/torznab/api?apikey=<API-KEY>&tvdbId=tt8806524

Also from my tests if a parameter is not supported then it just ignores it. 

Is that the case with all indexers?

### Describe the solution you'd like

if there is not some way to see all supported parameters a indexers supports then added a list of support parameters to the indexer config page like with supported categories

### Describe alternatives you've considered

checked the config of a few indexers and did not see supported parameters there.

**Comment by ilike2burnthing** [comment]
`/api/v2.0/indexers/1337x/results/torznab/api?apikey=APIKEY&t=caps`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<caps>
  <server title="Jackett" />
  <searching>
    <search available="yes" supportedParams="q" />
    <tv-search available="yes" supportedParams="q,season,ep" />
    <movie-search available="yes" supportedParams="q" />
    <music-search available="yes" supportedParams="q,album,artist" />
    <audio-search available="yes" supportedParams="q,album,artist" />
    <book-search available="yes" supportedParams="q" />
  </searching>
  <categories>
    <category id="1000" name="Console">
...
```
