### ISSUE TITLE
Is Mono.Posix.NETStandard actually needed?

### ISSUE THREAD

**Issue by alexreg** [Jackett/Jackett#13080]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://flaresolverr
Using proxy: Disabled
App config/log directory: /Users/alex/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreMacOsArm64
OS version: Unix 12.2.1 (64bit OS) (64bit process)
Environment version: 6.0.3 (/opt/homebrew/Cellar/dotnet/6.0.103/libexec/shared/Microsoft.NETCore.App/6.0.3/)
Starting Jackett v0.20.740
```

### Description

I am wondering whether the *Mono.Posix.NETStandard* library is actually needed as a dependency of Jackett. I see a comment in the source code that it causes issues with .NET Core. But the big problem in my case is that it pulls in an Intel version of the library, which is not compatible with ARM64 (and thus the Apple M1 processor). For more information, see the problems mentioned [here](https://github.com/Homebrew/homebrew-core/pull/97508#issuecomment-1074687658) and in subsequent comments.

It also seems that going forwards, [*Mono.Posix*](https://github.com/mono/mono.posix) is the library to use. Is it possible to switch over to using that already?

### Logged Error Messages

```text
N.A.
```

**Comment by alexreg** [comment]
@garfield69 Created a PR. The very simple fix seems to be just to migrated to *Mono.Posix*, which is API-compatible, and doesn't drag in the nasty Intel-only `libMonoPosixHelper.dylib` dependency.

**Comment by garfield69** [comment]
v0.20.805
