### ISSUE TITLE
[rutracker] Пожалуйста, введите код подтверждения (символы, изображенные на картинке) (Config)

### ISSUE THREAD

**Issue by hackyit1951** [Jackett/Jackett#13089]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [x] I have read the Contributing Guidelines

### Environment

```markdown
Jackett version: v0.20.709

Using HTTP Client: HttpWebClient2

Using FlareSolverr: http://172.17.0.2:8191/

Using proxy: Disabled

App config/log directory: C:\ProgramData\Jackett

ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads

Running in Docker: No

Jackett variant: CoreWindows

OS version: Microsoft Windows NT 6.3.9600.0 (64bit OS)

Environment version: 6.0.3 (C:\ProgramData\Jackett\)

Jackett stopped
```

### Description

Rutracker have an error, captcha don't solved

(Sorry my bad english)

### Logged Error Messages

```text
An error occurred while updating this indexer
Пожалуйста, введите код подтверждения (символы, изображенные на картинке)
Click here to open an issue on GitHub for this indexer.
```

### Screenshots

![jackett-rutracker-captcha-error](https://user-images.githubusercontent.com/101488289/160257576-c428525f-5204-49b3-9327-067d4bf51036.JPG)

**Comment by garfield69** [comment]
try again, but this time use all lower case lettering.
