### ISSUE TITLE
[req]: https://xxxtorrent.net/

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#13085]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: xxxtorrent
- URL: https://xxxtorrent.net/
- Description: mix adult content
- Minimum Seeding Time and Minimum Ratio (if Private): public
- Additional Comments: site is updating and search engine is working
```

**Comment by garfield69** [comment]
site does not have its own .torrents but offloads them to a 3rd party that presents additional front end before downloads.
The seeds and peers are a randomly generated value.
Basivally this site is not suitable for use with Jackett and I am not going to waste my time trying to shoe horn it into conforming to torznab standards.
