### ISSUE TITLE
[req]: AnimeItalia.org

### ISSUE THREAD

**Issue by enrico1203** [Jackett/Jackett#13082]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: AnimeItalia
- URL: https://animeitalia.org/
- Description: Private italian tracker dedicated about anime sub ita or ita (no other contents)
- Minimum Seeding Time and Minimum Ratio (if Private): MR 1.0, no Hit and run
- Additional Comments: Registration are open with the form or i can send an invite.
- Engine UNIT3D 6.0.4
```

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine -at- gmail.com I will build the yml indexer for this site.

**Comment by enrico1203** [comment]
invite sent. thanks!

**Comment by garfield69** [comment]
Registration completed and login successful. Thanks.

**Comment by garfield69** [comment]
Next release of Jackett due out in about 10 hours or so will include the new indexer.

**Comment by garfield69** [comment]
v0.20.761

**Comment by garfield69** [comment]
https://animeitalia.org/ returns Error 503: Service Unavailable!

**Comment by garfield69** [comment]
v0.20.1027
