### ISSUE TITLE
[BitSearch] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13090]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

BitSearch is offline

### Logged Error Messages

```text
https://bitsearch.to/ returns the cloudflare refresh page
```

### Screenshots

![image](https://user-images.githubusercontent.com/6933240/160259491-da788861-232b-492a-9e72-dd5bee7a1d58.png)

**Comment by ilike2burnthing** [comment]
back up
