### ISSUE TITLE
[magico] Exception (magico): Login failed: No form found on https://trelas.club/?p=home

### ISSUE THREAD

**Issue by vlevas** [Jackett/Jackett#13094]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
docker: yes
Jackett Version v0.20.775

Running in Docker: Yes (image build: v0.20.775-ls60)

File /etc/issue: Ubuntu 18.04.6 LTS \n \l

Jackett variant: CoreLinuxAmdx64
	
OS version: Unix 4.15.0.171 (64bit OS) (64bit process)

Environment version: 6.0.3 (/app/Jackett/)
```

### Description

The tracker changes his domain name to : trellas.net 

I tried to change it on options on tracker but it shows an error..

### Logged Error Messages

```text
i post some link pictures
```

### Screenshots

https://prnt.sc/MuTj2Usr988Z

https://prnt.sc/ekKomKittOkg
https://prnt.sc/kh8GkgZuDXp-

**Comment by ilike2burnthing** [comment]
Change the sitelink from `https://trelas.club/` to `https://trellas.net/`.

**Comment by garfield69** [comment]
v0.20.778
