### ISSUE TITLE
[req]: help me to configure Jackett on Mac

### ISSUE THREAD

**Issue by FattsoCattso** [Jackett/Jackett#13096]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

*Jackett directory*: /Users/matas/Downloads/Jackett
*launchctl info*:
gui/501/org.user.Jackett = {
	active count = 0
	path = /Users/matas/Library/LaunchAgents/org.user.Jackett.plist
	state = spawn scheduled

	program = /Users/matas/Downloads/Jackett/jackett
	arguments = {
		/Users/matas/Downloads/Jackett/jackett
		--NoRestart
	}

	working directory = /Users/matas/Downloads/Jackett

	inherited environment = {
		SSH_AUTH_SOCK => /private/tmp/com.apple.launchd.7J8xUrYUEx/Listeners
	}

	default environment = {
		PATH => /usr/bin:/bin:/usr/sbin:/sbin
	}

	environment = {
		PATH => /usr/bin:/bin:/usr/sbin:/sbin
		XPC_SERVICE_NAME => org.user.Jackett
	}

	domain = gui/501 [100055]
	asid = 100055
	minimum runtime = 10
	exit timeout = 5
	runs = 1
	last exit code = 78: EX_CONFIG

	event triggers = {
		org.user.Jackett => {
			keepalive = 0
			service = org.user.Jackett
			stream = com.apple.launchd.helper
			monitor = com.apple.UserEventAgent-Aqua
			descriptor = {
				"Executable" => "/Users/matas/Downloads/Jackett/jackett"
				"SkipImmediatePoll" => true
			}
		}
	}

	event channels = {
		"com.apple.launchd.helper" = {
			port = 0x0
			active = 0
			managed = 1
			reset = 0
			hide = 0
			watching = 0
		}
	}

	spawn type = daemon (3)
	jetsam priority = 4
	jetsam memory limit (active) = (unlimited)
	jetsam memory limit (inactive) = (unlimited)
	jetsamproperties category = daemon
	submitted job. ignore execute allowed
	jetsam thread limit = 32
	cpumon = default

	properties = keepalive | runatload | penalty box | inferred program
}
*LaunchAgents permissions*:
drwxr-xr-x   3 matas  staff    96 Mar 29 15:26 .
drwx------@ 73 matas  staff  2336 Mar 29 15:26 ..
-rw-r--r--   1 matas  staff   702 Mar 29 16:04 org.user.Jackett.plist

### Describe the solution you'd like

help me to configure Jackett on Mac. I just transferred from windows to Mac and have no idea what's happening

**Comment by ilike2burnthing** [comment]
This isn't what requests are for.

https://github.com/Jackett/Jackett#installation-on-macos
