### ISSUE TITLE
[New Tracker REQ] Néo-tk

### ISSUE THREAD

**Issue by nikogaug** [Jackett/Jackett#1309]
Tracker Name : Néo-tk
Type : Movie and TV. (Some books and PC Games.)
Private tracker. I can send an invite.
Indexer URL : [http://neo-tk.com](http://neo-tk.com)
Indexer language : French

**Comment by nikogaug** [comment]
//Adulte-XXX
AddCategoryMapping("47", TorznabCatType.XXX);
//Films d'Animation, X265 ALL, CINE CLUB ALL, VFSTFR, WEBRIP ALL, VO ALL, FILM VOST-FR
AddMultiCategoryMapping(TorznabCatType.Movies, 28, 70, 54, 69, 62, 78, 53);
//Films BluRay 1080P, Films BluRay 720P, Full BluRay, 
AddMultiCategoryMapping(TorznabCatType.MoviesBluRay, 65, 42, 80);
//4K, REMUX, M-HD ALL, DVD-R
AddMultiCategoryMapping(TorznabCatType.MoviesHD, 79, 81, 71, 52);
//HDRIP ALL, BDRIP ALL, BRRIP ALL, DVDRIP ALL, DVDSCR R5, SCREENER TS CAM
AddMultiCategoryMapping(TorznabCatType.MoviesSD, 63, 56, 57, 2, 51, 50);
//HDTV ALL, SERIE PACK, TV ALL, HDTV ALL
AddMultiCategoryMapping(TorznabCatType.TV, 68, 18, 60, 73);
//WEB-DL ALL
AddCategoryMapping("72", TorznabCatType.MoviesWEBDL);
//BLURAY 3D
AddCategoryMapping("58", TorznabCatType.Movies3D);
//DOCUMENTAIRES ALL
AddCategoryMapping("9", TorznabCatType.TVDocumentary);
//AUTRES, INCLASSABLES DIVERS
AddMultiCategoryMapping(TorznabCatType.Other, 77, 61);
//E-BOOKS IMAGES
AddCategoryMapping("36", TorznabCatType.BooksEbook);
//E-BOOKS AUDIO
AddCategoryMapping("74", TorznabCatType.AudioAudiobook);
//NINTENDO, 
AddCategoryMapping("43",TorznabCatType.Console);
//JEUX PC
AddCategoryMapping("10", TorznabCatType.PCGames);
//JEUX PS3
AddCategoryMapping("43", TorznabCatType.ConsolePS3);
//JEUX PSP
AddCategoryMapping("12", TorznabCatType.ConsolePSP);
//JEUX Wii
AddCategoryMapping("43", TorznabCatType.ConsoleWii);
//XBOX 360
AddCategoryMapping("14", TorznabCatType.ConsoleXbox360);
//APPLE
AddCategoryMapping("75", TorznabCatType.PCMac);
//UBUNTU LINUX, WINDOWS, Phone Tablette
AddMultiCategoryMapping(TorznabCatType.PC, 20, 18, 78);
//SPECTACLE
AddCategoryMapping("67", TorznabCatType.TVOTHER);
//SPORTS ALL
AddCategoryMapping("68", TorznabCatType.TVSport);
//SERIE TV VF-HD, SERIE TV VOSTFR HD
AddMultiCategoryMapping(TorznabCatType.TVHD, 6, 59);

**Comment by nikogaug** [comment]
Sorry, the tracker seems to be down now. I will post a message when it will be up.

**Comment by nikogaug** [comment]
Ok it seems ok right now

**Comment by nikogaug** [comment]
I have invitation if you need one.

**Comment by garfield69** [comment]
can't reach site, took too long to respond. broken again or changed domain?

**Comment by pipopop** [comment]
No the site is dead since last month.
This ticket can be closed.

**Comment by pipopop** [comment]
Garfield69, Do you want other french tracker ?

**Comment by garfield69** [comment]
if you want us to attempt to add any other sites, please just open a request ticket, one for each site you would like added, so we can track the progress and status of each. Thanks.
