### ISSUE TITLE
VPN with Synology

### ISSUE THREAD

**Issue by komainu85** [Jackett/Jackett#1310]
Im using Jackett with my synology nas. I have a vpn setup on my disk station, and require jackett to only connect using the vpn from diskstation. Is this supported?

**Comment by flightlevel** [comment]
Jackett is just an application. How do you ensure any other app eg. Sonarr, torrent client etc only use the VPN on the Synology. Probably worth googling/Synology forum how people limit access eg. you'd think people would want to limit access on their download clients. Something as simple as blocking port 9117 outbound might be enough for you though ??? eg. http://whrl.pl/Reg9nM
