### ISSUE TITLE
[req]: Adding TV: Non English category for indexers capabilities 

### ISSUE THREAD

**Issue by Usomania** [Jackett/Jackett#13100]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

There is no TV Show Non English category and my queries come up empty. 

### Describe the solution you'd like

Adding updating tracker categories specifically torrentday. 

### Describe alternatives you've considered

Tried every category and the torrent would not show up in searches.

**Comment by ilike2burnthing** [comment]
Please provide an HTML dump of the TorrentDay search page, as we'll need a full list of all the categories and their IDs - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by ilike2burnthing** [comment]
@Usomania if you want this issue resolved you'll need to provide that HTML dump.
