### ISSUE TITLE
1337x not working

### ISSUE THREAD

**Issue by Johngeush** [Jackett/Jackett#13117]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.20.805

On Ubuntu 20.04 with système autostart
```

### Description

Hello

is 1337x not working for other people

I’m on the lastest Version since this morning and it doesn’t work anymore

I have tried removing adding back the indexing and get the same error

the website seems up

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (1337x): Name or service not known: Name or service not known (1337x.to:443)
```

**Comment by garfield69** [comment]
Not a Jackett issue. 
Some of 1337x domains are currently offline around the world.
Use your Jackett dashboard to edit the 1337x indexer, and select each of the alternate sitelinks one at a time and test to see if any work for you.
Note that some of the alternate domains require Jackett to use the Flaresolverr utility to complete the Cloudflare challenge. See https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured if required.
