### ISSUE TITLE
[req]: Allow BaseUrlOverride to set ServerURL For Download Links

### ISSUE THREAD

**Issue by Spartanaco** [Jackett/Jackett#13113]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I use Jackett on a slice server (shared with others), part of the implementation on this slice server is a primary Nginx instance that handles SSL termination, which then proxies traffic to another Nginx instance I have control over and am able to configure reverse proxy locations through.

Following the documentation to configure a reverse proxy implementation of Jackett everything seems to work fine, except the "Download" links that are generated (by the API and UI) appear to use a Host header value from the primary Nginx instance which I have no control over.

The rendered download links seem to use the Header(s) set by the primary Nginx server and ignore the Header values I'm setting in the subsequent reverse proxy implementation, resulting in broken Download links (both from the UI and returned by the API).

### Describe the solution you'd like

Since we already have the ability to define a BaseUrlOverride in the ServerConfig.json for use in Docker environments, why can't this value be used to define the ServerURL used to generate Download links?

I've tested this and it appears to work as desired for my use-case. Perhaps with an additional ServerConfig.json option to use the BaseURL Override would give greater flexibility in varying implementations.

The following was added in Jackett.Server/Services/ServerService.cs at line 388 for a custom build that fixed my issues.

```
if (string.IsNullOrEmpty(config.BaseUrlOverride))
                return $"{scheme}://{request.HttpContext.Request.Host.Host}:{port}{BasePath()}/";
            else
                return $"{config.BaseUrlOverride}:{port}{BasePath()}/";
```

### Describe alternatives you've considered

I've attempted many different Nginx configurations and can't seem to get the Headers set correctly to allow the default behavior to use the correct Host name in the computed ServerURL.

I'm told by support staff that my issue is likely related to how WebSockets are handled within Jackett and the odd "double proxy" configuration that's required if I want to use SSL for my Jackett connection strings, which I do.

**Comment by ilike2burnthing** [comment]
Would this not mean that what should be local download links for Docker users would now begin, e.g. `http://jackett:9117`?

**Comment by Spartanaco** [comment]
> Would this not mean that what should be local download links for Docker users would now begin, e.g. `http://jackett:9117`?

I'm not super familiar with how the "BaseUrlOverride" config option is used, but that's why I suggested adding an additional configuration option to override the ServerURL function to use the BaseUrlOverride, so it's an optional behavior that can be configured.

I'm open to feedback and ideas, I just wanted to raise awareness of this odd use-case I ran into.
I'm not sure I'm the best person to implement this feature/request given my limited knowledge of the codebase.

Also, I'd be happy to hear of some alternative Nginx options or configurations I could use in lieu of changing the codebase, as I think the issue is stemming from the proxy.

**Comment by ilike2burnthing** [comment]
BaseUrlOverride is purely a cosmetic change, modifying the URLs behind the `Copy * Feed` buttons to make it easier for Docker users working with Sonarr et al.

It may be better to just add a new setting to override the download URL.

Other than directing you towards our Readme and Wiki sections, I'm not sure I can help with something that niche:
https://github.com/Jackett/Jackett#running-jackett-behind-a-reverse-proxy
https://github.com/Jackett/Jackett/wiki/Reverse-Proxy

Presumably you'll have read those though, so if they're of no further help then we can change the title of this issue.

**Comment by Spartanaco** [comment]
I'm still of the opinion that the "BaseUrlOverride" should override the base of the Jackett URL - wherever it's used.
It wasn't very intuitive trying to figure out why the download links being sent back to clients were using the incorrect host name.

I think adding an additional configuration option to use the BaseUrlOverride for the GetServerUrl would be a nice addition in functionality with hopefully minimal impact.

If you'd like I can change the title of the issue to be more accurate, just wanted to get some feedback on this suggestion. Thanks.

**Comment by rafaelreis-r** [comment]
I second this request. 
I have jackett running as a docker container, behind caddy as reverse proxy. 
I use https://myurl.tld:**port**/ as Base URL. Since a few updates ago, jackett started stripping the port from the download links rendering the application useless.

This used to work on earlier versions, for years. Recently something has changed and broken this crucial feature.

**Comment by ilike2burnthing** [comment]
@rafaelreis-r can you try older images with a new container to track down what version this change occurred for you? To my knowledge, nothing we've done recently should have had any affect like that.

**Comment by garfield69** [comment]
v0.20.2158
