### ISSUE TITLE
[anidex] Exception (anidex): Anidex search returned unexpected result. Expected 200 OK but got Forbidden.: Anidex search returned unexpected result. Expected 200 OK but got Forbidden. (Test)

### ISSUE THREAD

**Issue by GersonAquino** [Jackett/Jackett#13112]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using Opera 85.0.4341.47 and BiglyBT 3.0, both return the same error
```

### Description

I simply tried to add Anidex to the indexers list, chose languages English and Portuguese(Portugal), then clicked Okay and that's it, the error showed up

### Logged Error Messages

```text
There are no logs... at least I can't find any.
```

### Screenshots

![image](https://user-images.githubusercontent.com/58166147/161850185-c7920cdf-e74f-446c-851d-ae628226f285.png)

No logs?? Maybe wrong folder?
![image](https://user-images.githubusercontent.com/58166147/161850598-befb2f9e-243e-4b4c-98dd-46aaa907dacc.png)

**Comment by garfield69** [comment]
this is already covered by ticket #1335
closing as a duplicate.
