### ISSUE TITLE
[MoreThanTV] Object reference not set to an instance of an object.: Parse error

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13111]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19043.0 (64bit OS)
Environment version: 6.0.3 (C:\ProgramData\Jackett\)
Starting Jackett v0.20.794
```

### Description

MoreThanTV indexer fails the dashboard TEST
It seems that the indexer is unable to locate the title, as the error occurs at line 267 in the indexer C# code
https://github.com/Jackett/Jackett/blob/d0a988b40e91b10cf130453d7e45aae03c17cf9a/src/Jackett.Common/Indexers/MoreThanTV.cs#L267
@missingfile As the last contributor to this indexer, perhaps you would like to take a look and resolve? 
Thanks.
[log.txt](https://github.com/Jackett/Jackett/files/8421432/log.txt)

### Logged Error Messages

```text
see attached log above for full details
Error on 20220406071059 for MoreThanTV.txtSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.MoreThanTV.GetReleasesAsync(ICollection`1 releases, TorznabQuery query, String searchQuery) in D:\a\1\s\src\Jackett.Common\Indexers\MoreThanTV.cs:line 267
```

**Comment by missingfile** [comment]
Interesting. It might make more sense to replace this scraper with their torznab compatible API though.

**Comment by garfield69** [comment]
Didn't know they had an API. have you a link to the docs, I can't find anything on the wiki.

**Comment by missingfile** [comment]
They're just starting to roll it out. The first news article post with the hidden text shows the details.

As for the scraper, I'm having issues getting the query selector to work with finding the download anchor.

```
                    var downloadAnchor = torrent.QuerySelector("a[href^=\"/torrents.php?action=download\"]");
                    var title = torrent.QuerySelector("a.overlay_torrent").TextContent.Trim();
```
should work. I tested those selectors in Chrome and they seem fine. But in my Jackett instance it fails.

**Comment by garfield69** [comment]
>The first news article post with the hidden text shows the details.

Cool. If Mtv is providing a Torznab API then users of Sonarr/Radarr can define an indexer without using Jackett as an intermediary.
But users of the Jackett search dashboard still need an indexer to search with.
I'll see if I can build a yml MoreThanTV-API indexer and get it working.

**Comment by garfield69** [comment]
However this will depend on whether or not the Mtv torznab API supports the general `t=search` as we want to provide a full torrent list, not just one specific for TV `t=tvsearch` or Movies `t=movie`  queries.

**Comment by garfield69** [comment]
first test results:
https://www.morethantv.me/api/torznab?t=search&cat=&extended=1&apikey=redacted&offset=0&limit=100
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:torznab="http://torznab.com/schemas/2015/feed"> <channel>
  <item>
    <title>Super.Pumped.The.Battle.for.Uber.S01E06.DV.2160p.WEB.h265-KOGi</title>
    <guid isPermaLink="true">https://www.morethantv.me/torrents.php?id=771200&amp;torrentid=736742</guid>
    <link>https://www.morethantv.me/torrents.php?action=download&amp;id=736742&amp;authkey=redacted&amp;torrent_pass=redacted</link>
    <comments>https://www.morethantv.me/torrents.php?id=771200&amp;torrentid=736742</comments>
    <pubDate>Wed, 6 Apr 2022 19:10:14 +0000</pubDate>
    <category>TV > UHD</category>
    <description>TBA</description>
    <enclosure url="https://www.morethantv.me/torrents.php?action=download&amp;id=736742&amp;authkey=redacted&amp;torrent_pass=redacted" length="19335" type="application/x-bittorrent" />
    <torznab:attr name="category" value="5000"/>
    <torznab:attr name="category" value="5045"/>
    <torznab:attr name="size" value="6512942156" />
    <torznab:attr name="files" value="1" />
    <torznab:attr name="poster" value="anon" />
    <torznab:attr name="grabs" value="0" />
    <torznab:attr name="seeders" value="2" />
    <torznab:attr name="leechers" value="1" />
    <torznab:attr name="peers" value="3" />
    <torznab:attr name="infohash" value="66f83ebcb6c2d68be3f86f47696c0d7e6030ed78" />
    <torznab:attr name="downloadvolumefactor" value="1.0" />
    <torznab:attr name="uploadvolumefactor" value="1.0" />
    <torznab:attr name="tag" value="anonymous" />
  </item>
```
Hmm. not entirely sure our Cardigann can process the `torznab:attr name=` keys to fetch the seeds, size etc.
I'll experiment and see what I can make of it all.

**Comment by missingfile** [comment]
Yea, there's also a bug where the movie endpoint's function name is moviesearch. Will be corrected to movie in the next update.

**Comment by FDrebin** [comment]
The API was recently released : https://www.reddit.com/r/trackers/comments/twe97h/major_mtv_announcement/

Not sure if anyone has access to MTV that you could ask questions of the staff or anything needed to make this work.

**Comment by missingfile** [comment]
For what it's worth, you can add ```&o=json``` if parsing JSON is easier than XML.

**Comment by garfield69** [comment]
OH DUH! forgot about that torznab parm. Thanks.

**Comment by garfield69** [comment]
Json output is not valid atm, all the torrents are returned as one item :-(
will continue with the xml coding for now.

**Comment by garfield69** [comment]
ignore that comment about json, I need a break and making mistakes.

**Comment by garfield69** [comment]
BTW the indexer is working again, so its likely the issue was temporary at the Mtv site.
I am closing this ticket, and will open a new one for switching to the api.
