### ISSUE TITLE
Blackhole Link: Missing Filename

### ISSUE THREAD

**Issue by guiburgueira** [Jackett/Jackett#1311]
Jackett version:  0.7.1310.0
Mono version (if not using Windows):  Mono JIT compiler version 4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan  3 11:48:26 UTC 2017)
-------------------------------
After setting up the torrent black hole directory correctly i tried to use the link "Save the server black hole" on the search results page, nothing happened but the site message "Request to Jackett server failed". I tailed the log file to see if anything was registered after clicking the button and there's nothing.

I found what's causing my jacket malfunction but don't know how to fix it.

The blackhole link have the filename missing. If i add it manually everything works.

Example:
Black hole link:
http://server.eu/gui/jackett/bh/rutracker/1blsdneq4bd4qi061m3c7r9ae4gmxy8q?path=aHR0cHM6Ly9ydXRyYWNrZXIub3JnL2ZvcnVtL2RsLnBocD90PTM3Mjk4MzU1&file=

You can see there's nothing after the &file=

And the Download locally link with the file name working properly:

http://server.eu/gui/jackett/dl/rutracker/1blsdneq4bd4qi061m3c7r9ae4gmxy8q?path=aHR0cHM6Ly9ydXRyYWNrZXIub3JnL2ZvcnVtL2RsLnBocD90PTM3Mjk4MzU1&file=(Melodic+Metal)+Wolfpakk+(%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82+Michael+Voss+%26+Mark+Sweeney%3A+%D0%B5x-Crystal+Ball%2C+Casanova%2C+Mad+Max+%26+many+guests)+-+%D0%94%D0%B8%D1%81%D0%BA%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F+(2011+-+2017%2C+4CD)+MP3%2C+320+kbps.torrent

If i manually add the same &file= string found on the  "Download locally link" i can get it working.

NOTE: It happens on every black hole link i try, no matter the tracker.

**Comment by kaso17** [comment]
The "file" argument should be ignored and the file name should be always set to "large number"+.torrent (e.g. 636211868389962111.torrent). It's working fine for me.
It seems like you're using a reverse proxy setup, maybe that combination is causing some trouble?
Please start jackett with the command line options "-l -t" and check the log again after clicking on a BH link.

**Comment by guiburgueira** [comment]
I'm on a managed seedbox. I can't use start parameters there.
I will close the issue so.
