### ISSUE TITLE
[fouducinema] Login failed: No form found on https://fou-du-cinema.net/login.php using form selector form[action=

### ISSUE THREAD

**Issue by gkovacsp** [Jackett/Jackett#13129]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
today at 11:01:3204-09 11:01:32 Info Starting Jackett v0.20.811 
today at 11:01:3404-09 11:01:34 Info Environment version: 6.0.3 (/app/Jackett/) 
today at 11:01:3404-09 11:01:34 Info OS version: Unix 5.10.103.7 
today at 11:01:3404-09 11:01:34 Info Jackett variant: CoreLinuxArm32 
today at 11:01:3404-09 11:01:34 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l 
today at 11:01:3404-09 11:01:34 Info Running in Docker: Yes (image build: v0.20.788-ls60) 
today at 11:01:3404-09 11:01:34 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
today at 11:01:3404-09 11:01:34 Info App config/log directory: /config/Jackett 
today at 11:01:3404-09 11:01:34 Info Using proxy: Disabled 
today at 11:01:3404-09 11:01:34 Info Using FlareSolverr: http://192.168.1.200:8191 
today at 11:01:3404-09 11:01:34 Info Using HTTP Client: HttpWebClient2 
```

### Description

Fou du cinema changed its engine, the login page has a new layout, jackett can't login.

### Logged Error Messages

```text
An error occurred while updating this indexer
Login failed: No form found on https://fou-du-cinema.net/login.php using form selector form[action="/login.php"]
```

### Screenshots

<img width="608" alt="image" src="https://user-images.githubusercontent.com/1654787/162564568-e607fd0f-f686-4b56-bda9-dc46ea84b917.png">
<img width="770" alt="image" src="https://user-images.githubusercontent.com/1654787/162564603-e3aa1986-81e5-4450-8171-f6e7858fa059.png">

**Comment by ilike2burnthing** [comment]
They appear to be in the middle of transferring over to using TorrentTrader as the tracker engine. In the last few minutes they've added their banner, rather than having the stock 'TorrentTrader' logo.

I'm going to sign up for an account, as registrations appear to be open. However, it's probably worth waiting a day or few before trying to update the indexer for it.

Are you able to sign in with your account?

**Comment by gkovacsp** [comment]
It seems there was a full reset, I had to recreate my account, there are only about 10 torrents on the site as of this morning.

**Comment by thegrunge36** [comment]
I can't add it yet this morning

**Comment by ilike2burnthing** [comment]
> However, it's probably worth waiting a day or few before trying to update the indexer for it.

https://github.com/Jackett/Jackett/issues/13129#issuecomment-1093947603

**Comment by garfield69** [comment]
the indexer for tt3 is prepared, however the site is still in flux.
the categories are a little strange, with the ones beginning with FILM looking more like they should be Music.
And the gold coin for freeleech should us as a encoded data stream or a images/free.gif link.
No signs of MR or MST yet, I could carry over the ones from the old indexer ...
The search results have not dates :-( even though the site supports sorting by date %-/
Just 47 torrents total on site atm. 
Going to wait a little longer before publishing until it looks like things are settling.

**Comment by garfield69** [comment]
getting 500 Internal Server Error

**Comment by garfield69** [comment]
online.
updated indexer with new category changes, and burst guess for MR.
The categories do not look finalised yet, there is a documentaries:all as well as a tv:documentaries and there is still no clear rules or FAQ regarding H&R or MR / MST requirements.
But I may publish this TT3.0 indexer tomorrow regardless, and feed updates later.

**Comment by garfield69** [comment]
v0.20.865

**Comment by garfield69** [comment]
v0.20.868
