### ISSUE TITLE
[req]: MioBT - Public Anime Tracker -Chinese

### ISSUE THREAD

**Issue by Ayi1337** [Jackett/Jackett#13125]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: MioBT
- URL: https://miobt.com/
- Description: Public Chinese Anime Tracker
- Minimum Seeding Time and Minimum Ratio (if Private): No
- Additional Comments: 
RSS is available,https://miobt.com/rss.xml
See kisssub.yml
```

**Comment by garfield69** [comment]
this has the identical content to kisssub.org
its likely that miobt is the original and kisssub is the skinned clone
we should probably just rename kisssub to miobt and add the kisssub.org domain as an alternate sitelink.

**Comment by garfield69** [comment]
v0.20.818

**Comment by garfield69** [comment]
https://miobt.com/
```
Warning: mysqli_real_connect(): (HY000/1040): Too many connections in /www/wwwroot/miobt.com/include/library/adodb/drivers/adodb-mysqli.inc.php on line 124
Too many connections
```

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://miobt.com/ Timeout
17 of 43 uptime are up the rest are showing HTTP Timeout

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
site has a click me to continue frontend  generated by https://miobt.com/addon.php?r=document/view&page=visitor-test which saves a cookie `visitor_test=human`
