### ISSUE TITLE
[req]: ps4-torrent.ru

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#13136]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: ps4-torrent
- URL: http://ps4-torrent.ru/
- Description: ps4 game iso sharing
- Minimum Seeding Time and Minimum Ratio (if Private): public
- Additional Comments:
```

**Comment by garfield69** [comment]
rubbish
anytime I click on the download link of a result I get this page
![image](https://user-images.githubusercontent.com/6933240/162851647-1514d5ed-6ea1-47da-842f-c4c5fbf252f9.png)
there is no point adding this indexer to jackett.

**Comment by garfield69** [comment]
v0.20.860

**Comment by garfield69** [comment]
https://ps4-torrent.ru/ returns domain not found

**Comment by garfield69** [comment]
v0.20.1819
