### ISSUE TITLE
Problem on search on some indexer

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#1313]
Hi, I've installed the 0.7.1310.0 on a Qnap system.

In this example I'll compare the Jackett manual search and the real manual search directly on website of this 3 local site
Il Corsaro Nero
TNTVillage
ShareIsland

So I search this movie:
https://www.themoviedb.org/movie/10402
the movie title on my country is: deuce bigalow gigolò per sbaglio
I added the movie in Radarr, and Radarr logs say:
`Searching 9 indexers for [Deuce Bigalow - Gigolò per sbaglio]`

So, here my test results:

If I search:
deuce bigalow gigolò per sbaglio 1999
On Jackett manual search I've:
From Il Corsaro Nero I got: 0 results
From TNTVillage I got: 0 results
From ShareIsland I got: 0 results
On manual search directly from website I've:
From Il Corsaro Nero I got: 0 results
From TNTVillage I got: 0 results
From ShareIsland I got: 0 results

If I search:
deuce bigalow gigolo per sbaglio 1999
On Jackett manual search I've:
From Il Corsaro Nero I got: 0 results
From TNTVillage I got: 1 results
From ShareIsland I got: 0 results
On manual search directly from website I've:
From Il Corsaro Nero I got: 0 results
From TNTVillage I got: 1 results
From ShareIsland I got: 0 results

If I search:
deuce bigalow gigolò per sbaglio
On Jackett manual search I've:
From Il Corsaro Nero I got: 1 results
From TNTVillage I got: 0 results
From ShareIsland I got: 0 results
On manual search directly from website I've:
From Il Corsaro Nero I got: 1 results
From TNTVillage I got: 0 results
From ShareIsland I got: 0 results

If I search:
deuce bigalow gigolo per sbaglio
On Jackett manual search I've:
From Il Corsaro Nero I got: 1 results
From TNTVillage I got: 2 results
From ShareIsland I got: 0 results
On manual search directly from website I've:
From Il Corsaro Nero I got: 1 results
From TNTVillage I got: 2 results
From ShareIsland I got: 0 results

In the last example, the funny thinks is that the release found in TNTVillage, have the ò character in the name of the rel, but if the indexer search the ò character nothing is found, seems that the TNTVIllage don't support non standard character.

Then, is possible to exchange all non standard character during the searching phase?

Chry

**Comment by kaso17** [comment]
fixed via 91eb4c37cb88b0f4593f39d870b7ee15a5f20296

**Comment by Jorman** [comment]
Tnx @kaso17
