### ISSUE TITLE
animeitaly.org

### ISSUE THREAD

**Issue by Dhy19971** [Jackett/Jackett#13141]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: animeitaly
- URL: https://animeitaly.org/
- Description: 
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments:
```

**Comment by ilike2burnthing** [comment]
This site only supplies streaming links, not torrents.
