### ISSUE TITLE
[req]: Audiences

### ISSUE THREAD

**Issue by xztxy** [Jackett/Jackett#13156]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: audiences
- URL: https://audiences.me/
- Description: Movies TV  games music ebook ...
- Minimum Seeding Time and Minimum Ratio (if Private): 0.2
- Additional Comments: NexusPHP
```
Engine: Standard v1.5 Beta 4
MST 48h

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.

**Comment by xztxy** [comment]
sorry~,I have no&nbsp;invite. Wait for me to upgrade!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jackett/Jackett"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 下午3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jackett/Jackett] [req]: Audiences (Issue #13156)



 If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.

**Comment by xztxy** [comment]
I asked someone to send you an invitation.&nbsp;
Thank you!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jackett/Jackett"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 下午3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jackett/Jackett] [req]: Audiences (Issue #13156)



 If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.

**Comment by garfield69** [comment]
Registration and login completed. Thank you.
I see that I have to pass a newbie exam by uploading 68GB and collecting 5555 seed bonus.
That is not going to happen, I don't contribute to the scene. So I expect my account will expire in 30 days.
But that is fine by me, plenty of time to create the indexer and do the preliminary test.

**Comment by usherkobe** [comment]
Awesome work!Cheers

**Comment by garfield69** [comment]
Due to announcement 
```html
[ 2022.04.08 - 【重要通知】4月15日擇機關閉遊客訪問]
因特殊原因，不出意外本站將於4月15日擇機關閉遊客訪問，開放時間另行通知，届時請勿登出或清除瀏覽器cookie，否則您將無法登入本站
```
I will set up the indexer to access the site via the cookie method instead of the usual login page.

**Comment by garfield69** [comment]
v0.20.929

**Comment by xztxy** [comment]
> v0.20.929

Thank you so much！

**Comment by garfield69** [comment]
https://audiences.me/ returns Error 526 Invalid SSL certificate

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://audiences.me/ cloudflare Bad gateway Error code 502

**Comment by ilike2burnthing** [comment]
back up
