### ISSUE TITLE
Demonoid returns 0 results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13159]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
04-16 22:38:19 Info Starting Jackett v0.20.876 
04-16 22:38:23 Info Environment version: 6.0.4 (/app/Jackett/) 
04-16 22:38:23 Info OS version: Unix 5.15.32.8 (64bit OS) (64bit process) 
04-16 22:38:23 Info Jackett variant: CoreLinuxArm64 
04-16 22:38:23 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l 
04-16 22:38:23 Info Running in Docker: Yes (image build: v0.20.876-ls61) 
04-16 22:38:23 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
04-16 22:38:23 Info App config/log directory: /config/Jackett 
04-16 22:38:23 Info Using proxy: Disabled 
04-16 22:38:23 Info Using FlareSolverr: http://flaresolverr:8191 
04-16 22:38:23 Info Using HTTP Client: HttpWebClient2
```

### Description

I get 0 results from Demonoid tracker. I just grab the new cookie and same result.

### Logged Error Messages

```text
No errors
```

**Comment by garfield69** [comment]
The indexer is working for me, so this suggests the problem is with your cookie not being accepted by the site or some issue accessing the domain?

**Comment by garfield69** [comment]
Oh, and don't forget to cross check your **THEME** on your account. It has to be set to **_Demonoid - V5**
I have found it reset back to _Demonoid - v3_ in the past and had to switch back again.

**Comment by ngosang** [comment]
> Oh, and don't forget to cross check your THEME on your account. It has to be set to Demonoid - V5

That was. Thank you!
