### ISSUE TITLE
[req]: Adding tracker Hd-united to list of active trackers

### ISSUE THREAD

**Issue by colinborins** [Jackett/Jackett#13152]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Adding the following trackers to the list of trackers https://hd-united.vn/

### Describe the solution you'd like

Adding the tracker to the list of trackers

**Comment by colinborins** [comment]
Opened it with the proper channels

**Comment by garfield69** [comment]
please use https://github.com/Jackett/Jackett/issues/new?assignees=&labels=&template=indexer-request.yml&title=%5Breq%5D%3A+
