### ISSUE TITLE
[MoreThanTV] Season level searches failing

### ISSUE THREAD

**Issue by MrRobot12** [Jackett/Jackett#1315]
I originally posted this at Sonarr, but they told me this was a Jacket issue.

The full discussion has be found here...
https://github.com/Sonarr/Sonarr/issues/1876

There's really no point in me copy and pasting all the information here, so please read that thread and let me know if anything can be done to fix this. Thanks!

**Comment by kaso17** [comment]
a96b7cfca9102dd34f2434f0fd69907f233edd09 should fix it.
