### ISSUE TITLE
E-Hentai returns deleted torrents

### ISSUE THREAD

**Issue by Dark-Yox** [Jackett/Jackett#13154]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.22000.0 (64bit OS)
Environment version: 6.0.4 (C:\ProgramData\Jackett\)
Starting Jackett v0.20.868
```

### Description

Search for "Samunekochan" on E-Hentai tracker
Try downloading the torrent
Get HTTP ERROR 404

If you open the E-Hentai link you see the message "This gallery has been removed or is unavailable."

### Logged Error Messages

```text
Error downloading. indexer: ehentai path: https://e-hentai.org/gallerytorrents.php?gid=2136446&t=6535911c59&gtid=1095764
System.Exception: Download selectors didn't match
   at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1876
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in D:\a\1\s\src\Jackett.Server\Controllers\DownloadController.cs:line 56
```

### Screenshots

![image](https://user-images.githubusercontent.com/45209462/163651500-17dc2791-84fb-45de-9a2e-3ea8284e77ba.png)

![image](https://user-images.githubusercontent.com/45209462/163651472-e5ef737d-d4a9-4b05-8de2-fc511ec7e4c0.png)

**Comment by garfield69** [comment]
Unfortunately this web site does not have a download link for the torrent on the search page results, you have to first navigate to the torrents details page.
It also does not have any flag or indicator on the rows of each torrent found for whether the download is available or not in the corresponding details page of each torrent.
This means that to check if the DL link is available for torrents on the search page, Jackett would have to visit the details page of every torrent to check.
Potentially an additional 100 get requests, one for each torrent in the results page.
This is not practical, and in these days of heightened DDoS awareness, could lead to your IP being blocked.
I do not see that there is anything we can do about this issue for this site.
