### ISSUE TITLE
TeamHD - Sonarr - Season Pack not found

### ISSUE THREAD

**Issue by CooleRnax** [Jackett/Jackett#13158]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: unknown)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64	
OS version: Unix 5.4.0.1071 (64bit OS) (64bit process)
Environment version: 6.0.4 (/app/)
Jackett Data will be stored in: /config
Starting Jackett v0.20.876
```

### Description

I have TeamHD Torznab indexer connected via jakket to sonarr with very good library
The problem is that season packs releases are called “[Season x]” instead of “Sx”
I have created the same issue in sonarr, they redirected me here.

### Logged Error Messages

```text
Torznab search in TeamHD for Game of Thrones S01 => Found 0 releases
```

**Comment by garfield69** [comment]
v0.20.912
