### ISSUE TITLE
Aggregate torznab feed - Can't download

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#1316]
When trying to download the torrent, the request is made with /all instead of the tracker source aggregated.

http://192.168.1.116:9118/dl/all/(key)?path=(path)&file=Unbreakable.2000.MULTi.1080p.BluRay.x264.DTS-MUxHD.torrent
instead of 
http://192.168.1.116:9118/dl/t411/(key)?path=(path)&file=Unbreakable.2000.MULTi.1080p.BluRay.x264.DTS-MUxHD.torrent

Logic but it fails :)

**Comment by chibidev** [comment]
Thanks, @raspdealer, there seems to be other issues as well. I'll post a patch to fix them.

**Comment by raspdealer** [comment]
Is that fox released?
I still have the issue with the last pre release.

**Comment by ajslater** [comment]
All these fixes, I think are all in the latest pre-release.
Sonarr will now connect to /all
Radarr refuses to connect:
`Rejected a request to AggregateSearch which does not support searching for movies.`

**Comment by chibidev** [comment]
@ajslater it will be fixed with #1333
