### ISSUE TITLE
Multiple Indexers Failing Due To Re-Captcha Request

### ISSUE THREAD

**Issue by Hossy** [Jackett/Jackett#1317]
Forgive me if I didn't see a previously provided solution.  I search the issues and Google in general and couldn't find a solution to solving this.

I'm new to using Jackett and just installed it today on Windows 7 x64 (running 0.7.1310.0).  The issue I have it that after I "successfully" add an indexer like KAT, TPB, and Torrentz2, the Test button shows a green checkmark.  However, when I click to test it (or test all), they fail.  The message "Test failed for torrentz2: Found no results while trying to browse this tracker" appears at the bottom of the web page.  The logs are very nondescript unless you enable enhanced logging.  However, after enabling enhanced logging, I can see that Cloudflare is presenting a CAPTCHA for a security check.

The first time I got this, I opened up the site in Chrome and, sure enough, there was the CAPTCHA.  I answered the CAPTCHA and was able to open the site, however, Jackett is still unable to do so.  Then, I tried hitting the specific URL Jackett was hitting (indicated by the GetString log line) in Chrome.  Chrome pulled it right up, but Jackett is still getting a CAPTCHA request.

[20170430-jackett-log.txt](https://github.com/Jackett/Jackett/files/966841/20170430-jackett-log.txt)

**Comment by flightlevel** [comment]
Are you connecting to Jackett via 127.0.01 ?
This might be it ??? https://github.com/Jackett/Jackett/wiki/Remote-access-via-proxy

**Comment by Hossy** [comment]
Yes

**Comment by flightlevel** [comment]
What country are you connecting from and can you try access via a different public IP address. I wonder if Cloudflare has flagged your IP. Most people aren't getting captchas on TPB KAT as far as I know

**Comment by Hossy** [comment]
Canada.  Currently, the issue seems to have subsided -- I'm not longer getting a CAPTCHA and Jackett is working properly.  However, Jackett is doing something differently from the local browser that is causing browser-answered CAPTCHA to not apply to Jackett web requests.

**Comment by Hossy** [comment]
@kaso17 Why did you close this issue?  Even though I'm not currently having the issue, the problem I'm reporting in that resolving a CAPTCHA in my web browser is not carrying over to Jackett.  I suspect Jackett is accessing sites differently or not using cookies from the browser created by validating a CAPTCHA request.

**Comment by kaso17** [comment]
the recaptchas are bound to IP+user agent+session ID. Session ID changes every time you've to do the captcha, there's no easy way to sync the browser clearance cookies to jackett.

**Comment by Hossy** [comment]
Ok, so it sounds like configuring Jackett to use an HTTP proxy wouldn't help then either.  Thinking about this... what about making Jackett a proxy and having it save/reuse the session ID for future connections (i.e. like never closing your browser tab)?  I could point my browser to the Jackett proxy, resolve the CAPTCHA, and Jackett would be able to function, for a while at least.

**Comment by kaso17** [comment]
Adding proxy server functionality is considered as part of #1026

**Comment by kaso17** [comment]
I had the idea you're describing before already (to deal with trackers which support only a single login session). Unfortunately the big downside is that it won't work with HTTPS trackers. To intercept the cookies from an HTTPS tracker jackett would have to use a self signed root CA to generate new certificates. As I hate such SSL intercepting "firewalls" I probably not going to implement it. There's a big discussion about such behavior going on currently. In the end the browser vendors might block such SSL intercepting proxies.

**Comment by Hossy** [comment]
Well, crap.  Ya, good point.  Didn't think about that.  At least HTTP would work, but so many sites are going HTTPS, HTTP is getting scarce.  Thanks for the feedback, @kaso17.

**Comment by Hossy** [comment]
My understanding of Jackett is the (maybe) week I've used it now is that you are HTML scraping when adding an indexer for anything Jackett might need from me.  Is it possible to extend that functionality to recognize CloudFlare CAPTCHAs?
