### ISSUE TITLE
[erai-raws] Challenge detected but FlareSolverr is not configured (Config)

### ISSUE THREAD

**Issue by opaku** [Jackett/Jackett#13183]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
.
```

### Description

Not working. ErayRaws is now privet

### Logged Error Messages

```text
.
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
