### ISSUE TITLE
[Speedapp] incorrect results returned

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#13188]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
docker container.
 Jackett Version v0.20.929
```

### Description

some search on speedapp return non matching results.

For example in the screenshot below i searched "Halo S01E05 1080p" but got results for things that dont contain S01E05 1080p e.g "Halo.S01E03.720p.WEB.h264-KOGi"

If i do the same search from the site itself i get the correct result.

Please note in the screenshot from web shows the episode "Halo.S01E05.1080p.WEB-DL.DD+.5.1.H.264-CAKES" which was uploaded a few seconds after the jackett search so its correct that its missing from the jackett search but doesnt explain why jackett returns not matching results.

### Logged Error Messages

```text
2022-04-21 08:13:25.7015 Info Manual search in SpeedApp for Halo  1080p S01E05 => Found 14 releases
```

**Comment by swannie-eire** [comment]
seems like this is an issue on there end if there are no matching results they return invalid results.

**Comment by swannie-eire** [comment]
> We could add an andmatch filter to the rows selector, which would ensure only titles that contains all the keywords are returned. I'll have to do some research and testing first to ensure there are not adverse effects. Let me know if you think this is worth the bother by re-opening the ticket and requesting research.

as the issue is on the site side i wouldnt boder until i know they are not going to fix it. I opened a ticket with speedapp and will reopen if they dont fix.

Thanks

**Comment by swannie-eire** [comment]
@garfield69 
Speedapp got back to me and it looks like this is by design. here is there response.

"The relevant results are at the top. The site returns you more by breaking down what you search and showing you in descending order by relevance. It's a new upgrade from 2-3 weeks, and it's still being worked on to fix some unwanted results. "

If its not too much work would appreciate if you added that match filter you mentioned.

**Comment by garfield69** [comment]
v0.20.933
