### ISSUE TITLE
Is this a torrent search engine like BTDigg?

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [Jackett/Jackett#13187]
I asked if [there is a torrent search engine with more options than BTDigg](https://lemmy.ml/post/238391) and I was told to try jackett. But it seems this is some middleware for sonarr and radarr. I don't know how to use it as a search engine. I want to search torrents with more filters like age<1 year, size>1 gb, files between 10 and 100. And combine those kind of filters. Is this what I'm looking for? If so where can I find the docs? I didn't see anything about advanced search in the wiki.

**Comment by garfield69** [comment]
I do not think Jackett is the tool you are looking for.

Once you have activated the indexers for which ever web sites Jackett provides indexers for, there are two ways to interact with Jackett, 
a) via the Jackett dashboard search GUI which provides a simple text base torrent name search, and
b) via other apps (such as Sonarr, Radarr, et. al. ) that can use the Jackett torznab api to make queries of the indexers and with the returned results apply their own filtering options over the top.

I'm not familiar with all the apps out there so I can't speak to whether any provide all the filters that you are looking for.
