### ISSUE TITLE
Torrenting.com tracker not working

### ISSUE THREAD

**Issue by neuman1812** [Jackett/Jackett#1319]
Jackett Version 0.7.1310.0
Mono JIT compiler version 4.8.1 (Stable 4.8.1.0/22a39d7 Wed Apr 12 12:47:01 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  armel,vfp+hard
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

Running Pi3. Ubuntu 16.04
-------------------------------
Trying to add the torrenting.com tracker 

log:

05-01 09:13:55 Error got NotImplemented/InternalServerError 
05-01 09:13:55 Error request.Method: GET 
05-01 09:13:55 Error request.Url: https://torrenting.com/login.php 
05-01 09:13:55 Error request.Cookies:  
05-01 09:13:55 Error request.Referer: https://torrenting.com/ 
05-01 09:13:55 Error request.RawPOSTDdata:  
05-01 09:13:55 Error cookies:  
05-01 09:13:55 Error headerString:

**Comment by kaso17** [comment]
please post the output of  "curl -v https://torrenting.com/login.php"

**Comment by neuman1812** [comment]
Resolved today.  I just tried it again, added the cookie based on the instructions here https://github.com/Jackett/Jackett/wiki/Finding-cookies,  and it works now.  I think it may have been an issue with my VPN.  

>
2017-05-08 07:46:43.5572 Info Found 35 releases from Torrenting
