### ISSUE TITLE
CardigannIndexer (swarmazon): Error while parsing row

### ISSUE THREAD

**Issue by protocolprowler** [Jackett/Jackett#13201]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/*********/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 20.04.3 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.4.0.107 (64bit OS) (64bit process)
Environment version: 6.0.4 (/home/protocolprowler/Jackett/)
Starting Jackett v0.20.961
```

### Description

Jackett Support-

Please review the category translations between the site and Jackett. Loads of content is being missed during Jackett searches. Also I have attached one of the errors in the logs, please let me know if there is anything else I can do to help. 

Examples of some categories being missed:
Movie-Bluray 
TV-Season

Examples of some categories working:
TV-WEB-DL
TV

Below is the sites internal category and types master list. 

id 	categoryname 	
1 	Movies 	
2 	Television 	
3 	Video Courses 
4 	Music 	
5 	Games 
6 	Software 	
7 	Anime 	
8 	E-Books 	
9 	Audio Books 	
10 	Comics 	

id   catid   type
1 	1 	WEB-DL 	
2 	1 	DVD 	
3 	1 	Bluray 
4 	1 	Boxset 	
5 	2 	Episode 	
6 	2 	Season 	
7 	2 	Documentary 	
8 	3 	Technology 	
9 	3 	Art 	
10 	3 	Cooking 
11 	3 	Music 
12 	3 	Business 	
45 	3 	Skill 
13 	4 	Audio 	
14 	4 	Collection 	
15 	4 	Video 
16 	4 	Podcast 	
17 	5 	Windows 
18 	5 	Apple 	
19 	5 	Linux 
20 	5 	Nintendo 
21 	5 	Playstation 
22 	5 	Xbox 
46 	5 	Andriod	
23 	6 	Windows 
24 	6 	Apple 
25 	6 	Linux 
26 	6 	Android 
27 	7 	Shounen 
28 	7 	Seinen 
29 	7 	Shoujo 
30 	7 	Josei 
31 	7 	Kodomo 
47 	7 	Mina 
32 	8 	Novel 
33 	8 	Short Story 	
34 	8 	Informative 
35 	9 	Novel 
36 	9 	Short Story 
37 	9 	Informative 
38 	10 	Superhero 
39 	10 	Manga 
40 	10 	Slice-of-Life 
41 	10 	Humor 
42 	10 	Fantasy 
43 	10 	Horror  

Thanks in advance for your time and help on this matter. 

### Logged Error Messages

```text
2022-04-26 00:27:45 	Error 	

CardigannIndexer (swarmazon): Error while parsing row '
<tr>
	<td>
		<div class="row text-center min-width-70">
			<img src="images/icons/BLURAY-ALT.svg" width="40" height="25">
			<br>
			<span style="font-size: 85%;">
				Bluray
			</span>
		</div>
	</td>
	<td class="Name" data-label="Name">
		<a href="en/view/torrent.php?hash=bed7735f62f824610a3c1ec4f1118d934f0e6ee0&amp;id=660" onmouseover=" return overlib('<img src=https://m.media-amazon.com/images/M/MV5BMTI2NTU2Nzc0MV5BMl5BanBnXkFtZTcwMzY1OTM2MQ@@._V1_SX300.jpg width=200 border=0>', DELAY, 250, CENTER, VAUTO);" onmouseout="return nd();">Natural Born Killers 1994 DC 1080p BluRay REMUX VC-1 TrueHD 5.1-FraMeSToR</a>
		<br>
		<small>by
			<a href="/en/view/user-torrents.php?userid=660">0z00z0</a>
			<img src="/css/staff.png" alt="Staff Member">
			in
			<a href="en/view/category.php?id=1">Movies</a><span class="fas fa-film"></span><span class="badge" style="color:black;background-color:#FF8000;font-size:9px;">Freeleech</span><span class="badge" style="color:black;background-color:#00FF00;font-size:9px;">Seeding</span><span class="badge" style="color:black;background-color:#FF3333;font-size:9px;">Downloaded</span>
			<span class="badge" style="color:black;background-color:#00FFFF;font-size:9px;"></span>
		</small>
	</td>
	<td data-label="Size">19.72 GB</td>
	<td data-label="Age">2022-04-15 01:33:00</td>
	<td data-label="Leech">3</td>
	<td data-label="Seeds" style="color:#00FF00;">4</td>
	<td data-label="Leech" style="color:#FF3333;">0</td>
	<td data-label="&nbsp;">
		<a href="/api/download.php?hash=bed7735f62f824610a3c1ec4f1118d934f0e6ee0&amp;torrent_pass=000000000000000000000000000000000000">
			<button type="button" class="btn btn-default btn-sm">
				<span class="glyphicon glyphicon-download-alt"></span>
				<b>&nbsp;Download</b>
			</button>
		</a>
	</td>
</tr>':

System.Exception: Error while parsing field=categorydesc, selector=td.Name small, value=Movies  
												  
												  Seeding
												  Downloaded: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1603
```

### Screenshots

![firefox_TLil1Pmx3C](https://user-images.githubusercontent.com/6018001/165254779-32755c62-1107-432b-960b-4c2527f211d8.png)

**Comment by garfield69** [comment]
@ilike2burnthing  this is your mess from 5b4df4a6d9a156164a1c0460093bf661fee91836 ;-b

**Comment by ilike2burnthing** [comment]
The badges are causing the issue, easily resolved.

Before I do so though, are there any other badges apart from:
`Freeleech`
`Seeding`
`Downloaded`
`Leeching`
?

**Comment by protocolprowler** [comment]
Interesting. Once you find it...it's always something simple. 

Nope, those are all four status badges in use. Would it be hopeful for us to hide stop and start characters for Jackett in comments? 

Also, there is an API in development for this site so we'll have better options for integrations soon. ;-)

**Comment by ilike2burnthing** [comment]
No, that's fine as it is.

Give us a shout when you release the API and we'll switch over to it.

**Comment by garfield69** [comment]
v0.20.970

**Comment by protocolprowler** [comment]
As always you guys are amazing! Thank again and keep up the great work.
