### ISSUE TITLE
bB: shutting down - May

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#13211]
>There is no easy way to say it, this site has been struggling since the great robot uprising nuked half our torrents. We've kept the lights on since then, but morale has been flagging, user and upload counts have never recovered, and developer bandwidth (hi that's me) has been minimal. Many of us staff have moved on to focus on other things, and unfortunately the time has come when it's clear that life support is the best we'll be able to manage. We don't want you to remember us like this, but nonetheless it's time to pull the plug.
>
>So after over a decade of torrenting pleasure, the time has come to say goodbye. In early May, baconBits will permanently shut down. Much love to everyone who's worked to make this possible over the years. From admins and devs to helpers and mods, uploaders, seeders and leechers alike, thank you all for everything you've done here.
>
>In the meantime we've activated global freeleech so you can grab a copy of anything you'll miss.
>
>Please feel free to share your favorite baconBits memories below, scream into the void, or just drop in to say hi one last time 🙂
>
>(PS please do not offer money or services, we wouldn't be here if there were a succession plan we could get behind. We're not broke and we can't hand things over to random community members, although we appreciate the thought.)

http://torrentinvites.org/f31/baconbits-news-603621/

https://baconbits.org/

**Comment by ilike2burnthing** [comment]
Now showing - `Database error.`

I'd say if it's not back up in time for our May 1st release, just remove it.

**Comment by garfield69** [comment]
v0.20.993

**Comment by mueslo** [comment]
please revert, it is currently not yet gone.

**Comment by ilike2burnthing** [comment]
I'm still just getting `database error`. Is that only for those not logged in?

**Comment by mueslo** [comment]
> I'm still just getting `database error`. Is that only for those not logged in?

Website works fine for me, login form is also there without a session cookie, I don't see this database error you mention

**Comment by ilike2burnthing** [comment]
Apologies, an extension which hadn't caused an issue before now was.

**Comment by garfield69** [comment]
v0.20.1024

**Comment by mueslo** [comment]
it is time

**Comment by garfield69** [comment]
v0.20.1066
