### ISSUE TITLE
[req]: Jackett for i386

### ISSUE THREAD

**Issue by Newbaatt** [Jackett/Jackett#13219]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Can't install Jackett on Debian 11 under i386 architecture

### Describe the solution you'd like

Is there a way to install or build Jackett for the i386 architecture?

**Comment by ilike2burnthing** [comment]
@garfield69 / @ngosang as far as I can see there has never been an x86 Linux build, any reason for this?

**Comment by garfield69** [comment]
>any reason for this?

IMO we don't build packages for every flavour of every platform, just a few core platforms.
pipelines takes long enough as it is to update for a change.
Go down that path, and we will be building (and having to support) every platform variation, and pipelines will take hours to run and exceed out free alotment.
Docker supports most other machines we don't build for, and user can always compile from source for the other flavours.

**Comment by ilike2burnthing** [comment]
@Newbaatt unlike a new platform (e.g. Mac ARM64) where we added support for new users, Linux x86 is fairly long in the tooth and this seems to be the only request for it in the last 7 years.

If you wish to build it yourself, make the necessary changes to https://github.com/Jackett/Jackett#linux
