### ISSUE TITLE
[Xthor] Issues finding releases

### ISSUE THREAD

**Issue by GregTroar** [Jackett/Jackett#13220]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.x.21:8191
Using proxy: Disabled
App config/log directory: /home/user/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Debian GNU/Linux 11 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.0.13 (64bit OS) (64bit process)
Environment version: 6.0.4 (/opt/Jackett/)
Starting Jackett v0.20.993
```

### Description

Currently when searching for a movie with Jackett on Xthor, Jackett will use the URL: https://api.xthor.tk/?passkey=xxxxxx&category=&search=&tmdbid=&freeleech=

the fact that &freeleech= is in the search URL will return only the freeleech movies no matter if it is &freeleech= or &freeleech=1 or &freeleech=0, due to this most of the movies are not found.

Just removing the &freeleech from the search url resolve the issue. (this works perfectly https://api.xthor.tk/?passkey=xxxxxx&category=&search=&tmdbid=)

How can I solve this ?

Thanks

### Logged Error Messages

```text
No error message
```

**Comment by garfield69** [comment]
>How can I solve this ?

by recoding the indexer to have to parms on the path statement instead of the input block.
I'll code a fix shortly.

**Comment by garfield69** [comment]
v0.20.1001

**Comment by GregTroar** [comment]
Awesome gonna try right away thanks for very fast reply
