### ISSUE TITLE
[btschool] (updating) Login failed: Selector "a[href="logout.php"]" didn't match

### ISSUE THREAD

**Issue by cikichen** [Jackett/Jackett#13228]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
05-07 15:42:37 Info Starting Jackett v0.20.1024 
05-07 15:42:39 Info Environment version: 6.0.4 (/app/Jackett/) 
05-07 15:42:39 Info OS version: Unix 5.10.60.0 (64bit OS) (64bit process) 
05-07 15:42:39 Info Jackett variant: CoreLinuxAmdx64 
05-07 15:42:39 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l 
05-07 15:42:39 Info Running in Docker: Yes (image build: v0.20.1024-ls64) 
05-07 15:42:39 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
05-07 15:42:39 Info App config/log directory: /config/Jackett 
05-07 15:42:39 Info Using proxy: Disabled 
05-07 15:42:39 Info Using FlareSolverr: No 
05-07 15:42:39 Info Using HTTP Client: HttpWebClient2
```

### Description

An error occurred while updating this indexer
Login failed: Selector "a[href="logout.php"]" didn't match

### Logged Error Messages

```text
An error occurred while updating this indexer
Login failed: Selector "a[href="logout.php"]" didn't match
Click here to open an issue on GitHub for this indexer.
```

**Comment by ilike2burnthing** [comment]
Pull a new cookie and reconfigure the indexer with it.

If that doesn't work, see the troubleshooting steps here:
https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work
and
https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-selector

**Comment by cikichen** [comment]
When I reopen it works fine

**Comment by yangchris4** [comment]
> When I reopen it works fine

什么意思？重启jackett吗？还是什么，我也出现这个问题了

**Comment by ilike2burnthing** [comment]
Did the steps in https://github.com/Jackett/Jackett/issues/13228#issuecomment-1120232516 not help? If not, open a new issue and provide the information requested.
