### ISSUE TITLE
Request for new Indexer for https://elifilms.net/

### ISSUE THREAD

**Issue by patbowling89** [Jackett/Jackett#13221]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Elifilms
- URL: https://elifilms.net/
- Description: Elifilms is a Public Site for Movies
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: This is a public site which has several movies (English and Latino languajes) available under torrent magnet url.
Magnet link is base64 encoded for some reason.
```

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
