### ISSUE TITLE
[req]: https://zimuku.org/

### ISSUE THREAD

**Issue by ljnandy** [Jackett/Jackett#13230]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: zimuku
- URL: https://zimuku.org/
- Description: A useful subtitle website
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: 
https://subhd.tv/ is also great but needs to use WeChat
```

**Comment by ilike2burnthing** [comment]
Unless I'm losing something in translation, there are no torrents, just subs.
