### ISSUE TITLE
[req]:pruc.org russian adult torrent

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#13231]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: pruc.org
- URL: http://pruc.org/
- Description: have all porn categories
- Minimum Seeding Time and Minimum Ratio (if Private): it haven't ratio semi-private
- Additional Comments: Russian semi-private(must register) adult torrent content share site. Search engine and torrent working.
```

**Comment by berat1397** [comment]
![resim](https://user-images.githubusercontent.com/36575395/167271111-870e77ca-f1c7-4456-9739-67be38412e3a.png)
![resim](https://user-images.githubusercontent.com/36575395/167271120-3d6bdd88-0587-4ca3-a6be-540aa2da558c.png)
![resim](https://user-images.githubusercontent.com/36575395/167271127-16bdbd56-d3e7-4114-81fb-747df4d1779f.png)

**Comment by garfield69** [comment]
Enough of these Russian 3x sites, we have 17 of these already!

**Comment by saw1543** [comment]
Hi Why dont add this site. I check it. İt have best content. I use jackett for game, movie and adult contents.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/13231#issuecomment-1120317583

**Comment by saw1543** [comment]
> Enough of these Russian 3x sites, we have 17 of these already!

Best site for jackett. Site have good content. You need check it. You see. Every day sharing new torrent like rarbg or pornolab. We need this site. Russians best on this job. They have best torrent website. rutracker, pornolab. uniondht, kinozal.

Pls give it chance.

**Comment by saw1543** [comment]
![resim](https://user-images.githubusercontent.com/107757665/174477234-5c5e6108-6819-433b-88d8-b71d8b15fa81.png)
İt have good seeder 
I wanna see pruc.org in jackett.

**Comment by ilike2burnthing** [comment]
PRs are open to everyone
