### ISSUE TITLE
[req]: Subs language in release for Erai Raws tracker

### ISSUE THREAD

**Issue by bonny1992** [Jackett/Jackett#13234]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Is it possible to have in the title of the release the language of the subtitles?

As it is right now it's `XXXXXX- 06 [1080p][Multiple Subtiles]` (I'm going by memory here), but from the RSS feed it's `[Torrent] XXXXXX- 06 [1080p][us][br][mx][es][sa][fr][de][it][ru][Airing]`. There is also a `erai:subtitles` xml tag.

Would it be possible? In this way Sonarr or Radarr would manage to understand the language of the release and download them automatically.

Thank you!

### Describe the solution you'd like

Having the title of the release with the subs language included.

### Describe alternatives you've considered

I considered asking Erai directly but I can see from their RSS feed that that's already what they have been doing.

**Comment by ilike2burnthing** [comment]
As far as I'm aware Sonarr/Radarr want the language of the audio, not the subs. I'm also not sure how they'd react to 7 different language codes, instead of the 1 expected.

If you can explain how this would work I'll take another look.

**Comment by bonny1992** [comment]
If it wants the language of the audio then it's wrong anyway because Sonarr and Radarr are seeing the releases as English, where the audio language is Japanese.

As for the multiple language usually I saw (mostly Radarr) identify the release with more than one language in the title as "Multi-language".

**Comment by ilike2burnthing** [comment]
Is every release's audio in Japanese? If so, then we could add that to the title.

**Comment by bonny1992** [comment]
I think mostly are in Japanese. They take multiple subs and mux them into a single raw episode which usually is in Japanese, yes.

Can't we put for example "JAP - Sub EN-FR etc" like other releases from other trackers?

**Comment by ilike2burnthing** [comment]
@6cUbi57z can you try to implement this as an optional setting?

**Comment by garfield69** [comment]
original:
![image](https://user-images.githubusercontent.com/6933240/167528247-23ba5f5d-f4fe-4880-bf47-95e5c99a32b0.png)

with subs enabled:
![image](https://user-images.githubusercontent.com/6933240/167528017-1c4f6e1d-f725-4b64-ac56-a4098e0ec7b1.png)

is this what you were looking for?

**Comment by bonny1992** [comment]
Yes, that is what I was looking for.

More in line with the original naming plus now Radarr and Sonarr could understand better the language of the file, if it's capable of doing that. Or at least I can download manually from Sonarr or Radarr's download page without having to search from their website directly for the release.

**Comment by garfield69** [comment]
v0.20.1043

**Comment by bonny1992** [comment]
That was fast. Thank you all :)
