### ISSUE TITLE
[req]: Search Freeleech Only option for HDBits

### ISSUE THREAD

**Issue by leonard4546** [Jackett/Jackett#13244]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

is it possible to add Search Freeleech Only option for HDBits like some other trackers.

### Describe the solution you'd like

HDB has multiple freeleech types. like 25 % Free, 50 % free and 100 % Free. so an option to search only 100 % freeleech torrents.

**Comment by ilike2burnthing** [comment]
None of the active maintainers have an account for HDBits. Does the search page have an option for searching by freeleech?

If so, please provide an HTML dump of the search page - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

If not, we can filter results for those which are freeleech.

**Comment by ilike2burnthing** [comment]
jacketttest [at] gmail [dot] com

**Comment by garfield69** [comment]
A pity we don't have an invite so we could improve the HDbitsAPI C# indexer with the freeleech search/filter and whatever else may be missing.

**Comment by garfield69** [comment]
v0.20.1088

**Comment by leonard4546** [comment]
> v0.20.1088

hey, is it possible to add this search freeleech feature for HDBits (API) Indexer? Normal indexer isn't working for me.

**Comment by garfield69** [comment]
Possibly. But to research we need access to an account so we can code and test and so forth.
One option is to send an invite to garfieldsixtynine -at- gmail.com 
Another is to let me borrow an account for the duration of the research.
A third option is to wait for a volunteer such as @jyggen or @ngosang  to contribute, but I don't know how soon they can respond and provide a solve.
Let me know how you want to proceed.

**Comment by jyggen** [comment]
There's no way to specify freeleech only as a request parameter. The response has a `freeleech` string field though that can either be `yes` or `no`, so that's probably what you want to filter on.

**Comment by garfield69** [comment]
well that's consistent with the html scraping indexer hdbits which uses a `Filter FreeLeech only` post search filter rather than the `Search Freeleech only` search query.
Can you code up a PR for the hdbitsapi indexer?
