### ISSUE TITLE
[req]: BTmirror

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13257]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: BTmirror
- URL: https://btsao.com/
- Description: BTmirror is a Public BitTorrent DHT search engine.
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments:
  proxy: https://btmirror.unblockit.blue/
```

**Comment by garfield69** [comment]
v0.20.1117

**Comment by ilike2burnthing** [comment]
https://btsao.com/ - Error 504 - Gateway time-out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://btsao.com/ returns Error 504 Gateway time-out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://btsao.com/ - Connection timed out - Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://btsao.com/ - Bad gateway - Error code 502

**Comment by garfield69** [comment]
v0.20.2142
