### ISSUE TITLE
[enhancement] update HDChina indexer to include Subheading

### ISSUE THREAD

**Issue by PaavoChung** [Jackett/Jackett#13255]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
docker
```

### Description

HDChina Search cannot return Subheading
![907BD0F3-7C84-403C-947D-9F2DA4B0884F](https://user-images.githubusercontent.com/12683956/170175021-1110ff7f-ad13-4890-8606-c1b34a58e865.jpeg)

### Logged Error Messages

```text
none
```

### Screenshots

![4915BAB4-3D9D-4E57-9CCF-EE808DBCE352](https://user-images.githubusercontent.com/12683956/170174808-549bae2d-53b7-4273-be6d-cb23dccb6b84.jpeg)

**Comment by garfield69** [comment]
I do not understand what you are reporting.
The indexer does not fetch data from the torrent details page.
The results that Jackett presents are from the primary torrent search page.
Can you explain in more detail what it is that you think Jackett should be extracting from the search page that it is not already doing?
Thanks.

**Comment by PaavoChung** [comment]
I think we should return the information with a subtitle so that I can choose the corresponding torrent to download.thanks
![11EA9A4B-5F51-44D2-8F72-3D236B0A138D](https://user-images.githubusercontent.com/12683956/170194552-b183d05e-7557-47cd-9c76-d466ce8df839.png)
![6DA6841C-4364-45DA-8B86-F5746C7FD083](https://user-images.githubusercontent.com/12683956/170194571-ccdb7a62-6b9e-4a6e-97ed-e5803b04a80a.png)
![EC7CD72F-FAFE-4A28-8BF6-D0FB4A75EDB7](https://user-images.githubusercontent.com/12683956/170194591-7656bbfb-91a8-4001-8f80-271212a0f698.png)

**Comment by garfield69** [comment]
Ahh, I understand.
Unfortunately none of the current team members have an account on HDChina so we cannot update and test the indexer independently.
The best option would be if you could send an invite to garfieldsixtynine -at- gmail.com I will update the indexer.
An alternate option is for you to post the HTML from the torrent search page `https://hdchina.org/torrents.php`, and the aboutnexus.php page `https://hdchina.org/aboutnexes.php`. I should be able to update the indexer, but it will be untested so may contain errors.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source for details.

**Comment by ilike2burnthing** [comment]
Yes, send it to that email address or post it here.

**Comment by PaavoChung** [comment]
Email has been sent, please check, thank you

**Comment by garfield69** [comment]
Next release of Jackett due out in about 10 hours or so will include the updated indexer. Let me know if it works or not.

**Comment by garfield69** [comment]
v0.20.1104

**Comment by PaavoChung** [comment]
Is working. Thank you very much.
