### ISSUE TITLE
[yggtorrent] (updating) The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject]  CN=*.yggtorrent.la[Issuer]  CN=E1, O=Let's Encrypt, C=US[Serial Number]  04C9888FB520E429EA08D3EDBCF49E47A9D6[Not Before]  4/10/2022 12:09:11 AM[Not After]  7/9/2022 12:09:10 AM[Thumbprint]  BBA50336008EE4BC04A59E1833CB1CC00525332F

### ISSUE THREAD

**Issue by Jiel62** [Jackett/Jackett#13269]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-05-30 22:39:17	Info	Using HTTP Client: HttpWebClient2
2022-05-30 22:39:17	Info	Using FlareSolverr: http://192.168.10.231:8191/
2022-05-30 22:39:17	Info	Using proxy: Disabled
2022-05-30 22:39:17	Info	App config/log directory: /volume1/@appstore/jackett/var/.config/Jackett
2022-05-30 22:39:17	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-05-30 22:39:17	Info	Running in Docker: No
2022-05-30 22:39:17	Info	Jackett variant: CoreLinuxAmdx64
2022-05-30 22:39:17	Info	OS version: Unix 4.4.59.0 (64bit OS) (64bit process)
2022-05-30 22:39:17	Info	Environment version: 6.0.5 (/volume1/@appstore/jackett/share/)
2022-05-30 22:39:09	Info	Starting Jackett v0.20.1120
```

### Description

Hello,
Since the change of domain of the site yggtorrent.la, the addition of the indexer is impossible
The error message talks about let's encrypt certificate.

Jackett is installed on a Xpenology version 6.2.3
Mono is in version 5.20.1.34-16

Thanks for your help

### Logged Error Messages

```text
An error occurred while updating this indexer
The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject] CN=*.yggtorrent.la [Issuer] CN=E1, O=Let's Encrypt, C=US [Serial Number] 04C9888FB520E429EA08D3EDBCF49E47A9D6 [Not Before] 4/10/2022 12:09:11 AM [Not After] 7/9/2022 12:09:10 AM [Thumbprint] BBA50336008EE4BC04A59E1833CB1CC00525332F
```

**Comment by ilike2burnthing** [comment]
Are you able to use Docker? If so, switch Jackett over to it (and if you're using Sonarr et al, then them too).

**Comment by ilike2burnthing** [comment]
@Luttymix if you're using https://www5.yggtorrent.la/ as the sitelink, you can access it in browser from the same device and IP address, while using the same DNS, and you cannot resolve your issue with the troubleshooting steps [here](https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed), then open a new issue, providing the information requested.

**Comment by garfield69** [comment]
@Jiel62  you ar enot using the mono variant of Jackett so this is not an issue with the R3 CA versus Mono's inability to handle let's encrypt certificates.
You are on the CoreLinuxAmdx64 which is .NET based.
Have you tried refreshing/updating your CA store?
If that does not work then as @ilike2burnthing  stated, switching to using Docker images is a good working alternative.
