### ISSUE TITLE
[req]: ygdy8

### ISSUE THREAD

**Issue by firstvip** [Jackett/Jackett#13265]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: ygdy8
- URL: https://www.ygdy8.net
- Description: ygdy8 is a Public Torrent Tracker for Movies, TV
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments:
```
Dependent on the answer to #13263

**Comment by ilike2burnthing** [comment]
Currently just getting `ERR_CONNECTION_TIMED_OUT` when trying to perform a search. 

I can't see a way to search for all results, only by individual categories. If that's not possible, this site won't be suitable for Jackett.

**Comment by firstvip** [comment]
Like this
http://s.ygdy8.com/plus/s.php?keyword=

**Comment by firstvip** [comment]
http://s.ygdy8.com/plus/s.php?keyword=good

**Comment by ilike2burnthing** [comment]
Is the search working for you? It's still just timing out for me.

**Comment by firstvip** [comment]
Thank you for your work.
Yes It works fine, maybe need to try again later.

**Comment by ilike2burnthing** [comment]
@garfield69 see if you have any better luck than me.

**Comment by garfield69** [comment]
>see if you have any better luck than me.

Same here. This is a purely Chinese site,  I suspect that it is going through the Chinese censorship firewall and the delay for non-regional users exceeds timeout limits.

**Comment by firstvip** [comment]
You can use the following website to get a temporary proxy, and just choose China for the country.
https://www.freeproxylists.net/

**Comment by garfield69** [comment]
this site is not suitable for indexing with Jackett. See https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
