### ISSUE TITLE
[req]: pixelados.tv

### ISSUE THREAD

**Issue by Nonii07** [Jackett/Jackett#13273]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Pixelados
- URL: https://pixelados.tv/
- Description: Pixelados is a Spanish Private Torrent Tracker for HD MOVIES / TV 
- Minimum Seeding Time and Minimum Ratio (if Private): 7 days
- Additional Comments: Invite required or application form
engine: Unit3d 6.1.0
```

**Comment by Nonii07** [comment]
invite is not posible, so if you need any other info feel free to ask me for them

regards

**Comment by garfield69** [comment]
Open registration appears to be closed, and is currently invitation only. No signs of an application form either.
`Registro libre cerrado. Se necesita una invitación para entrar. Has sido devuelto a la página inicial.`

If you are unable to provide an invite, then to progress this, you need to login to the web site, access the torrents page and dump the HTML.
IF you are correct that the site is using unit3d 6.1.0 then I should be able to use the HTML dump to build a standard u3d610 indexer.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by Nonii07** [comment]
i send you that info in to email

**Comment by garfield69** [comment]
Using which email address?   `garfieldsixtynine@gmail.com` ? 
Did you saved the HTML into a txt file and attached it, or did you paste the raw html into the email body?
IF the latter then its likely to be rejected. An attached file should be ok, in a zip file even better.
Nothing has arrived yet in any of my inboxes.

**Comment by Elinombrable** [comment]
@garfield69 i have sent you an HTML example from the tracker in .txt format to garfieldsixtynine@gmail.com since @Nonii07 didn't answer. I hope that it's what you needed. The tracker is clearly based on Unit3D but i could not find which version.

**Comment by garfield69** [comment]
@Elinombrable  I've received your email thank you.
however the file you have provided is not what I expected to see, it looks like it has been processed by some tool that modified the original HTML, which makes it very hard for me to read, and appears to be missing most of the stuff I am interested in :-(
Very confused.
Did you use a chrome browser to access the **torrents** page, and **right clicked** and selected **save as**, and added **.txt** to the filename before saving?

**Comment by Elinombrable** [comment]
@garfield69 i just sent you a new mail with the file downloaded from Firefox. Previously i used Edge and seems like it did something weird. Hopefully now it's better.

**Comment by garfield69** [comment]
The next release of Jackett due out in about 10 hours or so will include the new indexer.
If there are any problems please raise a fresh ticket and include an enhanced log. Thanks.

**Comment by garfield69** [comment]
v0.20.1144

**Comment by garfield69** [comment]
v0.20.2916
