### ISSUE TITLE
[req]: yggtorrent

### ISSUE THREAD

**Issue by starnakin** [Jackett/Jackett#13279]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: yggtorrent
- URL: yggtorrent.nl
- Description: YGGTorrent is a FRENCH Semi-Private Torrent Tracker for 0DAY / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: ygg have change URL and now it is public
```

**Comment by ilike2burnthing** [comment]
yggtorrent.nl appears to be a poor clone of yggtorrent.la, I'd suggest just using that
