### ISSUE TITLE
Kickass Torrents - Category's Fail With Sonarr

### ISSUE THREAD

**Issue by ForgottenSpecialist** [Jackett/Jackett#1327]
Hey,

So as of right now Kat works with Sonarr / Radarr using Jackett, Radarr works perfectly all movies picked up... When you search within jacket lets say "2 Broke Girls" search results show perfectly and show the category in this case TV/HD which is 5040 or even 100041 but both make sonarr unable to search / connect to the indexer..
Here is a working list of tv shows / movies ID's within Sonarr "2000,2020,2030,2040,2050,2070,100150,100128,100074,5050,5060,5070,5080,100146,100151,100007"

Any you get the "Testing (NAME) failed error with these 
"Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings."
100152, 100041, 100005, 5040, 5030

Like I say this seems to be down to the connection to Sonarr as searching for a torrent under these category's work within jackett but you get the above in the log when trying these.

**Comment by kaso17** [comment]
please provide a log with enhanced logging enabled.

**Comment by truckershitch** [comment]
This patch is working for me.  Your mileage may vary.  This addresses the errors I saw generated in the Jackett log when Sonarr tested the indexer.

```
--- kickasstorrent.yml.bak      2017-05-05 13:14:08.000000000 -0400
+++ kickasstorrent.yml  2017-05-05 20:23:45.525781267 -0400
@@ -68,7 +68,7 @@
       - {id: 153, cat: Other, desc: "Other - Wordpress"}
       - {id: 6, cat: TV/HD, desc: "TV - Blu-Ray Disc"}
       - {id: 7, cat: TV/Documentary, desc: "TV - Documentary"}
-      - {id: 5, cat: TV/SD, desc: "TV - DVD Disc"}
+      - {id: 5, cat: TV/SD, desc: "TV - DVD ISO"}
       - {id: 41, cat: TV/HD, desc: "TV - HD"}
       - {id: 151, cat: TV/Other, desc: "TV - Other"}
       - {id: 146, cat: TV/Sport, desc: "TV - Sport"}
@@ -164,7 +164,7 @@
           ":has(a:contains(\"Other\")):contains(\"Wordpress\")": 153
           ":has(a:contains(\"TV\")):contains(\"Blu-Ray Disc\")": 6
           ":has(a:contains(\"TV\")):contains(\"Documentary\")": 7
-          ":has(a:contains(\"TV\")):contains(\"DVD Disc\")": 5
+          ":has(a:contains(\"TV\")):contains(\"DVD ISO\")": 5
           ":has(a:contains(\"TV\")):contains(\"HD\")": 41
           ":has(a:contains(\"TV\")):contains(\"Other\")": 151
           ":has(a:contains(\"TV\")):contains(\"Sport\")": 146
```

**Comment by kaso17** [comment]
@truckershitch thank you, update the cats via 4dd49985c360f9275438bd51fcaf4af88ff8a83e

**Comment by ForgottenSpecialist** [comment]
Hey,

So i've just gone and re-installed to eliminate anything I may have screwed myself but now when I run a test on cat I get

"May 06, 2017 07:54:31 PM	Info	
Found 0 releases from KickAssTorrent
May 06, 2017 07:54:31 PM	Info	
CardigannIndexer (kickasstorrent): Relogin required
May 06, 2017 07:53:34 PM	Error	
Exception in test_indexer"

**Comment by ForgottenSpecialist** [comment]
The message I receive when trying to add indexer with Sonarr

"CardigannIndexer (kickasstorrent): Error while parsing row '<tr class="t-row"> <td class="ttable_col1" nowrap="nowrap">     <div class="iaconbox center floatright">         <a rel="17046" class="icommentjs kaButton smallButton rightButton" href="comments.php?type=torrent&amp;id=17046">0<i class="ka ka-comment">				</i>
			</a>          <a class="icon16" href="torrents-details.php?id=17046&amp;hit=1" title="Unverified Torrent">
				<i class="ka ka16 ka-unverify ka-lightgrey">				</i>
			</a>                    <a data-download="17046" title="Download torrent file" class="icon16" href="download.php?id=17046&amp;name=" onclick="javascript:return confirm('Confirm your download.')">
				<i class="ka ka16 ka-arrow-down">				</i>
			</a>     </div>     <div class="torrentname">          <div class="markeredBlock torType filmType">             <a href="torrents-details.php?id=17046&amp;hit=1" class="cellMainLink">Banshee Season 4 S04 720p BluRay x265 HEVC-MZABI</a>                  <span class="font11px lightgrey block">                 Posted by <i title="Uploader" class="ka ka-verify" style="font-size: 16px;color:lightgrey;">					</i>&nbsp;<a class="plain" href="account-details.php?id=2624">MZABI</a> in <span id="cat_12155145">
						<strong>
							<a href="torrents.php?parent_cat=TV">TV</a>  » Blu-Ray ISO                 </strong>
					</span>                           </span>            </div>     </div> </td>
	<td class="ttable_col2" align="center">4.37 GB</td> <td class="ttable_col1" align="center">15-01-2017 12:12:44</td>
	<td class="ttable_col2" align="center">
		<font color="green">2</font>
	</td> <td class="ttable_col1" align="center">
		<font color="#ff0000">30</font>
	</td> </tr>':

System.Exception: Error while parsing field=category, selector=span[id^="cat_"], value=<null>: None of the case selectors "[:has(a:contains("Anime")):contains("English Translated"), 118],[:has(a:contains("Anime")):contains("Other"), 133],[:has(a:contains("Applications")):contains("Handheld"), 144],[:has(a:contains("Applications")):contains("Linux"), 142],[:has(a:contains("Applications")):contains("Mac"), 140],[:has(a:contains("Applications")):contains("Other"), 131],[:has(a:contains("Applications")):contains("Windows"), 139],[:has(a:contains("Books")):contains("Audio books"), 109],[:has(a:contains("Books")):contains("Biography"), 110],[:has(a:contains("Books")):contains("Children"), 102],[:has(a:contains("Books")):contains("Comics"), 103],[:has(a:contains("Books")):contains("Computers &amp; Technology"), 113],[:has(a:contains("Books")):contains("Cooking"), 115],[:has(a:contains("Books")):contains("Educational"), 114],[:has(a:contains("Books")):contains("Fiction"), 107],[:has(a:contains("Books")):contains("History"), 112],[:has(a:contains("Books")):contains("Magazines"), 105],[:has(a:contains("Books")):contains("Manga"), 104],[:has(a:contains("Books")):contains("Non-fiction"), 108],[:has(a:contains("Books")):contains("Other"), 132],[:has(a:contains("Books")):contains("Religion"), 111],[:has(a:contains("Books")):contains("Sport"), 116],[:has(a:contains("Books")):contains("Textbooks"), 106],[:has(a:contains("Games")):contains("Handheld"), 92],[:has(a:contains("Games")):contains("Linux"), 87],[:has(a:contains("Games")):contains("Other"), 130],[:has(a:contains("Games")):contains("Playstation"), 97],[:has(a:contains("Games")):contains("Wii"), 91],[:has(a:contains("Games")):contains("Windows"), 85],[:has(a:contains("Games")):contains("Xbox"), 90],[:has(a:contains("Movies")):contains("3D Movies"), 69],[:has(a:contains("Movies")):contains("Animation"), 80],[:has(a:contains("Movies")):contains("Asian/Bollywood"), 79],[:has(a:contains("Movies")):contains("Blu-Ray Disc"), 148],[:has(a:contains("Movies")):contains("Cam"), 149],[:has(a:contains("Movies")):contains("Documentary"), 81],[:has(a:contains("Movies")):contains("Dubbed Movies"), 78],[:has(a:contains("Movies")):contains("DVD ISO"), 150],[:has(a:contains("Movies")):contains("HD"), 71],[:has(a:contains("Movies")):contains("Other"), 128],[:has(a:contains("Movies")):contains("Screener"), 74],[:has(a:contains("Movies")):contains("UltraHD"), 75],[:has(a:contains("Music")):contains("AAC"), 64],[:has(a:contains("Music")):contains("Karaoke"), 67],[:has(a:contains("Music")):contains("Lossless"), 23],[:has(a:contains("Music")):contains("MP3"), 22],[:has(a:contains("Music")):contains("Other"), 129],[:has(a:contains("Music")):contains("Radio Shows"), 26],[:has(a:contains("Music")):contains("Soundtrack"), 66],[:has(a:contains("Music")):contains("Transcode"), 65],[:has(a:contains("Music")):contains("Videos/Concerts"), 68],[:has(a:contains("Other")):contains("DazPoser"), 154],[:has(a:contains("Other")):contains("Other"), 138],[:has(a:contains("Other")):contains("Pictures"), 136],[:has(a:contains("Other")):contains("Subtitles"), 134],[:has(a:contains("Other")):contains("Tutorials"), 145],[:has(a:contains("Other")):contains("Wordpress"), 153],[:has(a:contains("TV")):contains("Blu-Ray Disc"), 6],[:has(a:contains("TV")):contains("Documentary"), 7],[:has(a:contains("TV")):contains("DVD Disc"), 5],[:has(a:contains("TV")):contains("HD"), 41],[:has(a:contains("TV")):contains("Other"), 151],[:has(a:contains("TV")):contains("Sport"), 146],[:has(a:contains("TV")):contains("Ultra HD"), 152],[:has(a:contains("XXX")):contains("Books"), 124],[:has(a:contains("XXX")):contains("Hentai"), 125],[:has(a:contains("XXX")):contains("Magazines"), 123],[:has(a:contains("XXX")):contains("Pictures"), 122],[:has(a:contains("XXX")):contains("UltraHD"), 121],[:has(a:contains("XXX")):contains("Videos"), 119],[:has(a:contains("XXX")):contains("XXX Games"), 126]" matched <span id="cat_12155145">
	<strong>
		<a href="torrents.php?parent_cat=TV">TV</a>  » Blu-Ray ISO                 </strong>
</span>
  at Jackett.Indexers.CardigannIndexer+<PerformQuery>c__async5.MoveNext () [0x0159d] in <89fd469df58e42b28e997e0f85a5aebe>:0 "

**Comment by truckershitch** [comment]
Sorry for the late reply.

I think this small patch will straighten out @ForgottenSpecialist 

```
--- kickasstorrent.yml.bak      2017-05-09 14:26:20.000000000 -0400
+++ kickasstorrent.yml  2017-05-09 15:25:32.995031165 -0400
@@ -66,7 +66,7 @@
       - {id: 134, cat: Other, desc: "Other - Subtitles"}
       - {id: 145, cat: Other, desc: "Other - Tutorials"}
       - {id: 153, cat: Other, desc: "Other - Wordpress"}
-      - {id: 6, cat: TV/HD, desc: "TV - Blu-Ray Disc"}
+      - {id: 6, cat: TV/HD, desc: "TV - Blu-Ray ISO"}
       - {id: 7, cat: TV/Documentary, desc: "TV - Documentary"}
       - {id: 5, cat: TV/SD, desc: "TV - DVD ISO"}
       - {id: 41, cat: TV/HD, desc: "TV - HD"}
@@ -162,7 +162,7 @@
           ":has(a:contains(\"Other\")):contains(\"Subtitles\")": 134
           ":has(a:contains(\"Other\")):contains(\"Tutorials\")": 145
           ":has(a:contains(\"Other\")):contains(\"Wordpress\")": 153
-          ":has(a:contains(\"TV\")):contains(\"Blu-Ray Disc\")": 6
+          ":has(a:contains(\"TV\")):contains(\"Blu-Ray ISO\")": 6
           ":has(a:contains(\"TV\")):contains(\"Documentary\")": 7
           ":has(a:contains(\"TV\")):contains(\"DVD ISO\")": 5
           ":has(a:contains(\"TV\")):contains(\"HD\")": 41
```

If you just open up `kickasstorrent.yml` in a text editor and make that small change yourself (`Blu-Ray Disc` to `Blu-Ray ISO`), you can be up and running in a few minutes.  Just restart Jackett and you should be good to go.

I searched for the same TV show you did and then tested the connection in Sonarr and it worked fine.

**Comment by ForgottenSpecialist** [comment]
Replaced as you suggested sadly a new one has recently popped up and this hasn't resolved it

All the log shows now is "CardigannIndexer (kickasstorrent): Relogin required"
Re-installed Jackett on an External Ubuntu server same issue ;(

**Comment by kaso17** [comment]
@ForgottenSpecialist can you please post a full log.

**Comment by eriksneff** [comment]
I'm seeing the same thing as @ForgottenSpecialist - 
`CardigannIndexer (kickasstorrent): Relogin required`

I've got thepiratebay.org working with jackett for sonarr/radarr, but I still haven't gotten kickasstorrents working. When I run the test on it, it fails saying:
`Test failed for kickasstorrent: Found no results while trying to browse this tracker`

Here's what's in the logs:

> 05-14 16:51:18 Info Found 18 (12 new) releases from The Pirate Bay
> 05-14 16:52:22 Info Found 18 (0 new) releases from The Pirate Bay
> 05-14 16:54:37 Info Found 18 (0 new) releases from The Pirate Bay
> 05-14 16:57:29 Info Checked for a updated release but none was found.
> 05-14 16:59:33 Info CardigannIndexer (kickasstorrent): Relogin required
> 05-14 16:59:33 Info Found 0 releases from KickAssTorrent
> 05-14 16:59:33 Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker
>   at Jackett.Services.IndexerManagerService+<TestIndexer>c__async0.MoveNext () [0x00106] in <6a50586ec9c547009628269443979fa1>:0
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0
>   at Jackett.Controllers.AdminController+<Test>c__async5.MoveNext () [0x0012b] in <6a50586ec9c547009628269443979fa1>:0

**Comment by eriksneff** [comment]
Hmmm - I'm betting this CAPTCHA is the problem...

![image](https://cloud.githubusercontent.com/assets/6926543/26039505/777d6874-38d0-11e7-9fb0-0740495a0f04.png)

Thoughts?

**Comment by kaso17** [comment]
seems like you've to solve the captcha on every search now?
That will make jackett integration useless.

**Comment by thebluepotato** [comment]
Hi! I'm new to Jackett (been using the now-defunct Cardigann) and I've been having the same issue with KAT (unable to add the tracker in Sonarr because the testing fails).
What's happening is that if you're not logged in, it shows a Captcha. If you however *are* logged in, you can search freely. The login process however is very weird : 

- You first log into the community forums using a standard username/password (registration is free and open)
- Then you log in to the KAT torrents section with your username and a passkey you get at some point during registration

I have no idea how you'd input said passkey through Jackett but I hope this helps.

**Comment by eriksneff** [comment]
That's right @thebluepotato - I noticed that too - it's one of the strangest login processes I've ever seen. They've introduced this concept of a passkey that as a technologist and user experience designer, I am at a loss to infer what they're intending. It's confusing as hell. Which is unfortunate, because unless I'm missing something, I'm pretty pessimistic about Jackett's ability to thwart this, and thus, KAT will probably simply need to be no longer supported. Sad! (lol)

**Comment by thebluepotato** [comment]
@eriksneff I agree, it's so weird that I'm not really sure what they intended. However it should be kept in mind that it's still "early days" of the reborn KAT so it could change.
For the technical stuff however, I see that T411 for example isn't in the Definitions per se but has it's own code. I guess that that's because the login there (or something) prevents a plain YML definition from being used. Maybe KAT also deserves it's own code?
Because in that case it would "just" be a matter of : 

1. User gives username, password and passkey
2. Jackett logs into the forum and stores the cookie forever
3. Jackett logs into the torrents section (I guess there's a cookie too)

I've never had to log back in since! I'm fairly optimistic that it could be done.

**Comment by eriksneff** [comment]
Wow, I hope you're right - I'm thinking since this is so far afield of the original purpose of this thread, maybe we should move it here: https://github.com/Jackett/Jackett/issues/1379

**Comment by kaso17** [comment]
is the categories stuff still a problem?
(Captcha support has been added in the latest version)

**Comment by ForgottenSpecialist** [comment]
Looks like this has done the job! just came back from a weekend away to all of this thanks for resolving this much appreciated.
