### ISSUE TITLE
Can't remove admin password from Jackett

### ISSUE THREAD

**Issue by arminask** [Jackett/Jackett#13286]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Ubuntu 20.04 LTS amd64
8GB DDR4 RAM
10 threads of AMD Ryzen 5 1600
```

### Description

Hello, I set an admin password on jackett and now I can't login because maybe I forgot it? I tried deleting the server configuration files from $HOME/.config/Jackett, then restarting the service. I also completely reinstalled Jackett, but the password prompt still stays here.

systemctl status jackett output:
```
root@ubuntu-server:/home/arminas/.config# systemctl status jackett
● jackett.service - Jackett Daemon
     Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-06-08 17:52:40 EEST; 2min 49s ago
   Main PID: 155409 (sh)
      Tasks: 13 (limit: 9441)
     Memory: 70.1M
     CGroup: /system.slice/jackett.service
             ├─155409 /bin/sh /opt/Jackett/jackett_launcher.sh
             └─155412 /opt/Jackett/jackett --NoRestart

Jun 08 17:52:42 ubuntu-server jackett[155412]: 06-08 17:52:42 Info Loaded 583 indexers in total
Jun 08 17:52:42 ubuntu-server jackett[155412]: 06-08 17:52:42 Info Adding aggregate indexer ('all' indexer) ...
Jun 08 17:52:42 ubuntu-server jackett[155412]: 06-08 17:52:42 Info Adding filter indexer ('type:public' indexer) ...
Jun 08 17:52:42 ubuntu-server jackett[155412]: 06-08 17:52:42 Info Adding filter indexer ('type:private' indexer) ...
Jun 08 17:52:42 ubuntu-server jackett[155412]: 06-08 17:52:42 Info Adding filter indexer ('type:semi-public' indexer) ...
Jun 08 17:52:42 ubuntu-server jackett[155412]: 06-08 17:52:42 Info Jackett startup finished in 2.898 s
Jun 08 17:52:42 ubuntu-server jackett[155412]: Hosting environment: Production
Jun 08 17:52:42 ubuntu-server jackett[155412]: Content root path: /opt/Jackett/Content
Jun 08 17:52:42 ubuntu-server jackett[155412]: Now listening on: http://[::]:9117
Jun 08 17:52:42 ubuntu-server jackett[155412]: Application started. Press Ctrl+C to shut down.
```

### Logged Error Messages

```text
https://pastebin.com/rgTewaRw
```

### Screenshots

![image](https://user-images.githubusercontent.com/72100724/172648690-74fd8234-c835-47c2-9e7e-5ba417391c72.png)

**Comment by arminask** [comment]
> 

![image](https://user-images.githubusercontent.com/72100724/172691205-411929af-0d08-43a0-a06c-2c1d20cf4fd1.png)
There is no ServerConfig.json file :/

**Comment by garfield69** [comment]
Restart Jackett, then take a look at the `~/.config/Jackett/log.txt` file. Look for `App config/log directory:` which should point to where your Jackett is storing the serverconfig

**Comment by garfield69** [comment]
Ha, a bit of a catch 22 there, because if you are not using the standard config path then you are not going to find the log file :-(
Are you specifying a path in your systemctl config for the jackett startup?

**Comment by arminask** [comment]
> 

It's just showing the default directory: https://pastebin.com/rgTewaRw

**Comment by garfield69** [comment]
@ilike2burnthing  another obscure linux issue, not my cup of tea. any thoughts?

**Comment by ilike2burnthing** [comment]
First issue to resolve:

> Jackett is running with root privileges. You should run Jackett as an unprivileged user. 

I suggest starting from scratch.

**Comment by arminask** [comment]
> oh, you are running root. so the server file should be at `/root/.config/Jackett/ServerConfig.json`

I just deleted Jackett completely and reinstalled it manually with a sh script, now it works.

**Comment by eyelanoesis** [comment]
I have a similar issue but in OSX. Any advice on how I start troubleshooting it?
I cannot find the .json files that you speak of.
