### ISSUE TITLE
[AnimeWorld] enhancement Cardigann: support range with indexing

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13280]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

According to https://github.com/Prowlarr/Indexers/issues/196 the standard unit3d api `&categories[]=n` does not work on this site.
The example used by the OP
Currently (wrong):
`https://animeworld.cx/api/torrents/filter?api_token=(removed)&name=Fullmetal+Alchemist+Brotherhood+S01&categories[]=9&categories[]=14&categories[]=2&sortField=created_at&sortDirection=desc&perPage=100&page=1`

Fixed Version:
`https://animeworld.cx/api/torrents/filter?api_token=(removed)&name=Fullmetal+Alchemist+Brotherhood+S01&categories[0]=9&categories[1]=14&categories[2]=2&sortField=created_at&sortDirection=desc&perPage=100&page=1`

The site presents a login meta description tag of 6.0.0 but since none of the team have an account we cannot verify independently.

I have raised a discussions question at https://github.com/HDInnovations/UNIT3D-Community-Edition/discussions/2256

But since its been 5 days without an answer, I will do testing on some 6.1.0 and 5.3.0 unit3d sites that I do have access to.

### Logged Error Messages

```text
none provided by OP
```

**Comment by garfield69** [comment]
I have done some testing, and it appears that both 5.3.0 (brsociety) and 6.1.0 (generationfree) and 6.1.1b (blutopia) all accept using an index on the categories API query parm.

So I will turn this into an enhancement request and code up a hack on cardigann to support this feature.
I propose that when the range statement includes `[*]` then cardigann will insert an incremental index beginning with zero in-between the brackets.
example of a regular range:
```yaml
# build a query string argument list for the selected categories
# input: [101,201,301]
"{{ range .Categories }}&categories[]={{.}}{{end}}"
# output: "&categories[]=101&categories[]=201&categories[]=301"
```
proposed enhancement of an indexed range
```yaml
# build a query string argument list for the selected categories
# input: [101,201,301]
"{{ range .Categories }}&categories[*]={{.}}{{end}}"
# output: "&categories[0]=101&categories[1]=201&categories[2]=301"
```

**Comment by garfield69** [comment]
v0.20.1148

**Comment by Qstick** [comment]
@garfield69 Any reason you didn’t stick to go template standard for this?

**Comment by garfield69** [comment]
>Any reason you didn’t stick to go template standard for this?

Um, because according to https://github.com/Prowlarr/Indexers/issues/196 the standard unit3d 6.* api template does not work for this site?

**Comment by garfield69** [comment]
not sure I understood the question. how would I have used the go template for this?

**Comment by Qstick** [comment]
Your cardigann templates are built using go template logic, Go template standard for range with index statements is 

```
{{ range $index items }}

Some Index: $index

{{ end }}
```

My question was just out of curiosity, why not stick with standard go template schema for this as cardigann ymls we're built around instead of using `*`

**Comment by garfield69** [comment]
Oh, well, as I have said many times, I'm not a software designer or a C# dev, so I just went for the simplest fix and hacked a solve without consideration ;-)
If you code a go-template solution for your prowlerr cardigann I will certainly try to retrofit it to the Jackett cardigann to replace my current method.
Even better would be if you could submit a PR to Jackett to correct my abortion ;-D
Thanks.

**Comment by Qstick** [comment]
> Oh, well, as I have said many times, I'm not a software designer or a C# dev, so I just went for the simplest fix and hacked a solve without consideration ;-)
> If you code a go-template solution for your prowlerr cardigann I will certainly try to retrofit it to the Jackett cardigann to replace my current method.
> Even better would be if you could submit a PR to Jackett to correct my abortion ;-D
> Thanks.

Haha no problem, I just didn't know if there was a particular reason. I'll have a look and see.

**Comment by Qstick** [comment]
Essentially it would turn into this, if you guys are fine with that

```
{{ range $i, $e := .Categories}}&categories[{{$i}}]={{.}}{{end}}
```

And Example Sandbox (Hit Run)
https://go.dev/play/p/ZGXp3f6CJE4

**Comment by garfield69** [comment]
LGTM thanks.

**Comment by garfield69** [comment]
I have successfully ported your range processing code over to Jackett's Cardigann and tested the standard and the indexed range statements. Thank you.

**Comment by Qstick** [comment]
> I have successfully ported your range processing code over to Jackett's Cardigann and tested the standard and the indexed range statements. Thank you.

Awesome, working ok?

**Comment by garfield69** [comment]
>Awesome, working ok?

yes, all good.
