### ISSUE TITLE
[kinozal] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13281]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

http://kinozal.tv/ is offline

### Logged Error Messages

```text
http://kinozal.tv/ returns Error 522 Connection timed out
```

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
http://kinozal.tv/ - Error 504 - Gateway time-out
https://kinozal-tv.appspot.com/ - Error: Page not found
*.guru and *-guru.appspot.com/ - working

**Comment by garfield69** [comment]
v0.20.1666
