### ISSUE TITLE
[rarbg] (testing) Test search in RARBG => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by johnsageeek** [Jackett/Jackett#13290]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Http_client Name Firefox Version 101.0.1 Build ID 20220608170832
No_Proxy
Win 10 21H
```

### Description

Ran from https://jackett.joshbayne.com/UI/Dashboard --> "configured testers __>""test all" Error occured with no intervention

### Logged Error Messages

```text
No logs available
```

### Screenshots

![image](https://user-images.githubusercontent.com/75183931/173159655-55e797e4-43a7-4949-803f-0146560c4f66.png)
![jackett_error_rarbg](https://user-images.githubusercontent.com/75183931/173159692-b450d15d-f139-4fc0-8413-81834a8a352d.png)

**Comment by ilike2burnthing** [comment]
Your Jackett and some of your other programs are open to the entire internet, you should fix that, or at the very least password protect everything.
