### ISSUE TITLE
[req]: support Proxy Auto-Configuration or allow overwriting proxy settings per indexer

### ISSUE THREAD

**Issue by Numynum** [Jackett/Jackett#13294]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Recently, ISPs in my country were mandated to block access to 1337x.to & co.
To get around that, I decided to setup a docker container with an openvpn http proxy, to make it easy for only jacket to use the VPN connection
This is working perfectly as expected, but now a private indexer is unavailable, since it blocks requests from my VPN.

### Describe the solution you'd like

Two options that would be great for my (and maybe other people's) usecase, is to either

- Support Proxy Auto-Configuration (see [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file)), this would allow me to use a PAC script to configure which hosts should use the proxy, and which should just use a direct connection instead. In general, this feature allows for more redundant proxy setups, and is mostly aimed at browsers and similar applications
- Allow specific indexers to use a different proxy setup, in my case disabling the proxy for the private index, or only enabling it for ISP blocked indexers

### Describe alternatives you've considered

I'm not sure if there's any good alternative available, I need to proxy 1 indexer, and avoid proxying another through my VPN

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/11693

https://github.com/Jackett/Jackett/issues/2539
