### ISSUE TITLE
[req]: oncesearch adult torrent

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#13305]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: oncesearch
- URL: http://oncesearch.com/
- Description: adult content
- Minimum Seeding Time and Minimum Ratio (if Private): public
- Additional Comments:
```

**Comment by berat1397** [comment]
![resim](https://user-images.githubusercontent.com/36575395/174423850-b2d69750-d76e-4dd3-b3b2-3d8a67522640.png)
![resim](https://user-images.githubusercontent.com/36575395/174423858-4f78db25-f2d0-4a87-bbb7-22a4c15fd97d.png)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/10539
