### ISSUE TITLE
[isohunt2] (testing) Test search in Isohunt2 => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by veeru1saini1** [Jackett/Jackett#13308]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.22000.0 (64bit OS)
Environment version: 6.0.6 (C:\ProgramData\Jackett\)
Starting Jackett v0.20.1202
```

### Description

Added IsoHunt from the index page, and clicked the test button which in turn caused this to pop up -
 An error occurred while testing this indexer
Test search in Isohunt2 => Found no results while trying to browse this tracker

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in Isohunt2 => Found no results while trying to browse this tracker
```

**Comment by ilike2burnthing** [comment]
All 4 site links for the indexer are working fine here. Have you tried all 4?

Are you able to access them in browser from the same device and IP, using the same DNS?

If so, please post an enhanced log of the issue? https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
