### ISSUE TITLE
[req]: More than one configuration is allowed for a indexer

### ISSUE THREAD

**Issue by yueyingjuesha** [Jackett/Jackett#13303]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hey team, is there a way to have more than 1 configuration for a indexer.
Currently when I try to create a second configuration for a indexer, I can no longer find that indexer in add indexer drop down

### Describe the solution you'd like

For example like I have 1 configuration for a site that only grabs the free torrent, but another configuration for the same site that can grab all the torrent they have.

**Comment by garfield69** [comment]
I presume you are referring to yml indexers, in which case all you need to do is:
clone the indexer file as indexername2.yml
edit the file and change the id and name  to match indexername2, and the description so you can tell your two indexers apart on the dashboard.
And you should be good to go.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/10525
