### ISSUE TITLE
[req]: BrasilTracker Parse

### ISSUE THREAD

**Issue by Fotguedes** [Jackett/Jackett#13315]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I've started using the BrasilTracker indexer in jackett and noticed it get a few errors when trying to parse the name.

In Radarr it's able to return and show the correct movie requested, but it shows the error:

`Failed to find movie title in release name Doutor Estranho no Multiverso da Loucura [Doctor Strange in the Multiverse of Madness] / WEB-DL / IMAX / Dual Audio / E-AC-3 / H.264 / Full HD /`

And also do not parse the release quality.

And in Sonarr it doesn't even show something in the search. When I tried directly from the Jackett it showed that the neither the season or the episode is being parsed
![image](https://user-images.githubusercontent.com/55153463/175437737-81cc557e-2129-4888-9a1b-fc1c5708ecc7.png)

### Describe the solution you'd like

I noticed that the release name for BrasilTracker is similar to the [BJ indexer](https://github.com/Jackett/Jackett/blob/5b357e601993ad8c696428d1aa1c9c80d2987860/src/Jackett.Common/Indexers/BJShare.cs) but i noticed the search for both are quite different.

**Comment by Fotguedes** [comment]
Also, I noticed that even thought the site have categories, when i'm importing the indexer it only show the option "Others"

**Comment by ilike2burnthing** [comment]
You'd need to ask the folks over at Radarr why `Doutor Estranho no Multiverso da Loucura [Doctor Strange in the Multiverse of Madness]` was rejected. I would guess that anything in square brackets is ignored, but that's just a guess. If it's as simple as that, it should be an easy fix.

Quality for results is simple enough, but I'll wait for your reply from Radarr first.

The tracker does not provide season and episode information in the search results,  nor does it provide categories, nothing we can do about that. You'd need to ask the site mods to change that.

**Comment by Fotguedes** [comment]
About the name, even thought the name in Brackets is the oficial one, i noticed that in the "titles" page of the Radarr the Portuguese was added already, but with the year in it... So it could also be that. Also the year isn't at the release name, even though it's in the site. I've tried with other releases, and i'm pretty sure it's not parsing because of the missing year, i'll try contacting the site owner before Radarr.

About the season and categories
![image](https://user-images.githubusercontent.com/55153463/175552490-a1846b80-5b45-4125-abf6-fbed85688883.png)

The site support both of them, and are also similar to BJShare
![image](https://user-images.githubusercontent.com/55153463/175552720-acc418a2-21a1-4a57-a76b-2ae08b5524c6.png)

Is there anything that te site needs to update to be able to pass this information to Jackett? They've asked me this yesterday and I couldn't answer it.

About the quality, no problems, when I get the answer from them i let you know.

Tks for the reply!

**Comment by ilike2burnthing** [comment]
The year could be added as well.

The season and episode information is only available when using the `Agrupar por lançamento` or `‎Group by posting` setting, which then shows multiple torrents for each result, something cardigann can't use. To make those enhancements the indexer will need to be rewritten in C#.

**Comment by Fotguedes** [comment]
So is it possible? Is there anything that i can support you or the site do?

Tks for the help, this week a big tracker (Pirata Digital) closed here in Brazil, and we're with few options to grab the new releases. Brasil Tracker is the tracker that a majority of people are migrating to.

**Comment by ilike2burnthing** [comment]
If BJShare is basically identical then it should just be a matter of copying that over and tweaking a few things.

I don't have time to do it right now, but @garfield69 might later (I do mean might, I'm not volunteering their time). Otherwise, PRs are open to all. If you're familiar with Visual Studio, or comfortable giving it a go, see https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md#contributing-code

Was there an announcement that Pirata Digital was permanently shutting down? Currently the site just times out.

**Comment by Fotguedes** [comment]
Perfect, tks for helping with it.

About Pirata Digital, the owner announced at their Discord this week, and the Uploaders confirmed and already deleted everything from their SeedBoxes, so unfortunately i think that it's definitive.

**Comment by Fotguedes** [comment]
Just checked here and everything is working great!

Radarr is now able to see the movies and get the release quality.

Sonarr that before couldn't even get the series now is able to see them, the only problem is that it's not parsing the quality, showing as unknow in sonarr.

I thought it would take a while, but you guys were amazing! Tks for everyone who got orphan because of PirataDigital.

**Comment by garfield69** [comment]
I have finished with stage 1, cloning the bjshare indexer and removing everything that will not work for use with brasiltracker.
I'll start working on stage 2, which will to try adding in all the bits that the new indexer is missing, such as posters, imdb and tmdb links, and if I can figure it out, the quality for tv.

**Comment by garfield69** [comment]
that should be it. added quality to series, and posters, imdb, tmdb and MST

**Comment by Fotguedes** [comment]
Just checked here, all working flawlessly!!

**Comment by garfield69** [comment]
v0.20.1226

**Comment by GabrielOsvair** [comment]
I can't make Sonarr search for anything in Brasil Tracker (but in Radarr, although the results are not identified, they can be seen). Would you help me?

**Comment by garfield69** [comment]
@GabrielOsvair Sonarr + Jackett with the BrasilTracker works for me.
In your Sonarr indexer setup set the categories to just `Séries` (100002) 
if that does not work then open a fresh ticket and provide the info in the form and we can try to help you diagnose the issue further.
