### ISSUE TITLE
Add cloudtorrents indexer

### ISSUE THREAD

**Issue by lucasjohnson** [Jackett/Jackett#13313]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: cloudtorrents
- URL: https://cloudtorrents.com
- Description: Anime / Applications / Books / Games / Movies
 / Music / Other / TV / XXX
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: excellent for sports
```

**Comment by garfield69** [comment]
v0.20.1216
