### ISSUE TITLE
[xthor] private tracker not working properly with freeleech

### ISSUE THREAD

**Issue by cedvan** [Jackett/Jackett#13326]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient/HttpWebClient2
Using FlareSolverr: Enabled (private url)
Using proxy: Disabled
App config/log directory: /config
Running in Docker: Yes
Docker image: ghcr.io/k8s-at-home/jackett:latest
Docker environement: Kubernetes v1.23.6
Jackett variant: CoreLinuxAmdx64
Jackett version: v0.20.892
```

### xthor private tracker not working properly with freeleech

**the xthor API specifies:**
*The "freeleech" parameter allows to obtain 3 different results, if the parameter is not defined the request will return the torrents in freeleech and those which are not, if the parameter is 0 only the torrents which are not in freeleech will be returned, if the parameter is set to 1 only freeleech torrents will be returned.*

With default configuration, Jackett add a empty freeleech parameter to xthor queries. 
But when freeleech is specified empty it will be understood as 0 by xthor.
So the api will return by default only non-freeleech torrents

It is therefore currently not possible to get freeleech and non-freeleech torrents with the same query in Jackett :cry: .

It would be necessary to modify the configuration of this tracker and transform the "freeleech" parameter into a drop-down list with the values:

"All" => NO parameter in the query
"Yes" => parameter "freeleech=1" in the query
"No" => parameter "freeleech=0" in the query

Thanks

### Logged Error Messages

```text
2022-06-28 10:17:20.4969 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://api.xthor.tk/?passkey=REDACTED&category=&search=strange&tmdbid=&freeleech=) 
2022-06-28 10:17:20.5960 Debug WebClient(HttpWebClient2): Returning OK => 63381 bytes
{
    "error": {
        "code": 0,
        "descr": "Ok"
    },
....
```

**Comment by garfield69** [comment]
Your Jackett v0.20.892 is outdated.
The freeleech option for the xthor indexer was fixed back in early May beginning with v0.20.1005

I recommend you fetch the latest docker image to resolve your issue.
