### ISSUE TITLE
[req]: Acervos

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13324]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Acervos
- URL: https://acervos.cc/
- Description: Acervos is a Brazilian tracker for movies, tv shows, and others.
- Minimum Seeding Time and Minimum Ratio (if Private): MST 5d
- Additional Comments: registration is currently open
engine: Unit3d 6.1.0
```

**Comment by garfield69** [comment]
v0.20.1246

**Comment by garfield69** [comment]
https://acervos.cc/ ERR_CONNECTION_REFUSED

**Comment by ilike2burnthing** [comment]
Should we just give up on this one?

**Comment by garfield69** [comment]
the last change was jan16 so I'm inclined to wait until Feb16 then delete if they are not open by then.

**Comment by garfield69** [comment]
acervos back online. registration currently open.

**Comment by ilike2burnthing** [comment]
https://acervos.cc/ - HTTP ERROR 500 (and so it begins...)

**Comment by garfield69** [comment]
Oh FFS. back to vanilla 6.4.1 invite only.

**Comment by garfield69** [comment]
@jaysonsantos Do you have any info about what is going on at Acervos?
The site has been trying to upgrade to unit3d 6.5.0 for a couple months now, without success so far.
ATM its at 6.4.1 and old accounts have not been ported and registration is closed.

**Comment by ilike2burnthing** [comment]
Registration is back open.

From their announcement:
`First, we apologize to those who previously signed up and had their account deleted. It was necessary for technical reasons.`

Will reset to v6.4.1

**Comment by garfield69** [comment]
https://acervos.cc/ ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
v0.21.34
