### ISSUE TITLE
SceneTime Sonarr Jackett - when alternative title exists it get wrong result. To many request in short time.

### ISSUE THREAD

**Issue by lindz0** [Jackett/Jackett#13328]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Starting Jackett v0.20.1251 
Environment version: 6.0.6 (C:\ProgramData\Jackett\) 
OS version: Microsoft Windows NT 10.0.19044.0 (64bit OS) 
Jackett variant: CoreWindows 
Running in Docker: No 
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
App config/log directory: C:\ProgramData\Jackett 
Using proxy: Disabled 
Using FlareSolverr: No 
Using HTTP Client: HttpWebClient2
```

### Description

SceneTime Sonarr Jackett - when alternative title exists in Sonarr it get wrong result. Sonarr makes a request to Jackett for every alternitive title. Scenetime rejects to many request at the same time. It don't work even with one alternative title. I don't know if it's a Jacket problem or Sonarr problem. It is Scenetimes fault. 

In scenetime.cs row 134. I have change my local source to;

            // response without results (the message is misleading)
            if (results.ContentString?.Contains("slow down geek!!!") == true)
                throw new Exception("slow down geek!!!");
            // return new List<ReleaseInfo>();

 I have no good solutions to this problem. Waiting 5 sec per call is not fun. 

### Logged Error Messages

```text
06-29 21:35:51 Info Torznab search in SceneTime for Australian Gold Schatzsuche Down Under S07E15 => Found 0 releases 
06-29 21:35:52 Error Jackett.Common.IndexerException: Exception (scenetime): slow down geek!!!
 ---> System.Exception: slow down geek!!!
   at Jackett.Common.Indexers.SceneTime.PerformQuery(TorznabQuery query) in F:\GitHub\Jackett\src\Jackett.Common\Indexers\SceneTime.cs:line 136
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in F:\GitHub\Jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:line 310
```

**Comment by garfield69** [comment]
A possible solution would be that when the indexer detects the geek message it retries the query after a delay.
All that remains is to determine the minimum time that scenetime will accept between queries. 
Common delay is typically a little over 2 seconds, 2.5s is often used.
I'll try to find another indexer that has this mechanism and see if I can adapt it for use with this indexer.

**Comment by garfield69** [comment]
v0.20.1254

**Comment by lindz0** [comment]
Thanks it works for me!
