### ISSUE TITLE
[m-teamtp]: 站点无法添加

### ISSUE THREAD

**Issue by log-time** [Jackett/Jackett#13336]
error:
```
- Name: m-team
- URL: https://kp.m-team.cc
无法正常添加站点
```

environment:
```
2022-07-03 11:21:49.9267 Info Starting Jackett v0.20.1263
2022-07-03 11:21:50.3065 Info Environment version: 6.0.6 (/app/Jackett/)
2022-07-03 11:21:50.3075 Info OS version: Unix 5.10.28.0 (64bit OS) (64bit process)
2022-07-03 11:21:50.3084 Info Jackett variant: CoreLinuxAmdx64
2022-07-03 11:21:50.3089 Info File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-07-03 11:21:50.3089 Info Running in Docker: Yes (image build: v0.20.1263-ls73)
2022-07-03 11:21:50.3100 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-07-03 11:21:50.3100 Info App config/log directory: /config/Jackett
2022-07-03 11:21:50.3111 Info Using proxy: Disabled
2022-07-03 11:21:50.3111 Info Using FlareSolverr: http://xx.xx.xx.xx:8191
2022-07-03 11:21:50.3124 Info Using HTTP Client: HttpWebClient2
```

**Comment by log-time** [comment]
[m-team.txt](https://github.com/Jackett/Jackett/files/9034343/m-team.txt)
[FlareSolverr.txt](https://github.com/Jackett/Jackett/files/9034344/FlareSolverr.txt)

**Comment by log-time** [comment]
此站点开启2FA验证时，使用MTeamTP2FA这个模板也无法正常添加站点。

**Comment by garfield69** [comment]
In future, please use the correct form when reporting problems with existing indexers.
![image](https://user-images.githubusercontent.com/6933240/177050696-f4a3d453-80ec-4ef2-a817-b3d5666e7b47.png)

If you have enabled 2FA then you need to be using the MTeamTP2FA indexer. But because you are using a Docker version of Jackett you are going to have ensure that the cookie and user-agent you provide have been fetched to match the docker machine specifics.
Have you read https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work ?
Especially the Notes section, items 4 to 7.

**Comment by log-time** [comment]
抱歉，下次提交bug时注意。这个站点我目前没有开启2FA，在使用m-teamtp模板添加站点时出现错误。
提到2FA模板问题，只是因为之前该站点我打开2FA后，使用mteamtp2FA模板，填入cookie也无法正常添加站点，所以顺带说一下。

**Comment by log-time** [comment]
我先仔细看一下您给的链接，看看是不是我的配置有问题。

**Comment by garfield69** [comment]
As for the problem with the regular m-teamtp indexer, could you repeat the test, but this time, beforehand, as well as setting `LOG_LEVEL=debug` could you please also set `LOG_HTML=true` for the flaresolverr server.
This way we should be able to see the html that flaresolverr is processing where it detects that cloudflare is in use but then complains that it cannot find the challenge selector.
Post just the flaresolverr log for us to look at this time.
Thanks.

**Comment by log-time** [comment]
[Uploading 20220704.txt…]()

**Comment by garfield69** [comment]
Hmm. It looks like your login was completed successfully, and flaresolverr was presented with the index.php page from the site.
Clearly the flaresolverr detection is not working. We should raise a ticker on https://github.com/FlareSolverr/FlareSolverr and perhaps that team will come up with a solution.

**Comment by log-time** [comment]
谢谢

**Comment by garfield69** [comment]
Wow. there is already a ticket raised by you for this exact issue https://github.com/FlareSolverr/FlareSolverr/issues/414
I'll add your latest results to that ticket.
Unfortunately there is nothing that can be done from the Jackett side  for this issue. I will close this ticket.

**Comment by log-time** [comment]
大佬费心了
