### ISSUE TITLE
Partis indexer multiple issues

### ISSUE THREAD

**Issue by dl1ch** [Jackett/Jackett#13330]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Not relevant.
```

### Description

I was able to identify two major issues with the Partis.si tracker indexer.
Because of the two described issues the indexer is not fully functional when in combination with Radarr/Sonarr/Bazarr for searching media and gathering the right context from torrents.

The two issues are:
- The indexer gathers only partial torrent names (not full torrent name)
- The indexer does not map the correct torrent category

### Logged Error Messages

```text
No logs.
```

### Screenshots

As you can see an example from the picture below, the search for string "beauty" gets the following results:
![image](https://user-images.githubusercontent.com/16349340/176655131-f40e6c25-263d-44e4-8bb9-725fa03977f0.png)

If we focus only on the first result (but you can see that also other results are affected by this issue), we can see that the gathered "Name" is "Beauty 2022 CroSubs 720p WEBRip XviD AC3-​" when the full name of the torrent is "Beauty 2022 CroSubs 720p WEBRip XviD AC3-Unknown" (shown in the picture below).

![image](https://user-images.githubusercontent.com/16349340/176656681-79dd6174-8bda-4e98-8774-e5baebf837f4.png)

Beside the partial name issue, you can also see that the torrent is categorized as "WEBRip" (100054) , but the indexer identified it as "Movies/SD" (2030).

If the media would have a longer name, there would be even less information about it. Because of this, most media cannot be categorized correctly or even identified.

**Comment by ilike2burnthing** [comment]
Categories fix in the works.

As for the names, we're using the search results page for information, not each result's details page, and it limits names to a certain length.

**Comment by garfield69** [comment]
v0.20.1261
