### ISSUE TITLE
[req]: torrent911

### ISSUE THREAD

**Issue by roshavagarga** [Jackett/Jackett#13332]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: Torrent911
- URL: https://www.oxtorrent.zip/
- Description: General French indexer, for movies, TV series and other
- Minimum Seeding Time and Minimum Ratio (if Private): None
- Additional Comments:
```

**Comment by garfield69** [comment]
This indexer already exists under its original name of oxtorrent.
@ilike2burnthing  shall we bother renaming the indexer?

**Comment by roshavagarga** [comment]
Ah, so the oxtorrent indexer also indexes the domains for Torrent911?

I can note that the latter tends to release torrents that are then copied/shared by other similar torrent websites (cpasbien clone, oxtorrent, gktorrent, t9 and t9 clone).

**Comment by ilike2burnthing** [comment]
Yea, sure.

**Comment by garfield69** [comment]
>Ah, so the oxtorrent indexer also indexes the domains for Torrent911?

the oxtorrent site became the torrent911 site. Its just a label change. that is why the oxtorrent indexer works.
we will relabel the indexer to reflect the new name.

**Comment by roshavagarga** [comment]
Ah, wow, I did not know that, thank you then for renaming it 👍

**Comment by garfield69** [comment]
v0.20.1270

**Comment by garfield69** [comment]
https://www.torrent911.pe/ has changed their layout
now presents results that are just posters with a title to link to the details page, and nothing else, no date, size, seeds ,leech, or anything else useful.
no longer suitable for processing with yaml.

**Comment by garfield69** [comment]
the alternate domain at https://www.t911.ws/ is still on list layout so we can use that until they follow the primary

**Comment by garfield69** [comment]
v0.21.2163

**Comment by garfield69** [comment]
torrent911 -> semi-private

**Comment by garfield69** [comment]
v0.22.100

**Comment by garfield69** [comment]
The torrent911 indexer has now been renamed to oxtorrent-vip
the 911 site switched from a list layout to a poster layout (has only cat and name, is missing size/peers/leechers), so we will not be creating a replacement t911 indexer as this site is now declared unsuitable for indexing.
https://github.com/Jackett/Jackett/issues/15411

**Comment by garfield69** [comment]
v0.22.119
