### ISSUE TITLE
[pterclub]  问题：pterclub开启2FA验证后，无法使用现有模板添加站点。

### ISSUE THREAD

**Issue by log-time** [Jackett/Jackett#13335]
error:

```markdown
- Name: pterclub
- URL: https://pterclub.com/
问题：pterclub开启2FA验证后，无法使用现有模板添加站点。
```

environment:
```
2022-07-03 11:21:49.9267 Info Starting Jackett v0.20.1263
2022-07-03 11:21:50.3065 Info Environment version: 6.0.6 (/app/Jackett/)
2022-07-03 11:21:50.3075 Info OS version: Unix 5.10.28.0 (64bit OS) (64bit process)
2022-07-03 11:21:50.3084 Info Jackett variant: CoreLinuxAmdx64
2022-07-03 11:21:50.3089 Info File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-07-03 11:21:50.3089 Info Running in Docker: Yes (image build: v0.20.1263-ls73)
2022-07-03 11:21:50.3100 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-07-03 11:21:50.3100 Info App config/log directory: /config/Jackett
2022-07-03 11:21:50.3111 Info Using proxy: Disabled
2022-07-03 11:21:50.3111 Info Using FlareSolverr: http://xx.xx.xx.xx:8191
2022-07-03 11:21:50.3124 Info Using HTTP Client: HttpWebClient2
```

**Comment by garfield69** [comment]
The captcha box still exists for some situations:
![image](https://user-images.githubusercontent.com/6933240/177023835-d01dfbaf-67b5-4561-ab6a-ee30f3692ac4.png)

IF you do not have a captcha box when you edit the pterclub config using your dashboard, then simply make sure that the `Captcha Text` input box is empty of all text and save.

If the login does not work then there is something else going on, in which case raise a issue ticker (not a request for a new indexer like you have done here). 
For the new issue provide an enhanced log so that we can see what the site is returning when you try to login.

**Comment by log-time** [comment]
[pterclub.txt](https://github.com/Jackett/Jackett/files/9034090/pterclub.txt)
这个是添加pterclub失败时的log,麻烦大佬看一下

**Comment by garfield69** [comment]
You have provided the **regular** log, which only shows that the image verification has failed error message, but does not show enough details about the session traffic leading up to the failure.
Please enable the enhanced log, then edit the pterclub config with your Jackett dashboard and fill in the config and save.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details on how to provide the enhanced log. 
Thanks.

**Comment by log-time** [comment]
[pterclub.txt](https://github.com/Jackett/Jackett/files/9034128/pterclub.txt)

**Comment by garfield69** [comment]
From the enhanced log that you have provided, it appears that the 2FA code field on the login page is no longer called `verify_code` , but `2fa_secret`.

I will change the indexer to use the new field name.
Once we publish Jackett in about 20 minutes, the LinuxServer.io automation may take some time to build the new docker image from our release source.
After which you can update your docker image with the new release and then you can try to configure the indexer again and see if the login succeeds with the 2FA and CAPTCHA fields filled in afresh.
Let me know if it works so I can close the ticket. Thanks.

**Comment by log-time** [comment]
谢谢大佬，等升级测试后再反馈

**Comment by garfield69** [comment]
v0.20.1270

**Comment by log-time** [comment]
该站点最新版本已经可以正常添加

**Comment by garfield69** [comment]
So everything is working OK for you now, and I can close this ticket?

**Comment by log-time** [comment]
是的，谢谢大佬！

**Comment by garfield69** [comment]
\o/
