### ISSUE TITLE
[req]:  Generate RSS from all indexers (from manual search)

### ISSUE THREAD

**Issue by fbeauvais** [Jackett/Jackett#13339]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Looked everywhere for this. Sorry If it has been covered. Maybe I'm not searching with the good terms. 

### Describe the solution you'd like

Just a line over all the indexers called All indexers with rss and every options.

**Comment by ilike2burnthing** [comment]
Do you mean this? https://github.com/Jackett/Jackett#aggregate-indexers

**Comment by fbeauvais** [comment]
Yep. Works. But should be implemented in GUI.

**Comment by ilike2burnthing** [comment]
We strongly recommend against using it to begin with, for the reasons explained there, so we're not going to add it to the GUI.
