### ISSUE TITLE
"Adding a Jackett indexer in Sonarr or Radarr"-Button does not return URL

### ISSUE THREAD

**Issue by shanks1337** [Jackett/Jackett#13346]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: Mozilla Firefox 102.0.1 (64-Bit)/Chromium Version 105.0.5169.0 (Developer-Build) (64-Bit)
OS version: Windows 8.1 Pro N
```

### Description

The button "Copy Torznab Feed" in 

"Adding a Jackett indexer in Sonarr or Radarr" at
 "2. Click on the indexers corresponding >>>**Copy Torznab Feed**<<< button and paste it into the Sonarr/Radarr URL field."

does not return an URL. 

Result: Nothing added to clipboard
Expected result: "http://127.0.0.1:9117/torznab/all" is added to clipboard

### Logged Error Messages

```text
.
```

### Screenshots

![Screenshot 2022-07-09 at 01-58-54 Jackett](https://user-images.githubusercontent.com/8984284/178083608-a99c9c4a-d3cd-47cb-a999-83854890b875.png)

**Comment by garfield69** [comment]
Those areas that you have circled are not functional buttons. The line of text tells you what to do, which is to go to the **corresponding indexer** and use the button on its right, labelled `Copy Torznab Feed` for each indexer you want to add to the *Arr app.
![image](https://user-images.githubusercontent.com/6933240/178084487-4c131ae2-295c-4539-b559-e09dabb1f728.png)

**Comment by shanks1337** [comment]
Thank you for your explanation! Even tho I see why a real button is added here, I still feel like this is a improper usage of a "real" button from a consistency / usability stand point. From my perspective, the intent of buttons is to be pressable. I guess that opinions can differ here when it comes to demonstrations.

I'm fairly new to *rr and Jacket, I wonder why it is not sufficant to add the "http://127.0.0.1:9117/torznab/all", so (to my understanding) all indexers are added to the *rr derivates. It seems to work just fine that way.

**Comment by garfield69** [comment]
We do not recommend using the ALL aggregate to *Arr apps.
You get more control by adding individual indexer to the apps.
See https://github.com/Jackett/Jackett#aggregate-indexers for an explanation of what features you loose when using ALL aggregate indexer.

**Comment by garfield69** [comment]
I see your point about the demo-button. I will look into disabling the button so its clearer that this is not a working button.
