### ISSUE TITLE
[mteamtp2fa] (updating) Login Failed, got redirected.

### ISSUE THREAD

**Issue by weiweigod** [Jackett/Jackett#13345]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
docker
```

### Description

An error occurred while updating this indexer
Login Failed, got redirected.
[Click here to open an issue on GitHub for this indexer.](https://github.com/Jackett/Jackett/issues/new?template=bug_report.yml&title=[mteamtp2fa]%20(updating)%20Login%20Failed%2C%20got%20redirected.)

### Logged Error Messages

```text
An error occurred while updating this indexer
Login Failed, got redirected.
[Click here to open an issue on GitHub for this indexer.](https://github.com/Jackett/Jackett/issues/new?template=bug_report.yml&title=[mteamtp2fa]%20(updating)%20Login%20Failed%2C%20got%20redirected.)
```

**Comment by ilike2burnthing** [comment]
Environment:
> Please provide the details of the system Jackett is running on. The best way to do this is to restart Jackett, access the dashboard, view the log, and copy/paste the last 10 Info lines at the bottom of the log.

The 'log' you provided is just the error notification, please provide the log for the issue.

Was this indexer previously working?

Is the browser (that you got the cookie and UA from) running on the same device  as Jackett is installed on, and using the same IP and DNS?

**Comment by jesongit** [comment]
我取消了我的2FA，就可以添加了
