### ISSUE TITLE
Service running but no dashboard (Opensuse Leap 15.4)

### ISSUE THREAD

**Issue by MetaStazz** [Jackett/Jackett#13351]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Opensuse Leap 15.4 - KDE 5.90 - Plasma 5.24
OS version: Unix 5.14.21.150400 (64bit)

Jackett: Jackett v0.20.1296 (CoreLinuxAmdx64)
Environment version: 6.0.6 (~/.system/Jackett/)
Running in Docker: No
Using proxy: Disabled
Using HTTP Client: HttpWebClient2
App config/log directory: ~/.config/Jackett
```

### Description

So first, I will say that everything was working fine on Leap 15.3. But since I upgraded to Leap 15.4, the service seems to not work properly!
I installed Jackett as a service, following the "Install on Linux (AMDx64) section B".
After reboot, the service is present, loaded and active, but I can't access the dashboard until I manually start the ~/.system/Jackett/jackett_launcher.sh

```shell
Command : sudo service --status-all
jackett.service   loaded    activating    auto-restart    Jackett Daemon

Command : systemctl status jackett
jackett.service - Jackett Daemon
Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: disabled)
Active: activating (auto-restart) (Result: exit-code) since Mon 2022-07-11 09:31:10 CEST; 4s ago
Process: 22321 ExecStart=/bin/sh ~/.system/Jackett/jackett_launcher.sh (code=exited, status=216/GROUP)
Main PID: 22321 (code=exited, status=216/GROUP)
```

### Logged Error Messages

```text
no error
```

**Comment by garfield69** [comment]
@ilike2burnthing  I've no clue about linux security, any ideas?

**Comment by ilike2burnthing** [comment]
Sorry, not a clue. I can only suggest reaching out to somewhere like:
https://www.reddit.com/r/openSUSE/ or https://forums.opensuse.org/

If you do get an answer, please let us know.

**Comment by MetaStazz** [comment]
So... As I didn't find anything on internet, at least with the keyword I used, I did a bit of digging and I found what cause the issue.

In `install_service_systemd.sh` line 74 `Group=${JACKETT_USER}`
This creates the service with the userName as groupName !!

I checked `/etc/systemd/system/jackett.service` and changed the group name by my actual group name and everything is working fine now !!
