### ISSUE TITLE
[req]: Ability to use same tracker twice

### ISSUE THREAD

**Issue by averon420** [Jackett/Jackett#13368]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Since sonarr can't filter by leechonly, its an issue to either filter by leechonly also for radarr, or not use the indexer at all on sonarr.

### Describe the solution you'd like

I'd love if sonarr would add custom profiles like radarr, but so far I though about adding the tracker twice, and use the leechonly on sonarr.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/10525
