### ISSUE TITLE
Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by neoOpus** [Jackett/Jackett#13360]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Loading Native indexers ...
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.25140.0 (64bit OS)
Environment version: 6.0.7 (C:\ProgramData\Jackett\)
Starting Jackett v0.20.1305
```

### Description

The updater executable (JackettUpdater.exe) seems infected by a malware according to Windows Security... 

### Logged Error Messages

```text
I keep getting notification about this even after trying to delete the file...
```

**Comment by garfield69** [comment]
This is most likely a false positive as VirusTotal reports only 2 of 66 anti-malware products suspect Jackett of being bad.
https://www.virustotal.com/gui/file/922ce0e257f15345aa0d31de523b97c30fba1ac502c7195d8861c62872c07539
There is nothing we can do about this. From time to time, anti-malware product see red, but never have a majority agreed there is a problem, so up to now its usually been a case of a false positive and eventually, the products refine and update their signatures files, and Jackett is given the all clear again.
It's up to you what to do next. 
When I get a hit on my PC like this, I usually load the file to virustotal.com to get a second option, and if given the all clear by the majority, I then add an exception to my security app to stop it nagging me. I then send a false positive report to the supplier via the apps reporting page and carry on. Once the next signature file is published I drop the exception and test.
Or you can uninstall Jackett and use another, like Prowlerr for instance, which is Jackett on steroids, a feature rich alternative.

**Comment by neoOpus** [comment]
I found that the version from the website is just fine but when I use WingetUI it download an infected version...

**Comment by garfield69** [comment]
@vedantmgoyal2009 do you have any comments or insights into a question of weather or not the winget flavour of Jackett could be flagged (legitimately or as a false positive) with a Win32/Wacatac.B!ml hit for this windows user?

**Comment by ilike2burnthing** [comment]
@neoOpus upload the file that Windows Defender has flagged on your system to https://VirusTotal.com and post the results link here.

**Comment by neoOpus** [comment]
> @neoOpus upload the file that Windows Defender has flagged on your system to https://VirusTotal.com and post the results link here.

It seems that this is due to scoop release being tampered with... I use WingetUI to do the update and that's when it happens...

**Comment by ilike2burnthing** [comment]
I very much doubt anything is being tampered with, it's almost certainly just a false positive. They happen all the time, especially with Windows Defender.

Again, please upload the file in question to https://VirusTotal.com and post the results link here.
