### ISSUE TITLE
Binary Package Permissions

### ISSUE THREAD

**Issue by reecewebb** [Jackett/Jackett#1336]
The files in the binary release package are all root:root 777. It's typically bad news to have anything world-writable, especially when owned by root.

Jackett # ls -al
total 8128
drwxrwxrwx 4 root root    4096 May  4 12:57 .
drwxr-xr-x 3 root root      57 May  5 10:07 ..
-rwxrwxrwx 1 root root 1223680 Oct  7  2016 AngleSharp.dll
-rwxrwxrwx 1 root root  273408 Feb 24  2016 AutoMapper.dll
-rwxrwxrwx 1 root root   16896 Jun 29  2016 Autofac.Integration.Owin.dll
-rwxrwxrwx 1 root root    7680 Aug 17  2016 Autofac.Integration.WebApi.Owin.dll
-rwxrwxrwx 1 root root   45568 Oct 24  2016 Autofac.Integration.WebApi.dll
-rwxrwxrwx 1 root root  212480 Jan 17 04:12 Autofac.dll
-rwxrwxrwx 1 root root   19968 Feb 20 11:10 CloudFlareUtilities.dll
-rwxrwxrwx 1 root root   58368 Feb 27  2013 CommandLine.dll
drwxrwxrwx 7 root root    4096 May  4 12:57 Content
-rwxrwxrwx 1 root root  815104 Jun  4  2013 CsQuery.dll
-rwxrwxrwx 1 root root   53248 May  4 12:57 CurlSharp.dll
-rwxrwxrwx 1 root root     338 May  4 12:56 CurlSharp.dll.config
-rwxrwxrwx 1 root root   19634 May  4 12:57 CurlSharp.dll.mdb
-rwxrwxrwx 1 root root   12288 Jan 19  2012 DateTimeRoutines.dll
drwxrwxrwx 2 root root    4096 May  4 12:57 Definitions
-rwxrwxrwx 1 root root  200704 Jan  3  2011 ICSharpCode.SharpZipLib.dll
-rwxrwxrwx 1 root root 1102336 May  4 12:57 Jackett.dll
-rwxrwxrwx 1 root root  205277 May  4 12:57 Jackett.dll.mdb
-rwxrwxrwx 1 root root   13824 May  4 12:57 JackettConsole.exe
-rwxrwxrwx 1 root root    2456 May  4 12:56 JackettConsole.exe.config
-rwxrwxrwx 1 root root    2453 May  4 12:57 JackettConsole.exe.mdb
-rwxrwxrwx 1 root root    4608 May  4 12:57 JackettService.exe
-rwxrwxrwx 1 root root    2222 May  4 12:56 JackettService.exe.config
-rwxrwxrwx 1 root root     941 May  4 12:57 JackettService.exe.mdb
-rwxrwxrwx 1 root root  753152 May  4 12:57 JackettTray.exe
-rwxrwxrwx 1 root root    2456 May  4 12:56 JackettTray.exe.config
-rwxrwxrwx 1 root root    2002 May  4 12:57 JackettTray.exe.mdb
-rwxrwxrwx 1 root root   11264 May  4 12:57 JackettUpdater.exe
-rwxrwxrwx 1 root root    2222 May  4 12:56 JackettUpdater.exe.config
-rwxrwxrwx 1 root root    2113 May  4 12:57 JackettUpdater.exe.mdb
-rwxrwxrwx 1 root root   18047 May  4 12:56 LICENSE
-rwxrwxrwx 1 root root  171672 Apr  3  2015 Microsoft.AspNet.Identity.Core.dll
-rwxrwxrwx 1 root root   18088 Feb 13  2015 Microsoft.Owin.FileSystems.dll
-rwxrwxrwx 1 root root   88232 Feb 13  2015 Microsoft.Owin.Host.HttpListener.dll
-rwxrwxrwx 1 root root  133288 Feb 13  2015 Microsoft.Owin.Host.SystemWeb.dll
-rwxrwxrwx 1 root root   64680 Feb 13  2015 Microsoft.Owin.Hosting.dll
-rwxrwxrwx 1 root root   64680 Feb 13  2015 Microsoft.Owin.StaticFiles.dll
-rwxrwxrwx 1 root root  101032 Feb 13  2015 Microsoft.Owin.dll
-rwxrwxrwx 1 root root  348160 Jun 10  2011 MonoTorrent.dll
-rwxrwxrwx 1 root root  488960 Jan 23 09:57 NLog.dll
-rwxrwxrwx 1 root root  658944 Jan 19 12:03 Newtonsoft.Json.dll
-rwxrwxrwx 1 root root    4608 Nov 13  2012 Owin.dll
-rwxrwxrwx 1 root root   10013 May  4 12:56 README.md
-rwxrwxrwx 1 root root   22232 Feb 19  2015 System.Net.Http.Extensions.dll
-rwxrwxrwx 1 root root  185544 Jan 27  2015 System.Net.Http.Formatting.dll
-rwxrwxrwx 1 root root   21720 Feb 19  2015 System.Net.Http.Primitives.dll
-rwxrwxrwx 1 root root   62152 Jan 27  2015 System.Web.Http.Owin.dll
-rwxrwxrwx 1 root root   29384 Jan 27  2015 System.Web.Http.Tracing.dll
-rwxrwxrwx 1 root root  471240 Jan 27  2015 System.Web.Http.dll
-rwxrwxrwx 1 root root     627 May  4 12:56 Upstart.config
-rwxrwxrwx 1 root root  181248 Jan 23 02:12 YamlDotNet.dll

**Comment by flightlevel** [comment]
Didn't realize you didn't have access @kaso17 , have added you now to AppVeyor

Happy to have a go at the above
The build system runs on Windows which obviously handles permissions very differently to Linux
Any suggestions?
Will chocolatey cygwin chmod 755 do it?

**Comment by kaso17** [comment]
I guess not, seems like 7z is executed in a normal windows environment and defaults to 777 in this case.
Is cygwin available for appveyor, then we should be able to use cgywin's tar instead of 7zip to work around the problem.
Is there some kind of shell you can get to play around with the scripts (never used appveyor before) or what's the script development process?

**Comment by flightlevel** [comment]
Under the build tab, we have an after build script (really should commit the appveyor.yml in case we lost access to the appveyor account) as below

```
xcopy src\Jackett.Console\bin\Release build.windows\  /e /y
copy /Y src\Jackett.Service\bin\Release\JackettService.exe* %APPVEYOR_BUILD_FOLDER%\build.windows\
copy /Y src\Jackett.Tray\bin\Release\JackettTray.exe* %APPVEYOR_BUILD_FOLDER%\build.windows\
copy /Y src\Jackett.Updater\bin\Release\JackettUpdater.exe* %APPVEYOR_BUILD_FOLDER%\build.windows\
copy /Y LICENSE build.windows\LICENSE
copy /Y README.md build.windows\README.md

xcopy build.windows WindowsBuild\Jackett\ /e /y

msbuild src\Jackett.sln /t:Clean /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
"C:\Program Files (x86)\Mono\bin\xbuild.bat" src\Jackett.sln /t:Build /p:Configuration=Release /verbosity:minimal /tv:12.0

xcopy src\Jackett.Console\bin\Release build.mono\  /e /y
copy /Y src\Jackett.Service\bin\Release\JackettService.exe* %APPVEYOR_BUILD_FOLDER%\build.mono\
copy /Y src\Jackett.Tray\bin\Release\JackettTray.exe* %APPVEYOR_BUILD_FOLDER%\build.mono\
copy /Y src\Jackett.Updater\bin\Release\JackettUpdater.exe* %APPVEYOR_BUILD_FOLDER%\build.mono\
copy /Y LICENSE build.mono\LICENSE
copy /Y README.md build.mono\README.md
copy /Y Upstart.config build.mono\Upstart.config

xcopy build.mono MonoBuild\Jackett\ /e /y

"C:\Program Files (x86)\Inno Setup 5\ISCC.exe" Installer.iss
RENAME Output\setup.exe Jackett.Installer.Windows.exe
MOVE Output\Jackett.Installer.Windows.exe %APPVEYOR_BUILD_FOLDER%

cd WindowsBuild
7z a -tzip -r "%APPVEYOR_BUILD_FOLDER%\Jackett.Binaries.Windows.zip" "Jackett\"

cd %APPVEYOR_BUILD_FOLDER%
cd MonoBuild
7z a -ttar "%APPVEYOR_BUILD_FOLDER%\Jackett.Binaries.Mono.tar" "Jackett\"
cd %APPVEYOR_BUILD_FOLDER%
7z a -tgzip "Jackett.Binaries.Mono.tar.gz" "Jackett.Binaries.Mono.tar"

appveyor PushArtifact Jackett.Installer.Windows.exe
appveyor PushArtifact Jackett.Binaries.Windows.zip
appveyor PushArtifact Jackett.Binaries.Mono.tar.gz
```

You were right AppVeyor does already include cygwin, so it doesn't even need to be downloaded. https://www.appveyor.com/docs/build-environment/#mingw-msys-cygwin Read that git bash might be an option to chmod as well ???

When I initially set it all up I just kept firing off new builds from AppVeyor after changing the script as you can't really do any damage since all our output goes to draft first which isn't publicly accessible. This looks like a good option though https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
