### ISSUE TITLE
Jackett RSS through qBittorrent - WORKS using IPV4 address login; however, behind my domain (ie. wiffleman.com), doesn't work!

### ISSUE THREAD

**Issue by wiffleman** [Jackett/Jackett#13362]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett running behind Docker container. Access available via two pathways: (1) IPV4:port address, and (2) behind my domain name ie. "jackett.wiffleman.com" which is routed via a custom domain name and Traefik.
```

### Description

When trying to generate RSS torrent lists through Jackett, and within qBittorrent, I am able to populate the lists properly when using the "RSS link" generated within the IPV4 port address (xx.xx.xx.xx:port/api/...). Unfortunately, when I try to generate it through my custom domain name address (jackett.wiffleman.com/api/...) - the RSS will not populate.

The **interesting** thing is that looking the query to Jackett IS logged within Jackett when using the domain name pathway - but the items just don't show up..

Unsure if I have described this issue adequately - please let me know if anything is unclear.

Thanks!

### Logged Error Messages

```text
No error messages recorded within Jackett.
```

**Comment by garfield69** [comment]
do you have the Jackett dashboard `external access` enabled?
what are your `Base Path Override` and `Base URL Override` set to?
is the `server port` open to WAN on router/firewall?
@ilike2burnthing  any other relevant questions about this docker/private domain set up we need to get answers for?

**Comment by ilike2burnthing** [comment]
That seems to cover it, I'd just link to this as well for a sanity check - https://github.com/Jackett/Jackett/wiki/Reverse-Proxy
