### ISSUE TITLE
[req]: Sonarr anime compatibility enhancement with 4 digits

### ISSUE THREAD

**Issue by neoestremi** [Jackett/Jackett#13370]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

When searching for episodes of anime with more than 999 episodes, the enhancement doesn't work.
Exemple : With the enhancement enabled, searching "one piece 999" returns results for "one piece e999" but searching for "one piece 1000" returns results for "one piece 1000" instead of "one piece e1000"

### Describe the solution you'd like

Maybe extend the remplacement to 4 digits or add another checkbox for that in addition to the first one.

### Describe alternatives you've considered

If the enhancement is enabled, do the research normally, without the added "e", then with it before the last number, without counting the number of digits.

**Comment by ilike2burnthing** [comment]
I take it you're referring to the option in yggtorrent/yggcookie?

I believe this was restricted to 2 or 3 digits because 4 would then break all search terms and result titles which contain a year.

Considering that, would you still want this option?

**Comment by neoestremi** [comment]
Exactly this option.
I actually have both trackers, one without the option and the other one with it, so I can have both results, and this way, even if I have broken results, the other one is giving the good ones :)
So, in my case yes, I would still want it.

**Comment by garfield69** [comment]
v0.20.1322
