### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by yjiawqgj** [Jackett/Jackett#13375]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
synology DS920+ 
Use the ROOT command
```

### Description

Use the SSH command to refer to the command "A) Command to download and install latest package and run the Jackett service" in the step of Install on Linux (AMDx64) on github. After executing the command, the following error appears "Checking if the service 'jackett.service" ' is running...
Service 'jackett.service' is not running
Jackett will be installed in '/opt/Jackett'
ERROR: The owner of Jackett directory is 'UNKNOWN'.
Please, change the owner with the command 'chown <user>:<user> -R "/opt/Jackett"'
The user <user> will be used to run Jackett.
"
But using ./jackett has no problem

### Logged Error Messages

```text
There are no logs because it is not started
```

### Screenshots

![QQ图片20220718205630](https://user-images.githubusercontent.com/71002956/179516002-353ead7f-f663-4b4c-8f23-4d08d12ba3d8.png)

**Comment by garfield69** [comment]
I thought installs on syno required a specific build such as what the readme points to with https://github.com/Jackett/Jackett#installation-on-synology ?

**Comment by ilike2burnthing** [comment]
Yea, I wasn't sure if that was just easier or actually necessary.

The old instructions for installing natively on Synology involved using `chown -R {user who will run jackett} Jackett` - https://github.com/Jackett/Jackett/blob/f6240c3cf00582e86d566d81872efeb7f84efbb0/README.md#installation-on-synology

That was then replaced by the SynoCommunity link - https://github.com/Jackett/Jackett/commit/0652e9b42d47721e62089132706ba7621ff382c4

**Comment by yjiawqgj** [comment]
> 使用 Docker 会容易得多。
> 
> 如果您仍然想在本地安装它，您是否尝试过按照说明操作并使用该文件夹？

Note: I am in Chinese, this is the feedback I translated and submitted using GOOGLE. I am using the root user, so I followed the prompt "chown root:root -R otp/Jackett/" without any prompts, and then executed "A) Command to download and install latest package and run the Jackett service:" The string of SSH commands described here will still produce the same error.
![image](https://user-images.githubusercontent.com/71002956/179654336-2984f774-da3b-485b-8f2a-4b962ccf74f2.png)

**Comment by ilike2burnthing** [comment]
Strange. Although Jackett shouldn't be run as root anyway.

Is there a reason you aren't using Docker or the SynoCommunity package?

**Comment by yjiawqgj** [comment]
> 



> 尽管Jackett应该以 root 身份运行。
> 
> 您不使用 Docker 或 SynoCommunity 是否有原因？

First, docker is run in a virtual-like manner, which causes system stress and waste. Second, SynoCommunity cannot control the version independently, and there is no way to do anything when there is a problem, and it can only be solved through SynoCommunity.

**Comment by ilike2burnthing** [comment]
I'm running almost everything in Docker, the overhead is negligible. I suggest trying it.

You can install Jackett from SynoCommunity, update through Jackett, and never have to deal with SynoCommunity again.

**Comment by ilike2burnthing** [comment]
Click the yellow/orange `Check for updates` button to update now (if one is available).

Otherwise, just do not tick the `Disable auto update` setting and auto-updates will take care of the rest.
