### ISSUE TITLE
[torrentcore] new search path

### ISSUE THREAD

**Issue by scriptzteam** [Jackett/Jackett#13374]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
N/A
```

### Description

https://github.com/Jackett/Jackett/blob/3e56808a34ced52c52b27fcbd893164fccb1d860/src/Jackett.Common/Definitions/torrentcore.yml#L60

New search path is https://torrentcore.xyz/search?s=*

### Logged Error Messages

```text
N/A
```

**Comment by ilike2burnthing** [comment]
Well that's crap - no size, files, or categories now, and we can't use index page (at least not without rewriting in C#)

**Comment by ilike2burnthing** [comment]
@garfield69 the results are now just a single block, with the date just being a row of text and I'm not sure how to specify it.

**Comment by garfield69** [comment]
search engine results are not compatible with the cardigann processor.
it's not worth converting to a C# indexer either.
I've removed the indexer.

**Comment by garfield69** [comment]
v0.20.1326

**Comment by scriptzteam** [comment]
Seems search page got updated, will works now?

**Comment by garfield69** [comment]
>Seems search page got updated, will works now?

It's missing the size and files in the white font, which means the search page is not in the same layout as the index page.
Because each of the rows are not enclosed in a html tag, we have to instead resort to counting the font tags to gather the fields for each row, and the index has 4 and the search has 3 so this site is still not compatible.

**Comment by scriptzteam** [comment]
Now got size/files in search page like in index

https://i.imgur.com/XlI2ai0.png

**Comment by garfield69** [comment]
v0.20.1698
