### ISSUE TITLE
torrentleech.org incorrect categories

### ISSUE THREAD

**Issue by DevilStyle** [Jackett/Jackett#13378]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-07-19 15:14:08	Info	
Loading Native indexers ...
2022-07-19 15:14:08	Info	
Using HTTP Client: HttpWebClient2
2022-07-19 15:14:08	Info	
Using FlareSolverr: No
2022-07-19 15:14:08	Info	
Using proxy: Disabled
2022-07-19 15:14:08	Info	
App config/log directory: /home/phoenixdl/.config/Jackett
2022-07-19 15:14:08	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-07-19 15:14:08	Info	
Running in Docker: No
2022-07-19 15:14:08	Info	
File /etc/issue: Debian GNU/Linux 9 \n \l
2022-07-19 15:14:08	Info	
Jackett variant: CoreLinuxAmdx64
2022-07-19 15:14:08	Info	
OS version: Unix 4.9.0.19 (64bit OS) (64bit process)
2022-07-19 15:14:08	Info	
Environment version: 6.0.7 (/home/phoenixdl/Jackett/)
2022-07-19 15:14:07	Info	
Starting Jackett v0.20.1326
```

### Description

Hello everyone, I added the torrentleech.org private tracker as an indexer, unfortunately, however, in the rss link when I enter the numbers of the various categories, unfortunately they are not updated. They are all high. Can you please correct? A thousand thanks

### Logged Error Messages

```text
nothing
```

**Comment by ilike2burnthing** [comment]
A quick check doesn't show any issues here. Can you give an example of the difference between what Jackett has for the categories and what you're expecting to work?
