### ISSUE TITLE
rss load error with rtorrent

### ISSUE THREAD

**Issue by DevilStyle** [Jackett/Jackett#13382]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-07-19 15:14:08	Info	Loading Native indexers ...
2022-07-19 15:14:08	Info	Using HTTP Client: HttpWebClient2
2022-07-19 15:14:08	Info	Using FlareSolverr: No
2022-07-19 15:14:08	Info	Using proxy: Disabled
2022-07-19 15:14:08	Info	App config/log directory: /home/phoenixdl/.config/Jackett
2022-07-19 15:14:08	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-07-19 15:14:08	Info	Running in Docker: No
2022-07-19 15:14:08	Info	File /etc/issue: Debian GNU/Linux 9 \n \l
2022-07-19 15:14:08	Info	Jackett variant: CoreLinuxAmdx64
2022-07-19 15:14:08	Info	OS version: Unix 4.9.0.19 (64bit OS) (64bit process)
2022-07-19 15:14:08	Info	Environment version: 6.0.7 (/home/phoenixdl/Jackett/)
2022-07-19 15:14:07	Info	Starting Jackett v0.20.1326
```

### Description

Hi, I added a new indexer of torrentleech.org but when I copy the rss link from the dashboard, I try mad to add it on rutorrent but it tells me error as if the does not recognize the link. (obviously the rss link works on the chrome browser) Thanks

### Logged Error Messages

```text
...
```

**Comment by garfield69** [comment]
probably related to #5835 #5267 and I now pass the baton to anyone who knows more about rtorrent, rss and .torrent versus magnet stuff

**Comment by ilike2burnthing** [comment]
If you test with other torrent or RSS clients, does the issue continue, or is it just rtorrent?

If you test with other indexers on Jackett, does the issue continue, or is it just for torrentleech.org?

**Comment by DevilStyle** [comment]
> Se esegui il test con altri client torrent o RSS, il problema persiste o è solo rtorrent?
> 
> Se esegui il test con altri indicizzatori su Jackett, il problema persiste o è solo per torrentleech.org?

Thanks so much for the reply, I have tried with other torrent sites but it does the same. It also does this with other rss clients besides rtorrent / rutorrent

Thank you

**Comment by ilike2burnthing** [comment]
Are you using a proxy or VPN?

Are you using a reverse proxy?

Do you have anything set for your base URL override or base path override in Jackett?

**Comment by DevilStyle** [comment]
I am not using any reverse proxy, I have not set any base path override. I hope this problem is solved. Thank you

**Comment by ilike2burnthing** [comment]
You missed a couple of questions there.

**Comment by DevilStyle** [comment]
> 

In what sense? So what should I add or change in my settings? Thank you

**Comment by ilike2burnthing** [comment]
> Are you using a proxy or VPN?

_

> Are you using a reverse proxy?

I am not using any reverse proxy

>Do you have anything set for your base URL override [in Jackett?]

_

> [Do you have anything set for your] base path override in Jackett?

I have not set any base path override.

**Comment by DevilStyle** [comment]
> > Are you using a proxy or VPN?
> 
> _
> 
> > Are you using a reverse proxy?
> 
> I am not using any reverse proxy
> 
> > Do you have anything set for your base URL override [in Jackett?]
> 
> _
> 
> > [Do you have anything set for your] base path override in Jackett?
> 
> I have not set any base path override.

Thanks for the reply,
I did not understand what I have to set in the URL override and in the base path override. Thank you

**Comment by ilike2burnthing** [comment]
So you have nothing set for them? That's fine.

And are you using a proxy or VPN?

**Comment by DevilStyle** [comment]
> So you have nothing set for them? That's fine.
> 
> And are you using a proxy or VPN?
As I mentioned yesterday, if I put the rss link in the browser, it works. The problem remains When I enter the link in the rutorrent client. 
I don't use any VPN or proxy. Thank you

**Comment by ilike2burnthing** [comment]
RSS is working for me, yet for you it's not working for any client or indexer, but it is working in browser. The issue is definitely on your end, but unfortunately I'm not sure what else to suggest or look into.

**Comment by DevilStyle** [comment]
> RSS funziona per me, ma per te non funziona per nessun client o indicizzatore, ma funziona nel browser. Il problema è sicuramente dalla tua parte, ma sfortunatamente non sono sicuro di cos'altro suggerire o esaminare.

Which torrent client are you trying with? May I know what format is your rss link? Because it doesn't work for me via rutorrent client. Thank you

**Comment by ilike2burnthing** [comment]
qBittorrent is what I recently tested on, but I've previously used uTorrent and some random RSS client, they all worked fine with the default RSS feed - http://127.0.0.1:9117/api/v2.0/indexers/INDEXER/results/torznab/api?apikey=APIKEY&t=search&cat=&q=

**Comment by DevilStyle** [comment]
> qBittorrent is what I recently tested on, but I've previously used uTorrent and some random RSS client, they all worked fine with the default RSS feed - http://127.0.0.1:9117/api/v2.0/indexers/INDEXER/results/torznab/api?apikey=APIKEY&t=search&cat=&q=

I find it strange that it works for you and I don't, even I used qbittorrent to try but it tells me loading error. In the url instead of having 127.0.0.1 I have the IP of my server, but still it should go the same, if you want I can send you the rss address generated by me in a private message to verify. Thank you very much

**Comment by ilike2burnthing** [comment]
Sure, send it to jacketttest AT gmail DOT com

**Comment by DevilStyle** [comment]
> Sure, send it to jacketttest AT gmail DOT com

I sent you an email. Thanks again for the help

**Comment by ilike2burnthing** [comment]
Thanks.

I ran into 2 problems:

1. despite being just an IP address, it is forcing HTTPS rather than HTTP, and the certificate is for your VPS, so is invalid for the IP address
2. when bypassing the invalid certificate, it requires authorisation, something I'm not sure RSS clients can handle

One or both of those is/are the cause/s of your problem, so you'd either need to disable these if possible, or find some alternative, such as a reverse proxy.
