### ISSUE TITLE
Multiple Tracker/Indexer URLs

### ISSUE THREAD

**Issue by twistedroutes** [Jackett/Jackett#134]
There are a few trackers that have multiple URLs (TorrentDay, BitSoup etc.).  In some cases a user would have a preference to use one over others.

Creating an issue to discuss with 'team-jacket' the direction they'd like to take.  For bitsoup I have toyed with using the item types presently available as shown below.  This requires some verification code in the indexer code to ensure the user entered a valid value (which I've included).  A more user-friendly approach may be to create a select or series of radio group based on an input collection (which can also be used to validate).

![image](https://cloud.githubusercontent.com/assets/2973320/11969859/b9f2f304-a8ee-11e5-80a7-a01ebd46d8db.png)

![image](https://cloud.githubusercontent.com/assets/2973320/11969870/ebbb6d26-a8ee-11e5-8ee3-a49d73a7c1ce.png)

**Comment by blindpet** [comment]
This is exactly what I was thinking

**Comment by twistedroutes** [comment]
Would you use a text entry as I have done and of so would you make it validate against a list of allowable due URLs or allow custom entry.

Custom entry for allow a user to keep pace with site changes rather than wait for a new release and update to their indexer but it also allows them to misdirect traffic.  Bare minimum for a custom entry would be to validate that the entry is a valid URL terminating with '/'.  I'd suggest keeping the notification section to inform users of possible alternatives.

**Comment by twistedroutes** [comment]
well, I've just pushed an update that includes a template for doing this, as well as supporting simple proxies.  It's not accepted and there are many changes to support the enhancements I've made, so I have no idea how long it will take to be accepted or rejected by the Jackett team.

**Comment by twistedroutes** [comment]
Can someone label this as feature/enhancement?  Also, it's now been implemented

**Comment by JigSawFr** [comment]
@twistedroutes implemented on BITSOUP only ?

**Comment by kaso17** [comment]
Base URLs are now configurable for all indexers in pre-release v0.7.841, please try it.
I'll keep this one open as a reminder to make it a little bit more user friendly (e.g. autodetection of working URLs and/or clicking on the URLs will automatically fill the Site Link field).
