### ISSUE TITLE
Tracker categories torrentseeds.org busted 

### ISSUE THREAD

**Issue by DevilStyle** [Jackett/Jackett#13401]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-07-19 15:14:08	Info	Loading Native indexers ...
2022-07-19 15:14:08	Info	Using HTTP Client: HttpWebClient2
2022-07-19 15:14:08	Info	Using FlareSolverr: No
2022-07-19 15:14:08	Info	Using proxy: Disabled
2022-07-19 15:14:08	Info	App config/log directory: /home/phoenixdl/.config/Jackett
2022-07-19 15:14:08	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-07-19 15:14:08	Info	Running in Docker: No
2022-07-19 15:14:08	Info	File /etc/issue: Debian GNU/Linux 9 \n \l
2022-07-19 15:14:08	Info	Jackett variant: CoreLinuxAmdx64
2022-07-19 15:14:08	Info	OS version: Unix 4.9.0.19 (64bit OS) (64bit process)
2022-07-19 15:14:08	Info	Environment version: 6.0.7 (/home/phoenixdl/Jackett/)
2022-07-19 15:14:07	Info	Starting Jackett
```

### Description

Hello, I noticed that the categories of the tracker torrentseeds.org are missing, since they updated the tracker, added and edited the categories, can you check and possibly update them? Thank you very much 

### Logged Error Messages

```text
...
```

**Comment by garfield69** [comment]
Are you having difficulty setting up Radarr or Sonarr, is this why you are raising these tickets like #13378 and #13401 ?

**Comment by DevilStyle** [comment]
> I've just checked the torrentseeds.org categories and they appear to match what is loaded on the torrentseeds (API) indexer. See the custom categories (the ones in the 100000 range) which are a 1 to 1 match for the site cats. In fact the indexer (and site) has not changed since 27th of Feb when we updated the indexer with the changes beginning with Jackett v0.20.639 Your environment details in your POST is missing the Jackett version so I can not tell whether you are on a newer version. Are you perhaps running an older version of Jackett and need to update? [edit] added a 0 on the custom range.

Hello, thanks for your answer, the version I currently have is the latest version available (v0.20.1463), the categories are there as on the site, but for example in the category "Games" is generic instead of being for example "Nintendo Switch" "ps4" is so on, I hope you understand what I mean. Thank you very much

**Comment by garfield69** [comment]
Ah. what you are talking about is **not** _categories_, but **type**.
if you look at the web site, you see 
![image](https://user-images.githubusercontent.com/6933240/180889670-b3a28c30-c60e-4238-952e-217ac89eb6c7.png)

We currently can only specify the category in the search requests we make to the torrentseeds api

There are no plans to make _type_ a selectable option on our dashboard search page.
The reason for this is that the search page is a global single layout that has to handle all the indexers, and searching with type is only available for certain web site, its not a global standard like categories is.

@ilike2burnthing  anything you would like to add to this topic?

**Comment by ilike2burnthing** [comment]
I'd just add that we also wouldn't be able to switch from using categories to using types instead, as certain types cover multiple categories (e.g. WEB has both TV and Movies).
