### ISSUE TITLE
[Not a Bug] How to properly backup Jackett in Windows 10 ( No Docker )?

### ISSUE THREAD

**Issue by oscdat** [Jackett/Jackett#13407]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
2022-07-28 06:15:45	Info	
Using FlareSolverr: http://127.0.0.1:8191/
2022-07-28 06:15:45	Info	
Using proxy: Disabled
2022-07-28 06:15:45	Info	
App config/log directory: C:\ProgramData\Jackett
2022-07-28 06:15:45	Info	
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-07-28 06:15:45	Info	
Running in Docker: No
2022-07-28 06:15:45	Info	
Jackett variant: CoreWindows
2022-07-28 06:15:45	Info	
OS version: Microsoft Windows NT 10.0.19044.0 (64bit OS)
2022-07-28 06:15:45	Info	
Environment version: 6.0.7 (C:\ProgramData\Jackett\)
2022-07-28 06:15:44	Info	
Starting Jackett v0.20.1466
```

### Description

Can someone please give a comprehensive list of all the folders and files inside the Jackett's Program Data that needs to be saved separately inorder to import all of the current user & indexer settings ( with password ) during a fresh install.

I've searched everywhere for an answer and the only thread that came close was this one [#2576 ](https://github.com/Jackett/Jackett/issues/2576) but it's outdated and on top of that it's confusing as some of the newer replies are talking about exporting Jackett when installed with a Docker.

Also this is a humble request to add a small subcategory in the Wiki section guiding us on how to properly import / export Jackett just like how Sonarr has a section covering this topic.

### Logged Error Messages

```text
How to Backup / Export.
```

**Comment by ilike2burnthing** [comment]
Folders `DataProtection` and `Indexers`, and also the file `ServerConfig.json` if you want to transfer your Jackett settings.

**Comment by garfield69** [comment]
But note that if you export to a different platform the encryption keys from win10 will not be valid on linux or mac so you will have to follow up on the noew platform with a Jackett dashboard config edit of all your private indexers and re-enter and save the passwords.

**Comment by oscdat** [comment]
> 

Thank you so much, really appreciate it.

**Comment by Altansar69** [comment]
@ilike2burnthing Hi, sorry to disturb you. I install jackett on my new pc, i paste in the folder of jackett the folder DataProtection, Indexers and ServerConfig but nothing happens. My indexers don't appear on my new PC, and even the condigueration server doesn't seem to have updated. Do you have any ideas?

**Comment by ilike2burnthing** [comment]
Install Jackett, stop the Jackett service, copy across the folders and file mentioned in https://github.com/Jackett/Jackett/issues/13407#issuecomment-1197532302, replacing any as needed, start the service again, access Jackett in browser.

**Comment by Altansar69** [comment]
Nice it's works. Thank you !
