### ISSUE TITLE
Change T411.ai to T411.al !

### ISSUE THREAD

**Issue by NBSDEVApp** [Jackett/Jackett#1340]
Hi,
Recently t411 change url please update on jackett.
Thanks

**Comment by ApteryxK** [comment]
There is an issue indeed, I get "impossible d'établir une relation de confiance pour le canal sécurisé SSL/TLS." 
Relation de confiance meaning trust (handshake ? )
I can't seem to connect to my tracker, weird enough

**Comment by ApteryxK** [comment]
My bad, I had to update the Jackett. Works just fine. Good luck
