### ISSUE TITLE
High CPU Usage after some time

### ISSUE THREAD

**Issue by Stiefel1234eu** [Jackett/Jackett#13408]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using FlareSolverr: url
Using proxy: Disabled
Running in Docker: Yes
https://hub.docker.com/r/linuxserver/jackett/
Jackett Version v0.20.1470

Jacket used in the following apps:
Sonarr, Radarr
```

### Description

The following screenshot displays the cpu usage of the jackett docker container
![image](https://user-images.githubusercontent.com/63855548/181457437-69ada44c-1152-48cf-afbe-f47dd2a36c89.png)

As you can see after a restart the cpu usage is really low (htop: 0.1% with an AMD Ryzen 5 3600 6-Core Processor)

But after 15ish minutes the cpu usage raises to 160%

I found a few threads for example:
https://github.com/Jackett/Jackett/issues/2602
https://github.com/Jackett/Jackett/issues/12244

but the solution of most of them: "disable proxy" in jackett

My Jackett Configuration:
![image](https://user-images.githubusercontent.com/63855548/181459335-09252428-bd42-41ab-b946-9243ef99efac.png)

### Logged Error Messages

```text
Here the Startup log:

2022-07-28 10:15:04	Info	Loading Native indexers ...
2022-07-28 10:15:04	Info	Using HTTP Client: HttpWebClient2
2022-07-28 10:15:04	Info	Using FlareSolverr: http://flaresolverr:8191
2022-07-28 10:15:04	Info	Using proxy: Disabled
2022-07-28 10:15:04	Info	App config/log directory: /config/Jackett
2022-07-28 10:15:04	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-07-28 10:15:04	Info	Running in Docker: Yes (image build: v0.20.1470-ls74)
2022-07-28 10:15:04	Info	File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-07-28 10:15:04	Info	Jackett variant: CoreLinuxAmdx64
2022-07-28 10:15:04	Info	OS version: Unix 5.4.0.90 (64bit OS) (64bit process)
2022-07-28 10:15:04	Info	Environment version: 6.0.7 (/app/Jackett/)
2022-07-28 10:15:03	Info	Starting Jackett v0.20.1470
```

**Comment by garfield69** [comment]
Are you using the aggregate indexer ALL with Sonarr/Radarr, or just a few select indexers?
in total, how many active indexer have you got defined in Jackett, and are being used by Sonarr and Radarr, and are you using the RSS autoscan option and how long is the interval between queries set to?

Basically, I recommend avoid using the ALL indexer, and chose only a select few indexers to scan and not the whole library, and if using rss scanning, set the interval as large as you can, say once an hour or even longer. IMO no one needs torrent updates every 5 minutes, in fact I do mine once a day (but that is just me).

That is all I can contribute. If you feel this does not help then you are probably going to need some one with more code and network skills than I so this is where I bow out of this topic. Good luck.

**Comment by Stiefel1234eu** [comment]
@garfield69 
I am using 1337x, tpb, torrent downloads, yts
you mean the task intervals in sonarr/radarr? so the "rss sync"?

radarr:
![image](https://user-images.githubusercontent.com/63855548/181472048-433f73c6-0518-4c78-bef0-7c56e7a84525.png)

sonarr:
![image](https://user-images.githubusercontent.com/63855548/181472132-cd8570dc-737b-4b4a-8a75-4d29415b0a08.png)

**Comment by garfield69** [comment]
yeah I meant the rss sync. Radarr looks reasonable, sonarr is a bit too often IMO.
So you are using 4 indexers, and you have then defined individually in the *arr apps?
If that is the case, then at first glance it would seem that this should not account for the high cpu you are recording, in my uninformed opinion.
But I have no idea what if anything can be done about it. 
Hopefully other contributors may help.

**Comment by garfield69** [comment]
One other thought before I go, just for comparison, have you tried disabling the cache?

**Comment by Stiefel1234eu** [comment]
yes the indexers are manually defined in sonarr/radarr

fyi:
I forgot to change the PUID/PGID in my docker compose to something else than "root", which I changed now...
But I am not sure if that has something to do with it...

I will wait some time to check if the CPU usage raises. If so I will disable the cache in jackett :)

Will report later - thx so far!

**Comment by ilike2burnthing** [comment]
Yes, Jackett should not be run as root.

If you're enabling external access, you'll want to add an admin password in Jackett so that others can't access it.

**Comment by Stiefel1234eu** [comment]
I am using my Nginx Proxy infront of my applications.
So I wont need any protection on the applications side

**Comment by Stiefel1234eu** [comment]
Update:
it seems like that the root user caused this issue?!
![image](https://user-images.githubusercontent.com/63855548/181605922-90270da7-777e-4c49-9bc5-7845837ffa8a.png)

I will monitor it the next few days.. if it was just temporary I will disable the cache and come back here.

Thanks for your assistance!

Cheers Stephan

**Comment by Stiefel1234eu** [comment]
Update:
![image](https://user-images.githubusercontent.com/63855548/181880627-8242424f-6305-478a-b820-1f8cce51639f.png)

I think it has something to do with an indexers which is not rechable...

The Flaresolverr log is full of these:

2022-07-29T16:23:00+00:00 INFO REQ-104 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://1337x.st/cat/Movies/time/desc/1/"}
2022-07-29T16:23:02+00:00 INFO REQ-104 Cloudflare detected
2022-07-29T16:23:03+00:00 INFO REQ-104 Cloudflare Error: No challenge selectors found, unable to proceed.
2022-07-29T16:23:03+00:00 INFO REQ-104 Response in 2.145 s

Idk but I think 1337x changed something because if you visis the site, its not the normal Cloudflare checkpage:
![image](https://user-images.githubusercontent.com/63855548/181883927-538e697e-6164-4535-825e-8df2bd3d85ef.png)

**Comment by garfield69** [comment]
yeah, I have an open ticket on flaresolverr for this, https://github.com/FlareSolverr/FlareSolverr/issues/442
I hope @ngosang  can look into this soon, its starting to affect more and more indexers as time goes by.

**Comment by ngosang** [comment]
Fixed in:
FlareSolverr 2.2.5 => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.5
Jackett v0.20.1496 => https://github.com/Jackett/Jackett/releases/tag/v0.20.1496
