### ISSUE TITLE
[req]: Enable Raw Search for AvistaZ

### ISSUE THREAD

**Issue by MarcoGlauser** [Jackett/Jackett#13412]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Related to https://github.com/Jackett/Jackett/pull/13409

Sonarr can't find `Today's Webtoon`, since it's searching for `Todays Webtoon `

```
07-29 19:40:05 Info Torznab search in AvistaZ for Todays Webtoon S01E01 => Found 0 releases 
07-29 19:41:32 Info Manual search in AvistaZ for Today's Webtoon S01E01 => Found 2 releases 
```

### Describe the solution you'd like

Jackett should allow raw queries for AvistaZ to handle this case. There are many more shows with `'`  in the title and currently not properly working.

**Comment by garfield69** [comment]
v0.20.1489
