### ISSUE TITLE
[tapochek] (testing) Exception (tapochek): Error: Вы ввели неверный код подтверждения: Parse error

### ISSUE THREAD

**Issue by dshkoda32** [Jackett/Jackett#13414]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
2022-07-30 10:26:44	Info	Using FlareSolverr: No
2022-07-30 10:26:44	Info	Using proxy: Disabled
2022-07-30 10:26:44	Info	App config/log directory: /config/Jackett
2022-07-30 10:26:44	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-07-30 10:26:44	Info	Running in Docker: Yes (image build: v0.20.1326-ls74)
2022-07-30 10:26:44	Info	File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-07-30 10:26:44	Info	Jackett variant: CoreLinuxAmdx64
2022-07-30 10:26:44	Info	OS version: Unix 5.4.0.122 (64bit OS) (64bit process)
2022-07-30 10:26:44	Info	Environment version: 6.0.7 (/app/Jackett/)
2022-07-30 10:26:43	Info	Starting Jackett v0.20.1489
```

### Description

The login and password stopped coming, everything was still working yesterday

### Logged Error Messages

```text
2022-07-30 08:27:24.4709 Error Error on 20220730082724 for Tapochek.txtJackett.Common.ExceptionWithConfigData: Error: Р’С‹ РІРІРµР»Рё РЅРµРІРµСЂРЅС‹Р№ РєРѕРґ РїРѕРґС‚РІРµСЂР¶РґРµРЅРёСЏ
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 538
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 755
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1530
```

**Comment by garfield69** [comment]
- use your browser to login with the username and password, and if the login page gives you a challenge then fill that in too.
- then logout of tapochk.
- then use your Jackett dashboard to edit the tapochek config and replace the username and password and save.

if this does not work, then please provide an **enhanced** log so we can see what the verification details are about in the HTML that the site sends to jackett durin the indexer login.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
Thanks.

**Comment by dshkoda32** [comment]
Everything goes through the browser without any problems

**Comment by garfield69** [comment]
please provide an enhanced log so we can see what the verification details are about in the HTML that the site sends to jackett during the indexer login.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
Thanks.

**Comment by dshkoda32** [comment]
http://on.lampa32.ru/log.txt

**Comment by dshkoda32** [comment]
Is this the right log?

**Comment by ilike2burnthing** [comment]
It's the right log, however the Russian has been transformed into gibberish, so if there is a specific error there, we can't see it. Is that how it actually appears in your log file? If not, just attach the file here rather than using a third-party site.

**Comment by garfield69** [comment]
@ilike2burnthing  I'm wondering if we should switch this indexer to utf8

**Comment by ilike2burnthing** [comment]
Just checked the enhanced log here for accessing the login page, it's working without issue. The html definitely says it's using windows-1251.

**Comment by dshkoda32** [comment]
What do I need to provide to solve the problem

**Comment by ilike2burnthing** [comment]
The error from the log you posted is this:

> Error: Р’С‹ РІРІРµР»Рё РЅРµРІРµСЂРЅС‹Р№ РєРѕРґ РїРѕРґС‚РІРµСЂР¶РґРµРЅРёСЏ

Which is meaningless nonsense. I assume the site you have posted it on is the cause, and that's not how your actual log appears, as the error in the title of your issue shows correctly as:

> Error: Вы ввели неверный код подтверждения

Therefore, please attach the log file directly here, not to a third party-site.

**Comment by dshkoda32** [comment]
2022-07-30 08:27:24.4709 Error Error on 20220730082724 for Tapochek.txtJackett.Common.ExceptionWithConfigData: Error: Вы ввели неверный код подтверждения
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 538
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 755
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1530




<!DOCTYPE html>
<html lang="ru">
<head>
 <title>Tapochek.net</title>
 <meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
 <meta http-equiv="Content-Style-Type" content="text/css" />
 <link rel="stylesheet" href="./templates/default/css/main.css?v=55_" type="text/css">
<link href="./misc/js/ui-lightness/jquery-ui-1.9.2.custom.css?v=55" rel="stylesheet" />

<link rel="search" type="application/opensearchdescription+xml" href="opensearch_desc_bt.xml" title="Tapochek.NET (Tracker)" />
<link rel="alternate" type="application/rss+xml" title="Tapochek.NET new games" href="rss/rssdg.xml" />
<link rel="alternate" type="application/rss+xml" title="Tapochek.NET new messages" href="rss/rss.xml" />
<link rel="alternate" type="application/rss+xml" title="Tapochek.NET new topics" href="rss/rss-topic.xml" />
<link rel="alternate" type="application/rss+xml" title="Tapochek.NET 100 messages" href="rss/rss-100.xml" />
<link rel="alternate" type="application/rss+xml" title="Tapochek.NET 100 topics" href="rss/rss-100-topic.xml" />
<link rel="alternate" type="application/rss+xml" title="Tapochek.NET All torrents" href="rss/rssd.xml" />
  <link rel="stylesheet" type="text/css" href="templates/default/css/report_hack.css" />
 <link rel="shortcut icon" href="./favicon.ico" type="image/x-icon">
 <script type="text/javascript" src="./misc/js/jquery.pack.js?v=28"></script>
<script type="text/javascript" src="./misc/js/ui/jquery.mousewheel.js?v=28"></script>
<script type="text/javascript" src="./misc/js/ui/jquery.scrollable.js?v=28"></script>
<script type="text/javascript" src="./misc/js/jquery.cluetip.js?v=28"></script>
<script type="text/javascript" src="./misc/js/jquery-ui-1.9.2.custom.min.js?v=28"></script>
<script type="text/javascript" src="./misc/js/main.js?lol&v=28"></script>
<script type="text/javascript" src="./misc/js/jquery.rater.js?v=28"></script>
<script type="text/javascript" src="./misc/js/dklab_realplexor.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$('a.load-local').cluetip({local:true, cursor: 'pointer',showTitle: true,arrows: true, clickThrough:true});
		$('a.load-local-menu').cluetip({local:true, activation: 'click', cursor: 'pointer',showTitle: true,sticky: true, closePosition: 'title', width: 500, height: 500, closeText: 'Закрыть', cluetipClass: 'jtip'});
		$('span[title]').tooltip();
		$.ionSound({
			sounds: [
				{name: "new_pm"},
				{name: "pm_chat"},
			],
			path: "./misc/sounds/",
			preload: true,
			volume: 1.0
		});

		var realplexor = new Dklab_Realplexor("http://rpl2.tapochek.net/");
		realplexor.subscribe('id_guest_4e23f18d61c9224931793136005b0c02', function() {});
		realplexor.subscribe('main', function(data,id)
		{
			if(data.pm)
			{
				if(1) $.ionSound.play('new_pm');
				$('div.u-pm-cnt').remove();
				if(document.webkitVisibilityState != 'visible') $('title').text('('+data.cnt+') Tapochek.net');
				$(window).focus(function(e) {$("title").text('Tapochek.net');});
				$('#u-profile').append('<div class="u-pm-cnt" title="'+data.title+'"><a title="'+data.title+'" href="privmsg.php?folder=inbox">'+data.cnt+'</a></div>');
			}
			else
			{
							}
		});
				realplexor.execute();
	});
	</script>
	<script type="text/javascript">
  var BB_ROOT       = "./";
  var cookieDomain  = ".tapochek.net";
  var cookiePath    = "/";
  var cookieSecure  = 0;
  var cookiePrefix  = "bb_";
  var LOGGED_IN     = 0;
  var InfoWinParams = 'HEIGHT=510,resizable=yes,WIDTH=780';

  var user = {
  	opt_js: {},

  	set: function(opt, val, days, reload) {
  		this.opt_js[opt] = val;
  		setCookie('opt_js', $.toJSON(this.opt_js), days);
  		if (reload) {
  			window.location.reload();
  		}
  	}
  }
  
  var ajax = new Ajax('./ajax.php', 'POST', 'json');

   </script>

**Comment by dshkoda32** [comment]
<style type="text/css">.menu-sub, #ajax-loading, #ajax-error, var.ajax-params { display: none; } /* temp */ /* temp end */</style>
<script type="text/javascript" src="./misc/js/glossy.js"></script>
</head>

<body class="winter" onload="body_load(); return true;">

<script>
    (function(w,d,o,g,r,a,m){
        var cid=(Math.random()*1e17).toString(36);d.write('<div id="'+cid+'"></div>');
        w[r]=w[r]||function(){(w[r+'l']=w[r+'l']||[]).push(arguments)};
        function e(b,w,r){if((w[r+'h']=b.pop())&&!w.ABN){
            var a=d.createElement(o),p=d.getElementsByTagName(o)[0];a.async=1;
            a.src='//cdn.'+w[r+'h']+'/libs/e.js';a.onerror=function(){e(g,w,r)};
            p.parentNode.insertBefore(a,p)}}e(g,w,r);
        w[r](cid,{id:1947006066,domain:w[r+'h']});
    })(window,document,'script',['trafficbass.com'],'ABNS');
</script>

<script>
function web_news() {
	$web_news = $('#web_news');
	$web_news.toggle();
	if (!$web_news.data('loaded'))
		ajax.web_news();
}
ajax.web_news = function() {
    ajax.exec({
		action : 'web_news'
	});
};
ajax.callback.web_news = function(data){
	$web_news = $('#web_news');
	$('td', $web_news).html(data.html);
	$web_news.data('loaded', 1);
};
</script>


<div id="layer" style="display: none;"></div>
<div id="ajax-loading"></div>
<table id="ajax-error" cellpadding="0" cellspacing="0"><tr><td>Ошибка</td></tr></table>
<div id="preload" style="position: absolute; overflow: hidden; top: 0; left: 0; height: 1px; width: 1px;"></div>
<div id="body_container">

**Comment by dshkoda32** [comment]
/div>
<script>
var toggle  = document.getElementById("toggle");
var content = document.getElementById("newyear");

toggle.addEventListener("click", function() {
  content.style.display = (content.dataset.toggled ^= 1) ? "block" : "none";
});
</script>
<script src="yagirlyanda1.js"></script>
-->







<br>
<table cellpadding="0" cellspacing="0" width="100%">
	<tbody>
	<tr style="height:100px;">
	
		<td width="230">	<a href="./index.php"><img src="images/logo/leto_odnako.png" alt="Tapochek.net" /></a></a></td>
</style>
		<td align="center" valign="middle" width="100%">
		 <script type="text/javascript">
var _0x7c4d=

**Comment by dshkoda32** [comment]
</script>


										</td>
	
		</tr>
		
	</tbody>
</table>




<div class="topmenu">
   <table width="100%" cellpadding="0" cellspacing="0">
   <tr>

            <td class="tCenter pad_2">
         <a href="profile.php?mode=register" id="register_link"><b>Регистрация</b></a>
         &nbsp;&#0183;&nbsp;
         <form action="https://tapochek.net/login.php" method="post" class="expose">
            Имя: <input type="text" name="login_username" size="12" tabindex="1" accesskey="l" />
            Пароль: <input type="password" name="login_password" size="12" tabindex="2" />
            <label title="Автоматически входить при каждом посещении"><input type="checkbox" name="autologin" value="1" tabindex="3" /> Запомнить</label>&nbsp;
            <input type="submit" name="login" value="Вход" tabindex="4" />
         </form>
<script type="text/javascript" src="./misc/js/ui/jquery.expose.js?v=28"></script>
<script type="text/javascript">
$(function() {
  $("form.expose").click(function() {
    $(this).expose({
      color: '#ccc',
      onLoad: function() {
        this.getExposed().css({backgroundColor: null});
      },
      onClose: function() {
        this.getExposed().css({backgroundColor: null});
      }
    });
  });
});
</script>

         &nbsp;&#0183;&nbsp;
         <a href="profile.php?mode=sendpassword">Забыли пароль?</a>
      </td>
         </tr>
   </table>
</div>













</div>











<div id="page_content">
	
	<table cellspacing="0" cellpadding="0" border="0" style="width: 100%;">
<tr><td colspan="2" align="center"></td></tr> <tr>

  <td id="main_content">
<br>
	     <div id="main_content_wrap">
    
	   



<script type="text/javascript">
$(function(){
	$('#cse-search-btn, #cse-search-btn-top').click(function(){
		var text_match_input_id = $(this).attr('href');
		var text_match = $('#'+text_match_input_id).val();
		if (text_match == '') {
			$('#'+text_match_input_id).addClass('hl-err-input').focus();
			return false;
		}
		$('#cse-text-match').val( text_match );
		$('#cse-submit-btn').click();
		return false;
	});

	$('#quick-search').submit(function(){
		var action = $('#search-action').val();
		var txt = $('#search-text').val();
		if (txt=='поиск...' || txt == '') {
			$('#search-text').val('').addClass('hl-err-input').focus();
			return false;
		}
		if (action == 'cse') {
			$('#cse-search-btn-top').click();
			return false;
		}
		else {
			$(this).attr('action', action);
		}
	});
});
</script>




<script type="text/javascript">
$(function(){
	$('a.dl-stub').click(function(){
		$('#dl-form').attr('action', this.href);
		$('#dl-sid').val( getCookie('bb_sid') );
		$('#dl-form').submit();
		return false;
	});
});
</script>
<div style="display: none;">
	<form action="" id="dl-form"  method="post">
		<input id="dl-sid" type="hidden" name="sid" value="" />
	</form>
</div>

**Comment by dshkoda32** [comment]
<style type="text/css" media="all">
table, tr, td { font-family: Verdana, Tahoma, Arial, sans-serif; font-size: 11px; color: #000; }
.tablefill   { border:1px solid #345487;background-color:#F5F9FD;padding:6px;  }
</style>

<table width="100%" height="85%" align="center">
<tr>
  <td valign="middle">
	  <table align="center" cellpadding="4" class="tablefill">
	  <tr> 
		<td width="100%" align="center">

			<h1 class="pagetitle" align="center">Вход</h1>

			<form action="https://tapochek.net/login.php" method="post">

			<input type="hidden" name="redirect" value="/tracker.php?f" />
			<input type="hidden" name="cookie_test" value="1823092562" />
			<input type="hidden" name="confirm_id" value="Z1jmlH6xBze1" /><input type="hidden" name="sid" value="HcyDbGRjaFnERfiFwZPg" />			
			<table class="forumline">
			<tr>
				<th>Введите ваше имя и пароль для входа в систему</th>
			</tr>
			<tr >
				<td class="row1">

				
				<div class="mrg_16">
				<table class="borderless bCenter">
				<tr>
					<td width="35%" align="right">Имя:</td>
					<td><input type="text" class="post" name="login_username" size="25" maxlength="40" value=""  /></td>
				</tr>
				<tr>
					<td align="right">Пароль:</td>
					<td><input type="password" class="post" name="login_password" size="25" maxlength="32" /></td>
				</tr>
						<tr>
			<td align="right" nowrap>Код подтверждения:</td>
				<td><div>
			<img src="profile.php?mode=confirm&amp;id=Z1jmlH6xBze1" alt="" title="" />
		</div><div>
				<input type="text" name="cfmcd" size="35" maxlength="6" /></div></td>
			</tr>
							

				</td>
			</tr>
				<tr>
					<td colspan="2" class="tCenter nowrap">Автоматически входить при каждом посещении: <input type="checkbox" name="autologin" checked="checked" /></td>
				</tr>
				<tr>
					<td colspan="2" class="warnColor1 tCenter" style="">Куки должны быть включены!</td>
				</tr>
				<tr>
					<td colspan="2" class="tCenter pad_6"><input type="submit" name="login" class="bold long" value="Вход" /></td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<a href="profile.php?mode=sendpassword" class="small">Забыли пароль?</a>&nbsp;|&nbsp;
						<a href="profile.php?mode=register" class="small register_link" style="color:red;"><b>Регистрация</b></a>
					</td>
				</tr>
				</table>
				</div>

				</td>
			</tr>


			</table>

			</form>

	    </td>
	  </tr>
	</table>
  </td>
</tr>
</table>


	</div>
	</td>

	
	</tr></table>
	</div>
	
	<div id="nav-panel" class="nav-hidden-arrow">
	  <div id="nav-up" class="nav-btn" title="Вверх">
	    <span class="nav-icon"></span>
	  </div>
	  <div id="nav-settings" class="nav-btn">
	    <span class="nav-icon" title="Настройки"></span>
	    <ul id="nav-opt-menu">
	      <li class="nav-event" data-event="click">Показывать по клику</li>
	      <li class="nav-event" data-event="mouseenter">Показывать по наведению</li>
	    </ul>
	  </div>
	  <div id="nav-down" class="nav-btn" title="Вниз">
	    <span class="nav-icon"></span>
	  </div>
	  <div class="nav-hidden-overlay"></div>
	</div>


	<div id="page_footer">
    <script>
(function(){function b(){var a=document.getElementById("gotop");a||(a=document.createElement("a"),a.id="gotop",a.className="scrollTop",a.href="#",a.style.display="none",a.style.position="fixed",a.style.zIndex="9999",a.onclick=function(a){a.preventDefault();window.top.goTop()},document.body.appendChild(a));300<(document.body.scrollTop||document.documentElement.scrollTop)?(a.style.display="block",l(a,"show",30,!1)):l(a,"hide",30,function(){a.style.display="none"});return!1}function l(a,e,f,c){function k(){g<
h?(d+=5,d<h?window.top.timeout=setTimeout(k,f):c&&c()):(d-=5,d>h?window.top.timeout=setTimeout(k,f):c&&c());var e=a,b=d;e.style.opacity=b/100;e.style.filter="alpha(opacity="+b+")"}var g=Math.round(100*a.style.opacity),d=g,h="show"==e?100:0;clearTimeout(window.top.timeout);window.top.timeout=setTimeout(k,30)}window.addEventListener?(window.addEventListener("scroll",b,!1),window.addEventListener("load",b,!1)):window.attachEvent&&(window.attachEvent("onscroll",b),window.attachEvent("onload",b));window.top.goTop=
function(a,e){a=a||0.1;e=e||12;var f=0,c=0,b=0,g=0,d=0,h=0;document.documentElement&&(f=document.documentElement.scrollLeft||0,c=document.documentElement.scrollTop||0);document.body&&(b=document.body.scrollLeft||0,g=document.body.scrollTop||0);d=window.scrollX||0;h=window.scrollY||0;f=Math.max(d,Math.max(b,f));c=Math.max(h,Math.max(g,c));g=1+a;window.scrollTo(Math.floor(f/g),Math.floor(c/g));(0<f||0<c)&&window.setTimeout("top.goTop("+a+", "+e+")",e);return!1}})();
</script>

<style>
.scrollTop{
	background:url('https://tapochek.net/images/up3.png') 0 0 no-repeat;
	width:50px; height:46px;
	bottom:7px; right:48%;
}
.scrollTop:hover{ background-position:0 -50px; }
</style>
					<table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
<tr>
	<td align="center"></td>
</tr>
</table>		
		<div class="med bold tCenter">
			<a href="misc.php?do=info&show=callback" onclick="window.open(this.href, '', InfoWinParams); return false;">Связь с администрацией</a>
		</div>
		<br />
																				<div style="display:none;"></div>
				<div class="clear"></div>
		<br /><br />

		  
		<div class="copyright tleft" align="center">
			Tracker	Powered by TorrentPier</a> &copy; + <a href=http://xbtt.sf.net/ target="_blank">XBTT</a> &copy; <strong>Meithar</strong>, RoadTrain | Последующая доработка и модификации <a href="https://tapochek.net/profile.php?mode=viewprofile&u=3">KasperGreen</a>,  <a href="https://tapochek.net/profile.php?mode=viewprofile&u=35704">Roman</a><br />
			Search Powered by <a href="http://www.sphinxsearch.com" target="_blank">Sphinx</a><br />
			Форум представлен на базе <a href="https://www.phpbb.com">phpBB</a> &copy; phpBB Group <br />
		</div>

	</div>

	<div class="copyright" align="center">
	<br /><b style="color: rgb(204, 0, 0);">!ВНИМАНИЕ!</b><br />Сайт не предоставляет электронные версии произведений, а занимается лишь коллекционированием и каталогизацией ссылок, присылаемых и публикуемых на форуме нашими читателями.<br /> 
<div></div>
	<div align="right">
		<script type="text/javascript">document.write("<a href='http://www.liveinternet.ru/click' target=_blank><img src='//counter.yadro.ru/hit?t16.2;r" + escape(document.referrer) + ((typeof(screen)=="undefined")?"":";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?screen.colorDepth:screen.pixelDepth)) + ";u" + escape(document.URL) + ";" + Math.random() + "' border=0 width=88 height=31 alt='' title='LiveInternet: показано число просмотров за 24 часа, посетителей за 24 часа и за сегодня'><\/a>")</script>
	</div>

		</div>
	

	</div>
	
</div>
</body>
</html>

**Comment by ilike2burnthing** [comment]
If you are going to copy and paste something, do it in just one comment.

But please DON'T do that, just attach log files here, like this:
[log.txt](https://github.com/Jackett/Jackett/files/9228572/log.txt)

Please include the whole log file reproducing the issue, not clipped bits.

**Comment by dshkoda32** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/9228633/log.txt)

**Comment by ilike2burnthing** [comment]
Again, please stop clipping the bits you think are important and just provide a full enhanced log for the issue.

**Comment by dshkoda32** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/9228874/log.txt)

**Comment by ilike2burnthing** [comment]
Thanks. Unfortunately your credentials, domain, and IP were visible. I have redacted them and reposted the log. You should reset your password.

The log shows that the tracker is asking for a verification code, something I can't see when I access the site in browser.

Are you using a seedbox or VPS? If so, test with a local install of Jackett on your computer to see if the issue continues. If it doesn't, the IP of the server may be being flagged by the tracker for extra security.

**Comment by dshkoda32** [comment]
The jacket is installed on a virtual server, so I can't check its operability from there. The verification code was required once before registration. I go to the site without any problems. I don't understand why this error pops up, maybe they block my server, thinking it's a bot.

**Comment by ilike2burnthing** [comment]
Yes, that would make sense, and it's something we've seen before with other trackers.

You can use a proxy or VPN to fix the issue, or switch server.

**Comment by dshkoda32** [comment]
By the way, I noticed that if you add the socks 5 proxy and add the tapochek indexer, pass the test and then turn off the proxy, then the tracker will pass the test successfully for about a month.
