### ISSUE TITLE
[selezen] (updating) Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by dshkoda32** [Jackett/Jackett#13427]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
2022-07-31 01:20:07	Info	
Using FlareSolverr: No
2022-07-31 01:20:07	Info	
Using proxy: Disabled
2022-07-31 01:20:07	Info	
App config/log directory: /config/Jackett
2022-07-31 01:20:07	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-07-31 01:20:07	Info	
Running in Docker: Yes (image build: v0.20.1326-ls74)
2022-07-31 01:20:07	Info	
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-07-31 01:20:07	Info	
Jackett variant: CoreLinuxAmdx64
2022-07-31 01:20:07	Info	
OS version: Unix 5.4.0.122 (64bit OS) (64bit process)
2022-07-31 01:20:07	Info	
Environment version: 6.0.7 (/app/Jackett/)
2022-07-31 01:20:05	Info	
Starting Jackett v0.20.1496
```

### Description

The selezen parser stopped passing the test, none of the addresses works, everything opens through the browser

### Logged Error Messages

```text
Log
```

**Comment by dshkoda32** [comment]
Log adress http://on.lampa32.ru/log2.txt

**Comment by garfield69** [comment]
Access your Jackett dashboard and click on the **Check for Updates** button to upgrade to v0.20.1504

**Comment by dshkoda32** [comment]
Ok. Thanks
