### ISSUE TITLE
cloudtorrents: configure downloadvolumefactor and fix search with no results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13421]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
v0.20.1496
```

### Description

* Configure DownloadVolumeFactor value
* Fix "query": "1234abcdf"

### Logged Error Messages

```text
CardigannIndexer (cloudtorrents): Error while parsing row '
<tr class="empty-state">
	<td colspan="6">Your query returned no torrents. Please try another query or try again later</td>
</tr>':

System.Exception: Error while parsing field=category, selector=a, value=<null>: Selector "a" didn't match 
<tr class="empty-state">
	<td colspan="6">Your query returned no torrents. Please try another query or try again later</td>
</tr>
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1622
```

**Comment by ilike2burnthing** [comment]
[v0.20.1518](https://github.com/Jackett/Jackett/releases/v0.20.1518)
