### ISSUE TITLE
[req]: mazepa

### ISSUE THREAD

**Issue by StevenRudenko** [Jackett/Jackett#13437]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: mazepa.to
- URL: https://mazepa.to
- Description: Videos tracker with Ukrainian soundtracks
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: registration is free

Engine: https://torrentpier.com/
```

**Comment by garfield69** [comment]
v0.20.1539

**Comment by ilike2burnthing** [comment]
https://mazepa.to/
- HTTP ERROR 500
- Could not connect to mysql server
- Bad gateway - Error code 502

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
I'm seeing `Error: Memcached extension not installed`. just me?

**Comment by ilike2burnthing** [comment]
back up (again...)

**Comment by garfield69** [comment]
https://mazepa.to/ cloudflare Bad gateway - Error code 502

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
- https://mazepa.to/ cloudflare Web server is down Error code 521
- HTTP 500 Internal Server Error
- Sorry, this forum is disabled. Try coming back later

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
- I'm getting ERR_NAME_NOT_RESOLVED, with all Uptrends checkpoints failing. 
- Wow. Must have crashed immediately after I ran the Jackett indexer test.
Now getting Error 1016 Origin DNS error

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://mazepa.to/ cloudflare Access denied Error code 1020
getting this using native, as well as proton VPN (Netherlands, USA, Japan) and hide.me VPN (France, Netherlands, Germany, Singapore, Spain, UK, USA)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://mazepa.to/ HTTP Timeout cloudflare 522

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13437#issuecomment-1861074284

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
Account not recognised, no email received for password reset. Just me?

**Comment by garfield69** [comment]
Just you. I can login via browser and indexer is working fine.

**Comment by ilike2burnthing** [comment]
Whoops, wrong tracker 🙄

**Comment by garfield69** [comment]
https://mazepa.to/ >  522 No Reason Phrase

**Comment by ilike2burnthing** [comment]
back up
