### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): Invalid URI: The hostname could not be parsed.: Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by morganorix** [Jackett/Jackett#13433]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [x] I have read the Contributing Guidelines

### Environment

```markdown
Linux debian. Environment docker-compose. Tout est à jour.
```

### Description

Impossible de se connecter sur yggtorrent (ET yggcookie) depuis ce matin sur Jackett. Flaresolverr fonctionne bien. J'ai changé mes DNS (FDN: https://www.fdn.fr/actions/dns/). J'ai redémarré mon serveur linux et mon docker. Rien n'y fait !

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (yggtorrent): Invalid URI: The hostname could not be parsed.: Parse error

AND

An error occurred while testing this indexer
Test search in YGGcookie => Found no results while trying to browse this tracker
```

### Screenshots

<img width="928" alt="Capture d’écran 2022-07-31 à 13 36 36" src="https://user-images.githubusercontent.com/4254819/182024432-906a2282-48fb-4783-a577-1440ba10d892.png">

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/13426

**Comment by morganorix** [comment]
Même problème après la MAJ de Jackett et Flaresolverr.

Pulling jackett ... done
Pulling flaresolverr ... done

**Comment by morganorix** [comment]
Ok thx c'est résolu avec la version 0.20.1504 ;-)
