### ISSUE TITLE
[btschool] (updating) Login Failed, got redirected.

### ISSUE THREAD

**Issue by vsin123** [Jackett/Jackett#13448]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2 
Using FlareSolverr: http://192.168.31.128:8191/ 
Using proxy: Disabled 
App config/log directory: /config/Jackett 
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
Running in Docker: Yes (image build: v0.20.1575-ls74) 
File /etc/issue: Ubuntu 20.04.4 LTS \n \l 
Jackett variant: CoreLinuxAmdx64 
OS version: Unix 4.4.180.0 (64bit OS) (64bit process) 
Environment version: 6.0.7 (/app/Jackett/) 
Starting Jackett v0.20.1575 
```

### Description

 An error occurred while updating this indexer
The operation was canceled.

### Logged Error Messages

```text
NULL
```

### Screenshots

NULL

**Comment by vsin123** [comment]
![image](https://user-images.githubusercontent.com/88284263/182797493-ed495055-1cd2-4102-961f-a4e149bf7f43.png)

**Comment by vsin123** [comment]
Did I reinstall with docker or it didn't fix it

**Comment by garfield69** [comment]
The fix will be included in the next release of Jackett due out in about 11 hours or so.
The the docker builders will create their own release using our source some time after that.

**Comment by vsin123** [comment]
> 该修复将包含在 Jackett 的下一个版本中，大约需要 11 个小时左右。 之后，docker builder 将使用我们的源代码创建他们自己的版本。

Thanks for your answer! I manually modified the btschool.yml configuration in docker

**Comment by garfield69** [comment]
And did it work for you?

**Comment by garfield69** [comment]
v0.20.1597

**Comment by vsin123** [comment]
> v0.20.1597

No, you need to manually replace the btschool.yml file in the docker container
https://github.com/Jackett/Jackett/commit/60ffb6796dca06b6d61d3483ba14253c3dcb2438

**Comment by ilike2burnthing** [comment]
If you're using v0.20.1597, you don't need to replace anything.
