### ISSUE TITLE
DonTorrent does not filter anything for TV/HD

### ISSUE THREAD

**Issue by octaviz** [Jackett/Jackett#13440]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.20.1518 
Docker version
NAS Synology
```

### Description

When you do the manual search of the DonTorrent indexer and filter only by TV/HD it shows nothing, but if you check the TV/SD and TV/HD boxes it shows SD and HD content with the correct category.

### Logged Error Messages

```text
NO log error
```

### Screenshots

![3](https://user-images.githubusercontent.com/856579/182078930-802cbd56-2887-4f47-a1ef-2d45c1c58026.png)

![2](https://user-images.githubusercontent.com/856579/182078810-5b96029d-0885-4a64-b260-9e411f93baa7.png)

**Comment by garfield69** [comment]
seems to apply to the ultimos page (keywordless search).
appears to work for keyword searches, for example `Primal` returns expected results separately and combined for 5030 5040

this indexer is written in C# and to my untrained eye is a huge steaming pile of ... confusion.
Needs a proper C# dev to decipher, its beyond my meagre skills.
Volunteers welcome.

**Comment by ilike2burnthing** [comment]
@javierjp93 @Lyuu17 can you have a look at this?

**Comment by garfield69** [comment]
v0.20.1563

**Comment by octaviz** [comment]
Thks!!!!
