### ISSUE TITLE
[req]: BakaBT - Separate Adult Content Categories

### ISSUE THREAD

**Issue by theTaikun** [Jackett/Jackett#13447]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

The indexer for BakaBT correctly recognizes broad categories such as Anime OVA, Manga, etc..., however for adult categories, there is a "hentai" modifier added to the broad category. Currently, Jackett doesn't account for this.

### Describe the solution you'd like

Separate categories for SFW and NSFW content. Example: Anime Series with a Hentai tag should be considered a Hentai Series.

### Describe alternatives you've considered

I plan to fork the project, and implement this feature myself. Issue opened just for documentation.

**Comment by garfield69** [comment]
v0.20.1597
