### ISSUE TITLE
[yggcookie] (testing) Exception (yggcookie): Hôte inconnu.: Hôte inconnu. (www5.yggtorrent.fi:443)

### ISSUE THREAD

**Issue by PierreAlexx01** [Jackett/Jackett#13446]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
windows
```

### Description

  error

### Logged Error Messages

```text
error
```

**Comment by ilike2burnthing** [comment]
> Please provide the details of the system Jackett is running on. The best way to do this is to restart Jackett, access the dashboard, view the log, and copy/paste the last 10 Info lines at the bottom of the log.

Are you able to access https://www5.yggtorrent.fi/ in browser on the same device?

Are you using a proxy or VPN for either your browser or Jackett?

Have you enabled DNS over HTTPS (DoH) for your browser?

**Comment by PierreAlexx01** [comment]
Je peut accèder a ce site dans le navigateur sur le meme appareil
je n'utilise pas de proxy ni de vpn
j'ai mis les dns de cloudflare sur mon pc

**Comment by ilike2burnthing** [comment]
Again, for the environment section:

> Please provide the details of the system Jackett is running on. The best way to do this is to restart Jackett, access the dashboard, view the log, and copy/paste the last 10 Info lines at the bottom of the log.

Aside from setting your DNS for your network connection, have you enabled DNS over HTTPS (DoH) for your browser?

**Comment by DevSide69** [comment]
I have the same issue than Pierre,
I not used any vpn or proxy, the website work on my browser but not with Jackett (same with YGGtorrent). 
I add DoH on my browser with --enable-features="dns-over-https<DoHTrial"--force-fieldtrials="DoHTrial/Group1"--force-fieldtrial-params="DoHTrial.Group1:serveur/https%3A%2F%2F1.1.1.1%2Fdns-query/method/POST on application target property. 
I also try with firefox, still using DoH (activate using firefox network settings) but not work too

**Comment by ilike2burnthing** [comment]
Without using DoH, can you still access https://www5.yggtorrent.fi/ in browser?

Is this also on a Windows device?

**Comment by DevSide69** [comment]
It's also on Windows and i can access without DoH

**Comment by ilike2burnthing** [comment]
Provide the output for running this in Command Prompt:

`curl -v https://www5.yggtorrent.fi/`

**Comment by DevSide69** [comment]
![image](https://user-images.githubusercontent.com/15063011/183869907-7bcd22b1-00ac-43e6-b0bb-e1a9edc70616.png)

**Comment by DevSide69** [comment]
I just tried with a vpn, and all work: 
![image](https://user-images.githubusercontent.com/15063011/183871027-d2f22f7a-8f95-4171-bcab-f333a6db6d29.png)

**Comment by ilike2burnthing** [comment]
If you're not already using Cloudflare for your DNS, try that. If you are, try switching to Google. You can try looking at other alternatives as well, but really either of the first 2 should work.

If those don't make a difference, then your solution is to use a VPN on your system or a proxy in Jackett's settings.

@PierreAlexx01 if you get the same for the `curl` command, then see the solution above.
