### ISSUE TITLE
Launch a manual search by URL

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#1345]
Hi guys,

To ease manual search, is it possible to do something like that:
http://url/Admin/Dashboard/Manual?query=Avatar

All the feature are already here but as the manual search is a pop up we can use it like that.
The final objective for me is to call a manual search in Javascript.

Thanks for your feedback,

R

**Comment by kaso17** [comment]
I agree that this would be useful (e.g. for browser search bar extensions, etc.).
Can you explain your javascript use case a little more? Do you want to generate a link which will do a manual search, just do a manual search from some other application or access jackett from another web app (via client side java script)?

**Comment by chibidev** [comment]
@raspdealer @Riz0 A minimal version is now available in v0.7.1609. You can launch a search by navigating to ```/Admin/Dashboard#search=whatever%20you%20want```

**Comment by raspdealer** [comment]
like a charm. Thanks

**Comment by kaso17** [comment]
improved it via 123bb4af5f85ac67fd91535e94eb9131163a1ad3 (tracker and category are now supported)

**Comment by Riz0** [comment]
@chibidev Works smoothly, thanks again!

**Comment by Lilla-Myare** [comment]
Any chance the Searchbox could be added? `&search=1080` for example

**Comment by ilike2burnthing** [comment]
This is already used:
`.../UI/Dashboard#search=1080&tracker=rarbg&category=5000&filter=type%3Apublic`

**Comment by Lilla-Myare** [comment]
> This is already used: `.../UI/Dashboard#search=1080&tracker=rarbg&category=5000&filter=type%3Apublic`

Sorry I was a bit unclear I realize, sorry for that. What is in `search=1080` ends up in the box labeled `Query` the box I mean is called `Search`. Not sure what to call it as it's a filter/subsearch of the results returned :)

Say I regularly search for `Dashboard#search=Moomin&category=2000,2010,2020,2030,2040,2045,2050,2060,2070&filter=all` and I prefer it in 1080p and x265 then I wanted to launch an url like this `Dashboard#search=Moomin&category=2000,2010,2020,2030,2040,2045,2050,2060,2070&filter=all&something=1080p+x265`  the few times it's blank I would only then clear the filter/subsearch.

Depending on importance or target I always enter something there manually now as it is.

**Comment by ilike2burnthing** [comment]
The top row `Query`, `Filter`, `Tracker`, `Category` are all part of the search form, hence why they can be added to the URL.

The secondary `Search` box, `Show # entries` and `Show dead torrent` at the top, as well as the indexers and categories filters at the bottom, are all part of the DataTables filters, and are only usable after results are returned.
