### ISSUE TITLE
xx.xx.xx.xx took too long to respond.

### ISSUE THREAD

**Issue by PBhadoo** [Jackett/Jackett#13457]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
https://hub.docker.com/r/linuxserver/jackett/
running on GCP
20.xx ubuntu server.
docker installed.
fresh server. updated.
```

### Description

I installed using this method.
https://hub.docker.com/r/linuxserver/jackett/

and also tried this
https://www.smarthomebeginner.com/install-jackett-using-docker/

CONTAINER ID   IMAGE                 COMMAND           CREATED         STATUS         PORTS                                       NAMES
c4d73ca0f442   boypt/cloud-torrent   "cloud-torrent"   3 seconds ago   Up 1 second    0.0.0.0:80->3000/tcp, :::80->3000/tcp       ct
665472b61c85   linuxserver/jackett   "/init"           3 minutes ago   Up 3 minutes   0.0.0.0:9117->9117/tcp, :::9117->9117/tcp   jackett

Tried another app to check, but just jackett isn't loading.

It says xx.xx.xx.xx took too long to respond.

i used

sudo docker create --name=jackett \
--restart=always \
-v /home/bhadoo/jackett/config:/config \
-v /home/bhadoo/jackett/downloads:/downloads \
-e PGID=1001 -e PUID=1001 \
-e TZ=Europe/London \
-p 9117:9117 \
linuxserver/jackett

also have tried different ports.

### Logged Error Messages

```text
na
```

**Comment by ilike2burnthing** [comment]
How are you trying to access it? `http://IP:Port` in browser?

Are other containers working and accessible?

Have you tried using Portainer?

**Comment by PBhadoo** [comment]
Installation via Portainer works.

Never heard of Portainer before, Thanks.

**Comment by noobietele** [comment]
how did you fix this ,getting the same error when trying access both Jackett & Portainer, can't reach this page,xx.xx.xx.xx took too long to respond
