### ISSUE TITLE
How to get only search results for imdbid that include 1080p and NTb?

### ISSUE THREAD

**Issue by erickyun** [Jackett/Jackett#13463]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
On Heroku app
```

### Description

I tried myself but this isn't working me?
I would appreciate if you could help me?
What am I missing here?

https://jack.com/api/v2.0/indexers/rarbg/results/torznab/api?apikey=xxxxx&t=tv&cat=5040,100041&imdbid=tt3032476&search=1080p+NTb

### Logged Error Messages

```text
.
```

**Comment by ilike2burnthing** [comment]
The format used would be:
https://jack.com/api/v2.0/indexers/rarbg/results/torznab/api?apikey=xxxxx&t=tvsearch&cat=5040,100041&imdbid=tt3032476&q=1080p+NTb

However, currently we don't support imdbid + keyword searches - https://github.com/Jackett/Jackett/issues/8107
