### ISSUE TITLE
Introduce ordering in the aggregated feed

### ISSUE THREAD

**Issue by ghost** [Jackett/Jackett#1346]
Hi,

Currently I have 5 separated Jackett source in my Sonarr application.
Sonarr don't want to introduce a priority order in term of source because for them, it's just about getting results.
But I really need to check some indexers before others.

It will be super great for the user to be able to order trackers on the homepage.
It can be done by numbers, with arrows or with a classic drag and drop feature (jQuery/Bootstrap - https://johnny.github.io/jquery-sortable#handle)

This will let user give priorities to the aggregated feed because it will retun results from 1# tracker then 2#, etc.

**Comment by garfield69** [comment]
Closing as stale.
