### ISSUE TITLE
[New Tracker REQ]  Blutopia

### ISSUE THREAD

**Issue by ceejayz711** [Jackett/Jackett#1348]
Tracker Name : Blutopia
Type : Movie and TV. 
Private tracker. Registration currently open.
Indexer URL : https://blutopia.xyz/
Indexer language : English

**Comment by adamwinn** [comment]
This might not be done for a while, or at least until they fix their website bugs.  Trying to implement this, I came across 3 different website bugs.

**Comment by HDVinnie** [comment]
Im the developer of the codebase Blutopia is running. Its a WIP built from scratch behind larval framework. Let me know what needs to be done. I know for one RSS needs work.

**Comment by raspdealer** [comment]
Open Registration Is Disabled and You Will Need A Invite To Gain Access!

**Comment by daddydeadpool** [comment]
@adamwinn hope we can get some info to @HDVinnie so we can get added to jackett.

**Comment by HDVinnie** [comment]
@adamwinn any update on what I need todo to add this to codebase?

**Comment by hitboxr** [comment]
@adamwinn Was looking for Blutopia in Jackett and didn't see it, searched and found this.  Any update on what @HDVinnie needs to do in order to get Blutopia added?

**Comment by adamwinn** [comment]
A beta version is ready by #1489

**Comment by kaso17** [comment]
can someone confirm that it's working?
Looking at the definition it looks like downloading torrents might not work.
