### ISSUE TITLE
[req]: torrent.by results

### ISSUE THREAD

**Issue by dshkoda32** [Jackett/Jackett#13484]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: torrent.by
- URL: http://torrent.by
- Description: 
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: 

Please help me what needs to be corrected in torrent.by.yml so that the tracker gives results in the program
```

**Comment by garfield69** [comment]
are you reporting a problem with the torrentby indexer?
the indexer is working for me.
if you have a problem, then open a new ticket using the correct form and provide the required information requested by [issue: Bug Report](https://github.com/Jackett/Jackett/issues/new?assignees=&labels=&template=bug_report.yml)
