### ISSUE TITLE
[req]: NewPCT.me no tv/shows category

### ISSUE THREAD

**Issue by Pegoku** [Jackett/Jackett#13485]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

NewPCT.me has in their's website the tv category but in the jackett indexers isn't this category.

### Describe the solution you'd like

Could you add it.
Thanks A LOT

### Describe alternatives you've considered

Adding the tv/shows category in the jackett indexer

Sorry for poor English.

**Comment by garfield69** [comment]
when the indexer was first added to Jackett #12284 the tv pages we not working properly so we left them out of the indexer.
I will investigate if we can now add tv to the indexer.

**Comment by garfield69** [comment]
v0.20.1740
