### ISSUE TITLE
Turkish words

### ISSUE THREAD

**Issue by Nuke142** [Jackett/Jackett#13496]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
v0.20.1778
```

### Description

There is no results if i search cinema in turkish words. Trackers itself have it, but no results in jackett.
I copy "Kiralık Aşk" from tracker's topic and paste to manual search in dashboard.
https://www.themoviedb.org/tv/63549-kiralik-ask?language=en-US

### Screenshots

![image](https://user-images.githubusercontent.com/19406558/185911234-e8237e30-053c-42f6-9cdf-8beeb6faa672.png)
![image](https://user-images.githubusercontent.com/19406558/185911483-7649e650-b7c1-4026-a616-cb6ca188c395.png)

![image](https://user-images.githubusercontent.com/19406558/185911003-0d55844c-b4ae-4970-bb17-a2a00210e96e.png)

**Comment by ilike2burnthing** [comment]
The affected indexers here are kinozal and rutracker.

Performing a search for `Kiralık Aşk` with rutracker in Jackett uses the URL:
https://rutracker.org/forum/tracker.php?nm=Kiral%C4%B1k+A%C5%9Fk
Performing the same search on rutracker.org supposedly uses the URL:
https://rutracker.org/forum/tracker.php?nm=Kiral%C4%B1k%20A%C5%9Fk
That's essentially the same thing, but if you paste it into a browser you get zero results. The URL actually being used is:
https://rutracker.org/forum/tracker.php?nm=Kiral%26%23305%3Bk%20A%26%23351%3Bk
So it is actually searching `Kiral&#305;k A&#351;k`.

Similarly, searching on kinozal.tv uses the URL:
http://kinozal.tv/browse.php?s=Kiral%26%23305%3Bk+A%26%23351%3Bk
Though oddly in this case Jackett uses (with redundant information removed):
http://kinozal.tv/browse.php?s=Kiral%3Fk+Ask
Which is searching for `Kiral?k Ask` and I have no idea why.

Both sites are converting the characters to unicode decimal codes (ı - 305, ş - 351), and I doubt we can do that. @garfield69 is there an easy solution here?

**Comment by garfield69** [comment]
>is there an easy solution here?

Both those indexers use the windows-1251 encoding. We could try switching to utf-8 ?
Other than that I have no idea, its a c# dev level question.

**Comment by ilike2burnthing** [comment]
Tested with kinozal using utf-8, it's definitely not a fix as it messes with titles and file sizes, but it has pointed me towards a potential solution.

So it now uses: http://kinozal.tv/browse.php?s=Kiral%C4%B1k+A%C5%9Fk
It finds the results, but testing in browser it shows that it's doing so because it has only searched for `Kiral`.

If we replace the characters causing issues with spaces, and search for `Kiral k A k` it now works in browser and Jackett. The same is true for rutracker.

`["[^a-zA-Zа-яА-Я0-9]+", " "]` works for this (considering they're Russian trackers). I'll throw up a PR for this shortly.

**Comment by garfield69** [comment]
v0.20.1790
