### ISSUE TITLE
[1337x] (testing) Exception (1337x): certificate validation failed:

### ISSUE THREAD

**Issue by xplorer990** [Jackett/Jackett#13493]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Ubuntu 22
Docker
```

### Description

I was able to add 1337x tracker but after a week I get this error message.

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (1337x): certificate validation failed: [Subject] E=root@localhost.localdomain, CN=localhost.localdomain, OU=IT, O=MyCompany, L=Seattle, S=WA, C=US [Issuer] E=root@localhost.localdomain, CN=localhost.localdomain, OU=IT, O=MyCompany, L=Seattle, S=WA, C=US [Serial Number] 1***SomeNumber [Not Before] 8/14/2018 1:33:36 PM [Not After] 8/11/2028 1:33:36 PM [Thumbprint] ****SomeCharacters**** : The SSL connection could not be established, see inner exception.
```

**Comment by ilike2burnthing** [comment]
Please see the steps in this older issue to see if they resolve your issue - https://github.com/Jackett/Jackett/issues/13216

If not, please answer here any questions which were asked there.
