### ISSUE TITLE
[hdcenter] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13501]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

hdcenter appears to be offline

### Logged Error Messages

```text
https://hdcenter.cc/ returns ERR_CONNECTION_TIMED_OUT
```

**Comment by dennisrpnw** [comment]
the tracker is dead

**Comment by ilike2burnthing** [comment]
Closure was announced back in May - https://torrentinvites.org/f31/hdcenter-news-603972/

**Comment by garfield69** [comment]
v0.20.1825
