### ISSUE TITLE
Endless login loop

### ISSUE THREAD

**Issue by ibigbug** [Jackett/Jackett#13505]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Running inside docker with latest image
```

### Description

I setup a fresh install inside Docker but the setup seems not working

### Logged Error Messages

```text
I did `curl -svL localhost:9117` and get endless redirections


< 
* Ignoring the response-body
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9117/UI/Dashboard'
* Found bundle for host localhost: 0x56495a419ac0 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 9117 (#0)
> GET /UI/Dashboard HTTP/1.1
> Host: localhost:9117
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Content-Length: 0
< Date: Fri, 26 Aug 2022 14:32:25 GMT
< Server: Kestrel
< Location: http://localhost:9117/UI/Login?ReturnUrl=%2FUI%2FDashboard
< 
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9117/UI/Login?ReturnUrl=%2FUI%2FDashboard'
* Found bundle for host localhost: 0x56495a419ac0 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 9117 (#0)
> GET /UI/Login?ReturnUrl=%2FUI%2FDashboard HTTP/1.1
> Host: localhost:9117
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Content-Length: 1373
< Content-Type: text/html
< Date: Fri, 26 Aug 2022 14:32:25 GMT
< Server: Kestrel
< Cache-Control: no-cache,no-store
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Last-Modified: Fri, 26 Aug 2022 03:31:59 GMT
< Location: /UI/Dashboard
< Pragma: no-cache
< Set-Cookie: Jackett=CfDJ8HahnAh931pLq3HYqeb7Thn1TnZz9AqG6kAKL19ngdIzlt1HOJLljfNW4B1LBmVNLcT9Ppbuf_0ZM-prRKmlKmNXAI5CVVOMGxJqeMCUjDJkXNNWqSG_cHZQFCRetXHqenGNRKIy3rbvSQVTT-0YnwFr-ItYXuxdj0uIlGaKN7WUob_UKVi5cfmYTdmBMiSw7Z2V4kPhFtN5_XRxSTpGFSh-0qX8mb-EBb1R1tng5v8_Z3CplkX59I4oo0Tty7lxWGuu9bjZL_WlgJzx9InPgvM4KlNbA-lr8LWWDI_QpT_GzaZu2CoQDJ2o1JI7qG7TdtRzlhasJikQuSuxxA93dGQ; expires=Fri, 09 Sep 2022 14:32:25 GMT; path=/; samesite=lax; httponly
< 
* Ignoring the response-body
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9117/UI/Dashboard'
* Found bundle for host localhost: 0x56495a419ac0 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 9117 (#0)
> GET /UI/Dashboard HTTP/1.1
> Host: localhost:9117
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Content-Length: 0
< Date: Fri, 26 Aug 2022 14:32:25 GMT
< Server: Kestrel
< Location: http://localhost:9117/UI/Login?ReturnUrl=%2FUI%2FDashboard
< 
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9117/UI/Login?ReturnUrl=%2FUI%2FDashboard'
* Found bundle for host localhost: 0x56495a419ac0 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 9117 (#0)
> GET /UI/Login?ReturnUrl=%2FUI%2FDashboard HTTP/1.1
> Host: localhost:9117
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Content-Length: 1373
< Content-Type: text/html
< Date: Fri, 26 Aug 2022 14:32:25 GMT
< Server: Kestrel
< Cache-Control: no-cache,no-store
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Last-Modified: Fri, 26 Aug 2022 03:31:59 GMT
< Location: /UI/Dashboard
< Pragma: no-cache
< Set-Cookie: Jackett=CfDJ8HahnAh931pLq3HYqeb7ThlzITbSoNSojGudjgqkome_YKdgxBeU-a6GjfOre8EJ958RXOYOWzuYcvaae-Bh8GR1x2tbXoZya2Dj5mTqd9vsnsFVQ_eCAO2cyFVIGQXK_IKo3gGK8yGCoxmhh2mM4EYJessZvzvXvMxIDElY8MJcRKqAjqDMibuEO0nNS7kjWGdH-Ba3gyawkl6X0D7q8wn8E4Wa-OTTW-mHuRmWmT37BVf6_aPV9v1w_bJQ81HpdtOJIWzxEnwSayVr7-1vmaMSA_2p0HjCE9A2vrY7TT6oVzSQ-AZNQ9jtyx6wYR8Vn968cLgDXLLwzNZc4XGaluY; expires=Fri, 09 Sep 2022 14:32:25 GMT; path=/; samesite=lax; httponly
< 
* Ignoring the response-body
* Connection #0 to host localhost left intact
* Maximum (50) redirects followed
```
```


### Screenshots

_No response_

**Comment by ilike2burnthing** [comment]
Can you access Jackett in browser?

What are you trying to achieve by curling Jackett from within its own container?

**Comment by ibigbug** [comment]
accessing in browser also gives redirect loop.

And I was trying to understand why it's like that - does it require something to be set explicitly ?

btw I'm running it behind Traefik.

**Comment by ilike2burnthing** [comment]
Can you access it when not behind the reverse proxy, i.e. just by IP and port?

https://github.com/Jackett/Jackett/wiki/Reverse-Proxy

**Comment by ibigbug** [comment]
> Can you access it when not behind the reverse proxy, i.e. just by IP and port?

Not really - traefik doesn't expose IP and port directly, and it has to access via a hostname.

tbh I think traefik doesn't pass XFF headers by default and there has been complaint about it.

nontheless - can I make Jackett to work without passing those XFF headers?

**Comment by ilike2burnthing** [comment]
So you can't access it by just using your local device IP and port? e.g. http://192.168.0.123:9117

Again - https://github.com/Jackett/Jackett/wiki/Reverse-Proxy

**Comment by ibigbug** [comment]
no I can't it's within a private subnet and it doesn't expose port to the host network.

I guess it's something to do with net core auth middleware.

do you think it makes sense to disable auth at all if `serverConfig.AdminPassword` is empty?

**Comment by ibigbug** [comment]
Actually I figured out a way to access via the IP:port `curl -sLv 172.18.0.3:9117`

and also gives redirect loop. not sure if it's really related to the reverse proxy now

**Comment by ibigbug** [comment]
if i save cookie with curl it works fine `curl -Lv -c cookie.txt localhost:9117`

**Comment by ilike2burnthing** [comment]
That's the Docker internal IP for communication between containers.

Have you not published the port?

Please provide your Docker compose file or Docker run command used for your Jackett container.

Please also provide the local IP of the host device running Docker.

**Comment by ibigbug** [comment]
no i didn't publish, all traffic is going through traefik into the private subnet so i don't have to. 

but anyways actually i think i might have found it - looks like an issue with traefik handling redirects and i've raised a ticket there: https://github.com/traefik/traefik/issues/9282

but in general i think this is not a best way of implementing login logic when user is made login and still get's redirect to the login page but tbh i never understood how asp auth works and what happens behind the sence when app.UserAuthentication is called etc.

but i guess there might be other ways doing this so that the login process won't confuse curl

https://github.com/Jackett/Jackett/blob/6eb61697cdfe840a3db7d7ce6fe03450cc47d0be/src/Jackett.Server/Controllers/UIController.cs#L47

but anyways let's see.

**Comment by ibigbug** [comment]
sorry for the confusion but i end up figuring out my firewall blocked the requests.
