### ISSUE TITLE
[TEKNO3D] missing categories in rss pull

### ISSUE THREAD

**Issue by chcme** [Jackett/Jackett#13509]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/name/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Debian GNU/Linux 10 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.19.0.17 (64bit OS) (64bit process)
Environment version: 6.0.8 (/home/name/Jackett/)	
Starting Jackett v0.20.1802
```

### Description

I'm not sure if this is a jackett bug or tracker issue.  There are movies that do not show up in the default rss feed, which are classified as category 37 on the tracker.  Unable to find a way to edit the feed to effectively pull those into the feed.

### Logged Error Messages

```text
No error log
```

**Comment by chcme** [comment]
Category 37 also referred to as  Category: Member Grades

**Comment by garfield69** [comment]
None of the team members have an account so we cannot proceed without your help.
If you provide a text file containing the HTML dump of the torrent search page on the site I should be able to update the indexer categories.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source
thanks.

**Comment by chcme** [comment]
[TEKNO3D HDR-X COMMUNITY.txt](https://github.com/Jackett/Jackett/files/9438661/TEKNO3D.HDR-X.COMMUNITY.txt)

**Comment by garfield69** [comment]
Urg. so it appears the site has had a radical category shake up.
And nearly everything is dumped into a cat 37 category, whether its a movie or a music video.
And presumably, tv too, although I cannot see an example of that in the sample you provided, but it likely the case.
All the individual categories for movie, tv and some others are gone.
I'll rework the indexer.

**Comment by garfield69** [comment]
@chcme what is SILVER ? 50% freeleech or a full freelech that expires after the set date/time?
are there any other of these types, such as 2x upload or similar?

**Comment by chcme** [comment]
I don't believe SILVER or any other items are really used properly.  It's subscription-based for a period of time but no benefits such as 50% or 2x, etc.  I would suggest ignoring any of that.

**Comment by garfield69** [comment]
OK.

**Comment by chcme** [comment]
Thank you

**Comment by garfield69** [comment]
v0.20.1810
