### ISSUE TITLE
[REQ] RacingForMe

### ISSUE THREAD

**Issue by mikesafari** [Jackett/Jackett#1351]
I have an invite available and will send it to staff.

This is a tracker exclusively for motorsport, so I believe this is the only category mapping that's required.

AddCategoryMapping("cat_id", TorznabCatType.TVSport);

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by garfield69** [comment]
Registration is currently closed. Invite needed.
If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by chielmi** [comment]
> Registration is currently closed. Invite needed.
> If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
> But if the site turns out to require a native c# indexer then I will not be able to complete the task.

I have sent you an invite. I hope you succeed in adding this site. Thanks in advance :)

**Comment by garfield69** [comment]
Registration and login successful. Thank you.

**Comment by garfield69** [comment]
Try Jackett v0.10.835

**Comment by garfield69** [comment]
https://www.racingfor.me/ ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
Heads up: site is due for an upgrade, which will require a password reset once implemented. Likely also involve significant indexer updates based on what is in the news article. Expect an outage as a prelude. No ETA as yet.
