### ISSUE TITLE
[req]: Add button for opening all indexers

### ISSUE THREAD

**Issue by milkdawg** [Jackett/Jackett#13513]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Lots of indexers require users login to site manually on a regular basis to not get disabled.

### Describe the solution you'd like

I would like a button in jackett to open all indexers like you just clicked on their name in the indexer list.

### Describe alternatives you've considered

An alternative is adding them all to a bookmarks folder and then using "open all bookmarks" option, but would prefer option in jackett as I/users already have them organized in one place.

**Comment by ilike2burnthing** [comment]
Click the `Test All` button to achieve the same thing.
