### ISSUE TITLE
[TJUPT] Filter brackets in titles for Sonarr/Radarr

### ISSUE THREAD

**Issue by jv43** [Jackett/Jackett#13519]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://flaresolverr:8191
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.1825-ls74)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.4.0.124 (64bit OS) (64bit process)
Environment version: 6.0.8 (/app/Jackett/)
```

### Description

In order for Sonarr/Radarr to properly parse TJUPT titles, Jackett will need to clean the title up.

For example, when Sonarr searches for "House of the Dragon S01E02" through Jackett indexer TJUPT:

The title for the first result:
`[美剧][龙之家族 第一季][House.of.the.Dragon.S01E02.The.Rogue.Prince.720p.HMAX.WEB-DL.DDP5.1.H.264-NTb]
`

Sonarr returned `Unable to parse release` error, because of all the brackets.

For radarr, errors are the same, e.g.
`Failed to find movie title in release name [美国/大陆][壮志凌云2：独行侠][Top Gun Maverick 2022 IMAX 1080p AMZN WEB-DL DDP5.1 Atmos H.264-FLUX]`

Titles on TJUPT is auto-generated. Its format:
For TV series and movies, [country or region][series/movie title translated to Chinese][**actual release title**]
For documentaries, [country or region][title translated to Chinese][**actual release title**][subtitle availability]

Now, my suggestion:

Make a regex subsitution to the search title, in order to put release title to the front, all other info to the back. 
`^\[([^\]]+)\]\[([^\]]+)\]\[([^\]]+)\](.*)$`
to
`$3 [$1][$2]$4`

This way all details are preserved, and Sonarr/Radarr can also parse correctly.

### Logged Error Messages

```text
There are no error logs from Jackett.
```

**Comment by garfield69** [comment]
v0.20.1830

**Comment by jv43** [comment]
> 

Wow, thanks @garfield69 ! You are the best!
