### ISSUE TITLE
Indexer BT4G no work RSS no search

### ISSUE THREAD

**Issue by octaviz** [Jackett/Jackett#13516]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Running Jackett last versión 1/9/22 in Docker Synology NAS
```

### Description

The BT4G Indexer doesn't work, I really don't know what it's for, you can't use RSS, you can't search for anything, neither with a category filter nor without, the web, on the other hand, works fine.

### Logged Error Messages

```text
When you do a search with Jackett it gives you this message: "Your search was done using: BT4G (Error) , "
```

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/856579/187870112-2b6dd92a-691e-472c-ad84-34e35ab25b37.png)

**Comment by garfield69** [comment]
this indexer is impacted by https://github.com/FlareSolverr/FlareSolverr/issues/481 and until the Flaresolverr team resolve that issue you cannot use the BT4G indexer ATM.

**Comment by octaviz** [comment]
Ok, we will wait! Thanks!

**Comment by ilike2burnthing** [comment]
[v2.2.7](https://github.com/FlareSolverr/FlareSolverr/releases/v2.2.7) now out. Update FlareSolverr and test again.
