### ISSUE TITLE
Need Support - Jackett does not start on my synology NAS

### ISSUE THREAD

**Issue by darkparanor** [Jackett/Jackett#13525]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Synology NAs: DS214se
DSM: 6.2
Jackett: v0.20.1171-15 (tested also 0.17.668-14)
```

### Description

Hello,
hope to be in the right place.
I am trying to use jackett on my synology NAS 6.2. 
The installation seems to be ok but the application does not start.
In the /var/log/messages I can read the following message:
2022-09-05T07:34:46+02:00 XXXXXX synoscgi_SYNO.Core.Package.Control_1_start[25312]: pkgstartstop.cpp:376 Failed to start pkgctl-jackett (err=-1) [0xD900 manager.cpp:204]

May you help me in troubleshooting the issue? Can you indicate me where are the logs or what to check? I am rpetty sure that it is more an issue on my NAS rather than jackett but cannot understand where to look or what to setup.
in 
/volume1/@appstore/jackett/var# cat jackett.log
only message:

Mon Sep  5 08:18:55 CEST 2022
Starting jackett command env HOME=/volume1/@appstore/jackett/var PATH=/volume1/@appstore/jackett/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin LD_LIBRARY_PATH=/volume1/@appstore/jackett/lib /volume1/@appstore/jackett/share/jackett --PIDFile /volume1/@appstore/jackett/var/jackett.pid
jackett is not running

Any advice or where to look is highly appreciated

Thank you

### Logged Error Messages

```text
/volume1/@appstore/jackett/var# cat jackett.log
only message:

Mon Sep  5 08:18:55 CEST 2022
Starting jackett command env HOME=/volume1/@appstore/jackett/var PATH=/volume1/@appstore/jackett/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin LD_LIBRARY_PATH=/volume1/@appstore/jackett/lib /volume1/@appstore/jackett/share/jackett --PIDFile /volume1/@appstore/jackett/var/jackett.pid
jackett is not running
```

**Comment by ilike2burnthing** [comment]
By the looks of it, Jackett never runs, so there will be no Jackett logs to look at.

Like you said, this appears to be a Synology issue, rather than a Jackett one, so I'd suggest looking for similar issues over at SynoCommunity, and in the various Synology community forums:
https://github.com/SynoCommunity/spksrc
https://www.synoforum.com
https://community.synology.com
https://www.reddit.com/r/synology
(try searching - `pkgstartstop.cpp Failed to start pkgctl err=-1`)
