### ISSUE TITLE
[req]: 3Evils.net

### ISSUE THREAD

**Issue by SassyJ1** [Jackett/Jackett#13534]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: 3evils
- URL: https://3evils.net/
- Description: 
- Minimum Seeding Time and Minimum Ratio (if Private): tbd
- Additional Comments: 
engine: U-232 V5

**Comment by garfield69** [comment]
Done. The next release of Jackett due out in about 10 hours from now will include this indexer.

**Comment by garfield69** [comment]
v0.20.1861

**Comment by garfield69** [comment]
https://3evils.net/ returns ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://3evils.net/ returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
Sign ups are open. Mine initially said it failed with some generic MySQL error, but it had actually gone through, and I was able to sign in.

Site appears to still be under construction, so may be a waste to try updating the indexer.

**Comment by garfield69** [comment]
v0.20.2273

**Comment by garfield69** [comment]
v0.20.2280

**Comment by ilike2burnthing** [comment]
https://3evils.net/ - ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
3Evils Will be removed when TheDarkCommunity indexer goes online #13923

**Comment by garfield69** [comment]
v0.20.2707
