### ISSUE TITLE
[req]: add Portuguese Language to the release name based on attribute audio_pt

### ISSUE THREAD

**Issue by Norin-Radd** [Jackett/Jackett#13542]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I would like to grab animation movies with portuguese audio (Portugal/PT-PT) so that radarr recognizes releases as Portuguese from Portugal based on tracker attribute.

### Describe the solution you'd like

Tag has Portuguese Language when in tracker api attribute is audio_pt

The trackers are Portugas and SceneRush, both Portuguese trackers.

**Comment by garfield69** [comment]
I can add the tag `Portugal/PT-PT` to the end of the title for the SceneRush indexer, but I am going to hold off updating the Prortugas indexer  because the site admins have announced an upgrade sometime today or tomorrow, so I will wait until that is complete because I expect to have to make significant changes to the indexer once they have upgraded.

**Comment by Norin-Radd** [comment]
Super!

Thank you for the consideration and fast Reply.

**Comment by Norin-Radd** [comment]
Erm... Isnt better the tag Portuguese PT-PT?

Think its better than Portugal, which refers to country instead of Portuguese language. 

because there is Portuguese PT-BR (Brasilian).

Its easier to adopt on naming scheme PT-PT and PT-BR to diferentiate i suppose.

**Comment by garfield69** [comment]
I just used what you specified in the brackets of your original post without thinking about it.
I can use `Portuguese PT-PT` if that is preferred.
And I currently look for the presence of the  i.fg-audiopt HTMP tag in the results row, which is to say, if the tag is present I add the text `Portuguese PT-PT` to the end of the title.
are you saying that the HTML tag  i.fg-audiopt can represent other languages?

**Comment by garfield69** [comment]
scenerush v0.20.1892

**Comment by Norin-Radd** [comment]
> I just used what you specified in the brackets of your original post without thinking about it. I can use `Portuguese PT-PT` if that is preferred. And I currently look for the presence of the i.fg-audiopt HTML tag in the results row, which is to say, if the tag is present I add the text `Portuguese PT-PT` to the end of the title. are you saying that the HTML tag i.fg-audiopt can represent other languages?

That just means there is an audio track on Portuguese PT-PT in the release, it also can be a dual release or single audio track in Portuguese.

**Comment by Norin-Radd** [comment]
Portugas is up

**Comment by garfield69** [comment]
Cool. They have upgraded from unit3d 4.0.0 to 6.3.0,  so we will be switching to an indexer that uses the sites API and deleting the old HTML scraping indexer.
I will add the language flag to the new indexer which will be called Portugas (API).

**Comment by Norin-Radd** [comment]
Thank you

**Comment by garfield69** [comment]
Portugas (API) v0.20.1901
