### ISSUE TITLE
Try different URL when current URL fails

### ISSUE THREAD

**Issue by t-zone** [Jackett/Jackett#13545]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Indexer fails to work when linked site goes down (obviously).

### Describe the solution you'd like

Some indexers in jacket currently have a list of URLs to try, usually at least one works. Jacket would ideally periodically test the indexers, if it fails then it cycles through recommended URLs for that indexer until one works. For example, available URLs for an indexer are abc.com and abc.net. abc.com is selected and works initially. It fails 2 days later and when this is detected Jackett selects abc.net, which is working.

### Describe alternatives you've considered

Currently manually check failed indexers and find a working URL.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/9618
