### ISSUE TITLE
Spidertk need enter Captcha Image almost every day

### ISSUE THREAD

**Issue by RedBull01** [Jackett/Jackett#13549]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://*************
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.1903)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.4.0.121 (64bit OS) (64bit process)
Environment version: 6.0.9 (/app/Jackett/)
Starting Jackett v0.20.1903
```

### Description

Hi.

Almost exery day Spidertk is on Error. Need enter Captcha Image.

Thx

### Logged Error Messages

```text
No log error.
```

**Comment by garfield69** [comment]
That does not happen to me, which suggests this has something to do with your setup.
For instance, are you using anything that might change your IP address daily?

**Comment by RedBull01** [comment]
> That does not happen to me, which suggests this has something to do with your setup. For instance, are you using anything that might change your IP address daily?

Thx for reply. 

No VPN. Always same ip. Jackett is on OVH Server.

**Comment by garfield69** [comment]
@ilike2burnthing  Any thoughts on this one, its out of my area?

**Comment by ilike2burnthing** [comment]
At a guess, the VPS/seedbox IP is being flagged for extra scrutiny, or is shared by other users which is causing login persistence issues.

I would suggest contacting SpiderTK staff to see if they can shed any light on the likely cause.
