### ISSUE TITLE
[yggcookie] (testing) Exception (yggcookie): Cannot assign requested address: Cannot assign requested address (www5.yggtorrent.fi:443)

### ISSUE THREAD

**Issue by sam37git** [Jackett/Jackett#13559]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: 192.168.1.72:9117
Using FlareSolverr: 192.168.1.72:8191
Using Proxy: Disabled
App config/log directory: /config/mnt/user/appdata/jackett
Running un Docker: Yes
OS version: Unraid 6.9.2
Jackett version: v0.20.1915
```

### Description

I can't test my indexer, no problem with other public indexer, before no problem. i have already see the topic #13552, i have changed my dns to 1.1.1.1 and 1.0.0.1 on my router and no change.

### Logged Error Messages

```text
An error occurred while updating this indexer
Cannot assign requested address (www5.yggtorrent.fi:443): Cannot assign requested address
```

### Screenshots

![image](https://user-images.githubusercontent.com/21193811/191316816-0d7d9ee1-e353-4138-b1df-d5f478199463.png)

**Comment by garfield69** [comment]
If you are using docker then I think that you may need to specify the DNS to the docker Jackett container 
examples:
for the docker run add the flags `--dns 1.1.1.1 --dns 1.0.0.1`
for the docker-compose.yml add 
```
    dns:
      - 1.1.1.1
      - 1.0.0.1
```

**Comment by sam37git** [comment]
Thanks it work ! So I don't need to change the DNS of my router ?
