### ISSUE TITLE
[yggcookie] (testing) Exception (yggcookie): certificate validation failed: [Subject]  CN=mikasway.fr[Issuer]  CN=R3, O=Let's Encrypt, C=US[Serial Number]  03C95D8D875452C0B740A3BD2A0942110718[Not Before]  9/16/2022 7:17:15 PM[Not After]  12/15/2022 7:17:14 PM[Thumbprint]  28826A3924CD85E795F828AC733160587EDF55E9: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by Mikasway** [Jackett/Jackett#13552]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
An error occurred while testing this indexer
Exception (yggcookie): certificate validation failed: [Subject] CN=mikasway.fr [Issuer] CN=R3, O=Let's Encrypt, C=US [Serial Number] 03C95D8D875452C0B740A3BD2A0942110718 [Not Before] 9/16/2022 7:17:15 PM [Not After] 12/15/2022 7:17:14 PM [Thumbprint] 28826A3924CD85E795F828AC733160587EDF55E9 : The SSL connection could not be established, see inner exception.
```

### Description

My cerificate is valide and there is a problème 

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (yggcookie): certificate validation failed: [Subject] CN=mikasway.fr [Issuer] CN=R3, O=Let's Encrypt, C=US [Serial Number] 03C95D8D875452C0B740A3BD2A0942110718 [Not Before] 9/16/2022 7:17:15 PM [Not After] 12/15/2022 7:17:14 PM [Thumbprint] 28826A3924CD85E795F828AC733160587EDF55E9 : The SSL connection could not be established, see inner exception.
```

### Screenshots

Thanks

**Comment by garfield69** [comment]
The yggtorrent web site uses cloudflare services, so the CA you should be seeing should have a CN=sni.cloudflaressl.com
You are seeing CN=mikasway.fr which most likely means that your ISP is blocking your access to the site by redirecting you to a black hole.
Either change the DNS that your ISP to one of the public ones such as cloudflare or google, or use a VPN.

**Comment by garfield69** [comment]
Hang on, your user name is the similar to the CN, are you using some sort of proxy?
@ilike2burnthing  This stuff is out of my ken, help?

**Comment by garfield69** [comment]
@Mikasway  please provide the environment data that was requested when you opened the ticket. Restart Jackett, access the log and post the first 10 lines of the log that has the jackett version and so forth.

**Comment by Mikasway** [comment]
Jackett.Common.IndexerException: Exception (yggtorrent): certificate validation failed: [Subject]
  CN=mikasway.fr

[Issuer]
  CN=R3, O=Let's Encrypt, C=US

[Serial Number]
  03D9BC91C33FDC090B818E0695D58E5DBDE3

[Not Before]
  9/16/2022 7:22:29 PM

[Not After]
  12/15/2022 7:22:28 PM

[Thumbprint]
  786A0D99B9813D1C039325D83AB952090D564F5B

 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Exception: certificate validation failed: [Subject]
  CN=mikasway.fr

**Comment by ilike2burnthing** [comment]
@Mikasway please provide the information requested in https://github.com/Jackett/Jackett/issues/13552#issuecomment-1249788167 and https://github.com/Jackett/Jackett/issues/13552#issuecomment-1249786576.
