### ISSUE TITLE
batch search requests aborts search

### ISSUE THREAD

**Issue by thaynos** [Jackett/Jackett#13551]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.22000.0 (64bit OS)
	
Environment version: 6.0.9 (C:\ProgramData\Jackett\)
```

### Description

this has happened a lot of times in which if i batch search only one of them completes, the rest get search aborted error. i am using the latest version of qbittorrent. im only able to search one at a time which is rather time-consuming. i dont know if this feature doesnt exist in the first place or theres something wrong.

### Logged Error Messages

```text
in screenshots
```

### Screenshots

![image](https://user-images.githubusercontent.com/83282129/190688075-fad04e30-e877-456f-8274-6a1b1b72d2fd.png)
![image](https://user-images.githubusercontent.com/83282129/190688092-2a1e95a6-44cf-4800-b5d4-5b9e9a7dab79.png)

**Comment by garfield69** [comment]
By batch search, I presume you mean that are using the Jackett aggregate ALL search query?
Are you using flarfesolverr 2.27 by any chance? 
Do some of the indexers that are included in your batch search require a cloudflare check?

**Comment by thaynos** [comment]
Im really sorry, i dint understand or know how to answer your questions.By batch search i mean in qbit u can search for something and it will show up as a tab, when im simu taneously searching in multiple tabs, it shows search abort.

**Comment by garfield69** [comment]
@ilike2burnthing  have you used the qBt search feature and know anything about it, or is this a question for @ngosang ?
@thaynos  I dont know anything about the qBt search feature and how it uses jackett.
was it working previously and recently started this behaviour, or is this the first time you set this up?

**Comment by garfield69** [comment]
Also what version of qBt are you using?
I'll try and set up a qBt search tab and do some research to better understand what we are talking about.

**Comment by ilike2burnthing** [comment]
I can cause something similar in 2 ways:

1. in Jackett's dashboard - have two tabs open, perform 2 different simultaneous searches with RARBG in both, e.g. `2022` in one, and `2021` in the other. So long as you don't get 'lucky' and have 1 search complete automatically (rather than on the 5th attempt), 1 will complete and the other will error out.

2. in qbittorrent - perform several successive searches with the Jackett search plugin, and a few indexers configured in Jackett. At least 1 will error out, but Jackett's log will show all as having been successful.

@thaynos please provide a normal log of the issue to see if it's just a normal error causing the problem, or if the issue lies with qbittorrent/the Jackett plugin.

**Comment by thaynos** [comment]
> @ilike2burnthing have you used the qBt search feature and know anything about it, or is this a question for @ngosang ? @thaynos I dont know anything about the qBt search feature and how it uses jackett. was it working previously and recently started this behaviour, or is this the first time you set this up?

this issue was always there for the past few months i think?

**Comment by thaynos** [comment]
> I can cause something similar in 2 ways:
> 
> 1. in Jackett's dashboard - have two tabs open, perform 2 different simultaneous searches with RARBG in both, e.g. `2022` in one, and `2021` in the other. So long as you don't get 'lucky' and have 1 search complete automatically (rather than on the 5th attempt), 1 will complete and the other will error out.

this did happen, the one i did first completed while the other errored out
![image](https://user-images.githubusercontent.com/83282129/190868975-d8e9077d-9d76-4a19-a091-4a0cdcfd8dd7.png)
this is the logs files
![image](https://user-images.githubusercontent.com/83282129/190869132-73036ef0-f8d4-4ded-8cc3-4d1f23588397.png)
![image](https://user-images.githubusercontent.com/83282129/190869140-f36be82f-2790-443b-b343-ecd7c6778423.png)



> 2. in qbittorrent - perform several searches in quick succession with the Jackett search plugin, and a few indexers configured in Jackett. At least 1 will error out, but Jackett's log will show all as having been successful.

i did 4 in quick succession and all 4 except the last one aborted whereas the last one completed. and yes indeed all of them were completed in the logs
![image](https://user-images.githubusercontent.com/83282129/190869088-c257079d-ba82-4f40-8c9b-a8bb2a5e518a.png)
![image](https://user-images.githubusercontent.com/83282129/190869093-2a76de7d-219c-407b-89ad-282fa46f16e3.png)


> 
> @thaynos please provide a normal log of the issue to see if it's just a normal error causing the problem, or if the issue lies with qbittorrent/the Jackett plugin.

im not sure what do you mean by normal log of issue.

**Comment by garfield69** [comment]
>im not sure what do you mean by normal log of issue.

we are taking about the Jackett log, in normal (default) mode, as opposed to enhanced mode (Jackett dashboard setting). 
Basically we are just checking that the reason for the cancel is not due to Jackett cancelling the response because of a problem with the indexer, and thus showing that the problem could possibly be with the qBt plugin in being unable to handle multiple tab searches to the same single Jackett interface.

**Comment by ilike2burnthing** [comment]
Going by those last screenshots, it seems to be a qbit or plugin problem, as Jackett completes the searches without issue. I suggest opening a new issue with them.
