### ISSUE TITLE
Demonoid - Download Selectors didn't match

### ISSUE THREAD

**Issue by billyjbryant** [Jackett/Jackett#13563]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.1916-ls77)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
Environment version: 6.0.9 (/app/Jackett/)
```

### Description

Unable to download using Demonoid as a tracker under a default configuration. I get the following error in Jackett's logs. 

I saw where this had been previously reported in #12122 and fixed via https://github.com/Jackett/Jackett/commit/9039d1d6e97165e0ba087680447961ffc0bd645a

Wasn't sure if the issue occurring was more of the same (change to Demonoid's html). I am on the v5 Web Theme in my settings. 

### Logged Error Messages

```text
Error downloading. indexer: demonoid path: https://www.demonoid.is/files/details/328169/054933443/?highlight=NCIS+Los+Angeles+S12E09
System.Exception: Download selectors didn't match
   at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1903
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97
```

### Screenshots

n/a

**Comment by garfield69** [comment]
I get this too.
It looks like demonoid have outsourced the .torrents storage to a 3rd party site, as the download link is now redirecting to hypercache.net instead of providing the .torrent directly.
I will try to amend the indexer to cope with the new front end.

**Comment by garfield69** [comment]
v0.20.1918
