### ISSUE TITLE
New private tracker torrent-town

### ISSUE THREAD

**Issue by lordduckstein** [Jackett/Jackett#13571]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: torrent-town
- URL: https://torrent-town.hopto.org
- Description: torrent-town is a private german Torrent Tracker for movies,tv an more
- Minimum Seeding Time and Minimum Ratio (if Private): min 48 hour seeding or 0.7 ratio
- Additional Comments: 
```
engine: ~~3xT~~ n/a

**Comment by garfield69** [comment]
v0.20.1951

**Comment by lordduckstein** [comment]
Sorry that I have to open again. Results from the tracker are found beautifully and put into my download program, but it doesn't download them. Information must be missing that allows the torrent to download. Direct torrents from the homepage working perfect.

**Comment by ilike2burnthing** [comment]
Downloads are working ok here. Please provide an enhanced log of your issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
site has reset and now using another engine (same as coastal-crew)

**Comment by garfield69** [comment]
v0.20.2080

**Comment by garfield69** [comment]
https://torrent-town.hopto.org/ returns DNS_PROBE_FINISHED_NXDOMAIN (DNS domain not found)

**Comment by garfield69** [comment]
@lordduckstein  do you have any news about torrent-town, is the site gone, moved to a new domain, or just broken?

**Comment by lordduckstein** [comment]
@garfield69 sorry I have not a Information what are happend. When I get something I let you know.

**Comment by garfield69** [comment]
v0.20.2267
