### ISSUE TITLE
[limetorrents] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13570]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

limetorrents passes keywordless search but fails when searching keywords

### Logged Error Messages

```text
keyword search returns error
https://www.limetorrents.lol/search/all/test/ returns `Can't connect to database, error: Too many connections`
```

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.limetorrents.lol/search/all/code-vba/ 
keyword search returns `Can't connect to database, error: No such file or directory`
TEST works

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.limetorrents.lol/ Can't connect to database, error: No such file or directory

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.limetorrents.lol/ - Error 1016 - Origin DNS error

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13570#issuecomment-1501247794

**Comment by garfield69** [comment]
online
