### ISSUE TITLE
movietorrent: download links are not working

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13588]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett: v0.20.1951
Arch Linux
Docker: Yes
```

### Description

Download links from "empty search" are not working
Text search "Boonie" is not working neither

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment]
we use the infohash to fetch the magnet so we can avoid using the site's handcoded trackers list which caused problems previously.
however the H2 html tag we used to fill in the title no longer exists so the infohash fails.
we will need to update the indexer with a new title selector.
