### ISSUE TITLE
Square brackets not showing in TorrentProject

### ISSUE THREAD

**Issue by zacnut** [Jackett/Jackett#1358]
I'm having problems with some shows because torrent project doesn't show square brackets in a query but will on the site. i'm thinking its because off the title it pulls.
This is a random example from some show.

Jackett Search:
![jackett search](https://cloud.githubusercontent.com/assets/7859329/25948929/13fb9732-3699-11e7-9466-978881bca7d7.png)

ProjectTorrrent: i'm assuming jackett pulls the top heading (no punctuation) 
Perhaps use the "torrent contents" title at the bottom of the screen shot?
![torrentproject search](https://cloud.githubusercontent.com/assets/7859329/25948950/25998300-3699-11e7-9118-d23a3c680cce.png)

**Comment by kaso17** [comment]
the title is taken from the search result pages which doesn't include the brakets.
As the original filename doesn't seem to be available from the search results page this can't be fixed.
