### ISSUE TITLE
ebooks-shares: size and other columns are wrong

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13585]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett: v0.20.1951
Arch Linux
Docker: Yes
```

### Description

![image](https://user-images.githubusercontent.com/10577978/192113307-c64f4cb1-97c8-43ed-94a1-8a8aea8cbfab.png)
![image](https://user-images.githubusercontent.com/10577978/192113331-be1cb63c-9d71-454d-a9bb-5f8931ee2442.png)

### Logged Error Messages

```text
.
```

**Comment by mikeoscar2006** [comment]
Don't have an account. Maybe an HTML would be helpful.
