### ISSUE TITLE
cpasbienclone: download links are not working

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13586]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett: v0.20.1951
Arch Linux
Docker: Yes
```

### Description

cpasbienclone: download links are not working

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment]
site has changed from a magnet href available in the details page, to one generated via JS.
will need to see if we can replicate the call to the script with the id, so that we can fetch the magnet, or perhaps find the hash someplace and use infohash to build instead.

**Comment by garfield69** [comment]
I cannot figure out how to fetch the magnet.
I can make a call to the JS with
```yaml
download:
  before:
    # request target
    path: "download_magnet?id={{ re_replace .DownloadUri.AbsoluteUri \"^.*-(\\d+)\\.html\" \"$1\" }}"
```
but I get back a pure text response containing the magnet string
```
magnet:?xt=urn:btih:HASHREDACTED&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://open.stealth.si:80/announce&tr=udp://explodie.org:6969/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://9.rarbg.to:2740/announce&tr=udp://9.rarbg.com:2770/announce&tr=http://1337.abcvg.info/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=http://tracker.bt4g.com:2095/announce&tr=udp://opentor.org:2710/announce&tr=udp://www.torrent.eu.org:451/announce&tr=udp://retracker.lanta-net.ru:2710/announce
```
but I cant find a way to process that response since everything expects a html document.
someone else want to try?

**Comment by mikeoscar2006** [comment]
Just throwing out two ideas:
1. Maybe we can use the Infohash block to extract the infohash and title from the magnet response.
2. Make one of the blocks capable of directly checking if response has a magnet link and return that instead.
