### ISSUE TITLE
newpct-me: download links are not working

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13589]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett: v0.20.1951
Arch Linux
Docker: Yes
```

### Description

newpct-me: download links are not working
I tested "empty search" and "text search"

### Logged Error Messages

```text
.
```

**Comment by mikeoscar2006** [comment]
The download and magnet links seem to be shortened using the ouo.io URL Shortener service.

**Comment by garfield69** [comment]
this 3rd party service requires a button click to prove you are human, followed by a wait countdown of 3 seconds before a new button is enabled, which once clicked  will finally yield the .torrent or magnet
the first 3 torrents I tried with the magnet all generated a 404 so only .torrents appear to be supported

newpct-me  is no longer suitable for indexing with Jackett. I will remove it.
