### ISSUE TITLE
torrent-pirat: returns 0 results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13592]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett: v0.20.1951
Arch Linux
Docker: Yes
```

### Description

The site looks good in my web browser but Jackett returns 0 results with "empty search" and with "text search".

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment]
cannot reproduce. keyword and keywordless searches produce results for me.

**Comment by ilike2burnthing** [comment]
It did this to me earlier, and then the next search worked fine. Presumably an intermittent issue with the site.
