### ISSUE TITLE
Not working with WebOS

### ISSUE THREAD

**Issue by DeadlySin2** [Jackett/Jackett#13604]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Running on Synology NAS in Docker container

Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.2004-ls77)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
Environment version: 6.0.9 (/app/Jackett/)
Starting Jackett v0.20.2013
```

### Description

On the PC everything is working fine, i can search for torrents and play them, but when i'm trying to set up the same parametrs of the jackett server on me WebOS TV it shows error - "Cannot connect to jacket server" all devices are in the same network. May be i have selected wrong option or something else?

In the log file i can see that TV has made a request and Jackett have found information, but it is not showing tham on the TV

### Logged Error Messages

```text
date	stream	content
2022-09-27T06:53:11.620219235Z	stdout	[39;49m[37m09-27 09:53:11 Info Manual search in LostFilm.tv, RuTracker, BitRu, Kinozal, NoNaMe Club, NoNaMe ClubL, PiratBit, RuTor, seleZen, torrent.by for Тор Любовь и гром => Found 162 releases 
2022-09-27T06:33:59.945930017Z	stdout	Application started. Press Ctrl+C to shut down.
2022-09-27T06:33:59.945891855Z	stdout	Now listening on: http://[::]:9117
```

**Comment by ilike2burnthing** [comment]
What are you accessing Jackett through on your WebOS TV, e.g. a browser, an app, some other interface?

**Comment by DeadlySin2** [comment]
lampa app

**Comment by garfield69** [comment]
`Allow CORS` is a _boolean_ so the correct setting is either **false** or **true**
in the ServerConfig.json file
```json
  "AllowCORS": false,
```
or
```json
  "AllowCORS": true,
```
