### ISSUE TITLE
Jackett loads a broken torrent from Torrent-Town

### ISSUE THREAD

**Issue by lordduckstein** [Jackett/Jackett#13601]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Running in Docker: yes
Jackett variant: DyonR/docker-Jackettvpn
OS version: OMV6 debian bullseye (64 bit)
Using Proxy: Disabled
```

### Description

Sorry that I have to reopen again. Results from the tracker are found beautifully and put into my download program, but torrent is broken. Information must be missing that allows the torrent start the download. Direct torrents from the homepage working perfect. See my pictures in the appendix they are different. Also the files are in the size different 13.62 KB (load from Torrent-Town direct) to 13.53 KB (load from Jackett direct) in my example.   

### Logged Error Messages

```text
no error in the log found
```

### Screenshots

**This is the beginning of the torrent directly downloaded in Torrent-Town:**

![IMG_20220926_142538](https://user-images.githubusercontent.com/30575840/192278276-5ab431da-5afe-42ae-89ad-e3952f3d63e0.jpg)

**This is the beginning of the torrent directly downloaded in Jackett:**
![IMG_20220926_142634](https://user-images.githubusercontent.com/30575840/192278305-0ff43b36-00ca-4335-8829-161633319e79.jpg)

**Comment by garfield69** [comment]
v0.20.2013

**Comment by lordduckstein** [comment]
It works perfectly.

Thank you
