### ISSUE TITLE
Ncore.cc Error: Failed download cookies

### ISSUE THREAD

**Issue by GMFalka** [Jackett/Jackett#1360]
Jackett version:  0.7.1389.0
Mono version (if not using Windows):  4.8.1 (Stable 4.8.1.0/22a39d7 Wed Apr 12 12:00:23 UTC 2017)

-------------------------------
After 1.5year of error free Jackett usage, randomly today this error popped up and sonarr cant download anything, but it sees the up-to-date entries in tracker.

Also the link below in the copied errorlog is 404 (when logged into the site) so thats probably the reason. Maybe ncore.cc changed something?

**Edit:**
This is the correct link for the download button on the actual site:
https://ncore.cc/torrents.php?action=download&id=2124626&key=7817b4randomletters&numbers
This is the link Jackett tries to reach:
https://ncore.cc/torrents.php?action=download&id=2124626

```
Error downloading ncore https://ncore.cc/torrents.php?action=download&id=2124626
Error	Failed download response:
Error	Failed download cookies: PHPSESSID=; nick=; pass=; nyelv=hu; stilus=dark
```

**Comment by kotysoft** [comment]
Yes, they're changed their download link. Now it's addig your custom passkey to link. 

So the plugin need only one additional entry:
>nick
>password
>PASSKEY

the format of correct download url is:
**https://ncore.cc/torrents.php?action=download&id=[TORRENTID]&key=[PASSKEY]**

**Comment by vampywiz17** [comment]
Yes please :) I affect same error .

**Comment by noorbertt** [comment]
Same here, need to fix please:)

**Comment by gurabli** [comment]
I see the fix is already done? I guess it will be included in the next pre-release or release?

**Comment by vampywiz17** [comment]
> I see the fix is already done? I guess it will be included in the next pre-release or release?

I hope yes

**Comment by gurabli** [comment]
I got the version from AppVeyor, just tested, and it works perfectly fine again. Thanks

**Comment by HermanCattaneo** [comment]
> I got the version from AppVeyor, just tested, and it works perfectly fine again.  Thanks

what version have you tested? with 0.7.1399.0 from AppVeyor it doesnt work for me. Thanks

**Comment by gurabli** [comment]
Version 0.7.1397.0, that version works fine. Not sure why 1399 doesn't work, if I'm correct, that should also have the fix included.

**Comment by HermanCattaneo** [comment]
> Version 0.7.1397.0, that version works fine. Not sure why 1399 doesn't work, if I'm correct, that should also have the fix included.

Thank you, i will test that version

**Comment by HermanCattaneo** [comment]
> Version 0.7.1397.0, that version works fine. Not sure why 1399 doesn't work, if I'm correct, that should also have the fix included.

> Thank you, i will test that version

Thank you gurabli, that version works nice. I have no clue about 1399, but i will stay at this version and wait for stable release fix. Thanks again!

**Comment by gurabli** [comment]
You're welcome! I didn't do the fix, I just tested the version with the fix and confirmed it is working. Credit goes to those who did the coding!
