### ISSUE TITLE
[ptfiles] (testing) Test search in PTFiles => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by sidneyki** [Jackett/Jackett#13617]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
http://192.168.1.12:9117/api/v2.0/indexers/ptfiles/results/torznab/
```

### Description

when adding the indexer in radarr no categories can be found

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in PTFiles => Found no results while trying to browse this tracker
Click here to open an issue on GitHub for this indexer.
```

### Screenshots

none

**Comment by garfield69** [comment]
The indexer is working for me and I can get movie results from Radarr with this indexer.
1. on the jackett dashboard use the TEST button on the ptfiles row to confirm that the indexer is working.
2. access the radarr ptfiles indexer and after updating the URL and APIKEY, then click in the Categories box, and untick the movies checkbox, tick the movies/SD HD UHD and DVD and then tick the Movies too, in that order.
3. then save. it should work as it does for me.

if it does not work then Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log including the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
