### ISSUE TITLE
[req]: Add OR logic to filter out manual search results on web ui.

### ISSUE THREAD

**Issue by batuhankrmn** [Jackett/Jackett#13619]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

When I want to filter the results for x265 codec., I can filter with +x265 but there is also HEVC tag which is commonly used for x265 codecs. So, it'd be really useful If we can filter the results with OR logic.

For the current logic, If I filter with +x265 +HEVC It'll only give the results that contains both HEVC and x265 together. This will critically limit the results because if there is HEVC on title, there might not be x265, vice versa.

### Describe the solution you'd like

As you know, we can filter out the results with + and - operators but these are working with AND logic. So we can use ( ) operator to handle OR logic.

+(x265 hevc) = Filters out the results contain HEVC or x265 in the torrent name.
-(x265 hevc) = Filters out the results doesn't contain HEVC or x265 in the torrent name.

I believe such a feature will bring a whole new functionality to Jackett. Thanks!

**Comment by mikeoscar2006** [comment]
@batuhankrmn I have created a pull request for this with a slightly different logic. If it's possible for you to test the pull request instead of waiting for the release, your feedback will be valuable. Otherwise you can open another issue or continue this as you feel like.

**Comment by batuhankrmn** [comment]
@mikeoscar2006 I checked your PR, looks like It will definitely solve the issue. I'd like to test it but I'm not familiar with the term of "testing the PR". How can I do that? Like should I download and install it like update? If you show me the way, I can test it right now.

**Comment by mikeoscar2006** [comment]
Sorry, I'm not sure if it will be possible for you without a development setup to test an individual PR.
Maybe Pipeline Binaries but would be too much work. 
I think @ilike2burnthing or @garfield69 can suggest better, whether we can test out the PR itself and merge it so the changes are live in the next release/update for you to check out or some other way.

**Comment by batuhankrmn** [comment]
> It's better to wait for their reply as they will give much better advice on this.

I agree, let's hear from them and I want to thank you for your quick contribution to this issue.  So, after the OR logic is added, can we save the parameters we use to filter the results as presets? I have detailed this request in #13618 I don't want to push the dev team and contributors; I'm just wondering if this feature can be done easily. Since you just handled OR logic in hours, I guess you may have an idea whether it is difficult to develop this feature.

**Comment by ilike2burnthing** [comment]
Generally we just provide a link to the drop folder. Users can then extract the version of the PR build they need, install, and test.

But hold off on that for now as I want to suggest a few changes.

**Comment by mikeoscar2006** [comment]
> > It's better to wait for their reply as they will give much better advice on this.
> 
> I agree, let's hear from them and I want to thank you for your quick contribution to this issue. So, after the OR logic is added, can we save the parameters we use to filter the results as presets? I have detailed this request in #13618 I don't want to push the dev team and contributors; I'm just wondering if this feature can be done easily. Since you just handled OR logic in hours, I guess you may have an idea whether it is difficult to develop this feature.

Actually, The person who has developed the UI can probably quickly tell how difficult it is. I'll definitely have a look at it and if it's a small thing, I'll create a pull as soon as I can. Otherwise I usually leave some pointers for later to be picked by me or someone else whenever we have some spare time.

**Comment by batuhankrmn** [comment]
Appreciated, thanks! @mikeoscar2006 
Please feel free to let me know when It's ready to test. @ilike2burnthing

**Comment by ilike2burnthing** [comment]
@batuhankrmn - https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/6848/artifacts?artifactName=drop&api-version=7.0&%24format=zip

`x265|hevc` will filter by `x265` OR `hevc`, but `+x265|hevc` and `-x265|hevc` do not use OR logic, rather will filter by the single keyword `x265|hevc`. See the discussion on #13621 for the reasoning why.

**Comment by batuhankrmn** [comment]
@ilike2burnthing Unfortunately, none of the parameters worked for me. I just installed the Version v0.20.2046 from the jackett.installer.windows.exe within drop.zip.  Do I need to do anything other than this?
![Screenshot_4](https://user-images.githubusercontent.com/57859656/193462970-e42b0fb0-006d-4e9a-8f62-003ada95e547.png)
![Screenshot_5](https://user-images.githubusercontent.com/57859656/193462973-798c81bc-9bc1-47f1-9f36-28a5d88bff47.png)
![Screenshot_6](https://user-images.githubusercontent.com/57859656/193462975-fc6e364c-5ccf-41d5-9e6f-a577f866d7a8.png)
![Screenshot_3](https://user-images.githubusercontent.com/57859656/193462977-7d0da8a1-8d85-4976-a921-d4beeb88607f.png)

**Comment by mikeoscar2006** [comment]
As mentioned in the PR and by @ilike2burnthing, The `|` operator won't work with `+` and `-`. So the First two screenshots shouldn't work as you can do the same functionality in the case of `-` by two filters separated by space.
As for the last screenshot, it should've worked. Are you sure you're using the Jackett server from the artifact linked in previous comment?

**Comment by ilike2burnthing** [comment]
Found the issue, fixed in https://github.com/Jackett/Jackett/pull/13621/commits/78a938395d7dd9d62a883c74d173d31a72d30985, will provide an undated download link shortly.

**Comment by mikeoscar2006** [comment]
Thanks! I'm dumb, changed a different timestamp lol.

**Comment by ilike2burnthing** [comment]
https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/6849/artifacts?artifactName=drop&api-version=7.0&%24format=zip

**Comment by batuhankrmn** [comment]
Thanks guys! It's working flawlessly with Version v0.20.2047. 
![image](https://user-images.githubusercontent.com/57859656/193466275-7a1d3b81-2a18-4045-9126-130a349f2789.png)

**Comment by garfield69** [comment]
v0.20.2063
