### ISSUE TITLE
Abnormal tracker bug

### ISSUE THREAD

**Issue by jojofofo36** [Jackett/Jackett#13614]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.1.45:8191
Using proxy: Disabled
App config/log directory: /config/Jackett
Running in Docker: Yes (image build: v0.20.1687-ls74)
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.0.0 (64bit OS) (64bit process)
Environment version: 6.0.9 (/app/Jackett/)
```

### Description

With abormal tracker the option to " replace MULTI by another language in release name " is not working. But It is working with yggtorrent.

### Logged Error Messages

```text
None
```

**Comment by garfield69** [comment]
v0.20.2034
