### ISSUE TITLE
[req]: animetracker.cc

### ISSUE THREAD

**Issue by aliswel567** [Jackett/Jackett#13611]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: animetracker.cc
- URL: https://animetracker.cc/
- Description: Animetracker is a brand-new anime private tracker that specialises in offering high-quality BD and DVD files while also enabling the posting of various types of anime content.
- Minimum Seeding Time and Minimum Ratio (if Private): MS 120hrs, MR: 0.4
- Additional Comments:
```
engine: unit3d 6.4.0

**Comment by garfield69** [comment]
v0.20.2026

**Comment by garfield69** [comment]
https://animetracker.cc/ cloudflare Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://animetracker.cc/ cloudflare Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://animetracker.cc/ - Connection timed out Error code 522

**Comment by garfield69** [comment]
@aliswel567 do you have any info on the status of animetracker, is the site gone, just broken or moved to a new domain?

**Comment by aliswel567** [comment]
@garfield69 I believe the site has been completely down for the past couple months, but don't really anything more.

**Comment by garfield69** [comment]
v0.21.1310
