### ISSUE TITLE
[req]: Export of indexers (for another Jackett instance)

### ISSUE THREAD

**Issue by DarrenPIngram** [Jackett/Jackett#13629]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Not a problem as such, more a desire.

### Describe the solution you'd like

I could have missed if this was raised in a past FR, I blame very poor eyesight if so and apologise.

Any scope to add an "export indexers" option so I can move from one instance of Jackett to another? [and import option from file]. Also it can act as a backup for those who don't backup everything...

I've seen mentions of copying Jackett data from /.config/ and have scp-ed that to another machine (Linux to Linux) but it does not seem to want to recognise the data, so maybe the advice found online was old, or something?

### Describe alternatives you've considered

I had looked at manually copying the files necessary, but as stated above, it has not been succesful. Possibly due to user/data error.

**Comment by garfield69** [comment]
The issue currently is that the passwords for private and semi indexers are encrypted by using the local machine's default configuration of the .net key and seed cryptology methods.
Which means that while you can carry over the indexer's *.json profiles and the serverConfig.json to a new machine, the dataProtection folder only works for the local machine to decrypt the passwords.
So this enhancement request would require significant redesign of the password (de)cryption services and a migration/conversion step for the local machine to ensure current indexers keep working after the upgrade to the version using the new method.

**Comment by ngosang** [comment]
We could add a new endpoint to export the indexes with passwords in plain text (decrypted by us) but I think this is a big security hole. Right now, if someone has access to the Jackett UI it's impossible to get the passwords. The same if he grabs the files from disk.
With the current implementation you can copy the files to the other machine and everything in the configuration will be imported but passwords (they will be wrong). You will have to only edit the passwords in the WebUI.
I prefer to not implement any export method.

**Comment by ilike2burnthing** [comment]
If you want to carry across your indexers, copy the `Indexers` folder.

If you want to carry across your Jackett settings, copy `ServerConfig.json`.

All I can really see an 'import/export' function doing (if it doesn't encrypt/decrypt the passwords) is un/zipping these from/into an archive file.

The only other way I could see it being workable is by requiring the admin password on export (and import?), but then using an admin password would need to be enforced, which I'm not sure is currently possible.
