### ISSUE TITLE
[PWTorrents] unable to fill episodes through the search inside Radarr

### ISSUE THREAD

**Issue by CrepuscularPulchritude** [Jackett/Jackett#13623]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19043.0 (64bit 0S)
Environment version: 6.0.9 (C:\ProgramData\Jackett\)
Starting Jackett v@.20.2034
```

### Description

I'm trying to better automate my downloads, but in trying to set up automation to grab from PWTorrents.net I'm hitting some walls. I've started my troubleshooting from adding PWT to Jackett to create a torznab feed, sending that to Sonarr, but when trying to fill episodes Sonarr can't bring up any PWT results, despite them being on the site and in the categories I've selected. The site DID have a redesign 8/29 in case that matters due to some changes on their end. 
Sonarr troubleshooting sent me to get more info, and this is where I landed without being able to proceed further:

> The Indexer's Capabilities do not support the query type (e.g. Season/Episode, etc.):
>     Within Prowlarr, an indexer's capabilities can be located in the (I) icon for the indexer
>     Jackett does not display a tracker's capabilities within its UI.

I installed prowlarr to test, and I can't add PWT to Prowlarr as a tracker, getting an error
Logs there showed the following
> 2022-10-02 15:08:03.0|Trace|IndexerHttpClient|Res: [GET] http://pwtorrents.net/browse.php?incldead=1&search=&sort=4&type=desc: 500.InternalServerError (62415 bytes) (389 ms)

Prowlarr says this is an issue coming from Jackett's end, and the devs here can maybe help, 

> nothing updated for that definition other than categories
> https://github.com/Jackett/Jackett/commits/697b21d95f20caa1f9e28d5f1af4d2ed1341f4fb/src/Jackett.Common/Definitions/pwtorrents.yml
> if they materially changed how their site handles queries then their definition will need to be updated and rewrote by someone with access to the site
> you're best bet would be to open up a github issue on jackett and then when they update the definition it'll be pulled over to prowlarr

If you guys don't have access to the site any longer, I can reach out to the admin for an invite/reactivation

I stopped jackett, backed up the old log and update text files, started jackett, and ran a test, then a search through radarr
[log.txt](https://github.com/Jackett/Jackett/files/9693610/log.txt)
no update file was created

### Logged Error Messages

```text
these were the errors from prowlarr, which they say should be able to help jackett find the issue

https://gist.github.com/CrepuscularPulchritude/2e249028a2ae25f91110c6c5693845a4

if this isn't enough, I can restart and pull logs from jackett
```

**Comment by garfield69** [comment]
yes, the pwt indexer has not been set up for use with sonarr properly.
I will post a fix shortly.
Once the new release of Jackett is available (in about 6 hours or so), and you have updated your Jackett to that new release, then:
-  you will need to access Sonarr and delete your current pwt indexer
- shut down sonnar (not just the gui page, but using the Sonarr systray **exit** )
- start up Sonarr and add the indexer anew, 
- change the default sonarr categories to TV/SPORT (5060) and save

using AEW Rampage as an example, change the Sonarr series to **Series type Daily** so that Sonarr will search for `AEW Rampage 2022.09.30` instead of `AEW Rampage S02E39`

a test shows I now can see results
![image](https://user-images.githubusercontent.com/6933240/193478352-37d17709-35d0-4160-9012-921c57ecdd6d.png)

**Comment by garfield69** [comment]
v0.20.2063
