### ISSUE TITLE
[req]: resolve search filter issues with some special characters

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#13628]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Search filter breaks upon use of `-`, `_`, and `.` (likely others) followed by another character, but not `[` (again, likely others), as discussed here - https://github.com/Jackett/Jackett/issues/13618#issuecomment-1267496974

Examples:
- `web-` works
- `web-d` does not work
- `1080p.` works
- `1080p.w` does not work
- `GRoUP[source]` works

Preceding these with `+` or `-` also does not work.

### Describe the solution you'd like

For it not to do that.

### Describe alternatives you've considered

Ctrl+F

**Comment by mikeoscar2006** [comment]
Strange! The `-` is getting escaped properly. Also Anything besides `+` should work exactly like before the PR. Don't know how nobody noticed it before.
Will try to find out why it isn't working even after being properly escaped.

**Comment by mikeoscar2006** [comment]
`web dl` works instead of `web-dl`
`web- dl` works instead of `web-dl`
`web H264` works instead of `web.H264` but also includes results with space in between
`web. dl` works perfectly instead of `web.dl`

Suggestion: Split the keyword on `-` or `.`  and keep it in front of first word.
Thoughts?

**Comment by ilike2burnthing** [comment]
The issue there being that rather than matching `web-dl`, you're now matching `web-` and `dl` instead, which could have other matches - `The.Candle.2022.1080p.WEB-NoGRP`

While an unlikely match, I'd rather work out why some special characters are breaking the search, but others aren't, and then resolve that, not just split the keyword on each of them, because there are likely more than the 3 listed above.
