### ISSUE TITLE
[acidlounge] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13627]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

acidlounge is offline

### Logged Error Messages

```text
https://www.acid-lounge.org.uk/ returns ERR_CONNECTION_REFUSED
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> We are looking at closing around the middle of next month [August] and will update the news as required.

**Comment by garfield69** [comment]
v0.22.545
