### ISSUE TITLE
[cinemaz] (testing) Exception (cinemaz): Unknown error: <!DOCTYPE html>

### ISSUE THREAD

**Issue by Vrozaksen** [Jackett/Jackett#13637]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
whatbox Jackett version (cant find)
```

### Description

Just added it to Jackett (Prowlarr have same issue)

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (cinemaz): Unknown error: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Error</title>

<link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

<style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 36px;
                padding: 20px;
            }
        </style>
</head>
<body>
<div class="flex-center position-ref full-height">
<div class="content">
<div class="title">
Too many requests. </div>
</div>
</div>
</body>
</html>

 ---> System.Exception: Unknown error: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Error</title>

<link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

<style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 36px;
                padding: 20px;
            }
        </style>
</head>
<body>
<div class="flex-center position-ref full-height">
<div class="content">
<div class="title">
Too many requests. </div>
</div>
</div>
</body>
</html>

   at Jackett.Common.Indexers.Abstract.AvistazTracker.PerformQuery(TorznabQuery query)
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer)
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer)
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request)
```

**Comment by ilike2burnthing** [comment]
You can find Jackett's version at the bottom of the webUI, or just follow the instructions in the initial issue template and post the startup logs.

Cinemaz is working ok here. This may be an issue with you using a shared IP from your seedbox.

Was it previously working for you?

Do other indexers work?

Does Cinemaz work on a local install for you?

**Comment by Vrozaksen** [comment]
> You can find Jackett's version at the bottom of the webUI, or just follow the instructions in the initial issue template and post the startup logs.
> 
> Cinemaz is working ok here. This may be an issue with you using a shared IP from your seedbox.
> 
> Was it previously working for you?
> 
> Do other indexers work?
> 
> Does Cinemaz work on a local install for you?
There is nothing on bottom of WebUI, maybe that was because of my AdGuard blocking footer...

It's my first time using CinemaZ, but other indexers work most of the time, this one just doesn't.

Nope i was checking Prowlarr on my Unraid Server and there is the same issue, that's little bit crazy, but maybe that's becaue i use AdGuard everywhere, maybe this issue is made with Radarr. My networking setup is crazy. I will check if that's AdGuard blocking something, or change URL from Radarr to Jackett/Prowlarr.

**Comment by garfield69** [comment]
cinemaz had flagged your traffic with a `Too many requests.`
if you are using sonarr or radarr then perhaps throttle back the rss period and perhaps avoid using those apps with cinemaz for a day or more to let the site relax its observation focus on your ip traffic.

**Comment by Vrozaksen** [comment]
2022-10-10 08:05:40 | Info | Using HTTP Client: HttpWebClient2
2022-10-10 08:05:40 | Info | Using FlareSolverr: No
2022-10-10 08:05:40 | Info | Using proxy: Disabled
2022-10-10 08:05:40 | Info | App config/log directory: /home/<PRIVATE>/.config/Jackett
2022-10-10 08:05:40 | Info | ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-10-10 08:05:40 | Info | Running in Docker: No
2022-10-10 08:05:40 | Info | File /etc/issue:
2022-10-10 08:05:40 | Info | Jackett variant: CoreLinuxAmdx64
2022-10-10 08:05:40 | Info | OS version: Unix 5.10.103.0 (64bit OS) (64bit process)
2022-10-10 08:05:40 | Info | Environment version: 6.0.1 (/usr/share/jackett/)
2022-10-10 08:05:39 | Info | Starting Jackett v0.0.0

I got version :D

Okay i'm gonna wait some time and we will see if thats true, maybe there is an option to "slow down" Jackett/Radarr with requests? I have seen torrentleech.pl sometimes have same issue

**Comment by ilike2burnthing** [comment]
v0.0.0? Well that's unfortunately unhelpful.

As garfield69 said, reduce the RSS period:
Sonarr/Radarr > Settings > Indexers > click 'Show Advanced' > increase 'RSS Sync Interval' > Save Changes

Right now though, you should just disable or remove the Cinemaz indexer in Sonarr/Radarr altogether.

**Comment by Vrozaksen** [comment]
So i did only one "Manual Search" in radarr now and "Too many requests." still happens... I don't know where is the issue, it was like 2 days...

**Comment by ilike2burnthing** [comment]
Did you disable RSS for the indexer in Sonarr/Radarr 2 days ago?

If so, then as I said in my initial reply, "This may be an issue with you using a shared IP from your seedbox."
