### ISSUE TITLE
[req]: Is webui accessible from other devices in same local network

### ISSUE THREAD

**Issue by itsboo07** [Jackett/Jackett#13630]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I run jackett in windows 11 and i can access web ui by http://localhost:9117 and my local host ip is 192.168.1.20).soo if i use http://192.168.1.20:9117 this too works but when i use the same url in other device from same local network then webpage does not load at all...why is this limited accessible to only on the device where jackett is installed and running?
also tried proxy and doesnot work either

### Describe the solution you'd like

i would like to access the webpage from other devices in same local network

**Comment by garfield69** [comment]
Access the Jackett dashboard, tick the **external access** checkbox and click on the **apply server settings** button.

just make sure that your router and Jackett firewall **DO NOT** have port 9117 automatically open to wan unless you want to also allow wan access, in which case I recommend enabling the Jackett admin password for security.
