### ISSUE TITLE
[torrentgalaxy] (configuring) Connection timed out (torrentgalaxy.to:443): Connection timed out

### ISSUE THREAD

**Issue by carnby77** [Jackett/Jackett#13634]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett running pi3b+ with raspios lite 64
```

### Description

i cant seem to add in torrentgalaxy into jackett indexer

### Logged Error Messages

```text
[torrentgalaxy] (configuring) Connection timed out (torrentgalaxy.to:443): Connection timed out
```

### Screenshots

![image](https://user-images.githubusercontent.com/89453256/194614503-c973df2f-987d-44d8-9343-6e64d72466ca.png)

**Comment by garfield69** [comment]
Have you tried any of the alternate sitelink in the TGx config?
Don't forget the site has a captcha that needs filling in with you config.
if you can't get any of them to work then 2 things:
- Please provide the full environment data as requested in the original post.  The best way to do this is to restart Jackett, access the dashboard, view the log, and copy/paste the **last 10 Info lines** at the bottom of the log.
- Please turn on **enhanced** logging, repeat the test and provide the **full enhanced log** including the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
