### ISSUE TITLE
[cpasbien] down - ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#13636]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Description

https://vwwvwvwvvw.cpasbien-fr.nz/ - ERR_NAME_NOT_RESOLVED

**Comment by garfield69** [comment]
v0.20.2093
