### ISSUE TITLE
[TorrentDB] Freeleech torrents aren't being tagged as freeleech

### ISSUE THREAD

**Issue by zHyuma** [Jackett/Jackett#13632]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using v0.20.2082
```

### Description

When searching TorrentDB, freeleech torrents aren't marked by the freeleech tag. Appearing as regular torrents.

Website source changed, and might need a definition update.

### Logged Error Messages

```text
Nothing
```

**Comment by garfield69** [comment]
urg. looks like they have dropped fontawsome icons and are using svg instead.

**Comment by garfield69** [comment]
v0.20.2092

**Comment by zHyuma** [comment]
Thanks a lot, garfield!
