### ISSUE TITLE
[BUG] Every new release resets the saved search filters.

### ISSUE THREAD

**Issue by batuhankrmn** [Jackett/Jackett#13639]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows 11 Pro
Jackett Version v0.20.2098
```

### Description

#13618 Since we got the saving search filters feature, I noticed that saved filters being resetted with every new release of Jackett.  I have to save them again and again after every update.

### Logged Error Messages

```text
N/A
```

**Comment by ilike2burnthing** [comment]
Just tested this in Windows 10 Sandbox using Chrome with no extensions, updating Jackett both manually and with the internal updater, restarting the browser in between each, and had no issue with the saved filters being removed.

What browser are you using? Any addons/extensions which may be interfering with this? Are you using any temp file cleaning software, or have you set your browser to clean certain files on close?

**Comment by batuhankrmn** [comment]
Wait a minute, does this feature change from browser to browser? I mean I just checked the filters from Edge (I saved the filters on Edge) and they didn't showed up on Chrome. If this is the situation I guess it's not a bug. I thought the filters were saved locally and would work the same in all browsers on the same device.

**Comment by ilike2burnthing** [comment]
They're saved on the local storage used by the browser, so the filters are unique to each browser.
