### ISSUE TITLE
[req]: Adapt updated Animebytes data for better release names

### ISSUE THREAD

**Issue by timothy-adam** [Jackett/Jackett#13631]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Animebytes and sonarr often rely on custom thexem mappings to work. Getting someone to add and approval for these mappings can be annoying.

According to https://github.com/Prowlarr/Prowlarr/issues/1115#issue-1363214172 animebytes very recently updated their api to return a list of filenames, this data could be used to generate better release names.

### Describe the solution you'd like

https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/AnimeBytes.cs#L335

I think adding an option to the animebytes tracker to add a synonym release with a title extracted from the filename could improve the interaction of jackett and sonarr.

### Describe alternatives you've considered

Waiting on prowlarr to update its mapping and switching over to it, but I like how lean jackett is compared to prowlarr.

**Comment by ilike2burnthing** [comment]
Where there is more than one file in a release, how would a name be created?

**Comment by timothy-adam** [comment]
I did not think about that.

But thinking about it now I can think of two things:
1)Do nothing. Ignoring multi-file releases wont make the current situation any worse then it is.
2)Use the file with the largest size to extract the name from

The biggest thing I'd like to see happen is that downloads for newly released shows work, I never use jackett/sonarr to download packs.

**Comment by ilike2burnthing** [comment]
Can you provide the filelist for a single episode release?

**Comment by timothy-adam** [comment]
```"FileCount":1,"FileList":[{"filename":"[SubsPlease] Spy x Family - 13 (1080p) [384E4368].mkv","size":"1475976907"}]```

**Comment by ilike2burnthing** [comment]
Ok, it's doable for single episode releases then if there's just one file. Basically just - if FileCount=1 use filename as title.

For releases with multiple files, I'm not sure using any one file (first, largest, random) would work, as you'd likely then be naming a season pack as just one episode, which obviously isn't great.

This will need someone with an account and C# skills.

**Comment by timothy-adam** [comment]
https://github.com/Jackett/Jackett/pull/13633

**Comment by garfield69** [comment]
v0.20.2092
