### ISSUE TITLE
[GPW] add option to replace group title with the first torrent filename

### ISSUE THREAD

**Issue by KyleSanderson** [Jackett/Jackett#13646]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
0.20.2100
```

### Description

Jackett returns both the Title and Subtitle from the search results. Unfortunately presently the Title is English, and the Subtitle is the same text in Mandarin, which results in an incomprehensible nightmare. The content from the tracker are also in English for these titles. Prowlarr does not have this defect with the same titles, and unfortunately now has me as a user again for this single tracker.

### Logged Error Messages

```text
https://github.com/Jackett/Jackett/issues/13641#issuecomment-1276920080
```

**Comment by garfield69** [comment]
v0.20.2134

**Comment by KyleSanderson** [comment]
> v0.20.2134

This still isn't correct. Prowlarr returns the actual name, Jackett is returning some crazy formatted string.

**Comment by garfield69** [comment]
please access the GPW website and do your search, and take a screen shot of the result and point to what it is you think that Jackett should be displaying.
you asked for the simplified Chinese to be left out and that is what we did.

**Comment by KyleSanderson** [comment]
Correct - my apologies. I didn't realize it wasn't the valid string anyway. This is the difference between the three.

![image](https://user-images.githubusercontent.com/1184902/199318108-1774afbe-69a3-47b4-bf65-8acff43ede8f.png)
![image](https://user-images.githubusercontent.com/1184902/199318192-82f7cb1f-fb82-4609-a82d-b179251bdf46.png)
![image](https://user-images.githubusercontent.com/1184902/199318421-952de4cb-0280-457f-aaaa-d332c25cb7bf.png)

**Comment by garfield69** [comment]
so what you are really asking for, is that instead of showing the group name and item details from the results (the section above the media details) you would like an option to display the first torrent filename?

**Comment by garfield69** [comment]
we don't have access to the folder name. the GPW api returns (example)
```json
{
	"groupId":9999,
	"groupName":"group name title",
	"groupSubName":"chinese title",
	"cover":"poster url .jpg",
	"tags":["drama","action","crime"],
	"bookmarked":false,
	"groupYear":2006,
	"releaseType":"Feature Film",
	"groupTime":"1667324726",
	"maxSize":35024758146,
	"totalSnatched":14,
	"totalSeeders":2,
	"totalLeechers":0,
	"imdbId":"tt12345678",
	"imdbRating":"6",
	"imdbVote":"111777",
	"doubanId":"99999999",
	"doubanRating":"5.7",
	"doubanVote":"13895",
	"rtRating":"46%",
	"region":"Germany, United States",
	"torrents":[
	{
		"torrentId":9999,
		"editionId":0,
		"remasterYear":0,
		"remasterTitle":"",
		"remasterCustomTitle":"",
		"scene":false,
		"jinzhuan":false,
		"fileCount":1,
		"time":"2021-07-02 07:28:03",
		"size":4180401550,
		"snatches":14,
		"seeders":1,
		"leechers":0,
		"isFreeleech":false,
		"isNeutralLeech":false,
		"freeType":"0",
		"isPersonalFreeleech":false,
		"canUseToken":true,
		"hasSnatched":false,
		"resolution":"576p",
		"source":"Blu-ray",
		"codec":"x264",
		"container":"MKV",
		"processing":"Encode",
		"chineseDubbed":"0",
		"specialSub":"0",
		"subtitles":"english,french,spanish",
		"fileName":"file.name.2006.Unrated.DC.576p.BluRay.DD5.1.x264-releasegroup",
		"releaseGroup":"releasegroup"
	}]
}
```

so we might be able to use the first torrents.filename and display that. 
the indexer uses the gazelletracker abstract which is a common module Jackett uses for all the gazelle engine web sites that Jackett has indexers for.
I don't know if I will be able to add this customization, I will take a look and have a go, but I may need to defer to a proper C# dev if I can figure out how to make it work.

**Comment by garfield69** [comment]
v0.20.2189
