### ISSUE TITLE
Jackett can't find the results on the Turkseed tracker.

### ISSUE THREAD

**Issue by batuhankrmn** [Jackett/Jackett#13650]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.20.2109
Windows 11 Pro
```

### Description

I noticed that while I was doing some performance testing for the trackers that I added to jackett, I was testing the which trackers cause the long query times, turns out It was the RARBG. Anyway... I noticed that Turkseed tracker doesn't return anything for my search queries, so I went to the tracker itself and did the same search, there was a result for my query. Seem like this indexer has some issues to gather results from Turkseed. I'm adding the proofs.

### Logged Error Messages

```text
N/A
```

### Screenshots

![16 10 2022 - 04 47 (38)](https://user-images.githubusercontent.com/57859656/196014238-9007d434-7bb8-4244-acd0-f145975e2404.png)
![16 10 2022 - 04 48 (07)](https://user-images.githubusercontent.com/57859656/196014241-3286243d-869c-4fe9-8b45-4254cbfdb1fa.png)
![16 10 2022 - 04 49 (41)](https://user-images.githubusercontent.com/57859656/196014242-bfda4b5a-4522-4ad3-8015-c8bc6645f319.png)
![16 10 2022 - 04 49 (23)](https://user-images.githubusercontent.com/57859656/196014243-6a7f6099-6182-4810-8428-e6caf2a797fc.png)

**Comment by garfield69** [comment]
confirmed. the indexer is using the name search which apparently stopped working when turkseed upgraded their engine from 7.5 to 8.0 yesterday.
we need  to update the indexer to use the name&descr option.

**Comment by ilike2burnthing** [comment]
They appear to only be using Turkish names for the name search.

Despite `Avengers` being in the title of the result above, if you name-only search `Avengers`, zero results are returned. Even when you switch to name and description search, you only get one result for `Avengers`.

But, if you search `Yenilmezler` in torrent name only, you get 9 results - 8 with `Avengers` in the results title (and 1 `Avangers`).

**Comment by garfield69** [comment]
Ah. its case sensitive. searching for Avengers returns results.

**Comment by batuhankrmn** [comment]
> They appear to only be using Turkish names for the name search.

Yes, this is common Turkish tracker behavior. Most of the Turkish trackers aim only Turkish people, so they have no interest to be global tracker. I also use them only for Turkish content tho. Thanks for fixing!

**Comment by garfield69** [comment]
v0.20.2113
