### ISSUE TITLE
[req]: Yts.pm

### ISSUE THREAD

**Issue by itsboo07** [Jackett/Jackett#13659]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: YTS
- URL: https://yts.pm
- Description: public torrent for movies 
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: most of the yts available base urls are blocked by my ISP... Yts.pm is the only working for now.... Is it possible to create this as base url?
When I tried yts.pm I get api error
- log: [yts] (testing) Exception (yts): Error Parsing Json Response: Status=NotFound Response={"Message":"No HTTP resource was found that matches the request URI 'http://yts.pm/api/v2/list_movies.json?query_term=&limit=50&sort=date_added'."}: Error Parsing Json Response: Status=NotFound Response={"Message":"No HTTP resource was found that matches the request URI 'http://yts.pm/api/v2/list_movies.json?query_term=&limit=50&sort=date_added'."}
```

**Comment by itsboo07** [comment]
thanks for responding...none of those official mirros works with my ISP...i tried to change few dns servers and still same result...only with vpn it works .....looks like my ISP have handblocked it with ip....
![image](https://user-images.githubusercontent.com/87331871/196768645-b8a2950d-4248-49b4-aee6-102ad37efad9.png)

**Comment by itsboo07** [comment]
@ilike2burnthing one small doubt...when I run same dns in android and and in windows...i can access yts.mx in android but in windows i cant... I also tried to check with dnsleaktest and it shows the corrent dns ....what am i missing and sorry to bother you.

**Comment by ilike2burnthing** [comment]
On Android are you using WiFi or cellular/mobile data?

Are you using a VPN on either?

**Comment by itsboo07** [comment]
Wifi...and no vpn...
Can i create a own custom indexer for yts.pm?

**Comment by ilike2burnthing** [comment]
Odd. Not sure why it would work for one but not the other.

Sure, PRs are always welcome.
