### ISSUE TITLE
Configuration failed on Animetorrents.me

### ISSUE THREAD

**Issue by techprowizard** [Jackett/Jackett#1366]
First time user of Jackett, and when i try to add Animetorrents.me i get the error "Configuration failed: an error occurred while sending the request". Other sources like TPB add just fine.
Running on Mono 5.0.0 on Ubuntu 16.0.4.2.

[log.txt](https://github.com/Jackett/Jackett/files/998892/log.txt)

**Comment by BoavaNet** [comment]
same here
Running unraid OS 6, docker img

**Comment by kaso17** [comment]
Works for me.

Please provide the complete log. The one posted is incomplete (just 3 lines).

**Comment by techprowizard** [comment]
Whoops. Must have grabbed the wrong one. this one should be right.
[log.txt](https://github.com/Jackett/Jackett/files/999587/log.txt)

**Comment by kaso17** [comment]
Some low level TLS error. Are other HTTPS trackers working for you?
If possible try downgrading mono to 4.8.

**Comment by kaso17** [comment]
it's working fine for me with mono 5.
There was a minor problem with the login (you had to click twice on okay, fixed with 37dc039de442139764953de30966af107915bb1e). But I'm confused why you're getting an TLS error at all. Until now http was the default for animetorrents.

**Comment by techprowizard** [comment]
Other https tackers seem to work. Also both http and https seem to give the error.

**Comment by kaso17** [comment]
please try updating to v0.7.1411 just to be sure it's not a related error.
Please also post the log lines before the ones you already posted.

**Comment by techprowizard** [comment]
rolled back to mono 4.8 and it added with no issue.

**Comment by kaso17** [comment]
Which mono 5 version were you running?
With 5.0.0 (Stable 5.0.0.100/9667aa6 Thu May 11 14:48:10 UTC 2017) it's working fine for me

**Comment by techprowizard** [comment]
Whatever was the most up to date for ubuntu. I just re-setup the server it is running on a week ago.

**Comment by kaso17** [comment]
The latest version is from May 11, so this might be already fixed on the mono side.

**Comment by techprowizard** [comment]
Possibly. I honestly don't remember. But I won't worry about it since 4.8 is working so far.

**Comment by techprowizard** [comment]
Thanks for the suggestions though. I may try that at a later date.
