### ISSUE TITLE
[req]: Support Padavan firmware (Asus routers etc...)

### ISSUE THREAD

**Issue by x-tropic** [Jackett/Jackett#13667]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I try install jackett to my router with Paadavan firmware (openwrt alternative).

i installed the following repositories: icu icu-full-data libstdcpp libintl-full procps-ng procps-ng-pgrep coreutils-whoami coreutils-readlink (from here: http://bin.entware.net/mipselsf-k3.4/archive/)

Now i try launch jackett and getting error:
`./jackett: line 1: syntax error: unexpected word (expecting ")")`

### Describe the solution you'd like

What information can I provide so that you can understand if the jackett can be installed on my architecture?

BusyBox v1.31.1 (2022-05-17 22:44:50 +05) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.

Currently defined functions:
        addgroup, adduser, arp, arping, ash, awk, basename, bash, brctl,
        bunzip2, bzcat, bzip2, cat, chgrp, chmod, chown, chpasswd, chroot,
        clear, cp, crond, crontab, cut, date, dd, df, dhcp6c, dirname, dmesg,
        dnsdomainname, dos2unix, du, echo, egrep, eject, env, ether-wake, expr,
        false, fdisk, fgrep, find, flock, free, fuser, grep, gunzip, gzip,
        head, hostname, ifconfig, inetd, insmod, kill, killall, klogd, ln,
        logger, login, ls, lsmod, lsof, md5sum, mdev, microcom, mkdir, mknod,
        mkswap, modprobe, more, mount, mountpoint, mv, netstat, nice, nslookup,
        ntpd, passwd, pgrep, pidof, ping, ping6, printf, ps, pwd, rm, rmdir,
        rmmod, route, sed, sendmail, seq, sh, sleep, sort, start-stop-daemon,
        stat, strings, swapoff, swapon, switch_root, sync, sysctl, syslogd,
        tail, tar, tee, telnet, telnetd, test, time, top, touch, tr,
        traceroute, traceroute6, true, udhcpc, umount, uname, uniq, unix2dos,
        unlink, uptime, usleep, vconfig, vi, watch, wc, wget, which, whoami,
        xargs, yes, zcat, zcip

```
/opt/home/admin # uname -a
Linux MI-MINI 3.4.113 #1 Tue May 17 22:36:40 +05 2022 mips GNU/Linux
```

**Comment by ilike2burnthing** [comment]
Are the OpenWrt instructions applicable or at least adaptable? https://github.com/Jackett/Jackett/wiki/Installation-on-OpenWrt

**Comment by x-tropic** [comment]
> Are the OpenWrt instructions applicable or at least adaptable? https://github.com/Jackett/Jackett/wiki/Installation-on-OpenWrt

I followed this guide and got an error when starting jackett_launcher.sh
`./jackett: line 1: syntax error: unexpected word (expecting ")")`

Can I provide the necessary information so that you can understand whether it is possible to install jackett on my firmware or not?

**Comment by ilike2burnthing** [comment]
Sorry, Jackett does not support MIPS architecture.
