### ISSUE TITLE
[rarbg] (updating) Could not find releases from this URL 

### ISSUE THREAD

**Issue by IleneUlick** [Jackett/Jackett#13662]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.20.2124
```

### Description

Doesn't function properly and can't get it working keep getting:

An error occurred while updating this indexer
Could not find releases from this URL

### Logged Error Messages

```text
An error occurred while updating this indexer
Could not find releases from this URL
```

### Screenshots

![Screenshot 2022-10-20 101709](https://user-images.githubusercontent.com/116300937/197015686-522f556e-a4fd-4aee-a53a-788455ccdba4.png)

**Comment by ilike2burnthing** [comment]
As requested when first opening your issue:

> Please provide the details of the system Jackett is running on. The best way to do this is to restart Jackett, access the dashboard, view the log, and copy/paste the last 10 Info lines at the bottom of the log.

If you access https://torrentapi.org/pubapi_v2.php in browser from the same device and IP, using the same DNS, what do you see?

**Comment by IleneUlick** [comment]
Sorry I’m a noob I have no idea. This is being used on my seedbox and have no idea how to find the logs. There is no “dashboard”  view log that I can see. Sent from my iPhoneOn Oct 20, 2022, at 11:28 AM, ilike2burnthing ***@***.***> wrote:﻿
As requested when first opening your issue:

Please provide the details of the system Jackett is running on. The best way to do this is to restart Jackett, access the dashboard, view the log, and copy/paste the last 10 Info lines at the bottom of the log.

If you access https://torrentapi.org/pubapi_v2.php in browser from the same device and IP, using the same DNS, what do you see?

**Comment by IleneUlick** [comment]
> FYI I'm having to use hideme today to get results from the rarbg api, without which I get a `{"error":"No results found","error_code":20,"rate_limit":1}` returned no matter how long I wait between attempts.

What is "hideme"?

**Comment by garfield69** [comment]
>what is hideme?

a free vpn, home page at https://hide.me/

**Comment by IleneUlick** [comment]
Oh duh I’ve heard of that. Something is whack with rarbg today! Sent from my iPhoneOn Oct 20, 2022, at 1:01 PM, garfield69 ***@***.***> wrote:﻿

what is hideme?

a free vpn, home page at https://hide.me/

**Comment by ilike2burnthing** [comment]
From my IP RARBG works fine, but when using a NordVPN SOCKS5 proxy it returns no results. I would have said that maybe they're blocking shared IPs (e.g. seedboxes and VPNs), but @garfield69 is experiencing the complete opposite.

I have to agree with the very technical assessment, 'something is whack with rarbg today'.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/13663
