### ISSUE TITLE
[req]: prevent repeated identical queries from hammering a torrent site via Jackett

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13676]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

as highlighted by https://github.com/Jackett/Jackett/issues/13663#issuecomment-1288311897 and hopefully correctly explained by https://github.com/Jackett/Jackett/issues/13663#issuecomment-1288339707

it is possible for Jackett to be deliberately/inadvertently used to abuse torrent web sites by hammering them with repeated requests for the same query (typically the keywordless search (or TEST which is the equivalent). 

### Describe the solution you'd like

I was thinking that maybe, the cache should be permanently on, and that turning it off on the config would actually only avoid cache lookup if the incoming query is not identical to the previous one if it arrives within a time period (say within 30 seconds).

in this way if someone turns off the cache in the config, but generates repeatedly the same query, the cache would service the results and avoid torrent site bashing.

notes: this conflicts with https://github.com/Jackett/Jackett#search-cache and https://github.com/Jackett/Jackett#torznab-cache

OH, and the cache TTL should have a minimum value to prevent it being set so low as to be pointless (such as anything below 300 seconds / 5mins).

### Describe alternatives you've considered

these limits are up for discussion. I just want to avoid a site getting 25 identical requests within a minute for example.

OR

For a simpler approach, we could just set our own rate limit for incoming requests and bounce identical requests within a short time period

**Comment by ilike2burnthing** [comment]
An enforced cache would be easy enough to get around for those deliberately wanting to do so, they would just randomise the keyword.

I could also see a minimum TTL being a problem/annoyance when trying to get enhanced logs from users (more so than usual), and also if trying to test minor changes when working on an indexer.

I think the cache being enabled by default is enough to catch most users who would accidentally do something like this.

**Comment by garfield69** [comment]
closing as improactical
