### ISSUE TITLE
New Torznab indexers - "Invalid API Key"

### ISSUE THREAD

**Issue by jamaroney** [Jackett/Jackett#13679]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient
Mono version: 6.8.0.105 (6.8.0.105 Mon Mar  9 21:00:56 UTC 2020)
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /usr/local/jackett
ThreadPool MaxThreads: 800 workerThreads, 200 completionPortThreads
Running in Docker: No
Jackett variant: Mono
OS version: Unix 13.1.2.0 (64bit OS) (64bit process)
Environment version: 4.0.30319.42000 (/usr/local/lib/mono/4.5)
Jackett Data will be stored in: /usr/local/jackett
Starting Jackett v0.20.2158
```

### Description

I use Jackett for Torznab Indexers for Sonarr (TV) and Watcher (movies). Recently, I tried adding several new Indexers to both programs, but each time I do, I keep getting "Invalid API Key" even though the API is accurate. And all indexers test fine within Jackett.

The weird thing is if I do a "Test" on any Torznab indexer that I previously set up on either program (via Jackett w/ same API key), either program says all is OK. So the problem lies only with any new indexers I'm trying to add. To test this further, I removed an indexer from one of the programs, and when I tried to re-add it, again the "Invalid API Key" shows.

The fact that both Sonarr (mono) and Watcher (python) both act that way suggests that the problem lies within Jackett.

### Logged Error Messages

```text
From Sonarr:

2022-10-25 05:50:16.9|Warn|Torznab|Indexer returned result for RSS URL, API Key appears to be invalid: Invalid API key
2022-10-25 05:50:16.9|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- ApiKey: Invalid API Key
2022-10-25 05:57:42.7|Error|NewznabCapabilitiesProvider|Failed to determine newznab api capabilities for http://192.168.1.103:9117/api/v2.0/indexers/torrentdownloads/results/torznab/, using the defaults instead till Sonarr restarts
```

**Comment by ilike2burnthing** [comment]
If you copy the API key from a working indexer in Sonarr, and use it on a new indexer, does that work? If so, does that key match the one you're seeing in Jackett?

Are you sure there's no leading or trailing space being added?

Are you just running the one instance of Jackett?

Do you know roughly when/what version you were last able to add new Jackett indexers to Sonarr?

What version of Jackett are you running?

**Comment by jamaroney** [comment]
"If you copy the API key from a working indexer in Sonarr, and use it on a new indexer, does that work?"

That did the trick! Very weird - I'm looking at the API shown on Jackett (which I originally copied) and it's EXACTLY the same as what I copied from a working indexer.

**Comment by maopequena** [comment]
> "If you copy the API key from a working indexer in Sonarr, and use it on a new indexer, does that work?"

That did not do the trick for me, since I'm a new user and have no older indexers. I checked for leading a trailing spaces, checked each character, and still receive the "Invalid API Key" message in *arr apps (Sonarr, Readarr and Radarr). What I don't understand is that this is a brand new Docker install. 
Also, testing indexers works fine. And if I add them as RSS they also work fine, but then there's no search.

Help, please?
