### ISSUE TITLE
[req]: Add download description endpoint

### ISSUE THREAD

**Issue by AzRunRCE** [Jackett/Jackett#13671]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hello guys,
i use the api of jaccket and i have a problem when the torrent source is an magnet.
**Current behavior** : When the result source is an magnet the download endpoint make an redirection. (HTTP Location). 
And for this reason i can't handle the location destination in javascript because the fetch api follow redirect automatically and reject an error

### Describe the solution you'd like

Can you add an endpoint where result is given into an json response body
(direct link or the magnet uri)
for exemple
` { Url: "magnet://blabla"
}`

### Describe alternatives you've considered

I have tried many things to handle the location destination from the header
 (fetch api, XMLRequest, axios etc..) any javascript library can't catch the location destination

**Comment by ilike2burnthing** [comment]
When the magnet link or infohash are on the search results page of the tracker, the `magneturl` is returned in the API:

```text
<torznab:attr name="magneturl" value="magnet:?xt=urn:btih:0123ABCD...&amp;dn=NameGoesHere&amp;tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce...
```

I assume you're referring to when the magnet link or infohash are instead on the details page of a result. We can't provide the `magneturl` in this case, as it would mean requesting the details page of every result (we aim for around 100 results per indexer per search).

If I've misunderstood, let me know.

**Comment by AzRunRCE** [comment]
Thank you for your quick reply.
I think there is confusion. I understand that sometimes torrent sites provide magnet:// urls to get the torrents.
I would just like the [endpoint ](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Server/Controllers/DownloadController.cs )line 70 rather than making a redirect wrap the response in a json.

for Exemple this new endpoint
```
 [HttpGet]
public async Task<IActionResult> GetDownloadDescription(string indexerID, string path, string jackett_apikey, string file)
{
     return Json(new { torrent: "magnet://"});
}
```


Because when we make a fetch in javascript on given Link from the result it occurs an error for unsuported protocol.

**Comment by ilike2burnthing** [comment]
I'm sure this makes sense, but my brain is refusing to process it.

@garfield69 are you able to better understand this than me right now?

**Comment by garfield69** [comment]
@AzRunRCE It is confusing to me because I don't see how a JS script could end up using the Jackett downloadcontroller if you are using the Jackett Torznab API to make search requests.
typical example:
`http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=REDACTED&t=tvsearch&q=resident%20alien%20s02`
xml returned
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://127.0.0.1:9117/" rel="self" type="application/rss+xml" />
    <title>RARBG</title>
    <description>RARBG is a Public torrent site for MOVIES / TV / GENERAL</description>
    <link>https://rarbg.to/</link>
    <language>en-US</language>
    <category>search</category>
    <item>
      <title>Resident.Alien.S02.WEBRip.x265-ION265</title>
      <guid>https://rarbg.to/infohash/d3b79a9f13428f2ecb8f72c630f097df2181ec27</guid>
      <jackettindexer id="rarbg">RARBG</jackettindexer>
      <type>public</type>
      <comments>https://torrentapi.org/redirect_to_info.php?token=REDACTEDapp_id=ttekcaJ_v0.20.2158</comments>
      <pubDate>Sat, 01 Oct 2022 08:34:15 +1300</pubDate>
      <size>4953928892</size>
      <description />
      <link>magnet:?xt=urn:btih:d3b79a9f13428f2ecb8f72c630f097df2181ec27&amp;dn=Resident.Alien.S02.WEBRip.x265-ION265&amp;tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&amp;tr=udp%3A%2F%2F9.rarbg.me%3A2790&amp;tr=udp%3A%2F%2F9.rarbg.to%3A2740&amp;tr=udp%3A%2F%2Ftracker.thinelephant.org%3A12710&amp;tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14790</link>
      <category>5030</category>
      <category>100018</category>
      <enclosure url="magnet:?xt=urn:btih:d3b79a9f13428f2ecb8f72c630f097df2181ec27&amp;dn=Resident.Alien.S02.WEBRip.x265-ION265&amp;tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&amp;tr=udp%3A%2F%2F9.rarbg.me%3A2790&amp;tr=udp%3A%2F%2F9.rarbg.to%3A2740&amp;tr=udp%3A%2F%2Ftracker.thinelephant.org%3A12710&amp;tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14790" length="4953928892" type="application/x-bittorrent" />
      <torznab:attr name="category" value="5030" />
      <torznab:attr name="category" value="100018" />
      <torznab:attr name="tvdbid" value="368166" />
      <torznab:attr name="imdb" value="8690918" />
      <torznab:attr name="imdbid" value="tt8690918" />
      <torznab:attr name="tmdbid" value="96580" />
      <torznab:attr name="genre" value="" />
      <torznab:attr name="seeders" value="13" />
      <torznab:attr name="peers" value="16" />
      <torznab:attr name="infohash" value="d3b79a9f13428f2ecb8f72c630f097df2181ec27" />
      <torznab:attr name="magneturl" value="magnet:?xt=urn:btih:d3b79a9f13428f2ecb8f72c630f097df2181ec27&amp;dn=Resident.Alien.S02.WEBRip.x265-ION265&amp;tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&amp;tr=udp%3A%2F%2F9.rarbg.me%3A2790&amp;tr=udp%3A%2F%2F9.rarbg.to%3A2740&amp;tr=udp%3A%2F%2Ftracker.thinelephant.org%3A12710&amp;tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14790" />
      <torznab:attr name="downloadvolumefactor" value="0" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>
[...]
  </channel>
</rss>
```
that is how all the *arr apps make requests to jackett for search queries, and process the results as they see fit.

what is your JS doing that is different from this?
Are you emulating the internal calls that the Jackett WEBUI is making when a user is browsing the Jackett dashboard?
