### ISSUE TITLE
[hdfans] (updating) Error: 登录 / 注册失败图片代码无效！不要返回，图片代码已被清除！点击这里获取新的图片代码。

### ISSUE THREAD

**Issue by dinsen80951** [Jackett/Jackett#13680]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: 
- URL: 
- Description: 
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments:
```

**Comment by ilike2burnthing** [comment]
You have opened an indexer request, but it looks like you meant to open a bug report.

Try adding the indexer again, making sure to enter your username, password, the captcha, and a 2FA code if you have one.

If that still fails, then open a bug report and provide the information requested.
