### ISSUE TITLE
[BUG] U-Torrents  Doesn't Work

### ISSUE THREAD

**Issue by VadVoci** [Jackett/Jackett#1368]
http:// u-torrents .ro

Found 0 releases from u-Torrent
Exception in test_indexer
..................................................................................................................
Using Jackett Version 0.7.1389.0 on synology 5.2..
Using Mono Beta Version 4.6.2.7-8

**Comment by kaso17** [comment]
works for me, please provide more details

**Comment by VadVoci** [comment]
"Test failed for utorrents: Found no results while trying to browse this tracker"
