### ISSUE TITLE
[req]: hentaitorrents

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#13685]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: hentaitorrents
- URL: https://www.hentaitorrents.com/
- Description: hentai,2d,3d,anime, comic have 
- Minimum Seeding Time and Minimum Ratio (if Private): public
- Additional Comments:
```

**Comment by ilike2burnthing** [comment]
Took me about 5s to find content we don't want to go anywhere near. You'd also only get a title (which are sometimes broken), a poster (which are sometimes broken), and a pointless category, so it would be a waste of time using this through Jackett.
