### ISSUE TITLE
Nyaa.si shows duplicate categories

### ISSUE THREAD

**Issue by mirolm** [Jackett/Jackett#13682]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/nzbdrone/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Debian GNU/Linux 10 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.0.0 (64bit OS) (64bit process)
Environment version: 6.0.10 (/opt/jackett/)
Starting Jackett v0.20.2167
```

### Description

I noticed some categories are duplicated for the tracker. For example: Anime (140679), English subtitled animes (127720) and some other more. When i add the tracker through Jackett in Sonarr the categories show doubled there too.

### Logged Error Messages

```text
None.
```

### Screenshots

![image](https://user-images.githubusercontent.com/9135358/198131729-872065ed-2ac1-4155-b06d-6ab80836e673.png)

**Comment by ilike2burnthing** [comment]
To accommodate both TV anime and movie anime results:

https://github.com/Jackett/Jackett/blob/bf581f690ea0e4cccdb110d6955960e9c3105b8d/src/Jackett.Common/Definitions/nyaasi.yml#L78-L91
