### ISSUE TITLE
[carpt] (updating) The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject]  CN=*.carpt.net[Issuer]  CN=E1, O=Let's Encrypt, C=US[Serial Number]  04F2A346C5B7AD2564CE0607AFB6177C8A68[Not Before]  10/25/2022 1:00:09 AM[Not After]  1/23/2023 1:00:08 AM[Thumbprint]  EECCB0244722EA69FBA3A0F35F7BFE1C3D6DAB12

### ISSUE THREAD

**Issue by xjxzyzz** [Jackett/Jackett#13695]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
using HTTP client: Httplwebclient2
Using Flaresolverr: No
using proxy : Disabled
App config/log directory: /volume1/@appstore/jackett/varl.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads，1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreLinuxAmdx64
os version: Unix 4.4.59.0 (64bit os)(64bit process)
Environment version: 6.0.10 ( /volume1/@appstore/jackett/share/)starting
Jackett ve.20.2189
```

### Description

add an account

### Logged Error Messages

```text
An error occurred while updating this indexer
The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject] CN=*.carpt.net [Issuer] CN=E1, O=Let's Encrypt, C=US [Serial Number] 04F2A346C5B7AD2564CE0607AFB6177C8A68 [Not Before] 10/25/2022 1:00:09 AM [Not After] 1/23/2023 1:00:08 AM [Thumbprint] EECCB0244722EA69FBA3A0F35F7BFE1C3D6DAB12
```

**Comment by garfield69** [comment]
please open a terminal and post back here the results of the following two commands:

```
openssl s_client -connect https://carpt.net:443
```
and
```
curl -vvv https://carpt.net/
```

I don't think either openssl or curl can handle a Let's Encrypt CA of type E1, usually web sites use R3.

**Comment by garfield69** [comment]
@ilike2burnthing  is the carpt indexer working for you?

**Comment by ilike2burnthing** [comment]
Working fine here on Docker.

May need to update openssl, mono, and/or certs - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work-the-ssl-connection-could-not-be-established
