### ISSUE TITLE
[req]: New private tracker ihdbits

### ISSUE THREAD

**Issue by godchenmeng** [Jackett/Jackett#13692]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: ihdbits
- URL: https://ihdbits.me/
- Description: CHINESE Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private):  min 120 hour seeding
- Additional Comments:
```
engine NexusPHP 1.7.29 2022-10-13
note: you have to pass an exam to keep account

**Comment by garfield69** [comment]
v0.20.2186

**Comment by ilike2burnthing** [comment]
https://ihdbits.me/ - HTTP ERROR 500

**Comment by garfield69** [comment]
@godchenmeng  do you have any news about ihdbits, has the site gone, is broken, or has moved to a new domain?

**Comment by godchenmeng** [comment]
I think the site is closed。

garfield69 ***@***.***> 于2023年3月25日周六 02:05写道：

**Comment by garfield69** [comment]
v0.20.3689
