### ISSUE TITLE
[bjshare] (updating) Your cookie did not work, make sure the user agent matches your computer: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.

### ISSUE THREAD

**Issue by talesam** [Jackett/Jackett#13696]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Version ARM64: https://hub.docker.com/r/linuxserver/jackett
Jackett Version v0.20.2203
```

### Description

" An error occurred while updating this indexer
Your cookie did not work, make sure the user agent matches your computer: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings."

### Logged Error Messages

```text
" An error occurred while updating this indexer
Your cookie did not work, make sure the user agent matches your computer: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings."
```

### Screenshots

Image error

![photo_2022-11-04_20-59-00](https://user-images.githubusercontent.com/981368/200090997-e6679272-b605-4b7c-a608-be9db1579f61.jpg)

**Comment by ilike2burnthing** [comment]
Please read this comment and below - https://github.com/Jackett/Jackett/issues/12756#issuecomment-1004350715

Let us know if any of those suggestions resolved your issue.
