### ISSUE TITLE
[idope] (testing) Test search in Idope => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by khalith** [Jackett/Jackett#13702]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
An error occurred while testing this indexer
Test search in Idope => Found no results while trying to browse this tracker
```

### Description

 An error occurred while testing this indexer
Test search in Idope => Found no results while trying to browse this tracker

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in Idope => Found no results while trying to browse this tracker
```

**Comment by garfield69** [comment]
see https://github.com/Jackett/Jackett/issues/13700#issuecomment-1307680915
