### ISSUE TITLE
[PrivateHD] No results in RSS file

### ISSUE THREAD

**Issue by norey** [Jackett/Jackett#13717]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett v0.20.2247
Configured as an indexer in Sonarr
```

### Description

Sonarr was not finding a show on PrivateHD even though it is there. I extracted the URL used by sonarr and it is 

`http://jackett:9117/api/v2.0/indexers/privatehd/results/torznab/api?t=tvsearch&cat=5000,5030,5040,2000&extended=1&apikey=<api-key>&offset=0&limit=100&q=Problem%20With%20Jon%20Stewart&season=2&ep=1`

The RSS file downloaded from that URL contains:

```
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://jackett:9117/" rel="self" type="application/rss+xml" />
    <title>PrivateHD</title>
    <description>BitTorrent site for High Quality, High Definition (HD) movies and TV Shows</description>
    <link>https://privatehd.to/</link>
    <language>en-US</language>
    <category>search</category>
  </channel>
</rss>
```

Without any other results, why is that?

I tested another indexer using
`http://jackett:9117/api/v2.0/indexers/1337x/results/torznab/api?t=tvsearch&cat=5000,5040,5045&extended=1&apikey=<api-key>&offset=0&limit=100&q=The%20Problem%20With%20Jon%20Stewart&season=2&ep=1`

and it did return an RSS file with the correct results.

I made sure I have the "Enable RSS Feed" checkbox checked in the PrivateHD account.
Any idea what I might be doing wrong?

### Logged Error Messages

```text
N/A
```

**Comment by garfield69** [comment]
The Jackett PrivateHD Indexer with Sonarr is working for me.

I suggest the following:
- access your sonarr indexer and click on the categories box
- untick the tv(5000)
- tick the tv/sd(5030), tv/hd(5040) and tv/uhd(5045)
- now tick the tv(5000) 
- do not tick any of the movie cats (2000,2030,2040,2045)
- save and try your search again.

let me know how you go.

**Comment by norey** [comment]
That worked! thank you very much!

Using the param `cat=5000` is enough, no need for other categories.
