### ISSUE TITLE
mejortorrent: error in some searches

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13716]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.20.2244
Docker / Linux
```

### Description

It works for most queries but it fails with "深海 0".

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment]
paste `深海` in the web site's search box generates the URL in my previous post, so this is an issue with the web site and not jackett.

**Comment by ilike2burnthing** [comment]
I tried some Hebrew and Cryrillic, they fail too. Should we strip keywords to English alphanumeric characters only?

**Comment by ngosang** [comment]
I would like that. Keep in mind there are upercase, lowercase, number, spaces, points, dashes...

**Comment by ngosang** [comment]
Thank you both.

**Comment by ilike2burnthing** [comment]
[v0.20.2255](https://github.com/Jackett/Jackett/releases/tag/v0.20.2255)
