### ISSUE TITLE
[fuzer] (testing) Test search in Fuzer => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by ori2015** [Jackett/Jackett#13729]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Loading Native indexers ...
2022-11-19 16:16:11	Info	Using HTTP Client: HttpWebClient2
2022-11-19 16:16:11	Info	Using FlareSolverr: No
2022-11-19 16:16:11	Info	Using proxy: Disabled
2022-11-19 16:16:11	Info	App config/log directory: C:\ProgramData\Jackett
2022-11-19 16:16:11	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-11-19 16:16:11	Info	Running in Docker: No
2022-11-19 16:16:11	Info	Jackett variant: CoreWindows
2022-11-19 16:16:11	Info	OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
2022-11-19 16:16:11	Info	Environment version: 6.0.11 (C:\ProgramData\Jackett\)
2022-11-19 16:16:07	Info	Starting Jackett v0.20.2267
```

### Description

fuzer.me dont cant add 

× An error occurred while testing this indexer
Test search in Fuzer => Found no results while trying to browse this tracker
[Click here to open an issue on GitHub for this indexer.](https://github.com/Jackett/Jackett/issues/new?template=bug_report.yml&title=[fuzer]%20(testing)%20Test%20search%20in%20Fuzer%20%3D%3E%20Found%20no%20results%20while%20trying%20to%20browse%20this%20tracker)

### Logged Error Messages

```text
× An error occurred while testing this indexer
Test search in Fuzer => Found no results while trying to browse this tracker
Click here to open an issue on GitHub for this indexer.
```

**Comment by garfield69** [comment]
The indexer is working for me which suggests the issue is at your end.
Was it working before on the same device and IP, using the same DNS?
Are other indexers working?
Are you using a proxy or VPN?
Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work
IF you can't figure it out the please provide a **full Enhanced** log, perhaps that will provide a clue. See https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by ori2015** [comment]
> 
FUZER never worked for me, the other indexers worked, only he didn't
I don't use a VPN and I use the same DNS

**Comment by ori2015** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/10049201/log.txt)

**Comment by ilike2burnthing** [comment]
Please read the instructions again for providing an **ENHANCED** log.

**Comment by ori2015** [comment]
> Please read the instructions again for providing an **ENHANCED** log.

[log.txt](https://github.com/Jackett/Jackett/files/10049210/log.txt)

this ok ?

**Comment by ilike2burnthing** [comment]
No. There should be `Debug` entries and the HTML of whatever is being returned.

**Comment by ori2015** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/10049347/log.txt)

**Comment by ori2015** [comment]
> No. There should be `Debug` entries and the HTML of whatever is being returned.

ok ?
i delete the cookie

**Comment by ilike2burnthing** [comment]
Yes, that's fine.

Have you changed the layout or style for the tracker? If so, revert to the default, pull a new cookie, and test again.

**Comment by ori2015** [comment]
> Yes, that's fine.
> 
> Have you changed the layout or style for the tracker? If so, revert to the default, pull a new cookie, and test again.

I don't change the style 
In fuzer you can't change design at all

**Comment by ilike2burnthing** [comment]
Then I'll leave this one to @garfield69 as I don't have an account.

**Comment by ori2015** [comment]
> The indexer is working for me which suggests the issue is at your end.
> Was it working before on the same device and IP, using the same DNS?
> Are other indexers working?
> Are you using a proxy or VPN?
> Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work
> IF you can't figure it out the please provide a **full Enhanced** log, perhaps that will provide a clue. See https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

You can help?

**Comment by garfield69** [comment]
A quick look at the Fuzer browse.php page you provided in your log with the one I get, it is clear that you are being presented with different HTML.
I shall do some research to see if its just account settings (classic, new dark, bright new, new uniform dark) or whether its something to do with your rank, (I'm Lead your are Gold).

**Comment by ori2015** [comment]
> A quick look at the Fuzer browse.php page you provided in your log with the one I get, it is clear that you are being presented with different HTML.
> I shall do some research to see if its just account settings (classic, new dark, bright new, new uniform dark) or whether its something to do with your rank, (I'm Lead your are Gold).

Thank you very much I am waiting for the update

**Comment by garfield69** [comment]
you can make it work right now by switching your config settings on the web site to use any style other than **Classic**
or you can want for the next release of Jackett due out in about 8 hours, which will handle all styles.
the advantage of not using Classic is that you get imdb tags in results.

**Comment by ori2015** [comment]
> you can make it work right now by switching your config settings on the web site to use any style other than **Classic**
> or you can wait for the next release of Jackett due out in about 8 hours, which will handle all styles.
> the advantage of not using Classic is that you get imdb tags in results.

Where do you have the option to change design in fuzer I can't find it?

**Comment by garfield69** [comment]
https://www.fuzer.me/profile.php?do=editoptions
![image](https://user-images.githubusercontent.com/6933240/202974607-957bcc09-bba0-4e7b-9ad4-faa0832406b1.png)

**Comment by garfield69** [comment]
v0.20.2271

**Comment by ori2015** [comment]
Thank you very much it works great
