### ISSUE TITLE
[Bit-City Reloaded] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13728]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

Bit-City Reloaded is offline

### Logged Error Messages

```text
https://bc-reloaded.net/ returns 

SQL Error
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
in /home/user/www/bc-online/include/bittorrent.php, line 2670
```

**Comment by mynameisbogdan** [comment]
Seems to be up now. 👍

**Comment by garfield69** [comment]
https://bc-reloaded.net/ returns Web server is down Error code 521

**Comment by garfield69** [comment]
v0.20.2390
