### ISSUE TITLE
error for cache 

### ISSUE THREAD

**Issue by makergit365** [Jackett/Jackett#13738]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
docker
Jackett Version v0.20.2285
```

### Description

原谅我英文很差，我不知道你通过浏览器的翻译能不能看懂。由于某种原因，使rarbg出现错误而返回空值。但这不重要。重要的是这个搜索结果被写入缓存，重新尝试搜索这个关键词时会直接调用缓存的错误结果，这样就不能重新从rarbg重新获取结果。

Forgive me for my poor English. I don't know if you can understand it through the browser translation. For some reason, the error of rarbg returns null. But it doesn't matter. The important thing is that the search results are written into the cache. When you try to search the keyword again, the cached error results will be called directly, so that you cannot retrieve the results from the rarbg again.

### Logged Error Messages

```text
11-25 01:01:42 Info Manual search in RARBG for Black.Adam => Found 31 releases 

11-25 01:01:54 Info Manual search in RARBG for Black.Adam => Found 8 releases 

11-25 01:02:28 Info Manual search in RARBG for The Peripheral => Found 0 releases 

11-25 01:02:33 Warn torrentapi.org returned code 20 with Rate Limit exceeded. Retrying after 5 secs. 

11-25 01:02:39 Warn torrentapi.org returned code 20 with Rate Limit exceeded. 

11-25 01:02:39 Info Manual search in RARBG for The Peripheral => Found 0 releases 

11-25 01:02:55 Warn torrentapi.org returned code 20 with Rate Limit exceeded. Retrying after 5 secs. 

11-25 01:03:01 Info Manual search in RARBG for The Peripheral => Found 12 releases 

11-25 01:03:18 Info Manual search in RARBG for The Peripheral => Found 0 releases (from cache) 

11-25 01:03:22 Info Manual search in RARBG for The Peripheral => Found 0 releases (from cache) 

11-25 01:03:29 Info Manual search in RARBG for The Peripheral => Found 0 releases (from cache)
```

**Comment by makergit365** [comment]
Forgive me for my poor English. I don't know if you can understand it through the browser translation. For some reason, there is an error in rarbg and the result is not retrieved. But it doesn't matter. The important thing is that the search results are written into the cache. When you try to search the keyword again, the cached error results will be called directly, so that you cannot retrieve the results from the rarbg again.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/11410#issuecomment-813570879

**Comment by makergit365** [comment]
> [#11410 (comment)](https://github.com/Jackett/Jackett/issues/11410#issuecomment-813570879)

I want to ask how long the cache expires

**Comment by garfield69** [comment]
>I want to ask how long the cache expires

you control how long the Jackett cache remembers an indexers previously found torrents, and how many of them to keep in cache.
the settings are shown on the Jackett dashboard.
the default cache TTL is 2100 seconds, and the default number of torrents kept per indexer  is 1000, but you can changes these values to suit your needs and indeed turn caching completely off is necessary.

**Comment by makergit365** [comment]
> > I want to ask how long the cache expires
> 
> you control how long the Jackett cache remembers an indexers previously found torrents, and how many of them to keep in cache. the settings are shown on the Jackett dashboard. the default cache TTL is 2100 seconds, and the default number of torrents kept per indexer is 1000, but you can changes these values to suit your needs and indeed turn caching completely off is necessary.

Thank you for your help. That's exactly what I need
