### ISSUE TITLE
[req]: get_iplayer as an indexer?

### ISSUE THREAD

**Issue by satozuki** [Jackett/Jackett#13735]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I was going to request it as "indexer request", but I realized that it is not a website...

### Describe the solution you'd like

[get_iplayer](https://github.com/get-iplayer/get_iplayer) is a BBC iPlayer/BBC Sounds Indexing Tool and PVR
_(basically a command line utility for downloading things from the BBC)_

It would be nice if we could add get_iplayer as an "indexer" so we can then use it as Torzanb feed or similar

### Describe alternatives you've considered

Search torrent is a possibility, but get_iplayer offers you best quality and correct subtitles.

...by the way... thank you for all your work! ;)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/General-guidelines-for-what-an-Indexer-should-aim-to-provide
