### ISSUE TITLE
[torrentleech] (updating) The SSL connection could not be established, see inner exception.: Authentication failed, see inner exception.

### ISSUE THREAD

**Issue by RossComputerGuy** [Jackett/Jackett#13732]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
OS: TrueNAS-13.0-U3.1
Proxy: yes w/ VPN (PIA over OpenVPN) via proxy (squid) and custom DNS (NextDNS)
Jackett Jail Version: 0.20.2203
```

### Description

Torrentleech fails to log in and says `The SSL connection could not be established, see inner exception.: Authentication failed, see inner exception.`. I can use `curl` and `wget` with the proxy and get a successful connection to TorrentLeech. 

### Logged Error Messages

```text
No logs printed related to TorrentLeech.
```

**Comment by ilike2burnthing** [comment]
Try without VPN, proxy, and custom DNS. If it then works, reintroduce each individually until it breaks again.

**Comment by RossComputerGuy** [comment]
I did, same results.

**Comment by ilike2burnthing** [comment]
Try just using Google or Cloudflare for your DNS.

See troubleshooting steps:
https://github.com/Jackett/Jackett/wiki/Troubleshooting/#connection-reset-by-peer-the-ssl-connection-could-not-be-established
and:
https://github.com/Jackett/Jackett/wiki/Troubleshooting/#a-connection-attempt-failed

**Comment by RossComputerGuy** [comment]
Still get the errors.

**Comment by RossComputerGuy** [comment]
Yeah, I can curl and wget in the jail. Every site I try has the same SSL errors, even Internet Archive.

**Comment by RossComputerGuy** [comment]
After looking deep through the issues, I found out it was related to the SSL certificates.

**Comment by LCzoboriek** [comment]
How did you go about fixing this? Im having the same problem
