### ISSUE TITLE
[torrentccf] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13733]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

torrentccf is offline with a cloudflare CA error

### Logged Error Messages

```text
https://et8.org/ returns SSL handshake failed Error code 525
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://et8.org/ returns cloudflare SSL handshake failed Error code 525

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://et8.org/ 502 Bad Gateway nginx

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://et8.org/ cloudflare Invalid SSL certificate Error code 526

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://et8.org/ > cloudflare Invalid SSL certificate Error code 526

**Comment by garfield69** [comment]
online
