### ISSUE TITLE
HellasHut search porblems

### ISSUE THREAD

**Issue by hon4** [Jackett/Jackett#13747]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient/HttpWebClient2
Using FlareSolverr: Disabled
Using proxy: Disabled
Running in Docker: No
Jackett variant: Latest
CoreWindows
OS version: Windows 10 (64bit)
Starting Jackett Latest
```

### Description

When i search something containing spaces ti adds "++%2B" as space but the website recognize "+" as space. So in order to get correct results i have to type it with dots "." instead of  spaces.

### Logged Error Messages

```text
nothing
```

### Screenshots

https://imgur.com/86nCyPT

**Comment by ilike2burnthing** [comment]
We're adding `+` to the start of each word, as per the search instructions for that tracker, and these are encoded as `%2B`. However, we are also adding an unnecessary space, which is causing the additional `+`s.

https://github.com/Jackett/Jackett/blob/bc1cf8fd8e10480b3806c78ae0fffcad26e695be/src/Jackett.Common/Definitions/hellashut.yml#L143

**Comment by garfield69** [comment]
v0.20.2297

**Comment by hon4** [comment]
Just remove these 3 lines and it works fine.
`keywordsfilters:
    - name: re_replace
      args: ["(\\w+)", " $1"] # prepend + to each word`

**Comment by ilike2burnthing** [comment]
It's already been fixed in v0.20.2297 - https://github.com/Jackett/Jackett/commit/784a631405f62875eb6d30b6ec64939845c6f14e

**Comment by hon4** [comment]
I restarted jackett 2-3 times and it didn't fixed so i changed it by hand.

**Comment by ilike2burnthing** [comment]
If you're using v0.20.2297, and the indexer had `"$1"` instead of `" $1"`, then the issue was fixed.

A search for `wargames 1983` will now add a `+` to the start of each word (as per the instructions of the tracker), which when URL encoded will appear as `%2Bwargames+%2B1983`, the same as when searching on the site.
