### ISSUE TITLE
Indexer intermittently disconnecting and connecting

### ISSUE THREAD

**Issue by muffinjar** [Jackett/Jackett#13746]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.2158-ls78)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
Environment version: 6.0.11 (/app/Jackett/)
Starting Jackett v0.20.2291
```

### Description

Repeated error with the indexer Nyaa:
Exception (nyaasi): Connection reset by peer: The SSL connection could not be established, see inner exception.
Currently running PiHole; however, the error persists with and without the application running. I have ensured that IPv6 is not running on any containers.
[log.txt](https://github.com/Jackett/Jackett/files/10096814/log.txt)

### Logged Error Messages

```text
Exception (nyaasi): Connection reset by peer: The SSL connection could not be established, see inner exception.
```

**Comment by garfield69** [comment]
intermittent reset by peer issues are usually caused by the web site taking too long to respond to a handshake.
try editing the nyaa.si jackett config via the jackett dashboard, and switching to one of the two alternate sitelinks and see if the problem persists with there too. 
let me know what happens.

**Comment by muffinjar** [comment]
Thanks! I'll try that out and see if it'll resolve the problem.
