### ISSUE TITLE
[req]: the uninstaller opened me a LOT of different cmd windows

### ISSUE THREAD

**Issue by Illegal-Services** [Jackett/Jackett#13743]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

No not really, just wasting time by running a wrongly codded, slow algorithm.

### Describe the solution you'd like

I propose my help if this cmd window are codded in Batch.
As I am a qualified Batch dev, I can very likely help by making this whole process way faster and better.

**Comment by ilike2burnthing** [comment]
PRs are always welcome. What are you proposing to change here? - https://github.com/Jackett/Jackett/blob/master/Installer.iss

**Comment by Illegal-Services** [comment]
I might be wrong but I believe the problem is located at:
https://github.com/Jackett/Jackett/blob/master/Installer.iss#L59

Too, I don't see why that would open many cmd consoles, those are only 2.

Also, I can help with Batch scripting and it isn't here, sadly.

**Comment by ilike2burnthing** [comment]
I only see 2 console windows flash. If you're seeing more than that, I'm not sure what would be causing that.

**Comment by Illegal-Services** [comment]
haven't investigated that myself; i just came reporting what I've seen

**Comment by Illegal-Services** [comment]
I just know that I had checked up all possible trackers in Jackett, and I'm thinking this cmd windows flash where due to uninstalling all of those one by one, this is just what I'm thinking right, I might be completely wrong about that.

**Comment by ilike2burnthing** [comment]
On uninstall I'm seeing only 1 console window flash. I would suggest having a look at folder and file permissions, and any security software which may be interfering with the installer/uninstaller.

**Comment by Illegal-Services** [comment]
Now that you mention that, I've uninstalled Jackett while I basically was doing some drives movings, so the uninstaller might have been matching some missing files or stuff like that. Again, this is a *maybe*.

**Comment by ilike2burnthing** [comment]
Feel free to reopen if you discover some actual edge case issue with our un/installer.
