### ISSUE TITLE
Application icon appears to be corrupted.

### ISSUE THREAD

**Issue by PaulCoddington** [Jackett/Jackett#13745]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
OS version: Microsoft Windows NT 10.0.22621.0 (64bit OS)
Jackett v0.20.2142
```

### Description

Application icon appears to be corrupted (both in source code project and in compiled exe files).
 • Start Menu takes a long time to resolve the icon (behaves like a timeout, presumably falls back on lower resolution).
 • Icon editor crashes when attempting to view the icon.
 
 Workaround:
 • Remove 256x256 icon from *.ico, use amended icon for Start Menu shortcut.

### Logged Error Messages

```text
n/a
```

### Screenshots

![icon](https://user-images.githubusercontent.com/20898441/204082169-c2f75a04-6747-4113-8aa1-b3b7e306ab78.png)

**Comment by ilike2burnthing** [comment]
Not having any issues here, even when navigating in Explorer with extra large icons. While I couldn't find the specific software you're using, icofx had no issues opening the icons either.

Can you provide a link to that software?

**Comment by PaulCoddington** [comment]
https://www.iconworkshop.com

**Comment by ilike2burnthing** [comment]
I can recreate your problem with that specific software. However, I'm not having issues in Explorer, and I can't recreate it with any other software.

I would suggest that the root of your issue may be the software which hasn't been updated since 2016, and whose website makes references to Windows XP and Vista, and Visual Studio 2005 and 2008.
