### ISSUE TITLE
[theshinning] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13751]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

the shinning is offline

### Logged Error Messages

https://theshinning.me/
- ERR_CONNECTION_TIMED_OUT
- ERR_NAME_NOT_RESOLVED

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://theshinning.me/ returns 
```
502 Bad Gateway
nginx/1.15.8
```

**Comment by garfield69** [comment]
looks like they are in the middle of a significant upgrade to their unit3d engine.
they were on 1.9.4 and it looks like they will be on 6.4.1 when completed which means we can switch to using the API.

**Comment by garfield69** [comment]
online. converting to theshinning-api to take advantage of unit3d 6.4.1

**Comment by garfield69** [comment]
v0.20.2360

**Comment by garfield69** [comment]
https://theshinning.me/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://theshinning.me/ > ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
v0.22.1150
