### ISSUE TITLE
Rutor indexer show wrong title

### ISSUE THREAD

**Issue by Anton111111** [Jackett/Jackett#13757]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2	
Using FlareSolverr: http://flaresolverr:8191/	
Using proxy: Disabled	
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads	
Running in Docker: Yes (image build: v0.20.1197-ls70)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxArm64
OS version: Unix 5.4.17.2102 (64bit OS) (64bit process)
Environment version: 6.0.11 (/app/Jackett/)
Starting Jackett v0.20.2318
```

### Description

Some times RuTor indexer show title with wrong season (season 0).
For example if search "the dragon prince" i get result "[The Dragon Prince -​ S0E1-​03 -​ rus -​ WEB-​DLRip -​ SDI Media, AlexFilm](http://rutor.info/torrent/708791/princ-drakon_the-dragon-prince-s01-03-2018-2019-web-dlrip-sdi-media-alexfilm)". But how you see title has seasons range. But we see season 0.
 

### Logged Error Messages

```text
no errors
```

**Comment by Anton111111** [comment]
I've updated  to v0.20.2319. Issue is still here.

**Comment by garfield69** [comment]
v0.20.2325

**Comment by Anton111111** [comment]
In version v0.20.3778 issue again happen. For example if search "Mandalorian" we will get result:
[The Mandalorian -​ S0E1-​03 -​ rus -​ WEB-​DLRip -​ LostFilm](http://rutor.info/torrent/728598/mandalorec_the-mandalorian-01-03x01-21-iz-24-2019-2023-web-dlrip-lostfilm)
