### ISSUE TITLE
How to - pass aggregate feed to Sonarr and Radarr?

### ISSUE THREAD

**Issue by TGM** [Jackett/Jackett#1375]
Hello,

How do you pass the aggregated feed to Sonarr and Radarr with the corresponding categories?

Regards,
Dan C.

**Comment by raspdealer** [comment]
Take any of your tracker feed url and replace the tracker name in the url by "all".
It should work.

**Comment by TGM** [comment]
http://example.com:9117/torznab/all
That works allright, but what about the categories?

**Comment by kaso17** [comment]
the standard cat attribute should work:
&cat=5040,5030
You probably don't want to use tracker specific categories (>=100000).

**Comment by TGM** [comment]
Yea, I was wondering about those. What are tracker specific categories used for?

**Comment by kaso17** [comment]
They're a 1:1 mapping of the corresponding tracker categories to torznab categories.
