### ISSUE TITLE
[req]: 菟丝子资源社区 (Dodder Resource Community)

### ISSUE THREAD

**Issue by bachig26** [Jackett/Jackett#13759]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: 菟丝子资源社区 (Dodder Resource Community)
- URL: https://dodder.top
- Description: Chinese Public Tracker for Softwares, Games, Adult Contents, TV Series.
- Minimum Seeding Time and Minimum Ratio (if Private): nil
- Additional Comments: nil
```

**Comment by garfield69** [comment]
v0.20.2336

**Comment by ilike2burnthing** [comment]
https://dodder.top/ - `Welcome to nginx!`
