### ISSUE TITLE
[req] ShizaProject

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13762]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: ShizaProject
- URL: https://shiza-project.com/
- Description: ShizaProject Tracker is a Public RUSSIAN tracker and release group for ANIME
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private):
- Additional Comments: 
```

**Comment by ilike2burnthing** [comment]
> Dear viewers, we are forced to address you with the most unpleasant news.
As a result of the conflict among the administration of the team, one of the administrators, the main developer, who was responsible for the entire technical part of the team, left us. It was his decision, made in a hurry, no one had any claims against him. In particular, in his competence there was a website.
The site is no longer at the disposal of Shiza's team. The developer who left us initially announced the amount for the site in 1.4 million rubles, but generously threw it off to 700 thousand rubles, which, as you understand, is still an unbearable amount for us. Installments were also offered, however, we (not having extensive knowledge in the field of website development) do not consider any of the announced costs reasonable. In our opinion, they clearly want to cash in on us.
>
> Our team itself does not disappear anywhere, we continue our activities and will look for a way to solve the problem.
We have not disappeared our telegram channel, where we pour ready-made series for viewing online, we will also upload to sibnet and to Kodik (for example, the resource animego), so look for our releases there.
Taking this opportunity, we want to announce that it would not hurt us to have a person who understands the development of sites.

https://vk.com/wall-12323082_334610?lang=en

**Comment by garfield69** [comment]
v0.20.2486

**Comment by garfield69** [comment]
Site appears unstable. when using browser I often get sent to a youtube link.
The  Jackett search seems towork, and torrent/magnets links are good, but the details link fails with ERR_FAILED.

**Comment by ilike2burnthing** [comment]
I may just be getting lucky with timing, but site is working fine for me, including details links. Checked with Uptrends as well (granted, just twice in the space of a few mins), and it had one slow checkpoint, but no issues.

**Comment by garfield69** [comment]
v0.21.916

**Comment by garfield69** [comment]
constantly getting the youtube redirect ATM. Just me?

**Comment by ilike2burnthing** [comment]
Not happening for me, and don't see any issues on Uptrends.

**Comment by garfield69** [comment]
Bloody strange. I even tried proton on Netherlands server, and hide.me on French server. Fine, I'll stop testing.

**Comment by garfield69** [comment]
the indexer is not returning results, it seems the data returned by the site does not contain any torrent data for titles.
I'll try to compare the indexer graphql form with the current one that the site is using, to see if there has been a change someplace or if it is just a case that the site no longer has torrent data (which given its history would not surprise me in the least) in which case I will put it on down label, and remove the indexer after 30d if there is no magnets forthcoming.

**Comment by garfield69** [comment]
the graphql forms are identical, so ...

**Comment by garfield69** [comment]
I tried to login just in case it would only show torrents for registered users, but despite my creds being current I cannot get past the hcaptcha which after completion simply presents the login page again without any errors
Just me?

**Comment by ilike2burnthing** [comment]
Trying to sign in I get a prompt to validate my email address, but it's one of 2 trackers that I used a temp email for, so I can't. Trying to register a new account results in `Internal server error`.

**Comment by ilike2burnthing** [comment]
Oh, the activation email for the new account came through anyway, despite the error. From a quick check I don't see any torrents for recent releases. Doing a few searches in Jackett and the site (signed in or not) does return results with torrents, so I'm guessing there's just been nothing recent.

**Comment by garfield69** [comment]
well in that case nothing to be done.

**Comment by ilike2burnthing** [comment]
They're no longer adding torrents to new releases (confirmed on Discord), just those on old releases. Remove?

**Comment by garfield69** [comment]
no .torrents or magnets, no point indexing. anyone wanting older titles will just have to use the browser.
