### ISSUE TITLE
RSS feed format for `&q=` with two queries ORed

### ISSUE THREAD

**Issue by jprokos** [Jackett/Jackett#13760]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: /Users/john/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreMacOs
OS version: Unix 12.6.1 (64bit OS) (64bit process)
Environment version: 6.0.11 (/Users/john/Applications/Jackett/)
Starting Jackett v0.20.2326
```

### Description

I looked around for a formatting guide but only found what is here in the READme. 

Using `&q=720p,1080p` I am trying to query "720p OR 1080p":

```
http://127.0.0.1:9117/api/v2.0/indexers/tag:tv/results/torznab/api?apikey=redacted&t=search&cat=5000&q=720p,1080p
```
But the result are only torrents that contain both 720p and 1080p in their filenames:

Using "+" instead of "," gives me the exact same results

**P.S.**
I found these additional Jackett RSS feed formatting options somewhere ( thinking qBittorrent site), but really don't know their function or if there are more options...

`&limit=`
`&cache=`
`&extended=`
`&offset=`

### Logged Error Messages

```text
N/A
```

**Comment by ilike2burnthing** [comment]
There is no `OR` search function for Jackett, as it will be different (if even supported) for each tracker. You'll need to just do 2 searches.

Where necessary, we will use tracker-specific formatting (e.g. prepending `+` to each word) or search settings for `AND` searching, so as to return only relevant results.

**Comment by jprokos** [comment]
Thank you for the quick response!
Where may I find more information on "tracker-specific" formatting? For example RARBG.

**Comment by ilike2burnthing** [comment]
Formatting example:

https://github.com/Jackett/Jackett/blob/784a631405f62875eb6d30b6ec64939845c6f14e/src/Jackett.Common/Definitions/3evils.yml#L103-L105

Setting example:

https://github.com/Jackett/Jackett/blob/a01c42c79f87e1bffd06247a69f9d286a415a40c/src/Jackett.Common/Definitions/nethd.yml#L84-L85

**Comment by jprokos** [comment]
Thank you for explaining it further.

One peculiarity...
`&q=1080p+WEB+x265`

Will only find files named:
> ...1080p.WEB-DL.x265...

while...
`&q=1080p+x265+WEB`

Will find files named:
```...1080p.WEB-DL.x265... ```
and
```...1080p.WEBRip.x265... ```

It seems this just has to do with the placement of the search term "WEB"  (moving it from the middle to the end of the query). But if we have two terms they can't both be at the end.

**Comment by ilike2burnthing** [comment]
Huh, appears to be a quirk of the API which does not exist on the site.

It looks like the first keyword will match the end of any relevant word, the last keyword will match the start of any relevant word, and any keywords in between are separate and distinct words.

Basically: `*man man man*`

For example:
`man 1080p x265` will match `gerMAN` and `MAN` but not `MANhunt`
`1080p x265 man` will match `MANhunt` and `MAN` but not `gerMAN`
`1080p man x265` will match `MAN` but not `gerMAN` or `MANhunt`

@rarbg is this intentional?

**Comment by rarbg** [comment]
@ilike2burnthing no that shouldnt happen
what are the api calls you are doing ?

**Comment by ilike2burnthing** [comment]
`man 1080p x265`

> https://torrentapi.org/pubapi_v2.php?token=TOKEN&format=json_extended&app_id=ttekcaJ_v0.20.2336&limit=100&ranked=0&sort=last&mode=search&search_string=man+1080p+x265&category=14%3B17%3B18%3B23%3B25%3B27%3B28%3B32%3B33%3B40%3B41%3B42%3B44%3B45%3B46%3B47%3B48%3B49%3B50%3B51%3B52%3B53%3B54

`1080p x265 man`

> https://torrentapi.org/pubapi_v2.php?token=TOKEN&format=json_extended&app_id=ttekcaJ_v0.20.2336&limit=100&ranked=0&sort=last&mode=search&search_string=1080p+x265+man&category=14%3B17%3B18%3B23%3B25%3B27%3B28%3B32%3B33%3B40%3B41%3B42%3B44%3B45%3B46%3B47%3B48%3B49%3B50%3B51%3B52%3B53%3B54

`1080p man x265`

> https://torrentapi.org/pubapi_v2.php?token=epqc1u4izn&format=json_extended&app_id=ttekcaJ_v0.20.2336&limit=100&ranked=0&sort=last&mode=search&search_string=1080p+man+x265&category=14%3B17%3B18%3B23%3B25%3B27%3B28%3B32%3B33%3B40%3B41%3B42%3B44%3B45%3B46%3B47%3B48%3B49%3B50%3B51%3B52%3B53%3B54

**Comment by rarbg** [comment]
@ilike2burnthing 
i cant change it because thats how it always worked i have no clue what it might break for someone 
its been like that since the first api - that is keyword weighting
whats important is that this "manhunt x265 1080p" and "1080p x265 manhunt" to produce the same results - and it does produce the same results

**Comment by ilike2burnthing** [comment]
A clearer example to deal with, 1 result vs 0 results by moving `man` from the start to the end:

`man forest killer x265`

> https://torrentapi.org/pubapi_v2.php?token=TOKEN&format=json_extended&app_id=ttekcaJ_v0.20.2336&limit=100&ranked=0&sort=last&mode=search&search_string=man+forest+killer+x265&category=14%3B17%3B18%3B23%3B25%3B27%3B28%3B32%3B33%3B40%3B41%3B42%3B44%3B45%3B46%3B47%3B48%3B49%3B50%3B51%3B52%3B53%3B54

```json
{
  "torrent_results": [
    {
      "title": "The.Forest.Killer.2014.GERMAN.1080p.WEBRip.x265-VXT",
      "category": "Movies/x265/1080",
      "download": "magnet:?xt=urn:btih:b30fa34e67435e983205516ae48bbbfe00bf8325&dn=The.Forest.Killer.2014.GERMAN.1080p.WEBRip.x265-VXT&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2850&tr=udp%3A%2F%2F9.rarbg.to%3A2760&tr=udp%3A%2F%2Ftracker.thinelephant.org%3A12740&tr=udp%3A%2F%2Ftracker.tallpenguin.org%3A15720",
      "seeders": 2,
      "leechers": 6,
      "size": 1502200714,
      "pubdate": "2022-12-09 04:47:10 +0000",
      "episode_info": {
        "imdb": "tt2568206",
        "tvrage": null,
        "tvdb": null,
        "themoviedb": "351982"
      },
      "ranked": 1,
      "info_page": "https://torrentapi.org/redirect_to_info.php?token=epqc1u4izn&p=2_9_3_9_4_4_6__b30fa34e67"
    }
  ]
}
```

---

`forest killer x265 man`

> https://torrentapi.org/pubapi_v2.php?token=TOKEN&format=json_extended&app_id=ttekcaJ_v0.20.2336&limit=100&ranked=0&sort=last&mode=search&search_string=forest+killer+x265+man&category=14%3B17%3B18%3B23%3B25%3B27%3B28%3B32%3B33%3B40%3B41%3B42%3B44%3B45%3B46%3B47%3B48%3B49%3B50%3B51%3B52%3B53%3B54

```json
{
  "error": "No results found",
  "error_code": 20
}
```

**Comment by rarbg** [comment]
the keyword is GERMAN not man - if someone searches for man and not german hes clearly not looking for a man

**Comment by rarbg** [comment]
@ilike2burnthing also there is OR search in the api but just 2 forwarded - i just saw your previous comment 
```
{{search 1|search 2}}
```
i think it should be formatted like that

but in general it should be : 
1. what you are searching for 
2. resolution
3. language
4. type of release - web/bluray/etc
5. codec
