### ISSUE TITLE
Unregistered torrents keep downloading

### ISSUE THREAD

**Issue by prenniee** [Jackett/Jackett#13765]
### Have you checked our Troubleshooting page for your issue?

- [x] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-12-08 18:29:41	Info	Using HTTP Client: HttpWebClient2
2022-12-08 18:29:41	Info	Using FlareSolverr: http://127.0.0.1:8191
2022-12-08 18:29:41	Info	Using proxy: Disabled
2022-12-08 18:29:41	Info	App config/log directory: C:\ProgramData\Jackett
2022-12-08 18:29:41	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-12-08 18:29:41	Info	Running in Docker: No
2022-12-08 18:29:41	Info	Jackett variant: CoreWindows
2022-12-08 18:29:41	Info	OS version: Microsoft Windows NT 10.0.22621.0 (64bit OS)
2022-12-08 18:29:41	Info	Environment version: 6.0.11 (C:\ProgramData\Jackett\)
2022-12-08 18:29:40	Info	Starting Jackett v0.20.2336
```

### Description

Since a couple of days unregistered torrents from the indexer _GAYtorrent.ru (https://www.gaytor.rent/)_ keep downloading again and again. So when I remove these torrents they are re-added with the RSS feed in qBittorrent.

When I search the GAYtorrent site, these Torrents are not even to be found...

The cache is disabled and I am using FlareSolverr and OMDB.

### Logged Error Messages

```text
No errors found in Jackett logs for this indexer
```

**Comment by ilike2burnthing** [comment]
Is GAYtorrent.ru the only indexer you're using with qBittorrent's RSS feed reader?

Are these torrents added with the GAYtorrent.ru tracker and your private passkey?

How often are these torrents downloaded?

**Comment by prenniee** [comment]
No, I am using many indexers, but currently I only have this one enabled in the RSS Downloading rules. However ALL indexers are refreshed every 15 minutes no matter if I use them or not. The torrents are added with the GAYtorrent.ru tracker and my private passkey. In Jackett I have chosen to only download freeleech torrent.

I have been using these setup for many months and I am only experiencing this since a week or so.

**Comment by ilike2burnthing** [comment]
Using only GAYtorrent.ru, enable enhanced logging and wait for the next unregistered torrent download, then provide the log for this issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by prenniee** [comment]
Should I remove all other indexers from the RSS reader so they will not be refreshed? Since I cannot disable them...
Or is it sufficient to have only Gaytorrent enabled in de downloading rules and all other disabled?

**Comment by ilike2burnthing** [comment]
To keep the logs clearer, remove everything apart from GAYtorrent.ru

**Comment by prenniee** [comment]
I've attached all log files with the relevant timeframe.

[log.txt.20221210.00007.txt](https://github.com/Jackett/Jackett/files/10200570/log.txt.20221210.00007.txt)
[log.txt.20221210.00005.txt](https://github.com/Jackett/Jackett/files/10200571/log.txt.20221210.00005.txt)
[log.txt.20221210.00006.txt](https://github.com/Jackett/Jackett/files/10200572/log.txt.20221210.00006.txt)

**Comment by ilike2burnthing** [comment]
Can you not find `Retake (2016)` on the tracker? It's definitely showing in the logs - `id=7f2a81c1a4d3191181741003ade62c6692535449cd2b5dc9`.

**Comment by prenniee** [comment]
Yes, but only with different file sizes. And when I replace the id in the URL with the id you mentioned it says: "No torrent with ID."

**Comment by ilike2burnthing** [comment]
@garfield69 as you have an account, do you get the same `no torrent with ID` error when using the above ID? Any clue why this would be happening?

**Comment by garfield69** [comment]
@ilike2burnthing  see maintainers page access to gaytorrent.ru
let me know when you are done.

**Comment by ilike2burnthing** [comment]
@garfield69 done

@prenniee as far as I can tell, it's just a case of valid torrents being removed. If you go to the above ID, the page's title is `Retake (2016)`, so at one point it was a valid torrent.

**Comment by prenniee** [comment]
Sorry for the confusion, but it seems I messed up some RSS configurations files of qBittorrent. I tried to change the API key in those RSS files, but for some reason the lines were doubled. All seems fine now.
