### ISSUE TITLE
Question: GitHub management

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#1376]
As I don't know how to contact you @JigSawFr, you can close this after or contact me at raspdealer @ protonmail . com to respond :)

Do you have a slack or discourse for Jackett?
As I'm following tickets on a daily basis, can I add labels on it to help?

Thanks :)

**Comment by kaso17** [comment]
@flightlevel raspdealer certainly would be able to help.

**Comment by flightlevel** [comment]
@raspdealer invite for GitHub sent, any help with trouble shooting issues appreciated
