### ISSUE TITLE
https://giveupgithub.org

### ISSUE THREAD

**Issue by rihaq** [Jackett/Jackett#13767]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Explained in https://giveupgithub.org 

### Describe the solution you'd like

Codeberg or sourcehut mirror

**Comment by ilike2burnthing** [comment]
While I'm not opposed to this, we currently don't have devs enough to work on Jackett itself, nevermind move it somewhere else, and all that would entail. Right now, leaving this open would be pointless, but if someone months or years from now wants to take up that task, then by all means.
