### ISSUE TITLE
[yggcookie] (testing) Test search in YGGcookie => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by imranedrissi** [Jackett/Jackett#13779]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Last jackett version
```

### Description

I think YGGtorrent and YGGcookie don't use login anymore

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in YGGcookie => Found no results while trying to browse this tracker
```

**Comment by garfield69** [comment]
The yggtorrent and yggcookie indexers are working for me.
The semi-private site still uses login, you cannot download if you do not have an account.

As for your issue, try fetching a new cookie and useragent
Read https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work for more help suggestions.

**Comment by bozoweed** [comment]
same trouble for me and nothing work

**Comment by bozoweed** [comment]
i had fresh update my cookie and header but seem not good

**Comment by bozoweed** [comment]
got the answer :) 

new link is this one 
https://www6.yggtorrent.lol/

**Comment by Thomas-Philippot** [comment]
> got the answer :)
> 
> new link is this one https://www6.yggtorrent.lol/

Thank's, I was just writing an aswer.

Can you tell me if the cookie tracker is going to expire or not ?

**Comment by bozoweed** [comment]
i don't know

**Comment by bozoweed** [comment]
personaly i have reset all the setting

**Comment by imranedrissi** [comment]
SOLUTION: The link has been changed, you must create an Indexer profile manually.  moreover, for French users, you must use a VPN or change the DNS because internet service providers block access to the site
