### ISSUE TITLE
[TorrentLeech] upcoming 2FA

### ISSUE THREAD

**Issue by austinwbest** [Jackett/Jackett#13772]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
All
```

### Description

TLDR, add a `alt2FAToken` setting to pass with the username/password fields for TL

TL is implementing 2FA options for its users. This will of course break being able to send the user/pass and login to search. Until they add a proper search API they are going to implement a new field `alt2FAToken` that will be an MD5 hash to bypass the 2FA login. So basically users will get this 2FA token from TL and add it to Jackett so it can bypass enabled 2FA user logins.

The staff is already testing the 2FA and plans are to roll it out to users in the next couple days. 

### Logged Error Messages

```text
None yet
```

**Comment by garfield69** [comment]
v0.20.3184

**Comment by bakerboy448** [comment]
@garfield69 @ilike2burnthing can we re-visit this

the OTP eventually expires and will need to be modified;  why do we not return to the original request of using the alt token?

and for posterity - the alt token in the OTP field does not work, confirmed with prowlarr today
