### ISSUE TITLE
[req]: SVG version of Jackett icon?

### ISSUE THREAD

**Issue by loganmarchione** [Jackett/Jackett#13789]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hello there! 👋

I'm the maintainer of [homelab-svg-assets](https://github.com/loganmarchione/homelab-svg-assets) and would like to add the [Jackett icon](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Content/jacket_medium.png) to my project. However, I didn't see any brand guidelines or a vector (SVG) version of the icon. I did find [this old PR](https://github.com/Jackett/Jackett/pull/9832) that was never merged.

Could you please provide one or both of these?

Thanks, and keep up the good work!

### Describe the solution you'd like

- Add SVG icon and guidelines

**Comment by ilike2burnthing** [comment]
The only SVG that I'm aware of ever existing was from that PR. The black and white version is the only original version.

As for brand guidelines, just use the image as is, unmodified, attributed to this repo, and solely to represent Jackett.
