### ISSUE TITLE
1Tamilmv

### ISSUE THREAD

**Issue by jrjaggari** [Jackett/Jackett#13782]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: 1Tamilmv
- URL: https://tamilmv.unblockit.pet/
- Description: 1Tamilmv is a tracker for Indian Movies and TV
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: Too many ads on the website
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/2421
https://github.com/Jackett/Jackett/issues/12097
