### ISSUE TITLE
[req]: 

### ISSUE THREAD

**Issue by 292818** [Jackett/Jackett#13783]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
名称：看片狂人
网址：https://www.kpkuang.org/
描述：TrackerX 是用于电影、电视和电子学习的私人 Torrent 追踪器，很好的种子
```

**Comment by ilike2burnthing** [comment]
There are three links before you get to an actual torrent file for a result, if a result even has a torrent, which you can't tell from the results page, and results have multiple torrents.

Please see https://github.com/Jackett/Jackett/wiki/General-guidelines-for-what-an-Indexer-should-aim-to-provide
