### ISSUE TITLE
[req]: 

### ISSUE THREAD

**Issue by 292818** [Jackett/Jackett#13780]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
名称：片库
网址：https://www.pkmp4.com/
描述：片库 是用于电影、电视和综艺 动漫 Torrent 追踪器  通常质量都很好


名称：哗嘀影视
网址：https://www.bdys01.com/
描述：片库 是用于电影、电视和综艺 动漫 Torrent 追踪器  通常质量都很好

名称：bt之家
网址：https://www.btbtt15.com/
描述：片库 是用于电影、电视和综艺 动漫 Torrent 追踪器  通常质量都很好
```

**Comment by garfield69** [comment]
one request per site please so we can trackthe progress of each independently

**Comment by ilike2burnthing** [comment]
bdys01 - https://github.com/Jackett/Jackett/issues/13758

pkmp4 - same problems as bdys01

btbtt15 - search doesn't appear to work for more than one word, and there are three links before you get to an actual torrent file for a result, if a result even has a torrent, which you can't tell from the results page

**Comment by 292818** [comment]
> 

那国内的影视作品应该在哪里寻找

**Comment by ilike2burnthing** [comment]
There are many available Chinese trackers - https://github.com/Jackett/Jackett/search?q=zh
