### ISSUE TITLE
[req]: [turktorrent] Turktorrent.us has missing category VIP

### ISSUE THREAD

**Issue by shubidubapp** [Jackett/Jackett#13798]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Torrentturk.us website has a "VIP" torrent category and it doesn't exist in current definitions file, I guess which is why you can't find any torrents in those categories when you search it from Jackett. 

### Describe the solution you'd like

I think its category ids are 57 and 66 ? At least those are the ID's I get when I generate a RSS Feed for those categories. I don't really know how the definitions should be in this project which is why I'm not creating a PR for a fix, but when I was playing around I added both id's to the YML file and at least I can now index the torrent in those categories.

![image](https://user-images.githubusercontent.com/16193640/208954137-251313aa-83d1-442c-a2c6-77e354273008.png)

As for as I can see this category is supposed to have TV, Movie, Software etc. all kinds of content. As a temporary fix I have added the categories as TV I don't know what it is supposed to be.

**Comment by shubidubapp** [comment]
As an extra information this is how the category looks in the website itself:

![image](https://user-images.githubusercontent.com/16193640/208955258-b80368d3-f207-4db1-9220-d45bb14ae707.png)

And the top (outer) "VIP" has the ID value: 57 and the bottom (inner) one is 66.

**Comment by garfield69** [comment]
As a non-vip user I do not see these categories on my torrents list which is why we have not added these up to now.
As the VIP content is multi media, I will add 57 and 66 as `Other` which is what we have done for other indexers in the past that have VIP content of this sort.

**Comment by garfield69** [comment]
v0.20.2417
