### ISSUE TITLE
Kinozal indexer returns invalid torrent file specified

### ISSUE THREAD

**Issue by MrJosu** [Jackett/Jackett#13803]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-12-22 19:27:30	Info	
Using HTTP Client: HttpWebClient2
2022-12-22 19:27:30	Info	
Using FlareSolverr: http://192.168.0.78:8191
2022-12-22 19:27:30	Info	
Using proxy: Disabled
2022-12-22 19:27:30	Info	
App config/log directory: /config/Jackett
2022-12-22 19:27:30	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-12-22 19:27:30	Info	
Running in Docker: Yes (image build: v0.20.2409-ls87)
2022-12-22 19:27:30	Info	
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-12-22 19:27:30	Info	
Jackett variant: CoreLinuxAmdx64
2022-12-22 19:27:30	Info	
OS version: Unix 5.19.14.0 (64bit OS) (64bit process)
2022-12-22 19:27:30	Info	
Environment version: 6.0.12 (/app/Jackett/)
2022-12-22 19:27:30	Info	
Starting Jackett v0.20.2417
```

### Description

When I am trying to download something using kinozal.tv or kinozal-guru.appspot.com or kinozal.guru I am getting an error - invalid torrent file specified. 
Credentials are correct
When I am trying to download via jackett - nothing happening.

### Logged Error Messages

```text
Invalid torrent file specified in sonarr
```

**Comment by ilike2burnthing** [comment]
Reconfigure the indexer to use `https://kinozal.tv/` and re-enter your credentials manually, leaving the `SID` field blank. Click `Okay`, perform a search, and try downloading again.

If the issue continues, please provide an enhanced log of the failed download - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
