### ISSUE TITLE
"Rejected a request to XSpeeds which is unconfigured"

### ISSUE THREAD

**Issue by kanelee** [Jackett/Jackett#1381]
I am using Mono Version 4.8.1 and Jackett Version and latest version of Jackett

https://pastebin.com/qc3anc9P

**Comment by kaso17** [comment]
Works for me, are other HTTPS trackers working?

You might have to import the certificates:
```
wget https://curl.haxx.se/ca/cacert.pem
cert-sync cacert.pem
```

**Comment by kanelee** [comment]
Thank you very much! Works like a charm now!
