### ISSUE TITLE
Add Locales

### ISSUE THREAD

**Issue by Machou** [Jackett/Jackett#13812]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hello,

I've been using Jackett for some time now, but I prefer to use software in my native language.

Could you add a file to be able to translate Jackett in different languages?

### Describe the solution you'd like

Add locales files to translate.

**Comment by garfield69** [comment]
closing as a duplicate fo #13262
