### ISSUE TITLE
[1337x] (testing) Exception (1337x): certificate validation failed: [Subject]  CN=blocked.t-mobilethuis.nl, O=T-Mobile Netherlands B.V., L=Den Haag, S=Zuid-Holland, C=NL[Issuer]  CN=DigiCert TLS RSA SHA256 2020 CA1, O=DigiCert Inc, C=US[Serial Number]  0AEA61784B07A7464E2DE6B47E3CBC72[Not Before]  12/12/2022 12:00:00 AM[Not After]  12/21/2023 11:59:59 PM[Thumbprint]  F552C077B76197B5863490E7D14EFAA740F31985: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by magmoot75** [Jackett/Jackett#13829]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
ik
```

### Description

ik

### Logged Error Messages

```text
ik
```

### Screenshots

![Schermafbeelding_20230102_152528](https://user-images.githubusercontent.com/121810639/210244351-d974ca27-d346-4e80-9796-782b4fb72712.png)

**Comment by ilike2burnthing** [comment]
ISP block. Use one of the alternative sitelinks, a proxy, or VPN.
