### ISSUE TITLE
Most of the results don't provide magnetic link despite this is available from the target (indexer) page.

### ISSUE THREAD

**Issue by wellloaded** [Jackett/Jackett#13823]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-12-29 16:34:20 	Info 	

Using HTTP Client: HttpWebClient2

2022-12-29 16:34:20 	Info 	

Using FlareSolverr: No

2022-12-29 16:34:20 	Info 	

Using proxy: Disabled

2022-12-29 16:34:20 	Info 	

App config/log directory: C:\ProgramData\Jackett

2022-12-29 16:34:20 	Info 	

ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads

2022-12-29 16:34:20 	Info 	

Running in Docker: No

2022-12-29 16:34:20 	Info 	

Jackett variant: CoreWindows

2022-12-29 16:34:20 	Info 	

OS version: Microsoft Windows NT 10.0.22000.0 (64bit OS)

2022-12-29 16:34:20 	Info 	

Environment version: 6.0.12 (C:\ProgramData\Jackett\)

2022-12-29 16:34:18 	Info 	

Starting Jackett v0.20.2451
```

### Description

As per title.

When I run a search I always look for the little magnet. To my surprise I find very few results with the magnet available, however opening the torrent destination page the magnet link is available from there.

On example is while using kickasstorrents.to but this applies to many other indexers.

Is this a bug? Magnet is definitely the way forward for security and practicality reason.

Thanks

### Logged Error Messages

```text
2022-12-29 16:31:41 	Info 	

Manual search in AvistaZ, CinemaZ, RARBG, 1337x, BitSearch, BT4G, EliteTorrent.biz, EXT Torrents, IBit, Isohunt2, iTorrent, kickasstorrents.to, The Pirate Bay, Torrent Downloads, TorrentFunk, YTS for gone with the wind => Found 373 releases
```

### Screenshots

![image](https://user-images.githubusercontent.com/46318040/209960992-8d1f6206-2478-4655-a1d0-96d078553a73.png)

**Comment by ilike2burnthing** [comment]
torrentfunk is amending the details link to create the torrent link, to save having to access the details page:

https://github.com/Jackett/Jackett/blob/cc6acd8efb0b56e7b2790c5a0dd93f272ebe02c5/src/Jackett.Common/Definitions/torrentfunk.yml#L84-L94

ibit is getting the infohash from the details page, so Jackett is unaware if it's a torrent or a magnet, and therefore defaults to the download icon:

https://github.com/Jackett/Jackett/blob/cc6acd8efb0b56e7b2790c5a0dd93f272ebe02c5/src/Jackett.Common/Definitions/ibit.yml#L51-L64

similarly, kickass gets the magnet link from the details page:

https://github.com/Jackett/Jackett/blob/cc6acd8efb0b56e7b2790c5a0dd93f272ebe02c5/src/Jackett.Common/Definitions/kickasstorrents-to.yml#L54-L57

and isohunt2:

https://github.com/Jackett/Jackett/blob/cc6acd8efb0b56e7b2790c5a0dd93f272ebe02c5/src/Jackett.Common/Definitions/isohunt2.yml#L60-L66

and torrentdownloads gets both the torrent and magnet link from the details page:

https://github.com/Jackett/Jackett/blob/cc6acd8efb0b56e7b2790c5a0dd93f272ebe02c5/src/Jackett.Common/Definitions/torrentdownloads.yml#L57-L82

So apart from torrentfunk, you're getting the magnet (unless torrentdownloads has been configured to try itorrents.org first.
