### ISSUE TITLE
[The Pirate Bay] using season variable returns 0 results for some shows

### ISSUE THREAD

**Issue by MathyEM** [Jackett/Jackett#13830]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Running in Docker: Yes - on RPi 4
Jackett Version v0.20.2319
```

### Description

Using sonarr, I am monitoring "Will and Grace" and currently trying to get some of the earlier seasons, but when I do a manual or interactive search it doesn't return any results from TPB. I have checked my debug log and it's making the following query: `http://192.168.87.117:9117/api/v2.0/indexers/thepiratebay/results/torznab/api?t=tvsearch&cat=5000,5040,5050,100205,100208&extended=1&apikey=(removed)&offset=0&limit=100&q=Will%20and%20Grace&season=4`

I have then tried removing the `season` variable which returns the expected results - season 1, 2, 3 and 4 are available. Searching specifically for `season=11` or `season=9` actually does return a relevant result. It seems like it might be an issue for some specific uploads.

Any workarounds for this issue?

### Logged Error Messages

```text
Not relevant
```

**Comment by ilike2burnthing** [comment]
Because there are no torrents on TPB which follow the naming scheme `Will and Grace SXX` except for `S09` and `S11`.

**Comment by MathyEM** [comment]
They are there as `Will and Grace Season x` and that's not an accepted naming scheme? Seems like it wouldn't hurt if it was.

**Comment by ilike2burnthing** [comment]
You'll have to do a manual search to get those, as `season=XX` is always `SXX`, only changing when a tracker's language requires it. We won't be doubling every season search request to use both `SXX` and `Season XX` just because an uploader is incapable of adhering to accepted standards.
