### ISSUE TITLE
Implementing uakino.club indexer

### ISSUE THREAD

**Issue by furang** [Jackett/Jackett#13833]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: UA Kino
- URL: https://uakino.club
- Description: Not So popular UA tracker
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments:
```

**Comment by garfield69** [comment]
not suitable for indexing with jackett.
see https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
