### ISSUE TITLE
Nyaa.pantsu not parsing torrent info

### ISSUE THREAD

**Issue by GiowGiow** [Jackett/Jackett#1383]
Nyaa.pantsu indexer is not parsing torrent-info correctly and because of that, the seeder/leechers counts are not being passed on to Sonarr/Radarr, that leads to the torrents not being grabbed because of their seed count being 0

Jackett Version: 0.7.1411.0 
Windows version: Windows 10
Logs: https://pastebin.com/p2sqhdHW

**Comment by tyler274** [comment]
please also add movie / tv support for nyaa pantsu, nyaa si, and bakabt.

currently i cannot add them as indexers to radarr because they don't define the correct categories in jackett.
