### ISSUE TITLE
EliteTorrent download links are not working

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13846]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett v0.20.2495
Linux / Docker
```

### Description

EliteTorrent download links are not working

### Logged Error Messages

```text
Error downloading. indexer: elitetorrent-biz path: https://www.elitetorrent.com/peliculas/trol/
System.Exception: Download selectors didn't match
   at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1903
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97
```

**Comment by ngosang** [comment]
They are protecting the URLs with something but I'm not able to download anything in the browser...

**Comment by ilike2burnthing** [comment]
They seem to have gone the way of another Spanish public tracker we removed a while ago - download links send you to a 'click here' page, then loads a fake news article or blog, which presumably drops a cookie that allows you to download. (uBlock Origin breaks all this)

I don't see a way to get around this or any infohash that we could use. Probably best to just remove.

**Comment by garfield69** [comment]
I will.
