### ISSUE TITLE
[req]: Hide tray menu on clicking outside of it

### ISSUE THREAD

**Issue by adem4ik** [Jackett/Jackett#13842]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

OS: Windows 10 x64
Version: v0.20.2489

1. Start Jackett
2. Perform right mouse click over the tray icon
3. Try to click somewhere outside of the tray menu

Result: nothing happens

### Describe the solution you'd like

Tray menu should be hidden

**Comment by garfield69** [comment]
Works for me. I'm on win10. What are you on?
Are the other systray apps working for you?
