### ISSUE TITLE
Rutor: torrent download links are not working

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13848]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett v0.20.2495
Linux / Docker
```

### Description

Only magnet links are working

### Logged Error Messages

```text
Error downloading. indexer: rutor path: http://new-rutor.org/parse/d.rutor.org/download/904095
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97
```

**Comment by garfield69** [comment]
rutor .torrent downloads are working for me. I'm using the `http://rutor.info/` domain.
you may need to enable enhanced logging to dig deeper.

**Comment by ngosang** [comment]
I can not use that domain in my country.

* http://new-rutor.org/

```
Error downloading. indexer: rutor path: http://new-rutor.org/parse/d.rutor.org/download/904171
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
```

* https://rutor.nocensor.lol/

```
Error downloading. indexer: rutor path: http://d.rutor.nocensor.lol/download/904171
System.Net.Http.HttpRequestException: Name or service not known (d.rutor.nocensor.lol:80)
```

**Comment by ilike2burnthing** [comment]
Confirmed. *.info and *.is work fine, new-*.org has an intermediate download page (breaking the indexer), and the nocensor proxy breaks when the d.* subdomain is used (that happened with some other tracker as well).

Options:
1. remove torrent download option
2. remove the non-functional mirror and proxy
3. add a note to the indexer that torrent file downloads only work with *.info and *.is

**Comment by garfield69** [comment]
I vote to go magnet only.
