### ISSUE TITLE
acgsou does not return results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13844]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett v0.20.2495
Linux / Docker
```

### Description

acgsou does not return results. there is not error in jackett but the website is working fine for me.

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment]
work for me on either of the two domains.
you may need to turn on enhanced logging to dig deeper.

**Comment by ngosang** [comment]
I'm blocked by Cloudflare but just in Jacket. Since is working for you I'm closing.
```
<h1>Access denied</h1>
<span class="cf-code-label">Error code <span>1020</span></span>
</div>
<div class="cf-error-description">
<p>You do not have access to www.36dm.club.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>

```
