### ISSUE TITLE
[req]: Do not open Web UI on right mouse click over the tray icon

### ISSUE THREAD

**Issue by adem4ik** [Jackett/Jackett#13841]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Version: v0.20.2489

1. Start Jackett
2. Perform right mouse click over the tray icon

Result: Web UI and tray menu are shown at the same time.

It seems strange for me. Afaik it worked differently before that change https://github.com/Jackett/Jackett/pull/13674

### Describe the solution you'd like

Do not open Web UI on right mouse click over the tray icon

**Comment by garfield69** [comment]
This does not happen to me.
Given your issue #13842 perhaps this is related to your issue.

**Comment by ilike2burnthing** [comment]
I can only recreate this (and sometimes https://github.com/Jackett/Jackett/issues/13842) when double right-clicking the tray icon. Single right-clicking behaves normally.

If you aren't knowingly double right-clicking, I'd suggest trying a different mouse and/or computer, a VM, and reinstalling any drivers or software for your mouse.

**Comment by garfield69** [comment]
or replace your mouse, the internal mouse buttons may be worn out.

**Comment by adem4ik** [comment]
I didn't use Jackett that much before, so I've tested it for this week:

- It is not related to my mouse for sure. Issue can't be reproduced in any other systray app.
- The right mouse click action works inconsistently. i.e. it may work as expected after fresh Jackett start, but after a while (5-10 minutes) it starts to work as explained in the starting post.
- This issue and https://github.com/Jackett/Jackett/issues/13842 are connected.

So if it's not related to the Jackett itself, it may be related to my Windows 10 x64 installation.

**Comment by ilike2burnthing** [comment]
Tested for the last half an hour. I can replicate https://github.com/Jackett/Jackett/issues/13842 with a single-click if I do so with the start menu currently open. However, I also get the same behaviour with my antivirus.

This seems to be a wider issue (Windows? dotNET?) and so can't be fixed by Jackett.
