### ISSUE TITLE
Review dead links

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13855]
- [x] acgrip  ||  https://acg.rip/  ||  HTTPSConnectionPool(host='acg.rip', port=443): Read timed out. (read timeout=60)
- [x] anidub  ||  https://tr.anidub.com/  ||  Bad HTTP response code: 404
- [x] borgzelle  ||  https://borgzelle.borg/  ||  Bad HTTP response code: 404
- [x] btsow  ||  https://btos.pw/  ||  Bad HTTP response code: 302
- [x] byrbt  ||  https://byr.pt/  ||  Bad HTTP response code: 404
- [x] cpasbien  ||  https://cpasbiens3.fr/  ||  Bad HTTP response code: 403
- [x] exttorrents  ||  https://site.extto.com/  ||  Bad HTTP response code: 301
- [x] exttorrents  ||  https://ext.torrentbay.to/  ||  Bad HTTP response code: 301
- [x] fouducinema  ||  https://fou-du-cinema.ca/  ||  Bad HTTP response code: 404
- [x] glodls  ||  https://glodls.unblockninja.com/  ||  Bad HTTP response code: 301
- [x] hdonly  ||  https://hd-only.org/  ||  Bad HTTP response code: 500
- [x] hdhome  ||  https://hdhome.org/  ||  Bad HTTP response code: 302
- [x] hdtorrentsit  ||  https://hdtorrents.xyz/  ||  Bad HTTP response code: 404
- [x] hdzone  ||  https://hdzone.me/  ||  Bad HTTP response code: 302
- [x] kinozal  ||  https://kinozal.guru/  ||  Bad HTTP response code: 302
- [x] lastfiles  ||  http://www.lastfiles.ro/  ||  Bad HTTP response code: 301
- [x] learnflakes  ||  https://learnflakes.net/  ||  HTTPSConnectionPool(host='learnflakes.net', port=443): Read timed out. (read timeout=60)
- [x] opencd  ||  https://open.cd/  ||  Bad HTTP response code: 302
- [x] polishsource  ||  https://polishsource.cz/  ||  Bad HTTP response code: 404
- [x] pornotor  ||  http://pornotor.org/  ||  Bad HTTP response code: 404
- [x] potuk  ||  https://www.potuk.net/  ||  Bad HTTP response code: 403
- [x] purovicio  ||  https://purovicio.in/  ||  HTTPSConnectionPool(host='purovicio.in', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd0f62bf190>, 'Connection to purovicio.in timed out. (connect timeout=60)'))
- [x] putao  ||  https://pt.sjtu.edu.cn/  ||  Bad HTTP response code: 302
- [x] satclubbing  ||  https://satclubbing.club/  ||  HTTPSConnectionPool(host='satclubbing.club', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0f6361960>: Failed to establish a new connection: [Errno 111] Connection refused'))
- [x] scenepalace  ||  https://scenepalace.info/  ||  Bad HTTP response code: 404
- [x] selezen  ||  https://www.selezen.net/  ||  Bad HTTP response code: 301
- [x] sukebeinyaasi  ||  https://sukebei.nyaa.lol/  ||  Bad HTTP response code: 302
- [x] swarmazon  ||  https://swarmazon.club/  ||  Bad HTTP response code: 302
- [x] swarmazon-api  ||  https://swarmazon.club/  ||  Bad HTTP response code: 302
- [x] thepiratebay  ||  https://tpb24.ukpass.co/  ||  Bad HTTP response code: 301
- [x] thepiratebay  ||  https://thepiratebay.d4.re/  ||  HTTPSConnectionPool(host='thepiratebay.d4.re', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd0f6361750>, 'Connection to thepiratebay.d4.re timed out. (connect timeout=60)'))
- [x] thepiratebay  ||  https://pirate-proxy.page/  ||  Bad HTTP response code: 301
- [x] thepiratebay  ||  https://5mins.shop/  ||  HTTPSConnectionPool(host='5mins.shop', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd0f6361300>, 'Connection to 5mins.shop timed out. (connect timeout=60)'))
- [x] thepiratebay  ||  https://tpb.surf/  ||  Bad HTTP response code: 301
- [x] thepiratebay  ||  https://tpb.monster/  ||  Bad HTTP response code: 302
- [x] torrent9  ||  https://www.torrent9.gg/  ||  Bad HTTP response code: 301
- [x] torrentbytes  ||  https://www.torrentbytes.net/  ||  HTTPSConnectionPool(host='www.torrentbytes.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:997)')))
- [x] torrentccf  ||  https://et8.org/  ||  HTTPSConnectionPool(host='et8.org', port=443): Read timed out. (read timeout=60)
- [x] torrentqq  ||  https://torrentqq215.com/  ||  Bad HTTP response code: 404
- [x] torrentseeds-api  ||  https://torrentseeds.org/  ||  Bad HTTP response code: 502
- [x] torrentsir  ||  https://torrentsir46.com/  ||  HTTPSConnectionPool(host='torrentsir46.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd0f62bd330>, 'Connection to torrentsir46.com timed out. (connect timeout=60)'))
- [x] torrentview  ||  https://torrentview25.com/  ||  HTTPSConnectionPool(host='torrentview25.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd0f6362200>, 'Connection to torrentview25.com timed out. (connect timeout=60)'))
- [x] wdt  ||  http://ultimatewrestlingtorrents.com/  ||  HTTPConnectionPool(host='ultimatewrestlingtorrents.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd0f6362c80>, 'Connection to ultimatewrestlingtorrents.com timed out. (connect timeout=60)'))
- [x] woot  ||  https://mywoot.biz/  ||  Bad HTTP response code: 301

**Comment by ilike2burnthing** [comment]
unblockit proxies need updated from .pet to .ink, so just removed them from above.

**Comment by garfield69** [comment]
I'll do the unblockit update. they changed domains a day early ;-)
Yes, byr.pt works for me.

**Comment by skillix** [comment]
hello, fouducinema || https://fou-du-cinema.ca/ is now https://les-cinephiles.nl/

**Comment by garfield69** [comment]
@skillix  we will. add les-cinephiles as a new indexer since it is a completely new site with no account carryover from fou-du-cinema. #13909
