### ISSUE TITLE
Manual Searches in Sonarr have no results

### ISSUE THREAD

**Issue by TheWhiteHunter** [Jackett/Jackett#1385]
So I'm new to Jackett. I've got it installed on Windows 10 as a service, alongside Sonarr, and I'm just not sure if it's working correctly in certain scenarios. Mainly, manual anime searches for episodes done through Sonarr.

I've got AnimeBytes, Nyaa.si, and EZTV set up in both Jacket and Sonarr and all tests say they're all functioning properly.

Now, Sonarr has been able to automatically download all the anime episodes fine from the Jackett sources I have it set up with, it's just that when I do a manual search for an episode, there are never any results from Animebytes or Nyaa.

I tested a manual search for a US show to see if any episodes from EZTV would pop up and they did, so that dismissed my thought that it was just how Jackett worked.

I ran manual searches in Jackett directly for anime and it's working there, so I'm just wondering if this is how it's supposed to work, or if there's something further I need to do in order to have anime search results show in manual searches in Sonarr?

I did search the issues for "sonarr search" and came across #1329 and #1164. I'm not sure if they're relevant to my issue though.

**Comment by raspdealer** [comment]
Hi @TheWhiteHunter ,

Can you please provide an example?

Thanks

**Comment by kaso17** [comment]
Which categories did you specify on sonarr (only shown when advanced settings are enabled). most likely you're missing TV/Anime.

**Comment by TheWhiteHunter** [comment]
Thanks kaso, I seem to have overlooked the advanced settings and have added the 5070 category for the AnimeBytes, Horrible Subs, and Nyaa.si indexers.

I'm getting search results from Nyaa.si and Horrible Subs now, but the results all show that they have zero peers. Also all the file sizes for Horibble Subs seem to show 500.0 MB, regardless of the actual file size.

![recrea](https://cloud.githubusercontent.com/assets/16769601/26120782/24accd82-3a2f-11e7-9b45-1ab0cc05350a.PNG)


AnimeBytes is working fine, albeit showing far more search results than necessary but I assume that's just due to the way search is handled on AnimeBytes.

**Comment by CodeMonkey626** [comment]
@TheWhiteHunter Nyaa.si wasn't showing seeder/leecher counts on their site for about 24 hours because of an an issue between the site and their tracker software. That has now been resolved.

HorribleSubs doesn't show this data because the underlying site doesn't provide it (Ex: http://horriblesubs.info/lib/search.php?value=Re-Creators).
