### ISSUE TITLE
[demonoid] (testing) Test search in Demonoid => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by duramato** [Jackett/Jackett#13878]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.1.55:8191/
Using proxy: Disabled
App config/log directory: /home/jackett/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 
Running in Docker: No
File /etc/issue: Debian GNU/Linux 9 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.9.0.19 (64bit OS) (64bit process)
Environment version: 6.0.12 (/home/jackett/Jackett/)
Starting Jackett v0.20.2495
```

### Description

When trying to test my already configured Demonoid it errors out, showing the attached log messages.

### Logged Error Messages

```text
https://gist.github.com/duramato/88d074d1d96fd4a0cf2500dffb28a332
```

**Comment by garfield69** [comment]
Before I dig much deeper into this, the first thing for you to check is to login to the demonoid webside, access your account settings, and double check your Theme is set to **Demonoid -v5 (New)**

it is common for this to be mysteriously reset back to Demonoid - v3 , which the Jackett indexer does no support.
Are you on Theme v5?

**Comment by duramato** [comment]
It was back on v3. Changing it to v5 made it work again.

It'd be good if Jackett could detect if it's on the correct theme, somehow.
