### ISSUE TITLE
[REQ] New Tracker – Torrent Downloads

### ISSUE THREAD

**Issue by zero77** [Jackett/Jackett#1387]
This tracker has been added but there’s a problem: #1629

Can you please add support for https://torrentdownloads.cc.
thanks.

Tracker Name : Torrent Download
Type : Movie, TV, XXX, Games, Music, Software, Anime, Books and Other
Public tracker.
Indexer URL : https://torrentdownloads.cc
Indexer language : English

**Comment by raspdealer** [comment]
Hi @zero77, do you have an invit to provide?

**Comment by zero77** [comment]
No, there's no invite needed.

**Comment by raspdealer** [comment]
Members Registration is closed at the moment

**Comment by zero77** [comment]
It's the same as RARBG where you can't sign up but you can download without an account.

**Comment by zero77** [comment]
This tracker has been added but there’s a problem: #1629

**Comment by kaso17** [comment]
dupe of #1559, added via #1563
