### ISSUE TITLE
YGG Torrent - An error occurred while updating this indexer The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by WaffleBoyQc** [Jackett/Jackett#13888]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
I am using on docker. 
Version on FlareSolverr 3.0.2
Portainer version : 2.16.2
```

### Description

Here is my configuration of stack for running seedbox on portainer.
`---
version: '2.4'
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    environment:
      - PUID=0
      - PGID=0
      - VPNSP=private internet access
      - REGION=CA Montreal
      - OPENVPN_USER=p3690944
      - OPENVPN_PASSWORD=3JF3ukVxxB
    volumes:
      - /svr/seedbox/Configs/Gluetun/Config:/gluetun
    ports:
      - 9080:9080 #QBitTorrent Web-UI
      - 6881:6881 #QBitTorrent
      - 6881:6881/udp #QBitTorrent
      - 9117:9117 #Jackett
      - 7878:7878 #Radarr
      - 8989:8989 #Sonarr

    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
      - UMASK=022
      - WEBUI_PORT=9080
    volumes:
      - /svr/seedbox/Configs/qbittorrent/config:/config
      - /mnt/media/Torrents:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    network_mode: "service:gluetun"
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
      - AUTO_UPDATE=true #optional
    volumes:
      - /svr/seedbox/Configs/Jackett/Config:/config
      - /mnt/media/Torrents:/downloads
 
    restart: unless-stopped
  
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /svr/seedbox/Configs/Radarr/config:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/Torrents:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /svr/seedbox/Configs/Sonarr/config:/config
      - /mnt/media/TV:/tv
      - /mnt/media/Torrents:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped
    
  flaresolver:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolver
    environment:
      - PUID=0 # remplacer 1000 par l'ID de l'utilisateur souhaité
      - PGID=0 # remplacer 1000 par l'ID du groupe souhaité
      - TZ=America/New_York # remplacer Europe/Paris par le fuseau horaire souhaité
    volumes:
      - /svr/seedbox/Configs/FlareSolver/config:/config # spécifiez le chemin vers le dossier de configuration de FlareSolver sur votre ordinateur
      - /mnt/media/Torrents:/downloads # spécifiez le chemin vers le dossier de téléchargement de torrents sur votre ordinateur
      
    ports:
      - 8191:8191

    restart: unless-stopped
    

    
  emby:
    image: emby/embyserver
    container_name: emby
    environment:
      - PUID=1000 # remplacer 1000 par l'ID de l'utilisateur souhaité
      - PGID=1000 # remplacer 1000 par l'ID du groupe souhaité
      - TZ=America/New_York # remplacer Europe/Paris par le fuseau horaire souhaité
    volumes:
      - /svr/seedbox/Configs/Emby/config:/config # spécifiez le chemin vers le dossier de configuration d'Emby sur votre ordinateur
      - /mnt/media/Movies:/movies # spécifiez le chemin vers le dossier de films sur votre ordinateur
      - /mnt/media/TV:/tv # spécifiez le chemin vers le dossier de séries télévisées sur votre ordinateur
      - /mnt/media/Music:/music # spécifiez le chemin vers le dossier de musique sur votre ordinateur
    ports:
      - 8096:8096 # port d'accès à l'interface web d'Emby
      - 8920:8920 # port de streaming d'Emby
    restart: unless-stopped
    `
    The issue on my Flaresolver is they are conneting and detected on Jaccket. 
    But once i valided my user name and password Jaccket send me that error. 
    `An error occurred while updating this indexer
The cookies provided by FlareSolverr are not valid`

But when i check on logs into docker. 
I have this message and no errors logs. 

`2023-01-08 17:06:07 INFO     172.22.0.3 POST http://172.22.0.4:8191/v1 200 OK
2023-01-08 17:06:15 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://www6.yggtorrent.lol/'}
2023-01-08 17:06:17 INFO     Challenge detected. Title found: Just a moment...
2023-01-08 17:06:19 INFO     Challenge solved!
2023-01-08 17:06:19 INFO     Response in 3.757 s
2023-01-08 17:06:19 INFO     172.22.0.3 POST http://172.22.0.4:8191/v1 200 OK`

Now i am confuse

### Logged Error Messages

```text
An error occurred while updating this indexer
The cookies provided by FlareSolverr are not valid
```

### Screenshots

No scrennshot

**Comment by WaffleBoyQc** [comment]
It was not on same netwok sorry solved ! :D

**Comment by ilike2burnthing** [comment]
If that's your real PIA username and password, I suggest changing them immediately.
