### ISSUE TITLE
[req]: Bit Of Valor

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13890]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Bit Of Valor
- URL: https://bitvalor.hu/
- Description: Bit of Valor is a HUNGARIAN Private Tracker for MOVIES / TV
- Minimum Seeding Time and Minimum Ratio (if Private): MST 4d
- Additional Comments:
```

**Comment by garfield69** [comment]
may not be suitable for *arr
the search engine appears to be an exact match search only, and there does not appear to be a keyword mask, AND, OR
so to find the torrent named `House.of.the.Dragon.S01.COMPLETE.WEBRip.XviD.HUN-LH44`  you need to search with ``House.of.the.Dragon.S01` with the dots and no skipped keywords in between.
I'll commit what I've got maybe someone can do better later.

**Comment by garfield69** [comment]
v0.20.2608

**Comment by garfield69** [comment]
https://bitvalor.hu/ ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://bitvalor.hu/ invalid CA plus the following response: Apache is functioning normally

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
[v0.21.1422](https://github.com/Jackett/Jackett/releases/v0.21.1422)
