### ISSUE TITLE
[req]: GainBound

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13899]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: GainBound
- URL: https://gainbound.net/
- Description: GainBound is a CHINESE Private Tracker for MOVIES especially from Hong Kong.
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: 
Registration is currently closed
```
entrance exam: UL 30GB, DL 30GB
engine: NexusPHP v1.8.0 2023-01-26

**Comment by garfield69** [comment]
v0.20.2930

**Comment by garfield69** [comment]
Bah. not sure what is going on here. My exam deadline is not due till 8th march but I am seeing
![image](https://user-images.githubusercontent.com/6933240/217701950-b0ad00c5-27b2-44b2-93dc-71490c75dc95.png)

**Comment by ilike2burnthing** [comment]
Seeing the same, with the main domain redirecting to `https://www.msn.com/nl-nl`.

**Comment by garfield69** [comment]
The site is accessible again now.

**Comment by garfield69** [comment]
https://gainbound.net/ DNS_PROBE_FINISHED_NXDOMAIN (DNS Lookup Error)

**Comment by garfield69** [comment]
v0.21.681
