### ISSUE TITLE
[req]: SharkPT

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13904]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: SharkPT
- URL: https://sharkpt.net/
- Description: SharkPT is a CHINESE Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): 7d
- Additional Comments: 
engine: NexusPHP 1.7.33 2022-12-19
Registration is currently invite only.
Entrance assessment: UL 150GB, DL 30GB, 20h seeding, 10000 coins
```

**Comment by Xeorszj** [comment]
Hello, I am a member of the management team of SharkPT, we have sent you an invitation letter, please check it; and hope you adapt to our site as soon as possible. good luck！

**Comment by garfield69** [comment]
v0.20.2904

**Comment by garfield69** [comment]
@Xeorszj  thank you for organizing the invite so that I could build the indexer for your site.
I usually only login to the account to keep the indexer up to date, and not for personal use.
Is there the possibility that I can be excused from passing the newbie exam?

**Comment by garfield69** [comment]
https://sharkpt.net/ Connection timed out Error code 522

**Comment by Xeorszj** [comment]
The service provider has an error and is shutting down for maintenance

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://sharkpt.net/ DNS_PROBE_FINISHED_NXDOMAIN (domain not found)

**Comment by Xeorszj** [comment]
https://t.me/shayupt/47
down

**Comment by garfield69** [comment]
v0.21.20

**Comment by zjjxwhh** [comment]
@garfield69 Hi, SharkPT has reopened a month and a half ago, is it possible to support SharkPT again? Thanks for your work and happy new year!

**Comment by garfield69** [comment]
>SharkPT has reopened a month and a half ago, is it possible to support SharkPT again? 

yes, no problem.

**Comment by garfield69** [comment]
v0.21.1468

**Comment by kai456789** [comment]
> v0.21.1468

 An error occurred while updating this indexer
Login failed: Selector "shark-icon-button[onclick*="logout.php"]" didn't match

**Comment by garfield69** [comment]
https://sharkpt.net/ redirects to https://www.hddolby.com/ !?!?

**Comment by garfield69** [comment]
v0.22.260
