### ISSUE TITLE
[req]: Les Cinephiles

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13909]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Les-Cinephiles
- URL: https://les-cinephiles.nl/
- Description: Les-Cinephiles is a FRENCH Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): MST 1d
- Additional Comments: 
Engine: TorrentTrader 2.08
Registration is currently open
```

**Comment by garfield69** [comment]
the site's torrent-search page has html full of errors which prevent the extracting of the category.
also, there is not flag in results to indicate if the torrent has been approved so you only find out at the download stage that the DL link in not available in the details page
front page notice does suggest the site is still a work in progress so placing ticket on hold until cats are available in results.

**Comment by garfield69** [comment]
So the site's torrent search page is a mess and I cant use the usual cat= href to fetch the category.
I could use the img[src] to tag the cats, except that the site has not got a list anyplace, so I can only tag those that are in existing 247 torrents, which means that of the 97 categories I can only positively tag 21 so far.

@ilike2burnthing  What do you reckon, do I
- [ ] hold publishing and wait until the site fixes the cat= href if ever
- [ ] publish using the img[src] , and fill in more as/when other cats get identified if ever
- [ ] go have a beer and call it a day

?

**Comment by ilike2burnthing** [comment]
This index help? https://les-cinephiles.nl/images/categories

There's 115 of them though, so there might be a bit of guesswork matching filenames to category names.

**Comment by garfield69** [comment]
Ooo, nice find. I can work with that.

**Comment by garfield69** [comment]
have about 6 cats that I cannot find a good match but that leaves 91 with a good fit so I'm calling it good.

**Comment by garfield69** [comment]
v0.20.2670

**Comment by garfield69** [comment]
https://les-cinephiles.nl/ DNS_PROBE_FINISHED_NXDOMAIN (DNS lookup error)
however uptime has 40 checkpoints that state online and only 3 that are http protocol error or tcp connection error %-/

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
>garfield1969 as usual?

yes thanks.

**Comment by ilike2burnthing** [comment]
> Hello!
For the moment it is not planned to close, just that since few uploaders are active I can not be at 2 places at the same time but we will organize this
Good day

So basically we'd need to have Les-Cinephiles and Le-Cinephile as 2 separate indexers (which we probably should anyway, given the accounts don't transfer), and then remove this one when it's finally killed off at some unknown point in the future.

**Comment by garfield69** [comment]
https://les-cinephiles.nl/ Fin de l aventure Merci a toutes et tous de ce bout de chemin merci !

**Comment by garfield69** [comment]
v0.22.600
