### ISSUE TITLE
[carpathians] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13917]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

the Carpathians site is offline

### Logged Error Messages

```text
https://mycarpathians.net/ ERR_CONNECTION_TIMED_OUT
```

**Comment by garfield69** [comment]
https://mycarpathians.net/ ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://mycarpathians.net/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online
