### ISSUE TITLE
[revolutiontt] (updating) Resource temporarily unavailable (revolutiontt.me:443): Resource temporarily unavailable

### ISSUE THREAD

**Issue by ubuntuaddicted** [Jackett/Jackett#13925]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2	
Using FlareSolverr: No	
Using proxy: Disabled	
App config/log directory: /home/ubu/.config/Jackett	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads	
Running in Docker: No	
File /etc/issue: Pop!_OS 22.04 LTS \n \l	
Jackett variant: CoreLinuxAmdx64	
OS version: Unix 6.0.12.76060006 (64bit OS) (64bit process)	
Environment version: 6.0.11 (/home/ubu/Jackett/)	
Starting Jackett v0.20.2686
```

### Description

I used to be able to use this tracker but now I keep getting the resource is unavailable. What's weird is that I can log into the website for revolutiontt just fine using the same credentials that I am using in jackett

### Logged Error Messages

```text
Resource temporarily unavailable (revolutiontt.me:443): Resource temporarily unavailable
```

### Screenshots

![jackett_error](https://user-images.githubusercontent.com/4355437/214017435-39d0d598-30b4-4e36-9173-5ea261b00bf5.PNG)

**Comment by ilike2burnthing** [comment]
Provide the output for the following on the same device as Jackett:

`curl -v https://revolutiontt.me/login.php`

**Comment by ubuntuaddicted** [comment]
it was a DNS issue. thanks. you can close this thread
