### ISSUE TITLE
lemonhd.yml

### ISSUE THREAD

**Issue by oglops** [Jackett/Jackett#13921]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
latest jackett v0.20.2671 running on Fedora 37
```

### Description

lemonhd still returns non-free torrent even when FreeLeech Only Search check box is on. Even though there is no search free torrent  in search option on lemon site,  if I add `&free=1` to url, it does filter the free torrent. 

Does this mean we can make it work by simply editing `lemonhd.yml`?

### Logged Error Messages

```text
no error
```

**Comment by ilike2burnthing** [comment]
My mistake, it wasn't removed in https://github.com/Jackett/Jackett/commit/91c70c88ece5ff3fe711a453dae64bee2fa6eecf, so it currently does nothing.

Does adding `&free=` or `&free=0` return all results (freeleech and normal)?

**Comment by oglops** [comment]
Just tried

| &free=1                            | show freeleech result only  |
|------------------------------------|-----------------------------|
| &free=                             | still shows free leech only |
| &free=0                            | still shows free leech only |
| &free                              | still shows free leech only |
| completely remove  &free or &free= |                             |

**Comment by garfield69** [comment]
v0.20.2686
