### ISSUE TITLE
[3evils] (updating) The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject]  CN=thedarkcommunity.cc[Issuer]  CN=R3, O=Let's Encrypt, C=US[Serial Number]  03A768BF02716999E8A90154092B468C6063[Not Before]  1/19/2023 7:13:33 AM[Not After]  4/19/2023 8:13:32 AM[Thumbprint]  236E0ACC7D677515775EE8E190A3A7443201122C

### ISSUE THREAD

**Issue by deecypher** [Jackett/Jackett#13922]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
I've followed the directions above including checking "Enhanced logging" and unchecking "Cache enabled", but I couldn't find any data similar to this field. Perhaps the log output has been modified?
```

### Description

Basically I just can't seem to add 3evils tracker. I think there's something wrong with their website because when I go to it, it's all buggy and weird looking.
[log.txt](https://github.com/Jackett/Jackett/files/10472995/log.txt)

### Logged Error Messages

```text
An error occurred while updating this indexer
The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject] CN=thedarkcommunity.cc [Issuer] CN=R3, O=Let's Encrypt, C=US [Serial Number] 03A768BF02716999E8A90154092B468C6063 [Not Before] 1/19/2023 7:13:33 AM [Not After] 4/19/2023 8:13:32 AM [Thumbprint] 236E0ACC7D677515775EE8E190A3A7443201122C
```

### Screenshots

<img width="618" alt="Screenshot 2023-01-21 at 3 35 13 PM" src="https://user-images.githubusercontent.com/9927271/213886192-cb1b8a52-81ee-4f5b-b34f-e93f6af98248.png">

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/13534#issuecomment-1382644108
