### ISSUE TITLE
[req]: Create discussions page - constant issues with RARBG due to user ignorance?

### ISSUE THREAD

**Issue by jprokos** [Jackett/Jackett#13936]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I have questions on best practices relative to implementing the RSS features of Jackett. These are not necessarily "bugs" but do have a possible impact on future development of Jackett... where do I post these questions? A discussions forum would be more appropriate than filing a "bug".

The problem is with RARBG, which is my primary indexer. I have followed the bug report [here](https://github.com/Jackett/Jackett/issues/13663) and seen the confusion over why so many calls to RARBG. One reason may be unintentional and based on user setup (since there is no repository of information on this site or any other active group - it's difficult to determine best practices).

It seems that the multiple RSS rules I have set up are causing the following errors:

> torrentapi.org returned code 20 with Rate Limit exceeded.
> torrentapi.org returned Error 520

I initially had the interval set to 20 minutes and now I have setup RSS feeds refresh interval to every 60 minutes and still received errors.

I have caching enabled in Jackett and have also added `&cache=true` to the requests (by the way `&cache=true` is undocumented as far as I can tell, if it is - where).

```
http://127.0.0.1:9117/api/v2.0/indexers/tag:tv/results/torznab/api?apikey=redacted&t=search&cache=true&cat=5000&q=
http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=redacted&t=search&cache=true&cat=5040&q=

http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=redacted&t=search&cache=true&cat=2045&q=2160p x265
http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=redacted&t=search&cache=true&cat=2040&q=1080p+x265+WEB
http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=redacted&t=search&cache=true&cat=2040&q=1080p+BluRay+x265
http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=redacted&t=search&cache=true&cat=2040&q=1080p x265
```
logs of RSS  refresh after 60 minutes with above RSS feeds
```
2023-01-27 09:48:36 | Info | Torznab search in tag:tv => Found 210 releases
-- | -- | --
2023-01-27 09:48:36 | Warn | torrentapi.org returned Error 520
2023-01-27 09:48:31 | Warn | torrentapi.org returned Error 520, retrying after 5 secs
2023-01-27 09:48:26 | Info | Torznab search in RARBG => Found 100 releases
2023-01-27 09:48:25 | Info | Torznab search in tag:mvgroup => Found 100 releases
2023-01-27 09:48:22 | Info | CardigannIndexer (mvgroupmain): Relogin required
2023-01-27 09:48:20 | Info | CardigannIndexer (mvgroupforum): Relogin required
2023-01-27 09:48:19 | Info | Torznab search in RARBG for 2160p x265 => Found 0 releases
2023-01-27 09:48:19 | Warn | torrentapi.org returned code 20 with Rate Limit exceeded.
2023-01-27 09:48:14 | Warn | torrentapi.org returned code 20 with Rate Limit exceeded. Retrying after 5 secs.
2023-01-27 09:48:09 | Info | Torznab search in RARBG for 1080p x265 => Found 100 releases
2023-01-27 09:48:03 | Warn | torrentapi.org returned code 20 with Rate Limit exceeded. Retrying after 5 secs.
2023-01-27 09:47:58 | Info | Torznab search in RARBG for 1080p BluRay x265 => Found 100 releases


```

### Describe the solution you'd like

I would like a method to communicate with the Jackett user base that doesn't entail bothering developers over various setup options.

### Describe alternatives you've considered

I have googled. Checked Reddit forum and searched the Jackett and qBittorrent GitHub repos.

@rarbg

**Comment by rarbg** [comment]
@jprokos whats your ip range ?

**Comment by jprokos** [comment]
> @jprokos whats your ip range ?

I am using a VPN
PUB IP 98.222.135.231
VPN IP 172.98.80.181

**Comment by rarbg** [comment]
@jprokos you are using a public VPN that is overabusing the API - user ignorance

**Comment by jprokos** [comment]
> @jprokos you are using a public VPN that is overabusing the API - user ignorance

I see, because it's a shared VPN IP I should expect to receive that warning regardless of my attempts to do right by RARBG?
There is no solution other than paying for a private VPN IP?
However having a private VPN IP seems to open my activity up to more scrutiny... am I incorrect?

**Comment by rarbg** [comment]
@jprokos 

> I see, because it's a shared VPN IP I should expect to receive that warning regardless of my attempts to do right by RARBG?

Rate limits are per ip address

>  There is no solution other than paying for a private VPN IP?

A) Dont use a public VPN to access the API - anyways public VPNs sell your data if you are going to say that you care about your privacy
B) dont use a VPN to access the API - use it only on your torrent client

>  However having a private VPN IP seems to open my activity up to more scrutiny... am I incorrect?

All VPNs can pinpoint clients and have full blown connection tracking. They might not log anything or they might just claim to do so but they can still track you

**Comment by jprokos** [comment]
@rarbg
>
> > There is no solution other than paying for a private VPN IP?
> 
> A) Dont use a public VPN to access the API - anyways public VPNs sell your data if you are going to say that you care about your privacy B) dont use a VPN to access the API - use it only on your torrent client

I am paying for PIA VPN and have an account is that not a private VPN? I understand the IPs are shared among all of their users I assumed this allowed greater anonymity - Please provide example of Private VPN... do you mean setting up your own VPN via a cloud VM?

> > However having a private VPN IP seems to open my activity up to more scrutiny... am I incorrect?
> 
> All VPNs can pinpoint clients and have full blown connection tracking. They might not log anything or they might just claim to do so but they can still track you

PIA says they have been audited and don't track, but...

**Comment by rarbg** [comment]
> Please provide example of Private VPN... do you mean setting up your own VPN via a cloud VM?

Private VPN ip means renting a IP that you only use from a VPN provider - some sell those - or buying a VM/dedicated and running your VPN on it

> PIA says they have been audited and don't track, but...

I have a bridge to sell you

**Comment by agneevX** [comment]
@rarbg this is the same for me on my residential connection unfortunately :(

**Comment by rarbg** [comment]
@agneevX provide logs

**Comment by agneevX** [comment]
@rarbg with caching disabled...

```
02-05 11:29:01 Warn torrentapi.org returned code 20 with Rate Limit exceeded. Retrying after 5 secs. 
02-05 11:29:06 Warn torrentapi.org returned code 20 with Rate Limit exceeded. 
02-05 11:29:06 Info Torznab search in RARBG => Found 0 releases 
02-05 11:29:11 Warn torrentapi.org returned code 20 with Rate Limit exceeded. Retrying after 5 secs. 
02-05 11:29:16 Warn torrentapi.org returned code 20 with Rate Limit exceeded. 
02-05 11:29:16 Info Torznab search in RARBG for Poker Face 2023 S01E03 => Found 0 releases
```

```
02-05 12:00:16 Warn torrentapi.org returned code 20 with Rate Limit exceeded. Retrying after 5 secs. 
02-05 12:00:21 Warn torrentapi.org returned code 20 with Rate Limit exceeded. 
02-05 12:00:21 Info Torznab search in RARBG => Found 0 releases 
02-05 12:00:27 Warn torrentapi.org returned code 20 with Rate Limit exceeded. Retrying after 5 secs. 
02-05 12:00:32 Warn torrentapi.org returned code 20 with Rate Limit exceeded. 
02-05 12:00:32 Info Torznab search in RARBG for Poker Face 2023 S01E04 => Found 0 releases
```

**Comment by rarbg** [comment]
@agneevX you have multiple services configured to jackett hitting the API limits at the same time or your ip is shared
contact support

**Comment by agneevX** [comment]
@rarbg 

> you have multiple services configured to jackett hitting the API limits at the same time or your ip is shared

As per the logs, that's the only thing being done.

> or your ip is shared

I do not think so as I'm the only one with the IP address I have now, it is however rotated in a IP pool.

> contact support

Please elaborate, thanks.

**Comment by rarbg** [comment]
@agneevX what version of jackett are you using ?

> Please elaborate, thanks.

contact support@rarbg.to duh

**Comment by agneevX** [comment]
@rarbg version v0.20.2904

Will email!

**Comment by rarbg** [comment]
@agneevX  - case confirmed to be using dynamic rotating ip shared with thousands of other users by his ISP
Once more a case of user ignorance

**Comment by agneevX** [comment]
@rarbg this is not true... this particular IP range is assigned to my internet provider's local node that distributes the connection to end users like me. 

At most this is shared between 30 users. How do I know this? Because the person-in-charge lives two doors away from me. Please choose your words carefully.

**Comment by rarbg** [comment]
@agneevX and the limit is  1 user per IP on the API. 30 users randomly distributing their requests will get your IP rate limited. And this is exactly what your logs show.

**Comment by agneevX** [comment]
@rarbg There is one single user per IP address, not more than that. My ISP does not do CGNAT.

**Comment by rarbg** [comment]
@agneevX i dont see what you claim to be true in the logs that i enabled for the range you provided. So i have no clue why you continue to argue that.

**Comment by agneevX** [comment]
@rarbg Please provide said logs to back your claim.

**Comment by rarbg** [comment]
@agneevX please fuck off if you think im going to provide you personal data logs
are you stupid ?

**Comment by agneevX** [comment]
@rarbg the fact that this is the same behavior on a VPS I own with a cloud provider that has a static IP assigned, further flames the fire.

**Comment by rarbg** [comment]
@agneevX i would suggest switching to another torrent site's API

**Comment by jprokos** [comment]
@rarbg

I came back to post and read through your comments. I appreciate there is frustration on your part AND at the same time I want to share that **for my part** I have been seeding over one thousand RARBG torrents for over a year, and paying for that unlimited bandwidth and additional speed. My ratio is 3.86. I recognize that I am probably not the norm AND it's the least I can do, but also feel like I am being grouped in with and punished with the abusers.

If you block every single person who is on a cable connection,  and also those using a "public" VPN to connect... well that's the majority of users out there. People use shared IPs for anonymity.

I found today that, while the RSS feed runs every hour and works, I can't run a single search on RARBG using Jackett. "No Results" every time. This wasn't always the case.

Thank you for your hard work.

**Comment by rarbg** [comment]
>  I found today that, while the RSS feed runs every hour and works, I can't run a single search on RARBG using Jackett. "No Results" every time. This wasn't always the case.

Send your ip to support to investigate

> If you block every single person who is on a cable connection, and also those using a "public" VPN to connect... well that's the majority of users out there. People use shared IPs for anonymity.

97% of the requests are not rate limited. If you think the majority of people are having issues - see how many are actually complaining

**Comment by 101John** [comment]
@rarbg 
I bypassed the dedicated IP from my VPN just for Jackett and have the same issue. I have a cable connection but my IP hasn't changed in over a year.

Maybe it's the **quantity** of rules themselves that are causing the issue? I have my download rules set up to query particular shows by id instead of scooping up all releases in a particular category (TV Shows) with a single RSS rule and then sifting through using regex filters.

Example
```
http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=redacted&t=tvsearch&cat=5000&tvdbid=364093
http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=redacted&t=tvsearch&cat=5000&tvdbid=76177
http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=redacted&t=tvsearch&cat=5000&tvdbid=81157
http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=redacted&t=tvsearch&cat=5000&tvdbid=84082
http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=redacted&t=tvsearch&cat=5040&tvdbid=80646
```

qBittorrent doesn't have an option to stage fetching for each rule. It just sends each fetch in succession to Jackett which is supposed to wait some time between fetches. With my fetch interval at one hour I still see that when the fetch starts some will run and then the next few will be rate limited.

If there is another way to get the same functionality, by ID, without getting rate limited I would do whatever. Would having RSS refresh rate set in qBittorrent to double or triple the Jackett Cache TTL fix this issue?
