### ISSUE TITLE
[req]: Add all button on add indexer page

### ISSUE THREAD

**Issue by CSMicros** [Jackett/Jackett#13934]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

im frustrated when i need to reinstall my machine and then re-install jackett and have to manually select all the indexers when i have all of them seleected

### Describe the solution you'd like

a button I can press and the add indexer page after selecting my filters.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/12143
