### ISSUE TITLE
Unable to download torrent files from Lime Torrents Tracker

### ISSUE THREAD

**Issue by Rishabh145** [Jackett/Jackett#1393]
```
Jackett version: 0.7.1422.0`
Mono version: Stable 5.0.0.100
Uname -a output: Linux BedroomRasPi 4.9.28-2-ARCH #1 SMP Wed May 17 01:14:29 UTC 2017 armv7l GNU/Linux
```
I am unable to download torrent files from LimeTorrent tracker, the search works perfectly and I'm able to download torrent files from other sites.
I need this feature as I use jackett along with radarr and sonarr, so limetorrent indexer doesn't work at all.

[log.txt](https://github.com/Jackett/Jackett/files/1007375/log.txt)

**Comment by kaso17** [comment]
I can't reproduce it.
Can you please run jackett with the -t -l command line switches and repost the log?

**Comment by fryfrog** [comment]
If you're using a systemd unit file, try
```
# /etc/systemd/system/jackett.service.d/override.conf
[Service]
Environment=MONO_TLS_PROVIDER=legacy
```

If you're not, get `MONO_TLS_PROVIDER=legacy` into your start command.

The new default TLS provider has issues. I've seen it in Arch and someone on CentOS using the Mono rpm repositories.

**Comment by ApteryxK** [comment]
@fryfrog  could you guide me a little more, I am on windows, I believe this won't work for me right ?

**Comment by Rishabh145** [comment]
Sorry for going AWOL, exams.

@kaso17 Here's the commandline output of jackett on running jackett with -t -l switches: [output.log.txt](https://github.com/Jackett/Jackett/files/1044446/output.log.txt)
Here's the jackett logs: [log.txt](https://github.com/Jackett/Jackett/files/1044463/log.txt)

**Comment by Rishabh145** [comment]
@fryfrog, making those changes did not make any difference, I still am unable to download torrent files from Lime Torrents.

**Comment by Rishabh145** [comment]
Also, I have upgraded Jackett to  v0.7.1437.0.

**Comment by kaso17** [comment]
@Rishabh145 from you log it looks like the "Samurai Jack  01-10" wasn't available on itorrents.org when you were trying to download it. please try again searching for it and downloading. By now it is.
This can't be fixed. Using the itorrents option is not recommended, you should use the magnet links only with lime torrents.

**Comment by Rishabh145** [comment]
@kaso17 There is no option to download the file via magnet link, I definitely would've preferred that if there was an option

**Comment by kaso17** [comment]
I checked the definition/page again. Unfortunately the info hash is not available from the search results, so magnet links can't be generated. Seems like they just generate the itorrents download links blindly too.
There's no good way to fix this on the jackett side.
