### ISSUE TITLE
[req]: UnleashTheCartoons.world

### ISSUE THREAD

**Issue by moonsugar33** [Jackett/Jackett#13930]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: UnleashTheCartoons
- URL: https://unleashthecartoons.world/
- Description: English/Romanian cartoon tracker
- Minimum Seeding Time and Minimum Ratio (if Private): 2 days or 1.0
- Additional Comments: Opened for beta testing recently.
```

**Comment by garfield69** [comment]
v0.20.2721

**Comment by ilike2burnthing** [comment]
> From the lack of time to upload and money to pay for the seeding servers, we will step down. You have time until 22nd July to grab the torrents, after that the site will go offline.

**Comment by garfield69** [comment]
latest news:
>I have talked with <removed> and we decide to keep Tracker alive. The torrents will be dead until the 1 of August, but if need them just ask for reseed🙂, Enjoy
