### ISSUE TITLE
[TOrrent-tuRK] Search results could not found when there is Turkish characters in the query.

### ISSUE THREAD

**Issue by batuhankrmn** [Jackett/Jackett#13931]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.20.2691
Windows 11 Pro
Chrome
```

### Description

I noticed that If there is any Turkish characters in the search request, results didn't queried. For instance search query is "bülbül" and no result returned on Jackett WebUI but there are 4 available results on the tracker itself. Same case is valid for "ş" "ö" "ü" "ç" "ğ" "ı" characters. I'm leaving the screenshots of the results:

### Logged Error Messages

```text
None
```

### Screenshots

![image](https://user-images.githubusercontent.com/57859656/214602488-e97fbe40-9dd8-4657-a0b7-fb8a23d64efe.png)

![image](https://user-images.githubusercontent.com/57859656/214602086-07d90313-25f4-4372-b56d-7a33e4d2c7e7.png)

**Comment by ilike2burnthing** [comment]
Since the indexer was created in 2018, it has replaced non-English alphanumeric characters with `%` as a wildcard:

https://github.com/Jackett/Jackett/blob/2a593a195c13069d96b7b42625cdaa77f5a05c3f/src/Jackett.Common/Definitions/torrent-turk.yml#L127-L129

I don't have an account, so I can say if there's been some recent change or if this was never needed and has been missed until now. You could try removing the three lines above and restarting Jackett, see if that helps.

**Comment by batuhankrmn** [comment]
> Since the indexer was created in 2018, it has replaced non-English alphanumeric characters with `%` as a wildcard:
> 
> https://github.com/Jackett/Jackett/blob/2a593a195c13069d96b7b42625cdaa77f5a05c3f/src/Jackett.Common/Definitions/torrent-turk.yml#L127-L129
> 
> I don't have an account, so I can say if there's been some recent change or if this was never needed and has been missed until now. You could try removing the three lines above and restarting Jackett, see if that helps.

Wow thanks, Removing these 3 lines really fixed the issue. You might want to add this change to next version.
![image](https://user-images.githubusercontent.com/57859656/214614143-433d53ac-b691-4b73-bad3-d40696888df8.png)

**Comment by ilike2burnthing** [comment]
I'll let @garfield69 double-check, in case anything else needs done, but hopefully it will be that simple.

**Comment by garfield69** [comment]
v0.20.2707
