### ISSUE TITLE
Information Request: Process of migrating an existing Cardigann definition to a code based implementation

### ISSUE THREAD

**Issue by CodeMonkey626** [Jackett/Jackett#1395]
I just wanted to know if there's a mechanism for replacing a Cardigann yml definition with a code based implementation for a tracker that seamlessly migrates users onto the new implementation.

I ask because nyaa.si today is using a Cardigann based implementation, but in the future they may implement an API: https://github.com/nyaadevs/nyaa/issues/18

If that happens, it we should switch the implementation to that API instead of scraping the website, but it would be ideal if this could be done in a seamless way for people who have already added the nyaa-si indexer.

Thanks.

**Comment by kaso17** [comment]
That should'n be a problem. The C# class just needs to have the same name (e.g. NyaaSi). The native indexers are loaded first, any following cardigann definition will fail to load.

Assuming the proposed torznab API is accepted i would suggest to implement a generic/abstract TorznabProxy indexer and then the NyaaSi indexer inheriting the generic TorznabProxy indexer.

**Comment by CodeMonkey626** [comment]
Yeah, that makes sense. At that point its kind of mostly about back-compat, because if a site exposes a Torznab API, it can be configured directly inside of Sonarr, etc without using Jackett.

**Comment by kaso17** [comment]
I fully agree, everyone should use the direct version. But we still should keep support for it in Jackett (using the API preferable).
