### ISSUE TITLE
[pttime] Web server is down

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#13969]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
n/a
```

### Description

https://www.pttime.org/ - Web server is down - Error code 521

[check posters once back up]

### Logged Error Messages

```text
n/a
```

**Comment by ilike2burnthing** [comment]
back up, posters working fine

**Comment by garfield69** [comment]
```
Seeing this prompt, it means that the site is suspended due to excessive server pressure, and we are trying to improve it... After the official operation, compensation including but not limited to supplementary cards, magic power, etc. will be given, thank you
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.pttime.org/ - Connection timed out Error code 522

**Comment by garfield69** [comment]
uptrend all clear and login page is present. Can you login?

**Comment by ilike2burnthing** [comment]
https://www.pttime.org/
- HTTP ERROR 500
- Connection timed out Error code 522

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://www.pttime.org/ - Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up
