### ISSUE TITLE
[xspeeds] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13974]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

The XSpeeds site is offline

### Logged Error Messages

```text
see screenshot below
```

### Screenshots

![image](https://user-images.githubusercontent.com/6933240/216787804-59d96d85-b1c6-4545-b8b6-b8b01a2ecf2d.png)

**Comment by ilike2burnthing** [comment]
back up
