### ISSUE TITLE
scenefz.me does not work "Configuration Failed:"

### ISSUE THREAD

**Issue by alextzro** [Jackett/Jackett#1398]
Hello,

Scenefz.me configuration does not work. It gives me a message "Configuration Failed:".
I am using the latest docker image from linuxserver Jackett Version 0.7.1432.0

**Comment by kaso17** [comment]
I believe since it has reopend the definition hasn't been updated.

**Comment by alextzro** [comment]
Before this it had a different address so I think it was updated.
Who can check this?

**Comment by panoramasecret** [comment]
Same for me, I try to add indexer scenefz.me and gives me 
"Configuration Failed:".
Anybody sorting out this issue?

**Comment by panoramasecret** [comment]
Does anybody look into this issue?

**Comment by seanvree** [comment]
Yeah, I have the same issue.

**Comment by kaso17** [comment]
To give you an update:
The current definition is for the old scenefz. The new one has a completely different software/layout. Due to that the definition must be completely recreated.
I've very little time currently and I'm focusing on other broken trackers which require less work.

**Comment by seanvree** [comment]
all good @kaso17  - thanks for the work!

**Comment by alextzro** [comment]
Seems there is an update to the site and the tracker does not work anymore

**Comment by kaso17** [comment]
fixed via 946c8bd5bf769485cdc939f506b9d5ba60e84c78
