### ISSUE TITLE
[oldtoonsworld] Login failed: No form found

### ISSUE THREAD

**Issue by Slikkster** [Jackett/Jackett#13981]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: https://flaresolverr.slikk.net
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.20348.0 (64bit OS)
Environment version: 6.0.13 (C:\ProgramData\Jackett\)
Starting Jackett v0.20.2930
```

### Description

Previously working configuration for OldToonsWorld now fails with the error:

> Exception (oldtoonsworld): Login failed: No form found on https://oldtoons.world/login.php using form selector form[action="takelogin.php"]: Parse error

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (oldtoonsworld): Login failed: No form found on https://oldtoons.world/login.php using form selector form[action="takelogin.php"]

Error on 20230206182624 for Old Toons World.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://oldtoons.world/login.php using form selector form[action="takelogin.php"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 591
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1544
```

**Comment by garfield69** [comment]
the indexer is working for me so the issue appears to be at your end.
the site has a captcha at login.
please confirm that if you edit the jackett oldtoonsworld config you see the captcha image?
if you do not then something is blocking you access.
turn on enhanced logging and repeat the config setup and see if the log gives you a clue to why the login failed.

**Comment by Slikkster** [comment]
I do not see the captcha. I assumed everything was fine as I am still logged into the site without any issues, but if I try to login with another browser I get this error:

> Login Locked! (the maximum number of failed Login attempts is reached during reauthentication)
> We come to believe you are trying to cheat our system, therefore we've banned your ip!

Unsure why this has happened, but obviously not a problem with Jackett.
