### ISSUE TITLE
[pterclub] (updating) Login failed: No form found on https://pterclub.com/login.php using form selector form[action="takelogin.php"]

### ISSUE THREAD

**Issue by ToJ112** [Jackett/Jackett#13995]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Ubuntu
```

### Description

this site close open login,we should login by private link

### Logged Error Messages

```text
An error occurred while updating this indexer
Login failed: No form found on https://pterclub.com/login.php using form selector form[action="takelogin.php"]
```

**Comment by ilike2burnthing** [comment]
Would cookies be sufficient to gain access?

**Comment by garfield69** [comment]
v0.20.3017
