### ISSUE TITLE
Result is cached when the search result returned error

### ISSUE THREAD

**Issue by programatix** [Jackett/Jackett#13998]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Running in Docker: Yes
Jackett variant: [linuxserver/jackett](https://github.com/linuxserver/docker-jackett)
Jackett version: v0.20.3017
```

### Description

Whenever a search result returns error, the result is cached. The next search will be obtained from cache with 0 result.

The following log shows that request through Torznab api casuing torrentapi.org (RARBG) to return error due to multiple queries. It seems that 5 seconds delay is insufficient. The call is from sonarr.
```
2023-02-10 20:09:45 | Info | Torznab search in RARBG for Dragon Prince S01 => Found 0 releases
2023-02-10 20:09:45 | Warn | torrentapi.org returned code 20 with Rate Limit exceeded.
2023-02-10 20:09:40 | Warn | torrentapi.org returned code 20 with Rate Limit exceeded. Retrying after 5 secs.
2023-02-10 20:09:35 | Info | Torznab search in RARBG for Der Prinz der Drachen S01 => Found 0 releases
2023-02-10 20:09:35 | Warn | torrentapi.org returned code 20 with Rate Limit exceeded.
2023-02-10 20:09:30 | Warn | torrentapi.org returned code 20 with Rate Limit exceeded. Retrying after 5 secs.
2023-02-10 20:09:24 | Info | Torznab search in RARBG for Il Principe dei Draghi S01 => Found 0 releases
```

Then subsequent search result is as follow,
```
Torznab search in RARBG for Dragon Prince S01 => Found 0 releases (from cache)
```

Performing manual search return result as expected,
```
2023-02-10 20:12:57 | Info | Manual search in RARBG for Dragon Prince S01 => Found 9 releases (from cache)
2023-02-10 20:12:54 | Info | Manual search in RARBG for Dragon Prince S01 => Found 9 releases
```

There seems to be 2 things that need to be corrected.
1. Increase the retry delay for certain tracker such as RARBG.
2. Do not cache result if search result is an error.
3. Add an option to use the cache for Manual search in Torznab search.

### Logged Error Messages

```text
2023-02-10 20:09:45 | Info | Torznab search in RARBG for Dragon Prince S01 => Found 0 releases
2023-02-10 20:09:45 | Warn | torrentapi.org returned code 20 with Rate Limit exceeded.
2023-02-10 20:09:40 | Warn | torrentapi.org returned code 20 with Rate Limit exceeded. Retrying after 5 secs.
2023-02-10 20:09:35 | Info | Torznab search in RARBG for Der Prinz der Drachen S01 => Found 0 releases
2023-02-10 20:09:35 | Warn | torrentapi.org returned code 20 with Rate Limit exceeded.
2023-02-10 20:09:30 | Warn | torrentapi.org returned code 20 with Rate Limit exceeded. Retrying after 5 secs.
2023-02-10 20:09:24 | Info | Torznab search in RARBG for Il Principe dei Draghi S01 => Found 0 releases
...
Torznab search in RARBG for Dragon Prince S01 => Found 0 releases (from cache)
```

**Comment by ilike2burnthing** [comment]
1. https://github.com/Jackett/Jackett/issues/13936 & https://github.com/Jackett/Jackett/issues/13663
2. https://github.com/Jackett/Jackett/issues/11410
3. if I'm understanding your point - https://github.com/Jackett/Jackett#torznab-cache

**Comment by programatix** [comment]
@ngosang closed https://github.com/Jackett/Jackett/issues/11410 because it is logical to cache 0 result if there is no error. However, the issue now is, when error (Warn), the 0 result is also cached.

It would be great if when there is a "Warn" or "Error", then the result is not cached.

The problem arises due to ..arr apps performing multiple searches if an item has alternative names and in the log above, the last search is the required one. Due to the "Rate Limit" error and jackett caching error result, the needed search will never be to get the result.

**Comment by ilike2burnthing** [comment]
Might be a while until they're next free.

In the mean time, see the first linked issue above, see if that applies to you. If not, then see the last link above.

**Comment by programatix** [comment]
For the 1st link, nothing we can do about it due to the "Rate Limit" implemented by rarbg.

For the last link, it is to disable Torznab cache in the .arr apps' indexer. By disabling cache, then the issue I'm having could not be resolved because as mentioned, in the issue stated above, the query that is required is the last one. Due to multiple queries before reaching that one, the "Rate Limit" has already triggered. The use of cache will resolve this issue, if it doesn't cache the error result.

eg,

1st pass
```
Torznab search in RARBG for Il Principe dei Draghi S01 => success
Torznab search in RARBG for Der Prinz der Drachen S01 => Found 0 releases due to error "Rate Limit"
Torznab search in RARBG for Dragon Prince S01 => Found 0 releases due to error "Rate Limit"
```

2nd pass (assuming Rate Limit has been released by rarbg)
```
Torznab search in RARBG for Il Principe dei Draghi S01 => success (cache)
Torznab search in RARBG for Der Prinz der Drachen S01 => success
Torznab search in RARBG for Dragon Prince S01 => Found 0 releases due to error "Rate Limit"
```

3rd pass (assuming Rate Limit has been released by rarbg)
```
Torznab search in RARBG for Il Principe dei Draghi S01 => success (cache)
Torznab search in RARBG for Der Prinz der Drachen S01 => success (cache)
Torznab search in RARBG for Dragon Prince S01 => success
```

**Comment by ilike2burnthing** [comment]
> For the 1st link, nothing we can do about it due to the "Rate Limit" implemented by rarbg.

So to be clear, you're not using a proxy or VPN, you don't have a shared IP, and no one else using your IP is running a second instance of Jackett?

**Comment by programatix** [comment]
I'm a home user and the IP is assigned dynamically by the ISP. In my house, the nas is the only one using jackett but it is running a few ..arr apps. The Rate Limit thing usually occurs when I performed a search in the ..arr apps. Sonar for example will performs multiple search queries if the show has alternatives names. This is the part which is causing problem.

**Comment by ilike2burnthing** [comment]
Multiple searches shouldn't really be an issue as they're still delayed to be 5s apart, with torrentapi's limit being 1req/2s.
