### ISSUE TITLE
Errors installing on (Fresh)tomato

### ISSUE THREAD

**Issue by wellloaded** [Jackett/Jackett#13994]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
FreshTomato 2022.7 ARM + Entware
```

### Description

I'm following a guide for OpenWRT found here: https://github.com/Jackett/Jackett/wiki/Installation-on-OpenWrt

But since I'm on FreshTomato I had to install manually some entware package like:
```

opkg install icu
opkg install icu-full-data
opkg install libstdcpp
opkg install libintl-full
opkg install coreutils-readlink
opkg install coreutils-dirname 
```

So:
```
root@router:/mnt/USB/nginx/html/Jackett# which dirname
/opt/bin/dirname
root@router:/mnt/USB/nginx/html/Jackett# which readlink
/opt/bin/readlink
```

For some reason I'm unable to run the jackett_launcher.sh
root@router:/mnt/USB/nginx/html/Jackett# ./jackett_launcher.sh
/mnt/USB/nginx/html/Jackett/jackett: line 1: syntax error: unexpected word (expecting ")")

however this looks pretty straight forward to me:
```
root@router:/mnt/USB/nginx/html/Jackett# cat jackett_launcher.sh
#!/bin/sh

# Helper script to fix
# https://github.com/Jackett/Jackett/issues/5208#issuecomment-547565515

# Get full Jackett root path
JACKETT_DIR="$(dirname "$(readlink -f "$0")")"

# Launch Jackett (with CLI parameters)
"${JACKETT_DIR}/jackett" --NoRestart "$@"
ec=$?

# Get user running the service
JACKETT_USER=$(whoami)

# Wait until the updater ends
while pgrep -u "${JACKETT_USER}" JackettUpdater > /dev/null; do
    sleep 1
done

exit $ec
```

### Logged Error Messages

```text
root@router:/mnt/USB/nginx/html/Jackett# ./jackett_launcher.sh
+ readlink -f ./jackett_launcher.sh
+ dirname /mnt/USB/nginx/html/Jackett/jackett_launcher.sh
+ JACKETT_DIR=/mnt/USB/nginx/html/Jackett
+ /mnt/USB/nginx/html/Jackett/jackett --NoRestart
/mnt/USB/nginx/html/Jackett/jackett: line 1: syntax error: unexpected word (expecting ")")
+ ec=2
+ whoami
+ JACKETT_USER=root
+ pgrep -u root JackettUpdater
+ exit 2
```

### Screenshots

Screenshot look exactly like the shell output above.

**Comment by ilike2burnthing** [comment]
MIPS architecture? See https://github.com/Jackett/Jackett/issues/13667.

**Comment by ilike2burnthing** [comment]
@avengermsoft any ideas?

**Comment by wellloaded** [comment]
I have no switched to the  Jackett.Binaries.LinuxMuslARM32.tar.gz (also tried x64 with the same result) and the message is now different:

```
root@sparrow:/tmp/mnt/USB/nginx/html/Jackett# ./jackett_launcher.sh
./jackett_launcher.sh: line 10: /tmp/mnt/USB/nginx/html/Jackett/jackett: not found

```

however:
```
root@sparrow:/tmp/mnt/USB/nginx/html/Jackett# ls -l ./jackett
-rwxrwxrwx    1 root     root         60384 Feb  9 05:10 ./jackett
```

Not sure what to try next?

**Comment by ilike2burnthing** [comment]
> I have no switched to the Jackett.Binaries.LinuxMuslARM32.tar.gz (also tried x64 with the same result)

What were you using before?

@hydazz you had the same issue in  https://github.com/Jackett/Jackett/issues/10555, and fixed it by making your own musl build. In case you weren't aware, we have our own as of a year ago. Are you seeing this issue with our build? If not, any idea of how to resolve it?

**Comment by avengermsoft** [comment]
Please show the result of the command ```cat /opt/etc/entware_release```?

**Comment by hydazz** [comment]
@ilike2burnthing
> @hydazz you had the same issue in https://github.com/Jackett/Jackett/issues/10555, and fixed it by making your own musl build. In case you weren't aware, we have our own as of a year ago. Are you seeing this issue with our build? If not, any idea of how to resolve it?

My issue was that at the time jackett was only build for glibc, so when it ran there was the `not found` error as the glibc libraries are not on alpine. I would think that this is a similar issue. I have no experience with tomato or openwrt but sounds like the binary is compiled for the wrong OS/library, either glibc or musl.

**Comment by avengermsoft** [comment]
I also do not see any problems in working on musl ARM64.

![изображение](https://user-images.githubusercontent.com/18549626/218021554-a5161da8-44cd-4734-b2d6-6879bb999080.png)

**Comment by wellloaded** [comment]
> Please show the result of the command:
> 
> `uname -a` `cat /opt/etc/entware_release` `ldd /tmp/mnt/USB/nginx/html/Jackett/jackett`
> 
> `chmod +x /tmp/mnt/USB/nginx/html/Jackett/jackett` `/tmp/mnt/USB/nginx/html/Jackett/jackett --version`
> 
> ?

Here you go:

![image](https://user-images.githubusercontent.com/46318040/218039051-139c37b4-d1f5-448e-bb7b-01996bc60dbf.png)

**Comment by hydazz** [comment]
@wellloaded `libc=glibc` you should not be using the musl release?

**Comment by wellloaded** [comment]
> @wellloaded `libc=glibc` you should not be using the musl release?

If I use the "standard" ARM builds e.g.
![image](https://user-images.githubusercontent.com/46318040/218041515-2d18893a-bbfd-44ba-b34c-bd0b51f6660c.png)

I get the line one error as per original post above.
```
root@router:/mnt/USB/nginx/html/Jackett# ./jackett_launcher.sh
/mnt/USB/nginx/html/Jackett/jackett: line 1: syntax error: unexpected word (expecting ")")
```

**Comment by avengermsoft** [comment]
Try using the musl build Jackett.Binaries.LinuxMuslARM32.tar.gz

**Comment by wellloaded** [comment]
> Try using the musl build Jackett.Binaries.LinuxMuslARM32.tar.gz

This was already attempted, see few posts above:
https://github.com/Jackett/Jackett/issues/13994#issuecomment-1424653183

Regardless here you go:
![image](https://user-images.githubusercontent.com/46318040/218048257-ed508c10-c908-41c9-b7ca-38bb89b8abd2.png)

**Comment by avengermsoft** [comment]
Will not work on Entware. The old version of toolchain 8.4 is used. It also uses glibc to build packages. To work, you need to use musl 1.2 when building packages, as is done in OpenWrt.

**Comment by avengermsoft** [comment]
For  Jackett.Binaries.LinuxMuslARM32.tar.gz :
```ldd /tmp/mnt/USB/nginx/html/Jackett/jackett```

**Comment by wellloaded** [comment]
> ldd /tmp/mnt/USB/nginx/html/Jackett/jackett

![image](https://user-images.githubusercontent.com/46318040/218053587-aac72535-45fa-4b69-b259-8c3937092093.png)

**Comment by ilike2burnthing** [comment]
Clearly a sign from the gods, someone just commented on this year old issue - https://github.com/Jackett/Jackett/issues/12648.

Not the same error, but ARMv7 caught my eye. Try [v0.19.275](https://github.com/Jackett/Jackett/releases/v0.19.275) ARM32 and see if that works.

**Comment by wellloaded** [comment]
> Clearly a sign from the gods, someone just commented on this year old issue - #12648.
> 
> Not the same error, but ARMv7 caught my eye. Try [v0.19.275](https://github.com/Jackett/Jackett/releases/v0.19.275) ARM32 and see if that works.

It seems to behave the same:
![image](https://user-images.githubusercontent.com/46318040/218120184-05984b53-293b-4565-af43-ce62d39a9faa.png)

**Comment by ilike2burnthing** [comment]
Out of interest, any difference if you write out the full path, rather than `./`?

**Comment by wellloaded** [comment]
> Out of interest, any difference if you write out the full path, rather than `./`?

Unfortunately not:
![image](https://user-images.githubusercontent.com/46318040/218122578-7dafd096-b9d8-48a6-8bb6-f4bb9f36fc71.png)

**Comment by lancethepants** [comment]
Someone from the tomato community asked me to take a look at this.
So there are a couple of issues with running jackett on Tomato.

Firstly, Tomato on all currently supported devices run uclibc, and a very old version at that. No glibc or musl prebuilt version is going to run with the native tomato libc.

The other option I explored was running jackett using the arm/musl libc version from my project [Tomatoware](https://github.com/lancethepants/tomatoware).  To get it to use the musl libc from my project I needed to run 
`patchelf --set-interpreter /mmc/lib/ld-musl-arm.so.1 jackett`
to point the jackett's dynamic linker to my project, which in itself is a bit hacky. Trying then to run jackett reveals the 2nd issue
 `Illegal instruction`.

All tomato arm supported routers use armv7 Cortex-A9 cpus. With the Cortex-A9 cpu the fpu is an optional feature depending on what the manufacturer wanted. Well asus and netgear arm32 router cpu's **do not** have an fpu. So tomato can only run binaries built with the `softfloat` abi.

So it looks as though this pre-built software is built against a libc built with the hardfloat abi. It would need a complete recompile, probably .NET and the whole works, if .NET even supports the softfloat abi.  Some software like nodejs require an fpu, and of course you can lose a ton of performance on fpu-less systems as well.

I was able to get the prebuilt musl arm64 version working on my rt-ax88u running asuswrt-merlin using my Tomatoware musl libc. For that I had to run 
`patchelf --set-interpreter /mmc/lib/ld-musl-aarch64.so.1 jackett`
and after compiling libicu it starts and I am able to access the web ui. I didn't try anything beyond that.
asuswrt uses 32bit glibc in userspace, even for 64bit cpus, so the prebuilt jackett might just work there as well, I didn't try it though.

**Comment by lancethepants** [comment]
Also `readelf -a jackett` reveals it needs VFPv3-D16. We cannot run those instructions because there is no fpu.
```
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3-D16
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_ABI_optimization_goals: Aggressive Size
  Tag_CPU_unaligned_access: v6
```

**Comment by ilike2burnthing** [comment]
Many thanks @lancethepants for the clarification.

Closing this issue as unsupported.
