### ISSUE TITLE
[req]: TheDarkCommunity (TDC)

### ISSUE THREAD

**Issue by SassyJ1** [Jackett/Jackett#13990]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: TDC
- URL: https://thedarkcommunity.cc/
- Description: TV and Movies Tracker
- Minimum Seeding Time and Minimum Ratio (if Private): 7 days
- Additional Comments: RSS and API key are both available, would like to be added to Jackett. Door closes on 10/02/2023 where it will be open application signups
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/13923
