### ISSUE TITLE
[req]:  Add possiblity to use proxy only for some tracker but not on every tracker

### ISSUE THREAD

**Issue by bozoweed** [Jackett/Jackett#13991]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

in some case i need to used proxy and some other i need to desable it ( for exemple for yggtorrent i don't wan't used proxy then flareSolverr can pass easly throu the captcha but for torrent9.io i need it because my ip was not able to acces a this website )

### Describe the solution you'd like

add an option in tracker for disable proxy on it 

### Describe alternatives you've considered

i have disable for now so i can go on yggtorrent .... but please juste add the option i think it was the better way

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/2539

**Comment by bozoweed** [comment]
okey but seem asked from 2018 .... please just add it , it's not so long to do ....

**Comment by ilike2burnthing** [comment]
PRs are always welcome, feel free.
