### ISSUE TITLE
TV Chaos UK broken

### ISSUE THREAD

**Issue by sethwarsh** [Jackett/Jackett#140]
When you test in Jackettapp web ui the result is the following::

The meta start tag position 9 line 2 does not match the end of tag of head line 25 position 3

It worked up until about 5 or 6 days ago.

Thanks for looking into it 

seth

**Comment by Azerelat** [comment]
The site has been offline for the last week.

**Comment by sethwarsh** [comment]
That’s a fairly good reason for the error ☺

Sorry, next time I’ll check the site first, that never even came to mind.

S
