### ISSUE TITLE
IMDB Results from web client differ relative to RSS indexer rule in qbittorrent

### ISSUE THREAD

**Issue by jprokos** [Jackett/Jackett#14009]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-02-13 03:11:31	Info	Using HTTP Client: HttpWebClient2
2023-02-13 03:11:31	Info	Using FlareSolverr: http://127.0.0.1:8191
2023-02-13 03:11:31	Info	Using proxy: Disabled
2023-02-13 03:11:31	Info	App config/log directory: /Users/john/.config/Jackett
2023-02-13 03:11:31	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-02-13 03:11:31	Info	Running in Docker: No
2023-02-13 03:11:31	Info	Jackett variant: CoreMacOs
2023-02-13 03:11:31	Info	OS version: Unix 12.6.3 (64bit OS) (64bit process)
2023-02-13 03:11:31	Info	Environment version: 6.0.13 (/Applications/Jackett/)
2023-02-13 03:11:30	Info	Starting Jackett v0.20.3063
```

### Description

I have searched using the web client at http://127.0.0.1:9117/ and find different results than appear in qBittorrent RSS for what I assumed was the same search request, but apparently is not.

How do I replicate this Jackett web client search with a RSS filter indexer rule?

<img width="1220" alt="Screen Shot 2023-02-13 at 2 41 41 AM" src="https://user-images.githubusercontent.com/9438406/218413198-66204e0e-f8c0-4e65-8fd8-4cfe0aa3d3fc.png">

I have tried this rule and it fails to find anything from the RARBG indexer:

`http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab/api?apikey=redacted&t=search&q=tt0081376`

<img width="1430" alt="Screen Shot 2023-02-13 at 2 41 59 AM" src="https://user-images.githubusercontent.com/9438406/218413991-71abf0b4-e2ab-4d4b-b1a0-10f3cd12c7eb.png">

I then tried adding `t=indexers` as suggested in "[Aggregate indexers](https://github.com/Jackett/Jackett#aggregate-indexers)" documentation. But this rule format fails.

`http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab/api?apikey=redacted&t=indexers&q=tt0081376`

It seems that if this search can work in the web client it should work in the RSS indexer as well if its syntax is correct.

Questions:

1. What search mode options are there? You allude to "...mixing search modes (IMDB, query, etc.)" Examples please of a mixing and non mixed search modes.

2. Does RARBG require a `cat=`statement in order to return results? what does the Web Client use for "Any" in Category when it runs its search?

### Logged Error Messages

```text
no Errors in logs
```

**Comment by jprokos** [comment]
@ilike2burnthing

You are reading and closing issues... the developer?

This had nothing to do with "losing control over indexer specific settings", rather needing more information. Information that is not stated on the ReadMe page.

@mynameisbogdan

Thank you!!!
**That was the solution, I get exactly the same results in RSS feed as I do in the web client**

**Comment by ilike2burnthing** [comment]
Not sure what your first question is supposed to be.

It's strongly recommended you don't use `all`.

It was decided a while ago that we're not going to enable Discussions.

**Comment by jprokos** [comment]
> Not sure what your first question is supposed to be.

I made a good faith effort to describe what I was seeing and asked for help in a way I thought was respectful. I did receive an answer from a user who was able to discern what my question was. 

> It's strongly recommended you don't use all.

I am using `all` as one of my indexers in order to use the elusive and newly "documented" `imdbid=` query. Is there another way to search using IMDB ID that doesn't require using `all` ?

- Existing documentation talks about various queries but non-developer users only know of `q=`.

> It was decided a while ago that we're not going to enable Discussions.

If we aren't going to enable discussions can someone add pertinent information to the ReadMe?

Thanks

**Comment by ilike2burnthing** [comment]
Ease off on the hyperbole, it's tiresome.

I can't find the issue, but I'm fairly sure proper API documentation has been previously discussed. IIRC, this was held off on because there was going to be some reworking of it. Plans and priorities changed, so it wasn't done.

I'll look at throwing together something quick and simple, but for now:

- search modes (e.g. `t=tvsearch`)
https://github.com/Jackett/Jackett/blob/8572ebf3b6353faec6b29fbad772383c6b6cd0d9/src/Jackett.Common/Models/TorznabQuery.cs#L50-L58

- supported sub-types of searches for each mode (e.g. `&imdbid=`)
https://github.com/Jackett/Jackett/blob/605b2a3cd9583082825334c5e985397284e11ba7/src/Jackett.Common/Models/TorznabCapabilities.cs#L206-L284

**Comment by ilike2burnthing** [comment]
Yea, when it comes to the search modes, it's just the optional parameters which we differ on, but there are a lot of extra functions and attributes in the Newznab spec that we don't touch.

**Comment by jprokos** [comment]
@ilike2burnthing

Hey thanks for following through on the additional info. Seeing that opens up a whole new world I didn't know existed within Jackett RSS rules. Didn't mean to be hyperbolic but did mean to stress that for non-developers this stuff can be a mystery and also suggest an option that would avoid bug reports by ignorant folks - like me.

It looks like qbittorrent is going to drop python search plugins and will come with Jackett only soon. A wave of torrenting noobs with many questions will undoubtedly follow.  A few more examples in the ReadMe might help avert an onslaught with the additional benefit of people not having to crawl bug reports for documentation...  my 2 ¢

thanks

**Comment by aidan-** [comment]
@ilike2burnthing  apologies for reviving an older thread, but this seems like the most relevant place to ask. Can the non-`torznab` endpoint make use of the [Search modes and parameters](https://github.com/Jackett/Jackett/#search-modes-and-parameters) options or is that exclusive to the `/torznab` path?  Alternatively, can the `torznab` path return JSON?

**Comment by garfield69** [comment]
>Can the non-torznab endpoint make use of the [Search modes and parameters](https://github.com/Jackett/Jackett/#search-modes-and-parameters) options or is that exclusive to the /torznab path?

the non-torznab endpoint **does not** make use of the [Search modes and parameters](https://github.com/Jackett/Jackett/#search-modes-and-parameters) options, which is exclusive to the /torznab API path.
The non-torznab endpoint is an internal Jackett interface between the Jackett HTML Dashboard and the Jackett Server, which converts the dashboard search query into a standard torznab t=search,q=term query for the indexer(s) being used in the query. 
While you are free to use that non-torznab interface if you want to, you should be aware that it is not supported as a public facing API, and its specs could change at any time based on whatever future needs the Jackett dashboard requires.

>Alternatively, can the torznab path return JSON?

Jackett implemented the most popular/common torznab API query options, based mostly on those first requested by the original Sonarr and Radarr apps. It has grown over the years to include additional query options, but still only provide results via the o=xml presentation.
The o=json has not been implemented thus far, see https://github.com/Jackett/Jackett/issues/921#issuecomment-271276823
