### ISSUE TITLE
[req]: AniLibria add RUSSIAN to end all titles

### ISSUE THREAD

**Issue by alikhanz** [Jackett/Jackett#14019]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

AniLibria it's only russian language tracker, but Sonarr determines as English. 

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/3951176/218861915-2de3100e-884a-479b-895c-eccc2cd95e12.png">

### Describe the solution you'd like

I think we can just add "addrussian" option for this indexer.
Strip russian option will be good too i think.

**Comment by garfield69** [comment]
v0.20.3127
