### ISSUE TITLE
Windows Installer v0.7.1432 is being flagged with Trojan by windows defender

### ISSUE THREAD

**Issue by TheDogg** [Jackett/Jackett#1401]
v0.7.1432

Trojan:Win32/Spursint.F!cl

The following error occurred: Error code 0x80508023. The program could not find the malware and other potentially unwanted software on this computer. 

Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
file:C:\Users\Administrator\Downloads\Jackett.Installer.Windows (2).exe.crdownload

**Comment by TheDogg** [comment]
Version v0.7.1422 does not do this

**Comment by kaso17** [comment]
There's no problem according to https://www.virustotal.com/de/file/64d1f439d1193b7c312bad1079d78455aafac77c998eca5e4e91be6bbfcd6b60/analysis/1495290122/

I also tried a windows 7 defender scan and had no problems:
Client Version:  6.1.7600.16385
Engine Version: 1.1.13704.0
Antispyware definitions: 1.243.711.0

Can you post a checksum of your downloaded file? Maybe it got infected during/after the download by something else?

**Comment by tbadaczewski** [comment]
Windows 10 is blocking newer releases as a virus, last release I was able to install was v0.7.1422.

**Comment by kaso17** [comment]
So this is only a problem on windows 10.
I thought windows defender signatures are the same on the different windows versions.
Does it block the zip file (no installer version) too?

**Comment by tbadaczewski** [comment]
Only blocks the windows installer not the zip with the binaries.

**Comment by kaso17** [comment]
Can someone provide the checksum(s) to double check the file hasn't been modified by something else?

**Comment by flightlevel** [comment]
Worked fine here on Windows 10
Checksum
`2fb0136c8e42f2e682516137704aac1b`
that was latest 1437
