### ISSUE TITLE
[req]: Integrate EZTV API 

### ISSUE THREAD

**Issue by jprokos** [Jackett/Jackett#14026]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

The problem, as far as I can tell, is I can't  take advantage of the API at EZTV that allows searching by `imdbid`.

https://eztv.re/api/

They don't appear to require an api login in or key

I have tried to use different RSS strings to accomplish that goal and they all have failed.

### Describe the solution you'd like

I would like to access shows on EZTV using the same method I use for RARBG:
```
http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=redacted&t=tvsearch&cat=5000&imdbid=tt0206501
```

### Describe alternatives you've considered

I have tried using `q=` instead but get many shows unrelated to the show I am trying to download... NOVA

Thank you for considering and if this capability exists thanks in advance for sharing

**Comment by garfield69** [comment]
Ah, good spotting. Saved me time.

**Comment by garfield69** [comment]
not suitable for indexing with jackett.
see https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
