### ISSUE TITLE
[req]: Dolphin Is Coming (DIC)

### ISSUE THREAD

**Issue by Siriussee** [Jackett/Jackett#14039]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Dolphin Is Coming (DIC)
- URL: https://dicmusic.club/
- Description: DIC is a Gazelle-based Private Torrent Tracker for Music
- Minimum Seeding Time and Minimum Ratio (if Private): MTS 72hrs, MR 0.6
- Additional Comments: 
I can help with implementing the DIC indexer. I currently don't have any invites available.
```

**Comment by ilike2burnthing** [comment]
Download, extract the relevant package for you (if you're currently using Docker you'll just have to install natively, e.g. on a Windows computer), add DICMusic, make sure you can successfully run a test, search, download, and that returned information is correct.

https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/7962/artifacts?artifactName=drop&api-version=7.0&%24format=zip

**Comment by Siriussee** [comment]
@ilike2burnthing I've tested and it worked. All test, search, and download torrent functionalities work well. The fetched data is identical to the DIC webpage.
Btw, I just forked Jackett, set up and wrote my indexer script, and then you've done all the work. Fantastic!

**Comment by garfield69** [comment]
v0.20.3160
