### ISSUE TITLE
[req]: Multiple languages in language specific indexers

### ISSUE THREAD

**Issue by alikhanz** [Jackett/Jackett#14038]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

For russian indexer we adding option "addrussian" for titles, but in fact results can be in different languages (including may not contain russian language). 

### Describe the solution you'd like

My suggestion is trying to parse languages string from result description, and combine this languages with "addrussian" option. I mean something like this pseudocode:
```
languageMap = {
'русский' => 'rus',
'украинский' => 'ukr',
'английский' => 'eng',
};
regex = <some language matching regexp>;
languages = [];

if (regex.contains(descritpion)) {
   matches = regex.match(description);
   foreach (matches as match) {
       if (languagesMap[match]) {
           languages[] = languagesMap[match];
       }
   }
} else {
    languages = addrussian === true ? ['rus'] : [];
}

title.append(languages.join(languages, ' '));
```

Examples for NNM Club tracker:
https://nnmclub.to/forum/viewtopic.php?t=1613062
https://nnmclub.to/forum/viewtopic.php?t=1613006
https://nnmclub.to/forum/viewtopic.php?t=1612689
https://nnmclub.to/forum/viewtopic.php?t=1612622
https://nnmclub.to/forum/viewtopic.php?t=1612587

<img width="545" alt="image" src="https://user-images.githubusercontent.com/3951176/219733940-5110f1af-53c0-4d34-9a93-5702028a02bf.png">

<img width="573" alt="image" src="https://user-images.githubusercontent.com/3951176/219734207-527f05f3-0746-4e26-8081-2b5ca6446216.png">

Yes, we won't cover all cases, but we'll make language detection more precise.
If it's possible i can try to add this logic, but for contribution i need examples cause im not C# developer.

**Comment by alikhanz** [comment]
Alternative solution it's avoid adding "RUS" for some categories. Like this:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/3951176/219736393-288dfe34-0d2e-4034-aec5-a381fde71196.png">

**Comment by ilike2burnthing** [comment]
We get information from the search results page, not the individual details pages of each torrent, otherwise that would involve as many as 100 or more additional requests in a short period of time (a quick way to get your account and/or IP flagged for bot activity).

As for using categories, while that could be viable for some indexers with a few categories, NNM has ~700, so we're not going to maintain something like that.

Thanks for the ideas.

**Comment by alikhanz** [comment]
@ilike2burnthing NNM has only 1 cat for "not russian movies". It's only 1 check for 1 category, seems not so difficult for maintain, but this make language detection more precise.

**Comment by ilike2burnthing** [comment]
See the use of `category_id` in https://github.com/Jackett/Jackett/commit/1f30b653d1eecf5022de920e99cd908f171a3af7.

**Comment by garfield69** [comment]
v0.20.3236
