### ISSUE TITLE
TorrentPotato Returning No Results

### ISSUE THREAD

**Issue by some-guy-23** [Jackett/Jackett#1404]
Jackett Version 0.7.1437.0

All my trackers are returning no results when movies are looked up via Radarr. I checked out the logs, and the trouble spot seems to be that when Jackett makes a request to OMDb the server. It returns a 401 error with the following content -

`{"Response":"False","Error":"No API key provided."}`

This seems to be related to OMDb's recent announcement that they are going private? - http://www.omdbapi.com/

Seems like from now on all request will require an API key. Is everyone experiencing this issue?

**Comment by flightlevel** [comment]
Yikes! They were getting 100 million requests an hour! https://www.patreon.com/posts/meeting-with-10066955

I don't think many people ever used CouchPotato with Jackett. Couchpotato is more like Sickbeard/SickRage than Sonarr/Raddar in the way it handles indexers. If you are using Radarr you should be using Torznab and not TorrentPotato

One option might be getting CouchPotato to send both IMDB and the movie title or looking for another API ???

**Comment by kaso17** [comment]
Seems like there's no way besides paying for it now.

I would suggest we replace omdbapi with direct queries to imdb. We should be able to use the code from @chibidev used in #1432 as a start.
I would suggest moving it to a separate helper class and add some simple caching.
@chibidev and @flightlevel what's your opinion on this?

**Comment by chibidev** [comment]
@kaso17 there's also a NuGet package that might help (untested): https://www.nuget.org/packages/imdbapi/

For a quick fix your suggestion sounds reasonable to me. However in the long run a stable API over IMDB might be a better solution (especially being aware of: https://github.com/ariejan/imdb). But I don't think that Jackett itself should provide the access. I'd suggest implementing UI for setting the OMDB API key, and use that. Those who want to use the IMDB fallback should become patrons to keep OMDB running (it's not that expensive).

**Comment by flightlevel** [comment]
I was think of creating a pull request for CouchPotato so that the request contains both the search term and IMDB id ?

**Comment by kaso17** [comment]
that certainly would reduce IMDB queries but we still would need the lookup for the aggregate indexer (or drop support for imdb queries if one of the member indexers doesn't support it).

**Comment by kaso17** [comment]
@RuudBurger what do you think about the suggestion from @flightlevel ? Would you accept a CP pull request which always sends the movie title (search parameter) and the imdbid?

**Comment by RuudBurger** [comment]
yeah sure, send It and Ill have a look

**Comment by chibidev** [comment]
In the meantime @kaso17 @flightlevel I have implemented my approach on chibidev/Jackett@cab8518. Once #1507 gets merged, I'll open the PR.
