### ISSUE TITLE
Red Head Sound

### ISSUE THREAD

**Issue by urtaevS** [Jackett/Jackett#14041]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Red Head Sound
- URL: https://redheadsound.ru/
- Description: Torrent tracker with movies/tv shows
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments:
```

**Comment by ilike2burnthing** [comment]
Multiple torrents per result but are only available on the details page. Not suitable - https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
