### ISSUE TITLE
[cloudtorrents] The response ended prematurely.

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14065]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
Environment version: 6.0.14 (C:\ProgramData\Jackett\)
Starting Jackett v0.20.3236
```

### Description

TEST fails for cloudtorrents
possibly related to #13958

### Logged Error Messages

```text
Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://cloudtorrents.com/latest)
Error Jackett.Common.IndexerException: Exception (cloudtorrents): The response ended prematurely.
```

**Comment by garfield69** [comment]
If I drop the useragent header from the indexer the TEST works again.

**Comment by garfield69** [comment]
for me ff305cdef7d588ca30c3e2ce01b9e5a0b829004d does not work on cloudtorrent

**Comment by condensacion3** [comment]
Doesn't this just mean the site owner doesn't want traffic from this app? Isn't it better to just remove the site from the app?

**Comment by ilike2burnthing** [comment]
> Doesn't this just mean the site owner doesn't want traffic from this app? Isn't it better to just remove the site from the app?

Could just be automated. It's also odd that they would purposefully block Prowlarr but not Jackett.

We usually give it a few tries before removing the indexer. Site admins are perfectly capable of contacting us directly (it's happened several times before), in which case the indexer would be removed immediately.

**Comment by ilike2burnthing** [comment]
@garfield69 damn, I tested it before making the commit. It went live with Prowlarr before us, so it had several hours in which to be picked up and blocked - https://github.com/Prowlarr/Indexers/commit/c46eaaf1658233f9dc3fac504eb9fcd6a77cba94.

Testing again, it's working fine by changing another single digit, or by using a user-configurable setting as per @mynameisbogdan's suggestion. I'd rather use the former wth a high request delay, like with acgsou - https://github.com/Jackett/Jackett/commit/2b34be06a77f64d1fd820e7e83755d4a8c5c422a. 

If that fails, I suggest we revert back to no delay and no UA, and just get Prowlarr to remove the indexer (and prevent it from being merged in future).

I'll make the change now and leave this open. @mynameisbogdan if you could merge the indexer change over on Prowlarr, so we can see if it gets blocked again after a few hours. Ta.

**Comment by ilike2burnthing** [comment]
Aaaaaand it's been blocked. I've removed the UA and requestDelay.

@mynameisbogdan not sure what the process is/would be to block an indexer from being merged for Prowlarr, but can you take a look at that? Thanks again.

**Comment by ilike2burnthing** [comment]
Looks to be working fine. For some reason they really just don't like Prowlarr.

**Comment by ilike2burnthing** [comment]
Spoke to soon, Windows and Linux UAs blocked. Removed the indexer.

**Comment by garfield69** [comment]
v0.20.3366
