### ISSUE TITLE
[req]: hdrezka russian tracker

### ISSUE THREAD

**Issue by alikhanz** [Jackett/Jackett#14060]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: HDRezka
- URL: https://rezka.cc
- Description: HDRezka
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: Nice torrent tracker
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/11316
