### ISSUE TITLE
[datascene-api] (updating) The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.: A task was canceled.

### ISSUE THREAD

**Issue by kretzu77** [Jackett/Jackett#14073]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using FlareSolverr: http://192.168.1.9:9117
Using proxy: Disabled
Running in Docker: Yes (on Synology DSM 7)
Jackett variant: linuxserver-Jackett v0.20.3269
```

### Description

Task canceled with message:
"The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.: A task was canceled."

### Logged Error Messages

```text
2023-02-23 21:03:22	Error	
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
2023-02-23 21:02:42	Error	
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```

### Screenshots

![2](https://user-images.githubusercontent.com/30404637/221007495-c049cc1e-4242-4724-b2ba-7959747bb909.jpg)
![1](https://user-images.githubusercontent.com/30404637/221007517-feec92ec-32e1-4291-aac1-f53c25c50a47.jpg)

**Comment by ilike2burnthing** [comment]
Working ok here, maybe a temporary issue. Try again.

If you're still having issues, are you able to access https://datascene.xyz/ in browser from the same IP and using the same DNS?

**Comment by ilike2burnthing** [comment]
From the same IP and using the same DNS?

Are other indexers working? Was DataScene (API) previously working?

**Comment by ilike2burnthing** [comment]
Try changing the DNS, e.g. `1.1.1.1` or `8.8.8.8`.

If that doesn't work, provide the output from the following command run within the container:
`curl -v https://datascene.xyz/api/torrents/filter?api_token=API_TOKEN&name=&sortField=created_at&sortDirection=desc&perPage=100&page=1`
(replacing `API_TOKEN` with your API token)

**Comment by kretzu77** [comment]
Solved after last version update without any changes in setup. Thank's a lot.
