### ISSUE TITLE
macOS update conflict, intermittent Gatekeeper issue

### ISSUE THREAD

**Issue by 101John** [Jackett/Jackett#14085]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: /Users/john/.config/Jackett
Running in Docker: No
Jackett variant: CoreMacOs
OS version: Unix 12.6.3 (64bit OS) (64bit process)
Environment version: 6.0.14 (/Applications/Jackett/)
Starting Jackett v0.20.3288
```

### Description

Attempted to manual update today and for the first time in over a year macOS Gatekeeper blocked the new version of Jackett that attempted to start up after download.

I had to turn off Gatekeeper  to get it to run.

Usually there is a macOS GUI notification asking to allow the software but in this instance that was not triggered and Jackett was blocked silently.

The solution was to turn off Gatekeeper, restart computer, and Jackett started up using my pre-existing `jacket.plist`.

I haven't tried turning Gatekeeper back on.

### Logged Error Messages

```text
n/a
```

**Comment by garfield69** [comment]
Unfortunately none of the current team have much experience on the osx platform. I used to have a Big Sur running on my windows VirtualBox which I used for simple testing of Jackett on mac, but that stopped working years ago when Oracle signed an agreement with Apple to prevent mac beta releases from working without a fully paid license.
I've gone back thought some tickets and found some volunteers that have responded to mac issues before, maybe we will get lucky.

@thebluepotato  @majorsl either of you have any insights into this macOS Monterey issue with Gatekeeper?

**Comment by thebluepotato** [comment]
I usually have auto updates on, so I can't say I've run into the issue. I assume that by updating manually you mean that you downloaded the files and pasted them in the folder.
You should try to uninstall Jackett using the script in the folder (to keep your configuration) and then use the install script again (which does take care of Gatekeeper issues).

**Comment by majorsl** [comment]
My solution is pretty much what I've suggested to others here and elsewhere: use Docker on the Mac. Jackett works great with Docker and if you're also using something like Sonarr, Radarr, Flaresolverr etc, having them all containerized makes maintaining them and potentially moving them to something else down the road easy.  Plus, you don't have to fight with Gatekeeper for every one (potentially).  Docker Desktop is a signed binary on the MacOS so it just works.

**Comment by jprokos** [comment]
> I usually have auto updates on, so I can't say I've run into the issue. I assume that by updating manually you mean that you downloaded the files and pasted them in the folder.
> You should try to uninstall Jackett using the script in the folder (to keep your configuration) and then use the install script again (which does take care of Gatekeeper issues).

Sorry, by "manually" I meant that I click the "Check for updates" button in the web client.

**Comment by ilike2burnthing** [comment]
Try @thebluepotato's reinstall solution anyway. Failing that, switch to Docker as suggested by @majorsl.
