### ISSUE TITLE
TorrentProject Torrent File Download Fails 

### ISSUE THREAD

**Issue by PaintPauller** [Jackett/Jackett#1408]
Jackett is not working with torrentproject for me. I think its caused from Jackett trying to grab a torrent file when only a magnet link exists.

Jackett when using manual search:
> This 127.0.0.1 page can’t be found
> 
> No webpage was found for the web address: http://127.0.0.1:9117/dl/torrentproject/7tzg8zjc8ctht6830ie41tcgi3lo45bo?path=aHR0cHM6Ly90b3JyZW50cHJvamVjdC5zZS8yOWMzNDIzN2QxMDAzMzc3ZmNlZDgxMjMzMzVkZGJjZjkzNGE3MDVmL0x1Y2lmZXItUzAyRTE3LTcyMHAtSERUVi14MjY1LVNoQWFOaUctbWt2LXRvcnJlbnQuaHRtbA2&file=Lucifer+S02E17+720p+HDTV+x265+ShAaNiG+mkv.torrent
> HTTP ERROR 404
> 

Jackett Log:
> May 22, 2017 09:16:18 PM	Error	
> Error downloading torrentproject https://torrentproject.se/29c34237d1003377fced8123335ddbcf934a705f/Lucifer-S02E17-720p-HDTV-x265-ShAaNiG-mkv-torrent.html

> May 22, 2017 09:16:18 PM	Error	
> On attempt 3 downloading from TorrentProject: Only 'http' and 'https' schemes are allowed.
> Parameter name: value

> May 22, 2017 09:16:17 PM	Error	
> On attempt 2 downloading from TorrentProject: Only 'http' and 'https' schemes are allowed.
> Parameter name: value

> May 22, 2017 09:16:17 PM	Error	
> On attempt 1 downloading from TorrentProject: Only 'http' and 'https' schemes are allowed.
> Parameter name: value

Jackett version:  0.7.1437.0
Windows: 10.0.14393 Build 14393

-------------------------------

**Comment by fryfrog** [comment]
If you're using a systemd unit file, try
```
# /etc/systemd/system/jackett.service.d/override.conf
[Service]
Environment=MONO_TLS_PROVIDER=legacy
```

If you're not, get `MONO_TLS_PROVIDER=legacy` into your start command.

The new default TLS provider has issues. I've seen it in Arch and someone on CentOS using the Mono rpm repositories.

If you're sonarr/radarr/other mono daemon is talking https to Jackett, you'll probably need to fix it too.

**Comment by ApteryxK** [comment]
Hi, I have got the exact same issue on windows. Fryfrog, i am sorry but I am a newbie, plus from what I see you are giving instructions for Unix based system. 
It is quite weird that it tries to get the .torrent while the magnet should just be fine.

**Comment by kaso17** [comment]
@PaintPauller is right, the definition is broken, there's no download link for torrent files. We've to generate a magnet link from the details URL (contains the infohash), similar to torrentz2.

**Comment by ApteryxK** [comment]
Great, is it an easy fix ?

**Comment by ApteryxK** [comment]
I am waiting for this to be fixed, how long should I expect ?

**Comment by PaintPauller** [comment]
any updates on this?

**Comment by kaso17** [comment]
fixed with 9aedd68f1c258009e9136937ab558b56b170fae8

**Comment by arkayenro** [comment]
the magnet link is being built with .Result.title but that isnt URL encoded so characters that should be encoded arent and its causing sonarr to barf

i dont know if theres an internal function to do URL encoding that you can wrap the title field in but i just pulled it out of the URL using the below (which sonarr doesnt barf on)

`

    fields:
      title:
        selector: span > a
      details:
        selector: span > a
        attribute: href
      maghash:
        selector: span > a
        attribute: href
        filters:
          - name: regexp
            args: "/(\\w+)/"
      magfile:
        selector: span > a
        attribute: href
        filters:
          - name: regexp
            args: "/\\w+/(.+)-torrent.html"
      magnet:
        text: "magnet:?xt=urn:btih:{{ .Result.maghash }}&dn={{ .Result.magfile }}.torrent&tr=http://182.176.139.129:6969/announce&tr=http://explodie.org:6969/announce&tr=http://tracker.mgtracker.org:2710/announce&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://tracker.pirateparty.gr:6969/announce&tr=udp://tracker.sktorrent.net:6969/announce&tr=udp://tracker.zer0day.to:1337/announce"
`

**Comment by kaso17** [comment]
nice catch.
73a3a9aca94e257b1db2a8c84d1998a315c29c87 should fix it using the new filters validfilename and urlencode
