### ISSUE TITLE
[REQ] HDChina

### ISSUE THREAD

**Issue by sethwarsh** [Jackett/Jackett#141]
Please add support for HDchina.club. I have invites available for testing. Email sethmw@gmail.com for invite.

Torznab categories below: ( I was a little confused doing this torznab listing because they have subcategories for medium type (like webdl or dvd, bluray, etc.), I did the best I could, but you probably want to have a quick look before implementing it. Use the site in google chrome and it's all translated to 100% english (it's mostly in english anyway but some of the categories are in chinese, but not in chrome).

Seth

/AddCategoryMapping("1", TorznabCatType.Console);
//AddCategoryMapping("1", TorznabCatType.ConsoleNDS);
//AddCategoryMapping("1", TorznabCatType.ConsolePSP);
//AddCategoryMapping("1", TorznabCatType.ConsoleWii);
//AddCategoryMapping("1", TorznabCatType.ConsoleXbox);
//AddCategoryMapping("1", TorznabCatType.ConsoleXbox360);
//AddCategoryMapping(1", TorznabCatType.ConsoleWiiwareVC);
//AddCategoryMapping("1", TorznabCatType.ConsoleXBOX360DLC);
//AddCategoryMapping("1", TorznabCatType.ConsolePS3);
//AddCategoryMapping("1", TorznabCatType.ConsoleOther);
//AddCategoryMapping("1", TorznabCatType.ConsoleOther);
//AddCategoryMapping("1", TorznabCatType.ConsoleOther);
//AddCategoryMapping("1", TorznabCatType.ConsoleOther);
//AddCategoryMapping("1", TorznabCatType.ConsoleOther);
//AddCategoryMapping("1", TorznabCatType.ConsoleOther);
//AddCategoryMapping("1", TorznabCatType.Console3DS);
//AddCategoryMapping("308", TorznabCatType.ConsolePSVita);
//AddCategoryMapping("1", TorznabCatType.ConsoleWiiU);
//AddCategoryMapping("39", TorznabCatType.ConsoleXboxOne);
//AddCategoryMapping("16", TorznabCatType.ConsolePS4);
//AddCategoryMapping("1", TorznabCatType.Movies);
//AddCategoryMapping("1", TorznabCatType.MoviesForeign);
//AddCategoryMapping("11", TorznabCatType.MoviesOther);
AddCategoryMapping("410", TorznabCatType.MoviesOther);
AddCategoryMapping("9", TorznabCatType.MoviesSD);
AddCategoryMapping("16", TorznabCatType.MoviesHD);
AddCategoryMapping("17", TorznabCatType.MoviesHD);
//AddCategoryMapping("1", TorznabCatType.Movies3D);
AddCategoryMapping("20", TorznabCatType.MoviesBluRay);
AddCategoryMapping("20", TorznabCatType.MoviesDVD);
//AddCategoryMapping("631", TorznabCatType.MoviesWEBDL);
AddCategoryMapping("408", TorznabCatType.Audio);
AddCategoryMapping("1", TorznabCatType.AudioMP3);
AddCategoryMapping("1", TorznabCatType.AudioVideo);
AddCategoryMapping("406", TorznabCatType.AudioVideo);
//AddCategoryMapping("1", TorznabCatType.AudioAudiobook);
//AddCategoryMapping("1", TorznabCatType.AudioLossless);
//AddCategoryMapping("1", TorznabCatType.AudioOther);
AddCategoryMapping("402", TorznabCatType.AudioOther);
//AddCategoryMapping("1", TorznabCatType.AudioForeign);
//AddCategoryMapping("1", TorznabCatType.PC);
//AddCategoryMapping("1", TorznabCatType.PC);
//AddCategoryMapping("1", TorznabCatType.PC0day);
//AddCategoryMapping("1", TorznabCatType.PCISO);
//AddCategoryMapping("1", TorznabCatType.PCMac);
//AddCategoryMapping("1", TorznabCatType.PCPhoneOther);
//AddCategoryMapping("4", TorznabCatType.PCGames);
AddCategoryMapping("27", TorznabCatType.PCPhoneIOS);
//AddCategoryMapping("1", TorznabCatType.PCPhoneAndroid);
AddCategoryMapping("405", TorznabCatType.TV);
AddCategoryMapping("409", TorznabCatType.TV);
//AddCategoryMapping("1", TorznabCatType.TVWEBDL);
AddCategoryMapping("41", TorznabCatType.TVWEBDL);
AddCategoryMapping("25", TorznabCatType.TVFOREIGN);
//AddCategoryMapping("1", TorznabCatType.TVFOREIGN);
AddCategoryMapping("41", TorznabCatType.TVSD);
AddCategoryMapping("1", TorznabCatType.TVSD);
AddCategoryMapping("13", TorznabCatType.TVHD);
AddCategoryMapping("13", TorznabCatType.TVHD);
AddCategoryMapping("405", TorznabCatType.TVOTHER);
AddCategoryMapping("15", TorznabCatType.TVSport);
//AddCategoryMapping("1", TorznabCatType.TVAnime);
AddCategoryMapping("5", TorznabCatType.TVDocumentary);
//AddCategoryMapping("1", TorznabCatType.XXX);
//AddCategoryMapping("1", TorznabCatType.XXXDVD);
//AddCategoryMapping("1", TorznabCatType.XXXWMV);
//AddCategoryMapping("1", TorznabCatType.XXXXviD);
//AddCategoryMapping("1", TorznabCatType.XXXx264);
//AddCategoryMapping("1", TorznabCatType.XXXOther);
//AddCategoryMapping("1", TorznabCatType.XXXImageset);
//AddCategoryMapping("1", TorznabCatType.XXXPacks);
AddCategoryMapping("16", TorznabCatType.Other);
AddCategoryMapping("409", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.Other);
//AddCategoryMapping(1", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.OtherMisc);
//AddCategoryMapping("1", TorznabCatType.OtherHashed);
AddCategoryMapping("404", TorznabCatType.Books);
AddCategoryMapping("404", TorznabCatType.BooksEbook);
AddCategoryMapping("404", TorznabCatType.BooksComics);
AddCategoryMapping("404", TorznabCatType.BooksComics);
AddCategoryMapping("404", TorznabCatType.BooksComics);
AddCategoryMapping("404", TorznabCatType.BooksMagazines);
AddCategoryMapping("404", TorznabCatType.BooksTechnical);
AddCategoryMapping("404", TorznabCatType.BooksOther);
AddCategoryMapping("404", TorznabCatType.BooksForeign);

Thanks for all of your hard work!

**Comment by VadVoci** [comment]
I can not see this tracker in Indexers.
It exists in the Jackett db Indexers? is still valid?

**Comment by kaso17** [comment]
It's not yet supported, please send an invite to kaso1717 -at- gmail.com and I'll add it.

**Comment by armani316** [comment]
I have contacted @sethwarsh about his invite offer. He should be able to provide invites soon.

**Comment by armani316** [comment]
For any Chinese to English translation, I'd recommend this wbesite over Google Translate. 
http://fanyi.baidu.com/

Translations are much more accurate and better phrased.

**Comment by armani316** [comment]
@sethwarsh No word yet from the HDChina sysop?

**Comment by RoloSoze** [comment]
I believe HDChina's invite system has just opened up for the first time in over six months. If anyone would like to help add HDChina to Jackett, please send an invite to @kaso17 on:

kaso1717 -at- gmail.com

I believe you can exchange 100K BPs for 1 invite! Thanks, guys!

**Comment by RoloSoze** [comment]
I believe HDChina's invite system has just opened up for the first time in over six months. If anyone would like to help add HDChina to Jackett, please send an invite to @kaso17 on:

kaso1717 -at- gmail.com

I believe you can exchange 200K BPs for 1 invite, and this will only be available for the next 10 hours or so! Thanks guys!

**Comment by RoloSoze** [comment]
Added with #1251 Thanks, @adamwinn!

**Comment by RoloSoze** [comment]
Temporarily down but should come back up soon.

**Comment by ilike2burnthing** [comment]
https://hdchina.org/ - This site is down for maintenance

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://hdchina.org/login.php
```
温馨提示：该网站暂时无法进行访问
原因一：根据工信部相关法规，您尚未进行备案；
原因二：根据工信部相关法规，您当前的接入商不是本司；
原因三：您的网站可能存在不适宜传播的信息，请联系网站管理员。
本页面为默认提示页面，如网站存在以上问题请及时进行处理。
谢谢合作！
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
I'm still seeing that unavailable notice. But all I want to really check is the aboutnexus.php page, can you check? Thanks.

**Comment by ilike2burnthing** [comment]
Oh, it's down again.

**Comment by ilike2burnthing** [comment]
back up

In case it goes down again, aboutnexus.php is annoyingly inaccessible without an account, but the login page does state - `Powered by NexusPHP Version 045f966`.

**Comment by ilike2burnthing** [comment]
https://hdchina.org/ - Connection timed out Error code 522

**Comment by garfield69** [comment]
@sethwarsh  do you have any news about hdchina, is the site broken, gone, moved to a new domain?
in a couple days we will remove the indexer.

**Comment by garfield69** [comment]
v0.21.1548
