### ISSUE TITLE
les-cinephiles.nl - need to click thanks button before download

### ISSUE THREAD

**Issue by xfouloux** [Jackett/Jackett#14101]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using prowlarr but it is the same for jackett
```

### Description

They added the need to click on thanks button before download

we need a before block inside download, something like this (has to be modified)
```
  before:
    path: "{{ .DownloadUri.AbsoluteUri }}"
    method: .....
    inputs:
      .....
      ....
```

we need to click on button identified by this element :
```
<input type="button" value="Dire Merci" id="refresh">
```

it's been a long time i didn't do some jackett debug, i need to setup my dev jackett again =p ! so i'll try to fix that in the comming days unless someone is faster than me ;)

### Logged Error Messages

```text
i don't have any debug log from prowlarr weirdly.
```

### Screenshots

![image](https://user-images.githubusercontent.com/9778409/221518824-58f18ddf-3c30-49c9-aaed-160977a68741.png)

**Comment by garfield69** [comment]
v0.20.3403
