### ISSUE TITLE
a fix for torrent9 : not a request ( when movie titles dont respect naming rules )

### ISSUE THREAD

**Issue by hed0nist** [Jackett/Jackett#1410]
Hi devs.
Sorry for my english and for the way i use to give this little contribution, as i ignore all the "pulls" and github environnement.

Using Radarr i noticed that torrent9 was returning no results as the site doesn't use the naming rules : Title.Date.Lang.
It is a known problem, i saw a thread referring to this.
I found a way to get it working with Radarr, hope it will help another (french) people or some beginners.

Here is the modified code

>    
    fields:
      site_date:
        selector: td:nth-child(1) a
        filters:
          # date is at the end of the title, so we get it and name it site_date
          - name: regexp
            args: "(\\w+)$"
      title:
        selector: td:nth-child(1) a
        filters:
          # now we put the date at the right place according scene naming rules using .Result.site_date
          - name: replace
            args: ["FRENCH", "{{ .Result.site_date }} FRENCH"]
          - name: replace
            args: ["TRUEFRENCH", "{{ .Result.site_date }} TRUEFRENCH"]
          - name: replace
            args: ["VOSTFR", "{{ .Result.site_date }} VOSTFR"] 
          # and we delete it at the end
          - name: re_replace
            args: ["(\\w+)$", ""]

**Comment by Nibeck1309** [comment]
hello,

Witch file do you edit for your modif?

**Comment by hed0nist** [comment]
@Nibeck1309 
You have to edit the file Jackett/Definitions/torrent9.yml ( with a text editor )
Be careful, you have to respect spaces and syntax ... make a copy before editing your file.
The code i gave is only a part of the entire content. You will find the place easily.
Maybe devs will change it in a future update.

**Comment by Nibeck1309** [comment]
This fix works for provider torrent9 with radarr or couchpotato.

Can you add in the next release?

**Comment by kaso17** [comment]
added with #1500 
Thank you @hed0nist
