### ISSUE TITLE
BrokenStones

### ISSUE THREAD

**Issue by ItsME6969** [Jackett/Jackett#14116]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.0.x
Using proxy: Disabled
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
Environment version: 6.0.14 (/app/Jackett/)
```

### Description

Just a minr change ... Broken stones changed domain to https://broken-stones.club/

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (brokenstones): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://broken-stones.club/">here</a>.</p>
</body></html>
```

**Comment by garfield69** [comment]
Thanks.

**Comment by garfield69** [comment]
v0.20.3444
