### ISSUE TITLE
[yggtorrent] (updating) Name does not resolve (www6.yggtorrent.lol:443): Name does not resolve

### ISSUE THREAD

**Issue by C2P0** [Jackett/Jackett#14124]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://XXX.XXX.X.X:49163
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.3451-ls96)
File /etc/issue: Welcome to Alpine Linux 3.17
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.10.60.0 (64bit OS) (64bit process)
Environment version: 6.0.14 (/app/Jackett/)
Starting Jackett v0.20.3451
```

### Description

Ygg no longer works on Jackett even with Flaresolverr. Website down?

### Logged Error Messages

```text
An error occurred while updating this indexer
Name does not resolve (www6.yggtorrent.lol:443): Name does not resolve
Click here to open an issue on GitHub for this indexer.
```

### Screenshots

![image](https://user-images.githubusercontent.com/9315405/222935168-0bafee47-9904-466d-8acd-19555d7d729a.png)

**Comment by ilike2burnthing** [comment]
If other indexers are working then try changing your DNS (e.g. 1.1.1.1 or 8.8.8.8).

**Comment by C2P0** [comment]
Thank you, I changed the DNS of the Network configuration of my container and it works again!

**Comment by Darkalll** [comment]
> Thank you, I changed the DNS of the Network configuration of my container and it works again!

Hi , how did you change the DNS of your container ? i can't find it in my container manager
