### ISSUE TITLE
[req]: Lightning-Tor.org indexer request

### ISSUE THREAD

**Issue by Prankish8407** [Jackett/Jackett#14159]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hi,

Would it be possible to add the following torrent site to Jacket: https://lightning-tor.org/ its a dutch tracker

### Describe the solution you'd like

Have https://lightning-tor.org/ implemented, i think it uses the same cookie grab option as extremetorrents.org thats already indexed.

**Comment by garfield69** [comment]
replaced by 14160
