### ISSUE TITLE
[req]: EliteTorrent-pl

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14155]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: EliteTorrent-pl
- URL: https://elitetorrent.pl/
- Description: EliteTorrent-pl is a POLISH semi-private site for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): TBD
- Additional Comments: 
Engine: similar to vtorrent
Registration currently open
```

**Comment by garfield69** [comment]
@ilike2burnthing  can you find any info in MR MST, I've can't seem to find anything?

**Comment by ilike2burnthing** [comment]
Nope. I can't even find any torrents using their tracker, just all public ones, some IPs, and DHT is enabled. I downloaded 1 about an hour ago and there's no record of it on my profile.

Each torrent has a poster and description though, so it's not just a DHT crawler.

**Comment by garfield69** [comment]
I wonder then if it's semi-private, just like vtorrent, which is also Polish and uses the same engine.

**Comment by ilike2burnthing** [comment]
Would be my guess.

**Comment by garfield69** [comment]
I'll switch it to semi now and go back to private if they ever close the signup.

**Comment by garfield69** [comment]
v0.20.3604

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13741#issuecomment-1642636743

**Comment by garfield69** [comment]
v0.21.510
