### ISSUE TITLE
[req]: How do we integrate jackett to qbittorrent 

### ISSUE THREAD

**Issue by scotrod** [Jackett/Jackett#14161]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

So, I couldn't find any information on the Internet around how to integrate Jackett with qbittorrent while both of them are running on TrueNAS. 
Where exactly do we have to put the API key, once it is pulled out of Jackett?

### Describe the solution you'd like

Explination of where exactly are the users supposed to insert the Jackett key into qbittorrent config, while running them both on TrueNAS.

**Comment by ilike2burnthing** [comment]
https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin

**Comment by scotrod** [comment]
> https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin

Thank you, this just still doesn't solve how to allow jackett to "allow remote calls and its IP"?

**Comment by ilike2burnthing** [comment]
Enable `External access` in Jackett.

**Comment by scotrod** [comment]
> Enable `External access` in Jackett.

dum-dum me. Thank you for your help, and sorry for spamming the issues section!
