### ISSUE TITLE
[req]: add new polish indexer https://helltorrents.com/

### ISSUE THREAD

**Issue by 60plus** [Jackett/Jackett#14162]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hello. 
Any chance to add decent polish tracker https://helltorrents.com/
it is semi private with registration torrent indexer

### Describe the solution you'd like

adding tracker https://helltorrents.com/

### Describe alternatives you've considered

not adding tracker https://helltorrents.com/

**Comment by garfield69** [comment]
please use the correct form https://github.com/Jackett/Jackett/issues/new?assignees=&labels=&template=indexer-request.yml&title=%5Breq%5D%3A+
thanks.
