### ISSUE TITLE
[REQ] Cesars Torrents/LACAVERNE.US

### ISSUE THREAD

**Issue by nikogaug** [Jackett/Jackett#1417]
Indexer Name : Cesars Torrents
Type : General
URL : [http://cesars-torrents.com](http://cesars-torrents.com)
Indexer Language : French
Invite : Available (I can give you one if you need)

Category Mapping : 
//Apps - Linux,  Apps - Log et Jeu PC, Apps - Windows
AddMultiCategoryMapping(TorznabCatType.PC, 20, 91, 18);
//Apps - Mac
AddCategoryMapping("88", TorznabCatType.PCMac);
//Apps Android - appli/jeux samrtphone et table
AddCategoryMapping("70", TorznabCatType.PCPhoneAndroid);
//Dessin Animé - All, Films - Bdrip et Brrip, Films - VOSTFR, Films - WebTV, Music - Comédie Musical
AddMultiCategoryMapping(TorznabCatType.Movies, 28, 56, 53, 93, 97);
//Enquètes films - Concert/spectacle, Enquètes films - Documentaire
AddMultiCategoryMapping(TorznabCatType.MoviesOther, 69, 9);
//Films - HD, Films - HD TV, Films - hdlight 1080p., Films - hdlight 720p
AddMultiCategoryMapping(TorznabCatType.MoviesHD, 63, 92, 82, 81);
//Films BluRay 1080p, Fims - BluRay 720p, Films - NlueRay*265
AddMultiCategoryMapping(TorznabCatType.MoviesBluRay, 42, 71, 55);
//Films - DVD R5, Films - DVDr, Films Dvdrip VF
AddMultiCategoryMapping(TorznabCatType.MoviesDVD, 86, 75, 2);
// Films - Screener
AddCategoryMapping("84", TorznabCatType.MoviesSD);
//Films - Serie.VOSTFR
AddCategoryMapping("59", TorznabCatType.TVFOREIGN);
//Films Série PACK, Films - Série VF
AddMultiCategoryMapping(TorznabCatType.TV, 48, 6);
//Films - VO
AddCategoryMapping("89", TorznabCatType.MoviesForeign);
//Films - blu-ray 3D
AddCategoryMapping("58", TorznabCatType.Movies3D);
//Jeux - Jeux consoles tout genre
AddCategoryMapping("72", TorznabCatType.Console);
//Jeux - PC
AddCategoryMapping("10", TorznabCatType.PCGames);
//Livre - E-Books livres et Epub, Sexy - E-Books X
AddMultiCategoryMapping(TorznabCatType.Books, 66, 67);
//Livre- Presse
AddCategoryMapping("83", TorznabCatType.BooksMagazines);
//Music - Clip Vidéo
AddCategoryMapping("98", TorznabCatType.AudioVideo);
//Music - Flac, Music - karaoke
AddMultiCategoryMapping(TorznabCatType.Audio,96 ,87);
//Music - MP3
AddCategoryMapping("95", TorznabCatType.AudioMP3);
//Sexy - XXX
AddCategoryMapping("47", TorznabCatType.XXX);
//Sport - Sport
AddCategoryMapping("90", TorznabCatType.TVSport);

**Comment by bidulle95** [comment]
+1

**Comment by Khogniak** [comment]
Hi @nikogaug ,
I'm interested in that kind of tracker and I can make it work with Jackett.
Just need an invite to do that.

**Comment by nikogaug** [comment]
Hi Khogniak.
Thank you. The site got new modification and the forum isn't ready. I need it to request an activation of a invitation.
Another thing is that I don't see any work of you on the Jackett project, and I have to be sure that you work on it before giving an invitation.
I hope you will understand my precautions.

**Comment by Khogniak** [comment]
No problem, I understand.
Please have a look here : https://github.com/Jackett/Jackett/pull/1536
It must be trackers you had heard of

**Comment by nikogaug** [comment]
Ok thanks. And sorry for that. I will ask for an invite.

**Comment by nikogaug** [comment]
Hello Khogniak. the rules for invitations have change. I have to become an uploader before I can send my invitations. Sorry for that. I will post e message here when I were an uploader.

**Comment by nikogaug** [comment]
Hello,
The site have change. Now it's [http://lacaverne.us](http://lacaverne.us).
But it's very difficult to have an invitation. Is it possible that I give you my account ?
Great thanks.
Nikogaug

**Comment by nikogaug** [comment]
I close this issue because the tracker has been down for a while.
