### ISSUE TITLE
[req]: Добавьте возможность использовать pxoxy.pac файлы

### ISSUE THREAD

**Issue by xPomaHx** [Jackett/Jackett#14171]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Сложно обходить блокировки иначе

### Describe the solution you'd like

Чтобы было удобно использовать антизапрет

**Comment by garfield69** [comment]
this is a duplicate request of #11693

**Comment by Omegaplexx** [comment]
Установи OpenVPN на компьютер и добавь в него профиль Антизапрета. Подключаешься к нему и ищешь торренты без блокировок.
https://openvpn.net/community-downloads/
https://antizapret.prostovpn.org/
