### ISSUE TITLE
[req]: THOR'S LAND (eThor)

### ISSUE THREAD

**Issue by OXYDER** [Jackett/Jackett#14187]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: THOR'S LAND
- URL: https://ethor.tk
- Description: eThor is a French Generalist Private Torrent Tracker
- Minimum Seeding Time and Minimum Ratio: MST 48hrs, MR 0.80
- Additional Comments: Hidden ReCaptcha V3 at login and need a invite link for signup.
```

**Comment by ilike2burnthing** [comment]
Is this a resurrected version of the tracker that was killed off in 2020? https://github.com/Jackett/Jackett/commit/3169ac6cb430494b5e63c057593b2f8f684a87f5

**Comment by OXYDER** [comment]
New site, new team. Not resurrected but a new project with the same name ;)

**Comment by garfield69** [comment]
v0.20.3681

**Comment by lepasvite** [comment]
I would like to have an invitation to this site,

**Comment by garfield69** [comment]
This is not a forum for soliciting invitations, it a support site for the Jackett app.
Please look elsewhere.

**Comment by geznar** [comment]
i need a invit please. j'ai besoin d'un invite svp. j'etais sur l,ancien thorland avant et ma vie est completement fini sans ce tracker @OXYDER

**Comment by garfield69** [comment]
This is a support site for the Jackett app and not a forum for soliciting invites.
Please look elsewhere.

**Comment by geznar** [comment]
i dont know where to look :( @garfield69

**Comment by garfield69** [comment]
https://ethor.tk/ Web server is down Error code 521

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://ethor.tk/ cloudflare Bad gateway Error code 502

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
online

**Comment by Frenzer09** [comment]
hi
i like invitation
thanks

**Comment by ilike2burnthing** [comment]
This isn't an invite forum, don't use it as one.

**Comment by garfield69** [comment]
https://ethor.tk/ cloudflare Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://ethor.tk/ cloudflare Web server is down Error code 521

**Comment by garfield69** [comment]
online

**Comment by iron3433432343** [comment]
Allo!i'm an ancient user of ethor net,i had a very good ratio,i have been on ethor for about 12 years.ethor miss me a lot.yesterday i found about thor's land that as apparently reopen last summer!!i was wondering if it could be possible to get an invitation for thor's land for somebody!!thank you

**Comment by garfield69** [comment]
This is a support site for the Jackett app and not a forum to solicit invitations. Please look elsewhere.

**Comment by garfield69** [comment]
https://ethor.tk/ DNS_PROBE_FINISHED_NXDOMAIN (DNS Lookup Error)

**Comment by garfield69** [comment]
@OXYDER  Do you have any news on the state of Thor's land, is the site GONE, just BROKEN, or moved to a new DOMAIN?
We will be removing the indexer in a week or so if the site remains offline.

**Comment by OXYDER** [comment]
Is GONE, you can remove them.

**Comment by garfield69** [comment]
v0.22.71
