### ISSUE TITLE
[yggtorrent] (testing) Test search in YGGtorrent => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by helsan74** [Jackett/Jackett#14182]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTPWebClient
FlareSolverr: enabled url
No Proxy
Docker Yes
OS Ubuntu 20.04 Server LTS
Jackett Version v0.20.3664
```

### Description

After update to v0.20.3664 able to add the Indexer but still not able to connect.

### Logged Error Messages

```text
Error | System.Exception: Test search in YGGtorrent => Found no results while trying to browse this tracker
Test search in YGGtorrent => Found 0 releases [19605ms]
```

**Comment by ilike2burnthing** [comment]
Remove the indexer, restart the Docker container, re-add the indexer, run another test search.

If you still get no results, see the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

If you still get no results, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by helsan74** [comment]
Thanks It's working now!

Keep up the great work!
