### ISSUE TITLE
Update Jackett Truchart's container

### ISSUE THREAD

**Issue by scotrod** [Jackett/Jackett#14183]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Truenas Scale
```

### Description

Currently, the latest version of Jackett's Docker container within Truecharts is v0.20.2297 which was released last year. Perhaps we can make a process to distribute the newer releases to Truecharts repository as well?

### Logged Error Messages

```text
No error messages.
```

**Comment by ilike2burnthing** [comment]
We're not responsible for any Docker images (LS.io, binhex, truecharts, etc.), you'd need to contact them. There seems to be plenty of ways to do that - https://artifacthub.io/packages/helm/truecharts/jackett
