### ISSUE TITLE
[InternetArchive] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14180]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

The InternetArchive site is offline

### Logged Error Messages

```text
https://archive.org/ returns

Temporarily Offline
Internet Archive services are temporarily offline.

Please check our Twitter feed for the latest information.

We apologize for the inconvenience.
```

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://archive.org/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://archive.org/ Temporarily Offline

**Comment by AARON8888** [comment]
Hi @garfield69. Site is working for me some days ago. Can you fix in Jackett?

**Comment by garfield69** [comment]
v0.22.860

**Comment by garfield69** [comment]
https://archive.org/ > Temporarily Offline

**Comment by garfield69** [comment]
online
