### ISSUE TITLE
[BitTorrentFiles] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14181]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

The BitTorrentFiles site is offline

### Logged Error Messages

```text
https://bittorrentfiles.me/ returns ERR_CONNECTION_REFUSED
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
BTF have implemented an API
I shall research and see if I can get it working to replace our current HTML scraper indexer

**Comment by garfield69** [comment]
The API is currently not a compete replacement for the html indexer, as the torrent search returns only the basic details
```
  "id": 1234567,
  "category": 41,
  "numfiles": 234,
  "seeders": 1,
  "leechers": 1,
  "snatched": 0,
  "added": 1727325469,
  "size": 732552892,
  "name": "a long title -AUDiOBOOK-WEB-MP3-DE-2024-PaZ",
  "status": "ACTIVE"
```
Missing is the imdb, download, types (free, half, 2x).    The details link is also missing but that could be built from the id and web site details url, like we do for some other indexers.

Its only by fetching each torrent by id that you get more data (as shown in the docs below)
```
"id": 0,
"name": "string",
"status": "ACTIVE",
"category": 0,
"numfiles": 0,
"seeders": 0,
"leechers": 0,
"snatched": 0,
"size": 0,
"imdb": "string",
"added": 0,
"pretime": 0,
"download": "string",
"types": [
"HALFDOWN"
]
```
the download string is likely the api download string, which the indexer would need to use via the API. I expect using a built download url similar to the details link would not work as the indexer is not logged in.

**Comment by garfield69** [comment]
I cant find the API docs anymore and a forum entry states that the API as been deleted again. Closing.
Another entry dated 8/8/2025 implies that the API will be re-introduced, but clearly, so far, that has not happened.
