### ISSUE TITLE
Blackhole directory and Check for updates failing.

### ISSUE THREAD

**Issue by leetwanker** [Jackett/Jackett#142]
I just updated to the newest release of Jackett
```
$ mono /opt/jackett/JackettConsole.exe -v
Jackett v0.7.75.0
```
I'm still getting the same error `Request to Jackett server failed` when trying to save to blackhole directory. (I also get the error when clicking "Check for updates" in the WebUI) One thing I'm confused about, and this may be related to the problem somehow, is that the version number in the WebUI still says `Jackett Version 0.6.45.0`. 

Is it possible I upgraded wrong, an old conf file or something?

**Comment by flightlevel** [comment]
Very odd, can you try deleting all files in the Jackett folder and then redownload the latest release

**Comment by leetwanker** [comment]
That's basically what I did when I upgraded earlier. I moved the /opt/jackett directory into a backup directory in ~, so I would have it if anything went wrong. I'll give it another shot and post the results.

**Comment by leetwanker** [comment]
Ah, I think I figured it out. Even though I stopped the service and deleted the jackett directory the process never actually stopped. I had to manually kill it just now after reinstalling the latest version. Problem solved :)
