### ISSUE TITLE
Run jackett not as a service (from the AUR)

### ISSUE THREAD

**Issue by FrenchGithubUser** [Jackett/Jackett#14207]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Artix Linux (arch linux based), openrc 
```

### Description

Posting here, because Idk where else I could ask, sorry if it is the wrong place.

I installed [jackett](https://aur.archlinux.org/packages/jackett) from the aur. However, I don't know if it is possible to simply run the binary (as it would be possible when downloading it from the releases). Is it only possible to run it as a service if downloaded from the aur ?

`which jackett` and `pacman -Qo jackett` both do not find it.

Btw, I also tested with jackett-mono with the same results

### Logged Error Messages

```text
none
```

**Comment by ilike2burnthing** [comment]
@ngosang / @txtsd ping

**Comment by txtsd** [comment]
This should do it:
`runuser -u jackett -- /usr/lib/jackett/jackett --NoRestart --NoUpdates --DataFolder /var/lib/jackett`

I actually do it this way here: https://github.com/txtsd/aur_jackett_updater/blob/e250b6f53f0d906006211dc14be16d052dd621a2/.github/workflows/update_pkgbuild.yml#L131

If you want to run `jackett-mono`, do it this way:
`runuser -u jackett -- /usr/bin/mono --debug /usr/lib/jackett/JackettConsole.exe --NoRestart --NoUpdates --DataFolder /var/lib/jackett`

See: https://github.com/txtsd/aur_jackett_updater/blob/e250b6f53f0d906006211dc14be16d052dd621a2/.github/workflows/update_pkgbuild.yml#L143

<details>
<summary></summary>
This is my first time coming across a support request from a non-systemd user.
</details>

**Comment by FrenchGithubUser** [comment]
Thanks, that seems to work well ! However, I used to run jackett from the downloaded release and its configuration was stored in `.config/Jackett/` and it does not seem to be used anymore with the aur version. Is this normal behavior ?

**Comment by txtsd** [comment]
If you manually download and run it, that should be where the config is stored. However the AUR packages are configured to run it explicitly as a service.

**Comment by FrenchGithubUser** [comment]
I see, but then do you know where I should move the existing configuration so the aur package can use it too ?

**Comment by garfield69** [comment]
I don't know if this can apply to the AUR packages, but jackett on linux flavoured systems can specify the data folder via the XDG_CONFIG_HOME environment variable.

**Comment by fryfrog** [comment]
Its just like any other program, run it how you want as the user you want pointed at the config folder you want. There's nothing special about jackett or any of the other software. You could modify the user/group in the service file to run as yourself, you could modify the data folder argument to point at what ever folder you want. You're the boss, do what you like. Just don't forget that what ever user/group you run it as will need read/write access to its data folder. And w/o write access to the install folder, built in update won't work (but since you're using AUR package, you shouldn't built in updater anyway).
