### ISSUE TITLE
[req]: NextJAV

### ISSUE THREAD

**Issue by saw1543** [Jackett/Jackett#14227]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: nextjav
- URL: https://nextjav.com/
- Description:  jav porn
- Minimum Seeding Time and Minimum Ratio (if Private): public
- Additional Comments: torrent's and search engine working.
```

**Comment by saw1543** [comment]
![resim](https://user-images.githubusercontent.com/107757665/230498339-1bd7b13f-f0d1-4a4a-a790-d68f7442f7e2.png)
![resim](https://user-images.githubusercontent.com/107757665/230498485-32d8c76a-6cdb-481d-951f-7e5b8fa2fa26.png)
![resim](https://user-images.githubusercontent.com/107757665/230498557-a170be3b-ae72-4bba-af93-fb078f38d31f.png)

**Comment by garfield69** [comment]
v0.20.3817

**Comment by garfield69** [comment]
https://nextjav.com/ 
![image](https://github.com/Jackett/Jackett/assets/6933240/1b59f17d-e590-4f1e-bb0b-65e684e6322b)

**Comment by garfield69** [comment]
v0.22.315
