### ISSUE TITLE
Unable to add Alpharatio 

### ISSUE THREAD

**Issue by jdrewsteiner** [Jackett/Jackett#1422]
Error when trying to add Alpharatio tracker: " Configuration failed: An error occurred while sending the 

Log: 
May 26, 2017 06:29:28 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
May 26, 2017 06:29:28 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
May 26, 2017 06:29:28 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
May 26, 2017 06:29:28 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
May 26, 2017 06:29:28 PM	Info	
HttpActionBinding ExecuteBindingAsync 
May 26, 2017 06:29:28 PM	Info	
HttpActionBinding ExecuteBindingAsync 
May 26, 2017 06:29:28 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
May 26, 2017 06:29:28 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
May 26, 2017 06:29:28 PM	Info	
ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
May 26, 2017 06:29:28 PM	Info	
ApiControllerActionSelector SelectAction 
May 26, 2017 06:29:28 PM	Info	
AdminController ExecuteAsync 
May 26, 2017 06:29:28 PM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
May 26, 2017 06:29:28 PM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
May 26, 2017 06:29:28 PM	Info	
DefaultHttpControllerActivator Create 
May 26, 2017 06:29:28 PM	Info	
HttpControllerDescriptor CreateController 
May 26, 2017 06:29:28 PM	Info	
DefaultHttpControllerSelector SelectController Admin
May 26, 2017 06:29:28 PM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
May 26, 2017 06:29:28 PM	Info	
  http://192.168.0.200:9117/Admin/GetLogs?_=1495837657762
May 26, 2017 06:28:29 PM	Info	
AdminController Dispose 
May 26, 2017 06:28:29 PM	Info	
AdminController Dispose 
May 26, 2017 06:28:29 PM	Info	
  Content-type='application/json; charset=utf-8', content-length=92
May 26, 2017 06:28:29 PM	Info	
AdminController ExecuteAsync 
May 26, 2017 06:28:29 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync 
May 26, 2017 06:28:29 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()'
May 26, 2017 06:28:29 PM	Info	
ApiControllerActionInvoker InvokeActionAsync 
May 26, 2017 06:28:29 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
May 26, 2017 06:28:29 PM	Error	
Exception in Configure
May 26, 2017 06:28:29 PM	Debug	
IWebClient.GetString(Url:https://alpharatio.cc/login.php)
May 26, 2017 06:28:29 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Configure()'
May 26, 2017 06:28:29 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='Configure()'
May 26, 2017 06:28:29 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
May 26, 2017 06:28:29 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Configure()'
May 26, 2017 06:28:29 PM	Info	
HttpActionBinding ExecuteBindingAsync 
May 26, 2017 06:28:29 PM	Info	
HttpActionBinding ExecuteBindingAsync 
May 26, 2017 06:28:29 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
May 26, 2017 06:28:29 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
May 26, 2017 06:28:29 PM	Info	
ApiControllerActionSelector SelectAction Selected action 'Configure()'
May 26, 2017 06:28:29 PM	Info	
ApiControllerActionSelector SelectAction 
May 26, 2017 06:28:29 PM	Info	
AdminController ExecuteAsync 
May 26, 2017 06:28:29 PM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
May 26, 2017 06:28:29 PM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
May 26, 2017 06:28:29 PM	Info	
DefaultHttpControllerActivator Create 
May 26, 2017 06:28:29 PM	Info	
HttpControllerDescriptor CreateController 
May 26, 2017 06:28:29 PM	Info	
DefaultHttpControllerSelector SelectController Admin
May 26, 2017 06:28:29 PM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
May 26, 2017 06:28:29 PM	Info	
  http://192.168.0.200:9117/Admin/configure_indexer
May 26, 2017 06:27:59 PM	Info	
AdminController Dispose 
May 26, 2017 06:27:59 PM	Info	
AdminController Dispose 
May 26, 2017 06:27:59 PM	Info	
  Content-type='application/json; charset=utf-8', content-length=996
May 26, 2017 06:27:59 PM	Info	
AdminController ExecuteAsync 
Close

QNAP Version: 4.3.3
Jackett version:  0.7.1437.0
Mono version (if not using Windows):  4.8.1.0

-------------------------------

**Comment by kaso17** [comment]
is this still a problem (It works for me)?

**Comment by jdrewsteiner** [comment]
Yes.  It's very strange.  Cardigann is not working either.  Strangely, If I uninstall it and reinstall it, it works for a few hours and then stops again.

**Comment by flightlevel** [comment]
Between when it works and when it doesn't are you viewing their website in your browser at any stage?

**Comment by jdrewsteiner** [comment]
No.  I was not.  I updated to v0.7.1469 and it seems to be working consistently.
