### ISSUE TITLE
Some indexers cannot pass test and search withing Jackett.

### ISSUE THREAD

**Issue by qinguoluo** [Jackett/Jackett#14234]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client:
Using FlareSolverr: 
Using proxy: Disabled	
App config/log directory: /config/Jackett
Running in Docker: no
Jackett variant:
OS version: windows11 (64bit)
Environment version: 
Starting Jackett v0.20.3846
```

### Description

I've noticed that quite a few indexers fail the test and don't return search results withing Jackett. But you can directly open the URL and search. I don't know the reason, what should I do?

### Logged Error Messages

```text
2023-04-10 08:59:37	Error	
System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (anidex.info:443)
2023-04-10 08:59:22	Error	
System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (anidex.info:443)
2023-04-10 08:59:15	Warn	
Request to Anidex failed with exception '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (anidex.info:443)'. Retrying in 1s... (Attempt 2 of 2).
2023-04-10 08:59:09	Error	
System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (anidex.info:443)
2023-04-10 08:59:00	Warn	
Request to Anidex failed with exception '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (anidex.info:443)'. Retrying in 1s... (Attempt 2 of 2).
2023-04-10 08:58:53	Warn	
Request to Anidex failed with exception '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (anidex.info:443)'. Retrying in 0.5s... (Attempt 1 of 2).
2023-04-10 08:58:47	Warn	
Request to Anidex failed with exception '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (anidex.info:443)'. Retrying in 1s... (Attempt 2 of 2).
2023-04-10 08:58:38	Warn	
Request to Anidex failed with exception '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (anidex.info:443)'. Retrying in 0.5s... (Attempt 1 of 2).
2023-04-10 08:58:25	Warn	
Request to Anidex failed with exception '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (anidex.info:443)'. Retrying in 0.5s... (Attempt 1 of 2).
2023-04-10 08:58:08	Error	
System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (anidex.info:443)
2023-04-10 08:57:46	Warn	
Request to Anidex failed with exception '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (anidex.info:443)'. Retrying in 1s... (Attempt 2 of 2).
2023-04-10 08:57:24	Warn	
Request to Anidex failed with exception '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (anidex.info:443)'. Retrying in 0.5s... (Attempt 1 of 2).
2023-04-10 08:56:17	Error	
System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (anidex.info:443)
```

### Screenshots

![屏幕截图 2023-04-10 091647](https://user-images.githubusercontent.com/92149037/230807075-47918455-6e82-4e17-b411-98874d150fff.png)

**Comment by ilike2burnthing** [comment]
Based on the log for that one indexer - https://github.com/Jackett/Jackett/wiki/TroubleShooting#a-connection-attempt-failed

See the rest of the troubleshooting issues for further issues.

BTDigg doesn't currently work on Windows Jackett.

**Comment by Locutus64** [comment]
I just ran into this same issue with multiple indexers failing. I'm assuming it's something in today's update.

**Comment by ilike2burnthing** [comment]
The only indexers there changed in v0.20.3889 are limetorrents and limetorrentsclone, both of which are working for you. See the troubeshooting link above.

**Comment by Locutus64** [comment]
I decided to do one more reboot and test in both Jackett and sonarr and now only Glo is having a issue. That's normal and expected from time to time with them.
