### ISSUE TITLE
Malware detcted by Kaspersky Security Network

### ISSUE THREAD

**Issue by Root-FTW** [Jackett/Jackett#14231]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows 10 64 bits
```

### Description

Fresh install

![image](https://user-images.githubusercontent.com/108767514/230707757-2766bb55-a19b-4007-98d0-b4cc2413909c.png)

### Logged Error Messages

```text
Malware on JackettCOnsole.exe detected by Kaspersky
```

### Screenshots

![image](https://user-images.githubusercontent.com/108767514/230707812-995fd817-8fed-483b-ac10-f5d8a7650e2b.png)

![image](https://user-images.githubusercontent.com/108767514/230707838-68e63bff-7e0a-4faa-bf0a-196ee8ed6cd6.png)

**Comment by garfield69** [comment]
This is very likely a false hit from your security software.
passing the zip file and separately the jackettconsole exe to [virustotal](https://www.virustotal.com/gui/home/upload) returns no suspicious hits across all the virus engines the site uses
the wndows zip https://www.virustotal.com/gui/file/6a3d5a87b8771fed4a0961e297a8755086314b7de85aa48c4e94b1923653177c
the jackettconsole exe 
https://www.virustotal.com/gui/file/e25e093d22340c7d0a50693a3b7113d35ba6a42a8da97022f46ecc30010ccbe5
