### ISSUE TITLE
(More a FYI than an actual Bug) > When activating VPN provider's proxy some of the indexes stop working and RARBG starts throttling  

### ISSUE THREAD

**Issue by AdilusPrimus** [Jackett/Jackett#14242]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
![Screenshot from 2023-04-11 10-11-30](https://user-images.githubusercontent.com/3187466/231203025-ed0f51be-86cb-4a3a-a2bc-2b640fc72c3c.png)
```

### Description

![Screenshot from 2023-04-11 10-55-12](https://user-images.githubusercontent.com/3187466/231203136-c79871b9-cf40-47d1-9809-fa00e514f312.png)

VPN Service Provider NordVPN.
At the time of the observation, I was using the L.A Proxy.

The idea here would be to add a warning message about this unfortunate behavior (for a few indexes) that cannot be solved in Jackett.

Next to this message in the Proxy Configuration Section?
![Screenshot from 2023-04-11 10-58-26](https://user-images.githubusercontent.com/3187466/231204368-618ca1ef-b138-490f-b3c8-5e6907bc0ff4.png)

Cheers!

### Logged Error Messages

```text
For the RARBG Throttling rule (Rate Limiting when query originates from a public proxy and perhaps even VPN):
2023-04-11 10:48:53 	Error 	

Jackett.Common.IndexerException: Exception (rarbg): Rate limited with StatusCode 520, retry in 3 minutes

For GloDS: 
Exception: Test search in GloDLS => Found no results while trying to browse this tracker

for FrozenLayer:
Jakett.Common.IndexerException: Exception (frozenlayer):  Received an unexpected EOF or 0 bytes from the transport stream.

2023-04-11 10:48:53 	Error 	

Jackett.Common.IndexerException: Exception (rarbg): Rate limited with StatusCode 520, retry in 3 minutes

2023-04-11 10:48:53 	Info 	

```

**Comment by ilike2burnthing** [comment]
It's just sites blocking common VPN IPs, or in the case of RARBG being rate limited because other people with the same IP also using it. The same would happen if you were to use the same servers in a VPN client external to Jackett.
