### ISSUE TITLE
[noname-clubl] (testing) Exception (noname-clubl): The given key '.Config.freeleech' was not present in the dictionary.: The given key '.Config.freeleech' was not present in the dictionary.

### ISSUE THREAD

**Issue by sample** [Jackett/Jackett#14246]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.3889-ls101)
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.4.0.146 (64bit OS) (64bit process)
Environment version: 6.0.16 (/app/Jackett/)
Starting Jackett v0.20.3889
```

### Description

When I press test button for nnm-clubl indexer, test failed with error "An error occurred while testing this indexer
Exception (noname-clubl): The given key '.Config.freeleech' was not present in the dictionary.: The given key '.Config.freeleech' was not present in the dictionary."

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (noname-clubl): The given key '.Config.freeleech' was not present in the dictionary.
```

### Screenshots

![2023-04-12_17-02-25](https://user-images.githubusercontent.com/354018/231482276-0152e4c1-a21b-4644-8e7d-1bbd01456bca.png)

**Comment by garfield69** [comment]
Oops. A recent update accidentally reverted the freeleech option.
we will fix this in the next release of jackett.
Sorry about that.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/27466e2e87a6464beee5d8fad16e8343f8436cec
