### ISSUE TITLE
[REQ] Votre télé québecois French tracker

### ISSUE THREAD

**Issue by maxcore** [Jackett/Jackett#1424]
the invitation was open http://votretelequebecoise.net/signup.php

AddCategoryMapping("130", TorznabCatType.ConsoleXboxOne);
AddCategoryMapping("107", TorznabCatType.Movies);
AddCategoryMapping("76", TorznabCatType.Audio);
AddCategoryMapping("122", TorznabCatType.PC);
AddCategoryMapping("123", TorznabCatType.PCISO);
AddCategoryMapping("124", TorznabCatType.PCMac);
AddCategoryMapping("127", TorznabCatType.PCPhoneOther);
AddCategoryMapping("9", TorznabCatType.PCGames);
AddCategoryMapping("126", TorznabCatType.PCPhoneAndroid);
AddCategoryMapping("6", TorznabCatType.TV);
AddCategoryMapping("28", TorznabCatType.TVWEBDL);
AddCategoryMapping("5", TorznabCatType.TVFOREIGN);
AddCategoryMapping("101", TorznabCatType.TVOTHER);
AddCategoryMapping("12", TorznabCatType.TVSport);
AddCategoryMapping("8", TorznabCatType.TVDocumentary);
AddCategoryMapping("11", TorznabCatType.Other);
AddCategoryMapping("91", TorznabCatType.Books);
AddCategoryMapping("91", TorznabCatType.BooksEbook);
AddCategoryMapping("94", TorznabCatType.BooksComics);
AddCategoryMapping("93", TorznabCatType.BooksMagazines);

**Comment by thenamelessthing** [comment]
@maxcore  C'est bien ce tracker? Je ne connaissais pas..

**Comment by maxcore** [comment]
Oui pas juste de la tv

________________________________

**Comment by ploufs** [comment]
@maxcore c'est maintenant sur invitation.
Donc, si tu veux que je l'ajoute envoi un code d'invitation.

**Comment by maxcore** [comment]
DEAD
