### ISSUE TITLE
[cartoonchaos] (testing) Test search in CartoonChaos => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by timc6896** [Jackett/Jackett#14252]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

Jackett is running in docker with flaresolverr also in a container on Raspberry Pi 4.
No proxy.

### Description

 An error occurred while testing this indexer
Test search in CartoonChaos => Found no results while trying to browse this tracker

### Logged Error Messages

System.Exception: Test search in CartoonChaos => Found no results while trying to browse this tracker

</body>
</html>

**Comment by ilike2burnthing** [comment]
Site is loading slowly for me, but it does eventually load. They may be having been a temporary issue. Retry now. If you have the same problem see the troubleshooting steps here:
- https://github.com/Jackett/Jackett/wiki/Troubleshooting/#login-failed-selector
- https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work-the-ssl-connection-could-not-be-established

If that doesn't resolve your issue, provide an enhanced log - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by timc6896** [comment]
Site is loading quick and the test result is instant.  It looks like it is connecting immediately but not returning any results.  The actual error is:

 An error occurred while testing this indexer
Test search in CartoonChaos => Found no results while trying to browse this tracker

This error is on Jackett testing and not from Sonarr or Radarr

**Comment by ilike2burnthing** [comment]
Read the rest of the comment above.

**Comment by timc6896** [comment]
Oh man, I'm such a bonehead!!!  Thanks for pointing out the obvious, took me a while to find the xBtit_Default setting on their site.
