### ISSUE TITLE
[mvgroupforum] (testing) Exception (mvgroupforum): Login failed: No form found on https://forums.mvgroup.org/index.php?

### ISSUE THREAD

**Issue by 101John** [Jackett/Jackett#14256]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://0.0.0.0:8191
Using proxy: Disabled
App config/log directory: /Users/john/.config/Jackett	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads	
Running in Docker: No
Jackett variant: CoreMacOs
OS version: Unix 12.6.5 (64bit OS) (64bit process)
Environment version: 6.0.16 (/Applications/Jackett/)
Starting Jackett v0.20.3897
```

### Description

I have entered a user name and password for this site in Jackett.

Been running into this over and over. The only way I have found to straighten it out is to open the **Configure** dialog for those two indexers in Jackett and then click **Okay** - without changing anything. This then logs me in to the website and Jackett can grab releases. Can this be done programmatically within Jackett?

### Logged Error Messages

```text
2023-04-16 16:07:14	Error	
Jackett.Common.IndexerException: Exception (mvgroupforum): Login failed: No form found on https://forums.mvgroup.org/index.php?act=Login&CODE=00 using form selector form[action^="?act=Login"]

2023-04-16 16:07:14	Error	
Error on 20230416160714 for MVGroup Forum.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://forums.mvgroup.org/index.php?act=Login&CODE=00 using form selector form[action^="?act=Login"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /Users/runner/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 595
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1581

Please login to the forum first
2023-04-16 16:07:14	Info	
CardigannIndexer (mvgroupforum): Relogin required
2023-04-16 16:07:14	Error	
Redirected to: https://forums.mvgroup.org/index.php?act=Login&CODE=00
```

**Comment by ilike2burnthing** [comment]
Working ok here. Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-no-form-found-on-url

> The only way I have found to straighten it out is to open the Configure dialog for those two indexers in Jackett and then click Okay - without changing anything. This then logs me in to the website and Jackett can grab releases.

Do you mean not entering any credentials? That should fail. Or do you mean using auto-filled credentials? If so, that would suggest that whatever you're entering manually is incorrect.

**Comment by 101John** [comment]
@ilike2burnthing 

I wrote that the only way to get the auto login feature to work for that site, after I get these errors, is to open the Configure dialog again for each of these indexers in Jackett and then click on OK - without changing my credentials or anything else. I get a message that it's been successfully configured and the log in issue disappears from the logs until, I assume that freshly created cookie goes stale, wherein I have to redo that same procedure when seeing the log in error again.

Been doing this for months trying to avoid opening an issue here in the hopes this would be corrected.

I have both" mvgroup forum" and "mvgroup main" each are associated with the tag "mvgroup"

Thanks!

**Comment by ilike2burnthing** [comment]
To be clear, your troubleshooting procedure is as follows:

1. remove existing indexers
2. restart Jackett
3. add indexers without issue
4. after some time (hours? days? weeks?) get errors on searches/test
5. open config and just click Okay
6. indexers are added and test fine
7. after some more time they fail again
8. open config and just click Okay
9. indexers are added and test fine
10. repeat...

Is that correct?

I've had these indexers added to my test setup for a couple of years and I don't think I've ever needed to manually reconfigure them.

Are you signing in and out of the site in that time? Are you using a different IP than Jackett?

**Comment by 101John** [comment]
Thanks

Before we continue, what do you mean by signing in and out of the site? ... I rarely use a web browser to access the site. This is why I have the credentials inside of Jackett.

Yes what you wrote is exactly correct. Except I don't re-add the indexers each time. After clicking Okay I get a message saying they have been configured. A few times, In an attempt to troubleshoot, I have followed the FAQ and removed them, exited Jackett, restarted, Jackett and re-added the indexers. The problem repeats after a certain amount of time.

I only have one IP address.

Can you share what you have in the Site Link field... I am wondering if this has something to do with it.

These fields are auto populated with "https://forums.mvgroup.org/"

**Comment by ilike2burnthing** [comment]
If you're not signing in and out of the site then it shouldn't be an issue.

That's the correct URL.

Provide an enhanced log the next time it happens.

**Comment by garfield69** [comment]
Interesting.
I have had the MVGroupMain indexer set up ever since Jan 2018, and I have never had to open the config to force a manual login.
I note that my logs regularly show 
```
2023-04-17 16:35:08 | Error | Redirected to: https://forums.mvgroup.org/index.php?act=Login&CODE=00
2023-04-17 16:35:08 | Info | CardigannIndexer (mvgroupmain): Relogin required
2023-04-17 16:35:12 | Info | Test search in MVGroup Main => Found 50 releases [5277ms]
```
whenever I do a TEST (which I run daily on all my active indexers as part of my Jackett support schedule),
which shows that Jackett regularly detects that a re-login is needed, and successfully completes the auto login, since results are returned subsequently.

I may have missed spotting this in your earlier OP, but how often do you use the MVG indexers, and how often are you having to do the open/OK config sequence?

**Comment by garfield69** [comment]
It's contagious!
While doing a TEST today I got this:
```
2023-04-20 10:52:32	Debug	
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://forums.mvgroup.org/maintracker.php?seed=0&orderby=added&order=DESC)
2023-04-20 10:52:34	Debug	
WebClient(HttpWebClient2): Returning Redirect => https://forums.mvgroup.org/index.php?act=Login&CODE=00 31 bytes <BINARY>
2023-04-20 10:52:34	Debug	
WebClient(HttpWebClient2): HexDump20: P(50)l(6C)e(65)a(61)s(73)e(65) (20)l(6C)o(6F)g(67)i(69)n(6E) (20)t(74)o(6F) (20)t(74)h(68)e(65) (20)
2023-04-20 10:52:34	Error	
Redirected to: https://forums.mvgroup.org/index.php?act=Login&CODE=00
2023-04-20 10:52:34	Info	
CardigannIndexer (mvgroupmain): Relogin required
2023-04-20 10:52:34	Error	
Error on 20230420105234 for MVGroup Main.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://forums.mvgroup.org/index.php?act=Login&CODE=00 using form selector form[action^="?act=Login"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 595
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1581



Please login to the forum first
2023-04-20 10:52:34	Error	
Jackett.Common.IndexerException: Exception (mvgroupmain): Login failed: No form found on https://forums.mvgroup.org/index.php?act=Login&CODE=00 using form selector form[action^="?act=Login"]
```

**Comment by 101John** [comment]
Looks similar to what I am seeing today. It was roughly 4 days before the error popped up again.

Thanks for taking my issue seriously and fixing it so quickly.
