### ISSUE TITLE
Application error id 1000

### ISSUE THREAD

**Issue by Starbuck1991** [Jackett/Jackett#14268]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.22621.0 (64bit OS)
Environment version: 6.0.16 (C:\ProgramData\Jackett\)
```

### Description

Every time I start Windows 11, the Event log register the following application error (my OS is Spanish, but I think you'll get the idea):

Nombre de la aplicación con errores: JackettService.exe, versión: 0.20.3971.0, marca de tiempo: 0x641cef99
Nombre del módulo con errores: KERNELBASE.dll, versión: 10.0.22621.1555, marca de tiempo: 0x686e4e74
Código de excepción: 0xe0434352
Desplazamiento de errores: 0x001479d2
Identificador del proceso con errores: 0x0x11E0
Hora de inicio de la aplicación con errores: 0x0x1D9761359FDBC20
Ruta de acceso de la aplicación con errores: C:\ProgramData\Jackett\JackettService.exe
Ruta de acceso del módulo con errores: C:\Windows\System32\KERNELBASE.dll
Identificador del informe: 87eb0010-c3e1-423e-b7ff-249c1068b751
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores: 

### Logged Error Messages

```text
No logged error in the Jackett log.
```

**Comment by garfield69** [comment]
Not so much an issue with the Jackett service, more an issue with PC (software/hardware).
have a read of this article https://appuals.com/how-to-fix-application-error-0xe0434352-on-windows/ and in particular take a look at method 2 ( .NET frameworks repair) and method 3 (CHKDSK scan).
OR/AND read this article which covers even more options than might apply to you https://windowsreport.com/event-1000-application-error-windows-10/
