### ISSUE TITLE
[0magnet] (configuring) No space left on device : '/config/Jackett/Indexers/0magnet.json.2e580cbf3a374020a951764bb3490fd9.tmp'

### ISSUE THREAD

**Issue by sidneyki** [Jackett/Jackett#14260]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Ubuntu server running Docker. The docker is running jackett.
```

### Description

An error occurred while configuring this indexer
No space left on device : '/config/Jackett/Indexers/0magnet.json.2e580cbf3a374020a951764bb3490fd9.tmp
I do not know how to resolve.

### Logged Error Messages

```text
An error occurred while configuring this indexer
No space left on device : '/config/Jackett/Indexers/0magnet.json.2e580cbf3a374020a951764bb3490fd9.tmp
```

### Screenshots

An error occurred while configuring this indexer
No space left on device : '/config/Jackett/Indexers/0magnet.json.2e580cbf3a374020a951764bb3490fd9.tmp

**Comment by garfield69** [comment]
This is a Docker disk space management issue and not a Jackett problem.
I suggest you so a Google search for `ubuntu docker No space left on device` to read up on possible causes and suggested methods to free up volume space
@ilike2burnthing  anything to add?

**Comment by ilike2burnthing** [comment]
Assuming there is actually space on your device, it's likely a permissions issues, ensure your `PUID` and `PGID` ENVs are correct.

Also check that your volume mapped folder for `/config/` exists, is accessible to that user, and isn't configured as read-only.

If you're unsure, provide your Docker run command, compose file, or Portainer screenshots.
