### ISSUE TITLE
[1337x] (testing) Exception (1337x): No such host is known.: No such host is known. (1337x.to:443)

### ISSUE THREAD

**Issue by thaynos** [Jackett/Jackett#14279]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
windows 10
```

### Description

tested 1337x and it failed

### Logged Error Messages

```text
title
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

**Comment by thaynos** [comment]
sorry
