### ISSUE TITLE
Exception (btdigg): Got redirected to another domain. Try changing the indexer URL to https://www.domflow.it/.: Parse error

### ISSUE THREAD

**Issue by Woody-Stock** [Jackett/Jackett#14273]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows 10 x64 22H2 19045.2728
Jackett v0.20.3985 but has been happening for several weeks
Flaresolverr deactivated as it doesn't work with proxies in its latest versions
HTTPS5 proxy (from Privado) activated (the targeted website isn't accessible without proxy from my location).
```

### Description

Testing the BTDIGG index returns an error. Same with other proxies from Privado.
It's accessible without issues using the proxy via Firefox.

The same proxy works without issue for Jackett with 60 other indexers.

An issue was previously opened and thought to be resolved via the use of a TOR proxy link but that stopped working a few days afterwards.

I couldn't work out on reopening the original [#14198](https://github.com/Jackett/Jackett/issues/14198) issue (according to my research it's not possible but I could be wrong).

### Logged Error Messages

```text
Exception (btdigg): Got redirected to another domain. Try changing the indexer URL to https://www.domflow.it/.: Parse error
```

**Comment by Woody-Stock** [comment]
Hi, I'm fine with reopening the original (closed) issue I just don't know how.

**Comment by garfield69** [comment]
I've re-opened https://github.com/Jackett/Jackett/issues/14198.

**Comment by Woody-Stock** [comment]
Thanks!
