### ISSUE TITLE
[lostfilm] (updating) Exception (lostfilm): Address not available: Parse error

### ISSUE THREAD

**Issue by Bull6** [Jackett/Jackett#14284]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Runnin in docker: latest version

....

jackett:
        image: linuxserver/jackett
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ="Asia/Yekaterinburg"
            - AUTO_UPDATE=true #optional
            - RUN_OPTS= #optional
        volumes:
            - /home/jackett/config:/config
            - /srv/dev-disk-by-uuid-5590fcc1-f472-4281-af4a-7df7a256c522/media:/downloads
        # ports:
        #   - 9117:9117
        restart: unless-stopped
        network_mode: service:openvpn
...
```

### Description

try add lostfilm.tv at jackett indexer (try same link of list)

### Logged Error Messages

```text
add log file to issue
```

### Screenshots

![image](https://user-images.githubusercontent.com/8268783/235448418-b9e81310-4bf3-48a5-bef5-7f59c80a8e2b.png)
[jackett_error.log](https://github.com/Jackett/Jackett/files/11365210/jackett_error.log)

**Comment by ilike2burnthing** [comment]
Working ok here, not sure why insearch.site is being requested for you. Try again, see if it was a temporary issue.

If it continues, try changing site link. Be aware, when you change site link it will fail (as the captcha will no longer be valid), so you'll need to close the config panel, reopen it, and then enter the new captcha.

**Comment by Bull6** [comment]
> Working ok here, not sure why insearch.site is being requested for you. Try again, see if it was a temporary issue.
> 
> If it continues, try changing site link. Be aware, when you change site link it will fail (as the captcha will no longer be valid), so you'll need to close the config panel, reopen it, and then enter the new captcha.

Thank you for answer, but it doesn't help for me. I tried every link from list, but i get this error - "Address not available: Parse error", every time
ps i try link like you sayed with close config panel for get new capcha for new site link

**Comment by ilike2burnthing** [comment]
Are you using a proxy or VPN? If so, try disabling it or changing to a different server.
