### ISSUE TITLE
Jackett grabs torrent but sometimes 1 hour later

### ISSUE THREAD

**Issue by dr400** [Jackett/Jackett#14282]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2

Using FlareSolverr: http://192.168.0.10:8191

Using proxy: Disabled

App config/log directory: /config/Jackett

ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
	
Running in Docker: Yes (image build: v0.20.2489-ls87)
	
File /etc/issue: Ubuntu 20.04.4 LTS \n \l

Jackett variant: CoreLinuxAmdx64
	
OS version: Unix 4.4.180.0 (64bit OS) (64bit process)

Environment version: 6.0.16 (/app/Jackett/)
	
Starting Jackett v0.20.4013
```

### Description

When manual search is triggered (using yggtorrent as for tracker), the results shown are different from ones on yggtorrent websites. Youngest torrents are not yet shown and sometimes 1 hour (or even more) passed before jackett is able to provide the youngest torrents ...

Is there also the possibility to filter the result given by jackett and only show the results not older than x hours when using the webapi http request : something like that

http://ipaddr:port/api/v2.0/indexers/yggtorrent/results/torznab/api?apikey=xxxxxx&t=search&cat=102154,102156&q=&maxage=1h

or :

http://ipaddr:port/api/v2.0/indexers/yggtorrent/results/torznab/api?apikey=xxxxxx&t=search&cat=102154,102156&q=&publishedmaxage=1h

### Logged Error Messages

```text
no logged Error Msg
```

### Screenshots

![image](https://user-images.githubusercontent.com/48514024/235296434-8ea53ebe-09d8-4324-8f21-0fceaca70683.png)

This is result from yggtorrent while at the same time the same request via jackett is giving : 

![image](https://user-images.githubusercontent.com/48514024/235296397-9b4034f6-916c-4571-b7dc-7063b491cf9f.png)

 "Vélo Magazine" is published in yggtorrent but not showing in jackett (yet)

**Comment by ilike2burnthing** [comment]
Going by the `91m ago` of that result, specificity the indexer can't have from a new search (it should just say `2h ago`), I'd suggest looking at your `Cache TTL` setting in Jackett.

**Comment by dr400** [comment]
Thx for the quick reply

Changed TTL from 2100 to 300 ... let's see if it's better or not ... 

About the results, I've changed "Cache max results per indexer" to 10 to get the more recent torrents but still get 50+ results ...

**Comment by dr400** [comment]
arf ...

![image](https://user-images.githubusercontent.com/48514024/235305364-9d93684e-3dc8-4691-8075-162809020d7a.png)
 and jackett only shows : 

![image](https://user-images.githubusercontent.com/48514024/235305376-d5c9d7d2-d3ee-4c79-8beb-6c28431152c7.png)

**Comment by ilike2burnthing** [comment]
You can leave the max cached results at 1000. I'm not sure how Jackett deals with receiving more results than are able to be cached, but reducing it to 10 will either be useless or break something.

Try just disabling cache and performing a search. If that works, re-enable it with a reduced TTL.

**Comment by dr400** [comment]
max cached results is back to 1000

But I'm not sure how to disable cache ? putting 0 maybe ?

**Comment by ilike2burnthing** [comment]
Deselect `Cache enabled`.

**Comment by dr400** [comment]
ok ! got it ! see if it's getting better ... Thanks for your help
