### ISSUE TITLE
[req]: Uploads

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14291]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Uploads
- URL: http://uploads.ltd/
- Description: Uploads is a CHINESE Private Torrent tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): none
- Additional Comments: 
does not support https
Engine: NexusPHP 1.7.30 2022-11-05
Registration current open ATM
```

**Comment by garfield69** [comment]
v0.20.4071

**Comment by garfield69** [comment]
http://uploads.ltd/ 502 Bad Gateway nginx/1.18.0 (Ubuntu)

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
http://uploads.ltd/ 500 Internal Server Error

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14291#issuecomment-1622330435

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14291#issuecomment-1622330435

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14291#issuecomment-1620591548

**Comment by garfield69** [comment]
v0.21.747
