### ISSUE TITLE
[req]: Comando Torrents

### ISSUE THREAD

**Issue by diegomartins404** [Jackett/Jackett#14305]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Comando Torrents
- URL: https://comandotorrents.to/
- Description: Popular Brazilian Tracker
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/5731
