### ISSUE TITLE
xtreme zone test failed

### ISSUE THREAD

**Issue by panoramasecret** [Jackett/Jackett#1430]
Hi,
I added new indexer Xtreme Zone everything whent ok, but when I run the test is showing "Test failed for xtremezone: Found no results while trying to browse this tracker"

I'm using
Jackett version:  0.7.1437.0
OpenMediaVault 3.0.77 (erasmus)

[log.txt](https://github.com/Jackett/Jackett/files/1038237/log.txt)

-------------------------------

**Comment by valentinolaru** [comment]
Hello,
Same problem here, they are changing a lot in the website.

**Comment by davidst** [comment]
I had the same issue and found a solution to fix it. The lines for seeders and leechers in the definition file for Xtreme Zone (xtremezone.yml) need to be changed.

Before:
      seeders:
        selector: td:nth-child(7)
      leechers:
        selector: td:nth-child(8)

After:
      seeders:
        selector: td:nth-child(8)
      leechers:
        selector: td:nth-child(9)

**Comment by kaso17** [comment]
fixed with ce8570c6567abfd58000879370f274fd31f18c7d
Thank you @davidst

**Comment by panoramasecret** [comment]
After the last update is working fine. Manny thanks to everybody helping to sort out this issue.
