### ISSUE TITLE
[brasiltracker] (updating) Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by giucberna** [Jackett/Jackett#14312]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
An error occurred while updating this indexer
Object reference not set to an instance of an object.
Click here to open an issue on GitHub for this indexer.
```

### Description

Nao conecta com o meu indexador

### Logged Error Messages

```text
Da erro e manda para ca
```

### Screenshots

![image](https://user-images.githubusercontent.com/57237851/236702860-dbfc0488-e136-4aad-b4fe-6c43e3d654c8.png)

**Comment by garfield69** [comment]
confirmed.
the site's login page has a new challenge which the indexer is not expecting.
I'll test to see if its one that can be coded for using the standard login challenges, otherwise I will switch to using the cookie method.

**Comment by garfield69** [comment]
BTW your config site link is too long.
Once we have published the next version of Jackett and you have updated to it, then edit the brasiltracker config, and replace your sitelink with `https://brasiltracker.org/` and fill in the cookie by following the config instructions.

**Comment by garfield69** [comment]
@ilike2burnthing  for this indexer I noticed that the indexer is dropping out the title for TV series.
for the other entries (movies, books, music) the title is included.
Want to take a look, or pass it on to @mynameisbogdan ? Thanks.

**Comment by ilike2burnthing** [comment]
I'll take a look shortly. If I can't make sense of it I can throw credentials your way.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/571bd12a47bdbcd3a7a7eb7b48ab9b4d6f3c96d4

Fixed it in like 5mins, but then got side tracked thinking converting it to YAML would be a good idea. While it was possible, all the titles were truncated. Then categories became the new fixation... :P

**Comment by garfield69** [comment]
Good job. ;-)

**Comment by garfield69** [comment]
v0.20.4119
