### ISSUE TITLE
[amigosshare] Non-standard quality label affecting Sonarr/Radarr etc.

### ISSUE THREAD

**Issue by GomesPriv** [Jackett/Jackett#14316]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.22621.0 (64bit OS)
Environment version: 6.0.16 (C:\ProgramData\Jackett\)
Starting Jackett v0.20.4119
```

### Description

The "Amigos Share Club" indexer fails to normalize "4k" quality label like [other indexers](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/BJShare.cs#L542-L548), leading Sonarr/Radarr to not properly recognize the release quality (as shown below)

Example search (one of the results returns "4k" in the title, should be "2160p" instead):
![image](https://user-images.githubusercontent.com/132962759/236968029-6a0d4351-46a0-4a4d-bc18-076ec73caf00.png)

Example from Radarr (note the "Unknown" quality label):
![image](https://user-images.githubusercontent.com/132962759/236968259-13e4ce01-1c8c-4b4a-ab87-911a2492a829.png)

I think the solution should be simply replacing "4k" to "2160p" in results.

### Logged Error Messages

```text
No error messages
```

**Comment by garfield69** [comment]
v0.20.4125
