### ISSUE TITLE
[1337x] (testing) Exception (1337x): certificate validation failed: [Subject]  CN=1337x.to[Issuer]  CN=E1, O=Let's Encrypt, C=US[Serial Number]  0395FD3301E9930FCB79961441852DB1B011[Not Before]  5/7/2023 7:00:59 PM[Not After]  8/5/2023 7:00:58 PM[Thumbprint]  4210325329CC20CFD30852AA7964D24DB7A85292: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by soggychips** [Jackett/Jackett#14315]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: Yes
Using proxy: Http
App config/log directory: /home/jackett/.config/Jackett
Running in Docker: no
Jackett variant: CoreLinuxAmdx64
OS version: Unix 3.10.0.1062 (64bit OS) (64bit process)
Environment version: 6.0.16
Starting Jackett v0.20.4119
```

### Description

1. Add 1337x indexer
2. Press 'test'

This indexer (and others) have been working for well over a year. I tried all the other mirrors, and I get the same thing.

I am able to curl 1337x.to just fine. Output of curl w/ proxy:

```
...
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=1337x.to
* 	start date: May 08 02:00:59 2023 GMT
* 	expire date: Aug 06 02:00:58 2023 GMT
* 	common name: 1337x.to
* 	issuer: CN=E1,O=Let's Encrypt,C=US
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 1337x.to
> Accept: */*
>
< HTTP/1.1 200 OK
...
```

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (1337x): certificate validation failed: [Subject]
  CN=1337x.to

[Issuer]
  CN=E1, O=Let's Encrypt, C=US

[Serial Number]
  0395FD3301E9930FCB79961441852DB1B011

[Not Before]
  5/7/2023 7:00:59 PM

[Not After]
  8/5/2023 7:00:58 PM

[Thumbprint]
  4210325329CC20CFD30852AA7964D24DB7A85292
```

### Screenshots

![image](https://user-images.githubusercontent.com/4753910/236910474-51b888cd-9c22-4dfc-b954-9bfe253f00ac.png)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14311

**Comment by soggychips** [comment]
This isn't a duplicate issue to the one you linked, as it's a different index, with a very different setup:

- not a NAS
- using a proxy
- using flaresolverr

**Comment by ilike2burnthing** [comment]
You're already engaging on the other issue and are getting the same error for the same indexer as OP (plus others, which OP may now also have issues with). If namanix resolves their issue but yours continue, or if they don't reply in a few days, we can reopen this one.

**Comment by soggychips** [comment]
OK, thanks for the consideration

**Comment by soggychips** [comment]
In case anyone's running into this in the future and nothing else works, you can always disable SSL in the `jacket_launcher.sh` script by adding `--IgnoreSslErrors true` as a flag to the launch command.
