### ISSUE TITLE
Warning: The login page has been disabled

### ISSUE THREAD

**Issue by PN62323424** [Jackett/Jackett#14310]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
synology
```

### Description

piggo.me and ultrahd.net are two sites that often shut down visitor access (most of the time, to be precise), making it impossible to access them in jackett unless you use a cookie to do so. Is there a solution to this problem?

The site pt.btschool.club is not closed to visitors, but every one or two days it also needs to re-enter the captcha.

### Logged Error Messages

```text
[Warning: The login page has been disabled. Please backup your cookie and do not logout](https://piggo.me/usercp.php)
```

**Comment by garfield69** [comment]
v0.20.4105
