### ISSUE TITLE
[iptorrents] (testing) Exception (iptorrents): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /usr/ports/lang/mono6.8/work/mono-6.8.0.123/external/boringssl/ssl/handshake_client.c:1132: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by ClintGit** [Jackett/Jackett#14318]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient
Mono version: 6.8.0.123 (tarball Fri May  5 10:43:13 UTC 2023)
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /usr/local/jackett
ThreadPool MaxThreads: 200 workerThreads, 200 completionPortThreads
Running in Docker: No
Jackett variant: Mono
OS version: Unix 12.2.0.0 (64bit OS) (64bit process)
Environment version: 4.0.30319.42000 (/usr/local/lib/mono/4.5)
Jackett Data will be stored in: /usr/local/jackett
Starting Jackett v0.20.4125
```

### Description

I have been running Jackett for sometime now on FreeBSD 12.2 Release and it started acting up recently. I just noticed it today but from the log it looks like it started on May 6th. I seen a similar issue here:
[https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work-the-ssl-connection-could-not-be-established](url)

I tried to upgrade mono version to the latest, and got updated certificates then rebooted the system. The issue still persists, please help me. I have attached my log.txt as per the contributing instructions.

Thanks,
Clint
[log.txt] removed. see log in next post.

### Logged Error Messages

```text
2023-05-10 04:04:59.9004 Error Jackett.Common.IndexerException: Exception (iptorrents): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /wrkdirs/usr/ports/lang/mono6.8/work/mono-6.8.0.123/external/boringssl/ssl/handshake_client.c:1132 Jackett.Common.IndexerException: Exception (iptorrents): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /wrkdirs/usr/ports/lang/mono6.8/work/mono-6.8.0.123/external/boringssl/ssl/handshake_client.c:1132 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

**Comment by ClintGit** [comment]
Please refer to the log.txt here instead as I didn't properly enable enhanced logging the first time.

Thanks,
C

[log.txt](https://github.com/Jackett/Jackett/files/11438379/log.txt)

**Comment by garfield69** [comment]
please open a terminal and post the results here from 
```
openssl s_client -connect iptorrents.com:443
```
Also
```
openssl version
```
thanks.

**Comment by ClintGit** [comment]
> please open a terminal and post the results here from
> 
> ```
> openssl s_client -connect iptorrents.com:443
> ```
> 
> Also
> 
> ```
> openssl version
> ```
> 
> thanks.

See below:

root@jrs:/ # openssl s_client -connect iptorrents.com:443
CONNECTED(00000003)
depth=1 C = US, O = Let's Encrypt, CN = E1
verify return:1
depth=0 CN = iptorrents.com
verify return:1
---
Certificate chain
 0 s:CN = iptorrents.com
   i:C = US, O = Let's Encrypt, CN = E1
 1 s:C = US, O = Let's Encrypt, CN = E1
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X2
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X2
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 3 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDyDCCA02gAwIBAgISBBOY0xxjBbZ1Up1KXfJSar+KMAoGCCqGSM49BAMDMDIx
CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
MTAeFw0yMzA1MDQwMDE1MDRaFw0yMzA4MDIwMDE1MDNaMBkxFzAVBgNVBAMTDmlw
dG9ycmVudHMuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAES1d4NOW2Lxbd
ewXfeZMIRkljP+zwzGzHzzI5zGm9heA07aC1EZmkQU6MWGSHyMbBBQrd8JqU/28b
QnEJepjcCaOCAlowggJWMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggrBgEF
BQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUyJPIIHO8KeHL
BHTa1MPGRyEEelQwHwYDVR0jBBgwFoAUWvPtK/w2wjd5uVIw6lRvz1XLLqwwVQYI
KwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vZTEuby5sZW5jci5vcmcw
IgYIKwYBBQUHMAKGFmh0dHA6Ly9lMS5pLmxlbmNyLm9yZy8wKwYDVR0RBCQwIoIQ
Ki5pcHRvcnJlbnRzLmNvbYIOaXB0b3JyZW50cy5jb20wTAYDVR0gBEUwQzAIBgZn
gQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5s
ZXRzZW5jcnlwdC5vcmcwggEDBgorBgEEAdZ5AgQCBIH0BIHxAO8AdgC3Pvsk35xN
unXyOcW6WPRsXfxCz3qfNcSeHQmBJe20mQAAAYfkU7ilAAAEAwBHMEUCIQCkS4Kk
j8YeqhjFGsxO2KZV5eTgZBZHd85kxAL3sVoXggIgCj3Ssa4dCjFoCrxcjR6PK0k9
3B9EZcw7pJikKqTT2AsAdQDoPtDaPvUGNTLnVyi8iWvJA9PL0RFr7Otp4Xd9bQa9
bgAAAYfkU7hOAAAEAwBGMEQCICOJfARZtKpFuQJ1X8qCbSoKvDrz2TakcpAw6zin
aYyWAiA7xK0pMa+aaBzbFqzE42AYZCUF2mtAWFTUQMTtFKqH/zAKBggqhkjOPQQD
AwNpADBmAjEAuGAJm7X8J3Zq25bitfnReMJAp0R5euVa0KGSl28cBmLbDthWcp5v
JpqvCEKv5H/mAjEA6VK2sQ2YHtjS3O3bAMlmLqBJrhUW88mOiaAUosGurchc3D9M
/TiB0q+Mnp6wwiP1
-----END CERTIFICATE-----
subject=CN = iptorrents.com

issuer=C = US, O = Let's Encrypt, CN = E1

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 4513 bytes and written 398 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 256 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 7511CF56C1E79A863A7C1936268A165D5C92B0CA9E4EE4BA326C6E64B7C759FE
    Session-ID-ctx:
    Resumption PSK: CCA3C8C2EDAEA18D8B097311BDF54B3EA3794DA3FE4A6C345B9A43FC68584241732C433AE98C1707C082DE1864851A9A
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 64800 (seconds)
    TLS session ticket:
    0000 - d0 ff af 5c 34 a5 83 ab-24 67 88 31 09 5d bb cf   ...\4...$g.1.]..
    0010 - 29 d7 64 bb 41 7a 26 09-2f 2b 7b 5b ae 26 cd 71   ).d.Az&./+{[.&.q
    0020 - 83 c6 fe e4 1c 0b 61 d9-fe 73 a1 b4 d9 58 b5 d8   ......a..s...X..
    0030 - 1c 2d a4 50 65 e0 55 bc-a8 b3 0a c1 90 54 e7 12   .-.Pe.U......T..
    0040 - 2b 49 e4 ad 87 5d bb 9a-50 97 df d6 03 ce 20 c1   +I...]..P..... .
    0050 - 40 67 8a 1e c8 b5 ed cc-15 07 fa 01 6c 43 49 bc   @g..........lCI.
    0060 - 87 88 58 ac 7b 52 94 9e-b4 5a 86 fd 87 e9 13 ac   ..X.{R...Z......
    0070 - b0 1b 01 df 29 68 e9 4a-99 d3 af 0f cc 63 7f 78   ....)h.J.....c.x
    0080 - 17 7b 2f 62 07 49 7a d5-c7 a6 d8 f7 4f 77 fc 52   .{/b.Iz.....Ow.R
    0090 - 70 d3 6a 3f 8c f8 63 36-65 b0 98 25 91 a0 e9 96   p.j?..c6e..%....
    00a0 - 8b b0 ca 65 cf 32 b6 34-dd 4e 93 7b 6d a8 3f 9a   ...e.2.4.N.{m.?.
    00b0 - 39 5e 45 2d 9c bd a7 bb-d0 0e 52 b9 72 66 15 3e   9^E-......R.rf.>
    00c0 - 7b 5d ab 84 41 9b 3e 9e-ea 34 51 1d 45 c5 ed 96   {]..A.>..4Q.E...

    Start Time: 1683764221
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 14336
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 9FDCA205FB7228D1CCA99BCC2AC0A0EDEBF07A2D5194DE9A383D047C309ABB95
    Session-ID-ctx:
    Resumption PSK: 66895E92EB56847CE6C90514E6E391A410B0828745C7768F342F896F7FDE183DB54F957D7BA7FB1171793628E0A0F121
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 64800 (seconds)
    TLS session ticket:
    0000 - d0 ff af 5c 34 a5 83 ab-24 67 88 31 09 5d bb cf   ...\4...$g.1.]..
    0010 - 1a 36 72 d9 f5 df c9 ae-b9 3e 78 46 de c3 52 47   .6r......>xF..RG
    0020 - 0a 57 80 ae 6f 84 7b 2a-a6 ab 61 51 5e 16 c6 80   .W..o.{*..aQ^...
    0030 - 2c 88 34 dc a9 47 6b 03-dd 69 88 ff e6 0b d5 48   ,.4..Gk..i.....H
    0040 - 4a ff 57 55 c3 01 2f 3e-a6 da a1 f0 ac 18 f5 82   J.WU../>........
    0050 - 2d 1c 60 2a e4 45 d3 e2-b6 c4 37 32 ff 2a 63 6b   -.`*.E....72.*ck
    0060 - e2 eb 8d c8 1b bb 92 16-0e 03 98 fb 44 0d 44 cb   ............D.D.
    0070 - 33 64 62 4e be ba ef 46-1d 31 99 ef 69 cb ea 23   3dbN...F.1..i..#
    0080 - c2 76 69 fb 56 9d 00 23-96 e0 c1 06 c5 39 13 ac   .vi.V..#.....9..
    0090 - 2d c5 85 fb 3a 67 15 3e-37 69 06 71 f8 4f 3a 57   -...:g.>7i.q.O:W
    00a0 - 62 d2 ea 97 c6 59 0b 60-49 a1 c0 df 1c e8 3e ff   b....Y.`I.....>.
    00b0 - 32 ec 7b 57 8c 09 f6 fd-5a 08 11 df 7a 33 5d 7f   2.{W....Z...z3].
    00c0 - fd f0 fa 5e 35 7f a7 07-db ed a4 09 93 ca 96 1e   ...^5...........

    Start Time: 1683764221
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 14336
---
read R BLOCK
closed
root@jrs:/ # openssl version
OpenSSL 1.1.1h-freebsd  22 Sep 2020

**Comment by garfield69** [comment]
well, if that results came from the same machine that ran the jackett indexer, then it looks ok to me. have you tries using the indexer again, are you still getting the same error?

**Comment by sethlyons** [comment]
i'm experiencing the exact same issue on Rocky Linux 8.7.  `openssl_connect` works as above, but i get the same certificate error when trying to connect to iptorrents.
```
2023-05-10 21:50:24 | Info | Using HTTP Client: HttpWebClient
2023-05-10 21:50:24 | Info | Mono version: 6.12.0.107 (tarball Wed Dec  9 21:44:58 UTC 2020)
2023-05-10 21:50:24 | Info | Using FlareSolverr: http://127.0.0.1:8191
2023-05-10 21:50:24 | Info | Using proxy: Disabled
2023-05-10 21:50:24 | Info | App config/log directory: /home/jackett/.config/Jackett
2023-05-10 21:50:24 | Info | ThreadPool MaxThreads: 400 workerThreads, 200 completionPortThreads
2023-05-10 21:50:24 | Info | Running in Docker: No
2023-05-10 21:50:24 | Info | File /etc/issue: \S
2023-05-10 21:50:24 | Info | Jackett variant: Mono
2023-05-10 21:50:24 | Info | OS version: Unix 4.18.0.425 (64bit OS) (64bit process)
2023-05-10 21:50:24 | Info | Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5)
2023-05-10 21:50:23 | Info | Starting Jackett v0.20.4132
```

**Comment by ClintGit** [comment]
> well, if that results came from the same machine that ran the jackett indexer, then it looks ok to me. have you tried using the indexer again, are you still getting the same error?

That is what I thought too, I got my hopes up thinking it was somehow working again but when I run the test it still fails with the same error.

**Comment by garfield69** [comment]
@ilike2burnthing @mynameisbogdan well I am confused. Is it simply that the mono build uses an internal openssl module or some other openssl library which is not quite the same as the openssl cli 1.1.1h command?

**Comment by garfield69** [comment]
I see from https://www.mono-project.com that mono 6.12 is the latest version ,but the freebsd version https://www.mono-project.com/docs/about-mono/supported-platforms/bsd/ is at least 2 years old, so may not be as up to date as it could be. 
Anyway I am out of my league with this linux stuff so I am bowing out of this one.

**Comment by sethlyons** [comment]
> I see from https://www.mono-project.com that mono 6.12 is the latest version ,but the freebsd version https://www.mono-project.com/docs/about-mono/supported-platforms/bsd/ is at least 2 years old, so may not be as up to date as it could be. Anyway I am out of my league with this linux stuff so I am bowing out of this one.

my mono version is `6.12.0.107` and also has the issue.

**Comment by sethlyons** [comment]
i changed to the non-mono version and it works!

**Comment by ClintGit** [comment]
My solution to getting this working was to make a backup of my config files, uninstall the package, delete the jackett folder and install the package again. See below steps:

Stop jackett if it is running:
`service jackett stop`

Backup config files:
`cp /usr/local/jackett/ServerConfig.json /path/to/your/backup`

Backup DataProtection folder:
`tar -czvf /path/to/your/backup /usr/local/jackett/DataProtection`

Backup Indexers folder:
`cp -r /usr/local/jackett/Indexers /path/to/your/backup`

Uninstall jackett:
`pkg delete jackett`

Delete the jackett folder:
`rm -rf /usr/local/jackett`

Install jackett:
`pkg install jackett`

Restore your config files:
`cp /path/to/your/backup/ServerConfig.json /usr/local/jackett`

Restore DataProtection folder:
`tar -zxvpf /path/to/your/backup/DataProtection.tar.gz -C /usr/local/jackett/DataProtection`

Restore Indexers folder:
`cp -r /path/to/your/backup/Indexers /usr/local/jackett/`

Start jackett:
`service jackett start`

I did the same procedure for Radarr it installed the .net version somehow. Now there is a new version of radarr but I am unable to update with the web UI and there is no updated package for FreeBSD. If anyone has any pointers for getting Radarr and Sonarr updated with the .net version on FreeBSD it would be very much appreciated.  I will close this issue now.
