### ISSUE TITLE
[req]: MetalGuru

### ISSUE THREAD

**Issue by Streaming77** [Jackett/Jackett#14326]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: MetalGuru
- URL: https://metalguru.me/
- Description: MetalGuru is a Private Torrent Tracker for General with focus on Music
- Minimum Seeding Time and Minimum Ratio (if Private):  36h or 1.0 (freeleech 48h or 1.0)
- Additional Comments: signup is currently open
```
Engine: U-232 Ver.5+

**Comment by garfield69** [comment]
v0.20.4166
