### ISSUE TITLE
[req]: 

### ISSUE THREAD

**Issue by hlonza123** [Jackett/Jackett#14324]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: https://rarbgtor.org/to
- URL: https://rarbgtor.org/torrents
- Description: wont work on Jacket 
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments:
```

**Comment by garfield69** [comment]
This is an incorrectly filled in form. I don't know if this is a request to add a new indexer or a bug report for an existing indexer. Please use the correct form and fill in the appropriate information. Closing.
