### ISSUE TITLE
Yet another reverse-proxy redirect question (Apache2)

### ISSUE THREAD

**Issue by jimevans** [Jackett/Jackett#14325]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/****/.config/Jackett
Running in Docker: No
File /etc/issue: Ubuntu 20.04.6 LTS
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.4.0.0 (64bit OS) (64bit process)
Environment version: 6.0.16 (/opt/jackett/)
```

### Description

I'm sure this is simply a configuration issue, but neither the wiki, the README, nor previous similar issue reports are being helpful.
I have the following config set up for my reverse-proxy
```
   <Location /jackett>
        ProxyPreserveHost On
        Allow from 0.0.0.0
        RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
        ProxyPass "http://127.0.0.1:9117"
        ProxyPassReverse "http://127.0.0.1:9117"
    </Location>
```

I have `"BasePathOverride": "/jackett"` set in `ServerConfig.json`.

What I want: To be able to navigate to `https://mydomain.com/jackett`, and have that properly redirect to `https://mydomain.com/jackett/UI/Dashboard`.

What I see: Navigating to `https://mydomain.com/jackett` redirects to `https://mydomain.com/UI/Dashboard`.

Notes:
* Navigating to `https://mydomain.com/jackett/UI/Dashboard` works
* Navigating to `http://localhost:9117/jackett` when logged in on the host desktop works

### Logged Error Messages

```text
No logs
```

**Comment by garfield69** [comment]
the wiki at https://github.com/Jackett/Jackett/wiki/Reverse-Proxy shows the apache config should look like
```xml
  <Location /jackett>
        ProxyPreserveHost On
        Allow from 0.0.0.0 
        ProxyPass "http://127.0.0.1:9117/jackett"
        ProxyPassReverse "http://127.0.0.1:9117/jackett" 
    </Location>
```
have you tried that? (after edit it probably best to reboot your machine to ensure apache and jackett get a fresh start).
