### ISSUE TITLE
[mikan] (testing) Exception (mikan):  Received an unexpected EOF or 0 bytes from the transport stream.: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by VocAl11** [Jackett/Jackett#14322]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown

```

### Description

 An error occurred while testing this indexer

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (acgsou): Received an unexpected EOF or 0 bytes from the transport stream.: The SSL connection could not be established, see inner exception.
```

**Comment by VocAl11** [comment]
Jackett.Common.IndexerException: Exception (miobt):  Received an unexpected EOF or 0 bytes from the transport stream.

**Comment by garfield69** [comment]
Yeah, Nah. Pasting the same error message in all 3 panels does not help us help you.
Please edit the Environment section and provide the details of the system Jackett is running on. The best way to do this is to restart Jackett, access the dashboard, view the log, and copy/paste replacing the example below with the last 10 Info lines at the bottom of the log.
Then turn on the enhanced logging and provide the full error set so we can see what the inner exception is.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
