### ISSUE TITLE
[dontorrent] (testing) Exception (dontorrent): Parsing error

### ISSUE THREAD

**Issue by illegalPointer** [Jackett/Jackett#14331]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.4151-ls105)
File /etc/issue: Welcome to Alpine Linux 3.17
Jackett variant: CoreLinuxMuslAmdx64
2023-05-17 12:46:48	Info	
OS version: Unix 5.10.0.22 (64bit OS) (64bit process)
2023-05-17 12:46:48	Info	
Environment version: 6.0.16 (/app/Jackett/)
2023-05-17 12:46:47	Info	
Starting Jackett v0.20.4151
```

### Description

Lately DonTorrent has been failing. They've changed domain, but it is not only that, I've changed the domain to the one they are now using and it keeps failing with a Parse error.

Following the 302 that the base domain throws to https://dontorrent.discount/ultimos fails as well.

### Logged Error Messages

**https://dontorrent.discount/ultimos**
```text

System.Exception: Parse error
	
Error on 20230517125314 for DonTorrent.txtJackett.Common.ExceptionWithConfigData: 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//ES" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:og="http://ogp.me/ns#" xmlns="http://www.w3.org/1999/xhtml" xml:lang="es">
<head>
```

**Comment by ilike2burnthing** [comment]
Site link should be https://dontorrent.discount/

If you continue to have issues, delete the indexer, restart the container, and re-add the indexer.

**Comment by illegalPointer** [comment]
Hello, 

I have tried several times but it seems to be failing to add, without anything showing in the logs. It just fails the test. 

Previously to this status it failed with a parse error and a HTTP response that was a 302 redirection to the URL I pasted in my initial post.

**Comment by garfield69** [comment]
@illegalPointer  wrote:
>Hello, I have tried several times but it seems to be failing to add, without anything showing in the logs. It just fails the test. Previously to this status it failed with a parse error and a HTTP response that was a 302 redirection to the URL I pasted in my initial post.

Use your dashboard to edit the dontorrent config and click on any of the links on the `This indexer has multiple known URLs:` box which will load that link into the sitelink box for you.
Try each link to see it any of them work for you.

Also note that it takes time for the indexer to fetch results. For me it takes on average over 190 seconds.
