### ISSUE TITLE
[Aggregate] Invalid nCore results

### ISSUE THREAD

**Issue by chibidev** [Jackett/Jackett#1433]
I discovered a peculiar issue during the implementation of #1432. When I had IsoHunt and nCore both configured and I did an IMDB query (you'll need a 3rd tracker that supports IMDB queries in order to reproduce; RARBG will do), then nCore results are suddenly pushed out by other trackers. I didn't do a very thorough debugging, however it seems to me that whenever IsoHunt is configured, the web request nCore does doesn't return the actual results but the most recent uploads instead (i.e. the same when you log in to nCore).
As far as I checked the indexer is not doing anything wrong, and the URL and the POST params are the same in both cases (IsoHunt configured/not), so if I have to guess I'd say something happens in IWebClient that will result in nCore redirecting the query and returning the basic results instead of the correct ones. But that's just my intuition.
I'm planning to look into this, but I'm probably not the most suitable one as I'm fairly new to Jackett. I'm reporting this issue to see if anyone wants to jump in.
It is still unclear whether the issue is only present with these indexers or others might be affected as well.

System: macOS 10.12.4
Mono JIT compiler version 3.2.5 (tarball Sat Nov 22 00:07:42 PST 2014)
Copyright (C) 2002-2012 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       normal
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by kaso17** [comment]
is this still a problem?
