### ISSUE TITLE
{bug} Search rarbg via jacket different results than on web siteon site

### ISSUE THREAD

**Issue by cocokola** [Jackett/Jackett#1434]
Tried pre-release as well:
Searching for america's Next Top Model s22e02 from the website pulls up two hits.  Through your interface, none.  the possessive character may be the problem, but also noticed searching for
americas Next Top Model s22e02 works but 
america Next Top Model s22e02 does not through jacket, but works fine through the web page search.

I believe I have many other torrents with have this type of problem, and it may not only be with Rarbg.  Can you explain, or can you enhance the matching?

 I am not including logs, not sure where to find the info that needs stripped and you should be able to recreate easily..  

Jackett version:  Jackett Version 0.7.1437.0
Mono version (if not using Windows):  

-------------------------------

**Comment by chibidev** [comment]
@cocokola would you post the list of your configured trackers? Thanks.

**Comment by cocokola** [comment]
sure:

![jacket](https://cloud.githubusercontent.com/assets/9909697/26732435/38c3cd2e-477d-11e7-8b14-6a28b11f39ec.JPG)

**Comment by kaso17** [comment]
Seems like the rarbg API and website search form handles special characters slightly different.
b4948c924d2c72644bd4595ad8e29cbfaf8c3be0 should fix it for now.
Opened https://github.com/rarbg/torrentapi/issues/18 for clarification.
