### ISSUE TITLE
[bakabt] (testing) Exception (bakabt): 2,212: 2,212

### ISSUE THREAD

**Issue by Commissar0617** [Jackett/Jackett#14340]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
linux debian
```

### Description

test bakabt with prior working setup... gives [bakabt] (testing) Exception (bakabt): 2,212: 2,212
i have no idea what this means

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (bakabt): 2,212
```

**Comment by garfield69** [comment]
It may mean that you are using and old version of Jackett. 
BakaBT was updated back in 22nd April and this should not be occurring if you are on versions v0.20.3968 - v0.20.4166

If however you are on the latest version and you are seeing this error message then post back and we will reopen this ticket.
