### ISSUE TITLE
french tracker

### ISSUE THREAD

**Issue by prophetmaster** [Jackett/Jackett#1435]
is possible to add more french tracker in jackett ?

https://www.nextorrent.net
http://cpabien.xyz
https://www.omgtorrent.me

or how to add by myself ?

**Comment by kaso17** [comment]
If you've a little knowledge about HTML/CSS have a look at https://github.com/Jackett/Jackett/wiki/Definition-format

**Comment by gprime44** [comment]
I'm interested too :-) I can try create the nexttorrent indexer. We just need to create the  yml file ?

**Comment by kaso17** [comment]
@gprime44 yes, most trackers can be added/implemented via the yml cardigan definition.

**Comment by gprime44** [comment]
I've implemented nexttorrent but i've not tested now. I'm using Jackett with linuxserver docker image, did you know if i can push the yml inside container ? thx

**Comment by gprime44** [comment]
#1523

**Comment by gprime44** [comment]
http://cpabien.xyz is http://www.torrent9.cc/

https://www.omgtorrent.me doesn't have a download link to download torrent file

**Comment by ploufs** [comment]
https://github.com/Jackett/Jackett/pull/1527 pull request for cpabien.xyz

**Comment by garfield69** [comment]
cpasbien and nexttorrent have been added.
omgtorrent does not have magnet or .torrent download links on the results page.
