### ISSUE TITLE
[rarbg] (testing) Test search in RARBG => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by Akshay-Kumar** [Jackett/Jackett#14354]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
[rarbg] (testing) Test search in RARBG => Found no results while trying to browse this tracker
```

### Description

[rarbg] (testing) Test search in RARBG => Found no results while trying to browse this tracker

### Logged Error Messages

```text
[rarbg] (testing) Test search in RARBG => Found no results while trying to browse this tracker
```

**Comment by ilike2burnthing** [comment]
Please provide the environment information as requested, not copying and pasting the same useless log snippet 3 times:

> The best way to do this is to restart Jackett, access the dashboard, view the log, and copy/paste the last 10 Info lines at the bottom of the log.

Was RARBG previously working, or is this your first time using it?

Are other indexers working on the same install of Jackett?

**Comment by Paladinfeng** [comment]
- Jackett Version: v0.21.34
- Issue: [ **Rarbg** ] Search No Result
- Docker Logs:
<img width="1237" alt="image" src="https://github.com/Jackett/Jackett/assets/15520106/57a2e8a9-0e1e-45ab-8c0e-f842cacf6449">

**Comment by ilike2burnthing** [comment]
You were rate limited, try again later.

If you're using a proxy or VPN, switch server.
