### ISSUE TITLE
[req]: return an icon URL and color for indexers

### ISSUE THREAD

**Issue by fugkco** [Jackett/Jackett#14363]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Jackett can be used in a variety of places. I have created a plugin for the kodi addon elementum, which allows searching for torrents via Jackett. This often leads to a bunch of results, and makes it hard to distinguish where a torrent came from. It would be great for Jackett to return a colour code that can be consistent, across the board.

### Describe alternatives you've considered

 I've written [some code that can always return the same colour code based on the provider name](https://github.com/fugkco/script.elementum.jackett/blob/master/src/utils.py#L112-L129). The issue with that is the providers can potentially have colours that aren't necessarily associated with the provider, for example [RARBG's colour code comes back as green](https://github.com/fugkco/script.elementum.jackett/issues/16).

**Comment by ilike2burnthing** [comment]
This would serve no purpose in Jackett, so I don't think we'd ever add it. As for fixing things for your project, I could only suggest either hardcoding certain colours for popular trackers, or making it user-configurable.
