### ISSUE TITLE
[req]: Use "Series" to search for complete season packs on TV Chaos UK

### ISSUE THREAD

**Issue by Merlyn42** [Jackett/Jackett#14369]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

TV Chaos UK names complete season packs as "Series xx" instead of the typical "Season xx". This is normal British English but doesn't work when using Sonarr to search for complete seasons using Jackett.

### Describe the solution you'd like

Add "Series xx" as an alternative search for season packs for the tracker TV Chaos UK

### Describe alternatives you've considered

TV Chaos UK could change their naming scheme to the American style but their team is not willing to do that.

**Comment by garfield69** [comment]
v0.21.34
