### ISSUE TITLE
[Waffles.ch] Broken

### ISSUE THREAD

**Issue by romprod** [Jackett/Jackett#1436]
Fails to download the torrent from Waffles.ch

I've attached log file which I've removed apikeys and filenames from.

[log.txt](https://github.com/Jackett/Jackett/files/1042731/log.txt)

**Comment by kaso17** [comment]
@adamwinn can you have a look at this?

**Comment by adamwinn** [comment]
@kaso17 Sure thing

**Comment by 0naicuL** [comment]
Any updates on this/karagarga?

**Comment by adamwinn** [comment]
I wrote @kaso17 an email for clarification but haven't heard back yet.

**Comment by romprod** [comment]
Any joy on this?

**Comment by kaso17** [comment]
If someone has an invite for me (kaso1717 -at- gmail.com) I can have a look at it, should be an easy fix.

**Comment by romprod** [comment]
Invite sent

**Comment by kaso17** [comment]
thank you
fixed via 464b142130562b1c3040286ca68230674141664c
