### ISSUE TITLE
[req]: Is it possible to implment configuration of indexer by API

### ISSUE THREAD

**Issue by pf58jdz** [Jackett/Jackett#14383]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

 Is it possible to implment configuration of indexer by API
And if possible a swagger

### Describe alternatives you've considered

Make it manually for the moment

**Comment by ilike2burnthing** [comment]
Maybe for public or some very generic semi-/private indexers (e.g. only username and password, or API key, or cookie, possibly freeleech only and sort/order settings too), but so many indexers have uncommon or unique settings, which wouldn't be possible via an API (at least not a very bloated one that basically no one would use).
