### ISSUE TITLE
 [Request] New Torrent Tracker – Twilight Torrents

### ISSUE THREAD

**Issue by 1n5aN1aC** [Jackett/Jackett#1438]
Can you please add support for https://www.twilightsdreams.com/

Tracker Name : Twilight Torrents
Type : Movie, TV, Games, Music, Software, Books and Other

Indexer URL : https://www.twilightsdreams.com/
Indexer language : English
Private Tracker
I do have an invite available, if that is needed.

Twilight Torrents is a Private Torrent Tracker for MOVIES / TV / GENERAL

**Comment by Vorbroker** [comment]
I would also like to have this tracker added.

**Comment by garfield69** [comment]
registration currently closed. invite needed.
If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by tkdrob** [comment]
Signups are open now @garfield69 . It would be nice if you can add support for this tracker, too

**Comment by garfield69** [comment]
registration and login successful.

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.453

**Comment by garfield69** [comment]
https://www.twilightsdreams.com/ returns domain not found

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.twilightsdreams.com/ returns ERR_CONNECTION_REFUSED

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.twilightsdreams.com/
- [2006] dbconn: mysql_connect: MySQL server has gone away
- The server load is very high at the moment. Retrying, please wait...

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.twilightsdreams.com/
- The server load is very high at the moment. Retrying, please wait...

**Comment by garfield69** [comment]
@1n5aN1aC  @Vorbroker  @tkdrob 
Anyone have news on the status of https://www.twilightsdreams.com/, is the site just broken, or gone or moved to a new domain?
Indexer will be removed in a weeks time if there is no news or change to status.

**Comment by garfield69** [comment]
v0.20.3996
