### ISSUE TITLE
[pretome] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14388]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

The PreToMe site is offline

### Logged Error Messages

```text
cloudflare Connection timed out Error code 522
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
Just me then. I see uptime has 12 of 43 reporting timeout which is what I am still seeing. :-(
