### ISSUE TITLE
7owuun6q55apka3j7t5n5ugxlrks6qz3

### ISSUE THREAD

**Issue by vcchome** [Jackett/Jackett#14387]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Torznab 
- URL: 7OWuun6Q55APKA3J7T5N5UGxlrks6qZ3
- Description: TorrentPotato
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: 7OWuun6Q55APKA3J7T5N5UGxlrks6qZ3
```

**Comment by vcchome** [comment]
#14386 #14385 #14384 #14376 #14380 #14376

**Comment by vcchome** [comment]
- Name: Torznab 
- URL: 7OWuun6Q55APKA3J7T5N5UGxlrks6qZ3
- Description: TorrentPotato
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: 7OWuun6Q55APKA3J7T5N5UGxlrks6qZ3

**Comment by ilike2burnthing** [comment]
...what?
