### ISSUE TITLE
[REQ] New tracker - WorldWide Torrents

### ISSUE THREAD

**Issue by Arathen** [Jackett/Jackett#1439]
Requesting support for https://worldwidetorrents.eu/ please :)

Tracker Name: WorldWide Torrents
Tracker Content: Movies, TV, Games, Music, Applications, Anime, Books, Comics, Sports and Others
Tracker URL : https://worldwidetorrents.eu/
Tracker Language : English
Tracker Access: Public (Signup optional)

An RSS feed is available at https://worldwidetorrents.eu/rss.php

Many thanks!

**Comment by cesalo** [comment]
Just asking for an update .. Will this be added at some point?

Thanks.

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by garfield69** [comment]
I cannot access  https://worldwidetorrents.eu/, getting `server DNS address could not be found`.      
A Whois lookup appears to show that the domain has been suspended.      
Has been moved?      
If it has gone for good then this ticket can be closed.

**Comment by Arathen** [comment]
Domain has moved to https://worldwidetorrents.me since this ticket was opened.

**Comment by garfield69** [comment]
https://worldwidetorrents.to/ currently returning Error 522 Connection timed out
is site broken, gone, or new domain?

**Comment by garfield69** [comment]
removed wwt. in the unlikely event they return we can always add them back.
