### ISSUE TITLE
The content under some Categories cannot be searched

### ISSUE THREAD

**Issue by PN62323424** [Jackett/Jackett#14393]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
running in docker :yes
x86/64
synology
```

### Description

Some content under the 404 Categories of the kp.m-team.cc site cannot be searched，I'm sure I've checked 100404 in sonarr, but I've tried several episodic documentaries and they don't search

By the way I also tried prowlarr, also can't search, but can search in jackett alone to search

### Logged Error Messages

```text
05-28 21:55:33 Info Torznab search in M-Team - TP (2FA) for Story of Chuaner S01 => Found 0 releases [13941ms]
```

**Comment by ilike2burnthing** [comment]
In Jackett, perform a keywordless/empty search using only category 404. Does it return results?

Next, perform a keyword search using only category 404, for something you know definitely exists in that category. Does it return results?

Next, perform the same keyword but with no categories selected. Does it return the same results from category 404 (or return category 404 results that were previously missing?

**Comment by PN62323424** [comment]
In Jackett, perform a keywordless/empty search using only category 404. Does it return results?

yes

Next, perform a keyword search using only category 404, for something you know definitely exists in that category. Does it return results?

yes

Next, perform the same keyword but with no categories selected. Does it return the same results from category 404 (or return category 404 results that were previously missing?

no，the results is same

**Comment by PN62323424** [comment]
> Can you enable enhanced logging and provide me the exact URL that doesn't work?

yes，thanks for your help!

https://temp-file.org/68YGLlriiRgi78X/file

**Comment by PN62323424** [comment]
sorry

https://file.io/hKl2xjjq6Ysk

**Comment by PN62323424** [comment]
> @ilike2burnthing it's our buggy friend from #13697 described by @garfield69.
> 
> > sorry
> 
> Don't worry, I managed to work around it.
> 
> Any reason you're using categories like 100404 in Sonarr?

Because many resources are posted under 100404, such as some episodic documentaries, some variety festivals. This site is posted like this

**Comment by PN62323424** [comment]
That's what I thought, but I picked a few more because I was worried about the irregularity of the site posting.

Is it a problem on the site side so far, or is it a problem with my usage?

By the way, it would be great if jacket could control the search frequency of some sites (or allow users to control themselves?). . For example, kp.m-team.cc, which is probably the largest site in Asia, can only search once a minute at most, more will be briefly blocked

**Comment by ilike2burnthing** [comment]
This will hopefully be fixed [soon](https://github.com/Jackett/Jackett/pull/14353), but for now limit your categories in any particular search to only:
`401, 419, 420, 421, 439, 403, 402, 435, 438, 404, 405, 407, 422, 423, 427, 409`
OR
`410, 429, 424, 430, 426, 437, 431, 432, 436, 425, 433, 411, 412, 413` (adult)
OR
`406, 408, 434` (music)

However, in Sonarr you should only be using `403, 402, 435, 438, 404, 405, 407`.

If there are TV results in other categories, that's an issue for the tracker to resolve.
