### ISSUE TITLE
[torrentland] (testing) Exception (torrentland): Login failed: No form found on https://torrentland.li/login using form selector form[action$="/login"]: Parse error

### ISSUE THREAD

**Issue by clonbg** [Jackett/Jackett#14392]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
An error occurred while testing this indexer
Exception (torrentland): Login failed: No form found on https://torrentland.li/login using form selector form[action$="/login"]: Parse error
Click here to open an issue on GitHub for this indexer.
```

### Description

 An error occurred while testing this indexer
Exception (torrentland): Login failed: No form found on https://torrentland.li/login using form selector form[action$="/login"]: Parse error
Click here to open an issue on GitHub for this indexer.

### Logged Error Messages

```text
Dont work torreland indexer
```

### Screenshots

![Screenshot_20230528_131145_us spotco fennec_dos](https://github.com/Jackett/Jackett/assets/3451012/53ec0cb5-0aa7-4f41-9efe-26b1b273899e)

**Comment by ilike2burnthing** [comment]
Was previously down - https://github.com/Jackett/Jackett/issues/12600

It's now back up, try again.

If you still have issues, try the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#login-failed-selector
