### ISSUE TITLE
DropDown list needed for Provider settings

### ISSUE THREAD

**Issue by JigSawFr** [Jackett/Jackett#144]
Hello,
A really usefull feature could be to add a dropdown list option for providers settings.
It's not very intuitive to use N x Yes/No instead of one select list :)
Thanks you !

**Comment by raspdealer** [comment]
yes

**Comment by armani316** [comment]
@JigSawFr @raspdealer Is this still relevant with the new, list-based Jackett interface? I wasn't using Jackett around the time this issue was opened, so it sounds like the Yes/No option was used back then but not anymore? 

If my understanding is incorrect, please elaborate.

**Comment by armani316** [comment]
@kaso17 Do you think this still makes sense in light of the new table-based Jackett interface?

**Comment by kaso17** [comment]
I've also no idea. Closing for now

Do you need a select item for some indexer configuration settings?
That shouldn't be to hard to add.

**Comment by armani316** [comment]
@kaso17 I think that's what @JigSawFr meant, but I'm not sure which settings.
