### ISSUE TITLE
[cinemaz] (testing) Exception (cinemaz): Unknown error (0x80090304): The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by AnythingOldSkewl** [Jackett/Jackett#14401]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
I am using a seedbox with Ubuntu 22.04 installed. Installed Jackett using Wine 8.01
```

### Description

This showed for 90% of my trackers. I can't figure it out.

### Logged Error Messages

```text
please see screenshot
```

### Screenshots

![Jackett 1](https://github.com/Jackett/Jackett/assets/42495993/7b68a692-8dc2-412b-9efa-b10b2e88c5f0)

&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

![Jackett 2](https://github.com/Jackett/Jackett/assets/42495993/9d45fcf7-7c88-4dd9-85be-a85305d75de7)

**Comment by ilike2burnthing** [comment]
Try the troubleshooting steps here:
https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work-the-ssl-connection-could-not-be-established
and here:
https://github.com/Jackett/Jackett/wiki/Troubleshooting/#a-connection-attempt-failed

If some of these steps are outside of your control, and the rest don't work, contact your seedbox support.

**Comment by ilike2burnthing** [comment]
> Running Windows apps with Wine on Linux, what could go wrong. 👍

Oh waoh, I missed that.

Yeah, don't do that, there are native Linux versions available, use those.

**Comment by AnythingOldSkewl** [comment]
> Try the troubleshooting steps here: https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work-the-ssl-connection-could-not-be-established and here: https://github.com/Jackett/Jackett/wiki/Troubleshooting/#a-connection-attempt-failed
> 
> If some of these steps are outside of your control, and the rest don't work, contact your seedbox support.

Yeah, that didn't seem t work. It's odd, it seems to happen where randomly only one tracker gives results. Never seen this before. To be honest, I consider myself an intermediate user of Linux. I've learned a lot, but I'm no were near "master user." My feeling is, most of my troubles come from bad/outdated scripts and defunct repositories. It's very frustrating. How could a programmer update one area and fail to make sure that the rest is functional? I'll create a ticket with my seedbox. Thank you.

**Comment by AnythingOldSkewl** [comment]
> > Running Windows apps with Wine on Linux, what could go wrong. +1
> 
> Oh waoh, I missed that.
> 
> Yeah, don't do that, there are native Linux versions available, use those.

I always try to install the native Linux versions, but they don't all seem to work, and they look like they don't work because of outdated repositories. I'm not all that proficient with Linux, and I don't know how to, of feel that I should be digging for repositories or prerequisite programs I know nothing about.

**Comment by AnythingOldSkewl** [comment]
> Try the troubleshooting steps here: https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work-the-ssl-connection-could-not-be-established and here: https://github.com/Jackett/Jackett/wiki/Troubleshooting/#a-connection-attempt-failed
> 
> If some of these steps are outside of your control, and the rest don't work, contact your seedbox support.

Hi! Forgive me, I spoke prematurely. After I tried the script, I didn't realize I had to reboot my seedbox. Jackett appears to be working now! Thank you so much!!
