### ISSUE TITLE
[yggtorrent] (updating) Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match

### ISSUE THREAD

**Issue by Wells83** [Jackett/Jackett#14404]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-05-30 16:33:33 	Info 	

Using HTTP Client: HttpWebClient2

2023-05-30 16:33:33 	Info 	

Using FlareSolverr: http://192.168.2.2:8192

2023-05-30 16:33:33 	Info 	

Using proxy: Disabled

2023-05-30 16:33:33 	Info 	

App config/log directory: C:\ProgramData\Jackett

2023-05-30 16:33:33 	Info 	

ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads

2023-05-30 16:33:33 	Info 	

Running in Docker: No

2023-05-30 16:33:33 	Info 	

Jackett variant: CoreWindows

2023-05-30 16:33:33 	Info 	

OS version: Microsoft Windows NT 10.0.17763.0 (64bit OS)

2023-05-30 16:33:33 	Info 	

Environment version: 6.0.16 (C:\ProgramData\Jackett\)

2023-05-30 16:33:29 	Info 	

Starting Jackett v0.21.88
```

### Description

impossible to add ygg tracker

### Logged Error Messages

```text
An error occurred while updating this indexer
Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match
Click here to open an issue on GitHub for this indexer.
```

**Comment by buddyqc69** [comment]
i have the right page, now that the login form on YGGT..

that can change anything i think

`<form action="/user/login" method="post" id="user-login">
		<input type="text" name="id" placeholder="Pseudo" required="">
		<input type="password" name="pass" placeholder="Mot de passe" required="" autocomplete="off"> 
		<center id="resetpass" style=" margin: 10px 10px;  font-weight: bold;"><a href="https://www3.yggtorrent.do/user/reset_password">Mot de passe oublié ?</a></center>
		<input type="hidden" name="ci_csrf_token" value="">
		
										
		<button type="submit">Connexion <i class="ico_unlock"></i></button>
	</form>`

**Comment by garfield69** [comment]
Users that have had problem in the last couple days with YGG found that by upgrading their jackett to the very latest version (currently v0.21.90) resolved their problem.
Have you tried the latest version?
