### ISSUE TITLE
[Putao] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14418]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

The PuTao site is offline

### Logged Error Messages

```text
https://pt.sjtu.edu.cn/ ERR_CONNECTION_TIMED_OUT
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://pt.sjtu.edu.cn/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14418#issuecomment-2143980340

**Comment by garfield69** [comment]
online
