### ISSUE TITLE
[Peers.FM] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14419]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

The Peers.FM site is offline

### Logged Error Messages

```text
https://peers.fm/ ERR_CONNECTION_TIMED_OUT
```

**Comment by ilike2burnthing** [comment]
back up
