### ISSUE TITLE
Freeleech Only missing for SpeedApp

### ISSUE THREAD

**Issue by fedonr** [Jackett/Jackett#14413]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Description

The option to Search Freeleech only which is availalble for other Private Trackers like Torrentleech, Digitalcore, etc is missing in SpeedApp.

**Comment by garfield69** [comment]
Requires upgrading the c# speedapptracker, which is an abstract used by both the speedapp indexer and the retroflix indexer.
Complicated in part by the fact that while speedapp does not support searching for freeleech, retroflix does.
So the speedapptracker would need to be able to support two freeleech modes, a Filter Freeleech for speedapp, and a Search Freeleech for retroflix.

**Comment by garfield69** [comment]
v0.21.114

**Comment by fedonr** [comment]
Hey @garfield69 thanks a lot, for such amazingly quick fix to you and all the other devs involved. This is one reason I using Jackett without even considering any other option. And it works great. Thanks a lot.

**Comment by fedonr** [comment]
There is some bug here, as now even tho it works but not completely, it detects only few torrents from freeleech while ignores the rest.

Example: Fast X is available in HD, FHD and UHD under Freeleech but it only detects the old Cam Print

> v0.21.114
