### ISSUE TITLE
[seedfile] (updating) Address not available (www.seedfile.ro:443): Address not available

### ISSUE THREAD

**Issue by Alex-Goaga** [Jackett/Jackett#14425]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.1.120:8191
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.128-ls109)
File /etc/issue: Welcome to Alpine Linux 3.17
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.4.106.1 (64bit OS) (64bit process)
Environment version: 6.0.16 (/app/Jackett/)
2023-06-05 16:31:30	Info	
Starting Jackett v0.21.132
```

### Description

1) Click on the Add indexer button
2) Search for SeedFile
3) Click configure / add user and pass etc etc
4) Note that www.seedfile.ro:443): Address not available error is displayed

### Logged Error Messages

```text
An error occurred while updating this indexer
Address not available (www.seedfile.ro:443): Address not available
```

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed
