### ISSUE TITLE
FlareSolverr + Proxy with Auth

### ISSUE THREAD

**Issue by sklose** [Jackett/Jackett#14422]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Info Environment version: 6.0.16 (/app/Jackett/) 
Info OS version: Unix 5.19.0.43 (64bit OS) (64bit process) 
Info Jackett variant: CoreLinuxMuslAmdx64 
Info File /etc/issue: Welcome to Alpine Linux 3.17 
Info Running in Docker: Yes (image build: v0.21.114-ls108) 
Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
Info App config/log directory: /config/Jackett 
Info Using proxy: Socks5 
Info Using FlareSolverr: http://flaresolverr:8191
Info Using HTTP Client: HttpWebClient2
```

### Description

Configure a proxy that requires authentication + FlareSolverr. FlareSolverr will receive the proxy name on each request, but not the credentials. All FlareSolverr requests fail. Possible solution: don't send a proxy URL to FlareSolverr if authentication is required (or make the behavior configurable).

### Logged Error Messages

```text
From FlareSolverr:

Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://....', 'proxy': {'url': 'socks5://sto.socks.ipvanish.com:1080'}}
Error: Error solving the challenge. Message: unknown error: net::ERR_SOCKS_CONNECTION_FAILED ...
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/657
