### ISSUE TITLE
[World of Tomorrow] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14423]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

The World of Tomorrow site is offline

### Logged Error Messages

https://w-o-t.pro/ HTTP ERROR 500
[edit] Uptime shows 9 of 43 checkpoint are ok, the rest http protocol error

**Comment by ilike2burnthing** [comment]
back up (confirmed with Uptrends)

**Comment by garfield69** [comment]
https://w-o-t.pro/ ERR_CONNECTION_REFUSED or ERR_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14423#issuecomment-1690602735

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
v0.24.1261
