### ISSUE TITLE
[req]: Question, Sorting.

### ISSUE THREAD

**Issue by johnproteam** [Jackett/Jackett#14426]
Starting Jackett v0.21.132

How do i sort results by latest? 
For example YTS, currenty those are the first entries on the site
![image](https://github.com/Jackett/Jackett/assets/118519433/805539e2-74fd-451d-9ee7-40e67e84dec7)

But, on the api they are completely diff, in the api i got "Fire Island (2023) 1080p WEBRip -YTS" as the first one.

I have the same situation with torrentgalaxy for example..

**Comment by garfield69** [comment]
IF you use your browser and try https://yts.mx/api/v2/list_movies.json?limit=50&sort_by=date_added&order_by=desc
you will find that the results differ in content from what you get if you use https://yts.mx/browse-movies

Nothing we can do about it.
