### ISSUE TITLE
Request New Torrent Tracker – Bibliotik

### ISSUE THREAD

**Issue by swablueme** [Jackett/Jackett#1443]
Can you please add support for bibliotik.me
Tracker Name: Bibliotik
Type: Audio/Audiobook, Books, Books/Ebook, Books/Comics, Books/Magazines, Books/Technical

Indexer URL: bibliotik.me
Indexer language : English
Private Tracker

**Comment by garfield69** [comment]
registration currently closed. invite needed.
If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by garfield69** [comment]
@the6step no signs of an invite email from bibliotik in my inbox or spam box so far. 
perhaps the site blocks outlook, or maybe you are supposed to manually email the invite code rather than the site doing it for you outomatically?
if you need an alternate email then you can use garfieldsixtynine at gmail.com

**Comment by JohanSF** [comment]
Hey garfield69, I actually sent you an email that I would be willing to cooperate about this, as I have an account and invites are currently disabled at bibliotik. Of course this means I would do testing for you and not share my account. Did you not receive that email? I sent it to garfield69@outlook.com with my discord and telegram handles.

**Comment by garfield69** [comment]
@JohanSF Thank you for the offer.
However, it's not practical to do what you suggested. 
Building an indexer requires (at least for me) requires lots of coding-test-repeat cycles, as I often find the sites return results in different ways than I expect (usually because I have not interpreted the HTML correctly the first time, or I've coded a selector that is too general and needs to exclude other hits).
Doing this through a 3rd party would be a time consuming process I'm just not prepared to go through.

Then only practical way is for me to have an account so I can perform the code-test-repeat as often and as quickly as I need to and get the job done.

**Comment by JohanSF** [comment]
I completely understand.

For a long time their invite-system has been completely turned off, who knows when it will open again. :/

Implementation with jackett would be a huge game changer for my ebook-stack though :D

**Comment by takosine** [comment]
I've opened a PR for this here: https://github.com/Jackett/Jackett/pull/6840

Bibliotik doesn't provide an API so it was a bit annoying, but seeing as no one else seems to have access I wanted to take a stab.

**Comment by garfield69** [comment]
Jackett 0.12.1470

**Comment by a-nunes** [comment]
It's not working properly for me. It says "Found no results while browsing this tracker". But if I get the log, it found some results, but the parser doesn't get it.

This is the error:

System.Exception: Error while parsing field=files, selector=.t_files_size_added, value=1		 file,
				128.33 MiB
        4 hours, 36 minutes ago: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1561

**Comment by mattjmorgan** [comment]
> It's not working properly for me. It says "Found no results while browsing this tracker". But if I get the log, it found some results, but the parser doesn't get it.
> 
> This is the error:
> 
> System.Exception: Error while parsing field=files, selector=.t_files_size_added, value=1 file,
> 128.33 MiB
> 4 hours, 36 minutes ago: Input string was not in a correct format.
> at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1561
> 
> Edit: I solved the problem by removing the parsing field "files", but I think the solution is to review the regex used.

Same problem here.. Which files did you remove?

**Comment by a-nunes** [comment]
You have to go to src/Jackett.Common/Definitions/bibliotik.yml and remove the section:

      files:
        selector: .t_files_size_added
        filters:
          - name: regex
            args: "(\\d+) file"

It's returning some error because this regex is not returning the proper information, but I don't know about regex to fix, so I deleted this part,  this workaround works for me.

**Comment by garfield69** [comment]
the problem is simply that the filter name is wrong.
please replace `regex` with `regexp` and report if that solve the issue.
I don't have an a/c in this site so I cannot test for myself.
If you report success I will amend the official source ;-)

**Comment by a-nunes** [comment]
It didn't work.

Here is the HTML returned:

	<td class="t_files_size_added">
		14		 files, 				350.62 MiB<br>
		<time datetime="2020-01-13T14:45:43Z">4 hours, 43 minutes ago</time>

And here is the new error:

System.Exception: Error while parsing field=files, selector=.t_files_size_added, value=: Input string was not in a correct format.

The other one seems to return more information. This one returned just a ':' after value=

**Comment by garfield69** [comment]
Ah. ok.
so we currently go looking and expecting to find `14 file` in the string, but there appears to be more than one space between the `14` and `files,` from what your html returned.
so change `args: "(\\d+) file"` to `args: "^\\s*(\\d+)\\s*file"` and see if that works.
if after this it still does not work then I will just remove the files section like you did before.
Thanks.

**Comment by mattjmorgan** [comment]
Still no... error is:

```
System.Exception: Error while parsing field=files, selector=.t_files_size_added, value=1		 file,
				1.31 MiB
        1 day, 3 hours ago: Input string was not in a correct format.
```

**Comment by garfield69** [comment]
Jackett 0.12.1572

**Comment by mihaixxl** [comment]
give me inviation on bibliotik.me on email mihail-didu@mail.ru

**Comment by garfield69** [comment]
@mihaixxl  This GitHub site is a support site for the Jackett app and the indexers written to access tracker web sites.
The initial invite request at the start of this ticket is raised so that the indexer developer can create the indexer and test it. 

This GitHub site is **not** a forum to solicit invites for personal use.
Please look elsewhere.

**Comment by Rilbow** [comment]
Hi, would there be any chance for me to get a log in to access the site?  I've got 4 kids going to school here in Belgium and they have access to an e-reader and i cant always find the books that they need .

Would greatly appreciate any help I can get!

Kind regards,

Eric @  greenielw@gmail.com

**Comment by garfield69** [comment]
@Rilbow  Sorry. This is a support site for the Jackett app and not a forum to solicit invitations to sites.
Please look elsewhere.
