### ISSUE TITLE
[torrentland] Reporting wrong torrent age and size

### ISSUE THREAD

**Issue by Potajito** [Jackett/Jackett#14437]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

Hi,
These couple of days, it seem that jackett (also prowlarr) report wrong torrent age (0 minutes) and size (very low amount of Bytes).
Account looks fine, is in good standing, meets the thanks requirements, has rss and api access and has good standing.
![image](https://github.com/Jackett/Jackett/assets/39760810/c2fd7a08-a85c-402b-8e0b-d68dee6b3c63)

It also seems to report the wrong seed/leachers ratio.

![image](https://github.com/Jackett/Jackett/assets/39760810/ffef709c-e8c9-46eb-a24f-86ec8df7644b)

Any idea?
Thanks!

### Logged Error Messages

```text
doesnt seem to be any explicit error.
```

**Comment by garfield69** [comment]
v0.21.177
