### ISSUE TITLE
Anidex Test issue

### ISSUE THREAD

**Issue by rubimpassos** [Jackett/Jackett#1444]
Anidex don't work with latest upate. Test failed, see log.
[log.txt](https://github.com/Jackett/Jackett/files/1050098/log.txt)

Jackett version:  0.7.1469.0
I'm on Windows 10

-------------------------------

**Comment by kaso17** [comment]
I broke it during the last update. It no longer works if no category is specified, please specify categories in the settings or your torznab queries. Will fix it soon.

**Comment by CodeMonkey626** [comment]
@kaso17 Plz fix Anidex. :P

I looked at it last night and there's two problems, the first is that the if else parsing doesn't handle a nested a range expression, so the previous category setting that @aeonlucid added is now broken (there's a `{{end}}` added into the url).

The second is that I think Cardigann is going to have to be updated to allow for an explicit separator character for range expressions. Unless you can somehow use the existing trim filter to strip off a trailing comma.

**Comment by kaso17** [comment]
reverted to the fixed category (fa56b1d15f39132be6912459414e7e60d8ccdf38) until we find time to fix and improve the templating engine.
