### ISSUE TITLE
[req]: rargb.to 

### ISSUE THREAD

**Issue by saw1543** [Jackett/Jackett#14446]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: rargb.to 
- URL: https://rargb.to/
- Description: this site still workking
- Minimum Seeding Time and Minimum Ratio (if Private): no
- Additional Comments:
```

**Comment by garfield69** [comment]
https://torrentfreak.com/dodgy-rarbg-knockoffs-thrive-as-former-users-seek-refuge-230606/

**Comment by Altansar69** [comment]
can you use that: https://ipfs.io/ipfs/QmbpRxBZ5HDZDVRoeAU8xFYnoP4r5eGCxdkmfFW3JbA6mq/ 
?

**Comment by tifo71** [comment]
> No. The official therarbg domain is `https://therarbg.to/` , as per [#14685 (comment)](https://github.com/Jackett/Jackett/issues/14685#issuecomment-1806831355)

yes it's good it work sorry. I had modified the url in the settings, I deleted it and everything works.

**Comment by AARON8888** [comment]
Hi @garfield69!
Can you check site? It seems now is working well and maybe possible to add to Jackett.
I realised that no possible to find IMDb id instead. This is a pity.

**Comment by ilike2burnthing** [comment]
Read above.
