### ISSUE TITLE
ShareIsland - Global Freelech not recognized in download/upload volume factor

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#14443]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Installed from docker -> Jackett Version v0.21.186
```

### Description

Hi,
Currently, the tracker is in Global Freelech mode and uploads are counted double.
So, would be:
Downloadvolumefactor -> 0
Uploadvolumefactor -> 2
In the rss file however, this is not recognized.
I tried to fix the definition, but I saw that everything has changed, and I don't know where I have to put my hands to fix it anymore, I seem to remember that you used to parse the code (images or text) and set the volumes from there.

Maybe if you tell me what file I can edit, I can fix it on my own, otherwise I have to wait for you.

Thank you

Jo

### Logged Error Messages

```text
No error
```

**Comment by ilike2burnthing** [comment]
We're using the API, not crawling the site, and the API is returning `"freeleech": "0%",`, so there's nothing we can do about it on our end.
