### ISSUE TITLE
[lostfilm] (testing) Exception (lostfilm): certificate validation failed: [Subject]  CN=***.duckdns.org[Issuer]  CN=R3, O=Let's Encrypt, C=US[Serial Number]  03B98497D6E05456BACF497474E85E533A54[Not Before]  5/6/2023 1:13:18AM[Not After]  8/4/2023 1:13:17AM[Thumbprint]  EFC31CFFA8D58C14729FA4124C317CF4B4875B62: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by m0t0rh3ad** [Jackett/Jackett#14441]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
jackett used as Docker, Flaresolver is installed
```

### Description

Lostfilm indexer disappeared frim Indexers List and not working, by the way the site mentioned for indexer - https://www.lostfilm.run is not reachable, but other mirrors are working, for example https://www.lostfilm.tv

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (lostfilm): certificate validation failed: [Subject] CN=***.duckdns.org [Issuer] CN=R3, O=Let's Encrypt, C=US [Serial Number] 03B98497D6E05456BACF497474E85E533A54 [Not Before] 5/6/2023 1:13:18AM [Not After] 8/4/2023 1:13:17AM [Thumbprint] EFC31CFFA8D58C14729FA4124C317CF4B4875B62 : The SSL connection could not be established, see inner exception.
```

### Screenshots

![2023-06-09_](https://github.com/Jackett/Jackett/assets/29656275/55d878b3-5d45-42bb-895c-8eef8c4bdaa0)

**Comment by garfield69** [comment]
The certificate presented has a CN=*duckdns* which is an amazon dynamic DNS host.
Since this is not an official CA from the lostfilm sites (which have CN=lostfilm.*, the only conclusion is that you are being blocked by your router or ISP or something.
Have you tried any of the other alternate links in the lostfilm config?
Remember that you may have to open and close the config at least once whenever the prior site has loaded a captcha challenge for you to fill, since, once you change the sitelink to an alternate you need to load its own new challenge by opening the config afresh with the new site link already loaded..

**Comment by garfield69** [comment]
>Lostfilm indexer disappeared frim Indexers List and not working

you mean it disappeared from your active indexer page or do you mean it is missing from the add-indexer page?

**Comment by m0t0rh3ad** [comment]
> it is missing from the add-indexer page
 it is missing from the add-indexer page - correct

**Comment by garfield69** [comment]
and if you restart Jackett does it show up again, in either the add-indexer or the active list page?

**Comment by freeball155** [comment]
lostfilm.run domain is expired, suspended or something other happend:

nslookup -q=any www.lostfilm.run 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	www.lostfilm.run
Address: 127.0.0.1
www.lostfilm.run
	origin = ns1.verification-hold.suspended-domain.com
	mail addr = admin.suspended-domain.com
	serial = 2012022012
	refresh = 7200
	retry = 7200
	expire = 172800
	minimum = 7200
 
You can remove "old" lostfilm.run and add new one with lostfilm.tv URL.

**Comment by garfield69** [comment]
@ilike2burnthing  rebuttal?

**Comment by ilike2burnthing** [comment]
None, it appears to be very dead for me too, and SSL checker sites are returning their own certs as well. Will remove.

**Comment by garfield69** [comment]
v0.21.188
