### ISSUE TITLE
[REQ]add these sites if it's possible

### ISSUE THREAD

**Issue by Rafielreca** [Jackett/Jackett#1445]
Add support to these sites please
- [x] mega-bliz.nl [959f66ad787c3515bef76f8b6f2f8687c7d61227]
- [x] nextorrent.net redirects to nextorrent.tv [616b4366489f95628843b0a5ccc4d9d28b263072]
- [x] rutor.info [ea7421ea935b2351cd29ae0bc068396f1873a7e7]
- [x] gfxnews.org [9139e64762462d28c187dfa008aaccb43925bd92]
- [x] bigtower.info(general) [f7bf8fba40b6ec81561d4e196879f5d941f9ada1]
- [x] elittorent.us(general) [15412c25084151c6cc94a4fa2923cba7230ce57e]
- [x] worldwidetorrents.eu(General) is now worldwidetorrents.me [db476951fe659ceadd29cdbf73028230fbf9e6d9]
- [x] aftershock-tracker.eu(General) [1ab02d3d6d74ba5ad50735e184b664bf5d9d791c]
- [ ] bitsite.us: HUNGARIAN/Private (MOVIES / GENERAL) [registration closed 01-nov-2017]
- [ ] ~~tvunderground.org.ru~~ : (tv/Documentary) [semi-private, no magnets or .torrents, just ED2K]
-------------------------------

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.10 for aftershock

**Comment by garfield69** [comment]
aftershock at https://aftershock-tracker.eu/ ruturning a Plesk setup page.
Crashed, gone, or moved to another domain?

**Comment by garfield69** [comment]
aftershock is back, normal operations resumed.

**Comment by garfield69** [comment]
mega-blitz https://mega-bliz.nl/ returning ERR_CONNECTION_TIMED_OUT
is the site gone, changed domain or just broken?

**Comment by garfield69** [comment]
gfxnews currently returning `Could not connect to the database 'localhost'`

**Comment by garfield69** [comment]
gfxnews now returning 504 gateway timeout
```
Gateway Time-out
The gateway did not receive a timely response from the upstream server or application.

Apache/2.2.15 (CentOS) Server at forum.gfxnews.org Port 80
```

**Comment by garfield69** [comment]
removing magabliz and gfxnews.
in the unlikely event they return we can always add them back.

**Comment by garfield69** [comment]
http://elittorent.us/ returning ERR_CONNECTION_REFUSED
just me or is the site broken, gone or moved to a new domain?

**Comment by garfield69** [comment]
still getting ERR_CONNECTION_REFUSED from http://elittorent.us/
anyone have any news?

**Comment by garfield69** [comment]
https://aftershock-tracker.net/ returns
![image](https://user-images.githubusercontent.com/6933240/179642554-36c56d23-c6b9-4e92-b219-41c593ed3fb1.png)
site broken, gone or moved to a new domain?

**Comment by ilike2burnthing** [comment]
back up
