### ISSUE TITLE
[1337x] (testing) Exception (1337x): No such host is known.: No such host is known. (1337x.to:443)

### ISSUE THREAD

**Issue by dillingerdisco7** [Jackett/Jackett#14456]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
Environment version: 6.0.16 (C:\ProgramData\Jackett\)
```

### Description

Its not finding 1337x

### Logged Error Messages

```text
Everything is listed above from what I saw.
```

**Comment by dillingerdisco7** [comment]
Wasn't thinking so, but maybe? 4 others work except this and rarbg. Same
issue there. Other than that other trackers are connecting fine. I'll poke
around with some network settings and see.

**Comment by ilike2burnthing** [comment]
You left the Jackett version out of your environment information, but if you're still seeing RARBG as an available indexer then Jackett is out of date. Update and try again.

Can you access https://1337x.to in browser on the same device as Jackett? If not, you'll need to change your DNS, use a VPN or proxy, or reconfigure the indexer to use one of the other sitelinks.

**Comment by dillingerdisco7** [comment]
Well guess that explains that one at least...shame.

**Comment by dillingerdisco7** [comment]
Yeah, switched up the DNS and it's good to go.

Any idea why that would work fine under the same settings for 3 months,
then stop without any changes on my end? Switched isp in March, worked fine
until a few days ago with no manipulation...

Just curious if there's something I should look out for

**Comment by ilike2burnthing** [comment]
No idea, might even just be a temporary issue, but if you've found a DNS that works, then happy days.

Current version is [v0.21.207](https://github.com/Jackett/Jackett/releases/tag/v0.21.207).
