### ISSUE TITLE
[u2]: incorrect freeleech search

### ISSUE THREAD

**Issue by trim21** [Jackett/Jackett#14458]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.21.205
```

### Description

https://github.com/Jackett/Jackett/blob/19de5f46b0635c9250cb463dfa2c3f2aebe47781/src/Jackett.Common/Definitions/u2.yml#L97-L98

`8` is not all promotions, it's "0 and not (1 or 2 or 3 or 4 or 5 or 6 or 7)"

### Logged Error Messages

```text
null
```

**Comment by trim21** [comment]
> Provide an URL with the correct freeleech argument.

There is no correct freeleech argument

**Comment by trim21** [comment]
https://github.com/Jackett/Jackett/blob/19de5f46b0635c9250cb463dfa2c3f2aebe47781/src/Jackett.Common/Definitions/u2.yml#L97-L98

all of `2`, all of `4` and some of `8` are freeleech, and also, some of `8` is not free.

and this tracker doesn't support `or` filter with multiple `spstate`.

**Comment by garfield69** [comment]
v0.21.235
