### ISSUE TITLE
[req]: Movieworld (Flicker)

### ISSUE THREAD

**Issue by Altansar69** [Jackett/Jackett#14454]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: MovieWorld
- URL: https://movieworld.pics/
- Description: MovieWorld is a Semi-Private Torrent Tracker for MOVIES / TV / 3X
- Minimum Seeding Time and Minimum Ratio (if Private): 3 days
- Additional Comments:
engine: xbtitFM v4.1.26
```

**Comment by ilike2burnthing** [comment]
Torrents available at https://movieworld.pics/index.php?page=torrents without an account, can download even though PID is `00000000000000000000000000000000`.

Created an account to see if there were more available. Was told there would be a verification email, haven't gotten one (used gmail). When I sign in anyway, the login form is still available, but I get `You’re not authorized to view the Torrents!` when trying to access the torrents page (can access it in a private/incognito window).

@Altansar69 do you have a working account for the site?

**Comment by ilike2burnthing** [comment]
Never got an email, but my account has now been approved, there are more torrents.

**Comment by Altansar69** [comment]
sorry I just saw your message, yes my account is working. But you don't seem to need it anymore.

**Comment by garfield69** [comment]
v0.21.235

**Comment by Neotastisch** [comment]
I have the same problem

**Comment by ilike2burnthing** [comment]
What problem?

**Comment by Neotastisch** [comment]
> Torrents available at https://movieworld.pics/index.php?page=torrents without an account, can download even though PID is `00000000000000000000000000000000`.
> 
> Created an account to see if there were more available. Was told there would be a verification email, haven't gotten one (used gmail). When I sign in anyway, the login form is still available, but I get `You’re not authorized to view the Torrents!` when trying to access the torrents page (can access it in a private/incognito window).
> 
> @Altansar69 do you have a working account for the site?

**Comment by ilike2burnthing** [comment]
Wait for a few hours, seems they have to be manually approved.

**Comment by Altansar69** [comment]
Yeah my account work @Neotastisch
How can i help you ?

**Comment by ilike2burnthing** [comment]
They're quoting my earlier comment, not asking you.

**Comment by Altansar69** [comment]
oh, yeah sorry.

**Comment by garfield69** [comment]
https://movieworld.pics/
```
Link opens in a new tab so when done come back here & refresh to continue.
Your license is invalid, please vaildate your license [Here](https://movieworld.pics/include/activate.php).
Only the owner of this site can activate the license so if your not the owner Please Do Not Try & contact the owner about this.


The site is under maintenance.
Do not click and do not enter your site credentials because it is a license update problem.
Please try again later or press F5 on your keyboard to refresh the page.
Thanks for your understanding.
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://movieworld.pics/ HTTP Test Page powered by CWP | CentOS-WebPanel.com

**Comment by garfield69** [comment]
v0.21.2404
