### ISSUE TITLE
Issues with HAProxy

### ISSUE THREAD

**Issue by ZoltrixGFC** [Jackett/Jackett#14455]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.205-ls110)
File /etc/issue: Welcome to Alpine Linux 3.17
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.4.0.150 (64bit OS) (64bit process)
Environment version: 6.0.18 (/app/Jackett/)
Starting Jackett v0.21.205
```

### Description

Attempting to get Jackett working via HTTPS and HAProxy.

Jackett works via the HAProxy except when trying to login, and when trying to use the https address in Sonarr.

Eg, if I've already logged into Jackett and open https://subdomain.domain.tech, the Jackett web interface loads fine.

If I try and access the URL and Jackett isn't logged in, I receive a "A potential DNS Rebind attack" and it attempts to load the URL https://subdomain.domain.tech:10443/?url=/UI/Login?ReturnUrl=%2FUI%2FDashboard (port number is that of my firewall, which hosts HAProxy).

If I manually change the URL to https://subdomain.domain.tech/UI/Login?ReturnUrl=%2FUI%2FDashboard the login page appears.

I believe this error is also stopping me from using the https address when configuring the trackers in Sonarr. It fails to work unless I specific the http address via the IP directly.

Sonarr reports the tracker is working correctly, when you enter the details, see screenshot. But when attempting to grab an item I get an invaild URI error.

### Logged Error Messages

```text
in Sonarr - Invalid URI: The format of the URI could not be determined.
```

### Screenshots

![Screenshot 2023-06-15 183144](https://github.com/Jackett/Jackett/assets/77313738/85d01bf6-83ce-43e5-a4f1-3aa20d1056a3)
![Screenshot 2023-06-15 183407](https://github.com/Jackett/Jackett/assets/77313738/3f5035d1-e0f5-41bf-9202-7373cf6b8b78)

**Comment by ZoltrixGFC** [comment]
Thanks @ilike2burnthing 

Config as follows:

`# Frontend: HAProxy ()
frontend HAProxy
    bind 192.168.0.1:443 name 192.168.0.1:443 ssl  crt-list /tmp/haproxy/ssl/645f24abca2233.72163684.certlist 
    mode http
    option http-keep-alive

    # ACL: Jackett
    acl acl_6486ce40dccec7.84047064 hdr(host) -i jackett.domain.tech

    # ACTION: Jackett
    use_backend Jackett if acl_6486ce40dccec7.84047064

# Backend: Jackett ()
backend Jackett
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m  
    stick on src
    http-reuse safe
    server Jackett 192.168.0.26:9117 location /jackett/`

**Comment by ilike2burnthing** [comment]
No idea if these are of any use, but might as well share them while you wait:
https://www.haproxy.com/blog/haproxy-ssl-termination
https://www.haproxy.com/blog/redirect-http-to-https-with-haproxy
