### ISSUE TITLE
[req]: sinsitio

### ISSUE THREAD

**Issue by vadorrey** [Jackett/Jackett#14469]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: sinsitio
- URL: https://www.sinsitio.site/
- Description: web free in spanish for tv,film,muxic and xxx
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments:
```

**Comment by garfield69** [comment]
engine: DataLife
Not suitable for cardigann yml as the indexer needs to process the details page of tv shows in order to collect the seasons multiple episode torrents. needs a C# indexer to be written.

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
