### ISSUE TITLE
Settings not persisting across daemon restart

### ISSUE THREAD

**Issue by barbequesauce** [Jackett/Jackett#1446]
New user - installed Jackett & Mono this morning on a RPi running Raspian (Debian Jessie). 

I've managed to get it installed and running, but discovered that the config settings (base URL, black hole directory, etc) are not being maintained across daemon restarts. I don't see a save button - not sure if I'm just not looking in the right place. 

Trackers are being preserved, it's just the bottom configuration section that is getting reset...

Am I being dense?

**Comment by kaso17** [comment]
Clicking on "Apply Server config" should save them. Check the logs and permissions of the ~/.config/Jackett directory if that doesn't work.

**Comment by barbequesauce** [comment]
Thanks. Staring me in the face...
