### ISSUE TITLE
Imcomplete freeleech search SpeedApp

### ISSUE THREAD

**Issue by fedonr** [Jackett/Jackett#14466]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Linux : Amd 64 
Installation : Docker  Container
Version : v0.21.207
```

### Description

 SpeedApp freeleech only search tho it  works, it is incomplete.

For  example, there are freeleech options for Fast X 2023 for Cam, HD, FHD and UHD.

But with Jackett it only detects Cam version.

### Logged Error Messages

```text
N/A
```

**Comment by garfield69** [comment]
The speedapp website returns a JSON response to the Jackett indexer query to their API
`https://speedapp.io/api/torrent?itemsPerPage=100&sort=torrent.createdAt&direction=desc&search=fast+x+2023`

below is a compressed example of the response, redacted to show only the critical parts
```json
[
{"download_volume_factor":1,"upload_volume_factor":1,"name":"Fast.X.2023.1080p.MA.WEB-DL.DDP5.1.Atmos.x264-CMRG","category":{"id":29},"is_freeleech":false,"is_double_upload":false,"is_half_download":false},

{"download_volume_factor":1,"upload_volume_factor":1,"name":"Fast.X.2023.2160p.MA.WEB-DL.DDP.5.1.Atmos.DV.H.265-CMRG","category":{"id":57},"is_freeleech":false,"is_double_upload":false,"is_half_download":false},

{"download_volume_factor":1,"upload_volume_factor":1,"name":"Fast.X.2023.720p.MA.WEB-DL.DDPA5.1.x264-CMRG","category":{"id":29},"is_freeleech":false,"is_double_upload":false,"is_half_download":false},

{"download_volume_factor":1,"upload_volume_factor":1,"name":"Fast.X.2023.2160p.MA.WEB-DL.DDP5.1.Atmos.HDR.DV.HEVC-CMRG","category":{"id":61},"is_freeleech":false,"is_double_upload":false,"is_half_download":false},

{"download_volume_factor":1,"upload_volume_factor":1,"name":"Fast.X.2023.1080p.AMZN.WEB-DL.DDP5.1.H.264-CfaMilyRG","category":{"id":8},"is_freeleech":false,"is_double_upload":false,"is_half_download":false},

{"download_volume_factor":0,"upload_volume_factor":1,"name":"Fast.X.2023.1080p.Cam.X264.Blurred.DD.2.0-SPSD","category":{"id":35},"is_freeleech":true,"is_double_upload":false,"is_half_download":false},

{"download_volume_factor":1,"upload_volume_factor":1,"name":"Fast.X.2023.1080p.Cam.X264.Will1869","category":{"id":8},"is_freeleech":false,"is_double_upload":false,"is_half_download":false}]
```
as you can see only one of the torrents was flagged by the web site as being freeleech (is_freeleech=true and download_volume_factor=0)

However there is currently a global freeleech active until June 17 at the web site.

It appears that the response for the website does not take into account global freeleech.

I do not believe there is anything we can do about this. If the indexer does not receive the correct data it cannot display the correct data.

**Comment by fedonr** [comment]
Got it thanks a lot for the revert, I'll keep on testing it after global Freeleech ends.
