### ISSUE TITLE
May I ask which public API has imdb data

### ISSUE THREAD

**Issue by cnstephen** [Jackett/Jackett#14477]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
May I ask which public API has imdb data
```

### Description

May I ask which public API has imdb data？
thank you

### Logged Error Messages

```text
May I ask which public API has imdb data
```

**Comment by ilike2burnthing** [comment]
If you mean which public indexers support searching by IMDB ID - https://github.com/search?q=repo%3AJackett%2FJackett+%22type%3A+public%22+%22,%20imdbid%22&type=code

If you mean which public indexers return an IMDB ID for results - https://github.com/search?q=repo%3AJackett%2FJackett+%22type%3A+public%22+%22imdbid:%22&type=code
