### ISSUE TITLE
No search results with teh if specifying resolution

### ISSUE THREAD

**Issue by qtv** [Jackett/Jackett#1447]
I get results searching with teh if I include just the name of the movie i.e. "Doctor Strange". However, if I run a manual search with any resolution after it - like "Doctor Strange 1080p" - there are no results even though there is a copy in that resolution. This is true for all movies. You can enter the year of the movie and it will come up, it's just the resolution that matters the most to me.

Jackett version:  0.7.1467.0

**Comment by kaso17** [comment]
which trackers do you use for the search?

**Comment by qtv** [comment]
tehconnection, sorry

**Comment by kaso17** [comment]
That's unfortunately a limitation of tehconnection. If you use their website search you can't search for e.g. qualities either.
If you can convince the tehconnection staff to support searches like that it should be automatically fixed in jackett too.

**Comment by qtv** [comment]
You can specify resolution in the advanced search of tehconnection. Just parse the Jackett search string for a resolution and use the advanced search, no? It would be better than what it is now.

**Comment by kaso17** [comment]
ok, that should be possible. I'm changing this to an enhancement issue.
