### ISSUE TITLE
DimeADozen

### ISSUE THREAD

**Issue by Altansar69** [Jackett/Jackett#14475]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Don't need
```

### Description

DimeADozen tracker is not a semi-public tracker but a private tracker.

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment]
v0.21.258
