### ISSUE TITLE
New tracker: 32p

### ISSUE THREAD

**Issue by barbequesauce** [Jackett/Jackett#1448]
Hi -

I've searched but I don't see a previous request, surprisingly - can 32p be added please?

**Comment by adamwinn** [comment]
@barbequesauce if you can send me an invite, I'll add it

**Comment by barbequesauce** [comment]
Meh... after some discussion in their message boards they're not too enthusiastic about inclusion; from their perspective Mylar is the automation solution and no other... thanks for consideration.

**Comment by janot** [comment]
Could this be reopened or is it better to create a new issue?

**Comment by cadatoiva** [comment]
According to this issue, the site admins aren't too keen on us adding their site. Has this changed since the last update of this one?

**Comment by barbequesauce** [comment]
Their original response said they do not support third party applications but they also do not forbid them.

They went on to say that a Jackett module would be ok, but they would not support it; any dev looking for access to build it must follow the invite rules as well. 

I'd also note that any end user using such a module would have to be careful about the site's access rules...

**Comment by cadatoiva** [comment]
Then on that note, we should reopen this one. Very few sites offer us any kind of support.

**Comment by garfield69** [comment]
Jackett 0.16.137

**Comment by garfield69** [comment]
https://32pag.es/ returning Error 522 Connection timed out and may have been that way since 31/Oct/2020
is the site Gone, broken, or moved to a new domain?

**Comment by ilike2burnthing** [comment]
32P Announcement - It's dead

I know this isn't the news anyone was hoping for, but it's time to call it. We had a great run. First and foremost, I want to thank all of users, especially those that supported us financially to help us keep things running. Additionally, I want to really celebrate all of our staff members, from both the old and current site. This never could have happened without you sacrificing countless hours of your personal time to volunteer on a project like this.

As far as the current situation goes: Even before the 2nd hardware failure in the spring, our staffing was stretched too thin. Personal obligations had taken many of us away from the attention we needed to devote to the site. That was working ok for us thanks to our Admin/Lead Dev who was carrying on the majority of the work on their own. With the current hardware failure and data loss, the bandwidth just isn't there to get things back up again. I wish I had better news, but it's probably par for course for 2020.

We will miss you all. So long, and thanks for all the fish.

https://torrentinvites.org/f31/32pag-es-news-officially-dead-581315/
