### ISSUE TITLE
[req]: 3wmg

### ISSUE THREAD

**Issue by CyberRim** [Jackett/Jackett#14489]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: 3Wmg
- URL: https://www.3wmg.com
- Description: 3Wmg is a CHINESE Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): The Minimum Ratio is 1
- Additional Comments: This is a small site without exam, and the registration is currently closed. 
   What email address should I send an invite to? if needed.
```
Engine: NexusPHP v1.6.0-beta12 2020-06-23

**Comment by garfield69** [comment]
Please send an invite to garfieldsixtynine -at- gmail.com and I will build a cardigann indexer for this site.

**Comment by CyberRim** [comment]
> Please send an invite to garfieldsixtynine -at- gmail.com and I will build a cardigann indexer for this site.

It throws some errors when I use the site's invitation system. I PM admin but didn't get a response at the moment.

It did generate the invite, and I decided to stitch the invite link myself using the hash of the generated invite and send it to Garfieldsixtynine -at- gmail.com using my personal email.I checked the link and it did open the registration page.

**Comment by garfield69** [comment]
I filled in the registration form, however there was a problem :-(
![image](https://github.com/Jackett/Jackett/assets/6933240/bada0697-a7c7-4b78-a1d5-08327b1996ef)

**Comment by CyberRim** [comment]
> I filled in the registration form, however there was a problem :-( ![image](https://user-images.githubusercontent.com/6933240/247493513-bada0697-a7c7-4b78-a1d5-08327b1996ef.png)

I'm not sure if it's a site language issue, it seems that I can only wait for the admin to reply to me, I am sorry for the waste of time

**Comment by garfield69** [comment]
no problem. basically my account was created, but the system was unable to mail me the confirmation link which would allow me to activate the account.
it looks like the web sites' mail system is broken, which accounts for you being unable to send me an invite directly from the web site, and for me being unable to receive a confirmation email.

**Comment by CyberRim** [comment]
Yes, I saw on the site that your account is indeed registered. In addition to the email system, I deeply suspect that there is also a problem with the multilingual support of the website.
If the website language is selected non-Chinese, then 500 errors will be thrown on many pages. 
You can try to change the language of your site to Chinese on your personal page to see if the site is completely working. 
Anyway, it looks like the site lacks maintenance, although it has been able to torrent normally

**Comment by garfield69** [comment]
Ah well. 
Without the confirmation link, I cannot login, and the account will expire after a day.

We will just have to wait until the site is stable and ready for use. Once that happens you can try again to send an invite.
Until then I'll place this ticket on hold.

**Comment by garfield69** [comment]
I logged in successfully just now, so I shall be able to get to work on the indexer ;-)

**Comment by garfield69** [comment]
v0.21.275

**Comment by garfield69** [comment]
https://www.3wmg.com/ HTTP ERROR 500

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.3wmg.com/ 1040 Too many connections

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.3wmg.com/ 1040 Too many connections

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.3wmg.com/ Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1040] Too many connections

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14489#issuecomment-1904445693

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14489#issuecomment-1904445693

**Comment by garfield69** [comment]
v0.21.1991
