### ISSUE TITLE
[req]: MuseBootlegs

### ISSUE THREAD

**Issue by Altansar69** [Jackett/Jackett#14482]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: MuseBootlegs
- URL: https://www.musebootlegs.com/
- Description: MuseBootlegs (MB) is a Semi-Private Torrent Tracker for MUSE MUSIC / BOOTLEGS
```
Engine: TSUE 2.0

**Comment by garfield69** [comment]
v0.21.265

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by garfield69** [comment]
online.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
once logged in the following: Database Error! Please try again later or contact an Administrator.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-2105048316

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-1692236254

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14482#issuecomment-2105048316

**Comment by garfield69** [comment]
online
