### ISSUE TITLE
[aro.lol] down, for sale

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#14499]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
N/A
```

### Description

https://aro.lol/
- This domain is for sale https://github.com/Jackett/Jackett/pull/13278#issuecomment-1605396045
- ERR_NAME_NOT_RESOLVED

### Logged Error Messages

```text
N/A
```

**Comment by garfield69** [comment]
v0.21.532
