### ISSUE TITLE
[req]: rarbg.best

### ISSUE THREAD

**Issue by bountin** [Jackett/Jackett#14494]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Rarbg Dump Index
- URL: https://rarbg.best/
- Description: RARBG archive
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments:
```

**Comment by ilike2burnthing** [comment]
We won't be supporting stale archive sites.
