### ISSUE TITLE
[req]: cheggit

### ISSUE THREAD

**Issue by Altansar69** [Jackett/Jackett#14495]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: cheggit
- URL: https://www.cheggit.me/
- Description: XXX
- Minimum Seeding Time and Minimum Ratio (if Private): https://www.cheggit.me/articles.php?topic=rules
- Additional Comments: Open actually
```
Engine: n/a
MR 0.51

**Comment by ilike2burnthing** [comment]
Can either of you get torrents to connect to the tracker in client? I'm just getting that the connection has been actively refused.

The last torrent is from a year ago, and the forum has a bunch of posts and comments about the site and tracker being dead.

**Comment by garfield69** [comment]
same here. adding this indexer has been a waste of time ;-(

**Comment by garfield69** [comment]
v0.21.290

**Comment by garfield69** [comment]
this site is stale, last torrent was 3 years ago, and all links present a go to bootytape recommendation.
I'm removing this indexer.

**Comment by garfield69** [comment]
v0.21.1915
