### ISSUE TITLE
Ncore - not forward all search results to Sonarr, Radarr

### ISSUE THREAD

**Issue by vampywiz17** [Jackett/Jackett#1450]
Hello there,

In Ncore, two type of "title" appear on site. first of normal title and the second one to the sub-title. 

Normally, the normal title is english, and the sub-title is Hungarian version of the title. 

![01](https://cloud.githubusercontent.com/assets/14281430/26779866/6e3f5272-49e7-11e7-917e-f5380d6dce1f.jpg)

If they use the above mode,  no problem, Sonarr and Radarr found the release.

The problem started, that sometimes the uploaders replace the two title... The jackett also found this releases (i think it search on sub title) but it can not forward the results to the Sonarr+Radarr...

![02](https://cloud.githubusercontent.com/assets/14281430/26779879/741ed208-49e7-11e7-8048-adae32e352cc.jpg)

It is possible to fix it? (the IMDB search is not possible, Ncore not support, and possible it will never support it...)

**Comment by kaso17** [comment]
I don't see an easy fix for this tracker limitation.
You would have to make Sonarr/radarr search for the Hungarien title too.
Or convince the site staff to improve their search so that both versions (english and hungarian) are returned in depended of the search string language.

**Comment by vampywiz17** [comment]
If i set it to radarr the hungarian lang, it find, it, but in Sonarr, it not working. 

The Ncore staff Dont plan to improve the search in near future...

**Comment by MaddionMax** [comment]
Is there any solution for this problem?
