### ISSUE TITLE
[req]: Time

### ISSUE THREAD

**Issue by Altansar69** [Jackett/Jackett#14500]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

When I make a request on jackett it takes a very long time to have results.

### Describe the solution you'd like

I have no idea how it works, but I imagine that when you search all the trackers, some take longer to respond than others. If that's the case, would it be possible that after a search on this tracker, for example:
https://i.ibb.co/C6W4815/image.png

we can find out how long each tracker has taken to respond so that we can disable those that are taking too long.

by the way, if it's possible to do that, it would be even better to be able to average out the time it takes each tracker to respond, based on our previous requests. And to be able to select only the fastest trackers in the filters, for example.
just here: https://i.ibb.co/RTbK3PM/image.png

### Describe alternatives you've considered

To be honest, I don't know if it's ever been asked. I can't find a good keyword to search for in the issues without getting hundreds of results.

**Comment by ilike2burnthing** [comment]
See logs, e.g. `Test search in BitSearch => Found 100 releases [1185ms]`. Remove the ones you feel are taking too long.

Several of your trackers are down, so it's not just a case of them taking too long; again see the logs.

You can use the `test:passed` filter if you only want to use those indexers which passed their last test, or add a tag to known good indexers and then filter by that tag.
