### ISSUE TITLE
[req]: icv.crew

### ISSUE THREAD

**Issue by Lorenzopitton99** [Jackett/Jackett#14507]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: il corsaro verde
- URL: https://www.icv-crew.com
- Description: italian private tracker site
- Minimum Seeding Time and Minimum Ratio (if Private): 1.0
- Additional Comments:
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/3189
