### ISSUE TITLE
[req]: rargb

### ISSUE THREAD

**Issue by Altansar69** [Jackett/Jackett#14512]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: rargb
- URL: https://rarbg.best/
- Description: Search anything from the dead RARBG (R.I.P) website's dump (5,714TB) and get WORKING MAGNET LINKS.
- Additional Comments: there is categories, torrent size, full name, date, imdb link and magnet.
I hope this gives you enough information to create an indexer.
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14494
