### ISSUE TITLE
[req]: skeysnow 

### ISSUE THREAD

**Issue by Altansar69** [Jackett/Jackett#14519]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Skeysnow
- URL: https://skyeysnow.com/forum.php?mod=torrents
- Description: Skyeysnow is a Chinese Private Torrent Tracker for Anime.
- Minimum Seeding Time and Minimum Ratio (if Private): i don't know sorry, don't understand chinese
- Additional Comments: Open actually
```

**Comment by ilike2burnthing** [comment]
> - [x] I have checked older issues, open and closed

Lies...
https://github.com/Jackett/Jackett/issues/7017

**Comment by Altansar69** [comment]
![Screenshot_2023-06-30-03-34-18-505-edit_com brave browser](https://github.com/Jackett/Jackett/assets/97360807/4694b483-585d-4b36-b235-3057f8310412)
Dont have other result in search

**Comment by ilike2burnthing** [comment]
You need to spell it right.

**Comment by Altansar69** [comment]
Oh ok. It's m'y Bad.
