### ISSUE TITLE
[hdatmos] (updating) Login failed: Selector "a[href="logout.php"]" didn't match

### ISSUE THREAD

**Issue by WoodC2011** [Jackett/Jackett#14529]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
a
```

### Description

a

### Logged Error Messages

```text
a
```

**Comment by garfield69** [comment]
did you figure out the problem? what was it?

**Comment by WoodC2011** [comment]
> 
Your recovery is so fast.... I'm not sure if there's a problem yet so I'm temporarily closed, I'll give you feedback when I have a few more tests of the problem
