### ISSUE TITLE
[lostfilm] (updating) {"error":4,"result":"ok"}

### ISSUE THREAD

**Issue by reinethernal** [Jackett/Jackett#14521]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
root@mediaserv:~# service jackett status
* jackett.service - Jackett Daemon
     Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-07-01 03:10:23 UTC; 6s ago
   Main PID: 343031 (sh)
      Tasks: 16 (limit: 21403)
     Memory: 86.2M
        CPU: 4.172s
     CGroup: /system.slice/jackett.service
             |-343031 /bin/sh /home/jacket/Jackett/jackett_launcher.sh
             `-343034 /home/jacket/Jackett/jackett --NoRestart

Jul 01 03:10:27 mediaserv jackett[343034]: 07-01 03:10:27 Info Loaded 591 indexers in total
Jul 01 03:10:27 mediaserv jackett[343034]: 07-01 03:10:27 Info Adding aggregate indexer ('all' indexer) ...
Jul 01 03:10:27 mediaserv jackett[343034]: 07-01 03:10:27 Info Adding filter indexer ('type:public' indexer) ...
Jul 01 03:10:27 mediaserv jackett[343034]: 07-01 03:10:27 Info Adding filter indexer ('type:private' indexer) ...
Jul 01 03:10:27 mediaserv jackett[343034]: 07-01 03:10:27 Info Adding filter indexer ('type:semi-public' indexer) ...
Jul 01 03:10:27 mediaserv jackett[343034]: 07-01 03:10:27 Info Jackett startup finished in 3.530 s
Jul 01 03:10:27 mediaserv jackett[343034]: Hosting environment: Production
Jul 01 03:10:27 mediaserv jackett[343034]: Content root path: /home/jacket/Jackett/Content
Jul 01 03:10:27 mediaserv jackett[343034]: Now listening on: http://[::]:9117
Jul 01 03:10:27 mediaserv jackett[343034]: Application started. Press Ctrl+C to shut down.
root@mediaserv:~#
```

### Description

An error occurred while updating this indexer
{"error":4,"result":"ok"}
[Click here to open an issue on GitHub for this indexer.](https://github.com/Jackett/Jackett/issues/new?template=bug_report.yml&title=[lostfilm]%20(updating)%20%7B%22error%22%3A4%2C%22result%22%3A%22ok%22%7D)

### Logged Error Messages

```text
An error occurred while updating this indexer
{"error":4,"result":"ok"}
Click here to open an issue on GitHub for this indexer.
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/35932698/daff9f4b-db46-402f-8455-756f40982a41)

**Comment by garfield69** [comment]
code 4 is a captcha code error
use the Jackett dashboard and edit the lostfilm config.
enter the correct captcha code if there is an image present.
if no image then clear the captcha code if one was left over from prior.
if you have changed the sitelink then click close and open again in order the load the captcha image for the new site
if you get the captcha code wrong, then close and open to load new code image.

let us know how you go.

**Comment by reinethernal** [comment]
That's strange. I did nothing, and it works!

**Comment by garfield69** [comment]
\o/
