### ISSUE TITLE
Fails w/ Managed Service Accounts

### ISSUE THREAD

**Issue by hemsleyk** [Jackett/Jackett#1452]
OS: Server 2016 Core

Jackett works fine using local system, but won't bind a port if external access is turned on while using a managed service account. It WILL bind to the correct port and start successfully if external access is disabled. No error is thrown in the logs, they end simply as such:
 2017-06-05 21:57:01.7376 Info Starting web server at http://*:91170/ 

Jackett version:  v0.7.1469
Mono version (if not using Windows):  

Workaround question ... are the default settings workable? I have sonarr and hadouken on the same host working just fine under MSAs and can freely alter/plunder ServerConfig.json

-------------------------------

**Comment by kaso17** [comment]
What's the error you're getting?

What do you mean with "default settings workable"?

**Comment by hemsleyk** [comment]
"Bad Request - Invalid Hostname HTTP Error 400. The request hostname is invalid."

Just the standard "error" (correct behavior) for external access being disabled. As far as when using an MSA goes, the service starts and then immediately stops when it gets to "starting web server" in its log.

For default settings I am wondering how much is configured out of the box / how usable the API key in serverconfig.json is.

**Comment by hemsleyk** [comment]
Did some further testing. Installed Chrome in the Server Core VM as a workaround and configured Jackett. Pointed Sonarr at it. Everything works.

**Comment by hemsleyk** [comment]
Ah, here we are, it does throw to eventlog

```
Service cannot be started. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: The parameter is incorrect
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at Jackett.Services.ServerService.Start() in C:\projects\jackett\src\Jackett\Services\ServerService.cs:line 318
   at Jackett.Service.Service.OnStart(String[] args)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
```

**Comment by kaso17** [comment]
Is this still a problem in the latest version?

**Comment by tolarianNZ** [comment]
I had this issue just now, and found upon this article, then looked a little harder at my Jackett settings.. and found an option for "External access" in the settings if you scroll right to the very bottom.  D'oh.

Not sure if that's your issue exactly, but either way sorted and yes, I'm using the latest version and works a treat.  Didn't need to run the service as admin or anything like that, it runs as local system as it should.  Hope this helps!

**Comment by EraYaN** [comment]
For anyone looking at this later on:

The fix is as follows
For port `9117` and Service Account name `Jackett`. DOMAIN can be your domain name or more likely the current computer name.
```
netsh http add urlacl url=http://*:9117/ user=DOMAIN\Jackett
```
Execute in cmd as admin.

@kaso17 Might want to add this to the wiki/instructions or something, this only applies to external access.

**Comment by kaso17** [comment]
#2250 seems to be related
What happens if you delete your ACL again and start `JackettCosole.exe --ReserveUrls` once?
