### ISSUE TITLE
Jackett installer keeps crashing

### ISSUE THREAD

**Issue by seeyoshirun** [Jackett/Jackett#14528]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
OS Version: Windows 7 64-bit
```

### Description

Jackett installer (current version - I just checked) keeps closing without an error message as soon as I reach the point of clicking the "install" button. Have also made sure to try running the installer as an administrator.

Given that I'm getting stuck before Jackett is even installed, I'm not sure what other information to provide; I'm more tech-literate than the average layperson, but probably less so than most people who would use GitHub. Where can I start with figuring out why this might not be working? Happy to provide any other information needed.

### Logged Error Messages

```text
No error messages received, which makes this extra confusing.
```

**Comment by ilike2burnthing** [comment]
Does the folder `C:\ProgramData\Jackett` exist? If so, what does it contain?

Empty the `%temp%` folder (ignore anything that cannot be removed), then run the installer again. It should create 2 folders something along the lines of `is-7FD1C.tmp`, one containing a folder `_isetup` and file `_setup64.tmp`, and the other a file `Jackett.Installer.Windows.tmp`.

Is this what you see?

When the installer fails, are these removed?

Check the logs and quarantine of your antivirus or other security software to see if something is being removed or blocked.

**Comment by seeyoshirun** [comment]
Wow, thanks for the speedy reply!

Okay, let's have a look. I did try installing it once and couldn't get it to work, so I figured I'd uninstall and reinstall and see if that fixed the issue (I realise now I should have mentioned that firsthand).

The ProgramData\Jackett folder exists, yeah. It contains two folders ("DataProtection", "Indexers") and four other files - ".lock", "ServerConfig.json", and two text documents titled "ServiceLog" and "TrayLog"). There's no "%temp%" folder.

When I run the Jackett installer, nothing appears to change in the aforementioned directory. I checked the recent history of my antivirus software (AVG Free version - no idea if that's a good piece of software or not) and there was nothing in there to indicate it had interfered with the installer).

**Comment by seeyoshirun** [comment]
(I also just checked my firewall - just to be safe, I added the installer to the list of programs allowed through the firewall, and it made no difference.)

**Comment by ilike2burnthing** [comment]
Rename `C:\ProgramData\Jackett` to `Jackett.old` and try rerunning the installer.

`%temp%` is the user Temp folder, e.g. `C:\Users\seeyoshirun\AppData\Local\Temp`, and can be accessed with the path `%temp%`.

Avast/AVG isn't an AV I'd ever use (they were previously exposed as selling user data and continue to push scareware-esque 'upselling' spam in their notification and even scan results), but if you want to check the quarantine and are unsure how - https://support.avg.com/supportarticleview?l=en&urlname=use-avg-antivirus-quarantine

You could try disabling and closing the AV (and firewall if it's a third-party application, not just Windows' own), then running the installer again.
