### ISSUE TITLE
[limetorrents] (testing) Exception (limetorrents): certificate validation failed: [Subject]  CN=advice.upc.biz, O=LGI, L=Default City, C=NL[Issuer]  CN=advice.upc.biz, O=LGI, L=Default City, C=NL[Serial Number]  00FAB7432891344B16[Not Before]  1/10/2017 3:19:53 PM[Not After]  1/5/2037 3:19:53 PM[Thumbprint]  895BB7AB48E403EE902217BB1DEBBF130B4769C6: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by OverlordOE** [Jackett/Jackett#14520]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett startup finished in 4.140 s
Adding filter indexer ('type:semi-public' indexer) ...
Adding filter indexer ('type:private' indexer) ...
Adding filter indexer ('type:public' indexer) ...
Adding aggregate indexer ('all' indexer) ...
Loaded 590 indexers in total
Loaded 515 Cardigann indexers.
Loading Cardigann indexers from: C:\ProgramData\Jackett\cardigann\definitions\, C:\ProgramData\Jackett\Definitions
Loaded 75 Native indexers.
Loading Native indexers ...
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.22621.0 (64bit OS)
Environment version: 6.0.19 (C:\ProgramData\Jackett\)
Starting Jackett v0.21.341
```

### Description

I was trying to search for some music with the searchengine in Qbittorrent and then I got error messages: "jackett: connection error for indexer:" for  kickasstorrents, 1337x, limetorrents and badasstorrents. I went to the jackett webUI and tested all of them but got the errors below.

I have checked previous issues and the troubleshooting guide.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (limetorrents): certificate validation failed: [Subject]
  CN=advice.upc.biz, O=LGI, L=Default City, C=NL

[Issuer]
  CN=advice.upc.biz, O=LGI, L=Default City, C=NL

[Serial Number]
  00FAB7432891344B16

[Not Before]
  1/10/2017 3:19:53 PM

[Not After]
  1/5/2037 3:19:53 PM

[Thumbprint]
  895BB7AB48E403EE902217BB1DEBBF130B4769C6
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/54840496/1eccdbee-24fe-4d75-a036-51647e14b950)

**Comment by garfield69** [comment]
Either your ISP or your router or your security app is blocking your access to limetorrents, as the official certificates for the limetorrents site has been replaced by one issued by advice.upc.biz
You may need to use a VPN or proxy to shield your traffic from your ISP/router/security app.

**Comment by OverlordOE** [comment]
Thanks for the answer! Could it have something to do with that i installed a new GPU yesterday and in turn reset my bios for it?
If not could you reccomend me an easy way to set up a VPN or proxy for Jackett/Qbittorrent?

**Comment by garfield69** [comment]
start by trying out a free vpn that would at a system level (that it, all traffic when the VPN is active goes through the VPN server you select.
If it solves the issue the research other VPN provides to find one that suits your traffic demands, as the free ones tend to have limits. 
https://hide.me/en/software/windows might be a good start, but Google is your friend

**Comment by OverlordOE** [comment]
Alright thanks Im gonna try it now.

**Comment by OverlordOE** [comment]
Using the VPN seems to solve 3/4. Only badasstorrents still remains.

**Comment by garfield69** [comment]
with the same `certificate validation failed: [Subject] CN=advice.upc.biz` error or something else?

**Comment by OverlordOE** [comment]
"Jackett.Common.IndexerException: Exception (badasstorrents): Challenge detected but FlareSolverr is not configured"

**Comment by garfield69** [comment]
use your jackett dashboard to edit the indexer config and try out the other two alternate site links.
if all three use cloudflare protection then you are going to need to install https://github.com/FlareSolverr/FlareSolverr/releases/latest and add its address to the jackett dashboard config.
