### ISSUE TITLE
[fanstasticheaven] down for maintenance 

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#14523]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
N/A
```

### Description

https://fantastic-heaven.eu/
- down for maintenance
- ERR_CONNECTION_REFUSED
- ERR_CONNECTION_TIMED_OUT

### Logged Error Messages

```text
N/A
```

**Comment by garfield69** [comment]
v0.21.574
