### ISSUE TITLE
[req]: https://riprarbg.pw/

### ISSUE THREAD

**Issue by oneandonlymort** [Jackett/Jackett#14536]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: riprarbg.pw
- URL: https://riprarbg.pw/
- Description: Uses same api as RARBG did; should be otherwise same as RARBG indexer but ith alternative URL
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments:
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14494
