### ISSUE TITLE
[req]: FastScene

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14532]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: FastScene
- URL: https://fastscene.net/
- Description: FastScene is a ROMANIAN / ENGLISH Private site for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): MST 48h or MR 1.1
- Additional Comments: 
Engine: TBD
Registration open ATM
to save you some registration grief, note that username must not be longer that 10 chars, and the password no longer than 15
```

**Comment by garfield69** [comment]
v0.21.378

**Comment by garfield69** [comment]
https://fastscene.net/
![image](https://github.com/Jackett/Jackett/assets/6933240/37393fbf-d898-4088-bdf5-9faeabd3066f)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
v0.21.2335
