### ISSUE TITLE
[yggtorrent] (testing) Test search in YGGtorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by ShauwThen** [Jackett/Jackett#14549]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
.
```

### Description

YGG TORRENT CHANGED ITS ADDRESS

### Logged Error Messages

```text
.
```

**Comment by XamYp** [comment]
#14550 

Hi, the yggtorrent.lol website is dead, replaced by yggtorrent.wtf
There was a commit about this but we have to wait for these changes to be added to the docker image. Once this is done you will have to pull the new docker image and replace it then it will work.

**Comment by mushuthecat** [comment]
Hi,

I solved the issue by editing the link in my jackett for YGG

![image](https://github.com/Jackett/Jackett/assets/83928911/16b68cb4-9823-4c2e-8d61-42b64a3f87ad)


Regards

**Comment by garfield69** [comment]
@ShauwThen the correct sitelink to use is `https://www3.yggtorrent.wtf/`

**Comment by ShauwThen** [comment]
Oh yeah right ! Huge thanks !

ShauwThen - Julien
