### ISSUE TITLE
[req]: MIRCrew indexer - get all magnet links

### ISSUE THREAD

**Issue by Kianda** [Jackett/Jackett#14543]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hi, I'm using the current MIRCrew indexer (login works fine) but maybe there is room for improvements?

**Issue:**
The search results are not magnet links but? A single link to the MIRCrew topic where all the magnets are? (MIRCrew topics have multiple magnets inside)
Giving this (or the Jackett RSS link) to a torrent client will download only the first magnet found, and discard the others.

### Describe the solution you'd like

Here some suggestions:

**1. Easier search (login always required)**
It seems that the implemented search is using the search.php of MIRCrew and then apply filtering on the results with some category mappings.
What about the 'Release List' feature? _https://mircrew-releases.org/releases/?q=search+query+here&cat=catIDhere_ I think it's easier to handle vs search.php

**2. Scraping of magnet links (login always required)**
Every release have all the magnet links always on the first post of the topic (behind a mandatory, one time, 'thank you' href)
This scraping rule (based on CSS) should work:
- Find the topic link using 'releases' search (example -> _https://mircrew-releases.org/viewtopic.php?p=242013_)
- Save the ID (example 242013) & "get the dom" of that page
- Use the saved ID to get all the magnet links inside the `<div id="p242013">`
- Show all the magnet links on Jackett search results (this will allow the RSS feed to work properly?)

Each magnet is showed with this schema:
```
<dl class="hidebox unhide">
  <dd>
    <a class="magnetBtn" href="magnet:?xt=urn:btih:somethingsomething">
      <img src="/images/custom/Magnet_Link.png" alt="Magnet link">
    </a>
    <p style="font-weight: bold; color: rgb(0, 0, 0);">TITLE OF THE MAGNET HERE</p>
    <p id="magnetData" style="color: rgb(0, 0, 0);">
      OTHER NESTED ADDITIONAL INFO HERE
    </p>
  </dd>
</dl>
```

My plan is to do this with Python using 'Beautiful Soup' and build my custom homemade RSS feed but have this implemented into Jackett would be amazing.

What do you think? It's doable on Jackett? Pros and cons?

Ty ^^

**Comment by garfield69** [comment]
the existing indexer is written in yaml which does not have the complexity to support what you suggest.
We would need to re-write the indexer in C#.

**Comment by Kianda** [comment]
Understood thanks!
Which current existing indexer written in C# is the closest as features compared to what I suggested?
I would like to take a look at that ^^

**Comment by ilike2burnthing** [comment]
Assuming I'm not misunderstanding, I think this is a similar solution to what was suggested for ICV - https://github.com/Jackett/Jackett/issues/3189#issuecomment-990791328

It was rejected due to it being a LOT of extra traffic and a lot of meaningless `Thanks`, potentially getting accounts flagged for bot activity.

**Comment by garfield69** [comment]
Given that mircrew requires a thank you before accessing any magnets in a forum post, it is not practical to fetch all the magnets in this manner to populate the primary results page, so we must reject this proposal for the same reasons given for IVC in #3189 
Using the releases page might be an alterative tofetch latest (technically a better option than searching for .Today.Year using the search page), but since the releases page is not laid out in the same way as the search.php page, it cannot be supported with yaml.
An indexer needs to be able to support both latest and search queries.
The reality is that unless someone contributes with a PR to re-write in C# support latest and search for these two different pages then this ticket in unlikely to get implemented, as shown by the many one-title-many-torrents tickets that remain open to this day (and which I end up closing as stale eventually after several years waiting).
I'm doing to close this one.

**Comment by easly1989** [comment]
@Kianda did you made any progress with your custom RSS or custom C# indexer for Mircrew?
I'm still trying to find a solution to grab all the magnets from tvshow releases without luck

**Comment by Kianda** [comment]
> [@Kianda](https://github.com/Kianda) did you made any progress with your custom RSS or custom C# indexer for Mircrew? I'm still trying to find a solution to grab all the magnets from tvshow releases without luck

Very little progress in 2023, C# is not my main language... I should give it a shot now in 2025 with all the "vibe coding" shenanigans and see how much help I can get from IA! 🤣

**Comment by easly1989** [comment]
So i've made a custom indexer with the help of the IA. It goes through the mircrew search, finds the topics and likes them right away to get access to the magnet links
After that it turns back to sonarr a list of alla the magnets it has found for us to choose.
I was not able to make a better implementation or a smarter one, so I'll give access to anyone that wants to try and make it better.
As for the moment it seems to be working fine.

the repo is here, feel free to fork and/or give help making it better: https://github.com/easly1989/mircrew-smart-indexer

**Comment by Kianda** [comment]
> So i've made a custom indexer with the help of the IA. It goes through the mircrew search, finds the topics and likes them right away to get access to the magnet links After that it turns back to sonarr a list of alla the magnets it has found for us to choose. I was not able to make a better implementation or a smarter one, so I'll give access to anyone that wants to try and make it better. As for the moment it seems to be working fine.
> 
> the repo is here, feel free to fork and/or give help making it better: https://github.com/easly1989/mircrew-smart-indexer

Thanks, easly1989!
I'll give it a try as soon as I have some free time.

I'm against the auto-like feature. It's nice but it's "too much".
I think the likes on MIRCrew are there for a reason; they also serve as feedback to the releaser.
Having Jackett installations abuse the MIRCrew system spamming auto-likes on every search is bad.

In my opinion, if a thread doesn't have any likes, then Jackett should only show the link to the thread.
The user should go there, place a like manually, and then next time Jackett will read the magnet links.

It's not that bad, a single like on a thread will unlock all the magnets for an entire season of a show (since the releaser updates the first post with each new episode).

Again, this is just my opinion and not a rule, but I think we should respect MIRCrew's choices about how their system works and don't bypass that (even if we can).

**Comment by easly1989** [comment]
I do agree with you, but I've not been able to find a workaround so as for now i decided to go with it.
Also I'm no expert with sonarr/jackett/prowlarr api so even to get the result from the query was kind of hard ahahah
I'll try to find some possible alternatives/ways to just like the requested thread, but it is way harder than it seems

**Comment by ilike2burnthing** [comment]
> In my opinion, if a thread doesn't have any likes, then Jackett should only show the link to the thread.
The user should go there, place a like manually, and then next time Jackett will read the magnet links.

Unfortunately this isn't an option, as any indexer must be compatible with *arrs, which that wouldn't be.

At that point, you might as well just use the current Jackett indexer and click through to the details page from the results, click `Thanks`, and then download whichever ones you want manually.

---

Just for anyone using @easly1989's indexer, please be aware (as [written above](https://github.com/Jackett/Jackett/issues/14543#issuecomment-1625710716)) you run the risk of getting your account flagged for bot activity.

**Comment by Kianda** [comment]
> > In my opinion, if a thread doesn't have any likes, then Jackett should only show the link to the thread.
> > The user should go there, place a like manually, and then next time Jackett will read the magnet links.
> 
> Unfortunately this isn't an option, as any indexer must be compatible with *arrs, which that wouldn't be.
> 
> At that point, you might as well just use the current Jackett indexer and click through to the details page from the results, click `Thanks`, and then download whichever ones you want manually.

My idea is:
- If there's already a like → read the magnets and return multiple rows (one for each magnet with its own title).
- If there isn't → show a single row, exactly as the current YAML implementation does.

Does that make sense?

**Comment by ilike2burnthing** [comment]
It makes sense, but that ends up being a rewrite in C# for a minority of users who would ever use that manual step, so they'd get exactly the same results they do now.

It would also mean up to 25 additional requests for each search, as there's no indication that a result has already been thanked in the search results page. To make matters worse, almost all searches (particularly for those using automation software) will return 100% un-thanked results, so it would be a waste of time as well, and still run the risk of getting accounts flagged for bot activity.
