### ISSUE TITLE
[1337x] (testing) Exception (1337x): No such host is known.: No such host is known. (1337x.to:443)

### ISSUE THREAD

**Issue by thaynos** [Jackett/Jackett#14541]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
windows 10 22h2
microsoft edge
```

### Description

1337x.to is blocked by my isp but the .tw domain isnt, but when i tried adding that it gave the below error
![image](https://github.com/Jackett/Jackett/assets/83282129/ea9c687b-b260-4032-8a37-7b1d679e27dc)

neither did it work when i tried 1377x.to
![image](https://github.com/Jackett/Jackett/assets/83282129/53ad2bee-0435-4699-acd1-223e93a9816b)

### Logged Error Messages

```text
nil
```

**Comment by thaynos** [comment]
while being similiar it doesnt explain why the alternative site link doesnt work.

**Comment by garfield69** [comment]
see https://github.com/Jackett/Jackett/issues/12951
basically 1337x.tw is not an official alternate, so likely a copycat, which means that while the skip may look similar, in the background the engine is different and the 1337x indexer has a mismatch that prevents it working with your chosen sitelink.

**Comment by thaynos** [comment]
thank you for the info, js before seeing this i realised it is indeed a copycat
