### ISSUE TITLE
Everything is not working except the GUI ! OSX

### ISSUE THREAD

**Issue by alfuraiji** [Jackett/Jackett#1455]
I have a huge issue after installation
1- I can't add IPTorrent (  Error: An error occurred while sending the request )
2- Test is not working and I think for all providers! ( Test failed for eztv: An error occurred while sending the request: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/external/boringssl/ssl/handshake_client.c:1132) )

I have the latest version of Mono and the latest version of Jackett 

here is my log : 
`Server Logs
When	Level	Message
Jun 07, 2017 03:44:30 PM	Error	
Exception in test_indexer
Jun 07, 2017 03:43:54 PM	Error	
Exception in GetConfigForm
Jun 07, 2017 03:37:19 PM	Error	
Exception in test_indexer
Jun 07, 2017 03:37:12 PM	Error	
Exception in test_indexer
Jun 07, 2017 03:36:53 PM	Error	
Error checking for updates.
Jun 07, 2017 03:35:47 PM	Error	
Error checking for updates.
Jun 07, 2017 03:32:11 PM	Error	
Exception in test_indexer
Jun 07, 2017 03:32:04 PM	Error	
Exception in test_indexer
Jun 07, 2017 03:30:24 PM	Error	
Exception in GetConfigForm
Jun 07, 2017 03:30:08 PM	Error	
Exception in GetConfigForm
Jun 07, 2017 03:28:16 PM	Error	
Exception in test_indexer
Jun 07, 2017 03:28:07 PM	Error	
Exception in test_indexer
Jun 07, 2017 03:28:01 PM	Info	
Manual search for "lion" on The Pirate Bay with 0 results.
Jun 07, 2017 03:28:01 PM	Error	
An error occured during manual search on The Pirate Bay:  One or more errors occurred.
Jun 07, 2017 03:27:51 PM	Info	
Manual search for "Game of thrones" on The Pirate Bay with 0 results.
Jun 07, 2017 03:27:51 PM	Error	
An error occured during manual search on The Pirate Bay:  One or more errors occurred.
Jun 07, 2017 03:27:21 PM	Error	
Exception in test_indexer
Jun 07, 2017 03:26:50 PM	Error	
Exception in test_indexer
Jun 07, 2017 03:26:49 PM	Error	
Exception in test_indexer
Jun 07, 2017 03:26:48 PM	Error	
Exception in test_indexer
Jun 07, 2017 03:26:42 PM	Error	
Exception in test_indexer
Jun 07, 2017 03:13:25 PM	Error	
Exception in GetConfigForm
Jun 07, 2017 03:13:11 PM	Info	
redirecting to /Admin/Dashboard
Jun 07, 2017 03:13:02 PM	Info	
Starting web server at http://*:9117/
Jun 07, 2017 03:13:02 PM	Info	
Adding aggregate indexer
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/ztracker.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/xtremezone.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/worldofp2p.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/waffles.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/utorrents.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/ultrahdclub.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/ultimategamerclub.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/uhdbits.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/trancetraffic.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/totheglory.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/torviet.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/torrentz2.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/torrentsmd.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/torrentsectorcrew.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/torrentproject.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/torrenting.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/torrenthr.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/torrentccf.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/torrentbd.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/torrent9.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/tokyotosho.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/tntvillage.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/thevault.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/thetorrents.yml
Jun 07, 2017 03:13:01 PM	Info	
Loading Cardigann definition /Applications/Jackett/Definitions/theshow.yml
Close
`

**Comment by alfuraiji** [comment]
I fixed it ! 
Just downgraded mono from the latest version to 4.6.2.16, since later versions have an SSL issue.

**Comment by kaso17** [comment]
You probably didn't import the CA certs (needed for mono >= 4.8)
Try running `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`

**Comment by crazymaca69** [comment]
I've got exactly the same problem, i have mono 5 installed. please can you provide a link to mono 4.6.2.16. the one i have seems to be having problems installing.
