### ISSUE TITLE
[req]: RARBG ISSSS back 

### ISSUE THREAD

**Issue by ukharley** [Jackett/Jackett#14552]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: RARBG
- URL: https://www2.rarbggo.to/

- Description:
  As before

- Minimum Seeding Time and Minimum Ratio (if Private): 

- Additional Comments: 
  Might not be the same owners but it is back.
  It has the latest shows so is not stale.
```

**Comment by ukharley** [comment]
The main domain is https://rargb.to/
I used the proxy above,
Just checked and the API isn't working so might not be viable.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14446
