### ISSUE TITLE
MS Defender flags JacketConsole.dll as containing Trojan:Win32/Randet.A!plock

### ISSUE THREAD

**Issue by santoshwildlifeart** [Jackett/Jackett#14556]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
OS Name	Microsoft Windows 11 Pro	
Version	10.0.22621 Build 22621	
Other OS Description 	Not Available	
OS Manufacturer	Microsoft Corporation	
System Manufacturer	LENOVO	
System Model	10J0A07RIG	
System Type	x64-based PC	
System SKU	LENOVO_MT_10J0_BU_LENOVO_FM_ThinkCentre M700	
Processor	Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz, 2496 Mhz, 4 Core(s), 4 Logical Processor(s)	
BIOS Version/Date	LENOVO FWKT54A, 24-06-2016	
SMBIOS Version	3.0	
Embedded Controller Version	1.22	
BIOS Mode	UEFI	
BaseBoard Manufacturer	LENOVO
```

### Description

Microsoft Defender flags the Jackett program as containing malware in its most recent routine scan. I've run Jackett previously for a couple of years on Win 10 and never had Defender flag it. But now it says the file JackettConsole.dll contains Trojan:Win32/Randet.A!plock and has quarantined it.

Is this a false positive?

### Logged Error Messages

```text
Can't run Jackett service as Defender has quarantined JackettConsole.dll
```

### Screenshots

![Screenshot 2023-07-13 135438](https://github.com/Jackett/Jackett/assets/16806187/fb17fec5-332e-48dd-8ed3-eda0516ed167)
![Screenshot 2023-07-13 135741](https://github.com/Jackett/Jackett/assets/16806187/73ca39a6-c325-421e-9a1c-2d9776a1f5dd)

**Comment by garfield69** [comment]
its a false hit. of the Virustotal 70 vendor tests only the microsoft one flagged a hit.
access your defender viruschest and add an exclude and restore the module.

**Comment by santoshwildlifeart** [comment]
Thanks, that is what I suspected.
