### ISSUE TITLE
[req]: The rarbg website has been reopened, please add, thank you

### ISSUE THREAD

**Issue by cnstephen** [Jackett/Jackett#14551]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

The rarbg website has been reopened, please add, thank you

rarbg.to

### Describe the solution you'd like

The rarbg website has been reopened, please add, thank you

**Comment by ilike2burnthing** [comment]
No, it hasn't.
