### ISSUE TITLE
Windows Security on Windows Server 2019 detects JackettConsole.dll has a trojan

### ISSUE THREAD

**Issue by MikeRotch76** [Jackett/Jackett#14560]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows Server 2019 Standard v1809, OS Build 17763.4645
Windows Security info:
Antimalware Client Version 4.18.23050.5
Engine Version: 1.1.23060.1005
Antivirus Version: 1.393.193.0
Antispyware Version: 1.393.193.0
```

### Description

Checked my server this morning around 8am and saw a Windows Security threat  from C:\ProgramData\Jackett\acketConsole.dll at 2:19 am (Mountain Time)
I pulled the latest Jacket.Installer.Windows.exe around 9am and executed it.  After installation, got the same threat.
I then downloaded Jacket.Installer.Windows.zip, extracted the JacketConsole.dll from that archive and copied it over to C:\ProgramData\Jackett and it did not trigger a threat and Jackett is currently running.

Does Jackett do auto updates?  Is that why I got a threat at 219 am?  I see in the releases that the last update was 8 hours ago which matches roughly of when my 2am threat was generated.

### Logged Error Messages

```text
In Description
```

### Screenshots
![image](https://github.com/Jackett/Jackett/assets/70385220/dc45d120-605e-4415-9f47-2ccd4e3756e7)
![image](https://github.com/Jackett/Jackett/assets/70385220/e45f87b6-0d28-4855-ab27-6f0a1619f801)
_No response_

**Comment by cognossitivo** [comment]
The same happened to me. Only with the installer. The zip version has no problems.

**Comment by bedub1** [comment]
My system just flagged this as well.

**Comment by bedub1** [comment]
Looks like only Microsoft thinks it's Malware.  https://www.virustotal.com/gui/file/727a31ba21edd5292b8015528a84978c6390f8743f24472a6d7e1e1a0652e0c7

**Comment by MikeRotch76** [comment]
> Looks like only Microsoft thinks it's Malware. https://www.virustotal.com/gui/file/727a31ba21edd5292b8015528a84978c6390f8743f24472a6d7e1e1a0652e0c7

Interesting... but then why is JackettConsole.dll detected differently between the installer and the .zip file?

**Comment by garfield69** [comment]
closing as a duplicate of #14556
