### ISSUE TITLE
[spidertk] (updating) Login failed: No form found on https://spidertk.top/login.php using form selector form[action="takelogin.php"]

### ISSUE THREAD

**Issue by BartoX360** [Jackett/Jackett#14569]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Info	Using HTTP Client: HttpWebClient2
Info	Using FlareSolverr: http://flaresolverr:8191
Info	Using proxy: Disabled
Info	App config/log directory: /config/Jackett
Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Info	Running in Docker: Yes (image build: v0.21.481-ls115)
Info	File /etc/issue: Welcome to Alpine Linux 3.18
Info	Jackett variant: CoreLinuxMuslAmdx64
Info	OS version: Unix 5.10.0.19 (64bit OS) (64bit process)
Info	Environment version: 6.0.20 (/app/Jackett/)
Info	Starting Jackett v0.21.481
```

### Description

Hello,
Since the re-upload of SpiderTK it's impossible to login.
Thanks for your help :)

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://spidertk.top/login.php using form selector form[action="takelogin.php"]
```

**Comment by garfield69** [comment]
The indexer is working for me which suggests the problem is at your end.
Please enable enhanced logging, retry your attempt to login, and provide the full enhanced log file for us to take a look at.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for how-to.
Thanks.

**Comment by BartoX360** [comment]
With the full debug log i see my IP is banned from SpiderTK. 
I will see with us for unban my IP.
Thanks for your help :)
Bartox
