### ISSUE TITLE
Missing catogories

### ISSUE THREAD

**Issue by RaidersPlay** [Jackett/Jackett#14563]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
Environment version: 6.0.20 (C:\ProgramData\Jackett\)
Starting Jackett v0.21.456
```

### Description

When looking for a series, it seems like the are few and far between.
Been struggling to download some series. But from a few sites it is works. 

I've now search for a series, and it seems the issue is category based. (Please correct me if I'm wrong.)

Example... https://thepiratebay.org/search.php?q=Star+Trek:+Lower+Decks
It seems like category 200 and 208 is used.
Jackett only starts at 1000

### Logged Error Messages

```text
No error, just no results.
```

**Comment by garfield69** [comment]
;-)
Categories are not missing. 
A web site's actual categories are represented by the Torznab custom categories.
Basically you add 100000 to the cats that the Web site uses. So 208 becomes 100208 in Jackett.
Jackett will convert a Torznab query such as
`http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=(removed)&Query=Star%20Trek%3A%20Lower%20Decks&Category[]=100208&Tracker[]=thepiratebay` 
into the  site specific query 
`https://apibay.org/q.php?q=star.trek.lower.decks&cat=208`
