### ISSUE TITLE
Just got an Avast warning re: Jackett - IDP.Generic infection

### ISSUE THREAD

**Issue by Tufflaw** [Jackett/Jackett#1456]
Jackett version:  0.7.1477.0
Mono version (if not using Windows):  Using Windows

-------------------------------

I've been using Jackett with zero problems for a while now, just got an alert popped up from Avast warning about jackett.exe, it said infected with IDP.Generic.

I haven't done anything to change my setup lately, any thoughts why this might be happening?

**Comment by flightlevel** [comment]
Not familiar with Avast but its not uncommon for antiviruses to have false positives. Nothing major has changed recently. Some antiviruses will flag files with a low download count as being 'uncommon' ???  You can report here https://www.avast.com/false-positive-file-form.php
Will close the issue as not much we can do here, feel free to re-open if you think something needs to change
