### ISSUE TITLE
Cinelidad is not working 

### ISSUE THREAD

**Issue by angel-lizander** [Jackett/Jackett#14566]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using Windows, http client. Latest jacket version.
```

### Description

When try to read all the torrent, something wrong happen. 

### Logged Error Messages

```text
An error occurred while configuring this indexer
Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión. (localhost:8191) ---> System.Net.Sockets.SocketException (10061): No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión. at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConn
Click here to open an issue on GitHub for FlareSolverr.
```

**Comment by garfield69** [comment]
The cinecalidad web site is currently using cloudflare to protect the site from DDoS attacks.
You must have seen this when you use the browser to access the site, you get the occasional `checking if the site is secure` page before the site gives you its main page.

This means that when you use Jackett's cinecalidad indexer to search for a torrent, Jackett recognises that it will need the flaresolverr proxy to try to resolve the cloudflare challenge.

You need to install flaresolverr from https://github.com/FlareSolverr/FlareSolverr and then load the flaresolverr address in your Jackett dashboard to allow Jackett to access that service.

One other fly in the ointment: flaresolverr cannot solve the newest cloudflare challenge used by cinecalidad ATM. 
A new release of flaresolverr is imminent, but I don't know how soon that will be (I'm guessing within the next few days at the most).
