### ISSUE TITLE
[enhancement]: Add video codec in YTS titles

### ISSUE THREAD

**Issue by altendorfme** [Jackett/Jackett#14572]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

YTS has started to add the x265 version, but the titles do not follow this information and can break filters

![image](https://github.com/Jackett/Jackett/assets/1530032/10b5d465-1bee-438a-8402-e3755f88db02)
![image](https://github.com/Jackett/Jackett/assets/1530032/23450c64-6778-455d-94bb-bf912da068da)

### Describe the solution you'd like

Add the video_codec after the quality:

![image](https://github.com/Jackett/Jackett/assets/1530032/59b66039-5f1e-4473-a4cf-bfcd3fdaf490)

**Comment by ilike2burnthing** [comment]
Added audio channels (showing 5.1 only), bit depth (showing 10 bit only), and codec.

Can be:
- Title  (2023) 2160p WEBRip 5.1 10Bit x265 -YTS
- Title  (2011) 720p BRRip x264 -YTS

**Comment by garfield69** [comment]
v0.21.491
