### ISSUE TITLE
[req]: Undo changes on locadora categories

### ISSUE THREAD

**Issue by costaht** [Jackett/Jackett#14576]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hi guys, can you please undo [these](https://github.com/Jackett/Jackett/commit/fbe225bbf6c9a528538edafe62f33984dc63ac55
) changes in our categorymappings?

As stated [here](https://github.com/Jackett/Jackett/issues/13334#issuecomment-1186310987), this gets confusing for the users. A user reported that they couldn't find a movie on the tracker and when I checked he didn't have the correct categories on Radarr and I wasn't aware of those changes.

### Describe the solution you'd like

Se categorymappings to the config below:
```caps:
  categorymappings:
    - {id: 1, cat: Movies}
    - {id: 2, cat: TV}
    - {id: 6, cat: TV/Anime}
    - {id: 7, cat: Movies, desc: "Concerts"}

### Describe alternatives you've considered

_No response_

**Comment by garfield69** [comment]
no problem. the changes will be included in the next release of Jackett due in about 3 hours or so.

**Comment by costaht** [comment]
We are actually adding concerts under the Movies categories, not Audio/Video

`- {id: 7, cat: Movies, desc: "Concerts"}`

**Comment by garfield69** [comment]
okely dokely

**Comment by garfield69** [comment]
v0.21.505

**Comment by costaht** [comment]
hey garfield, thanks for the change but I think the problem is the description. When we use description for a category Jackett will create a second category and I guess that's why we added description for Concerts only back then.
I removed those in the container and restarted the container to double check:
 
Before:
![Screenshot from 2023-07-21 02-55-01](https://github.com/Jackett/Jackett/assets/50637431/5dc3a6bd-9ee1-479a-b3ec-206a5c0ba86e)

After:
![Screenshot from 2023-07-21 03-04-50](https://github.com/Jackett/Jackett/assets/50637431/7950ae88-73ff-46ab-91a6-457274bf27eb)

**Comment by garfield69** [comment]
Torznab provides a one-to-one mapping of the website's categories by defining custom categories. 
these custom categories are the real web site category numbers, with 100000 added.
So when a Torznab app (like Sonarr) makes a query using category 100007, Jackett will translate that category back to 7 when it makes the corresponding query to the web site.

If a Sonarr app makes a query using the standard Torznab category 2000, Jackett will gather all the custom categories of type Movies, and build a query to the website that includes, using locadora's indexer as an example, a query with &categories[]=1&categories[]=7

Is this info helpful?

**Comment by costaht** [comment]
Yes, now I understand  why you create those and I thank you for the clarification. But look at this screenshot from a user's perspective:

![Screenshot from 2023-07-21 21-56-28](https://github.com/Jackett/Jackett/assets/50637431/5e6d75c1-c974-4cb2-a47c-baf8d56daf42)

I have the categories 2000 and 100001. 100001 will return Movies only, but 2000 will return Movies and Concerts.
Let's say we restore the categories descriptions like below:
```
- {id: 1, cat: Movies, desc: "Filmes"}
- {id: 2, cat: TV, desc: "Series"}
- {id: 6, cat: TV/Anime, desc: "Animes"}
- {id: 7, cat: Audio/Video, desc: "Shows"}
```

 the user will always select the parent (Movies 2000) category and its variant (Filmes 100001) because they think if they don't check the cat 2000 they'll be missing out, but when they do that, it defeats the purpose of the mapping Jackett does.

Wouldn't it be better if Jackett hid the parent categories to make it more intuitive and fool proof for the user? Just an idea. I don't know how others would be impacted.  I've been using Jackett for years now, and I only understood all those categories that other trackers have, right now. So I guess, most people are in fact just checking all the boxes and making unnecessary calls to the trackers.

And now that I understand the mapping that Jackett does, what would be the difference of using the cat: Audio/Video and cat: Movies ? My understanding is that if the user chooses Audio/Video Jackett will search using the string only, no IMDB/TMDB ids. Is that correct?

Thank you for your support!

**Comment by garfield69** [comment]
>Wouldn't it be better if Jackett hid the parent categories 

Not possible. We are obliged to conform to the Torznab standards so that app that use that specification knows how to code their torznab queries and process the responses.

>what would be the difference of using the cat: Audio/Video and cat: Movies 

Mostly to do with the Torznab search capabilities. When an app picks a search method, they get a default type of general category. so a t=music would usually search within general category 3000

The Torznap search capabilities that Jackett supports are:
```
t=search:
   params  : q
t=tvsearch:
   params  : q, season, ep, imdbid, tvdbid, rid, tmdbid, tvmazeid, traktid, doubanid, year, genre
t=movie:
   params  : q, imdbid, tmdbid, traktid, doubanid, year, genre
t=music:
   params  : q, album, artist, label, track, year, genre
t=book:
   params  : q, title, author, publisher, year, genre
```

Of course this also has to be search capabilities that the web site that the Jackett indexer references can provide. So while the Torznab specs allow for all those search parms, we define only the ones that give results in the indexer that references a web site.

FYI The Torznab general categories, as used by Jackett, are listed at https://github.com/Jackett/Jackett/wiki/Jackett-Categories

however, that said, there is nothing preventing an app from using other general categories in their queries, if the app supports them.  For instance, its common to support the general category  Other (8000). 

>My understanding is that if the user chooses Audio/Video Jackett will search using the string only, no IMDB/TMDB ids. Is that correct?

Correct, but only because the t=music does not support using imbd or tmdb queries, as shown in the capabilities table above.

**Comment by costaht** [comment]
So in that case the ARRs are the ones that choose to show the parent categories, right?
I guess I should've asked you about these concepts before asking you to undo those changes then. What do you think of we bring those back and I'll instruct my users on how to properly setup their categories on Radarr/Sonarr ?
```
  categorymappings:
    - {id: 1, cat: Movies, desc: "Filmes"}
    - {id: 2, cat: TV, desc: "Series"}
    - {id: 6, cat: TV/Anime, desc: "Animes"}
    - {id: 7, cat: Audio/Video, desc: "Shows"}

  modes:
    search: [q]
```

**Comment by garfield69** [comment]
>So in that case the ARRs are the ones that choose to show the parent categories, right?

Yes. When an ARR app wants to define an indexer, they do a t=caps query and Jackett returns all the caps defined for that indexer. But the General categories (as activated by whatever custom categories are defined at the web site) are always present.
And a t=movies would always expect general category 2000 to be present, and t=tvsearch expects 5000 to always be present at a minimum.

>What do you think of we bring those back

No problem. Should be ready by the next release due out in 3 hours or so.

**Comment by garfield69** [comment]
v0.21.510
