### ISSUE TITLE
[mteamtp2fa] (updating) Login Failed, got redirected to: https://kp.m-team.cc/index.php

### ISSUE THREAD

**Issue by zzfree2021** [Jackett/Jackett#14570]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
群晖nas，docker安装jackett最新版，中国大陆宽带ip，未使用 flaresolverr
```

### Description

cookie登陆无法用，用户名密码登录也无法使用

### Logged Error Messages

```text
An error occurred while updating this indexer
Login Failed, got redirected to: https://kp.m-team.cc/index.php
Click here to open an issue on GitHub for this indexer.
```

### Screenshots

[log.txt](https://github.com/Jackett/Jackett/files/12077513/log.txt)

**Comment by garfield69** [comment]
Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by garfield69** [comment]
Oh wait, you are using a cookie indexer, so the enhanced log will not help in this case.
please read https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work and especially the **Notes** section.

**Comment by garfield69** [comment]
And if the wiki does not help you figure it out, then as a last resort please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
