### ISSUE TITLE
[hdchina] (testing) Test search in HDChina => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by insomnia417** [Jackett/Jackett#14587]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
unraid 6.11.5
```

### Description

 An error occurred while testing this indexer
Test search in HDChina => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

cannot add hdchina

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in HDChina => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/47959853/691d70e7-87b2-4c41-a67f-56229fa7a4d5)

**Comment by garfield69** [comment]
1. please fill in the environment section properly, with out it we have no starting point. Restart Jackett and view the log from the dashboard, scroll to the bottom, and copy paste the first 10 lines, begins `Starting Jackett` and ends `Using HTTP Client` 
2. turn on enhanced logging and repeat your search and provide the full enhanced log. See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for how-to
Hopefully this will provide some debug and HTML to give us a clue to your issue.

**Comment by insomnia417** [comment]
> 

thanks, i have change the time type , now it works!
![image](https://github.com/Jackett/Jackett/assets/47959853/b6712152-4c11-4b89-a4c6-cf2f4c363104)

**Comment by garfield69** [comment]
If you would like us to update the indexer so that it works with both date types then by changing back your web setting and performing the test with the enhanced log enabled and providing that log here we should be able to update the indexer so other users do not have the same issue.

**Comment by garfield69** [comment]
v0.21.551

**Comment by insomnia417** [comment]
> v0.21.551

Thank you for your efforts. Both types of time can be used normally !

**Comment by garfield69** [comment]
\o/
