### ISSUE TITLE
ethor.tk - Wrong tracker URL in added torrents

### ISSUE THREAD

**Issue by OXYDER** [Jackett/Jackett#14582]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Torrent client: qBittorrent
Tracker: eThor.tk
```

### Description

Tracker URL need correction

All torrents was added with this tracker URL:

https://ethor.tk/announce/?passkey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

But the real one was:

https://odin.ethor.tk/announce/xxxxxxxxxxxxxxxxxxxxxxxxxxx

### Logged Error Messages

```text
*
```

**Comment by garfield69** [comment]
This has nothing to do with Jackett. Jackett simply provides the link to the web site's download service and the web site provides the torrent which contains the tracker announce that they web sites wants to provide.
If there is a problem with the announce url you need to contact the staff at thor's land and sort it out.
