### ISSUE TITLE
[req]: Gamera (駕瞑羅)

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14589]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Gamera
- URL: https://gamerapt.link/
- Description: Gamera (駕瞑羅) is a CHINESE Private Torrent Tracker for Japanese Monster and Superhero MOVIES / TV
- Minimum Seeding Time and Minimum Ratio (if Private): MR: 0.2
- Additional Comments: 
Engine: NexusPHP KEMURIKUSA 2019-01-09
Registration open ATM
```

**Comment by ilike2burnthing** [comment]
I think the google translate of `Kamala` is wrong, rather it's just Gamera - https://zh.wikipedia.org/wiki/%E5%8D%A1%E7%BE%8E%E6%8B%89

Downloaded torrent files also start with `[Gamera]`.

**Comment by ilike2burnthing** [comment]
Yea, DeepL translates `駕瞑羅PT` as `Driving Meilu PT`.

The wiki page I linked to above has `駕瞑羅` in the first sentence and gets translated differently depending on what you use:

- Bing (or Edge's Translate function) - Gamera
- Google - Kameiluo
- DeepL - Kamiro (although it also says it's homoerotic, rather than fan fiction like the other two)

A Chinese speaking contributor would definitely help! :P

For now though, given so many variations, I'd say going with Gamera or GameraPT is probably the safest bet.

**Comment by brainiac19** [comment]
The characters are simply transliteration of Gamera, which is some kind of monster from some Japanese film or something.

**Comment by garfield69** [comment]
v0.21.580

**Comment by garfield69** [comment]
https://gamerapt.link/ cloudflare Error 1033 Argo Tunnel error

**Comment by ilike2burnthing** [comment]
back up

**Comment by AARON8888** [comment]
It works now for me.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14589#issuecomment-1736065966

**Comment by AARON8888** [comment]
I can open and login well to site. So, withdraw of "Down" list.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14589#issuecomment-1736065966

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14589#issuecomment-1736065966

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14589#issuecomment-1736065966

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14589#issuecomment-1736065966

**Comment by ilike2burnthing** [comment]
back up

**Comment by AARON8888** [comment]
Site is down.
Http Protocol Error.
Error 1033.
Argo Tunnel Error.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14589#issuecomment-1736065966

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14589#issuecomment-1736065966

**Comment by garfield69** [comment]
v0.22.233
