### ISSUE TITLE
Sync between Jackett installations

### ISSUE THREAD

**Issue by alfablac** [Jackett/Jackett#1458]
_First of all. Jackett version for Windows on both servers.._

Tried to use my dyndns address on my offshore server to grab torrents from Jackett but it doesn't seem to work even though I enabled it to be acessed externally.
Is there anyway to sync Jackett between different computers so I can avoid to put dozens of torrent trackers manually on both installations?

Just like a appdata folder that has all configurations that can be shared inbetween.

TIA.

**Comment by kaso17** [comment]
There's no build in method. You'll have to deal with it yourself.
You'll also have to set the JACKETT_KEY environment variable to the same value on both machines (used for the config crypto foo). Additionally tracker cookies, etc. are bound to the IP address which might cause trouble for some trackers.

**Comment by flightlevel** [comment]
Something you'd have to handle yourself, too many things to go wrong doing this in Jackett
