### ISSUE TITLE
[req]: Installing Jackett on WebOS

### ISSUE THREAD

**Issue by 6ebeng** [Jackett/Jackett#14593]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

As a frequent user of your services, I appreciate the quality and functionality of your platform. However, I believe that integrating a new feature can significantly enhance the value proposition for a subset of your users. Specifically, I am suggesting the addition of installation support for Jackett on WebOS.

### Describe the solution you'd like

This feature request as a developer who sees an opportunity to enhance the user experience and reliability of the Lampa application on LGTV WebOS.

As we are aware, for browsing torrents in Lampa, an API from Jackett is used and for loading movies, the TorrServer service is used. Currently, the Jackett server has to be available all the time on a PC, making it somewhat dependent and less reliable for uninterrupted service. This requirement can sometimes pose difficulties for users, especially if their PC is not consistently available or encounters unexpected issues.

To tackle this situation, I would like to propose a feature - the ability to install Jackett directly onto the LGTV's WebOS. By doing this, we could ensure Jackett is consistently available without the need for a PC to be constantly up and running. This feature would not only improve the reliability of the service but also enhance user convenience, allowing them to browse and load movies with greater ease.

Here's a brief overview of how this feature might work:

Develop a WebOS-friendly version of the Jackett server.
Integrate an installation process for this version of Jackett within the Lampa app interface.
Provide a user-friendly way to manage Jackett settings directly from the app.
Establish a method for the app to communicate with the Jackett server on WebOS, without the need for a separate PC.
Adding this feature would likely require collaboration with the Jackett team to ensure compatibility with WebOS, but I believe the improved reliability and user experience would make this worthwhile.

**Comment by ilike2burnthing** [comment]
Given our current resources, nothing even remotely like this is going to be possible.

Instead of running a computer 24/7, I suggest looking at a Pi device or other SBC, or if you want more power and storage then look at a NAS and move to Plex/Jellyfin/Emby instead of Lampa.
