### ISSUE TITLE
[req]: Make ClientTimeout as custom

### ISSUE THREAD

**Issue by Zalatis** [Jackett/Jackett#14600]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

To explain my situation:
I'm trying to get ygg to work, since they've set up cloudflare's security to under attack so I'm using FlareSolverr.
The problem is that the resolution time is around 140 seconds.

So the error "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing." is problematic.

### Describe the solution you'd like

The possibility to manually change the ClientTimeout defined here : 
https://github.com/Jackett/Jackett/blob/9c510bf7ce23f4eaa1814b07875eb19b00fae726/src/Jackett.Common/Utils/Clients/WebClient.cs#L28C3-L28C3

**Comment by garfield69** [comment]
On the Jackett dashboard under the flaresolverr API URL is the flaresolverr Max Timeout (in milliseconds). Set this to 140000 if you want to.

But this is academic, as for most flaresolverr users ATM cloudflare solves are not working, see https://github.com/FlareSolverr/FlareSolverr/issues/811

**Comment by Zalatis** [comment]
But it looks like even after setting the FlareSolverr Max Timeout to something like 500000 the FlareSolverr is able to resolve the challenge, but Jackett still close after 100 seconds , so the solution is getting used after a new "Test"

**Comment by microbrews** [comment]
> But it looks like even after setting the FlareSolverr Max Timeout to something like 500000 the FlareSolverr is able to resolve the challenge, but Jackett still close after 100 seconds , so the solution is getting used after a new "Test"

Same here (docker, v0.21.1104).  I set my FlareSolverr Max Timeout to 300000, then test an indexer.  FlareSolverr log says it took 236 seconds to solve the challenge successfully, but by then jackett had already cancelled the test "due to the configured HttpClient.Timeout of 100 seconds elapsing".  It seems like the FlareSolverr timeout is not properly overriding the default timeout.

**Comment by ilike2burnthing** [comment]
> It seems like the FlareSolverr timeout is not properly overriding the default timeout.

It isn't meant to.
