### ISSUE TITLE
Throwing exception when added ANY indexer

### ISSUE THREAD

**Issue by krazeykow** [Jackett/Jackett#1460]
> at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
>   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <a3c4aef09b90421281b772cc05a43e75>:0
>   at System.Net.Http.HttpClient+<SendAsyncWorker>c__async0.MoveNext () [0x000a9] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs:276
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
>   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <a3c4aef09b90421281b772cc05a43e75>:0
>   at Jackett.Utils.Clients.HttpWebClient+<Run>c__async0.MoveNext () [0x0048c] in C:\projects\jackett\src\Jackett\Utils\Clients\HttpWebClient.cs:156
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
>   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <a3c4aef09b90421281b772cc05a43e75>:0
>   at Jackett.Utils.Clients.IWebClient+<GetString>c__async2.MoveNext () [0x00068] in C:\projects\jackett\src\Jackett\Utils\Clients\IWebClient.cs:92
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
>   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <a3c4aef09b90421281b772cc05a43e75>:0
>   at Jackett.Indexers.BaseIndexer+<RequestStringWithCookies>c__async6.MoveNext () [0x00097] in C:\projects\jackett\src\Jackett\Indexers\BaseIndexer.cs:423
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
>   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <a3c4aef09b90421281b772cc05a43e75>:0
>   at Jackett.Indexers.BitHdtv+<GetConfigurationForSetup>c__async0.MoveNext () [0x00021] in C:\projects\jackett\src\Jackett\Indexers\BitHdtv.cs:64
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /mnt/sdai/rossh/programs/mono-4.8.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
>   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <a3c4aef09b90421281b772cc05a43e75>:0
>   at Jackett.Controllers.AdminController+<GetConfigForm>c__async3.MoveNext () [0x000c7] in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:160

Jackett version:  0.7.1467.0 (same with latest build too)
Mono version (if not using Windows):  4.8.1

Any ideas to what is causing this issue?

-------------------------------

**Comment by flightlevel** [comment]
What OS and device?
Whats the output if you run
```csharp -e 'Console.WriteLine (new System.Net.WebClient ().DownloadString ("https://www.howsmyssl.com/").IndexOf ("1.2"))'```

**Comment by krazeykow** [comment]
I'm using Debian.  I didn't install libcurl.  Thanks for your help!

**Comment by kaso17** [comment]
libcurl is deprecated you should upgrade to mono 5 instead.
