### ISSUE TITLE
[Request]: Use 0 For All Categories

### ISSUE THREAD

**Issue by hbednar** [Jackett/Jackett#14603]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

From what i have read there is no way to automatically use all categories instead of selecting every category one by one for each indexer this is needed for.

This is because sometimes there are better results when selecting all categories, instead of selecting the category you think fits best.

### Describe the solution you'd like

Just like using the option all, can there be an option like that but four categories, perhaps using the number 0

**Comment by ilike2burnthing** [comment]
Are you referring to https://github.com/Jackett/Jackett/issues/14594?

In Jackett's UI search you can just tick the `Select all` option for categories.

For Jackett's API, in the case of the indexer above you'd just need to search using the categories 2000, 3000, 4000, 5000, 6000, 7000, 8000. If you want a catchall for every indexer, you could throw 1000 in there as well so that you get console torrents too, although you will get warnings in Jackett's logs about unsupported categories being used.

**Comment by hbednar** [comment]
@ilike2burnthing 
I should have been more clear i am talking about Torznab and not the UI.
Also, i have seen results for many other categories outside the ones you mentioned.

Which is why i think there should be an option to search for everything and not have to specify the category. 
As sometimes torrents have not been added to the right category or the one you are expecting.

**Comment by ilike2burnthing** [comment]
Yea, the API then. The root categories mentioned will cover everything.

**Comment by ilike2burnthing** [comment]
Which again would be covered - https://github.com/Jackett/Jackett/wiki/Jackett-Categories

**Comment by hbednar** [comment]
@ilike2burnthing 
Sorry, i may not be understanding or explaining myself very well, to clarify. 
Are you saying that in the example above, if i was to use categories `2000 and 8000` that would cover all the search results. Or are you saying that i would have to use all categories `2000, 8000, 2010, 2030 and 2040` ?

**Comment by ilike2burnthing** [comment]
As I said, using the root categories 2000, 3000, 4000, 5000, 6000, 7000, 8000 would search all categories apart from Console torrents (1000), which mteamtp doesn't support.

**Comment by hbednar** [comment]
Thanks for the clarification. 
Is `100000` also a root category, as i haven't added that and this could be why things are missing

**Comment by ilike2burnthing** [comment]
No, it's a custom category.

**Comment by wang923345843** [comment]
> No, it's a custom category.

您好，我是一个#14594的提问者，是一个外行人，不懂得代码等技术问题，不是很懂您的意思，对不起。
对于您的回复，是不是把yaml文件里面XXX对应的默认值改为true ，在默认any搜索的时候，就能出现XXX内容？

**Comment by ilike2burnthing** [comment]
You can do that if you want, yes. Just create a copy of the file and also amend the `name` and `id` to something else, then restart Jackett add your new indexer.

Any future changes we make to the indexer, you will need to make manually to your copy - https://github.com/Jackett/Jackett/commits/master/src/Jackett.Common/Definitions/mteamtp.yml

**Comment by wang923345843** [comment]
我可以不创建副本，直接在原来的yaml修改吗？





------------------ Original ------------------
From: ilike2burnthing ***@***.***&gt;
Date: Sat,Aug 5,2023 10:31 PM
To: Jackett/Jackett ***@***.***&gt;
Cc: wang923345843 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Jackett/Jackett] [Request]: Torznab Use 0 For All Categories(Issue #14603)





 
You can do that if you want, yes. Just create a copy of the file and also amend the name and id to something else, then restart Jackett add your new indexer.
 
Any future changes we make to the indexer, you will need to make manually to your copy - https://github.com/Jackett/Jackett/commits/master/src/Jackett.Common/Definitions/mteamtp.yml

**Comment by ilike2burnthing** [comment]
If you do, it will be overwritten with the next update.
