### ISSUE TITLE
[fastscene] (updating) Login failed: Selector "a[href="account-logout.php"]" didn't match

### ISSUE THREAD

**Issue by MohamadBayz** [Jackett/Jackett#14609]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
2023-08-05 17:18:12	Info	
Using FlareSolverr: http://127.0.0.1:12499/
2023-08-05 17:18:12	Info	
Using proxy: Disabled
2023-08-05 17:18:12	Info	
App config/log directory: /home/hamashareef/.config/Jackett
2023-08-05 17:18:12	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-08-05 17:18:12	Info	
Running in Docker: No
2023-08-05 17:18:12	Info	
File /etc/issue: 
2023-08-05 17:18:12	Info	
Jackett variant: CoreLinuxAmdx64
2023-08-05 17:18:12	Info	
OS version: Unix 5.15.112.0 (64bit OS) (64bit process)
2023-08-05 17:18:12	Info	
Environment version: 6.0.12 (/usr/share/jackett/)
2023-08-05 17:18:11	Info	
Starting Jackett v0.0.0
```

### Description

Fastscene index isn't working anymore when ever i try to add the indexer with the right cookies i get the error `Login failed: Selector "a[href="account-logout.php"]" didn't match` i suspect that they updates there way to login in the website 

### Logged Error Messages

```text
Request finished HTTP/1.0 POST http://jackett.[REMOVED]/api/v2.0/indexers/fastscene/config application/json 266 - 500 - application/json 595.8477ms
2023-08-05 17:21:04	Debug	
No response compression available for HTTPS requests. See ResponseCompressionOptions.EnableForHttps.
2023-08-05 17:21:04	Error	
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="account-logout.php"]" didn't match
2023-08-05 17:21:04	Info	
Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
2023-08-05 17:21:04	Info	
Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 565.5454ms

I would provide full log happily if needed
```

**Comment by ilike2burnthing** [comment]
Working ok here.

Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work

Failing that, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket (note that I redacted the domain from your log above, do the same if posting logs again)

**Comment by MohamadBayz** [comment]
Thank you for clarification i managed to get it working by using a proxy as it was mentioned in the troubleshooting page. Sorry for not checking the troubleshooting page first.
