### ISSUE TITLE
[yggcookie] (updating) Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match

### ISSUE THREAD

**Issue by Nitra971** [Jackett/Jackett#14607]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191	
Using proxy: Disabled	
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No	
Jackett variant: CoreWindows	
OS version: Microsoft Windows NT 10.0.19044.0 (64bit OS)	
Environment version: 6.0.20 (C:\ProgramData\Jackett\)
Starting Jackett v0.21.583
```

### Description

I got this error when i try to use YGGtorrent: 
Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match
Jackett is up to date. I recreate the indexer. Nothing change

### Logged Error Messages

```text
Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match
```

**Comment by ilike2burnthing** [comment]
Update FlareSolverr to v3.3.2 if you haven't already.

Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work

Try YGGTorrent instead.

**Comment by neoestremi** [comment]
Same issue with 3.3.2 and jackett 0.21.583
YGGtorrent is working fine but I need both so I can use the compatibility boxes for episodes number as it doesn't trigger an additionnal search.

**Comment by Nitra971** [comment]
> Update FlareSolverr to v3.3.2 if you haven't already.
> 
> Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work
> 
> Try YGGTorrent instead.

-Update done
-I follow the step but still not working
-YGGTorrent work fine but like neoestremi, I need both. :/

**Comment by ilike2burnthing** [comment]
Disable any VPN or proxy.

Disable IPv6.

**Comment by garfield69** [comment]
the yggcookie indexer is working for me which suggest the issue is at your end.
check the yggcookie config site link and ensure it is set to `https://www3.yggtorrent.wtf/`
ensure that the cookie and useragent are copied from your chrome browser session correctly. use ctrl-c and ctrl-v to copy/paste.
make sure they are coming from the correct development tools page and section. do not use the cookie tab by mistake.

**Comment by Nitra971** [comment]
> the yggcookie indexer is working for me which suggest the issue is at your end. check the yggcookie config site link and ensure it is set to `https://www3.yggtorrent.wtf/` ensure that the cookie and useragent are copied from your chrome browser session correctly. use ctrl-c and ctrl-v to copy/paste. make sure they are coming from the correct development tools page and section. do not use the cookie tab by mistake.

Done that too. Still not working and I have the same error. 
I use and configure this indexer and it's was working fine. But not anymore.

**Comment by garfield69** [comment]
are you quite certain you can login to the site with your browser and view torrents? and you used `https://www3.yggtorrent.wtf/` for both the browser and the indexer?
I've no further ideas. @ilike2burnthing  may have further suggestions on how to proceed.

**Comment by garfield69** [comment]
@neoestremi  you said the the yggtorrent indexer is working fine.
but that you need two ygg indexer for some reason?
then I suggest copying `C:\ProgramData\Jackett\Definitions\yggtorrent.yml` to `C:\ProgramData\Jackett\cardigann\definitions` as `yggtorrent2.yml`, editing the file with a plain text editor, and changing the id and name by appending a `2`
restart jackett and you're good to go ;-)

**Comment by ilike2burnthing** [comment]
Does your cookie look like this (where `X` can be numbers or letters, and `n` is just numbers)?

> v9_promo_details=XXXXX=; account_created=true; v10_promo_details=XXXXXX==; cf_clearance=XXXXXX-nnnnn-0-1-nnnnn-nnn.0.0; ygg_=XXXXXX

Does your user-agent look like this?

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.12.34 Safari/537.36 Edg/115.0.1234.567

If yggtorrent is working (you can perform a successful test search with it), you can open the indexer file (`C:\ProgramData\Jackett\Indexers\yggtorrent.json` on Windows), copy the `cookieheader` value, enter that as the cookie for YGGcookie in Jackett's UI, and for the user-agent use the Windows or Linux UA from here as appropriate (without the quotation marks or colon/semi-colon at the end):

https://github.com/Jackett/Jackett/blob/5d9067c31b8e43a781089d919cb0f837f3e04de1/src/Jackett.Common/Utils/BrowserUtil.cs#L10-L11

**Comment by neoestremi** [comment]
> 

Worked for me, had to improvise a little as I use the container but yeah, using its cookie and the userAgent from flaresolverr made it work right away.

**Comment by ilike2burnthing** [comment]
> I have a quick question, if I edit the value in yggcookie.json file while jackett is running, does it get updated ?

No. Any manual changes to an indexer .json file or a definition .yml file require a Jackett restart to be loaded.

**Comment by Nitra971** [comment]
> Does your cookie look like this (where `X` can be numbers or letters, and `n` is just numbers)?
> 
> > v9_promo_details=XXXXX=; account_created=true; v10_promo_details=XXXXXX==; cf_clearance=XXXXXX-nnnnn-0-1-nnnnn-nnn.0.0; ygg_=XXXXXX
> 
> Does your user-agent look like this?
> 
> > Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.12.34 Safari/537.36 Edg/115.0.1234.567
> 
> If yggtorrent is working (you can perform a successful test search with it), you can open the indexer file (`C:\ProgramData\Jackett\Indexers\yggtorrent.json` on Windows), copy the `cookieheader` value, enter that as the cookie for YGGcookie in Jackett's UI, and for the user-agent use the Windows or Linux UA from here as appropriate (without the quotation marks or colon/semi-colon at the end):
> 
> https://github.com/Jackett/Jackett/blob/5d9067c31b8e43a781089d919cb0f837f3e04de1/src/Jackett.Common/Utils/BrowserUtil.cs#L10-L11

Sooooooo... I try again the indexer and...it work. Don't know why. I do exactly the same thing as before.
And to respond to your message, the cookies and the agent are like the example you gave.

**Comment by ilike2burnthing** [comment]
They've removed the Cloudflare protection for now.
