### ISSUE TITLE
[thepiratebay] (testing) Exception (thepiratebay): Object reference not set to an instance of an object.: Error while parsing field=category, selector=category, value=507: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Bishop-trevorstuart** [Jackett/Jackett#14604]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient22023-08-02 12:52:11	Info	
Using FlareSolverr: http://192.168.1.84:8191/
2023-08-02 12:52:11	Info	Using proxy: Disabled
2023-08-02 12:52:11	Info	App config/log directory: /home/tstuart/.config/Jackett
2023-08-02 12:52:11	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-08-02 12:52:11	Info	Running in Docker: No
2023-08-02 12:52:11	Info	File /etc/issue: Ubuntu 20.04.6 LTS \n \l
2023-08-02 12:52:11	Info	Jackett variant: CoreLinuxAmdx64
2023-08-02 12:52:11	Info	OS version: Unix 5.4.0.155 (64bit OS) (64bit process)
2023-08-02 12:52:11	Info	Environment version: 6.0.20 (/home/tstuart/Jackett/)
2023-08-02 12:52:10	Info	Starting Jackett v0.21.574
```

### Description

Piratebay, but their site doesn't APPEAR to have changed. 
At least when I use the alt URL https://thepiratebay10.info/
all looks the same. 

### Logged Error Messages

```text
Date	Level	Message
2023-08-02 12:46:02	Error	
Jackett.Common.IndexerException: Exception (thepiratebay): Object reference not set to an instance of an object.
```

### Screenshots

[The Pirate Bay - The galaxy's most resilient bittorrent site.txt](https://github.com/Jackett/Jackett/files/12243712/The.Pirate.Bay.-.The.galaxy.s.most.resilient.bittorrent.site.txt)

**Comment by garfield69** [comment]
the Jackett indexer uses TPB API at apibay.org to get the latest data, which the official TPB site a https://thepiratebay.org/ uses, as do some other TPB proxies/clones. 
Other TPB clones sites are pure html and can be behind in their recent page results.
Anyway I see the same issue with my Jackett TPB indexer so I shall dig deeper to see what is going on.

**Comment by garfield69** [comment]
new category `210 Video>CAM/TS` and `507 porn>UHD/4k movies`. I'll update the indexer.

**Comment by garfield69** [comment]
v0.21.580
