### ISSUE TITLE
[req]: spidertk close

### ISSUE THREAD

**Issue by Machou** [Jackett/Jackett#14605]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

hello

Tracker fr_FR spidertk is closed definitely.

src/Jackett.Common/Definitions/spidertk.yml

source official of administrator : https://planete-warez.net/topic/1088/topic-unique-spider-tk-ferm%C3%A9-d%C3%A9finitivement/426?_=1691019010515

Regards

### Describe the solution you'd like

Remove the tracker ^^

**Comment by garfield69** [comment]
Thanks.
Duplicate.
see https://github.com/Jackett/Jackett/issues/12718#issuecomment-1656348174
