### ISSUE TITLE
[cinecalidad] (configuring) Could not find release from this URL.

### ISSUE THREAD

**Issue by nark3l** [Jackett/Jackett#14623]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
error
```

### Description

error

### Logged Error Messages

```text
error
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14621

Also, writing `error` 3 times is extremely unhelpful.
