### ISSUE TITLE
[req]: BT4G

### ISSUE THREAD

**Issue by malomehi** [Jackett/Jackett#14624]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: BT4G
- URL: https://bt4gprx.com/
- Description: BT4G (bt4g.com) is not a tracker and doesn't store any content and only collects torrent metadata (such as file names and file sizes) and a magnet link (torrent identifier)
```

**Comment by garfield69** [comment]
this site does not welcome automation as reported in #9449 so we will not be adding this indexer back to Jackett again.

**Comment by hsp1020** [comment]
> 이 사이트는 [#9449](https://github.com/Jackett/Jackett/issues/9449) 에서 보고된 대로 자동화를 환영하지 않으므로 이 인덱서를 Jackett에 다시 추가하지 않을 것입니다.

I created a BT4G indexer for my personal use as I don't think I'll be adding BT4G to my jackett anymore, but when I add it to my jackett and use it, it pulls the other information fine but not the magnet (infohash), can you take a look at the attachment and tell me what I need to fix?

[bt4g2.txt](https://github.com/user-attachments/files/19633381/bt4g2.txt)
