### ISSUE TITLE
JackettConsole.exe is falsely detected as trojan now by Kaspersy as a trojan

### ISSUE THREAD

**Issue by rafi-d** [Jackett/Jackett#14626]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Latest Windows 10 X64
```

### Description

See screenshot: 

### Logged Error Messages

```text
See screenshot. ackettConsole.exe  is being deleted
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/2458280/99d742ce-e04d-49c9-aa86-87d381f92b52)

**Comment by garfield69** [comment]
virustotal agrees with your assessment that this is a false hit, with 70 of 71 engines giving it the all clear.
https://www.virustotal.com/gui/file/76f51197a738233ee165bf66a330f869df18c0983b18b7861fde59709f91847c?nocache=1
use your kaspersy app to report the false hit if there is such an option, and restore the module from the viruschest and set up an exception to avoid further hits in the meantime.

**Comment by rafi-d** [comment]
I don't think they provide an option to report back. At least I could not find it.
Maybe you can do something in the app to avoid this?

**Comment by garfield69** [comment]
Not practical. We have no idea what is triggering the false hit and we are not going to modify the code just to circumvent 1 out of a possible 100 or more anti-malware apps out on the wild for every platform we package for, windows, linux, macOSX. Sorry, cant see how we can help further with this.

**Comment by garfield69** [comment]
you may find this relevant: https://forum.kaspersky.com/topic/kaspersky-how-to-report-false-positive-22328/

**Comment by rafi-d** [comment]
OK, thanks!

**Comment by rafi-d** [comment]
> you may find this relevant: https://forum.kaspersky.com/topic/kaspersky-how-to-report-false-positive-22328/

Feel free to send them your file as well... ;)
