### ISSUE TITLE
[cinecalidad] (updating) Could not find release from this URL.

### ISSUE THREAD

**Issue by RawSmokeTerribilus** [Jackett/Jackett#14621]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
webclient
linux redhat
no flaresolver
```

### Description

the web from the indexer is on but, in jacket, it does not work

### Logged Error Messages

```text
An error occurred while updating this indexer
Could not find release from this URL.
```

**Comment by garfield69** [comment]
they have changed their sub domain.
use your Jackett dashboard to edit the indexer config and change the site link to `https://wwv.cinecalidad.tf/`
642944e

**Comment by RawSmokeTerribilus** [comment]
doesn´t work

 An error occurred while testing this indexer
Test search in Cinecalidad => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

**Comment by garfield69** [comment]
The indexer works for me so this suggests the issue is at your end.
provide an enhanced log and we can take a look to see if we can spot the issue. 
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by RawSmokeTerribilus** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/12316422/log.txt)

**Comment by garfield69** [comment]
the log shows that you are still using `https://vww.cinecalidad.tf/`
as I said earlier, update the sitelink to `https://wwv.cinecalidad.tf/`
