### ISSUE TITLE
[hdatmos] (testing) Exception (hdatmos): Login failed: No form found on https://hdatmos.club/login.php using form selector form[action="takelogin.php"]: Parse error

### ISSUE THREAD

**Issue by WoodC2011** [Jackett/Jackett#14632]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
11
```

### Description

11

### Logged Error Messages

```text
11
```

**Comment by garfield69** [comment]
By not providing any information other that the general error you are wasting your time and ours. 
Next time fill in the form correctly (all three sections) and provide an enhanced log so that we have some data to work with.
