### ISSUE TITLE
Bit-HDTV

### ISSUE THREAD

**Issue by Fiala06** [Jackett/Jackett#1463]
I'm receiving the following error now with Jackett for bit-hdtv. It's worked fine for months up until a day or 2 ago.
Error I receive: "Configuration failed: String was not recognized as a valid DateTime."

IPT also started giving me the same issue, but after I deleted and re-added it, it works fine. Didn't resolve bit-hdtv tho :/

Jackett Version 0.7.1477.0 
[LOG.txt](https://github.com/Jackett/Jackett/files/1061804/LOG.txt)

**Comment by ConorNevin** [comment]
Also having the same issue - I suspect the RSS format has changed. The added field now contains additional text besides the date which explains the error. Example below.

```
<added>Added: 2017-06-08 16:23:38</added>
```

**Comment by kaso17** [comment]
fixed with 81f2c7e91c9d25eaf86c6ab75f29dc07315d8eea
