### ISSUE TITLE
[req]: Locadora will be unavailable

### ISSUE THREAD

**Issue by costaht** [Jackett/Jackett#14633]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Just a heads up. Locadora will be unavailable for about 7 days (maybe less) starting on 08/18. 

### Describe the solution you'd like

Please don't remove it from the trackers list.
Thank you!

**Comment by ilike2burnthing** [comment]
We'll treat it the same as any other indexer; we'll mark it as down to monitor it, and if it's offline for a month then it will be removed. Thanks for the heads up.
