### ISSUE TITLE
[req]: i want to ask what c# framework did jackett use

### ISSUE THREAD

**Issue by coboy2000** [Jackett/Jackett#14639]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hi i want ask what is the c# framework did jackett use. Because i want to hack it. Thanks

### Describe the solution you'd like

Just all the frameworks or development stacks jackett use. Thanks

**Comment by ilike2burnthing** [comment]
Should get everything you need from:
- https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md#setting-up-your-environment
- https://github.com/Jackett/Jackett/blob/master/azure-pipelines.yml
