### ISSUE TITLE
[req]: OnlyEncodes

### ISSUE THREAD

**Issue by edge20200** [Jackett/Jackett#14635]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: OnlyEncodes
- URL: https://onlyencodes.cc
- Description: OnlyEncodes is a Private Tracker for MOVIES / TV
- Minimum Seeding Time and Minimum Ratio (if Private): 48 hours min and 0.4 min ratio
- Additional Comments: 
```
Engine: unit3d 6.5.0
Registration currently open

**Comment by garfield69** [comment]
rules state MST is 7 days

**Comment by garfield69** [comment]
Ah, good to know. thank you.

**Comment by garfield69** [comment]
And for clarity, is seeding 48h or 0.4 ratio, or is the 48h seed time mandatory, and the 0.4 ratio is global?

**Comment by garfield69** [comment]
Ah I see. I will adjust the indexer to reflect this. Thanks.

**Comment by garfield69** [comment]
v0.21.648

**Comment by garfield69** [comment]
https://onlyencodes.cc/ Error 503: Service Unavailable! Sorry, we are doing some maintenance. Please check back soon.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14635#issuecomment-2000777799

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14635#issuecomment-2000777799
