### ISSUE TITLE
[req]: I hope the Jackett API will support returning site domain names

### ISSUE THREAD

**Issue by TonyLiooo** [Jackett/Jackett#14640]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

When using the Jackett API, I encounter difficulties with deduplication due to the absence of site domain names in the returned information. As I need to implement additional functionality for certain sites and still want to utilize Jackett's indexing capabilities, there is currently some overlap in features. To address this, I kindly request the author to consider adding the ability to include site domain names in the API responses. This enhancement would greatly facilitate the development and integration of Jackett into other applications. Thank you for your consideration!

### Describe the solution you'd like

Request to add support for returning site names along with their domain names in the API responses.

### Describe alternatives you've considered

I haven't found an alternative solution for now. I hope the author could consider adding the functionality to include domain names in the API responses.

**Comment by ilike2burnthing** [comment]
It is. For each result the details URL is returned as `<comments>` and the download URL as `<guid>` (unless it's a magnet).

Are you asking for something other than this?

**Comment by TonyLiooo** [comment]
I also hope that I can obtain the actual domain name of the sites I've added through the API. Currently, the obtained link format is '....../api/v2.0/indexers/ubits/results/torznab/'. In addition to this, I would appreciate it if the API could return the real link 'https://ubits.club/index.php', which can be used for site validation during usage.

**Comment by ilike2burnthing** [comment]
See `rss.channel.link`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://localhost/Jackett/" rel="self" type="application/rss+xml" />
    <title>UBits</title>
    <description>UBits is a CHINESE Private torrent tracker for MOVIES / TV / GENERAL</description>
    <link>https://ubits.club/</link>
    <language>en-US</language>
    <category>search</category>
    <item>
      <title>NAME 2007 1080p CEE BluRay x265 DDP5.1-UBits</title>
      <guid>https://ubits.club/download.php?id=XXXX</guid>
      <jackettindexer id="ubits">UBits</jackettindexer>
      <type>private</type>
      <comments>https://ubits.club/details.php?id=XXXX&amp;hit=1</comments>
      <pubDate>Wed, 16 Aug 2023 03:16:01 +0100</pubDate>
      <size>10426033152</size>
      <grabs>83</grabs>
      <description>完美陌生人/勾引陌生人/亲陌杀机 简体/繁体  主演：布鲁斯·威利斯 哈莉·贝瑞</description>
      <link>http://localhost/Jackett/dl/ubits/?jackett_apikey=REMOVED&amp;path=XXXXX&amp;file=NAME+2007+1080p+CEE+BluRay+x265+DDP5.1-UBits</link>
      <category>2000</category>
      <category>100401</category>
      <enclosure url="http://localhost/Jackett/dl/ubits/?jackett_apikey=REMOVED&amp;path=XXXXX&amp;file=NAME+2007+1080p+CEE+BluRay+x265+DDP5.1-UBits" length="10426033152" type="application/x-bittorrent" />
      <torznab:attr name="category" value="2000" />
      <torznab:attr name="category" value="100401" />
      <torznab:attr name="genre" value="" />
      <torznab:attr name="seeders" value="56" />
      <torznab:attr name="peers" value="58" />
      <torznab:attr name="minimumratio" value="0.8" />
      <torznab:attr name="downloadvolumefactor" value="0" />
      <torznab:attr name="uploadvolumefactor" value="2" />
    </item>
```
