### ISSUE TITLE
[req]: PTLSP

### ISSUE THREAD

**Issue by CyberRim** [Jackett/Jackett#14651]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: PTLSP
- URL: https://www.ptlsp.com/
- Description: PTLSP is a CHINESE Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): none stated
- Additional Comments:
```
Engine: NexusPHP v1.8.5 2023-07-29
Registration is invitation only ATM

**Comment by CyberRim** [comment]
An invite was send to jacketttest@gmail.com

**Comment by garfield69** [comment]
v0.21.687

**Comment by ilike2burnthing** [comment]
https://www.ptlsp.com/- Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14651#issuecomment-1839562544

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
I'm getting a mix of:
- Web server is down Error code 521
- Bad gateway Error code 502
- Connection timed out Error code 522
- SSL handshake failed Error code 525

Jackett at one point returned `The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set.`

Of course, now that I've typed this out and gone back to check again, it's working 🙄 

After another 5mins, it's still up, so 🤷 

Announcements from a few days mention server migration, so maybe still that. It fine right now though.

**Comment by ilike2burnthing** [comment]
https://www.ptlsp.com/

> Bye bye Broken Circle, the PTLSP site is permanently closed and will never be repeatedly cross hopped! I would like to sincerely apologise to all users!

**Comment by garfield69** [comment]
v0.22.119
