### ISSUE TITLE
[req]: magnetdl

### ISSUE THREAD

**Issue by thaynos** [Jackett/Jackett#14660]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: magnetdl
- URL: www.magnetdl.com
- Description: idk
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): na
- Additional Comments: idk if u guys already know this but theres boatloads of torrent sites on https://fmhy.pages.dev/torrentpiracyguide/ and in fmhy in general, found magnetdl from there, might wanna take a look!
```

**Comment by garfield69** [comment]
removed at request of site Admin. See https://github.com/Jackett/Jackett/pull/10347#issue-530982565 for more details.
