### ISSUE TITLE
[req]: start background service on program launch

### ISSUE THREAD

**Issue by Zoomaaa** [Jackett/Jackett#14666]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

when launching jackett. you have to manually run the background service

### Describe the solution you'd like

it would better if that happened automatically

**Comment by Zoomaaa** [comment]
The operating system is windows
Jackett is installed. I installed it using the "Jackett.Installer.Windows.exe" from the releases page.

**Comment by ilike2burnthing** [comment]
The service should be running after install and on every start of your computer, unless you unticked `Install as a Windows Service` in the installer (if so, reinstall and tick it). I'm not sure what else is being asked for here.

**Comment by Zoomaaa** [comment]
I have unticked the "install as a windows service" option when installing, because I want the service to only work when I launch the program instead of on every windows startup. On launch, however, the service isn't started. Instead, you need to manually right click on the jackett icon in the taskbar and click "start background service". I think it would be better if the service automatically started when launching jackett.

**Comment by ilike2burnthing** [comment]
Double-clicking the desktop or start menu shortcut launches JackettTray and JackettConsole, which is all that is needed when not installing as a service. Trying to run JackettService when it's not installed as a service just results in the process terminating.

Are you not able to replicate this by checking in Task Manager? If not, what are you seeing?

**Comment by garfield69** [comment]
There is a discrepancy in the OP report. 
If the Jackett  installer is run with the `install as a service` checkbox **not** ticked, then the Jackett system tray should only show the following options:
- Open Web UI
- Auto start on boot
- shutdown.

The options on the systray to
- stop background service
or
- start background service

should only appear if the `install as a service` checkbox is ticked.

IF the OP is seeing background options on the systray but is running a non-service install, then perhaps at some point one or more installs with either configuration got interrupted/cancelled resulting in a mixed install?

I suggest running the installer one more time with the  `install as a service` checkbox **not** ticked to ensure a complete installation.

**Comment by Zoomaaa** [comment]
> There is a discrepancy in the OP report. 
I Apologize for the confusion I caused. Indeed I installed with "install as a service" option ticked. 
I reinstalled with the mentioned option unticked and now the program behaves like I want. Still I think with the option ticked the background process should start on program launch.
