### ISSUE TITLE
[req]: Tray icon version info

### ISSUE THREAD

**Issue by Tmp341** [Jackett/Jackett#14681]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I'm using Jackett on Windows 10. I don't know if it is "portable/zip archive" problem or a feature hasn't been added yet . But i don't see version info when i hover over the tray icon. Sometimes updater doesn't trigger, so i can't be sure if i'm using latest version.

### Describe the solution you'd like

When i hover over Jackett tray icon, i would like to see version info like this if it isn't too much:
![ssss](https://github.com/Jackett/Jackett/assets/1683388/55b668f8-b99c-40e3-9a13-a8add4548ce1)

**Comment by ilike2burnthing** [comment]
I'm sure this can be changed, although for now just scroll to the bottom of Jackett's webUI, the version number is there.

**Comment by garfield69** [comment]
v0.21.750
