### ISSUE TITLE
GayTorrent.ru Indexer Failure HTML Page?

### ISSUE THREAD

**Issue by dstho** [Jackett/Jackett#14694]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
<div class="panel panel-default"><div class="panel-heading"><h3 class="panel-title">Download failed!</h3></div><div class="panel-body gtstandard" align="left"><h1>usage violation</h1>Make sure, you click on the download buttons from search, browse or details Page<br>If it still does not work, try using a different Browser</div></div></div>

As well as this error below:

<error code="500" description="Invalid torrent file specified" />
```

### Description

I'm having an issue with the GayTorrent.ru/Gaytor.rent tracker downloading torrent files. The indexer itself works and detects movies/tv shows, but when adding a file it doesn't download and when I try to manually force it download a torrent through Radarr/Sonarr, it fails.

Somebody looked into it for me and found a curious error. When downloading a torrent, it apparently directs to an HTML page.

Here's my Radarr logs https://privatebin.net/?76b22e8981e1ef20#6BAJE8eMZG3RekCd9h3y9cgy5hmkrycZHEeJ8rVTWtrK
Here's my Prowlarr logs. https://privatebin.net/?c9dae82aa35bc037#GeSx36SCeZZdscvqzXZmx3odu7VfEQ2cqacVoeFqtgKy

### Logged Error Messages

```text
Indexers unavailable due to failures: GAYtorrent.ru (Prowlarr)
```

**Comment by garfield69** [comment]
I checked and the indexer is working for me, I can get downloads by clicking the dashboard DL button no problems.

IF you are getting an intermediate page instead of the download then this means that you have exceeded your daily allocation of downloads.
Here is a typical example of that intermediate screen
```
Warning: Just 4 download slots left for today!
gaytor.rent has a daily download limit, which is bound to your share ratio and amount of uploaded own torrents:

You downloaded 0 torrent(s) in the past 24 hours
You are allowed to download 4 torrent file(s) per day. This is based on your share ratio of 174.813 and 0 uploaded own torrent(s).
Increase your limits and add up to 50 slots/day with a [Donation](https://www.gaytor.rent/donate.php)Indicates user has donated to the Site

More infos about our ratio system can be found [here](https://www.gaytor.rent/rationator.php)
Continue download? [Yes](https://www.gaytor.rent/download.php?id=a12b3c4d5e6f7g8h9i&n=File%20Name&p=dodownload) or [Back](https://www.gaytor.rent/details.php?id=a12b3c4d5e6f7g8h9i)
```

So login to the web site and check your daily allocation and avoid exceeded the limit to continue downloading.
Begin a download on the web site to see what is preventing you completing the download request by reading that page and following its instructions.

There is nothing we can do about this from Jackett's side of the fence.

**Comment by dstho** [comment]
> I checked and the indexer is working for me, I can get downloads by clicking the dashboard DL button no problems.
> 
> IF you are getting an intermediate page instead of the download then this means that you have exceeded your daily allocation of downloads. Here is a typical example of that intermediate screen
> 
> ```
> Warning: Just 4 download slots left for today!
> gaytor.rent has a daily download limit, which is bound to your share ratio and amount of uploaded own torrents:
> 
> You downloaded 0 torrent(s) in the past 24 hours
> You are allowed to download 4 torrent file(s) per day. This is based on your share ratio of 174.813 and 0 uploaded own torrent(s).
> Increase your limits and add up to 50 slots/day with a [Donation](https://www.gaytor.rent/donate.php)Indicates user has donated to the Site
> 
> More infos about our ratio system can be found [here](https://www.gaytor.rent/rationator.php)
> Continue download? [Yes](https://www.gaytor.rent/download.php?id=a12b3c4d5e6f7g8h9i&n=File%20Name&p=dodownload) or [Back](https://www.gaytor.rent/details.php?id=a12b3c4d5e6f7g8h9i)
> ```
> 
> So login to the web site and check your daily allocation and avoid exceeding the limit to continue downloading. Begin a download on the web site to see what is preventing you completing the download request by reading that page and following its instructions.
> 
> There is nothing we can do about this from Jackett's side of the fence.

That's extremely odd...it hasn't worked for me since day one. Odd though, there's no way I could have exceeded my daily allocation though.

Permissions	You downloaded 0 torrent(s) in the past 24 hours
You are allowed to download 145 torrent file(s) per day. This is based on your share ratio of 1.192 and 6 uploaded own torrent(s).

**Comment by garfield69** [comment]
This is the support site for Jackett, so I used the Jackett indexer to test.
I don't use Prowlarr so it is possible this is an issue with that app.
Let's wait for one of the other team members to respond to this ticket.
@ilike2burnthing  can you check on Prowlarr if the indexer is working for you there? Thanks.

**Comment by garfield69** [comment]
As a point of interest your Prowlarr log shows the same error html as https://github.com/Prowlarr/Prowlarr/issues/616 which was closed back in Nov 2021. So there is some history there. I find it odd that no one else has reported an issue with this indexer on Prowlarr since then, but perhaps that ticket needs to be re-opened and investigated from the Prowlarr side.

**Comment by garfield69** [comment]
v0.21.812

**Comment by dstho** [comment]
Just wanted to confirm as well on my end that the fix by @ilike2burnthing has apparently resolved the issue on my end. Thanks for all your help guys!
