### ISSUE TITLE
[epublibre] (configuring) The SSL connection could not be established

### ISSUE THREAD

**Issue by alescofet** [Jackett/Jackett#14690]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://localhost:8191/
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
Environment version: 6.0.21 (C:\ProgramData\Jackett\)
Starting Jackett v0.21.756
```

### Description

Can't connect to EpubLibre

### Logged Error Messages

```text
An error occurred while configuring this indexer
The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject] CN=www.epublibre.org [Issuer] CN="allot.com/emailAddress=info@allot.com", OU=Allot, O=Allot, L=Madrid, S=Madrid, C=ES [Serial Number] 31140864000000003603000000000000 [Not Before] 12/16/2016 2:07:49 PM [Not After] 12/16/2026 2:07:49 PM [Thumbprint] 9BEE956A1F4811D65184BCAD55F4C969A3EF1847
```

**Comment by garfield69** [comment]
You are being blocked by your ISP or by some anti-malware app on your PC or router.
The official certificate for epublibre is issued by Let's Encrypt, thumbprint cba761a043e5dc8e2c68386720dd8804617af17d
You are seeing a certificate issued by Allot Madrid, thumbprint of 9bee956a1f4811d65184bcad55f4c969a3ef1847

Use your Jackett dashboard to edit the epublibre config and select the alternate site link from unblockit and see if that works for you.

If that does not work, Then you needs to either whitelist the address in your security app, or try switching DNS from the ISP provided one to a public one such as cloudflare's 1.1.1.1 or Google's 8.8.8.8, or  use a VPN or proxy.
