### ISSUE TITLE
[req]: Add Transmission (rpc) download

### ISSUE THREAD

**Issue by fargom2** [Jackett/Jackett#14691]
### Is there already a request for your feature?

- [x] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I want to send torrent files directly to a Transmission server

### Describe the solution you'd like

Add another button to download column in Manual Search, that send magnet or torrent to a Transmission rpc server
(if Transmission rpc server is configured)

Documentation can be found here:
https://trac.transmissionbt.com/browser/trunk/extras/rpc-spec.txt?rev=14463#L356

A sample in c#:
Agregate Transmission.API.RPC library, and:

using Transmission.API.RPC;
using Transmission.API.RPC.Entity;

TransmissionClient client = new TransmissionClient("http://localhost:9091/transmission/rpc", "username", "password");

NewTorrent torrent = new NewTorrent
{
    //magnet
      Filename = "magnet:?xt=urn:btih:...",

  //or

   //file
   string torrentFilePath = "ruta/del/archivo.torrent";
   byte[] torrentFileData = File.ReadAllBytes(torrentFilePath);
   Metainfo = Convert.ToBase64String(torrentFileData)
};

// Agregar la tarea al servidor de transmisión
client.TorrentAdd(torrent);

**Comment by ilike2burnthing** [comment]
Would configuring Transmission's `watch-dir` and Jackett's `Blackhole directory` currently resolve this?

**Comment by garfield69** [comment]
Note: we will not be adding direct API support to the dozen or so bittorrent clients.
Jackett's main remit is to support torznab apps (which manage their own torrent client interfaces), with secondary support to dashboard manual searches (where magnets and .torrents are handled by the browser displaying the dashboard, and OS .torrent and magnet filetype interface, which allows torrents to be picked up by whatever client is associated with these torrents types).
