### ISSUE TITLE
Not able to download recent torrents from "Solid Torrent" locally

### ISSUE THREAD

**Issue by malomehi** [Jackett/Jackett#14699]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.0.2:8191/
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.812-ls164)
File /etc/issue: Welcome to Alpine Linux 3.18
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.4.0.4 (64bit OS) (64bit process)
Environment version: 6.0.22 (/app/Jackett/)
```

### Description

The step to reproduce is to try to download a recent torrent locally from Solid Torrent with the "Download locally" button (arrow pointing down).

This does not seem to be an issue with not recent torrents, so this is likely an issue for torrents that are a few hours/days old only.

### Logged Error Messages

```text
Error downloading. indexer: solidtorrents path: https://itorrents.org/torrent/D9CE5D7CB1BB8235074CD00C008046CF514159F1.torrent?title=[Bitsearch.to]La Rueda del Tiempo [4k 2160p][Cap.205](wolfmax4k.com)
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 85
```

**Comment by garfield69** [comment]
Solidtorrents uses https://itorrents.org to provide a .torrent (this service converts magnets into .torrents).
However itorrents can often be up to 4 hours behind the latest releases, and when it does not have a requested magnet hashinfo in its database it redirects to limetorrents.lol (which is the site that originally provided the itorrents service).

There is nothing Jackett can do about this.

Solidtorrents does also provide magnets, so if you cannot wait until the .torrent is available then use the magnet.

**Comment by malomehi** [comment]
Understood. Thanks for the detailed explanation.

**Comment by bugsyb** [comment]
Would it be possible to add to Jackett magnet to torrent converter, like itorrents does, or maybe find a way to integrate Jacket with, i.e. qbittorrent as it accepts Magnet?

**Comment by ilike2burnthing** [comment]
Jackett works with qBittorrent just fine.

**Comment by bugsyb** [comment]
When there is just magnet it fails as expects itorrents to generate torrent file from Magnetlink.
Qbittorrent supports adding downloads via Magnet links and there's no need to use third party service (which also does not always provide required torrent).

Please share how to get that all working with just Magnet available, as I must be missing something.

**Comment by ilike2burnthing** [comment]
Results for SolidTorrent provide both torrent and magnet; if the torrent fails just use the magnet instead.

Are you instead using qBittorrent to auto-download through its RSS feed function?

**Comment by bugsyb** [comment]
SolidTorrent seems to provide torrent only via itorrents which is not always available, i.e. for new ones (24+ delay).
In this case, itorrents automatically redirects to Limetorrents general page and that is where when Jacket is used, i.e. by Medusa, it fails. Manually, it is still possible to copy Magnetlink and it would be just cool if torrents could be generated automatically from Magnetlink in such situations.
