### ISSUE TITLE
[req]: SceneLinks

### ISSUE THREAD

**Issue by alexdinu05** [Jackett/Jackett#14702]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: SceneLinks
- URL: https://scenelinks.me/
- Description:  SceneLinks is a ROMANIAN Private Torrent tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MST 3d
```
Engine: unit3d 7.0.3

**Comment by garfield69** [comment]
adding adult section I missed on first pass

**Comment by garfield69** [comment]
v0.21.841

**Comment by garfield69** [comment]
scenelinks -> unit3d 7.0.3
seems the accounts have been migrated, but I had to use the `forgot password` option to get access.
I'll replace the tbdev indexer with a unit3d one

**Comment by garfield69** [comment]
https://www.scenelinks.me/ cloudflare Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up
