### ISSUE TITLE
[mteamtp2fa] (testing) Exception (mteamtp2fa): Login failed: Selector "a[href="logout.php"]" didn't match: Parse error

### ISSUE THREAD

**Issue by PN62323424** [Jackett/Jackett#14707]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
The kp.m-team.cc site was revamped yesterday, causing the ones in jackett to fail
```

### Description

The kp.m-team.cc website has been revamped, rendering the ones in jackett invalid

### Logged Error Messages

```text
none
```

**Comment by PN62323424** [comment]
I can access mteam from my Singapore IP, it's been updated, if you can't access it from your place, I'm not too

**Comment by PN62323424** [comment]
> Not yesterday, it's being revamped right now and it's too unstable to browse so I get why the need to lie.
> 
> ```
> System upgrade and maintenance under way
> The upgrade is in progress and is expected to take 24 hours, please be patient.
> ```
I managed to log in 10 minutes ago and now I'm prompted that it's under maintenance here as well, so I can provide a screenshot of me logging in if needed. Also I have no incentive to lie, I'm simply reporting on the site updates

**Comment by PN62323424** [comment]
https://ibb.co/FghJntF   

I think I may have just happened to log in at some point.

**Comment by PN62323424** [comment]
> The lie is `yesterday` when it's now. 😭

What I mean is that mteam started to change its version since yesterday, except that English is not my native language, and I'm using Google Translate to communicate with you, so I'm not expressing myself very clearly

**Comment by garfield69** [comment]
In which case we could:
1. replace the content of the mteamp indexer with the content from the mteamp2fa indexer, 
2. apart from the description of the original mteamp indexer, 
3. delete the mteamp2fa indexer since its now redundant
4. add an indexer-manager redirect for mteamp2fa to mteamp

But if they switch their search engine and results presentation to dynamic html then cardigann will not cope and the indexer may well need to be upgraded to C# ....

**Comment by garfield69** [comment]
we just have to hope that the cookie method works, and that they do not have a ridiculous short lifetime on the cookie session expiration. People hate having to fetch cookies daily for example ;-D

**Comment by garfield69** [comment]
mind you, if they are using an API then perhaps there will be a api key or session authority, so using cookies may net be required.

**Comment by garfield69** [comment]
looks like they have switched back to a regular html login page. Have they backed out their upgrade and restored their prior build? Do the existing indexers work?

**Comment by PN62323424** [comment]
> looks like they have switched back to a regular html login page. Have they backed out their upgrade and restored their prior build? Do the existing indexers work?

Yes，it works，I tested “M-Team - TP (2FA)” and it has no problems
