### ISSUE TITLE
Virus Warning: Webroot W32.Trojan.MSILZilla on Jackett.Common.dll

### ISSUE THREAD

**Issue by tonylost** [Jackett/Jackett#14703]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
View link
```

### Description

On run with WebSecure Anywhere
Webroot
W32.Trojan.MSILZilla
VirusTotal link:
https://www.virustotal.com/gui/file/c9d3ca3be9e42262f51c5d879f1d5de13c7e2d835c238c462ac6f6a7323cdec4/detection/f-c9d3ca3be9e42262f51c5d879f1d5de13c7e2d835c238c462ac6f6a7323cdec4-1695093273

### Logged Error Messages

```text
Virus Alert
1 security vendor and no sandboxes flagged this file as malicious
c9d3ca3be9e42262f51c5d879f1d5de13c7e2d835c238c462ac6f6a7323cdec4
Jackett.Common.dll
```

**Comment by garfield69** [comment]
Thank you for reporting.
However, give the other 69 vendors gave it a pass, it would seem most likely this is a false hit by the one vendor.
