### ISSUE TITLE
[REQ] CZTeam 

### ISSUE THREAD

**Issue by VadVoci** [Jackett/Jackett#1470]
Please add CZTeam Torrent Tracker https://czteam.club (Romanian tracker / Lot of English Content)
The Invite already sended to kaso1717...

**Comment by flightlevel** [comment]
Isn't this already present?
https://github.com/Jackett/Jackett/blob/master/src/Jackett/Definitions/czteam.yml

**Comment by kaso17** [comment]
it is
@VadVoci feel free to reuse your invite (I won't use it)
