### ISSUE TITLE
[req]: Exitorrent.org

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14709]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Exitorrent.org
- URL: https://exitorrent.org/
- Description: Exitorrent.org is a POLISH Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MST 2d
- Additional Comments: 
Engine: TBsource v1.5.0
Registration is invitation only ATM
Not to be confused with exitorrent.eu
```

**Comment by garfield69** [comment]
v0.21.887

**Comment by lukjod** [comment]
Categories are wrong supported always gave me 0 search results.
