### ISSUE TITLE
[coastalcrew] (testing) Test search in Coastal-Crew => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by CleanupSeeker61** [Jackett/Jackett#14719]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett run on docker
```

### Description

Indexer not work

### Logged Error Messages

```text
??
```

### Screenshots

[REMOVED]

**Comment by ilike2burnthing** [comment]
I removed your screenshot as it showed your public IP. Your Jackett is exposed to the internet; if for some reason it needs to be, use a password, same for any other applications you're using. Also, don't run the container with root privileges.

---

To your issue, there should be a blue arrow at the end of each result on the [search page](https://coastal-crew.bounceme.net/browse.php), which when clicked downloads a torrent. Does this work for you in browser? If not, check your PMs in case your download privileges have been restricted.

If you still have issues, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
