### ISSUE TITLE
[req]: PassThePopcoorn

### ISSUE THREAD

**Issue by zotoro** [Jackett/Jackett#14712]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: PassThePopcorn
- URL: https://passthepopcorn.me/
- Description: Private Movie Tracker
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 24 hours? Maybe 48 hours.
- Additional Comments: I know PTP was on Jackett before its downtime. Now that the site is back up, I would like to add PTP back to my indexer list. Maybe it's a problem on my end, but PTP is no longer shown in my added indexers and doesn't show up when searching the 'add indexed' option.
```

**Comment by garfield69** [comment]
Closing as a duplicate.  #14591
PTP has already been added back to Jackett, the release with the indexer available is due out in about 7 hours or so.
