### ISSUE TITLE
[enhancement] cardigann indexers with captcha, prevent trying to log in again when cookies expire.

### ISSUE THREAD

**Issue by wloot** [Jackett/Jackett#14726]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-09-27 12:35:49	Info	Running in Docker: Yes (image build: v0.21.916-ls173)
2023-09-27 12:35:49	Info	File /etc/issue: Welcome to Alpine Linux 3.18
2023-09-27 12:35:49	Info	Jackett variant: CoreLinuxMuslAmdx64
2023-09-27 12:35:49	Info	OS version: Unix 5.15.0.83 (64bit OS) (64bit process)
2023-09-27 12:35:49	Info	Environment version: 6.0.22 (/app/Jackett/)
2023-09-27 12:35:48	Info	Starting Jackett v0.21.916
```

### Description

My idea is that due to some like session expiration, jackett tried to log in again using the previous information, but the captcha has changed, which ultimately resulted in the IP being banned from logging in by the website.

### Logged Error Messages

```text
Banned from logging in
```

**Comment by garfield69** [comment]
yes that is a very likely scenario.
We should turn this into a general enhancement request, to ask the C# devs if they can change the cardigann processor to not perform an auto-login retry if there is a captcha present, and just throw an exception error instead.

**Comment by ilike2burnthing** [comment]
Is that not done here?

https://github.com/Jackett/Jackett/blob/865895cb83ea3c6319a6f1ca56a208275db6df34/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1028-L1033

**Comment by garfield69** [comment]
Hmm. So either the OP's conclusion are incorrect,  or that code is not being invoked.
Unfortunately we do not have an enhanced log to see if we did get the `found captcha ... aborting` message before the ip was blocked.

**Comment by ilike2burnthing** [comment]
I have previously seen that in my own logs, so I think it is working, however if some automation software was repeatedly making search requests, which were then kicked backed to login, that might get caught as suspicious behaviour.

**Comment by garfield69** [comment]
Closing as previously implemented, and original miss-diagnosis of likely cause of IP being blocked. As no logs were provided its not possible to investigate further.
