### ISSUE TITLE
result search for arche torrent via couch potato

### ISSUE THREAD

**Issue by helmutwasa** [Jackett/Jackett#1472]
Jackett version:  0.7.1437.0
Mono version (if not using Windows):  5.0.1.1

-------------------------------

Hello,

When i search on Archetorrent via couchpotato, the results of the search "Logan 2017" found 0 torrent.
On the manual searh of jackett, for the same search none of the result contain to word "logan" 

BUT 

if i search only for "Logan", i got it :) 
Is it possible to remove the year for archetorrent search?

Thanks in advance

**Comment by kaso17** [comment]
@elliotvr can you help with this one?

**Comment by elliotvr** [comment]
@kaso17 Jackett works with "Logan 2017" with the latest version.

@helmutwasa update to at least v0.7.1467

**Comment by helmutwasa** [comment]
thanks for your reply, 

I've updated Jackett to the latest (0.7.1437.0) and it still not find "lot" of result, let me explain:

Actually on the manual search of Jackett with only archetorrent activated, when i search "Logan 2017" (the search for torrentpotato adapter) i get only 2 relevant results with the title of the movie, others have "2017" on the name but not with "Logan" on the title.

If i search for "Logan" only, the result page is full of Logan movies :)

It appear with many other movies i try to search, here is my logs:

`Jun 20, 2017 06:54:13 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Risen 2016
Jun 20, 2017 06:54:10 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: How to Be a Latin Lover 2017
Jun 20, 2017 06:54:08 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: A Cure for Life 2017
Jun 20, 2017 06:54:00 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Burnt 2015
Jun 20, 2017 06:53:55 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Titan A.E. 2000
Jun 20, 2017 06:53:51 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Forsaken 2015
Jun 20, 2017 06:53:37 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Creed 2015
Jun 20, 2017 06:53:35 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Gold 2016
Jun 20, 2017 06:53:32 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: All Things Must Pass 2015
Jun 20, 2017 06:53:28 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Miracles from Heaven 2016
Jun 20, 2017 06:53:19 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Alien  Covenant 2017
Jun 20, 2017 06:53:12 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Baby Boss 2017
Jun 20, 2017 06:53:07 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Your Name 2016
Jun 20, 2017 06:53:04 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Where to Invade Next 2015
Jun 20, 2017 06:52:55 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Pirates des Caraïbes  La vengeance de Salazar 2017
Jun 20, 2017 06:52:49 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Ip Man 3 2015
Jun 20, 2017 06:52:40 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Les Gardiens de la Galaxie Vol. 2 2017
Jun 20, 2017 06:52:37 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Eye in the Sky 2015
Jun 20, 2017 06:52:18 PM	Info	
Found 0 torrentpotato releases from Arche Torrent for: Fast  Furious 8 2017`

Again if you search "Risen 2016" you get results, but nothing relevant, with "Risen" i get 7 movies.

**Comment by elliotvr** [comment]
@helmutwasa 0.7.1437.0 is less than 0.7.1467

With 1467, there is a commit than enhance search for ArcheTorrent, i just try "Risen 2016" and got 7 movies like you.

Juste update your Jackett, you may to need to check **Update to pre-release** on the main page.

**Comment by helmutwasa** [comment]
yep sorry for this, i forgot to stop / start the server :P 
Working with manual search as expected thanks

But not working with torrentpotato, i will make another ticket for this one

Thanks
