### ISSUE TITLE
ICC2022 down

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#14734]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP client: HttpWebClient
FlareSolverr
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits
```

### Description

https://www.icc2022.com/
Tracker site is not available. It is not shown tracker interface.

### Logged Error Messages

```text
Tracker is not shown.
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/2883468/e33d0f47-8230-4661-bbd6-207118eee68f)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/13898
