### ISSUE TITLE
[dontorrent] Moved to https://dontorrent.durban/

### ISSUE THREAD

**Issue by daljo25** [Jackett/Jackett#14737]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
[dontorrent] (testing) Exception (dontorrent): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>301 Moved Permanently</title></head><body><h1>Moved Permanently</h1><p>The document has moved <a href="https://dontorrent.durban/ultimos">here</a>.</p></body></html>: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>301 Moved Permanently</title></head><body><h1>Moved Permanently</h1><p>The document has moved <a href="https://dontorrent.durban/ultimos">here</a>.</p></body></html>
```

### Description

[dontorrent] (testing) Exception (dontorrent): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>301 Moved Permanently</title></head><body><h1>Moved Permanently</h1><p>The document has moved <a href="https://dontorrent.durban/ultimos">here</a>.</p></body></html>: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>301 Moved Permanently</title></head><body><h1>Moved Permanently</h1><p>The document has moved <a href="https://dontorrent.durban/ultimos">here</a>.</p></body></html>

### Logged Error Messages

```text
[dontorrent] (testing) Exception (dontorrent): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>301 Moved Permanently</title></head><body><h1>Moved Permanently</h1><p>The document has moved <a href="https://dontorrent.durban/ultimos">here</a>.</p></body></html>: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>301 Moved Permanently</title></head><body><h1>Moved Permanently</h1><p>The document has moved <a href="https://dontorrent.durban/ultimos">here</a>.</p></body></html>
```

**Comment by garfield69** [comment]
v0.21.958

**Comment by javyyk** [comment]
Hi @garfield69, now returns code 301 moved to
`https://dontorrent.party/`

**Comment by ilike2burnthing** [comment]
This change was made 5 days ago - https://github.com/Jackett/Jackett/commit/3b5824aa0174fc6667bb0b60647d03eb168bab3b

Update Jackett if you're not seeing it on your end.
