### ISSUE TITLE
retroflix missing dead result

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#14735]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using Jackett version -  Jackett Version v0.21.947  
Running in container
```

### Description

The results of a search of retroflix will be missing a torrent if that torrent is dead(no seeder). This makes cross-seeding more difficult.

The results are included in the webUI on the website and via API but only if you include includingDead=1 with the api. I can only assume that jackett is not passing include dead param as thats why its missing the dead torrents.

e.g
`curl -X GET "https://retroflix.club/api/torrent?imdbId=tt0480922&includingDead=1" -H  "accept: application/json" -H  "Authorization: <API_KEY>"`

### Logged Error Messages

```text
none
```

**Comment by garfield69** [comment]
you are correct, the speedapptracker abstract which the speedapp and retroflix indexer use, does not currently add the includedead parm.
I shall update the abstract to include it.

**Comment by swannie-eire** [comment]
@garfield69 Thanks.

I assume its the API ye are using to search or are ye scraping the site?

**Comment by garfield69** [comment]
the abstract is using the API as documented at https://speedapp.io/api/doc but given the docs are v1.0.0,  it has clearly never been updated after the inclidingDead parm was subsequently made available, as I have tested the parm just now on both indexers and can now get seed=0 results.

We've missed the Jackett release window, so this will be included in the next release does out in about 22 hours or so.

**Comment by swannie-eire** [comment]
that retroflix docs is well out of date too. I figured it out from using the private API the browser uses when searching the site.

Most of the params for uploading dont work and the staff at retro dont even know the correct params for things like description.

**Comment by garfield69** [comment]
v0.21.958
