### ISSUE TITLE
TorrentLite Public Indexer request

### ISSUE THREAD

**Issue by Mr4x3** [Jackett/Jackett#14732]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: TorrentLite 
- URL: https://TorrentLite.org 
- Description: a public tracker inspired by simplicity 
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): None 
- Additional Comments: Much Requested Feature https://lemmy.dbzer0.com/post/5232276
```

**Comment by ilike2burnthing** [comment]
Fork of https://therarbg.com/ without credit.

https://github.com/Jackett/Jackett/issues/14685

https://www.reddit.com/r/TheRarBg/comments/16w9b7c/some_pirate_content_some_pirate_a_pirate_site/
