### ISSUE TITLE
[req]: BTArg

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#14739]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: BTArg
- URL: https://www.btarg.com.ar/
- Description: BTArg is an ARGENTINIAN Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MR: 0.5
- Additional Comments: signup currently open
```

**Comment by garfield69** [comment]
v0.21.958
