### ISSUE TITLE
Shadowflow private tracker redirected to other website

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#14731]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP client: HttpWebClient
FlareSolverr
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits
```

### Description

It is redirected to this site: https://www.baobeihuijia.com/bbhj/

### Logged Error Messages

```text
Redirection to other site.
```

**Comment by garfield69** [comment]
the site is know to use camouflage, but I've asked another OP for confirmation.
Monitor #14483 for a response.
closing as a duplicate.
