### ISSUE TITLE
Trying to add Hon3yHD: Get "Exception in GetConfigForm"

### ISSUE THREAD

**Issue by desimaniac** [Jackett/Jackett#1474]
Jackett version:  Jackett Version 0.7.1483.0
Mono version (if not using Windows):  Windows OS
Log: https://gist.github.com/desimaniac/308b2610116d5d32d31a852df034a262

-------------------------------
Get error "Exception in GetConfigForm" when trying to add Hon3yHD.

**Comment by kaso17** [comment]
Is this still a problem in the latest version?

**Comment by desimaniac** [comment]
No not anymore. Sorry forgot to close.
