### ISSUE TITLE
Abnormal tracker freeleech search broken

### ISSUE THREAD

**Issue by jojofofo36** [Jackett/Jackett#14741]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-10-04 09:16:26	Info	Using HTTP Client: HttpWebClient2
2023-10-04 09:16:26	Info	Using FlareSolverr: http://192.168.1.45:8191/
2023-10-04 09:16:26	Info	Using proxy: Disabled
2023-10-04 09:16:26	Info	App config/log directory: /config/Jackett
2023-10-04 09:16:26	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-10-04 09:16:26	Info	Running in Docker: Yes (image build: v0.20.2304-ls85)
2023-10-04 09:16:26	Info	File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2023-10-04 09:16:26	Info	Jackett variant: CoreLinuxAmdx64
2023-10-04 09:16:26	Info	OS version: Unix 5.16.0.0 (64bit OS) (64bit process)
2023-10-04 09:16:26	Info	Environment version: 6.0.22 (/app/Jackett/)
2023-10-04 09:16:25	Info	Starting Jackett v0.21.958
```

### Description

abnormal search for freeleech only was working but now it doesnt find anything, it works without the freeleech option ticked

### Logged Error Messages

```text
none
```

**Comment by garfield69** [comment]
I do not have an a/c on this site, so while we wait for @ilike2burnthing to becomes available, you could possibly help me figure out what is going on if you provide an enhanced log.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket 
for the test, I would like you to set the Abnormal indexer config with the freeleech option **NOT-ticked**, and do a search for a torrent that you know has the freeleech flag (by using your browser to check on the web site first).
This way I can see what the changes are in the torrent record from the web site, and I should then be able to update the indexer.
Thanks.

**Comment by jojofofo36** [comment]
they actually have open invites right now so i could enter your email and you could have an account on the site if you want

**Comment by garfield69** [comment]
As long as the site does not have an exam or some form of mandatory attendance, downloading, or contributions, then send an invite to garfieldsixtynine -at- gmail.com .
But otherwise the choices remain: wait for ilike2burnthing or provide the log.
Thanks.

**Comment by jojofofo36** [comment]
i invited you ! i tried looking for the folder of enhanced log but i use docker from my nas i dont really know how to access it i think its easier you check for yourself on the website, the blue F logo next to torrent name is freeleech and to browse torrent just click torrent at the top left of the website

**Comment by garfield69** [comment]
the indexer appears to be working for me.
Admittedly, ATM everything is freeleech on the site that I can see, but I've tested by searching without keywords, and I can see all the torrents tagged as free, and ticking the freeleech config and repeating the search still shows free results.

is there a particular search you want me to try?

**Comment by jojofofo36** [comment]
try searching "ahsoka s01e08"

**Comment by garfield69** [comment]
yes I see what you mean, the indexer returns no results when searching for "ahsoka s01e08" with the freeleech config ticked.
however, if you use the website, and search for "ahsoka s01e08" with the freeleech box ticked, the web site does not return results.
So the problem is not the indexer, it is with the web site and there is nothing Jackett can do about it.

I see in the H&R wiki section that they have moved from v1 to v2 (but its not clear to me how long ago that was).
If they have recently upgraded to v2, then you may wish to report your finding on the site's forum or help chat or whatever.

**Comment by jojofofo36** [comment]
so weird because i can find 1 torrent for ahsoka s01e07 and 0 for episode 8 and the last update to the wiki page was a year ago

**Comment by garfield69** [comment]
clearly something is amiss at the web site. I suggest you report your findings on the [Rapports de bug](https://abn.lol/Forum/Topics?ForumId=7) forum.

**Comment by jojofofo36** [comment]
yes i will do it thank you

**Comment by ilike2burnthing** [comment]
Looks like there's global freeleech for the next few hours, so I'm assuming the 'freeleech only' search filter on the site just returns 'real freeleech' results, and not those which are freeleech only because of the global freeleech. I've seen that on a few other trackers. Check in another 3.5hrs to see if that's true.

**Comment by garfield69** [comment]
Looks like you are correct ilike2burnthing, now that the global freeleech is over, you can see that the freeleech-search shows only  true freeleech torrents.
