### ISSUE TITLE
Function "Add indexer", "Test" or "Search" similar to login to indexer?

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#14751]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP client: HttpWebClient
FlareSolverr: Yes
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits
SO: Windows 10
```

### Description

I want to know how indexer site could register my activitity using Jacking function "Adding indexer", "Test" or "Search".

As you know some indexer sites, specially private trackers register all incoming login IP connection of each user, to be exactly with IP.

Therefore, Is the function "Add indexer", "Test" or "Search" in Jackett UI same like I login to indexer? If so, the indexer site will registry my IP pinged by Jackett function. Is this correct?

### Logged Error Messages

```text
See above.
```

**Comment by ilike2burnthing** [comment]
When you add a semi-private or private indexer you're logging into it.
