### ISSUE TITLE
[req]: hdvbits

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14752]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: hdvbits
- URL: https://hdvbits.com/
- Description: hdvbits is a CHINESE Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): tbd
- Additional Comments: 
Engine: NexusPHP v1.8.4 2023-06-18
Registration open ATM
```

**Comment by garfield69** [comment]
v0.21.993

**Comment by garfield69** [comment]
https://hdvbits.com/ HTTP ERROR 500

**Comment by garfield69** [comment]
https://hdvbits.com/ cloudflare Bad gateway Error code 502

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://hdvbits.com/ - Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14752#issuecomment-1849022935 (Internal Server Error)

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14752#issuecomment-1915171446

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14752#issuecomment-1924351675

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://hdvbits.com/ redirects to https://hdvbits.com/lander domain expired landing page (expired on 2024-07-20 forgot to open ticket)

**Comment by garfield69** [comment]
v0.22.507
