### ISSUE TITLE
[exitorrent-org] (testing) Test search in exitorrent.org => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by PrzemekSkw** [Jackett/Jackett#14755]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett is working as docker on unraid server.
```

### Description

I add indexer with cookie as described in instructions and after click test it casuse issue, not find anything.
When I try in Prowlarr it sync with arr apps and test was OK but also don't search anything. Only when I try in nzb360 android app it search with Prowlarr in that indexer but don't grab to download client.

### Logged Error Messages

```text
Log file is on my server (selfhosted filebrowser) because it was too long for pastebins:
`https://serverplikowprzemka.duckdns.org/share/f5z5VIDX`
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/25219988/45499025-3428-46df-83cd-63321d0bb9a4)

![image](https://github.com/Jackett/Jackett/assets/25219988/98fb7eb4-a7e7-4bd6-bece-ca944f5214b5)

**Comment by garfield69** [comment]
v0.21.1011
