### ISSUE TITLE
Transfering added indexers from one Jackett to other Jackett?

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#14750]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP client: HttpWebClient
FlareSolverr
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits
```

### Description

I have two instances of jackett, one in my pc and other in other server of a virtual box.

My question is simple:
I want to transfer all my added indexers from my Jackett at PC to Jackett at virtual box. How can I do it? Is it possible? Exchanging API Key? If so, I cannot edit API Key into UI.

Best.

### Logged Error Messages

```text
See above.
```

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13407#issuecomment-1197532302
and
https://github.com/Jackett/Jackett/issues/13407#issuecomment-1197534091
