### ISSUE TITLE
[req]: Emmid Tracker

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#14758]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Emmid Tracker
- URL: https://emmidtracker.online/
- Description: Emmid Tracker is a BRAZILIAN Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): TBD
- Additional Comments: 
UNIT3D 6.5.0
registration currently open
```

**Comment by garfield69** [comment]
v0.21.1011

**Comment by ilike2burnthing** [comment]
My account has been banned for supposedly having multiple accounts, except I don't :/ Replying to the email bounces back as undeliverable, and the `Need help?` button in their email doesn't work.

If your account isn't also banned, can you see if you can get [REMOVED] restored? Ta.

**Comment by garfield69** [comment]
I've opened a ticket, hopefully that will get a response.

**Comment by ilike2burnthing** [comment]
And I'm back in, thanks!

**Comment by garfield69** [comment]
FYI, response from Sysop:
>Hello, the system in this case accused him of having "tapped" him, then one of my administrators saw it and banned him, but now that everything is clarified I unbanned him, ok.

**Comment by ilike2burnthing** [comment]
Oh ffs, banned again, this time:

> Possible cheater account, again with fake email and fake account. Infinite BAN

Can you message them again? Sorry. Once back in I'll open my own ticket and try and sort whatever the 'issue' is 🙄

**Comment by garfield69** [comment]
I've updated the ticket. Curious goings on. You've never had issues with other unit3d sites, I wonder why this one has it in for you %-/

**Comment by ilike2burnthing** [comment]
Thanks again. No, never. Maybe they're seeing 'test' in the email address and questioning it, but they'd be the first to do so.

**Comment by ilike2burnthing** [comment]
Any news?

Interestingly, Kaspersky have flagged the site for phishing. I've filed a false positive report, so we'll see if that changes.

**Comment by garfield69** [comment]
The sysop has not yet responded to my update that you were banned again.

**Comment by garfield69** [comment]
Its been 4 days and there has not been any updates to the ticket which was closed after the a/c reset.
You want me to open a fresh one?

**Comment by Emmid368** [comment]
Hello

**Comment by Emmid368** [comment]
I apologize for the misunderstanding, if possible join our discord so we can resolve this! https://discord.gg/SGY5rYCQNG

**Comment by ilike2burnthing** [comment]
It has since been resolved, thanks.

**Comment by garfield69** [comment]
https://emmidtracker.online/ Error 503: Service Unavailable!

after they updated to 7.0.0 access via api key (and thus the indexer) was working fine, however browser access using the logout and login links was not working because a simple icon link with http was causing https access to be flagged unsecure ;-D hopefully they will sort this out soon enough.

**Comment by garfield69** [comment]
back online as far as API is concerned,  however login page still generates a captcha error and the form is still generates console messages on chrome 118:
```
Mixed Content: The page at 'https://emmidtracker.online/login' was loaded over HTTPS, but requested an insecure element 'http://emmidtracker.online/img/icon.svg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
17:45:04.509 login:1 Mixed Content: The page at 'https://emmidtracker.online/login' was loaded over HTTPS, but requested an insecure favicon 'http://emmidtracker.online/favicon.ico'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by garfield69** [comment]
https://emmidtracker.online/ Error 503: Service Unavailable!

**Comment by garfield69** [comment]
v0.21.1076
