### ISSUE TITLE
TorrentDay Indexer

### ISSUE THREAD

**Issue by Gothamen** [Jackett/Jackett#1476]
Hi all, apologies I am not as technical as I would like when it comes to creating the TorrentDay Indexer or diagnosing the issue but I assume, based on several forums that this potentially has to do with a Recapture incompatibility or similar.

Requirement: Attempting to add the pre-defined TorrentDay indexer to Jackett 0.7.1483.0.
Site Link: https://www.torrentday.com/ (have attempted variants and similar results are received).
Error: Configuration Failed: Got a redirect to https://www.torrentday.com/t, please adjust your the alternative link.
Log has no entry at this point.

2nd Attempt: Retried with Site Link: https://www.torrentday.com/t
Error: Configuration Failed: Got a redirect to https://www.torrentday.com/login.php, please adjust your the alternative link.
Log has no entry at this point.

3rd Attempt: Retried with Site Link: https://www.torrentday.com/login.php
Error: Configuration Failed: Need urgent help?Click here to join our live irc Help channel.
Log has no entry at this point.

Some alternative methods suggested to try the:
4th Attempt: Site Link: https://classic.torrentday.com/
Error: 
![image](https://user-images.githubusercontent.com/29479083/27221025-725098ee-52ca-11e7-8d99-7d696bdfdd4f.png)
Log has no entry at this point.

Anyone have any thoughts on a workaround other than the RSS feed?

Cheers,
Gothamen.

**Comment by Gothamen** [comment]
> I was having the same issue as you are and saw your post when i was tring to fix myself.

What I found if I enabled external access in Jackett, then opened in my browser using the HOSTNAME of the machine (not localhost or 127.0.0.1), then when I went to add TD it asked for the Cookie, once I added that it all started working!

You are a legend, thank you for the quick and easy response!

**Comment by kaso17** [comment]
22cf450d07d9523c838df4a0ec8415dd3dec7f87 contains the proper fix

**Comment by FSurani** [comment]
I still was not able to login on TorrentDay with the latest release on windows. Had to apply this work around.

**Comment by Gothamen** [comment]
Noted thanks @kaso17 & @FSurani, trying this now.

**Comment by Gothamen** [comment]
Sorry I am very basic when it comes to this, uninstalled & re-installed and seems fine, issue is that the login may de-authenticate, for future reference, would you mind confirming how I would apply this as a work around? I assumed I would find and be able to update the file mentioned but can't see it?

Windows OS.

Cheers.

**Comment by kaso17** [comment]
@FSurani can you post an updated log?

**Comment by Gothamen** [comment]
To update, issue still occurs on new version, I am running Jackett with Sonarr and know this is not the Sonarr Git but that is how I am seeing the auth failure.

Let me know if I can provide anything to assist with identification of the error.

**Comment by kaso17** [comment]
@Gothamen a updated log with enhanced logging enabled would be helpfull

**Comment by Gothamen** [comment]
@kaso17 have enable enhanced logging, in the mean time this is the Sonarr error, again I know this isn't a Sonarr post but it may help decipher a potential disconnect?

> Details
> Message
> NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to uTorrent, please check your settings ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [GET] at [http://localhost:55424/gui/token.html]
>    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 106
>    at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, UTorrentSettings settings, Boolean reauthenticate) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 227
>    --- End of inner exception stack trace ---
>    at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, UTorrentSettings settings, Boolean reauthenticate) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 243
>    at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, UTorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 176
>    at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.GetTorrents(String cacheID, UTorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 81
>    at NzbDrone.Core.Download.Clients.UTorrent.UTorrent.GetItems() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrent.cs:line 82: Unable to connect to uTorrent, please check your settings
> 
> Exception
> NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to uTorrent, please check your settings ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [GET] at [http://localhost:55424/gui/token.html]
>    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 106
>    at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, UTorrentSettings settings, Boolean reauthenticate) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 227
>    --- End of inner exception stack trace ---
>    at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, UTorrentSettings settings, Boolean reauthenticate) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 243
>    at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, UTorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 176
>    at NzbDrone.Core.Download.Clients.UTorrent.UTorrentProxy.GetTorrents(String cacheID, UTorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrentProxy.cs:line 81
>    at NzbDrone.Core.Download.Clients.UTorrent.UTorrent.GetItems() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\uTorrent\UTorrent.cs:line 82
> Close

**Comment by lsaadeh1** [comment]
Does @kaso17 fix apply to torrentday.com? or just torrentday.it?
Im struggling to connect to torrentday.com which has more search results then torrentday.it

**Comment by kaso17** [comment]
@Gothamen according to th exception it looks more like an issue with the UTorrent/Sonarr connection.
@lsaadeh1 https://www.torrentday.com/ is working fine for me, please post an enhanced log

**Comment by lsaadeh1** [comment]
@kaso17 the logs generated in /opt/jackett are 4k+ lines longs, are these the logs you are after?
Also just because I think I might be adding torrentday.com incorrectly I'll tell you what I've done.
Currently I've got into the torrentday.json file and replace torrentday.it > torrentday.com.. is this correct?

**Comment by lsaadeh1** [comment]
For those who come across this looking for a solution. I got it to work for me by changing torrentday.it > https://www.torrentday.com/browse.php/ within  ~/.config/Jackett/Indexers/torrentday.json (remember to stop the service before you make changes) and then using the cookie which is on the site https://www.torrentday.com/browse.php/ (not https://www.torrentday.com/ as I was doing before)
