### ISSUE TITLE
totallykids.tv down

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#14765]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP client: HttpWebClient
FlareSolverr
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits
```

### Description

Site is down. 

### Logged Error Messages

```text
I checked in some countries where website is available (https://www.uptrends.com/) but site still down.
```

**Comment by garfield69** [comment]
The indexer is working for me and all 43 uptime checkpoints show online.
If you have a problem with the indexer then provide an **enhanced** log so we can take a look.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by AARON8888** [comment]
Now, site is opened well in many countries. Disregard my issue, you can close it. Sorry.
