### ISSUE TITLE
Tracker domain on sale: torrent-syndikat.org 

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#14763]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: yes
Using proxy: Enable
Running in Docker: No
Starting Jackett: v0.21.1017
```

### Description

Tracker domain on sale: torrent-syndikat.org 

### Logged Error Messages

```text
See above
```

**Comment by ilike2burnthing** [comment]
Nope - https://github.com/Jackett/Jackett/issues/9543#issuecomment-1228890188
