### ISSUE TITLE
MirCREW missing details (File dimensions & seed/peers)

### ISSUE THREAD

**Issue by wes1993** [Jackett/Jackett#14775]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett startup finished in 9.490 s
Adding filter indexer ('tag:ilcorsaroblu' indexer) ...
Adding filter indexer ('tag:therarbg' indexer) ...
Adding filter indexer ('tag:mircrew' indexer) ...
Adding filter indexer ('tag:ilcorsaronero' indexer) ...
Adding filter indexer ('tag:arabafenice' indexer) ...
Adding filter indexer ('tag:ildragonero' indexer) ...
Adding filter indexer ('tag:girotorrent' indexer) ...
Adding filter indexer ('tag:itatorrents' indexer) ...
Adding filter indexer ('type:semi-public' indexer) ...
Adding filter indexer ('type:private' indexer) ...
Adding filter indexer ('type:public' indexer) ...
Adding aggregate indexer ('all' indexer) ...
Loaded 595 indexers in total
Loaded 521 Cardigann indexers.
Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
Loaded 74 Native indexers.
Loading Native indexers ...
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.0.26:8191
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.993-ls185)
File /etc/issue: Welcome to Alpine Linux 3.18
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.2.16.15 (64bit OS) (64bit process)
Environment version: 6.0.22 (/app/Jackett/)
Starting Jackett v0.21.993
```

### Description

Do a search using this indexers.

Jackett cannot read the File Dimensions and seed/peer

### Logged Error Messages

```text
No error Message
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/52070589/d2a2ae22-17f4-4196-9488-447f96d9ad39)
The details inside the website
![image](https://github.com/Jackett/Jackett/assets/52070589/3d42ddd0-8adb-4dff-9262-69a1d6123120)

**Comment by ilike2burnthing** [comment]
That information is only on the release details page, not the search results page, so short of making 25 additional requests for every search (which we're not going to do, and would get accounts quickly banned), Jackett has no way of getting that information.

**Comment by wes1993** [comment]
@ilike2burnthing Ok thanks a lot i hope in the website search update so we can have this info :-D

**Comment by ilike2burnthing** [comment]
So long as it remains a forum-style tracker based on phpBB, it won't be available.
