### ISSUE TITLE
[req]: DreamingTree

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#14789]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: DreamingTree
- URL: https://dreamingtree.org/
- Description: DreamingTree is a Semi-Private Torrent Tracker for DAVE MATHEWS MUSIC / BOOTLEGS
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MST 72hrs, MR 0.6
- Additional Comments:
```

**Comment by garfield69** [comment]
v0.21.1073

**Comment by garfield69** [comment]
https://dreamingtree.org/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14789#issuecomment-2073075120

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14789#issuecomment-2073075120

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14789#issuecomment-2073075120

**Comment by garfield69** [comment]
online
