### ISSUE TITLE
Time delay btw torrent posted in yggtorrent and visible in rss

### ISSUE THREAD

**Issue by Jizzlord** [Jackett/Jackett#14792]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://172.17.0.1:15061
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.1073-ls197)
File /etc/issue: Welcome to Alpine Linux 3.18
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.10.0.0 (64bit OS) (64bit process)
Environment version: 6.0.23 (/app/Jackett/)
Starting Jackett v0.21.1073
```

### Description

Hello

I am using Jackett RSS feed in qbittorrent, and I have noticed a delay btw the torrent published in Yggtorrent and its appearance in the RSS feed, from 30 minutes up to 2 hours sometimes. RSS feed are updating automatically every 5 minutes in qbittorrent.

I tried with or without "Cache enabled" and haven't seen any difference.
Is ther anything to do/check to solve this issue?

### Logged Error Messages

```text
No error message in the log
```

**Comment by ilike2burnthing** [comment]
If the cache is disabled (you have unticked `Cache enabled (recommend)`, clicked `Apply server settings`, and waited for the page to reload), then what you see on the site in browser and what you see in Jackett's results will be the same.

What are you using as your RSS feed URL in qBittorrent?

**Comment by Jizzlord** [comment]
![YGG](https://github.com/Jackett/Jackett/assets/148698157/6439aa7c-8af0-406c-834d-dfd9eb89c2b6)
![qbittorrent](https://github.com/Jackett/Jackett/assets/148698157/bb5a2e28-c773-4267-94c2-fabd203f5d33)

Two screen shot at the same time, the last visible torrent in qb is 58 minutes old, the most recent are not shown, using the feed:

I am using the feed from "Copy RSS feed"

**Comment by Jizzlord** [comment]
![settings](https://github.com/Jackett/Jackett/assets/148698157/e1be15cd-0546-41a7-9bbc-c2a54a83abb9)

**Comment by Jizzlord** [comment]
That's weird: "The Fox" just appeared in qb, exactly an hour after being published

**Comment by ilike2burnthing** [comment]
From your screenshot you appear to be looking at - https://www3.yggtorrent.wtf/top/day

Jackett however is using the search page - https://www3.yggtorrent.wtf/engine/search?do=search

I'm seeing results from a few minutes ago on the first link, but not the second. This seems to be an issue with the site and would need to be brought up with them.

**Comment by Jizzlord** [comment]
You are right! thanks for the support
