### ISSUE TITLE
[global search engine] Search by full move name fails. While partial name is ok.

### ISSUE THREAD

**Issue by vasilky3** [Jackett/Jackett#14794]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/osmc/.config/Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: OSMC: Open Source Media Center \n \l
Jackett variant: CoreLinuxArm32
OS version: Unix 4.9.269.33
Environment version: 6.0.23 (/opt/Jackett/)
Starting Jackett v0.21.1073
```

### Description

Steps to reproduce:
1. Get the move title from https://www.imdb.com/title/tt1675434/
2. Search for The Intouchables 2011 via ui/api

Expected:
Got list of torrents corresponding to move:
![image](https://github.com/Jackett/Jackett/assets/43271561/bd876713-4c3b-4155-bd29-f3d66c42fbcc)

Got:
Seems like only `The` is proceeded by query:
![image](https://github.com/Jackett/Jackett/assets/43271561/4385189f-2834-45a7-b8fb-a8983479279a)

### Logged Error Messages

```text
the case is easy to reproducer. I will provide log if needed
```

**Comment by garfield69** [comment]
not entirely sure what expect from jackett.
none of the sites you searched have a torrent with the full name `the Intouchables`
rutracker, megapeer, kinozal and rutor have torrents with `Intouchables` in the name and these were found.

Jackett can only return results that are available at the site.
If you believe a web site has results with the title you are looking for, and Jackett is not returning them, show me the web site search and we can look deeper.

**Comment by vasilky3** [comment]
So jackett searches by whole string and doesn't count partial matches? 
Considering you reply i should see no results for `the Intouchables`?
But i got results with `the`. is it ok?

**Comment by garfield69** [comment]
Jackett simply sends the whole string to the web sites, and its up to the web sites to perform the search.
So it all depends on the web sites search engines.
Some sites perform a sequential AND, for example, matching `the sky is blue` but not `the blue sky`.
Others perform an regular AND on the keywords and these return the best results.
But some sites perform an OR on the keywords, and we often make the indexer apply an post search ANDmatch to remove hits that are partial.

In this case lostfilm is the one that is picking up the keyword `the` and returning spurious results, and I will check if we can add a post results ANDmatch to filter out the false hits.

But that is the only indexer in that set you we using that is returning rubbish, the rest all do not have the keyword `the` in their torrent names and thus do not return any results when you include it in the search request.

**Comment by vasilky3** [comment]
Now i see, the engine is on the tracker side. 
Thx for 'original title' field will try to use it.
