### ISSUE TITLE
Season and Ep variables from Sonarr cause failure on search

### ISSUE THREAD

**Issue by stephbairey** [Jackett/Jackett#1479]
Sonarr can't search TPB because it's adding variables I don't think TMB has.

For example: when searching for The Rachel Maddow Show as a daily show (not seasons), sonarr loads this URL:

http://127.0.0.1:9117/torznab/thepiratebay/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Rachel%20Maddow%20Show&season=2017&ep=06/14

It returns no results. If I remove "&season=2017&ep=06/14" it finds all shows. I am, of course, using the correct api, just removing it here.

If I change the show to Seasons (not daily) it searches for:

http://127.0.0.1:9117/torznab/thepiratebay/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Rachel%20Maddow%20Show&season=2017&ep=117

Again, it returns nothing unless I remove "&season=2017&ep=117".

Sonarr folks say this is a problem in how Jackett decides to send the data. This does work:

http://127.0.0.1:9117/torznab/thepiratebay/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Rachel%20Maddow%20Show%202017%206%2014

Torrent that should be found in this example: 

https://thepiratebay.org/torrent/17935080/The.Rachel.Maddow.Show.2017.06.14.540p.WEBDL-Anon.mp4

Jackett version:  0.7.1483.0
Mono version (if not using Windows):  nope, win10

Log doesn't seem to have much info, here's me trying the 2 examples above:

When	Level	Message
Jun 16, 2017 12:43:54 PM	Info	
Found 0 releases from The Pirate Bay for: Rachel Maddow Show 2017.06.14
Jun 16, 2017 12:43:51 PM	Info	
Found 0 releases from The Pirate Bay for: Rachel Maddow Show 2017.06.14

-------------------------------

**Comment by kaso17** [comment]
Change the sonarr categories to just 5000 instead of 5030,5040 (you've to enable advanced options for it) and it should work:
http://127.0.0.1:9117/torznab/thepiratebay/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&q=Rachel%20Maddow%20Show&season=2017&ep=06/14
