### ISSUE TITLE
[req]: ultrahd.online

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14793]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: ULTRA HD
- URL: https://ultrahd.online/
- Description: ULTRA HD is a BRAZILIAN Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): tbd
- Additional Comments: 
not to be confused with ultraHD a Chinese private site.
Engine: unit3d 7.0.0
registrations open ATM
```

**Comment by garfield69** [comment]
v0.21.1076

**Comment by ilike2burnthing** [comment]
https://ultrahd.online/ - Web server is down Error code 521

**Comment by ilike2burnthing** [comment]
@Emmid368 has the tracker closed or moved?

**Comment by garfield69** [comment]
v0.21.1310
