### ISSUE TITLE
[yggtorrent] (updating) Login failed: No form found on https://yggtorrent.wtf/ using form selector #user-login

### ISSUE THREAD

**Issue by xavierosef** [Jackett/Jackett#14807]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HttpWebClient => Jackett Version v0.20.3756
```

### Description

Using new YGG domain and getting this error (form with id "user-login" still exists)

### Logged Error Messages

```text
An error occurred while updating this indexer
Login failed: No form found on https://yggtorrent.wtf/ using form selector #user-login
Click here to open an issue on GitHub for this indexer.
```

**Comment by ilike2burnthing** [comment]
Change it back to https://www3.yggtorrent.wtf/

**Comment by garfield69** [comment]
site appears unstable for me ATM, I'm seeing 
- 500 Internal Server Error intermittently 
as well as 
- cloudflare Web server is returning an unknown error Error code 520 

Best to wait and try again later in the day.
