### ISSUE TITLE
Test search in Classix => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#14805]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: yes
Using proxy: Enable
Running in Docker: No
Starting Jackett: v0.21.1106
```

### Description

I can add indexer and search without any problem.
The issue is when I click "Test".

### Logged Error Messages

```text
See attached "Full log" after clicking "Test".
```
[Full log.txt](https://github.com/Jackett/Jackett/files/13209475/Full.log.txt)

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/2883468/11d75f84-395e-4ebe-a1ac-b01b5d92eec3)

**Comment by ilike2burnthing** [comment]
Have you changed an account setting which would affect the format of the date?

The indexer is expecting `26-10-2023` (day-month-year) but you're getting `10-26-2023` (month-day-year).

**Comment by AARON8888** [comment]
In my account setting in tracker I think I have US format date and I cannot change. Maybe you need to change this indexer to US format?

**Comment by garfield69** [comment]
@AARON8888 
There are 3 themes on classix, **Default**, **NB-41** and **white**.
You are currently using NB-41
As a test please switch to the **Default** theme and see if the indexer works and let us know the result.
You might as well test white too just in case.
Thanks.

**Comment by AARON8888** [comment]
@garfield69 
Thanks for notice. Anyhow I tested all themes and problem remain same.
I have some invites in my account. I can send you one just to test by your own, no problem. How I can contact with you?

**Comment by garfield69** [comment]
@ilike2burnthing  you want this one?

**Comment by ilike2burnthing** [comment]
Sure.

jacketttest [AT] gmail [DOT] com

**Comment by AARON8888** [comment]
Many thanks. Now working. :)

**Comment by ilike2burnthing** [comment]
[v0.21.1124](https://github.com/Jackett/Jackett/releases/v0.21.1124)
