### ISSUE TITLE
[req]: Twisted-Music

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#14815]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Twisted-Music
- URL: https://twisted-music.org/
- Description: Twisted-Music is a Private Torrent Tracker for MUSIC / AUDIO SOFTWARE
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MST 24h, MR 0.5
- Additional Comments: 
 TS Special Edition v.8.0
Invitation only ATM
```

**Comment by garfield69** [comment]
um, did they change the name while you were not looking, the site seems to be called twisted-music ?

**Comment by ilike2burnthing** [comment]
Whoops, just me being distracted doing other things at the same time :P

**Comment by garfield69** [comment]
v0.21.1128

**Comment by garfield69** [comment]
looks like twisted-music have ditched unit3d and gone for TS Special Edition v.8.0
However registration is disabled and my unit3d creds are not recognised (unsurprisingly).

**Comment by garfield69** [comment]
v0.21.1250

**Comment by garfield69** [comment]
registration open ATM, I'll code up a tssev8 indexer shortly

**Comment by garfield69** [comment]
bah. even though I was auto-logged in after registering, the moment I clicked read mail I got
```
You do not have permission to access this page. This could be because of one of the following reasons:
Your account has either been suspended or you have been banned from accessing this resource.
You do not have permission to access this page. Are you trying to access administrative pages or a resource that you shouldn't be? Check in the tracker rules that you are allowed to perform this action.
Your account may still be awaiting activation or moderation.
Feel free to contact us about this error message.
```
and when I went to login my credentials were rejected.
someone else can code an indexer for this site.

**Comment by ilike2burnthing** [comment]
Same. Was able to browse the site signed in, went away for a few minutes, came back and was no long signed in and credentials were no longer recognised. Guessing they haven't figured out how to disabled signups and are just deleting accounts for now.

Oddly though https://twisted-music.info/browse.php is accessible without having to login, just can't download obviously.

**Comment by garfield69** [comment]
v0.21.1298

**Comment by ilike2burnthing** [comment]
https://twisted-music.info/ - 504 Gateway Time-out

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://twisted-music.org redirects to https://twisted-music.org/ts_error.php?errorid=5
I did get an email about the domain this morning but I lost it :-( maybe they changed again?

**Comment by ilike2burnthing** [comment]
I'm getting a mix of timeouts, connection refused, and this redirect.

The email this morning was, rather ironically:

> sorry for the downtime
we are back

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14815#issuecomment-1890611638

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://twisted-music.info/ ERROR_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://twisted-music.org/ - ERR_CONNECTION_RESET

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://twisted-music.org/ DNS_PROBE_FINISHED_NXDOMAIN (DNS Lookup Error)

**Comment by ilike2burnthing** [comment]
Dead?

**Comment by garfield69** [comment]
yes

**Comment by garfield69** [comment]
v0.21.1915
