### ISSUE TITLE
[req]: Torrent Trader

### ISSUE THREAD

**Issue by Mayflower7482** [Jackett/Jackett#14811]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Torrent Trader
- URL: https://the-torrent-trader.com.
- Description: Torrent Trader is a GERMAN Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MST 48hrs, MR 0.7
- Additional Comments: 
Engine: TBD (in style of coastalcrew et al)
Registration is closed ATM, but application is open (mine was rejected)
```

**Comment by ilike2burnthing** [comment]
My application was rejected. If you can send an invite to jacketttest [AT] gmail [DOT] com I can create an indexer for this tracker.

**Comment by garfield69** [comment]
v0.21.1138
