### ISSUE TITLE
Awesome-HD uses combined stats

### ISSUE THREAD

**Issue by diksm8** [Jackett/Jackett#1481]
When manually searching for torrents on Awesome-HD it shows the combined stats and the max download size instead of showing each upload.
Jackett Version 0.7.1483.0

**Comment by kaso17** [comment]
@adamwinn can you help with this?

**Comment by adamwinn** [comment]
No, not really.  I tried all I could to make AHD work but it's outside my skillset or it needs to be re-written in C# as an indexer and not a definition.  I released it knowing there were some issues but it was the best I knew how.  Someone else can probably look at it and clean it up and improve it.

**Comment by RoloSoze** [comment]
@ngosang

**Comment by garfield69** [comment]
Jackett 0.14.326
