### ISSUE TITLE
[tornado] (updating) The SSL connection could not be established, see inner exception.: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.

### ISSUE THREAD

**Issue by hon4** [Jackett/Jackett#14810]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Proxy: no
Docker: no
Running on: Windows 7 x64 6.1 (build 7601)
Jackett: Version v0.21.1056
```

### Description

Proxy: no
Docker: no
Running on: Windows 7 x64 6.1 (build 7601)
Jackett: Version v0.21.1056

An error occurred while updating this indexer
The SSL connection could not be established, see inner exception.: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.

### Logged Error Messages

```text
An error occurred while updating this indexer
The SSL connection could not be established, see inner exception.: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
```

**Comment by ilike2burnthing** [comment]
Most likely a Windows 7 issue and you'd need to update your OS to Windows 10/11 to resolve the issue.

To confirm, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
