### ISSUE TITLE
[req]: HD-CLUB

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#14827]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: HD-CLUB
- URL: https://freecztorrent.eu/
- Description: HD-CLUB is a CZECH Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): No
- Additional Comments: xbtit 2.3.1
```

**Comment by garfield69** [comment]
v0.21.1172

**Comment by garfield69** [comment]
I'm getting 403 Forbidden Unauthorized IP address.
Just me?

**Comment by ilike2burnthing** [comment]
That's what I was getting when my IP was banned.
I can see that your account still exists, so I'll send them a message to see what's happened. I take it you didn't use a proxy/VPN?

**Comment by garfield69** [comment]
Don't normally use a proxy/vpn, except when I'm testing Jackett indexers for some sites that need it, hideme french server for cpasbien, and proton netherlands server for helltorrents and kinorun, and occasionally I forget to turn them off before moving to testing the other 432 indexers ;-)

**Comment by ilike2burnthing** [comment]
If your IP is unbanned, I noticed what I think are freeleech and 50% icons for torrents, but wasn't able to add them before being banned again 🙄

**Comment by garfield69** [comment]
Nope, I am still blocked, so if anyone wants us to make updates to the indexer they will have to provide a HTML dump of the torrents page.

**Comment by AARON8888** [comment]
> Nope, I am still blocked, so if anyone wants us to make updates to the indexer they will have to provide a HTML dump of the torrents page.

I suggest you to sign up again. Registry is still opened. Try to use static and non shared IP (home connection, private proxy ...), or second/non common subnet of normal VPN city.

**Comment by ilike2burnthing** [comment]
I've signed up multiple times, had a very weird conversation with the owner about the name of my ISP, and was banned repeatedly for nothing. I'm not entirely sure they know what they're doing, and are apparently incapable of googling. We won't be wasting any more time on them.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by garfield69** [comment]
https://freecztorrent.eu/ ERR_CONNECTION_RESET

**Comment by garfield69** [comment]
online

**Comment by AARON8888** [comment]
https://freecztorrent.eu/ - `Web is not working` then redirects to nasa.gov

**Comment by ilike2burnthing** [comment]
Login page back up, but I don't have an account to check if it's actually working.

Sign ups are closed, so this is a private tracker instead of semi-private.

**Comment by garfield69** [comment]
v0.21.1536

**Comment by ilike2burnthing** [comment]
@AARON8888 are you able to access your account? Is the indexer working in Jackett without any errors?

**Comment by AARON8888** [comment]
Yes, I can access without any problem. Also I can search too. 
You can withdraw from label: [Down / Waiting for removal]

**Comment by garfield69** [comment]
site has added a security check powered by WEDOS.protection that can generate a challenge
I will try using the cookie method to see if the indexer can be made to work again

**Comment by garfield69** [comment]
Bah. even with cookie + UA I cant get it to work.

**Comment by garfield69** [comment]
@HZY-Charlotter is the indexer working for you?

**Comment by ilike2burnthing** [comment]
So long as I'm using a CZ VPN server it's working ok for me in Jackett and browser. Maybe the IP you have has been flagged?

**Comment by garfield69** [comment]
I'm using Urban VPN. 
OK, if its working for you, I'll  just drop the indexer from my personal Jackett and leave it to you to periodically check it ;-)
One less indexer for me to check daily ;-b

**Comment by ilike2burnthing** [comment]
Just got this email:

> Your account has been suspended due to inactivity! Or other rule violation or an attempt to connect to an unauthorized program (@) has been detected

Given I successfully accessed the site last night through Jackett, I'm guessing it's the latter. Don't suppose you're able to access the site in browser again, see if there's some announcement or rule I missed?

**Comment by garfield69** [comment]
Can't find the rules page, but there is nothing in FAQ or FORUM that's new.
FAQ states minimum login every 60 days, so using Jackett may not count if the indexer has not had to login to access the torrents page.
I can access the web site via VPN urban czechia but the indexer returns unauthorized so I cant test the indexer.

**Comment by garfield69** [comment]
following up on my indexer not working, it fails because during login the indexer gets
```
WEDOS.protection – security verification required
WEDOS.protection has detected unusual activity from your browser.
To access this website, please complete the security challenge below.
```
which i do not get when I use the browser.
I may try using cookie to see if i get past it and then go back to regular to see if it continues to work.

**Comment by garfield69** [comment]
nah, using cookie + UA does not get around my issue :-(
