### ISSUE TITLE
[req]: Universal-Torrents

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#14836]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Universal-Torrents
- URL: https://uni-track.org/
- Description: Universal-Torrents is a GERMAN Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MR 1.0, MST 42hrs
- Additional Comments:
engine 3xT
Signups currently open
```

**Comment by ilike2burnthing** [comment]
[v0.21.1189](https://github.com/Jackett/Jackett/releases/v0.21.1189)

**Comment by ilike2burnthing** [comment]
Thanks, fixed. Will be available in the next release in ~20hrs.

**Comment by garfield69** [comment]
v0.21.1621

**Comment by garfield69** [comment]
https://uni-track.org/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.21.2526
