### ISSUE TITLE
[req]: BiatchTorrents

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14830]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: BiatchTorrents
- URL: https://biat.ch/
- Description: BiatchTorrents is a FRENCH Public torrent site for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments:
```

**Comment by garfield69** [comment]
v0.21.1172

**Comment by garfield69** [comment]
https://biat.ch/ ERR_CONNECTION_REFUSED

**Comment by locobastos** [comment]
Biat.ch is down, probably for ever.
All DNS was redirected to 127.0.0.1 few days ago and now are deleted: https://www.gdnspc.com/#A&biat.ch

**Comment by ilike2burnthing** [comment]
> probably for ever

Do you have information from them you can share, or are you just concluding this from the site currently being inaccessible?

**Comment by garfield69** [comment]
@ketsapiwiq do you have any info on the status of biachTorrents, is the site gone, just broken, or moved to a new domain?

**Comment by ketsapiwiq** [comment]
Hi!
No info, I gotta say I realized it's actually a mirror to the other French torrent yggtorrent that recently changed its domain name, and the person behind biat.ch might have not updated this.
I tried contacting who I think can be the owner but no answer.

**Comment by garfield69** [comment]
v0.21.1310
