### ISSUE TITLE
[scenetime] (updating) Your cookie did not work: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.

### ISSUE THREAD

**Issue by GBrayJ** [Jackett/Jackett#14831]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://10.0.0.201:8191
Using proxy: Disabled	
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.1128-ls210)
File /etc/issue: Welcome to Alpine Linux 3.18
Jackett variant: CoreLinuxMuslAmdx64	
OS version: Unix 5.15.0.88 (64bit OS) (64bit process)
Environment version: 6.0.24 (/app/Jackett/)	
Starting Jackett v0.21.1155
```

### Description

I copied my cookie from SceneTime, from an 'index.php' request. I also logged out and re logged in to create a new cookie, which also didn't work in Jackett. All other trackers work fine. 

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (scenetime): The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.

[v0.21.1155.0] Jackett.Common.IndexerException: Exception (scenetime): The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
 ---> System.Exception: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
   at Jackett.Common.Indexers.SceneTime.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/SceneTime.cs:line 156
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 339
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 357
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 733
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 319
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
resolved by c9c131e0dba1892b3d5c738f8e68b82a365c49c0 about 6 hours ago.
the fix will go out in the next jackett release due out in about 4 hours or so

**Comment by AARON8888** [comment]
I tested but not working cookie with this environment. Can you have a look again?

Using HTTP Client: HttpWebClient2
Using FlareSolverr: yes
Using proxy: Enable
Running in Docker: No
Starting Jackett: v0.21.1172

---
Attached full log: (I hide personal data with "xxx").
[Full log.txt](https://github.com/Jackett/Jackett/files/13300364/Full.log.txt)

**Comment by ilike2burnthing** [comment]
Are you pulling the cookie using the exact same proxy server as Jackett is using?

**Comment by AARON8888** [comment]
No, I use my own proxy set in UI Jackett and then copypaste the cookie is appeared in headers.
![image](https://github.com/Jackett/Jackett/assets/2883468/8f8f3ddb-937f-4f00-884a-876ed2a4c0f0)

**Comment by falcontx** [comment]
Not working for me, either, even after update. All other trackers work fine.

**Comment by GBrayJ** [comment]
Not working after update, even after adding user agent to Jackett. Cookie is correct, as well as user agent. All other trackers continue to work as intended.

**Comment by ilike2burnthing** [comment]
Working in Windows with a cookie taken from Windows or Docker. Not working in Docker with a cookie taken from Windows or Docker.

**Comment by falcontx** [comment]
I'm running in Windows with a cookie from Windows/Chrome and it is not working.

**Comment by ilike2burnthing** [comment]
Assuming you're adding the user-agent as well, follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work

**Comment by falcontx** [comment]
Correct. All steps were followed.

**Comment by AARON8888** [comment]
Me too, all steps were followed.
@ilike2burnthing, I think you can sign up (registry is opened) and test it to find a solution.

**Comment by ilike2burnthing** [comment]
I already have an account, hence being able to make this comment - https://github.com/Jackett/Jackett/issues/14831#issuecomment-1802813955

**Comment by AARON8888** [comment]
I updated my browser Chrome to last version and still not working.
I run Windows 10.
You said: "Working in Windows with a cookie taken from Windows". 
Windows 10 and Chrome too?

**Comment by ilike2burnthing** [comment]
Chrome, Edge, Firefox, all working. IPv6 is disabled, no proxies or VPNs used, same public IP for FlareSolverr and Jackett.

Remove the indexer from Jackett, restart the Jackett service, disable any proxies or VPNs on the system or in Jackett's settings, open a private/incognito browser window with no extensions enabled, sign in to SceneTime, navigate to the homepage and back to the browse page, then pull a new cookie and UA for the indexer.

**Comment by ilike2burnthing** [comment]
Got it working on Docker as well now, and it seems the issue wasn't that Windows was working and Docker wasn't, but rather that Windows was a fresh install. Follow the instructions in the above comment and it should work (for Docker, restart the container instead of the service).

**Comment by falcontx** [comment]
None of that mattered. Had to change the "Site Link" setting to "http://tracker.scenetime.com/".

**Comment by ilike2burnthing** [comment]
Did you try the above?

There's no Cloudflare challenge for `tracker.*`, so you're just bypassing the issue, and using an unencrypted site in the process.

**Comment by falcontx** [comment]
Yes, I tried the above and it didn't work. Then I tried changing the URL and it worked.

**Comment by AARON8888** [comment]
I tested also your advices ([https://github.com/Jackett/Jackett/issues/14831#issuecomment-1802966031] except:
- to disable my proxy, I don´t want to log in to site with home IP, it is risky for me to avoid any banned suprise.
- to disable IPv6 (never I tried and I don´t know well how to do it). Is is really necessary for this issue?

---
- "same public IP for FlareSolverr and Jackett". I don´t understand well this point. I use for Jackett URL: http://127.0.0.1:9117/) and for FlareSolverr API URL: http://127.0.0.1:8191, and both of them should be through with my proxy IP which is in Jackett server settings.

---
On the other hand, just to provide you further ideas in this issue, I realised that if you put in the site link in Jackett "configure" section an id of a movie (i.e. https://www.scenetime.com/details.php?id=3764998/), never mind what cookie you select in "configure", you can choose any cookie available. Cloudflare is not running and indexer works fine although only for this id search logically, not valid for general search.

**Comment by ilike2burnthing** [comment]
https://www.google.com/search?q=windows+disable+ipv6

Public IP, not local. If they're both using the same VPN/proxy server then they have the same public IP address.

Using a specific result URL for the sitelink breaks the search. As mentioned above, using alternative sitelinks is bypassing the issue, but with negative consequences.

**Comment by AARON8888** [comment]
I disable IPv6 in my internet adapter but the problem remains.

**Comment by AARON8888** [comment]
My proxy server is not only set in Jackett´s UI but also in my LAN connection. Therefore I guess FlareSolverr is using my proxy server too, but I cannot verify. Or maybe I can???

**Comment by ilike2burnthing** [comment]
Then remove it from Jackett's settings. If you won't remove the proxy completely, then try other servers in different locations.

**Comment by ortizdr** [comment]
I am running Jackett on Windows. I deleted the "SceneTime.json" file and the .bak file. Restarted Jackett and entered the settings. Viola! Working like a champ!

**Comment by ilike2burnthing** [comment]
Basically https://github.com/Jackett/Jackett/issues/14831#issuecomment-1802966031. Glad it's working for some.

**Comment by AARON8888** [comment]
What is the right site link to be entered the settings?

https://www.scenetime.com/login.php
or
https://www.scenetime.com/

or any of them could be valid?

**Comment by ilike2burnthing** [comment]
https://www.scenetime.com/

**Comment by garfield69** [comment]
I recently have not been able to get the website to accept my indexer's copy of my win10 browser cookie and UA, the site invokes a cloudflare session check which invalidates the cookie. Just me?

**Comment by michiel2304** [comment]
I think i have flaresolverr added to jackett. Not sure if it was necessarily required for this tracker but it might help if that is your issue

**Comment by ilike2burnthing** [comment]
Working ok with `cf_clearance` in Jackett for me, and there's no Cloudflare challenge when using it.

Though if I then try to reconfigure the indexer and remove `cf_clearance`, I get a Cloudflare challenge (which FlareSolverr solves) and login fails (like any other previous attempt to reconfigure the indexer).

Deleting the indexer, restarting Jackett, and adding the cookie without `cf_clearance` also fails (again though FlareSolverr solves the challenge).

Testing in Prowlarr, with or without `cf_clearance` works fine, as does reconfiguring the indexer, however every search causes a new Cloudflare challenge. This is not seen with an indexer like iDope - there a challenge for the first search but none after.

**Comment by ilike2burnthing** [comment]
IPv6 disabled, yes. FlareSolverr working for other indexers that require it (e.g. iDope).

Maybe the combination of Cloudflare and reCaptcha/hCaptcha on Scenetime/TurkTorrent is causing some problem? Though, it working if you delete the indexer and restart Jackett, but failing if you try to reconfigure, makes me think there's a bigger issue.

**Comment by garfield69** [comment]
FWIW, both SceneTime and TurkTorrent have been working for me all this week.

**Comment by ilike2burnthing** [comment]
TurkTorrent have dropped the Cloudflare challenge and is working fine for me, but SceneTime is still showing the same issue for me.

**Comment by ollie2a** [comment]
yes same issue for me on Scenetime .... FlareSolverr working but issue with cookies.

**Comment by ollie2a** [comment]
> yes same issue for me on Scenetime .... FlareSolverr working but issue with cookies.

resolved for me by changing the url to : tracker.scenetime.com

**Comment by garfield69** [comment]
just be aware that since tracker.scenetime.com does not support https any login or transactions are going through the wire un-encrypted for all to see if bad actors were snooping traffic

**Comment by ollie2a** [comment]
> just be aware that since tracker.scenetime.com does not support https any login or transactions are going through the wire un-encrypted for all to see if bad actors were snooping traffic

yes just realised this :-(

**Comment by ilike2burnthing** [comment]
TurkTorrent have dropped the Cloudflare challenge and SceneTime's cookies are now valid for a year. There may an underlying problem, but we're no longer able to test it, so closing this issue.
