### ISSUE TITLE
[Kinozal] doesn't start downloading .torrent

### ISSUE THREAD

**Issue by rbasa349** [Jackett/Jackett#14835]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
Running in Docker: Yes (image build: v0.21.1178-ls215)
Jackett variant: CoreLinuxMuslArm64
OS version: Unix 6.4.16.0 (64bit OS) (64bit process)
Environment version: 6.0.24 (/app/Jackett/)
Starting Jackett v0.21.1178
```

### Description

indexer 'Kinozal' doesn't start downloading .torrent

error: Safari cannot open the page because the address is invalid

in Chrome nothing happens

use Proxy/Vpn for test, use Win/Docker@macos.arm64 for test - in all cases everything is the same

other indexers works fine

no error messages

### Logged Error Messages

```text
2023-11-09 20:05:05.8184 Info Jackett startup finished in 37.935 s
2023-11-09 20:06:31.7617 Info Manual search in Kinozal for оппенгеймер => Found 14 releases [384ms]
```

### Screenshots

![2023-11-09_21 39 20_102643d0](https://github.com/Jackett/Jackett/assets/116624984/d575582e-f017-440d-ba12-7e0dfc6a1fe1)

**Comment by ilike2burnthing** [comment]
The Kinozal indexer returns magnet links, not torrent files. As far as I can tell Safari doesn't support magnet links (although there may be browser extensions which do). You'd also need to make sure your torrent client supports them and is associated with opening them.

This is just from some googling, not personal experience, so I'll leave you work it out. Feel free to report back what you found.

**Comment by rbasa349** [comment]
@ilike2burnthing 
 use **Win**/Docker@macos.arm64 for test. and chrome, sure

**Comment by ilike2burnthing** [comment]
Provide an enhanced log of the failed download on Windows while using Chrome - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by rbasa349** [comment]
@ilike2burnthing kinozal doesn't work with magnet (because it doesn't broadcast announcers for Kinozal), but i install torrent client and it works

but it doesn't make sense because without announcers including passkeys it won't work

I tried to add announcers text to the link and torrent files began to download. I’m not into js/css/html, so I can’t say anything more, but replacing the code below everything works on both MacOS and Windows (docker and no)

`download:
  before:
    path: get_srv_details.php
    inputs:
      action: 2
      id: "{{ printf \"%s&tr=http://tr3.torrent4me.com/ann?uk=my_pass_key\" .DownloadUri.Query.id }}"`

I think it’s worth returning the torrent-file to the default, because magnet-links are not functional for the Kinozal (since they are not transmitted announcers with passkey) and they have long been removed from the Kinozal

**Comment by rbasa349** [comment]
@ilike2burnthing after fix downloads "details.php"

**Comment by ilike2burnthing** [comment]
It downloads `download.php`, rather than a .torrent file, when your account has exceeded the allotted number of torrents for that day. This issue was originally raised in https://github.com/Jackett/Jackett/issues/11585 and resolved in https://github.com/Jackett/Jackett/pull/12263, however I'm assuming back then they relied on public trackers and so magnet downloads worked. This is a restriction of the tracker and seemingly can no longer be worked around.

**Comment by ilike2burnthing** [comment]
[v0.21.1179](https://github.com/Jackett/Jackett/releases/v0.21.1179)

**Comment by rbasa349** [comment]
> It downloads `download.php`, rather than a .torrent file, when your account has exceeded the allotted number of torrents for that day. This issue was originally raised in #11585 and resolved in #12263, however I'm assuming back then they relied on public trackers and so magnet downloads worked. This is a restriction of the tracker and seemingly can no longer be worked around.

yes, sorry, my bad, tested with second account and all works

> [v0.21.1179](https://github.com/Jackett/Jackett/releases/v0.21.1179)

thank you!

**Comment by YouROK** [comment]
Please revert magnets or make the choice of magnets or torrent files.
Kinozal gives a day limit on download torrents files
![photo_2023-11-10_21-00-34](https://github.com/Jackett/Jackett/assets/4067300/b6f5a447-8702-4ed7-aabd-555c915fde9f)
![photo_2023-11-10_21-01-01](https://github.com/Jackett/Jackett/assets/4067300/edcb11ff-04ba-4a17-8420-b6b90a85ed55)

**Comment by spawnlmg** [comment]
To bypass download restrictions you need to use magnets.

**Comment by YouROK** [comment]
![photo_2023-11-10_21-14-55](https://github.com/Jackett/Jackett/assets/4067300/682061e0-d4c3-4d93-95ee-c953c64d4684)
![photo_2023-11-10_21-15-00](https://github.com/Jackett/Jackett/assets/4067300/386be0c7-3953-4ae6-9d28-ad12a626797b)

**Comment by ilike2burnthing** [comment]
Yes, I'm aware the tracker only allows a limited number of torrents per day - https://github.com/Jackett/Jackett/issues/14835#issuecomment-1805001656

I think the only way to satisfy both is to create a second 'magnet' indexer. Will do this later.

**Comment by ilike2burnthing** [comment]
[v0.21.1189](https://github.com/Jackett/Jackett/releases/v0.21.1189)
