### ISSUE TITLE
[req]: AniToons

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#14846]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: AniToons
- URL: https://anitoons.xyz/
- Description: AniToons is a BRAZILIAN Private Torrent Tracker for ANIME / CARTOONS
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MST 5 days, global MR 0.4
- Additional Comments: 
engine UNIT3D 7.0.3
signup currently open
```

**Comment by ilike2burnthing** [comment]
[v0.21.1202](https://github.com/Jackett/Jackett/releases/v0.21.1202)

**Comment by garfield69** [comment]
https://anitoons.xyz/ cloudflare Connection timed out Error code 522

**Comment by garfield69** [comment]
v0.21.1855
