### ISSUE TITLE
[animetime] (testing) Exception (animetime): certificate validation failed: [Subject]  CN=animetime.cc[Issuer]  CN=R3, O=Let's Encrypt, C=US[Serial Number]  03A9A59F4A769491E33C8B8941218A7D089C[Not Before]  11/6/2023 4:19:53 AM[Not After]  2/4/2024 4:19:52 AM[Thumbprint]  93A2F59E6813E7A26AE9FEDFDB8C7AC88AC56DDD: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by Kuroo2021** [Jackett/Jackett#14843]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Synology NAS
```

### Description

Error

### Logged Error Messages

```text
Exception (animetime): certificate validation failed: [Subject] CN=animetime.cc [Issuer] CN=R3, O=Let's Encrypt, C=US [Serial Number] 03A9A59F4A769491E33C8B8941218A7D089C [Not Before] 11/6/2023 4:19:53 AM [Not After] 2/4/2024 4:19:52 AM [Thumbprint] 93A2F59E6813E7A26AE9FEDFDB8C7AC88AC56DDD : The SSL connection could not be established, see inner exception.
```

### Screenshots

![Screenshot 2023-11-10 203838](https://github.com/Jackett/Jackett/assets/18900059/884d1483-590b-47d5-b235-8fc362ad8c22)

**Comment by ilike2burnthing** [comment]
Working ok here, and your error shows the correct information. Provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
