### ISSUE TITLE
Can't add file to blackhole if browsing from ReverseProxy address

### ISSUE THREAD

**Issue by seanvree** [Jackett/Jackett#1484]
Windows 10E (1703)
webserver:  IIS
Jackett:  version:  0.7.1483.0 (windows service - NSSM)

settings:
Base override: /jackett
Server port:  9117  (reverse proxied from 80)
blackhole dir:  C:\Media\PlexDownloads\blackhole (on same box as jackett install)
external access:  enabled

**Issue:

I'm not sure if this ever worked on my rig, but just wanted to give it a shot.  So I get to my jackett front-end via my reverse proxy that is hosted on Windows 10E IIS

mydomain/jackett

I manually search for an item, and it finds it.  When I click send to blackhole I get:

" Request to Jackett server failed" in the UI, but NO mention of ANY erros in the log?

If I browse to the ui via   IP:port - and attempt to upload the same release, no erros. 

All other functions of jackett are working great. 

Any Ideas?

BTW - Thanks for all the hard work.

**Comment by kaso17** [comment]
Can you please try to run the JacketConsole.exe instead of the service with the "-l -t" arguments to get more log output, that should help tracking down the issue.

**Comment by seanvree** [comment]
@kaso17  - Will do brother.  

Thanks for your work.

**Comment by seanvree** [comment]
@kaso17  done, see here:   Search term was "kaskade" 

https://gist.github.com/seanvree/45ce33f118eb4036174751963603ec3f

**Comment by kaso17** [comment]
According to the logs the Blackhole download seems to work fine.
Does the actual blackhole download work (files are created in the directory) and the client just shows the error message?
Please also check the ISS log file. It might not like the response by jackett causing the problem.

**Comment by seanvree** [comment]
@kaso17 Actually, further investigation appears that you're right it down download the file, but the jackett console just shows that message.  

I'll go ahead and close this.
