### ISSUE TITLE
ISP Blocked Index

### ISSUE THREAD

**Issue by ohitstom** [Jackett/Jackett#14849]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Default windows 10 64 bit install
```

### Description

Sorry if this is a dumb question but my ISP blocks sites such as EZTV, is there a way to run just jackett through some sort of proxy or something like that?

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (eztv): An existing connection was forcibly closed by the remote host.
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/22730962/5e4c77b0-f835-4440-9e23-6e33752ea7f7)

**Comment by ilike2burnthing** [comment]
Reconfigure the indexers to use a working mirror or proxy site. Failing that, configure a proxy in Jackett's settings or use a VPN.

**Comment by ohitstom** [comment]
> Reconfigure the indexers to use a working mirror or proxy site. Failing that, configure a proxy in Jackett's settings or use a VPN.

sorry for the late reply can you recommend a proxy to use within jacketts settings?

**Comment by ilike2burnthing** [comment]
Hide.me offer a SOCKS proxy, otherwise just google `free SOCKS5 proxy` or `free HTML proxy`.

**Comment by ohitstom** [comment]
> Hide.me offer a SOCKS proxy, otherwise just google `free SOCKS5 proxy` or `free HTML proxy`.

ty
