### ISSUE TITLE
[req]: Torrentleech: Option to exclude rar (or any?) tag

### ISSUE THREAD

**Issue by Hannah-GBS** [Jackett/Jackett#14856]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Torrentleech has a fair amount of rar releases, but requires them to be tagged with the `rar` tag. The issue with this is their search function had no way to *exclude* a tag from a search. I opened a feature request for that some months ago, and it has now been added. Appending `-tags:rar` (for example) with a comma separated list of tags to the `query` section of the search URL now excludes releases with those tags.

ie `https://www.torrentleech.org/torrents/browse/index/query/lord of the rings -tags%3AFREELEECH` searches for `lord of the rings` results without the `FREELEECH` tag. This is notable different to their *include* tags format, which is not part of the `query` segment.

### Describe the solution you'd like

It would be nice if we could either simply have a checkbox to exclude releases tagged with `rar`, or possibly even better have a text box to input a comma separated list of tags to exclude, though that may be a little more niche.

### Describe alternatives you've considered

My alternative up to this point is to simply have Torrentleech only used on Interactive Searches, and verifying they're not rar releases, as I have no interest in adding an unpacking step to my setup.

**Comment by garfield69** [comment]
The indexer torrentleech already has a exclude rar checkbox, which is coded as a post search results filter to drop rows that have a tag that contains `rar`.

Admittedly swapping the current row filter `:not(.tags:contains(\"rar\"))` with a search parm `-tags:rar` would be a better option as long as the web sites supports the use of both the `tags:` and `-tags:` in the one search query. 
I'll test and if it works then we will update the indexer to support this method.

**Comment by Hannah-GBS** [comment]
Oh, I see it does. It doesn't have that option on Prowlarr and I saw they pull their indexer updates from Jackett so assumed the definition would be the same here as it was updated there recently, but looks like they excluded that feature, as per one of their issues:
`exclude archives setting not added (https://github.com/Jackett/Jackett/commit/93a26a78f5dce0208ee0f10440c48606939fd78d) as json filters not supported(?)`

Either way, yes I believe it allows tags and -tags: as regular tags are handled as /facets/tags/ in the URL, and on their site at least both work together fine.

**Comment by garfield69** [comment]
I've tested and it works fine. And the bonus is that this new method will allow prowlarr to import the Jackett indexer un-edited so it will work there too. ;-)

**Comment by garfield69** [comment]
v0.21.1230
