### ISSUE TITLE
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match

### ISSUE THREAD

**Issue by laurentbinagot** [Jackett/Jackett#14858]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using FlareSolverr: http://localhost:8191 (in docker)	
Using proxy: Disabled	
Running in Docker: No	
Jackett variant: CoreLinuxArm64	
Starting Jackett v0.21.1239
```

### Description

When i try to use YGGtorrent I got the error
Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match
Jackett is up to date. FlareSolverr too.
The logs of FlareSolverr show me that the Cloudflare challenge was resolve

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match

[v0.21.1239.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match
  at Jackett.Common.Indexers.CardigannIndexer.TestLogin () [0x002a9] in ./Jackett.Common/Indexers/CardigannIndexer.cs:884 
  at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration (Newtonsoft.Json.Linq.JToken configJson) [0x0008e] in ./Jackett.Common/Indexers/CardigannIndexer.cs:1043 
  at Jackett.Server.Controllers.IndexerApiController.UpdateConfig (Jackett.Common.Models.DTO.ConfigItem[] config) [0x0013e] in ./Jackett.Server/Controllers/IndexerApiController.cs:111 
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 
  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x00042] in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:26
```

**Comment by ilike2burnthing** [comment]
How have you set up Jackett and FlareSolverr in Docker that you're able to use localhost between the two of them?

Are you using yggtorrent or yggcookie?

Are you using a proxy or VPN?

Provide an enhanced log of your issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by laurentbinagot** [comment]
Jackett is install as a service and Flaresolver in a docker container, I use a ddns.net adresse and a port forwarding so I think they can see each other

yggtorrent but yggcookie send me same error

no proxy or vpn

there is an enhanced log [log.1.txt](https://github.com/Jackett/Jackett/files/13429199/log.1.txt)
 
thanks

**Comment by garfield69** [comment]
you are getting 404 not found when jackett attempts a search.
this is because you are using the incorrect sitelink.
use your Jackett dashboard to edit the yggtorrent indexer and set the sitelink to `https://www3.yggtorrent.wtf/`

**Comment by laurentbinagot** [comment]
I don't understand, there is already this sitelink

**Comment by laurentbinagot** [comment]
Sorry the enhanced log I've previously add was not mine but other I've download previously in order to find a clue
there is mine [log.txt](https://github.com/Jackett/Jackett/files/13429618/log.txt)

**Comment by garfield69** [comment]
it looks like the cookie returned by your docker flaresolverr is not being accepted by the website from your Jackett yggtorrent indexer session, and the website is returning the login page back to you again instead of a logged-in page.

I suspect that if you are using a docker flaresolverr then you may also need to use a docker Jackett so that the machine signatures are similar enough for the website to accept that you have passed the cloudflare security check.
@ilike2burnthing  does that seem likely to you?

**Comment by laurentbinagot** [comment]
> it looks like the cookie returned by your docker flaresolverr is not being accepted by the website from your Jackett yggtorrent indexer session, and the website is returning the login page back to you again instead of a logged-in page.
> 
> I suspect that if you are using a docker flaresolverr then you may also need to use a docker Jackett so that the machine signatures are similar enough for the website to accept that you have passed the cloudflare security check. @ilike2burnthing does that seem likely to you?

When I install Jackett in docker the ip address assign was lost and the port too :/

**Comment by laurentbinagot** [comment]
at the launch an ip was assign but few second after there is no one
<img width="1096" alt="Capture d’écran 2023-11-21 à 20 01 24" src="https://github.com/Jackett/Jackett/assets/9486467/7f5ba422-8a80-4674-bbfe-eeccff421c45">

**Comment by ilike2burnthing** [comment]
Have you published a port? Have you assigned it a fixed IPv4 address? Is it running on the same network as FlareSolverr?

What do the logs say?

**Comment by laurentbinagot** [comment]
there is my docker-compose.yml

version: "3"
services:
  jackett:
    image: ghcr.io/linuxserver/jackett:arm64v8-latest
    container_name: jackett
    environment:
      - TZ=Europe/Paris
      - AUTO_UPDATE=true
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      #- ./jackett/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - cloudflare
    depends_on:
      - flaresolverr
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      #- CAPTCHA_SOLVER=hcaptcha-solver
      - LANG=en_US
    ports:
      - 8191:8191
    restart: unless-stopped
    networks:
      - cloudflare

networks:
    cloudflare:
      external: false
      enable_ipv6: false



I'm unable to find the logs where are they when install with docker ?

**Comment by laurentbinagot** [comment]
no just stop the service

I try but say me that "No log line matching the '' filter"

**Comment by laurentbinagot** [comment]
Pulling jackett      ... pulling from linuxserver/jackett

ERROR: for jackett  no matching manifest for linux/arm/v8 in the manifest list entries
ERROR: no matching manifest for linux/arm/v8 in the manifest list entries

**Comment by ilike2burnthing** [comment]
Bit odd that it didn't work, but it shouldn't matter as it's exactly the same.

As you have volume mapping set up for the container, look in that config directory to find the log file.

**Comment by laurentbinagot** [comment]
I checked but the directory is empty

**Comment by ilike2burnthing** [comment]
Try removing the leading `.` from your volume mapping.

**Comment by laurentbinagot** [comment]
still no logs :/

**Comment by ilike2burnthing** [comment]
If you run Jackett as a single container, not as part of a stack, does it work then?

Can you connect to the console for the Jackett container ( `>_` icon under quick actions)?

**Comment by laurentbinagot** [comment]
No it’s the same

when I try this I got an error saying that I need to wait the container finish to restart

**Comment by ilike2burnthing** [comment]
To find the log on the host system:
`/var/lib/docker/containers/<container_id>/<container_id>-json.log`

**Comment by laurentbinagot** [comment]
empty too

**Comment by laurentbinagot** [comment]
when I run the container directly by command line I got
docker run -ti sha256:84aab43453ebb72033b528f2fd7e1ea70db67baab4fc234f2115fc494e538654
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v8) and no specific platform was requested

The specified image is the one I use in docker-compose

Raspberry Pi4 architecture isn't support ?

**Comment by ilike2burnthing** [comment]
Are you running at 32bit OS? https://forums.raspberrypi.com/viewtopic.php?t=288394

**Comment by ilike2burnthing** [comment]
Provide the responses for `lscpu` and `uname -a`.

**Comment by laurentbinagot** [comment]
lscpu

Architecture:                    aarch64
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     1500,0000
CPU min MHz:                     600,0000
BogoMIPS:                        108.00
L1d cache:                       128 KiB
L1i cache:                       192 KiB
L2 cache:                        1 MiB
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid


uname -a

Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

**Comment by ilike2burnthing** [comment]
And lastly the response for `docker version`. 

Open an issue over on the LS.io Jackett GH page, referencing this one, as there may be a wider issue.

**Comment by laurentbinagot** [comment]
Client: Docker Engine - Community
 Version:           25.0.0-beta.1
 API version:       1.44
 Go version:        go1.21.3
 Git commit:        2b521e4
 Built:             Mon Nov 13 16:49:51 2023
 OS/Arch:           linux/arm
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.0-beta.1
  API version:      1.44 (minimum version 1.12)
  Go version:       go1.21.3
  Git commit:       6af7d6e
  Built:            Mon Nov 13 16:49:51 2023
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by laurentbinagot** [comment]
after a completely new install of ubuntu OS 64 bits, It works well with Jackett and FlareSolverr in Docker.

Thanks for the help
