### ISSUE TITLE
REQUEST: Search - Add to Jackett RSS FEED

### ISSUE THREAD

**Issue by kingfenix** [Jackett/Jackett#1485]
1) Would it be possible to add a rss feed to Jackett which we could add to our favorite torrent program (deluge)? This feed would be empty initially, and be populated by (2) below

2) When saearching the indexers for content currently there are buttons to "download to blackhole" or magnet links, etc...add here a link to add the entry to the rss feed provided in (1)

**Comment by chibidev** [comment]
Just out of curiosity: @kingfenix what's your use case for a manually maintained RSS feed?

**Comment by kingfenix** [comment]
Well back before KAT was taken down it provided a rss feed, that you could do this exact thing with. It was a user private rss feed, and for any torrent in the page you could "add to your private rss" and this rss could then be used in your downloader suc as deluge (who uses a vpn of course) to download anything you ever added to your rss feed. I have never found a good replacement yet for that functionality. And doing so as requested here would be PERFECT. normal rss feeds will download everything matching some search criteria and you end up with more than you want normally. This would be a self-hosted, private rss feed, which you could add torrents to from any indexer via the search page, and be even BETTER as it handles multiple sites. Also I can access my jackett remotely unlike my vpn'ed deluge, so this provides the ability to download things to your server from anywhere really while maintaining your protection (VPN) 

Does that answer the question?

**Comment by chibidev** [comment]
@kingfenix I think so, thank you for such detail. If I get this right, basically you'd like some mechanism to add a torrent straight from Jackett to the downloader (e.g. Deluge) with just one click, correct? I understand that having a private, manually maintained RSS feed is one option, however that might not be the only option. Understanding the real reason behind helps with the implementation.

**Comment by kingfenix** [comment]
your absolutely right, being able to add torrents straight to the client without the "middleman" of sonarr/radarr which are also only good for tv/movies...with the direct approach I can add anything I want without any excess unwanted torrents through a web browser from anywhere

**Comment by kaso17** [comment]
@kingfenix a temporary workaround would be to use the blackhole directory and use a simple bash/whatever script to generate the rss feed from the blackhole torrent files.
Alternatively there were some browser plugins allowing to "redirect" torrent file downloads to deluge, rtorrent, etc.. Not sure if they are still available.

**Comment by kingfenix** [comment]
yeah there are a couple band-aid type workarounds, but not any good solutions yet

**Comment by jobrien2001** [comment]
I am hopeful this feature has not been forgotten.  I would really like the ability to create rss feeds out of jacket's search criteria that would be privately hosted within jacket so i can subscribe to them from a torrent client.   That way I can have the client auto download a search criteria from a site that doesn't support rss (most dont have the feature anymore).  This is would be the only software that i know of that would carry such a feature.

**Comment by kaso17** [comment]
@jobrien2001 this issue/feature is for a "manual" download RSS feed (an alternative way of pushing torrents from jacketts manual search into a client).

If you just need a RSS feed for some tracker which doesn't support RSS feeds anymore then you can already use the torznab feed (which is an enhanced RSS feed). Feel free to add your categories/keywords to the correspondig API URL. Every torrent client should be able to download torrents via the torznab feed.

**Comment by jobrien2001** [comment]
Thank you so much for your reply.  I had no idea how this was done. Ended up searching for information on the torznab API and after some tries was able to produce the rss result.

I want to leave a sample url in here in case someone else is searching for this , modify with your jacket IP/port, API key, and indexer, and optional category/search string:

> http://JACKETIP:JACKETPORT/api/v2.0/indexers/INDEXER/results/torznab/api?apikey=JACKETAPIKEY&t=search&cat=CATEGORY&q=SEARCHSTRING

Question: is there anyway to have an RSS icon link to a url like this on every search result?  Some users may not be tech savvy enough to follow your directions.  Others may not bre even aware this is possbile within jacket (like myself).  A user friendly link would be nice to just copy and paste into our clients.

**Comment by kaso17** [comment]
@jobrien2001 "Copy RSS feed" button was added via 54c1acb669f6a0ba58238fc42dcf579dbcbb9312

**Comment by jobrien2001** [comment]
@kaso17 Thanks for that. 

Purely for convenience... Is it possible to add it to the search results as well (with the query string and category already generated?

**Comment by justingoldberg** [comment]
Another site which has a private rss feed is showrss.info. RIP EZTV!

**Comment by kaso17** [comment]
@jobrien2001 please open another enhancement issue for this.

**Comment by krugster** [comment]
+1 for direct-to-deluge downloading from jackett. Sometimes Sonarr or Radarr don’t find the right torrent but I manage to find it in jackett. Because all of my apps are running remotely I can’t just click the magnet link to download locally so I need to copy the link, open up my deluge UI (which is HORRIBLE on a mobile browser), add torrent, paste link, etc. 

If Sonarr and radarr can put a torrent directly into deluge, can’t jackett?

**Comment by garfield69** [comment]
closing as stale.
