### ISSUE TITLE
[req]: Comando Torrents 

### ISSUE THREAD

**Issue by ruizlenato** [Jackett/Jackett#14861]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Comando Torrents 
- URL: https://comando.la/ 
- Description: Popular Brazilian Tracker for Movies and TV Shows
- Additional Comments: In the past, there was protection on the links, but now there is no more.
```

**Comment by garfield69** [comment]
duplicate of #5731
this site has single entry search results leading to multiple downloads (one for every TV episode, or one for every quality of movie)
as such it is not suitable for Cardigann processing.

**Comment by ruizlenato** [comment]
> duplicate of #5731 this site has single entry search results leading to multiple downloads (one for every TV episode, or one for every quality of movie) as such it is not suitable for Cardigann processing.
![image](https://github.com/Jackett/Jackett/assets/49354525/cebc24f5-1b0d-403b-b4db-571303df2a24)

https://github.com/felipemarinho97/torrent-indexer look this

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
