### ISSUE TITLE
I can't install custom indexer

### ISSUE THREAD

**Issue by skaz97** [Jackett/Jackett#14866]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Running Jacket installed in raspberry with dietpi.
```

### Description

I have everything correct, jacket with dietpi installed and working.

But I have seen that there are many old movies and series that cannot be found in the indexers that I have installed.
Therefore, I have looked for more indexers and I am trying to install them.

To test, I have seen the Newpct.cs indexer and I have copied it to the jacket/Indexers directory and it is copied correctly.

But when I go to the web interface, it doesn't appear anywhere.

I don't know how I have to install it and make it work. I've looked everywhere and can't find it...

Help please?

### Logged Error Messages

```text
I havent got.
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md#contributing-code
