### ISSUE TITLE
[req]: Adding Priority change for Service/Console - Windows

### ISSUE THREAD

**Issue by porter9992** [Jackett/Jackett#14868]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

In Windows, Changing the Service priorities to a higher priority (or lower) may gain a more results for those with systems that have higher CPU utilization.

### Describe the solution you'd like

A Setting in some form the can adjust all processes to a drop-down option list of the desired priority (as listed in the Windows Task Manager~Details~right-click~Set Priority).

**Comment by ilike2burnthing** [comment]
This can be done in the registry if really wanted, no need to add this to Jackett itself.
