### ISSUE TITLE
[yggtorrent] (updating) Address not available (www3.yggtorrent.wtf:443): Address not available

### ISSUE THREAD

**Issue by Obijc** [Jackett/Jackett#14876]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No	
Using proxy: Disabled
App config/log directory: /config/Jackett	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads	
Running in Docker: Yes (image build: v0.21.1293-ls237)
File /etc/issue: Welcome to Alpine Linux 3.18
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.1.0.13 (64bit OS) (64bit process)	
Environment version: 6.0.25 (/app/Jackett/)
Starting Jackett v0.21.1293
```

### Description

I can no longer use YggTorrent with Jackett; it was working perfectly fine until around Thursday when I started getting this error, and some friends of mine who use the same system are experiencing it too. I don’t know where the error is coming from, but the system was working perfectly before. I tried to completely reinstall and update Jackett but without success. The site is still accessible from another computer, and I checked that the DNS requests are not blocked.

### Logged Error Messages

```text
An error occurred while updating this indexer
Address not available (www3.yggtorrent.wtf:443): Address not available
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/96177186/82095905-9ce1-44b2-a2eb-1b1f9899becc)
![image](https://github.com/Jackett/Jackett/assets/96177186/6016a162-97e4-4bfa-a18e-a2674a52d463)

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed
