### ISSUE TITLE
[scenetime] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14878]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

the SceneTime website is offline

### Logged Error Messages

```text
https://www.scenetime.com/ Connection timed out Error code 522
all uptime checkpoints return 403 forbidden
now
Server Upgrade in Progress
Please try again in a few hours. We apologize for any inconvenience caused.
```

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
Scenetime returning zero results.
Looks like the browse page layout has changed, for example the row selector is now `<table class="bw-table" id="torrenttable">`

**Comment by garfield69** [comment]
v0.24.1459

**Comment by garfield69** [comment]
https://www.scenetime.com/rss.php?apikey=(removed)&t=search&limit=100 > 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<error code="102" description="Torznab API requires VIP/Donor status. Renew at /donate.php" />
```

do we switch this indexer to html scraping or create a new indexer for the html scraping and make the current one a VIP only indexer?

**Comment by mynameisbogdan** [comment]
I would switch to html scraping, but via yaml if possible.

**Comment by ilike2burnthing** [comment]
Add a `VIP/Donors only` note to this one ~and restore the C# indexer? Not sure if anything has changed that would affect it.~ [Bogdan got in before me]

I don't see why C# was being used (the retry logic maybe?) - https://github.com/Jackett/Jackett/blob/395dba3b1fcf8f06b7b5c386070d3c84783c2b44/src/Jackett.Common/Indexers/Definitions/SceneTime.cs

**Comment by mynameisbogdan** [comment]
> I don't see why C# was being used

The column selectors I think.

**Comment by zoostorm1** [comment]
I have asked the powers what is going on here, that message is news to me.

**Comment by mynameisbogdan** [comment]
@garfield69 I wanna take a jab at it, if you didn't already started on it.

**Comment by garfield69** [comment]
Go for it. I've done my morning contribution and wont be back till later in the day.

**Comment by zoostorm1** [comment]
Not sure what the big hurry is here ?
I mean if you are really that desperate to do work you may not need to, knock youself out.
However, I have asked for an official check as to whether that message is by design or a bug.

**Comment by mynameisbogdan** [comment]
> I mean if you are really that desperate to do work you may not need to, knock youself out.

You need to tone it down.

> However, I have asked for an official check as to whether that message is by design or a bug.

There's no bug when the site is advertising the torznab API for VIPs only.

**Comment by zoostorm1** [comment]
NO, I dont need to tone anything down.

Of course its a potential bug, there was never any mention while it was being developed of it being VIP only.

You need to take a chill pill instead of taking unnecessary digs at people trying to help you and potentially save you work.

**Comment by zoostorm1** [comment]
Abuse ? What a joke you are.
If thats what you want then sure, clearly you're an ass.

**Comment by ilike2burnthing** [comment]
> Torznab API Available
[...]
🔒 Your feed is on the standard plan. These need [VIP / Donor](https://www.scenetime.com/donate.php):
[...]
> - Torznab API — searching from Prowlarr, Sonarr and Radarr
> 
> ✔ Still yours: every category, the freeleech / featured / bookmarks types, and tag filters.

https://www.scenetime.com/rss.php

**Comment by mynameisbogdan** [comment]
> Go for it.

PR done, was quite easy. 😄

**Comment by garfield69** [comment]
v0.24.2398

**Comment by Phil57** [comment]
```
Your API is on the standard plan — up to 25 results per search and 60 searches/hour. Keyword, IMDB ID, season and episode searches all work normally.

[VIP / Donor](https://scenetime.com/donate.php) raises that to 100 results and 300 searches/hour, and unlocks the freeleech-only filter.
```

It looks like the API is back with a token after some changes

**Comment by mynameisbogdan** [comment]
The info is a little confusing, as even the text search is VIP only according to their site.

```
Your feed is on the standard plan. These need VIP / Donor:
- Keyword search — the q= parameter and the Search box below
- Advanced filters — IMDB ID, min/max size, min/max seeders, leechers, resolution, codec, language, date added and uploader
- Custom sort — your feed is always newest first
- More than 30 results — donors get up to 200, and can page with offset=
- A bigger Torznab API allowance — the API itself works on the standard plan (25 results, 60 searches/hour); donors get 100 results, 300 searches/hour and the freeleech-only filter
```

`imdbid` still shows in `t=caps` for non-VIP accounts, so if they don't want that it should be removed from there.

**Comment by StarTech27** [comment]
Its still being worked on atm.

**Comment by mynameisbogdan** [comment]
@garfield69 @ilike2burnthing Prowlarr's generic torznab can detect these fields but Jackett's lacks this kind of functionality, even considering scenetime is a yaml. I think we might need to eventually rename `scenetime-api` to `scenetime-api-vip`/`scenetime-vip`.

**Comment by StarTech27** [comment]
We discussed this change with the ST owner.
The limits should be removed now (so it works as before).
You should also see this message on the RSS & Torznab pages.

> Every filter, search and the full API are included for all members in good standing — up to 200 results per feed, 100 per API search, 300 requests/hour.

**Comment by mynameisbogdan** [comment]
Ah, I understand.

I was under the impression they would restrict imdbid searches for VIP only, which my previous message was about as we can't detect that in Cardigann.

Thanks for the clarification.

**Comment by StarTech27** [comment]
There shouldn't be any restrictions other than the usage limits.
If you do find an issue just let me know and we can look into it.

**Comment by garfield69** [comment]
v0.24.2413
