### ISSUE TITLE
[eztv] (testing) Test search in EZTV => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by Keatingfish** [Jackett/Jackett#14886]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No	
Using proxy: Disabled	
App config/log directory: /media/sdk1/home/monkstah/.config/Jackett	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads	
Running in Docker: No	
File /etc/issue: Debian GNU/Linux 9 \n \l	
Jackett variant: CoreLinuxAmdx64	
OS version: Unix 6.1.43.0 (64bit OS) (64bit process)
Environment version: 6.0.24 (/media/sdk1/home/monkstah/Jackett/)	
Starting Jackett v0.21.1085
```

### Description

EZTV has modified their site to reflect that the new location is https://eztvx.to/ .. However that page is just a front end that you have to click Home Page on. The real directory structure is at : https://eztvx.to/home 

Jackett is stating  An error occurred while testing this indexer
Test search in EZTV => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc. when utilizing that link. 

Unsure how to resolve as there is no cloudflare or other items happening
Jackett version v0.21.1085

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in EZTV => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc. when utilizing that link.
```

### Screenshots

.

**Comment by garfield69** [comment]
Your Jackett version is 45 days out of date.
Update to 0.21.1315 to resolve your issue.
