### ISSUE TITLE
[korsar] (updating) Login failed: Selector "a[href*="ucp.php?mode=logout"]" didn't match

### ISSUE THREAD

**Issue by acolis** [Jackett/Jackett#14884]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://x.x.x.x:8191
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.2365-ls86)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.0.0 (64bit OS) (64bit process)
Environment version: 6.0.25 (/app/Jackett/)
Starting Jackett v0.21.1310
```

### Description

follow the steps in the korsar private tracker.
Copy the cookie, copy the user agent.
Error is shown:
Login failed: Selector "a[href*="ucp.php?mode=logout"]" didn't match

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href*="ucp.php?mode=logout"]" didn't match

[v0.21.1310.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href*="ucp.php?mode=logout"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1043
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
Follow these troubleshooting steps:
https://github.com/Jackett/Jackett/wiki/Troubleshooting#login-failed-selector
https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work

If those don't work, provide an enhanced log of the issue:
https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by acolis** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/13574944/log.txt)

**Comment by garfield69** [comment]
It does not appear that your cookie was accepted, because the index.php page that was presented shows no signs of having any personal menu options you would expect to see if you have logged in successfully, such as options to logout, view your profile, change your settings.

Is this the first time you have tries to set up the korsar indexer with Jackett or was it working previously?
Are you fetching the cookie and UA from a browser running on the same ubuntu machine that is running Jackett?
If so what browser, chrome, firefox, something else? 
Are you using a system wide VPN or accessing it natively?

**Comment by acolis** [comment]
Jacket is in docker.
Fetching the cookie on my windows machine, tried via chrome or firefox with no luck.
Not using VPN.
I never worked, trying for first time

**Comment by garfield69** [comment]
Ah sorry, missed the docker clue in the environment section of your post.
which makes fetching cookies and UA more complicated because the environment the browser session is based on needs to match the environment the docker image is based on so that the cookies and UA have similar signatures.
ilike2burnthing as you know this is not my cup of tea, do you have suggestions for how the OP can capture a cookie for docker use?

**Comment by acolis** [comment]
Other cookie based trackers work fine, seems something specific for this tracker

**Comment by ilike2burnthing** [comment]
Pull the cookie and UA from a Firefox container - https://hub.docker.com/r/linuxserver/firefox

**Comment by acolis** [comment]
I dont use windows docker, its a docker on OMV box

**Comment by ilike2burnthing** [comment]
Given that Jackett can access http://filbi1976.org/index.php at all, and that there is a `points.php` link with an actual value, I'm guessing you are logged in.

Can you provide an HTML dump of `index.php` from your browser while signed in?

Have you changed any appearance/skin/layout settings which may be causing an issue here? Jackett expects to see a logout button, but there's none available from your Jackett log (there's not even a User Control Panel link - ucp.php), hence why the indexer is failing.

**Comment by ilike2burnthing** [comment]
Just `index.php` will be fine.

We don't necessarily have to use `index.php`, nor a logout button, but if there's a generic page with a logout button on it, provide the URL and the HTML dump for it.

**Comment by acolis** [comment]
[filbi1976.org - Поиск.txt](https://github.com/Jackett/Jackett/files/13575709/filbi1976.org.-.txt)

Html dump  based on the help link you provided, preparing the one with the logout button

**Comment by ilike2burnthing** [comment]
Please follow the linked instructions, that's not an HTML dump.

**Comment by acolis** [comment]
[http __filbi1976.org_.txt](https://github.com/Jackett/Jackett/files/13575771/http.__filbi1976.org_.txt)

Please see fixed file

**Comment by ilike2burnthing** [comment]
That looks to be the homepage rather than `index.php`, although the logout link it there. Can you provide the HTML dump of `index.php` just so we can be sure that's definitely the issue?

**Comment by acolis** [comment]
[http __filbi1976.org_index.php.txt](https://github.com/Jackett/Jackett/files/13575884/http.__filbi1976.org_index.php.txt)

**Comment by garfield69** [comment]
excellent. so we just need to use the home page (/) instead of /index.php and we should be good to go.

**Comment by garfield69** [comment]
v0.21.1315

**Comment by acolis** [comment]
Korsar works as intended. 

Thank you very much

**Comment by acolis** [comment]
Korsar is broken again
Jackett.Common.IndexerException: Exception (korsar): Login failed: Selector "a[href*="ucp.php?mode=logout"]" didn't match

**Comment by ilike2burnthing** [comment]
Enhanced Jackett log of the failed login please, as well as an HTML dump of http://filbi1976.org/

**Comment by acolis** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/13767197/log.txt)
[filbi1976.org - Поиск.txt](https://github.com/Jackett/Jackett/files/13767198/filbi1976.org.-.txt)

**Comment by acolis** [comment]
[filbi1976.org - Главная.txt](https://github.com/Jackett/Jackett/files/13767201/filbi1976.org.-.txt)

**Comment by ilike2burnthing** [comment]
You're being thrown back to the login page, pull a new cookie.

Failing that, follow these troubleshooting steps:
https://github.com/Jackett/Jackett/wiki/Troubleshooting#login-failed-selector
https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work

Failing all of that, delete the indexer, restart the Jackett container, sign out of the tracker in browser, sign back in, copy the new cookie and try to re-add the indexer in Jackett.

**Comment by acolis** [comment]
New Error

[log.txt](https://github.com/Jackett/Jackett/files/13767242/log.txt)


Open new issue?

**Comment by acolis** [comment]
The guide for the cookie for korsar should state that not the whole cookie is required but only this parts:

phpbb3_pwy9y_u=123456; phpbb3_pwy9y_k=32132as1d3as2d1as32d; phpbb3_pwy9y_sid=321asdasd321asd321asd

**Comment by ilike2burnthing** [comment]
No, that's fine, but I'll look at it tomorrow if no one else has.

**Comment by garfield69** [comment]
v0.21.1446

**Comment by acolis** [comment]
Thank you yet again
