### ISSUE TITLE
How to change App config/log directory ?

### ISSUE THREAD

**Issue by Nottt** [Jackett/Jackett#1488]
I'm trying to run jackett as another user and it keeps trying to read the app config from the root home directory, so that breaks my systemd script and I can't start it as the user too. As root works.

I tried this :

ExecStart=/usr/bin/mono --debug /opt/Jackett/JackettConsole.exe --NoRestart --data=/opt/.config/Jackett/

But didn't worked. So is there any way to change the directory ? My user has no home directory

**Comment by kaso17** [comment]
Try setting the XDG_CONFIG_HOME environment variable to the data dir please
#1469 is probably related

**Comment by hotio** [comment]
When starting Jackett with `--DataFolder=/config`

Settings file and indexer files are saved/read from /config, the log file however goes to the path in $XDG_CONFIG_HOME/Jackett/log.txt

**Comment by kaso17** [comment]
Setting the XDG_CONFIG_HOME environment variable is the correct way of doing this on Unix/mono systems. --DataFolder shouldn't be used. See my last comment on #1469.

**Comment by kaso17** [comment]
Readme has been updated via #1841
