### ISSUE TITLE
YGGtorrent new url

### ISSUE THREAD

**Issue by tifo71** [Jackett/Jackett#14882]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
OS : Windows 11
jackett version : v0.21.1302
Flaresolverr enabled
Docker : no
```

### Description

YGGTORRENT has changed its URL: the new URL is https://yggtorrent.qa so Jackett doesn't work for YGGTorrent and displays the following message : An error occurred while testing this indexer
Test search in YGGtorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

an update of jackett with new url of YGGTorrent is necessary because just modifying the url in the parameters is not enough, the test fails. You need to update the YGGTorrent profile in jackett

thanks

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in YGGtorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/130233722/623b98be-e051-4706-bb1d-82b0c4ad374f)

**Comment by garfield69** [comment]
Thanks for the notice.
We will update the indexer.
In the mean time you can continue to use your yggtorrent indexer if you use the Jackett dashboard to edit the config and set the sitelink to `https://www3.yggtorrent.qa/`

**Comment by tifo71** [comment]
> Thanks for the notice. We will update the indexer. In the mean time you can continue to use your yggtorrent indexer if you use the Jackett dashboard to edit the config and set the sitelink to `https://www3.yggtorrent.qa/`

Hello, yes I had modified the url it didn't work but in fact I just saw that I had made a mistake in the address I had forgotten the 3. Sorry

**Comment by garfield69** [comment]
v0.21.1310
