### ISSUE TITLE
[req]: kinozal: rawsearch

### ISSUE THREAD

**Issue by journeym** [Jackett/Jackett#14892]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

kinozal contains releases with special symbols such as & that cant be found form radarr.
radarr support said i should create an issue here to enable rawsearch for this tracker.

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by journeym** [comment]
case on radarr support
https://github.com/Radarr/Radarr/issues/9470

**Comment by garfield69** [comment]
v0.21.1327
