### ISSUE TITLE
Search with accents not normalized

### ISSUE THREAD

**Issue by m6speed** [Jackett/Jackett#14905]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett v0.21.1096
```

### Description

Search is submit via API for title with accents, i.e. Fiancé and it takes it down to the point and effectively return 0 results as close to no files are named with accents despite of original name

Following https://github.com/Jackett/Jackett/issues/257 it should potentially work well and when search is submit for "Fiancé" Jackett searches for "Fiance"

If there's a configuration option to fix it please kindly share.

### Logged Error Messages

```text
none - just unexpected behavior.
```

**Comment by ilike2burnthing** [comment]
Depends on whether an indexer [supports raw search](https://github.com/search?q=repo%3AJackett%2FJackett%20rawsearch&type=code), as some trackers' searches break when using special or accented characters. If there's a specific indexer which you think should support raw search, let us know.

**Comment by m6speed** [comment]
It would be benefitial for most if default behavior would be to normalize names to non-accented version as 99% titles are shared that way. For those who want, it might be good to have unchecked by default option to turn on search with accents.
One could argue that when search comes via API from the likes of Sonarr, Radarr, Medusa, etc. it should be already normalized, though this is not the case and it would be best to have jackett helping with the search and normalizing (removing accents).

**Comment by ilike2burnthing** [comment]
Default is that raw search isn't supported/allowed, so *arrs will normalise the search keywords for almost all indexers.

This shouldn't be user customisable, as either the tracker supports it or it doesn't, so either the indexer supports it or it doesn't. If an indexer needs changing, this can be reported so as to benefit everyone.
