### ISSUE TITLE
[tvchaosuk] (testing) Exception (tvchaosuk): The response ended prematurely.: An error occurred while sending the request.

### ISSUE THREAD

**Issue by PureLoneWolf** [Jackett/Jackett#14901]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.0.69:8191
Using proxy: Disabled
App config/log directory: /config/Jackett
Running in Docker: Yes (image build: v0.21.1333-ls245)
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.1.64.0 (64bit OS) (64bit process)
Environment version: 6.0.25 (/app/Jackett/)
Starting Jackett v0.21.1344
```

### Description

In the last few days, Jackett can't connect to TVChaos as it is being told to relogin.  This happened in the last few days.  I have deleted and re-added the tracker but the same issue occurs.

I am probably being dense, so if there is something I can do to resolve it, I am more than happy to do so :)

Thanks

### Logged Error Messages

```text
2023-12-11 07:51:00.6943 Error Redirected to: https://tvchaosuk.com/login
2023-12-11 07:51:00.6969 Info CardigannIndexer(tvchaosuk): Relogin required
```

**Comment by garfield69** [comment]
The indexer is working for me so the issue appears to be at your end.
Turn on the enhanced logging and use your Jackett dashboard to edit the config and enter your credentials afresh and save.
If it works then try the test button to check all is well.
If you get a failure then provide the full log so we can take a look for errors or clues in the response.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by PureLoneWolf** [comment]
I think this is what's required :)

It is still failing.  I have a number of other trackers (albeit public ones) that are all testing and returning results normally.  This is the only private tracker.

I have also manually connected to the site with the same credentials and works as expected.  
[log.txt](https://github.com/Jackett/Jackett/files/13632597/log.txt)


Thank you

**Comment by garfield69** [comment]
Hmm. I see the web site sending Jackett the login page, and I see Jackett sending to the web site the post with your credentials, and then I see the error: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The response ended prematurely.

It looks like something has interrupted coms, which smacks of something blocking access.
I see you're a docker user.

When you say you manually connected, are you using a browser from the same device and IP, using the same DNS, or from a different machine?

ilike2burnthing have you suggestions?

**Comment by ilike2burnthing** [comment]
May be the IP address is blocked, try changing the server. Closing as not a Jackett issue.
