### ISSUE TITLE
[req]: Why not use brew to install?

### ISSUE THREAD

**Issue by LostAccount** [Jackett/Jackett#14906]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I couldn't install on to Ubuntu 22.04 using your recommended steps.

### Describe the solution you'd like

Recommending you consider providing brew as an installation method.

### Describe alternatives you've considered

I used `brew install jackett` (requires [brew](https://brew.sh/) be installed as a prerequisite) and after installation the shell recommended I run `brew services start jackett` to start the service. Worked on Ubuntu 22.04. Cheers!

**Comment by garfield69** [comment]
v0.21.1366
