### ISSUE TITLE
HDChina down

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#14908]
![download](https://github.com/Jackett/Jackett/assets/2883468/326db514-1271-4968-b378-002cd899f728)
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP client: HttpWebClient
FlareSolverr
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits
```

### Description

Site https://hdchina.org/ is down.

### Logged Error Messages

```text
See above.
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/141
