### ISSUE TITLE
[TorrentWhiz] offline

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#14909]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP client: HttpWebClient
FlareSolverr
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits
```

### Description

Site https://torrentwiz63.com is down: 

This site can’t be reachedThe webpage at https://torrentwiz63.com/ might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED

### Logged Error Messages

```text
Anyhow:
Here it is said that site is working: https://www.websitenotworking.com/torrentwiz63.com
According to uptrends (https://www.uptrends.com/tools/uptime): "TCP Connections failed"
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/6633a4ec6eb824bda262cfb8c7982a6a6f926f18

**Comment by garfield69** [comment]
https://torrentwiz66.com/ Error 522 The tracker seems to be down. (http timeout)

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14909#issuecomment-1986739378

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14909#issuecomment-1986739378

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14909#issuecomment-1986739378

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/14909#issuecomment-1986739378

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://torrentwiz67.com/ Connection timed out Error code 522

**Comment by garfield69** [comment]
v0.22.946
