### ISSUE TITLE
[zmpt] (updating) Login Failed, got redirected to: https://www.baidu.com/ Try changing the indexer URL to https://www.baidu.com/.

### ISSUE THREAD

**Issue by Magic-riding** [Jackett/Jackett#14918]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Login Failed, got redirected to: https://www.baidu.com/ Try changing the indexer URL to https://www.baidu.com/.
```

### Description

zmpt changed the login mode to passkey login, and passkey is unique.  If you do not use the specified web page link to access, otherwise you can only jump to baidu.com.  The link contains the user's passkey, and direct access to the link can be accessed without login.
Take the link below for example:
https://zmpt.cc/9b****************************98/{passkey}
Due to the nature of the site, I can't post the full link.

### Logged Error Messages

```text
no
```

### Screenshots

no

**Comment by ilike2burnthing** [comment]
[v0.21.1422](https://github.com/Jackett/Jackett/releases/v0.21.1422)
