### ISSUE TITLE
[REQ] Allow option to disable XXX category in jackett.

### ISSUE THREAD

**Issue by Rishabh145** [Jackett/Jackett#1492]
I think the title sums it all up, *this a feature request, not an issue*. A lot of time results from XXX categories are returned when searching without specifying a category. I would like to prevent Jackett from displaying any results from that category.
I would love it if this feature is implemented.

**Comment by chrisjohnson00** [comment]
Agreed... I'm only interested in 1, maybe 2 categories from a site and would like to disable the other 50+ categories to reduce memory footprint and chances of a release being missed when refreshing.

**Comment by kaso17** [comment]
#1262 is the more generic feature request than this (allow to select multiple categories)

**Comment by garfield69** [comment]
Closing as stale.
