### ISSUE TITLE
[nocensor] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14936]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

the nocensor.cloud proxy service is offline

### Logged Error Messages

https://nocensor.cloud/ DNS Lookup Error

anyone know what the new domain is?

### Affected indexers
https://badasstorrents.nocensor.cloud/
https://bitsearch.nocensor.cloud/
https://demonoid.nocensor.cloud/
https://erairaws.nocensor.cloud/
https://extratorrent.nocensor.cloud/
https://eztv.nocensor.cloud/
https://gktorrent.nocensor.cloud/
https://glotorrents.nocensor.cloud/
https://ilcorsaronero.nocensor.cloud/
https://limetorrents.nocensor.cloud/
https://nyaa.nocensor.cloud/
https://rutor.nocensor.cloud/
https://solidtorrents.nocensor.cloud/
https://subsplease.nocensor.cloud/
https://tokyotosho.nocensor.cloud/
https://torlock.nocensor.cloud/
https://torrent9.nocensor.cloud/
https://torrentdownload.nocensor.cloud/
https://torrentdownloads.nocensor.cloud/
https://torrentfunk.nocensor.cloud/
https://torrentz2.nocensor.cloud/
https://yourbittorrent.nocensor.cloud/
https://yts.nocensor.cloud/
https://zetorrents.nocensor.cloud/

**Comment by ilike2burnthing** [comment]
Reported as down to https://unblocksource.re/ but no word back. Can replace with one of their other options, drop, or give them another couple of weeks.

**Comment by garfield69** [comment]
lets wait 30d then replace with any unblocksource domains that work.

**Comment by garfield69** [comment]
any idea where unblocksource  has moved to?

**Comment by ilike2burnthing** [comment]
No luck here. Their [Twitter](https://twitter.com/unblocksource) and [Telegram](https://t.me/s/unblocksource) look to be abandoned.

The mrunblock.bond proxies were also from there and are dead too. Time to give up hope on them?

**Comment by garfield69** [comment]
yup

**Comment by ekeekek1** [comment]
I would like to pay you to fix the problem for my site. Do you have an email or Telegram account?

**Comment by ilike2burnthing** [comment]
If this is related to Jackett, we provide support for free. If not, you'll have to look elsewhere.
