### ISSUE TITLE
[req]: KIMOJI

### ISSUE THREAD

**Issue by Ethan930717** [Jackett/Jackett#14934]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: KIMOJI
- URL: https://kimoji.club/
- Description: KIMOJI is a CHINESE Private Torrent Tracker for MUSIC
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MST 72hrs, Global MR 1.0
- Additional Comments: 
Engine: UNIT3D 7.1.3 (custom)
Invite Only
```

**Comment by garfield69** [comment]
IF you have an invite let us know.
Otherwise please provide a HTML dump of the torrents search page and we should be create an indexer for this site.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by Ethan930717** [comment]
> IF you have an invite let us know.
> 
> Otherwise please provide a HTML dump of the torrents search page and we should be able to create an indexer for this site.
> 
> See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

I have the invitation rights for this site. Which email address do I need to send it to?

**Comment by garfield69** [comment]
@ilike2burnthing  do you want this one?

**Comment by ilike2burnthing** [comment]
Sure.

@Ethan930717 send to `jacketttest [AT] gmail [DOT] com` please.

**Comment by garfield69** [comment]
v0.21.1461

**Comment by garfield69** [comment]
https://kimoji.club/ Domain expired landing page

**Comment by garfield69** [comment]
@Ethan930717  do you have any info on the status of kimoji, is the site GONE, BROKEN or moved you a new DOMAIN?
I'll be removing the indexer after a week has passed if we do not get news.

**Comment by Ethan930717** [comment]
Yes, I have stopped operating this site. Please remove it from Jackett’s supported list.

**Comment by garfield69** [comment]
v0.22.946
