### ISSUE TITLE
[yggtorrent] (testing) Test search in YGGtorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by PierreAlexx** [Jackett/Jackett#14930]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
win10
```

### Description

yggtorrent not working help

### Logged Error Messages

```text
yggtorrent not working
```

### Screenshots

 o

**Comment by ilike2burnthing** [comment]
As requested when opening your issue:

> Please provide the details of the system Jackett is running on. The best way to do this is to restart Jackett, access the dashboard, view the log, and copy/paste the last 10 Info lines at the bottom of the log.

Also provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
Hi @PierreAlexx ,

No response has been received for 7 days. To prevent issue tracker clutter, this issue will now be closed. To re-open the issue, please provide the information requested and the issue will automatically re-open.
