### ISSUE TITLE
JackettTray.exe infected with Trojan?

### ISSUE THREAD

**Issue by carrsteven** [Jackett/Jackett#14937]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Starting Jackett v0.21.1451
Environment version: 6.0.25 (C:\ProgramData\Jackett\)
OS version: Microsoft Windows NT 10.0.22631.0 (64bit OS)
Jackett variant: CoreWindows
Running in Docker: No
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
App config/log directory: C:\ProgramData\Jackett
Using proxy: Disabled
Using FlareSolverr: No
Using HTTP Client: HttpWebClient2
```

### Description

After most recent update, Windows Defender reporting JackettTray.exe infected with Trojan:Win64/Dridex!pz

### Logged Error Messages

```text
N/A
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/29719321/e99c5f6d-f62e-493c-97bb-8411ef878c8b)

**Comment by garfield69** [comment]
Fairly confident this is a false hit.
I have passed 0.21.1451 through virustotal and it reported No security vendors and no sandboxes flagged this file as malicious from its 60 vendors.
https://www.virustotal.com/gui/file/34e3f49db2c977dc92f3cfe4224630dded2309fc3756cf898602d801b076afa1
scanned jackettTray separately too
https://www.virustotal.com/gui/file/d9d032075d1b5366909db445aacf0e271494ca8db74aac2d479e14083cb21c5a
