### ISSUE TITLE
Beware Jackett customers: the Jackett uninstaller contains malware!

### ISSUE THREAD

**Issue by G-e-V-e** [Jackett/Jackett#14935]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Win10 64bit
```

### Description

Installed it
Did some search tests which found 0 hits
Uninstalled it => virusscanner alert: IDP.generic in C:\ProgramData\Jackett\JackettConsole.exe => quarantine

So this is how you thank your customers?

### Logged Error Messages

```text
Nothing
```

### Screenshots

Nothing

**Comment by garfield69** [comment]
This is very likely a false hit that occurs from time to time.
I have passed the latest windows built to the virus total site for scanning and it reported that No security vendors flagged this URL as malicious

Of the 91 checks just one did flag as suspicious the others gave it the all clear.

https://www.virustotal.com/gui/url/a8d31f1d84425788692765bd3522e92c2ec5c69b81771b443dd0e98ad934a14a?nocache=1

**Comment by ilike2burnthing** [comment]
1. Jackett users are not 'customers'
2. JackettConsole.exe isn't the uninstaller
3. It's clean - https://www.virustotal.com/gui/file/272ec4859d69f81e707b7b7e18873dae42762755a7b4b105b5474a8bbd580b16
4. Get a better AV than Avast/AVG
5. Something is very wrong if you're getting no results
