### ISSUE TITLE
[req]: RARBG Dump Index

### ISSUE THREAD

**Issue by joaquinito2070** [Jackett/Jackett#14945]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: RARBG Dump Index
- URL: https://rarbg-proxy.xeqhjstsc.workers.dev/
- Description: Search anything from the dead RARBG (R.I.P) website's dump (5,714TB) and get WORKING MAGNET LINKS.
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments:
```

**Comment by ilike2burnthing** [comment]
Already available on TheRARBG.
