### ISSUE TITLE
[req]: New and renamed categories for PornolabNet (2024 year update)

### ISSUE THREAD

**Issue by TheMiracleExpress** [Jackett/Jackett#14949]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

New categories has been added to PornoLab tracker:

Сайтрипы 2024 (HD Video) / SiteRip's 2024 (HD Video)   (new id is 1867)
Сайтрипы 2024 / SiteRip's 2024 ( new id is 1868)

Following categories were renamed:

Сайтрипы с русскими актрисами 2016-2023 (HD Video) / Rus..    (existing id is 1831)
to
Сайтрипы с русскими актрисами 2016-2024 (HD Video) / Rus..   (existing id is 1831)

Сайтрипы с русскими актрисами 2016-2023 / Russian SiteRi..     (existing id is 1803)
to
Сайтрипы с русскими актрисами 2016-2024 / Russian SiteRi..     (existing id is 1803)

### Describe the solution you'd like

Add new 2024 year categories
Rename existing categories to include 2024 year releases

**Comment by garfield69** [comment]
v0.21.1491
