### ISSUE TITLE
[req]: Add MagnetDL indexer support https://www.magnetdl.com/

### ISSUE THREAD

**Issue by RileyXX** [Jackett/Jackett#14942]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: MagnetDL
- URL: https://www.magnetdl.com/
- Description: MagnetDL is a public torrent tracker for Software, Movies, Games, E-Books, TV Shows, Music & more.
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): None/Public Tracker
- Additional Comments: 
Saw this indexer mentioned on Reddit https://www.reddit.com/r/Piracy/comments/17sacnn/comment/k8on375/?utm_source=reddit&utm_medium=web2x&context=3. "Long running site with lots of unique uploads, not just mirrored stuff." Would be nice to see this indexer supported by Jackett.
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/pull/10347

**Comment by RileyXX** [comment]
> #10347

Oh thanks I tried searching issues but couldn't find it. That sucks hopefully it can be added at some point.

**Comment by ilike2burnthing** [comment]
It's been over 3yrs, it won't be.

**Comment by RileyXX** [comment]
If I'm reading everything correctly the indexer can't be added because the site owner requested it be removed for too much traffic load? If it's been 3 years a lot has changed with automated software perhaps it would be a good time to try readding it.

**Comment by ilike2burnthing** [comment]
I suggest re-reading. It was left in the hands of the owner to contact us if they wanted support re-added for their sites. It's been over 3yrs, they haven't contacted us, it's not being re-added.

**Comment by RileyXX** [comment]
I think we should add MagnetDL support regardless of what the owners of the indexer say. You gave them 3 years to add a latest 100 feed so it looks like it's not happening.

Otherwise we might as well just create a fork with added support and let the users decide if they want to use it.

**Comment by ilike2burnthing** [comment]
No, that would be a dick thing to do.
