### ISSUE TITLE
BTDigg no longer listed as an indexer in Jackett?

### ISSUE THREAD

**Issue by RileyXX** [Jackett/Jackett#14941]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: BTDigg
- URL: btdig.com
```

I noticed recently BTDigg is no longer included in the list of indexers in Jackett. Is this intentional? Was this indexer removed for some reason in the past few months? I searched release notes over the past 6 months and didn't find any mention of it. I liked this indexer because it had some stuff that wasn't listed elsewhere.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/4907#issuecomment-1732111785

> - [X] I have checked older issues, open and closed

If you're going to tick it, do it.

**Comment by RileyXX** [comment]
> [#4907 (comment)](https://github.com/Jackett/Jackett/issues/4907#issuecomment-1732111785)
> 
> > * [x]  I have checked older issues, open and closed
> 
> If you're going to tick it, do it.

Thanks for linking that. I did search for it and even skimmed through that thread but didn't see the comment for why it was removed. Just assumed it was an unrelated/outdated thread.
