### ISSUE TITLE
[torrentqq] (testing) Exception (torrentqq): Il messaggio ricevuto era imprevisto o con formattazione scorretta.: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by p060477** [Jackett/Jackett#14958]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
An error occurred while testing this indexer
Exception (torrentqq): Il messaggio ricevuto era imprevisto o con formattazione scorretta.: The SSL connection could not be established, see inner exception.
```

### Description

 An error occurred while testing this indexer
Exception (torrentqq): Il messaggio ricevuto era imprevisto o con formattazione scorretta.: The SSL connection could not be established, see inner exception.

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (torrentqq): Il messaggio ricevuto era imprevisto o con formattazione scorretta.: The SSL connection could not be established, see inner exception.
```

**Comment by ilike2burnthing** [comment]
Site URL has been updated to https://torrentqq290.com/ in https://github.com/Jackett/Jackett/commit/fd93c24ab31de6fbf9bec77b84cbafa9ca7d6d7f. Until the next release you'll need to change this manually.

If you still have issues, follow the troubleshooting steps here:
- https://github.com/Jackett/Jackett/wiki/Troubleshooting/#connection-reset-by-peer-the-ssl-connection-could-not-be-established
- https://github.com/Jackett/Jackett/wiki/TroubleShooting#a-connection-attempt-failed

**Comment by p060477** [comment]
fine this is solved!
thxs for helping and patience too!!
cheers!
