### ISSUE TITLE
[torrent9clone] (testing) Test search in Torrent9 clone => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by p060477** [Jackett/Jackett#14959]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
An error occurred while testing this indexer
Test search in Torrent9 clone => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
```

### Description

 An error occurred while testing this indexer
Test search in Torrent9 clone => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in Torrent9 clone => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14961
