### ISSUE TITLE
Jackett is binding to IPv6 despite there being no v6 address in docker container

### ISSUE THREAD

**Issue by imro2** [Jackett/Jackett#14963]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
jackett  | 01-07 14:16:23 Info Starting Jackett v0.21.1510
jackett  | 01-07 14:16:25 Info Environment version: 6.0.25 (/app/Jackett/)
jackett  | 01-07 14:16:26 Info OS version: Unix 4.4.302.0 (64bit OS) (64bit process)
jackett  | 01-07 14:16:26 Info Jackett variant: CoreLinuxMuslAmdx64
jackett  | 01-07 14:16:26 Info File /etc/issue: Welcome to Alpine Linux 3.18
jackett  | 01-07 14:16:26 Info Running in Docker: Yes (image build: v0.21.1510-ls270)
jackett  | 01-07 14:16:26 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
jackett  | 01-07 14:16:26 Info App config/log directory: /config/Jackett
jackett  | 01-07 14:16:26 Info Using proxy: Disabled
jackett  | 01-07 14:16:26 Info Using FlareSolverr: No
jackett  | 01-07 14:16:26 Info Using HTTP Client: HttpWebClient2
```

### Description

No matter what I try to do, jackett running in a docker container binds to ipv6. The container has no ipv6 addresses.

```
docker-compose exec -ti jackett bash
root@9356a51ba43a:/# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0
3: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN qlen 500
    link/[65534]
    inet 172.21.24.138/23 scope global tun0
       valid_lft forever preferred_lft forever
28897: eth0@if28898: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether xx:xx:xx:1d:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.29.0.2/16 brd 172.29.255.255 scope global eth0
       valid_lft forever preferred_lft forever
root@9356a51ba43a:/# netstat -l | grep 9117
tcp        0      0 :::9117                 :::*                    LISTEN
```

I added the recommended `--sysctl net.ipv6.conf.all.disable_ipv6=1` to no avail. I am not sure if me running Docker on Synology has anything to do with it, but I would expect there to be an easier way to force jackett not to use ipv6.

### Logged Error Messages

```text
jackett  | Hosting environment: Production
jackett  | Content root path: /app/Jackett/Content
jackett  | Now listening on: http://[::]:9117
jackett  | Application started. Press Ctrl+C to shut down.
jackett  | [ls.io-init] done.
```

**Comment by imro2** [comment]
Further troubleshooting:

I checked all `disable_ipv6 ` settings according to [alpine wiki](https://wiki.alpinelinux.org/wiki/Sysctl.conf)
```
root@9356a51ba43a:/# sysctl -a | grep disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.sit0.disable_ipv6 = 1
net.ipv6.conf.tun0.disable_ipv6 = 1
```
I modified `/app/Jackett/jackett.runtimeconfig.json` according to https://github.com/Jackett/Jackett/issues/11224#issuecomment-1659356083 and [.NET Runtime configuration settings](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/) so it looks like this:
```

  "runtimeOptions": {
    "tfm": "net6.0",
    "includedFrameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "6.0.25"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "6.0.25"
      }
    ],
    "configProperties": {
      "System.Net.DisableIPv6": true,
      "System.GC.Server": false,
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
    }
  }
}
```

I added environmental variable `DOTNET_SYSTEM_NET_DISABLEIPV6=1` according to https://devblogs.microsoft.com/dotnet/dotnet-6-networking-improvements/

None of that helped. Jackett still starts with `Now listening on: http://[::]:9117`

**Comment by ilike2burnthing** [comment]
Do you just mean because the log shows `Now listening on: http://[::]:9117` or are you having problems accessing/using Jackett?

If the former, that's been the case on Linux since at least 2018 - https://github.com/Jackett/Jackett/issues/3330

**Comment by imro2** [comment]
> If the former, that's been the case on Linux since at least 2018 - #3330

Oh my, I spent hours trying to troubleshoot this. At first I started looking into because I was not able to access jackett via traefik, so I got anchored on the ipv6. The problem it is not just the log. If I do `netstat -l` it shows that jackett is actually listening on ipv6 interface. Anyway, this is a non issue, closing.

**Comment by imro2** [comment]
If anybody for some reason actually needs to force Jackett to listen on IPv4 only, the only way I found it to work was using the solution in #6278 

In my case it turned out to be unnecessary. Just leaving it here for future researchers.
