### ISSUE TITLE
[proporno] (testing) Test search in ProPorno => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by p060477** [Jackett/Jackett#14960]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.21.1504
```

### Description

An error occurred while testing this indexer
Test search in ProPorno => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in ProPorno => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
```

**Comment by ilike2burnthing** [comment]
Currently no results for 2024, so keywordless search won't work, but category is missing for keyword search results, so will need to update indexer.
