### ISSUE TITLE
Public trackers?

### ISSUE THREAD

**Issue by vitriolvm** [Jackett/Jackett#1496]
Hi, I'm sorry but looks like I'm unable to figure out what I am missing: on the main age of this project, just above the listing of all the supported private trackers, there is a list of public trackers. I've installed Jackett on my Synology NAS but I don't see any of the supported public trackers and no search gives results since I don't have an account for any of the private trackers.

What am I missing?

Thanks!

**Comment by Saltystew** [comment]
Click add indexer and sort by type, if it has a green lock its public.

**Comment by vitriolvm** [comment]
There were no locks icons, I forced an update check and voilà: brand new version with plenty of public trackers. Thanks
