### ISSUE TITLE
[btsow] (testing) Test search in BTSOW => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by p060477** [Jackett/Jackett#14967]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
this domain is on sale...why is included as indexer...??   -> ...BUG....
```

### Description

this domain is on sale...why is included as indexer...??   -> ...BUG....

### Logged Error Messages

```text
this domain is on sale...why is included as indexer...??   -> ...BUG....
```

### Screenshots

this domain is on sale...why is included as indexer...??   -> ...BUG....

**Comment by ilike2burnthing** [comment]
Are you referring to https://btsow.motorcycles/ ? It's working fine here.

If it's a different URL, there's an issue with your Jackett setup.

If that's the correct URL but showing as for sale for you, there's a much bigger issue on your end.

**Comment by p060477** [comment]
01-08 23:43:10 Info Starting Jackett v0.21.1519
01-08 23:43:13 Info Environment version: 6.0.25 (G:\back up 29.04.2010\C\Documents and Settings\Administrator\Dati applicazioni\JACKETT\Jackett 0.18.875\)
01-08 23:43:13 Info OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
01-08 23:43:13 Info Jackett variant: CoreWindows
01-08 23:43:13 Info Running in Docker: No
01-08 23:43:13 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
01-08 23:43:13 Info App config/log directory: C:\ProgramData\Jackett
01-08 23:43:13 Info Using proxy: Disabled
01-08 23:43:13 Info Using FlareSolverr: http://192.168.2.3:8191
01-08 23:43:13 Info Using HTTP Client: HttpWebClient2
01-08 23:43:13 Info Loading Native indexers ...
01-08 23:43:13 Info Loaded 73 Native indexers.
01-08 23:43:14 Info Loading Cardigann indexers from: C:\ProgramData\Jackett\cardigann\definitions\, G:\back up 29.04.2010\C\Documents and Settings\Administrator\Dati applicazioni\JACKETT\Jackett 0.18.875\Definitions


the url , but you should have to know it by yrself.., is:
https://btsow.cam/

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14961
