### ISSUE TITLE
[cinecalidad] (testing) Test search in Cinecalidad => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by p060477** [Jackett/Jackett#14968]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
this domain is on sale...why is included as indexer...??   -> ...BUG....
```

### Description

this domain is on sale...why is included as indexer...??   -> ...BUG....

### Logged Error Messages

```text
this domain is on sale...why is included as indexer...??   -> ...BUG....
```

**Comment by ilike2burnthing** [comment]
Are you referring to https://cinecalidad.fi/ ? It's working fine here.

If it's a different URL, there's an issue with your Jackett setup.

If that's the correct URL but showing as for sale for you, there's a much bigger issue on your end.

**Comment by p060477** [comment]
this is ther url:
https://www.cinecalidad.is/

i'm not setting  it by myself...i only copy past what jackett has on its own...

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14961
