### ISSUE TITLE
[gktorrent] (testing) Test search in GkTorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by p060477** [Jackett/Jackett#14969]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
see screenshoot...which kind of indexer is this...??.. -> BUG.....
```

### Description

see screenshoot

### Logged Error Messages

```text
see screenshoot
```

### Screenshots

[url=https://postimg.cc/XrT35bND][img]https://i.postimg.cc/XrT35bND/Imagine.jpg[/img][/url]

**Comment by p060477** [comment]
[url=https://postimg.cc/BtM0gDQF][img]https://i.postimg.cc/BtM0gDQF/Imagine.png[/img][/url]

this is the proof the indexer is bugged

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14961

**Comment by p060477** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/1034#issue-2070796844
