### ISSUE TITLE
[postman] (testing) Exception (postman): Host sconosciuto.: Host sconosciuto. (tracker2.postman.i2p:80)

### ISSUE THREAD

**Issue by p060477** [Jackett/Jackett#14973]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
this indexer has no web page at all -> BUG
```

### Description

this indexer has no web page at all -> BUG

### Logged Error Messages

```text
this indexer has no web page at all -> BUG
```

**Comment by ilike2burnthing** [comment]
I2P is required to access that tracker.

**Comment by p060477** [comment]
i do have also I2P:
I2PdBrowserPortable_1.3.3

![I2P](https://github.com/Jackett/Jackett/assets/12773559/8da8326a-91f3-4ae4-b874-f38248e35349)


...so what have i to do to finally have this indexer fine working in Jackett...??

**Comment by ilike2burnthing** [comment]
Jackett needs to be using I2P, not just the browser you're accessing Jackett in - https://geti2p.net/en/download

**Comment by p060477** [comment]
...i have also that...: 

![I2P 2 4 0 ](https://github.com/Jackett/Jackett/assets/12773559/63549cf7-9610-4ee3-8ebf-86f48cf19524)


so how to...??....

**Comment by ilike2burnthing** [comment]
Have you configured Jackett to use an `HTTP` proxy with the URL `127.0.0.1` on port `4444` (obviously while I2P is running)?

Are you able to access http://tracker2.postman.i2p/ in the I2P Firefox browser?

**Comment by p060477** [comment]
here it is the proof ...:

![postman](https://github.com/Jackett/Jackett/assets/12773559/b1581c55-c91d-4da7-86df-92a43314e9c8)

**Comment by ilike2burnthing** [comment]
I2P can be very slow, and I got a few timeouts for that site when testing earlier, in browser and Jackett. Retry a few times. Leave it a while and try again later.

**Comment by p060477** [comment]
but when doing those new tests i should have to reput proxy http 127.0.0.1 and port 4444 in jackett am i wrong..??..i ask cause for doing the other tests you ask me to delete that impostation in jackett...

**Comment by ilike2burnthing** [comment]
Yes.

The errors you were getting for the other indexers were because I2P was unreachable, I was removing an unnecessary variable.

So long as I2P is working, you can use the proxy, though things will be much slower.

**Comment by p060477** [comment]
test postman passed!! 
so now i ask a very stupid thing but this is my poor level...:
now this postman indexer works but only with proxy 127.0.0.1 port 4444 in jackett...so if i want to do a single search on it no problem but if i'd like a manual search on all the indexers...??...maybe the above mentioned proxy settings in jackett may let them not work at all..or at least if you do the modificastion you write maybe but very very slow...so when i do a manual search on all of them should be better to delete thoise proxy settings (I2P) in jackett...??
and another silly question:
if i do a single search on postman indexer,so having those proxy settings, and i find a torrent file to download...then i should have to give it to an I2P torrent client...??...as for ex:  XD-i2p-v0.4.4-windows.exe...??...
or that file is suitable also for normal client as utorent or qbittorrent...??
apologize my very poor level...
thxs in adv
cheers

**Comment by ilike2burnthing** [comment]
Again, other indexers work with the I2P proxy, but will be very slow. If you insist on having Postman added as an indexer but are rarely going to use it, just leave the proxy set to disabled and then switch to HTTP when you need to use Postman.

The trackers for torrents from Postman are all I2P trackers, yes, so you'd need a torrent client which supports it (supposedly qBittorrent supports it, but I haven't tried, you'd have to work that out yourself).

Or you could just not use the tracker and save yourself a lot of effort.

**Comment by p060477** [comment]
thxs so much indeed for yr kind helping
and sweet patience too
cheers
