### ISSUE TITLE
Error testing 1377x in jackett

### ISSUE THREAD

**Issue by jblesa** [Jackett/Jackett#14978]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2	
Using FlareSolverr: No
Using proxy: Disabled	
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No	
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
Environment version: 6.0.26 (C:\ProgramData\Jackett\)	
Starting Jackett v0.21.1536
```

### Description

Testing the 1377x server in Jackett appears an error

### Logged Error Messages

```text
[1337x] (testing) Exception (1337x): certificate validation failed: [Subject]  CN=1337x.to[Issuer]  CN="allot.com/emailAddress=info@allot.com", OU=Allot, O=Allot, L=Madrid, S=Madrid, C=ES[Serial Number]  37C50A65000000000C01000000000000[Not Before]  12/16/2016 2:07:49 PM[Not After]  12/16/2026 2:07:49 PM[Thumbprint]  7F6071B9658B55FC83D61C9A31ED6B1FF26090E7: The SSL connection could not be established, see inner exception.
```

**Comment by garfield69** [comment]
You are being blocked by your ISP and routed to a black hole with an invalid CA from Allot madrid.
Try using your jackett dashboard to edit the 1337x config and select each of the alternate sitelinks to see if any of them work for you.
Alternatively try switching your router or PC to using a public DNS service such as cloudflare's 1.1.1.1 or Googles 8.8.8.8
or use a VPN.
