### ISSUE TITLE
Startup probe failed: dial tcp XXXXX:9117: connect: connection refused

### ISSUE THREAD

**Issue by rpetion** [Jackett/Jackett#14979]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
OS: TrueNAS-SCALE-23.10.1

Jackett Version: v0.21.1155
Chart Version: 18.1.5

Are you using a proxy or VPN? no
```

### Description

Hi,

I installed jackett of true chart catalog. but this status is "Deploying"

**### My ix-value.yaml :** 
```
image:
  repository: ghcr.io/linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: 0.21.1155@sha256:5c408d64cb2385a3ee2934c8a5773eaadd5cd114e6b338328d60ab964ec0c88c
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/UI/Login"
            readiness:
              path: "/UI/Login"
            startup:
              path: "/UI/Login"
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
```
Thanks for help.

Regards.

### Logged Error Messages

```text
i've this message: 
2024-01-10 06:02:03**Startup probe failed: dial tcp 172.16.0.127:9117: connect: connection refused**
2024-01-10 06:01:51Started container jackett
2024-01-10 06:01:49Created container jackett
2024-01-10 06:01:42Container image "ghcr.io/linuxserver/jackett:0.21.1155@sha256:5c408d64cb2385a3ee2934c8a5773eaadd5cd114e6b338328d60ab964ec0c88c" already present on machine
2024-01-10 06:01:40Add net1 [192.168.1.84/24] from ix-jackett/ix-jackett-0
2024-01-10 06:01:33Add eth0 [172.16.0.127/16] from ix-net
```

**Comment by garfield69** [comment]
from a browser on your LAN can you access http://192.168.1.84:9117 ?
from same browser can you access the WAN address  http://172.x.x.x:9117 ?

**Comment by ilike2burnthing** [comment]
`172.16.x.x` is just for Docker, they won't be able to access it in browser.

Looks to be a [semi-common issue](https://github.com/truecharts/charts/issues?q=Startup+probe+failed%3A+dial+tcp+connect%3A+connection+refused), with the advice being to open a support ticket on their [Discord](https://github.com/truecharts/charts#contact-and-support).
