### ISSUE TITLE
Windows Defender flagging Jackett as Trojan

### ISSUE THREAD

**Issue by Luigialberto04** [Jackett/Jackett#14976]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Starting Jackett v0.21.1239
Environment version: 6.0.25 (C:\ProgramData\Jackett\)
OS version: Microsoft Windows NT 10.0.22631.0 (64bit OS)
Jackett variant: CoreWindows
Running in Docker: No
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
App config/log directory: C:\ProgramData\Jackett
Using proxy: Disabled
Using FlareSolverr: No
Using HTTP Client: HttpWebClient2
```

### Description

Windows Defender flagged JackettTray.exe and other files infected with trojan:O97M/Madeba!pz. False positive?

### Logged Error Messages

```text
N/A
```

### Screenshots

![Screenshot (45)](https://github.com/Jackett/Jackett/assets/125083536/2d7b0e32-88d0-4494-9ae7-15529b970d40)
![Screenshot (46)](https://github.com/Jackett/Jackett/assets/125083536/5e94e9bb-ba49-42dd-9855-0d3fe3661635)
![Screenshot (47)](https://github.com/Jackett/Jackett/assets/125083536/6c28f3c3-8b81-4439-af74-5847dac7d2b9)

**Comment by garfield69** [comment]
Yes, very likely a false positive.
I've passed JackettTray.exe and the complete windows builds (the zip and the exe) for v0.21.1529 through VirusTotal and got the green light on them all.

https://www.virustotal.com/gui/file/5412f1b72fc739db42b2b745a51bb2c542a7a4cb69e31075212e25c373fe657b
https://www.virustotal.com/gui/file/00713d74962d05f097da85efbc6834e821e347eefaf769c345e91e928de2cd4f
https://www.virustotal.com/gui/file/34a43dac0fb4bbd3f5399b1b7ecfd1ad63cd9ba4dac73237daf35786cc242e05
