### ISSUE TITLE
[MacOS] Error When Trying to Install on M1 MacBook Air (OSStatus error 99999.)

### ISSUE THREAD

**Issue by rmcguinn** [Jackett/Jackett#14975]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Running MacOS Sonoma 14.1.1 on an M1 Air
Using the latest Jackett.Binaries.macOS.tar.gz
```

### Description

Have never used Jackett before. Was trying to set it up for the first time. 

Downloaded the latest Jackett.Binaries.macOS.tar.gz. Extracted it, right clicked on install_service_macOS and clicked open. Which then shows a warning message that MacOS cannot verify the developer of Jackett. 

<img width="287" alt="SCR-20240108-uhql" src="https://github.com/Jackett/Jackett/assets/32882503/2e883fb6-0078-4ec8-be06-a98e2e7d5139">

Click Open anyways, then get presented with an error Message "The operation couldn't be completed. (OSStatus error 99999.)"

<img width="400" alt="SCR-20240108-ubik" src="https://github.com/Jackett/Jackett/assets/32882503/b0947f65-0287-4184-9fe1-c428eeecf85f">

Am not able to continue with installation due to this. I've installed plenty of other 3rd party apps in the past without issue. Some research online indicates error code 99999 could have something to do with a corrupted Gatekeeper in MacOS. But I haven't had issues with other similar programs. 

### Logged Error Messages

```text
The operation couldn't be completed. (OSStatus error 99999.)
```

**Comment by garfield69** [comment]
I presume your research lead you to https://softwaretested.com/mac/how-to-fix-osstatus-error-99999-on-mac/ and hence the gatekeeper conflict.
I suggest that you try installing docker and using a jackett docker image.

**Comment by rmcguinn** [comment]
> I presume your research lead you to https://softwaretested.com/mac/how-to-fix-osstatus-error-99999-on-mac/ and hence the gatekeeper conflict. I suggest that you try installing docker and using a jackett docker image.

Yup exactly the link I came across. Sounds good. I'll look more into it tomorrow and comment if that does the trick.
