### ISSUE TITLE
[proporno] (testing) Test search in ProPorno => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by p060477** [Jackett/Jackett#14971]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
site on sale....
https://proporno.org/
BUG
```

### Description

site on sale....
https://proporno.org/
BUG

### Logged Error Messages

```text
site on sale....
https://proporno.org/
BUG
```

**Comment by p060477** [comment]
site on sale....
https://proporno.org/
BUG

**Comment by ilike2burnthing** [comment]
Working fine here. If you're still have this problem, reopen by providing an enhanced log and the requested environment information - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by p060477** [comment]
i gave you here what you need...
https://github.com/FlareSolverr/FlareSolverr/issues/1034#issue-2070796844

**Comment by ilike2burnthing** [comment]
That has nothing to do with this potential issue. Provide the information requested.

**Comment by p060477** [comment]
**there is -all- my enviroment**...infact up to now is still UNSOLVED.....
https://github.com/FlareSolverr/FlareSolverr/issues/1034#issue-2070796844

**Comment by ilike2burnthing** [comment]
No, it's not. There's also no enhanced Jackett log as requested.

If you just follow simple instruction we might actually be able to solve your issues rather than going round in circles with you arguing for no reason.

**Comment by p060477** [comment]
01-08 23:43:10 Info Starting Jackett v0.21.1519
01-08 23:43:13 Info Environment version: 6.0.25 (G:\back up 29.04.2010\C\Documents and Settings\Administrator\Dati applicazioni\JACKETT\Jackett 0.18.875\)
01-08 23:43:13 Info OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
01-08 23:43:13 Info Jackett variant: CoreWindows
01-08 23:43:13 Info Running in Docker: No
01-08 23:43:13 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
01-08 23:43:13 Info App config/log directory: C:\ProgramData\Jackett
01-08 23:43:13 Info Using proxy: Disabled
01-08 23:43:13 Info Using FlareSolverr: http://192.168.2.3:8191
01-08 23:43:13 Info Using HTTP Client: HttpWebClient2
01-08 23:43:13 Info Loading Native indexers ...
01-08 23:43:13 Info Loaded 73 Native indexers.
01-08 23:43:14 Info Loading Cardigann indexers from: C:\ProgramData\Jackett\cardigann\definitions\, G:\back up 29.04.2010\C\Documents and Settings\Administrator\Dati applicazioni\JACKETT\Jackett 0.18.875\Definitions

**Comment by ilike2burnthing** [comment]
Once you have followed the instructions in https://github.com/Jackett/Jackett/issues/14961#issuecomment-1881956039, provide an enhanced log as requested.

A reminder from https://github.com/Jackett/Jackett/issues/14960#issuecomment-1880190387, the default search (the current year) will fail for now as there are no results with `2024` in the title, so instead provide an enhanced log for a search (e.g. `2023`).

**Comment by p060477** [comment]
01-08 23:58:15 Info Starting Jackett v0.21.1519
01-08 23:58:15 Info Environment version: 6.0.25 (G:\back up 29.04.2010\C\Documents and Settings\Administrator\Dati applicazioni\JACKETT\Jackett 0.18.875\)
01-08 23:58:15 Info OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
01-08 23:58:15 Info Jackett variant: CoreWindows
01-08 23:58:15 Info Running in Docker: No
01-08 23:58:15 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
01-08 23:58:15 Info App config/log directory: C:\ProgramData\Jackett
01-08 23:58:15 Info Using proxy: Disabled
01-08 23:58:15 Info Using FlareSolverr: http://192.168.2.3:8191
01-08 23:58:15 Info Using HTTP Client: HttpWebClient2
01-08 23:58:15 Info Loading Native indexers ...
01-08 23:58:15 Info Loaded 73 Native indexers.
01-08 23:58:15 Info Loading Cardigann indexers from: C:\ProgramData\Jackett\cardigann\definitions\, G:\back up 29.04.2010\C\Documents and Settings\Administrator\Dati applicazioni\JACKETT\Jackett 0.18.875\Definitions
01-08 23:58:17 Info Loaded 534 Cardigann indexers.
01-08 23:58:17 Info Loaded 607 indexers in total
01-08 23:58:17 Info Adding aggregate indexer ('all' indexer) ...
01-08 23:58:17 Info Adding filter indexer ('type:public' indexer) ...
01-08 23:58:17 Info Adding filter indexer ('type:private' indexer) ...
01-08 23:58:17 Info Adding filter indexer ('type:semi-public' indexer) ...
01-08 23:58:17 Info Jackett startup finished in 2.769 s
Hosting environment: Production
Content root path: G:\back up 29.04.2010\C\Documents and Settings\Administrator\Dati applicazioni\JACKETT\Jackett 0.18.875\Content
Now listening on: http://127.0.0.1:9117
Application started. Press Ctrl+C to shut down.

**Comment by ilike2burnthing** [comment]
Again, wait until we resolve the other issue.

Again, an enhanced log of the issue (see the link).

**Comment by p060477** [comment]
**just restart and re-logged...:**

01-08 23:58:15 Info Starting Jackett v0.21.1519
01-08 23:58:15 Info Environment version: 6.0.25 (G:\back up 29.04.2010\C\Documents and Settings\Administrator\Dati applicazioni\JACKETT\Jackett 0.18.875\)
01-08 23:58:15 Info OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
01-08 23:58:15 Info Jackett variant: CoreWindows
01-08 23:58:15 Info Running in Docker: No
01-08 23:58:15 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
01-08 23:58:15 Info App config/log directory: C:\ProgramData\Jackett
01-08 23:58:15 Info Using proxy: Disabled
01-08 23:58:15 Info Using FlareSolverr: http://192.168.2.3:8191
01-08 23:58:15 Info Using HTTP Client: HttpWebClient2
01-08 23:58:15 Info Loading Native indexers ...
01-08 23:58:15 Info Loaded 73 Native indexers.
01-08 23:58:15 Info Loading Cardigann indexers from: C:\ProgramData\Jackett\cardigann\definitions\, G:\back up 29.04.2010\C\Documents and Settings\Administrator\Dati applicazioni\JACKETT\Jackett 0.18.875\Definitions
01-08 23:58:17 Info Loaded 534 Cardigann indexers.
01-08 23:58:17 Info Loaded 607 indexers in total
01-08 23:58:17 Info Adding aggregate indexer ('all' indexer) ...
01-08 23:58:17 Info Adding filter indexer ('type:public' indexer) ...
01-08 23:58:17 Info Adding filter indexer ('type:private' indexer) ...
01-08 23:58:17 Info Adding filter indexer ('type:semi-public' indexer) ...
01-08 23:58:17 Info Jackett startup finished in 2.769 s
Hosting environment: Production
Content root path: G:\back up 29.04.2010\C\Documents and Settings\Administrator\Dati applicazioni\JACKETT\Jackett 0.18.875\Content
Now listening on: http://127.0.0.1:9117
Application started. Press Ctrl+C to shut down.

**Comment by ilike2burnthing** [comment]
Again again, wait until #14961 is resolved. If you post before that, you will be ignored.

Again again, and enhanced log of the issue, as per the linked instructions.

**Comment by p060477** [comment]
hi, first thxs for yr kind helping
here it is:

[result.txt](https://github.com/Jackett/Jackett/files/13876309/result.txt)

**Comment by p060477** [comment]
here it is:

[result.txt](https://github.com/Jackett/Jackett/files/13876309/result.txt)

**Comment by ilike2burnthing** [comment]
[v0.21.1536](https://github.com/Jackett/Jackett/releases/v0.21.1536).

**Comment by p060477** [comment]
hi, just to let you know that now with yr new vers.0.21.1536 the indexers: proporno and cpsabien PASSED the test!!
so i really want to thank you so much for yr efforts and for yr kind helping
and **for yr very sweet and big PATIENCE too!!**
cheers!
