### ISSUE TITLE
[kickasstorrents-to] (testing) Test search in kickasstorrents.to => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by p060477** [Jackett/Jackett#14970]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
error 451...-> BUG
```

### Description

error 451...-> BUG

### Logged Error Messages

```text
error 451...-> BUG
```

**Comment by p060477** [comment]
error 451...-> BUG

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14961

**Comment by p060477** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/1034#issue-2070796844
