### ISSUE TITLE
[req]: RM-HD

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14980]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: RM-HD
- URL: https://remastered-hd.org/
- Description: RM-HD (remastered-hd) is a UKRAINIAN Private tracker for remastered MOVIES / TV / MUSIC
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MR 1.0, MST 48hrs
- Additional Comments: 
Engine: tbd
registration is open
Ukrainian run/owned but mixed Ukrainian/Russian language (I think mainly Russian)
```
Some similarity to [BlueBird](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/bluebird.yml)

**Comment by garfield69** [comment]
I could not register, site asked me for an Invite code. Tried Proton VPN with Japan, Netherlands, USA servers, still wanted an IC :-(

**Comment by ilike2burnthing** [comment]
Tried a dozen or so NordVPN servers from different countries, no luck, always asked for an invite code.

**Comment by garfield69** [comment]
v0.21.1556

**Comment by garfield69** [comment]
RM-HD rejected my creds as not found, as did the restore password email check, and the registration page while appearing open returned `registration is not possible` after i submitted the form.
Just me?

**Comment by ilike2burnthing** [comment]
Account still ok here.

**Comment by ilike2burnthing** [comment]
https://remastered-hd.org/ - Account disabled by server administrator

**Comment by garfield69** [comment]
v0.21.2516
