### ISSUE TITLE
[Req] uakino.club

### ISSUE THREAD

**Issue by melboyscout** [Jackett/Jackett#14985]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: uakino.club
- URL: https://uakino.club/
- Description: uakino.club is a UKRAINIAN Semi-Private Torrent Tracker for MOVIES / TV
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): N/A
- Additional Comments: possible download torrent w/o registration with timeout
```

**Comment by ilike2burnthing** [comment]
Many if not most results don't have torrents, and many of those that do have multiple torrents. This would require a C# maintainer/contributor to write the indexer. Don't hold your breath.

**Comment by garfield69** [comment]
duplicate #13833
