### ISSUE TITLE
[req]: mendigosdaweb.cc

### ISSUE THREAD

**Issue by soumaisalan** [Jackett/Jackett#14987]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Mendigos da WEB
- URL: https://mendigosdaweb.cc/
- Description: Mendigos da WEB is a PORTUGUESE Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): Global MR 1.0, MST 7d
- Additional Comments:
```
Engine: unit3d 7.1.0
Registration is open ATM

**Comment by garfield69** [comment]
v0.21.1546

**Comment by garfield69** [comment]
must have been a timing issue, as now it is working. likely I searched just as someone was loading a torrent and had not filled in the name yet?

**Comment by garfield69** [comment]
https://mendigosdaweb.cc/ ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
v0.21.2424
