### ISSUE TITLE
FinElite results show only results from letter Z

### ISSUE THREAD

**Issue by greeningmarbles** [Jackett/Jackett#14995]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.1556-ls279)
File /etc/issue: Welcome to Alpine Linux 3.18
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.15.0.76 (64bit OS) (64bit process)
Environment version: 6.0.26 (/app/Jackett/)
Starting Jackett v0.21.1556
```

### Description

Torznab search in FinElite => Found 25 releases [1519ms]

Indexer test shows "Test succesful" so connection is there. But the search results are not the latest torrents but from letter Z. Seems that there may have been some changes done on tracker..?
Is there any way to fix this?

### Logged Error Messages

```text
-
```

**Comment by garfield69** [comment]
Unfortunately none of the current team have an account for FinElite so we cannot research independently.
If you have an invite let us know.
Alternatively, if you can use your browser to access https://finelite.org/selaa.php and provide an HTML dump of that page, we may be able to examine it and update the indexer.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by greeningmarbles** [comment]
Thank you for your reply! As FinElite is private tracker, I don't feel comfortable to put it's code here, even it's only an html. 
But thank you anyway for quick reply!

**Comment by garfield69** [comment]
Then email the HTML dump to me directly, garfieldsixtynine -at- gmail.com

**Comment by garfield69** [comment]
BTW, in you FinElite web site account profile, is there an option to hide XXX torrents? 
The indexer currently has categories for XXX HD and XXX SD , but your dump does not contain these cats.
IF you are not hiding XXX then this means they are not longer supported. Can you confirm?

**Comment by greeningmarbles** [comment]
Hi,

There are no xxx-categories anymore (I haven't hidden anything).

[image: kuva.png]


to 18. tammik. 2024 klo 9.29 garfield69 ***@***.***)
kirjoitti:

**Comment by garfield69** [comment]
OK good.
it looks like the site has changed the sort defaults, where sort by added is now value=1 (was 4), and sort by name is now value 4 (was 1).
This likely explains the results you are getting. So easy to fix.
My google translator is calling `jakajien mukaa` as `by divisors` which makes no sense to me. Is this actually `by Seeders` ?

**Comment by greeningmarbles** [comment]
Hi,
  

  
Yeah. Jakajien mukaan translates to by seeders.
  
  
  
  
  
  
  

  
  
>

**Comment by garfield69** [comment]
Thanks.

**Comment by garfield69** [comment]
I will update the indexer, but we have missed the publishing window, so the next one will not be until tomorrow in about 23 hours or so.
In the mean time, you can use your Jackett dashboard to edit the FinElite indexer config and set the sort to title and save.
Then do a keywordless search and see if that gives you a list by added.
If the list is order by oldest first, then edit the config and change the type to asc
But I don't expect you to need use type asc, so if you end up needing it then let me know so that I can change the default.
Thanks.

**Comment by garfield69** [comment]
v0.21.1566

**Comment by greeningmarbles** [comment]
Thank you, working perfectly now!
