### ISSUE TITLE
Mejortorrent and DivxTotal The SSL connection could not be established, see inner exception

### ISSUE THREAD

**Issue by raulmorales** [Jackett/Jackett#14994]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
01-16 15:59:24 Info Starting Jackett v0.21.1553
01-16 15:59:33 Info Environment version: 6.0.26 (/app/Jackett/)
01-16 15:59:33 Info OS version: Unix 6.1.21.8 (64bit OS) (64bit process)
01-16 15:59:33 Info Jackett variant: CoreLinuxMuslArm64
01-16 15:59:33 Info File /etc/issue: Welcome to Alpine Linux 3.18
01-16 15:59:33 Info Running in Docker: Yes (image build: v0.21.1553-ls278)
01-16 15:59:33 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
01-16 15:59:33 Info App config/log directory: /config/Jackett
01-16 15:59:33 Info Using proxy: Disabled
01-16 15:59:33 Info Using FlareSolverr: http://192.168.1.100:8191/
01-16 15:59:33 Info Using HTTP Client: HttpWebClient2
01-16 15:59:33 Info Loading Native indexers ...
01-16 15:59:34 Info Loaded 73 Native indexers.
01-16 15:59:34 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
01-16 15:59:59 Info Loaded 534 Cardigann indexers.
01-16 15:59:59 Info Loaded 607 indexers in total
01-16 15:59:59 Info Adding aggregate indexer ('all' indexer) ...
01-16 15:59:59 Info Adding filter indexer ('type:public' indexer) ...
01-16 15:59:59 Info Adding filter indexer ('type:private' indexer) ...
01-16 15:59:59 Info Adding filter indexer ('type:semi-public' indexer) ...
01-16 16:00:00 Info Jackett startup finished in 36.980 s
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
[ls.io-init] done.
```

### Description

Hello,

I have been investigating this problem about the validation of the mejortorrent index certificate for several days.

I have reviewed previous tickets and after consulting https://curl.se/docs/sslcerts.html, I believe that the problem is due to the fact that the certificate is self-signed for this site | index.

The same applies to the DivxTotal index. 

### Logged Error Messages

```text
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

[v0.21.1553.0] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Exception: certificate validation failed: [Subject]
  CN=www9.mejortorrent.rip

[Issuer]
  CN="allot.com/emailAddress=info@allot.com", OU=Allot, O=Allot, L=Madrid, S=Madrid, C=ES

[Serial Number]
  6EAFA365000000001A00000000000000

[Not Before]
  12/16/2016 2:07:49PM

[Not After]
  12/16/2026 2:07:49PM

[Thumbprint]
  5CA86C9EF9893808BFF6851EC2A1987603F5A0FA
```

### Screenshots

```
root@1d88ac520087:/# curl https://www9.mejortorrent.rip/
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Download certificate from mejortorrent to pass it to curl the file
```
apk add openssl
openssl s_client -showcerts -servername www9.mejortorrent.rip -connect www9.mejortorrent.rip:443 > cacert.pem
curl https://www9.mejortorrent.rip/ --cacert cacert.pem
<html><body>Object not found</body></html>

```

**Comment by garfield69** [comment]
You are being blocked by your ISP and routed to a black hole with an invalid CA from Allot Madrid.

MejorTorrent have switched subdomains to `https://www10.mejortorrent.rip/`, so you can try using your Jackett dashboard to edit the MejorTorrent config and changing the sitelink to `https://www10.mejortorrent.rip/` and see if that passes your ISP block.

DivxTotal is still using `https://www2.divxtotal.mov/` so if you are seeing an Allot Madrid CA for this too then this site is also being blocked by your ISP.

Try switching your router or PC to using a public DNS service such as cloudflare's 1.1.1.1 or Googles 8.8.8.8 or use a VPN.

**Comment by raulmorales** [comment]
Thanks @garfield69, with the new domain mejortorrent works.

I use a Adguard DNS, but I see that the ISP is blocking it in another way 

![image](https://github.com/Jackett/Jackett/assets/24702103/9c3042a0-2f1d-47c6-8ccc-352f5f1f2bd3)

**Comment by HasturW** [comment]
I'm having the same error, but is weird, because i can access to mejortorrent and DivXTotal via browser

**Comment by garfield69** [comment]
@HasturW please open a fresh ticket and fill in all the fields in the form, and we can begin to take a look.
