### ISSUE TITLE
Latest release call Jackett-latest.tar.gz

### ISSUE THREAD

**Issue by blindpet** [Jackett/Jackett#15]
I maintain the guides for installation and to ensure users get the latest version (I expect most to copy and paste the commands rather than read the fine print) it would be great if the latest release could be called the same name always. Alternatively using something like uscan may be of interest - I only just learned of its existence myself.

http://manpages.ubuntu.com/manpages/utopic/man1/uscan.1.html

https://davesteele.github.io/development/2015/05/02/debian-watch-file-format-for-signed-github-source-tars/

**Comment by flightlevel** [comment]
We're still working through how we're going to set things up, but will definitely keep this in mind.

**Comment by blindpet** [comment]
Much appreciated, a repo would also be great but that would require additional maintenance and server costs.

**Comment by raspdealer** [comment]
Hey @flightlevel, on the source github (zone117x/Jackett) there is a button on the release page called [*Latest release link*](https://github.com/zone117x/Jackett/releases/latest) to automatically get redirect to the last one but it's not available on this fork.... Can we add this?

@blindpet Based on this url I was used to do that : 
`WVERSION=$(curl https://github.com/zone117x/Jackett/releases/latest -s -L -I -o /dev/null -w '%{url_effective}'| grep -o 'v[0-9.].[0-9.].[0-9.]')`
`wget https://github.com/zone117x/Jackett/releases/download/${WVERSION}/Jackett.Binaries.Mono.${WVERSION}.tar.bz2`

May be this can help you to get what you need :)

**Comment by flightlevel** [comment]
Hi @raspdealer 
The button is created by GitHub, as soon a we create a release it will automatically appear.
Those two indexers you requested can you handle creating them or have invites?

**Comment by raspdealer** [comment]
I think I can send an invite for one of them but for the other one, I will need to wait.
