### ISSUE TITLE
API search does not work with Params unless using torznab

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#15009]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
running in docker container.
latest -  Jackett Version v0.21.1588
```

### Description

After like 5 hours trying to build the Jackett enviroment in visual studio i gave up and am just going to mitigate this [issue](https://github.com/Jackett/Jackett/issues/14904) using a custom qbittorrent.

when using the API is there a way to use the params to get the results back in JSON vs RSS/torznab as i can only get the search query to work.

**this works and gives me a json response**  Note query being used instead of q.
`http://10.0.0.125:9117/api/v2.0/indexers/retroflix/results?apikey=API_KEY&query=tt2362006`

**this search just gives me the last 100 torrents uploaded so the param imdbid does not actually work.** (i also tested with other params on other indexers and got the same result)
`http://10.0.0.125:9117/api/v2.0/indexers/retroflix/results?apikey=API_KEY&imdbid=tt2362006`

**using torznab this works but is in torznab/rss format**
`http://10.0.0.125:9117/api/v2.0/indexers/retroflix/results/torznab?apikey=API_KEY&imdbid=tt2362006`

I assume the full endpoint is `http://IP_ADDRESS:9117/api/v2.0/indexers/retroflix/results/api?apikey=APIKEY&t=movie&cat=2&imdbid=tt1234567` as thats what it looks like from the docs but that does not work either.
https://github.com/Jackett/Jackett#search-modes-and-parameters

Can something like example from the docs`.../api?apikey=APIKEY&t=movie&cat=2&imdbid=tt1234567` work with a JSON response or does it have to be torznab? as it does not work for me `http://10.0.0.125:9117/api/v2.0/indexers/retroflix/results/api?apikey=APIKEY&t=movie&cat=2&imdbid=tt1234567

i am trying to pull this data into a custom application and having the format in JSON makes parsing out the info so much easier.

### Logged Error Messages

```text
I dont see any logs generated even with verbose enabled when querying with `http://10.0.0.125:9117/api/v2.0/indexers/retroflix/results?apikey=API_KEY&imdbid=tt2362006`
```

### Screenshots

no logged errors

**Comment by ilike2burnthing** [comment]
The search modes and parameters are for the torznab endpoint, and it returns an XML RSS feed.

Our API can use either:

`api/v2.0/indexers/retroflix/results?apikey=API_KEY&query=tt2362006`

`api/v2.0/indexers/all/results?apikey=API_KEY&Tracker[]=retroflix&cat=&Query=tt2362006`

It returns JSON and does not support those search modes and parameters.

---

What issue were you having with Visual Studio?

**Comment by swannie-eire** [comment]
> The search modes and parameters are for the torznab endpoint, and it returns an XML RSS feed.
> 
> Our API can use either:
> 
> `api/v2.0/indexers/retroflix/results?apikey=API_KEY&query=tt2362006`
> 
> `api/v2.0/indexers/all/results?apikey=API_KEY&Tracker[]=retroflix&cat=&Query=tt2362006`
> 
> It returns JSON and does not support those search modes and parameters.
> 
> What issue were you having with Visual Studio?

are the only params supported with a JSON response Tracker, cat and query?

cant remember the exacy error as it was last week and i since deleted the windows VM i was working on but basically visual studio gives me an error saying i dont have the correct libraries installed to build/compile the project to get the exe even though i do. been nearly 10 years since i worked with C#/VS and it totally different now so gave up after like half a day searching online in how to fix.

**Comment by ilike2burnthing** [comment]
> are the only params supported with a JSON response Tracker, cat and query?

Whoops, edited above, it should have been `Category[]`, but yea:

https://github.com/Jackett/Jackett/blob/0533d384d10716f0b3523e64ec3961bbaaf4e04b/src/Jackett.Server/Controllers/ResultsController.cs#L198-L215

Were you following the contributing guide for setting up the environment?
https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md#contributing-code
