### ISSUE TITLE
m-team.cc can't be added

### ISSUE THREAD

**Issue by kristianvmd** [Jackett/Jackett#15008]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://172.17.0.1:18191/
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.1585-ls282)
File /etc/issue: Welcome to Alpine Linux 3.18
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 4.4.302.0 (64bit OS) (64bit process)
Environment version: 6.0.26 (/app/Jackett/)
Starting Jackett v0.21.1585
```

### Description

 jackett's reported error was:
```An error occurred while updating this indexer
The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.: A task was canceled.
```

The error reported by prowlarr was:
```Unable to connect to indexer. Redirected to https://www.google.com/torrents.php```

### Logged Error Messages

```text
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

[v0.21.1585.0] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies, Dictionary`2 headers) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 587
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 576
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1042
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```
```


### Screenshots

_No response_

**Comment by ilike2burnthing** [comment]
Do you have 2FA enabled for the tracker? Are you using the normal indexer or the 2FA indexer?

Are you using a proxy, VPN, VPS, or seedbox?

Are you able to access the tracker in browser from the same IP address that Jackett is using?

**Comment by kristianvmd** [comment]
> Do you have 2FA enabled for the tracker? Are you using the normal indexer or the 2FA indexer?
> 
> Are you using a proxy, VPN, VPS, or seedbox?
> 
> Are you able to access the tracker in browser from the same IP address that Jackett is using?

Do you have 2FA enabled for the tracker? Are you using the normal indexer or the 2FA indexer?

I don't have 2FA turned on.
I've tried both the normal indexer and 2FA indexe logins and neither of them work.

Are you using a proxy, VPN, VPS, or seedbox?

I've tried direct connect, direct connect + FlareSolverr, http proxy + FlareSolverr, none of them work!

Are you able to access the tracker in browser from the same IP address that Jackett is using?

The tracker for this station has been inaccessible on my computer, but I can see the correct ip using the nslookup command on nas

The most important thing is that this started happening about 2-3 days ago, it used to work fine before, I was able to add m-team in jackett before no matter if it was proxy or direct access, not since the last couple of days

**Comment by ilike2burnthing** [comment]
If you're unable to access the site on your computer, from the same IP address as your NAS that Jackett is running on, then I think the issue is either with your ISP or an IP block by the site.

Try to resolve the issue on your computer first: change DNS, use a proxy/VPN, try multiple servers from multiple countries, etc. - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

As a test, you could also try:
- running Jackett on your computer and see if it the indexer works there
- running a Firefox container on your NAS and trying to access the site through it - https://registry.hub.docker.com/r/linuxserver/firefox/

**Comment by kristianvmd** [comment]
Sorry, I may not have explained what I meant clearly. I can access m-team on my computer and enter the nslook command on the nas to parse kp.m-team.cc correctly.

发送自 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: ilike2burnthing ***@***.***>
发送时间: 星期二, 一月 23, 2024 09:19
收件人: Jackett/Jackett ***@***.***>
抄送: kristianvmd ***@***.***>; Author ***@***.***>
主题: Re: [Jackett/Jackett] m-team.cc can't be added (Issue #15008)


If you're unable to access the site on your computer, from the same IP address as your NAS that Jackett is running on, then I think the issue is either with your ISP or an IP block by the site.

Try to resolve the issue on your computer first: change DNS, use a proxy/VPN, try multiple servers from multiple countries, etc. - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

As a test, you could also try:

  *   running Jackett on your computer and see if it the indexer works there
  *   running a Firefox container on your NAS and trying to access the site through it - https://registry.hub.docker.com/r/linuxserver/firefox/

―

**Comment by ilike2burnthing** [comment]
Ok, well follow the linked instructions for your NAS then.

**Comment by kristianvmd** [comment]
> Ok, well follow the linked instructions for your NAS then.

Yes, I can open this URL in nas firefox: https://kp.m-team.cc/

**Comment by ilike2burnthing** [comment]
You've followed these troubleshooting steps for your NAS? https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

Have you tried Jackett on Windows?

Have you tried all 3 URLs for the indexer?

**Comment by kristianvmd** [comment]
> You've followed these troubleshooting steps for your NAS? https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed
> 
> Have you tried Jackett on Windows?
> 
> Have you tried all 3 URLs for the indexer?

Have you tried Jackett on Windows?
yes,the result is:
```
 An error occurred while updating this indexer
Login Failed, got redirected to: https://kp.m-team.cc/index.php
Click here to open an issue on GitHub for this indexer.
```

Have you tried all 3 URLs for the indexer?
yes,the result is :
```
The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.: A task was canceled.
```

Since I was able to add it using jackett without any problems in previous years, I think it's that m-team has had a new change in the last week, I just don't know how to troubleshoot and fix it.

The last few days I've tried the following and can't add it:
docker version of firefox+jackett+FlareSolverr, all without using a proxy
docker version of firefox+jackett+FlareSolverr, both using proxies
PC Browser+jackett+FlareSolverr, all without proxy
PC Browser + jackett + FlareSolverr, all using proxy.
prowlarr+FlareSolverr, neither using proxy
prowlarr+FlareSolverr, both using proxies

Both prompt the following:
The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.: A task was canceled.

Here are the results of my nslookup after entering jackett

```
root@26f5686fcbcb:/# nslookup kp.m-team.cc
Server:         192.168.31.1
Address:        192.168.31.1:53

Non-authoritative answer:
Name:   kp.m-team.cc
Address: 104.26.13.50
Name:   kp.m-team.cc
Address: 104.26.12.50
Name:   kp.m-team.cc
Address: 172.67.73.8

Non-authoritative answer:
Name:   kp.m-team.cc
Address: 2606:4700:20::681a:d32
Name:   kp.m-team.cc
Address: 2606:4700:20::ac43:4908
Name:   kp.m-team.cc
Address: 2606:4700:20::681a:c32
```

**Comment by ilike2burnthing** [comment]
Please provide 2 enhanced logs of the issue, one from your NAS and the other from Windows - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

@mynameisbogdan are you able to add and use the indexer with Jackett?

**Comment by PlanZV** [comment]
> Please provide 2 enhanced logs of the issue, one from your NAS and the other from Windows - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
> 
> @mynameisbogdan are you able to add and use the indexer with Jackett?

It's strange, I was able to get it to work on win today instead, but the docker install of jackett still doesn't work, here's the log from the container install of jackett

[log.txt](https://github.com/Jackett/Jackett/files/14049864/log.txt)

The cookie and user-agent of the docker version of jackett are retrieved from the docker version of firefox.
The cookie and user-agent of the windows version of jackett are obtained from edge on windows.

**Comment by kristianvmd** [comment]
> Please provide 2 enhanced logs of the issue, one from your NAS and the other from Windows - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
> 
> @mynameisbogdan are you able to add and use the indexer with Jackett?

It's strange, I was able to get it to work on win today instead, but the docker install of jackett still doesn't work, here's the log from the container install of jackett

[log.txt](https://github.com/Jackett/Jackett/files/14049864/log.txt)

The cookie and user-agent of the docker version of jackett are retrieved from the docker version of firefox.
The cookie and user-agent of the windows version of jackett are obtained from edge on windows.

**Comment by kristianvmd** [comment]
> @kristianvmd please use https://privatebin.net to upload the log contents. Currently for me it's just an empty file filled with NULLs.

https://privatebin.net/?c563e1322daad2a5#9qQSNUiUVGtjWg8kpb4tgJx5xggMUmHsXDqLEPqdCyZx    

I'm sorry. Is this right now?

**Comment by kristianvmd** [comment]
> Yes, the contents are shown properly.

I found out today that if I use the computer version of jackett, I can easily add the m-team by account password or cookie.

But if I am using the docker version of jackett, I tried installing jackett using macvlan network, bridge network with firefox browser, and none of them can add m-team!

**Comment by ilike2burnthing** [comment]
Provide the enhanced log for the non-2FA indexer. I'm curious whether it times out on the login page as well, or just index.php once logged in.

**Comment by kristianvmd** [comment]
> Provide the enhanced log for the non-2FA indexer. I'm curious whether it times out on the login page as well, or just index.php once logged in.

OK

https://privatebin.net/?81125bfcfa10a00f#DDDymRpZvixT5jpwsG8uaVSsTYf7Gn1r1dwrGzBUqhRs

**Comment by kristianvmd** [comment]
> `Error: 我們懷疑你在欺騙系統，因此禁用了你的IP位址！ Login 鎖定！(認證的最大錯誤嘗試次數Login次已到)` = `Error: We suspect you are spoofing the system and have disabled your IP address! Login locked! (The maximum number of failed authentication attempts, Login times, has been reached)`

I actually partially solved the problem, which is that if jackett uses the host network, it can successfully add the m-team, regardless of password or cookie login.

But this only works on my old synology, not on unraid, and I'm not sure what the reason is

**Comment by ilike2burnthing** [comment]
That error is from the 18th, but it does suggest something else might be going on.

That latest log entry is still for the 2FA indexer, I'd need to see the credentials indexer instead.

**Comment by kristianvmd** [comment]
> That error is from the 18th, but it does suggest something else might be going on.
> 
> That latest log entry is still for the 2FA indexer, I'd need to see the credentials indexer instead.

https://privatebin.net/?856584cb564411bc#BBSGhs8ohdt1e2dFkvZZn2aeTgBRbh8QVZ8XrC2P1ry

**Comment by ilike2burnthing** [comment]
Delete the current log file, make sure there's no other activity (e.g. Sonarr RSS sync), attempt to add/reconfigure the non-2FA indexer and only that. Provide that new enhanced log.

**Comment by kristianvmd** [comment]
> Delete the current log file, make sure there's no other activity (e.g. Sonarr RSS sync), attempt to add/reconfigure the non-2FA indexer and only that. Provide that new enhanced log.

OK, the non-2FA indexer means``` [M-Team - TP``` or ```M-Team - TP (2FA)``` ?

**Comment by kristianvmd** [comment]
I stopped sonarr and radarr, deleted the history logs, and then regenerated the following logs（the ```M-Team - TP (2FA)``` logs)

https://privatebin.net/?ab044f80ac46a3dc#3RZHASwjEFi2xyQdQY9P3UVaTJdHuXwX38hKXHzWwnU4

**Comment by kristianvmd** [comment]
Here's the ```[M-Team - TP]``` log I regenerated after turning off sonarr and radarr

https://privatebin.net/?871b853d121bd3db#EHRXXKafzzB9bVHfEcb6jBvtpx2k3GJqVRRQL5Q4LVwm

**Comment by ilike2burnthing** [comment]
Run the output for the following command, once from within the Jackett container and then again just from your host device:

> curl -v https://kp.m-team.cc/login.php

**Comment by kristianvmd** [comment]
run from unraid

```
root@Tower:~# curl -v https://kp.m-team.cc/login.php
*   Trying 104.26.13.50:443...
*   Trying 2606:4700:20::681a:d32:443...
* Immediate connect fail for 2606:4700:20::681a:d32: Network is unreachable
*   Trying 2606:4700:20::681a:c32:443...
* Immediate connect fail for 2606:4700:20::681a:c32: Network is unreachable
*   Trying 2606:4700:20::ac43:4908:443...
* Immediate connect fail for 2606:4700:20::ac43:4908: Network is unreachable
* Connected to kp.m-team.cc (104.26.13.50) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: none
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Apr 22 00:00:00 2023 GMT
*  expire date: Apr 21 23:59:59 2024 GMT
*  subjectAltName: host "kp.m-team.cc" matched cert's "*.m-team.cc"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /login.php]
* h2h3 [:scheme: https]
* h2h3 [:authority: kp.m-team.cc]
* h2h3 [user-agent: curl/7.83.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x496470)
> GET /login.php HTTP/2
> Host: kp.m-team.cc
> user-agent: curl/7.83.1
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 302 
< date: Fri, 26 Jan 2024 05:33:33 GMT
< content-type: text/html
< location: https://www.google.com/login.php
< strict-transport-security: max-age=15552000; includeSubDomains; preload
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=FVsS7uXjWE078bmXFDMCZe%2FPQCdIqh%2FkLEcuSSasajTY4Dnlx2WvsNyZ5L5M7C6nTxXREiCuh4GGIaGDm8sz1paRTgv4WwRuXq3y4dP9uSlZP27C%2BvJUNqyRU6h1KA%3D%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< x-content-type-options: nosniff
< server: cloudflare
< cf-ray: 84b661b899ac82bd-IAD
< alt-svc: h3=":443"; ma=86400
< 
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.23.3</center>
</body>
</html>
* Connection #0 to host kp.m-team.cc left intact
```


run from jackett

```
root@Tower:~# docker exec -it jackett sh
root@495ca9139b47:/# curl -v https://kp.m-team.cc/login.php
* Host kp.m-team.cc:443 was resolved.
* IPv6: 2606:4700:20::681a:d32, 2606:4700:20::681a:c32, 2606:4700:20::ac43:4908
* IPv4: 172.67.73.8, 104.26.12.50, 104.26.13.50
*   Trying 172.67.73.8:443...
*   Trying [2606:4700:20::681a:d32]:443...
* Immediate connect fail for 2606:4700:20::681a:d32: Address not available
*   Trying [2606:4700:20::681a:c32]:443...
* Immediate connect fail for 2606:4700:20::681a:c32: Address not available
*   Trying [2606:4700:20::ac43:4908]:443...
* Immediate connect fail for 2606:4700:20::ac43:4908: Address not available
* Connected to kp.m-team.cc (172.67.73.8) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Apr 22 00:00:00 2023 GMT
*  expire date: Apr 21 23:59:59 2024 GMT
*  subjectAltName: host "kp.m-team.cc" matched cert's "*.m-team.cc"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha1WithRSAEncryption
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://kp.m-team.cc/login.php
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: kp.m-team.cc]
* [HTTP/2] [1] [:path: /login.php]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
> GET /login.php HTTP/2
> Host: kp.m-team.cc
> User-Agent: curl/8.5.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 302 
< date: Fri, 26 Jan 2024 05:34:35 GMT
< content-type: text/html
< location: https://www.google.com/login.php
< strict-transport-security: max-age=15552000; includeSubDomains; preload
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=FTm4SCIibeeIkAnazfXj83B13NoqlzTVNRvfdySMAKVMlepp9x5OLq8fJuYZIA1VwybqpGb3eUlHBYAHIKrd1G9NwNPFuHvFtmd9PI8qVxHSDVAxOHB17WijQa1SNg%3D%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< x-content-type-options: nosniff
< server: cloudflare
< cf-ray: 84b6633c5afe81d6-IAD
< alt-svc: h3=":443"; ma=86400
< 
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.23.3</center>
</body>
</html>
Connection #0 to host kp.m-team.cc left intact
```

**Comment by ilike2burnthing** [comment]
Given that it's working on a computer on the same local network, the issue seems to be with your NAS then, and not specifically just for Jackett.

I can only point back to earlier troubleshooting (though now in regards to your NAS) regarding changing DNS, proxy/VPN (checking you're not already using one, and trying to use one), disabling/enabling IPv6, checking your firewall settings, as well as any other security or content filtering settings or software such as Pi-hole.

You may also need to check your router.
