### ISSUE TITLE
POTUK remove magnet as option to DL

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#15010]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
running in docker container.
latest -  Jackett Version v0.21.1588
```

### Description

If using POTUK indexer with some automation tools it will use the magnet link instead of the actual torrent. In many cases the torrent will be stuck downloading metadata in clients.

As this is a private tracker it should use the torrent file as it should always be available.

Suggestion:
remove parsing the magnet DL link from POTUK site and use only torrent file.

### Logged Error Messages

```text
no error log
```

**Comment by ilike2burnthing** [comment]
Does the magnet not include the tracker announce and your passkey?

If it does and you're having this issue, then it's either a problem with your client or there are no peers.

**Comment by swannie-eire** [comment]
> Does the magnet not include the tracker announce and your passkey?
> 
> If it does and you're having this issue, then it's either a problem with your client or there are no peers.

Yes it does but a lot of the people using potuk have misconfigured clients so even if there is seeders in many cases you can't download the metadata from them.

Personally think it's better to just remove the magnet links as it causes more problems than it fixes. .

**Comment by ilike2burnthing** [comment]
If the sole reason magnets may not work is because some people have misconfigured their torrent client, I'd rather leave users the choice of magnets and torrents, and anyone with a problem can fix their client.

**Comment by swannie-eire** [comment]
> If the sole reason magnets may not work is because some people have misconfigured their torrent client, I'd rather leave users the choice of magnets and torrents, and anyone with a problem can fix their client.

ok Thank you I can understand your point. i dont use the automation tools people are reporting but did encounter the issue with qbittorrent plugin but that was an easy fix to only use magnet if torrent link is null as it was defaulting to magnet for some reason.

The majority of people using potuk are not technical and id say less than 20 out of the 10K+ users actually know how to create, add and upload a torrent.

**Comment by swannie-eire** [comment]
@ilike2burnthing if i put in a pull request for this would you merge it?

seems its only remove 3 lines from the potuk.yml.

    ```magnet:
      selector: a[href^="magnet:?x"]
      attribute: href```

**Comment by ilike2burnthing** [comment]
As already explained, no.
