### ISSUE TITLE
[req]: Cinematik.net now runs on UNIT3D

### ISSUE THREAD

**Issue by Audionut** [Jackett/Jackett#15035]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

No longer need to scrape the site.

### Describe the solution you'd like

Use the API. - v7.2.5

**Comment by ilike2burnthing** [comment]
None of the maintainers have an account, and it's currently invite only. If you can provide an invite, please send it to `jacketttest [AT] gmail [DOT] com`

If not, please provide an HTML dump of the search page - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by HDVinnie** [comment]
> None of the maintainers have an account, and it's currently invite only. If you can provide an invite, please send it to `jacketttest [AT] gmail [DOT] com`
> 
> If not, please provide an HTML dump of the search page - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

sent

**Comment by garfield69** [comment]
v0.21.1680

**Comment by Audionut** [comment]
Something changed:

`Exception (cinematik): Object reference not set to an instance of an object.: Error while parsing field=category, selector=category_id, value=6: Object reference not set to an instance of an object.`

**Comment by garfield69** [comment]
the site must have added a new category or changed the id of one of the existing ones. @ilike2burnthing  will update the indexer when he is available to take a look.

**Comment by Audionut** [comment]
Category was indeed added. Perhaps hold off for the moment, and I'll reply again once I am aware of no intended further changes.

**Comment by garfield69** [comment]
PR's that updates to the categories are always welcome, see https://github.com/Jackett/Jackett/wiki/Jackett-Categories if you need to lookup what Jackett category ids we support.
