### ISSUE TITLE
Trellas / Magico Indexer not working anymore

### ISSUE THREAD

**Issue by colethegamer123** [Jackett/Jackett#15032]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.1556-ls279)
File /etc/issue: Welcome to Alpine Linux 3.18
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 4.15.0.213 (64bit OS) (64bit process)
Environment version: 6.0.26 (/app/Jackett/)
Starting Jackett v0.21.1650
```

### Description

Magico ( new name is Trellas ) Indexer changed something. Its not working anymore. I can find manually the torrents im looking for but using the indexer in Sonarr or Radarr does not find anything even with interactive search. Please check on it I think it wont be a big deal. You can try also Manual search inside Jackett and try for example ( Fear The Walking Dead ). It wont find anything still I just downloaded all episode manually from that site. It can be also the categories are changed.

### Logged Error Messages

```text
I cannot really see anything important or not normal in the logs, it just does not find anything.

Log:
"Manual search in Magico for Fear The Walking Dead => Found 0 releases [9566ms]"
```

**Comment by garfield69** [comment]
Unfortunately none of the current team have an account on Trellas so we cannot investigate independently.

Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by colethegamer123** [comment]
Thanks for your fast answer, I really appreciate it. as I see from the logs its partly working partly not. I was using Fear The Walking Dead Search criteria you will see in the logs. I replaced my personal informations in the log like IP address and username.
[log.txt](https://github.com/Jackett/Jackett/files/14116776/log.txt)

Thank you!

**Comment by garfield69** [comment]
When you search on the website for `fear of the walking dead`, do you get the first 20 results, none of which are the actual full title, but have some of those keywords, and you then scroll to the next page to find the series you want?

OR If this is not the case, and you get the titles you are after on the first page or results, then can you provide the full address in the browser bar after you have done the search, so I can compare the options with what the indexer is using?
Thanks.

**Comment by garfield69** [comment]
It looks to me like trellas has ignored our search keywords and presented a list of the latest torrents.
My guess is that they have switched to using a POST instead of our current GET.
So i will do several things;
- rename the indexer to Trellas
- add config sort options
- switch the search GET to POST
- fix the freeleech flag
and once Jackett is published in about 6 hours or so you can test and report back.

**Comment by garfield69** [comment]
v0.21.1658

**Comment by colethegamer123** [comment]
> It looks to me like trellas has ignored our search keywords and presented a list of the latest torrents. My guess is that they have switched to using a POST instead of our current GET. So i will do several things;
> 
> * rename the indexer to Trellas
> * add config sort options
> * switch the search GET to POST
> * fix the freeleech flag
> * update/refresh categories
>   and once Jackett is published in about 6 hours or so you can test and report back.

Thank you very much. Im just amazed how professional you are guys. I'll test it! I'll give feedback ASAP.

**Comment by colethegamer123** [comment]
Now the testing already goes to error.  New enhanced log attached. Cleared out history.
[log.txt](https://github.com/Jackett/Jackett/files/14123981/log.txt)
![jackett](https://github.com/Jackett/Jackett/assets/62310407/8a0cc841-c522-4adb-b159-87b27604c182)

**Comment by garfield69** [comment]
Oops, clearly POST is not the way forward. I'll compare some of the other TSUE 2.2 indexer with Trellas and see if I can come up with some options.

**Comment by garfield69** [comment]
I've researched the other TSUE 2.2 indexer and nothing stands out as missing, so clearly this is a customisation specific to Trellas.
I've reset back to GET search, and added a submit keyword.
I'm also looking at amending the logCleanser tool to stop it stripping the &pid= from the logs as this may be a clue that I am missing.
So after the next Jackett release please try again and if still not working then provide fresh enhanced logs so I can see if the pid is significant. Thanks.

**Comment by garfield69** [comment]
v0.21.1664

**Comment by colethegamer123** [comment]
Thanks. I tried the version. We are somewhere at the point where we were. The test works now, but I cannot find the right ones Im looking for. It has a sucess rate because If I look for something very known where there is a lot of torrent it finds a few, but for example Fear The Walking Dead is there and cannot find it. I can help with a Trellas account if its possible in private. That is pretty much important to me to being solved, I try to do everything to help your really apprciated help.

I attached the new enhanced log.

[log.txt](https://github.com/Jackett/Jackett/files/14137133/log.txt)
![fearthewalkingead](https://github.com/Jackett/Jackett/assets/62310407/95f27b7f-9004-468b-8fec-1e78399d2c83)

**Comment by garfield69** [comment]
It certainly would help if we could have access to an account, because right now I am at a loss to figure out why out search request is being ignored and why we are given back the latest 20 torrents instead of what we asked for.

I think its time to get some fresh eyes on this issue so I am going to ask ilike2burnthing  to take over.
If you have an invite you can talk to them about whether they want it and where to email it, or however else you can help with an account. Thanks.

@ilike2burnthing  Can you take a look at this ticket and see if you can help, I've hit a brick wall. Thanks.

**Comment by ilike2burnthing** [comment]
Only other thing I could really see it being would be changing the search input `pid` from `32` to `10`. Feel free to test that, but otherwise I'd need access to look further. My email is:

jacketttest [AT] gmail [DOT] com

**Comment by colethegamer123** [comment]
> Only other thing I could really see it being would be changing the search input `pid` from `32` to `10`. Feel free to test that, but otherwise I'd need access to look further. My email is:
> 
> 
> 
> jacketttest [AT] gmail [DOT] com

Hello friend.

I sent the credentials to your mail. I really appreciate your help. Thanks for your kindness.

**Comment by ilike2burnthing** [comment]
This was already basically working, but a keywords filter was breaking any search with spaces.

I've now logged out; please change your password.

**Comment by garfield69** [comment]
yes, I'll post the Jackett version that includes all the fixes for this indexer.

**Comment by garfield69** [comment]
v0.21.1672

**Comment by colethegamer123** [comment]
> v0.21.1672

Working perfectly. From my side the ticket is closed. Thanks you very much for your fast and pro active really appreciated help. Looking forward to work again with a team what is professional like that. Have a nice one guys.

**Comment by colethegamer123** [comment]
Sorry just one last feedback. From 10 search 8 goes to Bad Request and puts the indexer as Unavailable in Radarr/Sonarr.

`HTTP Error - Res: HTTP/1.1 [GET] http://IPADDRESS:9117/api/v2.0/indexers/magico/results/torznab/api?t=search&cat=2000,2030,2050,100001,100014,100016,100017,100038,100039,100044,100055,100082,100084&extended=1&apikey=(removed)&offset=0&limit=100&q=Rebel%20Moon%20Part%20One%20A%20Child%20of%20Fire: 400.BadRequest (1633 bytes)
<?xml version="1.0" encoding="UTF-8"?>
<error code="900" description="Jackett.Common.IndexerException: Exception (trellas): Error: Προέκυψε ένα λάθος!&#xA; ---&gt; System.Exception: Parse error&#xA; ---&gt; Jackett.Common.ExceptionWithConfigData: Error: Προέκυψε ένα λάθος!&#xA;   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 542&#xA;   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1737&#xA;   --- End of inner exception stack trace ---&#xA;   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 770&#xA;   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1878&#xA;   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 360&#xA;   --- End of inner exception stack trace ---&#xA;   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 360&#xA;   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 747&#xA;   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 489" />`

**Comment by ilike2burnthing** [comment]
We'd need to see the Jackett logs for the failure. If there's no error on Jackett's end, then the issue looks like the connection between it and Sonarr/Radarr.

**Comment by ilike2burnthing** [comment]
Fix will be out in the next build in ~16hrs.

**Comment by colethegamer123** [comment]
> Fix will be out in the next build in ~16hrs. You can change your password again.

You are amazing. Thanks for your time.

**Comment by garfield69** [comment]
v0.21.1700

**Comment by colethegamer123** [comment]
Now everything works perfectly. I cannot be grateful enough. Thanks for your time guys, you did wonderful job.

**Comment by colethegamer123** [comment]
Hello guys, Sorry I know I gave you enough thing to do already, but I have a last question, since everything else working perfecly now. On Greek torrent sites its an unwritten law, that if you want to find greek stuffs, what is really officially greek made stuff, you need to search with big letters, in Greek language of course, Sonarr/Radarr knows the real greek title when I add it, but its gives you with small greek letters. Do you think you can change this to also search with big letters? It does not need only when Greek, its easier to do like that to always search with small characters and also with big ones. Small characters will find international medias, big characters will find greek based stuffs. If it something what you can do or sonarr/radarr should change and that wont happen probably?

Thank you. hope my issue was understandable. 

Here is an example:
I Die for You added to Radarr - Found alternative title "Πεθαινω για σενα" - Cannot be found on Trellas
If I change "Πεθαινω για σενα" to Big letters it looks "ΠΕΘΑΙΝΩ ΓΙΑ ΣΕΝΑ" - Found on Trellas ΠΕΘΑΙΝΩ ΓΙΑ ΣΕΝΑ (2009) 1080p WEB-DL.

I changed back the testing account's password for you if needed. I dont if this is really possible from side but the whole Greek community would be really happy I can tell. Have a nice day.

**Comment by ilike2burnthing** [comment]
Thanks, you can revert the password again. New release with the fix will be out in  ~12hrs.

**Comment by garfield69** [comment]
v0.21.1776
