### ISSUE TITLE
[req]: 

### ISSUE THREAD

**Issue by colethegamer123** [Jackett/Jackett#15031]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Trellas / Magicko
- URL: https://trellas.net/?p=home&pid=1
- Description: Greek Torrent site not working anymore
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments: Can you please try to solve it? I added as an indexer but does not find anything properly. Of course I tested manually and its there what im looking for.

Thank you!
```

**Comment by garfield69** [comment]
Please fill in https://github.com/Jackett/Jackett/issues/new?assignees=&labels=&projects=&template=bug_report.yml
this is the wrong ticket form.
