### ISSUE TITLE
[req]: ToonsForMe

### ISSUE THREAD

**Issue by edge20200** [Jackett/Jackett#15033]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: ToonsForMe
- URL: https://toonsfor.me/
- Description: ToonsForMe is a Private Tracker for Cartoons/Kids MOVIES / TV
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 48 Hour seedtime no matter ratio. with a sitewide ratio of 0.4
- Additional Comments: Unit3d (v7.2.5) with API, site is open to register so it can be tested/setup.
```

**Comment by garfield69** [comment]
v0.21.1658

**Comment by vincejv** [comment]
Tracker has shutdown as what their website says, IRC also closed
https://toonsfor.me/

> ToonsForMe
I have decided to shut down ToonsForMe, and have wiped the server of all information. What started as a project months ago with lots of hope, alot can change and i think its best for the community to close now and focus on our orginal project.
-edge2020

**Comment by garfield69** [comment]
v0.21.1750
