### ISSUE TITLE
Jackett Service randomly stops

### ISSUE THREAD

**Issue by viking2** [Jackett/Jackett#15047]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-02-09 15:56:43 	Info 	Using HTTP Client: HttpWebClient2
2024-02-09 15:56:43 	Info 	Using FlareSolverr: No
2024-02-09 15:56:43 	Info 	Using proxy: Disabled
2024-02-09 15:56:43 	Info 	App config/log directory: C:\ProgramData\Jackett
2024-02-09 15:56:43 	Info 	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2024-02-09 15:56:43 	Info 	Running in Docker: No
2024-02-09 15:56:43 	Info 	Jackett variant: CoreWindows
2024-02-09 15:56:43 	Info 	OS version: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit OS)
2024-02-09 15:56:43 	Info 	Environment version: 6.0.26 (C:\ProgramData\Jackett\)
2024-02-09 15:56:42 	Info 	Starting Jackett v0.21.1693
```

### Description

Jackett service randomly stops. It is set to restart after a failure (but it doesn't).
I have to manually restart the service almost daily.

Windows 7 (64bit) 
Jackett Version v0.21.1693

### Logged Error Messages

```text
After the last restart a few minutes ago, I see the following error:

2024-02-09 15:56:47 	Error 	
An error occurred during the last update. If this error occurs again, you need to reinstall Jackett following the documentation. If the problem continues after reinstalling, report the issue and attach the Jackett and Updater logs.
```

**Comment by garfield69** [comment]
>An error occurred during the last update. If this error occurs again, you need to reinstall Jackett following the documentation. If the problem continues after reinstalling, report the issue and attach the Jackett and Updater logs.


So did you follow the suggestion on the latest error message and downloaded the latest version from https://github.com/Jackett/Jackett/releases/tag/v0.21.1712 and installed?
You can install over the top without having to remove the old one.
And if so, if you are still getting this issue then please provide the log as suggested by the error message.
You will find them in the C:\ProgramData\Jackett folder, pack all the updater*txt files in a  zip and drag/drop here so we can have a looksee for clues.

**Comment by garfield69** [comment]
BTW the most common breaker on windows for the updater is your anti-malware pulling out a module to its vault, usually because it is getting a false hit off it. Are you running such software and is there anything in its logs about a Jackett module being flagged as suspicious?

**Comment by viking2** [comment]
Comodo firewall is frequently pausing the update and asking if I trust Jackett. I always answer yes, and to trust it in the future (but it still comes back asking; I assume because the signature has changed next time).

Jackett just updated by itself a few minutes ago (and I answered yes to Comodo as usual). It is now running v0.21.1712 (and no error in the log). I will have to wait until the Service stops again and check the logs again at that time.

**Comment by ilike2burnthing** [comment]
https://help.comodo.com/topic-72-1-284-2969-.html

**Comment by viking2** [comment]
> ~https://help.comodo.com/topic-72-1-284-2969-.html~
> 
> Actually, more likely this: https://help.comodo.com/topic-72-1-766-9054-configure-internet-access-rights-for-applications.html and/or maybe this: https://help.comodo.com/topic-72-1-766-9173-Application-Rules.html

For Jackett Console, I have:
https://i.gyazo.com/fd5e2ba6d3fca3a3930e183c48d45656.png

For Jackett Service, I have:
https://i.gyazo.com/80fc09c3983f3738e86414070398480a.png

I think that these rules are automatically created when I check allow in the future.

**Comment by ilike2burnthing** [comment]
As updates seem to be your issue, JackettUpdater.exe should be added as well.

If there's the option for `Allow all incoming and outgoing requests` as per the [example](https://help.comodo.com/uploads/Comodo%20Internet%20Security/913112e8718da237a1a4c0f7f7cf3e22/5eac818f1e1c4adc19d335055b06586b/8660ee80d456f63bdbf3c1c664fe9578/set_fw_app_rule3_1.png), I'd just go with that.

**Comment by viking2** [comment]
I added JackettUpdater.exe to Allow all incoming and outgoing requests. I no longer get the Comodo warning. However, the Service still stops and when I look in the log, I see the update error. If I restart the service and then do a manual update (by checking for updates) the update works fine and I get no error.

Would there be any large disadvantage(s) if I Disable auto update? At least as a troubleshooting step.

**Comment by ilike2burnthing** [comment]
Only disadvantage would be you having to manually update it periodically. Are you wanting to see if Jackett crashes other than when auto-updating?

**Comment by viking2** [comment]
The service has not stopped since I disabled the auto update.
It is not clear to me why the service stops with the auto update enabled?
(As I wrote above it does not seem related to Comodo)?

**Comment by garfield69** [comment]
Find the updater*.txt logs in the  folder and zip them up and drag/drop the archive here. I'll take a looksee and see if I can spot anything.

**Comment by viking2** [comment]
OK. I did a manula update and that worked fine. I am now running v0.21.1832. I next renamed the old updater.txt file to start "fresh" and enabled auto update. I will wait for the next time that the service stops and report here.

**Comment by viking2** [comment]
I noticed that the Service stopped again.  I started it and The log shows the update error again.
I have zipped updater.txt and attached it here:
[updater.zip](https://github.com/Jackett/Jackett/files/14467917/updater.zip)

**Comment by garfield69** [comment]
the updater shows a clean update to Jackett 0.21.1873 with no errors shutting down the services, extracting the files from the update archive and copying them to the corresponding folders.
the last message is the info for starting the windows service

**Comment by viking2** [comment]
I am not sure what to do next...?
I am now running Version v0.21.1873. Jacket service shut down again sine I wrote the previous message a few hours ago and the log shows the update error again:

`
2024-03-01_ 23:22:38 | Error | An error occurred during the last update. If this error occurs again, you need to reinstall Jackett following the documentation. If the problem continues after reinstalling, report the issue and attach the Jackett and Updater logs.
`

I guess the only solution is to disable auto-update?

**Comment by garfield69** [comment]
you mentioned comodo firewall, are you running comodo antivirus? if so have you checked its logs and quarantine vault for Jackett modules?

**Comment by viking2** [comment]
I am not running any Antivirus. 
Comodo Firewall is not getting any alerts since I allowed the updater.

**Comment by viking2** [comment]
It seems that the program is updated frequently. What is being updated?

**Comment by garfield69** [comment]
the yaml indexer and c# indexers are update as require to keep up with any changes caused by their corresponding web sites, usually category updates, occasionally search results page layout changes, and less often login page changes.
Also less frequently the Jackett core modules are updates, as well as the GUI.

**Comment by starbucks424** [comment]
I am running into this _constantly_ on Windows 10 recently. It's terrible. Any advice welcome.

**Comment by ilike2burnthing** [comment]
Check your logs and update logs for clues.

If you're using Windows Defender then it's probably this - https://github.com/Jackett/Jackett/issues/16352

**Comment by ExA455** [comment]
> I am running into this _constantly_ on Windows 10 recently. It's terrible. Any advice welcome.

In a Powershell(Admin) run this:

`Add-MpPreference -ExclusionPath "C:\Windows\SystemTemp\JackettUpdate*"`

You can then check it in Virus & threat protection setting > Exclusions:

We have to do it this way because the update folder always changes.
