### ISSUE TITLE
[req]: Disable Security Risk Alert Message?

### ISSUE THREAD

**Issue by joe-eklund** [Jackett/Jackett#15042]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hello-

I recently upgraded my Jackett instance (deployed using LinuxServer.io Docker) and noticed there is now this error message appearing at the top of the UI that cannot be dismissed:

`Security Risk: Your instance has external access enabled without using an admin password. `

### Describe the solution you'd like

Is there a way to disable this message? I couldn't find a way to turn it off in the settings. If there isn't, it really should be configurable, even if it has to be set in some config file or environment variable. My current workaround is to just have ublock origin block it with a script.

In my case, I am using a third party authentication / authorization layer to handle access. So just because I have external access on and no admin password set, doesn't mean it's a security risk. It's just being handled elsewhere. This paradigm is very common (see Authelia, Authentik, Keycloak, etc.).

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/pull/15017#issuecomment-1922093649

**Comment by joe-eklund** [comment]
I would appreciate if that was documented somewhere other than a random comment on a PR. Somewhere in the wiki would be better. 

Also, that solution is not great. It requires it to be done on each and every client that will be accessing the UI. I would prefer a server side solution that can be configured one time, and then it will apply to each client accessing Jackett. Even if it was just a checkbox stating I am using external authentication, so don't annoying me with a big red error message that doesn't apply to my situation.

I see I am not alone (as the comment you linked to ran into the same issue as I did). 

Thoughts?

**Comment by joe-eklund** [comment]
And for anyone who want's the ublock code, add the following to your custom filter list:

`jackett.<your_domain.tld>##.text-center.alert-danger.alert`

At least with cloud sync turned on for Ublock Origin, you have a solution that won't have to be repeated on each client. Not what I would consider a perfect solution, but it's better than nothing I guess.

**Comment by garfield69** [comment]
Yes the wiki entry is a good idea, see https://github.com/Jackett/Jackett/wiki/Troubleshooting/#security-risk-your-instance-has-external-access-enabled-without-using-an-admin-password

As for adding a disabling option, we will monitor complaints/requests and implement if there is a significant count. 
Out of the 4000 or so Native Jackett uses, and the countless docker users, so far there has been 2.
