### ISSUE TITLE
[req]: Ability to configure proxy per indexer

### ISSUE THREAD

**Issue by iGerman00** [Jackett/Jackett#15041]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I only use a proxy to bypass ISP blocks of some indexers, while others, like Filelist, are not blocked but require an IP whitelist. A conflict arises where it goes through the proxy to every indexer including Filelist, when I only really want it to go through the proxy for one or two indexers

### Describe the solution you'd like

Each indexer seems to have a settings menu. Why not add the proxy settings there and have it be configured per-indexer? Or, alternatively, have a simple checkbox that's something like "Bypass proxy for this indexer"

### Describe alternatives you've considered

Can't seem to think of any.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/2539
