### ISSUE TITLE
[req]: ADBT

### ISSUE THREAD

**Issue by virusperfect** [Jackett/Jackett#15056]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Anime Datenbank Tracker (ADBT)
- URL: https://adbt.is-into-anime.com/
- Description: Anime Datenbank Tracker (ADBT) is a Private GERMAN Tracker for Anime, Hentai and Cartoons
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MST 48hrs, global MR 0.6
- Additional Comments:
```
registration currently closed
engine: NetVision ? TBC

**Comment by virusperfect** [comment]
I sent you an invite. Please accept within 24h.

**Comment by garfield69** [comment]
I have registered, awaiting account activation. Thanks.

**Comment by garfield69** [comment]
v0.21.1781
