### ISSUE TITLE
Lost access to docker Jackett dashboard, how to fix?

### ISSUE THREAD

**Issue by PrzemekSkw** [Jackett/Jackett#15066]
Hello, today when i go to jackett dashboard I get warning that my Jackett is exposed and don't have admin password. I uncheck external access and save. After that I cannot reach dashboard. 
Please help me to fix that

### Description

I broke my Jackett

### Logged Error Messages

```text
[custom-init] No custom files found, skipping...
02-19 13:15:33 Info Starting Jackett v0.21.1792
02-19 13:15:33 Info Environment version: 6.0.27 (/app/Jackett/)
02-19 13:15:33 Info OS version: Unix 6.1.74.0 (64bit OS) (64bit process)
02-19 13:15:33 Info Jackett variant: CoreLinuxMuslAmdx64
02-19 13:15:33 Info File /etc/issue: Welcome to Alpine Linux 3.18
02-19 13:15:33 Info Running in Docker: Yes (image build: v0.21.1792-ls311)
02-19 13:15:33 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
02-19 13:15:33 Info App config/log directory: /config/Jackett
02-19 13:15:33 Info Using proxy: Disabled
02-19 13:15:33 Info Using FlareSolverr: http://192.168.0.208:8191
02-19 13:15:33 Info Using HTTP Client: HttpWebClient2
02-19 13:15:33 Info Loading Native indexers ...
02-19 13:15:33 Info Loaded 73 Native indexers.
02-19 13:15:33 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
02-19 13:15:34 Info Loaded 534 Cardigann indexers.
02-19 13:15:34 Info Loaded 607 indexers in total
02-19 13:15:34 Info Adding aggregate indexer ('all' indexer) ...
02-19 13:15:34 Info Adding filter indexer ('type:public' indexer) ...
02-19 13:15:34 Info Adding filter indexer ('type:private' indexer) ...
02-19 13:15:34 Info Adding filter indexer ('type:semi-public' indexer) ...
02-19 13:15:34 Info Jackett startup finished in 1.608 s
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://127.0.0.1:9117
Application started. Press Ctrl+C to shut down.
[ls.io-init] done.
```

**Comment by garfield69** [comment]
@ilike2burnthing  is there a better method?

**Comment by PrzemekSkw** [comment]
Hello, thank You very much. I change server config.json and now works again 😀
Why I get that warning? Do I have to set admin pass if I have jackett only in local network?
![Screenshot_2024-02-19-18-15-55-74_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/Jackett/Jackett/assets/25219988/56c05ca2-f2ef-4ebe-8a89-eb003afabcdf)

**Comment by garfield69** [comment]
The original intent (as far as I understand it) was to warn native Jackett users about WEB exposure to an unsecured Jackett dashboard.
But the author may not have considered that Docker Jackett users need external access enabled even on their LAN which is a complication.
@mynameisbogdan @ilike2burnthing thoughts?

**Comment by PrzemekSkw** [comment]
I can live with that warning if my jackett is safe without password in local address only. Thanks for help.
Regards.

**Comment by garfield69** [comment]
I think a dismiss button is a good idea, and I would go further and suggest the cookie be set to life. If the user decides to dismiss the warning, then we have done our bit to point an issue out, and its up to the user to accept and add a password, or ignore it and deal with the consequences.

**Comment by LazyBacO** [comment]
Thanks @garfield69 it allow me to change the port of the web UI , i made a mistake by removing the ''1 '' in front of 19117 , in the docker cmd i change everything like i want without the need of the web UI ,it work fine now !
