### ISSUE TITLE
[wolfmax4k] (configuring) Address not available (wolfmax4k.com:80): Address not available

### ISSUE THREAD

**Issue by esguti** [Jackett/Jackett#15073]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Docker
```

### Description

wolfmax4k.com is not available and wolfmax4k.net does not work

### Logged Error Messages

```text
Address not available (wolfmax4k.com:443): Address not available
```

**Comment by Jakmaster199** [comment]
Hi @esguti 

First of all, the original URL and the only one of Wolfmax4K is the one that ends on ".com". The other one is a fake clon which always redirect to ads pages and doesn't have real content.

For other side, maybe the website is blocked by your ISP. At this moment, with DIGImobil the URL loads perfectly:

![image](https://github.com/Jackett/Jackett/assets/1685032/077b82ae-5ffc-4b67-bb9f-1566081070be)

Can you try to load it behind a proxy or tor network?

**Comment by esguti** [comment]
Thank you for your quickly response. It works using Tor, my ISP should be blocking the connection.
