### ISSUE TITLE
[rarbg] (configuring) Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by ContraktTV** [Jackett/Jackett#15079]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-02-24 03:27:06 	Error 	

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

2024-02-24 03:27:01 	Warn 	

Request to RARBG failed with status ServiceUnavailable. Retrying in 1s... (Attempt 2 of 2).

2024-02-24 03:26:55 	Warn 	

Request to RARBG failed with status ServiceUnavailable. Retrying in 0.5s... (Attempt 1 of 2).
```

### Description

Attempted to add RARBG.TO as a client
Returns error: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### Logged Error Messages

```text
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
```

**Comment by garfield69** [comment]
1. the environment section of this ticket is not a place to put your log error messages, it is where you tell us about the JAckett version, which platform you are running it on, etc. in future please fill in the form correctly.
2. the RARBG indexer was removed 4 years ago back in Dec 2020. So if you are still seeing this then your Jackett is well and truly out of date and is not supported. Update to the latest Jackett version.
3. there is an indexer called TheRARBG, but that does not support a domain of rarbg.to. Use only the domains available in the config.
4. if you are having trouble using TheRARBG indexer, then open a fresh ticket, and fill in the form correctly, and we can take a close look.
