### ISSUE TITLE
[req]: https://www.dkb.si/

### ISSUE THREAD

**Issue by Wannacry-ops** [Jackett/Jackett#15082]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: dkb
- URL: https://www.dkb.si/
- Description: anime en multiples idiomas
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments:
```

**Comment by garfield69** [comment]
All the dkb releases are on nyaa.si whose results page is more in line with what Jackett likes to process.
The dkb site shows very little detail other than a title, date and poster, missing the size, seeds, leech and the .torrent or magnet links.
there is an alternate view which has just the title and the .torrent (which points to the nyaa.si download link) and a magnet, and that is all.
I do not see the point of creating an indexer for this site.
