### ISSUE TITLE
[enhancement] [webui]: Add colour coding to indexer results paragraph

### ISSUE THREAD

**Issue by vonvenera** [Jackett/Jackett#15080]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Not a problem, but it makes it easier to spot indexers that returned errors, no results or max results, especially if using10+ indexers.

### Describe the solution you'd like

Add color coding to list of indexers used in search:
 - red for error
 - opacity0.5 for no results
 - yellow for indexers that returned max number of results, indicating that search query was not specific enough 

Question: Is there a way to know for all (or most) indexers if they query generated more results than displayed (for example, multiple pages of results, but Jackett only parses the first one)?
If not, how hard would it be to add this? One solution is to add textbox into tracker configuration for users to enter max number of results configured for that tracker. If user does not add any number, they never see yellow style.

Example:
![image](https://github.com/Jackett/Jackett/assets/132844947/dc02a169-a2f0-44b0-a89a-c45f38368e1e)

If approved, I can submit PR.

**Comment by garfield69** [comment]
>Question: Is there a way to know for all (or most) indexers if they query generated more results than displayed (for example, multiple pages of results, but Jackett only parses the first one)? If not, how hard would it be to add this? 

The current design of Jackett does not allow for that information to be made available. There are multiple enhancement tickets open for adding pagination processing, but most have stalled.
Currently, Jackett aims to retrieve up to 100 results, preferably from the first page of the sites torrent search page. But some site only offer as little as 10 results per page, some 25, others 40.
Jackett avoids performing multiple page fetches, if possible, to try to reach the 100 quota, even with embedded delays between requests.
These days, many sites are hyper sensitive to potential DDoS attacks, and Jackett tries to avoid stressing sites into blocking the users IP address or being labelled a spammer or worse.

The Jackett  dashboard search is actually a small part of the Jackett function, its main goal is to provide Torznab responses for *arr apps, which only expect up to 100 results (some reject more), and do not need to fetch every possible result in one request as they  provide a full query, so usually get back a smaller number of specific results.
Its only dashboard search users that are vague in their query keyword usage, and this minority are not worth the effort to rewrite Jackett significantly to support your yellow coded suggestion.

I would suggest red for error, green for success and leave it at that.

I'm always open to opinions from the other team members, so don't treat what I've said as the definitive answer set in concrete. ;-)

**Comment by vonvenera** [comment]
Thanks for your feedback.

> These days, many sites are hyper sensitive to potential DDoS attacks, and Jackett tries to avoid stressing sites into blocking the 
> users IP address or being labelled a spammer or worse.

> Its only dashboard search users that are vague in their query keyword usage, and this minority are not worth the effort to rewrite Jackett significantly to support your yellow coded suggestion.
> 
> I would suggest red for error, green for success and leave it at that.

Yea, this makes sense. I wasn't thinking about performing extra requests per tracker for manual search, more in the lines of... if parser, while parsing first page of results, also takes a look at the pagination on the tracker's 1st results page and returns total number of torrents along with actual torrents from first page. I could make use of that, but its not something to add just for a bit of styling on manual search page.

**Comment by ilike2burnthing** [comment]
Red for error makes sense. I do like 0.5 opacity/grey for 0 results (a quick way to identify them, without being in your face), then just leave those with results as black, rather than making things too colourful.

Make a PR, we can comment more once we can play around with it, get a better idea of how it looks. Thanks.

**Comment by garfield69** [comment]
v0.21.1855
