### ISSUE TITLE
[req]: icv ilcorsaroverde

### ISSUE THREAD

**Issue by mtguido87** [Jackett/Jackett#15084]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: icv ilcorsaroverde
- URL: https://www.icv-crew.com/forum/
- Description: italian forum tracker
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): no
- Additional Comments: 

In the past it seems to me that this tracker was added but now it is no longer present. How come? 
It is one of the best from Italy. It's a shame.
Would it be possible to restore it?

Thank you
```

**Comment by garfield69** [comment]
No it is not possible.
See https://github.com/Jackett/Jackett/issues/3189#issuecomment-1248637673 for explanation.
