### ISSUE TITLE
Update Gimmepeers.yml  ( remove imdbid for TV search) Not needed.

### ISSUE THREAD

**Issue by nrgneilo** [Jackett/Jackett#15089]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Linux, windows.
```

### Description

Gimmepeers doesn't use imdb in their search for TV listing. Please remove the imdbid  search capabilities for TV-search in the gimmepeers.yml   Having the imdb is preventing successful searches.   

### Logged Error Messages

```text
modes:
    search: [q]
    tv-search: [q, season, ep, imdbid, genre]
    movie-search: [q, imdbid, genre]
    music-search: [q]
    book-search: [q]
```

**Comment by garfield69** [comment]
v0.21.1855
