### ISSUE TITLE
[1337x] (testing) Exception (1337x): certificate validation failed: [Subject]  CN=1337x.to[Issuer]  CN="allot.com/emailAddress=info@allot.com", OU=Allot, O=Allot, L=Madrid, S=Madrid, C=ES[Serial Number]  0082B3B165000000004801000000000000[Not Before]  12/16/2016 2:07:49 PM[Not After]  12/16/2026 2:07:49 PM[Thumbprint]  7706900EE8B990774F31D5D0B0369C4D41F7F4F3: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by mar-i0** [Jackett/Jackett#15098]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: Chrome from Windows
OS version: Linux 5.10.0-27-amd64 #1 SMP Debian 5.10.205-2 (2023-12-31) x86_64 GN                                                                                                                                                             U/Linux
Environment version: Running on plex
Running in Docker: no
Jacket variant: Jackett v0.21.1873
```

### Description

it simply stop working

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (1337x): certificate validation failed: [Subject] CN=1337x.to [Issuer] CN="allot.com/emailAddress=info@allot.com", OU=Allot, O=Allot, L=Madrid, S=Madrid, C=ES [Serial Number] 0082B3B165000000004801000000000000 [Not Before] 12/16/2016 2:07:49 PM [Not After] 12/16/2026 2:07:49 PM [Thumbprint] 7706900EE8B990774F31D5D0B0369C4D41F7F4F3 : The SSL connection could not be established, see inner exception.
Click here to open an issue on GitHub for this indexer.
```

### Screenshots

![jackett](https://github.com/Jackett/Jackett/assets/61831928/703a30a3-fcb4-4d3a-b5ee-f1d8f9648dde)

**Comment by garfield69** [comment]
Your ISP is blocking your access to the domain your Jackett indexer is using, and routing you to a black hole owned by Allot Madrid.
Try each of the other alternate domains on the indexer config and if none work then read and try out https://github.com/Jackett/Jackett/wiki/TroubleShooting#a-connection-attempt-failed
