### ISSUE TITLE
[req]: Heavens-Hell

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#15092]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Heavens-Hell
- URL: https://heavens-hell.info
- Description: Heavens-Hell is a Private Torrent Tracker for MUSIC / AUDIO SOFTWARE
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MST 24h MR 0.5
- Additional Comments: 
engine:  TS Special Edition v.8.0 
Registration open ATM
```

**Comment by garfield69** [comment]
v0.21.1861

**Comment by ilike2burnthing** [comment]
https://heavens-hell.info/
- ERR_CONNECTION_TIMED_OUT
- MySQL ERROR: Check server logs to see more information about this issue.

**Comment by garfield69** [comment]
working for me

**Comment by ilike2burnthing** [comment]
https://heavens-hell.info/ - redirect loop to https://heavens-hell.info/ts_error.php?errorid=5

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://heavens-hell.info/ cloudflare  SSL handshake failed Error code 525

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://heavens-hell.info/ Server Error 503 Service Temporarily Unavailable

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://heavens-hell.info/ ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
Aaaaand back up :P

**Comment by garfield69** [comment]
https://heavens-hell.info/ ERR_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://heavens-hell.info/ 503 Service Temporarily Unavailable

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/15092#issuecomment-2028316077

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
site still under attack, flaky online presence atm
https://github.com/Jackett/Jackett/issues/15092#issuecomment-2028316077

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/15092#issuecomment-2028316077

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/15092#issuecomment-2016674616

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/15092#issuecomment-2016674616

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/15092#issuecomment-2027819370

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/15092#issuecomment-2016674616

Also, before this I wasn't able to log in and recovery said my account didn't exist.

**Comment by garfield69** [comment]
MY credentials are invalid, recovery does not know my email, and registration requires an invite code. Bah!

**Comment by garfield69** [comment]
Online, registration open ATM. I've registered, pending admin validation.

**Comment by garfield69** [comment]
And then, just like that, I'm gone again. I'm deleting the indexer, its not worth the trouble.

**Comment by garfield69** [comment]
v0.21.2542
