### ISSUE TITLE
[req]: pass proxy creds to FlareSolverr

### ISSUE THREAD

**Issue by Breaknus** [Jackett/Jackett#15099]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I'm using Jackett with socks5 proxy with auth, but for some indexers I need using FlareSolverr via exact same proxy. I have looked to FlareSolverr logs and found that creds for proxy does not passing through

`Incoming request => POST /v1 body: {'postData': 'someday, 'maxTimeout': 55000, 'cmd': 'request.post', 'url': 'https://some/tracker.php', 'proxy': {'url': 'socks5://<proxyip>:8088'}}`

Also I found false flag to this function: 
https://github.com/Jackett/Jackett/blob/4f5a53fbd622ef44c26962c1f2e1e01e050815e1/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs#L63

### Describe the solution you'd like

Jackett should pass proxy url with creds to FlareSolverr.

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverrSharp/issues/23

There is a PR there for it, and I did test it a while ago with https://www.nuget.org/packages/FlareSolverrSharp-fork but couldn't get it to work.

**Comment by garfield69** [comment]
v0.21.1915

**Comment by Breaknus** [comment]
Thanks a lot! Tested it with http proxy with auth and noname club!
