### ISSUE TITLE
ExtremlymTorrents - Error: La operación de E/S se anuló por una salida de subproceso o por una solicitud de aplicación.

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#15096]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: yes
Using proxy: Enable
Running in Docker: No
Starting Jackett: v0.21.1873
```

### Description

Maybe another available domain to fix this issue?

### Logged Error Messages

```text
See full log with present domain.
[full log.txt](https://github.com/Jackett/Jackett/files/14432685/full.log.txt)
```

**Comment by ilike2burnthing** [comment]
Again, site issue.
