### ISSUE TITLE
LostFilm not work

### ISSUE THREAD

**Issue by rummyvn** [Jackett/Jackett#15109]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett v0.21.1915
Environment version: 6.0.27 (/app/Jackett/)
OS version: Unix 6.1.64.0 (64bit OS) (64bit process)
Jackett variant: CoreLinuxMuslAmdx64
File /etc/issue: Welcome to Alpine Linux 3.18
Running in Docker: Yes (image build: v0.21.1897-ls323)
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
App config/log directory: /config/Jackett
Using proxy: Disabled
Using FlareSolverr: http://192.168.1.221:8191
Using HTTP Client: HttpWebClient2
```

### Description

Lostfilm not work again. Site good access link (like in lostfilm.json, see shot):
https://www.lostfilmtv5.site/
[log_jackett.txt](https://github.com/Jackett/Jackett/files/14469815/log_jackett.txt)

### Logged Error Messages

```text
in attache
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/139438950/76aac99c-f1de-43cd-9103-f941c74e4b89)
![image](https://github.com/Jackett/Jackett/assets/139438950/1c14d813-5ab3-45a8-ba9a-ca294511432a)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14954#issuecomment-1974922299
