### ISSUE TITLE
[req]: linux uninstall scripts

### ISSUE THREAD

**Issue by slrslr** [Jackett/Jackett#15102]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

missing uninstallation command/s on README.md

### Describe the solution you'd like

https://github.com/Jackett/Jackett?tab=readme-ov-file#install-on-linux-amdx64
Before i install something, i would like to know how to work with it and how to uninstall it.
There is a script install_service_systemd.sh but not uninstall_service_systemd.sh

On README i can not see any easily accessible index of README sections that would allow me to quickly navigate through pretty long README. If you tell me basic acceptable syntax and where to place it in README, i may make such index and PR.

**Comment by ilike2burnthing** [comment]
The top right of the readme has a list button (3 dots followed by 3 lines), clicking this provides the outline or index.

As for an uninstall script, there is one for MacOS (created back in 2020 by a contributor), but yes there isn't one for Linux.

**Comment by garfield69** [comment]
A PR raised by any volunteer that would basically take install_service_systemd.sh and revert it to create an uninstall_service_systemd.sh would be welcomed.

**Comment by bakerboy448** [comment]
Chat gpt for the start of a revised install script S directions.  
https://chat.openai.com/share/22b7b407-4c44-43a8-9e1d-85972e36b4e6

and a matching uninstall from gpt
```bash
#!/bin/bash

# Define the directory where Jackett was installed
##INSTALL_DIR="/opt/jackett"

# Define the systemd service file for Jackett
##JACKETT_SERVICE_PATH="/etc/systemd/system/jackett.service"

# Ensure the script is running with superuser privileges
if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run as root. Try using 'sudo bash $0'."
  exit 1
fi

echo "Starting Jackett uninstallation..."

# Stop the Jackett service
echo "Stopping the Jackett service..."
if systemctl stop jackett.service; then
  echo "Jackett service stopped successfully."
else
  echo "Failed to stop the Jackett service. It may not have been running."
fi

# Disable the Jackett service
echo "Disabling the Jackett service..."
if systemctl disable jackett.service; then
  echo "Jackett service disabled successfully."
else
  echo "Failed to disable the Jackett service."
fi

# Remove the systemd service file
echo "Removing the systemd service file..."
if rm -f "$JACKETT_SERVICE_PATH"; then
  echo "Systemd service file removed successfully."
else
  echo "Failed to remove the systemd service file. File may not exist."
fi

# Reload systemd to remove traces of the Jackett service
echo "Reloading systemd daemon..."
systemctl daemon-reload

# Remove the Jackett installation directory
echo "Removing Jackett installation directory..."
if rm -rf "$INSTALL_DIR"; then
  echo "Jackett installation directory removed successfully."
else
  echo "Failed to remove the Jackett installation directory. Directory may not exist."
fi

echo "Jackett has been successfully uninstalled."
```
