### ISSUE TITLE
[req]: LilleSky.org

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#15104]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: LilleSky.org
- URL: https://lillesky.org/
- Description: LilleSky.org is a Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MST 7 days, global MR 0.4
- Additional Comments: 
Engine: unit3d 7.2.5
Signups currently open
Couldn't find any rule or FAQ entry for account activity
```

**Comment by garfield69** [comment]
v0.21.1915

**Comment by garfield69** [comment]
https://lillesky.org/ Under Maintenance

**Comment by garfield69** [comment]
While it seems they have upgraded to 8.0.2 they also appear to have reset torrent categories and lost the rules/FAQ etc.
But at least the accounts were carried over ;-)

**Comment by garfield69** [comment]
v0.21.2476

**Comment by garfield69** [comment]
https://lillesky.org/ swizzin login plus selfsigned CA CN=sd-55398.dedibox.fr

**Comment by garfield69** [comment]
v0.22.372
