### ISSUE TITLE
Wrong torrent size for ABTorrents

### ISSUE THREAD

**Issue by costaht** [Jackett/Jackett#15110]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: unknown)
File /etc/issue: Welcome to Alpine Linux 3.18
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.14.0.419 (64bit OS) (64bit process)
Environment version: 6.0.27 (/app/)
Jackett Data will be stored in: /config
Starting Jackett v0.21.1915
```

### Description

I noticed that Jackett is reporting the incorrect size of Audiobooks from ABTorrents. As you can see below, for Audiobooks Jackett is reporting GB as MB, MB as KB and so on.

![abtorrents-incorrect](https://github.com/Jackett/Jackett/assets/50637431/41f66b86-e321-4b71-983c-a40e498523fd)

On the other hand, Ebooks' torrents have their size reported correctly:

![abtorrents-correct](https://github.com/Jackett/Jackett/assets/50637431/9b29d73c-6979-47b3-94f8-6c61de2304ca)

I don't know if that bug affects other categories, but I also noticed that the results order on Jackett don't match the website order, so maybe there's another problem with sorting too.

Let me know if you guys need any extra info.

### Logged Error Messages

```text
N/A
```

**Comment by garfield69** [comment]
v0.21.1932
