### ISSUE TITLE
BTSOW (under proxy use) --> certificate validation failed: [Subject]   CN=btsow.motorcycles, O="OpenDNS, Inc."

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#15119]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: yes
Using proxy: Enable
Running in Docker: No
Starting Jackett: v0.21.1939
```

### Description

Site is not accessible using my proxy (Jackett or web browser), nevertheless I can use it without proxy
Maybe can be fixed in Jackett app to be accessed with my proxy?
Maybe another alternative domain available?

I know this issue opened more than six years old could be a solution too: https://github.com/Jackett/Jackett/issues/2539
I appreciate it will be advanced this year if possible.

Full log of error: 
[full log.txt](https://github.com/Jackett/Jackett/files/14486653/full.log.txt)

### Logged Error Messages

```text
See full log in "Description" section.
```

**Comment by ilike2burnthing** [comment]
If you get the same issue in browser then the solution is to use a different proxy server or provider.

**Comment by AARON8888** [comment]
Many thanks @ilike2burnthing
I have just solved this problem in Jackett which was hard for me. 
I can run well in Jackett using my home IP, or my proxy alone, or vpn too. The problem is arised when I use vpn+proxy altogether due to DNS OpenDNS action via Cisco Umbrella´s blocking.

Firstly I had to [detele HSTS connection](https://www.ssl2buy.com/wiki/how-to-clear-hsts-settings-on-chrome-firefox-and-ie-browsers#:~:text=Clearing%20HSTS%20in%20Chrome&text=Open%20Google%20Chrome,simply%20press%20the%20Delete%20button.) and secondly exclude domain of site btsow.motorcycles in my vpn app.

**Comment by AARON8888** [comment]
Hi @ilike2burnthing 
BTSOW site is reached with my proxy well in my web browser (chrome), but I cannot in Jackett. It´s strange since I use same proxy in Jackett too.
See [full log.txt](https://github.com/Jackett/Jackett/files/14692461/full.log.txt)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/946011e2ec2b5e2e00639fc3e01f0c7942d4c64f
