### ISSUE TITLE
[req]: Tormac

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#15130]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Tormac
- URL: https://tormac.org/
- Description: Tormac is a RUSSIAN Private Torrent Tracker for MOVIES / TV / GENERAL for Apple products
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MR: above 0.3
- Additional Comments: signups open
```

**Comment by garfield69** [comment]
v0.21.1981
