### ISSUE TITLE
slosoul - certificate validation failed: [Subject]   CN=slosoul.net

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#15133]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: yes
Using proxy: Enable
Running in Docker: No
Starting Jackett: v0.21.1981
```

### Description

Certificate validation failed: [Subject]   CN=slosoul.net
See attached full log: 
[full log.txt](https://github.com/Jackett/Jackett/files/14545837/full.log.txt)

### Logged Error Messages

```text
See above attachment.
```

**Comment by garfield69** [comment]
v0.21.1991
