### ISSUE TITLE
[req]: dx-team.org

### ISSUE THREAD

**Issue by monnolo** [Jackett/Jackett#15142]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: dx-team.org
- URL: https://dx-team.org/
- Description: DX team is a semi-private torrent tracker for Console, Movies, Audio, PC, TV, XXX, Books, Other
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments: None
```

**Comment by ilike2burnthing** [comment]
Where are the torrents? I'm only seeing direct downloads.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
