### ISSUE TITLE
rutor.info http problem

### ISSUE THREAD

**Issue by DogancanYr** [Jackett/Jackett#15146]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.22635.0 (64bit OS)
Environment version: 6.0.28 (C:\ProgramData\Jackett\)
Starting Jackett v0.21.2025
```

### Description

rutor.info site should be set to https. When I try to access it via http, it does not open.

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment]
http://new-rutor.org/ returns пс. Что-то пошло не так, попробуйте перезагрузить страницу
https://new-rutor.org/ returns ERR_CONNECTION_REFUSED
it used to be the case that https://rutor.is/ and https://rutor.info/ would also return ERR_CONNECTION_REFUSED  but that appears to be no longer the case, so I shall update the indexer to default to https for those two domains.

**Comment by garfield69** [comment]
v0.21.2031
