### ISSUE TITLE
[Request] Add Torrentvault 

### ISSUE THREAD

**Issue by seedboxer** [Jackett/Jackett#1514]
This is a very old and stable tracker with very good pre-times and gets under used.
Please, can it be added to jackett so it can be better utilized . #

**Comment by Vorbroker** [comment]
Please add this tracker. The site currently has open registration until 9/11/2017

**Comment by JakeShirley** [comment]
+1. Love this tracker, would be great to use it with Jackett

**Comment by kaso17** [comment]
added via 40ab7280caf0142ffd982c902ac6310d2617856f

**Comment by antigravity83** [comment]
Great news- unfortuantely doesn't work. Get this error when attempting to add

An error occurred while sending the request: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /tmp/buildd/mono-5.0.1.1/external/boringssl/ssl/handshake_client.c:1132)

**Comment by kaso17** [comment]
@antigravity83 did you follow the steps from the readme/troubleshooting section?

**Comment by antigravity83** [comment]
@kaso17 
Sorry yes, I reloaded the certs, restarted Jackett, and still no luck.

**Comment by antigravity83** [comment]
@kaso17

Any ideas? Reloaded the certs but still getting that error.

**Comment by kaso17** [comment]
Ok, they're sending an incomplete CA chain.
See https://www.ssllabs.com/ssltest/analyze.html?d=www.torrentvault.org&latest
Please contact the site staff and let them know.

**Comment by kaso17** [comment]
Workaround has been added via 27f0448caf498cd9237735b5776b55330549b492

**Comment by antigravity83** [comment]
Thankyou :)

**Comment by kaso17** [comment]
anyone knows if torrentvault is still alive?

**Comment by Vorbroker** [comment]
Something happened. A database got deleted on accident or something and
messed everything up. I think they just gave up and took the site down
after they couldn't figure out how to fix it.

**Comment by kaso17** [comment]
removed via 70a47c80b5fb2014737aae9f6e7826dfe3beeb01
