### ISSUE TITLE
[passthepopcorn] (updating) Parse error

### ISSUE THREAD

**Issue by shanleishe** [Jackett/Jackett#15145]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
出错
```

### Description

出错

### Logged Error Messages

```text
出错
```

### Screenshots

出错

**Comment by garfield69** [comment]
Totally unacceptable ticket information provided. How do you expect us to help you resolve the problem if you do not provide any  information? 
It's like going to the doctor and say I am sick, and expecting them to give you a magic pill.
Open a new ticket and provide the requested information, if you want help with your problem.
