### ISSUE TITLE
[thepiratebay] (testing) Exception (thepiratebay): A task was canceled.: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

### ISSUE THREAD

**Issue by LunchBox951** [Jackett/Jackett#15147]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using Proxy: Disabled
Running in Docker: No
Jackett variant: CoreLinuxAmdx64
OS Version: Unix 6.7.9.1 (64bit OS)
Environment Version: 6.0.28
Jackett Version: v0.21.2025
```

### Description

Multiple indexers are timing out sporadically causing cascading issues.

### Logged Error Messages

```text
2024-03-15 02:04:32.2052 Error Jackett.Common.IndexerException: Exception (thepiratebay): A task was canceled.

[v0.21.2025.0] Jackett.Common.IndexerException: Exception (thepiratebay): A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 581
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1521
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 755
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 320
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
the indexer TPB is working for me which suggests the issue is at your end.
If any of your public indexers are in this list then you need to use flaresolverr: 1337x, Cinecalidad, EXTTorrents, ExtraTorrent.st, LePorno.info, MacTorrentsDownload, TorrentQQ, Torrent[CORE], iDope

for the rest, have a read of this wiki https://github.com/Jackett/Jackett/wiki/TroubleShooting/#a-task-was-cancelled and see if that helps you figure out your problem.

**Comment by LunchBox951** [comment]
The issue is not ISP related since I have a windows system with the same settings working perfectly fine on the same network.

**Comment by garfield69** [comment]
The indexer for TPB uses the API server at  https://apibay.org/. The sitelinks in the indexer are used only to view a torrent details page when you click on the name.
open a browser on the same machine that is running jackett and see if you get a response from https://apibay.org/precompiled/data_top100_recent.json

**Comment by LunchBox951** [comment]
It returns:

`[{"id":74858860,"info_hash":"33AA2507558E1C0CEB8755EDF58255CAAE9C9C2A","category":205,"name":"Food Paradise S05E11 XviD-AFG","status":"vip","num_files":6,"size":689996763,"seeders":0,"leechers":0,"username":"TvTeam","added":1710553424,"anon":0,"imdb":null},{"id":74858859,"info_hash":"83DF3C8B091AF223FEDED2F5B8348223A6BC55E3","category":506,"name":"BenefitMonkey 24 03 07 Silvia Soprano XXX 480p MP4-XXX [XC]","status":"vip","num_files":2,"size":306449962,"seeders":3,"leechers":2,"username":"Mesoglea","added":1710553357,"anon":0,"imdb":null},{"id":74858858,"info_hash":"985EA5C448E8142A8160095F4B378F1CE0A1AF98","category":205,"name":"Property.Brothers.S01E13.WEB.x264-TORRENTGALAXY","status":"vip","num_files":4,"size":501021017,"seeders":3,"leechers":19,"username":"TGxGoodies","added":1710553318,"anon":0,"imdb":null},{"id":74858857,"info_hash":"8BD5F76273CBF3A3452D153C16B8F31E13F61A25","category":505,"name":"WhenGirlsPlay 24 03 16 Cherry Kiss And Gizelle Blanco Sneaky Mi","status":"vip","num_files":2,"size":1386009987,"seeders":12,"leechers":5,"username":"Mesoglea","added":1710553240,"anon":0,"imdb":null},{"id":74858856,"info_hash":"409DDC3EE0C7A29E53876D9A33B27772780B5974","category":505,"name":"BenefitMonkey.24.03.07.Silvia.Soprano.XXX.1080p.HEVC.x265.PRT[Xv","status":"vip","num_files":3,"size":715771673,"seeders":6,"leechers":4,"username":"GalaXXXy","added":1710553154,"anon":0,"imdb":null},{"id":74858855,"info_hash":"10BE165BF689E43D065E4E00977A62C97ABF8E57","category":505,"name":"Wicked.24.03.15.Kay.Lovely.So.Extra.XXX.1080p.HEVC.x265.PRT[XvX]","status":"vip","num_files":3,"size":402131286,"seeders":1,"leechers":6,"username":"GalaXXXy","added":1710553125,"anon":0,"imdb":null},{"id":74858854,"info_hash":"6106543165A97F586433448F0C0ADBE9B217458A","category":501,"name":"TeensLoveHugeCocks 24 03 16 Lily Starfire And Chanel Camryn XXX XviD-iPT Team","status":"vip","num_files":12,"size":361188789,"seeders":0,"leechers":0,"username":"TvTeam","added":1710553102,"anon":0,"imdb":null},{"id":74858853,"info_hash":"7F1919DC00BF8F6AF7C08CFB99B902DC0712B956","category":501,"name":"PublicAgent 24 03 16 Mini Mitzix XXX XviD-iPT Team","status":"vip","num_files":12,"size":229594564,"seeders":0,"leechers":0,"username":"TvTeam","added":1710553094,"anon":0,"imdb":null},{"id":74858852,"info_hash":"4E8BE8305B64D6B58A730407F69724498E7F3997","category":505,"name":"PublicAgent 24 03 16 Mini Mitzix XXX 1080p MP4-WRB [XC]","status":"vip","num_files":2,"size":1480005669,"seeders":12,"leechers":10,"username":"Mesoglea","added":1710553089,"anon":0,"imdb":null},{"id":74858851,"info_hash":"5E2C32B2C428CDF1BDCE188B8C3D824FE03E3F6C","category":501,"name":"MomXXX 24 03 16 Helina Dream XXX XviD-iPT Team","status":"vip","num_files":12,"size":278026929,"seeders":0,"leechers":0,"username":"TvTeam","added":1710553086,"anon":0,"imdb":null},{"id":74858850,"info_hash":"0147B1F44F758B810B34FDE45141AF9672278D15","category":205,"name":"Food Paradise S05E12 XviD-AFG","status":"vip","num_files":6,"size":680659129,"seeders":1,"leechers":0,"username":"TvTeam","added":1710553084,"anon":0,"imdb":null},{"id":74858849,"info_hash":"4A64D769BCB7272CC164B6B3F7A3D969ED6E8DF3","category":505,"name":"MetArtX.24.03.15.Ariana.Cortez.Macarons.XXX.720p.HEVC.x265.PRT[X","status":"vip","num_files":3,"size":176534150,"seeders":1,"leechers":5,"username":"GalaXXXy","added":1710553062,"anon":0,"imdb":null},{"id":74858848,"info_hash":"216ACF85573E5C5432AF610C4BF2B112D884D1F9","category":505,"name":"TeensLoveHugeCocks 24 03 16 Lily Starfire And Chanel Camryn XXX","status":"vip","num_files":2,"size":1513573743,"seeders":11,"leechers":14,"username":"Mesoglea","added":1710553042,"anon":0,"imdb":null},{"id":74858847,"info_hash":"ACB9094805C525652BD8602CC68412FE58B72234","category":505,"name":"MatureNL.24.03.13.Lucinda.And.Marisah.Mature.Anal.Party.XXX.720p","status":"vip","num_files":3,"size":481092222,"seeders":2,"leechers":4,"username":"GalaXXXy","added":1710552963,"anon":0,"imdb":null},{"id":74858846,"info_hash":"D9D6DADE7781BC8227530072A9A334A323A2D2BB","category":507,"name":"BrazzersExxtra 24 03 16 Lexi Lore Some Assistance Please XXX 21","status":"vip","num_files":2,"size":2154170497,"seeders":8,"leechers":8,"username":"Mesoglea","added":1710552916,"anon":0,"imdb":null},{"id":74858845,"info_hash":"CFE0DD6818E9EA9AD09522D032889FC756553098","category":505,"name":"BrazzersExxtra 24 03 16 Lexi Lore Some Assistance Please XXX 10","status":"vip","num_files":2,"size":1590081023,"seeders":11,"leechers":13,"username":"Mesoglea","added":1710552913,"anon":0,"imdb":null},{"id":74858844,"info_hash":"2B35C0CB60A942ACFF46A889CC10140BB07A5648","category":505,"name":"MomXXX 24 03 16 Helina Dream XXX 1080p MP4-WRB [XC]","status":"vip","num_files":2,"size":1232761063,"seeders":10,"leechers":13,"username":"Mesoglea","added":1710552803,"anon":0,"imdb":null},{"id":74858843,"info_hash":"A10107EC4199B3574358AFC4BE40D39AA35B0440","category":501,"name":"BrazzersExxtra 24 03 16 Lexi Lore Some Assistance Please","status":"vip","num_files":12,"size":411573292,"seeders":0,"leechers":0,"username":"TvTeam","added":1710552746,"anon":0,"imdb":null},{"id":74858842,"info_hash":"7657945BBDD7F32FCAD6C2AAA580A23D189DD7B7","category":505,"name":"MetArtX.24.03.15.Ariana.Cortez.Macarons.XXX.1080p.HEVC.x265.PRT[","status":"vip","num_files":3,"size":267086691,"seeders":14,"leechers":14,"username":"GalaXXXy","added":1710552547,"anon":0,"imdb":null},{"id":74858841,"info_hash":"D7BAD54BAEC11FE830227A61CAE5D0D048D2CF03","category":205,"name":"Property.Brothers.S09E12.WEB.x264-TORRENTGALAXY","status":"vip","num_files":4,"size":539239828,"seeders":9,"leechers":19,"username":"TGxGoodies","added":1710552492,"anon":0,"imdb":null},{"id":74858840,"info_hash":"809E83BE4147F1A8CDF686D8ED9FA19EC0CB9C14","category":205,"name":"Food Paradise S05E10 XviD-AFG","status":"vip","num_files":6,"size":606643478,"seeders":1,"leechers":10,"username":"TvTeam","added":1710552463,"anon":0,"imdb":null},{"id":74858839,"info_hash":"81A16D895014383CD2018D3A212F8E6C4D9F3E68","category":205,"name":"Gogglebox.S23E05.480p.x264-RUBiK","status":"trusted","num_files":6,"size":363993866,"seeders":4,"leechers":23,"username":"Saturn5","added":1710552306,"anon":0,"imdb":"tt2762330"},{"id":74858838,"info_hash":"9DC57F114B85C12AF36321AA1A1D7DC1904ACB44","category":505,"name":"WhenGirlsPlay.24.03.16.Cherry.Kiss.And.Gizelle.Blanco.Sneaky.Mir","status":"vip","num_files":2,"size":1386010671,"seeders":2,"leechers":33,"username":"GalaXXXy","added":1710552192,"anon":0,"imdb":null},{"id":74858837,"info_hash":"11653D682DF60E0D7038F1D7B9475518DBE8136F","category":505,"name":"PublicAgent.24.03.16.Mini.Mitzix.XXX.1080p.MP4-WRB[XvX]","status":"vip","num_files":2,"size":1480006353,"seeders":11,"leechers":19,"username":"GalaXXXy","added":1710552190,"anon":0,"imdb":null},{"id":74858836,"info_hash":"2399F463BA07B4C16CEF96F3703316C4C881453F","category":205,"name":"Food Paradise S05E08 XviD-AFG","status":"vip","num_files":6,"size":755318852,"seeders":1,"leechers":12,"username":"TvTeam","added":1710552184,"anon":0,"imdb":null},{"id":74858835,"info_hash":"019F74F15855618055838285C16E4C485B01471B","category":505,"name":"TeensLoveHugeCocks.24.03.16.Lily.Starfire.And.Chanel.Camryn.XXX.","status":"vip","num_files":2,"size":1513574427,"seeders":4,"leechers":44,"username":"GalaXXXy","added":1710552143,"anon":0,"imdb":null},{"id":74858834,"info_hash":"BF23C4678C077DEABAF26E8EAEDDF8C726A2B23B","category":506,"name":"MyLifeInMiami 24 03 07 Baby Nicols Smoking Hot Latina XXX 480p ","status":"vip","num_files":2,"size":195901769,"seeders":5,"leechers":9,"username":"Mesoglea","added":1710552074,"anon":0,"imdb":null},{"id":74858833,"info_hash":"C713FB1ECACD9188C24FEF2462158AC87C8605D0","category":205,"name":"Property.Brothers.S01E07.WEB.x264-TORRENTGALAXY","status":"vip","num_files":4,"size":488943365,"seeders":6,"leechers":18,"username":"TGxGoodies","added":1710552062,"anon":0,"imdb":null},{"id":74858832,"info_hash":"D556632CABB8F8A78112BA2294579F20E8F98820","category":507,"name":"BrazzersExxtra.24.03.16.Lexi.Lore.Some.Assistance.Please.XXX.216","status":"vip","num_files":2,"size":2154171181,"seeders":1,"leechers":16,"username":"GalaXXXy","added":1710552032,"anon":0,"imdb":null},{"id":74858737,"info_hash":"5D417752677C4CA154985C5D67959F618FAD9772","category":208,"name":"Gogglebox S23E05 1080p ALL4 WEB-DL AAC2 0 H 264-NioN","status":"vip","num_files":0,"size":1788686311,"seeders":74,"leechers":139,"username":"jajaja","added":1710552001,"anon":0,"imdb":"tt2762330"},{"id":74858736,"info_hash":"E034CCAC9E7D1D99866AC3D1F3E1D644B18D32AA","category":208,"name":"Gold Rush White Water S07E03 1080p HEVC x265-MeGusta","status":"vip","num_files":0,"size":1074672254,"seeders":43,"leechers":72,"username":"jajaja","added":1710552001,"anon":0,"imdb":"tt7749176"},{"id":74858735,"info_hash":"1CAE55B063D7B3A534819B1B177E559E3F8FBA68","category":208,"name":"Cops S35E31 720p HEVC x265-MeGusta","status":"vip","num_files":0,"size":194889262,"seeders":8,"leechers":21,"username":"jajaja","added":1710552001,"anon":0,"imdb":"tt0305095"},{"id":74858734,"info_hash":"147DFE9DF56A4A418BA6E378B979ED1051EC9EDC","category":208,"name":"The Young and the Restless S51E114 1080p HEVC x265-MeGusta","status":"vip","num_files":0,"size":271285071,"seeders":8,"leechers":27,"username":"jajaja","added":1710552001,"anon":0,"imdb":"tt0069658"},{"id":74858733,"info_hash":"60540B50A267D7DCF87D4A5E4CD92EAFB58B6EF6","category":208,"name":"Masters of the Air S01 COMPLETE 720p ATVP WEBRip x264","status":"vip","num_files":0,"size":2865558827,"seeders":5,"leechers":79,"username":"jajaja","added":1710552001,"anon":0,"imdb":"tt2640044"},{"id":74858738,"info_hash":"62E99BDD9F87FFA4C5EC74CEBADC31C104818D04","category":205,"name":"The Talk 2024 03 15 480p x264-mSD","status":"vip","num_files":0,"size":150814903,"seeders":5,"leechers":13,"username":"jajaja","added":1710552001,"anon":0,"imdb":"tt1740718"},{"id":74858732,"info_hash":"575EC1FC12B22AD682AFA81966E63D1226B7784E","category":506,"name":"ShadySpa 24 03 07 Selina Bentz XXX 480p MP4-XXX [XC]","status":"vip","num_files":2,"size":108368966,"seeders":7,"leechers":4,"username":"Mesoglea","added":1710551991,"anon":0,"imdb":null},{"id":74858731,"info_hash":"D71271C5F9C0203B96C32755A46B93259E8B0A2C","category":505,"name":"BrazzersExxtra.24.03.16.Lexi.Lore.Some.Assistance.Please.XXX.108","status":"vip","num_files":2,"size":1590081707,"seeders":3,"leechers":63,"username":"GalaXXXy","added":1710551790,"anon":0,"imdb":null},{"id":74858730,"info_hash":"EF75A81D1CA14FECC75231175B466D51E6D0D8AA","category":505,"name":"MatureNL.24.03.13.Lucinda.And.Marisah.Mature.Anal.Party.XXX.1080","status":"vip","num_files":3,"size":774943081,"seeders":6,"leechers":8,"username":"GalaXXXy","added":1710551769,"anon":0,"imdb":null},{"id":74858729,"info_hash":"3E3EC6B5731DEE155344998207E5DFCA8AE41A2C","category":505,"name":"DevilsFilm.24.03.15.Kay.Lovely.XXX.720p.HEVC.x265.PRT[XvX]","status":"vip","num_files":3,"size":376097540,"seeders":11,"leechers":9,"username":"GalaXXXy","added":1710551683,"anon":0,"imdb":null},{"id":74858728,"info_hash":"DF4D185DDBE28BA0EDE1A13DA53E757F9672F4E8","category":208,"name":"Property Brothers S09E12 Ready for Home Sweet Home Jaeme and Bli","status":"vip","num_files":4,"size":3228745895,"seeders":5,"leechers":25,"username":"TGxGoodies","added":1710551603,"anon":0,"imdb":null},{"id":74858727,"info_hash":"81D75F1A012EA325FE007C68EC886223DE11C57B","category":205,"name":"Food Paradise S05E09 XviD-AFG","status":"vip","num_files":6,"size":608728164,"seeders":1,"leechers":11,"username":"TvTeam","added":1710551564,"anon":0,"imdb":null},{"id":74858726,"info_hash":"9FD0D89F2DEFC9329C3E2742E77B5B39609C9310","category":506,"name":"ProducersFun 24 03 07 Penny Barber XXX 480p MP4-XXX [XC]","status":"vip","num_files":2,"size":434684266,"seeders":6,"leechers":6,"username":"Mesoglea","added":1710551498,"anon":0,"imdb":null},{"id":74858725,"info_hash":"FC88B38ED2657974FE4B087C464735D8B5656141","category":506,"name":"BreedMe 24 03 07 Roxie Sinner XXX 480p MP4-XXX [XC]","status":"vip","num_files":2,"size":170740675,"seeders":5,"leechers":2,"username":"Mesoglea","added":1710551342,"anon":0,"imdb":null},{"id":74858724,"info_hash":"3A886CEB64C7D769D83037E0E03784B5F3D76857","category":505,"name":"AdultTime.24.03.15.Valentina.Nappi.Katrina.Colt.Cheating.In.Plai","status":"vip","num_files":3,"size":456184689,"seeders":8,"leechers":8,"username":"GalaXXXy","added":1710551330,"anon":0,"imdb":null},{"id":74858723,"info_hash":"A297C5D08DAEAF892CA106F73B8CDFA670B0B66C","category":205,"name":"The Young and the Restless S51E114 1080p HEVC x265-MeGust","status":"vip","num_files":6,"size":299165913,"seeders":1,"leechers":14,"username":"TvTeam","added":1710551291,"anon":0,"imdb":null},{"id":74858722,"info_hash":"EBDC21A2187FBB9206661A90DA003D891B2BDD9B","category":205,"name":"Food Paradise S05E07 XviD-AFG","status":"vip","num_files":6,"size":641803061,"seeders":1,"leechers":14,"username":"TvTeam","added":1710551284,"anon":0,"imdb":null},{"id":74858721,"info_hash":"134CF62C648A30C5CCF660B57D95E0B9EB0AE713","category":505,"name":"ALSAngels.24.03.05.Amber.Moore.Masturbation.XXX.720p.HEVC.x265.P","status":"vip","num_files":3,"size":458958208,"seeders":5,"leechers":1,"username":"GalaXXXy","added":1710551246,"anon":0,"imdb":null},{"id":74858720,"info_hash":"4E6CA53C700336E47CEFE17CCBD48474936EC8ED","category":505,"name":"AllOver30.24.03.14.Ruby.Shades.Ladies.With.Toys.XXX.720p.HD.WEBR","status":"vip","num_files":2,"size":254484711,"seeders":5,"leechers":5,"username":"GalaXXXy","added":1710551220,"anon":0,"imdb":null},{"id":74858719,"info_hash":"3A30C69ECEB8F0E0E927074C499D9DF608A4B087","category":205,"name":"Property.Brothers.S01E11.WEB.x264-TORRENTGALAXY","status":"vip","num_files":4,"size":481228440,"seeders":5,"leechers":19,"username":"TGxGoodies","added":1710551185,"anon":0,"imdb":null},{"id":74858718,"info_hash":"67EDCA8813DF05E4A80F1CE343A6A10B20EA7B69","category":205,"name":"Cops S35E31 720p HEVC x265-MeGusta","status":"vip","num_files":6,"size":205853011,"seeders":4,"leechers":12,"username":"TvTeam","added":1710551003,"anon":0,"imdb":null}]`

**Comment by garfield69** [comment]
so if your browser on the same machine that runs Jackett can view the API TPB, but Jackett gets a task cancelled, then look on your debian for something local that can block access, such as a firewall or anti-malware or something.
