### ISSUE TITLE
[req]: Renew subtorrent request

### ISSUE THREAD

**Issue by Sergiomg86** [Jackett/Jackett#15148]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: SubTorrent
- URL: https://www.subtorrents.eu/
- Description: Spanish public tracker with films and TV
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments: I saw that this request had already been requested before, I have seen the website and I think it is new, I see that the search engine results and the links to the torrents are simple, I don't know if it is viable today to add it as an indexer, already I know you rejected it before but I think the website is new.
```

**Comment by ilike2burnthing** [comment]
Results for series return all episodes on the results' details pages, and the download links are for an external site which involves multiple steps.

Some results for films have a direct link to the torrent, whereas others use the same external site as series.
