### ISSUE TITLE
Just a question to know how to request a tracker

### ISSUE THREAD

**Issue by nikogaug** [Jackett/Jackett#1515]
Hi,
On the wiki, there is a description on how to request a tracker.
An the wiki, we see the list of available categories like this:

> AddCategoryMapping("cat_id", TorznabCatType.Console);
> AddCategoryMapping("cat_id", TorznabCatType.ConsoleNDS);
> AddCategoryMapping("cat_id", TorznabCatType.ConsolePSP);

and in the exemple for FnT there are multicategory like this:

> AddMultiCategoryMapping(TorznabCatType.TVAnime,116, 140, 151, 117, 141, 152, 148);

But when I look on the code of existing tracker, I never see the "AddMultiCategoryMapping". Is it better to list category with or without "AddMultiCategoryMapping" ?

I don't know if I can"t post the question here, but I don't know where to ask it. Sorry for the inconvenient.

**Comment by kaso17** [comment]
The article and the format is outdated.
Please provide the mappings in the newer cardigann format.
See https://github.com/Jackett/Jackett/wiki/Definition-format for a few more details (Caps section).

**Comment by nikogaug** [comment]
Great thanks kaso17. I will look at this.
