### ISSUE TITLE
[req]: AT-12 Project

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#15150]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: AT-12 Project
- URL: https://at-12project.cc/
- Description: AT-12 Project is a Private Torrent Tracker for JAPANESE MOVIES / TV
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): only MR 1.0?
- Additional Comments: signups current open
Engine: UNIT3D 7.0.3?
No account activity info
```

**Comment by garfield69** [comment]
v0.21.2042

**Comment by garfield69** [comment]
https://at-12project.cc/ cloudflare Connection timed out Error code 522

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://at-12project.cc/ cloudflare Web server is down Error code 521

**Comment by ilike2burnthing** [comment]
Currently no torrents on tracker. Announcement:

> Guys, an important update is being carried out and some instabilities may occur.
Old torrents will be deleted and you will only have torrents with original Japanese audio and subtitles.

**Comment by ilike2burnthing** [comment]
2 torrents added now

**Comment by garfield69** [comment]
v0.21.2212

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/15150#issuecomment-2024310052

**Comment by garfield69** [comment]
v0.21.2335
