### ISSUE TITLE
[req]: H-P2P

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#15161]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: H-P2P
- URL: https://h-p2p.xyz/
- Description: H-P2P is a Private Torrent Tracker for OnlyFans XXX
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MST 2 days, MR 1.0 (global?)
- Additional Comments: signups open
Engine: UNIT3D 8.1.3
```

**Comment by garfield69** [comment]
v0.21.2069

**Comment by garfield69** [comment]
Site upgraded to 8.1.3 a little while ago, and I upgraded the indexer and tested successfully.
However, only minutes later, my credentials are no longer valid, neither is my apikey, and registrations are closed.
Just me?

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://h-p2p.cam/ 404 Not Found nginx/1.18.0 (Ubuntu)

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://h-p2p.cam/ Bad gateway Error code 502

**Comment by garfield69** [comment]
online but intermittent 502 still occur

**Comment by garfield69** [comment]
https://h-p2p.cam/ DNS_PROBE_FINISHED_NXDOMAIN (DNS Lookup Error)

**Comment by garfield69** [comment]
https://h-p2p.xyz/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.22.416
