### ISSUE TITLE
Old Greek Tracker  - test search => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#15165]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: yes
Using proxy: Enable
Running in Docker: No
Starting Jackett: v0.21.2069
```

### Description

See attached full log. [
[full log.txt](https://github.com/Jackett/Jackett/files/14641286/full.log.txt)
](url)

### Logged Error Messages

```text
See above full log.
```

**Comment by garfield69** [comment]
fixed by 48af896f911d4856d633d4d8ab29152967952c05 2 hours ago.
save your effort raising a ticket by checking https://github.com/Jackett/Jackett/commits/master/ first ;-)
