### ISSUE TITLE
[mteamtp2fa] (updating) Login failed: Selector "a[href="logout.php"]" didn't match

### ISSUE THREAD

**Issue by JiaoXing** [Jackett/Jackett#15179]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
无法登陆
```

### Description

无法登陆

### Logged Error Messages

```text
无法登陆
```

**Comment by garfield69** [comment]
1. Totally unacceptable report. Next time fill in the form correctly by providing the requested information.
2. Stating you cannot log in is not helpful to us for diagnosing a problem.
3. As it happens, this is related to #15177 so I'm closing this as a duplicate.
4. Follow the other ticket for progress on this issue.
