### ISSUE TITLE
[hdspace] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#15178]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

the hdspace site is offline

### Logged Error Messages

```text
https://hd-space.org/ cloudflare Web server is down Error code 521
```

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://hd-space.org/ cloudflare Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://hd-space.org/ No Sponsors (domain expired, parked)

**Comment by garfield69** [comment]
online
