### ISSUE TITLE
[req]: m-team is not avaliabled now

### ISSUE THREAD

**Issue by qx** [Jackett/Jackett#15183]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Please check
- URL: https://kp.m-team.cc/
- Description: 
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): private
- Additional Comments: this site has been updated,changed login way ,please check
```

**Comment by qx** [comment]
![Uploading 截屏2024-03-26 06.53.16.png…]()

**Comment by garfield69** [comment]
Refer to #15177
We have had to remove the yaml two indexers got mteamtp and replace them with a new indexer written in C#.
The new **M-Team - TP** indexer will be available once we publish the latest Jackett release, which is due out in about 7 hours or so.
