### ISSUE TITLE
[req]: Modify the old TorrentKitty

### ISSUE THREAD

**Issue by zY3unxTUEqszn7w** [Jackett/Jackett#15189]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
The old torrentkitty can not be connected. The new url should be here`https://torkitty.com/search/`.

#6833
```

**Comment by garfield69** [comment]
out of the current list of alternate domains
https://www.torrentkitty.tv/
https://www.torrentkitty.se/
https://www.torrentkitty.io/
https://www.torrentkitty.vip/
https://www.torrentkitty.app/
https://www.torrentkitty.red/
https://www.torrentkitty.lol/
https://www.torrentkitty.best/
https://www.torrentkitty.ink/
only .se is expired, the rest are working for me.
I have tested the domain you provided and it works with the indexer so I will add this to the list of alternates.

**Comment by garfield69** [comment]
v0.21.2175
