### ISSUE TITLE
[req]: AniX.Moe Indexer

### ISSUE THREAD

**Issue by zY3unxTUEqszn7w** [Jackett/Jackett#15187]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: AniXMoe
- URL: https://www.anix.moe/
- Description: AnixMoe is a public Torrent tracker for games, videos, pictures, and XXX.
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments: This site needs flaresolverr.
```

**Comment by garfield69** [comment]
This site appears to just aggregate feeds from the anidex.info and sukebei.nyaa.si sites. for which we have already indexers on Jackett.
The only difference is that on anix.moe all the seeders and leechers are zero!
Why should we bother adding this site to Jackett?

**Comment by garfield69** [comment]
I'll add it on the basis that it may provide an alternative way to access torrents from anidex and sukebei  for those users that are blocked from those two sites.

**Comment by zY3unxTUEqszn7w** [comment]
yeah. You are right. This should not be added.

**Comment by garfield69** [comment]
Ah. Found a wrinkle. 
It not only uses the cloudlfare are-you-human checkbox challenge (which flaresolverr can handle), but it also can use a Hcaptcha, which flaresolverr cannot handle.
While I can set up a cookie access, the cookie would only last for as long as cloudflare next challenge, which can be cased on how many requests are made within a time period, which may not be long at all.
As such this is not practical for use as a Jackett indexer. :-(
