### ISSUE TITLE
[req]: U3C3

### ISSUE THREAD

**Issue by zY3unxTUEqszn7w** [Jackett/Jackett#15188]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: U3C3
- URL: https://u3c3.com/
- Description: U3C3 is a public tracker for XXX containing videos, photos, and books.
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments:
```

**Comment by garfield69** [comment]
v0.21.2199

**Comment by garfield69** [comment]
https://u3c3.com/ Connection timed out Error code 522

**Comment by garfield69** [comment]
online
