### ISSUE TITLE
[req]: Retro Within

### ISSUE THREAD

**Issue by Journoud-Lucas** [Jackett/Jackett#15193]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Retro Within
- URL: https://retrowithin.com
- Description: Retro Within (RW) is a torrent site dedicated to the preservation and sharing of classic gaming and game-related media. We're focused on retro gaming from the first 1970's arcade games up to the seventh generation consoles. We don't accept new games from any of the current consoles!
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments: the website is "hidden" until you log in
```

**Comment by ilike2burnthing** [comment]
To be able to create an indexer for the tracker, we'd need at least one invite. If you're able to provide an invite(s), please send it/them to `garfieldsixtynine [at] gmail [dot] com` and/or `jacketttest [at] gmail [dot] com`

**Comment by Journoud-Lucas** [comment]
I don't have invitation unfortunatly. I can send you my account if needed

**Comment by ilike2burnthing** [comment]
Yea, that works too. Sign out of the site in your browser and stop downloading/seeding any torrents from it, then send your credentials to `jacketttest [at] gmail [dot] com`

**Comment by Journoud-Lucas** [comment]
Perfect, I've just sent it to you

**Comment by ilike2burnthing** [comment]
I've signed out.

I suggest you sign in, change the password, read rule 1 on their wiki, and search their forum for `Jackett` (granted that's from 2020).

We'd need the admins to ok this before we could proceed. If not, we can delete this issue.

**Comment by Journoud-Lucas** [comment]
I know this rule. It's also the rule for most private trackers. I think we can remove the vast majority of what's on jackett if we have to follow this rule xD.

I hadn't seen that for Jackett, and I don't think you'll be able to get their agreement.

Thanks for trying, anyway!
