### ISSUE TITLE
Jackett on a VPS does not see all the topics on the tracker

### ISSUE THREAD

**Issue by LexxDaae** [Jackett/Jackett#15204]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /root/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 20.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.4.0.144 (64bit OS) (64bit process)
Environment version: 6.0.28 (/root/Jackett/)
Starting Jackett v0.21.2199
```

### Description

Good afternoon. Sorry for my bad English, it's not my native language.

Jackett is installed on a VPS, from where, in theory, there should be normal access to trackers, but for some reason it does not see all the topics on the tracker. I attach screenshots of the tracker and the number of topics found. Interestingly, the result is not affected by the date the distribution was created on the tracker or the date it was updated.
How can this be fixed?
[disclaimer: I'm a girly girl, so if you don't mind, could you explain it the way you would explain it to a monkey?]

### Logged Error Messages

```text
no errors
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/93102750/3ebabdc3-17d6-40d9-b25f-3c052176ad41)
![image](https://github.com/Jackett/Jackett/assets/93102750/4efe9d6a-a250-4ad4-a156-77a9ba81d4f7)

**Comment by LexxDaae** [comment]
![image](https://github.com/Jackett/Jackett/assets/93102750/3097141a-78f0-4e32-8939-0f1253ad2ad2)

**Comment by ilike2burnthing** [comment]
A search for `аватар 2024` returns 10 results in Jackett for me. In this specific case, I can only get one result returned if I specify searching the `TV/UHD` category. Might that have been what you did?

As for the 'girly girl' comment, have a bit more self-respect.

**Comment by LexxDaae** [comment]
![image](https://github.com/Jackett/Jackett/assets/93102750/0a120c27-ee00-4989-b2d8-b0ec1ee31ecf)
Perhaps I'm doing something wrong? Even if I specify in the TV categories without HD, it still gives only one result.

**Comment by LexxDaae** [comment]
It runs at 77.246.108.114:9117
Can youlook please? No pass required)

**Comment by LexxDaae** [comment]
![image](https://github.com/Jackett/Jackett/assets/93102750/62a6967f-92b8-47ab-a0e3-144495f9a8f7)
In the same HD section there is another version of the series, but Jackett doesn’t see it either. Therefore, I have no idea how to treat it, to be honest))

**Comment by ilike2burnthing** [comment]
You've confused RuTracker (semi-private) and RuTracker.RU (public).

**Comment by ilike2burnthing** [comment]
Comment deleted that contained the IP address of your Jackett instance. Add an admin password if you're going to expose it to the internet.

**Comment by garfield69** [comment]
ilike2burnthing  do you think we should rename rutracker to rutracker.org just to distinguish it a bit more from rutracker.ru ?

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/e6e1d09c2a712fe6de6e098ee666004069c0aeb3

**Comment by garfield69** [comment]
v0.21.2212
