### ISSUE TITLE
[yggtorrent] (testing) Test search in YGGtorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by Jur4ssic** [Jackett/Jackett#15203]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.21.2199
Windows 64 bits
```

### Description

hi it's been 1 month now since jackett encountered an error with yggtorrent, I haven't yet seen any post with this kind of error (unless already posted, sorry in advance) so I'm publishing the error here in case someone has the answer, I specify that I did not touch anything it arrived overnight, thank you in advance for the people who will have an answer

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in YGGtorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
Click here to open an issue on GitHub for this indexer.
```

### Screenshots

![Screenshot 2024-03-28 164535](https://github.com/Jackett/Jackett/assets/51913142/29f29ca0-8b2d-4dd7-ba61-55189f98f4fd)
![Screenshot 2024-03-28 164600](https://github.com/Jackett/Jackett/assets/51913142/bf2d8915-a430-4912-bafc-0b87f008b9f2)

**Comment by ilike2burnthing** [comment]
Try reconfiguring the indexer, ensuring that the site link is exactly `https://www3.yggtorrent.qa/`

If you still have problems, follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#could-not-find-releases-from-this-url

Failing that, provide the full environment information as requested and an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Jur4ssic** [comment]
hi thank you now it works like before with "https://www3.yggtorrent.qa/`

**Comment by daniwalter001** [comment]
> hi thank you now it works like before with https://www3.yggtorrent.qa/

How did u fix it?

**Comment by ilike2burnthing** [comment]
> Try reconfiguring the indexer, ensuring that the site link is exactly https://www3.yggtorrent.qa/

**Comment by Jur4ssic** [comment]
> > hi thank you now it works like before with https://www3.yggtorrent.qa/
> 
> How did u fix it?

I used the site link and gave it to jackett in the yggtorrent settings, in "site link"

**Comment by daniwalter001** [comment]
Still working? Ygg is not working at my end. Keep saying Flaresolverr timeout error

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/1036
