### ISSUE TITLE
[req]: Need to add parameter in Hebits indexer

### ISSUE THREAD

**Issue by BuSHari** [Jackett/Jackett#15223]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Yes: https://github.com/Jackett/Jackett/issues/13808

### Describe the solution you'd like

You forgot to add `group_results=0` to the parameters/inputs, we need it to get accurate results, as for now we are getting all episodes for a series when mentioning a specific episode

**Comment by garfield69** [comment]
v0.21.2284
