### ISSUE TITLE
Bit-hd cookie

### ISSUE THREAD

**Issue by noorbertt** [Jackett/Jackett#1522]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by noorbertt** [comment]
Hi

I have problem with bit-hdtv.com when I try to add in Jackett I have to write my full cookie header. 
For some reason I can not found. 
Can I get a little help:) ?

**Comment by kaso17** [comment]
Getting your cookies is explained here: https://github.com/Jackett/Jackett/wiki/Finding-cookies
