### ISSUE TITLE
[Skipthetrailers] use of the STT API download_link generates an Error 500 Internal Server Error at the site

### ISSUE THREAD

**Issue by edge20200** [Jackett/Jackett#15234]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
Environment version: 6.0.28 (C:\ProgramData\Jackett\)
Starting Jackett v0.21.2324
```

### Description

~~Tracker is set to use unit3d v8 but is still on the last unit3d v7 version.~~
Using the DL link generates an error at the site.

### Logged Error Messages

```text
Warn 	Request to SkipTheTrailers failed with status InternalServerError.

Error

Failed download response:
<!DOCTYPE html>
<html class="no-js page__error" lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Error 500: Internal Server Error - SkipTheTrailers</title>
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Error" />
        <meta property="og:title" content="SkipTheTrailers" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="https://skipthetrailers.xyz/img/og.png" />
        <meta property="og:url" content="https://skipthetrailers.xyz" />
        <meta name="csrf-token" content="" />
        <link rel="shortcut icon" href="https://skipthetrailers.xyz/favicon.ico" type="image/x-icon" />
        <link rel="icon" href="https://skipthetrailers.xyz/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" href="/css/app.css?id=(removed)" />
    </head>
    <body>
        <main>
            <article>
                <section class="error">
                    <h1 class="error__heading">Error 500: Internal Server Error</h1>
                    <div class="error__body">Our server encountered an internal error. Sorry For The Inconvenience</div>
                    <a href="https://skipthetrailers.xyz" class="error__home-link">
                        <i class="fas fa-home"></i>
                        Go Home
                    </a>
                </section>
            </article>
        </main>
    </body>
</html>


Error 
Error downloading. indexer: skipthetrailers path: https://skipthetrailers.xyz/torrent/download/REDACTED.(removed)
System.Exception: Remote server returned InternalServerError
   at Jackett.Common.Indexers.BaseWebIndexer.Download(Uri link, RequestType method, String referer, Dictionary`2 headers) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 547
   at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 2123
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 99
```

**Comment by garfield69** [comment]
Not actually a  problem with the indexer. 
It is in fact still set up for v7.2.5, only the comments were updated to reflect v8 since the v7 docs were deleted on the unit3d github repo.
As it happens, the indexer uses whatever link is provided by the STT API in the field **download_link**, so the issue is that the STT API is retuning a download link that is not valid.
While we wait for STT to upgrade to v8, we can make the indexer edit out the invalid portion of the DL so it works again.

**Comment by garfield69** [comment]
This is a genuine problem with the STT API server, the provided download_link returned by the STT API server is causing a `Error 500: Internal Server Error`
I've raised a forum bug https://skipthetrailers.xyz/forums/topics/130

**Comment by garfield69** [comment]
No response from admins so far.
I suppose that in the interim we could switch the indexer to use a user/pswd login method, in conjunction with using the api-token for the query.
This in combo with using the download link from the details page, should allow DL to succeed.
The only downside to this is that we would have to forego the api-token validation that we currently perform during config, as the login block cannot action both a user login and an api-token check in the one login-block.
OR we wait some more.
Opinions?

**Comment by ilike2burnthing** [comment]
Open a helpdesk ticket? Maybe they'll be more likely to see/respond to that than the forum post.

Other than that, credentials plus API token sounds good (there's no open sign up at the moment, so I doubt there will be many new users adding the indexer and potentially entering a bad API token).

As the details link is `/torrents/12345` and the download link is `/torrents/download/12345`, do we just build the latter using the former, rather than having to use a download block?

**Comment by garfield69** [comment]
v0.21.2354

**Comment by garfield69** [comment]
Admin have responded:
>we have checked logs and are stumped as too what the issue is with the API, we are still looking into it and will post once we have some answers

**Comment by garfield69** [comment]
closing due to #13066

**Comment by garfield69** [comment]
v0.21.2446
