### ISSUE TITLE
[req]: RocketHD

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#15237]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: RocketHD
- URL: https://r0k3t.li/
- Description: RocketHD is a GERMAN Private Torrent Tracker for MOVIES / TV
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 48hrs
Engine: UNIT3D 8.3.3
```

**Comment by garfield69** [comment]
v0.21.2342

**Comment by garfield69** [comment]
https://r0k3t.li/ Error 503: Service Unavailable! Sorry, we are doing some maintenance. Please check back soon.

**Comment by garfield69** [comment]
v0.22.332

**Comment by AARON8888** [comment]
It seems that tracker is back. Anyhow,my login details are not valid now and I cannot recover my account :(

**Comment by garfield69** [comment]
Yes, its still a unit3d engine but upgraded now to 8.3.0
My credentials are also not recognised and its Invite only ATM
I shall not be adding the indexer yet because we do not know what the categories are, or MST / MR, etc. etc.

**Comment by garfield69** [comment]
v0.22.932

**Comment by wake134** [comment]
rocket-hd.cc has updated UNIT3D from 9.1.5 to 9.2.0 so `info_hash` needs to be dropped.

**Comment by garfield69** [comment]
Thanks for the notice.
Indexer updated.

**Comment by garfield69** [comment]
v0.24.487
