### ISSUE TITLE
[iptorrents] (testing) Test search in IPTorrents => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by TommySnyder** [Jackett/Jackett#15232]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-04-08 06:10:53	Info	Using HTTP Client: HttpWebClient2
2024-04-08 06:10:53	Info	Using FlareSolverr: http://192.168.0.11:8191/
2024-04-08 06:10:53	Info	Using proxy: Disabled
2024-04-08 06:10:53	Info	App config/log directory: C:\ProgramData\Jackett
2024-04-08 06:10:53	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2024-04-08 06:10:53	Info	Running in Docker: No
2024-04-08 06:10:53	Info	Jackett variant: CoreWindows
2024-04-08 06:10:53	Info	OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
2024-04-08 06:10:53	Info	Environment version: 6.0.28 (C:\ProgramData\Jackett\)
2024-04-08 06:10:53	Info	Starting Jackett v0.21.2313
```

### Description

Worked until a few days ago.  Using Qbittorrent  4.6.4.  Works with 3 other Indexers using same Qbittorent and Jackett. 

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in IPTorrents => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
```

**Comment by ilike2burnthing** [comment]
Working ok here.

Reconfigure the indexer and try the other site links available.

If all fail, follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#could-not-find-releases-from-this-url

If you still have problems, provide an enhanced log of the no results issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by TommySnyder** [comment]
I'm guessing this is what you want...
[log.txt](https://github.com/Jackett/Jackett/files/14910684/log.txt)

**Comment by garfield69** [comment]
Your log shows that the search results are missing the categories column href that the Jackett indexer needs to identify the category number.

With your browser go to your iptorrents **settings** and change the **torrents category column** option to **icons**
Then browser the torrents page and if necessary hit the refresh button until the torrent rows show the icon in the category column
Then try the Jackett indexer again and you should be good to go

**Comment by ilike2burnthing** [comment]
In your account settings, revert `Torrents - Category column` to `Icons` and wait about a minute.

---

@garfield69 / @mynameisbogdan the indexer is supposed to throw an error in this scenario:

https://github.com/Jackett/Jackett/blob/4d2198c0ccf6f5b07e71b4faa1dece4dfd5b6bc8/src/Jackett.Common/Indexers/IPTorrents.cs#L380-L384

**Comment by ilike2burnthing** [comment]
Get out of my brain garfield69! :P

**Comment by TommySnyder** [comment]
You guys are the greatest!!!!!  It's back working perfectly.  Thank you so much.

**Comment by garfield69** [comment]
>the indexer is supposed to throw an error in this scenario

yeah, I expect that 10b3d8448209a63d71ad02d4c494f69671b59b49 gets in front.
Don't know how to change that, its a C# dev subject ;-b
But I have amended the indexer config with 50d9da4c14d489f28e0d4f9e3ab9cc97f7ed5350 to at least display all the required settings to get good results.

**Comment by garfield69** [comment]
easy fix then, we use just `a[href^="?"]` as the selector

**Comment by garfield69** [comment]
v0.21.2329

**Comment by vdbhb59** [comment]
Also, regularly update the cookies & the user agent. Mine was expiring and have to renew every 90 days, even if I am logged in several time between those 90 days time frame.
