### ISSUE TITLE
YGG cookie question

### ISSUE THREAD

**Issue by skillix** [Jackett/Jackett#15244]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.21.2371
FlareSlover v3.3.17
```

### Description

Hello, more of a question than an error (I think).

I use the YGGcookie version of the indexer (the YGGtorrent version being out of order with the current flare solver problem) no probelem when saving, but very quickly it is no longer functional...

I have the impression that this only works for the lifespan of the cookie, is this normal operation, is there a subtlety that I missed to refresh the cookie?

### Logged Error Messages

```text
no log
```

**Comment by ilike2burnthing** [comment]
The cookie indexer only works as long as the cookie is valid. Use the normal credentials indexer.

**Comment by skillix** [comment]
normal settings indexer is no longer functional following the latest cloudflare update, if I understood correctly

**Comment by ilike2burnthing** [comment]
Works for some, not for others. Increase the timeout and keep trying.
