### ISSUE TITLE
Blutopia limited results compared to website

### ISSUE THREAD

**Issue by natoriousbigg** [Jackett/Jackett#1524]
As per the title, when searching using Jackett there are much few results compared to from the website. For example if you search "1080p remux" only 1-2 results compared to hundreds more on the website.

Jackett version:   0.7.1514.0
Mono version (if not using Windows):  not sure, running linuxserver.io docker

-------------------------------

**Comment by adamwinn** [comment]
Please read the limitation from the pull request #1489

**Comment by raspdealer** [comment]
Any one can help on this request ?

**Comment by ladude626** [comment]
Looks like by default it searches the BD50 (full bluray disk). Is there anyway you can select another movie category like bluray 1080p?

**Comment by adamwinn** [comment]
@kaso17 From what I remember, yes.  If you leave that out of your GET string, the site fails.  That's why I noted it in my merge request.

**Comment by kaso17** [comment]
Depending on how many combinations there are doing multiple requests might be an option to fix it.
See the search/paths section from https://github.com/Jackett/Jackett/wiki/Definition-format
A real world example:
https://github.com/Jackett/Jackett/blob/master/src/Jackett/Definitions/majomparade.yml#L72-L82

**Comment by KristupasSavickas** [comment]
So it looks @adamwinn talked about in his PR is not true (according to https://github.com/HDInnovations/UNIT3D/issues/574#issuecomment-462907571). Does anyone care enough to fix this? I'd do it myself, but I'm on Linux and Visual Studio is not supported there.

**Comment by adamwinn** [comment]
I used to be that way, but I'm sure it's not now. The site was under very active development back then.

**Comment by garfield69** [comment]
the blutopia indexer has gone though multiple revisions since this ticket was first posted.
including a major rewrite on Oct 2017
does the issue even still apply? Has anyone actually checked recently?
