### ISSUE TITLE
Mac: "Do you want the application “jackett” to accept incoming network connections?" prompt every time Jackett opens

### ISSUE THREAD

**Issue by godzfire** [Jackett/Jackett#15248]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Mac OS 12.7.4 (21H1123). Intel Mac mini (2018).

04-14 18:28:04 Info Starting Jackett v0.21.2358
04-14 18:28:04 Info Environment version: 6.0.29 (/Volumes/GODZ/Misc/Apple Extras/ABC/Jackett/)
04-14 18:28:04 Info OS version: Unix 12.7.4 (64bit OS) (64bit process)
04-14 18:28:04 Info Jackett variant: CoreMacOs
04-14 18:28:04 Info Running in Docker: No
04-14 18:28:04 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
04-14 18:28:04 Info App config/log directory: /Users/godzfire/.config/Jackett
04-14 18:28:04 Info Using proxy: Disabled
04-14 18:28:04 Info Using FlareSolverr: No
04-14 18:28:04 Info Using HTTP Client: HttpWebClient2
```

### Description

Whenever Jackett needs to be reopened (for example rebooting the computer), I will get the Mac OS system message: "Do you want the application “jackett” to accept incoming network connections? Clicking Deny may limit the application’s behavior. This setting can be changed in the Firewall pane of Security & Privacy preferences."

As shown in the pictures, I click allow, which should stop it from happening. Unfortunately once I quit Jackett and reopen it, the message comes back. It's already added to the Allow list in my Firewall pane.

I've used previous versions of Jackett and never had this problem. I recently updated versions so I can't comment if it's that or not.

### Logged Error Messages

```text
"Do you want the application “jackett” to accept incoming network connections? Clicking Deny may limit the application’s behavior. This setting can be changed in the Firewall pane of Security & Privacy preferences."
```

### Screenshots

<img width="260" alt="SS 2024-04-14 at 6 26 29 PM" src="https://github.com/Jackett/Jackett/assets/2067820/ff451bdf-1764-4fe6-bf45-6866fe4d3550">
<img width="565" alt="SS 2024-04-14 at 6 27 37 PM" src="https://github.com/Jackett/Jackett/assets/2067820/7fa65977-0f1e-41cc-8397-62a222865292">

**Comment by ilike2burnthing** [comment]
Close Jackett, remove the Jackett entry from your firewall settings, run Jackett, allow incoming connections, close Jackett again, start Jackett again, see if that solved your issue.

If not, in some quick googling I saw that this may be an issue for unsigned applications, and that you'd have to use `codesign`. I don't have a Mac to test this on, so I can just suggest you google the error and do some testing.

**Comment by godzfire** [comment]
> Close Jackett, remove the Jackett entry from your firewall settings, run Jackett, allow incoming connections, close Jackett again, start Jackett again, see if that solved your issue.
> 
> If not, in some quick googling I saw that this may be an issue for unsigned applications, and that you'd have to use `codesign`. I don't have a Mac to test this on, so I can just suggest you google the error and do some testing.

Unfortunately I have to reopen this. I thought I had fixed it but I was wrong. I've tried doing what you suggested but it doesn't work.

**Comment by ilike2burnthing** [comment]
What was happening to make you think it had been resolved?

What did you do regarding `codesign`?

**Comment by godzfire** [comment]
I had tried setting it not to autolaunch at started and put it to manual, but when it updates that gets overwritten and back to automatic.

Tried multiple combinations already of what you posted about adding/removing it from the firewall list.

I also did different combinations of the codesigning and listed here:
https://apple.stackexchange.com/questions/3271/how-to-get-rid-of-firewall-accept-incoming-connections-dialog

**Comment by ilike2burnthing** [comment]
So you run:

`sudo codesign --force --sign - /path/to/jackett.app` (or possibly with `--deep`)

You then open Jackett, accept incoming connections one more time, and close Jackett. Once you open Jackett again, are you still asked to accept incoming connections? If not, does that only reappear after updating Jackett?

**Comment by ilike2burnthing** [comment]
Also, do you have the setting `External access` enabled in Jackett's settings? If so, disable it, see if that prevents the alerts.

**Comment by godzfire** [comment]
> So you run:
> `sudo codesign --force --sign - /path/to/jackett.app` (or possibly with `--deep`)
> You then open Jackett, accept incoming connections one more time, and close Jackett. Once you open Jackett again, are you still asked to accept incoming connections? If not, does that only reappear after updating Jackett?
Yes that one, and tried the other command as well. And yes, it still asks.
<img width="786" alt="SS 2024-05-19 at 5 55 45 PM" src="https://github.com/Jackett/Jackett/assets/2067820/5e161666-bcb4-4948-a30a-9a3d63ce0c24">

> Also, do you have the setting `External access` enabled in Jackett's settings? If so, disable it, see if that prevents the alerts.
Tried that, same results.

So I wanted to do a test, and just download a fresh/newest copy of jackett from the site and try installing/running that. Did so. The allow prompt came up like normal, clicked allow. Shut down jackett, and ran it again. This time I did not get the prompt. Tried it a number of times, same result. 

Moved it to the location I normally keep it, deleted the old one, and launched it again there. I got the prompt again. I clicked allow, shut it down again, and ran it again. Again this time no more prompt after the initial confirmation at that location.

So this leads me to a theory, and also why I thought it was fixed last time, but came back. I *THINK* that downloading a new copy and running that, it's properly 'registered' with MacOS, and why that prompt doesn't come back. However, if I do an update to Jackett via the WebGUI, it doesn't properly 'register' with the system or have the proper codesign, and keep prompting.

**Comment by thebluepotato** [comment]
I've never run into this issue, but then again, my firewall is off by default (which I'm reconsidering). The only "nag" I regularly have is that whenever Jackett auto-updates (or at least that's I assume when it happens), the system tells me the Jackett has installed some services that will be running in the background. I can only guess that maybe macOS identifies each update as some new program instead of an update, and it might therefore be related to the issue here.

**Comment by ilike2burnthing** [comment]
Yea, at a guess, it may use a hash of the file as the identifier, rather than just the name and location, so when it updates it is no longer recognised.

**Comment by ilike2burnthing** [comment]
@godzfire would be good to know if there's a wider issue. Please reply when you have time to test. Thanks.
