### ISSUE TITLE
[dreamtracker] (testing) Test search in Dream Tracker => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by Strouroul** [Jackett/Jackett#15249]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
jackett running on windows 10

flaresolver same domain url with different port but works fine with all other indexers
```

### Description

cant search using dream.net ?
never see results back from the indexer

### Logged Error Messages

```text
cant search using dream.net ?
never see results back from the indexer
```

**Comment by ilike2burnthing** [comment]
From the indexer config:

> On 1st March 2024 this site became VIP only. You will not be able to access the Torrents page with this indexer if you do not have a subscription membership.

and:

> 1. Only the English Classic profile is supported.
> 2. Make sure to set the Torrent Listing option in your profile to Classic
> 3. And set the Language to English
> 4. Using the Modern theme will prevent results, and using Greek will prevent upload dates.

So do you have an active VIP account and have you configured it correctly?
