### ISSUE TITLE
[req]: Plusteca

### ISSUE THREAD

**Issue by raphace00** [Jackett/Jackett#15246]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Plusteca
- URL: https://plusteca.com/
- Description: Plusteca is a BRAZILIAN Private Torrent Tracker for MOVIES / TV
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): Seedtime 7 Days 
- Additional Comments: signups currently open
Engine: UNIT3D 6.3.0
```

**Comment by garfield69** [comment]
v0.21.2387

**Comment by garfield69** [comment]
https://plusteca.com/  cloudflare Origin is unreachable Error code 523

**Comment by raphace00** [comment]
The server was down for a few minutes, I restarted it and it went back to
normal. This has been happening since yesterday. Accounting problem.

Em ter., 27 de ago. de 2024 às 23:39, garfield69 ***@***.***>
escreveu:

**Comment by garfield69** [comment]
Plusteca have enabled cloudlfare challenge protection, and while that is fine for user on browsers accessing the web sites' HTML pages, its a show stopper for apps using the sites' API (which includes Jackett).

**Comment by raphace00** [comment]
I removed it. We are changing VPS and migrating the tracker. ok

Em qua., 28 de ago. de 2024 às 23:09, garfield69 ***@***.***>
escreveu:

**Comment by garfield69** [comment]
https://plusteca.com/ cloudflare Connection timed out Error code 522

**Comment by raphace00** [comment]
o tracker foi encerrado

Em sex., 25 de out. de 2024 às 14:48, garfield69 ***@***.***>
escreveu:

**Comment by garfield69** [comment]
v0.22.844
