### ISSUE TITLE
[tocashare] (updating) Error: The API key was not accepted by https://tocashare.com/.

### ISSUE THREAD

**Issue by brkr1** [Jackett/Jackett#15257]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
It's now tocashare.biz
```

### Description

It's now tocashare.biz

### Logged Error Messages

```text
An error occurred while updating this indexer
Error: The API key was not accepted by https://tocashare.com/.
Click here to open an issue on GitHub for this indexer.
```

**Comment by garfield69** [comment]
The .biz domain is a working alternate domain and I've updated the indexer to make it available again.
FWIW I checked and my existing apikey works for both domains.
So the OPs issue is either a genuine incorrect apikey (perhaps a cut/paste issue to the indexer config) or something else is interfering.

**Comment by garfield69** [comment]
v0.21.2414
