### ISSUE TITLE
Add new categories to EliteTracker

### ISSUE THREAD

**Issue by nikogaug** [Jackett/Jackett#1526]
Hello !
In [EliteTracker.cs](https://github.com/Jackett/Jackett/blob/master/src/Jackett/Indexers/EliteTracker.cs)
Is it possible to add this categories:

- Between line 74-75
`AddCategoryMapping(84, TorznabCatType.MoviesHD, "4K");`

- Between line 76-77
`AddCategoryMapping(85, TorznabCatType.MoviesHD, "x265");`

Great thanks !

**Comment by kaso17** [comment]
Done via 3b3c3b0947dc19549aaf19f236b745b41cdfe9f9, thank you
