### ISSUE TITLE
[animeworld] Season search not returning old results

### ISSUE THREAD

**Issue by virusperfect** [Jackett/Jackett#15266]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config
Running in Docker: Yes (image build: unknown)
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.15.0.105 (64bit OS) (64bit process)
Environment version: 6.0.29 (/app/)
Starting Jackett v0.21.2424
```

### Description

When doing a season search with something like:
`.../api/v2.0/indexers/animeworld-api/results/torznab/api?apikey=<JackettApiKey>&t=tvsearch&tmdbid=91600&season=1`
Only results are shown that were uploaded after 2022-02-18 (seems to be the cutoff date).

The results do show up without the season:
`.../api/v2.0/indexers/animeworld-api/results/torznab/api?apikey=<JackettApiKey>&t=tvsearch&tmdbid=91600`

This is annoying because Sonarr season searches don't work properly.

### Logged Error Messages

```text
None
```

**Comment by garfield69** [comment]
The indexer can only process what the web site returns. Also, only the first page of results (usually up to a max of 100 torrents) returned by the site is processed by the indexer.

The only member who has an account is rather busy this week so if you want a prompt reply you will need to do some research yourself ;-)
OR you could wait until that team member becomes available again ;-) 

If you perform a manual search at the website, using the tmdbid and season 1 search options, do you get all the results you expect to see on the first page?
It may also be the case that the websites search engine has this cut off date.

**Comment by ilike2burnthing** [comment]
I think the issue is caused by searching using `seasonNumber`, but I'll check again later.

**Comment by ilike2burnthing** [comment]
So as far as I can work out, anything before `2022-02-18` does not have season or episode tags (or however it works behind the scenes). Given that `seasonNumber=1` returns over 7500 results, it's clearly working otherwise, so I don't think it should be removed.

I did a quick test with Blutopia, and it doesn't have the same issue, so I'm not sure whether this is specific to AnimeWorld. You could try asking the admins, see if they're aware of the issue and if they can resolve it.

**Comment by garfield69** [comment]
Interestingly, that date falls at around the time the site upgraded from unit3d 5.3.0 to 6.0.0 , so its possible some data did not get brought across or was not converted during the new version upgrade.

**Comment by virusperfect** [comment]
The staff confirmed to me that old uploads never had fields for season/episode numbers. They might try to fix that in the future by deriving it automatically from the title.

Should I close the issue since this seems to be a problem on their side?
