### ISSUE TITLE
[req]: add aMule as a tracker

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#15265]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I retested the eDonkey protocol (I haven't used it in 20 years). And it works! It's Alive!

But today, it couldn't be used with automated app as Medusa, and others

### Describe the solution you'd like

I'm using aMule, which lets you integrate a web interface with an eDonkey client, and a user managed to create a container that acts as a tracker between Radarr and aMule. So this "personal tracker" can be used in Radarr and Sonarr

Do you think it would be possible to integrate this container as a tracker with Jackett? So that it can be used on software other than Radarr?

Here's the link to the container : EDIT : [https://github.com/vexdev/amarr](https://github.com/vexdev/amarr)

### Describe alternatives you've considered

Alternatives could be :
- use only Radarr and Sonarr.
- integrate Amarr container in Jackett
- ask Amarr dev to add Medusa (or other automated app like Radarr and sonarr) compatibility
- ask Medusa to add Amarr tracker.

Thanks in advance. And thank you for everything you've already done for Jackett and all its users.

I won't be available for testing during the day. But I will be available in the evening from 20:30 (GMT+1 / Paris).

**Comment by garfield69** [comment]
Um, where is that container link? ;-)

**Comment by pipopop** [comment]
Sorry ^^ here : [https://github.com/vexdev/amarr](https://github.com/vexdev/amarr)

**Comment by garfield69** [comment]
If I have understood the amarr readme correctly, when setting up the Sonarr/Radarr indexer  for amule you don't just set up the torznab search path to perform searches and get results, but you also have to set up a download client which processes the download request.

So While a Jackett indexer could perform a search via amarr and return results from amule (we do something similar with the [BitTorrent indexer](https://github.com/Jackett/Jackett/blob/22534dafa764ac5f7b772d661f616aa3343a07bd/src/Jackett.Common/Definitions/bitmagnet.yml) ),  when you request a download through Jackett it will fail because a Jackett DL link needs to be either a .torrent or a magnet .

I'll leave this open to get a second opinion from any of the other team members.

**Comment by pipopop** [comment]
You're right, to be used with automation tools, you must always use Amarr as a download client.

Depending on the automation tools, it is possible to assign trackers to download clients, to avoid the risk of errors.

A less interesting solution would be for Jackett to return a link to the search for the file found in amule to proceed with manual downloading via the interactive search.

This would also make it possible to search amule directly via Jackett.

But then you'd lose total automation, from search to download.

**Comment by garfield69** [comment]
When someone clicks on the DL button on the dashboard search results, or an *arr  app makes a DL request to Jackett, we do not have any way to redirect the fake magnet to the amarr client as opposed to it being picked up by the default torrent client running on the users system.
We would be talking about writing a C# indexer and supporting the equivalent of the Sonarr/Radarr preferred torrent client config associated with the indexer option.
Realistically, for such a niche scenario I don't see this getting developed any time soon. We've got tons of enhancements tickets that are languishing a slow path to stale status as it is.

**Comment by pipopop** [comment]
> When someone clicks on the DL button on the dashboard search results, or an *arr app makes a DL request to Jackett, we do not have any way to redirect the fake magnet to the amarr client as opposed to it being picked up by the default torrent client running on the users system. We would be talking about writing a C# indexer and supporting the equivalent of the Sonarr/Radarr preferred torrent client config associated with the indexer option. Realistically, for such a niche scenario I don't see this getting developed any time soon. We've got tons of enhancements tickets that are languishing a slow path to stale status as it is.

This feature is already in use in Radarr.
For each tracker, you can define a default download client.
For example, for the fake tracker, we can define the fake client qBittorrent Amarr :
When Radarr sends the search to Amarr, it receives a link.
And since Amarr is configured as the default download client for the Amarr tracker, Radarr sends the download request to Amarr, which forwards it to Emule.

If Jackett acted as a fake aMule tracker, we could have the same configuration:
1. Radarr searches for Jackett aMule.
2. Jackett aMule sends back an ed2k link.
3. Radarr sends this ed2k link to Amarr (Radarr can associate a tracker with a download client).

This means you still have to use Amarr for the download client.

**Comment by ilike2burnthing** [comment]
Any indexer in Jackett also needs to work in Jackett's own search, not just with *arrs. As it returns a torznab feed anyway, the tracker already works with the *arrs, so adding it to Jackett is neither feasible nor necessary.
