### ISSUE TITLE
New update reported as carrying Trojan

### ISSUE THREAD

**Issue by matthewr88** [Jackett/Jackett#15269]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Can't run Jackett at the moment, Windows is blocking it...
```

### Description

Windows Defender has just reported the latest update as carrying the Trojan Wacatac.B!ml

### Logged Error Messages

```text
.
```

### Screenshots

![Screenshot 2024-04-23 114245](https://github.com/Jackett/Jackett/assets/12818259/d0a77174-f657-473e-b3b4-65aad7754951)

**Comment by matthewr88** [comment]
I've rolled back to 0.21.2428 and turned off auto update.

**Comment by garfield69** [comment]
This is likely a false hit.
I have run the windows Jackett v0.21.2441 installer package through virus total and it gave it a pass, with just 1 of the 67 security vendor engines reporting it suspicious.
https://www.virustotal.com/gui/file/51853e9ac2cd85f6d942926d642a7667cef050e8259a32c684b94fe3d951073d
Also ran the jackettconsole.exe 
https://www.virustotal.com/gui/file/ce5d632bb2eefd32d8462f4b9346d158bfb357bc89f237b0f1b7d57f21522bfd
and jackettconsole.dll
https://www.virustotal.com/gui/file/bdf71d20f6bd9a494f6e96da13547823f19c1cb16e98a64047aba12dc0f0156c
and they both got a clean bill.
