### ISSUE TITLE
[req]: Question: How do I deploy to IIS / CentOS ?

### ISSUE THREAD

**Issue by brianmontesdeoca** [Jackett/Jackett#15267]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I'm trying to deploy to a IIS Site (Windows server or CentOS with netcore ) in order to access as API from outside the server, not localhost. and I don't see how to do it. I've deployed the server into a IIS but It shows a 503 error.

Thank you all

### Describe the solution you'd like

Any advice or config I should change?

**Comment by ilike2burnthing** [comment]
If it's installed and running, but you're just having problems accessing it non-locally, you'd need to enable the `External access` setting (just make sure you also set an admin password).

If if not running, or you can't access it with `External access` enabled, then provide any logs available.
