### ISSUE TITLE
[req]: Allow disabling the "Security Warning" message with an environment variable

### ISSUE THREAD

**Issue by highghlow** [Jackett/Jackett#15260]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I have Jackett running behind a reverse proxy that requires authorization (and even if it didn't, I don't port-forward it), so security is not a problem, but the security warning is. It's really annoying!

### Describe the solution you'd like

Allow specifying an environment variable (or configuration option) which would disable this warning

### Describe alternatives you've considered

Allow the warning to be closed by the user and save the closed state in a client side cookie, which would prevent the warning from appearing on this client

**Comment by ilike2burnthing** [comment]
Workaround - https://github.com/Jackett/Jackett/pull/15017#issuecomment-1922093649

Previously discussed - https://github.com/Jackett/Jackett/issues/15066#issuecomment-1953126680

**Comment by highghlow** [comment]
> Workarounds - [#15017 (comment)](https://github.com/Jackett/Jackett/pull/15017#issuecomment-1922093649) or [#15042 (comment)](https://github.com/Jackett/Jackett/issues/15042#issuecomment-1933290906)

Thanks! I can use the second one

**Comment by garfield69** [comment]
or you could wait for the next release of Jackett and use the button I just installed.

**Comment by garfield69** [comment]
v0.21.2424
