### ISSUE TITLE
[yggtorrent] (updating) Name does not resolve (www3.yggtorrent.qa:443): Name does not resolve

### ISSUE THREAD

**Issue by Darkalll** [Jackett/Jackett#15276]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.1.78:8191/
Using proxy: Disabled
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.2458-ls380)
File /etc/issue: Welcome to Alpine Linux 3.19
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 4.4.302.0 (64bit OS) (64bit process)
Environment version: 6.0.29 (/app/Jackett/)
Starting Jackett v0.21.2476
```

### Description

When trying to connect Yggtorrent to my Jackett, it show me this, i changed my DNS, i think the site is not workign but i need confirmation that it's not my configuration  that does this

### Logged Error Messages

```text
An error occurred while updating this indexer
Name does not resolve (www3.yggtorrent.qa:443): Name does not resolve
```

**Comment by theorousseaux** [comment]
Hi ! I've just seen that the site has changed its URL. It is no longer https://www3.yggtorrent.qa but https://yggtorrent.qa/ right now. However, even with this address I cannot connect yggtorrent to my jacket, I got this error :

`Test search in YGGtorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.`

 I'd be interested to know how it is with you.

**Comment by ilike2burnthing** [comment]
No, it hasn't changed, revert back to https://www3.yggtorrent.qa/

**Comment by ilike2burnthing** [comment]
Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

Can you access https://www3.yggtorrent.qa/ in browser, from the same public IP address and using the same DNS?

**Comment by theorousseaux** [comment]
It worked again for me with this new URL - https://www3.yggtorrent.cool/

**Comment by garfield69** [comment]
@Darkalll  it appears that theorousseaux is correct, ygg changed their domain about 8 hours ago and `https://www3.yggtorrent.cool/` is now the active domain.
