### ISSUE TITLE
[req]: CBR - Do not use the file name but the upload title

### ISSUE THREAD

**Issue by harpiacbr** [Jackett/Jackett#15278]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hello, I would like searches for the capybarabr (CBR) tracker to return the upload title instead of the file name

### Describe the solution you'd like

search movie: Donnie Brasco 
actual: Donnie.Brasco.1997.1080p.HMAX.WEB-DL.DD2.0.x264.pt-BR.ENG-LCD.mkv
expected: Donnie Brasco 1997 1080p HMAX WEB-DL DD2.0 x264 DUAL-LCD

**Comment by garfield69** [comment]
Simply use your Jackett dashboard to edit the CapybaraBR config and untick the `Use filename as title for single file releases` check box.

**Comment by harpiacbr** [comment]
it's possible change to false in "src/Jackett.Common/Definitions/capybarabr.yml" ?

**Comment by harpiacbr** [comment]
> Simply use your Jackett dashboard to edit the CapybaraBR config and untick the `Use filename as title for single file releases` check box.


it's possible change to false in "src/Jackett.Common/Definitions/capybarabr.yml" ?

**Comment by garfield69** [comment]
I do not understand. 
if  the checkbox has a tick then title will use the filename, and when the checkbox does not have a tick it will use the default title.
The presentation of the config is standard across all the unit3d indexers, and the use of a checkbox is a common method to indicate if an option is enabled or disabled.

**Comment by garfield69** [comment]
Are you asking that for the CBR indexer, you want to only ever provide the default title for all users of this indexer, in other words, you want us to remove the filename as title option from that indexer config?

**Comment by garfield69** [comment]
Or are you wanting the default for that filename option to be unticked?

**Comment by harpiacbr** [comment]
> Are you asking that for the CBR indexer, you want to only ever provide the default title for all users of this indexer, in other words, you want us to remove the filename as title option from that indexer config?

Sorry for not explaining it so well. In the capybarabr.yml file, the option "single_file_release_use_filename" is set to true. I would like it to be changed to false or removed. The best option for the capybarabr tracker is to use the upload title and not the file. This for all users.

**Comment by garfield69** [comment]
Oh I see.
Yes, we can remove that option from the indexer so that only the default title will be used for all users.
I will make the requested changes to the indexer. It will be published in the next Jackett release due out in about 12 hours or so.

**Comment by harpiacbr** [comment]
Thanks, garfield.

**Comment by ilike2burnthing** [comment]
I'm also confused by this.

@harpiacbr I know you're one of the CBR owners, and we always want to work closely with tracker staff when possible (we have done so many times before), but I don't understand why this is specific to CBR.

Can you help me out and explain why it is necessary that CBR members see:

> Donnie Brasco 1997 1080p HMAX WEB-DL DD2.0 x264 DUAL-LCD

rather than:

> Donnie.Brasco.1997.1080p.HMAX.WEB-DL.DD2.0.x264.pt-BR.ENG-LCD.mkv

?

If this is just a preference of the staff, I'd rather we change the default to `false` than remove the setting altogether, and allow users to decide.

Thanks!

**Comment by harpiacbr** [comment]
> I'm also confused by this.
> 
> @harpiacbr I know you're one of the CBR owners, and we always want to work closely with tracker staff when possible (we have done so many times before), but I don't understand why this is specific to CBR.
> 
> Can you help me out and explain why it is necessary that CBR members see:
> 
> > Donnie Brasco 1997 1080p HMAX WEB-DL DD2.0 x264 DUAL-LCD
> 
> rather than:
> 
> > Donnie.Brasco.1997.1080p.HMAX.WEB-DL.DD2.0.x264.pt-BR.ENG-LCD.mkv
> 
> ?
> 
> If this is just a preference of the staff, I'd rather we change the default to `false` than remove the setting altogether, and allow users to decide.
> 
> Thanks!

Hi ilike2burnthing, yes i'm one of the CBR owners. I will try to explain better, the *.pt-BR.ENG* standard is used in another Brazilian tracker called locadora. But all other Brazilian trackers tend to use "DUAL" in releases that contain more than one audio. We chose to accept this pattern from the other tracker in ours, as long as the upload title was changed to "DUAL", which standardizes all releases in CBR and which all users are more accustomed to.

As I mentioned previously, I suggested "to be changed to false or removed." I leave the best choice up to you. I appreciate the support.

I hope that clarifies, English is not my native language.

**Comment by garfield69** [comment]
OK, in that case, given the feedback from the other Jackett team members, I'll revert my update and implement the default to false for the filename option in the config. This will meet the admin request and also give users the option out if they need to adjust for the *arr app issue.
Thanks for the explanation.

**Comment by ilike2burnthing** [comment]
Thanks for the explanation, that makes sense, I just couldn't understand the reasoning before.

Your English is a hell of a lot better than my Português Brasileiro (yes I googled that) 😋

**Comment by harpiacbr** [comment]
thanks guys 😉

**Comment by garfield69** [comment]
v0.21.2485
