### ISSUE TITLE
[yggtorrent] (testing) Test search in YGGtorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by Jur4ssic** [Jackett/Jackett#15289]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.21.2542 (seedbox)
windows 22H2 my pc
i use seedbox from https://ultra.cc/
```

### Description

hi sorry if this error has already been published i'm still having trouble with github but here it is, before this message i had the timeout problem with jackett which seems to be fixed except that now i have this error the link to ygg seems correct because i copied the url address but i'm not going any further than this message so i'm coming here hoping someone can help me fix this error
thank you

Translated with DeepL.com (free version)

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in YGGtorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
```

### Screenshots

![Screenshot 2024-05-05 093708](https://github.com/Jackett/Jackett/assets/51913142/1e4194f4-d508-4ab4-9c1e-777aaa4f1c8f)
![Screenshot 2024-05-05 093738](https://github.com/Jackett/Jackett/assets/51913142/2a1f27e0-c9a3-4f9a-b948-f4113ba46314)

**Comment by ilike2burnthing** [comment]
The correct URL is https://www3.yggtorrent.cool/

**Comment by Jur4ssic** [comment]
thank you, I feel stupid, after a check in the faq of the site I saw the real the same address as you thank you for the information and thank you for your help, I thought that the address of the url would be sufficient ^^'
