### ISSUE TITLE
[cpasbien] (testing) Test search in cpasbien => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by DogancanYr** [Jackett/Jackett#15281]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.22635.0 (64bit OS)
Environment version: 6.0.29 (C:\ProgramData\Jackett\)
Starting Jackett v0.21.2485
```

### Description

It's not working and this is the new link.
https://www.cpasbien.tw/

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment]
Nope. https://www.cpasbien.tw/ is for cpasbienclone which a different engine from cpasbien
as for https://cpasbien-vf.li/ uptime shows 38 checkpoints active, but Singapore, Montreal, Paris, Lelystad and 
Lille are getting 403 forbidden (which Is what I see when I try using this indexer in jackett)
@ilike2burnthing  does your cpasbien indexer work for you, I know you have different access points than me?

**Comment by garfield69** [comment]
v0.21.2496
