### ISSUE TITLE
Lostfilm mirror request

### ISSUE THREAD

**Issue by Vinticb** [Jackett/Jackett#15295]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hello. Please, add new actual mirror (https://www.lostfilm.download) for Lostfilm tracker, the other mirrors listed there are not accessible for me (ISP block) so this extra mirror would be useful for me and others in my position.

### Describe the solution you'd like

Add new actual mirror (https://www.lostfilm.download) for Lostfilm tracker

**Comment by ilike2burnthing** [comment]
Apologies for the delay, I could not get Uptimia working no matter what I tried, went down a bit of a rabbit hole  :P 

Will update with a second commit in a bit, just with more recent Uptrends results and changing to Uptime.com for the second results.

**Comment by garfield69** [comment]
no problem. figures you got lost so I tested and added another I found on the official forum. ;-)

**Comment by garfield69** [comment]
v0.21.2554
