### ISSUE TITLE
[req]: I hope to get the magnet link in therarbg

### ISSUE THREAD

**Issue by cnstephen** [Jackett/Jackett#15299]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I hope to get the magnet link in therarbg, but I didn't find it. There is only a json page,but I can't get the json information using phpcurl because there is a cloudflare block. 

### Describe the solution you'd like

Can you add the magnet to therarbg?

### Describe alternatives you've considered

From gogole transalte, I hope you can understand.
Great project, I use it all the time.Thank you

**Comment by garfield69** [comment]
We are not responsible for what therarbg delivers, we are not the maintainers of that web site.
If you use the Jackett indexer via a torznab query then you will get magnets.
if you are fetching the json response from therarbg directly then you have to build your own magnet by using the infohash and adding your own trackers, we source ours from https://github.com/ngosang/trackerslist/blob/master/trackers_best.txt

**Comment by cnstephen** [comment]
Yes, the results obtained from this link do not have magnet links
http://127.0.0.1/api/v2.0/indexers/therarbg/results/torznab/api?apikey=****&t=search&cat=&q=
`<item>
      <title>Muse Dash v4 3 0</title>
      <guid>https://therarbg.to/post-detail/764ad1/muse-dash-v4-3-0/?format=json</guid>
      <jackettindexer id="therarbg">TheRARBG</jackettindexer>
      <type>public</type>
      <comments>https://therarbg.to/post-detail/764ad1/muse-dash-v4-3-0/</comments>
      <pubDate>Thu, 02 May 2024 07:33:21 +0800</pubDate>
      <size>3006477056</size>
      <description />
      <link>http://127.0.0.1:9117/dl/therarbg/?jackett_apikey=&amp;path=Q2ZESjhBZVBXeWdWb1NWTGp4WS0wRHgyY29XUUV3UlcxMkRPOEFLZE8yMk9HVlhwWFJvQkMxRlozSXZJR2RDRTl1VXI0OUNSRGlvWk9ZTjJ2b1lxdFlpQjNVQnY5N0tYaGo5MW9ocDR0NWZNSXI5NEkwSTg5MU9nWGN1S09iVERNNzhYdFhWWlU1OG5KNlhMV281XzZnOU9oM2E5dkJRMTBWRVVnNkxJMU5UeEJKbTdvWm5qa00xXzhpdXJKUDFERWNfR3lqTWVyUGU5OTB1bDdzV1c2TkRPUDJv&amp;file=Muse+Dash+v4+3+0</link>
      <category>4050</category>
      <category>136409</category>
      <enclosure url="http://127.0.0.1:9117/dl/therarbg/?jackett_apikey=&amp;path=Q2ZESjhBZVBXeWdWb1NWTGp4WS0wRHgyY29XUUV3UlcxMkRPOEFLZE8yMk9HVlhwWFJvQkMxRlozSXZJR2RDRTl1VXI0OUNSRGlvWk9ZTjJ2b1lxdFlpQjNVQnY5N0tYaGo5MW9ocDR0NWZNSXI5NEkwSTg5MU9nWGN1S09iVERNNzhYdFhWWlU1OG5KNlhMV281XzZnOU9oM2E5dkJRMTBWRVVnNkxJMU5UeEJKbTdvWm5qa00xXzhpdXJKUDFERWNfR3lqTWVyUGU5OTB1bDdzV1c2TkRPUDJv&amp;file=Muse+Dash+v4+3+0" length="3006477056" type="application/x-bittorrent" />
      <torznab:attr name="category" value="4050" />
      <torznab:attr name="category" value="136409" />
      <torznab:attr name="genre" value="" />
      <torznab:attr name="seeders" value="20" />
      <torznab:attr name="peers" value="53" />
      <torznab:attr name="downloadvolumefactor" value="0" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>`

**Comment by garfield69** [comment]
if you follow the link tag you will be delivered a magnet.
we cannot return a magnet directly in the results because we have to build one from the infohash in the details page, as the magnet is not available in the search results returned by therarbg.

**Comment by cnstephen** [comment]
Yes, because of cloudflare, I can't curl to get information. It would be too troublesome to get infohash from one link to another. thank you for your reply!

**Comment by cnstephen** [comment]
If only the infohash value is required, can the infohash value be displayed on this page?

**Comment by ilike2burnthing** [comment]
We'd need to perform up to an additional 100 requests every search to return all the infohashes, so no.

**Comment by garfield69** [comment]
I have made a request to therarbg admin about adding the infohash to the search query results, see https://github.com/Jackett/Jackett/issues/14685#issuecomment-2097725368 , and we shall see if that bears fruit.

**Comment by cnstephen** [comment]
> We'd need to perform up to an additional 100 requests every search to return all the infohashes, so no.
ok, thank you
