### ISSUE TITLE
Error displaying cached releases or manual search results (Synology)

### ISSUE THREAD

**Issue by Ssnarf** [Jackett/Jackett#1529]
Jackett version:  0.7.1523.0
Mono version (if not using Windows):  Stable 4.6.2.7/08fd525 (Synocommunity)

-------------------------------

Hitting the button to view cached releases or running a manual search gives a red warning message "Request to Jackett server failed" with [log output](https://pastebin.com/ETCxGGJ8) showing an unhandled exception in the JsonWriter.

I suspect an issue with the older version of Mono but would appreciate any advice.

**Comment by barbarass** [comment]
Same issue here but with the latest mono , Request to Jackett server failed.

**Comment by zjpleau** [comment]
Having the same issue: Request to Jackett server failed

**Comment by chibidev** [comment]
Thank you for reporting. This is the same issue as in #1539 and #1532. Please note, that #1543 will fix this.

**Comment by chibidev** [comment]
@Ssnarf @barbarass @zjpleau please update to the pre-release version and check whether it's working.

**Comment by zjpleau** [comment]
I'm actually running the docker container from linuxserver/docker-jackett and it doesn't look like pre-releases are supported

**Comment by chibidev** [comment]
Running the same, and pre-release working just fine. You have to enable via the user interface and check for updates after.

**Comment by petermgates** [comment]
Confirmed working as expected on 0.7.1581.0
Thanks.

**Comment by Ssnarf** [comment]
Confirmed working as expected on 0.7.1581.0.
Thanks.
