### ISSUE TITLE
[req]: TrueGear

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#15297]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: TrueGear
- URL: http://truegear.net/
- Description: TrueGear is a Private Torrent Tracker for AUTOMOTIVE E-LEARNING / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 24hrs or 1.0
- Additional Comments: signups currently open (awaiting admin validation)
Engine: xbtit dt fm v13.1
`Any account that is in-active for 90 days will be deleted.`
```

**Comment by garfield69** [comment]
Are there any torrents on this site? I see nothing, and news dated Dec 2023 stated that all torrents are dead due to seedbox crash.

**Comment by ilike2burnthing** [comment]
I assumed I wasn't seeing anything because I was still waiting approval, but it's been nearly a day. I'll give it another day and then give up on it.

**Comment by garfield69** [comment]
My credentials are no longer valid.

**Comment by HealingArcYT** [comment]
I have been able to see and download things 1-2 months ago, but right now i dont get a response from the site

**Comment by garfield69** [comment]
Does not matter to us since we did not create an indexer for this site since it appeared dead to us and our credentials were deleted within 3 days of us registering.
