### ISSUE TITLE
[1337x] qbittorrent can't find torrent I can find manually

### ISSUE THREAD

**Issue by krumpirko8888** [Jackett/Jackett#15308]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
I have no idea what you want me to do
```

### Description

I'm sorry I just don't understand half of thing you are asking me to do and I don't have much time today. I hope this picture explains it. If you need more info let me know
https://imgur.com/a/vR98c1d

### Logged Error Messages

```text
none
```

### Screenshots

![Screenshot 2024-05-13 211104](https://github.com/Jackett/Jackett/assets/168210907/f8688ad1-7f31-448c-86dd-dbda998cfb1d)

**Comment by garfield69** [comment]
just refine your search string, as `her` + `sparks` is not enough to filter out all the other false hits that 1337x is presenting
search for `her 2013 sparks` and you should find results.
