### ISSUE TITLE
[yggtorrent] (updating) Login failed: No form found on https://ygg.re/ using form selector #user-login

### ISSUE THREAD

**Issue by upperanell** [Jackett/Jackett#15314]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
[custom-init] No custom files found, skipping...
jackett  | 05-17 08:08:53 Info Starting Jackett v0.21.2606
jackett  | 05-17 08:08:53 Info Environment version: 6.0.30 (/app/Jackett/)
jackett  | 05-17 08:08:53 Info OS version: Unix 6.1.0.20 (64bit OS) (64bit process)
jackett  | 05-17 08:08:53 Info Jackett variant: CoreLinuxMuslAmdx64
jackett  | 05-17 08:08:53 Info File /etc/issue: Welcome to Alpine Linux 3.19
jackett  | 05-17 08:08:53 Info Running in Docker: Yes (image build: v0.21.2606-ls403)
jackett  | 05-17 08:08:53 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
jackett  | 05-17 08:08:53 Info App config/log directory: /config/Jackett
jackett  | 05-17 08:08:53 Info Using proxy: Disabled
```

### Description

Just site renew css code i think, ygg.re and userform change

### Logged Error Messages

```text
#user-login change variable i think
```

**Comment by enzogh** [comment]
[ #15313](https://github.com/Jackett/Jackett/pull/15313)

**Comment by garfield69** [comment]
the fix will be published in the next Jackett release dues out in about 8 hours or so.
