### ISSUE TITLE
[limetorrents] (testing) Exception (limetorrents): Name does not resolve: Name does not resolve (www.limetorrents.lol:443)

### ISSUE THREAD

**Issue by Olivier6767** [Jackett/Jackett#15329]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://flaresolver:8191
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.2628-ls404)
File /etc/issue: Welcome to Alpine Linux 3.19
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.15.0.105 (64bit OS) (64bit process)
Environment version: 6.0.30 (/app/Jackett/)
Starting Jackett v0.21.2628
```

### Description

Testing LimeTorrents results in :
Name does not resolve (www.limetorrents.lol:443)

I think the SSL port indication (:443) should be removed for the DNS query.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (limetorrents): Name does not resolve

[v0.21.2628.0] Jackett.Common.IndexerException: Exception (limetorrents): Name does not resolve
 ---> System.Net.Http.HttpRequestException: Name does not resolve (www.limetorrents.lol:443)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
```

**Comment by garfield69** [comment]
The indexer is working for me which suggest the problem is at your end.

Try accessing the docker image via your terminal and using openssl and curl from within the image 
```
docker exec -it jackett /bin/bash
```
then install openssl
```
apk add openssl
```
and now see what you get from the following:
```
openssl s_client -connect www.limetorrents.lol:443
```
and try
```
curl -vvv https://www.limetorrents.lol/
```
I expect neither to work showing that this is not a Jackett issue but something else.

Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

**Comment by Olivier6767** [comment]
I tried running your commands and they both worked.
After this I tested limetorrents again (from jackett web page) and the test was successful.

I pulled the docker container again and restarted it.

After this, the test failed with the error message again : Name does not resolve (www.limetorrents.lol:443)
I connected into the container and just added : apk add openssl
I tested limetorrents again (from Jackett web page) and it worked.

So it looks like there is dependency on openssl...
Can you please confirm?

The container I used is : linuxserver/jackett   (https://github.com/linuxserver/docker-jackett)

**Comment by garfield69** [comment]
@ilike2burnthing  your insights welcome, linux docker stuff not my cup of tea ;-b

**Comment by Olivier6767** [comment]
Did further testing, openssl is not required.

However, after I start the container, I have have to ssh into it and do a ping of limpetorrents (ping -c 2 www.limetorrents.lol).
Once I do this, the test via the web page is successfull. Without this, the test fails with the error : Name does not resolve ([www.limetorrents.lol:443](http://www.limetorrents.lol:443/)).

This is the only indexer that I have tis behavior with.

For now, I added a custom script that does the ping at the start of the container. This fixes it.
