### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): Login failed: No form found on https://www3.yggtorrent.cool/ using form selector #user-login: Parse error

### ISSUE THREAD

**Issue by edricus** [Jackett/Jackett#15320]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.21.2603 
Running in docker: yes
```

### Description

Yggtorrent (ygg.re) have become a private tracker.  
The new login in available at this address : https://www.ygg.re/auth/login

### Logged Error Messages

```text
An error occurred while updating this indexer
Login failed: No form found on https://www.ygg.re/ using form selector #user-login
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/83724412/720f94cd-81d4-4896-9323-5564738dc641)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/15314
