### ISSUE TITLE
[yggtorrent] Switch To Private Torrent Tracker

### ISSUE THREAD

**Issue by Kpl972** [Jackett/Jackett#15322]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://172.2.x.x:8191
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.2606-ls403)
File /etc/issue: Welcome to Alpine Linux 3.19
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.14.0.427 (64bit OS) (64bit process)
Environment version: 6.0.30 (/app/Jackett/)
Starting Jackett v0.21.2606
```

### Description

Hello, 
YggTorrent Switch To Private Torrent Tracker (17/05/24). 
Since then the indexer no longer works. Could you make the change?
Thank you very much.

### Logged Error Messages

```text
An error occurred while updating this indexer
Login failed: No form found on https://www.ygg.re/ using form selector #user-login
```

**Comment by garfield69** [comment]
the update will be available when Jackett is next published in about 12 hours or so.
