### ISSUE TITLE
[yggtorrent] (updating) Login failed: No form found on https://www.ygg.re/ using form selector #user-login

### ISSUE THREAD

**Issue by gfadie** [Jackett/Jackett#15328]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: YES
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.2606-ls403)
File /etc/issue: Welcome to Alpine Linux 3.19
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.10.0.22 (64bit OS) (64bit process)
Environment version: 6.0.30 (/app/Jackett/)
Starting Jackett v0.21.2606

Docker on portainer
```

### Description

The YGG torrent site has been upgraded from semi-private to private.
Integration into existing indexers will need to be modified.

Error
Login failed: No form found on https://www.ygg.re/ using form selector #user-login

It's more a Feature than a bug

### Logged Error Messages

```text
Login failed: No form found on https://www.ygg.re/ using form selector #user-login
```

**Comment by garfield69** [comment]
you are on v0.21.2606. update to v0.21.2628 to pick up the new ygg.
