### ISSUE TITLE
[req]: 2FA on HappyFappy

### ISSUE THREAD

**Issue by LeGrosFromage** [Jackett/Jackett#15333]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Please implement 2FA for HappyFappy... I believe they use the same codebase as Empornium so I'd imagine the solution is very similar to the Empornium2FA indexer.

### Describe the solution you'd like

Same as, or similar to, Empornium 2FA.

### Describe alternatives you've considered

NA

**Comment by garfield69** [comment]
created happyfappy2fa indexer, available in the next jackett release due out in about 12 hours or so.
