### ISSUE TITLE
[req]: Minor correction in README

### ISSUE THREAD

**Issue by mioux** [Jackett/Jackett#15331]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

This is not properly talking an issue. In the Linux install script, there is a whole part used to get the current release. It can be simplified 

### Describe the solution you'd like

The script for automatic installation can be reduced to ```cd /opt && f=Jackett.Binaries.LinuxAMDx64.tar.gz && sudo wget -Nc https://github.com/Jackett/Jackett/releases/latest/download/"$f" && sudo tar -xzf "$f" && sudo rm -f "$f" && cd Jackett* && sudo ./install_service_systemd.sh && systemctl status jackett.service && cd - && echo -e "\nVisit http://127.0.0.1:9117"```

**Comment by garfield69** [comment]
thanks.

**Comment by garfield69** [comment]
v0.21.2644
