### ISSUE TITLE
[mteamtp] (updating) Unknown status code: 301 (Moved)

### ISSUE THREAD

**Issue by PN62323424** [Jackett/Jackett#15337]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
none
```

### Description

none

### Logged Error Messages

```text
none
```

**Comment by ilike2burnthing** [comment]
You've created an issue, but haven't provided any details to allow the community to assist you. To prevent issue tracker clutter, this issue will now be closed. Please provide the information needed and re-open this issue.
