### ISSUE TITLE
Wolfmax4k indexer not working

### ISSUE THREAD

**Issue by trucheromayor** [Jackett/Jackett#15348]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Runing over dokcer in a synology.
Flareresolver with URL.
```

### Description

Unable to add wolfmax4k indexer

Following error

<meta http-equiv="refresh" content="0; url=/" /> <script>(function(){if (!document.body) return;var js = "window['__CF$cv$params']={r:'88abe0743b9b314e',t:'MTcxNjg3NDQ3OC43OTcwMDA='};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script>

### Logged Error Messages

```text
Proper site link is (May 2024) https://wolfmax4k.net/
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/15073
