### ISSUE TITLE
Log indicates indexers loaded, none appear in UI, searches empty

### ISSUE THREAD

**Issue by cc0800** [Jackett/Jackett#15341]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Starting Jackett v0.21.2710
Environment version: 6.0.30 (/home/minter/Downloads/Jackett/)
OS version: Unix 5.15.0.76 (64bit OS) (64bit process)
Jackett variant: CoreLinuxAmdx64
File /etc/issue: Linux Mint 21.2 Victoria \n \l
Running in Docker: No
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
App config/log directory: /home/minter/.config/Jackett
Using proxy: Disabled
Using FlareSolverr: No
Using HTTP Client: HttpWebClient2
```

### Description

While the log indicates indexers being successfully loaded:
```
Loaded 72 Native indexers.
...
Loading Cardigann indexers from: /home/minter/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /home/minter/Downloads/Jackett/Definitions
...
Loaded 613 indexers in total
```
Upon entering the web UI, the Indexer list is empty with the message "No data available in table".  Interestingly, upon inspecting the API request for indexers, it does seem to be working, returning the 613 JSON entries.  However the end result is searches for simple common terms, whether manual from the web UI or from an external application, immediately return an empty result set.

[log.txt](https://github.com/Jackett/Jackett/files/15447068/log.txt)

### Logged Error Messages

```text
Debug Attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Category' of type 'System.Int32[]' using the name 'Category' in request data ...
Debug Could not find a value in the request with name 'Category' for binding property 'Jackett.Common.Models.DTO.ApiSearch.Category' of type 'System.Int32[]'.
Debug Done attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Category' of type 'System.Int32[]'.
Debug Attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Tracker' of type 'System.String[]' using the name 'Tracker' in request data ...
Debug Could not find a value in the request with name 'Tracker' for binding property 'Jackett.Common.Models.DTO.ApiSearch.Tracker' of type 'System.String[]'.
Debug Done attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Tracker' of type 'System.String[]'.
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/56432680/875a4151-7263-4a83-b43c-bc211acba5c0)
![image](https://github.com/Jackett/Jackett/assets/56432680/ed6576fb-ef89-43e7-9572-16bbc791f55f)
![image](https://github.com/Jackett/Jackett/assets/56432680/a8f1f01b-062f-4bc6-895f-70ae6574a77e)

**Comment by ilike2burnthing** [comment]
Click the green `Add indexer` button and add your desired indexers.
