### ISSUE TITLE
[req]: METALWRKS

### ISSUE THREAD

**Issue by soredake** [Jackett/Jackett#15340]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: METALWRKS
- URL: https://metalworks.lol/
- Description: METALWRKS is a Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 1:1 ratio or 48 hours. 
- Additional Comments:
engine: unit3d 8.1.3
registration currently open
Account inactivity: `Accounts that are inactive for more than 60 days may be disabled.`
```

**Comment by garfield69** [comment]
v0.21.2710

**Comment by ilike2burnthing** [comment]
https://metalworks.lol/ - ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
@soredake  do you have any news about metalwrks, is the site GONE, just BROKEN, or moved a new DOMAIN?
We will be removing the indexer in a week if the site is not back online by then.

**Comment by soredake** [comment]
@garfield69 this tracker seems to be gone, can't find anything about it now.

**Comment by garfield69** [comment]
v0.22.228
