### ISSUE TITLE
[torrentgalaxy] (testing) Exception (torrentgalaxy): Relogin failed: Parse error

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#15358]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191/
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
Environment version: 8.0.6 (C:\ProgramData\Jackett\)
Starting Jackett v0.22.40+06ee63e0ceb2532a9a2ea6d6a70c011d2be142d3
```

### Description

Despite passing the config test by filling in the capctha, performing a TEST fails with Relogin failed: Parse error
It appears there is an additional check which the indexer does not pass.

### Logged Error Messages

```text
2024-06-03 06:45:15	Info	CardigannIndexer(torrentgalaxy): Relogin required
2024-06-03 06:45:17	Error	CardigannIndexer (torrentgalaxy): Found captcha during automatic login, aborting
2024-06-03 06:45:17	Error	Error on 20240603064517 for TorrentGalaxy.txtSystem.Exception: Relogin failed
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1744
<script src='/common/js/shades.js?sec=1717353915'></script><script>if(typeof timestamp == 'undefined') {shades2.get(function(components){ timestamp = shades2.x64hash128(components.map(function (pair) { return pair.value }).join(), 31);
xhr=new XMLHttpRequest();
xhr.open('POST', '/hub.php?a=vlad&u='+new Date().getTime());
xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
xhr.send(encodeURI('fash=' + timestamp));
});}</script><html><head><meta http-equiv='content-type' content='text/html;charset=utf-8'><title>TGx:Checkpoint</title><style>body {font-family: mono,sans-serif}img { border:none; }</style></head><body><br /><br /><center><img src='/common/images/tgxlogo.png' alt='TorrentGalaxy-logo.png'><blockquote><h2><font color='red'>GALAXY CHECKPOINT</font></h2></blockquote><script>document.write("<img style='margin:20px 0px 10px 0px;' src='/common/images/checkloader.gif' /><br />");</script><div id=(removed) value='0' max='5' id=(removed) wait while a jury of your peers judge your worthiness.</p><noscript><h1><u><font color='red'>Access denied!</font></u></h1></noscript></center><script>var timeleft = 5;var downloadTimer = setInterval(function(){  if(timeleft <= 0){clearInterval(downloadTimer);window.location.reload(1);}document.getElementById('loader').value = 5 - timeleft; document.getElementById('cd').innerHTML = timeleft;timeleft -= 1;}, 1000);</script></body></html>
[v0.22.40.0] Jackett.Common.IndexerException: Exception (torrentgalaxy): Relogin failed
 ---> System.Exception: Parse error
 ---> System.Exception: Relogin failed
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1744
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 801
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1901
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 365
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 386
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 775
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 322
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2024-06-03 06:45:17	Error	Jackett.Common.IndexerException: Exception (torrentgalaxy): Relogin failed
```

**Comment by snodemon540** [comment]
Experiencing the same symptoms and behavior except I am running Jackett inside of a linuxserver docker container.

**Comment by ben-pelletier** [comment]
same

**Comment by ben-pelletier** [comment]
same as @snodemon540, docker container with linuxserver.io img

**Comment by ilike2burnthing** [comment]
There's a new checkpoint:

![tgx](https://github.com/Jackett/Jackett/assets/59480337/8d5e89b5-f070-4a52-95a3-f4b0799bda41)

It runs the Javascript seen in the log above, with the source `/common/js/shades.js`:

```js
if (typeof timestamp == 'undefined') {
	shades2.get(function(components) {
		timestamp = shades2.x64hash128(components.map(function(pair) {
			return pair.value
		}).join(), 31);
		xhr = new XMLHttpRequest();
		xhr.open('POST', '/hub.php?a=vlad&u=' + new Date().getTime());
		xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
		xhr.send(encodeURI('fash=' + timestamp));
	});
}
```

I assume this would be doable with C#, but 🤷

It can be bypassed using cookie login (no UA needed, although it's IP-locked). The test selector would therefore need to be changed, to allow for those with accounts. The test path should probably be changed too, as there's no check on the homepage.

The site only allows one search every ~8s, if you haven't passed the captcha as well, so users would have to access https://torrentgalaxy.to/galaxyfence.php?f (or domain equivalent), complete the captcha, wait for the checkpoint to complete, and then pull the cookie (consists of both `PHPSESSID=` and `fencekey=`).

The proxyninja proxy appears to break the checkpoint for now.

@garfield69 do we change to cookie login? `fencekey` lasts an hour (but that was the case when we used captcha login too), and `PHPSESSID` last for the session (shocker, I know). We could leave this open with a `Rewrite in C#` label for a C# contributor.

**Comment by garfield69** [comment]
Are you saying that it is impractical to continue using this cardigann indexer, because even with the switch to the cookie method,  having performed all the steps on the browser to fetch a good cookie, the next time you go to use the indexer the session-id will have changed, necessitating the need to go fetch the cookie all over again?
If so then we might as well remove the indexer and flag for a C# solution, which is not going to be forthcoming any time soon.

**Comment by ilike2burnthing** [comment]
I restarted Jackett a few times with that test indexer and it worked fine. I closed and restarted the browser with the same IP, I was presented with another checkpoint when I accessed TGx, however the indexer in Jackett continued to work with the old cookie (I tested restarting Jackett again as well).

This was over the space of ~20mins, so I'm not sure how long the cookie is valid for (there may be some IP check server-side), but it seems to work ok.

**Comment by garfield69** [comment]
If we can determine how long the cookie is good for, that will help us decide what to do next.
I think If the cookie cannot last the day, then its not worth implementing.
Anything shorter that than would make the indexer unsuitable for *arr usage.

**Comment by ilike2burnthing** [comment]
Well that was short-lived, it didn't last over an hour :/

I'll sign in, message the admins, see if they can help at all.

**Comment by thegabriele97** [comment]
I get both this and 

`Test search in TorrentGalaxy => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.`

I don't know if it is related

**Comment by ilike2burnthing** [comment]
From one of the admins:

> The checkpoint is a new feature and still in beta testing. I'm not certain if it will stay or be discarded. Right now it's a work in progress.

So basically we wait and see. If they keep it, I'll message again.

**Comment by Panchajanya1999** [comment]
Same problem here on Jackett.

**Comment by ilike2burnthing** [comment]
'same here' comments are not helpful, please stop posting them. If you really feel you need to show you're also affected, thumbs up react to the initial post.

**Comment by carterja** [comment]
> 'same here' comments are not helpful, please stop posting them. If you really feel you need to show you're also affected, thumbs up react to the initial post.

any update on the issue that you can share?

**Comment by ilike2burnthing** [comment]
Updates will be posted here.

**Comment by ilike2burnthing** [comment]
There are still some issues being worked out, and they don't want to throw the combined public-tracker-using userbases of Jackett and Prowlarr (maybe DuckieTV too) at it just yet. There is a potential solution in mind, but we're waiting for TGx to give us the green light.

Keeping it marked as down just to remind me to check for updates.

**Comment by vdbhb59** [comment]
BTW, FYI: TGX is down for more than 18 hours now, 20, I presume at the time of posting this.

**Comment by vdbhb59** [comment]
It is up now, with new URL: https://torrentgalaxy.mx/ This is where every official URL is automatically redirecting to. I will raise a PR for the update to URL as well.

**Comment by ccduke83** [comment]
still cant add too jackett

**Comment by Panchajanya1999** [comment]
> still cant add too jackett

Not yet fixed yet it seems. I am trying on Prowlarr

**Comment by vdbhb59** [comment]
I agree. Cannot add setup on Jackett yet. The indexer setting does not seem to work and is freezed, and instead just launches the site in a new tab. Copy paste also does not work. :(

**Comment by vdbhb59** [comment]
> I restarted Jackett a few times with that test indexer and it worked fine. I closed and restarted the browser with the same IP, I was presented with another checkpoint when I accessed TGx, however the indexer in Jackett continued to work with the old cookie (I tested restarting Jackett again as well).
> 
> This was over the space of ~20mins, so I'm not sure how long the cookie is valid for (there may be some IP check server-side), but it seems to work ok.

10 minutes of inactivity. Max 15 minutes of inactivity.
Tried and tested as a user over the last 2 weeks. Even with the .mx domain, same inactivity period is taken. IP does not change, but session expiration or demise is set by TGX.

**Comment by vdbhb59** [comment]
@garfield69 I asked around after the latest downtime and all, so mafketel commented. This is just an update. :)
![image](https://github.com/Jackett/Jackett/assets/60728004/b33781dc-80b0-4f4c-b42f-bc8644bd399f)

**Comment by ilike2burnthing** [comment]
I'm already in contact with the admins, in particular Mafketel.

As a general comment to everyone, please do not ask TGx for updates, you're more likely to pester them than anything else.

**Comment by carterja** [comment]
> I'm already in contact with the admins, in particular Mafketel.
> 
> As a general comment to everyone, please do not ask TGx for updates, you're more likely to pester them than anything else.

thanks for the update!

**Comment by jdukleth** [comment]
> @garfield69 I asked around after the latest downtime and all, so mafketel commented. This is just an update. :) ![image](https://private-user-images.githubusercontent.com/60728004/340315017-b33781dc-80b0-4f4c-b42f-bc8644bd399f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NzUzNjEsIm5iZiI6MTcxODY3NTA2MSwicGF0aCI6Ii82MDcyODAwNC8zNDAzMTUwMTctYjMzNzgxZGMtODBiMC00ZjRjLWI0MmYtYmM4NjQ0YmQzOTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDAxNDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNTIxYzVmZWUyNGYxZTBlODg5MTJkYWM1ODVhYzE1MTNkMGM3YzJhYzRjNjY5NWE5N2ZmMGFhNzExNDMzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HV34Uw_QRcOyjOupxzkMopAJiDdMOdEl_af-AOYpkAs)

Pretty disappointing, tbh. Why not fund raise for better capacity? This would be the perfect excuse to do so.

**Comment by Z3r0Fell** [comment]
May as well add my own name to the list on this one. Ever since they implemented the GalaxyFence protocol, it looks like the Jackett interface stopped working. I tried loading FlameSolverr but it doesn't look like it's doing squat in case the Captcha comes up ... so .. proverbial creek, meet paddle!

**Comment by bombz88** [comment]
> I'm already in contact with the admins, in particular Mafketel.
> 
> As a general comment to everyone, please do not ask TGx for updates, you're more likely to pester them than anything else.

Appreciate the assistance, looking forward to a resolution.

**Comment by garfield69** [comment]
removed. When/If admins allow access again we can always add it back.

**Comment by garfield69** [comment]
v0.22.260

**Comment by Purplehaze915** [comment]
then they deserve the pestering

**Comment by bombz88** [comment]
> v0.22.260

Clarification ... TGx is removed from Jackett/Sonarr/Radarr/etc. until their team adds it back?

**Comment by garfield69** [comment]
While the TGx web site's checkpoint code is in place Jackett/Prowlarr cannot access. 
When TGx admin allow Jackett/Prowlarr to access their site again, we will add the indexer back.

**Comment by bombz88** [comment]
> While the TGx web site's checkpoint code is in place Jackett/Prowlarr cannot access. When TGx admin allow Jackett/Prowlarr to access their site again, we will add the indexer back.

Appreciate the clarification, thank makes sense. 
Thank you kindly @garfield69 for all you do!

**Comment by hannsen** [comment]
What is even the point of this "checkpoint"? All you have to do it post some random hex value to hub.php and you're in, it's like cloudflare captcha from wish.com

**Comment by garfield69** [comment]
Offline, https://torrentgalaxy.to/ displaying an image from the movie Logan, with  message: `TG(X) Forever ...`

**Comment by vdbhb59** [comment]
Yes, TGX is down and mods/owner is not reachable.
Demonoid too is down for almost a month now.

**Comment by Z3r0Fell** [comment]
> seems to be online now
> 
> how do you add it to jacket? apologies for the basic question, I'm using the docker from LinuxServer and TorrentGalaxy is not showing as an indexer.

Due to the addition of GalaxyFence, the admins removed it from the listing for adding purposes. AFAIK, the devs are in contact with TGx peeps to overcome the delay in searches, but nothing has yet to be released.

**Comment by hannsen** [comment]
There is a working qbittorrent search plugin for anyone interested

**Comment by hannsen** [comment]
I'm gonna assume no, it is for qbittorrent.

**Comment by hannsen** [comment]
> anyway share it

https://github.com/nindogo/qbtSearchScripts/issues/16#issuecomment-2273625014

**Comment by Arakys7** [comment]
Based on the linked python code, here's a **very** basic implementation in C# to get the search results:

```
var client = new HttpClient(new HttpClientHandler()
{
	CookieContainer = new CookieContainer(),
});
await client.GetAsync(url);

await Task.Delay(5000);

var seconds = DateTimeOffset.Now.ToUnixTimeSeconds();
var content = new FormUrlEncodedContent(new Dictionary<string, string>() { { "fash", Guid.NewGuid().ToString("N") } });
await client.PostAsync($"https://torrentgalaxy.to/hub.php?a=vlad&u={seconds}", content);

var response = await client.GetAsync(url);
var text = await response.Content.ReadAsStringAsync();
```

**Comment by chesh1r3k** [comment]
Looks like the checkpoint has been removed for now.

**Comment by vdbhb59** [comment]
Yup, just checked. Seems to be removed.

**Comment by nomisunrider** [comment]
Can we get it added back?

**Comment by chesh1r3k** [comment]
And.....the checkpoint is back :(

**Comment by Akirainblack** [comment]
I've not noticed the checkpoint and I've been checking it regularly to double check. I've even set up prowlarr to keep testing it and that's had no issues.

**Comment by Akirainblack** [comment]
So, you're triggering the galaxyfence by refreshing too frequently. I've not seen it at all but then again I'm only browsing normally.

**Comment by garfield69** [comment]
v0.22.1109

**Comment by nomisunrider** [comment]
I see it is re-enabled but sonarr says:

"Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings."

It tests fine in jackett.  Anyone else got it working with sonarr?

**Comment by garfield69** [comment]
@nomisunrider  TGx still has the checkpoint which it invokes whenever it wants. This is most likely what you are getting.
To confirm this, turn on Jackett enhanced logging and repeat your Sonarr test.
Then look at the Jackett logs and you may find in one of the Debug entries the HTML response from TGx that contains the text `GALAXY CHECKPOINT` in which case you are being blocked by TGx.
Basically, the TGx indexer currently works best with the Jackett dashboard search, as long as you do not select specific categories. I can use the Dashboard search to do queries with the TGx indexer ok.
Sonarr insists on using a category, and TGx appears to focus on this as a request that needs to be blocked.

**Comment by nomisunrider** [comment]
Yah, searching for things in jackett works.  I don't see a way to add it to sonarr as an indexer without a category.  Is there any known way?

**Comment by garfield69** [comment]
no.

**Comment by chesh1r3k** [comment]
Weird, just updated to 0.22.1111 and I'm not seeing it listed as a provider.

![image](https://github.com/user-attachments/assets/3ff4126c-373c-4177-9d9a-f87c47e9f828)

![image](https://github.com/user-attachments/assets/c664cbdd-f592-492d-8301-32ed41c46019)

**Comment by chesh1r3k** [comment]
Nope, and no .yml file in the Definitions folder either for it.

**Comment by garfield69** [comment]
what platform? using native or docker?

**Comment by chesh1r3k** [comment]
UnRAID and docker. 

⁣Sent from BlueMail ​

**Comment by garfield69** [comment]
So I presume by update you mean you did an image pull, or did you use the check-for-updates button on the jackett dashboard?

**Comment by chesh1r3k** [comment]
Did an image pull

**Comment by ilike2burnthing** [comment]
Working ok here. Have you volume mapped the definitions folder?

**Comment by ilike2burnthing** [comment]
As for compatibility with the Arrs, we could use TGx's `parent_cat` variable instead of `cat`, and use multiple `categories` paths. I'll test this now and add a PR shortly.

Assuming I haven't missed too much, this won't really work with Prowlarr (see YGG), so they'd need to remove category searching completely, and just rely on results being filtered.

I'll message the admin I was in touch with, to see if there's anything more that can be done (e.g. whitelisting).

**Comment by chesh1r3k** [comment]
No idea what the issue was, but just grabbed a different repo of Jackett and TGx is now there.  Only had 6 indexers set up, so not that big of a deal to switch.

**Comment by garfield69** [comment]
v0.22.1116 for *arr app users

**Comment by ilike2burnthing** [comment]
Whoops, forgot about the request delay. Fixed.
