### ISSUE TITLE
[req]: Trellas Indexer Not Working Anymore / They changed something on their side

### ISSUE THREAD

**Issue by colethegamer123** [Jackett/Jackett#15352]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Trellas
- URL: https://trellas.me/
- Description: They changed something from their side, its not working anymore even if I change URL.
- Additional Comments: Earlier I sent you an account in email Username is "jim8727827", I changed back the password to that what was in the email so you can test easier.

Thanks for your help, I really appreciate it. Our Community really need this change.
Have a nice day.
```

**Comment by garfield69** [comment]
So the OP stated that even with the new url it still does not work. I take it your tests prove otherwise?

**Comment by colethegamer123** [comment]
I think the problem was on their side. I tested later afternoon and it was working with URL replacement. Looks like they fixed that port, the HTML forms of the login site was bad earlier. Thanks for the update guys. I really appreciate it.

**Comment by ilike2burnthing** [comment]
It's just the domain change.

To use now, reconfigure the indexer to use the `.me` domain, click `Okay`, it will fail as you've seen (because it will try to use the returned redirect page from the initial `.net` request), exit the config panel, open it again (the `.me` will now be used), click `Okay` and it will log in without issue.

**Comment by garfield69** [comment]
v0.21.2855
