### ISSUE TITLE
[hdonly] films may end with extraneous ÷ in Jackett

### ISSUE THREAD

**Issue by rgossiaux** [Jackett/Jackett#15369]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.2850-ls416)
File /etc/issue: Welcome to Alpine Linux 3.19
Jackett variant: CoreLinuxMuslArm64
OS version: Unix 6.6.28.8 (64bit OS) (64bit process)
Environment version: 8.0.6 (/app/Jackett/)
Starting Jackett v0.22.43+f3b02a0bb0bad0bcf3d9db3cf600cc3fd4a38117
```

### Description

When searching for films on HD-Only in Jackett, the film titles may have an extraneous ÷ at the end. This is not Jackett's fault per se, but rather poorly formatted data from HDO.

If you go to a link like https://hd-only.org/ajax.php?searchstr=Cartouche&action=browse&group_results=0 you will see among the results returned `"fileName":"Cartouche (1962) 1080p BR FHD FR x264 VOF DTS HDMA 2.0 - LeConcepteur.mkv \u00f7"`. I have no idea why HDO includes this (it's not actually part of the name on the site), but Jackett should strip it out. It's present among a large number of titles and is breaking some integrations I have.

I believe this have a quick fix by adding another filter here to just strip out this character:

https://github.com/Jackett/Jackett/blob/37cb1eff1f5d0cd4cd10b9459eb8a650ca07d49a/src/Jackett.Common/Definitions/hdonly.yml#L268

### Logged Error Messages

```text
n/a
```

**Comment by garfield69** [comment]
v0.22.56
