### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Re4zOon** [Jackett/Jackett#15365]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.22.43-ls421)
File /etc/issue: Welcome to Alpine Linux 3.20
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.8.0.31 (64bit OS) (64bit process)
Environment version: 8.0.6 (/app/Jackett/)
Starting Jackett v0.22.43+f3b02a0bb0bad0bcf3d9db3cf600cc3fd4a38117
```

### Description

Both sonarr and radarr fails their indexer checks since last update of Jackett.
Interestingly it works for a short time after restart (at least the internal indexer checks in radarr/sonarr).
The internal checks of Jackett itself are working fine, search works fine, so can't say definitely that its a Jackett bug.
However, it started happening at the same time for both Radarr and Sonarr and they haven't been updated in days.

Reverting Jackett to older version doesn't help.
I might try reinitializing the whole thing later, maybe its an update bug?

### Logged Error Messages

```text
06-03 18:03:14 Error System.NullReferenceException: Object reference not set to an instance of an object.

[v0.22.43.0] System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Server.Controllers.ResultsController.<>c__DisplayClass18_0.<Torznab>b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454
```

Test call from Radarr (example):
```text
Unable to connect to indexer, check the log above the ValidationFailure for more details. 
HTTP request failed: [400:BadRequest] [GET] at 
http://<hostname>:<port>/jackett/api/v2.0/indexers/<indexer>/results/torznab/api?t=movie&cat=2000,2030,2040,106566,139341,143075,154333,164864,165288&extended=1&apikey=<key>&offset=0&limit=100
```

**Comment by Re4zOon** [comment]
Actually, the first test finishes successfully from radarr/sonarr after restart, but subsequent checks are failing.

**Comment by dr400** [comment]
<error code="900" description="System.NullReferenceException: Object reference not set to an instance of an object. at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func) at System.Linq.Enumerable.SelectListIterator`2.ToList() at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454"/>

It looks like first request is (slow) but succeeds, following requests are very quick but unsuccessful (see above)

**Comment by mirolm** [comment]
Duplicate to [#15364](https://github.com/Jackett/Jackett/issues/15364) ??? 

It is already fixed but we wait for a new version. As a temporary workaround disable Jackett cache.

**Comment by Re4zOon** [comment]
> Duplicate to [#15364](https://github.com/Jackett/Jackett/issues/15364) ???
> 
> It is already fixed but we wait for a new version. As a temporary workaround disable Jackett cache.

Sorry, somehow glanced over that... Yes, its a duplicate.
