### ISSUE TITLE
[tvchaosuk] (testing) Exception (tvchaosuk): Error: These credentials do not match our records.: Parse error

### ISSUE THREAD

**Issue by funkyronster** [Jackett/Jackett#15388]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-06-08 14:03:35	Info	Using HTTP Client: HttpWebClient2
2024-06-08 14:03:35	Info	Using FlareSolverr: No
2024-06-08 14:03:35	Info	Using proxy: Disabled
2024-06-08 14:03:35	Info	App config/log directory: /config/Jackett
2024-06-08 14:03:35	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-06-08 14:03:35	Info	Running in Docker: Yes (image build: )
2024-06-08 14:03:35	Info	File /etc/issue: Welcome to Alpine Linux 3.18
2024-06-08 14:03:35	Info	Jackett variant: CoreLinuxMuslAmdx64
2024-06-08 14:03:35	Info	OS version: Unix 5.15.0.102 (64bit OS) (64bit process)
2024-06-08 14:03:35	Info	Environment version: 6.0.29 (/app/Jackett/)
2024-06-08 14:03:34	Info	Starting Jackett v0.21.2536
```

### Description

[tvchaosuk] (testing) Exception (tvchaosuk): Error: These credentials do not match our records.: Parse error

### Logged Error Messages

```text
[tvchaosuk] (testing) Exception (tvchaosuk): Error: These credentials do not match our records.: Parse error
```

**Comment by ilike2burnthing** [comment]
Check that your credentials are correct and that you can log into the site from the same network, using the same public IP.

I think the login page has changed, but I'll need @garfield69 to check, as I don't have an account.

Looks like there are new hidden inputs: `_captcha`, `_username` (no value), and a randomly generated 16 character input with a 10 digit input (can use `input[type="hidden"]:last-of-type` to get).

**Comment by funkyronster** [comment]
None of that makes sense to me! If I log out and log in again it's just the same user/pass I have always had, no capcha that I can see. Or am I talking about the right thing?

**Comment by ilike2burnthing** [comment]
Log out, open browser devtools (F12), go to the `Network` tab, select `HTML` for Firefox or `Doc` for Chromium-based browsers, log into TV Chaos UK, select the `login` page in devtools, select the `Request` subtab in Firefox or `Payload` in Chromium-based browsers, you'll see the form data sent includes `_token`, `username`, `password`, and `remember` which we already use, and the new inputs that we don't yet, and may need to add.

**Comment by funkyronster** [comment]
OK I have managed that I have token, username, password and capcha

But the username and pass is mine .... and I don't want to get into trouble with TVC, so please comment before I divulge any more info.

**Comment by ilike2burnthing** [comment]
You don't need to do anything, just wait for the fix, likely in the next release ~14hrs from now. If you're using automation software like Sonarr or Radarr, disable TV Chaos UK as an indexer in them, and don't use it in Jackett until then.

**Comment by funkyronster** [comment]
OK thanks

**Comment by garfield69** [comment]
The tvchousuk indexer is working for me, and the site remains on unit3d 2.2.7 unchanged.
I do not see a captcha in the login page and the indexer config is not expecting one.

Any issue is likely at your end. 

I see that you are on an old version of jackett v0.21.2536 so perhaps update your image to 0.22.84
Also try re-entering the username/password afresh in your Jackett tvchaosuk config via the dashboard.
IF you continue to have issues, then provide an full enhanced log so we can take a look at the clues in the debug and HTML.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by funkyronster** [comment]
Thanks - I now get a positive tick test.

**Comment by funkyronster** [comment]
You guys have been very helpful, and I thank you. But I am a beginner to this - I was recommended jackett because RSS on rutorrent was consistently unreliable. But until now I was completely ignorant of the world of sonarr radarr jacket and this whole family of automating stuff. For years I have been happy manually finding stuff and using rtorrent on my seedbox and populating my Plex client. 

So forgive me for being ignorant, but could somebody please confirm that what I have discovered so far is correct.

Jackett is a front end for indexes - I only use 2 - TvC and Torrentday - but if I used more, I would configure jackett with them in the same way.

Then in Sonarr, which I have also never used before, I just configure it with a single indexer - Jackett, as per the instructions in jackett. Then I configure Sonarr with my download client - rtorrent. 

Then I just pick my progs in Sonarr - and Sonarr asks jackett, jackett asks all the indexes it is configured for, and if found passes them back to Sonarr which then shoves them into rtorrent.

So the purpose of Jackett is to save me having multiple indexes configured in Sonarr .... 

Have I got all that right?!

**Comment by garfield69** [comment]
>Jackett is a front end for indexes

Jackett is a front end for accessing torrent web sites via indexers
Indexers are what Jackett uses to contact the web sites, issue queries to them and process the HTML (or API JSON) responses
An indexer contains code that knows hot the web site pages are structured, what syntax the web sites expect for queries, etc. 

>Then in Sonarr, which I have also never used before, I just configure it with a single indexer

Not recommended. Create a Sonarr indexer for each of the Jackett indexer you want to connect to. This way you get better performance and responses.

Jackett is essentially removing the burden from Sonarr of having to know how to communicate to a torrent website specific requirements, by presenting a uniform method of making queries and getting responses. The Jackett indexers do all the translation work in between the app and the web site.
