### ISSUE TITLE
[req]: YemaPT

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#15389]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: YemaPT
- URL: https://www.yemapt.org/
- Description: YemaPT is a CHINESE Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 1.0 global (sliding scale depending on how much downloaded)
- Additional Comments: Signups open (you have to click the 'Don't have an invitation code?' link on the sign up page)
Entrance exam - 10GB upload in a month
Email must be verified before site is accessible (Gmail or QQ)
```

**Comment by ilike2burnthing** [comment]
Site has similarities to NexusPHP but is completely different. Searches are done per category. There is a request for a site-wide search - https://github.com/YemaPT-org/feedback/issues/7

They are using an API internally, but my attempts to use it failed. I've asked for documentation - https://github.com/YemaPT-org/feedback/issues/9

**Comment by ilike2burnthing** [comment]
No API usage external to the webpage. The issue suggesting a site-wide search has just been marked as an enhancement now though.

**Comment by ilike2burnthing** [comment]
Site-wide search has been implemented, but is limited to 1 search per minute.

**Comment by GaTuchoHD** [comment]
Greetings friends!

I'd like to know if I have the opportunity to implement it in Jackett. If you need anything, I'm happy to help.

**Comment by ilike2burnthing** [comment]
My account has been removed due to inactivity. PRs are welcome, but https://github.com/Jackett/Jackett/issues/15389#issuecomment-2157449778 would need to have been resolved for this to be feasible.

**Comment by GaTuchoHD** [comment]
@ilike2burnthing I checked their Wiki and there's nothing clearly related to "but is limited to 1 search per minute".

https://wiki.yemapt.org/developer/open-api

**Comment by ilike2burnthing** [comment]
If it supports searching (I don't see it explained there) then by all means submit a PR for it.

**Comment by GaTuchoHD** [comment]
Registration is open; if you need a code, click "No invitation code/Open registration?" to generate the code.:

[Register- YemaPT](https://www.yemapt.org/#/user/register) (https://www.yemapt.org/#/user/register)

**Comment by ilike2burnthing** [comment]
I couldn't find any additional information about the API upon joining, so as far as I can tell it's still the case that API search is internal use only. As for scraping the site, results are loaded using JS, so we can't do that either.
