### ISSUE TITLE
[trellas] (testing) Exception (trellas): Login failed: No form found on https://trellas.net/

### ISSUE THREAD

**Issue by vlevas** [Jackett/Jackett#15385]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Environment version: 8.0.6 (/app/Jackett/)
```

### Description

The domain has changed from https://trellas.net/ to https://trellas.me 

### Logged Error Messages

```text
Login error because of change of domain name
```

**Comment by garfield69** [comment]
you are clearly using an old version of Jackett. Update to pick up the new domain.

**Comment by vlevas** [comment]
Hello @garfield69 i update my jackett docker and i have the version Version v0.22.76  , still the trellas have wrong domain name.. the new is https://trellas.me can you check it?
