### ISSUE TITLE
[Rutracker.org] Couldn't get hash 

### ISSUE THREAD

**Issue by d3s0880** [Jackett/Jackett#15397]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.22621.0 (64bit OS)
Environment version: 8.0.6 (C:\ProgramData\Jackett\)
Starting Jackett v0.22.100
```

### Description

Hello! I am using Jackett on my TV (Lampa + Torrserve) via external access, so i can get results page of the requested movie or whatever but when i click on any result it says "Не удалось получить HASH" (translation: "Couldn't get HASH"). 

Do you happen to know how to fix it?

### Logged Error Messages

```text
-
```

**Comment by ilike2burnthing** [comment]
As far as I can tell from googling, this is a Lampa error. If you can find something Jackett's logs relating to this, provide them and reopen.
