### ISSUE TITLE
Jackett dashboard is not avaiable

### ISSUE THREAD

**Issue by LexxDaae** [Jackett/Jackett#15403]
### Have you checked our Troubleshooting page for your issue?

- [x] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Can't get anything :(
```

### Description

After resetting the server, I needed to reinstall Jackett. Judging by what the console writes, it works, but when I try to access the web interface, I receive a message that the site does not allow a connection to be established. The server itself sends correct packets when pinged, but even after restarting Jackett I am unable to access the interface. Tell me, is this generally for you or the provider/hoster?)
(English is not my native language, I apologize for any mistakes)

### Logged Error Messages

```text
:(
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/93102750/5952d038-0e67-4ead-969d-cd656d154ad2)

**Comment by garfield69** [comment]
I suspect you need to turn on Jackett's external access, as the default is local.
- Access your server console, navigate to the Jackett config folder (usually `~/.config/Jackett/`)
- find and edit with a plain text editor `ServerConfig.json`
- change `"AllowExternal": false,` to `"AllowExternal": true,` and save
- restart the Jackett service and see if that help
Let us know how you get on.

**Comment by LexxDaae** [comment]
Hm. The console and file manager do not find such a file on the entire server. Do I need to tear everything down again or somehow reinstall it on top?

**Comment by ilike2burnthing** [comment]
Service should look like this:

![service](https://github.com/Jackett/Jackett/assets/59480337/2a10e26e-4c50-4399-9277-59ae3811b739)

It seems yours is just failing or crashing, then restarting. Not really sure why, but maybe a permissions issue?

If that doesn't lead you to a solution, provide the output for the following:

```bash
journalctl -u jackett --no-pager
```

**Comment by LexxDaae** [comment]
> provide the output for the following:

This command returns a huge log, with entries marked every 20-30 seconds. Tell me, do I need to copy the entire log? Or any specific places?
Unfortunately, I am not very familiar with Unix systems, so I perform most of the actions on a copy-paste basis, focusing on the expected result, especially with the command line.

**Comment by ilike2burnthing** [comment]
Uninstall - https://github.com/Jackett/Jackett#uninstallation-on-linux

Delete `/var/lib/jackett/` and any left over files.

Install - https://github.com/Jackett/Jackett#installation-on-linux-amdx64

**Comment by ilike2burnthing** [comment]
> Something seems to be going wrong. That is, I see a requirement to change the owner of the directory, I change it, but the installation crashes.

Did you rerun the install script after changing ownership of the directory? If not, uninstall, remove files, install again.

If it then continues to fail, provide the output for `journalctl -u jackett --no-pager` again.

**Comment by LexxDaae** [comment]
It seems that the problem was that when passing the entire bunch of commands, at some point the installation crashes due to incorrect ownership. After unzipping, you need to separately change the owner of the directory and then it will work correctly, starting with the command "sudo ./install_service_systemd.sh". As an option - if it’s not difficult for you, add to the installation order the item “if you don’t understand at the programmer level what you are doing, but want to get the result, then "adduser jackett" and here you need “chown” between the commands” :) 

(because there are those who don’t know how to download and unzip a file using a separate command, and just run through a bunch of commands, and then, like me, sit and try to figure out what’s wrong)
