### ISSUE TITLE
Dashes removed on Lime

### ISSUE THREAD

**Issue by TehAppKiller** [Jackett/Jackett#15405]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: /home/xxx/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 22.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.15.0.112 (64bit OS) (64bit process)
Environment version: 8.0.6 (/opt/Jackett/)
Starting Jackett v0.22.106
```

### Description

When requesting list from LimeTorrents dashes are removed, while it's working for others trackers.
'-NTb' becomes ' NTb'
Thus cannot filter releases
Thanks <3

### Logged Error Messages

```text
N/A
```

### Screenshots

![lime1](https://github.com/Jackett/Jackett/assets/47398236/7429268d-4111-4309-af76-96dcfdeeadbe)
![lime2](https://github.com/Jackett/Jackett/assets/47398236/cf27cec9-59f4-4790-85d1-061648c64b52)

**Comment by ilike2burnthing** [comment]
All hyphens are removed from LimeTorrents results' titles in order to make them readable, as they're being taken from the URL rather than text, because the text gets cut off - https://github.com/Jackett/Jackett/issues/8708.
