### ISSUE TITLE
Update CHDBits Domain to https://chdbits.co/

### ISSUE THREAD

**Issue by xiaobaiya8** [Jackett/Jackett#15413]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
unraid docker
```

### Description

Description:
The domain for CHDBits has changed to https://chdbits.co/
Additionally, it appears that FlareSolverr is no longer required for accessing the site.

### Logged Error Messages

```text
no
```

**Comment by ilike2burnthing** [comment]
It may be that once signed in you no longer get Cloudflare challenges. If you open the site in a private/incognito window, or attempt to reconfigure the indexer, you will likely get get a new challenge.

**Comment by xiaobaiya8** [comment]
> The current domain is valid as well. Any proof of your statement?
> 
> > Additionally, it appears that FlareSolverr is no longer required for accessing the site.
> 
> Sadly false, the cloudflare challenge was triggered for both domains in my case.

I tried accessing the site using incognito mode and switching browsers, and I did not receive the challenge. I guess it might be related to language or IP?

**Comment by xiaobaiya8** [comment]
> It may be that once signed in you no longer get Cloudflare challenges. If you open the site in a private/incognito window, or attempt to reconfigure the indexer, you will likely get get a new challenge.

I tried accessing the site using incognito mode and switching browsers, and I did not receive the challenge. I guess it might be related to language or IP?

**Comment by garfield69** [comment]
v0.22.127
