### ISSUE TITLE
Add <Torrent9 clone> to semi-private tracker ???

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#15429]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP client: HttpWebClient
FlareSolverr
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits
```

### Description

This site has user and password in settings. Then, I think it must be included as semi-private.

Also when I try to add indexer, I can´t. Maybe due to is labelled as "public" tracker?

See below full log.
[full log.txt](https://github.com/user-attachments/files/15891238/full.log.txt)

Best

### Logged Error Messages

```text
Take note this log: "Warn | Indexer torrent9clone has been renamed to torrent9-tel. Please, update the URL of the feeds.  This may stop working in the future."
```

**Comment by AARON8888** [comment]
Thanks @garfield69 
Anyhow it is still labelled as "public" in the last Web UI Jackett version.
![image](https://github.com/Jackett/Jackett/assets/2883468/fe89c181-3dea-4d0c-94dc-aa791dba6b74)

**Comment by garfield69** [comment]
show me the version at the bottom of your jackett dashboard

**Comment by AARON8888** [comment]
![image](https://github.com/Jackett/Jackett/assets/2883468/241aa7d8-cf2a-4693-83d1-4a1bd7737394)

**Comment by garfield69** [comment]
looks like I forgot to add a delete torrent9clone.yml to the updater ;-)
I'll fix it for the next release.

**Comment by garfield69** [comment]
v0.22.175
