### ISSUE TITLE
New tracker - YggTorrent

### ISSUE THREAD

**Issue by Miloune** [Jackett/Jackett#1542]
Hi,

It will be great if someone can add the new French tracker YggTorrent:
http://yggtorrent.com

No invitation needed.

Thanks :)

PS: Apparently already added in pull request: https://github.com/Jackett/Jackett/pull/1536

**Comment by bertrandgressier** [comment]
We need just waiting the next release of this amazing tool, this PR has been accepted yet

**Comment by JigSawFr** [comment]
Please take a look at recent PR/ISSUES before submitting new issue.
Thank you.
