### ISSUE TITLE
[req]: Add Demonoid back as it has been brought back from the dead again.

### ISSUE THREAD

**Issue by 1ColdAssHonkey** [Jackett/Jackett#15425]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: Demonoid
- URL: https://www.demonoid.is
- Description: Semi-private general tracker.
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): None
- Additional Comments: The site still has a screwed up logging in process.
```

**Comment by garfield69** [comment]
Thanks for the heads up. I will reinstate.
closing as a duplicate of #5678

**Comment by garfield69** [comment]
v0.22.164
