### ISSUE TITLE
[req]: need instructions in readme for manually installing Windows binaries

### ISSUE THREAD

**Issue by Laidbak300** [Jackett/Jackett#15438]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

 Having same problem as https://www.reddit.com/r/qBittorrent/comments/1117pbf/windows_10_preventing_qbittorrent_install/ except those instructions don't help. Neither do these: https://pureinfotech.com/allow-blocked-file-app-microsoft-defender-antivirus/ . In both cases the instructions say to do things which, on my system, Windows doesn't give me the option of doing. In the reddit case, I don't get the option to do the second right-click; Windows automatically deletes the installer file as soon as I hit "Run Anyway", presumably to protect me from myself because obviously users never know what they're doing. In the second case, my Windows Defender "Virus & threat protection" doesn't have a "Protection History" option anywhere in it. Nor is it anywhere in any of the other screens under Windows Security. In the pureinfotech case, when I open Windows Security | Virus & threat protection, I don't have a "Protection History" option. It's just not there, so I can't proceed with those instructions either.

So I'm stymied. Also, after downloading jackett 3 times, Windows decided to stop me from being able to download it anymore. Even when I boot up as admin, it tells me I don't have permission to DL in regular downloads dir & asks if I want to DL to my Users dir, and when I say yes, it shunts me off to that dir but gives the same message. And since I'm now at that dir but Windows still won't allow me to download even though I'm at the directory which it says it will allow me to download into, that's that. No further experimentation with the standard installation file is possible.

### Describe the solution you'd like

As a result of the foregoing issues, I need to use the manual windows binaries. Yet in the readme there are no instructions for a manual installation with the binaries.  I'd be most grateful if someone could add total noob, step-by-step baby instructions for doing so to the readme.

### Describe alternatives you've considered

I've done independent internet searches for third-party instructions and even asked on the qbittorrent reddit, all to no avail. Nobody knows how to do this. I suppose another alternative would be to turn Windows security completely off--a generally unsafe thing to do, so not a good option. C'mon, folks, what would it hurt to add the sort of instructions I'm asking for?

**Comment by garfield69** [comment]
The reality is that if you cannot master your windows defender, then its going to interfere with your manual installation too.
IMO you are better off uninstalling defender and opting for any of the other 3rd party anti-malware products out there, there are plenty to choose from, which will all have better user interfaces that you may be able to master more easily.
Creating noob instructions for a manual installation that will only be used by 1 person out of 25000 windows users that have managed to just run the installer package without issues, is not a good investment on my time.
Sorry, but I'm busy enough just keeping the Jackett indexers up to date with what little free time I have available.

**Comment by Laidbak300** [comment]
"if you cannot master your windows defender, then its going to interfere with your manual installation too"
If that's the case, you're right, not worth the bother. It took another hour or so to do some more investigation and solved the problem. For anyone else with a similar issue, it turned out that the sticking point was not really Windows Defender per se but rather its "Smartscreen Filter" sidekick. This checks for "reputation" when you install a new program, and not surprisingly, Jackett has a very poor reputation with Microsoft ;) so M$ is likely to attempt to interfere with installation. To turn off Smartscreen Filter and have a successful install, follow the instructions at https://www.makeuseof.com/windows-smartscreen-filter-enable-disable/ or if that's dead by the time you read this, just do a search for similar instructions.
