### ISSUE TITLE
[mteamtp] API Endpoint will be changed

### ISSUE THREAD

**Issue by issaccv** [Jackett/Jackett#15433]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
No env needed
```

### Description

Although there are no problems at the moment, mteam has given a notice of the change of the API call endpoint, from the previous ${SiteUrl}/api to api.${domain}

Specifically, it should be changed from the current:

https://github.com/Jackett/Jackett/blob/bfe944efcbebe11eac73f7d3408dad023c7d7625/src/Jackett.Common/Indexers/MTeamTp.cs#L218-L227

to

```
var response = await RequestWithCookiesAndRetryAsync(
$"{ApiUrl}api/torrent/search",
method: RequestType.POST,
rawbody: STJson.ToJson(searchQuery),
headers: new Dictionary<string, string>
{
{ "Accept", "application/json" },
{ "Content-Type", "application/json" },
{ "x-api-key", configData.ApiKey.Value }
});
```

Where ApiUrl should be `api.m-team.io` or `api.m-team.cc`

The existing endpoint will be discontinued on July 1st

### Logged Error Messages

```text
No Log needed
```

**Comment by ilike2burnthing** [comment]
Thanks for the heads up, feel free to make a PR for this.

Is the new endpoint currently working, or do we have to wait for July 1st?

**Comment by issaccv** [comment]
According to my test, new endpoint is working.

I am not a C# expert, but from what I have observed, we only need to change SiteUrl to ApiUrl.

e.g.

from `https://kp.m-team.cc/api/torrent/search` to `https://api.m-team.cc/api/torrent/search`

**Comment by garfield69** [comment]
`https://api.m-team.cc/api/torrent/search` seems to differ from your previous example in your first post, which had `https://api.m-team.cc/torrent/search`
which is it?

**Comment by garfield69** [comment]
never mind. I see you updated the original post. thanks.

**Comment by garfield69** [comment]
v0.22.188
