### ISSUE TITLE
yggtorrent indexer configuration form is not displayed

### ISSUE THREAD

**Issue by SadE54** [Jackett/Jackett#15437]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using FlareSolverr: http://172.17.0.1:15211
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.2943-ls420)
File /etc/issue: Welcome to Alpine Linux 3.20
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.10.0.0 (64bit OS) (64bit process)
Environment version: 6.0.31 (/app/Jackett/)
Starting Jackett v0.21.2943
```

### Description

When trying to add Yggtorrent indexer, the configuration form is not displayed at all. I have the same problem on chrome and edge. I deleted the browser data, still the same. But it's working for YggCookie indexer , I can access the configuration form ... 🤔

### Logged Error Messages

```text
nothing related
```

**Comment by ilike2burnthing** [comment]
Is you FlareSolverr API URL actually correct? Normally the port is `8191`.

If so, or if the issue continues after fixing it, are you on FlareSolverr `3.3.20`, released late yesterday? If not, update.

If it continues on `3.3.20`, provide an enhanced Jackett log of the issue and the normal (info) FlareSolverr log - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

This is likely just another case of https://github.com/FlareSolverr/FlareSolverr/issues/1036, but I don't see why it would prevent the config panel showing at all, unless you're not waiting long enough.

**Comment by SadE54** [comment]
Yeah using flaresolverr 3.3.20. The port is setup by the docker host provider. I know the problem for challenge . But here I cannot even setup the indexer , because there's no form. 
[jackett.log](https://github.com/user-attachments/files/15936611/jackett.log)

**Comment by ilike2burnthing** [comment]
And the FlareSolverr log?

In future when providing logs, make sure nothing else (e.g. Sonarr/Radarr) is performing a search at the same time, it makes the logs very difficult to follow.

**Comment by SadE54** [comment]
Sorry for that fat log 😫 For flaresolverr logs , I don't have access to it on my provider 😣

**Comment by garfield69** [comment]
This record in the jackett log is interesting
```
2024-06-22 14:47:39	Info Request finished HTTP/1.1 GET http://127.0.0.1:15229/jackett/api/v2.0/indexers/yggtorrent/config?_=1719060005942 - - - 200 2813 application/json;+charset=utf-8 419960.2431ms
```
So does that mean the config panel would have taken about 7 minutes to open after the wrench icon was clicked on the Jackett dashboard?

The Jackettt http client has a http.timeout of 100 seconds, 
```
2024-06-22 14:47:39	Error Exception in GetConfigurationForSetup (yggtorrent): System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```
And the flaresolverr timeout is 62 seconds.
```
2024-06-22 14:12:44 DEBUG    ReqId 139873876793088 Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Timeout after 60.0 seconds.', 'startTimestamp': 1719065502580, 'endTimestamp': 1719065564894, 'version': '3.3.20'}
2024-06-22 14:12:44 INFO     ReqId 139873876793088 Response in 62.314 s
```

But since the Jackett log does not go back far enough to encompass the start request we cannot see what has been going on between the first 100 seconds timeout and the other 320 seconds to that finished request record.
I have not idea what is going on here.

**Comment by blancham** [comment]
I updated my FlareSolverr to the current latest version ([v3.3.20](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.20)) and it starts working again 😉

**Comment by SadE54** [comment]
> I updated my FlareSolverr to the current latest version ([v3.3.20](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.20)) and it starts working again 😉

I understand your happiness , but this problem is not related (and I got flaresolverr v3.3.20) 😉

**Comment by ilike2burnthing** [comment]
Per @garfield69's comment, restart both the FlareSolverr and Jackett containers, stop any other containers which may use them (e.g. Sonarr, Radarr, Prowlarr, etc.), wait a few minutes, enable enhanced logging for Jackett, attempt to open the config panel for YGG, and then wait at least 10 minutes to see if the config panel opens or at least an error appears.

After that, provide the enhanced Jackett log from the moment the button was clicked to when the config panel/error appeared or the 10mins elapsed.

**Comment by SadE54** [comment]
Ok , I followed the process and I observed a strange thing . After clicking to add yggtorrent , the config window appeared about 4 minutes later (click at 11:17 on my PC, configuration window at 11:22). But after validating the config , It's blocking forever with the configuration window still displayed (I joined a small video) . The flaresolverr time seems to be GMT while the jackett one is corresponding to my timezone (GMT+2) 

https://github.com/Jackett/Jackett/assets/2878768/0eb385e3-e04f-460b-827a-69e364a7aa9d

[jackett.log](https://github.com/user-attachments/files/15969733/jackett.log)
[flaresolverr.log](https://github.com/user-attachments/files/15969734/flaresolverr.log)

PS:  I don't have control on the flaresolverrlog , it was gently provided by the host IT through helpdesk ticket

**Comment by ilike2burnthing** [comment]
If FlareSolverr is v3.3.20, then unfortunately the issue is https://github.com/FlareSolverr/FlareSolverr/issues/1036. We're working on fixes, but nothing concrete as of yet.

You've set your FlareSolverr timeout in Jackett particularly high, the default is `60000`, whereas yours is currently 10x that. You can put it to something like `90000`, apply, and you should see the YGG config panel appear after ~100s when you try it now (the challenge likely won't be resolved, but that should at least confirm the source of the issue).

As an aside, your Jackett is out of date, it is the last .NET 6.0 build (v0.21.2943). We updated to .NET 8.0 three weeks ago (current version is v0.22.207). I don't know if you can control updates, but if so I suggest updating Jackett.

**Comment by SadE54** [comment]
Thanks for the answer. I will check if it's possible to switch to the 0.22+ . The automatic update is stuck on 0.21 last version. 
I guess it's related to dependencies.  I guess I'm going to end up setup a VM on my internet box and install Jackett / Flaresolverr on it 😄
