### ISSUE TITLE
Carp-Hunter --> Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#15436]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP client: HttpWebClient
FlareSolverr
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits
```

### Description

Found no results while trying to browse this tracker
[full log.txt](https://github.com/user-attachments/files/15935790/full.log.txt)

### Logged Error Messages

```text
See above full log.
```

**Comment by garfield69** [comment]
the indexer is set up for details link only

go to the web site settings (Beállítások)  and change the download (Letöltések) option to link to details (Link a részletekhez) and save(Megváltoztat)
