### ISSUE TITLE
YourBittorrent --> failed (Error BadGateway) - The tracker seems to be down.

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#15449]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP client: HttpWebClient
FlareSolverr
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits
```

### Description

I have checked this situation two days ago at least, and not included into "Down / Waiting for removal" section at least.
Maybe I´m wrong, idk, and sorry if so.

See full log: 
[full log.txt](https://github.com/user-attachments/files/16043904/full.log.txt)

### Logged Error Messages

```text
See above.
```

**Comment by garfield69** [comment]
Both domains of this indexer are working for me, however 12 of 43 of uptimes checkpoints are showing offline
We only flag down for a majority.
Sometimes the alternate domain works so try flipping.
