### ISSUE TITLE
Error downloading. indexer: wolfmax4k path: https://wolfmax4k.com/ System.OverflowException: Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by Nexuswhitak** [Jackett/Jackett#15446]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191/
Using proxy: Disabled
App config/log directory: /home/pi/jackett
Running in Docker: No
Jackett variant: CoreLinuxArm64
OS version: Unix 6.6.20.8 (64bit OS) (64bit process)
Environment version: 8.0.6 (/home/pi/jackett/Jackett/)
```

### Description

When doing a search of one tv shows in wolfmax4k, i get an error when trying to download the media.

### Logged Error Messages

```text
Error downloading. indexer: wolfmax4k path: https://wolfmax4k.com/descargar/serie-en-hd/chicago-pd/temporada-10/capitulo-06/
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Jackett.Common.Indexers.Wolfmax4K.OpenSSLDecrypt(String encrypted, String passphrase) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 465
   at Jackett.Common.Indexers.Wolfmax4K.Download(Uri link) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 181
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 56
```

**Comment by garfield69** [comment]
@highfredo Could you take a look at this please and see if there is anything can be done? Thanks.

**Comment by highfredo** [comment]
the download of https://wolfmax4k.com/descargar/serie-en-hd/chicago-pd/temporada-10/capitulo-06/ (and more torrents) worked for me

maybe the site was temporarily down?

![image](https://github.com/Jackett/Jackett/assets/5951524/b15d7c84-e424-4906-ba24-a855519896ad)

**Comment by garfield69** [comment]
I suppose it may have been, although at the time I searched for `Chicago PD S10` and was able to DL ep 5 and ep 8 ok, it was only ep 6 that was failing.
But  I can now DL `Chicago PD 0 [WEB-DL 1080p][Dual DDP5.1 + Subs][www.AtomoHD.Futbol] S10E06 [HDTV 1080p AC3 5.1] SPANISH`, so it seems resolved now. Ta.
