### ISSUE TITLE
[req]: BlurayTracker

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#15458]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: BlurayTracker
- URL: https://bluraytracker.cz/
- Description: BlurayTracker is a CZECH Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): not mentioned in FAQ
- Additional Comments: signups currently open
Engine: TSUE 2.2
No inactivity rules in FAQ
```

**Comment by garfield69** [comment]
Bah! Got `Database Error! Please try again later or contact an Administrator.` during registration. I'll try again a little later.

**Comment by garfield69** [comment]
v0.22.267

**Comment by garfield69** [comment]
is there any news in the forum about the DB Error preventing registrations?

**Comment by ilike2burnthing** [comment]
No, nothing as of yet. I'd messaged the admin about any MST/MR. I'll ask once they get back to me.

**Comment by garfield69** [comment]
no. I only use proton or hideme for a couple of the 432 indexer I support.
but I always use my local ISP address when registering.
perhaps the site is choking on the ISP dual addressing, IPv4 and IPv6?

**Comment by garfield69** [comment]
I switched from my windows to my win VM ubuntu22 image and registered ok.

**Comment by garfield69** [comment]
https://bluraytracker.cz/ > timeout
uptrends has all checkpoints failing with TCP Connection failed (timeout)

**Comment by ilike2burnthing** [comment]
back up
