### ISSUE TITLE
[req]: SportVideo

### ISSUE THREAD

**Issue by harakirix88** [Jackett/Jackett#15461]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: SportVideo
- URL: https://www.sport-video.org.ua/index.html
- Description: SportVideo is a sports-focused torrent site boasting its colossal torrent collection covering football, basketball, hockey, rugby, and other sports.
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments: No Registration needed. Daily updated
```

**Comment by garfield69** [comment]
This is not an ideal site for indexing with Jackett, as we only have the name and a poster. 
And while we could have fuzzed it up a bit by providing a default size and seeders to meet the torznab minimum specs, the lack of a true search option is a deal breaker. 
offloading search to google is not an option, as it means we have to support separate layouts, one for the search and another for the latest (index.html) page.
I'm marking this as not suitable, others may choose to implement if they choose to.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
