### ISSUE TITLE
[req]: OKFUN PT

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#15473]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: OKFUN PT
- URL: https://pt.okfun.org/
- Description: OFUN PT is a CHINESE Private Tracker for MOVES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): tbd
- Additional Comments: 
engine: NexusPHP Standard v1.5 Beta 4
Registration: open ATM
Exam: UL 50GB DL 50GB
CA Expired 19 May 2017
Cherish your user account. Inactive accounts would be deleted based on the following rules:
             1.Veteran User or above would never be deleted.
             2.Elite User or above would never be deleted if parked (at User CP)
             3.Parked accounts would be deleted if users have not logged in for more than 400 days in a row.
             4.Unparked accounts would be deleted if users have not logged in for more than 150 days in a row.
             5.Accounts with both uploaded and downloaded amount being 0 would be deleted if users have not logged in for more than 100 days in a row.
```

**Comment by garfield69** [comment]
v0.22.306
files are very old, probably should not have bothered.

**Comment by AARON8888** [comment]
@garfield69 All torrents without active torrents. Dead activity. I think this tracker is fully dead. 
I checked the last activity of all staff members: https://pt.okfun.org/staff.php
Between year 2015 and 2017.
I recomend to delete this tracker of Jackett.

**Comment by garfield69** [comment]
Forum inactive, staff missing, and torrents are all seedless. Site is dead. Deleting indexer.

**Comment by garfield69** [comment]
v0.22.320
