### ISSUE TITLE
[lostfilm] (testing) Exception (lostfilm): Operation canceled: Parse error

### ISSUE THREAD

**Issue by Vinticb** [Jackett/Jackett#15471]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
Running in Docker: Yes (image build: v0.22.301-ls458)
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.1.0.22 (64bit OS) (64bit process)
Environment version: 8.0.6 (/app/Jackett/)
Starting Jackett v0.22.301
```

### Description

[log8.txt](https://github.com/user-attachments/files/16132614/log8.txt)

Hello. I get the error "Exception (lostfilm): Operation cancelled: Parse error" after clicking on the "Test" button. Of all the possible mirrors, I only have access to https://www.lostfilm.download /, the rest are blocked by the ISP

### Logged Error Messages

```text
Exception (lostfilm): Operation cancelled: Parse error
```

**Comment by garfield69** [comment]
The Jackett lostfilm indexer using the *download domain is working for me.

Looking at the log you provided, here are the pertinent entries
```
2024-07-08 20:24:49.1293 Debug PerformQuery: 
2024-07-08 20:26:54.5360 Info Request finished HTTP/1.1 POST http://192.168.17.8:9117/api/v2.0/indexers/lostfilm/test - 499 - - 110442.7996ms
2024-07-08 20:27:25.2661 Error Error on 20240708202725 for LostFilm.tv.txtSystem.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```
Essentially, the TEST was ultimately successful, but took 110 seconds to process 42 results, which is 10 seconds longer than the standard http timeout allows, resulting in the indexer being terminated.

when I run the indexer test it completes in 23 seconds to process 45 results.

So either the lostfilm website server was running particularly slow during your test, or your network or computer was to slow to process all the data within the allotted time.

in any case this in not an issue with Jackett.

If you cannot use any of the alternate domains for this indexer, then I suggest you try again at another time of the day to see if you get a better response time, and if it does not succeed then your options are to change to a faster ISP plan, and/or upgrade your computer, or give up trying to access lostfilm via Jackett with your current setup.
