### ISSUE TITLE
[req]: dlkoo

### ISSUE THREAD

**Issue by rpeng6** [Jackett/Jackett#15479]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: dlkoo
- URL: dlkoo.me/ www.dlkoo.cc/
- Description: dlkoo is a CHINESE Public tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): N/A
- Additional Comments:
```
the *.net and *.com redirect to *.me

**Comment by rpeng6** [comment]
site is good providing high resolution movies and tv series it would be a good addition to the indexer list :)

**Comment by garfield69** [comment]
This site is not suitable for processing by the cardigann indexer, which can only process sites that have a one-title-one-torrent structure.
The details pages for titles on this site can have multiple torrents, and would require an indexer written in C#.
See https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
The brutal reality is that C# indexer are just not being created by volunteers these days, so there is little point placing it in the C# queue. Closing as not-planned.
