### ISSUE TITLE
[req]: GOOD Tracker

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#15485]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: GOOD Tracker
- URL: http://good73.net/
- Description: GOOD tracker is a RUSSIAN Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 1.0
- Additional Comments: 
Engine: TBDev v2.0
```

**Comment by garfield69** [comment]
v0.22.320

**Comment by garfield69** [comment]
http://good73.net/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/15485#issuecomment-2249391175

**Comment by garfield69** [comment]
v0.22.809

**Comment by AARON8888** [comment]
Tracker is online.
