### ISSUE TITLE
[req]: Toggle indexers on or off

### ISSUE THREAD

**Issue by 5p4r74cu5** [Jackett/Jackett#15480]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

Hey there, apologies in advance if there is already a feature request for this; I searched but might have missed it due to being uncertain about what search terms to use.

I'd like to be able to turn indexers on and off,  specifically for example, something like a toggle button near the existing test/delete/etc buttons in the list of indexers. The use case is to be able to disable some indexers without needing to delete them, which is useful in the case of indexers that have a bunch of api info that is annoying to add or set up. Some trackers are a bit picky about VPNs without individual IP addresses, so depending on what I'm doing with my VPN some indexers won't work. Other times I just to use private trackers and turn off the public ones, without need to manually readd them again.

### Describe alternatives you've considered

Do it the old fashioned way ;-)

**Comment by garfield69** [comment]
I presume you are predominantly a Jackett dashboard user?
in which case you can add a VPN tag to those suitable indexers, and use the dashboard filter to select them when you want to group search while VPN is active.
Similarly, there already exists pre-set filters for public, private or semi-private to filter the active list to those classes.

**Comment by 5p4r74cu5** [comment]
Hey @garfield69 I'm actually mainly using jackett via qBittorrent, but that does sound like a good alternative solution if this feature isn't worth implementing :-)

**Comment by garfield69** [comment]
is you are using an app to access jackett indexer, via the torznab query, then add the filters to the query to select the wanted groups you've tagged. See https://github.com/Jackett/Jackett#filter-indexers

**Comment by 5p4r74cu5** [comment]
Hello again, oh i see, damn jackett is cool. but alas, seems that perhaps qbittorrent can only handle rss, doesnt seem to be accepting torznab url i feed it. but appreciate the suggestions

**Comment by garfield69** [comment]
Well that's unfortunate, because using the dashboard filters is not going to prevent your qBt plugin from accessing any of the active indexers. Torznab is the only supported way to select indexers other than by name from an app.
So we're back to toggling indexer on/off which is a awkward and manually intensive way to manage access to indexers.
The brutal reality is that there is little C# development for optional features going on in Jackett, but I'll reopen this ticket in case the other two regular attending members have an thoughts to add.

**Comment by 5p4r74cu5** [comment]
After seeing how torznab works, I agree with that toggling on or off is an inferior alternative, I might bring this up with qtbittorrent and see if they can do something on their end. If there are any updates regarding that, ill post here ;-)

**Comment by ilike2burnthing** [comment]
There was work being done on qBit moving completely to Torznab search:
- https://github.com/qbittorrent/search-plugins/issues/121
- https://github.com/qbittorrent/search-plugins/wiki/New-Torznab-search-engine
but that started in 2019 and the last on it was in 2022 - https://github.com/qbittorrent/qBittorrent/pull/15126.

Quick solution for you:
1. download the Jackett search engine file - https://github.com/qbittorrent/search-plugins/raw/master/nova3/engines/jackett.py
2. open in Notepad or other text editor
3. on line 145 replace `indexer_id` with `"tag:YOUR_TAG_HERE"` and save
4. qBit > Search > Search plugins... > right-click Jackett > Uninstall
5. Install a new one > Local file > locate and select your edited Jackett engine file
6. edit jackett.json to add your API key
7. success!

Tags were the solution to previous requests to allowed enabling/disabling indexers, so I think this can be closed.

**Comment by 5p4r74cu5** [comment]
Hey there, thanks for the instructions, much appreciated, I'll play around with it and see what I can do.
