### ISSUE TITLE
Password set in ServerConfig.txt is not being accepted

### ISSUE THREAD

**Issue by 0belous** [Jackett/Jackett#15495]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/obelous/.config/Jackett
Running in Docker: No
Jackett variant: CoreLinuxAmdx64
OS version: Ubuntu 24.04 LTS x86_64
Environment version: 8.0.7 (/opt/Jackett/)
Starting Jackett: v0.22.320
```

### Description

Cannot access the webui using the password defined in ServerConfig.txt
I could log in a few weeks before but not anymore
After entering the password the page refreshes and nothing happens

Tried restarting jackett
Tried changing password
Tried clearing cookies
Tried incognito mode
Tried entering the password repeatedly

### Logged Error Messages

```text
None
```

**Comment by ilike2burnthing** [comment]
`AdminPassword` in ServerConfig.json is not stored in plain text. Remove the password completely, restart Jackett, try again.
