### ISSUE TITLE
[isohunt2] (testing) Exception (isohunt2): Got redirected to another domain. Try changing the indexer URL to http://isohunts.to/.: Parse error

### ISSUE THREAD

**Issue by austin-r-brown** [Jackett/Jackett#15493]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Running latest Jackett version on Windows 10 build 1803
```

### Description

All of the suggested urls for isohunt are not working (shows 403 forbidden), so when I googled what the current isohunt url is ([isohunts.to](https://isohunts.to/)) and tried that, it errors out with the aforementioned error.  Changing the url to https/http like it suggests does not seem to make any difference.

### Logged Error Messages

```text
Got redirected to another domain. Try changing the indexer URL to http://isohunts.to/.: Parse error
```

**Comment by ilike2burnthing** [comment]
That's a fake clone that appears to want you to download something, likely malware (if you didn't download and run anything, you're fine).

If *.nz and *.ch don't work for you then see - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed (TL;DR - you'll likely need to use a VPN or proxy if changing your DNS doesn't work).
