### ISSUE TITLE
funfile: warn - invalid categories

### ISSUE THREAD

**Issue by KyleSanderson** [Jackett/Jackett#15512]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
v0.22.339
```

### Description

Load was insane with a couple bad trackers. Cleaned them out (hd-space in particular just seems broken, so does speed.cd).

### Logged Error Messages

```text
Warn [funfile] Invalid Release: 'https://www.funfile.org/details.php?id=1'. No categories provided.
```
I'm not sure if they're all like that, but I have 40 lines each time that say that. Manual downloading works well, seems like it's just through Jackett throwing the warning (or effective error?).

**Comment by ilike2burnthing** [comment]
Please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

Have you changed some appearance/style/layout/theme setting for the tracker?
