### ISSUE TITLE
[REQ] new french tracker (le saloon)

### ISSUE THREAD

**Issue by bidulle95** [Jackett/Jackett#1551]
http://lesaloon.co/
french tracker 
private tacker

**Comment by fopaldir** [comment]
Bonjour, une invitation est-elle possible ? :-)

**Comment by pipopop** [comment]
Update:
New adress : https://lesaloonv2-0.net/
Here is the headers and cap section:

Header:

site: LeSaloonV2
name: ...:::Le Saloon v2.0:::...
description: "Tracker français généraliste"
language: fr-fr
type: private
encoding: UTF-8
links:
- http://lesaloonv2-0.net/
legacylinks:
- http://lesaloon.co/

**Comment by garfield69** [comment]
registration currently closed, invite needed.
If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.closed. invite needed.

**Comment by pipopop** [comment]
@garfield69 I send it know. 

Have you reveive it ?

**Comment by garfield69** [comment]
registration received and login is now pending admin approval. thanks.

**Comment by garfield69** [comment]
login accepted. ready for work.

**Comment by garfield69** [comment]
have a go with Jackett 0.10.719

**Comment by pipopop** [comment]
Thanks to you Garfield69 !

**Comment by pipopop** [comment]
Seems to work great but listed as "en" instead of "fr-fr" in the tracker list.

**Comment by garfield69** [comment]
the language is derived from what the server presents in the html.  the site  does not specify fr-fr so the default is en.
if I hard code fr-fr it may impact the way the html is processed by jackett.

**Comment by garfield69** [comment]
I've just tested hard coding fr-fr and it does not seem to affect the Jackett processing so I've committed that change.

**Comment by pipopop** [comment]
Thanks for all !
So it's possible that there are other trackers in Jackett in French with the "en" property ?
do you know if there are any?

**Comment by garfield69** [comment]
>So it's possible that there are other trackers in Jackett in French with the "en" property ?
>do you know if there are any?

a scan of the world `french` yielded 16 cardigann indexers, and all had `fr-fr` as the language. 
So while i'ts possible, I currently don't think so.

**Comment by pipopop** [comment]
Thanks again.
Have a good day and thakns again for your works.

**Comment by garfield69** [comment]
>I have other French trackers with invitation.

read https://github.com/Jackett/Jackett/issues/1309#issuecomment-461887307

**Comment by garfield69** [comment]
http://lesaloonv2-0.net/ currently pointing to namecheap
anyone know if the site is gone or just has a new domain?

**Comment by pipopop** [comment]
I think i see this sunday that he closed his site after receiving a DMCA complaint. He will soon open his site at a new address.

**Comment by pipopop** [comment]
It wa not a DMCA complaint. I confused it with another tracker. But know, everything is ok. We just have to reconfigure the tracker with name/password and captcha and it works. Great thanks Garfield !

**Comment by garfield69** [comment]
back online, same domain.

**Comment by garfield69** [comment]
lesaloon currently broken. main page after login looks kike this
![image](https://user-images.githubusercontent.com/6933240/62440278-8460cf00-b7a3-11e9-94f1-7417e66ab05a.png)

**Comment by pipopop** [comment]
It works great now.
I don't know if the problem was just when you tested, but I use it since you created it here without any problem, more than 55 automatic downloads, the last one was the 26/07.

**Comment by garfield69** [comment]
I dont understand.
http://lesaloonv2-0.net/index.php and i'm now seeing 
![image](https://user-images.githubusercontent.com/6933240/62448289-8d5d9a80-b7bb-11e9-8d60-82771af1976c.png)
Blue saloon v2 ???

**Comment by pipopop** [comment]
I don't understand. I don't have that. I have the good one :
![lesaloon](https://user-images.githubusercontent.com/32160626/62452395-5f069d80-b770-11e9-9cbb-91a284b3f78b.png)

With the same URL

**Comment by garfield69** [comment]
no worries. I'll leave it for now.
This time next week I'l do my usual test-all-my-197-indexers loop, and see if it has changed for me.
but even if it hasn't as long as other users don't raise a ticket then I am happy.

**Comment by pipopop** [comment]
Ok I understand why. I see that for your profil :

Pseudo : garfield1969
Rang du membre : Pendus

It seems that you were hanged ^^. Probably because you didn't do anything since the creation of your profile.

**Comment by garfield69** [comment]
Thanks for the info.
Yes, I am not a contributing member, I only used the account to create the indexer, not to become a valued member of the scene.

**Comment by EricG66** [comment]
FYI LeSaloon v2 domain xyz is currectly down, they temporary switch back to .net for now. They are working of restoring the .xyz domain. @garfield69

**Comment by garfield69** [comment]
Thanks. I'll set up an auto-switch to .net and if you let us know when .xyz is back online we can reset after.

**Comment by EricG66** [comment]
@garfield69 They decided to change to .lol but .net is still working at the moment. I dont think xyz will be used again.  So I propose .lol as the main and "auto-switch" to .net in case of problems?

**Comment by guilh22** [comment]
how can we get an invite?

**Comment by francispoire** [comment]
@pipopop got one for me?

**Comment by jeffrey29-debug** [comment]
> http://lesaloonv2-0.net/ currently pointing to namecheap
> anyone know if the site is gone or just has a new domain?

J aimerais tellement pour voir être invité sur se site la
