### ISSUE TITLE
[1337x] RSS doesn't support xxx catagory 6000 content

### ISSUE THREAD

**Issue by shawn8888** [Jackett/Jackett#15519]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.188-ls109)
File /etc/issue: Welcome to Alpine Linux 3.17
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 3.10.102.0 (64bit OS) (64bit process)
Environment version: 8.0.7 (/app/Jackett/)
Starting Jackett v0.22.402
```

### Description

RSS doesn't return any XXX content. 
"Manual search" can find XXX entries.
I added "cat=6000" in the RSS Feed URL, and it returns empty feed.
Please help.

### Logged Error Messages

```text
n/a
```

**Comment by shawn8888** [comment]
It's funny, I tried kickasstorrents.to and it's rss feed doesn't support XXX either.

**Comment by ilike2burnthing** [comment]
1337x does not support multi-category filtering, so when you select a category in Jackett it is just filtering the results returned.

Keywordless searches pull the pages for the latest Movies, TV, Music, and Other categories, so if you try to filter by XXX categories then nothing will be returned. However, keyword searched just pull the first 4 pages of results, not filtering by category, so if you search for something which will return XXX results, e.g. `natural beauty`, then the `XXX` filter will return results.

Similarly, KAT.to does not support category filtering, so if there are no XXX results in the first 5 pages of results, then Jackett will return no results.

**Comment by shawn8888** [comment]
Dear @ilike2burnthing 
Thank you for your response!
The issue lies not in the search functionality, but rather with the RSS feed itself. Even without applying the filter by including "cat=6000," the RSS feed fails to return any XXX content whatsoever. My feed URL is like this:
http://mydomain.com:9117/api/v2.0/indexers/1337x/results/torznab/api?apikey=myapi
While it does generate numerous entries, it does not produce any XXX content. Is this the intended behavior?

**Comment by ilike2burnthing** [comment]
1337x: 

> Keywordless searches pull the pages for the latest Movies, TV, Music, and Other categories

**Comment by shawn8888** [comment]
Dear @ilike2burnthing 
If I understand your message correctly, the reason the Jackett RSS feed fails to deliver XXX content is that Jackett must conduct a keywordless search on the homepage, and 1337x does not return category XXX but only lists Movies, TV, Music, and Other, indicating that XXX is absent from the RSS feed.

Given that 1337x does not offer native RSS support, is there a workaround to integrate XXX content into my RSS feed using Jackett?

Interestingly, if you click on the XXX link: https://www.1337x.to/popular-xxx, it displays all the latest XXX content just as it does for other categories without a keyword!

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/blob/75a542ee0d964e95a836640f7fca063509918c1d/src/Jackett.Common/Definitions/1337x.yml#L182-L188

You'd need to create yourself a custom indexer (with a different the filename, ID and name) and change say `cat/Other` to  `cat/XXX`, then save, restart Jackett, and add your new custom indexer. No, we won't be doing that or adding XXX for Jackett as whole.

**Comment by shawn8888** [comment]
I don't think I am capable to do that level of programming, but thanks for your help.

**Comment by ilike2burnthing** [comment]
There's no 'programming' involved, you're editing a text file.

**Comment by shawn8888** [comment]
> There's no 'programming' involved, you're editing a text file.

Dear @ilike2burnthing, 

That’s interesting! Editing a text file appears to be straightforward, yet I have a few additional questions:
1. I am running Jackett in a Docker container on my Synology NAS, but I cannot locate the YML files. They do not seem to be in the /config folder. I am utilizing the recommended linuxserver/jackett Docker image. To employ my own modified YML file as a new indexer, must I map the YML folder outside the container image, and how?

2. I am uncertain how Jackett updates function. The log indicates: Running in Docker: Yes (image build: v0.21.188-ls109), whereas the web UI displays: Jackett Version v0.22.404. I assume that Jackett can somehow update itself without enforcing an image update, correct?

3. Additionally, I encounter a minor issue when attempting to update the Docker image. Each time I try to download the image, I receive the error: “Failed to query registry,” whereas other Docker images are fine.

![image](https://github.com/user-attachments/assets/22766cb5-300b-4db3-b0b3-07a03bd1a0d8)

![image](https://github.com/user-attachments/assets/4075cf0d-4c1c-4797-8b79-4e804b949f8e)

**Comment by shawn8888** [comment]
Thanks for your help, @ilike2burnthing , I think I figured it out. 

First, I mapped the folder /config/cardigann/definitions to a local directory. Second, I copied 1337x.yml and renamed it to 1337xxx.yml. I then edited the file, modifying the ID, name, and changing four instances of "cat/..." to "cat/XXX."

The only drawback is that it only captures the latest 20 releases from https://www.1337x.to/cat/XXX/1/ and does not check subsequent pages such as https://www.1337x.to/cat/XXX/2/ or https://www.1337x.to/cat/XXX/3/, and so forth. If the RSS client does not refresh frequently, it may miss some releases due to this 20-item limitation.

![image](https://github.com/user-attachments/assets/2bb29196-a12d-45cb-b0b7-d07efef49117)

**Comment by ilike2burnthing** [comment]
As you already have `/config` mapped, you can just create the directory `/cardigann/definitions` in your `docker/jackett/config` folder, rather than creating another volume map.

If you want to keep your images automatically updated, I suggest adding [Watchtower](https://hub.docker.com/r/containrrr/watchtower).

If you still have issues, remove the container and image, create a new container with the same mapped folders, and you should pick up from where you left off. Beyond that, you'd need to ask for help on a Synology forum.

**Comment by shawn8888** [comment]
You are correct. I have removed the /config/cardigann/definitions mapping.
If Jackett can upgrade itself without me upgrade the image, I will not worry about the error for now.
Although the solution of editing the definition file is easy enough, why is XXX not supported for RSS Feed by default? Is it censorship a thing in this project?

**Comment by ilike2burnthing** [comment]
Yep, it's censorship, that's definitely it... 🙄
