### ISSUE TITLE
[req]: PornRips.To

### ISSUE THREAD

**Issue by papampi** [Jackett/Jackett#15514]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: PornRips.To
- URL: https://pornrips.to/
- Description: Home of PRT 1080p & 720p HEVC x265 Porn XXX Releases
```

**Comment by garfield69** [comment]
v0.22.393

**Comment by garfield69** [comment]
https://pornrips.to/ > cloudflare Origin is unreachable Error code 523

**Comment by garfield69** [comment]
online
