### ISSUE TITLE
[req]: Add TorrentGalaxy to Docker version running on Synology.

### ISSUE THREAD

**Issue by damianernst79** [Jackett/Jackett#15510]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: TorrentGalaxy
- URL: https://torrentgalaxy.to
- Description: Please add torrentgalaxy to the Jackett version running in docker
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): Public
- Additional Comments: I saw this in the syno community beta package but i uninstalled that as it complained it was out of data and when i added it, it kept saying no data was returned.
```

**Comment by garfield69** [comment]
not going to happen yet, if at all. See https://github.com/Jackett/Jackett/issues/15358#issuecomment-2222535251
