### ISSUE TITLE
[req]: best-torrents

### ISSUE THREAD

**Issue by Pe0xonN** [Jackett/Jackett#15526]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: BestTorrents
- URL: https://best-torrents.com
- Description: BestTorrents is a POLISH Semi-Private PAY2DL tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments:
```

**Comment by garfield69** [comment]
In order to view the search page or download you have to register, and registration costs $$$ which I am not willing to spend.

To build this indexer I will need an HTML dump of the search page to map the categories, search query  and results rows, and a torrent details page to map the .torrent and magnet download links

See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by Pe0xonN** [comment]
> In order to view the search page or download you have to register, and registration costs $$$ which I am not willing to spend.
> 
> To build this indexer I will need an HTML dump of the search page to map the categories, search query and results rows, and a torrent details page to map the .torrent and magnet download links
> 
> See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source


I can help you with what to do because I have an account here

**Comment by Pe0xonN** [comment]
@garfield69 What should I do to help you add to the index

**Comment by garfield69** [comment]
what I need is here https://github.com/Jackett/Jackett/issues/15526#issuecomment-2276961109
use your browser to go to the site, access the torrent search page and dump the HTML, do the same for a details page.
save the dumps as txt files, edit for privacy any userid/passkeys/etc, and drag drop them here so I can examine them.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source for method to save html dump.

**Comment by Pe0xonN** [comment]
@garfield69 Like if I send you login and password somehow on private as well as on other contact you could do it because I don't know about it

**Comment by garfield69** [comment]
If you cannot provide the html dumps, then I guess that as long as you are sure that the site does not care what IP address you may login in from, then you could email me your login credentials for the site  to `garfieldsixtynine [at] gmail [dot] com`  .
But make sure you are logged out of the site, and stay out until I give the all clear.

**Comment by Pe0xonN** [comment]
@garfield69 Did I write anything to you?

**Comment by garfield69** [comment]
Was "You are you 🎺" from you?

**Comment by Pe0xonN** [comment]
@garfield69 Yes

Are you currently active?

**Comment by garfield69** [comment]
yes, for an hour or so.

**Comment by Pe0xonN** [comment]
@garfield69 I sent you an e mail address see email

**Comment by garfield69** [comment]
v0.22.431
I recommend you change your password to restore privacy.
