### ISSUE TITLE
[hdarea] (testing) Test search in HDArea => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by iNfRaS0NiC** [Jackett/Jackett#15525]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-08-08 12:53:47	Info	Using FlareSolverr: No
2024-08-08 12:53:47	Info	Using proxy: Disabled
2024-08-08 12:53:47	Info	App config/log directory: C:\ProgramData\Jackett
2024-08-08 12:53:47	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2024-08-08 12:53:47	Info	Running in Docker: No
2024-08-08 12:53:47	Info	Jackett variant: CoreWindows
2024-08-08 12:53:47	Info	OS version: Microsoft Windows NT 10.0.22631.0 (64bit OS)
2024-08-08 12:53:47	Info	Environment version: 8.0.7 (C:\ProgramData\Jackett\)
```

### Description

I think the same issue as I had with CHDBits.
I am a Power user, can download torrents but nothing is being found. 

### Logged Error Messages

```text
CardigannIndexer (hdarea): Error while parsing row '
<tr class="nonstick_outer_bg">
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="?cat=401">
			<img class="c_movies_bluray" src="pic/cattrans.gif" alt="Movies Blu-ray" title="Movies Blu-ray" style="background-image: url(pic/category/chd/scenetorrents/en/catsprites.png);">
		</a>
	</td>
	<td class="rowfollow" width="100%" align="left">
		<table class="torrentname" width="100%">
			<tbody>
				<tr class="nonstick_inner_bg">
					<td class="embedded">
						<a title="Big George Foreman 2023 BluRay 1080p AVC DTS-HD MA5.1-MTeam" href="details.php?id=(removed)&amp;hit=1">
							<b>Big George Foreman 2023 BluRay 1080p AVC DTS-HD MA5.1-MTeam</b>
						</a>
						<img class="pro_50pctdown" src="pic/trans.gif" alt="50%" title="50%">
					</td>
					<td width="80" class="embedded" style="text-align: right;" valign="middle"></td>
					<td width="60" class="embedded" style="text-align: right;" valign="middle"></td>
					<td width="100" class="embedded" style="text-align: right;" valign="middle"></td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow nowrap">2024-08-07<br>18:40:42</td>
	<td class="rowfollow">35.71<br>GB</td>
	<td class="rowfollow">
		<span class="red">0</span>
	</td>
	<td class="rowfollow">
		<b>
			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#leechers">1</a>
		</b>
	</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=(removed)">
			<b>8</b>
		</a>
	</td>
	<td class="rowfollow">
		<i>Anonymous</i>
	</td>
</tr>':

System.Exception: Error while parsing field=download, selector=a[href^="download.php?id="], value=<null>: Selector "a[href^="download.php?id="]" didn't match 
<tr class="nonstick_outer_bg">
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="?cat=401">
			<img class="c_movies_bluray" src="pic/cattrans.gif" alt="Movies Blu-ray" title="Movies Blu-ray" style="background-image: url(pic/category/chd/scenetorrents/en/catsprites.png);">
		</a>
	</td>
	<td class="rowfollow" width="100%" align="left">
		<table class="torrentname" width="100%">
			<tbody>
				<tr class="nonstick_inner_bg">
					<td class="embedded">
						<a title="Big George Foreman 2023 BluRay 1080p AVC DTS-HD MA5.1-MTeam" href="details.php?id=(removed)&amp;hit=1">
							<b>Big George Foreman 2023 BluRay 1080p AVC DTS-HD MA5.1-MTeam</b>
						</a>
						<img class="pro_50pctdown" src="pic/trans.gif" alt="50%" title="50%">
					</td>
					<td width="80" class="embedded" style="text-align: right;" valign="middle"></td>
					<td width="60" class="embedded" style="text-align: right;" valign="middle"></td>
					<td width="100" class="embedded" style="text-align: right;" valign="middle"></td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow nowrap">2024-08-07<br>18:40:42</td>
	<td class="rowfollow">35.71<br>GB</td>
	<td class="rowfollow">
		<span class="red">0</span>
	</td>
	<td class="rowfollow">
		<b>
			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#leechers">1</a>
		</b>
	</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=(removed)">
			<b>8</b>
		</a>
	</td>
	<td class="rowfollow">
		<i>Anonymous</i>
	</td>
</tr>
 ---> System.Exception: Selector "a[href^="download.php?id="]" didn't match 
<tr class="nonstick_outer_bg">
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="?cat=401">
			<img class="c_movies_bluray" src="pic/cattrans.gif" alt="Movies Blu-ray" title="Movies Blu-ray" style="background-image: url(pic/category/chd/scenetorrents/en/catsprites.png);">
		</a>
	</td>
	<td class="rowfollow" width="100%" align="left">
		<table class="torrentname" width="100%">
			<tbody>
				<tr class="nonstick_inner_bg">
					<td class="embedded">
						<a title="Big George Foreman 2023 BluRay 1080p AVC DTS-HD MA5.1-MTeam" href="details.php?id=(removed)&amp;hit=1">
							<b>Big George Foreman 2023 BluRay 1080p AVC DTS-HD MA5.1-MTeam</b>
						</a>
						<img class="pro_50pctdown" src="pic/trans.gif" alt="50%" title="50%">
					</td>
					<td width="80" class="embedded" style="text-align: right;" valign="middle"></td>
					<td width="60" class="embedded" style="text-align: right;" valign="middle"></td>
					<td width="100" class="embedded" style="text-align: right;" valign="middle"></td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow nowrap">2024-08-07<br>18:40:42</td>
	<td class="rowfollow">35.71<br>GB</td>
	<td class="rowfollow">
		<span class="red">0</span>
	</td>
	<td class="rowfollow">
		<b>
			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#leechers">1</a>
		</b>
	</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=(removed)">
			<b>8</b>
		</a>
	</td>
	<td class="rowfollow">
		<i>Anonymous</i>
	</td>
</tr>
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.handleSelector(selectorBlock Selector, IElement Dom, Dictionary`2 variables, Boolean required) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1265
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1837
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1862
```

**Comment by garfield69** [comment]
I don't have an account on this site so i cannot check independently.

Yes, it does look like exactly the same thing.
So was this working before?
Did your user status change recently?
Can you check the details page of a torrent and confirm that the download link is `href="download.php?id=123456"` ?
Thanks.

**Comment by iNfRaS0NiC** [comment]
@garfield69 Thank you for your response, here is the href
![08 August at 20 02 18](https://github.com/user-attachments/assets/9c4d3e06-dd91-43f6-a25d-520778e13f8f)
I don't know if it was working before because I just recently switched to Jackett.

**Comment by garfield69** [comment]
OK. 
I've basically made the same mods as with chdbits.

**Comment by garfield69** [comment]
v0.22.425

**Comment by iNfRaS0NiC** [comment]
@garfield69, unfortunately, the same error after the update:

`CardigannIndexer (hdarea): Error while parsing row '
<tr class="nonstick_outer_bg">
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="?cat=415">
			<img class="c_movies_remux" src="pic/cattrans.gif" alt="Movies REMUX" title="Movies REMUX" style="background-image: url(pic/category/chd/scenetorrents/en/catsprites.png);">
		</a>
	</td>
	<td class="rowfollow" width="100%" align="left">
		<table class="torrentname" width="100%">
			<tbody>
				<tr class="nonstick_inner_bg">
					<td class="embedded">
						<a title="The Searchers 1956 1080p BluRay Remux VC-1 DD 1.0-ADE" href="details.php?id=(removed)&amp;hit=1">
							<b>The Searchers 1956 1080p BluRay Remux VC-1 DD 1.0-ADE</b>
						</a>
						<img class="pro_50pctdown" src="pic/trans.gif" alt="50%" title="50%">
					</td>
					<td width="80" class="embedded" style="text-align: right;" valign="middle"></td>
					<td width="60" class="embedded" style="text-align: right;" valign="middle"></td>
					<td width="100" class="embedded" style="text-align: right;" valign="middle"></td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow nowrap">2024-08-08<br>14:18:41</td>
	<td class="rowfollow">19.52<br>GB</td>
	<td class="rowfollow" align="center">
		<b>
			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#seeders">7</a>
		</b>
	</td>
	<td class="rowfollow">0</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=(removed)">
			<b>10</b>
		</a>
	</td>
	<td class="rowfollow">
		<i>Anonymous</i>
	</td>
</tr>':

System.Exception: Error while parsing field=download, selector=a[href^="download.php?id="], value=<null>: Selector "a[href^="download.php?id="]" didn't match 
<tr class="nonstick_outer_bg">
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="?cat=415">
			<img class="c_movies_remux" src="pic/cattrans.gif" alt="Movies REMUX" title="Movies REMUX" style="background-image: url(pic/category/chd/scenetorrents/en/catsprites.png);">
		</a>
	</td>
	<td class="rowfollow" width="100%" align="left">
		<table class="torrentname" width="100%">
			<tbody>
				<tr class="nonstick_inner_bg">
					<td class="embedded">
						<a title="The Searchers 1956 1080p BluRay Remux VC-1 DD 1.0-ADE" href="details.php?id=(removed)&amp;hit=1">
							<b>The Searchers 1956 1080p BluRay Remux VC-1 DD 1.0-ADE</b>
						</a>
						<img class="pro_50pctdown" src="pic/trans.gif" alt="50%" title="50%">
					</td>
					<td width="80" class="embedded" style="text-align: right;" valign="middle"></td>
					<td width="60" class="embedded" style="text-align: right;" valign="middle"></td>
					<td width="100" class="embedded" style="text-align: right;" valign="middle"></td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow nowrap">2024-08-08<br>14:18:41</td>
	<td class="rowfollow">19.52<br>GB</td>
	<td class="rowfollow" align="center">
		<b>
			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#seeders">7</a>
		</b>
	</td>
	<td class="rowfollow">0</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=(removed)">
			<b>10</b>
		</a>
	</td>
	<td class="rowfollow">
		<i>Anonymous</i>
	</td>
</tr>
 ---> System.Exception: Selector "a[href^="download.php?id="]" didn't match 
<tr class="nonstick_outer_bg">
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="?cat=415">
			<img class="c_movies_remux" src="pic/cattrans.gif" alt="Movies REMUX" title="Movies REMUX" style="background-image: url(pic/category/chd/scenetorrents/en/catsprites.png);">
		</a>
	</td>
	<td class="rowfollow" width="100%" align="left">
		<table class="torrentname" width="100%">
			<tbody>
				<tr class="nonstick_inner_bg">
					<td class="embedded">
						<a title="The Searchers 1956 1080p BluRay Remux VC-1 DD 1.0-ADE" href="details.php?id=(removed)&amp;hit=1">
							<b>The Searchers 1956 1080p BluRay Remux VC-1 DD 1.0-ADE</b>
						</a>
						<img class="pro_50pctdown" src="pic/trans.gif" alt="50%" title="50%">
					</td>
					<td width="80" class="embedded" style="text-align: right;" valign="middle"></td>
					<td width="60" class="embedded" style="text-align: right;" valign="middle"></td>
					<td width="100" class="embedded" style="text-align: right;" valign="middle"></td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow nowrap">2024-08-08<br>14:18:41</td>
	<td class="rowfollow">19.52<br>GB</td>
	<td class="rowfollow" align="center">
		<b>
			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#seeders">7</a>
		</b>
	</td>
	<td class="rowfollow">0</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=(removed)">
			<b>10</b>
		</a>
	</td>
	<td class="rowfollow">
		<i>Anonymous</i>
	</td>
</tr>
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.handleSelector(selectorBlock Selector, IElement Dom, Dictionary`2 variables, Boolean required) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1265
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1837
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1862`

**Comment by garfield69** [comment]
oops. added the download block for the details page, forgot to take out the download link on the row ;-(
just a moment.

**Comment by garfield69** [comment]
Okely Dokely, try v0.22.426

**Comment by iNfRaS0NiC** [comment]
@garfield69 I can confirm that now HDArea is working as expected, thank you.
However, do the same fix for this one - https://github.com/Jackett/Jackett/issues/15524

**Comment by garfield69** [comment]
Darn. Should have taken the time to double check that one too ;-b
Ah well. Fix is in progress.
