### ISSUE TITLE
YggTorrent

### ISSUE THREAD

**Issue by hugolapointe** [Jackett/Jackett#1553]
In the Readme file, it said that YggTorrent is now supported. I also saw the commit. But I can't figure how to add it. I did update my version, but still, I only see the old T411 indexer. Can you help me?

**Comment by ploufs** [comment]
Available in pre-release v0.7.1557
https://github.com/Jackett/Jackett/releases

**Comment by hugolapointe** [comment]
I'm using the image of jackett on docker. Which tag can I use to pull the pre-release version?

**Comment by chibidev** [comment]
@hugolapointe you can use the default tag (latest), pre-release need to be enabled on the UI once you have Jackett running.
