### ISSUE TITLE
[req]: Add additional URL to BitMagnet indexer definition to allow connections within docker-compose stack

### ISSUE THREAD

**Issue by tyrells** [Jackett/Jackett#15537]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Currently the only URL defined for the BitMagnet (Local DHT) indexer is `http://127.0.0.1:3333/`. When using Jackett and BitMagnet as part of a single docker-compose stack file (i.e. [Servarr wiki Docker guide](https://wiki.servarr.com/docker-guide)), you cannot connect to a different container in the same stack using the localhost IP address, but must rather use the `container_name` specified for the particular container you are trying to connect to.

### Describe the solution you'd like

Add a second URL in the BitMagnet indexer definition file as follows `http://bitmagnet:3333/`. This is the `container_name` used in the [official bitmagnet installation instructions](https://bitmagnet.io/setup/installation.html).

**Comment by ilike2burnthing** [comment]
Reconfigure indexer, edit site link, click Okay.
