### ISSUE TITLE
Help creating new definition

### ISSUE THREAD

**Issue by Guizzoni** [Jackett/Jackett#1554]
Hi, i'm trying to create a new definition for a Brazilian tracker called "Manicomio Share". 
I'm able to properly configure the categories and Jackett is even requesting the correct search URL, but i'm having some trouble in the "selector" part.

Can someone give me a hand writing the code to show the results in Jackett?
This the HTML response from the search (results start on line 595): [https://pastebin.com/vUQBAFXe](https://pastebin.com/vUQBAFXe)
This is the definition YML: [https://pastebin.com/KDMgQXbr](https://pastebin.com/KDMgQXbr)
Error in Jackett console: [https://pastebin.com/iEpX8gqD](https://pastebin.com/iEpX8gqD)

**Comment by Guizzoni** [comment]
EDIT: Fixed by using "selector: td:nth-child" instead of "selector: a[href^="torrents.php?id="]"

**Comment by kaso17** [comment]
The following selectors would work too:
```a[href^="https://www.manicomio-share.com/download.php?id="]```

Or this one (more flexible in case the URL changes):
```a[href*="/download.php?id="]```

**Comment by Guizzoni** [comment]
Thanks kaso17!
