### ISSUE TITLE
[req]: Jackett as an indexer in Sonarr and Radarr

### ISSUE THREAD

**Issue by Kapy2003** [Jackett/Jackett#15545]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

It is very frustrating and tedious job to manually add countless indexers and manage them it can be useful and easier if the Jackett app can be used as an indexer in Sonarr and Radarr app

### Describe the solution you'd like

It would be great if Jackett can be added in Sonarr and Radarr as an indexer where we only have to manage Jackett indexer and the indexers in Sonarr and Radarr are managed not talking about Prowlarr.

**Comment by garfield69** [comment]
Never going to happen. 
If you want the bells and whistles then Prowlarr is the app that would probably  suit you better.
Jackett is meant to be a bread and butter no fuss no gravy app that just gets the basics right.
