### ISSUE TITLE
Windows: request to Jackett server failed

### ISSUE THREAD

**Issue by primaeval** [Jackett/Jackett#1555]
I tried a search on a local machine and and a remote machine.
Search and View Cached Releases fail with "request to Jackett server failed".
[log.txt](https://github.com/Jackett/Jackett/files/1143355/log.txt)

**Comment by chibidev** [comment]
@primaeval Thank you for reporting. Please know, that this was already fixed by #1543 and is available in the latest pre-release version (0.7.1557). Please update to that version and report whether the issue persists.

Thanks.

**Comment by primaeval** [comment]
It did fix it. Thanks very much.
I had to run JackettUpdater.exe manually as the web interface update also wouldn't work due to the bug.

**Comment by Mahmoud87** [comment]
@chibidev I am on Linux guys and tried to update but always return with "Checked for updated release but none found", eventhough the "update to pre-released" box is ticked. Has anyone had this problem?

**Comment by chibidev** [comment]
@Mahmoud87 would you please check "Enhanced logging" on the web UI, reproduce the issue and post your log file somewhere? It would help us track down the issue.

**Comment by Mahmoud87** [comment]
Hi @chibidev here is the log mate, ticked the Enhanced logging box, also the upgrade to the pre-release box.

`

When | Level | Message
-- | -- | --
Jul 18, 2017 07:14:55 AM | Info | Checked for a updated release but none was found.
Jul 18, 2017 07:14:45 AM | Error | HandleCore(): unhandled exception: Message = Self referencing loop detected for property 'encoding' with type 'System.Text.Latin1Encoding'. Path 'Results[2].Origin.Encoding.encoderFallback'. Data = System.Collections.ListDictionaryInternal InnerException =  TargetSite = Void Throw() StackTrace =   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x00105] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContainerContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.Serialization.JsonContract& memberContract, System.Object& memberValue) [0x000c7] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b0] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b0] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b0] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b0] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList (Newtonsoft.Json.JsonWriter writer, System.Collections.IEnumerable values, Newtonsoft.Json.Serialization.JsonArrayContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000d6] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000d4] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b0] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00253] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value) [0x00000] in <907bcb40e35c44f399677976c6fdd480>:0    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream (System.Type type, System.Object value, System.IO.Stream writeStream, System.Text.Encoding effectiveEncoding) [0x0004a] in <dd5d13035e4d4a2e812d07ec2f066876>:0    at System.Net.Http.Formatting.JsonMediaTypeFormatter.WriteToStream (System.Type type, System.Object value, System.IO.Stream writeStream, System.Text.Encoding effectiveEncoding) [0x00084] in <dd5d13035e4d4a2e812d07ec2f066876>:0    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream (System.Type type, System.Object value, System.IO.Stream writeStream, System.Net.Http.HttpContent content) [0x00015] in <dd5d13035e4d4a2e812d07ec2f066876>:0    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync (System.Type type, System.Object value, System.IO.Stream writeStream, System.Net.Http.HttpContent content, System.Net.TransportContext transportContext, System.Threading.CancellationToken cancellationToken) [0x00031] in <dd5d13035e4d4a2e812d07ec2f066876>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113    at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__24.MoveNext () [0x0019d] in <f99f496cb0d249c1a945c1fcabce1695>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447    at System.Net.Http.HttpContent+<LoadIntoBufferAsync>d__17.MoveNext () [0x00064] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/System.Net.Http/System.Net.Http/HttpContent.cs:146  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113    at System.Web.Http.Owin.HttpMessageHandlerAdapter+<BufferResponseContentAsync>d__13.MoveNext () [0x000a0] in <3af1be95d6624fee83df21798930c383>:0  HelpLink =  Source = mscorlib HResult = -2146233088
Jul 18, 2017 07:14:45 AM | Error | Unhandled exception url: http://192.168.1.10:9117/Admin/search
Jul 18, 2017 07:14:45 AM | Error | Unhandled exception: Message = Self referencing loop detected for property 'encoding' with type 'System.Text.Latin1Encoding'. Path 'Results[2].Origin.Encoding.encoderFallback'. Data = System.Collections.ListDictionaryInternal InnerException =  TargetSite = Void Throw() StackTrace =   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x00105] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContainerContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.Serialization.JsonContract& memberContract, System.Object& memberValue) [0x000c7] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b0] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b0] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b0] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b0] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList (Newtonsoft.Json.JsonWriter writer, System.Collections.IEnumerable values, Newtonsoft.Json.Serialization.JsonArrayContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000d6] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000d4] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b0] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00253] in <907bcb40e35c44f399677976c6fdd480>:0    at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value) [0x00000] in <907bcb40e35c44f399677976c6fdd480>:0    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream (System.Type type, System.Object value, System.IO.Stream writeStream, System.Text.Encoding effectiveEncoding) [0x0004a] in <dd5d13035e4d4a2e812d07ec2f066876>:0    at System.Net.Http.Formatting.JsonMediaTypeFormatter.WriteToStream (System.Type type, System.Object value, System.IO.Stream writeStream, System.Text.Encoding effectiveEncoding) [0x00084] in <dd5d13035e4d4a2e812d07ec2f066876>:0    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream (System.Type type, System.Object value, System.IO.Stream writeStream, System.Net.Http.HttpContent content) [0x00015] in <dd5d13035e4d4a2e812d07ec2f066876>:0    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync (System.Type type, System.Object value, System.IO.Stream writeStream, System.Net.Http.HttpContent content, System.Net.TransportContext transportContext, System.Threading.CancellationToken cancellationToken) [0x00031] in <dd5d13035e4d4a2e812d07ec2f066876>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113    at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__24.MoveNext () [0x0019d] in <f99f496cb0d249c1a945c1fcabce1695>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447    at System.Net.Http.HttpContent+<LoadIntoBufferAsync>d__17.MoveNext () [0x00064] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/System.Net.Http/System.Net.Http/HttpContent.cs:146  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /builddir/build/BUILD/mono-5.0.1.1/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113    at System.Web.Http.Owin.HttpMessageHandlerAdapter+<BufferResponseContentAsync>d__13.MoveNext () [0x000a0] in <3af1be95d6624fee83df21798930c383>:0  HelpLink =  Source = mscorlib HResult = -2146233088
Jul 18, 2017 07:14:44 AM | Info | Manual search for "John Wick" on AlphaRatio, Demonoid, FunFile, IPTorrents, Speed.cd, TorrentBytes, TorrentLeech with 215 results.
Jul 18, 2017 07:14:11 AM | Info | Checked for a updated release but none was found.
Jul 18, 2017 07:12:51 AM | Info | Checked for a updated release but none was found.
Jul 18, 2017 07:11:29 AM | Info | Found 5 torrentpotato releases from Demonoid for: Baywatch 2017

`

**Comment by chibidev** [comment]
@Mahmoud87 sorry for asking a dumb question, but did you press "Apply server settings" button after ticking both checkboxes? The log still contains only Info level messages, so I'm just wondering...

**Comment by Mahmoud87** [comment]
@chibidev Stupidly enough from me I didn't, how sad!! Lol. Cheers man I tried it after applying the server settings and it worked perfectly fine upgraded to the beta ver. Also the manual search works fine. Thanks man and sorry for this mistake 👍
