### ISSUE TITLE
[req]: RareFilm - Rare Films on Requests

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#15563]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: RareFilm - Rare Films on Requests
- URL: https://rarefilm.net/
- Description: Rare Films on Requests. Download Rare Classic and Selected Films, Request on Classic Movies
- Additional Comments: Seems to be open without registration but... the link is hosted behind a nitroflare link, not sure if it is possible to have
```

**Comment by garfield69** [comment]
This site is not suitable for indexing with Jackett because the site does not provide a direct download link to the .torrent file.
See https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
