### ISSUE TITLE
how to add all jackett indexers to sonarr and radarr at once

### ISSUE THREAD

**Issue by potatosips** [Jackett/Jackett#15569]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
ubuntu docker
```

### Description

using Jackett Version v0.22.540 docker. i tried to add http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab/ to radarr and sonarr url page. it loads for a while after pressing test or save. then it shows a warning sign (no messege)

all I want is to add all the jacket indexers to sonarr and radarr. how to do that?
adding hundreds of indexes to sonarr and radarr one by one would be a psychopathic task.

please share a add feature to add all the indexers to sonarr and radarr at once

### Logged Error Messages

```text
sonarr  | [Warn] SonarrErrorPipeline: Invalid request Validation failed:
sonarr  |  -- ApiPath: Jackett's all endpoint is not supported, please add indexers individually
```

### Screenshots

![image](https://github.com/user-attachments/assets/36b01fb3-3482-4362-bad1-d6d9278c4400)
![image](https://github.com/user-attachments/assets/42daf272-f0e0-491b-9ddf-81c4ff0b2d9f)

**Comment by garfield69** [comment]
There is no `add all indexer` at once option in Jackett.
Looks like you may prefer to use Prowlarr, its the all bells and whistles alternative to our Jackett and feeds off our indexers so you wont miss out.
