### ISSUE TITLE
[req]: https://aitorrent.zerroug.de/

### ISSUE THREAD

**Issue by joaquinito2070** [Jackett/Jackett#15567]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: AiTorrent
- URL: https://aitorrent.zerroug.de/
- Description: AiTorrent is a new torrent tracker for AI models.
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments:
```

**Comment by garfield69** [comment]
Not sure this is a site suitable for indexing with Jackett.
It's not the usual movie or tv or game or audio or book site, does not have categories, date, size, seeds etc.
The latest page is not in the same layout as the search page results, and the search page does not support keywordless search.
Using the default 2024 as a substitute for a keywordless search returns no results.
Do not see the benefit of adding an indexer for this site.
