### ISSUE TITLE
[rutracker] Can't find anime titles on rutracker by season

### ISSUE THREAD

**Issue by shir** [Jackett/Jackett#15566]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
[custom-init] No custom files found, skipping...
08-30 12:13:10 Info Starting Jackett v0.22.534
08-30 12:13:18 Info Environment version: 8.0.8 (/app/Jackett/)
08-30 12:13:18 Info OS version: Unix 4.4.302.0 (64bit OS) (64bit process)
08-30 12:13:18 Info Jackett variant: CoreLinuxMuslAmdx64
08-30 12:13:18 Info File /etc/issue: Welcome to Alpine Linux 3.20
08-30 12:13:18 Info Running in Docker: Yes (image build: v0.22.534-ls513)
08-30 12:13:18 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
08-30 12:13:18 Info App config/log directory: /config/Jackett
08-30 12:13:18 Info Using proxy: Disabled
08-30 12:13:18 Info Using FlareSolverr: No
08-30 12:13:18 Info Using HTTP Client: HttpWebClient2
08-30 12:13:18 Info Loading Native indexers ...
08-30 12:13:18 Info Loaded 71 Native indexers.
08-30 12:13:18 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
08-30 12:13:26 Info Loaded 541 Cardigann indexers.
08-30 12:13:26 Info Loaded 612 indexers in total
08-30 12:13:26 Info Adding aggregate indexer ('all' indexer) ...
08-30 12:13:26 Info Adding filter indexer ('type:public' indexer) ...
08-30 12:13:26 Info Adding filter indexer ('type:private' indexer) ...
08-30 12:13:26 Info Adding filter indexer ('type:semi-public' indexer) ...
08-30 12:13:27 Info Jackett startup finished in 19.024 s
Hosting environment: Production
```

### Description

I use Jackett together with Sonarr and had this issue for years. And today I finally decided to figure out what's going on.

When Sonarr searches for a TV show (including anime) by season it adds "S01" which is [translated to the "Сезон 1" for rutracker](
https://github.com/Jackett/Jackett/blob/ef7ade22f00374d2ee7fbb47f37bd8dab6791dd3/src/Jackett.Common/Indexers/Definitions/RuTracker.cs#L1541). And it works well for TV shows. But for animes on rutracker the format "ТВ-1" is used so it doesn't find any anime (see screenshots 1 and 2 below)

I suggest translating "S01" into the "Сезон | ТВ 1" to find anime results too (see the search example screenshot below).

### Logged Error Messages

```text
No error, just empty results.
```

### Screenshots

![SCR-20240830-gmx](https://github.com/user-attachments/assets/0117980e-8073-4312-9d11-1c8de3d2b839)
![SCR-20240830-gnb](https://github.com/user-attachments/assets/186f3caf-8eb8-4ae9-81cd-36ca94ff924f)
![SCR-20240830-gt6](https://github.com/user-attachments/assets/036e9974-089e-4937-9283-f55cf54ebb4a)

**Comment by garfield69** [comment]
v0.22.707

**Comment by shir** [comment]
@garfield69 Thank you for the fix! I confirm it works. (messed up with my notifications and wasn't aware of the update for a while)
