### ISSUE TITLE
[req]: TorrentGalaxy

### ISSUE THREAD

**Issue by gh0sti** [Jackett/Jackett#15579]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: TorrentGalaxy
- URL: https://torrentgalaxy.to/
- Description: Semi-Private? Torrent Tracker for Movies, TV, Games
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments: We're currently allowing 5 sign ups a day.
No more sign ups left for today, check back tomorrow.
```

**Comment by ilike2burnthing** [comment]
> ### Is there already a request for your tracker?
> - [X] I have checked older issues, open and closed

Uh huh...

**Comment by gh0sti** [comment]
@ilike2burnthing 
<img width="954" alt="closed" src="https://github.com/user-attachments/assets/6d78583c-594d-4e35-b311-c0bfc869e2a8">
<img width="854" alt="open issues" src="https://github.com/user-attachments/assets/4799ed04-6920-46f7-b36a-6d51f9284df4">


Looking at open and closed I didn't see a specific [req]TorrentGalaxy unless it was the one trying to fix for synology which I do apologize then for not understanding that was considered an open case.

**Comment by ilike2burnthing** [comment]
See the top open issue there.
