### ISSUE TITLE
[sktorrent] (updating) The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.: A task was canceled.

### ISSUE THREAD

**Issue by slrslr** [Jackett/Jackett#15571]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/user/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Debian GNU/Linux 11 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.0.32 (64bit OS) (64bit process)
Environment version: 8.0.8 (/opt/Jackett/)
Starting Jackett v0.22.545 (installed from Jackett.Binaries.LinuxAMDx64.tar.gz)
```

### Description

Click Add new Indexer button, search "skt", select configuration button at line "SkTorrent".
Fill random username and password.

Wait like a minute, it returns:

The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

### Logged Error Messages

```text
https://bin.disroot.org/?9bd4382c5cdb62d9#E1rAEdT3QeP1gkHHT1vS2xb8VYtecrZcGsHLrqSfdu9w
```

**Comment by garfield69** [comment]
The indexer is working for me which suggests the issue is at your end.
See https://github.com/Jackett/Jackett/wiki/TroubleShooting#a-connection-attempt-failed for possible reasons and solution attepts.

**Comment by slrslr** [comment]
Thank you for testing this and quick reply, You were right, it appears that the tracker is refusing the connection from the IP which my Jackett is using. I will consider using a proxy in a Jackett configuration.
