### ISSUE TITLE
Installation/Update Problems - Error Message : "Unable to execute file in temporary directory. Setup aborted . Error 5: Access is denied."

### ISSUE THREAD

**Issue by 13regent** [Jackett/Jackett#15572]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-09-01 23:57:14	Info	Using FlareSolverr: No
2024-09-01 23:57:14	Info	Using proxy: Disabled
2024-09-01 23:57:14	Info	App config/log directory: C:\ProgramData\Jackett
2024-09-01 23:57:14	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2024-09-01 23:57:14	Info	Running in Docker: No
2024-09-01 23:57:14	Info	Jackett variant: CoreWindows
2024-09-01 23:57:14	Info	OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
2024-09-01 23:57:14	Info	Environment version: 6.0.20 (C:\ProgramData\Jackett\)
2024-09-01 23:57:10	Info	Starting Jackett v0.21.565
```

### Description

Was using newer version of Jackett...maybe a few weeks old... and today I could not connect to the web interface. Uninstalled and downloaded version 0.22.540. Tried to install it and and get the message "Unable to execute file in temporary directory. Setup aborted . Error 5: Access is denied." Tried right clicking setup and run as administrator with no change. I have my temp folder open and when I try to install I can see a folder created and then disappear and then get the "Error 5: Access is denied". I had a very old  version of Jackett version 0.21.565 saved and tried installing it. It installs fine...but will not update.  This all worked ok fine a few weeks ago. Not sure how or why things went sideways. 

### Logged Error Messages

```text
2024-09-02 00:01:27	Error	
Error performing update.
System.ComponentModel.Win32Exception (5): An error occurred trying to start process 'C:\WINDOWS\TEMP\JackettUpdate-v0.22.545-638608320735207340\Jackett\JackettUpdater.exe' with working directory 'C:\WINDOWS\system32'. Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Jackett.Common.Services.UpdateService.StartUpdate(String updaterExePath, String installLocation, Boolean isWindows, Boolean noRestart, Boolean trayIsRunning) in ./Jackett.Common/Services/UpdateService.cs:line 357
   at Jackett.Common.Services.UpdateService.CheckForUpdates() in ./Jackett.Common/Services/UpdateService.cs:line 138
2024-09-02 00:01:27	Info	
Starting updater: C:\WINDOWS\TEMP\JackettUpdate-v0.22.545-638608320735207340\Jackett\JackettUpdater.exe --Path "C:\ProgramData\Jackett" --Type "WindowsService" --Args " " --KillPids "2936"
2024-09-02 00:01:03	Info	
Downloading release v0.22.545 It could take a while...
2024-09-02 00:01:03	Info	
New release found. Current version: v0.21.565 New version: v0.22.545
2024-09-02 00:01:02	Info	
Checking for updates... Jackett variant: CoreWindows
2024-09-02 00:00:34	Info	
Jackett startup finished in 204.417 s
2024-09-02 00:00:34	Error	
An error occurred during the last update. If this error occurs again, you need to reinstall Jackett following the documentation. If the problem continues after reinstalling, report the issue and attach the Jackett and Updater logs.
2024-09-02 00:00:33	Info	
Deleting JackettUpdate temp files from C:\WINDOWS\TEMP\JackettUpdate-v0.22.545-638608318822958781
2024-09-02 00:00:33	Info	
Adding filter indexer ('type:semi-public' indexer) ...
2024-09-02 00:00:33	Info	
Adding filter indexer ('type:private' indexer) ...
2024-09-02 00:00:33	Info	
Adding filter indexer ('type:public' indexer) ...
2024-09-02 00:00:33	Info	
Adding aggregate indexer ('all' indexer) ...
2024-09-02 00:00:33	Info	
Loaded 592 indexers in total
2024-09-02 00:00:33	Info	
Loaded 519 Cardigann indexers.
2024-09-02 00:00:32	Info	
Loading Cardigann indexers from: C:\ProgramData\Jackett\cardigann\definitions\, C:\ProgramData\Jackett\Definitions
2024-09-02 00:00:32	Info	
Loaded 73 Native indexers.
2024-09-02 00:00:32	Info	
Loading Native indexers ...
2024-09-02 00:00:32	Info	
Using HTTP Client: HttpWebClient2
2024-09-02 00:00:32	Error	
Your version of Jackett v0.21.565 is very old. Multiple indexers are likely to fail when using an old version. Update to the latest version of Jackett.
```

### Screenshots

![image](https://github.com/user-attachments/assets/a750aaaa-2e5a-41e5-b780-f8b30f05062a)

**Comment by garfield69** [comment]
I think it best if you install afresh from https://github.com/Jackett/Jackett/releases/download/v0.22.545/Jackett.Installer.Windows.exe
and then once I publish 0.22.549 in about 30 minutes, you can use your dashboard and click on the check for updates button and see if the update starts working again.

**Comment by garfield69** [comment]
Also check that your anti-malware is not getting in the way, perhaps its tripping over a false hit on the Jackett updater or other modules.

**Comment by 13regent** [comment]
Thanks for your suggestion. I use Windows Defender as my antivirus and it is blocking Jackett from being installed. I temporarily removed its real-time protection and installed Jackett 0.22.549 without issue. I will have to figure out how to make an exception for this.

![image](https://github.com/user-attachments/assets/83197875-686c-477f-ba18-77cf89b9f1c8)

**Comment by garfield69** [comment]
I don't use defender but perhaps this is useful for you: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by 13regent** [comment]
To add an exclusion for Jackett in Windows Defender see screenshot.

![image](https://github.com/user-attachments/assets/35948827-8690-4c91-b5a0-3af2a1096dbe)

**Comment by ilike2burnthing** [comment]
Are you using an enterprise or business device, or have you used a tool or script such as ConfigureDefender to modify Defender's settings? If so, that will be the cause of your issue. If the exclusion doesn't resolve your issue, you'll need to look at how your ASR is configured (we won't be providing help for that).

**Comment by 13regent** [comment]
It appears that Windows Defender now has an attack surface reduction rule to block Jackett.

**Comment by ilike2burnthing** [comment]
Nope, just to detect ransomware as shown in your screenshot, but seemingly it's poorly coded and is falsely detecting the updater as malicious. Feel free to submit a false positive report or change to a better AV - https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by 13regent** [comment]
I submitted a false positive report yesterday.

**Comment by ilike2burnthing** [comment]
Many thanks.
