### ISSUE TITLE
danishbytes.club is not in english?

### ISSUE THREAD

**Issue by slrslr** [Jackett/Jackett#15586]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
-
```

### Description

https://danishbytes.club does not speak english to me, should you replace "en-US" in https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/danishbytes-api.yml by "da-DK" (http://www.lingoes.net/en/translator/langcode.htm) ?

### Logged Error Messages

```text
-
```

**Comment by garfield69** [comment]
Sure we can do that. The Indexer language was originally based on their site's HTML language tag which is set to EN, but their rules and FAQ are in Danish despite the rest of the site having multi-languages option that their UNIT3D engine supports.

**Comment by garfield69** [comment]
v0.22.581

**Comment by MandeHanne29** [comment]
Someone there has an invite link I need to get
