### ISSUE TITLE
[dimeadozen] (testing) Exception (dimeadozen): Login failed: Selector "a[href="account-logout.php"]" didn't match: Parse error

### ISSUE THREAD

**Issue by slrslr** [Jackett/Jackett#15587]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/user/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Debian GNU/Linux 11 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.0.32 (64bit OS) (64bit process)
Environment version: 8.0.8 (/opt/Jackett/)
Starting Jackett v0.22.545 (installed from Jackett.Binaries.LinuxAMDx64.tar.gz)
```

### Description

I have registered a new account at http://www.dimeadozen.org/ and added new indexer, after testing it at http://127.0.0.1:9117/UI/Dashboard it returns the error in the title of this issue, i can login on site, but not in Jackett where submission of same login data returns said error.

### Logged Error Messages

```text
-
```

**Comment by garfield69** [comment]
The indexer is working for me so this suggests the problem is at your end.
Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by slrslr** [comment]
Thanks, the [enhanced log](https://bin.disroot.org/?b411d7aefabd5da1#4kY2Y3FpfaGmw4LDbtGCURdhhMtKFHL848upZScULuRD) (password: j) file revealed that my IP is actually forbidden (403) to access the web page. My web browser is using different IP than my system (Jackett) so that is why I have failed to realize why it fails. Second reason is that Jacket did not provide more useful message that would suggest forbidden connection.

**Comment by garfield69** [comment]
@mynameisbogdan  Does the Jackett Cardigann not trap http code 403 and give a  more useful message?
Do I need to add to the indexer in the login error block a trap for `- selector: :root:contains("Error 403")` instead?

**Comment by garfield69** [comment]
Ok thanks. I'll code a specific trap in the indexer login block instead.

**Comment by garfield69** [comment]
v0.22.581
