### ISSUE TITLE
 [xxxclub] indexer searches not working

### ISSUE THREAD

**Issue by HornyQT** [Jackett/Jackett#15581]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://localhost:8191/
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.22.534-ls513)
File /etc/issue: Welcome to Alpine Linux 3.20
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.6.46.1 (64bit OS) (64bit process)
Environment version: 8.0.8 (/app/Jackett/)
```

### Description

after adding the indexer the search does not work anymore.
giving the same result for each query.

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment]
v0.22.574
