### ISSUE TITLE
[req]: BitStream

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#15597]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: BitStream
- URL: https://bitstream.click/
- Description: BitStream is a SPANISH Private tracker for H.265 MOVIES / TV
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MST 15d
- Additional Comments: 
Engine: Unit3d 8.2.0
Registration: Open ATM
```

**Comment by garfield69** [comment]
While registration is open ATM their email does not appear to be working. I am not getting confirmation or password reset mail to gmail [dot] com ;-(

**Comment by garfield69** [comment]
v0.22.600

**Comment by ilike2burnthing** [comment]
Supposedly the owner left - https://www.reddit.com/r/OpenSignups/comments/1fgjuxp/comment/lrdq4pt/

@bitstream-click can you confirm?

**Comment by garfield69** [comment]
v0.22.907
