### ISSUE TITLE
[request]  new tracker www.torrentdownloads.me

### ISSUE THREAD

**Issue by neuman1812** [Jackett/Jackett#1559]
https://www.torrentdownloads.me/

Good little site,  open to the public.
-------------------------------

**Comment by Guizzoni** [comment]
Added on PR #1563

**Comment by chibidev** [comment]
Merged #1563, thank you @Guizzoni for the contribution.

**Comment by garfield69** [comment]
https://www.torrentdownloads.me/ returning This site can’t be reached

**Comment by garfield69** [comment]
https://www.torrentdownloads.info/ works as does https://torrentdownloads.unblockit.club/

**Comment by ilike2burnthing** [comment]
*.me is working here (in Jackett and browser) so long as I use a VPN or proxy, otherwise my AV (Kaspersky) refuses let it load.

**Comment by garfield69** [comment]
Switched back to using cloudflare 1.1.1.1 instead of quad9 9.9.9.9 and now its working.

**Comment by ilike2burnthing** [comment]
https://www.torrentdownloads.info/ - working
https://www.torrentdownloads.info/today/ - no torrents (and hasn't been for the last few days)

**Comment by garfield69** [comment]
if in another 15 days torrentdownloads has still not fixed their recent-uploads page then we could add a default search of today.year so retain the indexer that way.
there are several sites that are used mostly as archives since they stopped getting updates for which we keep indexers active.

**Comment by garfield69** [comment]
v0.18.623
