### ISSUE TITLE
Changed in YAML fields details for those :  GKtorrent OxTorrent-vip Torrent9 Torrent9-tel

### ISSUE THREAD

**Issue by elvis-gratton** [Jackett/Jackett#15610]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP client HttpWeClient
FlareSolver Disabled
Proxy Disabled
Docker Yes
Jackett Version v0.22.681
windows 11 x64 with Docker Desktop
```

### Description

Hi there,

download magnets links are not working on those site.
some change need to be done on the following YAML files for:
gktorrent
oxtorrent-vip
torrent9
torrent9-tel

those are the change needed:

gktorrent		fields-details 							changed torrent >> detail
oxtorrent-vip	fields-details_href & details_onclick 	        changed torrent >> detail
torrent9		download-selectors  					changed 
torrent9-tel	fields-details_href & details_onclick 	        changed torrent >> detail

I have included the fix in the attached zip file.

[YAML-fixed.zip](https://github.com/user-attachments/files/17171146/YAML-fixed.zip)

Have a nice day !

### Logged Error Messages

```text
see description section

fix is include in the zip file.
```

**Comment by garfield69** [comment]
Thank You.

**Comment by garfield69** [comment]
v0.22.685
