### ISSUE TITLE
[req]: A manual search only page without being able to edit settings

### ISSUE THREAD

**Issue by kuolemaaa** [Jackett/Jackett#15617]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

The problem is that to manual search something I still need to type the admin password I would like to have separation of this kind of thing an admin-password-protected dashboard to edit jackett settings and an optionally normal-user-password-protected manual search page

### Describe the solution you'd like

An endpoint to /UI/Search with the possibility to access it without an admin password or, at least, with a non-admin password

### Describe alternatives you've considered

I was looking for some web application that can forward query to jackett using the api key but I didnt find any

**Comment by garfield69** [comment]
Jackett is designed for personal use only. 
There is no https support, and the dashboard is not set up for multi-user access.
the apikey is meant to be a private key, and the admin password when enabled prevents unauthorised access to the dashboard if you choose to access it via WAN.
Typical usage scenario is a single user with LAN access.

There are no plans to enable multi-user secure access to the jackett services.

**Comment by kuolemaaa** [comment]
For the completeness of the information: I managed to do what I wanted using nzbhydra
