### ISSUE TITLE
[req]: Allow zenrows as potential cloudflare solver (Possible solution for, Ygg and many others regarding flaresolver problems).

### ISSUE THREAD

**Issue by CyberPoison** [Jackett/Jackett#15611]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hi, everyone.

I have found a tool called ZenRows, that allow to access to websites with cloudflare, i have tested it for a while, it's a bit expensive (arround 65$/Month) but it will be nice to have diferents solutions when flaresolver don't works as, or when cloudflare has locked us out of automation . 

### Describe the solution you'd like

The zenrows allow proxy also for solving cloudflare, but i got this issue.

```bash
Exception (yggtorrent): certificate validation failed: [Subject] CN=api.zenrows.com, O=ZenRows Proxy [Issuer] E=, CN=proxy.zenrows.com, OU=ZenRows, O=ZenRows, L=Getxo, S=Bizkaia, C=ES [Serial Number]  [Not Before] 8/29/2024 12:02:58 AM [Not After] 9/28/2025 12:02:58 AM [Thumbprint]  : The SSL connection could not be established, see inner exception.
```

and have also a way to test over api/curl with query parameters (It comes with 1K free requests on sign up)
, in my opinion over api will be much cool due to long range of query that we could use.

### Describe alternatives you've considered

```
public static bool ValidateCertificate(HttpRequestMessage request, X509Certificate2 certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
{
    return true; // Always trust the certificate just for testing.
}
```

According to the actuall code but not tested yet.
As i would like to consider the best before ending to edit the code and compile my self, on MacOS M1 and made a docker only for testing.

And finaly just to remmeber than ygg as long as many others are have been free for years and many like ygg don't have api, so i'm starting considering realy to pay maybe 30-40$/Month just for something that really let me scrape as if it was a api. 

Ygg as disabled he's cflare for maybe 2 weeks but they already had blocked it/put it back.

And flaresolver don't seems to work good again and it's looks like more the game of the cat and the mouse last months.

ZenRows website: https://zenrows.com

**Comment by ilike2burnthing** [comment]
Are you able to use ZenRows as a normal HTTP proxy? If so, can you not just use the normal proxy settings in Jackett?

As for FlareSolverr, see the contributor builds in the recent PRs on that repo.

**Comment by ilike2burnthing** [comment]
Please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
try the following:
1. restart Jackett, view the log from the dashboard and scroll to the bottom
2. look for the entry `Loading Cardigann indexers from:`. The last path is where yggtorrent.yml is stored, and the first path is a folder you can store custom yml into. For example on my win10 its `Loading Cardigann indexers from: C:\ProgramData\Jackett\cardigann\definitions\, C:\ProgramData\Jackett\Definitions`
3. copy yggtorrent.yml from definitions to cardigann/definitions
4. use a plain text editor and open yggtorrent.yml
5. insert after requestdelay the following
```yaml
certificates:
  - 8CD76FDE73A3326E4A373D30D10E87FAC7714103
```
6. save and restart Jackett
7. try it out and see if that helps bypass the issue.
