### ISSUE TITLE
[req]: need request yamaahmad493@gmail.com

### ISSUE THREAD

**Issue by yamaahmad493** [Jackett/Jackett#15619]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

need request

### Describe the solution you'd like

need request to login

**Comment by garfield69** [comment]
Sorry, I've no idea what you are asking for.
Request to login to Jackett?
You mean you have lost the Jackett admin password, or you are not seeing the login prompt or not even the Jackett dashboard?
More info please.

**Comment by yamaahmad493** [comment]
> Sorry, I've no idea what you are asking for.
> Request to login to Jackett?
> You mean you have lost the Jackett admin password, or you are not seeing the login prompt or not even the Jackett dashboard?
> More info please.

I mean for tapechek.net

**Comment by ilike2burnthing** [comment]
Then click the `Забыли пароль?` (forgot your password) button on the site. We're not a support channel for various trackers. I am deleting this issue as it contains your email address in the title, you'll likely get spam now.
