### ISSUE TITLE
[yts] (testing) Exception (yts): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Error Parsing Json Response

### ISSUE THREAD

**Issue by AlZaabiXIV** [Jackett/Jackett#15622]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using YTS indexer in Jackett
Testing YTS Fail
```

### Description

All the old links aren't active.
The latest active address: https://en.yts-official.mx/, is not available on the YTD > Configure > Site Link (list)

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (yts): No such host is known.: No such host is known. (yts.mx:443)
Click here to open an issue on GitHub for this indexer.
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/blob/59f29abfc44b951953b92631dd1988260279bb4b/src/Jackett.Common/Definitions/yts.yml#L12

Your address is a fake clone.

As Bogdan said, it's likely an ISP block or other content filter, you'll need to change your DNS, or use a proxy/VPN.
