### ISSUE TITLE
[crazyspirits] (testing) Test search in CrazySpirits => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by nitrup** [Jackett/Jackett#15647]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.22.779
FlareSolverr v3.3.21
No freeleech check
```

### Description

After successfully adding the indexer, it was impossible to run a test on it, so it was impossible to add it to Sonarr or radarr.

### Logged Error Messages

```text
Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
```

### Screenshots

![image](https://github.com/user-attachments/assets/f7da03f6-4c0c-4432-8201-0230a691fe52)

**Comment by garfield69** [comment]
update your Jackett to v0.22.789 to resolve.

**Comment by nitrup** [comment]
Thanks it works
