### ISSUE TITLE
[request] Please add BTDB to list

### ISSUE THREAD

**Issue by OasisFounder** [Jackett/Jackett#1564]
http://btdb.to/

This is a great fallback torrent site to retrieve hard to find items and all torrents in general. Its open/public - I tried creating a scraper file but failed.

**Comment by ilike2burnthing** [comment]
https://btdb.eu/ - working
https://btdb.eu/recent - working
https://btdb.eu/recent?sort=time (or any other sort) - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://btdb.eu/ - working
https://btdb.eu/recent (or any other page) - Error 524 - A timeout occurred

**Comment by ilike2burnthing** [comment]
aaaand back up

**Comment by ilike2burnthing** [comment]
https://btdb.eu/ - Doing some maintenance

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://btdb.eu/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://btdb.eu/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://btdb.eu/ - Error 504 - Gateway time-out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://btdb.eu/ - Error 504 - Gateway time-out

**Comment by garfield69** [comment]
v0.18.502
