### ISSUE TITLE
[req]: vault network

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#15641]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Vault network 
- URL: https://vault-network.net/
- Description: Vault network is a Private tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 24h or 1.0
- Additional Comments: let me know who to send invite to
```
Engine:  TS Special Edition v.8.0
Registration: Invite only
torrent list default is 20, max 40
thankyou before download

**Comment by garfield69** [comment]
Please send invite to `garfieldsixtynine [at] gmail [dot] com` thanks.

**Comment by swannie-eire** [comment]
Invite sent

**Comment by garfield69** [comment]
I registered and am pending confirmation. But its been an hour and there is nothing in my gmail inbox or spam box.
I've had a handful of sites that did not like gmail so I'll wait out the 48 hours until expiry, and then if nothing has changed, we can retry and I'll use my proton email instead.
Or you may wish to follow up with admin instead, user: `garfield1969` email: `garfieldsixtynine@gmail.com`

**Comment by swannie-eire** [comment]
Staff said your account has been confirmed.

@garfield69

**Comment by garfield69** [comment]
Excellent. I can now login and start work.

**Comment by garfield69** [comment]
v0.22.772
