### ISSUE TITLE
[req]: HDZero

### ISSUE THREAD

**Issue by LynkOne** [Jackett/Jackett#15659]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: HDZero
- URL: https://hdzero.org/
- Description: HD Zero is a SPANISH Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 5 Days or 1:1 Ratio
- Additional Comments: UNIT3D 8.2.0
- Registration: Invitation only

Suggested category mapping (id 6 may be Movies instead of TV/Anime):
caps:
  categorymappings:
    - {id: 1, cat: Movies, desc: "Películas"}
    - {id: 2, cat: TV, desc: "Series"}
    - {id: 5, cat: TV, desc: "Series Emision"}
    - {id: 6, cat: TV/Anime, desc: "Animacion Peliculas"}
    - {id: 7, cat: TV/Anime, desc: "Animacion Series"}
    - {id: 8, cat: TV/Anime, desc: "Anime Peliculas"}
    - {id: 9, cat: TV/Anime, desc: "Anime Series"}
    - {id: 10, cat: TV/Documentary, desc: "Documentales"}
    - {id: 11, cat: TV/Documentary, desc: "Documentales Series"}
    - {id: 12, cat: TV, desc: "Programas TV"}
    - {id: 13, cat: TV, desc: "Telenovelas"}
    - {id: 3, cat: Other, desc: "Delete"}
```

**Comment by garfield69** [comment]
v0.22.817

**Comment by garfield69** [comment]
@LynkOne  one thing I forgot to ask you to check, which is the time zone.
Can you access the HDZero with a browser and view the torrent page, find the most recent upload
Then use Jackett to search that title and check that the time reported is similar to the one on the web site.
Let me know what you find. Thanks.

**Comment by LynkOne** [comment]
Jackett results:
0m ago HD Zero (API) Blade Runner (1982) BDFull 1080p AVC DD 5.1-HDZ
SPANiSH IMDB TMDB NO UPLOAD 26.94 GB 107 Movies 0 1 0 1 0
0m ago HD Zero (API) Blade Runner (El corte final) (1982) UHDFull 2160p
HDR10 HEVC DD 5.1-HDZ SPANiSH IMDB TMDB NO UPLOAD 55.71 GB 400 Movies 0 1 0
1 0
14d ago HD Zero (API) Blade Runner 2049 (2017) UHDFull 2160p HDR10 DTS-HD
MA 5.1 HEVC-HDZ SPANiSH IMDB TMDB NO UPLOAD 78.63 GB 818 Movies 1 2 0 1 0
14d ago HD Zero (API) Blade Runner 2049 (2017) BDFull 1080p DTS-HD 5.1
AVC-HDZ SPANiSH IMDB TMDB NO UPLOAD 43.01 GB 955 Movies 0 1 0 1 0

Tracker Results:
22min ago
26min ago
2 weeks ago
2 weeks ago
