### ISSUE TITLE
[req]: SceneNZBs

### ISSUE THREAD

**Issue by Bensonheimer992** [Jackett/Jackett#15658]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: SceneNZBs
- URL: scenenzbs.com
- Description: 
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments:
```

**Comment by garfield69** [comment]
Jackett supports only .torrent or magnet trackers. Usenet (Newznab) sites are not supported.
See https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
You may wish to get SceneNZBs added to Prowlarr, see https://github.com/Prowlarr/Prowlarr?tab=readme-ov-file#indexers--trackers
