### ISSUE TITLE
[hhanclub] (updating) Login failed: No form found on https://hhanclub.top/login.php using form selector form[action="takelogin.php"]

### ISSUE THREAD

**Issue by nasssssss2363** [Jackett/Jackett#15655]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://172.17.0.1:8191/
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.22.806-ls561)
File /etc/issue: Welcome to Alpine Linux 3.20
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.1.35.0 (64bit OS) (64bit process)
Environment version: 8.0.10 (/app/Jackett/)
Starting Jackett v0.22.806
```

### Description

none

### Logged Error Messages

```text
none
```

**Comment by garfield69** [comment]
Given that hhanclub's login page does indeed have a form[action="takelogin.php"] selector, it appears that your jackett is being blocked from accessing it.
See https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-no-form-found-on-url and if you cannot solve the issue for yourself then provide a full **enhanced log**. Perhaps the debug and HTML in the enhanced log will provide the clue to your issue. 
See https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by nasssssss2363** [comment]
> Given that hhanclub's login page does indeed have a form[action="takelogin.php"] selector, it appears that your jackett is being blocked from accessing it. See https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-no-form-found-on-url and if you cannot solve the issue for yourself then provide a full **enhanced log**. Perhaps the debug and HTML in the enhanced log will provide the clue to your issue. See https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

It seems to be caused by me using a proxy, I canceled it and it's fine, thanks for your help!
