### ISSUE TITLE
[REQ] Add Downloadville tracker

### ISSUE THREAD

**Issue by skrew** [Jackett/Jackett#1565]
Please add [http://downloadville.net](http://downloadville.net)

This tracker will be invite only soon and it's in free leech mode until 22 July, so it's time for adding and testing it easily.

Thanks.

**Comment by nikogaug** [comment]
Here is the definitions:
`- {id: 2030, cat: Movies/SD, desc: "DVDRIP"}
- {id: 2000, cat: Movies, desc: "MKV"}
- {id: 2040, cat: Movies/HD, desc: "HD"}
- {id: 2040, cat: Movies/HD, desc: "4K"}
- {id: 18, cat: Movies/SD, desc: "3D"}
- {id: 2000, cat: Movies, desc: "MP4"}
- {id: 2030, cat: Movies/SD, desc: "MPG"}
- {id: 2060, cat: Movies/BluRay, desc: "ISO"}
- {id: 3010, cat: Audio/MP3, desc: "MP3"}
- {id: 3040, cat: Audio/Lossless, desc: "FLAC"}
- {id: 3999, cat: Audio/Other, desc: "Karaoké"}
- {id: 5000, cat:TV , desc: "Série TV en français"}
- {id: 5000, cat:TV , desc: "Série TV en anglais"}
- {id: 5000, cat:TV , desc: "Série TV Québécoise"}
- {id: 1000, cat: Console, desc: "Console"}
- {id: 4050, cat: PC/Games, desc: "PC"}
- {id: 4070, cat: PC/Phone-Android, desc: "Android"}
- {id: 4000, cat: PC, desc: "Windows"}
- {id: 4030, cat: PC/Mac, desc: "Mac"}
- {id: 4000, cat: PC, desc: "Linux"}
- {id: 4070, cat: PC/Phone-Android, desc: "Android"}
- {id: 7000, cat: Books, desc: "ePub"}
- {id: 7000, cat: Books, desc: "PDF"}
- {id: 7000, cat: Books, desc: "Autres formats"}
- {id: 0010, cat: Other/Misc, desc: "Inclassables"}`

Is it in the good format ?

**Comment by nikogaug** [comment]
Header and login( not sure for that) :
`Header`
``
`  site: downloadville`
`  name: DownloadVille`
`  language: fr-fr`
`  type: private # public for now (new tracker)`
`  encoding: UTF-8`
`  links: # List of known domains (the first one is the default, should end with /)`
`    - http://downloadville.net`
`  certificates: # None`
`  `
`    `
`  modes:`
`search: [q]`
`tv-search: [q]`
`movie-search: [q]`
``
`settings:`
`    - name: uid # internal variable`
`      type: text # input type`
`      label: Utilisateur # Display name`
`    - name: pwd`
`      type: password`
`      label: Mot de passe`
`  `
`  Login :`
`  method: post # use simple post login`
`    path: tracker/index.php?page=login # target of the POST request`
`    inputs: # list of POST parameters`
`      username: "{{ .Config.username }}" # use configured username from the settings`
`      password: "{{ .Config.password }}" # use configured username from the settings`

**Comment by skrew** [comment]
I have to learn how to make (or at least how to fix) definitions !

BTW thanks @nikogaug

**Comment by nikogaug** [comment]
You're welcome.
You have all informations here: [https://github.com/Jackett/Jackett/wiki/Definition-format](https://github.com/Jackett/Jackett/wiki/Definition-format) at Caps section for the definitions.

**Comment by garfield69** [comment]
Jackett team, I just have this last part of the coding for the definition of Downloadville.net to do.    
I could use a hand figuring out how what is required for the thanks.php for this site.    
here is the relevant html section from the torrent-details page:    
```html
<tr>
 <td align="right" class="header" valign="top">Remerciements</td>
 <td class="lista" align="center">
  <div id="thanks_div" name="thanks_div" style="display:block;"><span id="result"></span></span></div>
  <form action="thanks.php" method="post" onsubmit="return false">
   <div id="thanks_div" name="thanks_div" style="display:block;"></div>
   <div id="loading" name="loading" style="display:none;"><img src="images/ajax-loader.gif" alt="" title="ajax-loader" /></div>
   <input type="image" src='images/saythankyou.png' id="ty" value="Dire merci!" onclick="thank_you('81e86cdb25224a191bf72528c1f2c342a585f3a3')" /><br>
   <font color = "blue" size="2"><b>Ne pas oublier de remercier l'Uploadeur...nombres de merci jusqu'à maintenant : <font color="red"><b>3</b></font></b>
   </td>
   </tr>
  </form>
  <script type="text/javascript">ShowThank('81e86cdb25224a191bf72528c1f2c342a585f3a3');</script>
 </td>
</tr>
```
and this is the definition download section I've got so far:    
```yaml
  download:
    before:
      path: "thanks.php"
      method: "post"
#      inputs:
#        infohash: "{{ .DownloadUri.Query.id }}"
    selector: a[href^="download.php?id="]
```
so how do I simulate clicking in the image so that the onclick thank_you() is called?

**Comment by kaso17** [comment]
From the html code it's not clear what's happening, apparently the ShowThank() javascript method is doing something. I suggest you have a look at the browser developer tools/network tab to see which parameters are sent to the server when clicking the thanks button.

**Comment by garfield69** [comment]
found the relevant script section:
```html
    <div align="center" class="b-content"><script type="text/javascript">
function ShowHide(id,id1) {
    obj = document.getElementsByTagName("div");
    if (obj[id].style.display == 'block'){
     obj[id].style.display = 'none';
     obj[id1].style.display = 'block';
    }
    else {
     obj[id].style.display = 'block';
     obj[id1].style.display = 'none';
    }
}

function windowunder(link)
{
  window.opener.document.location=link;
  window.close();
}


function disable_button(state)
{
 document.getElementById('ty').disabled=(state=='1'?true:false);
}

at=new sack();

function ShowUpdate()
{
  var mytext=at.response + '';
  var myout=mytext.split('|');
  document.getElementById('thanks_div').style.display='block';
  document.getElementById('loading').style.display='none';
  document.getElementById('thanks_div').innerHTML = myout[0]; //at.response;
  disable_button(myout[1]);
}

function thank_you(ia)
{
  disable_button('1');
  at.resetData();
  at.onLoading=show_wait;
  at.requestFile='thanks.php';
  at.setVar('infohash', ia);
  // at.setVar('infohash',"'"+ia+"'");
  at.setVar('thanks',1);
  at.onCompletion = ShowUpdate;
  at.runAJAX();
}

function ShowThank(ia)
{
  at.resetData();
  at.onLoading=show_wait;
  at.requestFile='thanks.php';
  at.setVar('infohash', ia);
  // at.setVar('infohash',"'"+ia+"'");
  at.onCompletion = ShowUpdate;
  at.runAJAX();
}

function show_wait()
{
  document.getElementById('thanks_div').style.display='none';
  document.getElementById('loading').style.display='block';
}

</script>
```

**Comment by kaso17** [comment]
Try
```
  download:
    before:
      path: "thanks.php"
      method: "post"
      inputs:
        infohash: "{{ .DownloadUri.Query.id }}"
        thanks: "1"
        rndval: "1487013827343"
    selector: a[href^="download.php?id="]
```

**Comment by kaso17** [comment]
It looks like the same tracker source as arabafenice/passionetorrent. Looking at that these definitions might help.

**Comment by kaso17** [comment]
@vlsoft @Celedhrim do you know if this tracker is dead?

**Comment by nikogaug** [comment]
I think this tracker is not dead. I use it for 6-9 months. And it is offline since 4 days. Perhaps a little bug.

**Comment by Celedhrim** [comment]
Hello , 

seeems their is an issue with the domain , then servers , should wait some more days I think :)

**Comment by garfield69** [comment]
@Celedhrim I been getting ERR_NAME_RESOLUTION_FAILED for https://downloadville.net/ for a week now.
do you happen to know if they have changed domain or shut down?
perhaps it's similar to their june 2018 issue and I should just wait a bit longer before deleting the indexer.

**Comment by Celedhrim** [comment]
Hi @garfield69 !

I don't know what happen , I think we could wait one more week.
During this week I saw that downloadville was down in jackett / radarr / sonarr but I was able to get the website with my web browser.
I was busy this week and couldn't dig more sorry :(

**Comment by garfield69** [comment]
Hah! the site is back up and running now. :-)

**Comment by garfield69** [comment]
here we go again. https://downloadville.net/ returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
now https://downloadville.net/ is returning
```
Forbidden
You don't have permission to access / on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by Celedhrim** [comment]
now it's an auto index https://downloadville.net/

With 2 directories and they have the date of :  2019-05-09 19:57 and 2019-05-09 20:50

Smells like a server migration

**Comment by garfield69** [comment]
appears to be back now.

**Comment by garfield69** [comment]
https://downloadville.net/ returning ERR_CONNECTION_TIMED_OUT

**Comment by pipopop** [comment]
Sit offline since few days.
I will post more information when I have more informations.

**Comment by GuiroSat** [comment]
Hello,
I have an error with this tracker

`Found no results while trying to browse this tracker (Test)`

Thanks

**Comment by garfield69** [comment]
@GuiroSat  refer and follow #7514 for updates regarding your issue.

**Comment by garfield69** [comment]
https://downloadville.net/ returning ERR_CONNECTION_TIMED_OUT
refer #9538

**Comment by hchris6116** [comment]
Stop

**Comment by garfield69** [comment]
stop?

**Comment by pipopop** [comment]
The tracker is definitely dead. I post a issue for that : [https://github.com/Jackett/Jackett/issues/9538#issuecomment-693629465](url). I don't know witch procedure is the best. Create a new issue for that ? add a comment for the last issue of this tracket ? or add a comment at the issue created for the request add of this tracker ?

Btw, thanks for your work.

**Comment by garfield69** [comment]
removed with Jackett 0.16.1231
