### ISSUE TITLE
Torrentflix

### ISSUE THREAD

**Issue by thedragon40** [Jackett/Jackett#15656]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Torrentflix
- URL: https://www.torrenflix.com/
- Description: It is a website for Spanish torrents.
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments: I don't know if it can be added, but I would like it if it could.
```

**Comment by garfield69** [comment]
As with most of these Spanish sites, torrentflix is set up with a one poster many torrents layout, which is not suitable for processing by yaml, and would need a custom C# indexer to be written.
https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
The reality is that nobody has recently volunteered to code a C# indexer so this is unlikely to ever be completed.
