### ISSUE TITLE
[req]: CineClassics

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#15664]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: CineClassics
- URL: https://cineclassics.org/
- Description: CineClassics is a Private Torrent Tracker for MOVIES pre 2015
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): qualified sharing rate, see Rules Ratio section.
- Additional Comments: no account inactivity rules found despite rule 1.4 which leads to a page not found.
- Engine: GazellePW
- Registration open ATM
Similar to GPW

**Comment by garfield69** [comment]
Golden Rules:
2.4. Public disclosure of site information is prohibited
Do not disclose the site name and abbreviation " CineClassics.org ", server address and tracker address in any public area. Please cover the site logo when taking screenshots.
5.2. Prohibition of abuse of automated access to the Website
All automated site access must be done through the specified [API](https://github.com/WhatCD/Gazelle/wiki/JSON-API-Documentation) . The API will only respond to 5 requests in 10 seconds. Scripts and other automated processes may not scrape the HTML pages of the site. If in doubt, consult an administrator.

You've already broken rule 2.4 ;-0

Site requires we code an indexer with C# via the GazelleTracker.cs abstract.

**Comment by garfield69** [comment]
Looks very similar to GPW, so I'm going to try using that indexer as a template.

**Comment by garfield69** [comment]
v0.22.825

**Comment by garfield69** [comment]
https://cineclassics.org/ > ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.22.1150
