### ISSUE TITLE
Is there anyway to manually view seasons on sonarr using jackett?

### ISSUE THREAD

**Issue by jonesb63** [Jackett/Jackett#1566]
Just wondering if there are anyway to view full seasons of a show when attempting to do a manual search from sonarr using jackett? If not, this would be a great feature.  For example, for BTN when you search any episode, the full season packs appear as well.

**Comment by chibidev** [comment]
@jonesb63 although I'm not an expert on the Newznab specification, however I think it is up to Sonarr to handle this. Jackett supports searching for whole seasons, you just have to leave the episode query parameter unspecified.
@kaso17 and @flightlevel If you can, weigh in.

**Comment by flightlevel** [comment]
@chibidev comments are correct. Jackett does support searching for a season and you can try this via manual search in Jackett
Jackett is just an API that other programs consume eg Sonarr 
We don't control what they search for, so this be more a question for Sonarr 

Might be something useful in here https://forums.sonarr.tv/search?q=season
Will say that from Sonnarr point of view season searching just wouldn't be as straight forward as single episodes eg. I want episodes 10 to 20, with torrents, you've really got to download the whole season pack to get just 10 through 20 etc more complex ...
