### ISSUE TITLE
[AvistaZ] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#15670]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

The AvistaZ site is offline

### Logged Error Messages

- https://avistaz.to/ cloudflare 524
- cloudflare Bad gateway Error code 502

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://avistaz.to/ cloudflare Bad gateway Error code 502
they have also turned on cloudflare challenge so the site may be under a DDoS attack.

**Comment by felipemarinho97** [comment]
The website is online for me but this API is down -> https://avistaz.to/api/v1/jackett/torrents?in=1&type=0&limit=50&search=&discount[]=1

I see the same error as described in [#1027](https://github.com/FlareSolverr/FlareSolverr/issues/1027)
