### ISSUE TITLE
[request] Add hd-bits.ro

### ISSUE THREAD

**Issue by that1guy** [Jackett/Jackett#1567]
Would love to see http://hd-bits.ro/ on here.  Happy to pass along invite if needed.

**Comment by garfield69** [comment]
getting ERR_CONNECTION_TIMED_OUT     
Anyone know if this site still active or moved on to another domain?      
Otherwise this ticket can be closed.

**Comment by garfield69** [comment]
https://opentrackers.org/hd-bits-ro-has-shut-down/
