### ISSUE TITLE
[req]: Manual update trigger available from command line or through http POST.

### ISSUE THREAD

**Issue by tuhajbej6** [Jackett/Jackett#15695]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Installed as a plugin for KODI on Libreelec it working great (using Mono), except auto-updater. The checkbox does noting, and update has to be done frequently by button.

### Describe the solution you'd like

1. Calling that updater trigger from simple command.
2. auto creating cron entry for jackett updater.

**Comment by garfield69** [comment]
>The checkbox does noting, 

which checkbox are you talking about, is it one on the Jackett dashboard? 

>and update has to be done frequently by button.

are you referring to the check-for-updates button on the Jackett dashboard?

We are not responsible for 3rd party port of Jackett, which include plugins for kodi.

This GitHub repo supports all the binaries that are part on the packages listed under the **assets** list on https://github.com/Jackett/Jackett/releases/latest

For those packages, the auto-update runs daily and the check-for-update button works.

If your kodi plugin is not auto-updating, its possible that they have disabled auto-updates via the --Noupdates for what ever reason. 
Odds are good that kicking off a cron task to run the update may not work for the same reason that the plugin does not allow the auto-updates, who knows why.

Do not think we can help with this one.

**Comment by tuhajbej6** [comment]
Yes I am all asking about auto update called from GUI. The Update button
works, the checkboc does not. How the hell this Function is can be disabled
inside jackett - I assume the command which would be called has been
purposfully removed for the kodi plugin.

Basically I would like to trace that command that is executed after
pressing Update button. Is it a shell command with args ? What is happening
then?

pt., 8 lis 2024, 06:19 użytkownik garfield69 ***@***.***>
napisał:

**Comment by garfield69** [comment]
When the check-for-updates button is press the dashboard does a POST http://127.0.0.1:9117/api/v2.0/server/update

**Comment by garfield69** [comment]
BTW that address is what my windows Jackett is using, your address would be whatever your kodi plugin uses, as shown in the localBindAddress on the Jackett dashboard.

**Comment by tuhajbej6** [comment]
Yes this is much closer to what I look for, I can see this in logs it is
being called, except that
calling it by curl does nothing, like this:

curl -X POST "http://localhost:7700/api/v2.0/server/update"

Are there no additional parameters ?



pt., 8 lis 2024 o 08:36 garfield69 ***@***.***> napisał(a):

**Comment by garfield69** [comment]
>Are there no additional parameters ?

I don't think so. The index.html has the button which calls the api JS via api.updateServer, and the api JS does a 
`return $.post(this.getApiPath("server", "update"), callback);`

**Comment by tuhajbej6** [comment]
That is right, and calling http:.//../server/config does show some json
config.
So calling the self-update from the button - despite the info that POST
arent supported, does in fact all the update.


Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Info Request
starting HTTP/1.1 POST http://10.9.8.1:7700/api/v2.0/server/update - - 0
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug Request is
continuing in applying rules. Current url is
http://10.9.8.1:7700/api/v2.0/server/update
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug Request is
continuing in applying rules. Current url is
http://10.9.8.1:7700/api/v2.0/server/update
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug Request is
continuing in applying rules. Current url is
http://10.9.8.1:7700/api/v2.0/server/update
*Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug POST
requests are not supported*
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug
AuthenticationScheme: Cookies was successfully authenticated.
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug 1
candidate(s) found for the request path '/api/v2.0/server/update'
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug Endpoint
'Jackett.Server.Controllers.ServerConfigurationController.Update (jackett)'
with route pattern 'api/v2.0/server/Update' is valid for the request path
'/api/v2.0/server/update'
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug Request
matched endpoint
'Jackett.Server.Controllers.ServerConfigurationController.Update (jackett)'
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Info Executing
endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Update
(jackett)'
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Info Route
matched with {action = "Update", controller = "ServerConfiguration"}.
Executing controller action with signature Void Update() on controller
Jackett.Server.Controllers.ServerConfigurationController (jackett).
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug Execution
plan of authorization filters (in the following order):
Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug Execution
plan of resource filters (in the following order): None
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug Execution
plan of action filters (in the following order):
Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order:
-2147483648),
Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order:
-3000), Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter
(Order: -2000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug Execution
plan of exception filters (in the following order): None
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug Execution
plan of result filters (in the following order):
Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order:
-2000)
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug
Authorization was successful.
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug Executing
controller factory for controller
Jackett.Server.Controllers.ServerConfigurationController (jackett)
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug Executed
controller factory for controller
Jackett.Server.Controllers.ServerConfigurationController (jackett)
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Info Executed
action Jackett.Server.Controllers.ServerConfigurationController.Update
(jackett) in 2.4168ms
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Info Executed
endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Update
(jackett)'
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Debug Connection
id "0HN81RPC3DA8N" completed keep alive response.
Nov 11 00:22:15 kodi service.jackett[302]: 11-11 00:22:15 Info Request
finished HTTP/1.1 POST http://10.9.8.1:7700/api/v2.0/server/update - 200 0
- 23.7078ms



pt., 8 lis 2024 o 18:01 garfield69 ***@***.***> napisał(a):

**Comment by tuhajbej6** [comment]
OK I got some more awareness regarding using such http POSTs.
Finally I got some reaction after providing an api-key and enconding
header. Along with this also some authorization is required. when calling
using button this mechanism uses browser cookie authorization. Maybe I am
doing something wrong or maybe there is way other than cookie to authorize
this POST request. But at least I get all the reaction for my command:

*# curl -X POST "http://localhost:7700/api/v2.0/server/update
<http://localhost:7700/api/v2.0/server/update>" -H "Authorization: Bearer
ngxlc6x3865jnfv4h5du2oefmqbejt7v" -H "Accept-Encoding: gzip, deflate" -H
"Cookie:
CfDJ8BVbyJlUnVxHoq7SLmzrDMeVzWvimTihgCWTLRB3rhdecKnDntxKRP0XNeF8eQFW07dkWdlfC7h7lmrzWD-PRIUoPkg5dPvErXLUU-enjf0LfDf2QqLq0ogsj3Yl2vc695TzfuFUEI-6XE_kbqBhd_Ok10LfA3Tey1r7uhbgmzwkoSWyacloCoyBsALY8AHrAp0xZ-YNOaSwcBbcP-pMMjOAaYhhfiQbqVxFvbZ_DF493RmKw9i0KQGUUPVb3D_4QVUKSC1pPU4bacnJoJv1hnp1_3nIA9KpCeoQ65bYRL34WfGJJo80mYUZkgWs5z9yA1SbVV6Xx1nmNN0FpqoGaNU"
*

and the jacket says that I falied the authorization. Can anyone tell how to
authorize ?


Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Info Request
starting HTTP/1.1 POST http://localhost:7700/api/v2.0/server/update - - -
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug Request is
continuing in applying rules. Current url is
http://localhost:7700/api/v2.0/server/update
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug Request is
continuing in applying rules. Current url is
http://localhost:7700/api/v2.0/server/update
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug Request is
continuing in applying rules. Current url is
http://localhost:7700/api/v2.0/server/update
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug POST
requests are not supported
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug
AuthenticationScheme: Cookies was not authenticated.
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug 1
candidate(s) found for the request path '/api/v2.0/server/update'
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug Endpoint
'Jackett.Server.Controllers.ServerConfigurationController.Update (jackett)'
with route pattern 'api/v2.0/server/Update' is valid for the request path
'/api/v2.0/server/update'
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug Execution
plan of authorization filters (in the following order):
Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Info
Authorization failed. These requirements were not met:
Nov 11 01:17:04 kodi service.jackett[302]:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.




pon., 11 lis 2024 o 00:37 Jan Słupczewski ***@***.***> napisał(a):

**Comment by tuhajbej6** [comment]
Finally I got some reaction after providing an api-key and enconding
header. Along with this also some authorization is required. when calling
using button this mechanism uses browser cookie authorization. Maybe I am
doing something wrong or maybe there is way other than cookie to authorize
this POST request. But at least I get all the reaction for my command:

```
# curl -X POST "http://localhost:7700/api/v2.0/server/update
<http://localhost:7700/api/v2.0/server/update>" -H "Authorization: Bearer
ngxlc6x3865jnfv4h5du2oefmqbejt7v" -H "Accept-Encoding: gzip, deflate" -H
"Cookie:
CfDJ8BVbyJlUnVxHoq7SLmzrDMeVzWvimTihgCWTLRB3rhdecKnDntxKRP0XNeF8eQFW07dkWdlfC7h7lmrzWD-PRIUoPkg5dPvErXLUU-enjf0LfDf2QqLq0ogsj3Yl2vc695TzfuFUEI-6XE_kbqBhd_Ok10LfA3Tey1r7uhbgmzwkoSWyacloCoyBsALY8AHrAp0xZ-YNOaSwcBbcP-pMMjOAaYhhfiQbqVxFvbZ_DF493RmKw9i0KQGUUPVb3D_4QVUKSC1pPU4bacnJoJv1hnp1_3nIA9KpCeoQ65bYRL34WfGJJo80mYUZkgWs5z9yA1SbVV6Xx1nmNN0FpqoGaNU"
```

and jackett says that I falied the authorization. Can anyone tell how to authorize ?


```
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Info Request
starting HTTP/1.1 POST http://localhost:7700/api/v2.0/server/update - - -
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug Request is
continuing in applying rules. Current url is
http://localhost:7700/api/v2.0/server/update
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug Request is
continuing in applying rules. Current url is
http://localhost:7700/api/v2.0/server/update
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug Request is
continuing in applying rules. Current url is
http://localhost:7700/api/v2.0/server/update
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug POST
requests are not supported
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug
AuthenticationScheme: Cookies was not authenticated.
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug 1
candidate(s) found for the request path '/api/v2.0/server/update'
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug Endpoint
'Jackett.Server.Controllers.ServerConfigurationController.Update (jackett)'
with route pattern 'api/v2.0/server/Update' is valid for the request path
'/api/v2.0/server/update'
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Debug Execution
plan of authorization filters (in the following order):
Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Nov 11 01:17:04 kodi service.jackett[302]: 11-11 01:17:04 Info
Authorization failed. These requirements were not met:
Nov 11 01:17:04 kodi service.jackett[302]:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.

```

**Comment by garfield69** [comment]
There is no username that I am aware of, and the only password is the admin password on the dashboard, which by default is not enabled unless to used the dashboard to set one up.
As for the cookie, if I use my browser to access my Jackett dashboard and navigate to the manage-on-device site data, and delete my cookies, then after a reload I se ethat the Jackett cookie is set to expire two weeks later.

As for all these other questions, you are straying into C# developer territory, and outside the area of my expertise. I did not write the app or maintain the apps core facilities, I just support the yaml indexers and dabble in some simple C# coding for the C# indexers.

**Comment by ilike2burnthing** [comment]
```bash
curl -c ./cookie.txt "http://localhost:9117/UI/Dashboard" -d "password=password"
curl -X POST -b ./cookie.txt "http://localhost:9117/api/v2.0/server/update"
```

That's probably doable in a single line, but I'm just testing quickly in Windows Sandbox. 

That resolve your issue?

**Comment by tuhajbej6** [comment]
Hi, after a month it occurs that cookie is necessary, but it is still
accepted so such cookie period is quite tolerable.
The API key is naturally expected, so the correct version I use is
following:

curl -X POST "http://localhost:7700/api/v2.0/server/update" -H
"Authorization: Bearer <api-key-without-braces>" -H "Accept-Encoding: gzip,
deflate" -H "Cookie: Jackett=<cookie-without-braces"

cheers!



śr., 11 gru 2024 o 09:43 ilike2burnthing ***@***.***>
napisał(a):
