### ISSUE TITLE
Public & Semi-Private Trackers on new branch

### ISSUE THREAD

**Issue by JigSawFr** [Jackett/Jackett#157]
**Hello**,
I know that a recent decision from Jackett team removed all public trackers for some obscur reasons.
But, deleting all public trackers is not the good decision.
Some of them are public with content not verified or with craps inside. (TPB)
Others are very popular with content verified, validated for downloading purpose and are a reference in a country (T411).

So, as Sonarr/Sickrage/Couchpotato support public trackers, i don't understand why Jackett don't want to support them too.

**For what obscure reasons ?**
- Craps torrents ?
- Public content ?
- RIAA or Hollywood targeted ?

**So it's risky for end users ?** Yes it is, but it's to end user to take responsability for what they are doing. Network provider are not taking down torrent protocol for example to prevent users downloading or to be harmed / scammed. It's the liberty to choose what they want. It's risky too to download on bitorrent, registring on private trackers, ...

If users are capable of installing Jackett, they are capable of understand what risks they will have if they uses public trackers. The main aim of Jackett for me is to centralize providers for all apps as Sonarr / Couchpotato and others. So all configured in one place. (*If you start removing providers, ... it will not complete only my goal, but goal's of many users*)

In final what i suggest is to reintegrate public providers, but if you want in another branch named "public", so master will remain with private trackers only, but you can let end users to choose public branch to have all providers. Or to integrate an option setting (with warning), to enable public trackers.

**Why** i created this ? Because i prefer to participate in one project, and not dividing contributors among many forks. Please consider this point of view seriously, it's not an attack at all, but just a suggestion to find a compromise.

Thanks you

**Comment by JigSawFr** [comment]
Poke @flightlevel @Azerelat @raspdealer @maxcore

**For what main reason i opened this ?** Because for French, T411 is the reference of french content, it's semi private (required registration), but serious, content is verified and validated before users can download them for example, you need to respect strict rules.

**Comment by raspdealer** [comment]
Agree with your point of view.
Reintegrate all publics trackers disabled by default with a checkbox : Activate public trackers.
I'm convinced that unity is the best way to support community!

**Comment by maxcore** [comment]
@JigSawFr  @raspdealer  the same way for me too , i have exactly the same point view . T411 is the reference for French community i am register Date d'enregistrement:2007-03-15 (Il y a 8 ans) .

**Comment by Azerelat** [comment]
Would it be acceptable if we make an exception for T411? I would like a proper RSS implementation rather than just search which is available before its merged back in mind you.

**Comment by JigSawFr** [comment]
@Azerelat in short term yes, i will be satisfied with an exception for t411. But i think for all other users in long term. 

Okay so, why do you prefer a proper RSS implementation ? I don't know why it's the best way for you as T411 has an API available. And if you can explain it, it could be great for me to understand for all providers (to improve mine, as i don't use any RSS). I prefered to scrape tracker as we can do a search, with RSS we can't search for a release, or many informations are missing.

And finally, can you explain your point of view about public trackers or team point of view, the real not a link to a three words evasive post as i can saw somewhere here. Thanks you !

Ps: Do you actively search contributors for your Jackett team and github mainteners users ?

**Comment by twistedroutes** [comment]
I (who doesn't have a vote here but....) would opt for the check-box option...or even release as a separate package (with checkbox option in main package to activate) ?

**Comment by duramato** [comment]
Or perhaps just as a launch option?

**Comment by Azerelat** [comment]
For all the above, pretty much all those points.  Apps consuming the api will already implement most public trackers anyway so I don't know why this is an issue other than t411.

I mean RSS as in being able to get the latest from the Jackett which isn't supplied by the api so the site would need to be scraped.

If you keep contributing as you are you're likely to be put up as a contributor should the rest of the team agree.  From my point of view i'd like to stop seeing features implemented at the indexer level.

**Comment by vdbxavier** [comment]
what is the last release with t411 please ?

**Comment by vdbxavier** [comment]
it's time to fork a french jackett ?

**Comment by vdbxavier** [comment]
+1 for parameter / check box opt

**Comment by raspdealer** [comment]
0.6.45.0

**Comment by PartTimeLegend** [comment]
+1

**Comment by blablanumerodeux** [comment]
+1

**Comment by PartTimeLegend** [comment]
@JigSawFr you appear to be the main person around here, the project doesn't show the developer team, so if I am mistaken my apologies.

Can we get an update from you (or whoever the developer is) on the status of this request? I know there are other forks that retain the public trackers. As products like Sonarr don't contain these trackers, some of us relied on the ability to use them.

**Comment by JigSawFr** [comment]
This request is on my todo list, but as i'm in intership for my studies, i' dont have enough time to do it now. I will start seriously around end of february ;)

**Comment by PartTimeLegend** [comment]
@JigSawFr are you not able to simply rip the modules from the original project and import them? Like revert the commit and then ff your changes atop?

**Comment by raspdealer** [comment]
@PartTimeLegend The idea is to be able to turn on/off public tracker with a warning.

**Comment by JigSawFr** [comment]
Yes, it's the condition from Jackett Team

**Comment by Azerelat** [comment]
T411 will be re-added probably as an exception sooner rather than later when there is a fully functioning indexer as the old one didn't work fully.

We don't deal with public trackers, if they are popular enough they'll already be implemented outside Jackett.
