### ISSUE TITLE
[req]:  BT之家

### ISSUE THREAD

**Issue by a799841185** [Jackett/Jackett#15708]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: BT之家lou站
- URL: https://www.1lou.me/
- Description:  BT movies tv 
-
```

**Comment by garfield69** [comment]
This site does not have magnet or .torrent links on site, but routes links to a 3rd party file service with its own set of pages and adverts and purchase options.
It is not suitable for indexing with Jackett.
See https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
