### ISSUE TITLE
M-Team search not returning correct results

### ISSUE THREAD

**Issue by qtv** [Jackett/Jackett#1570]
Jackett version: Jackett Version 0.7.1578.0

Search nearly anything in M-team and you won't get the results that the log has or the site search has. "Lego Batman", for example, turns up the movie on M-team and in the log but Jackett GUI only shows two things (which are dead), none of which are the movie.

I would love to post the log if I could removed all personal details, but I'm getting a lot of :
`System.Exception: Error while parsing field=title, selector=a[title][href^="details.php?id="], value=<null>: Selector "a[title][href^="details.php?id="]" didn't match <tr> <td class="rowfollow nowrap" valign="middle" style="padding: 0px">`

and

 `   at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__25.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:line 1279 
2017-07-17 03:12:08.7661 Error CardigannIndexer (mteamtp): Error while parsing row '<tr> <td class="rowfollow nowrap" valign="middle" style="padding: 0px"> `

**Comment by kaso17** [comment]
is this still a problem in the latest version, for me it's working fine (using manual search)

**Comment by drewbitt** [comment]
This is still an issue on 0.8.199.0. Any manual search does not come up with the correct results. "Wonder Woman" shows 4 releases when the site has 27, all non-dead.

**Comment by qtv** [comment]
This is still an issue on 0.8.199.0. Any manual search does not come up with the correct results. "Wonder Woman" shows 4 releases when the site has 27, all non-dead.

**Comment by kaso17** [comment]
Are you talking about the radarr/sonarr manual search or the jackett manual search?
Jackett mnaual search returns 30 Wonder Woman releases for me.
If you're talking about the radarr manual search: maybe you're missing some categories?

**Comment by qtv** [comment]
No, I mean the Jackett manual search, all categories. I do not know why I am getting different results than you. I have tried on multiple different Jackett versions, including complete deletion of Jackett and reinstalling. That's weird

**Comment by kaso17** [comment]
ok, I think this is related to the tooltip option in the UserCP/Tracker settings.
please try tuning tooltips "off" there.
I tried turning them on but I don't have any tooltips at all now (before it was the full release name).
Do you have IMDB tooltips for movie releases?

**Comment by qtv** [comment]
I can confirm that it Jackett search works without tooltips. It returns the correct amount of results.

Before I had median tooltips on which included Median IMDb Info (Picture + Title + Year + IMDb Rating + Runtime + Country + Language + Director + Genre + Main Cast + Plot Outline in English). It had been so long that I had forgotten that it didn't originally look like this, since I rely on IMDB reviews heavily.

**Comment by kaso17** [comment]
2e1ce6f2029e099e743b1234abb822d6e10e5403 adds support for imdb tooltips
Do the tooltips actually work for you? looking at your log I can't see any tooltip code for the torrent titles.

**Comment by qtv** [comment]
Tooltips work for me for showing the IDMB info on the search page, as well as runtime + cast etc but it doesn't have "plot outline in English" or a couple other things.
