### ISSUE TITLE
Missing language in hdf.world / HD-Forever results

### ISSUE THREAD

**Issue by hbooo** [Jackett/Jackett#1571]
Jackett Version 0.7.1581.0

Hello, 

I have a problem with the new tracker : hdf.world

The language isn't retrieved for the releases so there is no way to differentiate a release in french to another in english with subtitles.

![image](https://user-images.githubusercontent.com/242125/28266516-8be6ce3e-6af5-11e7-9322-436af7d42090.png)

First release have french audio, second release has french subtitles.

**Comment by kaso17** [comment]
I assume you mean the tags like "VFF / StFr / MULTI"? These are not available via the gazelle tracker API (https://hdf.world/ajax.php?action=browse&order_by=time&order_way=desc). If they add them to the API output we can add them in Jackett too. Please contact the site staff regarding this limitation.
