### ISSUE TITLE
[u2] (testing) Test search in U2 => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by AppleFrank** [Jackett/Jackett#15710]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-11-16 00:21:08	Info	Using HTTP Client: HttpWebClient2
2024-11-16 00:21:08	Info	Using FlareSolverr: No
2024-11-16 00:21:08	Info	Using proxy: Disabled
2024-11-16 00:21:08	Info	App config/log directory: /config/Jackett
2024-11-16 00:21:08	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-11-16 00:21:08	Info	Running in Docker: Yes (image build: v0.22.937-ls592)
2024-11-16 00:21:08	Info	File /etc/issue: Welcome to Alpine Linux 3.20
2024-11-16 00:21:08	Info	Jackett variant: CoreLinuxMuslAmdx64
2024-11-16 00:21:08	Info	OS version: Unix 6.8.0.48 (64bit OS) (64bit process)
2024-11-16 00:21:08	Info	Environment version: 8.0.11 (/app/Jackett/)
2024-11-16 00:21:05	Info	Starting Jackett v0.22.937
```

### Description

can not use u2, my cookie is right 

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in U2 => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
Click here to open an issue on GitHub for this indexer.
```

### Screenshots

![u2](https://github.com/user-attachments/assets/69040356-d326-449a-8fd6-b54626e57dd2)

**Comment by garfield69** [comment]
As none of the team have an account on U2 we cannot research independently, we will need your help to investigate.
Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by AppleFrank** [comment]
> As none of the team have an account on U2 we cannot research independently, we will need your help to investigate. Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue. See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

Many thanks mate, please find the attached log
[U2 log.txt](https://github.com/user-attachments/files/17779539/U2.log.txt)

**Comment by garfield69** [comment]
It appears that the download link is no longer available on the torrents.php page.

Can you confirm that this is not just a case of you having lost your download rights because you have exceeded your ratio or something, or been demoted or whatever?

If you access the details page of any title on the torrents page, is the download link available there?
If you find the download link, then assuming that it is still the same path I can just update the indexer to fetch it from the details page instead of looking for it on the torrents page.

IF you right click over the download link and select inspect, does the link look something like:
`<a title="Download torrent" href="download.php?id=123456"></a>` ?

**Comment by AppleFrank** [comment]
> It appears that the download link is no longer available on the torrents.php page.
> 
> Can you confirm that this is not just a case of you having lost your download rights because you have exceeded your ratio or something, or been demoted or whatever?
> 
> If you access the details page of any title on the torrents page, is the download link available there? If you find the download link, then assuming that it is still the same path I can just update the indexer to fetch it from the details page instead of looking for it on the torrents page.
> 
> IF you right click over the download link and select inspect, does the link look something like: `<a title="Download torrent" href="download.php?id=123456"></a>` ?

I confirm I do have the download right. There is no download button from the torrents.php page, I have to click the title go to torrent detail page and download torrent from there. The download link looks like: https://u2.dmhy.org/download.php?id=12345

**Comment by garfield69** [comment]
Great.
I will update the indexer for the download fetch from the details page, and update the selectors from the torrents page as date, size, seeders etc. are all offset back by 1 now the download column is gone.

**Comment by AppleFrank** [comment]
> Great. I will update the indexer for the download fetch from the details page, and update the selectors from the torrents page as date, size, seeders etc. are all offset back by 1 now the download column is gone.

Thank you so much for your time!

**Comment by garfield69** [comment]
v0.22.946
