### ISSUE TITLE
[1337x] (testing) Exception (1337x): A task was canceled.: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

### ISSUE THREAD

**Issue by jkmelvin** [Jackett/Jackett#15721]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
An error occurred while testing this indexer
Exception (1337x): A task was canceled.: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing
```

### Description

An error occurred while testing this indexer
Exception (1337x): A task was canceled.: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (1337x): A task was canceled.: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing
```

### Screenshots

An error occurred while testing this indexer
Exception (1337x): A task was canceled.: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/TroubleShooting/#a-task-was-cancelled
