### ISSUE TITLE
[req]: Any French Canadian (Québecois) Indexer available (public ideally) ?

### ISSUE THREAD

**Issue by levydanqc** [Jackett/Jackett#15726]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
I don't know any of them, but does anyone know if there are some ?
```

**Comment by garfield69** [comment]
there are then only public French indexers we have
![image](https://github.com/user-attachments/assets/6e4206fb-adbf-44c3-88a7-bddd7cbaa3cb)
and I doubt any of them are French-Canadian.
