### ISSUE TITLE
No results with search API

### ISSUE THREAD

**Issue by Ozzah** [Jackett/Jackett#1573]
Jackett version: 0.7.1533.0 on Windows 10

CouchPotato has not found any matches in many weeks. After further investigation:

http://localhost:9117/potato/iptorrents?imdbid=tt1628841&user=&passkey=xxx (the URL CouchPotato calls)
gives
`{
"results": [],
"total_results": 0
}`

Same story for http://localhost:9117/potato/ncore?imdbid=tt1628841&user=&passkey=xxx as well as all my other configured trackers.

However, if I log into the Jackett server in my browser and manually search against the tracker(s), I get plenty of results, as expected.

Here are the logs, although they don't really shed any light:

> Jul 18, 2017 06:06:06 PM | Info | Found 0 torrentpotato releases from nCore
> Jul 18, 2017 06:06:05 PM | Info | Found 0 torrentpotato releases from IPTorrents

and manually searching from the admin dashboard:

> 18, 2017 06:18:16 PM | Info | Manual search for "Independence Day Resurgence" on IPTorrents with 50 results.

**Comment by chibidev** [comment]
@Ozzah apparently Jackett did not enable searching for potato results with only an IMDB id. d90a261 should enable that, please give it a try

**Comment by Ozzah** [comment]
Thanks, this appears to have fixed the problem.
