### ISSUE TITLE
[seedpool] seedpool does not support searching by imdbid or tvdbid

### ISSUE THREAD

**Issue by groggy9788** [Jackett/Jackett#15733]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
11-27 23:59:22 Info Starting Jackett v0.0.0
11-27 23:59:22 Info Environment version: 8.0.1 (C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\)
11-27 23:59:22 Info OS version: Microsoft Windows NT 10.0.22631.0 (64bit OS) (64bit process)
11-27 23:59:22 Info Jackett variant: CoreWindows
11-27 23:59:22 Info Running in Docker: No
11-27 23:59:22 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
11-27 23:59:22 Info App config/log directory: C:\ProgramData\Jackett
11-27 23:59:22 Info Using proxy: Disabled
11-27 23:59:22 Info Using FlareSolverr: No
```

### Description

Seedpool does not support searching by TVDB id or IMDB id. If these options are provided, the API will return no results since they have not set up the integration with the downstream TVDB and IMDB APIs. These options have been disabled in the tracker UI, and Jackett (and Prowlarr) should no longer send them. 

I have confirmed with the site admins via IRC that imdb/tvdb searches will not be supported and should be removed from the jackett definitions. 

I have tested a fix for this locally, and will open it as a PR, but wanted to include an issue number if that PR is rejected for whatever reason. 

### Logged Error Messages

```text
There are no error messages in Jackett but the API call to seedpool will return no results if these values are included. If required, I can provide sample API responses, but they are just empty so seemed redundant.
```

### Screenshots

IMDB/TVDB are not options to search by in the tracker UI 
![image](https://github.com/user-attachments/assets/c1fd945f-851b-4e3f-813f-9ff383949e05)

**Comment by garfield69** [comment]
Go ahead and submit a PR, or if you prefer I can quickly implement this myself using this ticket as the justification. ;-)

**Comment by groggy9788** [comment]
> Go ahead and submit a PR, or if you prefer I can quickly implement this myself using this ticket as the justification. ;-)

I've opened a PR, but if it is not satisfactory, feel free to close and fix yourself. Wanted to try my hand at contributing since it seemed like a simple enough fix :)

**Comment by groggy9788** [comment]
Dang, that was speedy. Thanks so much @garfield69!

**Comment by garfield69** [comment]
Missed the Jackett release window, so the commit will be included in the next release due out in about 23 hours or so from now.

**Comment by groggy9788** [comment]
sounds great! I appreciate it

**Comment by garfield69** [comment]
v0.22.1018
