### ISSUE TITLE
`GLIBCXX_3.4.21' not found via Updater

### ISSUE THREAD

**Issue by MichealX64** [Jackett/Jackett#15732]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett v0.21.2015
RHEL 7.9
Unix 3.10.0.1160
libstdc++.x86_64                4.8.5-44.el7
Latest GLIBC: GLIBCXX_3.4.19
```

### Description

Hello, I attempted to update Jackett via the Updater and recieved a GLIBC error. I was wondering is this GLIBC dependancy a part of the Updater or Jackett itself? If it's limited to the Updater I'll go ahead and manually upgrade. Was just curious. Thanks!

### Logged Error Messages

```text
Nov 27 14:28:11 jackett[1026]: /tmp/JackettUpdate-v0.22.1012-638683432907754924/Jackett/JackettUpdater: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/JackettUpdate-v0.22.1012-638683432907754924/Jackett/JackettUpdater)
Nov 27 14:28:11 jackett[1026]: /tmp/JackettUpdate-v0.22.1012-638683432907754924/Jackett/JackettUpdater: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/JackettUpdate-v0.22.1012-638683432907754924/Jackett/JackettUpdater)
```

**Comment by garfield69** [comment]
This looks similar to #15492 which was on a QNAP system, does that apply to you?

**Comment by garfield69** [comment]
if you were on 0.21.2015 then that was running on .NET 6
and the 0.22.+ suite upgraded to .NET 8, so you may need to prep your platform to support .NET 8
after which a manual install of the current Jackett would be needed, and from then on the update should work.
