### ISSUE TITLE
YGGTorrent indexer doesn't work with Radarr

### ISSUE THREAD

**Issue by gprime44** [Jackett/Jackett#1574]
YGGTorrent Indexer doesn't work with fine with Radarr.

https://github.com/Radarr/Radarr/issues/1811

We need to move movies year like torrent9 indexer I think.

I'll try some tests.

**Comment by kaso17** [comment]
I believe the necessary options have been added by now.

**Comment by deromemont** [comment]
Reopen this ticket, radarr is not OK since the v2

**Comment by kaso17** [comment]
@deromemont please provide more details/logs of what's not working.

**Comment by kaso17** [comment]
I assume it's the same problem as in #2158
