### ISSUE TITLE
Manual search returns results, torznab/qBittorrent search blank when using IMDB ID

### ISSUE THREAD

**Issue by knw257** [Jackett/Jackett#15752]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Running in docker
Client: qBittorrent Jackett search plugin
Jackett Version v0.22.1083

I'm using the qBittorrent-nox docker container, connecting to the Jackett container through a shared network.
```

### Description

When I perform a search via the qBittorrent search plugin using an IMDB ID, no results appear. Using other search criteria (e.g. movie title) returns results successfully. When I perform the same IMDB ID search in the Jackett WebUI, the expected results are returned normally

In reviewing the qBittorrent search plugin code, I was able to reproduce the issue with the following URL:
http://<jackett-host>/api/v2.0/indexers/all/results/torznab/api?apikey=<API KEY>&q=tt28015403

Using network tracing, I can also reproduce the successful search from the Web UI using the following URL:
http://<jackett-host>/api/v2.0/indexers/all/results?apikey=<API KEY>&Query=tt28015403

The main differences I can see is the use of the torznab API in the qB search plugin, and the change to the parameter name from q= to Query=. If I change the qB search URL to use the Query parameter, I get results back, but they seem to return a large number of results not matching my search

### Logged Error Messages

```text
12-16 02:26:59 Info Manual search in IPTorrents, TorrentDay => Found 34 releases [512ms]
12-16 02:27:03 Info Torznab search in AggregateSearch for tt28015403 => Found 0 releases [2ms]
```

### Screenshots
Manual search in Jackett WebUI
![image](https://github.com/user-attachments/assets/f752773a-30c6-41f1-b26c-3bba68d7378a)

qBittorrent search with IMDB ID
![image](https://github.com/user-attachments/assets/bcab7c28-fafe-4947-840e-39ec586361f9)

qBittorrent search with movie title
![image](https://github.com/user-attachments/assets/6bc33fcc-a5b6-4cd2-ab52-e4632f2038e2)

**Comment by garfield69** [comment]
- The correct parameter for imdb searches via torznab is &imdbid=tt12345678
however results are depended on whether the web site that a specific indexer connects to, can actually support searching with an imdb, many do not.
- The aggregate indexer `ALL` is useful only for a general title search, and had many disadvantages compares to using a specific indexer. see https://github.com/Jackett/Jackett#aggregate-indexers
- The qBt plug in is not part of the Jackett app so questions and support are bust directed at the qBt support/forum site.
