### ISSUE TITLE
[dontorrent] (testing) Exception (dontorrent): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>301 Moved Permanently</title></head><body><h1>Moved Permanently</h1><p>The document has moved <a href="https://dontorrent.auction/ultimos">here</a>.</p></body></html>: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>301 Moved Permanently</title></head><body><h1>Moved Permanently</h1><p>The document has moved <a href="https://dontorrent.auction/ultimos">here</a>.</p></body></html>

### ISSUE THREAD

**Issue by JonArgErk** [Jackett/Jackett#15759]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No	
Using proxy: Disabled	
App config/log directory: /root/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 24.04.1 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 6.8.12.5 (64bit OS) (64bit process)
Environment version: 8.0.11 (/opt/Jackett/)
Starting Jackett v0.22.1096
```

### Description

the indexer DonTorrent now reports an issue.

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (dontorrent): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>301 Moved Permanently</title> </head><body> <h1>Moved Permanently</h1> <p>The document has moved <a href="https://dontorrent.auction/ultimos">here</a>.</p> </body></html> : <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>301 Moved Permanently</title> </head><body> <h1>Moved Permanently</h1> <p>The document has moved <a href="https://dontorrent.auction/ultimos">here</a>.</p> </body></html>
Click here to open an issue on GitHub for this indexer.
```

### Screenshots

![Captura de pantalla 2024-12-19 172952](https://github.com/user-attachments/assets/b9e6725c-62a1-4239-88b0-3b915d1f72cd).

**Comment by garfield69** [comment]
You can either:
- wait for the next release of Jackett due out in about 13 hours or so which will have the new domain, 
- or you can simply use your Jackett dashboard to edit the dontorrent config and replace the site link with `https://dontorrent.auction/` and click save.

**Comment by garfield69** [comment]
v0.22.1101

**Comment by slrslr** [comment]
5 months later, i can see the "301 Moved Permanently" and being redirected from 
https://dontorrent.date to 
https://dontorrent.gift

When i delete indexer, i can add .gift one, yet the error upon adding it is:
The document has moved <a href="https://dontorrent.gift/ultimos">here</a>

**Comment by ilike2burnthing** [comment]
Changed 3 days ago - https://github.com/Jackett/Jackett/commit/6e56730d933fb6760e94fde013549c3335ea05f9

Update Jackett.
