### ISSUE TITLE
Adding multiple trackers at once

### ISSUE THREAD

**Issue by ThatFluxNerd** [Jackett/Jackett#1576]
See title. Would that be possible? Or is it already and I'm just an idiot?
And it would also be nice if Jackett had an option to export the tracker list to Sonarr or other downloaders.

**Comment by chibidev** [comment]
@ThatFluxNerd Can you describe what you're trying to do? You can configure as many trackers as you want in Jackett.
Also, although it is still under development, you can use a special API endpoint that searches all trackers. Just copy the API URL of any tracker and replace the tracker's name with all. E.g. for me it looks like this: ```http://localhost:9117/torznab/all```

**Comment by ThatFluxNerd** [comment]
@chibidev I just want a checkbox next to trackers in Add Tracker menu so I can check them, press "Add selected" and have them added. As for the second part, I'm imagining something like selecting a tracker, checking a box with categories you want searched by, let's say, Sonarr, save to a JSON (or any other file), that can be then loaded by Sonarr to automatically add that tracker to the indexer list.

**Comment by chibidev** [comment]
@ThatFluxNerd thank you. May I ask why you need the ability to quickly add multiple trackers with the checkboxes? Don't get me wrong, I'm just curious about what you're trying to achieve and what your use-case is really about.

**Comment by ThatFluxNerd** [comment]
I frequently distrohop, it would make setting up Jackett easier.

**Comment by chibidev** [comment]
@ThatFluxNerd Understandable. However for me it seems like Jackett's configuration should be portable, so once you have Jackett and the Indexers configured, you could take the configuration directory, distrohop, install Jackett and have Jackett completely configured the same way. @flightlevel @kaso17 what do you guys think?

**Comment by kaso17** [comment]
Additionally to the Jackett Config directory it's also necessary to copy the corresponding keystore containing the keys used for obfuscating passwords in the config.
mono stores then at ~/.config/.mono/keystore
besides that it should work.

For adding/syncing trackers to sonarr/radarr/... there's already an issue open: #1413

**Comment by refriedfood** [comment]
I'd just like to add all the public trackers at once to the main page instead of one-by-one.

**Comment by coaxial** [comment]
Same here, it's a bit tedious to add them one by one

**Comment by Smalfinn** [comment]
+1 to this

**Comment by John-Gee** [comment]
I'm just starting to use Jackett and I agree that it's tedious to add one, go back to the main page, go back to add index, scroll to where I was, add another, and so on till I'm done.

**Comment by saviodesign** [comment]
So, there's no way to add multiple indexers in batch?

**Comment by oranblackwell** [comment]
I came up with a quick, dirty work around for adding all the free indexers in one go. 

From the Jackett page, click the "add indexer" button so that the pop up window with the full list of indexers appears.

You'll then need to open your browser's development toolbar (in Chrome just hit F12) and go to the JavaScript Console and enter the following:
```
////hack to add all free indexers in Jackett
$(document).ready(function () {
	EnableAllUnconfiguredIndexersList();
});


function EnableAllUnconfiguredIndexersList() {
    var UnconfiguredIndexersDialog = $($("#select-indexer").html());

    var indexersTemplate = Handlebars.compile($("#unconfigured-indexer-table").html());
    var indexersTable = $(indexersTemplate({ indexers: unconfiguredIndexers, total_unconfigured_indexers: unconfiguredIndexers.length  }));
    indexersTable.find('.indexer-setup').each(function (i, btn) {
        var indexer = unconfiguredIndexers[i];
        $(btn).click(function () {
            $('#select-indexer-modal').modal('hide').on('hidden.bs.modal', function (e) {
                displayIndexerSetup(indexer.id, indexer.name, indexer.caps, indexer.link, indexer.alternativesitelinks, indexer.description);
            });
        });
    });
    indexersTable.find('.indexer-add').each(function (i, btn) {
       
            $('#select-indexer-modal').modal('hide').on('hidden.bs.modal', function (e) {
                var indexerId = $(btn).attr("data-id");
                api.getIndexerConfig(indexerId, function (data) {
			        if (data.result !== undefined && data.result == "error") {
			            doNotify("Error: " + data.error, "danger", "glyphicon glyphicon-alert");
			            return;
			        }
	                api.updateIndexerConfig(indexerId, data, function (data) {
		                if (data == undefined) {
		                    reloadIndexers();
		                    doNotify("Successfully configured " + name, "success", "glyphicon glyphicon-ok");
		                } else if (data.result == "error") {
		                    if (data.config) {
		                        populateConfigItems(configForm, data.config);
		                    }
		                    doNotify("Configuration failed: " + data.error, "danger", "glyphicon glyphicon-alert");
		                }
			        }).fail(function (data) {
			            if(data.responseJSON.error !== undefined) {
                doNotify("An error occured while configuring this indexer<br /><b>" + data.responseJSON.error + "</b><br /><i><a href=\"https://github.com/Jackett/Jackett/issues/new?title=[" + indexerId + "] " + data.responseJSON.error + " (Config)\" target=\"_blank\">Click here to open an issue on GitHub for this indexer.</a><i>", "danger", "glyphicon glyphicon-alert", false);
            } else {
                doNotify("An error occured while configuring this indexer, is Jackett server running ?", "danger", "glyphicon glyphicon-alert");
            }
                        
			        });
                });
            });
        
    });
    indexersTable.find("table").DataTable(
        {
            "stateSave": true,
            "fnStateSaveParams": function (oSettings, sValue) {
                sValue.search.search = ""; // don't save the search filter content
                return sValue;
            },
            "bAutoWidth": false,
            "pageLength": -1,
            "lengthMenu": [[10, 20, 50, 100, 250, 500, -1], [10, 20, 50, 100, 250, 500, "All"]],
            "order": [[0, "asc"]],
            "columnDefs": [
                {
                    "name": "name",
                    "targets": 0,
                    "visible": true,
                    "searchable": true,
                    "orderable": true
                },
                {
                    "name": "description",
                    "targets": 1,
                    "visible": true,
                    "searchable": true,
                    "orderable": true
                },
                {
                    "name": "type",
                    "targets": 2,
                    "visible": true,
                    "searchable": true,
                    "orderable": true
                },
                {
                    "name": "type_string",
                    "targets": 3,
                    "visible": false,
                    "searchable": true,
                    "orderable": true,
                },
                {
                    "name": "language",
                    "targets": 4,
                    "visible": true,
                    "searchable": true,
                    "orderable": true
                },
                {
                    "name": "buttons",
                    "targets": 5,
                    "visible": true,
                    "searchable" : false,
                    "orderable": false
                }
            ]
        });

    var undefindexers = UnconfiguredIndexersDialog.find('#unconfigured-indexers');
    undefindexers.append(indexersTable);

    UnconfiguredIndexersDialog.on('shown.bs.modal', function() {
        $(this).find('div.dataTables_filter input').focusWithoutScrolling();
    });

    UnconfiguredIndexersDialog.on('hidden.bs.modal', function (e) {
        $('#indexers div.dataTables_filter input').focusWithoutScrolling();
    });

    $("#modals").append(UnconfiguredIndexersDialog);

    UnconfiguredIndexersDialog.modal("show");
}
```

**Comment by boniboni** [comment]
@oranblackwell Thanks for the script! Extremely useful

**Comment by D4M4EVR** [comment]
> From the Jackett page, click the "add indexer" button so that the pop up window with the full list of indexers appears.
> 
> You'll then need to open your browser's development toolbar (in Chrome just hit F12) and go to the JavaScript Console and enter the following

thank you!

**Comment by eltrkbrd** [comment]
Thanks, worked great!

**Comment by MedGR450** [comment]
oranblackwell thank you so much, worked perfectly!

**Comment by allanlaal** [comment]
can we reopen #1576 or #3274 ?
Adding all public trackers in one go was the first idea I got when setting up Jackett first time in my life

**Comment by kjbweb** [comment]
At the very least, can we have it so the window with all the trackers to add doesn't close after selecting one to add?  It's super tedious.

**Comment by Fiskelord** [comment]
I second this, would very much appreciate an "add all public" option

**Comment by bonesoul** [comment]
+1

**Comment by dontdieych** [comment]
I'm glad that I'm only one who think about this.

Thanks, @oranblackwell . script works good!

**Comment by bakerboy448** [comment]
for posterity: there are 0 logical reasons to be adding or using that many trackers

**Comment by saviodesign** [comment]
@bakerboy448 
It's called **redundancy** or **failover** 
(you may want to Google this term, rather than spout useless comments which help no one at all.)

In the IT Admin world, it's how you prevent the core elements of a system from becoming completely crippled.

In this case you'd have the option of multiple indexers/trackers, thus creating a catalog of choices, rather than limiting you to (1) single indexer;  effectively creating a "failover" feature for whenever one of the other indexers decides goes down, something which will absolutely occur .

**Comment by scotrod** [comment]
That's cool and all but can't we get a single "Add all" button instead of using this script?

**Comment by ilike2burnthing** [comment]
Closest thing to it likely to happen would be https://github.com/Jackett/Jackett/issues/7311

**Comment by sxiii** [comment]
Script helped but I would also note that this feature is really important. That was my only reason for installing Jackett actually (to been able to search all public trackers at once)

**Comment by vicentehenrique1998** [comment]
Could someone update this script? it's not working anymore.

**Comment by wardboumans** [comment]
I found out about Jackett, installed it via docker, found out i have to manuall add all indexers: LOL, delete, no way, horrible UX.

**Comment by garfield69** [comment]
@wardboumans  perhaps [prowlerr](https://github.com/Prowlarr/Prowlarr) will suit you better.

**Comment by unai-ndz** [comment]
Last time I checked Prowlarr did not have it either.
