### ISSUE TITLE
[req]: BT之家

### ISSUE THREAD

**Issue by lainiaobb** [Jackett/Jackett#15776]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: BT之家
- URL: https://www.1lou.info
- Description: Movie  TV series
```

**Comment by garfield69** [comment]
duplicate of #15708, same site alternate domain
