### ISSUE TITLE
Pass parameters in http headers?

### ISSUE THREAD

**Issue by Riz0** [Jackett/Jackett#1577]
Hi guys,

I enjoy using the manual search of Jackett and would like to pass the search query parameters in the http request, but I can't seem to get it working properly as no page resolves. I've tried the following after capturing the post parameters, but no luck:

http://127.0.0.1:9117/Admin/search%20Query=test&Category=&Tracker=

Any advice? Thanks in advance. 

-------------------------------

**Comment by chibidev** [comment]
@Riz0 are you trying something similar to what #1345 suggests?

**Comment by Riz0** [comment]
@chibidev Yes. I'm surprised I didn't find it myself when searching open issues, sorry. Would love to see this feature implemented.

**Comment by chibidev** [comment]
@Riz0 moving the discussion to the other thread, I'm closing this down.
