### ISSUE TITLE
Possible rootkit infection Linux.Xor.DDoS

### ISSUE THREAD

**Issue by flavioscalini** [Jackett/Jackett#15778]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

Linux xxx 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

### Description

Obviously a false positive - but please adapt those scripts to not trigger it.

wget https://github.com/Jackett/Jackett/releases/download/v0.20.3971/Jackett.Binaries.LinuxARM64.tar.gz
tar zxvf Jackett.Binaries.LinuxARM64.tar.gz
sudo mkdir /opt/jackett
sudo mv Jackett/* /opt/jackett

cat << EOF | sudo tee /etc/systemd/system/jackett.service
```
[Unit]
Description=NEOCORTEX Jackett Daemon
After=network.target
[Service]
SyslogIdentifier=jackett
Restart=always
RestartSec=5
Type=simple
User=torrent
Group=torrent
WorkingDirectory=/opt/jackett
ExecStart=/opt/jackett/jackett --NoRestart
TimeoutStopSec=20
EOF
[Install]
WantedBy=multi-user.target
```
systemctl start jacket

git clone https://github.com/Magentron/chkrootkit.git
cd chkrootkit
sudo ./chkrootkit

```
...
Searching for Linux.Xor.DDoS ... INFECTED: Possible Malicious Linux.Xor.DDoS installed
/tmp/JackettUpdate-v0.22.1116-638706798496262017/Jackett/jackett_launcher.sh
/tmp/JackettUpdate-v0.22.1116-638706798496262017/Jackett/install_service_systemd.sh
/tmp/JackettUpdate-v0.22.1116-638706798496262017/Jackett/JackettUpdater
/tmp/JackettUpdate-v0.22.1116-638706798496262017/Jackett/jackett
```

### Logged Error Messages

```text
Searching for Linux.Xor.DDoS ... INFECTED: Possible Malicious Linux.Xor.DDoS installed
/tmp/JackettUpdate-v0.22.1116-638706798496262017/Jackett/jackett_launcher.sh
/tmp/JackettUpdate-v0.22.1116-638706798496262017/Jackett/install_service_systemd.sh
/tmp/JackettUpdate-v0.22.1116-638706798496262017/Jackett/JackettUpdater
/tmp/JackettUpdate-v0.22.1116-638706798496262017/Jackett/jackett
```

**Comment by ilike2burnthing** [comment]
There's nothing that needs updating with our scripts in relation to this.

That repo has now been archived, and its last commit was from 5.5 years ago. The [original](https://www.chkrootkit.org/) seems to be more up to date, although even then its last update was a year and a half ago. Feel free to submit a false positive report to them, if it has the same issue, though I doubt you'll get far.
