### ISSUE TITLE
CardigannIndexer (torrent-explosiv): Relogin required

### ISSUE THREAD

**Issue by FizzyMUC** [Jackett/Jackett#15782]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2	
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.22.1128-ls625)
File /etc/issue: Welcome to Alpine Linux 3.20
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 4.4.302.0 (64bit OS) (64bit process)
Environment version: 8.0.11 (/app/Jackett/)
Starting Jackett v0.22.1128
```

### Description

Identical issue as #4763 

Returns empty search result (manual search from Jackett UI). Same applies to search via API.
In logs it shows only:
CardigannIndexer (torrent-explosiv): Relogin required 

Test runs and shows a green checkmark.
Tested with releases that are published on the site.

### Logged Error Messages

```text
2024-12-27 11:20:30	Info	
Test search in Torrent-Explosiv => Found 60 releases [5785ms]
Manual search in Torrent-Explosiv for Ronja => Found 0 releases [2198ms]
2024-12-27 11:17:58	Info	
CardigannIndexer(torrent-explosiv): Relogin required
2024-12-27 11:17:58	Error	
Redirected to: https://torrent-explosiv.me/login.php?returnto=%2Fselection.php%3Fsearch%3DRonja%26blah%3D2%26orderby%3Dadded%26sort%3Ddesc
```

**Comment by garfield69** [comment]
Yes I see this too.
T-E have switched to an ajax engine for searching and the indexer requires updating.
 Its the same engine that dark-shadow recently switched to using which now returns JSON results.

**Comment by FizzyMUC** [comment]
Nice, does this mean it's already fixed?

**Comment by ilike2burnthing** [comment]
Fix has been added, next release is due in ~8hrs.

**Comment by garfield69** [comment]
v0.22.1136
