### ISSUE TITLE
[DevQ] How to test private trackers?

### ISSUE THREAD

**Issue by chibidev** [Jackett/Jackett#1578]
Since almost 90% of the supported trackers are private I think we need something to be able to test them. Most of them require an invitation that probably cannot be shared and they often need constant usage (to prevent auto purging; I'm not talking about just searching and logging into the site, but actually downloading as well). There are numerous issues posted here that deal with private trackers, and not being able to fix them is a little bit frustrating.
(And I'm pretty sure that if I suddenly got all the invitations, I'd require it once again, because I probably won't use all of them constantly.)
@kaso17 @flightlevel what do you guys think, is there something that we could do about this?
I think somewhere (it might have been Sonarr/Radarr) I've seen that they post example responses from trackers. Although this wouldn't solve the issue altogether, since updates to the sites still cannot be updated without an invite, however at least some regression testing would be in place.
I was also thinking about reaching out to tracker providers, although I can hardly imagine that they would like to provide an API (e.g. in a format of torznab) or something for us, because they have no business in doing so (they will more likely generate income from people actually visiting their sites).

**Comment by kaso17** [comment]
My idea to solve this would be to improve the error/exception handling.
I would like to introduce some kind of request session. For each torznab/manual search/... request jackett would create a new session which contains all HTTP requests made to Jackett and requests made by jackett to the tracker webserver (probably based on the HTTP Archive format) and any other relevant information (e.g. log messages and results). In case of an error we could then dump the session information, with it we have all necessary information to reproduce the error. In a developer/simulator mode we could replay the requests/responses accordingly allowing us to easily identify problems and test fixes.

Ideally we add an integrated issue posting system allowing the uses to easily upload the session dumps and create corresponding issues directly from Jackett (no more asking for logs...).
For proper paginating support we'll need some kind of state/session anyway, so this will fit nicely.
I'm not sure how we should handle sensitive information (passwords, passkeys, cookies). I think we should add some kind of obfuscation regex magic which tries to obfuscate as much as possible of these information. Any maybe add some access protection to the uploaded session dumps (only developers can download them).

**Comment by chibidev** [comment]
This is a fairly good start, I think it resolves a couple issues, however it being kind of a reactive pattern (i.e. we get a report after something goes wrong), this is more useful for support issues (i.e. XYZ tracker is not working) in cases where the site changes for example. Those are pretty much resolved with this.

However I think there's another aspect. For example if I want to refactor a tracker (being a concrete one like nCore or some base functionality in BaseIndexer or similar) currently I cannot make sure that it will work for all trackers until I have access to all of them. I'm not saying that we should be able to prevent issues happening from refactoring, however it would definitely be awesome if we could prevent issues rather than reacting on them.

**Comment by kaso17** [comment]
Currently the "Test" button only tests if the search for the empty string returns > 0 releases.
That's something we could improve to. 
Some more things we could test:
* search for a non empty string (several trackers use different pages for "most recent" torrents and search results)
* Torrent download (To ensure downloading works)
* Check that the results have categories set (to make sure the category mapping is complete + detect changes)
* Check that the number of results returned are the maximum possible (to ensure users have adjusted the tracker profile settings, etc.)
* Run queries against the torznab/potato endpoints.

It shouldn't be very hard to use the resulting session dumps for automated regression testing.

**Comment by garfield69** [comment]
Closed as stale.
