### ISSUE TITLE
"Add new provider" improvements

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#158]
The provider list starts to be very big (And that's cool!)
But using a popup where you need to slide and which can easily be closed by mistake is not very user friendly...
Can we change the layout  from this big tile view to a more common list with pictures ? or may be create a dedicated page ?

**Comment by mkeguy106** [comment]
Do we really need pictures?  Just a list view would be great, IMHO.

**Comment by Azerelat** [comment]
You now only have images
