### ISSUE TITLE
Search query formatted with "%2b" is improperly parsed

### ISSUE THREAD

**Issue by nosmokingbandit** [Jackett/Jackett#1582]
Windows 10 tested by me, but verified on linux (unknown mono version) by others.

When searching an indexer with a query string such as `q=this%2bis%2ba%2bdownload`, Jackett parses this as `thisisadownload` rather than `this+is+a+download`.

Percent-encoding works for spaces. `q=this%20is%20a%20download` is read as `this is a download`

**Comment by kaso17** [comment]
fixed via 168f04e7861fc37994ea82624eb00f8b5aba7299
