### ISSUE TITLE
Demonoid has new URL

### ISSUE THREAD

**Issue by DrSeussFreak** [Jackett/Jackett#1585]
Demonoid needs to be updated to demonoid.click

**Comment by garfield69** [comment]
As far as I can tell (from the [official twitter a/c](https://twitter.com/DemonoidP2P), `https://www.demonoid.pw/` is still the primary url and works fine for me.     
If for some reason you need to change it, I would suggest you open your Jackett Demonoid indexer entry (by clicking on the wrench) and over-type the sitelink address with the one that works for you.      
IMO there is no need to make the *.click the default url for everyone.

**Comment by DrSeussFreak** [comment]
That did the trick for me
