### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by duramato** [Jackett/Jackett#159]
The version says ```Jackett Version 0.7.55.0``` but when i press the check for updae button i only get 
```Jan 06, 2016 11:57:06 AM	Info	Checked for a updated release but none was found.```

**Comment by JigSawFr** [comment]
Maybe related to https://github.com/Jackett/Jackett/issues/154

**Comment by Azerelat** [comment]
OS?

**Comment by duramato** [comment]
Debian

**Comment by Azerelat** [comment]
There was an issue which was fixed in v0.7.75 when running under mono.  You'll just have to upgrade manually.

**Comment by Bybou** [comment]
I am on Debian and it's working perfectly since 0.7.75

**Comment by duramato** [comment]
Auto update works , but manual check doesnt...

**Comment by duramato** [comment]
![image](https://cloud.githubusercontent.com/assets/10121067/12154052/332d87d0-b4b5-11e5-93b5-986404153aab.png)

Afteri waited a but after that SS was taken and jackett was updated (look where it says " none was found" )

**Comment by Azerelat** [comment]
The log says it running 107 so yes it is indeed running the latest.  The page doesn't refresh when you click trigger update as its a background activity which doesn't allow for it to refresh the page after its done.

**Comment by duramato** [comment]
The SS was taken on 102 and when i pressed check update ad found non when 107 was already avaiable (as you can see from the other tab) 
The update was made later (maybe from autoupdate?)

**Comment by Azerelat** [comment]
It can take 30-60 seconds to happen in the background depending on factors.  The starting Jackett version in the only one to look at as the one at the bottom of the page will not update until the page is refreshed but that isn't fixable currently.  Auto update takes 48 hours to run so we don't hammer Github every time you start the app.

**Comment by duramato** [comment]
and what about the log line ```Checked for a updated release but none was found.```
None
