### ISSUE TITLE
Sonarr can't download from YGG 

### ISSUE THREAD

**Issue by tomtom54** [Jackett/Jackett#1590]
Jackett version: 0.7.1609.0
Mono version (if not using Windows):  5.0.1.1

N.B. : using Docker from linuxserver (https://github.com/linuxserver/docker-jackett). 
But also tried to change the jackett version to be the last (develop branch). 

-------------------------------

Hi guys,

I've been issues with sonarr / radarr to use YGGTorrent with Jackett. 
It's seems the issue is related to Jackett since the problem is that the .torrent can't be downloaded. 
Here is an example : 
I'm looking for an episode in sonarr, I've the result from YGG. 
I click on download and it goes red. 
I look to the log in sonarr and I've an error but I also look to Jackett and I get this log : 
` 
07-26 08:31:16 Error Error downloading yggtorrent https://yggtorrent.com/engine/download_torrent?id=37842 MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
  at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent (MonoTorrent.BEncoding.RawReader reader) [0x0001e] in <2bea12db43634c238e7bd39fb9f0ca6a>:0
  at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent (System.IO.Stream s) [0x00006] in <2bea12db43634c238e7bd39fb9f0ca6a>:0
  at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent (System.Byte[] bytes) [0x00006] in <2bea12db43634c238e7bd39fb9f0ca6a>:0
  at Jackett.Controllers.DownloadController+<Download>c__async0.MoveNext () [0x00162] in <8c9dd9456ca844e9816aad61d0d5b140>:0
`
So I've tried to follow the link and the torrent is downloaded. 
If I remember well this thing was working at the beginning but since 2/3 versions I have the issue. 

Does anyone know why or has the same issue ? 

Thanks

**Comment by Dravenrip** [comment]
yes i've the same issue with the same configuration.

**Comment by foux** [comment]
Same issue for me!

**Comment by Nerwysh** [comment]
Same issue without docker...

Mono JIT compiler version 5.0.1.1
Jackett v0.7.1609

`juil. 26 15:05:43 XXXX mono[31536]: 07-26 15:05:43 Error Error downloading yggtorrent https://yggtorrent.com/engine/download_torrent?id=33856 MonoTorrent.BEncoding.BEncodingException: Invalid ...found. Aborting
juil. 26 15:05:43 XXXX mono[31536]: at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent (MonoTorrent.BEncoding.RawReader reader) [0x0001e] in <2bea12db43634c238e7bd39fb9f0ca6a>:0
`

**Comment by Amonbofils** [comment]
also can't found movies from couch! manually, it works but from couchpotato, no ...

**Comment by foux** [comment]
@Amonbofils this is a different issue, please put it in a new thread, with your logs

**Comment by chibidev** [comment]
@tomtom54 @Dravenrip @foux @Nerwysh Are you logged into YGG via Jackett?

**Comment by foux** [comment]
@chibidev I definitively was, and downloading used to work. But I re-entered my password as you suggested, and it worked again, thanks.
But I'm wondering why it stopped working at some point. Do you know when the authentication is done? Perhaps a cookie, or token is expiring at some point?

**Comment by Nerwysh** [comment]
@chibidev I have test to re-entered my password but same issue/log for me.

**Comment by tomtom54** [comment]
@chibidev you've right. 
I just have to open parameter of YGG from Jackett (don't even change the password) and just click okay and it was it. 
I would never had think to that (strange issue still) so thanks.

**Comment by Nerwysh** [comment]
I have create new account on ygg and it's work now ... thanks

**Comment by chibidev** [comment]
Strange. Don't know what happened with YGG, maybe the cookie was expired and a re-login solved it. I'm glad it's working now.

**Comment by foux** [comment]
Reproduced today (haven't changed password). Re-entered password, and it worked again

**Comment by Miloune** [comment]
Reproduced today. Wasn't able to download with Sickrage. Had to re-entered my password and now working fine.

**Comment by LePrt** [comment]
Hello here, 
Same issue for me.
- tried to re-enter my password in Jackett -> not working
- tried to delete/add Yggtorrent indexer -> not working
- manually deleted the indexer files in my jackett docker folder and adding indexer again -> not working

I noticed that, even if I leave the "password" field blank while configuring the yggtorrent indexer, jackett returns no error and I am even able to manually search for torrents.

Here are the logs : 
"Error Error downloading yggtorrent https://yggtorrent.com/engine/download_torrent?id=55317 MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
  at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent (MonoTorrent.BEncoding.RawReader reader) [0x0001e] in <2bea12db43634c238e7bd39fb9f0ca6a>:0 
  at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent (System.IO.Stream s) [0x00006] in <2bea12db43634c238e7bd39fb9f0ca6a>:0 
  at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent (System.Byte[] bytes) [0x00006] in <2bea12db43634c238e7bd39fb9f0ca6a>:0 
  at Jackett.Controllers.DownloadController+<Download>c__async0.MoveNext () [0x00162] in <1f28d1090a504fe4ae2d6d43a5f9c072>:0 "

Is the re-login solution still working for you guys ?

Thx

**Comment by flightlevel** [comment]
@Khogniak would you be able to have a look?

**Comment by Khogniak** [comment]
@flightlevel I'm currently testing a fix, I'm waiting for YGG frontend update to make a PR.

You can try a hotfix by adding the selector line in the login test (in Definitions/yggtorrent.yml) : 
```
test:
      path: "/"
      selector: "a[href=\"https://yggtorrent.com/user/logout\"]"
```
It should work
