### ISSUE TITLE
Couchpotato doesn't work with yggtorrent

### ISSUE THREAD

**Issue by Amonbofils** [Jackett/Jackett#1594]
Hi,

I got an issue with couchpotato and Ygg : with latest update, couchpotato request never find a movie. Jackett only return 0 releases found.

If i use old version (0.7.1581), jackett return the releases found. But when i try to download thru couchpotato, log said : 

Error Error downloading yggtorrent https://yggtorrent.com/engine/download_torrent?id=27970 MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
juil. 26 16:52:21 Maison mono[5783]: at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent (MonoTorrent.BEncoding.RawReader reader) [0x0001e] in <2bea12db43634c238e7bd39fb9f0ca6a>:0
juil. 26 16:52:21 Maison mono[5783]: at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent (System.IO.Stream s) [0x00006] in <2bea12db43634c238e7bd39fb9f0ca6a>:0
juil. 26 16:52:21 Maison mono[5783]: at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent (System.Byte[] bytes) [0x00006] in <2bea12db43634c238e7bd39fb9f0ca6a>:0
juil. 26 16:52:21 Maison mono[5783]: at Jackett.Controllers.DownloadController+<Download>c__async0.MoveNext () [0x00162] in C:\projects\jackett\src\Jackett\Controllers\DownloadController.cs:55

**Comment by chibidev** [comment]
@Amonbofils The error you're getting is probably the same as in #1590 . Can you describe what you're trying to do with Couchpotato and Jackett?

**Comment by Amonbofils** [comment]
Sorry just came back from holidays ! 

so this issue is solved, i don't have any logs anymore but still, there is an issue ! Couchpotato doescn't found anything ... 

for exemple :
in couchpotato logs after manual search :
`
08-23 10:29:35 INFO
[hpotato.core.plugins.base] Opening url: get http://xxx.xxx.xxx.xxx:9117/potato/yggtorrent?imdbid=tt2398241&search=Smurfs%3A+The+Lost+Village+2017&user=&passkey=xxx
08-23 10:29:35 INFO
[core.media.movie.searcher] Search for Smurfs: The Lost Village in 1080p ignoring ETA
`

i got this log on jackett : 

Aug 23, 2017 10:29:35 AM | Info | Found 0 torrentpotato releases from YGGtorrent for: Smurfs The Lost Village 2017
-- | -- | --


Now if i do manual search on jackett for the same keywords : 

Aug 23, 2017 10:33:45 AM | Info | Manual search for "Smurfs The Lost Village 2017" on YGGtorrent with 9 results.
-- | -- | --


If i try with radarr it works only with torznab but no with torrentpotato. i think the issue is arround potato feed ...

any idea ?

**Comment by kaso17** [comment]
What's the category returned for the manual search?
The potato feed will filter results to results with Movie categories.

**Comment by Amonbofils** [comment]
manual search is with movies (2000) and works

**Comment by kaso17** [comment]
Ok, then someone with access to the tracker needs to debug this.
