### ISSUE TITLE
torznab - B2S-Share fail

### ISSUE THREAD

**Issue by chmercesmoreira** [Jackett/Jackett#1595]
My problem is exactly the same as this one:
https://github.com/Jackett/Jackett/issues/655

But with another tracker: B2S-Share.
`<string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">Incorrect API key</string>`

**Comment by chibidev** [comment]
@chmercesmoreira Where do you want to add it? What settings do you use?

**Comment by chmercesmoreira** [comment]
It worked now, I have no idea why it didn't work before.
