### ISSUE TITLE
[req] partis.si

### ISSUE THREAD

**Issue by petekblaz** [Jackett/Jackett#1596]
Would love to see partis.si support on here.

**Comment by petekblaz** [comment]
If you ever get to this, you need Slovenian IP to login, as far as I know. Just an FYI.

**Comment by garfield69** [comment]
jacket 0.12.1146

**Comment by ilike2burnthing** [comment]
https://www.partis.si/ - maintenance?
>Prosimo izpolnite obrazec z vašim uporabniškim imenom in e-mailom in vas bomo obvestili takoj, ko bo stran na voljo.

> ‎Please complete the form with your username and e-mail and we will inform you as soon as the page is available.‎

**Comment by garfield69** [comment]
victim of the server building fire at OVH I reported a little while ago.
Home page states they are slowly rebuilding from backups etc.

**Comment by garfield69** [comment]
still no signs of life, and now https://www.partis.si/ is returning ERR_CONNECTION_REFUSED
I'm going to remove it and in the event it later returns we can always add it back.

**Comment by garfield69** [comment]
v0.18.210

**Comment by ilike2burnthing** [comment]
Site is back up and out of their recovery and beta access phases (thank you to @FileGo for the update).

Unfortunately it looks like there is no way to recover old accounts (even just to start from scratch), and I don't see a signup page. The site is completely different, so we can't just restore the old indexer, therefore we'd need an invite to continue.

**Comment by mjazbc** [comment]
What do you mean "no way to recover old accounts"? You old account should work just fine - at least mine does. You can also try to [reset your password](https://partis.si/pozabilgeslo). If that doesn't work, you'll probably just have to wait for them to re-add signup page. There are no invites as far as i know.

**Comment by ilike2burnthing** [comment]
Perhaps some accounts were saved then, who knows, but mine definitely isn't, and trying to reset my password results in `‎User not found in database‎` (I did try that before, but I've confirmed again).

If you notice signups being available, let us know.

**Comment by garfield69** [comment]
v0.19.275

**Comment by garfield69** [comment]
https://www.partis.si/ returns Portal trenutno ni dosegljiv

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
partis returns Internal Server Error

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://www.partis.si/ - `Dear users, due to a lack of resources for the operation of the portal, this is currently unavailable.`

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.partis.si/ cloudflare Gateway time-out Error code 504

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://www.partis.si/ - A timeout occurred - Error code 524

check freeleech search/filter when back up

**Comment by garfield69** [comment]
A timeout occurred Error code 524

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
A timeout occurred Error code 524

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/1596#issuecomment-1501035723

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
Bad gateway Error code 502

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.partis.si/portal#torrent/search 500 Internal server error

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/1596#issuecomment-1501035723

**Comment by garfield69** [comment]
Mysql2::Error::ConnectionError  Can't connect to server on '127.0.0.1'

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/1596#issuecomment-1509413856

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
/www.partis.si/torrent/search 404

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.partis.si/portal#torrent/search Mysql2::Error::ConnectionError  Can't connect to server on '127.0.0.1

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
404

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.partis.si/user/login redirects to http://www.partis.si/user/login which in turn presents 
`DNS points to prohibited IP | www.partis.si | Cloudflare`

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.partis.si/portal#torrent/search Internal server error

**Comment by garfield69** [comment]
v0.21.446

**Comment by ilike2burnthing** [comment]
`we're coming back in a different form`
