### ISSUE TITLE
Found no results while trying to browse this tracker - WorldOfP2P

### ISSUE THREAD

**Issue by greatcapp** [Jackett/Jackett#1597]
I seem to be able to log in ok with Jackett (if i enter incorrect login details i get a login error) but i then get the above error. Is this likely to be site based, or a Jackett issue? Please let me know if i need to include some more information.
-------------------------------

**Comment by chibidev** [comment]
Thank you, @greatcapp. The latest release (v0.7.1622) should fix the issue, please give it a go.

**Comment by greatcapp** [comment]
It looks to be fixed now. Many thanks for that.
