### ISSUE TITLE
black tray icon on black taskbar

### ISSUE THREAD

**Issue by Giligilitelj** [Jackett/Jackett#1598]
hi, i love this project and I'm using it all the time. My issue is not that big of a deal. Just an aesthetics one.
The icon that is used for Jackett is completely black, and the tray icon is almost invisible for some of us that prefer dark/black theme. Solution is very simple, just add white stroke around the icon or white circle.
I did it for my Jackett, and actually quite like it.
Here is my solution for it.

![jackett](https://user-images.githubusercontent.com/27040483/28728094-99f3e3f6-73c7-11e7-8f8d-28912dc6ac0d.png)

Please, don't think badly of me for posting such miscellaneous issue.
Dalibor

**Comment by flightlevel** [comment]
Thanks @Giligilitelj 
Just to confirm, you converted the above the png to an .ico file and then placed it in the Jackett.Tray directory and then rebuilt the exe ?

**Comment by kaso17** [comment]
@Giligilitelj can you answer the question?
