### ISSUE TITLE
Better result with searchTerm in lowercase for xthor

### ISSUE THREAD

**Issue by aureliensauv** [Jackett/Jackett#1599]
I've better result with searchTerm in lowercase for Xthor API.

Ex : "The Last Man On Earth S03E09" and test with "the last man on earth s03e09"

Fix : Just add searchTerm = searchTerm.ToLower(); after var searchTerm = query.GetQueryString(); (L159) in PerformQuery method (Xthor.cs)

Jackett version:  v0.7.1594
Mono version (if not using Windows):  5.0.1.1

-------------------------------

**Comment by flightlevel** [comment]
Happy to make this change if its been well tested
Does the same thing happen on the website?
Is there any theory behind this as well, ie. accent characters in French ????
Any thoughts @JigSawFr

**Comment by aureliensauv** [comment]
It  works on my branch since 15days without any problem.
I don't hnow why the search query return better result in lowercase. Xthor works with an api and the website seems not to be affected by that.

**Comment by JigSawFr** [comment]
Hum, it's strange because I've just tested with your example, and API endpoint return 6 results in both case.
@flightlevel I've not tested with accents, as 99% of files have scene naming rules (so no accents)

As searching with lowercase don't affect us, we can let it search with lowercase if someone think we have better results doing with this manner.

**Comment by aureliensauv** [comment]
i just tested, and effectively the problem seems to be resolved. Perhaps a fix on xthor api ... I don't know.

Je continu en francais. Initialement quand je tapais "The Last Man On Earth S03E09" l'api me retournait des résultats sur the last man mais S01E01 des trucs du genre (aucun match). J'ai testé un peu par hasard en mettant tout en minuscule et la nickel. Problème bizarre de base ...

**Comment by JigSawFr** [comment]
@aureliensauv pas de soucis, n'hésites pas si tu rencontres d'autres problèmes ;)
