### ISSUE TITLE
Jackett not working with Couchpotato (ShareSpaceDB)

### ISSUE THREAD

**Issue by rouggy** [Jackett/Jackett#1600]
Hi all,

I cannot get Jackett to work with some French providers such as SharespaceDB
I always get the same error in the log, actually i cannot get it to work with any 

ERROR
[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://jackett.xxx.xxx/potato/sharespacedb?imdbid=tt1544608&search=Voice+from+the+Stone+2017&user=&passkey=xxx&search=Voice+from+the+Stone+2017&user=&passkey=xxx

If i use above link to try directly from Chrome i always get the "API is incorrect" message despite the fact i change in above link the passkey=xxx by the real passkey...

Jackett Version 0.7.1622.0
Mono version (if not using Windows):  Mono JIT compiler version 5.0.1.1 

Anyone is having the same issue ?

Thanks

**Comment by flightlevel** [comment]
Does the same thing happen when using a localhost address?

**Comment by rouggy** [comment]
Yes i confirm same issue with local ip:port

**Comment by kaso17** [comment]
CP shouldn't add user/passkey twice to the URL
Looks like #1692
closing in favor off #1692
