### ISSUE TITLE
[REQ] Add "t411.si" tracker

### ISSUE THREAD

**Issue by D4rk56** [Jackett/Jackett#1601]
A site that includes the template of t411.
--> https://t411.si/

**Comment by JigSawFr** [comment]
This torrent tracker seems to be a "fake" mirror of original tracker sized by authority.
Due to security reasons, as stealing account or members credentials,
This request is now closed.

**Comment by NexusJS** [comment]
I visited the twitter, saw multiple different user and real updates on css and so on. I'm pretty sure it's a "legit" version of t411 using a public tracker instead of a semi-private one like before.  Imo it's worth a reconsideration.
Thanks.

**Comment by elafarge** [comment]
Hi there,

T411 is indeed  a complete revamp of the old T411 website - and not a clone in any case. However, it doesn't require to login to download torrents, leech & seed them. Login is only required to post new torrents & comments.

In other words, this new website works like any other public tracker (the pirate bay, Torrentz2) from a downloader/seeder perspective (actually a lot of the content it provides comes from such public trackers already). In the past few weeks, it got a lot of traction in french speaking countries.

Therefore supporting it in Jackett, IMO, would totally make sense: 
  * It would make a lot of content in French (but not only: it also references a lot of multilingual `.mkv` or `.mp4` movies and shows) available to Jackett-Sonarr-Radarr-Plex users
  * These users would - in most cases - seed the torrents provided by T411.si, giving the new T411 the help it needs to become even better than its predecessor :)

Thanks a lot for taking that into consideration :)

Cheers,

-E

**Comment by hkaj** [comment]
+1, it's legit. Check t411 Twitter account (in French) for confirmation.

**Comment by douchmehdi** [comment]
+1

**Comment by D4rk56** [comment]
The tracker is already added

**Comment by elafarge** [comment]
Hi @D4rk56 ,

Thanks for the quick feedback. I just came across [this commit](https://github.com/Jackett/Jackett/commit/f2ce167bbf079327a5ce5e3105811e8a8de3f5fa) and another one that updates definitions accordingly 7 days ago. My bad for undigging this thread.

However, I'm using the (`latest`) Docker image from LinuxServer.io built two days ago and the new T411 isn't there. I'll reach them out on IRC to figure out if there's a way to get the latest tip of Jackett's `master` branch built :)

Thanks again,

-E

**Comment by elafarge** [comment]
Ok I get it, linuxserver builds its images based on the latest Github release, do we have an ETA for the next one ?

**Comment by elafarge** [comment]
(If not that's no issue, I'll just build the latest pre-release and push it to my Dockerhub account)

**Comment by solspire** [comment]
I would like use t411 with jackett on my nas synology (packet jackett) but t411 is t411.al and not t411.si. I hope work soon ! ++

**Comment by JigSawFr** [comment]
As @D4rk56 this tracker was already added as a Definition,
see https://github.com/Jackett/Jackett/blob/master/src/Jackett/Definitions/t411v2.yml
