### ISSUE TITLE
Many Indexers Fail the Test with VPN Enabled

### ISSUE THREAD

**Issue by viking2** [Jackett/Jackett#1602]
Many, but not all, of my indexers fail the Test with "Found no results" and "Exception in test_indexer"
Jackett version:  v0.7.1622 (Windows 7; 64 bit)

The log file when testing EZTV has been attached.

If I turn off my VPN, the Test of EZTV and many others, but not all, pass.
Does that mean I cannot use a VPN with many indexers?

[log_Test_EZTV.txt](https://github.com/Jackett/Jackett/files/1185555/log_Test_EZTV.txt)

**Comment by chibidev** [comment]
@viking2 based on your logs it seems that you receive a Cloudflare page. More information can be found here: https://support.cloudflare.com/hc/en-us/articles/203366080-Why-do-I-see-a-captcha-or-challenge-page-Attention-Required-trying-to-visit-a-site-protected-by-Cloudflare-as-a-site-visitor-
This shouldn't be related to Jackett, you should receive the same page when connecting to the site in a normal browser from behind your vpn.
