### ISSUE TITLE
Torrent Network 405 Not Allowed nginx

### ISSUE THREAD

**Issue by Wyall** [Jackett/Jackett#1603]
Jackett version:  0.7.1622.0
Mono version (if not using Windows):  5

-------------------------------

It's been a few weeks since Torrent Network stopped working. They completly changed their website and shut down the classic version a few weeks ago, but not sure if thats coincidence.

When I try to add the tracker I get "Configuration failed: 405 Not allowed nginx"

**Comment by hannesschmidt** [comment]
Still not fixed

**Comment by kaso17** [comment]
fixed in the latest pre release
