### ISSUE TITLE
Test of ShowRSS Works in Jacket but not in Sonarr

### ISSUE THREAD

**Issue by viking2** [Jackett/Jackett#1608]
Test of ShowRSS Works in Jacket but not in Sonarr. I have attached logs from both tests, which shows: 
In Jacket: Found 81 releases from ShowRSS 
Via Sonarr: Found 0 (0 new) releases from ShowRSS 
(Other Jacket Indexers works fine in Sonarr)

Jackett version:   0.7.1622.0 (windows 7 64-bit)

[log_Test_ShowRSS.txt](https://github.com/Jackett/Jackett/files/1186004/log_Test_ShowRSS.txt)
[log_Test_Sonarr_ShowRSS.txt](https://github.com/Jackett/Jackett/files/1186005/log_Test_Sonarr_ShowRSS.txt)

**Comment by BetaLeaf** [comment]
Same here.

**Comment by viking2** [comment]
I checked the logs above. 
When Testing, Jackett queries http://showrss.info/other/all.rss in both cases and in both cases several shows are found. However, while the Jacket Test counts the found shows as 81, the Test via Sonarr counts those shows as 0. 

p.s. When I use http://showrss.info/other/all.rss in my browser, I find nothing. However, http://showrss.info/other/shows.rss works. 
If http://showrss.info/other/shows.rss is the correct URL, I wonder why the logs shows http://showrss.info/other/all.rss ?

**Comment by chibidev** [comment]
@viking2 shows.rss contains the shows available at ShowRSS while all.rss contains the actual feed for episodes.

Apparently Sonarr passes the categories which filters out basically all results from ShowRSS. 29ecf8a should fix that, however there are major problems with ShowRSS as it is today, so it might need a bigger refactor. The latest pre-release (v0.8.10) contains the fix, feel free to try it out.
