### ISSUE TITLE
Sky Torrents generates errors in log and doesn't function because of it.

### ISSUE THREAD

**Issue by BetaLeaf** [Jackett/Jackett#1612]
Sky Torrents does not function in Sonarr at all. Checking Jackett logs shows it is having trouble processing the results from search.

Jackett version:  Jackett Version 0.7.1622.0
Mono version (if not using Windows):  Mono JIT compiler version 4.8.1 (4.8.1.0 Sun Jul 23 01:32:56 UTC 2017)
Running on a FreeNAS server, inside a jail.

[Logs.zip](https://github.com/Jackett/Jackett/files/1190289/Logs.zip)

**Comment by jeff15110168** [comment]
same issue, Sky is not working anymore. Also is idope available?

**Comment by a92nj2efnfsa** [comment]
Looks like he removed the ability to download torrent files from the search results. Now there is only a magnet link. This is most certainly what has broke jacket from working properly on that site. It's looking at the wrong table row now since one of them has been removed.

**Comment by jeff15110168** [comment]
hmm, so could this be updated? I assume the magnet links is still what jackett uses?

**Comment by a92nj2efnfsa** [comment]
Yea fairly easily. The devs just have to tell Jackett to look at the first TR instead of the second one now.

**Comment by jeff15110168** [comment]
awesome, anyway we can push this devs to become an update? Otherwise i assume they will potentially check the issues thread with enough upvotes/comments

**Comment by flightlevel** [comment]
@a92nj2efnfsa can you please submit a PR with the fix then

**Comment by danmed** [comment]
https://github.com/Jackett/Jackett/pull/1626

**Comment by chibidev** [comment]
This is available in the latest pre-release v0.7.1662. @jeff15110168 @BetaLeaf can you confirm it's working?

**Comment by BetaLeaf** [comment]
checking now

**Comment by BetaLeaf** [comment]
Confirmed. It's working now.
