### ISSUE TITLE
Secret-Cinema problem

### ISSUE THREAD

**Issue by octophetus** [Jackett/Jackett#1613]
The tracker Secret-Cinema has been revamped, now located at https://secret-cinema.pw/
Can't log in via Jackett anymore. Error states: "Configuration failed: Login Failed, got redirected".

**Comment by kaso17** [comment]
they deleted my account due to inactivity, somebody else has to fix it.

**Comment by kaso17** [comment]
@JigSawFr did you test if it works again?
I've only changed the URL in the definition but didn't test it.

**Comment by JigSawFr** [comment]
@kaso17 I supposed it was fixed by changing link

**Comment by kaso17** [comment]
@octophetus if you just change the URL in the indexer configuration to the new one, does that fix your problem?

**Comment by octophetus** [comment]
I've tried changing it to https://secret-cinema.pw/ and https://secret-cinema.pw/index.php and they do not work. Configuration failed: Login Failed, got redirected.

**Comment by octophetus** [comment]
Also, I guess I'm not sure what you mean by "changed the URL in the definition" but the default is still set to http://www.secret-cinema.net/

But changing it doesn't make it work anyway.

**Comment by kaso17** [comment]
In the latest pre-release the default domain is changed to .pw.
But it won't fix the problem. Someone still has to fix the definition.

**Comment by octophetus** [comment]
Yeah I can definitely see now that it's defaulting to https://secret-cinema.pw/ as the url in the tracker list at least, but it is still showing the same error.

**Comment by adamwinn** [comment]
I can take a look at this one

**Comment by adamwinn** [comment]
Fixed with #1803

**Comment by kaso17** [comment]
Thank you

**Comment by octophetus** [comment]
Hooray! Thank you!

**Comment by savahu** [comment]
@octophetus does it work for you now?
I can add it, but I see no categories.

**Comment by adamwinn** [comment]
Secret Cinema appears to have gotten rid of categories.  They use tags for what I assume used to be categories
