### ISSUE TITLE
[REQ] New Tracker – Extra Torrent

### ISSUE THREAD

**Issue by zero77** [Jackett/Jackett#1621]
Can you please add support for Extra Torrent,
thanks.

Tracker Name : Extra Torrent
Type : Movie, TV, Music, Anime, Games, Software, Books, Pictures, Mobile, Adult, Other
Public tracker.
Indexer URL : https://extratorrent.cd
Indexer language : English

**Comment by zero77** [comment]
Hi
What help is needed?

**Comment by kaso17** [comment]
Someone who's willing to implement it :)
If you know a little HTML/CSS you can try it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format

**Comment by metaMMA** [comment]
Extratorrent.cd is simply a mirror of TPB. It is not related in anyway to the previous ExtraTorrent.  See article here: https://torrentfreak.com/no-extratorrent-has-not-been-resurected-170524/ I suugest just using TPB.

**Comment by JigSawFr** [comment]
Thank you @metaMMA, as it's just a mirror of TPB, request is now closed
