### ISSUE TITLE
[REQ] New Indexer eMule-Island

### ISSUE THREAD

**Issue by UneYahourtiere** [Jackett/Jackett#1622]
Tracker Name : eMule Island
Type : Movie, TV, Music, Anime, Games, Software, Books, Other
Public tracker.
Indexer URL : ~~https://www.emule-island.ru/~~ https://ww6.emule-island.ru/
Indexer language : French

Thank you !

**Comment by garfield69** [comment]
not going near this one. as far as I can tell, there are no torrent links, it all streaming or direct downloads that only work via an app you first have to install. 
the site is not suitable for a cardigann definition.

**Comment by ngosang** [comment]
@garfield69 if there aren't torrents can we close?

**Comment by garfield69** [comment]
absolutely.

**Comment by ngosang** [comment]
@garfield69 Offtopic: We have too many open issues. When you have free time, could you close as much as possible?
No label => https://github.com/Jackett/Jackett/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+no%3Alabel
Connection => https://github.com/Jackett/Jackett/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+connection
I just checked all public trackers are working fine (there are 4 temporary down). Old issues can be closed and ask the user to install latest Jackett.
