### ISSUE TITLE
Tests failing on all indexes

### ISSUE THREAD

**Issue by nofaddey** [Jackett/Jackett#1623]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  Jackett Version 0.7.1644.0
Mono version (if not using Windows):  most recent version

-------------------------------

Hi,
 
installed jackett on my raspberry pi 3 on most recent version of raspbian jessie lite.

I cant connect to any of the indexes, not sure what the problem is. tried --IgnoreSslErrors fix but didn't fix it. All mono dependencies are install from running sudo apt-get install mono-devel.

All of the indexes I have tried fail the test with these errors in the logs, here is an example from kickass torrents:

Aug 06, 2017 08:26:29 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
-- | -- | --
Aug 06, 2017 08:26:29 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Aug 06, 2017 08:26:29 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Aug 06, 2017 08:26:29 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Aug 06, 2017 08:26:29 PM | Info | HttpActionBinding ExecuteBindingAsync
Aug 06, 2017 08:26:29 PM | Info | HttpActionBinding ExecuteBindingAsync
Aug 06, 2017 08:26:29 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 06, 2017 08:26:29 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 06, 2017 08:26:29 PM | Info | ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Aug 06, 2017 08:26:29 PM | Info | ApiControllerActionSelector SelectAction
Aug 06, 2017 08:26:29 PM | Info | AdminController ExecuteAsync
Aug 06, 2017 08:26:29 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Aug 06, 2017 08:26:29 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Aug 06, 2017 08:26:29 PM | Info | DefaultHttpControllerActivator Create
Aug 06, 2017 08:26:29 PM | Info | HttpControllerDescriptor CreateController
Aug 06, 2017 08:26:29 PM | Info | DefaultHttpControllerSelector SelectController Admin
Aug 06, 2017 08:26:29 PM | Info | DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Aug 06, 2017 08:26:29 PM | Info | http://192.168.0.245:9117/Admin/GetLogs?_=1502047560248
Aug 06, 2017 08:26:26 PM | Info | AdminController Dispose
Aug 06, 2017 08:26:26 PM | Info | AdminController Dispose
Aug 06, 2017 08:26:26 PM | Info | Content-type='application/json; charset=utf-8', content-length=81
Aug 06, 2017 08:26:26 PM | Info | AdminController ExecuteAsync
Aug 06, 2017 08:26:26 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Aug 06, 2017 08:26:26 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Aug 06, 2017 08:26:26 PM | Info | ApiControllerActionInvoker InvokeActionAsync
Aug 06, 2017 08:26:26 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]'
Aug 06, 2017 08:26:26 PM | Debug | Saving new config file: /root/.config/Jackett/Indexers/kickasstorrent-kathow.json.b7e0fdb07ff14342b4fcc1a59ea9e7e3.tmp
Aug 06, 2017 08:26:26 PM | Error | Exception in test_indexer
Aug 06, 2017 08:26:26 PM | Info | Found 0 releases from KickAssTorrent (kat.how)
Aug 06, 2017 08:26:26 PM | Debug | IWebClient: Returning NotImplemented =>
Aug 06, 2017 08:26:26 PM | Error | headerString:
Aug 06, 2017 08:26:26 PM | Error | cookies:
Aug 06, 2017 08:26:26 PM | Error | request.RawPOSTDdata:
Aug 06, 2017 08:26:26 PM | Error | request.Referer:
Aug 06, 2017 08:26:26 PM | Error | request.Cookies:
Aug 06, 2017 08:26:26 PM | Error | request.Url: https://kat.how/search.php?q=
Aug 06, 2017 08:26:26 PM | Error | request.Method: GET
Aug 06, 2017 08:26:26 PM | Error | got NotImplemented/InternalServerError
Aug 06, 2017 08:26:26 PM | Debug | IWebClient.GetString(Url:https://kat.how/search.php?q=)
Aug 06, 2017 08:26:26 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
Aug 06, 2017 08:26:26 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Test()'
Aug 06, 2017 08:26:26 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Aug 06, 2017 08:26:26 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()'
Aug 06, 2017 08:26:26 PM | Info | HttpActionBinding ExecuteBindingAsync
Aug 06, 2017 08:26:26 PM | Info | HttpActionBinding ExecuteBindingAsync
Aug 06, 2017 08:26:26 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 06, 2017 08:26:26 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 06, 2017 08:26:26 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Test()'
Aug 06, 2017 08:26:26 PM | Info | ApiControllerActionSelector SelectAction
Aug 06, 2017 08:26:26 PM | Info | AdminController ExecuteAsync

Let me know if I can provide anymore details.

Thanks

**Comment by flightlevel** [comment]
Full logs needed to investigate ie run with `-t -l`
https://github.com/Jackett/Jackett#troubleshooting

**Comment by nofaddey** [comment]
This is a log of it starting and running two tests on isohunt and kat

[log.txt](https://github.com/Jackett/Jackett/files/1232304/log.txt)

**Comment by kaso17** [comment]
@nofaddey what kind of hardware are you running jackett on?
You're using the legacy libcurl webclient.
Please Try running jackett with `-c httpclient`

isohunt is down (https://isohunt.to/latest.php)

**Comment by kaso17** [comment]
closing, no response
