### ISSUE TITLE
Pretome Indexer: Parsing failed «TimeAgo parsing failed, unknown unit: <br»

### ISSUE THREAD

**Issue by ctroncoso** [Jackett/Jackett#1627]
using Jackett Version 0.7.1644.0
Pretome news say that they'll be updating the front page, which might have broken the parser. 
Testing fails with the following error: TimeAgo parsing failed, unknown unit: <br

**Log**: 
Error on 20170807140359 for PreToMe.txtSystem.Exception: TimeAgo parsing failed, unknown unit: <br
  at Jackett.Utils.DateTimeUtil.FromTimeAgo (System.String str) [0x0026a] in <3c02d63f4dc54c69812f99444f189d7e>:0 
  at Jackett.Indexers.Pretome+<PerformQuery>c__async1.MoveNext () [0x00543] in <3c02d63f4dc54c69812f99444f189d7e>:0 

**html that caused error**: https://gist.github.com/ctroncoso/d70aa415c716ddbe5412cf4254b9f2d1

**Comment by bmay4048** [comment]
I am having this issue as well.

**Comment by belgarth** [comment]
Myself as well

**Comment by mikesafari** [comment]
Yup, same here as well.

**Comment by kaso17** [comment]
For me it's working again (with the changes made by @flightlevel). Can we close it?

**Comment by mikesafari** [comment]
Not working for me still. Must admit it's been ages since I've poked around in code, but is it fairly easy to update this manually or should I wait for the update to be pushed out?

**Comment by kaso17** [comment]
the changes haven't been released yet, a pre-release will follow soon.
