### ISSUE TITLE
Cannot add Pretome

### ISSUE THREAD

**Issue by duramato** [Jackett/Jackett#163]
I can not add, pretome it just replies invalid pin code `Configuration failed: Login failed. Did you use the PIN number that pretome emailed you?`
Any info that i can get?

**Comment by Azerelat** [comment]
I just tried re-setting up the tracker and can login fine.  Silly question but you put the pin in the right field right?

**Comment by duramato** [comment]
Yes , "Login Pin Number"

**Comment by Azerelat** [comment]
I am wondering if its a Linux encoding issue.  If you are on Linux try removing non alpha numerics from all the fields and see if it helps.

**Comment by duramato** [comment]
yes im on linux ,debian to be more specific but my passwords its just letters and numbers

**Comment by kaso17** [comment]
working with the latest version
