### ISSUE TITLE
Hon3yHD Inaccurate Search Results

### ISSUE THREAD

**Issue by qazero** [Jackett/Jackett#1630]
I noticed Hon3yHD's native search functionality isn't very good. For example, if you search for the movie "Mujhse Shaadi Karogi" you will get accurate results. However, if you search for the same movie with its release year appended "Mujhse Shaadi Karogi 2002" then it will produce many more results but most of them would be completely wrong titles. In addition, many of the correct results from the first search query without the release year are not found either. The simple solution would be to leave out the release year from the search query but unfortunately Radarr has no option to do this. Radarr automatically appends the release year to each search query it makes by default. That being said, could you please add a feature to Jackett to automatically remove the last word/string it receives from Raddar (as this would correspond to the release year)? This would only need to be applied to the configuration for Hon3yHD so it wouldn't effect the searches made for other trackers. Thanks

**Comment by flightlevel** [comment]
Combining this issue into https://github.com/Jackett/Jackett/issues/1636
Potential enhancement to remove the year from movie searches???
