### ISSUE TITLE
No result witch year provided - remove year search ?

### ISSUE THREAD

**Issue by leloki** [Jackett/Jackett#1636]
Hi,

I have a pretty regular issue when to find some movies.
I use Radarr with Jackett and 3 different indexers (torrent9, cpasbien,freedomhd)

If my indexers have the movie in their database with a different year no movie release will be found. I think this is due to the difference between imdb release year and the release year in different country (France for me).
I have a example :
Kingsman - Services Secrets, imdb release year 2014 but referenced in my indexers in 2015.
So no results at all in Radarr though the movie is found with manual search in Jackett with 2015 instead of 2014.

How could I remove the year (as a workaround) in the search keywords ? 

I tried that in torren9.yml : 

  search:
    path: "{{if .Query.Keywords}}/search_torrent/{{range .Categories }}{{.}}/{{end}}{{ .Query.Keywords }}/page-0,trie-seeds-d{{else}}/top_torrent.php{{end}}"
    keywordsfilters:
      - name: re_replace
        args: ["[1-2][0-9]{3}", ""] # remove year in search keywords

But it does not work.

Could you help me please ?

Jackett version:  
0.7.1662.0
Mono version (if not using Windows):  
5.0.1.1 (linux)
Loki

-------------------------------

**Comment by Khogniak** [comment]
Try
```
- name: re_replace
  args: ["([1-2]\d{3})", ""] # remove year in search keywords
```

**Comment by leloki** [comment]
thanks for your response. But it does not work :'(

**Comment by flightlevel** [comment]
Potential enhancement to remove the year from movie searches???
Should this be a Jackett feature or Radarr???

**Comment by Khogniak** [comment]
This issue is on Radarr's side ; their name-scrapper is too strict and doesn't fit with most of torrent providers. I think Jackett doesn't have to modify content/metadata in his process.
This is processor's job.

**Comment by kaso17** [comment]
I agree that a workaround for this is better suited on the Radarr side.

For your temporary workaround you'll also have to change the ".Query.Keywords" (always the original query string) in the path to ".Keywords" (with keywordsfilters applied).

But Radarr still might not accept the results as valid (due to year mismatch).

**Comment by leloki** [comment]
@kaso17 Thanks ! your workaround correction is perfect :) it works now. 
In addition to the nightly version of Radarr which include a force download tool to add an alternative title or year everything is working now :)

Thanks again !

**Comment by JigSawFr** [comment]
@kaso17 maybe we can detect if request is processed by Radarr and strip year in this case ?

**Comment by leloki** [comment]
that could be useful yes but I doubt this is possible. And we have the same problem with the movies titles... But that is an even more difficult problem

**Comment by JigSawFr** [comment]
@leloki I don't know if Radarr set a custom UserAgent or something else

**Comment by kaso17** [comment]
@JigSawFr It definitely would be possible to add the necessary features on the radarr/jackett side but what would be the benefit if it's only striped for radarr queries? It seems like a general (or at least french) release naming/searching issue.

**Comment by garfield69** [comment]
Closing as stale.

**Comment by OpenPrunus** [comment]
@ilike2burnthing answer me. It's Sonarr scene mapping problem https://wiki.servarr.com/sonarr/faq#how-does-sonarr-handle-scene-numbering-issues-american-dad-etc.

Thank you !

Prunus
