### ISSUE TITLE
Adjust download url for easier log sanitizer

### ISSUE THREAD

**Issue by Taloth** [Jackett/Jackett#1638]
A request from Team Sonarr.

For a long time we've used some logic to remove sensitive information from Sonarr's log file entries such as apikeys, passkeys etc since users frequently post them on pastebin and forums.
However, the jackett download urls are hard to sanitize for two reasons:
- The apikey is part of the url path, instead of an &apikey= query param. Not very sensitive unless the Jackett instance is running remotely on a public IP, but worth noting.
- The 'path' query param contains an base64 encoded download url, which almost always contains the trackers api/passkey. This is obviously quite sensitive when posted publicly.

Example url: `http://127.0.0.1:9117/dl/indexername/flwjiefewklfjacketapikeysdfldskjfsdlk?path=we0re9f0sdfbase64sfdkfjsdlfjk&file=The+Torrent+File+Name.torrent`

I'd like to ask if these can be changed so Sonarr has an easier time to keep user's log pastebin-friendly.
Moving the apikey to an query param should be relatively easy to do.
For the 'path' param I can think of a few options:
- encrypt the param.
- store/cache the download url in Jackett and use an id instead.
- rename 'path' to something that's more unique for jackett, so Sonarr can identify the string and sanitize it.

Alternatively I could probably regex on /dl/*/{secret}?path={secret}&file=*, but that more error prone.

Lemme know if you'll consider adjusting it. Tnx.

**Comment by kaso17** [comment]
That sounds like a good idea.
Changed with 289c5cd24f51313c09883bc0d3f8238c2700f2c0
The apikey now moved to the jackett_apikey param and the path is encrypted.

DL links now look like this:
http://127.0.0.1:9117/dl/indexer/?jackett_apikey=12345&path=encryptedPath&file=example.torrent

**Comment by Taloth** [comment]
That'll work, I'll add 'jackett_apikey' as secret query param list. Here's the list we filter on atm: https://github.com/Sonarr/Sonarr/blob/816cf608fcef07e375aa750a863d0a7365108981/src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs#L12
