### ISSUE TITLE
[REQ] New Tracker – MVGroup

### ISSUE THREAD

**Issue by yllanos** [Jackett/Jackett#1640]
Can you please add support for MVGroup,
thanks.

Tracker Name : MVGroup
Type : Documentaries
Public tracker.
Indexer URL : MVGroup.org
Indexer language : English

**Comment by yllanos** [comment]
Not sure at thechnical level what to provide.

I believe they have a Tracker at: http://forums.mvgroup.org/maintracker.php

Most releases are handled by BitTorrent or ed2k

**Comment by flightlevel** [comment]
https://github.com/Jackett/Jackett/issues/315
