### ISSUE TITLE
HD4Free passes test, but.....

### ISSUE THREAD

**Issue by HitsvilleUK** [Jackett/Jackett#1641]
Running on 2 dedicated Linux servers and a Linux seedbox. HD4Free brings up zero results in manual search. Even just typing "The" gives no results.
Meanwhile having installed it on my Windows box at home to troubleshoot everything works fine. 
All 4 installs are running Jackett Version 0.7.1644.0 

This definitely only started about two or 3 days ago.. because I have been using HD4Free heavily over the last week.
I'm really not good at Linux but will figure out how to get any more info you need.

**Comment by flightlevel** [comment]
Full logs are needed ie `-t -l` from linux instance with the issue
Possibly its the mono redirect issue like in another issue but without logs we are just guessing

**Comment by HitsvilleUK** [comment]
Just to let you know that after a fresh OS install on one of the Linux systems, HD4free seems to work ok. 
Still not with the other two... but they were only temporary boxes anyway and will be cancelled. 
Will close the ticket.
