### ISSUE TITLE
Req: Save similar torrents to folder

### ISSUE THREAD

**Issue by pietervw** [Jackett/Jackett#1646]
I have a suggestion to help with cross seeding.

When a torrent is grabbed and similar torrents exists (or are made available later), output those .torrent files to a folder.

This folder can be the torrent client's watch folder to auto implement cross-seeding

**Comment by kaso17** [comment]
While I would love to see a proper replacement for my own cross seeding scripts this is beyond the purpose of Jackett.
Jackett is only a proxy/API. A cross seeding tool is a own project (which could use torznab/jackett as a source).
