### ISSUE TITLE
Filelist issue

### ISSUE THREAD

**Issue by sahara101** [Jackett/Jackett#1651]
Hello, 

I just installed sonarr on QNAP HS-251, also Jackett with filelist .
When I search for a show I get the following errors:

NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://192.168.1.78:9117/dl/filelist/Modified?path=aHR0cDovL2ZpbGVsaXN0LnJvL2Rvd25sb2FkLnBocD9pZD00NzEzNjgmdXNldG9rZW49MQ2&file=Sherlock.S04.1080p.AMZN.WEBRip.DD%2B5.1.x264-CasStudio.torrent]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00142] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:101 
  at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:223 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String torrentUrl) [0x00024] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\TorrentClientBase.cs:134 

Log in Jackett:

Error downloading filelist http://filelist.ro/download.php?id=471368&usetoken=1

From what I see sonarr is pulling the correct link, but jackett is adding &usetoken=1, which is used to download as freelech. Pasting the link on the tracker does not pop the download .torrent window, removing &usetoken=1 does.

Also, manually starting the download from sonarr is working.
I could not find what exactly the Manual download blackhole directory: is for?

Thank you!

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
Can't reproduce this.
But I suspect that when you have FL tokens (I don't have any) you've multiple download links on the search result page (one for normal download, one for FL token DL)?
fbbe4f9c451bb2bc10be52f9b41e80ea5ebff02d should fix it anyway.

**Comment by sahara101** [comment]
That is right. Is that an update or what should I do with the code? 
I tried to update but am receiving "Error checking for updates." 

Thanks

**Comment by kaso17** [comment]
the chagne is not yet released, a pre-release will be released soon.
