### ISSUE TITLE
Error loading Jackett settings, request to Jackett server failed

### ISSUE THREAD

**Issue by JourneyOver** [Jackett/Jackett#1656]
Installed the newest version of jackett and now I get "Error loading Jackett settings, request to Jackett server failed" whenever I go to jackett settings, anything I click on be it logs or whatever seems to just pop this error up without actually dong anything else. API key is completely void and all of my indexers are completely gone and I can't add anymore due to the error just popping up whenever I click a button..

Jackett version:  8.12
Mono version (if not using Windows):  

Running windows 10 x64
seems the last working version that works for me is v0.7.1662
-------------------------------

**Comment by MaDTaZ** [comment]
Hello All

I am having the same issue beleive it did an automatic update and now not working

running mono version

**Comment by AdditionalPylons** [comment]
Are you under a reverse proxy?

**Comment by flightlevel** [comment]
@JourneyOver How did you update? Running on Windows?

@JourneyOver @MaDTaZ Can you both in your browser, load the Jackett dashboard, press F12, hit the Sources tab, click on custom.js and paste the contents from line 1093
Alternatively, from your Jackett install folder, go to Content folder and paste the contents of custom.js file

**Comment by garfield69** [comment]
I have the same issue. I was on Jackett 0.7.1662 under windows7 x32 and had the *update to pre-release* check-box ticked. After auto-upgrade to 0.8.12 I am showing the same symptoms described by OP's first post .      
I also manually stopped the Jackett service and jackett tray and manually installed from `https://github.com/Jackett/Jackett/releases/download/v0.8.12/Jackett.Installer.Windows.exe` but this has not made a difference for me.     

screen shot of dashboard after 0.8.12 install:
![image](https://user-images.githubusercontent.com/6933240/29238801-40a1d3ba-7f90-11e7-87e0-43376188c9f7.png)

screenshot of the custom.js as requested:
![image](https://user-images.githubusercontent.com/6933240/29238787-eadc6116-7f8f-11e7-8928-70c03deb6d52.png)
and one from a formatted view just in case:
![image](https://user-images.githubusercontent.com/6933240/29238795-1694ada4-7f90-11e7-9976-93ef38a6eb3a.png)

Have reverted back to  0.7.1662 to restore functionality.

**Comment by garfield69** [comment]
addendum: output from `jackettconsole.exe -t -l`
[log0.8.12.txt](https://github.com/Jackett/Jackett/files/1219567/log0.8.12.txt)

**Comment by chibidev** [comment]
@garfield69 @flightlevel Relevant part of the log: ```08-12 19:19:08 Debug Response: {"Message":"No HTTP resource was found that matches the request URI 'http://127.0.0.1:9117/libs/api.js'.","MessageDetail":"No route data was found for this request."} ``` (I really don't get it...)
But that's definitely an old version of custom.js

Everyone experiencing this: when you navigate to Jackett, could you press Shift+F5 or Ctrl+Shift+R instead of doing a regular refresh? That invalidates cache and hopefully resolve the issue.

**Comment by garfield69** [comment]
Fantastic. Shift-F5 worked for me, the dashboard is now operational on 0.8.12 
Thanks.

**Comment by flightlevel** [comment]
Hope its that simple, but...
@garfield69 used the auto-updater and THEN manually installed
I'm wondering if the auto-updater actually updates the `Content` folder ???
Will have a go at trying to repro this

**Comment by chibidev** [comment]
@flightlevel I auto-updated my own server without a problem (couple times actually). It's running in docker on top of Unraid, but it shouldn't be that different for Windows machines as well. Anyway, thanks for giving it a go.

**Comment by qtv** [comment]
Having the same issue - error loading jackett settings, request to Jackett server failed. Shift+F5 did not work for me. Jackett Version 0.8.18.0

**Comment by flightlevel** [comment]
Couldn't repro my theory, worked perfectly on Ubuntu updating from stable to pre-release via auto-updater
Only very minor unrelated thing I found was the 'check for updates' in v0.8 gives a console error and isn't showing the bootstrap alert , but completely irrelevant to issue here
Next person that has this will have to try and see whats in custom.js from their Content folder to establish if its simply cache or file not getting updated

**Comment by seanvree** [comment]
I'm getting this issue. 

Shift + F5 did not work for me. 

Here's a link to my custom.js

https://gist.github.com/seanvree/1d9c50766cf90b047f330419fea6a6bb

**Comment by JourneyOver** [comment]
@flightlevel I've tried updating by going to the admin dashboard and checking for an update, and I've tried by just going to the releases tab of the repo and downloading the latest version, both ways have the issue.
(I've even tried uninstalling jackett completely/cleaning everything to do with jackett/restarting my computer and then reinstalling jackett without any luck)

but it looks like shift + F5 worked for me on fixing the issue.

**Comment by MaDTaZ** [comment]
This is from the f12 in browser    
    }).fail(function () {
            doNotify("Request to Jackett server failed", "danger", "glyphicon glyphicon-alert");
        });
1093    });

Code diectly from .js
            doNotify("Request to Jackett server failed", "danger", "glyphicon glyphicon-alert");
        });
1093    });

**Comment by chibidev** [comment]
@flightlevel I think I have tracked it down. The JS API wasn't ready to deal with the scenarios with base path override, so if someone had a prefix in their URL (e.g. /jackett/ in case of @seanvree) it will not load correctly...
Anyway, v0.8.25 should fix it, please give it a go @seanvree.

**Comment by MaDTaZ** [comment]
Just load new version and same thing for me.  Still will not find the settings
 Error loading Jackett settings, request to Jackett server failed

**Comment by seanvree** [comment]
@chibidev   - Confused by your comment - 

"e.g. /jackett/ in case of @seanvree"

Mine isn't set like that  - mine is " /jacket "   which has always worked .  I have my IIS rewrite rules set up for that as well.

**Comment by chibidev** [comment]
@seanvree The point is that on your machine any path for Jackett does not start at /, it starts at /jackett, so any API call must be prefixed with that path. In v0.8 there's a new API and the JS client was modified, however it couldn't handle these prefixes... 0.8.25 solves that and in your case instead of going to /api/v2/... it should go to /jackett/api/v2/....

**Comment by seanvree** [comment]
okay, cool @chibidev  I didn't know the API was modified.  Was just making a piont that it has alwasy worked that way. 
I'll udpate and let you know

**Comment by seanvree** [comment]
@chibidev  - looks to be resolved. I"m on Jackett Version 0.7.1644.0

**Comment by DrSeussFreak** [comment]
Windows 10
Jackett Version 0.8.26.0
Sonarr 2.0.0.4949

Half of my torrent sites no longer work, below is the error in Sonarr

![screen shot 2017-08-12 at 11 45 54 pm](https://user-images.githubusercontent.com/175500/29246222-83b449a8-7fb8-11e7-963f-485fd29d794b.png)

yet in Jackett they are all fine, per a test.  This all just started.

![screen shot 2017-08-12 at 11 48 12 pm](https://user-images.githubusercontent.com/175500/29246232-cb6c673a-7fb8-11e7-93f3-79b6939bb7fd.png)

Thoughts?

What I see in the Sonarr logs is

`v2.0.0.4949] NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [GET] at [http://10.0.1.50:9087/api/v2.0/indexers/eztv/results/torznab?t=tvsearch&cat=5030,5040,5070&extended=1&apikey=(removed)&offset=0&limit=100]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 94
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 302
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 288
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 315
<Error><Message>eztv does not support the requested query.</Message></Error>`

**Comment by MaDTaZ** [comment]
so before I upgrade again do I need to have my base path different then the default?

**Comment by D4rk56** [comment]
@MaDTaZ For me /jackett, same error
![bmebcvb](https://user-images.githubusercontent.com/13504808/29252302-a040c360-8064-11e7-9f33-bf5109bcfbf3.png)

**Comment by MaDTaZ** [comment]
Ya that is what I had and still cannot upgrade.

**Comment by chibidev** [comment]
Everyone getting HTTP error 400 and "xyz does not support the requested query", v0.8.49 probably fixes that. Please update and see if it's working.

**Comment by DrSeussFreak** [comment]
v0.8.49 resolved my issues

**Comment by chibidev** [comment]
@JourneyOver @MaDTaZ @seanvree @D4rk56 can you confirm that v0.8.49+ works for you as well?

**Comment by JourneyOver** [comment]
Things have been working fine for me since my last message (where i did a shift + F5), currently on 8.55 atm with no issues.

**Comment by D4rk56** [comment]
Yes

**Comment by MaDTaZ** [comment]
I will try the new version tonight

Cheers
Andie

**Comment by MaDTaZ** [comment]
Upgraded just now and confirmed working

Cheers
Andie

**Comment by dualznz** [comment]
Shift + F5 worked for me, loaded all indexers just fine
