### ISSUE TITLE
[BroadcastTheNet] NullReference

### ISSUE THREAD

**Issue by qtv** [Jackett/Jackett#1658]
Jackett version:  0.8.18.0 (Windows)

Cannot manually search. Logging turns up

`08-12 05:43:26 Error Error on 20170812054326 for BroadcastTheNet.txtSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Indexers.BroadcastTheNet.<PerformQuery>d__7.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\BroadcastTheNet.cs:line 101`

Removing BTN or searching in a category that is not used by BTN alleviates the issue.

**Comment by seanvree** [comment]
Me as well. 

Windows 10E 1703 X64

**Comment by DrSeussFreak** [comment]
Also have the same issue, same versions

**Comment by D4rk56** [comment]
same

**Comment by chibidev** [comment]
@DrSeussFreak @D4rk56 are you having issue with BTN or Jackett altogether? If latter, please #1656 and post your logs as well. Thanks.

**Comment by DrSeussFreak** [comment]
Mine is relevant to #1656, not BTN, posting logs there

**Comment by JigSawFr** [comment]
Tracker seems to be working great, I've just tested manual search with success.
`08-14 16:12:10 Info Manual search for "preacher" on BroadcastTheNet with 100 results. `
If you experience related problems with this indexer, please open an issue **with logs !**
Thank you

**Comment by kaso17** [comment]
this happened when BTN returned no results and was fixed via 8e1d321817f3a7c4dd19a30151256192d2bb3c71
