### ISSUE TITLE
[REQ] Xthor - French Tracker

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#166]
Thanks !

**Comment by Barracuda26** [comment]
Xthor will it be available on Jackett please ?

**Comment by smiro0** [comment]
Read how to ask for a new provider then ask again :)

It is in the wiki section.

**Comment by JigSawFr** [comment]
Now included.
See Commit https://github.com/Jackett/Jackett/commit/bfb58f53f5f3ff33ecceef8c64fc0df0cbc79ac3 and PR #295
