### ISSUE TITLE
No results with CouchPotato when providing imdbid

### ISSUE THREAD

**Issue by tchadawei** [Jackett/Jackett#1660]
Jackett Version 0.7.1644.0

I'm using CouchPotato which is providing both imdbid and title search. But it always get 0 results.

This will return 0 results :
http://mylocalip:9117/potato/kickasstorrent?imdbid=tt3896198&search=Guardians+of+the+Galaxy+Vol.+2+2017&user=&passkey=mypasskey

This will work :
http://mylocalip:9117/potato/kickasstorrent?search=Guardians+of+the+Galaxy+Vol.+2+2017&user=&passkey=mypasskey

I tried with different providers (Kickass Torrent and YGGTorrent), both does the same.

**Comment by tchadawei** [comment]
It looks like Jackett is actually expecting a parameter "imdb_id" rather than "imdbid".

But the specs from CouchPotota states that it should be "imdbid".
https://github.com/CouchPotato/CouchPotatoServer/wiki/Couchpotato-torrent-provider

Anyone experiencing a similar issue ?

**Comment by cloneMe** [comment]
To my mind, this issue duplicates this one: TorrentPotato doesn't find torrents #1606

**Comment by tchadawei** [comment]
I've been having a look into the code. It looks like if the provider is not defined as supporting imdb (in the Jackett/Content/Definitions folder), then any request with an imdbid parameter given will fail.

Maybe this imdbid should be left unused if the provider is not compatible.

**Comment by tchadawei** [comment]
I just made a PR : https://github.com/Jackett/Jackett/pull/1662
