### ISSUE TITLE
[MoreThanTV] stopped working

### ISSUE THREAD

**Issue by MrRobot12** [Jackett/Jackett#1667]
MTV stopped working with Sonarr as of a few days ago.

Indexers unavailable due to failures: MoreThanTV

17-8-11 21:48:05.0|Warn|HttpClient|HTTP Error - Res: [GET] http://127.0.0.1:xxxx/torznab/morethantv/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100: 400.BadRequest
<Error><Message>morethantv does not support the requested query.</Message></Error>
17-8-11 21:48:05.0|Warn|Torznab|MoreThanTV HTTP request failed: [400:BadRequest] [GET] at [http://127.0.0.1:xxxx/torznab/morethantv/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100]

**Comment by flightlevel** [comment]
MoreThanTv supports categories 2000 and 5000
Can you try with category 5000 in Sonarr?

![Image](https://i.snag.gy/5m6YuO.jpg)

**Comment by MrRobot12** [comment]
Do you mean the setting on Sonarr that says Edit - Torznab - Categories? 

I changed it from 5030,5040 to 5000 and it's working now. It's been working fine with the defaults 5030,5040 until now though. So, it's fixed?

Any idea why this change would be needed all of a sudden?

**Comment by chibidev** [comment]
@MrRobot12 there was a recent change in query validation, and in several cases the validation is stricter than before, so it might fail in cases it did not before.
I sense gaps in the Newznab API specification in this regard, so it is unclear to me whether a query to a  subcategory should look for results in the parent category as well... And vice versa. Happy to implement whichever if it becomes clear or someone can point me to the documentation.
@kaso17 can you help?

**Comment by kaso17** [comment]
Not sure why it stopped working, in the latest pre-release it's working again with 5030,5040 which is wrong in my opinion. We shouldn't search in parent categories if child categories are specified.
The MTV implementation doesn't care very much about categories and it seems like we're not filtering the results later.
Sonarr should be set to 5000
