### ISSUE TITLE
[FR] 2f4y.me

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#167]
Thanks!

**Comment by JigSawFr** [comment]
Maybe later, need a mapping to optimize time.

**Comment by raspdealer** [comment]
Will add it when I have some free time

**Comment by maxcore** [comment]
@raspdealer is good site ?

**Comment by raspdealer** [comment]
Just starting to discover

**Comment by maxcore** [comment]
the site was open for account ?

**Comment by raspdealer** [comment]
Got an invite.

**Comment by armani316** [comment]
Signup seems to be closed at the moment:
http://www.2f4y.me/account-signup.php

@raspdealer If a developer volunteers to add this tracker, maybe you can send them an invite (if you still have one)?

**Comment by raspdealer** [comment]
yes

**Comment by maxcore** [comment]
👍

**Comment by kaso17** [comment]
please send the invite to kaso1717 -at- gmail.com

**Comment by maxcore** [comment]
ah you got the invite ! ;) the email was already use ;)

**Comment by kaso17** [comment]
got the invite, thank you.

**Comment by raspdealer** [comment]
welcome

**Comment by kaso17** [comment]
added with ef09d9828ae3e9a43a80724c9d5c11c0eb33ff14

**Comment by ilrale** [comment]
Hi could it possible to got an invite ? 
ilrale988 -at- gmail.com 

Thx

**Comment by thecyril** [comment]
where can i still get invites ?
