### ISSUE TITLE
Search by URL improvements

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#1672]
Hi guys,

This new feature is working nicely except a small minor thing.
The results table displays "no result available" before the search ends.

You though it's finished without results but green symbol still turning.

Thx

**Comment by chibidev** [comment]
@JigSawFr so I guess I'm the web UI specialist now? 😄

**Comment by JigSawFr** [comment]
Oh sorry, I was thinking it's related to your commit, that's why you are tagged 😇

**Comment by chibidev** [comment]
Don't take this the wrong way, I have no issue implementing it, and you're right in a way that I was the one with the initial implementation. I just want to emphasize that I'm not really a frontend developer (although doing it for a couple years on the desktop), so if there's someone more qualified, I would have no issue letting it go :)

**Comment by kaso17** [comment]
@raspdealer is this still a problem in the latest pre-release? For me it it looks ok.
