### ISSUE TITLE
[Tasmanit.es] Not Working?

### ISSUE THREAD

**Issue by antigravity83** [Jackett/Jackett#1673]
Hi there,

I can't seem to pull any results from Tasmanit.es, even when there is applicable content available

For example- I just searched for "Australia Survivor S04E07", which is available in Tasmanit.es, but Jackett returns no results

Jackett Result: ![image](https://user-images.githubusercontent.com/27241813/29294218-a284e72c-8191-11e7-81c9-9ddb177ed9b8.png)
Tasmanit.es Torrent List: 
![image](https://user-images.githubusercontent.com/27241813/29294240-bd7d5f32-8191-11e7-8737-403737a6ac9f.png)

I am searching via Sonarr - and with the same search request, it is finding results from other Trackers via Jackett- so seems to be an issue specifically with Tasmanit.es

Sonarr Search Result: 
![image](https://user-images.githubusercontent.com/27241813/29294298-0c801f52-8192-11e7-8c5b-c0b49efa1430.png)

Jackett version: 0.7.1644.0
Ubuntu 16.04

**Comment by flightlevel** [comment]
Without logs its anyones guess?
If you have an invite, can have a look jackettapp AT gmail

**Comment by antigravity83** [comment]
Sorry, I checked logs and all I saw was what I pasted in the original issue. Didn't realise there was a detailed log option. Please see below.

Sonarr Debug Log: https://pastebin.com/MJVjhewf
Jacket Log: https://pastebin.com/tmZZvfKU

Searched for True Story with Hamish and Andy - S01E08 via Sonarr. 

Sonarr returns no results, but file is available on Tasmanit.es

![image](https://user-images.githubusercontent.com/27241813/29410468-e400d608-8393-11e7-8de0-f705325b1e2b.png)

**Comment by flightlevel** [comment]
Can you try copying this into your web browser and see if there is any results

`http://localhost:9117/torznab/tasmanit/api?t=tvsearch&cat=5000,5050,100055,100076,100016,100080,100017,100013,100015,100021,100022,100072,100023,100011,100008,100018,100014,100009,100010,100012&extended=1&apikey=8ir13nyhd8fc1rn69tfq09dacolphc04&offset=0&limit=100&q=True Story With Hamish Andy&season=1&ep=8`

**Comment by antigravity83** [comment]
This is what I get:

https://pastebin.com/uBY0xF6C

**Comment by kaso17** [comment]
From the HTML output from the log:
`Found 0 releases from Tasmanit for: True Story With Hamish And Andy S01E08`
In your screenshot it seems like file name used the "&" symbol but you're searching with "and". That might be the problem.

**Comment by antigravity83** [comment]
Thanks. I don't believe that's the issue though as I can't find any content on Tasmanit.es, regardless of the content name.

**Comment by kaso17** [comment]
then please post an updated log. Does the jackett manual search feature work?

**Comment by antigravity83** [comment]
Here's the logs searching for content mentioned in the original post (Four Corners).

Sonarr Results (note IPTorrents OK):
![image](https://user-images.githubusercontent.com/27241813/29484005-edcf1814-84f8-11e7-8231-d56640e7f4da.png)

Proof of availability on Tracker: 
![image](https://user-images.githubusercontent.com/27241813/29483981-6e8a0974-84f8-11e7-85b0-2a3770593d83.png)

Jackett Log:
https://pastebin.com/g5Ujb4aw

Sonarr Log (understand it is saying I already have a 720P version, but Sonarr will still find results when manually searching. As per screenshots above, it finds IPTorrents, but nothng ever from Tasmanit.es)
https://pastebin.com/SFVB87t4

**Comment by kaso17** [comment]
Does
http://localhost:9117/torznab/tasmanit/api?t=tvsearch&extended=1&apikey=8ir13nyhd8fc1rn69tfq09dacolphc04&offset=0&limit=100&q=Australian Survivor&season=4&ep=6 return any results?
what about manual search (from the jackett GUI)

**Comment by antigravity83** [comment]
This is the result I get when visiting that URL:
https://pastebin.com/M8CpQMf1

I get results when using the Jackett GUI- notice that the published date is a negative? Could that be the issue?
![image](https://user-images.githubusercontent.com/27241813/29485123-e23b1d24-850f-11e7-8ed2-dd5d114da248.png)

**Comment by antigravity83** [comment]
Full logs have been provided. Cheers

**Comment by kaso17** [comment]
Does https://tasmanit.es/browse.php?do=search&keywords=Australian+Survivor+S04E06&search_type=t_name&include_dead_torrents=yes
return any results?
according to the log it doesn't.
What must be changed to get the correct result?

**Comment by antigravity83** [comment]
No it doesn't return any results.

If I remove the . between the series name and the S**E** number, it returns a result.

So I'm thinking maybe it's the . that is causing the issue, but I've found a file on Tasmanit.es for another show I watch, the description doesn't have a . in it, but I can't get a result with it either. But I get a result when searching within Jackett. 

Pulse S01E05

Tasmanites Result:
![image](https://user-images.githubusercontent.com/27241813/29521720-101d845a-86ca-11e7-9615-9f965f290a9f.png)

Sonarr Results:
![image](https://user-images.githubusercontent.com/27241813/29521647-b4e68208-86c9-11e7-913e-d92cea254967.png)

Jackett Results:
![image](https://user-images.githubusercontent.com/27241813/29521693-e3f51a46-86c9-11e7-8210-f60aff151cb5.png)

I've double checked categories, they are correct. I've also tried narrowing down to single categories and tested them one by one, dont get results that way either.

Do you need logs for this example?

**Comment by antigravity83** [comment]
Searching for Pulse S01E05 which is available on Tasmanit.es

Jackett Log: https://pastebin.com/8tjPHfXt
Sonarr Log: https://pastebin.com/wfMGbWxv

Finds a results on IPTorrents, but not Tasmanit.es

Hope that helps - thanks

**Comment by kaso17** [comment]
Sonarr searchs for "Pulse 2017 S01E05" (with year) which results in no results.
This looks like a scene naming vs TvDB naming issue.

**Comment by antigravity83** [comment]
The same search returns results on other trackers though?

**Comment by antigravity83** [comment]
No matter what I search (have provided 3 examples with full logs), I cannot get a result from Tasmanit.es, but the same search returns results on other trackers (ie. IPTorrents).

**Comment by kaso17** [comment]
The IPTorrents search engine is pretty good. The Tasmanit engine seems to be pretty bad (needs an exact match).
Just try searching for "Pulse 2017 S01E05" on IPtorrents an Tasmanit directly.
7af8e1916e9dafb3b9586e30db4a651f7bf6600d should improve the situation a little for Tasmanit (your Australian Survivor) example should work now.

**Comment by antigravity83** [comment]
Many thanks @kaso17 - I've updated the file, and it's now picking up Australian Survivor in Sonarr. 

Other issues must be related to naming conventions used on Tasmanit.es (they're a mess)
