### ISSUE TITLE
[nyaa.si] Indexer missing.

### ISSUE THREAD

**Issue by supremacy2k** [Jackett/Jackett#1676]
In latest release, nyaa.si  indexer is missing.

Jackett Version 0.8.49.0

**Comment by JigSawFr** [comment]
Old definition was deleted and replaced.
See here: https://github.com/Jackett/Jackett/blob/08b471fd1e3208b1c0e73ce56a853437842d15ef/src/Jackett/Definitions/nyaasi.yml
You need to re-add this indexer.

**Comment by supremacy2k** [comment]
yes, and as i stated, the Indexer is MISSING.

See picture.
[http://imgur.com/a/JN411](Indexer completely missing in Jackett)
