### ISSUE TITLE
[FR] Le-paradis-du-net.com

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#168]
Thanks!

**Comment by JigSawFr** [comment]
I don't have account on this tracker, need invite and mapping to do it.

**Comment by raspdealer** [comment]
Will map it when free time, invites are opened now.

**Comment by maxcore** [comment]
if i find how can invite i will do @JigSawFr 

Ratio: 2.01

**Comment by raspdealer** [comment]
It's open!

**Comment by bidulle95** [comment]
personne n'aurais une petite invite pour moi svp pour ce tracker

**Comment by armani316** [comment]
Not sure if it's public or semi-private, but registration seems to be (always?) open:
https://le-paradis-du-net.com/signup.php?agree=yes&invitehash=

**Comment by kaso17** [comment]
added with c94679a9953a0aab5242663db53bfab88ca04db1

**Comment by armani316** [comment]
@kaso17 I believe it should be marked as 'Semi-Private' since it's always open for registration.

**Comment by kaso17** [comment]
changed with 39a52f2417b786ee362130a6896e4b1b533a0556

**Comment by armani316** [comment]
@kaso17 I think results need to be filtered more strictly on Le Paradis Du Net. I'm having the same issue here as some takers in #810

**Comment by kaso17** [comment]
Currently their database is down so I can't test.
Does it return completely irrelevant results or cause problems like #810 (problems with short movie names)

**Comment by armani316** [comment]
@kaso17 I believe it returns partially relevant results - the same issue that RockHard Lossless & WorldOfP2P used to have - so an andmatch might be required. For example, searching for Arrival 2016 returns other movies from 2016, and searching for Superior Donuts S01E01 returns S01E01 from other shows.

**Comment by kaso17** [comment]
this tracker seems to have shutdown, can someone confirm/deny?

**Comment by armani316** [comment]
@kaso17 I believe that's the case, yes, but I'm not 100% certain.

**Comment by kaso17** [comment]
removed 978ce0827f09d545c4a3efad14b581f55d90d062
