### ISSUE TITLE
[T411 V2] Test failed and return nothing 

### ISSUE THREAD

**Issue by Gromak123** [Jackett/Jackett#1683]
Hello, im on the latest version of Jackett (0.8.59) and it's seems that the T411 V2 indexer doesn't work anymore. here are  some enhanced logging of a test of the indexer : 
 

>  

When | Level | Message
-- | -- | --
Aug 18, 2017 01:20:58 AM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
Aug 18, 2017 01:20:58 AM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
Aug 18, 2017 01:20:58 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Aug 18, 2017 01:20:58 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
Aug 18, 2017 01:20:58 AM | Info | HttpActionBinding ExecuteBindingAsync
Aug 18, 2017 01:20:58 AM | Info | HttpActionBinding ExecuteBindingAsync
Aug 18, 2017 01:20:58 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 18, 2017 01:20:58 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 18, 2017 01:20:58 AM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
Aug 18, 2017 01:20:58 AM | Info | ApiControllerActionSelector SelectAction
Aug 18, 2017 01:20:58 AM | Info | ServerConfigurationController ExecuteAsync
Aug 18, 2017 01:20:58 AM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ServerConfigurationController
Aug 18, 2017 01:20:58 AM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ServerConfigurationController
Aug 18, 2017 01:20:58 AM | Info | DefaultHttpControllerActivator Create
Aug 18, 2017 01:20:58 AM | Info | HttpControllerDescriptor CreateController
Aug 18, 2017 01:20:58 AM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
Aug 18, 2017 01:20:58 AM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
Aug 18, 2017 01:20:58 AM | Info | http://XXX/api/v2.0/server/logs?_=1503012043979
Aug 18, 2017 01:20:54 AM | Info | IndexerApiController Dispose
Aug 18, 2017 01:20:54 AM | Info | IndexerApiController Dispose
Aug 18, 2017 01:20:54 AM | Info | Content-type='application/json; charset=utf-8', content-length=90
Aug 18, 2017 01:20:54 AM | Info | IndexerApiController ExecuteAsync
Aug 18, 2017 01:20:54 AM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Aug 18, 2017 01:20:54 AM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Aug 18, 2017 01:20:54 AM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Aug 18, 2017 01:20:54 AM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Aug 18, 2017 01:20:54 AM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Aug 18, 2017 01:20:54 AM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Test()'
Aug 18, 2017 01:20:54 AM | Error | ApiControllerActionInvoker InvokeActionAsync
Aug 18, 2017 01:20:54 AM | Error | ReflectedHttpActionDescriptor ExecuteAsync
Aug 18, 2017 01:20:54 AM | Info | Found 0 releases from t411 v2

**Comment by solspire** [comment]
t411 is t411.si now
Jackett support that ?
I would like t411 provider in "MYLAR" (automated downloader for comics)
If you have any recomandation..

**Comment by solspire** [comment]
I had create t411v2.yml in definition folder and paste the code for t411.si but 
i can't add this provider

**Comment by D4rk56** [comment]
@thebluepotato thanks !
