### ISSUE TITLE
IPTorrents not working?

### ISSUE THREAD

**Issue by Gershy13** [Jackett/Jackett#1686]
Im trying to get sonarr and radarr to connect with iptorrents and be able to search, but its not working...
Jackett comes up with an issue saying: Error: An error occurred while sending the request.

Anyone know what is going on and how i can fix it?

Thanks
Gershy13

**Comment by hotio** [comment]
Seems to be a problem on your end.

**Comment by Gershy13** [comment]
Any ideas on how I can fix it? I just realised I can't access their site
unless I use a VPN... Maybe I need to fix that first...

**Comment by kaso17** [comment]
If your provider blocks it you need to fix that first...

**Comment by Gershy13** [comment]
Yeah, is there anyway jackett can use unblocked links?

**Comment by Gershy13** [comment]
thanks, do you know of any unblock sites that do ipt??

**Comment by kaso17** [comment]
only use official mirrors, unblock sites are unsafe and most likely won't work.

**Comment by Gershy13** [comment]
do you know of any? i can only find unblock sites...

**Comment by hotio** [comment]
Can you go to the ip directly?

**Comment by Gershy13** [comment]
What is the IP?

On 21 Aug 2017 20:34, "hotio" <notifications@github.com> wrote:

Can you go to the ip directly?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Jackett/Jackett/issues/1686#issuecomment-323832155>,
or mute
the thread

**Comment by Gershy13** [comment]
So ive found mirrors that work, but i cant figure out how to add it into jackett. any ideas?

**Comment by DejaVu** [comment]
The section to specify an alternative URL for trackers has been removed in newer releases.
Can we get this back? Plenty of official mirrors to use, but no longer able to specify in Jackett.

Please bring back this option!

**Comment by kaso17** [comment]
@DejaVu it's possible to change the Site Link for all indexers in the current version.

**Comment by DejaVu** [comment]
I'm on Jackett Version 0.8.701.0, but adding IPT Torrents fails when pressing the spanner icon. It automatically tried to look for the address given before asking for a mirror and fails.

**Comment by garfield69** [comment]
@DejaVu  then try this hack:
1. shut down the Jackett service (or the jackettconsole)
2. edit the iptorrents.json file in the `%ProgramData%\Jackett\Indexers` on Windows or `~/.config/Jackett/Indexers` on Linux/macOS folder
3. and change the value in the sitelink block to whatever you need
current default `https://iptorrents.com/`, alternates which may or may not be valid
```
https://ipt-update.com/
https://iptorrents.eu/
https://nemo.iptorrents.com/
https://ipt.rocks/
http://ipt.read-books.org/
http://alien.eating-organic.net/
http://kong.net-freaks.com/
http://ghost.cable-modem.org/
http://logan.unusualperson.com/
http://baywatch.workisboring.com/
```
4. startup the jackett service and go.

**Comment by DejaVu** [comment]
This iptorrents.json file only gets created after the settings have been entered and excepted. 
In this folder I've only got the trackers that are currently working listed.

**Comment by kaso17** [comment]
You have to create it manually, see #1473
