### ISSUE TITLE
All indexers are KO...

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#169]
Since the last update, Sonarr returns that : 

16-1-8 18:12:41.2|Debug|Torznab|Downloading Feed http://192.168.1.116:9118/torznab/bluetigers/api?t=tvsearch&cat=5000,5030,5040,5070&extended=1&apikey=<removed>&offset=0&limit=100
16-1-8 18:12:41.2|Trace|HttpClient|Req: [GET] http://192.168.1.116:9118/torznab/bluetigers/api?t=tvsearch&cat=5000,5030,5040,5070&extended=1&apikey=<removed>&offset=0&limit=100
16-1-8 18:12:41.8|Trace|HttpClient|Res: [GET] http://192.168.1.116:9118/torznab/bluetigers/api?t=tvsearch&cat=5000,5030,5040,5070&extended=1&apikey=<removed>&offset=0&limit=100 : 200.OK (592 ms)
16-1-8 18:12:41.8|Trace|NzbDroneErrorPipeline|Handling Exception
16-1-8 18:12:41.8|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings.

**Comment by maxcore** [comment]
@raspdealer bluetigers was in maintenance

**Comment by raspdealer** [comment]
I have 3 trackers in the list...

**Comment by maxcore** [comment]
i see just bluetigers hehe

**Comment by maxcore** [comment]
@raspdealer why you dont use Sickrage ? all nice french is add with backlog ?

**Comment by duramato** [comment]
@maxcore just fyi SR supports jackett :P i use it myself

**Comment by raspdealer** [comment]
Because I'm using jackett?

**Comment by JigSawFr** [comment]
Yes, it's much appreciable to use Sonarr. But errors messages are only for bluetigers. Have you tested directly with Jackett these trackers ? Do you have log messages from other providers ?

**Comment by raspdealer** [comment]
Same for others...
16-1-9 22:02:25.5|Debug|Torznab|Downloading Feed http://192.168.1.116:9118/torznab/fnt/api?t=tvsearch&cat=5030,5040,5070&extended=1&apikey=<removed>&offset=0&limit=100
16-1-9 22:02:25.5|Trace|HttpClient|Req: [GET] http://192.168.1.116:9118/torznab/fnt/api?t=tvsearch&cat=5030,5040,5070&extended=1&apikey=<removed>&offset=0&limit=100
16-1-9 22:02:33.5|Trace|HttpClient|Res: [GET] http://192.168.1.116:9118/torznab/fnt/api?t=tvsearch&cat=5030,5040,5070&extended=1&apikey=<removed>&offset=0&limit=100 : 200.OK (7,975 ms)
16-1-9 22:02:33.5|Trace|NzbDroneErrorPipeline|Handling Exception
16-1-9 22:02:33.5|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings.
16-1-9 22:02:46.9|Debug|Torznab|Downloading Feed http://192.168.1.116:9118/torznab/torrentleech/api?t=tvsearch&cat=5030,5040,5070&extended=1&apikey=<removed>&offset=0&limit=100
16-1-9 22:02:46.9|Trace|HttpClient|Req: [GET] http://192.168.1.116:9118/torznab/torrentleech/api?t=tvsearch&cat=5030,5040,5070&extended=1&apikey=<removed>&offset=0&limit=100
16-1-9 22:02:47.6|Trace|HttpClient|Res: [GET] http://192.168.1.116:9118/torznab/torrentleech/api?t=tvsearch&cat=5030,5040,5070&extended=1&apikey=<removed>&offset=0&limit=100 : 200.OK (667 ms)
16-1-9 22:02:47.6|Trace|NzbDroneErrorPipeline|Handling Exception
16-1-9 22:02:47.6|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings.

**Comment by raspdealer** [comment]
I'm on raspbian with mono

**Comment by raspdealer** [comment]
Manual search for "blacklist" on BlueTigers, Fnt, TorrentLeech with 0 results.
No result found for your query, please try another search term ...

This is not normal...

**Comment by raspdealer** [comment]
I've readded all indexers and few are now working!
May be an indexers update wasnt retroactiv...
