### ISSUE TITLE
potatofeed

### ISSUE THREAD

**Issue by KennyVB** [Jackett/Jackett#1692]
Jackett version:  pre-release 0.8.67.0
Mono version (if not using Windows):  4.8.1

-------------------------------

my couchpotato fails in connection to jacket with the "either links don't work" 

at the torrent index I added I have this link 
http://10.0.1.36:9117/api/v2.0/indexers/hounddawgs/results/potato/

how ever couhcpotato says it returns a error when trying to connect to it
ERROR
[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.1.36:9117/api/v2.0/indexers/hounddawgs/results/potato/?imdbid=tt0103855&user=&passkey=xxx&user=&passkey=xxx
if I copy url I get this page

{
  "result": "error",
  "error": "An item with the same key has already been added."
}

when I use the "normal" release couchpotato doesn't even try to connect to jackett

**Comment by chibidev** [comment]
@KennyVB you have user and passkey twice in the URL, which is why Jackett gives you an error. All parameters should be passed exactly once.

**Comment by KennyVB** [comment]
I only pasted the http://10.0.1.36:9117/api/v2.0/indexers/hounddawgs/results/potato/ directly into couchpotato and nothing else :) but if what you said is true, then the problem is at couchpotato ?!?

**Comment by chibidev** [comment]
@KennyVB if that's the URL CP tries to open I'd say CP is the culprit here. It's probably reasonable to raise this issue for them as well.

**Comment by kaso17** [comment]
are you running an old version of CP?
Would have expected the movie title (besides the imdbid) in the URL too.

**Comment by KennyVB** [comment]
i'm useing latest version from GitHub - master

**Comment by KennyVB** [comment]
Still a issue.. I found out somehow a buddy of mine had "tried" to tweak the settings in couchpotato so I had to roll it back to 
[hpotato.core.plugins.base] Opening url: get http://10.0.1.36:9117/api/v2.0/indexers/hounddawgs/results/potato?imdbid=tt1346983&search=Loving+Leah+2009&user=&passkey=xxx

now it's even weirder !

ERROR : [hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.1.36:9117/api/v2.0/indexers/hounddawgs/results/potato?imdbid=tt1346983&search=Loving+Leah+2009&user=&passkey=xxx&search=Loving+Leah+2009&user=&passkey=xxx

**Comment by kaso17** [comment]
http://10.0.1.36:9117/api/v2.0/indexers/hounddawgs/results/potato?imdbid=tt1346983&search=Loving+Leah+2009&user=&passkey=xxx
Is valid and should return 0 results (not available on hounddawgs).

http://10.0.1.36:9117/api/v2.0/indexers/hounddawgs/results/potato?imdbid=tt1346983&search=Loving+Leah+2009&user=&passkey=xxx&search=Loving+Leah+2009&user=&passkey=xxx
Still adds all the arguments twice which is not correct but it should actually work with the latest version (as a side effect of 00027a41c1471a9c6a8ecd004b51a8869610c962)

**Comment by kaso17** [comment]
is this working now?

**Comment by cbruscato** [comment]
This is still happening.

### Steps to reproduce:
1. Configure Jackett in TorrentPotato
2. Search Movie
3. Results append user and pass twice in URL passed to Jackett

### Information:
Movie(s) I have this with: Baby Driver
Quality of the movie being searched: Any
Providers I use: Jackett
Version of CouchPotato: desktop: 3.0.1
Running on: Windows 10 Build 1703 64-Bit

### Logs:
```
09-17 04:04:38 ERROR [hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.1.24:9117/api/v2.0/indexers/thepiratebay/results/potato/?imdbid=tt3890160&user=&passkey=xxx&user=&passkey=xxx 
```

**Comment by kaso17** [comment]
the problem is that CP only send the imdb ID (which is not supported by TPB).
CP should add the search argument containting the movie name too.
E.g. http://10.0.1.24:9117/api/v2.0/indexers/thepiratebay/results/potato/?imdbid=tt3890160&search=Baby%20Driver&user=&passkey= should work.
As I don't use CP myself I don't know how to enable this behavior (maybe it's only enabled in the latest developer version).

**Comment by Telecart** [comment]
Did anyone manage to solve this? I still see two user/pass arguments passed to the query string via CP.  Also tried the temporary solution suggested [here](https://github.com/Jackett/Jackett/issues/1606) but it didn't seem to do anything.

To reiterate, from one of the more-recent releases (I can't say if it's been a month or two months or what but fairly recently), all potato feeds render this error in CP
`[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://127.0.0.1:9117/api/v2.0/indexers/NOMATTERWHAT/results/potato/?imdbid=tt1234567&user=&passkey=xxx&user=&passkey=xxx`

**Comment by kaso17** [comment]
Did you try opening an issue at CP?

**Comment by Telecart** [comment]
This was first result of googling the issue, I'm also pretty sure CP development is dead :/
Tried two different alternatives this weekend, nothing quite there yet unfortunately.

**Comment by oasisck** [comment]
I still have this issue with Jackett Version 0.8.737.0 and CP dae7327d35773c9eb62689c4609d8465abb31dea
CP from official FreeNAS plugin
Works with https://github.com/Ripolin/potatoygg but I prefer Jackett works

**Comment by kaso17** [comment]
dae7327d35773c9eb62689c4609d8465abb31dea seems to be a two year old stale branch, please change to the master/develop branch, it should fix the issue.

**Comment by oasisck** [comment]
I'm already on the master branch but i have issue when I want update CP. (I thought I was up to date, because CP display no update available)
I will create a proper jail and a hand installation, not by the freenas's plugin.
