### ISSUE TITLE
[bithdtv] No username  or password input Login again (Config)

### ISSUE THREAD

**Issue by bonk1990** [Jackett/Jackett#1697]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  5.2.0.215

-------------------------------
Hi, i have problem with Bit-HDTV cookie. I paste full cookie header but there is alert: "An error occured while updating this indexer
No username or password input Login again"

**Comment by kaso17** [comment]
cookie login was broken
fixed via 9928815777de81fe740d0d7084921d01958d89fe
