### ISSUE TITLE
[REQ] New Indexer - Speed-Share

### ISSUE THREAD

**Issue by tnascif** [Jackett/Jackett#1699]
Hi, any chance adding this brazilian tracker as na indexer ( http://speed-share.org/ ). I might be able to get an invite if needed.

**Comment by Guizzoni** [comment]
In currently working on this.

**Comment by tnascif** [comment]
@Guizzoni Great man! Since manicomio and BJ-share have the dates messed up, i really hope speed-share works like B2S-Share. tks

**Comment by kaso17** [comment]
@tnascif I assume you sent me the invite? I won't use it, feel free to reuse it for someone else.

**Comment by Guizzoni** [comment]
@kaso17 i'm already working on this

**Comment by Guizzoni** [comment]
@kaso17 is there a way to send a POST with "x-www-form-urlencoded" data in the search? 

This tracker uses a JS to show results on the page, the JS receives "x-www-form-urlencoded" data.

**Comment by kaso17** [comment]
@Guizzoni Just add "method: post".
Example: https://github.com/Jackett/Jackett/blob/master/src/Jackett/Definitions/chdbits.yml#L47
x-www-form-urlencoded should be the default for post.

**Comment by kaso17** [comment]
Does the JS call return HTML or JSON?
If it's JSON a native C# indexer is probably the better idea.
The cardigann format only works well for HTML parsing.

**Comment by Guizzoni** [comment]
@kaso17 yeah, i'm not receiving anything back after requesting in jackett, even with "method: post".

I'm receiving the following log after searching: 

> 08-28 20:28:26 Info JsonMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'JsonMediaTypeFormatter' for type='ManualSearchResult', mediaType='application/json; charset=utf-8'
System.Net.Http.Formatting: JsonMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'JsonMediaTypeFormatter' for type='ManualSearchResult', mediaType='application/json; charset=utf-8'
08-28 20:28:26 Info JsonMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'JsonMediaTypeFormatter' formatter
System.Net.Http.Formatting: JsonMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'JsonMediaTypeFormatter' formatter
08-28 20:28:26 Info DefaultContentNegotiator Negotiate Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8'
System.Net.Http.Formatting: DefaultContentNegotiator Negotiate Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8'

Apparently it returns a JSON... 
If that's the case it would be better if someone else made this, i'm not good with C#

**Comment by Guizzoni** [comment]
This is what i made so far:
[speed-share.zip](https://github.com/Jackett/Jackett/files/1258670/speed-share.zip)

**Comment by tnascif** [comment]
I just want to say that @garfield69 is my new favorite person!

**Comment by kaso17** [comment]
@Guizzoni 
sorry for the late response.
you've to use the multi path syntax for post:
```
search:
    paths:
      - path: buscar_tor.php
        method: post
```

**Comment by Guizzoni** [comment]
Thank you @kaso17 !
Created PR #2005

**Comment by tnascif** [comment]
Mine is not getting the quality info for some reason!
![untitled](https://user-images.githubusercontent.com/1376614/31967674-5ab1d782-b8ed-11e7-8c05-7e4a7e9ab448.jpg)

**Comment by Guizzoni** [comment]
@tnascif Yes, this is happening because Speed-Share doesn't bring quality info in the release title. I'm working on a fix for this.
