### ISSUE TITLE
Space in search URL (SceneAccess)

### ISSUE THREAD

**Issue by Nakebod** [Jackett/Jackett#170]
Hello,

So far I haven't been able to use Jackett, although I think my config etc is correct.
I think I've found a small bug with Jackett and SceneAccess. And hopefully also the cause. 

Running JackettConsole with debug options: JackettConsole.exe -t -l
System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Call(indexerID=sceneaccess)'
01-08 18:19:56 Debug UnixLibCurlWebClient:GetString(Url:https://sceneaccess.eu/all?search=Serie_Name S03E08&method=2)
01-08 18:19:58 Debug UnixLibCurlWebClient:GetString Returning OK =>

**What appears to be the problem?**
There is a space in the URL. Checking the debug output, and the search results, Jackett seems to be using the following URL: 
https://sceneaccess.eu/all?search=Serie_Name
This URL is not giving the correct results, at least not for this episode search :)

**Possible solution**
When I change the URL to (So replacing the space with %20) the results are as expected.
https://sceneaccess.eu/all?search=Serie_Name%20S03E08&method=2
So with my basic knowledge, I'd think that Jackett should replace spaces?

**Comment by JigSawFr** [comment]
@Nakebod seem that parameter of search is not encoded for URI.

**Comment by TouchMyBox** [comment]
Yeah, this is the same issue as https://github.com/Jackett/Jackett/issues/115 Jackett is only useful for grabbing stuff as it releases with this bug.

**Comment by Azerelat** [comment]
Let me know how this fix goes.

**Comment by TouchMyBox** [comment]
Looks good so far from my early impressions, thanks!

**Comment by Nakebod** [comment]
Updated to v0.7.118 and it is working! 
Thanks!

**Comment by raspdealer** [comment]
So you can close this one :)
