### ISSUE TITLE
[Awesome-HD] No Search results found

### ISSUE THREAD

**Issue by MaDTaZ** [Jackett/Jackett#1702]
Jackett version:  
Mono version (if not using Windows):  
Jackett Version 0.8.91.0
-------------------------------

Add this tracker and after adding it it has no search results.

**Comment by kaso17** [comment]
I don't think any developer has access to it and it hasn't been update for a long time.
Is the invite system currently open/can you provide one?

**Comment by MaDTaZ** [comment]
I don't have one right now but will let you know if open or invites available

**Comment by adamwinn** [comment]
@MaDTaZ I was unable to reproduce this.  It worked for me.  Can you post the full log?

**Comment by MaDTaZ** [comment]
Hey @adamwinn 

Looks like it was down at the time.  it is showing results now.

On thing that I noticed was that I have to add my cookie at least once week have you seen that?

**Comment by adamwinn** [comment]
@MaDTaZ No, not that I've noticed, but I don't use the tracker a lot
