### ISSUE TITLE
[SceneAccess] Long torrent titles are getting cut off in the middle

### ISSUE THREAD

**Issue by ladude626** [Jackett/Jackett#1708]
As the title states, long torrent names in SceneAccess is getting cut off in the middle of the name. It's not a big deal with manual search but with automated apps/scripts, sometimes the resolution of and the apps cannot parse the solution. Here's an example below. Looks like the underlying cause is not Jackett but SceneAccess's website.

Jackett's page:
![screen shot 2017-08-22 at 9 13 22 pm](https://user-images.githubusercontent.com/3040306/29595693-c757c9b4-877e-11e7-8ae4-e9b8a65af0de.png)

SceneAccess website:
![screen shot 2017-08-22 at 9 17 01 pm](https://user-images.githubusercontent.com/3040306/29595791-4ad32a22-877f-11e7-952a-a36856db9594.png)

I don't know how to fix it but I can point it out to someone who can. Instead of using the actual search result page's text which is cut off, there's a "title" in the html link which contains the full name:

    <a href="details?id=XXXXXX" title="Dolphins.in.the.Deep.Blue.Ocean.3D.2009.720p.BluRay.x264-PussyFoot"><b>Dolphins.in.the.Deep.Blue.Ocean.3D.2009....luRay.x264-PussyFoot</b></a>

**Comment by kaso17** [comment]
fixed via 947dbac48529a484ada6e78f52942335e8526abf, thank you
