### ISSUE TITLE
Exception in test_indexer [TorrentBD]

### ISSUE THREAD

**Issue by ShahadatRD** [Jackett/Jackett#1709]
Most probably the login form need some changes in Jacket console!

`

Aug 23, 2017 01:10:26 PM | Error | Exception in test_indexer
-- | -- | --
Aug 23, 2017 01:10:26 PM | Error | Error on 20170823131026 for TorrentBD.txtJackett.ExceptionWithConfigData: Login failed: No form found on http://www.torrentbd.com/torrent/account-login.php using form selector form[action="account-login.php"]    at Jackett.Indexers.CardigannIndexer.<DoLogin>d__15.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:line 426 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__25.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:line 1069     <html> <head><title>301 Moved Permanently</title></head> <body bgcolor="white"> <center><h1>301 Moved Permanently</h1></center> <hr><center>nginx/1.9.6</center> </body> </html>

`

**Comment by kaso17** [comment]
For some reason the cloudflare clearance cookie is not returned after solving the captcha. 
But I won't wast any more time with this tracker until they reduce their protection level.

**Comment by garfield69** [comment]
it just needed the site link to be switched to https, after which the form was found.
and the error test needed adjusting, looking for the wrong selector.
but since I don't have an account, I cannot test the login all the way, just as far as entering a username and password and getting the username-not-found error.
so if anyone can test and report back that would be useful. thanks.

**Comment by garfield69** [comment]
Jackett pre-release v0.10.785

**Comment by garfield69** [comment]
resolved. see #4781 for confirmation.

**Comment by garfield69** [comment]
https://www.torrentbd.net/ Site is offline due to maintenance.

**Comment by garfield69** [comment]
v0.22.372
