### ISSUE TITLE
Yggtorrent indexer : bad size returned

### ISSUE THREAD

**Issue by leloki** [Jackett/Jackett#1711]
Hi,

I would like to retport a bug in yggtorrent indexer, every results return 1B of size (and this is false of course).
This is inconvenient because Radarr tries to match the size with the desired quality.

If we force the download in jackett or radarr it work tough.

Thanks by advance and well done for all the work already done !!

Jackett version: 0.7.1644.0
Mono version (if not using Windows):  5.0.1.1

-------------------------------

**Comment by Khogniak** [comment]
Hello,

Already corrected here : https://github.com/Jackett/Jackett/pull/1635

Update the file manually or wait for next release update.
