### ISSUE TITLE
indexer dansihbits has a new format.

### ISSUE THREAD

**Issue by richardpoyner** [Jackett/Jackett#1715]
They have changed the rules.
You will be block if using the torrents.php. (it works but it will block you later)
The php link should be something like this:
{URL}/couchpotato.php?imdbid={imdbid}&search={querytext}&user={username}&passkey={key}

**Comment by kaso17** [comment]
what exactly is the problem?
In the latest pre-release danishbits is working fine for me.

**Comment by richardpoyner** [comment]
Where kan i get the pre-release?

**Comment by richardpoyner** [comment]
I have changed the text in the description.
I will test the pre-release first.

**Comment by kaso17** [comment]
Ok, this is the same as #1491
The current implementation is still working but still using the torrents.php as source.
i guess if you do to many requests it get's you banned for 3 hours.
We'll have to rewrite it to use the couchpotato API.

**Comment by richardpoyner** [comment]
Ok thanks. I will close this since i have overseen the other "same" issue. Sorry.

**Comment by kaso17** [comment]
The other one was your pull request which would have broken the current working implementation.
We'll keep this issue open for discussion.

**Comment by supremacy2k** [comment]
There is another issue here, from july 8th, regarding the same problem.

https://github.com/Jackett/Jackett/issues/1530

**Comment by richardpoyner** [comment]
Nope. It is the same issue.

**Comment by annonymous7913** [comment]
Any progress on this case? :)

**Comment by kaso17** [comment]
fixed via 108213f0983b51b534b5095ea0b0c4f7f7f5a905
