### ISSUE TITLE
[ Skytorrents ] Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by seabb** [Jackett/Jackett#1718]
Jackett version: 0.7.1644.0
-------------------------------

[ Skytorrents ] Found no results while trying to browse this tracker

Was working as of 22nd Aug 2017 (before the Skytorrents.in outage)

[log.txt](https://github.com/Jackett/Jackett/files/1249563/log.txt)

**Comment by JigSawFr** [comment]
`2017-08-25 00:15:57.5968 Debug Error while parsing DateTime "3 mins ago", using layout "01-02 2006" (MM-dd yyyy): String was not recognized as a valid DateTime. `

**Comment by kaso17** [comment]
already fixed in the latest pre release via #1626
