### ISSUE TITLE
Error when adding IPTorrents?

### ISSUE THREAD

**Issue by neobithia** [Jackett/Jackett#1719]
I did a search I couldn't find this issue.

I get this error when adding IPTorrents as an indexer:
![jackett error](https://user-images.githubusercontent.com/5649096/29687789-dfabb310-88da-11e7-8064-7f7ee4cb6322.jpg)

Log:  https://pastebin.com/eQ2mqWkD
Jackett Version: 0.7.1644.0
Mono version (if not using Windows):  running on Windows 8.1 Enterprise

-------------------------------

**Comment by kaso17** [comment]
`The remote name could not be resolved: 'iptorrents.com'`
Fix your DNS.
