### ISSUE TITLE
TorrentPotato support

### ISSUE THREAD

**Issue by duramato** [Jackett/Jackett#172]
Add TorrentPotato endpoint support for the following : 
HD-Space
HoundDawgs
SceneTime
Demonoid

**Comment by JigSawFr** [comment]
@duramato create a separate issue for each (and if they are private). Otherwise we can't view in one click tracker requested and there will be duplicated issue

**Comment by duramato** [comment]
@JigSawFr they are all on jackett already ,they just need to be mapped for TorrentPotato.

**Comment by JigSawFr** [comment]
@duramato ok, no problem, i don't use them :)

**Comment by Azerelat** [comment]
Its just a case of mapping the categories, if you do that then this will be done sooner rather than later.

https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker

**Comment by twistedroutes** [comment]
I've added movies to demonoid.

**Comment by flightlevel** [comment]
This issue is more than a year old. If the issue still exists, please reopen and include the specific indexers that are an issue 
Off topic: Very impressed with what they've done with Radarr in such a short time, supports torznab as well
