### ISSUE TITLE
[thepiratebay] An error occurred while sending the request: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /build/mono-5.2.0.215/external/boringssl/ssl/handshake_client.c:1132) (Test)

### ISSUE THREAD

**Issue by MarkLuk** [Jackett/Jackett#1721]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
Try running `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin` as root.
