### ISSUE TITLE
[yts] An error occurred while sending the request.: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. (Config)

### ISSUE THREAD

**Issue by Harath** [Jackett/Jackett#1724]
Not much to say really.
it was working before but recently i noticed some errors in radarr and i checked jackett and sure enough it wasn't working anymore.

Windows PC

[log.txt](https://github.com/Jackett/Jackett/files/1251921/log.txt)

**Comment by kaso17** [comment]
please try the steps from the Readme/Troubleshooting section

**Comment by Harath** [comment]
Obviously i tried those steps before i came and posted here.

**Comment by kaso17** [comment]
Then please enabele enhanced logging and post a new log.

**Comment by garfield69** [comment]
No reply.
Since I don't have any problems adding and using yts.am with 0.8.500 I'm closing this one.
