### ISSUE TITLE
[demonoid] String was not recognized as a valid DateTime. (Test)

### ISSUE THREAD

**Issue by risoftwi** [Jackett/Jackett#1729]
Unable to use Demonoid. I have attached a copy of the log file below.

[log.txt](https://github.com/Jackett/Jackett/files/1254383/log.txt)

Jackett version:  0.8.105.0
Mono version (if not using Windows):  5.0.0.100

-------------------------------

**Comment by JigSawFr** [comment]
Duplicate issue.

https://github.com/Jackett/Jackett/issues/1725
