### ISSUE TITLE
[thepiratebay] A task was canceled. (Test)

### ISSUE THREAD

**Issue by attzonko** [Jackett/Jackett#1733]
Can't get the TPB indexer to pass the test. Get a message: "A task was cancelled"

Jackett version:  0.8.105.0
Mono version (if not using Windows):  n/a (using Windows 10)
-------------------------------
Full Log:

When | Level | Message
-- | -- | --
Aug 27, 2017 03:19:02 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
Aug 27, 2017 03:19:02 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
Aug 27, 2017 03:19:02 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Aug 27, 2017 03:19:02 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
Aug 27, 2017 03:19:02 PM | Info | HttpActionBinding ExecuteBindingAsync
Aug 27, 2017 03:19:02 PM | Info | HttpActionBinding ExecuteBindingAsync
Aug 27, 2017 03:19:02 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 27, 2017 03:19:02 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 27, 2017 03:19:02 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
Aug 27, 2017 03:19:02 PM | Info | ApiControllerActionSelector SelectAction
Aug 27, 2017 03:19:02 PM | Info | ServerConfigurationController ExecuteAsync
Aug 27, 2017 03:19:02 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ServerConfigurationController
Aug 27, 2017 03:19:02 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ServerConfigurationController
Aug 27, 2017 03:19:02 PM | Info | DefaultHttpControllerActivator Create
Aug 27, 2017 03:19:02 PM | Info | HttpControllerDescriptor CreateController
Aug 27, 2017 03:19:02 PM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
Aug 27, 2017 03:19:02 PM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
Aug 27, 2017 03:19:02 PM | Info | http://127.0.0.1:9117/api/v2.0/server/logs?_=SECRETNUMBER
Aug 27, 2017 03:18:00 PM | Info | IndexerApiController Dispose
Aug 27, 2017 03:18:00 PM | Info | IndexerApiController Dispose
Aug 27, 2017 03:18:00 PM | Info | Content-type='application/json; charset=utf-8', content-length=61
Aug 27, 2017 03:18:00 PM | Info | IndexerApiController ExecuteAsync
Aug 27, 2017 03:18:00 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Aug 27, 2017 03:18:00 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Aug 27, 2017 03:18:00 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Aug 27, 2017 03:18:00 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Aug 27, 2017 03:18:00 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Aug 27, 2017 03:18:00 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Test()'
Aug 27, 2017 03:18:00 PM | Warn | ApiControllerActionInvoker InvokeActionAsync Cancelled
Aug 27, 2017 03:18:00 PM | Warn | ReflectedHttpActionDescriptor ExecuteAsync Cancelled
Aug 27, 2017 03:16:19 PM | Debug | IWebClient.GetString(Url:https://thepiratebay.org/recent)
Aug 27, 2017 03:16:19 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
Aug 27, 2017 03:16:19 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Test()'
Aug 27, 2017 03:16:19 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync
Aug 27, 2017 03:16:19 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Test()'
Aug 27, 2017 03:16:19 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Aug 27, 2017 03:16:19 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()'
Aug 27, 2017 03:16:19 PM | Info | HttpActionBinding ExecuteBindingAsync
Aug 27, 2017 03:16:19 PM | Info | HttpActionBinding ExecuteBindingAsync
Aug 27, 2017 03:16:19 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 27, 2017 03:16:19 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 27, 2017 03:16:19 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Test()'
Aug 27, 2017 03:16:19 PM | Info | ApiControllerActionSelector SelectAction
Aug 27, 2017 03:16:19 PM | Info | IndexerApiController ExecuteAsync
Aug 27, 2017 03:16:19 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.IndexerApiController
Aug 27, 2017 03:16:19 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.IndexerApiController
Aug 27, 2017 03:16:19 PM | Info | DefaultHttpControllerActivator Create
Aug 27, 2017 03:16:19 PM | Info | HttpControllerDescriptor CreateController
Aug 27, 2017 03:16:19 PM | Info | DefaultHttpControllerSelector SelectController IndexerApi
Aug 27, 2017 03:16:19 PM | Info | DefaultHttpControllerSelector SelectController Route='indexerId:thepiratebay,action:test,controller:IndexerApi'

**Comment by thebluepotato** [comment]
I can confirm the issue. However, I'm not able to reach https://thepiratebay.org/browse with my browser either. I'm guessing the task is cancel because of a request timeout.
This is almost certainly an issue on TPB's side (maintenance or overload).

**Comment by Concipient** [comment]
I am able to reach TPB via my browser, but I am still timing out via Jackett.

**Comment by thebluepotato** [comment]
@Concipient The url I gave probably wasn't the best example. I could already reach TPB's homepage, but you can't start a search (I got a 502 Bad Gateway).

**Comment by attzonko** [comment]
@thebluepotato I am able to access that URL without any issue from the same system running Jacket. 
I am also able to start a search, etc. At first I also thought it was an issue with TPB but that does not seem to be the case.

**Comment by thebluepotato** [comment]
I really don't wanna be a pest but there _really_ is an issue with TPB at the moment, globally:
 - http://currentlydown.com/thepiratebay.se
 - http://www.isitdownrightnow.com/thepiratebay.org.html
Both say it's down (with brief uptimes). Jackett's test worked once after a long delay, then failed again due to timeout. Since these tests worked, the definition is ok, it really is TPB. They're probably doing some maintenance. From the browser, I can search but there's a really long ping and although results show, the loading doesn't stop...
I say: let's wait a little more.

**Comment by attzonko** [comment]
@thebluepotato You are not being a pest in the least. What you said makes total sense. Thanks for checking this out. Makes sense to wait and see if it starts working again.

**Comment by metaMMA** [comment]
I am getting an error with TPB, as well. I figured more log information is better than too little log information, so I'll include mine below.

I am also thinking it might be related to TPB servers going down, because TPB would work fine for a couple hours, and then have an error. Rinse and repeat.

The error seems to be:
 `Error CardigannIndexer (thepiratebay): Error while parsing row........`

Followed by 
`System.Exception: Error while parsing ..........`

The parse errors were unique in each case, as you can see in the log linked [here](https://pastebin.com/Sfbs7tJ4). (IP address in log file is IP of VPN)

**Comment by thebluepotato** [comment]
YMMV, but for me https://thepiratebay.org/recent loads after 30s or so of just waiting for a response. Then a couple searches work ok, then it's again super slow, etc. My guess for now is that even when you can get search results, you can see it never stops loading so maybe Jackett wants the page to load completely (which it never does for now...).

**Comment by thebluepotato** [comment]
As of now, I've been able to browse normally and test & search using Jackett! Please test if it's working for you.

**Comment by garfield69** [comment]
this article https://torrentfreak.com/game-thrones-traffic-surge-slowed-pirate-bay-170830/ may 
 explanation for your recent problems at TPB

**Comment by attzonko** [comment]
Yup I see it passing the test now.
