### ISSUE TITLE
[REQ] SpeedTorrent Reloaded

### ISSUE THREAD

**Issue by pluusla** [Jackett/Jackett#1734]
Hi!

It would be great if there is any chance to add SpeedTorrent Reloaded (german content tracker) in jackett. 
I might be able to recruit (need more information from the staff) a new user.

URL: ~~https://speedtorrent-tracker.mine.nu~~ https://st-tracker.eu/

**Comment by kaso17** [comment]
added via eac11ab8077ca2279bdd11fbf80c6c9a4e728f6c

**Comment by garfield69** [comment]
```
After careful consideration, we have decided to
send ST-Tracker and the team into well-deserved retirement on September 1st, 2024.
```

**Comment by garfield69** [comment]
v0.22.545
