### ISSUE TITLE
[REQ] New Indexer AST4U

### ISSUE THREAD

**Issue by spadoinkle** [Jackett/Jackett#1735]
Hi!
An other request by me, hope it's ok. 

It would be great if there is any chance to add AST4U (german content tracker) in jackett.
Atm, I can not offer any invite.. sorry.. 

URL: https://www.ast4u.me

**Comment by kaso17** [comment]
If you know a little HTML/CSS you might want to try adding it yourself.
have a look at https://github.com/Jackett/Jackett/wiki/Definition-format

**Comment by spadoinkle** [comment]
@kaso17 

Thanks for the input. I have some very restricted basic know-how about HTML/CSS. 


I tried my best for adding all the needed information. Is there a way I can test this?

File is attached. 

[ast4u.txt](https://github.com/Jackett/Jackett/files/1256670/ast4u.txt)

**Comment by kaso17** [comment]
If you start Jackett one of the first lines of the output will show you where jackett looks for yml definition files (rename your file to ast4u.yml and place it in one of these directories, restart jackett and you should be able to add the indexer.

**Comment by spadoinkle** [comment]
@kaso17

Ok, I tried this. But it seems it doesn't work properly.... (getting Error in definitions and previously added trackers disappear when I add the ast4u.yml file) I attached the file, maybe with your know how, you'll get the source of mistake faster than me
[AST4u.txt](https://github.com/Jackett/Jackett/files/1261145/AST4u.txt)

 ;)

Thanks!

**Comment by kaso17** [comment]
the lats line is missing 10 spaces at the beginning (incorrect indention), after fixing it your disappeared indexers should come back.

**Comment by spadoinkle** [comment]
@kaso17 

Thanks for your input.

I added 10 spaces to the file. Now all the disappeared indexers are back. 
But I've another problem:
If I want to connect AST4u.me with my login credentials, I receive the following message:

>  An error occurred while updating this indexer
Login Failed, got redirected

I attached the logfile and the .yml file. Maybe you got an idea where's the source of this error is. 

[AST4u.txt](https://github.com/Jackett/Jackett/files/1267878/AST4u.txt)
[log.txt](https://github.com/Jackett/Jackett/files/1267879/log.txt)

**Comment by kaso17** [comment]
Try
```
    path: takelogin.php
    method: post
```

**Comment by spadoinkle** [comment]
Both suggestions didn't work... 

error for your first suggestion:

>  An error occured while updating this indexer
> Login failed: No form found on https://www.ast4u.me/takelogin.php using form selector form

error for your second suggestion:
>  An error occured while updating this indexer
> Der Wert darf nicht NULL sein. Parametername: uriString


[log.txt](https://github.com/Jackett/Jackett/files/1272025/log.txt)

**Comment by kaso17** [comment]
It looks like they're doing an redirect to an invalid location after login.
To debug it I'll need an account.

**Comment by spadoinkle** [comment]
I can provide you an invite.

Just need a Gmail-address.

**Comment by kaso17** [comment]
kaso1717@gmail.com

**Comment by spadoinkle** [comment]
@kaso17 sent.

**Comment by kaso17** [comment]
didn't receive anything

**Comment by spadoinkle** [comment]
@kaso17 check your email again.

**Comment by kaso17** [comment]
ok, got your email.
This is a working login block (returnto was missing).
```json
  login:
    path: takelogin.php
    method: post
    inputs:
      username: "{{ .Config.username }}"
      password: "{{ .Config.password }}"
      returnto: "/index.php"
    test:
      path: browse.php
```

**Comment by spadoinkle** [comment]
Yeah, thanks kaso17, login works now.

But the search doesn't return any torrents. It seems it can't find any files or data. 

Added the logfile. Maybe you got an idea, otherwise: no problem, thank you for your effort! 


[log.20170902.00002.txt](https://github.com/Jackett/Jackett/files/1272500/log.20170902.00002.txt)
[ast4u.txt](https://github.com/Jackett/Jackett/files/1272501/ast4u.txt)

**Comment by kaso17** [comment]
A few more selectors needed to be fixed.
Added via c8d974cf529975730679a0aef87c22e929351036
Thank you.
