### ISSUE TITLE
iptorrent

### ISSUE THREAD

**Issue by neiliid** [Jackett/Jackett#1745]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
please provide a proper error descirption

**Comment by neiliid** [comment]
Hi,

I am unable to download the .torrent files from IPtorrents, the search returns values and the account is valid. When using other trackers in Jackett, I am able to download the .torrent file

Jackett Ver: 0.8.124.0

IP download results.

No web page was found for the web address: http://localhost:9117/dl/iptorrents/?jackett_apikey=thekey&path=thepath&file=Junot+Diaz%2C+Cynan+Jones%2C+Mark+Haddon%2C+Sarah+Hall%2C+Cynan+Jones%2C+Toby+Litt%2C+Ali+Smith+-+Sunday+Times+EFG+Private+Bank+Short+Story+Award+2013+-+6+Shorts+(epub).torrent

where thekey is removed API key and thepath is a long string

**Comment by kaso17** [comment]
it's working fine for me, please provide an enhanced log.
