### ISSUE TITLE
XSpeeds and ImmortalSeed Not Working

### ISSUE THREAD

**Issue by antigravity83** [Jackett/Jackett#1746]
Jackett Version: 0.7.1644.0

Logs: https://pastebin.com/RNnhyvHe

Jackett is regularly failing to connect to Xpeeds and ImmortalSeed (please see logs).

**Comment by kaso17** [comment]
please try with the latest pre-release or wait for the new stable release (later today)

**Comment by antigravity83** [comment]
Updated to 0.8.128.0

Xspeeds still not working. Looks like my account has now been banned as a result. 

https://pastebin.com/0H6FVstu

**Comment by antigravity83** [comment]
I can log-in to my account from a different IP, so my account hasn't been banned. Maybe just the IP.

**Comment by antigravity83** [comment]
Further more, when I attempt to unblock the IP, it says no unblocked IP in database.

**Comment by kaso17** [comment]
For me Xspeeds login+search is working perfectly fine on Windows + Linux using 0.8.128.
The second log only shows that your IP is banned. Can't help you with that.

**Comment by antigravity83** [comment]
Ok thanks. At least I know it works.

**Comment by antigravity83** [comment]
Looks like Immortal Seed is still not working?

https://zerobin.net/?313ed12bd971eb2c#PkteiYFgyY582DLgF3K+2IkNSzArx2Hj5m0VaDXwsIs=

**Comment by kaso17** [comment]
http://immortalseed.me/ is down

**Comment by antigravity83** [comment]
Ah ok thanks sorry

**Comment by antigravity83** [comment]
XSpeeds still not working. I had my IP unblocked and Jackett (which is the only system I use to access trackers) is causing multiple login failures, and auto blocking my IP again.

https://pastebin.com/i8t3rypv

@Kaso17 are you able to get XSpeeds working on your end? Just trying to figure out if this is isolated just to me?

**Comment by kaso17** [comment]
yes, still working fine for me. Seems like no one else is having trouble either.
Not sure what's different about your account/IP.

**Comment by p145085** [comment]
Has Immortalseed been down for a couple of days or is there something wrong on my end? I get "DNS_PROBE_FINISHED_NXDOMAIN". IRC seems to be down as well.

**Comment by garfield69** [comment]
immortalseed has been down for at least 4 days.
Keep an eye on #13970 for any updates.
