### ISSUE TITLE
Dream team tracker dead?

### ISSUE THREAD

**Issue by kaso17** [Jackett/Jackett#1747]
http://dream-team.ml/

Is this tracker dead?
@valantislevas ?

**Comment by valantislevas** [comment]
2 days now it seems down.. let it 1-2 days to see please..
thanks.

**Comment by garfield69** [comment]
the dream-team.ml domain was re-registered on 22-08-2017 by Stichting OpenTLD, which appears to be a click bait company.

**Comment by kaso17** [comment]
anyone got any news?

**Comment by valantislevas** [comment]
yes i think is down for good if we have any news i will inform.. thanks!

**Comment by valantislevas** [comment]
just changed the address http://dream-team.ga/

**Comment by adamwinn** [comment]
@kaso17 You might want to revert commit a5cc7d9 then

**Comment by valantislevas** [comment]
its all the same only the domain has changed..

thanks @kaso17

**Comment by kaso17** [comment]
reverted and improved via e537e4976e6db6c36df285387fbd3302e0db6cac, thank you

**Comment by kaso17** [comment]
is this dead again or just a new domain?
