### ISSUE TITLE
Synology Jackett update?

### ISSUE THREAD

**Issue by king8084** [Jackett/Jackett#1748]
is there a way to update it? i been stuck with Jackett Version 0.7.1644.0 for a very long time, clicking "check for updates" does not update to anything after this version

**Comment by kaso17** [comment]
Have you tried upgrading during the last hour?
There hasn't been a stable update for almost a month. since ~1 hour you should be able to upgrade to v0.8.128 (stable). If it doesn't work please provide a log.

**Comment by king8084** [comment]
i just tried and for some reason now the entire jackett settings i had is gone and i am getting this

http://i.imgur.com/56MKh57.gifv

**Comment by king8084** [comment]
in one synology it did update to 0.8.1

and in my other one it stopped working

i will uninstall and reinstall

**Comment by king8084** [comment]
i uninstalled it but now i cannot install it back, it says port 9117 is taken, when i go to that path i get one gigantic error related to jackett

starting with

{
  "result": "error",
  "error": "Could not find a part of the path \"/volume1/@appstore/jackett/share/jackett/Content/index.html\".",

**Comment by king8084** [comment]
restarted synology, now i can install it, it says version is 0.7.1, i hit "check updates" i see in logs it says "0.8" available, i hit refresh, now it says this again

http://i.imgur.com/0xyxoox.gifv

**Comment by king8084** [comment]
well, doing the shift + f5 trick fixed it....

not sure if this is ok now or not
