### ISSUE TITLE
Jackett generate Torznab links with extra "/base/UI"

### ISSUE THREAD

**Issue by seanvree** [Jackett/Jackett#1750]
OS: Windows10E X64 1703
Jackett Version 0.8.128.0

When generating a Torznab link, links are generated in the following format:

```
http://localhost:9117/jackett/UI/jackett/api/v2.0/indexers/zetorrents/results/torznab/
```
I generated this while on the Dashboard at address: http://localhost:9117/jackett/UI/Dashboard which is what I get directed to when I go to localhost:9117

Screenshot:

![jackett](https://user-images.githubusercontent.com/8906637/29834233-13a3529c-8ca3-11e7-979f-053255bb357b.PNG)

**Comment by kaso17** [comment]
Your base path override should be /jackett (leading /)
I'm surprised it works that well without the /

**Comment by seanvree** [comment]
@kaso17  okay, in the previous version you told me to remove the "/"  .  

thanks,

**Comment by kaso17** [comment]
not sure why I recommended that

**Comment by kaso17** [comment]
1689c46c919fa8ab6154ea103072e6750a7a9e10 should avoid issues like this in the future.

**Comment by seanvree** [comment]
@kaso17  - thanks buddy.  Yeah, it was back a few weeks ago when peeps couldn't access the dashboard getting "server error" or something.  All good now.  Appreciate the work brother. Keep it up.
