### ISSUE TITLE
Error loading Jackett settings on 127.0.0.1

### ISSUE THREAD

**Issue by calexandre** [Jackett/Jackett#1751]
Hello,
Just updated to the latest version and i'm getting an error message on the UI Dashboard: "Error loading Jackett settings, request to Jackett server failed".

Tried again, but using **localhost** instead of **127.0.0.1** and it works.

**Comment by kaso17** [comment]
most likely a caching issue. Try reloading with Strg + F5 / Shift + F5

**Comment by calexandre** [comment]
Yep, you were totally right! :)
Thanks. Closing the issue.
