### ISSUE TITLE
Error loading Jackett settings, request to Jackett server Failed

### ISSUE THREAD

**Issue by jpichie** [Jackett/Jackett#1756]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.8.136 Pre-Release
Mono version (if not using Windows): 
-------------------------------

Good afternoon,
I am having trouble putting the correct logs as if I connect using http://localhost:9117 I can connect fine, and add indexers, but for advanced options i need to connect to http://127.0.0.1:9117.
If I connect using http://127.0.0.1:9117, All my servers settings are default, and I cannot open anything or make any changes, such as enhanced logging or adding indexers.

It was working fine until I finally upgraded from 0.7.xxx to 0.8.xxx
I have completely removed the application and C:\ProgramData\Jackett folder and reinstalled after reboot, and same issue.
Any help would be appreciated.
thanks

**Comment by thebluepotato** [comment]
Force refresh the page using Ctrl+Shift+R

**Comment by jpichie** [comment]
@thebluepotato 
I hate that that fixed the problem... I should have known to try that :)
thank you!

**Comment by thebluepotato** [comment]
@jpichie You're welcome and you're not the only one who's had issues! Please close this one since it's been resolved.
