### ISSUE TITLE
Request: have Jackett force refresh after an update

### ISSUE THREAD

**Issue by thebluepotato** [Jackett/Jackett#1757]
Seeing the issues #1756, #1751, #1675, and #1656 are all related to Jackett needing a forced reload (Ctrl+Shift+R or Shift+F5) after "big" updates to the API, should Jackett do it automatically after updates? I've just updated to the latest pre-release (0.8.136.0) and also had to force refresh for the "multi-tracker" and "multi-categories" dropdowns to work.
So, more precisely:
 - Can Jackett detect that it has just been updated?
 - Can Jackett tell the browser to force refresh?

I think this would be a nice addition, especially since many people will face these issues now that there's a release with the new API (and not only a pre-release anymore). What do you think?

**Comment by kaso17** [comment]
Thank you for bringing this up.
We could do a `location.reload(true);` if the server version changed (compared to a cookie/local storage). But that would force a reload even if there is no change. I think the easiest way of fixing is is to simply add a ?changed=2017083101 parameter to the JS/CSS includes and adjust them if we change something  in the corresponding files.
@flightlevel @chibidev @JigSawFr what's your opinion regarding this?
Can we automate this via the AppVeyor build process?

**Comment by chibidev** [comment]
@kaso17 based on https://stackoverflow.com/questions/5721704/window-location-reload-with-clear-cache ``location.reload(true);`` probably wouldn't work for Chrome. Chrome uses very aggressive caching and has an in-memory cache for each tab, so if you do subsequent refreshes (either manually or programmatically) it will reuse from memory.
This is something we should test. I've found little documentation about how Chrome decides to use the in-memory cache or reload the resource, so it is a little bit unclear whether the Cache-Control headers have any effect on that.

**Comment by kaso17** [comment]
I added a dummy changed arguments via 9e9deb17c7aa436ee4ae6b3e752122fec29cec58.
That works as expected. We just have to make sure to update them when we change the corresponding files.

**Comment by flightlevel** [comment]
Good solution and once we go .net core should be able to just swap them with `asp-append-version="true"` https://www.constructcode.com/post/cache-busting-in-asp-net-core

On .net core, have a really busy month ahead but will then have another crack (unless someone else wants to) starting again from current master and making small commits so its easy to follow

**Comment by kaso17** [comment]
closing this as it's "fixed", once we moved to .net core we should use the asp-append-version option
