### ISSUE TITLE
IPTorrents - Proxies, not working

### ISSUE THREAD

**Issue by neiliid** [Jackett/Jackett#1759]
A number of ISPs have blocked access to IPT, however the site has published a series of non-ssl proxies that can be used instead. It is possible to access IPT via the proxy from the Jackett box.

When trying to configure Jackett with one of these proxies, the system reports that it is unable to add the tracker. I have redacted the specific Proxy URL for privacy reasons.

log:

Aug 31, 2017 09:04:10 AM 	Debug 	IWebClient: Returning OK => 7949 bytes
Aug 31, 2017 09:04:10 AM 	Debug 	IWebClient.GetBytes(Url:http://alien.REDACTED.net/t)
Aug 31, 2017 09:04:10 AM 	Debug 	IWebClient: Returning Redirect => http://alien.REDACTED.net/t 0 bytes
Aug 31, 2017 09:04:10 AM 	Debug 	IWebClient.GetBytes(Url:http://alien.REDACTED.net/)
Aug 31, 2017 09:04:10 AM 	Debug 	IWebClient: Returning Redirect => http://alien.REDACTED.net/ 
Aug 31, 2017 09:04:10 AM 	Debug 	UnixLibCurlWebClient: Posting username=REDACTED&password=REDACTED&g-recaptcha-response=
Aug 31, 2017 09:04:10 AM 	Debug 	IWebClient.GetString(Url:http://alien.REDACTED.net/take_login.php)
Aug 31, 2017 09:04:10 AM 	Info 	ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Config(config=Jackett.Models.DTO.ConfigItem[])'
Aug 31, 2017 09:04:10 AM 	Info 	ApiControllerActionInvoker InvokeActionAsync Action='Config(config=Jackett.Models.DTO.ConfigItem[])'
Aug 31, 2017 09:04:10 AM 	Info 	RequiresIndexerAttribute OnActionExecutingAsync

**Comment by kaso17** [comment]
All of the new official mirrors are working perfectly fine for me.
It seems like you're running an old mono version resulting in a libcurl use.
Please try updating to mono > 5 first.

**Comment by neiliid** [comment]
Thanks, will try. Did an upgrade of mono from 4 to 5, but that caused sonarr and jackett to stop working completely. Had to roll back. Will wait for the repository update for ubuntu 17.04.
