### ISSUE TITLE
Cannot add Beyond.HD

### ISSUE THREAD

**Issue by duramato** [Jackett/Jackett#176]
Whenever i try to add it, i get "Configuration failed: Your cookie did not work: Your cookie did not work" after pasting the cookie

**Comment by ipsq** [comment]
You need to connect to Jackett using an SSH tunnel and access Jackett over localhost so you can sign in using your username, password and captcha. 

#35

**Comment by duramato** [comment]
Any guide on how to do it?

**Comment by ipsq** [comment]
`ssh -L 9117:localhost:9117 root@yourserversip` then go to localhost:9117 in your browser and do the login and captcha.

**Comment by duramato** [comment]
Thanks that worked, i was trying to tunnel port 80, was thinking i needed to acess the site itself from there
Perhaps add a little not on the add site?
