### ISSUE TITLE
Error adding SceneTime to Sonarr

### ISSUE THREAD

**Issue by un4gvnbb** [Jackett/Jackett#1763]
When trying to add SceneTime I get the following error.
An error occured while updating this indexer
Exception (scenetime): Value cannot be null. Parameter name: input: Value cannot be null. Parameter name: input

I've already verified that the username and password are correct and I've passed the captcha.

Jackett version:  0.8.128.0
[Jackett Error Log.txt](https://github.com/Jackett/Jackett/files/1268770/Jackett.Error.Log.txt)

-------------------------------

**Comment by Kranzy** [comment]
Im having the same issue.

**Comment by kaso17** [comment]
Caused by the release "Grand Theft Auto V EUR PS4-​TCD" which had no category. 
Fixed via 1cd0358531f1836a104613e012f7d8bfa88f2c06

**Comment by un4gvnbb** [comment]
@kaso17 Thanks, worked for me
