### ISSUE TITLE
Blackhole download fails due to mixed content when used through Apache reverse proxy with HTTPS

### ISSUE THREAD

**Issue by incorpusyehtee** [Jackett/Jackett#1764]
This is probably me not knowing how to use Apache's reverse proxy features properly, but maybe someone here knows how to fix this without modifying Jackett itself. Much thanks in advance.

### Apache config
```
RewriteEngine on 
ProxyRequests on
ProxyPreserveHost on

<Proxy *>
    Order deny,allow
    Allow from all
</Proxy>

<Location "/example">
    ProxyPass				http://localhost:9117/example/
    ProxyPassReverse		http://localhost:9117/example/
</Location>

```

### Jacket config
```
{
  "Port": 9117,
  "AllowExternal": true,
  "APIKey": "something",
  "AdminPassword": null,
  "InstanceId": "whatever",
  "BlackholeDir": "C:\\crap",
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": "/example",
  "OmdbApiKey": ""
}
```

### Description of issue

All functions work perfectly over HTTP/HTTPS reverse proxy with Apache, except for downloading to the torrent blackhole over HTTPS. When visiting https://website.tld/example/, seeing all the Jackett interface and whatnot, clicking the blackhole download button produces "Request to Jackett server failed"

In Firefox this console message is generated:
`Blocked loading mixed active content “http://localhost/example/bh/tracker/?jackett_apikey=key&path=path&file=torrent.torrent&_=number”[Learn More]`

Chrome produces this console mssage: 
```
Mixed Content: The page at 'https://localhost/example/UI/Dashboard#search=nothing&tracker=&category=' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost/example/bh/tracker/?jackett_apikey=key&path=path&file=torrent.torrent&_=number'. This request has been blocked; the content must be served over HTTPS.
send @ jquery.min.js?changed=2017083001:4
```

JackettConsole.exe produces the following output:
`it doesnt produce an output`

Also as an aside: This might sound really dumb, considering the lineage and motivation behind Jackett, but would anyone be willing to take a commission to implement showing NZBs.org results or like NZBHydra results in-line with torrent results? I just want to be able blackhole torrents and NZBs from one UI that works as well as Jackett does. Maybe $150?

**Comment by kaso17** [comment]
This is caused by the reverse proxy HTTPS => HTTP setup.
See #1464
It was just fixed.

Regarding your NZB integration request: I never used NZBs and don't know how it usually works. So I can't comment on the idea.
Please open another issue for it.
