### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): An error occurred while sending the request: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by ndkid1986** [Jackett/Jackett#1767]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
please include a full log

**Comment by garfield69** [comment]
I'ts been a month and no reply from the OP.  So I'm closing this ticket. The OP can open a new one (and provide full logs) if they want future help on this topic.
