### ISSUE TITLE
[yggtorrent] Login failed: Selector

### ISSUE THREAD

**Issue by vitrioldrinker** [Jackett/Jackett#1768]
When clicking Okay after entering credentials, This error pops up : 

> Login failed: Selector "a[href="https://yggtorrent.com/user/logout"]" didn't match

Nothing appears in log

Jackett version:  0.8.128.0
Mono version (if not using Windows):  5.2.0.215-0xamarin10+debian8b1

-------------------------------

**Comment by kaso17** [comment]
@Khogniak can you have a look?

**Comment by thebluepotato** [comment]
I had this tonight too but going to the page with the browser showed they were actually under maintenance. Config and testing successful just now, so I think everything is in order.
