### ISSUE TITLE
Jackett GitHub Labels.

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#177]
Hi admin,

Is it possible to get rights to add labels?
or to give this right to an active contributor?

Labels usage is not picky and I can do it if needed.

Thanks

**Comment by Azerelat** [comment]
We appreciate all input and help to the project but Github has no permission levels meaning I can't allow for editing issues without allowing everything else too.  

As the auto updater pulls from the release page people we have to very tightly control who can make release in the project as there is the potential for malicious code being pushed out.  Perhaps we should  make a separate project just for issues as is the case for Sickrage.

**Comment by raspdealer** [comment]
Yes may be it can be a solution, it's a shame that github doesnt support user rights :-1:

**Comment by raspdealer** [comment]
@Azerelat  Have you took a decision? How can I help to clean this...?

**Comment by Azerelat** [comment]
I think JigSaw is all over this ;D
