### ISSUE TITLE
[demonoid] Please click on the captcha box to prove you are human (Config)

### ISSUE THREAD

**Issue by JediBrooker** [Jackett/Jackett#1770]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
they changed the login method, needs to be updated

**Comment by kaso17** [comment]
Recaptcah support has been added via c544de8fed61478ee06c93366df6aaf835591a3f
But they also added incapsula ddos protection and I'm not getting back a cloudflare style java script challenge. This probably will be a bigger project.

**Comment by kaso17** [comment]
If someone can help with reverse engineering this, that would be very much appreciated.

**Comment by kaso17** [comment]
Is this still a problem for anyone?
It's working fine for me again.

**Comment by garfield69** [comment]
demonoid working for me on my win7 platform.

**Comment by kaso17** [comment]
works for me and I wasn't able to get any captcha
