### ISSUE TITLE
Add Scene Rush ( PT-PT) private tracker on Jackett

### ISSUE THREAD

**Issue by luckyzor** [Jackett/Jackett#1775]
Hello everybody :)
I'm wondering if it was possible to add this tracker to jackett. There are only one pt-pt in jackett so a second one it will be nice. Tell me if you need some informations.
Thanks alot and btw i love jackett you have done a really nice job ;)

**Comment by luckyzor** [comment]
http://www.scene-rush.pt/ here the site.

**Comment by napalmpt** [comment]
I would like this also. thanks.

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by luckyzor** [comment]
Unfortunately I don't have that kind of skills, Can tell you neither if there are any kind of API.
What do you need to add this tracker to jackett? Invitation? 

Thanks for the help

**Comment by garfield69** [comment]
registration currently closed. invite required.

**Comment by garfield69** [comment]
If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by napalmpt** [comment]
sorry but currently I can't send invite, maybe in a few weeks... thanks.

**Comment by napalmpt** [comment]
I sent you the invite now.

**Comment by garfield69** [comment]
Registration and login successful. Thank you.

**Comment by luckyzor** [comment]
@garfield69 can you please update when and if it works?

Thanks for your help

**Comment by garfield69** [comment]
try Jackett v0.10.880

**Comment by napalmpt** [comment]
Thanks. it is working excelent.

**Comment by garfield69** [comment]
https://www.scene-rush.pt/ returning ERR_CONNECTION_TIMED_OUT
is the site gone, broken or moved to a new domain?

**Comment by napalmpt** [comment]
The site has been down today for me too...

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
@napalmpt or @luckyzor are you still able to access your accounts? The site is up, but my account isn't recognised. I was able to access it roughly a week ago, so I'm just confused.

**Comment by luckyzor** [comment]
its working for me.

**Comment by napalmpt** [comment]
working for me too. maybe you got banned? what's the error?

**Comment by ilike2burnthing** [comment]
Thanks both. Yea, I'm assuming I got banned, but I've definitely had access to the account without issue for the last few weeks, and not broken any rules that I'm aware of.

Login says my username or password are incorrect (they're not), and when trying to reset the password the email address isn't found.

If either of you could message the staff a link to this message, it would be much appreciated.

---

Username: `nahik99374`
Email: `jacketttest AT gmail DOT com`
Registered: 14/06/2021 21:16 UTC

I'm one of the maintainers here, so having an account would be useful for ensuring continued support for SceneRush members, like those above.

Thanks again!

**Comment by ilike2burnthing** [comment]
Don't suppose either of you got word back from the admins?

**Comment by lmrqs** [comment]
> working for me too. maybe you got banned? what's the error?

Napalmpt, achas que me podes convidar? ando há meses a tentar encontrar alguém, luiscpt279 at gmail.

Grande abraço
