### ISSUE TITLE
[yggtorrent] An error occurred while sending the request: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /tmp/source-mono-d15-3/bockbuild-d15-3/profiles/mono-mac-xamarin/build-root/mono-x64/external/boringssl/ssl/handshake_client.c:1132) (Config)

### ISSUE THREAD

**Issue by Eldoc62** [Jackett/Jackett#1777]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  5,2

-------------------------------

**Comment by kaso17** [comment]
Following the steps from The `Readme/Troubleshooting/Unable to connect to trackers with invalid SSL certificates` section should fix your problem.
