### ISSUE TITLE
Installed Jackett, can not get to admin page

### ISSUE THREAD

**Issue by energyczar** [Jackett/Jackett#178]
I'm in need of some help!

I installed Jackett on Windows 10 without an issue, I was able to get to the admin dashboard to begin setting things up. I noticed there was an option to change the port, add a password, and make it available externally. I tried to change the port to 38086, but now I can no load Jackett. I tried to uninstall the program, and install it again. It goes through the install process and completes, but I can not load Jackett on http://localhost:9117/Admin/Dashboard and if I right click the icon in the tray it attempts to go to port 38086 even after the uninstall. Is there a configuration file somewhere that I need to delete so I can just do a clean install again.

Thanks for the help and sorry if this is not the correct place to post this, I did try looking online first  :-)

**Comment by Azerelat** [comment]
Firewall?

Delete C:\ProgramData\Jackett\ServerConfig.json to reset the config, if there is a permission issue closing the app or service then running the console exe as admin may help.

**Comment by energyczar** [comment]
Thank you very much! That did the trick. Great Program!!
