### ISSUE TITLE
[New Tracker REQ] nnm-club.me

### ISSUE THREAD

**Issue by ffuubarbuzz** [Jackett/Jackett#1780]
One of the biggest provider of russian content.

**Comment by garfield69** [comment]
https://nnmclub.to/ returning 502 Bad Gateway

**Comment by garfield69** [comment]
online.

**Comment by ilike2burnthing** [comment]
https://nnmclub.to/ - 500 Internal Server Error

**Comment by garfield69** [comment]
Both the public and semi indexers are working for me.

**Comment by ilike2burnthing** [comment]
https://nnmclub.to/ - Error 1033 - Argo Tunnel error

**Comment by garfield69** [comment]
online
