### ISSUE TITLE
Jackett on synology always crashes if it loses it internet connection

### ISSUE THREAD

**Issue by king8084** [Jackett/Jackett#1781]
if anything happens to the internet connection even for 10 seconds, jackett status become "stopped"

**Comment by kaso17** [comment]
can you share a log of such a crash?

**Comment by king8084** [comment]
cant share atm, i will need to edit a lot of the info out, but you can reproduce it 100% of the time, just stop the internet connection to synology for 1 minute and jackett crashes, i tried this on 3 different synology and 100% of the time jackett crashes

**Comment by Moulde** [comment]
Don't have a synology :)
