### ISSUE TITLE
[karagarga] Found no results while trying to browse this tracker 

### ISSUE THREAD

**Issue by savahu** [Jackett/Jackett#1783]
My syslog is filled with exceptions from this indexer.

Jackett version:  0.8.140.0
Mono version (if not using Windows):  Mono JIT compiler version 5.2.0.215 (tarball Mon Aug 14 15:46:23 UTC 2017)

-------------------------------
Log is attached:
[jackettlog.txt](https://github.com/Jackett/Jackett/files/1276453/jackettlog.txt)

**Comment by kaso17** [comment]
@adamwinn can you have a look at it?
I don't have access.

**Comment by adamwinn** [comment]
@kaso17 I can try but last time I tried to do some dev work on Jackett, my local instance just stopped showing the tracker listings on the main page.  I couldn't add, delete, view, etc any trackers.  I was basically dead in the water after that

**Comment by adamwinn** [comment]
I finally got my dev environment working again.

I was still on an old version and this worked fine.  I could not reproduce the error.  Then I upgraded to the latest and the error happened, so something introduced it.  I'll take a look.
