### ISSUE TITLE
Install jackett as a service (OSX)

### ISSUE THREAD

**Issue by Eldoc62** [Jackett/Jackett#1784]
Hello,

Resolved 👍 

The solution :
----------------------------------------
1 Open Terminal
2 Copy and paste cd /YOUR_ADRESS/Jackett/
3 Press Enter (it shouldn't show anything particular)
4 Copy and paste ./install_service_macos.sh
5 Press Enter (it should say that the agent was successfully installed)
----------------------------------------

I can not install Jackett as a service: /

Here's what I tested:

cd / Volumes / Macintosh \ 2TO / Log \ 's / Apple / Mac / Jackett / JackettConsole.exe ./install_service_macos.sh

/ Volumes / Macintosh \ 2TO / Log \ 's / Apple / Mac / Jackett / JackettConsole.exe ./install_service_macos.sh

/ Volumes / Macintosh \ 2TO / Log \ 's / Apple / Mac / Jackett / JackettConsole.exe / install_service_macos.sh

I do not find...

Please tell me the correct order

**Comment by kaso17** [comment]
only go to "/ Volumes / Macintosh \ 2TO / Log \ 's / Apple / Mac / Jackett / "
no JackettConsole.exe

**Comment by Eldoc62** [comment]
Ok so if i take that 

/Volumes/Macintosh\ 2TO/Log\'s/Apple/Mac/Jackett/install_service_macos.sh 

I've : 

Couldn't locate JackettConsole.exe. Are you running from the right directory?

**Comment by kaso17** [comment]
```
cd /Volumes/Macintosh\ 2TO/Log's/Apple/Mac/Jackett/
./install_service_macos.sh
```

@thebluepotato is it possible to make the script even more pullet proof by doing the cd to the basedir of the executable itself?

**Comment by Eldoc62** [comment]
cd /Volumes/Macintosh\ 2TO/Log's/Apple/Mac/Jackett/

"ENTER"

There is 

>

I past : 

install_service_macos.sh

and it's over ?

**Comment by thebluepotato** [comment]
@Eldoc62 either wait for pull request #1786 to be merged, or follow these instructions. To be very detailed:
 1. Copy and paste `cd /Volumes/Macintosh\ 2TO/Log's/Apple/Mac/Jackett/`
 2. Press Enter (it shouldn't show anything particular)
 3. Copy and paste `./install_service_macos.sh`
 4. Press Enter (it should say that the agent was successfully installed)

**Comment by Eldoc62** [comment]
@thebluepotato thanks ;) works fine 👍
