### ISSUE TITLE
[yggtorrent] Login failed: Selector

### ISSUE THREAD

**Issue by sh4rkman** [Jackett/Jackett#1788]
Login failed: Selector "a[href="https://yggtorrent.com/user/logout"]" didn't match

**Comment by cadavor** [comment]
+1

**Comment by golgoth73** [comment]
+1

**Comment by cedatif** [comment]
+1

**Comment by WhoKnowsWhat** [comment]
This is when the website is down/under maintenance.
Will not be fixed till YGG release the new (stable) UI.

**Comment by kaso17** [comment]
is this still a problem in the altest pre-release or was it also fixed with 3b447b697cb1dab1b027d9a3631dda42ca2d2910 ( @garfield69 )

**Comment by garfield69** [comment]
I've had no problems logging in today.
I believe this ticket was raised during a yggtorrent outage, just as WhoKnowsWhat stated earlier.
