### ISSUE TITLE
Jackett is not opening on Windows 10

### ISSUE THREAD

**Issue by swassglass** [Jackett/Jackett#1789]
Jackett has worked flawlessly for me for a long time, but now it does not open and Sonarr/Radarr can not connect to it. I tried reinstalling using the instructions on the wiki, but it still will not open. I am getting an "unable to connect" error when navigating to http://127.0.0.1:9117/
Any suggestions?

**Comment by HidyHo** [comment]
Check your antivirus/internet security settings.  I just found out that Bitdefender quarantined mine.  I added the programdata\jackett folder to exclusion and reinstalled.

**Comment by swassglass** [comment]
Thanks @HidyHo . I'll check that out. I am using Windows's default Defender (same as my friends who have no issues), but I will disable that temporarily to see if that fixes anything.

**Comment by swassglass** [comment]
I disabled Windows Defender and I had the same issue. Just out of curiosity I spin up a Windows 10 VM and did the Jackett install in there. It worked fine. I am not sure what happened to my main desktop that it is no longer working.

**Comment by kaso17** [comment]
please check the log file

**Comment by flightlevel** [comment]
re-open if still an issue with log file
