### ISSUE TITLE
[secretcinema] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by savahu** [Jackett/Jackett#1790]
I can't add the new Secret Cinema domain as indexer.
I'm using "https://secret-cinema.pw/"

Jackett version:  0.8.151.0
Mono version (if not using Windows):  Mono JIT compiler version 5.2.0.215 (tarball Mon Aug 14 15:46:23 UTC 2017)

-------------------------------
Relevant logging:

> Sep 06, 2017 11:23:58 PM | Error | ReflectedHttpActionDescriptor ExecuteAsync
> -- | -- | --
> Sep 06, 2017 11:23:58 PM | Debug | IWebClient: Returning Redirect => https://secret-cinema.pw/torrents.php
> Sep 06, 2017 11:23:58 PM | Debug | IWebClient.GetString(Url:https://secret-cinema.pw/browse.php)
> Sep 06, 2017 11:23:58 PM | Debug | CardigannIndexer (secretcinema): Cookies after login:
> Sep 06, 2017 11:23:58 PM | Debug | IWebClient: Returning NotFound => File not found.
> Sep 06, 2017 11:23:58 PM | Debug | IWebClient.GetString(Url:https://secret-cinema.pw/takelogin.php)
> Sep 06, 2017 11:23:58 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Config(config=Jackett.Models.DTO.ConfigItem[])'

**Comment by adamwinn** [comment]
Looks like after they re-did their site, they removed the `takelogin.php` and are using a form with `login.php` now

**Comment by kaso17** [comment]
dupe #1613
The definition needs to be rewritten since they changed a lot but I've no access.
