### ISSUE TITLE
Request to Jackett server failed

### ISSUE THREAD

**Issue by Linwelin** [Jackett/Jackett#1792]
Trying to add IPtorrents but keep getting Request to Jackett server failed, I have added torrentleech and alpharatio without any problem.

When | Level | Message
-- | -- | --
Sep 08, 2017 04:12:35 AM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
Sep 08, 2017 04:12:35 AM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
Sep 08, 2017 04:12:35 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Sep 08, 2017 04:12:35 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
Sep 08, 2017 04:12:35 AM | Info | HttpActionBinding ExecuteBindingAsync
Sep 08, 2017 04:12:35 AM | Info | HttpActionBinding ExecuteBindingAsync
Sep 08, 2017 04:12:35 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Sep 08, 2017 04:12:35 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Sep 08, 2017 04:12:35 AM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
Sep 08, 2017 04:12:35 AM | Info | ApiControllerActionSelector SelectAction
Sep 08, 2017 04:12:35 AM | Info | ServerConfigurationController ExecuteAsync
Sep 08, 2017 04:12:35 AM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ServerConfigurationController
Sep 08, 2017 04:12:35 AM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ServerConfigurationController
Sep 08, 2017 04:12:35 AM | Info | DefaultHttpControllerActivator Create
Sep 08, 2017 04:12:35 AM | Info | HttpControllerDescriptor CreateController
Sep 08, 2017 04:12:35 AM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
Sep 08, 2017 04:12:35 AM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
Sep 08, 2017 04:12:35 AM | Info | http://127.0.0.1:9117/api/v2.0/server/logs?_=1504840330247
Sep 08, 2017 04:12:33 AM | Info | IndexerApiController Dispose
Sep 08, 2017 04:12:33 AM | Info | IndexerApiController Dispose
Sep 08, 2017 04:12:33 AM | Info | Content-type='application/json; charset=utf-8', content-length=6990
Sep 08, 2017 04:12:33 AM | Info | IndexerApiController ExecuteAsync
Sep 08, 2017 04:12:32 AM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Sep 08, 2017 04:12:32 AM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Sep 08, 2017 04:12:32 AM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Sep 08, 2017 04:12:32 AM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Config()'
Sep 08, 2017 04:12:32 AM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Sep 08, 2017 04:12:32 AM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Config()'
Sep 08, 2017 04:12:32 AM | Error | ApiControllerActionInvoker InvokeActionAsync
Sep 08, 2017 04:12:32 AM | Error | ReflectedHttpActionDescriptor ExecuteAsync
Sep 08, 2017 04:12:32 AM | Debug | IWebClient.GetString(Url:https://iptorrents.com/login.php)
Sep 08, 2017 04:12:32 AM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Config()'
Sep 08, 2017 04:12:32 AM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Config()'
Sep 08, 2017 04:12:32 AM | Info | RequiresIndexerAttribute OnActionExecutingAsync
Sep 08, 2017 04:12:32 AM | Info | RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Config()'
Sep 08, 2017 04:12:32 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Sep 08, 2017 04:12:32 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Config()'
Sep 08, 2017 04:12:32 AM | Info | HttpActionBinding ExecuteBindingAsync
Sep 08, 2017 04:12:32 AM | Info | HttpActionBinding ExecuteBindingAsync
Sep 08, 2017 04:12:32 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Sep 08, 2017 04:12:32 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Sep 08, 2017 04:12:32 AM | Info | ApiControllerActionSelector SelectAction Selected action 'Config()'
Sep 08, 2017 04:12:32 AM | Info | ApiControllerActionSelector SelectAction
Sep 08, 2017 04:12:32 AM | Info | IndexerApiController ExecuteAsync
Sep 08, 2017 04:12:32 AM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.IndexerApiController
Sep 08, 2017 04:12:32 AM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.IndexerApiController
Sep 08, 2017 04:12:32 AM | Info | DefaultHttpControllerActivator Create
Sep 08, 2017 04:12:32 AM | Info | HttpControllerDescriptor CreateController
Sep 08, 2017 04:12:32 AM | Info | DefaultHttpControllerSelector SelectController IndexerApi
Sep 08, 2017 04:12:32 AM | Info | DefaultHttpControllerSelector SelectController Route='indexerId:iptorrents,action:config,controller:IndexerApi'

Jackett version:  Windows Latest
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
Can you access https://iptorrents.com/ from your system? Or is it blocked by the ISP?

**Comment by Linwelin** [comment]
It's blocked by virgin media, I use alternate urls and or vpn to access ipt

**Comment by kaso17** [comment]
You're running in the problem described here: #1473
Please use a VPN or the workaround provided there.
