### ISSUE TITLE
Problem with saving on BlackHole directory an locally

### ISSUE THREAD

**Issue by grk3000** [Jackett/Jackett#1797]
Hello, 

I'm using Jackett on a seedbox Ubuntu server. This server is on the cloud and I'm using it remotely. It runs Jackett, rtorrent/Rutorrent, radarr, sonarr.

I would like to use the very usefull manual search feature to be able to add torrent to rtorrent directly (for ebooks for instance as I use radarr for movies and sonarr for TV series)

The manual search works fine and I can find the torrents I'm looking for in my indexers.

My problem is that the "Save to BlackHole directory" and "save locally" features do not work. I get "Request to Jackett server failed".

When looking at the url format for these 2 requests, here's what they look like 

for local download : http://localhost:9117/jackett/dl/t411v2/?jackett_apikey=xxxxxxxxxxx&path=xxxx&file=xxx.torrent 
for BH : http://localhost:9117/jackett/bh/t411v2/?jackett_apikey=xxxxxxxxxxx&path=xxxx&file=xxx.torrent 

The problem is that the url site is http://localhost:9117/jackett/ but i'm not running jackett and rtorrent locally but remotey on a server.

When I copy/paste the url on my web browser and modify the IP adress of the url with the one of my server then it works fine.

http://IP Address_of_my_remote_server:9117/jackett/bh/xxxxxxxxx
http://IP Address_of_my_remote_server:9117/jackett/dl/xxxxxxxxx

Would it be possible to specify that I'm using a remote server in order to have the right link url with the IP address of my server ?

Thx for you help.

Jackett Version 0.8.147.0
Mono JIT compiler version 5.2.0.215
-------------------------------

**Comment by kaso17** [comment]
you're using a reverse proxy setup.
You've make sure it sets's the Host header correctly.
For apache you've to enable the ProxyPreserveHost option

**Comment by grk3000** [comment]
Well,
I'm effectively using a reverse proxy with apache (quickbox automatic installation).

On which file should I enable it ?
Thx for your help

**Comment by grk3000** [comment]
What I don't understand is that the BH and local donwload link is interpreted by my brosser.

As the URL is http://localhost:9117/jackett/bh/... then my browser will try to reach localhost (my laptop) port 9117. As Jackett is not on my laptop but on a remote serveur, it will not work.

And when i coup/paste the link and change localhost by thé ipaddress of my server then it works. Are you sure it's a reverse proxy issue ?

**Comment by kaso17** [comment]
Yes, it's a reverse proxy issue.
When the reverse proxy is sending the request to jackett it's using host "localhost". To send the original host they've to enable the ProxyPreserveHost flag
I suggest you contact the quickbox team about this.
I don't know their configuration.
If they're using https too also have a look at https://github.com/Jackett/Jackett/issues/1464#issuecomment-326611441
