### ISSUE TITLE
animetorrents.me english name search does not work.

### ISSUE THREAD

**Issue by joshuasm** [Jackett/Jackett#1799]
I am Using Sonarr with Jacket and when Sonarr searches for an anime it uses the English name, now AnimeTorrents only uses the Japanese name and so when it searches it cannot find it. Is there anyway to convert it using Jacket or would I have to consult the Sonarr devs?

I tried searching manually for the anime through jacket the Japanese name worked but the English name didn't.

**Comment by kaso17** [comment]
This is something the Sonarr devs have to "fix". I believe there are already plenty of open issues regarding multi language support, etc..

**Comment by walkerp1** [comment]
English title searches are supported by AnimeTorrents directly through a description search. You could do a fallback search if the main returned no hits by changing searchin=filename to searchin=filedisc&search in Jackett/Indexers/AnimeTorrents.cs
