### ISSUE TITLE
Torrentleech snatching wrong releases 

### ISSUE THREAD

**Issue by chris0101** [Jackett/Jackett#1800]
Having issues with torrentleech at the moment, its grabbing incorrect releases. for example 
couchpotato searched " justice league " and it downloaded " justice league dark " from torrentleech 
 anothere was " it " it download "it and the way foreward " or something 

any ideas?

**Comment by kaso17** [comment]
CP doesn't do any validation on the release. jackett just returns the search results to CP.
I personally would only use trackers which support search by imdbid with couch potato to avoid these problems.

**Comment by chris0101** [comment]
Ah ok, thanks
