### ISSUE TITLE
How Do I move Jackett Installation to New Computer (Win10 --> Win10)?

### ISSUE THREAD

**Issue by jeff15110168** [Jackett/Jackett#1804]
I'm moving computers from a laptop to a desktop, and I was wondering if someone could tell me how to easily move my jackett installation over. I have jackett running as a service.

I was planning to copy the Jackett, nzbdrone and Radarr folders from C:\ProgramData and just replacing those in my new desktop when I'm done building it.

Let me know if that doesn't work and if I need to do something special.

**Comment by kaso17** [comment]
This will be difficult on windows.
Jackett uses the DataProtection class to store the keys for obfuscating the passwords in the config.
I don't know how to extract/migrate them on windows.
If you're successful please let us know.

**Comment by jeff15110168** [comment]
I imported the prorgamdata folder to new computer, but it looks like i had to manually re-add each tracker and enter in password again. Other than that, everything seems to be working.

Would be good in future if a dev or someone with knowledge can give us isntructions on best way to move data over. Otherwise people googling may just follow my experience (moving programdata folder over and re-entering in all the private tracker info).

**Comment by DrissiReda** [comment]
So we can't move the data even if we only had open trackers??

**Comment by inspector71** [comment]
> So we can't move the data even if we only had open trackers??

FWIW, I moved my indexer definitions from Windows 10 to a Linux based Jackett install by copying the contents of this `Indexers` folder:

`%ProgramData%\Jackett\Indexers`

One messy aspect of Jackett on Linux systems is the duplication, and mixed casing, of folders named *ackett. That is, the `Indexers` folder generally (unless Jackett is running from a seemingly less-than-common location) _lives_ here:

`/opt/jackett/Jackett`

That is:

`/opt/jackett/Jackett/Indexers`

Understand this is not specifically on point with the issue topic but hopefully it is relevant, helpful to someone who may end up here despite having a slightly different use case.
