### ISSUE TITLE
[hounddawgs] Exception (hounddawgs): Invalid URI: The format of the URI could not be determined.: Invalid URI: The format of the URI could not be determined. (Test)

### ISSUE THREAD

**Issue by InfAmoUsaeble** [Jackett/Jackett#1805]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by InfAmoUsaeble** [comment]
Hi

I would love to provide full logs, but there are a lot of sensitive information in them, and it would take some time to clean up. As I'm new to GitHub as a user, I would like to know if there is a way to upload files for project owners only. Otherwise, please contact me privately if possible and I will happily upload the logs directly to some one.

Thank you for a great project btw.

/BR

**Comment by Moulde** [comment]
I got the same error, and seemed to fix it by changing the address to: https://www.hounddawgs.org/
But then i get another error https://github.com/Jackett/Jackett/issues/1806

**Comment by InfAmoUsaeble** [comment]
It seems to be working again, not sure what was going on ... =/

Logs can still be sent if needed.

**Comment by Moulde** [comment]
I'm getting this now.

{
  "result": "error",
  "error": "Exception (hounddawgs): Invalid URI: The format of the URI could not be determined.: Invalid URI: The format of the URI could not be determined.",
  "stacktrace": "  at Jackett.Indexers.BaseIndexer+<ResultsForQuery>c__async1.MoveNext () [0x0011f] in <dbbd8c496833464ca81bca9d2cfac226>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <204f770036d441bb8dfd3daba3550e83>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <204f770036d441bb8dfd3daba3550e83>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <204f770036d441bb8dfd3daba3550e83>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <204f770036d441bb8dfd3daba3550e83>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 \n  at Jackett.Indexers.BaseWebIndexer+<ResultsForQuery>c__asyncC.MoveNext () [0x0006b] in <dbbd8c496833464ca81bca9d2cfac226>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <204f770036d441bb8dfd3daba3550e83>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <204f770036d441bb8dfd3daba3550e83>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <204f770036d441bb8dfd3daba3550e83>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <204f770036d441bb8dfd3daba3550e83>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 \n  at Jackett.Controllers.V20.ResultsController+<Torznab>c__async1.MoveNext () [0x002e1] in <dbbd8c496833464ca81bca9d2cfac226>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <204f770036d441bb8dfd3daba3550e83>:0 \n  at

**Comment by kaso17** [comment]
I assume this has been fixed (looks like an issue on the tracker side).
