### ISSUE TITLE
[gimmepeers] Exception (gimmepeers): Index and length must refer to a location within the string.Parameter name: length: Index and length must refer to a location within the string.Parameter name: length (Config)

### ISSUE THREAD

**Issue by DragonslayerNZ** [Jackett/Jackett#1811]
[log.txt](https://github.com/Jackett/Jackett/files/1295168/log.txt)
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
@BenJaminBMorin and @TheDogg can you help with this?

**Comment by kaso17** [comment]
According to @albertsj1 (see #1811) you've to disable the "View Top20" option in the profile.
Maybe @BenJaminBMorin and/or @TheDogg can help making it work independently of the option.

**Comment by DragonslayerNZ** [comment]
Thanks for the info. I disabled top 20 and its working fine now.

**Comment by BenJaminBMorin** [comment]
Just created a pull request to fix this issue.  Turns out that the Top 20 and the master table share the same class.  Telling the css selector on the gimmepeers.cs indexer to select the ":last" one will allow the top 20 to show or not show and still work.  Sorry it took so long to put in a fix.  Super simple once I looked at it.

**Comment by kaso17** [comment]
fixed via #2360
