### ISSUE TITLE
[anidex] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by FabioCastilho** [Jackett/Jackett#1817]
anidex does not find any result and error when testing in the jackeet

Jackett version:  last
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
I cannot replicate this. My test is successful.
![image](https://user-images.githubusercontent.com/6933240/30361395-db5cbcac-98aa-11e7-8092-7e787fe6359c.png)

Can you access the site directly from your browser `https://anidex.info/` ?
Also, on the Jackett dashboard, click on the *wrench* icon to view the *anidex* config, and check that the *Site Link* is set correctly.
![image](https://user-images.githubusercontent.com/6933240/30361477-524fa5f4-98ab-11e7-9ea8-3101584a0e7d.png)
If not, change it, and click on the *Okay* button to save and then perform the test, which should work as it did for me.       
If the site link is correct, then provide full debug logs.

**Comment by FabioCastilho** [comment]
Ola fiz a configuração e mesmo assim da erro. Rodando em um RPI3

Hello, I made a configuration and still the error. Running on an RPI3

![capturar](https://user-images.githubusercontent.com/21134162/30688924-d353cdde-9e95-11e7-8dc5-8c4cd82b3004.PNG)
![capturar1](https://user-images.githubusercontent.com/21134162/30688926-d3589e54-9e95-11e7-80df-bb8ad5f88b34.PNG)
![capturar2](https://user-images.githubusercontent.com/21134162/30688925-d3578c4e-9e95-11e7-81c4-32ee668e6aae.PNG)

**Comment by garfield69** [comment]
- Please update to the latest version of jackett, currently v0.8.216      

![image](https://user-images.githubusercontent.com/6933240/30711582-4f132c86-9f5d-11e7-89fa-d6d67c5c7230.png)     

- Repeat your test.     
- If it does not work, then enable enhanced logging      

![image](https://user-images.githubusercontent.com/6933240/30712037-a65e62de-9f5e-11e7-8d96-4885ab2987a3.png)
    

- Perform your test     
- Then find the log.txt which is stored in %ProgramData%\Jackett on Windows and ~/.config/Jackett/ on Linux/macOS.     
- Edit to remove your username/password/cookies.     
- Post the log.txt here for us to examine.

**Comment by christronyxyocum** [comment]
I'm running 0.8.216.0 and am able to replicate this issue.
[jackett_logs.txt](https://github.com/Jackett/Jackett/files/1322805/jackett_logs.txt)

**Comment by garfield69** [comment]
Thank you. I can replicate the problem now and I see the problem.     
I should be able to code a fix shortly.
