### ISSUE TITLE
[FR] Ethor.net

### ISSUE THREAD

**Issue by dardano** [Jackett/Jackett#182]
Hi, I just found your Jackett app for Windows. It's a life changer.

I would like to request support for 2 private trackers
ethor -> http://ethor.net/dp#/?
T411 -> http://www.t411.in/

Thanks

**Comment by feline51** [comment]
Hi, 
t411 is the best french tracker
Thank you for adding this one.

**Comment by JigSawFr** [comment]
Planned but not for now, I'm too busy.

**Comment by dardano** [comment]
I have invites for ethor if needed. let me know.

**Comment by maxcore** [comment]
@dardano i hope for etho but amazing captcha ..

**Comment by raspdealer** [comment]
Can you update this issue to concern only Ethor ?
And follow this: https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker

About T411, it was there before but it has been removed. The last version with t411 is 0.6.45.
If you need to run this version AND a recent one, you can take a look to my fork.
More info about why it has been removed: https://github.com/Jackett/Jackett/issues/157

**Comment by Bybou** [comment]
@dardano you can contact me on my public mail

**Comment by dardano** [comment]
@raspdealer to whom may I sent the invite for ethor ?

@Bybou I sent you an email.

**Comment by dardano** [comment]
@maxcore ethor is the best french tracker with t411. I know the captcha is something to get through...

**Comment by JigSawFr** [comment]
@dardano i'm searching how i can bypass captcha to login. After why not building a full provider, At this time, i don't have account on this tracker.

**Comment by dardano** [comment]
@JigSawFr you will need an invite. send me your email at my public email. I will send you an invite to access this tracker.

**Comment by maxcore** [comment]
@dardano
Its my best provider ! I have invite too for dev

**Comment by JigSawFr** [comment]
you can send me an invite to
```
jigsawlimitedfr@gmail.com
```
:)

**Comment by raspdealer** [comment]
Can you please rename your issue ?
Thanks :)

**Comment by feline51** [comment]
@raspdealer Thank you for your answer but on Synology Jackett is already installed and I don't know how install manuelly your release.

**Comment by dardano** [comment]
@raspdealer T411 with the proper release doesn't seem to work,... is it possible to add it again in Jackett ?

Thx

**Comment by raspdealer** [comment]
Can you please create a second issue for that?

**Comment by JigSawFr** [comment]
@raspdealer T411 provider may be outdated, so you can't create an issue for an old version of Jackett. Need to wait for t411 to be part of project again.

**Comment by maxcore** [comment]
@JigSawFr you got your invite or not ?

**Comment by feline51** [comment]
@maxcore someone has an invite for Ethor ? maybe.. :+1:

**Comment by dardano** [comment]
@maxcore I gave an invite by email to @JigSawFr

**Comment by maxcore** [comment]
@dardano thx for this ;)

**Comment by JigSawFr** [comment]
@dardano thanks, just received and registred. It will be not complicated for me to do a provider, the only thing i need to study is how to bypass captcha on login, and it will be fine.

**Comment by raspdealer** [comment]
If you can bypass it, it's not a good captcha :D

**Comment by JigSawFr** [comment]
Need to see if another provider is bypassing capatcha or if an OCR library is embed in Jackett Core.

@Azerelat do you have an idea on this subject ?

**Comment by dardano** [comment]
@JigSawFr This is great news !

**Comment by dardano** [comment]
@JigSawFr there is already *BitMeTV* on Jackett with captcha

**Comment by JigSawFr** [comment]
@dardano okay, i will take a look asap

**Comment by JigSawFr** [comment]
So, i take a look and i understand it.
Captcha is showed to user when configure.
I will this in first time, and i will incorporate and a captcha solver service in second time.

**Comment by JigSawFr** [comment]
As a note:
Providers with captchas:
* BitMeTV (simple captcha)
* TorrentDay (reCaptcha 2)

**Comment by dardano** [comment]
@JigSawFr , any update yet ?

Thanks for your help.

**Comment by flightlevel** [comment]
@JigSawFr email sent

**Comment by smiro0** [comment]
Any update on this ?

Any programmer needs an invite ?

**Comment by dardano** [comment]
Any update for ethor.net ?

I have 1 invite left to help.

@JigSawFr have you got time to solve the captcha login ?

thanks

**Comment by dardano** [comment]
Any update ? 
Thanks in advance

**Comment by saitoh183** [comment]
Any update on Ethor?

**Comment by kaso17** [comment]
I got an invite and added Ethor to my TODO queue.

**Comment by maxcore** [comment]
Great news

**Comment by JigSawFr** [comment]
t411 is available on cardigann ;) (we can't add it to jackett as it's a public tracker)

**Comment by kaso17** [comment]
You should be able to use the t411 definition from cardigann with jackett too.
