### ISSUE TITLE
[bitspyder] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Biffaboy** [Jackett/Jackett#1832]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
works for me, please provide a full log

**Comment by Biffaboy** [comment]
> CardigannIndexer (bitspyder): Error while parsing row '<tr class="alt2">
> 	<td class="rowcol" width="1" align="center" style="padding: 0px">
> 		<a href="browse.php?cat=43">
> 			<img border="0" src="/pic/Lynda.jpg" alt="Lynda.com">			
> 		</a>
> 	</td> <td class="rowcol" align="left">
> 		<a class="altlink6" href="details.php?id=84413&amp;hit=1">
> 			<b>Learning LinkedIn Recruiter | Lynda com</b>
> 		</a>
> 		<br>
> 		
> 		<table style="padding-top: 4px; background-color: transparent;" width="100%">
> 			<tbody>
> 				<tr>
> 					<td style="padding-top: 4px; background-color: transparent;" align="left" class="clear" width="100">
> 						<font size="1" color="#373737">Size: </font>
> 						<font color="#A52A2A" size="1">230.70&nbsp;MB&nbsp;</font> </td>
> 					<td style="padding-top: 4px;" class="clear" width="80" align="left"> <font color="#5F5F5F" size="1">Files: </font>
> 						<font color="#5F5F5F" size="1"> <a class="altlink4" href="details.php?id=84413&amp;hit=1&amp;filelist=1">20</a>
> 						</font>
> 					</td> <td style="padding-top: 4px;" class="clear" width="90" align="left">
> 						<font color="#5F5F5F" size="1"> Comments: </font>
> 						<font color="#5F5F5F" size="1">0</font>
> 					</td> <td style="padding-top: 4px;" class="clear" width="120" align="left">
> 						<font color="#5F5F5F" size="1">Snatches: 8</font>
> 					</td> <td style="padding-top: 4px;" class="clear" align="right" width="40"> <font color="#5F5F5F" size="1">Rating: </font>
> 					</td>
> 					<td style="padding-top: 4px;" class="clear" align="center" width="57">&nbsp;---</td> <td style="padding-top: 4px;" class="clear" width="20" align="left">
> 						<a href="#" onclick="displayMessage('bookmarkpop.php?torrent=84413'); return false">
> 							<img src="/pic/bookmark.png" border="none" alt="Bookmark" title="Bookmark this torrent">							 </a>
> 					</td>
> 					<td style="padding-top: 4px;" class="clear" width="1" align="right">
> 						<a class="altlink" href="#" onclick="displayMessage('last1.php'); return false">
> 							<img src="/pic/last_browse.png" border="none" alt="Last Browse">							
> 						</a>
> 					</td>
> 				</tr>
> 			</tbody>
> 		</table>
> 	</td> <td class="rowcol" align="right">
> 		<b>
> 			<a style="text-decoration: none;" href="details.php?id=84413&amp;hit=1&amp;toseeders=1">
> 				<font color="#000000">6</font>
> 			</a>
> 		</b>
> 	</td> <td class="rowcol" align="right">0</td> <td class="rowcol" align="center">
> 		<center>
> 			<font size="1">
> 				<a class="altlink" href="/userdetails.php?id=3836">
> 					<b>truejack</b>
> 				</a>
> 			</font> <br>
> 			
> 			<font size="1" class="small">
> 				<a title="Upploaded at - 2017-09-14&nbsp;16:40:27">1 day ago</a>
> 			</font>
> 		</center>
> 	</td> </tr>':
> 
> System.Exception: Error while parsing field=grabs, selector=td.rowcol:nth-child(7):has(br), value=<null>: Selector "td.rowcol:nth-child(7):has(br)" didn't match <tr class="alt2">
> 	<td class="rowcol" width="1" align="center" style="padding: 0px">
> 		<a href="browse.php?cat=43">
> 			<img border="0" src="/pic/Lynda.jpg" alt="Lynda.com">			
> 		</a>
> 	</td> <td class="rowcol" align="left">
> 		<a class="altlink6" href="details.php?id=84413&amp;hit=1">
> 			<b>Learning LinkedIn Recruiter | Lynda com</b>
> 		</a>
> 		<br>
> 		
> 		<table style="padding-top: 4px; background-color: transparent;" width="100%">
> 			<tbody>
> 				<tr>
> 					<td style="padding-top: 4px; background-color: transparent;" align="left" class="clear" width="100">
> 						<font size="1" color="#373737">Size: </font>
> 						<font color="#A52A2A" size="1">230.70&nbsp;MB&nbsp;</font> </td>
> 					<td style="padding-top: 4px;" class="clear" width="80" align="left"> <font color="#5F5F5F" size="1">Files: </font>
> 						<font color="#5F5F5F" size="1"> <a class="altlink4" href="details.php?id=84413&amp;hit=1&amp;filelist=1">20</a>
> 						</font>
> 					</td> <td style="padding-top: 4px;" class="clear" width="90" align="left">
> 						<font color="#5F5F5F" size="1"> Comments: </font>
> 						<font color="#5F5F5F" size="1">0</font>
> 					</td> <td style="padding-top: 4px;" class="clear" width="120" align="left">
> 						<font color="#5F5F5F" size="1">Snatches: 8</font>
> 					</td> <td style="padding-top: 4px;" class="clear" align="right" width="40"> <font color="#5F5F5F" size="1">Rating: </font>
> 					</td>
> 					<td style="padding-top: 4px;" class="clear" align="center" width="57">&nbsp;---</td> <td style="padding-top: 4px;" class="clear" width="20" align="left">
> 						<a href="#" onclick="displayMessage('bookmarkpop.php?torrent=84413'); return false">
> 							<img src="/pic/bookmark.png" border="none" alt="Bookmark" title="Bookmark this torrent">							 </a>
> 					</td>
> 					<td style="padding-top: 4px;" class="clear" width="1" align="right">
> 						<a class="altlink" href="#" onclick="displayMessage('last1.php'); return false">
> 							<img src="/pic/last_browse.png" border="none" alt="Last Browse">							
> 						</a>
> 					</td>
> 				</tr>
> 			</tbody>
> 		</table>
> 	</td> <td class="rowcol" align="right">
> 		<b>
> 			<a style="text-decoration: none;" href="details.php?id=84413&amp;hit=1&amp;toseeders=1">
> 				<font color="#000000">6</font>
> 			</a>
> 		</b>
> 	</td> <td class="rowcol" align="right">0</td> <td class="rowcol" align="center">
> 		<center>
> 			<font size="1">
> 				<a class="altlink" href="/userdetails.php?id=3836">
> 					<b>truejack</b>
> 				</a>
> 			</font> <br>
> 			
> 			<font size="1" class="small">
> 				<a title="Upploaded at - 2017-09-14&nbsp;16:40:27">1 day ago</a>
> 			</font>
> 		</center>
> 	</td> </tr>
>    at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__25.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:line 1303

**Comment by Biffaboy** [comment]
CardigannIndexer (bitspyder): Error while parsing row '<tr class="alt2">
	<td class="rowcol" width="1" align="center" style="padding: 0px">
		<a href="browse.php?cat=43">
			<img border="0" src="/pic/Lynda.jpg" alt="Lynda.com">			
		</a>
	</td> <td class="rowcol" align="left">
		<a class="altlink6" href="details.php?id=84413&amp;hit=1">
			<b>Learning LinkedIn Recruiter | Lynda com</b>
		</a>
		<br>
		
		<table style="padding-top: 4px; background-color: transparent;" width="100%">
			<tbody>
				<tr>
					<td style="padding-top: 4px; background-color: transparent;" align="left" class="clear" width="100">
						<font size="1" color="#373737">Size: </font>
						<font color="#A52A2A" size="1">230.70&nbsp;MB&nbsp;</font> </td>
					<td style="padding-top: 4px;" class="clear" width="80" align="left"> <font color="#5F5F5F" size="1">Files: </font>
						<font color="#5F5F5F" size="1"> <a class="altlink4" href="details.php?id=84413&amp;hit=1&amp;filelist=1">20</a>
						</font>
					</td> <td style="padding-top: 4px;" class="clear" width="90" align="left">
						<font color="#5F5F5F" size="1"> Comments: </font>
						<font color="#5F5F5F" size="1">0</font>
					</td> <td style="padding-top: 4px;" class="clear" width="120" align="left">
						<font color="#5F5F5F" size="1">Snatches: 8</font>
					</td> <td style="padding-top: 4px;" class="clear" align="right" width="40"> <font color="#5F5F5F" size="1">Rating: </font>
					</td>
					<td style="padding-top: 4px;" class="clear" align="center" width="57">&nbsp;---</td> <td style="padding-top: 4px;" class="clear" width="20" align="left">
						<a href="#" onclick="displayMessage('bookmarkpop.php?torrent=84413'); return false">
							<img src="/pic/bookmark.png" border="none" alt="Bookmark" title="Bookmark this torrent">							 </a>
					</td>
					<td style="padding-top: 4px;" class="clear" width="1" align="right">
						<a class="altlink" href="#" onclick="displayMessage('last1.php'); return false">
							<img src="/pic/last_browse.png" border="none" alt="Last Browse">							
						</a>
					</td>
				</tr>
			</tbody>
		</table>
	</td> <td class="rowcol" align="right">
		<b>
			<a style="text-decoration: none;" href="details.php?id=84413&amp;hit=1&amp;toseeders=1">
				<font color="#000000">6</font>
			</a>
		</b>
	</td> <td class="rowcol" align="right">0</td> <td class="rowcol" align="center">
		<center>
			<font size="1">
				<a class="altlink" href="/userdetails.php?id=3836">
					<b>truejack</b>
				</a>
			</font> <br>
			
			<font size="1" class="small">
				<a title="Upploaded at - 2017-09-14&nbsp;16:40:27">1 day ago</a>
			</font>
		</center>
	</td> </tr>':

System.Exception: Error while parsing field=grabs, selector=td.rowcol:nth-child(7):has(br), value=<null>: Selector "td.rowcol:nth-child(7):has(br)" didn't match <tr class="alt2">
	<td class="rowcol" width="1" align="center" style="padding: 0px">
		<a href="browse.php?cat=43">
			<img border="0" src="/pic/Lynda.jpg" alt="Lynda.com">			
		</a>
	</td> <td class="rowcol" align="left">
		<a class="altlink6" href="details.php?id=84413&amp;hit=1">
			<b>Learning LinkedIn Recruiter | Lynda com</b>
		</a>
		<br>
		
		<table style="padding-top: 4px; background-color: transparent;" width="100%">
			<tbody>
				<tr>
					<td style="padding-top: 4px; background-color: transparent;" align="left" class="clear" width="100">
						<font size="1" color="#373737">Size: </font>
						<font color="#A52A2A" size="1">230.70&nbsp;MB&nbsp;</font> </td>
					<td style="padding-top: 4px;" class="clear" width="80" align="left"> <font color="#5F5F5F" size="1">Files: </font>
						<font color="#5F5F5F" size="1"> <a class="altlink4" href="details.php?id=84413&amp;hit=1&amp;filelist=1">20</a>
						</font>
					</td> <td style="padding-top: 4px;" class="clear" width="90" align="left">
						<font color="#5F5F5F" size="1"> Comments: </font>
						<font color="#5F5F5F" size="1">0</font>
					</td> <td style="padding-top: 4px;" class="clear" width="120" align="left">
						<font color="#5F5F5F" size="1">Snatches: 8</font>
					</td> <td style="padding-top: 4px;" class="clear" align="right" width="40"> <font color="#5F5F5F" size="1">Rating: </font>
					</td>
					<td style="padding-top: 4px;" class="clear" align="center" width="57">&nbsp;---</td> <td style="padding-top: 4px;" class="clear" width="20" align="left">
						<a href="#" onclick="displayMessage('bookmarkpop.php?torrent=84413'); return false">
							<img src="/pic/bookmark.png" border="none" alt="Bookmark" title="Bookmark this torrent">							 </a>
					</td>
					<td style="padding-top: 4px;" class="clear" width="1" align="right">
						<a class="altlink" href="#" onclick="displayMessage('last1.php'); return false">
							<img src="/pic/last_browse.png" border="none" alt="Last Browse">							
						</a>
					</td>
				</tr>
			</tbody>
		</table>
	</td> <td class="rowcol" align="right">
		<b>
			<a style="text-decoration: none;" href="details.php?id=84413&amp;hit=1&amp;toseeders=1">
				<font color="#000000">6</font>
			</a>
		</b>
	</td> <td class="rowcol" align="right">0</td> <td class="rowcol" align="center">
		<center>
			<font size="1">
				<a class="altlink" href="/userdetails.php?id=3836">
					<b>truejack</b>
				</a>
			</font> <br>
			
			<font size="1" class="small">
				<a title="Upploaded at - 2017-09-14&nbsp;16:40:27">1 day ago</a>
			</font>
		</center>
	</td> </tr>
   at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__25.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:line 1303

**Comment by kaso17** [comment]
they redesigned their alternative style.
To fix it Click on "Switch style" on their Downloads/Search website.
I'll try to make it compatible for both styles again soon.

**Comment by kaso17** [comment]
fixed via 8b5d3d017096be80157fb708a913c092620e03c3
