### ISSUE TITLE
Can't connect to TheEmpire Tracker

### ISSUE THREAD

**Issue by antigravity83** [Jackett/Jackett#1835]
Jackett version: 0.8.175.0
Logs: https://pastebin.com/f0YvMAip

Thank you

**Comment by adamwinn** [comment]
URL in the definition probably needs to be changed from `http` to `https`.  See e33e95c1b284237647c34827f6137dac838e4d4e

**Comment by adamwinn** [comment]
Fixed in v0.8.181 with e33e95c1b284237647c34827f6137dac838e4d4e

**Comment by antigravity83** [comment]
Thanks!
