### ISSUE TITLE
T411 need to be in again

### ISSUE THREAD

**Issue by dardano** [Jackett/Jackett#184]
Is it possible to get back T411 as french tracker ?

It is one of the best french tracker.

Thanks

**Comment by raspdealer** [comment]
It was there before but it has been removed. The last version with t411 is 0.6.45.
If you need to run this version AND a recent one, you can take a look to my fork.
More info about why it has been removed: #157

**Comment by JigSawFr** [comment]
@dardano please do a search before opening an issue, thanks.

**Comment by dardano** [comment]
@JigSawFr @raspdealer 
Is there a way to have T411 back on Jackett ?

If not, I will close this case.
Thx

**Comment by JigSawFr** [comment]
Not now, need to wait for Jackett to reintegrate public trackers.

**Comment by dardano** [comment]
@JigSawFr Thank you for your answer. I'll wait.
