### ISSUE TITLE
[kapaki] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Hackerpcs** [Jackett/Jackett#1842]
Jackett version:  0.8.199.0

**Comment by kaso17** [comment]
works for me, please provide an enhanced log

**Comment by Hackerpcs** [comment]
https://ghostbin.com/paste/choue

**Comment by kaso17** [comment]
same here, please upload it to another pastebin (it's down)

**Comment by garfield69** [comment]
@kaso17  I can access this pastebin now, so try again ;-)

**Comment by kaso17** [comment]
I assume this has been fixed via 6a4a9a09f5f5406d4a85d627f183c1b3b71a0d04, if not please let us know.
