### ISSUE TITLE
[ptfiles] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Hackerpcs** [Jackett/Jackett#1844]
Jackett version:  0.8.199.0

**Comment by kaso17** [comment]
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by Hackerpcs** [comment]
https://ghostbin.com/paste/wbopt

**Comment by kaso17** [comment]
Can you please reupload it to another pastebin

**Comment by Hackerpcs** [comment]
It is up again but if it goes down again use
https://archive.fo/
to see them again, I've archived them there
