### ISSUE TITLE
[Traker Request] - scambiofile.info

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#1845]
Hi, is possible to add this little (local) traker?

Link: http://www.scambiofile.info/rss.php
Tipe: open
Language: italian

Is possible to make search and there's also a rss feed

What do you think?

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by Jorman** [comment]
I'm not, but is not so important this traker, is a small one, in my language. In future, with no rush, if you don't know how to do, you can consider to implement that.

Always tnx!

**Comment by Jorman** [comment]
Traker is not available anymore
