### ISSUE TITLE
[ethor] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by DeltaHit** [Jackett/Jackett#1849]
Jackett version:  0.8.199.0
Mono version (if not using Windows):  

-------------------------------
This tracker's test doesn't work anymore, and I can't create a new instance with the tracker either.

**Comment by kaso17** [comment]
works for me, please provide an enhanced log

**Comment by DeltaHit** [comment]
Sep 19, 2017 12:42:41 PM | Error | ApiControllerActionInvoker InvokeActionAsync
-- | -- | --
Sep 19, 2017 12:42:41 PM | Error | ReflectedHttpActionDescriptor ExecuteAsync

These are the parts of the enhanced log that were highlighted in red, tell me if you need more logs!

**Comment by kaso17** [comment]
Please update to v0.8.216 and retry + repost the log (should contain more details)

**Comment by DeltaHit** [comment]
Sep 20, 2017 01:07:27 PM | Info | IndexerApiController Dispose
-- | -- | --
Sep 20, 2017 01:07:27 PM | Info | IndexerApiController Dispose
Sep 20, 2017 01:07:27 PM | Info | Content-type='application/json; charset=utf-8', content-length=5068
Sep 20, 2017 01:07:27 PM | Info | IndexerApiController ExecuteAsync
Sep 20, 2017 01:07:27 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Sep 20, 2017 01:07:27 PM | Error | {0}
Sep 20, 2017 01:07:27 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Sep 20, 2017 01:07:27 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Sep 20, 2017 01:07:27 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Sep 20, 2017 01:07:27 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Sep 20, 2017 01:07:27 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Test()'
Sep 20, 2017 01:07:27 PM | Error | ApiControllerActionInvoker InvokeActionAsync
Sep 20, 2017 01:07:27 PM | Error | ReflectedHttpActionDescriptor ExecuteAsync
Sep 20, 2017 01:07:27 PM | Info | Found 0 releases from Ethor.net (Thor's Land)
Sep 20, 2017 01:07:27 PM | Debug | IWebClient: Returning Unauthorized => {"status":"error","message":"Impossible de changer de page, vous n'\u00eates plus authentifi\u00e9 sur le site.<br><br><a href='javascript:location.reload();'>Veuillez recharger la page<\/a>"}
Sep 20, 2017 01:07:27 PM | Debug | IWebClient.GetString(Url:https://ethor.net/browse.php?search=&advcat=0&incldead=1&stype=b&dp=0&isUserClick=0)
Sep 20, 2017 01:07:27 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
Sep 20, 2017 01:07:27 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Test()'
Sep 20, 2017 01:07:27 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync
Sep 20, 2017 01:07:27 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Test()'
Sep 20, 2017 01:07:27 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Sep 20, 2017 01:07:27 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()'
Sep 20, 2017 01:07:27 PM | Info | HttpActionBinding ExecuteBindingAsync
Sep 20, 2017 01:07:27 PM | Info | HttpActionBinding ExecuteBindingAsync

Here's what I've been able to retrieve, and I just noticed that the website is returning "Impossible to change page, you are not authenticated anymore, please reload the page"

**Comment by DeltaHit** [comment]
Also, I have successfully updated to Jackett Version 0.8.216.0, so the version of Jackett at the beginning of the issue no longer applies.

**Comment by DeltaHit** [comment]
Nevermind! The issue has been solved, I tried to mess around with my username/password to fix the issue earlier, but with the new version of Jackett, it is now working for me (after putting the right username/password)

Thank you for your help kaso17!
