### ISSUE TITLE
DanishBits: FreeLeech results shown under Movies, when searching for Series.

### ISSUE THREAD

**Issue by supremacy2k** [Jackett/Jackett#1851]
Jackett: 0.8.199.0

https://prnt.sc/gmlg8s

This picture shows, series with freeleech is shown under Movies according to Jackett.

**Comment by kaso17** [comment]
related to #1715
Their API  provides incorrect categories (it only returns "movie" or "tv" currently.  I already send the staff a PM regarding this.
We can't fix this without violating the tracker rules.

**Comment by supremacy2k** [comment]
Okey, thanks for your time.
Didn't realize the api returned wrong info. :S
