### ISSUE TITLE
Kickass Torrents (KAT) Test Failed and Not Pulling RSS Sync in Sonarr

### ISSUE THREAD

**Issue by jeff15110168** [Jackett/Jackett#1852]
Sonarr is showing test failed for KAT, even though all the other torrent indexers are working (both private and public ones like pirate bay or skytorrents). Furthermore, KAT actually is working when I manually search for episodes in Sonarr. KAT shows up and I can pull/download episodes from the manual search. 

The issue is that RSS sync doesn't seem to be working and when I "test" KAT indexer in Sonarr, it says it fails. Any idea what could be the problem?

Jackett version:  0.8.199

**Comment by kaso17** [comment]
please provide an enhanced log during a failed test

**Comment by danmed** [comment]
check your categories.. i had to remove 5030 to get any results

**Comment by jeff15110168** [comment]
That didn't seem to work. I may try remove other items as well. What exactly do the categories do?

On Sep 21, 2017, at 6:40 AM, danmed <notifications@github.com<mailto:notifications@github.com>> wrote:


check your categories.. i had to remove 5030 to get any results

**Comment by zero77** [comment]
This is the same for Radarr but I think it is ok on duckietv.

**Comment by jeff15110168** [comment]
So what do we do? I figured out how to my fix KAT by deleting most of the categories, I don’t want this to affect my ability to search files though. Any idea?

How do categories affect torrents btw? I thought it was a newsfeed feature that doesn’t apply to torrents

On Sep 21, 2017, at 10:12 AM, zero77 <notifications@github.com<mailto:notifications@github.com>> wrote:


This is the same for Radarr but I think it is ok on duckietv.

**Comment by danmed** [comment]
If you look at the Kat listing in Jackett it tells you which categories are
supported.. i had some in the list that were not supported so i removed
them and all is well now.

**Comment by jeff15110168** [comment]
The issue is I chose the ones from that list but then it fails. And it seems a lot of the listed codes have issues with testing

On Sep 21, 2017, at 6:01 PM, danmed <notifications@github.com<mailto:notifications@github.com>> wrote:

If you look at the Kat listing in Jackett it tells you which categories are
supported.. i had some in the list that were not supported so i removed
them and all is well now.

**Comment by garfield69** [comment]
Once #1920 is accepted, then on the next release of Jackett you will be able to use KickassTorrent on Sonarr.     
For example, if you are interested in all tv and movies then load the following categories on the KATcr Sonarr indexer `2000,2020,2030,2040,2050,2060,2070,5030,5040,5050,5060,5070`
![image](https://user-images.githubusercontent.com/6933240/31107698-d243a292-a850-11e7-82ff-79f1d0f554df.png)
which should result in Sonarr searches like this:
![image](https://user-images.githubusercontent.com/6933240/31107728-fb2f02a0-a850-11e7-8772-712552fca714.png)
