### ISSUE TITLE
[Torrent9] New address .pe

### ISSUE THREAD

**Issue by cadavor** [Jackett/Jackett#1854]
Torrent9 change his domain from .cc to .pe

**Comment by garfield69** [comment]
resolved with c9f945a08e7e8d9e785f6b0badcf695d5d4fe722 and will be included in the very next pre-release or whenever the next full release is published.

**Comment by cadavor** [comment]
Thanks.

For impatient people, edit the config of Torrent9 and change the website url to .pe. It works

**Comment by kaso17** [comment]
You can simply change the address via the GUI too
