### ISSUE TITLE
Tehconnection doesn't work

### ISSUE THREAD

**Issue by Fyx0z** [Jackett/Jackett#186]
When I'm trying to add Tehconnection I'm getting the following error message: 
Configuration failed: Unable to login to TehConnection

**Comment by JigSawFr** [comment]
We need errors logs and more informations about your issue to help you.

**Comment by Fyx0z** [comment]
Here is the log (I removed the username & pw):

Jan 13, 2016 09:41:45 AM	Info	
AdminController Dispose 
Jan 13, 2016 09:41:45 AM	Info	
AdminController Dispose 
Jan 13, 2016 09:41:45 AM	Info	
  Content-type='application/json; charset=utf-8', content-length=819
Jan 13, 2016 09:41:45 AM	Info	
AdminController ExecuteAsync 
Jan 13, 2016 09:41:45 AM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync 
Jan 13, 2016 09:41:45 AM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()'
Jan 13, 2016 09:41:45 AM	Info	
ApiControllerActionInvoker InvokeActionAsync 
Jan 13, 2016 09:41:45 AM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
Jan 13, 2016 09:41:45 AM	Debug	
UnixLibCurlWebClient:GetString Returning InternalServerError => 
Jan 13, 2016 09:41:45 AM	Debug	
UnixLibCurlWebClient: Posting username=****&password=****&keeplogged=1&login=Log+In%21
Jan 13, 2016 09:41:45 AM	Debug	
UnixLibCurlWebClient:GetString(Url:https://tehconnection.eu/login.php)
Jan 13, 2016 09:41:45 AM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Configure()'
Jan 13, 2016 09:41:45 AM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='Configure()'
Jan 13, 2016 09:41:45 AM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Jan 13, 2016 09:41:45 AM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Configure()'
Jan 13, 2016 09:41:45 AM	Info	
HttpActionBinding ExecuteBindingAsync 
Jan 13, 2016 09:41:45 AM	Info	
HttpActionBinding ExecuteBindingAsync 
Jan 13, 2016 09:41:45 AM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Jan 13, 2016 09:41:45 AM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Jan 13, 2016 09:41:45 AM	Info	
ApiControllerActionSelector SelectAction Selected action 'Configure()'
Jan 13, 2016 09:41:45 AM	Info	
ApiControllerActionSelector SelectAction 
Jan 13, 2016 09:41:45 AM	Info	
AdminController ExecuteAsync 
Jan 13, 2016 09:41:45 AM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Jan 13, 2016 09:41:45 AM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Jan 13, 2016 09:41:45 AM	Info	
DefaultHttpControllerActivator Create 
Jan 13, 2016 09:41:45 AM	Info	
HttpControllerDescriptor CreateController 
Jan 13, 2016 09:41:45 AM	Info	
DefaultHttpControllerSelector SelectController Admin
Jan 13, 2016 09:41:45 AM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Jan 13, 2016 09:41:45 AM	Info

**Comment by duramato** [comment]
Also getting the same thing
````

When	Level	Message
Jan 13, 2016 04:16:09 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
Jan 13, 2016 04:16:09 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Jan 13, 2016 04:16:09 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Jan 13, 2016 04:16:09 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Jan 13, 2016 04:16:09 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Jan 13, 2016 04:16:09 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Jan 13, 2016 04:16:09 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Jan 13, 2016 04:16:09 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Jan 13, 2016 04:16:09 PM	Info	
ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Jan 13, 2016 04:16:09 PM	Info	
ApiControllerActionSelector SelectAction 
Jan 13, 2016 04:16:09 PM	Info	
AdminController ExecuteAsync 
Jan 13, 2016 04:16:09 PM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Jan 13, 2016 04:16:09 PM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Jan 13, 2016 04:16:09 PM	Info	
DefaultHttpControllerActivator Create 
Jan 13, 2016 04:16:09 PM	Info	
HttpControllerDescriptor CreateController 
Jan 13, 2016 04:16:09 PM	Info	
DefaultHttpControllerSelector SelectController Admin
Jan 13, 2016 04:16:09 PM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Jan 13, 2016 04:16:09 PM	Info	
  http://supergonkas.uk.to:9117/admin/GetLogs?_=1452701756472
Jan 13, 2016 04:16:07 PM	Info	
AdminController Dispose 
Jan 13, 2016 04:16:07 PM	Info	
AdminController Dispose 
Jan 13, 2016 04:16:07 PM	Info	
  Content-type='application/json; charset=utf-8', content-length=835
Jan 13, 2016 04:16:07 PM	Info	
AdminController ExecuteAsync 
Jan 13, 2016 04:16:07 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync 
Jan 13, 2016 04:16:07 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()'
Jan 13, 2016 04:16:07 PM	Info	
ApiControllerActionInvoker InvokeActionAsync 
Jan 13, 2016 04:16:07 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
Jan 13, 2016 04:16:07 PM	Debug	
UnixLibCurlWebClient:GetString Returning InternalServerError => 
Jan 13, 2016 04:16:06 PM	Debug	
UnixLibCurlWebClient: Posting username=XXX&password=XXX&keeplogged=1&login=Log+In%21
Jan 13, 2016 04:16:06 PM	Debug	
UnixLibCurlWebClient:GetString(Url:https://tehconnection.eu/login.php)
Jan 13, 2016 04:16:06 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Configure()'
Jan 13, 2016 04:16:06 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='Configure()'
Jan 13, 2016 04:16:06 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Jan 13, 2016 04:16:06 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Configure()'
Jan 13, 2016 04:16:06 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Jan 13, 2016 04:16:06 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Jan 13, 2016 04:16:06 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Jan 13, 2016 04:16:06 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Jan 13, 2016 04:16:06 PM	Info	
ApiControllerActionSelector SelectAction Selected action 'Configure()'
Jan 13, 2016 04:16:06 PM	Info	
ApiControllerActionSelector SelectAction 
Jan 13, 2016 04:16:06 PM	Info	
AdminController ExecuteAsync 
Jan 13, 2016 04:16:06 PM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Jan 13, 2016 04:16:06 PM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Jan 13, 2016 04:16:06 PM	Info	
DefaultHttpControllerActivator Create 
Jan 13, 2016 04:16:06 PM	Info	
HttpControllerDescriptor CreateController 
Jan 13, 2016 04:16:06 PM	Info	
DefaultHttpControllerSelector SelectController Admin
Jan 13, 2016 04:16:06 PM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Jan 13, 2016 04:16:06 PM	Info	
  http://supergonkas.uk.to:9117/admin/configure_indexer
Jan 13, 2016 04:15:59 PM	Info	
AdminController Dispose 
Jan 13, 2016 04:15:59 PM	Info	
AdminController Dispose 
Jan 13, 2016 04:15:59 PM	Info	
  Content-type='application/json; charset=utf-8', content-length=1109
```

**Comment by JigSawFr** [comment]
No problem on tracker's side ? 

```
Returning InternalServerError
````

**Comment by duramato** [comment]
The trackers site is working just fine for me

**Comment by Fyx0z** [comment]
Tracker is working fine for me too

**Comment by flightlevel** [comment]
Works here on mono.
What OS, mono version and confirm you are using `--IgnoreSslErrors true`  https://github.com/Jackett/Jackett/issues/82#issuecomment-162443570

**Comment by Fyx0z** [comment]
Ubuntu 14.04

Mono JIT compiler version 3.10.0 (tarball Wed Nov  5 12:50:04 UTC 2014)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           __thread
    SIGSEGV:       altstack
    Notifications: epoll
    Architecture:  amd64
    Disabled:      none
    Misc:          softdebug
    LLVM:          supported, not enabled.
    GC:            sgen

**Comment by Fyx0z** [comment]
TehC started working for me after adding --IgnoreSslErrors

**Comment by Azerelat** [comment]
Testing shows no problem from windows.

Odds are your SSL certificate chain is out of date, either use the switch above or update them.

Mono 3 :(

**Comment by duramato** [comment]
That start up option works but currently im using an upstart script. Would it be possible to add this as an UI option?
