### ISSUE TITLE
No results returned from indexer [sonarr > zooqle]

### ISSUE THREAD

**Issue by ShadeBlack** [Jackett/Jackett#1864]
hi. just wanted to confirm if anyone is able to successfully add zooqle as an indexer within sonarr.
I have other indexers via jackett in sonarr that test and save correctly, but when adding zooqle, I received a notice: 'No results were returned from your indexer, please check your settings.'

I've checked both sonarr and jackett logs and can't find anything that might relate to the error.
inside of Jackett, I can manually search and that works fine, so I'm unsure if this is a jackett or sonarr problem.

Jackett version:  
windows > 0.8.216.0

Is this just me or is zooqle not fully supported at the moment?

**Comment by HidyHo** [comment]
I'm also having same issue trying to add this to Sonarr.  I am assuming this is Sonarr issue since everything works fine in Jackett.

**Comment by garfield69** [comment]
When I create the Zooqle definition, I tested it only on the Jackett Dashboard.     
But now that I've installed Sonarr on my sandbox for additional testing, I have replicated the problem and I can see what I need to change. Working on a fix.

**Comment by garfield69** [comment]
Amend your Sonarr indexer definition for *Zooqle* by replacing its *default categories* with categories `2000,3000,4000,4050,5000,5070,7010,8000` and you should be able to use it fine.      
![image](https://user-images.githubusercontent.com/6933240/30772416-3f0ed004-a0ae-11e7-85fb-5b0c2d5bbbd9.png)

**Comment by HidyHo** [comment]
Thanks garfield69.  The change worked for me as well 👍

**Comment by ShadeBlack** [comment]
I can also confirm this is now working for me.
Thanks garfield! wonderful work!

**Comment by garfield69** [comment]
excellent. this ticket can be closed.
