### ISSUE TITLE
Jackett being blocked by Bitdefender

### ISSUE THREAD

**Issue by maseren** [Jackett/Jackett#1875]
Hi Everyone,

Jackett as of today is being blocked by Bitdefender. Its blocking an attempt to go to this IP address:

104.18.54.151

Similar IP addresses are also being blocked. I am currently running Jackett Version 0.8.199.0 running on a PC. 

Is this something for me to be concerned about? Do I have the most updated version by chance?

I'm mainly concerned that their might be a security issue with the application. It was running fine as of yesterday. 

Log Follows:

When | Level | Message
-- | -- | --
Sep 21, 2017 03:22:37 PM | Error | On attempt 3 checking for results from YTS: An error occurred while sending the request.
Sep 21, 2017 03:22:37 PM | Error | On attempt 3 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 03:22:37 PM | Error | On attempt 3 checking for results from Demonoid: An error occurred while sending the request.
Sep 21, 2017 03:22:36 PM | Error | On attempt 2 checking for results from YTS: An error occurred while sending the request.
Sep 21, 2017 03:22:36 PM | Error | On attempt 2 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 03:22:36 PM | Error | On attempt 2 checking for results from Demonoid: An error occurred while sending the request.
Sep 21, 2017 03:22:36 PM | Error | On attempt 1 checking for results from YTS: An error occurred while sending the request.
Sep 21, 2017 03:22:36 PM | Error | On attempt 1 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 03:22:36 PM | Error | On attempt 1 checking for results from Demonoid: An error occurred while sending the request.
Sep 21, 2017 03:17:52 PM | Error | Error checking for updates.
Sep 21, 2017 03:17:31 PM | Error | Error checking for updates.
Sep 21, 2017 03:16:09 PM | Error | On attempt 3 checking for results from Demonoid: An error occurred while sending the request.
Sep 21, 2017 03:16:09 PM | Error | On attempt 3 checking for results from YTS: An error occurred while sending the request.
Sep 21, 2017 03:16:09 PM | Error | On attempt 3 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 03:16:08 PM | Error | On attempt 2 checking for results from Demonoid: An error occurred while sending the request.
Sep 21, 2017 03:16:08 PM | Error | On attempt 2 checking for results from YTS: An error occurred while sending the request.
Sep 21, 2017 03:16:08 PM | Error | On attempt 2 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 03:16:08 PM | Error | On attempt 1 checking for results from Demonoid: An error occurred while sending the request.
Sep 21, 2017 03:16:08 PM | Error | On attempt 1 checking for results from YTS: An error occurred while sending the request.
Sep 21, 2017 03:16:08 PM | Error | On attempt 1 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 12:38:27 PM | Error | On attempt 3 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 12:38:26 PM | Error | On attempt 2 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 12:38:26 PM | Error | On attempt 1 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 11:37:51 AM | Error | On attempt 3 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 11:37:50 AM | Error | On attempt 2 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 11:37:50 AM | Error | On attempt 1 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 10:37:15 AM | Info | Found 100 (2 new) releases from RARBG
Sep 21, 2017 10:35:43 AM | Info | Found 50 (0 new) releases from EZTV
Sep 21, 2017 10:35:42 AM | Info | Found 6 (3 new) releases from The Pirate Bay
Sep 21, 2017 10:20:13 AM | Info | Found 6 (3 new) releases from The Pirate Bay
Sep 21, 2017 10:20:11 AM | Info | Found 50 (2 new) releases from EZTV
Sep 21, 2017 10:04:42 AM | Info | Found 4 (0 new) releases from The Pirate Bay
Sep 21, 2017 10:04:40 AM | Info | Found 50 (0 new) releases from EZTV
Sep 21, 2017 09:56:29 AM | Info | Found 100 (100 new) releases from RARBG
Sep 21, 2017 09:56:11 AM | Info | Found 6 (6 new) releases from The Pirate Bay
Sep 21, 2017 09:56:03 AM | Info | Found 50 (47 new) releases from EZTV
Sep 21, 2017 09:36:39 AM | Error | On attempt 3 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 09:36:38 AM | Error | On attempt 2 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 09:36:38 AM | Error | On attempt 1 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 08:36:04 AM | Error | On attempt 3 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 08:36:03 AM | Error | On attempt 2 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 08:36:03 AM | Error | On attempt 1 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 07:35:27 AM | Error | On attempt 3 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 07:35:27 AM | Error | On attempt 2 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 07:35:26 AM | Error | On attempt 1 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 06:34:52 AM | Error | On attempt 3 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 06:34:51 AM | Error | On attempt 2 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 06:34:51 AM | Error | On attempt 1 checking for results from RARBG: An error occurred while sending the request.
Sep 21, 2017 06:32:06 AM | Error | Error checking for updates.
Sep 21, 2017 05:34:15 AM | Error | On attempt 3 checking for results from RARBG: An error occurred while sending the request.

**Comment by kaso17** [comment]
It's a random cloudflare IP not sure to which indexers it belong directly, what happens if you try to access it in your browser? I would expect it get's blocked too.

**Comment by maseren** [comment]
Hi kaso, what exactly is cloudflare? Should I unblock it? Is it safe? The
strange thing is this popped up after a bit. What I've done for now is
removed jackett and reinstalled it and that seems ok for now. Concerned for
the future though.

**Comment by kaso17** [comment]
Cloudflare is an anti ddos/load reducing/optimization proxy used by many websites (including plenty of torrent websites). I guess the IP is/was used by some website distributing malware and got blacklisted by bitdefender. As the IPs are shared by several websites that caused your problem. I guess by now it was already unblocked again.
