### ISSUE TITLE
Strange results with Xthor & Sonarr

### ISSUE THREAD

**Issue by itdaboyz** [Jackett/Jackett#1883]
Hi,

When doing a search with Sonarr, I have strange result with Xthor (and only Xthor).
Example here, searching for "100 S04E01" but it happens with every search via Sonarr : 
https://i.imgur.com/ycR0Avz.png

In Jackett's logs : https://i.imgur.com/IPAJ6Nd.png

And I have good results if I use Jackett's search function : https://i.imgur.com/vmtjoO0.png

Jackett version: 0.8.225.0

**Comment by kaso17** [comment]
what happens if you do a manual search without the quotes?

**Comment by itdaboyz** [comment]
Manual search without the quotes doesn't show what I want because my example is not good (100 is not precise enough in this case).

Let's take American Dad S04E01 as example then.
Sonarr search will show strange results (Couchpotato also btw) and manual search will show the good results, with or without quotes.

If I set up Xthor for Couchpotato, CP will download my wanted movie with wrong files : 

> Snatched "Pirates.of.the.Caribbean.Dead.Men.Tell.No.Tales.2017.MULTi.TRUEFRENCH.1080p.BluRay.DTS.HDMA.7.1.x264-Poney[Xthor]": What Happened to Monday (2017) in 1080p from TorrentPotato, localhost

> Snatched "Pirates.Of.The.Caribbean.Dead.Men.Tell.No.Tales.2017.MULTi.1080p.BluRay.x264-ZEST[Xthor]": Okja (2017) in 1080p from TorrentPotato, localhost

**Comment by kaso17** [comment]
Please provide the torznab query URLs used by Sonarr when searching.

**Comment by itdaboyz** [comment]
`http://localhost:9117/api/v2.0/indexers/xthor/results/torznab/api?t=tvsearch&cat=5030,5040,5050&extended=1&apikey=xxx&offset=0&limit=100&q=Brooklyn Nine Nine&season=5&ep=4 `
`Builded query for "brooklyn nine nine s05e04"... https://api.xthor.bz/?passkey=xxx&search=brooklyn+nine+nine+s05e04&category=14+16+15+17+13+98+30+34+33 `
https://i.imgur.com/PbmlOcB.png

I think it's because of the category parameter. If I try without it, it returns good results. (So it's more on Xthor side, but we can fix it in Jackett).

**Comment by kaso17** [comment]
c58b9d58a90995113cafbc9f88589960508b0c7b adds tracker specific categories for xthor.
You'll have to update your sonar categories accordingly.

**Comment by itdaboyz** [comment]
That did it, thanks!
