### ISSUE TITLE
[blutopia] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by deom17** [Jackett/Jackett#1889]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

**Provide a description of the feature request or bug, the more details the better.**
I am trying to add blutopia to jackett. I am able to add it successfully but I get an error when testing. I have two instances of jackett running one on windows at my home and one on a vps running linux. Both jacket installs are not able to add blutopia.

If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.8.225.0

-------------------------------

When | Level | Message
-- | -- | --
Sep 23, 2017 07:31:07 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
Sep 23, 2017 07:31:07 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
Sep 23, 2017 07:31:07 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Sep 23, 2017 07:31:07 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
Sep 23, 2017 07:31:07 PM | Info | HttpActionBinding ExecuteBindingAsync
Sep 23, 2017 07:31:07 PM | Info | HttpActionBinding ExecuteBindingAsync
Sep 23, 2017 07:31:07 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Sep 23, 2017 07:31:07 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Sep 23, 2017 07:31:07 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
Sep 23, 2017 07:31:07 PM | Info | ApiControllerActionSelector SelectAction
Sep 23, 2017 07:31:07 PM | Info | ServerConfigurationController ExecuteAsync
Sep 23, 2017 07:31:07 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ServerConfigurationController
Sep 23, 2017 07:31:07 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ServerConfigurationController
Sep 23, 2017 07:31:07 PM | Info | DefaultHttpControllerActivator Create
Sep 23, 2017 07:31:07 PM | Info | HttpControllerDescriptor CreateController
Sep 23, 2017 07:31:06 PM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
Sep 23, 2017 07:31:06 PM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
Sep 23, 2017 07:31:06 PM | Info | http://127.0.0.1:9117/api/v2.0/server/logs?_=1506209454681
Sep 23, 2017 07:31:03 PM | Info | IndexerApiController Dispose
Sep 23, 2017 07:31:03 PM | Info | IndexerApiController Dispose
Sep 23, 2017 07:31:03 PM | Info | Content-type='application/json; charset=utf-8', content-length=5068
Sep 23, 2017 07:31:03 PM | Info | IndexerApiController ExecuteAsync
Sep 23, 2017 07:31:03 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Sep 23, 2017 07:31:03 PM | Error | {0}
Sep 23, 2017 07:31:02 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Sep 23, 2017 07:31:02 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Sep 23, 2017 07:31:02 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Sep 23, 2017 07:31:02 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Sep 23, 2017 07:31:02 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Test()'
Sep 23, 2017 07:31:02 PM | Error | ApiControllerActionInvoker InvokeActionAsync
Sep 23, 2017 07:31:02 PM | Error | ReflectedHttpActionDescriptor ExecuteAsync
Sep 23, 2017 07:31:02 PM | Info | Found 0 releases from Blutopia
Sep 23, 2017 07:31:02 PM | Debug | IWebClient: Returning NotFound => <!DOCTYPE html> <html class="no-js" lang="en">  <head>   <meta charset="utf-8">   <title>Error 404: Page Not Found - Blutopia</title>             <meta http-equiv="x-ua-compatible" content="ie=edge">       <meta name="viewport" content="width=device-width, initial-scale=1">       <meta name="description" content="">       <meta property="og:title" content="Blutopia">       <meta property="og:type" content="website">       <meta property="og:image" content="https://blutopia.xyz/img/rlm.png">       <meta property="og:url" content="https://blutopia.xyz">       <meta name="csrf-token" content="">            <link rel="shortcut icon" href="https://blutopia.xyz/favicon.ico" type="image/x-icon">   <link rel="icon" href="https://blutopia.xyz/favicon.ico" type="image/x-icon">          <link rel="stylesheet" href="https://blutopia.xyz/css/main/custom.css">   <link rel="stylesheet" href="https://blutopia.xyz/css/main/advbuttons.css">   <link rel="stylesheet" href="https://blutopia.xyz/css/vendor/vendor.min.css" />       </head>  <body>   <section class="container content" id="content-area" style="min-height: 344px;">     <h2></h2>     <div class="jumbotron shadowed">       <div class="container">         <h1 class="mt-5 text-center">           <i class="fa fa-question-circle text-warning"></i> Error 404: Page Not Found         </h1>         <div class="separator"></div>         <p class="text-center">The Requested Page Cannot Be Found! <br>Not Sure What Your Looking For But Check The Address And Try Again!</p>         <p class="text-center">           <a href="https://blutopia.xyz" role="button" class="btn btn-labeled btn-primary"><span class="btn-label"><i class="fa fa-home"></i></span>Go Home</a>         </p>       </div>     </div>   </section> </body>  </html>
Sep 23, 2017 07:31:02 PM | Debug | IWebClient.GetString(Url:https://blutopia.xyz/torrents/search?name=&category_id=1&type=BD50&order=created_at%3adesc)
Sep 23, 2017 07:31:02 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
Sep 23, 2017 07:31:02 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Test()'
Sep 23, 2017 07:31:02 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync
Sep 23, 2017 07:31:02 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Test()'
Sep 23, 2017 07:31:02 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Sep 23, 2017 07:31:02 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()'
Sep 23, 2017 07:31:02 PM | Info | HttpActionBinding ExecuteBindingAsync
Sep 23, 2017 07:31:02 PM | Info | HttpActionBinding ExecuteBindingAsync
Sep 23, 2017 07:31:02 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Sep 23, 2017 07:31:02 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Sep 23, 2017 07:31:01 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Test()'

**Comment by garfield69** [comment]
This should be closed as a duplicate of #1819
