### ISSUE TITLE
[Request] Private tracker - Mowga

### ISSUE THREAD

**Issue by topdollar3** [Jackett/Jackett#1890]
Requesting support for French Private Tracker Mowga

Tracker Name: Mowga
Tracker Content: HD Movies
Tracker URL : http://mowga.net
Tracker Language : French

Thank you

**Comment by garfield69** [comment]
Does this site require an Invite or is registration open?
If you have an invite, please sent it to kaso1717 -at- gmail.com :-)

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by topdollar3** [comment]
invite sent to kaso1717 at gmail.com

**Comment by kaso17** [comment]
got it, thank you. Don't know when I'll have time for it yet.

**Comment by kaso17** [comment]
@topdollar3 Is this tracker dead? getting only an empty page

**Comment by topdollar3** [comment]
@kaso17  it seems that this tracker has been shut down, you can close this request.

Thanks for you efforts, wish you all the best.
