### ISSUE TITLE
[Request] Private tracker - SceneHD

### ISSUE THREAD

**Issue by topdollar3** [Jackett/Jackett#1891]
Requesting support for Private Tracker SceneHD

Tracker Name: SceneHD
Tracker Content: HD Movies
Tracker URL : https://scenehd.org
Tracker Language : English

Thank you

**Comment by garfield69** [comment]
This should be closed as a duplicate of #3

**Comment by kaso17** [comment]
fixed via 10473c6bd306fa098a2fe1ab57a1ebd8268019a7
