### ISSUE TITLE
[torrentproject] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by hominid** [Jackett/Jackett#1893]
after adding "TorrentProject Public", it failed the test
 An error occured while testing this indexer
Found no results while trying to browse this tracker.
[log.txt](https://github.com/Jackett/Jackett/files/1327674/log.txt)

Jackett Version 0.8.225.0

**Comment by garfield69** [comment]
@hominid  torrentProject has been out of commission since around 30th August. There is not clear consensus on whether it will be back or if it is gone for good.      
This ticket can be closed.

**Comment by hominid** [comment]
Thanks for the update. It sounds like folks are prepared to drop this
option as soon as it seems advisable.

**Comment by ThorMeOut** [comment]
https://torrentproject2.se/ is the replacement

**Comment by garfield69** [comment]
>https://torrentproject2.se/ is the replacement

I cant find anything that confirms this is an official replacement.
Most likely it is a clone. as are the .com and .org. sites.
I see from whois, that all 3 domains were registered on the same day (2017-09-18), within a couple minutes of each other, so they are probably all from the same provider.
Given that no one has complained yet that these sites are malicious, I suppose it would be safe to create a definition and use it, until we hear one way or another about what the story is with the original site.
updates or feedback welcome.

**Comment by garfield69** [comment]
I note that most of the links at the bottom of the main page all point to the browse page:  *Metasearch, Trackers, About, TOR, Api, Feedback/Contact*
And that sorting does not work from the browse results (clicking on any of the sortby links dump you to the main page), but lat least they work on the search results page.

**Comment by garfield69** [comment]
Ah. But neither magnets or .torrent links are available on the primary search results.
A magnet link is available on the details page, but it uses the mylink.st service to provide the link, which the current Jackett Cardigann implementation cannot handle because of the captcha that site uses.
So no go at the moment.
