### ISSUE TITLE
[1337x] Error when Downloading in Sonarr

### ISSUE THREAD

**Issue by MVallee** [Jackett/Jackett#1895]
Jackett Version 0.8.225.0
Sonarr Version 2.0.0.4949

I have 1337x enabled in Sonarr and it finds releases but when it tries to download them I always get an error in Sonarr (Downloading torrent failed, HTTP request failed: [404:NotFound]) and multiple errors in Jackett (Failed download cookies, Failed download response, Error downloading).

I also have 1337x enabled in Radarr but it downloads movie releases just fine.

I don't know if everyone is having this issue or if it's just me. I'm not sure which logs would be helpful, I'm new to Sonarr and Jackett. Let me know what other info is needed. Thanks.

**Comment by supremacy2k** [comment]
I get the same error on DanishBits.
I test it, it works, i search, set it to download, it fails, 404 not found.

**Comment by kaso17** [comment]
fixed via 034edbd32a5fefab8b9c868bd8e87b249fe4ea4a

**Comment by kaso17** [comment]
@MVallee please provide a full log

**Comment by kaso17** [comment]
no reply, closing
