### ISSUE TITLE
Add Support for Audio/Music Search and Search Parameters. 

### ISSUE THREAD

**Issue by Qstick** [Jackett/Jackett#1896]
Add support to Jackett API for music/audio search to match Newznab spec and map received parameters to indexer specific searching parameters (Waffles, Gazelle based Indexers, etc.). 

Should include caps page tweak to add `<audio-search>`

`<audio-search available="yes" supportedParams="q,album,artist,label,year,genre"/>`

Reference:
https://inhies.github.io/Newznab-API/functions/#music-search
https://github.com/WhatCD/Gazelle/wiki/JSON-API-Documentation#torrent-search

-------------------------------

**Comment by kaso17** [comment]
I'll have a look at this soon

**Comment by Qstick** [comment]
Thanks @kaso17

**Comment by kaso17** [comment]
Initial work has been done via adcfade7f2a43ac6d8a1179041002300a4658e01
Redacted, Synthesiz3r and notwhat.cd now offer 
`<music-search available="yes" supportedParams="q,album,artist,label,year"/>`
genre is still missing, is there a full list of genre tags for these trackers available?

**Comment by Qstick** [comment]
@kaso17 Thanks. However the newznab standard seems to be `audio-search` instead of `music-search`.

As for the genre tags, I'm not sure.

**Comment by kaso17** [comment]
where's the audio-search coming from? The https://inhies.github.io/Newznab-API/functions/#music-search document only mentions music-search

**Comment by Qstick** [comment]
@kaso17 from every indexer that supports it:

dognzb:
```
<searching>
  <search available="yes" supportedParams="q,group" />
  <tv-search available="yes" supportedParams="q,rid,tvdbid,season,ep" />
  <movie-search available="yes" supportedParams="q,imdbid,genre" />
  <audio-search available="yes" supportedParams="q,album,artist,label,trak,year,genre" />
</searching>
```

nzbgeek:
```
<audio-search available="yes" supportedParams="q,album,artist,label,year,genre"/>
```

I'm sure we can find some more. 

when calling the api the music search does use `t=music`, however the `t=caps` call always returns `<audio-search`

**Comment by kaso17** [comment]
kind of inconsistent but I added audio-search via 6dc12f0d3c6438f6be13e6f9183ac531df6853d0

**Comment by Qstick** [comment]
@kaso17 I agree, unfortunately looks as though that’s been made the standard.
