### ISSUE TITLE
Question: How to index a forum

### ISSUE THREAD

**Issue by EffeF** [Jackett/Jackett#1897]
I am creating a new definition for a forum, there are no torrent files, but only magnet links. The magnet links are not shown on the results page, but you need to open the relative post, and press "like".

I did as explained [here](https://github.com/Jackett/Jackett/wiki/Definition-format#download), but after getting the link magnet as I show it in Jackett's results?

**Comment by kaso17** [comment]
The indirect download feature doesn't support magnet links. The problem is that the the client would do a http request and then get a redirect to a magnet url. Many clients don't support this.
Due to that you would have to get the magnet links during the search (One extra request for each release). 
You'll have to implement it as a native c# indexer (cardigann definitions don't support this).

**Comment by EffeF** [comment]
And if instead of making a request for each release the request was made only when you click the magnet links in Jackett? Would this be feasible?

I do not know C#, I would not know how to make a native indexer.

**Comment by kaso17** [comment]
not sure  if this would be possible with javascript and a single click. It would be limited to manual search too. It wouldn't work with torznab/potatofeeds.
You could try to rewrite the download link to an http://itorrents.org/ link in the download block, that should work (assuming the torrents listed in the forum are available via itorrents.org).

**Comment by kaso17** [comment]
Or is there a standard supported by the popular torrent clients to pass the magnet link as part of an file?

**Comment by EffeF** [comment]
I had thought itorrents, but not all the magnet links are available through it... I could try it with it, I would lose only part of the releases.

But even if I could to show the links to Jackett I would have another problem. 
If I search for a movie I have as a result a post, a post equals a magnet link for movies, and it is ok.
However, If I search for a TV series I have as a result a post, a post equals many magnet link, one for any episode.

Even using itorrents there is no way, i presume, to manage multiple torrent files for each search result, right?

**Comment by kaso17** [comment]
No, that definitely looks like a case for a custom c# implementation.

**Comment by EffeF** [comment]
I got it, unfortunately I do not have the skills to do it
