### ISSUE TITLE
Below

### ISSUE THREAD

**Issue by Carlosgrr** [Jackett/Jackett#190]
On the main screen of Jackett, item 3 of the "Adding a Jackett indexer in Sonarr", it reads:
For the API key using the key below.

The problem is: the API key is above, not below...

**Comment by raspdealer** [comment]
https://github.com/Jackett/Jackett/pull/193

Ahahahah never noticed that.

**Comment by raspdealer** [comment]
Fixed. You can update and close. Thanks.
