### ISSUE TITLE
MagnetDL Tracker Failing in Sonarr Jackett Version 0.8.225.0 

### ISSUE THREAD

**Issue by OasisFounder** [Jackett/Jackett#1901]
Only message proceeded in logs of sonar:

 Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings.

Error still present after changing/adding default 5030,5040 categories to include 5000

**Comment by garfield69** [comment]
change the categories in your Sonarr MagnetDL indexer definition to 2000,5000 and try again.

**Comment by OasisFounder** [comment]
Thanks - this fixed it
