### ISSUE TITLE
Zoogle Tracker Failing in Sonarr Jackett Version 0.8.225.0

### ISSUE THREAD

**Issue by OasisFounder** [Jackett/Jackett#1903]
Received this error in Sonarr:

Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings.

Error did not change after adding categories 5000,5070 as configured through Jackett

**Comment by garfield69** [comment]
change your Sonarr categories in the Zooqle indexer definition to 2000,5000,5070 and try again.

**Comment by zero77** [comment]
This is the same for Radarr but changing the categories doesn’t seam to work.

**Comment by garfield69** [comment]
this is the sonarr indexer setup I used for Zooqle which passes the test & save for me
![image](https://user-images.githubusercontent.com/6933240/31090862-a4e83e7a-a805-11e7-9667-2801e59239d3.png)

**Comment by jeff15110168** [comment]
weird, that worked. Could someone help with trying to figure out the correct categories required for each? I can't get KAT to work properly.

**Comment by OasisFounder** [comment]
Problem seems to be resolved for me

**Comment by garfield69** [comment]
@zero77  Radarr is for movies only. so set your Zooqle torznab indexer category to `2000`
![image](https://user-images.githubusercontent.com/6933240/31114951-e7c0cc36-a87c-11e7-9f19-d4e7d35875d4.png)

**Comment by zero77** [comment]
I gave both 2000,5000,5070 and only 2000 a try it is very slow to accept it in Radarr but, when it does it doesn’t return any results in Raddar and there no logs in jacket relating to zooqle.

**Comment by kaso17** [comment]
please provide the toznab request url from the sonarr log
