### ISSUE TITLE
[thepiratebay] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by GarethRobson200** [Jackett/Jackett#1904]
Jackett version:  0.8.225.0

Log files attached.
I tried browsing to https://pirateproxy.cam/recent which I beleive is where the issue is reporting a "MOVED PERMANENTALLY" response but in my browser this opens fine.
[log.txt](https://github.com/Jackett/Jackett/files/1344107/log.txt)

**Comment by christronyxyocum** [comment]
Why not just use one of the real URLs, IE: https://thepiratebay.org/, which is working perfectly for me right now with version 0.8.225.0.

**Comment by GarethRobson200** [comment]
I'm just using the "built in" pirate bay item as I believe this should be using a list of pirate bay sites that changes when one goes down meaning less work to keep it going.....in theory

**Comment by garfield69** [comment]
Your log shows you have defined your Jackett TPB indexer definition Site Link as pirateproxy.cc, which is why you are getting the redirect error.     
Change your Jackett TPB definition Site Link to pirateproxy.cam and you will succeed as I did when I tested this just now.
