### ISSUE TITLE
[torrentz2] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by komainu85** [Jackett/Jackett#1906]
Jackett Version 0.8.225.0
Mono Version 2.6.2.7-8
Platform: Synology Diskstation DSM 6.1.3-15152 Update 5

Logs below. Same issue if I try ThePirateBay, however TV Chaos works fine.

Sep 29, 2017 09:01:43 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
-- | -- | --
Sep 29, 2017 09:01:43 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
Sep 29, 2017 09:01:43 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Sep 29, 2017 09:01:43 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
Sep 29, 2017 09:01:43 PM | Info | HttpActionBinding ExecuteBindingAsync
Sep 29, 2017 09:01:43 PM | Info | HttpActionBinding ExecuteBindingAsync
Sep 29, 2017 09:01:43 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Sep 29, 2017 09:01:43 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Sep 29, 2017 09:01:43 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
Sep 29, 2017 09:01:43 PM | Info | ApiControllerActionSelector SelectAction
Sep 29, 2017 09:01:43 PM | Info | ServerConfigurationController ExecuteAsync
Sep 29, 2017 09:01:43 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ServerConfigurationController
Sep 29, 2017 09:01:43 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ServerConfigurationController
Sep 29, 2017 09:01:43 PM | Info | DefaultHttpControllerActivator Create
Sep 29, 2017 09:01:43 PM | Info | HttpControllerDescriptor CreateController
Sep 29, 2017 09:01:43 PM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
Sep 29, 2017 09:01:43 PM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
Sep 29, 2017 09:01:43 PM | Info | http://10.0.0.33:9117/api/v2.0/server/logs?_=1506715258112
Sep 29, 2017 09:01:38 PM | Info | IndexerApiController Dispose
Sep 29, 2017 09:01:38 PM | Info | IndexerApiController Dispose
Sep 29, 2017 09:01:38 PM | Info | Content-type='application/json; charset=utf-8', content-length=12305
Sep 29, 2017 09:01:38 PM | Info | IndexerApiController ExecuteAsync
Sep 29, 2017 09:01:38 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Sep 29, 2017 09:01:38 PM | Error | {0}
Sep 29, 2017 09:01:38 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Sep 29, 2017 09:01:37 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Sep 29, 2017 09:01:37 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Sep 29, 2017 09:01:37 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Sep 29, 2017 09:01:37 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Test()'
Sep 29, 2017 09:01:37 PM | Error | ApiControllerActionInvoker InvokeActionAsync
Sep 29, 2017 09:01:37 PM | Error | ReflectedHttpActionDescriptor ExecuteAsync
Sep 29, 2017 09:01:37 PM | Info | Found 0 releases from Torrentz2
Sep 29, 2017 09:01:37 PM | Debug | IWebClient: Returning NotImplemented =>
Sep 29, 2017 09:01:37 PM | Error | headerString:
Sep 29, 2017 09:01:37 PM | Error | cookies:
Sep 29, 2017 09:01:37 PM | Error | request.RawPOSTDdata:
Sep 29, 2017 09:01:37 PM | Error | request.Referer:
Sep 29, 2017 09:01:37 PM | Error | request.Cookies:
Sep 29, 2017 09:01:37 PM | Error | request.Url: https://torrentz2.eu/searchA?f=
Sep 29, 2017 09:01:37 PM | Error | request.Method: GET
Sep 29, 2017 09:01:37 PM | Error | got NotImplemented/InternalServerError
Sep 29, 2017 09:01:37 PM | Debug | IWebClient.GetString(Url:https://torrentz2.eu/searchA?f=)
Sep 29, 2017 09:01:37 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
Sep 29, 2017 09:01:37 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Test()'
Sep 29, 2017 09:01:37 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync
Sep 29, 2017 09:01:37 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Test()'
Sep 29, 2017 09:01:37 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Sep 29, 2017 09:01:37 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()'
Sep 29, 2017 09:01:37 PM | Info | HttpActionBinding ExecuteBindingAsync
Sep 29, 2017 09:01:37 PM | Info | HttpActionBinding ExecuteBindingAsync

**Comment by kaso17** [comment]
Please post the output of `curl -v https://torrentz2.eu/searchA`

**Comment by komainu85** [comment]
curl -v https://torrentz2.eu/searchA
* Failed to connect to torrentz2.eu port 443: Connection refused
curl: (7) Failed to connect to torrentz2.eu port 443: Connection refused

**Comment by komainu85** [comment]
Ive solved it, DNS was set to my local DNS server and not resolving the external domains correctly. Set to google on the NAS fixed it.
