### ISSUE TITLE
[IPTorrents] Season search strings not yielding individual episodes

### ISSUE THREAD

**Issue by swummer7** [Jackett/Jackett#1907]
I am having an issue with IPTorrents that is identical to the one brought up in this thread

“Jackett is not yielding results from Sonarr search string for missing season #1164”

I tried to look for the IPTorrents YML file, but none exists to modify to make the correction as outlined in the previous fix. Can this be fixed with an IPTorrents YML file? Is there another workaround with IPTorrents? Any help is much appreciated.

**Comment by kaso17** [comment]
Can you please provide an example?
http://127.0.0.1:9117/torznab/iptorrents?apikey=xxx&cat=5000&q=This+is+Us&season=1
Is working fine for me.

**Comment by swummer7** [comment]
So, maybe not specifically with that show. My example is that I am trying to add the series “Bojack Horseman” to Sonarr with an add and search. Sonarr only searches for past seasons at the season level, i.e. “Bojack Horseman s01”. The issue is that IPTorrents does not pull up all the individual episodes for season 1, but rather only searches the exact phrase as above. There are only 5 results with the above IPT search, eg. “Bojack Horseman s01-s03.” 

As in the referenced issue, if only “bojack horseman” was searched for, instead of the added “s01”, all individual episodes appear and can be pulled into sonarr.

As it is now, I try to add and search the whole season and not a single episode is auto retrieved, a manual search of each individual episode causes them all to start. I have had the same issue with other series. Either sonarr would need an option to search all individual episodes, or jackett could eliminate the season level search if an episode number is not included.

Does this make sense?

**Comment by kaso17** [comment]
This is a IPtorrent limitation (Searching only for season will show only episodes).
Unless you find a way of searching which returns complete seasons and single episodes this can't be fixed (not searching for the season at all is not an option).
I suggest you contact the IPtorrents team and let them know about this limitation/bug.
