### ISSUE TITLE
Fixed re-enable SSL on tracker side with BlueTigers Provider

### ISSUE THREAD

**Issue by xataz** [Jackett/Jackett#191]
Hello,

Bluetigers have re-enable SSL, can you please re-enable this ?

Thanks and regards

**Comment by raspdealer** [comment]
https://github.com/Jackett/Jackett/pull/192

**Comment by raspdealer** [comment]
Fixed. You can update and close. Thanks.

**Comment by dardano** [comment]
Any invite for me for bluetigers.net ? an invite on Ethor.net as exchange

**Comment by maxcore** [comment]
@dardano email me , maxcore.plante at gmail

**Comment by raspdealer** [comment]
Please do not do it here!!!!

**Comment by raspdealer** [comment]
and close it :)
