### ISSUE TITLE
How to ID unlisted category?

### ISSUE THREAD

**Issue by MisterC925** [Jackett/Jackett#1913]
Using Sonarr with Jackett on tvchaosuk.com.

If I do manual searches withing Jackett for a show in their "Foreign" category, I get a list of results but the category is blank.

As a result, searches from Sonarr (using 5000) fail for the same query.

I've tried all listed categories supported by the tvchaos setup and none return the results.

Is there as reasonably easy way to determine the category for currently unlisted categories?

Thanks!

**Comment by kaso17** [comment]
should be fixed with 211e80cb17a59d8164212c2ae2ce92dabbe3e0ba

**Comment by MisterC925** [comment]
Thanks!
