### ISSUE TITLE
Indexer failed DanishBits

### ISSUE THREAD

**Issue by Kamds** [Jackett/Jackett#1915]
Jackett version:  0.8.237.0

-------------------------------
I keep getting the error "[Getting release from indexer failed](https://i.imgur.com/liaXAdo.png)" when I try to download shows from DanishBits. The indexer works fine when I test it, and then goes back to Indexer unavailable due to failure when it tries to pull anything.

I'm only having this issues with DanishBits.

**Comment by supremacy2k** [comment]
Might be related to https://github.com/Jackett/Jackett/issues/1895

**Comment by kaso17** [comment]
dupe

**Comment by kaso17** [comment]
fixed via 034edbd32a5fefab8b9c868bd8e87b249fe4ea4a
