### ISSUE TITLE
[Request] Private tracker - koffiehuukske

### ISSUE THREAD

**Issue by filoor** [Jackett/Jackett#1917]
Requesting support for French Private Tracker koffiehuukske

Tracker Name: koffiehuukske
Tracker Content:  Dutch and International, as well as related documentaries, movies, music, reading and more.
Tracker URL : http://koffiehuukske.info/
Tracker Language : Dutch

its a open registration system

Thank you

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution
