### ISSUE TITLE
Sonarr API Translating is returning 0 results

### ISSUE THREAD

**Issue by Kyon147** [Jackett/Jackett#1924]
Hi all,

For some reason, Jackett is not translating the API search string from Sonarr into something the tracker can use to search. Here's an example request.

```
17-10-3 21:59:39.7|Debug|Torznab|Downloading Feed http://192.168.1.133:9117/api/v2.0/indexers/thepiratebay/results/torznab/api?t=tvsearch&cat=5030,5040,100205,5000&extended=1&apikey=(removed)&offset=0&limit=100&q=Doctor%20Foster&season=2
17-10-3 21:59:39.7|Debug|Torznab|Downloading Feed http://192.168.1.133:9117/api/v2.0/indexers/thepiratebay/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Doctor%20Foster&season=2
```
When browsing this via Chrome, it returns no result. Digging deeper, the results are not returned because the tracker does not know how to interpret &season and &ep which makes sense as the t=caps only mention q being accepted.

Jackett is not translating this correctly over to in this example The Pirate Bay. Removing the season and episode parameters return correct results in the browser. This is the same for KickAssTorrents and a couple others I have tested.

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
My results do not line up with what you have reported.      
I'm on Jackett 0.8.249 and Sonarr 2.0.0.4949      
A search on TPB for *doctor foster s02e05* yields 8 hits
![image](https://user-images.githubusercontent.com/6933240/31195627-6e0f2910-a9a7-11e7-9977-c7a4f7e48ad3.png)
and a Sonarr search for the same episode yields the corresponding 8 hits
![image](https://user-images.githubusercontent.com/6933240/31195658-848c63ce-a9a7-11e7-86c0-ba0dadca26ff.png)

The key here is that TPB uses custom categories, so in order to use Jackett TPB indexer on Sonarr, you have to replace the default Sonarr Torznab categories with ones that are used by TPB.      
I've set my Sonarr TPB categories for TV and MOVIES: `100201,100202,100203,100204,100205,100206,100207,100208,100209,100299`

I suspect something similar applies to the other indexers you are having problems with.
My Sonarr KAT categories are `100005,100006,100007,100041,100069,100071,100074,100075,100078,100079,100080,100081,100090,100118,100128,100133,100146,100148,100149,100150,100151,100152`

**Comment by Kyon147** [comment]
Your comment makes sense, I have for argument sake used your categories for both KAT and TPB. This is in the logs still. I'm using 
Jackett 0.8.246.0
Sonarr 2.0.0.4949
Mono 4.2.1

```
17-10-4 21:30:14.6|Info|NzbSearchService|Searching 3 indexers for [Rick and Morty : 2017-10-01]
17-10-4 21:30:14.6|Debug|Torznab|Downloading Feed http://192.168.1.133:9117/api/v2.0/indexers/thepiratebay/results/torznab/api?t=tvsearch&cat=100201,100202,100203,100204,100205,100206,100207,100208,100209,100299&extended=1&apikey=(removed)&offset=0&limit=100&q=Rick%20and%20Morty&season=2017&ep=10/01
17-10-4 21:30:14.6|Debug|Torznab|Downloading Feed http://192.168.1.133:9117/api/v2.0/indexers/kickasstorrent/results/torznab/api?t=tvsearch&cat=100005,100006,100007,100041,100069,100071,100074,100075,100078,100079,100080,100081,100090,100118,100128,100133,100146,100148,100149,100150,100151,100152&extended=1&apikey=(removed)&offset=0&limit=100&q=Rick%20and%20Morty&season=2017&ep=10/01
17-10-4 21:30:15.7|Info|NzbSearchService|Searching 3 indexers for [Rick and Morty : 2017-09-24]
17-10-4 21:30:15.7|Debug|Torznab|Downloading Feed http://192.168.1.133:9117/api/v2.0/indexers/thepiratebay/results/torznab/api?t=tvsearch&cat=100201,100202,100203,100204,100205,100206,100207,100208,100209,100299&extended=1&apikey=(removed)&offset=0&limit=100&q=Rick%20and%20Morty&season=2017&ep=09/24
17-10-4 21:30:15.7|Debug|Torznab|Downloading Feed http://192.168.1.133:9117/api/v2.0/indexers/kickasstorrent/results/torznab/api?t=tvsearch&cat=100005,100006,100007,100041,100069,100071,100074,100075,100078,100079,100080,100081,100090,100118,100128,100133,100146,100148,100149,100150,100151,100152&extended=1&apikey=(removed)&offset=0&limit=100&q=Rick%20and%20Morty&season=2017&ep=09/24
17-10-4 21:30:17.9|Debug|NzbSearchService|Total of 0 reports were found for [Rick and Morty : 2017-10-01] from 3 indexers
17-10-4 21:30:17.9|Info|DownloadDecisionMaker|No results found
17-10-4 21:30:17.9|Info|EpisodeSearchService|Episode search completed. 0 reports downloaded.
```

**Comment by garfield69** [comment]
how come your *rick and morty* is searching for a date (2017-10-01) instead of season=3 ep=10 ?

**Comment by Kyon147** [comment]
I have no idea ha! That was strange to me but I didn't know if that was normal or not as I am new to Jackett and Sonarr.

Do you know of any setting which could be causing it?

**Comment by garfield69** [comment]
I've done a little research and found that it has to do with you having set the *Rick and Morty* **Series Type**  as *Daily*. Switch it back to *Standard*.      
![image](https://user-images.githubusercontent.com/6933240/31213152-77e39124-aa01-11e7-802b-067052dca861.png)

**Comment by Kyon147** [comment]
Oh, strange I will have to take a look when I am back home later as I feel all of the shows are set to daily by default without me realising. 

Will let you know!
