### ISSUE TITLE
Problem on search with apostrophe

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#1926]
Hi, I think that is similar to an old problem with accent mark

In this case one space (I think) is missing

For example the movie:
Ace Ventura: Pet Detective

In my country the tile is:
Ace Ventura - L'acchiappanimali

So, correct me if I wrong, jackett search the original title and my local title but search
ace ventura lacchiappanimali

So the ' is missing and don't find any
If I try for example to search on ilcorsaronero you can see the difference
https://ilcorsaronero.info/argh.php?search=ace+ventura+l+acchiappanimali -> 1 results
https://ilcorsaronero.info/argh.php?search=ace+ventura+l%27acchiappanimali -> 1 results
https://ilcorsaronero.info/argh.php?search=ace+ventura+lacchiappanimali -> 0 results

Is a Jackett problem or, in this case, Sonarr problem?

**Comment by kaso17** [comment]
Does the jacket manual search return any results if you search for "Ace Ventura L'acchiappanimali"?
From my experience sonarr will strip any special characters from the search resulting in "ace ventura lacchiappanimali" in this case. In that case we can't fix it in jackett (unless ilcorsaronero supports searching by imdb id, which isn't the case AFAIK).
Please check the sonarr logs to find out the torznab request url.

**Comment by Jorman** [comment]
I said Sonarr, sorry I mean Radarr, but I think is the same at end.

So, if I search on Jackett "Ace Ventura L'acchiappanimali" I got results, so I think is about you said, Radarr and Sonarr strip out char!

Tnx for your support!
