### ISSUE TITLE
Error while adding RuTracker indexer

### ISSUE THREAD

**Issue by puwin** [Jackett/Jackett#1928]
Jackett version:  Jackett Version 0.8.246.0
Mono version:  5.2.0.0 (Mac)

-------------------------------

I have an issue while adding RuTracker to indexer list, and I'm not sure what causes the problem. Every other tracker works as intended, but when I try to add RuTracker I get an error:

![screen shot 2017-10-05 at 23 26 34](https://user-images.githubusercontent.com/32548066/31250872-d1454eec-aa24-11e7-884b-d06fd6523948.png)

Also logs don't tell much:

![screen shot 2017-10-05 at 23 23 19](https://user-images.githubusercontent.com/32548066/31250904-e9268166-aa24-11e7-8261-b6a43ffc6c23.png)

**Comment by kaso17** [comment]
Please provide a full enhanced log (the one you posted looks like the standard log). Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by puwin** [comment]
![screen shot 2017-10-08 at 18 16 32](https://user-images.githubusercontent.com/32548066/31318083-f2052fc6-ac54-11e7-91f5-66d39826cb32.png)

Probably full logs from /.config/Jackett/ would be more helpful?

**Comment by kaso17** [comment]
yes, please provide the log file

**Comment by garfield69** [comment]
no reply.
Since I don't have any problems adding and using rutracker with v0.8.500 I'm closing this one.
