### ISSUE TITLE
[worldwidetorrents] The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by eybox** [Jackett/Jackett#1930]
Haven't seen this one not reported yet. Here's the error:

An error occured while testing this indexer
Exception (worldwidetorrents): Request to https://worldwidetorrents.me/torrents-search.php failed (Error 522) - The tracker seems to be down.: Request to https://worldwidetorrents.me/torrents-search.php failed (Error 522) - The tracker seems to be down.

Jackett Version 0.8.225.0 (running as Docker on UnRaid OS)

**Comment by garfield69** [comment]
yup, looks like the site has crashed.      
the cloudflare 522 is a timeout error, the site was not responding when you did your test.     
right now, wwt is responding with a raw server configuration file list
![image](https://user-images.githubusercontent.com/6933240/31291702-251aaa40-ab2d-11e7-90aa-aca603e67eef.png)
so it looks like the site is in a bit of trouble.

**Comment by garfield69** [comment]
Well at least someone is working on WWT, we're now seeing a **Upgrading Hardware , Be Back** page.

**Comment by garfield69** [comment]
WWT is back up running and the Jackett test is now successful.       
this ticket can be closed.
