### ISSUE TITLE
Jackett functions detected as viruses by Bitdefender 2018

### ISSUE THREAD

**Issue by maseren** [Jackett/Jackett#1932]
Good Morning Everyone, 

I noticed an issue with Bitdefender detecting certain aspects of Jackett as viruses. This hasn't stopped the functioning of Jackett from what I can tell but it is concerning. Any ideas what might be the cause would?

![image](https://user-images.githubusercontent.com/32177154/31281544-bf3b544a-aa7d-11e7-9f1d-4a78b8cc7ea1.png)
![image](https://user-images.githubusercontent.com/32177154/31281560-d000c3c8-aa7d-11e7-9d5b-8f0e1fecb287.png)

**Comment by garfield69** [comment]
its a false hit. I uploaded the latest jacketttray.exe to VirusTotal (they provide a virus consensus web site) and here is the result https://www.virustotal.com/#/file/f999542d0685376179492e79f36f0acc67ce0bbfd82ea563a36aab549598b367/detection
just one of 65 engines flagged is as suspicious.
You can do the same for your files if you want personal confirmation. start by accessing https://www.virustotal.com and follow the prompts.
