### ISSUE TITLE
Awesome-HD not working

### ISSUE THREAD

**Issue by antigravity83** [Jackett/Jackett#1943]
Can't add Awesome-HD to Sonarr/Radarr. Connects and searches ok in Jackett itself. Added cookie as per wiki.

Jackett Logs: https://pastebin.com/utL4cNk8
Radarr Logs: https://pastebin.com/9gPYmCB0

Jackett version:  0.8.246.0

**Comment by garfield69** [comment]
related to #1481 and #1352     
Essentially the existing definition may benefit from reworking, by switching from Cardigann to GazelleTracker.     
A quick look at the definition in its current form suggest to me that it is not set up to handle Sonarr/Radarr requests.

@kaso17  whats the policy with these invites? I mean, once you have received one and set up an account, are the login details available to the Jackett devs for the asking while the work on a fix, or is it strictly a personal account for private use only?

**Comment by kaso17** [comment]
@garfield69 the corresponding tracker rules apply (If they don't allow account sharing it applies to jackett devs too).
not sure what the current situation regarding the AHD invite system is. An invite is needed. @antigravity83 can you help with that?

**Comment by antigravity83** [comment]
Unfortunately I've only just been added to the site so don't have any invites to use. 

When I get one happy to send it your way

**Comment by chriswiduta** [comment]
+1 same symptoms. tests ok in jackett, can not be added to radarr because it fails test.

**Comment by chriswiduta** [comment]
I have messaged this issue to the staff.

**Comment by chriswiduta** [comment]
UPDATE: AHD provides integration directly with Radarr, jackett is not needed

**Comment by pyr0ball** [comment]
@chriswiduta There doesn't seem to be any documentation readily available as to how to add AHD to radarr. Any chance you could elaborate?

**Comment by Sibicle** [comment]
> UPDATE: AHD provides integration directly with Radarr, jackett is not needed

There is currently no good way to prioritize one movie torrent tracker over another in radarr:

https://feathub.com/Radarr/Radarr/+16

which means that if one wants to select priority, they need to use jackett to query their trackers, add them to nzbhydra with the jackett api to organize their priority, and finally add the nzbhydra feed to radarr. 

😅

**Comment by pyr0ball** [comment]
AHD also has TV uploads and sonarr does not include AHD integration, which jackett could provide

**Comment by chriswiduta** [comment]
> 
> 
> > UPDATE: AHD provides integration directly with Radarr, jackett is not needed
> 
> There is currently no good way to prioritize one movie torrent tracker over another in radarr:
> 
> https://feathub.com/Radarr/Radarr/+16
> 
> which means that if one wants to select priority, they need to use jackett to query their trackers, add them to nzbhydra with the jackett api to organize their priority, and finally add the nzbhydra feed to radarr.
> 
> 😅

Prioritization is a separate issue in my option.

**Comment by Sibicle** [comment]
> Prioritization is a separate issue in my option.

I agree, I am just giving the justification for the need to have AHD work properly with jackett. Ideally radarr would allow you to choose index priority, but that issue was opened over 2 years ago.

**Comment by garfield69** [comment]
Jackett 0.14.326
