### ISSUE TITLE
New Tracker Request - animetorrents.me (Windows installation)

### ISSUE THREAD

**Issue by archangel00uk** [Jackett/Jackett#195]
Hi,

Like to request for private tracker to animetorrents.me to be added, I can see in the old fork it had implemented - 

https://github.com/zone117x/Jackett/blob/master/src/Jackett/Indexers/AnimeTorrents.cs

But am unable to see it when configured into Windows - anyone able to help implement it within Windows? or advise how I can add?

Thanks.

**Comment by Azerelat** [comment]
Nothing wrong with the current implementation apart from the login doesn't work, if the login can be fixed it can be included again.

**Comment by archangel00uk** [comment]
oh didnt realise the login was not working.

**Comment by kaso17** [comment]
fixed with #600
