### ISSUE TITLE
document the OMDB feature

### ISSUE THREAD

**Issue by chrisjohnson00** [Jackett/Jackett#1958]
There's a new config value for OMDB but there isn't any documentation about this new feature.  This is a request to update the documentation for this feature.

**Comment by garfield69** [comment]
you mean the OMDB API key on the Jackett Dashboard?

**Comment by chrisjohnson00** [comment]
i do

**Comment by drewbitt** [comment]
Can see some OMDB discussion in #1617, added in #1509 

it is essentially used as a fallback to get the IMDB ID of a movie and was added for torrentpotato since it did not provide IMDB id's of movies

**Comment by alxlaxv** [comment]
Thanks @kaso17 , you can close this one now.
