### ISSUE TITLE
Torrentbytes.net - configuration failed

### ISSUE THREAD

**Issue by vectorlost** [Jackett/Jackett#196]
Hi, I just installed Jackett on windows. When I add torrentbytes.net as a "configured indexers in http://127.0.0.1:9117/Admin/Dashboard, I get the following error : 

"Configuration failed: Found no results while trying to browse this tracker"

Any clue why?

**Comment by flightlevel** [comment]
Weird, just tried on windows & mono and it worked perfectly adding the tracker.
Can you try again? Any unusual characters in your user/password?

**Comment by flightlevel** [comment]
Also, made a minor adjustment in the latest release which might have been causing a problem if there was no category
