### ISSUE TITLE
[xtremezone] Exception (xtremezone): Parse error: Parse error (Test)

### ISSUE THREAD

**Issue by davidst** [Jackett/Jackett#1964]
Jackett version:  0.8.259.0

Log:
> Error on 20171014102153 for Xtreme Zone.txtJackett.ExceptionWithConfigData: Login failed: No form found on https://www.myxz.org/login.php using form selector form
>    at Jackett.Indexers.CardigannIndexer.<DoLogin>d__15.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:line 433
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__25.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:line 1098

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.myxz.org/browse?search=&amp;incldead=1">here</a>.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at www.myxz.org Port 443</address>
</body></html>
```

**Comment by kaso17** [comment]
fixed via 3c61cb6f06d5dff990a3cc22795f748a4b3ebe8e
