### ISSUE TITLE
[M-Team] Other search page

### ISSUE THREAD

**Issue by qtv** [Jackett/Jackett#1965]
Right now you can search using Jackett at https://tp.m-team.cc/torrents.php which searches movies, TV etc. However, what Jackett does not do is search adult content since that is an actual different search page, https://tp.m-team.cc/adult.php. Since M-Team is, uh, popular for this sort of content it would be nice to be able to search adult content as well.

**Comment by kaso17** [comment]
fixed via 3863008846285e8a4b84d1bbe53ebf0b42faab0a
