### ISSUE TITLE
IPTorrents: Getting release from indexer failed

### ISSUE THREAD

**Issue by adajan** [Jackett/Jackett#197]
Hello folks, 

So just recently I've been getting this error every time Sonarr tries to grab a torrent from IPTorrent's index. https://gyazo.com/43230b2540447684138212f6d14c8ad4 

Other indexer's such as TorrentDay still work. I've deleted the current IPTorrents details on both programs, and reentered them. Yet the problem is still there. 

I think I found the problem, in the logs:
https://i.gyazo.com/a7788405bd71f0b756193482dc1bdb94.png

It shows that the download link has an extra /
https://iptorrents.com//download.php*
Removing the extra / by download fixes the problem.

**Comment by JigSawFr** [comment]
@adajan can you show us a *working* link ?

https://iptorrents.com/download.php/XXXXXXXXXXXXXXXXX ?

**Comment by duramato** [comment]
https://iptorrents.eu/download.php/1686353/UFC.Fight.Night.81.720p.HDTV.x264-KILLERS.torrent

**Comment by JigSawFr** [comment]
@duramato : new domain ?

**Comment by adajan** [comment]
Just removing a / out by download will make it a proper download link. It's just a typo in the code

**Comment by duramato** [comment]
@JigSawFr no they have several .com .me .eu .ru

**Comment by flightlevel** [comment]
@adajan 
Before creating an issue
1. search on the issue tracker, most of the time someone has had the same problem already
2. check you are on the latest release, we only support the latest release

https://github.com/Jackett/Jackett/issues/143
https://github.com/Jackett/Jackett/issues/125
