### ISSUE TITLE
IPT aliases configuration

### ISSUE THREAD

**Issue by neiliid** [Jackett/Jackett#1973]
I picked up an odd issue when trying to use one of the IPT aliases. I am in a region where access to IPT is blocked using the traditional URLS.

Each time I tried to add IPT using one of the aliases Jackett would report an error and not add the URL. It appears that when the config is first opened, Jackett attempts to make a call to the standard URLs, if this fails, then you cannot configure with one of aliases.

The work around was to connect the machine to a VPN in a region that was not blocking IPT, then configure Jackett with an alias URL, then disconnect the VPN. 

After this it seems to work without any problems.

Cheers

**Comment by kaso17** [comment]
This is handled in #1473
