### ISSUE TITLE
Sonarr is not able to connect to jacket 500 error

### ISSUE THREAD

**Issue by skluthe** [Jackett/Jackett#1984]
I'm using the docker container for jackett and running it on openmediavault with port 9117 open and tried both with authentication and without. Also tried domain name that redirects to jackett and just using the ip and port. they're on the same network with a hairpin nat and a reverse proxy sitting on the wan that forwards based on the subdomain that is requesting a connection.

HTTP Error - Res: [GET] https://jackett.sklu3.us/api/v2.0/indexers/torrentz2/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100: 500.InternalServerError
{
  "result": "error",
  "error": "Exception (torrentz2): An error occurred while sending the request: An error occurred while sending the request",
  "stacktrace": "  at Jackett.Indexers.BaseIndexer+<ResultsForQuery>c__async1.MoveNext () [0x0011f] in <431b593737d5408c91cdc3cdb49f985b>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at Jackett.Indexers.BaseWebIndexer+<ResultsForQuery>c__asyncC.MoveNext () [0x0006b] in <431b593737d5408c91cdc3cdb49f985b>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at Jackett.Controllers.V20.ResultsController+<Torznab>c__async1.MoveNext () [0x002e1] in <431b593737d5408c91cdc3cdb49f985b>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Threading.Tasks.TaskHelpersExtensions+<CastToObject>d__3`1[T].MoveNext () [0x00063] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__18`1[TResult].MoveNext () [0x001da] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Web.Http.Controllers.ApiControllerActionInvoker+<InvokeActionAsyncCore>d__0.MoveNext () [0x000c7] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__18`1[TResult].MoveNext () [0x001da] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__5.MoveNext () [0x0009d] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__5.MoveNext () [0x001f6] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__0.MoveNext () [0x0011b] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__5.MoveNext () [0x0009d] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__5.MoveNext () [0x001f6] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__0.MoveNext () [0x0011b] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Web.Http.Controllers.ActionFilterResult+<ExecuteAsync>d__2.MoveNext () [0x001f1] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Web.Http.Filters.AuthorizationFilterAttribute+<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext () [0x00109] in <f99f496cb0d249c1a945c1fcabce1695>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Web.Http.Controllers.ExceptionFilterResult+<ExecuteAsync>d__0.MoveNext () [0x00097] in <f99f496cb0d249c1a945c1fcabce1695>:0 ",
  "innerstacktrace": "  at System.Net.Http.HttpClientHandler+<SendAsync>d__63.MoveNext () [0x004ab] in <149d36f59bb1479fbc679af921c4ba4a>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at CloudFlareUtilities.ClearanceHandler+<SendAsync>d__15.MoveNext () [0x0010f] in <2a9dc05438c84af3aa7d27cc128eeed6>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <149d36f59bb1479fbc679af921c4ba4a>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at Jackett.Utils.Clients.HttpWebClient+<Run>c__async0.MoveNext () [0x004ee] in <431b593737d5408c91cdc3cdb49f985b>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at Jackett.Utils.Clients.IWebClient+<GetString>c__async2.MoveNext () [0x000fa] in <431b593737d5408c91cdc3cdb49f985b>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at Jackett.Indexers.BaseWebIndexer+<RequestStringWithCookies>c__async3.MoveNext () [0x000e6] in <431b593737d5408c91cdc3cdb49f985b>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at Jackett.Indexers.CardigannIndexer+<PerformQuery>c__async5.MoveNext () [0x008d8] in <431b593737d5408c91cdc3cdb49f985b>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 \n  at Jackett.Indexers.BaseIndexer+<ResultsForQuery>c__async1.MoveNext () [0x000ab] in <431b593737d5408c91cdc3cdb49f985b>:0 "
}

**Comment by skluthe** [comment]
It also looks like jackett can't search any indexers.

**Comment by skluthe** [comment]
Name resolution failed when searching on indexers. I'll take a look at my dns settings.

**Comment by skluthe** [comment]
Looks like DHCP is handing out the correct DNS servers and they show up in /etc/resolv.conf on the container. I don't believe I'm able to ping from this container though.

**Comment by skluthe** [comment]
![image](https://user-images.githubusercontent.com/23664304/31785500-35d28f88-b4ba-11e7-863b-a97a29da991e.png)
This is the error I get when searching an indexer.

**Comment by skluthe** [comment]
I was able to use curl to verify that name resolution is working. I am able to connect to google.com and my own website. I'm not sure where to go from here as far as troubleshooting goes. Sorry for all of the comments, I'm just trying to provide as much info as possible.

**Comment by skluthe** [comment]
Here are the container details from my OMV docker container:

[
    {
        "Id": "da36c967d0edcdc39d34c0c1808ea84e14765ecd7c8ae2e5f23f0ccc2d4ac378",
        "Created": "2017-10-19T17:40:37.573043724Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 4403,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-10-19T17:40:38.653737483Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:7fd1687d591c520e258906f6875914bf8e0f57395e022e2c68bc791e0209cefa",
        "ResolvConfPath": "/var/lib/docker/openmediavault/containers/da36c967d0edcdc39d34c0c1808ea84e14765ecd7c8ae2e5f23f0ccc2d4ac378/resolv.conf",
        "HostnamePath": "/var/lib/docker/openmediavault/containers/da36c967d0edcdc39d34c0c1808ea84e14765ecd7c8ae2e5f23f0ccc2d4ac378/hostname",
        "HostsPath": "/var/lib/docker/openmediavault/containers/da36c967d0edcdc39d34c0c1808ea84e14765ecd7c8ae2e5f23f0ccc2d4ac378/hosts",
        "LogPath": "/var/lib/docker/openmediavault/containers/da36c967d0edcdc39d34c0c1808ea84e14765ecd7c8ae2e5f23f0ccc2d4ac378/da36c967d0edcdc39d34c0c1808ea84e14765ecd7c8ae2e5f23f0ccc2d4ac378-json.log",
        "Name": "/jackett",
        "RestartCount": 0,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc/localtime:/etc/localtime:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "9117/tcp": [
                    {
                        "HostIp": "10.0.100.11",
                        "HostPort": "9117"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "10b5ba88bc11ea3a86306dc9aa16bb6090313f31b639c289dd0b7449961429d4",
                "Source": "/var/lib/docker/openmediavault/volumes/10b5ba88bc11ea3a86306dc9aa16bb6090313f31b639c289dd0b7449961429d4/_data",
                "Destination": "/downloads",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "7d6e15da975bf3a6ecd777165aebd43404e5de106351c8cc0fe75dbc3752943a",
                "Source": "/var/lib/docker/openmediavault/volumes/7d6e15da975bf3a6ecd777165aebd43404e5de106351c8cc0fe75dbc3752943a/_data",
                "Destination": "/config",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "jackett",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "9117/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HOME=/root",
                "LANGUAGE=en_US.UTF-8",
                "LANG=en_US.UTF-8",
                "TERM=xterm",
                "XDG_DATA_HOME=/config",
                "XDG_CONFIG_HOME=/config"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "linuxserver/jackett:latest",
            "Volumes": {
                "/config": {},
                "/downloads": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {
                "build_version": "Linuxserver.io version:- 85 Build-date:- October-13-2017-22:16:34-UTC"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "9303c1b2fe3b0533efe0201147f5ce465213dd8f45c316c8d23992373a74b876",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "9117/tcp": [
                    {
                        "HostIp": "10.0.100.11",
                        "HostPort": "9117"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/9303c1b2fe3b",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "22e11406afb9827514d5ea22ee4bd0a5bf6354390ec491ae3f7e4cd17fd8f41c",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.4",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:04",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "188fd97d27ca34684f831d75050cbd43c2f1296d46ae77e52764b0a0f04070bd",
                    "EndpointID": "22e11406afb9827514d5ea22ee4bd0a5bf6354390ec491ae3f7e4cd17fd8f41c",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:04",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by kaso17** [comment]
Please try starting jackett with the command line argument `-c libcurl`

**Comment by skluthe** [comment]
How would I do that in docker? I'm using the docker plugin on openmediavault.

**Comment by skluthe** [comment]
Wound up spinning up an ubuntu lxc container on my hypervisor instead of using docker on my omv vm. Working fine there. Not sure what the problem is but if anyone can tell me how to use that command argument in the omv docker plugin let me know.
