### ISSUE TITLE
[zooqle] CAPTCHA Challenge via VPN

### ISSUE THREAD

**Issue by kingy444** [Jackett/Jackett#1988]
Unable to find search results for Zooqle when running via VPN (Private Internet Access)

CAPTCHA challenge for Zooqle has been completed in all browsers. Zooqle works fine whether connected to the VPN or not through a browser, it is only Jackett failing to connect. Other indexers work fine via VPN.

When VPN is connected all traffic is directed down that tunnel. If i turn off VPN Zooqle connection works fine via the normal LAN tunnel. Anyway to have the Captcha challenge accepted within Zooqle when connected to the VPN? 

I should also note all this is being completed on the one box - so i am not able to resolve re-captacha locally as described under https://github.com/Jackett/Jackett/issues/1770

[log.20171021.00000.txt](https://github.com/Jackett/Jackett/files/1403826/log.20171021.00000.txt)
[log.20171021.00001.txt](https://github.com/Jackett/Jackett/files/1403827/log.20171021.00001.txt)
[log.txt](https://github.com/Jackett/Jackett/files/1403828/log.txt)

Jackett version:  Windows v0.8.285

-------------------------------

**Comment by kingy444** [comment]
after looking at closed issues it appears this is similiar to https://github.com/Jackett/Jackett/issues/1602

**Comment by kaso17** [comment]
yes, it's the same as #1602
Not sure why the CF challenge solving is no longer working but even if it would work you have to resolve it ever couple of hours making it useless in combination via Jackett.
I suggest you get another VPN which isn't blacklisted by cloudflare.

**Comment by kingy444** [comment]
I think you missed the part where it works with the VPN connected if using Chrome, EDGE or IE. It's just not working in Jackett @kaso17 can you please re-evaluate as I can verify the captcha through the browser, its just Jackett not accepting it. Perhaps a cookie or such needs to be passed?
I'm not sure this is all on cloudfare as i believe EZTV use cloudfare aswell and that indexer works fine

**Comment by kingy444** [comment]
I dont believe it is cloudfare blacklisting the VPN as i also get the same Captcha on a box that is off the VPN. Surely there will be other sites that start to use cloudfare captchas in the future? I thought Demenoid were starting to?

**Comment by kaso17** [comment]
Demonoid isn't using cloudflare.
google just fixed a loophole which we used to solve the captchas, #1026 needs to be implemented first.
