### ISSUE TITLE
[theempire] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by gazrat17** [Jackett/Jackett#1991]
Not able to connect - Fails Test

Jackett version:  Latest: v0.8.285
Mono version (if not using Windows):  5.0.1.1 

Logs:
https://pastebin.com/KDzTPUsy

-------------------------------

**Comment by garfield69** [comment]
The log shows your were redirected to a 404 not-found page, which occurs when the username/password or captcha is incorrect.
Click on the wrench on the JackettDashboard and validate your definition again.

**Comment by gazrat17** [comment]
Ah ha ! Good to know, thanks that's fixed it
