### ISSUE TITLE
[cpasbien] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by alex7614** [Jackett/Jackett#1994]
IWebClient: Returning MovedPermanently => http://cpabien.la/search.php?t= <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>301 Moved Permanently</title> </head><body> <h1>Moved Permanently</h1> <p>The document has moved <a href="http://cpabien.la/search.php?t=">here</a>.</p> </body></html>
--

Jackett version:  Last

-------------------------------

**Comment by garfield69** [comment]
access your Jackett Dashboard, click on the wrench for capsbien, and overwrite the SiteLink so it contains `http://cpabien.la/`.
