### ISSUE TITLE
[nexttorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by alex7614** [Jackett/Jackett#1996]
IWebClient: Returning MovedPermanently => http://www.nextorrent.tv/recherche/ <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>301 Moved Permanently</title> </head><body> <h1>Moved Permanently</h1> <p>The document has moved <a href="http://www.nextorrent.tv/recherche/">here</a>.</p> </body></html>
--

Jackett version:  Last

-------------------------------

**Comment by garfield69** [comment]
Yup, according to their WhoIs domain record, it looks like they moved yesterday.
You can fix this for yourself now, by opening your Jackett Dashboard, clicking on the wrench icon for nextTorrent and overwriting the SiteLink with `http://www.nextorrent.tv/`
I'll post a commit to update the definition source shortly.
