### ISSUE TITLE
not grabbing release name off UHD tracker

### ISSUE THREAD

**Issue by king8084** [Jackett/Jackett#1998]
jackett isnt working correctly with UHD, this is what it grabs

![image](https://user-images.githubusercontent.com/9740702/31864670-0917c0f0-b76a-11e7-9402-9acdb86b9d48.png)

the release name isnt grabbed, but instead the title is grabbed which is missing information (such as bluray in this case), also for some reason it always show the release date 0.1 minute ago

**Comment by drewbitt** [comment]
UHD search page only has the titles, not release names.

**Comment by kaso17** [comment]
thank you for fixing the date, the title can't be changed (no release name available)
