### ISSUE TITLE
Jackett need to live!

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#2]
Hi,

Can we consider this fork as an "official" futur for Jackett ?
Would be glad !

**Comment by flightlevel** [comment]
+1
@Kayomani would you be able to add to the readme on https://github.com/zone117x/Jackett 
Development continuing over at https://github.com/Jackett/Jackett

**Comment by raspdealer** [comment]
Would be great, in H2 - Red.

**Comment by raspdealer** [comment]
@flightlevel Can I share my email with you? It would be great if we can privatly share an email for all new request invites (to be able to let all admins to use it.)

**Comment by Kayomani** [comment]
@flightlevel Once there is a release.

**Comment by camjac251** [comment]
What is your email @raspdealer, I'd like to discuss about a website for Jackett

**Comment by raspdealer** [comment]
nickname at gmail

**Comment by raspdealer** [comment]
Hi @WhatFox , 
@flightlevel @camjac251  and I are already in contact to make this project live.
Can you contact me by email please?
Nickname @ gmail

**Comment by philborman** [comment]
Hi, don't want to hijack your thread, but I'm working on LazyLibrarian https://github.com/DobyTang/LazyLibrarian.git
and would like to add support for using Jackett/torznab  as a search option. Is there any documentation on your api? The jackett server has a page that searches all the configured providers in one call, which would be cool to integrate.

**Comment by raspdealer** [comment]
Can you create a new issue like the one below?
https://github.com/Jackett/Jackett/issues/20

**Comment by raspdealer** [comment]
@philborman  please continue here https://github.com/Jackett/Jackett/issues/21

**Comment by raspdealer** [comment]
Release are here now :D
