### ISSUE TITLE
Refactor T411

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#200]
* Following this topic https://github.com/Jackett/Jackett/issues/157 and to keep an open issue, if we want t411 back, we will need to refactor it because results are not very relevant...
* And of course an option to turn public tracker on or off.
* The point below involved a private/public value on the tracker instance.

**Comment by djdmd** [comment]
@ raspdealer . Hello
Is it possible having a package build for debian of your fork because i dont have all things needed to build on windows 
thanks a lot

**Comment by raspdealer** [comment]
Done. Please open this fork related issues...on the fork ;)

**Comment by djdmd** [comment]
Ok
Rhanks but I don't have the link for issues in the fork

**Comment by solspire** [comment]
Hello, I would like t411 provider for use with mylar (PVR for comics, the only existng).
Mr Evilhero say me to try with jackett.!
I see t411 in your screenshot but not in your software :(

I am in synology, I instal synocomunity package of jackett (beta) +Mono (beta)
I am on Version 0.7.33.0

If it is possible, it's great because mylar can't find french result on KAT.

Thanks a lot for your work and help

**Comment by Bybou** [comment]
I think you are looking for this fork https://github.com/raspdealer/Jackett

2016-03-08 16:45 GMT+01:00 solspire <notifications@github.com>:

> Hello, I would like t411 provider for use with mylar (PVR for comics, the
> only existng).
> Mr Evilhero say me to try with jackett.!
> I see t411 in your screenshot but not in your software :(
>
> I am in synology, I instal synocomunity package of jackett (beta) +Mono
> (beta)
> I am on Version 0.7.33.0
>
> If it is possible, it's great because mylar can't find french result on
> KAT.
>
> Thanks a lot for your work and help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jackett/Jackett/issues/200#issuecomment-193829849>.
>



-- 

Cordialement,


*Johan Copin*

johan.copin@gmail.com <jcopin@micropole.com>

**Comment by solspire** [comment]
Thinks, 
But I have never instal manualy a fork on my nas synology.
So I use a official package of synocommunity,
and inside I don't have t411.

PS : have you a link guide for explain me how instal a github fork ? Is it in ssh ? Thinks
