### ISSUE TITLE
[transmithenet] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by shebanghds** [Jackett/Jackett#2003]
Jackett version: 0.8.285.0
Mono version (if not using Windows):  5.4.0.201
-------------------------------
Fails to test or search for any content.
Here's a full log stripped of details: https://transfer.sh/EFQM3/neb-issue.txt

**Comment by kaso17** [comment]
it looks like they've a problem with their website/database.
Try searching on their website. I can't find any torrents.

**Comment by shebanghds** [comment]
Yep, they just confirmed it with a blog post ~20 minutes ago.
