### ISSUE TITLE
potato feed - couch potato

### ISSUE THREAD

**Issue by Nakash23** [Jackett/Jackett#2006]
Jackett version: 0.8.285.0
Mono version (from synocommunity): 4.6.2.7-8

Hello,

using couch potato since many years. i tried jacket and torrent potato is not working. I thing i configured it properly exactly like jackets asked.

any help please?

Thanks a lot.

-------------------------------

**Comment by drewbitt** [comment]
What does couchpotato's log say about the feed?

**Comment by Nakash23** [comment]
### Steps to reproduce:
1. ..
2. ..

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 89fd4e11 (2016-01-24 10:42:44)
Running on: ...

### Logs:
```
10-23 22:53:27 ERROR [hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://192.168.0.14:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt0116213&user=&passkey=76ki1a75vdekfoqdn9fxxsoz1fbembzt Traceback (most recent call last):
HTTPError: 400 Client Error: Bad Request for url: http://192.168.0.14:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt0116213&user=&passkey=76ki1a75vdekfoqdn9fxxsoz1fbembzt

**Comment by drewbitt** [comment]
If you go to the link yourself does it work?
Tried same query you did with 1337x and it gives me a "1337x does not support the requested query." but no HTTP 400 error.

**Comment by kaso17** [comment]
CP only sends the imdbid, due to that it doesn't work (1337x doesn't support searching by imdbid.
I don't know if it depends on the version or if there's a switch for it somewhere but CP somehow can send both arguments (imdb id and movie name).

**Comment by Nakash23** [comment]
on the link directly, yes it's working.

So, no really solutions. I tired with other tracker than x1337, same issue.

sad

**Comment by flightlevel** [comment]
@Nakash23 
Your CouchPotato version is two years old
Movie name wasn't included until a bit over a year ago https://github.com/CouchPotato/CouchPotatoServer/commits/b538f9a08db9a0be1af2f298727834edeafa322e/couchpotato/core/media/movie/providers/torrent/torrentpotato.py

Update your Couchpotato version and I'd suggest Jackett as well
Have a look at Radarr as well, I find it better than CP

**Comment by alxlaxv** [comment]
Any feedback from @Nakash23?
I guess it can be closed.

**Comment by kaso17** [comment]
closing, no reply
