### ISSUE TITLE
Please fix indexer 'Fuzer'

### ISSUE THREAD

**Issue by BuSHari** [Jackett/Jackett#2007]
Hello, it seems that Fuzer change their search URL, 
When i try to find the movie 'Annabelle Creation 2017' i get no results, but when i search for 'Annabelle 2 Creation 2017' i get results.

I checked it in the site and it works in both keywords, i looked in your code to find the problem, and i saw that jacket use a different URL from the browse site.

jacket use (no results):
https://fuzer.me/index.php?name=torrents&text=annabelle+creation+2017&category=0&search=1

fuzer new URL (results):
https://fuzer.me/browse.php?ref_=basic&query=annabelle+creation+2017&matchquery=any

Can you please fix it?
This is a private tracker so i can send an invite per request.

**Comment by kaso17** [comment]
fixed via b4e81301a3f514cc6d1cc0d22486ff0efe4dd8ad, can you please try v0.8.308 (pre release)

**Comment by BuSHari** [comment]
Great! thank you that was fast!
Do you know how can i check it in the docker container?

**Comment by kaso17** [comment]
Don't know how to check it within the docker container

**Comment by BuSHari** [comment]
Nevemind, i've suceeded to update to pre-release.
Right now it's working great...
