### ISSUE TITLE
[1337x] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by user897943** [Jackett/Jackett#2008]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by gustavogarciagithub** [comment]
Hello,

The log is attached and was obtained after enabling Enhanced logging and testing the indexer again. I changed the server address before the port definition.
I am trying to implement Sonarr on a Qnap TS-219p+ and Jackett came up as a possible solution to problems adding indexers. The issue reported happen in Jackett, though.

Versions:
Mono (Qmono): 5.4.1.6.0
Jacket: 0.8.402.0

Thanks.

[JackettLog.xlsx](https://github.com/Jackett/Jackett/files/1539718/JackettLog.xlsx)

**Comment by kaso17** [comment]
please also update to the latest jackett version

**Comment by garfield69** [comment]
no reply. presumed fixed. closing.
