### ISSUE TITLE
Links to 127.0.0.1 on seedbox

### ISSUE THREAD

**Issue by Xen0sis** [Jackett/Jackett#2009]
Hello

Trying to setup Jackett on my remote Swizzin Seedbox.

The seedbox is attached to a .tk domain with letsencrypt certificate.

I have no problem open Jackett and search on the added indexers, but when I press the torrent download button I'm redirected to:
`https://127.0.0.1/jackett/dl/k726p.....`

So I'm unable to download, unless I change 127.0.0.1 back to my .tk domain then it will download the torrent..

I've tried checking "External access:" also comfirming that is was changed in config file.. But same result

Anyway to change this, so it don't use 127.0.0.1 but keep using my domain?

Thank you..

**Comment by kaso17** [comment]
Your reverse proxy configuration needs to be adjusted, see #1464
