### ISSUE TITLE
[alpharatio] Exception (alpharatio): Parse error: Parse error (Test)

### ISSUE THREAD

**Issue by M1ntBerryCrunch** [Jackett/Jackett#2011]
Jackett version:  Jackett Version 0.8.300.0

**Comment by kaso17** [comment]
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by M1ntBerryCrunch** [comment]
I'm sorry. I had skimmed through the log already several times and even waited for an update, I just missed the issue. My Jackett server was connecting from an IP that is banned, it was right there all along. Thanks for the work, and for responding.
