### ISSUE TITLE
LostFilm.tv indexer not working in SickRage

### ISSUE THREAD

**Issue by UniverseXXX** [Jackett/Jackett#2012]
The tracker doesn't work with SickRage. Do you know if there is something needs to be specifically configured for the Series (i.e. name should be in Russian language etc.).
Thanks.

Jackett version:  0.8.285.0 installed in Linuxserver docker (https://hub.docker.com/r/linuxserver/jackett/)

**SickRage Logs:**
> 2017-10-24 16:17:07 INFO SEARCHQUEUE-MANUAL-289096 :: Unable to find a download for: [The Shannara Chronicles - S02E02 - Wraith]
2017-10-24 16:17:07 DEBUG SEARCHQUEUE-MANUAL-289096 :: formatting pattern: %SN - S%0SE%0E - %EN -> The Shannara Chronicles - S02E02 - Wraith
2017-10-24 16:17:07 DEBUG SEARCHQUEUE-MANUAL-289096 :: formatting pattern: %SN - S%0SE%0E - %EN -> The Shannara Chronicles - S02E02 - Wraith
2017-10-24 16:17:07 INFO SEARCHQUEUE-MANUAL-289096 :: [LostFilm-JK] :: Performing season pack search for The Shannara Chronicles
2017-10-24 16:17:07 DEBUG SEARCHQUEUE-MANUAL-289096 :: [LostFilm-JK] :: Fallback season pack search initiate
2017-10-24 16:17:07 DEBUG SEARCHQUEUE-MANUAL-289096 :: [LostFilm-JK] :: GET URL: http://192.168.0.10:9117/api/v2.0/indexers/lostfilm/results/torznab/api?apikey=**********&season=2&maxage=500&cat=5000%2C5010%2C5020%2C5030%2C5040%2C5050%2C5060%2C5070%2C5080%2C5030%2C5040&q=The+Shannara+Chronicles+S02E02&limit=100&t=tvsearch&offset=0&ep=2 [Status: 200]
2017-10-24 16:17:05 DEBUG SEARCHQUEUE-MANUAL-289096 :: [LostFilm-JK] :: Search string: The Shannara Chronicles S02E02
2017-10-24 16:17:05 DEBUG SEARCHQUEUE-MANUAL-289096 :: [LostFilm-JK] :: Search Mode: Episode
2017-10-24 16:17:05 INFO SEARCHQUEUE-MANUAL-289096 :: [LostFilm-JK] :: Performing episode search for The Shannara Chronicles
2017-10-24 16:17:05 DEBUG SEARCHQUEUE-MANUAL-289096 :: [LostFilm-JK] :: GET URL: http://192.168.0.10:9117/api/v2.0/indexers/lostfilm/results/torznab/api?apikey=**********&maxage=500&cat=5000%2C5010%2C5020%2C5030%2C5040%2C5050%2C5060%2C5070%2C5080%2C5030%2C5040&limit=100&t=tvsearch&offset=0 [Status: 200]
2017-10-24 16:16:52 DEBUG SEARCHQUEUE-MANUAL-289096 :: [LostFilm-JK] :: Search Mode: RSS
2017-10-24 16:16:52 INFO SEARCHQUEUE-MANUAL-289096 :: Beginning manual search for: [The Shannara Chronicles - S02E02 - Wraith]
2017-10-24 16:16:52 DEBUG SEARCHQUEUE-MANUAL-289096 :: formatting pattern: %SN - S%0SE%0E - %EN -> The Shannara Chronicles - S02E02 - Wraith

**Jackett Logs:**
> 10-24 16:17:04 Info FetchEpisodeReleases: https://www.lostfilm.tv/series/The_Shannara_Chronicles/season_2/episode_2/
10-24 16:17:04 Info FetchTrackerReleases: https://www.lostfilm.tv/v_search.php?c=268&s=2&e=2
10-24 16:17:05 Info FollowTrackerRedirection: http://retre.org/v3/index.php?c=268&s=2&e=2&u=5173480&h=d395b0e7db73c19e6641fc8d5ee98cc1&n=1
10-24 16:17:05 Info > Parsing 3 releases
10-24 16:17:05 Info > Add: The Shannara Chronicles - S2E2 - Wraith - WEB-DLRip
10-24 16:17:05 Info > Add: The Shannara Chronicles - S2E2 - Wraith - 1080p WEB-DLRip
10-24 16:17:05 Info > Add: The Shannara Chronicles - S2E2 - Wraith - 720p WEB-DLRip
10-24 16:17:05 Info Found 44 (2 new) releases from LostFilm.tv
10-24 16:17:07 Info PerformQuery: The Shannara Chronicles S02E02 S02E02
10-24 16:17:07 Info PerformSearch: The Shannara Chronicles S02E02 [tvsearch]
10-24 16:17:07 Info > Searching: The Shannara Chronicles S02E02
10-24 16:17:07 Info Found 0 releases from LostFilm.tv for: The Shannara Chronicles S02E02 S02E02

-------------------------------

**Comment by krin-san** [comment]
From the logs I see that SickRage made 2 requests:
- empty RSS request to grab the latest releases
- manual **tvsearch** request with **The Shannara Chronicles S02E02** search string, season=2 and episode=2

I'm not sure why SickRage rejected the RSS fetch results - it actually found three releases for this series. Could be that SickRage's post-processing failed:
- ... to map S2E2 as S02E02
- ... to recognize release language: ru/rus in the name
- ... to recognize release quality: usually "WEBDL" is written with a vertical size, but Lostfilm releases always contains "WEB-DLRip" string and don't have 480p for SD releases.

What goes wrong with the second request: season and episode were defined both in search string and in *tvsearch* query parameters. It's not the case I expected testing it on Sonarr and Jackett's manual search.

So the next key fixes should be applied to Lostfilm indexer:
- [ ] Rewrite release naming to fit language/quality recognizer needs (release names on retre.org is a trash)
New format: **Could someone suggest a better format?**
- [ ] Don't expect **tvsearch** search string will contain only serie name
- [ ] Write S01E01 instead of S1E1 just for consistency

**Comment by UniverseXXX** [comment]
Thank you, @krin-san. Let me know if you want me to run more tests.

**Comment by kaso17** [comment]
For the "search string contains the season/episode" this sickrage issue is relevant: https://github.com/SickRage/SickRage/issues/3526
First you certainly have to come up with some release rewriting rules to fix the bad naming conventions of lostfilm.

**Comment by krin-san** [comment]
@UniverseXXX, to better understand how SickRage works could you add extra logs for "Prison Break Ressurection" extra episode search? http://www.lostfilm.tv/series/Prison_Break/additional/episode_1/

My implementation relies on Sonarr behavior. It makes a **search** query with empty episode/season fields and "Prison Break Ressurection" search string. _Hoping SickRage will not make a tvsearch query for it_

**Comment by UniverseXXX** [comment]
@krin-san here is the log:
**SickRage:**
> 2017-10-27 10:43:44 INFO SEARCHQUEUE-BACKLOG-75340 :: No needed episodes found during backlog search for: [Prison Break]
2017-10-27 10:43:44 INFO SEARCHQUEUE-BACKLOG-75340 :: [LostFilm-JK] :: Performing season pack search for Prison Break
2017-10-27 10:43:44 DEBUG SEARCHQUEUE-BACKLOG-75340 :: [LostFilm-JK] :: Fallback season pack search initiate
2017-10-27 10:43:44 DEBUG SEARCHQUEUE-BACKLOG-75340 :: [LostFilm-JK] :: GET URL: http://192.168.0.10:9117/api/v2.0/indexers/lostfilm/results/torznab/api?apikey=**********&season=0&maxage=500&cat=5000%2C5010%2C5020%2C5030%2C5040%2C5050%2C5060%2C5070%2C5080%2C5030%2C5040&q=Prison+Break+S00E11&limit=100&t=tvsearch&offset=0&ep=11 [Status: 200]
2017-10-27 10:43:41 DEBUG SEARCHQUEUE-BACKLOG-75340 :: [LostFilm-JK] :: Search string: Prison Break S00E11
2017-10-27 10:43:41 DEBUG SEARCHQUEUE-BACKLOG-75340 :: [LostFilm-JK] :: Search Mode: Episode
2017-10-27 10:43:41 INFO SEARCHQUEUE-BACKLOG-75340 :: [LostFilm-JK] :: Performing episode search for Prison Break

**Jackett:**

> 10-27 10:43:13 Info PerformQuery: Prison Break S00E11
10-27 10:43:13 Info PerformSearch: Prison Break S00E11 [tvsearch]
10-27 10:43:13 Info > Searching: Prison Break S00E11
10-27 10:43:14 Info Found 0 releases from LostFilm.tv for: Prison Break S00E11
10-27 10:43:43 Info PerformQuery: Prison Break S00E11
10-27 10:43:43 Info PerformSearch: Prison Break S00E11 [tvsearch]
10-27 10:43:43 Info > Searching: Prison Break S00E11
10-27 10:43:44 Info Found 0 releases from LostFilm.tv for: Prison Break S00E11

**Comment by krin-san** [comment]
Lol! SickRage matched it to S00E11 which is not listed nor on [TVDB](https://www.thetvdb.com/?tab=seasonall&id=75340&lid=7) either on [TMDB](https://www.themoviedb.org/tv/2288-prison-break/season/0). The only place I found S00E11 is this unknown website: http://www.actucine.com/sous-titres/prison-break-s00e11-317625.html

Sorry, but I think it's impossible to automatically fetch such extras using SickRage. Not with the current implementation and not from the LostFilm.

**Comment by UniverseXXX** [comment]
@krin-san 
> Sorry, but I think it's impossible to automatically fetch such extras using SickRage. Not with the current implementation and not from the LostFilm.

Don't think it's a big issue. I never downloaded any extras, so neither my friends.
Thanks anyway.

**Comment by krin-san** [comment]
Found new issues with series with special characters in the title like "Stargate: Atlantis". LostFilm search API filters out special characters but then can't match the right series without them. Spikes on the spikes on the spikes...

**Comment by krin-san** [comment]
@kaso17, what the right Indexer behavior for Season Pack searches if there are no pack found: return empty response or try to fetch separate episode? I started thinking that the fallback to searching separate episodes if no season pack was found is already implemented in SickRage and Sonarr so I'm reinventing the wheel =]

*E.g.: /api?t=tvsearch&q=Shannara%20Chronicles&season=1*

**Comment by krin-san** [comment]
@UniverseXXX, you could try out updated indexer on the latest pre-release [v0.8.354](https://github.com/Jackett/Jackett/releases/tag/v0.8.354).

**Comment by UniverseXXX** [comment]
@krin-san 
Seems it's still not working.

**SickRage logs:**
> 2017-11-02 09:41:41 INFO SEARCHQUEUE-MANUAL-314189 :: Unable to find a download for: [Blood Drive - S01E13 - Finish Line] 2017-11-02 09:41:41 DEBUG SEARCHQUEUE-MANUAL-314189 :: formatting pattern: %SN - S%0SE%0E - %EN -> Blood Drive - S01E13 - Finish Line 2017-11-02 09:41:41 DEBUG SEARCHQUEUE-MANUAL-314189 :: formatting pattern: %SN - S%0SE%0E - %EN -> Blood Drive - S01E13 - Finish Line 2017-11-02 09:41:39 INFO SEARCHQUEUE-MANUAL-314189 :: [LostFilm] :: Performing season pack search for Blood Drive 2017-11-02 09:41:39 DEBUG SEARCHQUEUE-MANUAL-314189 :: [LostFilm] :: Fallback season pack search initiate 2017-11-02 09:41:39 DEBUG SEARCHQUEUE-MANUAL-314189 :: [LostFilm] :: GET URL: http://127.0.0.1:9117/api/v2.0/indexers/lostfilm/results/torznab/api?apikey=**********&season=1&maxage=500&cat=5030%2C5040&q=Blood+Drive+S01E13&limit=100&t=tvsearch&offset=0&ep=13 [Status: 200] 2017-11-02 09:41:28 DEBUG SEARCHQUEUE-MANUAL-314189 :: [LostFilm] :: Search string: Blood Drive S01E13 2017-11-02 09:41:28 DEBUG SEARCHQUEUE-MANUAL-314189 :: [LostFilm] :: Search Mode: Episode 2017-11-02 09:41:28 DEBUG SEARCHQUEUE-MANUAL-314189 :: [LostFilm] :: GET URL: http://127.0.0.1:9117/api/v2.0/indexers/lostfilm/results/torznab/api?apikey=**********&t=caps [Status: 200] 2017-11-02 09:41:26 INFO SEARCHQUEUE-MANUAL-314189 :: [LostFilm] :: Performing episode search for Blood Drive 2017-11-02 09:41:26 DEBUG SEARCHQUEUE-MANUAL-314189 :: [LostFilm] :: Last update was too soon, using old cache: 2017-11-02 09:16:44. Updated less then 30 minutes ago 2017-11-02 09:41:26 INFO SEARCHQUEUE-MANUAL-314189 :: Beginning manual search for: [Blood Drive - S01E13 - Finish Line] 2017-11-02 09:41:26 DEBUG SEARCHQUEUE-MANUAL-314189 :: formatting pattern: %SN - S%0SE%0E - %EN -> Blood Drive - S01E13 - Finish Line

**Jackett logs:**
Nov 02, 2017 09:44:46 AM	Info	
Found 3 releases from LostFilm.tv for: Blood Drive S01E13 S01E13

P.S. It seems that "Enhanced logging" option gets reset (untick itself), therefore cannot provide debug logs. Will try to pull it later from Docker container.

**Comment by krin-san** [comment]
@UniverseXXX, starting from the last issue to first.

> `{"error":1,"result":"ok"}`

I assumed it is returned when we're logging in while we already have a valid session.. and I was right. Placing another `logout` call before `login` works perfectly!

Also turned out that frequent login/logout could cause Captcha to be entered. In this case you should re-login in browser manually to enter it. Not an issue, but a point for improvement.

- [ ] (optional) Show Captcha if it was required on login

> "Enhanced logging" option gets reset 

I noticed the same thing during debugging but it drops only when I restart the server (windows console version of it). Ensure you checked this option, pressed "Apply server settings" and wait until Jackett will reload your page. Worked for me ;)

> Seems it's still not working.

There is not much to obtain from Jackett logs, but we've got some breadcrumbs:
- Search string was "Blood Drive S01E13" with Season=1 and Episode="13"
- LostFilm indexer actually returned 3 releases for this query. I forgot to check this weird SickRage search behavior for episodes, but seems like improved search logic just ignores the S01E13 which could cause filtering out good results

SickRage logs _(again)_ doesn't saying WHY all this releases were rejected. I even used the URL provided in logs and got those 3 releases.

When I wrote release type replacement _(web-dlrip, web-dl, etc.)_ I referenced both SickRage docs and Sonarr QualityParser implementation and wrote in a way both should successfully parse it. _Debug logs from Sonarr for the same search: https://pastebin.com/raw/xSk5dq48_

@UniverseXXX, could you invest more time on SickRage debugging to know in detail why it rejects releases this time?

**Comment by UniverseXXX** [comment]
@krin-san Many thanks for the reply.

1. First two "issues" are resolved itself. Thanks for the assistance.
Does it mean that Sonarr is working fine with LostFilm? I'm now inclined to switch to Sonarr.

P.S. Unfortunately, at the moment I'm not in the position to spend some time investigating SickRage issue. However, if I'll have spare time I'd further digging into it.

**Comment by kaso17** [comment]
From my understanding of the torznab specification a search for just the season (no episode specified) should return individual episodes from that season too.

**Comment by krin-san** [comment]
@UniverseXXX, good to know the are self-resolved, but I will publish re-login fix anyway.
Wel, yeah. Lostfilm indexer now works even better with Sonarr. It even started downloading new releases from rss search and with some quality profile tuing I managed to download season packs for old series like Supernatural.

@kaso17, unfortunately I disabled this indexer's feature. @flightlevel on PR review mentioned Sonarr will do that automatically so I see not reason to reimplement the same.

**Comment by flightlevel** [comment]
969c365a64d91c526ad08aed45deda8811f4d87c Now in pre-release, thanks @krin-san

**Comment by doul59** [comment]
Hi,

I have the same issue with other indexer

Nov 16, 2017 09:13:46 PM | Info | Found 0 releases from cpasbien for: XXX S02E08 S02E08
Nov 16, 2017 09:13:44 PM | Info | Found 0 releases from YGGtorrent for: XXX S02E08 S02E08

i'm on Jackett Version 0.8.434.0

**Comment by krin-san** [comment]
@doul59, sure, this fix is only for LostFilm.tv indexer. Take a look on SickRage/SickRage#3526 - that thing could affect a lot of indexers.
