### ISSUE TITLE
[manicomioshare] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by FabioCastilho** [Jackett/Jackett#2015]
Hello, it works normally when it is configured, but if I log in to the site, it will deactivate Jackett, causing this error.

Sonarr and Jackett latest version.
---------------
Olá, funciona normalmente quando se configura porém se eu logar no site ele deslolga no Jackett ocasionando este erro..

Sonarr e Jackett última versão.

**Comment by kaso17** [comment]
There are several trackers which support only a single login session. Maybe manicomioshare is one of them. What happens if you login to it in another browser, I would expect that it will logout your other browser's session.

**Comment by FabioCastilho** [comment]
I understand can it really does this and has tried to see in the tracker itself if it has as they put at least 2 logins or disable it for good. Taking advantage of the topic bj-share.me does not have RSS so does not the searches have how to put make it?
____
Entendo pode ele realmente faz isso viu tentar ver no próprio tracker se tem como eles colocarem no mínimo 2 logins ou desativar isso de vez. Aproveitando o tópico o bj-share.me não possui RSS por isso não faz as buscas tem como colocar tornar isso?

**Comment by kaso17** [comment]
sorry, I don't understand your question

**Comment by FabioCastilho** [comment]
Bj-share.me does not perform the search when a new episode comes out, I think that for lack of RSS it is limited to manually searching is there anything that can be done in relation to this?
..... 
O bj-share.me não realiza a busca quando sai um novo episódio, eu acho que por faltar RSS ele se limita a procura manualmente há algo que possa ser feito em relação a isso?

**Comment by kaso17** [comment]
bj-share empty search/rss of the latest torrents is working fine for me. Please open a new issue with corresponding logs.

I assume this manicomioshare issue is fixed.

**Comment by Guizzoni** [comment]
Yes @kaso17
Manicomio Share only supports one login session at a time. Is there a workaround to fix this?
The "login detection" doesn't seem to work properly.

**Comment by Guizzoni** [comment]
(Hopefully) fixed in #2045

**Comment by FabioCastilho** [comment]
@Guizzoni Were you able to solve the problem?

**Comment by Guizzoni** [comment]
Yes, i opened a new PR just now to try and fix the Manicomio Share issue

**Comment by FabioCastilho** [comment]
@Guizzoni 

Coming home, I'm going to test thank you.

Chegando em casa vou testar obrigado.

**Comment by Guizzoni** [comment]
@FabioCastilho you'll have to wait until the new Jackett release or pre-release

**Comment by FabioCastilho** [comment]
@Guizzoni 

Any date or undefined?
Alguma data ou indefinido?

**Comment by Guizzoni** [comment]
They update Jackett on a pretty regular basis. 
We should have a release with the definition updates pretty soon.
