### ISSUE TITLE
[blutopia] Exception (blutopia): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. (Test)

### ISSUE THREAD

**Issue by Wyall** [Jackett/Jackett#2016]
I add Blutopia and it works, but after some time it stops working. I first noticed this because Radarr/Sonarr say Indexers unavailable due to failures: Blutopia
If I click "test" in Jackett it then also fails, giving the error in the title.
I'm able to fix this by entering my Blutopia password again, but after some time it fails again

Jackett version:  0.8.300.0
Mono version (if not using Windows):  5.2

Edit: Found this in the logs: https://pastebin.com/uQvkAu4t

**Comment by kaso17** [comment]
It is already fixed (since v0.8.308)

**Comment by Wyall** [comment]
I didn't see that in die Patchnotes, thanks!
