### ISSUE TITLE
[torrentz2] Exception (torrentz2): An error occurred while sending the request: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by Noedel-Man** [Jackett/Jackett#2020]
`**Please` use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.8.321
Mono version (if not using Windows):  4.8.0
log: https://pastebin.com/x7ZiawKc
-------------------------------
fedora 26 headless server.

tried running with `mono --debug JackettConsole.exe --IgnoreSslErrors true`

**Comment by garfield69** [comment]
Torrentz2's CA certificate is valid and I can access the site.
  Try reimporting the certificates in this case:
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`

**Comment by Noedel-Man** [comment]
thank you for your response, I did the `wget` command as `sudo` and restarted jackett and re-added torrentz2 but I still have the same error.
