### ISSUE TITLE
[yts] Access to the path 'C:\ProgramData\Jackett\Indexers\yts.json.bak' is denied. (Test)

### ISSUE THREAD

**Issue by MrPryor** [Jackett/Jackett#2022]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
Try running the Jackett installer as an administrator.
Or if this is from running the JackettConsole from a command prompt, then  first start the command prompt as an administrator.
Let me know how you go.

**Comment by flightlevel** [comment]
@MrPryor 
Re-open if still an issue, looks like a permission as garfiled69 noted, restarting PC might even help for weird path issues sometimes

**Comment by epheterson** [comment]
I hit this on my Synology NAS after doing an update and a reboot fixed it.
