### ISSUE TITLE
Move Package References in to Project Files

### ISSUE THREAD

**Issue by NathanNZ** [Jackett/Jackett#2024]
I'm proposing we move to storing package references in our project files in order to make the move to .NET Core easier.  Targeting .NET Standard projects without package reference is a mess of binding redirects and causes many more packages to be linked than are actually required.

It also helps maintain the solution as packages bubble up, if you remove a package from a project that another project depends on the package is automatically removed from the parent project. (assuming that project doesn't have the package installed, or is referencing another project where it is)

Requirements:
-  Visual Studio 2017
-  .NET Framework 4.5.2 (For automatic binding redirects)

Additional Documentation:
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
https://www.hanselman.com/blog/ReferencingNETStandardAssembliesFromBothNETCoreAndNETFramework.aspx

**Comment by garfield69** [comment]
is this complete now that #2025 has been merged, can I close the ticket, or is there more?

**Comment by NathanNZ** [comment]
Yep! All done.
