### ISSUE TITLE
[hounddawgs] Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by chpetersen** [Jackett/Jackett#2027]
Stopped working like 2 month ago tried readding the tracker and got this issue
Jackett Version 0.8.321.0
[log.txt](https://github.com/Jackett/Jackett/files/1424375/log.txt)

**Comment by kaso17** [comment]
please update to a more recent jackett version, probably already fixed

**Comment by kaso17** [comment]
if it's still a problem please post a full enhanced log (including the html code before the error)

**Comment by LeetDonkey** [comment]
Jackett Version 0.8.423.0
Still encountering the error:
[log.txt](https://github.com/Jackett/Jackett/files/1478138/log.txt)

**Comment by kaso17** [comment]
for some reason you don't see the "Snatches" column, don't know why (couldn't find a profile setting).
fixed via c1e495b21283a1f5cbaea6112f92786c60a31635
