### ISSUE TITLE
[t411v2] Exception (t411v2): Une tâche a été annulée.: Une tâche a été annulée. (Test)

### ISSUE THREAD

**Issue by thertemis** [Jackett/Jackett#2028]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
[t411.log](https://github.com/Jackett/Jackett/files/1424694/t411.log)

**Comment by garfield69** [comment]
The site has changed their results row header. 
I'll commit a fix shortly which will be included in the next build that is released.
