### ISSUE TITLE
Templateshares Ultimate Edition

### ISSUE THREAD

**Issue by valantislevas** [Jackett/Jackett#203]
Its possible to add custom tracker that uses: Templateshares Ultimate Edition 2.2 ?

**Comment by JigSawFr** [comment]
@valantislevas French ADN provider is on TSUE ;)

**Comment by valantislevas** [comment]
thanks going to check then !

**Comment by valantislevas** [comment]
so i will do my changes localy to test if its works... or is possible to tell the trackers links are 2 and the best on Greece

**Comment by JigSawFr** [comment]
Due to your request, i close your issue.
