### ISSUE TITLE
[REQ] Bit Torrent Scene

### ISSUE THREAD

**Issue by zero77** [Jackett/Jackett#2038]
Tracker Name : Bit Torrent Scene
Type : MOVIES, SERIES, MUSIC, GAMES, SOFTWARE, EBOOKS, ANIME, MISC
Public tracker  although it has a login option
Supports torrent and magnet
Indexer URL : https://torrent-corp.com
Indexer language : English

**Comment by garfield69** [comment]
https://torrent-corp.com redirects to https://bttorrentz.com which is a clone of the official public https://bt-scene.cc/ site.
So I will try to build a definition for the latter.

**Comment by zero77** [comment]
Thank you, I didn’t know it was a mirror I just found it listed either on unblocked.st or torrents.me.
