### ISSUE TITLE
[REQ] Greekleech.info/Magico

### ISSUE THREAD

**Issue by valantislevas** [Jackett/Jackett#204]
link Greekleech.info

AddCategoryMapping("45", TorznabCatType.Movies);
AddCategoryMapping("31", TorznabCatType.MoviesForeign);
AddCategoryMapping("108", TorznabCatType.MoviesOther);
AddCategoryMapping("17", TorznabCatType.MoviesSD);
AddCategoryMapping("55", TorznabCatType.MoviesHD);
AddCategoryMapping("56", TorznabCatType.Movies3D);
AddCategoryMapping("56", TorznabCatType.MoviesBluRay);
AddCategoryMapping("17", TorznabCatType.MoviesDVD);
AddCategoryMapping("106", TorznabCatType.MoviesWEBDL);
AddCategoryMapping("78", TorznabCatType.TV);
AddCategoryMapping("72", TorznabCatType.TVWEBDL);
AddCategoryMapping("74", TorznabCatType.TVFOREIGN);
AddCategoryMapping("78", TorznabCatType.TVSD);
AddCategoryMapping("74", TorznabCatType.TVHD);
AddCategoryMapping("72", TorznabCatType.TVOTHER);
AddCategoryMapping("75", TorznabCatType.TVSport);

also if needed i can write the multi categories

EDIT:

AddMultiCategoryMapping(TorznabCatType.MoviesDVD,14, 17, 31, 55, 56, 106, 45, 101);
AddMultiCategoryMapping(TorznabCatType.TVSD, 78, 76);

---

also i have another tracker i will create new req. thanks

**Comment by valantislevas** [comment]
i also have invite for greekleech.info and magico.info if needed..

**Comment by valantislevas** [comment]
@JigSawFr

or is possible to compile the changes myself localy?

**Comment by JigSawFr** [comment]
You need visual studio to edit and compile it. And push it to github.
I can do it next week if you want ;)

**Comment by valantislevas** [comment]
thanks i tried yes with only http link change but login fails maybe about broswer settings have problem.. if i found i will push it thanks i will tell you if i cant do it to help me thanks..

**Comment by JigSawFr** [comment]
TSUE has extra layers of security ;)

**Comment by valantislevas** [comment]
thanks i tried several things but nothing.. i will wait for your changes, thanks

greekleech.info if you do this i thing i will do the other magico.info

thanks

**Comment by JigSawFr** [comment]
@valantislevas TSUE need absolutely emulated browser to be activated in my providers. This sript check history of your naviguation (so, you can't login if you didn't visit login page before), they add multiple cookies over pages (that you need to save in order to work), it's very boring, but can be functionnal ;)

**Comment by valantislevas** [comment]
omg its so difficult.. i think.. i hope you can do that.. thanks for the explain how it works..

**Comment by valantislevas** [comment]
hi, @JigSawFr we have any news about?

thanks!

**Comment by JigSawFr** [comment]
Not at the moment sorry

**Comment by valantislevas** [comment]
thanks if you need any help tell me.. thanks.

**Comment by valantislevas** [comment]
hello, any news @JigSawFr

**Comment by valantislevas** [comment]
hey @JigSawFr

**Comment by JigSawFr** [comment]
working on https://github.com/Jackett/Jackett/issues/300 at this time

**Comment by kaso17** [comment]
Please send an invite to kaso1717 -at- gmail.com and I'll add it.

**Comment by kaso17** [comment]
added with 12c421b6dbc037e602f13158df2caf0228e4a4e9

**Comment by valantislevas** [comment]
You are awesome!!
ass i see the request https://github.com/Jackett/Jackett/issues/300i have another tracker with the same provider files Powered by TS Special Edition v.7.5tracker: http://dream-team.ml/index.php i think is open with signups now.. if not tell me to check from my profile..
also if you have other tracker with Powered by TS Special Edition v.7.5 is possible to edit myself the categorys id's and links to add the tracker?thanks for your job!



    Στις 10:44 μ.μ. Τετάρτη, 18 Ιανουαρίου 2017, ο/η kaso17 <notifications@github.com> έγραψε:
 

 added with 12c421b—

**Comment by kaso17** [comment]
Dream Team added with 9c971b0daba85863a10eeccc74ee41f71990ded0 categories are incomplete for it, feed free to add them.
BTNext has no open signups

From my experience no tracker is like another tracker, you most likely will have change more than just the category IDs.

**Comment by valantislevas** [comment]
nice as i see the categories movies and tv is ok.. other isnt nessessary but i will post the ids

also it works from jackett manual search but on couchpotato doesnt download the file it says:

`[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last): File "/opt/couchpotato/couchpotato/core/media/_base/providers/base.py", line 207, in download return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False) File "/opt/couchpotato/couchpotato/core/plugins/base.py", line 227, in urlopen response.raise_for_status() File "/opt/couchpotato/libs/requests/models.py", line 837, in raise_for_status raise HTTPError(http_error_msg, response=self) HTTPError: 404 Client Error: Not Found for url: http://MY-JACKETT:9117/dl/dreamteam/dnmq47acful07aaka51kt2awbqf4pm67?path=aHR0cDovL2RyZWFtLXRlYW0ubWwvZG93bmxvYWQucGhwP2lkPTQzODQ1&file=BLOOD+FATHER+(2016)+HDRip+XviD+AC3-iFT.torrent
`
do you know why?

**Comment by valantislevas** [comment]
i tried some manually search movies from jackett and doesnt find them i think something going wrong ? on dream-team tracker

thnx

**Comment by valantislevas** [comment]
@kaso17 can you check?

**Comment by kaso17** [comment]
the DL doesn't work due to their thank you requirement system.
I'll have to make some core changes to fix that, will do later.

Please provide examples of the search strings which aren't working

**Comment by valantislevas** [comment]
thanks for the reply as i see on dream-team tracker some movies is ok can find them in search.. but some cant find them like "Alone in Berlin" "Pet 2016" "the book of love" "the snare" i think many results from category=133 

thanks

**Comment by kaso17** [comment]
They've a minimum search term length of 4 characters, that's why these searches are not working (try it directly on their website). I'll implement a filter to remove words <= 3 characters before sending it to their server and then filter them in jackett. That should fix all the examples you provided except the "pet 2016" as it will search their server for only "2016" which will return plenty of unrelated results.

I suggest you open a bug/suggestion in their forum asking to remove this search character limitation (That's the better fix).

**Comment by valantislevas** [comment]
i see.. thanks i already do post on their forum !! if you do something for filtering tell me to check it.. thanks!

**Comment by kaso17** [comment]
fixed with 666e311476b7526f9f2694ca961c855a360d8a8e, please try v0.7.942 (pre release)

**Comment by valantislevas** [comment]
@kaso17 
2 days now jackett doesnt work.. and i see red errors on log..

on dream-team says:  Configuration failed: Login failed: Selector "a[href^="http://dream-team.ml/logout.php"]" didn't match

on magico i had to remove and add it again to make it work 
also kapaki.info wanted to remove and add it again to make it work..

dream-team cant make it work as i see now i think the tracker do updates but i dont know can you check?

**Comment by valantislevas** [comment]
`2, 2017 03:31:08 PM	Error	
Error on 20170212143108 for Kapaki.txtJackett.ExceptionWithConfigData: Login failed: No form found on https://kapaki.info/?p=home&pid=1 using form selector form#loginbox_form
  at Jackett.Indexers.CardigannIndexer+<DoLogin>c__async0.MoveNext () [0x00592] in <0a574295ba6048f5b63246983ff2b96a>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at Jackett.Indexers.CardigannIndexer+<PerformQuery>c__async5.MoveNext () [0x0064e] in <0a574295ba6048f5b63246983ff2b96a>:0 




<!DOCTYPE html>
<html id="TSUE" lang="gr-eu">
	<head>
		<noscript><meta http-equiv=refresh content="0; URL=https://kapaki.info/?noscript=1" /></noscript>
		<base href="https://kapaki.info/" />
		<title>Kapaki - The Place to Be!</title>
		<meta charset="utf-8" />
		<meta name="description" content="Kapaki - The Place to Be!" />
		<meta name="viewport" content="width=device-width" />
		<meta name="MobileOptimized" content="width" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
		<link rel="stylesheet" href="https://kapaki.info/style.php?lv=2.2&l=style,fancybox,jqueryTools,forums,fileuploader,tinymce_ui,thread_prefixes,comments,downloads,image_gallery,extra,menu,ajax,shoutbox,staffDropDownMenu,upcomingReleases,staffOnlineNow,subtitles,oneStepUpload,mixed,topDonors,fls,memberCard,plugin_torrent_categories,dj,torrentai,members,blackjack" type="text/css" media="screen" />
		<link rel="Shortcut Icon" href="https://kapaki.info/favicon.ico?lv=2.2" type="image/x-icon" />
	</head>

	<body>
		 

		
		<div id="wrap">
			

			
			<div id="header">
				<div class="content"><img src="https://kapaki.info/data/languageFlags/2.png" alt="Assassins Creed" rel="selectLanguage" class="clickable" /> </div>
			</div>
			

			
<ul id="menu">
	<li class="nodrop">
	<a href="https://kapaki.info/?p=home&amp;pid=1" class="link ">Αρχική</a>
	
</li><li class="nodrop">
	<a href="https://kapaki.info/?p=signup&amp;pid=16" class="link ">Εγγραφή</a>
	
</li><li class="nodrop">
	<a href="https://kapaki.info/?p=contact&amp;pid=14" class="link ">Επικοινωνία</a>
	
</li>
</ul>

<div class="clear"></div>
			
			<div id="inner">
 
				<div class="breadBoxTop">
	<nav>
		<fieldset class="breadcrumb">
			<span class="crumbs">
				
				<span class="crust" itemscope="itemscope" itemtype="http://data-vocabulary.org/Breadcrumb">
	<a href="https://kapaki.info/?p=home&amp;pid=1" class="crumb" rel="up" itemprop="url"><span itemprop="title">Αρχική</span></a>
	<span class="arrow"><span></span></span>
</span>
<span class="crust" itemscope="itemscope" itemtype="http://data-vocabulary.org/Breadcrumb">
	<a href="https://kapaki.info/?p=torrents&amp;pid=32" class="crumb" rel="up" itemprop="url"><span itemprop="title">Τόρρεντ</span></a>
	<span class="arrow"><span></span></span>
</span>
			</span>
		</fieldset>
	</nav>
</div>
				
				
				<div id="plugins">
					
					<div id="content" class="mainContent fullwidth">  <div class="error" id="show_error">
	<b>Ουπς! Λάθος!</b><br />Δεν έχετε δικαίωμα να δείτε αυτήν την σελίδα ή να εκτελέσετε αυτήν την ενέργεια.
</div><div class="widget">
	<h4>Σύνδεση</h4>
	<div id="loginbox">
		<form id="loginbox_form" action="">
			
			<p>
				<label for="loginbox_membername">Όνομα Χρήστη</label><br />
				<input type="text" name="loginbox_membername" id="loginbox_membername" class="s" accesskey="m" value="" />
			</p>
			
			<p>
				<label for="loginbox_password">Κωδικός</label><br />
				<input type="password" name="loginbox_password" id="loginbox_password" class="s" accesskey="p" value="" />
			</p>
			
			<p>
				<input type="checkbox" name="loginbox_remember" id="loginbox_remember" accesskey="r" value="1" /> 
				<label for="loginbox_remember">Μείνετε συνδεδεμένοι</label>
			</p>
			
			<p id="loginbox-buttons">
				<input type="submit" value="Σύνδεση" class="submit" /> 
				<input type="reset" value="Καθαρισμός" class="submit" />
			</p>
			
			<p>
				<a href="https://kapaki.info/?p=signup&pid=16" id="signup">Εγγραφή</a>
				<br />
				<a href="#" rel="forgot-password">Ξεχάσατε τον κωδικό σας;</a>
			</p>
		
		</form>
	</div>
</div></div>
					<div class="clear"></div>
				</div>
				
			
			</div>
			

			
			<div id="footer">
				<div class="wrap">
					
					<p>Powered by Templateshares Ultimate Edition 2.2 &copy; Copyright 2011-2013 <a href="http://www.templateshares-ue.net">www.templateshares-ue.net</a></p>
					
				</div>
			</div>
			
		</div>
		
		
		<script type="text/javascript">
		//<![CDATA[
			var TSUEPhrases = 
{
	months: "Ιανουάριος, Φεβρουάριος, Μάρτιος, Απρίλιος, Μάιος, Ιούνιος, Ιούλιος, Αύγουστος, Σεπτέμβριος, Οκτώβριος, Νοέμβριος, Δεκέμβριος",
	shortMonths: "Ιαν, Φεβ, Μαρ, Απρ, Μάι, Ιούν, Ιούλ, Αύγ, Σεπ, Οκτ, Νοέ, Δεκ",
	days: "Κυριακή, Δευτέρα, Τρίτη, Τετάρτη, Πέμπτη, Παρασκευή, Σάββατο",
	shortDays: "Κυρ, Δευ, Τρι, Τετ, Πεμ, Παρ, Σαβ",

	relative_a_moment_ago: "Πριν από λίγο",
	relative_one_minute_ago: "Πριν από ένα λεπτό",
	relative_x_minutes_ago: "{1} λεπτά πριν",
	relative_one_hour_ago: "Πριν μία ώρα",
	relative_x_hours_ago: "{1} ώρες πριν",
	relative_one_day_ago: "Μία ημέρα πριν",
	relative_x_days_ago: "{1} ημέρες πριν",

	button_save: "Αποθήκευση",
	button_update: "Ενημέρωση",
	button_cancel: "Ακύρωση",
	button_okay: "Ναι",
	button_preview: "Προεπισκόπηση",

	message_saved: "Οι αλλαγές σας έχουν αποθηκευθεί.",
	message_posted: "Το μήνυμα σας έχει αναρτηθεί.",
	message_deleted: "Το μήνυμα σας έχει διαγραφεί.",
	message_required_fields_error: "Παρακαλώ συμπληρώστε όλα τα απαιτούμενα πεδία.",

	website_active_admin_alert: "Ειδοποίηση! Η Ιστοσελίδα είναι προς το παρόν κλειστή!",
	ajax_error: "Σφάλμα Ajax! Παρακαλώ δοκιμάστε ξανά αργότερα.",
	confirmation_required: "Χρειάζεται Επιβεβαίωση",
	confirm_delete_message: "Είστε σίγουροι ότι θέλετε να διαγράψετε αυτά τα μηνύματα;",
	confirm_delete_message_global: "Είστε σίγουροι ότι θέλετε να διαγράψετε αυτό το περιεχόμενο;",
	login_required: "Θα πρέπει να είστε συνδεδεμένοι για να συνεχίσετε.",
	an_error_hash_occurded: "Ουπς! Λάθος!",
	loading: "Παρακαλώ περιμένετε, φορτώνεται...",

	shoutbox_inacitivityWarning: "Έχουμε σταματήσει την λειτουργεία της Συνομιλίας λόγω ότι είσασταν αδρανής. Αν είστε πάλι πίσω, παρακαλώ πατήστε <span id=\"imback\">εδώ</span>.",
	you_have_new_alerts: "έχετε νέες ειδοποιήσεις.",

	javascript_resized: "Αλλαγή μεγέθους από %1px * %2px σε %3px * %4px. Πατήστε στην εικόνα για να την δείτε ολόκληρη.",
	javascript_current: "Προβολή Εικόνας {current} από {total}"
	,turn_on_suggestions: "ενεργοποιήσετε τις προτάσεις",turn_off_suggestions: "απενεργοποιήσετε τις προτάσεις",turn_on_suggestions_alt: "Auto-suggest helps you quickly narrow down your search results by suggesting possible matches as you type.",searching: "Αναζήτηση...",enter_a_search_word: "εισαγάγετε μια λέξη αναζήτησης",forums_search_results: "Αποτελέσματα Αναζήτησης",message_nothing_found: "Δεν βρέθηκε τίποτε.",show_more_torrents: "Προβολή Περισσότερων Τόρρεντ"
};

var TSUESettings = 
{
	charset: "utf-8",
	memberid: "0",
	membername: "Guest",
	memberTimezone: 2,
	memberDST: 0,
	stKey: "0-1486906268-14ed4e4f724b0b58234629a65d738249ef5b295f",
	website_title: "Kapaki - The Place to Be!",
	website_url: "https://kapaki.info",
	theme_dir: "https://kapaki.info/styles/Assassins Creed/",
	website_active: "1",
	website_resize_images_max_width: "665",
	website_resize_images_max_height: "760",
	ajaxHolderID: 'ajaxloader',
	ajaxLoaderImage: '<img src="https://kapaki.info/styles/Assassins Creed/ajax/fb_ajax-loader.gif" class="ajaxLoaderImage">',
	security_enable_captcha: "1",

	shoutbox_enabled: 1,
	irtm_enabled: 0,
	alerts_enabled: 0
};
		//]]>
		</script>

		<script type="text/javascript" src="https://kapaki.info/js.php?lv=2.2&s=jquery,tsue,comments,torrents,login,signup,forgot_password,passwordstrength"></script>

                <script type="text/javascript" src="https://kapaki.info/js/tsue/rasta.js"></script>
		<script type="text/javascript" src="https://kapaki.info/js/tiny_mce/tiny_mce_gzip.js?lv=2.2"></script>
		<script type="text/javascript">tinyMCE_GZ.init({plugins : '-inlinepopups,-smilies,-quote,-tsuecode,-autoresize,-autolink',themes:'tsue',languages:'',disk_cache:true,debug:false});</script>
		<script type="text/javascript">
		//<![CDATA[
			tinyMCE.addI18n('en.tsue',
{
	apply: "Εφαρμογή",
	insert: "Εισαγωγή",
	update: "Ενημέρωση",
	cancel: "Ακύρωση",
	close: "Κλείσιμο",
	font_size: "Μέγεθος γραμματοσειράς",
	fontdefault: "Επιλογή γραμματοσειράς",
	bold_desc: "Έντονο (CTRL+B)",
	italic_desc: "Πλάγιο (CTRL+I)",
	underline_desc: "Υπογραμμισμένο (CTRL+U)",
	striketrough_desc: "Διαγράμμιση",
	justifyleft_desc: "Στοίχιση αριστερά",
	justifycenter_desc: "Στοίχιση στο κέντρο",
	justifyright_desc: "Στοίχιση δεξιά",
	bullist_desc: "Μη αριθμημένη λίστα",
	numlist_desc: "Αριθμημένη λίστα",
	undo_desc: "Αναίρεση (CTRL+Z)",
	redo_desc: "Επανάληψη (CTRL+Y)",
	link_desc: "Εισαγωγή / Επεξεργασία Συνδέσμου",
	unlink_desc: "Αφαίρεση Συνδέσμου",
	image_desc: "Εισαγωγή / Επεξεργασία Εικόνας",
	removeformat_desc: "Αφαίρεση μορφοποίησης",
	cleanup_desc: "Καθαρισμός λανθασμένου κώδικα",
	forecolor_desc: "Επιλογή χρώματος κειμένου",
	quote: "Παράθεση",
	code_desc: "Εισάγετε μορφοποιημένο κώδικα",
	smilies_desc: "Αισθηματόσημα"
});

tinyMCE.init({ mode:'none', theme:'tsue', language:'', plugins:'-inlinepopups,-smilies,-quote,-tsuecode,-autoresize,-autolink' });
		//]]>
		</script>

		<img src="https://kapaki.info/cron.php?rq=1486906268&amp;lv=2.2" alt="" width="1" height="1" />
	</body>
</html>
Feb 12, 2017 03:31:08 PM	Info	
CardigannIndexer (kapaki): Relogin required`

**Comment by kaso17** [comment]
For magico and kapaki the autoamtic relogin is workign fine for me.
Your log isn't complete (The following lines, etc. after the "Relogin required" are the interesting ones.

Dream Team is doing an update, see http://dream-team.ml/

**Comment by valantislevas** [comment]
ahh i see yesterday was ok before do the post above.. i will check the automatic relogin and if i see any issue i will tell you.. i also reply after the upgrade of dream-team

**Comment by valantislevas** [comment]
@kaso17 Configuration failed: Login failed: No form found on http://magico.info/?p=home&pid=1 using form selector form#loginbox_form

it changed to https:// is possible to upgrade it?

**Comment by kaso17** [comment]
You've to change the site link in the configuration.
There's a small bug with form based login. If you change the url and click ok you still get the error. Just close and reopen the dialog and click okay again.

**Comment by kaso17** [comment]
default is changed with 1865ba1393c557482dd1abeb5184bf5fad9321a9

**Comment by valantislevas** [comment]
fantastic thanks.

**Comment by valantislevas** [comment]
Hello @kaso17 for some reason when i connect my account on Greek-Team tracker is ok.. if i press test said error
```
May 25, 2017 03:28:23 PM	Error	
CardigannIndexer (greekteam): Error while parsing row '<tr> <td align="center" style="padding: 0px" class="row2">
		<a href="browse.php?cat=20">
			<img border="0" src="pic/gameswin.png" alt="Games Windows">			
		</a>
	</td> <td class="row2" align="left">
		<a href="details.php?id=120646&amp;hit=1" class="torname" style="vertical-align: bottom;">
			<b>Steel Division Normandy 44-CODEX</b>
		</a>
		<hr>		&nbsp;&nbsp; <img src="pic/checked2.png" width="17" border="0" alt="Checked - by sudoer - Torrent is OK!" title="Checked - by sudoer - Torrent is OK!">		    <a class="info" href="#">             <img src="pic/free.png">			              <span>Unlimited !<br>				Only Seeding Counted !             </span>
		</a>                                <hr>
		
		<i>
			<font style="BACKGROUND-COLOR: #d0d0e1" size="1">*** Checked by<font color="blue"> Staff</font> - Torrent is ok to download! ***</font>
		</i>
	</td> <td class="row1" align="right">
		<b>
			<a href="details.php?id=120646&amp;hit=1&amp;filelist=1">90</a>
		</b>
	</td> <td class="row1" align="right">0</td> <td class="row1" align="center">
		<nobr>2017-05-24<br>			20:16:40</nobr>
	</td> <td class="row1" align="center">19<br>		hours</td> <td class="row1" align="center">20.44<br>		GB</td> <td class="row1" align="right">
		<b>
			<a href="details.php?id=120646&amp;hit=1&amp;toseeders=1">
				<font color="#000000">6</font>
			</a>
		</b>
	</td> <td class="row1" align="right">
		<b>
			<a href="details.php?id=120646&amp;hit=1&amp;todlers=1">8</a>
		</b>
	</td> <td class="row1" align="center">
		<a href="userdetails.php?id=229234">
			<b>jumaru</b>
		</a> </td> </tr>':

System.Exception: Error while parsing field=date, selector=td:nth-last-child(5), value=19hours +02:00: DateTime parsing failed for "19hours +02:00": System.Exception: FromFuzzyTime parsing failed
  at Jackett.Utils.DateTimeUtil.FromFuzzyTime (System.String str, System.String format) [0x00029] in <31d48d5ba5e14d74937fe73ef8cba7c4>:0 
  at Jackett.Utils.DateTimeUtil.FromUnknown (System.String str, System.String format) [0x002a2] in <31d48d5ba5e14d74937fe73ef8cba7c4>:0 
  at Jackett.Indexers.CardigannIndexer+<PerformQuery>c__async5.MoveNext () [0x01627] in <31d48d5ba5e14d74937fe73ef8cba7c4>:0 

```
Also this happen the same thing on Kapaki tracker..
 Test failed for kapaki: Found no results while trying to browse this tracker

Is possible to check it..?

thanks a lot.

**Comment by valantislevas** [comment]
any news about @kaso17 ?

**Comment by kaso17** [comment]
My account on greek team got deleted (inactive) so I can't test myself.
From your error messages the page layout might have changed.
Can you please post the complete log (with enhanced logging enabled?)

Kapaki is working fine for me. Please open a new issue with a full enhanced log.
