### ISSUE TITLE
[t411v2] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by minitoine** [Jackett/Jackett#2040]
[log.20171029.00011.txt](https://github.com/Jackett/Jackett/files/1425267/log.20171029.00011.txt)
[log.20171029.00012.txt](https://github.com/Jackett/Jackett/files/1425268/log.20171029.00012.txt)
[log.20171029.00013.txt](https://github.com/Jackett/Jackett/files/1425269/log.20171029.00013.txt)

Hi, here the logs files for the tracker T411 v2 failed test.
The command was launch after 16h42, and test failed before 16h46

Hope it helps

minitoine

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the p
ast as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by kriegalex** [comment]
Same thing here.

Jackett Version 0.8.285.0
mono-4.8.1.0_2 (FreeBSD - Freenas 9.10)

**Comment by garfield69** [comment]
Please upgrade to the latest pre-release v0.8.339 which contains a fix for a change t411v2 has made to their search results page recently.

Also, I've just tried accessing t411v2 directly, and I am finding it extremely slow to respond. We're talking several minutes just to pull up a search box. So it may be that Jackett is timing out.
If Jackett is timing out, you will see an `Exception (t411v2): A task was canceled.: A task was canceled.` error, that's assuming you are using the Jackett Dashboard manual search.

**Comment by kriegalex** [comment]
t411 is no more, that's the reason of the problem. This should be removed from the list of providers. Yggtorrent is now t411v2+yggtorrent
