### ISSUE TITLE
Torrenleech/Torrentbytes breaks when new IP is assigned

### ISSUE THREAD

**Issue by zebbe152** [Jackett/Jackett#205]
Hi,

I recently started using Jackett together with sonarr. As indexers I use torrentleech and torrentbytes and I also run a VPN service for added security. Everything works great until the VPN service is restarted or if I reboot the computer. That causes both indexers to stop working, I'm not able to preform searches anymore.

I get this error when I click the test buttons:

Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker
   vid Jackett.Services.IndexerManagerService.<TestIndexer>d__9.MoveNext() i C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:rad 93
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Jackett.Controllers.AdminController.<Test>d__18.MoveNext() i C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:rad 263

I'm guessing it's because I get a new IP address from the VPN provider each time the service is restarted. Is the IP somehow connected to the cookie(s) from torrentleech/torrentbytes?

Anyway, to fix this i need to click on the edit button for each indexer and hit the okay button to "re-save" them, I assume that Jackett preforms a new log in and the cookie is refreshed?

Is there some way to fix this so I don't need to do this every time I reboot the computer? Or maybe add a "refresh cookie" button next to the test button?

**Comment by fatalfurry** [comment]
I have this same question but with freshon.tv. In my case I also a proxy installed that will go through my  VPN. Is there a way to setup the API requests to route through this proxy?

**Comment by smarshallsay** [comment]
Yeah I can confirm this is still an issue :|
If I get time I'll take a look and see if I can fix it but don't hold your breath ;)

**Comment by kaso17** [comment]
is this still a problem?

**Comment by zebbe152** [comment]
@kaso17, Torrentleech seems to be working fine now. 

Torrentbytes however breaks as soon as a new IP is assigned.  I get this error after switching to a new IP "Test failed for torrentbytes: Found no results while trying to browse this tracker". As soon as I "re-save" the settings for everything works again.

**Comment by kaso17** [comment]
Looks like the cookies are bound to your IP.
I'll implement a check to login again if necessary.
Is it just TorrentBytes which behaves like this or other trackers too?

**Comment by zebbe152** [comment]
Not sure if there's any more. I'm using Torrentleech, SceneAccess, IPTorrents and Torrentbytes. Torrentbytes is the only one that I experience this issue with. It wouldn't surprise me if there's a couple of more trackers with this issue though.
