### ISSUE TITLE
v0.8.349 doesn't start on DSM, missing libs.

### ISSUE THREAD

**Issue by kcgthb** [Jackett/Jackett#2050]
Jackett version:  v0.8.349
Mono version (if not using Windows):  4.6.2.7-8

-------------------------------

Right after upgrading form v0.8.339 to v0.8.349, Jackett fails to start with the following error:
```
[...]
2017-10-31 08:32:25.3025 Info Loading Cardigann definition /volume1/@appstore/jackett/share/jackett/Definitions/ztracker.yml
2017-10-31 08:32:25.3199 Info Adding aggregate indexer
2017-10-31 08:32:25.4229 Warn Libcurl failed to initalize. Did you install it?
2017-10-31 08:32:25.4234 Warn Debian: apt-get install libcurl4-openssl-dev
2017-10-31 08:32:25.4234 Warn Redhat: yum install libcurl-devel
2017-10-31 08:32:25.4252 Error Top level exception System.TypeInitializationException: The type initializer for 'CurlSharp.NativeMethods' threw an exception. ---> System.DllNotFoundException: api-ms-win-core-sysinfo-l1-2-0.dll
  at (wrapper managed-to-native) Interop+mincore:GetNativeSystemInfo (Interop/mincore/SYSTEM_INFO&)
  at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture () [0x0001c] in <dd91439f3167478ebd2cbf9c036a1395>:0
  at CurlSharp.NativeMethods..cctor () [0x0000c] in <e7908ee31f0d4133be510ed29d5eb5cb>:0
   --- End of inner exception stack trace ---
  at Jackett.Utils.Clients.UnixLibCurlWebClient.Init () [0x0008a] in <0a90acc946724add8bcae2ba4199a336>:0
  at Jackett.Services.ServerService.Initalize () [0x003e0] in <0a90acc946724add8bcae2ba4199a336>:0
  at JackettConsole.Program.Main (System.String[] args) [0x0058a] in <cfcc44715b314117adcb869359eb5d3b>:0
```

Previous versions (including v0.8.339) work fine.

**Comment by krin-san** [comment]
Same thing. Just switched to pre-releases from v0.8.339 to v0.8.349.
```
2017-10-31 21:08:09.4575 Warn Libcurl failed to initalize. Did you install it?
```

OS info:
```bash
# uname -a
FreeBSD jackett 11.0-STABLE FreeBSD 11.0-STABLE #0 r321665+c0805687fec(freenas/11.0-stable): Tue Sep  5 16:07:24 UTC 2017     root@gauntlet:/freenas-11-releng/freenas/_BE/objs/freenas-11-releng/freenas/_BE/os/sys/FreeNAS.amd64  amd64

# pkg info
apr-1.6.2.1.6.0                Apache Portability Library
ca_root_nss-3.32.1             Root certificate bundle from the Mozilla Project
curl-7.56.1                    Command line tool and library for transferring data with URLs
cvsps-2.1_2                    Create patchset information from CVS
db5-5.3.28_6                   Oracle Berkeley DB, revision 5.3
expat-2.2.1                    XML 1.0 parser written in C
fontconfig-2.12.1,1            XML-based font configuration API for X Windows
freetype2-2.8                  Free and portable TrueType font rendering engine
gdbm-1.13_1                    GNU database manager
gettext-runtime-0.19.8.1_1     GNU gettext runtime libraries and programs
giflib-5.1.4                   Tools and library routines for working with GIF images
git-2.14.1                     Distributed source code management tool
glib-2.50.2_6,1                Some useful routines of C programming (current stable version)
indexinfo-0.2.6                Utility to regenerate the GNU info page index
jbigkit-2.1_1                  Lossless compression for bi-level images such as scanned pages, faxes
jpeg-turbo-1.5.2               SIMD-accelerated JPEG codec which replaces libjpeg
kbproto-1.0.7                  KB extension headers
lcms2-2.8                      Accurate, fast, and small-footprint color management engine
libX11-1.6.5,1                 X11 library
libXScrnSaver-1.2.2_3          The XScrnSaver library
libXau-1.0.8_3                 Authentication Protocol library for X11
libXdmcp-1.1.2                 X Display Manager Control Protocol library
libXext-1.3.3_1,1              X11 Extension library
libXft-2.3.2_1                 Client-sided font API for X applications
libXrender-0.9.10              X Render extension library
libffi-3.2.1_1                 Foreign Function Interface
libiconv-1.14_11               Character set conversion library
libinotify-20170711_1          Kevent based inotify compatible library
libnghttp2-1.26.0              HTTP/2.0 C Library
libpthread-stubs-0.4           This library provides weak aliases for pthread functions
libxcb-1.12_2                  The X protocol C-language Binding (XCB) library
libxml2-2.9.4                  XML parser library for GNOME
mono-4.8.1.0_2                 Open source implementation of .NET Development Framework
nano-2.8.7                     Nano's ANOther editor, an enhanced free Pico clone
openjpeg-2.2.0                 Open-source JPEG 2000 codec
p5-Authen-SASL-2.16_1          Perl5 module for SASL authentication
p5-Digest-HMAC-1.03_1          Perl5 interface to HMAC Message-Digest Algorithms
p5-Error-0.17025               Error/exception handling in object-oriented programming style
p5-GSSAPI-0.28_1               Perl extension providing access to the GSSAPIv2 library
pcre-8.40_1                    Perl Compatible Regular Expressions library
perl5-5.24.3                   Practical Extraction and Report Language
pkg-1.10.1                     Package manager
png-1.6.32                     Library for manipulating PNG images
py27-pillow-3.4.2_1            Fork of the Python Imaging Library (PIL)
py27-setuptools-36.2.2         Python packages installer
py27-tkinter-2.7.14_6          Python bindings to the Tk widget set (Python 2.7)
python27-2.7.14                Interpreted object-oriented programming language
readline-7.0.3                 Library for editing command lines as they are typed
renderproto-0.11.1             RenderProto protocol headers
scrnsaverproto-1.2.2           ScrnSaver extension headers
serf-1.3.9_1                   Serf HTTP client library
sqlite3-3.20.1_1               SQL database engine in a C library
subversion-1.9.7               Version control system
tcl86-8.6.7                    Tool Command Language
tiff-4.0.8                     Tools and library routines for working with TIFF images
tk86-8.6.7                     Graphical toolkit for Tcl
webp-0.6.0_4                   Google WebP image format conversion tool
xextproto-7.3.0                XExt extension headers
xproto-7.0.31                  X11 protocol headers
```

**Comment by flightlevel** [comment]
I know this was working for you previously but could you confirm you do have libcurl installed
Step 2
https://github.com/Jackett/Jackett/blob/master/README.md#installation-on-linux
@NathanNZ any ideas?

**Comment by NathanNZ** [comment]
459 seems to be after the change of Curlsharp - will have a look now to see if I can reproduce it in freenas.

**Comment by NathanNZ** [comment]
Pull request pending - sorry for the inconvenience, and thanks for the information to help track down the issue @kcgthb @krin-san  🥇

**Comment by krin-san** [comment]
@NathanNZ, thank you for the quick resolution! Looks uncommon for me so I could spent much more time fixing it.

**Comment by flightlevel** [comment]
Can you all try latest pre-release and report back
https://github.com/Jackett/Jackett/releases/tag/v0.8.354

**Comment by kcgthb** [comment]
Yup, v0.8.354 works great, thank you!

**Comment by krin-san** [comment]
Works great! Thanks

**Comment by skupjoe** [comment]
Latest release also broke my libcurl, even though this was installed. The pre-release fixed my issues, thank you. Please merge ASAP :)

**Comment by nicoduj** [comment]
Hi, I have the same problem, how do you force jackett to switch to the pre release since it can't start at all ?

**Comment by extric99** [comment]
How can i install this prerelease in my DSM environment? Tried searching but I found no way to install either the tar.gz or zip. I would prefer not to uninstall to keep my config.

**Comment by hugoduraes** [comment]
Yes, how can I install the pre-release?

**Comment by hugoduraes** [comment]
@extric99 I was unable to start Jackett on my Synology. So I reinstalled it and updated through the web interface. There, you can check the "update to pre-releases" checkbox.
Don't know if that fixes the issue, though!

**Comment by skupjoe** [comment]
Gotta do it manually:

Make a new directory, wget the latest .gz.bz, tar -xvzf <file> to extract it, fix permissions/chown, then mv ./* into the old directory. You might need to delete one or 2 folders from the old directory to move the new ones in.

**Comment by krin-san** [comment]
On FreeNAS I referred to [this installation guide](https://gist.github.com/BernCarney/35d904822d79be37eafcb277321415ec#jackett). **If config files are stored in a different location** than Jackett folder, it's safe to perform this:
```
cd /usr/local/share
# Make a backup
mv Jackett Jackett_bak

fetch https://github.com/Jackett/Jackett/releases/download/latest/Jackett.Binaries.Mono.tar.gz
tar -xzvf Jackett.Binaries.Mono.tar.gz
rm Jackett.Binaries.Mono.tar.gz

# Test update by starting service
service jackett start
```
If everything gone well, don't forget to remove a backup folder
```
cd /usr/local/share/
rm -rf Jackett_bak
```

**Comment by flightlevel** [comment]
Should be okay now
Suggestions:
1- Update Mono to 4.8, 5.0, 5.2 or 5.4 -> Then you won't have to use libcurl, HttpClient (Mono 4.8+) is much faster
2- If you can't copy files, turn off pre-releases. Pre-releases are beta versions, you should expect some breakages on pre-releases, that's why we use them, can never test in every environment. If you don't want to be a tester turn off pre-releases

**Comment by hugoduraes** [comment]
@flightlevel how can I update Mono? I'm using Mono 4.6 on my Synology.

**Comment by kaso17** [comment]
@hugoduraes nobody of the devs is using a synology box, i suggest you ask the synology community

**Comment by VadVoci** [comment]
Same thing happened to me ..

uname -a
Linux Synology 3.10.35 #1 SMP Tue Feb 2 17:44:24 CET 2016 x86_64 GNU/Linux synology_bromolow_3615xs

ipkg list_installed
cacerts - 20171031-1
gconv-modules - 2.25-4
glibc-opt - 2.25-1
ipkg-static - 0.2.4-1
libcurl - 7.55.0-2
libcurl-dev - 7.55.0-2
libnsl - 2.25-1
openssl - 1.0.2h-2
wget - 1.19.1-3
zlib - 1.2.8-2

ls /volume1/@appstore
DNSServer          debian-chroot      jackett            python
Perl               deluge             minidlna           sshfs
Plex Media Server  ebi                mono               znc
VPNCenter          git                nzbdrone
couchpotatoserver  ipkgui             plexpy-custom

find / -name mono
/usr/syno/etc/packages/mono
/usr/local/mono
/var/packages/mono
/volume1/@tmp/pkglist.tmp/icon/AVAIL/OTHER/mono
/volume1/@tmp/pkglist.tmp/icon/INST/mono
/volume1/@appstore/debian-chroot/var/chroottarget/volume1/@tmp/pkglist.tmp/icon/AVAIL/OTHER/mono
/volume1/@appstore/debian-chroot/var/chroottarget/volume1/@tmp/pkglist.tmp/icon/INST/mono
/volume1/@appstore/debian-chroot/var/chroottarget/volume1/@appstore/mono
/volume1/@appstore/debian-chroot/var/chroottarget/volume1/@appstore/mono/bin/mono
/volume1/@appstore/debian-chroot/var/chroottarget/volume1/@appstore/mono/etc/mono
/volume1/@appstore/debian-chroot/var/chroottarget/volume1/@appstore/mono/lib/mono
/volume1/@appstore/mono
/volume1/@appstore/mono/bin/mono
/volume1/@appstore/mono/etc/mono
/volume1/@appstore/mono/lib/mono

The troubleshoots started from this time:
2017-10-31 12:55:23.6262 Info Jackett Updater v0.8.349 
2017-10-31 12:55:23.6857 Info Options "--Path" "/volume1/@appstore/jackett/share/jackett" "--Type" "mono" "--Args" " jackettconsole.exe " "--KillPids" "22579" 
2017-10-31 12:55:23.7406 Info Finding files in: /tmp/JackettUpdate-v0.8.349-636450513223823940/Jackett/ 
....
2017-10-31 12:55:23.9568 Info Process 22579 is already dead 
2017-10-31 12:55:23.9576 Info Starting Jackett: mono /volume1/@appstore/jackett/share/jackett/JackettConsole.exe  jackettconsole.exe
....
2017-11-07 18:30:53.2183 Info Adding aggregate indexer 
2017-11-07 18:30:53.3923 Warn Libcurl failed to initalize. Did you install it? 
2017-11-07 18:30:53.3923 Warn Debian: apt-get install libcurl4-openssl-dev 
2017-11-07 18:30:53.3923 Warn Redhat: yum install libcurl-devel 
2017-11-07 18:30:53.3930 Error Top level exception System.TypeInitializationException: The type initializer for 'CurlSharp.NativeMethods' threw an exception. ---> System.DllNotFoundException: api-ms-win-core-sysinfo-l1-2-0.dll
  at (wrapper managed-to-native) Interop+mincore:GetNativeSystemInfo (Interop/mincore/SYSTEM_INFO&)
  at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture () [0x0001c] in <dd91439f3167478ebd2cbf9c036a1395>:0 
  at CurlSharp.NativeMethods..cctor () [0x0000c] in C:\projects\jackett\src\CurlSharp\NativeMethods.cs:51 
   --- End of inner exception stack trace ---
  at Jackett.Utils.Clients.UnixLibCurlWebClient.Init () [0x0008a] in <0a90acc946724add8bcae2ba4199a336>:0 
  at Jackett.Services.ServerService.Initalize () [0x003e0] in <0a90acc946724add8bcae2ba4199a336>:0 
  at JackettConsole.Program.Main (System.String[] args) [0x0058a] in <cfcc44715b314117adcb869359eb5d3b>:0

Today i made a manual update to version /v0.8.354/Jackett.Binaries.Mono.tar.gz via WinSCP and the problem has been fixed.

P.S
@kaso17 It's time to buy / build a synology machine for yourself.  :)
I built one with only 50 euros(without the HDD price)

Thank you for your work!

**Comment by kaso17** [comment]
m4tt075 is offering mono 5.8 packages for synology here which should fix your issues:
SynoCommunity/spksrc#2808 (comment)
If your platform is still missing please ask m4tt075 to build a package for your platform.
