### ISSUE TITLE
[REQ] www.ettv.tv

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#2052]
The TV and movie torrent uploaders ETTV and ETHD have now joined forces and launched a torrent site of their own, simply named ETTV.tv.

https://torrentfreak.com/extratorrent-uploader-groups-launch-their-own-torrent-site-171031/

I'll wait until the new site has become stable (currently a WIP with lots of changes happening daily) and then I'll code up a definition.

**Comment by garfield69** [comment]
Bugger. www.ettv.tv do not have a magnet or .torrent in the primary search results page.
And the details page for a download has only a magnet, which Jackett's Cardigann cannot handle :-(

**Comment by sayem314** [comment]
convert a magnet link into a .torrent file ?
https://github.com/danfolkes/Magnet2Torrent

**Comment by garfield69** [comment]
To convert a magnet to a .torrent I have previously used itorrents.org. Simply grab the the hashinfo code from the magner URI, and prepend `http://itorrents.org/torrent/` and append `.torrent`.     
The problem is that the Jackett Cardigann code at the moment does not support pre-processing on the download command. It assumes it is a .torrent, and takes whatever href we point it to from the site's details page, and uses it to download the .torrent metadata,    
The Jackett Cardigann code would need to be changed to either a) allow pre-processing, or b) detect that the URI is a magnet and handle it differently from .torrent .

**Comment by matmuilwijk** [comment]
Just curious, but isn't TPB only magnets as well? This is already implemented in Jackett, and works anyway.

However, i cant make anything on the Definition to find out how it works. 

Although, I'm pretty sure that Sonarr and Radarr import magnets from the Torznab-feeds, since the only other tracker I have active is the native RARBG indexer.

**Comment by garfield69** [comment]
@matmuilwijk  the difference here is that TPB has its magnet links on the primary search results page.    
Jackett Cardigann can handle magnets (and .torrent) links on the primary search results page.     
But ETTV does not have magnets or .torrents on the primary results page. You have to first click on the details link of a search result, and then click on the download magnet button on that secondary page.          
Its the extra processing for magnets that Jackett Cardigann cannot currently handle.     
If it had been a .torrent link on the details page, then Jackett Cardigann can handle that.

**Comment by matmuilwijk** [comment]
@garfield69 Ah, I see. Maybe I'm not much of a developer, but I sure as hell can try and contact these guys. Pretty sure that they're willing to adjust something here and there to get their traffic, and their seeds up. :)

**Comment by kaso17** [comment]
@matmuilwijk please do so and ask them to provide the magnet link as part of their search results (not just on the details page).

**Comment by matmuilwijk** [comment]
I've mailed them through their Whois-protected mail adress, and send all of their admins a PM on their website. Still no response, so all that's left is waiting for a response. :)

**Comment by matmuilwijk** [comment]
Still no response. I've posted the request on their forum as well. They had a suggestionbox, and I couldnt help myself....

**Comment by kaso17** [comment]
#1063 is a realted issue
@sayem314 thank you for your suggestion of Magnet2Torrent.
It's using libtorrent to connect to the DHT, etc. network and get the torrent file.
We certainly could do something similar using https://github.com/libragnar/ragnar 
but I would like to avoid adding more native libraries to the project

I'll add support for indirect download/magnet link redirects and see how sonarr, etc. handle these.

**Comment by kaso17** [comment]
magnet support via a6b5401c0be94aab3bcae7aa59fc11fb2c975ef7
ETTV was added via 7b8f6ccd7fd8a48be01fcfbb223c4b1ea02c9280

**Comment by kaso17** [comment]
Please test pre-release v0.8.396 which contains ETTV support.
For me it's working fine in combination with sonarr+deluge
Please report you test results.

**Comment by matmuilwijk** [comment]
It's working great with Sonarr+uTorrent server. However, in Radarr I get weird results that are in no way associated with what I'm looking for... Tried it with both name-searching swithed on, and off. Results are not even matching when doing a manual search on the site.
![screenshot 2017-11-09 15 49 46](https://user-images.githubusercontent.com/20720945/32611380-cb3b11f6-c565-11e7-8180-0daae72a6818.png)
![screenshot 2017-11-09 15 50 19](https://user-images.githubusercontent.com/20720945/32611381-cb579038-c565-11e7-9be7-88a702dfbdf2.png)

**Comment by matmuilwijk** [comment]
After looking at the definition: Could it be that it's having trouble with searching multiple categories? When I check the URL on the site, it changes to c{category number}={category number}&search={search+query}&cat={cat number}&etc&etc... I can't find anything of this in the definition. Just a simple straight search in a single category, yet the logs show 1 query made for all cats...

**Comment by matmuilwijk** [comment]
Update: same problem in Sonarr... Getting loads of hits that are not even near the search parameters.

**Comment by garfield69** [comment]
found the problem and provided a fix, which the next release (or pre-release) should include.

**Comment by matmuilwijk** [comment]
Fix confirmed. Getting the right results now. Thanks @garfield69 !

**Comment by sayem314** [comment]
I'm late on testing but everything is working smooth :)

**Comment by ilike2burnthing** [comment]
https://www.ettvcentral.com/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://www.ettvcentral.com/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://www.ettvcentral.com/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.ettvcentral.com/ - Error 521 - Web server is down

**Comment by garfield69** [comment]
Definitively gone: https://torrentfreak.com/piracy-icon-ettv-officially-shuts-down-due-to-a-lack-of-funds-220206/

**Comment by garfield69** [comment]
v0.20.521
