### ISSUE TITLE
RevolutionTT - Can't establish SSL connection

### ISSUE THREAD

**Issue by some-guy-23** [Jackett/Jackett#206]
Today I noticed the RevoluionTT tracker is no longer working, not sure when it started. I tracked down the issue and it seems that it is related to a recent change of how their SSL works via CloudFlare.

They've used CloudFlare for a while, and I originally setup the index class to work with it. However, they have a thread in the forums about how a change to use "SNI SSL" by CloudFlare broke the tracker for older clients. The team at RevolutionTT apparently changed something as of yesterday to fix this. However, this seems to be the same time that the SSL connection via Jackett broke.

I'm a bit stumped on where to go with debugging from here, so opening this issue in case anyone with more experience in this area has any ideas. You don't need credential for the site, can just type in any log-in while debugging and will see the error.

Here are the details -

```
<Message>An error has occurred.</Message><ExceptionMessage>The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.</ExceptionMessage><ExceptionType>System.Net.WebException</ExceptionType><StackTrace>   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)</StackTrace><InnerException><Message>An error has occurred.</Message><ExceptionMessage>The remote certificate is invalid according to the validation procedure.</ExceptionMessage><ExceptionType>System.Security.Authentication.AuthenticationException</ExceptionType>
```

Additional details I got from running trace log during connection -

```
System.Net Information: 0 : [9884] SecureChannel#51781231 - Remote certificate has errors:
System.Net Information: 0 : [9884] SecureChannel#51781231 -     A certificate chain could not be built to a trusted root authority.

System.Net Information: 0 : [9884] SecureChannel#51781231 - Remote certificate was verified as invalid by the user.
```

The odd thing is that the site loads just fine in my web browser (over SSL). So, not sure why Jackett is not using the same root certs as the browser?

**Comment by JigSawFr** [comment]
You can use an option when starting Jackett to bypass cert validation :)

**Comment by some-guy-23** [comment]
Seems like a bit of a hack though, the cert is showing as valid in-browser, so why shouldn't it also be valid for Jackett client?

For the option, assume you are talking about "--IgnoreSslErrors true". I'm on Windows with Jackett installed as a service. Any tips for adding that as a command line parameter?

**Comment by Azerelat** [comment]
Does the web site work ok in ie/edge?  Other browsers will carry their own certs

**Comment by some-guy-23** [comment]
Yeap, it loads fine in Chrome, Firefox, IE, Edge, and Opera.

**Comment by JayMan6014** [comment]
I am seeing the same issue with Jackett on windows. The odd thing is Windows 10 it works fine, WIndows 7 is where the issues start.

**Comment by some-guy-23** [comment]
I'm on Windows 10 and having the issue.

**Comment by xllnk** [comment]
I'm using Windows 10 and i'm having the same problem with Revtt. I've tried usinng both Chrome and Edge. Here's the error I get when trying to add revtt: "Configuration failed: An error occurred while sending the request."

**Comment by JayMan6014** [comment]
Must be just during the adding process. I just moved my Sonarr to another machine and can't readd Revtt into Jackett but if I go back to my old machine it is still working.

**Comment by some-guy-23** [comment]
JayMan6014, can you make a backup of your config, remove RevoTT, and try re-adding it on the machine that is currently working? Then can restore the config if it ends up actually being a problem specific to login.

I was having issues both with the initial/setup (login) request and all other requests/searches over SSL though.

**Comment by JayMan6014** [comment]
@some-guy-23 I could remove it and readd it on the old machine without issues.

**Comment by some-guy-23** [comment]
Thanks for testing it, so definitely sounds related to the machine itself.

**Comment by JayMan6014** [comment]
I just checked RevTT's SSL Cert and it was put in place  Monday, January 18, 2016  the same time I guess the issues started.

**Comment by JayMan6014** [comment]
Ok Fixed it.  Exported the SSL from RevTT as a  p7c file, maually imported into my Sonarr Box and boom RevTT works again.

**Comment by xllnk** [comment]
I just tried that and it didn't work. I used certmgr.msc to import the certificate in Windows 10.

**Comment by JayMan6014** [comment]
I just right clicked on the export and told it to install Cert.   with certmgr you would need to import it to the proper spot.

**Comment by some-guy-23** [comment]
@xllnk - make sure you stop/start your Jackett service. That is how I got it to work after exporting.

**Comment by xllnk** [comment]
Restarting the service did the trick. thanks guys. :)

**Comment by flightlevel** [comment]
This issue hasn't had activity for a while. If the issue still exists, please create a new issue and include full logs. https://github.com/Jackett/Jackett#troubleshooting
