### ISSUE TITLE
[REQ] ettv.tv

### ISSUE THREAD

**Issue by zero77** [Jackett/Jackett#2061]
Tracker Name : ETTV
Type : MOVIE, TV
Public tracker although it has a login option
Supports ~~torrent and~~ magnet
Indexer URL : ettv.tv
Indexer language : English

**Comment by garfield69** [comment]
Not currently possible :-( 
see #2052 for explanation.

**Comment by zero77** [comment]
ok, thanks

**Comment by garfield69** [comment]
@zero77  FYI ETTV has now been added to Jackett.

**Comment by zero77** [comment]
Thank you
