### ISSUE TITLE
[torrentday] Exception (torrentday): Request to https://torrentday.it/browse.php failed (Error 522) - The tracker seems to be down.: Request to https://torrentday.it/browse.php failed (Error 522) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by RyanOver9000** [Jackett/Jackett#2064]
Torrentday not working due to the inability to connect to https://torrentday.it/browse.php
Can confirm that I am also unable to reach this URL.

I am however able to access the site https://torrentday.com/browse.php

Jackett version:  Jackett Version 0.8.321.0
OS: UnRaid
Docker: LinuxServer.io version

-------------------------------

**Comment by RyanOver9000** [comment]
Whenever I tried to re-add the indexer to hopefully configure it differently, I noticed TorrentDay was no longer on the list.  Has this been removed?

**Comment by myoho1** [comment]
I had the same issue, though once I removed the indexer, TorrentDay showed back up in the list. However, when I click the configure button, nothing happens.

**Comment by RyanOver9000** [comment]
Can confirm what @myoho1 reports. Same exact thing happened.

**Comment by RyanOver9000** [comment]
Looks like https://torrentday.it/browse.php" is back up.  

This may be something to still look into, using the main domain rather than a mirror.
