### ISSUE TITLE
[YGGTorrent] Wrong categories ?

### ISSUE THREAD

**Issue by minitoine** [Jackett/Jackett#2066]
I'm trying to use YGGTorrent with Sonarr, well, it works except the RSS feeds are wrong ?

102182 for TV Shows (for exemple) but the results has nothing to do with what it is on the website.
And whatever I choose for the categories, I always get the same results : "popular" which is the main page
Are you sure about categories ?

Regards

**Comment by garfield69** [comment]
I've taken a look at the yggtorrent definition for you, and I see that it only supports the general search query.
This means that the tv-search query that Sonarr uses is not supported by this definition.

**Comment by garfield69** [comment]
Out of interest, what category(s) have you loaded your Sonarr indexer for yggTorrent?

**Comment by minitoine** [comment]
Well, thanks, I think we have to ave for their v2.
Can you please tell me where do you find the definitions ? (link or technique)
I was looking for these last night, and came here because I didn't found anything..

Thanks !

**Comment by garfield69** [comment]
>Can you please tell me where did you find the definitions ? (link or technique)     

- The definition source is at 
 https://github.com/Jackett/Jackett/tree/master/src/Jackett/Definitions
- a wiki on what it all means is at https://github.com/Jackett/Jackett/wiki/Definition-format
- and you will find the active working copy of the definition locally on your windows PC at `C:\ProgramData\Jackett\Definitions`

**Comment by garfield69** [comment]
>Well, thanks, I think we have to wait for their v2.

I'll have a go at improving the definition and see if we can get it working with Sonarr's rss feeds requests.

**Comment by minitoine** [comment]
Thanks for you reply and your time spent on this.

Actually, I was asking about the YGG categories definition. How do you know 5000 is for TV ? 
Is there a standard ? (It seems since most of the trackers use 5000 for TV). Do you analyse the html url of each category directly on the website ?

I will also try to figure out what happens. 
Whatever the asked category, YGG sends the same results.

**Comment by garfield69** [comment]
>Actually, I was asking about the YGG categories definition. How do you know 5000 is for TV ?

Jackett uses the newznab categories, which are defined at https://github.com/nZEDb/nZEDb/blob/dev/docs/newznab_api_specification.txt#L608-L695

>Do you analyse the html url of each category directly on the website ?

When preparing a Jackett Cardigann definition, first I examine the HTML produced by the site's search page, and then see if any of the categories match pre-existing newznab ones.
If they exist then these are added to the definition as found.
Any that don't match get defined as *custom* categories, but get cross-assigned the closest real newznab one.

**Comment by garfield69** [comment]
switched to using /today instead of /popular for Sonarr rss feed.
added all available categories.
