### ISSUE TITLE
[kinozal] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Mavrag** [Jackett/Jackett#2069]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  Debian 4.2.1.102+dfsg2-7ubuntu4

-------------------------------

**Comment by garfield69** [comment]
I don't have any problems accessing this site from my win7 jackett dashboard.
Please provide the full enhanced log file. Instructions are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by Mavrag** [comment]
found the problem , i was using this mirror : https://kinozal-tv.appspot.com/  to the site due to isp blocking kinozal.tv and that was the issue
