### ISSUE TITLE
Crashing on armv6 device

### ISSUE THREAD

**Issue by Xerceng** [Jackett/Jackett#2070]
Log: https://pastebin.com/zJPYGcb3

Jackett crashes when you try to load it in the browser.

Jackett version:  v0.8.308.0
Mono version (if not using Windows): 
 `Mono JIT compiler version 5.4.0.201 (tarball Fri Oct 13 22:54:38 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
`

**Comment by NathanNZ** [comment]
May I ask what device and distro you are using? I'm going to try sourcing an old Raspberry Pi and see if I can reproduce the issue this week.

**Comment by Xerceng** [comment]
Device: `Odroid XU4`
Distro: `Dietpi`

I think it has something to do with the mono version. I accidentally updated the mono version and after that Jackett, Sonarr and Radarr were giving the same exact error: `mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb`

**Comment by flightlevel** [comment]
Out of interest can you try starting Jackett with
`mono --debug JackettConsole.exe -c libcurl`
and see if it makes a difference, TLS, Mono and ARM seem to be a dodgy combination

**Comment by Xerceng** [comment]
Tried `mono --debug JackettConsole.exe -c libcurl` but it still gives the same error.

**Comment by flightlevel** [comment]
Closing this as its not a Jackett issue if happening on Sonarr and Radarr as well
Suggestions:
-Downgrade to previous Mono version
-Search around and see if others having similar Mono errors
-Docker
