### ISSUE TITLE
[hon3yhd] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by sayem314** [Jackett/Jackett#2076]
I think the title is self-explanatory.

Since this is private-torrent site you might think my ratio is bad.

![](https://i.imgur.com/trP0lpi.png)

I can manually login and download torrents without any problem/redirection.

Logs: https://paste.ee/p/QRibL
Jackett Version: 0.8.361.0 
Mono version: 5.4.0.201

-------------------------------

![](https://i.imgur.com/JKDSDpU.png)

**Comment by garfield69** [comment]
when you look at the login manually, has the form been changed recently?
![image](https://user-images.githubusercontent.com/6933240/32417428-88b69fc0-c2be-11e7-8c80-1227765a6dca.png)
for instance, has the *now click the button marked* **X** always been thee or is this new?
What about the captcha to prove you are human, is that new?

**Comment by sayem314** [comment]
Login form has not been changed. It qas always like this. I've downloaded few torrents day before yesterday using Jackett on Radarr. It disappeared from Jackett today suddenly (maybe after updates, I didn't notice when).

**Comment by kaso17** [comment]
works for me, please provide the full enhanced log (lines before the error)

**Comment by sayem314** [comment]
Sorry. It was an IP problem. I have tested with different IP and it works. So this can be closed.

**Comment by surajitrana1985** [comment]
I am not able to login as it doesn't show up the image I need to select. Refer the screenshot below:
![image](https://user-images.githubusercontent.com/13241573/59088666-bd0c3580-8925-11e9-974d-100285121480.png)

**Comment by garfield69** [comment]
@surajitrana1985 if the screenshot you provided is of your attempt to login via your browser and it is not working, then this has nothing to do with jackett. 
as the text in red says, you need to enable cookies and javascript on your browser for this site in order to login.

**Comment by avijit-dutta** [comment]
I am also facing the same issue. I have reset the Chrome Browser, then also not. Even I have reinstalled the browser still not working. It is not showing the image.

**Comment by surajitrana1985** [comment]
Again I am getting the same issue. Please refer the screenshot attached below:

![image](https://user-images.githubusercontent.com/13241573/60024770-0abec700-96b6-11e9-85a3-ec0c569fe41c.png)

**Comment by MithuJani** [comment]
![Screenshot_2019-06-24 Hon3yHD Login](https://user-images.githubusercontent.com/52174299/60040442-73b43800-96d2-11e9-9d1b-b7f7f77c4f79.png)

**Comment by MithuJani** [comment]
plz fix it

**Comment by garfield69** [comment]
let clear up any misunderstandings.

are you saying that you are not able to login via your browser directly to the https://hon3yhd.com/login.php web site ?

Because if this is so, then there is nothing we can do to help you. We are not admins for the hon3yhd web site and have nothing to do with supporting the site.

Are you saying that you can login to hon3yhd directly via your browser, but cannot use the jackett app to do so?

Then ensure you upgrade jackett to v0.11.440 then edit the jackett hon3yhd indexer and update the config with the cookie by following the config instructions.

**Comment by kris419** [comment]
Give me 1  invitation code please. ctgmam@gmail.com

**Comment by garfield69** [comment]
@kris419 this is not an invitation forum. Please look elsewhere.
