### ISSUE TITLE
"Jackett.Tray has stopped working" on Windows Server 2012

### ISSUE THREAD

**Issue by ericwbentley** [Jackett/Jackett#2086]
Tried running Jackett v0.8.361 on Windows Server 2012 R2, with .NET 4.5 feature fully installed. After launch it will immediately fail with "Jacket.Tray has stopped working" and problem details as follows:

> Problem signature:
>   Problem Event Name:	CLR20r3
>   Problem Signature 01:	JackettTray.exe
>   Problem Signature 02:	0.8.361.0
>   Problem Signature 03:	59feedee
>   Problem Signature 04:	Autofac
>   Problem Signature 05:	3.5.0.0
>   Problem Signature 06:	539f2b9b
>   Problem Signature 07:	415
>   Problem Signature 08:	44
>   Problem Signature 09:	X1KM4HEGKILRYMEUFC0GIJTXT1QE2ALE
>   OS Version:	6.3.9600.2.0.0.272.7
>   Locale ID:	1033
>   Additional Information 1:	5861
>   Additional Information 2:	5861822e1919d7c014bbb064c64908b2
>   Additional Information 3:	5f25
>   Additional Information 4:	5f2531ae070278f893fa99352dadd49e

Here are the exported events from Event Viewer application logs
[jackett_crash.zip](https://github.com/Jackett/Jackett/files/1449526/jackett_crash.zip)

**Comment by kaso17** [comment]
Is the actual jackett service working?

**Comment by ericwbentley** [comment]
It looks like the Jackett service is not even installed, which is strange. This is after uninstalling and reinstalling a couple times.

It looks like the service may have been installed at one point though, there's another application log with source "Jackett" with error "Service cannot be started. The service process could not connect to the service controller"

Just to make sure, I uninstalled Jackett again, rebooted, and ran installer as administrator. There's no Jackett service listed in MMC services snap-in

**Comment by seanvree** [comment]
yeah, I'm also getting this issue as well when I try to update via the WebUI, I'll get this error in Windows Event logs:

```
The Service Control Manager tried to take a corrective action (Restart the service) after the unexpected termination of the Jackett service, but this action failed with the following error: 
An instance of the service is already running.
```

Possibly related:

https://github.com/Jackett/Jackett/issues/2087

**Comment by wesleycombs** [comment]
Same issue - Server 2012 virtual machine on Esxi.

**Comment by echyzowski** [comment]
Yes, I get the same issue after uninstalling and re-installing.
Also a W2012R2 Server in an ESXi 6.5 VM Environment.

**Comment by flightlevel** [comment]
@NathanNZ 
Would you be able to have a look at this one, I'm hopeless with Autofac

Repro:
Start the Jackett.Tray

![image](https://user-images.githubusercontent.com/9430010/32540779-d0c6838e-c4c1-11e7-8a31-cd2358293937.png)

**Comment by ericwbentley** [comment]
Should the service not being installed by the installer be tracked as a different issue? With v0.8.355 the service is installed and tray application is not crashing

**Comment by NathanNZ** [comment]
Sorry - my bad. Messed up a merge and left a class in the wrong assembly. Pull request to fix this above.

Still don't like the way Autofac does things but not going to change anything until I have a good think about how we could improve what we have 👍
