### ISSUE TITLE
[archetorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by kindyy** [Jackett/Jackett#2090]
An error occured while testing this indexer
Found no results while trying to browse this tracker

Jackett version:   0.8.361.0
Mono version (if not using Windows):   From Nas Synology

-------------------------------

**Comment by garfield69** [comment]
Please include full enhanced log file. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by kindyy** [comment]
After delete and add, test is OK
