### ISSUE TITLE
[shareisland] Login Failed, got redirected

### ISSUE THREAD

**Issue by rafuz** [Jackett/Jackett#2093]
Something happened to the shareisland plugin (italian private tracker)
This morning I began to get some errors on login.

Platform: Ubuntu Server 17.04
Jackett Version 0.8.373.0
Mono JIT compiler version 5.4.0.201

`
Nov 08, 2017 09:34:45 AM | Error | {0}
-- | -- | --
Nov 08, 2017 09:34:45 AM | Error | Error on 20171108093445 for Shareisland.txtJackett.ExceptionWithConfigData: Login Failed, got redirected   at Jackett.Indexers.CardigannIndexer+<TestLogin>d__16.MoveNext () [0x000cb] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:637  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <9790d962aaad40deb63d33029ba0d2f6>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <9790d962aaad40deb63d33029ba0d2f6>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <9790d962aaad40deb63d33029ba0d2f6>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <9790d962aaad40deb63d33029ba0d2f6>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <9790d962aaad40deb63d33029ba0d2f6>:0    at Jackett.Indexers.CardigannIndexer+<PerformQuery>d__25.MoveNext () [0x0091f] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:1129
Nov 08, 2017 09:34:45 AM | Info | CardigannIndexer (shareisland): Relogin required

`

**Comment by kaso17** [comment]
http://shareisland.org/ is currently down

**Comment by rafuz** [comment]
Yes, now is offline. 
This mornig was online but I did get errors when trying to configure the plugin in jackett.

**Comment by garfield69** [comment]
shareisland is back up and I can confirm the redirection error when using Jackett, and being able to login manually via the browser.
Enhanced log will be provided as soon as #2100 is sorted.

**Comment by kaso17** [comment]
they've enabled https and forcing it, fixed via aa35280ca99db08301dab608f7cec4538b333ddc
