### ISSUE TITLE
Jackett is not auto-starting on linux (Mint 18.2)

### ISSUE THREAD

**Issue by Vitorvlv** [Jackett/Jackett#2099]
Jackett is not working on auto start. It works if I manually start with `mono --debug JackettConsole.exe`

Here is what I am seeing when I do `systemctl status jackett`

```
● jackett.service - Jackett Daemon
   Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Qua 2017-11-08 13:53:20 AMT; 2s ago
  Process: 11725 ExecStart=/usr/bin/mono --debug JackettConsole.exe --NoRestart (code=exited, status=200/CHDIR)
 Main PID: 11725 (code=exited, status=200/CHDIR)

Nov 08 13:53:20 vitor-System-Product-Name systemd[1]: jackett.service: Unit entered failed state.
Nov 08 13:53:20 vitor-System-Product-Name systemd[1]: jackett.service: Failed with result 'exit-code'.
Nov 08 13:53:22 vitor-System-Product-Name systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
Nov 08 13:53:22 vitor-System-Product-Name systemd[1]: Stopped Jackett Daemon.

```
  
Mono version: Mono JIT compiler version 5.4.0.201  

-------------------------------

**Comment by Xedecimal** [comment]
Just started happening for me too. I believe this is related to some kind of update that made the exe not match the MDB, here's the output of `mono --debug JackettConsole.exe`

```
Symbol file /opt/jackett/JackettConsole.exe.mdb doesn't match image /opt/jackett/JackettConsole.exe
Symbol file /opt/jackett/Jackett.dll.mdb doesn't match image /opt/jackett/Jackett.dll

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Jackett.Common, Version=0.8.361.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Jackett.Common, Version=0.8.361.0, Culture=neutral, PublicKeyToken=null'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Jackett.Common, Version=0.8.361.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Jackett.Common, Version=0.8.361.0, Culture=neutral, PublicKeyToken=null'
```

**Comment by garfield69** [comment]
@Vitorvlv is this a first time install or were you using Jackett previously and was working?
What version of Jackett are you on now?
The 200/CHDIR typically means that the systemd config for Jackett does not have a 'User=' defined .... is this the case for you?

@Xedecimal  do you still get the mdb mismatch error if you upgrade to pre-release 0.8.383 ?

**Comment by flightlevel** [comment]
@Xedecimal Delete any file in the Jackett folder ending with `.mdb` and then try again

@Vitorvlv problem is different, he start Jackett from the command line with `mono --debug JackettConsole.exe`

**Comment by Xedecimal** [comment]
I just grabbed the latest release and re-installed the files, Working fine now.

**Comment by kaso17** [comment]
@Vitorvlv is this still a problem for you with the latest version?

**Comment by Vitorvlv** [comment]
Latest version is working fine, thanks!
