### ISSUE TITLE
jackettconsole 0.8.393 -t -l not seeing trace in log?

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#2100]
Jackett version:  0.8.393 win7

I am using the jackettconsole from a windows cmd  with the log and trace enabled
`Jackettconsole -t -l >c:/temp/testingEnhancedLogging.log`
but the log only appears to show Info messages.
Could someone do sanity check for me and confirm that trace logging is working/not working please?
Thanks.

**Comment by kaso17** [comment]
command line options are broken in 393
Enabling it via the GUI should still work.
fixed via b5d846442db1e244162b0923d11aa5fed1adcaa3
