### ISSUE TITLE
[BJ] Movies are mixing in radarr search, or sometimes not showing up at all

### ISSUE THREAD

**Issue by Nottt** [Jackett/Jackett#2101]
Jackett version:  0.8.393.0
Mono version (if not using Windows):   Mono JIT compiler version 5.4.0.201

Examples : It (mixes with other movies), Pete's Dragon ( don't show up at all in radarr ). This issue only happens like 2% of the time, so I don't know what must be happening in those edge cases? If you can't fix this without breaking the other 98% you can just close this :) 

Thanks so much!

------------------------------
[jackettlog.txt](https://github.com/Jackett/Jackett/files/1457293/jackettlog.txt)

**Comment by kaso17** [comment]
radarr is searching for "petes dragon 2016", BJ doesn't return any results for it due to the missing '.
We cant'f fix this properly via Jackett.
