### ISSUE TITLE
Error with installation as a service, Jackett disappearing from tray

### ISSUE THREAD

**Issue by EtienneAllegre** [Jackett/Jackett#2104]
Jackett version: v0.8.361

I've followed the simple installation procedure on a clean W10 installation, I run the installer as administrator, check the box to install Jackett as a service, but when it's done, I can see the tray icon but as soon as i hover it it disappear, I also cannot access the web interface.

Starting it using JackettConsole works fine but it's really instable (often loosing connection to indexers and I need to restart it )

**Comment by Leo-Besancon** [comment]
Hey, same problem here same config (v0.8.361, Win10 x64).

The service doesn't seem to be installed, so I ran `installutil JacketService.exe` (using VS 2017 developer tools) to see if I could install it manually.

I haven't looked at the code, so I don't know if this will be useful (and I don't even know if the service could be installed that way !), but this leads to the following error : 

`Beginning the Install phase of the installation.
See the contents of the log file for the C:\ProgramData\Jackett\JackettService.exe assembly's progress.
The file is located at C:\ProgramData\Jackett\JackettService.InstallLog.
Installing assembly 'C:\ProgramData\Jackett\JackettService.exe'.
Affected parameters are:
   logtoconsole =
   logfile = C:\ProgramData\Jackett\JackettService.InstallLog
   assemblypath = C:\ProgramData\Jackett\JackettService.exe
No public installers with the RunInstallerAttribute.Yes attribute could be found in the C:\ProgramData\Jackett\JackettService.exe assembly.`

There doesn't seem to be an installer class ?

**Comment by flightlevel** [comment]
Latest version should fix, re-open if it doesn't
