### ISSUE TITLE
[enhancement REQ] support login error message display language

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#2105]
Currently it appears that when a login error occurs and the error message is displayed, it is not presented in the language supported by the site.
for example, while testing my definition for Elit Tracker, a Hungarian site that uses `language: hu-hu` and `encoding: iso-8859-2` I see this:
![image](https://user-images.githubusercontent.com/6933240/32625543-570f55f8-c5f1-11e7-8783-b0859238b4e7.png)
The actual text is supposed to look like this:
`Hiba: Hibás felhasználónév vagy jelszó! Győződj meg a helyességükől vagy próbáljd a jelszóemlékeztetőt.Még [9] alkalommal próbálkozhatsz.`
Is this something I can correct by adding an additional statement in my definition, or is it something that requires c# coding support?

**Comment by kaso17** [comment]
fixed via 0b302915d66201b87eb692c919e8ff045439590e
