### ISSUE TITLE
Jackett runs for a second, and then exits

### ISSUE THREAD

**Issue by TheBigC53** [Jackett/Jackett#2109]
I just installed Jackett on a new machine, I have uninstalled and installed a few times.

OS: Win10 x64 Pro

Log is included.

Jackett version:  0.8.361.0

-------------------------------
[Jackett log.txt](https://github.com/Jackett/Jackett/files/1459822/Jackett.log.txt)

**Comment by defect833** [comment]
I've also just installed Jackett on a Win10 x64 Pro machine and am experiencing the same crash shortly after it starts. Windows Event Viewer is reporting the following error:

Application: JackettTray.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Autofac.Core.Registration.ComponentNotRegisteredException

**Comment by TheBigC53** [comment]
From the event log, I have two entries. This one appears first:

Application: JackettTray.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Autofac.Core.Registration.ComponentNotRegisteredException

Immediately followed by:

Faulting application name: JackettTray.exe, version: 0.8.361.0, time stamp: 0x59feedee
Faulting module name: KERNELBASE.dll, version: 10.0.16299.15, time stamp: 0x2cd1ce3d
Exception code: 0xe0434352

**Comment by garfield69** [comment]
From the windows event log you provided, it seems you are on stable release 0.8.361    
Pre-Release 0.8.396 has some autofac tidy-up commits included, so please upgrade to this version and see if it resolves your problem.

**Comment by TheBigC53** [comment]
Sorry, I must be dense. Could you give me a link to the pre-release version that addresses this issue please.

**Comment by garfield69** [comment]
Sure, no problem, here you go.    
https://github.com/Jackett/Jackett/releases/tag/v0.8.396
I'm not saying this will fix it, only that it contains commits that deal with autofac ;-)

**Comment by defect833** [comment]
I can confirm on the same system (Win10 x64 Pro) using the Pre-Release 0.8.396 version this is no longer an issue.

**Comment by TheBigC53** [comment]
Thank you. That version corrected the error.
