### ISSUE TITLE
[REQ] IPTorrents freeleech setting

### ISSUE THREAD

**Issue by nacho692** [Jackett/Jackett#211]
With free=on on the query it should filter only freeleech items.

**Comment by tyler43636** [comment]
+1

**Comment by snowhoro** [comment]
+1

**Comment by eseelke** [comment]
+1

**Comment by kaso17** [comment]
With the new downloadvolumefactor attribute (see https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer) you can identify free leech torrents

**Comment by pietervw** [comment]
This issue is not resolved with the above-mentioned Torznab indexer update for Sonarr, since Jackett is used for others apps too (like Couch Potato). 

An option to only download Freeleech would still be useful for Jackett

**Comment by kaso17** [comment]
On the Potato feed the freeleech attribute is set correctly, so e.g. Couch Potato can decide to download/not to download is based on the freeleech attribute.

**Comment by pietervw** [comment]
Not when you are using IPTorrents through Jackett as source in Couch Potato

**Comment by kaso17** [comment]
Try to open e.g. http://127.0.0.1:9117/potato/iptorrents/api?imdbid=tt2303687&search=Line%20of%20Duty&user=&passkey=XXX
You'll see that "freeleech": true is set. As the potato feed was specified by couch potato I would assume it's possible to filter by that attribute in couch potato.
If it's not possible you've to open a feature request for it @Couch Potato.
