### ISSUE TITLE
[xthor] Exception (xthor): Parse error: Parse error (Test)

### ISSUE THREAD

**Issue by fana13** [Jackett/Jackett#2110]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:   0.8.361.0
Mono version (if not using Windows):  4.8.0

-------------------------------

Hello,

I've got this error since a couple days.
In log :
`Error on 20171110081337 for Xthor.txtSystem.NullReferenceException: Object reference not set to an instance of an object
  at Jackett.Indexers.Xthor+<PerformQuery>d__19.MoveNext () [0x00160] in C:\projects\jackett\src\Jackett.Common\Indexers\Xthor.cs:193 `

**Comment by garfield69** [comment]
Please upgrade to the latest release (currently 0.8.398) and try again. If error persists, then please provide the complete enhanced log.  Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
Thanks.

**Comment by hbooo** [comment]
Same here with Jackett Version 0.8.398.0

Here is a full log : https://pastebin.com/mxpgsENH

**Comment by kaso17** [comment]
@hbooo from your log:
`2017-11-10 10:59:00.5948 Debug IWebClient: Returning InternalServerError =>`
Please check again (might have been a temporary xthor issue.
If it's still a problem please post a log right after Jackett startup.

**Comment by hbooo** [comment]
Hi, 

I still got the problem.
Reboot service and try to test : KO
https://pastebin.com/SR9e4F37

**Comment by kaso17** [comment]
Please try accessing https://api.xthor.bz/?passkey=YourPasskey&search= while the problem occurs, currently it looks like an issue on the xthor side causing the internalServerErrors

**Comment by hbooo** [comment]
Got an error 500 from xthor, looks like it's on their side, thanks for the help

**Comment by maxcore** [comment]
Exactly the same for me

**Comment by kaso17** [comment]
@hbooo it would be great if you could find out if they added some limits.

**Comment by hbooo** [comment]
It looks like the error is raised if calls are made  within one minute.

**Comment by itdaboyz** [comment]
The error is because they did something with the API 3-4 months ago. I think they put a limit to the number of calls we can do. Something like one call per 5 minute, yeah that's really low.
Well, at this point it will be better to use a Cardigann definition with the site search function and stop using the API.

**Comment by kaso17** [comment]
did anyone tried to contact the xthor site staff regarding this?

**Comment by itdaboyz** [comment]
I did a month ago and they said it was not a bug but intended. They closed the subject without further information.

**Comment by kaso17** [comment]
Added error handling via 4eda11f79eab2687c9eae2b49d574ce0a88d2052
Can't do anything more here.
If someone writes an alternative cardigann/scraping implementation please submit it as a PR.
