### ISSUE TITLE
SOLVED: [RARBG] Exception (RARBG): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by shanecolliatie** [Jackett/Jackett#2111]
SOLVED:
Updated my certificate using the following steps
1. Download the following file https://curl.haxx.se/ca/cacert.pem
2. Put it somewhere on the NAS.
3. SSH into the NAS
4. Run the following command:
/share/CACHEDEV1_DATA/.qpkg/Qmono/bin/cert-sync /[LOCATION of THE cacert.pem FILE]/cacert.pem
5. Restart the Jackett application.

Seems to work just fine now

Jackett version:  0.8.402.0
Mono version (if not using Windows):  QMono 4.8.1.0 running on QNAP NAS fw 4.3.4

-------------------------------

This just started happening today.. the relevant logs leading up until the problem are:

Nov 10, 2017 01:45:36 PM | Error | {0} -- | -- | --
Nov 10, 2017 01:45:35 PM | Error | On attempt 3 checking for results from RARBG: An error occurred while sending the request
Nov 10, 2017 01:45:33 PM | Error | On attempt 2 checking for results from RARBG: An error occurred while sending the request
Nov 10, 2017 01:45:32 PM | Error | On attempt 1 checking for results from RARBG: An error occurred while sending the request
Nov 10, 2017 01:45:31 PM | Error | {0}
Nov 10, 2017 01:42:24 PM | Info | Starting web server at http://*:9117/
Nov 10, 2017 01:42:24 PM | Info | Deleting JackettUpdate temp files from /tmp/JackettUpdate-v0.8.402-636459181348532810
Nov 10, 2017 01:42:24 PM | Info | HttpWebClient: Disabling certificate validation
Nov 10, 2017 01:42:24 PM | Info | Adding aggregate indexer

**Comment by kaso17** [comment]
dupe #2111

**Comment by ltjdym** [comment]
I'm getting the error: 


share/CACHEDEV1_DATA/.qpkg/Qmono/bin/cert-sync: line 2: /opt/Qmono/bin/mono: No such file or directory
/share/CACHEDEV1_DATA/.qpkg/Qmono/bin/cert-sync: line 2: exec: /opt/Qmono/bin/mono: cannot execute: No such file or directory
[~] #

**Comment by ltjdym** [comment]
downloading newest version of jackett from qnapstore fixed it for me
