### ISSUE TITLE
[shareisland] Exception (shareisland): Parse error: Parse error (Test)

### ISSUE THREAD

**Issue by gipasoft** [Jackett/Jackett#2117]
I use my credential for ShareIsland (on chrome all ok) but I obtain this error: Login Failed, got redirected

**Comment by garfield69** [comment]
Please upgrade to release 0.8.402.
ShareIsland switched to enforcing https, and if you are on a release (or pre-release) older than 0.8.396 then you will not have had your definition updated automatically.     
Alternatively, you can edit your shareisland link directly by using the wrench and replacing the SiteLink address that begins with http to https.
IF you are already on 0.8.402 when you get this error, then please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the location the log file at https://github.com/Jackett/Jackett#troubleshooting.

**Comment by gipasoft** [comment]
Thank for your reply, I was installed 0.8.285 version (on QNAP TS-469 PRO) so now I have upgrade Jacket at 0.8.402, but now I have a big problem for many indexers:
`Exception (1337x): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED: An error occurred while sending the request` 
So I have restored my previous version, in attach the log file
[log.txt](https://github.com/Jackett/Jackett/files/1464558/log.txt)

**Comment by gipasoft** [comment]
Now I've been forced to disable auto update

**Comment by gipasoft** [comment]
If I try to update the certificate I obtain this error:
`-sh: cert-sync: command not found
--2017-11-12 23:58:36--  https://curl.haxx.se/ca/cacert.pem
Resolving curl.haxx.se (curl.haxx.se)... 151.101.62.49
Connecting to curl.haxx.se (curl.haxx.se)|151.101.62.49|:443... connected.
OpenSSL: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
Unable to establish SSL connection.`

**Comment by gipasoft** [comment]
Wow I have solved the certificate problem: [thank at this post](https://forum.qnap.com/viewtopic.php?t=116660&start=75)
But I have always my original problem with ShareIsland, the error is:
`Found no results while trying to browse this tracker` the log in attachment
[log.txt](https://github.com/Jackett/Jackett/files/1465204/log.txt)

**Comment by garfield69** [comment]
well done for sorting out the certificates.
the log shows:
```html
</div> <div class="error" id="show_error">
	<b>Spiacenti.</b><br />Non è possibile visitare questa pagina finchè non hai letto tutti i tuoi messaggi non letti. Clicca <a href="?p=messages&amp;pid=**redacted**">Qui</a> per visitare la pagina dei messaggi.
</div></div>
```
Basically you have to log in manually via your Chrome Browser and read any outstanding messages your account has pending.
After which you should be able to resume using Jackett to browse/search for torrents.

Please confirm this resolves your problem. Thanks.

**Comment by gipasoft** [comment]
Thanks a lot, I confirm that this solve my problems ... only one little problem: the certificate are losed when  I restart my QNAP, but this is not a big problem, I can import the certificate at Autostart job

**Comment by kaso17** [comment]
@gipasoft Thank you for sharing that qnap thread.
You can also try to change to the jackett user (`su -s /bin/sh ...`) and then run `cert-sync --user $file`.
That imports the certificates to the user store (instead of the global one), maybe that one survives a reboot.

If you found a solution it would be grate if you could share a short instructions list for others.
