### ISSUE TITLE
[alpharatio] An error occurred while sending the request: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED) (Config)

### ISSUE THREAD

**Issue by chris-pilly** [Jackett/Jackett#2118]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:
Jackett Version 0.8.361.0

Mono version (if not using Windows):  

Mono JIT compiler version 4.8.1 (Stable 4.8.1.0/22a39d7 Wed Apr 12 12:00:40 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen

-------------------------------
Edit: tried updating CA certs with -> wget -O - https://curl.haxx.se/ca/cacert.pem | sudo cert-sync /dev/stdin

still same error

**Comment by chris-pilly** [comment]
NVM... reboot solved problem 

duh...

**Comment by rocksolid2018** [comment]
getting similar issue. please provides steps to update certificate on Synology platform

**Comment by kaso17** [comment]
@rocksolid2018 please try the latest mono 5.8 builds from https://github.com/m4tt075/spksrc/releases/tag/Mono-5.8.0-fixed

**Comment by rocksolid2018** [comment]
thanks kaso, it fixed the problem

**Comment by Damien13150** [comment]
Hello there,

Getting similar problem and cannot find the solution anywhere,

I tried updating the certificate with wget -O - https://curl.haxx.se/ca/cacert.pem | sudo cert-sync /dev/stdin

Tried rebooting

But still same error, any idea ?
