### ISSUE TITLE
TPB not showing results that contain period instead of spaces

### ISSUE THREAD

**Issue by deanochips** [Jackett/Jackett#2120]
TPB not showing results that contain period instead of spaces

for example

searching "The Russell Howard Hour" will find no results even though there are releases available on the tracker and can be seen if searched manually but they contain periods instead of spaces

if i used jackett and search "The.Russell.Howard.Hour" it will see the releases

**Comment by deanochips** [comment]
adding "tolower" to the keyword filters fixes the issue perhaps that could be added to the release

**Comment by garfield69** [comment]
Huh?
![image](https://user-images.githubusercontent.com/6933240/32694455-0cd646e4-c7a5-11e7-9eae-ef8d965d4e2e.png)
I'm using `https://thepiratebay.org/` as the SiteLink. Are you perhaps using a proxy?
