### ISSUE TITLE
Logging uses Dependency Injection

### ISSUE THREAD

**Issue by NathanNZ** [Jackett/Jackett#2123]
I've noticed that logging is being injected into the indexers via DI. I'm not a huge fan of mixing logging with DI when writing application code as it gives you all the overhead without any of the benefits. 

It also appears we are duplicating a lot of the logic (such as checking if tracing is enabled and such) that NLog already supports out of box, so would be nice to get that cleaned up.

I'm proposing we either use GetCurrentClassLogger in each class, or just rock a property in Engine.cs that points to GetCurrentClassLogger with a predefined value.  NLog's implementation is threadsafe and this is the recommended way via their documentation, so it's not going to be that hard for any new contributors to understand after a quick glance at the NLog documentation.

Should let us clean up a lot of the code - especially in places where logging is after the initialisation of DI due to the dependency on DI finishing.

**Comment by flightlevel** [comment]
Sounds good to me @NathanNZ , absolutely no attachment to the current logging system here.

**Comment by kaso17** [comment]
I fully agree too

**Comment by garfield69** [comment]
Closed as stale.
