### ISSUE TITLE
[1337x] Exception (1337x): An error occurred while sending the request: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by Alculete** [Jackett/Jackett#2127]
When I test 1337x on Jackett I receive the error
`[1337x] Exception (1337x): An error occurred while sending the request: An error occurred while sending the request (Test)`

My Machine Information
Mono JIT compiler version 5.4.0.201 (tarball Fri Oct 13 21:51:45 UTC 2017)
OS: Ubuntu-Server 16.04 xenial
Kernel: x86_64 Linux 4.4.0-98-generic

**Comment by garfield69** [comment]
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.

**Comment by Bowerz** [comment]
I am also getting this, although tested OK a few days ago (since you logged the issue) will grab log files shortly

**Comment by garfield69** [comment]
@Bowerz wrote:     
> the link above doesn't show how to enable full logging?     

![image](https://user-images.githubusercontent.com/6933240/33331523-b3ccde94-d4c6-11e7-8af1-8c63e50bd22f.png)

**Comment by Bowerz** [comment]
Well that's just embarrassing, that was clearly a complete 'man look'. find logs attached after running a test.
[log.txt](https://github.com/Jackett/Jackett/files/1510995/log.txt)

**Comment by garfield69** [comment]
@Bowerz  your log shows that your service provider is blocking access to `1337x.to` by redirecting you to a hard coded dead-end address `193.113.9.167`.

you could try to access the alternate domain at `https://1337x.st/` by using the wrench icon on your Jackett Dashboard and editing the Site Link on the 1337x definition.
![image](https://user-images.githubusercontent.com/6933240/33335949-6ac51204-d4d3-11e7-8cf4-9795aa783ccc.png)

But if that does not work you will probably need to research using a vpn or finding some other valid proxy address for the 1337x site.

**Comment by Bowerz** [comment]
ah, so simple, didn't even think to check if it was blocked as it previously worked. I have updated my DNS settings for media server not to use my ISP's DNS server and now working! Many thanks
