### ISSUE TITLE
[cinemaz] An error occurred while sending the request: Error: SecureChannelFailure (One or more errors occurred.) (Config)

### ISSUE THREAD

**Issue by dewaehem** [Jackett/Jackett#2131]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.

**Comment by garfield69** [comment]
Been a month with no reply. Closing.
