### ISSUE TITLE
[piratethenet] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Hackerpcs** [Jackett/Jackett#2134]
Jackett version: 0.8.409.0
-------------------------------
https://pastebin.com/ugNkDB0L

**Comment by kaso17** [comment]
looks like your cookies are invalid, please try to reconfigure (relogin).

Should happen automatically in the future with 1a85927e440412156ebd1351ad7b973d7e23fe4c

**Comment by Hackerpcs** [comment]
I've relogged in PtN site, relogged in Jacket, restarted Jackett and logged in again but doesn't work

**Comment by kaso17** [comment]
Please try again with version v0.8.416 (pre-release)

**Comment by Hackerpcs** [comment]
With v0.8.416 it works, thank you.
