### ISSUE TITLE
[speed-share] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by DarkSupremo** [Jackett/Jackett#2136]
Jackett Version: 0.8.409.0
Mono version (if not using Windows):  using windows
Log: [log_speed_share.txt](https://github.com/Jackett/Jackett/files/1467172/log_speed_share.txt)

I'm trying to add this tracker, but it's failing at the test, can someone check please?
In the log, looks like it's listing some torrents, but still it show no result
Thanks.

**Comment by kaso17** [comment]
@Guizzoni can you have a look?

**Comment by Guizzoni** [comment]
I'm 100% sure this is something related to the "User Preferences" in the tracker

Go to [http://speed-share.org/account.php?action=edit_settings&do=edit](http://speed-share.org/account.php?action=edit_settings&do=edit) and set "Modelo da Home:" to "Sistema Lista de Torrents"

**Comment by DarkSupremo** [comment]
Yes, that worked. Thanks.

It would be nice to have such info somewhere in the wiki, i did an search for speed-share before posting this issue and didn't found anything related

**Comment by kaso17** [comment]
not sure what that option does but if it's not possible to make the definition work with both options I would suggest adding a note to the configuration. See https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/mteamtp.yml#L61-L64 for an example.

**Comment by Guizzoni** [comment]
Added in #2138

**Comment by kaso17** [comment]
thank you
