### ISSUE TITLE
New tracker request capsbien.io

### ISSUE THREAD

**Issue by Sylrob434** [Jackett/Jackett#214]
Hi guys,

Really nice prject, would love to have  free french tracker

Best Regards,

Sylvain

**Comment by JigSawFr** [comment]
Hi,
At this time, Jackett is providing private trackers only.
This (french) public tracker is considered as a crap by community, and is very dangerous.
You know, french governement (Hadopi institution) is tracking users on this website to assign them in a court or to shut down their connection to internet.
I think, this tracker will not be part of Jackett in a short future.

**Comment by famewolf** [comment]
Will ANY public trackers be supported by Jackett in future?  Lazy Librarian currently only supports kat.cr for torrents and I was in hopes of using jackett to expand it's searchers.

**Comment by JigSawFr** [comment]
In future, probably, we need to create an option in Jaclett to allow public trackers with a warn for users about dangerous situation to use a public tracker.

**Comment by Azerelat** [comment]
Perhaps it can be added by a third party when we do plugin support.  Closing whilst its wontfix.
