### ISSUE TITLE
[REQ-Indexer] private tracker

### ISSUE THREAD

**Issue by r2binx** [Jackett/Jackett#2141]
Hi, I'm trying to add my own indexer however this goes far further than my programming skills. I would really appreciate some help. I can't really figure out the query section. I've copied the indexer file of myAmity and edited the parts I could, like the basic URLs and the categories

The categories are as followed:
>
            AddCategoryMapping(1, TorznabCatType.PC); // Software
            AddCategoryMapping(66, TorznabCatType.AudioAudiobook); // Hoerbuecher
            AddCategoryMapping(53, TorznabCatType.Audio); // Musik / Lossless
            AddCategoryMapping(6, TorznabCatType.Audio); // Musik / Lossy
            AddCategoryMapping(63, TorznabCatType.Movies3D); // HD / 3D
            AddCategoryMapping(51, TorznabCatType.MoviesBluRay); // HD / Untouched
            AddCategoryMapping(62,  TorznabCatType.MoviesDVD); // SD / DVD Rip
            AddCategoryMapping(19, TorznabCatType.MoviesHD); // SD / DVD 
            AddCategoryMapping(48, TorznabCatType.MoviesHD); // HD / Rip 1080p
            AddCategoryMapping(43, TorznabCatType.MoviesHD); // HD / Rip 720p
            AddCategoryMapping(67, TorznabCatType.MoviesHD); // HD / 4K
            AddCategoryMapping(49, TorznabCatType.TV); // Serien / HD
            AddCategoryMapping(7, TorznabCatType.TV); // Serien / SD
            AddCategoryMapping(61, TorznabCatType.TVDocumentary); // Doku / HD
            AddCategoryMapping(25, TorznabCatType.TVDocumentary); // Doku / SD
            AddCategoryMapping(58, TorznabCatType.Console); // Games / Konsolen
            AddCategoryMapping(4, TorznabCatType.PCGames); // Games - PC
            AddCategoryMapping(31, TorznabCatType.Books); // E-Books
            AddCategoryMapping(9, TorznabCatType.Other); // Sonstiges

the search is entered with the following line however thats the part I can't figure out. With subtracker you can search with the following line

> ?cats=43&search=test&incldead=0&searchin=0&imdbid=&team=0&orderby=added&sort=desc

however in myamity it looks like this

> ?search=test&cat=0&incldead=0&freeleech=0&inclexternal=0&lang=0

I'm not quite shure how and what to edit.

Some help would be awesome!
Thank you very much!

**Comment by garfield69** [comment]
These days we try to use Cardigann definitions to support new trackers, and only resort to c# indexers if it requires special additional coding support that Cardigann cannot provide.
The Cardigann definitions are much simpler to code up and support :-)

Browse the existing definitions at https://github.com/Jackett/Jackett/tree/master/src/Jackett.Common/Definitions for examples, and refer to the wiki at https://github.com/Jackett/Jackett/wiki/Definition-format for supporting information.

But if you really want to continue with your c# indexer version, then

start by replacing 
```c#
            queryCollection.Add("incldead", "1");
            queryCollection.Add("freeleech", "0");
            queryCollection.Add("inclexternal", "0");
            queryCollection.Add("lang", "0");
```
with 
```c#
            queryCollection.Add("incldead", "0");
            queryCollection.Add("searchin", "0");
            queryCollection.Add("team", "0");
            queryCollection.Add("orderby", "added");
            queryCollection.Add("sort", "desc");
```

It looks like your new tracker can support imdbid.  Take a look at other c# indexers that handle imdbid to see the different ways this parameter can be supported. I use the GitHub search to find them
![image](https://user-images.githubusercontent.com/6933240/32803000-f8853e22-c9e6-11e7-9d3e-9fece2cc7444.png)

and then drill into each indexer to see which one has the best match for what subtracker expects.

As for the `cats=`, this will depend on how subtracker handles multiple categories. take a look at https://github.com/Jackett/Jackett/blob/571c52a0f2e192c2c00d2007790be73f4fdee436/src/Jackett.Common/Indexers/TorrentNetwork.cs for example. Or search GitHub for cats to see other ways to handle multiple categories.
