### ISSUE TITLE
[b2s-share] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by DarkSupremo** [Jackett/Jackett#2142]
Log: [log_b2s.txt](https://github.com/Jackett/Jackett/files/1469216/log_b2s.txt)

Jackett Version 0.8.409.0
Mono version (if not using Windows):  using windows

Hello, tests are failing to this tracker, maybe there is some setting that i must configure too?
In the log, i can't see the html returned (Enhanced logging is enabled), but if i open the url in the browser, it display the results ok

**Comment by kaso17** [comment]
according to the log a request to http://www.b2s-share.com/torrents-search.php?search= returned an empty document. Can you please try to capture the network traffic using e.g. wireshark and see if the website is actually transmitted?

**Comment by DarkSupremo** [comment]
Looks to me that it's failing to login, or trying to login again every time?

HTTP/1.1 200 OK\r\n
Refresh: 0; url=account-login.php?returnto=%2Ftorrents-search.php%3Fsearch%3D\r\n

Captured packet: [b2s.zip](https://github.com/Jackett/Jackett/files/1476068/b2s.zip)

**Comment by DarkSupremo** [comment]
Tried entering the password again and it worked, maybe i accidentally typed something wrong...

**Comment by Guizzoni** [comment]
Added login selector on #2153 to prevent this from happening again.

**Comment by DarkSupremo** [comment]
Thanks
