### ISSUE TITLE
SSL error with every indexer, running on QNAP with Qmono

### ISSUE THREAD

**Issue by an303042** [Jackett/Jackett#2144]
Searched around and found some options but nothing worked.
Whatever index add i get an exception - Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED: An error occurred while sending the request

Runing Jackett 0.8.285 from here - https://forum.qnap.com/viewtopic.php?f=320&t=116660&start=90
and Qmono 4.8.1.0 on a QNAP NAS.

tried installing CACert, and also running all sorts of command through SSL, but no dice so far..
Any idea would be appreciated!

**Comment by kaso17** [comment]
please try the instructions from #2111

**Comment by an303042** [comment]
Amazing! Works now.. Thanks so much!
