### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Connection refused: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by matteos1** [Jackett/Jackett#2149]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
Works for me, is pirate bay blocked by your ISP? Or maybe it was just a temporary server issue?

**Comment by tylermac** [comment]
Same issue. Able to hit the url from the browser.

**Comment by kaso17** [comment]
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
