### ISSUE TITLE
[REQ] Private tracker -TBplus

### ISSUE THREAD

**Issue by mos388** [Jackett/Jackett#2155]
Requesting support for SpanishPrivate TBplus

Tracker Name: TBplus
Tracker Content: HD Movies, HD Series, Documentals, eBooks.
Tracker URL : https://tbplus.li/
Tracker Language : Spanish

Jackett Version 0.8.402.0

-------------------------------

**Comment by garfield69** [comment]
is this site currently open for registration, or invite only?

**Comment by garfield69** [comment]
never mind, registration is closed, invitation only.

**Comment by mos388** [comment]
I send invitation...
