### ISSUE TITLE
Nyaa.si potato feed

### ISSUE THREAD

**Issue by rourke** [Jackett/Jackett#2157]
Jackett version: 0.8.402.0
Mono version (if not using Windows): 5.4.0.201 (tarball Fri Oct 13 21:51:45 UTC 2017)

-------------------------------

Nyaa.si seems to support movies. Can we get a potato feed for it?

**Comment by kaso17** [comment]
Which of the categories do you consider "movies"?

**Comment by rourke** [comment]
I don't know how it works with the categories here. But I notice a lot of anime movies on the site that I can't index in Radarr. Nyaa.si categories that also contain anime movies:

https://nyaa.si/?c=1_2
https://nyaa.si/?c=1_3
https://nyaa.si/?c=1_4

Some movie examples:

https://nyaa.si/?f=0&c=0_0&q=akira&s=seeders&o=desc
https://nyaa.si/?f=0&c=0_0&q=perfect+blue&s=seeders&o=desc

**Comment by kaso17** [comment]
Which software are you using to get the anime movies (couchpotato or radarr)?

**Comment by rourke** [comment]
I'm using Radarr.

**Comment by kaso17** [comment]
then just use the torznab instead of potato feed and make sure to include category 5070

**Comment by rourke** [comment]
Sorry for reopening. But I can't add torznab to Radarr for nyaa.si because Radarr tries the `t=movie` query in the request url, and it returns the error `nyaasi does not support the requested query`.

**Comment by kaso17** [comment]
@rourke acc8a24c21d017e4f39a65db9868e6130e7b0655 should fix it
