### ISSUE TITLE
[Bug] Base path URL doesn't properly redirect

### ISSUE THREAD

**Issue by some-guy-23** [Jackett/Jackett#216]
I ran into some problems setting up a reverse proxy with Jackett, and tracked it down to an issue with the Base Path setting.

Essentially my reverse proxy is setup at domain.com/jackett and it redirects all requests internally to localhost:9117/jackett. I noticed that for some reason it wasn't loading resources properly (javascript/css/etc.), only the HTML itself.

The issue is, when a Base Path is set up, instead of acting identical to hitting / (without a base URL) and redirecting to /Admin/Dashboard, it will instead just try to load the dashboard page, which breaks all relative URL's.

You can see this also if you load Jackett locally with a base url of "/jackett" and go to http://localhost:9117/jackett

Since it does not properly redirect to /Admin/Dashboard the call to "get_jackett_config" breaks. I would say that with a Base Path, navigating to that base path should result in the same action as navigating to root normally would.

**Comment by jgillman** [comment]
I experienced this too: ![screen shot 2016-06-07 at 1 25 34 pm](https://cloud.githubusercontent.com/assets/172217/15875498/0fb4d814-2cbd-11e6-97f9-821658499f9c.png)


# However

Using Nginx I was able to get a rewrite working with this config:

```
location /jackett/ {
  rewrite /jackett/(.*) /$1 break;
  proxy_bind $server_addr;
  proxy_pass http://127.0.0.1:9117;
}
```

**Comment by flightlevel** [comment]
This should be working now, please reopen if not the case
