### ISSUE TITLE
Jackett not updating or working on Synology

### ISSUE THREAD

**Issue by jasonmotec** [Jackett/Jackett#2162]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by jasonmotec** [comment]
Synology DS 116
DSM 6.1.4
Mono ver: 5.8.0.22-9
Jackett ver: 0.7.1483.0

Recently, My version of Jackett worked for approx. 8 days, and then stopped and will not start up again no matter what I tried (restart Synology, attempt to restart it from the Package Center), 
I had to uninstall it, then re-install it, update it from 0.7.1483.0 to the latest version (the initial ver is the latest version on the synocommunity) reconfigure all my settings, and it would work again well - until 7-9 days and end up with the same result... becoming a tedious task. 
I had Mono 4.6.2 during this time, and discovered that my Mono version was outdated... I have since updated to Mono 5.8.0.22, uninstalled Jackett (as it just stopped working) re-installed Jackett - now it is stuck on version 0.7.1483.0 - when I hit the 'Check for updates' button, it says check logs... logs indicate "Error checking for updates"

Extended logs in Package Center of Synology for Jackett indicate Error: SecureChannelFailure (One or more errors occurred) ---> System.AggresgateException: One or more errors occurred ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception ---> System.DllNotFoundException: /volume1/@appstore/mono/lib/../lib/libmono-btls-shared.so

I have also tried to add the following to the /var/packages/jackett/scripts/start-stop-status: 
"--IgnoreSslErrors true" at the end of Command... but made no difference.

Please help me with this issue - When Jackett does work, it works well - and it has for the past 10 months up until a month ago :(

**Comment by flightlevel** [comment]
What happens when you run
`/var/packages/Mono/target/usr/local/bin/cert-sync /etc/ssl/certs/ca-certificates.crt`

**Comment by jasonmotec** [comment]
I get this:

Linux Cert Store Sync - version 4.6.2.0
Synchronize local certs with certs from local Linux trust store.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

I already trust 173, your new list has 173
Import process completed.

I checked again after running the above command, and still the same issue :(

**Comment by flightlevel** [comment]
Can you try installing Mono 5.8 again from https://github.com/Safihre/spksrc/releases/tag/mono-build-4
Suspect problem has something to do with your version  `Linux Cert Store Sync - version 4.6.2.0`

**Comment by kaso17** [comment]
definitely a problem with the mono package, please follow this issue:
https://github.com/SynoCommunity/spksrc/issues/2808#issuecomment-345655789
