### ISSUE TITLE
[avistaz] Exception (avistaz): An error occurred while sending the request: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by coolboiime** [Jackett/Jackett#2163]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by flightlevel** [comment]
Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
Can't do much without logs

**Comment by coolboiime** [comment]
I fixed it by updating it.
