### ISSUE TITLE
400 BadRequest TPB

### ISSUE THREAD

**Issue by vaxo101** [Jackett/Jackett#2170]
I have linked up Radarr with TPB TorrentPotato index.
When testing indexer in Radarr it tests correctly, however when searching for a specific title it will push out an error:

> HTTP Error - Res: [GET] http://localhost:9117/api/v2.0/indexers/thepiratebay/results/potato/?passkey=(removed)&user=&imdbid=tt1790809.400.BadRequest{Message":"thepiratebay does not support the requested query."}

**Comment by vaxo101** [comment]
This may not actually be an issues to do with Jackett at all due to me just testing a manual search inside the Jackett Admin Dashboard... All results returned correctly - There must be an issue with Radarr.

**Comment by kaso17** [comment]
don't use the potato feed with radar, use the torznab feed
