### ISSUE TITLE
Indexers fail when proxy values are entered

### ISSUE THREAD

**Issue by jclemons7** [Jackett/Jackett#2174]
I'm not positive how to troubleshoot this.  I use TorGuard and no matter what I do, I can't get indexers to work when proxy values are enabled.  Proxy works fine with Sonarr / Radarr / uTorrent etc.. same settings will not work (on the same physical device) with Jackett at all.  I've tried Sock5 and HTTP, no workie

**Comment by garfield69** [comment]
Start by providing some basic info.     
What platform are you using Jackett on, and what version of Jackett are you using.     
Enable the enhanced logging, perform a test and drag&drop the log file here so we can take a look.     
You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.

**Comment by kaso17** [comment]
Please also make sure you're running the latest v0.8.436 pre release as it contains proxy related fixes.

**Comment by garfield69** [comment]
two months and no reply. closing.
