### ISSUE TITLE
Warning in latest Jackett

### ISSUE THREAD

**Issue by gers1978** [Jackett/Jackett#2178]
Running Mono in macOS 10.12

`11-21 22:19:04 Error Error UrlMalformatUser Error: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision. setting option SslCtxFunction`

**Comment by garfield69** [comment]
this looks similar to #2106    
so make sure you are on the latest version of jackett    
and try updating your version of mono, ideally to Mono 5+ , especially if you are still on 4.6    
and finally, refresh you CA certificates `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin `    
let us know how you go.

**Comment by gers1978** [comment]
@garfield69 that fixed it, cheers
