### ISSUE TITLE
missing indexers

### ISSUE THREAD

**Issue by gsgorveatt** [Jackett/Jackett#2180]
I've been using jackett for a while using torrentday and torrenting as my indexers. They seem to be missing of your list in the newest update. Can you add them again. 
Thanks a million

**Comment by garfield69** [comment]
Huh? We have not deleted these indexers.      
I presume you accessed your Jackett Dashboard and your active indexers list is empty?     
If so, then (assuming you are using a Chrome Browser), try using the **Shift-F5** key to force a *refresh-with-Cache-Flush* and see if that restores your list.      
Did that work?

**Comment by gsgorveatt** [comment]
fixed it. I deleted indexer from my list and then added it again and its working good now. thanks. appreciate the help.
