### ISSUE TITLE
Tray icon - does not check for existing instance

### ISSUE THREAD

**Issue by dk4dk4** [Jackett/Jackett#2181]
If you launch Jackett multiple times the tray icons start stacking up.  The app should check for an existing instance and exit before it launches another instance...  The black tray icon is also really hard to work with.

![jackett_tray_icons](https://user-images.githubusercontent.com/33904434/33135430-599de626-cf70-11e7-92d7-550d21b153dd.png)

**Comment by garfield69** [comment]
Confirmed. This also occurs on my win7 PC installed with Jackett as a service. You can start multiple JackettTray instances.
