### ISSUE TITLE
Newsnab + Medusa (sickrage fork) 

### ISSUE THREAD

**Issue by saitoh183** [Jackett/Jackett#2182]
Over on Medusa I posted a problem that when Medusa used jackett to pick up new files, it would create the torrent file with a nzb extension instead of a torrent extension. The problem was corrected but it is now broken again because seems that jackett changed the format of the file retrieval. Here is the link to the issue in Medusa https://github.com/pymedusa/Medusa/issues/3149

Here is the snatched info that the Medusa correction was based on...the file name finishes with .torrents
```
SNATCHQUEUE-MANUALSNATCH-316544 :: [3f23fd2] GET URL: http://192.168.13.198:8086/jackett/dl/ethor/?jackett_apikey=b66if81o0czme93f44ooj49rb0a9ta8a&path=LzJBaGhZSERiT045RXFsU2o0aGJYSjBaV3dNYVFKVUxzVmV1Z0Q5ckhnWmJZNXd2eDdVUEtZUzhTN2Z1SVpUMjgvSmk2eUJ5VTZHWmdvb0d1T2VpREFZSUZLbm9pV3ZDUGg2Nk5oMW03NktpaS9xWmloSkxqZlhWcXNWcytYSEtXTkxBQ2VmMC92bTlZT3VTYk5rWk9YOGhjMjV4Z1NwVGQ5Uld6R0hCOStEZUxlem1iQ1lnMXZEdnArSDVsZUZFZVA3VEd1enhlUExOSTNBSDBVZk1oYTF2WEdrUWxIaVhrZm90UUdtMTUrVUVRM09laVhCcG83c2lvQVYxM0FQYi9Dd0gvRTlvb1l4UHZBVk03T1BHb3ZZOCtrclc3dkpYcUZJblBVMDBHZ1puSmRqMWZxNmtqWnF0ZVo4TFhOdnRZeTEvNDJudWxGa3d5ekpuTnByb3R3PT01&file=District+31+S02E15+WEBRiP+720p+x264.torrent [Status: 200]
```
Here is what it is now... There is no extension anymore which brakes the fix 
```
SNATCHQUEUE-MANUALSNATCH-265625 :: [364be02] Downloading Memoires.Vives.S05E22.WEBRiP.720p.x264 from ETHOR at http://192.168.13.198:8086/jackett/dl/ethor/?jackett_apikey=**********&path=bWtnTURVT0h6OXNqUjlyb0RiK0MyMUwrdndLMVlpdzFibjBVTUI5b3pQL0VwMkErU1p1WU5WZHdSVTk3U0lNY0VOSkUrYXR4MnVGTTFscWpmWTdyTHhwbUR1a3hmUVNJUmJtM0IweFBoYnFKWWc3aEs4YkFjdllmM3hERlhobzBsZ0FPZXJQVFlHUWZubFA1SWJldmh2V1lOcTdBNnlMWTM5VlRlZ3MwR1lvcHZ0eWJrdVExRUJyMlZZVXJWSVh3eEVuRGk3S0lJZEVlMjI1VDZLaXJyNmI0QnY2VVd5UW53aWRQU0o5U1pUbkkrQzJneHpGbWJIUnphOFltemxlbzhCbndoWEFjbklOU05iUjlkcVpDWHVKYjJnM1Y3WEFjbmI0Q285a3c5ZnZaSDJCQko3WU1FUEVieis0Y1c5T3pWamVyQzVFZk5QOW5uZXNPc1RYYkRRPT01&file=Memoires+Vives+S05E22+WEBRiP+720p+x264
```

**Comment by maxcore** [comment]
I downgrade my jackett ...

**Comment by saitoh183** [comment]
How do I downgrade a docker image

**Comment by saitoh183** [comment]
@maxcore 

The issue is not with sickrage or Medusa im guessing since it only started after i updated as well. Lets hope this can be fix soon cuz i hate having to stop updates.

**Comment by maxcore** [comment]
Yes i know but i have no problem with sonarr ... the sickrage tornzab section was poor  i think sickrage need better config and dedicate to tornzab

**Comment by maxcore** [comment]
@saitoh183 

<img width="890" alt="capture d ecran 2017-11-23 14 00 36" src="https://user-images.githubusercontent.com/4043787/33186327-b3969c18-d056-11e7-878b-4da0c4532571.png">

put this in this line

**Comment by saitoh183** [comment]
do i need to turn off auto updates?

**Comment by maxcore** [comment]
yes i forget to mention turn off in jackett

**Comment by saitoh183** [comment]
Thanks..hope someone fixes it soon

**Comment by maxcore** [comment]
Yes me too

**Comment by ERR1R** [comment]
Yep, got this problem ass well!

**Comment by saitoh183** [comment]
@garfield69 

Any news on this issue?

**Comment by garfield69** [comment]
Not my field of expertise, I just noted the other duplicate ticket. None of the c# specialists have picked this up so far, I'm guessing they have other demands on their time at the moment.

**Comment by saitoh183** [comment]
@garfield69 ah ok,np...i hope it can be fixed soon cuz now im stuck on this old version and with Xthor url change i cant use it with this version

**Comment by garfield69** [comment]
@saitoh183  regarding the xthor url change:
You should be able to fix this by using the wrench icon on your Jackett Dashboard to edit the Xthor definition's Site Link to `https://xthor.to/`
![image](https://user-images.githubusercontent.com/6933240/33457516-93bc7dfe-d687-11e7-911a-e230a641483e.png)

**Comment by maxcore** [comment]
@garfield69 nop still not working
@saitoh183  check this one : https://github.com/SickRage/SickRage/issues/4132

**Comment by garfield69** [comment]
@maxcore  sorry whats not working?

**Comment by saitoh183** [comment]
@garfield69 

Tried that and the test button fails

@maxcore is there a solution in that link? Also i use Medusa not sickrage but if there is a fix there, maybe i can apply it to Medusa.

**Comment by garfield69** [comment]
@saitoh183  @maxcore  My bad. Sorry. I took a look at the code and I see that the Xthor definition code has several hard coded URL references, so changing the SiteLink on the Jackett Dashboard does not work for this indexer.  Version v0.8.469 contains the c# fix which of course is no use to you at the moment if you cannot upgrade.

**Comment by saitoh183** [comment]
@maxcore 

Medusa is fixed now i dont know if the fix will apply exactly the same as sickrage but it might.

**Comment by maxcore** [comment]
Thx ! I will check it 😀

**Comment by maxcore** [comment]
@saitoh183 when Medusa will push to master i will switch to Medusa i love all new features !

**Comment by saitoh183** [comment]
I'm on dev version

**Comment by flightlevel** [comment]
Closing as @saitoh183 has found its now fixed in Medusa

**Comment by maxcore** [comment]
@saitoh183 what is the trick to switch on dev with unraid ??
