### ISSUE TITLE
Danishbits error

### ISSUE THREAD

**Issue by supremacy2k** [Jackett/Jackett#2183]
An error occured while testing this indexer
Exception (danishbits): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Error while parsing json:
301 Moved Permanently

**Comment by garfield69** [comment]
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.

**Comment by supremacy2k** [comment]
Sorry about the delay.

[Enhanced Logs](https://pastebin.com/uJC0Wyfa)

**Comment by kaso17** [comment]
just change the URL in the indexer config from http to https.
Will be fixed automatically via eed9745c67c9efd726667bd3429d16be5fda3a9a with the next release.

**Comment by supremacy2k** [comment]
Thanks! :D
