### ISSUE TITLE
ETTV showing unrelated results

### ISSUE THREAD

**Issue by matmuilwijk** [Jackett/Jackett#2187]
While searching for a movie/tv -show ETTV shows unrelated results. The results are the same with searching by IMDB and by Title.

Jackett version:  0.8.450.0
Mono version (if not using Windows):  5.4.1.6
![2017-11-24 09_53_21-greenshot](https://user-images.githubusercontent.com/20720945/33202612-81849e58-d0fd-11e7-922f-baabaf88ad53.jpg)

[log.20171124.00000.txt](https://github.com/Jackett/Jackett/files/1501060/log.20171124.00000.txt)
[log.20171124.00001.txt](https://github.com/Jackett/Jackett/files/1501061/log.20171124.00001.txt)
[log.20171124.00002.txt](https://github.com/Jackett/Jackett/files/1501062/log.20171124.00002.txt)
[log.20171124.00003.txt](https://github.com/Jackett/Jackett/files/1501063/log.20171124.00003.txt)
[log.20171124.00004.txt](https://github.com/Jackett/Jackett/files/1501064/log.20171124.00004.txt)

-------------------------------

**Comment by matmuilwijk** [comment]
Noticed that I get the exact same results while searching for another movie....
![2017-11-24 10_04_54-greenshot](https://user-images.githubusercontent.com/20720945/33203036-061ebae4-d0ff-11e7-86f5-40a983104c17.jpg)

**Comment by silentmiles** [comment]
This is occurring for me too.

**Comment by garfield69** [comment]
It looks like ETTV's search engine has changed it's behaviour.     
Using the Chrome Browser to access the ETTV site's Advanced Search Engine, it appears that adding `+` in from of each keyword now no longer restricts the search results to only hits with *ALL* those keywords, it's behaving like an *OR* and not an *AND*.     
I will add the **andmatch** filter to the Jackett ETTV definition, which will filter results post-search.

**Comment by matmuilwijk** [comment]
Updated the definition manually, and now there are no ETTV results at all. (Yes, I've restarted the Jackett-service)

**Comment by garfield69** [comment]
I've removed the sort and pre-search keyword filters because they interfered with the andmatch.     
Tested on the Jackett Dashboard and with Sonarr.

**Comment by kaso17** [comment]
they fixed their search engine, restored old keywordfitlers via b8507c71b64b114def922364808cd81890053a77
