### ISSUE TITLE
Saving torrents as .nzb instead of .torrent

### ISSUE THREAD

**Issue by ERR1R** [Jackett/Jackett#2188]
It seems to be working like it should with this version: **Jackett Version 0.8.318.0**
I tried some others but they all failed.. 

Jackett version:  v0.8.450
Mono:  Mono JIT compiler version 4.6.2 (Stable 4.6.2.7)
Sickrage
Synology
-------------------------------

**Comment by garfield69** [comment]
Duplicate of #2182
