### ISSUE TITLE
[Tehconnection Provider] stops working

### ISSUE THREAD

**Issue by duramato** [Jackett/Jackett#219]
Every so ofen , like everyday, tehconnection stops working
and returns 
```
{
  "results": [],
  "total_results": 0
}
```
for every result , and the only way starts working again is by readding it to jackett.
Also if i try the test button it just says `Test failed for tehconnection: Found no results while trying to browse this tracker`

**Comment by Azerelat** [comment]
Perhaps your ip is changing?

**Comment by duramato** [comment]
No, its on a VPS with a dedicated ip

**Comment by flightlevel** [comment]
@duramato Latest release might fix this issue

**Comment by flightlevel** [comment]
Try deleting the indexer first and then re-add after updating to latest

**Comment by duramato** [comment]
That seems to have fixed it , thanks! :+1:
