### ISSUE TITLE
Tracker YTS is not working

### ISSUE THREAD

**Issue by matmuilwijk** [Jackett/Jackett#2190]
[yts] Exception (yts): Error reading JObject from JsonReader. Path '', line 0, position 0.: Parse error (Test)

YTS website is working, and torrents can be grabbed from there. Just not through Jackett.

Jackett version: 0.8.450.0
Mono version: 5.4.1.6

**Comment by garfield69** [comment]
You can fix this for yourself right now by using the wrench icon on the Jackett Dashboard and editing the YTS definition's  Site link and Url link, and replace the suffix of `.ag` with `.am`
![image](https://user-images.githubusercontent.com/6933240/33235891-585cd958-d2a8-11e7-948f-364ba54fec09.png)
