### ISSUE TITLE
[HD4Free] Search returning only part of title

### ISSUE THREAD

**Issue by jstever** [Jackett/Jackett#2192]
I have been having issues with Jackett searching HD4Free.xyz.  When you search for a Movie by IMDB, it returns the available torrents, however the name only pulls the year.  See attached screenshot showing a search for Atomic Blonde by IMDB.  You'll see it only returns "(2017)" as the name.  The same happens when I try to search by name, it only returns a result if I search "(2017)".

This only seems to be an issue on HD4Free.  Other trackers I use work fine.

Jackett version:  0.8.450.0

<img width="1226" alt="screen shot 2017-11-26 at 2 09 52 am" src="https://user-images.githubusercontent.com/11879948/33238273-083ddd80-d250-11e7-8081-770fd73d4e3c.png">

-------------------------------

**Comment by kaso17** [comment]
works fine for me, please share an enhanced log

**Comment by jstever** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/1525611/log.txt)
Logs attached

**Comment by kaso17** [comment]
the log only contains requests for morethantv, please provide one for hd4free

**Comment by jstever** [comment]
Sorry about that. I ran a few searches on HD4Free before pulling this log. 
[log.txt](https://github.com/Jackett/Jackett/files/1529462/log.txt)

**Comment by jstever** [comment]
I've attached another with a few more searches.  Thanks for your help.
[log.txt](https://github.com/Jackett/Jackett/files/1529477/log.txt)

**Comment by kaso17** [comment]
ok, the name is already missing in the JSON returned by the server.
Is there anything special about your account? special rank/permissions?
What happens if you search for `tt2406566` directly on https://hd4free.xyz/browse.php?
Does it work?
If yet, please use the browser network debugger (F12) and post the "POST Data" for the request to the initial_recall10.php URL.

**Comment by Killswitch11** [comment]
HD4Free has switched to use the same setup as Blutopia(https://github.com/Jackett/Jackett/issues/1348).

**Comment by jstever** [comment]
> HD4Free has switched to use the same setup as Blutopia(#1348).

I was able to add HD4FREE by using Blutopia and changing the site address.  Search is also working now too.

**Comment by kaso17** [comment]
fixed via 844d2ba1adf7880b533015a075f53fdf37fbbb2d
I assume the software change also fixed the initial issue, closing
