### ISSUE TITLE
Sometimes mono flips and uses 50-100% CPU until jackett is stopped

### ISSUE THREAD

**Issue by Redsandro** [Jackett/Jackett#2198]
Jackett version:  v0.8.450
Mono version:  5.4.0.201
Docker image: [docker-jackett](https://github.com/linuxserver/docker-jackett)

My computer was having issues. Upon inspection it turns out the temperature was near to 100 degrees Celsius. I've inspected sensor data and it started around the time I did a whole bunch of jackett searches.

I restarted jackett, and temperatures went back to normal. Then after some time mono flipped again. You can clearly see the temperature raise:

![image](https://user-images.githubusercontent.com/1702193/33285388-6ef64d10-d3b2-11e7-9bfe-e5496a405710.png)

There were three `mono` processes running, two of them stuck racing between 50% and 100% CPU load. They stop and everything goes back to normal when Jackett is restarted.

I have no idea what causes this, and it doesn't happen frequently.

While I'm typing this and doing some searches in another tab, I see that this issue was reported here as well: https://github.com/linuxserver/docker-jackett/issues/34

**Comment by kaso17** [comment]
If it happens again please provide the jackett log during the high CPU load time.
Is this a standard x86_64 platform or some embedded system?

**Comment by paulo17** [comment]
I got the same things twice. I had to stop the container and start again to fix the issue.

**Comment by Redsandro** [comment]
@kaso17 in my case Intel Xeon Debian x86_64.

Any specific settings I need to enable to get a satisfactory log when this happens again?

**Comment by kaso17** [comment]
preferably with enhanced logging enabled (-t CLI option)

**Comment by supremacy2k** [comment]
My docker image seems to do the same.
And it seems to happen whenever a tracker crashes (going from working to failed status)
Can't provide logs as it's been a while since one of my trackers crashed.

But it least it's a place to start looking.

**Comment by pkoenig10** [comment]
I'm seeing the same thing on my server using the docker image.

My CPU usage is shown below. Red is jackett and green is docker itself (ignoring the short spike around 02:15). Clearly nothing else is using CPU so the docker CPU usage is due to jackett.

Jackett logs during that time are [here](https://gist.github.com/anonymous/7b27b75709782bad222a6c8056620096).

![image](https://user-images.githubusercontent.com/5273164/33977956-507ef614-e052-11e7-9e0c-a61e5afb5936.png)

**Comment by Quiksmage** [comment]
I had a similar issue and it was due to leaving auto-update on. Make sure that's turned off.

**Comment by kaso17** [comment]
@Quiksmage is right, if you're using docker and an update comes in it might cause these symptoms.

**Comment by pkoenig10** [comment]
Disable auto-update seemed to resolve the problem for me.

**Comment by kaso17** [comment]
Starting with version v0.8.676 jackett has a new command line option `--NoUpdates` which will prevent any kind of self updates.

**Comment by andycarver101** [comment]
Mono spiking in OSX, Checked disable auto update. Lets see who it goes...

**Comment by kaso17** [comment]
@andycarver101 another common cause of high CPU usage is the use of socks proxy, is that the case for you?

**Comment by deakster** [comment]
@kaso17 I have been noticing high CPU usage until restart since I configured the use of a socks proxy in Jackett. So yes, I think it is related.

**Comment by xboxhacks** [comment]
Same here, SOCKS 5 proxy has made my cpu usage hit over 70% on my synology nas
