### ISSUE TITLE
[REQ] Libertalia.me

### ISSUE THREAD

**Issue by maxcore** [Jackett/Jackett#22]
I have invitation for developper if need it !

**Comment by raspdealer** [comment]
You can invite jackettapp at gmail

**Comment by maxcore** [comment]
@raspdealer 
check your email

**Comment by raspdealer** [comment]
@flightlevel

**Comment by flightlevel** [comment]
Have joined, will look at when have some spare time

**Comment by flightlevel** [comment]
Category mapping https://github.com/Jackett/Jackett/issues/95#issue-118475360

**Comment by itdaboyz** [comment]
Libertalia closed definitely... You can close this request.
