### ISSUE TITLE
Feature request: YTS

### ISSUE THREAD

**Issue by matmuilwijk** [Jackett/Jackett#2200]
Small feature request regarding the YTS indexer. 

Would it be possible to add 'BRRip' to the returned result? All releases on YTS are BRRips, but the API returns only 'Film title (year) 720p', and Radarr sees the release as HDTV720p/HDTV1080p and not as the BRRip that they are. :)

**Comment by kaso17** [comment]
done via 570553f7d600abf8db2cf631fe0cdeb25e483fa5
