### ISSUE TITLE
[kickasstorrent] Exception (kickasstorrent): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.64.119.34:443: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by weezzelboy** [Jackett/Jackett#2207]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
katcr.co site is down.
![image](https://user-images.githubusercontent.com/6933240/33412824-c0719874-d5f2-11e7-8cf9-17ead695e228.png)
This [Reddit post](https://www.reddit.com/r/kickasstorrents/comments/7gbuto/kat_is_presently_down/dqiz2kn/) explains:
>The reason KATCR.CO is currently offline is due to an issue with our hosting provider.

Nothing to do but wait.
