### ISSUE TITLE
[xthor] An error occurred while sending the request: Error: NameResolutionFailure (Config)

### ISSUE THREAD

**Issue by CamilleTh** [Jackett/Jackett#2209]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
You should be able to fix this by using the wrench icon on your Jackett Dashboard to edit the Xthor definition's Site Link to `https://xthor.to/`
![image](https://user-images.githubusercontent.com/6933240/33457516-93bc7dfe-d687-11e7-911a-e230a641483e.png)

**Comment by garfield69** [comment]
Apologies. My previous advice is incorrect. To fix this you will first need to upgrade to at least v0.8.469, after which you can manually update the SiteLink if it has not been updated automatically.
