### ISSUE TITLE
[REQ] ripstracker.com

### ISSUE THREAD

**Issue by aaseef021** [Jackett/Jackett#2210]
Hi I am trying to add a custom indexer that does not exist in Jackett

http://ripstracker.com

How can I add the above?

**Comment by garfield69** [comment]
>How can I add the above?     

By creating a definition. :grin:     
All you need is a little knowledge about HTML and CSS selectors.      

You will find details on the yaml indexer definition format at the following wiki https://github.com/Jackett/Jackett/wiki/Definition-format .
And you can take a look at the existing definitions in https://github.com/Jackett/Jackett/tree/master/src/Jackett.Common/Definitions for examples.
If you get stuck feel free to ask for help :+1:

**Comment by aaseef021** [comment]
Hi would i be able to take a exist definisiton format and edit it. After I do that, how do import it into Jackett.  Is there is tool to test it to verify i get a sucessful test?

**Comment by kaso17** [comment]
Check the Jackett output during startup, there you'll see where it looks for the definitions.

If there's a syntax error it will be printed during startup too.

Make sure to run jackett with the -t option to get more debug output.
Then just start configuring your indexerand run test searches until it works as expected. On the log/console output you'll see any errors.

**Comment by aaseef021** [comment]
Sorry not understanding how to import the indexer into Jackett

I do not have any experience with HTML or CSS so will try my best. but may require assistance. I do not mind paying for teaching me.

**Comment by kaso17** [comment]
Please manually start jackett from the console and post the output.

**Comment by aaseef021** [comment]
Hi I copied one of the definition, can you verify if it looks good, it is for RipsTracker.com. Also how do I imported it into Jackett to add as a indexer

**Comment by garfield69** [comment]
@aaseef021 I am going to give you an example of the process that I use, based on the windows platform which has had Jackett installed as a service. If this does not match your situation and you cannot work out how to adapt the example for your platform let us know.     
 
-  so you cloned an existing definition and saved it as ripstracker.yml in the same folder you found the other definitions,  and you altered its code to suit your tracker's requirements.
- so to test it, first shut down the Jackett service.
- open a windows cmd shell with admin priviledges
- and start the jackettconsole with the enhanced logging enabled `jackettconsole -t -l`
- check the log to see if you passed the syntax check (i.e. that there are no errors against your definition during the jackettconsole startup
- open your chrome browser and access the Jackett Dashboard 
-  use the *Add Indexer* button, locate your ripstracker indexer and add it to your active list
- test the indexer
- if it does not work as you expect, then shutdown the jackettconsole and look at the log for errors and try to resolve the issue.
- rinse and repeat until you get it right.

If you want us to look at your definition then post it here. If you have an error you cant figure out how to resolve then post the full log here.

**Comment by garfield69** [comment]
unfortunately this site cannot be processed by the Cardigann yaml processor as the search query needs to include a securitytoken which Cardigann cannot fetch.
this indexer will need to be written in C#

**Comment by garfield69** [comment]
closing as stale.
