### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login Failed, got redirected: Parse error (Test)

### ISSUE THREAD

**Issue by florian-perez** [Jackett/Jackett#2211]
Failed testing tracker YggTorrent since this day (01/12/2017). It seems they changed the tracker URL about this time (from https://yggtorrent.com to https://ww1.yggtorrent.com). It used to work perfectly fine. Below are the logs :

When | Level | Message
-- | -- | --
Dec 01, 2017 03:36:43 AM | Error | {0}
Dec 01, 2017 03:36:43 AM | Error | Error on 20171201033643 for YGGtorrent.txtJackett.ExceptionWithConfigData: Login Failed, got redirected   at Jackett.Indexers.CardigannIndexer+<TestLogin>d__16.MoveNext () [0x000db] in <591ed7f10ff1476caa9cdbf49059c036>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a8460a77e67a430a8486a9751162e5f4>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <a8460a77e67a430a8486a9751162e5f4>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <a8460a77e67a430a8486a9751162e5f4>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <a8460a77e67a430a8486a9751162e5f4>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <a8460a77e67a430a8486a9751162e5f4>:0    at Jackett.Indexers.CardigannIndexer+<PerformQuery>d__25.MoveNext () [0x00969] in <591ed7f10ff1476caa9cdbf49059c036>:0
Dec 01, 2017 03:36:42 AM | Info | CardigannIndexer (yggtorrent): Relogin required

Jackett version:  0.8.469.0

-------------------------------

**Comment by garfield69** [comment]
Thanks for reporting. Fixed by 57aa438e6408833b035e86e7fbfa761d4b832d3c, which should be included in the next (pre-)release, whenever that happens.

**Comment by kaso17** [comment]
update v0.8.479 contains the fix

**Comment by kaso17** [comment]
v0.8.486 contains another YGG fix

**Comment by darkpisto** [comment]
Fixed in v0.8.486  thanks you ! :)
