### ISSUE TITLE
[yggtorrent] Login failed: Selector

### ISSUE THREAD

**Issue by PastaGringo** [Jackett/Jackett#2215]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version: **5.4.1.6 (tarball Wed Nov  8 20:35:02 UTC 2017)**
Mono version (if not using Windows):  

-------------------------------

Hello, 
They changed the website URL to https://ww1.yggtorrent.com.

I have this error message : _Login failed: Selector "a[href="https://yggtorrent.com/user/logout"]" didn't match_

Log content : 

2017-12-01 14:25:01.3678 Error Jackett.ExceptionWithConfigData: Login failed: Selector "a[href="https://yggtorrent.com/user/logout"]" didn't match
  at System.Web.Http.Controllers.ExceptionFilterResult+<ExecuteAsync>d__0.MoveNext () [0x00097] in <f99f496cb0d249c1a945c1fcabce1695>:0  Jackett.ExceptionWithConfigData: Login
 failed: Selector "a[href="https://yggtorrent.com/user/logout"]" didn't match

Thanks 👍

**Comment by kaso17** [comment]
dupe #2211
