### ISSUE TITLE
[BUG] Link in torznab XML feed is not properly escaped

### ISSUE THREAD

**Issue by phendryx** [Jackett/Jackett#222]
In the given example, the link is not properly escaped. 

```
    <item>
      <title>J K Rowling - Harry Potter and the Half-Blood Prince 2012 Retail EPUB eBook-BitBook</title>
      <guid>[removed]</guid>
      <comments>[removed]</comments>
      <pubDate>Sat, 23 Jun 2012 18:26:59 -0400</pubDate>
      <size>1003520</size>
      <description>J K Rowling - Harry Potter and the Half-Blood Prince 2012 Retail EPUB eBook-BitBook</description>
      <link>http://192.168.111.12:9117/dl/iptorrents/[removed]?path=aHR0cHM6Ly9pcHRvcnJlbnRzLmNvbS9kb3dubG9hZC5waHAvNjU1NTE0L0ouSy5Sb3dsaW5nLi0uSGFycnkuUG90dGVyLmFuZC50aGUuSGFsZi1CbG9vZC5QcmluY2UuMjAxMi5SZXRhaWwuRVBVQi5lQm9vay1CaXRCb29rLnRvcnJlbnQ1&amp;file=J K Rowling - Harry Potter and the Half-Blood Prince 2012 Retail EPUB eBook-BitBook.torrent</link>
      <category>8000</category>
      <enclosure url="http://192.168.111.12:9117/dl/iptorrents/[removed]?path=aHR0cHM6Ly9pcHRvcnJlbnRzLmNvbS9kb3dubG9hZC5waHAvNjU1NTE0L0ouSy5Sb3dsaW5nLi0uSGFycnkuUG90dGVyLmFuZC50aGUuSGFsZi1CbG9vZC5QcmluY2UuMjAxMi5SZXRhaWwuRVBVQi5lQm9vay1CaXRCb29rLnRvcnJlbnQ1&amp;file=J K Rowling - Harry Potter and the Half-Blood Prince 2012 Retail EPUB eBook-BitBook.torrent" length="1003520" type="application/x-bittorrent" />
      <torznab:attr name="seeders" value="7" />
      <torznab:attr name="peers" value="7" />
    </item>
```

The & has been encoded to `&amp;` but spaces have not been converted to %20. If I manually test and change `&amp;` to `&` and replace spaces with %20, the url is valid and downloads as expected. Sonarr doesn't seem to care or perhaps finds another link that is properly formatted. I am trying to use Jackett with LazyLibrarian and in cases like the one above, it fails because it's assuming the url is properly formatted.

Is this something that can be addressed in Jackett or will cleaning up the url actually break Sonarr? I'm   wanting to submit a fix to either Jackett or LazyLibrarian to take care of the issue but I'm not sure which side is actually broken (malformed url vs url sanitization).

**Comment by flightlevel** [comment]
@phendryx Can you give latest release a try and report back

**Comment by phendryx** [comment]
@flightlevel Works! Thank you on the quick turn around!
