### ISSUE TITLE
"blackhole"ing a file works (JSON: success), but "downloading" fails (404) [torrentnetwork]

### ISSUE THREAD

**Issue by jackett0r** [Jackett/Jackett#2224]
When I try to use torrentnetwork I cant use the "download" ( /dl/ ) feature. Blackholing ( /bh/ ) the same file gives me a JSON "success" response and the file is downloaded to the blackhole directory. But wenn I try to download that file locally, I get a 404.

Maybe its because of this:

> 
> 2017-12-02 15:23:53.8831 Error Error downloading torrentnetwork https://tntracker.org/sdownload
> /1318462/ BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
>   at BencodeNET.Parsing.BencodeParser.Parse (BencodeNET.IO.BencodeStream stream) [0x0008f] in <8cfe090dffe84883b8ffe55488a96c94>:0 
>   at BencodeNET.Parsing.BencodeParser.Parse (System.IO.Stream stream) [0x00008] in <8cfe090dffe84883b8ffe55488a96c94>:0 
>   at BencodeNET.Parsing.BencodeParser.Parse (System.Byte[] bytes) [0x00007] in <8cfe090dffe84883b8ffe55488a96c94>:0 
>   at Jackett.Controllers.DownloadController+<Download>d__5.MoveNext () [0x001ab] in <64979c5b464a4a74b7d2629a3f2f7541>:0

full logs attached.

System:
[log.txt](https://github.com/Jackett/Jackett/files/1523875/log.txt)
Ubuntu 16.04.

Mono version:
`Mono JIT compiler version 5.4.1.6 (tarball Wed Nov  8 20:35:02 UTC 2017)`

**Comment by kaso17** [comment]
re-configuring the indexer should fix it
fixed via d49cb02d2f2c089b818a66f6efb5060819c68946
