### ISSUE TITLE
[ptfiles] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by g82858** [Jackett/Jackett#2225]
Jackett version:  0.8.486.0
Mono version (if not using Windows):  5.4.1.6 

Running latest linuxserver/jackett Docker container.

Enhanced Log: https://pastebin.com/VEVU3AE0
Manual Search Log: https://pastebin.com/33ZLCag1

**Comment by kaso17** [comment]
it looks like you've an extra column (the third one). What is it?
Please share a complete enhanced log (the lines before the errors containg the full HTML code of the request).

**Comment by g82858** [comment]
ptfiles test log: https://pastebin.com/EcFCvvR2
ptfiles Manual Search for "batman" log:  https://pastebin.com/rW3QkkRK

**Comment by kaso17** [comment]
fixed via 105bd85441ddbf576445ee66fed829f42b39a5ce
