### ISSUE TITLE
Unable to parse episodes from release name. But name seems good.

### ISSUE THREAD

**Issue by falkin** [Jackett/Jackett#2228]
Jackett version: 0.8.486.0
Mono version: 5.2.0.215

![image](https://user-images.githubusercontent.com/1089835/33522170-145b3626-d7e6-11e7-96d0-306025a0992b.png)

![image](https://user-images.githubusercontent.com/1089835/33522187-43f49882-d7e6-11e7-9243-fdbf491deaaa.png)

What's wrong with name on torrent9 and GkTorrent ?

**Comment by kaso17** [comment]
check the sonarr logs to see what's wrong with it.

**Comment by flightlevel** [comment]
@falkin 
Going to close this as its a question for Sonarr
Jackett is supplying the information it sourced from the tracker, Sonarr parses the release names as entered on the tracker

However... I think you're being unreasonable expecting Sonarr to be able to handle this poor naming
The successful matches all make it clear in their naming that 117 is the episode number, whereas the two that failed simply have 'Dragon Ball Super 117'
How do you know that 117 is the episode, how do you know its not part of the title, many shows have numbers in their titles
eg.
The 100
Beverley Hills 90210
Babylon 5
24

and what about
Dragon Ball Super 1
Dragon Ball Super 2
is that episode, season ????

**Comment by falkin** [comment]
Ok the for answering, now it's clear :)
