### ISSUE TITLE
[eztv] Exception (eztv): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /build/mono-5.4.1.6/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by Troussdesoin** [Jackett/Jackett#2229]
Jackett version:  Most up to date linuxserver.io DOCKER
Mono version (if not using Windows):  No idea, it's a docker

Hi there, I've got a problem, i run jackett in a docker and none of the tracker actually work. And by that i mean every test i do fails. 

I've spent a few hours on the github to find some explanation but none of them actually applied to the docker version and tbh, most of them had as a solution to install jackett as a docker.

-------------------------------
Edit: I am using Smart Dns Proxy by the way. Which is a dns server. I don't know if it can have an impact and how to handle it.

**Comment by kaso17** [comment]
please open a shell in the docker and run this command and post the output:
`wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`

**Comment by Troussdesoin** [comment]
here's the output :

root@UnraidChoupi:~# wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin
-bash: cert-sync: command not found
--2017-12-03 17:35:59--  https://curl.haxx.se/ca/cacert.pem
Resolving curl.haxx.se (curl.haxx.se)... 151.101.82.49, 2a04:4e42:13::561
Connecting to curl.haxx.se (curl.haxx.se)|151.101.82.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 236061 (231K) [application/x-pem-file]
Saving to: ‘STDOUT’

-                     0%[                    ]       0  --.-KB/s    in 0s      


Cannot write to ‘-’ (Success).

**Comment by kaso17** [comment]
What was the problem?
