### ISSUE TITLE
Jackett doesn't start on Debian (ARM)

### ISSUE THREAD

**Issue by monsieurpouet** [Jackett/Jackett#2230]
Hi Jackett Users !

My Jackett installation doesn't work :/
With the latest version (0.8.489) on my ReadyNas (debian arm) with Mono 5.2.0.215.

When I start Jackett, i've this log:

```
Dec 03 19:00:12 nastheo mono[8491]: [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its depend
encies.
Dec 03 19:00:12 nas mono[8491]: File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
Dec 03 19:00:12 nas mono[8491]:   at CommandLine.Core.ReflectionExtensions.IsMutable (System.Type type) [0x00031] in <c500474b04314b778910cf182873b214>:0
Dec 03 19:00:12 nas mono[8491]:   at CommandLine.Parser.ParseArguments[T] (System.Collections.Generic.IEnumerable`1[T] args) [0x0000e] in <c500474b04314b778910cf182873b214>:0
Dec 03 19:00:12 nas mono[8491]:   at JackettConsole.Program.Main (System.String[] args) [0x0000c] in <581f93235e9745e2995cd5c0902be09b>:0
Dec 03 19:00:12 nas systemd[1]: jackett.service: Main process exited, code=exited, status=1/FAILURE
Dec 03 19:00:12 nas systemd[1]: jackett.service: Unit entered failed state.
Dec 03 19:00:12 nas systemd[1]: jackett.service: Failed with result 'exit-code'.

```
My command to launch: 
` ExecStart=/usr/bin/mono --debug /data/.apps/Jackett/JackettConsole.exe`

Did you have the issue ?

**Comment by kaso17** [comment]
is the mono-devel package installed?

**Comment by nova-techies** [comment]
> Is the mono-devel package installed?

Just FYI this also fixes the install issue on Debian Stretch on x86_64.

**Comment by monsieurpouet** [comment]
F**k, the notification doesn't work.. 
Yes mono-devel is installed!

**Comment by kaso17** [comment]
Can you please try upgrading to mono 5.4 from http://www.mono-project.com/download/#download-lin-debian?

**Comment by monsieurpouet** [comment]
Hummm, my mono-devel package is broken.
I had install mono-devel package.

`The following packages have unmet dependencies:
 mono-devel : Depends: libc6 (>= 2.24) or
                       libc6.1 (>= 2.24) but it is not installable or
                       libc0.1 (>= 2.24) but it is not installable`

Dependencies problem I guess..

**Comment by kaso17** [comment]
Which debian version is running on the NAS and which repository did you install?

**Comment by monsieurpouet** [comment]
Debian 8.9 on ARM
I use the repository of strech from the mono website:
http://www.mono-project.com/download/#download-lin-debian

**Comment by kaso17** [comment]
8.9 < 9
use the debian 8 /jessi repo

**Comment by monsieurpouet** [comment]
I'll gonna try it !!
