### ISSUE TITLE
[cpasbien] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Echupk** [Jackett/Jackett#2231]
Jackett Version 0.8.489.0
Mono version (if not using Windows):  4.6.2.7-8

-------------------------------

Seems like cpasbien change their URL again.

Jackett: cpasbien.club
google: http://www.cpabien.cx/

(cpasbien.club redirecting to http://www.wawa-mania.xyz/)

Can you update please ? 

Regards

**Comment by kaso17** [comment]
cpabien.club isn't redirecting for me, it's just down.
wawa-mania looks like a different tracker
http://www.cpabien.cx/ is this a fake?

**Comment by garfield69** [comment]
Opentrackers.org seem to think www.cpabien.cx is legit, it's an alternate for cpabien.club that has been around for some time it seems.
Using the Chrome Browser directly, I also am getting cpabien.club reported by CloudFlair as being down, but www.cpabien.cx works fine for me.
However, with Jackett, having swapped out the sitelink of cpasbien to `http://www.cpabien.cx/` in the cpasbien definition, I am seeing redirection 302, but to the same address, Cloudflair again?
log
```
Dec 05, 2017 07:52:48 AM | Debug | Saving new config file: C:\ProgramData\Jackett\Indexers\cpasbien.json.133c3ce3d3ed4127bcb1e5bd7e92dc5a.tmp
Dec 05, 2017 07:52:48 AM | Info | CardigannIndexer (cpasbien): Relogin required
Dec 05, 2017 07:52:48 AM | Debug | WebClient(HttpWebClient).GetString(Url:http://www.cpabien.cx/search.php?t=cruel)
Dec 05, 2017 07:52:48 AM | Debug | WebClient(HttpWebClient): Returning Redirect => http://www.cpabien.cx/
Dec 05, 2017 07:52:48 AM | Info | Manual search for "cruel" on cpasbien with 0 results.
```

**Comment by garfield69** [comment]
Oh, I see now. The site at the .cx address is using different html from .club so the Jackett definition does not match.
Should I re-code the cpasbien definition for the new .cx site or wait a few days to see of .club comes back?

**Comment by kaso17** [comment]
if it's legit I suggest to adjust the definition
