### ISSUE TITLE
[hdtorrentsit] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by memnos** [Jackett/Jackett#2235]
When test this tracker i have error
Here is the log:
https://paste2.org/gBc4I0M6

Jackett version:  0.8.489.0
Mono version (if not using Windows):  Mono JIT compiler version 5.4.1.6 

-------------------------------

**Comment by kaso17** [comment]
It returns error 404 which most likely means your IP is geo blocked
