### ISSUE TITLE
[cpasbien] Exception (cpasbien): Request to http://cpabien.club/search.php?t= failed (Error 522) - The tracker seems to be down.: Request to http://cpabien.club/search.php?t= failed (Error 522) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by Kenoux** [Jackett/Jackett#2239]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
If you upgrade to Jackett v0.8.496 you should be able to connect to the replacement site

**Comment by Kenoux** [comment]
Thanks

**Comment by Kenoux** [comment]
Hi,

I've checked and it's working !

Thanks for your help Garfield69
