### ISSUE TITLE
How update

### ISSUE THREAD

**Issue by lilp69** [Jackett/Jackett#2240]
Hi I follow link to install jackett on debian 9.0 : https://www.htpcguides.com/install-jackett-ubuntu-15-x-for-custom-torrents-in-sonarr/

But I want to know how update Jackett? 
I download new version by wget, I untar .tar.gz in Jackett folder, and restart systemctl. But I've still have old version : 0.8.402.0

Auto update don't work :+1: 

Starting web server at http://*:9117/
--
Dec 06, 2017 05:02:47 PM | Info | Deleting JackettUpdate temp files from /tmp/JackettUpdate-v0.8.496-636481729606497290
Dec 06, 2017 05:02:47 PM | Info | Adding aggregate indexer

**Comment by kaso17** [comment]
Make sure the jacket user has write permissions for the complete Jackett directory.
If it still doesn't work check the updater log:
~/.config/Jackett/updater.txt

**Comment by lilp69** [comment]
My put 777 permission to Jackett folder and I my user in root group which is in systemctl\system\jackett.service.

How auto update?

**Comment by kaso17** [comment]
~/.config/Jackett/updater.txt doesn't exist?
Is you systemd service using restart=always?
If it is add  --NoRestart to the ExecStart lines
Please have a look at the this wiki article for systemd best practice:
https://github.com/Jackett/Jackett/wiki/systemd-service

Please also check the jounrlal for possible hints regarding the update failure:
`journalctl -fa -n 5000 -u jackett`

**Comment by lilp69** [comment]
updater.txt exist.
I add --NoRestart to the system script and I've can make the update
Thks
