### ISSUE TITLE
[1337x] Exception (1337x): Error: NameResolutionFailure: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by gustavogarciagithub** [Jackett/Jackett#2241]
I can't seem to get any public indexers working. All of them give out an error when I try to test them and also when I try to add them to Sonarr.

I'm running on a QNAP 219p+ with:
 QTS 4.3.3
 Mono 5.4.1.6.0
 Qsonarr 2.0.0.50.54
 Radarr 0.2.0.182
 Jackett 0.8.402.0

Thanks for any help.

-------------------------------

**Comment by kaso17** [comment]
check the log, looks like a DNS issue

**Comment by gustavogarciagithub** [comment]
Hi.

Thanks for the reply but I can't figure out why it should happen. I look at the log and it seems to me the problem occurs when the IWebClient.GetString method is invoked and then the ApiController encounters an error.
The DNS appears to be working ok (I am using Google's ones for the moment) as I can access the net, add torrents manually and download them correctly, etc.
I attach the Log just in case you could take a peek at it and point me in a possible solution direction.
Thank you!

[JackettLog.xlsx](https://github.com/Jackett/Jackett/files/1539767/JackettLog.xlsx)
