### ISSUE TITLE
[yggtorrent] Login failed: Selector  "a[href$="user/logout"]" didn't match

### ISSUE THREAD

**Issue by s7relok** [Jackett/Jackett#2248]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  Jackett Version 0.8.496.0

Mono version (if not using Windows):  5.4.1.6

-------------------------------

When | Level | Message
-- | -- | --
Dec 07, 2017 11:02:09 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
Dec 07, 2017 11:02:09 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
Dec 07, 2017 11:02:09 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Dec 07, 2017 11:02:09 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
Dec 07, 2017 11:02:09 PM | Info | HttpActionBinding ExecuteBindingAsync
Dec 07, 2017 11:02:09 PM | Info | HttpActionBinding ExecuteBindingAsync
Dec 07, 2017 11:02:09 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Dec 07, 2017 11:02:09 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Dec 07, 2017 11:02:09 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
Dec 07, 2017 11:02:09 PM | Info | ApiControllerActionSelector SelectAction
Dec 07, 2017 11:02:09 PM | Info | ServerConfigurationController ExecuteAsync
Dec 07, 2017 11:02:09 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ServerConfigurationController
Dec 07, 2017 11:02:09 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ServerConfigurationController
Dec 07, 2017 11:02:09 PM | Info | DefaultHttpControllerActivator Create
Dec 07, 2017 11:02:09 PM | Info | HttpControllerDescriptor CreateController
Dec 07, 2017 11:02:09 PM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
Dec 07, 2017 11:02:09 PM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
Dec 07, 2017 11:02:09 PM | Info | http://192.168.4.2:9117/api/v2.0/server/logs?_=1512684100170

**Comment by garfield69** [comment]
The *Login Failed* message means that you did not enter the correct username and/or password when you configured the yggtorrent definition using your Jackett Dashboard.      

So,
1. try to login manually using your Chrome Browser directly at https://ww1.yggtorrent.com/user/login to double check your username/password is correct    
2. sort it out if it isn't,     
3. and then use the TrashBin icon on your Jackett Dashboard to delete the existing yggtorrent definition if it exists,    
4. and then add the yggtorrent indexer to your active list afresh with the correct username/password.

**Comment by drloser123** [comment]
I have the same problem, and I'm sure my login/password are corrects. (It was working fine a couple of days ago - not sure when the problem started)
