### ISSUE TITLE
[rodvd] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by VadVoci** [Jackett/Jackett#2249]
An error occured while updating this indexer RoDVD
Login Failed, got redirected

/usr/local/jackett/var/.config/Jackett/log.txt
https://pastebin.com/83100tdi

Jackett version:  Jackett Version 0.8.496.0 
Mono version :  mono-4.6.2  
synology 5.2.3 
synology_bromolow_3615xs

-------------------------------
Btw:
@kaso17 
I can send you an invitation if you do not have an account on rodvd anymore ..

**Comment by kaso17** [comment]
This is a normal log, please enable enhanced logging first.

**Comment by VadVoci** [comment]
An error occured while adding this indexer
Login Failed, got redirected

Enhanced logging:
https://pastebin.com/rfDxtuHF

**Comment by kaso17** [comment]
no idea what's wrong there. please send an invite to kaso1717 -at- gmail.com

**Comment by VadVoci** [comment]
@kaso17 RoDVD Invitation sent! 2017-12-11

**Comment by kaso17** [comment]
didn't get anything (already checked spam)

**Comment by VadVoci** [comment]
@kaso17 
I sent you an invitation code from my mail.  eg. free4 ....@... , "Vad Voci"

**Comment by kaso17** [comment]
It's working perfectly fine with my new account. Can you please try to remove the indexer, restart jackett, re-add the indexer?

**Comment by VadVoci** [comment]
I can not add the RoDVD indexer

An error occured while updating this indexer
Login Failed, got redirected

I give up finding a solution to rodvd ..

**Comment by kaso17** [comment]
This is probably caused by some incompatibility caused by the legacy libcurl webclient.
With an update to mono 5.4 the problem might disappear.
See this Syno issue: https://github.com/SynoCommunity/spksrc/issues/2808

**Comment by VadVoci** [comment]
I have to admit that I have the DSM version 5.2-5967. (And I can not update it)
I can not find mono 5.4 for me.

**Comment by alxlaxv** [comment]
Did you tried to ask directly on the synocommunity? 
https://github.com/SynoCommunity/spksrc

**Comment by kostass21** [comment]
i have problem too,is possible to have an invitation for log-in?
