### ISSUE TITLE
Windows URL ACL when AllowExternal=false

### ISSUE THREAD

**Issue by SystemOfSilence** [Jackett/Jackett#2250]
I think you are missing calls to netsh to register the URL on the system when AllowExternal=false in the configuration or some setup in the .net api. When AllowExternal is true Jacket runs great as long as urlACL entry exists, when AllowExternal is false Jacket never opens the port on the system. No errors are present in the Jacket log, Jacket console or system audit logs. I even increased the number of categories the audit log includes to no avail. It does work when run with administrative rights but I don't see urlACL entries even though in the source I see where netsh is called. Let me know what more information I can provide to help. This is not a show stopper bug but annoying. I wonder how many people are running as admin or local system unnecessarily as a result.

My Setup(we will call is special and probably not normal...):
Running on server 2012r2 with a dedicated user account that has had logon as batch/service granted and denied local/remote interactive logon.
JacketConsole.exe is ran via NSSM with stout/stderr redirected to text files rotated on startup.
Manual entries made to system urlACL for Jacket (http://*:port#/) and other apps as required(Ombi,Sonarr).

**Comment by kaso17** [comment]
I've no idea about this URL registration stuff on windows but the installer normally starts JackettCosole.exe with the `--ReserveUrls` option which should take care of it.

The resulting commands are these (AllowExternal=false)
```
netsh.exe http add urlacl http://127.0.0.1:9117/ sddl=D:(A;;GX;;;S-1-1-0)
netsh.exe http add urlacl http://localhost:9117/ sddl=D:(A;;GX;;;S-1-1-0)
```
or this (AllowExternal=true)
```
netsh.exe http add urlacl http://*:9117/ sddl=D:(A;;GX;;;S-1-1-0)
```
I assume changing between AllowExternal true/false without rerunning `JacketConsole.exe --ReserveUrls` might break it.

What's the best practice for this? Always register all 3 URLs? Only register http://*:9117/?

**Comment by alxlaxv** [comment]
@System99-Networks updates?

**Comment by garfield69** [comment]
Closed as stale.
