### ISSUE TITLE
[Feature Request] Key Words Filter

### ISSUE THREAD

**Issue by zero77** [Jackett/Jackett#2251]
Can you please add the option to filter include and exclude search results by key words.
Thanks

**Comment by kaso17** [comment]
I don't understand this request.
Can you please explain it a little bit further? Maybe an example?

**Comment by zero77** [comment]
Ok, hope this makes more sense.

For example, if you search for It (2017) there are also results for It Comes at Night (2017) so, using a key word exclude you could exclude words like at night or just night from the search results.

Or, if you wanted It Comes at Night (2017) instead of It (2017), you could include key words like at night or just night from the search results.

**Comment by kaso17** [comment]
Do you want to use this for jackett's manual search filter feature (client side filtering) or also want to use this via e.g. torznab?

**Comment by zero77** [comment]
Jackett's manual search

**Comment by kaso17** [comment]
Unfortunately the jquery datatable search feature doesn't support negative search keywords.
Otherwise it would be an easy addition.
Marking this one as enhancement.

**Comment by zero77** [comment]
What about doing a secondary search on the completed results once finished or on the fly.

For instance, either hiding everything that doesn’t contain a word or set of words, or only showing results that contain a word or set of words.

**Comment by kaso17** [comment]
I could implement it via the jQuery DataTable search box which is already present by using e.g. a "!" prefix to declare the exclusion of the following word. But the search engine doesn't support anything like this yet so it needs to be implemented either directly in the jquery lib or via some kind of hook/callback.

**Comment by zero77** [comment]
Instead of having a prefix in front of words that will be excluded.

Would it be quicker and easier to add another data table search box which, any of the content would automatically be excluded. 

Or would this method be more troublesome.

**Comment by kaso17** [comment]
To do the actual filtering you still have to hook the jquery search functions, extracting the keywords from the existing or a new box is the easy part.

**Comment by RoloSoze** [comment]
@garfield69 Isn't this achieved with #8048?

**Comment by garfield69** [comment]
yes.
