### ISSUE TITLE
Broken integration with Medusa

### ISSUE THREAD

**Issue by darkbroodzed** [Jackett/Jackett#2252]
Jackett version:  Version 0.8.485.0
Mono version (if not using Windows):  docker image lsioarmhf/jackett

Jackett send magnet link instead of torrent file and this is jackett bug according Medusa dev
https://github.com/pymedusa/Medusa/issues/3435#issuecomment-350291053

**Comment by kaso17** [comment]
See my post in https://github.com/pymedusa/Medusa/issues/3435#issuecomment-350317148
It's not a bug.

**Comment by darkbroodzed** [comment]
Thanks for answer and post in Medusa bug tracker.

On Dec 8, 2017 8:09 PM, "kaso17" <notifications@github.com> wrote:

Closed #2252 <https://github.com/Jackett/Jackett/issues/2252>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Jackett/Jackett/issues/2252#event-1379200262>, or mute
the thread
