### ISSUE TITLE
[torrentproject] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by ward0** [Jackett/Jackett#2254]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  Jackett Version 0.8.259.0
Mono version (if not using Windows):  4.6.2.7.8

-------------------------------

**Comment by garfield69** [comment]
torrentproject is gone. delete this definition from your active list using the trash-bin icon on your Jackett dashboard.
