### ISSUE TITLE
[yts] Exception (yts): Parse error: Parse error (Test)

### ISSUE THREAD

**Issue by ward0** [Jackett/Jackett#2259]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version: Jackett Version 0.8.259.0
Mono version (if not using Windows): 4.6.2.7.8

-------------------------------

**Comment by garfield69** [comment]
YTS changed domain 15 days ago. You need to upgrade to the latest Jackett v0.8.500 in order to pick up the updated yts definition so you can connect.
