### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: Selector

### ISSUE THREAD

**Issue by darkpisto** [Jackett/Jackett#2260]
An error occured while testing this indexer
Exception (yggtorrent): Login failed: Selector "a[href$="user/logout"]" didn't match: Parse error

 Jackett Version 0.8.500.0 

Thanks :)

**Comment by kriegalex** [comment]
Hi, Please check your login informations are ok in jackett and you are using your username (not email).
For me, the login text box was empty and was causing this error message

**Comment by darkpisto** [comment]
Sorry i don't speak english very well.

The username was empty, but i used Jacket since months without enter my login again oO

Thanks for the info :)
