### ISSUE TITLE
[torrent9] Exception (torrent9): Request to http://www.torrents9.pe/top_torrent.php failed (Error BadGateway) - The tracker seems to be down.: Request to http://www.torrents9.pe/top_torrent.php failed (Error BadGateway) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by Sillikk** [Jackett/Jackett#2261]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Windows

-------------------------------

**Comment by garfield69** [comment]
torrent9 is back up and running.
I see that torrent9 have asked cloudflair to turn on ddos protection, so it appears that their servers were under attack earlier, which accounts for the bad gateway issue you reported.

**Comment by Sillikk** [comment]
Sorry but I keep getting errors on that tracker. It doesn't seem to work and the tracker is up. I tried downloading a torrent I picked directly from the site and it worked.

**Comment by kaso17** [comment]
@Sillikk the domain changed, change it manually (see #2273) or update to jackett v0.8.509
