### ISSUE TITLE
[theempire] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by benfishbus** [Jackett/Jackett#2263]
Error when testing theempire.click

Jackett version:  0.8.500.0
Mono version (if not using Windows):  5.4.1.6
[jackett-log.txt](https://github.com/Jackett/Jackett/files/1545872/jackett-log.txt)

-------------------------------

**Comment by garfield69** [comment]
Unfortunately the log you provided is just the normal log, and does not contain enough detail to be useful in diagnosing your problem.    
Please provide the full **enhanced** log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.

**Comment by benfishbus** [comment]
Good grief. Short answer: I needed to reenter my credentials, and now it tests fine. Longer answer: After I figured out I was forgetting to "Apply server settings" after checking the box for enhanced logging, the enhanced log showed a 404 error for theempire. Same URL loaded fine in browser, so had to be a lack of authentication.
