### ISSUE TITLE
[rarbg] Error reading JObject from JsonReader. Path '', line 0, position 0. (Config)

### ISSUE THREAD

**Issue by vinchi007** [Jackett/Jackett#2266]
tried adding "+" RARBG and received below error:

An error occured while configuring this indexer
Error reading JObject from JsonReader. Path '', line 0, position 0.

Jackett version:  latest master v0.8.500
Mono version (if not using Windows):  Stable 4.6.2.7
running on freenas unix

-------------------------------

**Comment by kaso17** [comment]
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
