### ISSUE TITLE
Error downloading kickasstorrent-kathow

### ISSUE THREAD

**Issue by kianrafiee** [Jackett/Jackett#2269]
Jackett version:  v0.8.500
Mono version (if not using Windows):  5.4.1
Synology NAS DS218play

-------------------------------
When trying to download a torrent from KickAss Torrents through Radarr, I get a "Getting release from indexer failed" and since my indexer is using Jackett, I looked at the Jackett log and found this:
```
Dec 11, 2017 09:39:42 PM | Error | Error downloading kickasstorrent-kathow https://mylink.st/r.php?url=magnet:%3Fxt%3Durn:btih:2B5A87785500953BB43955AA558B9C0520E96D15%26dn%3D%252Abatteries%2Bnot%2Bincluded%2B%25281987%2529%2B%255B1080p%255D%2B%255BYTS.AG%255D%2B-%2BYIFY%26tr%3Dudp%253A%252F%252Fglotorrents.pw%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.opentrackr.org%253A1337%252Fannounce%26tr%3Dudp%253A%252F%252F9.rarbg.com%253A2710%252Fannounce%26tr%3Dudp%253A%252F%252Fp4p.arenabg.com%253A1337%26tr%3Dudp%253A%252F%252Ftracker.leechers-paradise.org%253A6969%26tr%3Dudp%253A%252F%252Ftracker.internetwarriors.net%253A1337%26tr%3Dudp%253A%252F%252Ftracker.coppersurfer.tk%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.zer0day.to%253A1337%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.leechers-paradise.org%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Fcoppersurfer.tk%253A6969%252Fannounce

```

**Comment by garfield69** [comment]
Yeah, the problem here is that kathow are using the mylink.st service to provide the links for the magnets, and mylink are using a coinhive captcha to generate transaction revenue.     
Jackett is not expecting this intermediate step on the download links.

**Comment by kianrafiee** [comment]
So I'm guessing this won't be fixed until kathow stops using revenue generating links?

**Comment by kianrafiee** [comment]
Oh I see you fixed it through code. Nice. So we have to wait for the next jackett update?

**Comment by garfield69** [comment]
Good news. Turns out that by stripping the mylink address and urldecoding the rest, the magnet link can then be used as normal. 
Commit 7fb6fd4 will be included in the next (pre)release of Jackett, whenever that happens next.

**Comment by kianrafiee** [comment]
Nice, thank you!
