### ISSUE TITLE
[torrent9] Exception (torrent9): Request to http://www.torrents9.pe/top_torrent.php failed (Error BadGateway) - The tracker seems to be down.: Request to http://www.torrents9.pe/top_torrent.php failed (Error BadGateway) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by turak** [Jackett/Jackett#2273]
Error when launch test connection for this tracker.

 An error occured while testing this indexer
Exception (torrent9): Request to http://www.torrents9.pe/top_torrent.php failed (Error BadGateway) - The tracker seems to be down.: Request to http://www.torrents9.pe/top_torrent.php failed (Error BadGateway) - The tracker seems to be down.

Jackett version:  Version 0.8.505.0

URL http://www.torrents9.pe/top_torrent.php  works fine
And curl command works fine from my server.

-------------------------------

**Comment by garfield69** [comment]
you can fix this now for yourself by using the wrench icon on your Jackett Dashboard and editing the torrent9 SiteLink to `http://www.torrent9.bz/`
![image](https://user-images.githubusercontent.com/6933240/33952363-75aac6a4-e096-11e7-823e-78fe4b2c28e5.png)
or you can wait for the next (pre)release of Jackett which includes the fix in  cab4687

**Comment by turak** [comment]
Arghhh not see this.. Thanks a lot!
