### ISSUE TITLE
[1337x] Exception (1337x): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 104.31.17.3:443: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by shaun2312** [Jackett/Jackett#2274]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
Looks like a temporary outage at 1337x. I don't have any problems accessing 1337x from Jacket now. So try again.      
In the unlikely event you still have a problem then please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
