### ISSUE TITLE
[yggtorrent] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by BaptisteGh** [Jackett/Jackett#2286]
Jackett version:  0.8.509.0
Mono version (if not using Windows):  5.4.1.6

-------------------------------

My login/password are good
actual address : https://yggtorrent.com/

**Comment by garfield69** [comment]
Read solution in duplicate #2283

**Comment by BaptisteGh** [comment]
No, it doesn't work (i said, the link is : https://yggtorrent.com/ (the good one))

**Comment by garfield69** [comment]
yes i see. In that case you are going to have to wait until the next Jackett release which will has the fix. Sorry.
