### ISSUE TITLE
[yggtorrent] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by darkpisto** [Jackett/Jackett#2288]
Sorry i d'ont speak english very well ;)

The URL of https://yggtorrent.com was https://ww1.yggtorrent.com, it's https://yggtorrent.com again -_-

Why the url list can't be modified without making an issue ?

Thanks in advance :)

Bests regards

**Comment by garfield69** [comment]
Duplicate of #2283

**Comment by darkpisto** [comment]
And i found how to fix manually : 
Edit the "yggtorrent.yml" like this : 
  links:
    - https://yggtorrent.com/
    - https://ww1.yggtorrent.com/

Restart Jacket and tadaaaaaaaa :)
