### ISSUE TITLE
French Indexer - Intergrate - Cpasbien or how to modify Perl sources

### ISSUE THREAD

**Issue by RogerWilco08** [Jackett/Jackett#229]
Hello,

Is the nice Idea your Script but a litle short.

Is it possible to include more of free French Indexer like Cpasbien.

Or how to modify your script for that.

Regards

RW

**Comment by JigSawFr** [comment]
Cpabien is a big crap tracker and is under heavy attention by governement. So i don't think that it will be implemented in a short or long future.
