### ISSUE TITLE
Jackett not starting on Synology, access to the path "/config/Jackett" is denied

### ISSUE THREAD

**Issue by jornbakhuys** [Jackett/Jackett#2291]
Docker image: `linuxserver/jackett`
Synology: DS218+

When using the `linuxserver/jackett` docker image on Synogoly, I'm getting high CPU usage, and Jackett isn't available on the port. Looking at the logs it says `Access to the path \"/config/Jackett\" is denied.`.

I've provided the `-e PGID=1024 -e PUID=100` flags, and looking at the logs I see:
```
User uid:    100
User gid:    102
```
Could it have something to do with an incorrect `gid`, messing up the permissions?

Extended view of a row of the log:
> `2017-12-16 14:06:03,stdout,"12-16 15:06:03 Error Top level exception Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ServerService (ReflectionActivator), Services = [Jackett.Services.Interfaces.IServerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IndexerManagerService (ReflectionActivator), Services = [Jackett.Services.Interfaces.IIndexerManagerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IndexerConfigurationService (ReflectionActivator), Services = [Jackett.Services.Interfaces.IIndexerConfigurationService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ConfigurationService (ReflectionActivator), Services = [Jackett.Services.Interfaces.IConfigurationService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(ISerializeService, IProcessService, Logger, RuntimeSettings)' on type 'ConfigurationService'. ---> Could not create settings directory. Access to the path \"/config/Jackett\" is denied. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IndexerManagerService (ReflectionActivator), Services = [Jackett.Services.Interfaces.IIndexerManagerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IndexerConfigurationService (ReflectionActivator), Services = [Jackett.Services.Interfaces.IIndexerConfigurationService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ConfigurationService (ReflectionActivator), Services = [Jackett.Services.Interfaces.IConfigurationService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(ISerializeService, IProcessService, Logger, RuntimeSettings)' on type 'ConfigurationService'. ---> Could not create settings directory. Access to the path \"/config/Jackett\" is denied. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IndexerConfigurationService (ReflectionActivator), Services = [Jackett.Services.Interfaces.IIndexerConfigurationService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ConfigurationService (ReflectionActivator), Services = [Jackett.Services.Interfaces.IConfigurationService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(ISerializeService, IProcessService, Logger, RuntimeSettings)' on type 'ConfigurationService'. ---> Could not create settings directory. Access to the path \"/config/Jackett\" is denied. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ConfigurationService (ReflectionActivator), Services = [Jackett.Services.Interfaces.IConfigurationService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(ISerializeService, IProcessService, Logger, RuntimeSettings)' on type 'ConfigurationService'. ---> Could not create settings directory. Access to the path \"/config/Jackett\" is denied. (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(ISerializeService, IProcessService, Logger, RuntimeSettings)' on type 'ConfigurationService'. ---> Could not create settings directory. Access to the path \"/config/Jackett\" is denied. (See inner exception for details.) ---> System.Exception: Could not create settings directory. Access to the path \"/config/Jackett\" is denied.`

Thanks for the help 🙏

**Comment by kaso17** [comment]
I suggest you try opening an issue over at the linuxsserver project as its probably a docker specific issue (access denied)
