### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Connection refused: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by MostlyDisappointing** [Jackett/Jackett#2292]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------
Running Jackett in Docker on a synology NAS, using a VPN on the NAS and computer. All torrent sites when running test give this error.

[log.txt](https://github.com/Jackett/Jackett/files/1564921/log.txt)

**Comment by kaso17** [comment]
looks like a generic connectivity issue of your NAS. Try accessing some of the tracker websites from the shell and try to find out what's the problem with the configuration.

**Comment by MostlyDisappointing** [comment]
Ah, right. Looks like I need to look into what the NAS is doing with my VPN. Thanks.

curl -I -L thepiratebay.org
HTTP/1.1 302 Moved Temporarily
Content-Type: text/html
Date: Sat, 16 Dec 2017 16:54:37 GMT
Location: http://www.ukispcourtorders.co.uk/
Connection: Keep-Alive
Content-Length: 0
