### ISSUE TITLE
Stripping / from AnimeTorrents search

### ISSUE THREAD

**Issue by raitono** [Jackett/Jackett#2296]
Jackett version:  0.8.514.0
Mono version (if not using Windows):  mono-4.8.1.0_2
I'm using FreeBSD 11.1.

The / character is being removed from searches and so I cannot get results for  Fate/Apocrypha. You can see that at line 319 of the attached log.
[log.txt](https://github.com/Jackett/Jackett/files/1565284/log.txt)

**Comment by kaso17** [comment]
fixed via 4692cd60ee53eaa101ef6f3aa42f68b13dced3df
