### ISSUE TITLE
[HDSky]search error, search result is totally irrelevant

### ISSUE THREAD

**Issue by bimzcy** [Jackett/Jackett#2297]
Any search got irrelevant result and the log show error:

![01](https://user-images.githubusercontent.com/2244565/34076469-2d037ea2-e323-11e7-9c4e-24ffd80a5d30.jpg)

Please fix it, thank you.

Jackett version: 0.8.514.0

**Comment by garfield69** [comment]
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
We need to see the full log with the trace enabled so we can determine what changes to make to the hdsky definition's  css selectors. Thanks.

**Comment by bimzcy** [comment]
log added.
[log.txt](https://github.com/Jackett/Jackett/files/1565346/log.txt)

**Comment by kaso17** [comment]
can't reproduce the error.
in the log it only says that you're not logged in to hdsky. please reconfigure the indexer
