### ISSUE TITLE
Tracker Modification - Torrentbytes

### ISSUE THREAD

**Issue by SaskiFX** [Jackett/Jackett#230]
I noticed that Jackett is missing some categories for Torrentbytes. Mainly the TV/Pack category. Is there any way to add that one? It has quite a few full seasons I am wanting Sonarr to download, but it never finds them. Its especially nice since the Packs on Torrentbytes are free to download.

**Comment by JigSawFr** [comment]
@SaskiFX you can suggest a better mapping for this tracker ;)

**Comment by flightlevel** [comment]
Contributions are very welcome.
Options - https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker
Categories already present https://github.com/Jackett/Jackett/blob/master/src/Jackett/Indexers/TorrentBytes.cs#L45

**Comment by SaskiFX** [comment]
Ah, now that I'm looking at the code, I'm realizing that it is there, but its listed as TV only. I also didn't realize that the categories it shows in the Jackett config can relate to multiple categories on the tracker. 

I have added the appropriate category to Sonarr and I'll see if it starts picking up the files.
