### ISSUE TITLE
[yggtorrent] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by fantasio31** [Jackett/Jackett#2300]
Yggtorrent tracket does no longer work while it has worked before. It always return a "got redirected" error while trying to reconfigure the tracker.
Trying on the original web site with the same credentials works fine.

Jackett version:  0.8.500.0
Mono version:  5.4.1.6

Logs:
[log.txt](https://github.com/Jackett/Jackett/files/1565695/log.txt)
------------------------------

**Comment by HLFH** [comment]
Same issue.

**Comment by HLFH** [comment]
Works fine with v0.8.514. Please update.

You can close this issue.

**Comment by fantasio31** [comment]
ok, closed with b0.8.514.

**Comment by garfield69** [comment]
Duplicate of #2283
