### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Parse error: Parse error (Test)

### ISSUE THREAD

**Issue by Sonii** [Jackett/Jackett#2302]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  9.0.30
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
where on earth did you find Jackett version 9.0.30?     
The latest official version of Jackett as far as I know is v0.8.514 (https://github.com/Jackett/Jackett/releases) which has a working yggtorrent definition.
Also, make sure you are using your username and not your email address for your login details, a requirement that yggtorrent implemented about a week ago
