### ISSUE TITLE
Update Zooqle Path Definition

### ISSUE THREAD

**Issue by Qstick** [Jackett/Jackett#2303]
Zooqle definition has a few issues:

1.  The hard-coded movie category causes issues with Sonarr/Lidarr on test due to the fact we are sending a blank request with Audio or TV categories.

    `- path: "/search?q={{if .Keywords}}{{ .Keywords}}&s=ns&v=t&sd=d{{else}}movie+test+torrent+category%3AMovies{{end}}"`

    should be

    `- path: "/search?q={{if .Keywords}}{{ .Keywords}}&s=ns&v=t&sd=d{{else}}movie+test+torrent{{end}}"`

    Or better yet use the categories that are passed to ensure results are returned

2. Categories are not being used in above search request, correct format for categories should be:

    `https://zooqle.com/search?q={search term}+category%3AMusic` 

    or for multiple categories

    `https://zooqle.com/search?q={search term}+category%3AMovies%2CMusic` 

Jackett version:  0.8.514.0
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
fixed via 20b4d936862fbdf1a445dc8326e2ff55ddeecd6a (including category support)
