### ISSUE TITLE
[1337X] - Cannot download torrent (manually/automatically)

### ISSUE THREAD

**Issue by n1nj4888** [Jackett/Jackett#2305]
When manually searching for a torrent on 1337 indexer and then selecting "Send to Server Blackhole" the torrent is sent to the server blackholde but it then marked as .invalid (either by Jackett/Deluge?) - The contents of the .magnet file that are sent to the balckhole are strange also - They appear to be the HTML code of the website rather than the single magnet URL? I get the following error in the jackett log:

Dec 18, 2017 06:53:50 AM | Error | Error downloading to blackhole 1337x https://1337x.to/torrent/2668480/Gomorra-S03E09E10-720p-x264-MultiSubs-StB/
-- | -- | --

This issue may also be the reason that, when trying to download the same Episode as a torrent (using this same Jackett 1337X indexer) via Sonarr, I get the following error in Sonarr:

| ReleaseModule | Downloading torrent failed: Downloading torrent failed | 6:42am
| Deluge | Downloading torrent file for episode 'Gomorra S03E09E10 720p x264 MultiSubs-StB' failed since it no longer exists (<URL REMOVED> &file=Gomorra+S03E09E10+720p+x264+MultiSubs-StB): 
HTTP request failed: [404:NotFound] [GET] at [<URL REMOVED> | 6:42am
| HttpClient | HTTP Error - Res: [GET] <URL REMOVED> file=Gomorra+S03E09E10+720p+x264+MultiSubs-StB: 404.NotFound

-------------------------------
Jackett version:  0.8.514.0 (Linuxserver.io-jackett on Synology Docker)
Mono version (if not using Windows):  Mono JIT compiler version 5.2.0.224

-------------------------------

**Comment by kaso17** [comment]
The itorrents download link of that torrent is simply dead.
80960665ec7f45c01b70a9ab0cfe7e7bbd82f54d makes the download link selection configurable defaulting to magnet which should fix your problem

**Comment by n1nj4888** [comment]
Great! Thanks @kaso17!!! Presumably 8096066 refers to a code change that will be available in a later version of Jackett?

**Comment by kaso17** [comment]
it's included in the v0.8.522 release
