### ISSUE TITLE
[ettv] Exception (ettv): Request to https://www.ettv.tv/torrents-search.php?search=

### ISSUE THREAD

**Issue by HidyHo** [Jackett/Jackett#2306]
Exception (ettv): Request to https://www.ettv.tv/torrents-search.php?search=&incldead=1 failed (Error BadGateway) - The tracker seems to be down.: Request to https://www.ettv.tv/torrents-search.php?search=&incldead=1 failed (Error BadGateway) - The tracker seems to be down.
[log.txt](https://github.com/Jackett/Jackett/files/1567766/log.txt)

**Comment by HidyHo** [comment]
Tracker is not down ...

**Comment by daman96** [comment]
Yes, The tracker is up but Jackett is returning "BadGateway" error. The URL can be accessed directly from the same machine using Chrome or another browser.

**Comment by kaso17** [comment]
I could only reproduce this on my linux machine.
Can you please share the current config (cookies) of ETTV:
`cat ~/.config/Jackett/Indexers/ettv.json`
Then remove/re-add the indexer to reset the cookies (that fixed it for me)

**Comment by daman96** [comment]
Yes, removing and re-adding the indexer solved the issue. These are the contents of `cat ~/.config/Jackett/Indexers/ettv.json`:

`[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://www.ettv.tv/"
  },
  {
    "id": "cookieheader",
    "type": "hiddendata",
    "name": "CookieHeader",
    "value": "__cfduid=dc4a5d6b7cf153a266940a08f3c3800301512623946; PHPSESSID=12ciie91nlbpikc9m7djmfrme2; pass=deleted; uid=deleted; cf_use_ob=443; cf_ob_info=523:3cdafaec2b250902:CDG"
  },
  {
    "id": "lasterror",
    "type": "hiddendata",
    "name": "LastError",
    "value": "Exception (ettv): Request to https://www.ettv.tv/torrents-search.php?search=&incldead=1 failed (Error BadGateway) - The tracker seems to be down.: Request to https://www.ettv.tv/torrents-search.php?search=&incldead=1 failed (Error BadGateway) - The tracker seems to be down."
  }
]`

**Comment by kaso17** [comment]
Was apparently caused by the extra `cf_use_ob=443; cf_ob_info=523:3cdafaec2b250902:CDG` cookies injected by cloudflare which are breaking the connection.
Seems to be a generic issue:
http://www.giantitp.com/forums/archive/index.php/t-272067.html
If it happens again please report here so we can get rid of the cookies automatically.

**Comment by kaso17** [comment]
With 405981581195297b539e5bdbc13a4ceee9c2eef0 we're now dropping these cookies.
Indexers experiencing this problem still might have to be re-added but it shouldn't happen again.
