### ISSUE TITLE
Update MagnetDL path definition to use Category during test

### ISSUE THREAD

**Issue by Qstick** [Jackett/Jackett#2310]
MagnetDL fails test on Sonarr and Lidarr due to hard coded movie categories used during test (no search keywords):

https://github.com/Jackett/Jackett/blob/ed41d383a3995c0f488f9e9b8129288ea21cdc7d/src/Jackett.Common/Definitions/magnetdl.yml#L40

Instead of using `download/movies` Jacket should use `download/{first category}` with first category being the first mapped category provided by the request. MagnetDL doesn’t appear to accept multiple categories in a request call.

**Comment by kaso17** [comment]
situation improved via 8c90b8ed02ddc4be662c169a7b61666b434c1e6b
as long as the latest 40 torrents contains >= 1 audio you should be fine
Let me know if you get more reports of failed tests.
If another idea of fixing it in a better way.

**Comment by Qstick** [comment]
Thanks @kaso17, this should be better. Would be nice to use the category for the test call if one is passed, but wasn't sure if you guys had the ability to add that logic here.

**Comment by wherearemylegs** [comment]
This is still an issue for me.

**Comment by wherearemylegs** [comment]
This is still an issue for me but a workaround is to add MagnetDL using another tracker's URL for the test. Once added, edit the indexer with MagnetDL's URL and save. The test will still fail but it doesn't need the test to pass for edits.

**Comment by Arzte** [comment]
Bumping this issue as @wherearemylegs's solution no longer works in lidarr. As it stands right now attempting to magnetDL to lidarr fails with no result found.
