### ISSUE TITLE
WorldWideTorrents possible failure during test

### ISSUE THREAD

**Issue by Qstick** [Jackett/Jackett#2311]
We have had multiple users experience failure during test on Lidarr due to the indexer not returning any results on a “test” call. This is due to the category being hard coded to 0 during test. 

https://github.com/Jackett/Jackett/blob/ed41d383a3995c0f488f9e9b8129288ea21cdc7d/src/Jackett.Common/Definitions/worldwidetorrents.yml#L163

Because this looks at all releases there is a possibility that the feed will not contain a release in the user set category passed by sonarr, Lidarr, or radarr. Ex. We pass a test call with category 3000, however the test feed actually contains no music release,thus jackett returns no releases and the test fails.

A fix for this would be to use categories (if passed) during the test call instead of only using `cat=0`

**Comment by kaso17** [comment]
their multi category search seems to be broken clicking one or more of the category search boxes on their search page doesn't have any impact.
