### ISSUE TITLE
Jackett reverse proxy not working

### ISSUE THREAD

**Issue by Mssol94** [Jackett/Jackett#2316]
Jackett version:  0.8.527.0
Mono version (if not using Windows):  

-------------------------------
I'm trying to set up reverse proxy with Jackett, but I can't access localhost/jackett. My `ServerConfig.json` is:

```
{
  "Port": 9117,
  "AllowExternal": true,
  "APIKey": "***",
  "AdminPassword": "***",
  "InstanceId": "***",
  "BlackholeDir": "",
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": "/jackett",
  "OmdbApiKey": "",
  "ProxyUrl": "",
  "ProxyType": 0,
  "ProxyPort": null,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true
}
```
The server is Nginx and my `nginx.conf` is:
```
        location /jackett {
		    proxy_pass http://127.0.0.1:9117;
		    proxy_set_header Host $host;
		    proxy_set_header X-Real-IP $remote_addr;
		    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    }
```
Here is the response:
![screenshot_6](https://user-images.githubusercontent.com/7490531/34297100-5848e240-e716-11e7-9ef2-9b872da088dd.png)

**Comment by kaso17** [comment]
Do you see the request going to jackett at all (start jackett with the -l option)?
Anything in the nginx logs?
I suspect something is wrong with your nginx config.

**Comment by Quiksmage** [comment]
what do your nginx server settings look like?

Do you have other location's that are working from nginx?

**Comment by Mssol94** [comment]
I haven't got access to the config file for nginx right now, but I have other locations that are working.

**Comment by Quiksmage** [comment]
and you're accessing them the same way, right? http://localhost/thing. No subdomains, or anything?

What page do you specifically see when going to http://localhost/jackett?

If you go to  http://localhost/jackett/UI/Dashboard, does it work?

If it's just not redirecting properly, I can give you a few settings to try.

**Comment by Quiksmage** [comment]
to further clarify, mine acts the same way on https://domain.com/jackett

I have to use https://domain.com/jackett/ for it to properly redirect to UI/Dashboard

@kaso17 is that a problem with my nginx config or something that should be fixed on jackett's side?

**Comment by Mssol94** [comment]
I tried localhost/jackett/UI/Dashboard and localhost/jackett/ and they both work.

**Comment by sho-87** [comment]
I have the same issue using apache, so I dont think its specific to OPs nginx config

My apache config:

```
        <Location /jackett>
                ProxyPreserveHost On
                RequestHeader set X-Forwarded-Proto "https"
                ProxyPass http://192.168.187.10:9117/jackett
                ProxyPassReverse http://192.168.187.10:9117/jackett
        </Location>
```

when I go to `https://www.website.com/jacket` I get a 404 error, but if I go to `https://www.website.com/jacket/` everything works fine (correctly redirects to `/UI/dashboard`)

The same thing happens when I try to access via localip: `<local ip>/jacket` gives 404, but `<local ip>/jacket/` works fine

**Comment by kaso17** [comment]
please try
        <Location /jackett>
                ProxyPreserveHost On
                RequestHeader set X-Forwarded-Proto "https"
                ProxyPass http://192.168.187.10:9117
                ProxyPassReverse http://192.168.187.10:9117
        </Location>

**Comment by Quiksmage** [comment]
Hey @kaso17 , any idea why it's a white page on /jackett, but properly redirects on /jackett/?

This is bypassing the reverse proxy and just being local on http://localhost:9117/jackett

**Comment by kaso17** [comment]
@Quiksmage either by having a tailing / in the basepath override in the jackett config or by adding /jackett to the ProxyPass/ProxyPassReverse apache settings.

My personal recommended apache config snipped:
```
<Location /jackett>
  ProxyPreserveHost On
  RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
  ProxyPass http://127.0.0.1:9117
  ProxyPassReverse http://127.0.0.1:9117
</Location>

```

**Comment by kaso17** [comment]
@Quiksmage can you please try v0.8.624 (pre release), it contains some changes which should make /jackett work too.

**Comment by Quiksmage** [comment]
Current version Jackett Version 0.8.602.0 gives a 404 on /jackett

Jackett Version 0.8.626.0 appears to be working

/jackett now correctly redirects to jackett/UI/Dashboard

Thanks for the continued support @kaso17 everyone definitely appreciates it here :)

I think this will be good to be closed once that pre-release goes live
