### ISSUE TITLE
[kickasstorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by weezzelboy** [Jackett/Jackett#2318]
when running test in web UI  I get this error.
[kickasstorrent] Found no results while trying to browse this tracker (Test)

they are not under the DDoS attack anymore site is functioning well and fast too. 
I go to the site login and i am able to download from them just fine. using any torrent client. 
Jackett Version 0.8.527.0 on windows.

**Comment by garfield69** [comment]
Duplicate of #2280
KATcr are using a DDOS protection check which recognises Jackett as a ROBOT and stops it working.
