### ISSUE TITLE
Animebytes returns too many results

### ISSUE THREAD

**Issue by Quiksmage** [Jackett/Jackett#2322]
Hi,
Animebytes currently DOES work and returns the result you are looking for, but it also returns EVERYTHING from the series name

For example,
![image](https://user-images.githubusercontent.com/12449533/34329018-7801d372-e8a5-11e7-8d44-689f1b5b1c00.png)

It shouldn't return anything here as episode 24 has not been released yet. It lists every episode for the series.

Thankfully sonarr rejects the results as it's the wrong episode :)

It also lists the published hours listed incorrectly.

If I can provide any details or testing, please let me know.

Thanks in advance and have a Happy Holidays :)

**Comment by DarkSupremo** [comment]
I'm not sure if that's the case (i don't have account on that tracker), but some trackers does not support searching for specific episode, so the workaround is to search excluding the episode number, so it will return the latests episodes for that anime

**Comment by Quiksmage** [comment]
gotcha, thanks for looking at that for me :)

Merry Christmas/Happy Holidays.
