### ISSUE TITLE
[cpasbien] Exception (cpasbien): Request to http://www.cpabien.cx/derniers/ failed (Error BadGateway) - The tracker seems to be down.: Request to http://www.cpabien.cx/derniers/ failed (Error BadGateway) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by BaptisteGh** [Jackett/Jackett#2323]
Jackett version:  0.8.527.0
Mono version (if not using Windows):  5.4.1.6

-------------------------------
"Exception (cpasbien): Request to http://www.cpabien.cx/derniers/ failed (Error BadGateway) - The tracker seems to be down.: Request to http://www.cpabien.cx/derniers/ failed (Error BadGateway) - The tracker seems to be down."

**Comment by garfield69** [comment]
looks similar to #2306 
Can you please share the current config (cookies) of cpasbien:
`cat ~/.config/Jackett/Indexers/cpasbien.json`
Then remove/re-add the indexer on your Jackett Dashboard to reset the cookies and see if that works for you or not.

**Comment by BaptisteGh** [comment]
Cookie :
[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "http://www.cpabien.cx/"
  },
  {
    "id": "cookieheader",
    "type": "hiddendata",
    "name": "CookieHeader",
    "value": "__cfduid=d632b09da4c8a6bd8ddd9229a489dc89e1513098631; PHPSESSID=fc10b996667611cf302465a2b9c223cd; cf_clearance=866964b00a1d1d5b4f6c5b6f7b0ddffcb1f06e5c-1513098631-31536000; cf_use_ob=80; cf_ob_info=524:3cefd82e14f77301:AMS"
  },
  {
    "id": "lasterror",
    "type": "hiddendata",
    "name": "LastError",
    "value": "Exception (cpasbien): Request to http://www.cpabien.cx/derniers/ failed (Error BadGateway) - The tracker seems to be down.: Request to http://www.cpabien.cx/derniers/ failed (Error BadGateway) - The tracker seems to be down."
  }
]#

—————
After remove/re-add it works ! Thanks

**Comment by kaso17** [comment]
thank you, should be "fixed" via 405981581195297b539e5bdbc13a4ceee9c2eef0 too
