### ISSUE TITLE
[Nyaa.si] category setting does not work for "Anime - English Translated"

### ISSUE THREAD

**Issue by Archmonger** [Jackett/Jackett#2324]
On the nyaa.si tracker, changing the "category" setting to "Anime - English Translated" does not result in the same results as would be expected if selecting "Anime - English Translated" on the nyaa.si webpage. Many of the results received are dubbed. An example of this is when searching for "New Game!" in Sonarr, the majority of the results are dubbed. 

Jackett version: 0.8.527.0

**Comment by kaso17** [comment]
works fine for me.
Can you please share some example search queries/unexpected releases.

**Comment by Archmonger** [comment]
### Nyaa.si Config 
_Freenas Jail [Mono] - Auto update enabled - Version 0.8.527.0_

- Site Link: https://nyaa.si/
- Filter: No Filter
- Category: Anime - English Translated

### Sonarr 
_Freenas Plugin - Auto update enabled - Version 2.0.0.5085_
1) Add New Game! to library
2) Click to start a manual search for Episode 1 Season 1
3) Results are: https://gyazo.com/1896d71571f224dad31796ace13e2369

**Comment by Archmonger** [comment]
Actually never mind. Even though Nyaa considers the category "English-Translated" as "Anime Sub", it appears as if users still upload dubs using this same category. My fault for not realizing this.
