### ISSUE TITLE
[torlock] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by SteffanCline** [Jackett/Jackett#2328]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.8.527.0
Mono version (if not using Windows):  Latest

-------------------------------

**Comment by garfield69** [comment]
I've no problems accessing or testing torlock.    
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.

**Comment by SteffanCline** [comment]
Attached is the log file as requested. You'll probably see a couple others that failed as well.
[log.txt](https://github.com/Jackett/Jackett/files/1589553/log.txt)

**Comment by garfield69** [comment]
could not find torlock in that log.
please perform a test just with torlock and upload that enhanced log thanks.

**Comment by SteffanCline** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/1589603/log.txt)

**Comment by kaso17** [comment]
once again the log doesn't contain any torlock searches

**Comment by SteffanCline** [comment]
I'm pressing the button repeatedly. What else can I do to capture it?

**Comment by SteffanCline** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/1589760/log.txt)

**Comment by SteffanCline** [comment]
Try that one.

**Comment by kaso17** [comment]
you're receiving a cloudflare captcha challenge. Most likely you're using an IP with bad reputation. Please try with a different IP.
