### ISSUE TITLE
[shareisland] Login failed: Selector

### ISSUE THREAD

**Issue by rafuz** [Jackett/Jackett#2329]
Jackett version:  0.8.527.0
Mono version (if not using Windows):  5.4.1.6 

-------------------------------
`
An error occured while updating this indexer
Login failed: Selector "div#member_info_bar" didn't match
`

Shareisland has changed the layout of the website. The plugin is not working anymore.

**Comment by kaso17** [comment]
fixed via caac78165100a4f9c1dfa5b2e591654e313c105a
