### ISSUE TITLE
Error on search - Few results in cached Cached Releases

### ISSUE THREAD

**Issue by Slinkynose** [Jackett/Jackett#233]
I see the following error in the Jackett log when I execute a search from Couch Potato - 
"On attempt 1 checking for results from TehConnection: Error while copying content to a stream."

When I look at the Cached Releases Page I only see around 13 items.  If I search an item from that list in Couch Potato, the download begins correctly.

**Comment by kaso17** [comment]
is this still a problem?

**Comment by flightlevel** [comment]
This issue hasn't had activity for a while. If the issue still exists, please reopen and include full logs. https://github.com/Jackett/Jackett#troubleshooting
