### ISSUE TITLE
Forgot my Password

### ISSUE THREAD

**Issue by Smaleee** [Jackett/Jackett#2335]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by Smaleee** [comment]
Help please... Mac OS High Sierra ver 10.13.2, Mono 4.6.1, Jackett_Install_Macos
My Problem: I either need an admin password to override a corrupt/lost password or a clean uninstall method to remove an incorrectly logged password as I'm nnable to access UI/Dashboard. Thanks.

**Comment by kaso17** [comment]
stop jackett, edit the ~/.config/Jackett/ServerConfig.json file and change the AdminPassword line to this:
`  "AdminPassword": null,`
Start jackett again and there should be no password.

**Comment by Smaleee** [comment]
Thanks Kaso17, forgive me but... How do I stop Jackett, it autoruns at start up and... Where might I find said file, also what program might I use to edit it... I am no more than an enthusiastic end user who auto installed and have no programming/terminal knowledge?

**Comment by Smaleee** [comment]
is this what I'm looking for?
![screen shot 2017-12-28 at 17 09 49](https://user-images.githubusercontent.com/34604361/34418121-2ab857c4-ebf4-11e7-8cc6-3550ea8170ba.png)

**Comment by kaso17** [comment]
No idea about mac os.
Try doing a `rm -f ~/.config/Jackett/` to reset the jackett config.

**Comment by Smaleee** [comment]
What ? Where ? How ? Apologies for my apparent incompetence !

**Comment by garfield69** [comment]
I don't have a macos either, but a quick google came up with some basic instructions for you to try out:
1. open a terminal (see https://superuser.com/questions/178735/how-do-you-get-a-shell-on-a-mac#178736 as an example)
2. paste the following at the command prompt to set yourself up with admin authority `sudo -i` and supply the admin password when prompted. ( https://stackoverflow.com/questions/31700746/how-to-run-terminal-as-administrator-on-mac-pro)
3. paste the following at the prompt `launchctl unload ~/Library/LaunchAgents/org.user.Jackett.plist` to shutdown the jackett service (https://github.com/Jackett/Jackett#install-as-service)
4. edit the jackett config by pasting the following at the prompt: `open -e ~/.config/Jackett/ServerConfig.json`  (https://stackoverflow.com/questions/9421717/how-do-i-invoke-a-text-editor-from-the-terminal#21705438)
5. scroll down till you find the `AdminPassword` line and replace it with `"AdminPassword": null,`
6. save your changes.
7. start the jackett service `launchctl load ~/Library/LaunchAgents/org.user.Jackett.plist` (https://github.com/Jackett/Jackett#install-as-service)

Good luck.

**Comment by Smaleee** [comment]
Thanks Garfield, your copy and paste instructions for terminal worked great for me, you're a star !
