### ISSUE TITLE
[secretcinema] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by bourneon1** [Jackett/Jackett#2336]
log.txt removed for security

Jackett version:  0.8.539.0
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
please provide a log with enhanced logging enabled (the one provide is a normal one)

**Comment by bourneon1** [comment]
Sorry. Advanced log attached.
[log.txt](https://github.com/Jackett/Jackett/files/1591840/log.txt)

**Comment by garfield69** [comment]
Sorry, no good. The log you provided contains only waffles, worldofp2p and xtremezone.
Try again, this time using only secretcinema.
Alternatively, provide all the other parts of the log, that go by the naming convention similar to `log.20171227.00046.txt` for example.

**Comment by bourneon1** [comment]
Thanks for the help. 

[log.txt](https://github.com/Jackett/Jackett/files/1593184/log.txt)

**Comment by garfield69** [comment]
Looks like we will need to update the current Jackett secretcinema definition, because the current row selector does not match the html that the secretcinema site is using for their search results in your log.

**Comment by bourneon1** [comment]
[log_e.txt](https://github.com/Jackett/Jackett/files/1598397/log_e.txt)

**Comment by kaso17** [comment]
Can someone provide an invite so I can fix it?
Please sent it to kaso1717 -at- gmail.com

**Comment by bourneon1** [comment]
sent

**Comment by kaso17** [comment]
thank you, fixed via cacafcff582d1fe530a49516e0d09e03a156c85e
