### ISSUE TITLE
Synology service not starting

### ISSUE THREAD

**Issue by lrafagnin** [Jackett/Jackett#2337]
The service cannot start on Synology, no errors are logged

Strangely, it starts if I run the following on shell
```bash
su -c "/usr/local/mono/bin/mono /usr/local/jackett/share/jackett/JackettConsole.exe" - jackett
```

I was also able to get it going if I replace /var/packages/jackett/scripts/start-stop-status with a bash script like this
```bash
#!/bin/sh

# Package
PACKAGE="jackett"
DNAME="Jackett"

# Others
INSTALL_DIR="/usr/local/${PACKAGE}"
MONO_DIR="/usr/local/mono"
PATH="${INSTALL_DIR}/bin:${MONO_DIR}/bin:${PATH}"
USER="jackett"
MONO="${MONO_DIR}/bin/mono"
APPSERVER="${INSTALL_DIR}/share/jackett/JackettConsole.exe"
# CFG_FILE="${INSTALL_DIR}/var/.config/Jackett/ServerConfig.json"
PID_FILE="${INSTALL_DIR}/var/jackett.pid"
LOG_FILE="${INSTALL_DIR}/var/.config/Jackett/log.txt"


start_daemon ()
{
    su - ${USER} -c "PATH=${PATH} nohup ${MONO} ${APPSERVER} --PIDFile ${PID_FILE} --NoRestart &>> ${LOG_FILE} &"
}

stop_daemon ()
{
    kill `cat ${PID_FILE}`
    wait_for_status 1 20 || kill -9 `cat ${PID_FILE}`
    rm -f ${PID_FILE}
}

daemon_status ()
{
    if [ -f ${PID_FILE} ] && kill -0 `cat ${PID_FILE}` > /dev/null 2>&1; then
        return
    fi
    rm -f ${PID_FILE}
    return 1
}

wait_for_status ()
{
    counter=$2
    while [ ${counter} -gt 0 ]; do
        daemon_status
        [ $? -eq $1 ] && return
        let counter=counter-1
        sleep 1
    done
    return 1
}


case $1 in
    start)
        if daemon_status; then
            echo ${DNAME} is already running
        else
            echo Starting ${DNAME} ...
            start_daemon
        fi
        ;;
    stop)
        if daemon_status; then
            echo Stopping ${DNAME} ...
            stop_daemon
        else
            echo ${DNAME} is not running
        fi
        ;;
    status)
        if daemon_status; then
            echo ${DNAME} is running
            exit 0
        else
            echo ${DNAME} is not running
            exit 1
        fi
        ;;
    log)
        echo ${LOG_FILE}
        ;;
    *)
        exit 1
        ;;
esac
```

**Comment by mctinker** [comment]
I am having the same issue. 

I tried your shell command, but get "Permission denied" using my admin password.  Any clues?

**Comment by mctinker** [comment]
Never mind.  Logged in a root and this fixed my problem.  Thanks for the workaround!

**Comment by kaso17** [comment]
Is this still a problem?

**Comment by mctinker** [comment]
It certainly is for me.  The only way I can get Jackett to start is via ssh as root (per top post): su -c "/usr/local/mono/bin/mono /usr/local/jackett/share/jackett/JackettConsole.exe" - jackett

I tried replacing the start-stop-status script with the one above, but that doesn't work for me either...just via the above su command.

**Comment by kaso17** [comment]
@mctinker which syno package version are you using?
Possible related syno issue:
https://github.com/SynoCommunity/spksrc/issues/3071

**Comment by lrafagnin** [comment]
@kaso17 probably related. Issues started last week, the uninstall/reinstall seemed to work, but only for a day or two, and then the problem was back, hence why I opened this ticket.
I'll try installing the latest version to confirm if the issue has been fixed.

**Comment by mctinker** [comment]
I'm running Version 0.8.496.0

**Comment by kaso17** [comment]
So after reinstalling it works and then after some time (maybe 24 hours?) it stops working?
After 24 hours jackett will check for updates and update itself. maybe that's breaking in your case.
Can you please try to reinstall, then click on the "Check for Updates" button in the jackett UI.
After a few seconds jackett should be updated to the latest version (>=v0.8.555).
If it just dies with the latest packages please post the synology logs ("View logs" in the package manager)

**Comment by mctinker** [comment]
Update failed fore me...probably because I started it via su script.

Uninstall and re-install fixed the autostart for me for now.  Will post if future problem arises.

Anyway to backup and restore pre-defined indexers?

**Comment by mctinker** [comment]
After a Synology recycle, Jackett again does not start automatically or by manual start via Package Center.  It only starts with su command, per top post.  Running Version 0.8.562.0 .

**Comment by kaso17** [comment]
I'm confused by the various syno jackett packages out there.
Where did you get the package from?
Which version is shown in the syno package manager (not jackett UI)?

**Comment by kaso17** [comment]
If I remember correctly the config is stored at /usr/local/jackett/var/ on syno.

**Comment by mctinker** [comment]
I get the beta version via Synology Package Center (Community selection).  The version that appears in the Package Center is: 0.7.1483-4 ... which doesn't jive at all with what the Jackett GUI says. 

I uninstalled and reinstalled, and then updated the version from within the Jackett GUI.  After an hour or two, Package Center says it has stopped, but it is still running.  Woaw!  I am clueless as to what is happening.

Thanks for the pointer to the configuration file.

**Comment by ward0** [comment]
i think its releated to the version of mono you are running, what mono version do you have in package center?

**Comment by mctinker** [comment]
Package Center says that the mono version is 4.6.2.7-8  .

**Comment by ward0** [comment]
@mctinker Yep, have the same version of Mono and having the same issues like you have.

**Comment by kaso17** [comment]
The DSM 6.1 update broke the jackett package. 
There are some updated jackett syno packages here: which should make it work on DSM 6.1 again https://github.com/Jackett/Jackett/releases/tag/v0.8.490

There should be official new packages soon too, see https://github.com/SynoCommunity/spksrc/pull/3070

You should update mono to 5.4 too, see https://github.com/SynoCommunity/spksrc/issues/2808

**Comment by ward0** [comment]
@kaso17 : the Mono5.4 build is not released? I mean my mono package in Synology is not asking for an update...

**Comment by kaso17** [comment]
@ward0 apparently it's been merged but packages haven't been build yet. The links in the thread with the pre-release packages are down too. please ask in the Syno thread when it will be release or where to download the pre-release packages.

**Comment by mctinker** [comment]
I just installed the Mono version 5 update on Synology, and Jackett auto-started fine for the first since I started having problems.  I will keep an eye on this and will report back in a couple of days.

**Comment by ward0** [comment]
@mctinker I have mono5 aswell now and jackett works. Still can't fire up sonar

**Comment by mctinker** [comment]
I'm having no problem with Sonar (version 2.0.0.5085).  It is showing mono version 5.4.1.6.  Jackett now starts and stays running without a problem.
