### ISSUE TITLE
[limetorrents] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by neuman1812** [Jackett/Jackett#2338]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  Jackett Version 0.8.423.0

Mono version (if not using Windows):  

Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  armel,vfp+hard
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

-------------------------------
Limetorrents Fail test.  No results.  

Dec 29 13:12:54 media mono[22929]:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 29 13:12:54 media mono[22929]:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 29 13:12:54 media mono[22929]:   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 29 13:12:54 media mono[22929]:   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 29 13:12:54 media mono[22929]:   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 29 13:12:54 media mono[22929]:   at System.Web.Http.Filters.AuthorizationFilterAttribute+<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext () [0x00109] in <f99f496cb0d249c1a945c1fcabce1695>:0
Dec 29 13:12:54 media mono[22929]: --- End of stack trace from previous location where exception was thrown ---
Dec 29 13:12:54 media mono[22929]:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 29 13:12:54 media mono[22929]:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 29 13:12:54 media mono[22929]:   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 29 13:12:54 media mono[22929]:   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 29 13:12:54 media mono[22929]:   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
Dec 29 13:12:54 media mono[22929]:   at System.Web.Http.Controllers.ExceptionFilterResult+<ExecuteAsync>d__0.MoveNext () [0x00097] in <f99f496cb0d249c1a945c1fcabce1695>:0

**Comment by garfield69** [comment]
similar to #2309 
I suggest upgrading your mono 4.6 to the latest version **5.4**, and Jackett to the latest version **v0.8.539**, as your current mono is unlikely to be able to handle the current limetorrents certificate

**Comment by neuman1812** [comment]
Thanks,  I was unaware of the updates.  Will try.

**Comment by neuman1812** [comment]
Updated mono and Jackett.  But I was still getting the error,  however based on @garfield69  comment over in #2309 ,  I removed and readded Lime torrents and it passed the test. 

Thank you all.
