### ISSUE TITLE
[HDChina]Request to Jackett server failed

### ISSUE THREAD

**Issue by bimzcy** [Jackett/Jackett#2339]
Can not add indexer of HDChina, it keep saying Request to Jackett server failed.

**Comment by bimzcy** [comment]
Here is the log: 
[log.txt](https://github.com/Jackett/Jackett/files/1594222/log.txt)

**Comment by kaso17** [comment]
domain change, fixed via 7309e6a694c38bccdd17e2b63360b31d177c0aab
