### ISSUE TITLE
[carpathians] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by GroupMaster** [Jackett/Jackett#2341]
unable to add Carpathians. 
 An error occured while updating this indexer
Login Failed, got redirected

Jackett Version 0.8.539.0
Windows 7

**Comment by garfield69** [comment]
Have you tried accessing the Carpathians site directly and are you able to login?
If you have a valid username and password and you can login to Carpathians directly, but not via Jackett, then please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.

**Comment by kaso17** [comment]
works fine for me...

**Comment by GroupMaster** [comment]
Yeah, there was a typo... I just carefully repeated it and it works. I
guess i need to go back you keyboarding 101. Thanks for the time. Happy New
Year!!!!
