### ISSUE TITLE
[infinityt] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by dotpower** [Jackett/Jackett#2347]

**Comment by kaso17** [comment]
Apparently caused by some cloudflare changes

**Comment by DontCallMeLarry** [comment]
I have the same problem but I don't get much useful log information even with enhanced logging.

 Error | Exception in test_indexer

**Comment by dotpower** [comment]
Ok, they are being DDoS attacked on a regular basis atm. And the cloudflare DDoS must be blocking the API hits.

**Comment by dotpower** [comment]
DDoS prevention*

**Comment by kaso17** [comment]
It's caused by a recent cloud flare change, pull request to fix it is already pending:
https://github.com/elcattivo/CloudFlareUtilities/pull/21

**Comment by kaso17** [comment]
fixed via 05a9e96bbb2f7c6bdba36104979842ce6ec1883d but it seems like the tracker shutdown
