### ISSUE TITLE
[REQ] Nordicbits

### ISSUE THREAD

**Issue by samip5** [Jackett/Jackett#2348]
Would it be possible to get this tracker added?

I don't know enough HTML/PHP/CSS to be able to add it myself.

Full URL: https://nordicb.org

**Comment by samip5** [comment]
Any progress?

**Comment by kaso17** [comment]
I don't think anyone is working on this.
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by samip5** [comment]
@kaso17 Unfortunately that site is awful with the browse.php categorias as they are not following any standards.

**Comment by samip5** [comment]
@kaso17, could you maybe help a bit?

If the browse.php requires this much after it when searching for TV Content (All categorys, including 4K), how should I go about making the defination file and can I get in touch with you with some live chat perhaps?

`browse2.php?cats2[]=48&cats2[]=57&cats2[]=11&cats2[]=7&cats2[]=31&cats2[]=30&cats2[]=32&cats2[]=5&cats2[]=66&search=&searchin=title&incldead=0`

P.S Searching with IMDB ID is not possible.

**Comment by kaso17** [comment]
the browse2.php/cats2 think seems to be a custom modifications. You'll need something like this in the search/inputs section to deal with the categories:
`$raw: "{{range .Categories}}cats2[]={{.}}&{{end}}"`

**Comment by samip5** [comment]
What if the cats2 changes?

For movies it's cat1 for example, and depends on category?

**Comment by kaso17** [comment]
I'm on discord, please ask your questions here or there

**Comment by hallengreenn** [comment]
So I also took a look at this.
I think this site and Norbits site is very familiar to each other.
The only difference is a other use of the category search. 

Ex - 
Norbits - 'main_cat[]=5&sub2_cat[]=42'
Nordicbits - 'cats4[]=4'

As Nordicbits don't have the couchpotato.php API (which Norbits don't have either), we can work with the browser manipulation to get the catagorys and search.

I have changed the .cs of Nordicbits and inserted all the catagorys - however I am unable to test this until next week.
We may need to change the Performquery to match the output of that site.

Feel free to test -
Nordicbits.cs - https://pastebin.com/R98HU6tD
ConfigurationDataNordicbits.cs - https://pastebin.com/cmwuJsCZ

**Comment by samip5** [comment]
@hallengreenn I can verify that login works, but please see the log at https://pastebin.com/EtHwHKvi.

**Comment by hallengreenn** [comment]
Hello again,
So I am not the big github guy, but I have tested the code today and made some adjustments to the code above and have a working copy now.
You can test it here - https://github.com/Jackett/Jackett/pull/3552

Best regards 
H

**Comment by samip5** [comment]
@hallengreenn Yes, I can verify that it works at least manually from Jackett interface. Will need to try it in production-like usage.

**Comment by samip5** [comment]
Closed as of #3552 was merged.

**Comment by garfield69** [comment]
https://nordicb.org/ returning ERR_CONNECTION_REFUSED
http://nordicb.org/ returning namecheap home page

**Comment by samip5** [comment]
Their domain has expired.

**Comment by RoloSoze** [comment]
The domain is back online but I'm getting the following error message: 
`Exception (nordicbits): No connection could be made because the target machine actively refused it`

Are people also getting this?

**Comment by garfield69** [comment]
Working for me now.
double check your sitelink is `https://nordicb.org/`

**Comment by RoloSoze** [comment]
> `https://nordicb.org/`

That's the one I have; not sure what the problem is. I'll wait for a few hours and if it's not resolved, I'll open a new issue.

**Comment by RoloSoze** [comment]
https://github.com/Jackett/Jackett/issues/8333

**Comment by ngosang** [comment]
https://nordicb.org/

Site down. https://www.uptrends.com/tools/uptime

**Comment by ilike2burnthing** [comment]
The rumor is that the site's owner was arrested in Spain.
Quote from another forum (translated in English):
```
I was part of the staff at NB, and late the day before yesterday we were told that the "owner" had been taken by Spanish police, no one had heard from him for a few days before that. And one of the others had gotten a phone call with the message to close the site.
So for security reasons the site was deleted, so did our discord page.
That's all I know right now
```
https://torrentinvites.org/f31/nordicbits-news-580496/

**Comment by samip5** [comment]
More information obtained from IRC:
![Nordicb_Down_For_Good](https://user-images.githubusercontent.com/1703002/94469187-553ec580-01ce-11eb-8d4b-49900a7ed71b.png)
