### ISSUE TITLE
[xthor] Exception (xthor): Passkey not found in tracker's database: Parse error (Config)

### ISSUE THREAD

**Issue by giopas** [Jackett/Jackett#2349]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
Have you logged onto the site directly and confirmed that your passkey is valid?

**Comment by giopas** [comment]
I have just discovered that you need to manually download a file to obtain the passkey. The info is available in the GB version of the FAQ. Apologize for the report.
