### ISSUE TITLE
[morethantv] Exception (morethantv): Request to https://www.morethan.tv/torrents.php?searchstr=

### ISSUE THREAD

**Issue by screwfaze** [Jackett/Jackett#2350]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.

**Comment by screwfaze** [comment]
Hi @garfield69 can I PM you the log as I don't want to post that on an open forum.

Thanks

**Comment by garfield69** [comment]
Sure. Please sent to kaso1717 -at- gmail.com thanks.

**Comment by screwfaze** [comment]
I have sent the logs please let me know if you need anything else.

Thanks

**Comment by kaso17** [comment]
Potentially might be caused by the cloud flare cookie bug. Please try removing/reading MTV.

**Comment by screwfaze** [comment]
Thanks mate this is working now appreciate your help.
