### ISSUE TITLE
[REQ] Ability to disable password

### ISSUE THREAD

**Issue by kmlucy** [Jackett/Jackett#2351]
Jackett version:  0.8.539.0
Mono version (if not using Windows):  5.4.1.6
-------------------------------

I use nginx's auth request module for SSO for various services, and I would like to use it for Jackett as well. I havie not found any way to completely disable to the admin password to make that possible, however. 

Could an option to disable the password be added? Or does it already exist and I just missed it?

**Comment by garfield69** [comment]
If a password has been previously set, then clearing the password field and clicking on the *Set Password* button on the Jackett Dashboard is supposed to disable the password option.    
But a test I performed on 0.8.539 just now, shows that once a password has been set, even if it is subsequently cleared and saved, still causes the Jackett Dashboard to present a login challenge, which I don't think is supposed to happen, @kaso17 is this correct?

In the mean time @kmicki , you can remove the password using the following method:      
1. stop jackett, 
2. edit the ~/.config/Jackett/ServerConfig.json file and change the AdminPassword line to this:     
`  "AdminPassword": null,`
3. Start jackett again and there should be no password.

**Comment by kmlucy** [comment]
That worked perfectly, thank you very much!

**Comment by kaso17** [comment]
fixed via 61d1c02961c5cbad69ab83fcd23e5737318766e3

**Comment by ReenigneArcher** [comment]
@garfield69 Where is this ServerConfig.json file on Windows? I have been searching for an hour and can't find it.

**Comment by garfield69** [comment]
`%ProgramData%\Jackett`
