### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Request to https://yggtorrent.com/torrents/today?category=2145 failed (Error BadGateway) - The tracker seems to be down.: Request to https://yggtorrent.com/torrents/today?category=2145 failed (Error BadGateway) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by florian-perez** [Jackett/Jackett#2352]
YggTorrent test not working anymore. Below are the enhanced logs. Thank you in advance.

When | Level | Message
-- | -- | --
Jan 01, 2018 06:21:33 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
Jan 01, 2018 06:21:33 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
Jan 01, 2018 06:21:33 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Jan 01, 2018 06:21:33 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
Jan 01, 2018 06:21:33 PM | Info | HttpActionBinding ExecuteBindingAsync
Jan 01, 2018 06:21:33 PM | Info | HttpActionBinding ExecuteBindingAsync
Jan 01, 2018 06:21:33 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Jan 01, 2018 06:21:33 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Jan 01, 2018 06:21:33 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
Jan 01, 2018 06:21:33 PM | Info | ApiControllerActionSelector SelectAction
Jan 01, 2018 06:21:33 PM | Info | ServerConfigurationController ExecuteAsync
Jan 01, 2018 06:21:33 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ServerConfigurationController
Jan 01, 2018 06:21:33 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ServerConfigurationController
Jan 01, 2018 06:21:33 PM | Info | DefaultHttpControllerActivator Create
Jan 01, 2018 06:21:33 PM | Info | HttpControllerDescriptor CreateController
Jan 01, 2018 06:21:33 PM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
Jan 01, 2018 06:21:33 PM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
Jan 01, 2018 06:21:33 PM | Info | http://192.168.1.14:9117/api/v2.0/server/logs?_=1514827283578
Jan 01, 2018 06:21:26 PM | Info | IndexerApiController Dispose
Jan 01, 2018 06:21:26 PM | Info | IndexerApiController Dispose
Jan 01, 2018 06:21:26 PM | Info | Content-type='application/json; charset=utf-8', content-length=16528
Jan 01, 2018 06:21:26 PM | Info | IndexerApiController ExecuteAsync
Jan 01, 2018 06:21:26 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Jan 01, 2018 06:21:26 PM | Error | {0}
Jan 01, 2018 06:21:26 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Jan 01, 2018 06:21:26 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Jan 01, 2018 06:21:26 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Jan 01, 2018 06:21:26 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Jan 01, 2018 06:21:26 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Test()'
Jan 01, 2018 06:21:26 PM | Error | ApiControllerActionInvoker InvokeActionAsync
Jan 01, 2018 06:21:26 PM | Error | ReflectedHttpActionDescriptor ExecuteAsync
Jan 01, 2018 06:21:26 PM | Debug | WebClient(UnixLibCurlWebClient): Returning BadGateway => <!DOCTYPE html>     <html class="no-js" lang="en-US">  <head> <title>yggtorrent.com \| 502: Bad gateway</title> <meta charset="UTF-8" /> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /> <meta name="robots" content="noindex, nofollow" /> <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" /> <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />  <style type="text/css">body{margin:0;padding:0}</style>  <script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script> <script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script> </head> <body><div id="cf_alert_div" style="margin: 0;padding: 0;position: relative;top: 0;left: 0;display: block; z-index: 1000"><div style="margin: 0px;padding: 10px;border-bottom: 1px solid #a5a5a5;background: #f0f0f0;font-weight: normal;text-align: left;"><table width="100%"><tr><td valign="top"><a href="#" onclick="document.cookie='cf_use_ob=0;path=/';window.location.reload();return false;" style="margin: 0 20px 0 0;padding: 10px 0 0 20px;text-decoration: none;font: 12px Helvetica,Arial,sans-serif;color: #eff7e8;font-weight: bold;text-align: left;position: relative;display: inline-block;height: 38px;background: url(/cdn-cgi/images/retry.png) no-repeat 0 0;overflow: visible;font-size: 14px;line-height: 1.2em;text-shadow: #437b0a 0 1px 0;white-space: nowrap;">Retry for a live version<span style="margin: 0;padding: 0;position: absolute;top: 0;left: 100%;width: 20px;height: 38px;background: url(/cdn-cgi/images/retry.png) no-repeat 100% -38px;"></span></a> <noscript style="margin: 10px 0 10px 0;padding: 0;font: 12px Helvetica,Arial,sans-serif;color: #404040;display: block;">(Enable Javascript first.)</noscript></td><td valign="middle" style="margin: 0;padding: 0;"><p style="margin: 0 0 0 20px;padding: 0;font: 12px Helvetica,Arial,sans-serif;color: #404040;">This page (<a href="/torrents/today?category=2145" style="margin: 0;padding: 0;text-decoration: underline;font: 12px Helvetica,Arial,sans-serif;color: #007ed9;font-weight: normal;text-align: left;">https://yggtorrent.com/torrents/today?category=2145</a>) is currently offline. However, because the site uses Cloudflare's Always Online&trade; technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. <span id="caption" style="margin: 0;padding: 0;color: #a5a5a5;">Always Online&trade; is powered by <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=ao_banner" target="_blank" style="margin: 0;padding: 0;text-decoration: underline;font: 12px Helvetica,Arial,sans-serif;color: #007ed9;font-weight: normal;text-align: left;">Cloudflare</a> \| <a href="javascript:void(null);" onclick="document.getElementById('cf_alert_div').style.display='none';" style="margin: 0;padding: 0;text-decoration: underline;font: 12px Helvetica,Arial,sans-serif;color: #007ed9;font-weight: normal;text-align: left;">Hide this Alert</a></span></p></td></tr></table></div></div> <div id="cf-wrapper"> <div id="cf-error-details" class="cf-error-details-wrapper"> <div class="cf-wrapper cf-error-overview"> <h1> <span class="cf-error-type" data-translate="error">Error</span> <span class="cf-error-code">502</span> <small class="heading-ray-id">Ray ID: 3d6727aaabdf6926 &bull; 2018-01-01 17:21:26 UTC</small> </h1> <h2 class="cf-subheadline" data-translate="error_desc">Bad gateway</h2> </div> <div class="cf-section cf-highlight cf-status-display"> <div class="cf-wrapper"> <div class="cf-columns cols-3"> <div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status "> <div class="cf-icon-error-container"> <i class="cf-icon cf-icon-browser"></i> <i class="cf-icon-status cf-icon-ok"></i> </div> <span class="cf-status-desc" data-translate="browser_desc">You</span> <h3 class="cf-status-name" data-translate="browser_label">Browser</h3> <span class="cf-status-label" data-translate="browser_status_label">Working</span> </div> <div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status "> <div class="cf-icon-error-container"> <i class="cf-icon cf-icon-cloud"></i> <i class="cf-icon-status cf-icon-ok"></i> </div> <span class="cf-status-desc" data-translate="cloud_desc">Paris</span> <h3 class="cf-status-name" data-translate="cloud_label">Cloudflare</h3> <span class="cf-status-label" data-translate="cloud_status_label">Working</span> </div> <div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source"> <div class="cf-icon-error-container"> <i class="cf-icon cf-icon-server"></i> <i class="cf-icon-status cf-icon-error"></i> </div> <span class="cf-status-desc" data-translate="server_desc">yggtorrent.com</span> <h3 class="cf-status-name" data-translate="server_label">Host</h3> <span class="cf-status-label" data-translate="server_status_label">Error</span> </div> </div> </div> </div> <div class="cf-section cf-wrapper"> <div class="cf-columns two"> <div class="cf-column"> <h2 data-translate="what_happened">What happened?</h2> <p>The web server reported a bad gateway error.</p> </div> <div class="cf-column"> <h2 data-translate="what_can_i_do">What can I do?</h2> <p data-translate="try_again_in_a_few">Please try again in a few minutes.</p> </div> </div> </div> <div class="cf-error-footer cf-wrapper"> <p> <span class="cf-footer-item">Cloudflare Ray ID: <strong>3d6727aaabdf6926</strong></span> <span class="cf-footer-separator">&bull;</span> <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 2a01:cb19:8693:f800:211:32ff:fe32:ca1b</span> <span class="cf-footer-separator">&bull;</span> <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span> </p> </div> </div> </div>
Jan 01, 2018 06:21:25 PM | Debug | WebClient(UnixLibCurlWebClient).GetString(Url:https://yggtorrent.com/torrents/today?category=2145)
Jan 01, 2018 06:21:25 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
Jan 01, 2018 06:21:25 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Test()'
Jan 01, 2018 06:21:25 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync
Jan 01, 2018 06:21:25 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Test()'
Jan 01, 2018 06:21:25 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Jan 01, 2018 06:21:25 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()'
Jan 01, 2018 06:21:25 PM | Info | HttpActionBinding ExecuteBindingAsync
Jan 01, 2018 06:21:25 PM | Info | HttpActionBinding ExecuteBindingAsync
Jan 01, 2018 06:21:25 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Jan 01, 2018 06:21:25 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Jan 01, 2018 06:21:25 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Test()'
Jan 01, 2018 06:21:25 PM | Info | ApiControllerActionSelector SelectAction
Jan 01, 2018 06:21:25 PM | Info | IndexerApiController ExecuteAsync
Jan 01, 2018 06:21:25 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.IndexerApiController
Jan 01, 2018 06:21:25 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.IndexerApiController
Jan 01, 2018 06:21:25 PM | Info | DefaultHttpControllerActivator Create
Jan 01, 2018 06:21:25 PM | Info | HttpControllerDescriptor CreateController

Jackett version:  0.8.539.0
Mono version (if not using Windows):  4.6.2.7-8

-------------------------------

**Comment by garfield69** [comment]
Your log seems to indicate that the site was offline when you did your test.
Using windows Jackett 0.8.539 I had no problems accessing yggtorrent just now.
So try again.
If it is still not working for you, consider upgrading your Mono 4.6 to the latest version 5.4
Let us know how you go.

**Comment by florian-perez** [comment]
Thank you, I already checked when I tested and the tracker was running despite the error. I retried today and the problem is still the same. I requested a Mono Package 5.4 for my platform (DSM 6.1, DS415Play, AtomCE5335) because only 4.6 is available in the packetcenter or [here](https://github.com/Safihre/spksrc/releases/tag/mono-5-dsm61).

**Comment by florian-perez** [comment]
Installed the 5.4 Mono Package, restarted and everything is working fine. Thank you for the help.
