### ISSUE TITLE
[HD-Torrents] Missing 4k categories

### ISSUE THREAD

**Issue by MateEke** [Jackett/Jackett#2353]
Jackett version:  latest docker image (0.8.539.0)

-------------------------------

There is no category mapped for
- Movie/UHD/Remux
- Movie/UHD/Blu-Ray
HD-Torrents categories.

Movie/2160p category is mapped as 'Movies/HD', but I think it should be 'Movies/UHD' (2045). 

I think 'Movie/UHD/Blu-Ray' should be mapped as 'Movies/BluRay' (2050) or 'Movies/UHD' (2045),
and 'Movie/UHD/Remux' should be mapped as 'Movies/UHD' (2045).

I haven't checked series categories yet, but maybe it should be checked too.

![jackett-valerian](https://user-images.githubusercontent.com/11072174/34479458-595f518e-efa7-11e7-9383-d8dd30197fd3.PNG)

**Comment by kaso17** [comment]
fixed via 1a803fb1826f64747d1fc3305ace73d9ae64abd7 + 8773022f10319a84fa849aa0af961cb7d3e516e4 + 87584668ddd529eefdd2f5f4d1e5a84da4f839be
