### ISSUE TITLE
[Karagarga] Dates not working

### ISSUE THREAD

**Issue by drewbitt** [Jackett/Jackett#2357]
01-02 19:37:01 Debug Error while parsing DateTime "Aug 27 08", using layout "Jan 02 06" (MMM dd yy): String was not recognized as a valid DateTime

Does so for all dates. Dates are in formats like May 27 '17 where we remove the '. Looks okay to me, and didn't fix if I appended time / time zone.

**Comment by garfield69** [comment]
Check the HTML source. Could the spaces in between the date-values be *white-spaces* ?
perhaps adding this filter prior to the dateparse helps?
```yaml
      - name: re_replace
        args: ["[^a-zA-Z0-9]+", " "]
```

**Comment by drewbitt** [comment]
Yup, that fixed it. Didn't think of that. Thanks
