### ISSUE TITLE
[frozenlayer] Exception (frozenlayer): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /build/mono-5.4.1.6/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by LoveOFF** [Jackett/Jackett#2361]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
FrozenLayer's certificate expired on the 18th Dec 2017
![image](https://user-images.githubusercontent.com/6933240/34546840-a142a09a-f15b-11e7-8d5c-6f7ab36872c7.png)

**Comment by garfield69** [comment]
@kaso17  when coding a `certificate:` statement for the yaml definition, which part of the certificate do I use for the hex string, the serial number, the thumbprint, some other part?
Also is that string case sensitive, or does it need to be uppercase?

**Comment by kaso17** [comment]
Fixed via 5ef4e2f0ddde1c3a27f8ebd88822228f51d8ad82
@garfield69 it's the thumbprint, case doesn't matter
In your case it seems like you've avast installed which hijacks your TLS connections, the thumbprint of the real certificate is needed.
