### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /build/mono-5.4.1.6/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by JonBrune** [Jackett/Jackett#2362]
I have search other issues and seen similar problem as I have. 
I have already done:
**
This is often caused by missing CA certificates.
Try reimporting the certificates:

On Linux (as user root): wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin
On macOS: curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin
**
Iḿ not sure what I can do now but im running jackett on unraid.

Jackett version: 0.8.539.0
Mono version (if not using Windows):  5.4.1.6

-------------------------------

**Comment by garfield69** [comment]
Did you remember to recycle Jackett or rebooted your system after updating your certificates?

**Comment by JonBrune** [comment]
Yes I did

**Comment by garfield69** [comment]
@kaso17  whats the next step in the problem diagnosis checklist in this situation?

**Comment by kaso17** [comment]
Is it running in a jail or some other kind of environment isolation? Then you've to run the certificate commands inside the jail too.

**Comment by JonBrune** [comment]
Im running it dockers and i did run the commands there. But it has been fixed now, I dont know what freally fixed it but I updated the OS and jackett, after that it worked
