### ISSUE TITLE
Additional option in MVGroup to strip "BBC." from front of torrent name

### ISSUE THREAD

**Issue by SirSilent** [Jackett/Jackett#2367]
Would it be possible to add another option in the MVGroup trackers to strip "BBC." from the front of the torrent name? This would help match with TheTVDB as they don't prefix their series names.

I did have a look through but I'm not a developer and see some trackers do some stripping, but not in the same place as MVGroup has files so I can't do it myself unfortunately.

It could also be a global setting, since it isn't the only tracker effected but as MVGroup has the largest BBC library it would help the most.

**Comment by kaso17** [comment]
Should be possible. @garfield69 what's your opinion?

**Comment by garfield69** [comment]
The next release of Jackett should include 29b8375 which strips "BBC " from the front of all the search result titles for the mvgroup definitions.

**Comment by thunderousleader10** [comment]
Could we do a similar thing for Channel 5 which is prefixed at the start of torrent names as CH5?

**Comment by garfield69** [comment]
>Could we do a similar thing for Channel 5 which is prefixed at the start of torrent names as CH5?

I'll add it to the BBC checkbox in the next release.

**Comment by garfield69** [comment]
v0.17.790
