### ISSUE TITLE
[Private] FunFile.org

### ISSUE THREAD

**Issue by malelan** [Jackett/Jackett#237]
happy to produce account for funfile for anyone that is interested in integration.

**Comment by JigSawFr** [comment]
Please read wiki : https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker
Before requesting a new tracker :hand: 
Thanks you

**Comment by malelan** [comment]
sorry for not reading that in typical fashion.  see below:

AddCategoryMapping("4", TorznabCatType.Console);
AddCategoryMapping("4", TorznabCatType.ConsoleNDS);
AddCategoryMapping("4", TorznabCatType.ConsolePSP);
AddCategoryMapping("4", TorznabCatType.ConsoleWii);
AddCategoryMapping("4", TorznabCatType.ConsoleXbox);
AddCategoryMapping("4", TorznabCatType.ConsoleXbox360);
AddCategoryMapping("4", TorznabCatType.ConsoleWiiwareVC);
AddCategoryMapping("4", TorznabCatType.ConsoleXBOX360DLC);
AddCategoryMapping("4", TorznabCatType.ConsolePS3);
AddCategoryMapping("4", TorznabCatType.ConsoleOther);
AddCategoryMapping("4", TorznabCatType.Console3DS);
AddCategoryMapping("4", TorznabCatType.ConsolePSVita);
AddCategoryMapping("4", TorznabCatType.ConsoleWiiU);
AddCategoryMapping("4", TorznabCatType.ConsoleXboxOne);
AddCategoryMapping("4", TorznabCatType.ConsolePS4);
AddCategoryMapping("19", TorznabCatType.Movies);
AddCategoryMapping("19", TorznabCatType.MoviesForeign);
AddCategoryMapping("19", TorznabCatType.MoviesOther);
AddCategoryMapping("19", TorznabCatType.MoviesSD);
AddCategoryMapping("19", TorznabCatType.MoviesHD);
AddCategoryMapping("19", TorznabCatType.Movies3D);
AddCategoryMapping("19", TorznabCatType.MoviesBluRay);
AddCategoryMapping("19", TorznabCatType.MoviesDVD);
AddCategoryMapping("19", TorznabCatType.MoviesWEBDL);
AddCategoryMapping("6", TorznabCatType.Audio);
AddCategoryMapping("6", TorznabCatType.AudioMP3);
AddCategoryMapping("6", TorznabCatType.AudioVideo);
AddCategoryMapping("6", TorznabCatType.AudioVideo);
AddCategoryMapping("43", TorznabCatType.AudioAudiobook);
AddCategoryMapping("6", TorznabCatType.AudioLossless);
AddCategoryMapping("6", TorznabCatType.AudioOther);
AddCategoryMapping("6", TorznabCatType.AudioForeign);
AddCategoryMapping("22", TorznabCatType.PC);
AddCategoryMapping("22", TorznabCatType.PC0day);
AddCategoryMapping("22", TorznabCatType.PCISO);
AddCategoryMapping("22", TorznabCatType.PCMac);
AddCategoryMapping("31", TorznabCatType.PCPhoneOther);
AddCategoryMapping("4", TorznabCatType.PCGames);
AddCategoryMapping("31", TorznabCatType.PCPhoneIOS);
AddCategoryMapping("31", TorznabCatType.PCPhoneAndroid);
AddCategoryMapping("7", TorznabCatType.TV);
AddCategoryMapping("7", TorznabCatType.TVWEBDL);
AddCategoryMapping("7", TorznabCatType.TVFOREIGN);
AddCategoryMapping("7", TorznabCatType.TVSD);
AddCategoryMapping("7", TorznabCatType.TVHD);
AddCategoryMapping("7", TorznabCatType.TVOTHER);
AddCategoryMapping("7", TorznabCatType.TVSport);
AddCategoryMapping("44", TorznabCatType.TVAnime);
AddCategoryMapping("7", TorznabCatType.TVDocumentary);
AddCategoryMapping("45", TorznabCatType.XXX);
AddCategoryMapping("45", TorznabCatType.XXXDVD);
AddCategoryMapping("45", TorznabCatType.XXXWMV);
AddCategoryMapping("45", TorznabCatType.XXXXviD);
AddCategoryMapping("45", TorznabCatType.XXXx264);
AddCategoryMapping("45", TorznabCatType.XXXOther);
AddCategoryMapping("45", TorznabCatType.XXXImageset);
AddCategoryMapping("45", TorznabCatType.XXXPacks);
AddCategoryMapping("40", TorznabCatType.Other);
AddCategoryMapping("40", TorznabCatType.OtherMisc);
AddCategoryMapping("40", TorznabCatType.OtherHashed);
AddCategoryMapping("27", TorznabCatType.Books);
AddCategoryMapping("27", TorznabCatType.BooksEbook);
AddCategoryMapping("27", TorznabCatType.BooksComics);
AddCategoryMapping("27", TorznabCatType.BooksMagazines);
AddCategoryMapping("27", TorznabCatType.BooksTechnical);
AddCategoryMapping("27", TorznabCatType.BooksOther);
AddCategoryMapping("27", TorznabCatType.BooksForeign);

**Comment by malelan** [comment]
not sure if this helps, but out of the box sick gear supports funfile and here is a copy of the code from the python module.

`import re
import traceback

from . import generic
from sickbeard import logger, tvcache
from sickbeard.bs4_parser import BS4Parser
from sickbeard.helpers import tryInt
from lib.unidecode import unidecode


class FunFileProvider(generic.TorrentProvider):

    def __init__(self):
        generic.TorrentProvider.__init__(self, 'FunFile')

        self.url_base = 'https://www.funfile.org/'
        self.urls = {'config_provider_home_uri': self.url_base,
                     'login': self.url_base + 'takelogin.php',
                     'search': self.url_base + 'browse.php?%s&search=%s&incldead=0&showspam=1&',
                     'get': self.url_base + '%s'}

        self.categories = {'shows': [7], 'anime': [44]}

        self.url = self.urls['config_provider_home_uri']
        self.url_timeout = 90
        self.username, self.password, self.minseed, self.minleech = 4 * [None]
        self.cache = FunFileCache(self)

    def _authorised(self, **kwargs):

        return super(FunFileProvider, self)._authorised(
            logged_in=(lambda x=None: None is not self.session.cookies.get('uid', domain='.funfile.org') and
                       None is not self.session.cookies.get('pass', domain='.funfile.org')),
            post_params={'login': 'Login', 'returnto': '/'}, timeout=self.url_timeout)

    def _search_provider(self, search_params, **kwargs):

        results = []
        if not self._authorised():
            return results
`

**Comment by malelan** [comment]
just wanted to update that i have sent an invite to jackettapp at gmail dot com , not sure how long it can sit there, no need to work on the code, but try to accept the invite if you can.

**Comment by flightlevel** [comment]
Invite accepted, added to the queue

**Comment by anonymous--** [comment]
just curious how long for the update, I too want this tracker

**Comment by anonymous--** [comment]
Just curious how long before the update, I too wish for this tracker.

**Comment by flightlevel** [comment]
There is a tiny issue with one of the packages we use. It has been fixed now, just waiting for it to get released https://github.com/AngleSharp/AngleSharp/commit/810859244a86f3ca050dfc42eac36e57f38a6238
Probably a few weeks

**Comment by anonymous--** [comment]
Hello just wondering is there any update to when this provider will be added?

**Comment by bskrtich** [comment]
I am interested in this. Has there been any work done on this? If not can I pick it up?

**Comment by kaso17** [comment]
If someone has another invite please send it to kaso1717 @at@ gmail . com and I'll add it.

**Comment by bskrtich** [comment]
@kaso17 Invite sent!

**Comment by kaso17** [comment]
got the invite, thank you.
Implementation looks straight forward.
I'll work on it tomorrow.

**Comment by kaso17** [comment]
Ok, added it in pull request #516
