### ISSUE TITLE
[passthepopcorn] Exception (passthepopcorn): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. (Test)

### ISSUE THREAD

**Issue by Fiala06** [Jackett/Jackett#2376]
Jackett version:  0.8.566.0
Mono version (if not using Windows):  

-------------------------------

Seems like yesterday all my trackers but 2/10 stopped working. 

TL Test: An error occured while testing this indexer
Exception (torrentleech): : 

PTP:  An error occured while testing this indexer
Exception (passthepopcorn): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

MTV:  An error occured while testing this indexer
Found no results while trying to browse this tracker

Doesn't make sense. I've verifed I can log into all ym trackers by visiting their sites. 

![mstsc_2018-01-06_08-07-08](https://user-images.githubusercontent.com/5183146/34641674-84527ba6-f2bc-11e7-9ab7-a3cb03b9459c.png)

![mstsc_2018-01-06_08-07-29](https://user-images.githubusercontent.com/5183146/34641679-976e863a-f2bc-11e7-9b02-fb1b326f3ff1.png)

[log.txt](https://github.com/Jackett/Jackett/files/1608984/log.txt)

**Comment by kaso17** [comment]
Please provide an enhanced (the one attached is a normal one) to clarify it.
Based on the apollo error from the log it looks like your IP got blacklisted by cloudflare (captcha challenge required).

**Comment by Fiala06** [comment]
Thanks turns out Cloudflare Captcha has flagged my IP for some reason. I'm getting them for every website using CF. Guess I'll have to wait it out. Thanks
