### ISSUE TITLE
[yts] Exception (yts): Object reference not set to an instance of an object: Parse error (Test)

### ISSUE THREAD

**Issue by PiscisSwimeatus** [Jackett/Jackett#2378]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
I've see this before when the yts.ag api server is not returning results.
I can get results via Jackett at the moment so have another go.
If it still does not work, then please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.

**Comment by PiscisSwimeatus** [comment]
It have started working again, so closing the issue.
