### ISSUE TITLE
jackett not starting on DSM6.1.4 with mono4.6.2

### ISSUE THREAD

**Issue by ward0** [Jackett/Jackett#2379]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  last release, can't check(not getting jackett started atm)
Mono version (if not using Windows):  4.6.2
-------------------------------

I found related information i think https://github.com/SynoCommunity/spksrc/issues/2808

But i don't know what to do next, i can't fire up jackett, so i can't really make a backup... I can't delete Mono before i deleted jackett/radarr...

i'm kinda stuck :(

**Comment by kaso17** [comment]
dupe #2337
