### ISSUE TITLE
jackett not connecting to iptorrents torrents (http error 404)

### ISSUE THREAD

**Issue by odyseus8** [Jackett/Jackett#2380]
[iptorrents connection error.txt](https://github.com/Jackett/Jackett/files/1609594/iptorrents.connection.error.txt)

I have set up an Unraid platform and use sonarr, jackett and deluge to download files. I have added zamunda and iptorrents as indexers. If I search for any torrent files both indexers return with results. I can download from zamunda without a problem however if I try to download any file from iptorrents; the page can't be connected error pops up with error 404. I use a VPN service for secure connection but I didn't have any problems with other indexers other than iptorrents. Not sure what to change or what to do in order to fix the problem. Also when I try to edit settings of iptorrents, jackett asks for cookie verification. I connect to iptorrents from my personal computer (which is connected to some modem) without a problem and the connection and test settings turn out to be completed in jackett. I would really appreciate if anyone can help. Thanks in advance.
I have added to Jackett error log for further info.

**Comment by kaso17** [comment]
In the log I don't see any download attempts (only successful searches).
Are you using a reverse proxy setup?

**Comment by garfield69** [comment]
no reply. closing.
