### ISSUE TITLE
[zooqle] Exception (zooqle): Request to https://zooqle.com/search?s=dt

### ISSUE THREAD

**Issue by peter-vanderstruys** [Jackett/Jackett#2383]
Jackett version:  566
Mono version (if not using Windows):  4.8.1

-------------------------------

Jan 08, 2018 12:38:21 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
-- | -- | --
Jan 08, 2018 12:38:21 PM | Error | {0}
Jan 08, 2018 12:38:21 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Jan 08, 2018 12:38:21 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Jan 08, 2018 12:38:21 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Jan 08, 2018 12:38:21 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Jan 08, 2018 12:38:21 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Test()'
Jan 08, 2018 12:38:21 PM | Error | ApiControllerActionInvoker InvokeActionAsync
Jan 08, 2018 12:38:21 PM | Error | ReflectedHttpActionDescriptor ExecuteAsync
Jan 08, 2018 12:38:21 PM | Debug | WebClient(UnixLibCurlWebClient): Returning BadGateway => <!DOCTYPE html>     <html class="no-js" lang="en-US">  <head> <title>zooqle.com \| 502: Bad gateway</title> <meta charset="UTF-8" /> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /> <meta name="robots" content="noindex, nofollow" /> <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" /> <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />  <style type="text/css">body{margin:0;padding:0}</style>  <script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script> <script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script> </head> <body><div id="cf_alert_div" style="margin: 0;padding: 0;position: relative;top: 0;left: 0;display: block; z-index: 1000"><div style="margin: 0px;padding: 10px;border-bottom: 1px solid #a5a5a5;background: #f0f0f0;font-weight: normal;text-align: left;"><table width="100%"><tr><td valign="top"><a href="#" onclick="document.cookie='cf_use_ob=0;path=/';window.location.reload();return false;" style="margin: 0 20px 0 0;padding: 10px 0 0 20px;text-decoration: none;font: 12px Helvetica,Arial,sans-serif;color: #eff7e8;font-weight: bold;text-align: left;position: relative;display: inline-block;height: 38px;background: url(/cdn-cgi/images/retry.png) no-repeat 0 0;overflow: visible;font-size: 14px;line-height: 1.2em;text-shadow: #437b0a 0 1px 0;white-space: nowrap;">Retry for a live version<span style="margin: 0;padding: 0;position: absolute;top: 0;left: 100%;width: 20px;height: 38px;background: url(/cdn-cgi/images/retry.png) no-repeat 100% -38px;"></span></a> <noscript style="margin: 10px 0 10px 0;padding: 0;font: 12px Helvetica,Arial,sans-serif;color: #404040;display: block;">(Enable Javascript first.)</noscript></td><td valign="middle" style="margin: 0;padding: 0;"><p style="margin: 0 0 0 20px;padding: 0;font: 12px Helvetica,Arial,sans-serif;color: #404040;">This page (<a href="/search?s=dt&amp;v=t&amp;sd=d&amp;q=%20*" style="margin: 0;padding: 0;text-decoration: underline;font: 12px Helvetica,Arial,sans-serif;color: #007ed9;font-weight: normal;text-align: left;">https://zooqle.com/search?s=dt&amp;v=t&amp;sd=d&amp;q=%20*</a>) is currently offline. However, because the site uses Cloudflare's Always Online&trade; technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. <span id="caption" style="margin: 0;padding: 0;color: #a5a5a5;">Always Online&trade; is powered by <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=ao_banner" target="_blank" style="margin: 0;padding: 0;text-decoration: underline;font: 12px Helvetica,Arial,sans-serif;color: #007ed9;font-weight: normal;text-align: left;">Cloudflare</a> \| <a href="javascript:void(null);" onclick="document.getElementById('cf_alert_div').style.display='none';" style="margin: 0;padding: 0;text-decoration: underline;font: 12px Helvetica,Arial,sans-serif;color: #007ed9;font-weight: normal;text-align: left;">Hide this Alert</a></span></p></td></tr></table></div></div> <div id="cf-wrapper"> <div id="cf-error-details" class="cf-error-details-wrapper"> <div class="cf-wrapper cf-error-overview"> <h1> <span class="cf-error-type" data-translate="error">Error</span> <span class="cf-error-code">502</span> <small class="heading-ray-id">Ray ID: 3d9ac00c580189e0 &bull; 2018-01-07 23:38:21 UTC</small> </h1> <h2 class="cf-subheadline" data-translate="error_desc">Bad gateway</h2> </div> <div class="cf-section cf-highlight cf-status-display"> <div class="cf-wrapper"> <div class="cf-columns cols-3"> <div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status "> <div class="cf-icon-error-container"> <i class="cf-icon cf-icon-browser"></i> <i class="cf-icon-status cf-icon-ok"></i> </div> <span class="cf-status-desc" data-translate="browser_desc">You</span> <h3 class="cf-status-name" data-translate="browser_label">Browser</h3> <span class="cf-status-label" data-translate="browser_status_label">Working</span> </div> <div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status "> <div class="cf-icon-error-container"> <i class="cf-icon cf-icon-cloud"></i> <i class="cf-icon-status cf-icon-ok"></i> </div> <span class="cf-status-desc" data-translate="cloud_desc">Auckland</span> <h3 class="cf-status-name" data-translate="cloud_label">Cloudflare</h3> <span class="cf-status-label" data-translate="cloud_status_label">Working</span> </div> <div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source"> <div class="cf-icon-error-container"> <i class="cf-icon cf-icon-server"></i> <i class="cf-icon-status cf-icon-error"></i> </div> <span class="cf-status-desc" data-translate="server_desc">zooqle.com</span> <h3 class="cf-status-name" data-translate="server_label">Host</h3> <span class="cf-status-label" data-translate="server_status_label">Error</span> </div> </div> </div> </div> <div class="cf-section cf-wrapper"> <div class="cf-columns two"> <div class="cf-column"> <h2 data-translate="what_happened">What happened?</h2> <p>The web server reported a bad gateway error.</p> </div> <div class="cf-column"> <h2 data-translate="what_can_i_do">What can I do?</h2> <p data-translate="try_again_in_a_few">Please try again in a few minutes.</p> </div> </div> </div> <div class="cf-error-footer cf-wrapper"> <p> <span class="cf-footer-item">Cloudflare Ray ID: <strong>3d9ac00c580189e0</strong></span> <span class="cf-footer-separator">&bull;</span> <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 203.118.134.21</span> <span class="cf-footer-separator">&bull;</span> <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span> </p> </div> </div> </div>
Jan 08, 2018 12:38:21 PM | Debug | WebClient(UnixLibCurlWebClient).GetString(Url:https://zooqle.com/search?s=dt&v=t&sd=d&q=%20*)
Jan 08, 2018 12:38:21 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
Jan 08, 2018 12:38:21 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Test()'
Jan 08, 2018 12:38:21 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync
Jan 08, 2018 12:38:21 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Test()'
Jan 08, 2018 12:38:21 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Jan 08, 2018 12:38:21 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()'
Jan 08, 2018 12:38:21 PM | Info | HttpActionBinding ExecuteBindingAsync
Jan 08, 2018 12:38:21 PM | Info | HttpActionBinding ExecuteBindingAsync
Jan 08, 2018 12:38:21 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Jan 08, 2018 12:38:21 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Jan 08, 2018 12:38:21 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Test()'
Jan 08, 2018 12:38:21 PM | Info | ApiControllerActionSelector SelectAction
Jan 08, 2018 12:38:21 PM | Info | IndexerApiController ExecuteAsync
Jan 08, 2018 12:38:21 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.IndexerApiController
Jan 08, 2018 12:38:21 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.IndexerApiController
Jan 08, 2018 12:38:21 PM | Info | DefaultHttpControllerActivator Create
Jan 08, 2018 12:38:21 PM | Info | HttpControllerDescriptor CreateController

**Comment by garfield69** [comment]
The log shows that zooqle was unavailable. I just tried now and can access zooqle with jacket fine. So try again and report your success or failure. Thanks.

**Comment by peter-vanderstruys** [comment]
HI, this is the same also. jackett fails but i can browse the url jackett uses.

https://zooqle.com/search?s=dt&v=t&sd=d&q=%20*

Thanks

**Comment by kaso17** [comment]
Probably the same issue as in #2382

**Comment by peter-vanderstruys** [comment]
Hi, yes it was :)
