### ISSUE TITLE
Cloud flare robot check fails

### ISSUE THREAD

**Issue by manderss99** [Jackett/Jackett#2384]
When connected to a specific vpn node Jackett test fails for all indexers using Cloudflare due to a robot test. Attaching log file.

Jackett version:  0.8.566.0
Mono version (if not using Windows):   5.4.1.6

-------------------------------

[logile.zip](https://github.com/Jackett/Jackett/files/1611425/logile.zip)

**Comment by kaso17** [comment]
then the VPn IP is blacklisted at cloudflare, use another one.

**Comment by manderss99** [comment]
If I log in via a browser on the same vpn connection I get the robot check, I select the checkbox and then I get logged in correctly to the site. 
I would not expect that if the ip was blacklisted?

**Comment by kaso17** [comment]
You get the robot check/captcha because the IP is blacklisted (bad reputation).
Even if we could present the captcha to the user during the configuration (which is no longer possible easily) you've to resolve it every couple of hours (~4) making it not very useful for automated setups.
