### ISSUE TITLE
Always "Found no results while trying to browse this tracker"

### ISSUE THREAD

**Issue by Zhoth** [Jackett/Jackett#2385]
Jackett version:  0.8.500.0
Mono version: 5.4.1.6
System QNap TS219P

Hi guys, I've a problem when I try to test the 2 Italian trackers (Il Corsaro Nero and TNTVillage).
I have attached the log file.

Thanks for your support.
-------------------------------
[log.txt](https://github.com/Jackett/Jackett/files/1612552/log.txt)

**Comment by kaso17** [comment]
please update to the latest jackett version and try again

**Comment by Zhoth** [comment]
@kaso17 I've tried but unfortunately I got the same error. Any idea?

**Comment by kaso17** [comment]
please try running this command and post the output

`csharp -e 'Console.WriteLine (new System.Net.WebClient().DownloadString("https://www.howsmyssl.com/").IndexOf ("1.2"))'`

Where did you the mono version from?

**Comment by Zhoth** [comment]
@kaso17 I've downloaded Mono for my QNap from here: https://qnapclub.eu/it/qpkg/193

The command doesn't work. This is the error:

![immagine](https://user-images.githubusercontent.com/35234113/34789432-867dd422-f63e-11e7-8899-2a1d8f88055f.png)

**Comment by kaso17** [comment]
"NameResolutionFailure" make sure your DNS settings are correct.

**Comment by Zhoth** [comment]
I'm using Google DNS and if I try to do a curl to that URL it works:
![immagine](https://user-images.githubusercontent.com/35234113/34908891-f23c7fb4-f897-11e7-87f0-dcaa05c0d7e5.png)

**Comment by kaso17** [comment]
Then please report this issue to the qnap mono maintainer. If DNS doesn't work via mono but in general does on the system mono seems to be broken for your platform.
