### ISSUE TITLE
[Feature Request] ToTheGlory Security Questions

### ISSUE THREAD

**Issue by drewbitt** [Jackett/Jackett#2386]
Sites like ToTheGlory have options to have security questions you can set up and answer when you login. It's not a captcha since the options are always the same. Does / can Jackett have the ability for security questions like this?

**Comment by kaso17** [comment]
Assuming it's all on the same login page it should be easy to add. If anyone submits a PR it's welcome.

**Comment by garfield69** [comment]
resolved with 23cc0a0
