### ISSUE TITLE
Shazbat Not Working

### ISSUE THREAD

**Issue by MadCat1** [Jackett/Jackett#239]
Jackett seems to add Shazbat correctly because the tests work and Sonarr says the tests work as well but when I do manual searches through sonarr or the automatic searches nothing ever appears, even if I go to the shazbat website to insure the torrent does exist.

**Comment by Azerelat** [comment]
The integration fully supports rss but yes the search is a bit broken but that is mainly as the site doesn't properly support search.  Sonarr will search for certain seasons such as "Certain show S1" or "S1E01" and the site will never return anything for either for those as it will only work with the title of the show then from there you get a list of shows and then you'd also need to go to the torrents or season page for each show which is completely unworkable from our point of view.  We don't want really want to hit their server more than once to get results as most of our requests are automated and for the sake of their servers it hasn't been done.

**Comment by flightlevel** [comment]
This issue hasn't had activity for a while. If the issue still exists, please reopen and include full logs. https://github.com/Jackett/Jackett#troubleshooting
