### ISSUE TITLE
An unknown option was passed in to libcurl setting option SslCtxFunction  

### ISSUE THREAD

**Issue by kimattree** [Jackett/Jackett#2394]
Getting this error in my logs:

01-10 08:52:07 Error Error UnknownTelnetOption Error: An unknown option was passed in to libcurl setting option SslCtxFunction  
01-10 08:52:07 Info Found 3 releases from RARBG for: Beat Shazam S01E14

**Comment by kaso17** [comment]
Please update to mono >= 5.4, then libcurl should no longer be used.
