### ISSUE TITLE
x265 Files Missing from Searches

### ISSUE THREAD

**Issue by wigster** [Jackett/Jackett#2398]
Apologies, but a bit of a noob with Jackett. I am trying to use it with Sonarr on Windows.

For some reason Sonarr/Jackett is filtering out all x265 files in its searches for any of the trackers I've tried (e.g. tpb, rarbg, torrentz2).

When I do a manual search in sonarr, the list of files returned only contains x264 files. These only then get filtered by my tags as insufficient quality etc, which is why I think the issue is with Jackett. 

When I search on the actual torrent search site, there are plenty of x265 sources.

What is going wrong?

Jackett version:  0.8.588.0

**Comment by garfield69** [comment]
no reply, closing.
