### ISSUE TITLE
Sorting by seeds/peers with an additional URI parameter

### ISSUE THREAD

**Issue by itsgarryb** [Jackett/Jackett#2399]
Is it possible to sort search results by seeds (peers) with an additional parameter to the URI request? I guess this involves Torznab since as far as I understand that's the "component" handling the XML responses to the URI search requests.

Ideally I'd like to be able to add something like `sortby=seed` (or `sortbyseed=1` if it's easier) to sort the XML results. It would be awesome! This could also a chance to add some other kind of sorting, if not already available. I can sort the frontend table containing the results without problems, but that's done via browser if I'm not mistaken.

Thanks.

**Comment by kaso17** [comment]
Can you explain your use case? Just sorting the XML results doesn't make much sense to me, would have to pass it to the corresponding indexer too.

**Comment by itsgarryb** [comment]
I would like to use this software to get a list of torrents for a given file.

I would like to have the option to sort the XML results so that I don't have to loop the whole (potentially very large) XML file in order to find, for example, the torrent with the most seeds/peers. In particular, let's say I'd like to quickly retrieve 5 torrents with the most seeds for a given file.

If I could have a sorted XML file, this would be very easy: the first 5 elements of the XML would be what I'm looking for.

Another curiosity: what's the sorting criteria for the returned elements? In other words, how are they sorted by default (if there's a sorting logic at all)?

I have a very limited experience with Jackett, so if there's already a way to do this I'm eager to know! Thanks for your time.

**Comment by garfield69** [comment]
Closed as stale.
