### ISSUE TITLE
Error loading Jackett settings, request to Jackett server failed

### ISSUE THREAD

**Issue by LickABrick** [Jackett/Jackett#240]
I've just installed Jackett and get the error "Error loading Jackett settings, request to Jackett server failed" when I load the page, when I press the 'Logs' (or any other) button I get the error "Request to Jackett server failed". I am however able to change my password (while still giving me the error)

Help would be appreciated.

(Running on Debian Jessie)

**Comment by flightlevel** [comment]
Sounds like Jackett is crashing and then you aren't getting any response.
Any more info from the console if you run
```mono --debug JackettConsole.exe```

**Comment by flightlevel** [comment]
This issue hasn't had activity for a while. If the issue still exists, please reopen and include full logs. https://github.com/Jackett/Jackett#troubleshooting
