### ISSUE TITLE
[nexttorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by antodu44** [Jackett/Jackett#2401]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

Nextorrent become http://www.nextorrent.pro/

-------------------------------

**Comment by garfield69** [comment]
`http://www.nextorrent.pro/` is not using the `recherche/<keywords>` path that `https://www.nextorrent.tv/` previously used, but uses instead `?s=<keywords>` and returns completely different HTML in its search results.
How confident are you that this in fact from the same people, and not someone else's clone?

**Comment by garfield69** [comment]
Does anyone know if nextorrent.pro is the legit replacement for nextorrent.tv?

**Comment by garfield69** [comment]
Well, it looks like nextorrent.tv is gone, I can find their Twitter or Facebook accounts and the domain refuses to connect.
So I've switched this definition to support nextorrent.pro as requested by the OP, with commit 940863a, which will be available with the next (pre)release of Jackett whenever that happens.
