### ISSUE TITLE
High RAM memory usage on Qnap NAS?

### ISSUE THREAD

**Issue by billerr** [Jackett/Jackett#2405]
Jackett version:  0.8.578.0
Mono version (if not using Windows):  4.6.2.7

-------------------------------

Hi! I've searched the forum and the internets for this issue (thinking I'm not the only one experiencing it), but no luck. So I guess it's just me.

I have Jackett installed on a Qnap TS 251+ (through a QnapClub package). It's updated to the latest version, and serving 17 trackers to Sonarr and Radarr on localhost.

However, RAM consumption by Jackett is quite large. After an uptime of a couple of days, RAM usage is on average upward of 700-800MB. On a 2GB machine, this is quite taxing, and slows stuff quite a bit. 

Is this normal behaviour? Is there some setting I can change to mitigate this? Or should I just cut back on trackers?

**Comment by zero77** [comment]
There may be a memory leak with mono because, lots of users of Radarr which also uses mono like Jackett, are reporting high memory usage and some users are suggesting it looks like its down to mono https://github.com/Radarr/Radarr/issues/1580.

**Comment by d1slact0r** [comment]
this can be closed, now netcore is being used.
