### ISSUE TITLE
TorrentHR not returning any results via Jackett

### ISSUE THREAD

**Issue by rusty1281** [Jackett/Jackett#2406]
Hello,

Would like to report an issues that I have noticed with a private tracker: TorrentHR

Jackett version:  0.8.578.0
Mono version (if not using Windows):  not sure considering I'm using the latest docker image: linuxserver/jackett

-------------------------------
Adding the tracker works fine and testing as well, however the results are not showing. Looking at an enhanced log I can see that the site does return results for a specific query, but again, non are reported are results.

Pastebin example log: https://pastebin.com/q34bHEKR

Thank you for any info on this matter.

**Comment by kaso17** [comment]
fixed via 1bc3413660fd19f675f7383edf060b9bebeca6b5
