### ISSUE TITLE
PirateBay not working

### ISSUE THREAD

**Issue by mrangryoven** [Jackett/Jackett#2407]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.8.578.0
Mono version (if not using Windows):  

-------------------------------
ThePirateBay is not working, says that there was an error testing this indexer.
No results were found while trying to browse this indexer.

`

When | Level | Message
-- | -- | --
Jan 12, 2018 04:01:38 PM | Error | {0}
Jan 12, 2018 04:01:38 PM | Info | Found 0 releases from The Pirate Bay
Jan 12, 2018 04:01:26 PM | Info | redirecting to /UI/Dashboard
Jan 12, 2018 03:59:40 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 12, 2018 03:54:19 PM | Info | Found 0 torrentpotato releases from The Pirate Bay for: -
Jan 12, 2018 03:44:09 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 12, 2018 03:28:38 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 12, 2018 03:13:07 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 12, 2018 02:57:37 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 12, 2018 02:53:47 PM | Info | Found 0 torrentpotato releases from The Pirate Bay for: -
Jan 12, 2018 02:42:06 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 12, 2018 02:26:35 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 12, 2018 02:11:05 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 12, 2018 01:53:16 PM | Info | Found 0 torrentpotato releases from The Pirate Bay for: -
Jan 12, 2018 01:40:09 PM | Error | {0}
Jan 12, 2018 01:25:09 PM | Error | {0}
Jan 12, 2018 01:09:39 PM | Error | {0}
Jan 12, 2018 12:54:09 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 12, 2018 12:52:44 PM | Info | Found 0 torrentpotato releases from The Pirate Bay for: -
Jan 12, 2018 12:38:38 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 12, 2018 12:23:06 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 12, 2018 12:07:37 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 12, 2018 11:52:09 AM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 12, 2018 11:51:54 AM | Info | Found 0 torrentpotato releases from The Pirate Bay for: -
Jan 11, 2018 10:35:35 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 11, 2018 10:20:04 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 11, 2018 10:11:38 PM | Info | Found 0 torrentpotato releases from The Pirate Bay for: -
Jan 11, 2018 10:04:39 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 11, 2018 10:02:04 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 11, 2018 09:59:01 PM | Info | Found 0 torrentpotato releases from The Pirate Bay for: -
Jan 11, 2018 09:46:32 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 11, 2018 09:31:02 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 11, 2018 09:30:43 PM | Info | Found 0 torrentpotato releases from The Pirate Bay for: -
Jan 11, 2018 09:15:32 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 11, 2018 08:59:59 PM | Info | Found 0 (0 new) releases from The Pirate Bay
Jan 11, 2018 08:44:29 PM | Info | Found 0 (1 new) releases from The Pirate Bay
Jan 11, 2018 08:43:24 PM | Info | Found 0 torrentpotato releases from The Pirate Bay for: -
Jan 11, 2018 08:37:33 PM | Info | Manual search for "cars 3" on thepiratebay with 0 results.
Jan 11, 2018 08:37:15 PM | Error | {0}
Jan 11, 2018 08:37:15 PM | Info | Found 0 releases from The Pirate Bay
Jan 11, 2018 08:36:43 PM | Error | {0}
Jan 11, 2018 08:36:43 PM | Info | Found 0 releases from The Pirate Bay
Jan 11, 2018 08:36:31 PM | Error | {0}
Jan 11, 2018 08:36:31 PM | Info | Found 0 releases from The Pirate Bay
Jan 11, 2018 08:35:49 PM | Info | redirecting to /UI/Dashboard
Jan 11, 2018 08:35:31 PM | Info | Service started
Jan 11, 2018 08:35:30 PM | Info | Starting web server at http://127.0.0.1:9117/
Jan 11, 2018 08:35:29 PM | Info | Adding aggregate indexer
Jan 11, 2018 08:35:29 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\ztracker.yml
Jan 11, 2018 08:35:29 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\zooqle.yml

`

**Comment by kaso17** [comment]
please provide the log.txt file

**Comment by garfield69** [comment]
no reply. closing.
