### ISSUE TITLE
RSS feeds don't work if used on a different machine

### ISSUE THREAD

**Issue by akang6** [Jackett/Jackett#2408]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

Jackett version: 0.8.578.0

So I have jackett running on a machine on my network, and I wanted to use the Copy RSS Feed on a client that's on a different machine in my local network. Unfortunately, it looks like the <link> field in the rss feed has 127.0.0.1:9117 hard coded making it impossible to use the rss feed on any computer other than the one that jackett is running on.

This is what the field looks like:
`<link>http://127.0.0.1:9117/jackett/dl/1337x/?jackett_apikey=eayvv53q5dtt3k7px4izwe8v3pqbupwl&amp;path=RW9IOUkzTDFXZGJCWUoxL3JHV0RBVnNOUUNkZ0J6TVlwL0ViVHc2Z2NrY2IxaElVZ0Vla3NmY2pnVW15MHJja0ZWalptTzVuaFBxaWNBbnhEa0s0ZGduVTczb1hoSjRGY3hrRGNIZThnWEJCT1BEcUJEc2NKK2JUUnVQR3BxTXBTTTkrbGUzWkc0N0QrNzhQVUQraEgzZnVzT3VTRHJucGJmQ0JqRGVFaHVUTXIyNWFuWWZUUFdDSXp5Nk1yK3VBeUpIMFE5d2N0NCtySDMxb3F3TE52RmdsUHBYeC9DTml1akRjanArU1NVVk8wQTlaMFlVTE1pRDFNNEVocmlsTFlkVGVlRFY3dEdzZU5WK2dJRFBYMDhDVmVPR1pvNnZ4YlJmVHJFNFJjS2lPUzE2ZjZLdFFUanBXVkdIdFNGTGJ4K0dPVUZCL1BxK3JkenZNV1FoRUxzMlkvbFBLT3ZXb0l2Ti9reXFPdzAzbk5Cd1N0N1hnKzF2WThLU2x6ZWEvZEN1cmF3OWNpZTdYdzlPeWN3WG1CK01IcENNLzlpVEd4UERrODA3eEdNMD01&amp;file=NJPW.Wrestle.Kingdom.12.in.Tokyo.Dome.ENG.WEB-DL.x264.Fight-BB</link>`

**Comment by kaso17** [comment]
You're using a reverse proxy which doesn't pass the original Host header correctly. Have a look at the README for apache instructions.
