### ISSUE TITLE
Scenetime index failure; Error on 20160212211546 for SceneTime.txtSystem.FormatException

### ISSUE THREAD

**Issue by Rycore** [Jackett/Jackett#241]
`Error on 20160212211546 for SceneTime.txtSystem.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Jackett.Utils.ParseUtil.CoerceFloat(String str) in C:\projects\jackett\src\Jackett\Utils\ParseUtil.cs:line 19
   at Jackett.Models.ReleaseInfo.GetBytes(String str) in C:\projects\jackett\src\Jackett\Models\ReleaseInfo.cs:line 62
   at Jackett.Indexers.SceneTime.<PerformQuery>d__12.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\SceneTime.cs:line 99`

Jackett Version: 0.7.168.0
OS: Windows 7 32bit

Jackett Version 0.7.164.0 allows me to connect without the error, but searching is messed up as it fails to display the categories.. so you can litterally search for movies, software etc.. whilst selecting a TV category and it will still find it.

**Comment by flightlevel** [comment]
Have you got an invite so I can test?
Tried to fix this issue without access last week https://github.com/Jackett/Jackett/issues/231 and it obviously hasn't worked

**Comment by Rycore** [comment]
No sorry, only VIP's can invite.. you could try [torrent-invites](http://www.torrent-invites.com/showthread.php?t=285670), I'd happily give you my user and pass since I don't use the site anymore, and you can make requests to get an invite..

Regarding the issue.. 

Version 0.7.164.0 works, it allows access, provides data based on search criteria, but the problem is the catagories aren't being detected, so when searching it doesn't matter what you're searching for it will pull the data from all catagories matching that info

Where as 0.7.168.0 isn't capable of searching... maybe it depends on the OS people are on, I'm on windows which is were I'm having the problem, were as 1c3bolt might be on linux and on his/her end the problem appears to be resolved.. ultimately it's confusing because if it worked for 1c3bolt it should be working for everyone else..

**Comment by flightlevel** [comment]
Think its just the column numbers, maybe a setting in your profile changes how many columns you have compared to say @1c3bolt 
Could you just search for a couple of popular shows and paste the HTML source into something like gist or pastebin and I can do it that way.

**Comment by Rycore** [comment]
yeah, no worries, I'll update back to the latest version again, "I downgraded to try 0.7.164.0" and I'll get back to you.

**Comment by flightlevel** [comment]
Don't have to change Jackett versions. I meant just visit the scenetime site normally in chrome, search for a show in chrome, right click, view page source and paste contents so that I can see scenetime HTML

**Comment by Rycore** [comment]
I know, but I only provided you with the error message and not the full log as I didn't want to spam the post. This is the full log including some HTML content that came with it.

http://pastebin.com/3J7rYRYS

I'm going to grab the other stuff now for you.

**Comment by Rycore** [comment]
Search no category
http://pastebin.com/uh1TXuWN The 100
http://pastebin.com/VycN36Pj Supernatural
http://pastebin.com/hNhFvfLE Walking Dead

Search based on category; TV/XviD, TV-HD, TV/SD, TV/Web-Rip
http://pastebin.com/Wv2pvETr Walking Dead
http://pastebin.com/TpMu7hxW Supernatural
http://pastebin.com/Zf4uvLqL

I actually think I've figured it out.. I don't think Version 0.7.164.0 has the issue with the categories.. I mean like yeah it's now displaying the category names in jackett when you do a manual search, but when I searched The Walking Dead and even had it set for those four tv categories, it still provided the game despite not having that category selected, now if I select each category separately and do a search, it the search preference works, but when you try to search through more than one category it instantly breaks and displays all criteria for that search term.


If you want me to provide you the same results but for the categories seperate let me know.. hopefully this is enough to help resolve the matter.

**Comment by Rycore** [comment]
Just to note, I placed all my settings back to default as I originally had it on 25 torrent per page, just to see if maybe 1c3bolt had their's as basic but no change in the error.

**Comment by flightlevel** [comment]
@Rycore Thanks for that
Can you give latest a go https://github.com/Jackett/Jackett/releases/tag/v0.7.170 (note its a pre-release, tick box down the bottom of your Jackett dashboard to update)

**Comment by 1c3bolt** [comment]
Hi Guys,
Sorry for the late reply.
So mine is on linux. i run with everything on default and i'm using only sonarr to do the searches. i haven'r tried the manual search from jackett it self.

**Comment by Rycore** [comment]
@flightlevel It connects to sonarr without issue.

But jackett is only grabbing the data from the first page, it's not actually searching, so if the HD or SD catagory is there, it will display that item but because none of the other content has a catagory such as movies, it is still being displayed, but only if the content is on the first browse page.

Here are screenshots.
http://prnt.sc/a2pat7 - All Results
http://prnt.sc/a2pau8 - HD Only
http://prnt.sc/a2pav0 - SD Only

As you can see, despite me providing a specific query, it's not actually using it. 

@1c3bolt thanks for replying, at least we know the linux version is working, I don't use manual search as I let sonarr do it all for me, but the manual search should produce the same results the automatic search done in sonarr, which is when I figured out that jackett wouldn't produce any results on 0.7.168.0 but would show up (with no categories) on the 0.7.164.0.

**Comment by 1c3bolt** [comment]
Hi since you pointed out it seems it only picks up the 25 first entries.
Also notice that the manual search, the categories aren't filtering it always retrieves everything.
I didn't noticed it before as sonarr just searches per episode.

**Comment by Rycore** [comment]
@1c3bolt I'm assuming you've been updated to the latest version 0.7.170.0? if so try downgrading to 0.7.168.0 and then disabling the updates by ticking "Disable auto update:", then manually search for an episode..

Odds are the previous version was working fine for you, for me the previous version wouldn't even grab data from scenetime..

**Comment by flightlevel** [comment]
@Rycore if you don't mind can you send me your user/pass to jacketapp at gmail (and then just change password once I'm done) I can't fix it from just the html. Something weird is happening, eg the pastebins have zero results for the 100 or supernatural, plus the results you are getting through Jackett.

**Comment by flightlevel** [comment]
@1c3bolt 
If you look at this image, do you have the same number of columns? http://snag.gy/zGZff.jpg
Seems like columns size, seeders, leechers are number 6, 7, 8 respectively for @Rycore whereas for you they are columns 4, 5, 6. Can't see how it could be linux related?

**Comment by Rycore** [comment]
This is what my scenetime columns looks like, http://prnt.sc/a2z1vg, @flightlevel I'll change my password and send you the details to that address now.

**Comment by flightlevel** [comment]
@Rycore typo in the email should be double t 
jackettapp at gmail

**Comment by Rycore** [comment]
@flightlevel k, had to change the pw again, sent the email.

**Comment by flightlevel** [comment]
thanks @Rycore you can now change your password back
Latest release should fix issue, be interesting to see if it still works for @1c3bolt

**Comment by Rycore** [comment]
Thanks @flightlevel, all working smoothly once again.

**Comment by 1c3bolt** [comment]
Hi ,
so there are too thing:
1. web server reponse based on os type.so maybe you will need to create a branch for linux os and another for windows.
2. i m still on version 0.7.18
