### ISSUE TITLE
[yts] Exception (yts): Error reading JObject from JsonReader. Path '', line 0, position 0.: Parse error (Test)

### ISSUE THREAD

**Issue by jpacione** [Jackett/Jackett#2411]
Yify through Jackett is erroring out.  Any ideas?

**Comment by kaso17** [comment]
Works for me.

Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by jpacione** [comment]
I’ve resolved.  The url was updated. 

 
John Pacione
