### ISSUE TITLE
[utorrents] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by bjaguar33** [Jackett/Jackett#2412]
An error occured while testing this indexer
Exception (utorrents): Login Failed, got redirected: Parse error

rror on 20180113035847 for u-Torrent.txtJackett.ExceptionWithConfigData: Login Failed, got redirected
   at Jackett.Indexers.CardigannIndexer.<TestLogin>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__25.MoveNext()

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<meta http-equiv="refresh" content="0;url=http://www.u-torrents.ro/login.php" />
<title>Redirecting to http://www.u-torrents.ro/login.php</title>
<script type="text/javascript">
//<![CDATA[
window.__cfRocketOptions = {byc:0,p:0,petok:"e44ce98d8a279bc810f7b3c1e9169e492f84c57d-1515808726-1800"};
//]]>
</script>
<script type="text/javascript" src="https://ajax.cloudflare.com/cdn-cgi/scripts/9014afdb/cloudflare-static/rocket.min.js"></script>
</head>
<body>
Redirecting to <a href="http://www.u-torrents.ro/login.php">http://www.u-torrents.ro/login.php</a>.
</body>
</html>

-------------------------------

**Comment by kaso17** [comment]
Update to the latets version and use the scenefz indexer (scene fz and utorrent are the same now)

**Comment by seanvree** [comment]
I"m getting this error:

```
An error occured while updating this indexer
Login failed: No form found on https://scenefz.me/login.php using form selector form
Click here to open an issue on Github for this indexer.
```

Using  https://scenefz.me/

**Comment by buggyro** [comment]
I am also getting the same error both with scenefz and u-torrents link:

> An error occured while updating this indexer
> Login failed: No form found on https://scenefz.me/login.php using form selector form
> Click here to open an issue on Github for this indexer.

>  An error occured while updating this indexer
> Login failed: No form found on https://www.u-torrents.ro/login.php using form selector form
> Click here to open an issue on Github for this indexer.

**Comment by kaso17** [comment]
should be fixed via 156f6f6ccec137779c811cc6fcc7d1ce29da9151

**Comment by buggyro** [comment]
Dear kaso,
Thanks for your fix. The login now works.
However i now receive:

>  An error occured while testing this indexer
> Found no results while trying to browse this tracker

Do you know why this might be happening?
Thanks

**Comment by kaso17** [comment]
d49666835f9b4802b6605f5d6ff8da42d94a5df0 should fix these errors

**Comment by buggyro** [comment]
Thanks!
Seems to be working.
