### ISSUE TITLE
[xspeeds] Please turn JavaScript on and reload the page.                                    Checking your browser before accessing xspeeds.eu.        This process is automatic. Your browser will redirect to your requested content shortly.    Please allow up to 5 seconds… (Config)

### ISSUE THREAD

**Issue by RyanMulready** [Jackett/Jackett#2413]
Broke recently, was working fine up until a release or two ago.

**Comment by kaso17** [comment]
works fine for me using 0.8.588.0

Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by RyanMulready** [comment]
Can confirm working now with 0.8.588 was broken on 0.8.578.0
