### ISSUE TITLE
[tvchaosuk] getting error when trying to search.

### ISSUE THREAD

**Issue by timtimar** [Jackett/Jackett#2418]
Getting this error when trying to use tvchaosuk.
running Jackett Version 0.8.588.0

[tvchaosuk] Exception (tvchaosuk): '', hexadecimal value 0x02, is an invalid character. Line 349, position 54.: '', hexadecimal value 0x02, is an invalid character. Line 349, position 54. (Config)

**Comment by kaso17** [comment]
can't reproduce this anymore, still a problem?

**Comment by timtimar** [comment]
Issue is gone.  Must have been on the site itself.
Just happen to occur after the update.
