### ISSUE TITLE
[anidex] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by BladeCL** [Jackett/Jackett#2420]
Just that, anidex doesn't found anything, attached logs.

Jackett version:  **0.8.596.0**
Mono version (if not using Windows):  Mono JIT compiler version **4.8.1** (4.8.1.0 Thu Oct 19 03:09:13 UTC 2017) (FreeBSD)

[log.txt](https://github.com/Jackett/Jackett/files/1629015/log.txt)

**Comment by garfield69** [comment]
I don't have any problems access Anidex from my win7 Jackett Dashboard.
But your log shows that you got a cloudflare DDOS challenge which broke your Jackett session with *ServiceUnavailable*.
@kaso17  where are we with the cloudflare stuff, was the CloudFlareUtilities: update to 1.0.0 supposed to resolve this or is there some other problem here?
Should this user on mono 4.8.1 upgrade to 5.4 and would that help in this situation?

**Comment by kaso17** [comment]
the CF issue wasn't fully fixed for the libcurl webclient, should be fixed now via 6ecc500dde5b87c12d21b50401ff7e2c7212b3b8
