### ISSUE TITLE
btbit

### ISSUE THREAD

**Issue by SteffanCline** [Jackett/Jackett#2425]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  latest
Mono version (if not using Windows):  latest

-------------------------------
Manually searching through Jackett seems to be fine but going through Sonarr yields an error:
Unable to connect to indexer: HTTP request failed: [400:BadRequest] [GET] at [http://127.0.0.1:9117/api/v2.0/indexers/btbit/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=fswt7oji677km8c03kayyjc2967gbg7y&offset=0&limit=100]

HTTP Error - Res: [GET] http://127.0.0.1:9117/api/v2.0/indexers/btbit/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100: 400.BadRequest
<Error><Message>btbit does not support the requested query.</Message></Error>

**Comment by kaso17** [comment]
categories again...
