### ISSUE TITLE
Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by SSlimC** [Jackett/Jackett#2431]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
which indexer are you using that returns no results for you?
Also which version of Jackett are you on, and if you are using mono, which version are you using?
Help us to help you by providing these basic info bytes.
