### ISSUE TITLE
[QUESTION] Only one category as same time

### ISSUE THREAD

**Issue by Albvadi** [Jackett/Jackett#2432]
Jackett version: 0.8.602.0
Mono version (if not using Windows): Windows 7
______________________________

Hi,
coding a new definition for another tracker, I have a doubt that I do not know how to code.

In this tracker, only can search in a one category at the same time (it´s a simple select). The all categories it´s a '0' value and the rest has a different value.

I´ve code this in this way:

1. Adding the normal categorymappings
2. Adding a category input manually:
    ```yaml
    inputs:
        page: "torrents"
        category: "0"
    ```
All it´s working correctly. In a manual search, if I select "Any", get all the results. 
If I select one category, I get results only from that category.
If I select two categories, I get results only from those categories...

So... all works.. but.. is the correct way to do this??

Thanks!

**Comment by kaso17** [comment]
Some trackers actually support multiple categories without giving the user the option.
Try e.g. multiple categories separated by semicolon (&category=1;2;3;...) or cX=1 arguments (&c1=1&c2=2&c3=1).

If that doesn't work the only alternative would be to to send one search query for each category. If the tracker has more than a handful of categories I wouldn't recommend this. Your current solution (always search all categories) is perfectly fine.

**Comment by Albvadi** [comment]
> Try e.g. multiple categories separated by semicolon (&category=1;2;3;...)

You are right, categories separated with semicolon works perfect.
Thanks!!
