### ISSUE TITLE
Unable to update jackett on qnap

### ISSUE THREAD

**Issue by drumstick77** [Jackett/Jackett#2436]
Hi All,

unable to update jackett to any later version. currently still on 0.6.45.
kept getting message on Web UI saying that can't be installed please check logs.
any help would be appreciated. thanks

**Comment by drumstick77** [comment]
oh and I'm using Qmono 4.4.2.11.

**Comment by garfield69** [comment]
By *update* do you mean you are using the *check for updates* button on the Dashboard and this is failing?       
You may want to uninstall your v0.6.45 Jackett and install the latest package manually instead. There has been significant updates to the Jackett auto-update code just after 0.6.45 :-).     
Also recommend upgrading your mono to 5.4 for maximum compatibility with the Jackett 0.8 suite.

**Comment by drumstick77** [comment]
Thanks. I've uninstalled jackett completely and when trying to install any
of the later version, it just refused to do it.

I haven't however uninstall Qmono as yet, but my Sonarr is working fine
with the current Qmono 4.2.11.
(Sonarr requires Qmono to run, correct?)

Thanks

**Comment by garfield69** [comment]
@drumstick77  did you manage to resolve this for yourself?

**Comment by drumstick77** [comment]
No, i gave up at the end. I am using dockers within open media vault now.
Much easier.

Regards,

Jonathan Halim
