### ISSUE TITLE
[torrent9] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by darkcattz** [Jackett/Jackett#2438]
Hello

Jackett version:  0.8.602.0
Mono version (if not using Windows):  5.4.1.6-9 (Synology)

Thanks

---------------------------
Logs
---------------------------

Jan 18, 2018 11:56:45 AM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
-- | -- | --
Jan 18, 2018 11:56:45 AM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
Jan 18, 2018 11:56:45 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Jan 18, 2018 11:56:45 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
Jan 18, 2018 11:56:45 AM | Info | HttpActionBinding ExecuteBindingAsync
Jan 18, 2018 11:56:45 AM | Info | HttpActionBinding ExecuteBindingAsync
Jan 18, 2018 11:56:45 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Jan 18, 2018 11:56:45 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Jan 18, 2018 11:56:45 AM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
Jan 18, 2018 11:56:45 AM | Info | ApiControllerActionSelector SelectAction
Jan 18, 2018 11:56:45 AM | Info | ServerConfigurationController ExecuteAsync
Jan 18, 2018 11:56:45 AM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ServerConfigurationController
Jan 18, 2018 11:56:45 AM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ServerConfigurationController
Jan 18, 2018 11:56:45 AM | Info | DefaultHttpControllerActivator Create
Jan 18, 2018 11:56:45 AM | Info | HttpControllerDescriptor CreateController
Jan 18, 2018 11:56:45 AM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
Jan 18, 2018 11:56:45 AM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
Jan 18, 2018 11:56:45 AM | Info | http://192.168.1.50:9117/api/v2.0/server/logs?_=1516272677267
Jan 18, 2018 11:56:39 AM | Info | IndexerApiController Dispose
Jan 18, 2018 11:56:39 AM | Info | IndexerApiController Dispose
Jan 18, 2018 11:56:39 AM | Info | Content-type='application/json; charset=utf-8', content-length=12297
Jan 18, 2018 11:56:39 AM | Info | IndexerApiController ExecuteAsync
Jan 18, 2018 11:56:39 AM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Jan 18, 2018 11:56:39 AM | Error | {0}
Jan 18, 2018 11:56:39 AM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Jan 18, 2018 11:56:39 AM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Jan 18, 2018 11:56:39 AM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Jan 18, 2018 11:56:39 AM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Jan 18, 2018 11:56:39 AM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Test()'
Jan 18, 2018 11:56:39 AM | Error | ApiControllerActionInvoker InvokeActionAsync
Jan 18, 2018 11:56:39 AM | Error | ReflectedHttpActionDescriptor ExecuteAsync
Jan 18, 2018 11:56:39 AM | Info | Found 0 releases from Torrent9
Jan 18, 2018 11:56:39 AM | Debug | WebClient(HttpWebClient): Returning NotFound => <!DOCTYPE html> <html> <head> <meta charset="utf-8"> <style>html{height:100%}body{margin:0 auto;min-height:600px;min-width:800px;height:100%}.top{height:100px;height:calc(40% - 140px)}.bottom{height:150px;height:calc(60% - 210px)}.center{height:350px;text-align:center;vertical-align:middle;font-family:Verdana}.circle{margin:auto;width:260px;height:260px;border-radius:50%;background:#c0c6cc}.circle_text{line-height:260px;font-size:100px;color:#ffffff;font-weight:bold}.text{line-height:40px;font-size:26px;color:#505a64} </style> </head> <body> <div class="top"></div> <div class="center"> <div class="circle"> <div class="circle_text">404</div> </div> <div> <p class="text" id="a"></p> </div> <script> /* Copyright (c) 2017 Synology Inc. All rights reserved. */  (function(){var a=new XMLHttpRequest();a.open("get","/missing",true);a.send();a.onreadystatechange=function(){if(a.readyState==4&&(a.status==200\|\|a.status==304)){var c=String(a.responseText);var e=document.open("text/html","replace");e.write(c);e.close()}else{var d={en:"The page you are looking for cannot be found.",zh:"\u60a8\u8981\u627e\u7684\u9875\u9762\u672a\u627e\u5230\u3002",it:"Impossibile trovare la pagina ricercata.","zh-HK":"\u60a8\u6240\u6307\u5b9a\u7684\u9801\u9762\u4e0d\u5b58\u5728\u3002",cs:"Hledan\u00e1 str\u00e1nka nebyla nalezena.",es:"Lo sentimos, no se encuentra la p\u00e1gina que est\u00e1 buscando.",ru:"\u041d\u0435 \u0443\u0434\u0430\u0435\u0442\u0441\u044f \u043d\u0430\u0439\u0442\u0438 \u0438\u0441\u043a\u043e\u043c\u0443\u044e \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443.",nl:"Kan de gezochte pagina niet vinden.",pt:"A p\u00e1gina que procura n\u00e3o foi encontrada.",no:"Finner ikke siden du leter etter.",nb:"Finner ikke siden du leter etter.",tr:"Arad\u0131\u011f\u0131n\u0131z sayfa bulunam\u0131yor.",pl:"Nie znaleziono strony, kt\u00f3rej szukasz.",fr:"La page que vous recherchez est introuvable.",de:"Die Seite, nach der Sie suchen, kann nicht gefunden werden.",hu:"A keresett oldal nem tal\u00e1lhat\u00f3.","pt-BR":"N\u00e3o foi poss\u00edvel encontrar a p\u00e1gina que voc\u00ea est\u00e1 buscando.","zh-MO":"\u60a8\u6240\u6307\u5b9a\u7684\u9801\u9762\u4e0d\u5b58\u5728\u3002",da:"Den side, du leder efter, kunne ikke findes.",ja:"\u304a\u63a2\u3057\u306e\u30da\u30fc\u30b8\u304c\u3001\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3002",nn:"Finner ikke siden du leter etter.","zh-TW":"\u60a8\u6240\u6307\u5b9a\u7684\u9801\u9762\u4e0d\u5b58\u5728\u3002",ko:"\ucc3e\uace0 \uacc4\uc2e0 \ud398\uc774\uc9c0\ub97c \ubc1c\uacac\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.",sv:"Sidan du s\u00f6ker kunde inte hittas."};var b=["zh-TW","zh-HK","zh-MO","pt-BR"];var f;if(window.navigator.languages!==undefined){f=window.navigator.languages[0]}else{f=window.navigator.language\|\|window.navigator.browserLanguage}if(b.indexOf(f)<0){f=f.split("-")[0]}document.getElementById("a").innerHTML=d[f]\|\|d.enu}}})(); </script> </div> <div class="bottom"></div> </body> </html>
Jan 18, 2018 11:56:39 AM | Debug | WebClient(HttpWebClient).GetString(Url:http://www.torrent9.top/top_torrent.php)
Jan 18, 2018 11:56:39 AM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
Jan 18, 2018 11:56:39 AM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Test()'
Jan 18, 2018 11:56:39 AM | Info | RequiresIndexerAttribute OnActionExecutingAsync
Jan 18, 2018 11:56:39 AM | Info | RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Test()'
Jan 18, 2018 11:56:39 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Jan 18, 2018 11:56:39 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()'
Jan 18, 2018 11:56:39 AM | Info | HttpActionBinding ExecuteBindingAsync
Jan 18, 2018 11:56:39 AM | Info | HttpActionBinding ExecuteBindingAsync
Jan 18, 2018 11:56:39 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Jan 18, 2018 11:56:39 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Jan 18, 2018 11:56:39 AM | Info | ApiControllerActionSelector SelectAction Selected action 'Test()'
Jan 18, 2018 11:56:39 AM | Info | ApiControllerActionSelector SelectAction
Jan 18, 2018 11:56:39 AM | Info | IndexerApiController ExecuteAsync
Jan 18, 2018 11:56:39 AM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.IndexerApiController
Jan 18, 2018 11:56:39 AM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.IndexerApiController
Jan 18, 2018 11:56:39 AM | Info | DefaultHttpControllerActivator Create

**Comment by garfield69** [comment]
logs show you are looking for `http://www.torrent9.top/top_torrent.php` and getting a not-found error.
So try this: on your Jackett Dashboard use the wrench icon to edit your torrent9 indexer and change the SiteLink from `http://www.torrent9.top/` to `http://www.torrent9.bz/` which is torrent9's current domain name.

**Comment by darkcattz** [comment]
Damn, it was simple indeed :)
Thanks
