### ISSUE TITLE
[gktorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by darkcattz** [Jackett/Jackett#2440]
Hello,

Platform : Synology DSM6
Jackett version:   0.8.602.0
Mono version (if not using Windows):   5.4.1.6-9

Thanks

-------------------------------
Logs
------------------------------

Jan 18, 2018 11:54:14 AM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
-- | -- | --
Jan 18, 2018 11:54:14 AM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
Jan 18, 2018 11:54:14 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Jan 18, 2018 11:54:14 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
Jan 18, 2018 11:54:14 AM | Info | HttpActionBinding ExecuteBindingAsync
Jan 18, 2018 11:54:14 AM | Info | HttpActionBinding ExecuteBindingAsync
Jan 18, 2018 11:54:14 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Jan 18, 2018 11:54:14 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Jan 18, 2018 11:54:14 AM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
Jan 18, 2018 11:54:14 AM | Info | ApiControllerActionSelector SelectAction
Jan 18, 2018 11:54:14 AM | Info | ServerConfigurationController ExecuteAsync
Jan 18, 2018 11:54:14 AM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ServerConfigurationController
Jan 18, 2018 11:54:14 AM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ServerConfigurationController
Jan 18, 2018 11:54:14 AM | Info | DefaultHttpControllerActivator Create
Jan 18, 2018 11:54:14 AM | Info | HttpControllerDescriptor CreateController
Jan 18, 2018 11:54:14 AM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
Jan 18, 2018 11:54:14 AM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
Jan 18, 2018 11:54:14 AM | Info | http://192.168.1.50:9117/api/v2.0/server/logs?_=1516272677266
Jan 18, 2018 11:54:03 AM | Info | IndexerApiController Dispose
Jan 18, 2018 11:54:03 AM | Info | IndexerApiController Dispose
Jan 18, 2018 11:54:03 AM | Info | Content-type='application/json; charset=utf-8', content-length=12297
Jan 18, 2018 11:54:03 AM | Info | IndexerApiController ExecuteAsync
Jan 18, 2018 11:54:03 AM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Jan 18, 2018 11:54:03 AM | Error | {0}
Jan 18, 2018 11:54:03 AM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Jan 18, 2018 11:54:03 AM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Jan 18, 2018 11:54:03 AM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Jan 18, 2018 11:54:03 AM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Jan 18, 2018 11:54:03 AM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Test()'
Jan 18, 2018 11:54:03 AM | Error | ApiControllerActionInvoker InvokeActionAsync
Jan 18, 2018 11:54:03 AM | Error | ReflectedHttpActionDescriptor ExecuteAsync
Jan 18, 2018 11:54:03 AM | Info | Found 0 releases from GkTorrent
Jan 18, 2018 11:54:03 AM | Debug | WebClient(HttpWebClient): Returning MovedPermanently => http://www.gktorrent.net/
Jan 18, 2018 11:54:03 AM | Debug | WebClient(HttpWebClient).GetString(Url:http://www.gktorrent.com/)
Jan 18, 2018 11:54:03 AM | Info | CardigannIndexer (gktorrent): Relogin required
Jan 18, 2018 11:54:03 AM | Debug | WebClient(HttpWebClient): Returning MovedPermanently => http://www.gktorrent.net/
Jan 18, 2018 11:54:03 AM | Debug | WebClient(HttpWebClient).GetString(Url:http://www.gktorrent.com/)
Jan 18, 2018 11:54:03 AM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
Jan 18, 2018 11:54:03 AM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Test()'
Jan 18, 2018 11:54:03 AM | Info | RequiresIndexerAttribute OnActionExecutingAsync
Jan 18, 2018 11:54:03 AM | Info | RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Test()'
Jan 18, 2018 11:54:03 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Jan 18, 2018 11:54:03 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()'
Jan 18, 2018 11:54:03 AM | Info | HttpActionBinding ExecuteBindingAsync
Jan 18, 2018 11:54:03 AM | Info | HttpActionBinding ExecuteBindingAsync
Jan 18, 2018 11:54:03 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Jan 18, 2018 11:54:03 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Jan 18, 2018 11:54:03 AM | Info | ApiControllerActionSelector SelectAction Selected action 'Test()'
Jan 18, 2018 11:54:03 AM | Info | ApiControllerActionSelector SelectAction
Jan 18, 2018 11:54:03 AM | Info | IndexerApiController ExecuteAsync

**Comment by garfield69** [comment]
Looks like gktorrent have switched domain. I'll submit a fix shortly.
In the mean time you can fix this directly for yourself, by using the wrench icon on your Jackett dashboard and editing the gktorrent Site Link from `http://www.gktorrent.com/` to `http://www.gktorrent.net/`

**Comment by darkcattz** [comment]
Thanks ;)
