### ISSUE TITLE
[danishbits] Exception (danishbits): your API settings er ikke korrekte!

### ISSUE THREAD

**Issue by webersnet** [Jackett/Jackett#2443]
I cannot add DanishBits to my list anymore. Seems like the API changed. 
Exception (Danishbits) your API settings are not correct.

**Comment by garfield69** [comment]
What happens if you open this link in your browser (add your login details in the appropriate places)?
`https://danishbits.org/couchpotato.php?search=%25&passkey=yourpasskeynotpassword&user=yourusername`

**Comment by webersnet** [comment]
Rigt now (because i setup RSS) it says all API hits used. Ill try it again tomorrow. API Hits are reset at 0400 hours danish time.

**Comment by webersnet** [comment]
Jackett still gives me an error om testing. But is just says API settings incorrect.

**Comment by webersnet** [comment]
The link give me an API error message. 

{"error":"Dine API settings er ikke korrekte!"}

translation: Your API settings are not correct!

**Comment by kaso17** [comment]
If you're getting the same error in the browser then I suggest you contact the danishbits support.
If it's working in the browser but not in jackett please compare the URLs from the jackett log with the browser.

**Comment by supremacy2k** [comment]
I just tested on v0.8.602 and v0.8.618, and both works with danishbits.
@OP are you sure, you're using your passkey, and not password?

**Comment by webersnet** [comment]
Since last night everything works again without me doing anything.
