### ISSUE TITLE
Couchpotato duplicate results

### ISSUE THREAD

**Issue by mhendu** [Jackett/Jackett#2446]
When results returned to Couchpotato are incorrect (e.g., I'm looking for a movie called 'Jackett' from 2017 and Couchpotato shows me 'I Heart Jackett' as a result, which is a different movie), and I click the 'x' at the far right to tell Couchpotato not to count the result, after some interval Couchpotato will report the same torrent as a result for the search as a duplicate entry. After I do this a few times this results in rows and rows of duplicate listings of the wrong torrents, which begins to make the UI unresponsive. For indexers natively handled by Couchpotato this doesn't occur - Couchpotato will only surface the torrent once and if you click the 'x' it will not return that same result as a new row, it will just keep the one row available. Not sure if there's a good fix for this but would love to get this resolved if possible.

Jackett version:  0.8.602.0

**Comment by kaso17** [comment]
From which tracker are these torrents?

**Comment by mhendu** [comment]
Every tracker, as far as I can tell, both public and private.

**Comment by kaso17** [comment]
Ok, then I believe this is a CP bug. Non of the information returned by jackett for a specific torrent changes (unless it changes on the tracker). So most likely this is some kind of "CP clears old releases cache after some time" issue.  unless someone expplains me how CP handles this  kind of caching there's nothing we can do about. I suggest you open an CP issue.
