### ISSUE TITLE
Jackett Log File Becoming Enormous In Weeks

### ISSUE THREAD

**Issue by RyanAStrouse** [Jackett/Jackett#2448]
Jackett version:  Version 0.8.602.0
Mono version (if not using Windows):  Mono JIT compiler version 5.4.1.7 (tarball Wed Jan 17 20:35:45 UTC 2018)

Running Jackett in a docker provided by linuxserver.io

-----------------------

Hello,

I've noticed that I'm receiving an error on my server about hard drive space running out and it occurs every couple of weeks. It always seems to be the Jackett log file and it gets upwards of 26GB or so. Granted, I do need to move my system to a larger OS SSD that I have, but I'm more concerned about why this is happening and how I could track down the answer. I already deleted the log this time (which now that I thought about it, would probably have been great to save elsewhere to look through it).

Thanks for any input!

**Comment by garfield69** [comment]
is full enhanced logging been enabled? drop the -t -l parms from the startup. this should reduce the log output.

**Comment by FedoraTipper** [comment]
Same with docker builds, although there is a work around by keeping docker's logging to minimum.


https://github.com/linuxserver/docker-jackett/issues/28

**Comment by kaso17** [comment]
@RyanAStrouse can you please specify if you're talking about docker logs or jackett logs (log.txt files)?
The jacket log files should auto rotate at 500KB and ther should be a maximum of 5 archive files, so a total of 3 MB of log files. If that's not the case we need to look into this (probably docker specific).

**Comment by RyanAStrouse** [comment]
@kaso17 I'm thinking it's actually a docker log issue then, since I find the file under the docker container ID for Jackett. Sorry for posting in the wrong location.

@garfield69 I do not have enhanced logging turned on.
