### ISSUE TITLE
[kickasstorrent-kathow] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Hossy** [Jackett/Jackett#2449]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.8.602.0
Mono version (if not using Windows):  5.4.1.7

-------------------------------
[20180120-Jackett Logs--kickasstorrent-kathow.txt](https://github.com/Jackett/Jackett/files/1649529/20180120-Jackett.Logs--kickasstorrent-kathow.txt)

**Comment by zero77** [comment]
I am getting the same thing but for me it’s the cloudflare capture, what happens if you visit the domain in your browser do you see a capture.

If so, you need to use a proxy and this request may help you, if its implemented.
https://github.com/Jackett/Jackett/issues/2359

**Comment by Hossy** [comment]
I have Jackett running inside Docker, so no browser.

**Comment by zero77** [comment]
Yes but what happens if you visit the Domains outside of Jackett just in your browser, do you see a cloudflare capture or can you access the domains ok without seeing a capture.

**Comment by Hossy** [comment]
Sorry, I should've clarified: the Docker container is attached to the shared network namespace of an OpenVPN client Docker container for the use of the VPN connection.  Any browser I load will not be using the same VPN connection.  I can run wget or curl, but that's the best I can do.

**Comment by Hossy** [comment]
Here is what I get from wget -qO /downloads/https--kat.how.html.txt https://kat.how/.  It doesn't look like a CAPTCHA.

[https--kat.how.html.txt](https://github.com/Jackett/Jackett/files/1652275/https--kat.how.html.txt)

**Comment by zero77** [comment]
Ok I see, and from the logs you are getting a “301 Moved Permanently” try changing the domain to https://thekat.nz/ from https://kat.how/ 
See if that helps

**Comment by Hossy** [comment]
Well, what d'ya know... that returns a good test. :-)  Unfortunately, a redirect is not the case for https://katcr.co/new/ https://github.com/Jackett/Jackett/issues/2450

**Comment by Hossy** [comment]
Is there a feature request/bug report somewhere about Jackett failing on redirects?

**Comment by zero77** [comment]
I don’t know, try the wiki

**Comment by Hossy** [comment]
I just searched open issues and it doesn't appear there is one.  I'll create on separate from this.

**Comment by kaso17** [comment]
fixed via dd9a6c1c7be06f2a41afb9bcf880a0a6cb957be3 :)
