### ISSUE TITLE
[kickasstorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Hossy** [Jackett/Jackett#2450]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.8.602.0
Mono version (if not using Windows):  5.4.1.7

-------------------------------
[20180120-Jackett Logs--kickasstorrent.txt](https://github.com/Jackett/Jackett/files/1649531/20180120-Jackett.Logs--kickasstorrent.txt)

**Comment by zero77** [comment]
I am getting the same thing but for me it’s the cloudflare capture, what happens if you visit the domain in your browser do you see a capture.

If so, you need to use a proxy and this request may help you, if its implemented.
https://github.com/Jackett/Jackett/issues/2359

**Comment by Hossy** [comment]
I have Jackett running inside Docker, so no browser.

**Comment by Hossy** [comment]
# wget -O /downloads/https--katcr.co_new.html.txt https://katcr.co/new/
--2018-01-22 08:27:22--  https://katcr.co/new/
Resolving katcr.co (katcr.co)... 107.154.65.197, 107.154.38.197
Connecting to katcr.co (katcr.co)|107.154.65.197|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: â/downloads/https--katcr.co_new.html.txtâ

/downloads/https--katcr.co_new.html.txt                         [   <=>                                                                                                                                   ] 232.00K   431KB/s    in 0.5s

2018-01-22 08:27:23 (431 KB/s) - â/downloads/https--katcr.co_new.html.txtâ saved [237569]

[https--katcr.co_new.html.txt](https://github.com/Jackett/Jackett/files/1652283/https--katcr.co_new.html.txt)

**Comment by Hossy** [comment]
Looking at the logs, there is a line:
`2018-01-20 22:23:10.4354 Debug WebClient(HttpWebClient).GetString(Url:https://katcr.co/new/torrents/top-100-latest-uploads.html)`

which returns a 404...

    # wget -O /downloads/https--katcr.co_new_torrents_top-100-latest-uploads.html.txt https://katcr.co/new/torrents/top-100-latest-uploads.html
    --2018-01-22 08:52:54--  https://katcr.co/new/torrents/top-100-latest-uploads.html
    Resolving katcr.co (katcr.co)... 107.154.38.197, 107.154.65.197
    Connecting to katcr.co (katcr.co)|107.154.38.197|:443... connected.
    HTTP request sent, awaiting response... 404 Not Found
    2018-01-22 08:52:54 ERROR 404: Not Found.

**Comment by kaso17** [comment]
dupe #2280
