### ISSUE TITLE
[speedcd] Unable to add - wrong page

### ISSUE THREAD

**Issue by endriu0** [Jackett/Jackett#2451]
Not able to add speed.cd - getting a 404 speed.cd/takelogin.php doesn't exist when logging in.

Error : html,body{font-family:tahoma, arial, helvetica, sans-serif;font-size:11pt;color:#000;background:url(/V3/img/error_bg.gif) no-repeat center #000;height:100%;width:100%;margin:0;padding:0} .uiButton{background:#eee url(/pic/ui/buttons/ui.png) repeat-x 0 0;border:1px solid #999;border-bottom-color:#888;box-shadow:0 1px 0 rgba(0,0,0,.1);-moz-box-shadow:0 1px 0 rgba(0,0,0,.1);cursor:pointer;display:inline-block;font-size:11px;font-weight:700;line-height:normal!important;text-align:center;text-decoration:none;vertical-align:top;white-space:nowrap;padding:2px 6px} .uiButton .button{background:none;text-decoration:none;border:0;color:#333;cursor:pointer;display:inline-block;font-size:11px;font-weight:700;outline:0;white-space:nowrap;margin:0;padding:3px 25px 5px} .uiButtoncolor{background-color:#69a74e;background-position:0 -96px!important;border-color:#3b6e22 #3b6e22 #2c5115} .uiButtoncolor:active{background:#609946;border-bottom-color:#3b6e22} .uiButtoncolor .button{color:#fff} .boxHead{background-color:red;border:none;filter:alpha(opacity=70);opacity:0.7;font-size:18px;color:#FFF;font-weight:700;} .boxBody{background-color:#FFF;filter:alpha(opacity=90);opacity:0.9} .boxBody .link{margin:1.5em 0;text-align:center} File Not Found No page exists at your destination address, http://speed.cd/takelogin.php but the Speed.cd home page should help you to find what you need. Return to Speed.cd Home Page 

Jackett version: 0.8.450.0
Mono version (if not using Windows):  5.4.1.6

-------------------------------

**Comment by kaso17** [comment]
fixed a long time ago via bed9b9d54b2921ff4825b3e0b1776d6e2893a747
please update to the latest version
