### ISSUE TITLE
[yts] An error occurred while sending the request.: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. (Config)

### ISSUE THREAD

**Issue by ZshlomiA4** [Jackett/Jackett#2454]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett Version 0.8.602.0:  
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
they renewed their certificate today, I assume it's already fixed by now.
