### ISSUE TITLE
Test Fails when Getting 301 Redirect

### ISSUE THREAD

**Issue by Hossy** [Jackett/Jackett#2456]
Opening a separate issue to track this in general as it would not be specific to an individual tracker.

During troubleshooting with @zero77 on https://github.com/Jackett/Jackett/issues/2449, we found that changing the site link to the final URL in the 301 redirect chain resolved the problem with failing tests.

IMHO, Jackett should not fail a test because of a redirect, which is a valid HTTP return code.  Further, without digging into this (even just testing with a browser), it is not evident to the user that a redirect is involved.  So, the user has a lower chance of resolving this because there is no information other than a failure being provided.  Just follow the redirect. :-)

**Comment by kaso17** [comment]
We can't just blindly follow the redirect as it's used for login failure/relogin detection by plenty of indexers.
But I added domain change detection with a corresponding suggestion to change the URL via f89c9769be0e9ba454aa94b6fa0e0128224d6850
This should help troubleshooting issues like this.
