### ISSUE TITLE
[scenetime] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by RossD327** [Jackett/Jackett#2457]
I have added Scenetime to Jackett.
 Tried manual search within Jackett and of course on the Indexer site to verify.  No results regardless of search.

Running Windows version of Jackett , Win7
Jackett v0.8.618

Any suggestions would be appreciated

Ross

-------------------------------

**Comment by garfield69** [comment]
Assuming that you have correctly added the recapcha cookie strings to the Jackett SceneTime Idexer config, then the next step is to produce a full enhanced log so we can take a look for clues.
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.

**Comment by RossD327** [comment]
Thank you for the response. I did apply UN/PW hash as instructed. Sorry that attachment didn't apply the first time, not sure what happened there.
R
[log.txt](https://github.com/Jackett/Jackett/files/1654725/log.txt)

R

**Comment by garfield69** [comment]
the log shows you are being redirected to the login page, which implies that the cookie data you provided was either incorrect or incomplete or else something has changed with the site.
But that is about all I can do for you, so now I'll invite @kaso17 to continue this analysis.

**Comment by kaso17** [comment]
works perfectly fine for me, please double check your cookies again.

**Comment by RossD327** [comment]
Thank you. I tried the User Profile section of the site as opposed to the Search section of the site and that hash worked first try. 
Thank you for the assistance.
Ross

**Comment by 1c3bolt** [comment]
Cant do any search. I get values from the first 100 rows after that if the item being searched isn't there then it returns zero

**Comment by kaso17** [comment]
@1c3bolt most indexers only support search results from the first page. See #975
