### ISSUE TITLE
[Fuzer] - Add option to fetch by IMDB Id

### ISSUE THREAD

**Issue by BuSHari** [Jackett/Jackett#2461]
Hi,

Can you please add the option to search by IMDB Id?
If i'm searching in Fuzer website by the id i'm getting the resluts, but if i try to search from Jackett i get no results (tt4901306)

Thanks,
Idan

**Comment by kaso17** [comment]
fone via ac9274c540f10240061a2b14265da7d031c05aa2

**Comment by BuSHari** [comment]
Thanks @kaso17 , but now the indexer isn't working at all
I've tried to search for 'Perfetti sconosciuti' or 'tt4901306'
see log: 
[log.txt](https://github.com/Jackett/Jackett/files/1657448/log.txt)

**Comment by BuSHari** [comment]
@kaso17 Please reopen the issue

**Comment by kaso17** [comment]
another change pretty much broke jackett, see #2463
