### ISSUE TITLE
[demonoid] Exception (demonoid): String was not recognized as a valid DateTime.: Parse error (Test)

### ISSUE THREAD

**Issue by JZXPacky** [Jackett/Jackett#2465]
Have been using Demonoid since installation and this has started failing since 4 days ago. After restarting the system and testing, here is the error.

[https://pastebin.com/Ke7p88kG](url)

Jackett version:  0.8.588.0
Mono version (if not using Windows):  5.4.1.7

-------------------------------

**Comment by garfield69** [comment]
Duplicate of #2458 fix has been issued but pre(release) not yet published.
