### ISSUE TITLE
Issues when trying to download from CouchPotatoe/Radarr via torrent9

### ISSUE THREAD

**Issue by Djal94** [Jackett/Jackett#2470]
Hi, i have a problem with torrent9 indexer in Jackett.
I'm on a seedbox (QuickBox).
I manage to make a search via torrent9, it's ok from Jackett and from CouchPotatoe/Radarr, but when i'm trying to download (either from Couch or Radarr), there is an error : 

![image](https://user-images.githubusercontent.com/35771339/35338273-bf39e8d4-011d-11e8-8d8c-81095d0e30ab.png)

**Comment by Djal94** [comment]
Just a thing, it's working well with "cpasbien" and "yggtorrent" indexer, with the same config.

**Comment by Djal94** [comment]
Ok nice thanks. Can i make the modification myself?

**Comment by garfield69** [comment]
I'll work on it tonight (my local time) when I next have free time. As soon as I figure out the regex I'll post a fix.

**Comment by Djal94** [comment]
Thanxs a lot ;)

**Comment by Djal94** [comment]
Thanks, I've edited the torrent9.yml file to make the changes and now, I can't see this indexer anymore after restarting Jackett?!?

**Comment by garfield69** [comment]
turn on the enhanced logging and restart jackett. look at the start of the log and you will probably find that your torrent9 failed to load because of a syntax error.

**Comment by Djal94** [comment]
Thanks, it works
