### ISSUE TITLE
[Req] Add ExtraTorrent.ag as a new Tracker

### ISSUE THREAD

**Issue by Daptonic** [Jackett/Jackett#2478]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.8.626.0
Mono version (if not using Windows):  

-------------------------------
Please add ExtraTorrent.ag as a new Tracker. This is an official replacement for ExtraTorrent.cc.

Thanks!

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by garfield69** [comment]
https://extratorrent.ag/ has been returning **SQL Query Error.** for five days now.
Broken, gone, or moved to a new domain?

**Comment by garfield69** [comment]
https://extratorrent.ag/ currently returning cloudflare 522 followed by an offline cloudflare cache-copy
just me, or is the site broken, gone, or moved to a new domain?

**Comment by garfield69** [comment]
back online.

**Comment by garfield69** [comment]
offline again, cloudflare 521

**Comment by garfield69** [comment]
back online

**Comment by garfield69** [comment]
oh boy. https://extratorrent.ag/ now returning SQL Query Error.

**Comment by garfield69** [comment]
back online.

**Comment by garfield69** [comment]
https://extratorrent.ag/ returning SQL Query Error. . . Again.

**Comment by garfield69** [comment]
the https is returning `Cloudflare 525 SSL handshake error` and the http is returning `Cloudflare 520 Web server is returning an unknown error`

**Comment by garfield69** [comment]
back online.

**Comment by garfield69** [comment]
https://extratorrent.ag/ returning SQL Query Error. . . Again.

**Comment by garfield69** [comment]
offline

**Comment by garfield69** [comment]
the web site does not return any results when using the search.
the _popular torrents_ page and the _today torrents_ pages work so its just the SE that is stuffed.

**Comment by coolvicky2** [comment]
can you put back , extratorrents.ag please

**Comment by garfield69** [comment]
The sites' search engine is still not working, returning 0 results for any keyword search.
Once their search engine is fixed will certainly upon notification, add the indexer back.

**Comment by garfield69** [comment]
#8186

**Comment by ilike2burnthing** [comment]
ERR_NAME_NOT_RESOLVED

[UpTrends](https://www.uptrends.com/tools/uptime) shows it as up for 8 locations and a mix of errors for the other 35. Down for anyone else?

**Comment by garfield69** [comment]
https://extratorrent.ag/ returns ERR_NAME_NOT_RESOLVED but the proxy https://extratorrent.unblockit.me/ is still working for me at the moment, with the latest torrent added  3 minutes ago, apparently.

**Comment by ilike2burnthing** [comment]
Proxy is down now too

**Comment by ilike2burnthing** [comment]
Proxy is back up, still can't reach .ag

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
offline returning 520 and getting cloudflare retry for live version

**Comment by ilike2burnthing** [comment]
.ag is working for me (browser and Jackett), but it's very slow. Will check back tomorrow to see if it's improved any.

**Comment by ilike2burnthing** [comment]
.ag has been up though today, just slow
proxy also back up now

**Comment by garfield69** [comment]
not for me.
![image](https://user-images.githubusercontent.com/6933240/83938452-75660580-a828-11ea-912b-9636c4402eb5.png)

**Comment by ilike2burnthing** [comment]
Seems to be working fine again here. How about on your end?

**Comment by garfield69** [comment]
nope. still seeing `sql error` with my browser and `Found no results while trying to browse this tracker` with  Jackett.

**Comment by garfield69** [comment]
@ngosang  is this indexer working for you?

**Comment by ngosang** [comment]
No. `SQL Query Error.`

**Comment by garfield69** [comment]
@ilike2burnthing  how are you testing this domain?
are you using the Jackett test button for the indexer with the site link set to https://extratorrent.ag/, or using your browser to directly access https://extratorrent.ag/ ?
anything other method is not valid.

**Comment by ilike2burnthing** [comment]
Weird...
I tested again, browser and Jackett, still working here.
.ag is very slow, proxy is better but not great. Both are working for me though.

**Comment by garfield69** [comment]
I get keyword search results
But keywordless searches still fail intermittently, with sql error. Sometimes it works.
But not reliable ATM.

**Comment by ilike2burnthing** [comment]
Just got SQL Query Error (and proxy is down), guessing I've just been getting lucky up to now

**Comment by garfield69** [comment]
https://extratorrent.ag/search/?search=reach 
returning Error 520 Web server is returning an unknown error
if its not up in the next 6 days i'm deleting this indexer.
if it come up and goes back down within the next 6 days i'm deleting this indexer
if it sneezes, looks at me sideways or talks dirty i'm deleting this indexer.

**Comment by garfield69** [comment]
can anyone get a keyword search working on this site directly?
if not, then I'll delete this indexer this evening.

**Comment by ilike2burnthing** [comment]
Nope :/

I'll keep an eye on the site and if it ends up being stable for a month or something, I'll comment here if that's alright

**Comment by coolvicky2** [comment]
it's working perfect fine for now let's hope for the best

**Comment by ilike2burnthing** [comment]
Already been removed, and searching still fails
