### ISSUE TITLE
[REQ] YTS now started publishing 2160p quality 

### ISSUE THREAD

**Issue by ZshlomiA4** [Jackett/Jackett#2479]
Hello,
As stated in the subject,
YTS has now began to release small size 2160p quality movies,
but the indexer is capable up to 1080p quality.

Could the 2160p quality be added to YTS?

Jackett version:  0.8.618.0
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
can you post the name of a movie that yts has made 2160p available? The site's search quality pull downs still only list 720p, 1080p, 3D ... may have to wait until they update their site search engine.

**Comment by ZshlomiA4** [comment]
of course,
adding a direct link to the movie:

https://yifymovie.co/movie/jupiter-ascending-2015

btw, YTS changed their address (again) to:
yifymovie.co.

yts.me + yts.pe are redirected to that address.

**Comment by ZshlomiA4** [comment]
P.S
they started (i believe) with the best movie in the last decade:
Deadpool!!!
https://yifymovie.co/movie/deadpool-2016

**Comment by garfield69** [comment]
OK well that explains why I am seeing different results.
Jackett's yts.ag indexer points to https://yts.am/ 

So https://yifymovie.co is a completely different site.

**Comment by garfield69** [comment]
I've created a YIFY indexer that uses the yifymovie.co address and supports UHD.  Should be availabel in the next pre(release) that gets published.

**Comment by ZshlomiA4** [comment]
SWEET.
Thank you very much :)
