### ISSUE TITLE
[rarbg] Exception (rarbg): Error: NameResolutionFailure: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by tontonwalace** [Jackett/Jackett#2483]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
I don't have any problems using rarbg with Jackett 0.8.626 on my win7 platform.
Help us to help you by providing the requested info bytes above: The version of your Jackett, the mono version (if not using windows), and an enhanced log so we can search for clues.
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.
