### ISSUE TITLE
No row results with correct selector

### ISSUE THREAD

**Issue by Albvadi** [Jackett/Jackett#2486]
Jackett version:  0.8.602.0
Mono version (if not using Windows):  Windows 7

-------------------------------
Defining a new tracker, I have problems retrieving the rows:
![image](https://user-images.githubusercontent.com/6285255/35442646-46bfe002-02a8-11e8-85af-9adce00e5c74.png)

With this definition:
```yaml
rows:
      selector: "#Mcol table:not(.lista)+table tr:not(:first-child)"
      filters:
          - name: strdump
```

I obtain no results and no info debug from strdump:
```log
01-26 14:48:36 Debug Saving new config file: C:\ProgramData\Jackett\Indexers\torrentland.json.20ab94b67b8a4ff19cbf614bd3fda8b5.tmp
01-26 14:48:36 Info Manual search for "matrix" on torrentland with 0 results.
```

The HTML returned in logs it´s correct and same from web browser.
Any idea what it´s wrong?

**Comment by kaso17** [comment]
might be a bug in the anglesharp selector engine or the content is dynamically generated by javascript (and not seen by jackett).
Can you share the HTML output of the complete page (before javascript is executed)?

**Comment by Albvadi** [comment]
I don´t know what´s happening, but the selector I posted in last post, it´snt working today...
I just tried another selector (`#Mcol table.table-inverse+table.table-inverse tr:not(:first-child)`), it worked correctly, I refreshed the page and it does not work anymore ...

I attach the html file here: [torrentland.txt](https://github.com/Jackett/Jackett/files/1676905/torrentland.txt)

**Comment by kaso17** [comment]
`table.table-inverse ~ table.table-inverse > tbody > tr:not(:first-child)` should work
The ~ is a looser variant to the + combinator.
+ means that the element immediately is preceded by the sibling
~ means that the element is preceded by the sibling (not immediately)
In this case ~ is needed due to the various <if...> tags.

**Comment by Albvadi** [comment]
Fantastic, your selector works perfectly.
I had no idea of the ~ symbol. Thanks for the explanation.

One more question. It´s possible get any attribute from the tr itself?
In many trackers, the freelech or silver status it´s indicated only in a class in the tr...

**Comment by kaso17** [comment]
Just don't specify any selector at all in this case (if no selector is specified the row element is "selected")

**Comment by Albvadi** [comment]
I don´t understand... :confused:
For example, in the html provided, a single row has the next html:
```HTML
<tr class="font-gray" style="background: #a9a9a9">
  <!-- modificacion titelas : color verde para cuando hay freeleech -->
  <td>
    <a href="https://torrentland.li/index.php?page=torrents&amp;category=66" data-ss1517300780="1"><img src="./torrentland_files/1080.png" border="0" alt="HD 1080" title="HD 1080" data-pagespeed-url-hash="4108509281" onload="pagespeed.CriticalImages.checkImageForCriticality(this);"></a>
  </td>

  <td>&nbsp;&nbsp;
    <a href="https://torrentland.li/index.php?page=torrent-details&amp;id=e3b4253ea65a537de950a3a774f62c4374957a08" onmouseover=" return overlib(&#39;&lt;img src=torrentimg/e3b4253ea65a537de950a3a774f62c4374957a08.jpg width=200 border=0&gt;&#39;, CENTER);" onmouseout="return nd();" data-ss1517300780="1">Matrix (1999) Bluray 1080p ESP AC3 5 1 ING AC3 5 1 x264   Eml HDTeam</a>&nbsp;
    <img title="Release EML HDTeam." src="./torrentland_files/scene.png" data-pagespeed-url-hash="963062624" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
  </td>



  <td>
    <a href="https://torrentland.li/download.php?id=********&amp;f=Matrix+%281999%29+Bluray+1080p+ESP+AC3+5.1+ING+AC3+5.1+x264+-+Eml+HDTeam.torrent" data-ss1517300780="1"><img src="./torrentland_files/download.gif" border="0" alt="Descargar Torrent" title="Descargar Torrent" data-pagespeed-url-hash="2799758473" onload="pagespeed.CriticalImages.checkImageForCriticality(this);"></a>
  </td>
  <td>
    <a href="https://torrentland.li/smf/index.php?topic=27441" data-ss1517300780="1"><img src="./torrentland_files/foro2.png" border="0" alt="Ir al Foro" title="Ir al Foro" data-pagespeed-url-hash="900105740" onload="pagespeed.CriticalImages.checkImageForCriticality(this);"></a>
  </td>
  <td>
    <a href="https://torrentland.li/index.php?page=bookmark&amp;do=add&amp;torrent_id=e3b4253ea65a537de950a3a774f62c4374957a08" data-ss1517300780="1"><img src="./torrentland_files/anadirfav.png" border="0" title="Añadir a favoritos" data-pagespeed-url-hash="2145599886" onload="pagespeed.CriticalImages.checkImageForCriticality(this);"></a>
  </td>
  <td>16.88 GB</td>
  <td>28/11/2017</td>
  <td>
    <a href="https://torrentland.li/index.php?page=peers&amp;id=e3b4253ea65a537de950a3a774f62c4374957a08" title="Click aqui para ver los detalles de los peers" data-ss1517300780="1">2</a>
  </td>
  <td>
    <a href="https://torrentland.li/index.php?page=peers&amp;id=e3b4253ea65a537de950a3a774f62c4374957a08" title="Click aqui para ver los detalles de los peers" data-ss1517300780="1">0</a>
  </td>
  <td>
    <a href="https://torrentland.li/index.php?page=torrent_history&amp;id=e3b4253ea65a537de950a3a774f62c4374957a08" title="History - Matrix (1999) Bluray 1080p ESP AC3 5.1 ING AC3 5.1 x264 - Eml HDTeam" data-ss1517300780="1">6</a>
  </td>
  <td align="center">
    <a href="https://torrentland.li/index.php?page=userdetails&amp;id=3623" data-ss1517300780="1"><span style="color:#2c36f9">Sparda</span></a>
  </td>
</tr>
```
How can I get the class attr from the tr tag to use in another field?? `font-gray` in this case?

**Comment by garfield69** [comment]
>How can I get the class attr from the tr tag to use in another field?? font-gray in this case?

something like this perhaps?
```yaml
      grabfont:
        selector: 
        attribute: class
```
or did kaso17 mean this:
```yaml
      grabfont:
        attribute: class
```

**Comment by Albvadi** [comment]
OMG.... 🤦‍♂️

It had not fallen that the initial tr is part of the available code and I can reference it that way. I thought that only what was inside was available ...

Thanks so much for pointing me out this.
