### ISSUE TITLE
MVGroup Torznab Integration searches do not conform to MVGroup naming scheme

### ISSUE THREAD

**Issue by hechz** [Jackett/Jackett#2488]
After having added MVGroup Forum and Main indexers, manual search succeed, but searches from Sonarr fail. When the search is executed by Sonarr 

The search terms show as "Attenboroughs Life That Glows S01E01"
However, MVGroup doesn't number single episode releases, Manual search for "Attenboroughs Life That Glows" suceeds.
Can an option to disable the appending of the  passed parameters "&season=1&ep=1" be made available?

Jackett version:  0.8.629.0
Mono version (if not using Windows):  
Mono JIT compiler version 4.6.2 (Stable 4.6.2.16/ac9e222 Mon Feb 20 21:24:38 CST 2017)

**Comment by kaso17** [comment]
@garfield69 can you have a look?

**Comment by garfield69** [comment]
commit 5e4022cc43dd385975e7b8f707735c7d6224a715 will be included in the next (pre)release of Jackett whenever that happens next.

**Comment by y4m4aa** [comment]
this is somehow not working for me. with the box checked jackett log says "Found 0 releases from MVGroup Main for: Blue Planet II S01E02" when i search from sonarr.

**Comment by y4m4aa** [comment]
strange... thats exactly what i did.

**Comment by garfield69** [comment]
Have you checked  that your sonarr indexer URL is using the torznab path of the *main* mvgroup, and not the *forum* by any chance?

**Comment by y4m4aa** [comment]
yes checked that. I have only the main mvgroup in jackett and it shows up in the log of jackett. But it trys to search with S01E02 at the end. Other trackers work perfectly fine in jackett. Could it be that i use a different sonarr version? my version is 2.0.0.5228. Jackett version 0.10.12.0

**Comment by garfield69** [comment]
Apologies. I've just upgraded jackett and  sonarr and I see that the searches are returning no results as you reported the first time. Looking at the jackett logs I think I see what the problem is and I'll have a go trying to fix it.

**Comment by y4m4aa** [comment]
great thanks so much!

**Comment by garfield69** [comment]
so when i first tested this for you, i searched with sonarr for the first episode of *blue planet II* and got 
![image](https://user-images.githubusercontent.com/6933240/43807462-a395b5e4-9afc-11e8-9aef-2f73661bb829.png)
which was why i said it was working the first time.
 jackett returned 24 entries to sonarr, and it picked 3 of them..
but after you said you could still not get it working, i repeated the search  but looking for episode 2.,  however sonarr  returned *not found*.
so i thought to add code to the jackett mvgroup main indexer, and strip out the s01e02. however,  even though jackett returned the same 24 entries, sonarr picked the same 3 entries for ep2 as it did for ep1.
im puzzled.  
ill keep digging, but no quick answers forthcomming. this could take me a while.

**Comment by garfield69** [comment]
I invite any of the other jackett developers to take a look and offer a solution, if one is available. I personally cant come up with a solve for this so far.
