### ISSUE TITLE
Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /spksrc/spk/mono/work-88f6281-6.1/mono-5.4.1.6/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by suisuneko** [Jackett/Jackett#2491]
Hi there,
i'm getting lots of ssl handshake errors lately...happens on all trackers i tried to add. Started sometime after updating to the latest DSM Version on my DS413j, worked without any hiccups before that.

Currently running ->
Jackett version:   0.8.602.0
Mono version (if not using Windows): 5.4.1.6-9
DSM Version: DSM 6.1.4-15217 Update 5

Any ideas? Couldn't find any similar errors nor Google could help me :)

**Comment by garfield69** [comment]
Try reimporting the certificates in this case:
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
    or `sudo wget -O - https://curl.haxx.se/ca/cacert.pem | sudo cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`
  - On QNAP refer to #2111

and reboot (or just restart all Jackett services) after the imports are completed.

**Comment by suisuneko** [comment]
@garfield69 you saved my life :) Thank you so much

used the QNAP reference and used following command to get it working on my Synology:
- download the cacert.pem with "wget https://curl.haxx.se/ca/cacert.pem"
- Import the CA's with cert-sync "/volume1/@appstore/mono/bin/cert-sync /tmp/cacert.pem"
- Reboot the Synology NAS
- DONE

**Comment by DrMacinyasha** [comment]
Had the same issue myself on Synology. Ran these two commands and **afterwards** restarted Jackett from DSM, didn't have to reboot the whole NAS:

`wget https://curl.haxx.se/ca/cacert.pem`
`sudo /volume1/@appstore/mono/bin/cert-sync ./cacert.pem`

**Comment by matelons** [comment]
@DrMacinyasha 
Hi. Did the same but same error again after restarting Jackett

**Comment by Snowaks** [comment]
What would the command be for FreeBSD

wget https://curl.haxx.se/ca/cacert.pem did not work

**Comment by ilike2burnthing** [comment]
Try:
https://github.com/Jackett/Jackett/issues/12341#issuecomment-957585781
and if that doesn't work see the discussion here:
https://github.com/fulder/iocage-plugin-jackett/issues/4#issuecomment-944931404
