### ISSUE TITLE
[torrentday] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by hopfrogpoe** [Jackett/Jackett#2494]
Tracker for torrentday was working yesterday but this morning it's throwing this error and returning no results. The site seems to be working fine though.

Jackett version:  0.8.629.0
Mono version (if not using Windows):  4.2.3
Log: [log.txt](https://github.com/Jackett/Jackett/files/1671019/log.txt)

-------------------------------

**Comment by hopfrogpoe** [comment]
And now, without changing anything, it's saying my cookie is wrong even if I grab the current cookie data and try to edit it.

**Comment by xMrWhite** [comment]
Dupe of #2493

**Comment by pcliff069** [comment]
Issue seems to be with the Torznab URL through Jackett.
Copying RSS feed from TD seems to work fine

**Comment by hopfrogpoe** [comment]
So no fix as of right now or am I missing something?

**Comment by garfield69** [comment]
Duplicate of #2493
