### ISSUE TITLE
[passtheheadphones] Something went wrong. You have 5 attempts remaining. (Config)

### ISSUE THREAD

**Issue by csmithere** [Jackett/Jackett#2497]
I use MFA on most of my trackers, which is presumably why I'm getting a permission denied.  I'm assuming this is a non-starter w/Jackett, or is it dependent on the tracker and whether or not the API is exposed w/o it?

Thanks
csmithere
-------------------------------
Mono JIT compiler version 5.4.1.7 (tarball Wed Jan 17 20:26:34 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

**Comment by kaso17** [comment]
yes, 2FA authentication is usually not supported by jackett indexers (pull requests to change this are welcome)
