### ISSUE TITLE
Jackett service constantly consuming 15-18% CPU

### ISSUE THREAD

**Issue by nordicblue** [Jackett/Jackett#2498]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.8.629.0 running as a service
Windows Server 2012 R2 | .NET 4.7.1
-------------------------------
Trying to find out why Jackett is constantly consuming ~15% of my CPU. I've gone as far as stopping my indexer services using Jackett, and thre CPU still sits at 15 to 20% CPU. What is Jackett doing that takes a constant 15% CPU utilization please? I love Jackett, but it's hard to give up 15% of 2 Xeon processors to use it.

Thanks!

**Comment by supremacy2k** [comment]
Try Disabling auto-update and restart, and see if that helps. 

On docker it uses 100% cpu after an update.

**Comment by nordicblue** [comment]
@supremacy2k , thanks for the suggestion. I attempted that, but with no luck. This morning, in reviewing the server CPU,  it was up at 25% CPU by Jackett. A restart of the service will return things to normal levels, so what I have done for now is setup a powershell script to execute at 4am daily to restart the service. I'll keep an eye on it, during the day today, to see if I see it spike up again. Alternatively, might also look at powershell to check the CPU use by Jackett service and, if high, then restart. Open for any other suggestions. Thanks!

**Comment by supremacy2k** [comment]
Are you sure det auto-update is disabled in Jackett?
It checks for updates every night.

**Comment by nordicblue** [comment]
![image](https://user-images.githubusercontent.com/24925360/35539066-1a2ac17e-051e-11e8-9c46-819f397e73cc.png)

I see that a new release came out today. Going to install it and let's see if it's better with this release.

**Comment by Zuescho** [comment]
I have the same problem, got the new release and still have the problem off around 30% CPU usage. But the docker even says that Jackett is going for 100% CPU Usage.

**Comment by nordicblue** [comment]
The newest release did not work, so I am starting to load older releases to see if I can pinpoint the release that this became an issue for me on (downfall of me having the auto update enabled before and not keeping a closer eye on the resources).

I am currently, back down to Version 0.8.578.0 and so far Jackett hasn't jumped over 3%, mostly sitting at 0%. All newer releases from there had this issue for me. It has only been running for about an hour, so not 100% yet whether this release is good for or not. Will update a little later on. 

Definitely not giving up Jackett, though, I love the ease of use of it too much. Thanks to everyone who have put all the effort into this amazing software for us, you are a Godsend:)

**Comment by Zuescho** [comment]
I'm a Docker Noob and back to 0.7.1499.0 clicked update back to 0.8.637.0 is there any way to update to another version?

**Comment by kaso17** [comment]
Looking forward to your findings.
I can't think of anything which might cause this.

For the docker uses: please make sure auto updates are disabled, updating jackett in the docker image is not supported by the image, please see #2198

**Comment by Zuescho** [comment]
Just for the records i downgraded my Jackett Docker to v0.8.578 and will also keep an eye on it.

**Comment by nordicblue** [comment]
0.8.578.0 did not fix the problem. 

My thought process is that something that is installed on the server is interfering with Jackett and causing my issue. To confirm this, I installed Jackett on another Server 2012 R2 to see if the issue persists over servers. 

The reason that I went this route is that the issue seemed to start around the time that I started using Plex Live TV/DVR and it looks like the CPU jumps high right about the same time a live feed (transcode) starts. Point being, my issue might not be the fault of Jackett as a service, but something else with my configuration. 

So far, Jackett has been running on the other server since yesterday afternoon and so far no jumps in CPU that I have been able to catch. If I can get to tonight with it, with no CPU jumps, I will consider this not a Jackett issue, but something with my server setup (highly likely, at this point).

**Comment by nordicblue** [comment]
Moving the service to a different server from my Plex server has corrected the issue. Not a 100% sure, but it somehow may seem to relate to when the plex transcoder runs, that the Jackett Service spikes and stays up at that 15-18% mark. 

For now, I am going to keep it on a separate VM and I will close this ticket as an issue on my side instead of with Jackett. 

P.S. After I let it run for a few days, I upgraded to the latest release. It has also been running a few days without any issues at all.
