### ISSUE TITLE
[ilcorsaronero] Exception (ilcorsaronero): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /SRC/mono-5.4.1.6/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#2503]
Hi

my system is a Qnap
Jackett at the latest version (0.8.637.0)
mono version mono-5.4.1.6

since few days I've this error from this traker, here the log:
https://pastebin.com/vazeYWby

I already set this fix in my mono.sh and also make it via ssh session but no lucky in my case
https://github.com/Jackett/Jackett/issues/2111

Let me know if you need more data or tests

Tnx, Jo

**Comment by gmatranga86** [comment]
Hi

same problem here.
Jackett Version 0.8.629.0
Mono JIT compiler version 5.4.1.6

Already try all the fixes found with cert-sync but the problem still happening.

Thanks,
Giulio.

**Comment by gmatranga86** [comment]
@Jorman: do you still have the problem? There is a new update of Jackett but i have the same problem :(

**Comment by manu67a** [comment]
Ahd the same issue and solved it by updating to the latest version

**Comment by gmatranga86** [comment]
@manu67a: i have Jackett v0.8.656 and still have the issue
which version of mono do you have?

**Comment by manu67a** [comment]
mono version is 5.4.1.7-0xamarin1+debian9b1 on debian 9.3

**Comment by gmatranga86** [comment]
no way :(

with Jackett Version 0.8.656.0 and Mono JIT compiler version 5.8.0.108 when i'm testing the tracker 'ilcorsaronero' still jave the error 'Exception (ilcorsaronero): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED'

i'll wait for a fix

thank you @manu67a

**Comment by kaso17** [comment]
please update to v0.8.663

**Comment by gmatranga86** [comment]
@kaso17 can you tell us where do you found the new certificate ca cert?

Thank you, 
Giulio.

**Comment by kaso17** [comment]
just used my browser to get the current certificate and updated the thumbprint in the definition
