### ISSUE TITLE
[kickasstorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#2504]
Hi

my system is a Qnap
Jackett at the latest version (0.8.637.0)
mono version mono-5.4.1.6

since few days I've this error from this traker, here the log:
https://pastebin.com/xmJCqjZ0

Let me know if you need more data or tests

Tnx, Jo

**Comment by garfield69** [comment]
Duplicate of #2280
