### ISSUE TITLE
[shareisland] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#2505]
Hi

my system is a Qnap
Jackett at the latest version (0.8.637.0)
mono version mono-5.4.1.6

since few days I've this error from this traker, here the log:
https://pastebin.com/UKKc1SZg

Let me know if you need more data or tests

Tnx, Jo

**Comment by garfield69** [comment]
Duplicate of #2389
