### ISSUE TITLE
[torrentday] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Steven-Harris** [Jackett/Jackett#2507]
Jackett version:   0.8.629.0

using latest docker version if that helps
-------------------------------

I have tried manually editing the torrentday.json and pointing to both torrentday.it and torrentday.com urls to see if that helped. nothing.

**Comment by martinezconcepts** [comment]
Jackett Version 0.8.629.0
synology docker:  linuxserver/jackett:latest

i had the same problem for the past day or two, i restarted docker (no luck), checked for updates (yellow button under Jackett Configuration), and now

Jackett Version 0.8.637.0
and it is working again!!!

good luck

**Comment by Steven-Harris** [comment]
@martinezconcepts you're a dang genius! thanks!

**Comment by garfield69** [comment]
Duplicate of #2493
