### ISSUE TITLE
[yts] Parse error: Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by ZshlomiA4** [Jackett/Jackett#2511]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:   0.8.637.0
Mono version (if not using Windows):  

-------------------------------

**Comment by thewillwilson** [comment]
Also had the same issue as you.

**Comment by kaso17** [comment]
fixed via 2fb3d52b44c1d1ac9f74d637a15b2f3a210297db
