### ISSUE TITLE
[rarbg] An error occurred while sending the request: Error: SecureChannelFailure (One or more errors occurred.) (Config)

### ISSUE THREAD

**Issue by JC128** [Jackett/Jackett#2512]
Hi all.  I am trying to set up this program, but have never used it before, nor have any programming knowledge either sorry.  I also apologise if this query is appearing in the incorrect spot.

I have access to rarbg website on my computer, but something in my setup of Jackett is not correct and I am not able to save rarbg as an indexer, the following pops up in a red box:
An error occured while configuring this indexer
An error occurred while sending the request: Error: SecureChannelFailure (One or more errors 

I don't think this is program error, but rather my lack of knowledge with the correct setup.  I would appreciate any suggestions.

For what it is worth, I also am not able to add this indexer in Sonarr.

Jackett Version 0.8.637.0
Mono 5.4.1.6-9
Synology 218+

I cannot find the log to attach either sorry, the best I could find is

Jan 30, 2018 11:50:50 PM | Error | On attempt 3 checking for results from RARBG: An error occurred while sending the request
-- | -- | --
Jan 30, 2018 11:50:49 PM | Error | On attempt 2 checking for results from RARBG: An error occurred while sending the request
Jan 30, 2018 11:50:48 PM | Error | On attempt 1 checking for results from RARBG: An error occurred while sending the request
Jan 30, 2018 11:50:44 PM | Error | On attempt 2 checking for results from RARBG: An error occurred while sending the request
Jan 30, 2018 11:50:44 PM | Error | On attempt 1 checking for results from RARBG: An error occurred while sending the request

Regards
Jac

**Comment by kaso17** [comment]
This is often caused by missing CA certificates.
Try reimporting the certificates:
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`

**Comment by JC128** [comment]
Ah thanks.  I will try that tonight and let you know how I go.

**Comment by JC128** [comment]
I have installed the certificates but there still seems to be an error.  The secure channel error is still showing.

**Comment by kaso17** [comment]
please post the output of `curl -v https://rarbg.to/`

**Comment by JC128** [comment]
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
> GET / HTTP/1.1
> Host: rarbg.to
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Sun, 04 Feb 2018 04:18:16 GMT
< Content-Type: text/html
< Content-Length: 0
< Connection: keep-alive
< Location: /index8.php
< Accept-Ranges: bytes
< Strict-Transport-Security: max-age=15768000; includeSubdomains; preload
<
