### ISSUE TITLE
Can't change non-working domain of a tracker

### ISSUE THREAD

**Issue by Hackerpcs** [Jackett/Jackett#2513]
Jackett version:  0.8.637.0

-------------------------------

Trying to change the non working domain of a tracker to a working one
https://nnm-club.name/ to https://nnm-club.me/,
https://vk.com/nnm_club?w=wall-13695159_28045
results in
`Request to Jackett server failed`
Log:
https://pastebin.com/rtgJGFfR

**Comment by garfield69** [comment]
I get the same error when trying to add that indexer for the first time.
May have something to do with the DNS not finding the nnm-club.name’s server IP address ?      
I don't have problems making changes to any of the other indexers (tried a bunch of random public, semi and private ones), so the issued is specific to the no-name-club address.
Anyway, commit 85f522b changes the domain for this indexer from .name to .me.
