### ISSUE TITLE
Special search parameters for Avistaz search

### ISSUE THREAD

**Issue by Dnkhatri** [Jackett/Jackett#2520]
Would it be possible that jackett omits the S01 in search  as on avistaz the first season is not used in the naming for the episodes. And tvdb rarely has absolute numbers so setting the show as anime does not work in sonarr either.  If a show has a 2nd season which is rare the S02 is used but the original episode numbers won't be changed.  I have asked the avistaz mod about changing the naming convention but even if they do it won't make the earlier releases searchable. Same thing searching for whole shows does not work either as most shows full season pack are actually full show packs so are only named with complete with no mention of the season so jackett gives no result for the search either. 
I think these modification are needed to make use of avistaz in jackett properly. I personally think these modifications are better suited in the avistaz tracker definition instead of making any special changes in sonarr as it would allow avistaz to work with other app like sonarr as well.

**Comment by kaso17** [comment]
The naming seems to be very inconsistent, there are plenty of releases containing S01 too.
Their search engine apparently only works on word boundaries so if we simply strip S01 from the search it won't find releases with proper tags.
E.g.:
https://avistaz.to/torrents?in=1&search=+Sana+Dalawa+ang+Puso+S01E10&type=2&tags=&uploader=
vs
https://avistaz.to/torrents?in=1&search=+Sana+Dalawa+ang+Puso+E10&type=2&tags=&uploader=

I would suggest to continue trying to convince them to fix the naming rules or to improve their search engine so you can properly search for season/episode. They apparently track that information for TV torrents, so they just have to make it searchable.

**Comment by Dnkhatri** [comment]
Yes I get what you mean. I have asked them about it lets see. The best option with the current system I see is to just use the show name and quality. And let sonarr handle detecting of the episodes. They already have tv show and movie search restrictions so going with below would work. But I am not sure if jackett has the ability to use different searches if the query is from sonarr for a tv show or from radarr for a movie
https://avistaz.to/torrents?in=0&search=Sana+Dalawa+ang+Puso&type=2&tags=&uploader=

**Comment by Dnkhatri** [comment]
After trying a few times to convince avistaz mods of fixing the problem with no results. I am wondering what will I have to do to modify the avistaz definitions in jackett to just search for show name. As trying that in manual search works yes it give results of all episode but it is better than getting no results at all currently.

**Comment by kaso17** [comment]
b9b5b3a442b09a5ab1c1b7815f0d3a81aaef1f38 should fix your problem

**Comment by Dnkhatri** [comment]
Thanks for this it solves 90% of the problem for me. Now have to convince the sonarr developers to the show when have complete in the name instead of season.

**Comment by Dnkhatri** [comment]
Please revert this workaround as season numbers have been added to single episode releases now so the normal search works.
