### ISSUE TITLE
[speedcd] An error occured while updating this indexer

### ISSUE THREAD

**Issue by cretayo** [Jackett/Jackett#2522]
Jackett version:  Latest
Mono version (if not using Windows):  5.4.1.6.0

-------------------------------
This seems to still be a issue. Im getting when trying to add this tracker:
```
An error occured while updating this indexer
body{height:100%;background:url("/V3/img/index.png");font-family:"tahoma","arial","helvetica","sans-serif";font-size:8pt}h5{font-size:16px}Wrong Captcha!Please press back and try again.
Click here to open an issue on Github for this indexer.
```

Log:

When | Level | Message
-- | -- | --
Jan 31, 2018 01:41:46 PM | Error | {0}

**Comment by 19wolf** [comment]
Mar 06, 2018 12:29:15 PM | Error | {0}
-- | -- | --
Mar 06, 2018 12:29:15 PM | Error | headerString:
Mar 06, 2018 12:29:15 PM | Error | cookies:
Mar 06, 2018 12:29:15 PM | Error | request.RawPOSTDdata:
Mar 06, 2018 12:29:15 PM | Error | request.Referer: https://speed.cd/
Mar 06, 2018 12:29:15 PM | Error | request.Cookies:
Mar 06, 2018 12:29:15 PM | Error | request.Url: https://speed.cd/take.login.php
Mar 06, 2018 12:29:15 PM | Error | request.Method: POST
Mar 06, 2018 12:29:15 PM | Error | got NotImplemented/InternalServerError

**Comment by kaso17** [comment]
@19wolf you're using the legacy libcurl client, which mono version are you using and on which platform?

**Comment by kaso17** [comment]
@cretayo after a failed login attempt you've to sovle a catpcha (not supported by jackett), white list your IP again via a normal browser login and then redo the login via jackett.

**Comment by 19wolf** [comment]
Turns out I hadn't updated to the latest build, and was also on mono 4.2 for some reason. All fixed for me
