### ISSUE TITLE
[yggtorrent] Error: Ces identifiants sont invalides (Config)

### ISSUE THREAD

**Issue by Julien-404** [Jackett/Jackett#2523]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
I have no problems using yggTorrent on my win7 Jackett v0.8.647.
IF you are not on the latest version of Jackett then first upgrade.
From the error message you posted on the ticket title, it appears your login details are incorrect.
Confirm that you have used the correct username and password by using your browser to logon directly.
Then try again with the Jackett config.

**Comment by Julien-404** [comment]
Everythings work fine now, just have to reboot my server.
