### ISSUE TITLE
[torrentday] Your cookie did not work: Your cookie did not work

### ISSUE THREAD

**Issue by zwetje12** [Jackett/Jackett#2524]
I am trying to add TorrentDay as a tracker, since Captcha is not available from within Jackett, I use the full cookie header. I have copied the cookie header from the chrome browser as described in the manual provided by Jackett. However this does not work.

I have also tried to copy it from Firefox, same result.

**Comment by garfield69** [comment]
Are you using Jackett v0.8.647 ? 
if not upgrade and try again.

**Comment by zwetje12** [comment]
I am using Jackett Version 0.8.647.0

**Comment by garfield69** [comment]
@kaso17  what is the status with TD at the moment, are you able to use this indexer?

**Comment by konzolec** [comment]
I can confirm the latest version 0.8.647.0 works. I removed the old one and used the new one.

**Comment by zwetje12** [comment]
For some magical reason, readding the provider for the 10th time, it works.
