### ISSUE TITLE
[kinozal] An error occurred while sending the request: Error getting response stream (ReadDone2): ReceiveFailure (Config)

### ISSUE THREAD

**Issue by enchained** [Jackett/Jackett#2525]
Jackett version:  0.8.647.0
OS: Synology DSM 6
Mono version: 5.4.1.6-9 (synocommunity package)

-------------------------------
Logs just say this one line on every try to add kinozal (with Enhanced logging on):

`Feb 01, 2018 01:12:15 AM | Error | {0}`

Looks like it's a mono issue, but I don't know what to do with it. Can somebody help, please?

**Comment by kaso17** [comment]
please check the log.txt for the complete error message

**Comment by enchained** [comment]
Thanks, found this:
https://pastebin.com/H0tJG6a4

**Comment by kaso17** [comment]
looks like a general socket error.
do normal request outside of mono work?
Please try running e.g. `curl http://kinozal.tv/`

**Comment by enchained** [comment]
I sshd into my Sinology DSM, and `curl -v http://kinozal.tv/` returns trackers html as expected, no errors.

**Comment by enchained** [comment]
(I found you from other kinozal issues) @Mavrag, @ThiRaBrTNK 
I wonder if anybody else seems to have this problem too with kinozal?

**Comment by garfield69** [comment]
@enchained  kinozal still broken for you or has this been resolved?

**Comment by enchained** [comment]
@garfield69 kinozal started working after I replaced 'http://kinozal.tv' with it's https mirror 'https://kinozal.guru'. I think it's connected to provider's blocking which doesn't work over https.
