### ISSUE TITLE
AnimeBytes not working

### ISSUE THREAD

**Issue by kurenaitoichi** [Jackett/Jackett#253]
Website login works but I tried 3 times adding this tracker to jackett and it does not work.
I get the following error message: Configuration failed: Failed to login, 6 failed attempts will get you banned for 6 hours.
 I am 100% certain I typed the username/password correctly.

**Comment by TheLuckiest** [comment]
Same situation for me, not able to log in to AnimeBytes.

**Comment by Azerelat** [comment]
Login working fine here.

1. Is cloudfare protection active for you? It'll not work if so which is happening now and again.
2. Are you using tenticletastic (default) theme?
3. Try making your password alphanumeric only and let me know if it makes any difference.
4. Are you on windows?

**Comment by TheLuckiest** [comment]
It just started working for me yesterday, my apologies for wasting your time! I expect it was a hiccup on AnimeBytes' end.

Thanks!

**Comment by Azerelat** [comment]
Cool

Going to put this down to cloudfare which we can't do much about currently.

**Comment by kurenaitoichi** [comment]
Still not working for me.

1. Do you mean the site being offline and cloudflare showing the cached version? If so, then no.
2. Yes
3. Already alphanumeric
4. jackett is installed on linux and im accessing it via the web interface on a windows pc

Don't know if it makes a difference, but when I go to the site, it asks to confirm im not a robot using the google nocaptcha

**Comment by Azerelat** [comment]
We can't automate the captcha and that will cause it to fail.  Perhaps try getting a different ip address.

**Comment by AliShaikh94** [comment]
I'm still unable to log in to Animebytes, getting configuration error
