### ISSUE TITLE
omdb UTF-8 encoding error (Windows)

### ISSUE THREAD

**Issue by scottia** [Jackett/Jackett#2532]
Am using a valid omdb api key (menu setting) resulting in many errors similar to the following.  Is it an actual error?  Links are good when tested.

Feb 02, 2018 08:25:03 AM | Error | WebClient(HttpWebClient).GetString(Url:http://omdbapi.com/?apikey="myapikey"&i=tt4025798): No encoding detected, defaulting to UTF-8
-- | -- | --
Feb 02, 2018 08:25:03 AM | Error | WebClient(HttpWebClient).GetString(Url:http://omdbapi.com/?apikey="myapikey"&i=tt6433880): No encoding detected, defaulting to UTF-8

**Jackett version**:  0.8.656.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
Thank you for reporting it.

Fixed via 7db24cc4a0b0ea0b60238c39757640d0c8b45a9e

It's no serious issue.
