### ISSUE TITLE
Jacket/Sonarr/'Anime Tosho' not working by default.

### ISSUE THREAD

**Issue by orionshock** [Jackett/Jackett#2533]
When adding "Anime Tosho" from Jackett to Sonarr, it immediately failed. Other indexers worked just fine with out making any ajdustments. Pasted in the URL & API Key, gave it a Name -- worked just fine.

Logs were not very useful, something along the lines of 
`[v2.0.0.5085] System.InvalidOperationException: Sequence contains no elements`

So i hacked/conjured up a URL for Jackett's Anime Tosho Feed & plugged it into a browser; got this in response:

`<Error>
<script/>
<Message>animetosho does not support the requested query.</Message>
</Error>`

Examining the URL itself i found "t=tvsearch&cat=5030,5040". As this is an anime source, i went back to Sonarr seeing there is an Anime Categories field. 
However as the TV field has numbers in it, referencing [the specs for torznab](https://github.com/nZEDb/nZEDb/blob/dev/docs/newznab_api_specification.txt) the code for TV/Anime  is 5070. 

After putting that into the Anime Field & deleting everything in TV field,  it all worked..

Just want to point out, these adjustments are not obvious to the newb and should probably be documented somewhere.

**Comment by kaso17** [comment]
Improved the error message via ad4aa891cfe1f57e2a923727b3f19f0e37deec71 and updated the instructions via 9215ae44ba6cc52080bc21142ca56de8319c2e81
