### ISSUE TITLE
How do I change the URL in the Indexer?

### ISSUE THREAD

**Issue by viking2** [Jackett/Jackett#254]
I am using an old version of Jacket (v0.6.3.0) which still supported Rutor. 

Now, Rutor has changed the URL from rutor.org to new-rutor.org.

However, when I change it and click on OK, I get an error:
_" Configuration failed: An error occurred while sending the request."_

**Log File Shows:**
Feb 22, 2016 07:49:29 PM 	Error 	

Exception in Configure

Feb 22, 2016 07:49:28 PM 	Error 	

On attempt 3 checking for results from RUTor: An error occurred while sending the request.

Feb 22, 2016 07:49:25 PM 	Error 	

On attempt 2 checking for results from RUTor: An error occurred while sending the request.

Feb 22, 2016 07:49:23 PM 	Error 	

On attempt 1 checking for results from RUTor: An error occurred while sending the request.

**Comment by Azerelat** [comment]
Grab a copy of the source code of that release
Extract
Open sln using visual studio 2015 community
Do a serarch for rutor and change the url
Compile
Replace the existing program files with those from the output folder.

**Comment by viking2** [comment]
So it is not possible to simply change the URL in Web interface?

I have never used any programming software. Would the free version (Visual Studio Community: https://www.visualstudio.com/products/free-developer-offers-vs) work?

**Comment by Azerelat** [comment]
Yes

**Comment by viking2** [comment]
Why is it not possible to simply change the URL in the Web interface?
This worked for another indexer [when I needed to change the URL].
