### ISSUE TITLE
Launch a search by URL without redirection

### ISSUE THREAD

**Issue by hartar9** [Jackett/Jackett#2540]
Hi ! 

Like the #1345 , I would like to search via an url, directly retrieving the result (in JSon as currently), without going through the web page.   (http://url/Admin/Dashboard/Manual?query=MY_MOVIE )

Is it possible to directly return the result of the search?

Thank you.

**Comment by kaso17** [comment]
Just use the Torznab API in this case:
E.g.:
http://127.0.0.1:9117/jackett/api/v2.0/indexers/1337x/results/torznab/api?apikey=XXX&t=search&cat=&q=MY_MOVIE

While JSON is general supported by toznab it's not implemented by jackett.
If you need JSON instead of XML then that needs to be implemented.

**Comment by hartar9** [comment]
I just check your URL and it's exactly what i need ! Xml or Json is the same :) 

Thank you very much !
