### ISSUE TITLE
[Downloadville] Error 404 download link

### ISSUE THREAD

**Issue by doreybenjamin** [Jackett/Jackett#2543]
Hi,

When you want click to download with this tracker i have a error HTTP ERROR 404 any help ?
Jackett 0.8.663.0 

Regards,

**Comment by kaso17** [comment]
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by doreybenjamin** [comment]
Error downloading downloadville https://downloadville.net/tracker/index.php?page=torrent-details&id=0a1417266bae3f18d0ceabb90269b85344eab970

Failed download response:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /download.php was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

Failed download cookies: uid=4380; pass=6ba384d2b7e6cb670c611d7dfecc9baa; xbtitLoginCookie=deleted; xbtit=3n3cunuhdsofpkc65u3oao9g40

**Comment by kaso17** [comment]
@garfield69 can you have a look? I've no access.

**Comment by garfield69** [comment]
@kaso17  i have sent you an invite which I am told is valid for 48 from the date of this post.

**Comment by kaso17** [comment]
fixed via 1c031722110416cb217079e06b54f766cdf7fd27
