### ISSUE TITLE
[limetorrents] Exception (limetorrents): Nenhuma ligação pôde ser feita porque o computador de destinoas recusou ativamente 213.13.145.120:443: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by viktorfreire** [Jackett/Jackett#2545]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
your ISP is blocking your access:
`O site a que se pretende aceder encontra-se bloqueado na sequência do cumprimento de ordem judicial`

Look for a proxy that works for your region https://torrents.me/proxy/limetorrents/ which you can use on your Jackett Dashboard by clicking the wrench icon to edit your limetorrents indexer config and changing the SiteLink.
or try switching to an alternate dns like google's `8.8.8.8` or `8.8.4.4`
Or look into using a VPN.
