### ISSUE TITLE
Failed to Launch Jackett - Rockstor

### ISSUE THREAD

**Issue by Mahmoud87** [Jackett/Jackett#2547]
Hey Guys

Jackett has been working fine for months till few days ago I have noticed that it doesn't even start. I haven't done any changes to my environment, I am running Rockstor CentOS 7.

Jackett Ver.: Can't tell since I am not able to launch the WebUI
Mono Ver:  5.4.1.6

This was the last log I have seen on system, it was on the 25.01.2018.
[log.20180125.00027.txt](https://github.com/Jackett/Jackett/files/1697092/log.20180125.00027.txt)

This is my Systemd conifg.

[Unit]
Description=Jackett Daemon
After=network.target

[Service]
WorkingDirectory=/mnt2/Jackett/Jackett
User=root
Restart=always
RemainAfterExit=no
RestartSec=5
Type=simple
ExecStart=/usr/bin/mono --debug /mnt2/Jackett/Jackett/JackettConsole.exe
TimeoutStopSec=5

[Install]
WantedBy=multi-user.target

Will appreciate your help, cheers.

**Comment by kaso17** [comment]
Check the journalctl output for the error.
There might be another (broken) instance of jackett blocking the port.
Your systemd config is definitly missing the `--NoRestart` flag.
See https://github.com/Jackett/Jackett/wiki/systemd-service for details

**Comment by jafo5236** [comment]
Can you check the status of you jackett service?  I'm having the same issue and my service says that it is activating.

Redirecting to /bin/systemctl status jackett.service
● jackett.service - Jackett Daemon
   Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) since Tue 2018-02-06 14:02:52 CST; 5s ago
  Process: 1648 ExecStart=/usr/bin/mono --debug JackettConsole.exe --NoRestart (code=exited, status=0/SUCCESS)
 Main PID: 1648 (code=exited, status=0/SUCCESS)

**Comment by Mahmoud87** [comment]
Hey @kaso17 I have checked the journalctl didn't notice any broken instances. I have also added the --NoRestart and didn't do much.

@jafo5236 If you restart jackett then ran the status command it will show active then if you run this last command one more time it will show the error below.


[root@rockstor_nas ~]# systemctl status jackett
● jackett.service - Jackett Daemon
   Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-02-07 12:42:28 ACDT; 40ms ago
 Main PID: 25434 (mono)
   CGroup: /system.slice/jackett.service
           └─25434 /usr/bin/mono --debug /mnt2/Jackett/Jackett/JackettConsole.exe --NoRestart

Feb 07 12:42:28 rockstor_nas systemd[1]: Started Jackett Daemon.
Feb 07 12:42:28 rockstor_nas systemd[1]: Starting Jackett Daemon...


[root@rockstor_nas ~]# systemctl status jackett
● jackett.service - Jackett Daemon
   Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-02-07 12:43:25 ACDT; 2s ago
  Process: 25602 ExecStart=/usr/bin/mono --debug /mnt2/Jackett/Jackett/JackettConsole.exe --NoRestart (code=exited, st            atus=1/FAILURE)
 Main PID: 25602 (code=exited, status=1/FAILURE)

Feb 07 12:43:25 rockstor_nas mono[25602]: [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: ...cies.
Feb 07 12:43:25 rockstor_nas mono[25602]: File name: 'CommandLine, Version=1.9.71.2, Culture=neutral, PublicKe...8c32'
Feb 07 12:43:25 rockstor_nas systemd[1]: Unit jackett.service entered failed state.
Feb 07 12:43:25 rockstor_nas systemd[1]: jackett.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[root@rockstor_nas ~]#

**Comment by kaso17** [comment]
From the very partial log it looks like you updated jackett from a very old version. Most likely the updater wasn't able to create new files in the jackett directory (permission issue). To fix it you've manually extract/reinstall the latest jackett version (just replace all files).

it that doesn't fix it please post the journal output

**Comment by Mahmoud87** [comment]
@kaso17  thanks mate, I have downloaded the latest Jackett and tried to replace the files first and this didn't work. I had to create a new directory and give ownership also edited my jackett.service and it's working perfectly fine. Thanks for your help much appreciated.
