### ISSUE TITLE
BeyondHD Indexer Not Reporting All Capabilities

### ISSUE THREAD

**Issue by georgeurbane** [Jackett/Jackett#255]
The BeyondHD Indexer doesn't seem to correctly report all of it's capabilities.

I would expect to see TV sections reported too, no?
![screenshot 2016-02-23 13 12 04](https://cloud.githubusercontent.com/assets/17436505/13261642/1d536386-da2f-11e5-916c-57ce7c8feb86.png)

From the source, it looks like it it's not pulling in any of the AddMultiCategoryMapping bits.  Forgive me if I'm missing something obvious.

**Comment by Azerelat** [comment]
Incoming toznab query categories are mapped to the tracker categories (That is what was used above) then there is a separate function to map the results back to torznab categories.

I've removed the ability to add mappings to one and not the other which was happening and as its not possible to output that group it wasn't shown on the ui.
