### ISSUE TITLE
Error checking for updates AND Exception in Configure

### ISSUE THREAD

**Issue by Msurrow** [Jackett/Jackett#2552]
Jackett stopped working on Synology NAS, complaining something about SSL certs and Mono not valid. The suggested command to run did not work, so I uninstalled Jackett using the DSM packet manager, and reinstalled. Jackett no longer complains about Mono SSL certs, but now I cannot update (log says: "Error checking for updates") and I cannot add my tracker DanishBits (yes I'm using passkey instead of pasword) (log says: " Exception in Configure"). 

Here are enhanced logs for both errors:

Feb 06, 2018 08:40:56 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
-- | -- | --
Feb 06, 2018 08:40:56 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Feb 06, 2018 08:40:56 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Feb 06, 2018 08:40:56 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Feb 06, 2018 08:40:56 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 06, 2018 08:40:56 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 06, 2018 08:40:56 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 06, 2018 08:40:56 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 06, 2018 08:40:56 PM | Info | ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Feb 06, 2018 08:40:56 PM | Info | ApiControllerActionSelector SelectAction
Feb 06, 2018 08:40:56 PM | Info | AdminController ExecuteAsync
Feb 06, 2018 08:40:56 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Feb 06, 2018 08:40:56 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Feb 06, 2018 08:40:56 PM | Info | DefaultHttpControllerActivator Create
Feb 06, 2018 08:40:56 PM | Info | HttpControllerDescriptor CreateController
Feb 06, 2018 08:40:56 PM | Info | DefaultHttpControllerSelector SelectController Admin
Feb 06, 2018 08:40:56 PM | Info | DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Feb 06, 2018 08:40:56 PM | Info | http://192.168.2.10:9117/Admin/GetLogs?_=1517945977608
Feb 06, 2018 08:40:53 PM | Error | Error checking for updates.
Feb 06, 2018 08:40:53 PM | Info | AdminController Dispose
Feb 06, 2018 08:40:53 PM | Info | AdminController Dispose
Feb 06, 2018 08:40:53 PM | Info | Content-type='application/json; charset=utf-8', content-length=2
Feb 06, 2018 08:40:53 PM | Info | AdminController ExecuteAsync
Feb 06, 2018 08:40:53 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Feb 06, 2018 08:40:53 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'TriggerUpdates()'
Feb 06, 2018 08:40:53 PM | Info | ApiControllerActionInvoker InvokeActionAsync
Feb 06, 2018 08:40:53 PM | Debug | IWebClient.GetString(Url:https://api.github.com/repos/Jackett/Jackett/releases)
Feb 06, 2018 08:40:53 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
Feb 06, 2018 08:40:53 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'TriggerUpdates()'
Feb 06, 2018 08:40:53 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='TriggerUpdates()'
Feb 06, 2018 08:40:53 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Feb 06, 2018 08:40:53 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'TriggerUpdates()'
Feb 06, 2018 08:40:53 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 06, 2018 08:40:53 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 06, 2018 08:40:53 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 06, 2018 08:40:53 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 06, 2018 08:40:53 PM | Info | ApiControllerActionSelector SelectAction Selected action 'TriggerUpdates()'
Feb 06, 2018 08:40:53 PM | Info | ApiControllerActionSelector SelectAction
Feb 06, 2018 08:40:53 PM | Info | AdminController ExecuteAsync
Feb 06, 2018 08:40:53 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Feb 06, 2018 08:40:53 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Feb 06, 2018 08:40:53 PM | Info | DefaultHttpControllerActivator Create
Feb 06, 2018 08:40:53 PM | Info | HttpControllerDescriptor CreateController
Feb 06, 2018 08:40:53 PM | Info | DefaultHttpControllerSelector SelectController Admin
Feb 06, 2018 08:40:53 PM | Info | DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Feb 06, 2018 08:40:53 PM | Info | http://192.168.2.10:9117/Admin/trigger_update?_=1517945977607
Feb 06, 2018 08:40:00 PM | Info | AdminController Dispose
Feb 06, 2018 08:40:00 PM | Info | AdminController Dispose
Feb 06, 2018 08:40:00 PM | Info | JsonMediaTypeFormatter WriteToStreamAsync
Feb 06, 2018 08:40:00 PM | Info | JsonMediaTypeFormatter WriteToStreamAsync Value='System.Collections.Generic.List`1[Jackett.Models.CachedLog]', type='List`1', content-type='application/json; charset=utf-8'

Feb 06, 2018 08:43:00 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
-- | -- | --
Feb 06, 2018 08:43:00 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Feb 06, 2018 08:43:00 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Feb 06, 2018 08:43:00 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Feb 06, 2018 08:43:00 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 06, 2018 08:43:00 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 06, 2018 08:43:00 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 06, 2018 08:43:00 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 06, 2018 08:43:00 PM | Info | ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Feb 06, 2018 08:43:00 PM | Info | ApiControllerActionSelector SelectAction
Feb 06, 2018 08:43:00 PM | Info | AdminController ExecuteAsync
Feb 06, 2018 08:43:00 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Feb 06, 2018 08:43:00 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Feb 06, 2018 08:43:00 PM | Info | DefaultHttpControllerActivator Create
Feb 06, 2018 08:43:00 PM | Info | HttpControllerDescriptor CreateController
Feb 06, 2018 08:43:00 PM | Info | DefaultHttpControllerSelector SelectController Admin
Feb 06, 2018 08:43:00 PM | Info | DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Feb 06, 2018 08:43:00 PM | Info | http://192.168.2.10:9117/Admin/GetLogs?_=1517945977609
Feb 06, 2018 08:42:55 PM | Info | AdminController Dispose
Feb 06, 2018 08:42:55 PM | Info | AdminController Dispose
Feb 06, 2018 08:42:55 PM | Info | Content-type='application/json; charset=utf-8', content-length=92
Feb 06, 2018 08:42:55 PM | Info | AdminController ExecuteAsync
Feb 06, 2018 08:42:55 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Feb 06, 2018 08:42:55 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()'
Feb 06, 2018 08:42:55 PM | Info | ApiControllerActionInvoker InvokeActionAsync
Feb 06, 2018 08:42:55 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
Feb 06, 2018 08:42:55 PM | Error | Exception in Configure
Feb 06, 2018 08:42:55 PM | Debug | IWebClient.GetString(Url:https://danishbits.org/login.php)
Feb 06, 2018 08:42:55 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Configure()'
Feb 06, 2018 08:42:55 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Configure()'
Feb 06, 2018 08:42:55 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Feb 06, 2018 08:42:55 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Configure()'
Feb 06, 2018 08:42:55 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 06, 2018 08:42:55 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 06, 2018 08:42:55 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 06, 2018 08:42:55 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 06, 2018 08:42:55 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Configure()'
Feb 06, 2018 08:42:55 PM | Info | ApiControllerActionSelector SelectAction
Feb 06, 2018 08:42:55 PM | Info | AdminController ExecuteAsync
Feb 06, 2018 08:42:55 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Feb 06, 2018 08:42:55 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Feb 06, 2018 08:42:55 PM | Info | DefaultHttpControllerActivator Create
Feb 06, 2018 08:42:55 PM | Info | HttpControllerDescriptor CreateController
Feb 06, 2018 08:42:55 PM | Info | DefaultHttpControllerSelector SelectController Admin
Feb 06, 2018 08:42:55 PM | Info | DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Feb 06, 2018 08:42:55 PM | Info | http://192.168.2.10:9117/Admin/configure_indexer
Feb 06, 2018 08:42:52 PM | Info | AdminController Dispose
Feb 06, 2018 08:42:52 PM | Info | AdminController Dispose
Feb 06, 2018 08:42:52 PM | Info | Content-type='application/json; charset=utf-8', content-length=969
Feb 06, 2018 08:42:52 PM | Info | AdminController ExecuteAsync

**Comment by becian** [comment]
I started having the same problem too on my Synology system. Un-installed, installed and my tracker (iptorrent) and updates stopped working. I installed on windows, iptorrent tracker works but when ii add it to radar/sonar on my nas I get errors. I'll update my post when I get home from work with log info

**Comment by SliceOfSublime** [comment]
Same problem.

**Comment by becian** [comment]
`<table class="dataTable compact cell-border hover stripe">
                            <thead>
                                <tr>
                                    <th style="width: 200px">When</th>
                                    <th style="width: 80px">Level</th>
                                    <th>Message</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>JackettAPINoCacheAttribute OnActionExecutingAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>HttpActionBinding ExecuteBindingAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>HttpActionBinding ExecuteBindingAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>JackettAuthorizedAttribute OnAuthorizationAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>JackettAuthorizedAttribute OnAuthorizationAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>ApiControllerActionSelector SelectAction Selected action 'GetLogs()'</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>ApiControllerActionSelector SelectAction </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>AdminController ExecuteAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>HttpControllerDescriptor CreateController Jackett.Controllers.AdminController</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>DefaultHttpControllerActivator Create Jackett.Controllers.AdminController</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>DefaultHttpControllerActivator Create </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>HttpControllerDescriptor CreateController </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>DefaultHttpControllerSelector SelectController Admin</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:05 PM</td>
                                    <td>Info</td>
                                    <td><pre>  http://192.168.86.34:9117/Admin/GetLogs?_=1517993994484</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:02 PM</td>
                                    <td>Info</td>
                                    <td><pre>AdminController Dispose </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:02 PM</td>
                                    <td>Info</td>
                                    <td><pre>AdminController Dispose </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:02 PM</td>
                                    <td>Info</td>
                                    <td><pre>  Content-type='application/json; charset=utf-8', content-length=72</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:02 PM</td>
                                    <td>Info</td>
                                    <td><pre>AdminController ExecuteAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:02 PM</td>
                                    <td>Info</td>
                                    <td><pre>JackettAPINoCacheAttribute OnActionExecutedAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:02 PM</td>
                                    <td>Info</td>
                                    <td><pre>JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'GetConfigForm()'</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:02 PM</td>
                                    <td>Info</td>
                                    <td><pre>ApiControllerActionInvoker InvokeActionAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:02 PM</td>
                                    <td>Info</td>
                                    <td><pre>ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'</pre></td>
                                </tr>
                                <tr class="jackettlogError">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Error</td>
                                    <td><pre>Exception in GetConfigForm</pre></td>
                                </tr>
                                <tr class="jackettlogDebug">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Debug</td>
                                    <td><pre>IWebClient.GetString(Url:https://iptorrents.com/login.php)</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetConfigForm()'</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>ApiControllerActionInvoker InvokeActionAsync Action='GetConfigForm()'</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>JackettAPINoCacheAttribute OnActionExecutingAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetConfigForm()'</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>HttpActionBinding ExecuteBindingAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>HttpActionBinding ExecuteBindingAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>JackettAuthorizedAttribute OnAuthorizationAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>JackettAuthorizedAttribute OnAuthorizationAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>ApiControllerActionSelector SelectAction Selected action 'GetConfigForm()'</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>ApiControllerActionSelector SelectAction </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>AdminController ExecuteAsync </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>HttpControllerDescriptor CreateController Jackett.Controllers.AdminController</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>DefaultHttpControllerActivator Create Jackett.Controllers.AdminController</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>DefaultHttpControllerActivator Create </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>HttpControllerDescriptor CreateController </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>DefaultHttpControllerSelector SelectController Admin</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 07:00:01 PM</td>
                                    <td>Info</td>
                                    <td><pre>  http://192.168.86.34:9117/Admin/get_config_form</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 06:59:53 PM</td>
                                    <td>Info</td>
                                    <td><pre>AdminController Dispose </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 06:59:53 PM</td>
                                    <td>Info</td>
                                    <td><pre>AdminController Dispose </pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 06:59:53 PM</td>
                                    <td>Info</td>
                                    <td><pre>  Content-type='application/json; charset=utf-8', content-length=316531</pre></td>
                                </tr>
                                <tr class="jackettlogInfo">
                                    <td>Feb 07, 2018 06:59:53 PM</td>
                                    <td>Info</td>
                                    <td><pre>AdminController ExecuteAsync </pre></td>
                                </tr>
                            </tbody>
                        </table>`

**Comment by becian** [comment]
This is the problem im having with mine

When | Level | Message
-- | -- | --
Feb 07, 2018 07:00:05 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
Feb 07, 2018 07:00:05 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Feb 07, 2018 07:00:05 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Feb 07, 2018 07:00:05 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Feb 07, 2018 07:00:05 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 07, 2018 07:00:05 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 07, 2018 07:00:05 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 07, 2018 07:00:05 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 07, 2018 07:00:05 PM | Info | ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Feb 07, 2018 07:00:05 PM | Info | ApiControllerActionSelector SelectAction
Feb 07, 2018 07:00:05 PM | Info | AdminController ExecuteAsync
Feb 07, 2018 07:00:05 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Feb 07, 2018 07:00:05 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Feb 07, 2018 07:00:05 PM | Info | DefaultHttpControllerActivator Create
Feb 07, 2018 07:00:05 PM | Info | HttpControllerDescriptor CreateController
Feb 07, 2018 07:00:05 PM | Info | DefaultHttpControllerSelector SelectController Admin
Feb 07, 2018 07:00:05 PM | Info | DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Feb 07, 2018 07:00:05 PM | Info | http://192.168.86.34:9117/Admin/GetLogs?_=1517993994484
Feb 07, 2018 07:00:02 PM | Info | AdminController Dispose
Feb 07, 2018 07:00:02 PM | Info | AdminController Dispose
Feb 07, 2018 07:00:02 PM | Info | Content-type='application/json; charset=utf-8', content-length=72
Feb 07, 2018 07:00:02 PM | Info | AdminController ExecuteAsync
Feb 07, 2018 07:00:02 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Feb 07, 2018 07:00:02 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'GetConfigForm()'
Feb 07, 2018 07:00:02 PM | Info | ApiControllerActionInvoker InvokeActionAsync
Feb 07, 2018 07:00:02 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
Feb 07, 2018 07:00:01 PM | Error | Exception in GetConfigForm
Feb 07, 2018 07:00:01 PM | Debug | IWebClient.GetString(Url:https://iptorrents.com/login.php)
Feb 07, 2018 07:00:01 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetConfigForm()'
Feb 07, 2018 07:00:01 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='GetConfigForm()'
Feb 07, 2018 07:00:01 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Feb 07, 2018 07:00:01 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetConfigForm()'
Feb 07, 2018 07:00:01 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 07, 2018 07:00:01 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 07, 2018 07:00:01 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 07, 2018 07:00:01 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 07, 2018 07:00:01 PM | Info | ApiControllerActionSelector SelectAction Selected action 'GetConfigForm()'
Feb 07, 2018 07:00:01 PM | Info | ApiControllerActionSelector SelectAction
Feb 07, 2018 07:00:01 PM | Info | AdminController ExecuteAsync
Feb 07, 2018 07:00:01 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Feb 07, 2018 07:00:01 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Feb 07, 2018 07:00:01 PM | Info | DefaultHttpControllerActivator Create
Feb 07, 2018 07:00:01 PM | Info | HttpControllerDescriptor CreateController
Feb 07, 2018 07:00:01 PM | Info | DefaultHttpControllerSelector SelectController Admin
Feb 07, 2018 07:00:01 PM | Info | DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Feb 07, 2018 07:00:01 PM | Info | http://192.168.86.34:9117/Admin/get_config_form
Feb 07, 2018 06:59:53 PM | Info | AdminController Dispose
Feb 07, 2018 06:59:53 PM | Info | AdminController Dispose
Feb 07, 2018 06:59:53 PM | Info | Content-type='application/json; charset=utf-8', content-length=316531
Feb 07, 2018 06:59:53 PM | Info | AdminController ExecuteAsync

**Comment by kaso17** [comment]
Please try the latest mono and jackett builds from https://github.com/m4tt075/spksrc/releases/tag/Mono-5.8.0-fixed and https://github.com/m4tt075/spksrc/releases/tag/Jackett-0.8.490

**Comment by Msurrow** [comment]
Thank you, that worked for me. 

For anyone else with the same problem: I was a bit confused by the many builds on the above links. Turns out that the Synology have a lot of different cpu architectures across their models. You can see with one you have here: 
https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model

**Comment by becian** [comment]
@kaso17  Thanks for that. Fixed mine too. Had to re-install sonarr/radarr but backed it up so shouldn't be a problem.
@Msurrow You saved me the trouble of checking it out myself haha thank you!
