### ISSUE TITLE
Cannot Start WebServer

### ISSUE THREAD

**Issue by Artanisx** [Jackett/Jackett#2557]
**Jackett version**:  v0.8.670
**O.S.** Windows 10  v.1709
-------------------------------
It seems I can't launch the web server at all. If I try to open the web server via http://127.0.0.1:9117/ I get the ERR_CONNECTION_REFUSED error. I've already tried adding port 9117 to the Windows Firewall, adding Jackett service and Jackett application. I've also tried disabling Windows Firewall, no dice.

I've tried launching Jackettconsole to see if I could find some info and I got the below:

> 02-07 18:35:11 Info Starting web server at http://127.0.0.1:9117/
> 02-07 18:35:11 Error Top level exception System.Reflection.TargetInvocationException: Eccezione generata dalla destinazione di una chiamata. ---> System.Net.HttpListenerException: Impossibile raggiungere la destinazione del percorso di rete. Per informazioni sulla risoluzione dei problemi di rete, consultare la Guida di Windows
>    in System.Net.HttpListener.AddAllPrefixes()
>    in System.Net.HttpListener.Start()
>    in Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
>    in Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
>    --- Fine della traccia dello stack dell'eccezione interna ---
>    in Jackett.Services.ServerService.Start() in C:\projects\jackett\src\Jackett\Services\ServerService.cs:riga 306
>    in JackettConsole.Program.<>c.<Main>b__0_1(ConsoleOptions options) in C:\projects\jackett\src\Jackett.Console\Program.cs:riga 188

Sadly it's in Italian, so below find a quick translation:
> 02-07 18:35:11 Info Starting web server at http://127.0.0.1:9117/
> 02-07 18:35:11 Error Top level exception System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Failed to reach net path. For more info on net issues check Windows Help
>    in System.Net.HttpListener.AddAllPrefixes()
>    in System.Net.HttpListener.Start()
>    in Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
>    in Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
>    --- Stop stack traces on internal exception ---
>    in Jackett.Services.ServerService.Start() in C:\projects\jackett\src\Jackett\Services\ServerService.cs:riga 306
>    in JackettConsole.Program.<>c.<Main>b__0_1(ConsoleOptions options) in C:\projects\jackett\src\Jackett.Console\Program.cs:riga 188

Now, I've also tried disabling the antivirus and the firewall. Any tips? Thanks!

**Comment by garfield69** [comment]
My guess is that one of your indexers SiteLinks is now causing Jackett to crash.      
As a test, try this: rename `%ProgramData%\Jackett\Indexers` to `%ProgramData%\Jackett\IndexersORG` then start the JackettConsole program.      
If you can access the webgui now, then you'll find none of pre-configured indexers are listed. 
So shut down JackettConsole. 
Take a look inside IndexersORG, you will finds all the indexers you have configured as `*.json` files. 
Copy over the first one to your Indexers folder and start the JackettConsole.
Rinse and repeat until you get the crash. Let us know which indexer causes Jackett to fail.

**Comment by Artanisx** [comment]
Hi garfield69!
First of all, thank you for your answer!

I've tried your test and renamed Indexers to InderxersORG. Then launched again JackettConsole.exe. Sadly I got the very same error. Also tried launching the webserver again, but got again "ERR_CONNECTION_REFUSED". The odd thing is... Jackett worked correctly a few days ago. Today I tried to load the Web Gui and it didn't work. So I went ahead and updated it to the latest version, but it didn't fix the issue I'm having. I'm not sure what's wrong here.

Yes, I changed Antivirus (had Bitdefender, installed Avast) but as I tried this with Avast disabled, it shouldn't be it (I also included the Jackett folder in the exclusion lists just to be safe).... :(

**Comment by garfield69** [comment]
Darn.
OK, so restore your indexersORG back, sorry for wasting you time on that red herring.
It may be useful to see the full log, in enhanced mode, so could you start the JackettConsole with the `-t -l` parms and access the web gui. 
Once it crashes, find the log.txt in the `%ProgramData%\Jackett` folder and drop it here for us to take a look.
Thanks.

**Comment by Artanisx** [comment]
Not at all, thank you for helping me :)
So, I've launched "JacketConsole.exe -t -l" here's the log.txt.
[log.txt](https://github.com/Jackett/Jackett/files/1704484/log.txt)

I'm sorry there's a few Italian mixed in the error messages, let me know if I need to translate some of it :)

**Comment by kaso17** [comment]
Please try running `JacketConsole.exe --ReserveUrls`
Did you install it via the installer or manually by extracting the zip?

**Comment by Artanisx** [comment]
Hi kaso17!
I just tried launching it with the command you mentioned, but nothing seems to have happened:

> C:\ProgramData\Jackett>jackettconsole.exe --ReserveUrls
02-07 20:44:11 Info App config/log directory: C:\ProgramData\Jackett
C:\ProgramData\Jackett>

I've tried launching the web gui, but no luck.

I've used the installer and installed as a service.

**Comment by kaso17** [comment]
ok, then please run
`netsh.exe http add urlacl http://*:9117/ sddl=D:(A;;GX;;;S-1-1-0)`

**Comment by Artanisx** [comment]
OK done:

> C:\ProgramData\Jackett>netsh.exe http add urlacl http://*:9117/ sddl=D:(A;;GX;;;S-1-1-0)
Aggiunta della prenotazione URL completata

Which means "Added URL reservation completed".

Tied to run again Jackettconsole.exe, but got the same message sadly:

> 02-07 21:13:56 Info Starting web server at http://127.0.0.1:9117/
02-07 21:13:57 Error Top level exception System.Reflection.TargetInvocationException: Eccezione generata dalla destinazione di una chiamata. ---> System.Net.HttpListenerException: Impossibile raggiungere la destinazione del percorso di rete. Per informazioni sulla risoluzione dei problemi di rete, consultare la Guida di Windows
   in System.Net.HttpListener.AddAllPrefixes()
   in System.Net.HttpListener.Start()
   in Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   in Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- Fine della traccia dello stack dell'eccezione interna ---
   in Jackett.Services.ServerService.Start() in C:\projects\jackett\src\Jackett\Services\ServerService.cs:riga 306
   in JackettConsole.Program.<>c.<Main>b__0_1(ConsoleOptions options) in C:\projects\jackett\src\Jackett.Console\Program.cs:riga 188

**Comment by kaso17** [comment]
ok, then I'm out of ideas.
Try changing the language to english to get a useful error message :)
But most likely something is preventing jackett from using the port.

**Comment by Artanisx** [comment]
Well, the error message says something about it being impossible to reach the net destination path (Error Top level exception System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Failed to reach net path. For more info on net issues check Windows Help). I do think too there's something up on the port. It's almost like Windows Firewall is blocking that port (but it isn't, since I've disabled it and I have no other firewalls installed). The thing I don't understand is why it worked before and now it suddendly stopped. It might be something about the PC being on for too long (I think the uptime is a few days now)?
Anyway, thank you for trying! :)

**Comment by garfield69** [comment]
maybe something has inserted an entry in the hosts file for 127.0.0.1
with a plain text editor (notepad, textpad,etc) open `C:\Windows\System32\drivers\etc\hosts`
anything in there for 127.0.0.1 that does not have a `#` in front of it?

**Comment by Artanisx** [comment]
It looks fine, all two entries are with a # before them:

\#    127.0.0.1 localhost
\#   ::1             localhost


By the way, I can open Sonarr which is on http://localhost:8989/ 

Infact, this prompted me to try out Jackett on http://localhost:9117/ instead of http://127.0.0.1:9117/ but I still get an error albeit different: HTTP Error 503. The service is unavailable.


I really don't understand... it was working fine a few days ago! :(

**Comment by garfield69** [comment]
and you have checked the services, and the Jackett service is running?
have you checked the avast viruschest, has it flagged any of the jackett components as malicious and moved them there?

**Comment by Artanisx** [comment]
Checked the service, it wasn't running. I tried to manually run it, but it said it started and stopped immediately after. I also checked Avast quarantine/virus bin and it's empty, likewise for Malwarebytes. Nothing there, checked also the logs those two program did not fire (I've disabled them just in case).

I've tried reinstalling it (chosed an old version as an extra test) and during installation, for a split second (i had to capture the screen) the below screens appears:
http://puu.sh/ziUNC/f51686ce2a.jpg

The italian strings are:
Source of EventLog Jackett removal.
Warning: Jackett source/origin is not registered on the local computer.
Jackett service is being removed from the system now...


This window appears for a brief moment during installation, other similar windows appears very quickly and the the setup completes normally.

I'm going to reinstall the latest version and record the installation because I THINK the yellow text I saw for a split second was much longer than the one it happers on this old version.

**Comment by garfield69** [comment]
Access the services manager and select properties for the Jackett service. Click on the *Log On* tab, and make sure that the *Allow Service to interact with Desktop* check box is not ticked.
then use the *Apply* and *OK* buttons and start the service and see if it works now.

**Comment by flightlevel** [comment]
Be worth trying another port (edit port in C:\ProgramData\Jackett\ServerConfig.json) and also try running it as admin to see if that makes a difference

**Comment by Artanisx** [comment]
@garfield69: Tried that too, sadly it made no difference and the service still stops right after I try to start it. :(

flightlevel: Tried that as well. Changed to port 9118 and launched as administrator. If i try Jackettconsole, it produces the yellow error mentioned, if I launch Jacketttray, it crashes at startup. :'(
