### ISSUE TITLE
Not able to find music [TorrentDay]

### ISSUE THREAD

**Issue by eriuhdkjnwwk** [Jackett/Jackett#2558]
When I search for an artist via Jackett on TorrentDay, if anything, it returns music videos or very large compilations, but no actual albums. I am trying to get this working with headphones,  but so far it appears to be a Jackett/Tracker configuration issue.

If I manually perform the same search in the tracker's site, I get several results for the search. 

I'm wondering if it's related to the WebClient(HttpWebClient).GetString log entry where it appears to not include category '27'

https://torrentday.it/t.json?29;28;42;20;30;47;43;25;11;5;3;21;22;13;44;48;1;23;41;16;45;4;18;8;10;9;24;32;31;33;46;14;26;7;34;2;6;15;q=Justin+Timberlake+Man+of+the+Woods

If I add '27;' to the string and paste it into my browser, I get the results I'm expecting:
https://torrentday.it/t.json?29;28;42;20;30;47;43;25;11;5;3;21;22;13;44;48;1;23;41;16;45;4;18;8;10;9;24;32;31;33;46;14;26;7;34;2;6;15;27;q=Justin+Timberlake+Man+of+the+Woods

Jackett Version 0.8.670.0
Windows

Thanks for your time!

-------------------------------
Logs
-------------------------------

Feb 07, 2018 02:54:05 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
-- | -- | --
Feb 07, 2018 02:54:05 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
Feb 07, 2018 02:54:05 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Feb 07, 2018 02:54:05 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
Feb 07, 2018 02:54:05 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 07, 2018 02:54:05 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 07, 2018 02:54:05 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 07, 2018 02:54:05 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 07, 2018 02:54:05 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
Feb 07, 2018 02:54:05 PM | Info | ApiControllerActionSelector SelectAction
Feb 07, 2018 02:54:05 PM | Info | ServerConfigurationController ExecuteAsync
Feb 07, 2018 02:54:05 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ServerConfigurationController
Feb 07, 2018 02:54:05 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ServerConfigurationController
Feb 07, 2018 02:54:05 PM | Info | DefaultHttpControllerActivator Create
Feb 07, 2018 02:54:05 PM | Info | HttpControllerDescriptor CreateController
Feb 07, 2018 02:54:05 PM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
Feb 07, 2018 02:54:05 PM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
Feb 07, 2018 02:54:05 PM | Info | http://htpc:9117/api/v2.0/server/logs?_=1518038286623
Feb 07, 2018 02:53:48 PM | Info | ResultsController Dispose
Feb 07, 2018 02:53:48 PM | Info | ResultsController Dispose
Feb 07, 2018 02:53:48 PM | Info | JsonMediaTypeFormatter WriteToStreamAsync
Feb 07, 2018 02:53:48 PM | Info | JsonMediaTypeFormatter WriteToStreamAsync Value='Jackett.Models.DTO.ManualSearchResult', type='ManualSearchResult', content-type='application/json; charset=utf-8'
Feb 07, 2018 02:53:48 PM | Info | Content-type='application/json; charset=utf-8', content-length=unknown
Feb 07, 2018 02:53:48 PM | Info | ResultsController ExecuteAsync
Feb 07, 2018 02:53:48 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Feb 07, 2018 02:53:48 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Results(ApiSearch request)'
Feb 07, 2018 02:53:48 PM | Info | RequiresValidQueryAttribute OnActionExecutedAsync
Feb 07, 2018 02:53:48 PM | Info | RequiresValidQueryAttribute OnActionExecutedAsync Action filter for 'Results(ApiSearch request)'
Feb 07, 2018 02:53:48 PM | Info | ApiControllerActionInvoker InvokeActionAsync
Feb 07, 2018 02:53:48 PM | Info | DefaultContentNegotiator Negotiate Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8'
Feb 07, 2018 02:53:48 PM | Info | JsonMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'JsonMediaTypeFormatter' formatter
Feb 07, 2018 02:53:48 PM | Info | JsonMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'JsonMediaTypeFormatter' for type='ManualSearchResult', mediaType='application/json; charset=utf-8'
Feb 07, 2018 02:53:48 PM | Info | DefaultContentNegotiator Negotiate Type='ManualSearchResult', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer]
Feb 07, 2018 02:53:48 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Action returned 'Jackett.Models.DTO.ManualSearchResult'
Feb 07, 2018 02:53:48 PM | Info | Manual search for "Justin Timberlake Man of the Woods" on torrentday with 0 results.
Feb 07, 2018 02:53:48 PM | Debug | WebClient(HttpWebClient): Returning OK => [{"t":3037810,"c":41,"size":7294049938,"files":587,"seeders":101,"leechers":25,"completed":240,"ctime":1517670668,"category":"Music/Packs","name":"MutzNutz Music Pack 17 2018","download-multiplier":0}]
Feb 07, 2018 02:53:48 PM | Debug | WebClient(HttpWebClient).GetString(Url:https://torrentday.it/t.json?29;28;42;20;30;47;43;25;11;5;3;21;22;13;44;48;1;23;41;16;45;4;18;8;10;9;24;32;31;33;46;14;26;7;34;2;6;15;q=Justin+Timberlake+Man+of+the+Woods)
Feb 07, 2018 02:53:48 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Results(request=Jackett.Models.DTO.ApiSearch)'
Feb 07, 2018 02:53:48 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Results(request=Jackett.Models.DTO.ApiSearch)'
Feb 07, 2018 02:53:48 PM | Info | RequiresValidQueryAttribute OnActionExecutingAsync
Feb 07, 2018 02:53:48 PM | Info | RequiresValidQueryAttribute OnActionExecutingAsync Action filter for 'Results(ApiSearch request)'
Feb 07, 2018 02:53:48 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Feb 07, 2018 02:53:48 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Results(ApiSearch request)'
Feb 07, 2018 02:53:48 PM | Info | HttpActionBinding ExecuteBindingAsync Model state is valid. Values: request=Jackett.Models.DTO.ApiSearch
Feb 07, 2018 02:53:48 PM | Info | ModelBinderParameterBinding ExecuteBindingAsync Parameter 'request' bound to the value 'Jackett.Models.DTO.ApiSearch'
Feb 07, 2018 02:53:48 PM | Info | ModelBinderParameterBinding ExecuteBindingAsync Binding parameter 'request'
Feb 07, 2018 02:53:48 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 07, 2018 02:53:48 PM | Info | RequiresApiKeyAttribute OnAuthorizationAsync
Feb 07, 2018 02:53:48 PM | Info | RequiresApiKeyAttribute OnAuthorizationAsync
Feb 07, 2018 02:53:48 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Results(ApiSearch request)'

**Comment by garfield69** [comment]
added cat 27 via 5bfa6ff73609fd43ff5b400874f10f6530d481f0 which will be included in the next (pre)release of Jackett whenever that gets published.
