### ISSUE TITLE
[cpasbien] Exception (cpasbien): Request to https://www.cpabien.bz/derniers/ failed (Error 522) - The tracker seems to be down.: Request to https://www.cpabien.bz/derniers/ failed (Error 522) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by kYc0o** [Jackett/Jackett#2560]
Apparently CPasBien stopped to work, the frontend asked me to submit an issue though I don't know if this is correct. Anyways, feel free to close if I'm mistaken.

**Jackett version**:  Jackett 0.8.670.0
**Mono version** (if not using Windows):  Mono JIT compiler version 5.8.0.108 (tarball Fri Jan 19 18:55:10 UTC 2018)

-------------------------------

**Comment by garfield69** [comment]
legitimate outage
![image](https://user-images.githubusercontent.com/6933240/36004167-0e1809ca-0d96-11e8-8f73-cc2512c97fe3.png)
try again later
