### ISSUE TITLE
[torrentday] Exception (torrentday): Login failed, please reconfigure the tracker to update the cookies: Login failed, please reconfigure the tracker to update the cookies (Test)

### ISSUE THREAD

**Issue by niftienev** [Jackett/Jackett#2562]
I still lose Torrentday at least 3 times a day. Redoing the cookie works OK. But it is a pain and seems to me to be a waste of time using Jackett.

**Comment by garfield69** [comment]
then stop using it. 
there is nothing we can do about this at the moment.

**Comment by niftienev** [comment]
Thank you for your reply, I fixed it anyhow.
