### ISSUE TITLE
[cpasbien] Exception (cpasbien): Got redirected to another domain. Try changing the indexer URL to http://ww1.cpabien.mx/.: Parse error (Test)

### ISSUE THREAD

**Issue by darkcattz** [Jackett/Jackett#2564]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

Hello, 

 An error occured while testing this indexer
Exception (cpasbien): Got redirected to another domain. Try changing the indexer URL to http://ww1.cpabien.mx/.: Parse error

but http://ww1.cpabien.mx/ doesn't exists.

Thanks
Regards

Feb 09, 2018 11:07:39 AM | Error | {0}
-- | -- | --
Feb 09, 2018 11:07:39 AM | Error | Error on 20180209110739 for cpasbien.txtJackett.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to http://ww1.cpabien.mx/.   at Jackett.Indexers.CardigannIndexer.CheckIfLoginIsNeeded (Jackett.Utils.Clients.WebClientStringResult Result, AngleSharp.Dom.Html.IHtmlDocument document) [0x0002e] in <99a65a45fcd94dba9cf02d62c21339a4>:0    at Jackett.Indexers.CardigannIndexer+<PerformQuery>d__28.MoveNext () [0x00872] in <99a65a45fcd94dba9cf02d62c21339a4>:0      <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>302 Found</title> </head><body> <h1>Found</h1> <p>The document has moved <a href="http://ww1.cpabien.mx/">here</a>.</p> </body></html>
Feb 09, 2018 10:55:58 AM | Error | {0}
Feb 09, 2018 10:55:58 AM | Error | Error on 20180209105558 for cpasbien.txtJackett.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to http://ww1.cpabien.mx/.   at Jackett.Indexers.CardigannIndexer.CheckIfLoginIsNeeded (Jackett.Utils.Clients.WebClientStringResult Result, AngleSharp.Dom.Html.IHtmlDocument document) [0x0002e] in <99a65a45fcd94dba9cf02d62c21339a4>:0    at Jackett.Indexers.CardigannIndexer+<PerformQuery>d__28.MoveNext () [0x00872] in <99a65a45fcd94dba9cf02d62c21339a4>:0      <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>302 Found</title> </head><body> <h1>Found</h1> <p>The document has moved <a href="http://ww1.cpabien.mx/">here</a>.</p> </body></html>

**Comment by kaso17** [comment]
tracker is currently down.
moving domains again?

**Comment by garfield69** [comment]
domain moved to cpabien.mx and restored some old selectors back again. 
15bf794 will be included in the next (pre)release of Jackett, whenever that happens next.
