### ISSUE TITLE
[FRENCH-ADN] Search is different with accent

### ISSUE THREAD

**Issue by itdaboyz** [Jackett/Jackett#257]
Hi,

If you search for something with Jackett with or without accent, result will be different.
Example:
```
Feb 25, 2016 06:06:12 PM	Info	
Manual search for "josephine" on French-ADN with 1 results.
Feb 25, 2016 06:06:05 PM	Info	
Manual search for "joséphine" on French-ADN with 0 results.
```

I think it should return the same thing in both cases as CouchPotato do the search with the accent : 
```
Feb 25, 2016 05:59:00 PM	Info	
Found 0 torrentpotato releases from French-ADN for: Joséphine
```

Thanks !

**Comment by JigSawFr** [comment]
Hi @itdaboyz 
It's strange, but what I can do is to replace all accentued caracters with normal caracters.
I can add on option for this later, why not.

**Comment by itdaboyz** [comment]
Thanks, I think this should work.

**Comment by JigSawFr** [comment]
This problem is related to search engine of FADN tracker. They are working a new search page / engine, please be patient. Jackett is using old page, age the new is truncating torrents name... Please be patient.

**Comment by m1dnight** [comment]
This issue also arises when you search for movies such as "Pokémon Detective Pikachu 2019"  it will not return any results, although the official name(https://www.imdb.com/title/tt5884052/)  is indeed with the accent. 

I would still like to see an option to ignore accents.
