### ISSUE TITLE
[limetorrents] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by rocksolid2018** [Jackett/Jackett#2570]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.663.0
**Mono version** 4.6.2

-------------------------------

**Comment by garfield69** [comment]
in the recent past, users that had trouble with limetorrents turn out to be having trouble with it's certificate.
consider upgrading your mono to the latest version, currently 5.8 http://www.mono-project.com/download/#download-lin
