### ISSUE TITLE
Jackett test for root gives false positive on Debian if started via init script

### ISSUE THREAD

**Issue by CptnKickass** [Jackett/Jackett#2572]
When running jackett via init.d script as non-privileged user `jackett`, it displays the warning: `Jackett is running with root privileges. You should run Jackett as an unprivileged user.`

Demonstrated by:
```
jackett@eddard:~$ ps aux | grep Jackett
jackett  15616  0.8  0.8 749944 144796 ?       Sl   15:06   0:02 /usr/bin/mono JackettConsole.exe
jackett  16204  0.0  0.0  12784   968 pts/0    S+   15:10   0:00 grep Jackett
```

I am starting Jackett via `/etc/init.d/jackett` - https://gist.github.com/CptnKickass/9bdc49e0d42fb9853d94f20a8a7d72ab

When I start it without the init.d script, it does not show this error. However, attempting to add `jackett.service` to `/etc/systemd/system/` as described in the wiki, it fails to run without an error message.

---

**Jackett version**:  0.8.676.0
**Mono version** (if not using Windows):  Mono JIT compiler version 5.8.0.108 (tarball Fri Jan 19 18:46:10 UTC 2018)

**Comment by kaso17** [comment]
Probably the same problem as in #2419
You've to manually set the USER environment variable.
But you definitely should try to get the systemd version running (Did you check the journald output?)
