### ISSUE TITLE
[archetorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by harmakhis971** [Jackett/Jackett#2574]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by harmakhis971** [comment]
Hi everyone , 

With the log file i think it will be much  more understandable 


  | Info | Found 0 releases from ArcheTorrent
-- | -- | --
Feb 11, 2018 06:28:41 PM | Error | CardigannIndexer (archetorrent): Error while parsing row '<tr class="t-row"> <td class="ttable_col1" align="center" valign="middle"> 		<a href="torrents.php?cat=22"> 			<img border="0" src="https://archetorrent.com/images/categories/bluray.png" alt="bluray">			 		</a> 	</td> <td class="ttable_col2" align="center" valign="middle"> 		<a href="https://archetorrent.com/uploads/images/91368.jpg" class="highslide" onclick="return hs.expand(this)"> 			<img src="https://archetorrent.com/uploads/images/91368.jpg" alt="Highslide JS" title="Click to enlarge" height="50" width="40">			 		</a> 	</td> <td class="ttable_col1" nowrap="">&nbsp;<a href="torrents-details.php?id=91368&amp;hit=1" onmouseover="return overlib('<table width=100% class=ttable_col1 cellspacing=0 cellpadding=5 align=center><tr><td class=ttable_head colspan=2 align=center>Accident.Man.2018.MULTI.BluRay.1080p.AVC.DTS-HD.MA5.1-MTeam</td></tr><tr valign=top><td align=center><img border=0 width=100 src=https://archetorrent.com/uploads/images/91368.jpg></td><td><div align=left><b>Poster le: </b>11-02-2018<br /><b>Heure: </b>10:23<br><b>Taille: </b>34.79 GB<br /><b>Terminer: </b>0<br /></div><div align=left><b>Vue: </b>29<br /><b>Langue: </b>Multilangues<br /><b>Hits: </b>4<br /><b>Seeders: </b><font color=green>1</font><br /><b>Leechers: </b><font color=red>1</font> </div></td></tr></table>')" ;="" onmouseout="return nd()"> 			<b>Accident.Man.2018.MULTI.BluRay.1080p.AVC.DTS-HD.MA5.1-MTeam</b> 			<b> 				<font color="#ff0000"> - (Nouveau!)</font> 			</b> <img src="images/free.gif" border="0" alt="">			 <img src="images/seedbox.png" border="0" title="Torrent seedbox">			 		</a> 	</td> 	<td class="ttable_col2" align="center"> 		<a href="account-details.php?id=23529" onmouseover="return overlib('<table width=100% class=ttable_col1 cellspacing=0 cellpadding=4 align=center><tr style=background-color:#000000><td align=center><font color=#B7B7B7><b>harrisheldon</b></font></td><td align=center><font color=#B7B7B7><b>classe:</b> <b>Super Archer<b></font></td></tr><tr valign=top><td align=center><img src=https://www.archetorrent.com/avatars/23529.jpg width=100 border=0 /></td><td colspan=2><div style=margin-top:3px>Inscrit le: <font style=margin-left:24px><small><b>2017-11-14 20:08:46</b></small></font></div><div style=margin-top:3px>Uploader: <font style=margin-left:24px color=limegreen><b>2.43 TB</b></font></div><div style=margin-top:3px>Téléchager: <font style=margin-left:7px color=red><b>11.10 GB</b></font></div><div style=margin-top:3px>Ratio: <font style=margin-left:19px><b>224.34</b></font></div><div style=margin-top:3px>confidentialité: <font style=margin-left:2px><b>normal</b></font></div><div style=margin-top:3px>client: <font style=margin-left:2px><b>rutorrent</b><font></div><div style=margin-top:3px>Donation: <font style=margin-left:2px><b>0&nbsp;€</b><font></div></td></tr></table>');" onmouseout="return nd();"> 			<font color="#8FCF3C">harrisheldon</font> 		</a> 	</td> 	<td class="ttable_col1" align="center"> 		<font size="1" face="verdana"> 			<a href="comments.php?type=torrent&amp;id=91368">0</a> 		</font> 	</td> <td class="ttable_col1" align="center">34.79 GB</td> <td class="ttable_col2" align="center"> 		<font color="green"> 			<b>1</b> 		</font> 	</td> <td class="ttable_col1" align="center"> 		<font color="#ff0000"> 			<b>1</b> 		</font> 	</td> <td class="ttable_col2" align="center"> 		<font color="orange"> 			<b>0</b> 		</font> 	</td> 	<td class="ttable_col1" align="center"> 		<img src="https://archetorrent.com/images/health/health_10.gif" alt="">		 	</td> </tr>':  System.Exception: Error while parsing field=date, selector=td:nth-child(2) a, value=<null>: Attribute "onmouseover" is not set for element <a href="https://archetorrent.com/uploads/images/91368.jpg" class="highslide" onclick="return hs.expand(this)"> 	<img src="https://archetorrent.com/uploads/images/91368.jpg" alt="Highslide JS" title="Click to enlarge" height="50" width="40">	 </a>    at Jackett.Indexers.CardigannIndexer+<PerformQuery>d__28.MoveNext () [0x0160b] in <48b104d44fd84c25a6046ad6d12ad853>:0

**Comment by kaso17** [comment]
@elliotvr  can you have a look?

**Comment by elliotvr** [comment]
@kaso17 there is no more **tbody** in row selector.
Can you fix it, or do i need to make a merge request ?

**Comment by kaso17** [comment]
@elliotvr based on the error it looks like the row selector is working fine but there's a problem with the date field.

If you got a working definition it would be great if you could do a quick pull request (just use the github online file edit feature if you don't want to setup a full git environment).

**Comment by garfield69** [comment]
a67dd5dc6a997f89756f621e8d0718943e3a501d 6e6e89463c0d1becc5327fd04ea37f267c6be3d8
