### ISSUE TITLE
How to backup Jackett settings?

### ISSUE THREAD

**Issue by coaxial** [Jackett/Jackett#2576]
This is not a bug report but a question: If I want to backup Jackett so I can restore the settings on a new install, what do I need to backup? I found `Jackett/ServerConfig.json`, is there anything else?

**Comment by garfield69** [comment]
and also the `Jackett/Indexers` folder where all your individual active indexer configs are stored. That's it. ;-)

**Comment by kaso17** [comment]
You also should backup ~/.config/.mono/keypairs/
Without the keystore it's not possible to decrypt passwords in the config files making them useless.

**Comment by stringer44** [comment]
any solution for windows?

**Comment by JustSomeGuyNZ** [comment]
> any solution for windows?

You can find the files in %ProgramData%\Jackett

**Comment by thedelo187** [comment]
> any solution for windows?

@stringer44 

C:\ProgramData\Jackett\DataProtection\*.xml

**Comment by 07416** [comment]
> You're looking for `/config/Jackett/DataProtection/`, and yep everything should be in the `Jackett` folder.

Not even the parent folder exists on my system:

	[user@localhost ~]$ ls /.config/Jackett/
	ls: cannot access '/.config/Jackett/': No such file or directory
	[user@localhost ~]$ ls /config/Jackett/
	ls: cannot access '/config/Jackett/': No such file or directory

I originally installed Jackett manually on Fedora 33.

**Comment by ilike2burnthing** [comment]
Sorry, I was going off my Docker install. If you restart Jackett and look at the logs it should say something to the effect of: `App config/log directory: /config/Jackett`, that should point you in the right direction.
