### ISSUE TITLE
[ilcorsaronero] Exception (ilcorsaronero): No connection could be made because the target machine actively refused it 127.0.0.1:443: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by spupuz** [Jackett/Jackett#2578]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

ilcorsaronero indexer ita not working

**Comment by kaso17** [comment]
looks like someone (your provider) is messing with your DNS to block https://ilcorsaronero.info/
