### ISSUE TITLE
How to change the password

### ISSUE THREAD

**Issue by LoloBond** [Jackett/Jackett#258]
How can I change/disable the password? I set the same password I use for sonnar and some how I made a typo and can't find a way to change the password. I tried reinstalling but Jackett still password protected. TIA!

**Comment by LoloBond** [comment]
Found it, on Ubuntu delete /.config/Jackett/ServerConfig.json

**Comment by MaDTaZ** [comment]
hey all 
I am running ubuntu but I dont see Jackett in my .config directory.  Would there be another spot for it.

**Comment by kaso17** [comment]
@MaDTaZ
maybe you're looking in the wrong users' home DIR?
Check the jackett log output during startup, one of the first lines tells you where it looks for the config.

**Comment by MaDTaZ** [comment]
@kaso17  thank you looks like it is starting in my root  in stead of my log in 

Much Appreciated.

**Comment by jvacek** [comment]
For those who only find this now, you can also just get rid of the "password" line instead of the entire config and you won't break anything else.
