### ISSUE TITLE
[lostfilm] Exception (lostfilm): log in first: Parse error (Test)

### ISSUE THREAD

**Issue by AbayefD** [Jackett/Jackett#2585]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
based on your error message it appears that you did not successfully login.    
Have you confirmed that you can login by using `https://www.lostfilm.tv/` directly from your browser?      
The correct your Jackett lostfilm indexer config using the wrench icon and try again. 
If you still get this problem, then please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.

**Comment by krin-san** [comment]
Hi, @AbayefD. Parser author here ✋
Got the same error just now. Changed a password and ensured I could login from browser and even entered captcha. Possibly they changed smth in webpage format so auto-relogin fails. Will take a closer look soon..

**Comment by i3laze** [comment]
Thanks for fixing.
Unfortunately, naming on LostFilm differs heavily from Sonarr's standards.

HomeLand series gives 0 results, The Magicians give "Release Rejected: Unknown Series"

**Comment by krin-san** [comment]
@i3laze, not sure why you get 0 results for HomeLand coz manual Search in Jackett for "HomeLand" word and manual search for "HomeLand S7E1" in Sonarr both gave me results. I assume Sonarr could find the whole season as well, but can't check that without a button for that.

If you know any particular issue with the latest version of LostFilm indexer feel free to open new issue for that.
