### ISSUE TITLE
[REQ] Add Romanian Metal Tracker 

### ISSUE THREAD

**Issue by 0xAtreides** [Jackett/Jackett#2587]
** Jackett Version 0.8.692.0 **:  
**Mono JIT compiler version 5.4.1.6 

-------------------------------

Please add this amazing tracker for metal music...

http://metal.iplay.ro

Thanks for your work!

**Comment by xfouloux** [comment]
well looks like I've got it =) !

**Comment by ilike2burnthing** [comment]
https://metal.iplay.ro/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up
