### ISSUE TITLE
[almost all indexers] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by sho-87** [Jackett/Jackett#2592]
**Jackett version**:  0.8.676.0
**Mono version** (if not using Windows):  

-------------------------------

I recently updated my docker container (running this on unraid) to the latest version of Jackett, and since updating I've not been able to connect/test any indexers. About 90% of them fail the test, so I'm guessing something changed in the latest update?

[log.txt](https://github.com/Jackett/Jackett/files/1728456/log.txt)

**Comment by kaso17** [comment]
You're IP might have got blacklisted by cludflare, from the log it looks like you've to solve a cloudflare captcha e.g. for btdb.to (Which jackett can't do).

**Comment by sho-87** [comment]
if Im failing a captcha for one indexer, why do all the other indexers also fail the test?

**Comment by kaso17** [comment]
the log doesn't include any other errors.

**Comment by flightlevel** [comment]
No response, closing
