### ISSUE TITLE
Tasmanit.es: Unable to parse episodes from release name

### ISSUE THREAD

**Issue by zang74** [Jackett/Jackett#2593]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  v0.8.692
**Mono version** (if not using Windows):  5.8.0.108

-------------------------------

I'm not sure if this is an issue with all sites running on TS Special Edition, but long file names on Tasmanit.es are having issues.

Running a search on Sonarr with Jackett proxy doesn't find available files because the file name is truncated on the website. However, the information is there in the tooltip, and could be scraped just as easily as the anchor tag. 

![screen shot 2018-02-15 at 1 32 34 pm](https://user-images.githubusercontent.com/5435684/36274132-c5649608-1254-11e8-9065-2af9a046a4f8.png)
![screen shot 2018-02-15 at 1 21 57 pm](https://user-images.githubusercontent.com/5435684/36273961-3f5ce5c4-1254-11e8-9767-a8a0569a6d39.png)
![screen shot 2018-02-15 at 1 22 22 pm](https://user-images.githubusercontent.com/5435684/36273983-5188cc68-1254-11e8-9359-86177eaeec03.png)

**Comment by kaso17** [comment]
Might be fixed via ed82e34d104591f48914f9686819bf6752eb56ea
please test and report (I don't have access)

**Comment by zang74** [comment]
That fixed it. Thanks! It does seem like TS Special Edition-based websites do truncate search listings. To note; TVCUK does the same, but seems to be truncated to a longer length:
![screen shot 2018-02-16 at 4 19 44 pm](https://user-images.githubusercontent.com/5435684/36329828-60d44a8a-1335-11e8-8580-b3257daa79ce.png)
