### ISSUE TITLE
not able to add nCore tracker

### ISSUE THREAD

**Issue by eszge100** [Jackett/Jackett#2594]
Hi, 

I tried to re-install Jackett after having troubles with version (0.7.1483.0) from Synocommunity, Mono version: 5.4.1.6-9. It kept stopping and I was unable to update it from WebUI. After re-install there was still no success to get the latest update plus I could not add nCore indexer as I get the notification of "Configuration failed: An error occurred while sending the request" on the bottom. Had the same issue before but that time I could add nCore second or third try.

-------------------------------

**Comment by kaso17** [comment]
nCore seems to be extremely slow currently, the requests probaly times out
Please also see https://github.com/SynoCommunity/spksrc/issues/3150
