### ISSUE TITLE
[torrentday] Your cookie did not work: Your cookie did not work (Config)

### ISSUE THREAD

**Issue by VilDegard** [Jackett/Jackett#2595]
Hi,

As stated in the title, cookies from TD are no longer recognised by Jackett. IPTorrents cookie still work though.

Any welcome warmly welcome.

**Jackett version**:  0.8.216.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
upgrade to v0.8.692 as there have been some changes to cookie handling since 0.8.216 came out.
