### ISSUE TITLE
can you add offcloud support as a download client 

### ISSUE THREAD

**Issue by daveftw84** [Jackett/Jackett#2597]
can you add offcloud support as a download client pleaseeeeeee?

-------------------------------
they have an api system already and support third party api.
they download the torrents,there bandwidth is used... then directly upload to your gdrive you link up to your account. its an amazing time saver and safer alt to regular  torrent clients.
https://offcloud.com/#/remote

**Comment by kaso17** [comment]
Jackett currently doesn't support specific clients at all.
It's probably best to suggest them to add some kind of dummy torrent file handler which you can install on your PC which will send all .torrent files to they cloud client.

If someone want's to implement direct support please get in contact with us before starting to code.
