### ISSUE TITLE
[torrentday] Exception (torrentday): Login failed, please reconfigure the tracker to update the cookies: Login failed, please reconfigure the tracker to update the cookies (Test)

### ISSUE THREAD

**Issue by niftienev** [Jackett/Jackett#2600]
If you want to know:-

This is how you loose site cookies. If you click 'configure' then exit out in any way including the 'x' it will loose the cookie. 

Neville

**Comment by kaso17** [comment]
yes, the second you open the config dialog the cookies are wiped (at least for TD).
