### ISSUE TITLE
Redirection indexers

### ISSUE THREAD

**Issue by eckop** [Jackett/Jackett#2603]
**Jackett version**:  v0.8.701
**Mono version** (if not using Windows):  Windows 10 x64
-------------------------------

Hello,

I have a problem of redirection in jackett, impossible to connect to the links created by jackett (ex: to go on yggtorrent he create me a link http://127.0.0.1:9117/api/v2.0/indexers/yggtorrent / results / potato / that does not work) I had installed before jackett on an external server which did not pose a problem but it poses me problem.

Thank you in advance for your return

**Comment by supremacy2k** [comment]
Replace 127.0.0.1 with the actual ip of the server Jackett is running on, and it should work.

**Comment by eckop** [comment]
Jackett is on my pc and when I put my address, it's always the same.
![image](https://user-images.githubusercontent.com/29877955/36343115-49e9b2be-1408-11e8-81bf-aee2e6b8d831.png)
![image](https://user-images.githubusercontent.com/29877955/36343124-5e474c30-1408-11e8-9cbf-d8da14a267ec.png)

**Comment by supremacy2k** [comment]
Oh sorry, I thought it was the API link for 3rd party software to connect to Jackett, eg. Sonarr or radarr.

**Comment by kaso17** [comment]
please double check the passkey in the URL (should be the jackett API key).
Is this a windows server?

**Comment by garfield69** [comment]
@eckop did you resolve this?

**Comment by flightlevel** [comment]
No response, closing
