### ISSUE TITLE
[horriblesubs] Exception (horriblesubs): Got redirected to another domain. Try changing the indexer URL to http://horriblesubs.info/.: Parse error (Test)

### ISSUE THREAD

**Issue by Stanzilla** [Jackett/Jackett#2605]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.670.0
**Mono version** (if not using Windows):  5.8

-------------------------------

I think their SSL cert expired?

**Comment by garfield69** [comment]
use the wrench icon on your jackett dashboard to edit the sitelink and make sure it is loaded with http://horriblesubs.info/
I have no problems accessing this site on my win7 jackett 0.8.701.0

**Comment by Stanzilla** [comment]
Well I know how to change the URL I just thought the default has to be changed if their cert expired and they don't renew it.

**Comment by garfield69** [comment]
as far as I know `http://horriblesubs.info/` is the default and since its http there is not cert.
if you caoded a sitelink starting with https: you get redirected to http: which is probably what is happening to you. Thats their site doing it, bot chrome browser or jackett.

**Comment by Stanzilla** [comment]
Weird, it worked before, not sure why I had changed that then.

**Comment by garfield69** [comment]
i've added a legacylinks block 785d00a for those users who might be on https to avoid getting the redirection error.
