### ISSUE TITLE
[rarbg] An error occurred while sending the request.: Unable to connect to the remote server (Config)

### ISSUE THREAD

**Issue by HHCHunter** [Jackett/Jackett#2607]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  Most recent stable build from Github prebuilds.

**Comment by sar-cough-agus** [comment]
I've had (I assume) the same problem with NBL (formerly TtN). Essentially the tracker won't load.

I don't understand these at all but here are my log files of the event:

Feb 18, 2018 04:43:24 PM | Info | IndexerApiController Dispose
-- | -- | --
Feb 18, 2018 04:43:23 PM | Info | IndexerApiController Dispose
Feb 18, 2018 04:43:23 PM | Info | Content-type='application/json; charset=utf-8', content-length=7273
Feb 18, 2018 04:43:23 PM | Info | IndexerApiController ExecuteAsync
Feb 18, 2018 04:43:23 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Feb 18, 2018 04:43:23 PM | Error | {0}
Feb 18, 2018 04:43:23 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Feb 18, 2018 04:43:23 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Feb 18, 2018 04:43:23 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Config(ConfigItem[] config)'
Feb 18, 2018 04:43:23 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Feb 18, 2018 04:43:23 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Config(ConfigItem[] config)'
Feb 18, 2018 04:43:23 PM | Error | ApiControllerActionInvoker InvokeActionAsync
Feb 18, 2018 04:43:23 PM | Error | ReflectedHttpActionDescriptor ExecuteAsync
Feb 18, 2018 04:43:01 PM | Debug | WebClient(HttpWebClient).GetString(Url:https://nebulance.io/login.php)
Feb 18, 2018 04:43:01 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Config(config=Jackett.Models.DTO.ConfigItem[])'
Feb 18, 2018 04:43:01 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Config(config=Jackett.Models.DTO.ConfigItem[])'
Feb 18, 2018 04:43:01 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync
Feb 18, 2018 04:43:01 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Config(ConfigItem[] config)'
Feb 18, 2018 04:43:01 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Feb 18, 2018 04:43:01 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Config(ConfigItem[] config)'
Feb 18, 2018 04:43:01 PM | Info | HttpActionBinding ExecuteBindingAsync Model state is valid. Values: config=Jackett.Models.DTO.ConfigItem[]
Feb 18, 2018 04:43:01 PM | Info | FormatterParameterBinding ExecuteBindingAsync Parameter 'config' bound to the value 'Jackett.Models.DTO.ConfigItem[]'
Feb 18, 2018 04:43:01 PM | Info | JsonMediaTypeFormatter ReadFromStreamAsync Value read='Jackett.Models.DTO.ConfigItem[]'
Feb 18, 2018 04:43:01 PM | Info | JsonMediaTypeFormatter ReadFromStreamAsync Type='ConfigItem[]', content-type='application/json'
Feb 18, 2018 04:43:01 PM | Info | FormatterParameterBinding ExecuteBindingAsync Binding parameter 'config'
Feb 18, 2018 04:43:01 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 18, 2018 04:43:01 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 18, 2018 04:43:01 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 18, 2018 04:43:01 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Config(ConfigItem[] config)'
Feb 18, 2018 04:43:01 PM | Info | ApiControllerActionSelector SelectAction
Feb 18, 2018 04:43:01 PM | Info | IndexerApiController ExecuteAsync
Feb 18, 2018 04:43:01 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.IndexerApiController

**Comment by sar-cough-agus** [comment]
Strike that. Ran the console as admin and now it's working. Resolved for me (if it's the same issue)

**Comment by garfield69** [comment]
@HHCHunter  I've no trouble accessing the RARBG api via my win7 jackett 0.8.701.0
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.

**Comment by lkeels** [comment]
Jackett appears to use torrentapi.org for RARBG. TorrentAPI.org is gone. The domain name is up for sale.

**Comment by garfield69** [comment]
@lkeels  the RarBG API domain has been re-registered and I expect the API service will resume shortly.

RarBG insist we use their API instead of the usual html web-scraping that we do for most of the other sites we support searching on.

**Comment by garfield69** [comment]
no reply from OP, closing.
