### ISSUE TITLE
[Synology] Don't save settings when password is enable

### ISSUE THREAD

**Issue by Jamyz** [Jackett/Jackett#2611]
**Jackett version**:  0.8.701
**Mono version** (if not using Windows):  5.4.1.6-9
-------------------------------
Hi. I have a synology with DSM 6.1.
- I installed Jackett with community package ( Jackett Beta 0.7.1483)
- I updated to 0.8.701
When i set a password, and come back in web, i don't have api key and i can't save settings with "Apply server settings". I have  "Error loading Jackett settings, request to Jackett server failed, is server running ?"

How i can fix that ?
Thanks

PS: I dont use Docker because the latest Docker package don't run correctly on my synology.

**Comment by kaso17** [comment]
Probably related to #3150, please follow the instructions there.

**Comment by Jamyz** [comment]
@kaso17 #3150 ??? i have the issue #2611. Give me the url, please. Thanks....

**Comment by kaso17** [comment]
sorry, https://github.com/SynoCommunity/spksrc/issues/3150
