### ISSUE TITLE
non standard tmp path query.

### ISSUE THREAD

**Issue by userdocs** [Jackett/Jackett#2613]
I used jackett on Feral hosting. So as a non root user on Debian stable. I start jackett using this command.

~~~
screen -dmS jackett && screen -S jackett -p 0 -X stuff "export TMPDIR=~/.userdocs/tmp; ~/bin/mono --debug ~/.jackett/JackettConsole.exe -c libcurl^M"
~~~

What i noticed is that when jackett auto updates the tmp path seems to be misinterpreted and what should be:

~~~
media/1234/username/.userdocs/tmp
~~~

Is read as

~~~
media/1234/username/~/.userdocs/tmp
~~~

Creating a folder named `~` in my home directory instead interpreting it as part of the path. So i end up with a directory structure like this:

~~~
media/1234/username/~/.userdocs/tmp/.../...
~~~

I resolved this by using this command instead:

~~~
screen -dmS jackett && screen -S jackett -p 0 -X stuff "export TMPDIR=.userdocs/tmp; ~/bin/mono --debug ~/.jackett/JackettConsole.exe -c libcurl^M"
~~~

This solves the issue but does not fix the problem. I use this same command with Sonarr and Radarr and they interpret the environment variable properly and auto update using the correct location. jackett is the odd one out when it comes to interpreting this variable `export TMPDIR=~/.userdocs/tmp`.

Can you have a look at this to see if something you fix?

**Jackett version**:  v0.8.*
**Mono version** 5.8.*

-------------------------------

**Comment by kaso17** [comment]
According to https://msdn.microsoft.com/en-us/library/system.io.path.gettemppath(v=vs.110).aspx you should use the TMP or TEMP environment variables, not TMPDIR

**Comment by userdocs** [comment]
Thank you for the reply. While i will take that into account and adapt the command to reflect that information, it does not quite address the issue i was experiencing with `~` being incorrectly interpreted a part of the part instead of being expanded to insert the required path.

Would using this command solve that issue?

~~~
export TMP=~/.userdocs/tmp;
~~~

**Comment by kaso17** [comment]
that might be a mono limitation, try using $HOME instead of ~

**Comment by kaso17** [comment]
does $HOME work for you?

**Comment by userdocs** [comment]
I will have to wait until your 2nd release supporting 5.10 to test this as i have updated to mono 5.10.

The issue is realized when Jackett auto updates and creates a folder instead of using the defined folder. I'll have it all set up and waiting. As soon as a new version is release and it auto updates i'll know if it worked.

Is there a way to log issue better? Such as how Jacket is interpreting the path. As i said before, Sonarr/Radarr don't seem to have this issue.

**Comment by userdocs** [comment]
Seems like using `$HOME`  instead of `~` worked to overcome this issue.

~~~
03-09 06:59:25 Info Deleting JackettUpdate temp files from /media/****/username/.userdocs/tmp/JackettUpdate-v0.8.745-636561755585212950
~~~

**Comment by kaso17** [comment]
ok, seems like it's a mono limitation then
