### ISSUE TITLE
[Request new traker] - Italian Open Torrent

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#2614]
Hi, I don't know if is possible to add this website
https://www.italianopentorrent.info/index.php

Is a kind of semi-private traker, registration is required if you want to became a donator member (download without advertise). Without registration the site works but there's no direct link to .torrent or magnet, you download one zip file that contain all the torrent

On site you can find games, movie and tv show.

What do you think about it?

Jo

**Comment by bubez81** [comment]
quote!

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by Jorman** [comment]
Hi, sorry I see that only now! I'm not so good in general, I can try, I've to understand some to make it works, maybe I can start and see what happen

**Comment by Jorman** [comment]
Traker is not available anymore
