### ISSUE TITLE
[YggTorrent] No results found for Animes

### ISSUE THREAD

**Issue by Veichey** [Jackett/Jackett#2615]
**Jackett version**:  0.8.715.0
**Mono version** (if not using Windows):  5.8.0.108

-------------------------------
Well I can't use Sonarr with yggtorrent for searching any anime, Sonarr find nothing. I used the search bar on my Jackett and I finded the torrents, so idk, perhaps I missconfigured anything. 

I drop the logs of Jackett and screens of my configuration. Also, I tried to launch the search without the Anime tag in Sonarr but it didn't worked too. Yet, TV Shows work perfectly.
[log.txt](https://github.com/Jackett/Jackett/files/1740812/log.txt)
![vivaldi_2018-02-20_17-05-31](https://user-images.githubusercontent.com/32543196/36434875-618f82fe-1660-11e8-94eb-bb9e3ce04be2.png)

Btw there is a bug with Nyaa but I haven't checked yet, so if it's really buggy (see logs at the end) I will perhaps make a new issue.

**Comment by garfield69** [comment]
I've added anime cats with 4b3adbc which will be available in the next (pre)release of jackett whenever that comes out. let me know if that makes a difference.

**Comment by Veichey** [comment]
I've retried and it doesn't change anything. Sonarr seems to searching each episodes and it does not ring a bell on yggtorrent, and if I set the serie type to **standart** nothing changes.

I drop a screen of the manual search with jackett, the logs didn't change from earlier.
![vivaldi_2018-02-20_21-21-32](https://user-images.githubusercontent.com/32543196/36447299-46fb94ea-1684-11e8-8135-e616554880d2.png)
![putty_2018-02-20_21-23-53](https://user-images.githubusercontent.com/32543196/36447340-684e6b0e-1684-11e8-892a-c7e9dbaa2466.png)

**Comment by garfield69** [comment]
did you apply the fix manually to your copy of the indexer?  because the next (pre)release of jackett is not out yet.

**Comment by Veichey** [comment]
Yeah, I applied manually the fix to my indexer.

**Comment by garfield69** [comment]
oh I see. The two *Ergo Proxy* torrents on yggtorrent are all the episodes bundled in one torrent. 
I don't think this has anything to do with Jackett, this is Sonarr looking for individual episode torrents and not finding any since yggtorrent has none.

**Comment by Veichey** [comment]
Well I'm going to ask for help with Sonarr, given that it's not an issue related to Jackett, finally. Thanks for help 👍
