### ISSUE TITLE
[zooqle] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by SteffanCline** [Jackett/Jackett#2617]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  latest
**Mono version** (if not using Windows):  latest

-------------------------------
I know I reported this before but I am curious. I went to the site directly and clicked on the cloudfare verifier but trying to search even manually through Jackett fails too. Is it a matter of Jackett saving it's own cookie? I get some decent search results when manually searching and would like to find a way to use it through Jackett. I thought I saw somewhere that there was an API for cloudfare. Any chance of incorporating that? I use a VPN and have changed IPs yet cloudfare always catches them. I'm at a bit of a loss.

**Comment by kaso17** [comment]
I assume you're getting the cloudflare captcha? It can't be solved automatically.
I suggest you get a better VPN/server with an IP which doesn't get blacklisted.
