### ISSUE TITLE
AST4u login doesn't work.

### ISSUE THREAD

**Issue by le34567** [Jackett/Jackett#2619]
**Jackett version**:  0.8.716.0

AST4u login doesn't work. It says that it got redirected. Both username and password were correct.
**Log**:https://ghostbin.com/paste/etew2

**Comment by kaso17** [comment]
please repost the log (ghostbin seems to be down: Service Unavailable)

**Comment by garfield69** [comment]
the log you provided shows that ast4u returned `Benutzername oder Passwort ungï¿½ltig` -> `Username or password invalid`
Assuming that you have manually logged onto `https://www.ast4u.me/login.php` via your browser to confirm that you have the correct username and password, then I suggest using the trashbin icon on your Jackett Dashboard to delete your ast4u indexer, and add it anew, entering the correct username and password.

**Comment by flightlevel** [comment]
No response, closing
