### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by brentqld** [Jackett/Jackett#262]
This is not so much of an issue as a compliment: I am very impressed with Jackett on Sonarr in a Synology DS215+
I cannot contribute any expertise to the Jackett project but I am in a position to be able to donate a small financial contribution to the cause. Is there any way to donate financially to the Jackett project, if so, how?

Cheers, Brent

**Comment by Azerelat** [comment]
Not at the minute but we appreciate the gesture, maybe in the future should costs arise but at the minute development is fueled by our passion for helping people.
