### ISSUE TITLE
Problems with configuration management

### ISSUE THREAD

**Issue by opsxcq** [Jackett/Jackett#2621]
If possible, add some features to make configuration management easier. I've been trying to set some variables (InstanceID, Api key, enabled search engines) via configuration, but every time that I start Jackett, my configuration (ServerConfig.json) is overwritten by Jackett.

If possible, can Jackett read those configuration from environment variables ? So the deploy with automated tools will be easier and less manual. Using environment variables I can set them in one place and reuse across all services that use Jackett in my deploy.

Thank you !

Environment: Debian 9.2 running as a docker container
Jackett version: 0.8.692
Mono:
```
Mono JIT compiler version 5.8.0.108 (tarball Fri Jan 19 18:46:10 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

**Comment by kaso17** [comment]
What exactly do you mean with "enable search engines"?

**Comment by opsxcq** [comment]
I mean, any configuration that can be done via the web interface, if possible, let it be done by environment variables too, for example, enable and configure a certain torrent search engine, could be:

```
JACKETT_PIRATEBAY_ENABLED=true
JACKETT_PIRATEBAY_USERNAME=xxxxx
JACKETT_PIRATEBAY_PASSWORD=xxxxx
```

Or any other variable name pattern that you find more suitable for this situation. More about why I find this useful, can be found here: https://12factor.net/config

Thank you !!

**Comment by kaso17** [comment]
I think making all indexer configurable via environment variables would become very ugly very fast (too many different options)/login methods.
I can think of adding support for storing passwords in plaintext, then it should be easy to edit the config files, etc.
If you want to configure the indexers I would suggest you go through the JSON/REST internal API which is used by the web interface too.
