### ISSUE TITLE
[nyaa-pantsu] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by enchained** [Jackett/Jackett#2623]
**Jackett version**:  0.8.716.0
**OS**: Synology DSM 6
**Mono version** (if not using Windows):  5.4.1.6-9 (synocommunity package)
**Logs:** https://pastebin.com/4NJw0jGe

Nyaa-pantsu stopped working for me, and I think it's the only nyaa with a properly working search since I haven't been able to get older releases in sonarr since pantsu indexer stopped working, only the recent ones.

**Comment by kaso17** [comment]
your jackett version is very old, please update
