### ISSUE TITLE
TorrentDay can't find music

### ISSUE THREAD

**Issue by eriuhdkjnwwk** [Jackett/Jackett#2624]
Trying to use Headphones to find music via Jackett.

It appears that the GetString is using the wrong category to find music:

WebClient(HttpWebClient).GetString(Url:https://torrentday.it/t.json?45;q=In+Flames+Siren+Charms)
Returns nothing ````https://torrentday.it/t.json?45;q=In+Flames+Siren+Charms````
Returns Podcasts ````https://torrentday.it/t.json?45````

Jackett Version 0.8.716.0
Windows 8.1

-------------------------------
Log
-------------------------------
When | Level | Message
-- | -- | --
Feb 22, 2018 09:26:54 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
Feb 22, 2018 09:26:54 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
Feb 22, 2018 09:26:54 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Feb 22, 2018 09:26:54 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
Feb 22, 2018 09:26:54 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 22, 2018 09:26:54 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 22, 2018 09:26:54 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 22, 2018 09:26:54 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Feb 22, 2018 09:26:54 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
Feb 22, 2018 09:26:54 PM | Info | ApiControllerActionSelector SelectAction
Feb 22, 2018 09:26:54 PM | Info | ServerConfigurationController ExecuteAsync
Feb 22, 2018 09:26:54 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ServerConfigurationController
Feb 22, 2018 09:26:54 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ServerConfigurationController
Feb 22, 2018 09:26:54 PM | Info | DefaultHttpControllerActivator Create
Feb 22, 2018 09:26:54 PM | Info | HttpControllerDescriptor CreateController
Feb 22, 2018 09:26:54 PM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
Feb 22, 2018 09:26:54 PM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
Feb 22, 2018 09:26:54 PM | Info | http://htpc:9117/api/v2.0/server/logs?_=1519359722064
Feb 22, 2018 09:26:51 PM | Info | ResultsController Dispose
Feb 22, 2018 09:26:51 PM | Info | ResultsController Dispose
Feb 22, 2018 09:26:51 PM | Info | Content-type='application/rss+xml; charset=utf-8', content-length=701
Feb 22, 2018 09:26:51 PM | Info | ResultsController ExecuteAsync
Feb 22, 2018 09:26:51 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Feb 22, 2018 09:26:51 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Torznab(TorznabRequest request)'
Feb 22, 2018 09:26:51 PM | Info | RequiresValidQueryAttribute OnActionExecutedAsync
Feb 22, 2018 09:26:51 PM | Info | RequiresValidQueryAttribute OnActionExecutedAsync Action filter for 'Torznab(TorznabRequest request)'
Feb 22, 2018 09:26:51 PM | Info | ApiControllerActionInvoker InvokeActionAsync
Feb 22, 2018 09:26:51 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.ResponseMessageResult'
Feb 22, 2018 09:26:51 PM | Info | Found 0 releases from TorrentDay for: In Flames Siren Charms
Feb 22, 2018 09:26:51 PM | Debug | WebClient(HttpWebClient): Returning OK => []
Feb 22, 2018 09:26:51 PM | Debug | WebClient(HttpWebClient).GetString(Url:https://torrentday.it/t.json?45;q=In+Flames+Siren+Charms)
Feb 22, 2018 09:26:51 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Torznab(request=Jackett.Models.DTO.TorznabRequest)'
Feb 22, 2018 09:26:51 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Torznab(request=Jackett.Models.DTO.TorznabRequest)'
Feb 22, 2018 09:26:51 PM | Info | RequiresValidQueryAttribute OnActionExecutingAsync
Feb 22, 2018 09:26:51 PM | Info | RequiresValidQueryAttribute OnActionExecutingAsync Action filter for 'Torznab(TorznabRequest request)'
Feb 22, 2018 09:26:51 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Feb 22, 2018 09:26:51 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Torznab(TorznabRequest request)'
Feb 22, 2018 09:26:51 PM | Info | HttpActionBinding ExecuteBindingAsync Model state is valid. Values: request=Jackett.Models.DTO.TorznabRequest
Feb 22, 2018 09:26:51 PM | Info | ModelBinderParameterBinding ExecuteBindingAsync Parameter 'request' bound to the value 'Jackett.Models.DTO.TorznabRequest'
Feb 22, 2018 09:26:51 PM | Info | ModelBinderParameterBinding ExecuteBindingAsync Binding parameter 'request'
Feb 22, 2018 09:26:51 PM | Info | HttpActionBinding ExecuteBindingAsync
Feb 22, 2018 09:26:51 PM | Info | RequiresApiKeyAttribute OnAuthorizationAsync
Feb 22, 2018 09:26:51 PM | Info | RequiresApiKeyAttribute OnAuthorizationAsync
Feb 22, 2018 09:26:51 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Torznab(TorznabRequest request)'
Feb 22, 2018 09:26:51 PM | Info | ApiControllerActionSelector SelectAction
Feb 22, 2018 09:26:51 PM | Info | ResultsController ExecuteAsync
Feb 22, 2018 09:26:51 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ResultsController
Feb 22, 2018 09:26:51 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ResultsController
Feb 22, 2018 09:26:51 PM | Info | DefaultHttpControllerActivator Create
Feb 22, 2018 09:26:51 PM | Info | HttpControllerDescriptor CreateController

**Comment by garfield69** [comment]
as far as we know, 45 is podcasts.  here are the other audio cats:
```
            AddCategoryMapping(17, TorznabCatType.Audio, "Music/Audio");
            AddCategoryMapping(23, TorznabCatType.AudioForeign, "Music/Non-English");
            AddCategoryMapping(41, TorznabCatType.Audio, "Music/Packs");
            AddCategoryMapping(16, TorznabCatType.AudioVideo, "Music/Video");
            AddCategoryMapping(27, TorznabCatType.Audio, "Music/Flac");
```
so adjust you cats selection to include the other audio cats and you should be good to go.

**Comment by eriuhdkjnwwk** [comment]
Sorry was away for a bit. How do I adjust my categories? Is that done in Jackett?

**Comment by kaso17** [comment]
assuming you're using the torznap API you can adjust it via the cats argument. See Toznab API spcs and the indexer configuration dialog for a list of available categories.
