### ISSUE TITLE
" Jackett is running with root privileges." and also not saving my indexers.

### ISSUE THREAD

**Issue by MaddionMax** [Jackett/Jackett#2625]
root@77mc:/opt/jackett# mono JackettConsole.exe -t
02-23 09:20:49 Info Tracing enabled.
02-23 09:20:49 Info App config/log directory: /home/maddionmax/.config/Jackett
02-23 09:20:50 Info Starting Jackett 0.8.716.0
02-23 09:20:50 Info Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5)
02-23 09:20:50 Info OS version: Unix 4.13.0.36 (64bit OS) (64bit process)
02-23 09:20:50 Info ThreadPool MaxThreads: 400 workerThreads, 200 completionPortThreads
02-23 09:20:50 Info issue: Ubuntu 17.10 \n \l
02-23 09:20:50 Info mono version: 5.8.0.127 (tarball Wed Feb 21 16:43:57 UTC 2018)
02-23 09:20:50 Info TrustedRootCertificates count: 149
02-23 09:20:50 Error Jackett is running with root privileges. You should run Jackett as an unprivileged user.
02-23 09:20:50 Info Using HTTP Client: HttpWebClient

I see Jackett is running with root, but why is this problem?

**Comment by kaso17** [comment]
because you're starting it as root, you shouldn't do that, please use a separate user.
