### ISSUE TITLE
ImmortalSeed Torznab Feed cannot be added to sonarr

### ISSUE THREAD

**Issue by aser007** [Jackett/Jackett#2626]
Indexer 4 Immortalseed seems to work in Jacket(Test successful for immortalseed) but not in Sonarr(Test failed)

Sonarr Error Logs:

NzbDroneErrorPipeline | Invalid request Validation failed:   -- Unable to connect to indexer, check the log for more details | 10:57

-- | -- | --
  | Torznab | Unable to connect to indexer: HTTP request failed: [404:NotFound] [GET] at [http://10.10.10.100:9117/api/v2.0/indexers/immortalseed/results/torznab443?t=caps&apikey=aw82relft8x0f6d5d4elulgs5pg7zwx9] | 10:57

  | HttpClient | HTTP Error - Res: [GET] http://10.10.10.100:9117/api/v2.0/indexers/immortalseed/results/torznab443?t=caps&apikey=(removed) 404.NotFound <Error><Message>No HTTP resource was found that matches the request URI 'http://10.10.10.100:9117/api/v2.0/indexers/immortalseed/results/torznab443?t=caps&amp;apikey=aw82relft8x0f6d5d4elulgs5pg7zwx9'.</Message><MessageDetail>No action was found on the controller 'Results' that matches the name 'torznab443'.</MessageDetail></Error> | 10:57

all my other indexers work

**Comment by kaso17** [comment]
probably a typo?
The URL shouldn't end with torznab443, just torznab

**Comment by aser007** [comment]
http://10.10.10.100:9117/api/v2.0/indexers/immortalseed/results/torznab/ this is the url i get from jacket i put it in it adds the 443 itself

**Comment by kaso17** [comment]
then it's a sonarr issue, please open an issue with them.
