### ISSUE TITLE
[isohunt] Exception (isohunt): Request to https://isohunt.to/latest.php?ihq= failed (Error 522) - The tracker seems to be down.: Request to https://isohunt.to/latest.php?ihq= failed (Error 522) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by strongy** [Jackett/Jackett#2628]
[isohunt] Exception (isohunt): Request to https://isohunt.to/latest.php?ihq= failed (Error 522) - The tracker seems to be down.: Request to https://isohunt.to/latest.php?ihq= failed (Error 522) - The tracker seems to be down. (Test)

**Comment by garfield69** [comment]
isohunt.to shutdown in august 2017.      
there is a clone still running as isohunt2.net.      
On your Jackett Dashboard, you could try using the wrench to edit your indexer to replace the site link, but if that does not work consider upgrading your Jackett to the latest version.
