### ISSUE TITLE
[yggtorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Saskya99** [Jackett/Jackett#2629]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.436.0
**Mono version** (if not using Windows):  Mono JIT compiler version 5.8.0.127

-------------------------------
[log.20180225.00029.txt](https://github.com/Jackett/Jackett/files/1756345/log.20180225.00029.txt)

**Comment by garfield69** [comment]
Upgrade to the latest Jackett, currently v0.8.716.     
There have been updates to the yggtorrent definition to fix the download selector since 0.8.436 came out.

**Comment by Saskya99** [comment]
thanks it works and sorry
