### ISSUE TITLE
Request URI added extra /

### ISSUE THREAD

**Issue by Ryahn** [Jackett/Jackett#263]
I am currently having an issue where there is an extra / being added to the URL of the download link. This causes the link to not work.

http://a.pomf.cat/cxyhil.png

https://iptorrents.com//download.php/1547348/XXXXXX.torrent

**Comment by flightlevel** [comment]
What version of Jackett are you running?

**Comment by Ryahn** [comment]
Jackett Version 0.7.33.0

**Comment by flightlevel** [comment]
You are on a very old version, this was fixed a while ago, update to latest release
