### ISSUE TITLE
[LostFilm.tv] Cleaning titles for Sonarr

### ISSUE THREAD

**Issue by i3laze** [Jackett/Jackett#2631]
Anyone to fix LostFilm title parsing?
Got 0 results on "Homeland" series and "The Magicians (2015)" give me results with "Release rejected: Unknown Series" (Jackett better drop this 'year in title' thing).

**Comment by vSh1ny** [comment]
I get normal response upon searching for both "Homeland" and "The Magicians", excluding the year.
<details>
<summary>Console output</summary>

```
Info Manual search for "Homeland" on lostfilm with 26 results.
Info Manual search for "The Magicians" on lostfilm with 30 results.
```
</details >

&nbsp;
But recently I get this with rather annoying regularity, probably it's somehow related:
<details>
<summary>Log messages sans the hostname and tokens</summary>

```
Mar 06 07:03:40 docker-jackett[6598]: 03-06 07:03:40 Error lostfilm: Error while parsing row '<div class="inner-box--item">
Mar 06 07:03:40 docker-jackett[6598]:             <div class="inner-box--label">
Mar 06 07:03:40 docker-jackett[6598]: HD                        </div>
Mar 06 07:03:40 docker-jackett[6598]:             <div class="inner-box--link main"><a href="http://tracktor.in/td.php?s=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Звездные врата: Начало.
Mar 06 07:03:40 docker-jackett[6598]: 1 сезон, 7 серия.
Mar 06 07:03:40 docker-jackett[6598]: </a></div>
Mar 06 07:03:40 docker-jackett[6598]:             <div class="inner-box--link sub"><a href="http://tracktor.in/td.php?s=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">http://tracktor.in/td.php?s=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</a></div>
Mar 06 07:03:40 docker-jackett[6598]:             <div class="inner-box--desc">Видео: . Размер: 397.44 МБ. Перевод: Многоголосый закадровый (LostFilm.TV)</div>
Mar 06 07:03:40 docker-jackett[6598]:           </div>':
Mar 06 07:03:40 docker-jackett[6598]: System.FormatException: Input string was not in a correct format.
Mar 06 07:03:40 docker-jackett[6598]:   at System.Number.ParseSingle (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt) [0x00085] in <a6f810169ec746eeb2789b925e2858c0>:0
Mar 06 07:03:40 docker-jackett[6598]:   at System.Single.Parse (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) [0x00000] in <a6f810169ec746eeb2789b925e2858c0>:0
Mar 06 07:03:40 docker-jackett[6598]:   at System.Single.Parse (System.String s, System.Globalization.NumberStyles style, System.IFormatProvider provider) [0x0000e] in <a6f810169ec746eeb2789b925e2858c0>:0
Mar 06 07:03:40 docker-jackett[6598]:   at Jackett.Utils.ParseUtil.CoerceFloat (System.String str) [0x00010] in <594e817a3cf9452f8e1f75df9b6a2bd4>:0
Mar 06 07:03:40 docker-jackett[6598]:   at Jackett.Models.ReleaseInfo.GetBytes (System.String str) [0x0004c] in <594e817a3cf9452f8e1f75df9b6a2bd4>:0
Mar 06 07:03:40 docker-jackett[6598]:   at Jackett.Indexers.LostFilm+<FollowTrackerRedirection>d__24.MoveNext () [0x00372] in <594e817a3cf9452f8e1f75df9b6a2bd4>:0
Mar 06 07:03:40 docker-jackett[6598]: 03-06 07:03:40 Error lostfilm: Error while parsing row '<div class="inner-box--item">
Mar 06 07:03:40 docker-jackett[6598]:             <div class="inner-box--label">
Mar 06 07:03:40 docker-jackett[6598]: MP4                        </div>
Mar 06 07:03:40 docker-jackett[6598]:             <div class="inner-box--link main"><a href="http://tracktor.in/td.php?s=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Звездные врата: Начало.
Mar 06 07:03:40 docker-jackett[6598]: 1 сезон, 7 серия.
Mar 06 07:03:40 docker-jackett[6598]: </a></div>
Mar 06 07:03:40 docker-jackett[6598]:             <div class="inner-box--link sub"><a href="http://tracktor.in/td.php?s=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">http://tracktor.in/td.php?s=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</a></div>
Mar 06 07:03:40 docker-jackett[6598]:             <div class="inner-box--desc">Видео: . Размер: 350.40 МБ. Перевод: Многоголосый закадровый (LostFilm.TV)</div>
Mar 06 07:03:40 docker-jackett[6598]:           </div>':
Mar 06 07:03:40 docker-jackett[6598]: System.FormatException: Input string was not in a correct format.
Mar 06 07:03:40 docker-jackett[6598]:   at System.Number.ParseSingle (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt) [0x00085] in <a6f810169ec746eeb2789b925e2858c0>:0
Mar 06 07:03:40 docker-jackett[6598]:   at System.Single.Parse (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) [0x00000] in <a6f810169ec746eeb2789b925e2858c0>:0
Mar 06 07:03:40 docker-jackett[6598]:   at System.Single.Parse (System.String s, System.Globalization.NumberStyles style, System.IFormatProvider provider) [0x0000e] in <a6f810169ec746eeb2789b925e2858c0>:0
Mar 06 07:03:40 docker-jackett[6598]:   at Jackett.Utils.ParseUtil.CoerceFloat (System.String str) [0x00010] in <594e817a3cf9452f8e1f75df9b6a2bd4>:0
Mar 06 07:03:40 docker-jackett[6598]:   at Jackett.Models.ReleaseInfo.GetBytes (System.String str) [0x0004c] in <594e817a3cf9452f8e1f75df9b6a2bd4>:0
Mar 06 07:03:40 docker-jackett[6598]:   at Jackett.Indexers.LostFilm+<FollowTrackerRedirection>d__24.MoveNext () [0x00372] in <594e817a3cf9452f8e1f75df9b6a2bd4>:0
Mar 06 07:03:42 docker-jackett[6598]: 03-06 07:03:42 Error lostfilm: Error while parsing row '<div class="inner-box--item">
Mar 06 07:03:42 docker-jackett[6598]:             <div class="inner-box--label">
Mar 06 07:03:42 docker-jackett[6598]: HD                        </div>
Mar 06 07:03:42 docker-jackett[6598]:             <div class="inner-box--link main"><a href="http://tracktor.in/td.php?s=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Звездные врата: Начало.
Mar 06 07:03:42 docker-jackett[6598]: 1 сезон, 6 серия.
Mar 06 07:03:42 docker-jackett[6598]: </a></div>
Mar 06 07:03:42 docker-jackett[6598]:             <div class="inner-box--link sub"><a href="http://tracktor.in/td.php?s=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">http://tracktor.in/td.php?s=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</a></div>
Mar 06 07:03:42 docker-jackett[6598]:             <div class="inner-box--desc">Видео: . Размер: 361.18 МБ. Перевод: Многоголосый закадровый (LostFilm.TV)</div>
Mar 06 07:03:42 docker-jackett[6598]:           </div>':
Mar 06 07:03:42 docker-jackett[6598]: System.FormatException: Input string was not in a correct format.
Mar 06 07:03:42 docker-jackett[6598]:   at System.Number.ParseSingle (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt) [0x00085] in <a6f810169ec746eeb2789b925e2858c0>:0
Mar 06 07:03:42 docker-jackett[6598]:   at System.Single.Parse (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) [0x00000] in <a6f810169ec746eeb2789b925e2858c0>:0
Mar 06 07:03:42 docker-jackett[6598]:   at System.Single.Parse (System.String s, System.Globalization.NumberStyles style, System.IFormatProvider provider) [0x0000e] in <a6f810169ec746eeb2789b925e2858c0>:0
Mar 06 07:03:42 docker-jackett[6598]:   at Jackett.Utils.ParseUtil.CoerceFloat (System.String str) [0x00010] in <594e817a3cf9452f8e1f75df9b6a2bd4>:0
Mar 06 07:03:42 docker-jackett[6598]:   at Jackett.Models.ReleaseInfo.GetBytes (System.String str) [0x0004c] in <594e817a3cf9452f8e1f75df9b6a2bd4>:0
Mar 06 07:03:42 docker-jackett[6598]:   at Jackett.Indexers.LostFilm+<FollowTrackerRedirection>d__24.MoveNext () [0x00372] in <594e817a3cf9452f8e1f75df9b6a2bd4>:0
```
</details>

&nbsp;
Clearly, the webpage layout on Lostfilm.tv has changed once again.
Using Jackett Version 0.8.737.0 via Docker container by LinuxServer.

**Comment by i3laze** [comment]
Unfortunately, Sonarr doesn't have Indexer - Parser Leniency setting, like Radarr does.

This way it tries to match Homeland and Magicians with year in title and fails. I guess, a workaround from Jackett LostFilm parser is required.

**Comment by i3laze** [comment]
Seems, somebody merged a fix, great!

**Comment by i3laze** [comment]
Searching “X-Files” is crashing Jackett, you’d better investigate:
`2018-03-12 07:31:09.4153 Error Error on 20180312073109 for LostFilm.tv.txtSystem.ArgumentException: Accessed JArray values with invalid key value: "data". Int32 array index expected.
   в Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   в Jackett.Indexers.LostFilm.<PerformSearch>d__19.MoveNext()




[] 
2018-03-12 07:31:09.4213 Error Jackett.IndexerException: Exception (lostfilm): Accessed JArray values with invalid key value: "data". Int32 array index expected. ---> System.Exception: Parse error ---> System.ArgumentException: Accessed JArray values with invalid key value: "data". Int32 array index expected.
   в Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   в Jackett.Indexers.LostFilm.<PerformSearch>d__19.MoveNext()
   --- Конец трассировки внутреннего стека исключений ---
   в Jackett.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex)
   в Jackett.Indexers.LostFilm.<PerformSearch>d__19.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Jackett.Indexers.LostFilm.<PerformQuery>d__17.MoveNext()`

**Comment by i3laze** [comment]
Got an error which breaksauto import:
The.X-Files.S11E09.1080p.rus.LostFilm.TV.mkv
**File quality does not match quality of the grabbed release**


From Sonarr forum:
> Your indexer is altering the release name so Sonarr doesn’t know what it’s actually grabbing, it should be using the actual torrent name or at least including the same information about the source in the title. The indexer should correct this issue if Sonarr is going to be of use, since as you’re seeing it won’t import it automatically.

**Comment by i3laze** [comment]
`Found 3 releases from LostFilm.tv for: Lost in Space 2018 S01E01`
Got “Release Rejected, Unknown Series”
Title:
Lost in Space - S1E1 - Impact - rus 1080p WEBDL (LostFilm)

Please fix this parser (till I have to dive in myself).

**Comment by i3laze** [comment]
Currently I got these bunch of errors:
The Handmaid's Tale - not found
HomeLand - quality not defined, manual import required
Lost in Space - not found
And so on...

Looks like episode numbering and naming has changed and parser is outdated.

**Comment by edalex86** [comment]
From manual search in Jackett Homeland is not found for me too.

**Comment by i3laze** [comment]
P.S. HomeLand releases on LostFilm are blacklisted in for Russian IPs (like  Game of Thrones).
(I personally use Jackett with Tor socks5 proxy.) use a proxy and search results would be there.

**Comment by edalex86** [comment]
I don't believe it's the issue. Parsing error in logs:

> 

Apr 28, 2018 12:41:14 AM | Info | Manual search for "homeland" on lostfilm with 0 results.
-- | -- | --
Apr 28, 2018 12:41:14 AM | Error | lostfilm: Error while parsing row '<tr> 					<td class="placeholder"></td> 					<td class="alpha"> 						<div class="haveseen-btn" title="Пометить серию как просмотренную" onclick="markEpisodeAsWatched(this);" data-episode="161001001" data-season="161001999" data-code="161-1-1"></div> 					</td> 					<td class="beta" onclick="goTo('/series/Homeland/season_1/episode_1/',false)" title="Перейти к серии">1 сезон 1 серия</td> 					<td class="gamma" onclick="goTo('/series/Homeland/season_1/episode_1/',false)" title="Перейти к серии"> 						 						<div> 						Пилот<br> 						<span class="gray-color2 small-text">Pilot</span> 						</div> 					</td> 					<td class="delta" onclick="goTo('/series/Homeland/season_1/episode_1/',false)" title="Перейти к серии">Ru: 05.11.2011<br><span class="gray-color2 small-text">Eng: 02.10.2011</span></td> 					<td class="epsilon" onclick="goTo('/series/Homeland/season_1/episode_1/comments/',false)" title="Перейти к обсуждению серии"> 						<div class="comment-blue-box"> 							<div class="tail"></div> 							593 						</div> 					</td> 					<td class="epsilon" onclick="goTo('/series/Homeland/season_1/episode_1/',false)" title="Оценка серии пользователями Lostfilm.TV"> 						<div class="mark-green-box">9</div> 					</td> 					<td class="zeta"> 						<div class="external-btn2" title="" onclick="copyrightedEpisode()"></div> 					</td> 					<td class="placeholder"></td> 				</tr>':  System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.    в Jackett.Common.Indexers.LostFilm.TrackerUrlDetails..ctor(IElement button)    в Jackett.Common.Indexers.LostFilm.<FetchSeriesReleases>d__25.MoveNext()
Apr 28, 2018 12:41:14 AM | Error | lostfilm: Error while parsing row '<tr> 					<td class="placeholder"></td> 					<td class="alpha"> 						<div class="haveseen-btn" title="Пометить серию как просмотренную" onclick="markEpisodeAsWatched(this);" data-episode="161001002" data-season="161001999" data-code="161-1-2"></div> 					</td> 					<td class="beta" onclick="goTo('/series/Homeland/season_1/episode_2/',false)" title="Перейти к серии">1 сезон 2 серия</td> 					<td class="gamma" onclick="goTo('/series/Homeland/season_1/episode_2/',false)" title="Перейти к серии"> 						 						<div> 						Благодать<br> 						<span class="gray-color2 small-text">Grace</span> 						</div> 					</td> 					<td class="delta" onclick="goTo('/series/Homeland/season_1/episode_2/',false)" title="Перейти к серии">Ru: 07.11.2011<br><span class="gray-color2 small-text">Eng: 09.10.2011</span></td> 					<td class="epsilon" onclick="goTo('/series/Homeland/season_1/episode_2/comments/',false)" title="Перейти к обсуждению серии"> 						<div class="comment-blue-box"> 							<div class="tail"></div> 							214 						</div> 					</td> 					<td class="epsilon" onclick="goTo('/series/Homeland/season_1/episode_2/',false)" title="Оценка серии пользователями Lostfilm.TV"> 						<div class="mark-green-box">9.2</div> 					</td> 					<td class="zeta"> 						<div class="external-btn2" title="" onclick="copyrightedEpisode()"></div> 					</td> 					<td class="placeholder"></td> 				</tr>':  System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.    в Jackett.Common.Indexers.LostFilm.TrackerUrlDetails..ctor(IElement button)    в Jackett.Common.Indexers.LostFilm.<FetchSeriesReleases>d__25.MoveNext()
Apr 28, 2018 12:41:14 AM | Error | lostfilm: Error while parsing row '<tr> 					<td class="placeholder"></td> 					<td class="alpha"> 						<div class="haveseen-btn" title="Пометить серию как просмотренную" onclick="markEpisodeAsWatched(this);" data-episode="161001003" data-season="161001999" data-code="161-1-3"></div> 					</td> 					<td class="beta" onclick="goTo('/series/Homeland/season_1/episode_3/',false)" title="Перейти к серии">1 сезон 3 серия</td> 					<td class="gamma" onclick="goTo('/series/Homeland/season_1/episode_3/',false)" title="Перейти к серии"> 						 						<div> 						С чистого листа<br> 						<span class="gray-color2 small-text">Clean Skin</span> 						</div> 					</td> 					<td class="delta" onclick="goTo('/series/Homeland/season_1/episode_3/',false)" title="Перейти к серии">Ru: 14.11.2011<br><span class="gray-color2 small-text">Eng: 16.10.2011</span></td> 					<td class="epsilon" onclick="goTo('/series/Homeland/season_1/episode_3/comments/',false)" title="Перейти к обсуждению серии"> 						<div class="comment-blue-box"> 							<div class="tail"></div> 							131 						</div> 					</td> 					<td class="epsilon" onclick="goTo('/series/Homeland/season_1/episode_3/',false)" title="Оценка серии пользователями Lostfilm.TV"> 						<div class="mark-green-box">9.3</div> 					</td> 					<td class="zeta"> 						<div class="external-btn2" title="" onclick="copyrightedEpisode()"></div> 					</td> 					<td class="placeholder"></td> 				</tr>':  System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.    в Jackett.Common.Indexers.LostFilm.TrackerUrlDetails..ctor(IElement button)    в Jackett.Common.Indexers.LostFilm.<FetchSeriesReleases>d__25.MoveNext()

>

**Comment by i3laze** [comment]
I remind that the current issue is:
LostFilm returns search results in the format that does not match with Sonarr’s engine.

**Comment by dmnrmr** [comment]
Basically Sonarr think it is downloading `WEBDL-1080p` but after download it's `HDTV-1080p`. Can't really do much since it's a problem of file naming.

**Comment by garfield69** [comment]
jackett 0.12.1623

**Comment by krin-san** [comment]
With the above-mentioned release I tried to improve search "engine" a bit, making `The Magicians (2015)` query work fine while maintaining a feature of searching for Specials. [More on that here...](https://github.com/krin-san/Jackett/blob/eaf39863013c4b0e60a91b762d3cdb39131a925d/src/Jackett.Common/Indexers/LostFilm.cs#L254)
I have also tried searching for other series you mentioned but I get results without issues. If there's smth still not working after update, please provide as comprehensive details as possible so I can reproduce and fix it.

**Comment by gelato** [comment]
Could you please dive into this issue one more time? Torrents from lostfilm.tv can't be imported right now - Sonarr thinks it is downloading WEBDL-1080p but after download it thinks the file is HDTV-1080p.

**Comment by garfield69** [comment]
@gelato  Please provide a screencapture of the Sonarr episode search results page that you believe is in error so we have some reference for investigation. Point out the row that has HDTV-1080p that you believe should read WEBDL-1080p. Thanks.

**Comment by gelato** [comment]
@garfield69 Thanks for your response.
I got screenshots for import history - episode is grabbed as WEBDL-1080p, but at import time it is detected as HDTV-1080p
<img width="1192" alt="import_history" src="https://user-images.githubusercontent.com/1236528/81993269-0690f480-964e-11ea-8d07-9e0e125164a2.png">

Then i made screenshots of grab info and import info.
<img width="776" alt="grabbed" src="https://user-images.githubusercontent.com/1236528/81993290-0f81c600-964e-11ea-8757-84ea75c13ae7.png">
<img width="886" alt="imported" src="https://user-images.githubusercontent.com/1236528/81993300-14df1080-964e-11ea-80d4-cdcd35bf2851.png">

Ans the last screenshot is a manual search on that episode.
<img width="1240" alt="manual_search" src="https://user-images.githubusercontent.com/1236528/81993316-19a3c480-964e-11ea-980f-161d6c75950e.png">

**Comment by garfield69** [comment]
I do not know what the situation was with the web site at the time you did your search but right now, lostfilm reports
![image](https://user-images.githubusercontent.com/6933240/81996788-15a19200-96a2-11ea-96a8-9768e7c9e02e.png)
as you can see, all the versions of that episode are WEB-DLRip and there is only 1 of the 1080p listed.
There are no HDTV episodes to be found.
and this matches with what the Jackett indexer returns
![image](https://user-images.githubusercontent.com/6933240/81996927-7fba3700-96a2-11ea-9138-778b943d6a88.png)
So as far as I can tell, all is working as expected.
It would appear that at the time you did your search may well have been a HDTV entry but it has since been removed from the web site.
