### ISSUE TITLE
[torrentday] Exception (torrentday): Login failed, please reconfigure the tracker to update the cookies: Login failed, please reconfigure the tracker to update the cookies (Test)

### ISSUE THREAD

**Issue by lordradon** [Jackett/Jackett#2637]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
**Jackett version: ??**
**Mono version: ??** (if not using Windows)
have you updated the definition with the latest cookies after your manual login attempt through your chrome browser?

**Comment by garfield69** [comment]
no reply, closing.
