### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): An existing connection was forcibly closed by the remote host: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by orbitingful** [Jackett/Jackett#2642]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Log when I try testing pirate bay indexer. Same thing happens with EZTV indexer and KAT indexer. How do I fix, really want to use pirate bay with sonarr. Thanks.

When | Level | Message
-- | -- | --
Feb 27, 2018 11:24:44 PM | Error | {0}

**Jackett version**:  
**Mono version** (if not using Windows):  
0.8.716.0
-------------------------------

**Comment by garfield69** [comment]
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.

**Comment by aristosv** [comment]
I have the same issue. How can I provide the full enhanced log file?

**Comment by aristosv** [comment]
Actually it seems to be a problem with piratebay. This is the message I get when visiting thepiratebay.org

This page (https://thepiratebay.org/) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version.

**Comment by garfield69** [comment]
Yes. TPB site is not available via https at the moment.
use https://pirates-forum.org/misc.php?page=tpbstatus to check on the status of TPB, service will be restored with there are green dots across the row.
in the mean time you just have to wait.

**Comment by garfield69** [comment]
TPB is online again.
