### ISSUE TITLE
Problem with Webinterface, no idea what's wrong

### ISSUE THREAD

**Issue by trohnjavolta** [Jackett/Jackett#2644]
**OS**: Armbian (debian jessie variant for arm boards)
**Hardware**: Odroid HC2
**Jackett version**:  latest
**Mono version** :  mono-complete v. 5.8.0.127

-------------------------------

Mono and Jackett seem to install just fine, I cannot spot any errors during the process. However I end up with a webinterface looking like this:
https://user-images.githubusercontent.com/35167895/36749540-5b03f730-1bfb-11e8-8abc-657bc9296196.JPG

It's not responsive, selecting any field doesn't do anything.
I tried clearing the browser cache, which didn't work.
I can provide a log later when I'm at home.

**Comment by kaso17** [comment]
please check the network tab of your browser debugger (F12) and start jackett with the -l option and check the logs for errors.

**Comment by garfield69** [comment]
@trohnjavolta  your screen capture looks similar to what you would see if javascript had been disabled. 

Check on the right had side of the browser address box for a 
![image](https://user-images.githubusercontent.com/6933240/36808943-6bc3b0a2-1d2b-11e8-81a2-d568e7082937.png) `javascript was blocked` icon.

if present then click on it and select `always allow javascript on http://127.0.0.1:9117` and then the `Done` button
![image](https://user-images.githubusercontent.com/6933240/36809071-c315c64c-1d2b-11e8-86ae-8319c7728938.png)

**Comment by trohnjavolta** [comment]
JavaScripts are allowed.

I now startet Jackett in konsole and accessed the webif. Now I see Jackett stopped working. Last line is this:

```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
  at System.Net.Http.Formatting.XmlMediaTypeFormatter.GetCachedSerializer (System.Type type, System.Boolean throwOnError) [0x00000] in <5a7138b0edb648f4983f51f6123e20e5>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
  at System.Net.Http.Formatting.XmlMediaTypeFormatter.GetCachedSerializer (System.Type type, System.Boolean throwOnError) [0x00000] in <5a7138b0edb648f4983f51f6123e20e5>:0
```

And trying a second time I get this:

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

**Comment by trohnjavolta** [comment]
After starting it a 3rd time it now works....Idk why. Maybe it's because I previously tried to restore a backup.
