### ISSUE TITLE
[eztv] Exception (eztv): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 202.136.99.181:443: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by sandykervink** [Jackett/Jackett#2646]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
working fine for me, looks like your server can't connect tot the eztv server.
