### ISSUE TITLE
[yggtorrent] Login failed: Selector

### ISSUE THREAD

**Issue by AizeLeOuf** [Jackett/Jackett#2647]
An error occured while updating this indexer
Login failed: Selector "a[href$="user/logout"]" didn't match

-------------------------------

**Comment by kaso17** [comment]
works fine for me.
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by garfield69** [comment]
works for me on my win7 Jackett 0.8.735
try logging in to yggtorrent directly via your browser. look for any alerts you may have outstanding on your account. yggtorrent often enforce password changes for example.

**Comment by alxlaxv** [comment]
Please check https://github.com/Jackett/Jackett/issues/2709
