### ISSUE TITLE
[AlphaRatio] Add Season Categories or custom category mappings

### ISSUE THREAD

**Issue by Kithros** [Jackett/Jackett#265]
So it looks like the way to add categories to a tracker is to add the mapping in the code and recompile. I would like to have the Alpharatio include the season categories when seaching as they divide season packs and single episodes in to different categories.

Looks like they are filter[4] and filter[5] 

![image](https://cloud.githubusercontent.com/assets/1827060/13696548/14a298e8-e735-11e5-81e4-40c36da5fd8e.png)

it would be awesome if we can have some way of adding custom category mappings on the fly. (without recompiling the code)

**Comment by flightlevel** [comment]
Don't have access to AlphaRatio, but this is very easy for you to do.

Have a look here https://github.com/Jackett/Jackett/blob/master/src/Jackett/Indexers/AlphaRatio.cs#L41 and that is the categories Jackett already knows about.

Hover your mouse over the categories on the Alpharatio website and you will see the category number in the url.

Now match it against the options from here https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#3-prepare-the-category-mapping just like the others in the first link

**Comment by Kithros** [comment]
The hurdle for me doing it myself is not the code or the figuring out how to edit it, or what categories. Its actually the compiling part.

I am a linux user so the only way i can see to get it compiled is via mono compiler, Not sure how that works, or if its compatible with C#. I guess i could play with that.

I think this is one of those ease of use things that would increase adoption. Eventually it could be made to add trackers completely without recompile or code changes. but for right now i am just asking for a way in the ui to add/change category mappings.

**Comment by flightlevel** [comment]
@Kithros Just paste the categories in this issue and I will add them for you.eg. https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#3-prepare-the-category-mapping

The next major version of Jackett will be built on .NET Core which will allow you to use Visual Studio Code that runs on linux.

In terms of adding new trackers without code, it would be great if we could have a template and then everything is just based on that, but its just not that easy to scrape a lot of trackers. eg. captchas, cookies, apis, tables, paging etc

**Comment by Kithros** [comment]
Ok ill get that in tonight, I understand that scrapping the sites is not practical, but for existing trackers that you know how to do, having the option to add new mappings on the fly would be ideal. 

Thanks much, Mappings incoming.

**Comment by liquidox** [comment]
Just discovered today that the TvDVDRip from Alpha is missing in Jackett. This category actually contains the BluRay quality rips of TV shows, so it's quite important!

Any way this could be added, or should I figure out how to recompile this stuff myself (not done that before).

**Comment by armani316** [comment]
@liquidox TVDVDRip is working fine for me through Jackett

**Comment by flightlevel** [comment]
This issue hasn't had activity for a while. If the issue still exists, please reopen and include full logs. https://github.com/Jackett/Jackett#troubleshooting

**Comment by Qdhcjv** [comment]
Jackett still does not support the TV Pack categories from AlphaRatio. I don't think log files are relevant since the category simply isn't an option at this time. If I search AR from Jackett it can find season pack torrents but these results are not available in software like Sonarr since no category number is provided.

**Comment by kaso17** [comment]
Looks like gazelle, potentially it can be migrated to the generic gazelle indexer.
Will have to check later.
Categories are definitely incomplete.

**Comment by jimrubenstein** [comment]
Any info here? I Jackett doesn't seem to be able to handle the `season` or `ep` query params as they come from Sonarr. If I drop those from the the query-string that sonarr sends over to jackett, jackett will return results.

Maybe I'm barking up the wrong tree here - lmk if that's true.

**Comment by kaso17** [comment]
migrated to gazelle and updated categories via 804c771cbece41bb2707d3f7cc0fcf2e8d31ec21
