### ISSUE TITLE
mono 5.10 jackett wont start ubuntu

### ISSUE THREAD

**Issue by Nukem51** [Jackett/Jackett#2652]
I recently ran an update on my ubuntu 16 os and it happened to pickup mono 5.10 which broke three applications sonarr radarr and jackett. not i have the first to working again as the sonarr team released a fix tha corrected both of those applications 
fix here https://forums.sonarr.tv/t/mono-5-10-update-broke-sonarr/17800
however i cant seem to find a fix for jackett.

here is the output of the service status-
 
jackett.service - LSB: starts instance of Jackett
   Loaded: loaded (/etc/init.d/jackett; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-02-28 20:18:23 MST; 4s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 3572 ExecStop=/etc/init.d/jackett stop (code=exited, status=1/FAILURE)
  Process: 3495 ExecStart=/etc/init.d/jackett start (code=exited, status=0/SUCCESS)

Feb 28 20:18:02 Jupiter systemd[1]: Started LSB: starts instance of Jackett.
Feb 28 20:18:23 Jupiter systemd[1]: Stopping LSB: starts instance of Jackett...
Feb 28 20:18:23 Jupiter jackett[3572]: Removing stale /var/run/jackett/jackett.pid
Feb 28 20:18:23 Jupiter jackett[3572]: Stopping Jackett
Feb 28 20:18:23 Jupiter jackett[3572]: No process in pidfile '/var/run/jackett/jackett.pid' found running; none
Feb 28 20:18:23 Jupiter systemd[1]: jackett.service: Control process exited, code=exited status=1
Feb 28 20:18:23 Jupiter systemd[1]: Stopped LSB: starts instance of Jackett.
Feb 28 20:18:23 Jupiter systemd[1]: jackett.service: Unit entered failed state.
Feb 28 20:18:23 Jupiter systemd[1]: jackett.service: Failed with result 'exit-code'.
Feb 28 20:18:26 Jupiter systemd[1]: Stopped LSB: starts instance of Jackett.

**Comment by garfield69** [comment]
likely related to #2636 
try
```
cd .../Jackett
wget https://download.sonarr.tv/hotfixes/regression-mono-5.10/NLog.dll.gz
gunzip -f NLog.dll.gz
```

**Comment by Nukem51** [comment]
@garfield69 I must have been real tired last night, could have sworn that file didn't exist in the directory because I "looked" lol. It's there and that did work thank you for helping me see the light.
