### ISSUE TITLE
Jackett "Error Sending the Request" on all trackers.

### ISSUE THREAD

**Issue by maddawg2** [Jackett/Jackett#2653]
So it seems that torrentday no longer works. Been using Jackett for a little over a year, it was working fine. Now when I try to test I get an error that says " Request to Jackett server failed" I thought maybe deleting and adding torrentday back would work but now that I've deleted it I can't add it back.  Clicking the "settings" link in jackett brings me the same error. The log shows "On attempt 3 checking for results from TorrentDay: An error occurred while sending the request".

Jackett version 0.8.716.0

-------------------------------

**Comment by kamos69** [comment]
I've been experiencing the same issue for a few days now. When I re-add the cookie (torrentday.it), it works for a few minutes but then starts failing afterwards.

**Comment by maddawg2** [comment]
I am not even able to re-add the cookie it fails. I tried to remove the tracker with the delete button and re-add it but that too fails :-(... Sadly it's the only private tracker I have so now jackett is not working and therefore neither is Radarr or Sonarr.

Hopefully some others can weigh in on this

**Comment by samsepiol59** [comment]
Could this have to do with the Mono issues that sonarr and radarr are experiencing?

**Comment by kaso17** [comment]
@maddawg2 most likely your jackett isn't running at all (maybe due to the mono issue
