### ISSUE TITLE
Add custom tracker

### ISSUE THREAD

**Issue by darkmac78** [Jackett/Jackett#2656]
Did not used jackett for long time and I might be wrong but I remember that I was able to add a custom tracker.

Was this feature removed ???
Thanks !

**Comment by garfield69** [comment]
simply create an indexer written in yaml and save it in your .../Jackett/Definitions folder.
See existing indexers in that folder for inspiration, and refer to this [wiki](https://github.com/Jackett/Jackett/wiki/Definition-format) for syntax specifics.

**Comment by darkmac78** [comment]
Thanks for fast and clear answer !

**Comment by kaso17** [comment]
@darkmac78 is you write one please contribute them back so everyone can profit from it :)

**Comment by RaymondSchnyder** [comment]
@kaso17 Not everyone is allowed to share the private tracker jackett configs they get from the staff.
