### ISSUE TITLE
RSS Feed Danishbits.

### ISSUE THREAD

**Issue by supremacy2k** [Jackett/Jackett#2657]
Hi.

The provided RSS feed through Jackett to Danishbits, shows the oldest entries first.
When just copying the RSS link, and show it in a browser, it's clear it's showing 6-7 years old content.

I tested on 1337x, DanishBits, Horrible Subs, IPTorrents and Nyaa.si, and only Danishbits are having this issue.

Any way to reverse the feed?
Or is it a tracker specific issue?

Danishbits rss links looks like this:

`https://danishbits.org/rss.php?id=0&auth=xxx&passkey=xxx&authkey=xxx`

**Comment by kaso17** [comment]
jackett is using the coudpotato API, I requested them to fix this via a staff pm but as you know they didn't care very much.
See #2233

**Comment by supremacy2k** [comment]
It's funny though, when checking the RSS feed in a browser the sort order is in the right order.

**Comment by kaso17** [comment]
the couchpoato API is not the same as the RSS API, the RSS API doesn't support searching. That's why we use the couchpotato API.
It probably would be 5 minutes of work to fix their couchpotato API but it looks like they're not very motivated.

**Comment by supremacy2k** [comment]
Would it be possible to implement a separate url for the rss feed?

**Comment by garfield69** [comment]
closed due to #9949
