### ISSUE TITLE
Jackett certificate error on clean macOS install

### ISSUE THREAD

**Issue by ourcore** [Jackett/Jackett#2669]
I just installed Sonarr, which runs fine, but now I'm trying to set up Jackett, which says:
> The mono certificate store is not initialized. Please run the following command as root: curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin

When I try to run the command with or without `sudo`, it says:
> zsh: command not found: cert-sync
> curl: (23) Failed writing body (0 != 2750)

I Googled the error, but found very little. I'm running the Zsh shell. Has anyone else experienced this or does anyone know how to fix the certificate store? Thanks in advance!

Jacket v0.8.737.0
Mono v5.8.0.108

**Comment by ourcore** [comment]
Nevermind–I simply needed to restart my terminal as the `$PATH` had been updated!

**Comment by garfield69** [comment]
have you recycled your jackett service or rebooted your mac?

**Comment by ourcore** [comment]
@garfield69 I couldn't find how to restart the service, so I actually just restarted my Mac, however the error message still appears.

**Comment by garfield69** [comment]
I suggest you try the curl command again and don't forget to run it as root.

**Comment by garfield69** [comment]
The service part of jackett i mentioned earlier applies only if you installed jackett as a service, by following the instructions  at https://github.com/Jackett/Jackett#installation-on-macos
```
stop it by running launchctl unload ~/Library/LaunchAgents/org.user.Jackett.plist from Terminal. 
start it again it using launchctl load ~/Library/LaunchAgents/org.user.Jackett.plist
```
If you did not install jackett as a service then this does not apply to you.

***
I don't think your import is working, from your log:
```
Could not import OU=GlobalSign Root CA - R2, O=GlobalSign, CN=GlobalSign
System.UnauthorizedAccessException: Access to the path "/usr/share/.mono" is denied.
```
which implies that you still have not established root access completely

Try the following:
```
sudo curl -sS https://curl.haxx.se/ca/cacert.pem | sudo cert-sync /dev/stdin
```
then check the log to see if those *access ... denied* messages are gone.
Restart the mac or the Jackett service, whichever applies.

**Comment by ourcore** [comment]
@garfield69 Yes, I installed Jackett as a service. I re-ran the command with `sudo` on both parts, but the _access ... denied_ messages are still there. I restarted the service after using the commands you mentioned above. I usually run commands as root without any issues. Thanks for your help.

**Comment by garfield69** [comment]
an alternate to the double sudo in that command, is to use the `sudo -s` command first, to set the terminal shell into root mode, then do the import without any sudo prefixes (since they should not be necessary).

**Comment by garfield69** [comment]
@kaso17  I could use your expertise with this issue, I do not understand why a root shelled import would get access denied ... have you come across this before?

**Comment by ourcore** [comment]
I ended up running the non-root version (`curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`), which didn't return any _access ... denied_ messages and cleared the message in Jackett's interface.

I'd still really like to know why the `sudo` version didn't work. Are there any limitation to running it as the user only? Thanks again.

**Comment by kaso17** [comment]
@ourcore and @garfield69  it's a macos limitation. For macos only the --user version will work.
Update the notice accordingly via a2185bf957c967880c5e79fe727b9510c0beb045
