### ISSUE TITLE
Request: add hdtime.org definition (torrent)

### ISSUE THREAD

**Issue by k1n6b0b** [Jackett/Jackett#2670]
Referencing the yaml documentation and examples my skills are unfortunately not sufficient to create a valid definition for hdtime.org - anybody willing would be awesome

site: hdtimeorg
name: HDTime
description: "Time to Forever!"
language: zh
type: private 
encoding: UTF-8
links:
- https://hdtime.org/

**Comment by garfield69** [comment]
registration currently closed. invite required.

**Comment by garfield69** [comment]
If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by garfield69** [comment]
implemented with #7015 on 25th Jan 2020.
