### ISSUE TITLE
[yggtorrent] Access to the path

### ISSUE THREAD

**Issue by darkcattz** [Jackett/Jackett#2671]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.737.0 on Synology
**Mono version** (if not using Windows):  5.8.0.108-11

-------------------------------

 An error occured while updating this indexer
Access to the path "/usr/local/jackett/var/.config/Jackett/Indexers/yggtorrent.json.981a9c0ae6d64ece820f853bcfa90555.tmp" is denied.

**Comment by kaso17** [comment]
please post the output of the commands `sudo ps aux` and `sudo stat /usr/local/jackett/var/.config/Jackett/Indexers`

**Comment by kaso17** [comment]
closing, no reply
