### ISSUE TITLE
[yggtorrent] An error occurred while sending the request: Error: NameResolutionFailure (Config)

### ISSUE THREAD

**Issue by yao89** [Jackett/Jackett#2673]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.490-6
**Mono version** (if not using Windows):  5.8.0.108-11

-------------------------------

Hi all, just give another try to Jackett for Ygg (with Sonarr), relaunch it, try to connect to Ygg with new password, and got this..
I tried to restart it, change URL (https://yggtorrent.com) but got this every time..

Thanks ;)

**Comment by garfield69** [comment]
oh wait, you really need to update your jackett from 0.8.490 to a version more current. domain change to yggtorrent was with 0.8.514 but you might as well get the latest version.

**Comment by adrienlabigne** [comment]
0.8.490 is the latest version on Synology repo. Maybe push the new one to it ?
Thanks ;)

**Comment by yao89** [comment]
0.8.490 is the latest version on Synology repo. Maybe push the new one to
it ?
Thanks ;)

And removing & adding again is tested, but not working :’(

-- 

*Adrien Labigne*

Numéro : +32 496 21 45 42

Site internet : yao-nas.myds.me

Le 6 mars 2018 à 04:25:51, garfield69 (notifications@github.com) a écrit:

oh wait, you really need to update your jackett from 0.8.490 to a version
more current. domain change to yggtorrent was with 0.8.514 but you might as
well get the latest version.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Jackett/Jackett/issues/2673#issuecomment-370649870>,
or mute
the thread

**Comment by kaso17** [comment]
use the build in update mechanism to update to the latest version (don't use the syno package center) and check the footer of the jackett website to see your actual version

**Comment by adrienlabigne** [comment]
Great, that was that !
Thanks a lot for your help.

--
Adrien Labigne
Haute Ecole Albert Jacquard - Infographie  
Service Technique - Responsable Audiovisuel et gestionnaire Apple

  

Le 6 mars 2018 à 11:20:50, kaso17 (notifications@github.com) a écrit:

use the build in update mechanism to update to the latest version (don't use the syno package center) and check the footer of the jackett website to see your actual version

**Comment by yao89** [comment]
Great, that was that ! Thanks a lot for your help.

-- 

*Adrien Labigne*

Numéro : +32 496 21 45 42

Site internet : yao-nas.myds.me

Le 6 mars 2018 à 11:20:47, kaso17 (notifications@github.com) a écrit:

use the build in update mechanism to update to the latest version (don't
use the syno package center) and check the footer of the jackett website to
see your actual version

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Jackett/Jackett/issues/2673#issuecomment-370734027>,
or mute
the thread
