### ISSUE TITLE
[torrentday] Your cookie did not work: Login failed, please reconfigure the tracker to update the cookies (Config)

### ISSUE THREAD

**Issue by gers1978** [Jackett/Jackett#2674]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:   0.8.743.0
**Mono version** (if not using Windows):  5.1.4.6 on OS X 10.13.3

-------------------------------

**Comment by garfield69** [comment]
have you updated the definition with the latest cookies after your manual login attempt through your chrome browser?

**Comment by gers1978** [comment]
Yes, I have

**Comment by garfield69** [comment]
@kaso17 I don't know where we are at with the torrentday cookie issue... 
Do you think that upgrading this OP's mono from 5.1.4.6 to the latest would help or should we ask for a complete enhanced log?

**Comment by kaso17** [comment]
@gers1978 
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

I doubt a mono update will change this.
Most likely it's really caused by a bad cookie.
The cookie string should look like this:
`__cfduid=asdjft7asdjhf78as6d786asd785667asdfasd; uid=1234567; pass=123456789012345678901234567890`

**Comment by gers1978** [comment]
Log attached.

[Log.txt](https://github.com/Jackett/Jackett/files/1794980/Log.txt)

**Comment by kimchibreath** [comment]
kaso17 helped me solve this issue, they're right about the full cookie string. I updated to the latest Jackett (v 0.8.745.0 as of this typing) before I did this.

Delete the TorrentDay entry in Jackett and re-add it. When you inspect the TorrentDay page, go to Network, then you'll see 'XHR', 'JS', 'CSS', 'Img', etc -- go to Documents, hit F5 to reload the page and you'll see 3 documents show up in the list: 't', 'lyrics_add.php?TD' and 'lyrics_add.php?TD2'

Either 'lyrics_add.php' document will have the first part of the cookie string, '__cfduid=' the entire cookie string should look like kaso17 posted, but with obviously different values.

Hope that helps.

**Comment by kaso17** [comment]
@gers1978 the cookie from the log looks wrong, it has a pwd instead of pass value, there are spaces at the wrong place+missing.
The "__cfduid" part of the cookie actually can be ignored, only the uid and pass part are required.

**Comment by kimchibreath** [comment]
I tried using only the uid & pass part and it wouldn't work -- it's working now so I have no complaints!

**Comment by gers1978** [comment]
I've tried uid=1111111;pwd=47329843829yfghjkghsk (where uid and pwd come from the Cookie folder under the Storage tab on the Safari Web Inspector)

**Comment by kaso17** [comment]
a space is missing after the ;
ideally use the network tab/requests headers for the correct cookie string.

**Comment by gers1978** [comment]
If I put a space after ; I get the following error:

[d6eb72d] Cookie is not correctly formatted

Also, my network tab doesn't show cookies and I don't have a requests tab (using Safari on OS X)

**Comment by kaso17** [comment]
Where are you getting this error exactly?

**Comment by gers1978** [comment]
In the Medusa logs, as soon as I try to search for any show/episode with TorrentDay set up as a search provider

**Comment by gers1978** [comment]
No, it doesn't, it says "An error occured while updating this indexer
Your cookie did not work: Login failed, please reconfigure the tracker to update the cookies"

It gives me a link to raise the issue here, which is how this thread started

**Comment by gers1978** [comment]
I tried getting the cookie from Internet Explorer (was using Safari and Chrome before) and it had it in the format uid=xxxxxxxxxx;pass=xxxxxxxxx and this now works.  So it seems I need to use "pass" and not "pwd"
