### ISSUE TITLE
[yts] Exception (yts): Object reference not set to an instance of an object: Parse error (Test)

### ISSUE THREAD

**Issue by mem-alloc** [Jackett/Jackett#2675]
YTS Tracker fails to work. I tested both through Jackett and through Radarr. It was working fine yesterday. I do have an outdated version of Jackett, but that is due to the incompatibility of the new version with Radarr. Could this be an issue with YTS itself? The site works fine.

**Jackett version**:  8.555
**Mono version** (if not using Windows):  5.8.0.108 (Mac)

**Comment by garfield69** [comment]
yes, this is likely due to your 0.8.555 version of the YTS indexer, which cannot cope when YTS's API retrieves movie records that do not have a torrent defined. This was fixed starting with 0.8.647

**Comment by mem-alloc** [comment]
@garfield69 I was able to download from YTS just fine yesterday with this version, though. It doesn’t really add up.

**Comment by garfield69** [comment]
Sometimes movies get added to yts without a linked torrent. when you do your searches,  if the jackett indexer comes across one of these records it prevent the indexer from completing the search. the fix allows it to handle these records.
I'm using the latest win7 jackett version and I don't have any issues searching with the yts indexer.

if you want to dig deeper then please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.
we can then check if this is the issue that is affecting you, or something else.
