### ISSUE TITLE
[iptorrents]  (Config)

### ISSUE THREAD

**Issue by smoothrunnings** [Jackett/Jackett#2676]
[log.txt](https://github.com/Jackett/Jackett/files/1785763/log.txt)
**Jackett version**:  0.8.743.0
**Mono version** (if not using Windows):  

-------------------------------

After entering my creds for iPTorrents I get an error "an error occurred while updating indexer"

**Comment by kaso17** [comment]
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by smoothrunnings** [comment]
attached

**Comment by kaso17** [comment]
nothing there

**Comment by smoothrunnings** [comment]
Look in my first post!!! (sigh)

**Comment by garfield69** [comment]
the log shows `Invalid username or password.Please try again`
have you tried logging on to [iptorrents](https://iptorrents.com/) directly via the browser to confirm that your username and password are correct?

**Comment by smoothrunnings** [comment]
Did you look at the entire log? I suspect you haven't. I looked at the look, yes I see the first attempt saying incorrect user name and password, but below that are the other attempts. Why am I doing your support work for you? I work for an MSP I shouldn't have to do this.. lol

**Comment by garfield69** [comment]
;-)
the log you provided is the standard log, which only contains the stack trace, which is not much use. 
I spotted the invalid user messages and assumed that was the problem. my bad.
but what we really need is the log in enhanced mode, which will contain debug messages that pre-sequence the stack trace dumps.
You can get additional logging with the command line switches `-t -l` or by enabling *Enhanced logging* via the web interface (followed by clicking on the Apply Server Settings button).
