### ISSUE TITLE
Jackett's mono process gets stuck at max cpu usage 

### ISSUE THREAD

**Issue by halsafar** [Jackett/Jackett#2680]
It seems every few hours Jackett's process starts consuming 400% of my CPU (according to `top`, 4 core machine).

I've setup a cron task to just restart Jackett every few hours to mitigate it.

I setup a process monitor to see how often it happens.  There is no correlation I can find.  Sometimes a day passes with no error.  Sometimes it happens a dozen times in one day.

Sonarr has the same issue.  So I tried running just one or the other for awhile to see if that was the cause.  It did not matter, with only Jackett running it still gets into this weird state.

The log file shows Jackett is doing literally nothing when this happens.  strace shows it is looping on a FUTEX.

Jackett is completely usable when this happens.  The only way to tell is to check `top`.  

**Jackett version**:  Version 0.8.737.0
**Mono version** (if not using Windows):  5.10.0.140

-------------------------------

**Comment by garfield69** [comment]
if you are using a docker image then try adding `--NoUpdates` to your Jackett startup. see #2198
if you are using Jackett through a SOCKS5 proxy then see #2602

**Comment by halsafar** [comment]
I am using it through a SOCKS5 proxy. So #2602 is very likely the issue.  Closing this.
