### ISSUE TITLE
[scenefz] Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by andreimusca** [Jackett/Jackett#2682]
Error is returned when pushing the Test indexer button.

**Jackett version**:  0.8.743.0
**Mono version** (if not using Windows):  
Mono JIT compiler version 5.0.0 (Stable 5.0.0.100/9667aa6 Wed Jul 12 17:00:30 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

-------------------------------

Mar 07, 2018 09:19:33 AM | Error | {0}
-- | -- | --
Mar 07, 2018 09:19:33 AM | Info | Found 0 releases from SceneFZ / u-torrents
Mar 07, 2018 09:19:31 AM | Info | CardigannIndexer (scenefz): Relogin required
Mar 07, 2018 09:19:23 AM | Info | Starting web server at http://*:9117/

**Comment by kaso17** [comment]
Please update to v0.8.745, reconfigure the indexer and repost the log if the error still exists.

**Comment by andreimusca** [comment]
Update to 0.8.745 , still not working but now the error is visible in the logs.  And here it is the stack trace: [https://pastebin.com/Yjihav5f](url)

**Comment by kaso17** [comment]
Please provide a full enhanced log shoing the configuration+test. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by andreimusca** [comment]
Steps to reproduce:
1. Start with no indexer.
2. Add indexer Scene.fz (fill username and password) hit ok
3. Indexer is added
4. Hit Test button next to the indexer , the error occurs.

Reproducibility: all the time

Here it is the full enhanced log file, I hope this is more helpful

[log.txt](https://github.com/Jackett/Jackett/files/1794523/log.txt)

**Comment by andreimusca** [comment]
Hmm...sorry for this , but I was sure I've checked the Enable enhanced logging button. And apparently I did, but it seams that this change is not persisted across service restarts. Every time I restart the Jackett service the enhanced logging is disabled. A bit strange.


Anyway here it is the full log:

[log.txt](https://github.com/Jackett/Jackett/files/1797383/log.txt)

Thanks

**Comment by kaso17** [comment]
Looks like they changed the layout once again:
should be fixed via fb499570aa51226507382538c4b3da99cd8e2796

**Comment by andreimusca** [comment]
Thank you for the quick fix
