### ISSUE TITLE
IPTorrents has change to finding cookies. 

### ISSUE THREAD

**Issue by smoothrunnings** [Jackett/Jackett#2683]
I look at your finding cookies page but doesn't look anything like the Chrome version I am running which is the latest one on Windows 10. All I can see in the code under F12 is the site is got a lot of CloudFair stuff in it. 

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
yes, we should update the screenshots.
You have to change to the Network tab (header row of the developer console) first

**Comment by smoothrunnings** [comment]
No idea how to do that, can you tell me or show me? 

Thanks,

**Comment by smoothrunnings** [comment]
Hi Kaso17,

I was able to get working after downloading the image you have and opening it so I can see everything. The problem now is the group IDs you have aren't correct, when I input category number for the TV H.265 which is something like 1000099 (off the top of my head) sonarr gives me an index error. When I leave the default catergory in place sonarr is able to connect without any issues.

**Comment by smoothrunnings** [comment]
oddly after putting in the number afterwards "100099" it accepted it without any issues.

**Comment by smoothrunnings** [comment]
Can cookies stop working?

The IPTorrent cookie starts with "__" before giving the string info. After about a couple of minutes the cookie stops working until I reconnect and copy and paste it into Jacket again. This time around I removed the "__" for argument sake and Jacket accepted it. Now I have to wait and see if it fails again. 

Any ideas?

**Comment by smoothrunnings** [comment]
Sorry to do this again. 100099 isn't correct # for the category of TV/265, I am sure all of them are wrong. :( 

When I search "any" I see Megusta's releases, he only releases hevc stuff (TV/265) when I switch the the category it comes with no search results.

**Comment by smoothrunnings** [comment]
safe to close this now. I created a new ticket with the problem I am having now which is technically a different issue than this one. 

Thanks.

**Comment by julioferrer** [comment]
I'm having the same issue, the cookie stops working after a while even after removing the underscore.

**Comment by kaso17** [comment]
There should be actually two underscores at the beginning.
The cookie string should look like this:
`__cfduid=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; uid=XXXXXX; pass=XXXXXXXXXXXXXXXXXXXXX`
