### ISSUE TITLE
REQ: Add local DHT indexer (magnetico / dht-bay)

### ISSUE THREAD

**Issue by pimboli** [Jackett/Jackett#2684]
Hello,

is there any possibility to include support for local installed DHT indexers such as:

- https://github.com/FlyersWeb/dhtbay
- http://labs.boramalper.org/magnetico/

Thanks

**Comment by kaso17** [comment]
assuming both have some kind of API it shouldn't be a problem

**Comment by Norin-Radd** [comment]
+1

**Comment by ngosang** [comment]
Magnetico support included in Jackett v0.16.2106
dht-bay does not have an API so it can't be integrated.
