### ISSUE TITLE
AnimeBytes updated CSRF (again)

### ISSUE THREAD

**Issue by aetaric** [Jackett/Jackett#2685]
I had Jackett setup and working for ages, suddenly I was greeted with the following: 

```
An error occured while testing this indexer
Exception (animebytes): CSRF token missing, invalid or expired. Refresh page and try again.: CSRF token missing, invalid or expired. Refresh page and try again.
```

**Jackett version**:  Jackett Version 0.8.745.0
**Mono version** (if not using Windows):  
Mono JIT compiler version 4.8.0 (Stable 4.8.0.524/9d74414 Fri Apr 21 00:52:36 EDT 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

-------------------------------

**Comment by kaso17** [comment]
hit this a couple of days ago too.
Re-configuring the indexer fixed it for me.
Please try that first.

**Comment by kaso17** [comment]
Ok, v0.8.748 contains a potential fix, please try updating/re-testing first before re-configuring.

**Comment by aetaric** [comment]
Confirmed working after reconfiguring.
