### ISSUE TITLE
IPTorrents category 100099 isn't the correct # for TV/265. 

### ISSUE THREAD

**Issue by smoothrunnings** [Jackett/Jackett#2686]
IPTorrents category 100099 isn't the correct # for TV/265. 

When I search "any" I see Megusta's releases, he only releases HEVC H.265 stuff (TV/265) when I switch the the category it comes with no search results. When I check on IPT TV/265 I see the same results and when I search for ANY or just TV using the Jacket search tool I get results but it includes everything else which I want to filter out.

When I search in other groups for things they seem to work. TV/265 is very important because most of my stuff ends up on my Plex server.

**Jackett version**:  0.8.743.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
For me it seems to work fine:
![x265](https://user-images.githubusercontent.com/11887264/37215146-6f2104e2-23b7-11e8-9446-62f5985e92ba.png)

Can you please share a corresponding torznab/search URL which isn't working as expected?

**Comment by smoothrunnings** [comment]
http://127.0.0.1:9117/UI/Dashboard#search=&tracker=iptorrents&category=100099

**Comment by smoothrunnings** [comment]
![image](https://user-images.githubusercontent.com/6445945/37224520-c4619d2e-23a1-11e8-95b2-55d39304b2e6.png)

**Comment by smoothrunnings** [comment]
using Chrome 64.0.3282.186 (official build) (64bit)

**Comment by smoothrunnings** [comment]
Just tried it on Firefox and it again shows me zero results when I search for anything in 100099. I am about to uninstall and reinstall your app again to see if it changes. Will let you know.

**Comment by kaso17** [comment]
Please provide a full enhanced log of your search request.

**Comment by smoothrunnings** [comment]
First log file with 20180310.00008 shows that I am able to find megusta stuff using Any. It shows 50 matches found. 

Second log file is when I change the any to 1000099 (TV/x265) and hit search with the criteral being "megusta" search results is a big zero (0) 

If I log in my IPT account and search megusta only selecting TV/x265 I get a lot of megusta results. Which I am happy to snip and post here. 

Thanks,
[log.txt](https://github.com/Jackett/Jackett/files/1800005/log.txt)
[log.20180310.00008.txt](https://github.com/Jackett/Jackett/files/1800006/log.20180310.00008.txt)

**Comment by smoothrunnings** [comment]
I will save you trouble of requesting a screen shot. 
![image](https://user-images.githubusercontent.com/6445945/37249255-37a18a0e-24b2-11e8-9448-938109591bb6.png)

**Comment by smoothrunnings** [comment]
PS. I uninstalled Jackett and download and installed the latest version (0.8.755.0) before running the test again and posting my two log files.

**Comment by smoothrunnings** [comment]
Here is another copy of the log file with the -i -l and enhanced log option enabled in Jackett. Again, I logged in to the Web portal, enabled enhanced logging, click on the search for IPTorrents, put Megusta in the search field leave the group set to Any. Hit search, got results. Closed the search window. Opened the search window, selected 100099, left search bar empty, click search, got 0 results found. Closed window. Grabbed log and attached here. :)
[log.txt](https://github.com/Jackett/Jackett/files/1800469/log.txt)

**Comment by smoothrunnings** [comment]
Oh I just saw this in the log. 
2018-03-11 10:54:05.3795 Debug WebClient(HttpWebClient).GetString(Url:https://iptorrents.com/t?99=) 

When I mouse over the TV/x265 on IPT it doesn't have an "=" at the end of its t?99 not sure if it's related?

**Comment by smoothrunnings** [comment]
Just removed the indexer from Sonarr, removed it from Jackett, re-created the IPT indexer. Tested it. OK. clicked on the search icon (an magnifier), started at 100101 (Movie/4K) and worked my way up with nothing in the search field and 100099 comes up with zero search results while everything else shows content. Thanks!

**Comment by kaso17** [comment]
ok, found the problem.
Please go to https://iptorrents.com/settings.php and change the "Torrents - Category column" option to "Icons". Wait a minute (cache) and then try again.

Check to enforce this has been added via e3fc4a86a370fd8511b4b132d44dd4bbddc9c97c
