### ISSUE TITLE
Checking for updates?

### ISSUE THREAD

**Issue by smoothrunnings** [Jackett/Jackett#2687]
I am running the Windows version, it shows version 0.8.745.0 is installed, I hit check for updates but nothing happens. When I view the logs it says the following:

Checked for a updated release but none was found. Current: v0.8.749 Latest: v0.8.749

But it says Jackett Version 0.8.745.0 at the bottom of the main screen. 

**Jackett version**:  Unsure at this point...
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
user *Shift F5* to refresh your Jackett Dashboard page and it should show the correct version.

**Comment by ward0** [comment]
permission issue?

**Comment by smoothrunnings** [comment]
Same deal. Even restarted the physical server is lives on and I still the old version number. 

Is there anyway to backup my settings and uninstall and install the latest version? 

Its not a permission issue. I have local admin access, all my other apps such as plex, and uTorrent don't have an problem updating.

**Comment by garfield69** [comment]
sorry, try *Ctrl F5*

**Comment by smoothrunnings** [comment]
Ctrl F5 worked. Thanks
