### ISSUE TITLE
Can the api be used to create/update the admin password and how?

### ISSUE THREAD

**Issue by userdocs** [Jackett/Jackett#2690]
I was looking at this.

https://github.com/Jackett/Jackett/blob/master/src/Jackett/Controllers/ServerConfigurationController.cs

Can this be used to create the admin password on first run?

If yes then how would you format the api url?

**Comment by kaso17** [comment]
yes,

just use the browser debugger to see how the API calls are looking:
example curl request:
`
curl 'http://127.0.0.1:9117/jackett/api/v2.0/server/adminpassword -H 'Content-Type: application/json' -H 'Accept: application/json, text/javascript, */*; q=0.01' --data-binary '"newpassword"' 
`

**Comment by userdocs** [comment]
I think it might also resolve this https://github.com/Jackett/Jackett/issues/2404

Thank you. This set the password when there was none set. I think there is a missing `'` in your example.

I used a URL similar to this example and it worked for me:

~~~
curl 'http://127.0.0.1:PORT/api/v2.0/server/adminpassword' -H 'Content-Type: application/json' -H 'Accept: application/json, text/javascript, */*; q=0.01' --data-binary '"changeme"'
~~~

I have another question if you would not mind regarding perhaps a way to set the password before jackett runs for the first time.

I was looking at this https://github.com/Jackett/Jackett/blob/3e5e48c3a03423c0a3c654997ea1e515ff50ab00/src/Jackett.Common/Utils/StringCipher.cs

1: If i could salt my own password in the same way jackett does could i put it in a  `ServerConfig.json` 
 template then load jackett using this preset password? I want to generate a random password  and salt it. I do not want to use a presalted phrase across all installations. Would this method work to set a random password before Jackett evens loads for the first time? I already use a template installation method for the basics and it works.

2: How would i recreate this password salt in linux/bash? I don't fully understand how you are salting the passwords.

**Comment by kaso17** [comment]
you're right, there was a ' missing.

The easiest way of doing it before starting is probably to use the csharp interpreter to include the corresponding jackett ProtectionService class and use it to generate the password.

https://github.com/Jackett/Jackett/blob/master/src/Jackett/Services/ProtectionService.cs

Make sure you do it as the same user as jackett will use later (mono keystore is stored in ~/.config/mono)

**Comment by userdocs** [comment]
Thanks for the reply. I'll try to figure it out and i'll add a working linux solution here if i manage to actually get it working.
