### ISSUE TITLE
Jackett search interval -- missing torrents older then 30 days on certain trackers?

### ISSUE THREAD

**Issue by gurabli** [Jackett/Jackett#27]
Not sure why is this happening: if you search with Jackett's manual search, only episodes that are no older then 30 days are displayed as a result. This happens with RARBG and nCore too (it is easier to check with RARBG as it is an open tracker). 
If you use Pirate Bay, the same search returns all the episodes, even the S01E01.

Try it with for example, Gotham (HD). 

Now if you add Gotham to Sonarr, and do a season two full automatic search, it will grab only Gotham S02 from E04, as it is no more then 30 days old (using RARBG or nCore). When doing a manual search for S02E01, the episode is found and it can be manually added without any problems.

Any limitation of Jackett I'm not aware of, or how can we fix this?
Maybe if you can also check on other private trackers and see the list of results Jackett outpusts. Use only the series name (eg.: Gotham), and see how old torrents are displayed.

**Comment by gurabli** [comment]
Thanks to @flightlevel we have the explanation for the above. 

If a given tracker doesn't have an API (in case of nCore it is unfortunately the case, and I guess with RARBG too), then Jackett can see only the torrents listed on the first page after a search. On nCore by default is it 25 results. If you modify this to higher number (I set it on the highest, 100 results/page) then Jackett will see the first 100 results. In most cases this should be enough, but if not, it depends on the tracker's site how many results/page can it display. 
Wish all the sites had an API...

So issue closed, adjust your tracker accordingly!

**Comment by Inrego** [comment]
This is actually not true. If you look at DanishBits (and I think NextGen too), I implemented paging. Jackett can receive offset from Sonarr and use this for grabbing more than the first page. I have, however not found much consistency for what makes Sonarr ask for the next page, but I have seen it happen I'm pretty sure.

Alternatively, it's possible to just go through several pages in the tracker implementation (you can see example of this in earlier versions of NextGen).

**Comment by gurabli** [comment]
Thanks Inrego for pointing this out. This is important and brings up many new questions:) 

I'm afraid I will not be able to detect this in the code, not to mention implementing to a new tracker (in my case nCore). I will however take a look at it. @flightlevel if you don't mind to look at this several pages search implementation that Inrego mentions?

**Comment by flightlevel** [comment]
Looks like DanishBits has paging implemented but not nCore.
How often do you expect to get more than 100 results?

**Comment by gurabli** [comment]
In case of new series it is not relevant, but for the releases that are not uploaded as season packs, but single episodes (and they come in at least 4-5 different releases), and are running for many season, it is easy to reach 100 torrents/page. I can easily live without this, but if it is something that is easy to add, it would be great to have it. After all, let's make things as perfect as possible.

I'm not sure, but I believe DanishBits has this on lines 153-169? Is it just a matter of adding this to nCore or other parts need complete or partial rewriting?

**Comment by Inrego** [comment]
Sonarr searches for specific episodes, for example season 3 episode 5. The information is available in the query method of the tracker, and should be used when executing search on the tracker, in order to only get relevant results.

**Comment by rarbg** [comment]
Limits in our api are increased in v2.1 of it. However its still in development state.
About your limits - you can always perform multiple searches like everyone does right now to get all results

**Comment by gurabli** [comment]
&rarbg "you can always perform multiple searches" could you please explain this what do you mean by multiple searches?

**Comment by rarbg** [comment]
@gurabli 
Lets say the show you are looking for has 3seasons and 17 episodes each
You can always search for
S01E0
S01E1
S02E0
S02E1
S03E0
S03E1
...
to get all episodes + all seasons

**Comment by gurabli** [comment]
OK, I got it. Well, it is better then nothing:)
I'm unlucky since the site I use doesn't have an API, and I'm very much sure they won't implement it. 
Luckily it is problematic only when I backserach series which have many seasons, something I don't use frequently and can live with this limitation. 

Don't get me wrong, I'm very much satisfied with Jackett, it is an excellent pieces of code and I love it very much! I just want to make full automation to be really full, if possible:)

**Comment by Taloth** [comment]
Sonarr expects pages of 100 items (that's the newznab page size), if the current page contains the full 100 items, then it will (within reason) continue to grab more pages until a page has less than 100 items.
So if a Jackett indexer support paging, it should ensure it returns chunks of 100 items.

Sonarr supports rarbg out of the box, but doesn't have paging, only the first 100 items. That likely causes some issues with season searches.

**Comment by Inrego** [comment]
Thanks for the insight Taloth. I'll make sure to update the trackers I've implemented to return pages of 100. I do believe that there are some parameters that specifies page length (something like offset and count if I remember correctly)?

**Comment by gurabli** [comment]
Thanks Taloth for explanation. 
@Inrego and @flightlevel I looked into this for nCore, but not sure how can I add paging support to the indexer. As always, you help is very much appreciated. Once this is done, I think we will have everything supported at nCore.

**Comment by raspdealer** [comment]
Is that closed @gurabli ?
