### ISSUE TITLE
Jackett keeps crashing randomly

### ISSUE THREAD

**Issue by alexrengel** [Jackett/Jackett#270]
I have Jackett on a Synology from the synocommunity repo. Here's the log from when the error starts happening: [http://pastebin.com/cdaCzq91](http://pastebin.com/cdaCzq91)

It has an admin password, server port is the default, external access is available, It works but it randomly crashes. Any help would be appreciated.

**Comment by flightlevel** [comment]
Have you tried running it via a docker?

**Comment by slamanna212** [comment]
Mine crashed all the time, so i now run it as an upstart script, it crashes a lot less and its eaiser to restart when it does. All i did was copy the script for Sonarr , since they both use mono

file name: /etc/init/jackett.conf

```
author "Simon Tallmyr - Nosscire"
description "Upstart Script to run Sonarr as a service on Ubuntu/Debian based s$

#Set username for the process. Should probably be what you use for logging in
setuid media

env DIR=/opt/Jackett
#This is the install directory. If you installed using a deb package or the Son$

setgid nogroup
start on runlevel [2345]
stop on runlevel [016]

respawn

exec mono --debug $DIR/JackettConsole.exe

author "Simon Tallmyr - Nosscire"
description "Upstart Script to run Sonarr as a service on Ubuntu/Debian based s$

#Set username for the process. Should probably be what you use for logging in
setuid media

env DIR=/opt/Jackett
#This is the install directory. If you installed using a deb package or the Son$

setgid nogroup
start on runlevel [2345]
stop on runlevel [016]

respawn

exec mono --debug $DIR/JackettConsole.exe


```

**Comment by greenbeanz2** [comment]
Try updating your cookie data for iptorrents

**Comment by flightlevel** [comment]
This issue hasn't had activity for a while. If the issue still exists, please reopen and include full logs. https://github.com/Jackett/Jackett#troubleshooting
