### ISSUE TITLE
AnimeTorrents - PerformQuery needs an update

### ISSUE THREAD

**Issue by Zedjaw** [Jackett/Jackett#2700]
Hi guys,
There is an issue with AnimeTorrents search where it would be too specific with the wording, for example,
the "-" needs to be including for it to show any results

The fix for this can be resolved via an update to the code: for instance:

"Before, in PerformQuery

var searchString = query.GetQueryString(); 
var searchUrl = SearchUrl;

After

var searchString = query.GetQueryString(); 
var match = System.Text.RegularExpressions.Regex.Match(searchString, " [0-9]+$").Index; 
if (match != 0) searchString = searchString.Substring(0, match) + " - " + searchString.Substring(match+1).PadLeft(2,'0'); 
var searchUrl = SearchUrl;

For example, this changes "Boku no Hero Academia 13" to "Boku no Hero Academia - 13" or "Boku no Hero Academia 9" to "Boku no Hero Academia - 09"

To be more clear, can we get the AnimeTorrents.cs file update as it is not going to show searches for:
"Boku no Hero Academia 13"
but will show if adding a dash "-"
"Boku no Hero Academia - 13"

**Comment by Zedjaw** [comment]
To be more clear, can we get the AnimeTorrents.cs file update as it is not going to show searches for example:
"Boku no Hero Academia 13"
but will show if adding a dash "-"
"Boku no Hero Academia - 13"

Thank you team

**Comment by kaso17** [comment]
I can't find any results with `Boku no Hero Academia - 13` either.
In general it seems like it's possible to use % as wildcard.
So just replacing all whitespaces with % looks like a better solution.
so the search string would become `Boku%no%Hero%Academia%13`

**Comment by Zedjaw** [comment]
How are you doing the tests? It is a private tracker site, so you’ll need an account.
Is the % method working for you?

**Comment by kaso17** [comment]
Yes, I've an account to test it.
Using episode 11 e.g. this works fine for me:
https://animetorrents.me/torrents.php?cat=0&searchin=filename&search=Boku%25no%25Hero%25Academia%2511

Using your example I don't find anything:
https://animetorrents.me/torrents.php?cat=0&searchin=filename&search=Boku+no+Hero+Academia+-+13

**Comment by Zedjaw** [comment]
Hey Kaso, i am very sorry. I used a horrible example, as Boku no Hero episodes aren't there anymore (they are all batched)

Here's a better example:
https://animetorrents.me/torrents.php?search=Boruto%3A+Naruto+Next+Generations+-+48&SearchSubmit=

**Comment by Zedjaw** [comment]
If the percentage method works for that also, can it be added ASAP. Also, with Baruto: net generations, when added the percentage after Baruto:% it comes up as nothing

**Comment by kaso17** [comment]
212045751835a35813439cc2ac231917ca23bfc9 should fix your problem
