### ISSUE TITLE
[lostfilm] An error occurred while sending the request: Error: NameResolutionFailure (Config)

### ISSUE THREAD

**Issue by AbayefD** [Jackett/Jackett#2702]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
**Jackett version**:  **?**
**Mono version** (if not using Windows):  **?**
are you using docker?

**Comment by AbayefD** [comment]
Yes

11 мар. 2018 г. 21:44 пользователь "garfield69" <notifications@github.com>
написал:

*Jackett version*: *?*
*Mono version* (if not using Windows): *?*
are you using docker?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Jackett/Jackett/issues/2702#issuecomment-372138487>,
or mute
the thread

**Comment by garfield69** [comment]
Previous ticket that showed a NameResolutionFailure error was resolved by upgrading to a version of Jackett of at least version 0.8.737
However users of docker often don't get the latest version in a timely manner from the official docker repo, so it may take some time to fetch a version at, or better than version 0.8.737, the latest official Jackett release being currently v0.8.749 
Check on your Jackett Dashboard at the bottom for the version you are on, and upgrade if you are on an older version as best you can.

**Comment by mikeatdesk** [comment]
I'm running version 0.8.1045.0 on Mac OS and running into the same NameResolutionFailure error.

Any further troubleshooting possible? Seems I'm on the latest version of Jackett (I just installed for the first time).
