### ISSUE TITLE
"an error has occurred" trying to load dashboard on QNAP after latest update

### ISSUE THREAD

**Issue by an303042** [Jackett/Jackett#2704]
running on qnap nas, updated to latest version and now jackett no longer running or loading.
Qmono 5.10.0.140
Jackett 0.8.755

tried reinstalling - same thing.

**Comment by mikkihugo** [comment]
Same issue for me and same versions - also reinstalled.

**Comment by kaso17** [comment]
is v0.8.749 working for you?
Please try running "mono --debug JackettConsolo.exe" from the command line and share the output.

**Comment by FloydKulis** [comment]
Qmono 5.10, with the last Jacket 0.8.755 don`t work.

[~] # mono --debug JackettConsolo.exe
-sh: mono: command not found

Jacket take a lot of memory:
![image](https://user-images.githubusercontent.com/37215675/37281466-69a1bac0-25f1-11e8-98fe-7e1d2ff5d13c.png)

**Comment by an303042** [comment]
yep, rolling back to Qmono 5.4.1.6.0 fixes it.

**Comment by kaso17** [comment]
@FloydKulis please try finding the correct path of the mono binary:
`find / -name mono`
It might be called qmono too:
`find / -name qmono`

**Comment by FloydKulis** [comment]
Hi @kaso17 

sorry about my english. I found somthing like that:

[~] # find / -name mono
/share/CE_CACHEDEV1_DATA/.qpkg/Qmono/bin/mono
/share/CE_CACHEDEV1_DATA/.qpkg/Qmono/etc/mono
/share/CE_CACHEDEV1_DATA/.qpkg/Qmono/include/mono-2.0/mono
/share/CE_CACHEDEV1_DATA/.qpkg/Qmono/lib/mono
/share/CE_CACHEDEV1_DATA/.qpkg/Qmono/share/mono-2.0/mono

And what now? i must go to this folder? command "cd"?

**Comment by kaso17** [comment]
use cd to change to the Jackett directory.
If you don't know it use `find -name JackettConsole.exe`  to find it.
Then execute `/share/CE_CACHEDEV1_DATA/.qpkg/Qmono/bin/mono --debug JackettConsole.exe -t -l`

**Comment by 0xW1sKy** [comment]
I'm having this same issue. 
Is there anything i can contribute to help resolve this?

**Comment by 0xW1sKy** [comment]
Attached results of debug command for mono

[debug-output.txt](https://github.com/Jackett/Jackett/files/1808289/debug-output.txt)

**Comment by kaso17** [comment]
Thank you for the log. Unfortunately the error is originating from the .NET System.Web.Http library which isn't controlled by jackett. And it's a very useless error. Someone with access to the platform will have to debug this step by step to see what exactly is the problem.

**Comment by FloydKulis** [comment]
So, we can only instal old version Qmono, ora wait for new one.

**Comment by kaso17** [comment]
yes, that's probably the easiest option.

**Comment by Jorman** [comment]
Same here, same system ... rolling back too!
Bored of Qnap software, planning to install debian and erease qnap system, lol

**Comment by FloydKulis** [comment]
**Q**mono is unofficial.
Mono from AppCenter is officjonal, but with it dosn`t work.

@Jorman it is true QTS is very bad system.

**Comment by an303042** [comment]
I think [THIS](https://www.cachem.fr/forum-nas/viewtopic.php?f=21&t=1523&sid=638f65d89f59810d09733bd76dd456c4&start=70) is where the author of qmono posts. I tried to register to the forums so I can point him to this thread, but the captcha there is broken and i couldnt register.
Maybe someone else who already has an account there can help...

**Comment by nephaste** [comment]
Hi Kaso.. this Qoolbox...

this look more an issue in Jackett with 5.10.x.x mono version... just update to 5.10.0.160 (Latest stable from mono project)
issue remain the same...

Jackett start and web Ui display 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Message>An error has occurred.</Message>
</Error>

 No error display in logs...

Jackett seems running on background

admin     5101 14.0  0.7 1116040 125732 ?      Sl   12:17   1:21 /opt/Qmono/bin/mono --debug JackettConsole.exe --IgnoreSslErrors true --UseClient libcurl

I will try to update Jackett qpkg to latest...

**Comment by oniric84** [comment]
Exactly same issue for me.

**Comment by oniric84** [comment]
where can we get an older qmono version?

**Comment by nephaste** [comment]
you can get it on QnapClub repo ( you can select version)

**Comment by kaso17** [comment]
@nephaste Thank you for looking into this.
So far we're getting this error report only from qnap/ARM users.
@oniric84 @an303042 @Jorman @FloydKulis @mikkihugo can you please let us know which qnap platform/CPU you're using?
I suspect it's some general mono issue affecting 32 bit ARM systems.
@truckershitch already spend some time on debugging it in #2575 on his armv7h platforms.

This error/exception is not triggered by jackett directly. It's apparently caused by the microsoft/mono http library. Unfortunately the error message is useless making it necessary to debug Jackett/the http library to see what exactly is causing the error.
As I can't reproduce this on my test platforms someone else have to do this.

Starting with v0.8.737 jackett should work perfectly fine with mono 5.10, there was an problem with nlog (see #2636).

**Comment by curnacat** [comment]
I'm a Qnap user with a TS-253A and last firmware version installed, so intel 64 architecture.

Using Qmono 5.10.0.60 and Jackett 0.8.755 doesn't work.  The error I get when connecting to Jackett is:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Message>An error has occurred.</Message>
</Error>

**Comment by Jorman** [comment]
Hi @kaso17 
here mine dettails
```
uname -a
Linux Qnap 3.4.6 #1 SMP Thu Feb 15 01:39:11 CST 2018 x86_64 GNU/Linux
```
Let me know if you need some more extra info

**Comment by oniric84** [comment]
I am a HS-251+ qnap user, therefore running on 64 bits also.

Enviado desde Correo para Windows 10

De: Jorman
Enviado: lunes, 19 de marzo de 2018 20:38
Para: Jackett/Jackett
CC: oniric84; Mention
Asunto: Re: [Jackett/Jackett] "an error has occurred" trying to loaddashboard on QNAP after latest update (#2704)

Hi @kaso17
here mine dettails
uname -a
Linux Qnap 3.4.6 #1 SMP Thu Feb 15 01:39:11 CST 2018 x86_64 GNU/Linux
Let me know if you need some more extra info

**Comment by an303042** [comment]
@kaso17 @nephaste on Qnap ts-453pro so as mentioned above intel x64.
right now I've rolled back to 5.4.1.6.0, but i can reinstall the non working version if you guys need more info.
I will, however, need step by step instructions on how to get you what you need :)

Thank you both for you time, work and effort on putting this whole thing together!

**Comment by kaso17** [comment]
ok, now I have to suspect that it's something qnap build/environment specific triggering this bug.
On plenty of "standard" (Debian/Ubuntu/CentOS/SUSE) linux x86_64 environments jackett is running perfectly fine (using the distribution or official mono packages).
Is it possible to run a docker container or virtual machine on a qnap NAS?
If it is I would suggest testing either this docker container https://hub.docker.com/r/linuxserver/jackett/ or in case of a generic VM install a Debian or ubuntu and use the official mono packages.

**Comment by Jorman** [comment]
On my qnap is not possible, in fact I'm planning to delete qts and install
or pure Debian to be free from this and others problem

Il mar 20 mar 2018, 15:18 kaso17 <notifications@github.com> ha scritto:

**Comment by nephaste** [comment]
Hi Kaso.. in all my plateform .. it refuses to start including arm64, armv7l , armv5, x86_64
Mono was built on the same way from source with --enable-btls and --with-csc=mcs (recommandation from Mono Team github issue on ARM plateform on compilation https://github.com/mono/mono/issues/7382  ), but i dont think it can have an impact, Radarr, Sonarr, Duplicati , Emby and every other Mono project are running fine with it...

**Comment by FloydKulis** [comment]
Yep, i have x64 architecture. Radarr works now. Jackett not.

**Comment by kaso17** [comment]
@nephaste can you please share the build commands you're using? Then I'll try to reproduce this on amd64

**Comment by nephaste** [comment]
standard autogen.sh with prefix

```
PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"  \
CFLAGS="-O2 -I$PREFIX/include" \
CXXFLAGS="-O2 -I$PREFIX/include "     \
LDFLAGS="-L$PREFIX/lib -Wl,-rpath,$PREFIX/lib" \
CPPFLAGS="-O2 -I$PREFIX/include"     \
./autogen.sh --prefix=$PREFIX \
--bindir=$PREFIX/bin \
--sbindir=$PREFIX/bin \
--libexecdir=$PREFIX/libexec \
--libdir=$PREFIX/lib \
--datadir=$PREFIX/share \
--datarootdir=$PREFIX/share \
--sysconfdir=$PREFIX/etc \
--sharedstatedir=$PREFIX/com \
--localstatedir=$PREFIX/var \
--includedir=$PREFIX/include \
--oldincludedir=$PREFIX/include \
--infodir=$PREFIX/share/info \
--localedir=$PREFIX/share/locale \
--with-libiconv-prefix=$PREFIX \
--with-crosspkgdir=$PREFIX/lib/pkgconfig \
--enable-btls \
--with-csc=mcs && make && make install
```

**Comment by Blisk** [comment]
I have the same problem, where I can get older version of qmono?

**Comment by vgabor86** [comment]
I had the same problem, rolling back qmono to 5.4.6.1.0 fixed it. I found the qpkg here https://qnapclub.eu/en/qpkg/193

**Comment by WeirDave** [comment]
TS-653A x86_64 - Having same issue. Please let me know what I can do to help.

Thanks!

**Comment by nephaste** [comment]
Just released 5.12.0.266 mono version on QnapClub Repo.. all is working now .. Jackett is launching

this issue is probably due previous Qmono version was not compiled with Roslyn but build with --with-csc=mcs option (workaround to fix an issue on arm64 mono compilation) .. i am not sure yet , i need to check once i ll compiled the new arm64 mono version

**Comment by Jorman** [comment]
Goog to know! Thank you!

**Comment by WeirDave** [comment]
Works GREAT! Thank you for fixing

**Comment by kaso17** [comment]
Thank you for fixing it. I updated the readme accordingly (2cf3cf15e377c3547acf5df1d6570de8f42e1329).
