### ISSUE TITLE
[PTP] You have exceeded the maximum session soft limit of 10. Once the hard limit is reached, old sessions will be silently logged out. 

### ISSUE THREAD

**Issue by trunet** [Jackett/Jackett#2712]
Most causes of many or run-away sessions are malformed scripts. Scripts should be saving and re-using the session cookies that PTP sets. Not only will this make the scripts operate faster, it'll be less burden on PTPs infrastructure. 
Short lived/one-off scripts should not be setting keeplogged=1 as this will allow a shorter expiry of 30 minutes once the session is no longer in use.

**Comment by trunet** [comment]
Specifically https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/PassThePopcorn.cs#L81 should not be there to expire after 30 minutes.

**Comment by trunet** [comment]
https://github.com/Radarr/Radarr/issues/2626

**Comment by kaso17** [comment]
6ad732cd877d5e6d588e4c2d101af7dcfec73fd9 and 7d1110e86a0aa9545bff4d26a40ebaf35ba6d291 should fix/improve the problem.
Unfortunately I don't have an account to test it myself.
Can you please test it with v0.8.763.
Please let me know if it's still causing problems.

**Comment by trunet** [comment]
updated to pre-release v0.8.763, waiting to see if the problem is fixed, get back to you tomorrow.

**Comment by trunet** [comment]
I can confirm that this fixed the problem. However, the long term solution, would be to implement storing the cookie and reusing the session. I will leave it to you if you want to implement that or close the ticket.

**Comment by kaso17** [comment]
Jackett already stores/reuses the cookies but for some unknown reason the original indexer author decided to do a login on every search request.
With 15ff725ee5dbd7f5f00b573a3f25e3c893930b68 we use keeplogged=1 again, this should result in extra sessions only (and depending on the tracker behavior) when configuring the indexer in jackett.
If someone else with an account wants to fix this too: Adding a proper logout before logging in again should fix that too (for the logout it's probably necessary to grab the authkey from some other page first).

@trunet if you see new unexpected new sessions please let us know.
