### ISSUE TITLE
Jackett.Common.IndexerException: Exception (isohunt2)

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#2715]
Hi, I don't know if this is a problem but on test and on search I see error message from this traker, I attack the log, hope can help to understand

The log:
http://s000.tinyupload.com/index.php?file_id=76459216029526375330

J

**Comment by kaso17** [comment]
If this is still a problem please try removing/re-adding the indexer.

**Comment by Jorman** [comment]
I'll try tnx, for now seems to works, maybe only a temporary problem with the host?

**Comment by kaso17** [comment]
yes, your log indicated a bad gateway error
