### ISSUE TITLE
Enhancement: Parsing of Usent Forums

### ISSUE THREAD

**Issue by inject00r** [Jackett/Jackett#2717]
Would it be possible to integrate usenet forums and make the searches of them parsable?

**Comment by kaso17** [comment]
I've no experience with usenet, but from my understanding there are indexers which provide newznab feeds, so this shouldn't be necessary?

**Comment by flightlevel** [comment]
@inject00r Jackett is designed for torrents, there is plenty of solutions out there for usenet
