### ISSUE TITLE
Trouble updating

### ISSUE THREAD

**Issue by neuman1812** [Jackett/Jackett#2721]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.539
**Mono version** (if not using Windows):  Mono JIT compiler version 5.8.0.108 

-------------------------------
The update seems to be failing,  but not sure how.  My Log shows this after I click the "check for update" button

```
Mar 15 15:17:01 media CRON[974]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Mar 15 15:17:45 media mono[958]: 03-15 15:17:45 Info New release found.  Current: v0.8.539 New: v0.8.763
Mar 15 15:17:53 media mono[958]: 03-15 15:17:53 Info Starting updater: mono /tmp/JackettUpdate-v0.8.763-636567238715454920/Jackett/JackettUpdater.exe --Path "/opt/jackett" --Type "mono" --Args " JackettConsole.exe " --KillPids "958"
Mar 15 15:17:53 media mono[958]: 03-15 15:17:53 Info Updater started process id: 990
Mar 15 15:17:53 media mono[958]: 03-15 15:17:53 Info Exiting Jackett..
Mar 15 15:17:59 media systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
Mar 15 15:17:59 media systemd[1]: Stopped Jackett Daemon.
Mar 15 15:17:59 media systemd[1]: Started Jackett Daemon.
Mar 15 15:18:02 media mono[995]: 03-15 15:18:02 Info App config/log directory: /home/pi/.config/Jackett
Mar 15 15:18:03 media mono[995]: 03-15 15:18:03 Info Starting Jackett 0.8.539.0
Mar 15 15:18:03 media mono[995]: 03-15 15:18:03 Info Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5)
Mar 15 15:18:03 media mono[995]: 03-15 15:18:03 Info OS version: Unix 4.9.61.7
Mar 15 15:18:03 media mono[995]: 03-15 15:18:03 Info ThreadPool MaxThreads: 400 workerThreads, 200 completionPortThreads
Mar 15 15:18:03 media mono[995]: 03-15 15:18:03 Info issue: Raspbian GNU/Linux 9 \n \l
Mar 15 15:18:03 media mono[995]: 03-15 15:18:03 Info mono version: 5.8.0.108 (tarball Fri Jan 19 18:55:10 UTC 2018)
Mar 15 15:18:03 media mono[995]: 03-15 15:18:03 Info TrustedRootCertificates count: 166
Mar 15 15:18:03 media mono[995]: 03-15 15:18:03 Info Using HTTP Client: HttpWebClient
Mar 15 15:18:04 media mono[995]: 03-15 15:18:04 Info Loading Cardigann definitions from: /home/pi/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /opt/jackett/Definitions

```

My jackett install is located in the /opt/jackett directory.

**Comment by kaso17** [comment]
make sure jackett can write to the directory:
`chown -R jackettUser /opt/jackett`

And it looks like you're using systemd in that case you should use the --NoRestart flag.
Please see https://github.com/Jackett/Jackett/wiki/systemd-service for details

**Comment by neuman1812** [comment]
It was just the --norestart I had to add.  My "pi" user starts the service.  

Thanks!
