### ISSUE TITLE
[1337x] Exception (1337x): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /build/mono-5.10.0.160/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by YouCantHaveMyId** [Jackett/Jackett#2723]
Probable duplicate of [Issue 2582](https://github.com/Jackett/Jackett/issues/2582) but I am using mono-5.10.0.160 while they had mono-5.8.0.108.

I'm rocking Jackett Version 0.8.763.0 and Mono version 5.10.0.160

 I have run `sudo wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin` and restarted the Jackett Service afterwards via 
`$ sudo service jackett restart`
and the Pi with 
`$ sudo shutdown -r now`
to no avail.

`$ sudo wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`

> Mono Certificate Store Sync - version 5.10.0.160
> Populate Mono certificate store from a concatenated list of certificates.
> Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.
> 
> --2018-03-16 00:36:37--  https://curl.haxx.se/ca/cacert.pem
> Resolving curl.haxx.se (curl.haxx.se)... 151.101.18.49, 2a04:4e42:4::561
> Connecting to curl.haxx.se (curl.haxx.se)|151.101.18.49|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 215556 (211K) [application/x-pem-file]
> Saving to: ‘STDOUT’
> 
> -                                 100%[===========================================================>] 210.50K  1.28MB/s    in 0.2s
> 
> 2018-03-16 00:36:38 (1.28 MB/s) - written to stdout [215556/215556]
> 
> Importing into legacy system store:
> I already trust 133, your new list has 133
> Import process completed.
> 
> Importing into BTLS system store:
> I already trust 133, your new list has 133
> Import process completed.

As per @kaso17's   response in [Issue 2694](https://github.com/Jackett/Jackett/issues/2694) (modified for 1337x.to) however my response is substantially different to what was recorded in that issue.
` $ curl -v https://1337x.to/`

> *   Trying 213.46.185.10...
> * TCP_NODELAY set
> * Connected to 1337x.to (213.46.185.10) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
> * successfully set certificate verify locations:
> *   CAfile: /etc/ssl/certs/ca-certificates.crt
>   CApath: /etc/ssl/certs
> * TLSv1.2 (OUT), TLS header, Certificate Status (22):
> * TLSv1.2 (OUT), TLS handshake, Client hello (1):
> * TLSv1.2 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (OUT), TLS alert, Server hello (2):
> * SSL certificate problem: self signed certificate
> * Curl_http_done: called premature == 1
> * stopped the pause stream!
> * Closing connection 0
> curl: (60) SSL certificate problem: self signed certificate
> More details here: https://curl.haxx.se/docs/sslcerts.html
> 
> curl performs SSL certificate verification by default, using a "bundle"
>  of Certificate Authority (CA) public keys (CA certs). If the default
>  bundle file isn't adequate, you can specify an alternate file
>  using the --cacert option.
> If this HTTPS server uses a certificate signed by a CA represented in
>  the bundle, the certificate verification probably failed due to a
>  problem with the certificate (it might be expired, or the name might
>  not match the domain name in the URL).
> If you'd like to turn off curl's verification of the certificate, use
>  the -k (or --insecure) option.

**Comment by kaso17** [comment]
`curl: (60) SSL certificate problem: self signed certificate`
your ISP or something else is hijacking your TLS connections.
