### ISSUE TITLE
[cpasbien] Exception (cpasbien): Got redirected to another domain. Try changing the indexer URL to http://cpasbiens1.com/.: Parse error (Test)

### ISSUE THREAD

**Issue by JoeSophia** [Jackett/Jackett#2725]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
domain changed with 8db85b5 , which will be included in the next (pre)release of Jackett, whenever that happens.
In the mean time you can fix this for yourself by using the wrench icon on the Jackett Dashboard to edit the cpabien indexer and changing the Site Link to `http://cpasbiens1.com/`
