### ISSUE TITLE
Torlock doesn't use categories when searching

### ISSUE THREAD

**Issue by Qstick** [Jackett/Jackett#2732]
**Jackett version**:  Latest
**Mono version** (if not using Windows):  NA

https://github.com/Jackett/Jackett/blob/8db85b5abb5977887866e775493b6c89ee70697f/src/Jackett.Common/Definitions/torlock.yml#L34

-------------------------------
Torlock definition should be updated to use categories when sending search request or test request. This results in random test failures in Sonarr/Radarr/Lidarr if a Tv/Movie/Music torrent is not in the main recent feed. 

Should use:

`https://www.torlock2.com/movies.html` if movies categories are passed to jackett
`https://www.torlock2.com/music.html` if music categories are passed
`https://www.torlock2.com/television.html` if TV categories are passed

and then revert back to main feed if no valid category is passed.

**Comment by guntherbob20** [comment]
Not related to Torlock specificly, but I ran into a similar issue with The Pirate Bay indexer and Lidarr. Here is how my indexers were set up and I got one successful test and the other an unsuccessful test:

Right.

This is what I am experiencing:

This configuration would not work: https://i.imgur.com/Jxo9Wa3.png

But this configuration would work: https://i.imgur.com/tDwK9H8.png

This is the RSS feed of TPB with the Category Code 3000: [RSS Feed Fail](http://10.1.1.106:9117/api/v2.0/indexers/thepiratebay/results/torznab/api?apikey=zvcui6dj74hx9nfjaxcpru22ibygdf4v&t=search&cat=3000&q=)

RSS Feed: [3000.txt](https://github.com/Jackett/Jackett/files/1857301/3000.txt)


This is the RSS feed of TPB with the Category Code 3000,2000: [RSS Feed Succeed](http://10.1.1.106:9117/api/v2.0/indexers/thepiratebay/results/torznab/api?apikey=zvcui6dj74hx9nfjaxcpru22ibygdf4v&t=search&cat=3000,2000&q=)

RSS Feed: [3000 and 2000.txt](https://github.com/Jackett/Jackett/files/1857300/3000.and.2000.txt)

**Comment by bobloadmire** [comment]
This issue was closed, maybe you should start a new one @guntherbob20

**Comment by kaso17** [comment]
This issue is still open.
The root problem is that it's not possible to get the latest torrents for multiple categories with one request.

**Comment by bobloadmire** [comment]
gotcha. Hope it can be fixed easily, I can't currently use jackett with lidarr which is a bummer because the native indexers are not the best.

**Comment by kaso17** [comment]
@bobloadmire keep trying adding torlock, once there's a audio torrent on the https://www.torlock2.com/fresh.html page the test should succeed.

**Comment by bobloadmire** [comment]
oh good idea, i'll try that.

**Comment by bobloadmire** [comment]
Actually it looks like https://www.torlock2.com/fresh.html excludes audio. There are audio torrents added within the last 40min, where there are hours old torrents on that page. So unfortunately I don't think it will ever work.

**Comment by kaso17** [comment]
@bobloadmire thank you for letting us know.
8fd10dd2d10e2552a629b7889e91bebe88748e52 should fix the problem, but make sure to specify the search cats. If no/all categories are specified it will hit the server with 11 queries.

**Comment by bobloadmire** [comment]
Thanks, Lidarr defaults to 8000, 8010, 8020, and 8030 so it should be good to go.
