### ISSUE TITLE
Iptorrents cookie not working

### ISSUE THREAD

**Issue by Pizza132** [Jackett/Jackett#2734]
Hi Sir,

I'm getting crazy now, i'm trying for a few months to get access to iptorrents with Jackett.
When i search for cookie i get this:
__cfduid=d70951e359ffea0187a8905a35f6507881521374368; uid=1779880; pass=a54c88c98d00356e1db4653faf7a39a6; hideCats=0; hideTop=0

But that's not working and it doesn't start with PHPSESSID. Please tell me what to do. Seems like i'm to dumb for this.

Greetings,

**Comment by kaso17** [comment]
Cookie looks fine.
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by Pizza132** [comment]
Hi Sir,

You are great! because of watching the log files i see what was wrong.
On iptorrents, you need to set in settings -> torrents category -> Icons and i had it on Code.

Thats why cookie didn't work. Thank you very much!
