### ISSUE TITLE
[thepiratebay] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by jlasalle148** [Jackett/Jackett#2746]
**Jackett version**: 0.8.770.0 
**Mono version** (if not using Windows):  4.2.1
And when you search it returns 0 items no matter what you search for.
-------------------------------

**Comment by garfield69** [comment]
works for me on my win7 Jackett 0.8.770
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.

**Comment by kaso17** [comment]
please update your mono version, 4.2 is really old and no longer officially supported by jackett.
