### ISSUE TITLE
How to decrypt a password / use a backup configuration?

### ISSUE THREAD

**Issue by alxlaxv** [Jackett/Jackett#2747]
Hi there 🦊 

I'm contacting you because I'm struggling with a problem of encrypted password.
I have redefine one of my indexer password on the tracker website and in Jackett and everything is working fine.

The issue is that my password manager didn't get the password change... so I have no idea what the new password is to connect myself to the website.
And cherry on the cake, the staff is not answering AND the procedure to reset the password doesn't work on their site.
I'm running on a Synology NAS.

So I have done the following steps:

1. Export the Indexers configuration
2. Install VS2017 Community
3. Launch Jackett Console project
4. Add a no login indexer to create the config tree
5. Stop Jackett
6. Copy my indexer .json file in the proper folder
7. Relaunch Jackett

And here is the error:
```
03-19 15:53:52 Error Failed loading configuration for XXX, trying backup System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()

03-20 09:27:30 Error Failed loading backup configuration for Elite-Tracker (no backup available), you must reconfigure this indexer System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
```

I know that the encrypting module store a RSA keys and stuff like that somewhere so thanks to @kaso17  I found it on Linux (Synology) in  `/usr/local/jackett/var/.config/.mono/keypairs/` but I can't find it on Windows for my debugging session.

The XML file from Linux contains the following structure, I found nothing about that in Windows.

```
<KeyPair>
  <Properties>
    <Provider Type="1" />
    <Container Name="98f3a7e3-0d6e-f432-8a18-e1144b53633f" />
  </Properties>
  <KeyValue>
    <RSAKeyValue>
      <Modulus></Modulus>
      <Exponent></Exponent>
      <P></P>
      <Q></Q>
      <DP></DP>
      <DQ></DQ>
      <InverseQ></InverseQ>
      <D></D>
    </RSAKeyValue>
  </KeyValue>
</KeyPair>
```

Maybe because it's not yet created? I have added a private tracker for my debugging session but this one is not encrypted...

So...

- Is there a simple way to decrypt this password on my running instance (linux/synology) directly?
- How can I import the RSA keys and stuff on Windows and where?
- Why are some password encrypted and not others?

Thanks for your help!!

**Comment by kaso17** [comment]
decoding the password on the Synology would require some custom mono program (
importing the linux keypairs into a windows system is probably very hard (windows stores them in some "secure" environment which can't be accessed easily).
There are 1 or two indexers which don't used the "password" config option to store it, in that case it's not encrypted, otherwise it should be always encrypted.
Given that you already went through the trouble of installing VS studio just add a line like `logger.Error("password: " + configData.Password.Value);` to e.g. the PerformQuery() method, compile it, copy it to the NAS, restart jackett. Now every time you do a search query the plaintext password should be written to the log.
