### ISSUE TITLE
[kickasstorrent-kathow] Exception (kickasstorrent-kathow): Ssl error:10000417:SSL routines:OPENSSL_internal:SSLV3_ALERT_ILLEGAL_PARAMETER  at /build/mono-5.10.0.160/external/boringssl/ssl/tls_record.c:462: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by chenks** [Jackett/Jackett#2750]
clicked the test button on "KickAssTorrent (thekat.nz)" and the result was

[kickasstorrent-kathow] Exception (kickasstorrent-kathow): Ssl error:10000417:SSL routines:OPENSSL_internal:SSLV3_ALERT_ILLEGAL_PARAMETER  at /build/mono-5.10.0.160/external/boringssl/ssl/tls_record.c:462: An error occurred while sending the request (Test)

**Jackett version**:  0.8.763.0
**Mono version** (if not using Windows):  5.10.0.160

-------------------------------

**Comment by kaso17** [comment]
Works fine for me. On which platform are you using it?

**Comment by chenks** [comment]
Debian Jessie - running on a raspberry pi

![untitled](https://user-images.githubusercontent.com/11945919/37662099-366296bc-2c4e-11e8-9921-eea4a804d784.jpg)

**Comment by kaso17** [comment]
please update to v0.8.770, that might fix it.

**Comment by chenks** [comment]
i'm not being present with an update for mono.
note that the other indexers work OK, just that one that has the error.

**Comment by kaso17** [comment]
the url changed recently, please update the jackett version

**Comment by chenks** [comment]
how do i update?
there is no update option within the GUI.

**Comment by kaso17** [comment]
Click on "Check for updates" (yellow button) below the indexer list

**Comment by chenks** [comment]
nothing happens

**Comment by kaso17** [comment]
please check the log

**Comment by chenks** [comment]
here is the log when testing that tracker

[log.txt](https://github.com/Jackett/Jackett/files/1836598/log.txt)

**Comment by kaso17** [comment]
The log doesn't show the update click, please enable enhanced logging first.
And make sure the jackett user has full write permissions to the jackett folder/files (should be the owner)

**Comment by chenks** [comment]
log attached
folder permission is set correctly.

[log.txt](https://github.com/Jackett/Jackett/files/1838975/log.txt)

**Comment by kaso17** [comment]
it's a normal log, please click on "apply server settings" after enabling enhanced logging

**Comment by chenks** [comment]
i did do that.
i ticked the box, then clicked apply server settings.
that was the resulting log after i then clicked on update.

**Comment by kaso17** [comment]
The log should contain "Debug" messages, which isn't the case. Please try running jackett with the `-t -l` command line options.
