### ISSUE TITLE
[rarbg] Exception (rarbg): Error parsing Infinity value. Path '', line 1, position 2.: Error parsing Infinity value. Path '', line 1, position 2. (Test)

### ISSUE THREAD

**Issue by simeon4110** [Jackett/Jackett#2758]
**Jackett version**:  0.8.770.0
**Mono version** (if not using Windows):  Mono JIT compiler version 5.10.0.160 (tarball Wed Mar  7 15:14:33 UTC 2018)

**Comment by garfield69** [comment]
Duplicate of #2753
