### ISSUE TITLE
[TehConnection] Returns 0 results for some searches

### ISSUE THREAD

**Issue by tgharib** [Jackett/Jackett#276]
For these two, I consistently get 0 results:

http://127.0.0.1:9117/potato/tehconnection?imdbid=tt0371746&user=&passkey=xxx

http://127.0.0.1:9117/potato/tehconnection?imdbid=tt0259446&user=&passkey=xxx

Is this an issue on my end or can anyone confirm it's a bug?

**Comment by flightlevel** [comment]
This should be fixed in the latest release https://github.com/Jackett/Jackett/releases/tag/v0.7.195
It was failing when the imdb id had a zero in front like above

**Comment by tgharib** [comment]
I still get an error for the first one. The second one has been fixed though with the v0.7.195 release.

**Comment by flightlevel** [comment]
I see what's happening here, should be fixed in next release
