### ISSUE TITLE
[torrentsyndikat] Exception (torrentsyndikat): Index was out of range. Must be non-negative and less than the size of the collection.Parameter name: index: Parse error (Test)

### ISSUE THREAD

**Issue by uffcd** [Jackett/Jackett#2764]
[torrentsyndikat] Exception (torrentsyndikat): Index was out of range. Must be non-negative and less than the size of the collection.Parameter name: index: Parse error (Test)

**Jackett version**:   0.8.779.0

**Comment by garfield69** [comment]
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.

**Comment by kaso17** [comment]
fixed via 792d2a433f4700773524dcabe20b36c34eb88ce5
