### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Connection reset by peer: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by AamirMunir** [Jackett/Jackett#2773]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
is this still happening to you?
TPB has been up and down like a yo-yo these last couple days, but appears to be back up again at the moment.

**Comment by JKay85** [comment]
I've been getting a similar issue with x1337
