### ISSUE TITLE
Indexers not loading

### ISSUE THREAD

**Issue by hsimm** [Jackett/Jackett#2774]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.779.0
**Mono version** (if not using Windows):  5.8.0.127

-------------------------------

Upon loading Jackett Dashboard, and clicking into "Add Indexer", the list of indexers do not show.
Tried pressing CMD + Shift + R, but nothing happened.

[log.txt](https://github.com/Jackett/Jackett/files/1837064/log.txt)
![image](https://user-images.githubusercontent.com/1507531/37765842-8c867272-2d82-11e8-8091-83dadab1b49d.png)

**Comment by kaso17** [comment]
please use the debugger of your browser (F12) and check the network tab for errors during reload

**Comment by hsimm** [comment]
Hi @kaso17, so there's a failed request to /api/v2.0/indexers?_=1521777509473
How can I resolve this error? I've tried reinstalling but it doesn't work.

![image](https://user-images.githubusercontent.com/1507531/37814015-ff78a5c8-2e24-11e8-96cd-71edd1663fec.png)

**Comment by kaso17** [comment]
please provide screenshots of the headers and response tabs of that request
