### ISSUE TITLE
not auto updating Jackett on synology

### ISSUE THREAD

**Issue by ward0** [Jackett/Jackett#2778]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  Version 0.8.763.0
**Mono version** (if not using Windows):  mono version: 5.8.0.108 (tarball Sat Feb 24 10:26:40 UTC 2018)

-------------------------------
manual update works w/o problem:
Deleting JackettUpdate temp files from /tmp/JackettUpdate-v0.8.784-636573497957004930

auto update to pre-release is enabled but never working :(

**Comment by flightlevel** [comment]
These sorts of issues are usually file permission related

Does updater.txt log file give any clues?

**Comment by ward0** [comment]
@flightlevel  not finding any file in all subfolders under /usr/local/radarr

**Comment by kaso17** [comment]
Does the manual update really work (new version after you checked for updates)?
Auto update is essentially nothing else than an automated update check every 24 hours (Same code as the manual check).
Which jackett version is shows in the syno package center?
AFAIK it should be v0.8.490-6.
Which DSM version are you running?

**Comment by ward0** [comment]
@kaso17 my jackett version in synology is v0.8.490-6

i do auto updates with DSM, so no version behind.

yes, manual work all the time, no problem with that.

**Comment by kaso17** [comment]
very odd, please leave it running for >24 hours once a new release is available (and it should update) and post the enhanced logs (preferable without any requests).

**Comment by ward0** [comment]
@kaso17 I will disable my shutdown task to see if it works then. the updater task will register the elapsed time in a database i presume before a new update check?

**Comment by kaso17** [comment]
no, the updater will run every 24 hours after starting jackett (it's not stored anywhere). If you stop/shutdown jackett before this 24 hours timer this explains the problem :)

**Comment by ward0** [comment]
@kaso17 Any chance you can resolve this? Change the update behavior for people who don't run 24/7?

Maybe add a parameter so we can set when to check for updates? 1hour instead of 24hours.. That should be possible to set in the config and make the update checker a variable that you can fill in?

**Comment by kaso17** [comment]
With 457449866e3a6ac64ca545e2a45ba18f669f62b1 the first update check will be after 1 hour.

**Comment by ward0** [comment]
@kaso17 Thanks!!!!!
