### ISSUE TITLE
[torrentleech] Error when attempting torrent grab

### ISSUE THREAD

**Issue by Skrumpy** [Jackett/Jackett#2784]
During some testing I requested the movie "Only The Brave" on Ombi. The request is sent appropriately to Radarr (Jackett indexer as torznab feed) and finds an appropriate match from TL, but then throws an error (shown below). Jackett log error is also shown below (with all logs attached). The torrent file will not be sent to BlackHole even via a manual download. Other movies from TL and other trackers (all generated from Jackett) have DL'd fine so far. I can even manually download other versions from TL for the same movie. All Jackett tests and communication tests via Ombi/Radarr/Jackett and torrents are successful.

As a side-note, Radarr only seems to want the non-proper release from TL. I was getting an error that the title with "proper" in (title only varies by this tag, shown below) was rejected because it didn't match the requested name. I'm assuming this is because the torrent was named Only The Brave proper YEAR instead of Only The Brave YEAR proper, although I tried both searching by title yes/no. Not sure if this is WAI.

**Jackett version**:  0.8.784.0
**Mono version** (if not using Windows):  Using Win 10 Pro x64 Creators

[log.20180323.00000.txt](https://github.com/Jackett/Jackett/files/1843798/log.20180323.00000.txt)
[log.20180323.00001.txt](https://github.com/Jackett/Jackett/files/1843799/log.20180323.00001.txt)
[log.20180323.00002.txt](https://github.com/Jackett/Jackett/files/1843800/log.20180323.00002.txt)
[log.20180323.00003.txt](https://github.com/Jackett/Jackett/files/1843801/log.20180323.00003.txt)
[log.txt](https://github.com/Jackett/Jackett/files/1843802/log.txt)

-------------------------------
**From Jackett log**
![image](https://user-images.githubusercontent.com/20248002/37841937-e065ecbc-2e8e-11e8-8ce2-61169e2b199b.png)

**What appears in Radarr**
![image](https://user-images.githubusercontent.com/20248002/37841109-d933927a-2e8c-11e8-8f3e-c24a8728a552.png)

**Manual search at TL for the movie**
![image](https://user-images.githubusercontent.com/20248002/37842438-1b75111a-2e90-11e8-80d9-62d87f9418cb.png)

**Comment by kaso17** [comment]
error also happens if you download that particular torrent directly from their website (other torrents are working fine). Not an Jackett issue, please contact the TL staff.
