### ISSUE TITLE
[torrentsyndikat] Exception (torrentsyndikat): String was not recognized as a valid TimeSpan.: Parse error (Test)

### ISSUE THREAD

**Issue by y4m4aa** [Jackett/Jackett#2788]
[torrentsyndikat] Exception (torrentsyndikat): String was not recognized as a valid TimeSpan.: Parse error (Test)

[log.txt](https://github.com/Jackett/Jackett/files/1844646/log.txt)

**Jackett version**:  0.8.799.0
**Mono version**:  5.10.0.140

-------------------------------

**Comment by kaso17** [comment]
fixed via #2795 (Thank you @Fippsy) + 65b008b75aa2463303c7bdc5fc8231e9132ebe5a
