### ISSUE TITLE
Jackett category find

### ISSUE THREAD

**Issue by MaddionMax** [Jackett/Jackett#2791]
Hello!

Please somebody help me, how can I find and identify categories between tracker and Jackett?
In Jackett I see 2030, 2040 numbers, whats are xvid and xvid_hun on tracker side.

Where can I find a a tutorial for this, which write down how to set these numbers to tracker categories?

Thanks!

**Comment by kaso17** [comment]
The exact mapping can be found in the code:
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/NCore.cs#L46-L82
For ncore there's no 1:1 mapping because they don't use numeric IDs (for trackers with numeric IDs a 1:1 mapping is created).
