### ISSUE TITLE
[torrentleech] Exception (torrentleech): Invalid URI: The format of the URI could not be determined.: Parse error (Config)

### ISSUE THREAD

**Issue by Jackeldk** [Jackett/Jackett#2793]
Anyone seen this issue before and perhaps knows a fix ?

**Jackett version**:  0.8.799.0

-------------------------------

**Comment by kaso17** [comment]
fixed via 257295ed089d6a303e7de3b192e9f00a7d229a87

**Comment by gymllfixit** [comment]
Only TorrentLeech changed something and now this has broken TorrentLeech entirely.

```
018-03-25 21:20:18.0131 Error Error downloading torrentleech https://www.torrentleech.org//download/1011429/Westworld.S01.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.torrent System.Exception: Remote server returned NotFound```

**Comment by Jackeldk** [comment]
okay.. cool..

but how do i put this fix in ?
cant seem to find the files here.

**Comment by kaso17** [comment]
@gymllfixit looks like they changed the download link format back...
a839f7d56f94d2e9a979283a76759098fe86d9eb should fix it for both cases...

**Comment by kaso17** [comment]
@Jackeldk update to the latest version
