### ISSUE TITLE
Add IMDB search via RSS for rarbg

### ISSUE THREAD

**Issue by ajarmoszuk** [Jackett/Jackett#2801]
I've noticed that I cannot search via a IMDB ID on the rarbg tracker, is this a possibility to be added in? 
I understand that rarbg returns the imdb id by itself when searching via the name itself. 
Searching by name results in a bunch of items that not at all related to what is being searched. 
As an example if I search for "Mr.Robot", I get unrelated results for Robot Chicken.

Jackett version: Docker newest
Mono version (if not using Windows): N/A

**Comment by kaso17** [comment]
should be fixed via 06bf11b64eb79030326c8c5c2961a006643ac412
With the next release you should be able to use imdbid with all search modes like this:
http://127.0.0.1:9117/jackett/api/v2.0/indexers/rarbg/results/torznab/api?apikey=XXX&t=tv-search&cat=&imdbid=4158110
