### ISSUE TITLE
Extratorrent.ag is the same extratorrents-cc.com?

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#2804]
If yes, why don't switch to
https://www.extratorrents-cc.com/

instead wait all times .ag?

**Comment by garfield69** [comment]
nope. they are different sites.
replacing the address will not work without also changing the supporting html processing code.

**Comment by garfield69** [comment]
extratorrent.ag is back up again.

**Comment by XxUnkn0wnxX** [comment]
nope it down again :(
