### ISSUE TITLE
void CloudFlareUtilities.ClearanceHandler.set_ClearanceDelay(int): void CloudFlareUtilities.ClearanceHandler.set_ClearanceDelay(int) (Test) when connecting to any tracker

### ISSUE THREAD

**Issue by khumps** [Jackett/Jackett#2807]
**Jackett version**:  0.8.799.0
**Mono version** (if not using Windows):  5.10.1.4-0xamarin1+ubuntu1604b1

Jackett has been working fine and then, as of yesterday it is no longer pulling results. Ive tried restarting jackett, restarting the server, proxying the traffic but no luck
https://pastebin.com/g3eDhAx4
-------------------------------

**Comment by kaso17** [comment]
most likely during the update not all files were updated. please make sure the jackett user owns the jackett directory and all sub folders/dirs.

To fix this you'll have to manually re-extract the archive replacing all files.
