### ISSUE TITLE
[Enhancement] Aggregate indexers should use Caps of indexer with worst caps

### ISSUE THREAD

**Issue by galli-leo** [Jackett/Jackett#2808]
I haven't come across this myself, but it seems like Jackett doesn't correctly report the caps for aggregate indexers. (See https://github.com/Radarr/Radarr/issues/2510#issuecomment-376178507).

When not all indexers support searching by imdbid, the caps endpoint for /all should not allow searching by imdbid. This can probably be applied to all other capabilities as well, such as searching by tvdbid.

**Comment by kaso17** [comment]
jackett should look up the title in case the imdbid is specified, but probably the OMDB API key needs to be configured in order to make this work. I'll look into this.

**Comment by biship** [comment]
I am the creator of that ticket for Radarr and after your comment upgraded my OMDB account from free to paid to allow for more API queries just in cast that was the issue. I wasn't seeing any API errors however, and the behavior has not changed since. (So I do not think the account upgrade helped).

**Comment by kaso17** [comment]
should be fixed via 9ceeb7144868211b2ea46228080fe65439b63156
