### ISSUE TITLE
Can't search indexer if VPN is enabled

### ISSUE THREAD

**Issue by smarshallsay** [Jackett/Jackett#281]
Can't search indexer if VPN is up for some reason. Only indexer I am using is TorrentLeech.

Error in log is "Error	Exception in test_indexer"

VPN is PrivateInternetAccess, Windows 10 x64

Anyone have any ideas? I can browse the TL website just fine with VPN up or down.

EDIT: Full log from enhanced logging:

Mar 22, 2016 10:27:32 AM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
Mar 22, 2016 10:27:32 AM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Mar 22, 2016 10:27:32 AM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Mar 22, 2016 10:27:32 AM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Mar 22, 2016 10:27:32 AM	Info	
HttpActionBinding ExecuteBindingAsync 
Mar 22, 2016 10:27:32 AM	Info	
HttpActionBinding ExecuteBindingAsync 
Mar 22, 2016 10:27:32 AM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Mar 22, 2016 10:27:32 AM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Mar 22, 2016 10:27:32 AM	Info	
ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Mar 22, 2016 10:27:32 AM	Info	
ApiControllerActionSelector SelectAction 
Mar 22, 2016 10:27:32 AM	Info	
AdminController ExecuteAsync 
Mar 22, 2016 10:27:32 AM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Mar 22, 2016 10:27:32 AM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Mar 22, 2016 10:27:32 AM	Info	
DefaultHttpControllerActivator Create 
Mar 22, 2016 10:27:32 AM	Info	
HttpControllerDescriptor CreateController 
Mar 22, 2016 10:27:32 AM	Info	
DefaultHttpControllerSelector SelectController Admin
Mar 22, 2016 10:27:32 AM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Mar 22, 2016 10:27:32 AM	Info	
  http://127.0.0.1:9117/Admin/GetLogs?_=1458642358978
Mar 22, 2016 10:27:30 AM	Info	
AdminController Dispose 
Mar 22, 2016 10:27:30 AM	Info	
AdminController Dispose 
Mar 22, 2016 10:27:30 AM	Info	
  Content-type='application/json; charset=utf-8', content-length=81
Mar 22, 2016 10:27:30 AM	Info	
AdminController ExecuteAsync 
Mar 22, 2016 10:27:30 AM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync 
Mar 22, 2016 10:27:30 AM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Mar 22, 2016 10:27:30 AM	Info	
ApiControllerActionInvoker InvokeActionAsync 
Mar 22, 2016 10:27:30 AM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]'
Mar 22, 2016 10:27:30 AM	Error	
Exception in test_indexer
Mar 22, 2016 10:27:30 AM	Info	
Found 0 releases from TorrentLeech
Mar 22, 2016 10:27:29 AM	Debug	
WindowsWebClient: Returning OK => <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"> 
    <head>
        <title>Login :: TorrentLeech.org</title>                        <link href="/templates/tl_default/css/default.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/templates/tl_default/css/tlbasic/jquery-ui.css" media="screen" rel="stylesheet" type="text/css" />
                <script type="text/javascript" src="/js/global/jquery-1.4.2.min.js"></script>        <script type='text/javascript'>
            $(document).ready(function(){
                $("#tweet").tweet({
                    username: "torrentleech",
                    join_text: "auto",
                    avatar_size: 55,
                    count: 4,
                    auto_join_text_default: "we said,", 
                    auto_join_text_ed: "we",
                    auto_join_text_ing: "we were",
                    auto_join_text_reply: "we replied to",
                    auto_join_text_url: "we were checking out",
                    loading_text: "loading tweets..."
                });
            });
        </script>
        <script type='text/javascript'>
            var googletag = googletag || {};
            googletag.cmd = googletag.cmd || [];
            (function() {
            var gads = document.createElement('script');
            gads.async = true;
            gads.type = 'text/javascript';
            var useSSL = 'https:' == document.location.protocol;
            gads.src = (useSSL ? 'https:' : 'http:') + 
            '//www.googletagservices.com/tag/js/gpt.js';
            var node = document.getElementsByTagName('script')[0];
            node.parentNode.insertBefore(gads, node);
            })();
            </script>
            
            <script type='text/javascript'>
            googletag.cmd.push(function() {
            googletag.defineSlot('/1262945/TL_Login_Page_TOP', [728, 90], 'div-gpt-ad-1335175113394-0').addService(googletag.pubads());
            googletag.pubads().enableSingleRequest();
            googletag.enableServices();
            });
        </script>
    </head>

    <body>
        <div id="loginHeader"></div>
        <div id="login">
            <div class="ui-widget ui-widget-content ui-corner-all"><center>
                
                <div id='div-gpt-ad-1335175113394-0' style='width:728px; height:90px;'>
                <script type='text/javascript'>
                    googletag.cmd.push(function() { googletag.display('div-gpt-ad-1335175113394-0'); });
                </script>
                </div>
            </center></div>
            <div id="loginFormBlock">
                                            <form method="post" action="/user/account/login/">
                       <div id=loginform>
                           <label class="field-title">Username </label><label class="txt-field"><input name="username" type="text" tabindex="1" /></label>
                           <label class="field-title">Password </label><label class="txt-field"><input name="password" type="password" tabindex="2"/></label>
                       </div>
                                              <div id="remember">
                           Remember Me: <input name="remember_me" type="checkbox" tabindex="3" />
                           <input name="login" type="submit" value="submit" tabindex="4"/><br>
                       </div>
                       <div style="text-align: center; margin-top:20px">
                           <a class="lostpassword" href="/user/account/lostpassword" tabindex="5">Lost Password</a> | 
                           <a class="signup" href="/user/account/signup" tabindex="6">Signup With Invite</a>
                       </div>
                   </form>
                </div>
                        <div id="loginTwitterNews">
                <div class="tweetText">
                <img alt="Twitter" src="/images/twitter.png" class="textmiddle" height="30" width="30"/>&nbsp;<a href="http://www.twitter.com/torrentleech">Latest Tweets</a>
                </div>
                <div id="chat"><img alt="Chat" src="/images/chat.png" class="textmiddle" height="30" width="30"/>&nbsp;<a href="/user/chat/guest" target="_blank">Chat</a></div>
                <div id="tweet">                <a class="twitter-timeline"  href="https://twitter.com/torrentleech"  data-widget-id="374526060034936832">Tweets by @torrentleech</a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></div></div>
            <div id="clearfloat"></div>
        </div>
        
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-5866012-1', 'auto');
            ga('send', 'pageview');

        </script>
    </body>
</html>
Mar 22, 2016 10:27:29 AM	Debug	
WindowsWebClient:GetString(Url:https://www.torrentleech.org/torrents/browse/index/)
Mar 22, 2016 10:27:29 AM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
Mar 22, 2016 10:27:29 AM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='Test()'
Mar 22, 2016 10:27:29 AM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Mar 22, 2016 10:27:29 AM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()'
Mar 22, 2016 10:27:29 AM	Info	
HttpActionBinding ExecuteBindingAsync 
Mar 22, 2016 10:27:29 AM	Info	
HttpActionBinding ExecuteBindingAsync 
Mar 22, 2016 10:27:29 AM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Mar 22, 2016 10:27:29 AM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Mar 22, 2016 10:27:29 AM	Info	
ApiControllerActionSelector SelectAction Selected action 'Test()'
Mar 22, 2016 10:27:29 AM	Info	
ApiControllerActionSelector SelectAction 
Mar 22, 2016 10:27:29 AM	Info	
AdminController ExecuteAsync 
Mar 22, 2016 10:27:29 AM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Mar 22, 2016 10:27:29 AM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Mar 22, 2016 10:27:29 AM	Info	
DefaultHttpControllerActivator Create 
Mar 22, 2016 10:27:29 AM	Info	
HttpControllerDescriptor CreateController 
Mar 22, 2016 10:27:29 AM	Info	
DefaultHttpControllerSelector SelectController Admin
Mar 22, 2016 10:27:29 AM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Mar 22, 2016 10:27:29 AM	Info	
  http://127.0.0.1:9117/Admin/test_indexer

**Comment by flightlevel** [comment]
While you are connected to the VPN, if you remove the indexer from Jackett dashboard and then re add it, does it work then?

**Comment by smarshallsay** [comment]
Yep, that worked! Thanks!.

How come?

**Comment by flightlevel** [comment]
Best guess would be that the tracker creates a new cookie when your IP address changes

**Comment by smarshallsay** [comment]
Well thanks a ton for your work :D

**Comment by smarshallsay** [comment]
I've temporarily fixed this my end by forcing Jackett to re-authenticate every time a query is made. 
Not ideal but I can prove it works by disconnecting and reconnecting VPN and it still works. 
Maybe you'll need an re-auth (ApplyConfiguration) if request fails. That way it would only fail and need to be re-authed once every IP change.

**Comment by JigSawFr** [comment]
@smarshallsay this "problem" is on tracker's side, it's security measure. If you use a VPN on your computer, situation will be same.
