### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by vogstar** [Jackett/Jackett#2811]
I have been useing Jacket for about a year and just yesterday it stoped downloading links from Torrenleech.  I noticed I might have to upgrade but when I try it never upgrades and stays at 8.811

here is what I see in the logs

Mar 26, 2018 06:33:31 PM | Info | Found 100 (1 new) releases from TorrentLeech
-- | -- | --
Mar 26, 2018 06:33:18 PM | Info | Starting web server at http://*:9117/
Mar 26, 2018 06:33:18 PM | Info | Deleting JackettUpdate temp files from /tmp/JackettUpdate-v0.8.815-636577003931494700
Mar 26, 2018 06:33:18 PM | Info | Adding aggregate indexer
Mar 26, 2018 06:33:18 PM | Info | Loading Cardigann definition /opt/jackett/Definitions/ztracker.yml
Mar 26, 2018 06:33:18 PM | Info | Loading Cardigann definition /opt/jackett/Definitions/zooqle.yml
Mar 26, 2018 06:33:18 PM | Info | Loading Cardigann definition /opt/jackett/Definitions/zelkaorg.yml
Mar 26, 2018 06:33:18 PM | Info | Loading Cardigann definition /opt/jackett/Definitions/zamundanet.yml

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
whats the platform? windows, linux, etc
if you use the *Ctrl F5* sequence on your Jackett Dashboard, what does the version at the bottom of the page say?

**Comment by evilvibes** [comment]
Also having this issue on ubuntu 16.04 won't update past Version 0.8.692.0

**Comment by jlogan** [comment]
I'm having an issue with Jackett connecting to TorrentLeech also. I'm sure it has to do with the new TorrentLeech web site design.

**Comment by HyakoV2** [comment]
same here after the site update cant connect on jackett!

**Comment by kaso17** [comment]
Make sure that the jackett user owns the Jackett directory and all files in it.
torrentleech support has been fixed in v0.8.857

**Comment by vogstar** [comment]
do we have to use v4.torrenleech.org or will it work with the current setup?

**Comment by garfield69** [comment]
once you are on Jackett 0.8.857 or newer ,then the torrentleech indexer is set up for v5.

**Comment by jlogan** [comment]
My TorrentLeech indexer still is not working even after upgrading to v0.8.857. When I test, I get this:

`An error occured while testing this indexer
Exception (torrentleech): Input string was not in a correct format.: Parse error`

And there are some scary looking logs too.

**Comment by kaso17** [comment]
@jlogan please open a new issue containing the full enhanced log.
Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
