### ISSUE TITLE
Torlock:  Error while parsing row '<tr>

### ISSUE THREAD

**Issue by biship** [Jackett/Jackett#2812]
**Jackett version**:  0.8.815.0
-------------------------------
I'm getting errors about every 5 mins, looks like it is coming from torlock. Other indexers are working fine. A test on torlock runs successfully. I haven't changed the default url of https://www.torlock2.com/
`

Mar 27, 2018 08:13:05 AM | Error | CardigannIndexer (torlock): Error while parsing row '<tr> 	<td> 		<div style="float:left"> 			<span class="tv3"> 			</span> 			<a href="/torrent/6982036/the-voice-s14e09-web-tbs%5Beztv%5D.html"> 				<b>The Voice S14E09 WEB x264-TBS[eztv]</b> 			</a> 		</div> 		<div style="float:right"> 			<img src="/images/ver.png" title="Verified Torrent" alt="" class="tb">			 		</div> 	</td> 	<td class="td">59 min</td> 	<td class="ts">1.1 GB</td> 	<td class="tul">93</td> 	<td class="tdl">257</td> 	<td> 		<img src="/images/health7.jpg" alt="" class="th">		 	</td> </tr> ':  System.Exception: Error while parsing field=date, selector=td:nth-child(2), value=59 min: DateTime parsing failed for "59 min": System.Exception: FromFuzzyTime parsing failed    at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format)    at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format)    at Jackett.Common.Indexers.CardigannIndexer.<PerformQuery>d__28.MoveNext()
-- | -- | --
Mar 27, 2018 08:13:05 AM | Error | CardigannIndexer (torlock): Error while parsing row '<tr> 	<td> 		<div style="float:left"> 			<span class="tv1"> 			</span> 			<a href="/torrent/6982037/%5Bdygc-org%5D%E7%A5%96%E5%AE%97%E5%8D%81%E4%B9%9D%E4%BB%A3-the-faces-of-my-gene-2018-4in1-4k-1080p-x265-aac-mandarin-chs-dygc.html"> 				<b>[DYGC ORG]祖宗十九代 The Faces of My Gene 2018 4In1 4K 1080P X265 X264 AAC Mandarin CHS ENG-DYGC</b> 			</a> 		</div> 		<div style="float:right"> 			<img src="/images/ver.png" title="Verified Torrent" alt="" class="tb">			 		</div> 	</td> 	<td class="td">58 min</td> 	<td class="ts">9.9 GB</td> 	<td class="tul">146</td> 	<td class="tdl">220</td> 	<td> 		<img src="/images/health7.jpg" alt="" class="th">		 	</td> </tr> ':  System.Exception: Error while parsing field=date, selector=td:nth-child(2), value=58 min: DateTime parsing failed for "58 min": System.Exception: FromFuzzyTime parsing failed    at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format)    at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format)    at Jackett.Common.Indexers.CardigannIndexer.<PerformQuery>d__28.MoveNext()
Mar 27, 2018 08:13:05 AM | Error | CardigannIndexer (torlock): Error while parsing row '<tr> 	<td> 		<div style="float:left"> 			<span class="tv3"> 			</span> 			<a href="/torrent/6982041/torrent9-red-%5D-the-terror-s01e01-vostfr-webrip.html"> 				<b>Torrent9 red ] The Terror S01E01 VOSTFR WEBRip XviD<font color="#ccc">-ZT</font> 				</b> 			</a> 		</div> 		<div style="float:right"> 			<img src="/images/ver.png" title="Verified Torrent" alt="" class="tb">			 		</div> 	</td> 	<td class="td">56 min</td> 	<td class="ts">350 MB</td> 	<td class="tul">164</td> 	<td class="tdl">224</td> 	<td> 		<img src="/images/health7.jpg" alt="" class="th">		 	</td> </tr> ':  System.Exception: Error while parsing field=date, selector=td:nth-child(2), value=56 min: DateTime parsing failed for "56 min": System.Exception: FromFuzzyTime parsing failed    at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format)    at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format)    at Jackett.Common.Indexers.CardigannIndexer.<PerformQuery>d__28.MoveNext()

`

**Comment by kaso17** [comment]
fixed via c866748de303979f5c56f1f6519d8d4b2abda5d0
