### ISSUE TITLE
[wihd] Exception (wihd): Object reference not set to an instance of an object: Parse error (Config)

### ISSUE THREAD

**Issue by Bl0ub** [Jackett/Jackett#2814]
**Jackett version**:  0.8.815.0
**Mono version** (if not using Windows):  5.8.0.108-11

Error when adding the indexer for wihd :

Error on 20180327174749 for WiHD.txtSystem.NullReferenceException: Object reference not set to an instance of an object   at Jackett.Common.Indexers.WiHD+<PerformQuery>d__21.MoveNext () [0x0048b] in <776eb7c1fae349a9ba3d54d43a83867c>:0      Error, unable to parse result    at Jackett.Common.Indexers.WiHD+<PerformQuery>d__21.MoveNext () [0x0048b] in <776eb7c1fae349a9ba3d54d43a83867c>:0

**Comment by kaso17** [comment]
The wihd indexer haven't been updated for a long time because no staff member has access to it.
If you have an invite please send it to kaso1717 -at- gmail.com
