### ISSUE TITLE
[yify] Sequence contains no matching element (Config)

### ISSUE THREAD

**Issue by Firemad03** [Jackett/Jackett#2815]
**Jackett version**:  v0.8.815
**Mono version** (if not using Windows):  4.6

-------------------------------

**Comment by garfield69** [comment]
YiFY works fine for me on my win7 Jackett 0.8.815
I suspect the problem could be your ancient mono version... perhaps you should consider upgrading to the latest version, http://www.mono-project.com/download/stable/ and straight afterwards, refresh your certificates as well.
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
    or `sudo wget -O - https://curl.haxx.se/ca/cacert.pem | sudo cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`
  - On QNAP refer to #2111
and reboot (or just restart all Jackett services) after the imports are completed.

**Comment by Nosskirneh** [comment]
I get this as well with Jackett version 0.9.16.0 and Mono version 5.12.0.260-1.

```
/ » wget -O - https://curl.haxx.se/ca/cacert.pem | sudo cert-sync /dev/stdin
--2018-07-25 09:30:52--  https://curl.haxx.se/ca/cacert.pem
Mono Certificate Store Sync - version 5.12.0.0
Populate Mono certificate store from a concatenated list of certificates.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving curl.haxx.se (curl.haxx.se)... 151.101.86.49, 2a04:4e42:14::561
Connecting to curl.haxx.se (curl.haxx.se)|151.101.86.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 213947 (209K) [application/x-pem-file]
Saving to: ‘STDOUT’

-                                            100%[===========================>] 208.93K   118KB/s    in 1.8s

2018-07-25 09:31:00 (118 KB/s) - written to stdout [213947/213947]

Importing into legacy system store:
I already trust 134, your new list has 132
2 previously trusted certificates were removed.
Certificate removed: O=Root CA, OU=http://www.cacert.org, CN=CA Cert Signing Authority, E=support@cacert.org
Certificate removed: O=CAcert Inc., OU=http://www.CAcert.org, CN=CAcert Class 3 Root
Import process completed.

Importing into BTLS system store:
I already trust 134, your new list has 132
2 previously trusted certificates were removed.
Certificate removed: O=CAcert Inc., OU=http://www.CAcert.org, CN=CAcert Class 3 Root
Certificate removed: O=Root CA, OU=http://www.cacert.org, CN=CA Cert Signing Authority, E=support@cacert.org
Import process completed.

/ » sudo systemctl restart jackett
```

Still doesn't work.

**Comment by flightlevel** [comment]
@Nosskirneh 
That was more than 4 months ago
Is Yify's website still running and if so, what is their new address?

**Comment by Nosskirneh** [comment]
@flightlevel
It is still running: https://yts.am/

**Comment by flightlevel** [comment]
yts.am is already present in Jackett
Instead of searching for Yify when adding an indexer, search for yts
