### ISSUE TITLE
[OxTorrent] Exception (OxTorrent): Got redirected to another domain. Try changing the indexer URL to http://www.rantop.org/.: Parse error (Test)

### ISSUE THREAD

**Issue by Firemad03** [Jackett/Jackett#2816]
**Jackett version**:  v0.8.815
**Mono version** (if not using Windows):  4.6

-------------------------------

I think this torrent is dead. I followed the link and I got a 404 errors.

**Comment by garfield69** [comment]
@hed0nist since you created this indexer, can you confirm this site is gone, or know if there is a replacement domain name for the site?

**Comment by hed0nist** [comment]
Indeed the site is dead. You can delete it, and as far as i know there is no replacement. Actually it was a site very similar to NextTorrent in his layout. Sorry i am not really familiar with github. Let me know if it cant be deleted without my hand.

**Comment by kaso17** [comment]
deleted via 525f78caca3f832cda99c691949c4a5204bfa9ce, thank you
