### ISSUE TITLE
[worldwidetorrents] Exception (worldwidetorrents): Request to https://worldwidetorrents.me/torrents-search.php?search=

### ISSUE THREAD

**Issue by mtulek** [Jackett/Jackett#2819]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
the problem is at the WWT site itself, which is returning `DATABASE: mysql_connect: Connection refused`
remains to be seen if they sort it out in due time.

**Comment by garfield69** [comment]
WWT is back up and running fine now.
