### ISSUE TITLE
[torrentsyndikat] Exception (torrentsyndikat): Index was out of range. Must be non-negative and less than the size of the collection.Parameter name: index: Parse error (Config)

### ISSUE THREAD

**Issue by 5624158563** [Jackett/Jackett#2820]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
Duplicate of #2764
upgrade to Jackett 0.8.815 to fix.
