### ISSUE TITLE
Jackett - Torznab - The Pirate Bay - No Results in RSS then can't add Indexer

### ISSUE THREAD

**Issue by guntherbob20** [Jackett/Jackett#2822]
**Jackett version**:  0.8.815.0
-------------------------------
I was creating my Lidarr instance and I ran into an issue which blocked me from using The Pirate Bay from Jackett for my torrent client. In one certain configuration I was blocked from adding the indexer to Lidarr due to a failure to find anything from the RSS, but when i added the Movie category to the configuration it worked no problem. Bellow details what I am experiencing:

This configuration would not work: https://i.imgur.com/Jxo9Wa3.png

But this configuration would work: https://i.imgur.com/tDwK9H8.png

This is the RSS feed of TPB with the Category Code 3000: [RSS Feed for Not working](http://10.1.1.106:9117/api/v2.0/indexers/thepiratebay/results/torznab/api?apikey=zvcui6dj74hx9nfjaxcpru22ibygdf4v&t=search&cat=3000&q=)

RSS Feed: [3000.txt](https://github.com/Jackett/Jackett/files/1857766/3000.txt)

This is the RSS feed of TPB with the Category Code 3000,2000: [RSS Feed for Working](http://10.1.1.106:9117/api/v2.0/indexers/thepiratebay/results/torznab/api?apikey=zvcui6dj74hx9nfjaxcpru22ibygdf4v&t=search&cat=3000,2000&q=)

RSS Feed: [3000 and 2000.txt](https://github.com/Jackett/Jackett/files/1857767/3000.and.2000.txt)

Since i was able to find a workaround for my issue i don't consider this a major bug, but there are not indicators in either system Lidarr or Jackett which i was able to identify what was causing the indexer to not find anything. It wasn't until i just happen to miss type something and realized it worked. 

Thanks for all the hard work!

**Comment by kaso17** [comment]
TPB unfortunately doesn't allow limiting the "most recent torrents" view to specific categories.
Due to that it often happens that the most recent torrents don't contain any audio torrents resulting in zero results causing the lirdarr test to fail.

**Comment by Darks7ar** [comment]
Jackett can fix by allowing us to override the test and add the indexer anyway without validation.
