### ISSUE TITLE
Development on Mac

### ISSUE THREAD

**Issue by renjithsasidharan** [Jackett/Jackett#2826]
I was trying to build this on Mac and ran into this error.

`/workspace/Jackett/src/Jackett.Common/Jackett.Common.csproj: Error NU1201: Project CurlSharp is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project CurlSharp supports: net452 (.NETFramework,Version=v4.5.2) (NU1201) (Jackett.Common)`

Is it possible to do development on Mac?

**Comment by renjithsasidharan** [comment]
Basically, I was trying to enhance the api to take subset of available indexers to search for.
Something like `api/v2.0/indexers/rarbg,thepiratebay/results`

See the multiple indexers used in the url.

**Comment by kaso17** [comment]
Yes, building on mac should work (but I can't help you) 
The curlsharp part should be compatible with netstandard2.0.
