### ISSUE TITLE
New better kickasstorrent tracker.

### ISSUE THREAD

**Issue by Soul1990** [Jackett/Jackett#2828]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------
I hope this is okay to request, I have been going through all the different versions of KAT and searching randomly to see who has better results, https://katcr.date/ had every popular show that came out this week hours before any of the other KAT sites and it even included the x265 versions.

If https://katcr.date/ could be added as a tracker it would be greatly appreciated.

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by garfield69** [comment]
https://kickasstvshow.club/ returning cloudflare Error 524 A timeout occurred

**Comment by garfield69** [comment]
katcrs back online.

**Comment by garfield69** [comment]
returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
so has https://kickasstvshow.club/ gone, broken or moved to another domain?
if I don't get any news by the end of the month I will remove it.

**Comment by garfield69** [comment]
if I use http://kickasstvshow.club/ it is currently showing
```
502 Bad Gateway
openresty
```
https://kickasstvshow.club/ returns ERR_CONNECTION_REFUSED

any one have any news?
