### ISSUE TITLE
Forgot my password

### ISSUE THREAD

**Issue by Popupkiller** [Jackett/Jackett#283]
I activated password protection, but I forgot my password.
Is there anything I can do besides reinstalling?

**Comment by flightlevel** [comment]
https://github.com/Jackett/Jackett/issues/258

**Comment by Popupkiller** [comment]
Thanks.

**Comment by jvacek** [comment]
For those who only find this now, just get rid of the "AdminPassword" line in your config file (e.g. ~/.config/Jackett/ServerConfig.json).

**Comment by Winblackka** [comment]
I have lost my password running Jackett on Qnap. Cant find the folder to edit the "ServerConfig.json"
Im using the APP from QNap Club.

**Comment by cadatoiva** [comment]
It looks like the location is: `/share/CACHEDEV1_DATA/homes/{user}/.config/Jackett/ServerConfig.json`
https://forum.qnap.com/viewtopic.php?t=116660#p518003
