### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Ssl error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER  at /spksrc/spk/mono/work-x64-6.1/mono-5.8.0.108/external/boringssl/ssl/tls_record.c:217: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by JKay85** [Jackett/Jackett#2835]
Attempted to test connection to tracker 1337x and got error message "[thepiratebay] Exception (thepiratebay): Ssl error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER  at /spksrc/spk/mono/work-x64-6.1/mono-5.8.0.108/external/boringssl/ssl/tls_record.c:217: An error occurred while sending the request (Test)"

PLATFORM
Synology DSM 6.1.6
**Jackett version**:  0.8.490-6
**Mono version** (if not using Windows):  5.8.0.108-11

Error log below:

Jackett.Common.IndexerException: Exception (thepiratebay): Ssl error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER   at /spksrc/spk/mono/work-x64-6.1/mono-5.8.0.108/external/boringssl/ssl/tls_record.c:217 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: SecureChannelFailure (One or more errors occurred.) ---> System.AggregateException: One or more errors occurred. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER   at /spksrc/spk/mono/work-x64-6.1/mono-5.8.0.108/external/boringssl/ssl/tls_record.c:217   at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00038] in <6b85ae33ded1428e932cb7ae66272042>:0    at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status) [0x0003e] in <6b85ae33ded1428e932cb7ae66272042>:0    at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus)   at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00006] in <6b85ae33ded1428e932cb7ae66272042>:0    at Mono.Net.Security.AsyncProtocolRequest+<ProcessOperation>d__24.MoveNext () [0x000ff] in <6b85ae33ded1428e932cb7ae66272042>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Mono.Net.Security.AsyncProtocolRequest+<StartOperation>d__23.MoveNext () [0x0008b] in <6b85ae33ded1428e932cb7ae66272042>:0     --- End of inner exception stack trace ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Mono.Net.Security.MobileAuthenticatedStream+<ProcessAuthentication>d__47.MoveNext () [0x00254] in <6b85ae33ded1428e932cb7ae66272042>:0     --- End of inner exception stack trace ---   at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Threading.Tasks.Task.Wait () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Mono.Net.Security.MobileAuthenticatedStream.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) [0x0000d] in <6b85ae33ded1428e932cb7ae66272042>:0    at Mono.Net.Security.MonoTlsStream.CreateStream (System.Byte[] buffer) [0x0007b] in <6b85ae33ded1428e932cb7ae66272042>:0    at System.Net.WebConnection.CreateStream (System.Net.HttpWebRequest request) [0x00073] in <6b85ae33ded1428e932cb7ae66272042>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00058] in <6b85ae33ded1428e932cb7ae66272042>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0041d] in <e82d510832964e7fadf0488ac21616d5>:0     --- End of inner exception stack trace ---   at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00478] in <e82d510832964e7fadf0488ac21616d5>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at CloudFlareUtilities.ClearanceHandler+<SendAsync>d__20.MoveNext () [0x0010c] in <16bb5fa9963142ceb54a189838ea6903>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <e82d510832964e7fadf0488ac21616d5>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Jackett.Common.Utils.Clients.HttpWebClient+<Run>d__7.MoveNext () [0x0045b] in <323994a4b3be4386abb088219eaa8d9b>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Jackett.Common.Utils.Clients.WebClient+<GetString>d__18.MoveNext () [0x0010b] in <323994a4b3be4386abb088219eaa8d9b>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Jackett.Common.Indexers.BaseWebIndexer+<RequestStringWithCookies>d__5.MoveNext () [0x000cb] in <323994a4b3be4386abb088219eaa8d9b>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Jackett.Common.Indexers.CardigannIndexer+<PerformQuery>d__28.MoveNext () [0x00825] in <323994a4b3be4386abb088219eaa8d9b>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__64.MoveNext () [0x00091] in <323994a4b3be4386abb088219eaa8d9b>:0     --- End of inner exception stack trace ---   at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__64.MoveNext () [0x000ce] in <323994a4b3be4386abb088219eaa8d9b>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x0006b] in <323994a4b3be4386abb088219eaa8d9b>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x000a3] in <323994a4b3be4386abb088219eaa8d9b>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Jackett.Controllers.IndexerApiController+<Test>d__12.MoveNext () [0x000d3] in <591b5032f8464d379da99f10a505640f>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Threading.Tasks.TaskHelpersExtensions+<CastToObject>d__0.MoveNext () [0x0005b] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__17`1[TResult].MoveNext () [0x001a7] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Web.Http.Controllers.ApiControllerActionInvoker+<InvokeActionAsyncCore>d__1.MoveNext () [0x000ab] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__17`1[TResult].MoveNext () [0x001a7] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x00091] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x001ad] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__5.MoveNext () [0x00103] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x00091] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x001ad] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__5.MoveNext () [0x00103] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Web.Http.Controllers.ActionFilterResult+<ExecuteAsync>d__5.MoveNext () [0x001af] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Web.Http.Filters.AuthorizationFilterAttribute+<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext () [0x000f3] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Web.Http.Controllers.ExceptionFilterResult+<ExecuteAsync>d__6.MoveNext () [0x00087] in <69abafc3d8434ab584330d77cc8d6da3>:0
--

**Comment by JKay85** [comment]
Please reopen ticket #2833 closed due to not having required details.

**Comment by kaso17** [comment]
most likely pirate bay is blocked by your ISP. please check that first.

**Comment by JKay85** [comment]
Some proxies are. It was my understanding that Jackett was designed to find the proxies that worked though? Or is this something that you need to change manually on a regular basis?

**Comment by kaso17** [comment]
you have to manually select a working one
