### ISSUE TITLE
Tracker request

### ISSUE THREAD

**Issue by poplolnman** [Jackett/Jackett#2836]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------
hi,
i was wondering if you could add https://tehconnection.me/ to the list? i have an invite just need an email to send it to.

**Comment by flightlevel** [comment]
Is this a fake @poplolnman ?
From what I last read, TC staff were still rebuilding

**Comment by poplolnman** [comment]
it was restarted by alastor the owner of nebulance. it is his own restart of it. if read on reddit it shows its legit, just not the most popular move: https://www.reddit.com/r/trackers/comments/888226/someone_made_a_new_tracker_named_tehconnection/

**Comment by kaso17** [comment]
@poplolnman please send the invite to kaso1717 -at- gmail.com and I'll have a look

**Comment by mgray88** [comment]
+1

**Comment by kaso17** [comment]
added via #2845
