### ISSUE TITLE
Pirateproxy.live provider returning 0 results

### ISSUE THREAD

**Issue by Naffles** [Jackett/Jackett#2837]
From looking through the debug logs, it appears to be a problem with not including '200' at the end of the search string... Copying the link below into browser does indeed return 0 results, but adding the 200 (same as doing a normal search through browser) shows results. 

Am i doing something wrong here??

**Jackett version**:  0.8.490.0
**Mono version** (if not using Windows):  5.8.0.108
-------------------------------

Apr 01, 2018 10:04:07 PM | Debug | WebClient(HttpWebClient).GetString(Url:https://pirateproxy.live/search/the%20walking%20dead/0/99/)
-- | -- | --

**Comment by kaso17** [comment]
fixed via 5b07e6424a9e393ce3dca1fa61a49060bc4813de and 93d1976a148c54e7a1a2acca896007ba86dbd744

**Comment by Naffles** [comment]
Thanks for quick actioning... but it seems your fix didnt work... still 0 results. Updated request:

WebClient(HttpWebClient).GetString(Url:https://pirateproxy.live/search/the%20walking%20dead/0/99/101102103104199201202203204205206207208209299301302303304305306399401402403404405406407408499501502503504505506599601602603604605699)

**Comment by Naffles** [comment]
@kaso17

**Comment by garfield69** [comment]
it should be noted that thepiratebay.org (official site) does return results when using `:https://thepiratebay.org/search/the%20walking%20dead/0/99/` so the OP's problem is a restricted to using `:https://pirateproxy.live`

**Comment by kaso17** [comment]
Multi category search was broken for the original mirror too.
Should be fixed for good for both versions via 01a43e04e19b58967b5f9476cdc128b10628790c

**Comment by Naffles** [comment]
Can confirm is now working as intended. Thanks mate
