### ISSUE TITLE
[BJ-Share] Titles not including release names, quality or resolution whatsoever on RSS Feed

### ISSUE THREAD

**Issue by LordeKamen** [Jackett/Jackett#2853]
I've read the code for the Bj-share and I've found some lines that seems to manipulate resolutions (replacing Full HD to 1080p, etc.), but on my qBitTorrent RSS feed, TV Shows and movies are only Shown as "Title - SXXEXX", without any important tags for matching the correct release that I'd like to download.
Hope someone can fix it!

**Comment by kaso17** [comment]
fixed via 5bfe0179b2dce5987a503dd5b718b8b506026064
