### ISSUE TITLE
[torrentleech]  An error occured while updating this indexer

### ISSUE THREAD

**Issue by ger43** [Jackett/Jackett#2859]
Hello,

This is the error I get when trying to add TorrentLeech to jackett. This is a fresh install on windows. If you need enhanced logs please let me know.

 **An error occured while updating this indexer
Found no results while trying to browse this tracker
Click here to open an issue on GitHub for this indexer.**

**Comment by dawtmaytrikx** [comment]
They just switched to the a new page layout.

**Comment by ger43** [comment]
Thanks, I just noticed that as well right after submitting this.

**Comment by nova-techies** [comment]
@dawtmaytrikx how does that change the API though?  Is the new page layout breaking how Jackett is talking to it?

**Comment by patsfacts** [comment]
Also fails if you attempt to use https://v4.torrentleech.org, as there has been a captcha added to the legacy login.

**Comment by nova-techies** [comment]
That works. Thanks for the heads up @patsfacts

**Comment by gmaster12** [comment]
I have the same issue, @patsfacts was saying that DOES NOT work. @nova-techies are you saying it does?

**Comment by ger43** [comment]
@gmaster12 using https://v4.torrentleech.org did not work for me.

**Comment by Magi1053** [comment]
When setting it up in Jackett, I've had it search successfully some times, and not work other times. However it is never able to retrieve the download link.

**Comment by vogstar** [comment]
I tried V4 and it search but doesn't give the download file so that your deludge can download the file. 

Hopefully their will be a fix soon.

**Comment by bearlikelion** [comment]
Can confirm it seems to be an issue with the CloudFlare protection.
Comparing the [CardigannIndexer](https://github.com/Jackett/Jackett/blob/01a43e04e19b58967b5f9476cdc128b10628790c/src/Jackett.Common/Indexers/CardigannIndexer.cs#L434) TL has no ClearanceURL.

This was caused by TL releasing their new v5 design.
Also v4 has a captcha breaking automated logs.

Looking forward to a fix.

**Comment by jlogan** [comment]
Is there no way to add a generic RSS feed to Jackett? That could be a possible workaround, no?

**Comment by vogstar** [comment]
I asked torrentleech Ana they said they don’t accept third party software :(. I’m hopeing the team can fix it as if not have to find a new torrent site

**Comment by vogstar** [comment]
on Version 4 you are able to search for the items when the download link doesn't work like in the last update where it was giving a 404 error.

**Comment by lkeazy** [comment]
I tried the v4 as well. similar results
sonarr logs show: Failed to download release from indexer, no longer available.
and NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound]

**Comment by hamishsw** [comment]
I am getting the same. Here is the beginning of the jacket log:

`CloudFlareUtilities.CloudFlareClearanceException: Clearance failed after 4 attempt(s).
  at CloudFlareUtilities.ClearanceHandler+<SendAsync>d__20.MoveNext () [0x00265] in <16bb5fa9963142ceb54a189838ea6903>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
  at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <e82d510832964e7fadf0488ac21616d5>:0 `

**Comment by flightlevel** [comment]
Thank you @marseneault
CloudFlareUtilities package has now been updated and Jackett fix is now in release v0.8.857
