### ISSUE TITLE
[Archetorrent] Error

### ISSUE THREAD

**Issue by doreybenjamin** [Jackett/Jackett#2867]
Hi when i test this tracker i have a error : 
An error occured while testing this indexer
Found no results while trying to browse this tracker

[archetorrent] Found no results while trying to browse this tracker (Test)

Regards,

**Comment by flightlevel** [comment]
What's so hard about providing some information?
You've opened three 3 issues with the same topic, all with no details

What version of Jackett are you using?

**Comment by doreybenjamin** [comment]
Hello,
i have this message when i click on test button: 
 An error occured while testing this indexer
Found no results while trying to browse this tracker
Click here to open an issue on GitHub for this indexer.

 Jackett Version 0.8.846.0

**Comment by titi69lpb** [comment]
Error for me :  An error occured while testing this indexer
Exception (archetorrent): Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu 67.215.8.26:443: Une erreur s'est produite lors de l'envoi de la demande.

**Comment by garfield69** [comment]
@titi69lpb  your ISP is blocking access to archetorrent, redirecting you to a black hole address 67.215.8.26.

@donfanning assuming that you are still having issues with this site, if you want help then:
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.
