### ISSUE TITLE
[torrentleech] Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by Speaktomenow** [Jackett/Jackett#2874]
TL launched a new interface, getting 0 results from what was a stable install. The log also mentions CloudFlare:

CloudFlareUtilities.CloudFlareClearanceException: Clearance failed after 4 attempt(s).

**Jackett version**:  Jackett 0.8.846.0 
**Mono version** 5.0.1

-------------------------------

**Comment by Speaktomenow** [comment]
That duplicate post had no info in it and was closed. So this might be the better spot for people to add content to. Re-opening.

**Comment by flightlevel** [comment]
Use the search function before opening issues

First page of the issues

![image](https://user-images.githubusercontent.com/9430010/38297935-38bf3266-3839-11e8-8e7e-1dca96ad218b.png)

Read those two issues, they are upgrading their website
