### ISSUE TITLE
Filelist search cat=19 not working

### ISSUE THREAD

**Issue by valentinolaru** [Jackett/Jackett#2887]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.846.0
**Mono version** (if not using Windows):  

-------------------------------

When manual searching for category:
 AddCategoryMapping(19, TorznabCatType.MoviesForeign, "Filme HD-RO");
no results are displayed, even though filelist has movies in that category.

Checked the log and no errors occurred

**Comment by kaso17** [comment]
use cat=100019 to get good results (filelist only supports searching with one category, no multi cat support)

**Comment by valentinolaru** [comment]
I didn't tell anything about multi cat support.
And I'm still saying you, no results are displayed for that category.. (cat=100019)
https://imgur.com/a/yjZSQ

**Comment by valentinolaru** [comment]
Can you please open the ticket again?

**Comment by kaso17** [comment]
you have to enable "IncludeRomanianReleases" in the indexer config

**Comment by valentinolaru** [comment]
Ok, that was the problem, shame on me. Thanks.
