### ISSUE TITLE
[torrentleech] Exception (torrentleech): Object reference not set to an instance of an object: Parse error (Config)

### ISSUE THREAD

**Issue by hamishsw** [Jackett/Jackett#2896]
When attempting to get around the torrentLeech V5 upgrade using the URL of their classic version instead (http://classic.torrentleech.org), I get this error...

Jackett.Common.IndexerException: Exception (torrentleech): Object reference not set to an instance of an object ---> System.Exception: Parse error ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Jackett.Common.Indexers.TorrentLeech+<PerformQuery>d__10.MoveNext () [0x0039c] in <b70f364cf6894a5287f7a029a4d3f09a>:0 

Jackett version: 0.8.490-6
Mono version: 5.8.0.108-11

-------------------------------

**Comment by QL0GIC** [comment]
use http://v4.torrentleech.org/ and it will work

**Comment by hamishsw** [comment]
thanks @QL0GIC I have tried using V4 and although this passes the jacket test, my Sonarr and Radarr instances are still getting download failures...as others have reported in #2882 and other similar issues...

**Comment by flightlevel** [comment]
Thank you @marseneault
CloudFlareUtilities package has now been updated and Jackett fix is now in release v0.8.857
