### ISSUE TITLE
Demonoid error on search from Sonarr

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#2899]
Hi, I already opened a post on Sonarr forum ([This one](https://forums.sonarr.tv/t/demonoid-search-error/18238)) but markus tell me that probably is a Jackett problem, so here I am

If I search via Jackett (manual search) no problem, I think, I said this because I got results, so
If I launch a manual search via Sonarr, on Sonarr log I see this
```
18-4-5 06:46:14.2|Debug|TorznabRssParser|Failed to parse Url https://www.demonoid.pw//genlb.php?genidx=Qk1QNU5lK25pWnQ1b1dVbG9LVkZndz09&genidy=ekJHVlJtZ2UzRzlrQndOL0pVK1phQT09, ignoring.

[v2.0.0.5169] System.ArgumentException: Uri didn't match expected pattern: https://www.demonoid.pw//genlb.php?genidx=Qk1QNU5lK25pWnQ1b1dVbG9LVkZndz09&genidy=ekJHVlJtZ2UzRzlrQndOL0pVK1phQT09
  at NzbDrone.Common.Http.HttpUri.Parse () [0x000a7] in <e9bf6d12f49c4ca8be6b4abc936d3de1>:0 
  at NzbDrone.Common.Http.HttpUri..ctor (System.String uri) [0x00016] in <e9bf6d12f49c4ca8be6b4abc936d3de1>:0 
  at NzbDrone.Core.Indexers.RssParser.ParseUrl (System.String value) [0x0001b] in <68a7c5155669439b99902bb57fd00d5c>:0
```

Markus tell that there's an extra slash in search but I don't know why, I searched inside code but is out of my capacity

What do you think?

**Comment by garfield69** [comment]
I'm using win7 Jackett 0.8.846 with Sonarr 2.0.0.5163
I've set up demonoid as my Sonarr indexer via Jackett, and I can find episodes without problems.
What version of Jackett are you  using. and if not on windows, what version of Mono?
If you are not on the latest versions of either, consider upgrading.

**Comment by edalex86** [comment]
Also demonoid search results have some categories missing in mapping i.e. 3010/
I just don't want to start new issue...

**Comment by Jorman** [comment]
@garfield69 
Jacket 0.8.846.0
mono is the latest on qnap (that works)

The problem is that I've some random problem, lol

See https://github.com/Jackett/Jackett/issues/2904

For now I'll monitor, maybe I've to install some? (I recently switched to entware, maybe some module are missing? python or whatever, but I don't think)

**Comment by flightlevel** [comment]
@Jorman your issue is Mono related, its multiple trackers that are a problem for you, track in #2904

**Comment by kaso17** [comment]
The link issue is fixed via 7d332aada4c5a8fee1ddf39677d73813ab365f74

3010 is not included in the categories because searching by it is not supported (only the parent category 3000 is). Search results might contain more specific results than just 3000.

**Comment by edalex86** [comment]
Search result contains only 3010 that's why I'm asking. My software tried to match all cat Ids from results by site's categories but failed on one item. You could try to search i.e. "arrow" on site yourself.

**Comment by kaso17** [comment]
Which software are you using?
It should accept sub categories of supported parent categories.

**Comment by Jorman** [comment]
I've to check https://github.com/Jackett/Jackett/issues/2904 but

For demonoid fix, I don't use 3010 for categories
On Sonarr side I've
`5030,5040,5000,100003`
On Radarr side I've
`2000,2010,2020,2030,2035,2040,2045,2050,2060,100001`

Maybe happen before, but I never noticed this error

**Comment by edalex86** [comment]
Mine sofware. I'm trying to add your service to MediaPortal media center. Where I could find all cat trees in API?
These leads me to lack of api docs. I didn't find endpoint except indexers and server/config. Demonoid part in indexers doesn't have 3010. Torznab feed has 3010 as subcat though but I don't want to call another url.

**Comment by kaso17** [comment]
Have a look at https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Models/TorznabCatType.generated.cs
for the default torznab categories (parent groups are defined at the end).
In general all IDs starting with the same digit are belonging to the same parent category (e.g. 3001-3999 are child of 3000).
