### ISSUE TITLE
T411 doens't work in Sonarr, getting "No results were returned from your indexer, please check your settings."

### ISSUE THREAD

**Issue by Snoflex** [Jackett/Jackett#29]
The issue was also present in the zone117x/Jackett.

I can add T411 just fine in Jackett, perform searches and all, but i can't add it to Sonarr.

Other trackers i tried work fine.

**Comment by raspdealer** [comment]
Weird. Mine is working fine.

**Comment by Snoflex** [comment]
Did you change any parameters in sonarr or jackett ? 

I also saw your post about the query needing some changes, did you make yours work that way?

**Comment by raspdealer** [comment]
My T411 search is working fine. Since the first day I used it.
My issue is about the RSS feed that is not retrieved good informations this is why I made the mapping for dev.

Have you tried to remove the tracker completely from jackett and restart completely jackett?

**Comment by Snoflex** [comment]
It's on a two days fresh Windows 10 installation with both sonarr and jackett having been installed yesterday.

One thing I noticed is that the manual search in jackett using t411 doesn't give me any recent results. I don't know if that's linked to my issue though

**Comment by Snoflex** [comment]
i actually think my categories aren't mapped correctly but i can't find a way to edit them. I would need to change them in Jackett and then in Sonarr.

**Comment by Snoflex** [comment]
![capture](https://cloud.githubusercontent.com/assets/15156037/11037809/140f9fe2-8700-11e5-9087-b1abebd1b943.PNG)
Here is a screenshot of my configuration, and the error i'm getting. I am missing anything?

**Comment by raspdealer** [comment]
Disable RSS, it's not implemented.
And try again.

**Comment by Snoflex** [comment]
I tried and it still gives me the same error, i added it to sonarr anyway but it doesn't find anything, and when i do a manual search in jackett i only get very old results like so:

![old results](https://cloud.githubusercontent.com/assets/15156037/11039577/a1b85476-8708-11e5-9de4-a9cf95349e7a.PNG)

**Comment by raspdealer** [comment]
Ok. We will need @flightlevel here.
It looks like related to this.
https://github.com/Jackett/Jackett/issues/19

**Comment by Snoflex** [comment]
Allright then, i'll wait for the dev to take a look at it

Thx man !

**Comment by raspdealer** [comment]
https://github.com/Jackett/Jackett/pull/49

**Comment by flightlevel** [comment]
@Snoflex 
This is an easy one.
Look at your Sonarr settings and you are only searching categories 5030, 5040.
http://newznab.readthedocs.org/en/latest/misc/api/#predefined-categories
This means you're only wanting files in the TVSD or TVHD category. But if you look at your results from Jackett all the returned results were in category TV. 
So if you add 5000 to your categories in Sonarr, you should now start getting results.

**Comment by Snoflex** [comment]
Thanks @flightlevel ! Manual search is now working, unfortunately RSS Sync doesn't work but from what i understood it is related to this #19 .

Thx again

**Comment by flightlevel** [comment]
t411 no longer supported
