### ISSUE TITLE
Error got NotImplemented/InternalServerError

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#2904]
With latest Jackett (0.8.846.0)

I've a lot of error during a "test all"
Here the log, hope can help
http://s000.tinyupload.com/index.php?file_id=25624854828410073886

**Comment by kaso17** [comment]
The NotImplemented/InternalServerError is an error triggered by the libcurl client which is deprecated (usually its caused due to a TLS/certificate issue).
Use a mono version with btls support and don't use the "-c libcurl" command line option to fix this.

**Comment by flightlevel** [comment]
https://forum.qnap.com/viewtopic.php?f=320&t=116660&sid=e3c0aa109d90169c093dc572f615a922&start=105
Instructions here @Jorman Looks like someone has asked qpkg maintainer to fix

**Comment by Jorman** [comment]
Right! after fix all working like a charm!
tnx guys I forgot the fix!!!
