### ISSUE TITLE
[YGG] Anime TvShows Categorie

### ISSUE THREAD

**Issue by lilp69** [Jackett/Jackett#2913]
Hello,
I'm using Jackett with Sonarr and YGG, it's working well for TvShows.
But never found any Anime TvShows

In Jackett, when I run a search with 5070, I found my Anime TvShows like Simpson...
But never any results in Sonarr.

Regards

**Comment by lilp69** [comment]
Here it's the log : 18-4-9 10:37:01.0|Info|NzbSearchService|Searching 2 indexers for [The Simpsons : S28E18]
18-4-9 10:37:07.2|Info|DownloadDecisionMaker|No results found
18-4-9 10:40:39.8|Info|RssSyncService|Starting RSS Sync
18-4-9 10:40:42.2|Warn|Torznab|Indexer Torrent9 rss sync didn't cover the period between 09/04/2018 08:25:10 and 09/04/2018 08:40:42 UTC. Search may be required.
18-4-9 10:40:42.2|Info|DownloadDecisionMaker|Processing 38 releases

**Comment by kaso17** [comment]
please increase the debug level, the log doesn't contain the request urls used to search

**Comment by lilp69** [comment]
HTTP Error - Res: [GET] https://xxx.xxx.xxx/jackett/api/v2.0/indexers/yggtorrent/results/torznab/api?t=tvsearch&cat=5030,5040,5070&extended=1&apikey=(removed)&offset=0&limit=100: 500.InternalServerError
{
  "result": "error",
  "error": "Exception (yggtorrent): Connection reset by peer: An error occurred while sending the request",
  "stacktrace": "  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__64.MoveNext () [0x000c6] in C:\\projects\\jackett\\src\\Jackett.Common\\Indexers\\BaseIndexer.cs:256 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x00024] in C:\\projects\\jackett\\src\\Jackett.Common\\Indexers\\BaseIndexer.cs:719 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at Jackett.Controllers.ResultsController+<Torznab>d__14.MoveNext () [0x003a6] in <43761907f9f24f4f9a3a50dd7d7d22c3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Threading.Tasks.TaskHelpersExtensions+<CastToObject>d__1`1[T].MoveNext () [0x0005b] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__17`1[TResult].MoveNext () [0x001a7] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Web.Http.Controllers.ApiControllerActionInvoker+<InvokeActionAsyncCore>d__1.MoveNext () [0x000ab] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__17`1[TResult].MoveNext () [0x001a7] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x00091] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x001ad] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__5.MoveNext () [0x00103] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x00091] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x001ad] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__5.MoveNext () [0x00103] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Web.Http.Controllers.ActionFilterResult+<ExecuteAsync>d__5.MoveNext () [0x001af] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Web.Http.Filters.AuthorizationFilterAttribute+<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext () [0x000f3] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Web.Http.Controllers.ExceptionFilterResult+<ExecuteAsync>d__6.MoveNext () [0x00087] in <69abafc3d8434ab584330d77cc8d6da3>:0 ",
  "innerstacktrace": "  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00478] in <1b4ca1e290fd4a81978c5860ac6ff8f4>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at CloudFlareUtilities.ClearanceHandler+<SendAsync>d__20.MoveNext () [0x0010c] in <d0213015414e4bf286b46bc1ee77bd72>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <1b4ca1e290fd4a81978c5860ac6ff8f4>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at Jackett.Common.Utils.Clients.HttpWebClient+<Run>d__7.MoveNext () [0x0040e] in C:\\projects\\jackett\\src\\Jackett.Common\\Utils\\Clients\\HttpWebClient.cs:210 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at Jackett.Common.Utils.Clients.WebClient+<GetString>d__18.MoveNext () [0x000c1] in C:\\projects\\jackett\\src\\Jackett.Common\\Utils\\Clients\\WebClient.cs:114 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at Jackett.Common.Indexers.BaseWebIndexer+<RequestStringWithCookies>d__5.MoveNext () [0x00084] in C:\\projects\\jackett\\src\\Jackett.Common\\Indexers\\BaseIndexer.cs:350 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at Jackett.Common.Indexers.CardigannIndexer+<PerformQuery>d__29.MoveNext () [0x007f4] in C:\\projects\\jackett\\src\\Jackett.Common\\Indexers\\CardigannIndexer.cs:1209 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 \n  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__64.MoveNext () [0x00047] in C:\\projects\\jackett\\src\\Jackett.Common\\Indexers\\BaseIndexer.cs:240 "
}

**Comment by kaso17** [comment]
the request link is working fine for me.
`Connection reset by peer: An error occurred while sending the request` indicates a connectivity issue (ygg server down, ISP blocking it, ...)

**Comment by lilp69** [comment]
I've access at YGG with another TV Shows (TWD...)

**Comment by mrhydejc** [comment]
it works for me with The Simpsons S28e19 from sonarr

**Comment by garfield69** [comment]
the simpsons is not ANIME so you're not going to find this tv series under that category on ygg..
