### ISSUE TITLE
[iptorrents] Exception

### ISSUE THREAD

**Issue by cjamesdesigner** [Jackett/Jackett#2915]
An error occured while updating this indexer
Exception (iptorrents): Please go to https://iptorrents.eu/settings.php and change the "Torrents - Category column" option to "Icons". Wait a minute (cache) and then try again.: Parse error

I have done this and still can't get iptorrents to work after updating Jackett to the latest. Do I need to clear cache somehow?

**Comment by kaso17** [comment]
If it's still a problem please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by cjamesdesigner** [comment]
https://pastebin.com/aRyjkYyJ

**Comment by kaso17** [comment]
the settings change is not yet active (iptorrents might have increased their caching time), please keep trying (you can also check the iptorrents search results, the first column should be an icon instead of just text).

**Comment by cjamesdesigner** [comment]
okay...thank you
