### ISSUE TITLE
Returning results it shouldn't for showRSS?

### ISSUE THREAD

**Issue by jriker1** [Jackett/Jackett#2922]
I am trying to add showRSS to Jackett and it seems to "add", but not sure it's working right.  From what I read on showrss I just added one show and they mention about no results being available until the show airs again.  So I put the feed URL in and get:

`<rss version="2.0">
<channel>
<title>showRSS personal feed</title>
<link>http://showrss.info</link>
<ttl>30</ttl>
<description>showRSS personal feed</description>
</channel>
</rss>`

So technically nothing shows.  But when I do a search in Jackett and limit it to showrss with no content, it returns a bunch of show entries tied to showrss.  

Is something wrong with Jackett and it's also using one of my other indexers even though it says showRSS for the Tracker name?

**Comment by kaso17** [comment]
Only use the default site URL.
Jackett doesn't support the personal feed.

**Comment by jriker1** [comment]
Thanks.  Do we know what the default site URL is anymore?  The one I used before doesn't work anymore and they don't advertise it if it's there anymore on my user page anyway.

Thanks.

JR

**Comment by kaso17** [comment]
https://showrss.info/
