### ISSUE TITLE
[bitmetv] Login failed! (Config)

### ISSUE THREAD

**Issue by ECKoBASE** [Jackett/Jackett#2927]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  Using Synology DS2415+

-------------------------------

**Comment by flightlevel** [comment]
Ensure that you have the 'Force SSL' option set to 'yes' in your profile on the BitMeTv webpage.

If that doesn't work, a full enhanced log must be included

**Comment by ECKoBASE** [comment]
Tried that, didn't work. I Restarted the Jackett App, Worked.
