### ISSUE TITLE
PhxBit : "Error downloading"

### ISSUE THREAD

**Issue by itdaboyz** [Jackett/Jackett#293]
Hi,

I'm trying PhxBit but I have this error in Jackett when trying to download a torrent via manual search or cached release (the search is working : releases are shown) : `Error downloading phxbit https://phxbit.com/get.php?action=torrent&id=XXX&passkey=XXX`

In Sonarr, the error when trying to add a download is : 
```
NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://localhost:9117/dl/phxbit/pjzv3qwe2qtd0nst9cl4w6nvfzwlq1bo?path=aHR0cHM6Ly9waHhiaXQuY29tL2dldC5waHA_YWN0aW9uPXRvcnJlbnQmaWQ9NzQmcGFzc2tleT1hNjU1ZjNhYzdmY2NhNGY4Mjg1NTc4YWI2MzUxOTYzMw2&file=The.Flash.2014.S02E01.VOSTFR.1080p.WEB-DL.DD5.1.H264-PHX.torrent]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x0017c] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\HttpClient.cs:106 
  at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\HttpClient.cs:189 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String torrentUrl) [0x00024] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\TorrentClientBase.cs:106
```

Any ideas ?

**Comment by raspdealer** [comment]
Same in CouchPotato.

[hpotato.core.plugins.base] Opening url: get http://192.168.1.116:9118/dl/phxbit/ig9y8gjhhq1u1ux9d7he25q53xghnb5b?path=aHR0cHM6Ly9waHhiaXQuY29tL2dldC5waHA_YWN0aW9uPXRvcnJlbnQmaWQ9NjQzNCZwYXNza2V5PWQ1YTgyYTEyOWIzZDdlMDMxMWZhZjkxMGEyMTViNTNm0&file=The.Devils.Advocate.1997.UNRATED.DC.MULTi.720p.BluRay.x264-KLI.torrent, data: []
04-02 19:20:55 ERROR
[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last): File "/opt/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 205, in download return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False) File "/opt/CouchPotatoServer/couchpotato/core/plugins/base.py", line 226, in urlopen response.raise_for_status() File "/opt/CouchPotatoServer/libs/requests/models.py", line 837, in raise_for_status raise HTTPError(http_error_msg, response=self) HTTPError: 404 Client Error: Not Found for url: http://192.168.1.116:9118/dl/phxbit/ig9y8gjhhq1u1ux9d7he25q53xghnb5b?path=aHR0cHM6Ly9waHhiaXQuY29tL2dldC5waHA_YWN0aW9uPXRvcnJlbnQmaWQ9NjQzNCZwYXNza2V5PWQ1YTgyYTEyOWIzZDdlMDMxMWZhZjkxMGEyMTViNTNm0&file=The.Devils.Advocate.1997.UNRATED.DC.MULTi.720p.BluRay.x264-KLI.torrent

**Comment by JigSawFr** [comment]
I will check ASAP ! Thanks for report.

**Comment by maxcore** [comment]
oups yes same error too i have not try to download before i say the plug in work my mistake hehe

**Comment by JigSawFr** [comment]
Tested, same bug, i will investigate now.

**Comment by JigSawFr** [comment]
Error found, tested and working now, sorry guys ! I will submit fix ASAP

**Comment by zorgade** [comment]
I have an another problem with Phxbit, i can't snatch a torrent on couchpotato, i have this error:
`04-03 15:10:21 ERROR
[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last): File "/home/zorgade/.couchpotato/couchpotato/core/media/_base/providers/base.py", line 205, in download return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False) File "/home/zorgade/.couchpotato/couchpotato/core/plugins/base.py", line 226, in urlopen response.raise_for_status() File "/home/zorgade/.couchpotato/libs/requests/models.py", line 837, in raise_for_status raise HTTPError(http_error_msg, response=self) HTTPError: 404 Client Error: Not Found for url: http://IP:9117/dl/phxbit/APIKey?path=aHR0cHM6Ly9waHhiaXQuY29tL2dldC5waHA_YWN0aW9uPXRvcnJlbnQmaWQ9MTQ3MTUmcGFzc2tleT00NzAxOTBjY2Y1NDQxNDBhMjlkN2UzYzEyNDY1MzYzZA2&file=The.Rover.2014.MULTi.1080p.BluRay.x264-LOST.torrent` 

Thanks you for help

**Comment by JigSawFr** [comment]
Solved by PR #294.
Will merge ASAP.

**Comment by Bybou** [comment]
It works fine now.
Thks @JigSawFr

**Comment by nic0dk** [comment]
hi same problem with danishbits via Sonarr :) can you fix that ?
16-11-30 16:32:41.2|Error|Deluge|Downloading torrent file for episode 'The.Walking.Dead.S07E06.Custom.DKsubs.720p.HDTV.X264-SUBSTANCE' failed (http://192.168.100.3:9117/dl/danishbits/jcidykjxulz6pk639xgkrey4gz6t0hqz?path=aHR0cHM6Ly9kYW5pc2hiaXRzLm9yZy90b3JyZW50cy5waHAvVGhlLldhbGtpbmcuRGVhZC5TMDdFMDYuQ3VzdG9tLkRLc3Vicy43MjBwLkhEVFYuWDI2NC1TVUJTVEFOQ0UudG9ycmVudC8_YWN0aW9uPWRvd25sb2FkJmF1dGhrZXk9JnRvcnJlbnRfcGFzcz0maWQ90&file=The.Walking.Dead.S07E06.Custom.DKsubs.720p.HDTV.X264-SUBSTANCE.torrent)

[v2.0.0.4409] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://192.168.100.3:9117/dl/danishbits/jcidykjxulz6pk639xgkrey4gz6t0hqz?path=aHR0cHM6Ly9kYW5pc2hiaXRzLm9yZy90b3JyZW50cy5waHAvVGhlLldhbGtpbmcuRGVhZC5TMDdFMDYuQ3VzdG9tLkRLc3Vicy43MjBwLkhEVFYuWDI2NC1TVUJTVEFOQ0UudG9ycmVudC8_YWN0aW9uPWRvd25sb2FkJmF1dGhrZXk9JnRvcnJlbnRfcGFzcz0maWQ90&file=The.Walking.Dead.S07E06.Custom.DKsubs.720p.HDTV.X264-SUBSTANCE.torrent]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x001a2] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\HttpClient.cs:105 
  at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\HttpClient.cs:188 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String torrentUrl) [0x00024] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\TorrentClientBase.cs:146
