### ISSUE TITLE
[thepiratebay] Wrong search results

### ISSUE THREAD

**Issue by edalex86** [Jackett/Jackett#2930]
Hi, tpb indexer returns irrelevant results.
Url from log:
https://thepiratebay.org/search/formula/0/99/101,102,103,104,199,201,202,203,204,205,206,207,208,209,299,301,302,303,304,305,306,399,401,402,403,404,405,406,407,408,499,501,502,503,504,505,506,599,601,602,603,604,605,699
Default url from site search (looks like sorted by seeds desc)
https://thepiratebay.org/search/Formula/0/99/0
Link with main categories is still working fine
https://thepiratebay.org/search/formula/0/99/100,200,300,400,500,600
Either categories are wrong or site doesn't like such categories listing.
Btw, if we add 100,200,300,400,500,600 to jackett url results look fine I think:
https://thepiratebay.org/search/formula/0/99/100,200,300,400,500,600,101,102,103,104,199,201,202,203,204,205,206,207,208,209,299,301,302,303,304,305,306,399,401,402,403,404,405,406,407,408,499,501,502,503,504,505,506,599,601,602,603,604,605,699
It's still sorted by seeders but anyway.
Also if we change 99 in link to 3 we will have results  sorted by date desc  which are latest results I think.
So what do you think about problems in url and sorting by date?
**Jackett version**:  0.8.864.0

-------------------------------

**Comment by kaso17** [comment]
fixed via e6834990ec8264f63143b8e5f9f67d92713aaf8b
