### ISSUE TITLE
[torrentleech] Exception (torrentleech): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Parse error (Config)

### ISSUE THREAD

**Issue by topcat30** [Jackett/Jackett#2940]
When trying to add the Torrentleech indexer I get the exception error:
[torrentleech] Exception (torrentleech): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Parse error (Config)

Issue exists on the latest version v0.8.870 and v0.8.857

**Comment by garfield69** [comment]
Works for me on my win7 Jackett 0.8.870.

Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.

**Comment by topcat30** [comment]
I got it working by changing the url back to www.torrentleech.org
