### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://yggtorrent.is/ using form selector form[action$=

### ISSUE THREAD

**Issue by xfouloux** [Jackett/Jackett#2951]
Hi,

yggtorrent changed their website, and now the login form selector is not working because the form is on a modal on the index page, and the form elements are sent to /user/login (ajax query)

also url got changed to https://yggtorrent.is/ 

Is there any way to update this please ?

Regards.

**Comment by garfield69** [comment]
what version of Jackett are you on?
yggtorrent works for  me on v0.8.870. 
So upgrade to that version and try again.

**Comment by xfouloux** [comment]
I'm on version 0.8.881.0

**Comment by garfield69** [comment]
kaso17 in #2830 reported:
>I'm still running into timeouts/server errors causing test errors. But the definition itself is working fine in the latest version.

@xfouloux: if you are consistently unable to login to yggtorrent when using 0.8.881 then there are a few things you could check/try.
1. check that your jackett/definitions/yggtorrent.yml is the same code as the latest in github, you may have somehow missed out on an update?!.
2. try deleting your jackett/indexers/yggtorrent.json and *json.bak and recycling jackett. then try adding yggtorrent afresh using the dashboard.
3. login to yggtorrent directly and check you have no outstanding alerts (such as a request to update your password).
4. if still no joy, then please provide the full **enhanced** log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.
Also, what platform are you running jackett on, and if not windows, what version of mono are you on?

**Comment by ralex** [comment]
Removing Jackett/Indexers/yggtorrent.json.bak and restarting jackett service helped in my case.

**Comment by xfouloux** [comment]
Hi,

still no luck, jackett updated my definition and yggtorrent is not working anymore after update.

I did everything you said and it's still not working so here is the enhanced log
[enhancedlogjackett.txt](https://github.com/Jackett/Jackett/files/1926559/enhancedlogjackett.txt)

but when I change the definition file with my pull request it is working ok => #2952 

Jackett Version 0.8.898.0

mono -V
Mono JIT compiler version 5.0.1.1 (2017-02/5077205 Thu May 25 09:19:47 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian

**Comment by kaso17** [comment]
2018-04-19 05:06:49.7896 Debug WebClient(HttpWebClient).GetString(Url:https://yggtorrent.is/user/login) 
2018-04-19 05:06:50.5804 Debug WebClient(HttpWebClient): Returning Unauthorized =>  

make sure your credentials are working

**Comment by kaso17** [comment]
@xfouloux garfield is right.
Your pull requests essentially disabled the login test making it looks like it's working but AFAIK a working login is needed in order to download the torrents.
