### ISSUE TITLE
[Multiple] Exception (1337x / EZTV): A task was canceled.: A task was canceled. (Test)

### ISSUE THREAD

**Issue by darklightindigo** [Jackett/Jackett#2954]
Multiple trackers, observed with 1337x and EZTV so far.
Including .json and .json.bak (prior to update around 2018-04-08) for both trackers for further analysis.
AniRena tracker had no changes, and still works fine.
Initial review of Definitions shows no changes in the past several months, but this may be related to a faulty call causing a regression elsewhere.

Jackett Version 0.8.743.0
Mono JIT compiler version 5.10.1.20 (tarball Thu Mar 29 11:55:26 UTC 2018)

-------------------------------
[log.txt](https://github.com/Jackett/Jackett/files/1897621/log.txt)
~~1337x.json.bak.txt~~
~~1337x.json.txt~~
~~eztv.json.bak.txt~~
~~eztv.json.txt~~
[edit] removed for security. there is nothing useful in them for this case anyway.

**Comment by garfield69** [comment]
the log you provided is the regular log.
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.

**Comment by darklightindigo** [comment]
My apologies, I thought I had enhanced logging turned on.
As for the details, this is a generic account on a dedicated system behind multiple firewalls.
If I have to waiver the bloody thing, I will, but that seems a bit much to require to get a log. ;)
[log.txt](https://github.com/Jackett/Jackett/files/1899043/log.txt)

**Comment by kaso17** [comment]
It's still not an enhanced log.
"A task was canceled" usually means that the connection/request took to long (timeout).
Your firewalls/ISP might block eztv/1337x, please check that too.

**Comment by darklightindigo** [comment]
Very strange, it is indeed timing out from that line.
But then, shouldn't the site also not load?
I just noticed, it seems the IPv6 is being attempted, perhaps this is related.
