### ISSUE TITLE
Change upgrader check to not downgrade

### ISSUE THREAD

**Issue by biship** [Jackett/Jackett#2955]
**Jackett version**:  v0.8.872
-------------------------------
Can you please change the version check to not downgrade us if we are running a dev release?

Apr 11, 2018 08:38:39 AM | Info | New release found.  Current: v0.8.872 New: v0.8.870
-- | -- | --

And then it downloads and installed 0.870 :(
I have "Update to pre-release" enabled as sometimes you release a version before I manually install it.

**Comment by kaso17** [comment]
I personally like the simple version (if current version != latest version) check used by the updater over a more complicated and error prone version string comparison. If you update to an unofficial draft version I would suggest to disable auto updates until it's released officially.

@flightlevel what's your opinion regarding this?

**Comment by biship** [comment]
I use System.Version to do this in my code, which I believe to be numeric comparisons.
https://msdn.microsoft.com/en-us/library/system.version(v=vs.110).aspx

**Comment by flightlevel** [comment]
@biship Seriously, how often are you installing pull requests? Jackett does very regular releases. If you want to run pull request versions, then turn off auto updater.
As far as I know you are the only person running pull request builds and we shouldn't change logic to suit one person.
!= logic is useful in case we stuff up a release. It allows us to kill the release, work out what's wrong and then put out a new one
