### ISSUE TITLE
[FIXED] [FreedomHD]  An error occured while testing this indexer Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by ztheoz** [Jackett/Jackett#2956]
Hi,
I've got an issue with Jackett and FreedomHD: I always have the problem "An error occured while testing this indexer : Found no results while trying to browse this tracker."
The only way I have to fix this issue for 3 min is just to open the settings of FreedomHD, change nothing and just click Okay. The tracker is then accessible for 3 min, and then the bug restarts.

Here are the logs of the error : https://pastebin.com/SA1PJ20c
**Jackett version**:   0.8.857.0 
**Mono version** (if not using Windows):  5.8.0.127

If anyone knows how to fix this forever, it would be awesome.

**Comment by kaso17** [comment]
Please provide a full enhanced log showing a full 3 minute cycle (reconfigure/login to fix it, working test, failed test). Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by ztheoz** [comment]
Okay, I've done that. But it seems to be random, as this time it took almost an hour to have the bug back.
There is the full log, with the reconfiguration at the top and the bug at the end:
https://ufile.io/rioxu
(It's too big to go on pastbin)

**Comment by ztheoz** [comment]
Okay, I think that I know how to reproduce : the bug appeared after a reboot of Jackett. I don't understand why only freedom-hd...

**Comment by kaso17** [comment]
the GUI enhanced logging option is reset on jackett restart, so the interesting part is missing from the log. Please either enable enhanced logging immediately after restarting jackett (before doing the search). Or start jackett with the -t command line option to enable it.

**Comment by ztheoz** [comment]
Ok, I've uploaded those logs here : https://pastebin.com/F2TbMHc3
Thanks!

**Comment by kaso17** [comment]
According to the log the search request returns an empty document
```
WebClient(HttpWebClient).GetString(Url:http://freedom-paradise.eu/torrents-search.php?search=&incldead=1)
WebClient(HttpWebClient): Returning OK =>
```
In case of an invalid login it should return a redirect to account-login.php.
To me it looks like their server is simply overloaded causing the empty document.
Do you really have to reconfigure the indexer once this happens? I would have expected that it should start working automatically once their server returns to normal state.

**Comment by ztheoz** [comment]
Well, I'm pretty sure that is not the case, because it seems weird to me that instantly after reconfiguring the tracker the servers returns to normal state, I think that I've tried this too many times for a coincidence.
But I'm going to make other tests, I've installed a docker version to run them on two separate installations. But I'm not going to do them now, because the site was super laggy today (but as it's only todays I'm not sure that it's an overload).

**Comment by ztheoz** [comment]
OK so the today's lags are done, it was a server update. But it's not a server overload, because when I first start both jackett installations I can't connect to the tracker, but as soon as I reconfigure it, it starts working on one installation, but not the other. I have to make the reconfiguration on it too to make it working.
I'll send new logs tomorrow (French time) if you want, as there were maybe different because of the maintenance.

**Comment by kaso17** [comment]
5e00b2ec3360a6cad2d9e6bee8a60b3aebb48475 should result in a relogin in case of an empty page. Please test it and report.

**Comment by ztheoz** [comment]
Hi, thanks for your suggestion. I've tried this, but the bug is still there. 
Here are new logs: https://pastebin.com/CHRctJSY
Thanks!

**Comment by ztheoz** [comment]
I think the modification is working!
Instead of doing the modification manually (what I've done the first time), I've just downloaded the full file with the modification, and it's working now!
I'm going to do some other tests, and I'll mark that issue as solved if all will be ok.
Thanks!

**Comment by ztheoz** [comment]
Okay, I confirm that the solution is working properly.
Thanks!

**Comment by garfield69** [comment]
@ztheoz  are you able to access http://freedom-paradise.eu/, i've been getting a timeout for the last month.
broken, gone or moved to a new domain?

**Comment by ztheoz** [comment]
> @ztheoz are you able to access http://freedom-paradise.eu/, i've been getting a timeout for the last month.
> broken, gone or moved to a new domain?

Nope, the tracker seems to be closed, as it has been unreachable for more than a month now...
