### ISSUE TITLE
[kickasstorrent-kathow] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by jriker1** [Jackett/Jackett#2957]
Using latest version of Jackett on Windows.  I think the torrent site is returning NordVPN messages even though I'm on PIA and interfering with results so get zero results.  This is the kat.li site.  Site comes up but when you search it comes up with that NordVPN information.

JR

**Comment by jriker1** [comment]
I partly agree, however how can this be a duplicate of a closed issue?  Can't be closed and still broken.  Saw references to NordVPN in the content that individual sent but not sure if they were coming to the same conclusions.  Plus it was closed!!! :)

JR

**Comment by garfield69** [comment]
this is not Jackett's fault. If you navigate directly to https://kat.li/new/ on your chrome browser you will see that currently kat.li is returning no results.
Regular searches using keywords work.
I expect the site to fix this eventually.
