### ISSUE TITLE
[tvchaosuk] Exception (tvchaosuk): String was not recognized as a valid DateTime.: Parse error (Config)

### ISSUE THREAD

**Issue by UKQuinny** [Jackett/Jackett#2961]
I recently changed my password on TVChaos and now i get the error in the tittle when i try to add the tracker to Jacket.

**Comment by garfield69** [comment]
what version of Jackett are you on?
there was a fix for tvchaosuk in v0.8.881

**Comment by UKQuinny** [comment]
Thanks for the quick reply.
 
Jackett Version 0.8.870.0

Im clicking the update button in the Jackett Configuration section and nothing is happening.

**Comment by UKQuinny** [comment]
All sorted, cheers
