### ISSUE TITLE
Filelist Not Working

### ISSUE THREAD

**Issue by antigravity83** [Jackett/Jackett#2962]
Jackett Version 0.8.870.0
Mono Version 5.10.1.20

Can't connect to Filelist anymore

Logs: https://gist.github.com/antigravity83/81ea69cf9fb7755e755a5c78be21bb89

**Comment by garfield69** [comment]
the sitelink for filelist was updated in jackett 0.8.881

**Comment by antigravity83** [comment]
Thanks- upgrade in GUI mustn't have been working. Manually upgraded and working now. Thanks!
