### ISSUE TITLE
No results when searching from sonarr

### ISSUE THREAD

**Issue by mephasor** [Jackett/Jackett#2967]
**Jackett version**:  0.8.881.0
**Mono version** (if not using Windows):  5.10.1.20

-------------------------------

**Log**: [log.txt](https://github.com/Jackett/Jackett/files/1907504/log.txt)

I am having issues with some shows. I went through the usual process of trying to figure out the problem and did the following: 

- check if the categories are correct (they are, at some point I added all of them)
- Check if using the request 'by hand' yields results (yes, see below)
- Update mono version

After going through the logs of all actors involved, I think I could pinpoint the issue to the following lines:
![image](https://user-images.githubusercontent.com/3739250/38737158-c07e54da-3f04-11e8-848d-78ca1cffc883.png)

It seems the %20 codes are not transformed to spaces which creates an ugly search string. 

Further, I wondered why some titles work and others don't. It seems this error happens if the title has at least 3 words in it. Shows with less than 3 words in the title seem to be working properly. I might be wrong here. Maybe some 'the's are being ignored when creating the search query. 

Any idea for a quick workaround? 
Thanks for all the work you put into this

**Comment by kaso17** [comment]
Yes, the original request is already wrong (double URL escaped keywords)
`http://localhost:9117/api/v2.0/indexers/iptorrents/results/torznab/api?t=tvsearch[...]&q=Better%2520Call%2520Saul&season=1`

Are you running the latest version of sonarr?
If you do please provide the sonarr log file of the search.

**Comment by mephasor** [comment]
It seems so. I am on the master branch of sonarr. Just verified, I am using the release from March 18. 
Here the log files. I deleted logs right before running the test, so it should appear right at the beginning. 

Hope it helps: 
[sonarr.trace.20.txt](https://github.com/Jackett/Jackett/files/1909983/sonarr.trace.20.txt)
[sonarr.debug.8.txt](https://github.com/Jackett/Jackett/files/1909984/sonarr.debug.8.txt)

**Comment by mephasor** [comment]
Interesting. I played around with it a little more. After removing the indexer from sonarr and adding it back, it seems to work just fine now. Not sure why

**Comment by SmaginPV** [comment]
Same issue with me.
