### ISSUE TITLE
[HDBits] Parsing fails and 404 on download attempt

### ISSUE THREAD

**Issue by concernedUser21** [Jackett/Jackett#2968]
**Jackett version**:  0.8.881.0
**Mono version** (if not using Windows):  N/A (Using Windows 10)

-------------------------------
I am experiencing and issue where the XML that is returned by HDBits is not getting parsed correctly and when jackett attempts to download the torrent, it throws a 404.  This happens for both API calls to jackett for specific torrents and when manually searching and trying to use the Jackett UI directly.  

The log I have is for a random torrent just to illustrate the issue.  This has been happening for a few weeks now (with a continuously updating jackett client) but I just got around to creating a ticket.  I very quickly tried to change a couple of the indices that the parser was looking for, but I'm not super familiar with it and it didn't yield any positive results.  

Happy to provide any additional information.

Thanks!

[log-scrubbed.txt](https://github.com/Jackett/Jackett/files/1908352/log-scrubbed.txt)

**Comment by edalex86** [comment]
Honestly, hdbits indexer should be changed from scrapping to api. Link to torrent file from log is fine fo me

**Comment by kaso17** [comment]
e947059da1ac1663982f3edd81ed21e2bd8ff123 might fix the download issue.
If it has an API it should be used indeed, unfortunately I'm not a member and can't fix it.

**Comment by kaso17** [comment]
is this working now?

**Comment by concernedUser21** [comment]
Thank you @kaso17 , working now!
