### ISSUE TITLE
AlphaRatio doesn't support daily searches containing periods

### ISSUE THREAD

**Issue by adampetrovic** [Jackett/Jackett#2971]
Jackett is using AlphaRatio's /ajax.php endpoint to search for new releases, however often daily shows aren't being returned properly. When I search using the same string on AlphaRatio's website, it returns results as expected. For example:

https://alpharatio.cc/ajax.php?action=browse&order_by=time&order_way=desc&searchstr=Conan+2018.04.11&filter_cat[1]=1&filter_cat[3]=1&filter_cat[4]=1&filter_cat[2]=1&filter_cat[5]=1

`{
"status": "success",
"response": {
"results": [],
"youMightLike": []
}
}`

**versus**

https://alpharatio.cc/torrents.php?searchstr=Conan+2018.04.11 - **[Screenshot](https://i.imgur.com/Y1PWIJV.png)**

If I replace the periods with spaces in the request to /ajax.php the api returns results as expected.

**Jackett version**:  v0.8.886
**Mono version** (if not using Windows):  5.10.1.20 (tarball Thu Mar 29 10:44:58 UTC 2018) 

-------------------------------

**Comment by kaso17** [comment]
seems like the alpharatio API can't handle dots in the search string.
Workaround implemented via 427428d09b87926135bcc1629fabfc8f9fec036e
