### ISSUE TITLE
Add BTKitty

### ISSUE THREAD

**Issue by getpanoramic** [Jackett/Jackett#2974]
Please add http://btkitty.red

It's a very popular DHT crawler/indexer in china. And very usefull to find hard to get torrents.
It has no categories similiar to BTDB.

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by haudankaivajasi** [comment]
This would be awesome to have!

**Comment by garfield69** [comment]
anyone know which domain BTKitty is now on?
