### ISSUE TITLE
auto-update sabotaging /tmp partition

### ISSUE THREAD

**Issue by TouchMyBox** [Jackett/Jackett#298]
I was wondering why my Plex library was failing to update, until I saw that Jackett had tried to auto update and downloaded a thousand update files to my /tmp partition, filling it and ruining the operation of my server. I've obviously since disabled auto-updates now since I use a package manager, but this behaviour is new since it never did this before a few updates ago.

**Comment by raspdealer** [comment]
Related to https://github.com/Jackett/Jackett/issues/154

**Comment by flightlevel** [comment]
Can you provide the log with all the updates
Also, what OS and version of mono?

**Comment by tadfisher** [comment]
Experienced th

**Comment by thejacer87** [comment]
same issue for me... 2GB /tmp was filled within a day after i deleted everything

**Comment by zeflash** [comment]
It's still an issue - on my Qnap NAS, the tmp partition is only 64 MB - needless to say it breaks things down easily when Jackett doesn't remove the downloaded update files (14 MB for each revision)

Should be easy to fix to remove those files after the update has been installed, right? please fix, I too have to disable auto-update for the moment.

**Comment by zeflash** [comment]
At least, make it so that the tmp folder used to download the updates is read off one system export - TMPDIR for example. This way people will be able to change that in the launch script & point it somewhere else than a RAM partition

**Comment by kaso17** [comment]
should be fixed with bbff25fd5479dbf62fe9b0d72d7d21d25895ddba

**Comment by Nightraider89** [comment]
Is this a returning issue? since i have it for quite some tim on my readynas, runs latest version, keeps on updating to newer ones, but fails to delete the temporary setup files, causing my root drive to choke .
