### ISSUE TITLE
Add please QxR  

### ISSUE THREAD

**Issue by Zero0Q** [Jackett/Jackett#2980]
Can you please add this site https://qxr.pw/ to Jackett. They have releases on 1337x and ETTV, but Radarr and Sonarr cant search their releases for some reason,  They have the best releases and they growing fast. 
Thanks

**Comment by garfield69** [comment]
I cant find their torrent search engine... have they got one?
Need a link to their torrent results page so we can build a indexer for the site.

**Comment by Zero0Q** [comment]
They have this if its helps https://qxr.pw/hashes/

**Comment by Zero0Q** [comment]
and this https://qxr.pw/hashes/rssbuilder.php

**Comment by Zero0Q** [comment]
and search box is https://qxr.pw/index.php?/search/

**Comment by Zero0Q** [comment]
Hope this will help..

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by Zero0Q** [comment]
I don't know nothing about HTML/CSS

**Comment by bonfire62** [comment]
would love this as well!

**Comment by cybersteel8** [comment]
QxR is added, this should be closed right?
( Even though it's kinda useless as an indexer for searching because of #4724 )

**Comment by garfield69** [comment]
no, i'm leaving it open because the intention is to replace this cardigann indexer with one written in c# so that it can properly process this site's results.
waiting on a volunteer with c# skills.

**Comment by garfield69** [comment]
qxr has closed.
