### ISSUE TITLE
How do I manually get cookies from iptorrents?

### ISSUE THREAD

**Issue by hdubb** [Jackett/Jackett#2981]
I read all the previous questions that were the same but none of them ever gave step by step instructions.

**Comment by flightlevel** [comment]
https://github.com/Jackett/Jackett/wiki/Finding-cookies

**Comment by hdubb** [comment]
These steps do not work for the website I listed.

**Comment by flightlevel** [comment]
Confirm you have done this
` Please go to https://iptorrents.com/settings.php and change the "Torrents - Category column" option to "Icons". Wait a minute (cache) and then try again.`
Then provide a full enhanced log https://github.com/Jackett/Jackett#troubleshooting
And provide the format of the cookie you are using
