### ISSUE TITLE
add support for search by tvdb/tvmaze/trakt/moviedb ID

### ISSUE THREAD

**Issue by kaso17** [Jackett/Jackett#2984]
Currently jackett only supports search by IMDB ID.

We should add support searching by other IDs too.

If you're aware of trackers supporting other IDs than IMDB please post them here.

**Comment by kaso17** [comment]
BTN and HDBits supports TVDB

**Comment by HDVinnie** [comment]
Blutopia (BLU), BTWorld and TorrentWTF support IMDB, TMDB, TVDB and MAL.

**Comment by AWaheedi** [comment]
YTS support IMDB

**Comment by edalex86** [comment]
Since tvdb/tmdb support was implemented could you add it to sites mentioned here?

**Comment by ilike2burnthing** [comment]
@seeyabye can you add tvdbid search support to the BTN indexer?

@jyggen can you add tmdbid search support to the HDBitsApi C# indexer, and if possible add imdbid, tmdbid, and tvdbid to the hdbits yaml indexer (not sure if it's actually usable at the moment - https://github.com/Jackett/Jackett/issues/12120)?

I think those are the only ones mentioned here which still exist and are incomplete.

**Comment by jyggen** [comment]
Their API does not support TMDb ID, otherwise I would've added it right away. As for the yaml indexer I'd consider it deprecated since the C# one can do everything and more in a better way. People should just use the C# one instead 🙂

**Comment by edalex86** [comment]
> Their API does not support TMDb ID, otherwise I would've added it right away. As for the yaml indexer I'd consider it deprecated since the C# one can do everything and more in a better way. People should just use the C# one instead 🙂

Yes, the only missing thing is TVDB for BTN

**Comment by Jessie722** [comment]
JPTV only support TMDB ID, I need help to improve the indexer.

**Comment by garfield69** [comment]
@Jessie722  the jptv indexer already has  tmdbid support for movies.
if a torznab app makes a query to Jackett using the t=movie and the tmdbid=number then Jackett will return result.
example:
http://127.0.0.1:9117/api/v2.0/indexers/jptv/results/torznab/api?t=movie&cat=100001&tmdbid=900645&extended=1&apikey=youjackettapikey&offset=0&limit=100

**Comment by garfield69** [comment]
or are you talking about removing the imdbid and tvdbid components of the jptv indexer?

**Comment by Jessie722** [comment]
> @Jessie722 the jptv indexer already has tmdbid support for movies. if a torznab app makes a query to Jackett using the t=movie and the tmdbid=number then Jackett will return result. example: http://127.0.0.1:9117/api/v2.0/indexers/jptv/results/torznab/api?t=movie&cat=100001&tmdbid=900645&extended=1&apikey=youjackettapikey&offset=0&limit=100
> 
> [edit] t=search with tmdbid also works, just tested and got the same torrent back.

Thank you for your reply. 
I checked the log again. JPTV indexer does have tmdbid support and I missed that.
Then I realized that the reason I didn't find the episodes was that Sonarr didn't send TMDB. So this is Sonarr's problem right?
And if I add season=number&ep=number, Jackett returns nothing.

**Comment by garfield69** [comment]
Sonarr is a TV series torznab app, and uses either the t=search or t=tvsearch torznab queries.
However, current torznab specs state that only the t=movie torznab query supports the use of the tmdbid search parm, (because at the time the specs were drawn up the TMDB web site only provided movies).
So if a torznab app makes a capabilities query against the jackett jptv indexer, it will be informed that the t=search and t=tvsearch do not support the use of the tmdbid query.
and this is why Sonarr is not likely to use that type of query when making torznab requests to Jackett.
Radarr however can make such queries, which is how I know that the t=movie torznab request with the tmdbid works.

**Comment by Jessie722** [comment]
> Sonarr is a TV series torznab app, and uses either the t=search or t=tvsearch torznab queries.
> However, current torznab specs state that only the t=movie torznab query supports the use of the tmdbid search parm, (because at the time the specs were drawn up the TMDB web site only provided movies).
> So if a torznab app makes a capabilities query against the jackett jptv indexer, it will be informed that the t=search and t=tvsearch do not support the use of the tmdbid query.
> and this is why Sonarr is not likely to use that type of query when making torznab requests to Jackett.
> Radarr however can make such queries, which is how I know that the t=movie torznab request with the tmdbid works.

You solved my question. Thank you !

**Comment by garfield69** [comment]
Closed as stale.
