### ISSUE TITLE
[torrentleech]  (Config) Can't add indexer, login broken

### ISSUE THREAD

**Issue by ksemeks** [Jackett/Jackett#2985]
**Jackett version**:  0.8.886.0 
**Mono version** (if not using Windows):  5.10.0.160
-------------------------------

Seems like the login isn't working properly. This is the error from the log

> <strong><i class="fa fa-exclamation-circle"></i> Error: </strong> Please click on the reCAPTCHA box.                  

[log.txt](https://github.com/Jackett/Jackett/files/1919435/log.txt)

**Comment by kaso17** [comment]
535f71c18cff9c66e2a166652d6496f31519541a should fix it

**Comment by ksemeks** [comment]
It's working now, but wrong credentials throw another exception. See log

[log.txt](https://github.com/Jackett/Jackett/files/1919977/log.txt)

**Comment by kaso17** [comment]
fixed error message parsing via 48cdc3bb5e795e62155194b37666120579c06beb
