### ISSUE TITLE
[Tracker Request] RGU

### ISSUE THREAD

**Issue by DeltaHit** [Jackett/Jackett#2987]
If possible, could you guys please add the RGU tracker? 
Here's the website's link, it currently is in open signups: [rgu.rgt.life](https://rgu.rgt.life)

Thanks!

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by DeltaHit** [comment]
Wow thank you! I'll definitely try it out!

**Comment by kaso17** [comment]
you can add it locally, it's loaded on every jackett start.
Once it's working please create a pull request.

**Comment by gjm1976** [comment]
got the yml 
will create pull request

**Comment by gjm1976** [comment]
[rgu.zip](https://github.com/Jackett/Jackett/files/1957055/rgu.zip)
wouldn't let me create a pull request to master? so added here

**Comment by kaso17** [comment]
added via #3084, thank you

**Comment by kaso17** [comment]
@gjm1976 @DeltaHit is this tracker dead?

**Comment by DeltaHit** [comment]
I don't know, I have stopped using it a while ago, but the website still appears to be up and running

**Comment by kaso17** [comment]
ok, looks like just the domain changed.
thank you
