### ISSUE TITLE
[yify] Parse error: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. (Config)

### ISSUE THREAD

**Issue by WeirDave** [Jackett/Jackett#2991]
Had a warning on this indexer in Radarr

**Jackett version**:   Jackett Version 0.8.886.0 
**Mono version** (if not using Windows):  5.4.1.6.0
[log.txt](https://github.com/Jackett/Jackett/files/1924099/log.txt)
[updater.txt](https://github.com/Jackett/Jackett/files/1924100/updater.txt)

-------------------------------

**Comment by flightlevel** [comment]
Looks to be related to using Libcurl

https://github.com/Jackett/Jackett/issues/2809
https://forum.qnap.com/viewtopic.php?f=320&t=116660&start=120

Can you try updating to latest Mono and Jackett (looks like on QNAP forum they've removed the libcurl startup argument in the most recent Jackett qpkg)

**Comment by WeirDave** [comment]
I have the latest version from the QNAP club website installed which is 0.8.881

**Comment by kaso17** [comment]
It looks like you hanged the site link to `https://yifymovie.co/10002`, make sure it's only `https://yifymovie.co/`

**Comment by WeirDave** [comment]
> https://yifymovie.co/2040

That is the default that is listed when i remove the "2040" I still get the following error:

 An error occured while updating this indexer
Parse error: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by kaso17** [comment]
Please post an updated log with Site lionk = `https://yifymovie.co/` (no extra arguments)

**Comment by WeirDave** [comment]
Attached log. today the error is with YTS
[radarr.txt](https://github.com/Jackett/Jackett/files/1944781/radarr.txt)

**Comment by kaso17** [comment]
we'll need the jackett log, not the radarr log

**Comment by WeirDave** [comment]
[log.20180424.00000.txt](https://github.com/Jackett/Jackett/files/1957789/log.20180424.00000.txt)
