### ISSUE TITLE
[nyaasi] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by bidossessi** [Jackett/Jackett#2992]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  jackett-0.8.886 (Archlinux aur)
**Mono version** (if not using Windows):  5.10.0.179

-------------------------------
URL to logs: https://ptpb.pw/u2-S

**Comment by garfield69** [comment]
nyaa.si's domain disappeared yesterday, but is just now back again. 
However I'm having trouble with the ssl certificate, so lets give it a day or so and see if the site sort it all out.

**Comment by garfield69** [comment]
nyaa.si seems to be back to full operation now.
