### ISSUE TITLE
AnimeBytes upload dates

### ISSUE THREAD

**Issue by gotson** [Jackett/Jackett#2993]
I see on the AnimeBytes configuration that it doesn't support dates:

> This tracker does not supply upload dates so they are based off year of release.

Is this still accurate ?
I see upload dates on the AnimeBytes website, just wanted to understand where is the limitation.

On another note, the date returned seems to be hardcoded to 2017.
Here is what i got yesterday for a torrent published yesterday: `Tuesday, April 18 2017 00:00`

**Comment by kaso17** [comment]
The date is not available via the search results page (without retrieving the torrent details page). Currently they're blocking jackett completely, see #3008
