### ISSUE TITLE
[torrentz2] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by gt2416** [Jackett/Jackett#2995]
**Jackett version**: 0.8.701.0

**Comment by garfield69** [comment]
Hi @gt2416 ,

You've created an issue, but haven't provided any details to allow the community to assist you. To prevent issue tracker clutter, this issue will now be closed. Please provide the information needed below and your comment will automatically re-open this issue.

Provide a description of the feature request or bug, the more details the better. If you are experiencing an issue with a tracker, a full enhanced log must be included. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

works for me on my win7 Jackett 0.8.898
