### ISSUE TITLE
RSS Number of Results?

### ISSUE THREAD

**Issue by majorsl** [Jackett/Jackett#2997]
**Jackett version**:  0.8.886.0
**Mono version** (if not using Windows):  Unsure, Synology Package
-------------------------------
Firstly, I'm new. I just installed Jackett over the weekend for RSS feeds of some sites that provide none.

Is there a way to adjust the number of hits returned to an RSS feed from a search when using the "Copy RSS Feed" link?

**Comment by kaso17** [comment]
You can reduce the results via the limit option increasing them is not possible (depends on the tracker).
See #975
Make sure you set the number of results per page in your tracker settings to the maximum.
