### ISSUE TITLE
[jpopsuki] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by poplolnman** [Jackett/Jackett#2999]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

every time i try and save the details for jpopsuki it just says its being redirected...

**Jackett version**:  0.8.886.0
**Mono version** (if not using Windows):  

-------------------------------

When | Level | Message
-- | -- | --
Apr 20, 2018 04:21:27 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
Apr 20, 2018 04:21:27 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
Apr 20, 2018 04:21:27 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Apr 20, 2018 04:21:27 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
Apr 20, 2018 04:21:27 PM | Info | HttpActionBinding ExecuteBindingAsync
Apr 20, 2018 04:21:27 PM | Info | HttpActionBinding ExecuteBindingAsync
Apr 20, 2018 04:21:27 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Apr 20, 2018 04:21:27 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Apr 20, 2018 04:21:27 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
Apr 20, 2018 04:21:27 PM | Info | ApiControllerActionSelector SelectAction
Apr 20, 2018 04:21:27 PM | Info | ServerConfigurationController ExecuteAsync
Apr 20, 2018 04:21:27 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.ServerConfigurationController
Apr 20, 2018 04:21:27 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.ServerConfigurationController
Apr 20, 2018 04:21:27 PM | Info | DefaultHttpControllerActivator Create
Apr 20, 2018 04:21:27 PM | Info | HttpControllerDescriptor CreateController
Apr 20, 2018 04:21:27 PM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
Apr 20, 2018 04:21:27 PM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
Apr 20, 2018 04:21:27 PM | Info | http://localhost:9117/api/v2.0/server/logs?_=1524255652665
Apr 20, 2018 04:21:21 PM | Info | IndexerApiController Dispose
Apr 20, 2018 04:21:21 PM | Info | IndexerApiController Dispose
Apr 20, 2018 04:21:21 PM | Info | Content-type='application/json; charset=utf-8', content-length=5982
Apr 20, 2018 04:21:21 PM | Info | IndexerApiController ExecuteAsync
Apr 20, 2018 04:21:21 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Apr 20, 2018 04:21:21 PM | Error | Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.    at Jackett.Common.Indexers.CardigannIndexer.<TestLogin>d__20.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Indexers.CardigannIndexer.<ApplyConfiguration>d__24.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Controllers.IndexerApiController.<UpdateConfig>d__10.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\IndexerApiController.cs:line 101 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
Apr 20, 2018 04:21:21 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Apr 20, 2018 04:21:21 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Apr 20, 2018 04:21:21 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Config(ConfigItem[] config)'
Apr 20, 2018 04:21:21 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Apr 20, 2018 04:21:21 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Config(ConfigItem[] config)'
Apr 20, 2018 04:21:21 PM | Error | ApiControllerActionInvoker InvokeActionAsync
Apr 20, 2018 04:21:21 PM | Error | ReflectedHttpActionDescriptor ExecuteAsync
Apr 20, 2018 04:21:21 PM | Debug | WebClient(HttpWebClient): Returning Redirect => https://jpopsuki.eu/login.php
Apr 20, 2018 04:21:20 PM | Debug | WebClient(HttpWebClient).GetString(Url:https://jpopsuki.eu/torrents.php)
Apr 20, 2018 04:21:20 PM | Debug | CardigannIndexer (jpopsuki): Cookies after login: PHPSESSID=35onelo5f0mf18g819f51gtui0; keeplogged=deleted
Apr 20, 2018 04:21:20 PM | Debug | WebClient(HttpWebClient): Returning OK => <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> <head> 	<title>Login :: JPopsuki 2.0</title> 	<meta http-equiv="Pragma" content="no-cache" /> 	<meta http-equiv="Expires" content="-1" /> 	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 	<link rel="shortcut icon" href="static/styles/public/favicon.ico" /> 	<link href="static/styles/public/style.css" rel="stylesheet" type="text/css" /> 	<script src="static/functions/global.js" type="text/javascript"></script> 	<script src="static/functions/validate.js" type="text/javascript"></script> </head> <body> <div id="head"></div> <table cellpadding="0" cellspacing="0" border="0" id="maincontent"> 	<tr> 		<td align="center" valign="middle"> 			<div id="logo"> 				<a href="index.php">Home</a> 				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="login.php">Login</a>   				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="media.php">JPopsuki Radio / TV</a> 			</div> <div style="width:440px;"> <script type="text/javascript" language="javascript"> //<![CDATA[ function formVal() { 	if (!$('#username').get(0).value.match(/^[a-z0-9\-\_]+$/i)) { return showError('#username','You did not enter a valid username.'); } 	if ($('#password').get(0).value=="" \|\| $('#password').get(0).value.length>40 \|\| $('#password').get(0).value.length<6) { return showError('#password','You entered an invalid password.'); } } //]]> </script> 	<form name="loginform" id="loginform" method="post" action="login.php" onsubmit="return formVal();"> 	<font color="red"><strong>You did not enter a valid username.</strong></font><br /><br /> 	You have <font color="green"><strong>1</strong></font> attempts remaining.<br /><br /> 	<strong>WARNING:</strong> You will be banned for 6 hours after your login attempts run out.<br /><br /> 	<table cellpadding="2" cellspacing="1" border="0" align="center"> 		<tr valign="top"> 			<td align="right">Username&nbsp;</td> 			<td align="left"><input type="text" name="username" id="username" class="inputtext" /></td> 		</tr> 		<tr valign="top"> 			<td align="right">Password&nbsp;</td> 			<td align="left"><input type="password" name="password" id="password" class="inputtext" /></td> 		</tr> 		<tr valign="top"> 			<td colspan="2" align="right"><input type="checkbox" name="keeplogged" value="1" checked="checked" />Keep me logged in</td> 		</tr> 		<tr> 			<td colspan="2" align="right"><input type="submit" name="login" value="Log In!" class="submit" /></td> 		</tr> 	</table> 	</form> 	<br /><br /> 	Lost your password? <a href="login.php?act=recover">Recover it here!</a><br /><br /> 	You did not receive your confirmation email?<br /> 	Account suddenly disabled?<br /> 	<a href="javascript:void(0);" onclick='window.open("http://widget.mibbit.com/?settings=b50a31cdebbf5c6f3187a8646147857d&server=irc.synirc.net&noServerMotd=true&noServerTab=false&channel=%23jpopsuki-support&autoConnect=true&nick=jpopsuki%3F%3F%3F","","width=999,height=555,toolbar=no,scrollbars=no,menubar=no,location=no,status=no")'>Use this webchat link and ask for support from our Team (Pop-Up)</a><br /> 	Or use your own IRC client: <a href='irc://irc.synirc.net/jpopsuki-support'>irc://irc.synirc.net/jpopsuki-support</a><br /> 	Please do not join to request an invite - you will be ignored.<br /> </div> 		</td> 	</tr> </table> <div id="foot"><div id="copyleft"></div></div> </body> </html>
Apr 20, 2018 04:21:18 PM | Debug | WebClient(HttpWebClient).GetString(Url:https://jpopsuki.eu/login.php)
Apr 20, 2018 04:21:18 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Config(config=Jackett.Common.Models.DTO.ConfigItem[])'
Apr 20, 2018 04:21:18 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Config(config=Jackett.Common.Models.DTO.ConfigItem[])'
Apr 20, 2018 04:21:18 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync
Apr 20, 2018 04:21:18 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Config(ConfigItem[] config)'
Apr 20, 2018 04:21:18 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Apr 20, 2018 04:21:18 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Config(ConfigItem[] config)'
Apr 20, 2018 04:21:18 PM | Info | HttpActionBinding ExecuteBindingAsync Model state is valid. Values: config=Jackett.Common.Models.DTO.ConfigItem[]
Apr 20, 2018 04:21:18 PM | Info | FormatterParameterBinding ExecuteBindingAsync Parameter 'config' bound to the value 'Jackett.Common.Models.DTO.ConfigItem[]'
Apr 20, 2018 04:21:18 PM | Info | JsonMediaTypeFormatter ReadFromStreamAsync Value read='Jackett.Common.Models.DTO.ConfigItem[]'
Apr 20, 2018 04:21:18 PM | Info | JsonMediaTypeFormatter ReadFromStreamAsync Type='ConfigItem[]', content-type='application/json'
Apr 20, 2018 04:21:18 PM | Info | FormatterParameterBinding ExecuteBindingAsync Binding parameter 'config'
Apr 20, 2018 04:21:18 PM | Info | HttpActionBinding ExecuteBindingAsync
Apr 20, 2018 04:21:18 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Apr 20, 2018 04:21:18 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Apr 20, 2018 04:21:18 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Config(ConfigItem[] config)'
Apr 20, 2018 04:21:18 PM | Info | ApiControllerActionSelector SelectAction
Apr 20, 2018 04:21:18 PM | Info | IndexerApiController ExecuteAsync
Apr 20, 2018 04:21:18 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.IndexerApiController
Apr 20, 2018 04:21:18 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.IndexerApiController
Apr 20, 2018 04:21:18 PM | Info | DefaultHttpControllerActivator Create
Apr 20, 2018 04:21:18 PM | Info | HttpControllerDescriptor CreateController
Apr 20, 2018 04:21:18 PM | Info | DefaultHttpControllerSelector SelectController IndexerApi
Apr 20, 2018 04:21:18 PM | Info | DefaultHttpControllerSelector SelectController Route='indexerId:jpopsuki,action:config,controller:IndexerApi'
Apr 20, 2018 04:21:18 PM | Info | http://localhost:9117/api/v2.0/indexers/jpopsuki/config
Apr 20, 2018 04:21:16 PM | Info | IndexerApiController Dispose
Apr 20, 2018 04:21:16 PM | Info | IndexerApiController Dispose
Apr 20, 2018 04:21:16 PM | Info | JsonMediaTypeFormatter WriteToStreamAsync
Apr 20, 2018 04:21:16 PM | Info | JsonMediaTypeFormatter WriteToStreamAsync Value='[   {     "id": "sitelink",     "type": "inputstring",     "name": "Site Link",     "value": "https://jpopsuki.eu/"   },   {     "id": "cookieheader",     "type": "hiddendata",     "name": "CookieHeader",     "value": ""   },   {     "id": "lasterror",     "type": "hiddendata",     "name": "LastError",     "value": ""   },   {     "id": "username",     "type": "inputstring",     "name": "Username",     "value": "dlovestrange@gmail.com"   },   {     "id": "password",     "type": "inputstring",     "name": "Password",     "value": "\|\|\|%%PREVJACKPASSWD%%\|\|\|"   } ]', type='JToken', content-type='application/json; charset=utf-8'
Apr 20, 2018 04:21:16 PM | Info | Content-type='application/json; charset=utf-8', content-length=unknown
Apr 20, 2018 04:21:16 PM | Info | IndexerApiController ExecuteAsync
Apr 20, 2018 04:21:16 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Apr 20, 2018 04:21:16 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Config()'
Apr 20, 2018 04:21:16 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Apr 20, 2018 04:21:16 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Config()'
Apr 20, 2018 04:21:16 PM | Info | ApiControllerActionInvoker InvokeActionAsync
Apr 20, 2018 04:21:16 PM | Info | DefaultContentNegotiator Negotiate Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8'
Apr 20, 2018 04:21:16 PM | Info | JsonMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'JsonMediaTypeFormatter' formatter
Apr 20, 2018 04:21:16 PM | Info | JsonMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'JsonMediaTypeFormatter' for type='JToken', mediaType='application/json; charset=utf-8'
Apr 20, 2018 04:21:16 PM | Info | DefaultContentNegotiator Negotiate Type='JToken', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer]
Apr 20, 2018 04:21:16 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.OkNegotiatedContentResult`1[Newtonsoft.Json.Linq.JTok

**Comment by kaso17** [comment]
check your credentials: ` You did not enter a valid username.`
Error detection fixed via 0037811fb559cc17f7705433252065a6a884396f
