### ISSUE TITLE
[REQ] SceneHD.org

### ISSUE THREAD

**Issue by IeUDE** [Jackett/Jackett#3]
Would it be possible to add support for this tracker? (scenehd.org)

Films and TV-Shows

Thank you in advance.

**Comment by flightlevel** [comment]
This is a private tracker, we would require an invite to attempt it.

**Comment by sethwarsh** [comment]
I would like this tracker complimented as well, I will work on a Torznab mapping and an invite, but we cannot get invitations until their donation quota had been met, so it may be a few weeks.

**Comment by sethwarsh** [comment]
I have invites available now.

Here's a torznab mapping:

/AddCategoryMapping("1", TorznabCatType.Console);
//AddCategoryMapping("1", TorznabCatType.ConsoleNDS);
//AddCategoryMapping("1", TorznabCatType.ConsolePSP);
//AddCategoryMapping("1", TorznabCatType.ConsoleWii);
//AddCategoryMapping("1", TorznabCatType.ConsoleXbox);
//AddCategoryMapping("1", TorznabCatType.ConsoleXbox360);
//AddCategoryMapping(1", TorznabCatType.ConsoleWiiwareVC);
//AddCategoryMapping("1", TorznabCatType.ConsoleXBOX360DLC);
//AddCategoryMapping("1", TorznabCatType.ConsolePS3);
//AddCategoryMapping("1", TorznabCatType.ConsoleOther);
//AddCategoryMapping("1", TorznabCatType.ConsoleOther);
//AddCategoryMapping("1", TorznabCatType.ConsoleOther);
//AddCategoryMapping("1", TorznabCatType.ConsoleOther);
//AddCategoryMapping("1", TorznabCatType.ConsoleOther);
//AddCategoryMapping("1", TorznabCatType.ConsoleOther);
//AddCategoryMapping("1", TorznabCatType.Console3DS);
//AddCategoryMapping("308", TorznabCatType.ConsolePSVita);
//AddCategoryMapping("1", TorznabCatType.ConsoleWiiU);
//AddCategoryMapping("39", TorznabCatType.ConsoleXboxOne);
//AddCategoryMapping("16", TorznabCatType.ConsolePS4);
//AddCategoryMapping("1", TorznabCatType.Movies);
//AddCategoryMapping("1", TorznabCatType.MoviesForeign);
//AddCategoryMapping("11", TorznabCatType.MoviesOther);
//AddCategoryMapping("8", TorznabCatType.MoviesOther);
AddCategoryMapping("11", TorznabCatType.MoviesSD);
AddCategoryMapping("1", TorznabCatType.MoviesHD);
//AddCategoryMapping("1", TorznabCatType.Movies3D);
AddCategoryMapping("22", TorznabCatType.MoviesBluRay);
AddCategoryMapping("4", TorznabCatType.MoviesDVD);
//AddCategoryMapping("631", TorznabCatType.MoviesWEBDL);
AddCategoryMapping("1", TorznabCatType.Audio);
AddCategoryMapping("1", TorznabCatType.AudioMP3);
AddCategoryMapping("1", TorznabCatType.AudioVideo);
AddCategoryMapping("13", TorznabCatType.AudioVideo);
//AddCategoryMapping("1", TorznabCatType.AudioAudiobook);
//AddCategoryMapping("1", TorznabCatType.AudioLossless);
//AddCategoryMapping("1", TorznabCatType.AudioOther);
//AddCategoryMapping("1", TorznabCatType.AudioOther);
//AddCategoryMapping("1", TorznabCatType.AudioForeign);
//AddCategoryMapping("1", TorznabCatType.PC);
//AddCategoryMapping("1", TorznabCatType.PC);
//AddCategoryMapping("1", TorznabCatType.PC0day);
//AddCategoryMapping("1", TorznabCatType.PCISO);
//AddCategoryMapping("1", TorznabCatType.PCMac);
//AddCategoryMapping("1", TorznabCatType.PCPhoneOther);
//AddCategoryMapping("4", TorznabCatType.PCGames);
//AddCategoryMapping("1", TorznabCatType.PCPhoneIOS);
//AddCategoryMapping("1", TorznabCatType.PCPhoneAndroid);
//AddCategoryMapping("1", TorznabCatType.TV);
//AddCategoryMapping("41", TorznabCatType.TV);
//AddCategoryMapping("42", TorznabCatType.TVWEBDL);
//AddCategoryMapping("41", TorznabCatType.TVWEBDL);
///AddCategoryMapping("1", TorznabCatType.TVFOREIGN);
//AddCategoryMapping("41", TorznabCatType.TVFOREIGN);
//AddCategoryMapping("41", TorznabCatType.TVSD);
//AddCategoryMapping("1", TorznabCatType.TVSD);
AddCategoryMapping("7", TorznabCatType.TVHD);
AddCategoryMapping("5", TorznabCatType.TVHD);
AddCategoryMapping("1", TorznabCatType.TVOTHER);
//AddCategoryMapping("1", TorznabCatType.TVSport);
//AddCategoryMapping("1", TorznabCatType.TVAnime);
//AddCategoryMapping("1", TorznabCatType.TVDocumentary);
AddCategoryMapping("10", TorznabCatType.XXX);
//AddCategoryMapping("1", TorznabCatType.XXXDVD);
//AddCategoryMapping("1", TorznabCatType.XXXWMV);
//AddCategoryMapping("1", TorznabCatType.XXXXviD);
//AddCategoryMapping("1", TorznabCatType.XXXx264);
//AddCategoryMapping("1", TorznabCatType.XXXOther);
//AddCategoryMapping("1", TorznabCatType.XXXImageset);
//AddCategoryMapping("1", TorznabCatType.XXXPacks);
AddCategoryMapping("16", TorznabCatType.Other);
AddCategoryMapping("9", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.Other);
//AddCategoryMapping(1", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.OtherMisc);
//AddCategoryMapping("1", TorznabCatType.OtherHashed);
//AddCategoryMapping("1", TorznabCatType.Books);
//AddCategoryMapping("1", TorznabCatType.BooksEbook);
//AddCategoryMapping("1", TorznabCatType.BooksComics);
//AddCategoryMapping("1", TorznabCatType.BooksComics);
//AddCategoryMapping("1", TorznabCatType.BooksComics);
//AddCategoryMapping("1", TorznabCatType.BooksMagazines);
//AddCategoryMapping("1", TorznabCatType.BooksTechnical);
//AddCategoryMapping("1", TorznabCatType.BooksOther);
//AddCategoryMapping("1", TorznabCatType.BooksForeign);

Please email me for the invite sethmw@gmail.com

**Comment by IeUz** [comment]
Any chances to have this implemented?

**Comment by sethwarsh** [comment]
I really would like it as well!

**Comment by flightlevel** [comment]
None of the devs are members here, send an invite to jackettapp at gmail
and i'll add it

**Comment by sethwarsh** [comment]
Give me a few days to get an invite.

What about ToTheGlory, M-Team, HDchina, HDarena I submitted torznabs cats for them, and I can send invites immediately.

**Comment by d2dyno** [comment]
What's the status of this?

**Comment by kaso17** [comment]
I guess a invite is needed. Please send it to flightlevel or to me (kaso1717 -at- gmail.com)

**Comment by kaso17** [comment]
fixed via 10473c6bd306fa098a2fe1ab57a1ebd8268019a7

**Comment by kaso17** [comment]
Thank you for letting us know. I'll update it to use the API once I've time (probably next year).

**Comment by kaso17** [comment]
migrated to API usage via 590fd5139ffdc2096fbcbc6c2d2162a2c3d72b8c
