### ISSUE TITLE
[REQ] Add PixelHD

### ISSUE THREAD

**Issue by dxm765** [Jackett/Jackett#30]
Can you please add PixelHD as a tracker, theyre still accepting applications. When applying at how did you hear about the site you can put "the7egend"

**Comment by kaso17** [comment]
done

**Comment by kaso17** [comment]
is this tracker dead?

**Comment by dxm765** [comment]
I'm not sure, I see its currently unreachable, not sure if its down for
maintenance or if its dead.

**Comment by kaso17** [comment]
ok, it's alive

**Comment by benoittravers** [comment]
Is it still working on Jackett? Not seeing it as an option.

**Comment by garfield69** [comment]
@benoittravers  yes, the pixelhd indexer is still available 
![image](https://user-images.githubusercontent.com/6933240/155892905-ee8de475-eda8-443c-ae85-6dfa82c7440f.png)
