### ISSUE TITLE
[skytorrents] Exception (skytorrents): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 46.166.187.41:443: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by goku-son** [Jackett/Jackett#3002]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.886.0
**Mono version** (if not using Windows):  

-------------------------------
Hi, I get the following error when testing sky torrents, not sure if it is down or if it some other issue. Here are the errors I get:
An error occured while testing this indexer
Exception (skytorrents): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 46.166.187.41:443: An error occurred while sending the request.

**Comment by garfield69** [comment]
SkyTorrents shutdown.
details at https://torrentfreak.com/skytorrents-dumps-massive-torrent-database-and-shuts-down180221/
indexer was removed starting with jackett v0.8.735
