### ISSUE TITLE
[torrentleech] Exception (torrentleech): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Parse error (Test)

### ISSUE THREAD

**Issue by mephasor** [Jackett/Jackett#3006]
**Jackett version**:   0.8.886.0
**Mono version** (if not using Windows):  5.10.1.20

-------------------------------
[log.txt](https://github.com/Jackett/Jackett/files/1935762/log.txt)

Everything worked fine until last night. Any suggestions?

**Comment by lukecamilo** [comment]
Same issue, but first time trying to use it.


**Jackett version**:   0.8.886.0
**Mono version** (if not using Windows):  Using Windows server 2012R2
[log.txt](https://github.com/Jackett/Jackett/files/1935838/log.txt)


-------------------------------

**Comment by mephasor** [comment]
Using the sonarr RSS functionality for now. Would love the search to be back at some point though :)

**Comment by kaso17** [comment]
@mephasor: From the log:
```You are automatically being redirected to this page because your account didn't meet the right ratio criteria to stay active.
You can either choose to donate and your account will automatically be enabled and you will gain VIP access or it will automatically be deleted in 180 days.```

@lukecamilo please post the complete log (it seems like a few lines are missing), I'm especially interested in the request sent to TL because it's working fine for me.

**Comment by mephasor** [comment]
@kaso17 Oh boy. Reading is quite a useful skill at times. Thanks, from my side, the issue can be closed :smiley:

**Comment by lukecamilo** [comment]
Enabled Enhanced logging, cleaned up logs, tried again.
Two sets of logs created

[log.20180423.00000.txt](https://github.com/Jackett/Jackett/files/1939103/log.20180423.00000.txt)
[log.txt](https://github.com/Jackett/Jackett/files/1939105/log.txt)

**Comment by kaso17** [comment]
Your're using the wrong site link, change it to `https://www.torrentleech.org/`
