### ISSUE TITLE
Problem all Frenches Providers in CouchPotato

### ISSUE THREAD

**Issue by fana13** [Jackett/Jackett#301]
Hi, have some problems in all frenches providers.
I've this error : 
4-05 18:06:27 INFO
[hpotato.core.plugins.base] Opening url: get http://xx.xx.xx.xx/jackett/potato/phxbit?imdbid=tt3850214&user=&passkey=xxx
04-05 18:06:27 ERROR
[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://xx.xx.xx.xx/jackett/potato/phxbit?imdbid=tt3850214&user=&passkey=xxx&user=&passkey=xxx
04-05 18:06:27 DEBUG
[hpotato.core.plugins.base] Failed getting cache: Traceback (most recent call last): HTTPError: 401 Client Error: Unauthorized for url: http://xx.xx.xx.xx/jackett/potato/phxbit?imdbid=tt3850214&user=&passkey=xxx

In this case is for PHX but it's the same thing for ABN or Bluetigers right now (i don't speak for F-ADN because is down now).
Have you an idea ?
In jackett search is good and also test too.
But in CP nothing works.
The APi key is the same between Jackett and CP et username is blank.

Thx ;)

**Comment by JigSawFr** [comment]
Have you tried another provider ? (english provider or something else)

**Comment by fana13** [comment]
I've BTN but it's useless for CP.
Without jackett, providers are OK, i can snatch for xthor, hdo, ptp or t411.
I've only this error with jackett / torrentpotato

**Comment by JigSawFr** [comment]
It's not the problem ..
What i want is you test another provider with CP (A jackett provider I mean !)
Not a CP provider. I suppose that probleme is between communication with jackett or auth with Jackett from CP. 
Maybe not related directly to providers

**Comment by raspdealer** [comment]
I never had a single issue between CouchPotato and Jackett on my side.
Except core issue like PhxBit download link for example.

**Comment by flightlevel** [comment]
@fana13 
You are getting error `Client Error: Unauthorized for url:` which probably means your api key is incorrect.
Try entering the url in your browser and see what happens.
eg. localhost:9117/potato/bluetigers?imdbid=tt1979320&user=&passkey=YOUR_API_KEY

You could also try without your reverse proxy

**Comment by fana13** [comment]
@flightlevel i tried the url with the port and with the reverse proxy too, and it's allright.
I've the good result, Rush movie, all informations are goods
@JigSawFr i know it was just for more precision, only for that. And i don't have other provider for test sorry

**Comment by JigSawFr** [comment]
@fana13 : As @flightlevel said, seems to be an error with your API key in CP for Jackett

**Comment by fana13** [comment]
I've tried everything but nothing works.
I try with a fresh install of CP, with new settings.conf.
I try to reboot my server.
The test of @flightlevel in local (on my server) or distant is allright, the api is correct, but not in CP.
I'm lost, i don't understand why it doesn't work.
If someone want to help me, that was cool :)

**Comment by fana13** [comment]
It's really the api that not appear in CP.
I don't hide the api when i post my log :  http://xx.xx.xx.xx/jackett/potato/phxbit?imdbid=tt3850214&user=&passkey=xxx
The "xxx" at the end is that i really see in my CP log !! 
So normally it was the entire api.
I don't understand why the api key is not good in CP.
Can i changed this api in jackett for test ?

**Comment by duramato** [comment]
Check the CouchPotato config file

**Comment by fana13** [comment]
Allright i finally found the problem.
I've changed the port into jackett and reload.
The api is correct and all works now.
I don't know why the port doesn't work but it was simply that.
Thanks all for your help.
:)

**Comment by JigSawFr** [comment]
Nice to see that you problem is now solved @fana13 ;)

**Comment by rouggy** [comment]
Hello, i have same issue and even changing the port of jackett did not help :(
