### ISSUE TITLE
Problem with CouchPotato starting with v0.8.913.0

### ISSUE THREAD

**Issue by ElYoM** [Jackett/Jackett#3017]
Hello, starting with version 0.8.913.0, CouchPotato started to show following errors for all my trackers being configured in Jackett 🚔 

04-24 13:58:32 INFO
[hpotato.core.plugins.base] Opening url: get http://192.168.0.152:9117/api/v2.0/indexers/archetorrent/results/potato/?imdbid=tt3829266&search=The+Predator+2018&user=&passkey=xxx
04-24 13:58:32 ERROR
[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://192.168.0.152:9117/api/v2.0/indexers/archetorrent/results/potato/?imdbid=tt3829266&search=The+Predator+2018&user=&passkey=xxx&search=The+Predator+2018&user=&passkey=xxx

To be clear, I didn't replace the passkey with xxx, it's the raw error message.

If I reinstall previous Windows version of Jackett (v0.8.886), no problem in CouchPotato. The error appears also with Jackett v0.8.898.

Thank you.

**Jackett version**:  0.8.913.0
-------------------------------

**Comment by narimanshariat** [comment]
I'm running into the same problem with any tracker that uses user/passkey auth method. For trackers that use cookies there doesn't seem to be an issue.

**Comment by loulich** [comment]
+1 I've got the same probleme with any tracker private or public, no problem when i downgrade to 0.8.886.
Ubuntu server 16.04

**Comment by kaso17** [comment]
fixed via 1b4826f966e5ac7be2605eda80e3e864a73947aa, sorry for breaking it.

**Comment by ElYoM** [comment]
Hello @kaso17 , thank you for the fix !
Do we have to manually change the modified file to make it work again ?

**Comment by kaso17** [comment]
just released v0.8.926 containing the fix

**Comment by ElYoM** [comment]
Perfect ! Thank you. ;)
