### ISSUE TITLE
installer doesn't open win server 2016

### ISSUE THREAD

**Issue by duelistjp** [Jackett/Jackett#3025]
I am trying to install on win server 2016 but the installer doesn't do anything when clicked. tried messing with compatibility settings and tried a previous release.  any idea what is wrong

**Comment by kaso17** [comment]
Unfortunately no, can't test it either

**Comment by tastyratz** [comment]
I have Jackett installed on windows server 2016. The installer opened and ran just fine for me.

**Comment by ElYoM** [comment]
Hello, can you test to right click on the installer and go to "Properties" > check "Unblock" option > click "Apply" ?

**Comment by flightlevel** [comment]
@duelistjp Can you try the latest version and see if it makes a difference. Also try running it as admin
