### ISSUE TITLE
Can't Add Indexer (torrentday)

### ISSUE THREAD

**Issue by Maverin1** [Jackett/Jackett#303]
I followed the guide to install on linux mint. I can access the webui but whenever I try to add torrentday I enter the username and password, pass the captcha, then hit ok but the loading wheel spins indefinitely.

**Comment by JigSawFr** [comment]
Please submit your logs, whitout, we can help you so much.

**Comment by Maverin1** [comment]
Can you point me to the log?

**Comment by JigSawFr** [comment]
@Maverin1 just click on "View Logs" button :radio_button:

**Comment by Maverin1** [comment]
I don't know what happened here but I found the option to enable logging the terminal since I missed that log button and I tried to add it and it worked.
