### ISSUE TITLE
[torrentbytes] Recent NewsPollWhen do you open Christmas presents?

### ISSUE THREAD

**Issue by mallyooh** [Jackett/Jackett#3030]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------
 An error occured while updating this indexer
Recent NewsPoll When do you open Christmas presents? " Christmas Eve Christmas Day I don't Other, post in the forums Blank Vote ("I just want to see the results!")

**Comment by kaso17** [comment]
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by kaso17** [comment]
@enilfodne thank you for looking into this. Fixed via 27d4ab3967e5f094393855838f77ac9d19b20105
