### ISSUE TITLE
[iptorrents] Your cookie did not work: Parse error

### ISSUE THREAD

**Issue by canadianschism** [Jackett/Jackett#3036]
I am currently trying to get Jackett to work with IPT. I've followed the screenshots to get my cookie after having logged in, but am CONSTANTLY getting a Parse Error when I click OK.

The only thing that I found different between the screenshot and my cookie, is that the help file shows PHPSESSID=, whereas my cookie starts with __cfduid=

When I'd first tried installing Jackett, it asked me for a username and password. Which I'd forgotten. So I spent some time resetting my IPT password, only to find that Jackett was now wanting a cookie. I've tried multiple different variations of the cookie, I've tried uninstalling and reinstalling Jackett, updating it, nothing is working.

If I need to paste my error log, please let me know.

**Comment by Opply** [comment]
I have exactly the same problem...

**Comment by canadianschism** [comment]
> EDIT: 2018-04-30 12:34:39.9456 Error Error on 20180430123439 for IPTorrents.txtSystem.Exception: Please go to https://iptorrents.com/settings.php and change the "Torrents - Category column" option to "Icons". Wait a minute (cache) and then try again.
> 
> Try that :)

Well, you sir/madam Internaut, have saved my bacon.

That worked amazingly well, first shot.

The screenshots may need updating... lol
