### ISSUE TITLE
[REQ] SceneFZ tracker.

### ISSUE THREAD

**Issue by hex** [Jackett/Jackett#304]
Private tracker [http://scenefz.net/](http://scenefz.net/), popular romanian tracker similar to _filelist.ro_

<pre>
AddCategoryMapping("19", TorznabCatType.Console);
AddCategoryMapping("57", TorznabCatType.ConsoleXbox360);
AddCategoryMapping("59", TorznabCatType.ConsolePS3);
AddMultiCategoryMapping(TorznabCatType.ConsoleOther, 58, 17, 46);
AddMultiCategoryMapping("32", TorznabCatType.Movies);
AddMultiCategoryMapping(TorznabCatType.MoviesHD, 47, 53);
AddMultiCategoryMapping("22", TorznabCatType.MoviesBluRay, 22, 54);
AddMultiCategoryMapping(TorznabCatType.MoviesDVD, 41, 52);
AddCategoryMapping("27", TorznabCatType.Audio);
AddCategoryMapping("8", TorznabCatType.AudioMP3);
AddCategoryMapping("45", TorznabCatType.AudioVideo);
AddCategoryMapping("14", TorznabCatType.AudioAudiobook);
AddCategoryMapping("61", TorznabCatType.AudioLossless);
AddCategoryMapping("20", TorznabCatType.PC);
AddCategoryMapping("36", TorznabCatType.PC0day);
AddCategoryMapping("20", TorznabCatType.PCISO);
AddCategoryMapping("48", TorznabCatType.PCMac);
AddMultiCategoryMapping(TorznabCatType.PCGames, 16, 18);
AddCategoryMapping("64", TorznabCatType.PCPhoneIOS);
AddCategoryMapping("65", TorznabCatType.PCPhoneAndroid);
AddCategoryMapping("33", TorznabCatType.TV);
AddCategoryMapping("69", TorznabCatType.TVFOREIGN);
AddMultiCategoryMapping(TorznabCatType.TVSD, 66, 67);
AddMultiCategoryMapping(TorznabCatType.TVHD, 68, 69);
AddCategoryMapping("cat_id", TorznabCatType.TVOTHER);
AddCategoryMapping("60", TorznabCatType.TVSport);
AddCategoryMapping("28", TorznabCatType.TVAnime);
AddCategoryMapping("34", TorznabCatType.XXX);
AddCategoryMapping("33", TorznabCatType.XXXImageset);
AddCategoryMapping("34", TorznabCatType.XXXPacks);
AddCategoryMapping("cat_id", TorznabCatType.Other);
AddCategoryMapping("cat_id", TorznabCatType.OtherMisc);
AddCategoryMapping("cat_id", TorznabCatType.OtherHashed);
AddCategoryMapping("14", TorznabCatType.Books);
AddCategoryMapping("14", TorznabCatType.BooksEbook);
AddCategoryMapping("14", TorznabCatType.BooksOther);
</pre>

**Comment by hex** [comment]
Where should I send the invitation?

**Comment by hexzorian** [comment]
#319

**Comment by kaso17** [comment]
It seems like SceneFZ is down/gone, does someone know if it will come back?

**Comment by hex** [comment]
SceneFZ is gone, there was a post on the Facebook page but I can't find the FB page anymore.
They recommended some other sites like [https://www.myxz.org/](https://www.myxz.org/)

**Comment by kaso17** [comment]
thank you, removed via 4226a48041d85e07b95e366332598685b4664007

**Comment by RoloSoze** [comment]
@kaso17 Looks like SceneFZ is back and is open for registration at the moment :) Any chance of adding it back in Jackett?

http://scenefz.me/signup.php

**Comment by kaso17** [comment]
can't login with my old account. Reregistered. But seem slike they changed something, will have to look at it later.

**Comment by RoloSoze** [comment]
@kaso17 This is actually a new tracker that uses the SceneFZ name; I doubt it's connected to the old SceneFZ in any way.

**Comment by hex** [comment]
@kaso17 Yep, this is not the old SceneFZ. The old one is gone, only the email addresses of the users could be recovered.

**Comment by kaso17** [comment]
it's working by now
