### ISSUE TITLE
Odd Result?

### ISSUE THREAD

**Issue by jriker1** [Jackett/Jackett#3048]
Using latest Jackett for Windows.  Did a search for "General Hospital April 30 2018".  Got one result from Zoogle called "The Coming Age - Bionics Droids Transhumanism Future of Mankind".  What's up with that?

Thanks.

JR

**Comment by garfield69** [comment]
that is the zooqle site returning this result
![image](https://user-images.githubusercontent.com/6933240/39555724-88c0d524-4ecf-11e8-8af9-e29095e8d295.png)
nothing jackett can do about that.

except that if it becomes a problem we could add a andmatch to the indexer to exclude these spurious hits
