### ISSUE TITLE
[xtremezone] Exception (xtremezone): Request to https://www.myxz.org/browse.php?search=

### ISSUE THREAD

**Issue by vulpasin** [Jackett/Jackett#3049]
Hello, 

New address of www.myxz.org is https://myxz.eu/.

Please change it.

Thank you.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
This was done back on the 30th of march with c11de64a3523deb4a448bc7293d3b45b2840f6fb and included from v0.8.823 onward.      
upgrade your jackett to the latest version, or v0.8.826 at the very least, to pick up a download link fix for this indexer as well.
