### ISSUE TITLE
Login fails on yggtorrent indexer

### ISSUE THREAD

**Issue by aarsenca** [Jackett/Jackett#3050]
An error occured while testing this indexer
Exception (yggtorrent): Login failed: No form found on https://yggtorrent.is/ using form selector form[action$="/user/login"]: Parse error

**Jackett version**:  0.8.929.0
**Mono version** (if not using Windows):  Mono JIT compiler version 5.10.1.20

[log.txt](https://github.com/Jackett/Jackett/files/1965331/log.txt)

Thanks.

Andre
-------------------------------

**Comment by aarsenca** [comment]
It is now working. I just reentered my yggtorrent password in the jackett indexer settings and the test is now successful. According to my password manager, I last modified this password on March 25, 2018. The jackett error message in the original post refers to a form not found...

**Comment by JuGuSm** [comment]
Can you share yggtorrent.yml ? Still not working for me :/

**Comment by aarsenca** [comment]
It still works for me. Here is the file you are asking for.

[yggtorrent.zip](https://github.com/Jackett/Jackett/files/1976918/yggtorrent.zip)
