### ISSUE TITLE
RSS Feed URL Limit Results

### ISSUE THREAD

**Issue by coolboiime** [Jackett/Jackett#3056]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.886.0
**Mono version** (if not using Windows):  Not sure, docker image

-------------------------------

I'm having trouble trying to limit results from the RSS feed URL. I did some searches on your repo, but it says something about pagination and that I can't set the limit query.

I'm using a Transmission RSS docker image to grab the latest search torrents, but it's grabbing all 100 results every 10 minutes.

How do I limit the results in the RSS feed?

I tried `offset=0&limit=10` but it still doesn't work.

**Comment by coolboiime** [comment]
I am doing a RARBG category search, and setting the limit and offset arguments do not work.

**Comment by kaso17** [comment]
fixed via 6a4c34d5df30f242df22478c6cbcf64123dfab16
