### ISSUE TITLE
Jackett  crashes on raspbian with mono error

### ISSUE THREAD

**Issue by warsylep** [Jackett/Jackett#306]
Hi.
Jacket  0.7.219.0 installed as systemd unit
Raspbian 8
I've tried this several times now.
After first install Jackett works fine, but after a while (random) it crashes and every attempt to start it results in a crash with the log in attachment.

[log.txt](https://github.com/Jackett/Jackett/files/215521/log.txt)

Any suggestions i can try?
Thanks in advance

**Comment by flightlevel** [comment]
What version of mono are you running?
RPi are great little units, but mono is generally pretty resource hungry.
@raspdealer are you running on a Pi?
Hopefully in the not too distant future .NET core will be available with Pi support which should make these sorts of problems a thing of the past.

**Comment by warsylep** [comment]
[code]pi@rasnas:/mnt $ mono --version
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:34:50 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
pi@rasnas:/mnt $        [/code] 

Really weird..  Even after rebooting the pi,  jackett (or mono? ) will give the same error. It won't work again until i reinstall it.

**Comment by McGriddle** [comment]
I was also trying to get mono/jackett running on a pi. It worked for me *after* doing the following :smile: 

- Raspbian Jessie
- Mono v4.4.2
- Jackett 0.7.370.0

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
sudo apt-get update && apt-get dist-upgrade
sudo apt-get install mono-complete
```

**Comment by flightlevel** [comment]
This issue hasn't had activity for a while. If the issue still exists, please reopen and include full logs. https://github.com/Jackett/Jackett#troubleshooting
