### ISSUE TITLE
[rutracker] Вы ввели неверное/неактивное имя пользователя или неверный пароль (Config)

### ISSUE THREAD

**Issue by ALERTua** [Jackett/Jackett#3061]
"You entered wrong username/password" while the password is correct and the username includes **russian letters**. You can reproduce it by registering temporary user @ rutracker with russian letters in the login name and trying to use it with Jackett.
**Jackett version**:  0.8.929.0

**Comment by ngosang** [comment]
@ALERTua is this fixed?

**Comment by ALERTua** [comment]
@ngosang , nope
![image](https://user-images.githubusercontent.com/8375129/72791669-5df2fb00-3c40-11ea-9a91-28540613b092.png)

**Comment by garfield69** [comment]
Jackett 0.12.1746
