### ISSUE TITLE
BT-Scene download link is sometimes not working

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#3070]
**Jackett version**:  0.8.929 windows

when using the jackett dashboard to search bt-scene, and clicking on the downloading link of a result, sometimes  a *This 127.0.0.1 page can’t be found* error is produced.
example: 
- search for `The.Big.Bang.Theory.S11E16.720p` and click on downloading link for a result:
![image](https://user-images.githubusercontent.com/6933240/39648164-9f015860-5035-11e8-8a0b-684e4767f73e.png)

returnes:
```
This 127.0.0.1 page can’t be found
No web page was found for the web address: http://127.0.0.1:9117/dl/bt-scene/?jackett_apikey=**redacted**&path=bDhtOWRBK1dsSDkxNlVTWDBoNWxNL0RCbEp2dUxwSlhka1gwN0JEOTdJUHJyeGRvbWlFMnR1dlNsMThVSEFHcGk2THF2WEpJQjdVdW5YNXppUUk3Y0JNV0lWMDcrRXZuV1lZUU15Q1BpdXJyekhhNkJ1RklTNVFqSnJGNjVjTDlnWWhaS21NbUlFOXlzQ3dIUW5ra1IxR0V0Z084WDBIM0RRNjI4c0sxd3hWY2x2dXJ3M2tHYUk2RnhWUi9kYjFxYWUzMzBuakN0WU41b2hFa3NxSnhSY1lZdUZxblNNQVBYUmVsZkFjZEZ4dEZ6OXR6aTd4a0V1Y1k4aXZKQXNrNTZ2UDRONWhsNHgrM0FoL1hqQVBCS2N2Wm8wMk9Rc3ZaWG5CWUNnY1VvYVNtaFZoUDVzS01tSGR4QnI2bDdhb2RHZXgzK3JZU3hGajFMbjlZekdRTnRxR0tRbzNOOHZkeUIwNzlPem5uTG9vPQ2&file=The.Big.Bang.Theory.S11E16.720p.HDTV.x264-AVS%5Brarbg%5D
HTTP ERROR 404
```

**Comment by garfield69** [comment]
the bt-scene indexer builds the download link from the ID tag, which works when a .torrent is available.
but in this situation only a magnet is available and generating `https://bt-scene.cc/torrentget.php?id=6326387` for the example above returns an intermediate page with *This torrent is not available, use magnet link*
![image](https://user-images.githubusercontent.com/6933240/39650339-dbc44d9c-503b-11e8-82f5-b101789f80c3.png)

**Comment by ldexterldesign** [comment]
https://github.com/Jackett/Jackett/issues/3749 - possibly related

I suggest this issue is closed

Regards
