### ISSUE TITLE
[animebytes] Parse error: missing username param (Config)

### ISSUE THREAD

**Issue by poplolnman** [Jackett/Jackett#3073]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  8.929
**Mono version** (if not using Windows):  windows

i keep on trying to add animebytes to jackett but keep on getting missing username param when i am using the right passkey.

-------------------------------

When | Level | Message
-- | -- | --
May 05, 2018 10:54:01 AM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
May 05, 2018 10:54:01 AM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
May 05, 2018 10:54:01 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
May 05, 2018 10:54:01 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
May 05, 2018 10:54:01 AM | Info | HttpActionBinding ExecuteBindingAsync
May 05, 2018 10:54:01 AM | Info | HttpActionBinding ExecuteBindingAsync
May 05, 2018 10:54:01 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
May 05, 2018 10:54:01 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
May 05, 2018 10:54:01 AM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
May 05, 2018 10:54:01 AM | Info | ApiControllerActionSelector SelectAction
May 05, 2018 10:54:01 AM | Info | ServerConfigurationController ExecuteAsync
May 05, 2018 10:54:01 AM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.ServerConfigurationController
May 05, 2018 10:54:01 AM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.ServerConfigurationController
May 05, 2018 10:54:01 AM | Info | DefaultHttpControllerActivator Create
May 05, 2018 10:54:01 AM | Info | HttpControllerDescriptor CreateController
May 05, 2018 10:54:01 AM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
May 05, 2018 10:54:01 AM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
May 05, 2018 10:54:01 AM | Info | http://localhost:9117/api/v2.0/server/logs?_=1525531746496
May 05, 2018 10:53:52 AM | Info | IndexerApiController Dispose
May 05, 2018 10:53:52 AM | Info | IndexerApiController Dispose
May 05, 2018 10:53:52 AM | Info | Content-type='application/json; charset=utf-8', content-length=5842
May 05, 2018 10:53:52 AM | Info | IndexerApiController ExecuteAsync
May 05, 2018 10:53:52 AM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
May 05, 2018 10:53:52 AM | Error | System.Exception: Parse error ---> System.Exception: missing username param    at Jackett.Common.Indexers.AnimeBytes.<GetResults>d__21.MoveNext()    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex)    at Jackett.Common.Indexers.AnimeBytes.<GetResults>d__21.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Indexers.AnimeBytes.<PerformQuery>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Indexers.AnimeBytes.<ApplyConfiguration>d__17.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Controllers.IndexerApiController.<UpdateConfig>d__10.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\IndexerApiController.cs:line 101 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
May 05, 2018 10:53:52 AM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
May 05, 2018 10:53:52 AM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
May 05, 2018 10:53:52 AM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Config(ConfigItem[] config)'
May 05, 2018 10:53:52 AM | Info | RequiresIndexerAttribute OnActionExecutedAsync
May 05, 2018 10:53:52 AM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Config(ConfigItem[] config)'
May 05, 2018 10:53:52 AM | Error | ApiControllerActionInvoker InvokeActionAsync
May 05, 2018 10:53:52 AM | Error | ReflectedHttpActionDescriptor ExecuteAsync
May 05, 2018 10:53:52 AM | Error | Error on 20180505105352 for AnimeBytes.txtSystem.Exception: missing username param    at Jackett.Common.Indexers.AnimeBytes.<GetResults>d__21.MoveNext()     {"error":"missing username param"}
May 05, 2018 10:53:52 AM | Debug | updating Cookies  => __cfduid=d04a76c23ff6096575281b390aff507ba1525532031; transient=Lw452mj12iHgKqHV1Hi3FGpGPo2LJw0M
May 05, 2018 10:53:52 AM | Debug | WebClient(HttpWebClient): Returning OK => {"error":"missing username param"}
May 05, 2018 10:53:51 AM | Debug | WebClient(HttpWebClient).GetString(Url:https://animebytes.tv/scrape.php?torrent_pass=PI6R9kQm0VNhA1mJpaKl6M6cLM7XkT7X&type=music&searchstr=)
May 05, 2018 10:53:51 AM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Config(config=Jackett.Common.Models.DTO.ConfigItem[])'
May 05, 2018 10:53:51 AM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Config(config=Jackett.Common.Models.DTO.ConfigItem[])'
May 05, 2018 10:53:51 AM | Info | RequiresIndexerAttribute OnActionExecutingAsync
May 05, 2018 10:53:51 AM | Info | RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Config(ConfigItem[] config)'
May 05, 2018 10:53:51 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
May 05, 2018 10:53:51 AM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Config(ConfigItem[] config)'
May 05, 2018 10:53:51 AM | Info | HttpActionBinding ExecuteBindingAsync Model state is valid. Values: config=Jackett.Common.Models.DTO.ConfigItem[]
May 05, 2018 10:53:51 AM | Info | FormatterParameterBinding ExecuteBindingAsync Parameter 'config' bound to the value 'Jackett.Common.Models.DTO.ConfigItem[]'
May 05, 2018 10:53:51 AM | Info | JsonMediaTypeFormatter ReadFromStreamAsync Value read='Jackett.Common.Models.DTO.ConfigItem[]'
May 05, 2018 10:53:51 AM | Info | JsonMediaTypeFormatter ReadFromStreamAsync Type='ConfigItem[]', content-type='application/json'
May 05, 2018 10:53:51 AM | Info | FormatterParameterBinding ExecuteBindingAsync Binding parameter 'config'
May 05, 2018 10:53:51 AM | Info | HttpActionBinding ExecuteBindingAsync
May 05, 2018 10:53:51 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
May 05, 2018 10:53:51 AM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
May 05, 2018 10:53:51 AM | Info | ApiControllerActionSelector SelectAction Selected action 'Config(ConfigItem[] config)'
May 05, 2018 10:53:51 AM | Info | ApiControllerActionSelector SelectAction
May 05, 2018 10:53:51 AM | Info | IndexerApiController ExecuteAsync
May 05, 2018 10:53:51 AM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.IndexerApiController
May 05, 2018 10:53:51 AM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.IndexerApiController
May 05, 2018 10:53:51 AM | Info | DefaultHttpControllerActivator Create
May 05, 2018 10:53:51 AM | Info | HttpControllerDescriptor CreateController
May 05, 2018 10:53:51 AM | Info | DefaultHttpControllerSelector SelectController IndexerApi
May 05, 2018 10:53:51 AM | Info | DefaultHttpControllerSelector SelectController Route='indexerId:animebytes,action:config,controller:IndexerApi'
May 05, 2018 10:53:51 AM | Info | http://localhost:9117/api/v2.0/indexers/animebytes/config
May 05, 2018 10:53:47 AM | Info | IndexerApiController Dispose
May 05, 2018 10:53:47 AM | Info | IndexerApiController Dispose
May 05, 2018 10:53:47 AM | Info | Content-type='application/json; charset=utf-8', content-length=5842
May 05, 2018 10:53:47 AM | Info | IndexerApiController ExecuteAsync
May 05, 2018 10:53:47 AM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
May 05, 2018 10:53:47 AM | Error | System.Exception: Parse error ---> System.Exception: missing username param    at Jackett.Common.Indexers.AnimeBytes.<GetResults>d__21.MoveNext()    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex)    at Jackett.Common.Indexers.AnimeBytes.<GetResults>d__21.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Indexers.AnimeBytes.<PerformQuery>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Indexers.AnimeBytes.<ApplyConfiguration>d__17.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Controllers.IndexerApiController.<UpdateConfig>d__10.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\IndexerApiController.cs:line 101 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
May 05, 2018 10:53:47 AM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync

**Comment by flightlevel** [comment]
Fixed in latest release https://github.com/Jackett/Jackett/releases/tag/v0.8.953
