### ISSUE TITLE
[lostfilm] Exception (lostfilm): Input string is not a valid DateTime.: Parse error (Test)

### ISSUE THREAD

**Issue by edalex86** [Jackett/Jackett#3087]
Manual search is fine but test is failing.
**Jackett version**:  0.8.953.0

-------------------------------
[log.txt](https://github.com/Jackett/Jackett/files/1985882/log.txt)

**Comment by garfield69** [comment]
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.

**Comment by edalex86** [comment]
Hmm, And what's wrong with attached log?
Anyway, I think i Found the issue. Last episode on site http://www.lostfilm.tv/series/Trust/season_1/episode_7/ has original date "2018" not "08.0.5.2018"
Also I think generally parsing is wrong because it seaarches "eng" release date https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/LostFilm.cs#L391 
which is episode aired date and "ru" date is release date.
Html part looks like this:
`<div class="left-box">
Дата выхода ru: 08 мая 2018 г.<br/>
Дата выхода eng: 2018 г.<br/>
</div>`

**Comment by garfield69** [comment]
oh gee... I've got to get new lenses, totally missed the attachment. my bad. sorry.
should be able to sort something out soon. ;-)

**Comment by garfield69** [comment]
Bah. I thought I could just replace `eng:` with `ru:` and be done with it, but testing shows the code is more complicated than that :-(
so I'm going to pass on this, and hopefully another dev will provide the correct fix.

**Comment by edalex86** [comment]
I wish I could help you but I've struggled with compiling Jackett in VS2012 Express. :-(
My end goal with compiling it witn .Net 4.0 is even more unreachable :-D

**Comment by garfield69** [comment]
this was fixed with b6692a7dab557dae20e045da0c0baeb72e7ec551 on 30th june. closing.
