### ISSUE TITLE
[nyoo] Exception (nyoo): The remote name could not be resolved: 'nyoo.moe': An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by goku-son** [Jackett/Jackett#3088]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.886.0
**Mono version** (if not using Windows):  

-------------------------------

Not sure if this indexer is down or has gone away.

**Comment by garfield69** [comment]
the domain is returning `nyoo.moe’s server IP address could not be found.` so it looks like it has disappeared for now.

this is a mirror for the nyaa.pantsu site, so you could try switching to that indexer instead.
alternatively, according to `https://nyaa.pantsu.cat/faq`, another mirror is `https://nyaa.pt`, so if you cannot access nyaa.pantsu.cat using the nyaa.pantsu indexer, you can trying changing the SiteLink in its config and see if that mirror works instead.

if nyoo remains AWOL in  month or so or I get confirmation from someone that it has definitely shutdown then I'll delete the indexer.

**Comment by goku-son** [comment]
Thank you! Changing to nyaa.pantsu.cat did the trick!
