### ISSUE TITLE
Torrenting indexer not updated for IMDBID

### ISSUE THREAD

**Issue by 1ccs-todd** [Jackett/Jackett#3092]
**Jackett version**:  0.8.953.0
**Mono version** (if not using Windows):  5.2.0 

-------------------------------

I have been attempting to get Jackett working with Torrenting.com.  I have Jackett fully working and can query titles without problems.  The issue I have found is that CP sends an IMDBID query and the torrenting.yml file is not setup for IMDBID queries.  With CP only sending IMDBID queries, all of the queries fail.

When I manually search using a search string instead of IMDBID, the searches work fine.  Unfortunately CP is not setup to do keyword searches when using Jackett/Torrenting indexer.

_____________________________________
Examples:
Query that Succeeds:
http://x.x.x.x:9117/api/v2.0/indexers/torrenting/results/potato/?search=Game+Night+2018&user=&passkey=xxx

Query that Fails:
http://x.x.x.x:9117/api/v2.0/indexers/torrenting/results/potato/?imdb=tt2704998&user=&passkey=xxx

Error Message:
torrenting does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported.

**Comment by garfield69** [comment]
not every torrent website supports searching using the IMDBID.
Have you logged onto torrenting.com directly via your browser, and can you confirm that their search engine supports searching using IMDBID?

**Comment by 1ccs-todd** [comment]
Oh yes,  torrenting site is already based on imdbid.  Here is an example search from their own site:
https://torrenting.me/t?72;o=size;q=tt2704998#torrents

**Comment by kaso17** [comment]
IMDB ID support has been added via 1ab0827ae7f0e9bd23ba16ee3beab111e2785d51
but you also should update to the latest mster/develop CP version (it always send imdbid nad title).
