### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on https://yggtorrent.is/ using form selector form

### ISSUE THREAD

**Issue by kriegalex** [Jackett/Jackett#3099]
**Jackett version**:  0.8.953.0
**Mono version** (if not using Windows):  Mono JIT compiler version 5.10.1.47
**From docker** : linuxserver/jackett

They probably changed something again in the structure

-------------------------------

[log.txt](https://github.com/Jackett/Jackett/files/1994546/log.txt)

**Comment by Lunaden** [comment]
Just change yggtorrent.yml definition file line 103 : 

`form: form[action$="/user/login"]`

by 

`form: form[action="/user/login"]`

**Comment by flightlevel** [comment]
Is anyone else getting this issue and can they confirm @Lunaden fix resolves the issue for them. If so, it can be merged in

**Comment by Lunaden** [comment]
Oh weird.
My version : 0.8.929.0
But in this repo : https://github.com/Jackett/Jackett/blob/8cd330e5fbc556fe514044029fa3ad9bf7df1513/src/Jackett.Common/Definitions/yggtorrent.yml#L103

And the form connection on yggtorrent is :
````php
<form action="https://yggtorrent.is/user/login" method="post" id="user-login">
		<input type="text" name="id" placeholder="Pseudo" required="">
		<input type="password" name="pass" placeholder="Mot de passe" required="" autocomplete="off">
```

![image](https://user-images.githubusercontent.com/34348877/39954997-79bf0aea-55c9-11e8-8486-f1f2a97fc807.png)

**Comment by garfield69** [comment]
yes that is correct.
 the `$=` in the yml form selector tells jackett to pick the form that has an `action` attribute, which ends in `/user/login`.

**Comment by Lunaden** [comment]
Ok thx for the explanation.

I've had this error to before : `Login failed: No form found on https://yggtorrent.is/ using form selector form[action$="/user/login"`

The only things i have done is modifying this line : form[action$="/user/login"]
and try to connect directly to the website to see if the login/password combination works.

Now on Version 0.8.975.0 it works out of the box.

So it's just a random error ?
