### ISSUE TITLE
SCC Archive not working

### ISSUE THREAD

**Issue by Drayden** [Jackett/Jackett#31]
Sonarr can't find any TV packs releases from the SceneAccess archive through Jackett. It seems the TV Packs Archive category (cat=26) is not being picked by Jackett. Other TV categories other than Archive are picked fine.

**Comment by luxus** [comment]
i did download something from the archive.. 
but i have problems with scc it not download series on release.. just when i search from the wanted section of sonarr.
i don't know why it is not finding anything on rss update and just on search.

**Comment by WhatFox** [comment]
I am going to change non empty searches to search both standard and archive categories
