### ISSUE TITLE
any existing tracker running xbtit?

### ISSUE THREAD

**Issue by valantislevas** [Jackett/Jackett#310]
is there any tracker that is working jackett with xbtit tracker files?

**Comment by armani316** [comment]
@kaso17 @flightlevel Do you guys know the answer to this question by any chance?

**Comment by flightlevel** [comment]
@valantislevas What's the reason for this question? Are you trying to add a new tracker in?

**Comment by valantislevas** [comment]
i am ok now!! thanks!
