### ISSUE TITLE
Request indexer https://skytorrents.lol/

### ISSUE THREAD

**Issue by loady** [Jackett/Jackett#3103]
Sky torrents has gone but there seems to be a new version running that works well but is not included on the indexers within jackett, can it be added ? https://skytorrents.lol/

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by loady** [comment]
hmmm...not my arena. I tried just modding one of the current one by changing its url but it didn't work, although it links to the website

**Comment by ash121121** [comment]
they have moved to https://www.skytorrents.to the rss works there

**Comment by garfield69** [comment]
updated jackett yesterday for .to with  pre-release 0.10.505 has the automated fix.
or you can manually change it on your jackett dashboard with the wrench, and after editing the sitelink click 
OKAY. if you get an error just click CLOSE and repeat. it should work the second time.

**Comment by garfield69** [comment]
skytorrentsclone now redirects to https://btdb.eu which we already have as BTDB.
i'll remove this indexer at the end of the month if I don't see objections or get an alternate domain to its own site again.

**Comment by garfield69** [comment]
ok turns out its just https://www.skytorrents.to/ that redirects to BTDB
https://www.skytorrents.lol/ is still the original clone. 
but changes made to support .to a while back need to be reversed to restore .lol's dl links and query parm for searches.

**Comment by garfield69** [comment]
4295e65dfe9d3138189a359cba5161b02ca6b451

**Comment by ilike2burnthing** [comment]
https://skytorrents.to/ - Error 522 - Connection timed out
Also check:
https://skytorrents.to/top100
https://skytorrents.to/top100?sort=created

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.skytorrents.lol/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
https://www.skytorrents.to/ - Error 504 - Gateway time-out
same for .org and .net

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://www.skytorrents.to/ - Error 504 - Gateway time-out
> same for .org and .net

**Comment by garfield69** [comment]
v0.18.502
