### ISSUE TITLE
Torrent9 definition - Able to search but not able to download.

### ISSUE THREAD

**Issue by sbeaudoin** [Jackett/Jackett#3104]
Jackett version 0.8.975.0 on Windows 10.

**Context**
Have been able to search for a movie for the torrent9 site, but a download does not work.

**Diagnostic**
Deduced that Jackett generate an url to download to torrent file based on the link.  In this case, the link of the search result page is :

`http://www.torrent9.red/torrent/60989/red-sparrow-french-dvdrip-2018`

It takes the id 60989 and generate a new url to download the torrent file by replacing "torrent" with "get-torrent" :

`http://www.torrent9.red/get-torrent/60989/red-sparrow-french-dvdrip-2018`

This does not work anymore.  For example, for this film, the correct download link should be :

`http://www.torrent9.red/downloading/4a6f6b508803b830b2f5a5777b74d938a749fc04/60989`

This link is available on the "Télécharger le torrent" button shown on the page of the original link.  As you can see, The new download link have a generated id included in the url.  My test show this number is associated to this particular movie and not generated each time.  I suspect this is a hash generated from one of the movie information, possibly the title.

**What I tried**
I tried to understand and modify the yaml file "C:\ProgramData\Jackett\Definitions\torrent9.yml" based on the documentation you provide on this site.  Sadly, I see no reference to obtain data from a different page and have no tools to debug the changes I would make.

I hope these informations will help you to produce a correction and to provide it to us the fastest possible as good torrent sources for french movies are very very very rare.

Thank you.

**Comment by kaso17** [comment]
fixed via 96af05fbefdabbabb6d2810ee8ce18cdeeb1c142, thank you for investigating

**Comment by sbeaudoin** [comment]
Wow!  This is fast.  I thought the correction will be wayyyy more difficult than this.  
Thanks!

**Comment by sbeaudoin** [comment]
Sorry, but I don't think it works.  I downloaded the new torrent9.yml file to try it and it gives me this :

> CardigannIndexer (torrent9): Download selector a[href^="/downloading/"] didn't match:

Followed by the html of what seems the main page of torrent9 site.

**Comment by kaso17** [comment]
v0.8.994 contains the upodated file now
Please share an enhanced log showing the search+download

**Comment by kaso17** [comment]
Looking at the error description it looks like you correctly replaced the yml file.
I suspect that torrent9 might not immediately add torrent files for all releases which might cause this error on very new releases. Please observe it accordingly.
