### ISSUE TITLE
Problem with Horriblesubs

### ISSUE THREAD

**Issue by saitoh183** [Jackett/Jackett#3105]
[horriblesubs] Exception (horriblesubs): Request to http://horriblesubs.info/lib/latest.php?value= failed (Error BadGateway) - The tracker seems to be down.: Request to http://horriblesubs.info/lib/latest.php?value= failed (Error BadGateway) - The tracker seems to be down. (Test)

**Jackett version**:  0.8.975.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
Is this still a problem for you?
For me it's working (again).
Looks like a temporary outage.

**Comment by saitoh183** [comment]
@kaso17 

yup it is back
