### ISSUE TITLE
[yify] Exception (yify): String was not recognized as a valid DateTime.: Parse error (Test)

### ISSUE THREAD

**Issue by tinefin** [Jackett/Jackett#3106]
When testing yify indexer in jackett web UI on http://127.0.0.1:9117/UI/Dashboard by hitting the "test" button, I get a red box pop up saying:

```
 An error occured while testing this indexer
Exception (yify): String was not recognized as a valid DateTime.: Parse error
Click here to open an issue on GitHub for this indexer.
```
### Tried:
Unloading and loading jackett again. Does not fix the issue.

### Software versions
OS: Mac OS High Sierra 10.13.4
Mono version: 5.10.0.160
Jackett version: 0.8.987.0

### Enhanced log:
https://gist.github.com/tinefin/bbe1d36da169869040b065ca726a8a50

**Comment by kaso17** [comment]
They've a small problem with their API (returning empty dates).
Otherwise 086d8b32e95bc06daee03523a6a34076d826b69a will fix it too.
