### ISSUE TITLE
[Torrent9] Getting release from indexer failed

### ISSUE THREAD

**Issue by tmallet** [Jackett/Jackett#3109]
Hi,
I have a problem since 2 days. When I try to download something from Sonarr using Torrent9 indexer, I get this error :
`Downloading torrent file for episode 'Silicon Valley S05E08 FINAL HDTV VOSTFR ' failed since it no longer exists (http://192.168.1.34:9117/dl/torrent9/?jackett_apikey=(removed)&path=VEdmcG1pUWkzeHdENklIbGNJd0dRZFFPL1lNZHI3dXlXOTlKK0h3M0tKWEV6WW5WWEN6cXpXaWtxV24rMUUyaU8va2l2dUJkWFZVMTNxZENpN2FZQnJzak5WVzZOWm5vMEFhMThoZktQWnB5U3BTZC9HaVdIV1FhNU9wYjhwaGlhZ3ZoamNDbTgrQzgzYkcxdXptUCtGMkROZWxsQ2FNUnNyZmVvL3RnM0pTeDZOSVRacmVEc24rWVJYN3piRElKeEhidFlXRFYrbGluZityN0JzWnp4WnlmaGJwZE5IRG5LWXhtakEvNGRLRER3cE9mY0x5bUVCM1RPMFUvZFFaV1dMZ1RhL01jQmhIa2E2dHR1aDdUajZCSzErQ0NwSy9QM1A0MExJakVSc0JtZ1gwU3V1RnJmVk54ZnpyWENFVDgxNkJzd2tucmVNUGxnVHpnNjdzRG1mRWx2d3BxbFd4WUM4dXc4V1dlZzkyeVJVZVJncksxK0xqOVVIZVpFdzBkZkFxZk43bytPU1F2TzlValEwTWFDQT090&file=Silicon+Valley+S05E08+FINAL+HDTV+VOSTFR+): HTTP request failed: [404:NotFound] [GET] at [http://192.168.1.34:9117/dl/torrent9/?jackett_apikey=iyhp2d2ca04b1upa1ax30ve2qzr4dgqv&path=VEdmcG1pUWkzeHdENklIbGNJd0dRZFFPL1lNZHI3dXlXOTlKK0h3M0tKWEV6WW5WWEN6cXpXaWtxV24rMUUyaU8va2l2dUJkWFZVMTNxZENpN2FZQnJzak5WVzZOWm5vMEFhMThoZktQWnB5U3BTZC9HaVdIV1FhNU9wYjhwaGlhZ3ZoamNDbTgrQzgzYkcxdXptUCtGMkROZWxsQ2FNUnNyZmVvL3RnM0pTeDZOSVRacmVEc24rWVJYN3piRElKeEhidFlXRFYrbGluZityN0JzWnp4WnlmaGJwZE5IRG5LWXhtakEvNGRLRER3cE9mY0x5bUVCM1RPMFUvZFFaV1dMZ1RhL01jQmhIa2E2dHR1aDdUajZCSzErQ0NwSy9QM1A0MExJakVSc0JtZ1gwU3V1RnJmVk54ZnpyWENFVDgxNkJzd2tucmVNUGxnVHpnNjdzRG1mRWx2d3BxbFd4WUM4dXc4V1dlZzkyeVJVZVJncksxK0xqOVVIZVpFdzBkZkFxZk43bytPU1F2TzlValEwTWFDQT090&file=Silicon+Valley+S05E08+FINAL+HDTV+VOSTFR+]
`
Jackett version : 0.8.975
Mono version : 4.6.2

**Comment by dany8075** [comment]
same thing for me with the pre-release version 0.8.975

**Comment by kaso17** [comment]
fixed in v0.8.994
