### ISSUE TITLE
Can not add bluetigers.ca

### ISSUE THREAD

**Issue by Lethtel** [Jackett/Jackett#311]
Hi guys,

i'm trying to add bluetigers.ca to jackett but it returns me that error : 
Configuration failed: Une erreur s'est produite lors de l'envoi de la demande.

I got no problem with Xthor so far.

here is the part of the log that should interest you :
http://pastebin.com/e8YNuG13

Seems to be an auth problem.

If you guys have an idea, will be glad to test it out :o

Thanks for your time.

**Comment by JigSawFr** [comment]
Maybe a SSL issue, try starting Jackett with SSL FIX option :)

**Comment by Lethtel** [comment]
So, searched a bit how to active this, and finally tried witch an admin cmd window in my jacket folder.

Tried to launch "jackettconsole.exe -s" with a "-f true" argument, same error.
So i tried "-n true" and even "-f true -n true" still the exact same error

http://pastebin.com/ZakWu04t

Maybe am i trying it wrong ? (not very used to all that :p)
If not, have you another lead ?

Once again, thanks :)

**Comment by JigSawFr** [comment]
Maybe related to PHX older problem, Jackett doesn't support all ciphers for SSL.
Do you noticed a different SSL certificate from tracker ?

**Comment by Lethtel** [comment]
i don't know as i never feel the need to use SSL.

I just know they changed their infrastructure mid-january, but i don't know if it's related.
Since then other ppl would have report a bug with this tracker i think.

Is there anything else i can do to check/help you ?

**Comment by ElYoM** [comment]
I have the exact same problem, it's impossible to add Bluetigers in Jackett. Thanks in advance for the resolution.

**Comment by JigSawFr** [comment]
@ElYoM PR is building on appveyor. Jackett will now support TLS 1.1 & TLS 1.2
Bluetigers support only these protocols now. Tested on my dev plateform without problem (with mono too)

**Comment by JigSawFr** [comment]
Now fixed by #337. Enjoy !
