### ISSUE TITLE
Year on title cant find search on medusa/sickrage

### ISSUE THREAD

**Issue by albertehc** [Jackett/Jackett#3111]
I have a problem searching with medusa and sickrage on the trackets xBytes and torrentland, they put the actual year on the filename so the program cant find the file,
For example the name:
The Good Fight (2018) S02E11 [1080p WEBDL x264] [ESP AC3 5 1 ENG AC3 5 1] [SUBS]
And the showtv is from 2017

**Comment by Diablobait** [comment]
Same problem with the .
for example:
Como.defender.a.un.asesino.S04E12.1080p.AMZN-WEBDL.Dual.Subs.x264-Akane.mkv
