### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: Selector

### ISSUE THREAD

**Issue by sybri** [Jackett/Jackett#3117]
Exception (yggtorrent): Login failed: Selector "a[href$="/user/logout"]" didn't match: 

in yggtorrent the dom is `<li><a href="https://yggtorrent.is/user/logout"> Déconnexion</a></li>`

it shoud work

**Jackett version**:  0.8.994.0
**Mono version** (if not using Windows):  Mono JIT compiler version 5.4.1.6 (tarball Wed Nov  8 20:37:08 UTC 2017)

-------------------------------

**Comment by kaso17** [comment]
please check your credentials and provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
