### ISSUE TITLE
[HDME] Different passkey on download locally

### ISSUE THREAD

**Issue by Hackerpcs** [Jackett/Jackett#3121]
**Jackett version**:  0.8.997.0

-------------------------------

On manual search, the "download locally" button on results from HDME gives a torrent file with a different passkey every time. Most likely it is random so the torrent doesn't work and the tracker needs to be edited with your passkey on the client after adding

**Comment by kaso17** [comment]
fixed via 0a07738c5be915947c227a054d3814eb0afa4280
