### ISSUE TITLE
[tvchaosuk] Exception (tvchaosuk): '', hexadecimal value 0x02, is an invalid character. Line 515, position 54.: '', hexadecimal value 0x02, is an invalid character. Line 515, position 54. (Test)

### ISSUE THREAD

**Issue by szukalski** [Jackett/Jackett#3123]
Jackett Version 0.8.997.0

Just started getting this error message for tvchaos last night:

"
[tvchaosuk] Exception (tvchaosuk): '', hexadecimal value 0x02, is an invalid character. Line 515, position 54.: '', hexadecimal value 0x02, is an invalid character. Line 515, position 54. (Test)
"

**Comment by kaso17** [comment]
fixed via af94dd27575c9236d34314f7833ac600a1b0edba
