### ISSUE TITLE
RGU comming back with Invalid searches

### ISSUE THREAD

**Issue by mstrdraco** [Jackett/Jackett#3129]
When doing a search via Radarr using Jackett.. For example Avengers Infinity war.. RGU is returning Invalid searches.   I've attached a screenshot.  
![rgu error](https://user-images.githubusercontent.com/37802459/40363003-30e8d258-5d9c-11e8-8bbb-7f45be381b62.png)

**Jackett version**:  0.8.1000.0
**Mono version** (if not using Windows):   5.10.1.38

-------------------------------

**Comment by mstrdraco** [comment]
When I did a Manual Search saw this in the logs- 

Jackett.Common.IndexerException: Exception (RGU): Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index ---> System.Exception: Parse error ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException () [0x0000c] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at Jackett.Common.Indexers.CardigannIndexer+<PerformQuery>d__29.MoveNext () [0x00b92] in <cba6f3e462374e3baeccb5cc53a14aea>:0     --- End of inner exception stack trace ---   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError (System.String results, System.Exception ex) [0x00064] in <cba6f3e462374e3baeccb5cc53a14aea>:0    at Jackett.Common.Indexers.CardigannIndexer+<PerformQuery>d__29.MoveNext () [0x01a57] in <cba6f3e462374e3baeccb5cc53a14aea>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__64.MoveNext () [0x00091] in <cba6f3e462374e3baeccb5cc53a14aea>:0     --- End of inner exception stack trace ---   at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__64.MoveNext () [0x000ee] in <cba6f3e462374e3baeccb5cc53a14aea>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x0006b] in <cba6f3e462374e3baeccb5cc53a14aea>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <15d2ea3aab9344afb64fdf5699a5fd28>:0    at Jackett.Controllers.ResultsController+<Results>d__13.MoveNext () [0x00145] in <64b7bf99651e4985b9007c1d19a3eb36>:0
--
May 22, 2018 09:35:34 AM | Error |

**Comment by kaso17** [comment]
@Jachryl can you have a look at this?

If RGU always will return unrelated results you should add a rows andmatch filter (example: https://github.com/Jackett/Jackett/blob/a3c685388eae9389d1f29be7671250d5ca957b95/src/Jackett.Common/Definitions/eztv.yml#L28-L29)

**Comment by mstrdraco** [comment]
Seems to have helped I only have 1 result now it seems.. I'm assuming it's working correctly and I put it in the proper spot.  It's located : 
  "only_free": "{{ if .Config.onlyfree }}1{{else}}0{{end}}"

    rows:
      selector: tr.browse_color, tr[id^="kdescr"]
      filters:
        - name: andmatch
      after: 1
    fields:

**Comment by kaso17** [comment]
508125e68fe386b8c726e710893160197d9062dc should be a better fix
