### ISSUE TITLE
ttn giving lots of bad matches

### ISSUE THREAD

**Issue by Terebi42** [Jackett/Jackett#314]
Did a manual search (via sonarr) for 
Blue's Room - 1x01 - Snacktime Playdate

TTN gave many many results with no obvious relationship to the search

torrent	
0.1 minutes
Blindspot.S01E18.1080p.HDTV.X264-DIMENSION	transmitTheNet	2.4 GB	1 / 0	HDTV-1080p		
torrent	
7.3 minutes
Hunters.S01E02.720p.WEB-DL.DD5.1.H.264-VietHD	transmitTheNet	1.3 GB	3 / 0	WEBDL-720p		
torrent	
0.1 minutes
Hunters.S01E02.1080p.WEB-DL.DD5.1.H.264-VietHD	transmitTheNet	1.6 GB	5 / 0	WEBDL-1080p		
torrent	
68.3 minutes
Castle.S08E18.Backstabber.720p.WEB-DL.DD5.1.H.264	transmitTheNet	1.4 GB	3 / 0	WEBDL-720p		
torrent	
30.3 minutes
Castle.S08E18.Backstabber.1080p.WEB-DL.DD5.1.H.264	transmitTheNet	1.7 GB	3 / 0	WEBDL-1080p		
torrent	
62.3 minutes
Supergirl.S01E20.Better.Angels.1080p.WEB-DL.DD5.1.H.264	transmitTheNet	1.6 GB	6 / 0	WEBDL-1080p		
torrent	
64.3 minutes
Supergirl.S01E20.Better.Angels.720p.WEB-DL.DD5.1.H.264	transmitTheNet	1.3 GB	4 / 0	WEBDL-720p		
torrent	
0.1 minutes
the.island.with.bear.grylls.s03e04.hdtv.x264-c4tv	transmitTheNet	614.2 MB	1 / 0	SDTV		
torrent	
0.1 minutes
the.island.with.bear.grylls.s03e04.720p.hdtv.x264-c4tv	transmitTheNet	1.8 GB	1 / 0	HDTV-720p		
torrent	
0.1 minutes
the.island.with.bear.grylls.s03e03.hdtv.x264-c4tv	transmitTheNet	608.0 MB	1 / 0	SDTV		
torrent	
0.1 minutes
the.island.with.bear.grylls.s03e03.720p.hdtv.x264-c4tv	transmitTheNet	1.7 GB	1 / 0	HDTV-720p		
torrent	
0.1 minutes
The.Voice.S10E17.HDTV.x264-ALTEREGO	transmitTheNet	676.1 MB	1 / 0	SDTV		
torrent	
0.1 minutes
Scorpion.S02E23.1080p.HDTV.X264-DIMENSION	transmitTheNet	4.4 GB	1 / 0	HDTV-1080p		
torrent	
0.1 minutes
dracula.2016.101.1080p.web-ifh	transmitTheNet	1.7 GB	2 / 0	HDTV-1080p		
torrent	
0.1 minutes
the.a.word.s01e05.1080p.hdtv.x264-moritz	transmitTheNet	1.8 GB	1 / 0	HDTV-1080p		
torrent	
0.1 minutes
the_a_word.1x05.720p_hdtv_x264-fov	transmitTheNet	821.2 MB	1 / 0	HDTV-720p		
torrent	
0.1 minutes
The.A.Word.S01E05.HDTV.x264-ORGANiC	transmitTheNet	280.8 MB	1 / 0	SDTV		
torrent	
0.1 minutes
Filthy.Rich.S01E20.1080p.HDTV.x264-FiHTV	transmitTheNet	1.8 GB	1 / 0	HDTV-1080p		
torrent	
0.1 minutes
The.A.Word.S01E05.720p.HDTV.x264-ORGANiC	transmitTheNet	821.0 MB	1 / 0	HDTV-720p		
torrent	
0.1 minutes
The.Real.Housewives.of.Potomac.S01E12.Reunion.Part.2.1080p.BRAV.WEBRip.AAC2.0.x264-BTW	transmitTheNet	1.3 GB	2 / 0	WEBDL-1080p		
torrent	
0.1 minutes
The.Real.Housewives.of.Potomac.S01E12.Reunion.Part.2.720p.BRAV.WEBRip.AAC2.0.x264-BTW	transmitTheNet	824.1 MB	2 / 0	WEBDL-720p		
torrent	
0.1 minutes
Coast.New.Zealand.S01E01.HDTV.x264-FiHTV	transmitTheNet	395.0 MB	1 / 0	SDTV		
torrent	
0.1 minutes
Disney.Tsum.Tsum.S01E18.Hunny.Fountain.720p.WEB-DL.AAC2.0.H.264-TVSmash	transmitTheNet	62.4 MB	2 / 0	WEBDL-720p		
torrent	
0.1 minutes
Disney.Tsum.Tsum.S01E20.Tsum.Tsum.Grand.Prix.1080p.WEB-DL.AAC2.0.H.264-TVSmash	transmitTheNet	78.1 MB	1 / 0	WEBDL-1080p		
torrent	
0.1 minutes
Disney.Tsum.Tsum.S01E19.Ninja.Castle.1080p.WEB-DL.AAC2.0.H.264-TVSmash	transmitTheNet	80.2 MB	1 / 0	WEBDL-1080p		
torrent	
0.1 minutes
Disney.Tsum.Tsum.S01E18.Hunny.Fountain.1080p.WEB-DL.AAC2.0.H.264-TVSmash	transmitTheNet	78.7 MB	1 / 0	WEBDL-1080p		
torrent	
0.1 minutes
holby.city.s18e28.720p.hdtv.x264-angelic	transmitTheNet	883.6 MB	1 / 0	HDTV-720p		
torrent	
0.1 minutes
Disney.Tsum.Tsum.S01E20.Tsum.Tsum.Grand.Prix.720p.WEB-DL.AAC2.0.H.264-TVSmash	transmitTheNet	62.8 MB	1 / 0	WEBDL-720p		
torrent	
0.1 minutes
Disney.Tsum.Tsum.S01E19.Ninja.Castle.720p.WEB-DL.AAC2.0.H.264-TVSmash	transmitTheNet	63.6 MB	1 / 0	WEBDL-720p		
torrent	
0.1 minutes
Coast.New.Zealand.S01E01.720p.HDTV.x264-FiHTV	transmitTheNet	1.2 GB	1 / 0	HDTV-720p		
torrent	
0.1 minutes
The.Voice.S10E17.720p.HDTV.x264-ALTEREGO	transmitTheNet	2.1 GB	2 / 0	HDTV-720p		
torrent	
0.1 minutes
Mike.Tyson.Mysteries.S02E11.Life.Is.But.a.Dream.1080p.REPACK.WEB-DL.DD5.1.H.264-BTN	transmitTheNet	424.5 MB	2 / 0	WEBDL-1080p		
torrent	
0.1 minutes
Mike.Tyson.Mysteries.S02E11.Life.Is.But.a.Dream.720p.REPACK.WEB-DL.DD5.1.H.264-BTN	transmitTheNet	345.1 MB	2 / 0	WEBDL-720p		
torrent	
8.3 minutes
Damien.S01E07.1080p.WEB-DL.DD5.1.H.264-VietHD	transmitTheNet	1.6 GB	3 / 0	WEBDL-1080p		
torrent	
8.3 minutes
Damien.S01E07.720p.WEB-DL.DD5.1.H.264-VietHD	transmitTheNet	1.3 GB	2 / 0	WEBDL-720p		
torrent	
14.3 minutes
Thronecast-Game.Of.Thrones.The.Story.So.Far.2016.720p.HDTV.x264-CRAVERS	transmitTheNet	1.3 GB	6 / 1	HDTV-720p		
torrent	
63.3 minutes
NCIS.Los.Angeles.S07E22.Granger.O.1080p.WEB-DL.DD5.1.H.264	transmitTheNet	1.7 GB	3 / 0	WEBDL-1080p		
torrent	
66.3 minutes
NCIS.Los.Angeles.S07E22.Granger.O.720p.WEB-DL.DD5.1.H.264	transmitTheNet	1.4 GB	4 / 0	WEBDL-720p		
torrent	
86.3 minutes
Wicked.Tuna.S05E11.720p.HDTV.x264-FINDERS	transmitTheNet	1.9 GB	1 / 0	HDTV-720p		
torrent	
90.3 minutes
carson.daly.2016.03.24.zack.snyder.720p.hdtv.x264-crooks	transmitTheNet	606.6 MB	1 / 0	HDTV-720p		
torrent	
101.3 minutes
carson.daly.2016.03.24.zack.snyder.hdtv.x264-crooks	transmitTheNet	180.4 MB	1 / 0	SDTV		
torrent	
102.3 minutes
Peter.Kays.Comedy.Shuffle.S01E01.720p.WEB.h264-spamTV	transmitTheNet	492.4 MB	2 / 0	WEBDL-720p		
torrent	
102.3 minutes
i.want.my.wife.back.s01e01.720p.hdtv.x264-tla	transmitTheNet	475.9 MB	1 / 0	HDTV-720p		
torrent	
105.3 minutes
i.want.my.wife.back.s01e01.hdtv.x264-tla	transmitTheNet	177.4 MB	1 / 0	SDTV		
torrent	
106.3 minutes
raw.travel.s01e01.720p.hdtv.x264-ascendance	transmitTheNet	635.8 MB	1 / 0	HDTV-720p		
torrent	
107.3 minutes
raw.travel.s01e01.hdtv.x264-ascendance	transmitTheNet	215.0 MB	1 / 0	SDTV		
torrent	
3.3 hours
Better.Call.Saul.S02.1080p.WEB-DL.DD5.1.H	transmitTheNet	17.6 GB	3 / 0	WEBDL-1080p		
torrent	
5.2 hours
Plebs S03E04 The Cupid 720p WEB-DL AAC2.0 H.264-SFT	transmitTheNet	701.5 MB	2 / 0	WEBDL-720p		
torrent	
5.2 hours
RuPauls.Drag.Race.S08E07.Shady.Politics.1080p.WEB-DL.AAC2.0.H.264-RTN	transmitTheNet	1.5 GB	1 / 0	WEBDL-1080p		
torrent	
5.2 hours
balls.deep.0101-yestv	transmitTheNet	160.5 MB	1 / 0	Unknown

**Comment by flightlevel** [comment]
Fixed in latest release
