### ISSUE TITLE
[demonoid] "An error occurred while updating this indexer" 

### ISSUE THREAD

**Issue by cpthook26** [Jackett/Jackett#3141]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by Samsonait** [comment]
ay 30, 2018 01:32:41 PM | Error | ApiControllerActionInvoker InvokeActionAsync
-- | -- | --
May 30, 2018 01:32:41 PM | Error | ReflectedHttpActionDescriptor ExecuteAsync

Jacket Version:  Jackett Version 0.8.1039.0 
Docker Container in UnRaid

**Comment by kaso17** [comment]
the log is incomplete, please provide the full log (including all HTML output).
Site URL must be https://www.demonoid.pw/

**Comment by Samsonait** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/2055204/log.txt)

This is the only log i could find in the docker container, if u want more logs then point me the right way :-)
Enhanced loggin is on. From what i can see from the entrys this is a HTML log file.

**Comment by cpthook26** [comment]
Hello..  I am so sorry for not actually looking at my post after submitting.  Thanks for not closing my incident.  I've attached the portion of the log where I am trying to re-add/ re-configure the tracker.  This tracker has always worked for me through Jackett up until the day I posted this incident originally.

[DemonoidLogs.txt](https://github.com/Jackett/Jackett/files/2056355/DemonoidLogs.txt)

**Comment by Samsonait** [comment]
Any updates on this issue?

**Comment by flightlevel** [comment]
@Samsonait While that is an enhanced log, you haven't replicated the problem (looks like you were on pirate bay)
@cpthook26 Looks like you had an issue with awesomehd

Turn on enhanced logging, then replicate the problem i.e. clicking test on Demonoid or adding Demonid

**Comment by Samsonait** [comment]
When adding Demonoid with url https://www.demonoid.pw/

 An error occured while updating this indexer
Found no results while trying to browse this tracker

When adding Demonoid with url https://demonoid.pw/

I get an credential error, but its the right credentials i checket them.

Again here are the logs:

https://paste.ubuntu.com/p/C7vyMGjtHQ/

At the bottom there are some red lines:

https://paste.ubuntu.com/p/rnbbdwgZBH/

And this one:

https://paste.ubuntu.com/p/7DPS7ydS6V/


If u need another log i will gladly hear it. Just updated Docker and still the issue persist.

**Comment by kaso17** [comment]
@kurankat @Samsonait : `Fatal Error. Please try again in a moment. Stage 1 error: Broken reverse proxy chain jump: rp2->rp3 (Code 113: Connection reset by peer: socket read error)`
looks like a (temporary) server problem. please check again and provide a new enehanced log if it's still a problem

**Comment by Samsonait** [comment]
@kaso17 Alright, then its an connection reset by peer for a full week now. DNS isnt blocking it. I can provide another log.

Errors:

https://paste.ubuntu.com/p/k6Vpyc3FBK/

Full log:

https://paste.ubuntu.com/p/9mtcHbSX8r/

I get these logs out of the web application. If u want another log tell me where to look ;-)

Thanks for youre patience.

**Comment by Samsonait** [comment]
@kaso17 Alright, then its an connection reset by peer for a full week now. DNS isnt blocking it. I can provide another log.

Errors:

https://paste.ubuntu.com/p/k6Vpyc3FBK/

Full log:

https://paste.ubuntu.com/p/9mtcHbSX8r/

I get these logs out of the web application. If u want another log tell me where to look ;-)

Thanks for youre patience.

**Comment by kaso17** [comment]
If it's happening all the time please try running curl form the command line:
`curl "https://www.demonoid.pw/files/?category=0&subcategory=All&quality=All&seeded=2&to=1&query=&external=2"`
If that works try deleting/readding the indexer (maybe some cookies are causing the reverse proxy to fail).

**Comment by Samsonait** [comment]
This is the output when run your curl command:

# curl "https://www.demonoid.pw/files/?category=0&subcategory=All&quality=All&seeded=2&to=1&query=&external=2"
<span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">Fatal Error. Please try again in amoment. <br>
            <span style="font-size: 11px;color: red">Stage 1 error: Broken reverse proxy chain jump: rp4->rp5(Code 113: Connection reset by peer: socket read error)<br>
            Staff notified, no action required.</span></span>#

This is the output when giving it a curl -v https://www.demonoid.pw

 curl -v "https://www.demonoid.pw"
* Rebuilt URL to: https://www.demonoid.pw/
*   Trying 104.31.17.3...
* Connected to www.demonoid.pw (104.31.17.3) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: sni152824.cloudflaressl.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: EC
*        certificate version: #3
*        subject: OU=Domain Control Validated,OU=PositiveSSL Multi-Domain,CN=sni152824.cloudflaressl.com
*        start date: Sun, 03 Jun 2018 00:00:00 GMT
*        expire date: Mon, 10 Dec 2018 23:59:59 GMT
*        issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO ECC Domain Validation Secure Server CA 2
*        compression: NULL
* ALPN, server accepted to use http/1.1
> GET / HTTP/1.1
> Host: www.demonoid.pw
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Wed, 06 Jun 2018 17:28:18 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d5c19ae29221aa852bf97ce180209fb831528306098; expires=Thu, 06-Jun-19 17:28:18 GMT; path=/; domain=.demonoid.pw; HttpOnly
< Location: /?ntps=5&g=XCEE156
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 426c983ade012c60-AMS
<
* Connection #0 to host www.demonoid.pw left intact
#


Litery getting an error right now in browser:

Fatal Error. Please try again in a moment.
Stage 1 error: Broken reverse proxy chain jump: rp6->rp7 (Code 113: Connection reset by peer: socket read error)
Staff notified, no action required.

Im pulling my hair ATM.

**Comment by kaso17** [comment]
There's not much you can do. It's a problem on the Demonoid side. I don't know their infrastructure but some users might be more affected by this than others.

**Comment by Samsonait** [comment]
Alright! Thanks for the reply :-)
