### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): An attempt was made to access a socket in a way forbidden by its access permissions 104.27.216.28:443: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by apcrcom** [Jackett/Jackett#3147]
[log.txt](https://github.com/Jackett/Jackett/files/2041668/log.txt)
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
something is blocking the access (some magic anti malware program/firewall?). please disable these. Are other indexers working?
