### ISSUE TITLE
[YGGTorrent] Search manuel sonarr/radarr not work.

### ISSUE THREAD

**Issue by D4rk56** [Jackett/Jackett#3149]
**Jackett version**:  Version 0.8.1027.0
**Mono version** : Running docker : Linuxserver.io - Jackett

At the time of starting a manual search, the loading is frozen and the connection with the tracker fails.
-------------------------------
Log : [https://pastebin.com/giK07syU](url)

**Comment by kaso17** [comment]
`Exception (yggtorrent): Error getting response stream (ReadDoneAsync2): ReceiveFailure ---> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error getting response stream (ReadDoneAsync2): ReceiveFailure`

That looks like a low level network problem. Are all indexers affected or just specific ones?

**Comment by kaso17** [comment]
I guess something is messing with your connectivity, ISP blocking ygg?

**Comment by D4rk56** [comment]
I do not see anything that could block =/

**Comment by kaso17** [comment]
check the log for the actual link jackett is trying to access (just before the error in enhanced logging mode) and try accessing it via some other http client (curl, wget) from the same machine/container

**Comment by D4rk56** [comment]
Same problem with another server, same image..

**Comment by kaso17** [comment]
Which mono version are you using? #3191 might be related.

**Comment by Celedhrim** [comment]
Hi !

I have the same issue , using mono 5.12.0.226-0xamarin3+debian9b1 , rollback to mono 5.8.0.127-0xamarin5+debian9b1 , and no more having this issue.

**Comment by Celedhrim** [comment]
I tried with 5.14.0.87 (tarball Sun May 20 09:50:07 UTC 2018)

Same issue , I rollback to 5.8 :)

**Comment by D4rk56** [comment]
Close the issue, it works. Thanks .
