### ISSUE TITLE
[demonoid] Exception (demonoid): Specified argument was out of the range of valid values.Parameter name: index: Parse error (Test)

### ISSUE THREAD

**Issue by m-s-y** [Jackett/Jackett#3151]
**Jackett version**:  Version 0.8.1027.0
**Mono version** (if not using Windows):  Mono JIT compiler version 5.12.0.226

**Comment by kaso17** [comment]
This error (ArgumentOutOfRangeException) was caused by a Demonid change. They removed the download link from the search results. 9c5cda72da120d6ddb130b6849203cc538966df7 fixes it.
