### ISSUE TITLE
[REQ] Add Audiobookbay to trackers

### ISSUE THREAD

**Issue by goldharv** [Jackett/Jackett#3160]
Please add Audiobookbay.nl to Jackett's trackers. It's an open tracker, but you have to register by creating a user id and a password. It has torrents for audiobooks. I don't know if there's an API. To get the torrent downloaded from the web GUI is somewhat convoluted:
1) Search for title or author, if found
2) Click on the "Audiobook Details" link
3) On the "Torrent Download" line, click on either the "Torrent Free Download" or "Magnet" link.

Thanks.

Jackatt version 0.8.1027.0:

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

**Comment by kevinpawsey** [comment]
I have had a look at it, and I am a little confused as to how to get it to work, is there any chance of some pointers? 

For instance, the results are displayed of the query, then you are supposed to click on the Audiobook details... but the format of that URL is something along the lines of /audiobook/search+results+title, how do we se;eat this?

**Comment by goldharv** [comment]
Wow. Thanks for looking. 

It’s not that obvious. Toward the bottom of the details list there are 2 links on the line labeled “Torrent Download” - Torrent Free Downloads and Magnet. They work as expected.

Of course you have to register and login first or clicking on either link takes you to the login page.

**Comment by kevinpawsey** [comment]
Yeh, I saw the links for the download, I was just trying to work out how to get to the download page... was wondering if @kaso17 had any pointers :)

**Comment by kaso17** [comment]
@kevinpawsey you've to us the indirect download feature.
Set the search/fields/download selector to the same as the details fields and add a top level download block like this:
```yaml
  download:
    selector: a[href^="/download?"]
```

Example: https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/1337x.yml#L115-L117

**Comment by kevinpawsey** [comment]
oh, cool... thank you 👍 

I will have a look at l337x, as I have a login for that to see if the download method is similar, then use that to make the new tracker ⭐️ 

If I manage to get it working, what is the best way of making it public (apart from a little dance of the rooftop!)?

**Comment by kaso17** [comment]
Just go to https://github.com/Jackett/Jackett/tree/master/src/Jackett.Common/Definitions and click on the "Upload files" button and upload your definition. That should lead you through the process of creating the pull request. Don't forget to update the README file (tracker list) too.

**Comment by kevinpawsey** [comment]
Do you have another example for the definition that I can take a look at that is similar to l337x?

I can't open that site from the UK, and I was going to try and compare the methods of getting torrents.

Thanks :D

**Comment by zero77** [comment]
@kevinpawsey 
There’s a list of proxies hear that will let you access l337x and a lot of other similar sites.
https://torrents.me/sites

**Comment by kaso17** [comment]
ettv is another example

**Comment by kevinpawsey** [comment]
@zero77 I did try using your proxies for accessing 1337x.to, but it appeared that they did things to the site... it just looked different from when I fired up a VPN and popped out in a different country :)

I seem to be making (slow) progress with this (thanks to oodles of help from @kaso17 in Discord).
At the moment I can pull the bare bones of the first page of results on ABB, and it can download the torrent for it.  Things I need to work on (probably):
1. getting multiple pages of search results
2. getting more information, like size (being a public tracker it doesn't provide seeders/leechers information, so need to look at how other public trackers handle that)
3. documenting the script (hmmm... maybe not as the last thing... otherwise I will forget what all the parts do!! lol)
Was just wondering, do you want me to upload the definition as-is, or do you want it to do more before I upload it?

**Comment by kevinpawsey** [comment]
It is working in LazyLibrarian... as long as you set the minimum size to zero for the audiobooks :)
Let me document it a little bit and I will do that... you said that there is an 'upload' button in the Definitions folder on GitHub didn't you?

**Comment by kaso17** [comment]
yes, see my comment above

**Comment by kevinpawsey** [comment]
ah yeh, I knew you mentioned it at some time... I will see if I can slap some documentation in the code and the README file today :)

**Comment by bluenote73** [comment]
@kevinpawsey thanks for your efforts so far. If you're not done, maybe you could show what you have?

**Comment by kevinpawsey** [comment]
Hi there,

 

I know it has been a while… but I was thinking I had already uploaded my audiobooktorrents definition.

 

I’ve just gone to the URL you suggested below, and it is saying that I don’t have permission to upload to that folder… have I missed something on there?

 

Thanks for your help

 

Kevin

**Comment by kaso17** [comment]
@kevinpawsey seems like there was some github change. It's no longer creating a form using the upload feature. You seither manually have to fork/upload/creat pull request or use the "Create new file" button which still works like the upload button used to work.

**Comment by kevinpawsey** [comment]
my fault for dragging my feet!! lol

OK, I have done it that way to create a new file, it seems to have worked... not sure if you have to approve or anything.

**Comment by kaso17** [comment]
please also edit the README file in your "patch-1" branch. Then you'll have to create a pull request "new pull request" button". Select the jackett/jackett master branch on the left and choose your patch-1 branch on the right side.

**Comment by kevinpawsey** [comment]
OK, done that.. but I am getting the following when creating the pull request:
Merging is blocked
The base branch restricts merging to authorized users. Learn more about protected branches.

**Comment by bluenote73** [comment]
@kevinpawsey Hey Kevin, thanks so much for this :) I just tried it out and it works.  One thing I noticed is that the torrent size is not populated in jackett although it is shown on the search and listing page of audiobookbay. I hope you might find that to be an easy fix, that would be convenient to have this.  Thanks again for your efforts :)

**Comment by garfield69** [comment]
@bluenote73  with pre-release v0.10.258 you should get size, category, date and up to 35 results per search.
