### ISSUE TITLE
Research OS X install guide

### ISSUE THREAD

**Issue by ldexterldesign** [Jackett/Jackett#317]
https://forums.sonarr.tv/t/jackett-additional-torrent-trackers-for-sonarr/5156/176?u=ldexterldesign

Hey,

Thanks for plugin

Can anyone point me at an updated OS X install guide - https://github.com/Jackett/Jackett#installation-on-linuxosx really isn't very helpful?

Hope to hear back

Kind thanks

**Comment by ldexterldesign** [comment]
BUMP

**Comment by flightlevel** [comment]
Don't have a mac here, where are you getting stuck?
If you've already got Sonarr running, you should be able to just go to step 3 and run

**Comment by jgillman** [comment]
@ldexterldesign Just installed on OS X with these steps and without issue:

1. Install mono with brew: `brew update && brew install mono`
1. Download the latest `.tar.gz` release from here: https://github.com/Jackett/Jackett/releases
1. Start Jackett with `mono JackettConsole.exe`

**Comment by ldexterldesign** [comment]
Hey @jgillman,

Thanks for reply

```
Apple-MacBook-Pro:Jackett-0.7.285 ldexterldesign$ which mono
/usr/local/bin/mono
Apple-MacBook-Pro:Jackett-0.7.285 ldexterldesign$ mono --version
Mono JIT compiler version 4.2.3 (explicit/832de4b Thu Mar  3 19:24:57 EST 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-(detached/a173357)
	GC:            sgen
Apple-MacBook-Pro:Jackett-0.7.285 ldexterldesign$ pwd
/Applications/Jackett-0.7.285
Apple-MacBook-Pro:Jackett-0.7.285 ldexterldesign$ ls
Build.bat	Installer.iss	LICENSE		README.md	Upstart.config	src
Apple-MacBook-Pro:Jackett-0.7.285 ldexterldesign$ mono JackettConsole.exe
Cannot open assembly 'JackettConsole.exe': No such file or directory.
```

Can you think of anything obvious I'm missing?

Hope to hear back

Kind thanks

**Comment by ldexterldesign** [comment]
BUMP

**Comment by flightlevel** [comment]
In your directory `Build.bat   Installer.iss   LICENSE     README.md   Upstart.config  src` you have the source code (you can delete all of this), you can't run this directly, you have to run code that has been compiled.

Go to the releases page https://github.com/Jackett/Jackett/releases and download the latest `Jackett.Binaries.Mono.tar.gz` file and extract contents. cd into the directory that contains `JackettConsole.exe` and then you will be able to run `mono JackettConsole.exe`

**Comment by ldexterldesign** [comment]
Hey @flightlevel,

Cheers for reply

All sorted - kind thanks

--

> Download and extract the latest .tar.gz release from the releases page and run Jackett using mono with the command "mono JackettConsole.exe".
- https://github.com/Jackett/Jackett#installation-on-linuxosx

May I suggest the README is updated, because there are two ``tar.gz`` downloads on https://github.com/Jackett/Jackett/releases :

> 1. Jackett.Binaries.Mono.tar.gz
> 2. Source code (tar.gz)

The following wording would have saved me a bunch of time and probably the creation of this issue altogether:

> Download and extract the latest ``Jackett.Binaries.Mono.tar.gz`` release from the releases page and run Jackett using mono with the command "mono JackettConsole.exe".

Kind regards

**Comment by jgillman** [comment]
@ldexterldesign I changed the wording in PR #424. Should be better now :)

**Comment by ldexterldesign** [comment]
@jgillman 👊
