### ISSUE TITLE
[kickasstorrent-kathow] Returns invalid json on api call 

### ISSUE THREAD

**Issue by hannsen** [Jackett/Jackett#3170]
Jackett Version 0.8.1027.0 

search term:` lol`

search url: `http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=xxxxxxxxxx&Query=lol`

Log entry: `2018-05-28 19:16:46.7432 Info Manual search for "lol" on kickasstorrent-kathow with 87 results.` 

json response:  https://gist.githubusercontent.com/hannsen/db3b46266e3bd8be33f9a405208e7804/raw/ca95a306755911bc2d714b7f0ca83c901c87c444/invalid_jacket_json

I think the problematic portion is ` Multiple Dildots are Pervertful Awakening "A Dream ` which is a string inside a magnet url.

so my guess is to escape magnet urls correclty for json usage

**Comment by kaso17** [comment]
jackett is using the Newtonsoft JSON library for JSON generation, it should take care of escaping the string. Not sure why this didn't happen here. There might be some unicode voodoo going on causing the problem. Unfortunately I can't reproduce it (the torrent disappeared from KAT). If this happens again it would be great if you could enable enhanced logging and provide a binary copy of the log file.
