### ISSUE TITLE
drops my system to its knees

### ISSUE THREAD

**Issue by LEdiodes** [Jackett/Jackett#3172]
0.8.1027.0 -- seems like malware to me. my beefy system almost becomes unusable, it wasn't always like this but due to this I have uninstalled and do not plan to re-install(as it seems it is laced with malware).

Just wanted to give you my feedback. I did like Jackett previously..

**Comment by kaso17** [comment]
Did this start with 0.8.1027.0? Which version was the last one not causing problems?
Are you using the socks proxy feature? It's buggy and causing high CPU usage.
