### ISSUE TITLE
[funfile]  -  "An error occured while updating this indexer"

### ISSUE THREAD

**Issue by lxdrd** [Jackett/Jackett#3179]
Getting "An error occured while updating this indexer" when trying to add funfile (or any indexer) to jackett. The snippet below are the logs that correspond to the when the issue occurs. Please let me know if you need anything else. Thank you.

May 30, 2018 01:36:17 PM | Info | IndexerApiController Dispose
-- | -- | --
May 30, 2018 01:36:17 PM | Info | IndexerApiController Dispose
May 30, 2018 01:36:17 PM | Info | Content-type='application/json; charset=utf-8', content-length=14150
May 30, 2018 01:36:17 PM | Info | IndexerApiController ExecuteAsync
May 30, 2018 01:36:17 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
May 30, 2018 01:36:17 PM | Error | {0}
May 30, 2018 01:36:17 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
May 30, 2018 01:36:17 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
May 30, 2018 01:36:17 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Config(ConfigItem[] config)'
May 30, 2018 01:36:17 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync
May 30, 2018 01:36:17 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Config(ConfigItem[] config)'
May 30, 2018 01:36:17 PM | Error | ApiControllerActionInvoker InvokeActionAsync
May 30, 2018 01:36:17 PM | Error | ReflectedHttpActionDescriptor ExecuteAsync
May 30, 2018 01:36:17 PM | Debug | IWebClient: Returning NotImplemented =>
May 30, 2018 01:36:17 PM | Error | headerString:
May 30, 2018 01:36:17 PM | Error | cookies:
May 30, 2018 01:36:17 PM | Error | request.RawPOSTDdata:
May 30, 2018 01:36:17 PM | Error | request.Referer: https://www.funfile.org/takelogin.php
May 30, 2018 01:36:17 PM | Error | request.Cookies:
May 30, 2018 01:36:17 PM | Error | request.Url: https://www.funfile.org/takelogin.php
May 30, 2018 01:36:17 PM | Error | request.Method: POST
May 30, 2018 01:36:17 PM | Error | got NotImplemented/InternalServerError
May 30, 2018 01:36:16 PM | Debug | UnixLibCurlWebClient: Posting username=&password=&login=Login
May 30, 2018 01:36:16 PM | Debug | IWebClient.GetString(Url:https://www.funfile.org/takelogin.php)
May 30, 2018 01:36:16 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Config(config=Jackett.Models.DTO.ConfigItem[])'
May 30, 2018 01:36:16 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Config(config=Jackett.Models.DTO.ConfigItem[])'
May 30, 2018 01:36:16 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync
May 30, 2018 01:36:16 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Config(ConfigItem[] config)'
May 30, 2018 01:36:16 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
May 30, 2018 01:36:16 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Config(ConfigItem[] config)'
May 30, 2018 01:36:16 PM | Info | HttpActionBinding ExecuteBindingAsync Model state is valid. Values: config=Jackett.Models.DTO.ConfigItem[]
May 30, 2018 01:36:16 PM | Info | FormatterParameterBinding ExecuteBindingAsync Parameter 'config' bound to the value 'Jackett.Models.DTO.ConfigItem[]'

Jackett version
v0.8.1039

Mono Version:
Mono JIT compiler version 4.6.2 (Stable 4.6.2.7/08fd525 Tue Dec 27 10:49:36 UTC 2016) 

-------------------------------

**Comment by flightlevel** [comment]
Upgrade to at least Mono 5.4 (later is better)

If that still doesn't work, post an enhanced log https://github.com/Jackett/Jackett#troubleshooting
