### ISSUE TITLE
reverse proxy

### ISSUE THREAD

**Issue by djdmd** [Jackett/Jackett#318]
Hello
i need to access to jackett from another server and i'd like to make the same as my other program an d proxify jacket so i only have to type domain-name/jackett but it doesn't work , i always have a blanck page and no error 

here's what the revese proxy contain's
`location  /jackett($|./*) {
    proxy_pass          http://127.0.0.1:9117;
     proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
`
thx

**Comment by Bybou** [comment]
It's work fine for me.
You have to put /jackett in the field " Base Path Override: /jackett"

2016-04-21 11:09 GMT+02:00 djdmd <notifications@github.com>:

> Hello
> i need to access to jackett from another server and i'd like to make the
> same as my other program an d proxify jacket so i only have to type
> domain-name/jackett but it doesn't work , i always have a blanck page and
> no error
>
> here's what the revese proxy contain's
> location /jackett($|./*) {
> proxy_pass http://127.0.0.1:9117;
> proxy_set_header Host $host;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> }
>
> thx
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Jackett/Jackett/issues/318>
>



-- 

Cordialement,


*Johan Copin*

johan.copin@gmail.com <jcopin@micropole.com>

**Comment by djdmd** [comment]
Ok thx where is this field  ?

**Comment by Bybou** [comment]
In the app when it launch locally or you can find in the xml file property
of Jackett on /jackett/.config/Jackett/ServerConfig.json
Folder ".config" is hidden :)

2016-04-21 13:39 GMT+02:00 djdmd <notifications@github.com>:

> Ok thx where is this field ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Jackett/Jackett/issues/318#issuecomment-212875769>
>



-- 

Cordialement,


*Johan Copin*

johan.copin@gmail.com <jcopin@micropole.com>

**Comment by djdmd** [comment]
I have this
{
  "Port": 9117,
  "AllowExternal": true,
  "APIKey": "jzvnvbghnqes7ftdspq1lk1cj30l357y",
  "AdminPassword": "c77015e1a4ef64d3fba25ef2d3fe0bc64c3f3f965dc5bcdc6ea4a3b12c3$
  "InstanceId": "xlcungrwquv35daaa7th4133ktyqnxltfu31ol6pdp7aemt5tegrln5dplqwxp$
  "BlackholeDir": null
  }

**Comment by Bybou** [comment]
I have this
{
  "Port": 5000,
  "AllowExternal": true,
  "APIKey": "*****",
  "AdminPassword": "",
  "InstanceId": "*****",
  "BlackholeDir": "",
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": "/jackett"
}

Don't show ever APIKey, Password or instance ;)

2016-04-21 14:05 GMT+02:00 djdmd <notifications@github.com>:

> I have this
> {
> "Port": 9117,
> "AllowExternal": true,
> "APIKey": "jzvnvbghnqes7ftdspq1lk1cj30l357y",
> "AdminPassword":
> "c77015e1a4ef64d3fba25ef2d3fe0bc64c3f3f965dc5bcdc6ea4a3b12c3$
> "InstanceId":
> "xlcungrwquv35daaa7th4133ktyqnxltfu31ol6pdp7aemt5tegrln5dplqwxp$
> "BlackholeDir": null
> }
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Jackett/Jackett/issues/318#issuecomment-212885049>
>



-- 

Cordialement,


*Johan Copin*

johan.copin@gmail.com <jcopin@micropole.com>

**Comment by djdmd** [comment]
Ok thx 
I think i have found why it doesn't work , i run the raspdealer fork for french torrent providers and it doesn't have the latest update for reverse proxy .

@Raspdealer can you add the link on your fork so that i can post issue on it.

thanks

**Comment by JigSawFr** [comment]
@djdmd we can't help you on using a fork of this project as it's not up to date, please contact your fork's owner
