### ISSUE TITLE
All my indexers have disappeared?

### ISSUE THREAD

**Issue by antigravity83** [Jackett/Jackett#3181]
Version 0.8.1045.0
Ubuntu 10.04

Logged into my Jackett this morning and all my indexers have disappeared? 

Logs: https://pastebin.com/vrZ7b49T

**Comment by flightlevel** [comment]
Have you changed anything recently, new system, mono update, os update?

Please post an enhanced log https://github.com/Jackett/Jackett#troubleshooting

**Comment by MarkTechComputers** [comment]
Same issue here. 
OS: Debian 9
Jackett V: 0.8.1045.0

The following is the errors found for each indexer:
`Error Failed loading backup configuration for x, you must reconfigure this indexer System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at Jackett.Common.Indexers.BaseIndexer.LoadFromSavedConfiguration (Newtonsoft.Json.Linq.JToken jsonConfig) [0x00008] in <f13be822aba941ce9acc4e8726877eeb>:0 
  at Jackett.Common.Services.IndexerConfigurationService.Load (Jackett.Common.Indexers.IIndexer idx) [0x0006d] in <f13be822aba941ce9acc4e8726877eeb>:0`

**Comment by kaso17** [comment]
@MrToasterOven which mono version are you running?

**Comment by MrToasterOven** [comment]
Mono V: 4.8.1.0-0xamarin1

**Comment by kaso17** [comment]
Is the mono-devel package installed?
If it is please try installing mono-complete and see if that fixes the problem?

If that doesn't fix it please install mono >=5.8 from https://www.mono-project.com/download/stable/#download-lin

**Comment by MrToasterOven** [comment]
Both mono-complete and mono-devel are installed. Also, we shouldn't be installing old versions of Mono... We should be upgrading to support the new versions. Keep in mind that downgrading Mono means having to spend hours trying to get other packages to not interfere w/ the downgrade.

**Comment by kaso17** [comment]
you're running the old mono 4.8 version (probably the official debian package?).
@flightlevel planned wanted to change the minimum supported version to 5.8, not sure why he didn't do that yet but I suspect that this error might be related. I'm running the latest nightly 5.14 build on debian without any problems.

**Comment by MrToasterOven** [comment]
Ah, my mistake. I was on 5.10, but since they changed some things, it caused massive problems and I had to downgrade. Ever sense, I haven't upgraded. Whoopsies. Will report back w/ any new information.

**Comment by MrToasterOven** [comment]
Seems to work good now. Wonder what changed that caused the issue in 4.8.

**Comment by kaso17** [comment]
The latest pre-release contains a migration logic in preparation for the .NET Core change.
The Readme was actually updated but not completely, fixed via e243c11cc0c51db186f60487a17becdd581d0802

@flightlevel I suggest we catch this exception and handle it gracefully instead of breaking old mono installations like this.

**Comment by kaso17** [comment]
1615bff2d050472d13a8943ed9594f101cf47527 is an attempt to avoid the exception (not sure when the class is actually loaded).

**Comment by flightlevel** [comment]
Thanks @kaso17 beat me to it
Strange about https://www.nuget.org/packages/System.Runtime.InteropServices.RuntimeInformation/ thought it would be okay being net45
Didn't really need it in the end, so thought just safer to remove it for now
