### ISSUE TITLE
[iptorrents]  (Config)

### ISSUE THREAD

**Issue by extensivez953** [Jackett/Jackett#3185]
**Jackett version**:  0.8.1039.0
-------------------------------
log 
https://www.dropbox.com/s/dh096oglhwj8lja/log.txt?dl=0

just found jackett today.  i installed it on windows 10.  i loaded up the webui and tried adding IPTorrents to no avail.  I tried all of the urls.  I tried the username and using email as username (what should it be anyways?)

please help

**Comment by extensivez953** [comment]
i swear now i went in and tried adding it again and now it is saying something about cookie header information.  i tracked that down and pasted it into jacket and it is saying parse error.  i ran jacket with -t and there is little to no information given.  help!

**Comment by extensivez953** [comment]
anybody?

**Comment by flightlevel** [comment]
Error in the logs is
`
Error:
	Invalid username or password.Please try again
`
It's your IPT username

If that still doesn't work, post an enhanced log https://github.com/Jackett/Jackett#troubleshooting

**Comment by Rocket01666** [comment]
im trying to get ipt working using the cookie method and i cant figure out where to add the cookie, the .json file has not been created so i cannot edit that. 

where do you put the cookie once you find it?
