### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down.: Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by brimnac** [Jackett/Jackett#3186]
Using LinuxServer IO Docker in unRAID, error requesting thepiratebay. I get the below text when testing:

> An error occured while testing this indexer
> Exception (thepiratebay): Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down.: Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down.
> 

I'm able to access the link it provides (the [https://thepiratebay.org/recent](https://thepiratebay.org/recent) link).

**Jackett version**:  Jackett Version 0.8.1039.0
**Mono version** (if not using Windows):  ? unraid 6.5.0 ?

-------------------------------

**Comment by flightlevel** [comment]
Can you try again, 522 is a cloudflare error

If still not working

Run `curl -v https://thepiratebay.org` from the docker container and post the output

**Comment by internetR** [comment]
same problem see also 

https://pastebin.com/jmKAWpiz

curl -v htttps://proxytpb.pw results in connection time out

**Comment by ahumphries003** [comment]
root@cb441a87f24a:/# curl -v https://thepiratebay.org
* Rebuilt URL to: https://thepiratebay.org/
*   Trying 104.27.217.28...
* Connected to thepiratebay.org (104.27.217.28) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: ssl778319.cloudflaressl.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: EC
* 	 certificate version: #3
* 	 subject: OU=Domain Control Validated,OU=PositiveSSL Multi-Domain,CN=ssl778319.cloudflaressl.com
* 	 start date: Sat, 03 Mar 2018 00:00:00 GMT
* 	 expire date: Sun, 09 Sep 2018 23:59:59 GMT
* 	 issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO ECC Domain Validation Secure Server CA 2
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET / HTTP/1.1
> Host: thepiratebay.org
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 522 Origin Connection Time-out
< Date: Tue, 12 Jun 2018 02:23:30 GMT
< Content-Type: text/html; charset=UTF-8
< Content-Length: 4795
< Connection: keep-alive
< Set-Cookie: __cfduid=dbfedb288aadc49e61c2a79630563fdbf1528770179; expires=Wed, 12-Jun-19 02:22:59 GMT; path=/; domain=.thepiratebay.org; HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:01 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< X-Frame-Options: SAMEORIGIN
< Set-Cookie: cf_use_ob=443; expires=Tue, 12-Jun-18 02:24:00 GMT; path=/
< Set-Cookie: cf_ob_info=522:4298da578a9e4243:MSP; expires=Tue, 12-Jun-18 02:24:00 GMT; path=/
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 4298da578a9e4243-MSP
< 
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<meta http-equiv="refresh" content="0">

<title>thepiratebay.org | 522: Connection timed out</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>




</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="cf-error-details-wrapper">
        <div class="cf-wrapper cf-error-overview">
            <h1>
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">522</span>
              <small class="heading-ray-id">Ray ID: 4298da578a9e4243 &bull; 2018-06-12 02:23:30 UTC</small>
            </h1>
            <h2 class="cf-subheadline">Connection timed out</h2>
        </div>
        
        <div class="cf-section cf-highlight cf-status-display">
            <div class="cf-wrapper">
                <div class="cf-columns cols-3">
                  
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-browser"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc">You</span>
  <h3 class="cf-status-name">Browser</h3>
  <span class="cf-status-label">Working</span>
</div>

<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-cloud"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc">Minneapolis</span>
  <h3 class="cf-status-name">Cloudflare</h3>
  <span class="cf-status-label">Working</span>
</div>

<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-server"></i>
    <i class="cf-icon-status cf-icon-error"></i>
  </div>
  <span class="cf-status-desc">thepiratebay.org</span>
  <h3 class="cf-status-name">Host</h3>
  <span class="cf-status-label">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="cf-section cf-wrapper">
            <div class="cf-columns two">
                <div class="cf-column">
                    <h2>What happened?</h2>
                    <p>The initial connection between Cloudflare's network and the origin web server timed out. As a result, the web page can not be displayed.</p>
                </div>
              
                <div class="cf-column">
                    <h2>What can I do?</h2>
                          <h5>If you're a visitor of this website:</h5>
      <p>Please try again in a few minutes.</p>

      <h5>If you're the owner of this website:</h5>
      <p><span>Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources.</span> <a href="https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522">Additional troubleshooting information here.</a></p>
                </div>
            </div>
              
        </div>

        <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>4298da578a9e4243</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: 75.134.22.9</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div>


    </div>
</div>
</body>
</html>
* Connection #0 to host thepiratebay.org left intact

**Comment by ahumphries003** [comment]
root@cb441a87f24a:/# curl -v https://thepiratebay.org
* Rebuilt URL to: https://thepiratebay.org/
*   Trying 104.27.217.28...
* Connected to thepiratebay.org (104.27.217.28) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: ssl778319.cloudflaressl.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: EC
* 	 certificate version: #3
* 	 subject: OU=Domain Control Validated,OU=PositiveSSL Multi-Domain,CN=ssl778319.cloudflaressl.com
* 	 start date: Sat, 03 Mar 2018 00:00:00 GMT
* 	 expire date: Sun, 09 Sep 2018 23:59:59 GMT
* 	 issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO ECC Domain Validation Secure Server CA 2
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET / HTTP/1.1
> Host: thepiratebay.org
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 522 Origin Connection Time-out
< Date: Tue, 12 Jun 2018 02:23:30 GMT
< Content-Type: text/html; charset=UTF-8
< Content-Length: 4795
< Connection: keep-alive
< Set-Cookie: __cfduid=dbfedb288aadc49e61c2a79630563fdbf1528770179; expires=Wed, 12-Jun-19 02:22:59 GMT; path=/; domain=.thepiratebay.org; HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:01 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< X-Frame-Options: SAMEORIGIN
< Set-Cookie: cf_use_ob=443; expires=Tue, 12-Jun-18 02:24:00 GMT; path=/
< Set-Cookie: cf_ob_info=522:4298da578a9e4243:MSP; expires=Tue, 12-Jun-18 02:24:00 GMT; path=/
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 4298da578a9e4243-MSP
< 
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<meta http-equiv="refresh" content="0">

<title>thepiratebay.org | 522: Connection timed out</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>




</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="cf-error-details-wrapper">
        <div class="cf-wrapper cf-error-overview">
            <h1>
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">522</span>
              <small class="heading-ray-id">Ray ID: 4298da578a9e4243 &bull; 2018-06-12 02:23:30 UTC</small>
            </h1>
            <h2 class="cf-subheadline">Connection timed out</h2>
        </div>
        
        <div class="cf-section cf-highlight cf-status-display">
            <div class="cf-wrapper">
                <div class="cf-columns cols-3">
                  
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-browser"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc">You</span>
  <h3 class="cf-status-name">Browser</h3>
  <span class="cf-status-label">Working</span>
</div>

<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-cloud"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc">Minneapolis</span>
  <h3 class="cf-status-name">Cloudflare</h3>
  <span class="cf-status-label">Working</span>
</div>

<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-server"></i>
    <i class="cf-icon-status cf-icon-error"></i>
  </div>
  <span class="cf-status-desc">thepiratebay.org</span>
  <h3 class="cf-status-name">Host</h3>
  <span class="cf-status-label">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="cf-section cf-wrapper">
            <div class="cf-columns two">
                <div class="cf-column">
                    <h2>What happened?</h2>
                    <p>The initial connection between Cloudflare's network and the origin web server timed out. As a result, the web page can not be displayed.</p>
                </div>
              
                <div class="cf-column">
                    <h2>What can I do?</h2>
                          <h5>If you're a visitor of this website:</h5>
      <p>Please try again in a few minutes.</p>

      <h5>If you're the owner of this website:</h5>
      <p><span>Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources.</span> <a href="https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522">Additional troubleshooting information here.</a></p>
                </div>
            </div>
              
        </div>

        <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div>


    </div>
</div>
</body>
</html>
* Connection #0 to host thepiratebay.org left intact

**Comment by kaso17** [comment]
@ahumphries003: The pirate bay servers are currently down
