### ISSUE TITLE
[shareisland] Login Failed, got redirected. Try changing the indexer URL to http://shareisland.org/. (Config)

### ISSUE THREAD

**Issue by jokerigno** [Jackett/Jackett#3192]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.1039.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by jokerigno** [comment]
Info added

**Comment by flightlevel** [comment]
They changed their address
Change your site link to 'http://shareisland.org/' 
Or wait for the next Jackett release

**Comment by jokerigno** [comment]
Site adress is already "http://shareisland.org/" so the issue should be open in my opinion.

**Comment by kaso17** [comment]
@jokerigno please provide an enhanced log
