### ISSUE TITLE
[DevQ]  Adding The Archive

### ISSUE THREAD

**Issue by travisboss** [Jackett/Jackett#3197]
I'd like to add The Archive private tracker, they are not offering any invites at this time.  I have attached an image of the categories I would need to add I would just need some assistance on how to go about making sure I map them correctly. 

<img width="1349" alt="screen shot 2018-06-03 at 10 28 15 pm" src="https://user-images.githubusercontent.com/16948721/40896898-72917396-677d-11e8-8499-c9ef6c428599.png">

**Comment by kaso17** [comment]
If you know a little HTML/CSS have a look at https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any specific questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by pyr0ball** [comment]
The Archive does use Gazelle. Would appreciate having this added!

**Comment by betamax2021** [comment]
the archive is currently open signups, I don't know for how much longer though. [https://www.reddit.com/r/OpenSignups/comments/8zawu4/weve_decided_to_go_perm_invite_only_after_this/](url)

**Comment by garfield69** [comment]
if the site this ticket is talking about *The Archive* is the one now called *nostalgic* then I've recently added a cardigann definition for it. Currently uses the cookie method to login as I have so far, not figured out how to get around the bots-are-forbidden detection. try Jackett v0.10.731

**Comment by garfield69** [comment]
cracked the bot-detection issue with 90d0f5b2e0c1ff7ab520dedb29cd1d0f3c61d6c4 so now the nostalgic indexer uses the regular username and password login method. :-) Jackett pre-release 0.10.732
