### ISSUE TITLE
REQ : Scenebits.org

### ISSUE THREAD

**Issue by xxandeer** [Jackett/Jackett#3198]
Please add scenebits.org as tracker.

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by xxandeer** [comment]
The tracker is based on rartracker, the same source as SuperBits. 
So maybe just change som values from the superbits file will do the work.
