### ISSUE TITLE
[scenetime] Your cookie did not work: Your cookie did not work (Config)

### ISSUE THREAD

**Issue by abright52** [Jackett/Jackett#3199]
I had this working previously, but it is no longer working.  Test failed, then I tried to re-enter the cookie and this fails, as well.  Next, I removed the cookie and reentered the credentials on the site.  Pulled the cookie info again, still no go.

Looking at the logs, it appears that "https://www.scenetime.com/browse_API.php" is returning a 404.

Perhaps they changed something...again.

**Jackett version**:  0.8.1039.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
fixed via b303befbb99847cdfc8d615af77fe9489faed7e1

**Comment by 1c3bolt** [comment]
The indexers now doesn't return any results

**Comment by kaso17** [comment]
@1c3bolt can you please provide an example search URL (not working).

**Comment by abright52** [comment]
Seems to be missing the search query.

WebClient(HttpWebClient).GetString(Url:https://www.scenetime.com/browse.php)

**Comment by 1c3bolt** [comment]
Hi
so i tried  with urls https://www.scenetime.com/ , https://www.scenetime.com/Movie.php, https://www.scenetime.com/browse.php it others but not work.

**Comment by kaso17** [comment]
@abright52 old API was using POST, fixed via 22a858c0766b2c48ce984dfc4541144599ef55f6
@1c3bolt did you test with a specific search? then you problem should be fixed too.
