### ISSUE TITLE
[Error] Unable to add TorrentDay.

### ISSUE THREAD

**Issue by humdedum1** [Jackett/Jackett#32]
Exception in GetConfigForm

Error: An error occurred while sending the request.

Those pop up whenever I click Setup to add TD.

EDIT: Adding that the other sites function fine.

**Comment by flightlevel** [comment]
Do you have an invite, very hard to test without logging in

**Comment by humdedum1** [comment]
I do. Just need an email.

**Comment by flightlevel** [comment]
jackettapp at gmail

**Comment by humdedum1** [comment]
Should be sent. Enjoy the testing.

**Comment by flightlevel** [comment]
Very strange, worked for me first go!
http://snag.gy/DqK9t.jpg
What OS, Jackett Version and when setting it up in Jackett, on the recaptcha are you seeing a tick?
Also, can you provide a log https://github.com/Jackett/Jackett#troubleshooting

**Comment by humdedum1** [comment]
Well, I found the issue. Apparently I had managed to compile the wrong version when I fidgeted with things, so I had the old zone177x v. 0.6.9. So that was the problem. Didn't even think to check that before you asked what version I was running. My apologies for wasting time. >_<

**Comment by flightlevel** [comment]
Good result. Latest releases are over here https://github.com/Jackett/Jackett/releases
Hopefully we will have a built it in autoupdater in the next couple of weeks, which will make it easier for everyone to stay updated.
