### ISSUE TITLE
Can't update anymore

### ISSUE THREAD

**Issue by bubez81** [Jackett/Jackett#3201]
Hello it' about 2 weeks that i noticed a problem when i check for updates:
`

un 05, 2018 01:07:26 PM | Error | Error checking for updates.
-- | -- | --
Jun 05, 2018 01:07:26 PM | Error | Failed to get the release list: Forbidden
Jun 05, 2018 01:07:26 PM | Debug | WebClient(HttpWebClient): Returning Forbidden => {"message":"API rate limit exceeded for 79.20.53.193. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}

`

**Comment by kaso17** [comment]
How often are you checking for updates?!?
It seems like you triggered the rate limit (according to the documentation it's 60 requests per hour.)
Is there something else on the system generating requests to github? Shared IP/System?
Jackett should normally do one request per day.

**Comment by bubez81** [comment]
with jacketts only sometimes...1 request x week manually.
I'm thinking about other programs...but i don't think...

**Comment by bubez81** [comment]
Solved! I think was Headphones fault.
Tnx
