### ISSUE TITLE
Save Magnet links in the blackhole directory

### ISSUE THREAD

**Issue by minitoine** [Jackett/Jackett#3206]
Hi,

You propose to save torrent files in the blackhole directory but not the magnet links.
Shouldn't it be possible to save the links in simple files like .magnet with only the link inside in the blackhole directory ?
Some clients / scripts seem to well handle this case and it might be useful. Or any format, everything can be adapted. But at least a file with a list of links, or a list of files with a link.

Thx :D

**Comment by kaso17** [comment]
this should be already the way it works if you use the blackhole feature with magnet only trackers. If it's not working please create a new issue with corresponding examples/logs.
