### ISSUE TITLE
RSS feed ordering wrong

### ISSUE THREAD

**Issue by t-zone** [Jackett/Jackett#3209]
A lot of the RSS feeds for indexers do not show the most recently added content. An example is btbit, which shows the RSS feed in the default order, but misses a lot of newly released content. If you do a search and order by created date, can you use that as an RSS feed (although it's xml and doesn't work with other apps) but I wanted this to work with Jackett. Is there a way to make the RSS feed on Jackett show the content in a particular order (i.e. published/created date)?

**Jackett version**:  v0.8.1039
**Mono version** (if not using Windows):  Windows 10

-------------------------------

**Comment by kaso17** [comment]
It's not possible to change the jackett RSS feed sort order (it shouldn't matter).
btbit seems to (geo) block me. I'm just getting a nginx 404 error. So I can't test/fix it. 
@garfield69 you added btbits, can you have a look?

@t-zone any other indexers affected by this.

**Comment by t-zone** [comment]
ETTV & Torrent Downloads seem to also have the same issue. It looks like they show the results with the default view you would get if you just searched their sites, which is relevance rather than latest, which isn't good for RSS as it shows a lot of old stuff. Unfortunately btbit is the only one that has the content I'm after.

**Comment by kaso17** [comment]
@garfield69 fixed it for btbit and ettv, thank you.
For torrent downloads I can't see any option on their normal search engine to change the order, so we can't fix this.

**Comment by garfield69** [comment]
@t-zone  btbit should apply sort to all results in the next jacket release.
