### ISSUE TITLE
No torrent found using BlueTigers

### ISSUE THREAD

**Issue by nabot93** [Jackett/Jackett#321]
I am trying to use the BlueTigers provider but I didn't manage to make it works.
In this example, I tried to look for Grimm S05E13 but it found nothing...

Request : /torznab/bluetigers/api?t=tvsearch&cat=5030,5040&extended=1&apikey=XXXXXX&offset=0&limit=100&q=Grimm&season=5&ep=13

Log : 2016-04-27 14:05:21.9853 Info Found 0 releases from BlueTigers for: Grimm S05E13 

There is nothing more in the log file.

Thanks for your help!

**Comment by JigSawFr** [comment]
Seems after some search, EP 13 is not present on BlueTigers ;)

**Comment by nabot93** [comment]
It is present on BlueTigers: https://www.bluetigers.ca/torrents-search.php?search=grimm+s05e13
Torrent link: https://www.bluetigers.ca/torrents-details.php?id=155984

**Comment by JigSawFr** [comment]
I will make some research, thanks

**Comment by nabot93** [comment]
Any news on this issue?

**Comment by nabot93** [comment]
I still have this issue... I there something I can do to help?
Another example: torznab/bluetigers/api?t=tvsearch&cat=5030,5040&extended=1&apikey=XXXX&offset=0&limit=100&q=Wynonna%20Earp&season=1&ep=6

**Comment by thenamelessthing** [comment]
Tracker are now closed.. ;-(

Sniff

https://twitter.com/hashtag/bluetigers
