### ISSUE TITLE
No download to blackhole link for magnet links

### ISSUE THREAD

**Issue by minitoine** [Jackett/Jackett#3211]
Hi !

I have some issues with the magnet download links to the blackhole directory. 
Logs don't show any error, but when doing a research, torrents have the options to download locally or to the blackhole directory, and only locally for magnet links.

I attached a screenshot of the situation. If you need any extra information, feel free to ask.
<img width="1810" alt="screen shot 2018-06-08 at 15 30 54" src="https://user-images.githubusercontent.com/6161713/41160929-65346764-6b31-11e8-8c5c-e018b94d7ec4.png">

Thanks in advance,

minitoine

Jackett Version 0.8.1065.0
Synology Mono version 5.8.0.108-11

**Comment by kaso17** [comment]
indeed this was broken in case of a direct magnet link.
Fixed via f3290800d8776226adf548a0291450386e0a2542
