### ISSUE TITLE
demonoid.pw is not a private tracker

### ISSUE THREAD

**Issue by hannsen** [Jackett/Jackett#3215]
nuff said :)

![image](https://user-images.githubusercontent.com/3775136/41195882-fb685db2-6c35-11e8-9bbf-e05e5a399ad1.png)

**Comment by flightlevel** [comment]
`nuff said`
Is this because they currently have registrations open to join or registrations are open permanently?

**Comment by hannsen** [comment]
https://www.demonoid.pw/, its a public tracker

**Comment by kaso17** [comment]
fixed via 53f8465e67c7d6c731b6499703bf46a593cff733
