### ISSUE TITLE
HDChina search returns completely unrelated results

### ISSUE THREAD

**Issue by yimingzhaomath** [Jackett/Jackett#3218]
I searched "total soccer" on HDChina, and I got completely unrelated result. Any idea why this is happening? The search on the PT site itself works correctly.

![untitled](https://user-images.githubusercontent.com/13087183/41206565-d51873a6-6cd3-11e8-96b7-18673465b314.jpeg)

**Comment by yimingzhaomath** [comment]
Here you go: 

https://hdchina.org/torrents.php?incldead=1&spstate=0&inclbookmarked=0&boardid=0&seeders=&search=total+soccer&search_area=0&search_mode=0

**Comment by kaso17** [comment]
99d8f63f9ed01561f4a333dd495569aeca5aada4 might fix it. please report if it's working.

**Comment by yimingzhaomath** [comment]
Works like a charm! Thanks.
