### ISSUE TITLE
Secret-Cinema Account Deleted?

### ISSUE THREAD

**Issue by motisb** [Jackett/Jackett#3219]
Hi,

I am username MOTIS, the founder of the original Cinema Obscura / Secret Cinema site.

I see that the site has been moved from secret-cinema.net to secret-cinema.pw

When I try to login, I get the error "there is no user with that e-mail address."

**Comment by kaso17** [comment]
I believe secret-cinema.net was moved to secret-cinema.pw a while ago. Can you login to the normal website? If not I guess your account got deleted.

**Comment by kaso17** [comment]
They migrated to a gazelle based tracker a while ago. Maybe your account got lost during this migration. I suggest you contact the current staff to sort this out. It's not a jackett issue :)

**Comment by motisb** [comment]
OK. Any idea how to contact them?

**Comment by kaso17** [comment]
Apparently you've to register at http://cosurvivors.proboards.com/ with your old username.
Otherwise try the IRC irc.brokensphere.net #sc
