### ISSUE TITLE
Request To Jackett Server Failed

### ISSUE THREAD

**Issue by vaiperboy** [Jackett/Jackett#3221]
When I press the settings toggle (the one where you put your username/password/cookies) I keep getting the "Request To Jackett Server Failed" error.
Have no idea why I'm getting that. Some torrents (e.g 2 Fast 4 You) can get past the settings part [not getting that request to jackett server failed error]
Running on ubtunu 16.04

Error log attached
[log.txt](https://github.com/Jackett/Jackett/files/2090200/log.txt)

**Jackett version**:  0.8.1070.0
**Mono version** (if not using Windows):  5.12.0.226

-------------------------------

**Comment by kaso17** [comment]
Your log contains a lot of certificate errors.
Try reimporting the certificates:
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`

**Comment by vaiperboy** [comment]
That fixed my issue.
Thanks a lot.

Cheers
