### ISSUE TITLE
[kickasstorrent] An error occurred while sending the request: Error: SecureChannelFailure (A call to SSPI failed, see inner exception.) (Config)

### ISSUE THREAD

**Issue by henkin67** [Jackett/Jackett#3224]
Hello,

When I'm trying to add different indexer (RARBG, KickAssTorrent, ...) I got this error : `An error occured while configuring this indexer
An error occurred while sending the request: Error: SecureChannelFailure (A call to SSPI failed, see inner exception.)`
Here is the full trace of this issue : [log_jackett.txt](https://github.com/Jackett/Jackett/files/2091421/log_jackett.txt)

**Jackett version**: 0.8.1100.0
**Mono version**: 5.12.0.226

Thanks in advance for your help.

**Comment by kaso17** [comment]
Are you running jackett on an ARM64 based platform?

**Comment by henkin67** [comment]
Yes, I'm running it on an Odroid C2 (ARM 64bits). Known issue?

**Comment by kaso17** [comment]
Yes, see #2173 and https://github.com/mono/mono/issues/8648

**Comment by kaso17** [comment]
I suggest you continue the discussion in the mono bug. If you're running debian 8 try upgrading to debian 9 (doesn't seem to be affected).
