### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://ww1.yggtorrent.is/ using form selector form[action$=

### ISSUE THREAD

**Issue by flemzord** [Jackett/Jackett#3230]
**Jackett version**:  v0.8.1100
**Mono version** (if not using Windows):  5.12.0.226

-------------------------------
Error : 

 An error occured while updating this indexer
Login failed: No form found on https://ww1.yggtorrent.is/ using form selector form[action$="/user/login"]

**Comment by flemzord** [comment]
All issue is close, or bug is not fix :(

**Comment by kriegalex** [comment]
#3228 probably has the same origine, so probably a duplicate

**Comment by garfield69** [comment]
Duplicate #3228
