### ISSUE TITLE
YGG unavailable.

### ISSUE THREAD

**Issue by lilp69** [Jackett/Jackett#3233]
YGG unavailable, on Windows need to add 31.220.0.115    yggtorrent.is
31.220.0.115    ww1.yggtorrent.is
31.220.0.115    www.yggtorrent.is on host file. How add this on Jackett?
-------------------------------

**Comment by alaunay** [comment]
Replace the sitelink in jackett from https://yggtorrent.is/ to https://ww1.yggtorrent.is/ (in the configure menu). Also works by editing the definition file.

**Comment by alaunay** [comment]
Ah, it's already been corrected here:
https://github.com/Jackett/Jackett/commit/6f7ecbfb7b6c24458155c2d19a82428a4ab969d0

**Comment by PlqnK** [comment]
When changing to https://ww1.yggtorrent.is/ I get this error `Login failed: No form found on https://ww1.yggtorrent.is/ using form selector form[action$="/user/login"]` is there a way to fix it?

**Comment by lrnv** [comment]
I know it's closed but Wahou. Got an issue, came to github, solved 45minuts ago. Well done everyone, very good job :)
