### ISSUE TITLE
[audiobooktorrents] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by kevinpawsey** [Jackett/Jackett#3241]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
0.8.1117.0 (did have the same issue prior to updating today)

**Mono version** (if not using Windows):  
Mono JIT compiler version 5.12.0.226 (tarball Thu May  3 09:48:32 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
-------------------------------
From the log file after pressing test:
`
Jun 15, 2018 12:15:31 AM | Error | System.Exception: Found no results while trying to browse this tracker   at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x000e8] in <d336d98f74624068b013e27cdaf47ab3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0    at Jackett.Controllers.IndexerApiController+<Test>d__12.MoveNext () [0x000d3] in <61152a6bb5be44ef95ed2e90d3933fbb>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Threading.Tasks.TaskHelpersExtensions+<CastToObject>d__0.MoveNext () [0x0005b] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__17`1[TResult].MoveNext () [0x001a7] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Web.Http.Controllers.ApiControllerActionInvoker+<InvokeActionAsyncCore>d__1.MoveNext () [0x000ab] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__17`1[TResult].MoveNext () [0x001a7] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x00091] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x001ad] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__5.MoveNext () [0x00103] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x00091] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x001ad] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__5.MoveNext () [0x00103] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Web.Http.Controllers.ActionFilterResult+<ExecuteAsync>d__5.MoveNext () [0x001af] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Web.Http.Filters.AuthorizationFilterAttribute+<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext () [0x000f3] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <71d8ad678db34313b7f718a414dfcb25>:0    at System.Web.Http.Controllers.ExceptionFilterResult+<ExecuteAsync>d__6.MoveNext () [0x00087] in <69abafc3d8434ab584330d77cc8d6da3>:0
-- | -- | --
`
It was previously working, but suddenly stopped... maybe after donating to the site?

**Comment by kevinpawsey** [comment]
Also, if I try to search anything on the abtorrents tracker in Jackett, it shows no results, but I can see this in the logs:
`

Jun 15, 2018 12:27:39 AM | Info | Manual search for "Stuff" on audiobooktorrents with 0 results.
-- | -- | --
Jun 15, 2018 12:27:39 AM | Error | CardigannIndexer (audiobooktorrents): Error while parsing row '<tr class="browse_color"> 	<td align="center" style="padding: 0px"> 		<a href="browse.php?cat=240"> 			<img border="0" src="./pic/caticons/1/cat_self_imp.png" alt="Self Improvement">			 		</a> 	</td> <td align="left"> 		<a href="details.php?id=34078&amp;hit=1" onmouseover="Tip('<b>Julie Morgenstern - When Organizing Isn't Enough - Shed Your Stuff, Change...</b><br /><b>(MP3/64kbps)</b><br /><b>Size:&nbsp;280.50 MB</b><br /><br /><img src=\'https://abtorrents.me/img.php/2017/07/a4322e_whenorganizingisntenough-cover.jpg\' width=\'150\' height=\'220\' border=\'0\' alt=\'Poster\' title=\'poster\' />');" onmouseout="UnTip();"> 			<b>Julie Morgenstern - When Organizing Isn'...</b> 		</a>&nbsp;&nbsp;<a href="javascript:klappe_descr('descr34078');"> 			<img src="./pic/plus.png" border="0" alt="Show torrent info in this page" title="Show torrent info in this page">			 		</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="./pic/mod.gif" width="15" border="0" alt="Checked - by Koolaid53" title="Checked - by Koolaid53">		&nbsp;&nbsp;&nbsp;<br>		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> <td align="center"> 		<a href="download.php?torrent=34078"> 			<img src="./pic/zip.gif" border="0" alt="Download This Torrent!" title="Download This Torrent!">			 		</a> 	</td> 	<td align="right"> 		<span id="bookmark34078" style="display:inline;">                     <a href="bookmark.php?torrent=34078&amp;action=add" class="bookmark" name="34078">                     <span title="Bookmark it!" class="add_bookmark_b">                     <img src="./pic/aff_tick.gif" align="top" width="14px" alt="Bookmark it!" title="Bookmark it!">					                     </span>                     </a>                     </span>                      <span id="remove34078" style="display:none;">                     <a href="bookmark.php?torrent=34078&amp;action=delete" class="remove" name="34078">                     <span class="remove_bookmark_b">                     <img src="./pic/aff_cross.gif" align="top" width="14px" alt="Delete Bookmark!" title="Delete Bookmark!">					                     </span>                     </a>                     </span> 	</td> 	<td align="right"> 		<b> 			<a href="filelist.php?id=34078">13</a> 		</b> 	</td> <td align="right"> 		<b> 			<a href="details.php?id=34078&amp;hit=1&amp;tocomm=1">2</a> 		</b> 	</td> <td align="center"> 		<span style="white-space: nowrap;">Jul 21 2017<br>			 01:59 PM</span> 	</td> <td align="center">280.50<br>		MB</td> <td align="center"> 		<a href="snatches.php?id=34078">6<br>			times</a> 	</td> <td align="right"> 		<b> 			<a href="peerlist.php?id=34078#seeders"> 				<font color="#006600">2</font> 			</a> 		</b> 	</td> <td align="right">0</td> <td align="center"> 		<a href="userdetails.php?id=16158"> 			<b>cgrimes</b> 		</a> 	</td> <td width="100%" colspan="13">When Organizing Isn't Enough: SHED Your Stuff, Change Your Life<br>		 by Julie Morgenstern<br>		 <br>		 Goodreads rating 3.71<br>		 <br>		 Julie morgenstern shows how to get rid of the physical, mental, and time clutter that’s keeping you from the life you want.<br>		 <br>		 Julie Morgenstern has made a career out of helping her clients get organized. But in the process, she...<br> 		 		<a href="details.php?id=34078&amp;hit=1">Read more...</a> 	</td> </tr>':  System.Exception: Error while parsing field=files, selector=td:nth-child(4), value=: Input string was not in a correct format.   at Jackett.Common.Indexers.CardigannIndexer+<PerformQuery>d__29.MoveNext () [0x01669] in <d336d98f74624068b013e27cdaf47ab3>:0
`

**Comment by kaso17** [comment]
You have an extra column (number 4) with bookmark features. I don't have this, not sure how to enable it.
ec4afda1849249f04ae995501c7f65b7e1c66f1d should fix it.

**Comment by kevinpawsey** [comment]
Oh... that is strange...  I will have a look to see if I can find it anywhere... see if I can disable/enable it.

How often is the executable re-compiled, so I know when to update and report back if it is solved?

**Comment by kaso17** [comment]
there's no fixed schedule, new version has been released.

**Comment by kevinpawsey** [comment]
You are a 🌟 ... it is fixed now... awesome job, thank you 😃
