### ISSUE TITLE
[1337x] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by bhill117** [Jackett/Jackett#3242]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.2.0.1120
**Mono version** (if not using Windows):  Using Windows

-------------------------------

**Comment by bhill117** [comment]
1337x added a re-captcha. Even after activating the re-captcha, this tracker, along with others still fail to retrieve information

**Comment by kaso17** [comment]
@bhill117 I don't get any captcha, might be related to your IP (blacklisted?)
