### ISSUE TITLE
[kickasstorrent] An error occurred while sending the request: Error: ConnectFailure (Connection refused) (Config)

### ISSUE THREAD

**Issue by FredBro** [Jackett/Jackett#3244]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  v0.8.1121 or v0.8.1117
**Mono version** (if not using Windows):  
I pulled the latest docker container image from Linuxserver.io and this is the first run. I was setting up indexers and clicked add on KickassTorrent and it failed. I think it's an issue with Kickass, not Jackett
-------------------------------

**Comment by kaso17** [comment]
Might be a temporary connectivity issue or your ISP is blocking it.
