### ISSUE TITLE
Cinemageddon fails to download torrent files

### ISSUE THREAD

**Issue by mhendu** [Jackett/Jackett#3262]
Sorry, not sure how / where to submit the log, but what shows up in the log is this:

Error CardigannIndexer (cinemageddon): Download selector a[href^="download.php?id="] didn't match:

Followed by a URL and what looks like a lot of gibberish.

Immediately after this in the logs it shows an error message and a download URL like this:

Error Error downloading cinemageddon http://cinemageddon.net/download.php?id=70295 System.Exception: Download selector a[href^="download.php?id="] didn't match
   at Jackett.Common.Indexers.CardigannIndexer.<Download>d__32.MoveNext()

If I go to that URL it does download the correct torrent file, so it looks like something is confusing Jackett in verifying that the URL being received from the tracker is correct.

**Comment by kaso17** [comment]
8fb92ca05cd53bf1162cca6e01f8b43db27be325 should fix it, please report if it's working with this patch
