### ISSUE TITLE
[LimeTorrents] HTTP 404 on any torrent download

### ISSUE THREAD

**Issue by marcelpaulo** [Jackett/Jackett#3264]
Downloading any torrent from **LimeTorrents** results in HTTP 404:
![image](https://user-images.githubusercontent.com/10074769/41719112-74018458-7535-11e8-8ab0-07af47544775.png)

This looks similar to #3184 for Demonoid (which was fixed last week with https://github.com/Jackett/Jackett/commit/676d03eb885fdbc8f1daa47cd960afbb7414acec ).

For the sake of testing, I searched for *simone dinnerstein 2018* on LimeTorrents and tried to download the single torrent that results from the search.

**Jackett version**:  0.8.1127.0
**Mono version** (if not using Windows):  5.12.0.226-0xamarin3+ubuntu1804b1
**Platform**: Xubuntu 18.04

-------------------------------
Here's the enhanced [log.txt](https://paste.ee/p/Wrmsi)

**Comment by marcelpaulo** [comment]
This is not happening anymore. I get the impression LimeTorrents has set up CloudFare: when I tried to download one of their torrents, it took ages and didn't complete, so I opened their website and tried to download directly from there: I saw the CloudFare message, and after that I could download torrents from them through Jackett.

**Comment by kaso17** [comment]
itorrents added cloud flare browser checking. The challenge solver used by jackett isn't perfect yet (takes along time and might not work always). This will happen again until the solver works perfectly. You simply have to retry the download.

**Comment by marcelpaulo** [comment]
Thanks for the explanation, @kaso17 !
