### ISSUE TITLE
[yts] An error occurred while sending the request.: The underlying connection was closed: An unexpected error occurred on a send. (Config)

### ISSUE THREAD

**Issue by t-zone** [Jackett/Jackett#3269]
I get the error in the subject when trying to add YTS. I use a URL that I can browse to but still doesn't work. Error log attached.
[Error message.txt](https://github.com/Jackett/Jackett/files/2127338/Error.message.txt)

**Jackett version**:  v0.8.1123
**Mono version** (if not using Windows):  Windows 10 Pro

-------------------------------

**Comment by kaso17** [comment]
definitely a connectivity/firewall problem preventing jackett from connecting to the specified URL, please check your system settings.
