### ISSUE TITLE
Long titles get truncated by jackett and thus don't get picked up by Sonarr

### ISSUE THREAD

**Issue by derrickbathory** [Jackett/Jackett#327]
Torrents with names that are over 60 characters long get truncated which means that some torrents don't get grabbed. Observed with tracker SCC.

(in this particular instance, the resolution is truncated, so sonarr sees it as 480p)

**Comment by kaso17** [comment]
please provide a corresponding example torrent name

**Comment by flightlevel** [comment]
This issue hasn't had activity for a while. If the issue still exists, please reopen and include full logs. https://github.com/Jackett/Jackett#troubleshooting
