### ISSUE TITLE
[fuzer] Couldn't login (Config)

### ISSUE THREAD

**Issue by Denagar** [Jackett/Jackett#3272]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by Denagar** [comment]
i am unable to add my fuzer account, i am able to login to the web page but the index wont work

**Comment by flightlevel** [comment]
@Denagar an enhanced log is needed for anyone to help

**Comment by kaso17** [comment]
they added an invisible recaptcha, fixed via ab37f0c2c76104701b4b68a4949241acc9c89c67
