### ISSUE TITLE
I don't think I have a complete list of indexers

### ISSUE THREAD

**Issue by mike689** [Jackett/Jackett#3273]
I'm updated to the latest version, 0.8.1138.0

In my list of indexers the count is 259, is that right?

I can't find PrivateHD or a lot of the ones listed for some reason.

EDIT: (I compiled by source, running on Debian 9 server) Log attached.
[log.txt](https://github.com/Jackett/Jackett/files/2129541/log.txt)

**Comment by flightlevel** [comment]
Why are you compiling from source when it's pre built for you?

I'd try a hard refresh in browser

Also, check if PrivateHd exists as a file in your Indexers folder in `/home/mike/.config/Jackett `

**Comment by mike689** [comment]
Actually just did a hard reset in chrome, no change.

No PrivateHD in that folder, but that's because I've never been able to configure it in Jackett because it doesn't show up on the list of trackers for me?

**Comment by flightlevel** [comment]
Have you tried using a pre-built version from https://github.com/Jackett/Jackett/releases on Debian?

**Comment by mike689** [comment]
Currently testing that

**Comment by mike689** [comment]
Odd,
I had to purge any trace of Jackett entirely, then installing from the pre-package worked fine and all indexers are there.

Problem solved, somehow
