### ISSUE TITLE
Jackett does not restart after update.

### ISSUE THREAD

**Issue by mikemc303** [Jackett/Jackett#3275]
I'm running Jackett on Raspbian Stretch and for some reason the auto-updating functionality will not properly restart the Jackett service after updating. I see this in the updater.txt file, but it's not much to go on:

```
2018-06-23 10:08:55.1549 Info Killing process 26710 
2018-06-23 10:08:55.1603 Info Process 26710 didn't exit within 5 seconds
```

Running a service stop and then start again will launch the Jackett service, but only if a stop is run first. Potentially a lock file is not getting deleted when the update runs?

This just happened when the service tried to auto-update from v0.8.1123 to v0.8.1138, but it's happened before and to prevent the service from dying on update I would just turn off the auto-updating feature. I'd rather have unattended updates, tho!

Mono version is 5.12.0.226.

Any ideas? It should be noted that Jackett does appear to successfully update itself to the latest version, but it just isn't able to restart itself properly. Once I manually revive it (as mentioned above) it shows the latest version.

**Comment by kaso17** [comment]
Use systemd with auto restart. That should work much better. https://github.com/Jackett/Jackett/wiki/systemd-service

**Comment by mikemc303** [comment]
After looking in to it a bit more (per the suggestion from @kaso17 ) it looks like this might be a problem when using init.d to start/stop the service rather than systemd. I've switched to systemd for running Jackett so hopefully that will fix the update problem. Thanks @kaso17 !
