### ISSUE TITLE
Failed loading configuration - After update

### ISSUE THREAD

**Issue by Logvin** [Jackett/Jackett#3277]
Jackett 0.8.1138.0 
Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5) 
OS version: Unix 4.13.0.43 (64bit OS) (64bit process)

-------------------------------

The last few times that Jackett auto-updated, it drops all my private trackers. I have to go in and manually re-add them. You can see the indexers working perfectly find in the log, then the update runs, and when Jackett starts again it says it cannot find the file. This is the 3rd or 4th time I've had to re-create my indexers. Log file is attached.
[jackett_log.txt](https://github.com/Jackett/Jackett/files/2130145/jackett_log.txt)

**Comment by kaso17** [comment]
`Could not load file or assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
File name: 'Microsoft.Extensions.PlatformAbstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'`

Is the `mono-devel` package installed?
Where do you get the mono package from?

**Comment by Logvin** [comment]
I have no idea. It’s been running fine for a year now. I don’t recall doing anything crazy to install mono.

**Comment by kaso17** [comment]
8ae09d453da91b427a1231f2e95d1b3c1deb6c90 should fix it.
You can try it using the v0.8.1165 draft release: https://github.com/Jackett/Jackett/releases/download/untagged-349ac52a588ff312ae61/Jackett.Binaries.Mono.tar.gz (manual install required)
