### ISSUE TITLE
[avistaz] Exception (avistaz): The underlying connection was closed: The connection was closed unexpectedly.: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by Buster14** [Jackett/Jackett#3278]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.1123.0

-------------------------------
I am still able to download and complete a  torrent from avistaz manually, so the problem seems to be on jackett side.

]Edit : problem solved, it was caused by me testing an open sock5, changed it to http and it's working again.
While we're on subject, could anyone explain how to get vpn working under jackett? my country blocks alot of torrenting websites

**Comment by kaso17** [comment]
VPN usually is transparent to the programs. No need to change anything on the jackett side.
