### ISSUE TITLE
[REQ] add casstudio.tv to trackers

### ISSUE THREAD

**Issue by toleeck** [Jackett/Jackett#3285]
site: casstudio
  name: CasStudio description: "CasStudio is a private BitTorrent site"
  language: ru-ru   
  type: private
  encoding: UTF-8
  links:
    - https://casstudio.tv/

`//WEBRip 2160p, WEB-DL 1080p, WEBRip 1080p, WEB-DL 720p, WEBRip 720p, BDRip 720p
AddMultiCategoryMapping(TorznabCatType.TVHD, 5040);`

if relevant, I will give my login / password

I doubt that I will succeed in adding this tracker myself. but I would like to help something.

**Comment by garfield69** [comment]
https://casstudio.tv/ returning ERR_NAME_NOT_RESOLVED
anyone have the new domain or know if the site is now gone?

**Comment by toleeck** [comment]
> anyone have the new domain or know if the site is now gone?

Yes, the tracker is temporarily unavailable for technical reasons. This is the admin response.

**Comment by garfield69** [comment]
thanks for the update.

**Comment by toleeck** [comment]
> anyone have the new domain or know if the site is now gone?

tracker changed domain. Now https://casstudio.tk/
Administration tracker will probably try to return to the old domain. but for now it's locked.

**Comment by garfield69** [comment]
yes, #5060 provided the update and I've changed the link in jackett v0.11.219

**Comment by garfield69** [comment]
https://casstudio.tk/ returning ERR_CONNECTION_TIMED_OUT
broken, gone or new domain?

**Comment by toleeck** [comment]
> broken, gone or new domain?
Yeah, they were in trouble again.  Now the tracker is already working.  Domain tk.

**Comment by garfield69** [comment]
https://casstudio.tk/ returning ERR_CONNECTION_TIMED_OUT
broken, gone or new domain?

**Comment by toleeck** [comment]
> 
> 
> https://casstudio.tk/ returning ERR_CONNECTION_TIMED_OUT
> broken, gone or new domain?

This is information from the owners:
_Сайт временно недоступен из-за поломки на стороне хостера. Примерное время восстановления 1-2 дня.
The site is temporarily unavailable due to a breakdown on the host side. Estimated recovery time 1-2 days._

**Comment by garfield69** [comment]
Thanks for the update.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://casstudio.tk/ returning ERR_CONNECTION_TIMED_OUT

**Comment by toleeck** [comment]
> https://casstudio.tk/ returning ERR_CONNECTION_TIMED_OUT

tracker casstudio.tk seems to be back to normal

**Comment by ilike2burnthing** [comment]
> https://casstudio.tk/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://casstudio.tk/ - 502 Bad Gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://casstudio.tk/ returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
here we go again
https://casstudio.tk/ returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.18.410
