### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Error: NameResolutionFailure: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by ps6c0tic** [Jackett/Jackett#3287]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by ps6c0tic** [comment]
Hello,

I'm using Jackett to to connect to YGGTorrent to my CouchPotato, but since few days it's not working at all. I got the same issue on my YGGTorrent's provider in Sickrage, but I fix it with changing the address to https//ww1.yggtorrent.is/. Maybe it's the same issue. How can I fix this on Jackett please?

Thank you !

**Comment by kaso17** [comment]
make sure you're running the latest jackett version
