### ISSUE TITLE
Bj-Share.info - Add other torrent Categories

### ISSUE THREAD

**Issue by alexaldr** [Jackett/Jackett#3288]
Please, could you add the other torrent categories of Bj-share.info in the RSS list, such as Softwares, Android Apps, Magazines, Video lessons etc? We are getting only videos in the RSS.

Thank you very much in advance.

![screenshot_696](https://user-images.githubusercontent.com/16973279/41880386-34cf8082-78b4-11e8-8b8b-3e6a76de1cad.png)
![screenshot_697](https://user-images.githubusercontent.com/16973279/41880372-2433a5fa-78b4-11e8-9f0c-163a7b355581.png)
![screenshot_695](https://user-images.githubusercontent.com/16973279/41880385-347bf714-78b4-11e8-8982-a56bc5ce94bf.png)

**Jackett version**:  0.8.1162.0
-------------------------------

**Comment by kaso17** [comment]
It's working perfectly fine for me
http://127.0.0.1:9117/jackett/api/v2.0/indexers/bjshare/results/torznab/api?apikey=XXX&t=search&cat=&q=android
contains various non movies torrents.

Are you limiting categories in your RSS link?

**Comment by alexaldr** [comment]
Hi, 
I am using this link: http://127.0.0.1:9117/api/v2.0/indexers/bjshare/results/torznab/api?apikey=XXX&t=search&cat=&q=

OS: Windows 10 Home x64
Torrent Client: qBittorrent 4.1.1 x64

P.S: If I use this link (http://127.0.0.1:9117/jackett/api/v2.0/indexers/bjshare/results/torznab/api?apikey=XXX&t=search&cat=&q=android) I can get the android torrents perfectly.

Is my link wrong to get all torrents?

**Comment by alexaldr** [comment]
Please,
nevermind my request.

I just put an asterisk(*) at the end of the link and now I can get all torrent types. (http://127.0.0.1:9117/api/v2.0/indexers/bjshare/results/torznab/api?apikey=XXX&t=search&cat=&q=*)
Thanks for the attention and feedback.

Sorry for expend your time with this.
