### ISSUE TITLE
tehconnection

### ISSUE THREAD

**Issue by sea3pea0** [Jackett/Jackett#329]
For some reason I have never been able to get tehconnection to work. Anybody have any luck with this provider? If so was there any tricks that you did to get it to work? [Here](https://gist.github.com/sea3pea0/79a45354e77195f0ae830b1e530ee37d) are the logs

**Comment by flightlevel** [comment]
Have you tried https://github.com/Jackett/Jackett/issues/186#issuecomment-171591841 ?
