### ISSUE TITLE
XbytesV2 Bad Definition

### ISSUE THREAD

**Issue by IhToN** [Jackett/Jackett#3290]
**Jackett version**:  0.8.1162.0

-------------------------------

Jackett is deleting the _year_ from the torrent name.

The file to edit would be:
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/xbytes2.yml

About how the title is being uploaded for a movie in XbytesV2 is:
_Cavernicola (2018/BDRemux/1080P/DTS/ESP/CAT/ING/SUBS)_

Which is currently parsed as:
_Cavernicola  BDRemux 1080P DTS ESP CAT ING SUBS_

And should be:
_Cavernicola 2018 BDRemux 1080P DTS ESP CAT ING SUBS_

Thanks!

**Comment by kaso17** [comment]
I think the year is stripped intentionally because it's not the show/movie release year but the torrent upload year. See #3068
@kicker83 can you help clarifying this.

**Comment by IhToN** [comment]
The name of the torrent specify the Year of Release.
But if it's a whole TV Show or multiple season, for example:
_Supergirl 2017 18_  means that the TV Show goes from 2017 to 2018.

Whole name:
_Supergirl (2017 18/S03/E22/AMZ WEB DL 1080p/AC3 5 1 /DUAL/SUB)_

**Comment by kicker83** [comment]
@IhToN yes this is intentionally, as @kaso17 said. This is because Sickrage adds Supergirl show like this: Supergirl (2015)

As you can see, sickrage adds the year of the first episode aired, but xbytes adds the current season year. Sickrage will try to find Supergirl (2015) and there won't be any name like that, because you will see Supergirl (2017 18) in xbytes.

If I search in jackett "Cavernicola" it is able to find it. You can't find it? or what is the problem? 

Hope this can help.

Regards!

**Comment by IhToN** [comment]
When using Sonarr/Radarr they forcefully add the release/aired year as a strict requirement. If the file doesn't have the year on the name it can't recognize it as a proper file for that film/episode.

**Comment by kicker83** [comment]
Ok, but what is the year is hoping sonarr/radarr, first aired episode? or current season year?

**Comment by IhToN** [comment]
Current episode year, the same happens with the movie. As Cavernícola, for example, doesn't have the "2018" in its name, Radarr can't map the .torrent

**Comment by kicker83** [comment]
For movies, but not for TV shows. If we put the year, all TV shows in xbytesv2, will stop working. Lets see if someone could help with this problem.
Meanwhile, you could download the xbytesv2 definition, and remove the year stripe.

**Comment by IhToN** [comment]
With the 20XX replacing change it seems to work properly on Radarr (for movies) but I don't know if that would affect TV Shows too.

**Comment by kaso17** [comment]
I'm pretty sure radarr expects the original release year too (just like sonarr/sickrage). So searching a movie from 2017 will ignore any xbytes releases containing 2018 as year.
@IhToN Please have a look at the Radarr "Parser Leniency" option (indexer/Settings with advanced settings enabled). That might fix the problem.

**Comment by IhToN** [comment]
@kaso17 currently, the year on Xbytes refers to the release year from the move, not when the torrent has been published. The main problem is within the TV Shows as Xbytes uses the year as the Season Release Date and not the First Episode Aired date.

In any case, I've already tried with
![imagen](https://user-images.githubusercontent.com/16889094/42048233-f464edd8-7b02-11e8-8b43-cd6b21b516d1.png)
And it seems that the option doesn't work as it should, the error is still the same.

**Comment by kaso17** [comment]
Also have a look at this option (for all indexers, not indexer specific):
![lenpars](https://user-images.githubusercontent.com/11887264/42049964-edf96028-7b07-11e8-8cce-5c1230967911.png)

If the year naming is only wrong for the TV series but correct for movies then the year replace should be only applied for tv shows.

**Comment by IhToN** [comment]
Applying the Year Remove filter to only TVShows would be a really good solution but I don't know how to do that.

**Comment by kaso17** [comment]
if the year is always followed by a season tag I would suggest to adjust the replace regex to only remove the year if it's followed by SXX. 
That should be the easiest option. If there's no common pattern for TV show titles then it's necessary to use some workarounds to use/not to use the regex based on e.g. the category.

**Comment by kicker83** [comment]
Radarr is working perfect with "Lentient parsing" option in the  indexers
section.

**Comment by IhToN** [comment]
![imagen](https://user-images.githubusercontent.com/16889094/42475762-e88c223e-83cb-11e8-91df-4fb40cce2641.png)

Just found this on Sonarr.

**Comment by kaso17** [comment]
check the sonarr log to see why it doesn't detect it correctly.

**Comment by garfield69** [comment]
Jackett 0.14.243
