### ISSUE TITLE
[YGGTorrent] torrent size issue

### ISSUE THREAD

**Issue by h2h2** [Jackett/Jackett#3294]
Hello,

Wrong size for torrents coming from YGGTorrent source)
Size is always  <1Mb

It leads to issue with couchpotato

**Jackett version**:  Version 0.8.1162.0
**Mono version** (if not using Windows):  5.10.1.20 

-------------------------------

**Comment by kaso17** [comment]
fixed via 5343c9109bdf0a03e0d2b2811e47f2b32b6edd5e + 8b861467153831c356d1cd54f79e5dac79f3f772
