### ISSUE TITLE
Torrent.ai (torrentlt) can't handle dots in the search string

### ISSUE THREAD

**Issue by visata** [Jackett/Jackett#3296]
Torrent.ai (torrentlt) can't handle dots in the search string.

Doesn't work:
?search=daily+show+2018.06.26

Works:
?search=daily+show+2018+06+26

**Comment by kaso17** [comment]
fixed via  (untested)

**Comment by visata** [comment]
I copy pasted the patch below to Jackett/Jackeet/Definitions/torrentlt.yml 
```
    keywordsfilters:
      - name: replace
        args: [".", " "] # issue #3296 
```

It doesn't seem to replace the dots to spaces. Here is what I see in Jackett's logs:
```
Found 0 releases from Torrent.LT for: Daily Show 2018.06.26
--

```

**Comment by visata** [comment]
I'm not sure how Jackett works but maybe I need to clear the cache or something?

**Comment by kaso17** [comment]
please try updating to v0.8.1201
