### ISSUE TITLE
[Definition] FrozenLayer doesn't allow search

### ISSUE THREAD

**Issue by IhToN** [Jackett/Jackett#3301]
**Jackett version**:  0.8.1162.0

-------------------------------
Error when trying to search some keywords using Sonarr or Radarr:

`[v2.0.0.5228] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: frozenlayer does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported.
`

The file to edit would be:
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/frozenlayer.yml

Example on link to search (public tracker):
https://www.frozen-layer.com/buscar/descargas/todos/little witch?search=Buscar

Thanks!

**Comment by kaso17** [comment]
What's the query URL you're sending to jackett?

**Comment by IhToN** [comment]
https://myjackettdomain.com/api/v2.0/indexers/frozenlayer/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Boku%20no%20Hero%20Academia&season=1&ep=1

**Comment by kaso17** [comment]
That query works perfectly fine for me (returning no results but that's a different problem)

**Comment by IhToN** [comment]
Yep, it seems something changed within it, the result can be replicated if you remove 5070 from the categories.

But as you say, the current result is:
![imagen](https://user-images.githubusercontent.com/16889094/42048407-78ad3546-7b03-11e8-8800-dc6fe0d73934.png)

But it should respond with the list of episodes:
https://www.frozen-layer.com/buscar/descargas/todos/Boku%20No%20Hero?search=Buscar

But in this case is something related to Frozen Layer itself as their torrent names doesn't set the season numerically but mark them as "first season" (primera temporada), "second season" (segunda temporada), "third season" (tercera temporada)...
I don't know if that would be possible to fix but yes, I guess that something that the tracker should take into account and name the files properly.

Thanks and sorry for bothering.

**Comment by IhToN** [comment]
A possible solution, but ugly one, would be to do something like this:

`filters:
          - name: re_replace
            args: ["\\/", " "]
          - name: re_replace
            args: ["\\(", ""]
          - name: re_replace
            args: ["\\)", ""]
          - name: re_replace
            args: ["([A-z]*) temporada", "S$1"]
          - name: re_replace            args: ["Sprimera", "S1"]
          - name: re_replace
            args: ["Ssegunda", "S2"]
          - name: re_replace
            args: ["Stercera", "S3"]
          - name: re_replace
            args: ["S([0-9]) - Episodio ([0-9]*)", "S$1E$2"]
          - name: re_replace
            args: ["- Episodio ([0-9]*) al ([0-9]*))", "E[$1-$2]"]   # this would mean Episode 1 to 12
          - name: re_replace
            args: ["- Episodio ([0-9]*)", "E$1"]
`

Although I guess it's not a generic one

**Comment by kaso17** [comment]
Added your changes via 847c5dfdcb9dd8db6af6f158c7af611b1bbade32
Also removed S/EXX from the search string. Or does the tracker provide any way of searching for a specific season/episode.
Not sure how sonarr handles single digit season/episode tags. You might have to add some more regexes to add a leading 0 in case of single digit S/E values.

**Comment by kaso17** [comment]
regarding the initial error: if you remove 5070 (TV/Anime) from the categories list the error is totally expected (the indexer only supports 5070).
