### ISSUE TITLE
[downloadville] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by EdRawaled** [Jackett/Jackett#3305]
An error occured while testing the Downloadville indexer

**Jackett version**:  0.8.1162.0 and 0.8.1180.0
**Mono version** (if not using Windows):  5.12.0.226

-------------------------------

CardigannIndexer (downloadville): Error while parsing row '<tr>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="index.php?page=torrents&amp;category=63">
			<img src="style/xbtit_default/images/categories/Livres Journaux.png" border="0" alt="Journaux" title="">			
		</a>
	</td>           <td class="lista" valign="middle" onmouseover="this.className='post'" onmouseout="this.className='lista'" style="padding-left:10px;overflow:auto;">
		<a href="index.php?page=torrent-details&amp;id=bae5c349daf8f42a06602d8929f7e7d4dcab52f4" title="Voir les détails: le.monde.28.06.18" onmouseover=" return overlib('<center>le.monde.28.06.18</center><center><img src=torrentimg/bae5c349daf8f42a06602d8929f7e7d4dcab52f4.jpg  width=200 border=0></center><center>Catégorie: Journaux Taille: 8.37 MB</center><center>Ajouté:1 jour ago</center><center><font color = green>Seeders: 4<font color = red> Leechers: 0<font color = purple> Complété: 3</font></center>', CENTER);" onmouseout="return nd();">le.monde.28.06.18</a>&nbsp;&nbsp;<br>		            &nbsp;&nbsp;</td>                      <script>
var g_nExpando=0;
function putItemInState(n,bState)
{
   var oItem,oGif;
      oItem=document.getElementById("descr"+n);
   oGif=document.getElementById("expandoGif"+n);
   
   if (bState=='toggle')
     bState=(oItem.style.display=='block');
   if(bState)
   {
       bState=(oItem.style.display='none');
       bState=(oGif.src='images/plus.gif');
   }
   else
   {
       bState=(oItem.style.display='block');
       bState=(oGif.src='images/minus.gif');
   }
}
function expand(nItem)
{
    putItemInState(nItem,'toggle');
}
function expandAll()
{
    if (!g_nExpando)
    {
        document.all.chkFlag.checked=false;
        return;
    }
    var bState=!document.all.chkFlag.checked;
    for(var i=0; i<g_nExpando; i++)
        putItemInState(i,bState);
}
</script>                      <td align="center" width="20" class="lista" style="text-align: center;">---</td>                              <td align="center" width="20" class="lista" style="text-align: center;">
		<a href="index.php?page=bookmark&amp;do=add&amp;torrent_id=bae5c349daf8f42a06602d8929f7e7d4dcab52f4">
			<img src="images/bookmark.png">			
		</a> </td>           <td align="center" width="40" class="lista" style="white-space:wrap; text-align:center;">27/06/2018 12:31:06</td> <td align="center" width="30" class="lista" style="text-align:center;">1 jours</td>                  <td align="center" width="30" class="#FFFF00" style="text-align: center;background:#00FF80">
		<a href="index.php?page=peers&amp;id=bae5c349daf8f42a06602d8929f7e7d4dcab52f4" title="Cliquez ici pour voir les détails des clients">4</a>
	</td>           <td align="center" width="30" class="#FF0000" style="text-align: center;background:#FF0000">
		<a href="index.php?page=peers&amp;id=bae5c349daf8f42a06602d8929f7e7d4dcab52f4" title="Cliquez ici pour voir les détails des clients">0</a>
	</td>           <td align="center" width="30" class="lista" style="text-align: center;">
		<a href="index.php?page=torrent_history&amp;id=bae5c349daf8f42a06602d8929f7e7d4dcab52f4" title="Historique - le.monde.28.06.18">3</a>
	</td>                      <td align="center" width="30" class="lista" style="text-align: center;">
		<a href="index.php?page=userdetails&amp;id=10356">
			<span style="color:#ae0001">ConcombreMasqué</span>
		</a>
	</td>                      <td align="center" width="45" class="lista" style="text-align: center;">8.37 MB</td>                                           <td align="center" width="45" class="lista" style="text-align: center;">100%<br>
		
		<table border="0" width="44" cellspacing="0" cellpadding="0">
			<tbody>
				<tr>
					<td align="right" border="0" width="2">
						<img src="images/bar_left.gif">						
					</td>
					<td align="left" border="0" background="images/progbar-red.gif" width="40">
						<img height="9" width="40" src="images/progbar-green.gif">						
					</td>
					<td align="right" border="0" width="2">
						<img src="images/bar_right.gif">						
					</td>
				</tr>
			</tbody>
		</table>
	</td>
	<td align="center" width="45" class="lista" style="text-align: center;background:">
		<a href="index.php?page=torrents&amp;action=up&amp;info_hash=bae5c349daf8f42a06602d8929f7e7d4dcab52f4">
			<img src="images/go_top.png" border="0" remonter="" alt="" title="">			
		</a>
	</td>
	<td class="lista" align="center" style="text-align: center;">	</td>         </tr>':

System.Exception: Error while parsing field=date, selector=td:nth-of-type(4), value= -04:00: DateTime parsing failed for "-04:00": System.Exception: FromFuzzyTime parsing failed
  at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime (System.String str, System.String format) [0x00023] in C:\projects\jackett\src\Jackett.Common\Utils\DateTimeUtil.cs:119 
  at Jackett.Common.Utils.DateTimeUtil.FromUnknown (System.String str, System.String format) [0x00254] in C:\projects\jackett\src\Jackett.Common\Utils\DateTimeUtil.cs:209 
  at Jackett.Common.Indexers.CardigannIndexer+<PerformQuery>d__29.MoveNext () [0x01626] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:1454

**Comment by kaso17** [comment]
@Celedhrim can you have a look at this?
