### ISSUE TITLE
[Bug] YTS & YIFY No Results

### ISSUE THREAD

**Issue by zero77** [Jackett/Jackett#3309]
When searching with both YTS and YIFY no results are displayed if the date is left in the search query.

**Jackett version**:  v0.8.1201
**Mono version** (if not using Windows):  5.12.0.226

**Comment by kaso17** [comment]
What do you mean with "if the date is left in the search query"?

**Comment by zero77** [comment]
@kaso17 
For example: 
film name 2018 = no results 
film name = results

**Comment by garfield69** [comment]
unable to replicate. closing.
![image](https://user-images.githubusercontent.com/6933240/46778578-cf22dd80-cd70-11e8-82c3-c79e57fd86e1.png)
