### ISSUE TITLE
torrentz.eu is missing

### ISSUE THREAD

**Issue by vinchi007** [Jackett/Jackett#331]
in previous branches there used to be torrentz.eu - can you please add it back. Thank you!

**Comment by ajslater** [comment]
This project is not adding public trackers as a matter of policy.

**Comment by JigSawFr** [comment]
As @ajslater said, public trackers are no longer accepted, maybe in a short-term future.

**Comment by ajslater** [comment]
However, an old fork exists from the public tracker days. Last commit was March: https://github.com/raspdealer/Jackett
