### ISSUE TITLE
[blutopia] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by travisboss** [Jackett/Jackett#3312]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.1162.0
**Mono version** (if not using Windows):  5.12.0.226

-------------------------------

Jun 30, 2018 01:53:15 PM | Error | System.Exception: Found no results while trying to browse this tracker   at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x000e8] in C:\projects\jackett\src\Jackett.Common\Services\IndexerManagerService.cs:225  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <ee725f74938b4972b8a81df0be67ae23>:0    at Jackett.Controllers.IndexerApiController+<Test>d__12.MoveNext () [0x000d3] in <fbfa02eccd084f9abf649cd074c72064>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Threading.Tasks.TaskHelpersExtensions+<CastToObject>d__0.MoveNext () [0x0005b] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__17`1[TResult].MoveNext () [0x001a7] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Web.Http.Controllers.ApiControllerActionInvoker+<InvokeActionAsyncCore>d__1.MoveNext () [0x000ab] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__17`1[TResult].MoveNext () [0x001a7] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x00091] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x001ad] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__5.MoveNext () [0x00103] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x00091] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x001ad] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__5.MoveNext () [0x00103] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Web.Http.Controllers.ActionFilterResult+<ExecuteAsync>d__5.MoveNext () [0x001af] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Web.Http.Filters.AuthorizationFilterAttribute+<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext () [0x000f3] in <69abafc3d8434ab584330d77cc8d6da3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <ee725f74938b4972b8a81df0be67ae23>:0    at System.Web.Http.Controllers.ExceptionFilterResult+<ExecuteAsync>d__6.MoveNext () [0x00087] in <69abafc3d8434ab584330d77cc8d6da3>:0
-- | -- | --

**Comment by kaso17** [comment]
#3313 shouldn't fix your problem.
Can you please share a full enhanced log (not just the error)

**Comment by travisboss** [comment]
[jacketlog.txt](https://github.com/Jackett/Jackett/files/2153292/jacketlog.txt)

This should be everything from my enhanced log I just tried to test the connection and it failed, it successfully adds blutopia but the test always fails.

**Comment by kaso17** [comment]
the log is still incomplete (even less than you posted before)

**Comment by travisboss** [comment]
[jackettUpdatedLog07032018.txt](https://github.com/Jackett/Jackett/files/2161623/jackettUpdatedLog07032018.txt)

Here is a new log with enhanced, I hope this is enough.

**Comment by kaso17** [comment]
this has been fixed with version v0.8.1201 5 days ago
