### ISSUE TITLE
Connecting to Jackett using Internet Explorer 11 causes HTTP Error 503 on Window's Server 2016

### ISSUE THREAD

**Issue by BetaLeaf** [Jackett/Jackett#3314]
**Jackett version**:  0.8.1100.0
**Mono version** (if not using Windows):  Using Windows Server 2016

-------------------------------

As the title says, connecting to Jackett using Internet Explorer 11 on Window's Server 2016 causes HTTP Error 503.

**Comment by BetaLeaf** [comment]
- Is it only happening with IE11?
    - I only tested Chrome and IE11, so not sure. 
  - Are you accessing it directly or via IIS?
    - Directly
  - Have you tried both localhost & 127.0.0.1?
    - Yes, both fail.
  - Any difference running as admin?
    - No difference.
  - Try running JacketConsole.exe --ReserveUrls as admin
    - **That fixed it.**
  - Running via console or windows service? Did you use the installer?
    - Window's Service
  - In C:\ProgramData\Jackett there is a serverconfig file. Does changing the port or AllowExternal make any difference?
    - Didn't test, see above.
  - Provide a full enhanced log by starting Jackett with JackettConsole.exe -t -l
    - I did this yesterday, but I didn't see anything that helped. Now I can't test properly because a previous step fixed it. See above.

Is it an error that it didn't do this automatically or is there a reason it doesn't run with --ReserveUrls?

**Comment by kaso17** [comment]
I'm not a windows expert, but --ReserveUrls should be called during the install (if you use the installer). If you later enable external access --ReserveUrls need to be executed manually.
@flightlevel can't we just reserve all URLs when calling --ReserveUrls ?

**Comment by flightlevel** [comment]
Good point @kaso17  Done in 00e4e8109e1f369c8683466a3a2e8e8f22b37ee8
