### ISSUE TITLE
[horriblesubs] Exception (horriblesubs): Got redirected to another domain. Try changing the indexer URL to https://horriblesubs.info/.: Parse error (Test)

### ISSUE THREAD

**Issue by colsw** [Jackett/Jackett#3318]
**Jackett version**:  Latest (0.8.1201.0)
**Mono version** (if not using Windows):  n/a

-------------------------------

seems like the fix in #2605 is now causing an issue when they've moved back to forced-https.

recommend the primary and secondary links be swapped so that it is default https again.

**Comment by kaso17** [comment]
Looks like they changed the site too.
https://horriblesubs.info/lib/latest.php?value= is no longer available.
The new latest list only show the series title, not the individual releases.
Is there another list containing the latest releases/search results one by one instead of this grouped view?

If not the indexer needs to be re-implemented as native indexer.

**Comment by MrsAngelD** [comment]
Came here to report this error, glad I checked before posting.

**Comment by Lauwens** [comment]
This might help:
https://horriblesubs.info/api.php?method=getlatest

**Comment by shlatchz** [comment]
@Lauwens how do I apply it to `horriblesubs.yml`?

**Comment by p-sebastian** [comment]
@Lauwens updating the SiteLink to that, still shows an error for me

**Comment by 64Hz** [comment]
Tried updating the Site Link to that also and no luck for me.

**Comment by 64Hz** [comment]
The reason the link from @Lauwens won't work is that Jackett continuously applies a final `/` at the end of any Site URL. However this specific URL does not reach anything with the `/` added and I can see no way to remove it.

**Comment by kaso17** [comment]
The api.php output is not useful (it's what's used by the main page).
This needs to be rewritten as native C# indexer

**Comment by Lauwens** [comment]
Indeed wont work anymore and will need a new indexer, (as stated in their update) they changed it to go to an extra page for monetizing reasons

> Finally, yes, it takes an extra click to download something now. I'll be honest. This is done mainly to improve revenue and SEO.

**Comment by 64Hz** [comment]
Could you link the source for that?

Not that I don't believe you, I just want to read the whole thing. :-)

**Comment by Lauwens** [comment]
It is on the main site: https://horriblesubs.info/2018/07/j-list-ax-giveaway-and-site-updates/

**Comment by 64Hz** [comment]
Thanks a bunch!

**Comment by ilco3** [comment]
does some one know a quick fix  for this - i would be verry thankfull

**Comment by 64Hz** [comment]
I still can't find a way to stop Jackett from appending a `/` to the end of the link @Lauwens sent:

> This might help:
> https://horriblesubs.info/api.php?method=getlatest

Any ideas anyone? 
Jackett changes the above URL to `https://horriblesubs.info/api.php?method=getlatest/` which doesn't work.

**Comment by flightlevel** [comment]
There is heaps of devs that have posted/viewed this issue. Its not a massive task to implement a tracker and there is heaps of examples in https://github.com/Jackett/Jackett/tree/master/src/Jackett.Common/Indexers to copy from. Community assistance needed

**Comment by 64Hz** [comment]
@colsw I tested both URL's as my Jackett indexer for HorribleSubs and whilst the URLs work in a browser, Jackett seems to be unable find any releases from it. I will leave it saved and see if that changes when they next release something, but just wanted to let you know.

**Comment by kaysond** [comment]
Bump. Their RSS feed is a useful stopgap. Can't search, but at least you can grab latest releases: https://horriblesubs.info/rss.php?res=all

Also want to comment that their search api method (`https://horriblesubs.info/api.php?method=search&value=test&_=1534542892201`) doesn't seem to always get the most results.

Might be worth periodically scraping `https://horriblesubs.info/shows/` for shows, parsing the show pages (`https://horriblesubs.info/shows/made-in-abyss/`) for the show ID (`<script type="text/javascript">var hs_showid = 924;</script>`) to create a cache that can be used for future searches using the getshows api method (`https://horriblesubs.info/api.php?method=getshows&type=show&showid=924&nextid=1&_=1534543062011`)

**Comment by squirrelboot** [comment]
Still having this same problem. Note the URL needs to be https:// for anyone else who had issues there. 
After that is fixed, it returns:

> An error occured while testing this indexer
> Found no results while trying to browse this tracker

**Comment by squirrelboot** [comment]
Actually I have more to add to this:

`
System.Exception: Found no results while trying to browse this tracker   at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x000e8] in C:\projects\jackett\src\Jackett.Common\Services\IndexerManagerService.cs:225  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Server.Controllers.IndexerApiController+<Test>d__15.MoveNext () [0x000e1] in C:\projects\jackett\src\Jackett.Server\Controllers\IndexerApiController.cs:141  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <f5622e7f79be469e83d9e2bde9addd07>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x00042] in C:\projects\jackett\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:29
`

**Comment by au5ton** [comment]
If you are using this for Sonarr, an alternative at this point is to search another tracker (like [nyaa](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/nyaasi.yml) or [nyaa-pantsu](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/nyaa-pantsu.yml)) for releases containing `[HorribleSubs]`.

**Comment by 64Hz** [comment]
I've been doing what Austin suggested above and it has worked well.
You can specify within sonar to search for Specific strings in releases
based on tags within sonarr.

E.g. I have tagged Tokyo Ghoul with `hs` and it will search directly for
`[Horrible subscribe]` to be included in the torrent title.

**Comment by kaysond** [comment]
@au5ton @64Hz Thanks that's a great workaround

**Comment by flightlevel** [comment]
Thanks to @gerdus this is now back in the latest release

**Comment by flightlevel** [comment]
@kaysond try latest version of Jackett

**Comment by kaysond** [comment]
@flightlevel fixed! thanks
