### ISSUE TITLE
Btbit captcha issue

### ISSUE THREAD

**Issue by t-zone** [Jackett/Jackett#3319]
Indexer Btbit now uses a captcha process which breaks it's Jackett functionality. Is there a way around this?

**Jackett version**:  v0.8.1162
**Mono version** (if not using Windows):  Windows 10 Pro

-------------------------------

**Comment by kaso17** [comment]
This cloudflare captcha can't be handled easily (It needs to be resolved every couple of hours again). Some trackers activate this high level of CF protection in case of extreme DDoS attacks and deactivate it later again. Not sure why they decided to activate it.
