### ISSUE TITLE
Jackett with couchpotato

### ISSUE THREAD

**Issue by NunoMiguelVeloso** [Jackett/Jackett#332]
Hi guys, I'm already using jackett with sonarr and works great but with couchpotato I just cant connect to Jackett.

I got this error when couchpotato do a search through Jackett: "A request from 127.0.0.1 was made with an incorrect API key."

I've enable TorrentPotato:
Host: http://127.0.0.1:9117/potato/hdtorrents
Pass Key: jackett_apikey

I'm I doing something wrong? Anyone with the same problem?

Cheers

**Comment by duramato** [comment]
Double check the api key  in couch potato's config file just to be sure,  I've  had issues with CP not saving them correctly at times,  for some reason

**Comment by NunoMiguelVeloso** [comment]
Thanks man! Fixed
