### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: Selector

### ISSUE THREAD

**Issue by Leicas** [Jackett/Jackett#3325]
Stopped working with error being  
Exception (yggtorrent): Login failed: Selector "a[href$="/user/logout"]" didn't match: Parse error

**Jackett version**:  0.8.1209.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
