### ISSUE TITLE
[torrentday] Your cookie did not work: Got a redirect to https://torrentday.it/t.json?29

### ISSUE THREAD

**Issue by rednekcowboy** [Jackett/Jackett#3326]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------
cookies no longer working, either update your screenshot or be specific on exactly what you need!!!!

**Comment by kaso17** [comment]
It's working fine.
I've update the screenshots on https://github.com/Jackett/Jackett/wiki/Finding-cookies

**Comment by rednekcowboy** [comment]
Thank you, it is now working with the updated screenshots.

Was weird before as I was able to add it to Cardigann (which is the only reason I used that software) but not here.

Sorry if I was short with you, was pretty frustrated at that point lol.  I tremendously appreciate your work here!
