### ISSUE TITLE
Gimmepeers tracker / old Bitsoup

### ISSUE THREAD

**Issue by crazylobster70** [Jackett/Jackett#333]
Can you add a new private tracker  www.gimmepeers.com. It is a new private tracker of Bitsoup owners ,Bitsoup will be soon closed

**Comment by duramato** [comment]
Another tracker like bitsoup? A pay2leech one?

**Comment by crazylobster70** [comment]
not quite as pay2leech but much better than Bitsoup

**Comment by mentasm** [comment]
I'll add my vote here too.  the bitsoup tracker will soon be defunct.  I think the category numbers might have changed on the new site.  I can see if I can get a category map

**Comment by mentasm** [comment]
Heres a mapping file
[gimmepeers.txt](https://github.com/Jackett/Jackett/files/260933/gimmepeers.txt)

**Comment by Kwyj** [comment]
Please do **NOT** add gimmepeers. 

In response to @duramato - Yes, they are a pay to leech site but, worse than that, it is a scam site that will quite happily take money in the form of subscriptions then delete user accounts.
Refer to https://www.reddit.com/r/bitsoup/ for more information.

Do not add this tracker as it will only add an air of legitimacy to their scam.

**Comment by duramato** [comment]
fyi I said it in a sarcastic matter, bitsoup is gone afaik so gimmepeers won't be alive any longer without people, it's 2016 no one had paid or will pay for torrent tracker acess...

**Comment by SuxToobu** [comment]
@ crazylobster70
With all due respect gimmepeers is far worse a pay2leech site than bitsoup EVER was.
bitsoup had a large PU base. Any members that wanted to join their new gimmepeers site, PU and VIP were required to pay a $10 transfer fee "VIPs were given 72 hours to sign up to the new site ($10 fee) or they forfeit their remaining membership time" On top of that there is a monthly $10 membership fee ALL members must pay, no exception. So what you mean by "not quite as pay2leech but much better than Bitsoup"  I have no clue.

**Comment by crazylobster70** [comment]
@SuxToobu 
after reading on https://www.reddit.com/r/bitsoup/ about bitsoup I definitely changed my mind about them, that what SuxToobu wrote about them is complete truth.I'm sorry that I tried to defend them

**Comment by P1X3L8ED** [comment]
1000% Pay to Leech Scam all over again!!!
