### ISSUE TITLE
YGGTORRENT - Wrong size returned

### ISSUE THREAD

**Issue by leloki** [Jackett/Jackett#3331]
Hi,

I have an issue with yggtorrent tracker, the search works fine but the size of the release are completly wrong (in Bytes), how could I correct this please ?

Thanks !
![capture](https://user-images.githubusercontent.com/7544624/42231585-3ac9ae34-7eec-11e8-8c74-d078039c8a30.PNG)

**Jackett version**:   Jackett Version 0.8.1162.0 
**Mono version** (if not using Windows):   5.12.0.233

-------------------------------

**Comment by kaso17** [comment]
already fixed in the latest release

**Comment by leloki** [comment]
I had to update the definition file indeed and the last release. It works now.

Thanks !
