### ISSUE TITLE
[REQ] TehConnection

### ISSUE THREAD

**Issue by sentriz** [Jackett/Jackett#3332]
**Jackett version**:  0.8.1123.0

Hello, I don't see Teh on the tracker list, but there are github issues here related to it. Has it been removed? Thank you

**Comment by kaso17** [comment]
The old TehConnection was supported and removed when the tracker shutdown. The new TehConnection.me (AFAIK it has nothing to do with the old one) just has been added via 636be458a6967d889960c7e2efa17357385c9f65

**Comment by sentriz** [comment]
Oh, I didn't know the original was shut down.
Thank you for adding it back
