### ISSUE TITLE
2FA Support

### ISSUE THREAD

**Issue by Oius** [Jackett/Jackett#3345]
hello,

i would like to request support for 2 factor authentication.
Currently i cant use jackett with redacted when it has 2FA enabled.

not sure if it's even possible, but if it is it would be great.

Kind Regards, Tim

Jackett Version 0.8.1162.0

**Comment by kaso17** [comment]
It should be possible to integrate, help is welcome.

**Comment by d2dyno** [comment]
Bumping as I just enabled 2fa on all my trackers

**Comment by BurhanDanger** [comment]
Me also ( just subscribing here)

**Comment by BurhanDanger** [comment]
@garfield69 can we not get cookie support as an alternative. For eg. I have 2FA enabled on GGn and with cookies I can still use it with jackett.

**Comment by garfield69** [comment]
@BurhanDanger sure. only problem is that the cardigann processor (for the yaml indexers) does not support **optionally** providing a _full_ login versus a _cookie_ login. 
its one or the other, unless someone volunteers to provide the c# coding to make that change, in which case they might as well implement the optional 2fa support.
I am not a c# developer.
Assuming GGn (which existing indexer is this by the way?) is a yaml indexer, I could in the mean time, provide an alternate indexer with the cookie login... just name the indexer(s).

**Comment by mvanbaak** [comment]
GGn == GazelleGames

**Comment by garfield69** [comment]
@mvanbaak  thanks for the GGn explanation.

GazelleGames is a c# indexer. I'll take a look but I don't think I can change this one unless I can find another c# indexer that uses a cookie logon. I'll post back if I get lucky... or not.
As I may have posted before, I'm not a c# developer, I support mostly the cardigann yaml indexers. But I'm willing to make c# changes as long as its simple and I've got an example to follow.

**Comment by Y0lan** [comment]
I support this request !

**Comment by Brando47** [comment]
Something I'd like to see as well, I see some trackers are giving rewards for having 2FA enabled and it'd be nice to still be able to use them with Jackett

**Comment by awsms** [comment]
Why not just implement a way to add a session cookie if 2FA is enabled, like it's done for IPT, SBS etc?

**Comment by mvanbaak** [comment]
> Why not just implement a way to add a session cookie if 2FA is enabled, like it's done for IPT, SBS etc?

Because of what was said on Juli 4:

> only problem is that the cardigann processor (for the yaml indexers) does not support optionally providing a full login versus a cookie login.
> its one or the other, unless someone volunteers to provide the c# coding to make that change, in which case they might as well implement the optional 2fa support.

**Comment by danaimone** [comment]
I'll see if this is something I can tackle. I'm a bit rusty with my C#, but I did do some website building in ASP; no guarantees!

**Comment by ljmerza** [comment]
@danaimone hey any update on this? Does it seem doable? I'm not a C# dev but would love this to be added in.

**Comment by joydashy** [comment]
Would also love this!

**Comment by BurhanDanger** [comment]
Why is this issue closed ? Is two factor authentication now supported for every tracker?

**Comment by ngosang** [comment]
This issue was open for Redacted.
Jackett supports ~500 trackers and most of them don't support 2FA authentication method. It's better to open one different issue for each tracker with 2FA support not implemented in Jackett.

**Comment by ljmerza** [comment]
This is for 2fa support for redacted. That has been fixed with an api workaround. If you want 2fa support on a different tracker open up a new issue.

**Comment by garfield69** [comment]
Jackett 0.16.1664
