### ISSUE TITLE
French-ADN : Torrents Page Changes : Unable to parse anymore

### ISSUE THREAD

**Issue by itdaboyz** [Jackett/Jackett#335]
Hi,

Since some days, Jackett can't connect to French ADN : 
```
May 12, 2016 10:04:18 AM 	Error 	
Exception in test_indexer
May 12, 2016 10:04:16 AM 	Error 	
-> Login failed: Error during attempt !
```

Jackett Version 0.7.237.0
Mono version 4.2.2

**Comment by JigSawFr** [comment]
Thanks for report i will investigate ASAP !

**Comment by JigSawFr** [comment]
Just checked, and i performed loggin without problems:
`Validating Settings ...

Validated Setting -- Username (auth) => ** Censored **
Validated Setting -- Password (auth) => ** Censored **
Validated Setting -- Max Pages => 4

Validated Setting -- Browser Simulation enabled
Validated Setting -- ACCEPT (header) => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Validated Setting -- ACCEPT-LANG (header) =>    fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
Validated Setting -- USER-AGENT (header) => ** Censored **

Deleting Provider Storage folder and all files recursively ...
-> No Storage folder found for this provider !

Getting index page (for cookies).. with https://french-adn.com/

Getting login page (user simulation).. with https://french-adn.com/login.php?

Perform loggin.. with https://french-adn.com/takelogin.php

Cookies saved for future uses...

-> Login Success


-> Checking logged-in state....
-> Already logged, continue...


Builded query for "all"... https://french-adn.com/browse.php?do=search&keywords=&category=&search_type=t_name

Querying tracker for results....

Found 4480 result(s) (+/- 40) in 112 page(s) for this query !

There are 40 results on the first page !`

**Comment by itdaboyz** [comment]
Is this only on my server then?
It's strange, i changed nothing and it worked great before.

When trying again, I have a different error :
	
```
Error on 20160513201716 for French-ADN.txtSystem.NullReferenceException: Object reference not set to an instance of an object
  at Jackett.Indexers.FrenchAdn+<PerformQuery>c__async3.MoveNext () [0x006dd] in C:\projects\jackett\src\Jackett\Indexers\FrenchAdn.cs:404 
Error, unable to parse result 
  at Jackett.Indexers.FrenchAdn+<PerformQuery>c__async3.MoveNext () [0x006dd] in C:\projects\jackett\src\Jackett\Indexers\FrenchAdn.cs:404 
```

**Comment by duramato** [comment]
Maybe its blocked for you?

**Comment by itdaboyz** [comment]
I can access the site without problem, but Jackett can't.
Maybe they banned Jackett only but I doubt it.

**Comment by JigSawFr** [comment]
@itdaboyz problem you referred is different, you can login without problem, but they edited torrents page, so Jackett is unable to parse due to changes on tracker's side, i'm fixing it.

**Comment by JigSawFr** [comment]
I will submit pull request as soon as possible. Stay tuned.
