### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Connection refused: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by sameep22** [Jackett/Jackett#3366]
So I am not sure which information I need to add, since i have just added the pirate bay link from the provided options. However, this is the error I get.

-------------------------------

**Comment by flightlevel** [comment]
Is your ISP blocking it?

**Comment by ageisen2000** [comment]
Mine also recently started doing this. I use pi-hole for DNS if that makes a difference.
