### ISSUE TITLE
[gktorrent] Exception (gktorrent): Got redirected to another domain. Try changing the indexer URL to http://www.gktorrent.org/.: Parse error (Test)

### ISSUE THREAD

**Issue by campbc** [Jackett/Jackett#3372]
Look like GKtorrent change sites to https://www.gktorrent.org/ vs https://www.gktorrent.net/

Jackett Version 0.8.1258.0 
Mono JIT compiler version 5.12.0.226

**Comment by kaso17** [comment]
already fixed via e1ff4b9e121d770aa422c117daab314f061711c5

**Comment by campbc** [comment]
Thanks!
