### ISSUE TITLE
Mono update caused Jackett to stop working properly

### ISSUE THREAD

**Issue by Theogermal** [Jackett/Jackett#3373]
On my asustor NAS, Mono got updated to 5.8.1.0.r6 and doing so caused jackett to stop working.

I've tried searching for fixes and the ones I did find have not solved the problem for me. My log file is attached. Any help is greatly apprecited.
[log.txt](https://github.com/Jackett/Jackett/files/2186211/log.txt)

**Comment by Theogermal** [comment]
Hey, yes I've tried the fix from issue #3348 plus a fix from a thread on the asustor forums

 https://forum.asustor.com/viewtopic.php?f=23&t=9717#

That version is the latest I can install from the asustor apps and I am unable to update to a more recent version as it just tells me that updates failed. 

I'll run cert-sync when I get home again

**Comment by flightlevel** [comment]
Read this post in the forum
https://forum.asustor.com/viewtopic.php?f=23&t=9717#p31431
or this
https://github.com/duplicati/duplicati/wiki/SSL-TLS-support-in-Mono#asustor

Both give the path to cert-sync on Asustor

**Comment by Theogermal** [comment]
Ok, after a bit of struggling, I did a fresh re-install and then ran
`sudo mono /usr/local/AppCentral/mono/lib/mono/4.5/cert-sync.exe /etc/ssl/certs/ca-certificates.crt`

Everything seems to be working fine now.

Thanks for the help
