### ISSUE TITLE
Nginx Reverse Proxy now gives 404 for Jackett

### ISSUE THREAD

**Issue by akanealw** [Jackett/Jackett#3378]
**Jackett version**:  0.9.1
**Mono version** (if not using Windows):  

-------------------------------
Was working on previous versions, now 404s on same nginx config as before:

   location /jackett {
		    proxy_pass http://127.0.0.1:9117;
		    proxy_set_header Host $host;
        	    proxy_set_header X-Real-IP $remote_addr;
		    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		}

ServerConfig.json:

 "Port": 9117,
  "AllowExternal": true,
  "BlackholeDir": "C:\\NZBHydra2\\Torrents",
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": "/jackett",
  "OmdbApiKey": "",
  "OmdbApiUrl": "",
  "ProxyUrl": "",
  "ProxyType": 0,
  "ProxyPort": null,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true

**Comment by D34DC3N73R** [comment]
Working for me using 0.9.1 docker (linuxserver.io) on Ubuntu server with letsencrypt+nginx (linuxserver.io). However, I use subdomains and don't forward headers. 

location / {
                include /config/nginx/proxy.conf;
                proxy_pass http://127.0.0.1:9117;
        }

**Comment by burkasaurusrex** [comment]
Same issue with IIS and using a subdirectory named "jackett". Probably something to do with the BasePathOverride.

I can access the service directly (e.g., via http://localhost:9117/jackett), however, I can't access it through the reverse proxy (e.g. via https://www.myurl.com/jackett).

**Comment by flightlevel** [comment]
v0.9 for Windows has a completely new webserver to host Jackett. Will investigate

**Comment by flightlevel** [comment]
@akanealw @burkasaurusrex 
Can you please try v0.9.2 (its a pre-release) and see how it goes?
It worked on nginx for me but haven't tested on IIS
56074155e9a408b7399447ddc1fb80d59bd9c265

**Comment by burkasaurusrex** [comment]
@flightlevel just downloaded and quickly tested and it appears to be working. Thanks!

**Comment by akanealw** [comment]
@flightlevel yep, that seems to have fixed it for me too. thanks!

**Comment by flightlevel** [comment]
Thanks for the feedback @akanealw @burkasaurusrex
Its now in the general release
