### ISSUE TITLE
MejorTorrent - Torrent Naming Issues

### ISSUE THREAD

**Issue by IhToN** [Jackett/Jackett#3384]
**Jackett version**:  0.9.1.0

-------------------------------

It seems that the new naming system doesn't recognize files as it should.
Here is an example of _Finding Dory_:
![imagen](https://user-images.githubusercontent.com/16889094/42665779-88189914-8641-11e8-9348-f1b98105adc1.png)

And also an example of _Now you see me_ (1 and 2):
![imagen](https://user-images.githubusercontent.com/16889094/42665827-c58fef0e-8641-11e8-8399-2e2b47265d9f.png)

Also, it seems that if a movie has in their original name that it's an extended version, 4k or 3D, that string gets removed.

Another good implementation would be the possibility "link" the anchor to the website, as it occurs with other indexers, right now every torrent found in MejorTorrent has an anchor to:
yourJackett.domain/UI/Dashboard

-------------------------------

After trying to understand the current indexer, it seems that right now it changes the category to 2160p of the title contains _(4k)_ in its name but it's also referenced as _(4K)_. Also 3D movies appear tagged with a _[3d]_ in its title.
Full BlueRay movies (BD25/BD50) appears as with the title tag _(fullbluray)_. Should be re-categorized as BR-DISK or something like that.

**Comment by IhToN** [comment]
It seems that @ivandelabeldad was making some changes to how MejorTorrent works.

**Comment by ivandelabeldad** [comment]
I didn't make some changes, I did the whole indexer.
I'll check this out when I have some time.

**Comment by IhToN** [comment]
Sorry, I haven't checked the whole history of the indexer, just the latest commit.
I was testing it out and those little things are what I've found so far.

**Comment by Yllelder** [comment]
To this day, the indexer still **doesn't differentiate whether a movie is 3D or 4k**.

This problem means that the indexer cannot be used as it often downloads the 3D version of the movie.

Still, I want to thank @ivanbeldad  for the work they did to create the indexer. Good job!
