### ISSUE TITLE
[blutopia] Exception (blutopia): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Parse error (Test)

### ISSUE THREAD

**Issue by KoopaTroopas** [Jackett/Jackett#3389]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  Version 0.9.1.0
**Mono version** (if not using Windows):  Version 5.12.0.226

-------------------------------
The posted fix for this bug doesn't work for me, I've verified that blutopia.yml is correct but I still receive the same error as before.  I have multiple other trackers in jackett that seem to work fine, and this one was working fine until a recent blutopia site that seemed to break it for everyone.

Full enhanced log for the tracker here can be found here: https://pastebin.com/DGV4mtJe

**Comment by KoopaTroopas** [comment]
The solution for that issue doesn't seem to fix my issue.  I've updated jackett to a version including that commit and it still fails on test

**Comment by KoopaTroopas** [comment]
Just adding a note that the latest v0.9.6 did not fix the issue either

**Comment by HDVinnie** [comment]
works fine for me since last update @kaso17 pushed

**Comment by KoopaTroopas** [comment]
Well, I'm not sure what caused the issue, but after deleting all of jackett's file and redownloading it works now.  Closing the issue
