### ISSUE TITLE
TorrentDay not using correct category for UHD releases

### ISSUE THREAD

**Issue by ghostbitmeta** [Jackett/Jackett#3393]
Jackett Version 0.9.1.0

When searching TorrentDay tracker for UHD films, it uses `https://torrentday.it/t.json?48;q=` instead of `https://torrentday.it/t.json?96;q=`

**Comment by flightlevel** [comment]
Done
In future you can easily correct these yourself
Open https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/TorrentDay.cs
Click on the pencil and you can make changes
