### ISSUE TITLE
IlCorsaroBlu not working anymore

### ISSUE THREAD

**Issue by JackHack96** [Jackett/Jackett#3395]
"IlCorsaroBlu" tracker is not working anymore. It seems they've changed something in their servers.

The error is:
```shell
Exception (ilcorsaroblu): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /build/mono-5.12.0.226/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request
```

**Jackett version**:  0.8.1229.0
**Mono version** (if not using Windows): 5.12.0.226 

-------------------------------

**Comment by flightlevel** [comment]
Please let the site admin know that their certificate chain is broken
https://www.ssllabs.com/ssltest/analyze.html?d=www.ilcorsaroblu.info&hideResults=on
7fc37f1156aa99ca670e7c44e10d4072f1666f81 is a temporary fix until they fix their certificates
