### ISSUE TITLE
Error adding tracker

### ISSUE THREAD

**Issue by justinrhodes** [Jackett/Jackett#340]
Jackett 0.7.247.0 running in a Docker on UnRaid. Cannot add a tracker, get this error.

Configuration failed: Mapping types: WebClientByteResult -> WebClientStringResult Jackett.Utils.Clients.WebClientByteResult -> Jackett.Utils.Clients.WebClientStringResult Destination path: WebClientStringResult Source value: Jackett.Utils.Clients.WebClientByteResult

**Comment by flightlevel** [comment]
Latest release fix should fix https://github.com/Jackett/Jackett/releases/tag/v0.7.251
The autoupdater won't work from version 247, so you will have to download manually
