### ISSUE TITLE
Jackett v0.8.490-6 package not available for Armada 38x?

### ISSUE THREAD

**Issue by cerulliulliulli** [Jackett/Jackett#3403]
**Jackett version**:  v0.8.490-6 

Assuming this one goes to @Dr-Bean, I noticed the Jackett package on SynoCommunity was updated for everything but Armada 38x? The package is available for other lesser Armada architectures, but that one is missing. There is a critical failure in the previous versions that was resolved in v0.8.490-6 and was hoping for some insight into why Armada 38x support seems to be missing.

Much appreciated!

**Comment by flightlevel** [comment]
You've got a much better chance of getting an answer asking the people who maintain the package at https://github.com/SynoCommunity/spksrc
Reading this issue over there it looks like there are users running Armada 38x https://github.com/SynoCommunity/spksrc/issues/2808 search for 38x and you can see users had success with it. Closing this so you can discuss with package maintainers at SynoCommunity
