### ISSUE TITLE
Request to Jackett server failed when trying to send torrent to blackhole directory

### ISSUE THREAD

**Issue by akanealw** [Jackett/Jackett#3406]
**Jackett version**:  0.9.6.0
**Mono version** (if not using Windows):  

-------------------------------

When trying to add a torrent to the blackhole directory "Request to Jackett server failed" pops up. Directory is valid, nothing I can see in the logs.

[log.txt](https://github.com/Jackett/Jackett/files/2199102/log.txt)

**Comment by flightlevel** [comment]
Is this specific to AniRena or all trackers?
Does not using reverse proxy make any difference?

**Comment by akanealw** [comment]
It's all trackers but only behind the reverse proxy. Locally it works fine. Sorry about that.
My knowledge of reverse proxies is very little so I'm open to suggestions.
Currently my config is this for Jackett.

    location /jackett {
				proxy_pass http://127.0.0.1:9117;
				proxy_set_header Host $host;
				proxy_set_header X-Real-IP $remote_addr;
				proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			}

**Comment by JigSawFr** [comment]
@akanealw can you tell us which download link are generated for your torrents ? Just search a torrent and c/c your download link. I suspect Host to be invalid in Nginx config or misconfig of base path in Jackett

**Comment by akanealw** [comment]
http://akanealw.com/jackett/bh/1337x/?jackett_apikey=<myapikey>&path=Q2ZESjhGSFVWc0RKdWVWT281RUNSZGdzOXpSd3dUVWkzS2lMTmFuU1NFemctaDBpems4RzJBb3lVTnVKZFFNMzA2aGdidjNoWkRpYXB4QzlOTnZhZlNUYWV3UU5OWmpSc2NCcjRjTXFIVXNReW9kb0l6ZExlU1QySHkwQTBZM1dXMGQ3TnJGRUc3MnNCU3NPRURJV3BtWTVZQmNpbFFkWXQ5TlJnZ2VjNkVyMnEzazREVXhiVk5EaUkxaXdRNkxlODI3dF9BTDQyYkhDM0xfeloyV2p6SklqRVlF&file=Ubuntu+16.04.1+LTS+Desktop+64-bit

nginx config:
    location /jackett {
				proxy_pass http://127.0.0.1:9117;
				proxy_set_header Host $host;
				proxy_set_header X-Real-IP $remote_addr;
				proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			}

jackett server.json:
  "Port": 9117,
  "AllowExternal": true,
  "APIKey": "<myapikey>",
  "AdminPassword": "<mypassword>",
  "InstanceId": "0yfuqq11rvfy6f37c81g07u462iju86r7g26ogvbq2pcqgn8vqvl377lozizi95u",
  "BlackholeDir": "C:\\NZBHydra2\\Torrents",
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": "/jackett",
  "OmdbApiKey": "",
  "OmdbApiUrl": "",
  "ProxyUrl": "",
  "ProxyType": 0,
  "ProxyPort": null,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true
}

**Comment by akanealw** [comment]
I got it working by matching my Jackett config in my nginx.conf file with what works for my NZBHydra config.

    location /jackett {
				proxy_pass http://127.0.0.1:9117;
				proxy_set_header Host $host;
				proxy_set_header X-Real-IP $remote_addr;
				proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
				proxy_set_header X-Forwarded-Proto $scheme;
				proxy_set_header X-Forwarded-Host $host;
				proxy_redirect off;
			}
