### ISSUE TITLE
Index site Torlock returns no results

### ISSUE THREAD

**Issue by binhex** [Jackett/Jackett#3408]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version: 0.9.6.0
Mono version (if not using Windows): 5.10.0

-------------------------------
Index site Torlock does not return any results, i performed a 'manual search' with query search terms 720p and again with search term 1080p, both returned zero results.

Again please let me know if you can't replicate and i will post logs.

p.s. test does pass for this index site but it takes a VERY long time.

**Comment by flightlevel** [comment]
Works perfectly here, must be your connection @binhex as you are reporting multiple indexers that work perfectly here

**Comment by binhex** [comment]
Please find attached the log file (enhanced logging enabled), i am still seeing no results returned, the manual search term was 720p in this test.
[torlock_log.txt](https://github.com/Jackett/Jackett/files/2201944/torlock_log.txt)

**Comment by flightlevel** [comment]
When I visit this site in the web browser (never visited before today)
Every torrent is called 'No name'. Is that normal and how do you know which one to click on?

![image](https://user-images.githubusercontent.com/9430010/43035497-67bc0238-8d34-11e8-8f7b-d9dc2fc431ec.png)

**Comment by garfield69** [comment]
torlock works fine for me so i'm closing this.
