### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 213.75.28.117:443: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by BLX-S** [Jackett/Jackett#3409]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.9.6.0

-------------------------------
Tried adding TPB using built-in menu but tests turn negative.

**Comment by flightlevel** [comment]
Is your ISP blocking the site?
