### ISSUE TITLE
Index site Torrentz2 returns no results and fails test

### ISSUE THREAD

**Issue by binhex** [Jackett/Jackett#3410]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version: 0.9.6.0
Mono version (if not using Windows): 5.10.0
-------------------------------
Index site Torrentz2 returns no results for 'manual search' with query string 720p or 1080p, it also fails to pass the test in jackett.

**Comment by flightlevel** [comment]
Works perfectly here, both the test and searching for 720p
![image](https://user-images.githubusercontent.com/9430010/42807547-7b217238-89f4-11e8-8372-a756889b4666.png)
Turn on enhanced logging, replicate the problem and then supply the log file

**Comment by binhex** [comment]
Hmm this looks to be a sporadic issue, i tested it again and it failed, i enabled enhanced logging, deleted the existing log, restarted jackett and it then worked, sods law in action perhaps :-), im happy to close for now and i will monitor it, if i see it fail again i will see if i can get some logs over to you.
