### ISSUE TITLE
Jackett v0.9.6: Not displaying API KEY on Windows 7

### ISSUE THREAD

**Issue by tawolude** [Jackett/Jackett#3414]
I have tried installing jackett several times on my laptop after i reverted from Windows 10 to windows 7 for some reasons but after i launch it, it doesn't show the API key. Kindly help.
Note: I'm new to the app. 

-------------------------------
![jackett v0 9 6](https://user-images.githubusercontent.com/14343427/42833798-2089eb68-89ed-11e8-9f5d-64807c97749b.PNG)

**Comment by flightlevel** [comment]
Stop the Windows service
Start Jackett from the command line using `JackettConsole.exe -t -l`
Then provide the log file

**Comment by tawolude** [comment]
could you help me out and show me step-by-step how to generate the logs needed because i can't seem to get what you require

**Comment by flightlevel** [comment]
-Stop Jackett service from Windows services
-Open command prompt
-`cd C:\ProgramData\Jackett`
-`JackettConsole.exe -t -l`
-Open file explorer, go to C:\ProgramData\Jackett 
-Copy the contents of log.txt to pastebin or similar site

**Comment by tawolude** [comment]
Find attached

[ServiceLog.txt](https://github.com/Jackett/Jackett/files/2216201/ServiceLog.txt)

[ServerConfig.txt](https://github.com/Jackett/Jackett/files/2216202/ServerConfig.txt)

**Comment by flightlevel** [comment]
The server config looks good, but can you try changing `"AllowExternal": true,` from false to true and restart Jackett

Then load Jackett in your browser (make sure address is localhost:9117), then in Chrome press F12 to open developer tools and click on the network tab. Then press CTRL + F5 and post the results, should like this
![image](https://user-images.githubusercontent.com/9430010/43045168-cff5bc82-8df6-11e8-80ea-5d9f710b2a2a.png)

**Comment by tawolude** [comment]
Thanks...It worked
