### ISSUE TITLE
Could not load file or assembly AutoMapper -  All Indexers

### ISSUE THREAD

**Issue by sixtyfeight** [Jackett/Jackett#3415]
Jackett Version 0.8.1162.0 

Exception (rarbg): Could not load file or assembly 'AutoMapper, Version=6.2.2.0, Culture=neutral, PublicKeyToken=' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040): Could not load file or assembly 'AutoMapper, Version=6.2.2.0, Culture=neutral, PublicKeyToken=' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by Kheiden** [comment]
This was fixed for me by updating to 0.9.6.0

**Comment by Gingey231** [comment]
Cheers @Kheiden didn't even notice a new version! Seems to be fixed for me now!

**Comment by sixtyfeight** [comment]
I tried checking for updates through the web interface and it said there weren’t any. Will do the update when I’m home. Thanks folks.

**Comment by Gingey231** [comment]
@sixtyfeight Yeah my check for updates was broken too. You'll need to download the latest one from https://github.com/Jackett/Jackett/releases/tag/v0.9.6 - Just make sure to stop your services/application from running first. Mine just installed over the top, and kept all configurations when it came back up 👍
