### ISSUE TITLE
[limetorrents] Exception (limetorrents): Got redirected to another domain. Try changing the indexer URL to https://www.limetorrents.io/.: Parse error (Test)

### ISSUE THREAD

**Issue by majorsl** [Jackett/Jackett#3431]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.9.14.0
**Mono version** (if not using Windows):  5.8.0.108-11

-------------------------------
Looks like they may have done a site makeover and possibly redirecting to a new/different domain.

**Comment by SkYNewZ** [comment]
Hi!

I just have this issue with YggTorrent that change their url today. I fixing this by remove Ygg and re-add it, and I can see the new URL without doing much. You can try, maybe it correct your provider too :wink:

**Comment by flightlevel** [comment]
Should be fixed with the latest version v0.9.16
