### ISSUE TITLE
Web UI doesn't load

### ISSUE THREAD

**Issue by ericralph** [Jackett/Jackett#3435]
I just (attempted) to update from ~0.6 to the most recent release and can't seem to access the Web UI through http://127.0.0.1:9117, I'm told that the site cannot be found. I see the Jackett Tray, Console, and System processes all running in Task Manager. Thoughts?

**Comment by ericralph** [comment]
Windows version is 10.0.17134 Build 17134, CPU is a Core i5 4690K.

**Comment by flightlevel** [comment]
Not much to go on here...

Try it in an incognito window

Uninstall and reinstall

If thats still not working

Stop the service
Start Jackett from the console with `JackettConsole.exe -t -l`
and post the full log file
https://github.com/Jackett/Jackett#troubleshooting

**Comment by Slinkynose** [comment]
FYI, I had this issue and uninstall/reinstall worked.
