### ISSUE TITLE
[yts] An error occurred while sending the request: Error: TrustFailure (One or more errors occurred.) (Config)

### ISSUE THREAD

**Issue by mcjfauser** [Jackett/Jackett#3439]
I'm trying to add yts to Jackett, and keep getting this error.

I've tried going to terminal and running wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin with no luck.

Jackett Version 0.9.14.0

**Comment by flightlevel** [comment]
Works perfectly here
This issue is commonly caused by missing certificates

What OS and CPU?
Mono version
Post the output after running cert-sync as root
Do any other https trackers work?

**Comment by mcjfauser** [comment]
Thank you for the response!

**OS:** unRAID 6.5.0.
**Kernel:** Linux 4.14.26-unRAID x86_64
**OpenSSL:** 1.0.2n
**CPU:** Ryzen 1600

**Output:** root@NAS:~# wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin
-bash: cert-sync: command not found
--2018-07-22 10:24:12--  https://curl.haxx.se/ca/cacert.pem
Resolving curl.haxx.se (curl.haxx.se)... 151.101.82.49, 2a04:4e42:13::561
Connecting to curl.haxx.se (curl.haxx.se)|151.101.82.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 213947 (209K) [application/x-pem-file]
Saving to: ‘STDOUT’

-                                 0%[                                                      ]       0  --.-KB/s    in 0s


Cannot write to ‘-’ (Success).

**Comment by flightlevel** [comment]
That explains it `-bash: cert-sync: command not found`
The certs aren't getting imported because it can't find cert-sync
Never used Unraid, but I'd try something like 
`find / -name cert-sync`
to try and find it and then run the import command from that directory
If you can't find it, it might not have got installed with Mono
https://www.mono-project.com/download/stable/#download-lin
Install ca-certificates-mono package

**Comment by flightlevel** [comment]
Are you running Jackett inside a Docker container?

**Comment by mcjfauser** [comment]
Yeah, binhex-jackett.

**Comment by flightlevel** [comment]
I'd suggest trying linuxserver.io's version, 40 million pulls, so well tested and used
https://www.linuxserver.io/our-images/

**Comment by mcjfauser** [comment]
So I can't update the certificates in the current one?

**Comment by kaso17** [comment]
@mcjfauser Probably you can but it most likely won't survive a restart of the container. I'd suggest you try the linuxserver image, if it's working you can open a bug report with the binhex team.

**Comment by mcjfauser** [comment]
@kaso17 This CA certificate stuff is happening in more than one of my Dockers though.

For example: 

**Headphones:** 

Unable to connect to remote host because of a SSL error. It is likely that your system cannot verify the validityof the certificate. The remote certificate is either self-signed, or the remote server uses SNI. See the wiki for more information on this topic.

**Sonarr:**

Unable to connect to indexer: Torznab error detected: Exception (eztv): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /build/mono/src/mono/external/boringssl/ssl/handshake_client.c:1132
NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: Exception (eztv): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /build/mono/src/mono/external/boringssl/ssl/handshake_client.c:1132
  at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000ca] in <f8c4a2c9e6194b509efc6018724d76df>:0 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in <f8c4a2c9e6194b509efc6018724d76df>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00050] in <f8c4a2c9e6194b509efc6018724d76df>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00024] in <f8c4a2c9e6194b509efc6018724d76df>:0

**Comment by kaso17** [comment]
Either the CA certificates are not correctly initialized in your containers or something is intercepting the corresponding connections.
Please post the output of `curl -vvv https://yts.am/` (from inside of your jackett container)

**Comment by mcjfauser** [comment]
@kaso17 What would the command be to do this inside the Jackett container? Apologies for the basic question.

**Comment by kaso17** [comment]
`docker exec -it <mycontainer> bash` should get you a shell inside the container.

**Comment by mcjfauser** [comment]
This is the result:

[root@8515bb08a7d8 /]# curl -vvv https://yts.am/
*   Trying 101.167.166.53...
* TCP_NODELAY set
* Connected to yts.am (101.167.166.53) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / AES128-SHA
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=AU; ST=Victoria; L=Melbourne; O=Telstra Corporation Limited; OU=Telstra Operations; CN=www.tvicb.com
*  start date: Jun  1 04:54:51 2016 GMT
*  expire date: Jun  1 04:54:48 2019 GMT
*  subjectAltName does not match yts.am
* SSL: no alternative certificate subject name matches target host name 'yts.am'
* stopped the pause stream!
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (51) SSL: no alternative certificate subject name matches target host name 'yts.am'

**Comment by kaso17** [comment]
`subject: C=AU; ST=Victoria; L=Melbourne; O=Telstra Corporation Limited; OU=Telstra Operations; CN=www.tvicb.com`
This is not the correct certificate. Googling this seems to be indicating that it's due to your ISP blocking the connections.
