### ISSUE TITLE
[REQ] Openelec installation

### ISSUE THREAD

**Issue by zorvalth** [Jackett/Jackett#344]
I think it will be nice to be a openelec install-able as an addon for example. Many people are using Openelec with couchpotato and jacket will be great addition.

**Comment by armani316** [comment]
Is there a plan to implement this?

**Comment by kaso17** [comment]
I suggest you request packaging for jackett as a feature request at the openelec project. Not sure how their pkt distribution is working. Jackett has it's own build in update process which might cause trouble with traditional pkt managers.
It shouldn't be very hard to install it manually once and then just use the update manger.

**Comment by armani316** [comment]
@kaso17 @zorvalth I'll close this for now, please feel free to reopen it if you feel it's appropriate.
