### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://ww2.yggtorrent.is/ using form selector form[action$="/user/login"]

### ISSUE THREAD

**Issue by Aerya** [Jackett/Jackett#3442]
Hi, YGG is not working anymore (just saw it today, this might be older...).

Using the LinuxServer Docker build: [DockerHub](https://hub.docker.com/r/linuxserver/jackett/)
**Log**: [here](https://pastebin.com/kYiCh8ZE) 
**Jackett version**:   0.9.14.0 
**Mono version** (if not using Windows):  5.12.0.226

Thanks

-------------------------------

**Comment by flightlevel** [comment]
Should be fixed with the latest version v0.9.16
Also, login to their website via browser and make sure your password hasn't expired
