### ISSUE TITLE
[iptorrents] Your cookie did not work: Your cookie did not work (Config)

### ISSUE THREAD

**Issue by GrayHogan** [Jackett/Jackett#3446]
I am having issues with both IPT and with Torrentday.  I have uninstalled Jackett, logged out of the sites, rebooted, ran jackett as admin, and still no luck.  I know how to get the cookie (to be fair, the f12 method has changed since the screenshot, as it now has the cookie broken down and in a table- but I grabbed the __cfduid=.  

I have tried to put in the UID and Pass.  This only happens with cookie-type indexers as I had no problems with hd-space. 

Any help at all is greatly appreciated.  Thanks!

**Jackett version**:  0.9.16
-------------------------------

Threw my enhanced logs in here
https://pastebin.com/Ar5MGV7p

**Comment by flightlevel** [comment]
Running Chrome 67 here and the wiki looks spot on, its not in a table and there is nothing to join, its just a straight copy paste. Are you sure you are looking in the right place?

Also, both sites have multiple addresses that you can use, please try another 1 or 2 different addresses to be certain. No other reports of this issue and both are very large trackers

**Comment by GrayHogan** [comment]
![cookie shotd](https://user-images.githubusercontent.com/8440010/43054989-2afedebe-8e02-11e8-9838-a167267922eb.png)

As attached, you can see that the cookie listing is off.  So, this must be a setting I somewhere have toggled and don't know where?  I am on Chrome 67 as well.  
Between when I posted this, and when I came back tonight, IPT now asks for a UN and Pass bypassing the cookie issue altogether.  Did that and it seems to work now- but just IPT and not TD. I have attempted to use several site names for TD, and had no luck.  I am convinced that I have a weird gremlin.  

Is there a place where the app info is stored? (looked all around and couldn't find it) I tried - as I mentioned- a fresh install, but it remembered HD space for some reason, and that was after a reboot.

**Comment by flightlevel** [comment]
Uninstalling removes program files but leaves your configuration behind.
Indexer configuration is in `C:\ProgramData\Jackett\Indexers`
You are so close with the cookie, you just need to click on the 'Headers' tab, you are on the 'Cookies' tab
