### ISSUE TITLE
Unable to parse episodes from release name, Animes on BJ-Share

### ISSUE THREAD

**Issue by HyakoV2** [Jackett/Jackett#3457]
Im getting this error for almost 1 month, but the problem it is only on cat Anime. 

**Jackett version**:  0.9.16.0
**Mono version** (if not using Windows):  Mono JIT compiler version 5.8.0.127 (tarball Wed Mar 21 19:21:33 -03 2018)

-------------------------------
Not working only on category Anime.
![image](https://user-images.githubusercontent.com/10909511/43091186-cf7c02dc-8e7f-11e8-954b-304e889f3291.png)

Working on category Series.
![image](https://user-images.githubusercontent.com/10909511/43091433-77d14410-8e80-11e8-82d8-7cafe6ce7c51.png)

**Comment by flightlevel** [comment]
Have you asked Sonarr about this? Its Sonarr that parses the release names. Jackett is a proxy server and simply supplies the name provided by the tracker

**Comment by HyakoV2** [comment]
Im gonna ask there. Thanks!

**Comment by HyakoV2** [comment]
Sup @flightlevel i made the same question there, can you read the answer here: https://github.com/Sonarr/Sonarr/issues/2677

**Comment by flightlevel** [comment]
markus has now provided an answer, its a data issue, Sonarr can parse the name Jackett is providing
