### ISSUE TITLE
[abnormal] Object reference not set to an instance of an object (Config)

### ISSUE THREAD

**Issue by Naokor** [Jackett/Jackett#3460]
Hello,

There is an error message while adding the Abnormal indexer to the list. Everything seems to be config correctly but as soon as you press the "Okay" Button at the bottom this message appears. I can provide more info if needed.

![capture12](https://user-images.githubusercontent.com/26311252/43128494-6bd619bc-8f32-11e8-8be7-dfb7e3ca78f9.JPG)

[log extract abn.txt](https://github.com/Jackett/Jackett/files/2222850/log.extract.abn.txt)

**Jackett version**:  0.9.16.0
**Mono version** (if not using Windows):  Mono JIT compiler version 5.12.0.226

-------------------------------

**Comment by flightlevel** [comment]
@JigSawFr Does it work for you?

**Comment by kaso17** [comment]
It's working fine for me.
From the log: `Votre adresse IP a été bannit.`
