### ISSUE TITLE
Mono 5.12.0.301 seems to be incompatible with Jacket 0.9.14.0

### ISSUE THREAD

**Issue by aassaly** [Jackett/Jackett#3466]
Operating System: CentOS

**Jackett version**:  Jackett 0.9.14.0
**Mono version** (if not using Windows):  5.12.0.301

I get the following errors in the logs when when trying to startup Jackett:

> 07-24 21:21:31 Info Logging enabled. 
07-24 21:21:31 Info Tracing enabled. 
07-24 21:21:31 Info Starting Jackett 0.9.14.0 
07-24 21:21:31 Info Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5) 
07-24 21:21:31 Info OS version: Unix 3.10.0.862 (64bit OS) (64bit process) 
07-24 21:21:31 Info ThreadPool MaxThreads: 800 workerThreads, 200 completionPortThreads 
07-24 21:21:31 Info App config/log directory: /root/.config/Jackett 
07-24 21:21:31 Info issue: \S 
07-24 21:21:31 Info mono version: 5.12.0.301 (tarball Fri Jul 20 15:09:05 UTC 2018) 
07-24 21:21:31 Info TrustedRootCertificates count: 163 
07-24 21:21:31 Error Jackett is running with root privileges. You should run Jackett as an unprivileged user. 
07-24 21:21:31 Info Using HTTP Client: HttpWebClient 
07-24 21:21:32 Info Loading Cardigann definitions from: /root/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /opt/jackett/Definitions 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/1337x.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/2fast4you.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/3dtorrents.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/Bittorrentfiles.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/acidlounge.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/anidex.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/anirena.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/aox.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/arabafenice.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/archetorrent.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/asiandvdclub.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/ast4u.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/audiobooktorrents.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/awesomehd.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/b2s-share.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/backups.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/bigtorrent.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/bithorlo.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/bithumen.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/bitme.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/bitspyder.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/bluebird.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/blutopia.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/bt-scene.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/btbit.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/btdb.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/btnext.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/btworld.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/btxpress.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/carpathians.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/ccfbits.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/chdbits.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/cinemageddon.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/cinematik.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/classix.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/cpabien.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/cztorrent.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/datascene.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/deildu.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/diablotorrent.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/downloadville.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/dragonworldreloaded.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/dreamteam.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/elitehd.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/elittracker.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/empornium.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/eotforum.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/estone.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/ethor.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/ettv.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/extratorrent-ag.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/eztv.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/fanoin.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/femdomcult.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/freedomhd.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/frozenlayer.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/fullmixmusic.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/funkytorrents.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/gay-torrents.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/gaytorrentru.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/gfxnews.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/gfxpeers.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/gigatorrents.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/girotorrent.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/gktorrent.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/gods.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/greekteam.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/hachede.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/hdbits.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/hdbitscom.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/hdchina.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/hdcity.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/hdhome.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/hdme.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/hdsky.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/hdspain.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/hdtorrentsit.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/hon3yhd.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/horriblesubs.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/hyperay.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/icetorrent.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/idope.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/ilcorsaroblu.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/ilcorsaronero.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/iloveclassics.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/inperil.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/insanetracker.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/isohunt2.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/jpopsuki.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/kapaki.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/karagarga.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/kickasstorrent-kathow.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/kickasstorrent.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/kinozal.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/limetorrents.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/linkomanija.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/losslessclub.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/magico.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/magnetdl.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/majomparade.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/manicomioshare.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/megabliz.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/metaltracker.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/mononokebt.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/mteamtp.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/mvgroupforum.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/mvgroupmain.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/myspleen.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/nethd.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/newretro.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/newstudio.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/nexttorrent.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/nnm-club.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/nyaa-pantsu.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/nyaasi.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/nyoo.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/ourbits.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/passionetorrent.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/polishsource.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/ptfiles.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/puntotorrent.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/racing4everyone.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/rgu.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/rodvd.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/rutor.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/scenefz.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/scenereactor.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/sdbits.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/shareisland.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/sharespacedb.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/shellife.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/sktorrent.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/speed-share.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/speedtorrentreloaded.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/sporthd.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/sportscult.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/sukebei-pantsu.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/sukebeinyaasi.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/tasmanit.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/tbplus.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/tenyardtracker.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/theempire.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/thegeeks.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/thehorrorcharnel.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/theoccult.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/thepiratebay.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/theplace.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/theshinning.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/theshow.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/thetorrents.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/thevault.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/tntvillage.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/tokyotosho.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torlock.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torrent-turk.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torrent9.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torrentbd.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torrentccf.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torrentdownloads.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torrenthr.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torrenting.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torrentkim.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torrentland.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torrentlt.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torrentsectorcrew.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torrentseeds.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torrentsmd.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torrentz2.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/torviet.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/totheglory.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/trancetraffic.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/trezzor.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/uhdbits.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/ultimategamerclub.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/unionfansub.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/waffles.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/worldofp2p.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/worldwidetorrents.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/xbytes2.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/xtremezone.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/yggtorrent.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/yourexotic.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/zamundanet.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/zelkaorg.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/zooqle.yml 
07-24 21:21:32 Info Loading Cardigann definition /opt/jackett/Definitions/ztracker.yml 
07-24 21:21:32 Info Adding aggregate indexer 
07-24 21:21:32 Info Starting web server at http://*:9117/ 
07-24 21:21:32 Error Top level exception System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Method has zero rva
  at System.Web.Http.HttpConfiguration.DefaultFormatters (System.Web.Http.HttpConfiguration config) [0x00000] in <69abafc3d8434ab584330d77cc8d6da3>:0 
  at System.Web.Http.HttpConfiguration..ctor (System.Web.Http.HttpRouteCollection routes) [0x00059] in <69abafc3d8434ab584330d77cc8d6da3>:0 
  at System.Web.Http.HttpConfiguration..ctor () [0x0000b] in <69abafc3d8434ab584330d77cc8d6da3>:0 
  at Jackett.Startup.Configuration (Owin.IAppBuilder appBuilder) [0x00001] in <451e29735471472a922e85f1ea4f9451>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in /builddir/build/BUILD/mono-5.12.0.301/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 
   --- End of inner exception stack trace ---
  at Jackett.Services.ServerService.Start () [0x00128] in <451e29735471472a922e85f1ea4f9451>:0 
  at Jackett.Console.Program+<>c.<Main>b__0_1 (Jackett.Common.Models.Config.ConsoleOptions options) [0x0045d] in <813977f0ea994a6b84d0556506679015>:0

**Comment by marcelpaulo** [comment]
Why don't you upgrade Jackett to its latest version, **0.9.16.0** ? I'm running Jackett 0.9.16.0 with mono 5.12.0.301 on Xubuntu 18.04, and I don't get the error you got.

**Comment by flightlevel** [comment]
Working nicely here as well on .301
I'd try deleting your Jackett binaries and copying over a fresh copy

If that doesn't work
please run `mono --debug JackettConsole.exe -t -l`
and post the output

**Comment by aassaly** [comment]
Thank you for the advice/help resolving my issue.

Updating to the latest release has resolved the issue.

The problem for my environment is that my OS seems to have updated Mono before Jackett had a chance to get updated. As a result, Jackett failed to startup and auto-update using the latest version of mono.

Any advice on how to prevent this sort of failure from occurring in the future? Are manual updates for the OS the way to go?

**Comment by Dnkhatri** [comment]
Jackett developers are planning and trialing to leave mono in favour of net core. So jackett install and update will have the required runtime in the package.
