### ISSUE TITLE
[torrentday] Your cookie did not work: Parse error (Config)

### ISSUE THREAD

**Issue by Zeultuk** [Jackett/Jackett#3469]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.9.16.0
**Mono version** (if not using Windows):  

-------------------------------

I have tried a few of the working TD domains and tried getting cookies from Chrome/Firefox using the latest screenshots. 
I noticed that in the screenshot the cookie is in the following order UID, PASS then __CFDUID however chrome and firefox displays them __CFDUID, UID, PASS.

Tried flipping them around but still no joy.

**Comment by Fenanix** [comment]
Same problem here, tried to change the order, but still nothing.

**Comment by flightlevel** [comment]
Working here as well
@Zeultuk 
Try using the torrentday.com domain in your browser and in Jackett

**Comment by Zeultuk** [comment]
the torrentday.com domain is blocked by my ISP

**Comment by kaso17** [comment]
https://www.torrentday.it/ is used by default in jackett. If that is blocked to you'll have to use a proxy/VPN.

**Comment by Zeultuk** [comment]
https://www.torrentday.it/ works fine as does the other mirrors but the cookie doesn't work as mentioned in the original post.

**Comment by Zeultuk** [comment]
Managed to get this working using Cardigann so i dont think is a torrentday issue, if you need any logs from jackett please let me know. Happy to help to try and get this working.

**Comment by brentlintner** [comment]
FWIW: This definitely worked for me (not ISP blocked) using `https://www.torrentday.com/` and `__cfduid=xxxx;pass=xxxx;uid=xxxx;` for the cookie string. @Zeultuk did you try using lower case cookie names? Long shot but could be it. :-/

**Comment by whitesnakeftw** [comment]
It's important to pay attention to the "www." part. I took my cookie from torrentday.it but on Jackett the selected site link was **www**<b>\.</b>torrentday.it so just removing that "www." part did the trick for me.

**Comment by sideoutdude16** [comment]
I had the same issue, it apparently that you need the WHOLE cookie header (not just the cfduid key) 

You would need this info.

pass=xxxx; uid=xxxx; pass=xxxxx; uid=xxxx; PHPSESSID=xxxxx; old-pass=; __cfduid=xxxxx
