### ISSUE TITLE
Cannot download any torrents from indexers using iTorrents.org (LimeTorrents, 1337x)

### ISSUE THREAD

**Issue by marcelpaulo** [Jackett/Jackett#3475]
**Jackett version**:  0.9.23
**Mono version** (if not using Windows):  5.12.0.301
**Platform**:  Linux (Xubuntu 18.04)

Cannot download any torrents from LimeTorrents. Jackett takes a long time, in the order of minutes, to time out, and then returns HTTP error 404. Reloading Jackett and/or repeating the operation have no effect. As it is, LimeTorrents cannot be used at all.

The same torrents can be downloaded directly from https://www.limetorrents.io/, after Cloudfare checks the browser, which takes under one minute.

When this was discussed in #3264, it was possible to download torrents after Cloudfare checked the browser, but it has stopped working altogether around this week.

-------------------------------

Here's the [enhanced log](https://paste.ee/p/5GESp) after doing a manual search for `screwed 2011` on LimeTorrents and trying to download the first torrent in the list.

**Comment by marcelpaulo** [comment]
I've just noticed that the issue also happens with 1337x, so handling iTorrents.org seems to be the underlying cause.

**Comment by kaso17** [comment]
itorrents added cloudflare protection awhile ago causing these failed downloads. After several attempts it should work.
Changing 1337x/lime torrents to magnet download links should fix the problem too (assuming your client can handle it).

**Comment by marcelpaulo** [comment]
> Changing 1337x/lime torrents to magnet download links should fix the problem too (assuming your client can handle it)

I did that, it works, thanks for the tip !

DuckieTV can't handle it, but then I disabled 1337x/LimeTorrents via Jackett.
