### ISSUE TITLE
Horrible Subs now requires https

### ISSUE THREAD

**Issue by dkids** [Jackett/Jackett#3481]
Jackett Version 0.9.16.0 
Mono JIT compiler version 5.10.1.47 (2017-12/8eb8f7d5e74 Fri Apr 13 20:18:12 EDT 2018)

I can change it from http to https when editing but it doesn't save.   If I can't edit the URL, that's fine, but it seems like it would be better UI to not show it as editable.

Thanks!

-------------------------------
![screenshot_2018-07-27 jackett](https://user-images.githubusercontent.com/30055574/43328732-aa733c98-9173-11e8-9d11-2953383f71e7.png)

**Comment by kaso17** [comment]
dupe #3318
