### ISSUE TITLE
feature: choose data folder

### ISSUE THREAD

**Issue by franner** [Jackett/Jackett#349]
First of all thanks for a great program.

I have tried looking at the command line options (-h) and couldn't see a way to make jackett use a certain folder for its data from the command line.
Other projects like couchpotato, sonarr, sickbeard have some option like "-data" "-datadir" to make the program save to this custom directiory. I would like to request this feature as I think it is great if you could choose some custom folder to save all data into.

Thanks again and i hope you might consider this, if it aint a great trouble implementing this.

**Comment by flightlevel** [comment]
This is included in the latest release. Run JackettConsole.exe --help for more info.
