### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /spksrc/spk/mono/work-armada38x-6.1/mono-5.8.0.108/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by scubabas** [Jackett/Jackett#3496]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:   Jackett Version 0.8.490.0
**Mono version** (if not using Windows):  5.0.8.108

Running on a Synology NAS

-------------------------------

All trackers like piratebay and rarbg are giving the following message 

Exception (thepiratebay): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /spksrc/spk/mono/work-armada38x-6.1/mono-5.8.0.108/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request
[serverlog.txt](https://github.com/Jackett/Jackett/files/2242570/serverlog.txt)

Re-importing the certificates didn't fix the problem
[jackett.log](https://github.com/Jackett/Jackett/files/2242706/jackett.log)

**Comment by flightlevel** [comment]
@cerulliulliulli Did you ever get Jackett going, same Armada38x https://github.com/Jackett/Jackett/issues/3403

@scubabas 
Find the folder on you NAS that contains `cert-sync` and from that directory run `cert-sync /etc/ssl/certs/ca-certificates.crt` and post the output

**Comment by scubabas** [comment]
![github](https://user-images.githubusercontent.com/35252239/43459410-aecad5b4-94cd-11e8-9908-5c22c9ae8f2d.jpg)

See attached image

**Comment by kaso17** [comment]
please post the output of
`curl -vvv https://thepiratebay.org/` and/or `openssl s_client -connect thepiratebay.org:443`

**Comment by scubabas** [comment]
![first](https://user-images.githubusercontent.com/35252239/43462241-dc34ff5e-94d5-11e8-8882-2861ed3f2a53.jpg)
![second](https://user-images.githubusercontent.com/35252239/43462245-dfed371a-94d5-11e8-9365-22d6d1905af7.jpg)

**Comment by kaso17** [comment]
your ISP is intercepting/blocking the connection
