### ISSUE TITLE
[ettv] Exception (ettv): Could not load file or assembly 'AutoMapper, Version=6.2.2.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040): Could not load file or assembly 'AutoMapper, Version=6.2.2.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) (Test)

### ISSUE THREAD

**Issue by Eds1989** [Jackett/Jackett#3499]
Recently just started getting the errors mentioned in the title of this issue.
Seems to be occurring on all indexers configured.

Do I need to reinstall, or is there anything I can do to resolve this?

**0.8.1162.0**:  

-------------------------------

**Comment by flightlevel** [comment]
For anyone who finds this issue via search. Fix is to uninstall and the reinstall Jackett via the Windows installer
