### ISSUE TITLE
BeyondHD Tracker is not working

### ISSUE THREAD

**Issue by slamanna212** [Jackett/Jackett#35]
I have entered all the cookie information but its still saying invalid cookie header

**Comment by slamanna212** [comment]
Also spoke with support for BeyondHD and they verified im entering the info correctly

**Comment by flightlevel** [comment]
@slamanna212 Implemented ReCaptcha to save you having to find the cookie. Remove Beyond from Jackett, update to the latest release https://github.com/Jackett/Jackett/releases/tag/v0.6.45 and then add BeyondHD back in Jackett

**Comment by slamanna212** [comment]
I got the update and installed it, thank you. It did not work for me still, followed the instructions given, i have the cookie info but its not taking it

**Comment by slamanna212** [comment]
Cookie I used: session_id=XXX; PHPSESSID=xxx; ipsconnect_xxxxxx=1; coppa=0; session_id=xxxxxx; uid=xxxxx; pass=xxxxxxx; hashv=xxxxxx

All data replaced with x, except the coppa that was already 0

**Comment by flightlevel** [comment]
![untitled5](https://cloud.githubusercontent.com/assets/9430010/11057084/5a674da0-87dc-11e5-9ce6-8c7d1ec7948c.png)

Are you setting up BeyondHD on the computer that hosts Jackett. ie when setting up is the ip address in your web browser http://127.0.0.1:9117/Admin/Dashboard or http://localhost:9117/Admin/Dashboard ?
You shouldn't have to touch the cookie now, just click the tick box 'I'm not a robot'

**Comment by Sek0n** [comment]
Cookie way still doesn't seem to work, as @slamanna212 said. Not on a local computer, so can't do the captcha way easily.

Will see about tunneling in later if I can't get the cookie way to work soon. Thanks for working on it. :)

**Comment by flightlevel** [comment]
I wonder if the cookie is linked to your browser. The cookie from firefox doesn't work for me either. 
But If I setup Jackett on my home computer, copy the cookie that Jackett saves C:\ProgramData\Jackett\Indexers -> open beyond file in notepad and then copy and paste that cookie across to my seedbox it does work

**Comment by flightlevel** [comment]
Just looked, copy the cookie from chrome and then add a semicolon after the last value (just like the others have)

**Comment by Sek0n** [comment]
Nope, that didn't work for me either. I even tried installing it on my pc here, then copying it from the beyondhd json file like you said, and that didn't even work. =/

Getting "Configuration failed: Your cookie did not work: Your cookie did not work" for anything I put in.

**Comment by Sek0n** [comment]
This is what the log is spitting out btw:

```
 Error Exception in Configure System.Exception: Your cookie did not work: Your cookie did not work
  at Jackett.Indexers.BeyondHD+<ApplyConfiguration>c__async1.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter`1[Jackett.Models.IndexerConfigurationStatus].GetResult () [0x00000] in <filename unknown>:0
  at Jackett.Controllers.AdminController+<Configure>c__async4.MoveNext () [0x00000] in <filename unknown>:0
```

**Comment by flightlevel** [comment]
I see what you mean.
It looks like the cookie may have something to do with IP address?
If I get the cookie from chrome on the same PC and then copy & paste it works fine with Jackett on that PC..
If I try copying from one connection to the other, the cookie won't work.
No idea how Jackett can get around that.

**Comment by Sek0n** [comment]
Yea, no idea. Thinking the only way will be using ssh tunneling to set it up.

**Comment by Sek0n** [comment]
Just updating to say that setting it up through a tunnel works fine. (Not that there would be a reason it wouldnt)

Slight inconvenience, but at least it's possible. :)

**Comment by slamanna212** [comment]
Ok, i will set it up via a tunnel, i was doing it remotely. Sek0n, what settings did you use for the tunnel?

**Comment by slamanna212** [comment]
Actually , nevermind, i got it! Once i opened the tunnel it was super easy to setup!

**Comment by flightlevel** [comment]
Looks like the cookie is related to the IP address, don't think we can do much more.
