### ISSUE TITLE
SceneFZ tracker error

### ISSUE THREAD

**Issue by skylandr** [Jackett/Jackett#350]
Hi,

When i add this tracker i get this error: Test failed for SceneFZ: Found no results while trying to browse this tracker
This also appears when i test the tracker. Here is the full debug log: http://pastebin.com/70RauWjD

**Comment by kaso17** [comment]
@skylandr  Is this still a problem?

**Comment by kaso17** [comment]
please send an invite to kaso1717 -at- gmail.com to fix this.
