### ISSUE TITLE
[thepiratebay] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Eds1989** [Jackett/Jackett#3500]
I've always struggled with TPB as an indexer, and am now getting the above message when testing.

I am running latest Jackett version, and have removed and re-added TPB as an indexer, with no change.

**0.9.41.0**:  

-------------------------------

Here is log entry for the test:

System.Exception: Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.<TestIndexer>d__18.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Server.Controllers.IndexerApiController.<Test>d__15.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.<Execute>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Server.Middleware.CustomExceptionHandler.<Invoke>d__3.MoveNext()
--

**Comment by kaso17** [comment]
Make sure it's not blocked by your ISP
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by garfield69** [comment]
I've taken a look at the log you provided, and I can see the problem, which is that you are not using the official TPB site https://thepiratebay.org , but one of the many unofficial proxy site, in this case  https://piratebays.be .

the problem is that the proxy you are using is not a true mirror, in that the HTML that the proxy is generating is not identical to the official TPB site.
this in turn means that the jackett indexer for TPB cannot find one of the required lnks
`System.Exception: Error while parsing field=download, selector=td:nth-child(2) a[title^="Download"], value=<null>: Selector "td:nth-child(2) a[title^="Download"]" didn't match <tr class="alt"> 		<td class="vertTh">`
hence your *no results* issue.

since you are using a VPN, you should be able to use the official TPB site, so access your jackett dashboard, edit your TPB indexer config and change the site link to `https://thepiratebay.org/` .

**Comment by Eds1989** [comment]
Thanks.
I was using a proxy site as the official URL never seems to be online so doesn't work anyway lol.

I've changed it and still get an error, but now a 503.
I'll leave it configured to see if it ever works.

**Comment by garfield69** [comment]
interesting. i can access TPB currently, although it only recently came back up after a couple days downtime. perhaps the cloudflare provider in your region has not updated its servers yet...

**Comment by Eds1989** [comment]
Even before I started using Jackett, I was having to use proxies, as nine times out of ten the main URL was down.

I do get a cached cloudflare page, so perhaps you are right regarding my regions servers not yet updatin. I will just monitor and see how it goes.

**Comment by Eds1989** [comment]
Think it's a UK wide thing. Changed my VPN location to another country, and no longer get a CloudFlare error.
