### ISSUE TITLE
[cpasbien] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by ladenise** [Jackett/Jackett#3503]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  Jackett Version 0.8.1123.0
**Mono version** (if not using Windows): 4.2.3.4 
On a Quickbox.io server.
-------------------------------
After adding cpasbien indexer and clicking to the test button, I get the following error:
Exception : Got redirected to another domain. Try changing the indexer URL to http://www.cpasbien.io/

I changed the URL as asked and tried again without success getting:
An error occured while testing this indexer
Found no results while trying to browse this tracker.

**Comment by kaso17** [comment]
your jackett version is very old. update it. You'll have to update mono too.
