### ISSUE TITLE
[il corsaro blu] some error on script

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#3504]
Due to recent change there's some error on the script
Link to release don't works
download of torrent don't works

This's just a reminder to fix those error, when I find some time, I'll correct it

Btw there's also a problem with the release itself, sometimes S01E01 sometimes 1x01 and even S01 E01!!!

**Comment by kaso17** [comment]
I believe this has been fixed via #3532

**Comment by Jorman** [comment]
I've to ckeck if now works
