### ISSUE TITLE
[REQ]New tracker kinozal.tv

### ISSUE THREAD

**Issue by Mavrag** [Jackett/Jackett#351]
I'm not sure how all this is done. but could you possibly look in to it . there are no Russian trackers for sonarr or sickbeard , well at least i couldn't find any. www.kinozal.tv

**Comment by kaso17** [comment]
is this a public tracker?

**Comment by Mavrag** [comment]
yeah , sign up here : http://kinozal.tv/signup.php

**Comment by RoloSoze** [comment]
@Mavrag Unfortunately, Jackett is not meant to support public trackers. What you can do instead is request a definition file for kinozal.tv to be created for Cardigann:
https://github.com/cardigann/cardigann/issues

And then once it's been created, copy that file (.yml) into Jackett's Definitions directory. That should get Jackett to identify kinozal.tv as an indexer :)

**Comment by Mavrag** [comment]
hold on , by public i meant its that anyone can register without  an invite . but you have to register to download anything and you gotta maintain a ratio .. so i think its just right for jackett

 here are the categories 

1001: All Tv Shows
1002: All Movies
1003: All Cartoons/Anime 
1004: All Music
1006: Shows,Concerts,sports

**Comment by Mavrag** [comment]
1001: All Tv Shows
1002: All Movies
1003: All Cartoons/Anime
1004: All Music
1006: Shows,Concerts,sports
45: Russian Series
46: Tv Series
6:  Movies - Action / army
15: Movies - Thriller / Detective
17: Movies - Drama 
35: Movies - Melodrama
39: Movies - Indian
13: Movies - Fiction
14: Movies - Fantasy
24: Movies - Horror / Mystery
11: Movies - Adventure
10: Movies - Russian Movies
9:  Movies - Historical
47: Movies - Asian
18: Movies - Documentaries
37: Movies - Sport
12: Movies - Kids / Family
7: Movies - Classic
48: Movies - Concerts
49: Movies - Shows / Tv Shows
50: Movies - Tv Show Mir
38: Movies - Theatre,Opera,Ballet
16: Movies - Erotica
21: Cartoons
22: Cartoons - Russian
20: Cartoons - Anime
3: Music
4: Music - Russian
5: Music - Collections
42: Music - Classical
2: Other - AudioBooks
1: Other - Music Video's
23: Other - Games
32: Other - Programms
40: Other - Design / Graphic
41: Other - Library

**Comment by RoloSoze** [comment]
@Mavrag As of a few days ago, Jackett supports semi-private & public trackers (again), so this one should now be OK if a developer volunteers to add support :)

**Comment by garfield69** [comment]
I have nearly completed the Jackett Definition for the kinozal.tv site, jwith only the uploadvolumefactor: and downloadvolumefactor  left to code.
But here is the snag. I'm not fluent in Russian, and the Google Translator is not making things too clear.
Can a user of this site who is fluent in Russian (or knows enough about the rules on this site) explain the download/upload rules to me please?
I see that searches yield either gold links or plain ones, so I am assuming that gold are freeleech? 
[edit] there may also be silver?

**Comment by ffuubarbuzz** [comment]
@garfield69 you are correct, from info [here](http://forum.kinozal.tv/showthread.php?t=63820) my translation:
golden - download traffic is not counted, upload traffic is counted fully.
silver - download traffic is counted for 50%, upload traffic is counted fully.
Thank you for picking it up!

**Comment by Mavrag** [comment]
thanks for doing this . Btw there are hints in the the title of the torrents that says what translations the video's have 
ДБ=Dubbed,ПМ=Professional many voiced, ПД=Proffesional Dual Voiced, АП=Original from the author

not sure if that will be of any use

**Comment by D88M3R** [comment]
Hello, sorry to bump this but this forum is very confusing, where are the topics? Anyway, how can i download from kinozal.tv? There are no links and it does not let me register either because it says the captcha is wrong even though is not, what can i do? Thank you

**Comment by garfield69** [comment]
- https://kinozal.tv/ > cloudflare Connection timed out Error code 522
- https://kinozal.guru/ > online

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://kinozal.tv/ > cloudflare Connection timed out Error code 522
https://kinozal.guru/ > online

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://kinozal.tv/ > cloudflare Connection timed out Error code 522
https://kinozal.guru/ > online

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://kinozal.tv/ > DNS Lookup Error
https://kinozal.guru/ > OK

**Comment by garfield69** [comment]
online with new tld

**Comment by ineednewpajamas** [comment]
Should the new tld have also been applied to https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/kinozal-magnet.yml?

**Comment by garfield69** [comment]
yes, I forgot ;-(
 I'll fix it thanks.
