### ISSUE TITLE
Jackett Crashing 

### ISSUE THREAD

**Issue by djbears32** [Jackett/Jackett#3513]
My issue is exactly like what zero77 had (see below link)not sure what is causing it i have tried a reinstall, and a fresh install. I will attach the log files but i dont believe that will show anything, when it crashes it doesnt end up taking any logs of anything or say why it crashed (unless im looking at the wrong logs). Also i have noticed that Jacket is make multiple copies of the same log file not sure whats causing it will attach a screenshot to show. Maybe it is supposed to be like that but thats why you all are here. Thank in advance for your help!

[https://github.com/Jackett/Jackett/issues/2455](url)

[log.txt](https://github.com/Jackett/Jackett/files/2255494/log.txt)
[ServiceLog.txt](https://github.com/Jackett/Jackett/files/2255495/ServiceLog.txt)
[TrayLog.txt](https://github.com/Jackett/Jackett/files/2255496/TrayLog.txt)
[updater.txt](https://github.com/Jackett/Jackett/files/2255497/updater.txt)

![jackett](https://user-images.githubusercontent.com/42049424/43616790-6060e13c-968c-11e8-88fb-f73a50f53491.PNG)

**Jackett version*0.9.29.0*: Windows 10 
**Mono version** (if not using Windows):  

-------------------------------

**Comment by djbears32** [comment]
Alrigaht gave that a shot well see i started the jackett tray.exe with cmd did you want me to start jackett console with that as well?

**Comment by flightlevel** [comment]
Go into Windows services and stop the Jackett Service
Close the tray icon if its still open
Kill any Jackett processes from task manager
Delete your Jackett logs to make it easier
Open command prompt
cd in the directory that has Jackett application files, likely `C:\ProgramData\Jackett`
run `JackettConsole.exe -t -l`
Perform searches in Jackett or whatever to make it crash
Then grab the log file, it should have more detail in that way

**Comment by djbears32** [comment]
[log.txt.20180804.00534.txt](https://github.com/Jackett/Jackett/files/2259677/log.txt.20180804.00534.txt)
[log.txt.20180804.00535.txt](https://github.com/Jackett/Jackett/files/2259678/log.txt.20180804.00535.txt)
[log.txt.20180804.00536.txt](https://github.com/Jackett/Jackett/files/2259679/log.txt.20180804.00536.txt)
[updater.txt](https://github.com/Jackett/Jackett/files/2259680/updater.txt)
[log.txt](https://github.com/Jackett/Jackett/files/2259681/log.txt)
[log.txt.20180804.00532.txt](https://github.com/Jackett/Jackett/files/2259682/log.txt.20180804.00532.txt)
[log.txt.20180804.00533.txt](https://github.com/Jackett/Jackett/files/2259683/log.txt.20180804.00533.txt)

 Alright did all of the above please see logs it still seems things are messing up, I have attached the logs below should be of some help now.

**Comment by flightlevel** [comment]
You are getting permission errors in the updater.txt
` Error System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\Jackett\AngleSharp.dll' is denied.`
Please make a copy of the `C:\ProgramData\Jackett` folder
Uninstall Jackett using Windows Add/Remove programs
Delete the `C:\ProgramData\Jackett` folder
Install Jackett using the Windows installer (please use the latest pre-release v0.10.12
Stop the Jackett service and tray icon
From your backup folder in step 1 -> copy the serverConfig.json file, Indexers folder and DataProtection folder to `C:\ProgramData\Jackett` and choose to overwrite the existing files
Start the Jackett service

Also, when you say Jackett is crashing without anything going into the logs, what message are you getting in your web browser?

**Comment by djbears32** [comment]
I have tried the fresh uninstall and reinstall and got the same error but will try this again being as your the only person helping. and the Web GUI is non responsive if i run jacket the normal way, when i run it using JackettConsole.exe -t -l it stays up but the indexers start failing and i have to restart to get them to work again. Will post the solution to the troubleshooting step shortly.

**Comment by flightlevel** [comment]
Latest version is here https://github.com/Jackett/Jackett/releases/tag/v0.10.12

Try installing using the Windows Installer and install it as a Windows service and run it as Windows service
