### ISSUE TITLE
SSL offloading don't work.

### ISSUE THREAD

**Issue by Celedhrim** [Jackett/Jackett#3517]
**Jackett version**:  0.10.1
**Mono version** (if not using Windows):  5.8.0.127-0xamarin5+debian9b1

-------------------------------

Since 0.10.1 , ssl offload don't work , jackett try to redirect to http.

Maybe don't manage X-Forwarded-Proto header or something like that.

Rollback to 0.9.41 => work like a charm.

**Comment by flightlevel** [comment]
v0.10.1 is using a completely new web server
Which reverse proxy are you using and what is the setup
Can you compare to the wiki https://github.com/Jackett/Jackett/wiki/Reverse-Proxy

**Comment by Celedhrim** [comment]
I try to give you more detail this weekend.

But it's a little bit complex :)

nginx offload => varnish => nginx http => apache http :D

**Comment by kaso17** [comment]
Most likely the X-Forwarded-Proto header is getting lost/not set.

**Comment by Celedhrim** [comment]
Not here 

0.9 , works as expected , upgrade to 0.10 , don't work , rollback to 9;0 , work again 

nothing else than jacket version change.

Maybe the new jackett webserver don't handle X-Forwarded-Proto header ?

**Comment by Celedhrim** [comment]
I have just make a simple test : 

* I stop jackett
* I create a directory an put a simple index.php in it 

```php
<?php
foreach (getallheaders() as $name => $value) {
            echo "$name: $value</br>";
}
?>
```

* I start a php server on jackett port 
```
$ php -S localhost:9117
```

* then I call jackett url as usual :

```
Host: localhost:9117
X-Real-IP: X.X.X.X
X-Forwarded-Proto: https
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://xxxx.xxx.org/
Upgrade-Insecure-Requests: 1
X-Forwarded-For: x.x.x.x, 127.0.0.1, X.X.X.X
X-Varnish: 193208
X-Forwarded-Host: xxxx.xxxx.org
X-Forwarded-Server: xxx.xxxx.org
Connection: Keep-Alive
```

**Comment by kaso17** [comment]
ok can reproduce this via
```bash
curl -vvv 'http://localhost:9117/UI/Dashboard' \
 -H 'Host: localhost:9117' \
 -H 'X-Real-IP: X.X.X.X' \
 -H 'X-Forwarded-Proto: https' \
 -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0' \
 -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
 -H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3' \
 -H 'Accept-Encoding: gzip, deflate, br' \
 -H 'Referer: https://xxxx.xxx.org/' \
 -H 'Upgrade-Insecure-Requests: 1' \
 -H 'X-Forwarded-For: x.x.x.x, 127.0.0.1, X.X.X.X' \
 -H 'X-Varnish: 193208' \
 -H 'X-Forwarded-Host: xxxx.xxxx.org' \
 -H 'X-Forwarded-Server: xxx.xxxx.org' \
 -H 'Connection: Keep-Alive'
```

Seems to be only a problem if you're not logged in.
Will have a look at this.

**Comment by flightlevel** [comment]
Sorry @kaso17 bit over my head this one

I tried to use as much out of the box asp.net core functionality as possible before going to custom stuff

If there was a problem my guess would be authentication.

The reverse proxy stuff seems pretty straight forward in terms of configuration  https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1 and Microsoft's recommendation is to put it behind a reverse proxy.

To use out of the box authentication I had to turn on authentication for everyone, regardless of whether you set a password in Jackett or not. Currently, even if you don't have a password, you get redirected to `/UI/Login` and once you hit that, it automatically authenticates you knowing that you don't need to enter a password. In `UIController` the `Dashboard()` doesn't allow anonymous whereas 'Login()' does. In hindsight maybe it would have been better to go down the custom authentication route???
Can curl handle redirects and holding the cookie?
How come this only effects @Celedhrim other reverse proxy users seem to be okay?

**Comment by kaso17** [comment]
Not sure if others didn't upgrade to the pre release yet or they don't use https/password authentication.
But I can reproduce the ignored base path by simply enabling password authentication (and doing a relogin).

**Comment by flightlevel** [comment]
@kaso17 I'm not seeing this behaviour, could it be a cached redirect?
If you set a new basepath, open incognito windows -> dev tools -> disable cache, I see all requests going with a /basepath while logging in with a password

Off topic:
Do you think we are ready for a general release?
We've got this issue outstanding, but it looks like only effecting 1 user, gone through all recent issues and looks pretty good for the pre-release(9000 Mono downloads, 33,000 Windows downloads). Some of these 0.1% cases aren't going to come out until we get to all users

**Comment by arkpoah** [comment]
Same issue for me, ssl is not working anymore.

My configuration is a nginx vhost ssl only which serve jackett with /jackett uri.
When I call it I get a 302 redirection to http that I don't have in 0.9.x releases.

**Comment by flightlevel** [comment]
@arkpoah can you provide your nginx configuration

Also, can you please try the suggested setup in the Wiki and in the readme (they are slightly different) and see if that makes a difference

https://github.com/Jackett/Jackett/wiki/Reverse-Proxy

https://github.com/Jackett/Jackett#running-jackett-behind-a-reverse-proxy

**Comment by arkpoah** [comment]
I added some missing headers from wiki but it is not better :

        location /jackett/ {
                auth_request /auth-admin;  # organizr auth
                proxy_pass http://127.0.0.1:9117;
                add_header X-Frame-Options "SAMEORIGIN";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_http_version 1.1;
                proxy_set_header   Upgrade $http_upgrade;
                proxy_set_header   Connection keep-alive;
                proxy_cache_bypass $http_upgrade;
        }

When I call https://organizr.domain.tld/jackett/
I get a http redirect to jackett login : http://organizr.domain.tld/jackett/UI/Login?ReturnUrl=%2Fjackett%2FUI%2FDashboard

**Comment by kaso17** [comment]
@flightlevel forget my basepath issues, the basepath engine is intelligent enough not to include it in the redirect if it's not part of the original request. So not a problem.

But see this most basic curl example on linux (jackett  0.10.36, mono 5.14.0.173):
```
# curl -vvv "http://localhost:9117/jackett/UI/Dashboard" -H "X-Forwarded-Proto: https"
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9117 (#0)
> GET /jackett/UI/Dashboard HTTP/1.1
> Host: localhost:9117
> User-Agent: curl/7.47.0
> Accept: */*
> X-Forwarded-Proto: https
>
< HTTP/1.1 302 Found
< Date: Sun, 12 Aug 2018 09:46:18 GMT
< Server: Kestrel
< Content-Length: 0
< Location: http://localhost:9117/jackett/UI/Login?ReturnUrl=%2Fjackett%2FUI%2FDashboard
<
* Connection #0 to host localhost left intact
```
Redirected to http

And the same on windows:
```
>curl.exe -vvv "http://localhost:9117/jackett/UI/Dashboard" -H "X-Forwarded-Proto: https"
*   Trying ::1...
* TCP_NODELAY set
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9117 (#0)
> GET /jackett/UI/Dashboard HTTP/1.1
> Host: localhost:9117
> User-Agent: curl/7.61.0
> Accept: */*
> X-Forwarded-Proto: https
>
< HTTP/1.1 302 Found
< Date: Sun, 12 Aug 2018 09:36:28 GMT
< Server: Kestrel
< Content-Length: 0
< Location: https://localhost:9117/jackett/UI/Login?ReturnUrl=%2Fjackett%2FUI%2FDashboard
<
* Connection #0 to host localhost left intact
```

**Comment by Celedhrim** [comment]
Yes that's it , the issue is that 0.10.X don't care X-Forwarded-Proto.

It's concern everybody who proxy jackett with ssl offload

**Comment by kaso17** [comment]
@Celedhrim can you please try v0.10.37
With my simply curl test it's fixed.

**Comment by arkpoah** [comment]
v0.10.37 works for me, thanks

**Comment by Celedhrim** [comment]
Hello , better read the wiki and added 

ProxyPreserveHost On

In apache proxy pass , It 's now ok ( but I don't need it before )

I think it can be close

**Comment by flightlevel** [comment]
Nice work @kaso17 

@Celedhrim 
We've got two slightly different versions, 1 in the wiki https://github.com/Jackett/Jackett/wiki/Reverse-Proxy and one on the readme https://github.com/Jackett/Jackett#running-jackett-behind-a-reverse-proxy
Just to confirm so I can update the documentation, you had to ADD `ProxyPreserveHost On` and that made it work?

**Comment by Celedhrim** [comment]
Yes ! that's it !

**Comment by kaso17** [comment]
@Celedhrim setting the Host header correctly was needed before too (e.g. for download links to work).
Can you please try v0.10.47 without ProxyPreserveHost? It should use X-Forwarded-Host now.

**Comment by Celedhrim** [comment]
@kaso17 , you are right , direct download link never work for me but I've never used it , so I've never look at it.

I've just tried 0.10.47 without ProxyPreserveHost and I'm style redirect to localhost:9117.

**Comment by Celedhrim** [comment]
@kaso17 : Just test release 0.10.49.

Work prefect !! with or without ProxyPreserveHost
