### ISSUE TITLE
[yggtorrent] Login failed

### ISSUE THREAD

**Issue by Familure** [Jackett/Jackett#3519]
An error occured while updating this indexer
Login failed: No form found on https://ww3.yggtorrent.is/ using form selector form[action$="/user/login"]
Jackett Version 0.9.41.0
Docker linuxserver/jackett

-------------------------------
Jackett worked normally with https://yggtorrent.is/, but he does not work with https://ww3.yggtorrent.is/, https://ww2.yggtorrent.is/

**Comment by flightlevel** [comment]
It should work once you update the url in settings to `https://ww3.yggtorrent.is/` for Yggtorrent
Might be worth restarting the container as well

**Comment by tuipo** [comment]
I try but that's doesn't work. I don't know why so np i will find another solution thanks for answer dude 👍

**Comment by Familure** [comment]
Oh, sorry I did not see, 
https://github.com/Jackett/Jackett/pull/3515
I'll wait for the next update :)

**Comment by Familure** [comment]
I have update URL and restart, it works perfectly thanks 👍

**Comment by Tryum** [comment]
It fails on an irregular basis, how to help with catching what's wrond with this tracker ?

**Comment by kaso17** [comment]
@Tryum please provide an enhanced log on a failed login.

**Comment by Tryum** [comment]
I enabled the enhanced logs to catch it next time.
I went to the tracker settings and just hitting "Okay" without changing any settings seems to have solved the issue this time.

**Comment by teimahu** [comment]
Thanks Tryum, I did the same and it works now ...
