### ISSUE TITLE
Failed to update Jackett to latest release

### ISSUE THREAD

**Issue by ShaMana999** [Jackett/Jackett#3533]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.9.29.0
**Mono version** (if not using Windows):  5.8.1.0.r9

-------------------------------

I run all of the above on an asustor machine with limited knowledge in how to operate them beyond the visual interface. Apologies if the issue exists just running out of options to do. Since last Mono update most Jackett indexers stopped working with the following error

*Exception (IndexerName): The authentication or decryption has failed.: An error occurred while sending the request*

And additionally Jackett won't no longer update with a generic error in the log

*Error checking for updates.*

I don't posses sufficient know how on how to update manually

**Comment by kaso17** [comment]
This seems to be an asustor issue with their mono version. See #3489
