### ISSUE TITLE
System.BadImageFormatException: Could not load file or asse mbly 'AutoMapper, Version=7.0.1.0

### ISSUE THREAD

**Issue by goku-son** [Jackett/Jackett#3559]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  v0.10.12.0
**Mono version** (if not using Windows):  

-------------------------------

I just installed the latest version and it actually ran for an hour or so but seems to have crashed when I was deleting an obsolete indexer.  Here is what I see when I try and start in from the command line:

C:\Jackett-0.10.12>JackettConsole.exe -t -l
08-08 22:58:17 Info Starting Jackett v0.10.12.0
08-08 22:58:17 Info Logging enabled.
08-08 22:58:17 Info Tracing enabled.
08-08 22:58:17 Debug Creating web host...
08-08 22:58:17 Debug Content root path is: C:\Jackett-0.10.12\Content
08-08 22:58:17 Debug Autofac container built
08-08 22:58:17 Error System.BadImageFormatException: Could not load file or asse
mbly 'AutoMapper, Version=7.0.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1
005' or one of its dependencies. The module was expected to contain an assembly
manifest.
File name: 'AutoMapper, Version=7.0.1.0, Culture=neutral, PublicKeyToken=be96cd2
c38ef1005'
   at Jackett.Server.Helper.InitAutomapper()
   at Jackett.Server.Helper.Initialize()
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(ISer
viceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\M
icrosoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure lo
gging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fus
ion!EnableLog].
 System.BadImageFormatException: Could not load file or assembly 'AutoMapper, Ve
rsion=7.0.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its d
ependencies. The module was expected to contain an assembly manifest.
File name: 'AutoMapper, Version=7.0.1.0, Culture=neutral, PublicKeyToken=be96cd2
c38ef1005'
   at Jackett.Server.Helper.InitAutomapper()
   at Jackett.Server.Helper.Initialize()
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(ISer
viceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\M
icrosoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure lo
gging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fus
ion!EnableLog].

Unhandled Exception: System.BadImageFormatException: Could not load file or asse
mbly 'AutoMapper, Version=7.0.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1
005' or one of its dependencies. The module was expected to contain an assembly
manifest.
   at Jackett.Server.Helper.InitAutomapper()
   at Jackett.Server.Helper.Initialize()
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(ISer
viceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)

C:\Jackett-0.10.12>

Any ideas what is the problem? If I start my old 0.8.1027 version it starts no problem. I am on Windows 7.

**Comment by flightlevel** [comment]
I gather you just run from the Windows binaries `C:\Jackett-0.10.12` and not using the Windows Installer?
Can you please try re-downloading and copying to a different clean directory, potentially a file is missing or corrupted
Also, in `C:\ProgramData\Jackett` do you have any DLL files?

**Comment by goku-son** [comment]
Thanks for the reply. No DLLs in the directory mentioned. Also, I am using the Windows binaries. I have upgraded to the latest  0.10.117.0 and will monitor to see if the issue recurs.

**Comment by IronTooch** [comment]
For anyone getting here from the Google for a problem with 
```
 Fatal Unable to start Kestrel. System.BadImageFormatException: Could not load file or assembly 'System.Security.Cryptography.X509Certific
ates, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
May  2 07:20:19 casino jackett[1063]: File name: 'System.Security.Cryptography.X509Certificates, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
May  2 07:20:19 casino jackett[1063]:    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
May  2 07:20:19 casino jackett[1063]:    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.ValidateOptions()
May  2 07:20:19 casino jackett[1063]:    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
May  2 07:20:19 casino jackett[1063]: 05-02 07:20:19 Fatal Unable to start Kestrel. System.BadImageFormatException: Could not load file or assembly 'System.Security.Cryptography.X509Certific
ates, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
```

The answer is to make the .config and Jackett path in your user's home directory.
