### ISSUE TITLE
torrent9 doesen't work 

### ISSUE THREAD

**Issue by bibi32** [Jackett/Jackett#3569]
Debian 9.5
Mono : 5.12.0.301 
Jackett :  0.9.41.0
-------------------------------
torrent9 doesen't work

**Comment by bibi32** [comment]
torrents9 works from my last post until yesterday.

**Comment by garfield69** [comment]
To fix this now yourself, access your jackett dashboard, edit your torrent9 indexer config and change the sitelink from www to ww2 and save.
I'll post a fix which will be included in the next release shortly.

**Comment by bibi32** [comment]
It's work,I dosen't know that, thanks.
