### ISSUE TITLE
Req: Search by hash

### ISSUE THREAD

**Issue by Jimmy03** [Jackett/Jackett#3573]
I'd like to be able to search by hash on the jackett manual search.  
  
This could be used to help find and load more trackers for existing torrents.

i.e if your torrent has low seeds, you can search for the hash and then load more trackers from other torrents with that same hash

Many of the major torrent sites have the hashes posted on the same page as the torrents, so it would be easy to read.

**Comment by kaso17** [comment]
The search engine of the torrent site must support searching by hash and I don't think any do. So jackett can't do this.

For public torrents just compile a list of well known trackers and add to your torrent. But I think in general DHT, etc. should already take care of this.
