### ISSUE TITLE
Torrent9 - Indicates a redirection, redirection suggestion already active.

### ISSUE THREAD

**Issue by sbeaudoin** [Jackett/Jackett#3574]
Jacket 0.9.41.0.  Testing Torrent9 indicates to try "https://www.torrent9.blue/".  This is already configured with this URL.

Here is the full message of the generated exception : 

Unable to connect to indexer: Torznab error detected: Jackett.Common.IndexerException: Exception (torrent9): Got redirected to another domain. Try changing the indexer URL to https://ww2.torrent9.blue/. ---> System.Exception: Parse error ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://ww2.torrent9.blue/.
   à Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebClientStringResult Result, IHtmlDocument document)
   à Jackett.Common.Indexers.CardigannIndexer.<PerformQuery>d__29.MoveNext()
   --- Fin de la trace de la pile d'exception interne ---
   à Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex)
   à Jackett.Common.Indexers.CardigannIndexer.<PerformQuery>d__29.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext()
   --- Fin de la trace de la pile d'exception interne ---
   à Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Jackett.Common.Indexers.BaseWebIndexer.<ResultsForQuery>d__25.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext()

**Comment by garfield69** [comment]
Access your jackett dashboard and edit your torrent9 configuration. Replace www with ww2 and save.
Duplicate of #3569

**Comment by sbeaudoin** [comment]
Sorry, it was in the original message and I missed it.  It works, thanks.
