### ISSUE TITLE
[REQ] LearnFlakes

### ISSUE THREAD

**Issue by koper89** [Jackett/Jackett#3575]
Hello,

I would like to ask for support of learnflakes tracker.
https://learnflakes.net

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by garfield69** [comment]
If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by BurhanDanger** [comment]
Don't think this'll work with cardigann indexer

**Comment by tkdrob** [comment]
> If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
> But if the site turns out to require a native c# indexer then I will not be able to complete the task.

Invite sent

**Comment by tkdrob** [comment]
@garfield69 Invite sent

**Comment by garfield69** [comment]
registration and login successful. Thank you.

note: when the site upgrades (Aug 25) to using the google reCaptcha we will probably need to switch to using cookie logins :-(
On the upside, it does appear (from a quick scan of the torrent browse html) that the site is compatible with cardigann so I should be able to prepare an indexer.

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.504

**Comment by garfield69** [comment]
@tkdrob  Sorry I don't have accounts for for bitme and passthepopcorn either.

**Comment by koushik-sen-vst-au4** [comment]
I wish I could get one learnflakes invite. It will be a great help.You can provide me a invite at senkoushik91@gmail.com

Thank You.

**Comment by koushik-sen-vst-au4** [comment]
> @garfield69 

I wish you can help me.
U can provide me a invite at senkoushik91@gmail.com.

It will be a great help.
Looking forward to hear from you.

**Comment by koushik-sen-vst-au4** [comment]
@tkdrob 

I wish you can help me.
U can provide me a invite at senkoushik91@gmail.com.

It will be a great help.
Looking forward to hear from you

**Comment by RoloSoze** [comment]
@koushik-sen-vst-au4 This is not a forum to request tracker invites. It's a place to report issues regarding Jackett's functionality. Thank you.

**Comment by koushik-sen-vst-au4** [comment]
@tkdrob Can you please invite me once again,as it is saying "the link is missing or expired."

Please invite me once again on my mail senkoushik91@gmail.com .

and please share your email so I can contact you further.

Github is removing my posts.

Please invite me once again.

**Comment by koushik-sen-vst-au4** [comment]
I also want to contribute to the team. It will be great if someone could add me.

**Comment by BurhanDanger** [comment]
@RoloSoze @garfield69  please close this thread for collaborators.

**Comment by garfield69** [comment]
https://learnflakes.net/ returning Error 502 Bad gateway

**Comment by ilike2burnthing** [comment]
![lf](https://user-images.githubusercontent.com/59480337/84822833-495f3700-b015-11ea-8351-0321c5ff90e5.png)

Login page at least seems to be up

**Comment by garfield69** [comment]
yes, re-tested and now I'm blocked by cloudflare. Can access via VPN using a region other than my default.

**Comment by garfield69** [comment]
https://learnflakes.net/ returns Error 524 A timeout occurred

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://learnflakes.net/ returns Error 524 A timeout occurred

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://learnflakes.net/ - Error 502 - Bad gateway

**Comment by garfield69** [comment]
Learn-**Flakes** is flaky ;-D

**Comment by ilike2burnthing** [comment]
back up... for now... ;P

**Comment by ilike2burnthing** [comment]
https://learnflakes.net/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://learnflakes.net/ - Invalid SSL certificate Error code 526

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://learnflakes.net/ - domain expired Park Logic page

**Comment by ilike2burnthing** [comment]
back up
