### ISSUE TITLE
How to Bind Jackett to a local ip address on Windows

### ISSUE THREAD

**Issue by pedroash** [Jackett/Jackett#3583]
Is it Possible to Bind the windows Jackett Service to a local ip address of my choosing ?

Hope you can help

Thanks for your time

**Comment by flightlevel** [comment]
Local ip as in localhost 127.0.0.1?
Can you provide more information what you are trying to do?

**Comment by pedroash** [comment]
I have open vpn setup on my router and i choose which ip addresses on my network can use it.

The pc with Jackett on it has two ip address 192.168.1.1 used for standard taffic and 192.168.1.2 used for vpn traffic

I wish to bind Jackett to the 192.168.1.2 address to use my vpn

Hope the extra info helps

thanks

**Comment by flightlevel** [comment]
@pedroash Remind me on this issue in a fortnight and we can activate this feature

**Comment by pedroash** [comment]
That is great

Many Thanks

**Comment by allywilson1** [comment]
I'd also like to see this.

My Linux host connects to a public VPN service so it has both an internal IP and a public IP, and I'd like to only allow Jackett to be accessible on the internal IP.

Even if it's not IP specific, but adapter specific it would be good (so I could bind to eth0 and ignore tun0 for example).

**Comment by flightlevel** [comment]
Update to the latest version
Create a new file called `appsettings.json` in your Jackett config directory (likely `C:\ProgramData\Jackett`)
Paste the below contents into `appsettings.json` file

`{ "urls": "http://192.168.1.2:9117" }`

**Comment by foozmeat** [comment]
For future visitors, using `{ "urls": "http://0.0.0.0:9117" }` should work if you don't want to use a fixed IP.
