### ISSUE TITLE
[yts] Sequence contains no matching element (Config)

### ISSUE THREAD

**Issue by kanazaca** [Jackett/Jackett#3587]
yts.am - Sequence contains no matching element (Config) 

**Jackett version**: 0.9.41.0  
**Mono version** (if not using Windows):  5.12.0.226

-------------------------------

**Comment by john626** [comment]
I am having same issue
**Jackett Version** :  0.10.37.0

**Comment by nordicblue** [comment]
Same issue here.
Jackett Version :  0.10.37

**Comment by garfield69** [comment]
yts is under maintenance. nothing to do with jackett. just have to wait until yts is back up.
![image](https://user-images.githubusercontent.com/6933240/44065228-94a953f4-9fbd-11e8-95fb-2371b4da53a9.png)

**Comment by nordicblue** [comment]
Sorry to bother on this. I went to their home page, saw the site was up, and never bothered to check the API link. Will do more due diligence next time I see an issue.
