### ISSUE TITLE
[New Tracker REQ] Corsaro.red

### ISSUE THREAD

**Issue by EffeF** [Jackett/Jackett#3593]
**Indexer Name**
~~TNTRip~~
Corsaro.red

**Type**
Movies, TV, Anime, .Music, Books, Games, Software

**Indexer URL**
~~https://tntrip.pw/~~
https://corsaro.red/

**Indexer Language**
Italian

**Invite**
No invite required, no registration required, open tracker

**Comment by Jorman** [comment]
I see on the bottom of the page that the indexer take the release from TNTVillage

`Il contenuto di questo sito viene processato in modo automatico partendo da TNTVillage`

That is already present. Are the content different in some way?

**Comment by EffeF** [comment]
Yes, the contents are the same. TNTRip was born as an alternative to the TNTVillage search page, since the latter has become very slow, and often offline.

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by garfield69** [comment]
accessing https://tntrip.pw/ yieds: (google translated)
```
TNTRip is offline!
As a precautionary measure, given the bad time TNTVillage is passing, TNTRip will remain offline until further notice. For more information refer to  this post Facebook . At the moment we can not provide a service that guarantees complete safety for both the provider and those who use it. We trust that you users will understand why, while we are all waiting for new developments.
It's not goodbye, it's goodbye.
TNTRIP 31/08/2018 21:04
```
closing ticket.

**Comment by EffeF** [comment]
The service is active again with a new domain: https://corsaro.red

Also clicking on https://tntrip.pw/ you are redirected to the new domain now.

**Comment by garfield69** [comment]
Hmm. don't think ilcorsaro.red can be processed with cardigann, its not a standard html page, but an dynamically generated one built by active javascript. needs c#.

**Comment by dandag** [comment]
Made a python script for qbittorent [https://github.com/dandag/qBittorrent_search_engine/blob/master/corsarored.py](https://github.com/dandag/qBittorrent_search_engine/blob/master/corsarored.py)

Can someone rewrite it in c#?

**Comment by Ansem93** [comment]
Hi,
TNT village is officially closed. Is it possible to add this tracker to Jackett now that TNT is dead?

**Comment by garfield69** [comment]
as soon as a c# volunteer raises a PR.

**Comment by Redtwist27** [comment]
What is this?
https://github.com/dandag/qBittorrent_search_engine/blob/master/jackett.py

**Comment by Jorman** [comment]
I think is the qbittorrent search plugin

**Comment by garfield69** [comment]
implemented by @dandag with PR #5962 released with jackett v0.11.675

**Comment by garfield69** [comment]
https://corsaro.red/ broken. searches return 
```
Errore imprevisto durante l'esecuzione dell'operazione.
DEBUG INFORMATIONS:
MongoError: Topology was destroyed
```

**Comment by Jorman** [comment]
Is the site that have problem, maybe with the database?

**Comment by dandag** [comment]
Yes the site is broken, both categories and file search return {"ok":false,"err":"MongoError: Topology was destroyed"}

Sounds like mongodb driver connetion problem

**Comment by ilike2burnthing** [comment]
https://corsaro.red/ - 404 page not found

**Comment by garfield69** [comment]
their search engine is broken
![image](https://user-images.githubusercontent.com/6933240/95616113-ca12d900-0ac5-11eb-9cde-731a2d4755dc.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by Olivier-Levasseur** [comment]
no news :/
Hoping for updates

**Comment by garfield69** [comment]
changes at the web sites means that when the indexer sends https://corsaro.red/api/latests as part of the keywordless search (also used by the TEST button) the site returns a 404 page not found.
@dandag  are you available to investigate and fix?

**Comment by garfield69** [comment]
web site search engine still broken 
![image](https://user-images.githubusercontent.com/6933240/96654959-e6055d00-1398-11eb-99ba-bb2c3b350412.png)

**Comment by ngosang** [comment]
Site down 404

**Comment by zFerry98** [comment]
News?

**Comment by garfield69** [comment]
the site is still broken. same results as https://github.com/Jackett/Jackett/issues/3593#issuecomment-713196868
in another 8 days we will check once more and if still not fixed then we will remove the indexer from Jackett.
