### ISSUE TITLE
[Feature Request] Debugging / Testing In Pop Up Or Pup Under Window

### ISSUE THREAD

**Issue by zero77** [Jackett/Jackett#3594]
Is it possible to test trackers in a browser pop up or pup under window.

Because, I think this could help with testing and fixing miner problems, especially for less technical users and users of header less devices. 

For example, when fixing issues involving captures, cookies, incorrect domain names and ISP or Ip restrictions.

Also, users will lightly be able to provide better descriptions of the problem thus, decreasing time and work for developers.

Thanks

**Comment by kaso17** [comment]
What exactly is the the new window supposed to show?
The complete log/error message?

**Comment by zero77** [comment]
@kaso17 
No, I was thinking of the webpage being shown its self, in the same way as accessing the site through a browser.

Because, I imagine lots of the errors could be fixed by simply watching what’s happening when connecting to the site.
> For example, when fixing issues involving captures, cookies, incorrect domain names and ISP or Ip restrictions.

**Comment by kaso17** [comment]
I've some security concerns regarding this. We don't want tracker operators to be able to inject JS into the jackett GUI (With some indexers this is actually possible). We would at least have to render it inside of an iframe and we would have to make sure it doesn't have access to cookies, etc.
Overall I'm not convinced it would be super helpful. Overall it would only help with unhandled error messages generated by the indexer itself.

**Comment by zero77** [comment]
Yes, you make a good point but, I was just thinking of something simple a bit like a web proxy but in an iframe and that only shows the domain of the tracker you are checking.

Perhaps using a domain white list consisting of the tracker domains with in Jackett.

> Overall it would only help with unhandled error messages generated by the indexer itself. Overall it would only help with unhandled error messages generated by the indexer itself.

Yes, but I imagine it could solve a lot of the error reports you get and potentially it could help with adding cookies and capture solving.

**Comment by kaso17** [comment]
With cookie related issues this wont be helpful at all (users just get redirected to the login page again). Some kind of cookie validator (which checks the existence/length of specific cookie values might help with this. Captcha error handling should be done on the corresponding indexer level (configure corresponding error selectors to extract "wrong catcha" error messages).
