### ISSUE TITLE
[bithumen] Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by beloware** [Jackett/Jackett#3595]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

It works only when default settings are.
When functions of site enabled/disabled which changes default browse table layout it stops working properly.
Might can be request some update for  ?

Whatever contribution necessary please  let me know.

Thanks a million!

**Comment by kaso17** [comment]
Which settings exactly are causing problems?

**Comment by kaso17** [comment]
Only by disabling the download button I was able to break the definition, fixed via fc060d64685bcaeaa9d21370b295c2a4e36a139b

If there's any other option causing problems please let us know.
