### ISSUE TITLE
Jackett auto updating but not starting on Linux

### ISSUE THREAD

**Issue by maphex** [Jackett/Jackett#360]
When Jackett receives an update it will update correctly but does not restart like its suppose to. I have to login to the shell and "sudo service Jackett restart". This is then causing my sonarr to not load the torrents as it shows a failure on the indexers. then after restarting the service I then manually have to go into Sonarr to retest all indexers to clear the error. Is there something I am missing or permission that need to be changed to the folder  it is currently install to /opt/Jackett.

**Comment by FedoraTipper** [comment]
Mine doesn't update at all. Logs show that it found a a new release (0.7.285) but when it tries to go further is crashes.

**Comment by raspdealer** [comment]
https://github.com/Jackett/Jackett/issues/154

**Comment by ajfried22** [comment]
sudo systemctl start jackett

**Comment by kaso17** [comment]
If you're using systemd as init system please try updating to Jackett version >= v0.7.898 and the init script from https://github.com/Jackett/Jackett/wiki/systemd-service.

If you still have problems please post the update log

**Comment by robgates** [comment]
Still having update issues on Ubuntu 16 , using the systemd script as supplied I use the working directory as /opt/jackett as per install instructions you point to. What logs do you need as sorry a bit of a newbie

**Comment by kaso17** [comment]
the update/log.txt files from ~/.config/Jackett/

**Comment by robgates** [comment]
Sorry managed to fix this by using the new init script
