### ISSUE TITLE
[REQ] Internet Archive Torrent Indexer

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [Jackett/Jackett#3603]
There are quite a few YouTube series and old TV shows that are hosted by the Internet Archive in a torrent format. Would it be possible to add the Internet Archive as an indexer?
They do have a [JSON API](https://archive.org/help/json.php).

**Comment by garfield69** [comment]
jackett 0.12.1669

**Comment by ilike2burnthing** [comment]
https://archive.org/
```
Temporarily Offline
The Internet Archive's sites are temporarily offline.
We apologize for the inconvenience.
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by gingerbeardman** [comment]
Would also like this.

Am currently playing around with the idea of adding it as a Download Station DLM.

**Comment by gingerbeardman** [comment]
For anybody else that finds this, Internet Archive exists within Jackett.

**Comment by ilike2burnthing** [comment]
It was added nearly 2 years ago - https://github.com/Jackett/Jackett/issues/3603#issuecomment-581062130
