### ISSUE TITLE
Error during search from Sonarr

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#3609]
Before open an issue on Sonarr side I want to know your opinion

If I do a manual search inside Jackett on girotorrent I found 10 results, if I make a search from Sonarr 0

Here some logs, maybe you see some that I don't see!

Girotorrent script:
https://pastebin.com/H7mXZcWX

Manual search from Jackett:
https://pastebin.com/4tWARm91

Search from Sonarr:
https://pastebin.com/AdrEZ1vn

Log about Jackett about the Sonarr search:
https://pastebin.com/yqDG688x

Any idea? Maybe I made some mistake on script!

**Comment by garfield69** [comment]
Your manual search on jackett was for *royals s04* but the search string generated by sonarr for jackett to use is for *royals 2015 s04*.
I bet that if you did a manual search on jackett for the latter string you would not get any hits.

**Comment by Jorman** [comment]
@garfield69 
In this case Sonarr search 2 times, one for royals 2015 s04 and another time for royals s04
see the second search from the log
`18-8-15 19:30:26.6|Debug|Torznab|Downloading Feed http://192.168.2.100:9117/api/v2.0/indexers/girotorrent/results/torznab/api?t=tvsearch&cat=5030,5040,7000,5070,5080,100074,100037&extended=1&apikey=(removed)&offset=0&limit=100&q=Royals&season=4`

I think I've found the "problem" if is a problem, right now, during a reply, yes because I remember the category of tv series in giro and I can't see the right category in the string I just paste, so all my tries are nothing, I just tried with the right category and works. so the problem is that I'm a dumbass!

I just modified some other thinks into the script, I'll update all script
