### ISSUE TITLE
Ability to export the configuration and import it to another Jackett instance.

### ISSUE THREAD

**Issue by RXWatcher1** [Jackett/Jackett#361]
My jackett is running via docker. When the docket container gets recreated for whatever reason, I cant copy back in my previous configuration and have it work due to cert issues. This causes me to manually re-add every indexer and if you have like 10-15 of them, its a pain. I would like the ability to backup my provider information and import it into new container.

Thank you!

**Comment by arppl** [comment]
Any news/thoughts on this? I'm having the same issue

**Comment by RXWatcher1** [comment]
I moved to a different docker that puts the mono keypairs outside of the actual docker container.
This one allows updates without issue: https://github.com/tyler43636/unraid-jackett

**Comment by arppl** [comment]
Thanks, that one works better indeed!

**Comment by adamwinn** [comment]
@kaso17 Is there any way to export the configuration of all the trackers and move it to another Jackett instance?  I grepped the dir for one sample tracker I have configured and no files came up, so I guess they're not stored anywhere where we can easily get to them.

**Comment by JigSawFr** [comment]
To keep config, you just need to map container config directory to host.

```
docker create \
--name=jackett \
-v <path to data>:/config \
-v <path to blackhole>:/downloads \
-e PGID=<gid> -e PUID=<uid> \
-e TZ=<timezone> \
-v /etc/localtime:/etc/localtime:ro \
-p 9117:9117 \
linuxserver/jackett
```

> **-v <path to data>:/config**

**Comment by kaso17** [comment]
@adamwinn 
If you copy the complete config dir (The exact location is displayed during startup) it should work.
Copying individual indexers won't work as the passwords are obfuscated using the instance ID from the ServerConfig.json.

**Comment by adamwinn** [comment]
@kaso17 I copied the entire Jackett dir over but I'm getting this now
```
08-22 12:06:47 Error Failed loading backup configuration for WorldOfP2P, you must reconfigure this indexer System.Security.Cryptography.CryptographicException: Data unprotection failed. ---> System.Security.Cryptography.CryptographicException: Invalid data.
```

**Comment by adamwinn** [comment]
I added a tracker manually and the "value" field in the password section of the json file of the indexer is different than my backup, even tho the InstanceId in ServerConfig.json is the same.

**Comment by kaso17** [comment]
Ok, seems like some other key's are used then to. The Obfuscation is based on the "ProtectedData" API. I've no idea how it works but seems like it stores keys at other places to.
On my linux installation I wound a key file at ~/.config/.mono/keypairs/ which might be related.

**Comment by adamwinn** [comment]
That worked!! Thanks!!

**Comment by Tankamin** [comment]
Can this be done in windows 10?  Thanks.

**Comment by kaso17** [comment]
@Tankamin no, there's no easy way of migrating jackett between windows systems

**Comment by srscott** [comment]
Sorry to necro. 
What about migrating from a FreeNAS iocage jail to Docker? And keeping trackers?

**Comment by flightlevel** [comment]
You''ll have a folder that stores Jackett configuration, contents will look like below 
![image](https://user-images.githubusercontent.com/9430010/55146395-9b116c80-5198-11e9-8e5b-ddfa574df5a6.png)

Copy the contents to a folder and then map that to the config folder when you create your container
https://github.com/linuxserver/docker-jackett#docker
