### ISSUE TITLE
[Feature request] Copy category from Capabilities with one click

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#3611]
Is not urgent, I know, but can be helpfull during the configuration phase!

![cattura](https://user-images.githubusercontent.com/5203988/44199249-da2c0980-a143-11e8-9d8e-19d19b3f87b3.PNG)

Would be good if in any category configured, a simple button to copy the category text but ... with comma included, so for example 100074 after the copy became ,100074 and so on ....
In this way the configuration phase on various program are much faster.
Why the comma? So (except the very 1st that one put in the configuration) because the schema is always category,category,category .... So became quick make a configuration.

What do you think?

**Comment by garfield69** [comment]
Closed as stale.
