### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on https://ww4.yggtorrent.is/ using form selector form[action$=

### ISSUE THREAD

**Issue by virtualfrancky** [Jackett/Jackett#3626]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.54.0
**Mono version** (if not using Windows):  5.8..0.108-11

-------------------------------

Yggt change there adress, but putting ww4 instead of ww3 doesnt solve the problem

log : https://pastebin.com/EJdmhedZ

**Comment by NGDM** [comment]
I had the same problem. 
> Yggt change there adress, but putting ww4 instead of ww3 doesnt solve the problem
Just closing the Configure page with Okay, reopening it and pressing Okay again solved the problem for some reason.

**Comment by virtualfrancky** [comment]
Thanks for the tips, it works now.

**Comment by flightlevel** [comment]
Fixed in latest release
