### ISSUE TITLE
[REQ] New Tracker Gimme Peers

### ISSUE THREAD

**Issue by azz22** [Jackett/Jackett#363]
Can you add Gimme Peers as a tracker please? This is the old BitSoup site. site map below
[gimmepeers-2.txt](https://github.com/Jackett/Jackett/files/315681/gimmepeers-2.txt)

I was a member of BitSoup for 5 years and yes i did pay to upgrade but my account is still active. I regularly donate to the site to support. Please give users the option of adding this site if they want to. Thanks

**Comment by duramato** [comment]
https://www.reddit.com/r/bitsoup/

**Comment by azz22** [comment]
this could just be ex owners/users not agreeing to the new site. I for one have been an avid member for 5 years and never had an issue. I'm not asking you to love them just create a tracker for those who use gimme peers please?

**Comment by kaso17** [comment]
closing this in favor of #548
