### ISSUE TITLE
[bithorlo] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by beloware** [Jackett/Jackett#3640]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  Latest
**Mono version** (if not using Windows):  Latest ubuntu 16

-------------------------------

Simply fails after cookie added.

**Comment by pums974** [comment]
Same problem here but only with firefox
But I did nothing with cookies

Jackett Version 0.10.69.0
mono 5.14.0.177-1 (Arch Linux)

**Comment by kaso17** [comment]
Works fine for me.
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by beloware** [comment]
@kaso17 yes. Cookie works only when you logged in inplace. Figured out. Small detail for server users.
