### ISSUE TITLE
Help with il corsaro nero script - nesting of if functions

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#3641]
With the latest script I modified the way about the script search. He always use the advanced search but with this method I always have to specify a category.

So, during a Radarr or Sonarr or other search, no problem because each program are configured to search into a set of categories.
The problem came when I do a manual search from Jackett without any category set, in this case there're no results from search.

The actual code of the search is:
`path: "{{if .Keywords}}advsearch.php?&category={{range .Categories}}{{.}};{{end}}&search={{ .Keywords}}&order=data&by=DESC&page=0{{else}}/recenti{{end}}"`

Is possible to make another if inside the 1st? So if no category are select, all category must be used!
I tried with this but don't works
`path: "{{if .Keywords}}{{ if .Categories }}advsearch.php?&category={{range .Categories}}{{.}};{{end}}&search={{ .Keywords}}&order=data&by=DESC&page=0{{else}}advsearch.php?search={{ .Keywords}}&order=data&by=DESC&page=0{{end}}{{else}}/recenti{{end}}"`

Any idea?

**Comment by kaso17** [comment]
set default: true in the cetageorymappings.

Example:
https://github.com/Jackett/Jackett/blob/a5e2e6ef60b8b751e3fa5ba949054e2ee5bde17b/src/Jackett.Common/Definitions/thepiratebay.yml

If no category is selected all categories with default=true are used.

**Comment by Jorman** [comment]
Thanks, works!
I update the file
