### ISSUE TITLE
[zooqle] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by dkids** [Jackett/Jackett#3642]
Jackett Version 0.10.69.0 
Mono JIT compiler version 5.14.0.177 (2018-04/f3a2216b65a Fri Aug  3 09:28:16 EDT 2018)

Jackett lists Zooqle as public but I need to pass captcha to see anything.   This is consistent with various browsers and modes (incognito, etc.)  There doesn't seem to be a way of doing this.    Zooqle should either be listed as semi-private (easiest) or there needs to be a way of handling captcha on public sites.

I'm using a VPN and it's possible that Zooqle is using a list of VPN nodes to throw the captcha.

**Comment by kaso17** [comment]
@dkids are you seeing a generic cloudflare captcha  (due to bad reputation of your VPN IP) or a zooqle specific one?

**Comment by dkids** [comment]
If I change the VPN to use a different country, I don't see a captcha (ordinary Firefox, privacy mode, Jackett test).   I tried this with several different countries provided via Private Internet Access and almost never was there a captcha.

So it's not consistent with Zooqle/Cloudflare as to IP #.

I have seen other captchas with private trackers but am able to use cookies so that it's not an issue.

Zooqle does seem to let users register but even if I did that there would be no way to use it with Jackett if it's listed as a public tracker.

It would be nice if it were more clear on the dashboard why the test from Jackett failed.

**Comment by dkids** [comment]
![screenshot_2018-09-07 attention required cloudflare](https://user-images.githubusercontent.com/30055574/45242600-89708200-b2a5-11e8-8961-7f89fd0ecc38.png)


Attached a monitor and got a screenshot

**Comment by dkids** [comment]
![screenshot_2018-09-07 attention required cloudflare](https://user-images.githubusercontent.com/30055574/45242600-89708200-b2a5-11e8-8961-7f89fd0ecc38.png)


Attached a monitor and got a screenshot

**Comment by kaso17** [comment]
thank you. That's the cloudflare anti abuse recatpcha. There's no easy way to bypass it (last time I checked it needs to be re-solved every 4 hours).
We recently added some code (2d5a90ae31f0adcd6e0ff81be3c171da476767fb) to detect it and throw a corresponding error.
