### ISSUE TITLE
Demonoid "Configuration failed" issue

### ISSUE THREAD

**Issue by d2dyno** [Jackett/Jackett#365]
When I try to add Demonoid with my sign in, to Jackett, I get this error every time:

Configuration failed: Specified argument was out of the range of valid values. Parameter name: index

Running on Windows 10 x64, with Jackett version 0.7.277.0 running as a Windows service.

**Comment by ArcoSeal** [comment]
Same issue for me, logs:

```
2016-06-18 10:21:45.7257 Debug WindowsWebClient:GetBytes(Url:http://www.demonoid.pw/cdn-cgi/l/chk_jschl?pass=***********************) 
2016-06-18 10:21:46.2570 Debug WindowsWebClient: Returning Redirect => 165 bytes 
2016-06-18 10:21:46.3664 Debug WindowsWebClient:GetBytes(Url:http://www.demonoid.pw/) 
2016-06-18 10:21:54.5232 Debug WindowsWebClient: Returning Redirect => 4162 bytes 
2016-06-18 10:21:54.6013 Debug WindowsWebClient:GetBytes(Url:http://www.demonoid.pw/cdn-cgi/l/chk_jschl?pass=***********************) 
2016-06-18 10:21:54.7576 Debug WindowsWebClient: Returning Redirect => 165 bytes 
2016-06-18 10:21:54.8357 Debug WindowsWebClient:GetBytes(Url:http://www.demonoid.pw/) 
2016-06-18 10:22:03.1018 Debug WindowsWebClient: Returning Redirect => 4303 bytes 
2016-06-18 10:22:03.1956 Debug WindowsWebClient:GetBytes(Url:http://www.demonoid.pw/cdn-cgi/l/chk_jschl?pass==***********************) 
2016-06-18 10:22:03.8518 Debug WindowsWebClient: Returning Redirect => 165 bytes 
2016-06-18 10:22:04.5081 Error Exception in Configure System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Jackett.Indexers.Demonoid.<>c__DisplayClass8_0.<ApplyConfiguration>b__0() in C:\projects\jackett\src\Jackett\Indexers\Demonoid.cs:line 61
   at Jackett.Indexers.BaseIndexer.<ConfigureIfOK>d__58.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\BaseIndexer.cs:line 424
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Indexers.Demonoid.<ApplyConfiguration>d__8.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\Demonoid.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Configure>d__16.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:line 187
```

**Comment by theg1nger** [comment]
Same here. Not able to use setup demonoid.

Logs:
Jun 23, 2016 09:01:59 AM	Error	
Exception in Configure
Jun 23, 2016 09:01:59 AM	Debug	
WindowsWebClient: Returning Redirect => 165 bytes
Jun 23, 2016 09:01:59 AM	Debug	
WindowsWebClient:GetBytes(Url:http://www.demonoid.pw/cdn-cgi/l/chk_jschl?pass=1466690529.495-Mw1Sw5cG+z)
Jun 23, 2016 09:01:59 AM	Debug	
WindowsWebClient: Returning Redirect => 4596 bytes
Jun 23, 2016 09:01:51 AM	Debug	
WindowsWebClient:GetBytes(Url:http://www.demonoid.pw/)
Jun 23, 2016 09:01:51 AM	Debug	
WindowsWebClient: Returning Redirect => 165 bytes
Jun 23, 2016 09:01:50 AM	Debug	
WindowsWebClient:GetBytes(Url:http://www.demonoid.pw/cdn-cgi/l/chk_jschl?pass=1466690521.386-yf4KoXJiZh)
Jun 23, 2016 09:01:50 AM	Debug	
WindowsWebClient: Returning Redirect => 4166 bytes
Jun 23, 2016 09:01:42 AM	Debug	
WindowsWebClient:GetBytes(Url:http://www.demonoid.pw/)
Jun 23, 2016 09:01:42 AM	Debug	
WindowsWebClient: Returning Redirect => 165 bytes
Jun 23, 2016 09:01:42 AM	Debug	
WindowsWebClient:GetBytes(Url:http://www.demonoid.pw/cdn-cgi/l/chk_jschl?pass=1466690513.264-ttraSRgGSy)
Jun 23, 2016 09:01:42 AM	Debug	
WindowsWebClient: Returning Redirect => <!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif; font-size: 100%;}
    h1 {font-size: 1.5em; color: #404040; text-align: center;}
    p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 20px;}
    @-webkit-keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }
    @keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }
    .bubbles { background-color: #404040; width:15px; height: 15px; margin:2px; border-radius:100%; -webkit-animation:bubbles 0.6s 0.07s infinite ease-in-out; animation:bubbles 0.6s 0.07s infinite ease-in-out; -webkit-animation-fill-mode:both; animation-fill-mode:both; display:inline-block; }
  </style>

    <script type="text/javascript">
  //<![CDATA[
  (function(){
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      var a = document.getElementById('cf-content');a.style.display = 'block';
      setTimeout(function(){
        var s,t,o,p,b,r,e,a,k,i,n,g,f, mtWAOnL={"CuRob":+((!+[]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]))};
        t = document.createElement('div');
        t.innerHTML="<a href='/'>x</a>";
        t = t.firstChild.href;r = t.match(/https?:\/\//)[0];
        t = t.substr(r.length); t = t.substr(0,t.length-1);
        a = document.getElementById('jschl-answer');
        f = document.getElementById('challenge-form');
        ;mtWAOnL.CuRob*=+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]));mtWAOnL.CuRob-=+((!+[]+!![]+!![]+[])+(!+[]+!![]));mtWAOnL.CuRob+=+((+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]));mtWAOnL.CuRob+=+((!+[]+!![]+[])+(!+[]+!![]+!![]));mtWAOnL.CuRob-=+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]));a.value = parseInt(mtWAOnL.CuRob, 10) + t.length; '; 121'
        f.submit();
      }, 4000);
    }, false);
  })();
  //]]>
</script>


</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1></noscript>
  <div id="cf-content" style="display:none">
    <div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> demonoid.pw.</h1>
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>
  </div>
  <form id="challenge-form" action="/cdn-cgi/l/chk_jschl" method="get">
    <input type="hidden" name="jschl_vc" value="ef75d7aeb9d68ff30c0fece5921968bd"/>
    <input type="hidden" name="pass" value="1466690513.264-ttraSRgGSy"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
</div>


          <div class="attribution">
            <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=iuam" target="_blank" style="font-size: 12px;">DDoS protection by CloudFlare</a>
            <br>
            Ray ID: 2b787962ea812629
          </div>
      </td>
    </tr>
  </table>
</body>
</html>
8'

**Comment by ElYoM** [comment]
Same for me... :(

**Comment by flightlevel** [comment]
Willing to have a look if anyone has an invite

**Comment by ScouseTS** [comment]
Unsure how to PM? 

Pass me your email address, I have you one ready :)

**Comment by flightlevel** [comment]
jackettapp at gmail

**Comment by ScouseTS** [comment]
Sent.

**Comment by d2dyno** [comment]
For some reason, this is now working, even though the only recent update was for BeyondHD...

**Comment by chromerobv** [comment]
not working for me either.  latest release. any update on this ?

**Comment by simonlock** [comment]
Not working for me either:
Aug 17, 2016 07:34:29 PM	Error	
Exception in test_indexer
Aug 17, 2016 07:34:29 PM	Info	
Found 0 releases from Demonoid

**Comment by flightlevel** [comment]
Thanks to @ScouseTS who sent me an invite a month ago
When you try to register I get 'database error' . This happened a month ago and still happens today, is there anything about this on their forum?

By the looks of it, cloudflare appears to be the problem, looking a solution...

**Comment by ldexterldesign** [comment]
+1

**Comment by flightlevel** [comment]
Have attempted to fix, but haven't tested it out.
Can a few of you test the latest release to see if it fixes the problem.
The latest release is a 'pre-release', to update: Tick the 'update to pre-release' tick box on your Jackett dashboard and then click 'Apply server settings' and then check for update.  This should update you to version 0.7.330.0

**Comment by simonlock** [comment]
I'm attempting to run Jackett on a Raspberry Pi. Following your instructions a new release is found.  Current: v0.7.320 New: v0.7.330, but it never installs because 'Apply server settings' causes the running Jackett service to crash.

**Comment by simonlock** [comment]
After reinstalling jackett the update simply fails to install:

Aug 21, 2016 10:48:13 PM	Error	
Error performing update.
Aug 21, 2016 10:48:01 PM	Info	
New release found.  Current: v0.7.320 New: v0.7.330

**Comment by ldexterldesign** [comment]
Hey @flightlevel,

Hmm, I followed your instructions, but I'm still on v0.7.320.0 too 😕

Look forward to trying your fix though

Hope this is useful

Kind regards

**Comment by flightlevel** [comment]
Give the latest 'regular' release a try https://github.com/Jackett/Jackett/releases/tag/v0.7.335

**Comment by Xezuka** [comment]
Thanks flightlevel -- this appears to be working again since v0.7.330.0 (pre-release ticked). I updated to v0.7.335.0 just now and it's also working there. I just removed/added it after the update and did a manual searched to confirm. Looking good!

**Comment by ldexterldesign** [comment]
Hey @flightlevel,

Successful update via dashboard this time - appears to work great!

Kind thanks

PS Is there any documentation if one would like to get involved in development?

**Comment by simonlock** [comment]
Excellent it's working now after downloading from link provided by flightlevel. It didn't work from the dashboard for me.

**Comment by flightlevel** [comment]
Good to hear its working now

@ldexterldesign do you have Windows or mac only?

**Comment by simonlock** [comment]
I'm running on a raspberry Pi

**Comment by ldexterldesign** [comment]
@flightlevel Mac OS X v10.11.6

**Comment by simonlock** [comment]
Having updated mono it appears to broken again for me.

**Comment by dustyhelp** [comment]
This was working for me after the url update.  But now it seems demonoid has yet again changed their url.... it is now http://www.dnoid.me/......  would it be possible to add a variablized (not a word, i know :-)....) field on the configuration window?  where you input the username/password also have URL?

**Comment by simonlock** [comment]
Yes it's not working again for me too.

**Comment by antakar** [comment]
It is not working for me:
Configuration failed

**Comment by kaso17** [comment]
Working for me.

Please post a log with enhanced logging enabled
