### ISSUE TITLE
[btdb] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#3650]
Jackett version: v0.10.69
Mono version (if not using Windows): 5.14.0.177

NOTE: The test fails, but the search works.

**Comment by garfield69** [comment]
strange. i dont have any problems with the test, ive tried multiple times.
![image](https://user-images.githubusercontent.com/6933240/44312385-29778000-a44b-11e8-854b-42015d6ddd06.png)

**Comment by garfield69** [comment]
Please enable enhanced logging (instructions in the section around https://github.com/Jackett/Jackett#troubleshooting ), and repeat the test and post the log here for us to take a look.

**Comment by ngosang** [comment]
It's working now. Sorry for the false alarm.
