### ISSUE TITLE
[yggtorrent] No form found on https://ww2.yggtorrent.is/. Site moved to https://ww4.yggtorrent.is/

### ISSUE THREAD

**Issue by Mikasway** [Jackett/Jackett#3655]
Hi,

THE NEW URL of YGG is now : https://ww4.yggtorrent.is/

Thanks all :)

**Comment by garfield69** [comment]
This has been fixed in the pre-release but yet to be published in the main  release.
But you can fix this for yourself now if you like, by accessing the jackett dashboard, editing the ygg indexer config, and changing the sitelink from ww2 to ww4 and saving.
