### ISSUE TITLE
[torrenting] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by aser007** [Jackett/Jackett#3657]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by aser007** [comment]
ono JIT compiler version 5.14.0.177 (tarball Mon Aug  6 09:13:43 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-/)
        GC:            sgen (concurrent by default)

**Comment by kaso17** [comment]
they added a recaptcha, if you reconfigure the indexer it should ask you for a cookie now.
They also did a minor HTML change, fixed via f78434e758a35baa5255242e9af26cd54bc36666
