### ISSUE TITLE
Sonarr sending rid instead of q. Causing issues with Jackett.

### ISSUE THREAD

**Issue by FSurani** [Jackett/Jackett#366]
Hello, 

So attempting to download series "How To Get Away with Murder" last episode was 4 months ago. Tracker is TD. When I do manual search on Sonarr, I only get values that are maximum 30 days old. However, when I manually search through Jackett I see everything. 

It used to download the show fine. Somewhere along the way it stopped (maybe my own fault) but at least I know it isn't a mapping issue potentially? Maybe Sonarr is sending a strange search string into Jackett?

I have tested series that have episodes that are older than 4 months old and it seems to be working...

Edit: looking at the logs in Sonarr this is the line that is being sent for `How To Get Away With Murder`:
`16-6-17 16:13:19.8|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/torznab/torrentday/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&rid=37307&season=2&ep=12`

Interestingly enough it's missing the "q" tag, here is another example from a different series `Scream Queens`:

`16-6-17 16:22:56.2|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/torznab/torrentday/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Scream%20Queens%202015&season=1&ep=12`

**Comment by FSurani** [comment]
Okay, 

So I managed to figure out a solution? I removed Jackett as an indexer, then I added it again (exact same settings as before) and then restarted Sonarr. Checking the logs, the same query is being sent with rid instead of q but this time it worked. No idea why. 

I'm going to leave this open in case anyone wants to explain, or ask more questions for debugging. Hopefully it helps someone else?

**Comment by CatmanIX** [comment]
I'm having a somewhat similar issue, few if any results are returned when manually searching for episodes on Sonarr, but searching from Jackett (or directly on the trackers of course) returns everything i expect.

**Comment by flightlevel** [comment]
This issue hasn't had activity for a while. If the issue still exists, please reopen and include full logs. https://github.com/Jackett/Jackett#troubleshooting
