### ISSUE TITLE
Jackett fails after every update on Windows

### ISSUE THREAD

**Issue by bluenote73** [Jackett/Jackett#3662]
So I've had to reinstall Jackett after every update going back roughly a couple of months (and again with this last one in the last couple days).
I've now switched to linux to run jackett because I got tired of it happening.  I've seen this talked about in various places, but I figured that it should be identified officially since it's not just me for the benefit of the remaining Windows users.

**Comment by garfield69** [comment]
I think I may be seeing this issue too.
On my win7 system (which is running on a slow old core2 processor)  I find that during the auto-update task, one of the jackett processes is *suspended*. 
This leaves the dashboard unresponsive and the update incomplete until I use my task manager to resume the suspended process, after which the update completes successfully.
I forgot to write down the name of the suspended process when it happened last time, but I promise when it happens again to report back the name.

**Comment by flightlevel** [comment]
Works perfectly here
Will need logs to understand whats happening, next time after it happens, need the 
log.txt
servicelog.txt
traylog.txt
updater.txt

**Comment by bluenote73** [comment]
[updater.txt](https://github.com/Jackett/Jackett/files/2308264/updater.txt)
[TrayLog.txt](https://github.com/Jackett/Jackett/files/2308265/TrayLog.txt)
[ServiceLog.txt](https://github.com/Jackett/Jackett/files/2308266/ServiceLog.txt)
[log.txt](https://github.com/Jackett/Jackett/files/2308267/log.txt)

I don't see anything obvious, when I try to start the service it just goes to starting, then back to stopped.
Maybe once you've looked at this you could let me know so I can delete these logs or you can delete the message since I didn't look to sanitize anything in there. thanks

**Comment by snamds** [comment]
I've the same problem.
Let me know if I can do anything to help

**Comment by garfield69** [comment]
@bluenote73  check to see if jackettConsole.exe or jackettService.exe exists in your programData/Jackett folder after the jackett update fails.
I discovered that my AVAST virus checker has been flagging one or both as malware, and moving the programs to its viruschest. 
The programs are safe, virusTotal.com passed both of them without flags, so this is obviously a false hit by my AVAST.

**Comment by bluenote73** [comment]
What an absolute piece of crap avast is. It was completely silently quarantining this. Sorry all. And thanks so much garfield. I think avast reset my settings with one of their forced upgrades at some point.
