### ISSUE TITLE
Blackhole URL missing server port on non-standard ports

### ISSUE THREAD

**Issue by D4rkSl4ve** [Jackett/Jackett#3668]
As stated, having a Proxy Port of 8080, as I can't use port 80, and having set my Manual download blackhole directory to:  /home/pi/Torrents.  Do a manual search, which will find what I am looking for within the indexers chosen, will give me the "magnet link" which automatically opens my local torrent client, and the "Save to server blackhole directory" icon, when such is selected, it quickly shows a "Request to Jackett server failed"

Upon looking at the code that it is spitting out, the link to blackhole directory is only showing:  
```
   http://<externalIP>/jackett/bh/thepiratebay/?jackett_apikey=<myJackettAPIKey&path=Q2ZESjhOSHUzZWxGWk1wR2pYOGR0dUExX0NyRlRZTzdrLUpNNkJUdExPQnlhWFR5VlRXYjgwb2dvVjMyNWJxVUtSVFIzNkVYTXVEekhVMEpiYkJ0M0NUSU8wZXNfd0Zta2x4M3drTTZiLUQ1WC1kbFZyQnkzRXY0bEUwNmZuWXI4MkhFX2gtN3BzVm1CS3lEbF9zTTJCenlyVlJzUGc&file=Alex+Jones+Radio+Show+08.20.2018.mp3
```
(I cut the code to shorten the characters...)

thus the error.  If I were to take that same code, but add my 'Proxy port' to it as such:
```
http://<externalIP>:8080/jackett/bh/thepiratebay/?jackett_apikey=<myJackettAPIKey&path=Q2ZESjhOSHUzZWxGWk1wR2pYOGR0dUExX0NyRlRZTzdrLUpNNkJUdExPQnlhWFR5VlRXYjgwb2dvVjMyNWJxVUtSVFIzNkVYTXVEekhVMEpiYkJ0M0NUSU8wZXNfd0Zta2x4M3drTTZiLUQ1WC1kbFZyQnkzRXY0bEUwNmZuWXI4MkhFX2gtN3BzVm1CS3lEbF9zTTJCenlyVlJzUGc&file=Alex+Jones+Radio+Show+08.20.2018.mp3
```
(I cut the code to shorten the characters...)

then it works perfectly; saves the file to the blackhole folder, and my client picks up from the watch folder, and everyone is happy.

https://i.imgur.com/r6U2V9p.jpg

**Jackett version**:  0.10.97.0
**Mono version** (if not using Windows):  5.12.0.301
-------------------------------

**Comment by fryfrog** [comment]
We talked about this on Radarr Discord. @D4rkSl4ve didn't understand what the proxy was for.

**Comment by fryfrog** [comment]
I switched my nginx reverse proxy to port 8443 instead of 443 and reproduced this. The RSS, torznab and potato feeds all properly get `:8443` as part of their url. But the blackhole link does *not*.

This has nothing to do w/ the proxy setting in Jackett, obviously. :)

**Comment by kaso17** [comment]
Most likely nginx doesn't include the original port in the (X-Forwarded-)Host header. So jackett doesn't know about it. Please check the internal HTTP request using e.g. tcpdump (`tcpdump -Avvvni any port 9117 -s 9000`)
and post the corresponding HTTP request header.

**Comment by D4rkSl4ve** [comment]
tcpdump:  https://pastebin.com/r4G7sWfJ

**Comment by D4rkSl4ve** [comment]
tcpdump: https://pastebin.com/r4G7sWfJ

jackett.conf: https://pastebin.com/34b1F6VY

nginx site: https://pastebin.com/YEVcW5rd

**Comment by fryfrog** [comment]
But why did the rss / torznab / potato feeds get the port properly?

**Comment by kaso17** [comment]
The feed URLs are generated on the client side via javascript. The download links/blackhole links are generated on the server side.

**Comment by fryfrog** [comment]
Ah! :)

**Comment by D4rkSl4ve** [comment]
that change fixed the issue.  Thanks!
