### ISSUE TITLE
Tracker scenetime returning 0 results

### ISSUE THREAD

**Issue by tkirkland** [Jackett/Jackett#367]
Executed from commandline:

mono JackettConsole.exe --SSLFix true -t -l

Log result: [log.txt](https://github.com/Jackett/Jackett/files/321944/log.txt)

Running on Ubuntu 16 LTS

Any ideas would be great..  I miss Scenetime..  :)

Initially, Sonarr was saying '0 results found' so I tried searching with the builtin search and still getting 0 hits.

**Comment by flightlevel** [comment]
If you've got an invite willing to have a go, can see an error in the log, but not that helpful

**Comment by tkirkland** [comment]
I do have one available.  How would you like me to get it to you?

**Comment by flightlevel** [comment]
jackettapp at gmail

**Comment by tkirkland** [comment]
> jackettapp at gmail

Sent.

**Comment by flightlevel** [comment]
I wonder if SceneTime was having issues that day
`GetString Returning InternalServerError`
Just gave it a try now and it worked perfectly 

eg .https://snag.gy/UeJQkM.jpg

Let me know if it still isn't working for you

**Comment by kaso17** [comment]
working with the latest version
