### ISSUE TITLE
[yggtorrent] Login Failed, got redirected

### ISSUE THREAD

**Issue by stephane-r** [Jackett/Jackett#3670]
**Jackett version**:  0.9.16.0 

-------------------------------

Hi community,

I would like add yggtorrent since the new URL is updated, but i've this error :

An error occured while updating this indexer

I've test the login on yggtorrent Web site, and it work.

Anyone can help me ?

The ptoblem is from change the new domain

**Comment by stephane-r** [comment]
The check for update buttons do nothing :/ (i'm ussing docker)

**Comment by garfield69** [comment]
Ahh, if you are on docker then you must only upgrade by fetching the latest docker release once it is available there.
which puts you in a bind, since they are probably not quite up to date with the latest releases published here on github.
try this: access your jackett dashboard and edit your ygg indexer configuration.
change the site link to `https://ww4.yggtorrent.is/` and save.

**Comment by stephane-r** [comment]
Yes, i use the linuxserver image, and the latest commit is june ..

On the ygg config, the URL and account information are all good :/

**Comment by garfield69** [comment]
are you quite certain that the site link is set to ww**4** ? back in june ygg was using ww**1** and the jackett ygg indexer config would have been set to that.
if it is correctly set to ww4 now, and you still cannot get it to work, then  i'm out of ideas, so perhaps one of the other developers can come up with a solution other than waiting for the latest release to find its way to the docker site.

**Comment by xfouloux** [comment]
it is now back to https://www.yggtorrent.is/

**Comment by garfield69** [comment]
@xfouloux  thanks for the heads up. I'll submit a fix shortly.
@stephane-r  so the good news is that ygg have changed their domain name, and so you could have a try using your jackett dashboard to edit the ygg indexer config to change the site link to www and see if that works for you.

**Comment by eephyne** [comment]
I have the latest release on Arch (0.10.97.0) and also have this issue. Changing ww4 to www does nothing. Always got the error

> An error occured while updating this indexer Login
>  failed: No form found on https://ww.yggtorrent.is/ using form selector form[action$="/user/login"]

**Comment by garfield69** [comment]
works for me, so I don't know whats going on. maybe one of the other developers can come up with a solve.
![image](https://user-images.githubusercontent.com/6933240/44616083-8c2ea880-a89d-11e8-87bc-85ee5f5f494f.png)
![image](https://user-images.githubusercontent.com/6933240/44616096-b84a2980-a89d-11e8-8026-4d2a3930b9f9.png)

**Comment by eephyne** [comment]
@garfield69 what version of mono do you have?

**Comment by mlatorre31** [comment]
Try removing the trailing slash. Worked for me

**Comment by eephyne** [comment]
Holy *** it works!
I remember tested without the slash but know it works.

Thanks!!
