### ISSUE TITLE
[yourexotic] Error: The username email field is required. (Config)

### ISSUE THREAD

**Issue by Gdesfarges** [Jackett/Jackett#3672]
When I add this indexer (Exoticaz) I got this message about a "username email" and only username is available
I tried Using the email adress into the username field and got the same error

**Comment by Gdesfarges** [comment]
JacketVersion: 0.10.60.0

**Comment by kaso17** [comment]
fixed via f05db7f5440ef9e8a5ad51c856c84358ad8ca08f and 12cc25bdb0297340f359d86ea50fd629dacc609f
