### ISSUE TITLE
CouchPotato - DanishBits - ?imdbid

### ISSUE THREAD

**Issue by kyppo** [Jackett/Jackett#3675]
I'm experiencing issues when searching DanishBits. Manual searches in Jackett work great, but I get zero results in CP.

This is the link that CP requests from Jackett (taken from CP log):
http:/xxxxxx.xxxxxxxxxxxx.xxx:25003/api/v2.0/indexers/danishbits/results/potato/?imdbid=tt2395427&search=Avengers+Age+of+Ultron&user=&passkey=xxx

If I remove _imdbid=tt2395427&_ I get the expected results.

Is there any way to simply ignore the imdbid parameter for DanishBits?

**Comment by hallengreenn** [comment]
You can add the following under line 40 in Danishbits.cs

Line 40 - Type = "private";

Add: TorznabCaps.SupportsImdbSearch = false;

**Comment by kyppo** [comment]
I am on a seedbox, so source manipulation is not an option, I'm afraid.
Also, would that even work for TorrentPotato?

**Comment by kaso17** [comment]
a copy/paste error was causing this.
Proper fix for this is d065f0abf42fa47769ac6747f3f9a9b196719535
