### ISSUE TITLE
[theplace] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by rahimsaied** [Jackett/Jackett#3678]
![screenshot 5542](https://user-images.githubusercontent.com/42635182/44528095-54d9c380-a706-11e8-899f-34196532b780.png)
![screenshot 5543](https://user-images.githubusercontent.com/42635182/44528097-55725a00-a706-11e8-8b7c-97c5df5141f7.png)
![screenshot 5544](https://user-images.githubusercontent.com/42635182/44528098-55725a00-a706-11e8-8559-a40ad57b2050.png)
![screenshot 5545](https://user-images.githubusercontent.com/42635182/44528099-55725a00-a706-11e8-8545-089d6a6dff40.png)

**Jackett version**:  v0.10.97

**Mono version** (if not using Windows):  

-------------------------------

**Comment by rahimsaied** [comment]
I had not clearly explained the issue in #3676. This is a very clear explanation of the issue. Please do not close it.

**Comment by rahimsaied** [comment]
Thank you very much. Also can you please look into this issue. Jackett is a really great software and if you could solve this problem I would really appreciate it. Thank you.

**Comment by rahimsaied** [comment]
Please help. When I try to add this tracker [ThePlace]-https://theplace.click/ jackett says login failed.

**Comment by kaso17** [comment]
closing, see #3676
