### ISSUE TITLE
[privatehd] - Not all categories are available

### ISSUE THREAD

**Issue by Rouzax** [Jackett/Jackett#3681]
Jackett Version 0.10.97.0 

In Jackett privateHD only shows

Category | Description
-- | --
2000 | Movies
2010 | Movies/Foreign
2030 | Movies/SD
2040 | Movies/HD
3000 | Audio
5000 | TV
5030 | TV/SD
5040 | TV/HD

While the actual site offers much more categories.
![image](https://user-images.githubusercontent.com/4103090/44542550-6f636b00-a70d-11e8-8c66-71ca43a5800f.png)

**Comment by kaso17** [comment]
These are not real tracker categories (tags/Rip Type instead). But with a little work it should be possible to search/parse these as categories.

**Comment by RoloSoze** [comment]
Related to #7593

**Comment by ngosang** [comment]
It's technically possible to do, but due to different qualities in AvistaZ, CinemaZ and PrivateHD (both share the code) this is a bit complicate. I think with the changes in #8050 it's enough for now.

**Comment by RoloSoze** [comment]
>  I think with the changes in #8050 it's enough for now.

I agree.
