### ISSUE TITLE
[morethantv] An error occurred while sending the request: Error: TrustFailure (A call to SSPI failed, see inner exception.) (Config)

### ISSUE THREAD

**Issue by jackjohnsonuk** [Jackett/Jackett#3688]
The latest version of Jackett as of 25/08/18 seems to have caused an error (as in title) with morethentv private tracker - I've rolled my docker container back to 0.10.97.0 and all is working fine again

-------------------------------

**Comment by kaso17** [comment]
it's working fine for me, are other https trackers working with the latest version? Maybe something went wrong with the certificate store initialization of the container.

**Comment by flightlevel** [comment]
Works perfectly here on latest Linuxserver docker with Morethantv
Provide the enhanced log and the issue can be re-opened
