### ISSUE TITLE
Wrong exit code after update

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#3692]
I use systemd to start jackett as a service. It works really well but I noticed a small bug.
After executing the update process, the process is killed (kill -9) in a non clean manner. In my system, this causes systemd to send a notification with the service crash. After that, systemd restart jackett.

Could you end the process with a 0 exit code?

Systemd journal
```
Aug 26 12:53:23 -- mono[1175]: 08-26 12:53:23 Info Copying zelkaorg.yml
Aug 26 12:53:23 -- mono[1175]: 08-26 12:53:23 Info Copying zooqle.yml
Aug 26 12:53:23 -- mono[1175]: 08-26 12:53:23 Info Copying ztracker.yml
Aug 26 12:53:23 -- mono[1175]: 08-26 12:53:23 Info Killing process 1175
Aug 26 12:53:23 -- mono[1175]: 08-26 12:53:23 Info Process 1175 didn't exit within 5 seconds
Aug 26 12:53:23 -- systemd[1]: ksystem-jackett.service: Main process exited, code=killed, status=9/KILL
Aug 26 12:53:23 -- systemd[1]: ksystem-jackett.service: Failed with result 'signal'.
Aug 26 12:53:23 -- systemd[1]: ksystem-jackett.service: Triggering OnFailure= dependencies.
Aug 26 12:53:28 -- systemd[1]: ksystem-jackett.service: Service hold-off time over, scheduling restart.
Aug 26 12:53:28 -- systemd[1]: ksystem-jackett.service: Scheduled restart job, restart counter is at 1.
Aug 26 12:53:28 -- systemd[1]: Stopped Jackett Daemon.
Aug 26 12:53:28 -- systemd[1]: Started Jackett Daemon.
Aug 26 12:53:29 -- mono[8129]: 08-26 12:53:29 Info Starting Jackett v0.10.117.0
Aug 26 12:53:32 -- mono[8129]: 08-26 12:53:32 Info Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5)
Aug 26 12:53:32 -- mono[8129]: 08-26 12:53:32 Info OS version: Unix 3.16.57.25 (64bit OS) (64bit process)
```

Systemd unit
```
[Unit]
Description=Jackett Daemon
OnFailure=notify-service@%n.service
After=network.target

[Service]
Restart=always
RestartSec=5
Type=simple
ExecStart=/usr/bin/mono --debug /root/scripts/jackett/JackettConsole.exe --NoRestart
TimeoutStopSec=20

[Install]
WantedBy=multi-user.target
```

**Comment by flightlevel** [comment]
Its by design so that systemd restarts Jackett
Previously, when Jackett exited cleanly to run the update, users systemd would automatically start Jackett while the update was in progress

**Comment by ngosang** [comment]
> Previously, when Jackett exited cleanly to run the update, users systemd would automatically start Jackett while the update was in progress

@flightlevel please don't close it.
If I understand this well:
1. Jackett launches a new updater process.
2. The updater process do the task
3. When the updater process finish, It kills the Jackett process
4. With option `--NoRestart`, the Jackett process is restarted by systemd
5. Without option `--NoRestart`, the Jackett process is restarted by the Updater (we don't wan't this in unix because systemd will start another process...)

I'm not requesting to change these steps, they are fine. The issue is here => https://github.com/Jackett/Jackett/blob/master/src/Jackett.Updater/Program.cs#L90
I think that kill means `kill -9` and terminates the process in a wrong way causing me false alerts on my systems.

I tested this and works really well:
```
ps aux | grep jack

kill -9 11568
jackett.service: Main process exited, code=killed, status=9/KILL
jackett.service: Failed with result 'signal'.
jackett.service: Triggering OnFailure= dependencies.
jackett.service: Service hold-off time over, scheduling restart.
jackett.service: Scheduled restart job, restart counter is at 1.
Stopped Jackett Daemon.
Started Jackett Daemon.

kill -15 11568
jackett.service: Service hold-off time over, scheduling restart.
jackett.service: Scheduled restart job, restart counter is at 1.
Stopped Jackett Daemon.
Started Jackett Daemon.
```

If you can change that line to send a TERM signal instead of the current KILL signal will be appreciated. Thank you.
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Updater/Program.cs#L90

**Comment by ngosang** [comment]
what about?
```
if (unix) {
     var startInfo = new ProcessStartInfo()
     startInfo.Arguments ="-15 " + pid;
     startInfo.FileName = "kill";
     Process.Start(startInfo);
}
```

**Comment by ngosang** [comment]
@kaso17 Tested! It works really well.
The fix is a bit ugly but that things happen when you have multi platform support...
