### ISSUE TITLE
[torrent9] Found no results while trying to browse this tracker (Torrent9)

### ISSUE THREAD

**Issue by kesurof** [Jackett/Jackett#3700]
`

Aug 28, 2018 10:42:45 AM | Info | Request finished in 77.1605ms 500 application/json
-- | -- | --
Aug 28, 2018 10:42:45 AM | Error | System.Exception: Found no results while trying to browse this tracker   at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x000e8] in <3196b723abe34936a1795211b11d2a59>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Server.Controllers.IndexerApiController+<Test>d__15.MoveNext () [0x000e1] in <d6819775d910452ca544bd4b70d063ba>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <ed07561af00f49668ebc547ea3e7ce17>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <ed07561af00f49668ebc547ea3e7ce17>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <ed07561af00f49668ebc547ea3e7ce17>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <ed07561af00f49668ebc547ea3e7ce17>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <ed07561af00f49668ebc547ea3e7ce17>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <ed07561af00f49668ebc547ea3e7ce17>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <ed07561af00f49668ebc547ea3e7ce17>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <ed07561af00f49668ebc547ea3e7ce17>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <ed07561af00f49668ebc547ea3e7ce17>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <ed07561af00f49668ebc547ea3e7ce17>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <ed07561af00f49668ebc547ea3e7ce17>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <51f5e57c3b1641ff921c58f55f777af6>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware+<Invoke>d__3.MoveNext () [0x00115] in <560d56f8376d4258a59ad5478913c777>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x0008a] in <d6819775d910452ca544bd4b70d063ba>:0
Aug 28, 2018 10:42:45 AM | Info | Executed action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) in 71.8157ms
Aug 28, 2018 10:42:45 AM | Info | Found 0 releases from Torrent9
Aug 28, 2018 10:42:45 AM | Info | Executing action method Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) - Validation state: Valid
Aug 28, 2018 10:42:45 AM | Info | Authorization was successful.
Aug 28, 2018 10:42:45 AM | Info | Route matched with {action = "Test", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)
Aug 28, 2018 10:42:45 AM | Info | Request starting HTTP/1.1 POST http://localhost:9117/jackett/api/v2.0/indexers/torrent9/test  0

`

**Comment by garfield69** [comment]
torrent9 have changed their domain.
try accessing your jackett dashboard, editing the torrent9 config, and changing the site link to `https://www.torrent9.rip/` and save.
