### ISSUE TITLE
[bithdtv] Your cookie did not work: Your cookie did not work (Config)

### ISSUE THREAD

**Issue by ralin3** [Jackett/Jackett#3702]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:   Jackett Version 0.10.117.0 
**Mono version** (if not using Windows):  Not sure, I'm using linuxserver/jackett on docker swarm

-------------------------------
https://pastebin.com/QX7qg0hG - log.txt

I can't add bit-hdtv as an indexer.
I did find the cookie-tab in firefox, but my actuall PHPSESSID is way shorter than the example in the config-page, not sure if that's what's causing it...

Other indexers can be added.

**Comment by kaso17** [comment]
Working fine  for me, the log is just a normal one (not enhanced).
Make sure you copy the complete cookie. Firefox shows only a shortened cookie by default.
The full cookie should look like `PHPSESSID=xxxxxxxxxxxxxxxxxxxxxxxxxx; h_su=xxxxxxxx; h_sp=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; h_sl=xxxxxxxxxxxx; punbb_cookie=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

**Comment by ralin3** [comment]
Thank you, that did the trick.
For reference, I needed to add all the labels as you said - however the page on jackett just mentions PHPSESSID.

**Comment by garfield69** [comment]
@ralin3  can you provide a link to the page you are referring to, so I can update it if required. thanks.

**Comment by ralin3** [comment]
Add Indexer, search for bit-hdtv, and then the configure-button.
Only PHPSESSID is listed in the input field by default.

**Comment by kaso17** [comment]
@ralin3 the cookie input box might contain some pre-login cookies. Always insert the complete cookie string from the browser.
