### ISSUE TITLE
[speedcd] Exception (speedcd): Object reference not set to an instance of an object: Parse error (Config)

### ISSUE THREAD

**Issue by acavataio** [Jackett/Jackett#3703]
Getting this error:

Aug 28, 2018 07:00:10 PM | Error | Jackett.Common.IndexerException: Exception (speedcd): Object reference not set to an instance of an object ---> System.Exception: Parse error ---> System.NullReferenceException: Object reference not set to an instance of an object   at Jackett.Common.Indexers.SpeedCD+<PerformQuery>d__10.MoveNext () [0x00321] in <3196b723abe34936a1795211b11d2a59>:0     --- End of inner exception stack trace ---   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError (System.String results, System.Exception ex) [0x00064] in <3196b723abe34936a1795211b11d2a59>:0    at Jackett.Common.Indexers.SpeedCD+<PerformQuery>d__10.MoveNext () [0x00525] in <3196b723abe34936a1795211b11d2a59>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x00091] in <3196b723abe34936a1795211b11d2a59>:0     --- End of inner exception stack trace ---   at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x000ee] in <3196b723abe34936a1795211b11d2a59>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x0006b] in <3196b723abe34936a1795211b11d2a59>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x000a3] in <3196b723abe34936a1795211b11d2a59>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Server.Controllers.IndexerApiController+<UpdateConfig>d__13.MoveNext () [0x0012d] in <d6819775d910452ca544bd4b70d063ba>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <ed07561af00f49668ebc547ea3e7ce17>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <ed07561af00f49668ebc547ea3e7ce17>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <ed07561af00f49668ebc547ea3e7ce17>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <ed07561af00f49668ebc547ea3e7ce17>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <ed07561af00f49668ebc547ea3e7ce17>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <ed07561af00f49668ebc547ea3e7ce17>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <ed07561af00f49668ebc547ea3e7ce17>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <ed07561af00f49668ebc547ea3e7ce17>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <ed07561af00f49668ebc547ea3e7ce17>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <ed07561af00f49668ebc547ea3e7ce17>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <ed07561af00f49668ebc547ea3e7ce17>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <51f5e57c3b1641ff921c58f55f777af6>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x0008a] in <d6819775d910452ca544bd4b70d063ba>:0
-- | -- | --

**Comment by flightlevel** [comment]
They changed their site, try 0.10.134
