### ISSUE TITLE
[torrentland] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by sampleslaya** [Jackett/Jackett#3708]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  Jackett Version 0.10.117.0
**Mono version** (if not using Windows):  don't know

-------------------------------

**Comment by titooo7** [comment]
Same issue here. The test fails on Jackett despite entering right credentials for https://torrentland.li

**Comment by kaso17** [comment]
@Albvadi can you help with this?

**Comment by oscarmenendezgarcia** [comment]
Any update on this?
