### ISSUE TITLE
Building from source windows

### ISSUE THREAD

**Issue by snamds** [Jackett/Jackett#3709]
The readme.md should be modified:

- The Visual Studio Web Server package has to be installed because of the IIS Express
- Jackett.Server is the startup project

**Comment by kaso17** [comment]
Did you choose "Jackett.server" in the run button (instead of "IIS Express")?
I would expect in that case we don't need IIS Express installed.
I've updated the README accordingly via fcda42b9f1f9c93d14962e114d8c059979a52e69
