### ISSUE TITLE
[REQ] New Tracker: Tspate.me

### ISSUE THREAD

**Issue by bidulle95** [Jackett/Jackett#371]
hello i want use this tracker https://www.tspate.me/ please thanks i'm french user

**Comment by bidulle95** [comment]
AddCategoryMapping("1", TorznabCatType.Films: DVDRip);
AddCategoryMapping("2", TorznabCatType.Films: DVDRip VOSTFR);
AddCategoryMapping("3", TorznabCatType.Films: DVD-R);
AddCategoryMapping("4", TorznabCatType.Films: 720p);
AddCategoryMapping("5", TorznabCatType.Films: 1080p);
AddCategoryMapping("6", TorznabCatType.Films: BluRay);
AddCategoryMapping("7", TorznabCatType.Films: BluRay-3D);
AddCategoryMapping("8", TorznabCatType.Films: Cam / TS);
AddCategoryMapping("9", TorznabCatType.Films: R5);
AddCategoryMapping("10", TorznabCatType.Films: DVDSCR);
AddCategoryMapping("11", TorznabCatType.Films: BDRip);
AddCategoryMapping("12", TorznabCatType.Films: BRRip);
AddCategoryMapping("13", TorznabCatType.Films: WEBRip);
AddCategoryMapping("56", TorznabCatType.Films: mHD);
AddCategoryMapping("46", TorznabCatType.Musiques: MP3);
AddCategoryMapping("47", TorznabCatType.Musiques: FLAC);
AddCategoryMapping("48", TorznabCatType.Musiques: WMA);
AddCategoryMapping("49", TorznabCatType.Musiques: Autres);
AddCategoryMapping("14", TorznabCatType.Series: TV VF);
AddCategoryMapping("15, TorznabCatType.Series: TV VOSTFR);
AddCategoryMapping("16", TorznabCatType.Series: TV VOSTA);
AddCategoryMapping("17", TorznabCatType.Series: TV PACK);
AddCategoryMapping("18", TorznabCatType.Series: TV HD);
AddCategoryMapping("19", TorznabCatType.Series: TV HD FR);
AddCategoryMapping("20", TorznabCatType.Series: TV VO);
AddCategoryMapping("21", TorznabCatType.Series: DVD-R TV);
AddCategoryMapping("57", TorznabCatType.Series: TVHD VOSTFR);
AddCategoryMapping("22", TorznabCatType.Television: Documentaires);
AddCategoryMapping("23", TorznabCatType.Television: Sports);
AddCategoryMapping("24", TorznabCatType.Television: Spectacles);
AddCategoryMapping("25", TorznabCatType.Television: Animes);
AddCategoryMapping("26", TorznabCatType.Television: Television);
AddCategoryMapping("51", TorznabCatType.XXX);

**Comment by bidulle95** [comment]
AddMultiCategoryMapping(TorznabCatType.film,1,2,3,4,5,6,7,8,9,10,11,12,13,56);
AddMultiCategoryMapping(TorznabCatType.serie,14,15,16,17,18,19,20,21,57);
AddMultiCategoryMapping(TorznabCatType.television,22,23,24,25,26,51);

**Comment by thenamelessthing** [comment]
I want this tracket too!

**Comment by bidulle95** [comment]
I'm still waiting for this tracker?
What must I do to make my request come true?

**Comment by thenamelessthing** [comment]
I think Jackett project is almost dead.. At least it's my feeling. ;-(

**Comment by savahu** [comment]
@thenamelessthing How come? I see a lot of commits, and Cardigann is also in development.

**Comment by thenamelessthing** [comment]
@savahu I'm fine! Yeah I know the project is still alive, but maybe the project need more dev to help development?  Unfortunatly I have no skill for that... ;-(

**Comment by kaso17** [comment]
please send an invite to kaso1717 -at- gmail.com and I'll add it.

**Comment by thenamelessthing** [comment]
@kaso17   Check your mail...

**Comment by bidulle95** [comment]
You could add a freeleech option please

**Comment by kaso17** [comment]
got two invites, thank you, might take some time until I get to this one.
@bidulle95 what do you mean with freeleech option?

**Comment by bidulle95** [comment]
As for the xthor tracker

**Comment by bidulle95** [comment]
Tspate has to change name the address of the new site is https://www.sharespacedb.me
The identifiers are the same as for tspate could you change this indexer please

**Comment by kaso17** [comment]
added/renamed with 81c9828e4c7c051b9ba716d567f37274e295039e
