### ISSUE TITLE
Reverse Proxy dropping port on redirect with version 10

### ISSUE THREAD

**Issue by Quiksmage** [Jackett/Jackett#3712]
Jackett Version 0.10.134.0

Since updating to the new version, I find that when going to my reverse proxy URL,
https://domain.com:7373/jackett/UI/Dashboard
I'm being redirected to
https://domain.com/jackett/UI/Login?ReturnUrl=%2Fjackett%2FUI%2FDashboard

if I manually type the port into the above URL, i get a login prompt for jackett.
https://domain.com:7373/jackett/UI/Login?ReturnUrl=%2Fjackett%2FUI%2FDashboard
![image](https://user-images.githubusercontent.com/12449533/44815270-e7a9b080-ab93-11e8-9913-3545028dd240.png)

after logging in, it will present me with a HTTP ERROR 400 (it doesn't matter if I type the correct password in or not)
![image](https://user-images.githubusercontent.com/12449533/44815285-f55f3600-ab93-11e8-90e0-af440f2c5117.png)

If I refresh the page, I am again redirected to 
https://domain.com/jackett/UI/Login?ReturnUrl=%2Fjackett%2FUI%2FDashboard

Endless Loop.

My NGINX settings are below
```
#Jackett
        location /jackett {
                proxy_pass http://192.168.1.60:10005;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real_IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $server_name;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Ssl on;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }
```

I tried adding a trailing / to the location, but it didn't change anything
        location /jackett/ {

**Comment by Quiksmage** [comment]
Funnily enough, all my indexers are still working in sonarr/radarr through the existing reverse proxy URL.

**Comment by neuman1812** [comment]
Take a look at #3643

**Comment by Kilay** [comment]
Had the same error, you should replace `proxy_set_header Connection "Upgrade";` with `proxy_set_header Connection $http_connection;` in your Nginx config

Seems to be related to Kestrel (https://github.com/aspnet/KestrelHttpServer/issues/1263)
