### ISSUE TITLE
[scenetime] Your cookie did not work: Your cookie did not work (Config)

### ISSUE THREAD

**Issue by RossD327** [Jackett/Jackett#3713]
I am running:
 Jackett Version 0.8.716.0 
For some unknown reason I am unable to connect to Scenetime via Jackett. Two other indexers I use are working properly and Jacket appears to be functioning normally.  I am confused as to what the issue could be.  I have pasted the entire cookie hash multiple times from Scenetime all without success. Any ideas on what I could try next to fix?

Ross

**Comment by kaso17** [comment]
your jackett version is very old, update to the latest one.
