### ISSUE TITLE
[nCore] missing pagination

### ISSUE THREAD

**Issue by MateEke** [Jackett/Jackett#3716]
**Jackett version**:  0.10.134.0
**Mono version** (if not using Windows):  

-------------------------------

There was an issue about ncore  paging,  #27 . The problem still occours, however nCore implemented proper pagination, for example: [https://ncore.cc/torrents.php?oldal=2&tipus=all_own&mire=ncis&miben=name](https://ncore.cc/torrents.php?**oldal=2**&tipus=all_own&mire=ncis&miben=name), where "oldal=2" means "page=2".

**Comment by kaso17** [comment]
most indexers don't support pagination. There's a general issue to track this: #975

**Comment by morpheus133** [comment]
@MateEke  My correction was merged can you check it?

**Comment by MateEke** [comment]
I have a docker installation, so I can check if it gets released to dockerhub.

**Comment by MateEke** [comment]
The docker image is released now, so I have checked: works fine, thank you!
