### ISSUE TITLE
[torrentday] Exception (torrentday): Login failed, please reconfigure the tracker to update the cookies: Login failed, please reconfigure the tracker to update the cookies (Test)

### ISSUE THREAD

**Issue by SemperFratres** [Jackett/Jackett#3717]
Jackett is working fine with the exception of torrentday.
I get the cookie and it passes, but by the time I get to sonarr/radarr, jackett has shortened the cookie required for a pass.

required cookie:__cfduid=db711bec7e3199c5ddec8065a87axxxxxxxxxxxxxxx; uid=245xxxx; pass=4030dd6a6dad31faaxxxxxxxxxxxxxxx; uid=245xxxx; pass=4030dd6a6dad31faaxxxxxxxxxxxxxxx

jackett shortened cookie: __cfduid=db711bec7e3199c5ddec8065a87axxxxxxxxxxxxxxx; 

-------------------------------

**Comment by flightlevel** [comment]
Can you try a different site link e.g. `https://tdonline.org/` and make sure you get the cookie using the same web address as the site link in Jackett

**Comment by SemperFratres** [comment]
It seems to continue working once I put the cookie in and click OK, but if I open the settings again to see what categories I need, it fails and I have to re-enter the cookie. I created a .gif showing what I am doing. Obviously, I haven't included the clicking due to my cookie being visible if I did so, but you can see the messages and determine what I am doing.
At the start (not much video of the beginning) I use the full length cookie as stated in "required cookie" above. Opening the dialog box again shortens the cookie as stated above in the OP.

![torrentday](https://user-images.githubusercontent.com/6467149/44909497-97466600-aced-11e8-9baf-8e1c8bc639a3.gif)

**Comment by kaso17** [comment]
the TD indexer was resetting the cookies when you opened the configure dialog, this might have had a reason back when the recaptcha workaround was working but now there's no point in it.
Fixed via 88858022affa4bbc56c935910d6446b6d7cdc1f5
