### ISSUE TITLE
FreshOn.tv feed parsing issues w/ Sonarr

### ISSUE THREAD

**Issue by breakthestatic** [Jackett/Jackett#372]
Using Sonarr w/ Jackett for my FreshOn.tv account, I notice that Sonarr seems to ignore the FreshOn results.  In the Sonarr logs I see the following:

16-6-22 15:43:00.4|Debug|TorznabRssParser|Failed to parse Url https://freshon.tv//details.php?id=167490, ignoring.

[v2.0.0.4146] System.ArgumentException: Uri didn't match expected pattern: https://freshon.tv//details.php?id=167490
   at NzbDrone.Common.Http.HttpUri.Parse() in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\HttpUri.cs:line 85
   at NzbDrone.Core.Indexers.RssParser.ParseUrl(String value) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\RssParser.cs:line 263

It seems that Sonarr is choking when the url is incorrectly formatted (note the double forward slashes in the path - //details.php...)  I checked the actual source coming from FreshOn.tv and they seem to be properly encoded, so I think something inside Jackett is adding the duplicate, erroneous slash.  Would be great if we could get this Indexer fixed.  I can provide more detailed logs, info, etc... if it would help.

*EDIT*
I'm not a C# developer (just a UI/Web guy), but I downloaded Visual Studio and grabbed the source.  It seems that adding a .TrimStart('/') to the call to create the guid element in FreshOn.cs fixes the issue and allows Sonarr to parse the properly constructed URL.  I'm not sure if this is an appropriate code change or not (I believe that TrimStart is better than always doing a .substring(1) in the event that the href attribute does not begin with /).  If so, maybe I could do a pull request, although I'm not that familiar with Git.

**Comment by flightlevel** [comment]
Thanks @breakthestatic 
TrimStart did the trick, now fixed in the latest release
