### ISSUE TITLE
jackett not respecting -v "version" flag

### ISSUE THREAD

**Issue by jeremysherriff** [Jackett/Jackett#3720]
**Jackett version**:  v0.10.134.0
**Mono version** (if not using Windows):  5.14.0.177

Am on Ubuntu 16.04 LTS.
Previous versions have output the version string and exited cleanly when running `mono /opt/jackett/JackettConsole.exe -v`

v0.10.134.0 (and maybe some other recent versions) ignores this flag and attempts to launch the Jackett application as normal.  Not sure of the exact version thhat this last worked on.

If Jackett was already running (ie via systemd service) it correctly detects that the port is not free, and attempts to shut down.  However shutdown fails and the application does not die when sent Ctrl-C:

````
08-31 18:57:19 Error Address already in use: Most likely Jackett is already running. Failed to bind to address http://[::]:9117: address already in use.
Application is shutting down...
Application is shutting down...
Application is shutting down...
Application is shutting down...
Application is shutting down...
````
Running `mono /opt/jackett/JackettConsole.exe -?` indicates that acceptable flags for displaying the version string are `-v` `--Version` and `--version`.

This will cause people issues if they are relying on the -v flag to check and update Jackett versions using their own scripts.

**Comment by garfield69** [comment]
confirmed, and not restricted to just the linux platform either.
 on my win7 system for example, using `-v` on the command line results is a startup attempt, while using `--Version` correctly shows the version string and exits.

**Comment by jeremysherriff** [comment]
I was hoping to find the issue and open a PR but can't figure it out 😞 

Looks like the command line parameters are parsed in src/Jackett.Common/Models/Config/RuntimeSettings.cs
I can see where the ShowVersion bool is declared, but it doesn't look like it ever gets set, and then I cannot find it ever being referenced anywhere else (unlike other options like PIDFile or NoRestart)

But launching with the "--version" version of the flag works fine so I'm stumped

**Comment by flightlevel** [comment]
`--help` had the same issue, Jackett attempting to start
We get `--help` and `--version` both for free without writing any code
Don't think its worth adding code for just `-v`
Microsoft use `dotnet.exe --version` but not `dotnet.exe -v`
Jackett now won't start if you try `-v`
