### ISSUE TITLE
Can't disable enhanced logging

### ISSUE THREAD

**Issue by tbotcotw** [Jackett/Jackett#3723]
Enhanced logging seems to be turned on by default, my syslog is filling up whenever Jackett does anything, even when the checkbox is unchecked. Also, the checkbox doesn't seem to do anything, checking it and saving doesn't update the config file, and it's unchecked again if I reload the jackett process.

This is probably user error, but I've looked and looked and I can't get it to log less.

**Jackett version**:  0.10.134.0
**Mono version** (if not using Windows):  5.14.0.177

-------------------------------

**Comment by flightlevel** [comment]
Are you using systemd?
Can you provide example of whats going into syslog?
When Jackett restarts it automatically unticks the 'enhanced logging' so that people don't accidentally leave it on (it writes very detailed log files)
Jackett still does less detailed logging with 'enhanced logging' switched off

**Comment by tbotcotw** [comment]
Yes, systemd.

Here's what gets logged if I refresh the jackett dashboard:

Sep  5 10:42:21 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Sep  5 10:42:21 eastwood jackett[31435]:       Request starting HTTP/1.1 GET http://192.168.1.1:9117/UI/Dashboard
Sep  5 10:42:21 eastwood jackett[31435]: 09-05 10:42:21 Info Request starting HTTP/1.1 GET http://192.168.1.1:9117/UI/Dashboard
Sep  5 10:42:21 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Sep  5 10:42:21 eastwood jackett[31435]:       Route matched with {action = "Dashboard", controller = "WebUI"}. Executing action Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole)
Sep  5 10:42:21 eastwood jackett[31435]: 09-05 10:42:21 Info Route matched with {action = "Dashboard", controller = "WebUI"}. Executing action Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole)
Sep  5 10:42:21 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
Sep  5 10:42:21 eastwood jackett[31435]:       Authorization was successful.
Sep  5 10:42:21 eastwood jackett[31435]: 09-05 10:42:21 Info Authorization was successful.
Sep  5 10:42:21 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Sep  5 10:42:21 eastwood jackett[31435]:       Executing action method Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole) - Validation state: Valid
Sep  5 10:42:21 eastwood jackett[31435]: 09-05 10:42:21 Info Executing action method Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole) - Validation state: Valid
Sep  5 10:42:21 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
Sep  5 10:42:21 eastwood jackett[31435]:       Executed action method Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole), returned result Microsoft.AspNetCore.Mvc.PhysicalFileResult in 7.229ms.
Sep  5 10:42:21 eastwood jackett[31435]: 09-05 10:42:21 Info Executed action method Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole), returned result Microsoft.AspNetCore.Mvc.PhysicalFileResult in 7.229ms.
Sep  5 10:42:21 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Infrastructure.PhysicalFileResultExecutor[1]
Sep  5 10:42:21 eastwood jackett[31435]:       Executing Microsoft.AspNetCore.Mvc.PhysicalFileResult, sending file '/opt/Jackett/Content/index.html' with download name '' ...
Sep  5 10:42:21 eastwood jackett[31435]: 09-05 10:42:21 Info Executing Microsoft.AspNetCore.Mvc.PhysicalFileResult, sending file '/opt/Jackett/Content/index.html' with download name '' ...
Sep  5 10:42:21 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
Sep  5 10:42:21 eastwood jackett[31435]:       Executed action Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole) in 124.9852ms
Sep  5 10:42:21 eastwood jackett[31435]: 09-05 10:42:21 Info Executed action Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole) in 124.9852ms
Sep  5 10:42:21 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Sep  5 10:42:21 eastwood jackett[31435]:       Request finished in 608.3094ms 200 text/html
Sep  5 10:42:21 eastwood jackett[31435]: 09-05 10:42:21 Info Request finished in 608.3094ms 200 text/html
Sep  5 10:42:22 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Sep  5 10:42:22 eastwood jackett[31435]:       Request starting HTTP/1.1 GET http://192.168.1.1:9117/api/v2.0/server/config?_=1536165741975
Sep  5 10:42:22 eastwood jackett[31435]: 09-05 10:42:22 Info Request starting HTTP/1.1 GET http://192.168.1.1:9117/api/v2.0/server/config?_=1536165741975
Sep  5 10:42:22 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Sep  5 10:42:22 eastwood jackett[31435]:       Route matched with {action = "Config", controller = "ServerConfiguration"}. Executing action Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole)
Sep  5 10:42:22 eastwood jackett[31435]: 09-05 10:42:22 Info Route matched with {action = "Config", controller = "ServerConfiguration"}. Executing action Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole)
Sep  5 10:42:22 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
Sep  5 10:42:22 eastwood jackett[31435]:       Authorization was successful.
Sep  5 10:42:22 eastwood jackett[31435]: 09-05 10:42:22 Info Authorization was successful.
Sep  5 10:42:22 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Sep  5 10:42:22 eastwood jackett[31435]:       Executing action method Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole) - Validation state: Valid
Sep  5 10:42:22 eastwood jackett[31435]: 09-05 10:42:22 Info Executing action method Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole) - Validation state: Valid
Sep  5 10:42:22 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
Sep  5 10:42:22 eastwood jackett[31435]:       Executed action method Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 2.4066ms.
Sep  5 10:42:22 eastwood jackett[31435]: 09-05 10:42:22 Info Executed action method Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 2.4066ms.
Sep  5 10:42:22 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
Sep  5 10:42:22 eastwood jackett[31435]:       Executing ObjectResult, writing value of type 'Jackett.Common.Models.DTO.ServerConfig'.
Sep  5 10:42:22 eastwood jackett[31435]: 09-05 10:42:22 Info Executing ObjectResult, writing value of type 'Jackett.Common.Models.DTO.ServerConfig'.
Sep  5 10:42:22 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
Sep  5 10:42:22 eastwood jackett[31435]:       Executed action Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole) in 78.2364ms
Sep  5 10:42:22 eastwood jackett[31435]: 09-05 10:42:22 Info Executed action Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole) in 78.2364ms
Sep  5 10:42:22 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Sep  5 10:42:22 eastwood jackett[31435]:       Request finished in 86.4219ms 200 application/json; charset=utf-8
Sep  5 10:42:22 eastwood jackett[31435]: 09-05 10:42:22 Info Request finished in 86.4219ms 200 application/json; charset=utf-8
Sep  5 10:42:23 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Sep  5 10:42:23 eastwood jackett[31435]:       Request starting HTTP/1.1 GET http://192.168.1.1:9117/favicon.ico
Sep  5 10:42:23 eastwood jackett[31435]: 09-05 10:42:23 Info Request starting HTTP/1.1 GET http://192.168.1.1:9117/favicon.ico
Sep  5 10:42:23 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
Sep  5 10:42:23 eastwood jackett[31435]:       Sending file. Request path: '/favicon.ico'. Physical path: '/opt/Jackett/Content/favicon.ico'
Sep  5 10:42:23 eastwood jackett[31435]: 09-05 10:42:23 Info Sending file. Request path: '/favicon.ico'. Physical path: '/opt/Jackett/Content/favicon.ico'
Sep  5 10:42:23 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Sep  5 10:42:23 eastwood jackett[31435]:       Request finished in 25.3475ms 200 image/x-icon
Sep  5 10:42:23 eastwood jackett[31435]: 09-05 10:42:23 Info Request finished in 25.3475ms 200 image/x-icon
Sep  5 10:42:23 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Sep  5 10:42:23 eastwood jackett[31435]:       Request starting HTTP/1.1 GET http://192.168.1.1:9117/api/v2.0/indexers?_=1536165741976
Sep  5 10:42:23 eastwood jackett[31435]: 09-05 10:42:23 Info Request starting HTTP/1.1 GET http://192.168.1.1:9117/api/v2.0/indexers?_=1536165741976
Sep  5 10:42:23 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Sep  5 10:42:23 eastwood jackett[31435]:       Route matched with {action = "Indexers", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole)
Sep  5 10:42:23 eastwood jackett[31435]: 09-05 10:42:23 Info Route matched with {action = "Indexers", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole)
Sep  5 10:42:23 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
Sep  5 10:42:23 eastwood jackett[31435]:       Authorization was successful.
Sep  5 10:42:23 eastwood jackett[31435]: 09-05 10:42:23 Info Authorization was successful.
Sep  5 10:42:23 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Sep  5 10:42:23 eastwood jackett[31435]:       Executing action method Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole) - Validation state: Valid
Sep  5 10:42:23 eastwood jackett[31435]: 09-05 10:42:23 Info Executing action method Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole) - Validation state: Valid
Sep  5 10:42:23 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
Sep  5 10:42:23 eastwood jackett[31435]:       Executed action method Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 2.2953ms.
Sep  5 10:42:23 eastwood jackett[31435]: 09-05 10:42:23 Info Executed action method Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 2.2953ms.
Sep  5 10:42:23 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
Sep  5 10:42:23 eastwood jackett[31435]:       Executing ObjectResult, writing value of type 'System.Linq.Enumerable+SelectIPartitionIterator`2[[Jackett.Common.Indexers.IIndexer, Jackett.Common, Version=0.10.160.0, Culture=neutral, PublicKeyToken=null],[Jackett.Common.Models.DTO.Indexer, Jackett.Common, Version=0.10.160.0, Culture=neutral, PublicKeyToken=null]]'.
Sep  5 10:42:23 eastwood jackett[31435]: 09-05 10:42:23 Info Executing ObjectResult, writing value of type 'System.Linq.Enumerable+SelectIPartitionIterator`2[[Jackett.Common.Indexers.IIndexer, Jackett.Common, Version=0.10.160.0, Culture=neutral, PublicKeyToken=null],[Jackett.Common.Models.DTO.Indexer, Jackett.Common, Version=0.10.160.0, Culture=neutral, PublicKeyToken=null]]'.
Sep  5 10:42:23 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
Sep  5 10:42:23 eastwood jackett[31435]:       Executed action Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole) in 249.8232ms
Sep  5 10:42:23 eastwood jackett[31435]: 09-05 10:42:23 Info Executed action Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole) in 249.8232ms
Sep  5 10:42:23 eastwood jackett[31435]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Sep  5 10:42:23 eastwood jackett[31435]:       Request finished in 256.8795ms 200 application/json; charset=utf-8
Sep  5 10:42:23 eastwood jackett[31435]: 09-05 10:42:23 Info Request finished in 256.8795ms 200 application/json; charset=utf-8

**Comment by aureliensauv** [comment]
I have exactly same problem ! Have you any solution ?

**Comment by flightlevel** [comment]
@tbotcotw @aureliensauv 
Those logs aren't enhanced logs, they are just the regular logs
Have you tried anything from Google
https://www.google.com/search?q=systemd+service+prevent+log+to+syslog
You should be able to set the way you like

**Comment by aureliensauv** [comment]
For me, the real problem is the log level for Microsoft.AspNetCore.*.
I think it's currently set on INFO. Perhaps it's a little more for regular log.

**Comment by tbotcotw** [comment]
@flightlevel 

Thanks for confirming those are just the standard logs. I'll look at filtering them.

**Comment by aureliensauv** [comment]
@tbotcotw have you still the issue with the last version (0.10.446) ?

**Comment by uheow847** [comment]
> [ghost](/ghost)

I'm interested in entirely disabling logging - just too much balloning of the log files even with just regular logging on.  Is there any way to provide a disable logging checkbox option in the settings, or a way to change a config file / .ini or something equivalent to just entirely disable logging altogether?
