### ISSUE TITLE
[1337x] Exception (1337x): Ssl error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER  at /build/mono-5.14.0.177/external/boringssl/ssl/tls_record.c:217: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by Guson79** [Jackett/Jackett#3725]
System: Synology with Docker.
**Jackett version**:  Linuxserver Jackett Version 0.10.117.0 (docker container)
**Mono version** (if not using Windows):  One that came with Jacket docker? 
-------------------------------
I have tried over 10 different versisons of linuxserver jackett docker images. And no matter what tracker I try to configure, it complains about mono.
I assume using docker, its not my synology Mono version that is affected, but the one in Jacket docker image? 

Exception (1337x): Ssl error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER at /build/mono-5.14.0.177/external/boringssl/ssl/tls_record.c:217: An error occurred while sending the request

How can I solve this? no trackers can be setup without throwing this issue.
I have Sonarr, Nzbget, Couchpotato working great in their own containers.
I had a working jacket for 2 years, but suddenly I guess it updated something and now I get this..

thanks in advance.

**Comment by flightlevel** [comment]
If running from docker, it will use the Mono version in the container, so should run without issue. There is heaps of linuxserver jackett users.
I'd try clearing all your jackett related docker containers and images. Then pull the latest image from linuxserver

**Comment by kaso17** [comment]
closing, see #3731
