### ISSUE TITLE
[speedcd] issue setting up Speed.CD

### ISSUE THREAD

**Issue by Kepners** [Jackett/Jackett#3727]
trying to set up Speed.CD. havent changed any of the setting on SPeed.cd to get this error. 

An error occured while updating this indexer>>>

https://pastebin.com/ZKiSW0rT

**Jackett version**:  0.8.1070.0
**Mono version** (if not using Windows):  unknown. Latest?

-------------------------------

**Comment by garfield69** [comment]
speed.cd changed their site's html recently and you will need to upgrade to at least Jackett v0.10.134

**Comment by krazyjakee** [comment]
They have now added a captcha to the login process.
