### ISSUE TITLE
[torrentz2.eu] searching by torrent hash isn't possible

### ISSUE THREAD

**Issue by 07416** [Jackett/Jackett#3736]
**Jackett version**:  0.10.134.0 

[torrentz2.eu](https://torrentz2.eu/) supports searching by the torrent hash, for instance `3d4137dfb332138e539a812e33425a4a36219e66` (https://torrentz2.eu/3d4137dfb332138e539a812e33425a4a36219e66). Using hash in Jackett gives no results.

**Comment by kaso17** [comment]
When you search for a hash you get redirected to the torrent details page (no normal search results page). Jackett can't handle this easily.

#3573 is related.
