### ISSUE TITLE
[torrentz2.eu] Support for advanced search

### ISSUE THREAD

**Issue by 07416** [Jackett/Jackett#3737]
**Jackett version**: 0.10.134.0

https://torrentz2.eu/help

> **Advanced Search**
> 

> * Mozilla Firefox - search for Mozilla and Firefox anywhere in the title and file names
> * "Mozilla Firefox" - search exactly for "Mozilla Firefox"
> * Mozilla | Linux - search for Mozilla or Linux
> * Mozilla Firefox NOT beta - search for Mozilla AND Firefox but NOT beta
> * ^Mozilla - search for titles starting with Mozilla
> * Mozilla added: 7d - search for Mozilla added less than 7 days ago. Available date units: hours, days, months, years
> * Linux added > 5y - search for Linux added more than 5 years ago
> * Linux size > 700m - search for Linux torrents with size bigger than 700megabytes. Available size units: kilo, mega, giga, tera
> * Linux size 700m - 1g - search for Linux torrents in size range of 700m and 1g
> * Linux seed > 100 - search for Linux torrents with more than 100 seeders. Available seed(s,ers) and total peers
> * title: Fedora iso - search only in torrent title for Fedora iso
> * 1222639616 - deep search inside torrent for file with size of 1222639616 bytes

At least searching by the date (`added`), size and only title (`title:`) isn't possible and gives no results.

**Comment by kaso17** [comment]
we were using the andmatch filter before, due to that the search keywords don't work (without it it was returning a lot of garbage results.
Now with 9a071a3457d04b1398aaeabf8f3e7f9392baf84a it will use title: by default and all the extra filter options should work.
