### ISSUE TITLE
[demonoid] Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by nickk024** [Jackett/Jackett#3742]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  latest pre-release
**Mono version** (if not using Windows): 5.10.1.20  

-------------------------------

This is what shows up when I try to connect to Demonoid with my user/pass. Any ideas? Thanks!

**Comment by nickk024** [comment]
But that other one is closed also and was never solved...

**Comment by garfield69** [comment]
works for me on win7, so if you want us to dig deeper then we are going to need a *full enhanced log*. Instructions for obtaining enhanced log.txt are here: https://github.com/Jackett/Jackett#troubleshooting
