### ISSUE TITLE
Won't launch/Required to reinstall to use

### ISSUE THREAD

**Issue by PhatChance52** [Jackett/Jackett#3743]
This doesn't generate an error log, so I'm a bit stumped on how to proceed.

It used to be when I started using Jackett, it was fine, and great and no issues whatsoever. At some point a few months back, it stopped working (started the service, clicked the bookmark, and the page failed to load). So, I reinstalled, and it was fine. But the next day when I went to use it again, same thing happened, and the same solution (reinstall) works every time.

I get that this isn't a critical failure, or anything like that, but it gets pretty annoying having to uninstall and reinstall the program just to use it. if I happen to shut down my PC. 

Any tips on how to sort this out?

**Comment by garfield69** [comment]
Are you on a windows platform running AVAST by any chance?
I've seen a couple tickets (including personal experience on my win7 recently) where AVAST has been silently guaranteeing one of the Jackett modules, which lines up with the symptoms you describe.
So when it next happens that your Jackett stops working, check the jackett folder and look for missing jackettConsole.exe or jackettService.exe programs, and then check your viruschest to see if its been moved there.
