### ISSUE TITLE
Missing torrentday

### ISSUE THREAD

**Issue by Squatchnet** [Jackett/Jackett#3744]
Torrentday has changed from a .com to .it.  Will this and others like eztv be added back?

**Comment by garfield69** [comment]
they are *not gone* from Jackett, and their current domains are defined in the corresponding jackett indexers. Works for me on my win7 platform.

what version of jackett are you on, and on what platform?
consider upgrading to the latest jackett version, currently v0.10.153.

**Comment by Squatchnet** [comment]
v0.10.153 on win10 platform.  I have lost a few torrents over the last week and they are not on the list of torrents when you add them.  These are Torrentday, EZTV, torrentdownload and torrentz2.  I am also using ipvanish vpn

**Comment by garfield69** [comment]
strange. you're telling me that they don't show up on the primary jackett dashboard's *configured Indexers* page, and neither in the *select an indexer to set up* page?

Have you entered anything on the *search* box to restrict your indexer view?

the torrentday indexer is c# code so it could not go missing, and the others you mentioned are yaml code, so you should find them in the `C:\ProgramData\Jackett\Definitions` folder.

**Comment by Squatchnet** [comment]
![capture](https://user-images.githubusercontent.com/25893001/45003120-dcf97c00-afd6-11e8-8c96-a370b6d3c9d7.JPG)

**Comment by garfield69** [comment]
@Squatchnet  have you managed to figured out what is going on here, or is it still a puzzle?

**Comment by Squatchnet** [comment]
Hi - So its seems my VPN is showing connected but isnt if that makes sense..  Switched to another VPN and all working as expected.  :-)
