### ISSUE TITLE
RuTracker: Error Jackett.Common.IndexerException

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#3745]
**Jackett version**:  0.10.153 win7
when using the Jackett Dashboard from my win7 system to *test* **RuTracker**, I get presented with this screen as the test completes:
![image](https://user-images.githubusercontent.com/6933240/45005585-64330800-b048-11e8-8eff-59b34ff4513f.png)
and when I do a *manual search* on the Dashboard with RuTracker I get 0 results and an error flag:
![image](https://user-images.githubusercontent.com/6933240/45005617-83ca3080-b048-11e8-9d6a-14dca099082e.png)
I can confirm I am able to login to RuTracker directly and perform searches successfully.
the redacted log below contains both the *test* and the *manual search* with the *Enhanced Logging* enabled.
[RuTracker.log](https://github.com/Jackett/Jackett/files/2346883/RuTracker.log)

**Comment by xFilosofx** [comment]
Yes, i have same trouble.

**Comment by kaso17** [comment]
they changed some page details, fixed via 7b8de5e28dce4a70f2b03b34995ece9abf47d1aa
