### ISSUE TITLE
Jackett crashes after some hours

### ISSUE THREAD

**Issue by fontes31** [Jackett/Jackett#3747]
Iam using jackett on ubuntu server 16.04 connected to sonarr and radarr.
After some hours, jackett crashes, and i see that on sonarr, informing that cannot connect to tracker.
I checked the disable auto-update, let´s see how it happens today.

**Comment by fontes31** [comment]
Mono Version - 5.14.0.177
After 9 hours of starting jackett, it crashed

**Comment by garfield69** [comment]
may be related to #3653
