### ISSUE TITLE
BeyondHD Freeleech

### ISSUE THREAD

**Issue by Metigoth** [Jackett/Jackett#3748]
BeyondHD stated as 100% Freeleech when tracker has no freeleech it used to be a ratioless tracker about a year ago.

Jackett Version 0.10.134.0

Mono JIT compiler version 5.14.0.177 (tarball Mon Aug 6 09:13:21 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
TLS: __thread
SIGSEGV: altstack
Notifications: epoll
Architecture: amd64
Disabled: none
Misc: softdebug
Interpreter: yes
LLVM: yes(3.6.0svn-mono-/)
GC: sgen (concurrent by default)

-------------------------------

**Comment by kaso17** [comment]
fixed via d0937d3561562b7bc49d601cc315294a50186b20
Do you know if they have some freeleech torrents?

**Comment by Metigoth** [comment]
They do not
