### ISSUE TITLE
[bt-scene] Exception (bt-scene): The operation has timed out.: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by axl7777** [Jackett/Jackett#3749]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:   0.10.160.0
**Mono version** (if not using Windows):  (docker)

-------------------------------

**Comment by garfield69** [comment]
The btscene site has been down for several weeks now. If any one knows if there is a replacement domain for bt-snene.cc please let us know.

**Comment by abetancort** [comment]
So long bt-scene.cc

**Comment by garfield69** [comment]
I've removed the bt-scene indexer from jackett.
in the event it ever shows up again we can always add it back.

**Comment by ldexterldesign** [comment]
Hi @garfield69,

Thanks for follow up

Will that indexer be deleted by jackett from my config in the next update or will I have to delete it manually?

Yours hopefully

**Comment by garfield69** [comment]
yes, when you install the next (pre)release the bt-scene indexer should be automatically deleted.
