### ISSUE TITLE
Error:  Test failed for myanonamouse: Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by poplolnman** [Jackett/Jackett#375]
Hello,
I tried to test the tracker just  yesterday and it worked, but now its not when i test it again. Need help on where to find other logs if they are needed!

**Comment by staraxis** [comment]
I'm getting the same error as I just got a MAM account and it won't work with Jackett

**Comment by d2dyno** [comment]
Confirmed, having this issue as well.

**Comment by kaso17** [comment]
if you can send an invite to kaso1717 -at- gmail.com I can fix it.

**Comment by d2dyno** [comment]
I don't have enough reputation built to send invites yet. Can another user assist with this?

Also, logins are now by email, not username. Could this be a cause?

**Comment by kaso17** [comment]
seems like in the past there was a direct download link in the search results. But it's missing now. That caused the problem.
