### ISSUE TITLE
[nordicbits] Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by wazerstar** [Jackett/Jackett#3750]
So since nordicbits homepage is now nordicb.org its not longer possible to add this tracker, can we get it sorted out some how?

https://github.com/Jackett/Jackett/pull/3552

@hallengreenn maybe you can look into it?

log Added with help from @garfield69 

http://prntscr.com/kqnss2
https://github.com/Jackett/Jackett/files/2350494/log.txt

**Comment by garfield69** [comment]
Huh?
Jackett's nordicbits indexer is already using the site link https://nordicb.org
![image](https://user-images.githubusercontent.com/6933240/45060340-8fbefc80-b0f3-11e8-9ec7-9f810c4f1dc8.png)
so what ever your problem is its not the domain itself but perhaps your local access to it or maybe they have changed their HTML (which I cant test since I don't have a login :-( )?

**Comment by wazerstar** [comment]
@garfield69 I mentioned it here and another person.

https://github.com/Jackett/Jackett/pull/3552#issuecomment-417830915

I can provide you my login, should be no problem if needed,

**Comment by garfield69** [comment]
which version of Jackett are you on?
 the indexer's site link was update from Jackett version v0.10.47 onwards.

**Comment by wazerstar** [comment]
@garfield69 0.10.153.0

**Comment by garfield69** [comment]
absolutely.
the first thing you can do is enable the *enhanced logging* on your jackett dashboard, and click on the *apply server settings* button. (note this enhanced logging setting is reset the next time you restart jackett).

then perform your indexer test.
now look at the log (online via the dashboard, or directly from the log.txt file in the jackett folder) and look for errors.
if you cant make sense of the logs, then i suggest you open the log.txt with a plain text editor, and redact any mention of your username, password, or other personal details, save the file and drag drop the file here so we can take a look.

**Comment by wazerstar** [comment]
@garfield69 like this?
[log.txt](https://github.com/Jackett/Jackett/files/2350494/log.txt)

**Comment by wazerstar** [comment]
@garfield69 Thanks

Added the info to main topic,

**Comment by hallengreenn** [comment]
Hello there,

Okay, so something seems wrong for multiple people apparently. However I still don't have a problem, as mine just works.

How is yours configured?
Mine is configured as the following -

Username: username of course
Password: same
Browser Simulation (Forced): Checked
Injecting headers, Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Injecting headers, Accept-Language: en-US,en;q=0.9,da;q=0.8,de;q=0.7,sv;q=0.6
Injecting headers, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Enable DEV MODE (Developers ONLY): Checked

**Comment by wazerstar** [comment]
@hallengreenn 
Does not work.

Also you cannot test something that cannot be added.

**Comment by wazerstar** [comment]
@hallengreenn 
@garfield69 

I think I found out an bug in jackett, when adding new index and it fails to be added it will of course not show up under your indexer, but if you reboot jackett services the failed index you tried to add will be added and show up.

Here's a log when pressing test with nordicb.org

[log.txt.20180906.00000.txt](https://github.com/Jackett/Jackett/files/2358191/log.txt.20180906.00000.txt)

**Comment by hallengreenn** [comment]
@wazerstar 

> What does your site say, and what did your site say when you ADDED it with and without https?
- Leave it default... https://nordicb.org/

> Many changed their personal hostsfile to reflect to nordicb.org from nordicbits.org a month ago, did you do that, this index added by you reflects to nordicbits.org and not nordicb.org
- No I did not, as it just works now and it's a new install (my jackett + everything else)

> also what theme do you use on the site, with
- Just left it default, I think.
> stylesheet
- DarkV2
> language
- English
> shoutbox
- White
> show medals
- Yes

> Do you login with
> Browse nordicbits using https just this session
- True
>Browse nordicbits using https permanently
- True

Also under Profile > Security > SSL Option, I have 'Only for site browsing'.

I just installed a brand new W10 VM and installed Jackett - 
Here is the log, again no problems.

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/indexers/nordicbits/config?_=1536308948059
09-07 10:29:16 Info Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/indexers/nordicbits/config?_=1536308948059
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Config", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)
09-07 10:29:16 Info Route matched with {action = "Config", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
09-07 10:29:16 Info Authorization was successful.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole) - Validation state: Valid
09-07 10:29:16 Info Executing action method Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole), returned result Microsoft.AspNetCore.Mvc.OkObjectResult in 18.8695ms.
09-07 10:29:16 Info Executed action method Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole), returned result Microsoft.AspNetCore.Mvc.OkObjectResult in 18.8695ms.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'Newtonsoft.Json.Linq.JArray'.
09-07 10:29:16 Info Executing ObjectResult, writing value of type 'Newtonsoft.Json.Linq.JArray'.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole) in 69.9783ms
09-07 10:29:16 Info Executed action Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole) in 69.9783ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 181.9699ms 200 application/json; charset=utf-8
09-07 10:29:16 Info Request finished in 181.9699ms 200 application/json; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://127.0.0.1:9117/api/v2.0/indexers/nordicbits/config application/json 1158
09-07 10:30:13 Info Request starting HTTP/1.1 POST http://127.0.0.1:9117/api/v2.0/indexers/nordicbits/config application/json 1158
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole)
09-07 10:30:13 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole)
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
09-07 10:30:13 Info Authorization was successful.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) with arguments (Jackett.Common.Models.DTO.ConfigItem[]) - Validation state: Valid
09-07 10:30:13 Info Executing action method Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) with arguments (Jackett.Common.Models.DTO.ConfigItem[]) - Validation state: Valid

Validating Settings ...

Validated Setting -- Username (auth) => xxxxxxxxx
Validated Setting -- Password (auth) => xxxxxxxxxxxxxxxxx
Validated Setting -- Max Pages => 4

Validated Setting -- Browser Simulation enabled
Validated Setting -- ACCEPT (header) => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Validated Setting -- ACCEPT-LANG (header) => en-US,en;q=0.9,da;q=0.8,de;q=0.7,sv;q=0.6
Validated Setting -- USER-AGENT (header) => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Deleting Provider Storage folder and all files recursively ...
-> No Storage folder found for this provider !

Getting index page (for cookies).. with https://nordicb.org/

Getting login page (user simulation).. with https://nordicb.org/login.php

Perform loggin.. with https://nordicb.org/takelogin.php

Cookies saved for future uses...

-> Login Success


-> Checking logged-in state....
-> Already logged, continue...


Builded query for "all"... https://nordicb.org/browse.php?search=&searchin=title&incldead=0

Found 17 result(s) (+/- 17) in 1 page(s) for this query !

There are 15 results on the first page !
Torrent #1
ID: xxxxx
Category: 2040 (cat=21)
Seeders: 13
Leechers: 0
Files: 6
Completed: 17
Size: 3.37gb (3618509824 bytes)
Released on: 9/7/2018 8:24:43 AM
Details: https://nordicb.org/details.php?id=xxxxxxxxxxxxxx
Comments Link: https://nordicb.org/details.php?id=xxxx&comonly=1#page1
Download Link: https://nordicb.org/download.php?torrent=xxxxx&torrent_pass=xxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by wazerstar** [comment]
@hallengreenn issue found!

When using anything else than darkv2/darkv2-wide - lightv2/lightv2-wide

 it will fail now if we could all the rest working with it too? 

[](https://image.prntscr.com/image/pg7xfISlRWesHR5xOQc9Vw.png)

**Comment by hallengreenn** [comment]
@wazerstar 

It gives perfect sense, as we are taking the data from 'raw' HTML and translates it to what Jackett understands.
In theory, yes - we can get the rest of them working.

What you need to do is -
-> Match the function 'FindTorrentRows' with the new theme
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/Nordicbits.cs#L679

-> Then you edit the 'tRow.Find' foreach with what Jackett expects (ID, release Name, Category)
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/Nordicbits.cs#L336

I suggest you maybe, add a new setting in the Nordicbits.cs nofiguration, where you can choose Theme?
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataNordicbits.cs

**Comment by wazerstar** [comment]
@hallengreenn yeah I'm not going to do it, just narrowed it down now, not really my responsibility(if i knew 100% what i was doing then I would prob do it), I did not add support, in general there's actually no support yet for the site because the dark theme is not the default one, so it will never work without people knowing what to pick as theme first, or said in another way, I don't know how to do it, so I wont be doing it :)

cheers tho.

**Comment by hallengreenn** [comment]
@wazerstar I will take a look at adding support to the default theme and a prober error when using a non-supported theme, so we can help other people.
However we need to remember that this support is a unsupported way of doing this, small changes by the dev team can make it fail.
i will take a look at it next week to see if we can get it resolved. :)

**Comment by hallengreenn** [comment]
@wazerstar - what a crazy week.
I had the time to look at it, this evening and made a pull request so we can get support for all the themes on the site.
So from now on, there should be no more errors. :)

**Comment by wazerstar** [comment]
> 
> 
> @wazerstar - what a crazy week.
> I had the time to look at it, this evening and made a pull request so we can get support for all the themes on the site.
> So from now on, there should be no more errors. :)

Great! looking forward to :) thanks for doing.

**Comment by wazerstar** [comment]
afaik v3 is not default, its the first dark/white.
