### ISSUE TITLE
Error: using jackett with sickrage

### ISSUE THREAD

**Issue by poplolnman** [Jackett/Jackett#376]
Hi!

Getting this error:

Error on 20160623193550 for BroadcastTheNet.txtSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Indexers.BroadcastTheNet.<PerformQuery>d__7.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\BroadcastTheNet.cs:line 98

I get this when i use Jackett with sickrage's torznab feature.

Sometimes i will get results from btn and other times i will get this error.

**Comment by flightlevel** [comment]
This issue hasn't had activity for a while. If the issue still exists, please reopen and include full logs. https://github.com/Jackett/Jackett#troubleshooting
