### ISSUE TITLE
[Feature request] Add seeds/leechers in btdb

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#3765]
The current BTDB plugin always returns 999 for seeds/leechers.
I propose to return the "popularity" value instead. I know they are different things but is better than nothing.
The issue in the current implementation is there is no way to sort results by seeds/leechers. So many times I'm trying to download dead torrents...

**Comment by garfield69** [comment]
done. the next (pre)release of Jackett will include this request.
