### ISSUE TITLE
No results in Sonarr for anime. Indexer used - Animebytes

### ISSUE THREAD

**Issue by stephanie00100** [Jackett/Jackett#3766]
Jackett Version - 0.10.134.0
Screenshots of settings/results -

https://imgur.com/a/2NWsGWL

Jackett is able to see the results just fine for the different seasons. Sonarr doesn't show anything. Forgot to include indexer settings, 5070 is filled into the anime category and the indexer tests just fine.

Sonarr debug log

18-9-1 21:10:37.9|Debug|Api|[GET] /api/v3/tag: 200.OK (0 ms)

18-9-1 21:10:37.9|Debug|Api|[GET] /api/v3/qualityprofile: 200.OK (5 ms)

18-9-1 21:10:37.9|Debug|Api|[GET] /api/v3/config/ui: 200.OK (0 ms)

18-9-1 21:10:37.9|Debug|Api|[GET] /api/v3/system/status: 200.OK (1 ms)

18-9-1 21:10:37.9|Debug|Api|[GET] /api/v3/languageprofile: 200.OK (1 ms)

18-9-1 21:10:37.9|Debug|Api|[GET] /api/v3/series: 200.OK (47 ms)

18-9-1 21:10:38.1|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)

18-9-1 21:10:38.1|Debug|Api|[GET] /api/v3/log/file: 200.OK (0 ms)

18-9-1 21:10:38.2|Debug|Api|[GET] /api/v3/queue/status: 200.OK (84 ms)

18-9-1 21:10:41.7|Debug|Api|[GET] /api/v3/config/host: 200.OK (7 ms)

18-9-1 21:10:53.7|Debug|Api|[PUT] /api/v3/config/host: 202.Accepted (38 ms)

18-9-1 21:10:53.8|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)

18-9-1 21:10:53.8|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)

18-9-1 21:10:59.8|Debug|Api|[GET] /api/v3/wanted/missing?page=1&pageSize=20&sortDirection=descending&sortKey=airDateUtc&monitored=true: 200.OK (74 ms)

18-9-1 21:11:00.1|Debug|Api|[GET] /api/v3/queue/details?episodeIds=4558&episodeIds=4557&episodeIds=4556&episodeIds=4555&episodeIds=4554&episodeIds=4553&episodeIds=4552&episodeIds=4551&episodeIds=4550&episodeIds=4549&episodeIds=4548&episodeIds=4547&episodeIds=4546&episodeIds=4545&episodeIds=4544&episodeIds=4543&episodeIds=4542&episodeIds=4541&episodeIds=4540&episodeIds=4539: 200.OK (3 ms)

18-9-1 21:11:08.0|Debug|Api|[GET] /api/v3/config/host: 200.OK (2 ms)

18-9-1 21:11:14.1|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)

18-9-1 21:11:14.1|Debug|Api|[GET] /api/v3/system/status: 200.OK (0 ms)

18-9-1 21:11:14.2|Debug|Api|[GET] /api/v3/diskspace: 200.OK (77 ms)

18-9-1 21:11:16.6|Debug|Api|[GET] /api/v3/log/file: 200.OK (1 ms)

18-9-1 21:11:19.6|Debug|Api|[GET] /api/v3/series: 200.OK (28 ms)

18-9-1 21:11:19.8|Warn|MediaCoverMapper|File C:\ProgramData\Sonarr\MediaCover\34\poster.jpg not found

18-9-1 21:11:21.8|Debug|Api|[GET] /api/v3/queue/details?seriesId=35: 200.OK (7 ms)

18-9-1 21:11:21.8|Debug|Api|[GET] /api/v3/episodeFile?seriesId=35: 200.OK (9 ms)

18-9-1 21:11:21.8|Debug|Api|[GET] /api/v3/episode?seriesId=35: 200.OK (19 ms)

18-9-1 21:11:44.1|Debug|Api|[GET] /api/v3/queue/details?seriesId=35: 200.OK (3 ms)

18-9-1 21:11:46.4|Debug|Api|[POST] /api/v3/command: 201.Created (3 ms)

18-9-1 21:11:46.4|Info|NzbSearchService|Searching 1 indexers for [Bleach : 343]

18-9-1 21:11:46.4|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+343

18-9-1 21:11:50.1|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 343] from 1 indexers

18-9-1 21:11:50.1|Info|DownloadDecisionMaker|No results found

18-9-1 21:11:50.2|Info|NzbSearchService|Searching 1 indexers for [Bleach : 344]

18-9-1 21:11:50.2|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+344

18-9-1 21:11:50.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 344] from 1 indexers

18-9-1 21:11:50.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:11:50.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 345]

18-9-1 21:11:51.0|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+345

18-9-1 21:11:52.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 345] from 1 indexers

18-9-1 21:11:52.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:11:52.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 346]

18-9-1 21:11:52.9|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+346

18-9-1 21:11:54.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 346] from 1 indexers

18-9-1 21:11:54.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:11:54.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 347]

18-9-1 21:11:55.0|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+347

18-9-1 21:11:56.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 347] from 1 indexers

18-9-1 21:11:56.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:11:56.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 348]

18-9-1 21:11:56.9|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+348

18-9-1 21:11:58.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 348] from 1 indexers

18-9-1 21:11:58.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:11:58.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 349]

18-9-1 21:11:58.9|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+349

18-9-1 21:12:00.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 349] from 1 indexers

18-9-1 21:12:00.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:00.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 350]

18-9-1 21:12:00.9|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+350

18-9-1 21:12:02.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 350] from 1 indexers

18-9-1 21:12:02.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:02.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 351]

18-9-1 21:12:02.9|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+351

18-9-1 21:12:04.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 351] from 1 indexers

18-9-1 21:12:04.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:04.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 352]

18-9-1 21:12:05.0|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+352

18-9-1 21:12:06.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 352] from 1 indexers

18-9-1 21:12:06.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:06.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 353]

18-9-1 21:12:06.9|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+353

18-9-1 21:12:08.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 353] from 1 indexers

18-9-1 21:12:08.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:08.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 354]

18-9-1 21:12:09.0|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+354

18-9-1 21:12:10.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 354] from 1 indexers

18-9-1 21:12:10.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:10.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 355]

18-9-1 21:12:11.0|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+355

18-9-1 21:12:12.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 355] from 1 indexers

18-9-1 21:12:12.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:13.0|Info|NzbSearchService|Searching 1 indexers for [Bleach : 356]

18-9-1 21:12:13.0|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+356

18-9-1 21:12:14.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 356] from 1 indexers

18-9-1 21:12:14.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:14.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 357]

18-9-1 21:12:14.9|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+357

18-9-1 21:12:16.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 357] from 1 indexers

18-9-1 21:12:16.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:17.0|Info|NzbSearchService|Searching 1 indexers for [Bleach : 358]

18-9-1 21:12:17.0|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+358

18-9-1 21:12:18.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 358] from 1 indexers

18-9-1 21:12:18.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:18.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 359]

18-9-1 21:12:19.0|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+359

18-9-1 21:12:20.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 359] from 1 indexers

18-9-1 21:12:20.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:20.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 360]

18-9-1 21:12:20.9|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+360

18-9-1 21:12:22.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 360] from 1 indexers

18-9-1 21:12:22.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:22.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 361]

18-9-1 21:12:22.9|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+361

18-9-1 21:12:24.5|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 361] from 1 indexers

18-9-1 21:12:24.5|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:24.5|Info|NzbSearchService|Searching 1 indexers for [Bleach : 362]

18-9-1 21:12:24.5|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+362

18-9-1 21:12:27.0|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 362] from 1 indexers

18-9-1 21:12:27.0|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:27.0|Info|NzbSearchService|Searching 1 indexers for [Bleach : 363]

18-9-1 21:12:27.0|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+363

18-9-1 21:12:28.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 363] from 1 indexers

18-9-1 21:12:28.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:28.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 364]

18-9-1 21:12:28.9|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+364

18-9-1 21:12:30.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 364] from 1 indexers

18-9-1 21:12:30.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:30.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 365]

18-9-1 21:12:30.9|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+365

18-9-1 21:12:32.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 365] from 1 indexers

18-9-1 21:12:32.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:32.9|Info|NzbSearchService|Searching 1 indexers for [Bleach : 366]

18-9-1 21:12:32.9|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Bleach+366

18-9-1 21:12:34.9|Debug|NzbSearchService|Total of 0 reports were found for [Bleach : 366] from 1 indexers

18-9-1 21:12:34.9|Info|DownloadDecisionMaker|No results found

18-9-1 21:12:34.9|Info|SeasonSearchService|Season search completed. 0 reports downloaded.

18-9-1 21:12:57.5|Debug|Api|[GET] /api/v3/tag: 200.OK (5 ms)

18-9-1 21:12:57.5|Debug|Api|[GET] /api/v3/qualityprofile: 200.OK (2 ms)

18-9-1 21:12:57.6|Debug|Api|[GET] /api/v3/config/ui: 200.OK (0 ms)

18-9-1 21:12:57.6|Debug|Api|[GET] /api/v3/system/status: 200.OK (1 ms)

18-9-1 21:12:57.6|Debug|Api|[GET] /api/v3/languageprofile: 200.OK (4 ms)

18-9-1 21:12:57.6|Debug|Api|[GET] /api/v3/series: 200.OK (52 ms)

18-9-1 21:12:57.7|Debug|Api|[GET] /api/v3/queue/status: 200.OK (1 ms)

18-9-1 21:12:57.7|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)

18-9-1 21:12:57.8|Debug|Api|[GET] /api/v3/episodeFile?seriesId=35: 200.OK (4 ms)

18-9-1 21:12:57.8|Debug|Api|[GET] /api/v3/episode?seriesId=35: 200.OK (15 ms)

18-9-1 21:12:57.8|Debug|Api|[GET] /api/v3/queue/details?seriesId=35: 200.OK (0 ms)

18-9-1 21:13:07.6|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)

18-9-1 21:13:07.6|Debug|Api|[GET] /api/v3/system/status: 200.OK (4 ms)

18-9-1 21:13:07.7|Debug|Api|[GET] /api/v3/diskspace: 200.OK (76 ms)

18-9-1 21:13:09.9|Debug|Api|[GET] /api/v3/series: 200.OK (40 ms)

18-9-1 21:13:10.0|Warn|MediaCoverMapper|File C:\ProgramData\Sonarr\MediaCover\34\poster.jpg not found

18-9-1 21:13:10.8|Debug|Api|[GET] /api/v3/episodeFile?seriesId=35: 200.OK (5 ms)

18-9-1 21:13:10.8|Debug|Api|[GET] /api/v3/queue/details?seriesId=35: 200.OK (4 ms)

18-9-1 21:13:10.9|Debug|Api|[GET] /api/v3/episode?seriesId=35: 200.OK (19 ms)

18-9-1 21:13:14.1|Info|RssSyncService|Starting RSS Sync

18-9-1 21:13:14.1|Warn|FetchAndParseRssService|No available indexers. check your configuration.

18-9-1 21:13:14.1|Info|DownloadDecisionMaker|No results found

18-9-1 21:13:14.1|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0

18-9-1 21:13:14.1|Debug|PendingReleaseService|Removing failed releases from pending

18-9-1 21:13:14.2|Debug|Api|[GET] /api/v3/queue/details?seriesId=35: 200.OK (1 ms)

18-9-1 21:13:26.6|Debug|Api|[GET] /api/v3/health: 200.OK (1 ms)

18-9-1 21:13:26.6|Debug|Api|[GET] /api/v3/system/status: 200.OK (1 ms)

18-9-1 21:13:26.7|Debug|Api|[GET] /api/v3/diskspace: 200.OK (78 ms)

18-9-1 21:13:28.2|Debug|Api|[GET] /api/v3/log/file: 200.OK (1 ms)

**Comment by kaso17** [comment]
I can't find any single episode torrents for Bleach on AB. So the result is expected.

**Comment by ne0ark** [comment]
This is a bug If you set the Series Type to Standard it will work.

**Comment by Elehiggle** [comment]
Yes, it is a bug which needs fixing.
