### ISSUE TITLE
Jackett 0.10.164 not installing on windows server 2016

### ISSUE THREAD

**Issue by barbidule** [Jackett/Jackett#3772]
Hi !
Tried to install version 0.10.164 on  a windows server 2016, but nothing happens when executing the installer.

**Comment by garfield69** [comment]
did you figure out what was going on or do you still have this issue?

When you say nothing happens, you mean that you launched the installer and you don't get a gui presenting you with installation options?
![image](https://user-images.githubusercontent.com/6933240/45569994-618caa00-b8b5-11e8-9684-e288b1ad0f96.png)
do you get any sort of notification, error message, a popup with something?
which installer did you download to run?
check if it is blocked, by right clicking on the installer and go to "Properties" > check "Unblock" option > click "Apply" ?
have you checked your system events log for a related event record?

**Comment by barbidule** [comment]
The file was indeed blocked : 
![image](https://user-images.githubusercontent.com/6185569/45580916-fcc25700-b896-11e8-96bd-8b42f0fca678.png)

Thanks for your help !
