### ISSUE TITLE
[polishsource] Exception (polishsource): Login failed: No form found on https://polishsource.cz/login.php using form selector form[action=

### ISSUE THREAD

**Issue by FloydKulis** [Jackett/Jackett#3773]
![image](https://user-images.githubusercontent.com/37215675/45242322-c7929380-b2ef-11e8-851f-9bf401ba1ffd.png)

![image](https://user-images.githubusercontent.com/37215675/45242265-a467e400-b2ef-11e8-8bec-9bdae1016939.png)

**Jackett version**:  Jackett Version 0.10.164.0
**Mono version** (if not using Windows):  5.12

-------------------------------

**Comment by kaso17** [comment]
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
