### ISSUE TITLE
[Feature Request] Support for OpenPGP Keyserver Search

### ISSUE THREAD

**Issue by annomatik** [Jackett/Jackett#3774]
Apparently, some genius put magnet links into the OpenPGP Keyservers of MIT, Surfnet and others. They seem to be technically irremoveable, so that's pretty cool. And the OpenPGP Keyservers are searchable, too...

Here's the article:

https://torrentfreak.com/openpgp-keyservers-now-store-irremovable-torrent-magnet-links-180907/

Here's the search result for "hdrip" on the MIT server, as refered to by the article:

https://pgp.mit.edu/pks/lookup?search=hdrip&op=index

**Comment by kaso17** [comment]
I don't think this will work very long.
Closing this for now.
If it really becomes a thing please reopen the issue.
