### ISSUE TITLE
Yggtorrent force sort order by age desc

### ISSUE THREAD

**Issue by gotson** [Jackett/Jackett#3775]
**Jackett version**:  0.10.153.0
**Mono version** (if not using Windows):  5.8.0.108

-------------------------------

The indexer Yggtorrent doesn't sort searches by age by default, thus when using Jackett's RSS feeds, the most recent results do not appear first.

I understand some indexers could provide pagination and that Jackett could tap into that, but i'm asking for something different.

Would it be possible to have Yggtorrent searches be sorted by default by age in descending order ?
It is achievable via URL parameter, for example that's the default search:
https://www.yggtorrent.is/engine/search?name=pack+magazines&description=&file=&uploader=&category=2140&sub_category=2156&do=search

and that's the corresponding search, but sorted by age descending:
https://www.yggtorrent.is/engine/search?name=pack+magazines&description=&file=&uploader=&category=2140&sub_category=2156&do=search&order=desc&sort=publish_date

Would it be possible to add the following URL parameter `&order=desc&sort=publish_date` to all searches by default?

**Comment by garfield69** [comment]
done. the next (pre)release will include this request.
