### ISSUE TITLE
[REQ] new tracker (desitorrents.com)

### ISSUE THREAD

**Issue by Sheryars** [Jackett/Jackett#378]
can you kindly add http://desitorrents.com 

im sure there are a lot of indians/pakis waiting to get this tracker on jackett.

**Comment by kaso17** [comment]
Please send an invite to kaso1717 -at- gmail.com

**Comment by Sheryars** [comment]
sent you mail on login. they dont have invite so I have sent you my username and password

**Comment by RaNaMaster** [comment]
any up date on this tracker

**Comment by kaso17** [comment]
For the record: their search engine is not very good, see http://www.desitorrents.com/forums/showthread.php?p=5752397#post5752397

**Comment by ogjfie231** [comment]
DesiTorrents has come back up at https://desitorrents.tv. It looks like they are using TBDev now

Registration is currently open at https://desitorrents.tv/register.php

**Comment by shakir87** [comment]
Any update on adding this tracker?

**Comment by darthShadow** [comment]
Any updates?

**Comment by RaNaMaster** [comment]
Hey Kaso13 i have some invites for you where do i send it to

**Comment by mandu-man** [comment]
Any update on this?
Or any way for us to help?

**Comment by kaso17** [comment]
Given the change to a standard tracker software it shouldn't be hard to get this implemented as a cardigann definition indexer.
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

**Comment by Sheryars** [comment]
Would highly appreciate if you could add desitorrents to Jackett. We really need a good Bollywood tracker

**Comment by Sheryars** [comment]
I would like to make a donation too. Kindly let me know how to do it

**Comment by m3ntalsp00n** [comment]
If someone sends me some details for the torrent happy to add it.

**Comment by shakir87** [comment]
> If someone sends me some details for the torrent happy to add it.

What do you need? I can send you an invite to the tracker.

**Comment by m3ntalsp00n** [comment]
Rego is currently closed - so that'd be good thanks.

**Comment by Sheryars** [comment]
> Rego is currently closed - so that'd be good thanks.

how do i send  you the userID and password?

**Comment by m3ntalsp00n** [comment]
Feel free to send it here: m3ntalsp00n@yahoo.com

**Comment by kaso17** [comment]
added via #4354.
Thank you @m3ntalsp00n

**Comment by srinivasravuri** [comment]
Can anyone please send me the invite to join the desitorrents?
Thanks

**Comment by srinivasravuri** [comment]
srinivas_ravuri@yahoo.com

**Comment by average6409** [comment]
could you send me an invite to desitorrents.tv too?

**Comment by average6409** [comment]
> sent mail
could you send me an invite to desitorrents.tv too?

gary.capstone@gmail.com

**Comment by cadatoiva** [comment]
@average6409 this is not a tracker invite forum. As such it is not appropriate to ask for an invite to a tracker unless you are a maintainer dev who needs one in order to fix an active issue.

**Comment by average6409** [comment]
@cadatoiva didn't mean any disrespect, just wanted to ask if you know how I could get access to the site?

**Comment by cadatoiva** [comment]
I do not know, and this ticket is more than a year old. Clicking the link, I'm getting an NXDOMAIN error as well, so the site may be down.

**Comment by garfield69** [comment]
https://desitorrents.tv/ returning `back soon`

**Comment by ilike2burnthing** [comment]
Leaving this open for another couple of weeks, as apparently `DT WILL BE BACK REAL SOON`.

**Comment by ilike2burnthing** [comment]
Site now just times out. Looks like it may be dead - https://torrentinvites.org/f31/desitorrents-news-589838/

**Comment by garfield69** [comment]
v0.17.826

**Comment by geek-baba** [comment]
Its back up now, could we please add them back?

**Comment by geek-baba** [comment]
> Site now just times out. Looks like it may be dead - https://torrentinvites.org/f31/desitorrents-news-589838/

It just came back online today.

**Comment by geek-baba** [comment]
@garfield69 thanks for adding it back! How long till I can add them back, it was deleted from my list of indexers and now I still dont see the option to add them!

**Comment by garfield69** [comment]
>How long till I can add them back,

I'll post here with the version that has the reversal. I expect to publish in about 4 or 5 hours from now.

**Comment by garfield69** [comment]
v0.17.828

**Comment by geek-baba** [comment]
> v0.17.828

Thanks its back now!

**Comment by ilike2burnthing** [comment]
https://desitorrents.tv/ - 503 - SERVICE UNAVAILABLE

**Comment by geek-baba** [comment]
Site is moving to unit3d should be back in few days

**Comment by geek-baba** [comment]
Site is back up now, what is needed to update it from gezzele to unit3d?

**Comment by garfield69** [comment]
>what is needed to update it from Gazelle to unit3d?

Only patience while we wait for @ilike2burnthing (who should still have an active account on the site) to update the indexer with the unit3d template.

**Comment by garfield69** [comment]
v0.18.838

**Comment by garfield69** [comment]
v0.18.845
