### ISSUE TITLE
[ilcorsaroblu] Exception (ilcorsaroblu): Got redirected to another domain. Try changing the indexer URL to https://www.ilcorsaroblu.org/.: Parse error (Test)

### ISSUE THREAD

**Issue by trofio** [Jackett/Jackett#3785]
Exception (ilcorsaroblu): Got redirected to another domain. Try changing the indexer URL to https://www.ilcorsaroblu.org/.: Parse error

I change the URL to "https://www.ilcorsaroblu.org" , when press "okay" a pop-up says that the change is ok but it's not true because the URL remain "https://www.ilcorsaroblu.info"

**Comment by garfield69** [comment]
the *ilcorsaroblu* indexer was changed to **.org** beginning with Jackett v0.10.69 through to the current v0.10.164 
what version are you on, perhaps you should consider upgrading if you are on an earlier release.

**Comment by trofio** [comment]
Version 0.8.1070.0
i need to upgrade, but the "check for updates" button do nothing.
Is there a guide to upgrade manually?

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett#installation-on-windows
https://github.com/Jackett/Jackett#installation-on-linux
https://github.com/Jackett/Jackett#installation-on-linux-via-ansible
https://github.com/Jackett/Jackett#installation-on-macos
https://github.com/Jackett/Jackett#installation-using-docker
https://github.com/Jackett/Jackett#installation-on-synology

**Comment by trofio** [comment]
upgrade done, now works perfectly.
Thank you garfield69!
