### ISSUE TITLE
PirateBay URL update

### ISSUE THREAD

**Issue by neuman1812** [Jackett/Jackett#3787]
The piratebay.org url no longer works.

You can use the updated URL of piratebay.online  or thepiratebay.asia/

**Comment by garfield69** [comment]
It may not work for you because of your ISP provider blocking it, but the **.org** domain is still the official site address and works fine for the rest of us, so we will not be changing the default TPB jackett indexer site link.

**Comment by neuman1812** [comment]
appears to be a hit or miss with the ISP.  I run over a PIA vpn,  east coast, west coast, texas and EU servers are unable to connect.  I was able to get a German server to connect.

Thanks.
