### ISSUE TITLE
YTS - Cannot Add as indexer

### ISSUE THREAD

**Issue by bumsey** [Jackett/Jackett#3789]
I am unable to add YTS as an indexer, checking .config/Jackett/Indexers shows that there is no .json or .json.bak files being created for YTS either.

Running on Ubuntu 16.04.5 LTS container via proxmox

[log.txt](https://github.com/Jackett/Jackett/files/2372363/log.txt)

**Comment by garfield69** [comment]
the log shows that you are having issues accessing the YTS API.
try using your browser with https://yts.am/api/v2/list_movies.json?
do you get a response?
if it works, try Jackett again, it might have been a temporary *out of service* issue with YTS.
Let us know how you go.

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file in the Jackett folder
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by bumsey** [comment]
Full enhanced log attached as requested

[log.txt](https://github.com/Jackett/Jackett/files/2387119/log.txt)

**Comment by bumsey** [comment]
I can confirm that I get results from all of the links on my browser, I also pinged the websites from the container that runs Jackett and received responses however running the test on Jackett still results in a failure. I have not seen any cloudflare challenges or ISP blocking.
