### ISSUE TITLE
New Tracker Request - Nostalgic.is (vhstapes)

### ISSUE THREAD

**Issue by vitale333** [Jackett/Jackett#3795]
Please add support for https://nostalgic.is.

It is a tracker dealing with cartoons, video games, and the Howard Stern Show

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by garfield69** [comment]
@deecypher wrote:

I would like to add Nostalgic.is as a tracker with Jackett. It is a private tracker but I can provide one of your devs an invite code, so please provide me with an email address.

As for the mapping, I am not personally involved with the site but they have provided the following page as a reference: https://github.com/Empornium/Luminance/

I am not a dev nor do I work for the website, just an avid fan. I can be a go-between if necessary.

Please let me know if you require any more details to get this site attached.

Many thanks

**Comment by deecypher** [comment]
Thanks @garfield69 for consolidating this new tracker request. I don't have HTML/CSS skills to do what was suggested earlier, but I do have an invite for your team if you could possibly assist in adding this tracker.

**Comment by BrandonG777** [comment]
+1 on this. invite available if needed. I might dig into the HTML/CSS stuff next week if I can find the time.

**Comment by garfield69** [comment]
If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by deecypher** [comment]
Hi Garfield, I've sent you an invite. It expires in 3 days. Thanks!

**Comment by garfield69** [comment]
No signs of your email, I've check the spam folder too.
if you are sending the invite from within the nostalgic site to `garfield69@outlook.com`, its possible the outlook.com is blocked. you could try `garfieldsixtynine@gmail.com` instead.
But if you are using your own email service then did you get an undelivered reply?

**Comment by deecypher** [comment]
Hi there @garfield69, yes the invite is sent from within the site itself. I've tried your alternative email address, so hopefully you'll get the invite this time.

**Comment by garfield69** [comment]
Registration and login successful. thank you.

**Comment by garfield69** [comment]
try out jackett v0.10.731.
unfortunately I have not cracked the login yet, the site appears to have a bots are prohibited policy.
so I've had to resort to using the cookie method for now.

**Comment by deecypher** [comment]
Thanks @garfield69 for that! You rock!

**Comment by garfield69** [comment]
cracked the bot-detection issue with 90d0f5b2e0c1ff7ab520dedb29cd1d0f3c61d6c4 so now the nostalgic indexer uses the regular username and password login method. :-) Jackett pre-release 0.10.732

**Comment by garfield69** [comment]
nostalgic.to returning ERR_NAME_NOT_RESOLVED
is there a new domain or is the site gone?

**Comment by deecypher** [comment]
I just checked and the site is still active at the same domain. I’m not sure why you’re getting an error...

**Comment by garfield69** [comment]
could you post the full url (from the browser address bar) you used to access the site. thanks.

**Comment by deecypher** [comment]
https://nostalgic.is/

**Comment by garfield69** [comment]
Ahh. back to the .is domain!
at the time I created the indexer it was using .to and I did not think to check it might go back to .is
I'll update the indexer 
Thanks.

**Comment by garfield69** [comment]
https://nostalgic.is/ currently offline with
```
Server kept getting overloaded and bogging out due to lack of resources. Going to make adjustments. tracker online.
```

**Comment by garfield69** [comment]
nostalgic.is new redirects to is a dead end that just has [irc.dejatoons.net #nostalgic](https://kiwiirc.com/client?settings=2b1bc9007b9a0f6227ab505f15f0922c) on it.

anyone have an irc a/c and can find out if nostangic has moved to a new domain or had closed for good?

**Comment by deecypher** [comment]
From the looks of it, they're launching a new domain "vhstapes.org" in the new year and are carrying over user accounts.

> vhstapes.org , applications will go online Jan 1st 2020. Your stats carry over, first wave 100* users. Will be a steady task from our storages and user storages to replinish archive. Everything will be new, rules and all.

**Comment by garfield69** [comment]
thanks for the news.

**Comment by garfield69** [comment]
https://vhstapes.org/ returning `Not such Host is known`.
Site gone, broken or moved to a new domain?

**Comment by BrandonG777** [comment]
gone for good, but they've said that before, so who knows.
