### ISSUE TITLE
[New Tracker REQ] Torrentcouch

### ISSUE THREAD

**Issue by ward0** [Jackett/Jackett#3797]
Hello,

Could you please add this public open tracker.
the website is https:torrentcouch.com

Thanks in advance.

-------------------------------

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by ward0** [comment]
@garfield69 Thanks for the work!

**Comment by garfield69** [comment]
deleting torrentcouch.
they have switched to ozirum.com which supplies only streaming or direct downloads via 3rd party sites.
no .torrent or magnet available. 
Thus no longer suitable as a Jackett indexer.
