### ISSUE TITLE
[transmithenet] Exception (transmithenet): Object reference not set to an instance of an object: Parse error (Test)

### ISSUE THREAD

**Issue by hostile131313** [Jackett/Jackett#3799]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by hostile131313** [comment]
Let me know if you need any info and how to supply it

**Comment by hostile131313** [comment]
With all correct values enerered I get this error when testing connection.

**Comment by flightlevel** [comment]
@hostile131313 as per the template, an enhanced log is needed

**Comment by hostile131313** [comment]
I turned on the enhanced logging.  Do I just copy the text in red or the whole log ?  How do I know cookies and passwords are not in it ?  thanks

**Comment by garfield69** [comment]
Remember after enabling the enhanced logging switch, to also click on the *apply server settings* button.
Then repeat your test.
Locate the log.txt file in the Jackett folder, and using a plain text editor, redact your username, passwords, and any other confidential info. 
Then save and drag-drop it here.
Also remember that the enhanced logging switch is reset the next time Jackett is started.
