### ISSUE TITLE
Daemonoid.pw " Configuration failed: Specified argument was out of the range of valid values. Parameter name: index"

### ISSUE THREAD

**Issue by ScouseTS** [Jackett/Jackett#381]
Hi,

Just installed Jackett alongside Sonarr on my server 2012 machine. When attempting to add Daemonoid as a indexer I'm getting:

" Configuration failed: Specified argument was out of the range of valid values. Parameter name: index"

Does Jackett require IIS role installed in order to play nicely?

Keep up the good work :)

**Comment by d2dyno** [comment]
This has already been reported and confirmed as an issue here: https://github.com/Jackett/Jackett/issues/365

Please be sure to search for reported issues before starting new ones :)
