### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down.: Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by joshburgess79** [Jackett/Jackett#3810]
Log:

Error | Jackett.Common.IndexerException: Exception (thepiratebay): Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down. ---> System.Exception: Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down.   at Jackett.Common.Indexers.BaseWebIndexer.CheckTrackerDown (Jackett.Common.Utils.Clients.WebClientStringResult response) [0x000ea] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:583    at Jackett.Common.Indexers.BaseWebIndexer+<RequestStringWithCookies>d__5.MoveNext () [0x000d4] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:448  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Indexers.CardigannIndexer+<PerformQuery>d__29.MoveNext () [0x007dd] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:1213  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x00047] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:333     --- End of inner exception stack trace ---   at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x000e6] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:353  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x00024] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:817  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x00059] in C:\projects\jackett\src\Jackett.Common\Services\IndexerManagerService.cs:222  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Server.Controllers.IndexerApiController+<Test>d__15.MoveNext () [0x000e1] in C:\projects\jackett\src\Jackett.Server\Controllers\IndexerApiController.cs:141  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <f5622e7f79be469e83d9e2bde9addd07>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x00042] in C:\projects\jackett\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:29
-- | --

Result of curl:

* Rebuilt URL to: https://thepiratebay.org/
*   Trying 104.27.217.28...
* TCP_NODELAY set
* Connected to thepiratebay.org (104.27.217.28) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=ssl778319.cloudflaressl.com
*  start date: Aug 11 00:00:00 2018 GMT
*  expire date: Feb 17 23:59:59 2019 GMT
*  subjectAltName: host "thepiratebay.org" matched cert's "thepiratebay.org"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x56435577a8e0)
> GET / HTTP/2
> Host: thepiratebay.org
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Sat, 15 Sep 2018 15:57:50 GMT
< content-type: text/html;charset=UTF-8
< set-cookie: __cfduid=d3d90c85e5f1c534f6d5fc16dc55c95901537027069; expires=Sun, 15-Sep-19 15:57:49 GMT; path=/; domain=.thepiratebay.org; HttpOnly
< set-cookie: PHPSESSID=5d7794687c6eee0ad78a1003928f1bb9; path=/; domain=.thepiratebay.org
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: private, max-age=10800, pre-check=10800
< last-modified: Tue, 13 Jun 2017 21:19:24 GMT
< set-cookie: language=en_EN; expires=Sun, 15-Sep-2019 15:57:50 GMT; Max-Age=31536000; path=/; domain=.thepiratebay.org
< vary: Accept-Encoding
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 45ac4a8e587e5dec-BNA
< 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Download music, movies, games, software! The Pirate Bay - The galaxy's most resilient BitTorrent site</title>
    <meta name="description" content="Download music, movies, games, software and much more. The Pirate Bay is the galaxy's most resilient BitTorrent site.">
    <meta name="keywords" content="mp3, avi, bittorrent, torrent, torrents, movies, music, games, applications, apps, download, upload, share, kopimi, magnets, magnet">
    <meta name="google-site-verification" content="bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs" />
    <meta name="popwin" content="popwin-verification" />
    
    <link rel="stylesheet" href="//thepiratebay.org/static/css/main.css">
    <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="Search The Pirate Bay">
    <link rel="alternate" hreflang="en" href="/language/en_EN">
    <link rel="alternate" hreflang="sv" href="/language/sv_SE">
    <link rel="alternate" hreflang="nb" href="/language/nb_NO">
    <link rel="alternate" hreflang="nn" href="/language/nn_NO">
    <link rel="alternate" hreflang="da" href="/language/da_DK">
    <link rel="alternate" hreflang="fi" href="/language/fi_FI">
    <link rel="alternate" hreflang="is" href="/language/is_IS">
    <link rel="alternate" hreflang="nl" href="/language/nl_NL">
    <link rel="alternate" hreflang="de" href="/language/de_DE">
    <link rel="alternate" hreflang="it" href="/language/it_IT">
    <link rel="alternate" hreflang="es" href="/language/es_ES">
    <link rel="alternate" hreflang="pt" href="/language/pt_PT">
    <link rel="alternate" hreflang="pt" href="/language/pt_BR">
    <link rel="alternate" hreflang="fr" href="/language/fr_FR">
    <link rel="alternate" hreflang="pl" href="/language/pl_PL">
    <link rel="alternate" hreflang="hu" href="/language/hu_HU">
    <link rel="alternate" hreflang="el" href="/language/el_GR">
    <link rel="alternate" hreflang="tr" href="/language/tr_TR">
    <link rel="alternate" hreflang="ru" href="/language/ru_RU">
    <link rel="alternate" hreflang="sk" href="/language/sk_SK">
    <link rel="alternate" hreflang="ca" href="/language/ca_ES">
    <link rel="alternate" hreflang="he" href="/language/he_IL">
    <link rel="alternate" hreflang="ja" href="/language/ja_JP">
    <link rel="alternate" hreflang="bg" href="/language/bg_BG">
    <link rel="alternate" hreflang="et" href="/language/et_EE">
    <link rel="alternate" hreflang="ar" href="/language/ar_EG">
    <link rel="alternate" hreflang="sr" href="/language/sr_YU">
    <link rel="alternate" hreflang="zh" href="/language/zh_CN">
    <link rel="alternate" hreflang="cs" href="/language/cs_CZ">
    <link rel="alternate" hreflang="sl" href="/language/sl_SI">
    <link rel="alternate" hreflang="uk" href="/language/uk_UA">
    <link rel="alternate" hreflang="ms" href="/language/ms_MY">
    <link rel="alternate" hreflang="bn" href="/language/bn_IN">
    <link rel="alternate" hreflang="sq" href="/language/sq_AL">
    <link rel="alternate" hreflang="hr" href="/language/hr_HR">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/100" title="Audio">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/101" title="Audio - Music">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/102" title="Audio - Audio books">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/103" title="Audio - Sound clips">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/104" title="Audio - FLAC">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/199" title="Audio - Other">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/200" title="Video">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/201" title="Video - Movies">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/202" title="Video - Movies DVDR">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/203" title="Video - Music videos">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/204" title="Video - Movie clips">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/205" title="Video - TV shows">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/206" title="Video - Handheld">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/207" title="Video - HD - Movies">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/208" title="Video - HD - TV shows">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/209" title="Video - 3D">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/299" title="Video - Other">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/300" title="Applications">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/301" title="Applications - Windows">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/302" title="Applications - Mac">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/303" title="Applications - UNIX">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/304" title="Applications - Handheld">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/305" title="Applications - IOS (iPad/iPhone)">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/306" title="Applications - Android">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/399" title="Applications - Other OS">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/400" title="Games">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/401" title="Games - PC">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/402" title="Games - Mac">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/403" title="Games - PSx">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/404" title="Games - XBOX360">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/405" title="Games - Wii">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/406" title="Games - Handheld">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/407" title="Games - IOS (iPad/iPhone)">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/408" title="Games - Android">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/499" title="Games - Other">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/500" title="Porn">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/501" title="Porn - Movies">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/502" title="Porn - Movies DVDR">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/503" title="Porn - Pictures">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/504" title="Porn - Games">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/505" title="Porn - HD - Movies">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/506" title="Porn - Movie clips">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/599" title="Porn - Other">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/600" title="Other">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/601" title="Other - E-books">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/602" title="Other - Comics">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/603" title="Other - Pictures">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/604" title="Other - Covers">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/605" title="Other - Physibles">
    <link rel="alternate" type="application/rss+xml" href="//thepiratebay.org/rss/699" title="Other - Other">

</head>
<body>
<div id="fp">
    <h1><a href="/blog" title="The Pirate Bay"><span>The Pirate Bay</span></a></h1>
    <nav id="navlinks">
        <strong>Search Torrents</strong> |
        <a href="/browse" title="Browse Torrents">Browse Torrents</a> |
        <a href="/recent" title="Recent Torrents">Recent Torrents</a> |
        <a href="/tv/" title="TV shows">TV shows</a> |
        <a href="/music" title="Music">Music</a> |
        <a href="/top" title="Top 100">Top 100</a>
    </nav>
    <form name="q" method="get" action="/s/">
        <p id="inp">
            <input name="q" type="search" title="Pirate Search" placeholder="Pirate Search" autofocus required >
            <span>
                <a href="/settings" title="Preferences">Preferences</a>
                <a href="/language" title="Languages">Languages</a>
            </span>
        </p>
        <p id="chb">
            <label title="All" accesskey="a"><input id="all" onclick="setAll();" type="checkbox" checked>All</label>
            <label title="Audio" accesskey="q"><input name="audio" id="audio" onclick="rmAll();" type="checkbox">Audio</label>
            <label title="Video" accesskey="w"><input name="video" id="video" onclick="rmAll();" type="checkbox">Video</label>
            <label title="Applications" accesskey="e"><input name="apps" id="apps" onclick="rmAll();" type="checkbox">Applications</label>
            <label title="Games" accesskey="r"><input name="games" id="games" onclick="rmAll();" type="checkbox">Games</label>
            <label title="Porn" accesskey="t"><input name="porn" id="porn" onclick="rmAll();" type="checkbox">Porn</label>
            <label title="Other" accesskey="y"><input name="other" id="other" onclick="rmAll();" type="checkbox">Other</label>
        </p>
        <p id="subm">
            <input type="submit" title="Pirate Search" value="Pirate Search" accesskey="s"  >
            <input type="submit" title="I'm Feeling Lucky" name="lucky" value="I'm Feeling Lucky"  >
            <input type="hidden" name="page" value="0">
            <input type="hidden" name="orderby" value="99">
        </p>
    </form>
    <strong id="howdl"><a href="/help" title="How do I download?">How do I download?</a></strong>
</div>
<footer>
    <nav>
	<a href="/login" title="Login">Login</a> |
	<a href="/register" title="Register">Register</a> |
	<a href="/language" title="Select language">Language / Select language</a> |
	<a href="/about" title="About">About</a> |
	<a href="/blog" title="Blog">Blog</a>
	<br />
	 
	<a href="/policy" title="Usage policy">Usage policy</a> |
                     <a href="http://uj3wazyk5u4hnvtk.onion" title="TOR">TOR</a> |   

	
	<a href="/doodles" title="Doodles">Doodles</a> |
	<a href="http://pirates-forum.org/" title="Forum" target="_blank">Forum</a> 
    </nav>
    <div id="stats">
    </div>
    <div id="icons">
<br /><a href="http://bitcoin.org" target="_NEW">BTC</a>: <b>3HcEB6bi4TFPdvk31Pwz77DwAzfAZz2fMn</b><br /><a href="http://bitcoin.org" target="_NEW">BTC (Bech32)</a>: <b>bc1q9x30z7rz52c97jwc2j79w76y7l3ny54nlvd4ew</b><br /><a href="http://litecoin.org" target="_NEW">LTC</a>: <b>LS78aoGtfuGCZ777x3Hmr6tcoW3WaYynx9</b><br /><a href="http://getmonero.org" target="_NEW">XMR</a>: <b>46E5ekYrZd5UCcmNuYEX24FRjWVMgZ1ob79cRViyfvLFZjfyMhPDvbuCe54FqLQvVCgRKP4UUMMW5fy3ZhVQhD1JLLufBtu</b><br /><small>By entering TPB you agree to XMR being mined using your CPU. If you don't agree please leave now or install an adBlocker</small><br />	                <a href="/rss" title="RSS" class="sp rss"><span>RSS</span></a><br />
		<a href="http://www.kopimi.com/kopimi" target="_blank" title="Kopimi" class="sp kopimi"><span>Kopimi</span></a>
    </div>
</footer>
<script>
	if (top != self) top.location.href = location.href;
	function setAll(){
		t = document.forms.q.elements;
		t.audio.checked=false;
		t.video.checked=false;
		t.apps.checked=false;
		t.games.checked=false;
		t.other.checked=false;
	}
	function rmAll(){ document.forms.q.elements.all.checked=false; }
</script>
</body>
</html>
* Connection #0 to host thepiratebay.org left intact

**Comment by garfield69** [comment]
Oh, you're on Syno. so what version of Jackett are you on at the moment....still 0.8.* ?
