### ISSUE TITLE
[extratorrentclone] Exception (extratorrentclone): An attempt was made to access a socket in a way forbidden by its access permissions 104.27.171.11:443: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by notlahc** [Jackett/Jackett#3811]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
try accessing https://geetorrent.com/ from your browser, what do you see?
odds are good that your ISP is blocking access to this site.

**Comment by notlahc** [comment]
hey. 

it opens up extra torrent. im new to this so i wasnt sure if i screwed something up.

i also tried re installing jackett and no luck. all indexers fail as soon as i hit test

**Comment by garfield69** [comment]
jackett version and platform?
If you are experiencing an issue with a tracker, a **full enhanced log** must be included. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by notlahc** [comment]
Jackett Version 0.10.178.0
Windows 


Sep 16, 2018 05:03:49 PM | Info | Executing action method Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole) - Validation state: Valid
-- | -- | --
Sep 16, 2018 05:03:49 PM | Info | Authorization was successful.
Sep 16, 2018 05:03:49 PM | Info | Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing action Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)
Sep 16, 2018 05:03:49 PM | Info | Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/server/logs?_=1537081419921
Sep 16, 2018 05:03:41 PM | Info | Request finished in 105.2026ms 200 application/json; charset=utf-8
Sep 16, 2018 05:03:41 PM | Info | Executed action Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole) in 89.6006ms
Sep 16, 2018 05:03:41 PM | Info | Executing ObjectResult, writing value of type 'System.Linq.Enumerable+WhereSelectEnumerableIterator`2[[Jackett.Common.Indexers.IIndexer, Jackett.Common, Version=0.10.178.0, Culture=neutral, PublicKeyToken=null],[Jackett.Common.Models.DTO.Indexer, Jackett.Common, Version=0.10.178.0, Culture=neutral, PublicKeyToken=null]]'.
Sep 16, 2018 05:03:41 PM | Info | Executed action method Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 0.0075ms.
Sep 16, 2018 05:03:40 PM | Info | Executing action method Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole) - Validation state: Valid
Sep 16, 2018 05:03:40 PM | Info | Authorization was successful.
Sep 16, 2018 05:03:40 PM | Info | Route matched with {action = "Indexers", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole)
Sep 16, 2018 05:03:40 PM | Info | Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/indexers?_=1537081419920
Sep 16, 2018 05:03:40 PM | Info | Request finished in 23.6437ms 200 application/json; charset=utf-8
Sep 16, 2018 05:03:40 PM | Info | Executed action Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole) in 12.6984ms
Sep 16, 2018 05:03:40 PM | Info | Executing ObjectResult, writing value of type 'Jackett.Common.Models.DTO.ServerConfig'.
Sep 16, 2018 05:03:40 PM | Info | Executed action method Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 0.0303ms.
Sep 16, 2018 05:03:40 PM | Info | Executing action method Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole) - Validation state: Valid
Sep 16, 2018 05:03:40 PM | Info | Authorization was successful.
Sep 16, 2018 05:03:40 PM | Info | Route matched with {action = "Config", controller = "ServerConfiguration"}. Executing action Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole)
Sep 16, 2018 05:03:40 PM | Info | Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/server/config?_=1537081419919
Sep 16, 2018 05:03:39 PM | Info | Request finished in 32.0351ms 200 text/html
Sep 16, 2018 05:03:39 PM | Info | Executed action Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole) in 21.8799ms
Sep 16, 2018 05:03:39 PM | Info | Executing Microsoft.AspNetCore.Mvc.PhysicalFileResult, sending file 'C:\ProgramData\Jackett\Content/index.html' with download name '' ...
Sep 16, 2018 05:03:39 PM | Info | Executed action method Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole), returned result Microsoft.AspNetCore.Mvc.PhysicalFileResult in 0.0825ms.
Sep 16, 2018 05:03:39 PM | Info | Executing action method Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole) - Validation state: Valid
Sep 16, 2018 05:03:39 PM | Info | Authorization was successful.
Sep 16, 2018 05:03:39 PM | Info | Route matched with {action = "Dashboard", controller = "WebUI"}. Executing action Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole)
Sep 16, 2018 05:03:39 PM | Info | Request starting HTTP/1.1 GET http://127.0.0.1:9117/UI/Dashboard
Sep 16, 2018 05:02:34 PM | Info | Request finished in 4.2387ms 404
Sep 16, 2018 05:02:34 PM | Info | Request starting HTTP/1.1 GET http://127.0.0.1:9117/%ProgramData%/Jackett
Sep 16, 2018 04:58:50 PM | Info | Request finished in 20.7862ms 200 application/json; charset=utf-8
Sep 16, 2018 04:58:50 PM | Info | Executed action Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole) in 11.3772ms
Sep 16, 2018 04:58:50 PM | Info | Executing ObjectResult, writing value of type 'System.Collections.Generic.List`1[[Jackett.Common.Models.CachedLog, Jackett.Common, Version=0.10.178.0, Culture=neutral, PublicKeyToken=null]]'.
Sep 16, 2018 04:58:50 PM | Info | Executed action method Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 0.0093ms.
Sep 16, 2018 04:58:50 PM | Info | Executing action method Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole) - Validation state: Valid
Sep 16, 2018 04:58:50 PM | Info | Authorization was successful.
Sep 16, 2018 04:58:50 PM | Info | Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing action Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)
Sep 16, 2018 04:58:50 PM | Info | Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/server/logs?_=1537081125054
Sep 16, 2018 04:58:46 PM | Info | Request finished in 79.3109ms 200 application/json; charset=utf-8
Sep 16, 2018 04:58:46 PM | Info | Executed action Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole) in 64.589ms
Sep 16, 2018 04:58:45 PM | Info | Executing ObjectResult, writing value of type 'System.Linq.Enumerable+WhereSelectEnumerableIterator`2[[Jackett.Common.Indexers.IIndexer, Jackett.Common, Version=0.10.178.0, Culture=neutral, PublicKeyToken=null],[Jackett.Common.Models.DTO.Indexer, Jackett.Common, Version=0.10.178.0, Culture=neutral, PublicKeyToken=null]]'.
Sep 16, 2018 04:58:45 PM | Info | Executed action method Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 0.0049ms.
Sep 16, 2018 04:58:45 PM | Info | Executing action method Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole) - Validation state: Valid
Sep 16, 2018 04:58:45 PM | Info | Authorization was successful.
Sep 16, 2018 04:58:45 PM | Info | Route matched with {action = "Indexers", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Indexers (JackettConsole)
Sep 16, 2018 04:58:45 PM | Info | Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/indexers?_=1537081125053
Sep 16, 2018 04:58:45 PM | Info | Request finished in 30.2889ms 200 application/json; charset=utf-8
Sep 16, 2018 04:58:45 PM | Info | Executed action Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole) in 19.2938ms
Sep 16, 2018 04:58:45 PM | Info | Executing ObjectResult, writing value of type 'Jackett.Common.Models.DTO.ServerConfig'.
Sep 16, 2018 04:58:45 PM | Info | Executed action method Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 0.0475ms.
Sep 16, 2018 04:58:45 PM | Info | Executing action method Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole) - Validation state: Valid
Sep 16, 2018 04:58:45 PM | Info | Authorization was successful.
Sep 16, 2018 04:58:45 PM | Info | Route matched with {action = "Config", controller = "ServerConfiguration"}. Executing action Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole)
Sep 16, 2018 04:58:45 PM | Info | Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/server/config?_=1537081125052
Sep 16, 2018 04:58:44 PM | Info | Request finished in 76.4674ms 200 text/html
Sep 16, 2018 04:58:44 PM | Info | Executed action Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole) in 11.6529ms
Sep 16, 2018 04:58:44 PM | Info | Executing Microsoft.AspNetCore.Mvc.PhysicalFileResult, sending file 'C:\ProgramData\Jackett\Content/index.html' with download name '' ...
Sep 16, 2018 04:58:44 PM | Info | Executed action method Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole), returned result Microsoft.AspNetCore.Mvc.PhysicalFileResult in 0.0533ms.
Sep 16, 2018 04:58:44 PM | Info | Executing action method Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole) - Validation state: Valid
Sep 16, 2018 04:58:44 PM | Info | Authorization was successful.
Sep 16, 2018 04:58:44 PM | Info | Route matched with {action = "Dashboard", controller = "WebUI"}. Executing action Jackett.Server.Controllers.WebUIController.Dashboard (JackettConsole)
Sep 16, 2018 04:58:44 PM | Info | Request starting HTTP/1.1 GET http://127.0.0.1:9117/UI/Dashboard
Sep 16, 2018 04:58:41 PM | Debug | Helper initialization complete
Sep 16, 2018 04:58:41 PM | Info | Adding aggregate indexer
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\ztracker.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\zooqle.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\zelkaorg.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\zamundanet.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\yourexotic.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\yggtorrent.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\xtremezone.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\xbytes2.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\x-ite.me.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\worldwidetorrents.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\worldofp2p.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\waffles.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\unionfansub.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\ultimategamerclub.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\uhdbits.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\trezzor.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\trancetraffic.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\totheglory.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torviet.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrentz2.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrentsmd.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrentseeds.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrentsectorcrew.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrentlt.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrentland.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrenting.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrenthr.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrentdownloads.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrentccf.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrentbd.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrent9.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torrent-turk.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\torlock.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\tokyotosho.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\tntvillage.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\thevault.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\thetorrents.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\theshow.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\theshinning.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\theplace.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\thepiratebay.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\theoccult.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\thehorrorcharnel.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\thegeeks.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\theempire.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\tenyardtracker.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\tbplus.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\tasmanit.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\sukebeinyaasi.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\sukebei-pantsu.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\sportscult.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\sporthd.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\speedtorrentreloaded.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\speed-share.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\sktorrent.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\shellife.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\sharespacedb.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\shareisland.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\sdbits.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\scenereactor.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\scenefz.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\rutor.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\rodvd.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\rgu.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\retroflix.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\redtopia.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\redstartorrent.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\racing4everyone.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\puntotorrent.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\ptfiles.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\polishsource.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\passionetorrent.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\ourbits.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\nyoo.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\nyaasi.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\nyaa-pantsu.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\nnm-club.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\newstudio.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\newretro.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\nethd.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\myspleen.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\mvgroupmain.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\mvgroupforum.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\mteamtp.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\mononokebt.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\metaltracker.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\megabliz.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\manicomioshare.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\majomparade.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\magnetdl.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\magico.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\losslessclub.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\linkomanija.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\limetorrents.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\kinozal.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\kickasstorrent.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\kickasstorrent-kathow.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\karagarga.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\kapaki.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\jpopsuki.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\isohunt2.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\insanetracker.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\inperil.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\iloveclassics.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\ilcorsaronero.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\ilcorsaroblu.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\idope.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\icetorrent.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\hyperay.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\hqsource.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\hon3yhd.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\hdtorrentsit.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\hdspain.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\hdsky.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\hdme.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\hdhome.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\hdcity.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\hdchina.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\hdbitscom.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\hdbits.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\hachede.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\greekteam.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\gods.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\gktorrent.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\girotorrent.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\gigatorrents.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\gfxpeers.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\gfxnews.yml
Sep 16, 2018 04:58:41 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\gaytorrentru.yml
Sep 16, 2018 04:58:40 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\gay-torrentsorg.yml
Sep 16, 2018 04:58:40 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\gay-torrents.yml
Sep 16, 2018 04:58:40 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\funkytorrents.yml
Sep 16, 2018 04:58:40 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\fullmixmusic.yml
Sep 16, 2018 04:58:40 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\frozenlayer.yml
Sep 16, 2018 04:58:40 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\freedomhd.yml
Sep 16, 2018 04:58:40 PM | Info | Loading Cardigann definition C:\ProgramData\Jackett\Definitions\femdomcult.yml

**Comment by garfield69** [comment]
yeah, nah. 
that looks like the regular log, not much use.
here is a step by step list of what would be useful:
1. from your jackett dashboard, scroll down to the bottom and tick the *enhanced logging* checkbox,
2. then go up a bit and click on the *apply server settings* button.
3. now do a single test of extratorrentclone using the *test* button for that indexer
4. open file explorer and access the `C:\ProgramData\Jackett` folder
5. find the log.txt file
6. drag drop that file here so we can take a look

**Comment by garfield69** [comment]
interesting log. 
I see the Jackett auto update is failing to access the github api server:  *The remote name could not be resolved: 'api.github.com',* which suggests something is wrong with the setup.

But I thought you were going to test extratorrentclone ?
the log shows you testing etratorrent.ag which is down at the moment, so it does not provide a valid test condition for seeing what might be going on.
Admittedly it is generating the same error as you reported for extratorrentclone, but i would rather have a test for an online site to look at.

Please repeat the enhanced logging test with extratorrentclone.

Also, while we are at it, can you take a screen shot of the bottom of the jackett dashboard so we can confirm your config
![image](https://user-images.githubusercontent.com/6933240/45594496-b9c7c700-b9ef-11e8-9f95-8e1ec543ca25.png)
just in case there is some stray setting there that might be responsible.
Thanks.

**Comment by notlahc** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/2386445/log.txt)


my bad. i must've clicked the wrong one... when the test fails i usually delete it 

also thanks heaps for all your help sofar!

**Comment by garfield69** [comment]
ok good. we'll keep the last log. still looking to get the screen capture of the jackett settings....

**Comment by notlahc** [comment]
![untitled](https://user-images.githubusercontent.com/43308296/45595029-8170ba80-b9e8-11e8-9c75-7a2c00bc37ef.png)

**Comment by garfield69** [comment]
great thanks.
so I am unable to figure out what is going on here with your setup, so I am going to invite @kaso17  and @flightlevel  to take a look and see if they can figure out what is going on.

**Comment by notlahc** [comment]
awesome thanks heaps

**Comment by kaso17** [comment]
that error sounds more like an operating system error, I would suspect some kind of firewall/anti virus security product blocking the connection. Try to whitelist jackett for outgoing connections in your firewall.

**Comment by notlahc** [comment]
Hey 

i checked the settings an you were right. thanks heaps for all your help!
