### ISSUE TITLE
[arabafenice] Exception (arabafenice): Got redirected to another domain. Try changing the indexer URL to https://www.arabafenice.me/.: Parse error (Test)

### ISSUE THREAD

**Issue by gandalf764** [Jackett/Jackett#3814]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by gandalf764** [comment]
Jackett version: v0.10.186

[arabafenice] Exception (arabafenice): Got redirected to another domain. Try changing the indexer URL to https://www.arabafenice.me/.: Parse error (Test) #3814
![2018-09-16 21_36_21-jackett](https://user-images.githubusercontent.com/41706025/45600169-9bb29480-b9f8-11e8-8043-afba9e21a2a6.png)

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file in the Jackett folder
5. edit it with a plain text editor, redacting any personal details first, usernames, passwords, passkeys, hashes etc.
6. save, then darg-drop it here for us to take a look at.
Thanks.

**Comment by gandalf764** [comment]
I have activated enhanced logging but i cant find log.txt in my jackett
folder...

Il dom 16 set 2018, 21:58 garfield69 <notifications@github.com> ha scritto:

**Comment by garfield69** [comment]
are you looking in /opt/jackett ?

**Comment by gandalf764** [comment]
yes
![2018-09-16 22_30_13-contabo root ssh - sftp___root 5 189 132 73 - filezilla](https://user-images.githubusercontent.com/41706025/45600619-23e86800-ba00-11e8-993f-b364cad3939a.png)

**Comment by garfield69** [comment]
sorry, forgot that on linux the log hould be in `~/.config/Jackett/`

**Comment by gandalf764** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/2387013/log.txt)

**Comment by garfield69** [comment]
try accessing you jackett/dashboard and editing your arabafenice indexer to change the site link from *http* to **https** and see if that solves the problem.

**Comment by gandalf764** [comment]
Ops .. now work! Thanx!
But from many days work with http and now https? Why?
Problem silver thanx

Il dom 16 set 2018, 23:08 garfield69 <notifications@github.com> ha scritto:

**Comment by garfield69** [comment]
looks like the site is forcing users from http onto https. 
I've added a fix to auto correct for the other jackett users of the indexer.
