### ISSUE TITLE
[fuzer] Couldn't login (Config)

### ISSUE THREAD

**Issue by sagilo** [Jackett/Jackett#3815]
Can't login to fuzer tracker:
```
An error occured while updating this indexer
Couldn't login
```

**Jackett version**:  0.8.578.0
Running with docker

**Comment by garfield69** [comment]
version 0.8 is fairly old, consider upgrading to 0.10.* if possible

**Comment by sagilo** [comment]
I see..
Is there an official docker image?

**Comment by garfield69** [comment]
https://hub.docker.com/r/linuxserver/jackett/

**Comment by garfield69** [comment]
did you make progress resolving this?

**Comment by sagilo** [comment]
@garfield69 yes thank you. it all worked out.
