### ISSUE TITLE
[zooqle] Exception (zooqle): Request to https://zooqle.com/search?s=dt

### ISSUE THREAD

**Issue by chatainsim** [Jackett/Jackett#3818]
An error occured while testing this indexer
Exception (zooqle): Request to https://zooqle.com/search?s=dt&v=t&sd=d&q=%20* failed (Error Forbidden) - The page is protected by an Cloudflare reCaptcha. The page is in aggressive DDoS mitigation mode or your IP might be blacklisted (e.g. in case of shared VPN IPs). There's no easy way of making it usable with Jackett.: Request to https://zooqle.com/search?s=dt&v=t&sd=d&q=%20* failed (Error Forbidden) - The page is protected by an Cloudflare reCaptcha. The page is in aggressive DDoS mitigation mode or your IP might be blacklisted (e.g. in case of shared VPN IPs). There's no easy way of making it usable with Jackett.

```Jacket v0.10.186.0```

```# mono --version
Mono JIT compiler version 5.12.0.226 (tarball Thu May  3 09:48:32 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```

**Comment by garfield69** [comment]
so cloudflare ddos protection has been enabled for your IP block by zooqle and unfortunately jackett cannot handle this type of captcha challenge.
you should see the captcha for yourself if you access https://zooqle.com/ from your browser.

while the ddos protection is active you will not be able to use jackett to access zooqle

Usually the protection is lifted after the threat is over, so you will just have to wait and try again periodically.
or alternatively, using a VPN that assigns an alternate IP address for you that is outside of the currently blacklisted IP block should get you access again.

sometimes accessing zooqle via the browser first will grant you access respite long enough to use jackett, but this does not last long and jackett will get another challenge again in a short period of time.

nothing jackett can do about this at the moment. the captcha challenge is too difficult to code a solution for solving.
