### ISSUE TITLE
IMDB is less than 7 digits, will remove 0

### ISSUE THREAD

**Issue by mcyt** [Jackett/Jackett#3819]
such as tt0111161 display is 111161
how to solve it?

**Comment by mcyt** [comment]
https://www.imdb.com/title/tt111161/
404.
this is obviously not what I want

**Comment by mcyt** [comment]
If you can, please update(really really really hope).
If not, please tell me the method
Win 2008,I hope to elaborate
Please forgive me for being a newbie.
thank u.Jackett very nice!
-------google translate

**Comment by kaso17** [comment]
fixed via 1c3bc3cbf49938afc5c1b33d84ee61cbc3908a4e
