### ISSUE TITLE
Sonarr not fetching files from Avistaz

### ISSUE THREAD

**Issue by tomyam555** [Jackett/Jackett#382]
Hi there. My Sonarr not fetching files from Avistaz indexer after added wanted series. Please advise and hope to hear from you soon. Thank you

**Comment by flightlevel** [comment]
Does it work from the Jackett Dashboard?

**Comment by tomyam555** [comment]
yes. please advice and thank you

**Comment by tylerhammer** [comment]
Can confirm that this occurs as well. Works in the Jackett Dashboard but not in Sonarr.

**Comment by tylerhammer** [comment]
Any update on this?

**Comment by tomyam555** [comment]
hope they fix this soon

**Comment by tomyam555** [comment]
Any work around for this?

**Comment by tylerhammer** [comment]
Still no response?

**Comment by kaso17** [comment]
is this still a problem?

**Comment by kaso17** [comment]
closing (no answer)
