### ISSUE TITLE
Has my question been deleted?

### ISSUE THREAD

**Issue by mcyt** [Jackett/Jackett#3823]
Has my question been deleted?

**Comment by kaso17** [comment]
which question?
#3819 #3746?

**Comment by mcyt** [comment]
> which question?
> #3819 #3746?
i see fix imdb link generation
thank u.

**Comment by mcyt** [comment]
Asking, can I use this fix imdb link generation function directly after downloading the latest version?

**Comment by kaso17** [comment]
there will be a new release containing the fix within the next hour.
