### ISSUE TITLE
Sorry, maybe I made a mistake!imdb in the Copy RSS Feed

### ISSUE THREAD

**Issue by mcyt** [Jackett/Jackett#3824]
I mainly want to modify the parameters in the Copy RSS Feed.
Such as <torznab:attr name="imdb" value="111161" />
<torznab:attr name="imdb" value="0111161" />
Thank you, Big Brother.

**Comment by mcyt** [comment]
Ask one more, where to modify the number of resources, the default is 100.
in the Copy RSS Feed

**Comment by mcyt** [comment]
very very very sorry,thank you!

**Comment by mcyt** [comment]
I really want to wait online, but it is 1 am., I’m going to sleep.

**Comment by kaso17** [comment]
changed via ef92bf53427f7acfad8a6997ece233ae4f4c5b04
please try v0.10.198
