### ISSUE TITLE
New tracker request hd4free

### ISSUE THREAD

**Issue by mstrdraco** [Jackett/Jackett#3827]
requesting new tracker be added - hd4free - 
https://hd4.xyz/login

**Comment by WolfRamAlpha12** [comment]
I believe it's already there but with a different URL(https://hd4free.xyz/login). I tried to configure it but it failed. It's also possible that they changed the website as well.


Sep 17, 2018 07:46:52 PM | Info | IndexerApiController Dispose
-- | -- | --
Sep 17, 2018 07:46:52 PM | Info | IndexerApiController Dispose
Sep 17, 2018 07:46:52 PM | Info | Content-type='application/json; charset=utf-8', content-length=20287
Sep 17, 2018 07:46:52 PM | Info | IndexerApiController ExecuteAsync
Sep 17, 2018 07:46:52 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Sep 17, 2018 07:46:52 PM | Error | {0}
Sep 17, 2018 07:46:52 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Sep 17, 2018 07:46:52 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Sep 17, 2018 07:46:52 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Config()'
Sep 17, 2018 07:46:52 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Sep 17, 2018 07:46:52 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Config()'
Sep 17, 2018 07:46:52 PM | Error | ApiControllerActionInvoker InvokeActionAsync
Sep 17, 2018 07:46:52 PM | Error | ReflectedHttpActionDescriptor ExecuteAsync
Sep 17, 2018 07:46:52 PM | Debug | WebClient(HttpWebClient).GetString(Url:https://hd4free.xyz/login)
Sep 17, 2018 07:46:52 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Config()'
Sep 17, 2018 07:46:52 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Config()'
Sep 17, 2018 07:46:52 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync
Sep 17, 2018 07:46:52 PM | Info | RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Config()'
Sep 17, 2018 07:46:52 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Sep 17, 2018 07:46:52 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Config()'
Sep 17, 2018 07:46:52 PM | Info | HttpActionBinding ExecuteBindingAsync
Sep 17, 2018 07:46:52 PM | Info | HttpActionBinding ExecuteBindingAsync
Sep 17, 2018 07:46:52 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Sep 17, 2018 07:46:52 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Sep 17, 2018 07:46:52 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Config()'
Sep 17, 2018 07:46:52 PM | Info | ApiControllerActionSelector SelectAction
Sep 17, 2018 07:46:52 PM | Info | IndexerApiController ExecuteAsync
Sep 17, 2018 07:46:52 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.IndexerApiController
Sep 17, 2018 07:46:52 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.IndexerApiController
Sep 17, 2018 07:46:52 PM | Info | DefaultHttpControllerActivator Create
Sep 17, 2018 07:46:52 PM | Info | HttpControllerDescriptor CreateController
Sep 17, 2018 07:46:52 PM | Info | DefaultHttpControllerSelector SelectController IndexerApi

**Comment by HDVinnie** [comment]
@WolfRamAlpha12 The `HD4Free.cs` file was removed when they closed. They no longer use u-232 codebase anyway. I made a PR for a new indexer to work with there new codebase UNIT3D.

**Comment by 19wolf** [comment]
This says done but I can't find it in Jackett? I'm running the latest version 0.10.198.0.

**Comment by garfield69** [comment]
it will be included in the next (pre)release whenever that gets published.
Currently Draft 0.10.211 has it, which you could download from https://github.com/Jackett/Jackett/releases/tag/untagged-e1702586335a998418cd  if you want to install a canary version.

**Comment by 19wolf** [comment]
> which you could download from https://github.com/Jackett/Jackett/releases/tag/untagged-e1702586335a998418cd 

404

**Comment by garfield69** [comment]
Sorry, did not realise that draft builds are only available to group members.
You will have to just wait for the (pre)release to be published, whenever that happens.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/releases has prerelease 0.10.211 now.

**Comment by garfield69** [comment]
https://hd4.xyz/ returning ERR_CONNECTION_TIMED_OUT
just me, or is the site broken, gone or on a new domain?

**Comment by HDVinnie** [comment]
Site is gone for the moment. Operator fell off the face of the planet. I believe others are trying to reboot it.
