### ISSUE TITLE
Update fails on Syno 6.2

### ISSUE THREAD

**Issue by Stanzilla** [Jackett/Jackett#3831]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.178.0
**Mono version** (if not using Windows):  5.8.0.108
**OS**: Synology DSM 6.2

-------------------------------

Continuing from https://github.com/Jackett/Jackett/issues/3807 the update just fails and the log does not have very much information, even when enabling enhanced logging. Any hints on how I can provide more info?

**Comment by garfield69** [comment]
assuming syno is just a flavour of linux, then check if you have a folder `~/.config/Jackett/` and see what logs there are ... if there is an updater.txt then  drag-drop it here so we can take a look. 
also, #2778 may be useful.

**Comment by Stanzilla** [comment]
I have an updater.txt file but it has not been written to since july 2018

**Comment by garfield69** [comment]
@kaso @flightlevel : Guys, what is the status with auto-update (AU) on some linux flavours... I recall that AU does not work on docket images, users have to grab a new image to upgrade (please correct me if i'm out of date or completely wrong). Does the same apply on Synology platforms?

**Comment by kaso17** [comment]
do you have some kind of really slow internet connection?
The log indicates a timeout during the update download.
Please try to tun on enhanced logging before checking for updates and post an updated log.

**Comment by Stanzilla** [comment]
Okay I figured it out, /tmp/ was full. Two problems:

* If an update fails, jackett does not clean up the updater files in /tmp/ only adding to the problem
* The standard log should provide a clearer reason as to why the update failed. Just "update failed" is not good enough. The advanced log clearly says "disc is full".

* having an `updater.txt` on Syno seems to have blocked the upgrade process from properly starting. It only went on to download and extract files when that was deleted, could have been a coincident though.

**Comment by garfield69** [comment]
>having an updater.txt on Syno seems to have blocked the upgrade process from properly starting. It only went on to download and extract files when that was deleted, could have been a coincident though.

deleting the update.txt probably freed enough space to start the update process flowing...until disc got full again.

**Comment by Stanzilla** [comment]
yeah that was my thinking as well
