### ISSUE TITLE
Fix/update idope

### ISSUE THREAD

**Issue by ldexterldesign** [Jackett/Jackett#3832]
Hi all,

Seemingly, idope has been down for a few months now:

http://reddit.com/r/iDopeTorrent/comments/8scucx/whats_going_on
http://torrentfreak.com/top-10-torrent-site-idope-goes-down-with-domain-issues-180815

http://idope.cc
http://idope.co
http://idope.se

I have found http://idope.top works - any objection to updating the definition?

Hope this is clear/useful and to hear back

Keep up great work!

Yours faithfully

**Comment by garfield69** [comment]
idope.top appear to be a clone of the original, using different html, results presentation, and search logic.
so I have deleted Idope, and create IdopeClone as a replacement.
The next (pre)release of Jackett should include these changes.
