### ISSUE TITLE
Cookies in docker

### ISSUE THREAD

**Issue by hazadar** [Jackett/Jackett#3842]
Trying to setup cookie login with iptorrents. However setup is using docker, with jackett in a docker container, can't get a cookie working from outside the docker container to jackett. This is a headless server so I installed another docker image that allows me to run a browser from inside that container to grab the cookie, any thoughts on how I can get this working?

**Comment by flightlevel** [comment]
Why do you have to get the cookies using the same container as you docker? Thousands of people using the docker images, just getting the cookies via their web browser
