### ISSUE TITLE
[myanonamouse] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Hackerpcs** [Jackett/Jackett#3845]
**Jackett version**:  0.10.198.0

-------------------------------

https://pastebin.com/5xHmx0Hp

**Comment by garfield69** [comment]
you are getting *access limits exceeded* back from the site in response.
have you tried using the site directly from your browser?

**Comment by garfield69** [comment]
does the site  have a faq where they explain what *access limits exceeded* means?
the alternate is that you leave *enhanced loggin* on (and remember to turn it back on after a restart) so that you can catch the original error when this happens again.

**Comment by kaso17** [comment]
should be fixed via 9e37b1429a6409482da4a4e557cedb3e49db6b8b

**Comment by Hackerpcs** [comment]
It was fixed, got the error again on the version above, updated to latest v0.10.221 and it works.
