### ISSUE TITLE
http or http/https proxy?

### ISSUE THREAD

**Issue by niXta1** [Jackett/Jackett#3848]
Does Jackett's proxy work with https or only http?
Thanks.

Jackett Version: 0.10.198.0  

-------------------------------

**Comment by kaso17** [comment]
Jackett is using the standard HTTP proxy functionality provided by HttpClient. I would be very surprised if it can handle HTTPS. Can't find anything on the topic so I suspect your answer is no.

**Comment by Daniel15** [comment]
If you want to use a HTTPS proxy, you can use `socat` to create a tunnel:
```
socat TCP-LISTEN:24351,bind=127.0.0.1,fork,reuseaddr OPENSSL:proxy.example.com:443
```
Then use `127.0.0.1` port `24351` as the proxy. I'm doing this to use a HTTPS proxy with proxychains, but it'd work with any app that only supports HTTP proxies.
