### ISSUE TITLE
BeyondHD Provider domain change

### ISSUE THREAD

**Issue by Narkyzz** [Jackett/Jackett#385]
Hi,

The domain for BeyondHD has changed to beyondhd.xyz. If need access to the site, expected to go live in maybe 2 days from now.

Cheers,
BeyondHD Staff.

**Comment by d2dyno** [comment]
Updated in this pull request: https://github.com/Jackett/Jackett/pull/388

**Comment by d2dyno** [comment]
@Narkyzz Which should the domain name be? I see an announcement on BeyondHD, that the domain is now: Beyond-HD.me. Which one ought to be the primary?

**Comment by ajfried22** [comment]
https://www.reddit.com/r/trackers/comments/4qurpy/beyondhd_new_domain/d4xr9gh

**Comment by Narkyzz** [comment]
That is correct, thank you. The main domain is beyond-hd.me.
