### ISSUE TITLE
[demonoid] Exception (demonoid): Request to https://www.demonoid.pw/files/?category=0

### ISSUE THREAD

**Issue by nnovaes** [Jackett/Jackett#3859]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.164.0
**Mono version** (if not using Windows):   5.14.0.177 

-------------------------------

**Comment by garfield69** [comment]
demonoid is going through some technical difficulties at the moment, refer https://torrentfreak.com/pirate-bay-and-demonoid-face-technical-troubles-180914/

currently the site is returning cloudflare 502 Bad Gateway

nothing jackett can do about this, you will just have to try again on another day
