### ISSUE TITLE
Avast! Flags Jackett as Virus

### ISSUE THREAD

**Issue by trevorgentry** [Jackett/Jackett#3865]
I am using Jackett version 0.10.198.0 on Windows 10 Professional.
Avast flagged Jackett as a virus. More specifically, it flagged JacketConsole.exe as an IDP.Generic. I've had the program installed for about a week and had no problem with the program and my anti-virus until now. I added the file to my exceptions to avoid further issues and because I am confident it was a false positive, but I was hoping someone could figure out what was triggering it and fix/change it so other users don't experience the same issue.

**Comment by garfield69** [comment]
it's definitely a false positive, and as far as I know its just AVAST **behaviour shield** that is flagging it.
(its been doing it for all the builds beginning with the 0.10.* generation.)

I ran the latest jackettconsole.exe against virustotal.com and got a clean bill of health, even from its avast module! (https://www.virustotal.com/#/file/9057bf9c5d6cb1d0c350b9f44885392b2d713e62002aa5eacdbad63210f92355/detection)

And the local AVAST file scan gives it a clean bill of health too!

I've submitted the new 0.10.221 jackettconsole.exe to the AVAST virus lab as a false positive, but other than that I don't think there is anything more we can do.
