### ISSUE TITLE
Cinemageddon and THC: Ability to search by IMDb ID

### ISSUE THREAD

**Issue by MikeMilligan** [Jackett/Jackett#3866]
Hello. I'm new to this software but I'm really liking it so far. One thing I'm missing is the ability to search by IMDb in these to two trackers.

In these two sites there's the option to just type the IMDb ID of a given movie in the search field and it finds all movies matching that ID regardless of their titles, pretty useful specially for older movies with many re-releases. However, when I do so in Jackett I don't get any results from these two trackers (although it's working with other trackers like PTP, Secret Cinema or Filelist).

Thanks in advance.

**Jackett version**:  0.10.221.0

-------------------------------

**Comment by garfield69** [comment]
I could implement imdb query support for THC and Cinemageddon, but I would need invites to both these sites, as open registration is currently closed on either.
send invites to garfieldsixtynine @ gmail.com if you want support from me for this enhancement.

**Comment by MikeMilligan** [comment]
Sadly I don't have any invites for Cinemageddon but I sent you one for THC. Check your spam folder.

I hope it's not too difficult to implement. Thank you.

**Comment by garfield69** [comment]
registration to THT complete, login is pending your confirmation. Thanks.

**Comment by MikeMilligan** [comment]
Account confirmed :sunglasses: 

Thanks again.

**Comment by garfield69** [comment]
Try Jackett pre-release v0.10.796

**Comment by MikeMilligan** [comment]
It works! 

Too bad I don't have any invites for Cinemageddon. Thanks again. :grin:

**Comment by RoloSoze** [comment]
#4859

**Comment by RoloSoze** [comment]
I'll close this issue. It has not been fully resolved, but Cinemageddon is listed in #4859 among the trackers for which the IMDb ID search still needs to be implemented, so it serves the same purpose as this ticket. If someone would like this to be done, please feel free to send an invite to @garfield69.

**Comment by RoloSoze** [comment]
@MikeMilligan Cinemageddon's IMDb ID search support has been added in #8488 - It should be available in the upcoming update. Feel free to test it out.

**Comment by MikeMilligan** [comment]
> 
> 
> @MikeMilligan Cinemageddon's IMDb ID search support has been added in #8488 [[5f03bb3](https://github.com/Jackett/Jackett/commit/5f03bb3b7187de51f36b708cdfeea8564ced954d)] - It should be available in the upcoming update. Feel free to test it out.

Can confirm it works! Thanks a lot for this update and for notifying me.
