### ISSUE TITLE
some feedback on mejortorrent

### ISSUE THREAD

**Issue by icf20** [Jackett/Jackett#3869]
i run jackett on freenas 11.2 i did notice that jacket was using allot of CPU so i made a new jail and begin to test the indexers i use one by one, after few hours of running on my setup jacket cpu use goes up x10 times if it uses mejortorrent 

maybe other people want to make test on their setup and see if they get similar results

**Comment by TrashCanMan** [comment]
Maybe #3653 and #3710 are related, and there have been other problems with mejortorrent in the last few months...personally i didnt had problems with this in the last week or so, maybe they solved it from the tracker itself...

**Comment by xboxhacks** [comment]
I have had high cpu issues since using SOCKS 5 proxy

**Comment by garfield69** [comment]
jackett 0.12.1669
