### ISSUE TITLE
Torrentz2 Connection Test Failed

### ISSUE THREAD

**Issue by 91ajames** [Jackett/Jackett#3877]
An error occured while testing this indexer
Exception (torrentz2): Clearance failed after 11 attempt(s).: Clearance failed after 11 attempt(s).

Tested torrentz2 from Raspberry Pi to TinkerBoard

Pi Tested: ok
TB Tested: bad

Both kept it as default.

**Jackett version**:  0.8.929.0  RPi & TB
**Mono version**: 5.14.0.177 TB
-------------------------------

**Comment by garfield69** [comment]
duplicate #2948 
Cloudflare clearance support isn't perfect yet. Please keep retrying. At some point it should work.
