### ISSUE TITLE
[hd4free] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by doctorboyMP** [Jackett/Jackett#3878]
Dear all,

I'm trying to set up Jacket with the new tracker hd4free, I insert the cookie as instructed but I'm still not able to make it work.
Can you please check if everything is ok? If yes, what can I do to fix this?
Jacket is perfectly working for another 8 trackers, so this might be an isolated issue.
I've attached an export of the log with the error.
Thanks in advance.

-------------------------------
[export_log.txt](https://github.com/Jackett/Jackett/files/2426101/export_log.txt)

**Jackett version**:  0.10.221.0
**Mono version** (if not using Windows):  5.14.0.177

**Comment by garfield69** [comment]
it appears that the *hd4free* indexer has not been set up to handle the dates in non-english profiles.
I don't have a login, but I can fix this if you provide another enhanced log where you do a few searches that provide the most wide range of dates possible.
at the moment all I have to work with is `3 dias atrás` and I would like other date samples so I can customise the date parser.
Thanks.

**Comment by HDVinnie** [comment]
@garfield69 if you need a invite there to make your life easier you can feel free to email me at unit3d@protonmail.com

**Comment by garfield69** [comment]
@HDVinnie  request emailed. thank you.

**Comment by garfield69** [comment]
@HDVinnie  Thanks.

**Comment by doctorboyMP** [comment]
Sorry for the delay @garfield69. Thanks for your fantastic support!
Cheers
