### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://www.yggtorrent.fr/ using form selector form[action$=

### ISSUE THREAD

**Issue by goldriver2** [Jackett/Jackett#3884]
YGGtorrent is not working, 

[yggtorrent] Login failed: No form found on https://www.yggtorrent.fr/ using form selector form[action$=

**Comment by Bastien42** [comment]
try with https://yggtorrent.to/

**Comment by Bastien42** [comment]
and let me know please because it works well since yesterday but now it stop working

**Comment by garfield69** [comment]
@goldriver2  the site at https://www.yggtorrent.fr/ is a clone of the official site and is not supported by jackett, as they are using different html to present their results.
@Bastien42  I have no problems accessing https://yggtorrent.to/ this morning. hopefully its just a temporary condition for you.

**Comment by goldriver2** [comment]
When I tried it this morning it was not working with .to, just retried and now it works

Thanks
