### ISSUE TITLE
Torrentday Urls's

### ISSUE THREAD

**Issue by robgates** [Jackett/Jackett#3885]
Seems that Torrentday has changed the mirror links

> https://td.findnemo.net

> https://td.getcrazy.me

> https://td.venom.global

> https://td.workisboring.net
 

-------------------------------

**Comment by garfield69** [comment]
these mirrors are already loaded on the TD indexer a couple weeks back
![image](https://user-images.githubusercontent.com/6933240/46276218-e10bc000-c5bb-11e8-9c47-0d7866a96a49.png)
do you need to upgrade to the latest Jackett, currently v0.10.221 or pre-release v0.10.250 ?
