### ISSUE TITLE
[megabliz] Login failed: No form found on https://mega-bliz.nl/login.php using form selector form[action=

### ISSUE THREAD

**Issue by jochu38** [Jackett/Jackett#3887]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
megablitz is currently down.
![image](https://user-images.githubusercontent.com/6933240/46332843-808f8800-c67a-11e8-97cd-d945fb2072e0.png)
nothing to do with jackett.
