### ISSUE TITLE
[ilcorsaronero] Exception (ilcorsaronero): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /SRC/.MYSCRIPT/tmp/mono-5.12.0.226/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by gipasoft** [Jackett/Jackett#3892]
When I try to test `Corsaro Nero` indexer I obtain this error:

> Exception (ilcorsaronero): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /SRC/.MYSCRIPT/tmp/mono-5.12.0.226/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request

**Jackett version**:  0.10.250
**Mono version** (if not using Windows):  5.12.0.266
-------------------------------
Enhanced log: [log.zip](https://github.com/Jackett/Jackett/files/2442307/log.zip)

**Comment by garfield69** [comment]
should be fixed with pre-release v0.10.258 onwards.

**Comment by gipasoft** [comment]
I confirm that the issue is fixed in v0.10.258, thanks!
