### ISSUE TITLE
Tracker request: libble

### ISSUE THREAD

**Issue by joemarshalljm** [Jackett/Jackett#3897]
I've talked to the dev of libble.me and they're okay to work with you to add support. I can offer an invite.

**Comment by garfield69** [comment]
If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by garfield69** [comment]
BTW, whats the full address for libble please?

**Comment by garfield69** [comment]
never mind. its libble.me

**Comment by groenator** [comment]
If you are looking for an invite let me know and I can send you one.

**Comment by garfield69** [comment]
yes thanks. 
garfieldsixtynine @ gmail.com
I'll register asap,  but I wont be able to start work on the indexer for a couple weeks yet.

**Comment by groenator** [comment]
No problem, I'll send you the invite now.

I think they still open to sign up. Do you mind trying first and see if it
works?

If not, I'll send you an invite.

**Comment by garfield69** [comment]
registration and login successful.

**Comment by groenator** [comment]
Great!

**Comment by garfield69** [comment]
the layout of the search results (grouping of a title row, with one or more torrents rows) is not suitable for cardigann processing.
this indexer will need to be coded in c#

**Comment by tkdrob** [comment]
This tracker just had open signups. Its would be nice to have this indexer added

**Comment by koushik-sen-vst-au4** [comment]
Please provide me a invite at senkoushik91@gmail.com.

I will also be able to help you.

**Comment by JakeShirley** [comment]
Took a swing at implementing this in C#.

**Comment by garfield69** [comment]
closed with PR #3897

**Comment by garfield69** [comment]
Jackett 0.16.1204

**Comment by garfield69** [comment]
https://libble.me/ cloudflare Web server is down Error code 521

**Comment by garfield69** [comment]
online
