### ISSUE TITLE
7tor torrent issie

### ISSUE THREAD

**Issue by xFilosofx** [Jackett/Jackett#3902]
**Jackett version**:  0.10.250
**Mono version** (if not using Windows):  5.14.0.177
**OS version**: Ubuntu 18.04

Tracker test failed.

Log Jacket:

Jackett.Common.IndexerException: Exception (seventor):  ---> Jackett.Common.ExceptionWithConfigData   at Jackett.Common.Indexers.SevenTor+<>c__DisplayClass8_0.<ApplyConfiguration>b__0 () [0x0000b] in C:\projects\jackett\src\Jackett.Common\Indexers\7tor.cs:1600    at Jackett.Common.Indexers.BaseIndexer+<ConfigureIfOK>d__64.MoveNext () [0x00034] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:267  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Indexers.SevenTor+<ApplyConfiguration>d__8.MoveNext () [0x0018b] in C:\projects\jackett\src\Jackett.Common\Indexers\7tor.cs:1597  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Indexers.SevenTor+<PerformQuery>d__9.MoveNext () [0x001e0] in C:\projects\jackett\src\Jackett.Common\Indexers\7tor.cs:1642  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x00047] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:331     --- End of inner exception stack trace ---   at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x000e6] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:351  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x00024] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:815  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x00059] in C:\projects\jackett\src\Jackett.Common\Services\IndexerManagerService.cs:222  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Server.Controllers.IndexerApiController+<Test>d__15.MoveNext () [0x000e1] in C:\projects\jackett\src\Jackett.Server\Controllers\IndexerApiController.cs:141  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <f5622e7f79be469e83d9e2bde9addd07>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x00042] in C:\projects\jackett\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:29

-------------------------------

**Comment by garfield69** [comment]
Yeah, nah. The stack trace is of little use to me. Really need to see the messages in the log just before the event, they may yield a more useful clue.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by xFilosofx** [comment]
Hello, thanks for fast responce. The full log file is attached to this message.
[new 2.txt](https://github.com/Jackett/Jackett/files/2446037/new.2.txt)

**Comment by garfield69** [comment]
you are getting http 451:
```
In computer networking, "HTTP 451 Unavailable For Legal Reasons" is an error status code of the
 HTTP protocol to be displayed when the user requests a resource which cannot be served for
 legal reasons, such as a web page censored by a government.
```
nothing to do with jackett.
