### ISSUE TITLE
[ilcorsaronero] Exception (ilcorsaronero): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /build/mono-5.14.0.177/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by nick2k3** [Jackett/Jackett#3906]
Hi Everyone,
I am having again the same issue in a previous post of mine:
https://github.com/Jackett/Jackett/issues/3718

the certificate of this tracker is Let'sencrypt so I think this situation is going to be cyclical.

Can anyone update the code as done last time?
Thanks,

**Comment by garfield69** [comment]
fixed in jackett pre-release v0.10.258 onwards.
