### ISSUE TITLE
M-Team results aren't showing real file size and wrong date

### ISSUE THREAD

**Issue by TRaSH-** [Jackett/Jackett#3907]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.258.0
**Mono version** (if not using Windows):  5.14.0.177

-------------------------------
![image](https://user-images.githubusercontent.com/6155095/46492846-080e0000-c80f-11e8-88f1-368dc0578688.png)

The biggest issue is the file size because Radarr will ignore it because the size is to small.
Is this a know issue or something new ?
I did a search but couldn't find anything about it.

**Comment by garfield69** [comment]
its likely m-team have made changes to their html results page and the jackett indexer needs to be amended to cope.
i don't have a login for this site but I can make changes if you are willing to provide a sample of the html used.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by TRaSH-** [comment]
@garfield69 
Hope this will do
[log.txt](https://github.com/Jackett/Jackett/files/2447811/log.txt)

**Comment by TRaSH-** [comment]
@garfield69 
I'm getting now a 
![image](https://user-images.githubusercontent.com/6155095/46502159-c0e03900-c827-11e8-88dc-080d056f492c.png)

This is the new log
[log.txt](https://github.com/Jackett/Jackett/files/2448085/log.txt)

**Comment by garfield69** [comment]
bugger, apparently I got my selector count wrong, it appears to be out by 1.
try jackett pre-release v0.10.264 and see if that improves matters.

**Comment by TRaSH-** [comment]
@garfield69 
Still getting the following error
![image](https://user-images.githubusercontent.com/6155095/46503906-a2c90780-c82c-11e8-8f15-e2a4b0b112b8.png)

This is the new log
[log.txt](https://github.com/Jackett/Jackett/files/2448196/log.txt)

**Comment by garfield69** [comment]
OK. Sorry. 
There is more going on here than is apparent from the logs you have provided so far. Or else I'm not astute enough to see what the real problem is.
The indexer is doing two passes for each test, one using 
```yaml
      - path: torrents.php
        categorymappings: ["!", 410, 429, 424, 430, 426, 437, 431, 432, 436, 425, 433, 411, 412, 413]
```
and another using
```yaml
      - path: adult.php
        categorymappings: [410, 429, 424, 430, 426, 437, 431, 432, 436, 425, 433, 411, 412, 413]
```
and I suspect I would need a login to view and debug the full process.

So I have reverted my changes back to the original.

@kaso17  Hopefully you still have a login for this site, can you take a look at what is going on with this ticket please? Thanks.

**Comment by TRaSH-** [comment]
Thnx for the help,
Hope this can be solved soon.

**Comment by kaso17** [comment]
@TRaSH- 
Enabling the "Show number of comments X last comment on tooltip" option in the user CP/tracker options should fix the problem. With 2101ebb2dea82be996f0afeca7d23c42ed34e5f4 the problem should be fixed independ of the option.
