### ISSUE TITLE
[REQ] New Tracker: https://thecafe.me "TS Special Edition Provider"

### ISSUE THREAD

**Issue by nigelhooper** [Jackett/Jackett#391]
Would someone be kind enough to add https://thecafe.me it is "Powered by TS Special Edition v.7.3" which is the same software as used by tvchaosuk.com so with a bit of luck it should be pretty straightforward.

Let me know if you need an invite.

Here are all the categories that I can map, they use the same id for some categories e.g. PS3 & PS4 etc hope this is ok? please let me know if there is anything else that you need:

AddCategoryMapping("19", TorznabCatType.ConsolePSP);
AddCategoryMapping("63", TorznabCatType.ConsoleWii);
AddCategoryMapping("19", TorznabCatType.ConsolePS3);
AddCategoryMapping("18", TorznabCatType.ConsoleXboxOne);
AddCategoryMapping("19", TorznabCatType.ConsolePS4);
AddCategoryMapping("27", TorznabCatType.Movies);
AddCategoryMapping("28", TorznabCatType.MoviesOther);
AddCategoryMapping("30", TorznabCatType.MoviesSD);
AddCategoryMapping("29", TorznabCatType.MoviesHD);
AddCategoryMapping("60", TorznabCatType.Movies3D);
AddCategoryMapping("82", TorznabCatType.MoviesBluRay);
AddCategoryMapping("30", TorznabCatType.MoviesDVD);
AddCategoryMapping("31", TorznabCatType.Audio);
AddCategoryMapping("35", TorznabCatType.AudioMP3);
AddCategoryMapping("36", TorznabCatType.AudioVideo);
AddCategoryMapping("5", TorznabCatType.AudioAudiobook);
AddCategoryMapping("33", TorznabCatType.AudioLossless);
AddCategoryMapping("92", TorznabCatType.PCMac);
AddCategoryMapping("20", TorznabCatType.PCGames);
AddCategoryMapping("93", TorznabCatType.PCPhoneAndroid);
AddCategoryMapping("42", TorznabCatType.TV);
AddCategoryMapping("44", TorznabCatType.TVSD);
AddCategoryMapping("43", TorznabCatType.TVHD);
AddCategoryMapping("37", TorznabCatType.TVSport);
AddCategoryMapping("91", TorznabCatType.TVAnime);
AddCategoryMapping("16", TorznabCatType.TVDocumentary);
AddCategoryMapping("4", TorznabCatType.Books);
AddCategoryMapping("7", TorznabCatType.BooksEbook);
AddCategoryMapping("6", TorznabCatType.BooksComics);
AddCategoryMapping("8", TorznabCatType.BooksMagazines);

**Comment by kaso17** [comment]
looks like it is dead by now
