### ISSUE TITLE
[yts] Parse error: Count cannot be less than zero.Parameter name: count (Config)

### ISSUE THREAD

**Issue by coder2000** [Jackett/Jackett#3916]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.250.0
**Mono version** (if not using Windows):  

-------------------------------
[log.txt](https://github.com/Jackett/Jackett/files/2451358/log.txt)

**Comment by garfield69** [comment]
yts is currently broken. see #3908 for first report.
as at this moment, yts is not responding,
![image](https://user-images.githubusercontent.com/6933240/46549588-10f5f300-c92f-11e8-97d4-8d091ff2615b.png)
nothing Jackett can do about this.
wait and see if it comes back up.

**Comment by garfield69** [comment]
YTS have since switched back to yts.am !!
upgrade to the latest pre-release 0.10.280 to resolve.
