### ISSUE TITLE
[megabliz] Login failed: Selector

### ISSUE THREAD

**Issue by Indubitably1** [Jackett/Jackett#3926]
Synology NAS running DSM 6.2-23739 Update 2
Mono version 5.8.0.108-11
Jackett version 0.8.490-6

In Jackett, I added indexer Mega-Bliz
I had previously confirmed registration and logged into the website
In Jackett, I entered the verified username/password
Pressed 'Okay'
Got error message:

"An error occured while updating this indexer
Login failed: Selector "li a[href^="logout.php?hash_please="]" didn't match"

Re-checked and re-entered username/password
Pressed 'Okay'
Got the same error message as above.

**Comment by djwayne1985** [comment]
i have tried this and nothing its still the same error

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.
