### ISSUE TITLE
[ilcorsaroblu] Exception (ilcorsaroblu): The operation has timed out.: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by gandalf764** [Jackett/Jackett#3927]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
https://www.ilcorsaroblu.org/ is currently responding with an empty HTML page, so it looks like the site is having technical difficulties.
nothing to do with jackett.
just have to wait and see if they manage to sort out the problem.

**Comment by garfield69** [comment]
the site is back up, albeit very slow to respond.
