### ISSUE TITLE
[yts] Exception (yts): A contagem não pode ser inferior a zero.Nome do parâmetro: count: Parse error (Test)

### ISSUE THREAD

**Issue by alexandreSRibeiro** [Jackett/Jackett#3929]
unable to connect to this indexer

**Jackett version**: 0.10.250.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
upgrade your jackett to the latest release 0.10.267 to fix this.

**Comment by garfield69** [comment]
correction. YTS is returning error 525 at the moment. the site is having technical difficulties.
nothing to do with jackett.
just have to wait and see if yts sort the problem out.

**Comment by garfield69** [comment]
yts is back online and accessible via jackett 0.10.267

**Comment by garfield69** [comment]
yts broken again, same error as previous, cloudflare 525

**Comment by garfield69** [comment]
YTS is back up.
