### ISSUE TITLE
Research [OS X] run/start script on login

### ISSUE THREAD

**Issue by ldexterldesign** [Jackett/Jackett#393]
Hey,

Cheers for software

I'm looking to setup a run/start script on login (i.e. ``mono JackettConsole.exe``) - can anyone point me to a guide/tutorial or offer a [OS X] solution?

(Sorry, newbie question, never done this kind of thing before yet)

Hope to hear back

Kind thanks

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
Is ``launchd`` the current OS X solution here?

Hope to hear back

Kind thanks

**Comment by flightlevel** [comment]
https://www.google.com/search?q=osx+sonarr+startup

Jackett and sonarr both run on Mono.
Change to instructions to start Jackett instead of Sonarr

**Comment by ldexterldesign** [comment]
Hey @flightlevel,

Cheers for reply

Specifically, do you mean the plist instruction? ~ https://github.com/Sonarr/Sonarr/wiki/Autostart-on-OS-X

Kind thanks

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP
