### ISSUE TITLE
[yggtorrent] Login failed: Selector not taking the new domain address https://yggtorrent.to/user/login

### ISSUE THREAD

**Issue by Oscardadon** [Jackett/Jackett#3930]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by Oscardadon** [comment]
Hi the issue is using jackett to add ygg as an indexer the website is not
updated to the new domain still shown as yggtorrent.com instead of
yggtorrent.to.

[image: image.png]
Cordialement,

Oscar Dona
Technicien Informatique
CIUSSS Centre-Ouest-De-L'Île de Montréal
Hôpital Général Juif | Jewish General Hospital
3755 ch. de la Côte-Sainte-Catherine Rd.  Suite  B-118.10
Montréal, QC  H3T 1E2
514-340-8222 ex: 28254
Fax: 514-340-8151
Courriel Travail: oscar.dona.ccomtl@ssss.gouv.qc.ca
Cellulaire: 438-828-7470
Courriel personnel: felderdona@gmail.com

**Comment by garfield69** [comment]
the ygg indexer was switched to the new current domain https://yggtorrent.to/ with jackett  v0.10.186 21 days ago.
upgrade your jackett to the latest release v0.10.267
