### ISSUE TITLE
IPtorrents - Jackett

### ISSUE THREAD

**Issue by barichon** [Jackett/Jackett#3932]
Hello,

No way to add Iptorrents as indexer, whatever URL is use 

- https://iptorrents.com
- https://iptorrents.com/
- https://iptorrents.com/t
- https://iptorrents.com/t/
- https://iptorrents.com/login.php
- https://iptorrents.com/login.php/

No way to add it, after clicking on "Okay" it will load and give:

```
 An error occured while updating this indexer
Your cookie did not work: Parse error
Click here to open an issue on GitHub for this indexer.
```

**Comment by garfield69** [comment]
the correct site link is `https://iptorrents.com/` or any of the others alternatives that show up in your jackett IPT config, in the banner under the site link. (clicking on any of them will auto load it in the site link box.

you need to use the **full** cookie string, so:
1. open your browser, and access https://iptorrents.com/ (or whatever alternateyou are using) and login.
2. then follow the instructions at https://github.com/Jackett/Jackett/wiki/Finding-cookies to select and copy the full cookie string
3. paste/replace the cookie in the jackett IPT config cookie box and click OKAY

let us know how you go.

**Comment by Motophan** [comment]
How do I get to the config cookie box

**Comment by garfield69** [comment]
use your jackett dashboard and click on the wrench icon for your iptorrent indexer, scroll down till you see the *Full Cookie Header* box
![image](https://user-images.githubusercontent.com/6933240/46900196-ed1c4980-cefa-11e8-8b75-722e9c4623df.png)

**Comment by kendog819** [comment]
Also having this same issue, but there is no "Full Cookie header Area"

![image](https://user-images.githubusercontent.com/11353628/47591449-a2102680-d93d-11e8-96ab-75f936c45144.png)

**Comment by garfield69** [comment]
@kendog819 what version of Jackett are you using?

**Comment by Motophan** [comment]
I also have the identical page kendog819 has, not the one garfield69 has.
My version number is 0.10.380.0 I click update.

**Comment by garfield69** [comment]
There is currently an outstanding issue with iptorrents #4073, so I would wait for this to be resolved first.
Then I suggest you try using the trashbin icon on your jackett dashboard to delete your current indexer profile, then add a fresh one to start again.
