### ISSUE TITLE
i couldn't register or access my old account on t411 new website ! ggytorrent ! 

### ISSUE THREAD

**Issue by yas43dz** [Jackett/Jackett#3934]
hello guys ! 
i need an audio-book and the only place i could find that spécifique audio-book i was looking for is the replacement torrent site of the old ''t411''  which is called now "yggtorrent.so" ! i had an account on t411 before and now i tried to log in with it but every time i try it doesn't accept it ! i tried to open a new one but there was a problem with captcha on the registration process it just doesn't work ! 

can any one help ?? ~~or download the torrent file for me ! or send me the torrent direct link to put it in the utorrent so i can download it ?~~
[edit] do not request downloads via github. this is a software development platform not a file request forum.

= this is the url => **removed**

**Comment by garfield69** [comment]
the same torrent is available at the official ygg site https://yggtorrent.to/
try your old login there, or see if you can register, maybe their site's registration works.

**Comment by yas43dz** [comment]
maaaaaaaaaaaaaaaaaaaaaaaaaaaaan youuuuuuuuur are the man !!!! thanks for ever !!!!!!! <3
