### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Got redirected to another domain. Try changing the indexer URL to https://www3.yggtorrent.to/.: Parse error (Test)

### ISSUE THREAD

**Issue by foux** [Jackett/Jackett#3935]
Unable to login to YGGTorrent. Changing the URL still raises the issue

**Jackett version**:  0.10.269.0
**Mono version** (if not using Windows):  5.14.0.177

Log file : 
[log.txt](https://github.com/Jackett/Jackett/files/2454959/log.txt)

-------------------------------

**Comment by garfield69** [comment]
yeah, YGG changed their domain yet again!
Jackett pre-release 0.10.270 will handle the new domain automatically.

OR you can change it yourself by accessing your jackett dashboard, editing the YGG config and replacing the site link to https://www3.yggtorrent.to/
if clicking on OKAY generates an error, click CLOSE instead, and EDIT it again. the site link should remain https://www3.yggtorrent.to/ and OKAY will work the second time.

**Comment by foux** [comment]
Thanks @garfield69. I got stuck on the first "failed" (when changing the URL) and thought that was it. Thanks a lot for the tip
