### ISSUE TITLE
Log spamming:  Info Skipping update check as it is disabled

### ISSUE THREAD

**Issue by mfrelink** [Jackett/Jackett#394]
I disabled auto update but now syslog is being spammed every ~minute with the following message:

`Info Skipping update check as it is disabled`

I'm not sure it's necessary to check every minute for an update and log it :)

**Comment by zorvalth** [comment]
Same here, I was just about to open a ticket about that.

**Comment by FedoraTipper** [comment]
Take a look at: https://github.com/Jackett/Jackett/issues/154

**Comment by kaso17** [comment]
Is this still a problem?
The update check should run only once every 24 hours

**Comment by armani316** [comment]
I'm closing this for now. @mfrelink and @zorvalth. If the issue persists, feel free to reopen this :)
