### ISSUE TITLE
[req]  GranTorrent Spanish public

### ISSUE THREAD

**Issue by juanuto** [Jackett/Jackett#3946]
Requesting new tracker to be added - Grantorrent
~~https://grantorrent.net~~ ~~https://grantorrent.nl/~~ ~~https://grantorrent.ch/~~ (movies)
~~https://grantorrent.net/series/~~ ~~https://grantorrent.nl/series~~  ~~https://grantorrent.ch/series~~ (tv)
https://grantorrent.ac/

Thanks in advance.

**Comment by garfield69** [comment]
https://grantorrent.net/series/ cannot be processed with cardigann as the series details page contain multiple download links for each of the episodes in a series.
this will require a c# indexer.

**Comment by garfield69** [comment]
same applies to https://grantorrent.net. a search for venom takes you to a details page which then lists all the download links available so far for that movie. requires c# as cardigann cannot currently handle this.

**Comment by snakepage** [comment]
The are now https://grantorrent.nl/ . It is possible to add it on jackett? :)

**Comment by garfield69** [comment]
While the domain has changed, the engine is the same, which has a one-poster-many-torrents structure.
Which means I cannot write the indexer in yaml, so a volunteer will need to write a C# indexer to process the site.

**Comment by JorTurFer** [comment]
I am trying to add this indexed but I have doubts about how integrate the path route to decide between movies and series.
Can you say another indexer that works similar in order to know how should be resolved?
I have a little idea but I prefer if I can check another

**Comment by JorTurFer** [comment]
Another problem here is that the download links (and related information like quality or size) is in another page show the process should generate multiple requests. How should I handle this? Should it execute multiple requests?
Sorry for this questions but I don't have depth knowledge about this software and how it works

**Comment by ilike2burnthing** [comment]
@ngosang ping

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing

**Comment by ngosang** [comment]
I think it could be implemented in C#. Is similar to other Spanish trackers like Newpct and Divxtotal.

**Comment by garfield69** [comment]
closing as stale.
