### ISSUE TITLE
YTS issue

### ISSUE THREAD

**Issue by Co0ljay** [Jackett/Jackett#3948]
YTS updated the URL for the site from https://yts.ag to https://yts.am

When updating the URL the following error is displayed:
 An error occured while updating this indexer
Parse error: Count cannot be less than zero. Parameter name: count

**Comment by Co0ljay** [comment]
Updated to 10.280.  Following error:

Parse error: Unexpected character encountered while parsing number: ;. Path 'margin', line 1, position 9.

**Comment by garfield69** [comment]
YTS is broken yet again. seems what ever issue they are having with cloudflare keeps returning within 12 hours of what ever they do to fix it.
little to do here but wait for hem to sort it out.

**Comment by garfield69** [comment]
yts api seems to be back up and running again and jackett test is successful.
can't say the same for the yts web site, it is still generating cloudflare 522 and 525 but as long as the api server is ok then we are happy campers.
