### ISSUE TITLE
[req] tparser.me

### ISSUE THREAD

**Issue by 894-572** [Jackett/Jackett#3949]
https://tparser.me/ is a meta-search engine for Cyrillic trackers, including rutracker.org, nnm-club.ru, kinozal.tv, rutor.org and underverse.in. Rutracker results don't require an account, and neither do any other listed sources. The interface is in Russian, translating major terminology for Jackett is trivial.

**Comment by garfield69** [comment]
unfortunately the html that this site produces is dynamically generated by javascript, which means it cannot be scraped by traditional means and is therefore incompatible with Jackett.

To see what I mean, do a search using your browser, then right click and select *view page source*.
As you can see, the results are stored in JS vars that need decoding.

**Comment by 894-572** [comment]
To all reading this issue, Tparser domain is now https://tparser.me/

**Comment by garfield69** [comment]
http://tparser.me/ currently returning ERR_CONNECTION_REFUSED as is the https domain.

**Comment by 894-572** [comment]
The engine seems to be down for good. Closing the issue.
tparser.org redirects to `track.tkbo.com` (some advertising platform).
