### ISSUE TITLE
unable to add BeyondHD to configured indexers

### ISSUE THREAD

**Issue by happypaps** [Jackett/Jackett#395]
previously had no issues with this indexer, but after BeyondHD moved to new domain indexer was no longer functional despite newest update with updated domain. tried to delete indexer and re-add, but now when i click beyondhd icon nothing happens. when i click beyondhd icon the indexer selection screen closes and beyondhd is not added to configured indexer list nor do i get the setup screen. help?

**Comment by hthighway** [comment]
I am seeing the same issue.

**Comment by Killertoooth** [comment]
I had to wait ~30 seconds after clicking the BeyondHD icon before the setup screen popped up. You may just need to give it some more time before exiting or clicking on something else.

**Comment by happypaps** [comment]
tried this, no luck. attempted on internet explorer, edge and chrome with no success

**Comment by d2dyno** [comment]
I'm only able to do it remotely (reverse proxy), which requires me to input the cookie string for my session.

**Comment by happypaps** [comment]
log attached
[log.txt](https://github.com/Jackett/Jackett/files/362578/log.txt)

**Comment by flightlevel** [comment]
Should be fixed in latest release
