### ISSUE TITLE
[yts] Exception (yts): Count cannot be less than zero.Parameter name: count: Parse error (Test)

### ISSUE THREAD

**Issue by Tejas-D** [Jackett/Jackett#3951]
The YTS Indexer is not functioning correctly. 

**Jackett version**:  0.10.273.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
YTS have since switched back to yts.am !!
upgrade to the latest pre-release 0.10.280 to resolve.
