### ISSUE TITLE
[retroflix] Login Failed, got redirected. (Cookie format changed)

### ISSUE THREAD

**Issue by pyr0ball** [Jackett/Jackett#3959]
Attempting to add Retroflix as a tracker, but the format of cookie described in the wiki is very different than what shows up in RetroFlix site. Not sure if this is just a documentation issue or if their format is specifically different, but either way I'm unable to add it currently

**Jackett version**:  0.10.273.0
**Mono version** (if not using Windows):  5.14.0.177 

-------------------------------
![image](https://user-images.githubusercontent.com/8482805/46753893-ea5cf280-cc75-11e8-90af-5b650ef35d92.png)

**Comment by garfield69** [comment]
the wiki simply provides an example of how to find the cookie.
Once you have logged into retrofix and used the chrome network tool to find the cookie, copy the **whole** cookie string and paste it into your Jackett retrofix config.

**Comment by pyr0ball** [comment]
Take a look at the screenshot. There's no cookie string. It's split up into
different sections

**Comment by garfield69** [comment]
click on the header tab, and scroll down to the cookie parm, as is shown in the wiki.

**Comment by pyr0ball** [comment]
derp, I see it now. Thanks for the assist!
