### ISSUE TITLE
[REQ] HD4Free

### ISSUE THREAD

**Issue by d2dyno** [Jackett/Jackett#396]
I'd like to request the HD4Free tracker to be added to Jackett. Registrations are currently **open**. This tracker is the home of the popular encoding group LEGiON.

Mapping for categories are attached below. 
[HD4Free mapping.txt](https://github.com/Jackett/Jackett/files/356297/HD4Free.mapping.txt)

**Comment by jayotterbein** [comment]
For what it's worth, HD4Free can be used directly in sonarr and couchpotato.  I would suggest using the tracker directly because it's less likely to break on updates to their site.

**Comment by d2dyno** [comment]
@jayotterbein Correct. Still, I love the universal search that Jackett enables me to have, so I'd still love to see this :)

**Comment by kaso17** [comment]
If someone has an invite I would add it

**Comment by savahu** [comment]
I have. Will send tomorrow.

**Comment by savahu** [comment]
@kaso17 I sent it to your email!

**Comment by kaso17** [comment]
thank you, got it, will work on it soon
