### ISSUE TITLE
[Tracker Request] Prostylex

### ISSUE THREAD

**Issue by OminusHush** [Jackett/Jackett#3966]
Is it possible for the following semi-private tracker to be added to Jackett?

http://prostylex.com/

You need to login to be able to download the .torrent file.

**Comment by garfield69** [comment]
I've opted to download the magnets as these do not require a login.
Jackett pre-release 0.10.307 begins support for prostylex.

**Comment by garfield69** [comment]
http://prostylex.com/ returning ERR_NAME_NOT_RESOLVED
is the site gone, changed domain, or just broken?

**Comment by OminusHush** [comment]
The .com version is down, but you should be able to access it using
http://prostylex.org

**Comment by garfield69** [comment]
thanks. updated the domain to .org for the next jackett release.

**Comment by garfield69** [comment]
https://prostylex.org/ stuck on a cloudflare please-wait-while-we-check-your-browser page, eventually returning 
Error 524 A timeout occurred
Just me or is the site broken, gone or moved to a new domain?

**Comment by ilike2burnthing** [comment]
Back up here, though loading pretty slowly. Maybe an intermittent issue?

**Comment by garfield69** [comment]
yes

**Comment by ilike2burnthing** [comment]
https://prostylex.org/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://prostylex.org/ returns Error 520 Web server is returning an unknown error
uptime checkpoints all getting 503 Service Temporarily Unavailable

**Comment by garfield69** [comment]
online, if a little slower than usual.

**Comment by ilike2burnthing** [comment]
https://prostylex.org/ - `Site is down for a little while`

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://prostylex.org/ returns 503 Service Temporarily Unavailable

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
@garfield69 are you getting `Login Failed, got redirected.` in Jackett?

It's to https://prostylex.org/account-login.php?returnto=%2Fsearch.php so obviously something is going wrong.

I tried post, form, and cookie login, as well as changing the test path, but same result. Made sure I have access in browser, logged out and in again, no unread messages, etc. all the usual.

**Comment by garfield69** [comment]
Me too.  Re: cookie, did you try the Cookie+UA combo?

**Comment by ilike2burnthing** [comment]
No, I'll try that now.

**Comment by garfield69** [comment]
v0.20.1627

**Comment by ilike2burnthing** [comment]
https://prostylex.org/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
@ilike2burnthing  are you able to use the indexer? 
I keep getting flaresolverr cookies not valid, whether its from a native browser session cookie/UA, or from a hideme session.
Just me?

**Comment by ilike2burnthing** [comment]
Ah, same.

**Comment by ilike2burnthing** [comment]
Now getting the same thing for TorrentQQ. If this continues, FlareSolverr may require another update.

**Comment by garfield69** [comment]
yup, and for me in addition: 0magnet, bt4g, exttorrents, idope, torrentcore

**Comment by ilike2burnthing** [comment]
Ah :/

@ngosang if you get some free time this weekend, may be worth a look.

**Comment by ilike2burnthing** [comment]
https://prostylex.org/ - Connection timed out - Error code 522

**Comment by garfield69** [comment]
v0.20.2304
