### ISSUE TITLE
[ilcorsaronero] Exception (ilcorsaronero): Connection refused: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by theDoc5655** [Jackett/Jackett#3968]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by theDoc5655** [comment]
Simply adding Thepiratebay by the provided menu it simply won't complete
the check, i've just resolved the problem myself simply using a link to a
proxy of the site even if the site is normally accessible.

Il gio 11 ott 2018, 18:35 jackettbot[bot] <notifications@github.com> ha
scritto:

**Comment by garfield69** [comment]
I have no problems using or testing ilcorsaronero (https://ilcorsaronero.info/)
if you are unable to use the default site link then the most likely explanation is that your ISP is blocking it.
to confirm this, access https://ilcorsaronero.info/ directly from your browser and see what you get.
report back your result. :-)

**Comment by garfield69** [comment]
additionally, ensure your Jackett version is at least v0.10.258, as from this point forward Jackett includes a fix for the invalid CA that the site is currently using.

**Comment by bobonov** [comment]
Jackett Version 0.10.304.0 on linux with mono version 5.16.0.179
It seem that it changed domain from https://ilcorsaronero.info/ to https://ilcorsaronero.ch/
pointing to the new domain I get the following error
Exception (ilcorsaronero): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /build/mono-5.16.0.179/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request
tell me if you need more info (and some clue where to get them, I'm quite new to jackett)

**Comment by garfield69** [comment]
Thanks for the heads up.
No only have they have changed their domain today, but we have to ignore their new invalid CA as well.
try Jackett 0.10.314 which should have the fix.
