### ISSUE TITLE
[REQ]Torrenting Integration

### ISSUE THREAD

**Issue by bernalvarela** [Jackett/Jackett#398]
I really appreciate the inclusion of this tracker.

https://www.torrenting.com/

Best regards!

**Comment by SgtFalstaff** [comment]
I'd like to second this request. 
Cheers!

**Comment by Githubtordl** [comment]
Hi, any chance of adding this tracker, currently having opensignups

**Comment by kaso17** [comment]
added to my todo list

**Comment by kaso17** [comment]
added with c9e5f1468784e71e41825bed2734444b0ebf4aaf
