### ISSUE TITLE
No longer able to use Speed.cd

### ISSUE THREAD

**Issue by Cheesegawd** [Jackett/Jackett#399]
So in the past week or so, speed.cd has failed to query. I thought it was because of an update, so I uninstalled and reinstalled previous version, but it didn't fix it. 

The issue that I see is when I try to connect with my username and password, it pops up with "Configuration Failed:" with no reason why. The logs don't show much that I can decipher. 
[LOG.txt](https://github.com/Jackett/Jackett/files/362345/LOG.txt)

Maybe Speed.cd changed something on their end?

**Comment by maphex** [comment]
Having same issue.

**Comment by malfuncion** [comment]
Jackett Version 0.7.290.0

Can confirm same issue for me as well.

**Comment by malelan** [comment]
same here, speed.cd has also stopped working in sickrage for me.  so it's definitely on their end.

**Comment by xxcamouflagexx** [comment]
Unfortunately the same for me as well.

**Comment by flightlevel** [comment]
Should be fixed in latest release
