### ISSUE TITLE
[1337x] Exception (1337x): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /build/mono-5.16.0.179/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by adriangigliotti** [Jackett/Jackett#3995]
Hi,

I am receiving this error when adding trackers:

`[1337x] Exception (1337x): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /build/mono-5.16.0.179/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)`

I have seen this issue in this 'Issues' section before but none of the fixes worked for me.
I also tried posting in Gitter, although I didn't get any replies on my issue.

**Jackett version**:  
`Jackett Version 0.10.304.0`

**Mono version**:
```
Mono JIT compiler version 5.16.0.179 (tarball Thu Oct  4 10:29:10 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-/)
	GC:            sgen (concurrent by default)
```

Thanks

**Comment by garfield69** [comment]
did you try installing *mono-complete* and rebooting after the install is finished?

**Comment by garfield69** [comment]
please provide the output from `curl -vvv https://1337x.to`

**Comment by adriangigliotti** [comment]
```
curl -vvv https://1337x.to
* Rebuilt URL to: https://1337x.to/
*   Trying 2001:8006:3002:1110::21...
* Connected to 1337x.to (2001:8006:3002:1110::21) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / RSA_AES_128_CBC_SHA1
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* SSL: certificate subject name (www.tvicb.com) does not match target host name '1337x.to'
* Closing connection 0
curl: (51) SSL: certificate subject name (www.tvicb.com) does not match target host name '1337x.to'
```

Looks like an issue with my SSL certs.

**Comment by garfield69** [comment]
actually it looks like your ISP is blocking your request by routing you to a dead end address www.tvicb.com
try switching your DNS to googles public DNS 8.8.8.8 or 8.8.4.4 and see if that makes a difference.

**Comment by adriangigliotti** [comment]
I switched to Cloudflare's DNS Server (1.1.1.1) and it worked! 

Awesome, thank you very much.

**Comment by garfield69** [comment]
excellent.
