### ISSUE TITLE
please add the following sites

### ISSUE THREAD

**Issue by rafiks** [Jackett/Jackett#3996]
https://ytstv.com/
https://www.sport-video.org.ua/

thanks,

**Comment by garfield69** [comment]
Im sorry, but neither site is suitable for web scraping by jackett via cardigann yaml.
the search results page they both provide contains only links to individual details page.
we could code the indexers in c#, but the overhead of fetching every details page for all the entries on the results page would cause an excessive amount of network traffic.
IMO its just not worth the effort.
