### ISSUE TITLE
[REQ]Totally Kids

### ISSUE THREAD

**Issue by harroguk** [Jackett/Jackett#4]
Getting kids programs is the bane of my life.

http://www.totallykids.tv/

**Comment by flightlevel** [comment]
This is a private tracker, we would require an invite to attempt it.

**Comment by harroguk** [comment]
I have no invites however they are available upon request from some private trackers.

**Comment by armani316** [comment]
'Invite needed' label should be added in case there's interest in adding support for this tracker.

**Comment by flightlevel** [comment]
As zone117x says in https://github.com/Jackett/Jackett/issues/5#issuecomment-153216938 
This issue is more complex than simply adding in a new tracker due to the way cartoons are named
Highly likely it requires significant work in Sonarr or some type of XEM setup
Closing this issue as there isn't a lot we can do from Jackett. If anyone from the community has ideas on how it can be implemented feel free to create a new issue

**Comment by kaso17** [comment]
I'll reopen it. We still should support it, not everyone is using Jackett just for sonarr integration.
@harroguk please provide details on why trackers we can find invites.

**Comment by zone117x** [comment]
@kaso17 IIRC these cartoon tracker guys are the same or similar community. And they were lax about invites when mentioning wanted to develop support for them.

**Comment by MacGatlin** [comment]
@kaso17 Signups have opened https://opentrackers.org/totallykids/

**Comment by kaso17** [comment]
To late for me "Maximum number of users reached"

**Comment by garfield69** [comment]
Try out Jackett pre-release v0.10.900

**Comment by garfield69** [comment]
http://www.totallykids.tv/ currently returning
![image](https://user-images.githubusercontent.com/6933240/77237307-f51e0400-6c2b-11ea-8393-a08049bc2204.png)
anyone know if this is a temporary issue, or has the site closed, or moved on to a new domain?

**Comment by thetennismaster** [comment]
@garfield69 - Temporary. They're back now.

![image](https://user-images.githubusercontent.com/46232708/77252706-9f5a5380-6c4d-11ea-8e0e-6021651f1f4b.png)

**Comment by garfield69** [comment]
Thanks.

**Comment by ngosang** [comment]
http://www.totallykids.tv/
This domain has expired.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://www.totallykids.tv/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://www.totallykids.tv/ returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online.

**Comment by garfield69** [comment]
http://www.totallykids.tv/ returning ERR_CONNECTION_RESET
clearly unstable ATM same as sister site cartoonchaos

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://www.totallykids.tv/ returning ERR_CONNECTION_TIMED_OUT
just me?

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
http://www.totallykids.tv/ returning ERR_CONNECTION_RESET
https://www.uptrends.com/tools/uptime reports 42 with tcp connection failed and 1 with http connect failure across sites worldwide

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
http://www.totallykids.tv/ returning ERR_CONNECTION_RESET

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://www.totallykids.tv/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
not for me I still see ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
Same, must be up and down atm

**Comment by ilike2burnthing** [comment]
back up, checked several times over the past hour

**Comment by garfield69** [comment]
offline again

**Comment by ilike2burnthing** [comment]
back up for the past hour, who knows how long it will last...

**Comment by garfield69** [comment]
http://www.totallykids.tv/ really really slow, like 5 minutes waiting for the page to load

**Comment by garfield69** [comment]
back to normal

**Comment by garfield69** [comment]
http://www.totallykids.tv/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
now showing
![image](https://user-images.githubusercontent.com/6933240/159204475-c4f79055-1064-4098-86b1-ec148b5a2cb2.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://www.totallykids.tv/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online.

**Comment by moonsugar33** [comment]
Test search in TotallyKids => Found no results while trying to browse this tracker

**Comment by garfield69** [comment]
the indexer is working for me.
if you want help then please raise a fresh ticket and provide the info requested in the template.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/4#issuecomment-1246259366

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/4#issuecomment-1073468074

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://www.totallykids.tv/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/4#issuecomment-1591887027

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
Typical. I waited 6 hours before opening this just to be sure it wasn't a temporary issue, and then ...

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/4#issuecomment-1591887027

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/4#issuecomment-1591887027

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
v0.21.1764
