### ISSUE TITLE
[audiobookbay] A task was canceled. (Config)

### ISSUE THREAD

**Issue by ltjdym** [Jackett/Jackett#4002]
using QNAP NAS can't add http://audiobookbay.nl/

**Jackett version**:   Jackett Version 0.10.314.0
**Mono version** (if not using Windows):  QNAP QMono 5.14.0.177

AudioBookBay -
AudioBook Bay (ABB) is a semi-private Torrent Tracker for AUDIOBOOKS
Site Link

http://audiobookbay.nl/
This indexer has multiple known URLs:
http://audiobookbay.nl/
https://audiobookbay.la/
Click on an URL to copy it to the Site Link field.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

-------------------------------

Category | Description
-- | --
3030 | Audio/Audiobook

 An error occured while updating this indexer
A task was canceled.

**Comment by JaegerMaster** [comment]
I am alos facing the same issue while adding Audioookbay.

Below is the full log:

https://pastebin.com/raw/yQ5udzH

**Comment by kaso17** [comment]
" A task was canceled." indeicates a timeout during the request. please double check that your device can properly connect to the webserver as garfield already described.
