### ISSUE TITLE
[REQ] vanila.org

### ISSUE THREAD

**Issue by xFilosofx** [Jackett/Jackett#4003]
Login type: Form(post)
Desc: Vanila.org is Russian Semi-Private tracker for any media type.
Tracker Type: Semi-Private
categorymappings:
      # TV
      - {id: 1252, cat: TV, desc: "All TV Shows"}
      - {id: 503, cat: TV, desc: "Russian TV Series"}
      - {id: 504, cat: TV, desc: "TV Series"}
      - {id: 1355, cat: TV/FOREIGN, desc: "Asian TV Series"}
      - {id: 1415, cat: TV/FOREIGN, desc: "Indian, Latina, Turc TV Series"}
      - {id: 585, cat: TV/OTHER, desc: Video Lessons"}
      - {id: 1036, cat: TV/Sport, desc: TV Sport"}
      # Movies
      - {id: 442, cat: Movies, desc: "All Movies"}
      - {id: 463, cat: Movies/HD, desc: "Wordl Movies HD"}
      - {id: 962, cat: Movies/HD, desc: "World Movies UHD"}
      - {id: 963, cat: Movies/3D, desc: "World Movies 3D"}
      - {id: 465, cat: Movies/Other, desc: "World Movies Collection"}
      - {id: 466, cat: Movies/HD, desc: "Wordl Movies DVD\BD Rip"}
      - {id: 199, cat: Movies/Other, desc: "World Cartoons"}
      - {id: 467, cat: Movies, desc: "Classic Wordl Movies"}
      - {id: 1382, cat: Movies, desc: "CIS Movies"}
      - {id: 468, cat: Movies/Other, desc: "ART Movies"}
      - {id: 469, cat: Movies/Other, desc: "ART Movies Rip"}
      # Cartoons
      - {id: 28, cat: TV/Anime, desc: "All Cartoons/Anime"}
      - {id: 202, cat: TV/Anime, desc: "Cartoons"}
      - {id: 342, cat: TV/Anime, desc: "Cartoons - Disney\Pixar"}
      - {id: 893, cat: TV/Anime, desc: "Cartoons - Anime"}
      - {id: 200, cat: TV/Anime, desc: "Cartoons - Russian"}
      # Music
      - {id: 214, cat: Audio/MP3, desc: "All Lossy Music"}
      - {id: 165, cat: Audio/Lossless, desc: "All Lossless Music"}
      - {id: 139, cat: Audio/Video, desc: "Music Video"}
      - {id: 874, cat: Audio/Audiobook, desc: "Audiobook"}
      - {id: 7, cat: Audio/Other, desc: "Music Compilation"}
      # Books
      - {id: 536, cat: Books, desc: "All Books"}
      - {id: 537, cat: Books, desc: "Published Books"}
      - {id: 552, cat: Books/Magazines, desc: "Magazines"}
      - {id: 611, cat: Books/Technical, desc: "Technical"}
      # Other
      - {id: 3, cat: PC, desc: "PC Programs"}
      - {id: 4, cat: PC/Games, desc: "PC Games"}
      - {id: 5, cat: Console, desc: Console Games"}

**Comment by garfield69** [comment]
whats the link please?
this cannot be the right site? http://www.vanilla.org/
![image](https://user-images.githubusercontent.com/6933240/51959093-c2f59400-24b7-11e9-917f-ce0f56761101.png)

**Comment by garfield69** [comment]
sorry, brain dead moment. vanila with one L ;-)

**Comment by xFilosofx** [comment]
Hello, i tied add vanila.org on my Jacket today and have some issue:
`Login failed: No form found on https://vanila.org/ucp.php?mode=login using form selector form#login`

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by garfield69** [comment]
vanila currently returning sql error
![image](https://user-images.githubusercontent.com/6933240/65283224-c47ce500-db8a-11e9-8c6a-d7d6b440ffe2.png)

**Comment by xFilosofx** [comment]
It looks like the site has changed ownership or rebranding has occurred. I tried to download various distributions, but there is no torrent file download on all pages. Only a link to the MediaGet client. Maybe you should remove this torrent tracker from the list of supported ones.

**Comment by garfield69** [comment]
looks like the site has switched to using mediaget as a way to generate income to pay for the servers.
as you say, since this is not compatible with jackett (which expects .torrent/magnet links), the indexer will be removed.

**Comment by garfield69** [comment]
Jackett 0.13.144

**Comment by dimqua** [comment]
> has switched to using mediaget

Hash is still present.

**Comment by xFilosofx** [comment]
> 
> 
> > has switched to using mediaget
> 
> Hash is still present.

No, only for members in paid group. Look at the tracker creator topic https://vanila.org/viewtopic.php?t=1479172
