### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://yggtorrent.to/ using form selector form[action$=

### ISSUE THREAD

**Issue by artentica** [Jackett/Jackett#4004]
Not possible to add yggtorrent.

I think it's because the html selector is not correct

**Jackett version**:  0.8.864.0

-------------------------------

**Comment by artentica** [comment]
It's a duplicate yes but the other one has been closed beacause there was no details

**Comment by kaso17** [comment]
@artentica you're not providing any enhanced logs either. please post them.

**Comment by garfield69** [comment]
YGG have gone through 6 domain changes and 11 other indexer revisions since your version of Jackett 0.8.864 was published.
upgrade to the latest version of Jackett to resolve your issue.
