### ISSUE TITLE
[Yggtorrent] Can't find Anime with episode number in the query

### ISSUE THREAD

**Issue by Rapace21** [Jackett/Jackett#4006]
**Jackett version**:  0.10.314.0
**Mono version** (if not using Windows):  5.16.0.179

-------------------------------
Hello, jackett can't found anime with yggtorrent according to sonarr syntaxe query : 
With manual search : https://img.wazo.ovh/FhTSn
With manual search but with sonar syntaxe : https://img.wazo.ovh/rDd7Fmf8Rp

Any idea why ? Or any solution ?

**Comment by garfield69** [comment]
>Any idea why ? 

if you access the ygg site you get exactly that Jackett is showing you.
![image](https://user-images.githubusercontent.com/6933240/46974024-61373700-d11f-11e8-8dcd-92c8cd336076.png)

![image](https://user-images.githubusercontent.com/6933240/46974080-7f049c00-d11f-11e8-9f5d-489e44e1638b.png)

> Or any solution ?  

nothing to do with Jacket.
