### ISSUE TITLE
Feature request: add tracker language information

### ISSUE THREAD

**Issue by thenamelessthing** [Jackett/Jackett#401]
With the big quantity of "tracker" available in jackett, it can be a difficult to find which one are in english, french,etc.  It will be good and usefull specify the "main" language of each tracker available. Often, the tracker name are not enough accurate to determinate which language the tracker is specialized.  Maybe adding a flag (france,usa,etc.) for the language can be enough.

**Comment by thenamelessthing** [comment]
Can we expect this enhancement to be considerated???

**Comment by ldexterldesign** [comment]
Hey @thenamelessthing,

https://docs.google.com/spreadsheets/d/1WZ3RS3HA7tdRqMU2PXPEUYWGqrG1TnnguEJ6NbWJa-A/edit#gid=2059586408

Hope this is useful

Regards

**Comment by thenamelessthing** [comment]
Hi @ldexterldesign , I doens't have access to the link. It.s private and owner must grant me access! ;-/

**Comment by ldexterldesign** [comment]
If you request access you'll get 24 hour access without subscription

Regards

**Comment by thenamelessthing** [comment]
ldexterldesign If I understand, If I give you an invite for this tracker. In return you will help me to fix this?

**Comment by ldexterldesign** [comment]
I don't know how you've come to that conclusion

https://docs.google.com/spreadsheets/d/1WZ3RS3HA7tdRqMU2PXPEUYWGqrG1TnnguEJ6NbWJa-A/ is a torrent indexer/tracker resource, which does include country/language data for you to filter

Regards

**Comment by kaso17** [comment]
The next release will include a language column in the add indexer view
