### ISSUE TITLE
OMDB Key with request limit reached generates a NullReferenceException

### ISSUE THREAD

**Issue by alecsg77** [Jackett/Jackett#4015]
**Jackett version**:  0.10.325.0
Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5)
OS version: Unix 4.9.0.8 (64bit OS) (64bit process)
ThreadPool MaxThreads: 400 workerThreads, 200 completionPortThreads
App config/log directory: /var/opt/Jackett
issue: Debian GNU/Linux 9 \n \l
mono version: 5.16.0.179 (tarball Thu Oct  4 10:24:32 UTC 2018)
TrustedRootCertificates count: 152
Using HTTP Client: HttpWebClient2

-------------------------------
Steps:
1) Configure a valid free OMDB Key
2) Exceed the daily request limits
3) Perform an Torrent Potato Aggregated Request 

Results:
Error System.NullReferenceException: Object reference not set to an instance of an object
  at Jackett.Common.Indexers.Meta.ImdbTitleResultFilter.RemoveSpecialChars (System.String title) [0x00000] in <cdc59e47f5a74c15ab22c9d593421168>:0

**Comment by flightlevel** [comment]
@alecsg77 Thanks for investigating this. Since you've done the research why not make a contribution to the community and submit a pull request?
I personally won't work on this as I don't use OMDB like the majority of users and free limit seems relatively high

**Comment by alecsg77** [comment]
@flightlevel, done. I hope I did correctly. #4058
