### ISSUE TITLE
Change HDtorrents.it into HDtorrents.xyz

### ISSUE THREAD

**Issue by jokerigno** [Jackett/Jackett#4020]
Hi all,

I'm not a programmer but I wuold like to report that  HDtorrents.it moved to HDtorrents.xyz.

Can someone please upgrade it?

Thank you

**Comment by garfield69** [comment]
http://hdtorrents.xyz/ returning **404 Not Found** nginx

permanently broken or moved to another domain?

**Comment by kaso17** [comment]
@garfield69 they're using geo blocking to allow only italian users.
