### ISSUE TITLE
[REQ] alein.org

### ISSUE THREAD

**Issue by celeroll** [Jackett/Jackett#4021]
Hello,

can you please add following tracker:
http://alein.org 
It is a semi privat tracker. 
Only for downloads you need to be registered. For browsing it is not necessary.

**Comment by garfield69** [comment]
cannot register at the moment. getting `maximum number of users reached`.

**Comment by garfield69** [comment]
got an account now, so will start work on this soon.

**Comment by dimqua** [comment]
It seems this tracker has disappeared.

https://www.isitdownrightnow.com/alein.org.html

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/73598009-91664b80-4597-11ea-8daa-1e496da25766.png)

**Comment by garfield69** [comment]
it's been over a month since the site went offline. I'm removing the indexer.
In the event they return we can easily add them back.
