### ISSUE TITLE
Jacket Install Bug Password

### ISSUE THREAD

**Issue by Tpsw242** [Jackett/Jackett#4024]
Hello everyone, I tried to install jackett but he ask an admin password every time. I rm the config file ServerConfig.json, fill with “Password”= null, I uninstalled and installed again, but always the same thing.

Someone has an idea ?

**Comment by garfield69** [comment]
duplicate of #2335
stop jackett, 
edit the ~/.config/Jackett/ServerConfig.json file and change the AdminPassword line to this:
`"AdminPassword": null,`
Start Jackett again and there should be no password.
