### ISSUE TITLE
[yts] An error occurred while sending the request: Error: SecureChannelFailure (Unable to read data from the transport connection: Connection reset by peer.) (Config)

### ISSUE THREAD

**Issue by djwayne1985** [Jackett/Jackett#4027]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------
i have tried to use a link for the same site that isnt blocked but still getting the same issue

**Comment by djwayne1985** [comment]
maybe have alook under the first lot of writing you will see my issue

**Comment by garfield69** [comment]
if access to yts.am is blocked in your region and you are trying to use a proxy, then you need to check that the proxy you are using supports the YTS API in the same way as the original.
So from the same system that you are running Jackett on, open a browser and try https://yts.am/api/v2/list_movies.json?sort=date_added&limit=50
(replace yts.am with whatever proxy address you are testing)
you should get movie data back and not an error or a redirect.
something similar to
```
{"status":"ok","status_message":"Query was successful","data":{"movie_count":9006,"limit":50,"page_number":1,"movies":[{"id":9365,"url":"https:\/\/yts.am\/movie\/satyameva-jayate-2018","imdb_code":"tt8202612","title":"Satyameva Jayate","title_english":"Satyameva Jayate","title_long":"Satyameva Jayate (2018)","slug":"satyameva-jayate-2018","year":2018,"rating":6.4,"runtime":140,"genres":
etc
```
if you cant find a working proxy then consider using a vpn or more simply use a different DNS than the one your ISP provides. try cloudflare's 1.1.1.1 or google's 8.8.8.8 or 8.8.4.4
