### ISSUE TITLE
[yts] An error occurred while sending the request: Error: SecureChannelFailure (Unable to read data from the transport connection: Connection reset by peer.) (Config)

### ISSUE THREAD

**Issue by djwayne1985** [Jackett/Jackett#4028]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------
i have tried to use a different url for the site yts.am that works and im still getting the same issue

**Comment by garfield69** [comment]
yts.am is the only valid domain for this site, however we don't use their web page, we use their API.
So from the same system that you are running Jackett on, open a browser and try https://yts.am/api/v2/list_movies.json?sort=date_added&limit=50
you should get movie data back and not an error or a redirect.
something similar to
```
{"status":"ok","status_message":"Query was successful","data":{"movie_count":9006,"limit":50,"page_number":1,"movies":[{"id":9365,"url":"https:\/\/yts.am\/movie\/satyameva-jayate-2018","imdb_code":"tt8202612","title":"Satyameva Jayate","title_english":"Satyameva Jayate","title_long":"Satyameva Jayate (2018)","slug":"satyameva-jayate-2018","year":2018,"rating":6.4,"runtime":140,"genres":
etc
```

report back what you get.

you have not told us which version of Jackett and mono (if applicable) you are on, but I would recommend upgrading to the latest versions.
