### ISSUE TITLE
Only displays first 15 results from hd-torrents

### ISSUE THREAD

**Issue by alexkgodwin** [Jackett/Jackett#403]
When using CouchPotato or the manual search, Jackett only has 15 results, even though on the site there are lots more. I'd assume this is to do with the fact that on hd-torrents.org the page only shows 15 at a time. Is there a setting I'm missing, or is this a bug?

**Comment by alexkgodwin** [comment]
It could also be something to do with the fact it is running inside a FreeNAS jail on mono.

**Comment by flightlevel** [comment]
You're probably getting 15 results, because Jackett is only looking at the first page.
Not a member there, but you can go into your profile and there is usually setting that you can change about how many torrents are displayed per page. Change this to the max.
