### ISSUE TITLE
[REQ] DXDHD.com to be added

### ISSUE THREAD

**Issue by DXDHD** [Jackett/Jackett#4035]
Please enlist my tracker, 

Domain: https://www.dxdhd.com

Tracker: Running UNIT3D

Its on open registration mode at this moment, but if you dont get an email right away, please use resend password and you will get it straight away. Please let me know if theres anything else I can do.  

Thanks

**Comment by garfield69** [comment]
Hmm. not working for me at the moment.
after I completed the registration panel I got back an error 500
![image](https://user-images.githubusercontent.com/6933240/47243072-69f47980-d44d-11e8-94e5-ec6dcaae94cb.png)
and did not get an email.
I then used the password resend, got the email, used the link,
and after the password reset panel was entered, I once again got the error 500.

I'll try again another day once these server errors have been sorted.

**Comment by GouroB19** [comment]
Please allow me some time, Im working on this.

**Comment by GouroB19** [comment]
please try to login whenever you're free. Should be fine now.

**Comment by HDVinnie** [comment]
https://github.com/Jackett/Jackett/pull/4039

**Comment by garfield69** [comment]
available beginning with Jackett pre-release v0.10.354

**Comment by RoloSoze** [comment]
Down right now

**Comment by garfield69** [comment]
v0.17.788
