### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Got redirected to another domain. Try changing the indexer URL to https://www6.yggtorrent.to/.: Parse error (Test)

### ISSUE THREAD

**Issue by wuksion** [Jackett/Jackett#4036]
Jackett.Common.IndexerException: Exception (yggtorrent): Got redirected to another domain. Try changing the indexer URL to https://www6.yggtorrent.to/. ---> System.Exception: Parse error ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://www6.yggtorrent.to/.
  at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded (Jackett.Common.Utils.Clients.WebClientStringResult Result, AngleSharp.Dom.Html.IHtmlDocument document) [0x0002e] in <cdc59e47f5a74c15ab22c9d593421168>:0 
  at Jackett.Common.Indexers.CardigannIndexer+<PerformQuery>d__29.MoveNext () [0x00874] in <cdc59e47f5a74c15ab22c9d593421168>:0 
   --- End of inner exception stack trace ---

**Jackett version**:   _**0.10.325.0**_
**Mono version** (if not using Windows):  _**Synology 5.8.0.108-11**_

Thx for your great job !!

**Comment by garfield69** [comment]
upgrade to Jackett pre-release v0.10.343
OR
edit the config via your jackett dashboard, update the site link to www6.yggtorrent.to/ and when you click OKAY and get an error then click the CLOSE button.
Then EDIT the config again.
as long as the site link has remained www6.yggtorrent.to/ you can click OKAY and the config should save and you have got a working indexer again.

**Comment by wuksion** [comment]
Thx a lot 
You did a great job!
