### ISSUE TITLE
Jackett for Synology with Cpu FREESCALE QorIQ P1022

### ISSUE THREAD

**Issue by foobaan** [Jackett/Jackett#404]
Hello,

I would like to install Jackett on my Synology DS213+ but the package is not available on synocommunity package from my package center.

I think it is due to my cpu FREESCALE QorIQ P1022.

Is is possible that you compile Jackett for my CPU or tell we how to do it and publish it on synocommunity ?

Thank you

**Comment by next2non** [comment]
Its in beta so it wont normally appear in the synocommunity packages unless you switch it on. You need to go to package center ->settings and select the beta tab. You need to tick "Yes i want to see beta version". Jacket package should appear after that in the package list.

**Comment by foobaan** [comment]
Thanks for this information but I have already enable beta version. I can confirm because I see other beta package.

I was pointing CPU because if you go on **https://synocommunity.com/package/jackett** you can see all compatible architectures and I do not see mine : FREESCALE QorIQ

**Comment by flightlevel** [comment]
Jackett isn't native code, on Windows it runs on the .NET framework and linux/mac it runs on Mono. So, to run on any non windows platform it requires mono, exactly the same as Sonarr. 
Dont know anything about Synology but on here https://synocommunity.com/package/mono there is no mention of freescale.
Search around for freescale and mono/sonarr as you are more likely to find info on those topics
