### ISSUE TITLE
New tracker request Subtorrents

### ISSUE THREAD

**Issue by albertehc** [Jackett/Jackett#4043]
Requesting new public tracker to be added, is sub spanish:
~~https://www.subtorrents.tv/~~ 
~~https://www.subtorrents1.com/~~
~~http://www.subtorrents.la/~~
~~https://www.subtorrents.ch/~~
https://www.subtorrents.do/

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by ngosang** [comment]
@albertehc is this site still online? do you know the new domain?

**Comment by albertehc** [comment]
> @albertehc is this site still online? do you know the new domain?

[Subtorrent](www.subtorrents.la)

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
