### ISSUE TITLE
[cztorrent] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by mondychan** [Jackett/Jackett#4045]
Hello guys, 
this tracker doesnt work reliably. 
If you login to the website via browser, copy the cookie, it works inside Jackett for few minutes/hours. 

But only untill you are connected in the browser at the same time on the same machine. 
When you try to copy the cokie to diff (headless server perhabs) machine, it wont work there.
If i login to the website from diff location or logout, it stops working in Jackett inmediately.

I think it has something to do with the cloudflare protection.

**log**: https://pastebin.com/KRKN3BnC
**Jackett version**:  Jackett Version 0.10.358.0
**Mono version** (if not using Windows):  happens on both win and ubuntu using latest version

**Comment by kaso17** [comment]
probably unrelated  to cloudflare.
The login session seems to be restricted to a specific IP. So the cookie is restricted to a specific IP. Nothing we can do regarding this.
