### ISSUE TITLE
[megabliz] Login failed: Selector

### ISSUE THREAD

**Issue by djwayne1985** [Jackett/Jackett#4046]
i am unable to login to my account can you help please

**Comment by djwayne1985** [comment]
@jackettbot i have tried that and still gettin the same error

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by kaso17** [comment]
It's only a standard log. Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
