### ISSUE TITLE
[Feature Request] Enable Cross-seeding feature

### ISSUE THREAD

**Issue by doopeldedoo** [Jackett/Jackett#4050]
Jackett only downloads one torrent-file..
If the file is available on multiple trackers, can Jackett download them all to cross-seed?

Cross-seeding is when the same torrent is on two different trackers, you can download it from one, then seed to both.
This makes it possible to get a better ratio at multiple trackers.

So for instance: 
1. Sonarr or Radarr searches for a specific file via Jackett. 
2. Jackett downloads the file itself but also looks for the same file on different trackers.
3. Jackett downloads the same torrent on another tracker to enable cross-seeding.

**Comment by kaso17** [comment]
dupe #1646
