### ISSUE TITLE
[Bug] Downloading torrent files does not work on 720pier.ru

### ISSUE THREAD

**Issue by whitesnakeftw** [Jackett/Jackett#4055]
It throws: This 127.0.0.1 page can’t be found

**Comment by garfield69** [comment]
@koper89  as the author if this indexer can you sort this out?
I noticed that the file size seems wrong also.

**Comment by koper89** [comment]
Sure will have a look @garfield69, but size in my case is displaying correctly. Can you send examples?

**Comment by garfield69** [comment]
@koper89  
![image](https://user-images.githubusercontent.com/6933240/47455495-7a7e6880-d82e-11e8-882c-6a6ce774c3f8.png)

**Comment by koper89** [comment]
![image](https://user-images.githubusercontent.com/6483727/47461831-0cac4f80-d7e2-11e8-80ca-fb6b70031030.png)
Can't replicate it ;/

**Comment by koper89** [comment]
Ok found cause of your issue @garfield69 you need to change in profile to british english if you want this to work. (If you're having set profile to russian it'll not work)

![image](https://user-images.githubusercontent.com/6483727/47462020-86dcd400-d7e2-11e8-9fd9-fcfa32c3480f.png)

**Comment by garfield69** [comment]
fix available with jackett pre-release 0.10.377
thank you @koper89
