### ISSUE TITLE
YGGTORRENT Didn't Work

### ISSUE THREAD

**Issue by Mikasway** [Jackett/Jackett#4059]
Hi,

The tracker YGG is not functionnal since some days.

[yggtorrent] Login failed: No form found on **https://www6.yggtorrent.to**/ using form selector form[action$=.

I have change it mannually but its didn't work 👎 .

It is possible to be more "agile" on the detection on the new domains ? It will be nice to accept re rooting of DNS to not change it every week..

Please help and have a nice day :)

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
YGG change their domains quite often, unfortunately.
When it comes to updating the config manually, dont let the first error you get after pressing OKAY put you off, just click CLOSE.
Then edit the config again, and as long as the site remains what you last entered, click OKAY and it should save.
the automatic fix was released with jackett  version 0.10.343 onwards.
