### ISSUE TITLE
Torrent files for RARBG

### ISSUE THREAD

**Issue by 894-572** [Jackett/Jackett#4063]
[RARBG](https://rarbg.to/) provides torrent files, Jackett search doesn't fetch them.

**Comment by garfield69** [comment]
rarbg the web site may provide .torrent links, but the site actively prevents html scraping so jackett cannot use this usual method.
however rarbg does provide an API which is what jackett uses.
however the API only provides magnet links.

i suppose we could provide a .torrent link via the roundabout way of redirecting to itorrents.org, however be warned that this method is not guaranteed to allways return a .torrent when given a magnet hashkey.
do you want us to add this enhancement to our rarbg indexer?

**Comment by 894-572** [comment]
> 
> 
> rarbg the web site may provide .torrent links, but the site actively prevents html scraping so jackett cannot use this usual method.
> however rarbg does provide an API which is what jackett uses.
> however the API only provides magnet links.
> 
> i suppose we could provide a .torrent link via the roundabout way of redirecting to itorrents.org, however be warned that this method is not guaranteed to allways return a .torrent when given a magnet hashkey.
> do you want us to add this enhancement to our rarbg indexer?

I can see the enhancement as useful.

**Comment by garfield69** [comment]
implemented, beginning with jackett pre-release 0.10.380

**Comment by garfield69** [comment]
have reversed this out for now as it is causing issues downstream.
will re-implement as an optional, defaulting to false, once i sort out the required code.
