### ISSUE TITLE
Manual Search via API

### ISSUE THREAD

**Issue by speedyflipper** [Jackett/Jackett#407]
Is is possible to manually search all trackers using the API? I know there is the option on the dashboard but would like to have a script search and pull results. 

What is the format of the URL is possible?

**Comment by flightlevel** [comment]
Definitely, the dashboard is just using the API.
Jackett returns a torznab response.
https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer

eg.
localhost:9117/torznab/freshon/api?t=tvsearch&cat=5000,5030,5040&extended=1&apikey=olexxxxxxxxxxxxxh0da7uu4&offset=0&limit=100&q=Blacklist&season=3&ep=6

Sonarr logs are good place to look for examples as well

**Comment by speedyflipper** [comment]
Is there anyway to search all of the trackers with one command? It looks like the example is using the indexer freshon.

**Comment by armani316** [comment]
@flightlevel Should this remain open?

**Comment by kaso17** [comment]
Closing this one in favor of #921

**Comment by flightlevel** [comment]
Got asked this again, will place info here, so it can be searched for by others

Create a POST request to http://localhost:9117/Admin/search
with 
`{"Query": "The Big Bang Theory", "Category": "0", "Tracker": ""}`
the above JSON in the body, leave trackers as blank to get all results, change query to your tv show name. You will get a JSON result with all trackers

**Comment by grostim** [comment]
I second this request.
Is there a straightforward solution to submit a search to all the indexers at once through the torznab protocol ?

**Comment by flightlevel** [comment]
@grostim Read the readme
