### ISSUE TITLE
For ToTheGlory indexer, manual search works, but api seems to fail

### ISSUE THREAD

**Issue by yimingzhaomath** [Jackett/Jackett#4072]
I am using ToTheGlory indexer.

The manual search works perfectly. For example, if I search "antman" under the category 2040, the search returns what it's supposed to return.

A couple of weeks ago, this particular indexer in Jackett stopped to work for Radarr. I've been looking into this for some time now. I found out the api search with Jackett for this particular indexer doesn't seem to work. 

The api search I used is: http://myjackettdomain/api/v2.0/indexers/totheglory/results/torznab/api?cat=2040&apikey=mykey&q=antman

For some queries, it returns an error 900. For some other ones, it returns 

```
<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://nereus.bysh.me:44229/" rel="self" type="application/rss+xml" />
    <title>ToTheGlory</title>
    <description>A chinese tracker</description>
    <link>https://totheglory.im/</link>
    <language>en-us</language>
    <category>search</category>
    <image>
      <url>http://nereus.bysh.me:44229/logos/totheglory.png</url>
      <title>ToTheGlory</title>
      <link>https://totheglory.im/</link>
      <description>ToTheGlory</description>
    </image>
  </channel>
</rss>

```

Can you help me?

**Jackett version**:  0.10.365.0
**Mono version** (if not using Windows):  5.8.0.127
[log.txt](https://github.com/Jackett/Jackett/files/2517630/log.txt)

-------------------------------

**Comment by kaso17** [comment]
fixed via a93c347672943efd5364fee2cee5930b73769dd6
