### ISSUE TITLE
[iptorrents] Exception (iptorrents): A task was canceled.: A task was canceled.

### ISSUE THREAD

**Issue by blaidd4drwg** [Jackett/Jackett#4091]
An error occured while testing this indexer
Exception (iptorrents): A task was canceled.: A task was canceled.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.380.0
**Mono version** (if not using Windows):  5.16.0.179 on macOS 10.14 (18A391)

-------------------------------
Steps to reproduce: Used Test-Button to test Indexer. Rebooted system, restarted Jackett, tried again, same result. Login to iptorrents works.
[log.txt](https://github.com/Jackett/Jackett/files/2522784/log.txt)

**Comment by garfield69** [comment]
please upgrade to the latest version of jackett which has a recent iptorrents login fix, and see how you go.

**Comment by blaidd4drwg** [comment]
Works like a charm, thanks!
