### ISSUE TITLE
Exception Error: ServerProtocolViolation: An error occurred while sending the request

### ISSUE THREAD

**Issue by Trozmagon** [Jackett/Jackett#4094]
Brand new install, works fine before adding VPN, fails on all indexers after VPN added, tested VPN though uTorrent and Android device, both working fine. See attached. 

Indexers tried, EZTV, YTS, Piratebay, Kickass.
Debian 9.5
Jackett: 0.10.380.0
Mono:  5.16.0.179

[exception.txt](https://github.com/Jackett/Jackett/files/2525407/exception.txt)

**Comment by kaso17** [comment]
Seems like the vpn is messing with HTTP(S) connections so it no longer works with mono. Unlikely that this is a Jackett specific issue.
I'd suggest you continue troubleshooting this with tcpdump and a HTTP indexer (not HTTPS).
