### ISSUE TITLE
v0.10.380 RARBG .torrent update causing issues

### ISSUE THREAD

**Issue by ukharley** [Jackett/Jackett#4096]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------
Jackett version: v0.10.380.
Mono version: none, using Windows.

The RARBG .torrent update causes all RARBG API calls to fail with:
Torrent file content is empty: *****.S04E03.720p.HDTV.x264[rartv]
when using Medusa.
Someone else reported the same error (not using Medusa) and your reply was "wontfix."
Why?
Do what you have done for other sites such as ETTV, let us choose whether we want to use magnets or torrents.
Thank you.

**Comment by garfield69** [comment]
sounds reasonable. will implement your suggestion.

**Comment by garfield69** [comment]
i have reverted out the change with jackett 0.10.394
and will re-implement it as an optional, defaulting to false, at a later stage, once i sort out the required code.
sorry for the incovenience.
