### ISSUE TITLE
Error On attempt 2 downloading from RARBG: A task was canceled

### ISSUE THREAD

**Issue by spang11ers** [Jackett/Jackett#4097]
All other trackers work perfectly except RARBG on which I get the error "Error On attempt 1,2,3 downloading from RARBG: A task was canceled". 

If I copy the link directly from the log file for the torrent it downloads no problem.
[log.txt](https://github.com/Jackett/Jackett/files/2527538/log.txt)

**Jackett version - 0.10.380.0**
**Mono version -  5.16.0.179 **

-------------------------------

**Comment by garfield69** [comment]
upgrade to 0.10.394 for fix.
