### ISSUE TITLE
sceneaccess not working

### ISSUE THREAD

**Issue by seed1234** [Jackett/Jackett#41]

**Comment by luxus** [comment]
It is Working Manuel search Working Great

**Comment by flightlevel** [comment]
@seed1234 
What's the error?
What version of Jackett?

**Comment by seed1234** [comment]
Configuration failed:

**Comment by flightlevel** [comment]
That doesn't really help. Would need an invite to try logging in.

**Comment by seed1234** [comment]
i dont know how to get a solution then
it still does not work😢

**Comment by WhatFox** [comment]
Its working fine here, run with logging enabled for more details

**Comment by seed1234** [comment]
hey @WhatFox 
i tried again on adding SceneAccess it keeps saying configuration failed
and how do i enable more details 

Thanks

**Comment by WhatFox** [comment]
Run the console app with "-t -l" as per the front page and close the tray/service if you are on windows first.

**Comment by raspdealer** [comment]
Any news? Can we close it @WhatFox @Azerelat  after 1 month without news ?
