### ISSUE TITLE
Demonoid "Configuration failed" issue still occurring

### ISSUE THREAD

**Issue by ArcoSeal** [Jackett/Jackett#410]
This issue is still occurring as of version 0.7.296.0. Original (closed) issue here: https://github.com/Jackett/Jackett/issues/365

I'd post fresh logs but they're the same as before.

**Comment by vb543** [comment]
Having the same issue.

**Comment by flightlevel** [comment]
Duplicate
https://github.com/Jackett/Jackett/issues/365
