### ISSUE TITLE
Make generated RSS available online so 'Premiumize.me' can use it?

### ISSUE THREAD

**Issue by SaxonRix** [Jackett/Jackett#4103]
At the minute I'm using 'Premiumize.me', which allows you to link to an RSS feed to enable automatic downloads to the Premiumize servers. However, since the 'links' to the RSS feeds generated by Jackett are 'local', I'm unable to share that link with Premiumze in order to automatically download.

Is there anyway to 'host' the RSS feed online so that we can use the RSS feeds generated by Jackett with premiumize?

Many thanks.

**Comment by kaso17** [comment]
just enable external access and access jackett via the external IP/host or use a reverse proxy.
