### ISSUE TITLE
Xspeeds.eu Issue

### ISSUE THREAD

**Issue by maphex** [Jackett/Jackett#411]
Index stopped working but when i tried to test the connection i get this error message.

`Test failed for xspeeds: '', hexadecimal value 0x07, is an invalid character. Line 1953, position 144.`

When i retype my credentials i get this message:

` Configuration failed: Please turn JavaScript on and reload the page. Checking your browser before accessing xspeeds.eu. This process is automatic. Your browser will redirect to your requested content shortly. Please allow up to 5 seconds…`

**Comment by d2dyno** [comment]
The latter part of this has been reported here: https://github.com/Jackett/Jackett/issues/386
