### ISSUE TITLE
[torviet] Found no results while trying to browse this tracker (Test and Find)

### ISSUE THREAD

**Issue by neopet001** [Jackett/Jackett#4111]
1. The username & password are correct, I can see new successful login within my torrent account on torviet.com
2. I'm using Jackett Version 0.10.398.0
3. I'm using Jackett on a PlexGuide installation.

**Jackett version**:  0.10.398.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.
