### ISSUE TITLE
[1337x.to] Search results are limited to 20

### ISSUE THREAD

**Issue by whitesnakeftw** [Jackett/Jackett#4112]
1337x searches return 20 items max, no matter what.

For instance: https://1337x.to/search/mayans/1/

**Comment by garfield69** [comment]
In the next (pre)release that gets published, this indexer will try to fetch up to 100 results.

**Comment by OldSchool4664** [comment]
I am updated to 0.10.649 and only get 25 results.

**Comment by garfield69** [comment]
@OldSchool4664  if searching with keywords the indexer will attempt to fetch 5 pages.
if just doing a TEST, only the first page is fetched.

**Comment by OldSchool4664** [comment]
Thanks. I am using the manual search option; would that have the 1 page limit as well?

**Comment by OldSchool4664** [comment]
If I search for TEST I only get 25 results. If I search for TEST on the actual tracker site (Pretome), I get over 100 results. So with the latest release it seems I can only get 1 page.

**Comment by garfield69** [comment]
this suggests that your indexer has not been updated for some reason.
try installing the latest jackett from https://github.com/Jackett/Jackett/releases over the top of the existing one (as opposed to using the check-for-updates option)

**Comment by OldSchool4664** [comment]
Interesting. That's exactly what I did already. I manually installed 0.10.649 over top of my existing version since I didn't want to wait for an auto-update after enabling pre-releases. I suppose the next step is to re-add the tracker, and next try a reinstall.

**Comment by garfield69** [comment]
also visit the jackett folder, and take a look at the definitions folder for the 1337x.yml
id you have the correct indexer it should contain

https://github.com/Jackett/Jackett/blob/15049a4efb212817d234913ff3f0d91edef76344/src/Jackett.Common/Definitions/1337x.yml#L119-L127

**Comment by OldSchool4664** [comment]
Sorry to get back to you so late. I appreciate the pointers you have been giving me. I checked that file and the contents are the same. I tried re-adding the tracker, then a full uninstall (manually deleted leftover C:\ProgramData\Jackett), then installed the the latest version (v0.10.724). Still only 25 results!

The original poster said it is returning them 20 results, whereas for me I am getting 25. I wonder why there is a difference? Here is a log of my search:

2019-02-08 20:20:20.8540 Info Manual search for "test" on pretome with 25 results.

I wonder if pretome has some kind of detection to limit search results from automated tools like this? I will try asking on their forum and see if anyone can confirm. Any other ideas are greatly appreciated!

**Comment by garfield69** [comment]
if you want to dig deeper, then 
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by OldSchool4664** [comment]
Ahh, that was very useful! I can see the HTML in the logs so I am assuming Jackett is parsing that. Pretome returns 25 search results per page! You need to change pages to see more results.

Logfile attached with personal details removed.

[jackett_pretome_log.txt](https://github.com/Jackett/Jackett/files/2847514/jackett_pretome_log.txt)

**Comment by OldSchool4664** [comment]
Fortunately, there is a profile setting in pretome to increase the number of search results per page. I set it to the maximum, 100. When I do a manual search in Jackett now, I get 100 results!

I can see that there is already an open enhancement request for pagination:

https://github.com/Jackett/Jackett/issues/975

But for me, I think 100 results will resolve the problems I have been having with Sonarr not always finding things. Thanks so much for all the help!

**Comment by garfield69** [comment]
we crossed wires someplace. 
I thought we were still talking about 1337x, but at some point you switched to talking about pretome and I didn't catch that. 
but you solve the issue for yourself so that is all that matters in the end.

**Comment by OldSchool4664** [comment]
Wow I definitely didn't mention that in my original comment. Sorry about that, I will be more clear in the future.
