### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): An attempt was made to access a socket in a way forbidden by its access permissions 104.27.171.251:443: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by TNightster** [Jackett/Jackett#4113]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------
An error occured while testing this indexer
Exception (thepiratebay): An attempt was made to access a socket in a way forbidden by its access permissions 104.27.171.251:443: An error occurred while sending the request.

**Comment by garfield69** [comment]
your ISP is probably blocking your access to TPB or else you changed your Jackett TPB indexer's site link from thepiratebay.org to an IP address.
cloudflare does not normally allow access to its customer's web sites via direct ip address.
if you are using the domain name then try switching to a public DNS like cloudflare's 1.1.1.1 or google's 8.8.8.8 or  8.8.4.4 or use a VPN

**Comment by TNightster** [comment]
Thanks for the reply. Wasn't sure if it's something on my end.

I can't get thepiratebay.org to load in a browser.
I can get thepiratebay.rocks to load in a browser.

So I had switched the indexer link to the .rocks domain, but still not working.

I am going through PIA for my VPN.

Thanks.


________________________________
