### ISSUE TITLE
Waffles erroring and wont download

### ISSUE THREAD

**Issue by benflux** [Jackett/Jackett#4114]
**Jackett version**:  Version 0.10.410.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by benflux** [comment]
it seems that waffles is down for everyone. Will await

**Comment by kaso17** [comment]
it's back up again, downloads are working fine for me
