### ISSUE TITLE
Problem with category (YggTorrent)

### ISSUE THREAD

**Issue by samimaarouf** [Jackett/Jackett#4121]
Hello,

I'm using Jackett with Sonarr, and I found an issue when I'm searching an anime on yggtorrent.

This is my configuration with Sonarr : 
![image](https://user-images.githubusercontent.com/24414408/47966646-18efa280-e055-11e8-85e9-0fd69ef6f7ee.png)

And my configuration with Jackett : 
![image](https://user-images.githubusercontent.com/24414408/47966582-5acc1900-e054-11e8-9ee0-a9094dc8a660.png)

Then, when i search an anime on Sonarr, it's ONLY found if I put my anime on the "Standard" categorie.

For example : 
![image](https://user-images.githubusercontent.com/24414408/47966607-b1d1ee00-e054-11e8-88e0-f45f9a7ce3fb.png)

You can see, now it finds it when my anime is on the categorie "Standard" : 
![image](https://user-images.githubusercontent.com/24414408/47966624-e2198c80-e054-11e8-8d93-fc568d0b9527.png)

But, if I do it when I put my anime on the "anime" categorie, it won't work : 
![image](https://user-images.githubusercontent.com/24414408/47966707-d67a9580-e055-11e8-8af8-9f1381b69a0a.png)

![image](https://user-images.githubusercontent.com/24414408/47966686-8ef40980-e055-11e8-8557-81e6703336ec.png)
 
Btw, for Nyaa it's the same. But it doesn't match for the category "Standard" and works with the category "Anime".

**Comment by Hakujou** [comment]
I also have the same issue, animes are not matched on Ygg Torrent. Series works fine.

Jackett does find animes in the correct categories when using its search so I guess Sonarr uses some parameters on animes which breaks YggTorrent

**Comment by samimaarouf** [comment]
Finally, it was a Sonnar's issue. You can close it.

There it is the issue and the answer :
https://github.com/Sonarr/Sonarr/issues/2800?fbclid=IwAR0bFjyJ0R8DsGqhn86lWii57eE6oFjdR7uA0nOFcW1MMYEDFublmUdqApo
