### ISSUE TITLE
OSX Build failing

### ISSUE THREAD

**Issue by infomofo** [Jackett/Jackett#4129]
Hi, I'm trying to submit a PR, but before I submit it I wanted to test it locally. However, I'm on OSX and not able to get the [instructions in the readme](https://github.com/Jackett/Jackett/blob/master/README.md#osx) to work.

This is on OSX 10.14.1. Steps to reproduce:

1. `brew install nuget mono` and install deps from https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.302-macos-x64-installer
2. clone jackett
3. `cd src`
4. `nuget restore Jackett.sln`
5. `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`
6. `msbuild Jackett.Server/Jackett.Server.csproj /t:Build /p:Configuration=Debug`

At this point the next step says to run

    mono Jackett.Server/bin/Debug/JackettServer.exe

However, there's no executable in the Debug directory. There are two subdirectories under Debug `netcoreapp2.1` and `net461` and none of the subdirectories have a `JackettServer.exe`

I am going to just try to get my PR working by running it on a linux cloud server, but I thought you should know the OSX build instructions weren't working for me- have they changed?

-------------------------------

**Comment by kaso17** [comment]
Hi, 

you'll need to install the dotnet core SDK.
not sure if a `brew install dotnet-sdk` will work.
If not you probably have to manually install it via https://dotnet.microsoft.com/download?initial-os=macos.

Once that's done please try the following instructions:

```bash
git clone https://github.com/Jackett/Jackett.git
cd Jackett/src

# dotnet core version
dotnet publish Jackett.Server -f netcoreapp2.2 --self-contained -r osx-x64 -c Debug # takes care of everything
./Jackett.Server/bin/Debug/netcoreapp2.2/osx-x64/JackettConsole # run jackett
```

**Comment by garfield69** [comment]
thanks @kaso17 , your build instructions worked, ive got a working dotnet jackett going.
i've updated the readme with 869efa32f4eede6df05ded9cfd3ea3bf6cd76497
