### ISSUE TITLE
Error with my setup?

### ISSUE THREAD

**Issue by Zhangsun321** [Jackett/Jackett#4137]
Windows 10.   Jackett version  0.10.420.0

I am having a problem with all my feeds, it is downloading each posting about 4 times.    

https://i.imgur.com/0xd89Hl.png

lets just focus on the rarbg-tv and the r-tv as there are only 2 tv catagories and I can logically assume that there is something wrong with my jackett program, and not my rss reader url setup..

as you can see its showing multiple listings for the same torrent hash, i did verify this for a few torrents..

ALSO..  when i click on a 'torrent'  it doesnt get the magnet link directly into my tixati like it used to..  it now downloads the torrent file..  So I am thinking it is something in my 127...... setup??   I just installed the new version...      

I loaded torrentcouch to test it.. and it does the same thing there,   as torrentcouch only has 2 catagories.      

Also...  the two R-  are the feeds through jackett    the RARBG feeds are directly through rarbg.     

Thanks for the all the help...  It is much appreciated..

**Comment by kaso17** [comment]
the magnet link recently changed to the torrent link. The magnet link is still part of the feed but your feed reader has to use the correct field.

Regarding the duplicates:  most likely your reader is using the "link" attribute for de-duplication, it should use the guid attribute instead.

**Comment by Zhangsun321** [comment]
I fixed the problem... it was the crappy rss reader i was using.. can you recomend one for windows 10 that installs on the desktop?

**Comment by kaso17** [comment]
no, sorry
