### ISSUE TITLE
Jackett Fails to autostart until logged in

### ISSUE THREAD

**Issue by 07stuntar1** [Jackett/Jackett#4138]
**Jackett version**: Jackett Version 0.10.420.0 
**Mono version** (if not using Windows):  Mono JIT compiler version 5.16.0.179

Hi, I cant figure out what logs I need to provide. I don't see any errors for why it will not start. But for some reason my Jackett will not autostart when the system boots. I see it shows it booted after network.target. Unless I log in and do a systemctl status jackett the service does not start. As soon as I type systemctl status jackett it starts immediately. And everything works perfectly.

/etc/systemd/system/jackett.service

[Unit]
Description=Jackett Daemon
After=network.target

[Service]
WorkingDirectory=/opt/jackett/
User=(user)
ExecStart=/usr/bin/mono --debug JackettConsole.exe --NoRestart
Restart=always
RestartSec=2
Type=simple
TimeoutStopSec=5
SyslogIdentifier=jackett

[Install]
WantedBy=multi-user.target

**Comment by Jorman** [comment]
2 stupid questions:
Do you enable the service?
Do you give the user permission to /opt/jackett?

Btw, I know that you've WorkingDirectory, but I always specify the full path of the program
`ExecStart=/usr/bin/mono /opt/jackett/JackettConsole.exe --NoRestart`

They are just ideas

**Comment by 07stuntar1** [comment]
Hi @Jorman 
Yes the service is enabled. I tired your 2nd option and still doesn't work. Its weird because as soon as I ssh and log into the linux box jackett starts working. All the rest of the apps work fine with similar systemctl configs.

**Comment by Jorman** [comment]
Try to see the log from journal
journalctl -u jackett -ef


Il giorno ven 9 nov 2018, 01:30 07stuntar1 <notifications@github.com> ha
scritto:

**Comment by Jorman** [comment]
Maybe a full log is better.
do `journalctl -xb >log` after a fresh reboot, and we will see some log :)

**Comment by Soppiej** [comment]
so? you are running jackett from radarr.service? Look at your top line

/etc/systemd/system/radarr.service
what is the content of 
/etc/systemd/system/jackett.service

**Comment by 07stuntar1** [comment]
@Soppiej Sorry copied the wrong line. No its supposed to be jackett.service

@Jorman  So in the journalctl -xb i now see 
Nov 09 10:42:03 ubuntu jackett[1839]: System.Exception: Could not create settings directory. Access to the path "/home/me/.config" is denied.
Jackett is running as me and also has access to that folder. For trial I drwxrwxrwx the folder and contents. Still no luck.

It seems like when I login it then works
Nov 09 10:42:05 ubuntu jackett[1860]: 11-09 10:42:05 Info Starting Jackett v0.10.420.0
Nov 09 10:42:08 ubuntu jackett[1860]: 11-09 10:42:08 Info Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5)
Nov 09 10:42:08 ubuntu jackett[1860]: 11-09 10:42:08 Info OS version: Unix 4.4.0.138 (64bit OS) (64bit process)
Nov 09 10:42:08 ubuntu jackett[1860]: 11-09 10:42:08 Info ThreadPool MaxThreads: 400 workerThreads, 200 completionPortThreads
Nov 09 10:42:08 ubuntu jackett[1860]: 11-09 10:42:08 Info App config/log directory: /home/me/.config/Jackett
Nov 09 10:42:08 ubuntu jackett[1860]: 11-09 10:42:08 Info issue: Ubuntu 16.04.5 LTS \n \l
Nov 09 10:42:08 ubuntu jackett[1860]: 11-09 10:42:08 Info mono version: 5.16.0.179 (tarball Thu Oct  4 10:29:10 UTC 2018)
Nov 09 10:42:08 ubuntu jackett[1860]: 11-09 10:42:08 Info TrustedRootCertificates count: 148
Nov 09 10:42:08 ubuntu jackett[1860]: 11-09 10:42:08 Info Using HTTP Client: HttpWebClient
Nov 09 10:42:09 ubuntu jackett[1860]: 11-09 10:42:09 Info Loading Cardigann definitions from: /home/me/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /opt/jackett/Definitions

**Comment by Jorman** [comment]
Seems that you've not the right access to the path, report this
`ls -lah /home/me/`
`ls -lah /home/me/.config`

Then for me is strange
`Loading Cardigann definitions from: /home/me/.config/cardigann`
but maybe under ubuntu is normal

**Comment by 07stuntar1** [comment]
drwx------ 11 me me   4.0K Nov  9 10:43 me
drwx------  7 me  me   4.0K Mar 12  2018 .config

**Comment by kaso17** [comment]
You might want to check if there's some apparmor/selinux/... policies preventing access.

**Comment by ngosang** [comment]
@07stuntar1 did you manage to fix the problem?

**Comment by RoloSoze** [comment]
@ngosang No response in nearly 3 months. 

@07stuntar1 I'll close this issue for now. If this is still a problem, feel free to reopen it.
