### ISSUE TITLE
Can't add rutracker

### ISSUE THREAD

**Issue by samsepiol59** [Jackett/Jackett#4139]
**Jackett version**: 0.9.41.0
**Mono version** (if not using Windows):  I don't know, I'm on ultraseedbox

-------------------------------

I can't add rutracker, all I get is this error (I'm logged in in both pictures)
via organizr: https://i.imgur.com/OCcHlGA.png
via seedbox (x2go): https://i.imgur.com/LTj4V5w.png

**Comment by kaso17** [comment]
update to the latest jackett version
