### ISSUE TITLE
[nordicbits] Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by satzisa** [Jackett/Jackett#4140]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------
I'm unable to add private tracker.
https://i.imgur.com/orzni9J.png
https://i.imgur.com/lyBTxQ2.png
https://i.imgur.com/vdQWDX6.png
https://i.imgur.com/j1JjPos.png

 An error occured while updating this indexer
Found no results while trying to browse this tracker
Click here to open an issue on GitHub for this indexer.

If there is anyway to fix this pls assit me.

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by satzisa** [comment]
> 
> 
> Please provide the **full enhanced log** file.
> 
>     1. scroll down to the bottom of the Jackett Dashboard and _tick_ the _enhanced Logging_ checkbox
> 
>     2. scroll up a bit and _click_ on the _apply server settings_ button
> 
>     3. repeat the test
> 
>     4. find the _log.txt_ file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
> 
>     5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
> 
>     6. save, then drag-drop it here for us to take a look at.
>        Thanks.

@garfield69 Here I'm attaching the log file.
[log.txt](https://github.com/Jackett/Jackett/files/2567190/log.txt)
Thank you for the response.

**Comment by garfield69** [comment]
@hallengreenn  or @kaso17  or @flightlevel  could you take a look at this enhanced log and see if you can make sense of what is happening?
the indexer c# is just too complex for me to figure out. Thanks.

**Comment by kaso17** [comment]
383d9ff4f8959a941c40299a7fa04a55869214a6 contains some fixes which should fix the problem (untested).
template no. 7 was incorrectly detected as a "default" one.
Additionally the category mapping is incomplete. In case there is a release with a missing category this caused in indexer to crash.
@hallengreenn: I hope I didn't break anything by swapping the template detection order.

**Comment by satzisa** [comment]
@kaso17 have you updated it? I still got the same issue. 
Pls let me know

**Comment by garfield69** [comment]
yes, kaso17 loaded `Nordicbits: category mapping and template 7 related fixes` which is included in versions 0.10.431 -  v0.10.447
if you are on any of the above and still have issues then provide an enhanced log for kaso17 to take a look to see if there are additional amendments that need doing. thanks.

**Comment by satzisa** [comment]
@garfield69 I'm currently using cloudbox. Jackett Version is 0.10.422.0. I'm unable to update the latest version. When I check for update all I got is update triggered message. But its really not updating at all.
https://i.imgur.com/YV1dx1T.png
