### ISSUE TITLE
No package available on Synology

### ISSUE THREAD

**Issue by Nemrod7** [Jackett/Jackett#4144]
Hi,

I can't find the package for Synology, DSM up to date, beta or final.

Thanks

**Comment by garfield69** [comment]
are you referring to https://synocommunity.com/package/jackett ?

**Comment by kaso17** [comment]
The syno package is not maintained by the jackett team. please contact the synocommunity people.

**Comment by Nemrod7** [comment]
Ok, any idea how I can contact them ?

**Comment by kaso17** [comment]
https://github.com/SynoCommunity/spksrc/issues

**Comment by Nemrod7** [comment]
Thanks
