### ISSUE TITLE
[req]: HDArea 

### ISSUE THREAD

**Issue by screwfaze** [Jackett/Jackett#4145]
Please can you add Hdarea to jackett 
https://www.hdarea.club/
~~https://www.hdarea.co/~~

Thanks

**Comment by 55laren** [comment]
i hope it added to jackett too !!!!!!!!!!!

**Comment by screwfaze** [comment]
Any update on this?

**Comment by garfield69** [comment]
registration is currently closed, invite only.

**Comment by garfield69** [comment]
If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by lavasmuffin** [comment]
@garfield69 Do you still need an invite for this tracker?

**Comment by garfield69** [comment]
yes. 
please send an invite to garfieldsixtynine @ gmail.com .
thanks.

**Comment by lavamuffin** [comment]
I currently dont have an invite. But I took a quick look at cardigann definitions and was able to make one for this tracker. I can make a pull request if that's ok with you.

**Comment by garfield69** [comment]
absolutely!
go for it.
dont forget to add an entry in the readme file too. cheers.

**Comment by garfield69** [comment]
Available with Jackett pre-release 0.10.756

**Comment by 55laren** [comment]
thanks a lot

**Comment by garfield69** [comment]
https://www.hdarea.co/ currently returning cloudflare 522 Connection timed out.
just me, or is the site gone, broken or moved to a new domain?

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.hdarea.co/ - Bad gateway Error code 502

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> This website will change its domain to hdarea.club around July 20th. Please take note of this.

Marking as down to monitor.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/7be7b45b27a8af444c49897292b598ddd6d1447a

**Comment by garfield69** [comment]
@ilike2burnthing  try hdarea.club (without the www.)

**Comment by garfield69** [comment]
https://hdarea.club/login.php 404 Not Found @ilike2burnthing  is the site/indexer working for you?

**Comment by garfield69** [comment]
https://hdarea.club/aboutnexus.php works which suggests that they have deliberately disabled logins (as some other Chinese sites are want to do), do those with expired cookies could be out of luck unless they had a direct link saved (assuming the site supported that feature).

**Comment by ilike2burnthing** [comment]
Login page back up, and I'm making my way through just shy of 1000 GH emails 🤯
