### ISSUE TITLE
[zooqle] Exception (zooqle): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /build/mono-5.16.0.179/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by Tubaralho** [Jackett/Jackett#4150]
Jackett version:  
* 0.10.422.0

Mono version (if not using Windows):  

`Mono JIT compiler version 5.16.0.179 (tarball Thu Oct  4 12:22:11 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-/)
        GC:            sgen (concurrent by default)
`
-------------------------------

**Comment by truenicoco** [comment]
It is worth noting that the recommended way to do so in debian is `sudo update-ca-certificates`.

**Comment by Tubaralho** [comment]
Hi... thanks @garfield69  and @truenicoco 

I have done both 

1. `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
2. `sudo update-ca-certificates`

After each other I rebooted Jackett service and tested but in every case I have the same error.

Is there any more info I can add to this so you can help me?

Regards and thank you.

**Comment by garfield69** [comment]
Please post the output of `csharp -e 'Console.WriteLine (new System.Net.WebClient ().DownloadString ("https://www.howsmyssl.com/").IndexOf ("1.2"))'`
***
also use the wrench icon on the jackett dashboard for zooqle and check what your site link is set as. usually https://zooqle.com
then please post the output of `curl -vvv https://zooqle.com/` and `openssl s_client -connect  zooqle.com:443` (replace the domains to the one not working for you)

**Comment by Tubaralho** [comment]
`$ csharp -e 'Console.WriteLine (new System.Net.WebClient ().DownloadString ("https://www.howsmyssl.com/").IndexOf ("1.2"))'
3636`

Site: https://zooqle.com/

`$ curl -vvv https://zooqle.com/
*   Trying 195.23.113.202...
* TCP_NODELAY set
* Connected to zooqle.com (195.23.113.202) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: self signed certificate
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.`

`$ openssl s_client -connect zooqle.com:443
CONNECTED(00000003)
depth=0 C = PT, L = Lisbon, O = " -", OU = " -", CN = *
verify error:num=18:self signed certificate
verify return:1
depth=0 C = PT, L = Lisbon, O = " -", OU = " -", CN = *
verify return:1
---
Certificate chain
 0 s:/C=PT/L=Lisbon/O= -/OU= -/CN=*
   i:/C=PT/L=Lisbon/O= -/OU= -/CN=*
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDWzCCAkOgAwIBAgIJAIWgF7nVoNWhMA0GCSqGSIb3DQEBBQUAMEQxCzAJBgNV
BAYTAlBUMQ8wDQYDVQQHDAZMaXNib24xCzAJBgNVBAoMAiAtMQswCQYDVQQLDAIg
LTEKMAgGA1UEAwwBKjAeFw0xNTAzMTIxMTQzMjVaFw0yNTAzMDkxMTQzMjVaMEQx
CzAJBgNVBAYTAlBUMQ8wDQYDVQQHDAZMaXNib24xCzAJBgNVBAoMAiAtMQswCQYD
VQQLDAIgLTEKMAgGA1UEAwwBKjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBANCAR5XdgBEuFTZ0cfqNQd0nFzQAPnMjWEPbD9kJwShK9J+zPwS4TEW2poni
bqocTDc26H7ubupIjwp2vyveRs4B1ceRr1aXBSDplWtc4FvkJqA6z02TAod0F60r
b6ri7tEUK5YQ+REE4/SW19nT6GduSkmTv4FcGxsr3LxYdw5uN6ZXMAmjdD3mth2h
ggmxIAu12k7GoTvqHqF00qkL6y+XmIA2ZvR/XFVq7uzgD7LgVPneIHiSQog/77gV
F8g/kpsATGXNfO2nzJOoQyH3yDtsKH5DDBu0sOlz8dEU21QteSqJKzkZkE2Vf3Hu
HSmQjjdpG/Dkx+zprBdpt923s8MCAwEAAaNQME4wHQYDVR0OBBYEFBWZajzFzU16
yh/KnCM1WHuxv5UXMB8GA1UdIwQYMBaAFBWZajzFzU16yh/KnCM1WHuxv5UXMAwG
A1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAAtSs40R2Kg6Wkf16OvVv1Kp
t2qAl45b1Dz0IGhT1Q814ay3YelAQ/goEeaF7rZsTvO6VtfRM/AV5TMYi0HdizYK
yKl28QhYXiSbq9SYUYuWgseZPNqcQlzjDf3VnsTpZPCVHCbDg7u3sErPxe12/DxU
GWf5ajrDHnvA0Iyre56n53LdnxkIFqMvbjeA0sQ/AY1djkr6O2XH+TfvhVfXcTqq
REtFv1xjDh0dn5TrvwDQ+RGTM9jPI8PSRsI+URzBFAT/D43FMRzk6TDjAyO+7a6z
8RciQPOOoDdwddIuwpnSvCK7QZePDqdYEwm72mjt8Dv4MFf+2RfPIUF6lVyo/vs=
-----END CERTIFICATE-----
subject=/C=PT/L=Lisbon/O= -/OU= -/CN=*
issuer=/C=PT/L=Lisbon/O= -/OU= -/CN=*
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1533 bytes and written 302 bytes
Verification error: self signed certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: B993B14B4BC1C7E4E5159E02C9190DBF53BF144A1691C9D818ADA16A575E9BE3
    Session-ID-ctx:
    Master-Key: 30D1D75D8C3E90D4B82E9C5058C6D9DDC0D642D2433597654A90C748A946CF39D04739C8939FDD1519F67563EFF18578
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 600 (seconds)
    TLS session ticket:
    0000 - 76 38 e2 ab 72 b4 bf f6-da d1 d7 f8 77 78 e1 1b   v8..r.......wx..
    0010 - 3b 49 42 d6 e0 a2 14 27-33 43 51 39 be 6a 6c 56   ;IB....'3CQ9.jlV
    0020 - 68 47 8b 3b d0 91 94 e6-b8 35 fd 84 62 47 a7 b3   hG.;.....5..bG..
    0030 - 85 1c 44 a2 78 0c 24 e8-6d 1e 62 f8 fa f8 b5 fa   ..D.x.$.m.b.....
    0040 - d9 48 8f d0 3a 56 88 52-a8 44 ac 38 56 c4 b8 24   .H..:V.R.D.8V..$
    0050 - 80 0d 6e ed ae b5 87 ab-b4 32 27 20 73 76 4e 5f   ..n......2' svN_
    0060 - ec a4 6b 82 fe 6a 3e 1f-21 b8 6c 9f 4f f9 1e 28   ..k..j>.!.l.O..(
    0070 - 2d 8d f2 3c 4f 24 4c a8-3c a7 f3 b7 52 40 15 13   -..<O$L.<...R@..
    0080 - f9 04 4a 78 30 1a 46 a0-e0 80 cc 98 c1 a9 df 1b   ..Jx0.F.........
    0090 - 86 ba 29 6b e8 63 02 6a-a0 b9 8a 93 97 2a 05 9a   ..)k.c.j.....*..
    00a0 - 62 05 7a 47 92 51 d1 8b-f1 79 0a 8c 2d ec 71 a8   b.zG.Q...y..-.q.

    Start Time: 1542139911
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)
    Extended master secret: no
---
`

**Comment by garfield69** [comment]
Ahh. your ISP is blocking your access to zooqle.com by redirecting you to 195.23.113.202 which returns 
`A página a que pretende aceder encontra-se bloqueada na sequência do cumprimento de ordem judicial ou administrativa.`
try switching your DNS to a public one such as cloudflare's 1.1.1.1 or google's 8.8.8.8 and 8.8.4.4 or for total privacy use a VPN

**Comment by Tubaralho** [comment]
Thank you @garfield69  =)
