### ISSUE TITLE
Jacket does not return proper results on immortalseed.me

### ISSUE THREAD

**Issue by Seeveen** [Jackett/Jackett#4151]
for some reson Jackett does not return results from immortalseed.me on some release groups from categories like 5000,5030,100009,100047,100048, the results does not show even when i search with Jackett

**Jackett version**:  
**Mono version** (if not using Windows):  
Jackett Version 0.10.422.0 WIN 10

-------------------------------
example in the image 

![imt1](https://user-images.githubusercontent.com/24566404/48375252-470d5c00-e6bf-11e8-83d0-80df83138c6b.png)
![imt2](https://user-images.githubusercontent.com/24566404/48375253-470d5c00-e6bf-11e8-88c9-cccf3e42a5ab.png)

**Comment by kaso17** [comment]
It was always skipping the first release, fixed via 9bd65ceaa25d901eebdf7d2e37f55a22170f67d8
