### ISSUE TITLE
feature req - add option search string MULTI - FRENCH [ethor]

### ISSUE THREAD

**Issue by danyboy666** [Jackett/Jackett#4152]
_Originally posted by @danyboy666 in https://github.com/Jackett/Jackett/issue_comments#issuecomment-438085506_

When setting couchpotato to search ethor with MULTi as pattern cp doesnt get anything but if i search directly in jackett the same pattern i get the result alright but instead of MULTi in the tag it get somehow replaced with FRENCH even if the torrent page as MULTi. I have torrentleech configured and it returnes the proper results with MULTi in the name. Is this a bug or confirmed and wanted behavior?

**Comment by danyboy666** [comment]
The tracker is not xthor by the way but one really close to it. 

I did not see this issue with torrentleech releases, only the "not xthor" tracker. How can I change this behavior?

**Comment by danyboy666** [comment]
I don't see that option for that tracker in particular is this a bug then? How come it replaces the search strings by default for that tracker in particular if it's not enabled somehow? I don't have that issue with torrentleech and that option is nowhere to be seen for that tracker either... If it's a bug i'll open a specific issue for this tracker or change the title for sometime more relevent this this issue.

**Comment by danyboy666** [comment]
Oh nice i'll change the ticket thanks for your help :)

**Comment by kaso17** [comment]
7b5508d3333203534d5e39c3432fe7309248736e makes it configurable (default off)

**Comment by danyboy666** [comment]
everything works perfectly thanks again
