### ISSUE TITLE
Takeabyte-support

### ISSUE THREAD

**Issue by delize** [Jackett/Jackett#4153]
Please provide Takeabyte support where possible. 

Having searched, there does not seem to be a request for this tracker.

**Comment by garfield69** [comment]
full address please, also is it private, public, semi?

**Comment by delize** [comment]
Sorry.

Semi-public. Open signups are a thing, but, not all the time.
http://takeabyte-nordic.org

**Comment by garfield69** [comment]
https://takeabyte-nordic.org/ returning ERR_CONNECTION_TIMED_OUT
Just me or is the site down, broken or moved to a new domain?

**Comment by ilike2burnthing** [comment]
Down here too. May have been down for the past 5 days - https://torrentinvites.org/f31/takeabyte-nordic-news-583350/

**Comment by garfield69** [comment]
@delize  do you have any info on https://takeabyte-nordic.org/
is the site gone, broken or moved to another domain?

**Comment by delize** [comment]
Honestly, not sure - it has been a while since I used it.

**Comment by garfield69** [comment]
OK. 
We will keep an eye on it and if in 25 days or so it still has not come online, or we don't find another domain by then, then we will remove the indexer.
If it ever comes back after that we can always add it back again.

**Comment by garfield69** [comment]
Jackett 0.17.87
