### ISSUE TITLE
Query - Zeronet support

### ISSUE THREAD

**Issue by Pantar2205** [Jackett/Jackett#4156]
Is there anyway to add [zeronet](https://zeronet.io/) sites, such as play, tvepisodes.bit or zerotorrent.bit?

just a brain fart idea. i think it would be fun to try figure out how to do it.

**Comment by kaso17** [comment]
I don't see any general problem with it. Should work like any other indexer.

**Comment by Pantar2205** [comment]
Thanks, I have my work cut out for me!!
