### ISSUE TITLE
Transmithe.net Error

### ISSUE THREAD

**Issue by aprillia99** [Jackett/Jackett#416]
When i test the connection i get this

Test failed for transmithenet: Failure has occurred while loading a type.

Im running jackett and sonarr on a bytesized seedbox if it matters with access on the master branch. 

`Jul 30, 2016 10:17:40 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
Jul 30, 2016 10:17:40 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Jul 30, 2016 10:17:40 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Jul 30, 2016 10:17:40 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Jul 30, 2016 10:17:40 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Jul 30, 2016 10:17:40 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Jul 30, 2016 10:17:40 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Jul 30, 2016 10:17:40 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Jul 30, 2016 10:17:40 PM	Info	
ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Jul 30, 2016 10:17:40 PM	Info	
ApiControllerActionSelector SelectAction 
Jul 30, 2016 10:17:40 PM	Info	
AdminController ExecuteAsync 
Jul 30, 2016 10:17:40 PM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Jul 30, 2016 10:17:40 PM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Jul 30, 2016 10:17:40 PM	Info	
DefaultHttpControllerActivator Create 
Jul 30, 2016 10:17:40 PM	Info	
HttpControllerDescriptor CreateController 
Jul 30, 2016 10:17:40 PM	Info	
DefaultHttpControllerSelector SelectController Admin
Jul 30, 2016 10:17:40 PM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Jul 30, 2016 10:17:40 PM	Info	
  http://eros.bysh.me:44344/Admin/GetLogs?_=1469929580971
Jul 30, 2016 10:16:28 PM	Info	
AdminController Dispose 
Jul 30, 2016 10:16:28 PM	Info	
AdminController Dispose 
Jul 30, 2016 10:16:28 PM	Info	
  Content-type='application/json; charset=utf-8', content-length=71
Jul 30, 2016 10:16:28 PM	Info	
AdminController ExecuteAsync 
Jul 30, 2016 10:16:28 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync 
Jul 30, 2016 10:16:28 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Jul 30, 2016 10:16:28 PM	Info	
ApiControllerActionInvoker InvokeActionAsync 
Jul 30, 2016 10:16:28 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]'
Jul 30, 2016 10:16:28 PM	Error	
Exception in test_indexer

Heres the code let me know if you need more...`

**Comment by flightlevel** [comment]
Just tested, and it works here
Maybe a site issue?
If still no good, try https://github.com/Jackett/Jackett/issues/320#issuecomment-214712447
