### ISSUE TITLE
Jackett service crashes after several hours

### ISSUE THREAD

**Issue by hjmuller** [Jackett/Jackett#4163]
After running for several hours, the jackett service on Linux crashes. I have auto update already disabled and no change. I don't have Mejortorrent, which seems to have caused similar problems. Enhanced log is included here.

[jackett_log.txt](https://github.com/Jackett/Jackett/files/2581992/jackett_log.txt)

**Jackett version**:   0.10.304.0
**Mono version** Mono JIT compiler version 5.16.0.179
**Distribution** Debian 9

-------------------------------

**Comment by drewk312** [comment]
im getting the same issue

**Comment by kaso17** [comment]
@hjmuller are you running from the console. Any chance that stderr output got lost? A simple exit without any actual crash is strange.

@drewk312 please post a log

**Comment by hjmuller** [comment]
@kaso17 No, it's not running from the console. Would something in the log I posted reveal an error?

**Comment by kaso17** [comment]
if there's some low level/bad crash mono should dump some data to the standard error output (not written to the jackett log). If you're using e.g. systemd you should see the error output using jounalctl (`journalctl -a -n 1000 -u jackett`)

**Comment by drewk312** [comment]
@kaso17  there is no way for me to post a log when I try I get enchanted log and click apply server settings I get  Error: Unable to resolve service for type 'romMilliseconds.pService' while attempting to activate 'Jackett.Server.Controllers.ServerConfigurationController'.

**Comment by garfield69** [comment]
drewk312 has a separate ticket #4167  for his issue open.
