### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://www8.yggtorrent.to/ using form selector 

### ISSUE THREAD

**Issue by grego31430** [Jackett/Jackett#4164]
**Jackett : 0.10.441.0**:  
** mono : 5.16.0.179** :  

-------------------------------
New URL of Yggtorrent, and form not found

**Comment by garfield69** [comment]
use the wrench on your jackett dashboard to edit your yggtorrent indexer.
change the site link to `https://www8.yggtorrent.to/` and click OKAY.
if you get an error message, then click CLOSE, then edit open again and click OKAY.
you change should then be saved.
OR
upgrade to the latest pre-release 0.10.442 to fix it automatically.

**Comment by Nemrod7** [comment]
I already tried with : https://www8.yggtorrent.to, it's not working.
