### ISSUE TITLE
Request support for torrof.com

### ISSUE THREAD

**Issue by sinwe** [Jackett/Jackett#4165]
Please support http://torrof.com

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by garfield69** [comment]
looks like torrof.com has been hijacked, currently redirecting to http://www.friendlyduck.com or https://en.usenet.nl

anyone know if there is an official new domain ?

**Comment by garfield69** [comment]
deleted this indexer. if it ever reappears we can easily add it back in.
