### ISSUE TITLE
jackett crashed?

### ISSUE THREAD

**Issue by drewk312** [Jackett/Jackett#4167]
I get 

"An error occured while testing this indexer
Unable to resolve service for type 'romMilliseconds.otectionService' while attempting to activate 'Jackett.Server.Controllers.IndexerApiController'."

when ever I try a indexer private or public

**Comment by garfield69** [comment]
Believe it or not, it is really important you tell us which version of jackett you are using and the mono version of applicable.

**Comment by drewk312** [comment]
Jackett Version 0.10.434.0 and I have no clue on mono im using Whatbox.ca

**Comment by garfield69** [comment]
open a terminal and try `mono --version` see what you get.

**Comment by garfield69** [comment]
I suggest you try to upgrade your mono to the latest release 5.16+.
follow instructions at https://www.mono-project.com/download/stable/  if you need to.
yjrm reboot and see what you get from jackett.

**Comment by untouchablefc** [comment]
Having this issue on rpi.

https://github.com/Jackett/Jackett/issues/3547#issuecomment-439691018
