### ISSUE TITLE
Error with SpeedCD

### ISSUE THREAD

**Issue by aprillia99** [Jackett/Jackett#417]
Getting this code when i test connection to speedCD

 Test failed for speedcd: body{height:100%;background:url("/V3/img/index.png");font-family:"tahoma","arial","helvetica","sans-serif";font-size:8pt}h5{font-size:16px}Wrong Captcha!Please press back and try again.

`When   Level   Message
Jul 30, 2016 10:19:44 PM    Info    
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
Jul 30, 2016 10:19:44 PM    Info    
ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Jul 30, 2016 10:19:44 PM    Info    
JackettAPINoCacheAttribute OnActionExecutingAsync 
Jul 30, 2016 10:19:44 PM    Info    
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Jul 30, 2016 10:19:44 PM    Info    
HttpActionBinding ExecuteBindingAsync 
Jul 30, 2016 10:19:44 PM    Info    
HttpActionBinding ExecuteBindingAsync 
Jul 30, 2016 10:19:44 PM    Info    
JackettAuthorizedAttribute OnAuthorizationAsync 
Jul 30, 2016 10:19:44 PM    Info    
JackettAuthorizedAttribute OnAuthorizationAsync 
Jul 30, 2016 10:19:44 PM    Info    
ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Jul 30, 2016 10:19:44 PM    Info    
ApiControllerActionSelector SelectAction 
Jul 30, 2016 10:19:44 PM    Info    
AdminController ExecuteAsync 
Jul 30, 2016 10:19:44 PM    Info    
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Jul 30, 2016 10:19:44 PM    Info    
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Jul 30, 2016 10:19:44 PM    Info    
DefaultHttpControllerActivator Create 
Jul 30, 2016 10:19:44 PM    Info    
HttpControllerDescriptor CreateController 
Jul 30, 2016 10:19:44 PM    Info    
DefaultHttpControllerSelector SelectController Admin
Jul 30, 2016 10:19:44 PM    Info    
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Jul 30, 2016 10:19:44 PM    Info    
  http://eros.bysh.me:44344/Admin/GetLogs?_=1469929580972
Jul 30, 2016 10:19:12 PM    Info    
AdminController Dispose 
Jul 30, 2016 10:19:12 PM    Info    
AdminController Dispose 
Jul 30, 2016 10:19:12 PM    Info    
  Content-type='application/json; charset=utf-8', content-length=224
Jul 30, 2016 10:19:12 PM    Info    
AdminController ExecuteAsync 
Jul 30, 2016 10:19:12 PM    Info    
JackettAPINoCacheAttribute OnActionExecutedAsync 
Jul 30, 2016 10:19:12 PM    Info    
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Jul 30, 2016 10:19:12 PM    Info    
ApiControllerActionInvoker InvokeActionAsync 
Jul 30, 2016 10:19:12 PM    Info    
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]'
Jul 30, 2016 10:19:12 PM    Error  
Exception in test_indexer
Jul 30, 2016 10:19:12 PM    Debug  
UnixLibCurlWebClient:GetString Returning OK => <!DOCTYPE html><html><head><link rel="stylesheet" href="/rsrc/css/l/com.css" type="text/css"><style>body{height:100%;background:url("/V3/img/index.png");font-family:"tahoma","arial","helvetica","sans-serif";font-size:8pt}h5{font-size:16px}</style></head><body><div style="width:500px;position:absolute;top:30%;left:50%;margin-left:-250px;text-align:center"><img src="/pic/ui/icons/warn.png" class="icon"><div class="textBubble bubbleAttention uiInput" style="text-align:left;margin-top:10px"><img class="icon" src="/V3/img/.gif"><div><h5>Wrong Captcha!</h5><div class="tx"><img src="/V3/img/.gif" class="txtIcon info" title="Information"><div class="txt">Please press back and try again.</div></div></div></div></div></body></html>
Jul 30, 2016 10:19:11 PM    Debug  
UnixLibCurlWebClient: Posting username=Aprillia99&password=Aprillia1
Jul 30, 2016 10:19:11 PM    Debug  
UnixLibCurlWebClient:GetString(Url:https://speed.cd/takeElogin.php)
Jul 30, 2016 10:19:11 PM    Debug  
UnixLibCurlWebClient:GetString Returning Redirect => 
Jul 30, 2016 10:19:11 PM    Debug  
UnixLibCurlWebClient:GetString(Url:https://speed.cd/browse.php)
Jul 30, 2016 10:19:11 PM    Info  
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
Jul 30, 2016 10:19:11 PM    Info  
ApiControllerActionInvoker InvokeActionAsync Action='Test()'
Jul 30, 2016 10:19:11 PM    Info  
JackettAPINoCacheAttribute OnActionExecutingAsync 
Jul 30, 2016 10:19:11 PM    Info  
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()'
Jul 30, 2016 10:19:11 PM    Info  
HttpActionBinding ExecuteBindingAsync 
Jul 30, 2016 10:19:11 PM    Info  
HttpActionBinding ExecuteBindingAsync 
Jul 30, 2016 10:19:11 PM    Info  
JackettAuthorizedAttribute OnAuthorizationAsync 
Jul 30, 2016 10:19:11 PM    Info  
JackettAuthorizedAttribute OnAuthorizationAsync 
Jul 30, 2016 10:19:11 PM    Info  
ApiControllerActionSelector SelectAction Selected action 'Test()'
Jul 30, 2016 10:19:11 PM    Info  
ApiControllerActionSelector SelectAction 
Jul 30, 2016 10:19:11 PM    Info  
AdminController ExecuteAsync 
Jul 30, 2016 10:19:11 PM    Info  
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Jul 30, 2016 10:19:11 PM    Info  
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Jul 30, 2016 10:19:11 PM    Info  
DefaultHttpControllerActivator Create 
Jul 30, 2016 10:19:11 PM    Info  
HttpControllerDescriptor CreateController 
Jul 30, 2016 10:19:11 PM    Info  
DefaultHttpControllerSelector SelectController Admin
Jul 30, 2016 10:19:11 PM    Info  
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'`

Thanks! let me know if you need anymore info

**Comment by the-toph** [comment]
I am also experiencing this same issue.

**Comment by flightlevel** [comment]
Have you checked your speed.cd profile, they've updated their security, looks like that is why its asking you for a captcha.
Works well here

**Comment by aprillia99** [comment]
Yes i did look, however found no captcha to enter...

**Comment by flightlevel** [comment]
@aprillia99 Have you tried turning GeoLocking to OFF in your profile -> security tab settings

**Comment by ScriptingGuy** [comment]
Just FYI, having this issue as well.  I did go to SpeedCD and set GeoLocking to OFF for my account.

Looking on the forms on SpeedCD they mention that Jackett needs to add support for the captcha function.

**Comment by L33B0B** [comment]
i am also getting this error. Was this issue resolved? If so how do i resolve mine?

**Comment by kaso17** [comment]
If someone could send an invite to kaso1717 -at- gmail.com I can fix it.

**Comment by Mahmoud87** [comment]
I can confirm Speed CD works now, I have added it successfully to Jackett and was able to get results from the tracker after doing a search.

**Comment by cretayo** [comment]
This seems to still be a issue. Im getting when trying to add this tracker:
```
An error occured while updating this indexer
body{height:100%;background:url("/V3/img/index.png");font-family:"tahoma","arial","helvetica","sans-serif";font-size:8pt}h5{font-size:16px}Wrong Captcha!Please press back and try again.
Click here to open an issue on Github for this indexer.
```

**Comment by kaso17** [comment]
@cretayo looks like they added an recaptcha after 1 failed login.
Please login from the same IP via a normal browser and solve the captcha to whitelist your IP again.
