### ISSUE TITLE
[BigTower] test ok but do not download any torrent

### ISSUE THREAD

**Issue by gandalf764** [Jackett/Jackett#4171]
Test is ok but if i try to download any file don't work... sorry for my english, i attach image i hope you understand. thanx
![2018-11-15 20_24_15-5 189 132 73](https://user-images.githubusercontent.com/41706025/48576480-f8f19600-e914-11e8-8cd2-5d5811b171a7.png)
![2018-11-15 20_23_40-jackett](https://user-images.githubusercontent.com/41706025/48576481-f8f19600-e914-11e8-8535-c0b6e1cebab7.png)

**Comment by kaso17** [comment]
@neothematrix @Jorman can you have a look at this?

**Comment by Jorman** [comment]
Just tried, is not on jackett side, give the same error if you go through the web

Maybe need to implement a thanks function?

**Comment by kaso17** [comment]
If the download works via their normal website only after a thank you that must be added to the indexer.

**Comment by Jorman** [comment]
Just did some test
Thanks is not needed
The problem is only to the most recent torrent, so
Or is a problem on the site
Or is a kind of block for non donor member, like you can download only torrent old than ...

**Comment by gandalf764** [comment]
sorry, i have a problem with my bigtower account... i cant' download any torrent,

**Comment by Jorman** [comment]
Just to explain.
Those files are only for donor people.
I ask if there's any tag or any others way to recognize that.

If yes maybe there's a way to filter it and add a flag to configuration, show or not show donor files.
In case, do you think is possible @kaso17 ?

**Comment by Jorman** [comment]
Yep, @kaso17 
All the torrent for vip have this
`<img src="https://cdn2.iconfinder.com/data/icons/crystalproject/128x128/apps/keditbookmarks.png" border="0" title="V.i.P" style="width:25px;">`

Do you think is possible to add an option to exclude vip and then remove from search and rssync all vip results?

**Comment by gandalf764** [comment]
as I understand it is not torrent reserved for donors, but since my 
account in bigtower is limited because I exceeded the limit of "hit & 
run" I can only download the torrents I downloaded earlier. not the new ones

Il 16/11/18 21:06, Jorman ha scritto:

**Comment by Jorman** [comment]
Your problem is about hit and run, but the same results are for vip torrent.
For example the torrent that this morning wont start, now start because are not vip anymore.

So you opened an issue for a non problem but we found a possible problem with vip content :)

**Comment by neothematrix** [comment]
Hi all!
My understanding is that BigTower treats every new release as vip only, it removes the vip tag after ~48 hours and then everybody can download it.
I'm not sure however what's the best way to deal with it.

**Comment by Jorman** [comment]
IMHO the best way is to exclude the vip, so if
![dddd](https://user-images.githubusercontent.com/5203988/48646307-ce710d00-e9e8-11e8-8939-c1efb942c2b5.PNG)
show all torrent
else the vip torrent are removed from the list

But I don't know if is possible to do with cardigan definitions
maybe @kaso17 or @garfield69 can tell more about it, maybe there's another better way to do that

**Comment by Jorman** [comment]
Sorry if I insist, but @kaso17 
do you think is possible with cardigans definition to filter and remove/keep only certain torrent?
Bigtower like others use images tag (like the multiplier) to differentiate vip torrent to normal torrent

**Comment by Jorman** [comment]
I'll try thanks!

**Comment by Jorman** [comment]
Like you predict, I need your help @kaso17 

This's the actual try for the row selector
```
    rows:
      selector: table > tbody > tr > td > table.lista > tbody > tr:has(a[href^="index.php?page=torrent-details&id="]){{if .Config.donor }}{{else}}:not(:has(img[src*="keditbookmarks.png"])){{end}}
```
but don't work, now no results, so is not good my approach, but seems correct to me.

Any idea?

**Comment by kaso17** [comment]
0a60686023fd2c07d001494fcc583bc96f948203 should enable the templating system for the rows selector

**Comment by Jorman** [comment]
Thank you, seems working
