### ISSUE TITLE
Updater Windows

### ISSUE THREAD

**Issue by ST33LDI9ITAL** [Jackett/Jackett#4174]
Why design the updater the way it is, it's not necessarily an auto updater in current form. Why not take the PID/Path from currently running service to auto kill/delete files and update automagically?

**Comment by kaso17** [comment]
currently the update works like this on windows:
Jackett process downloads the update package, extracts it and starts it. Then it exits itself.
The updater waits a little (to make sure the main process is dead and the Jackett files are no longer in use. If the tray is used it's killed by the updater too.
After that it copies replaces the files and starts the service/process again.

What exactly do you suggest to change?

**Comment by ST33LDI9ITAL** [comment]
I apologize, I'm a dummy. It's working fine.

**Comment by ST33LDI9ITAL** [comment]
I thought the updater.exe was standalone. I didn't realize part of functionality was in the actual service.
