### ISSUE TITLE
[yggtorrent] Indexer adress needs to be updated

### ISSUE THREAD

**Issue by Shasdo** [Jackett/Jackett#4180]
The indexer changed is web adress and I get this error:

> Exception (yggtorrent): Got redirected to another domain. Try changing the indexer URL to https://www8.yggtorrent.to/.: Parse error (Test)

Tried to changed the indexer adess as recommanded, stil getting an error:
> An error occured while updating this indexer
Login failed: No form found on https://www8.yggtorrent.to/ using form selector #user-login put the new adress in the field"

**Jackett version**:  0.10.422.0
**Mono version** (if not using Windows):  Docker Container, don't know how to do this.

-------------------------------

**Comment by garfield69** [comment]
use the wrench on your jackett dashboard to edit your yggtorrent indexer.
change the site link to `https://www8.yggtorrent.to/` and click OKAY.
if you get an error message, then click CLOSE, then edit open again and click OKAY.
you change should then be saved.
OR
upgrade to the latest pre-release 0.10.442 to fix it automatically.
