### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://www8.yggtorrent.to/ using form selector 

### ISSUE THREAD

**Issue by Nemrod7** [Jackett/Jackett#4182]
I can't add YGG Torrents on its new address : https://www8.yggtorrent.to

Thanks for the help !

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Login ok from my browser
2. Using the last version
3. http://pasted.co/94b3ed1a

**Jackett version**:  0.8.490-6
**Mono version** (if not using Windows):  5.8.0.108-11

-------------------------------

**Comment by 3ldcm** [comment]
Hello
there is no way that the setting up of a given day ygg, is done automatically
every 2 days, there is an error between jackett and ygg,
