### ISSUE TITLE
[blutopia] Exception (blutopia): Login Failed, got redirected.: Parse error (Test)

### ISSUE THREAD

**Issue by Hackerpcs** [Jackett/Jackett#4188]
**Mono version** (if not using Windows):  0.10.446.0

-------------------------------

https://pastebin.com/XyiUXMjU

**Comment by kaso17** [comment]
it's working fine for me, please double check your credentials.
7868798857c4212eef37d28615b6aacac71e1daa should improve the error handling (but won't fix your problem)
