### ISSUE TITLE
TorrentLeech- error message?

### ISSUE THREAD

**Issue by nishanm** [Jackett/Jackett#419]
When i try to set up torrentleech, i get " Configuration failed: Found no results while trying to browse this tracker" how can i go about fixing this.

**Comment by ajfried22** [comment]
Hmm it works fine by me but not on sonarr's end it says validation error. However that error does pop up for Xspeed as mentioned [here] (https://github.com/Jackett/Jackett/issues/386)

**Comment by nishanm** [comment]
Granted im on Version 0.6.45.0 (needed a tor that wasnt supported in the current)

**Comment by smarshallsay** [comment]
Failing for me now - with latest Jackett. 

I think its because Torrentleech is currently undergoing a site upgrade to v4.0 so the Jackett HTML parsing may have to be updated.

**Comment by kingnello** [comment]
Still doesnt work for me anyone have a fix for this ?

**Comment by kaso17** [comment]
is it working by now?

**Comment by nishanm** [comment]
still not working, i get this error now " Configuration failed: Found no results while trying to browse this tracker"

**Comment by kaso17** [comment]
please include a full log (start jackett with -t option)

**Comment by kaso17** [comment]
closing (no logs provided)
