### ISSUE TITLE
btbit unavailable

### ISSUE THREAD

**Issue by alexandregregoire** [Jackett/Jackett#4191]
![btbit unavailable](https://user-images.githubusercontent.com/26188087/48729533-7c2a2900-ec40-11e8-92c4-948f0565e490.png)
Hi guys,

btbit is unaccessible to me anymore.

the URL ( http://en.btbit.org/ ) returns 404.

Regards,
Alex

**Comment by garfield69** [comment]
working for me. try again, it might have been a temporary outage. in any case it has nothing to do with jackett.
