### ISSUE TITLE
[REQ] BJ-Share IMDB ID's Search

### ISSUE THREAD

**Issue by LecoBaliza** [Jackett/Jackett#4204]
BJ-Share allow search by IMDB IDs, but jackett don't find any result.

![image](https://user-images.githubusercontent.com/45101650/48876751-fb596180-ede6-11e8-83da-2014bb5bb6fd.png)
![image](https://user-images.githubusercontent.com/45101650/48876737-f1376300-ede6-11e8-81f6-c2c05029db21.png)

Can you update Jackett with this new search option?

**Comment by LecoBaliza** [comment]
@regisdepret AFAIK BJ doesn't support searching by IMDB/TVDB ID, if they do please let us know.

_Originally posted by @kaso17 in https://github.com/Jackett/Jackett/issues/610#issuecomment-343504526_

If the tracker would support searching via IMDB/TVDB IDs (using the normal website search form) this could be used.

_Originally posted by @kaso17 in https://github.com/Jackett/Jackett/issues/610#issuecomment-343509358_

**Comment by kaso17** [comment]
I picked some other random torrent group (https://bj-share.info/torrents.php?id=2593) but searching for tt1839337 on the page doesn't give any results.

In order to enable imdb search it must be reliable (always finding all corresponding torrents), otherwise it won't work very well with sonarr/radarr. I'd suggest you check with the BJ staff first to make sure it's working reliable.

**Comment by kaso17** [comment]
added IMDB search via 0f839682e17de774cc8fbfadd816df57c4e11667. Please test it and report the bug mentioned above to the staff.

**Comment by kaso17** [comment]
Now two more torrents have been added and the IMDB search works fine for the mentioned torrent. Looks like a search engine bug to me.

**Comment by LecoBaliza** [comment]
> Now two more torrents have been added and the IMDB search works fine for the mentioned torrent. Looks like a search engine bug to me.

I think it's a bug with only new movies, I'll wait for the launch to test

**Comment by LecoBaliza** [comment]
> Now two more torrents have been added and the IMDB search works fine for the mentioned torrent. Looks like a search engine bug to me.

It's the cache of site
