### ISSUE TITLE
[Req]: FutureTorrent

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#4205]
Hi, this's an Italian private tracker, actually is open for registration
http://futuretorrent.org

I'm trying to make it works, but I don't know if any other tracker have the same structure.

Basically the layout is the same of many Italian tracker and the "all torrent" page is under
http://futuretorrent.org/browse.php
But after the search, the URL remain the same, and I can't see how to force various option like categories, page and other option that I can set before do the search

Any advice or help to make it works?

**Comment by Jorman** [comment]
I'll try thanks!

**Comment by garfield69** [comment]
v0.21.648

**Comment by garfield69** [comment]
my account appears to have been deleted already. just me?

**Comment by Jorman** [comment]
Yes, just tried, with my old account. Not working and same situation, now invitation only.

**Comment by ilike2burnthing** [comment]
Same :/

**Comment by garfield69** [comment]
FutureTorrent is now PAY2DL, with download only available to those that have purchased a VIP account.

**Comment by garfield69** [comment]
v0.22.2223
