### ISSUE TITLE
Manicomio-share melhorar busca / improve search

### ISSUE THREAD

**Issue by samukets** [Jackett/Jackett#4207]
Hello friends, the definition of the manicomio-share indexer works very well, congratulations.

The problem is when I put the radarr to work with the jackett the raddar gets lost because the manicomio-share indexer does not give search by movie name + movie year.

Any tips on how we could do a better indexer? with the clearest title for radar to work?

For example, the jackett finds the title:

The Nun - The Nun [DualAudio Eng, Port] [+] [HDRip - 720p]

We therefore have Radarr to work, name in Brazilian Portuguese for the film, name in English for the film, audio that the film adopts, film format and resolution.

The problem is that to work in radarr we have to activate the option lenient mapping and this option brings us many false results.

Any way we can use to compose the title two fields? The first one we used, we got:

The Nun - The Nun [DualAudio Eng, Port] [+] [HDRip - 720p]

The second field would be the name of the torrent file that comes wrapped in the top-of-the-house release on the site:

The.Nun.2018.720p.HDRip.BLURRED.AC3.X264-CMRG-DUAL-LPM.torrent

Notice that we have more information in the file name.

The filename is in the html of the site.

Another point to note is that there are tags in the html that give various information that could leave the title for the radarr or sonarr more accurate with various information, could you help me with this work?

Follow the html source code of the tracker to identify a solution:

https://pastebin.com/CqbyHJvE

We have an excellent indexer today and my request would be to try to refine the search.

I use here to mark in this topic the author the indexer:  @Guizzoni

--

Olá amigos, a definição do indexer manicomio-share funciona muito bem, parabéns. 

O problema é quando coloco o radarr para funcionar com o jackett o raddar se perde pois o indexer manicomio-share não dá busca por nome de filme + ano do filme.

Alguma dica de como poderiamos fazer um indexer melhor? com o title mais claro para o radarr funcionar?

Exemplo, o jackett acha como título:

A Freira - The Nun [DualAudio Eng,Port] [+] [HDRip - 720p]

Temos portanto para o Radarr trabalhar, nome em português do brasil  para o filme, nome em inglês para o filme, audio que o filme adota, formato do filme e resolução.

O problema é que, para funcionar no radarr temos que ativar a opção lenient mapping e essa opção nos traz muitos resultados falsos.

Alguma forma de usarmos para compor o título dois campos? O primeiro já usamos, obtivemos:

A Freira - The Nun [DualAudio Eng,Port] [+] [HDRip - 720p]

O segundo campo seria o nome do arquivo torrent que vem disposto no topo de casa release no site:

The.Nun.2018.720p.HDRip.BLURRED.AC3.X264-CMRG-DUAL-LPM.torrent

Percebam que temos mais informações no nome do arquivo.

O nome do arquivo está no html do site.

Outro ponto a se observar é que existem tags no html que dão diversas informações que poderiam deixar o title para o radarr ou sonarr mais preciso com várias informações, poderiam me ajudar com essa trabalho?

Segue código fonte html do tracker para identificamos uma solução:

https://pastebin.com/CqbyHJvE

Temos hoje um excelente indexer e meu pedido seria no intuito de tentarmos refinar a busca.

Aproveito aqui para marcar nesse tópico o autor do indexer: @Guizzoni

**Comment by samukets** [comment]
Today I was taking a look at the script and saw that it looks in the page search.php, okay, so what I wrote above could not be used. So let's go there:

When the author of the definition did not put the year in the title, we ended up generating several false positives in Radarr.

Today when searching for a movie we have the following formatting:

The Nun - The Nun [DualAudio Eng, Port] [+] [HDRip - 720p]

I would like to try to use the other tracker information to try to refine the search for movies so that we can at least use the .torrent name for the title or to use the year of the movie at the end of the search.

Example:

The Nun [DualAudio Eng, Port] [+] [HDRip - 720p] (2018)

Today the tracker reports this way:

 |2018|A Freira - The Nun [DualAudio Eng,Port] [+] [WEB-DL - 720p]

The creator of the definition of MANICOMIO * gave the command remove: font [color ^ = green] to remove the | 2018 |, leaving only the name of the movie A Nun [DualAudio Eng, Port] [+] [WEB-DL - 720p], this generates false positives and confuses the radarr, some way to have the year of the movie at the end or to use the .torrent name as a title?

Another question is:

The Manicomio provides extra information on a form, you click the button and it loads the information, how could we get this information and use? They are information such as release date of the file in the tracker, movie release year and name of who released the file on tracker.

Any way to use this information to compose a title within the most standardized standard?

Example:

Name of the movie (2018)

Photograph:

! [image] (https://user-images.githubusercontent.com/2901904/48972292-0e964800-f006-11e8-8588-aa2afe648922.png)

search.php html

https://pastebin.com/BesU9PDy
______________________________________________________________________
Hoje estava dando uma olhada no script e vi que ele busca na pagina pesquisa.php , ok, desta forma o que escrevi acima não poderia ser usado. Então vamos lá:

Quando o autor da definição não colocou o ano no título, acabamos por gerar vários falsos positivos no Radarr.

Hoje ao pesquisarmos um filme temos a seguinte formatação: 

A Freira - The Nun [DualAudio Eng,Port] [+] [HDRip - 720p]

Queria tentar usar as outras informações do tracker para tentar refinar a busca por filmes para que ao menos tenhamos como usar ou o nome do .torrent para o título ou para que usemos no final da busca o ano do filme.

Exemplo:

A Freira - The Nun [DualAudio Eng,Port] [+] [HDRip - 720p] (2018)

Hoje o tracker informa dessa forma:

 |2018|A Freira - The Nun [DualAudio Eng,Port] [+] [WEB-DL - 720p]

O criador da definição do manicomio deu o comando remove: font[color^=green] para remover o  |2018| sobrando somente o nome do filme A Freira - The Nun [DualAudio Eng,Port] [+] [WEB-DL - 720p], isso gera falsos positivos e confude o radarr, alguma forma de termos o ano do filme ao final ou de usarmos o nome do .torrent como título?

Outra pegunta é:

O manicomio disponibiliza informações extras em um formulário, você clica no botão e ele carrega as informações, como poderíamos pegar essas informações e usar? São informações como data de liberação do arquivo no tracker, ano de lançamento do filme e nome de quem lançou o arquivo.

Alguma forma de usar essas informações para compor um título dentro do padrão mais normatizado?

Exemplo:

Nome do filme (2018)

Foto:

![image](https://user-images.githubusercontent.com/2901904/48972292-0e964800-f006-11e8-8588-aa2afe648922.png)

html da search.php

https://pastebin.com/BesU9PDy

**Comment by Guizzoni** [comment]
The problem is that the year shown in green is not reliable in many cases, sometimes they reflect the year that the movie was launched, other times they reflect the year the author uploaded the movie, that's why the year was removed.

We cannot use the .torrent filename to extract the year simply because the filenames, as well as many other informations on the tracker, doesn't follow a common pattern. If you search for older movies you'll see that many .torrent filenames don't even contain a year in them.

Finally, I don't think we can use the information contained after we click the "+" button. That information is only fetched after we click the button, and is not displayed anywhere on the page beforehand.

The releases name should follow a specific [naming rule](https://en.wikipedia.org/wiki/Standard_(warez)#Naming), they shouldn't contain only the year, like you suggested.

**Comment by samukets** [comment]
Hello friend, thanks for the reply.

So the Manicomio is not interesting with Jackett and Radarr.

If you ask to search for Halloween (2018) he will get everything that exists with halloween and will not get  what you really want.

Any automation recommendation for Brazilian users to get dual audio release on other trackers maybe?

**Comment by Guizzoni** [comment]
So, i suggest that you use BJ-Share, it has many dual audio releases and the search results are better.
