### ISSUE TITLE
NewPct problem obtaining .torrent

### ISSUE THREAD

**Issue by nygagest** [Jackett/Jackett#4212]
Hello, i've problem with the spanish provider NewPct, i've checked the url, changed it and checked i can manually download the .torrent from the web.

My problem:

When I try to dowload a file from newpct (doesnt matter what url i'm using). I download the torrent, with medusa, and it says the torrent is empty, here you are the error on the provider and it says the link has been not found. (I've triyed to paste the error but it has too many lines and github does not stylize it good).

Thanks
**Jackett version**:  0.10.455.0
**Mono version** (if not using Windows):  5.12.0.226

-------------------------------

**Comment by RmG152** [comment]
Same issue:
Jackett Version 0.10.492.0
Mono: idk, the included in the docker.

**Comment by kaso17** [comment]
@snamds can you have a look?

**Comment by snamds** [comment]
I've just checked it and it seems to be ok using descargas2020 url
Try to download a file using the jacket web/dashboard. If this works but medusa fails, is a problem with the medusa cache system:
  - Stop medusa service
  - Delete the file "cache.db". It's in the same folder that the "database file". Check "settings/help & info" to check the folder
  - Restart the service
  - Try again and let us know the result

**Comment by RmG152** [comment]
Changing url to descargas2020, fix the issue.

Tvsinpagar it's not working. 

Thanks @snamds

**Comment by kaso17** [comment]
are descargas2020.com and tvsinpagar.com using the same database and just use slightly different frontends?
Then i would suggest to change the URL to descargas2020 (or make the indexer work with both layouts).

**Comment by snamds** [comment]
I don't know how they handle this. There's a set of more than 5 webs with slight different frontends and slight different content. The main problem is that there are links that sometimes don't work in some web but work in the others one. That's why I let the web to be configured.
I already set the default link to descargas2020 but I suppose this is only used the first time you add the indexer. Maybe I could put a checkbox that if checked, the default link will be used

**Comment by RmG152** [comment]
Maybe add all of them as different indexers?

**Comment by snamds** [comment]
I've done this PR https://github.com/Jackett/Jackett/pull/4298
With this PR if the .torrent can't be downloaded, the indexer will try with other mirrors.
The mirrors included are  tvsinpagar, descargas2020, torrentlocura, torrentrapid and tumejortorrent

**Comment by kaso17** [comment]
@snamds 
you can specify LegacySiteLinks to auto update old site links (If a user has configured a site link listed in the array the site link will be reset to the default sitelink).

Example: https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/Anthelion.cs#L12-L14
