### ISSUE TITLE
[1337x] Exception (1337x): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /build/mono-5.16.0.179/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by Dubwize** [Jackett/Jackett#4215]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------
All indexers error out.   Seems to be happening more and more frequently as of late.

![image](https://user-images.githubusercontent.com/16105140/48986203-11fe0200-f0e0-11e8-8397-82b10c1a3f74.png)

**Comment by vinchi007** [comment]
had exactly the same issue with release 455 - reported #4195 6 days ago but noone responded. Today updated to the latest release 467 and problem went away. Hope this helps you. BTW, you haven't mentioned the version number where you see these failures. try 467 release

**Comment by Dubwize** [comment]
I was on 467 when the issue was happening. 

my docker just updated (2 hours ago) to 468 and it a has fixed the issue.
