### ISSUE TITLE
[torrentbytes] Exception (torrentbytes): Connection refused: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by ascii-ts** [Jackett/Jackett#4221]
**Jackett version**:  0.10.467.0  
**Mono version** (if not using Windows): Mono JIT compiler version 5.16.0.179 (tarball Thu Oct  4 10:29:10 UTC 2018)
running in a docker image on a synology

Torrentbytes is not working for me.
i use torrentleech also which works perfect.
i use jackett together with Sonarr.

The Test is not working in jackett and also in Sonarr
Login via Browser works and also the search

[logs.txt](https://github.com/Jackett/Jackett/files/2619885/logs.txt)

addtional error
"Jackett.Common.IndexerException: Exception (torrentbytes): A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.\n  at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x004f5] in <8143c7fff6c24f069b2e1e781bdabec4>:0 \n  at CloudFlareUtilities.ClearanceHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x0010c] in <d0213015414e4bf286b46bc1ee77bd72>:0 \n  at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x000ca] in <8143c7fff6c24f069b2e1e781bdabec4>:0 \n  at Jackett.Common.Utils.Clients.HttpWebClient.Run (Jackett.Common.Utils.Clients.WebRequest webRequest) [0x00456] in <dda892bf63604511bda348fd26c8509c>:0 \n  at Jackett.Common.Utils.Clients.WebClient.GetString (Jackett.Common.Utils.Clients.WebRequest request) [0x0010b] in <dda892bf63604511bda348fd26c8509c>:0 \n  at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies (System.String url, System.String cookieOverride, System.String referer, System.Collections.Generic.Dictionary`2[TKey,TValue] headers) [0x000cb] in <dda892bf63604511bda348fd26c8509c>:0 \n  at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry (System.String url, System.String cookieOverride, System.String referer, System.Collections.Generic.Dictionary`2[TKey,TValue] headers) [0x00160] in <dda892bf63604511bda348fd26c8509c>:0 \n  at Jackett.Common.Indexers.TorrentBytes.ProcessPage (System.Collections.Generic.List`1[T] releases, System.String searchUrl) [0x00085] in <dda892bf63604511bda348fd26c8509c>:0 \n  at Jackett.Common.Indexers.TorrentBytes.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x00158] in <dda892bf63604511bda348fd26c8509c>:0 \n  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x00091] in <dda892bf63604511bda348fd26c8509c>:0 \n   --- End of inner exception stack trace ---\n  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x000ee] in <dda892bf63604511bda348fd26c8509c>:0 \n  at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x0006b] in <dda892bf63604511bda348fd26c8509c>:0 \n  at Jackett.Common.Services.IndexerManagerService.TestIndexer (System.String name) [0x000a3] in <dda892bf63604511bda348fd26c8509c>:0 \n  at Jackett.Server.Controllers.IndexerApiController.Test () [0x000e1] in <69a0c9445fa74f4ea00f97239ea0f878>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0 \n  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <f5622e7f79be469e83d9e2bde9addd07>:0 \n  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0 \n  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <69a0c9445fa74f4ea00f97239ea0f878>:0 "

**Comment by kaso17** [comment]
The error indicates a timeout. Make sure https://www.torrentbytes.net is reachable form your server.

**Comment by ascii-ts** [comment]
that is strange. jackett is running on my synology which is in the same network as my laptop.
TB is responding very fast and works smooth in the browser.
Is there a way to increase the timeout and test it?

**Comment by kaso17** [comment]
connection refused means that the server or something else (firewall) actively prevented the connection attempt. Adjusting timeouts won't change anything.
