### ISSUE TITLE
[REQ] Add support for 32pag.es

### ISSUE THREAD

**Issue by curiositycasualty** [Jackett/Jackett#4223]
**Jackett version**:  0.10.471.0
**Mono version** (if not using Windows):  5.16.0.179

Please support 32pag.es as an indexer.

**Comment by kaso17** [comment]
This is often caused by missing CA certificates.
Try reimporting the certificates:
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`

**Comment by curiositycasualty** [comment]
@kaso17 er, was that comment meant for this issue?

**Comment by curiositycasualty** [comment]
@kaso17 I think it's a gazelle tracker-- how would I tell for sure?

**Comment by kaso17** [comment]
If you go to https://32pag.es/ajax.php?action=browse you should get some JSON formated search results

**Comment by kaso17** [comment]
{"status":"failure"} indicates that it's most likely the Luminance fork (additionally needs the auth parameter).
Unfortunately their API isn't very complete and all indexers are using HTML scraping instead of the API.
Have a look at e.g. the Empornium definition. Unless they heavily modified the layout only minimal changes should be needed.

**Comment by curiositycasualty** [comment]
Looking around the site, I found some resistance to integrating with Jackett when Mylar apparently has built-in support for the site already.
Which both means that the site inhabitants probably don't care for or want Jackett and that the admins probably won't support any work to get Jackett support integrated on their end of things. So I'm closing this.

**Comment by tkdrob** [comment]
@garfield69 Signup: https://32pag.es/application.php

**Comment by garfield69** [comment]
@tkdrob  thank you. 
But I am not interested in any site that requires me to provide a history of active membership at other sites.
I don't contribute to the scene and have no interest in such activity.
