### ISSUE TITLE
Redacted.ch doesn't appear as an "Add indexer" option

### ISSUE THREAD

**Issue by curiositycasualty** [Jackett/Jackett#4224]
**Jackett version**:  0.10.471.0
**Mono version** (if not using Windows):  5.16.0.179

-------------------------------

When clicking "Add indexer" through the UI, there is not option for PTH or Redacted.ch despite [Indexers/Redacted.cs](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/Redacted.cs) existing

**Comment by garfield69** [comment]
I have no problems looking up redacted
![image](https://user-images.githubusercontent.com/6933240/49121126-3b9f6f00-f314-11e8-8736-e46f6c320a13.png)
are you filtering your add-indexer list with something in the search  box?
perhaps its already been added to your active list ?

**Comment by curiositycasualty** [comment]
I'm a fool: I'd already added it.
Thanks!
