### ISSUE TITLE
[ilcorsaronero] Exception (ilcorsaronero): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /build/mono/src/mono/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by GiorgioBrux** [Jackett/Jackett#4225]
Getting this error with the tracker https://ilcorsaronero.cc/.
Tried the cert. fix but didn't worked. 

**Jackett version**:  0.10.467-1   | Arch
**Mono version**:    5.16.0.179-1

-------------------------------

**Comment by garfield69** [comment]
upgrade jackett to 0.10.471 for fix
