### ISSUE TITLE
Unable to add speed.cd

### ISSUE THREAD

**Issue by sfunk1x** [Jackett/Jackett#4226]
When I attempt to add speed.cd as an indexer, I immediately get an error:

https://gist.github.com/sfunk1x/88ea95638b4ba18bcf7152d4ab7282e7

It appears Jackett is trying to go to https://speed.cd/takelogin.php instead of https://speed.cd/login.php.

**Jackett version**:  0.10.468.0
**Mono version** (if not using Windows):  

Mono JIT compiler version 5.16.0.179 (tarball Thu Oct  4 10:29:10 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-/)
	GC:            sgen (concurrent by default)

-------------------------------

**Comment by kaso17** [comment]
fixed via 9a4092d7a2ceefa702f856e60b3f417ec5d33571

**Comment by hartk1213** [comment]
how do you update your install of jackett with this new Speed.cd update?

**Comment by sfunk1x** [comment]
There is a `Check for updates` button on the Jackett home screen. Take note of the version number on the page (bottom). Click `Check for updates`, wait a few moments, refresh the page. Compare version numbers. It may take several seconds for an update to complete (network latency, speed of environment Jackett is running in, etc).

FYI - this issue is resolved.

**Comment by hartk1213** [comment]
awesome thanks!

**Comment by finchy70** [comment]
Im on Jackett Version 0.10.525.0 and still have this issue.

**Comment by kaso17** [comment]
fixed via 7644a5e3bda9d3ae7ccffb74d1c10543cbbb210c

**Comment by maicss** [comment]
Is anyone konw what opencd architecture?  

![image](https://user-images.githubusercontent.com/9784767/105654498-18bf7400-5ef9-11eb-9385-9cea227abfc1.png)
