### ISSUE TITLE
Add tracker qctorrent.io

### ISSUE THREAD

**Issue by thenamelessthing** [Jackett/Jackett#423]
Please add the very great french (french canadian specialized) tracker.

It's private but maybe I can give you a way to access to the tracker if needed.

https://www.qctorrent.io/

FR/EN

I will be glad to help you if I can!

**Comment by thenamelessthing** [comment]
With the close of Bluetigers  we need an alternative!!  Please add this tracker!

**Comment by raspdealer** [comment]
Tu as une invitation?

**Comment by kaso17** [comment]
Please send an invite to kaso1717 -at- gmail.com and I'll add it.

**Comment by kaso17** [comment]
got an invite, thank you

**Comment by kaso17** [comment]
fixed with 0e59621650b9bccde371f538d10413a43a46baa8

**Comment by kaso17** [comment]
is this tacker dead?

**Comment by thenamelessthing** [comment]
Yes. ;-(

**Comment by kaso17** [comment]
thank you for confirming, removed via 7229da2fbbeca095592413a88649c99922a7258b
