### ISSUE TITLE
ygg season search only return season pack (not separated episodes)

### ISSUE THREAD

**Issue by Tezonis** [Jackett/Jackett#4234]
Hi,

Just noticed that when you search for a whole season of a series (with the jackett "season" mode), ygg indexer only returns season packs, not the separated episodes.
This is especially annoying with an ongoing season.
By searching a whole season, I mean: from Sonarr, click on the season search button (or whole series search button). This generates this url:
http://127.0.0.1:9117/api/v2.0/indexers/yggtorrent/results/torznab/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&q=This%20Is%20Us&season=3

This request return nothing but should return the same result than this manual search on YGG:
https://ygg.to/engine/search?name=this+is+us&description=&file=&uploader=&category=2145&sub_category=2184&option_saison%5B%5D=6&do=search

Note that I tested the same situation with Rarbg jackett indexer, it works. So it should be possible to do the same with any tracker.

This issue isn't really a big deal since we can click on the search button of each episode in sonarr, but it's not perfect :)

**Comment by xfouloux** [comment]
It works fine with sonarr v3 =) !

**Comment by Tezonis** [comment]
Ok, thanks! I will wait for stable version then :)

**Comment by xfouloux** [comment]
I submited a PR for sonarrv3 and jackett to match even better for season search =)
