### ISSUE TITLE
[torrent9] Exception (torrent9): A task was canceled.: A task was canceled. (Test)

### ISSUE THREAD

**Issue by sinopsysHK** [Jackett/Jackett#4239]
**Jackett version**:  0.10.471.0
**Mono version** (if not using Windows):  5.8.0.5108-11 (synology)

-------------------------------

Fresh new url is https://torrent9.ga
But previous "/top_torrent.php" does exists anymore

**Comment by garfield69** [comment]
The official torrent9 is still https://ww1.torrent9.ph however they are going through periods where their download links have been replaced by advertising for VPN. See this TF article of 20th November for details. https://torrentfreak.com/torrent9s-disappearing-downloads-boosted-vpn-referrals-181120/

Jackett from version 0.10.465 onwards, supports a clone site torrent9clone  at https://www.torrent9.ch which afaik still has working dl links.
Torrent9.ga is yet another clone but jackett does not have an indexer for this site.

**Comment by sinopsysHK** [comment]
I apologise but your statement is not correct!
Based on today’s tweet: https://twitter.com/_torrent9/status/1067897762841272322?s=20
Torrent9.ch is a fake
Torrent9.ph is closed and not maintained anymore
Torrent9.ga is the new official replacement.

**Comment by kaso17** [comment]
I agree with @garfield69 
Torrent9.ga should be added as a new indexer unless someone comes with a better proof that the original team is behind it.
To me it looks like it is another clone trying to step in as replacement.

**Comment by sinopsysHK** [comment]
Referring to the tweet again, original torrent9 team seems to have collapsed and it is a new team that had hand over.
Fair enough if it should be thus a new indexer.
