### ISSUE TITLE
cannot add iptorrents version 0.10.471.0. Error adding indexer, enhanced logs attached

### ISSUE THREAD

**Issue by jroncalli** [Jackett/Jackett#4241]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------
[log.txt](https://github.com/Jackett/Jackett/files/2629974/log.txt)
[log.txt.20181129.00000.txt](https://github.com/Jackett/Jackett/files/2629975/log.txt.20181129.00000.txt)
[log.txt.20181129.00001.txt](https://github.com/Jackett/Jackett/files/2629976/log.txt.20181129.00001.txt)

**Comment by kaso17** [comment]
is this still a problem?
looks like a (temporary) issue with iptorrents not returning any search results.

**Comment by lsnow2017** [comment]
I've been having a similar issue since when I first tried yesterday, here is a screenshot of what the output looks like when trying to add IPT. I tried upgrading Jackett and I'm certain the credentials are correct.

![image](https://user-images.githubusercontent.com/4197432/49241183-145ca680-f3d5-11e8-9efd-0c051ccda022.png)

**Comment by jroncalli** [comment]
I get "Found no results when trying to browse this tracker"

**Comment by kaso17** [comment]
@jroncalli do you get any results when you visit https://nemo.iptorrents.com/t ?
According to the log you don't get any.
You should get the most recent torrents.

@lsnow2017 please post a full enhanced log

**Comment by lsnow2017** [comment]
@kaso17 
False alarm, thanks for the assistance but it looks like when I thought I updated Jackett I actually did not. It is working now on v0.10

**Comment by kaso17** [comment]
go to the address in your browser. Don't include /t in the jackett config.

**Comment by kaso17** [comment]
sorry, @jroncalli make sure you're running the latest version and if it still dosn't work open a new issue including a full log
