### ISSUE TITLE
icetorrent test

### ISSUE THREAD

**Issue by VadVoci** [Jackett/Jackett#4243]
Jackett log.txt /usr/local/jackett/var/.config/Jackett

https://pastebin.com/HRY5e5KW

Jackett updater.txt /usr/local/jackett/var/.config/Jackett
https://pastebin.com/VfBwBx79

Jackett Version v0.10.471
mono-5.8.0.108-11

Synology DSM 6.1.4 synology_bromolow_3615xs

_Originally posted by @VadVoci in https://github.com/Jackett/Jackett/issues/4213#issuecomment-442982679_

**Comment by garfield69** [comment]
try pre=release 0.10.474

**Comment by VadVoci** [comment]
It still does not work.
"An error occured while testing this indexer
Found no results while trying to browse this tracker
Click here to open an issue on GitHub for this indexer."

IceTorrent_Search
https://pastebin.com/uWGH6zPG

Jackett_ICETorrent_Test_Button_log
https://pastebin.com/LKqBCekG

Jackett Version v0.10.475
mono-5.8.0.108-11

Synology DSM 6.1.4 synology_bromolow_3615xs

**Comment by VadVoci** [comment]
It still does not work.
"An error occured while testing this indexer
Found no results while trying to browse this tracker
Click here to open an issue on GitHub for this indexer."

IceTorrent_Search_in_Firefox
https://pastebin.com/V0zddmVy

Jackett_ICETorrent_Test_Button_log
https://pastebin.com/LKqBCekG

Jackett Version v0.10.475
mono-5.8.0.108-11

Synology DSM 6.1.4 synology_bromolow_3615xs

**Comment by kaso17** [comment]
they keep making small changes to the layout.
Fixed via 802ddfe6ee22c7ec545b9c5e8c270e8f657df1df
