### ISSUE TITLE
Updated to pre-release, still cannot add iptorrents

### ISSUE THREAD

**Issue by jroncalli** [Jackett/Jackett#4245]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.474.0
[log.txt](https://github.com/Jackett/Jackett/files/2631149/log.txt)

**Mono version** (if not using Windows):  

-------------------------------
Per @garfield69 updated to pre-release, still cannot add, 

 An error occured while updating this indexer
Found no results while trying to browse this tracker

is the error i get.

**Comment by garfield69** [comment]
sorry, I misread the ticket. 
iptorrents was last updated a month go, so the 0.10.474 does not have a fix for your current issue. 
i've assigned the ticket to kaso17 since he was the last chap to work on  the indexer (probably the only one with a login ;-)

**Comment by kaso17** [comment]
@jroncalli please try opening https://iptorrents.com/t in your browser. Do you get any search results?

**Comment by jroncalli** [comment]
I get the website, but it says no torrents found, I have to select a category to see any torrents

**Comment by jroncalli** [comment]
Updated to latest version this morning. I noticed there is not a definition (.yml) file for iptorrents in my installation?

**Comment by kaso17** [comment]
iptorrents is implemented as native indexer (no definition file). Something seems to be wrong with your iptorrents profile. When you go to https://iptorrents.com/t you should get a list of most recent torrents.
Did you configure any "Browse default categories" in your iptorrents profile? Please try to select/unselect all of them. It will take a few minutes after you saved the profile till the change is active.

**Comment by jroncalli** [comment]
@kaso17 that was the problem. I had "Show XXX Torrents Unselected" (intentional) but somehow had one XXX category selected as default. About a month ago, torrents stopped showing up when I first logged in, I had to pick a category first, I thought they changed there website, have no idea how those settings got set like that. Thank you for your help, your team's support is on it!

**Comment by jroncalli** [comment]
Do you have Donate system in place, would love to donate to the project.

**Comment by kaso17** [comment]
No there's no donation system around. But thank you for your offer.

**Comment by kaso17** [comment]
added 74e85180609fd37bd09dedece17938c75c8313ee to handle this case in case it happens to someone else.
