### ISSUE TITLE
[gimmepeers] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Hillage** [Jackett/Jackett#4246]
Testing tracker when first set up works fine, after browsing to the tracker on my web browser Jackett will no longer properly connect to the tracker. Unsure if this is a Jackett issue or a tracker backend issue. If I should make a post on the tracker forums please let me know and I will do so.

**Jackett version**:  0.10.471.0
**Mono version**:  5.16.0.220

[log.txt](https://github.com/Jackett/Jackett/files/2631398/log.txt)

**Comment by Hillage** [comment]
Updated to Jackett 0.10.475.0 and the problem remains as above (same error).

Running 0.10.475.0 in Visual Studio will not reproduce the bug. Successful test produces the following beginning of the response:

`11-30 21:14:16 Info Executing action method Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) - Validation state: Valid 
Jackett.Server> 11-30 21:14:16 Debug WebClient(HttpWebClientNetCore).GetString(Url:https://www.gimmepeers.com/browse.php?incldead=0) 
Jackett.Server> 11-30 21:14:16 Debug WebClient(HttpWebClientNetCore): Returning OK => <html><head>
Jackett.Server> <title>GP :: Browse</title>
Jackett.Server> <META name="description" content="GimmePeers.com the greatest blackhole!">`

**Comment by kaso17** [comment]
I don't have an account there.

Maybe @furryllama or @BenJaminBMorin can have a look at it.

**Comment by furryllama** [comment]
It's still working fine for me. If you login to the site in a web browser do you have a message? If so try clearing it, I think the alert box interferes with jackett.

**Comment by Hillage** [comment]
Announcements cleared, no new messages, top20 on or off, just doesn't like it. Oddly enough running it in Visual Studio worked fine, even without a saved password or being logged in already. The remote server that I'm having the issue on acts like it doesn't want to log in properly after I've logged in at home.

**Comment by furryllama** [comment]
Yeah the site is strictly about only being logged in from one IP at a time.

**Comment by Hillage** [comment]
Yea I can understand that... However I'll log out and close the web page and jackett still errors

**Comment by kaso17** [comment]
added automatic relogin via bcfccd83d422700ba1e47008e3d6d83a7c777138

**Comment by albertsj1** [comment]
Thank you for fixing this.  I've been having this problem for a while and didn't realize this was the cause.  I can confirm this has fixed the issue for me.
❤️
