### ISSUE TITLE
Bluetigers tracker doesn't work anymore...

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#425]
I can't just find this in logs...
Aug 05, 2016 01:18:04 PM    Info  
JackettAPINoCacheAttribute OnActionExecutedAsync 
Aug 05, 2016 01:18:04 PM    Info  
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()'
Aug 05, 2016 01:18:04 PM    Info  
ApiControllerActionInvoker InvokeActionAsync 
Aug 05, 2016 01:18:04 PM    Info  
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
Aug 05, 2016 01:18:04 PM    Debug  
UnixLibCurlWebClient:GetString Returning InternalServerError =>

**Comment by nabot93** [comment]
I reported this issue some time ago but no new... Issue #321

**Comment by flightlevel** [comment]
`Returning InternalServerError`
Usually means a problem on the web servers end, just tried now it works for me from Jackett

**Comment by raspdealer** [comment]
Still KO for me.

**Comment by eyotiste** [comment]
Don't work either here

**Comment by eyotiste** [comment]
Works with --IgnoreSslErrors true

**Comment by raspdealer** [comment]
Not good so...

**Comment by eyotiste** [comment]
SSL works on Bluetigers, but it appears that sometimes their cert is KO

**Comment by thenamelessthing** [comment]
Search seem to be broken, when I manually search for Warcraft partial result are found but not all release are found.

**Comment by kaso17** [comment]
Bluetigers has been shutdown, closing
