### ISSUE TITLE
[torrent-turk] Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by kekec777** [Jackett/Jackett#4250]
The user and password is correct / double checked
Please fix the issue :)

Jackett Version 0.10.475.0

**Comment by kekec777** [comment]
btw the only thing i could find in log was :

Info | Found 0 releases from TOrrent-tuRK

**Comment by garfield69** [comment]
going to need to see the captured html and detailed debug error that the **enhanced** log should contains, so
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by kekec777** [comment]
Thanks for the reply :)
Here's the log file :)

[log.txt](https://github.com/Jackett/Jackett/files/2638605/log.txt)

**Comment by kekec777** [comment]
Thanks for the reply :)
Here's my log ( I think i replaced all the personal with XXX)
[log.txt](https://github.com/Jackett/Jackett/files/2638625/log.txt)

**Comment by kaso17** [comment]
Looks like they did a major redesign or you can choose between different designs (check your profile settings for a classic view).
@bpikap can you have a look at this?

**Comment by kekec777** [comment]
Oww that did the trick , i just went to my profile and changed the "Torrent listesi" to "Klasik" and now its working :) 
👍 

Thanks for the help 🥇

**Comment by fevkalbeser** [comment]
@kekec777 having the same problem. But I cannot find any setting related to changing designs under my profile. I have the same nickname in the site, so you can write me back using it. Since it is now not an issue of Jackett. Thanks.

**Comment by fevkalbeser** [comment]
@kekec777 nevermind, I just found it. Thank you all.

**Comment by kaso17** [comment]
Added a note via 488e793a227dc23758033c85e16ca8ce93c04af6
It would be great if someone could adjust the definition to support both layouts.
