### ISSUE TITLE
[Tracker Request] gdf76.altervista.org

### ISSUE THREAD

**Issue by gandalf764** [Jackett/Jackett#4253]
I created this tracker to spread ITA films in mp4 format optimized for streaming.
Who has a plex server, with this service can automate the addition of new films with excellent quality to small dimensions.
I would like to include it here on jackett so that it can be known. At the moment it is poor in content but I plan to keep it up to date.
I hope it's possible. Thank you.

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

**Comment by gandalf764** [comment]
unfortunately I'm not able to do it .. I hope someone can
