### ISSUE TITLE
[News] Jackett is officially supported in qBittorrent

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#4254]
Jackectt is officially supported by https://github.com/qbittorrent/qBittorrent and it's enabled by default.
Could you add it to the readme?
Thank you!

**Comment by kaso17** [comment]
done via a4053d914a43223fd627d6d4f5fcd2db6d8cfd11

I see that you're using the jackett internal API for queries. It never was supposed to be a stable API. We would have recommended to use the Torznab API instead. But I'll try to notify you in case we have do breaking changes to the internal API.
