### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down.: Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#4255]
The domain `thepiratebay.org` is blocked in many countries and lately, there are troubles with Cloudflare.
Why we don't use a proxy instead?
https://piratebayproxy.info/
 I have been using `https://piratebay.live/` for a long time without problems. There are no ads, etc...

**Comment by kaso17** [comment]
As these are not official proxies we didn't add them. But they seem to work fine and are not doing to much harm so I added a note via 537e25df3b94bf269e640fd755bb3cce3324826d.
