### ISSUE TITLE
[Req] Allow to disable some indexers from manual search

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#4256]
When I use "manual searcher" feature, in most situations I don't want to search in all indexers I have configured.
I can select only 1 indexer in the combo, but, What if I have 10 indexers configured and only want to manual search in 3?
I'm proposing to add a "flag" in each indexer to exclude from manual search.
![imagen](https://user-images.githubusercontent.com/10577978/49329228-0ac17300-f57c-11e8-9c72-d0f753392dcf.png)

**Comment by kaso17** [comment]
Indexer groups have been proposed to solve this problem (See e.g. #2185) but no one is working on this currently.
