### ISSUE TITLE
[Req] Expose manual search API to be used by external clients

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#4257]
You already noted in  #4254 we are using the internal "manual search" API in qBittorrent.
Currently, there isn't any way to search in all configured indexers at once. Will be very useful in combination with #4256 

PD: There are other clients like Medusa/SickRage/SickBeard that you have to configure all indexers one by one... https://github.com/pymedusa/Medusa/wiki/Using-Jackett-with-Medusa

**Comment by kaso17** [comment]
There's an "all" aggregate indexer to search all indexers at once (see "Aggregate indexers" section in the readme).

In general we don't recommend using it because it comes with various limitations (different indexers support different search modes (imdb, search string, ...) and you loose control over detailed category mappings, etc.

#1413 has been proposed as recommended solution for this but once again no one is working on it.

For your use case with qBittorrent (always using the basic search string) it should work ok.

**Comment by ngosang** [comment]
@kaso17 I will try to update qBittorrent plugin to use that URL.

Could you reopen this issue with the purpose to add a button called `Copy All Torznab Feed` or something like that at the top? Currently this feature is hidden in the documentation...

![imagen](https://user-images.githubusercontent.com/10577978/49330016-c1c3eb80-f588-11e8-9fd5-a507c1f08a06.png)

**Comment by ngosang** [comment]
@kaso17 Updated: I can't use the torznab URL in qBittorrent because, for each result, there isn't a field with the Indexer name.
We are showing the torrent source:
![](https://camo.githubusercontent.com/9868b6678601ce0cf9b0ea8db2c30e5aba2e1688/68747470733a2f2f692e696d6775722e636f6d2f75436177674c612e706e67)

**Comment by kaso17** [comment]
Added an jackettindexer element to each item containing the indexer id/name (c0b9bb64f8482238e56509aa758eb78eed80157b)
Example: `<jackettindexer id="thepiratebay">The Pirate Bay</jackettindexer>`

We don't want to encourage the sonarr/radarr users to use the all indexer. If someone implements the grouping of course we would show it in that list. Till then I think we should keep it "hidden".

**Comment by ngosang** [comment]
@kaso17 Thank you! Will be used in next releases. We have to wait some time until most people update to a recent version of Jackett with this feature.

**Comment by ngosang** [comment]
@kaso17 FYI We are using the Torznab api instead of internal api in qBittorrent. => https://github.com/qbittorrent/search-plugins/pull/79

**Comment by kaso17** [comment]
great, thank you
