### ISSUE TITLE
As a user, when I make a manual search, I want query syntax so I can filter results #Enhancement #Help #Idea #Question

### ISSUE THREAD

**Issue by ldexterldesign** [Jackett/Jackett#4261]
Hi all,

Hope you're well

Thanks for software

As title

Search results are generally noisy places and it would be useful to filter[r] some of this noise:

```
league gentlemen -extraordinary // filters out all results containing "extraordinary"
```

If documentation exists then feel free to link me or else can something on this topic be added to the documentation?

If you're reading this and:

a) agree, then please up-vote and/or reply +1, or;
b) disagree, then I'd love to know why?

If you have any issues (e.g. questions/queries) happy to help

Hope this is useful and to hear back

Keep up great work!

Cheers

[r] E.g. https://duck.co/help/results/syntax

**Comment by kaso17** [comment]
Jackett itself doesn't support this currently.
In case the tracker supports it it should work transparently.

Just for clarification: do you meant the standard torznab query string (query text field on the manual search dialog or the search option of the manual search?

**Comment by ldexterldesign** [comment]
Thanks for reply

> Just for clarification: do you mean the standard torznab query string (query text field on the manual search dialog or the search option of the manual search?

<img width="800" alt="foo" src="https://user-images.githubusercontent.com/1715809/49343142-80a10980-f664-11e8-9176-cc9a486b3420.png">

TBH I think this could be a great opportunity to revise the query/search interactions (i.e. inputs) to search/filter instead, and offer users some query syntax to filter with - I'm assuming the filtering could be done on the client side so wouldn't involve what the trackers do or don't support?

Cheers

**Comment by RoloSoze** [comment]
@garfield69 Isn't this achieved with #8048?

**Comment by garfield69** [comment]
The difference between the query box and the search box:
- The content of the query box is what gets sent to to the website by jackett. 
Which words and filters are used and what is returned by the web site are totally dependent on what the web sites' search engine does with the query once sent.
We currently don't do much amendments to the query string except on an indexer by indexer basis, such as translating Sonarr's S01E01 into 1x1 for italian sites, and such like.
- The Search box string is what the Jackett page uses to filter the results displayed, once the results are returned by the query we sent to the web site. 
So #8048 introduced the negative filter for this search box.

Given the above, I think we can close this. I do not think there is more can be done with the query, as we need to keep this as generic as possible to allow all web sites to accept the queries we send them. And the search now has the negative which goes a long way to help reduce clutter.
There is little point getting creating by adding more filtering options, the reality is that most people will start by using the query box and continue to refine the query until they see what the want.
The search is used mostly by those that do multi-tracker queries and want to reduce the displayed results.
