### ISSUE TITLE
[REQ] Add Support for Tracker 3Evils

### ISSUE THREAD

**Issue by RikT** [Jackett/Jackett#4264]
It would be great if you could add support for this tracker https://www.3evils.com/ it's code base is U-232 V5 also it is a general tracker with an autobot

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

**Comment by RikT** [comment]
I tried altering a .yml from another tracker that uses the same source but for some reason I could not get it to work which is why I requested it as it has had me pulling my hair out, also if an invite is required ask me and I shall sort one out for you.

**Comment by garfield69** [comment]
3evils shifted to new engine (its the-unknown site relabelled) on new domain https://www.3evils.net
I'll update the 3eveils indexer with the engine code from the-unknown
new: new registration required.

**Comment by garfield69** [comment]
https://www.3evils.net/ returning  ERR_CONNECTION_TIMED_OUT

just me, or is the site gone, broken or moved toa new domain?

**Comment by ilike2burnthing** [comment]
Down here as well. No news regarding it, the last thing I can find is regarding a death in their team a month ago, so hopefully not related to that - https://torrentinvites.org/f31/3-evils-news-583364/
