### ISSUE TITLE
Self-configured tracker, help with Radarr search

### ISSUE THREAD

**Issue by fevkalbeser** [Jackett/Jackett#4273]
I have manually configured the definition file for Bitturk (a Turkish torrent website) mostly using another definition file of a website sharing the same template. 
[bitturk.zip](https://github.com/Jackett/Jackett/files/2642838/bitturk.zip)

I managed to make it work using Jackett's own search menu:
![jackett1](https://user-images.githubusercontent.com/26334331/49425792-b56da780-f7af-11e8-9d4b-61c979570480.JPG)

Configured the Radarr part:
![radarr2](https://user-images.githubusercontent.com/26334331/49425941-f796e900-f7af-11e8-9df8-e3f2fc91c934.JPG)

But when I make the same search through Radarr, I get all the movie torrents from the homepage of the website as a list, not the result of the search:
![radarr1](https://user-images.githubusercontent.com/26334331/49425977-1f864c80-f7b0-11e8-8977-4d041c0ccb4e.JPG)

Is this a problem with the definition file I configured? Maybe it is due to the dates not being grabbed correctly, but I don't know how to fix it. I am assuming I managed to get the category mapping right. 
If you think this is a problem with Radarr, maybe I should open an issue there. 
What do you think?

**Comment by kaso17** [comment]
The only obvious problem I see in the definition is that you're using keywordsfilters but then not using the results.

`keywords: "{{ .Query.Keywords }}"`
should be
`keywords: "{{ .Keywords }}"`

.Query.Keywords always contains the original unmodified keywords.

please enable enhanced logging and check the request which jackett sends to the tracker to see what's not working correctly.

**Comment by fevkalbeser** [comment]
@kaso17 Yeah, I had added that while trying to figure out a solution and forgot to remove. 
Please find the enhanced log below:
[log1.txt](https://github.com/Jackett/Jackett/files/2650396/log1.txt)
I could not find what's wrong with my limited knowledge. Any ideas?

**Comment by fevkalbeser** [comment]
@kaso17 Could you check the log file? Any suggestions?

**Comment by kaso17** [comment]
the log fine only contains the result of the request, not the actual request.

**Comment by garfield69** [comment]
the bitturk indexer was officially published in feb 2019 and presumably resolved this ticket.
