### ISSUE TITLE
[nordicbits] Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by samip5** [Jackett/Jackett#4275]
**Jackett version**:   0.10.479.0
**Mono version** (if not using Windows):   5.16.0.220
**Virtualization**: Docker container provided by linuxserver.io

Log file: [http://termbin.com/ugiwn](http://termbin.com/ugiwn)

-------------------------------
1. Tried to setup NordicBits trackker using the web GUI.
2. It failed, even though it found results to me.

**Comment by samip5** [comment]
This is not a exact duplicate.

**Comment by kaso17** [comment]
@hallengreenn can you have a look at this?

**Comment by Maximus97** [comment]
Having the same issue

**Comment by Maximus97** [comment]
@kaso17 Changing the stylesheet back to DarkV2 fixed the issue for me

**Comment by samip5** [comment]
> @kaso17 @samip5 Changing the stylesheet back to DarkV2 fixed the issue for me

You mean on the Nordicbits website?

**Comment by kaso17** [comment]
Which stylesheet doesn't work?

**Comment by samip5** [comment]
The xmas one at least.

**Comment by hallengreenn** [comment]
I can see I am a bit late to the party..
If the developers, just could hold on to one structure it would be easier.
Or maybe just give us the API. :)

I put a pull request in, which gives us support for all themes.
https://github.com/Jackett/Jackett/pull/4380

**Comment by samip5** [comment]
@hallengreenn I have talked to the site admins, and they are not really interested to make a API as to me they don't fully understand what Jackett is and how it would benefit them.

**Comment by garfield69** [comment]
closed by #4380
