### ISSUE TITLE
TorrentLeech: "Configuration failed:"

### ISSUE THREAD

**Issue by SjorsB** [Jackett/Jackett#428]
When attempting to add TorrentLeech I'm getting a "Configuration failed:" (with no additional error message) error. This may be a duplicate of https://github.com/Jackett/Jackett/issues/419, though the error message does differ.

Anyone else having the same issue?

**Comment by eangulus** [comment]
I am having the same problem. Clean install of 0.7.303.0, go in to add TorrentLeech as my first one, and I get configuration failed message.

**Comment by i-am-at0m** [comment]
It may have to do with their pending update, they may have broken something in the backend.

**Comment by manderss99** [comment]
same problem

**Comment by JiriBakker** [comment]
So I tried adding TorrentLeech again today, and this time it 'magically' seems to work. Likely due to TL changing some stuff on their pages. Issue can be closed (at least as far as I'm concerned).

P.S. Sorry for not posting the version earlier, it was (and is) 0.7.303.0 (same as @enagulus)

**Comment by smarshallsay** [comment]
Was working with latest but seems to be broken again :|

**Comment by flightlevel** [comment]
Willing to have a look if anyone has an invite jackettapp At gmail

**Comment by smarshallsay** [comment]
Invite sent

**Comment by CptanPanic** [comment]
I think they may have added captcha page.  Might need to add cookie field like some of the other ones.

**Comment by flightlevel** [comment]
@smarshallsay Could you please resend, nothing has come through

**Comment by kingnello** [comment]
I sent you one

**Comment by seanvree** [comment]
Any update?

**Comment by flightlevel** [comment]
Tried yesterday as well as just now and it works perfectly for me everytime, can't reproduce any problems here

![Imaget](https://snag.gy/cvHGEw.jpg)

Can you delete TL from Jackett dashboard and try re adding to see if it works.

If not, full logs needed https://github.com/Jackett/Jackett#troubleshooting

**Comment by kingnello** [comment]
Yeah i deleted it and added it again and now it works fine thanks but before you couldnt add it again if you deleted it so i think something was fixed somehow
