### ISSUE TITLE
Addition of tracker request 

### ISSUE THREAD

**Issue by TechGuyTN** [Jackett/Jackett#4287]
I wanted to ask if my tracker may be added to Jackett? Url is https://420files.org/ & Unit3d is software. 

Thanks in advance. :)

**Comment by HDVinnie** [comment]
The prior issue was poor and provided no information and was closed as it should have been. However @jackettbot this issue should remain open. @TechGuyTN you can shoot me a invite to unit3d@protonmail.come so I can properly map your categories and make a PR to add your sites definition file.
