### ISSUE TITLE
Issue with Changing RSS URLs

### ISSUE THREAD

**Issue by mrjackyliang** [Jackett/Jackett#4292]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.492.0
**Mono version** (if not using Windows):  not sure, docker image

-------------------------------

Again with the RSS feed issues. When I query the RSS feed, the `jackett_apikey` is different every time on load. I understand this may be for security purposes, but I have connected Jackett with `transmission-rss` which keeps querying the indexer, causing it to redownload already downloaded torrents in addition to causing too many requests on the indexer.

Is there a way to prevent the everchanging API URLs so this doesn't happen?

I've been using @nning's `transmission-rss` for a very long time, and this issue started happening after I updated Jackett.

**Comment by jcalado** [comment]
I've been having issues with jackett throwing off the rutorrent rss plugin, but the strings that constantly change are inside the <link> and <enclosure> tags of each item.

The "path" keeps changing with each request and rutorrent treats it as everything being new.

**Comment by kaso17** [comment]
@mrjackyliang : the API key shouldn't change. Make sure jackett can write to it's config directory.

@jcalado I don't understand your problem. Can you explain further, maybe with an example?

**Comment by mrjackyliang** [comment]
@kaso17 I'm using a docker image, and this was not an issue back before I updated it. I assume @jcalado is also having the same problem as me. The issue lies here. On every request, the `jacket_apikey` is changed:

First try:
```
<link>http://something.com:9117/dl/rarbg/?jackett_apikey=zg9cujhr4jjx3w6jtnlnq1i6pdgt0myz&amp;path=Q2ZESjhPMFh1bFl5b0tWQXFvRVgtN3hxM05GbzRNV2FJZ2M1ZE5RZ2E3emlPNEpjNmZTS2cyeFFZcUxybDZpZjRjWUcwbUlVeXpNeTFhd1pIbVdPcXpnZFpPV1FydS1DeUNTS1ItT0s4ZzRoQnBSbF9nanRJdDdUYjJmRGN1c0xJLXI2azJacngxNWI4YmhWeUxwaUJiTHhoRGFXTkVOU1I4dGVROU5SU1QtSy1WNzN5bmFndFNWUjFvWVcyTkl5V04xTjRpLXlUWEdZX1FLSHU0YlFZMlRncWltX1FrV0k1cnMydGk2Y3pjR2hXLVZl&amp;file=Robin.and.Marian.1976.BRRip.XviD.MP3-XVID</link>
```

Second try:
```
<link>http://something.com:9117/dl/rarbg/?jackett_apikey=zg9cujhr4jjx3w6jtnlnq1i6pdgt0myz&amp;path=Q2ZESjhPMFh1bFl5b0tWQXFvRVgtN3hxM05Gb1M0NTZfdF9zSTlrdEplb3Jqdm9NbE9rRUZ6bDJMWE9kYURxNGM0LUdxWEhmaVNoczRJQ0RaTWprbUlzUDBwaklwWWhsRm5abUl3cVAtSVNQYXFJbWM3Uko1THhTNHpaR0M0R2pibkdDVmRDaHFCZnpFTlZYMVZMbzRwV3U0aEpVWWdrWUNOa0hFb1l0N0pJXy1oa0JwdlpkVXpmeWVLMEVDLUVpRXdhVm16RWVKbmtzMG1pRl9CZnpMdUF3NzVqN191YTh1MFA0NHZtZHctMjBac1NJ&amp;file=Robin.and.Marian.1976.BRRip.XviD.MP3-XVID</link>
```

**Comment by kaso17** [comment]
You mean the path parameter? That's because rarbg is generating a new URL every time. No way to fix this.
If your RSS client detects this as a new item every time your RSS clients is broken. It should use the GUID attribute for making sure an entry is unique (instead of the link attribute).

**Comment by mrjackyliang** [comment]
I'm not understanding the issue. This issue happened after updating to the new Jackett version. Tagging @nning in this.

**Comment by jcalado** [comment]
> You mean the path parameter? That's because rarbg is generating a new URL every time. No way to fix this.
> If your RSS client detects this as a new item every time your RSS clients is broken. It should use the GUID attribute for making sure an entry is unique (instead of the link attribute).

Yeah, i figured as much. Already reported this on the rutorrent issue tracker. 
Thanks!
