### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Request to https://ww3.yggtorrent.gg/engine/search?category=2145

### ISSUE THREAD

**Issue by matelons** [Jackett/Jackett#4293]
Hi 
Exception with tracker 

**Jackett version**:  0.8.490-6
**Mono version** :  5.8.0.108.11

Dec 08, 2018 07:00:56 PM | Error | Jackett.Common.IndexerException: Exception (yggtorrent): Request to https://ww3.yggtorrent.gg/engine/search?category=2145&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date failed (Error GatewayTimeout) - The tracker seems to be down. ---> System.Exception: Request to https://ww3.yggtorrent.gg/engine/search?category=2145&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date failed (Error GatewayTimeout) - The tracker seems to be down.   at Jackett.Common.Indexers.BaseWebIndexer.CheckTrackerDown (Jackett.Common.Utils.Clients.WebClientStringResult response) [0x00080] in <edbb16b10cc14b91a0743945e52573b3>:0    at Jackett.Common.Indexers.BaseWebIndexer+<RequestStringWithCookies>d__5.MoveNext () [0x000d4] in <edbb16b10cc14b91a0743945e52573b3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Jackett.Common.Indexers.CardigannIndexer+<PerformQuery>d__29.MoveNext () [0x0085e] in <edbb16b10cc14b91a0743945e52573b3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x00091] in <edbb16b10cc14b91a0743945e52573b3>:0     --- End of inner exception stack trace ---   at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x000ee] in <edbb16b10cc14b91a0743945e52573b3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x0006b] in <edbb16b10cc14b91a0743945e52573b3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x000a3] in <edbb16b10cc14b91a0743945e52573b3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Jackett.Server.Controllers.IndexerApiController+<Test>d__15.MoveNext () [0x000e1] in <f973eff5f36f4333aa34fefc0b6cccca>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <f5622e7f79be469e83d9e2bde9addd07>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0    at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x0008a] in <f973eff5f36f4333aa34fefc0b6cccca>:0
-- | -- | --

-------------------------------

**Comment by garfield69** [comment]
works for me so try again. they may have had a temporary outage.
