### ISSUE TITLE
theshinning.org no longer provides results

### ISSUE THREAD

**Issue by s0mm3rb** [Jackett/Jackett#4304]
**Jackett version**:  0.10.509.0
**Mono version**:  Mono JIT compiler version 5.10.1.57

Hi
unfortunately theshinning.org does not provide results
I've enabled enhanced logging and saw that the html response does have the results in it:
`<table cellpadding="0" cellspacing="0" border="0" style="width:100%"><div class="title_wrap" title="releasename">
<a href="details.php?id=230431&amp;hit=1"onMouseOver="overlib('<img src=><img src=/bitbucket/f-230431-1.jpg width=250 heigth=250 >');" onMouseOut="nd();"<b>releasename</b></a>`

but Jackett says "Manual search for "releasename" on theshinning with 0 results."

**Comment by kaso17** [comment]
it's working fine for me, please let us know the exact release name/other search arguments you're using.

**Comment by s0mm3rb** [comment]
Hi
there is not one release where it does not work, it does not work at all
regardless of what i search Jackett says "0 Results"

Here is an example:
https://pastebin.com/xNN8ZAQM

**Comment by s0mm3rb** [comment]
@kaso17 do you need more info/logs?

**Comment by s0mm3rb** [comment]
@kaso17 - I fixed it by changing line 110 of the definition
System is FreeBSD: **FreeNAS 11.1-U5**
file: `/usr/local/Jackett/Definitions/theshinning.yml`
changed line 110 from 
`selector: table.main > tbody > tr:contains("Alle Torrents") + tr > td > table.tableinborder > tbody > tr`
to
`selector: div.bro_torr_wrap > table.tableinborder > tbody > tr`

**Comment by kaso17** [comment]
@s0mm3rb thank you for troubleshooting/fixing it.
The layout changes depending on the "Empfohlene Torrents in der Liste anzeigen" option in the profile.
822dc191dcbee39b22ebea0257bb3aae7e854adc should make it work in both cases.

**Comment by s0mm3rb** [comment]
@kaso17 oh I see
yes this option does affect the layout, didn't know that
thanks
