### ISSUE TITLE
[Feature Request] 0 Equals All Categories

### ISSUE THREAD

**Issue by zero77** [Jackett/Jackett#4305]
As an easy universal option to use all categories can you set 0 to equal all categories.
Thanks

**Comment by kaso17** [comment]
Not specifying the cat argument at all should equal all categories. If that's not the case it's a indexer specific bug.

**Comment by zero77** [comment]
OK, Thanks

**Comment by adamwinn** [comment]
Leaving it blank I get the error `Either 'Categories' or 'Anime Categories' must be provided`
