### ISSUE TITLE
Sonarr not finding shows from Avistaz

### ISSUE THREAD

**Issue by totesfabulous** [Jackett/Jackett#431]
Hi,

I am trying to add a Japanese show called Infinity Challenge.  When I do a search in Jackett I can find several episodes.  I can find the latest episode 492 in the Jackett search.

When I go to Sonarr and run a search for Infinity Search, every episode finds nothing.  When I read the logs for Sonarr I can see it checking the avistaz link.  

What logs could I pull to help me investigate this further?

**Comment by flightlevel** [comment]
In sonarr, turn your debug level up and it should give you the url that sonarr is using to search Jackett
eg.
http://localhost:9117/torznab/freshon/api?t=tvsearch&cat=5000,5030,5040&extended=1&apikey=xxxxxxxxx&offset=0&limit=100&q=Blacklist&season=3&ep=6
Add in your Jackett api key and you should have a good idea of what its searching for.
Often its a simple thing like an apostrophe that causes the issue

**Comment by tylerhammer** [comment]
This has been an issue for some time now. Jackett finds the episodes, but it does not translate to Sonarr.

Also side note... Infinity Challenge is Korean.

**Comment by tylerhammer** [comment]
Part of my logs `16-9-9 04:02:22.4|Info|NzbSearchService|Searching 1 indexers for [Cinderella and Four Knights : S01E03]
16-9-9 04:02:22.4|Debug|Torznab|Downloading Feed http://127.0.0.1:9117/torznab/avistaz/api?t=tvsearch&cat=5030,5040,5000&extended=1&apikey=(removed)&offset=0&limit=100&q=Cinderella%20and%20Four%20Knights&season=1&ep=3
16-9-9 04:02:22.7|Debug|NzbSearchService|Total of 0 reports were found for [Cinderella and Four Knights : S01E03] from 1 indexers
16-9-9 04:02:22.7|Info|DownloadDecisionMaker|No results found
16-9-9 04:02:22.7|Debug|Api|[GET] /api/release?episodeId=5762&sort_by=releaseWeight&order=asc: 200.OK (312 ms)
16-9-9 04:02:31.9|Debug|Api|[GET] /api/health: 200.OK (0 ms)`

**Comment by timeisapear** [comment]
Also having the same issue where no results are returned to Sonarr but results do show up in Jackett's manual search page. Any progress or is this a problem on the Sonarr side?

**Comment by kaso17** [comment]
is this still a problem?

**Comment by armani316** [comment]
@flightlevel Should this be closed since it hasn't had any activity in a while?
