### ISSUE TITLE
[yts] Exception (yts): The remote certificate is invalid according to the validation procedure.: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by AviTapp** [Jackett/Jackett#4313]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can log in and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.511.0
**Mono version** (if not using Windows):  Windows 10 Build 18290

-------------------------------

**Comment by garfield69** [comment]
yeah, nah. there is nothing wrong with the yts certificate. you are probably being blocked by your ISP and being redirected to a black hole.
to confirm, open a browser and try this link https://yts.am/api/v2/list_movies.json
you should get some text similar to
```
{"status":"ok","status_message":"Query was successful","data":{"movie_count":9803,"limit":20,"page_number":1,"movies":[{"id":10160,"url":"https:\/\/yts.am\/movie\/saving-christmas-
etc
```
what do you get?
