### ISSUE TITLE
[yts] Exception (yts): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /build/mono-5.16.0.220/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by Dubwize** [Jackett/Jackett#4318]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.504.0
**Mono version** (if not using Windows):   mono-5.16.0.220
Linuxserver.io Docker, latest pull, tag 350

-------------------------------

All test are currently failing and have been since at least last night ( i just noticed today, but nothing downloaded yesterday. so it's been going on since then.

Checked https://yts.am/api/v2/list_movies.json to make sure it wasn't a network issue.

I have noticed this is happening ever couple updates in the last few months.

[log.txt](https://github.com/Jackett/Jackett/files/2681809/log.txt)

Thanks all.  let me know if you need more.

**Comment by garfield69** [comment]
its possible it is a temporary outage at yts.
Please open a terminal on that linuxserver and post the output of `curl -vvv https://yts.am/` and `openssl s_client -connect yts.am:443` 
i dont have any issues using the jackett yts indexer on my ubuntu18 just now.

**Comment by Dubwize** [comment]
It is all indexers failing, not just YTS.

![image](https://user-images.githubusercontent.com/16105140/50033581-17f05000-ffc7-11e8-8e74-19b0b044a2ce.png)

**Comment by Dubwize** [comment]
also
![image](https://user-images.githubusercontent.com/16105140/50033624-40784a00-ffc7-11e8-9633-ccb0f565de57.png)

**Comment by garfield69** [comment]
@kaso17 @flightlevel  any ideas?

**Comment by Dubwize** [comment]
So my docker updated again, it's now on tag 353 (updated 3 hours ago) and everything is working.  Other than 1, but that is KAT and i'm not all that worried.

So I would have to assume this issue is somewhere in the docker that ls.io is building.

![image](https://user-images.githubusercontent.com/16105140/50046211-c2bb4980-006d-11e9-9d7d-ab1c705907bf.png)

**Comment by Dubwize** [comment]
Thanks for looking into everyone.
