### ISSUE TITLE
Feature Req: Configure Auto Update frequency & Update Now

### ISSUE THREAD

**Issue by AnthonyBe** [Jackett/Jackett#4321]
Given the rate of version updates, especially if you select to accept pre-release updates (as I do), there are 2 features relating to updating I would like to request for consideration:

1. Configurable 'check for new updates' frequency or interval. At the moment, I can't quite work out how often it checks for updates but it feels like a daily check. Given how often trackers change, updates are pushed, and where that falls around the current cadence of update checking, I love to see this be configurable down to as often as hourly.
2. Addition in the UI, and right-click menu option of the tray icon, of a "Check for Updates" option that initiates an update check. If auto update isn't disabled in the UI then this will also result in Jackett updating if a newer version is detected.

**Comment by kaso17** [comment]
marked as enhancement, currently jackett checks for updates 1 hour after start, and then every 24 hours.

**Comment by garfield69** [comment]
also, the dashboard already has a **check for updates** button, its at the bottom of the active list in a row with the **apply server settings** and **view log** buttons. ;-)

**Comment by AnthonyBe** [comment]
/facepalm. Thanks @garfield69 ! So much in the UI I had missed it!

**Comment by MichaIng** [comment]
Another vote for having an "Update now" button on the web UI.

**Comment by garfield69** [comment]
Closed as stale.

**Comment by TheManchineel** [comment]
Get Docker + Watchtower
