### ISSUE TITLE
Error when attempting to access Dashboard

### ISSUE THREAD

**Issue by MaskedPilgrim** [Jackett/Jackett#4328]
Hi guys.

I'm running a QNAP TS-251+ and have run into an error with Jackett version 0.10.97. I was running the latest QMono version 5.14.0.177 but have tried downgrading to the 5.12.0.266 version in case that helped. It didn't. 

Here is the error message coming up when I attempt to access the Dashboard:

> {
  "result": "error",
  "error": "Could not resolve type with token 01000015 (from typeref, class/assembly Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common, Version=0.10.504.0, Culture=neutral, PublicKeyToken=null)",
  "stacktrace": "  at (wrapper managed-to-native) System.Reflection.MonoMethodInfo.get_parameter_info(intptr,System.Reflection.MemberInfo)\n  at System.Reflection.MonoMethodInfo.GetParametersInfo (System.IntPtr handle, System.Reflection.MemberInfo member) [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 \n  at System.Reflection.MonoCMethod.GetParameters () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 \n  at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.TryFindMatchingConstructor (System.Type instanceType, System.Type[] argumentTypes, System.Reflection.ConstructorInfo& matchingConstructor, System.Nullable`1[System.Int32][]& parameterMap) [0x0002a] in <4b47b422bc4c4615bbdebe1df9b21b0d>:0 \n  at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.FindApplicableConstructor (System.Type instanceType, System.Type[] argumentTypes, System.Reflection.ConstructorInfo& matchingConstructor, System.Nullable`1[System.Int32][]& parameterMap) [0x00011] in <4b47b422bc4c4615bbdebe1df9b21b0d>:0 \n  at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory (System.Type instanceType, System.Type[] argumentTypes) [0x00000] in <4b47b422bc4c4615bbdebe1df9b21b0d>:0 \n  at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.CreateActivator (Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor descriptor) [0x00059] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.CreateControllerFactory (Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor descriptor) [0x00057] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvokerCache.GetCachedResult (Microsoft.AspNetCore.Mvc.ControllerContext controllerContext) [0x00059] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvokerProvider.OnProvidersExecuting (Microsoft.AspNetCore.Mvc.Abstractions.ActionInvokerProviderContext context) [0x0004e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ActionInvokerFactory.CreateInvoker (Microsoft.AspNetCore.Mvc.ActionContext actionContext) [0x00012] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler+<>c__DisplayClass12_0.<RouteAsync>b__0 (Microsoft.AspNetCore.Http.HttpContext c) [0x0003d] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 \n  at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x0017b] in <0c4aed80d53349aab59d38ff83ba08f0>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 \n  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <f5622e7f79be469e83d9e2bde9addd07>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 \n  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 \n  at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x0008a] in <0a91ce266b754e2f9559f6d01fcc31f8>:0 "
}

**Comment by garfield69** [comment]
i suggest upgrading your mono to the latest version, 5.16

**Comment by garfield69** [comment]
oh! sorry, just spotted you said qmono. @kaso17  can you look at this ticket please? thanks.

**Comment by kaso17** [comment]
no idea what's wrong. Try reinstalling jackett. Otherwise it looks like a qnap specific issue.

**Comment by MaskedPilgrim** [comment]
Unfortunatley reinstalling Jackett did nothing to help.

**Comment by flightlevel** [comment]
QNAP TS-251+ has docker. Make your life so much easier and using LinuxServer's image with docker

**Comment by garfield69** [comment]
presuming that switching to docker resolved this issue.
