### ISSUE TITLE
#Suggestion Remove https://pretome.info/

### ISSUE THREAD

**Issue by ldexterldesign** [Jackett/Jackett#433]
Hey,

Thanks for software

https://pretome.info/ doesn't appear to be associated with torrents [any longer], so I'd suggest it's removed ~ https://github.com/Jackett/Jackett/issues/163

![jhe8lpgswaptczgqqiecbagaabagqiecbagaabagqiecbagaabagqiecbagaabagqiecbagaabagqipcyba9eulx379pwjr4 wcxcu1mcuw7asbn68uyymjjsfcxf2nuoa mgdgocqiecaaaecbagqiecaaaecbagqiecaaaecbagqiecaaaecbagqiecaaaecbagqipdibqsghzmxcqgqiecaaaecbagqiecaaaecbagqiecaaaecbagq](https://cloud.githubusercontent.com/assets/1715809/17612647/b649f568-6054-11e6-9637-2d463987747f.png)

Hope this is useful

Regards

**Comment by CatmanIX** [comment]
uh, no, that's just a dummy page, if you're a registered user you have a key to enter into the search box to make the sign-in prompt appear and login to the site proper.

**Comment by CatmanIX** [comment]
For reference: http://torrentinvites.org/f36/pretome-ptm-general-2016-review-146234/#post634297

**Comment by flightlevel** [comment]
Thanks @CatmanIX removal reverted https://github.com/Jackett/Jackett/pull/446

@ldexterldesign I know you're trying to help, but I wouldn't post stuff like this unless you are a member of the site and know for sure

**Comment by ldexterldesign** [comment]
Hey all,

@flightlevel yep, I'll take your advice in future

Apologies
