### ISSUE TITLE
 [torrent-turk] Login failed: No form found on https://torrent-turk.org/?p=home

### ISSUE THREAD

**Issue by kekec777** [Jackett/Jackett#4334]
Im having issues with this tracker (I think they have redesigned their layout)

Jackett version:0.10.518.0

Log:

Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://torrent-turk.org/?p=home&pid=1 using form selector form#loginbox_form   at Jackett.Common.Indexers.CardigannIndexer.DoLogin () [0x004b2] in <fd648084227b4c4eab9ab2399fdd6a00>:0    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration (Newtonsoft.Json.Linq.JToken configJson) [0x00079] in <fd648084227b4c4eab9ab2399fdd6a00>:0    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig (Jackett.Common.Models.DTO.ConfigItem[] config) [0x0012d] in <4880c95bc06e41bba9f1b7c31deb574e>:0    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <f5622e7f79be469e83d9e2bde9addd07>:0    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <4880c95bc06e41bba9f1b7c31deb574e>:0
--

**Comment by kekec777** [comment]
Found the solution 

in torrent-turk.yml line 49:
method: form
should be change to:
method:post

and delete line 50 and 51:
    form: form#loginbox_form
    submitpath: /ajax/login.php

This resolved that current issue, BUT then there was an error with logout 
and when i take a look at the script , I can see logout is under test / line 67:
selector: a#logout
I just deleted this line also

And wolla its working now.
Somebody with more skills should take a look at these :)

**Comment by kekec777** [comment]
Hallo forum - 
I found out the site is not using "form" any more , but "post" 
So i changed line 49 from:
method: form
to
method: post
and deleted the next line 50:
form: form#loginbox_form
Im not sure if you should delete line 51 aswell but i just left it.
So a new problem , the test in line 67 (logout) comes with a error 
selector: a#logout
This line i just deleted aswell AND REMEMBER im only testing around so somebody with more skills should take a look at these settings / script and correct them.
And remember to restart jackett after these edits.
The new error i get is :
System.Exception: Found no results while trying to browse this tracker

I hope these testings will help you guys to correct it :)

**Comment by kaso17** [comment]
It's still using from login. Try the original definition and change the form selector to `form#sls_form`.

**Comment by kaso17** [comment]
@bpikap: can you have a look at this?

**Comment by kekec777** [comment]
I changed it and now i running to other problems :(
but im not sure its jacketts fault:
I can maunaly search a tv serie in jackett (It finds the episodes etc.)
BUT in Sonarr i get this error : (Have tried to change Categories aswell): 
RAW text:

An error occurred while processing feed. http://192.168.1.100:9117/api/v2.0/indexers/torrent-turk/results/torznab?t=tvsearch&cat=100165&extended=1&apikey=(removed)&offset=0&limit=100&q=Cukur&season=2&ep=1: Torznab error detected: Jackett.Common.IndexerException: Exception (torrent-turk): Error: An error has occured!There are no results found. ---> System.Exception: Parse error ---> Jackett.Common.ExceptionWithConfigData: Error: An error has occured!There are no results found.
  at Jackett.Common.Indexers.CardigannIndexer.checkForError (Jackett.Common.Utils.Clients.WebClientStringResult loginResult, System.Collections.Generic.IList`1[T] errorBlocks) [0x00095] in <fd1b4469badf4b71a5bfe32a916394f5>:0 
  at Jackett.Common.Indexers.CardigannIndexer.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x00bfd] in <fd1b4469badf4b71a5bfe32a916394f5>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseWebIndexer.OnParseError (System.String results, System.Exception ex) [0x00064] in <fd1b4469badf4b71a5bfe32a916394f5>:0 
  at Jackett.Common.Indexers.CardigannIndexer.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x01bd1] in <fd1b4469badf4b71a5bfe32a916394f5>:0 
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x00091] in <fd1b4469badf4b71a5bfe32a916394f5>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x000ee] in <fd1b4469badf4b71a5bfe32a916394f5>:0 
  at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x0006b] in <fd1b4469badf4b71a5bfe32a916394f5>:0 
  at Jackett.Server.Controllers.ResultsController.Torznab (Jackett.Common.Models.DTO.TorznabRequest request) [0x00335] in <4e2f03721764454e804e8c490d0687e3>:0

**Comment by garfield69** [comment]
@kekec777  If you send an invite to garfieldsixtynine @ gmail.com I can have a look at this issue.

**Comment by nomadturk** [comment]
Problem still exists, 
Instead of him, I've sent you one.  

Check your inbox.

**Comment by kekec777** [comment]
Sorry,  I couldn't find any invite and instead of torrent-turk, i started to use turktorrent

**Comment by garfield69** [comment]
registration and login successful. thank you.

**Comment by garfield69** [comment]
Try Jackett pre-release v0.10.883
if you want proper dates then set the language to English in your site profile.

**Comment by nomadturk** [comment]
Perfect, good to know. 
Thanks for the the quick solution.

Will check ASAP.

**Comment by garfield69** [comment]
https://torrent-turk.co/ returning ERR_NAME_RESOLUTION_FAILED
is the site gone, changed domain or just broken?

**Comment by kekec777** [comment]
@garfield69 
try this one: 
https://torrent-turk.com

**Comment by garfield69** [comment]
Thanks.
Domain .com redirects to .de, and .de works with the indexer. 
Jackett pre-release 0.11.569

**Comment by alpturkay** [comment]
how did you overcome this issue? i am having "Found no results while trying to browse this tracker (Test)"

**Comment by garfield69** [comment]
>how did you overcome this issue? i am having "Found no results while trying to browse this tracker (Test)"

@alpturkay if you provide the **full enhanced log** file I can take a look for you.
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by alpturkay** [comment]
@garfield69 I deleted my comment immediately since I figured i was not set up the entire thing correctly. (i forgot to convert the website in English and change the mode) Thanks!

**Comment by garfield69** [comment]
https://torrent-turk.de/ returning a Plesk Web Server's Default Page
is the site gone, changed domain or just broken?

**Comment by kekec777** [comment]
> https://torrent-turk.de/ returning a Plesk Web Server's Default Page
> is the site gone, changed domain or just broken?

Hmm I can log in without any problem ? 
But I haven't tested jackett (I'm moving apartment so haven't my server up yet)

**Comment by garfield69** [comment]
My bad, Sorry.
Did not pay attention to my notes, that state I need to use  a VPN to switch from my local region to another.
Torrent-Turk redirects my local region's IP block to the plesk, but works fine from elsewhere.
