### ISSUE TITLE
docker : can't start because Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/init\": stat /init: no such file or directory"

### ISSUE THREAD

**Issue by kornflex** [Jackett/Jackett#4338]
Hello,

I'm using Jackett with Docker more than a year and use watchtower to keep it up to date.

This night, jackett stopped but I can't start it :/

I have downloaded the latest image from linuxserver.io/jackett
Create a new container, but when I start it I have this error :

Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/init\": stat /init: no such file or directory"

Can you help me please ?

**Comment by kaso17** [comment]
the container isn't maintained by the jackett team itself. Please contact the linuxserver support.
