### ISSUE TITLE
[1337x] - RSS not working

### ISSUE THREAD

**Issue by Wilson2013** [Jackett/Jackett#4339]
RSS feeds for this site are missing many entries including all of the most recent ones.

For example 

http://127.0.0.1:9117/api/v2.0/indexers/1337x/results/torznab/api?apikey={my API key}&t=search&cat=&q=x265

returns nothing from the past few days.

Torznab Search for the site works perfectly.

**Comment by kaso17** [comment]
fixed via time/desc/
