### ISSUE TITLE
Fix https://beyond-hd.me/

### ISSUE THREAD

**Issue by ldexterldesign** [Jackett/Jackett#434]
Hey all,

Hope you're well

I'm having some issues connected to https://beyond-hd.me/

<img width="1440" alt="screen shot 2016-08-12 at 14 02 07" src="https://cloud.githubusercontent.com/assets/1715809/17621771/e40caa36-6095-11e6-8caa-3e3be3e99220.png">

Can anyone help - unfortunately, I can't piece together the related issues into a solution yet?:

https://github.com/Jackett/Jackett/issues/35
https://github.com/Jackett/Jackett/issues/111
https://github.com/Jackett/Jackett/issues/267

If SSH is the solution would someone be kind enough to elaborate on the ``[user@]hostname [command]`` option? CC @ipsq ~ https://github.com/Jackett/Jackett/issues/176#issuecomment-171347987

Hope to hear back

Yours faithfully

**Comment by ldexterldesign** [comment]
BUMP

**Comment by kaso17** [comment]
If you can sent me an invite to kaso1717 -at- gmail.com I can have a look at it.

**Comment by ldexterldesign** [comment]
Hey @kaso17,

Apologies for delay

Thanks for reply

Unfortunately, I don't have an invite (not my choice)

A quick issue search reveals it's likely caused by the use of https://www.google.com/recaptcha/intro/index.html ..?

Anyone else have https://beyond-hd.me/ working / not working?

Hope to hear back

Cheers

**Comment by kaso17** [comment]
To "fix" this use 127.0.0.1 instead of localhost to access jackett

**Comment by ldexterldesign** [comment]
Apologies for delay

Cheers for reply

Works great now - may I ask why/how this solves the problem and should I consider switching from localhost to port urls in the future for all websites?

Kind thanks

**Comment by kaso17** [comment]
localhost shouldn't be a problem in the most cases.
It's just a little special due to the way the captcha in included, it seems like google checks the hostname but makes an exception if 127.0.0.1 is used.
