### ISSUE TITLE
install_service_systemd.sh - no such file

### ISSUE THREAD

**Issue by JakeHillion2** [Jackett/Jackett#4343]
This is an installation issue. The installation instructions specify sudo ./install_service_systemd.sh, and there doesn't appear to be any such file in the downloaded tar.gz. I apologise if I am being stupid - I have no problem writing the service myself but I'm just confused as to why I cannot find the file.

**Comment by kaso17** [comment]
fixed via de0dd2b03579a27899148d947c59b19041b4721c
