### ISSUE TITLE
Add https://www.digbt.org/

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#4344]
Please add https://www.digbt.org/

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by ngosang** [comment]
@garfield69 @kaso17 thank you both!

**Comment by garfield69** [comment]
https://www.digbt.org/ returning ERR_CONNECTION_TIMED_OUT
just me or is the site broken, gone or moved to another domain?

**Comment by ngosang** [comment]
@garfield69 it's down. wait a few days before removing it, maybe they come back.

**Comment by garfield69** [comment]
cheers.
I usually give each site a months grace before I remove indexers.
I was hoping it was just a case of new-domain in which case I could have loaded a fix straight away. ;-)
