### ISSUE TITLE
Manual search in nnm-club.me (NoName Club) doesn't work in Cyrillic

### ISSUE THREAD

**Issue by HippyRock** [Jackett/Jackett#4346]
Hi, I'm using jackett docker (Jackett Version 0.10.525.0).
Trying to add manually search shows in "NoName Club" indexer and it doesn't return relevant results if I search in Cyrillic. For example if I search for "Мажор" it returns something like:

> Отдел С.​С.​С.​Р.​ (2011) WEBRip (серии 01-​08 из 08)

or

> Ю.​ А.​ Трофимов, А.​ Р.​ Ходжаев | Кто с ножом – тот и с мясом.​ Или конспекты по рукопашному бою (2018) [PDF] 

That is all great but has nothing to do with search criteria. Searches in English work just fine.

**Comment by hispex** [comment]
The issue caused by encoding the search query with cp 1251, but utf-8 is expected.
Are there any torrents that use non utf-8 encoding for http requests?

**Comment by ngosang** [comment]
@garfield69 it's Cardigann. Could you take a look?

**Comment by garfield69** [comment]
the indexer has `encoding: windows-1251`
if this does not allow for Cyrillic queries then the problem is likely with the cardigann processor someplace, either in the grabbing of the Cyrillic input or in the building of the query url sent to the site.

**Comment by garfield69** [comment]
Jackett 0.12.1746
