### ISSUE TITLE
Jackett finds movie doing a manual search but Radarr does not

### ISSUE THREAD

**Issue by daveinfla** [Jackett/Jackett#4347]
I'm still having the same issue with Jackett and Radarr even after the last update.

As an example, if I search for the following Hallmark Movie from within Radarr nothing is returned. If I do a manual search I get results from all my trackers.

Christmas In Evergreen: Letters To Santa

I'm attaching the Jackett log and screenshots

Thanks,

Dave

[log.txt](https://github.com/Jackett/Jackett/files/2701196/log.txt)

![image](https://user-images.githubusercontent.com/11258487/50320122-e67cf600-0498-11e9-864c-ef291d38b680.png)

![image](https://user-images.githubusercontent.com/11258487/50320126-ed0b6d80-0498-11e9-8758-76d5482ec6ec.png)

**Comment by garfield69** [comment]
show us a screencapture of your sonarr indexer definitions

**Comment by garfield69** [comment]
Does the radarr torrentday indexer config have a torznab categories field, and if so what are they set to at the moment?

**Comment by daveinfla** [comment]
At first I didn't think Radarr had category settings, like Sonarr, however if you unhide the advanced settings the following categories are listed by default:

2000,2010,2020,2030,2035,2040,2045,2050,2060

This led me to locate the following information on the Radarr support page. Look at the second paragraph labeled "Jackett shows more results than Radarr when manually searching"

https://github.com/Radarr/Radarr/wiki/Common-Problems

I followed the instructions to enable search by title and also strip the year, it did not make a difference, searches still come up blank...

Thanks,

Dave

Sent from my mobile device...


-------- Original message --------

**Comment by garfield69** [comment]
So the three hits from your jackett dashboard search for that movie on  torrentday showed cat TV/HD which is torznab cat 5040,  so if you want radarr to accept torrentday tvhd you will need to add 5040 to the category  list for that radarr definition.
Have a go and see if that helps.

**Comment by daveinfla** [comment]
That did the trick!

Can you refer me to the complete list of categories, so I can ensure I have all the necessary categories listed for both Radarr and Sonarr?

Thanks,

Dave

**Comment by garfield69** [comment]
you can find the categories defined for torrentday by using your jackett dashboard and editing the torrentday indexer. cats 10000+ are custom ones. 
for a list of torznab cats see https://github.com/nZEDb/nZEDb/blob/dev/docs/newznab_api_specification.txt#L608-L695
