### ISSUE TITLE
Auto-update with docker?

### ISSUE THREAD

**Issue by Ansem93** [Jackett/Jackett#4349]
Hi everyone,
I was wondering if it was possible to enable auto update if I've installed jackett via docker.
Apparently auto-update was disabled because of a bug:
https://github.com/linuxserver/docker-jackett/issues/44
I asked if it was resolved here:
https://github.com/linuxserver/docker-jackett/issues/65
but apparantly jackett is not supposed to auto-update if installed with docker. I don't get why since Sonarr and Radarr can do that without a problem.

Has the high resource bug resolved?

**Comment by kaso17** [comment]
you've to update the entire docker container, there are apparently tools to do this automatically.
