### ISSUE TITLE
[REQ] Ebookee

### ISSUE THREAD

**Issue by jamesmay07** [Jackett/Jackett#4353]
Please can you add Ebookee found here:
`https://ebookee.org`

Not sure if you need me to do anything seems like a open search engine, I'd add it myself but not sure how to :)

Thank you for looking and happy holidays

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by jamesmay07** [comment]
Thank you i'll have a go :)

**Comment by jamesmay07** [comment]
Sadly my host doesn't allow me access to the correct folder :(

**Comment by hispex** [comment]
@garfield69 ebookee.org is not a torrent site, it refers to file share sites.
Does it make sense to add it?
If so, I think I can handle the yml.

**Comment by garfield69** [comment]
If the site does not provide any .torrent or magnets then there  is little point adding it to jackett. 
Thanks for the info.
