### ISSUE TITLE
Linux build failing + Incomplete Linux build instructions

### ISSUE THREAD

**Issue by dshanks01** [Jackett/Jackett#4356]
**Jackett version**:  As of commit b8a9eef6cfab2f4a2ace6d34615dac2f47406dc3 (HEAD -> master, tag: v0.10.550, origin/master, origin/HEAD)
**Mono version** (if not using Windows):  Mono JIT compiler version 5.18.0.225

Attempted to follow the instructions in the README.md to compile under Linux (Mint 19.1).

Instructions do not mention that package dotnet-sdk-2.2 must be installed. Suggest adding that to the list of required packages, as the error messages produced during a build will not obviously point to that problem for developers inexperienced with C#.

After installing dotnet-sdk-2.2, I re-cloned the Jackett tag above. It's unclear whether the nuget command does the equivalent of a "make clean." Suggest adding instructions for any commands that need to be run to put the code tree into an "unbuilt" state before doing a re-build.

Ran nuget and msbuild as described in README.md. I get the following error messages:
```
Utils/Clients/HttpWebClientNetCore.cs(140,34): error CS1061: 'HttpClientHandler' does not contain a definition for 'ServerCertificateCustomValidationCallback' and no extension method 'ServerCertificateCustomValidationCallback' accepting a first argument of type 'HttpClientHandler' could be found (are you missing a using directive or an assembly reference?) [/home/david/Source/Jackett/src/Jackett.Common/Jackett.Common.csproj]
Done Building Project "/home/david/Source/Jackett/src/Jackett.Common/Jackett.Common.csproj" (default targets) -- FAILED.
Done Building Project "/home/david/Source/Jackett/src/Jackett.Server/Jackett.Server.csproj" (Build target(s)) -- FAILED.
Done Building Project "/home/david/Source/Jackett/src/Jackett.Server/Jackett.Server.csproj" (Build target(s)) -- FAILED.

Build FAILED.

"/home/david/Source/Jackett/src/Jackett.Server/Jackett.Server.csproj" (Build target) (1) ->
"/home/david/Source/Jackett/src/Jackett.Server/Jackett.Server.csproj" (Build target) (1:3) ->
"/home/david/Source/Jackett/src/Jackett.Common/Jackett.Common.csproj" (default target) (2:6) ->
(CoreCompile target) -> 
  Utils/Clients/HttpWebClientNetCore.cs(140,34): error CS1061: 'HttpClientHandler' does not contain a definition for 'ServerCertificateCustomValidationCallback' and no extension method 'ServerCertificateCustomValidationCallback' accepting a first argument of type 'HttpClientHandler' could be found (are you missing a using directive or an assembly reference?) [/home/david/Source/Jackett/src/Jackett.Common/Jackett.Common.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:19.65
```

A complete build log is attached: [build.txt](https://github.com/Jackett/Jackett/files/2706784/build.txt)

-------------------------------

**Comment by kaso17** [comment]
I've updated the linux build instructions for dotnet core version.
The mono build seems to be severely broken.
