### ISSUE TITLE
Jackett Rocks \m/ but ...

### ISSUE THREAD

**Issue by STaRDoGG** [Jackett/Jackett#4359]
Would love to have the ability to use some filters when on the Add Indexer page.

i.e. only show english language indexers, and public indexers. =)

Perhaps just some respective combo boxes above each column, that when selected filters the current list, as well as stores that choice for any subsequent loads of that page.

**Comment by ngosang** [comment]
You can use the search to filter by language and sort by type.

**Comment by STaRDoGG** [comment]
@ngosang Thanks. I want to use the filters on the add indexer page though, to make choosing indexers  easier (particularly when wanting to add new indexers that I've never used before, or even knew existed).

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/72788421-c967b780-3c96-11ea-9362-188f564fd4f2.png)

**Comment by STaRDoGG** [comment]
This works: `en-us public`. Thanks guys.
