### ISSUE TITLE
CloudFlare

### ISSUE THREAD

**Issue by stevenmcastano** [Jackett/Jackett#436]
Multiple sites are failing due to CloudFlare protection. Is there any way around this?

I think it may have something to do with coming through Tor. If I access the sites through a browser through Tor, I get the coudflare page, if I go through my normal browser direct to the internet, I get straight through.

**Comment by kblanks** [comment]
Two of my indexers (IPT and FileList) are failing in Jackett – they both use CloudFlare.

Anything that can be done about this? It's a pretty big problem.

**Comment by stevenmcastano** [comment]
For me in particular right now Demonoid is failing.

**Comment by drtrotusk** [comment]
I cannot get results from IPT too.
I'm getting the error message "Configuration failed: Found no results while trying to browse this tracker"

Although in the log it looks like it can find new releases http://pastebin.com/2E9JjgFw

Jackett Version 0.7.303.0

**Comment by ldexterldesign** [comment]
~ https://github.com/Jackett/Jackett/issues/365

**Comment by kaso17** [comment]
This should no longer be a problem.
