### ISSUE TITLE
Long tracker and category name issue in manual search

### ISSUE THREAD

**Issue by OliverLew** [Jackett/Jackett#4362]
**Jackett version**:  jackett-0.10.554-1
**Mono version** 5.16.0.220-1 (if not using Windows):  
System: Archlinux

-------------------------------
![screenshot from 2018-12-27 21-22-48](https://user-images.githubusercontent.com/12032219/50481866-da57e200-0a1e-11e9-8640-1a7264843325.png)
Some of the tracker names are quite long, like "Anthelion (TehConnection.me)"
![screenshot from 2018-12-27 21-34-22](https://user-images.githubusercontent.com/12032219/50481981-6538dc80-0a1f-11e9-9cfa-bc0870f1ca18.png)
And some torrent will have multiple categories, so the list  is like
![screenshot from 2018-12-27 21-33-22](https://user-images.githubusercontent.com/12032219/50482015-88fc2280-0a1f-11e9-981c-92866a518d84.png)
Those result in what is showed in the first image. There is almost no space for torrent names, then the names are all wrapped into multiple lines, then it does not look good.

There is previous issue where you solved wrapping in torrent names, maybe wrap the tracker and category names too?

**Comment by kaso17** [comment]
431570e696b91a868497b9c4aadaffcd065cc9f5 removed the old tehconnectin name
#3453 is the general issue (general search UI redesign) which should tackel this issue too.

**Comment by OliverLew** [comment]
Cool if the redesign will also solve this. I am already quite satisfied with the current UI and the issue you referenced has indeed bothering me too.

Since this issue is not fixed and I don't know how much of progress there is on the UI redesign, I just leave it open and hope that maybe you can solve this first if it is easy to do so. Of course, you can close it too if you see fit.
