### ISSUE TITLE
HD-Forever : missing categories ?

### ISSUE THREAD

**Issue by WSHaRK93** [Jackett/Jackett#4363]
Hello,

Current capabilities of tracker "HD-Forever" are : 
100001 | Movies/HD
2040 | Movies/HD

Doing manual search on "HD-Forever" tracker :
When I'm searching for "Mononoke" with "Any" I get results (categorized in Movies/HD)
When I select the 2 categories (100001 and 2040) I get no results

Same case when I'm searching for a musical movie.

I guess it's related to the categories in HD-Forever (Film | Dessin animé | Bonus BD | Concert | Série | Série anim)

**Comment by kaso17** [comment]
Unfortunately their API is broken.
https://hdf.world/ajax.php?action=browse&order_by=time&order_way=desc&searchstr=Mononoke&filter_cat[2]=1
searchs in category 2/Dessin animé (filter_cat argument) but the category key isn't included in the search results (Like it should be on proper gazelle indexers).

I disabled category support via ebcb82ed80781f5d8c342a66fc8254e8bb40da5d
You might want to report this to the staff, if they can fix the API it will provide better results.
