### ISSUE TITLE
[scenehd] Error reading JObject from JsonReader. Path '', line 0, position 0. (Config)

### ISSUE THREAD

**Issue by karlan85** [Jackett/Jackett#4364]
I get this errormessage when trying to add Scenehd to feed.
![image](https://user-images.githubusercontent.com/6490526/50486013-16c41780-09f8-11e9-9c69-b6018991989e.png)

I suspect it has to do with their own captcha-solution.
In the log:
Dec 27, 2018 04:47:12 PM	Info	
Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) in 275.7971ms
Dec 27, 2018 04:47:12 PM	Debug	
WebClient(HttpWebClient): Returning Redirect => https://scenehd.org/login.php?returnto=%2FsimpleCaptcha.php%3FnumImages%3D1 
Dec 27, 2018 04:47:12 PM	Debug	
WebClient(HttpWebClient).GetString(Url:https://scenehd.org/simpleCaptcha.php?numImages=1)

No problems in loggin in manually, and im running the latest version of Jackett (downloaded and installed fresh today).

**Comment by kaso17** [comment]
fixed via f3de97be6186ed752ec466f060762c01f5e1a5a1

**Comment by daymanbpi** [comment]
When i try to use the cookie Auth for scenehd, 
it doesnt list the _cfduid like in this https://raw.githubusercontent.com/Jackett/Jackett/master/.github/cookies-firefox.png
Am i missing something?

**Comment by kaso17** [comment]
_cfduid is a cloudflare cookie, it's not relevant
