### ISSUE TITLE
BJ-Share - Searching not working properly for daily shows

### ISSUE THREAD

**Issue by tnascif** [Jackett/Jackett#4365]
Jackett Version 0.10.554.0  
Mono version (if not using Windows): windows 

![jackett](https://user-images.githubusercontent.com/1376614/50489222-8d0f4c80-09ed-11e9-8162-576aca5b8592.jpg)

![jackett2](https://user-images.githubusercontent.com/1376614/50489230-9f898600-09ed-11e9-961b-10c1829d5ab1.jpg)

I'm not sure if there is a fix for that

**Comment by kaso17** [comment]
I believe even if Jackett would strip the date from the search sonarr wouldn't accept the results (date isn't included in the release titles). Instead BJ seems to use some year (season) and sequential episode numbering. If other trackers are using proper daily show naming schemes there's no low maintenance way to fix this (would need a fixed episode <> date mapping table in jackett). If the year/sequential episodes naming is used by all releases adjust the source of the date (thetvdb). And add some minimal rewrite code to jackett.

**Comment by garfield69** [comment]
fix available beginning with jackett pre-release 0.12.827
