### ISSUE TITLE
Request to Jackett server failed (torrent tracker magico)

### ISSUE THREAD

**Issue by valantislevas** [Jackett/Jackett#4366]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------
 Jackett Version 0.10.556.0 

it fails and i remove and add again and it says 
Request to Jackett server failed 
can u check it?

thanks a lot!!

**Comment by kaso17** [comment]
They got their domain hijacked or something else is wrong with it.
https://magico.info/ is no longer working.

**Comment by valantislevas** [comment]
yes now i see the new domain: magico.one can u change it? thanks...

**Comment by valantislevas** [comment]
@kaso17 thanks for the help can u confirm that magico.one is working to you?

thanks

**Comment by kaso17** [comment]
yes, working fine for me. Looks legit to me.
fixed via 1352d1528abdd647a1270162a669ff3518330492
Please investigate and make sure that it's the real magico and not some kind of clone/fake before we publish a new release.

**Comment by valantislevas** [comment]
ye its the real i saw it on fb original announce.. thanks for the change!!

have a nice new year!
