### ISSUE TITLE
torrent9 clone can't add to sonarr

### ISSUE THREAD

**Issue by kornflex** [Jackett/Jackett#4368]
Hello,

I try to add torrent9 clone to sonarr or lidarr with torznab link. I have an error : No results were returned from your indexer, please check your settings.

 But, with Radarr, it's OK.

The difference between theses apps is that Radarr doesn't have the "categories" field.

Thank you very much

**Comment by garfield69** [comment]
Add the following cats to your sonarr indexer definition for your t9clone 2000,5000
Radarr has cats for its definitions, they are hidden by default. May need to enable enhanced setting or similar to see them.
