### ISSUE TITLE
[REQ] Add new indexer - WtFnZb - Custom!

### ISSUE THREAD

**Issue by wtfnzb** [Jackett/Jackett#4372]
RSS/API is accessed via apache auth, so there would be needed some workaround for it.

**AUTHENTICATED** Accessing RSS via browser:
`https://USER:PASS@wtfnzb.pw/user/rss.php?code=PRIVATECODE&user=USER&cat=MP3`

NZBHydra2 returned **401: Unauthorized**

RSS Sample output:
```
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title>WtF[nZb]</title>
<link>https://wtfnzb.pw/</link>
<description>WtF[nZb]</description>
<language>en-us</language>
<copyright>NoCopyLeft</copyright>
<atom:link href="http://wtfnzb.pw/" rel="self" type="application/rss+xml" />
<item>
<title>Duke_Demont_-_Club_FG-SAT-12-29-2018-TALiON_[aae5e0591]</title>
<link>https://wtfnzb.pw/user/dl.php?nzb=Duke_Demont_-_Club_FG-SAT-12-29-2018-TALiON_[aae5e0591]&amp;date=/2018/12/29/&amp;code=PRIVATECODE&amp;user=USER</link>
<pubDate>December 29 2018, 11:26:35</pubDate>
</item>
</channel>
</rss>
```

**Comment by kaso17** [comment]
HTTP basic/digest auth shouldn't be a problem for jackett.

**Comment by ngosang** [comment]
@garfield69 is this bittorrent or nzb?

**Comment by garfield69** [comment]
I do not have a clue what this ticket is about.
All I know is that it is not an indexer that could be written in Cardigann yaml so I just set the ticket labels and left it for someone else to look into ;-)

The question is best directed to @wtfnzb who raised the ticket.

**Comment by cadatoiva** [comment]
This is an NZB tracker according to https://usenetreviewz.com/wtfnzb-review/

Pretty sure this is out of scope of our project then.
