### ISSUE TITLE
[yggtorrent] No result in Sonarr

### ISSUE THREAD

**Issue by MoonLS** [Jackett/Jackett#4376]
Hi

I'm on Arch-linux

My Jackett version is Package Details: jackett 0.10.566-1 - Last Updated: 2018-12-29 00:53
My Sonarr version is Package Details: sonarr 2.0.0.5252-1 - Last Updated: 	2018-10-09 17:20

I have configured 2 indexer in Jacket :
- yggtorrent
- nyaa

I have configured 2 custom indexer in Sonarr, the test are OK
- jackett_ygg
- jacket_nyaa

When I test to search in Sonarr with jackett_ygg, I have no result in auto and manual search
When I test to search in Sonarr with jackett_ygg, I have no result on auto but I have some in manual search 

When I test to search in Jackett, I have result for both indexers.

This is the logfile of Sonar when i search with jackett_ygg
`18-12-29 19:24:54.5|Info|NzbSearchService|Searching 1 indexers for [Boruto: Naruto Next Generations : 87]
18-12-29 19:24:55.1|Info|DownloadDecisionMaker|No results found
18-12-29 19:24:55.1|Info|EpisodeSearchService|Episode search completed. 0 reports downloaded.`

This is the logfile of Sonar when i search with jackett_nyaa
`18-12-29 19:29:52.7|Info|NzbSearchService|Searching 1 indexers for [Boruto: Naruto Next Generations : 87]
18-12-29 19:29:53.1|Info|DownloadDecisionMaker|Processing 14 releases
18-12-29 19:29:53.2|Info|EpisodeSearchService|Episode search completed. 0 reports downloaded.`

**Comment by garfield69** [comment]
check your sonarr ygg definition categories. the sonarr default of 5030 and 5040 are not part of the ygg cat suite.
add at least 2000,5000,5070.
if you want to see all the ygg cats, use your jackett dashboard and edit the ygg indexer with the wrench icon. add any of those to sonarr that you want it to include in its searches.

**Comment by MoonLS** [comment]
> if you want to see all the ygg cats, use your jackett dashboard and edit the ygg indexer with the wrench icon. add any of those to sonarr that you want it to include in its searches.

That's what I have done...

**Comment by MoonLS** [comment]
I foud the issue !

You need to define it in "categorie" and not in "anime categorie"

**Comment by MoonLS** [comment]
and I have put them in the anime categorie like said in jackett : 

> Configure the correct category IDs via the (Anime) Categories options. See the Jackett indexer configuration for a list of supported categories.

**Comment by garfield69** [comment]
MoonLS wrote:
>I foud the issue !
>You need to define it in "categorie" and not in "anime categorie"

notice that anime is in brackets signifying it is an option ;-)
anyway well done for sorting it out yourself.

**Comment by MoonLS** [comment]
Nop sorry I have reactive the nyaa indexer and it was a fake true...

Still not working

**Comment by garfield69** [comment]
i though we wera talking about ygg?
nyaa is an anime site so you'll need what ever cats are in the nyaa jackett config copied over to the sonarr anime section

**Comment by MoonLS** [comment]
Yep
It's just that I have re-activate nyaa indexer when I was testing.
So I have some result in my test, but it was for nyaa indexer.
I still have no result for my jacket indexer with YGG.

Sonarr have allredy nyaa indexer, you don't need of jackett. But for testing where was the issue I have set YGGTorrent and Nyaa in jacket and i have configure 2 customs indexer in Sonarr. One with jackett_YGG and the other with jackett_nyaa.

I have no issue with jackett_nyaa, so I suppose it was and issue in the configuration of jackett_YGG.

**Comment by MoonLS** [comment]
After searching i finally found the issue.

Sonarr is giving very bad search request.
This is the log in Jackett : 
`Manual search for "Boruto Naruto Next Generations 87" on yggtorrent with 0 results.`

For sure !
Boruto.Naruto.Next.Generations.E87 should be very better...

**Comment by Sonicfury** [comment]
5 years later still the same issue.

I believe the issue isn´t on Jackett's side since I have the exact same issue using Prowlarr.
I read here and there that Ygg don't like automated setup so they do stuff to break indexers on purpose. I don't know if it's true though...

**Comment by ilike2burnthing** [comment]
Please don't comment on 5yr old closed issues.

For YGG, make sure you have FlareSolverr configured - https://github.com/Jackett/Jackett#configuring-flaresolverr

If you have any problems, check our troubleshooting pages - https://github.com/Jackett/Jackett/wiki/Troubleshooting
https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

If you still have problems, open a new issue (here or for FlareSolverr, depending on where the problem lies) and provide the information requested.
