### ISSUE TITLE
GazelleGames has no Torznab category for OSTs

### ISSUE THREAD

**Issue by alexdelifer** [Jackett/Jackett#4378]
![ost](https://user-images.githubusercontent.com/1463882/50544686-04e79d80-0bcd-11e9-9eeb-81a368ab6618.PNG)

GGn has no Audio tag added to OSTs, even though it has Music as a capability.

I suppose you can call it a feature request, I have no cs knowledge, if it was a Definition I could probably swing it.
Basically somebody needs to put `filter_cat[4]=1` in to one of these
```
AddCategoryMapping("", TorznabCatType.Audio, "Audio");
```
Or whatever makes sense...

I'm using NZBHydra and it's causing all sorts of weirdness not being tagged at all.

Thanks!

**Comment by kaso17** [comment]
should be fixed via 71babe611a4acab0a4ca3bdda7461e1fd3e66437
