### ISSUE TITLE
Rejection Reason

### ISSUE THREAD

**Issue by mouzzampk2014** [Jackett/Jackett#4379]
Afternoon, 

I am getting this error when searching any movie or shows.

![img-20181230-wa0000](https://user-images.githubusercontent.com/44548525/50548227-defbe080-0c40-11e9-922c-b9fe83dcff3b.jpg)

Tracker: Majomparádé

Thank you

**Comment by kaso17** [comment]
fixed via c38b668ea2022db297558d0ff85185e54f3491f1

**Comment by mouzzampk2014** [comment]
Hello thank you so much. Do I need to do anything with manually c38b668 or Jackett will update and fix this issue? I'm not sure how to use this code c38b668? Thank you

**Comment by kaso17** [comment]
It will be part of the next release.
