### ISSUE TITLE
What does http://itorrents.org do? #Question #Help

### ISSUE THREAD

**Issue by ldexterldesign** [Jackett/Jackett#4383]
Hi all,

Hope you're well

Apologies this is off topic so feel free to close/ignore / suggest an alternative place to post but I discovered it via some Jackett settings:

<img width="712" alt="screenshot 2018-12-31 at 12 11 09" src="https://user-images.githubusercontent.com/1715809/50559255-41161d80-0cf5-11e9-98a5-3dc248f7f4f5.png">

What does http://itorrents.org do and what's the benefit to whom?

All in the interests of improving my bittorrent knowledge huh

Hope to hear back

Cheers

**Comment by kaso17** [comment]
it provides torrent files based on the hash (but not for all torrents). Some pages only provide the magnet link/hash in this case itorrents can be used to get a torrent file.
