### ISSUE TITLE
Computer completely froze when using v0.10.554

### ISSUE THREAD

**Issue by Jimmy03** [Jackett/Jackett#4386]
Win7 x64
Firefox 64.0
Jackett installed as service

I was in the middle of doing a manual search of public trackers from the dashboard in firefox and everything froze, couldn't move the mouse cursor, no hdd activity, I had to do a hard power off at the back of the computer.

I have no idea what caused it but I thought I should let you know.  
Nothing else was running, so I assumed it was Jackett. 
It happened as the search icon was spinning, fetching results from the trackers.  
  
Could be something with one of the public trackers being searched

**Comment by kaso17** [comment]
thank you for letting us know but it most likely was some random RAM bit flip or similar, CPU over temperature, etc.. Jackett shouldn't be able to crash your system.
