### ISSUE TITLE
IPTorrents- Configuration failed: Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by jik0n** [Jackett/Jackett#439]
Attempting to get into IPT and get this, confirmed login working fine. Any suggestions? Logs don't show much.

Aug 17, 2016 12:58:49 PM	Error	 Exception in Configure
Aug 17, 2016 12:58:49 PM	Info	Found 0 releases from IPTorrents
Aug 17, 2016 12:56:31 PM	Error	 Exception in Configure
Aug 17, 2016 12:56:31 PM	Info	 Found 0 releases from IPTorrents

**Comment by joel32724** [comment]
Got the same error.  Worked just fine a week ago.  Can log into IPT with no problem.

Aug 17, 2016 08:40:16 PM	Error	 Exception in test_indexer
Aug 17, 2016 08:40:16 PM	Info	Found 0 releases from IPTorrents
Aug 17, 2016 08:07:57 PM	Error	 Exception in Configure
Aug 17, 2016 08:07:57 PM	Info	Found 0 releases from IPTorrents

**Comment by theimmortal68** [comment]
I am having the same issue.  I am using Arch Linux, and I have tried multiple versions of Jackett.

**Comment by flightlevel** [comment]
Working now here on the latest release https://github.com/Jackett/Jackett/releases/tag/v0.7.317
Let us know if its fixed for you

**Comment by theimmortal68** [comment]
This fixed it for me!  Thank you!

**Comment by jik0n** [comment]
Working here as well, thank you!

**Comment by theoneandonlyjoshua** [comment]
Jackett Version 0.7.1256.0 seems to be the latest version on SynoCommunity...any chance of an update coming...I am seeing same issues...where previously it worked a charm
