### ISSUE TITLE
[arabafenice] Exception (arabafenice): Ssl error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER  at /build/mono-5.18.0.225/external/boringssl/ssl/tls_record.c:217: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by gandalf764** [Jackett/Jackett#4394]
the site admin told me that they changed from https to http
so now jackett does not work on this tracker, can you fix it? thank you

**Comment by gandalf764** [comment]
close... is a temp problem..

**Comment by memnos** [comment]
I've got the same issue.
Are we sure it is a temp problem?
