### ISSUE TITLE
Deluge - Failed to download release from indexer, no longer available.

### ISSUE THREAD

**Issue by markpeo** [Jackett/Jackett#4395]
**Jackett version**:  0.10.566.0
**Mono version** (if not using Windows):  5.14.0

-------------------------------
My setup is Sonarr (2.0.0.5252), Jackett & Deluge (1.3.15) dockers all running on unraid.
Get the following error reported to Sonarr from Deluge for torrents being auto-downloaded from TVCHAOS tracker. 

{edit} - I can overcome this by going into Jackett, manually searching for the episodes I want and after it finds them, go into Sonarr, update the RSS feed and then it downloads successfully.

[log.txt](https://github.com/Jackett/Jackett/files/2725505/log.txt)

ProcessDownloadDecisions	Failed to download release from indexer, no longer available. Emmerdale S50E003 (03 Jan 2019) Pt.1 HD720p mkv	15:22

Deluge	Downloading torrent file for episode 'Emmerdale S50E003 (03 Jan 2019) Pt.1 HD720p mkv' failed since it no longer exists (http://192.168.1.20:9117/dl/tvchaosuk/?jackett_apikey=(removed)&path=Q2ZESjhLckJQelNlV245R2tnWncway1rYkdVcW9GcHNVQkZHTzBaVmZXZldCdHdmN0tRdk0tRVV0Y1J6WDdFb0lCUWFWWHFyTGRRbGo2QTNpTF9rR2VBb21FWnc2U3pGTkYtRHlSbW51UEFjRDl4OTJzVHBCWDg4c1ZFcUp5b3ZxLWl3bHpLZ3ZaOTdEeGpEVXYwdGgyUmg2Z3ZMMFd6aVA2REZOVTRIbE5Zd0RLR1V0c09PdU5nWERCdmlnZmwtdm1pTzNR&file=Emmerdale+S50E003+(03+Jan+2019)+Pt.1+HD720p+mkv): HTTP request failed: [404:NotFound] [GET] at [http://192.168.1.20:9117/dl/tvchaosuk/?jackett_apikey=1c6okq170tf0i8dyp4azci2r46r6ty53&path=Q2ZESjhLckJQelNlV245R2tnWncway1rYkdVcW9GcHNVQkZHTzBaVmZXZldCdHdmN0tRdk0tRVV0Y1J6WDdFb0lCUWFWWHFyTGRRbGo2QTNpTF9rR2VBb21FWnc2U3pGTkYtRHlSbW51UEFjRDl4OTJzVHBCWDg4c1ZFcUp5b3ZxLWl3bHpLZ3ZaOTdEeGpEVXYwdGgyUmg2Z3ZMMFd6aVA2REZOVTRIbE5Zd0RLR1V0c09PdU5nWERCdmlnZmwtdm1pTzNR&file=Emmerdale+S50E003+(03+Jan+2019)+Pt.1+HD720p+mkv]	15:22

HttpClient	HTTP Error - Res: [GET] http://192.168.1.20:9117/dl/tvchaosuk/?jackett_apikey=(removed)&path=Q2ZESjhLckJQelNlV245R2tnWncway1rYkdVcW9GcHNVQkZHTzBaVmZXZldCdHdmN0tRdk0tRVV0Y1J6WDdFb0lCUWFWWHFyTGRRbGo2QTNpTF9rR2VBb21FWnc2U3pGTkYtRHlSbW51UEFjRDl4OTJzVHBCWDg4c1ZFcUp5b3ZxLWl3bHpLZ3ZaOTdEeGpEVXYwdGgyUmg2Z3ZMMFd6aVA2REZOVTRIbE5Zd0RLR1V0c09PdU5nWERCdmlnZmwtdm1pTzNR&file=Emmerdale+S50E003+(03+Jan+2019)+Pt.1+HD720p+mkv: 404.NotFound	15:22

**Comment by kaso17** [comment]
should be fixed via ce15cb8bfec2eab56f80a5be82fcfb9cfdc137c9
