### ISSUE TITLE
[Tracker Request] TeamHD

### ISSUE THREAD

**Issue by n-ozerov** [Jackett/Jackett#4397]
https://teamhd.org/ -- reincarnation of private tracker HDClub #

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by garfield69** [comment]
currently requires an invite code.

**Comment by garfield69** [comment]
If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by n-ozerov** [comment]
Invite sent.

**Comment by garfield69** [comment]
registration and login successful. thank you.

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.334

**Comment by RoloSoze** [comment]
@garfield69 TeamHD needs the year stripping code from https://github.com/Jackett/Jackett/issues/7424#issuecomment-619158028. Exact same issue - entering the release year in the search strings returns nothing.

**Comment by garfield69** [comment]
Jackett 0.16.284

**Comment by garfield69** [comment]
https://teamhd.org/ 502 Bad Gateway nginx

**Comment by garfield69** [comment]
online
