### ISSUE TITLE
[Req] Add bitsoup.me tracker

### ISSUE THREAD

**Issue by mentasm** [Jackett/Jackett#44]
Can you look at adding bitsoup.me tracker?

I can probably sort out an invite.

**Comment by raspdealer** [comment]
https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker

**Comment by flightlevel** [comment]
Swamped with requests at the moment, will request an invite from you at a better time

**Comment by mentasm** [comment]
ok.  I'll look if I can make a mapping file

**Comment by mentasm** [comment]
Tried my best with this.  Not everything had an existing CatType but matched them as well as I could:

//AddCategoryMapping("624", TorznabCatType.Console);
//AddCategoryMapping("307", TorznabCatType.ConsoleNDS);
//AddCategoryMapping("308", TorznabCatType.ConsolePSP);
AddCategoryMapping("35", TorznabCatType.ConsoleWii);
//AddCategoryMapping("309", TorznabCatType.ConsoleXbox);
AddCategoryMapping("12", TorznabCatType.ConsoleXbox360);
//AddCategoryMapping("305", TorznabCatType.ConsoleWiiwareVC);
//AddCategoryMapping("309", TorznabCatType.ConsoleXBOX360DLC);
AddCategoryMapping("38", TorznabCatType.ConsolePS3);
//AddCategoryMapping("239", TorznabCatType.ConsoleOther);
//AddCategoryMapping("245", TorznabCatType.ConsoleOther);
//AddCategoryMapping("246", TorznabCatType.ConsoleOther);
//AddCategoryMapping("626", TorznabCatType.ConsoleOther);
//AddCategoryMapping("628", TorznabCatType.ConsoleOther);
//AddCategoryMapping("630", TorznabCatType.ConsoleOther);
//AddCategoryMapping("307", TorznabCatType.Console3DS);
//AddCategoryMapping("308", TorznabCatType.ConsolePSVita);
//AddCategoryMapping("307", TorznabCatType.ConsoleWiiU);
//AddCategoryMapping("309", TorznabCatType.ConsoleXboxOne);
//AddCategoryMapping("308", TorznabCatType.ConsolePS4);
//AddCategoryMapping("631", TorznabCatType.Movies);
//AddCategoryMapping("631", TorznabCatType.MoviesForeign);
//AddCategoryMapping("455", TorznabCatType.MoviesOther);
//AddCategoryMapping("633", TorznabCatType.MoviesOther);
AddCategoryMapping("19", TorznabCatType.MoviesSD);
AddCategoryMapping("41", TorznabCatType.MoviesHD);
AddCategoryMapping("17", TorznabCatType.Movies3D);
AddCategoryMapping("80", TorznabCatType.MoviesBluRay);
AddCategoryMapping("20", TorznabCatType.MoviesDVD);
//AddCategoryMapping("631", TorznabCatType.MoviesWEBDL);
AddCategoryMapping("6", TorznabCatType.Audio);
//AddCategoryMapping("623", TorznabCatType.AudioMP3);
AddCategoryMapping("29", TorznabCatType.AudioVideo);
//AddCategoryMapping("402", TorznabCatType.AudioVideo);
AddCategoryMapping("5", TorznabCatType.AudioAudiobook);
//AddCategoryMapping("1", TorznabCatType.AudioLossless);
//AddCategoryMapping("403", TorznabCatType.AudioOther);
//AddCategoryMapping("642", TorznabCatType.AudioOther);
//AddCategoryMapping("1", TorznabCatType.AudioForeign);
//AddCategoryMapping("233", TorznabCatType.PC);
//AddCategoryMapping("236", TorznabCatType.PC);
//AddCategoryMapping("1", TorznabCatType.PC0day);
AddCategoryMapping("1", TorznabCatType.PCISO);
//AddCategoryMapping("235", TorznabCatType.PCMac);
//AddCategoryMapping("627", TorznabCatType.PCPhoneOther);
AddCategoryMapping("21", TorznabCatType.PCGames);
AddCategoryMapping("4", TorznabCatType.PCGames);
//AddCategoryMapping("625", TorznabCatType.PCPhoneIOS);
//AddCategoryMapping("625", TorznabCatType.PCPhoneAndroid);
AddCategoryMapping("45", TorznabCatType.TV);
//AddCategoryMapping("433", TorznabCatType.TV);
//AddCategoryMapping("639", TorznabCatType.TVWEBDL);
//AddCategoryMapping("433", TorznabCatType.TVWEBDL);
//AddCategoryMapping("639", TorznabCatType.TVFOREIGN);
//AddCategoryMapping("433", TorznabCatType.TVFOREIGN);
AddCategoryMapping("7", TorznabCatType.TVSD);
AddCategoryMapping("49", TorznabCatType.TVSD);
AddCategoryMapping("42", TorznabCatType.TVHD);
//AddCategoryMapping("433", TorznabCatType.TVHD);
//AddCategoryMapping("635", TorznabCatType.TVOTHER);
//AddCategoryMapping("636", TorznabCatType.TVSport);
AddCategoryMapping("23", TorznabCatType.TVAnime);
//AddCategoryMapping("634", TorznabCatType.TVDocumentary);
AddCategoryMapping("9", TorznabCatType.XXX);
//AddCategoryMapping("1", TorznabCatType.XXXDVD);
//AddCategoryMapping("1", TorznabCatType.XXXWMV);
//AddCategoryMapping("1", TorznabCatType.XXXXviD);
//AddCategoryMapping("1", TorznabCatType.XXXx264);
//AddCategoryMapping("1", TorznabCatType.XXXOther);
//AddCategoryMapping("1", TorznabCatType.XXXImageset);
//AddCategoryMapping("1", TorznabCatType.XXXPacks);
//AddCategoryMapping("340", TorznabCatType.Other);
//AddCategoryMapping("342", TorznabCatType.Other);
//AddCategoryMapping("344", TorznabCatType.Other);
//AddCategoryMapping("391", TorznabCatType.Other);
//AddCategoryMapping("392", TorznabCatType.Other);
//AddCategoryMapping("393", TorznabCatType.Other);
//AddCategoryMapping("394", TorznabCatType.Other);
//AddCategoryMapping("234", TorznabCatType.Other);
//AddCategoryMapping("638", TorznabCatType.Other);
//AddCategoryMapping("629", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.OtherMisc);
//AddCategoryMapping("1", TorznabCatType.OtherHashed);
//AddCategoryMapping("408", TorznabCatType.Books);
AddCategoryMapping("24", TorznabCatType.BooksEbook);
//AddCategoryMapping("406", TorznabCatType.BooksComics);
//AddCategoryMapping("407", TorznabCatType.BooksComics);
//AddCategoryMapping("409", TorznabCatType.BooksComics);
//AddCategoryMapping("410", TorznabCatType.BooksMagazines);
//AddCategoryMapping("1", TorznabCatType.BooksTechnical);
//AddCategoryMapping("1", TorznabCatType.BooksOther);
//AddCategoryMapping("1", TorznabCatType.BooksForeign);


Let me know if I've not got it right or you need something different

**Comment by trianglepixel** [comment]
i have a bitsoup account and can code....will look into trying to create this indexer in my spare time :)

**Comment by twistedroutes** [comment]
I am happy to have a crack if someone wants to throw the invite my way.

**Comment by mentasm** [comment]
Couldn't work out how to prinate message you on this site.  Can send invite your way if trianglepixel isn't doing it

**Comment by twistedroutes** [comment]
Updated my profile with an email address if you wish.

**Comment by mentasm** [comment]
Will try and send this evening.  bitsoup is blocked at my work.  Please remember that the invitees reflect on the inviter.

**Comment by mentasm** [comment]
I don't think the site likes the + in your email address. Says it doesn't look valid.

**Comment by twistedroutes** [comment]
All good.  You can just drop the "+" and everything after it, and it goes to the same address.

**Comment by timtimar** [comment]
Would love to see bitsoup on Jackett.  Can I help in anyway?

**Comment by twistedroutes** [comment]
OK.  Done.  I'll commit to my fork and then submit it to the main project.

**Comment by twistedroutes** [comment]
I've used the bitsoup.me URL, but I have noticed that there is also bitsoup.org and soupbit.me - maybe time to implement a drop down config box to select the multiple URLs.  Similar thing has happened with other trackers having multiple URIs (some for specific countries).

![image](https://cloud.githubusercontent.com/assets/2973320/11947130/be44e7dc-a830-11e5-86a5-8524d432a9ab.png)

**Comment by mentasm** [comment]
let me know when i should be able to grab a new compiled version

**Comment by twistedroutes** [comment]
That I don't have control over.  It's up to someone with write access to accept and merge my changes.

As BitSoup (as do a few others) have multiple URLs, I've also been toying with a modification to the config page, such as the below.  I wonder how to 'chat' with the 'team jacket' to determine if this is the direction they want to go in (or implement another item type for a drop-down list for example, to choose URLs).

![image](https://cloud.githubusercontent.com/assets/2973320/11969822/16e9073e-a8ee-11e5-87d9-74b79261a582.png)

**Comment by mentasm** [comment]
Hi
Got the latest build and have installed and setup bitsoup as an indexer.  Have run into an issue when using it via sonarr.  Get the following when it is enabled as a search indexer:

Episode search failed: The string can't be left empty, null or consist of only whitespaces.
Parameter name: key: The string can't be left empty, null or consist of only whitespaces.
Parameter name: key

If I disable this indexer eerything works ok.  Can search bitsoup fine from the jackett web ui however so its not completely broken.  Seems to be something slightly off with comms between sonarr and jackett

Any ideas?

**Comment by twistedroutes** [comment]
Yes, there was a fix applied for this but it was with some other updates that were not accepted.  it is the releases GUID field not being filled in.  I need to add the fix back separately, which I will try to do this evening.

**Comment by twistedroutes** [comment]
just pushed the update...1 liner

**Comment by mentasm** [comment]
updated to release .95.0 today and it is working beautifuly.  Finally happy with my whole sonarr/jackett setup
