### ISSUE TITLE
Il corsaro nero [Problem .torrent download]

### ISSUE THREAD

**Issue by gandalf764** [Jackett/Jackett#4402]
![2019-01-04 20_23_17-jackett](https://user-images.githubusercontent.com/41706025/50706734-f3841280-105e-11e9-9b37-504e7de81eda.png)

"Add download link via itorrents.org" not work...
can you add other mode to download a torrent from corsaro nero? magnet or idope or torrage?
thanx

**Comment by garfield69** [comment]
@kaso17  ilcorsaronero only generates a torznab download link if the .itorrent.org checkbox is ticked.
the magnet link is always generated, but is this link a torznab attribute? if not, then that might explain why radarr wont pick it up. Am I right?

**Comment by kaso17** [comment]
Disable "Add download link via itorrents.org", it's unreliable.
@garfield69 if no download link is available the magnet link will be used instead.
radarr/sonarr should be able to handle it.

**Comment by gandalf764** [comment]
I tried to remove the check, but unfortunately the downloads via radarr to the "corsaro nero" are not sent to my client download (rutorrent).
If I manually glue the magnet link on utorrent it works, but it does not automatically.

**Comment by kaso17** [comment]
then please check the radarr/rutorrent logs.
