### ISSUE TITLE
[BeyondHD] Missing search results

### ISSUE THREAD

**Issue by jusher00** [Jackett/Jackett#4406]
I noticed that occasionally results were missing when searching the BHD tracker. To reproduce search "Allegiant". Jackett finds three, the site finds four releases. The last release is missing in Jackett. Looking at the source code of the website, I see that this specific release has a class of `highlight` instead of the usual `browse_color`, which Jackett is looking for and is thus omitting this release. Can anybody confirm this behavior or it somehow user specific?

**Comment by kaso17** [comment]
thank you for debugging, fixed via 7b2657870a58330f5a8823a328ea43c9d05016a6
