### ISSUE TITLE
[hd4free] Login Failed while trying to enter cookie manually

### ISSUE THREAD

**Issue by laoma84** [Jackett/Jackett#4407]
Hello,

I am having problem adding the cookie header for hd4free. i followed the instructions as described in entering a cookie manually but it doesn't seem to work.

I also have the most recent update of jackett. Any information on how to go about fixing this will be appreciated

**Comment by Boxer1990** [comment]
Not to hijack your thread but how did you manage to get the cookies?

Once i click that website it gives no explanation how to get to those steps - just a picture.

I'm on Firefox btw

**Comment by laoma84** [comment]
On the picture, on the left side, there are instructions on how to go about it based on what browser you are using

**Comment by Boxer1990** [comment]
https://raw.githubusercontent.com/Jackett/Jackett/master/.github/cookies-firefox.png

This is the image I see - but I find no instructions and on hd4free tracker can't seem to find the cookie-id once I get close to having similar panels up as in picture.

**Comment by Boxer1990** [comment]
Thanks for your help - I managed to do it but through incognito mode where the website forgot that I accepted computer cookies - not sure if it helps but give it a go.

**Comment by laoma84** [comment]
what do you mean by incognito mode ? How do you go about doing that

**Comment by controlol** [comment]
I managed to get cookies via firefox, on chrome they didn't work for me. But it just resets my cookies for some reasen, just entered them about 4 hours ago and they are reset again...

**Comment by HDVinnie** [comment]
Which cookie are you using?

**Comment by HDVinnie** [comment]
use the remember me option on login page and then use the remember_me cookie to avoid expire.
