### ISSUE TITLE
torrentdownloads.me and 1337x.to indexers failing

### ISSUE THREAD

**Issue by mmatthers** [Jackett/Jackett#4416]
Both 1337x.to and torrentdownloads.me have SSL issues when testing.  Certificates installed to the latest versions also.

An error occured while testing this indexer
Exception (1337x): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /build/mono-5.18.0.225/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request

An error occured while testing this indexer
Exception (torrentdownloads): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /build/mono-5.18.0.225/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request

**Jackett version**:   0.10.579.0
**Mono version**: 5.18.0.225

**Comment by kaso17** [comment]
if other trackers are working most likely your ISP is blocking them.

**Comment by mmatthers** [comment]
Thanks kaso17.  Had a DNS leak on the server.  All working now.  Cheers
