### ISSUE TITLE
error when downloading

### ISSUE THREAD

**Issue by broxamson** [Jackett/Jackett#4420]
Downloading torrent file for episode 'Schitts Creek S05E01 1080p WEBRip x264-TBS' failed since it no longer exists (http://127.0.0.1:9117/dl/torrentday/?jackett_apikey=(removed)&path=Q2ZESjhHa2k2RzRiWENWTG5YV3VhVFZ1M0poOFU1d0lSa2JlX2dVYlk2aGhNajFodUMxQ0dGal81U280anpuRExUSW1ZNmpMdkZ2bjZseGFfZmVTbDk4eUJ1RzdKSzFBNG9EY1Z2TDIxa3VYdmxnMlpDcFlYVmRvemlkWm16MXhma2oxcWloNFhEODhvc29PRndXWjVKQ2U0RWtjamNmb1V0cXE1cXdfZnZyMHlac0Q4V0tKbUxUbkRmSTR1QXpnSHV6MWtB&file=Schitts+Creek+S05E01+1080p+WEBRip+x264-TBS): HTTP request failed: [404:NotFound] [GET] at [http://127.0.0.1:9117/dl/torrentday/?jackett_apikey=c07n3y716ids9rgl16fk9entqq5gltwv&path=Q2ZESjhHa2k2RzRiWENWTG5YV3VhVFZ1M0poOFU1d0lSa2JlX2dVYlk2aGhNajFodUMxQ0dGal81U280anpuRExUSW1ZNmpMdkZ2bjZseGFfZmVTbDk4eUJ1RzdKSzFBNG9EY1Z2TDIxa3VYdmxnMlpDcFlYVmRvemlkWm16MXhma2oxcWloNFhEODhvc29PRndXWjVKQ2U0RWtjamNmb1V0cXE1cXdfZnZyMHlac0Q4V0tKbUxUbkRmSTR1QXpnSHV6MWtB&file=Schitts+Creek+S05E01+1080p+WEBRip+x264-TBS]
--

**Comment by chrisric** [comment]
Same issue here. As above, direct torrent download works via a browser but not through Jackett manually or automatically. Tried many different TD URL's in Jackett config.

QNAP: TS-453A, FW: v4.3.4.0516
Jackett: v0.10.325.0
Mono: Tried v5.11.0 (QNAP QPKG)

**Comment by G4mago** [comment]
I have the same issue as mentioed above. Worked fine yesterday but stopped working within the last 24h

 Jackett Version 0.10.589.0

**Comment by baggar11** [comment]
Confirmed here too.

**Comment by filipecmartins** [comment]
Same issue too

**Comment by kaso17** [comment]
fixed via 5af3eaa926712ea716614e5383cdb1c04387bea2
