### ISSUE TITLE
Cannot add IPtorrents to Jackett

### ISSUE THREAD

**Issue by ashmores** [Jackett/Jackett#4424]
I'm trying to add IPtorrents to Jackett.

I click on the spanner icon and the page returns to the jackett main screen and I then get a jackett server error.

I use a proxy to gain access to IPtorrents as my isp blocks that URL.

A curl reveals an issue with the SSL

scott@Jackett:~$ curl -v https://iptorrents.com/
* Hostname was NOT found in DNS cache
*   Trying 104.23.202.30...
* Connected to iptorrents.com (104.23.202.30) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to iptorrents.com:443
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to iptorrents.com:443

Mono Version

scott@Jackett:~$ mono --version
Mono JIT compiler version 5.18.0.225 (tarball Wed Jan  2 21:25:01 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

Jackett Version 0.10.589.0

The debug is pasted below

When | Level | Message
-- | -- | --
Jan 09, 2019 12:18:12 PM | Error | System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: SecureChannelFailure (Unable to read data from the transport connection: Connection reset by peer.) ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer   at System.Net.Sockets.Socket.EndReceive (System.IAsyncResult asyncResult) [0x00012] in <eeec8e88b1fc462e84ade7bf334d0c97>:0    at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x00057] in <eeec8e88b1fc462e84ade7bf334d0c97>:0     --- End of inner exception stack trace ---   at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x0009b] in <eeec8e88b1fc462e84ade7bf334d0c97>:0    at System.IO.Stream+<>c.<BeginEndReadAsync>b__43_1 (System.IO.Stream stream, System.IAsyncResult asyncResult) [0x00000] in <7b0d87324cab49bf96eac679025e77d1>:0    at System.Threading.Tasks.TaskFactory`1+FromAsyncTrimPromise`1[TResult,TInstance].Complete (TInstance thisRef, System.Func`3[T1,T2,TResult] endMethod, System.IAsyncResult asyncResult, System.Boolean requiresSynchronization) [0x00000] in <7b0d87324cab49bf96eac679025e77d1>:0  --- End of stack trace from previous location where exception was thrown ---    at Mono.Net.Security.MobileAuthenticatedStream.InnerRead (System.Boolean sync, System.Int32 requestedSize, System.Threading.CancellationToken cancellationToken) [0x00104] in <eeec8e88b1fc462e84ade7bf334d0c97>:0    at Mono.Net.Security.AsyncProtocolRequest.InnerRead (System.Threading.CancellationToken cancellationToken) [0x000ac] in <eeec8e88b1fc462e84ade7bf334d0c97>:0    at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x00093] in <eeec8e88b1fc462e84ade7bf334d0c97>:0    at Mono.Net.Security.AsyncProtocolRequest.StartOperation (System.Threading.CancellationToken cancellationToken) [0x0008b] in <eeec8e88b1fc462e84ade7bf334d0c97>:0    at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x00252] in <eeec8e88b1fc462e84ade7bf334d0c97>:0    at Mono.Net.Security.MonoTlsStream.CreateStream (System.Net.WebConnectionTunnel tunnel, System.Threading.CancellationToken cancellationToken) [0x00126] in <eeec8e88b1fc462e84ade7bf334d0c97>:0    at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x001ba] in <eeec8e88b1fc462e84ade7bf334d0c97>:0     --- End of inner exception stack trace ---   at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x0021a] in <eeec8e88b1fc462e84ade7bf334d0c97>:0    at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x00141] in <eeec8e88b1fc462e84ade7bf334d0c97>:0    at System.Net.WebOperation.Run () [0x0009a] in <eeec8e88b1fc462e84ade7bf334d0c97>:0    at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x00094] in <eeec8e88b1fc462e84ade7bf334d0c97>:0    at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <eeec8e88b1fc462e84ade7bf334d0c97>:0    at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in <eeec8e88b1fc462e84ade7bf334d0c97>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <7b0d87324cab49bf96eac679025e77d1>:0  --- End of stack trace from previous location where exception was thrown ---    at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x0041d] in <2d05f0f19f034ad09a31288b810590d5>:0     --- End of inner exception stack trace ---   at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00478] in <2d05f0f19f034ad09a31288b810590d5>:0    at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x000ca] in <2d05f0f19f034ad09a31288b810590d5>:0    at CloudFlareUtilities.ClearanceHandler.PassClearance (System.Net.Http.HttpResponseMessage response, System.Threading.CancellationToken cancellationToken) [0x0023c] in <d0213015414e4bf286b46bc1ee77bd72>:0    at CloudFlareUtilities.ClearanceHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00193] in <d0213015414e4bf286b46bc1ee77bd72>:0    at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x000ca] in <2d05f0f19f034ad09a31288b810590d5>:0    at Jackett.Common.Utils.Clients.HttpWebClient.Run (Jackett.Common.Utils.Clients.WebRequest webRequest) [0x00456] in <64351501325343a3bbac70d7261d86da>:0    at Jackett.Common.Utils.Clients.WebClient.GetString (Jackett.Common.Utils.Clients.WebRequest request) [0x0010b] in <64351501325343a3bbac70d7261d86da>:0    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies (System.String url, System.String cookieOverride, System.String referer, System.Collections.Generic.Dictionary`2[TKey,TValue] headers) [0x000cb] in <64351501325343a3bbac70d7261d86da>:0    at Jackett.Common.Indexers.IPTorrents.GetConfigurationForSetup () [0x00075] in <64351501325343a3bbac70d7261d86da>:0    at Jackett.Server.Controllers.IndexerApiController.Config () [0x0006a] in <7d92105df8cd41f9813933e9ef8c264a>:0    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00115] in <dd7bbb1eb6cb4178a82cd5136b2606b8>:0    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <7d92105df8cd41f9813933e9ef8c264a>:0

**Comment by kaso17** [comment]
see #1473 for a workaround

**Comment by ashmores** [comment]
Hi

I've followed the instructions on  #1473

I'm running jackett on ubuntu 14.04.5 LTS

I can't find where to place the iptorrents.json file.

My apologies if I'm missing something.

Thanks

**Comment by kaso17** [comment]
~/.config/Jackett/Indexers/

**Comment by ashmores** [comment]
Hi just as an update.

I'm still unable to click on the edit icon for iptorrents but I got it working by doing the following

I copied an existing .json and edited it to use the correct URL and deleted the remaining options. 

Then from #2683 I followed those instructions to add the cookie string

my final .json file looks like this and is working but I'm still unable to edit it through Jackett.

[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://iptorrents.com/"
  },
  {
    "id": "username",
    "type": "inputstring",
    "name": "Username",
    "value": null
  },
  {
    "id": "password",
    "type": "inputstring",
    "name": "Password",
    "value": ""
  },
    "id": "recaptcha",
    "type": "recaptcha",
    "name": "Recaptcha",
    "sitekey": null,
    "version": "2"
  },
  {
    "id": "",
    "type": "displayinfo",
    "name": "",
    "value": null
  },   
  {
    "id": "cookieheader",
    "type": "hiddendata",
    "name": "CookieHeader",
    "value": "__cfduid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; uid=xxxxxx$; pass=xxxxxxxxxxxxxxxxxxxxxxxxxxx"
  },
  {
    "id": "lasterror",
    "type": "hiddendata",
    "name": "LastError",
    "value": null
  }
]

Hope this is useful to anyone who has the same issue.  Thanks kaso17 for all your help 👍
