### ISSUE TITLE
[elitetracker] Exception (elitetracker): La référence d'objet n'est pas définie à une instance d'un objet.: Parse error (Config)

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#4431]
The tracker has been down since december. Now it is accessible, we can log into the tracker, but we can't login with Jackett.

**Jackett version**:  0.10.599.0 on Windows 10

Thanks for all ! happy new year !

**Comment by WSHaRK93** [comment]
I second that :)

**Comment by SckyzO** [comment]
The Same : 
An error occured while testing this indexer
Exception (elitetracker): Object reference not set to an instance of an object: Parse error

**Comment by Echupk** [comment]
Same!

**Comment by aureliensauv** [comment]
I've created a pull request for fix this error.
I hope it will be included in the next release.

**Comment by pipopop** [comment]
Great thanks to you @aureliensauv !

**Comment by kaso17** [comment]
fixed via #4444

**Comment by SckyzO** [comment]
Je sais pas pour vous mais moi ca ne fonctionne toujours pas. ?!

**Comment by aureliensauv** [comment]
@SckyzO you're right.
EliteTracker has revert a modification on his tooltip.
I've created a new pull request.

**Comment by pipopop** [comment]
Actualy it worked great just after the new release. But know it didn't work. Thank you @aureliensauv for your work.
