### ISSUE TITLE
[greekteam] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by tsikup** [Jackett/Jackett#4432]
Jackett (0.10.599.0) not working with greek-team tracker

It was working a few days back that I last checked.

**Comment by kaso17** [comment]
probably related to #4408.

Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by tsikup** [comment]
Sorry for the missing logs. It was related to #4408 and the proposed solution did work. Thank you!!
