### ISSUE TITLE
[torrentz2] Exception (torrentz2): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /spksrc/spk/mono/work-x64-6.1/mono-5.8.0.108/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by ward0** [Jackett/Jackett#4433]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.603.0
**Mono version** (if not using Windows):  5.8.0.108-11(synology)

-------------------------------An error occured while testing this indexer
Exception (torrentz2): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /spksrc/spk/mono/work-x64-6.1/mono-5.8.0.108/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request

trackers with this error:

1337x
kickasstorrent
Torrentz2

what to do next?

**Comment by mnervik** [comment]
Yeah, I have the same issue.I get this error on all my trackers

**Comment by actionless** [comment]
the same issue? https://github.com/Jackett/Jackett/issues/4441

**Comment by ward0** [comment]
@actionless check my comment in #4441  pls

**Comment by actionless** [comment]
sorry, but i'm not this app's dev

**Comment by ward0** [comment]
found the fix:

Had the same issue myself on Synology. Ran these two commands and afterwards restarted Jackett from DSM, didn't have to reboot the whole NAS:

wget https://curl.haxx.se/ca/cacert.pem
sudo /volume1/@appstore/mono/bin/cert-sync ./cacert.pem
