### ISSUE TITLE
[shareisland] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by gandalf764** [Jackett/Jackett#4435]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by gandalf764** [comment]
![2019-01-10 22_19_40-jackett](https://user-images.githubusercontent.com/41706025/50997898-237f5a00-1526-11e9-8b14-932cc0c6ee43.png)

**Comment by gandalf764** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/2750594/log.txt)

**Comment by kaso17** [comment]
affected only users which see the uploader column (depending on rank?)
should be fixed via 3294bbcea312dfcfc1cdfd1a56650cbbb9dcf696
