### ISSUE TITLE
Page not available when trying to download a release from HD-only

### ISSUE THREAD

**Issue by hbooo** [Jackett/Jackett#4437]
Hello, 

I have a redirection to a not known page when I try to download a release from hd-only.

Test is ok, search also but if I click download i'm redirected to 
This  page can’t be found
http://mydns:9117/dl/hdonly/?jackett_apikey=myjackettapikey&path=apathwithsomelettersandnumbers
4&file=La+Fureur+du+dragon+%5B1972%5D+%5BFilm%5D+HEVC+_+2160p+_+Blu-ray+Remux+4K
Error 404.

Website works and if I click on a release title i'm correctly redirected to the website.

This happens if you check 
![image](https://user-images.githubusercontent.com/242125/51019156-358ae800-157a-11e9-95ef-07615ecc3e83.png)
in the configuration, as the tracker is no ratio this option should be removed

**Jackett version**:  Jackett Version 0.10.599.0 from Unraid
**Mono version** (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
disabled tokens via 4a03e52cb489eb0607e44583c3ec65c7943f587c

Please provide a full log.
