### ISSUE TITLE
[Hush Tracker] can't add tracker or access to login properties

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#4438]
Hello,
Yesterday, the tracker worked correctly.
 but today, I try to configure login and password : Jackett said "Request to Jackett server failed"
So I delete the tracker, try to add it and Jackett said again : "Request to Jackett server failed".
Thanks,

**Jackett version**: 0.10.599.0
On Windows 10

**Comment by Celedhrim** [comment]
https://team-hush.org/

502 Bad Gateway

Tracker seems down

**Comment by pipopop** [comment]
Really sorry :/
