### ISSUE TITLE
[rarbg] An error occurred while sending the request: Error: TrustFailure (A call to SSPI failed, see inner exception.) (Config)

### ISSUE THREAD

**Issue by actionless** [Jackett/Jackett#4441]
**Jackett version**:  0.10.611-1
**Mono version** (if not using Windows):  5.16.0.220-1

-------------------------------

Site Link: https://rarbg.to/
URL: https://torrentapi.org/

it works with HTTP but not HTTPS (in browser both works well without any certificate warnings or so)

also the same problem is reproducible with few more trackers

**Comment by kaso17** [comment]
This is often caused by missing CA certificates.
Try reimporting the certificates:
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`

**Comment by actionless** [comment]
Thanks a lot!
it helped

i recommend adding a this hint to Troubleshooting section (https://github.com/Jackett/Jackett#troubleshooting) since some of the users could be not familiar with such .NET infra caveats

**Comment by kaso17** [comment]
it's already there but with an older error message. Updated it via 0288bd4ad8f4c69be2b8674c4edfe409dcfd753c

**Comment by ward0** [comment]
Not possible to do from within Jackett itself? The CA update? Jackett should be able to check if CA cert is expired or not and replace when needed...

**Comment by ward0** [comment]
error in synology:

Ward@SERVER:/$ wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin
-sh: cert-sync: command not found
--2019-01-14 19:51:22--  https://curl.haxx.se/ca/cacert.pem
Resolving curl.haxx.se... 2a04:4e42:9::561, 151.101.38.49
Connecting to curl.haxx.se|2a04:4e42:9::561|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 207949 (203K) [application/x-pem-file]
Saving to: 'STDOUT'

-                     0%[                    ]       0  --.-KB/s    in 0s


Cannot write to '-' (Success).
Ward@SERVER:/$

**Comment by kaso17** [comment]
Jackett can't update the system certificates (needs root permissions).
See #4433 for a synology solution.
