### ISSUE TITLE
Monova

### ISSUE THREAD

**Issue by LucasGorgal** [Jackett/Jackett#4447]
Hello.
I think monova.to is a good torrent tracker and should be added to Jackett.
Many thanks!

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by garfield69** [comment]
https://monova.org/ returning cloudflare 504 Gateway time-out
just me, or is the site broken, gone or moved to a new domain?

**Comment by garfield69** [comment]
back online.

**Comment by ilike2burnthing** [comment]
https://monova.org/ - Error 504 - Gateway time-out

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://monova.org/
![maintenance](https://user-images.githubusercontent.com/59480337/92984247-cc6f1c80-f4a0-11ea-9590-cfd88abe2981.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://monova.org/
> ![maintenance](https://user-images.githubusercontent.com/59480337/92984247-cc6f1c80-f4a0-11ea-9590-cfd88abe2981.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://monova.org/ - Error 502 - Bad gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://monova.org/ - Error 502 - Bad gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://monova.org/ - Error 502 - Bad gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://monova.org/ - 400 Bad Request
