### ISSUE TITLE
[superbits] Wrong Captcha. (Config)

### ISSUE THREAD

**Issue by Arcaniz86** [Jackett/Jackett#4450]
No captcha-line available in Jackett when trying to add indexer Superbits.org to Jackett.
Please add this to Jackett when possible <3

BR
Arcaniz

**Comment by kaso17** [comment]
changed to cookie auth via d8d8030644540c400e94018ae619e03d9bb5fe2d

**Comment by veeriz** [comment]
the cookie field is not visible for me, i´ve tested to configure superbits on 0.10.611, 0.10.632, 0.10.639 all versions give me username and password only, and if i input username & password it throws an error

**Comment by kaso17** [comment]
missed one, fixed via a76becef3acea6fd125473ed694c65c307c491f3

**Comment by veeriz** [comment]
Thanks so much for your work on this awesome app!
Will this change be committed into a windows build soon?

**Comment by kaso17** [comment]
released via v0.10.641
