### ISSUE TITLE
Jackett start then exit. error code = '22'

### ISSUE THREAD

**Issue by xenofree** [Jackett/Jackett#4451]
Hi,

**OS**: FreeBSD 12.0-RELEASE-p2
**Jackett version**:  jackett-0.10.589
**Mono version** (if not using Windows):  Mono JIT compiler version 5.10.1.57

-------------------------------

When I start Jackett, it exit after a few seconds whith error code 22.
The error seems to appear after upgrade in Freebsd 12.0.
Log in attachment.

[jackett.log](https://github.com/Jackett/Jackett/files/2753433/jackett.log)

**Comment by danielpo** [comment]
Same issue here with FreeBSD, worked fine with 11.2

**Comment by kaso17** [comment]
it's crashig during the webserver initialization.
I assume this is a mono/freebsd specific issue.
Try a newer mono version.

**Comment by mvanbaak** [comment]
This is an issue with the mono port on FreeBSD 12+
More info can be found here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198727
