### ISSUE TITLE
Torrentday

### ISSUE THREAD

**Issue by niftienev** [Jackett/Jackett#4452]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by niftienev** [comment]
Torrentday has changed to "tday.lov" due to UK/Aussie blocking.

Jacket no longer works for me. Help please

Error:

![capture](https://user-images.githubusercontent.com/35582574/51093542-62e0cb80-17f0-11e9-92bd-c9ef840d5746.JPG)

**Comment by MrAlfabet** [comment]
Same issue here, tried setting the cookies again, no dice.

**Comment by niftienev** [comment]
No, Cookies renew did not work for me either.

**Comment by kaso17** [comment]
changed the default via 7df5a64a8b8418f44138fc904de4f0d4def4ac0f.
remove and readd the idexer once there's a new release.

**Comment by MrAlfabet** [comment]
Still not working after removing and re-adding the indexer

**Comment by niftienev** [comment]
I removed Jackett and reinstalled the latest  version and it is working fine with tday.like.
I had to reconfigure remove the indexer in Sonarr and reinstall with the Torrentday (tday.like) settings including the API.
