### ISSUE TITLE
[hush] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#4454]
Hello,
This Jacket Tracker worked well until the tracker fall down.
Now, the tracker is online, but it doesn't work in Jackett.

Jackett Version 0.10.611.0
On Windows 10.

Great thanks for all !

**Comment by kaso17** [comment]
@kcgthb can you have a look?

**Comment by kcgthb** [comment]
Yeah, I'm not sure what changed... :\

**Comment by garfield69** [comment]
@kcgthb  If you send an invite to garfieldsixtynine @ gmail.com I can have a look at the issue.

**Comment by garfield69** [comment]
is this still a problem?

**Comment by pipopop** [comment]
No sorry. I tested it right now. It works great. Thank you !
