### ISSUE TITLE
BitsPiracy

### ISSUE THREAD

**Issue by alexxandeer** [Jackett/Jackett#4459]
Config file to add BitsPiracy to the PrivateTracker list.

https://bitspiracy.org/jacket/Bitspiracy.cs

**Comment by kaso17** [comment]
added via 86169a41c0e0de5d582279a86b3baef98789b5b4
thank you

**Comment by alexxandeer** [comment]
I did make a change in the source, please update

**Comment by kaso17** [comment]
done, if you've more changes please creat a corresponding pull request.
You can use the github edit feature (pen icon on the top right corner at https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/Bitspiracy.cs)

**Comment by garfield69** [comment]
https://bitspiracy.org/ returning ERR_CONNECTION_REFUSED
just me, or is site broken, gone or moved to new domain?

**Comment by garfield69** [comment]
https://bitspiracy.org/ returning ERR_CONNECTION_TIMED_OUT
anyone have any news?
