### ISSUE TITLE
xspeeds fix not working with sonarr with version 0.10.622.0

### ISSUE THREAD

**Issue by rvwoens** [Jackett/Jackett#4461]
Just updated to 0.10.622.0 for the xspeed fix, but this results in a new error when trying to use it with sonarr :

<error code="900" description="Jackett.Common.IndexerException: Exception (xspeeds): Minimum search length is 3 ---> System.Exception: Parse error ---> System.Exception: Minimum search length is 3
 ---

**Comment by kaso17** [comment]
fixed via 35b8f726fb5a3c0cca98d880a7513406cb203a0c
