### ISSUE TITLE
Iptorrent no longer working

### ISSUE THREAD

**Issue by Zeusy123** [Jackett/Jackett#4470]
Been using jacket with iptorrent since early days of jackett.
Using the hack of entering the cookie manually
, as in 👍 
    "id": "cookieheader",
    "type": "hiddendata",
    "name": "CookieHeader",
    "value": "__cfduid=d66c2876675765765ff190615e81547649190; uid=7655656; pass=78687687686868686868; hideCats=0; hideTop=0"

(I've edited my own details)

But sadly no matter what I try I cant get kacett to log into IPtorrents and work anymore.

**Comment by kaso17** [comment]
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by Zeusy123** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/2764591/log.txt)
![iptorrentloginissues](https://user-images.githubusercontent.com/24862324/51256712-4dad9d80-19a6-11e9-8a6a-e09f29b10995.png)

no istead of seeing the username & password box I just see a cookie box, ive attached image.

shall I also upload mt private iptorrent.json, with my details edited??

**Comment by kaso17** [comment]
In this case you've to supply the cookie (jackett can't solve the recaptcha during login) as explained in the config dialog.

**Comment by Zeusy123** [comment]
Hi Kaso17, firstly thanks for the help:)

I have logged out and loged back into using chrome and copied the full cookie which is this format:

PHPSESSID=t9612764565465465465; __cfduid=d0a71107657657576576576547649023; uid=10765657; pass=6756576576576576576; hideCats=0; hideTop=0

So i have pasted __cfduid=d0a71107657657576576576547649023; into the "full cookie Header" in jacket and click "OK" but throws error: "Your cookie did not work: Your cookie did not work"

Feeling so stupid I cant figure this out:-/

**Comment by kaso17** [comment]
you've to use the complete cookie, not just the cfduid

**Comment by Zeusy123** [comment]
OMG! - kaso17 thankyou:)
