### ISSUE TITLE
Xspeeds no longer working returning error

### ISSUE THREAD

**Issue by xgenosis** [Jackett/Jackett#4472]
Hi All,

Since Monday i have been having issues with Xspeeds with jackett and sonaar. its producing the following error from the logs. I have updated to the latest version of jackett. Not sure why this is occurring all of sudden but any help would be appreciated. i have tried to remove the .json files manually and recreate but still the same issue. the test seems to pass but thats its
 Jackett Version 0.10.622.0 

Jan 17, 2019 09:35:47 AM | Error | Jackett.Common.IndexerException: Exception (xspeeds): Minimum search length is 3 ---> System.Exception: Parse error ---> System.Exception: Minimum search length is 3    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex)    at Jackett.Common.Indexers.XSpeeds.<PerformQuery>d__20.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext()    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Indexers.BaseWebIndexer.<ResultsForQuery>d__25.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext()
-- | -- | --
Jan 17, 2019 09:35:47 AM | Error | Error on 20190117093547 for XSpeeds.txtSystem.Exception: Minimum search length is 3

-------------------------------

**Comment by Seeveen** [comment]
same problem here with last jackett update, now i cant added the indexer in sonarr/radarr

Jackett logs:

Jackett.Common.IndexerException: Exception (xspeeds): Minimum search length is 3 ---> System.Exception: Parse error ---> System.Exception: Minimum search length is 3    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex)    at Jackett.Common.Indexers.XSpeeds.<PerformQuery>d__20.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext()    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Indexers.BaseWebIndexer.<ResultsForQuery>d__25.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext()
--
Jan 17, 2019 02:41:43 PM | Error | Error on 20190117144143 for XSpeeds.txtSystem.Exception: Minimum search length is 3


Sonarr logs

Unable to connect to indexer: Torznab error detected: Jackett.Common.IndexerException: Exception (xspeeds): Minimum search length is 3 ---> System.Exception: Parse error ---> System.Exception: Minimum search length is 3
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex)
   at Jackett.Common.Indexers.XSpeeds.<PerformQuery>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext()
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.BaseWebIndexer.<ResultsForQuery>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext()

**Comment by kaso17** [comment]
this was fixed in version >= v0.10.632
