### ISSUE TITLE
[eztv] Sonarr errors "Value cannot be null"

### ISSUE THREAD

**Issue by quekky** [Jackett/Jackett#4473]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.622.0
**Mono version** (if not using Windows):  

-------------------------------

While searching for Gifted S02E12, Sonarr have this error in the log file
"[v2.0.0.5252] System.ArgumentNullException: Value cannot be null.
Parameter name: attribute"

When I download this url, I notice that some xml have no "size" field http://ip:9117/api/v2.0/indexers/eztv/results/torznab/api?apikey=&t=search&cat=&q=Gifted&season=2&ep=12
I'm not sure is this the cause of the error

Looking at the eztv website, I can see that there's no detail of the file
![image 3](https://user-images.githubusercontent.com/3648303/51296377-f7e4fe00-1a56-11e9-9c94-f7989ae61305.png)

Perhaps Jackett can put a 0 size if the size cannot be found?

**Comment by garfield69** [comment]
yes, in the Jackett eztv indexer, the size selector is optional. so I have provided a default of 500 MB.
fix will be included in the next release.

**Comment by garfield69** [comment]
try Jackett v0.10.739
