### ISSUE TITLE
Failed update Jackett

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#4474]
Hello !
Can't update to latest version.
Current version : v0.10.632
New version : V0.10.637
Here is the log detail:
`2019-01-17 12:33:49.1679 Info New release found.  Current: v0.10.632 New: v0.10.637 
2019-01-17 12:33:49.4529 Error Failed to find asset to download! 
2019-01-17 12:33:49.7269 Error Error performing update. System.ArgumentNullException: La valeur ne peut pas être null.
Nom du paramètre : path1
   à System.IO.Path.Combine(String path1, String path2, String path3)
   à Jackett.Common.Services.UpdateService.<CheckForUpdates>d__13.MoveNext()`
On Windows 10
Great Thanks,
Pipopop

**Comment by Seeveen** [comment]
@pipopop 
same problem here, but i noticed on github on the latest release, windows version is missing, only source code is available

**Comment by pipopop** [comment]
You're right! I didn't see it.

**Comment by kaso17** [comment]
should be fixed via the v0.10.639 release
