### ISSUE TITLE
TPB Search RSS not working

### ISSUE THREAD

**Issue by Wilson2013** [Jackett/Jackett#4475]
Latest Jackett version, Windows 7 64-bit.

This has never worked since I started using Jackett a few months ago.

When I try a search RSS for The Pirate Bay it always returns the most popular results instead of the latest. Ordering problem for this site. All other Jackett RSS feeds I use are fine.

Thanks for your help!!

**Comment by Wilson2013** [comment]
Additional info - Similar to https://github.com/Jackett/Jackett/issues/4339

which was fixed via 041115f

**Comment by garfield69** [comment]
as far as I can tell, the rss feed jackett provides is from the https://thepiratebay.org/recent page.
this page does not provide any options for sorting . WYSIWYG.

**Comment by garfield69** [comment]
for TPB keyword searches, you can set the indexer to sort the results in one of three ways, default, seeders, time.
access your jackett dashboard, edit the thepiratebay indexer with the wrench icon, and set the *Order Results* pulldown to *time* and click OKAY.
![image](https://user-images.githubusercontent.com/6933240/51763094-7ec06780-2136-11e9-85a7-580008011628.png)

**Comment by Wilson2013** [comment]
That's fixed it. Can't believe I didn't notice that.

Thanks so much for your help
