### ISSUE TITLE
Jackett not searching from sonarr but can manually search

### ISSUE THREAD

**Issue by jik0n** [Jackett/Jackett#448]
Hello,

I am using sonarr with jackett and I can manually search via jackett and get sonarr to pull it from the blackhole directory to DL it automatically but sonarr will not search it via automatic search. I am using IPT and the latest version of sonarr / jackett. There do not appear to be any logs

`SeasonSearchService Season search completed. 0 reports downloaded.  1:05pm
DownloadDecisionMaker   No results found    1:05pm
NzbSearchService    Searching 1 indexers for [Family Guy : S14] 1:05pm
Database    Log database compressed 1:05pm`

When pressing search it just instantly goes to no results found, but I can manually search via jackett and it works. Any suggestions?
Edit: it looks like IPT made some changes on their end that impacted couch potato and possibly jackett as well, wondering if this is the cause? I'm assuming that could be it, I'll wait for a response though

**Comment by flightlevel** [comment]
Are you searching for more than 1 epsidoe?
Judging by the logs, sonarr is trying to search for more than 1 episode eg [Family Guy : S14]
On most trackers if you search for ShowName S14 it will find:
ShowName S14
ShowName S14E01
ShowName S14E02
ShowName S14E03
etc

But try this on the IPT website and it will only find season pack
ShowName S14

**Comment by kaso17** [comment]
no response, closing
