### ISSUE TITLE
mvgroupmain Relogin required

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#4480]
Hi, just to tell you this, don't seem a big problem, because the rel was grabbed! I don't know why this kind of info, see the log:

```
Jan 18, 2019 07:47:32 AM | Info | Found 135 releases from MVGroup Main
-- | -- | --
Jan 18, 2019 07:47:29 AM | Info | CardigannIndexer (mvgroupmain): Relogin required
Jan 18, 2019 07:47:18 AM | Info | Manual search for "" on mvgroupmain with 135 results.
Jan 18, 2019 07:47:16 AM | Info | CardigannIndexer (mvgroupmain): Relogin required
```

Any idea?

**Comment by kaso17** [comment]
It usually means that the session expired. jackett will automatically re-login.
If it's happening on every search it might be worth investigating the definition to avoid unnecessary logins.

**Comment by Jorman** [comment]
@kaso17 

Happen on every sync, so every 15min for Sonarr and every 1h for Radarr

**Comment by kaso17** [comment]
Maybe @garfield69 can have a look at it.
Otherwise it shouldn't be a problem.

**Comment by Jorman** [comment]
That's not a problem, is just to let you know. All is working

Il giorno ven 18 gen 2019, 11:34 kaso17 <notifications@github.com> ha
scritto:
