### ISSUE TITLE
Feature Request: Enable HTTPS for Jackett

### ISSUE THREAD

**Issue by DrSeussFreak** [Jackett/Jackett#4484]
I would love to be able to enable https for my Jackett server.  I have it for everything else.

**Jackett version**:  0.10.641.0

**Comment by flightlevel** [comment]
Why?
Nginx or Apache or IIS or Caddy are going to do a 1,000 times better job than Jackett, are security tested and you only have to maintain one cert for all your services. Why add the extra burden to Jackett?

**Comment by DrSeussFreak** [comment]
I run NZBHydra2 and Tautulli on the same Ubuntu VM, and I have forced SSL configured.  All I need is for Jackett to allow https connections natively to make it seamless.  This needn't be an extra burden on Jackett itself.

**Comment by kaso17** [comment]
dupe #1411
