### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Got redirected to another domain. Try changing the indexer URL to http://www2.yggtorrent.gg/. Updated site link, please try again.: Parse error (Test)

### ISSUE THREAD

**Issue by SuissoNaBisso9** [Jackett/Jackett#4491]
Hi

I think the tracker just installed CloudFlare which generates a new URL when logged in. This might the issue !

**Jackett version**:  0.10.641.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
ygg had an outage: 
```
Following a failure on one of our servers that hosted Sphinx (search engine), it was no longer possible to connect and use the search engine.

We migrated Sphinx to a new machine, all features are new operational.
```
https://www2.yggtorrent.gg/ is the current domain.

**Comment by angarod** [comment]
It doesn't work. It is definitely a cloudflare issue.

**Comment by angarod** [comment]
hum you're right, works for me now. Must be a problem with my Jackett.
