### ISSUE TITLE
[feature request] multiple indexer add

### ISSUE THREAD

**Issue by ewtoombs** [Jackett/Jackett#4493]
Right now, if I want to add every public indexer to my list of indexers, I have to hit Add Indexer, then [+] for every single one. I'd like to be able to select multiple, then add them all at once. I can think of two different ways to do this:

1. Filter on "public" or some other kind of criteria, and have an "add all" button I can then hit.
2. Have a checkbox column that I can use to select multiple, then hit an "add all" button.

As a workaround, it would be cool if there were a jackett config somewhere with all of the public indexers already added that I could use as a starter. (Basically just an archive of the --DataFolder that I could point my daemon to.)

**Comment by mtemel123** [comment]
hello
u can use this method, in browser console.
```
document.querySelectorAll("button.btn.btn-success.btn-xs.indexer-add").forEach(m=>{
	m.click();
})
```

**Comment by RoloSoze** [comment]
Similar to #3274

**Comment by frenchiveruti** [comment]
I would love to see this feature too, setting all my indexers again would be such a PiTa haha

**Comment by garfield69** [comment]
v0.18.88
