### ISSUE TITLE
[Feature Request] Add Snyk Git Repo Bot That Finds Known Vulnerabilities

### ISSUE THREAD

**Issue by rebekah65** [Jackett/Jackett#4514]
I think its worth adding support for Snyk, which is a git hub bot that finds and can fix known vulnerabilities in open-source dependencies used in this repository. 

Its easy to implement and with out any coding needed, it can be set to automaticly run for every PR or build.

Also, Snyk can be set to send alerts when vulnerabilities are found, or new upgrades or patchis to fix the vulnerabilities are available.

To implement:

>  - Go to the integrations page and click “Connect to GitHub”.
>  - You need to grant Snyk additional GitHub permissions. Choose to give access to public and private repositories, or grant access to public repositories only.
>  - Next, you’ll see a list of all GitHub repos across your GitHub organisations. Select the repos you would like to test with Snyk. If you have supported manifest files at the root, or one or two directories deep, Snyk will automatically recognise and create projects for them.
>  - Click on the button at the bottom of the page “Add selected repositories to Snyk”. The selected repos appear in your projects, and will be continuously checked for vulnerabilities.
>  - Clicking “View report” on any project lets you view & fix vulnerabilities right away. You’ll be able to review the suggested remediations, and create a PR with the required upgrades or patches.

Git:
https://github.com/snyk/snyk

Documents/Wiki:
https://snyk.io/docs/github/

![snyk_test_in_pr](https://user-images.githubusercontent.com/43880872/51545583-306f4800-1e5a-11e9-80ba-fc8f0a0c1d75.png)

**Comment by ngosang** [comment]
@cadatoiva @junglebus @garfield69 what do you think?

**Comment by garfield69** [comment]
Don't know anything about this topic. 
If anyone thinks its relevant to Jackett then by all means feel free to implement.

**Comment by junglebus** [comment]
Not fussed either way, sometimes these things can be helpful and others just a nuisance

**Comment by cadatoiva** [comment]
We use several NuGet packages, which I assume is what this function is meant to find vulnerabilities in. It wouldn't hurt to add something like this, since it doesn't seem like we currently maintain the latest versions of these packages as a default.

**Comment by ngosang** [comment]
I think this is a good idea, but I I don't want that this check blocks the merge of PRs. Just show a warning or something like that. We will fix the security issues when we can.

**Comment by cadatoiva** [comment]
This tool will also create PRs that fix the security issues, so basically all we'd have to do is approve those PRs as they come in. I've made an account and checked, and it says we've actually got several issues with the HTTP library used by a few packages. I'll connect the account to the Jackett org so it can generate the pull requests and share non-blocking status updates.

**Comment by cadatoiva** [comment]
Just need @garfield69 or another member with "owner" status to approve the connection, and I can complete the setup

**Comment by ngosang** [comment]
@junglebus is the person you have to talk to :)

**Comment by cadatoiva** [comment]
You, me and @junglebus are all members, not owners. You can see [the list here](https://github.com/orgs/Jackett/people). As far as I can see, @garfield69 is the only active owner.

**Comment by garfield69** [comment]
I've managed to find the appropriate panel and have bumped all 3 of you to owner status ;-)
and approved the that snyk access.

**Comment by cadatoiva** [comment]
Thanks, I'll get to configuring it after lunch

**Comment by cadatoiva** [comment]
Easier than I thought it would be. Snyk is now attached to the Jackett repo and does the following things:

- Checks each PR for dependency vulnerabilities
  - This check does not fail unless there is a fixed version available
  - This check does not fail a PR unless the PR specifically adds the vulnerable version (existing vulnerabilities do not cause PRs to fail)
- Adds PRs automatically to update vulnerable dependencies that have fixes available.
  - Only updates depends if there is a security issue **and** a fix is available.

**Comment by ngosang** [comment]
@cadatoiva 
* There are 13 Snyk checks in each PR. Could you group them in 1 check?
* There isn't a details link to see what is doing
* Why is your name in all checks?

**Comment by cadatoiva** [comment]
The 13 checks are because one for each project/platform combination. I'll see if I can change that. My name is in it because I hadn't switched it to organization mode yet, so it's using the account name. I'll get that fixed.

Instead of a details, there's hover tooltext stating what it looked for.

I'll see about making this more usable, or switching to a different provider.

**Comment by cadatoiva** [comment]
Couldn't find a way to modify the check to not be 13, so I've disabled the checks. The only thing it would fail on anyway was if someone added a NuGet package that had a known vulnerability to it, and even then only if there was a version that fixed the vulnerability.

Instead I just left the "submit an automated PR to update vulnerable packages" and that should be enough for what we do. We're not changing enough to need the checks

**Comment by zero77** [comment]
Just tested it out and it looks like it's found 15 high vulnerabilities and 6 medium.

![image](https://user-images.githubusercontent.com/16563034/77753629-ce900c80-7021-11ea-974c-eeb6cdcbaba4.png)

**Comment by cadatoiva** [comment]
They're all the same 2 vulnerabilities. just spread out as a dependency for practically every NuGet package we use. The vulnerabilities themselves are also not found in the parts of those dependencies we end up using, so it's not a huge concern to fix. It's akin to being told your engine will explode if you go 90, but you only ever drive in town and never go over 45
