### ISSUE TITLE
[Xspeeds] 4K Categories

### ISSUE THREAD

**Issue by VDXr** [Jackett/Jackett#4519]
Can you add support for the 4K Movies, 4K TV, 4K TV Boxsets Categories? :)

**Comment by garfield69** [comment]
I don't have a login, but I should be able to extract the categories from your site torrent search HTML, if you provide the **full enhanced log** file.
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.
