### ISSUE TITLE
[cpasbien] Exception (cpasbien): Error: NameResolutionFailure: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by maxtop51** [Jackett/Jackett#4533]
I try to change the url and check the .yml and found something change on search method and I try to change that so didn't work.

thanks for help

**Comment by maxtop51** [comment]
Really need help and  the issue #4361 is closed

**Comment by garfield69** [comment]
cpabien is out of reach at the moment. the official cpabien.club redirects to cpabien.link which returns ip-address-not-found, and the alternate cpabien.cx redirects to www.cpasbien.io which is unregistered.
hopefully someone will share news on the official new domain if the site is still alive.

**Comment by maxtop51** [comment]
And the https://ww2.cpasbiens.co or https://ww2.cpasbien9.net/home is the new one?

**Comment by garfield69** [comment]
as far as I can tell those domains are not affiliated with the official site. they use different html to present results so are not compatible with the current indexer.

**Comment by maxtop51** [comment]
the majority of the old link I try redirects to https://www1.cpasbiens.ws/ or https://www.cpasbiens.tv

**Comment by garfield69** [comment]
closed with a45770f5411aa6851723185b743d131d483cd005
