### ISSUE TITLE
[Req] piratbit

### ISSUE THREAD

**Issue by skyfire000** [Jackett/Jackett#4537]
a Russian forum tracker  , possible to support?

**Comment by garfield69** [comment]
hmm. downloading requires captcha challenge, not sure if cardigann can support this @kaso17 ?

**Comment by garfield69** [comment]
Ah. for users that are logged in the .torrent does not have a prove-you-are-not-a-robot challenge so I will setup this site with a login.

**Comment by garfield69** [comment]
try out Jackett pre-release v0.10.723

**Comment by ilike2burnthing** [comment]
https://piratbit.top/ - Error 520 - Web server is returning an unknown error

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://piratbit.top/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://piratbit.top/ returning ERR_TOO_MANY_REDIRECTS

**Comment by garfield69** [comment]
v0.20.244

**Comment by garfield69** [comment]
https://top.pirat.one/ & https://pb.wtf/ cloudflare 522 timed out

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
#14762 removed the piratbit public indexer as the site is blocking jackett. v0.21.1017
this still leaves the login version of the indexer piratbitL which continues to work for now.

**Comment by garfield69** [comment]
the site is changing their search results page regularly, clearly in response to our indexer updates
time to remove this indexer as unwanted by sites' admin.

**Comment by garfield69** [comment]
v0.21.1051

**Comment by AARON8888** [comment]
Hi @garfield69
Pls add pirabit site in Jackett again. It is running https://pb.wtf/

**Comment by ilike2burnthing** [comment]
Read above.

**Comment by AARON8888** [comment]
Sorry, I didn´t see (https://github.com/Jackett/Jackett/issues/4537#issuecomment-1769007284).
Thanks @ilike2burnthing
