### ISSUE TITLE
[greekteam] Found no results while trying to browse this tracker (Test) - can someone check again?

### ISSUE THREAD

**Issue by valantislevas** [Jackett/Jackett#4540]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------
Jackett Version 0.10.657.0

**Comment by garfield69** [comment]
@bladews @tsikup can you confirm for @valantislevas  that greekteam is working for you please? thanks.

**Comment by valantislevas** [comment]
Jackett Version 0.10.675.0  and still doesnt work.. i already check the greekteam.yml with the changes but nothing..

**Comment by tsikup** [comment]
@valantislevas  Did you roll back to the previous greekteam.yml ? Can you upload your config file?

**Comment by valantislevas** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/2808000/log.txt)

**Comment by tsikup** [comment]
Try this one. Be sure to update your username and password if they are not already set.

[greekteam.zip](https://github.com/Jackett/Jackett/files/2808043/greekteam.zip)

**Comment by garfield69** [comment]
@tsikup  from the log it looks like the date selector from the current definition needs to have the nobr dropped.

**Comment by garfield69** [comment]
and the last child count for some of the other selectors is off too.

**Comment by garfield69** [comment]
sorry, looking in the wrong place, the statement about the nobr is wrong. i'll shut up now ;-)

**Comment by garfield69** [comment]
the definition that @tsikup provided should work, albeit the files selector should be 8 not 7.

**Comment by garfield69** [comment]
@valantislevas  try out jackett pre-release 0.10.681 and let us know how you go.
