### ISSUE TITLE
[arabafenice] Exception (arabafenice): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /build/mono-5.18.0.240/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by memnos** [Jackett/Jackett#4547]
It is many days that jackett cannot connect to arabafenice.
Pressing test button i have message in object.
Anything can be done to solve?

Jackett Version 0.10.641.0
Mono JIT compiler version 5.18.0.240

Here is the log:
https://paste2.org/1BhJUv7a

-------------------------------

**Comment by garfield69** [comment]
Please post the output of `curl -vvv https://www.arabafenice.me` and/or `openssl s_client -connect www.arabafenice.me:443`

**Comment by memnos** [comment]
curl -vvv https://www.arabafenice.me
* Rebuilt URL to: https://www.arabafenice.me/
*   Trying 51.38.54.218...
* Connected to www.arabafenice.me (51.38.54.218) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 594 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: arabafenice.me (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: OU=Domain Control Validated,OU=PositiveSSL,CN=arabafenice.me
*        start date: Fri, 04 Jan 2019 00:00:00 GMT
*        expire date: Sun, 15 Sep 2019 23:59:59 GMT
*        issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Domain Validation Secure Server CA
*        compression: NULL
* ALPN, server did not agree to a protocol
> GET / HTTP/1.1
> Host: www.arabafenice.me
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Date: Sat, 26 Jan 2019 11:17:20 GMT
< Server: Apache/2.4.7 (Ubuntu)
< X-Powered-By: PHP/5.5.9-1ubuntu4.26
< Set-Cookie: xbtitFM=4g99aknv8snu1qhs1kc6u2iq21; path=/
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Location: sbg_login_classic.php
< Content-Length: 0
< Content-Type: text/html
<
* Connection #0 to host www.arabafenice.me left intact

openssl s_client -connect www.arabafenice.me:443
CONNECTED(00000003)
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify return:1
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Domain Validation Secure Server CA
verify return:1
depth=0 OU = Domain Control Validated, OU = PositiveSSL, CN = arabafenice.me
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=PositiveSSL/CN=arabafenice.me
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
 1 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
 3 s:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
---
Server certificate
-----BEGIN CERTIFICATE-----
xxxxxxxxxxxxxxxxxx
-----END CERTIFICATE-----
subject=/OU=Domain Control Validated/OU=PositiveSSL/CN=arabafenice.me
issuer=/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 6357 bytes and written 431 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: D8F5328BDD84B327DDE82A1F1245786360C07FCEF1DB8221B5CC7BD21BC217C8
    Session-ID-ctx:
    Master-Key: B156DC09AC49CCFA32D90EB41577A74379CCE1BF7B8FD181699BD4F54004C061F5C7E39B12B41680B40E64252C7170E7
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - e9 22 a7 2a b3 af 4d 29-b8 75 3f b4 36 1b 04 25   .".*..M).u?.6..%
    0010 - 30 d4 77 cc dc 6b 6e 6d-5e 99 3e 4c 09 c0 76 66   0.w..knm^.>L..vf
    0020 - f9 90 34 e4 c6 49 dd 89-95 35 3a ee 67 f0 18 5f   ..4..I...5:.g.._
    0030 - 0e da d9 7f a7 b7 c0 a0-48 85 22 ca 63 b0 8c 1e   ........H.".c...
    0040 - 8a 23 8f 48 dc 05 c4 f1-c5 d1 d9 32 ea 0d 9b 54   .#.H.......2...T
    0050 - 9d 93 5a d0 57 ac 42 02-a5 76 26 6f da 0a 4b 72   ..Z.W.B..v&o..Kr
    0060 - c5 26 1b 57 8f 8d 0d d5-90 be 0d f7 13 6c c9 22   .&.W.........l."
    0070 - 76 93 5d 6b c3 f2 ca d4-47 b4 99 4e 94 e1 47 f5   v.]k....G..N..G.
    0080 - 59 0d c2 7e 31 14 37 37-b1 19 93 b7 d6 bd b4 c8   Y..~1.77........
    0090 - 80 a5 4b 35 58 53 f4 b8-1b 11 02 1d 8a 46 16 ab   ..K5XS.......F..
    00a0 - a1 96 1d a4 d0 29 f0 9b-6b 15 cb 95 6d f6 01 ea   .....)..k...m...
    00b0 - 91 5d 62 6b 31 c3 bc 9d-e4 3c 3e 5a 27 26 d7 ce   .]bk1....<>Z'&..

    Start Time: 1548501475
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---

**Comment by memnos** [comment]
Sorry, maybe better viewable here:
https://paste2.org/hmy83Pn7

**Comment by garfield69** [comment]
@kaso17  could you take a look at the ca test output in this ticket and see if you can spot why the OPs jackett would generate CERTIFICATE_VERIFY_FAILED when the output from the openssl and curl look OK to me? What am I missing? Thanks.

**Comment by memnos** [comment]
Today it is working fine.
Has anything been done?

**Comment by garfield69** [comment]
not by us on the jackett side of things.
