### ISSUE TITLE
[gktorrent] https://www.gktorrent.tv/ fail launch download 

### ISSUE THREAD

**Issue by Milkamax** [Jackett/Jackett#4548]
Hi,

The url Gktorrent work find but the launch fail from jackett cause the file downloaded haven't extension name ".torrent".

Somebody know how to auto put .torrent extension before load file to client torrent ?

Thank you for help,

**Comment by garfield69** [comment]
I'm using jackett 0.10.675
when I click on a jackett gktorrent search result download link I get a torrent file with the .torrent appended.

![image](https://user-images.githubusercontent.com/6933240/51883105-65454700-23e6-11e9-88c3-e0bace5c0dac.png)

if you are not getting this, then this has nothing to do with Jackett.
Most likely it is a set up issue with your system and you need to explore google for explanations.
