### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Request to https://www2.yggtorrent.gg/engine/search?category=all

### ISSUE THREAD

**Issue by NBSDEVApp** [Jackett/Jackett#4552]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.660.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by kriegalex** [comment]
This may be linked to the fact that they are using Cloudflare now ?

**Comment by garfield69** [comment]
make sure you are on jackett version at least 0.10.660 and check that your ygg config is using sitelink https://www.yggtorrent.gg/ and search url www2.yggtorrent.gg by using the wrench icon on your jackett desktop.
ygg is currently working for me with this config,
i'm on the latest jackett 0.10.675
