### ISSUE TITLE
Cloudflare issue with yggtorrent (maybe others ?)

### ISSUE THREAD

**Issue by xfouloux** [Jackett/Jackett#4562]
Hi

We have multiple issue mostly with yggtorrent tracker (as you can see with the number of opened issues) #4552 #4553 mostly

@garfield69 @kaso17 I see that Jackett use :  <PackageReference Include="CloudFlareUtilities" Version="1.2.0" /> from https://github.com/elcattivo/CloudFlareUtilities and it is up to date but we still have issues since yggtorrent moved to cloudflare, maybe you can help on this matter ?

sometimes it doesn't find the login selector, sometime it is another thing it doesn't find.
seems like the cloudflare page is returned sometimes instead of the real one.

YGGTORRENT is semi private, so for tests you could create an account of your own.

we have done some modification with @Hakujou to the yggtorrent.yml file but if we could have your help fixing this once and for all it would help a lot =) !

for info full debug on next post

we can see this : 

```
01-28 01:37:40 Debug WebClient(HttpWebClient).GetString(Url:https://yggtorrent.gg/)
01-28 01:37:41 Debug WebClient(HttpWebClient): Returning Redirect => http://yggtorrent.gg/ <html>redirect...</html>
01-28 01:37:41 Debug updating Cookies  => __cfduid=db84cd50e234d8273fc11de1cb21697681548599860; COLLCK=635071808
01-28 01:37:41 Info Executed action method Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole), returned result Microsoft.AspNetCore.Mvc.OkObjectResult in 898.9787ms.
```

so it mean jackett saw the redirect, got the cloudflare cookie, and continued maybe ? But then fail :/

yesterday night I changed the Site link in my config to : http://www.yggtorrent.gg/ instead of https://yggtorrent.gg/
It seems to be ok for now but until when ?

Thanks !

i'm on latest jackett pre release version on linuxserver docker

**Comment by xfouloux** [comment]
Yeah, this time, it was saying that is could not find user form, restarted docker and working again. So that is strange

**Comment by Hakujou** [comment]
I think the issue is caused by the redirection from the main domain (
www.yggtorrent.gg) to the secondary (www2.yggtorrent.gg), which happens
quite a lot when using the website normally and triggers Cloud Flare check
(the white web page) very often probably as CloudFlare see this behavior as
highly suspicious.

>

**Comment by sh4rkman** [comment]
same problem here, looks like it could not find login form
@xfouloux : restarting jackett fixed the issue ?

**Comment by Hakujou** [comment]
It's random, since CloudFlare is sometimes triggered, sometimes not, just like when using a regular browser.
Jackett seems to fail whenever there's a CloudFlare triggering, which happens quite a lot due to the way YggTorrent handles redirections (poorly done).

**Comment by kriegalex** [comment]
I may be wrong, but from a very low sample size, it seems that testing the connection without a proxy is more successful than with one. Maybe using a proxy from a popular VPN provider or a VPN docker with privoxy triggers Cloudflare "bad mood" ? Am I totally wrong ?

**Comment by Hakujou** [comment]
A proxy might trigger CloudFlare more often (as CloudFlare is probably based on a notation system, much like spam is handled), but the issue is definitely there even without proxy/VPN (I don't use one).

**Comment by SuissoNaBisso9** [comment]
same issue here, yesterday when I saw the post from @garfield69 I updated Jacket to latest version, restarted it then it worked properly. And this morning it's not working anymore....

**Comment by drskullster** [comment]
I worked around this using the secondary domain as Site Link : 

![image](https://user-images.githubusercontent.com/1693766/51897053-1d0a3280-23ae-11e9-884e-d6f6698a98be.png)

**Comment by Hakujou** [comment]
Indeed, it seems to work fine with those settings (no redirections, so it shouldn't trigger CloudFlare, or less, at least).
I'll see if it's stable and push a new update if it is.

**Comment by Hakujou** [comment]
I made a PR which includes those changes. Hopefully YggTorrent will stop changing URL everyday...

**Comment by kriegalex** [comment]
@Hakujou I think they are playing mouse and cat with blacklistings from ISPs. But they should provide some kind of static entry point that redirects to the correct URL so that we don't have to PR every other day Jackett...

**Comment by Hakujou** [comment]
Not ISP, as blocking domains is not allowed in France (at all).

It might be for SEO, but they're just changing subdomain, and in this case, they're switching back & forth to legacy and new URL.
I think they just have some trouble with configuration, especially CloudFlare.

**Comment by SuissoNaBisso9** [comment]
> Indeed, it seems to work fine with those settings (no redirections, so it shouldn't trigger CloudFlare, or less, at least).
> I'll see if it's stable and push a new update if it is.

only last 1 hour and then back to searching login form ^^ even updated and restarded Jackett but nothing to do, still the same issue

**Comment by Hakujou** [comment]
CloudFlare might have trippen again, but without both URL (everything on www2) it's way more stable for me. Pushed changes, will see how it goes in the long run.

I won't be able to fix it any better than this, as circumventing CloudFlare would require some C# and serious engineering.

**Comment by xfouloux** [comment]
it comes and goes.... sometimes I have to restart jackett only, sometimes I have to remove the indexer in jackett and create it again, and sometimes I have to manually remove the remaining yml files with username, password etc in it in order to be able to recreate it... :/

**Comment by Hakujou** [comment]
Unfortunately, it won't help much with our issue. The issues they're talking about are related to the tracker itself, and I have multiple internet providers and confirmed the website works properly.

The issue won't disappear completely unless we get an API or a way to bypass CloudFlare on their end. Until then, we can only tweak it to make it the more reliable we can.

**Comment by Hakujou** [comment]
Ok, they appear to have fully switched to CloudFlare and now it's completely broken. I can't make it work either with one URI or with two URI as before.
I have no idea of how to fix that. @xfouloux, any insight on this ? :)

**Comment by xfouloux** [comment]
working fine for me with Jackett Version 0.10.694.0, but i'm on sydney cloudflare.

**Comment by Hakujou** [comment]
Yes, I identified the issue on my setup.
IPv6 was enabled, which prevents it from working properly. Not sure of why, but anyway, disabled IPv6 for the Jackett container did the trick.

**Comment by xfouloux** [comment]
lets keep it opened a few days and then close if nothing new =)

**Comment by kriegalex** [comment]
can anyone else confirm @Hakujou 's "discovery" ?

**Comment by drskullster** [comment]
Still working for me with v0.10.707.0 and https://www2.yggtorrent.gg/ as Site Link

**Comment by Hakujou** [comment]
Yes it's working, as long as you don't use IPv6.

**Comment by fuzz105** [comment]
Hi
not working for me , jackett installed on syno last os version but with mono. My hardware is old and doesn't allow containers. Ipv6 not used. Question: did you modified yml file ton Make it work? Dobyou have the yml file ton push? Jackett 0.10.712.0.  Thanks a lot

**Comment by timothe** [comment]
Working fine for me atm - similar setup than @drskullster

**Comment by fuzz105** [comment]
Oki, where to find yml modification plz?

**Comment by garfield69** [comment]
@fuzz105 the yyg indexer has not changed with regards to cloudflare support since Jackett v0.10.681
so you are good in that regard.
i dont think there is any yml changes that make a difference, it just a question of whether the clouflare protection is invoked for your IP block or not. As the DDOS attacks die down and clouflare stop black listing IP blocks, access is restored to uses affected.

**Comment by SuissoNaBisso9** [comment]
Working perfectly for me too with URL www2.yggtorrent.gg and not even using search URL.

All good :)

**Comment by fuzz105** [comment]
Ok, just found my issue, works fine 😁

**Comment by deblex** [comment]
For me, doesn't work behind nordvpn servers. I use the Jackett proxy settings to connect to my indexers, it did work fine but now it doesn't anymore. If I take off the proxy, it works fine (tested with another test docker container).

**Comment by Hakujou** [comment]
Can you try to access it using a web browser with the VPN enabled. I think accessing CloudFlare from a VPN might trigger captcha.

**Comment by deblex** [comment]
I just tried (expose my proxy port from my transmissionVPN container) and I managed to login to ygg without captcha behind my proxy.

**Comment by Hakujou** [comment]
The latest fix should work. At least, it's still working for me, and since not much people complained, I guess I'm not alone.

**Comment by anthonyrichir** [comment]
I'm running Jackett Version 0.10.743.0 in a docker container on a Synology NAS with IPv6 disabled and I get the issue.

**Comment by drskullster** [comment]
The secondary domain workaround doesn't work for me anymore. There has been another DDoS attack this afternoon and now I get the cloudflare redirect on www2.yggtorrent.gg.

I'm way out of my league but as I understand from the discussions here the fix should come from ygg ?

Can somebody confirm this ? If someone has an explanation and a potential solution I can try to contact them.

**Comment by garfield69** [comment]
there is no solution. 
the main YGG page is fine, but the moment you navigate to the torrent search page, you are presented with a Captcha challenge to prove you are not a robot.
The challenge is typically the pick three or four pictures that are a bus, or store fronts, or traffic lights or whatever.
currently there is no way to automate a solution for this.
We will just have to wait till the DDOS has dies down and cloudflare relax their anti-DDOS mode.

**Comment by xfouloux** [comment]
@garfield69 right now it's only a captcha challenge where you have to tick a box, no solution for that ?

**Comment by garfield69** [comment]
show me.

**Comment by xfouloux** [comment]
this kind : http://devmd.com/wp-content/uploads/2014/12/No-CAPTCHA-reCAPTCHA.gif

maybe there is a way to get the tick box with JS, and tick it then ?

**Comment by garfield69** [comment]
that is just the start.,  once you tick the box  then you get the chalenge ;-)

**Comment by xfouloux** [comment]
well not always for recaptcha, but it seems to be the case for cloudflare, you always get images. Not just the tick box :/

**Comment by Hakujou** [comment]
CloudFlare works by using a score. The score includes (among other things) mouse movements, IP reputation, data sent by browser (referer, user agent, etc.).

The more your score is close to the "trusted" limit, the easier the captcha is. If you're score is above limit, then there's no captcha. If it's just beyond limit, then there's a simple checkbox (it is the case with CloudFlare, I have it pretty much every time without additional captcha).
If you're score is well below limit, then the captcha is present and the lower your score is, the harder it is.

So the captcha you get actually depends on a lot of factors. For instance, I never get images on CloudFlare, only a simple checkbox (or nothing).
