### ISSUE TITLE
[myanonamouse] Your man_id did not work: An error occurred while sending the request (Config)

### ISSUE THREAD

**Issue by eivl** [Jackett/Jackett#4567]
I try to add myanonamouse to jackett using a generated mam_id from /preferences/security

![3f9xhlj - imgur](https://user-images.githubusercontent.com/132364/52005597-651e7780-24ca-11e9-8cca-dcf3a9422f00.png)

here is a screenshot of my preferences, under is the error from Jackett logs

> System.Exception: Your man_id did not work: An error occurred while sending the request

Any idea if I am doing something wrong or if there is an issue?

**Jackett Version 0.10.678.0**:  
**Mono version 5.10.1.47 **

-------------------------------

**Comment by garfield69** [comment]
@eivl  your imgur link is incorrect, please fix.
@kaso17  could you check out myanonamouse please?

**Comment by eivl** [comment]
It should work now. Let me know if you need me to do anything. Was thinking about reproducing it on my laptop as well.

**Comment by eivl** [comment]
This is the Traceback.

> System.Exception: Your man_id did not work: An error occurred while sending the request   at Jackett.Common.Indexers.Myanonamouse+<ApplyConfiguration>d__8.MoveNext () [0x000df] in <6ea369577f494ec89ae0471fb3427bc3>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at Jackett.Server.Controllers.IndexerApiController+<UpdateConfig>d__13.MoveNext () [0x0012d] in <15cebf59a5824b38afcea3dcc353eb76>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <d7767e54cb234318be4a1e7ddd12ca51>:0    at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x0008a] in <15cebf59a5824b38afcea3dcc353eb76>:0

**Comment by a575606** [comment]
Sorry, slightly off topic, but on the subject of myanonamouse... is there any possibility of flagging vip releases and selecting whether or not to include those in results?

**Comment by garfield69** [comment]
@a575606  probably yes, since the current indexer is written in c# so it is not restricted as it would have been if the indexer was a cardigann definition.
But this request is an enhancement, and outside  the scope of this problem ticket. 
I suggest you raise a separate enhancement ticket, and detail your request there.

**Comment by a575606** [comment]
Yes, fair point. I will do that now.

**Comment by eivl** [comment]
Ill spin up a windows VM meanwhile just to get it working. Is it my ISP or that the server is hidden behind nginx?

**Comment by d2dyno** [comment]
Yeah I ran into this issue as well.

**Comment by kaso17** [comment]
I can reproduce the changing cookie. I've no idea if it's intended (please check with the staff). I also noticed that existing cookies got deleted for some reason but if I use the cookie generated during the initial creation of the entry it's working fine. It's not a jackett issue.
