### ISSUE TITLE
[superbits] Exception (superbits): Unexpected character encountered while parsing value: D. Path '', line 0, position 0.: Parse error (Test)

### ISSUE THREAD

**Issue by prydda** [Jackett/Jackett#4570]
Cannot not save settings to my tracker, since there is no cookie login url, I can only grab uid and passkey. But no url like your cookie example `PHPSESSID=8rk27odm; ipsconnect_63ad9c=1; more_stuff=etc;`
https://gist.github.com/prydda/7f6936c1a4e428a21e8bde5671fd6093

**Jackett version**:  0.10.678.0
**Mono version** (if not using Windows):  Running debian and jackett in docker. 

-------------------------------

**Comment by garfield69** [comment]
the example is just that, an example, not the specific cookie for your site.
copy the whole cookie string, whatever it contains using the copy and paste keys and paste it into the cookie box in your jackett definition.

**Comment by garfield69** [comment]
see https://github.com/Jackett/Jackett/wiki/Finding-cookies for an example of how to find your cookie.
