### ISSUE TITLE
[Tracker Request] Dark-Shadow

### ISSUE THREAD

**Issue by ShadowFM** [Jackett/Jackett#4573]
I saw there is a new german private Tracker "Dark-Shadow"

URL: https://dark-shadow.ml/

it looks like the CMS is the same as https://gods.lu

**Comment by garfield69** [comment]
currently registration is closed, invites only.

**Comment by garfield69** [comment]
If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by ShadowFM** [comment]
Hi,
I've sent you an invitecode, please check your mails.

**Comment by garfield69** [comment]
registration and login successful. thank you.

**Comment by garfield69** [comment]
Try out jackett v0.11.8

**Comment by ShadowFM** [comment]
Worked! 👍

**Comment by garfield69** [comment]
https://dark-shadow.ml/ returning ERR_NAME_NOT_RESOLVED
just me, or is site gone or moved to new domain?
