### ISSUE TITLE
Enhancement: [myanonamouse] - enable / disable vip torrents inclusion in results

### ISSUE THREAD

**Issue by a575606** [Jackett/Jackett#4579]
Any possibility of flagging vip releases and selecting whether or not to include those in results from myanonamouse? I can't find a way to filter them out in LazyLibrarian and that really limits being able to use myanonamouse as a non vip.

**Comment by mapleleafs89** [comment]
Bump :) +1

**Comment by ngosang** [comment]
I would like to add this feature, but I need an invite.

**Comment by Curtis-L** [comment]
> I would like to add this feature, but I need an invite.

you can apply via irc if you want, the interview is pretty easy. https://redd.it/giwjls

**Comment by RoloSoze** [comment]
If anyone wants to join MaM, I just found this - Should be very handy for the interview. 
[MyAnonaMouse interview.txt](https://github.com/Jackett/Jackett/files/4634217/MyAnonaMouse.interview.txt)
