### ISSUE TITLE
[720pier] Login fails and brings to a weird page

### ISSUE THREAD

**Issue by whitesnakeftw** [Jackett/Jackett#4581]
So whenever I try to add 720pier as indexer and hit Okay, instead of successfully login (or being thrown an error) I'm brought to a blank page where the only element is a button on the top-left corner linking to http://www.liveinternet.ru/click for some reason. The url of the blank page is: /UI/Dashboard#search

I deleted the json files for 720pier but that didn't help. Also I thought this was my problem because just yesterday I changed my 720pier password to a more elaborate one, but going back to a simpler password doesn't seem to fix the issue either.

**Comment by whitesnakeftw** [comment]
I closed the program and deleted the old log, so the new one should contain only the relevant info. Only thing that seemed to need redacting was the sid

Thanks for the help

[log.txt](https://github.com/Jackett/Jackett/files/2824960/log.txt)

**Comment by whitesnakeftw** [comment]
Actually no, both username and password are simple ASCII strings. And I confirm all the ? were already there

**Comment by garfield69** [comment]
I can replicate your results if I deliberately put an invalid username in the 720pier config. then after clicking the OKAY i get this page instead of an error message
![image](https://user-images.githubusercontent.com/6933240/52179562-0a29af00-2841-11e9-9380-9f923d5cbd2b.png)
@kaso17  this is one for you to sort out please, can you fix so that we get an error message please? Thanks.

**Comment by whitesnakeftw** [comment]
So weird, my username is really really basic [A-z] and I've had it for years. So is my password but it's also got numbers, really nothing fancy. I'm wondering if that password change triggered anything (I have not changed any settings onsite btw).

Also, for further reference, I was using Chrome before, so I also tried on an incognito Firefox session and the exact same thing happens.

**Comment by garfield69** [comment]
it'll be something obvious, once we can actually get to read the error message.

**Comment by whitesnakeftw** [comment]
Okay I was actually able to fix it. I went on the site, logged off, logged back in, deleted the .json files, restarted Jackett, and successfully added the indexer (even though it took it quite some time, like 10-15 seconds).

So I'm guessing the problem is in fact related to my password change. Maybe due to the fact that when you perform a password change on the site it doesn't really log you off and back in, so possibly some cookies fail to regenerate? Anyway this should be easy to reproduce by changing one's password.

**Comment by cadatoiva** [comment]
Is this bug still present after the changes I made in #6670 ?

**Comment by garfield69** [comment]
no, I can no longer replicate this error.
starting with 720pier from the add-an-indexer page, entering an invalid password generates
![image](https://user-images.githubusercontent.com/6933240/72280208-afc5df00-369c-11ea-833e-c87af9961b77.png)
closing.
