### ISSUE TITLE
[animetosho] Exception (animetosho): The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3.: The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3. (Config)

### ISSUE THREAD

**Issue by Kilo-Five** [Jackett/Jackett#4585]
[animetosho] Exception (animetosho): The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3.: The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3. (Config)

**Comment by Kilo-Five** [comment]
[animetosho] Exception (animetosho): The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3.: The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3. (Config)

**Comment by garfield69** [comment]
animetosho is returning 502 bad gateway. nothing to do with Jackett. just have to wait till the site is fixed by admin.
![image](https://user-images.githubusercontent.com/6933240/52159068-2d9b0f80-2704-11e9-977f-5ac12906cb71.png)

**Comment by garfield69** [comment]
AT was down, but appears to be up again now.
