### ISSUE TITLE
[kickasstorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by cocokola** [Jackett/Jackett#4588]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  Version 0.10.692.0
**Mono version** (if not using Windows):  
I dont see this one listed currently.. I get the no results error. page loads fine when clicking on the tracker on the left side of the list. 
-------------------------------

**Comment by garfield69** [comment]
katcr.co are undergoing maintenance ATM. nothing to do with JAckett. just have to wait until site is fixed.
![image](https://user-images.githubusercontent.com/6933240/52167397-498fc700-277f-11e9-9b36-8085611ec0e3.png)

**Comment by cocokola** [comment]
I was able to use the site manually when I logged the ticket.  I would not be so quick to dismiss.  It is online for me:
![image](https://user-images.githubusercontent.com/9909697/52168232-33d1c180-26ed-11e9-8ddd-36a1af871065.png)

**Comment by garfield69** [comment]
latest update from katcr.co
```
Sunday 3rd February 2019
Database servers are still not reachable, the current issue is no longer related to network maintenance that took place at Friday 1st February 2019.
This new raised issue is still being resolved with our provider's technical team.
We would like to apologise to you for the inconvenience.

Notes: The site may still show some pages such as: details, full, top-100, and some previous search results, these pages come from the site cache.
```
