### ISSUE TITLE
[torrentsectorcrew] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by ShadowFM** [Jackett/Jackett#4589]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well. 

**I did and cannot found a issue for torrentsectorcrew.**

Provide a description of the feature request or bug, the more details the better.

If I insert the credentials and did a test I receive the error above.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**full enhanced log**: https://pastebin.com/aB0T6byx

**Jackett version**: Version 0.10.692.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
Meh. I cant find anything useful in that log snipped you provided ;-(
@kaso17  if you still have a valid login can you check this please? Thanks.

**Comment by ShadowFM** [comment]
As sideinfo I tried it with 2 different server and use Jackett from „Cloudbox“

**Comment by kaso17** [comment]
fixed via dfd1ec375bc467c50dbb5cab6c5fc16acafee8a1
