### ISSUE TITLE
Jackett service in restart loop

### ISSUE THREAD

**Issue by lordaggo** [Jackett/Jackett#4604]
Hey guys, would appreciate your help

I run a raspberry pi3 with raspbian and sonarr, jackett and deluge. I set up the system yesterday and it was working fine at the beginning, but at a certain point the web interface simply stopped responding and there's  no bringing back now. I managed to capture a log:

> pi@raspberrypi:~ $ sudo journalctl -fa -n 100 -u jackett
-- Logs begin at Mon 2019-02-04 20:08:19 EET. --
фев 04 23:04:09 raspberrypi mono[18308]: Could not load type of field 'Jackett.C                                                                                                                                                             ommon.Indexers.RuTracker+<GetConfigurationForSetup>d__10:<LoginResultDocument>5_                                                                                                                                                             _2' (3) due to: Could not resolve type with token 010000b2 from typeref (expecte                                                                                                                                                             d class 'AngleSharp.Dom.Html.IHtmlDocument' in assembly 'AngleSharp, Version=0.9                                                                                                                                                             .9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea') assembly:AngleSharp, Ve                                                                                                                                                             rsion=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea type:AngleSharp.                                                                                                                                                             Dom.Html.IHtmlDocument member:(null)
фев 04 23:04:09 raspberrypi mono[18308]:   at (wrapper managed-to-native) System                                                                                                                                                             .Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
фев 04 23:04:09 raspberrypi mono[18308]:   at System.Reflection.Assembly.GetType                                                                                                                                                             s () [0x00000] in <04750267503a43e5929c1d1ba19daf3e>:0
фев 04 23:04:09 raspberrypi mono[18308]:   at Jackett.Common.Services.IndexerMan                                                                                                                                                             agerService.InitIndexers () [0x00030] in <45d7c4f9f6ef45beaacaf069a75af4e9>:0
фев 04 23:04:09 raspberrypi mono[18308]:   at Jackett.Common.Services.IndexerMan                                                                                                                                                             agerService.InitIndexers (System.Collections.Generic.IEnumerable`1[T] path) [0x0                                                                                                                                                             0000] in <45d7c4f9f6ef45beaacaf069a75af4e9>:0
фев 04 23:04:09 raspberrypi mono[18308]:   at Jackett.Services.ServerService.Ini                                                                                                                                                             talize () [0x005d1] in <fab5a40aa14e448e90ea29864a0d4794>:0
фев 04 23:04:09 raspberrypi mono[18308]:   at Jackett.Console.Program+<>c.<Main>                                                                                                                                                             b__0_1 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00305] in <3fdc9                                                                                                                                                             455375b4767b83b2ba8caded758>:0
фев 04 23:04:09 raspberrypi mono[18308]: System.TypeLoadException: Could not loa                                                                                                                                                             d type of field 'Jackett.Common.Indexers.CardigannIndexer:landingResultDocument'                                                                                                                                                              (2) due to: Could not resolve type with token 010000b2 from typeref (expected c                                                                                                                                                             lass 'AngleSharp.Dom.Html.IHtmlDocument' in assembly 'AngleSharp, Version=0.9.9.                                                                                                                                                             0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea') assembly:AngleSharp, Versi                                                                                                                                                             on=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea type:AngleSharp.Dom                                                                                                                                                             .Html.IHtmlDocument member:(null)
фев 04 23:04:09 raspberrypi mono[18308]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<DoLogin>d__16:<>4__this
фев 04 23:04:09 raspberrypi mono[18308]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<TestLogin>d__20:<>4__this
фев 04 23:04:09 raspberrypi mono[18308]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<GetConfigurationForSetup>d__22:<>4__this
фев 04 23:04:09 raspberrypi mono[18308]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<GetConfigurationForSetup>d__23:<>4__this
фев 04 23:04:09 raspberrypi mono[18308]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<ApplyConfiguration>d__24:<>4__this
фев 04 23:04:09 raspberrypi mono[18308]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<PerformQuery>d__29:<>4__this
фев 04 23:04:09 raspberrypi mono[18308]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<handleRequest>d__30:<>4__this
фев 04 23:04:09 raspberrypi mono[18308]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<Download>d__32:<>4__this
фев 04 23:04:09 raspberrypi mono[18308]: System.TypeLoadException: Could not loa                                                                                                                                                             d type of field 'Jackett.Common.Indexers.PiXELHD+<GetConfigurationForSetup>d__11                                                                                                                                                             :<LoginDocument>5__2' (3) due to: Could not resolve type with token 010000b2 fro                                                                                                                                                             m typeref (expected class 'AngleSharp.Dom.Html.IHtmlDocument' in assembly 'Angle                                                                                                                                                             Sharp, Version=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea') assem                                                                                                                                                             bly:AngleSharp, Version=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31e                                                                                                                                                             a type:AngleSharp.Dom.Html.IHtmlDocument member:(null)
фев 04 23:04:09 raspberrypi mono[18308]: System.TypeLoadException: Could not loa                                                                                                                                                             d type of field 'Jackett.Common.Indexers.RuTracker+<GetConfigurationForSetup>d__                                                                                                                                                             10:<LoginResultDocument>5__2' (3) due to: Could not resolve type with token 0100                                                                                                                                                             00b2 from typeref (expected class 'AngleSharp.Dom.Html.IHtmlDocument' in assembl                                                                                                                                                             y 'AngleSharp, Version=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea                                                                                                                                                             ') assembly:AngleSharp, Version=0.9.9.0, Culture=neutral, PublicKeyToken=e83494d                                                                                                                                                             cdc6d31ea type:AngleSharp.Dom.Html.IHtmlDocument member:(null)
фев 04 23:04:14 raspberrypi systemd[1]: jackett.service: Service hold-off time o                                                                                                                                                             ver, scheduling restart.
фев 04 23:04:14 raspberrypi systemd[1]: Stopped Jackett Daemon.
фев 04 23:04:14 raspberrypi systemd[1]: Started Jackett Daemon.
фев 04 23:04:18 raspberrypi mono[18313]: 02-04 23:04:18 Info App config/log dire                                                                                                                                                             ctory: /home/pi/.config/Jackett
фев 04 23:04:18 raspberrypi mono[18313]: 02-04 23:04:18 Info Starting Jackett 0.                                                                                                                                                             8.929.0
фев 04 23:04:18 raspberrypi mono[18313]: 02-04 23:04:18 Info Environment version                                                                                                                                                             : 4.0.30319.42000 (/usr/lib/mono/4.5)
фев 04 23:04:18 raspberrypi mono[18313]: 02-04 23:04:18 Info OS version: Unix 4.                                                                                                                                                             14.79.7
фев 04 23:04:18 raspberrypi mono[18313]: 02-04 23:04:18 Info ThreadPool MaxThrea                                                                                                                                                             ds: 400 workerThreads, 200 completionPortThreads
фев 04 23:04:18 raspberrypi mono[18313]: 02-04 23:04:18 Info issue: Hostname: \n
фев 04 23:04:18 raspberrypi mono[18313]: 02-04 23:04:18 Info mono version: 5.18.                                                                                                                                                             0.240 (tarball Wed Jan 16 09:36:05 UTC 2019)
фев 04 23:04:19 raspberrypi mono[18313]: 02-04 23:04:19 Info TrustedRootCertific                                                                                                                                                             ates count: 151
фев 04 23:04:19 raspberrypi mono[18313]: 02-04 23:04:19 Info Using HTTP Client:                                                                                                                                                              HttpWebClient
фев 04 23:04:19 raspberrypi mono[18313]: 02-04 23:04:19 Error Top level exceptio                                                                                                                                                             n System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Refle                                                                                                                                                             ction.ReflectionTypeLoadException' was thrown.
фев 04 23:04:19 raspberrypi mono[18313]: Could not load type of field 'Jackett.C                                                                                                                                                             ommon.Indexers.CardigannIndexer:landingResultDocument' (2) due to: Could not res                                                                                                                                                             olve type with token 010000b2 from typeref (expected class 'AngleSharp.Dom.Html.                                                                                                                                                             IHtmlDocument' in assembly 'AngleSharp, Version=0.9.9.0, Culture=neutral, Public                                                                                                                                                             KeyToken=e83494dcdc6d31ea') assembly:AngleSharp, Version=0.9.9.0, Culture=neutra                                                                                                                                                             l, PublicKeyToken=e83494dcdc6d31ea type:AngleSharp.Dom.Html.IHtmlDocument member                                                                                                                                                             :(null)
фев 04 23:04:19 raspberrypi mono[18313]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<DoLo                                                                                                                                                             gin>d__16:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<Test                                                                                                                                                             Login>d__20:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<GetC                                                                                                                                                             onfigurationForSetup>d__22:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<GetC                                                                                                                                                             onfigurationForSetup>d__23:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<Appl                                                                                                                                                             yConfiguration>d__24:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<Perf                                                                                                                                                             ormQuery>d__29:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<hand                                                                                                                                                             leRequest>d__30:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<Down                                                                                                                                                             load>d__32:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: Could not load type of field 'Jackett.C                                                                                                                                                             ommon.Indexers.PiXELHD+<GetConfigurationForSetup>d__11:<LoginDocument>5__2' (3)                                                                                                                                                              due to: Could not resolve type with token 010000b2 from typeref (expected class                                                                                                                                                              'AngleSharp.Dom.Html.IHtmlDocument' in assembly 'AngleSharp, Version=0.9.9.0, Cu                                                                                                                                                             lture=neutral, PublicKeyToken=e83494dcdc6d31ea') assembly:AngleSharp, Version=0.                                                                                                                                                             9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea type:AngleSharp.Dom.Html                                                                                                                                                             .IHtmlDocument member:(null)
фев 04 23:04:19 raspberrypi mono[18313]: Could not load type of field 'Jackett.C                                                                                                                                                             ommon.Indexers.RuTracker+<GetConfigurationForSetup>d__10:<LoginResultDocument>5_                                                                                                                                                             _2' (3) due to: Could not resolve type with token 010000b2 from typeref (expecte                                                                                                                                                             d class 'AngleSharp.Dom.Html.IHtmlDocument' in assembly 'AngleSharp, Version=0.9                                                                                                                                                             .9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea') assembly:AngleSharp, Ve                                                                                                                                                             rsion=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea type:AngleSharp.                                                                                                                                                             Dom.Html.IHtmlDocument member:(null)
фев 04 23:04:19 raspberrypi mono[18313]:   at (wrapper managed-to-native) System                                                                                                                                                             .Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
фев 04 23:04:19 raspberrypi mono[18313]:   at System.Reflection.Assembly.GetType                                                                                                                                                             s () [0x00000] in <04750267503a43e5929c1d1ba19daf3e>:0
фев 04 23:04:19 raspberrypi mono[18313]:   at Jackett.Common.Services.IndexerMan                                                                                                                                                             agerService.InitIndexers () [0x00030] in <45d7c4f9f6ef45beaacaf069a75af4e9>:0
фев 04 23:04:19 raspberrypi mono[18313]:   at Jackett.Common.Services.IndexerMan                                                                                                                                                             agerService.InitIndexers (System.Collections.Generic.IEnumerable`1[T] path) [0x0                                                                                                                                                             0000] in <45d7c4f9f6ef45beaacaf069a75af4e9>:0
фев 04 23:04:19 raspberrypi mono[18313]:   at Jackett.Services.ServerService.Ini                                                                                                                                                             talize () [0x005d1] in <fab5a40aa14e448e90ea29864a0d4794>:0
фев 04 23:04:19 raspberrypi mono[18313]:   at Jackett.Console.Program+<>c.<Main>                                                                                                                                                             b__0_1 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00305] in <3fdc9                                                                                                                                                             455375b4767b83b2ba8caded758>:0
фев 04 23:04:19 raspberrypi mono[18313]: System.TypeLoadException: Could not loa                                                                                                                                                             d type of field 'Jackett.Common.Indexers.CardigannIndexer:landingResultDocument'                                                                                                                                                              (2) due to: Could not resolve type with token 010000b2 from typeref (expected c                                                                                                                                                             lass 'AngleSharp.Dom.Html.IHtmlDocument' in assembly 'AngleSharp, Version=0.9.9.                                                                                                                                                             0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea') assembly:AngleSharp, Versi                                                                                                                                                             on=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea type:AngleSharp.Dom                                                                                                                                                             .Html.IHtmlDocument member:(null)
фев 04 23:04:19 raspberrypi mono[18313]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<DoLogin>d__16:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<TestLogin>d__20:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<GetConfigurationForSetup>d__22:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<GetConfigurationForSetup>d__23:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<ApplyConfiguration>d__24:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<PerformQuery>d__29:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<handleRequest>d__30:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<Download>d__32:<>4__this
фев 04 23:04:19 raspberrypi mono[18313]: System.TypeLoadException: Could not loa                                                                                                                                                             d type of field 'Jackett.Common.Indexers.PiXELHD+<GetConfigurationForSetup>d__11                                                                                                                                                             :<LoginDocument>5__2' (3) due to: Could not resolve type with token 010000b2 fro                                                                                                                                                             m typeref (expected class 'AngleSharp.Dom.Html.IHtmlDocument' in assembly 'Angle                                                                                                                                                             Sharp, Version=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea') assem                                                                                                                                                             bly:AngleSharp, Version=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31e                                                                                                                                                             a type:AngleSharp.Dom.Html.IHtmlDocument member:(null)
фев 04 23:04:19 raspberrypi mono[18313]: System.TypeLoadException: Could not loa                                                                                                                                                             d type of field 'Jackett.Common.Indexers.RuTracker+<GetConfigurationForSetup>d__                                                                                                                                                             10:<LoginResultDocument>5__2' (3) due to: Could not resolve type with token 0100                                                                                                                                                             00b2 from typeref (expected class 'AngleSharp.Dom.Html.IHtmlDocument' in assembl                                                                                                                                                             y 'AngleSharp, Version=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea                                                                                                                                                             ') assembly:AngleSharp, Version=0.9.9.0, Culture=neutral, PublicKeyToken=e83494d                                                                                                                                                             cdc6d31ea type:AngleSharp.Dom.Html.IHtmlDocument member:(null)
фев 04 23:04:24 raspberrypi systemd[1]: jackett.service: Service hold-off time o                                                                                                                                                             ver, scheduling restart.
фев 04 23:04:24 raspberrypi systemd[1]: Stopped Jackett Daemon.
фев 04 23:04:24 raspberrypi systemd[1]: Started Jackett Daemon.
фев 04 23:04:28 raspberrypi mono[18326]: 02-04 23:04:28 Info App config/log dire                                                                                                                                                             ctory: /home/pi/.config/Jackett
фев 04 23:04:28 raspberrypi mono[18326]: 02-04 23:04:28 Info Starting Jackett 0.                                                                                                                                                             8.929.0
фев 04 23:04:28 raspberrypi mono[18326]: 02-04 23:04:28 Info Environment version                                                                                                                                                             : 4.0.30319.42000 (/usr/lib/mono/4.5)
фев 04 23:04:28 raspberrypi mono[18326]: 02-04 23:04:28 Info OS version: Unix 4.                                                                                                                                                             14.79.7
фев 04 23:04:28 raspberrypi mono[18326]: 02-04 23:04:28 Info ThreadPool MaxThrea                                                                                                                                                             ds: 400 workerThreads, 200 completionPortThreads
фев 04 23:04:28 raspberrypi mono[18326]: 02-04 23:04:28 Info issue: Hostname: \n
фев 04 23:04:28 raspberrypi mono[18326]: 02-04 23:04:28 Info mono version: 5.18.                                                                                                                                                             0.240 (tarball Wed Jan 16 09:36:05 UTC 2019)
фев 04 23:04:29 raspberrypi mono[18326]: 02-04 23:04:29 Info TrustedRootCertific                                                                                                                                                             ates count: 151
фев 04 23:04:29 raspberrypi mono[18326]: 02-04 23:04:29 Info Using HTTP Client:                                                                                                                                                              HttpWebClient
фев 04 23:04:29 raspberrypi mono[18326]: 02-04 23:04:29 Error Top level exceptio                                                                                                                                                             n System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Refle                                                                                                                                                             ction.ReflectionTypeLoadException' was thrown.
фев 04 23:04:29 raspberrypi mono[18326]: Could not load type of field 'Jackett.C                                                                                                                                                             ommon.Indexers.CardigannIndexer:landingResultDocument' (2) due to: Could not res                                                                                                                                                             olve type with token 010000b2 from typeref (expected class 'AngleSharp.Dom.Html.                                                                                                                                                             IHtmlDocument' in assembly 'AngleSharp, Version=0.9.9.0, Culture=neutral, Public                                                                                                                                                             KeyToken=e83494dcdc6d31ea') assembly:AngleSharp, Version=0.9.9.0, Culture=neutra                                                                                                                                                             l, PublicKeyToken=e83494dcdc6d31ea type:AngleSharp.Dom.Html.IHtmlDocument member                                                                                                                                                             :(null)
фев 04 23:04:29 raspberrypi mono[18326]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<DoLo                                                                                                                                                             gin>d__16:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<Test                                                                                                                                                             Login>d__20:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<GetC                                                                                                                                                             onfigurationForSetup>d__22:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<GetC                                                                                                                                                             onfigurationForSetup>d__23:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<Appl                                                                                                                                                             yConfiguration>d__24:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<Perf                                                                                                                                                             ormQuery>d__29:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<hand                                                                                                                                                             leRequest>d__30:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: Invalid type Jackett.Common.Indexers.Ca                                                                                                                                                             rdigannIndexer for instance field Jackett.Common.Indexers.CardigannIndexer+<Down                                                                                                                                                             load>d__32:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: Could not load type of field 'Jackett.C                                                                                                                                                             ommon.Indexers.PiXELHD+<GetConfigurationForSetup>d__11:<LoginDocument>5__2' (3)                                                                                                                                                              due to: Could not resolve type with token 010000b2 from typeref (expected class                                                                                                                                                              'AngleSharp.Dom.Html.IHtmlDocument' in assembly 'AngleSharp, Version=0.9.9.0, Cu                                                                                                                                                             lture=neutral, PublicKeyToken=e83494dcdc6d31ea') assembly:AngleSharp, Version=0.                                                                                                                                                             9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea type:AngleSharp.Dom.Html                                                                                                                                                             .IHtmlDocument member:(null)
фев 04 23:04:29 raspberrypi mono[18326]: Could not load type of field 'Jackett.C                                                                                                                                                             ommon.Indexers.RuTracker+<GetConfigurationForSetup>d__10:<LoginResultDocument>5_                                                                                                                                                             _2' (3) due to: Could not resolve type with token 010000b2 from typeref (expecte                                                                                                                                                             d class 'AngleSharp.Dom.Html.IHtmlDocument' in assembly 'AngleSharp, Version=0.9                                                                                                                                                             .9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea') assembly:AngleSharp, Ve                                                                                                                                                             rsion=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea type:AngleSharp.                                                                                                                                                             Dom.Html.IHtmlDocument member:(null)
фев 04 23:04:29 raspberrypi mono[18326]:   at (wrapper managed-to-native) System                                                                                                                                                             .Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
фев 04 23:04:29 raspberrypi mono[18326]:   at System.Reflection.Assembly.GetType                                                                                                                                                             s () [0x00000] in <04750267503a43e5929c1d1ba19daf3e>:0
фев 04 23:04:29 raspberrypi mono[18326]:   at Jackett.Common.Services.IndexerMan                                                                                                                                                             agerService.InitIndexers () [0x00030] in <45d7c4f9f6ef45beaacaf069a75af4e9>:0
фев 04 23:04:29 raspberrypi mono[18326]:   at Jackett.Common.Services.IndexerMan                                                                                                                                                             agerService.InitIndexers (System.Collections.Generic.IEnumerable`1[T] path) [0x0                                                                                                                                                             0000] in <45d7c4f9f6ef45beaacaf069a75af4e9>:0
фев 04 23:04:29 raspberrypi mono[18326]:   at Jackett.Services.ServerService.Ini                                                                                                                                                             talize () [0x005d1] in <fab5a40aa14e448e90ea29864a0d4794>:0
фев 04 23:04:29 raspberrypi mono[18326]:   at Jackett.Console.Program+<>c.<Main>                                                                                                                                                             b__0_1 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00305] in <3fdc9                                                                                                                                                             455375b4767b83b2ba8caded758>:0
фев 04 23:04:29 raspberrypi mono[18326]: System.TypeLoadException: Could not loa                                                                                                                                                             d type of field 'Jackett.Common.Indexers.CardigannIndexer:landingResultDocument'                                                                                                                                                              (2) due to: Could not resolve type with token 010000b2 from typeref (expected c                                                                                                                                                             lass 'AngleSharp.Dom.Html.IHtmlDocument' in assembly 'AngleSharp, Version=0.9.9.                                                                                                                                                             0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea') assembly:AngleSharp, Versi                                                                                                                                                             on=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea type:AngleSharp.Dom                                                                                                                                                             .Html.IHtmlDocument member:(null)
фев 04 23:04:29 raspberrypi mono[18326]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<DoLogin>d__16:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<TestLogin>d__20:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<GetConfigurationForSetup>d__22:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<GetConfigurationForSetup>d__23:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<ApplyConfiguration>d__24:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<PerformQuery>d__29:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<handleRequest>d__30:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: System.TypeLoadException: Invalid type                                                                                                                                                              Jackett.Common.Indexers.CardigannIndexer for instance field Jackett.Common.Index                                                                                                                                                             ers.CardigannIndexer+<Download>d__32:<>4__this
фев 04 23:04:29 raspberrypi mono[18326]: System.TypeLoadException: Could not loa                                                                                                                                                             d type of field 'Jackett.Common.Indexers.PiXELHD+<GetConfigurationForSetup>d__11                                                                                                                                                             :<LoginDocument>5__2' (3) due to: Could not resolve type with token 010000b2 fro                                                                                                                                                             m typeref (expected class 'AngleSharp.Dom.Html.IHtmlDocument' in assembly 'Angle                                                                                                                                                             Sharp, Version=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea') assem                                                                                                                                                             bly:AngleSharp, Version=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31e                                                                                                                                                             a type:AngleSharp.Dom.Html.IHtmlDocument member:(null)
фев 04 23:04:29 raspberrypi mono[18326]: System.TypeLoadException: Could not loa                                                                                                                                                             d type of field 'Jackett.Common.Indexers.RuTracker+<GetConfigurationForSetup>d__                                                                                                                                                             10:<LoginResultDocument>5__2' (3) due to: Could not resolve type with token 0100                                                                                                                                                             00b2 from typeref (expected class 'AngleSharp.Dom.Html.IHtmlDocument' in assembl                                                                                                                                                             y 'AngleSharp, Version=0.9.9.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea                                                                                                                                                             ') assembly:AngleSharp, Version=0.9.9.0, Culture=neutral, PublicKeyToken=e83494d                                                                                                                                                             cdc6d31ea type:AngleSharp.Dom.Html.IHtmlDocument member:(null)
фев 04 23:04:34 raspberrypi systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
фев 04 23:04:34 raspberrypi systemd[1]: Stopped Jackett Daemon.

> 

**Jackett version**:   not sure...
**Mono version** (if not using Windows):  5.18.0.240                                                                                                                                                      

---------------------------

**Comment by lordaggo** [comment]
[jackett_error_log.pdf](https://github.com/Jackett/Jackett/files/2833573/jackett_error_log.pdf)

Attaching the log file itself...

**Comment by garfield69** [comment]
this still a problem?
