### ISSUE TITLE
Favicon cannot save as bookmark

### ISSUE THREAD

**Issue by cj2tech** [Jackett/Jackett#4605]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.712.0
**Installed on**: Docker
**Mono version** (if not using Windows):  5.18.0.240
[log.txt](https://github.com/Jackett/Jackett/files/2834657/log.txt)

Description of Issue :
When going to the website the ico files paths are broken. And the Icons cannot be saved for bookmarks by Firefox. I use a extension to see this that some of the files or images are broken. 

![image](https://user-images.githubusercontent.com/9431091/52318280-b5e21480-2991-11e9-9159-64f53e5e7033.png)

-------------------------------

**Comment by garfield69** [comment]
7c0fd1233f8bdfba29052988ddc1bfd17b758b8f
