### ISSUE TITLE
[turktorrent] Login failed: No form found on http://turktorrent1.in/login.php 

### ISSUE THREAD

**Issue by fevkalbeser** [Jackett/Jackett#4606]
This tracker is just added by @garfield69 
However, when I try to login, I get the error:
Login failed: No form found on http://turktorrent1.in/login.php using form selector form[action=action="takelogin.php"

log: [error.txt](https://github.com/Jackett/Jackett/files/2835312/error.txt)

Any ideas?

**Jackett version**:  0.10.716.0

**Comment by garfield69** [comment]
Hmm. works for me.
![image](https://user-images.githubusercontent.com/6933240/52327494-33208e80-2a51-11e9-96b9-6151d83b86b0.png)

the trace snippet you provided is not enough for a diagnosis.

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

It may be that the site is invoking cloudflare DDOS protection for your IP block, which may interfere with the timing.
yggtorrents went through something similar just recently. Eventually ( 3 to 7 days later) when cloudflare stopped black listing those Jackett users IP addresses, normal access was restored.

**Comment by fevkalbeser** [comment]
I hope it's temporary as you suggested. 
I'd appreciate if you take a look at the enhanced log file @garfield69 
[log.txt](https://github.com/Jackett/Jackett/files/2839700/log.txt)

**Comment by garfield69** [comment]
Ahh. you are being blocked by your ISP:

![image](https://user-images.githubusercontent.com/6933240/52396427-c2dc4080-2b16-11e9-9fd1-e86266ba0328.png)


you could try switching from using your ISP DNS to a public one from **CloudFlare**  see https://1.1.1.1/ for details, or **Google**  see https://developers.google.com/speed/public-dns/docs/using
