### ISSUE TITLE
Enhancement: Override base url in feed links

### ISSUE THREAD

**Issue by a575606** [Jackett/Jackett#4607]
**Jackett version**:  Version 0.10.665.0
**Mono version** (if not using Windows):  5.18.0.240

-------------------------------

I couldn't find anything in the documentation or config.json, but maybe I missed it. I'm running jackett in a docker container on a nas. I do the config in the web gui from a pc in the lan but most of the apps that use jackett are also in docker containers on the same nas. 

The issue is the ip address returned when I copy the torznab feeds is the server's ip, which is not accessible from the other docker containers. I.e. say the server is on 192.168.0.5, but from docker's perspective it's set as the docker gateway, i.e. 172.x.x.1. 

It's not the end of the world, just means I have to copy all the urls in notepad and replace the ips... just would be nice if I could specify the base domain or ip of the returned urls.

**Comment by kaso17** [comment]
I would suggest you use a reverse-proxy to have a hostname accessible by all services.
The URLs generated by jackett can by modified by setting the X-Forwarded-* Headers accordingly.
See https://github.com/Jackett/Jackett#running-jackett-behind-a-reverse-proxy

**Comment by csimpi** [comment]
@kaso17 I think this is overthinking. Why do I need to set up a reverse proxy to solve this very small issue with this huge footprint on the server? What if I run other websites with Apache that sits on my port 80?
