### ISSUE TITLE
PrivateHD tracker no longer works since website change

### ISSUE THREAD

**Issue by Xalaxis** [Jackett/Jackett#461]
Since PrivateHD has moved to their 'Beta 2.0' layout the connection to it has been lost by Jackett and any attempts to configure it result in 'Configuration Failed'

**Comment by staraxis** [comment]
Same here. Only getting the 'Configuration Failed' error.

**Comment by jdenson** [comment]
Same for me.

**Comment by d2dyno** [comment]
Same issue here. They added RSS functionality, which may have something to do with the issue.

Error in log during test of PrivateHD:

Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker
   at Jackett.Services.IndexerManagerService.<TestIndexer>d__9.MoveNext() in C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Test>d__18.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:line 263

**Comment by flightlevel** [comment]
Invite to jackettapp at gmail and ill have a look

**Comment by d2dyno** [comment]
Ok invite sent @flightlevel

**Comment by flightlevel** [comment]
Latest release should fix

**Comment by Xalaxis** [comment]
I can confirm this fixes the issue.  Cheers @flightlevel :smile:

**Comment by Megagator** [comment]
I can't seem to add PrivateHD as a tracker:
![screen shot 2016-08-24 at 15 57 04](https://cloud.githubusercontent.com/assets/6308213/17945813/785ddf94-6a13-11e6-84e8-b4d15a823956.png)

**Comment by d2dyno** [comment]
@Megagator I had to delete the tracker, then re-add it. Then it started working for me after update :)

**Comment by Megagator** [comment]
I've done the same, complete reinstall, re-added all indexers, but PrivateHD still fails. This is running in a docker on UnRaid, but that shouldn't make a difference?

**Comment by d2dyno** [comment]
@Megagator D: I'm guessing your account is in good standing and you can browse PrivateHD normally?

**Comment by Megagator** [comment]
Yeah, I'm manually DLing successfully. This is the docker I'm using: https://hub.docker.com/r/linuxserver/jackett/

**Comment by TouchMyBox** [comment]
I'm having the same issue as MegaGator after updating. Logs spit out this along with a bunch of html

```
Error on 20160825130649 for PrivateHD.txtSystem.TimeZoneNotFoundException: Exception of type 'System.TimeZoneNotFoundException' was thrown.
  at System.TimeZoneInfo.FindSystemTimeZoneByFileName (System.String id, System.String filepath) [0x00018] in /build/mono/src/mono-4.4.1/mcs/class/corlib/System/TimeZoneInfo.cs:552 
  at System.TimeZoneInfo.FindSystemTimeZoneByIdCore (System.String id) [0x0000c] in /build/mono/src/mono-4.4.1/mcs/class/corlib/System/TimeZoneInfo.cs:192 
  at System.TimeZoneInfo.FindSystemTimeZoneById (System.String id) [0x00069] in /build/mono/src/mono-4.4.1/mcs/class/corlib/System/TimeZoneInfo.cs:542 
  at Jackett.Indexers.PrivateHD+<PerformQuery>c__async1.MoveNext () [0x00208] in C:\projects\jackett\src\Jackett\Indexers\PrivateHD.cs:108 
```

**Comment by d2dyno** [comment]
@TouchMyBox It looks like there's an issue with Jackett finding your system's timezone. First off, can you confirm a timezone is set?

**Comment by TouchMyBox** [comment]
`timedatectl status
      Local time: Thu 2016-08-25 14:01:19 EDT
  Universal time: Thu 2016-08-25 18:01:19 UTC
        RTC time: Thu 2016-08-25 18:01:19
       Time zone: America/Toronto (EDT, -0400)
 Network time on: no
NTP synchronized: yes
 RTC in local TZ: no
`

It was working great before the website refresh.

**Comment by d2dyno** [comment]
Excellent, thanks for verifying that! Now we just wait for @flightlevel to look into what's going on.

**Comment by flightlevel** [comment]
@Megagator This will be fixed in the next release, some operating systems call timezones different names eg. Eastern, EST, New York etc Hard coded the value now

**Comment by flightlevel** [comment]
https://github.com/Jackett/Jackett/releases/tag/v0.7.348 should fix

**Comment by TouchMyBox** [comment]
Seems to be working great now. Thanks! :)

**Comment by Megagator** [comment]
@flightlevel Working great again, much thanks!

**Comment by jdenson** [comment]
Working again for me too.
