### ISSUE TITLE
Bug: Elitetorrent.biz wrong search results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#4611]
Searching "bohemian spanish" in Jackett returns wrong results.

Should return 0 results, the same as the website.
https://www.elitetorrent.biz/?s=bohemian+spanish&x=0&y=0

**Jackett version**:  latest

**Comment by garfield69** [comment]
yeah, its picking up the "you may like these alternate torrents" section below the "there was nothing found" message in the main results of the page.
i'll see about adding code to handle the not-found condition or find a way to drop the you-might-like section.
