### ISSUE TITLE
[animetosho] Exception (animetosho): A marca de início 'hr' na linha 5 posição 2 não corresponde à marca de fim de 'body'. Linha 5, posição 36.: A marca de início 'hr' na linha 5 posição 2 não corresponde à marca de fim de 'body'. Linha 5, posição 36. (Test)

### ISSUE THREAD

**Issue by junhinhow** [Jackett/Jackett#4616]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by junhinhow** [comment]
When | Level | Message
-- | -- | --
Feb 07, 2019 01:15:16 AM | Info | Found 39 releases from Horrible Subs
Feb 07, 2019 01:14:51 AM | Error | Jackett.Common.IndexerException: Exception (animetosho): A marca de início 'hr' na linha 5 posição 2 não corresponde à marca de fim de 'body'. Linha 5, posição 36. ---> System.Xml.XmlException: A marca de início 'hr' na linha 5 posição 2 não corresponde à marca de fim de 'body'. Linha 5, posição 36.    em System.Xml.XmlTextReaderImpl.Throw(Exception e)    em System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)    em System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)    em System.Xml.XmlTextReaderImpl.ParseEndElement()    em System.Xml.XmlTextReaderImpl.ParseElementContent()    em System.Xml.XmlTextReaderImpl.Read()    em System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)    em System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)    em System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)    em System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)    em Jackett.Common.Indexers.Feeds.BaseNewznabIndexer.ParseFeedForResults(String feedContent)    em Jackett.Common.Indexers.Feeds.BaseFeedIndexer.<PerformQuery>d__4.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    em Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext()    --- Fim do rastreamento de pilha de exceções internas ---    em Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    em Jackett.Common.Indexers.BaseWebIndexer.<ResultsForQuery>d__25.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    em Jackett.Common.Services.IndexerManagerService.<TestIndexer>d__18.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    em Jackett.Server.Controllers.IndexerApiController.<Test>d__15.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    em Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.<Execute>d__0.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    em Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    em Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)    em Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    em Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    em Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)    em Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    em Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    em Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    em Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    em Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    em Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext() --- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---    em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    em Jackett.Server.Middleware.CustomExceptionHandler.<Invoke>d__3.MoveNext()
Feb 07, 2019 01:14:45 AM | Info | Found 50 releases from Torrentz2

**Comment by garfield69** [comment]
you get this error when the anime tosho site is down, like it is at the moment
![image](https://user-images.githubusercontent.com/6933240/52393574-8a833500-2b0b-11e9-8dc9-e9e28482b5a5.png)
nothing to do with Jackett, you will just have to wait for the site to sort itself out.

**Comment by garfield69** [comment]
AT was down, but appears to be up again now.
