### ISSUE TITLE
[1337x] RSS links not working

### ISSUE THREAD

**Issue by jobrien2001** [Jackett/Jackett#4617]
Hello,

I am getting a 404 when trying to download links from the RSS results.

Anyone else getting the same thing?

Thanks

**Comment by garfield69** [comment]
use your wrench icon on your Jackett Dashboard and edit the 1337x config.
take a look at the **Download Link** select box, and switch from what ever its on currently, to the other one. (Magnets or Itorrents.org).

Caching for searches may interfere with new tests especially if reusing previously repeated searches prior to changing this settings, so consider rebooting the Jackett service, or trying new searches not previously performed, at least until the cache expires.

see if that makes a difference.

My guess is that you had it set to itorrents.org and this site looks up magnet infohash and attempts to provide a .torrent, but there is no guarantee that it can do so.
1337x only has magnets, but some users require .torrents.

**Comment by jobrien2001** [comment]
I had it set to magnets and getting the same results after switching back and forth and restarting the container.

**Comment by jobrien2001** [comment]
I am also not getting the Magnets on the regular search.  The only thing that works is send to blackhole.

**Comment by garfield69** [comment]
it's not just 1337x

any site that has .torrents on their primary results page, or makes users go to a secondary details page to use the download link, causes the rss feed generator to build the jackett redirect link that appears in the rss xml link block.

examples: 
**good magnet** link:
zooqle has magnets in the primary results page, extract from rss feed link
```XML
<link>magnet:?xt=urn:btih:725CABD4E328E944929F32789FF020F52FBEA939&amp;dn=[zooqle.com] The Real Housewives of Beverly Hills S09E01 480p x264-mSD&amp;tr=http://explodie.org:6969/announce&amp;tr=http://announce.xxx-tracker.com:2710/announce&amp;tr=http://tracker1.wasabii.com.tw:6969/announce&amp;tr=http://tracker1.itzmx.com:8080/announce&amp;tr=http://open.acgtracker.com:1096/announce</link>
```

**bad .torrent** link, **good magnet** link:
worldwidetorrent has .torrent and magnets on the primary results page, extract from rss feed link
```XML
<link>http://127.0.0.1:9117/dl/worldwidetorrents/?jackett_apikey=rjyt932397368ghzw99e7b3ev3r55wn5&amp;path=Q2ZESjhOUHlIenZ6RzExRm5Dbngtdm44NDRTNUpJeVFNUUxqeGRKcHJkZFozRi12VFFnUUE2VEJEaGl6Z19EMEtGbl85VHd2d1dQTVRvSExPc0M5SVVoaUZNeWZqeFZBV1ZHZE04VUdJdGtBckRWNWxQOExjMXdwVklvdE1PVm1DbU5zZ0ItY3ZlRmxrempJLXR1OW1XV19UMUJJRFloVFdiclkyZFhOUXQwRExKTFNkSC14ZWR1WDU2WENzRmhqUDBwbzBneFRVMDc2TDk4YnI1OXlBRHNKb0poNE5jNXdsS1RPdUFBQm1KZVUtQlVPTWNBc3gxbnZjTTJlX3B5SExsS0U5TFo1WUViM2lGZzQzSnVPak4taDdBZlVGR1R2dVhaWmZwLUpiNW5lR19kdUhjc3VCQWxoMXhZRVNBT1ExXzQzWXc&amp;file=Judge.Judy.S23E136.Halfway.House.Fail.Son.Paid.to.Care.for.Sick.Mother.HDTV.x264-W4F[ettv]</link>
<torznab:attr name="magneturl" value="magnet:?xt=urn:btih:c19d282bcc9b972d2b18fb4c497e810c73ff7498&amp;dn=Judge.Judy.S23E136.Halfway.House.Fail.Son.Paid.to.Care.for.Sick.Mother.HDTV.x264-W4F[ettv]&amp;tr=udp://tracker.coppersurfer.tk:6969/announce" />
```

**bad magnet or .torrent** link:
1337x requires you to navigate to a details page to get magnet and/or .torrent links, extract from rss
```XML
<link>http://127.0.0.1:9117/dl/1337x/?jackett_apikey=rjyt932397368ghzw99e7b3ev3r55wn5&amp;path=Q2ZESjhOUHlIenZ6RzExRm5Dbngtdm44NDRSZHR4S0xDNDVmN0ZCOVotbDBaV0ZDZHF4dDFHTHRRUTBOS0JGc2FZdjVuYlQ0WlZQVV9TYUtZZGUzdjM2ZC1kS25CaTVXTDBNY1hMUU1kdmNNS0g0bWY0X0owbEx3X3Z0OC04TVp4WEZiQ2xPUkd4MDlway13UmlWRXlpZlNJWXRMZVgtS3ZVNkRTQUZPWFpHNVFEYUFrQlRLVUFlVEtxZkFyRzBSYnRQejhkTDNaRzVLaGc3Nk5PU3ZNWmNHOWhVUml6SUFyMnljTkYtTE1LWDRJRWl4&amp;file=Dragon+Ball+Super:+Broly+(2018)+[WEBRip]+[1080p]+[YTS]+[YIFY]</link>
```

**bad .torrent** link:
3evils has .torrent on the primary results page, extract from rss
```XML
<link>http://127.0.0.1:9117/dl/3evils/?jackett_apikey=rjyt932397368ghzw99e7b3ev3r55wn5&amp;path=Q2ZESjhOUHlIenZ6RzExRm5Dbngtdm44NDRRT1IycFJoU2o1WXU5ZjdnbmFRT1N5c3ZCeUJlTmRoNHZzX09XQmszR1JnZ2diZm0wRjhFMkZfaXpNQzM1VVZwaGNEamZNdlU4Z3NJUTdhYmJPNGNKc0N6RVY2SDZXLWhiSDlEY1Y5Uk9relZIb0JWc2ZabnRySnBLVDh0TTRLYTdmMEdFY0sybHRSYUdtdVpnRDZTLVptbjVzbnpXbXJxTVN4dkJ2Z2tfWUNR&amp;file=Mary.Queen.Of.Scots.2019.DVDRip.XviD.AC3-EVO</link>
```

and none of the Jackett redirect links will work in this scenario.
@kaso17  @flightlevel  what is the explanation for this?

**Comment by jobrien2001** [comment]
This is odd because send to blackhole does work on the jacket search result page, so some sort of redirect or torrent building from hash is working.  However, both links provided in the rss are 404.

**Comment by Allilod** [comment]
Try this one proxy 1337x(.)to for get access to [1337x](https://vpnalist.com/1337x) torrent site

**Comment by garfield69** [comment]
Jackett 0.12.1572

**Comment by soggychips** [comment]
This is still a problem in late 2021... Why was this closed, and is there a fix?

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/blob/b312cf0b72ace2360537ba8c5f1d0f847dc4bc1a/src/Jackett.Server/ActionFilters/DownloadActionFilter.cs#L10-L16
