### ISSUE TITLE
Foreign title with CP - Xthor & Abnormal

### ISSUE THREAD

**Issue by aktavor69** [Jackett/Jackett#462]
Hi, I have an issue with Jackett and CP.

When I want search a foreign film, Jackett try to find the english title.
For exemple, I want to search "La Vache" ( One Man and His Cow )
I chose "La Vache" as title on CP

> 08-24 01:02:27 DEBUG [36m[to.core.media.movie._base] Adding titles: [u'La vache', u'One Man and His Cow'][0m
> 08-24 01:02:27 DEBUG [36m[hpotato.core.plugins.base] Releasing lock: media.get.9379dc66762443e4be3171d9e7d804c3[0m
> 08-24 01:02:27 DEBUG [36m[to.core.media._base.media] Changing status for La vache[0m
> 08-24 01:02:27 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/eta/tt4505208/, data: [][0m
> 08-24 01:02:27 DEBUG [36m[hpotato.core.plugins.base] Setting cache b4645740129144a4c20c5e2565074d34[0m
> 08-24 01:02:27 DEBUG [36m[iders.info.couchpotatoapi] Found ETA for tt4505208: {u'dvd': 0, u'expires': 1473418099, u'theater': 0, u'bluray': False}[0m
> 08-24 01:02:27 DEBUG [36m[o.core.notifications.core] Notifying frontend[0m
> 08-24 01:02:27 DEBUG [36m[o.core.notifications.core] Done notifying frontend[0m
> 08-24 01:02:27 INFO [0m[core.media.movie.searcher] Search for La vache in BR-Rip ignoring ETA[0m
> 08-24 01:02:27 INFO [0m[hpotato.core.plugins.base] Opening url: get https://jackett.domain.tld/potato/bluetigers?imdbid=tt4505208&user=&passkey=xxx[0m
> 08-24 01:02:28 DEBUG [36m[hpotato.core.plugins.base] Setting cache 02e1488d75842206c77f7686206934d6[0m
> 08-24 01:02:28 DEBUG [36m[core.media.movie.searcher] Nothing found for La vache in BR-Rip[0m
> 08-24 01:02:28 INFO [0m[core.media.movie.searcher] Search for La vache in DVD-Rip ignoring ETA[0m
> 08-24 01:02:28 DEBUG [36m[hpotato.core.plugins.base] Getting cache 02e1488d75842206c77f7686206934d6[0m
> 08-24 01:02:28 DEBUG [36m[core.media.movie.searcher] Nothing found for La vache in DVD-Rip[0m
> 08-24 01:02:28 INFO [0m[core.media.movie.searcher] Search for La vache in DVD-R ignoring ETA[0m
> 08-24 01:02:28 DEBUG [36m[hpotato.core.plugins.base] Getting cache 02e1488d75842206c77f7686206934d6[0m
> 08-24 01:02:28 DEBUG [36m[core.media.movie.searcher] Nothing found for La vache in DVD-R[0m
> 08-24 01:02:28 DEBUG [36m[o.core.notifications.core] Notifying frontend[0m
> 08-24 01:02:28 DEBUG [36m[o.core.notifications.core] Done notifying frontend[0m
> 08-24 01:02:28 DEBUG [36m[o.core.notifications.core] Notifying frontend[0m
> 08-24 01:02:28 DEBUG [36m[o.core.notifications.core] Done notifying frontend[0m
> 08-24 01:02:28 DEBUG [36m[o.core.notifications.core] Cleaning messages[0m
> 08-24 01:02:28 DEBUG [36m[o.core.notifications.core] Done cleaning messages[0m
> 08-24 01:02:43 DEBUG [36m[o.core.notifications.core] Cleaning messages[0m
> 08-24 01:02:43 DEBUG [36m[o.core.notifications.core] Done cleaning messages[0m

And on jackett 

`Aug 24, 2016 12:02:28 AM   Info    
Found 0 torrentpotato releases from BlueTigers for: One Man and His Cow`

And the movie is on the tracker. Same result with 720p ou 1080p version

Any idea ?

**Comment by flightlevel** [comment]
@aktavor69  

If you look here in the log

`08-24 01:02:27 INFO �[0m[hpotato.core.plugins.base] Opening url: get https://jackett.domain.tld/potato/bluetigers?imdbid=tt4505208&user=&passkey=xxx�[0m`

CP is supplying Jackett with only the IMDB id and no search term. Reading the CP wiki, it should be supplying both https://github.com/CouchPotato/CouchPotatoServer/wiki/CouchPotato-Torrent-Provider#parameters . Since Jackett only has an IMDB to go with and bluetigers doesn't support searching via IMDB id, Jackett must look up the movie name from the ID. If you look here http://www.omdbapi.com/?i=tt4505208&plot=short&r=json or the IMDB website the movies name has actually changed to 'One Man and His Cow', it was originally 'La vache'

I don't have CP running here. Can you stop CP. Then change the couchpotato/core/media/movie/providers/torrent/torrentpotato.py file on your computer to match this
https://gist.github.com/flightlevel/fe1db8cc11e80b4cd5f66be1a8cde10f

If it fixes your search, I'll submit a PR to CP

**Comment by aktavor69** [comment]
@flightlevel 

It's working now, thanks.

I have another issue, may be you can help me too with it.

When I want search a movie with french accent like " é " , for example " Les naufragés ", I have this : 

> 08-24 12:05:38 DEBUG [36m[to.core.media._base.media] Changing status for Les Naufragés[0m
08-24 12:05:38 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/eta/tt5338174/, data: [][0m
08-24 12:05:38 DEBUG [36m[hpotato.core.plugins.base] Setting cache 931de3babc159e101074744b171bc67b[0m
08-24 12:05:38 DEBUG [36m[iders.info.couchpotatoapi] Found ETA for tt5338174: {u'dvd': 0, u'expires': 1473433368, u'theater': 0, u'bluray': False}[0m
08-24 12:05:38 DEBUG [36m[o.core.notifications.core] Notifying frontend[0m
08-24 12:05:38 DEBUG [36m[o.core.notifications.core] Done notifying frontend[0m
08-24 12:05:38 INFO [0m[core.media.movie.searcher] Search for Les Naufragés in 720p ignoring ETA[0m
08-24 12:05:38 DEBUG [36m[hpotato.core.plugins.base] Getting cache cf748b0ea97221a562cb09875107efec[0m
08-24 12:05:38 INFO [0m[hpotato.core.plugins.base] Opening url: get https://jackett.domain.ltd/potato/bluetigers?imdbid=tt5338174&search=Les+Naufrag%C3%A9s&user=&passkey=xxx[0m
08-24 12:05:39 DEBUG [36m[hpotato.core.plugins.base] Waiting for TorrentPotato, 1 seconds[0m
08-24 12:05:39 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/search/movie?api_key=xxx&language=fr&query=les%20naufrages, data: [][0m
08-24 12:05:39 DEBUG [36m[hpotato.core.plugins.base] Setting cache d339cb2a1de128ad9d2ebe460ebb855e[0m
08-24 12:05:39 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd-only.org/ajax.php?action=browse&searchstr=les%20naufrag%C3%A9s, data: [][0m
08-24 12:05:39 DEBUG [36m[hpotato.core.plugins.base] Setting cache 7bb0c471715c5eab23124814d1e26a9b[0m
08-24 12:05:39 DEBUG [36m[hpotato.core.plugins.base] Getting cache cf748b0ea97221a562cb09875107efec[0m
08-24 12:05:40 INFO [0m[hpotato.core.plugins.base] Opening url: get https://jackett.domaine.ltd/potato/abnormal?imdbid=tt5338174&search=Les+Naufrag%C3%A9s&user=&passkey=xxx[0m
08-24 12:05:40 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/search/movie?api_key=xxx&language=fr&query=les%20naufrag%C3%A9s, data: [][0m
08-24 12:05:40 DEBUG [36m[hpotato.core.plugins.base] Setting cache 81bc2c46ac5d913ae19830a02506af3d[0m
08-24 12:05:40 DEBUG [36m[hpotato.core.plugins.base] Setting cache 72084488090a73bdd9cfd066648f6f35[0m
08-24 12:05:40 DEBUG [36m[hpotato.core.plugins.base] Waiting for TorrentPotato, 1 seconds[0m
08-24 12:05:41 INFO [0m[hpotato.core.plugins.base] Opening url: get https://jackett.domaine.ltd/potato/xthor?imdbid=tt5338174&search=Les+Naufrag%C3%A9s&user=&passkey=xxx[0m
08-24 12:05:41 DEBUG [36m[hpotato.core.plugins.base] Setting cache 6d8ddd21d9ce943ae89a7c60c1d6c9c7[0m
08-24 12:05:41 DEBUG [36m[core.media.movie.searcher] Nothing found for Les Naufragés in 720p[0m
08-24 12:05:41 INFO [0m[core.media.movie.searcher] Search for Les Naufragés in 1080p ignoring ETA[0m
08-24 12:05:41 DEBUG [36m[hpotato.core.plugins.base] Getting cache cf748b0ea97221a562cb09875107efec[0m
08-24 12:05:41 DEBUG [36m[hpotato.core.plugins.base] Getting cache d339cb2a1de128ad9d2ebe460ebb855e[0m
08-24 12:05:41 DEBUG [36m[hpotato.core.plugins.base] Getting cache fb644c75196e9ec87b3e9c3b8a84a8bc[0m
08-24 12:05:41 DEBUG [36m[hpotato.core.plugins.base] Getting cache 72084488090a73bdd9cfd066648f6f35[0m
08-24 12:05:41 DEBUG [36m[hpotato.core.plugins.base] Getting cache 6d8ddd21d9ce943ae89a7c60c1d6c9c7[0m
08-24 12:05:41 DEBUG [36m[hpotato.core.plugins.base] Getting cache 7bb0c471715c5eab23124814d1e26a9b[0m
08-24 12:05:41 DEBUG [36m[core.media.movie.searcher] Nothing found for Les Naufragés in 1080p[0m
08-24 12:05:41 DEBUG [36m[o.core.notifications.core] Notifying frontend[0m
08-24 12:05:41 DEBUG [36m[o.core.notifications.core] Done notifying frontend[0m
08-24 12:05:41 DEBUG [36m[o.core.notifications.core] Notifying frontend[0m
08-24 12:05:41 DEBUG [36m[o.core.notifications.core] Done notifying frontend[0m
08-24 12:05:52 DEBUG [36m[o.core.notifications.core] Cleaning messages[0m
08-24 12:05:52 DEBUG [36m[o.core.notifications.core] Done cleaning messages[0m
08-24 12:06:07 DEBUG [36m[o.core.notifications.core] Cleaning messages[0m
08-24 12:06:07 DEBUG [36m[o.core.notifications.core] Done cleaning messages[0m

> 

With Jackett

`Found 0 torrentpotato releases from BlueTigers for: Les Naufragés
Found 0 torrentpotato releases from Abnormal for: Les Naufragés
Found 0 torrentpotato releases from Xthor for: Les Naufragés
`

And with a manuel search on Jackett with the same word " Les Naufragés "

http://i.imgur.com/WGKct4b.png

Any idea why ?

Thanks for your big help !!

**Comment by flightlevel** [comment]
Good to hear @aktavor69 

We might need our french expert here, any ideas @JigSawFr 

Are all E's accented in french?

**Comment by aktavor69** [comment]
Nop, we have basic E and é, è, ê, ë

**Comment by JigSawFr** [comment]
@flightlevel sorry i missed your notification, your answer is true, not all E letter are accentued !

**Comment by aktavor69** [comment]
@flightlevel @JigSawFr any news about this ?
Thanks

**Comment by armani316** [comment]
This may be related to #968 and #977. I could be wrong here because I only ever search using English letters, but is Jackett's manual search capable of handling non-English letters and characters (Chinese, Nordic, Russian, other Eastern European, etc.)?

**Comment by kaso17** [comment]
Can someone supply an invite for the broken tracker (Xthor/Abnormal), then I should be able to fix it.

**Comment by itdaboyz** [comment]
Still need an invite for both trackers?

If that can be useful, here is a list of french accented characters : 

With accent | Corresponding letter
------------ | -------------
à, â, ä | a
À, Â, Ä | A
æ | ae
Æ | AE
ç | c
Ç | C
é, è, ê, ë | e
É, È, Ê, Ë | E
î, ï | i
Î, Ï | I
ô | o
Ô | O
œ | oe
Œ | OE
ù, û, ü | u
Ù, Û, Ü | U

**Comment by kaso17** [comment]
yes, an invite is still needed.

**Comment by itdaboyz** [comment]
Ok, I'll try to invite you then.

**Comment by kaso17** [comment]
got the abnormal "invite", it's just an email telling me to apply (interview) via IRC? Do you know if I can do it in english?

**Comment by itdaboyz** [comment]
Yeah, I asked the staff if they can invite you without the interview process.

**Comment by kaso17** [comment]
Thank you @itdaboyz 
Is this actually still a problem with the latest version?
http://127.0.0.1:9117/potato/abnormal?imdbid=tt5338174&search=Les+Naufrag%C3%A9s&user=&passkey=xxx
is working fine for me.
I think 3f8c87ad7f373db5a8032817c18529f09109d039 from 2 days ago fixed this.

**Comment by itdaboyz** [comment]
I had an issue with Abnormal yesterday but it's in fact an issue with the search function on the site : 
"Retour chez ma mère" shows 5 torrents : http://i.imgur.com/xcqQcCl.png
"Retour chez ma mère 2016" shows 0 torrent : http://i.imgur.com/juQh3cB.png
"Retour chez ma mere" shows 5 torrents : http://i.imgur.com/vij8nHA.png
"Retour chez ma mere 2016" shows 5 torrents : http://i.imgur.com/FWjBDJ1.png
Nothing to do with Jackett then because the same search was working with Xthor.

About the list of french characters https://github.com/Jackett/Jackett/issues/462#issuecomment-280274139 is it ok?

**Comment by kaso17** [comment]
I'm using the build in culture mapping from C#, that should work

Can't fix the tracker search engine ;)

xthor seems to be fixed also, closing this issue
