### ISSUE TITLE
[datascene] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by a-nunes** [Jackett/Jackett#4629]
When trying to do the test on DataScene tracker, it returns "Found no results while trying to browse this tracker", and recommend to open a GitHub issue.

**Jackett Version 0.10.716.0**:  

-------------------------------

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by a-nunes** [comment]
Here it is: https://pastebin.com/4SYGc9T0

**Comment by garfield69** [comment]
search result layout has changed. try Jackett pre-release 0.10.734

**Comment by Cry0nicS** [comment]
Would like to re-open this issue as I'm facing the same problem.
Currently, using Version 0.16.1138.0

Here's my log: https://pastebin.com/2TCRzRSx

**Comment by garfield69** [comment]
the logs you provided shows that your Jackett indexer is attempting to use the following path
` https://datascene.net/connect.php/browse.php?cat=0&search=&incldead=2&blah=0&sort=4&type=desc`
it should be
`https://datascene.net/browse.php?cat=0&search=&incldead=2&blah=0&sort=4&type=desc`
this suggests that you have the incorrect sitelink specified in your indexer config.

I suggest you access your jackett dashboard and edit the datascene config and check that the sitelink is set to `https://datascene.net/` and try again.
