### ISSUE TITLE
Couchpotato not finding TorrentDay movies/x265 releases

### ISSUE THREAD

**Issue by AnilDaoud** [Jackett/Jackett#463]
Couchpotato is not able to find x265 releases using Jackett/TD
Indeed, http://localhost:9117/potato/torrentday?imdbid=tt1392170&user=&passkey=xxx 
does not return any x265 release.
Whereas looking for tt1392170 through Jackett/Manual search does return a x265 release.

Is this a case of missing Movies/x265 in the list of categories for TD?

**Comment by flightlevel** [comment]
Yep, all the sequels didn't help either
Should be fixed now

**Comment by AnilDaoud** [comment]
Works great thanks.
