### ISSUE TITLE
New tracker request - https://www.loucos-share.org

### ISSUE THREAD

**Issue by Flosimfm** [Jackett/Jackett#4640]
Is it possible to add it in Jackett?

Tracker website : https://www.loucos-share.org

**Comment by garfield69** [comment]
it may be possible, but since the site appears to currently accept registrations only with invites, we don't know for certain.
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by Flosimfm** [comment]
New invitations are available at:

[](http://www.loucos-share.org/account-signup.php?fbclid=IwAR1AFdslhmpWMv00bGzOrGPz3gGi7Kunxgzh3FaYmfbl6p_JVEhlfEE5Fs4)

**Comment by garfield69** [comment]
that's the **form** for registering, but I still need the **invite** code ;-)

**Comment by Flosimfm** [comment]
invitation code sent via email

**Comment by garfield69** [comment]
registration and login successful. thank you.

**Comment by garfield69** [comment]
unfortunately this site builds its torrent results page dynamically, so there is no html to scrape.
this means it is not a candidate for a cardigann indexer, it will need a native c# indexer to be built and a c# developer to write it. :-(

**Comment by garfield69** [comment]
http://www.loucos-share.org/ currently returning Fatal error: Call to undefined function gmp_strval() in /home/brsh/public_html/loucos-share.org/backend/functionsnew.php on line 1238

**Comment by ilike2burnthing** [comment]
`This account is no longer active on this server.`

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
closed by mistake

**Comment by garfield69** [comment]
was going to take a look and see if the latest cardigann could handle this site, but:
https://www.loucos-share.org/ offline with ERR_CONNECTION_REFUSED
is it IP regional only?

**Comment by ilike2burnthing** [comment]
http://www.loucos-share.org/ redirects to http://ww1.loucos-share.org/ which is a domain parking ad page
