### ISSUE TITLE
[Req] amigos share club

### ISSUE THREAD

**Issue by Flosimfm** [Jackett/Jackett#4642]
Is it possible to add it in Jackett?

Tracker website: http://amigos-share.club

New invitations are available at: http://amigos-share.club/account-signup.php

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by Flosimfm** [comment]
invitation code sent via email

**Comment by garfield69** [comment]
registration and login successful. Thank you.
And at first glance it does look like the site can be processed by cardigann \o/

**Comment by garfield69** [comment]
Try Jackett v0.10.743

**Comment by Flosimfm** [comment]
It's working, thank you.

**Comment by garfield69** [comment]
site appears to be offline.
![image](https://user-images.githubusercontent.com/6933240/72409385-78555080-37ca-11ea-9a83-d7e50a3d9339.png)

**Comment by garfield69** [comment]
https://amigos-share.club/ now returning Error 521 Web server is down

**Comment by garfield69** [comment]
https://amigos-share.club/ down for maintenance
![image](https://user-images.githubusercontent.com/6933240/83980338-047a3700-a969-11ea-8c37-a88badb2e7de.png)

**Comment by ilike2burnthing** [comment]
login page back up

**Comment by garfield69** [comment]
https://cliente.amigos-share.club/ returns Error 524 A timeout occurred

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
I'm seeing
![image](https://user-images.githubusercontent.com/6933240/160323333-a3923a21-0e07-4caa-b999-ffd4e92e60f6.png)

**Comment by ilike2burnthing** [comment]
Ah, login page is now available, but I'm guessing if you sign in it's still down.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
5h later its down again with Error 522 Connection timed out

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://cliente.amigos-share.club/ returns
(google translation enabled)
![image](https://user-images.githubusercontent.com/6933240/161670163-69a2f42f-5b43-4f73-8813-8951d5f4a2f0.png)

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://cliente.amigos-share.club/
![image](https://github.com/Jackett/Jackett/assets/6933240/c042760b-d2d7-4dd5-a090-837fd6c7ff9a)

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://cliente.amigos-share.club/ cloudflare Web server is down Error code 521

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://cliente.amigos-share.club/ cloudflare Connection timed out Error code 522

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://cliente.amigos-share.club/ > invalid CA, domain expired landing page

**Comment by ilike2burnthing** [comment]
back up, valid cert
