### ISSUE TITLE
New Tracker Request - https://friends-share.me

### ISSUE THREAD

**Issue by tnascif** [Jackett/Jackett#4647]
Is it possible to add it in Jackett?

Tracker website: https://friends-share.me

New invitations are available at: https://friends-share.me/account-signup.php

**Comment by garfield69** [comment]
currently returning bad gateway 502

**Comment by garfield69** [comment]
registration and login successful.

**Comment by garfield69** [comment]
unfortunately, this site generates the torrent search results dynamically, which means it is not suitable for a cardigann definition, as there is no HTML to scrape.
It will require a native c# indexer to be written when a c# developer becomes available.

**Comment by gabrielofers** [comment]
Hi, good evening ... Any news on this tracker?
Thank you very much

**Comment by garfield69** [comment]
>Any news on this tracker?

no progress, pending a c# developer contributing.

**Comment by dimqua** [comment]
Gone?

**Comment by garfield69** [comment]
probably. seeing Error 522 Connection timed out

I'll close it. Can always reopen if someone updates with working domain.
