### ISSUE TITLE
puntotorrent.yml does't show right size

### ISSUE THREAD

**Issue by RicardoVelaC** [Jackett/Jackett#4663]
Jackett Version: 0.10.759.0

[Jackett/src/Jackett.Common/Definitions/puntotorrent.yml](Jackett/src/Jackett.Common/Definitions/puntotorrent.yml)

Results search torrents in Jackett appears with different size than website e.g.:

- 3,53GB show as 353GB

- 552,21MB show as 53,9GB

- 59,74GB show as 5,8TB

<img width="1242" alt="captura de pantalla 2019-02-13 a las 11 53 47" src="https://user-images.githubusercontent.com/6016812/52706942-d5c39a80-2f86-11e9-9703-1ad3fadf7891.png">
<img width="869" alt="captura de pantalla 2019-02-13 a las 11 54 21" src="https://user-images.githubusercontent.com/6016812/52706948-da884e80-2f86-11e9-9454-3dcec526ebba.png">

**Comment by garfield69** [comment]
fixed in Jackett pre-release 0.10.762
