### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Request to https://www2.yggtorrent.gg/engine/search?category=2145

### ISSUE THREAD

**Issue by razmoket89** [Jackett/Jackett#4665]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

`An error occured while testing this indexer
Exception (yggtorrent): Request to https://www2.yggtorrent.gg/engine/search?category=2145&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date failed (Error Forbidden) - The page is protected by an Cloudflare reCaptcha. The page is in aggressive DDoS mitigation mode or your IP might be blacklisted (e.g. in case of shared VPN IPs). There's no easy way of making it usable with Jackett.: Request to https://www2.yggtorrent.gg/engine/search?category=2145&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date failed (Error Forbidden) - The page is protected by an Cloudflare reCaptcha. The page is in aggressive DDoS mitigation mode or your IP might be blacklisted (e.g. in case of shared VPN IPs). There's no easy way of making it usable with Jackett.`

**Comment by razmoket89** [comment]
Using latest jackett version via docker
might be linked with recent ygg reopening.

**Comment by garfield69** [comment]
YGG are under DDOS attack, and have enabled cloudflare anti DDOS when accessing the torrent search page.
The reCaptcha cannot currently be automatically solved so Jackett chokes on the redirect that never gets resolved.
Nothing can be done currently, just have to wait for the cloudflare alert to be lifted when the attack is over.
