### ISSUE TITLE
System.Net.Sockets.SocketException: Address already in use

### ISSUE THREAD

**Issue by kz0** [Jackett/Jackett#467]
Trying to bind to loopback on Ubuntu produces this error.

Is there an alternate way to bind to a loopback device?

**Comment by flightlevel** [comment]
whats the result of https://github.com/Jackett/Jackett/issues/308#issuecomment-211341033

**Comment by flightlevel** [comment]
This issue hasn't had activity for a while. If the issue still exists, please reopen.
