### ISSUE TITLE
Add Indexer/Tracker - documentarytorrents.com

### ISSUE THREAD

**Issue by Theli93** [Jackett/Jackett#4670]
Private
http://www.documentarytorrents.com

**Comment by garfield69** [comment]
Try Jackett pre-release 0.10.768

**Comment by garfield69** [comment]
http://www.documentarytorrents.com/ returning 
```html
Gateway Timeout
The gateway did not receive a timely response from the upstream server or application.

Additionally, a 504 Gateway Timeout error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by garfield69** [comment]
http://www.documentarytorrents.com/ returning 
```html
Gateway Timeout
The gateway did not receive a timely response from the upstream server or application.

Additionally, a 504 Gateway Timeout error was encountered while trying to use an ErrorDocument to handle the request.
```
just me or is the site gone, broken, or moved to a new domain?

**Comment by garfield69** [comment]
back online.

**Comment by RoloSoze** [comment]
Down again.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
down again same as https://github.com/Jackett/Jackett/issues/4670#issuecomment-690979025

**Comment by ilike2burnthing** [comment]
~Working ok here. Just registered an account, added it to Jackett, and was able to search and download without issue.~

Refreshed the page just before posting this and got the same error as you.

**Comment by garfield69** [comment]
the server must be under strain. I just retried and it worked.
so the issue is intermittent.

**Comment by ilike2burnthing** [comment]
> http://www.documentarytorrents.com/ returning 504 Gateway timeout
> 
> ```
> Gateway Timeout
> The gateway did not receive a timely response from the upstream server or application.
> 
> Additionally, a 504 Gateway Timeout error was encountered while trying to use an ErrorDocument to handle the request.
> ```

Short lived 🙄

**Comment by garfield69** [comment]
working for me ATM

**Comment by ilike2burnthing** [comment]
Of course it comes back up when someone else looks at it. I'll keep an eye on it for a few hours, close this if it stays up

**Comment by ilike2burnthing** [comment]
Literally just failed again.

And as I typed that, it's back up again lol

**Comment by ilike2burnthing** [comment]
@garfield69 I've monitored this site closely over the past 2 weeks, and it seems to go down fairly frequently (every few hours for a few minutes), but mostly it's online. Should we just treat this as a volatile indexer, and only mark as down if someone reports the site as being actually offline for an extended period of time (e.g. >24hrs)?

**Comment by garfield69** [comment]
yes.
