### ISSUE TITLE
YTS category WEBRip parsed as BRRIP

### ISSUE THREAD

**Issue by johngjerde** [Jackett/Jackett#4672]
Using Radarr with Jackett and Transmission
Search results are sent back to Radarr with Bluray-1080p as the quality. The release is actually WEBDL-1080p. This causes a failure to automatically import the release: "File quality does not match quality of the grabbed release"

From the YTS rss feed:
<title>{REMOVED} (2019) [WEBRip] [1080p] [YTS.AM]</title>

From Jackett manual search:
[YTS] {REMOVED} (2019) 1080p BRRip

**Jackett version**:  0.10.759.0
**Mono version** (if not using Windows):  5.10.1.57_1

-------------------------------
[log.txt](https://github.com/Jackett/Jackett/files/2861591/log.txt)

**Comment by garfield69** [comment]
will be resolved when enhancement #4577 is committed.

**Comment by garfield69** [comment]
Jackett pre-release v0.10.783 has fix.
