### ISSUE TITLE
Update HD-Space to include movies

### ISSUE THREAD

**Issue by d2dyno** [Jackett/Jackett#468]
I would like for the HD-Space indexer to be updated, to support the site's movie and other categories. I will be appending the category mappings as a pull request.

**Comment by d2dyno** [comment]
@flightlevel Just a heads up, while the indexer now supports the category, the actual search function will not find movies or anything in a category besides TV.

**Comment by d2dyno** [comment]
Would we put something like this under query?
`var searchString = query.GetQueryString();`

Trying to learn as I go, to maybe be of some help in the future :)

**Comment by d2dyno** [comment]
Also, I think the SearchURL needs to be updated, but I'm not sure the proper way:

`index.php?page=torrents&active=0&options=0&category=21%3B22&search={0}` - categories are currently hardcoded in, which prevents from searching outside of TV categories on indexer.

`index.php?page=torrents&search=&active=0&options=0&category=19` - current URL from HD-Space itself, when searching.

**Comment by absintheboy** [comment]
Completely novice user here, but has this been implemented?  I have the latest version and I still can't d/l anything from HD-Space movie categories.  Not sure if there's something I should be doing to get this to work, or if I should just be patient and wait for it to be added.

**Comment by d2dyno** [comment]
@absintheboy this hasn't been added yet, so the movie functionality is currently missing for this tracker.

**Comment by flightlevel** [comment]
@d2dyno You're right its the categories hard coded in causing the issue
 the {0} is the value from  `query.GetQueryString()` https://github.com/Jackett/Jackett/blob/master/src/Jackett/Indexers/HDSpace.cs#L101 basically the showname - episode

What we need to do is add the categories in dynamically from the users search eg.
https://github.com/Jackett/Jackett/blob/master/src/Jackett/Indexers/IPTorrents.cs#L133

**Comment by d2dyno** [comment]
This was added in #584.
