### ISSUE TITLE
Getting this when trying to start jackett

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [Jackett/Jackett#4691]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jsackett/Jackett#troubleshooting

**Jackett version**:  v0.10.776
**Mono version** (if not using Windows):  v5.18.0.240

-------------------------------
Hey,
My jackket was working just fine, I think it updated itself to latest version and I cant turn it on anymore. Here is the output of `journalctl -u jackett.service` : 
`-- Logs begin at Thu 2019-02-14 11:53:34 WET, end at Fri 2019-02-15 17:47:19 WET. --
Feb 14 11:53:34 mike-machine systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
Feb 14 11:53:34 mike-machine systemd[1]: jackett.service: Scheduled restart job, restart counter is at 54289.
Feb 14 11:53:34 mike-machine systemd[1]: Stopped Jackett Daemon.
Feb 14 11:53:34 mike-machine mono[1351]: Unhandled Exception:
Feb 14 11:53:34 mike-machine mono[1351]: System.IO.FileNotFoundException: Could not load file or assembly 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies
Feb 14 11:53:34 mike-machine mono[1351]: File name: 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null'
Feb 14 11:53:34 mike-machine mono[1351]: [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyTok
Feb 14 11:53:34 mike-machine mono[1351]: File name: 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null'
Feb 14 11:53:34 mike-machine systemd[1]: Started Jackett Daemon.
Feb 14 11:53:34 mike-machine systemd[1]: jackett.service: Main process exited, code=exited, status=1/FAILURE
Feb 14 11:53:34 mike-machine systemd[1]: jackett.service: Failed with result 'exit-code'.
Feb 14 11:53:39 mike-machine systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
Feb 14 11:53:39 mike-machine systemd[1]: jackett.service: Scheduled restart job, restart counter is at 54290.
Feb 14 11:53:39 mike-machine systemd[1]: Stopped Jackett Daemon.
Feb 14 11:53:39 mike-machine systemd[1]: Started Jackett Daemon.
Feb 14 11:53:39 mike-machine mono[1535]: Unhandled Exception:
Feb 14 11:53:39 mike-machine mono[1535]: System.IO.FileNotFoundException: Could not load file or assembly 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies
Feb 14 11:53:39 mike-machine mono[1535]: File name: 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null'
Feb 14 11:53:39 mike-machine mono[1535]: [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyTok
Feb 14 11:53:39 mike-machine mono[1535]: File name: 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null'
Feb 14 11:53:39 mike-machine systemd[1]: jackett.service: Main process exited, code=exited, status=1/FAILURE
Feb 14 11:53:39 mike-machine systemd[1]: jackett.service: Failed with result 'exit-code'.
Feb 14 11:53:44 mike-machine systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
Feb 14 11:53:44 mike-machine systemd[1]: jackett.service: Scheduled restart job, restart counter is at 54291.
Feb 14 11:53:44 mike-machine systemd[1]: Stopped Jackett Daemon.
Feb 14 11:53:44 mike-machine systemd[1]: Started Jackett Daemon.
Feb 14 11:53:44 mike-machine mono[1670]: Unhandled Exception:
Feb 14 11:53:44 mike-machine mono[1670]: System.IO.FileNotFoundException: Could not load file or assembly 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies
Feb 14 11:53:44 mike-machine mono[1670]: File name: 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null'
Feb 14 11:53:44 mike-machine mono[1670]: [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyTok
Feb 14 11:53:44 mike-machine mono[1670]: File name: 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null'
Feb 14 11:53:44 mike-machine systemd[1]: jackett.service: Main process exited, code=exited, status=1/FAILURE
Feb 14 11:53:44 mike-machine systemd[1]: jackett.service: Failed with result 'exit-code'.
Feb 14 11:53:49 mike-machine systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
Feb 14 11:53:49 mike-machine systemd[1]: jackett.service: Scheduled restart job, restart counter is at 54292.
Feb 14 11:53:49 mike-machine systemd[1]: Stopped Jackett Daemon.
Feb 14 11:53:50 mike-machine systemd[1]: Started Jackett Daemon.
Feb 14 11:53:50 mike-machine mono[1809]: Unhandled Exception:
Feb 14 11:53:50 mike-machine mono[1809]: System.IO.FileNotFoundException: Could not load file or assembly 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies
Feb 14 11:53:50 mike-machine mono[1809]: File name: 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null'
Feb 14 11:53:50 mike-machine mono[1809]: [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyTok
Feb 14 11:53:50 mike-machine mono[1809]: File name: 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null'
Feb 14 11:53:50 mike-machine systemd[1]: jackett.service: Main process exited, code=exited, status=1/FAILURE
Feb 14 11:53:50 mike-machine systemd[1]: jackett.service: Failed with result 'exit-code'.
Feb 14 11:53:55 mike-machine systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
Feb 14 11:53:55 mike-machine systemd[1]: jackett.service: Scheduled restart job, restart counter is at 54293.
Feb 14 11:53:55 mike-machine systemd[1]: Stopped Jackett Daemon.
Feb 14 11:53:55 mike-machine systemd[1]: Started Jackett Daemon.
Feb 14 11:53:55 mike-machine mono[1955]: Unhandled Exception:
Feb 14 11:53:55 mike-machine mono[1955]: System.IO.FileNotFoundException: Could not load file or assembly 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies
Feb 14 11:53:55 mike-machine mono[1955]: File name: 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null'
Feb 14 11:53:55 mike-machine mono[1955]: [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyTok
Feb 14 11:53:55 mike-machine mono[1955]: File name: 'Jackett.Common, Version=0.10.716.0, Culture=neutral, PublicKeyToken=null'
Feb 14 11:53:55 mike-machine systemd[1]: jackett.service: Main process exited, code=exited, status=1/FAILURE
Feb 14 11:53:55 mike-machine systemd[1]: jackett.service: Failed with result 'exit-code'.
Feb 14 11:54:00 mike-machine systemd[1]: jackett.service: Service hold-off time over, scheduling restart.`

Thanks,
Miguel de Carvalho

**Comment by flightlevel** [comment]
A file is missing `FileNotFoundException`
Double check your permissions and then download the latest version and copy the binaries over

**Comment by MiguelNdeCarvalho** [comment]
Really thanks mate
