### ISSUE TITLE
cpasbien website tracker still not working properly. The domain have changed?

### ISSUE THREAD

**Issue by Doduf57** [Jackett/Jackett#4692]
This issue is not a duplicate. I have the same problem. cpasbien website tracker still not working properly. The domain have changed?

_Originally posted by @Doduf57 in https://github.com/Jackett/Jackett/issues/4683#issuecomment-464163759_

**Comment by garfield69** [comment]
use your jackett desktop wrench icon to edit the cpabein config and change the site link if it is not already set, to https://www.cpasbiens.cz/

works for me.

if you are having problems with this site domain, then 
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by Doduf57** [comment]
Thanks for your reply. I did two screenshots that might be sufficient to understand the problem. If not, I will found the logs in the docker container when I have time. 
<img width="1433" alt="screenshot 2019-02-15 at 20 35 38" src="https://user-images.githubusercontent.com/14351464/52880172-88e7eb80-3161-11e9-805e-a1f1068dcd21.png">
<img width="562" alt="screenshot 2019-02-15 at 20 34 35" src="https://user-images.githubusercontent.com/14351464/52880177-8d140900-3161-11e9-8f6d-ef6f1cec24b6.png">

**Comment by garfield69** [comment]
Ahh. Well the error message explains everything.
You will have to wait until cloudflare lifts the blacklisting of your IP block of addresses, which will happen some time after the DDOS attacks dies down. 
Nothing we can currently do from within Jackett to help you with this, Sorry.
A possible work around is if you are using a VPN where you can select a different IP region, and find one that is not currently blacklisted.

**Comment by Doduf57** [comment]
Thanks for your help, I will try to change my IP or use a VPN/Proxy. Jackett is the best open source software I have found, it help a lot.
