### ISSUE TITLE
[iptorrents] Exception (iptorrents): The remote name could not be resolved: 'www.iptorrents.bit': An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by Dialatech2303** [Jackett/Jackett#4718]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  Latest version aswell
[log.txt](https://github.com/Jackett/Jackett/files/2877398/log.txt)

http://www.iptorrents.bit/t works fine when i put it in my browser also this is in the Json file. I have attached that file aswell. I have rename the extension to log instead of json so you can look at it.
[iptorrents.log](https://github.com/Jackett/Jackett/files/2877404/iptorrents.log)

**Mono version** (if not using Windows):  

-------------------------------

**Comment by c0nsaw** [comment]
I have this issue also

**Comment by garfield69** [comment]
That's because www.iptorrents.bit is no longer valid. Try another of iptorrents addresses.
