### ISSUE TITLE
Request: Reduce thread number / memory usage

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#4720]
I'm running Jackett in a seedbox with low resources and I'm limiting the amount of memory for Jackett with the environment var MONO_GC_PARAMS=max-heap-size=128m

This is working fine most of the time, but when I **search all** manually (with 10 indexer) the process crash or shows ugly exceptions. I'm sure the errors are because of the memory restrictions. Fine.

If I remove the memory restrictions and I launch  **search all** manually (with 20 indexer) I can see exceptions and some indexers stop working.

Why is Jackett consuming so many memory and opening so many threads? Could you limit the number of concurrent threads (e.g. open a thread pool with 5 threads for search)?

I know a lot of people running this software in low budget seedboxes. This software is consuming more memory than sonarr + torrent client + ftp + openvpn combined.

**Jackett version**:  0.10.790.0
**Mono version** Mono JIT compiler version 5.18.0.240

**Comment by flightlevel** [comment]
I run Jackett on the smallest Kimsufi with heaps of other containers and it runs without issue...

Can you try the .NET Core version of Jackett to see if it makes a difference
Download the applicable artifact from here https://ci.appveyor.com/project/Jackett/jackett/builds/22536593/job/nj28w64v2owfu7vc/artifacts that starts with `Experimental` and from a terminal run `./jackett` to start

**Comment by ngosang** [comment]
I tested your artifact, these are the results. I still think the RAM values are too high for this app, compared to other mono apps like Sonarr. See also the results after removing indexers definitions.
NOTE: Is hard to measure RAM in Linux, results are approximately but close to real values.

## ArmX64, Ubuntu 18.04.2 LTS, All definitions

1. Before starting jackett (baseline)
=> Used RAM 487Mb
2. After stating Jackett
=> Used RAM 657Mb (**Jacket 170Mb aprox.**)
=> Jackett thread count 17
3. After searching "harry" in 6 indexers (using torznab / all / API)
=> Used RAM 821Mb (**Jacket 334Mb aprox.**)
=> Jackett thread count 21
=> **Jackett thread count (while performing search) 40**
4. After searching "harry potter" in 6 indexers (using torznab / all / API)
=> Used RAM 829Mb (**Jacket 342Mb aprox.**)
=> Jackett thread count 21
5. After closing Jackett
=> Used RAM 501Mb (close to baseline 487Mb)


## After removing not used indexers definitions. Definitions:
```
02-24 11:32:25 Info Loading Cardigann definition /root/tmp/Jackett/Definitions/thepiratebay.yml 
02-24 11:32:25 Info Loading Cardigann definition /root/tmp/Jackett/Definitions/elitetorrent-biz.yml 
02-24 11:32:25 Info Loading Cardigann definition /root/tmp/Jackett/Definitions/monova.yml 
02-24 11:32:25 Info Loading Cardigann definition /root/tmp/Jackett/Definitions/btbit.yml 
02-24 11:32:25 Info Loading Cardigann definition /root/tmp/Jackett/Definitions/torrentz2.yml 
02-24 11:32:25 Info Loading Cardigann definition /root/tmp/Jackett/Definitions/eztv.yml 
```
2. After stating Jackett
=> **Jacket 44Mb aprox.** (compared to 170Mb with all indexers)
3. After searching "harry" in 6 indexers (using torznab / all / API)
=> **Jacket 184Mb aprox.** (compared to 334Mb with all indexers)
3. After searching "harry potter" in 6 indexers (using torznab / all / API)
=> **Jacket 193Mb aprox.** (compared to 342Mb with all indexers)

One way of reduce memory usage to half is to not load in memory unused definitions. Most users will use 1-10 indexers. No need to have hundreds in memory...

**Comment by d1slact0r** [comment]
Good catch! Still after switching to netcore I do have exessive ram use. Altough I use docker so I can not delete these things, there should be another option.. @flightlevel ?

**Comment by flightlevel** [comment]
I think the idea has merit, however its not small piece of work. I simply don't have the time, If the community wants these sort of changes, we need more contributors... Help wanted

**Comment by edjalmobf** [comment]
@ngosang can you say if after updates **v0.11.224**, that reduces the cache size from a 7 day retention to just 1 hour, and the **v0.11.230**, that enable workstation garbage collection, got better?

Just reporting because I think these is a similar issues: https://github.com/Jackett/Jackett/issues/4966

**Comment by ngosang** [comment]
These are the results with latest version.

Old (v0.10.830 23/02/2019) vs **New (v0.11.256.0 28/04/2019)**
1. After stating Jackett
=> 170Mb vs **156Mb** aprox.
2. After searching "harry" in 6 indexers (using torznab / all / API)
=> 334Mb vs **282Mb** aprox.
3. After searching "harry potter" in 6 indexers (using torznab / all / API)
=> 342Mb vs **294** aprox.

I see a reduction of 48Mb in a normal use case. This is a nice improvement (17%), but we should keep the work towards memory reduction. Keep this open, thank you all.

**Comment by flightlevel** [comment]
Focus is on the standalone version of Jackett not Mono. The latest pre-release has further improvements again for the standalone version.
Also, the .NET team are reporting much lower memory use for .NET Core 3 https://devblogs.microsoft.com/dotnet/announcing-net-core-3-preview-4/  (about half way down the page) which should feed into Jackett once its released

**Comment by ngosang** [comment]
@garfield69 I think this is not a problem in latest versions with -Net Core version. You can close.
