### ISSUE TITLE
[Torrents.csv] dont work with radarr

### ISSUE THREAD

**Issue by angelss197200** [Jackett/Jackett#4727]
Torrents.csv works perfectly with jackett, but with radarr keeps saying "No results were returned from your indexer, please check your settings."

 Jackett Version 0.10.796.0

**Comment by celi28** [comment]
This is a radarr issue. Not a jackett one.
Also, if you want assistance, please provide more details about your current configuration.

**Comment by angelss197200** [comment]
i have 42 indexer configured in radarr, all the same way, but Torrents.csv is the only one who doesnt work.

what kind of details should i provide?

**Comment by garfield69** [comment]
Try the latest Jackett 0.10.814, it include an update to torrents.csv that may resolve your radarr issue.
If it does not work, re-examine the available categories in the jackett dashboard config for torrents.csv and make sure that radarr has the same categories defined in its corresponding indexer. (you may need to turn on advanced settings to see the categories there).

**Comment by angelss197200** [comment]
its fixed 
thanks
