### ISSUE TITLE
speed CD Error

### ISSUE THREAD

**Issue by seanvree** [Jackett/Jackett#473]
Configuration failed: Speed.cd Javascript is disabled or is not supported by your browser. Please upgrade your browser or enable Javascript to navigate the interface properly. Not seanvree? Identify Your Account Log in as: seanvree We could not recognize your account properly. Mind if we double check that? It's for your own security. Security Question Question: middle name Secret Answer:   Password:   Continue Request a login token by Email Email me a link to reset my IP lock settings. s******e@hotmail.com Type the full email Address:   Continue $(".togNext").on("click",function(){ $(".infoBody").not($(this).next()).slideUp();$(this).next().slideDown(500)}); Login

**Comment by d2dyno** [comment]
Sounds like geo-locking is enabled. Disable it through: http://speed.cd/user/#/Security/Geo

**Comment by seanvree** [comment]
close, looks like I needed to update my IP address. 

Thanks,
