### ISSUE TITLE
Specify allowed subnets to access the interface?

### ISSUE THREAD

**Issue by wellloaded** [Jackett/Jackett#4734]
How do I specify what IP/Subnets can access the Jackett interface?

It seems like only LAN connections are possible, I would like to be able to use jackett via a VPN connected remote site.

P.S. I do have the "external access" flag set

Thanks.

**Comment by kaso17** [comment]
jackett doesn't support any access restriction based on the client IP.
The external flag only controls if jackett is listening on any or just the localhost IP.
If you can access it from another PC via LAN then something else is blocking access to jackett.
