### ISSUE TITLE
[theshinning] Login failed: No form found on https://theshinning.me/login.php using form selector form (Config)

### ISSUE THREAD

**Issue by whitesnakeftw** [Jackett/Jackett#4735]
As the title says, login fails

Interface is quite different (Blutopia-like) than that on the old domain

**Comment by garfield69** [comment]
seems with the move from .org to .me there has been a change in server engine too...

I'm concerned about the message that states that you cant use old data and must register again....
![image](https://user-images.githubusercontent.com/6933240/53117319-83e6ca00-35af-11e9-81d7-5b6f9cdb2298.png)
Just want to be sure that this is the official site... 
are you a user from the old .org site, and can you login to the .me via the browser directly ok?

I don't have a login so I can assist. If you send an invite to garfieldsixtynine @ gmail.com I will have a go at amending the indexer for the new domain.

**Comment by whitesnakeftw** [comment]
@garfield69 Yes, that's because apparently they lost the user database and everybody had to sign up again (me included) so they're basically starting from scratch.

The old .org website can't be reached anymore, but more importantly I got this new domain from an email they sent to all the users of the old website, so it's 100% safe to assume this is the new official website.

Also registrations are currently open: https://theshinning.me/register/null

:)

**Comment by garfield69** [comment]
registration and login successful. I'll start adjusting the indexer for the new domain shortly.

**Comment by garfield69** [comment]
try out Jackett v0.10.804
