### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://ww1.yggtorrent.is/ using form selector form[action$=

### ISSUE THREAD

**Issue by 3th3r** [Jackett/Jackett#4736]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

latest version of linuxserver/jackett: can't find a version
Same for mono, can't any version on docker hub, **Mono version** (if not using Windows):  

-------------------------------

**Comment by xfouloux** [comment]
see #4652

**Comment by 3th3r** [comment]
Thank's a lot, very quick answer.
But the problem was the linuxserver docker image, it was on the 0.8.XX version. I've install directly the latest version and it works like a charm ! GJ guys +++

This isn't the first time I've some big problem with the linserver team repo. Next time, I will not use their images and bypass docker.

Thank's again,
Regards

**Comment by xfouloux** [comment]
or you can use mine for example : https://hub.docker.com/r/sclemenceau/docker-jackett

it can download the latest pre-build on each reboot
