### ISSUE TITLE
T411 support?

### ISSUE THREAD

**Issue by AnilDaoud** [Jackett/Jackett#474]
I see you used to support t411 (https://github.com/Jackett/Jackett/blob/v0.6.45/src/Jackett/Indexers/T411.cs)
Any particular reason it was removed?

I see another working proxy exists (https://github.com/KiLMaN/T411-Torznab) but would rather stick to jackett

Thanks, AD

**Comment by JigSawFr** [comment]
Public trackers are not currently supported anymore.

**Comment by julien-blanchon** [comment]
Please, t411 is a semi-private tracker
