### ISSUE TITLE
[yggtorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by benumb** [Jackett/Jackett#4741]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.795.0
**Mono version** (if not using Windows):  dont know

-------------------------------
[log.txt.20190221.00004.txt](https://github.com/Jackett/Jackett/files/2889250/log.txt.20190221.00004.txt)
[log.txt.20190221.00006.txt](https://github.com/Jackett/Jackett/files/2889251/log.txt.20190221.00006.txt)
[log.txt.20190221.00003.txt](https://github.com/Jackett/Jackett/files/2889252/log.txt.20190221.00003.txt)
[log.txt](https://github.com/Jackett/Jackett/files/2889253/log.txt)
[log.txt.20190221.00007.txt](https://github.com/Jackett/Jackett/files/2889254/log.txt.20190221.00007.txt)
[log.txt.20190221.00005.txt](https://github.com/Jackett/Jackett/files/2889255/log.txt.20190221.00005.txt)

**Comment by garfield69** [comment]
the log you provided shows that the ygg indexer you were using cannot identify the ygg result rows.
this is due to your indexer being out of date, 0.10.795

Upgrade to the latest Jackett v0.10.804 or newer to pick up the updated ygg indexer

**Comment by benumb** [comment]
Yes thank you and sorry for this mistake.

Le ven. 22 févr. 2019 à 04:30, garfield69 <notifications@github.com> a
écrit :

**Comment by garfield69** [comment]
no problem. glad it was a simple issue for you to fix :-)
