### ISSUE TITLE
[HDBits] Add API Key Functionality

### ISSUE THREAD

**Issue by ghost** [Jackett/Jackett#4742]
Currently HDBits functionality requires username/password which breaks if using 2FA.  HDBits API allows access using an API Key which would allow API access even while 2FA is in use.

Sonarr / Radarr have already implemented this feature.

**Comment by kaso17** [comment]
AGAIK non of the current jackett developers have access to HDBits.
Unless you can provide an invite or are aware of any recruitment threads this is probably not going to be fixed anytime soon.

**Comment by RoloSoze** [comment]
Closed with #6980
