### ISSUE TITLE
[torrentz2] Exception (torrentz2): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /spksrc/spk/mono/work-88f6281-6.1/mono-5.8.0.108/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by bretonesf** [Jackett/Jackett#4746]
Hello everyone,

This is my first post on Github, so please apologize if I'm doing something in a bad way.

I'm trying to set jackett in the following setup : 

NAS : DS213
Sickchill installed
Jackett version : dashboard indicates 0.10.819.0, DSM indicates 0.8.490.6 
Mono version : DSM indicates 5.8.0.108.11

I'm trying to set several indexers in Jackett, using the torznab feed in Sickchill, donwloading with Synology DS native app.

Some indexers are working great (ie : The pirate bay), but some others don't : tried 1337x, kickasstorrent, torrentz2 and when I test it, I have the same error : 

[torrentz2] Exception (torrentz2): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /spksrc/spk/mono/work-88f6281-6.1/mono-5.8.0.108/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

Already tried the fix from #4433, but for me nothing changed. Any idea?

Thx

**Comment by kaso17** [comment]
please post the output of
`curl -vvv https://torrentz2.eu/` and `openssl s_client -connect torrentz2.eu`

**Comment by bretonesf** [comment]
Sorry, kind of newbie, I'm learning step by step.

Being on synology, where should I do these 2 commands? Through Putty, accessing the NAS?

**Comment by kaso17** [comment]
yes, via SSH/command line

**Comment by bretonesf** [comment]
Curl : 

* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL: no alternative certificate subject name matches target host name 'torrent                                                                                                                                                             z2.eu'
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (51) SSL: no alternative certificate subject name matches target host name                                                                                                                                                              'torrentz2.eu'

Openssl : 

no port defined
usage: s_client args

**Comment by kaso17** [comment]
sorry, it must be
`openssl s_client -connect torrentz2.eu:443`

**Comment by bretonesf** [comment]
Here it is : 

CONNECTED(00000004)
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTru                                                                                                                                                             st External CA Root
verify return:1
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN                                                                                                                                                              = USERTrust RSA Certification Authority
verify return:1
depth=1 C = FR, ST = Paris, L = Paris, O = Gandi, CN = Gandi Standard SSL CA 2
verify return:1
depth=0 OU = Domain Control Validated, OU = Gandi Standard SSL, CN = onlinefairp                                                                                                                                                             lay.info
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=Gandi Standard SSL/CN=onlinefairplay.info
   i:/C=FR/ST=Paris/L=Paris/O=Gandi/CN=Gandi Standard SSL CA 2
 1 s:/C=FR/ST=Paris/L=Paris/O=Gandi/CN=Gandi Standard SSL CA 2
   i:/C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA                                                                                                                                                              Certification Authority
 2 s:/C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA                                                                                                                                                              Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External C                                                                                                                                                             A Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIHEjCCBfqgAwIBAgIRALFfG8d2wlsFwQtbuLGr3KswDQYJKoZIhvcNAQELBQAw
XzELMAkGA1UEBhMCRlIxDjAMBgNVBAgTBVBhcmlzMQ4wDAYDVQQHEwVQYXJpczEO
MAwGA1UEChMFR2FuZGkxIDAeBgNVBAMTF0dhbmRpIFN0YW5kYXJkIFNTTCBDQSAy
MB4XDTE5MDEyNTAwMDAwMFoXDTIwMDMyMTIzNTk1OVowXjEhMB8GA1UECxMYRG9t
YWluIENvbnRyb2wgVmFsaWRhdGVkMRswGQYDVQQLExJHYW5kaSBTdGFuZGFyZCBT
U0wxHDAaBgNVBAMTE29ubGluZWZhaXJwbGF5LmluZm8wggIiMA0GCSqGSIb3DQEB
AQUAA4ICDwAwggIKAoICAQDlThFO6rohzRBvDkKYGd/+clkRHgaD0nBAYhuU16Xu
FiqLPJ0m1owpGarH6cFZZbTaUJefc+2b/uwARE6z9WHvJePyMvzlCBK0ObRRgiUN
f5hNdCsDE9P2sfBFhyw19N7t7SIQHUFD4Od/1Qv1PDLRrUGxZoAYz0Wi/QRIsVAD
ZYkmBvQ2s8PcXqwkhM08hU86F5+meUF5LeDHeNYLX40O6def8VhRgTu8/KY9vxM8
DeiGLm9VsVqYa/GOlIJlnTvQmPELEcE8fFAM4cY+HaAY8wing1FVjmk193nXXU3G
wWiG5eErFFhFV1jTGazwIREGXFkbWHJZDbcTYihMKMhOwu1aTFNnIyLFFWGpmj1B
/ssHoNyf3GOlnrL001XPnfIFd1wd3Mc3Zn27gwG97yEDP+F4a0BRaIjBZ5kpd/Zn
hccwq/UCwzWLF7L1LupN16RA0G0XKHO8iVUNkWC0X4rbc+VN3JJje7EnDgS8b7ZF
MHaBDklc7syS1btMCKKhnnumN3tAYBELTQ081JlKjD7rCkYkX0TCDXI9uh9yXo5D
51d0ouMeMAcj6Mzm2iD7upR38sJoXPxYUpxT6wkbLMkQOE3ewUQ/WFtjH9A/YNCm
nKEJllHkBqUkLWIyikP4rsAn4VwVKqkqHmN4KnDE5mFe1C97r/YCjCJt8N0kXHaD
7QIDAQABo4ICyDCCAsQwHwYDVR0jBBgwFoAUs5Cn2MmvTs1hPJ98rV1/Qf1pMOow
HQYDVR0OBBYEFNJs2y8ns1GsmosCUzqsPz3cXy1oMA4GA1UdDwEB/wQEAwIFoDAM
BgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBLBgNV
HSAERDBCMDYGCysGAQQBsjEBAgIaMCcwJQYIKwYBBQUHAgEWGWh0dHBzOi8vY3Bz
LnVzZXJ0cnVzdC5jb20wCAYGZ4EMAQIBMEEGA1UdHwQ6MDgwNqA0oDKGMGh0dHA6
Ly9jcmwudXNlcnRydXN0LmNvbS9HYW5kaVN0YW5kYXJkU1NMQ0EyLmNybDBzBggr
BgEFBQcBAQRnMGUwPAYIKwYBBQUHMAKGMGh0dHA6Ly9jcnQudXNlcnRydXN0LmNv
bS9HYW5kaVN0YW5kYXJkU1NMQ0EyLmNydDAlBggrBgEFBQcwAYYZaHR0cDovL29j
c3AudXNlcnRydXN0LmNvbTA3BgNVHREEMDAughNvbmxpbmVmYWlycGxheS5pbmZv
ghd3d3cub25saW5lZmFpcnBsYXkuaW5mbzCCAQUGCisGAQQB1nkCBAIEgfYEgfMA
8QB2ALvZ37wfinG1k5Qjl6qSe0c4V5UKq1LoGpCWZDaOHtGFAAABaIVA7LMAAAQD
AEcwRQIhAP/TyIpdKrRTIS/ur0qHr2383h1mA1b/5WQQK/ek3pHWAiBePLGheP3Z
gmf6W6QbGc7+5Dx+9CMfUs1XwoLAZ37vrwB3AF6nc/nfVsDntTZIfdBJ4DJ6kZoM
hKESEoQYdZaBcUVYAAABaIVA7PwAAAQDAEgwRgIhAIj7A+KOSkpam+Z4lW7XU2Ji
2oYwNPUm2NFPOzj0KY1CAiEAvwK7OEksKsi5treLgYdZAAg/3TXHiesYdUlD4cgy
AE8wDQYJKoZIhvcNAQELBQADggEBAIG1kniZS5OVljzCBD8aQwwfaJgRajgo/u9k
/tOT2+8V1+Iqg8qq6vQ8Q+Wzc9FNbtauMDD4KQnO2tqMX+RdC/180/IqYiLMf129
3OGDqlhssWnnXCRSa3dgBuKO1qxOUWHvKQAiULRFHD/1AQW/cPUtGkt2VwVWwDgo
lRFI9BxpJtzjuQTmNDxNy7M89k8sEfFxEV3K//S2JeUnr++oTd53M0rgLOvoT0W6
4pJvUO1GUQiXTqJWgwyYoTzLd8ifBQAPflG27GGHVG2j4hmwLrzrcxxprKHTijDT
M46GLTsMXf/gDkAed6Aes6z8UBHrXxExgXEFQZjKZnLiKJAMMe4=
-----END CERTIFICATE-----
subject=/OU=Domain Control Validated/OU=Gandi Standard SSL/CN=onlinefairplay.inf                                                                                                                                                             o
issuer=/C=FR/ST=Paris/L=Paris/O=Gandi/CN=Gandi Standard SSL CA 2
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 5687 bytes and written 419 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 6ED24334E639B0A3C80A464D47E5D2AC8651A8EC8037D472A929A01842219FE1
    Session-ID-ctx:
    Master-Key: F74D95FD5A143EF28B2EED60EC855615CEFD15A09CCE4B732D2AE5A586A03E82                                                                                                                                                             F570738169BFB40050A136FC5FEECDC9
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - d6 d8 8c b3 9b dd fb a8-7e e6 08 1c ab 86 51 0e   ........~.....Q.
    0010 - d9 6d 11 25 de 4a 97 a8-23 f5 ab 66 ed cc 7b a6   .m.%.J..#..f..{.
    0020 - c3 25 c9 4b d8 f5 c4 26-2d 09 fd 70 f8 58 df 3d   .%.K...&-..p.X.=
    0030 - ec a3 83 51 83 56 fa c9-a6 ef 86 b2 6b e3 88 bb   ...Q.V......k...
    0040 - 90 35 b0 e0 d5 2a 0a b5-f7 37 08 0c e3 40 59 ab   .5...*...7...@Y.
    0050 - f4 ac 5c 3b 28 db c4 99-4d b7 b4 74 e3 c2 58 d4   ..\;(...M..t..X.
    0060 - d2 8f e2 ed 39 8c dc 65-0f 0f 0b 0c b4 e9 6d ef   ....9..e......m.
    0070 - e3 91 eb c5 f3 f6 59 61-82 46 4e ee aa 5f 98 2b   ......Ya.FN.._.+
    0080 - 79 13 19 60 7b 61 9d 45-95 e8 21 b8 3a bd 95 34   y..`{a.E..!.:..4
    0090 - d9 19 3f 0b 92 cf de 5e-67 16 4e 9f 41 ab b3 8b   ..?....^g.N.A...
    00a0 - 9a a4 fe 8d 05 99 d1 0f-1f 84 15 73 46 f6 65 88   ...........sF.e.
    00b0 - 8b d6 bf ed c7 a2 18 17-5d 2e 04 9e 02 0b ac c1   ........].......

    Start Time: 1550852439
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---

**Comment by kaso17** [comment]
Your ISP is blocking the site.
See https://onlinefairplay.info/

**Comment by bretonesf** [comment]
If I access directly the websites (1337x, torrentz2, kickasstorrent), I have no restriction from my ISP and I can download the .torrent file and the whole file with client.

**Comment by kaso17** [comment]
then your jackett instance is using some other internet connection. Maybe you're using some king of VPN/proxy which only works with your browser (if it's running on the same machine).
