### ISSUE TITLE
Trackers that return no results with search all cannot be added to e.g. Sonarr

### ISSUE THREAD

**Issue by Col666** [Jackett/Jackett#4748]
**Jackett version**:  0.10.198.0

-------------------------------

Certain trackers e.g. thepiratebay, ettv return no results when a search all is performed but return results with a search for e.g. mkv.

Sonarr and others use search all to test if the indexer is working. No results are returned and the indexer cannot be added.

**Comment by kaso17** [comment]
upgrade your jackett version and try again, post a log if it's still not working

**Comment by Col666** [comment]
Working.
