### ISSUE TITLE
Torrentday - torrentpotato, remote server returned bad request

### ISSUE THREAD

**Issue by AnilDaoud** [Jackett/Jackett#475]
this happened on 2 torrents so far, on torrentpotato only, never with sonarr. here is the log

so far other torrents on td have been fine

> 08-27 19:30:19 Error Error downloading torrentday https://tdonline.org/download.php/1095875/Taken 3 (2014) BRRip x265 HEVC HQ-CPG.torrent System.Exception: Remote server returned BadRequest
>   at Jackett.Indexers.BaseIndexer+<Download>c__async3.MoveNext () <0x5bc86e8 + 0x00217> in <filename unknown>:0 
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x18ab6f0 + 0x00035> in <filename unknown>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x18a8f10 + 0x000b7> in <filename unknown>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x18a8e70 + 0x00087> in <filename unknown>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x18a8e20 + 0x0003f> in <filename unknown>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x18a92a0 + 0x00024> in <filename unknown>:0 
>   at Jackett.Controllers.DownloadController+<Download>c__async0.MoveNext () <0x5bc7578 + 0x0039f> in <filename unknown>:0 
> 
> 08-27 19:26:20 Error Error downloading torrentday https://tdonline.org/download.php/1057264/The Hunger Games Mockingjay Part 1 (2014) BDRip x265 HEVC HQ-CPG.torrent System.Exception: Remote server returned BadRequest
>   at Jackett.Indexers.BaseIndexer+<Download>c__async3.MoveNext () <0x5bc86e8 + 0x00217> in <filename unknown>:0 
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x18ab6f0 + 0x00035> in <filename unknown>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x18a8f10 + 0x000b7> in <filename unknown>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x18a8e70 + 0x00087> in <filename unknown>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x18a8e20 + 0x0003f> in <filename unknown>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x18a92a0 + 0x00024> in <filename unknown>:0 
>   at Jackett.Controllers.DownloadController+<Download>c__async0.MoveNext () <0x5bc7578 + 0x0039f> in <filename unknown>:0

**Comment by AnilDaoud** [comment]
Hi let me know if and how I can help investigate!
Thanks

**Comment by JigSawFr** [comment]
Did you tried with latest Jackett version ?

**Comment by AnilDaoud** [comment]
this is with Jackett Version 0.7.512.0

`2016-11-03 22:32:44.1935 Info ApiControllerActionInvoker InvokeActionAsync Action='Download(indexerID=torrentday, path=aHR0cHM6Ly90ZG9ubGluZS5vcmcvZG93bmxvYWQucGhwLzE5NjI1NzcvSW5kZXBlbmRlbmNlIERheSBSZXN1cmdlbmNlIDIwMTYgSEVWQyBEM0ZpTDNSIChpc28pLnRvcnJlbnQ1, apikey=XXX, file=Independence Day Resurgence 2016 BluRay 1080p DD5 1 x265-D3FiL3R.torrent)' 
2016-11-03 22:32:44.1950 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Download(indexerID=torrentday, path=aHR0cHM6Ly90ZG9ubGluZS5vcmcvZG93bmxvYWQucGhwLzE5NjI1NzcvSW5kZXBlbmRlbmNlIERheSBSZXN1cmdlbmNlIDIwMTYgSEVWQyBEM0ZpTDNSIChpc28pLnRvcnJlbnQ1, apikey=XXX, file=Independence Day Resurgence 2016 BluRay 1080p DD5 1 x265-D3FiL3R.torrent)' 
2016-11-03 22:32:44.2082 Debug UnixLibCurlWebClient:GetBytes(Url:https://tdonline.org/download.php/1962577/Independence Day Resurgence 2016 HEVC D3FiL3R (iso).torrent) 
2016-11-03 22:32:44.3730 Debug UnixLibCurlWebClient:GetBytes Returning BadRequest => 177 bytes 
2016-11-03 22:32:44.3882 Error Error downloading torrentday https://tdonline.org/download.php/1962577/Independence Day Resurgence 2016 HEVC D3FiL3R (iso).torrent System.Exception: Remote server returned BadRequest`

**Comment by kaso17** [comment]
Can you download the files manually (without jackett)? maybe your account is parked or your download permissions got revoked.

**Comment by AnilDaoud** [comment]
Yep as per initial report, this happens on a handful of torrent only, and only from couchpotato.
Downloading the exact same torrent manually works fine.

**Comment by kaso17** [comment]
With the next release Jackett should dump the response in case of an error. Please post an new log then. Hopefully that will help.

**Comment by AnilDaoud** [comment]
Nov 07, 2016 10:35:37 PM	Error	
Error downloading torrentday https://torrentday.it/download.php/1995551/Imperium 2016 HEVC D3FiL3R (iso).torrent
Nov 07, 2016 10:35:37 PM	Error	
Failed download response:
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>
Nov 07, 2016 10:32:48 PM	Info

**Comment by kaso17** [comment]
Ok, I'll add some code to dump the request with the next version too.

**Comment by AnilDaoud** [comment]
Still have the same issue:

> Dec 11, 2016 09:30:18 PM	Error	
> Error downloading torrentday https://torrentday.it/download.php/1995622/Finding Dory 2016 HEVC BR D3FiL3R (iso).torrent
> Dec 11, 2016 09:30:18 PM	Error	
> Failed download response:
> <html>
> <head><title>400 Bad Request</title></head>
> <body bgcolor="white">
> <center><h1>400 Bad Request</h1></center>
> <hr><center>cloudflare-nginx</center>
> </body>
> </html>
> Dec 11, 2016 09:29:59 PM	Error	
> Error downloading torrentday https://torrentday.it/download.php/1995551/Imperium 2016 HEVC D3FiL3R (iso).torrent
> Dec 11, 2016 09:29:59 PM	Error	
> Failed download response:
> <html>
> <head><title>400 Bad Request</title></head>
> <body bgcolor="white">
> <center><h1>400 Bad Request</h1></center>
> <hr><center>cloudflare-nginx</center>
> </body>
> </html>

**Comment by kaso17** [comment]
should be fixed with 1050157546c40915c1c0776cc0a4ace2d0c3682e
