### ISSUE TITLE
Run as a service on CentOS6?

### ISSUE THREAD

**Issue by piperde** [Jackett/Jackett#476]
My apologies if this has been covered or should be obvious - I spent about an hour searching and couldn't find the answer.

I have a CentOS6 VM that I use to run Jackett, Headphones, Plex, etc.  I've taken a stab at using an init.d script to run Jackett but using the ps command I can see that the process either never starts or ends very soon after starting.

Is there a proper way to run Jackett automatically as a service?  Right now I have to keep a session logged into the VM running "mono JacketConsole.exe"

Thanks in advance.

**Comment by betamax2021** [comment]
For a temporary fix, use screen.  "yum -y install screen" then your command would be "screen mono JacketConsole.exe" then CTRL+A+D  releases you from the screen to let it run in the background. 

I personally use Debian based distros, Centos is based on redhat. My experience is very slim in that area. This tutorial might be of assistance to you. [LINK](https://blog.hazrulnizam.com/create-init-script-centos-6/)

**Comment by timelf123** [comment]
Screen will run the process in the background but will not restart it if it fails/crashes

**Comment by piperde** [comment]
Thanks for the responses.

Through trial-and-error I was able to get an init script to work with screen and Jackett. Service control is somewhat non-existent at the moment (is, getting status of the service and stopping the service) but that's another task for another day.
