### ISSUE TITLE
RSS Links are invalid but GUI links are Working

### ISSUE THREAD

**Issue by bnevets27** [Jackett/Jackett#4760]
I wanted to add a jackett RSS feed into yarss2/deluge. I noticed it wouldn't pull the torrent from the RSS feed.

Looking at the feed in web browser/chrome I tried a link from the feed. For example

`https://xxxxxxxxxxxxxx/jackett/dl/racing4everyone/?jackett_apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&amp;path=Q2ZESjhPTTdsSXA5V1oxSnNzQnJJbEpXM0VSMi1Xdy1qbFpHQTNYT3hra0htblk1T2NfUjI0SERDQ3RCeWc5amE1SVNPT2ttZmt5d2hqZlVFWmZsc29ZY0NUVkJSdC10Z2wyNkRqVXVvQkdqLVVzYUVLRjB1Q0JKRk9kdTVnQXBtVFZ4MWNWUkZWWTVJNGZQTEx5UGRxQ2lRRmRXTkd4RVF5b1MwOUQ5VjlYTjJTV0ZvTEJ1SkpGanFYbXdaYXFjcUU0MWxXTkItWTBxclBLY0NHRWlsYThSVUJyNVdVV2pld0oybmtqQl9JVFBrR1lHWDF0WlY5YzUxb0I1NVFCdEU3TGlHcldQMTk4VGFqS2JfTUxFaG1xeE4zMA&amp;file=Munster+Energy+NAZCAR+Cup+Series+2019+Clash+Race+FS1+720p60+x264+English`

That link doesn't work. Grabbing the same torrent from the GUI results in a slightly different link that does work.

`https://xxxxxxxxxxxxxxxxx/jackett/dl/racing4everyone/?jackett_apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&path=Q2ZESjhPTTdsSXA5V1oxSnNzQnJJbEpXM0VTbFpqYzkyRERwRFhNUEhialJUVHFtaUFQZVpiQ2tHbFFxU2IzWnZTQVNpaXBtOFZsY0E1S1V3SDVvLWpHMG94UklCYlVFRmN2UGNLNVZORUxlejFUbmFmUlJmR3g3Y0JNTkx3dDMzR2g3dWtndWVZOXI3V1RmdEFETlJJVWM1UEZGZ3BpbklTMkt0d2Fxbmlsd1FFb045ZnQ5bUVRVV9kTGZEYkFaYUFBLVYxVC1yMmtpczZCNGxMWGZmSkMydS1tZkg4Tm9DUGNIdXRkNWQ1UkI3M0pkZnRNbWNYeWZzUGlpeUU4N0R4SmpPUQ&file=Munster+Energy+NAZCAR+Cup+Series+2019+Clash+Practice+720p+x264+English`

Notice the `amp;` between `&` and `path`

Removing `amp;` from the RSS link results in a link that works.

I am running jackett behind a reverse proxy (letsencrypt)

Running 
Jackett Version  0.10.835.0
in docker on unraid

**Comment by Zunipox** [comment]
I got the exakt same problem, been haveing it for weeks or mayby a month, it just stopped working...

**Comment by garfield69** [comment]
possibly related to #4617

**Comment by bnevets27** [comment]
Yeah it looks like what your post [here](https://github.com/Jackett/Jackett/issues/4617#issuecomment-463493525) shows with the `amp;`

But the links provided within jackett work fine....

I wonder if it has anything to do with [Google's AMP](https://www.ampproject.org/latest/blog/whats-in-an-amp-url/) If so, just another reason I hate it, it breaks everything.

**Comment by bnevets27** [comment]
What are the chances of this getting fixed? Is this an issue with the trackers or Jackett? Not trying to rush the developers but I would really like to use the RSS feeds from Jackett. Are there any more diagnostics that need to be done?

**Comment by garfield69** [comment]
Jackett 0.12.1572
