### ISSUE TITLE
CardigannIndexer (skytorrentsclone): Relogin required 

### ISSUE THREAD

**Issue by bugsyb** [Jackett/Jackett#4763]
Returns empty search result (manual search from Jackett UI). Same applies to search via API.
In logs it shows only:
`CardigannIndexer (skytorrentsclone): Relogin required `

There is no login page for skytorrents. Something is wrong and tested it on titles with results returned by the page when using directly.

Jackett Version 0.10.722.0
Sitelink: https://www.skytorrents.to/ or https://www.skytorrents.lol/

**Comment by garfield69** [comment]
I cannot replicate your issue
![image](https://user-images.githubusercontent.com/6933240/53302838-c5d18200-38c7-11e9-9a98-ae74ddc26e74.png)

I suggest upgrading to the latest Jackett v0.10.828 or newer and trying again.

If the problem persists, turn on **enhanced** logging from your dashboard, and click on the **apply server settings** button, and repeat your test and see if the logs then yield something more.

**Comment by bugsyb** [comment]
Thanks for investigating it.
Something is wrong there still (still on older version). 
For empty query as on your screen it comes up with some results.
When submitting query for, i.e. "XnView" (2nd from your output), Jackett returns no results
At the same time query via web get's plenty of results: https://www.skytorrents.lol/?query=XnView

**Comment by garfield69** [comment]
dug deeper. found the site changes the search keyword from *query* to *search*.
will post an update shortly.

**Comment by bugsyb** [comment]
@garfield69 many thanks! If all issues could be sorted that quickly! :) 
Thanks again!

**Comment by garfield69** [comment]
Try Jackett v0.10.841

**Comment by bugsyb** [comment]
Works - confirmed.
Many thanks again!
