### ISSUE TITLE
Sonarr to Jackett Issues

### ISSUE THREAD

**Issue by TBrozovich** [Jackett/Jackett#4764]
Hello,

I am trying to add trackers from Sonarr to Jackett using my API Key and the Torznab Feed. The only one that I can get to work (public) is RARBG. TPB and KAT and all others gives me a 'No results were returned' error. I know the website is working and in Jackett I can access torrents as well as directly. Can anyone help explain what I may be doing wrong or what else to try? The issue instructions says to include logs, however, I am not sure what logs to include. I just get a specific error when trying to add the tracker.

No results were returned from your indexer, please check your settings.

Thank you

**Jackett version**: 0.10.828.0 

-------------------------------

**Comment by garfield69** [comment]
use your Jackett dashboard wrench icon to examine the categories that the indexer is using, and cross reference them with the ones that you have set up in your Sonarr indexer. 
Some Jackett indexer do not use the default Sonarr categories 5030,5040 and thus some searches may fail to return results.

**Comment by garfield69** [comment]
So add to Sonarr the missing torznab categories that the Jackett indexer is using, such as 5000 etc.

**Comment by TBrozovich** [comment]
That did fix my issue! The default category was still listed but there was an additional duplicate category for HD TV and it worked. I appreciate the quick response. Cheers!
