### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on http://www.yggtorrent.gg/ using form selector 

### ISSUE THREAD

**Issue by sebguilbaud** [Jackett/Jackett#4770]
> 1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.

check done, works fine from the same system where Jackett runs

**Jackett version**:  0.10.839.0
**Mono version** (if not using Windows):  5.18.0.240

log here 
[log.txt.20190225.00113.txt](https://github.com/Jackett/Jackett/files/2899905/log.txt.20190225.00113.txt)

I found the error message in the logs :

```
<input type="password" name="pass" placeholder="Mot de passe" required="" autocomplete="off" />
<div id="ban_msg_login" style="display: none;"><center style="margin: 10px 10px; color: #ff3f3f; font-weight: bold;">Votre compte a été banni! <br><span style="font-weight: bold; font-size: 15px; color: #582a2a;">Fin du ban : <span class="ban_duration"></span></span> <a id="ban_reason" style="font-weight:bold; font-size: 13px;">Voir le motif</a></center></div>
<div id="login_msg_pass" style="display: none;"><center style="margin: 10px 10px; color: #ff3f3f; font-weight: bold;">Échec de connexion . Vérifiez vos identifiants<br></center></div>
<div id="login_msg_mail" style="display: none;"><center style="margin: 10px 10px; color: #ff3f3f; font-weight: bold;">Vous n'avez pas confirmer votre compte à l'aide du mail que nous vous avons envoyé<br></center></div>

```

I swear my account is not banned and that I can access the site, and login from the same system where Jackett runs

**Comment by garfield69** [comment]
OK. first off, what you have highlighted in the code block in your post is not an error message, but a dump of the html presented by ygg on their login page :-D 

the actual error message in the log you provided is `Login failed: No form found on http://www2.yggtorrent.gg/ `

what I suggest you do is to:
1. Use the Jackett Dashboard **delete** button (trash-bin icon) on the ygg indexer from your active list.
2. Then access the **add indexer** button and edit the config the ygg indexer afresh using the **configure** button (the wrench icon).
3. double check that the **Site Link** box has `https://www.yggtorrent.gg/` 
4. and that the **Search and download URL** box has `www2.yggtorrent.gg`
5. enter your username 
6. and password 
7. and click the **OKAY** button.

let us know how you go.

**Comment by sebguilbaud** [comment]
I know it's HTML content, I was only trying to help pinpoint the real error cause as it was in french language.

It worked with your delete/re-add method, thanks !
