### ISSUE TITLE
[torrentproject2] doesnt work with radarr

### ISSUE THREAD

**Issue by angelss197200** [Jackett/Jackett#4773]
It can be added, it says "No results were returned from your indexer, please check your settings."

 Jackett Version 0.10.839.0

**Comment by garfield69** [comment]
yes, tp2 does not support categories, so everything it returns is of category Other.
turn on advanced settings in radarr, and when you add the tp2 indexer replace all the categories with 7000
this should let you save.

**Comment by angelss197200** [comment]
its fix thanks
