### ISSUE TITLE
[Torrents.csv] Radarr says "No results found"

### ISSUE THREAD

**Issue by angelss197200** [Jackett/Jackett#4774]
Every time that Torrents.csv is added in radarr the manual search says  "No results found".

Radarrs log Says "Movie search failed: The string can't be left empty, null or consist of only whitespaces.Parametername:key"

i put the complete log but is in Spanish

**Comment by garfield69** [comment]
yes, the torrentscsv was not setting all the required torznab elements. I will submit a fix shortly.

**Comment by garfield69** [comment]
Try Jackett pre-release 0.10.842

**Comment by angelss197200** [comment]
thanks
