### ISSUE TITLE
Replace /re_replace turkish tv show Season and Episode name

### ISSUE THREAD

**Issue by kekec777** [Jackett/Jackett#4775]
Jackett version:  0.10.841.0 on Debian

Hallo forum , i hope your guys can help me with this issue i have...
Im using Sonarr with Jackett, and in Sonarr i have a turkish tv shows called Cukur
but im not getting any hit when i use TURKTORRENT(.yml)
so i read about how you can replace some words or speciale character. 
In my search for a solution about this issue , i got this far:
**I added (turktorrent.yml):
keywordsfilters:
     - name: re_replace
       args: ["S0?(\\d{1,2})E(\\d{1,2})", "$1.sezon $2.blm"]**

This will replace S01E01 to 1.sezon 1.blm
**and removed:
      filters:
        - name: andmatch**

so now i get hit and thats good :)
BUT sonarr will see this as "Unknown Series"
its look like jackett sends wrong tw shows name to sonarr:
No matching series Cukur 2 Sezon

Please help with this issue :)

**Comment by garfield69** [comment]
the Italian indexers do something similar to make them compatible with Sonarr.

Having changed the search query to find results, they then have to change the result titles back to what was queried in order for Sonarr to accept them.
so you need to change 1.sezon 1.blm back into s01e01 in the titles of the results. 
take a look at  https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/ilcorsaroblu.yml for inspiration.

**Comment by kekec777** [comment]
Hallo again @garfield69 
I have looked at link you provided but i ran into some troubles..
Is there any way to change the :
keywords: "{{.Keywords}}"
to
keywords: '"{{.Keywords}}"'

because if i set quotes on .keywords i can search proberly in turktorrent.us , but it seems that if i try to edit this line ill get an error

**Comment by garfield69** [comment]
Use the escape key `\` to prevent the quotes being parsed as part of the string build.
But if you are going to hard-code quotes then you will probably only want them used when there are keywords, so I suggest using
`      keywords: "{{if .Keywords}}\"{{.Keywords}}\"{{else}}{{end}}"`

**Comment by kekec777** [comment]
MR @garfield69 i want to shake you hand :)
that did the trick :) Now im able to automatise this turkish tv series :D
You @garfield69 is life saver :) 🥇
