### ISSUE TITLE
[Bug] Cannot configure PolishTracker

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#4780]
I get the following error message when trying to configure PolishTracker in Jackett:

An error occurred while testing this indexer
Exception (polishtracker): Found. Redirecting to /login: Found. Redirecting to /login

[log.txt](https://github.com/Jackett/Jackett/files/2910075/log.txt)

Enhanced log attached. Thanks.

**Jackett version**: Jackett Version 0.10.842.0 
**Mono version** (if not using Windows): N/A

-------------------------------

**Comment by garfield69** [comment]
the log shows `You've made too many failed attempts in a short period of time, please try again  in 4 minutes` 
did you get this from using the TEST button on the jackett dashboard?
when was the last time you actually logged in directly from your browser?
Please do so and check that your username and password are valid and that you have no outstanding alerts on your account.
then use the wrench to edit your jackett config and validate your login details

**Comment by RoloSoze** [comment]
@garfield69 I logged in to the tracker from my browser earlier today. The tracker itself works fine but I can't configure it in Jackett. I get the same result through both the Test button and the Wrench configuration button. It's actually been the case for a while, ever since they changed the tracker's design.

**Comment by RoloSoze** [comment]
@garfield69 Found the cause. PT changed their authentication mechanism recently. I used to log in with my username & password. They now require email instead of username.

It would be great if the 'username' filed in Jackett can be renamed 'email' to avoid confusion.

Thank you for your hard work!

**Comment by garfield69** [comment]
okay well done, I can easily make that adjustment.
