### ISSUE TITLE
[Bug] Cannot configure TorrentBD

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#4781]
I get the following error message when trying to configure TorrentBD in Jackett:

Exception (torrentbd): Login failed: No form found on https://www.torrentbd.com/torrent/account-login.php using form selector form[action="account-login.php"]: Parse error

Enhanced log attached. Thanks
[log.txt](https://github.com/Jackett/Jackett/files/2910112/log.txt)

**Jackett version**: Jackett Version 0.10.842.0 
**Mono version** (if not using Windows): N/A

-------------------------------

**Comment by garfield69** [comment]
could you try Jackett pre-release v0.10.849 with **enhanced logging** enabled.
use the wrench to edit indexer and click OKAY.
if it fails, please provide the complete log.txt after redacting for privacy. Thanks.

**Comment by RoloSoze** [comment]
@garfield69 Works like a charm! Thank you!
