### ISSUE TITLE
[Bug] Cannot configure BIGTorrent

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#4782]
I get the following error when trying to configure BigTorrent in Jackett:

An error occurred while testing this indexer
Found no results while trying to browse this tracker

Enhanced log attached. Thanks!
[log.txt](https://github.com/Jackett/Jackett/files/2910128/log.txt)

**Jackett version**: Jackett Version 0.10.842.0 
**Mono version** (if not using Windows): N/A

-------------------------------

**Comment by garfield69** [comment]
closing as dupe of #1219 which has been reopened.
