### ISSUE TITLE
[Bug] Cannot configure ICE Torrent

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#4783]
I get the following when trying to configure ICE Torrent in Jackett:

An error occurred while testing this indexer
Found no results while trying to browse this tracker

Also, when ICE Torrent used to work a while back, I used to get 2 results for the same torrent (duplicates). I hope this gets fixed too!

Enhanced log attached. Thanks!

[log.txt](https://github.com/Jackett/Jackett/files/2910174/log.txt)

**Jackett version**: Jackett Version 0.10.842.0 
**Mono version** (if not using Windows): N/A

-------------------------------

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I can test if my changes work properly.

**Comment by RoloSoze** [comment]
@garfield69 Unfortunately I don't have an invite right now, but they do have a very simple application signup process:

https://www.icetorrent.org/inviteapp.php?lang=en

It's worth joining!

**Comment by garfield69** [comment]
I've applied but I doubt I'll get accepted. I just login to test my fixes not to upload or contribute to private sites.

**Comment by RoloSoze** [comment]
@garfield69 Keep me posted, please! Thanks a lot!

**Comment by RoloSoze** [comment]
@garfield69 This seems to be working fine with the newest pre-release, I'll close it for now; will revisit if something pops up! Thanks!

**Comment by garfield69** [comment]
I applied a blind fix in the latest pre-release https://github.com/Jackett/Jackett/commit/18f48cb04b5b202d782be065df07c868c14ed254, seems like I got it right then. 
Don't always get lucky, I usually need to test a few times to fine tune the fix.

**Comment by RoloSoze** [comment]
@garfield69 Gotta get lucky every now & then! 👍 Thanks again!
