### ISSUE TITLE
Jackett will not start if Proxy URL is unreachable

### ISSUE THREAD

**Issue by btowntkd** [Jackett/Jackett#4785]
Jackett fails to run, if the proxy URL specified in the settings is not reachable.
I am using a Socks5 proxy, and the URL I was using recently became unreachable.  Once this occurred, Jackett is no longer able to launch - instead, it throws an exception when attempting to instantiate the HttpWebClient.

Typically, Jackett verifies the URL *before* saving settings, so this issue will only arise when manually modifying the ServerConfig.json file, *or* when a previously-specified URL becomes unresponsive after the fact.

**Jackett version**:  v0.10.846
**Mono version** (if not using Windows):  Windows Server 2019

-------------------------------

**Comment by garfield69** [comment]
Jackett 0.16.1389
