### ISSUE TITLE
[beyondhd] Exception (beyondhd): Object reference not set to an instance of an object: Parse error (Test)

### ISSUE THREAD

**Issue by cjamesdesigner** [Jackett/Jackett#4786]
I am getting this parse error on 11 out of 20 trackers. Hope this one can help to figure them all out. I already deleted and reinstalled jackett to no avail. any suggestions would be helpful. Thanks 

**Jackett version**:  0.10.842.0
**Mono version** (if not using Windows):  5.18.0.240

-------------------------------
Log:
https://pastebin.com/pgpUWnxR

**Comment by garfield69** [comment]
I don't know about the other 10 indexers you say you get this error on, however looking at the log you provided for beyondhd, it is clear that the site's results table has changed and the jackett indexer needs updating to match.
If you send an invite to garfieldsixtynine @ gmail.com I will have a go at fixing this.

**Comment by cjamesdesigner** [comment]
I don't have an invite but I can't imagine all 11 sites changed their results tables at exactly the same time.

**Comment by cjamesdesigner** [comment]
here's another of the trackers with the error. https://pastebin.com/sQ1raPiC
I have seen parse error in issues but I have not found anything to work for this.

**Comment by garfield69** [comment]
Yeah. So I suggest you test one of the others with **enhanced logging** enabled, and raise a new ticket for it like you did this one so we can take a look ;-)

**Comment by cjamesdesigner** [comment]
Error for TorrentLeech https://pastebin.com/7tAfTzSX

**Comment by garfield69** [comment]
yeah I can't align the selectors for bithdtv with your html dump either, so that's two. I don't suppose you have an invite for that one?

But the torrentleech indexer processes a json response, (so I'm not going to see that data in the log), but if that is returning a reference-not-set then something in the return does not line up with the expected response. Without a login it much more difficult to diagnose this one.

Got a few more you want to provide a enhanced log dump for?

It would really be much better if you could raise separate tickets for each so they can be tracked and resolved separately.

And If you don't have any invites, then you are going to have to wait for a dev who has a login, (most likely @kaso17 ), but he seems unavailable most of the time recently so it may be a while before they all get resolved.

**Comment by garfield69** [comment]
actually I have a login for torrentleech, and that one is working for me fine.
so for this one something else might be going on that is preventing you seeing the json response.
Are you able to access https://www.torrentleech.org/ directly from a browser on the same system as your jackett?

**Comment by garfield69** [comment]
And having logged in manually with your browser, what do you see in response to using this link https://www.torrentleech.org/torrents/browse/list/ ?
you should get something like 
```json
{"numFound":803920,"torrentList":[{"fid":"1276245","filename":"Modern.Family.S10E16.HDTV.x264-SVA.torrent","name":"Modern Family S10E16 HDTV x264-SVA","addedTimestamp":"2019-02-28 01:32:25","categoryID":26,"size":173951138,"completed":124,"seeders":125,"leechers":13,"numComments":0,"tags":["comedy","Family"],"new":false,"imdbID":"","rating":0,"genres":"","tvmazeID":"","igdbID":""},{"fid":"1276244","filename":"Modern.Family.S10E16.720p.HDTV.x264-AVS.torrent","name":"Modern Family S10E16 720p HDTV x264-AVS","addedTimestamp":"2019-02-28 01:32:00","categoryID":32,"size":751011475,"completed":559,"seeders":537,"leechers":126,"numComments":0,"tags":["comedy","Family"],"new":false,"imdbID":"","rating":0,"genres":"","tvmazeID":"","igdbID":""},
[...etc...]
```

**Comment by cjamesdesigner** [comment]
I am on a dedi but I can log in and see that torrentleech link just fine. I am certain that it has something to do with my dedi and not the sites that are giving me an error. any thoughts on diagnosing my setup?

**Comment by garfield69** [comment]
@kaso17  @flightlevel  can you help with diagnosing this one please? thanks.

**Comment by cjamesdesigner** [comment]
Thanks anyway @garfield69. Mono just updated to 5.18.0.268 and its all working again!
