### ISSUE TITLE
[Enhancement] Automatically enclose ClassiX's search queries between quotation marks 

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#4788]
ClassiX Unlimited tends to display irrelevant, inaccurate, or partially matched search results - e.g. Try searching for A Nightmare on Elm Street, and almost every title with the word street will be displayed. Same thing with Mary Queen of Scots. Every title with the word Queen will be returned. 

This happens both when searching the tracker directly and in Jackett. 

I tried putting the search terms between quotation marks - i.e. "A Nightmare on Elm Street" and the results are much more accurate. 

It would be great if this can be done on the fly in Jackett. Thanks!

**Jackett version**: Jackett Version 0.10.849.0 
**Mono version** (if not using Windows): N/A

**Comment by RoloSoze** [comment]
@garfield69 Surprisingly, now it's doing the opposite. It's now omitting relevant search results! E.g. Searching for A Nightmare on Elm Street should spit out 7 results but I'm only getting one!

When I manually encapsulate the search term with quotation marks, I get accurate results.

**Comment by garfield69** [comment]
try Jackett v0.10.880

**Comment by RoloSoze** [comment]
@garfield69 Works perfectly fine now. Thanks!
