### ISSUE TITLE
Route traffic through HTTP Proxy

### ISSUE THREAD

**Issue by nickpaul41** [Jackett/Jackett#479]
Is it possible to route the HTTP traffic from Jackett through a proxy? 

I have a vpn setup with Privoxy and it would be nice to be able to send my Jackett requests through that.

**Comment by flightlevel** [comment]
You can use a proxy `--ProxyConnection`

```
JackettConsole.exe --help

  -i, --Install            Install Jackett windows service (Must be admin)

  -r, --ReserveUrls        (Re)Register windows port reservations (Required for
                           listening on all interfaces).

  -u, --Uninstall          Uninstall Jackett windows service (Must be admin).

  -l, --Logging            Log all requests/responses to Jackett

  -t, --Tracing            Enable tracing

  -c, --UseClient          Override web client selection.
                           [automatic(Default)/libcurl/safecurl/httpclient]

  -j, --ProxyConnection    use proxy - e.g. 127.0.0.1:8888

  -s, --Start              Start the Jacket Windows service (Must be admin)

  -k, --Stop               Stop the Jacket Windows service (Must be admin)

  -x, --ListenPublic       Listen publicly

  -z, --ListenPrivate      Only allow local access

  -h, --Help               Show Help

  -v, --Version            Show Version

  -p, --Port               Web server port

  -m, --MigrateSettings    Migrate settings manually (Must be admin on Windows)

  -f, --SSLFix             [true/false] Linux Libcurl NSS Missing ECC Ciphers
                           workaround (Use if you can't access some trackers) .

  -n, --IgnoreSslErrors    [true/false] Linux Libcurl - Ignores invalid SSL
                           certificates

  -d, --DataFolder         Specify the location of the data folder (Must be
                           admin on Windows) eg. --DataFolder="D:\Your
                           Data\Jackett\"
```

**Comment by Saner2oo2** [comment]
Hi. 

I'm trying to do this to, how do you authenticate?

I have tried 
/usr/bin/mono --debug /opt/jackett/JackettConsole.exe -j https://user:pass@url:port

But it didn't work

**Comment by fatalfurry** [comment]
Are there any thoughts to pushing this functionality to the web ui?

**Comment by AndyPeepsJR** [comment]
Was there any movement on this, I'm trying to configure Jackett on Linux to use my Privoxy+Tor solution to get to the .onion hosted versions of websites? It doesn't look like the -j flag is on the Linux version.

**Comment by flightlevel** [comment]
@kaso17 
Should we just remove the proxy option?
I can't imagine this is going to straight forward with all the options in Jackett libcurl, cloudflare, captchas

**Comment by kaso17** [comment]
@AndyPeepsJR any chance that you tested it with a HTTPS tracker, that was indeed broken. 46f508f1f6e553d1203a57813f5d69ee2f59037b should fix curl proxy usage for HTTPS. I didn't test it as I was to lazy to setup a proxy.

@Saner2oo2: I'm not sure if libcurl supports HTTPS proxys, can you plesae try HTTP only?

@fatalfurry: please open another issue for the web ui feature.

**Comment by kaso17** [comment]
@flightlevel: With mono 4 we should be able to to use the .NET HTTP client too. I tried it once and it seemd to be working for HTTP connections but was broken for HTTPS (seems like you've to set your own certificate validation function). If we can get it working we could make it the default on linux too and maybe completely remove libcurl/safecurl.

**Comment by niblarto** [comment]
Using the Windows service version of Jacket - I have a simple proxy in the cloud which uses authentication, so would like to route my Jacket Traffic through that - gets around some of the blocks my ISP has in place.

**Comment by kaso17** [comment]
I've opened #1083 as enhancement issue for this.
I'm closing this one for know, feel free to reopen if there are issues with the current proxy command line arguments.

**Comment by morpheus65535** [comment]
Can I use a SOCK5 proxy?

**Comment by flightlevel** [comment]
No, refer to https://github.com/Jackett/Jackett/issues/1083

**Comment by morpheus65535** [comment]
@flightlevel Thank you to point me in the right direction!
