### ISSUE TITLE
[req] new private tracker pthome

### ISSUE THREAD

**Issue by 55laren** [Jackett/Jackett#4795]
sorry   please!
http://www.pthome.net

**Comment by garfield69** [comment]
registration and login successful. Thank you.

**Comment by garfield69** [comment]
Try jackett v0.10.861

**Comment by 55laren** [comment]
> registration and login successful. Thank you.

nonono thank you very much

**Comment by garfield69** [comment]
https://www.pthome.net/ returns Bad gateway Error code 502
uptrends returns 503 Service Temporarily Unavailable

**Comment by ilike2burnthing** [comment]
back up
