### ISSUE TITLE
[AsianCinema] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#4798]
I get the following error when trying to search or test AsianCinema:
Found no results while trying to browse this tracker 

Enhanced log attached
[log.txt](https://github.com/Jackett/Jackett/files/2921398/log.txt)

P.S. Registration for this tracker is currently open:
https://asiancinema.me/register

**Jackett version**:  Latest
**Mono version** (if not using Windows):  N/A

**Comment by garfield69** [comment]
>P.S. Registration for this tracker is currently open: https://asiancinema.me/register

nah, it's broken. I did not get any mail from using either my gmail or outlook a/c

but no matter, the issue for you was a mismatching selector for the categories, so try out jackett pre-release  v0.10.862 and see if it works now.

**Comment by RoloSoze** [comment]
@garfield69 It works fine now, thanks a lot!

As for the registration, this happened to me too. I did not get the confirmation email, so what I did is that I went back to the login page & clicked on the "Forgot Your Password?" link. I entered my email address & received an email almost instantly. I reset my password & was able to access the website.

**Comment by garfield69** [comment]
good tip. that worked for me too. thanks.

**Comment by RoloSoze** [comment]
@garfield69 Just realized this is my 100th closed Jackett issue! Haha! Only 6 remain open!
