### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Connection reset by peer: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by jaime2k190** [Jackett/Jackett#4802]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by jaime2k190** [comment]
hello. i can get on to thepiratebay on browser but jackett will not work with it. some times it will connect then 5 minuets later it won't work.

**Comment by garfield69** [comment]
`Connection reset by peer` is a intermittent network error.
what platform are you running Jackett on?
in not windows, what version of mono are you on?
are you using the official TPB site or a proxy?

**Comment by jaime2k190** [comment]
am running it on l

Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23)
--

when i click on it, it sends me to >> https://thepiratebay.org/

**Comment by garfield69** [comment]
what version of mono? from a terminal try `mono --version`

**Comment by jaime2k190** [comment]
just says command not found when i try that

**Comment by jaime2k190** [comment]
i am on a seedbox btw don't know if that helps out

**Comment by garfield69** [comment]
@flightlevel  @kaso17  any ideas about this issue? is it a network issue with isp or seedbox provider?

**Comment by sachk** [comment]
This seems to be the same error I had due to a DNS block of thepiratebay in Australia.

**Comment by garfield69** [comment]
but surely a dns block would break the link every time, the OP states that it's intermittent?

**Comment by jaime2k190** [comment]
it will connect to thepiratebay RARBG EZTV then 2 minuets later it fails. i have spoken to support on ultraseedbox and they said they have all ports open. no firewall blocking it. it's working fine. it's down to jackett or the site them self. i just wish i could get it to work.
https://gist.github.com/e57df4930f171d05b45be8fc1f2b984b.git ere is the log file of jackett with error codes. hope this will help guys.

**Comment by garfield69** [comment]
```
Jackett.Common.IndexerException: Exception (thepiratebay): Connection reset by peer --->
 System.Net.Http.HttpRequestException: An error occurred while sending the request --->
 System.Net.WebException: Error: SecureChannelFailure (Unable to read data from the transport connection: Connection reset by peer.) --->
 System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. --->
 System.Net.Sockets.SocketException: Connection reset by peer
```
still looks like a network issue to me.
what version of Jackett are you using? have you updated the the very latest version?
@kaso17 or @flightlevel  any ideas guys? Thanks.

**Comment by jaime2k190** [comment]
yes i am on latest version it updated today. 

and i keep telling ultraseedbox that i think it's there inetrnet or it's clashing with another jackett on the node etc. but they keep saying it working fine.

**Comment by jaime2k190** [comment]
hello, it's me agen lol. i have the admin looking at my jackett and he has been at it for 3 days lol. he seems to think that some of the torrent site are blocking the ip address or Cloudflare setup is responsible for it. has he has tried different ip's and it works but he cannot change me ip due to he will have to change every 1ns ip on my node.

**Comment by garfield69** [comment]
so your ip has been blacklisted by cloudflare as part of an IP block that may have been part of a DDOS attack, and your options are either:
1. wait until the ddos alert is over and cloudflare relax the blacklist or
2. employ a vpn so you can access sites under a different ip address
in any case nothing that jackett can help you with.

**Comment by jaime2k190** [comment]
But they only thing I am confused with that. Jackett is that I connect to my seedbox with VNC and it's the same IP. And I can connect to the pirate bay and RARBG etc fine with no problems. But jacket refuse to connect to them.
