### ISSUE TITLE
[nnm-club] An error occurred while sending the request: The operation has timed out. (Config)

### ISSUE THREAD

**Issue by Imparium** [Jackett/Jackett#4803]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.10.861.0
**Mono version** (if not using Windows):  Mono JIT compiler version 5.18.0.225

-------------------------------

NoName Club API is not working.
I can access the site but it is not working in Jackett.

**Comment by garfield69** [comment]
nnm is going very slow and sometimes takes to long to respond before the session timeout kicks in.
but it is still working, so you just need to try again later.
currently three out of four test fail for me. don't think there is anything jackett can do about this.

**Comment by Imparium** [comment]
I see.
Notwithstanding with their API, the website works correctly for me.
Maybe Jackett is using a deprecated API?
