### ISSUE TITLE
[Enhancement] Allow users to save groups/subsets of trackers for different manual search purposes

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#4804]
I have multiple trackers/indexers configured in Jackett, but I don't necessarily need to use all of them for every manual search. Sometimes I might want to search for FLAC music albums, in which case I only need to search certain types of music trackers which I know are good for this type of search. Sometimes I only want to search for movies in a specific format (e.g. REMUX or Untouched/Full Blu-ray), or full TV series seasons, each of which has its own groups of specific trackers that I'd like to search.

While I'm currently able to select/tick certain trackers to search, I have no way of saving my preferences. Therefore, every time I access Jackett, I need to tick these trackers again, which is very inconvenient. 

I think we should allow users to create, name & save multiple categories or groups of trackers. Grouping trackers together and being able to search one or more group at a time would be very handy. 

If someone is willing to implement this, I'm happy to discuss further details on the look & feel and usability aspects of this feature. Thanks!

**Comment by RoloSoze** [comment]
@garfield69 Is it possible to add an 'Enhancement' label to this issue? I used to have the permission to do  that but not anymore.

**Comment by garfield69** [comment]
Usually the enhancement label is added only when a ticket has been accepted as a valid enhancement.
no one has reviewed this ticket yet, hence the lack of a label.
I disqualify myself from reviewing this ticket, as the topic is out of my area of expertise.

**Comment by RoloSoze** [comment]
@kaso17 Thoughts on this idea?

**Comment by kaso17** [comment]
there's already #2185 for this feature
