### ISSUE TITLE
sonarr not finding TorrentDay tv/x265 releases

### ISSUE THREAD

**Issue by AnilDaoud** [Jackett/Jackett#481]
similar issue as #463 ?

Sonarr is not able to find x265 releases using Jackett/TD, but manually searching through jackett returns a result (for example suits s06e08)

**Comment by flightlevel** [comment]
should be good now

**Comment by AnilDaoud** [comment]
i had to add category "5000" in the indexer options in sonarr for it to work with the recent update
works great!
