### ISSUE TITLE
[eztv] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by DarkHorse1997** [Jackett/Jackett#4813]
I get the following error message when trying to  test EZTV:
[eztv] Found no results while trying to browse this tracker (Test)

The site can be opened in the browser and it requires no login.

[log.txt](https://github.com/Jackett/Jackett/files/2926659/log.txt)

**Jackett version**:  0.10.861.0
**Mono version** (if not using Windows):  5.18.0.268

-------------------------------

**Comment by DarkHorse1997** [comment]
Log files are provided in this issue which wasn't in #4811

**Comment by garfield69** [comment]
looks like eztv have dropped magnets from the results page, and added file size.
will need to adjust jackett indexer to fetch magnet from the details page.

**Comment by garfield69** [comment]
fixed in jackett v0.10.886
