### ISSUE TITLE
New tracker request - https://www.sharingue.live

### ISSUE THREAD

**Issue by tnascif** [Jackett/Jackett#4817]
Brazilian Tracker : General

Tracker website: https://www.sharingue.live

New invitations are available at: https://www.sharingue.live/register/null

**Comment by garfield69** [comment]
Try Jackett pre-release v0.10.887

**Comment by garfield69** [comment]
Well that did not last long (3 days!). getting ERR_NAME_NOT_RESOLVED This site can’t be reached www.sharingue.live’s server IP address could not be found.

anyone know ifthey changed domain or have they shutdown already?

**Comment by garfield69** [comment]
removed. can always bring it back if anyone reports their new domain.
