### ISSUE TITLE
[xspeeds] can't add

### ISSUE THREAD

**Issue by thedude0101** [Jackett/Jackett#4818]
Clicking the configure button does nothing then about a minute later I get the error below.
Using binhex-jackett docker
Version 0.10.880.0
Currently connecting to jackett through VPN. No connection issues to any other trackers. I can also access the website just fine though browser using same VPN. I tried reinstalling the whole docker but the issue remains. I also tried switching VPN servers just in case but the issue remains.

Mar 04, 2019 06:10:06 PM | Error | System.Threading.Tasks.TaskCanceledException: A task was canceled.   at CloudFlareUtilities.ClearanceHandler+<PassClearance>d__24.MoveNext () [0x00187] in <d0213015414e4bf286b46bc1ee77bd72>:0  --- End of stack trace from previous location where exception was thrown ---   at CloudFlareUtilities.ClearanceHandler+<SendAsync>d__20.MoveNext () [0x00193] in <d0213015414e4bf286b46bc1ee77bd72>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <863261da85fa459daf42d16ece032f10>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Utils.Clients.HttpWebClient+<Run>d__7.MoveNext () [0x00456] in <9b0b0a2a268d4da68c76ef5a4e0229c5>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Utils.Clients.WebClient+<GetString>d__18.MoveNext () [0x0010b] in <9b0b0a2a268d4da68c76ef5a4e0229c5>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Indexers.BaseWebIndexer+<RequestStringWithCookies>d__5.MoveNext () [0x000cb] in <9b0b0a2a268d4da68c76ef5a4e0229c5>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Common.Indexers.XSpeeds+<GetConfigurationForSetup>d__18.MoveNext () [0x00078] in <9b0b0a2a268d4da68c76ef5a4e0229c5>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Server.Controllers.IndexerApiController+<Config>d__12.MoveNext () [0x0006a] in <039542d832ad4dc2bc38a7a28e544cbc>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0  --- End of stack trace from previous location where exception was thrown ---   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0  --- End of stack trace from previous location where exception was thrown ---   at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x0008a] in <039542d832ad4dc2bc38a7a28e544cbc>:0
-- | -- | --

**Comment by garfield69** [comment]
While I don't have an answer for your issue, I note that there is another ticket open #4591, which suggests that the jackett xspeeds indexer is currently broken, as it is unable to parse the dates on the xspeeds torrent search results page. May need to wait until 4591 is fixed before progressing with this one.

**Comment by garfield69** [comment]
Well, 4591 has been resolved (the problem appeared to be temporary and not related to Jackett).
So it most likely has nothing to do with your issue.
@kaso17  or @flightlevel  I don't know anything about  VPN usage in conjunction with Jackett, so I'll assign this one to you guys and hope you have the time to look into this ticket. Thanks.

**Comment by thedude0101** [comment]
I disabled the VPN and the issue is still present.

**Comment by thedude0101** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/2932082/log.txt)

**Comment by garfield69** [comment]
Please post the output of `curl -vvv https://www.xspeeds.eu/` 
and `openssl s_client -connect www.xspeeds.eu:443` 
Also, the log shows you are using mono 5.14 so try upgrading it to the latest 5.18

**Comment by thedude0101** [comment]
Thanks for all the help. I'm running jackett in an unraid container co i'm kind of stuck with the mono version I think.

curl:

<script type="text/javascript">
  //<![CDATA[
  (function(){
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      var a = document.getElementById('cf-content');a.style.display = 'block';
      setTimeout(function(){
        var s,t,o,p,b,r,e,a,k,i,n,g,f, KTITbEv={"DUfqojEG":+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+!![]))};
        t = document.createElement('div');
        t.innerHTML="<a href='/'>x</a>";
        t = t.firstChild.href;r = t.match(/https?:\/\//)[0];
        t = t.substr(r.length); t = t.substr(0,t.length-1);
        a = document.getElementById('jschl-answer');
        f = document.getElementById('challenge-form');
        ;KTITbEv.DUfqojEG-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[]));KTITbEv.DUfqojEG+=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]));KTITbEv.DUfqojEG-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+[])+(+[])+(+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]));KTITbEv.DUfqojEG*=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]));a.value = +KTITbEv.DUfqojEG.toFixed(10) + t.length; '; 121'
        f.action += location.hash;
        f.submit();
      }, 4000);
    }, false);
  })();
  //]]>
</script>

</head>
<body class="yui-skin-sam">
<div class="content">
<div id="header"><div class="f_search"></div></div>
<div id="subheader">
<div id="menu">
</div>
</div>
<div id="main">
<div class="left_side">
<div align="center">
<table id="main-table" cellpadding="4" cellspacing="0" border="1" style="width:100%;">
<tr><td style="font-weight:bold;">Please wait whilst we check your connection...</td></tr>
<tr><td style="font-size:12px;"><br /><div class="cf-browser-verification cf-im-under-attack">
  <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1></noscript>
  <div id="cf-content" style="display:none">

    <div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> xspeeds.eu.</h1>

    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>
  </div>

  <form id="challenge-form" action="/cdn-cgi/l/chk_jschl" method="get">
    <input type="hidden" name="s" value="d5f7be99c2bc8f7d4d241ce459cef3b964c630cf-1551808883-1800-AV/m2LEwoWqylysRUZ3W3BH30VWqB8iqRvwh3LfI5vWG4feHAHGr7dgVXa2Jff/W0P1+xR7cKp/lgHv68/8CDlbX+4JmRZRmYjIiNySdBk4n"></input>
    <input type="hidden" name="jschl_vc" value="13fdb4d316eb7103af7fb5cf1f36f489"/>
    <input type="hidden" name="pass" value="1551808887.946-TSeJ/zpm8a"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
</div>
<br /><br /></td></tr>

</table>
</div>
<br />
</div>
</div>
</div>

</body></html>
* TLSv1.3 (IN), TLS app data, [no content] (0):
* Connection #0 to host www.xspeeds.eu left intact

openssl s_client -connect www.xspeeds.eu:443
CONNECTED(00000003)
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Domain Validation Secure Server CA 2
verify return:1
depth=0 OU = Domain Control Validated, OU = PositiveSSL Multi-Domain, CN = ssl390193.cloudflaressl.com
verify return:1
---
Certificate chain
 0 s:OU = Domain Control Validated, OU = PositiveSSL Multi-Domain, CN = ssl390193.cloudflaressl.com
   i:C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Domain Validation Secure Server CA 2
 1 s:C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Domain Validation Secure Server CA 2
   i:C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Certification Authority
 2 s:C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Certification Authority
   i:C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIG3jCCBoSgAwIBAgIRAJBn1MdEZ+VLpTM5nXyv0UQwCgYIKoZIzj0EAwIwgZIx
CzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAOBgNV
BAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMTgwNgYDVQQD
Ey9DT01PRE8gRUNDIERvbWFpbiBWYWxpZGF0aW9uIFNlY3VyZSBTZXJ2ZXIgQ0Eg
MjAeFw0xODEwMTIwMDAwMDBaFw0xOTA0MjAyMzU5NTlaMGwxITAfBgNVBAsTGERv
bWFpbiBDb250cm9sIFZhbGlkYXRlZDEhMB8GA1UECxMYUG9zaXRpdmVTU0wgTXVs
dGktRG9tYWluMSQwIgYDVQQDExtzc2wzOTAxOTMuY2xvdWRmbGFyZXNzbC5jb20w
WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATqmo3Z75zRCQ/EFA065OyThzSB4M0C
+xqXqOu1sortmF8+Xh/UjNbYVG2S7rp8Qd0rWNQ7paBfJiXkswKi49BGo4IE3jCC
BNowHwYDVR0jBBgwFoAUQAlhZ/C8g3FP3hIILG/U1Ct2PZYwHQYDVR0OBBYEFDq7
cgAuNO5LDRgNbi2syOblY9EFMA4GA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAA
MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBPBgNVHSAESDBGMDoGCysG
AQQBsjEBAgIHMCswKQYIKwYBBQUHAgEWHWh0dHBzOi8vc2VjdXJlLmNvbW9kby5j
b20vQ1BTMAgGBmeBDAECATBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLmNv
bW9kb2NhNC5jb20vQ09NT0RPRUNDRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZl
ckNBMi5jcmwwgYgGCCsGAQUFBwEBBHwwejBRBggrBgEFBQcwAoZFaHR0cDovL2Ny
dC5jb21vZG9jYTQuY29tL0NPTU9ET0VDQ0RvbWFpblZhbGlkYXRpb25TZWN1cmVT
ZXJ2ZXJDQTIuY3J0MCUGCCsGAQUFBzABhhlodHRwOi8vb2NzcC5jb21vZG9jYTQu
Y29tMIICHgYDVR0RBIICFTCCAhGCG3NzbDM5MDE5My5jbG91ZGZsYXJlc3NsLmNv
bYIWKi5jbG91ZHByb3BlcnR5LmNvbS5hdYIXKi5jb3VwbGVzdGhlcmFweWluYy5j
b22CCyouZm1nZW0uY29tggwqLmhjbGlwcy5jb22CDCouaGNsaXBzLm5ldIIVKi5p
bmZsdWVuY2VycHJlc3MuY29tgg4qLmxvZGVraW5nLmNvbYIPKi5vcmxhamFtZXMu
Y29tgg8qLnJhZGlvZGlsZS5jb22CESoudGFza3NtYXJ0ZXIuY29tgg0qLnRoZWdh
eS5wb3JuggwqLnR1YmVyYi5jb22CFyoudXBza2lydGNvbGxlY3Rpb24uY29tgg0q
Lnd0ZnBhc3MuY29tggwqLnhzcGVlZHMuZXWCFGNsb3VkcHJvcGVydHkuY29tLmF1
ghVjb3VwbGVzdGhlcmFweWluYy5jb22CCWZtZ2VtLmNvbYIKaGNsaXBzLmNvbYIK
aGNsaXBzLm5ldIITaW5mbHVlbmNlcnByZXNzLmNvbYIMbG9kZWtpbmcuY29tgg1v
cmxhamFtZXMuY29tgg1yYWRpb2RpbGUuY29tgg90YXNrc21hcnRlci5jb22CC3Ro
ZWdheS5wb3Juggp0dWJlcmIuY29tghV1cHNraXJ0Y29sbGVjdGlvbi5jb22CC3d0
ZnBhc3MuY29tggp4c3BlZWRzLmV1MIIBAwYKKwYBBAHWeQIEAgSB9ASB8QDvAHYA
7ku9t3XOYLrhQmkfq+GeZqMPfl+wctiDAMR7iXqo/csAAAFmZs6IhgAABAMARzBF
AiEAiKviOeLXboLQerlUXSrP/Y/uRNmKt6MW7VptfBkCCnECIA6eGIUUOq4jXAsw
bmFnhL/Qss9VjEaaB3TIB7wqrzQbAHUAdH7agzGtMxCRIZzOJU9CcMK//V5CIAjG
NzV55hB7zFYAAAFmZs6KbgAABAMARjBEAiBDqCaNObgwKQymk6QLNAde30mhQADt
mIF99dqW5nRVvAIgMst5CndLTbs7UYJlWtx6qU5bt0tSomvcpKH0EfEsHU8wCgYI
KoZIzj0EAwIDSAAwRQIgZd+pmNqF8nm0fk4D/bCGZE79LudRGH7ZKR/0AJF7M6wC
IQCt7Cn9Ihg26mtW0xqc2yqP+FwC6NJ81IX3hm8SJKd9zw==
-----END CERTIFICATE-----
subject=OU = Domain Control Validated, OU = PositiveSSL Multi-Domain, CN = ssl390193.cloudflaressl.com

issuer=C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Domain Validation Secure Server CA 2

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3988 bytes and written 398 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 256 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 5E88C2387424551E0F453522F6834F059A98C5BB314F3885E01C4A7631353C63
    Session-ID-ctx:
    Resumption PSK: 88CC466D5BFBB396A70077A34B33FB021932409356ECD0D5DBFD2A9550A109643192B554A277182EC2D7055F2F056FE8
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 172800 (seconds)
    TLS session ticket:
    0000 - db bb fd cf 71 99 77 82-72 38 d0 08 a0 d0 36 a5   ....q.w.r8....6.
    0010 - c1 92 cf e2 bd 74 9c e5-34 3a 05 4a 9e dd 82 36   .....t..4:.J...6
    0020 - a7 70 af 9d cb 4a 03 14-ca 24 84 39 6b 2b 79 92   .p...J...$.9k+y.
    0030 - 6c bb 1f 5f 94 68 72 33-07 0d 4c 38 65 6d 3e dd   l.._.hr3..L8em>.
    0040 - 0e 8e 43 3f 52 c4 8f bb-35 9d 95 2b 61 80 7f 37   ..C?R...5..+a..7
    0050 - 5e f0 3e 22 86 a1 96 4c-03 43 9f 59 a3 5c cc e1   ^.>"...L.C.Y.\..
    0060 - dc 36 1c af e4 73 2e e0-e4 d8 ac e6 c9 c8 19 9f   .6...s..........
    0070 - 20 45 79 3e d3 6d b6 49-c3 41 4b 7f 30 55 59 f9    Ey>.m.I.AK.0UY.
    0080 - dc 30 5b 68 6d 2f b2 1b-6b 91 2e ed 2d 4c af 52   .0[hm/..k...-L.R
    0090 - 6b f3 81 d7 e5 b4 26 68-78 e2 29 2c ef 51 2c 72   k.....&hx.),.Q,r
    00a0 - a0 da 33 a2 1a f1 89 a7-2f 4e e5 be aa 16 84 7c   ..3...../N.....|
    00b0 - 61 b9 45 2c 04 c4 67 ec-da 48 a4 63 5a b2 cb 99   a.E,..g..H.cZ...

    Start Time: 1551808751
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: DF734DC550B706DB81FC7EBC730E223BD6C0474B26B84B180A81B5146F6BFF15
    Session-ID-ctx:
    Resumption PSK: 607E2E2DD7A97DB342EF3AA95F19542F43F39E18699C2B4D7E1D6D811D75567EC7905AEB235B63CFA7146BCBBD17BEB9
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 172800 (seconds)
    TLS session ticket:
    0000 - db bb fd cf 71 99 77 82-72 38 d0 08 a0 d0 36 a5   ....q.w.r8....6.
    0010 - 53 0e c5 0c dd 32 fd a0-a3 c3 c7 19 fe 6c 79 c4   S....2.......ly.
    0020 - de 5a 42 c6 ef 45 25 cc-b0 7c 38 d8 1f 95 b4 18   .ZB..E%..|8.....
    0030 - 63 1f 2b 41 7d a8 60 32-9e 9b d6 12 76 b1 c1 04   c.+A}.`2....v...
    0040 - 14 0a 02 25 3a 48 da 38-64 2c a8 73 63 ee 86 ac   ...%:H.8d,.sc...
    0050 - f5 98 05 c9 13 af 75 14-b5 00 33 f1 24 6a 61 8a   ......u...3.$ja.
    0060 - c7 c2 ca 8f bc 9f c0 34-96 b8 cb 7a 79 4c e2 81   .......4...zyL..
    0070 - 29 7b ab 01 d8 3c 51 46-29 13 af c6 99 4e 0c da   ){...<QF)....N..
    0080 - b0 d8 37 3e 32 8b 79 a0-3f 3f 24 6f 8d 6b 4b bd   ..7>2.y.??$o.kK.
    0090 - f5 d1 ce 4b 37 93 0b 00-6b 2b f1 f6 90 7c 3c 89   ...K7...k+...|<.
    00a0 - 8a 81 3b 88 46 34 a1 39-92 e2 16 ce 0c 82 4d 19   ..;.F4.9......M.
    00b0 - 57 81 1c 94 3a 46 ac d4-50 76 7e de aa 70 b7 84   W...:F..Pv~..p..

    Start Time: 1551808751
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
closed

**Comment by garfield69** [comment]
@kaso17  could really use your help diagnosing this one. Thanks.

**Comment by ngosang** [comment]
@thedude0101 Is that fixed?

**Comment by thedude0101** [comment]
I think it was an issue with xpeeds. It seems to be working ok now
