### ISSUE TITLE
Can´t update on freenas 11.2

### ISSUE THREAD

**Issue by fontes31** [Jackett/Jackett#4819]
Hi,

Iam running jackett v.0.10.566.0 but i cannot update to version v0.10.886.
I have jackett on a jail, installed with pkg install jackett but i do not know the command to update it.

**Comment by garfield69** [comment]
have you tried using the **check for updates** button on the Jackett Dashboard?
![image](https://user-images.githubusercontent.com/6933240/53825796-0756e100-3fdc-11e9-9003-49af9c14f0b8.png)
You may need to refresh the page later to check that the version at the bottom of the page has bumped.

**Comment by fontes31** [comment]
yes, it say view logs for details:

and the last one on logs - "Deleting JackettUpdate temp files from /tmp/JackettUpdate-v0.10.886-636873765051626990"

at the bottom still the same version 0.10.566.0

**Comment by fontes31** [comment]
update to pre-release? unchecked?

**Comment by garfield69** [comment]
looking back at previous tickets, on some systems the update processor does not work.
so it may be that you will need to just download the latest version and install over the top.

**Comment by fontes31** [comment]
ok, just delete the old version and install the new one? or just install the new one without deleting the old version?

**Comment by garfield69** [comment]
I would try install without delete and if that does not work then delete and install. Sorry I don't have a freenas so cant give you a definite answer.
