### ISSUE TITLE
[eztv] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by tempistraven** [Jackett/Jackett#4821]
I get the following error message when trying to test EZTV:
 "An error occured while testing this indexer
Found no results while trying to browse this tracker"

site is able to be accessed by the browser and has not login

Jackett version: 0.10.886.0
Mono version (if not using Windows): 5.18.0.225

[log.txt](https://github.com/Jackett/Jackett/files/2933470/log.txt)

**Comment by tempistraven** [comment]
this is not a duplicate since the issues #4813 was resolved and this is not resolve on my system.  Please open the issue.  Thank you

**Comment by garfield69** [comment]
looks like they reversed the changes they made yesterday. I'll revert the commit and publish an update shortly.

**Comment by garfield69** [comment]
Try Jackett v0.10.890
