### ISSUE TITLE
[torrent9] Search problem.

### ISSUE THREAD

**Issue by sbeaudoin** [Jackett/Jackett#4822]
If I do manual search in Jackett, only a search of the partial name works.

![image](https://user-images.githubusercontent.com/3873484/53843280-df319880-3f6f-11e9-94f4-6381c21ee819.png)

But on the target site, https://wvw.torrent9.uno, there are results for any of the three searches.

**Comment by garfield69** [comment]
its the site's search engine. 
when you search on the site for `l'exorcisme de hannah grace` the site actually looks for `lexorcisme de hannah grace`. Note it dropped the `'`.
if you manually search for `lexorcisme de hannah grace` on jackett you'll get the hits your expecting.
I'll update the indexer to also drop the apostrophe and this should match what the site is doing.
