### ISSUE TITLE
Incorrect Mono Version in README

### ISSUE THREAD

**Issue by craigkc** [Jackett/Jackett#4823]
This one is simple, but I'm afraid it might really throw off new users.  In the README under 'Install on Linux' it is written that the minimum version is 5.8.  According to mono-project.com, the latest stable Mono release is 5.18.0 Stable (5.18.0.268) as of today.  I'm guessing it's supposed to say "5.18" instead of "5.8".

**Comment by flightlevel** [comment]
No, its meant to say 5.8. 5.18 is newer than 5.8 (18 is greater than 8)
