### ISSUE TITLE
[BeyondHD] Multiple issues with search string processing

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#4828]
We've had issues in the past with how BeyondHD processes search strings. Please refer to issues #755 and #835 for a background on these issues. @kaso17 worked hard (thank you!) on solving them, to the extent that searching BHD in Jackett used to return more accurate results than doing so in the tracker directly. Unfortunately, ALL 4 issues from #835 are back again! Plus I found 2 more: 

5. A search issue that seems to kick in when there are numbers in the title (aside from the year). I tried searching for Taxi 1998. Doing so in both Jackett & the tracker returns no results. However, try searching for the word Taxi instead. You'll get 10 results, one of which is the 1998 Taxi. This happens not because the first search string has the year 1998 in it (years work fine with BHD). It's because the title has the number (15th), and as such, for some reason, it doesn't pop up in the initial search. If you search for Taxi 15th (you normally wouldn't though), it'll pop up!

Another example - Try searching for the sequel, Taxi 2 from the year 2000 (I don't typically enter the part number in my searches because some trackers might list it as 2, others as II, so I avoid entering it altogether). So I tried searching for Taxi 2000 and it works fine with every tracker except for BHD - no results pop up. Now try searching for Taxi 2 2000 or simply Taxi 2, and you'll find it!

6. Dead torrents do not appear in the search results.

**If you look at BHD's Browse Page (https://beyond-hd.me/browse.php), scroll down and click Show/Hide More Search Options. If Jackett can be configured so as to include dead torrents (2nd radio button) and narrow search by 'Description' for every search by default, I think all of these issues can be solved.**

**Jackett version**:  0.10.900.0
**Mono version** (if not using Windows): N/A

**Comment by garfield69** [comment]
is 855 typo? ticket seems unrelated to bhd.

**Comment by RoloSoze** [comment]
@garfield69 Corrected. It's #835

**Comment by RoloSoze** [comment]
@garfield69 I believed the last paragraph (in bold) in my issue statement above could be the solution to this issue. Can it be implemented?

**Comment by garfield69** [comment]
Most probably. but since I don't have a login for this private site I can't research and test.
If you send an invite to garfieldsixtynine @ gmail.com I can most probably implement.
Alternatively, I could try a blind commit, if you provide a html dump of the results page by enabling enhanced logging and doing a search so I can see what the selector requirements are.

**Comment by RoloSoze** [comment]
@garfield69 Check your Gmail. Also it would be great if you could check the inactivity rules, and initial & quarterly download rules & requirements for this tracker if you would like to avoid getting disabled & keep the account for future maintenance purposes.

**Comment by garfield69** [comment]
registration and login successful. thank you.
But it looks like I'll be suspended after the first quarter, since I don't intend to download 25gb quarterly or seed torrents for a minimum 120 hours etc. Sorry if that ends up burning your invite for this one time fix.

**Comment by garfield69** [comment]
so with the changes you requested, the indexer would create the following url:
https://beyond-hd.me/browse.php?searchin=descr&incldead=1&search=%25venom%252018%251080%25dts%25

which returns the following results:
![image](https://user-images.githubusercontent.com/6933240/54067306-4e2a2c80-42a3-11e9-9d81-3f807041a8d0.png)

is this what you expect? shall I go ahead and commit?

**Comment by garfield69** [comment]
other search results based on what you posted earlier
![image](https://user-images.githubusercontent.com/6933240/54067481-6733dd00-42a5-11e9-8f78-d42a928be20c.png)
![image](https://user-images.githubusercontent.com/6933240/54067489-829ee800-42a5-11e9-879d-c8d9fbecbb7e.png)

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/54067554-34d6af80-42a6-11e9-8194-9aaf0e7f8896.png)

**Comment by garfield69** [comment]
try out Jackett pre-release v0.10.917

**Comment by RoloSoze** [comment]
It seems like this fix is a double-edged sword - We're getting more relevant results but also a bunch of completely irrelevant ones since we're also searching in the description. Do you think the ANDMATCH method can fix this? In the Venom example above, we shouldn't be getting the final two results.

Also, since posting issue #835, I personally stopped searching with resolution, encode type, release group etc. I find that searching with the title and year and then filtering the search results within Jackett using the 'Search' box returns much better results.

**Comment by RoloSoze** [comment]
@garfield69 Alright let me try the pre-release.

**Comment by RoloSoze** [comment]
@garfield69 Can you please try the ANDMATCH method to see if the irrelevant search results can be filtered out?

Also. since BeyondHD allows users to search with the IMDb ID, can this be enabled in Jackett? I was meaning to open a new ticket and list the major trackers that allow searching with IMDb ID for which the capability isn't enabled in Jackett, and BeyondHD is one of them.

**Comment by RoloSoze** [comment]
@garfield69 I think that the irrelevant results are caused by the fact that searching in the description can return many unpredictable results. E.g. trying searching for Creed 2018. Previously, Jackett would've returned nothing but now it returns 11 results, 4 of which are completely irrelevant. That's because in those irrelevant results, the words Creed and 2018 both appear in the description section, albeit in completely different parts of it. 

Can Jackett somehow force the search of all keywords only within the same line? Just because the words Creed and 2018 appear in the description doesn't mean they're together/next to each other.

**Comment by garfield69** [comment]
I've implemented andmatch and it appears to work nicely. Try Jackett pre-release v0.10.920

I'll start working on adding imdbid processing with #4850 .

**Comment by RoloSoze** [comment]
@garfield69 It works perfectly fine now! I did a bunch of tests, and searching in Jackett returns all the relevant results, much better than searching the tracker directly. Thank you!

**Comment by RoloSoze** [comment]
@garfield69 Would you like me to put together a list of trackers that allow searching with IMDb ID for which this functionality is not supported in Jackett?

Also, does it makes a difference if the tracker accepts the IMDb ID in the default search box vs. a dedicated/separate search box?

**Comment by garfield69** [comment]
sure. raise an enhancement request ticket and list each of the indexers you would like imdb support for.
(use a check list so we can tick them off as they get implemented `- [ ] indexer name` )

if the indexers are native c# then is wont matter about the search box.
I don't know if that will be a problem with the cardigann indexers, until I take a look.

Also, I will only be able to implement those private indexers that I have logins for, so unless there are invites available for the rest, then they will have to wait until one of the other devs with a login can attend to the changes. ;-)

**Comment by RoloSoze** [comment]
Sounds good! I'll check out a few top indexers tomorrow and will put together a list. Thanks again!
