### ISSUE TITLE
CouchPotato and TorrentLeech not working

### ISSUE THREAD

**Issue by Trollet23** [Jackett/Jackett#4829]
I can't use CouchPotato with Jackett searching on TorrentLeech, for some reason.

In CouchPotato - Searchers - TorrentPotato I have the following settings:

Host: http://127.0.0.1:9117/api/v2.0/indexers/torrentleech/results/potato/
Passkey: [pasted from Jackett]
Username: Blank
Seed Ratio: 0
Seed Time: 0
Extra Score: 0

TorrentLeech is added as the only indexer in Jackett. The test works fine, green check mark.

When I search for the movie "7 Boxes" (or anything else, obviously) in CouchPotato, the log there says:

03-07 01:27:56 INFO [hpotato.core.plugins.base] Opening url: get http://127.0.0.1:9117/api/v2.0/indexers/torrentleech/results/potato/?imdbid=tt2333598&user=&passkey=xxx

03-07 01:27:57
ERROR [hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://127.0.0.1:9117/api/v2.0/indexers/torrentleech/results/potato/?imdbid=tt2333598&user=&passkey=xxx&user=&passkey=xxx

When I browse to http://127.0.0.1:9117/api/v2.0/indexers/torrentleech/results/potato/?imdbid=tt2333598&user=&passkey=[my passkey] I get this message:

> torrentleech does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported.

Browsing to http://127.0.0.1:9117/api/v2.0/indexers/torrentleech/results/potato/ gives a 401 error, but maybe that's how it should be?

Am I doing something wrong or is TorrentLeech not supported now? I'd be forever grateful if someone would help me out.
[log.txt](https://github.com/Jackett/Jackett/files/2938951/log.txt)

**Jackett version**:  0.10.906.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
As far as I can tell by skimming through the torrentleech c# indexer, it does not support imdbid lookup, which would appear to make it incompatible with couchpotato.

Now I don't know for sure if jackett has or not, a fall-back method where the omdb is used to fetch the series name and a general search is issued instead of the imdbid search, and whether or not that is broken or does not exist.

There is a similar ticket #4816 open.

@kaso17  or @flightlevel  do you folks know what the story is with couchpotato support in Jackett, are only indexers with imdbid capability supported, or is there a fallback with the use of omdb that is supposed to work but is currently broken?

**Comment by garfield69** [comment]
BTW,  how come you are not using couchpotato's internal torrentleech search engine?

**Comment by Trollet23** [comment]
> BTW, how come you are not using couchpotato's internal torrentleech search engine?

Hi

First of all, big thanks for your quick response.

The internal TorrentLeech search hasn't worked for ages through CouchPotato for me. Here's an example of what the CouchPotato log throws back when trying to add The Lord of the Rings using the internal TorrentLeech search only:

03-07 11:12:33
INFO [core.media.movie.searcher] Search for The Lord of the Rings: The Fellowship of the Ring in 1080p ignoring ETA

This is the reason why I started using Jackett. I can search on TorrentLeech through Jacket's UI, so the connection to TorrentLeech is okay from there. So, something goes wrong somewhere between CouchPotato and Jackett.

**Comment by flightlevel** [comment]
Is your version of CouchPotato really old?
Since 2016 CP should send a search parameter https://github.com/CouchPotato/CouchPotatoServer/blob/12ca4c22680961346e0aa2617941bf1a7252fc67/couchpotato/core/media/movie/providers/torrent/torrentpotato.py that is missing in your requests
When I request `/api/v2.0/indexers/torrentleech/results/potato/?imdbid=tt2333598&search=7%20boxes&user=&passkey=xxxxxxxxxxxxxxxxxxxxxxxx` I see one result

@garfield69 From memory it only kicked for aggregate indexer???
Anyway it shouldn't be needed ever for torrentpotato, since the Movie title is always provided by CP we can always search on that

**Comment by Trollet23** [comment]
> Is your version of CouchPotato really old?
> Since 2016 CP should send a search parameter https://github.com/CouchPotato/CouchPotatoServer/blob/12ca4c22680961346e0aa2617941bf1a7252fc67/couchpotato/core/media/movie/providers/torrent/torrentpotato.py that is missing in your requests
> When I request `/api/v2.0/indexers/torrentleech/results/potato/?imdbid=tt2333598&search=7%20boxes&user=&passkey=xxxxxxxxxxxxxxxxxxxxxxxx` I see one result

Hi

No, I actually updated it yesterday but it was fairly new before, too:

Version 3.0.1
Updater desktop
ID 5512

However, C:\Users\Me\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\couchpotato\core\media\_base\providers\torrent\torrentpotato.py is last modified 2015-08-31. Could that be the problem?



That same search as in your post returns one result for me, too. But I can't really get to that search through CouchPotato, when I add that movie and CP searches for it, the log shows:

Failed opening url in TorrentPotato: http://127.0.0.1:9117/api/v2.0/indexers/torrentleech/results/potato/?imdbid=tt2891174&user=&passkey=xxx&user=&passkey=xxx

**Comment by flightlevel** [comment]
Open torrentpotato.py in Notepad. On line 20 does it have the search parameter like the current version does? https://github.com/CouchPotato/CouchPotatoServer/blob/12ca4c22680961346e0aa2617941bf1a7252fc67/couchpotato/core/media/movie/providers/torrent/torrentpotato.py#L20

If not uninstall CP and reinstall it (or maybe just get the latest version of torrentpotato.py [but makes you wonder if have other old files then...])

**Comment by Trollet23** [comment]
It didn't, but I replaced it so now it does. No difference though.

I think I might as well uninstall CP completely and re-install it and see if that helps. As you say, it seems a lot of the files haven't been updated.

Will post in thread again after that.

**Comment by Trollet23** [comment]
This is interesting. After uninstalling, then deleting C:\Users\Me\AppData\Roaming\CouchPotato\ manually, I downloaded and reinstalled CouchPotato.

torrentleech.py 2015-05-07 21:15
torrentpotato.py 2015-05-07 21:15

Attaching the files (renamed to .txt). Isn't this super strange? Should I replace the entire folder with the one on Github?

[torrentleech.txt](https://github.com/Jackett/Jackett/files/2941153/torrentleech.txt)
[torrentpotato.txt](https://github.com/Jackett/Jackett/files/2941154/torrentpotato.txt)

**Comment by Trollet23** [comment]
Nope, replaced the entire folder with the one on Github but still no success. Any ideas or should I just give up?

**Comment by garfield69** [comment]
Cp 3.0.1 was built in sep 2015 and is 550 commits behind the github source.
I would suggest uninstalling that version and running cp from source by following the instructions in the cp readme https://github.com/CouchPotato/CouchPotatoServer/blob/master/README.md
