### ISSUE TITLE
[New Tracker REQ] HDPlus

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#4843]
Indexer Name
HDPlus

Type
Private

Indexer URL
https://hdplus.xyz

Indexer Language
English

Invite
Signups are currently open:
https://hdplus.xyz/register/

Notes
1. Please includes all 3 types of torrents in the search results (i.e. Dead, Dying, Alive)
2. Please enable searching via IMDb ID in Jackett

**Comment by garfield69** [comment]
Try out Jackett pre-release 0.11.4

**Comment by tnascif** [comment]
Mine is not working :(

**Comment by garfield69** [comment]
is https://hdplus.xyz still valid?  seeing ERR_CONNECTION_TIMED_OUT

**Comment by RoloSoze** [comment]
@garfield69 On & off. Let's give it sometime before declaring it dead.

**Comment by garfield69** [comment]
https://hdplus.xyz/ still returning ERR_CONNECTION_TIMED_OUT
anyone else having this issue?

**Comment by tnascif** [comment]
I'm almost possitive that the tracker is dead.

**Comment by garfield69** [comment]
ok thanks. i'll remove it.
if it turns up again we can always add it back ;-)
