### ISSUE TITLE
Jackett .Net Core update uses a lot of memory

### ISSUE THREAD

**Issue by thoradia** [Jackett/Jackett#4844]
@flightlevel 

Jackett (.Net Core for ARM32) auto-update dramatically increases memory consumption of Jackett (from about 100M to about 300M). This is a lot for constrained systems such as a Raspberry Pi.

Is there a way to limit memory consumption of auto-update?

Thank you for your attention

**Comment by flightlevel** [comment]
No, there isn't a way to limit memory consumption. We don't have much control over this being a .NET Core app, hopefully future versions of the runtime will make improvements in this area. What is the big deal about of a bit of paging though for 10 secs while it updates? If it bothers you, suggest turning off automatic updates.

Moving to .NET Core is going to allow us to improve the situation in the future. But we are dependent on changes in to .NET Core for that. More info here https://github.com/dotnet/corert and https://github.com/dotnet/core/blob/master/samples/linker-instructions.md
