### ISSUE TITLE
[AlphaRatio] Result is counted but not printed

### ISSUE THREAD

**Issue by whitesnakeftw** [Jackett/Jackett#4845]
This doesn't always happen apparently, but in this particular case it did. It correctly says:

> Your search was done using: AlphaRatio (1) ,

so it seems that it's found 1 result, but then no result is shown below:

> No matching records found

and also:

> Showing 0 to 0 of 0 entries (filtered from 1 total entries)

I obviously have no filter set. To reproduce search for "loro ithd" without quotes.

**Comment by whitesnakeftw** [comment]
I'm thinking the problem might be related to the fact the torrent was just uploaded a few hours before and thus had the extra html that made the number of seeds a red zero.

![ar_red_seeds](https://user-images.githubusercontent.com/9657324/54070490-e94de280-4260-11e9-97c7-84f043ede824.jpg)

**Comment by whitesnakeftw** [comment]
Can confirm that red zero is the cause of the problem. It doesn't happen anymore with the previous torrent because its stats have since updated, but it happens with the newest torrents that have that red zero.

**Comment by garfield69** [comment]
I need to see the HTML from the site to amend the indexer selectors.
If you send an invite to garfieldsixtynine @ gmail.com I should be able to sort this out.

If an invite is not available, then please provide the **full enhanced log** file. But because I would not be able to test my changes, there is a high risk of error.

1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by garfield69** [comment]
addendum: the AlphaRatio uses the gazelle engine. I don't know how to change the native jackett c# indexer to handle the difference in the selector that you have discovered, so I am going to pass this ticket on to the more experienced devs.

**Comment by whitesnakeftw** [comment]
@garfield69 There's almost always a torrent with a red zero among the newest torrents, so this should be fairly easy to reproduce at any given time. In case a full log is absolutely necessary I'll gladly provide it. :)

**Comment by garfield69** [comment]
nah. I don't have a login for alpharatio. 
If you send an invite to garfieldsixtynine @ gmail.com I will certainly investigate.

But doing a little research into the jackett gazelle engine, it does not process the sites html, it uses the site's provided API which returns json.
If you cannot provide an invite, then if you want to experiment in providing the required data, you could try the following:
1. from a browser login to alpharatio.
2. paste the following url: https://alpharatio.cc/ajax.php?action=browse&order_by=time&order_way=desc
3. paste the json response here so I can take a look.

If it is a large text dump maybe use pastebin or some such, or put in in a plain text file and drag/drop it here.

**Comment by whitesnakeftw** [comment]
@garfield69 Here it is (had to rename it to .txt) :)

[ajax.txt](https://github.com/Jackett/Jackett/files/2971966/ajax.txt)

**Comment by garfield69** [comment]
excellent. 
so the data you posted shows what you would get when you do a regular blank-search, and the result you provided does not show any obvious anomalous data.

so the next time you spot the issue,  login to alpharatio, and use:
 https://alpharatio.cc/ajax.php?action=browse&order_by=time&order_way=desc&searchstr=something

replacing **something** with whatever you searched for.
if **something** has dots or banks replace them with a + or if that does not work then use %20 instead.

then post the data here again, along with the title that has the red seeders, and I will compare that with the base json you gave me before.

**Comment by whitesnakeftw** [comment]
@garfield69 Ok so searching for "desus and mero" via Jackett (and on AlphaRatio only) yields 12 results, but Jackett only prints 9 of them. This is the related response:

[ajax2.txt](https://github.com/Jackett/Jackett/files/2972915/ajax2.txt)

where, in fact, exactly 3 torrents have 0 seeders. So I'm figuring maybe it's not about the zeros being red (since you pointed out the parsing is done via API, not HTML), but maybe the gazelle handler automatically excluding results with 0 seeders?

**Comment by garfield69** [comment]
well if it does I cant see it in the gazelle code. the seeders code just grabs the value and assigns it to the element `release.Seeders = (int)torrent["seeders"];`

that's the problem with not being able to generate the test myself, I cant put traces on the run and track the code flow. :-(

is there anything in the enhanced log that shows 3 exceptions being generated?

**Comment by kaso17** [comment]
this looks like it's working as intended. You probably disabled the "show dead torrents" button on the manual search page.

**Comment by whitesnakeftw** [comment]
@kaso17 That was it! Never noticed that button before... Thanks.
