### ISSUE TITLE
Rutracker.org blocked

### ISSUE THREAD

**Issue by EdisonMaxwell** [Jackett/Jackett#4846]
Rutracker,org seems to be blocked in my country. Rutracker.net seems to work and seems to be the same website. Do I need to submit a request for a new tracker?

**Comment by garfield69** [comment]
>Do I need to submit a request for a new tracker?

You are correct, the two domains point to the same site.
Try editing the rutracker indexer.
From your jackett dashboard access the add-indexers page, and use the wrench icon to open the rutracker config and change the sitelink from .org to .net.
enter your login details and click OKAY.

**Comment by Imparium** [comment]
What may also help you is to change your DNS server.
