### ISSUE TITLE
Search failing with TVChaos UK

### ISSUE THREAD

**Issue by MisterC925** [Jackett/Jackett#485]
Using Jackett(0.7.363.0) with Sonarr( 2.0.0.4230) and I have successfully downloaded from tvchaosuk.com in the past.

However, the series "Victoria" seems to be causing it a problem.

Sonarr does a search for "Victoria S01E03" which fails because the title in the tracker is "Victoria - S01E03".  A search for "Victoria" or "S01E03" returns the proper results but the two terms together does not seem to.

Since I do not believe I can easily change Sonarr's formatting of the query, can Jackett be updated to work properly?  For example, match both terms instead of the whole thing as one term?

Thanks!

**Comment by jccroft1** [comment]
I'm also having a problem with Sonarr searching on TV Chaos.

**Comment by kaso17** [comment]
if someone could send an invite to kaso1717 @ gmail.com I could have a look at it.

**Comment by kaso17** [comment]
Thank you for the invite.
Unfortunately the TVChaos UK search is very primitive requiring an exact match.
But I came up with a solution anyway.
It looks like they send the search query without escaping it to the database. On the one side this probably allows an attacker to dump the entire TVChaous UK database via an SQL injection attack but it allows us also to use % as a wildcard match character which improves the searchresults.
With my current pull request #516 you should get better results from TVChaos UK.

**Comment by MisterC925** [comment]
This fixed my issue, thanks!
