### ISSUE TITLE
[1337x] Exception (1337x): No connection could be made because the target machine actively refused it 193.113.9.167:443: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by morpheus2n2** [Jackett/Jackett#4852]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
your ISP is blocking your access to this site, see http://www.ukispcourtorders.co.uk/

consider switching from your ISP provided DNS to a public one like https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/ or https://developers.google.com/speed/public-dns/docs/using

**Comment by morpheus2n2** [comment]
That's what I thought but that's not my Public IP and I already use 1.1.1.1

**Comment by garfield69** [comment]
Huh?
193.113.9.167 was where jackett was redirected to, when it tried accessing the sitelink for  1337x.
193.113.9.167 equals http://www.ukispcourtorders.co.uk/
This suggests that DNS 1.1.1.1 was not used to resolve the 1337x sitelink.
From a browser on the same system as jackett access the jackett dashboard and click on the 1337x indexer name. Where does it take you?

**Comment by morpheus2n2** [comment]
Lol yeah just realized that 🤦‍♂️.
From the jackett dash if I click the name it takes me directly to the site witch is why I can't work out what's going on.
My router is set with 1.1.1.1 as the DNS.
Once I get home think I will also put the DNS on the machine aswell to make sure

**Comment by c0nsaw** [comment]
Same issue with iptorrents for me, cant get anything to work :(
