### ISSUE TITLE
Add option to silence "JackettTray is already running"

### ISSUE THREAD

**Issue by akaleeroy** [Jackett/Jackett#4861]
Please add a command-line switch to silence the message box saying **JackettTray is already running**

![image](https://user-images.githubusercontent.com/4068718/54131398-edbdfb00-441a-11e9-9555-852262d89a44.png)

I know it's already running, but Jackett is automatically started by a Scheduled Task whenever I start a torrent client. Because of it I have to make a script to check if running then execute only if not. I don't want it starting with Windows and using up resources for that once-in-a-blue-moon search. It's naturally a part of the torrent client workflow.

That message is a splash screen that steals focus and requires user action. It's more appropriate as a tray notification. If that's too difficult to implement maybe it's even more appropriate to be quiet by default.

**Comment by flightlevel** [comment]
Why is it such a big deal if it happens once in a blue moon?
And whats so terrible about adding a check in your script?
We're not adding switches for one users particular use case for their once in a blue moon scenario. If Jackett is already running, don't try starting it again

**Comment by akaleeroy** [comment]
I posted the issue to open it up to discussion. Sure I could make a script to fix it (it was only a scheduled task, now it has to be a script) but I think it's a UX mistake, the program should be quiet or notify via the appropriate channel. Starting Jackett when it's already running is not a user error, it can be handled gracefully. If this was the discussion and the conclusion is a splash screen is OK, then alright!
