### ISSUE TITLE
[rarbg] Exception (rarbg): The server returned an invalid or unrecognized response.: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by Daptonic** [Jackett/Jackett#4863]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.11.8.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
the jackett rarbg indexer uses the rarbg api at https://torrentapi.org/pubapi_v2.php which is currently returning ERR_CONNECTION_REFUSED
I've raised the issue with  support@rarbg.to and we just have to wait for the problem to be resolved.

**Comment by garfield69** [comment]
I was able to resolve the issue on my win10 by opening a cmd terminal and using the `ipconfig /flushdns` command.

**Comment by Daptonic** [comment]
Checked again and it's working now. Closing.
