### ISSUE TITLE
FDD Release

### ISSUE THREAD

**Issue by thoradia** [Jackett/Jackett#4865]
@flightlevel
 
Would it be possible to provide a FDD release in addition to the SCD releases?
Some operating systems, such as LibreELEC, already provide up-to-date .Net Core runtime and dependencies for all supported platforms

A FDD release would be smaller and platform independent

This could also solve memory surge during auto-update (LibreELEC has no swap file and dies when out of memory)

Thank you for you attention

**Comment by flightlevel** [comment]
Already explained why we don't provide a FDD release, we don't want to have to support multiple versions of the runtime and be limited by the lowest common denominator. We've gone through so much with Mono in this regard.
You can easily build this yourself if you want to
```
git clone https://github.com/Jackett/Jackett.git
cd Jackett/src
dotnet publish
```
