### ISSUE TITLE
Jackett won't start on Raspbian 9 stretch after v0.11.10 update.

### ISSUE THREAD

**Issue by NuggetFarmer** [Jackett/Jackett#4866]
After last night's auto-update, Jackett no longer starts. I'm currently running Jackett on a Raspberry Pi. I've had Jackett running strong for over a year without any hiccups, not sure what might have went wrong.

I'm using: 
Raspbian GNU/Linux 9 (stretch)
Mono 3.10.0
Latest Jackett

**I'm unable to update my version of Mono, as that version is required for other programs**

```
Missing method get_FrameworkDescription in assembly /opt/jackett/Jackett.Common.dll, type System.Runtime.InteropServices.RuntimeInformation

Unhandled Exception:
System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.RuntimeInformation' from assembly 'Jackett.Common'.
  at Jackett.Server.Program+<>c__DisplayClass9_0.<Main>b__2 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00000] in <filename unknown>:0
  at CommandLine.ParserResultExtensions.WithParsed[ConsoleOptions] (CommandLine.ParserResult`1 result, System.Action`1 action) [0x00000] in <filename unknown>:0
  at Jackett.Server.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.RuntimeInformation' from assembly 'Jackett.Common'.
  at Jackett.Server.Program+<>c__DisplayClass9_0.<Main>b__2 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00000] in <filename unknown>:0
  at CommandLine.ParserResultExtensions.WithParsed[ConsoleOptions] (CommandLine.ParserResult`1 result, System.Action`1 action) [0x00000] in <filename unknown>:0
  at Jackett.Server.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
```

Any idea what might have broken with last night's update?

**Comment by Dnkhatri** [comment]
> After last night's auto-update, Jackett no longer starts. I'm currently running Jackett on a Raspberry Pi. I've had Jackett running strong for over a year without any hiccups, not sure what might have went wrong.
> 
> I'm using:
> Raspbian GNU/Linux 9 (stretch)
> Mono 3.10.0
> Latest Jackett
> 
> **I'm unable to update my version of Mono, as that version is required for other programs**
> 
> ```
> Missing method get_FrameworkDescription in assembly /opt/jackett/Jackett.Common.dll, type System.Runtime.InteropServices.RuntimeInformation
> 
> Unhandled Exception:
> System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.RuntimeInformation' from assembly 'Jackett.Common'.
>   at Jackett.Server.Program+<>c__DisplayClass9_0.<Main>b__2 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00000] in <filename unknown>:0
>   at CommandLine.ParserResultExtensions.WithParsed[ConsoleOptions] (CommandLine.ParserResult`1 result, System.Action`1 action) [0x00000] in <filename unknown>:0
>   at Jackett.Server.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
> [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.RuntimeInformation' from assembly 'Jackett.Common'.
>   at Jackett.Server.Program+<>c__DisplayClass9_0.<Main>b__2 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00000] in <filename unknown>:0
>   at CommandLine.ParserResultExtensions.WithParsed[ConsoleOptions] (CommandLine.ParserResult`1 result, System.Action`1 action) [0x00000] in <filename unknown>:0
>   at Jackett.Server.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
> ```
> Any idea what might have broken with last night's update?

A new mono less version of Jackett is out for linux . You should probably move to that.

**Comment by flightlevel** [comment]
You must have had a really old version of Jackett. Any release of Jackett in the last 9 months won't start unless Mono 5.8 was present https://github.com/Jackett/Jackett/commit/e82b54994e4a2900594f738ed5c19b1c16da798a#diff-a55ae24a3ad226cb1662cfae6037fc9bL138 . Before that Mono 4 was required. So not sure how it ever ran with Mono 3

As @Dnkhatri pointed out, Mono is no longer needed to run Jackett, so I'd just download the relevant ARM release of Jackett
