### ISSUE TITLE
[mvgroupforum] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by d1slact0r** [Jackett/Jackett#4873]
There are 2 different entries and both of them are not working. Should be fixed and merged into 1

anyone that can test:
https://github.com/Jackett/Jackett/pull/4874

**Comment by garfield69** [comment]
I cannot replicate your problem. I can access and get results for both mvforum and mvgroup.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.
