### ISSUE TITLE
Jackett Start Error -    Service cannot be started. System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified  

### ISSUE THREAD

**Issue by anjoed** [Jackett/Jackett#4877]
Hello Guys, how are you ?

Well, My jackett doesn't want start. Every restart of my windows ( I have a Windows 7), I need to reinstall the jackett and only this way I could to use this program. I tried to figure out what is happening, but in the event viewer logs I have only this:

Service cannot be started. System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Jackett.Service.Service.StartConsoleApplication() in C:\projects\jackett\src\Jackett.Service\Service.cs:line 67
   at Jackett.Service.Service.OnStart(String[] args) in C:\projects\jackett\src\Jackett.Service\Service.cs:line 42
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)

In the servicelog.txt, I don't have details. So, What  I tried:

1) The port is free and The firewall isn't the problem (and the Antivirus);
2) I reinstalled and, only this way, without a restart after that, Jackett worked;
3) I updated the Jackett (v0.11.8.0).

What Am I missing ? I don' t find a way to enable the debug and I don't have a JackettConsole.exe in the Jackett folder....

Thanks!

**Comment by garfield69** [comment]
if the jackettconsole.exe is missing from the programdata/jackett folder then most likely your system security (anti malware program?) is silently moving it to its viruschest.

**Comment by anjoed** [comment]
> if the jackettconsole.exe is missing from the programdata/jackett folder then most likely your system security (anti malware program?) is silently moving it to **its viruschest**.

You are right! The problem was the antivirus (Avatar). It was my mistaken, because i really didn't add in the whitelist (I think I really added, however, I didn't apply the action :(  )

Thank you very much.
