### ISSUE TITLE
jackett binary doesn't exist

### ISSUE THREAD

**Issue by bicarbonate** [Jackett/Jackett#4881]
Downloaded the tar.gz package, extracted and there is no jackett binary. This is a Linux install, and the instructions on the main Code page are incorrect. 
I extracted the package and there is no binary for jacket to be called upon when running the install_service_system.sh script.

https://github.com/Jackett/Jackett/releases/download/v0.11.31/Jackett.Binaries.LinuxAMDx64.tar.gz

**Comment by flightlevel** [comment]
I can see it there
![image](https://user-images.githubusercontent.com/9430010/54266183-fe14d800-45ca-11e9-96ed-e6db40009232.png)
Can you explain what is wrong with the instructions, "are incorrect" doesn't help
I noticed one small issue in that `install_service_system.sh` doesn't have execute permission set, will fix that in the next release

**Comment by garfield69** [comment]
@flightlevel  having downloaded and extracted the latest AMDx64 package (0.11.46), I still can't use the install service script.
```
garfield69@Ubuntu-VirtualBox:~/Downloads/Jackett$ sudo ./install_service_systemd.sh
sudo: ./install_service_systemd.sh: command not found
garfield69@Ubuntu-VirtualBox:~/Downloads/Jackett$ ls i* -l
-rw-r--r-- 1 garfield69 garfield69 2115 Mar 15 06:31 install_service_systemd.sh
```
I notice that aa8e10672740ab31ac4986dfc89875a2f1c5e418 contains no actual changes so perhaps that is the problem?

re: the install instructions, perhaps the OP is looking for specifics, such as:  `open a terminal and cd to the Jackett folder you just installed` or something similar.

**Comment by flightlevel** [comment]
Thanks @garfield69 
https://github.com/Jackett/Jackett/commit/aa8e10672740ab31ac4986dfc89875a2f1c5e418 did make a slight change, not to file content, but file permission 
![image](https://user-images.githubusercontent.com/9430010/54424202-8085cf00-4766-11e9-98ad-5efb0816804a.png)

Needed a bit more persuasion though with 6882715a3f2af2a5e320dd9feb863b2fb55d06e2

On the instructions, agree, they could be more detailed, lets wait for OP feedback before changing

**Comment by garfield69** [comment]
confirming on my win10 VB ubuntu image, with 0.11.56 I can now run the installation script and access the Jackett Dashboard from the browser. Also confirming that the service is started after a reboot.

**Comment by bicarbonate** [comment]
Sorry for the late reply.. when I was extracting this the script then tried to run the ./jackkett I got an error 'no file found".  Whe I looked at what was extracted I did not see any 'jackett' file.
I'm at work now so I cannot verify or collect screenshots, but it seems LI likely did something wrong here so I'll retry tonight.
