### ISSUE TITLE
[hdplus] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by tnascif** [Jackett/Jackett#4885]
Jackett version:  0.11.36.0
Windows 10 
-------------------------------
[log.txt](https://github.com/Jackett/Jackett/files/2963384/log.txt)

**Comment by tnascif** [comment]
I found my problem! I had to set the language to English for it to work!

**Comment by garfield69** [comment]
Hmm. The HDplus indexer should cope with  Turkish|Estonian|Danish|Italian|Polish|Norwegian|Portoguese|Czech|Russian|Romanian|Spanish|French|German|Bulgarian|Dutch

what language did you originally have it set to?

**Comment by tnascif** [comment]
Portuguese (Brazilian)

**Comment by garfield69** [comment]
Oh, I see. I could not set up a translate for this because google translate does not have it :-(
but if you are willing I can set it up, if you provide the translations for the following:
minute
minutes
hour
hours
day
days
week
weeks
month
months
ago

**Comment by HDVinnie** [comment]
99% sure when it comes to `pt` vs`pt_BR` its the same. Just pretty much need to duplicate `pt`.

**Comment by tnascif** [comment]
minute = minuto
minutes = minutos
hour = hora
hours = horas
day = dia
days =dias
week = semana
weeks = semanas
month = mês
months = meses
ago = atrás

**Comment by garfield69** [comment]
which probably explains why google don't bother to provide a translate table for it.
But looking at the text that hdplus returns when the language is set to pt-br I see this:
9 eur 'zo , 1 devezh 'zo , 2 zevezh 'zo , 1 miz 'zo
which is not PT of any kind, (google auto-detect is confused too)  and explains why the jackett indexer cannot find a matching translation for the fields.
So i'm closing this ticket.

**Comment by tnascif** [comment]
I was about to post that! I'm trying to figure it out what a F** is that Lol

**Comment by HDVinnie** [comment]
It was a conflict with Carbon. https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/br.php

Idk what language that is which is why in UNIT3D `br` was changed to `pt_BR`.
