### ISSUE TITLE
new tracker request - https://kikibt.cc/

### ISSUE THREAD

**Issue by carlox97** [Jackett/Jackett#4886]
Is it possible to add it to Jackett?
No registration required.

**Comment by carlox97** [comment]
`---
  site: kikibt
  name: KIKIBT
  description: "kikiBT is a Public BitTorrent DHT search engine"
  language: cn-CN
  type: public
  encoding: UTF-8
  links:
    - https://kikibt.cc/

  caps:
    categories:
    # KIKIBT does not support categories
      1: Other

    modes:
      search: [q]

  settings: []

  search:

**Comment by garfield69** [comment]
Try it out on Jackett 0.11.46

**Comment by garfield69** [comment]
anyone know where KikiBT's new domain is now?

**Comment by carlox97** [comment]
> anyone know where KikiBT's new domain is now?

Sadly I don't. Could you please tell me if you find it somehow?
Many thanks.
