### ISSUE TITLE
[REQ] add public tracker https://mac-torrents.com

### ISSUE THREAD

**Issue by RicardoVelaC** [Jackett/Jackett#4889]
Add public Mac software tracker

https://mac-torrents.com

**Comment by garfield69** [comment]
try out jackett v0.11.53

**Comment by ilike2burnthing** [comment]
https://mac-torrents.io/ - Error 504 - Gateway time-out

**Comment by RicardoVelaC** [comment]
In that moment https://mac-torrents.io/ works for me, very slow but works

**Comment by garfield69** [comment]
https://mac-torrents.io/ returning 522 Connection Timeout

**Comment by RicardoVelaC** [comment]
Maybe they move it to https://www.torrentmac.net/

**Comment by garfield69** [comment]
v0.19.8
