### ISSUE TITLE
[REQ]Freetorrent - New french tracker

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#4894]
Please add french tracker https://freetorrent.tk/

Looks like blutopia.

Registrations are open for 44 days.

**Comment by garfield69** [comment]
Try out Jackett 0.11.58

**Comment by garfield69** [comment]
freetorrent login is currently broken. error generated is:
```
Validation Error
×
{"g-recaptcha-response":["The g-recaptcha-response field is required."]}
```
 but the g-recaptcha challenge is not presented at login, but the login script insists it be resolved.

catch22.

the console log shows:
```
api.js:1 Refused to load the script 'https://www.gstatic.com/recaptcha/releases/Zy-zVXWdnDW6AUZkKlojAKGe/recaptcha__en.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://www.google.com/recaptcha/api.js https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/api2/ https://www.gstatic.com/recaptcha/api2/v1550471573786/recaptcha__en.js https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.1/moment-with-locales.min.js https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.min.js https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.15.35/js/bootstrap-datetimepicker.min.js https://analytics.freetorrent.tk/piwik.js https://analytics.freetorrent.tk/matomo.js https://www.gstatic.com/recaptcha/releases/Zy-zVXWdnDW6AUZkKlojAKGe/recaptcha__fr.js 'nonce-fe7f172522f1f41b999174b6820f056c'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
looks like they have some versioning or corruption issues to sort out.

**Comment by garfield69** [comment]
@HDVinnie  I don't suppose you can get word to the freetorrent crew that their login page appears broken. see my prior post for details. im using google chrome 77.0.3865.120

**Comment by garfield69** [comment]
cant login to freetorrent. the captcha is not showing up in the form 
![image](https://user-images.githubusercontent.com/6933240/69451489-5f30b480-0dc4-11ea-8315-61e4219bb6be.png)
so the login validation generates an error
![image](https://user-images.githubusercontent.com/6933240/69451578-9b641500-0dc4-11ea-9ba8-2d06091644f4.png)

**Comment by garfield69** [comment]
fixed

**Comment by garfield69** [comment]
freetorrent back to its no-captcha breaking-the-login trick again.

**Comment by garfield69** [comment]
freetorrent offline returning Error 503: Service Unavailable!
`Sorry, we are doing some maintenance. Please check back soon.`

**Comment by garfield69** [comment]
online and upgraded to unit3d 2.2.?

**Comment by pipopop** [comment]
REQ change tracker type : semi-private

Hello, on the site, it's written that it's a private tracker. But since Mars 2019, Register was always opened.
And now, on the site, it's written that register is possible for 591 days.

**Comment by garfield69** [comment]
https://freetorrent.tk/ closed.
![image](https://user-images.githubusercontent.com/6933240/127100913-b00de50b-bde1-4e58-a141-407e2cdf56a9.png)

**Comment by garfield69** [comment]
v0.18.481
