### ISSUE TITLE
BJ-Share-  WEB parsed as HDTV

### ISSUE THREAD

**Issue by tnascif** [Jackett/Jackett#4895]
Jackett Version:  0.11.56.0  
Windows 10 Pro

![Sem título](https://user-images.githubusercontent.com/1376614/54483605-bdb89280-4834-11e9-99ff-96413283e97e.jpg)

**Comment by garfield69** [comment]
what am i looking at in that screen shot you posted? is that sonnar or radarr or something?
why are you expecting jackett to do something about it?

**Comment by tnascif** [comment]
yeah, my bad !i thought i posted on sonarr github
