### ISSUE TITLE
Torznab Limit implementation

### ISSUE THREAD

**Issue by salutdiego** [Jackett/Jackett#4901]
Hello,

I'm looking for a parameter to limit the number of entries on my RSS feed link.
I tried limit and l, but it's not working.
What is the right syntax ?

http://ip_addr:9117/api/v2.0/indexers/torrent9/results/torznab/api?apikey=my_api_key&t=search&cat=2000&q=1080p&limit=10

Synology
Mono 5.8.0.108
Jackett Version 0.11.58.0

**Comment by garfield69** [comment]
>I'm looking for a parameter to limit the number of entries on my RSS feed link.
>I tried limit and l, but it's not working.
>What is the right syntax ?
>http://ip_addr:9117/api/v2.0/indexers/torrent9/results/torznab/api?apikey=my_api_key&t=search&cat=2000&q=1080p&limit=10

you have the correct syntax. 
I think the issue here may be that the cardigann processor  (the torrent9 is a yaml indexer) does not make use of the limit parm
https://github.com/Jackett/Jackett/blob/1bbc01cfcd5ecbcdcd5fbcebfc3af88423bef60c/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1302
but I'll need to test this to be sure I'm looking in the right place.
@kaso17  or @flightlevel  please do step in if you know the answer off hand, thanks.

**Comment by garfield69** [comment]
@kaso17  @flightlevel  I've implemented the torznab Limit for the cardigannIndexer b3dec55, but before I publish, can you think of any reason why I should not go ahead?
Also, should I start looking at all the c# indexers and apply similar code for them, as right now, only a couple actually implement, Ncore and BroadcastTheNet?

**Comment by salutdiego** [comment]
Thanks a lot garfield69, the parameter "limit" works great with the new Jackett Version 0.11.92.0.
By the way, i have decided to switch to docker.

**Comment by garfield69** [comment]
tracking indexers that have been updated to honour the torznab Limit:
- [ ] 720pier
- [ ] 7tor
- [ ] Abnormal
- [ ] AlphaRatio
- [ ] AnimeBytes
- [ ] AnimeTorrents
- [ ] AnimeTosho
- [ ] Anthelion
- [ ] Avistaz
- [ ] AvistazTracker
- [ ] BB
- [ ] BJShare
- [ ] BakaBT
- [ ] BaseIndexer
- [ ] BeyondHD
- [ ] BitCityReloaded
- [ ] BitHdtv
- [ ] BitMeTV
- [ ] Bitspiracy
- [ ] BrasilTracker
- [ ] BrokenStones
- [ ] CinemaZ
- [ ] DanishBits
- [ ] DigitalHive
- [ ] EliteTracker
- [ ] FileList
- [ ] FunFile
- [ ] Fuzer
- [ ] GazelleGames
- [ ] GazelleTracker
- [ ] GimmePeers
- [ ] HDOnly
- [ ] HDSpace
- [ ] HDTorrents
- [ ] Hardbay
- [ ] Hebits
- [ ] HorribleSubs
- [ ] IIndexer
- [ ] IPTorrents
- [ ] ImmortalSeed
- [ ] LostFilm
- [ ] MejorTorrent
- [ ] MoreThanTV
- [ ] MyAnonamouse
- [ ] NewRealWorld
- [ ] Newpct
- [ ] Norbits
- [ ] Nordicbits
- [ ] Orpheus
- [ ] PassThePopcorn
- [ ] PiXELHD
- [ ] PirateTheNet
- [ ] PolishTracker
- [ ] Pretome
- [ ] PrivateHD
- [ ] Psytorrents
- [ ] Rarbg
- [ ] Redacted
- [ ] RevolutionTT
- [ ] SceneHD
- [ ] SceneTime
- [ ] SecretCinema
- [ ] Shazbat
- [ ] ShowRSS
- [ ] SpeedCD
- [ ] Superbits
- [ ] TVChaosUK
- [ ] TVVault
- [ ] TVstore
- [ ] TorrentBytes
- [ ] TorrentDay
- [ ] TorrentHeaven
- [ ] TorrentLeech
- [ ] TorrentNetwork
- [ ] TorrentSyndikat
- [ ] Torrentech
- [ ] Torrentscsv
- [ ] TransmitheNet
- [ ] XSpeeds
- [ ] Xthor
- [ ] cgpeers
- [ ] digitalcore
- [ ] myAmity
- [ ] notwhatcd
- [ ] rutracker
- [ ] yts
- [x] BroadcastTheNet
- [x] CardigannIndexer
- [x] NCore

**Comment by garfield69** [comment]
totally wasted my time. 
If I had done a limit request myself using any of the c# indexers that I've been examining the c# for, such as `http://127.0.0.1:9117/api/v2.0/indexers/beyondhd/results/torznab/api?apikey=rj***redacted***5&t=search&limit=10`
I would have seen from the start that the limit is applied.
so in the end it was just the cardigannIndexer that needed the fix. 
Duh!
I have still so much to learn about how Jackett hangs together ...

**Comment by morpheus133** [comment]
But you know that Limit itself is not enough, also implementation of offset is required to use result from more pages.
