### ISSUE TITLE
Cannot download torrents through search UI in qBittorrent with certain tracker results.

### ISSUE THREAD

**Issue by uNderdog101** [Jackett/Jackett#4902]
I cannot start a torrent through the qBt search UI, whether double clicking the result line or clicking the download button, but only on results from some trackers, most work fine.

The affected trackers I've found so far are: Limetorrents, Isohunt2, 1337x and ETTV.

I can go to the description page and try to download it from there and maybe get some clues as to what is wrong. On 1337x the magnet links work fine, but the torrent files are behind authentications or unavailable with adblock on, and on Isohunt2 both torrent files and magnet links are hidden behind a mylink nightmare 10 pages deep that is impossible to get past with adblock on.

Does the download functionality only use the torrent files and not the magnet links?

 Jackett Version 0.11.58.0

**Comment by ngosang** [comment]
@uNderdog101 I'm the qBittorrent maintainer.
I just tested with ETTV and other trackers and it's working fine. In most cases Jackett returns a magnet link but qBittorrent works with magnet and .torrent.
Please, update the Search plugins in qBittorrent and try again.

**Comment by uNderdog101** [comment]
> 
> 
> @uNderdog101 I'm the qBittorrent maintainer.
> I just tested with ETTV and other trackers and it's working fine. In most cases Jackett returns a magnet link but qBittorrent works with magnet and .torrent.
> Please, update the Search plugins in qBittorrent and try again.

Thanks, that worked. At first it gave no results and asked for the Jackett API number, but after inputting that it works fine.

The version of the qBt plugin available through https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins is version 1.11, but running an update after installing the version jumps to version 3.2, so that was a bit weird.

This can be marked closed.
