### ISSUE TITLE
[kapaki] Exception (kapaki): Login failed: No form found on https://kapaki.info/?p=home

### ISSUE THREAD

**Issue by valantislevas** [Jackett/Jackett#4905]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

i use  Jackett Version 0.11.60.0 

thanks..  yesterday this tracker get update or something and doesnt work.. thanks a lot..

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by valantislevas** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/2980840/log.txt)

thanks

**Comment by garfield69** [comment]
Hmm. unfortunately the log does not reveal the smoking gun.
I presume you have checked that you can login to this site directly from a browser on the system as the one running Jackett?
which OS is this?

**Comment by valantislevas** [comment]
ye i login as well from broswer on my home.. the jackett running on dedicade linux server..

**Comment by garfield69** [comment]
ok, just t be sure I understand,  the browser login that is successful is not performed on the same dedicated linux server that runs Jackett but from another computer?

**Comment by valantislevas** [comment]
yes..

**Comment by garfield69** [comment]
ok, on the dedicated linux server that runs Jackett, please post the output of 
`curl -vvv https://kapaki.info/` 
and 
`openssl s_client -connect kapaki.info:443`

**Comment by valantislevas** [comment]
` # curl -vvv https://kapaki.info/
*   Trying 178.238.234.152...
* Connected to kapaki.info (178.238.234.152) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 596 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: kapaki.info (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: OU=Domain Control Validated,OU=PositiveSSL,CN=kapaki.info
*        start date: Fri, 08 Sep 2017 00:00:00 GMT
*        expire date: Sat, 03 Oct 2020 23:59:59 GMT
*        issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Domain Validation Secure Server CA
*        compression: NULL
* ALPN, server accepted to use http/1.1
> GET / HTTP/1.1
> Host: kapaki.info
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 302 Moved Temporarily
< Date: Mon, 18 Mar 2019 23:55:00 GMT
< Server: Apache/2.4.29 (Ubuntu)
< Location: ?p=home&pid=1
< Cache-Control: max-age=600
< Expires: Tue, 19 Mar 2019 00:05:00 GMT
< X-Content-Type-Options: nosniff
< X-Frame-Options: sameorigin
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
<
* Connection #0 to host kapaki.info left intact
`

and the second command:

` openssl s_client -connect kapaki.info:443
CONNECTED(00000003)
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Domain Validation Secure Server CA
verify return:1
depth=0 OU = Domain Control Validated, OU = PositiveSSL, CN = kapaki.info
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=PositiveSSL/CN=kapaki.info
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
 1 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
 3 s:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFRjCCBC6gAwIBAgIRALIgsuFCo52EUOI5qCEtMhcwDQYJKoZIhvcNAQELBQAw
gZAxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMTYwNAYD
VQQDEy1DT01PRE8gUlNBIERvbWFpbiBWYWxpZGF0aW9uIFNlY3VyZSBTZXJ2ZXIg
Q0EwHhcNMTcwOTA4MDAwMDAwWhcNMjAxMDAzMjM1OTU5WjBPMSEwHwYDVQQLExhE
b21haW4gQ29udHJvbCBWYWxpZGF0ZWQxFDASBgNVBAsTC1Bvc2l0aXZlU1NMMRQw
EgYDVQQDEwtrYXBha2kuaW5mbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBAOQhPU07y1cMMFmgZvW/8zgdSNaC4jV+FUYPck7qno9SUIvCrnJMjaGFvMv8
4vrbteW4ng63WAQpGbWwT4GbAQjakgMLO35N/n+tdqesn5kgccX7Kv43U9eMLaTj
zxyVs5TXcemA+ZtTjvw5282XqEJ9a+3eLQ1C0/8Pakeg9gt8LX89X8pEXtCu4YJ8
YlgTMqmJaHTHoBKbYbO8I7raQ+XaxXJaBxcXyCSH7UUFItJ7wmZtKsm8MoRwIMD/
s4MzMbNewHqrq8z8GxU48wTMkZ7wkBXYBh9vNhAB+TcBxHo/YjxhxCK50F1LbBTQ
VtnTsrgAl/9p13u5YYfdsc8kPrcCAwEAAaOCAdkwggHVMB8GA1UdIwQYMBaAFJCv
ajqUWgvYkOoSVnPfQ7Q6KNrnMB0GA1UdDgQWBBSycBW33NjwHj68veB1gxPphqBS
eDAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEF
BQcDAQYIKwYBBQUHAwIwTwYDVR0gBEgwRjA6BgsrBgEEAbIxAQICBzArMCkGCCsG
AQUFBwIBFh1odHRwczovL3NlY3VyZS5jb21vZG8uY29tL0NQUzAIBgZngQwBAgEw
VAYDVR0fBE0wSzBJoEegRYZDaHR0cDovL2NybC5jb21vZG9jYS5jb20vQ09NT0RP
UlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZlckNBLmNybDCBhQYIKwYBBQUH
AQEEeTB3ME8GCCsGAQUFBzAChkNodHRwOi8vY3J0LmNvbW9kb2NhLmNvbS9DT01P
RE9SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3J0MCQGCCsGAQUF
BzABhhhodHRwOi8vb2NzcC5jb21vZG9jYS5jb20wJwYDVR0RBCAwHoILa2FwYWtp
LmluZm+CD3d3dy5rYXBha2kuaW5mbzANBgkqhkiG9w0BAQsFAAOCAQEAabBJO9aC
ac7CMqKtCqmVfk8pKQaueJL2p7NDwUjgPVo4UZ3chtolU0/RMeSDkPt4aqEZ3pzT
VoafQdbkVMqKjr4gPgOY+8g/jdOJQHy8xjQQfoGmTGPBC/ghm/MnTInhbjs/MCAS
FQUD1TxBZG0XBIQAtouCPB8g0NSciZd2HdFKYe5zUgStVHomEpsL/9rhFBvca+Y2
P6UCpRvuTjis1LX0DmzqvFB1AueOfGiwrOpvXM2aJBWQYOeAn0ySX6siVE2v/+WT
Q8eVA3irf+jFv2FPsiGcfg/v2wwykv5jDZWfx0MqGKEOki/q/Twi5CkEy988Mb3l
O9J7B7KnI++H4Q==
-----END CERTIFICATE-----
subject=/OU=Domain Control Validated/OU=PositiveSSL/CN=kapaki.info
issuer=/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 6050 bytes and written 269 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 6756AAD9B467115D87F84B9CE4531E8BD9BE9CA54D72DE4B4C6E1D2FA5BD53D6
    Session-ID-ctx:
    Master-Key: 2C93A77325C0E864F9276E305A594F441E5547E17FD1940C139805F53AA38B5364873861AAF1B0FD0E198CFF68AC83C2
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - ce 74 2c 3f ba 27 a9 f8-cd 8d 7e 60 ed c5 ac 3f   .t,?.'....~`...?
    0010 - 0a 70 62 06 89 40 5f 49-27 ec ee b2 0f 31 c9 1d   .pb..@_I'....1..
    0020 - 7c a9 e5 4e 3a 86 70 5b-a8 28 9a c7 66 7e b1 50   |..N:.p[.(..f~.P
    0030 - c0 31 81 f7 c7 1c 8b 23-e2 94 94 5a cb 8c 57 81   .1.....#...Z..W.
    0040 - 7e f0 07 9c 3a 3b b8 b1-60 ea ba 33 d3 b4 e4 24   ~...:;..`..3...$
    0050 - 5c 09 22 95 f8 44 90 b2-49 a1 39 33 e0 9a 38 67   \."..D..I.93..8g
    0060 - 12 86 e5 93 7f 8c 53 ab-bb cc 32 c4 64 0f f8 2b   ......S...2.d..+
    0070 - f7 82 3b 13 dc e0 f6 cf-41 75 e0 2f 87 d3 24 a5   ..;.....Au./..$.
    0080 - 19 2c 53 b0 3f be 5e d4-9b 3c 2f 27 e2 e4 44 57   .,S.?.^..</'..DW
    0090 - e1 aa 40 01 47 06 69 f2-37 af 76 93 ab 0c 67 ea   ..@.G.i.7.v...g.
    00a0 - 4b 68 08 5e 6b 8b 0c 51-e1 f4 31 c8 4f 8b 73 cb   Kh.^k..Q..1.O.s.
    00b0 - 06 c6 ef a3 bf 2f cb 1b-03 51 00 89 c9 12 7e 89   ...../...Q....~.

    Start Time: 1552953333
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
`

**Comment by garfield69** [comment]
@kaso17  or @flightlevel  any ideas what to check next to progress diagnosis on this ticket? thanks.

**Comment by valantislevas** [comment]
@garfield69 for some reason i delete and put again the informations and it works.. damn.. thanks anyway and i will check it if something changes i will tell u..
