### ISSUE TITLE
[REQ DEAD TRACKER] ArcheTorrent

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#4906]
ArcheTorrent Tracker is dead.
You can remove it.
Here is more explanation : [https://www.wareziens.net/forum/topic-42493-archetorrent-c-est-fini-page-1.html](https://www.wareziens.net/forum/topic-42493-archetorrent-c-est-fini-page-1.html)

**Comment by garfield69** [comment]
thanks for reporting.
