### ISSUE TITLE
[REQ] CiNEFiLHD

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#4908]
Please add this tracker which is open at the moment.

Name : CiNEFiLHD
Url : http://cinefilhd.org/
Type : private tracker.
Genre : Movies / TV / Classics / Criterions / Old Movies
language : English

Thanks

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/54568217-46088480-4a3b-11e9-84d6-09faa5582095.png)
appears to be invite only at the moment?

**Comment by skuizy** [comment]
I can send you one, but didn't find your mail address

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by garfield69** [comment]
Bah!, even the invite signups are closed presently.
![image](https://user-images.githubusercontent.com/6933240/54591357-efc53100-4a8e-11e9-9758-06c590f7597a.png)

**Comment by garfield69** [comment]
Perhaps you could PM the admin and ask when the invite signup will be available again?

**Comment by skuizy** [comment]
Done.

Wait and see ;)

**Comment by skuizy** [comment]
It seems you can register at http://www.cinefilhd.org/invite_signup.php ;)

**Comment by garfield69** [comment]
Signup successful, You apparently  need to confirm my account now?

**Comment by skuizy** [comment]
Seems so. Confirmed on my side !

**Comment by garfield69** [comment]
Try out Jackett v0.11.107

**Comment by garfield69** [comment]
currently getting ERR_CONNECTION_TIMED_OUT from http://www.cinefilhd.org/
broken, gone or moved to a new domain?

**Comment by skuizy** [comment]
Looks like they're gone...

**Comment by garfield69** [comment]
restore cinefilhd as it is now back online

**Comment by garfield69** [comment]
v0.20.4166

**Comment by ilike2burnthing** [comment]
http://cinefilhd.sytes.net/ - ERR_CONNECTION_TIMED_OUT (because of course)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://cinefilhd.sytes.net/ DNS_PROBE_FINISHED_NXDOMAIN (Domain not Found)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/4908#issuecomment-1552874678

**Comment by garfield69** [comment]
online
new preferred domain is http://cinefilhd.xyz/

**Comment by garfield69** [comment]
http://cinefilhd.xyz/ returns a web viewer page that wants me to install `http://xmsecu.com:8080/ocx/VideoPlayToolSetup.exe`  , and while only one virustotal test flagged it as malicious  https://www.virustotal.com/gui/url/ceeac5e04982c5da732b3dfd286fb2bbe353f39956793c12c8b9717e18aa91ff buggered if I'm going to installed it just to find out what the message may be.

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
http://cinefilhd.xyz/ - Site in constructie!!!

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/4908#issuecomment-1585062182

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/4908#issuecomment-1589933433

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/4908#issuecomment-1585062182

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
http://cinefilhd.xyz/ - ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/4908#issuecomment-1605229638

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
It's online, but as NordicHD (which itself is down).

**Comment by garfield69** [comment]
yes. a mail on the site gave me karma and was sighed as nordichd staff.
I think we should expect the old nordichd indexer to be obsolete and perhaps for cinefilhd to get renamed?

**Comment by ilike2burnthing** [comment]
Yea, that's probably the case. I'll send a message to their sysop, see if I can get some clarity.

**Comment by ilike2burnthing** [comment]
They're being merged and https://nordichd.org/ is the one that will remain.

**Comment by ilike2burnthing** [comment]
ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.21.364

**Comment by garfield69** [comment]
jeesh. https://nordichd.org/ redirecting to http://cinefilhd.xyz/ 
I'm getting very close to just deleting this one too and calling it a day for both of them.

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
🤷 Restore the indexer for now?

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/4908#issuecomment-1613599882

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
![image](https://github.com/Jackett/Jackett/assets/6933240/edd9ca1d-7226-4ed6-b7b9-d6b1bbaca586)

**Comment by garfield69** [comment]
while http://cinefilhd.xyz/ generates the poster above, http://cinefilhd.xyz/index.php and http://cinefilhd.xyz/browse.php work

**Comment by garfield69** [comment]
https://cinefilhd.xyz/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.21.763
