### ISSUE TITLE
Add PTN (PirateTheNet) tracker

### ISSUE THREAD

**Issue by savahu** [Jackett/Jackett#491]
I think this would be a nice addition.
PTN: http://piratethe.net/
I have an invite available.

Here is a custom plugin for couchpotato which could serve as an example:
https://github.com/Codehhh/PirateTheNetCouchPotatoPlugin

Thank you.

**Comment by kaso17** [comment]
Please send an invite to kaso1717 @ gmail.com and I'll add it.

**Comment by savahu** [comment]
@kaso17 I sent the invite. Thanks in advance! :)

**Comment by kaso17** [comment]
Thank you for the invite.
I added the tracker (pull request #493).
Let me know if you have any problems with it.

**Comment by savahu** [comment]
Thanks, I will test it in a few hours. 
Maybe remove your email from the comment now.

**Comment by garfield69** [comment]
v0.21.1025
