### ISSUE TITLE
[Req] Add btdb.eu indexer

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#4913]
The indexer https://btdb.eu/ was removed from Jackett in the past, but they are back. Please, find the old code and re-add it.
Thank you!

**Comment by garfield69** [comment]
FYI it may have the name BTDB but its not the same html.
However with some adjustments I can shoehorn in a replacement.

**Comment by ngosang** [comment]
@garfield69 thank you so much!

**Comment by garfield69** [comment]
https://btdb.eu/ redirecting to https://onionflix.org/

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/1564#issuecomment-870558421
