### ISSUE TITLE
[blutopia] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by mouzzampk2014** [Jackett/Jackett#4916]
I tried copy cookie values but still getting same error

**Jackett version**:  0.11.58.0

-------------------------------

**Comment by garfield69** [comment]
try jackett pre-release 0.11.85

**Comment by mouzzampk2014** [comment]
How I am on dockers? Is there tag I need to use? Thank you

**Comment by garfield69** [comment]
ahh. sorry, I believe the the docker distribution site only builds their images from a full release of Jackett, they don't grab our pre-releases.
I hadn't wanted to build a full release yet as I was waiting on feedback from a couple devs about #4901, but if I don't get a reply soon I'll go ahead and do a full release in about 6 hours.

**Comment by mouzzampk2014** [comment]
Awe thank you so much. You are the best :)

**Comment by salutdiego** [comment]
<3 garfield69

**Comment by garfield69** [comment]
Try out Jackett  v0.11.92

**Comment by mouzzampk2014** [comment]
Morning bestie,

Thank you so much. Everythig working fine now after update 🤗☺

You have a great day

Hassan Arshad
07951439409
