### ISSUE TITLE
[REQ] New tracker Bettyboop-tk

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#4919]
Name : Bettyboop-tk
URL : http://bettyboop-tk.biz/
Type : Movie/TV/General
Genre : semi-private
Language : french

Great thanks,

**Comment by garfield69** [comment]
the site's registration appears to be broken.
![image](https://user-images.githubusercontent.com/6933240/61989450-ab245480-b083-11e9-895a-e449207af9fe.png)

**Comment by pipopop** [comment]
I send a message to the administrator. I'm waiting.

**Comment by pipopop** [comment]
Perhaps, it's a wrong error, Have you try to login ?

**Comment by garfield69** [comment]
yes I did, and received an Access Denied Login Incorrect message.

**Comment by garfield69** [comment]
@nikogaug the username I use is garfield1969 and the email is  garfieldsixtynine @ gmail.com

**Comment by pipopop** [comment]
Ok They have a problem. So insciptions are closed until the problem is resolved.

**Comment by nikogaug** [comment]
Is it the same username for Genration Rosco tracker ?
I have to give it so they will verify your inscription.

Do you remember your password ? If not I have to ask them to reinitialize it.




De : garfield69 <notifications@github.com>
À : Jackett/Jackett <Jackett@noreply.github.com>
Sujet : Re: [Jackett/Jackett] [REQ] New tracker Bettyboop-tk (#4919)
Date : 31/07/2019 21:50:54 Europe/Paris
Copie à : nikogaug <nikogaug@hotmail.com>;
   Mention <mention@noreply.github.com>

@nikogaug the username I use is garfield1969 and the email is garfieldsixtynine @ gmail.com

**Comment by garfield69** [comment]
@nikogaug wrote:
>Is it the same username for Genration Rosco tracker ?

yes.

>Do you remember your password ?

yes.

**Comment by garfield69** [comment]
http://bettyboop-tk.biz/ returning ERR_NAME_RESOLUTION_FAILED
