### ISSUE TITLE
An italian tracker?

### ISSUE THREAD

**Issue by JDrillz** [Jackett/Jackett#492]
Hi guys, I would like to know if it's possible to add at least one italian private tracker.

Thanks

**Comment by savahu** [comment]
Do you have examples of good italian trackers?

**Comment by JDrillz** [comment]
Sure! These are probably the best (that I know):

Free: hdtorrents.it (the italian version of hdts.ru, already present in Jackett) 
Donation: hd-world.net

**Comment by JDrillz** [comment]
So, is it possible?

**Comment by giopas** [comment]
that would be great indeed!

**Comment by JDrillz** [comment]
Can you help us, @kaso17 ?

Thanks

**Comment by kaso17** [comment]
AFAIK public trackers are not accepted. If you can send an invite for private trackers to kaso1717 -at- gmail.com I can add it.

**Comment by JDrillz** [comment]
Thanks for your answer kaso, all these are private trackers, I'll send you a mail asap.

**Comment by JDrillz** [comment]
Mail sent on October 5

**Comment by kaso17** [comment]
@JDrillz I didn't get any email/invite on Oct. 5

**Comment by JDrillz** [comment]
That's very strange, I just sent you another mail, let me know.
Thanks

**Comment by kaso17** [comment]
got it, will work on it soon

**Comment by giacomofabbri** [comment]
Oh yeas please add the support!! It will be awesome!
@JDrillz ciao, non è che potresti mandarmi un invito per arabafenice.me?? Per favore, è da una vita che vorrei entrare, ora ho ha disposizione un dedi con 250Mbps Unmetered quindi sarei in grado di seedare ed aiutare la comunità! Grazie mille

**Comment by JDrillz** [comment]
Ciao giacomo, mi spiace ma attualmente non ho inviti per arabafenice, non ho potuto darlo neanche a kaso :/

**Comment by giacomofabbri** [comment]
Peccato! Ma c'è roba interessante?? O è meglio TNT?? In confronto?? Si può compare un invito?? Sarei curioso di vedere!!

**Comment by kaso17** [comment]
a short update:
shareisland is on my todo list
For hdtorrents.it I'll need a Italian VPN/proxy (HTTP) which works with the tracker as they're doing stupid geoblocking.

**Comment by giacomofabbri** [comment]
You can use Tunnelbear for a free VpN!!

**Comment by JDrillz** [comment]
Thanks kaso, have you tried the giacomofabbri's suggestion yet (Tunnelbear)?

**Comment by kaso17** [comment]
not yet as it looks like a VPN solution and I would have to interrupt a lot of background tasks to implement it. I would prefer a simple HTTP/socks proxy which I can just use for one application.

**Comment by JDrillz** [comment]
What about this?
h**p://www.cameratanuova.com/proloco/navigazione/

It works to me.

**Comment by kaso17** [comment]
That's just a regular website loading another website. I can't easily use this together with Jackett

**Comment by JDrillz** [comment]
Hi, I can't see Shareisland in Jackett, is it still WIP?

**Comment by kaso17** [comment]
WIP?
Shareisland is included and working fine for me.

**Comment by JDrillz** [comment]
I was looking in the "configured indexers" table, and there wasn't the shareisland logo. Should I add it through Torznab, directly on Sonarr? How should I configure this?

![immagine](https://cloud.githubusercontent.com/assets/21334032/20802005/ea1dd4f2-b7ea-11e6-88b4-45f2469534b8.png)

I'm sorry, this is the first time I use Jackett (because previously there wasn't italian trackers, obviously).

**Comment by kaso17** [comment]
No, you've to add the indexer in Jackett first, click on the plus/Add and look for the shareisland tracker.
This is the logo used in jackett:
https://github.com/Jackett/Jackett/blob/master/src/Jackett/Content/logos/shareisland.png

**Comment by JDrillz** [comment]
So I was doing right, but the problem still remain. I haven't the logo:

![immagine](https://cloud.githubusercontent.com/assets/21334032/20829904/6df59542-b87e-11e6-86f9-4a42bd072ff7.png)

This is a partial screenshot, ShareIsland should be between SceneTime and Shazbat.

I'm using Jackett in the Synology app version, could be this the reason why?

**Comment by kaso17** [comment]
Can you please post the log output during the startup of Jackett. The Synology package might not include the new cardigann indexers.

**Comment by JDrillz** [comment]
I send you the screenshots, because Synology doesn't allow me to copy the log...
I'm sorry for the inconvenience...

[SCREENS](https://www.flickr.com/gp/117481383@N07/U580ic)

The "shareisland" voices in the last screens are certainly my attempts to make it work, nothing more.

**Comment by kaso17** [comment]
It looks like the yml files are no installed with the Synology package. Please have a look at the following directory: /volume1/@appstore/jackett/share/jackett/Definitions
I assume it doesn't exist/is empty.

The following files should be in the directory:
https://github.com/Jackett/Jackett/tree/master/src/Jackett/Definitions

I suggest you download the latest release manually and copy the Definitions directory to your Synology manually.

Maybe @Dr-Bean knows it it's related to the Synology packaging.

**Comment by JDrillz** [comment]
You're right, "Definitions" folder doesn't exist in that directory.
Mine is the latest Jackett release for Synology from the SynoCommunity source (v0.7.33-1).
I tried to create the folder "Definitions" and to add a shareisland.yml, but nothing changes, logo doesn't appear. This is the situation:

[SCREENS](https://www.flickr.com/gp/117481383@N07/Dn289n)

I did not know how to download your shareisland.yml, so I created a new file with notepad++, copied/pasted the text and saved as .yml. It should be the same.

**Comment by Dr-Bean** [comment]
I can only assume that the updater fails to create the directories (the `Content` dir isn't created either, for example), so that might be worth investigating here.

I'll set up a new package release for 0.7.713: the dirs will be created during that process, and subsequent jackett updates can hopefully add/change the contents without issues.

**Comment by JDrillz** [comment]
Thanks Dr-Bean, I will wait anxiously :)

**Comment by Dr-Bean** [comment]
Jackett 0.7.713-2 has been published on the SynoCommunity repository.

@kaso17 Below what updater.log has to say when updating from a Jackett version that does not include the `Definitions` dir (just one snippet, it's more of the same for each of the files afaict).
I don't know how Jackett's updater works, but can you confirm it does try to create the directories before attempting to copy the files? Log doesn't show that unfortunately.
```
2016-12-07 12:24:01.1497 Info Copying alphareign.yml 
Error System.IO.DirectoryNotFoundException: Destination directory not found: /volume1/@appstore/jackett/share/jackett/Definitions
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, Boolean overwrite) <0x4310d898 + 0x00474> in <filename unknown>:0 
  at Jackett.Updater.Program.ProcessUpdate (Jackett.Updater.UpdaterConsoleOptions options) <0x42ef71e8 + 0x00463> in <filename unknown>:0  System.IO.DirectoryNotFoundException: Destination directory not found: /volume1/@appstore/jackett/share/jackett/Definitions
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, Boolean overwrite) <0x4310d898 + 0x00474> in <filename unknown>:0 
  at Jackett.Updater.Program.ProcessUpdate (Jackett.Updater.UpdaterConsoleOptions options) <0x42ef71e8 + 0x00463> in <filename unknown>:0
[..]
```

**Comment by kaso17** [comment]
@Dr-Bean you were right, directories weren't created by the updater, thank you for debugging
Updater should be fixed with bfdc5043ebe972336d585daf956cab49aa7d28a2

**Comment by JDrillz** [comment]
Hi guys, good news and bad news. Now the logo appears, and I can generate the Tornznab Host url:

![1](https://cloud.githubusercontent.com/assets/21334032/21074422/22599e2c-bef9-11e6-8f55-80585c15068d.jpg)

BUT, if I try to start the tests on Jackett and on Sonarr, they fails. This is Jackett:

![ewr](https://cloud.githubusercontent.com/assets/21334032/21074428/4762c806-bef9-11e6-97eb-1b30921b670c.JPG)

And this is Sonarr:

![2](https://cloud.githubusercontent.com/assets/21334032/21074444/8bb61580-bef9-11e6-81a7-6daf9bf4fb33.JPG)

**Comment by kaso17** [comment]
what does the log say?

**Comment by JDrillz** [comment]
This is a partial log from Jackett (I think there are a lot of repetitions in the cutted part, due to several attempts):

[LOG](http://pastebin.com/nz0NKvfV)

Tell me if you need the entire log.
Thanks!

**Comment by kaso17** [comment]
yes, please include the complete log. With that HTML response it's working fine for me

**Comment by kaso17** [comment]
And please also try to update to the latest version. If you still see logos you're on an old version.

**Comment by JDrillz** [comment]
Test passed! After the Jackett's update I had to change the Mono path, as done before the update (I had to do it again). Now the indexer is successfully added. There's only one little problem...
I tried to search Elementary Season 4, on Shareisland (website) I can see many episodes (not every, but don't care), but Jackett only finds (and correctly adds to queue) the episode 18, why? Is there a nomenclature problem?

**Comment by JDrillz** [comment]
And currently Jackett doesn't start anymore...

**Comment by kaso17** [comment]
The shareisland search requires an exact match which makes it very annoying.
fbfee66c7b26865af9f34937a93c2b36dd26e1a1 should improve the search results.
But you still have to get sonarr to search for "Elementary 4x17" as there are no "Elementary S04E17" torrents.

Please post a a log of your jackett not starting.

**Comment by JDrillz** [comment]
Now Jackett works again, and I've done nothing... 

Anyway, about the searching problem, it's strange... It finds:

Elementary.4x18.**Title**.ITA.DLMux.x264-UBi.mkv
and
Elementary.4x19.**Title**.ITA.DLMux.x264-UBi.mkv

but it doesn't find:

Elementary.4x17.**Title**.ITA.DLMux.x264-UBi.mkv

It doesn't make any sense, it's the same format.

I'm using this "media management" setting on Sonarr: **Series Title (2010) - 1x01 - Episode Title (1)**

Are you suggesting to replace the red line with the green line (in the fbfee66 link), right? Done, but nothing changes, unfortunately :/
Thanks for all your support, kaso :)

**Comment by kaso17** [comment]
Just changing the line will completely break the indexer, make sure you're running v0.7.817.
Please enable "Enhanced logging" , start a sonarr search and send me the log of jackett.

**Comment by JDrillz** [comment]
Ok, I restored the old line, my version is 0.7.713-2 (the last available for Synology, the one made by Dr. Bean).

```
Dec 19, 2016 07:21:45 PM Info 
Found 0 releases from Shareisland for: Elementary S04E15
Dec 19, 2016 07:21:43 PM Info 
Found 0 (0 new) releases from Shareisland
Dec 19, 2016 07:21:40 PM Info 
Found 0 releases from Shareisland for: Elementary S04E14
Dec 19, 2016 07:21:38 PM Info 
Found 0 (0 new) releases from Shareisland
Dec 19, 2016 07:21:36 PM Info 
Found 0 releases from Shareisland for: Elementary S04E13
Dec 19, 2016 07:21:34 PM Info 
Found 0 (0 new) releases from Shareisland
```

I suppose that the problem is the one that you told me before, the "S04E14" instead of "4x14", but my Sonarr should be ok:

![cattura](https://cloud.githubusercontent.com/assets/21334032/21324562/991439d4-c622-11e6-8fdc-9106ea6e76b9.JPG)

Probably this is not the proper section to edit...

**Comment by kaso17** [comment]
yes, the SXXEYY format is the problem, you've to make sonarr use XxY for searching.
But I'm not sure if you can change it.
The screenshot just shows the media settings for renaming files (after they've been downloaded)

**Comment by JDrillz** [comment]
Mmm... what's your suggestion? Should I try to ask in the Sonarr forum?

**Comment by kaso17** [comment]
yes

**Comment by JDrillz** [comment]
On second thought, I'm not so sure that the problem is the SXXEYY format.
As previously said, Sonarr finds

Elementary.4x18.Title.ITA.DLMux.x264-UBi.mkv
and
Elementary.4x19.Title.ITA.DLMux.x264-UBi.mkv
but not:
Elementary.4x17.Title.ITA.DLMux.x264-UBi.mkv

If the problem were the SXXEYY format, it shouldn't have find the episodes 18/19 neither. Do you agree?

**Comment by kaso17** [comment]
My expectation: Sonarr should find new releases (parsing the latest torrents) but not using automatic/manual search feature for single episodes. Please provide the sonarr and jackett log showing the failed search´.

**Comment by JDrillz** [comment]
This is Sonarr:
```
16-12-29 11:27:20.2|Info|NzbSearchService|Searching 2 indexers for [Elementary : S04E16] 
16-12-29 11:27:21.2|Info|DownloadDecisionMaker|Processing 8 releases 
16-12-29 11:27:22.4|Info|EpisodeSearchService|Episode search completed. 0 reports downloaded. 
16-12-29 11:27:22.7|Info|NzbSearchService|Searching 2 indexers for [Elementary : S04E17] 
16-12-29 11:27:23.5|Info|DownloadDecisionMaker|Processing 8 releases 
16-12-29 11:27:24.7|Info|EpisodeSearchService|Episode search completed. 0 reports downloaded.
```

And Jackett:

```
Dec 29, 2016 11:27:23 AM Info 
Found 0 releases from Shareisland for: Elementary S04E17
Dec 29, 2016 11:27:21 AM Info 
Found 0 releases from Shareisland for: Elementary S04E16
```

**Comment by kaso17** [comment]
If you do a manual search for E18/19 you most likely won't find them either.
Sonarr most likely picket them up during the normal refresh circle (when they were new).
Most likely S04E20 will be picked up automatically too.
But you can't search for old episodes.

I've opened #901 which should help with the problem.

**Comment by JDrillz** [comment]
Again, thank you so much for your help, kaso :)

**Comment by rafuz** [comment]
Hello!

any news for adding hdtorrents.it??
It would be nice to have this tracker for italian content

**Comment by kaso17** [comment]
It's at the end of my list due to their geo blocking (I hate geo blocking).

**Comment by rafuz** [comment]
I am sorry for the geoblocking... 
Would you consider to try the integration if I provide you a vpn access in Italy?

**Comment by rafuz** [comment]
There is still some problem with shareisland, a search like that from couchpotato does not work:
`http://localhost:9117/potato/shareisland?imdbid=tt1431045&search=Deadpool+2016&user=&passkey=xxx`

If I search manually in jackett I can't find it even using only the word "Deadpool" without the year but I can find results if I use it in the website, so something seems to be wrong with the plugin.

**Comment by kaso17** [comment]
@rafuz 2cc451ebef8803a319d1ea1e1534528efadefc88 should fix the "search with year" issue.
I definitely will need a VPN to implement it but having one doesn't give it a higher prio, sorry.
Try to convince the site staff to remove the geo blocking if you want to accelerate the implementation :)

**Comment by JDrillz** [comment]
> If you do a manual search for E18/19 you most likely won't find them either.
> Sonarr most likely picket them up during the normal refresh circle (when they were new).
> Most likely S04E20 will be picked up automatically too.
> But you can't search for old episodes.
> 
> I've opened #901 which should help with the problem.

News about the XXxYY format implementation? Unfortunately currently this indexer is useless :( (the 99% of all releases are XXxYY)

> Try to convince the site staff to remove the geo blocking if you want to accelerate the implementation :)

I'll try to ask him :)

**Comment by kaso17** [comment]
no news

**Comment by Jorman** [comment]
Hi, also http://ilcorsaronero.info/ can be a good traker to add

**Comment by kaso17** [comment]
@Jorman: please open a new issue to it.

**Comment by Jorman** [comment]
I'll @kaso17 
Btw, I update to the last pre-release and I see that shareisland is not present, why? I came from the last stable version and shareisland works good.

**Comment by kaso17** [comment]
@Jorman please post the log file (log.txt).
The most recent version contained several dependency updates which might cause a problem on some systems.

**Comment by Jorman** [comment]
ok, but I can leave shareisland active?

**Comment by kaso17** [comment]
If it disappeared and you can't re-add it again, it shouldn't work anymore.
Please post the logs so I can try to fix the issue.

**Comment by Jorman** [comment]
Hey, I came from an older version with shareisland, now shareisland works.
Here the log http://pastebin.com/z3c9EYh2

**Comment by kaso17** [comment]
@JDrillz ba14fab0a1c971404d9f26dd30c7b81ae0434f83 added S/E format normalization, please give it a try.

**Comment by JDrillz** [comment]
Thanks for your work @kaso17 , I appreciate it! I'll try :). 
In the meantime I probably just found (and solved, hopefully) another problem that I had with this tracker. In the "quality profiles" of Sonar, I had selected WEBDL-720p and WEBDL-1080p as qualities, but nothing was working, so I decided to download the files manually (from ShareIsland). I just noticed that in the page of the show (of Sonar), these episodes are recognised as HDTV, not as WEBDL. The episodes, actually, are named as DLMUX on ShareIsland, and a DLMUX is like a WEBDL, not an HDTV, but probably this tag is not used all over the world. Anyway, I just added HDTV-720p and HDTV-1080p as "quality", we'll see :)

**Comment by kaso17** [comment]
You might want to open an issue at Sonarr and ask for the DLMUX tag to be added.

**Comment by JDrillz** [comment]
Sure, I'll do it :)
Anyway, tonight it worked well, 2 episodes downloaded correctly.
In the meantime, I tried to ask to HD Torrent admin to remove the geo blocking, but he doesn't seems interested to do this. He told me to use (obviously) a VPN. :/

**Comment by kaso17** [comment]
closing this issue, please continue discussion in existing/new threads

**Comment by BomberDM** [comment]
Ciao ragazzi è possibile avere un invito su arabafenice.me?
