### ISSUE TITLE
[REQ] New tracker Génération Rosco

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#4920]
Name : Génération Rosco
URL : http://genration-rosco-tk.net/
Type : Movie/TV/General
Genre : semi-private
Language : french

Great thanks,

**Comment by garfield69** [comment]
registration appears to be broken.
![image](https://user-images.githubusercontent.com/6933240/61989422-233e4a80-b083-11e9-95d9-e7b70b95ab5e.png)

**Comment by pipopop** [comment]
I send a message to him. The site as change recently (TTV3), and I can't connect too.

**Comment by pipopop** [comment]
It could be a wrong message. I had the same, but I can log in with my username / password

**Comment by garfield69** [comment]
No, it definitely did not accept my registration. Trying to login results in an error.

**Comment by garfield69** [comment]
looks like http://genration-rosco-tk.net/ is gone. returning ERR_NAME_NOT_RESOLVED
