### ISSUE TITLE
[torrent9] Exception (torrent9): Error: NameResolutionFailure: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by darkcattz** [Jackett/Jackett#4922]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.11.58.0
**Mono version** (if not using Windows):  Synology 5.8.0.108-11

-------------------------------

Hello,

Error : 

Jackett.Common.IndexerException: Exception (torrent9): Error: NameResolutionFailure ---> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: NameResolutionFailure
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00058] in <6b85ae33ded1428e932cb7ae66272042>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0 
--- End of stack trace from previous location where exception was thrown ---

**Comment by garfield69** [comment]
try changing the sitelink to https://ww1.torrent9.uno/

**Comment by garfield69** [comment]
or even better https://wvw.t9.pe/
