### ISSUE TITLE
[idopeclone] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by NyanCatZ06** [Jackett/Jackett#4926]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by NyanCatZ06** [comment]
Trying to add iDope 2019 to list of trackers.  when I test, gets an error.
using https://idope.xyz/ as tracker address.  if go directly to site, arrive at search page and can successfully search.  Test does not work, gets 404 error and redirected.

**Comment by NyanCatZ06** [comment]
Error from Jackett: 
An error occured while testing this indexer
Found no results while trying to browse this tracker

**Comment by garfield69** [comment]
idope changed the way they present results and is no longer compatible with the cardigann engine.
the idope indexer will need rewriting as a native c# indexer, and request ticket #4841 will track its implementation, which is pending a c# dev to volunteer
