### ISSUE TITLE
Unable to force host/ip

### ISSUE THREAD

**Issue by noamanahmed** [Jackett/Jackett#4932]
Hello

I am trying to  install jacket but the Jackett keeps attaching to IPV6 .I need to force ipv4 .
There is not much in options to force to listen to specific host/ip
 
Mono version 

Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

Jackett v0.11.102.0

An option like this would be nice
  /etc/Jackett/jackett --listen-address 127.0.0.1

**Comment by flightlevel** [comment]
Instructions here https://github.com/Jackett/Jackett/issues/3583#issuecomment-416913013
