### ISSUE TITLE
Updater does not seem to actually update

### ISSUE THREAD

**Issue by pathsny** [Jackett/Jackett#4939]
**Jackett version**:  0.11.53.0
**Mono version** (if not using Windows):  5.10.1.57
Running on freebsd (In a freenas jail)
When I run the update process, it discovers the newer update, but then the actual running version remains the same. Please see logs in the linked gist

https://gist.github.com/pathsny/d5026d25de0c2368bb2f9990cc3e9cd1

**Comment by garfield69** [comment]
yes, there were a few releases published that had a broken updater.
manually install the latest release to fix the problem.
