### ISSUE TITLE
[Space-torrent] All torrent found as dead torrent

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#4943]
When searching for torrent in Jackett for Space Torrent tracker, all torrents are returned as dead torrents. Even if they are not.

**Jackett version**:  0.11.102.0
On Windows 10 1803

**Comment by garfield69** [comment]
that is because when you do a torrent search on the site there does not appear to be a single torrent that has a seeder. in fact  the page shows an info icon which displays `Ce torrent ne possède pas de seeder`.
this is why jackett shows seeder=0 instead.

**Comment by garfield69** [comment]
oh, and at the bottom of the sites torrent listing is the following:
` Pourquoi je vois pas les seeders/leechers ? Cette option a été supprimé de l'affichage des torrents dans un soucis de confidentalité et de sécurité. A la place, un système d'icônes colorées permet de savoir si un torrent possède des seeders.`
