### ISSUE TITLE
[OurBits] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#4944]
I get the following error when searching or testing OurBits:
Found no results while trying to browse this tracker

Enhanced log attached.
[log.txt](https://github.com/Jackett/Jackett/files/2998523/log.txt)

**Jackett version**: 0.11.107.0
**Mono version** (if not using Windows): N/A

**Comment by garfield69** [comment]
If you are able to send an invite to garfieldsixtynine @ gmail.com I can check this out properly.

**Comment by garfield69** [comment]
Try out Jackett v0.11.115

**Comment by RoloSoze** [comment]
Works fine now! Thank you.
