### ISSUE TITLE
 Error Error checking for updates. System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: TrustFailure (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by JackieMo0n** [Jackett/Jackett#4945]
Unable to update Jackett and all indexers fail with similar issue. 
I am unable to find a solution after browsing other issues on the web

Here is the log.

Error Error checking for updates. System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: TrustFailure (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
Mar 23 10:35:04 raspberrypi jackett[447]:   at /build/mono-5.18.1.0/external/boringssl/ssl/handshake_client.c:1132
Mar 23 10:35:04 raspberrypi jackett[447]:   at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00047] in /build/mono-5.18.1.0/mcs/class/System/Mono.Btls/MonoBtlsContext.cs:211
Mar 23 10:35:04 raspberrypi jackett[447]:   at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x000a1] in /build/mono-5.18.1.0/mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs:821
Mar 23 10:35:04 raspberrypi jackett[447]:   at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
Mar 23 10:35:04 raspberrypi jackett[447]:   at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00000] in /build/mono-5.18.1.0/mcs/class/System/Mono.Net.Security/AsyncProtocolRequest.cs:283
Mar 23 10:35:04 raspberrypi jackett[447]:   at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x000ff] in /build/mono-5.18.1.0/mcs/class/System/Mono.Net.Security/AsyncProtocolRequest.cs:221
Mar 23 10:35:04 raspberrypi jackett[447]:   at Mono.Net.Security.AsyncProtocolRequest.StartOperation (System.Threading.CancellationToken cancellationToken) [0x00046] in /build/mono-5.18.1.0/mcs/class/System/Mono.Net.Security/AsyncProtocolRequest.cs:187
Mar 23 10:35:04 raspberrypi jackett[447]:    --- End of inner exception stack trace ---
Mar 23 10:35:04 raspberrypi jackett[447]:   at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x0024c] in
/build/mono-5.18.1.0/mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs:396
Mar 23 10:35:04 raspberrypi jackett[447]:   at Mono.Net.Security.MonoTlsStream.CreateStream (System.Net.WebConnectionTunnel tunnel, System.Threading.CancellationToken cancellationToken) [0x00126] in /build/mono-5.18.1.0/mcs/class/System/Mono.Net.Security/MonoTlsStream.cs:129
Mar 23 10:35:04 raspberrypi jackett[447]:   at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x00170] in /build/mono-5.18.1.0/mcs/class/System/System.Net/WebConnection.cs:222
Mar 23 10:35:04 raspberrypi jackett[447]:    --- End of inner exception stack trace ---
Mar 23 10:35:04 raspberrypi jackett[447]:   at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x00208] in /build/mono-5.18.1.0/mcs/class/System/System.Net/WebConnection.cs:234
Mar 23 10:35:04 raspberrypi jackett[447]:   at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x000f7] in /build/mono-5.18.1.0/mcs/class/System/System.Net/WebConnection.cs:263
Mar 23 10:35:04 raspberrypi jackett[447]:   at System.Net.WebOperation.Run () [0x00052] in /build/mono-5.18.1.0/mcs/class/System/System.Net/WebOperation.cs:268
Mar 23 10:35:04 raspberrypi jackett[447]:   at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x0008e] in /build/mono-5.18.1.0/mcs/class/System/System.Net/WebCompletionSource.cs:111
Mar 23 10:35:04 raspberrypi jackett[447]:   at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts)
[0x000e8] in /build/mono-5.18.1.0/mcs/class/System/System.Net/HttpWebRequest.cs:956
Mar 23 10:35:04 raspberrypi jackett[447]:   at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00019] in
/build/mono-5.18.1.0/mcs/class/System/System.Net/HttpWebRequest.cs:1200
Mar 23 10:35:04 raspberrypi jackett[447]:   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <51aae36473e7439cb14534b3d8714641>:0
Mar 23 10:35:04 raspberrypi jackett[447]: --- End of stack trace from previous location where exception was thrown ---
Mar 23 10:35:04 raspberrypi jackett[447]:   at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x003d3] in /build/mono-5.18.1.0/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.cs:402
Mar 23 10:35:04 raspberrypi jackett[447]:    --- End of inner exception stack trace ---
Mar 23 10:35:04 raspberrypi jackett[447]:   at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x0046c] in /build/mono-5.18.1.0/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.cs:406
Mar 23 10:35:04 raspberrypi jackett[447]:   at CloudFlareUtilities.ClearanceHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00102] in <f1c2217fc655412a84a399ed529a3107>:0
Mar 23 10:35:04 raspberrypi jackett[447]:   at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request,
System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x00080] in /build/mono-5.18.1.0/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs:276
Mar 23 10:35:04 raspberrypi jackett[447]:   at Jackett.Utils.Clients.HttpWebClient.Run (Jackett.Utils.Clients.WebRequest webRequest) [0x00401] in C:\projects\jackett\src\Jackett.Common\Utils\Clients\HttpWebClient.cs:211
Mar 23 10:35:04 raspberrypi jackett[447]:   at Jackett.Utils.Clients.WebClient.GetString (Jackett.Utils.Clients.WebRequest request) [0x000c1] in C:\projects\jackett\src\Jackett.Common\Utils\Clients\WebClient.cs:117
Mar 23 10:35:04 raspberrypi jackett[447]:   at Jackett.Services.UpdateService.CheckForUpdates () [0x000c4] in C:\projects\jackett\src\Jackett.Common\Services\UpdateService.cs:96

**Jackett version**:  0.8.450.0
**Mono version** (if not using Windows):  5.18.10 on raspberry pi 3B+

-------------------------------

**Comment by garfield69** [comment]
It looks like your mono package is broken and your https handshaking or certificate verification is not working.
So instead of  installing the Jackett mono package, try installing the .net core package (which does not require mono), for instance Jackett.Binaries.LinuxARM32.tar.gz from https://github.com/Jackett/Jackett/releases/tag/v0.11.107
and see if that solves your problem.

**Comment by garfield69** [comment]
Oh, also read https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above to learn abour the new startup requirements.

**Comment by JackieMo0n** [comment]
Yes this solved my issue, thankyou
Installed Jackett without mono and everything worked
