### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on http://www2.yggtorrent.gg/ using form selector 

### ISSUE THREAD

**Issue by gotson** [Jackett/Jackett#4946]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.11.107.0
**Mono version** (if not using Windows):  

-------------------------------

Since recently the login form for Yggtorrent doesn't work anymore with Jackett.

Detailed log: https://gist.github.com/gotson/14dd97873ebc5ca2584622c5f5a4e9c7

**Comment by garfield69** [comment]
it appears that you have your YGG Site link set to http://www2.yggtorrent.gg/ which will not work for this indexer.

on your jackett dashboard, use the wrench icon to edit the config and set the **Site Link** is set to `https://www.yggtorrent.gg/` and the **Search and download URL** is set to `www2.yggtorrent.gg`
click OKAY and you should be good to go.

**Comment by gotson** [comment]
Hi, tried your suggestion but i have the same error.

**Comment by garfield69** [comment]
yeah, I've added your original sitelink as a legacylink so it will auto-switch the next time it happens to someone else.

**Comment by tlkops** [comment]
Hello,

Having the same error and switching to other url don't change anything:
Exception (yggtorrent): Login failed: No form found on https://www.yggtorrent.gg/ using form selector #user-login: Parse error

**Comment by TimmyOtool** [comment]
Same for me, try to change url but still the "Login failed: No form found" error.

**Comment by garfield69** [comment]
Use the wrench icon on your jackett dashboard to edit the config and set the **Site Link** to `https://www.yggtorrent.gg/` and the **Search and download URL** to `www2.yggtorrent.gg`.
If clicking **OKAY** generates an error, just click **CLOSE**, and edit the config again.
Then click OKAY and you should be good to go.

**Comment by TimmyOtool** [comment]
Thanks, it's working after changing the site link in the config
