### ISSUE TITLE
[cpasbien] Exception (cpasbien): Request to https://www.cpasbien.vg/ failed (Error Forbidden) - The page is protected by an Cloudflare reCaptcha. (Test)

### ISSUE THREAD

**Issue by Doduf57** [Jackett/Jackett#4949]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

Hello,

Is there any option Jackett can have to bypass the reCapcha from Cpasbien ? 
My IP is not blacklisted, I can access it from my own computer.

Thanks,
Best Regards

**Comment by garfield69** [comment]
I dont think so, but @kaso17 is the one who may be able to answer this definitively.

**Comment by kaso17** [comment]
this can't be byepassed and must be related to your IP reputation or temporary attack mode

**Comment by Doduf57** [comment]
Thanks @kaso17 for your reply. It's a pleasure to contribute to the Jackett project. I will try to connect my server to a VPN (Own Cloud Server). I'm connecting to an ISP with a shared public IP, I will check the IP reputation too.

Best regards,
