### ISSUE TITLE
Invite needed to fix BitTorrentFiles [Invites are open atm til 31.3]

### ISSUE THREAD

**Issue by Keksfeier** [Jackett/Jackett#4952]
Please someone send the dev an invite for btf. 
Invites are opten til 31.3

 Invite to  garfieldsixtynine @ gmail.com

**Comment by garfield69** [comment]
is there are problem with the btf indexer at the moment?

**Comment by Keksfeier** [comment]
> is there are problem with the btf indexer at the moment?

yes, also it says [invite needed] on mainppage

**Comment by garfield69** [comment]
btf appears to be down ATM
![image](https://user-images.githubusercontent.com/6933240/54880527-50e36f00-4eaa-11e9-9064-7cc80dd5124b.png)

**Comment by Keksfeier** [comment]
![Unbenannt](https://user-images.githubusercontent.com/48414067/54880646-3035fd80-4e47-11e9-8fb7-c2d9877c61d6.PNG)

hm nope its working

**Comment by garfield69** [comment]
classic. yup back up again for me too.
so what is the problem that you are seeing when you use this jackett indexer?

**Comment by Keksfeier** [comment]
Found no results while trying to browse this tracker (Test)


`

When | Level | Message
-- | -- | --
Mar 24, 2019 03:19:38 PM | Error | System.Exception: Found no results while trying to browse this tracker   at Jackett.Common.Services.IndexerManagerService.TestIndexer (System.String name) [0x000e8] in <b381bb3df4b94dba8868360a73af9631>:0    at Jackett.Server.Controllers.IndexerApiController.Test () [0x000e1] in <48090df526af4811a34975c18e4b6440>:0    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00115] in <dd7bbb1eb6cb4178a82cd5136b2606b8>:0    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <48090df526af4811a34975c18e4b6440>:0
Mar 24, 2019 03:19:38 PM | Info | Found 0 releases from Bittorrentfiles

`

**Comment by garfield69** [comment]
In that case, given that kaso17 has been unavailable recently,
send an invite to garfieldsixtynine @ gmail.com I will take a look instead.

**Comment by Keksfeier** [comment]
Should be done

**Comment by kaso17** [comment]
I'm available too, a little busy currently but an invite to kaso1717@gmail.com would be appreciated.

**Comment by garfield69** [comment]
@Keksfeier  registration successful, my a/c is now apparently awaiting unlocking by you?

**Comment by RoloSoze** [comment]
@Keksfeier I routinely test trackers for errors, inconsistencies, missing results, etc, so if you have an invite to spare, I would really appreciate one: RoloSoze@Outlook.com - Thank you.

**Comment by Keksfeier** [comment]
@garfield69 not by me but told the inviter. @RoloSoze sorry dont have invite privilege.

**Comment by garfield69** [comment]
login successful. Thank you. I'll start working on this ticket now.

**Comment by Keksfeier** [comment]
> login successful. Thank you. I'll start working on this ticket now.

i will relay the thanks to the inviter :) thanks for supporting smaller trackers also :)

**Comment by garfield69** [comment]
Try out Jackett pre-release v0.11.133
