### ISSUE TITLE
[Feature request] Replace MULTI word with specific language

### ISSUE THREAD

**Issue by maxtop51** [Jackett/Jackett#4957]
Can setup for all indexers the Multi = Language option ? if no can you add this fonction for all the indexers.

Thanks for help

**Comment by ngosang** [comment]
I think this feature request is not clear. Could you elaborate the request?

**Comment by maxtop51** [comment]
I want something like that in Jackett Configuration if it possible :
</br>
</br>
<img width="354" alt="Capture d’écran, le 2020-01-14 à 14 50 20" src="https://user-images.githubusercontent.com/46909214/72377256-5a5df200-36dd-11ea-84b9-7a286000fb4d.png">
</br>
</br>
if is not a possibility, it is possible to add in some indexer or explain me if the feature for this option are in c# folder because I already try to add this fonction in yml so I think a part are in c# folder!? so my knowledge in this language is really poor.

**Comment by ngosang** [comment]
There are 2 kinds of indexers:
* Cardigann definitions => .yml
* C#

You can copy the current implementation of one indexer and do the text replacement yourself in the source code.

I let this issue open, but don't expect to be implemented soon.

**Comment by garfield69** [comment]
Closed as stale.
