### ISSUE TITLE
[REQ]zone-torrent migration

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#4961]
French tracker zone-torrent is moving to www.tigers-dl.net.

**Comment by garfield69** [comment]
Umm, do not have zone-torrent (www.zt-v2.eu) on Jackett
can you expand on what you would like us to do?

**Comment by skuizy** [comment]
Indeed ! I thought this tracker was in the list. I've just checked if I could invite you but it's curently closed.

**Comment by garfield69** [comment]
https://www.tigers-dl.net/index.php?page=login currently returning 
```
This page isn’t working www.tigers-dl.net is currently unable to handle this request.
HTTP ERROR 500
```
is the site gone, changed domain or just broken?

**Comment by garfield69** [comment]
now the www.tigers-dl.net domain is bringing up a site called dltorrent.net
but the certificate is for domain dltorrent.net which is invalid
but the site looks nothing like tigers so this looks like a hijack?

**Comment by garfield69** [comment]
currently returning 
![image](https://user-images.githubusercontent.com/6933240/62440696-609e8880-b7a5-11e9-8716-5e0973b2a494.png)

**Comment by garfield69** [comment]
www.tigers-dl.net currently returning ERR_CONNECTION_TIMED_OUT
is the site gone, changed domain or just broken?

**Comment by garfield69** [comment]
removed tigersdl. in the unlikely event they return we can always add them back.

**Comment by Astrem2005** [comment]
https://www.tigers-dl.net/

Need captcha now.

**Comment by garfield69** [comment]
so the site is back online, although I don't see the option to change the torrent search page to LIST mode. It seems GRID mode is the only display available right now. anyone know if LIST mode is coming back, or where to find the option to switch it?

@Astrem2005  what captcha? I did not get one on my login page?
![image](https://user-images.githubusercontent.com/6933240/69011797-2ca54700-09d3-11ea-87f9-c6ae7ef48329.png)

**Comment by garfield69** [comment]
Oh, on closer inspection, it looks like it is a different server engine than previous. I will have to rewrite the tigers-ld indexer for the new engine.

**Comment by garfield69** [comment]
Bah.
There is no point adding this indexer back right now.
the current torrent search returns posters that only have a short title
![image](https://user-images.githubusercontent.com/6933240/69012807-c8888000-09de-11ea-9ad0-b64d4a3d72b6.png)
for example
```html
</td>
<td align='center'>
    <a href=torrents-details.php?id=242'><img id='cover_img1' class='cover_img' border='2' src='uploads/images/2420.jpg' width='128px' height='177px'></a>
    <b>The.Dark.Crysta...</b> <img src='images/free.gif' border='0' alt='' />
    <font color=#375682> <b>Serie</b></font>
    /
    <font color=#375682> <b>TV HD</b></font>
    <div style='margin-top:10px; font-size:13px;'>
    <img src=images/check.png height='14' title='Completed' border=0><font color=#375682> <b>1</b></font> |
    <img src=images/arrow_up.gif height='12' title='Seeders' border=0><font color=#00AA00><b>1</b></font> |
    <img src=images/arrow_down.gif height='12' title='Leechers' border=0><font color=#FF0000> <b>0</b></font>
    </div>
</td>
```
the full title is only available on the torrent details page
`The.Dark.Crystal.Age.of.Resistance.S01.MULTi.1080p.NF.WEB-DL.DDP5.1.x264-ARK01`
