### ISSUE TITLE
TorrentSectorCrew: no results found since 0.11.141 

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#4963]
**Jackett version**:  0.11.141

@kaso17  I'm not getting any results since you last commit dfd1ec375bc467c50dbb5cab6c5fc16acafee8a1

is it working for you?

[log.txt](https://github.com/Jackett/Jackett/files/3004968/log.txt)

**Comment by kaso17** [comment]
I didn't check yet but I suspect it's caused by the different layout options.
It's working for me with the `Klassisches Layout, sehr breite Darstellung` option

**Comment by garfield69** [comment]
Ahh that's the one.
the default for new users is Platzsparendes.
I'll add an **info note** to the config to direct users to the correct layout.
