### ISSUE TITLE
[zooqle] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by aSystemOverload** [Jackett/Jackett#4964]
Can't find any other issues mentioning 'Zoogle'.
I've added Zoogle, but TEST and MANUAL SEARCH fails, returning nothing.  Logs show that data is returned.

(At the bottom of your Jackett Dashboard page) **Jackett version**:  Version 0.11.115.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**: 

Installed via aurman -S jackett

-------------------------------
[jacket_logs_2019 03 25.txt](https://github.com/Jackett/Jackett/files/3005641/jacket_logs_2019.03.25.txt)

**Comment by garfield69** [comment]
I'm a bit confused by this log you have posted.
are you using the Jackett dashboard or some 3rd party app that is using Jackett as a proxy?
I don't have any problems using the Zooqle indexer with my win10 Jackett 0.11.141 via the Jackett Dashboard on the Chrome browser.
what are you using, and on which platform?

**Comment by aSystemOverload** [comment]
Installed on Arch Linux.  Using it directly, Sonarr connects to it and triggers the Indexers listed, which are Zoogle, EZTV and ShowRSS.  Zoogle is set up with [https://zooqle.com/rss/tv/v1qsaycas.rss/], which is a my personal URL and works when pasted in to a private browser session (ie: without needing to log in).
Maybe you can add this URL to yours and see if it comes up with anything?

**Comment by garfield69** [comment]
@kaso17  @flightlevel  do you guys understand what is going on here? I'm out of my depth with this one.

**Comment by kaso17** [comment]
set the site link to https://zooqle.com/ and it should work.
Not sure what the personal URL stuff is.

**Comment by aSystemOverload** [comment]
It's a curated list of your selected TV series at the qualities you want.
I'll try it with the standard URL. Thanks.
