### ISSUE TITLE
Possible solution for memory issue (?!)

### ISSUE THREAD

**Issue by edjalmobf** [Jackett/Jackett#4966]
I have a doubt. Sorry if this is a dumb question or if I misunderstood wrong its functioning.
Every time that Sonarr and Radarr request a rss sync or a search, Jackett storage this result. 
If I have a lot of indexers Jackett will consume a lot of memory and not releasing it after the rss sync and, **mainly**, in search.
So, If Jackett clear this cache after Sonarr/Radarr request would not solve this memory issue?

To see this: 
1. look Jackett memory usage
2. do a rss sync in Sonarr or Radarr
3. look again Jackett memory usage
4. add a new indexer in Sonarr or Radarr (or wait some time for indexers get new releases)
5. do a new rss sync in Sonarr or Radarr
6. look Jackett memory usage again

**Comment by kaso17** [comment]
Keeping this open as an enhancement to limit the caching amount (was #2405 before)

**Comment by garfield69** [comment]
commit 40b0cdffc30418bf9fa56546cf02e12fd7edc8bb in jackett v0.11.224 reduces the cache size from a 7 day retention to just 1 hour.

**Comment by edjalmobf** [comment]
Thanks, guys!
Just a question before I close this. When a RSS sync or a search happens the cache will be deleted 1 hour after that, or will be deleted hourly, no matter what happened?
I ask because Sonarr's RSS sync default are 15 minutes.

**Comment by edjalmobf** [comment]
Thank you guys very much for this! In low powered devices, sometimes this is the difference between a good run an freeze up!

Now, I'm a little confuse.
In my system, when Jackett start, memory usage is something like 100M. Now, look to the screenshot, 3h after, and see memory usage. It's not suppose to memory usage come back to something like 100M after a cache clear? Why this not happend?
**Jackett version: 0.11.224.0
Variant Mono**
![Captura de Tela 2019-04-15 às 11 50 44](https://user-images.githubusercontent.com/42322017/56142508-2babc300-5f75-11e9-9f81-a4feec713c67.png)

**Comment by garfield69** [comment]
It's my understanding that the cache can consists of up to 1000 results per indexer.
anytime a new search for any indexer is initiated, the results are added to the cache.
then for all indexers in the cache, any results older than 1 hour are removed, and the remaining results (up to 1000 per indexer) are retained.
@flightlevel is the author of the commit. Have I got that right? Any additional comments on the OPs q: ?

**Comment by edjalmobf** [comment]
I think as you!
I few minutes ago I checked releases in "View cached releases" and it shows only releases of 42 minutes ago, and Jackett is running for 9h. I waited 18 minutes and checked cached releases again, and now shows some, but a few has been deleted (before had 5 pages of releases and now have just 2). But this seems not affect memory usage. Memory usage was at 160M and after an hour are in 159M 🤔

**Comment by flightlevel** [comment]
@edjalmobf  v0.11.230 has some improvements in regards to memory usage, but unlikely to be as much as you want. 200MB of memory is realistic for Jackett, further improvements are likely to require significant code changes or an updated framework from Microsoft

**Comment by edjalmobf** [comment]
@flightlevel thanks!
The workstation garbage collection is a thing that work in Mono too or just in .NET version? 
I'll update to test this!

One thing just for the record: I created a swapfile in my Raspberry Pi and this seems help a little. With swapfile sometimes Jackett use less than 100M.

**Comment by ngosang** [comment]
The new cache is merged #10447
It reduces the memory usage by default and you can fine tune the cache size.
