### ISSUE TITLE
Mono-complete dependency...

### ISSUE THREAD

**Issue by Zamana** [Jackett/Jackett#4981]
I really don't know how/where do you run Jackett, but for me, in my headless server, installing mono-complete doesn't make any sense (Adwaita? Are kidding me?).

Please, remove this non-sense dependency.

Thanks.
Regards.

**Comment by garfield69** [comment]
There is nothing preventing you downloading the .net versions of Jackett from  https://github.com/Jackett/Jackett/releases.
just pick any but the one with mono in the name!

**Comment by Zamana** [comment]
Hi!

Thanks for reply.

This one is the exactly version/release that I'm downloading, and it requires the FULL BLOATED mono-complete to work now...

Regards.

**Comment by garfield69** [comment]
what platform are you running?

**Comment by garfield69** [comment]
I may not have been clear in my original reply ...
If you are on a Linux platform of one kind or other then kiss goodbye to mono by using one of the .net packages.
I suggest downloading one of the following:
Jackett.Binaries.LinuxAMDx64.tar.gz with https://github.com/Jackett/Jackett#install-on-linux-amdx64
or
Jackett.Binaries.LinuxARM64.tar.gz  with https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above
or Jackett.Binaries.LinuxARM32.tar.gz with https://github.com/Jackett/Jackett#installation-on-linux-armv6-or-below

**Comment by Zamana** [comment]
> what platform are you running?

An LXC container (Ubuntu 18.4) inside a Proxmox environment.

**Comment by Zamana** [comment]
> I may not have been clear in my original reply ...
> If you are on a Linux platform of one kind or other then kiss goodbye to mono by using one of the .net packages.
> I suggest downloading one of the following:
> Jackett.Binaries.LinuxAMDx64.tar.gz with https://github.com/Jackett/Jackett#install-on-linux-amdx64
> or
> Jackett.Binaries.LinuxARM64.tar.gz with https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above
> or Jackett.Binaries.LinuxARM32.tar.gz with https://github.com/Jackett/Jackett#installation-on-linux-armv6-or-below

This seems pretty better.

Thanks!
