### ISSUE TITLE
[REQ] [SceneTime] Missing "Freeleech" category

### ISSUE THREAD

**Issue by iFredOS** [Jackett/Jackett#4983]
I have a request for "Freeleech" category for SceneTime. Thank you!

**Comment by garfield69** [comment]
while its true that the FreeLeech checkbox appears in the *show categories* filter box, it is not actually a category that shows up in the *type* column in the results. IT is only a switch used during search, that adds &freeleech=on to the search url.
As such I cant add it as a category that you can then select for filtering like all the other categories such as MoviesSD or TVHD etc.
![image](https://user-images.githubusercontent.com/6933240/55199291-7a8bf580-521e-11e9-9ec8-9fc0eda1035e.png)
![image](https://user-images.githubusercontent.com/6933240/55199763-ff2b4380-521f-11e9-9bf9-13c7d9234b9b.png)

What I could do is add a config option checkbox to either always filter by freeleech, or not.
But obviously this is not a dynamic filter you can use, you would need to edit the config anytime you wanted to change the setting.
Do you want me to add this option in that way?

**Comment by iFredOS** [comment]
Yes please. I appreciate. 😄

**Comment by garfield69** [comment]
Try out Jackett v0.11.154
