### ISSUE TITLE
[Yggtorrent] Search season pack KO

### ISSUE THREAD

**Issue by Neocide62** [Jackett/Jackett#4987]
Hello,

i have a problem when i do a manual search with Jackett for season pack.

When i use this request :

localhost:9117/torznab/yggtorrent/api?t=tvsearch&apikey=x5t6jrbgx... &offset=0&limit=100&rid=153021&q=the+walking+dead&season=1&cat=5000

i have all this item :
`grep title jackett.txt
    <title>YGGtorrent</title>
      <title>YGGtorrent</title>
      <title>The.Walking.Dead.S09E15.VOSTFR.WEBRip.x264-OvD</title>
      <title>The.Walking.Dead.S09E15.VOSTFR.PROPER.HTDV.XviD-exPM5</title>
      <title>The.Walking.Dead.S09E15.VOSTFR.720p.WEBRip.x265-NSP</title>
      <title>The.Walking.Dead.S09E15.VOSTFR.1080p.WEBRip.x265-NSP</title>
      <title>The.Walking.Dead.S09E15.VOSTFR.1080p.AMZN.WEB-DL.DD+5.1.H.264-Tinker</title>
      <title>The.Walking.Dead.S09E15.SUBFRENCH.720p.HDTV.x264-SH0W</title>
      <title>The.Walking.Dead.S09E15.SUBFRENCH.HDTV.x264-AMB3R</title>
      <title>The.Walking.Dead.S09E14.VOSTFR.PROPER.HTDV.XviD-exPM5</title>
      <title>The.Walking.Dead.S09E14.VOSTFR.PROPER.720p.HDTV.x264-exPM5</title>
      <title>The.Walking.Dead.S09E14.VOSTFR.WEBRip.x264-OvD</title>
      <title>The.Walking.Dead.S09E14.VOSTFR.720p.WEBRip.x265-NSP</title>
      <title>The.Walking.Dead.S09E14.VOSTFR.1080p.WEBRip.x265-NSP</title>
      <title>The.Walking.Dead.S09E14.VOSTFR.1080p.AMZN.WEB-DL.DD+5.1.h264-Tinker</title>
      <title>The.Walking.Dead.S09E14.VOSTFR.1080p.AMZN.WEB-DL.DD5.1.x264-ARK01</title>
      <title>The.Walking.Dead.S09E11.VOSTFR.720p.WEBRip.x265-NSP</title>
      <title>The.Walking.Dead.S09E12.VOSTFR.720p.WEBRip.x265-NSP</title>
      <title>The.Walking.Dead.S09E13.VOSTFR.1080p.AMZN.WEB-DL.DD5.1.x264-ARK01</title>
      <title>The.Walking.Dead.S09E11.VOSTFR.1080p.WEBRip.x265-NSP</title>
      <title>The.Walking.Dead.S09E12.VOSTFR.1080p.WEBRip.x265-NSP</title>
      <title>The.Walking.Dead.S09E13.VOSTFR.1080p.WEBRip.x265-NSP</title>
      <title>The.Walking.Dead.S09E13.VOSTFR.WEBRip.x264-OvD</title>
      <title>The.Walking.Dead.S09E13.VOSTFR.720p.WEBRip.x265-NSP</title>
      <title>The.Walking.Dead.S09E13.Chokepoint.VOSTFR.1080p.AMZN.WEB-DL.DD+5.1.H.264-CasStudio</title>
      <title>The.Walking.Dead.S09E13.Chokepoint.VOSTFR.720p.AMZN.WEB-DL.DD+5.1.H.264-CasStudio</title>
      <title>The.Walking.Dead.S09E13.VOSTFR.PROPER.HTDV.XviD-exPM5</title>
      <title>The.Walking.Dead.S09E13.VOSTFR.PROPER.720p.HDTV.x264-exPM5</title>
      <title>The.Walking.Dead.S09E13.VOSTFR.WEB.h264-Tinker</title>
      <title>The.Walking.Dead.S09E13.VOSTFR.1080p.WEB.h264-Tinker</title>
      <title>The.Walking.Dead.S09E12.VOSTFR.WEBRip.x264-OvD</title>
      <title>The.Walking.Dead.S09E12.VOSTFR.1080p.AMZN.WEB-DL.DD5.1.x264-ARK01</title>
      <title>The.Walking.Dead.S09E12.Guardians.VOSTFR.1080p.AMZN.WEBRip.DDP5.1.x264-CasStudio</title>
      <title>The.Walking.Dead.S09E12.Guardians.VOSTFR.720p.AMZN.WEBRip.DDP5.1.x264-CasStudio</title>
      <title>The.Walking.Dead.S09E12.VOSTFR.PROPER.720p.HDTV.x264-exPM5</title>
      <title>The.Walking.Dead.S09E12.VOSTFR.WEB.h264-Tinker</title>
      <title>The.Walking.Dead.S09E12.VOSTFR.1080p.WEB.h264-Tinker</title>
      <title>The.Walking.Dead.S09E11.VOSTFR.1080p.AMZN.WEB-DL.DD5.1.x264-ARK01</title>
      <title>The.Walking.Dead.S09E11.Bounty.VOSTFR.1080p.AMZN.WEB-DL.DD+5.1.H.264-CasStudio</title>
      <title>The.Walking.Dead.S09E11.VOSTFR.WEBRip.x264-OvD</title>
      <title>The.Walking.Dead.S09E11.VOSTFR.PROPER.HTDV.XviD-exPM5</title>
      <title>The.Walking.Dead.S09E11.VOSTFR.1080p.WEB.h264-Tinker</title>
      <title>The.Walking.Dead.S09E11.VOSTFR.PROPER.720p.HDTV.x264-exPM5</title>
      <title>The.Walking.Dead.S09E11.SUBFRENCH.HDTV.x264-AMB3R</title>
      <title>The.Walking.Dead.S09E10.VOSTFR.WEBRip.x264-OvD</title>
      <title>The.Walking.Dead.S09E10.VOSTFR.1080p.WEBRip.x265-NSP</title>
      <title>The.Walking.Dead.S09E10.VOSTFR.1080p.AMZN.WEB-DL.DD5.1.x264-ARK01</title>
      <title>The.Walking.Dead.S09E10.VOSTFR.720p.WEBRip.x265-NSP</title>
      <title>The.Walking.Dead.S09E10.VOSTFR.PROPER.HTDV.XviD-exPM5</title>
      <title>The.Walking.Dead.S09E10.VOSTFR.PROPER.720p.HDTV.x264-exPM5</title>
      <title>The.Walking.Dead.S09E09.VOSTFR.1080p.WEBRip.x265-NSP</title>
      <title>The.Walking.Dead.S09E09.VOSTFR.WEBRip.x264-OvD</title>
      <title>The.Walking.Dead.S09E09.VOSTFR.PROPER.HTDV.XviD-exPM5</title>
      <title>The.Walking.Dead.S09E09.VOSTFR.PROPER.720p.HDTV.x264-exPM5</title>
      <title>The.Walking.Dead.S09E09.Adaptation.VOSTFR.1080p.AMZN.WEB-DL.DD+5.1.H.264-CasStudio</title>
      <title>The.Walking.Dead.S09E09.Adaptation.VOSTFR.720p.AMZN.WEB-DL.DD+5.1.H.264-CasStudio</title>
      <title>The.Walking.Dead.S09E09.VOSTFR.1080p.AMZN.WEB-DL.DD5.1.x264-ARK01</title>
      <title>The.Walking.Dead.S09E09.webdl. mpeg4 ac3-VOSTF-MOI</title>
      <title>The.Walking.Dead.S09E09.VOSTA.1080p.WEB-DL.AAC.x264-Sauron</title>
      <title>The.Walking.Dead.S08.Multi.1080p.BluRay.Remux.AVC.DTS-HDMA.NoTag</title>
      <title>The Walking Dead S08 1080p FRA Blu-ray AVC DTS-HD MA 5.1-HDiA</title>
      <title>Fear.The.Walking.Dead.S03.Multi.1080p.BluRay.Remux.AVC.DTS-HDMA.NoTag</title>
      <title>Fear.The.Walking.Dead.S02.Multi.1080p.BluRay.Remux.AVC.DTS-HDMA.NoTag</title>
      <title>Fear.The.Walking.Dead.S01.Multi.1080p.BluRay.Remux.AVC.DTS-HDMA.NoTag</title>
      <title>THE WALKING DEAD 2010 SAISON 8 1080P BLURAY MULTi DTS-HDMA X264-FoX</title>
      <title>The.Walking.Dead.S07.Multi.1080p.BluRay.Remux.AVC.DTS-HDMA.NoTag</title>
      <title>The.Walking.Dead.S06.Multi.1080p.BluRay.Remux.AVC.DTS-HDMA.HDF</title>
      <title>The.Walking.Dead.S05.Multi.1080p.BluRay.Remux.AVC.DTS-HDMA.NoTag</title>
      <title>The.Walking.Dead.S04.Multi.1080p.BluRay.Remux.AVC.DTS-HDMA.NoTag</title>
      <title>The.Walking.Dead.S03.Multi.1080p.BluRay.Remux.AVC.DTS-HDMA.NoTag</title>
      <title>The.Walking.Dead.S02.Multi.1080p.BluRay.Remux.AVC.DTS-HDMA.NoTag</title>
      <title>The.Walking.Dead.S01.Multi.1080p.BluRay.Remux.AVC.DTS-HDMA.NoTag</title>`

i would like to have :

`<title>The.Walking.Dead.S01.Multi.1080p.BluRay.Remux.AVC.DTS-HDMA.NoTag</title>`

With manual search in Jackett, i have the same problem.

**Comment by garfield69** [comment]
apparently this is deliberate, fa9abf2fedef7a9ff8dc961c0c5e856ae8d16dbc by @xfouloux 
https://github.com/Jackett/Jackett/blob/1cbeb74c8e762177abb58f8f5ce4a3567f52b33a/src/Jackett.Common/Definitions/yggtorrent.yml#L159-L165

**Comment by Neocide62** [comment]
Thanks, so i remove this line :

- name: re_replace 
     args: ["(.*)[sS](\\d{1,4})$", "$1"] 

And its OK, but every update, i need to do this modification.

**Comment by garfield69** [comment]
I will add a config checkbox to make the replace optional, i will be included in the next release. I'll post when its published.

**Comment by garfield69** [comment]
try out Jackett v0.11.177
you will need to edit the config and turn off the Sonarrv3hack

**Comment by Neocide62** [comment]
Thanks, it's perfect
