### ISSUE TITLE
[rarbg] An error occurred while sending the request: Error: ConnectFailure (Connection refused) (Config)

### ISSUE THREAD

**Issue by GreGNee** [Jackett/Jackett#4990]
Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
> https://rarbgmirror.xyz/ is reachable
> https://torrentapi.org/ is not reachable

Rarbg and 1337x not working

2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
> Updated to latest

3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

> See link: [http://s000.tinyupload.com/?file_id=95899998726499246798](url)

 Jackett Version 0.11.43.0 

-------------------------------

**Comment by garfield69** [comment]
rarbg requires us to use their API at https://torrentapi.org/ as the rarbg web sites actively prevents html scraping.
what response do you get from your browser when you try https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=Jackett ?
