### ISSUE TITLE
Microsoft.aspnetcore.rewrite causing load failure

### ISSUE THREAD

**Issue by doonze** [Jackett/Jackett#4999]
Debian 9, updated to latest packages. 

Jackett seems like it took an update on the 29th (two days ago). Now it fails to load with the below error:

Fatal Application startup exception System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Rewrite, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb97
93829ddae60' or one of its dependencies.

I can see this line in the update log from the 29th:

2019-03-29 22:45:52.8915 Info Copying microsoft.aspnetcore.rewrite.dll

It's the last line of the update log.

As of now, Jackett is unusable for me, any ideas?

I do see the file in /opt/jackett, and I can locate it by searching for the naming exactly as it is from the error (so no weird caps issues) by adding .dll to the assembly it's looking for.

Permissions exactly match all the other dll's in /opt/jackett.

**Comment by garfield69** [comment]
have you tried a manual upgrade to the latest jackett and see if that bypasses the issue?

**Comment by doonze** [comment]
No, not yet. Thought I'd drop a issue first. I'll try in a bit

**Comment by doonze** [comment]
So I re-downloaded the Linux release (had been using mono) and just set it up as a new install. All is working now. However I do want to pass on that the auto-update I took killed the mono version I had....

**Comment by garfield69** [comment]
I'm glad the .net version works for you.
Yes we had a few glitches while publishing the .net releases for the first time, and depending on which versions the users were on when the auto-update ran, for some it broke the updater.
