### ISSUE TITLE
[REQ]Cartoon Chaos

### ISSUE THREAD

**Issue by harroguk** [Jackett/Jackett#5]
Getting kids programs is the bane of my life.

http://www.cartoonchaos.org/

**Comment by flightlevel** [comment]
This is a private tracker, we would require an invite to attempt it.

**Comment by harroguk** [comment]
I have no invites however they are available upon request from some private trackers.

**Comment by zone117x** [comment]
A while ago we (including Sonarr dev Taloth) evaluated implementing this and the other cartoon trackers but found it to be impractical due to years of wildly inconsistent naming conventions and upload types. Ex: "Spongebob season 2 part b", " spongebob first half season one", etc.. 

If you still wanna try then join their irc channel and ask for an invite to do dev work, they were happy to invite me when I did.

**Comment by armani316** [comment]
'Invite needed' label should be added in case there's interest in adding support for this tracker.

**Comment by flightlevel** [comment]
As zone117x says in https://github.com/Jackett/Jackett/issues/5#issuecomment-153216938 
This issue is more complex than simply adding in a new tracker due to the way cartoons are named
Highly likely it requires significant work in Sonarr or some type of XEM setup
Closing this issue as there isn't a lot we can do from Jackett. If anyone from the community has ideas on how it can be implemented feel free to create a new issue

**Comment by kaso17** [comment]
I'll reopen it. We still should support it, not everyone is using Jackett just for sonarr integration.
If someone can provide an invite I'll add it fast. Otherwise I'll put it on low priority until I've time to apply in the IRC.

**Comment by zone117x** [comment]
@kaso17 ping me here when you have a working implementation. I'd be interested in seeing the heuristics involved with result parsing.

**Comment by MacGatlin** [comment]
@kaso17 Signups have been opened https://opentrackers.org/cartoonchaos/

**Comment by kaso17** [comment]
To late for me "Maximum number of users reached"

**Comment by DavGerm4** [comment]
I know this is quite old, but I can send an invite to a dev if it can help get CartoonChaos on Jackett?

**Comment by bourneon1** [comment]
@garfield69 care to take a wack at Cartoon Chaos?

**Comment by garfield69** [comment]
@bourneon1  sure. If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by bourneon1** [comment]
@garfield69 Thanks. Invite sent.

**Comment by garfield69** [comment]
registration and login successful. Thank you.

**Comment by garfield69** [comment]
Try out Jackett pre-release 0.10.741

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ returning ERR_CONNECTION_TIMED_OUT
just me, or is the site broken, gone or moved to a new domain?

**Comment by thetennismaster** [comment]
> http://www.cartoonchaos.org/ returning ERR_CONNECTION_TIMED_OUT
> just me, or is the site broken, gone or moved to a new domain?

cartoonchaos.org and totallykids.tv (related) are currently experiencing issues AFAIK. IRC is showing:
> :::CartoonChaos::: DOWN! :::TotallyKids::: DOWN!

**Comment by garfield69** [comment]
@thetennismaster  thanks for the info.

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ back online.

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online.

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ returning ERR_CONNECTION_TIMED_OUT
just me?

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ returning ERR_CONNECTION_TIMED_OUT
https://www.uptrends.com/tools/uptime reports 40 with tcp connection failed and 3 with http connect failure across sites worldwide

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
not for me I still see ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
Same, must be up and down atm

**Comment by ilike2burnthing** [comment]
back up, checked several times over the past hour

**Comment by garfield69** [comment]
offline again

**Comment by ilike2burnthing** [comment]
back up for the past hour

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ returning ERR_CONNECTION_RESET

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online.

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ The domain has expired

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/5#issuecomment-1312617232

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ is running slow as molasses. while the browser succeeds after several minutes, jackett timesout

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/5#issuecomment-1312617232

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ is running slow as molasses.

**Comment by garfield69** [comment]
http://www.cartoonchaos.org/ ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/5#issuecomment-1684815801

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
v0.21.1764
