### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of null - Empty indexer list

### ISSUE THREAD

**Issue by VSilantyev** [Jackett/Jackett#5000]
Jackett Version 0.11.156.0

Indexer list is empty in dashboard.
Caused by js error in console:

```
custom.js?changed=20190331:1232 Uncaught TypeError: Cannot read property 'trim' of null
    at proxyWarning (custom.js?changed=20190331:1232)
    at Object.success (custom.js?changed=20190331:102)
    at i (jquery.min.js?changed=2017083001:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?changed=2017083001:2)
    at A (jquery.min.js?changed=2017083001:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js?changed=2017083001:4)
```

Browser: Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)

I think error related to newly added proxyWarning function, because indexers are loaded after it:
```
        proxyWarning(data.proxy_url); <-- this line is in error call stack
        reloadIndexers();
```

**Comment by garfield69** [comment]
Try Jackett pre-release 0.11.163

**Comment by darffnad** [comment]
> Try Jackett pre-release 0.11.163

Was having the same issue, just updated to 0.11.169 with no success

**Comment by garfield69** [comment]
I cannot replicate this problem. it works for me.
https://github.com/Jackett/Jackett/blob/a61991fcdb059995e6b5f3566637cb44357d6c45/src/Jackett.Common/Content/custom.js#L1231-L1236

confused.... @flightlevel  ideas?

**Comment by seedem** [comment]
Exact same issue for me too, exactly as described right after updating, it would still provide search results to sonarr/radarr it's just the indexers that aren't showing.

**Comment by garfield69** [comment]
reversed b3d2ad94a7343224bf1197f8d768e638f0d40fb5.
jackett 0.11.170 should restore gui for those users that are experiencing problems.
Some users may need to manually force an update given the *check-for-updates* button may not be available to those affected.
