### ISSUE TITLE
Jackett: No indexers available to add, list is empty

### ISSUE THREAD

**Issue by Pedrostan** [Jackett/Jackett#5003]
Hi all.

Just recently I moved from synocommunity to Docker ( new synology DS218+)
I've installed latest Jackett from "linuxserver" ver. 0.11.156.0

Issue: When adding indexer the list is empty ( zero results for indexers ).

![Capture](https://user-images.githubusercontent.com/49131092/55295449-052e4980-5405-11e9-8a77-02450ee8a19e.PNG)

Please help. Thanks a lot.

**Comment by joaopsys** [comment]
Same happening to me right now after upgrading to v0.11.156. Running on Fedora 29, Mono 5.18.1.0

All my indexers seem to be gone from the GUI, but API calls are still working, so I guess this is just a GUI bug?

**Comment by norey** [comment]
Facing the exact same issue. I updated to 0.11.169.0 thinking it got fixed, but still nothing.

**Comment by garfield69** [comment]
cannot replicate this issue with either my win10 or ubuntu18 using jackett 0.11.169 and chrome browser.
original issue #5000, follow that ticket for news on updates.

**Comment by stephendelucia** [comment]
Same issue here.  Just installed v0.11.156 in Docker (Ubuntu) and no indexers.

**Comment by garfield69** [comment]
reversed b3d2ad9.
jackett 0.11.170 should restore gui for those users that are experiencing problems.
Some users may need to manually force an update given the check-for-updates button may not be available to those affected.
