### ISSUE TITLE
Sharewood tracker RSS feed created by Jackett does not seem to have been updated since few days

### ISSUE THREAD

**Issue by SuissoNaBisso9** [Jackett/Jackett#5006]
Hi !

The recently created Sharewood tracker (French tracker) is already on Jackett wich is really cool ! thanks for that
However this tracker is not providing any RSS feed, so I wanted to use the one we can get through Jackett, it was working well for few days but since 3/4 days maybe the RSS feeds is not refereshing and still mentions some old releases as latest ones.

Would you know what is happening ?
rest seems to be working fine, I mean I can search this tracker using Jackett with no issues

Thanks !

**Comment by garfield69** [comment]
try out Jackett v0.11.177

**Comment by SuissoNaBisso9** [comment]
yes it works ! however there is still a confusion in categories, when adding 2000 (for movies) it also grabs the TV show section.
But thanks !

**Comment by garfield69** [comment]
its a limitation resulting from how sharewood is organised. their main category is video (for both movies and tv), and this is what we use to set the primary torznab categories.
I'll see if I can tie in the sharewood's subcategories somehow.

**Comment by garfield69** [comment]
sorry, nothing can be done about this at this time.
the sub categories are not presented in the main search results page, they are hidden in the details page for each title.
