### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Got redirected to another domain. Try changing the indexer URL to http://www2.yggtorrent.gg/.: Parse error (Test)

### ISSUE THREAD

**Issue by Mikasway** [Jackett/Jackett#5011]
Hi,

It seems that the Tracker YGG is always changing his way to connecet or just there URL. Ok it's a fact we know what to do.

But now it seems that the "www2" HTTP redirect to HTTPS and HTTPS redirect to HTTP.. what we do in this case ?

Thanks for help :)

Best regards
-------------------------------

**Comment by garfield69** [comment]
1. you did no specify what version of Jackett you are on, so I will assume you are at the very least on a 0.11.*. If not, upgrade to the latest now.
then
2. on your jackett dashboard, use the **wrench** icon to edit the yggtorrent config and set the **Site Link** to `https://www.yggtorrent.gg/` and the **Search and download URL** to `www2.yggtorrent.gg`
and click **OKAY**. 
If you get an error, click **CLOSE** then edit and click **OKAY** once more. 
you should be good to go.

**Comment by Mikasway** [comment]
Hi,

Thanks its perfectly fonctionnal now  :)
