### ISSUE TITLE
[torrentccf] Exception (torrentccf): Got redirected to another domain. 

### ISSUE THREAD

**Issue by ylxb2016** [Jackett/Jackett#5012]
**Jackett version**:  0.11.177.0

> [torrentccf] Exception (torrentccf): Got redirected to another domain. Try changing the indexer URL to https://et8.org/.: Parse error (Test)

invite has been sent to kaso1717
Thank you!

-------------------------------

**Comment by kaso17** [comment]
thank you, it's working fine for me (I'm not getting redirected to https). Is this still a problem for you, might have been a temporary issue.
