### ISSUE TITLE
[Bug] ArenaBG

### ISSUE THREAD

**Issue by roshavagarga** [Jackett/Jackett#5013]
Software/OS:
DuckieTV New Tab Mode Nightly (2nd April 2019)
Jackett 0.11.177.0
qBittorrent 4.1.5
Windows 7 Ultimate, Service Pack 1

Setup:
Followed instructions to the letter, as posted both my Jackett and DuckieTV, qBittorrent is connected to DuckieTV via WebUI, no problems when downloading from other Jackett Search Engines - Zamunda, YGGTorrents and Torrent9.

When attempting a download from ArenaBG (logged with the correct username and password, can download from website, tried both with magnet and torrent links, neither works) I will get the DuckieTV popup that a Torrent has started downloading, but nothing pops up in qBittorrent. More info in logfiles.
[log.txt](https://github.com/Jackett/Jackett/files/3033298/log.txt)

Bonus unrelated question: Is it normal not to have magnet links for Zamunda, YGG, Torrent9 and ArenaBG in DuckieTV? @garfield69 
I can supply a username and password private, if required.

**Comment by garfield69** [comment]
To use Jackett's ArenaBG indexer with DuckieTV, you need to config the indexer to use the .torrent link.
read https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV#arenabg for details.

Regarding the magnet question, read https://github.com/SchizoDuckie/DuckieTV/wiki/Using-Jackett-with-DuckieTV#duckietv-jackett-problems-and-solutions for a general explanation.
If the websites in question provide magnets on their primary results page then they should be available on the Dtv search results as well. But if the sites require you to visit secondary torrent-details page, then generally magnets will not be available.

**Comment by roshavagarga** [comment]
@garfield69 Issue is still present. I was using the .torrent option, as described in the documentation which you linked, when I made said logs. No torrents were successfully initiated in qBittorrent despite this. No idea why that's happening, I even specifically checked whether my username/password combo was correct and reentered them before clicking on Okay. I repeated the process just now, nothing's changed, torrent still doesn't appear in qBit.

**Comment by garfield69** [comment]
i'll take a close look then.

**Comment by garfield69** [comment]
apologies. it appears arenabg have changed their download link for .torrents. I'll see if I can make an adjustment to the indexer to compensate.

**Comment by roshavagarga** [comment]
No worries, thanks for the awesome work both on Jackett and DuckieTV :)

**Comment by garfield69** [comment]
try out 0.11.180
you may need to edit the Jackett ArenaBG config to renew the download link selector, or perhaps even trash-bin the config and add it afresh. I would be interested in which method you ended up using. thanks.

**Comment by roshavagarga** [comment]
I'll try both in that order and tell you which way works in the morning, expect an answer in 10 or so hours :)

**Comment by roshavagarga** [comment]
@garfield69 0.11.180.0 is confirmed to be a-okay and working at full steam.
Went into the ArenaBG settings, inputted the username and password again, opened the dropdown menu, clicked on .torrent (already selected beforehand), clicked on okay, torrents from the website now function properly. You can mark this one as closed, thanks for the help :)
