### ISSUE TITLE
[REQ] The New Generation (Dutch)

### ISSUE THREAD

**Issue by savahu** [Jackett/Jackett#5014]
This is a Dutch usenet forum.

URL: https://www.the-newgeneration.net/

Temporarily open for registrations: https://www.the-newgeneration.net/register/

The indexer might be similar to film-paleis.me, since it's also a kind of forum.

**Comment by garfield69** [comment]
I've completed my registration and had my email validated. login is currently pending a final email however, something about my a/c needing to be approved.

**Comment by savahu** [comment]
Have you got a mail yet or should I ask their support?

**Comment by garfield69** [comment]
I have not received any followup mail as yet.
If I try to login I get an error that my username or email address does not belong to any account.
Please ask for support.
The user name I used during registration was garfield1969

**Comment by savahu** [comment]
I think this is not possible, because Jackett only supports torrents, not NZB-files.
