### ISSUE TITLE
[girotorrent] Login failed: Selector

### ISSUE THREAD

**Issue by hidaba** [Jackett/Jackett#5018]
Error when try to add:
An error occured while updating this indexer
Login failed: Selector "a[href="logout.php"]" didn't match

Jackett Version 0.11.180.0

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.
