### ISSUE TITLE
[GkTorrent][cpasbien][Torrent9] Bad file name for Radarr/Sonarr

### ISSUE THREAD

**Issue by ThomasClemenceau** [Jackett/Jackett#5027]
Hi,

I have an "issue" with these three trackers. I'm french, and I want TRUEFRENCH movies (FRENCH is canadian in most of the case). But all movies which are TRUEFRENCH have TRUE(YEAR) FRENCH as name, and are not recognized by Radarr/Sonarr.

Example :
If I want Mission Impossible : Fallout. The tracker send me "Mission Impossible : Fallout TRUE2018 FRENCH (QUALITY)". Radarr will find "Mission Impossible : Fallout TRUE" as the movie title, so he will not grab it.
![image](https://user-images.githubusercontent.com/29857316/55617645-e3cab600-5794-11e9-9ab2-4eeaf94bab42.png)

Example for Jurassic World 2 : 
![image](https://user-images.githubusercontent.com/29857316/55617677-f47b2c00-5794-11e9-9d1d-3187166741cc.png)

Is it possible to automatically rename these files to "(MOVIE TITLE) TRUEFRENCH 2018" or anything that is recognizable by Radarr/Sonarr including TRUEFRENCH (for restrictions)

NOTE : 
The torrent itself has a good name 
![image](https://user-images.githubusercontent.com/29857316/55617883-710e0a80-5795-11e9-82f8-1ff6d48d9717.png)

Thank you !

**Comment by garfield69** [comment]
yes, I see how that can come about...
https://github.com/Jackett/Jackett/blob/e8dbaa4a8e23c9e23415457659771b809c32d176/src/Jackett.Common/Definitions/gktorrent.yml#L65-L70
the first replace destroys the truefrench tag and you are the first to spot this since the code was added over 2 years ago!
Should be fixed with  Jackett 0.11.185

**Comment by ThomasClemenceau** [comment]
Oh I see.
Tried this changes on my Jackett and that fix it. It's solved ! Thank you a lot !
