### ISSUE TITLE
Blank Page on UI

### ISSUE THREAD

**Issue by jamesbbryant** [Jackett/Jackett#5033]
I uninstalled Jackett a while back and decided to use it again and performed a fresh install. Windows 10 Pro 1809 . The install goes through but when I try to open the Web UI, I just get a blank page, nothing loads. Firefox gives me a blank page, Chrome gives me a 404 message. I figured maybe this was due to some lingering files from the previous install. I did another uninstall, deleted all directories that Jackett was in and even went into the registry and deleted every reg key that had Jackett in the name. Did another reinstall and same experience. I'm guessing there is a lingering file somewhere that maybe is conflicting with the new install? I know most of the info I saw on posting logs, etc was for Linux so wasn't sure what info or how to get logs you were needing or thoughts you could have me try. Thanks for your help.

**Comment by garfield69** [comment]
take a look in `%ProgramData%\Jackett` and see if there is a log.* and drag/drop them here for us to take a look at.

**Comment by jamesbbryant** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/3050176/log.txt)

Here you go. Thanks for the help

**Comment by garfield69** [comment]
you are using a very old version of Jackett 0.7.58
suggest you uninstall it and download and install this latest version https://github.com/Jackett/Jackett/releases/download/v0.11.185/Jackett.Installer.Windows.exe

**Comment by jamesbbryant** [comment]
Well I feel stupid. That did the trick. I never even paid attention to what version it was. I just assumed it was the latest cause I did a quick google search for Jackett installer and  navigated to the site and downloaded it. Never crossed my mind that older versions were listed. Thanks for your help.

**Comment by garfield69** [comment]
no problem.
