### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on http://www2.yggtorrent.gg/ using form selector 

### ISSUE THREAD

**Issue by avrelaun** [Jackett/Jackett#5037]
Hi, I just got this error on ygg.

The url does not seem to have changed, at least I can browse the website

**Comment by avrelaun** [comment]
It worked all day, I did several successful queries a few minutes before having the error (on all my queries since). This is a new problem.

**Comment by garfield69** [comment]
on your Jackett dashboard, use the **wrench** icon to edit the *yggtorrent* config,
and carefully check that the **Site Link** is `https://www.yggtorrent.gg/` and that the **Search and download** URL is `www2.yggtorrent.gg` and click **OKAY**.
If you get an error, click **CLOSE** then edit and click **OKAY** once more.
if you are still seeing this *invalid URI* error after this, then provide a screenshot of your yggtorrent config, and a **complete** enhanced log (not just the stack trace) so we can dig deeper.

**Comment by avrelaun** [comment]
Here's a useless screenshot:
![Screenshot_2019-04-10 Jackett](https://user-images.githubusercontent.com/412102/55911173-5b0ea880-5be0-11e9-8cff-db000e4f8b8e.png)

And here's the actual error with the redirect:
```
Error on 20190410222750 for YGGtorrent.txtJackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to http://www2.yggtorrent.gg/. Updated site link, please try again.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebClientStringResult Result, IHtmlDocument document) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 747
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1243

<html>
<head><title>307 Temporary Redirect</title></head>
<body bgcolor="white">
<center><h1>307 Temporary Redirect</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by garfield69** [comment]
strange. works for me.
ok. using a browser on the same system as Jackett, please click on https://www.yggtorrent.gg/
and report back what the address is on the browser for that page.
for me its https://www.yggtorrent.gg/
![image](https://user-images.githubusercontent.com/6933240/55912438-c3887480-5c36-11e9-836e-0878d4cffee8.png)

then click on the **torrents** menu and select **rerchercher un torrent** and report what address you get for this page.
for me its https://www2.yggtorrent.gg/engine/search?do=search
![image](https://user-images.githubusercontent.com/6933240/55912563-0cd8c400-5c37-11e9-8919-e861024130d4.png)

what doe you get?
Also, confirm which version of Jackett you are using (bottom of your jackett dashboard) and on what platform. thanks.

**Comment by avrelaun** [comment]
This is a headless system so no browser. Maybe links/lynx.

I'm using https://hub.docker.com/r/linuxserver/jackett/, jackett version 0.11.185.0, on an archlinux server.

I must say that it worked perfectly for a few hours before showing this error message.

Here's the url: https://www2.yggtorrent.gg/engine/search?do=search&attempt=1

Maybe this is a user-agent check gone wrong ?

**Comment by garfield69** [comment]
no idea. i'm going to bump this to other devs that have more experience. @kaso17  or @flightlevel  please take a look at this ticket. thanks.

**Comment by avrelaun** [comment]
wiping the jackett database makes yggtorrent work again.
