### ISSUE TITLE
Config YGGtorent for Jackett issue

### ISSUE THREAD

**Issue by vergil54** [Jackett/Jackett#5038]
Hi,

I have an issue with Jackett configuration for YGGTorrent, can you help me.
Site Link
https://www.yggtorrent.gg/
Search and download URL
https://ww3.yggtorrent.gg/

It's worked fine earlier.

**Comment by garfield69** [comment]
on your Jackett dashboard, use the **wrench** icon to edit the *yggtorrent* config,
and carefully check that the **Site Link** is `https://www.yggtorrent.gg/` and that the **Search and download** URL is `www2.yggtorrent.gg` and click **OKAY**.
If you get an error, click **CLOSE** then edit and click **OKAY** once more.
if you are still seeing this an error after this, then provide a screenshot of your yggtorrent config, and a **complete** enhanced log (not just the stack trace) so we can dig deeper.

**Comment by vergil54** [comment]
Thanks ! Now it's works, can you say me how for the future I can know which variables put on **Search and download URL** ? If YYG change by example.

**Comment by garfield69** [comment]
If in future this stops working, you would need to visit the web site directly with your browser, click the **torrents** menu and select the **rechercher un torrent** option.
The variable for the *search and download url* box is whatever address ends up in the browser address box.
![image](https://user-images.githubusercontent.com/6933240/55690655-7911b880-59e8-11e9-8158-9b498951db26.png)

**Comment by vergil54** [comment]
yeahh Thanks a lot for this information.
Merci infiniment
