### ISSUE TITLE
RARBG: Direct links to the RARBG page

### ISSUE THREAD

**Issue by 07416** [Jackett/Jackett#5039]
torrentapi.org throws "403 Forbidden" error when the link is accessed — can the RARBG page links be used instead? I don't think there's a way to access RARBG  aside from copying the release title from Jackett and performing a search on the website.

**Comment by garfield69** [comment]
which link are you referring to?
if its the details page link of each search result entry, then the 403 for this was fixed beginning with Jackett v0.11.102 so upgrade to the latest v0.11.193
if its something else then explain further.

**Comment by 07416** [comment]
Sorry, I've overly relied on the auto-updater. I'm running 0.10.890 (Windows 10):

```
New release found.  Current: v0.10.890 New: v0.11.195
 Error performing update.
```

I'll close the issue for now.

**Comment by 07416** [comment]
torrentapi.org redirects to RARBG now.

 Jackett Version 0.11.195.0

**Comment by kaso17** [comment]
It's working fine for me, are you still having problems?

**Comment by 07416** [comment]
> 
> 
> It's working fine for me, are you still having problems?

No, but I'd prefer direct links to RARBG instead of the torrentapi.org redirection. Insignificant.

**Comment by kaso17** [comment]
The API doesn't provide the necessary details for direct links.
