### ISSUE TITLE
Rutracker magnet links

### ISSUE THREAD

**Issue by 07416** [Jackett/Jackett#5041]
Is it possible to add magnet links for the Rutracker indexer? Neither torrent or magnet links are added to the search results as far as I can see and are only available on the torrent pages.

**Comment by garfield69** [comment]
the primary search results page for the rutracker website provides just the .torrent link, it's the link you can see if you hover over the torrent size column in the websites search results page.
To add a magnet to the Jackett rutracker c# indexer, a c# contributor would need to provide a config option switch, and then change the download link to fetch the details pages' magnet link instead.
Are there any c# contributors who would like to volunteer?
