### ISSUE TITLE
Category puntorrent is not correct

### ISSUE THREAD

**Issue by simon25608** [Jackett/Jackett#5042]
Hello!

In the private tracker of puntotorrent the category of the torrent is not correct, the series appear as movies:

![img-2](https://user-images.githubusercontent.com/18722357/55690626-463dd500-5994-11e9-86ff-56cdbf8f2c01.png)
![img-1](https://user-images.githubusercontent.com/18722357/55690627-46d66b80-5994-11e9-8c7b-34e1dcb1c02d.png)

Jackett Version 0.11.185.0

**Comment by garfield69** [comment]
Try Jackett v0.11.195

**Comment by simon25608** [comment]
Perfect. Thanks
