### ISSUE TITLE
[REQ] crazyhd.com

### ISSUE THREAD

**Issue by BurhanDanger** [Jackett/Jackett#5043]
Hi, It'd be helpful to have it added. Thanks.

**Comment by garfield69** [comment]
registration and login successful. thank you.

**Comment by garfield69** [comment]
Try out Jackett v0.11.200

**Comment by BurhanDanger** [comment]
Search result is bit different

https://i.ibb.co/x3SHz4H/2019-04-09-10-25.png
https://i.ibb.co/VDk1S2R/2019-04-09-10-26.png

**Comment by garfield69** [comment]
Darn. It looks like the site is not compatible with the Cardigann indexer I created.
While the default torrent search using https://www.crazyhd.com/index.php?page=searchpage&search=&category=0&options=0&active=0&order=%2F&by=2&gold=0 generates HTML results than can be scraped, when it comes  to doing a search=keywords with https://www.crazyhd.com/index.php?page=searchpage&search=wrestlemania&category=0&options=0&active=0&order=%2F&by=2&gold=0 the site is ignoring the search keyword.

Using the website, the search box kicks off an interactive ajax or javaScript to fetch json and present the results. Cannot do the same with the Cardigann Indexer.

This indexer will need to be rewritten as a native c# indexer so it can process the json :-(

Shall I leave the current indexer in place while we wait for a c# developer to volunteer, or do you want me to remove it?

**Comment by BurhanDanger** [comment]
Well, dang. Thanks for your trouble. Since the search is not useful I think it'd be best to have it removed.

**Comment by Sytanek** [comment]
@garfield69 I have created pull request to make this work with just yml - https://github.com/Jackett/Jackett/pull/5816

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.580

**Comment by garfield69** [comment]
https://www.chd4.com/ returning Error 522 Connection timed out

**Comment by garfield69** [comment]
online

**Comment by parthp1808** [comment]
It's not working

**Comment by garfield69** [comment]
@parthp1808 wrote:
>It's not working

It is for me
![image](https://user-images.githubusercontent.com/6933240/163056375-7144fbe4-0e68-4af7-a32b-eca5bc918530.png)
open a new ticket with more info if you want help figuring out what's going on at your end.

**Comment by garfield69** [comment]
https://www.chd4.com/ cloudflare Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.chd4.com/ cloudflare A timeout occurred Error code 524

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.chd4.com/  No such file or directory

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/5043#issuecomment-1721682370

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
the following mailbox sql error is preventing access to all the other site pages
```
MySQL query error! 
Error: Table './ttrack4/dbschd_tracker_messages' is marked as crashed and last (automatic?) repair failed
Query: SELECT COUNT(*) as ur FROM dbschd_tracker_messages WHERE readed='no' AND receiver=123456
```

**Comment by garfield69** [comment]
v0.21.1106
