### ISSUE TITLE
[torrentday] Unable to download torrent file.

### ISSUE THREAD

**Issue by doogienz** [Jackett/Jackett#5050]
Not sure exactly when it started, but have checked on two different Jackett installs and same result.

Torrentday works fine via test, and you can search but it cannot download the torrents.  Debug attached.  Can login fine and search and download from the site.
[td.txt](https://github.com/Jackett/Jackett/files/3060874/td.txt)

Returns 404 - not found.

http://localhost:9117/dl/torrentday/?jackett_apikey={blargapi}&path=Q2ZESjhDRkFvRWZrbnBWR3BlZ1ZscUE0TFFUeVZ2cWZvNllmN2UtUmhhNW9rLUdXMzUtQUVRWDI4TFVrdDktQTRSeUZKQVloTVdLbFptX250MG1WanVmbTBGQUd4Q2ZrX3lCOUZTV1ZRb3c4bDZGY0dsRUx4QWFicFNWWVRWWDVBLV9pLUpxODF4dVJmS1hHd09IUjlRSjREd21kWWIzTjJ3YjlGd1F1QWhIczdJNUpxNXdxd1l2WVY2NXpTeGZERjkxM1hB&file=Kingsman+The+Golden+Circle+2017+DVDR-JFKDVD

Occured on 11.199 and 11.200 but suspect it's been like this for a while.

**Comment by kaso17** [comment]
you're getting redirected to  https://www.torrentday.com/forums.php?t=3082987
I guess your account is locked.

**Comment by doogienz** [comment]
Thanks for this - apologies for not checking that.
