### ISSUE TITLE
[torrent9] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Jamyz** [Jackett/Jackett#5053]
**Jackett version**:  Jackett Version 0.11.205.0 Docker
**Mono version**: Jackett Version 0.11.205.0 Docker

**Comment by garfield69** [comment]
works for me.
make sure that your SitelLink on your torrent9 config is `https://www.torrent9.cat//` and **not** \*ww1.\*

**Comment by Jamyz** [comment]
Hi @garfield69 ....
I use Docker with  Version 0.11.205.0.
I delete the all json and json.bak in the folder indexers.
Now torrent9 works on test. But torrent9clone not.
Thanks.

**Comment by garfield69** [comment]
if torrent9clone is returning what you raised in #5052 then that is a different problem than this one.
read https://github.com/Jackett/Jackett/issues/4982#issuecomment-477750444 for details.
