### ISSUE TITLE
[gktorrent] Exception (gktorrent): Specified argument was out of the range of valid values.Parameter name: Unknown operator: : Specified argument was out of the range of valid values.Parameter name: Unknown operator:  (Test)

### ISSUE THREAD

**Issue by Jamyz** [Jackett/Jackett#5054]
**Jackett version**:  Jackett Version 0.11.205.0 Docker
**Mono version**: Jackett Version 0.11.205.0 Docker

**Comment by garfield69** [comment]
duplicate of #4982

**Comment by freMea** [comment]
I guess it’s their ddos protection.

**Comment by Jamyz** [comment]
I don’t try but check release 0.11.245

**Comment by garfield69** [comment]
yes, its the cloudflare ddos protection. the issue will remain outstanding until either:
- the site drops their ddos protection, or
- the cloudflareutilities.dll that jackett uses to attempt to resolve the challenge is updated for the recent cloudflare ddos challenge. 

#4982 is the origin ticket which I've already posted earlier, and where you need to watch if you want updates on progress.

**Comment by garfield69** [comment]
solved with Jackett 0.11.635
