### ISSUE TITLE
[REQ] Extremetorrents.org

### ISSUE THREAD

**Issue by savahu** [Jackett/Jackett#5057]
private Dutch tracker.

URL: http://www.extremetorrents.org

It's very similar to Film-paleis, which is already supported.
Currently open registration.

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/55991319-14af6b80-5cfe-11e9-817e-70f1e2d63d78.png)

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by garfield69** [comment]
jackett 0.12.1361

**Comment by garfield69** [comment]
https://www.extremetorrents.org/ redirecting to https://torrenttop100.com/

**Comment by ilike2burnthing** [comment]
back up for you now?

**Comment by garfield69** [comment]
Yes, the indexer passes the test now without the redirect. Oddly the browser still redirects %-/ but that will probably clear later.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/5057#issuecomment-1749433769

**Comment by ilike2burnthing** [comment]
Working in Jackett and private window. Tried deleting cookies and disabling extensions, but couldn't get it to work in a normal window.

**Comment by garfield69** [comment]
https://www.extremetorrents.org/ 
`You will be redirected to the torrent top 100, there is a serious DDoS attack! Unfortunately, we have lost our hosting as a result`

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.extremetorrents.org/ cloudflare Connection timed out Error code 522

**Comment by garfield69** [comment]
v0.21.1250
