### ISSUE TITLE
Jackett reverse proxy not working anymore

### ISSUE THREAD

**Issue by mariothiel** [Jackett/Jackett#5058]
2019-04-11 12:25:46.5213 Info New release found.  Current: v0.11.205 New: v0.11.210
mono version: 5.18.1.0

Something changed, as my reverse proxy with apache is not working anymore since this latest update. Any idea?

**Comment by garfield69** [comment]
there were no changes to anything other than indexers in the releases from .205 to .210
so most likely has nothing to do with jackett

**Comment by mariothiel** [comment]
Maybe something changed earlier, I haven't checked for a couple of weeks. Nothing else changed on my end, reverse proxies for other apps are still working.

**Comment by kaso17** [comment]
Please check the reverse proxy configuration examples from the readme.
