### ISSUE TITLE
[casstudio.tv] new domain

### ISSUE THREAD

**Issue by GutsyHeart** [Jackett/Jackett#5060]
> Дорогие пользователи. Наш домен заблокировали добрые голландские п... Мотивировали тем, что у нас документы фейковые - скан русского паспорта.
В общем видимо русские буквы прочитать не смогли...
Пока перехали на зеркало
casstudio.tk

> 
New domain casstudio.tk

**Comment by garfield69** [comment]
thanks for the update.

**Comment by garfield69** [comment]
https://casstudio.tk/ returning ERR_CONNECTION_TIMED_OUT
broken, gone or new domain?
