### ISSUE TITLE
Elite-tracker: fix title with MULTI language

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#5064]
Elite-tracker is a french tracker so torrents with this tag are mostly ENG+FRE audio and VOSTFR.

We should then have the option to replace MULTI the same way we can do it for YGG

**Comment by garfield69** [comment]
this is not a cardigann indexer like yggtorrent, so it will require a dev with c# to add the requested config support and code changes.
I don't have a login for this site so someone else will need to volunteer.

**Comment by skuizy** [comment]
Imma soon (about a week or so) be abble to send an invite to someone willing to do it.

Let me know your mail address ;)

**Comment by skuizy** [comment]
Invites are open for the holidays ! I've sent you one.

**Comment by garfield69** [comment]
Registration and login successful. Thank you.

**Comment by garfield69** [comment]
Jackett 0.12.1345

**Comment by skuizy** [comment]
Thanks !

**Comment by neoliquid37** [comment]
Thanks @garfield69 

I allowed myself to create an issue, following the resolution of it for Elite-Tracker:
https://github.com/Jackett/Jackett/issues/6855
