### ISSUE TITLE
[REQ] XWtorrents seedbox download 

### ISSUE THREAD

**Issue by xpronic** [Jackett/Jackett#5071]
This tracker has two download options, one for regular (same ip) and another for seedbox users. At the moment it's only grabbing the regular downloads, and is failing once added to the seedbox. Is there anyway to add a seedbox only option to the tracker config on jackett?

**Comment by garfield69** [comment]
Try out Jackett pre-release v0.11.223
edit your xwtorrents config and tick the seedbox checkbox and you should be good to go.
