### ISSUE TITLE
[nordicbits] Exception (nordicbits): Object reference not set to an instance of an object.: Parse error (Config)

### ISSUE THREAD

**Issue by Aagv** [Jackett/Jackett#5072]
Version: 0.11.221.0  
[log.txt](https://github.com/Jackett/Jackett/files/3077201/log.txt)
-------------------------------

**Comment by garfield69** [comment]
working for me.
has this worked for you before, did you make any recent changes to your web profile?
which theme are you using, and which language?
also on the jackett config, have you choosen any  settings that were not the default?
have you filled in the *injecting headers* section?

**Comment by garfield69** [comment]
ping @hallengreenn
