### ISSUE TITLE
shellife tracker definition error

### ISSUE THREAD

**Issue by rrrevin** [Jackett/Jackett#5074]
Jackett version : 0.11.221.0
Mono version : Mono JIT compiler version 5.18.1.0 (tarball Fri Mar 15 21:12:55 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  arm64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
-------------------------------
The following error is displayed in the logs when parsing shellife.yml. I have not edited the file, it is as it came from source repo.

Apr 14 07:32:40 npi jackett[8904]: 04-14 07:32:40 Info Loading Cardigann definition /opt/Jackett/Definitions/shellife.yml
Apr 14 07:32:40 npi jackett[8904]: 04-14 07:32:40 Error Error while parsing Cardigann definition /opt/Jackett/Definitions/shellife.yml: (Line: 2, Col: 7, Id
x: 11) - (Line: 2, Col: 7, Idx: 11): Mapping values are not allowed in this context. YamlDotNet.Core.SyntaxErrorException: (Line: 2, Col: 7, Idx: 11) - (Lin
e: 2, Col: 7, Idx: 11): Mapping values are not allowed in this context.
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Core.Scanner.FetchValue () [0x0008c] in <bfbb3b9be9994b5ab56cc48bd8fb6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Core.Scanner.FetchNextToken () [0x00217] in <bfbb3b9be9994b5ab56cc48bd8fb6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Core.Scanner.FetchMoreTokens () [0x00065] in <bfbb3b9be9994b5ab56cc48bd8fb6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Core.Scanner.MoveNextWithoutConsuming () [0x00010] in <bfbb3b9be9994b5ab56cc48bd8fb6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Core.Parser.GetCurrentToken () [0x0005d] in <bfbb3b9be9994b5ab56cc48bd8fb6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Core.Parser.ParseDocumentEnd () [0x00002] in <bfbb3b9be9994b5ab56cc48bd8fb6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Core.Parser.StateMachine () [0x00090] in <bfbb3b9be9994b5ab56cc48bd8fb6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Core.Parser.MoveNext () [0x0001f] in <bfbb3b9be9994b5ab56cc48bd8fb6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Core.ParserExtensions.Allow[T] (YamlDotNet.Core.IParser parser) [0x00018] in <bfbb3b9be9994b5ab56cc48bd8f
b6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deseria
lize (YamlDotNet.Core.IParser parser, System.Type expectedType, System.Func`3[T1,T2,TResult] nestedObjectDeserializer, System.Object& value) [0x00000] in <b
fbb3b9be9994b5ab56cc48bd8fb6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue (YamlDotNet.Core.IParser parser, 
System.Type expectedType, YamlDotNet.Serialization.Utilities.SerializerState state, YamlDotNet.Serialization.IValueDeserializer nestedObjectDeserializer) [0
x00088] in <bfbb3b9be9994b5ab56cc48bd8fb6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue (YamlDotNet.Core.IParser parser,
 System.Type expectedType, YamlDotNet.Serialization.Utilities.SerializerState state, YamlDotNet.Serialization.IValueDeserializer nestedObjectDeserializer) [
0x0006e] in <bfbb3b9be9994b5ab56cc48bd8fb6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Serialization.Deserializer.Deserialize (YamlDotNet.Core.IParser parser, System.Type type) [0x0004e] in <b
fbb3b9be9994b5ab56cc48bd8fb6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Serialization.Deserializer.Deserialize (System.IO.TextReader input, System.Type type) [0x00007] in <bfbb3
b9be9994b5ab56cc48bd8fb6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at YamlDotNet.Serialization.Deserializer.Deserialize[T] (System.String input) [0x00007] in <bfbb3b9be9994b5ab56cc48bd8f
b6b39>:0
Apr 14 07:32:40 npi jackett[8904]:   at Jackett.Common.Services.IndexerManagerService+<>c__DisplayClass13_0.<InitCardigannIndexers>b__3 (System.IO.FileInfo 
file) [0x0002c] in <752c4c15cb3b4e19a0743ed4fa49472e>:0

Don't know how to fix, so posting here for your enjoyment :)

**Comment by donileo** [comment]
Why was this issue closed? I am also getting this same error..

**Comment by garfield69** [comment]
its closed because the fix https://github.com/Jackett/Jackett/commit/3a7608317f0d9b453a749652c862d0db5eb1badf was committed.
However the next release of Jackett which includes the fixs has not been published yet. Patience.

**Comment by garfield69** [comment]
try out Jackett v0.11.224

**Comment by donileo** [comment]
@garfield69 Thanks :D ! So quick...
