### ISSUE TITLE
[worldwidetorrents] Exception (worldwidetorrents): L'argument spécifié n'était pas dans les limites de la plage des valeurs valides.Nom du paramètre : Unknown operator: : L'argument spécifié n'était pas dans les limites de la plage des valeurs valides.Nom du paramètre : Unknown operator:  (Test)

### ISSUE THREAD

**Issue by freMea** [Jackett/Jackett#5077]
1. I can access the site [https://worldwidetorrents.to](https://worldwidetorrents.to) directly
2. Jackett v.0.11.254
3. **full enhanced log** [here](https://paste.ubuntu.com/p/p4GYrGKPBV/).

**Comment by garfield69** [comment]
duplicate of #4982

**Comment by garfield69** [comment]
cloudflare solved with Jackett 0.11.635
however WWT is down
