### ISSUE TITLE
[casatorrents] wrong results from Radarr

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#5078]
Jacket version 
Windows 10 x64
When I manually search in Jackett with casatorrents, I have the good results.
Same thing with this URL : http://[my IP]:9117/api/v2.0/indexers/casatorrent/results/torznab/?apikey=[apikey]&q=[movie title]
But when I search from Radarr, I always have 50 results (50 last torrents uploaded on tracker). Is it the same for you ? Or did I make a mistake configuring Jackett CASA Torrent on Radar.
Other jackett tracker work well in radarr.

Great thanks !

**Comment by garfield69** [comment]
casatorrent's search engine returns ANY keywords by default.
added the plus prefix to get site to return results with ALL keywords.

**Comment by garfield69** [comment]
Jackett 0.12.1572
