### ISSUE TITLE
Exception (worldwidetorrents): Specified argument was out of the range of valid values. Parameter name: Unknown operator: : Specified argument was out of the range of valid values. Parameter name: Unknown operator:

### ISSUE THREAD

**Issue by EdisonMaxwell** [Jackett/Jackett#5080]
It seems like this issue happens with random trackers at random times. Trackers I didn't have an issue with have and issue now and some that did have this issue are working now. 

I'm able to access this website itself.
I'm running Jackett variant: FullFrameworkWindows
Jackett version: 0.11.224.0 (current as of this posting)

[Log](https://github.com/Jackett/Jackett/files/3081738/JackettWWWissue.txt)

**Comment by garfield69** [comment]
duplicate of #4982

**Comment by adambirds** [comment]
Same issue with worldwidetorrents for me too.

**Comment by garfield69** [comment]
cloudflare solved with Jackett 0.11.635
however WWT is down.
