### ISSUE TITLE
[ilcorsaronero] Exception (ilcorsaronero): certificate validation failed: [Subject]  CN=synology.com, O=Synology Inc., L=Taipei, C=TW[Issuer]  CN=Synology Inc. CA, O=Synology Inc., L=Taipei, C=TW[Serial Number]  00ACCD0948D4A64A34[Not Before]  4/15/19 9:13:16 PM[Not After]  12/31/38 8:13:16 PM[Thumbprint]  DA8DB5CC5D77B89AFAC58A8A1F1EF6E7B850BFC5: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by lmennoia** [Jackett/Jackett#5083]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by garfield69** [comment]
that does not look like the correct certificate for ilcorsaronero so make sure to edit your jackett indexer config and check that your sitelink is set to `https://ilcorsaronero.pizza/`
if it is, and you are still getting this error then you are probably being redirected by your ISP to a dead end. test it with your browser to see where the sitelink takes you.
