### ISSUE TITLE
[lostfilm] Exception (lostfilm): Specified argument was out of the range of valid values.Parameter name: Unknown operator: : Specified argument was out of the range of valid values.Parameter name: Unknown operator:  (Test)

### ISSUE THREAD

**Issue by vSh1ny** [Jackett/Jackett#5086]
Lostfilm has recently switched to Cloudflare, which broke things. Aside from the fact that there's a "browser check" that comes with it, though, it still doesn't redirect http requests to https:// URIs.

**Comment by garfield69** [comment]
duplicate of #4982

**Comment by vSh1ny** [comment]
Right, sorry for not noticing that before. Thank you.
I'm closing this one in favor of #4982.
