### ISSUE TITLE
TorrentBytes Error: Exception in Configure

### ISSUE THREAD

**Issue by seanvree** [Jackett/Jackett#509]
Sep 13, 2016 05:07:52 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
Sep 13, 2016 05:07:52 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Sep 13, 2016 05:07:52 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Sep 13, 2016 05:07:52 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Sep 13, 2016 05:07:52 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Sep 13, 2016 05:07:52 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Sep 13, 2016 05:07:52 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Sep 13, 2016 05:07:52 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Sep 13, 2016 05:07:52 PM	Info	
ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Sep 13, 2016 05:07:52 PM	Info	
ApiControllerActionSelector SelectAction 
Sep 13, 2016 05:07:52 PM	Info	
AdminController ExecuteAsync 
Sep 13, 2016 05:07:52 PM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Sep 13, 2016 05:07:52 PM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Sep 13, 2016 05:07:52 PM	Info	
DefaultHttpControllerActivator Create 
Sep 13, 2016 05:07:52 PM	Info	
HttpControllerDescriptor CreateController 
Sep 13, 2016 05:07:52 PM	Info	
DefaultHttpControllerSelector SelectController Admin
Sep 13, 2016 05:07:52 PM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Sep 13, 2016 05:07:52 PM	Info	
  http://seanvree.com:9117/Admin/GetLogs?_=1473811643208
Sep 13, 2016 05:07:47 PM	Info	
AdminController Dispose 
Sep 13, 2016 05:07:47 PM	Info	
AdminController Dispose 
Sep 13, 2016 05:07:47 PM	Info	
  Content-type='application/json; charset=utf-8', content-length=103
Sep 13, 2016 05:07:47 PM	Info	
AdminController ExecuteAsync 
Sep 13, 2016 05:07:47 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync 
Sep 13, 2016 05:07:47 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()'
Sep 13, 2016 05:07:47 PM	Info	
ApiControllerActionInvoker InvokeActionAsync 
Sep 13, 2016 05:07:47 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
Sep 13, 2016 05:07:47 PM	Error	
Exception in Configure

**Comment by kaso17** [comment]
If you've an invite available I can have a look and probably fix it.

**Comment by seanvree** [comment]
@kaso17 they don't have an invite system. I'm willing to give you my credentials tho.

**Comment by kaso17** [comment]
ok, I see open signup. I tried it and configure+manual search is working fine for me with the latest version.

**Comment by seanvree** [comment]
I removed it and when I go to add it again, I get Error: no results while trying to browse this tracker??
