### ISSUE TITLE
Feature request: auto download freelech releaes

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#5092]
Hi, maybe this is not possible and maybe is not a good idea but ...

What about one option to add only to private tracker to auto-download freelech download?
A simple check button to put along the "Copy ... Feed"
So during a sync when jackett see a freelech release from the torrent, save the torrent into the black hole path.
All this to try to make a good ratio.

Is a stupid/bad idea?

**Comment by ngosang** [comment]
Jackett already shows the freeleech tag in the Web UI.
That information is also available in the Torznab response, RSS feed... so third party programs can do the download (you can write a script).

**Comment by Jorman** [comment]
Yep, I developed a little script that works with flexget but, I also had to modify the xml data because flexget is not fully compatible with torznab:attr format
