### ISSUE TITLE
Jackett fails to start on port change

### ISSUE THREAD

**Issue by TGM** [Jackett/Jackett#5099]
Jackett Version 0.11.15.0 
mono version: 5.10.1.57
OS FreeBSD 11.2

https://hastebin.com/ipejubusiz.bash

**Comment by garfield69** [comment]
which port did you change to:
where did you specify to jacket the port number?
is the port available and not already allocated to some other app?
is a firewall blocking the port?

**Comment by TGM** [comment]
Port changed in ServerConfig.xml

cat ServerConfig.json
{
  "Port": 80,
  "AllowExternal": true,
...
  "BlackholeDir": "",
  "UpdateDisabled": true,
  "UpdatePrerelease": false,
  "BasePathOverride": "/config",
  "OmdbApiKey": "",
  "OmdbApiUrl": "",
  "ProxyUrl": "",
  "ProxyType": 0,
  "ProxyPort": null,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true
}

sockstat reports that there are no other ports running on 80
sockstat -4 -l
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
jackett  mono-sgen  70574 54 tcp46  *:9117                *:*

no firewall enabled.

**Comment by flightlevel** [comment]
Not familiar with FreeBSD, but commonly OSes only allow ports less than 1025 to be used by root. Can you try another port between 2000 and 65000 to see if this is the issue?

**Comment by TGM** [comment]
Hello,
Indeed using other port then, example 3000 allows the application to run without any problems.
However, then I'm running a test with "nc -4 -l 80" allows the socket to be opened without any problems.
It seems to be limited to the jackett user.
Any toughs?
