### ISSUE TITLE
Please add new Tracker Mteam

### ISSUE THREAD

**Issue by sethwarsh** [Jackett/Jackett#51]
Please add new tracker Mteam. I will arrange for an invite.

I will prepare the category mappings as well and update my request after you request an invite.

Thnaks,

Seth

**Comment by sethwarsh** [comment]
I can provide an invite to the developers

**Comment by raspdealer** [comment]
https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker

**Comment by sethwarsh** [comment]
AddCategoryMapping("401", TorznabCatType.MoviesSD);
AddCategoryMapping("402", TorznabCatType.TVHD);
AddCategoryMapping("403", TorznabCatType.TVSD);
AddCategoryMapping(“404”, TorznabCatType.MoviesBBC);
AddCategoryMapping(“405”, TorznabCatType.TVAnime);
AddCategoryMapping("407", TorznabCatType.TVSport);
AddCategoryMapping(“408”, TorznabCatType.AudioMP3);
AddCategoryMapping("419", TorznabCatType.MoviesHD);
AddCategoryMapping("420", TorznabCatType.MoviesDVD);
AddCategoryMapping("421", TorznabCatType.MoviesBluRay);
AddCategoryMapping("422”, TorznabCatType.Software);
AddCategoryMapping(“423”, TorznabCatType.Game);
AddCategoryMapping("427”, TorznabCatType.Books);
//AddCategoryMapping(“434”, TorznabCatType.AudioLossless);
AddCategoryMapping(“435”, TorznabCatType.TVDVD);
AddCategoryMapping(“438”, TorznabCatType.TVBluRay);

**Comment by sethwarsh** [comment]
I can provide an invite to the staff as soon as they are ready to work on implementation.

Do you need me to do the full torznab list commenting out whats not there, or is this acceptable.

Also do you want me to add categories like Adult that aren't in the list to it?

Thanks

Seth

**Comment by armani316** [comment]
Already added. This should be closed.
