### ISSUE TITLE
[privatehd] Exception (privatehd): Request to https://privatehd.to/torrents?in=1

### ISSUE THREAD

**Issue by nikkburgess** [Jackett/Jackett#5101]
An error occured while testing this indexer
Exception (privatehd): Request to https://privatehd.to/torrents?in=1&type=0&search= failed (Error Forbidden) - The page is protected by an Cloudflare reCaptcha. The page is in aggressive DDoS mitigation mode or your IP might be blacklisted (e.g. in case of shared VPN IPs). There's no easy way of making it usable with Jackett.: Request to https://privatehd.to/torrents?in=1&type=0&search= failed (Error Forbidden) - The page is protected by an Cloudflare reCaptcha. The page is in aggressive DDoS mitigation mode or your IP might be blacklisted (e.g. in case of shared VPN IPs). There's no easy way of making it usable with Jackett.

Jackett Version 0.11.230.0
Connected with NordVPN

**Comment by nikkburgess** [comment]
This issue provides detailed information.

**Comment by garfield69** [comment]
So the reason for raising the ticket is?
