### ISSUE TITLE
[torrentleech] Exception (torrentleech): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Parse error (Config)

### ISSUE THREAD

**Issue by BaQs** [Jackett/Jackett#5103]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------
 Jackett Version 0.11.230.0

**Comment by garfield69** [comment]
cannot replicate your problem.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by partymola** [comment]
Attaching extended log. I am having this same issue too. :(

[log.txt](https://github.com/Jackett/Jackett/files/3169632/log.txt)

**Comment by garfield69** [comment]
@partymola the log shows that your account has an outstanding issue. you need to improve your ratio.
```html
        <!-- STATS -->
        <ul class="col-xs-8 navbar-stats list-inline">
            <!--Uploaded-->
            <li class="arrow" title="Uploaded">
                <i class="fa fa-caret-up color-green text-large"></i>
                10.27 GB            </li>
            <!--Downloaded-->
            <li class="arrow" title="Downloaded">
                <i class="fa fa-caret-down color-red"></i>
                110.13 GB            </li>
            <!--Ratio-->
            <li class="ratio" title="Ratio">
                <i class="fa fa-percent"></i>
                0.093            </li>
    <div id="donateTab" class="panel-body new_donate">
                <div class="col-md-8 col-md-offset-2">
            <div class="tl-info">
            <h3><span class="tl-caution">IMPORTANT NOTICE</span></h3>
            <h4><span class="tl-caution">PLEASE GO AT THE BOTTOM OF THE PAGE TO MAKE A DONATION IF YOU WANT TO ENABLE YOUR ACCOUNT</span></h4>
            <table class="donateTable">
                <tbody>
                <tr class="even">
                    <td class="option">
                        <p>
                            <span class="tl-caution">
You are automatically being redirected to this page because your account didn't meet the right
                                ratio criteria to stay active.<br/>
                                You can either choose to donate and your account will automatically be enabled and you will gain VIP access or
                                it will automatically be deleted in 180 days.<br/><br/>

                                Either way, we would like to thank you for your support and feel free to visit our <a href="/chat">chat</a> if you have any further questions.
                            </span>
                        </p>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
```
