### ISSUE TITLE
GitHub issue link generation needs a trim

### ISSUE THREAD

**Issue by Stanzilla** [Jackett/Jackett#5104]
Currently when there is an error and the `Click here to open an issue on GitHub for this indexer.` feature generates an URL, it can be too long for browsers/servers to handle, see this example:

[edit] replaced %20 with blanks so we can at least read it a little easier   at System.Net.WebConnection.HandleError (System.Net.WebExceptionStatus st, System.Exception e, System.String where) [0x00000] in %3C6b85ae33ded1428e932cb7ae66272042%3E:0   at System.Net.WebConnection.ReadDone (System.IAsyncResult result) [0x00000] in %3C6b85ae33ded1428e932cb7ae66272042%3E:0   at System.Threading.Tasks.TaskToApm+%3C%3Ec__DisplayClass3_0.%3CInvokeCallbackWhenTaskCompletes%3Eb__0 () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.AwaitTaskContinuation.InvokeAction (System.Object state) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback (System.Threading.ContextCallback callback, System.Object state, System.Threading.Tasks.Task& currentTask) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.AwaitTaskContinuation.Run (System.Threading.Tasks.Task task, System.Boolean canInlineContinuationTask) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task.FinishContinuations () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task.FinishStageThree () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task`1[TResult].TrySetResult (TResult result) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].SetResult (TResult result) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at Mono.Net.Security.MobileAuthenticatedStream+%3CStartOperation%3Ed__58.MoveNext () [0x00000] in %3C6b85ae33ded1428e932cb7ae66272042%3E:0   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext (System.Object stateMachine) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task.FinishContinuations () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task.FinishStageThree () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task`1[TResult].TrySetResult (TResult result) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].SetResult (TResult result) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at Mono.Net.Security.AsyncProtocolRequest+%3CStartOperation%3Ed__23.MoveNext () [0x00000] in %3C6b85ae33ded1428e932cb7ae66272042%3E:0   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext (System.Object stateMachine) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task.FinishContinuations () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task.FinishStageThree () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task`1[TResult].TrySetResult (TResult result) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].SetResult (TResult result) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].SetResult (System.Threading.Tasks.Task`1[TResult] completedTask) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at Mono.Net.Security.AsyncProtocolRequest+%3CProcessOperation%3Ed__24.MoveNext () [0x00000] in %3C6b85ae33ded1428e932cb7ae66272042%3E:0   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext (System.Object stateMachine) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task.FinishContinuations () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task.FinishStageThree () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task`1[TResult].TrySetResult (TResult result) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].SetResult (TResult result) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at Mono.Net.Security.AsyncProtocolRequest+%3CInnerRead%3Ed__25.MoveNext () [0x00000] in %3C6b85ae33ded1428e932cb7ae66272042%3E:0   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext (System.Object stateMachine) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task.FinishContinuations () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task.FinishStageThree () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task`1[TResult].TrySetResult (TResult result) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].SetResult (TResult result) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at Mono.Net.Security.MobileAuthenticatedStream+%3CInnerRead%3Ed__66.MoveNext () [0x00000] in %3C6b85ae33ded1428e932cb7ae66272042%3E:0   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext (System.Object stateMachine) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task.FinishContinuations () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task.FinishStageThree () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.Task`1[TResult].TrySetResult (TResult result) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.TaskFactory`1+FromAsyncTrimPromise`1[TResult,TInstance].Complete (TInstance thisRef, System.Func`3[T1,T2,TResult] endMethod, System.IAsyncResult asyncResult, System.Boolean requiresSynchronization) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.Tasks.TaskFactory`1+FromAsyncTrimPromise`1[TResult,TInstance].CompleteFromAsyncResult (System.IAsyncResult asyncResult) [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Net.Sockets.SocketAsyncResult+%3C%3Ec.%3CComplete%3Eb__27_0 (System.Object state) [0x00000] in %3C6b85ae33ded1428e932cb7ae66272042%3E:0   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in %3Ccb410c64c7fa4e8d9841a0cbe4173d66%3E:0 : Parse error (Test)

**Comment by garfield69** [comment]
works for me.
platform?
jackett version?
mono?
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by Stanzilla** [comment]
Sorry about the spaces, I just copied the generated url, I guess this is was two bug reports in one, the HorribleSubs error and the issue tracker URL generator feature needing a trim.

My system is:
Synology DSM 6.2
Mono 5.8.0-108-11
Jackett Version 0.11.230.0

And I just ran a test on HorribleSubs again and it works now, so changing the title of the issue to make it about the URL trim only
