### ISSUE TITLE
[rarbg] Error reading JObject from JsonReader. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by JoelBrenstrum** [Jackett/Jackett#5107]
Via both Radarr and Sonarr I'm experiencing indexer errors. the indexer tests fine from both Jackett and Radarr/Sonarr

[jackett.log](https://github.com/Jackett/Jackett/files/3100653/jackett.log)

`Apr 21, 2019 10:15:23 AM	Debug	
WebClient(HttpWebClientNetCore): Returning TooManyRequests => `
`Apr 21, 2019 10:15:23 AM	Debug	
WebClient(HttpWebClientNetCore).GetString(Url:https://torrentapi.org/pubapi_v2.php?token=jbszycui2t&format=json_extended&app_id=jackett_v0.11.224.0&limit=100&ranked=0&mode=search&search_imdb=tt4633694&category=51%3B50%3B52%3B42%3B46%3B17%3B44%3B45)
`
I found the following issue, which has since been resolved and I believe is in my version of jackett (0.11.224.0) #3872

**Comment by garfield69** [comment]
Hmmm. the RarBG API has a limit of 1 request per every 2 seconds, so the current requestDelay of 2.1 seconds has been sufficient  up to now.
I suppose it shouldn't hurt to make it 2.2 and see if that prevents your issue.

**Comment by JoelBrenstrum** [comment]
From the logs I cant see the initial request, only the `Returning TooManyRequests` is it possible im being blocked some other way?

Would it be possible to detect the the status of the request `result.Status` and return more readable error? https://github.com/Jackett/Jackett/blob/f6bb9ca263d2951f11f7a3da006753a2db581228/src/Jackett.Common/Utils/Clients/WebClient.cs#L156

**Comment by garfield69** [comment]
@flightlevel  @kaso17  can you take a look at this ticket please? thanks.

**Comment by JoelBrenstrum** [comment]
I changed the indexer to use the `all` endpoint instead of rarbg directly and now its working nicely.

**Comment by garfield69** [comment]
I may have misread you original post. Are you simply saying that your problem is that the sonarr indexer that you created to use the jackett rarbg indexer was disabled in sonarr because of prior errors?
In which case, just aceess the sonarr indexer entry, click the test and it should reset.
Also, disable the all indexer when you're doing this.
Also, are you running both sonarr and radarr at the same time, doing searches with jackett rarbg?
Because that might be the cause of your *too many requests* error?

**Comment by JoelBrenstrum** [comment]
You read correctly I believe. I do get the error but I get it every-time no matter what. 
I just changed my url from `.../jackett/api/v2.0/indexers/rarbg/results/torznab/` to `.../jackett/torznab/all/api` and its wr=orking without issue at the moment.

**Comment by flightlevel** [comment]
Do you get the issue when using the Jackett dashboard?
Enable debug logging for Jackett and Sonarr, then make a request from Sonarr to trigger the issue and upload both logs
