### ISSUE TITLE
[megabliz] A private tracker categorized as a semi-private.

### ISSUE THREAD

**Issue by ExtendLord** [Jackett/Jackett#5112]
The site https://mega-bliz.nl is categorized in the type "Semi-Private" even though it requires invitation code which means that it is a "Private" tracker and not a "Semi-Private", this should be changed.

![image](https://user-images.githubusercontent.com/26222159/56483732-67dea680-64d4-11e9-8d08-c77118c56063.png)

**Comment by garfield69** [comment]
e5827c3456007358b9de1ac7c1ab3b460e77a3dd
thanks for the report.
