### ISSUE TITLE
Jackett won't start

### ISSUE THREAD

**Issue by Lordfrank007** [Jackett/Jackett#5118]
Hello,

I followed this guide: https://www.htpcguides.com/install-jackett-ubuntu-15-x-for-custom-torrents-in-sonarr/ to install Jackett on Ubuntu. The service was created and is working, but I can't get to the webpage. Here's what I have when I type "mono /opt/jackett/JackettConsole.exe":

Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 010000d6
  at Jackett.Server.Program+<>c__DisplayClass9_0.<Main>b__2 (Jackett.Common.Models.Config.ConsoleOptions options) [0x0000d] in <445038f231514d929a20e0d1a9fd9e9c>:0 
  at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x00011] in <d7beb7c65d8a42b99c2e8878c93a3c3c>:0 
  at Jackett.Server.Program.Main (System.String[] args) [0x0007c] in <445038f231514d929a20e0d1a9fd9e9c>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 010000d6
  at Jackett.Server.Program+<>c__DisplayClass9_0.<Main>b__2 (Jackett.Common.Models.Config.ConsoleOptions options) [0x0000d] in <445038f231514d929a20e0d1a9fd9e9c>:0 
  at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x00011] in <d7beb7c65d8a42b99c2e8878c93a3c3c>:0 
  at Jackett.Server.Program.Main (System.String[] args) [0x0007c] in <445038f231514d929a20e0d1a9fd9e9c>:0

**Comment by garfield69** [comment]
I recomend ditching the mono version (uninstall it) and follow https://github.com/Jackett/Jackett#install-on-linux-amdx64 instead.

**Comment by rrrevin** [comment]
LordFrank007: I went from the mono version to the core version for an issue I had as well. All went great.  The system found my previous settings and trackers.  I didn't loose anything. 

My issue was this : https://github.com/Jackett/Jackett/issues/5116

**Comment by Lordfrank007** [comment]
Hi guys, thanks for checking in.

I tried it with what you suggested but here's what I get:

media@Media:~/jackett$ sudo ./install_service_systemd.sh
Created symlink /etc/systemd/system/multi-user.target.wants/jackett.service → /etc/systemd/system/jackett.service.
Agent successfully installed and launched!
media@Media:~/jackett$ systemctl status jackett.service 
● jackett.service - Jackett Daemon
   Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: 
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-04-24 16
  Process: 2947 ExecStart=/home/media/jackett/jackett --NoRestart (code=exited, 
 Main PID: 2947 (code=exited, status=203/EXEC)
 ESCOC

When I check the status of Jackett, it's stuck on "Activating":

jackett.service                       loaded    activating auto-restart Jackett Daemon

**Comment by flightlevel** [comment]
Stop the Jackett service
Open a terminal from the jackett directory
Run `./jackett -t -l` and post the output

**Comment by Lordfrank007** [comment]
bash: ./jackett: cannot execute binary file: Exec format error

**Comment by flightlevel** [comment]
What sort of CPU are you using? Is your OS 32 or 64 bit?

**Comment by Lordfrank007** [comment]
I have an old i7 860 on which ESXi is installed. I am virtualizing Lubuntu 64-bit. I tried with the AMD64 and the ARM64 installations, both give the same message when I try to execute Jackett.

**Comment by flightlevel** [comment]
Weird, that error is normally caused by incorrect architecture i.e. its expected when trying to run an ARM version but not with the AMDx64 version

What's the output of `uname -a`
From the the folder with jackett output of `file ./jackett`

Assuming you are running Lubuntu 18, I'd run to make sure no dependencies are missing
`
sudo apt-get install liblttng-ust0 libcurl4 libssl1.0.0 libkrb5-3 zlib1g libicu60
`
If anything installs then try again using the AMDx64 version (double check it is the AMDx64 version)

**Comment by garfield69** [comment]
#5167 also reported `status=203/EXEC` so it could be related.

**Comment by Lordfrank007** [comment]
I started over with Yesterday's release and it works. Thanks guys!
