### ISSUE TITLE
[torrentdownloads] Exception (torrentdownloads): Request to https://www.torrentdownloads.me/today/?new=1

### ISSUE THREAD

**Issue by MrAmos123** [Jackett/Jackett#5119]
(At the bottom of your Jackett Dashboard page) **Jackett version**:  0.11.221.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**: (Using Jackett Linux build)

**Comment by garfield69** [comment]
I'm currently seeing Cloudflare errors **522: Connection timed out** and **523: Origin is unreachable**.
but via the browser direct it seems to be working fine.
taking a deeper look.

**Comment by garfield69** [comment]
don't know what is going on. some kind of cloudflare interference... 
@kaso17  ideas on this one?
browser direct works fine, but via Jackett seeing cloudflare 523 and 522 regularly. 
tried adding headers for accept, and user-agent, even tried followredirect. no joy.

**Comment by MrAmos123** [comment]
Thanks for taking a look at this one, both.

**Comment by garfield69** [comment]
indexer appears to be working for me again.
must have been some kind of problem with the sites service provider.
