### ISSUE TITLE
Append Label

### ISSUE THREAD

**Issue by cyris69** [Jackett/Jackett#512]
Not sure if this is an issue or I'm missing something. I can no longer use CP's built in IPT searcher as it doesnt work, however after installing jackette which does work. I am however not able to see a way of having said found and added torrent to get a label added. Since I use CP to all my users to find and add movies and then be added to plex I need the label to set it to a specific folder plex uses. Is there a way of doing the label?

**Comment by kaso17** [comment]
Jackett is not responsible for any labels, CP adds the torrent to your client and is responsible for labels.

**Comment by cyris69** [comment]
Roger, I wasn't sure if it made any other changes. Thanks for that and I've asked on the CP git.
