### ISSUE TITLE
[metaltracker] 1 minute wait for all download

### ISSUE THREAD

**Issue by xfouloux** [Jackett/Jackett#5120]
Hi,

is there any way to have a wait/sleep timer for download part of the definition ?

Metaltracker (https://en.metal-tracker.com/) now make us wait 1 minute to download any torrent.
So you go to the download page, wait 1 minute, and get redirected to the same page but this time the download start.

Thanks.

**Comment by ngosang** [comment]
@xfouloux Is that fixed?
If not, the tracker has to be rewritten in C#.

**Comment by xfouloux** [comment]
indexer seems to be working fine, i hadn't checked this in a while
