### ISSUE TITLE
[NEWPCT] Wrong categories?

### ISSUE THREAD

**Issue by jasimancas** [Jackett/Jackett#5121]
Is it possible that the NEWPCT categories have an error? Especially movies.

"Any" Category:
![image](https://user-images.githubusercontent.com/15717847/56689203-dab96e80-66da-11e9-919f-ee7863499d8e.png)

"2000 (Movies)" Category:
![image](https://user-images.githubusercontent.com/15717847/56689248-eefd6b80-66da-11e9-8aad-40a26b60ae06.png)

Only have one category, maybe web update the categories?
![image](https://user-images.githubusercontent.com/15717847/56689322-1ce2b000-66db-11e9-946f-0cdf60a81eab.png)

Jackett Version 0.11.245.0

**Comment by garfield69** [comment]
nah, its the site, it sucks. @snamds  has been refining the indexer c# code over time, maybe he can improve the movie cat tagging... I'm not going to touch it, the code is way too complicated for me.
