### ISSUE TITLE
[Rarbg] search seems to be ignoring Season and Episode from sonarr 

### ISSUE THREAD

**Issue by Dnkhatri** [Jackett/Jackett#5124]
Searching directly from jackett with S01E01 works fine but for some reason Jackett seem to be ignoring the season and episode when I search using sonarr. First I thought it might be sonarr not sending the season and episode but looking at the results and search words from other trackers this is only happening with rarbg.

**Comment by garfield69** [comment]
huh?
using sonarr's built in rarbg i get this:
![image](https://user-images.githubusercontent.com/6933240/56712316-325ee500-6782-11e9-953c-34a858569142.png)
and using sonarr with the jackett rarbg I get this:
![image](https://user-images.githubusercontent.com/6933240/56712400-78b44400-6782-11e9-9eec-d83703175c7f.png)

results are identical. i'm using jackett 0.11.247

**Comment by Dnkhatri** [comment]
I was just a version behind updated to the latest jackett version still have the same problem. For other trackers jackett makes the correct search results I am getting these results for rarbg only. Btw I am using jackett netcore version on linux mint.

![jakcett](https://user-images.githubusercontent.com/7855682/56713199-b2298700-6763-11e9-94bd-1cf7d93449d2.png)

**Comment by garfield69** [comment]
sonarr rarbg via jackett
![image](https://user-images.githubusercontent.com/6933240/56713665-6e944480-6786-11e9-87c2-8ba2bbe5ad7e.png)
sonarr rarbg native
![image](https://user-images.githubusercontent.com/6933240/56713701-9a172f00-6786-11e9-9995-c2a4193e42ad.png)

no problems here.
note: do not use sonarr rarbg native and sonarr rarbg jackett at the same time. they both use the same rarbg server API, and  it has a 1 request every 2 seconds gateway. you could get clashes between the search requests and have failures.

since the sonarr rarbg native works for you I'd drop the sonarr rarbg jackett indexer.
if you really want to use it then drop the sonarr native rarbg and see if that clears up the issue.
if it still does not work then examine your sonarr jackett indexer config carefully and check it has been set up correctly.
other than that I don't know what it could be, its not jackett's rarbg indexer that is the problem here.

**Comment by garfield69** [comment]
have you kept your sonarr up to date? maybe you need to update it.

**Comment by Dnkhatri** [comment]
Yeah I just dropped the jackett rarbg indexer I actually was not using the  sonarr rarbg indexer just installed it to test if it gets the same kind of results. Its weird though looking at the logs for the other jackett trackers and makes me curious why this is happening. Even the log entry for rargb in jackett is a bit different compared to the rest. Anyway I am not closing this issue at the moment maybe someone else has an idea what is going on currently I am just disabling the jackett rarbg in favour of sonarr native.

When | Level | Message
-- | -- | --
Apr 25, 2019 02:35:11 PM | Info | **Found 59 (0 new) releases from RARBG**
Apr 25, 2019 02:35:09 PM | Info | Found 0 releases from Avistaz for: Whiskey Cavalier S01E09
Apr 25, 2019 02:35:09 PM | Info | Found 2 releases from TorrentLeech for: Whiskey Cavalier S01E09
Apr 25, 2019 02:35:06 PM | Info | Found 0 releases from PrivateHD for: Whiskey Cavalier S01E09

**Comment by Dnkhatri** [comment]
> have you kept your sonarr up to date? maybe you need to update it.

I am using the latest v3 sonarr. If the results were similar for other trackers I could blame sonarr the rest seem to be okay.

**Comment by garfield69** [comment]
sonarr v3? i'm on  2.0.0.5322 which is the latest official release https://github.com/Sonarr/Sonarr/releases

where you get v3 from?

**Comment by garfield69** [comment]
Oh you are using sonarr BETA! that might explain everything.

**Comment by Dnkhatri** [comment]
> Oh you are using sonarr BETA! that might explain everything.

that does not explain the problem with the results though as the results for other trackers are correct I even deleted rarbg from jackett and sonarr added it again and it is still the same. This is the sonarr log the search terms are exactly the same for all the trackers unless I am missing something in jackett settings for rarbg.  

```
```
|Info|NzbSearchService|Searching 4 indexers for [Whiskey Cavalier : S01E09]
19-4-25 14:32:40.6|Debug|Torznab|Downloading Feed http://192.168.1.240/api/v2.0/indexers/torrentleech/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Whiskey%20Cavalier&season=1&ep=9
19-4-25 14:32:40.6|Debug|Torznab|Downloading Feed http://192.168.1.240/api/v2.0/indexers/avistaz/results/torznab/api?t=tvsearch&cat=5030,5040,5020,5000,5050&extended=1&apikey=(removed)&offset=0&limit=100&q=Whiskey%20Cavalier&season=1&ep=9
19-4-25 14:32:40.6|Debug|Torznab|Downloading Feed http://192.168.1.240/api/v2.0/indexers/privatehd/results/torznab/api?t=tvsearch&cat=5030,5040,5020,5000,5050&extended=1&apikey=(removed)&offset=0&limit=100&q=Whiskey%20Cavalier&season=1&ep=9
19-4-25 14:32:40.6|Debug|Torznab|Downloading Feed http://192.168.1.240/api/v2.0/indexers/rarbg/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=tt7599942&season=1&ep=9
```

**Comment by garfield69** [comment]
@kaso17  @flightlevel  your input on this ticket is requested ;-)

**Comment by garfield69** [comment]
only one other possibility occurs to me, which is that you may not be as up to date on Jackett as is apparent by just the version level. 
there was a bunch of releases around the 0.10.something mark where the updater was not working as it should.
so one more thing to try is to manually fetch the latest Jackett and install it over the top of the old one, just to be sure that you have all the latest fixes etc. (if you are using a service, make sure to stop it before installing the new one).

**Comment by Dnkhatri** [comment]
Okay I found discrepancy rarbg is url has the imdb number instead of show name unlike the others  
http://192.168.1.240/api/v2.0/indexers/rarbg/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=tt7599942&season=1&ep=9

**Comment by Dnkhatri** [comment]
> only one other possibility occurs to me, which is that you may not be as up to date on Jackett as is apparent by just the version level.
> there was a bunch of releases around the 0.10.something mark where the updater was not working as it should.
> so one more thing to try is to manually fetch the latest Jackett and install it over the top of the old one, just to be sure that you have all the latest fixes etc. (if you are using a service, make sure to stop it before installing the new one).

I just upgrade my linux install from scratch so installed the net core version which was not around when Jackett was v10. My current Jackett Version is 0.11.247.0

**Comment by garfield69** [comment]
when my sonarr v2 sends a request to jackett its
`https://torrentapi.org/pubapi_v2.php?token=n98p2oqifa&format=json_extended&app_id=jackett_v0.11.247.0&limit=100&ranked=0&mode=search&search_string=Whiskey+Cavalier+S01E08&category=18%3B41%3B49`
so you've found the difference.

**Comment by garfield69** [comment]
oops sorry paster the wrong log.. here is the correct one.
`http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Whiskey%20Cavalier&season=1&ep=8`

**Comment by garfield69** [comment]
the jackett rarbg indexer should in theory be able to use the imdbid,
https://github.com/Jackett/Jackett/blob/db300f5ae921041f1a085468e523172dba7d9b1f/src/Jackett.Common/Indexers/Rarbg.cs#L158-L162
perhaps the jackett indexer need to be tested to ensure the code works as intended.

**Comment by Dnkhatri** [comment]
> perhaps the jackett indexer need to be tested to ensure the code works as intended.

But it does seem to be a bug in sonarr as it should be sending the show name it is up to jackett to decide it wants to search with imbd or show name. If my understanding of how jackett and sonarr work is correct. My settings for all the Jackett trackers in sonarr are the same but the search term for rarbg is  only different. Do you think I should open a ticket in sonarr or do you its a Jackett error.

**Comment by garfield69** [comment]
that is a question for the jackett c# devs to answer, out of my expertise.

**Comment by flightlevel** [comment]
@kaso17 Sonarr have made a change for v3. They will now send imdbid instead of show name if caps indicates that the tracker can handle imdb. Imdb works well for movies but I can't see it working well for tv shows, any show with more than one season is likely to fill the first results page if you don't search by season and episode number.
Am thinking we should remove these two lines https://github.com/Jackett/Jackett/blob/a7fab04e42f20d1d49bdf0d916d6f1e741b8c33f/src/Jackett.Common/Models/TorznabCapabilities.cs#L65-L66
Thoughts?

**Comment by fsegouin** [comment]
Is there any way we can manually disable imdb search per tracker in the meantime?

**Comment by garfield69** [comment]
@Dnkhatri  @fsegouin   Does Jackett v0.11.325 solve this issue ?

**Comment by Dnkhatri** [comment]
yes the results seem correct now

**Comment by mkelley2** [comment]
I just installed sonarr v3 last night and I'm getting this issue with every indexer i'm using through jackett. I've upgraded jackett.
![proof](https://i.imgur.com/Oqnp4fO.png "Messed up search results")

**Comment by garfield69** [comment]
PR #5791 is pending review, once accepted this may help with Sonnar v3 users. watch this space for updates.

**Comment by mkelley2** [comment]
going from v0.11.655 to v0.11.659 seems to have solved the problem for me.
