### ISSUE TITLE
[torrentslocal] Error: Новинки (Config)

### ISSUE THREAD

**Issue by ExtendLord** [Jackett/Jackett#5126]
When I try to login to my torrents-local account from Jackett it says "Error: Новинки"(Error: Newbie), while from the site I can login and search.

**Comment by garfield69** [comment]
are you using Cyrillic characters in your username or password?
I've seen tickets for Jackett Russian indexers where this has been an issue before. #3061 for instance.

**Comment by ExtendLord** [comment]
@garfield69 No, both the username and the password are in English letters, rutracker does work.
It doesn't say that my username/password is incorrect, it says Newbie even though I can search in the website itself with the same account.

**Comment by garfield69** [comment]
works for me.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by ExtendLord** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/3118946/log.txt)
Here it is @garfield69

**Comment by garfield69** [comment]
darn, nothing useful in that log.
when you login directly from your browser, and you click your username to view your profile, what does your profile say is your status?
mine is `Роль:  Пользователь`

can you access https://torrents-local.xyz/tracker.php and get results?

**Comment by revolveruk30** [comment]
I have the same issue. Maybe Torrents Local changed the url used to log in?

**Comment by Prosecutor** [comment]
Hi there!

So basically getiting this kind of error.

Log file: https://pastebin.com/vmuWvsKz
Version: v0.11.340
Status: Роль: Пользователь
Via: https://torrents-local.xyz/tracker.php i get the results and can access them
Using seedbox.

**Comment by garfield69** [comment]
@Prosecutor I need to see the full html that the site returns as you login, which you only get if **enhanced** logging is enabled.
I suspect there is some kind of notice being pushed out which interferes with recognising that the login was successful.

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by garfield69** [comment]
@ExtendLord, @revolveruk30   do you still have this problem or did you figure out what needed to change in your account to allow jackett to work with this indexer?

**Comment by garfield69** [comment]
the jackett indexer only works with the classic forum style.
on the torrentslocal site, access your profile preferences and set the forum style to Классическая тема
see if that works for you.
