### ISSUE TITLE
Web UI doesn't load.

### ISSUE THREAD

**Issue by crazymaca69** [Jackett/Jackett#5128]
Jackett is loading but the web UI is blank on Safari using Mac OSX Mojave (server is running OSX Sierra).

I have just updated to the newest release and still the same is happening. Any help appreciated :-)

**Comment by garfield69** [comment]
working for me on my win10 VB mojave image.
by *updated* you mean you followed https://github.com/Jackett/Jackett#installation-on-macos or used some other process?
if you access the Safari *develop menu* and *show web inspector* and click on the *console* tab are there any errors?
from a terminal, if shutdown the service with `launchctl unload ~/Library/LaunchAgents/org.user.Jackett.plist` and cd to where ever you installed jackett, and start it manually with `./jackett` what do you get?

**Comment by crazymaca69** [comment]
ok so i've realised if i use localhost:9117 actually on the server, it opens. If i use the private IP from another computer, it does not load. 

Console from safari shows no errors at all.

**Comment by garfield69** [comment]
clearly your server does not have the port open to the web or your firewall does not have the port mapped to the jackett port or it is being blocked. 
@flightlevel  insights?

**Comment by flightlevel** [comment]
Also double check 'external access' is ticked on the dashboard

**Comment by XxUnkn0wnxX** [comment]
as of v0.11.279 the mono build & standalone build doesnt startup web UI blank & in log it says 
2019-05-05 02:08:50.0596 Info Starting Jackett v0.11.279.0 - it hangs here & does nothing even after i delete all config the default port does not work either...
