### ISSUE TITLE
CinemaZ search error

### ISSUE THREAD

**Issue by savahu** [Jackett/Jackett#513]
With the latest development version (built it using Visual Studio), I get the following error when doing a search on CinemaZ:

> Error on 20160916153348 for CinemaZ.txtSystem.ArgumentNullException: Value cannot be null.
> Parameter name: uriString
>   at System.Uri.Parse (UriKind kind, System.String uriString) <0x4126b460 + 0x0007b> in <filename unknown>:0 
>   at System.Uri.ParseUri (UriKind kind) <0x4126b340 + 0x00023> in <filename unknown>:0 
>   at System.Uri..ctor (System.String uriString, Boolean dontEscape) <0x4126b0c0 + 0x001b7> in <filename unknown>:0 
>   at System.Uri..ctor (System.String uriString) <0x4126b090 + 0x00013> in <filename unknown>:0 
>   at Jackett.Indexers.AvistazTracker+<PerformQuery>d__9.MoveNext () <0x413fc720 + 0x005db> in <filename unknown>:0 
>

**Comment by kaso17** [comment]
The exception occurred due to some new rows at the end of the page. It shouldn't have any impact on the search results. But it's fixed with #516 anyway.

**Comment by savahu** [comment]
Thanks, works great!
Also thanks for the PTN 'AND Search', that also works 👍
