### ISSUE TITLE
Jackett "Updates", deletes all program files

### ISSUE THREAD

**Issue by helis4life** [Jackett/Jackett#5132]
I get a windows 10 notification that jackett installed an update, 0.11.247. But instead all files in jackett folder are deleted/removed except for uninstall.dat and .exe.

This has happened several times now. This last time it said it updated to version I already installed yesterday, 0.11.247. Today it says it updated to this version again, all files gone

To fix I have to uninstall via windows app, restart computer then reinstall

**Comment by helis4life** [comment]
I checked disable auto-update in jackett configuration but it still "updated" to the same version, deleting all program files and requiring a restart/reinstall

**Comment by flightlevel** [comment]
From `c:\ProgramData\Jackett` provide the log file and updater log file.
What antivirus are you using?

**Comment by chaospike** [comment]
Same thing on my install. I keep the Binaries tar.gz next to root to extract the contents back into /opt/Jackett ; Happens multiple times a day. 

Jackett Version 0.11.247.0 - Debian Stretch 9.6;

**Comment by flightlevel** [comment]
@chaospike Without logs (application and updater) nothing can be done

**Comment by helis4life** [comment]
Where can i find the logs? c:\ProgramData\Jackett contains nothing but unins000.dat and unins000.exe

Quick update: Jackett is running fine currently, in the c:\ProgramData\Jackett there is still only those two files mentioned above. So my previous comment about there being an update and files being removed isnt entirely accurate it seems. I install as a service.

The issue still exists, where jackett will update and then not function after, but im not sure what its doing

Also, when i set disable auto update i did not restart jackett to implement those changes. I have done that now and I have not been prompted for an update since then. 

I can allow updates and see if the issue happens again if you want, so that i can provide logs. But again there has never been any logs found in programdata/jackett. Is there anywhere else they could be located?

My antivirus is avast

**Comment by flightlevel** [comment]
Where is Jackett running from then? (Can use task manager, right click on Jackett and then properties to find out)
If you do run `%PROGRAMDATA%` what folder does it take you to?
Check Avast is there anything in quarantine/chest?

**Comment by flightlevel** [comment]
Also, if you restart the service, then open the dashboard and view logs button, you might see the path its using

**Comment by helis4life** [comment]
Thanks, I was looking in the wrong folder
[log.txt.20190426.00000.txt](https://github.com/Jackett/Jackett/files/3127127/log.txt.20190426.00000.txt)
[updater.txt](https://github.com/Jackett/Jackett/files/3127128/updater.txt)

**Comment by flightlevel** [comment]
mmm, the updater just dies shortly after starting
So where was Jackett located in the end? `C:\ProgramData\Jackett` ?
I'd disable Avast, click check for updates and see what happens

Looks similar to https://github.com/Jackett/Jackett/issues/3662

**Comment by helis4life** [comment]
Yes it was in programdata\jackett. I mistaken thought that referred to program files\

Thanks ill give that a go

**Comment by helis4life** [comment]
Looked in avast virus chest, it was quarantining jacketconsole.exe as reported in 3662
added exception and ran update. Updated with no issues. Thanks for the help

**Comment by flightlevel** [comment]
Good to hear that fixed it
