### ISSUE TITLE
[avistaz] Verification required (Config)

### ISSUE THREAD

**Issue by adrian-alexander** [Jackett/Jackett#5136]
I tried adding Avistaz to Jackett, put in the correct credentials, and got hit with a "Verification required" error. I added Avistaz to a different Jackett before just fine, and when I log into Avistaz normally there doesn't seem to be anything new. The only other "Verification required" post is empty, so I got nothing to help me. Any help is appreciated, thank you.
 **Jackett version**: Jackett Version 0.11.251.0 

-------------------------------

**Comment by garfield69** [comment]
looking at the indexer code it appears you are required to use your email address for the login, are you?

**Comment by NewbTheGamer2** [comment]
> 
> 
> looking at the indexer code it appears you are required to use your email address for the login, are you?

I just tried that, and I get the same error. When I previously logged into Avistaz with Jackett, I used my username. This is the log code: https://pastebin.com/hk7pRbvr

I have tried other private trackers, and they worked fine with just my username, if that matters.

**Comment by garfield69** [comment]
@kaso17  could you take a look at this ticket please? thanks.

**Comment by ngosang** [comment]
@adrian-alexander Is that fixed? If not, do you have an invitation?

**Comment by RoloSoze** [comment]
@ngosang :)

**Comment by ngosang** [comment]
I can't reproduce this issue. It's working for me.

**Comment by RoloSoze** [comment]
Me neither. 

@adrian-alexander I'll close this issue for now. If you're still facing this problem, feel free to reopen it and provide more details. Thanks.
