### ISSUE TITLE
Error after logging into Jackett via external ip

### ISSUE THREAD

**Issue by JimboJamez** [Jackett/Jackett#5138]
Hi Everyone

I have just set up Jackett on my Windows 10 machine and have it working locally. I have created an entry in my NGINX config files (copy below) and can access the log in page remotely (outside of my network):

	location /jackett {
            proxy_pass http://127.0.0.1:9117;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real_IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Ssl on;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_redirect default;
        }

When I enter the password the page then fails to load. I am presented with the following error:

> This page isn't working
> If the problem continues, contact the site owner.
> HTTP ERROR 400

I have updated all the required fields in the Jackett Configuration and everything seems to be OK there.

Any help/ideas on how to resolve this would be greatly appreciated.

**Comment by garfield69** [comment]
please read https://github.com/Jackett/Jackett#running-jackett-behind-a-reverse-proxy and try the supplied example.

**Comment by JimboJamez** [comment]
Thanks @garfield69 that works perfectly!
