### ISSUE TITLE
[REQ] hdolimpo .co [Private / Spanish]

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#5142]
Request to add support for Spanish private tracker https://hdolimpo.co
I don't have invitations, but if you provide an email address I think I can get one.
Thank you!

**Comment by RicardoVelaC** [comment]
I have 1 invitation for https://hdolimpo.co

**Comment by ngosang** [comment]
@garfield69 I can send you an invite. Just give me the email.

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by RicardoVelaC** [comment]
I sent you an invite

**Comment by garfield69** [comment]
registration and login successful. thank you.

**Comment by garfield69** [comment]
unfortunately this site uses js to generate its torrent list results after the html has been posted.
as such it is unsuitable for processing by the cardigann html scraping processor.
it will require the indexer be written on c#.

**Comment by garfield69** [comment]
Jackett 0.12.1486

**Comment by killer1595** [comment]
> 
> 
> @garfield69 I can send you an invite. Just give me the email.

Can i get invite please ?

**Comment by killer1595** [comment]
> 
> 
> I have 1 invitation for https://hdolimpo.co

can i get one please ?

**Comment by play15** [comment]
> @ garfield69 posso te enviar um convite. Apenas me dê o e-mail.

amigo me doa um convite
