### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://www2.yggtorrent.gg/ using form selector form[action$=

### ISSUE THREAD

**Issue by Karrock** [Jackett/Jackett#5144]
Hi actually I cannot use Yggtorrent as tracker through Jacket.

I got the following error :
```
Login failed: No form found on https://www2.yggtorrent.gg/ using form selector form[action$="/user/login"]
```

I tried to restart my container but same result.

Then I stopped it and pull the latest image and same result too.

I know that this is probably a problem from Ygg but have you an idea to resolve 

Jacket version : 0.8.1014.0

**Comment by garfield69** [comment]
to use ygg you will need to update your out of date 0.8.* Jackett.  
current Jackett version is v0.11.259
