### ISSUE TITLE
MKvCage (www.mkvcage.ws)

### ISSUE THREAD

**Issue by Theli93** [Jackett/Jackett#5146]
MKvCage really is a bit of a nightmare with the blog style and all the ads.
It may be a small miracle, if it can be added.

**Comment by garfield69** [comment]
darn, I am getting the new cloudflare DDoS test with this site so until https://github.com/elcattivo/CloudFlareUtilities/issues/44 is resolved I cant progress to testing my indexer code :-(

**Comment by Theli93** [comment]
Thank you for trying anyway.
I'll keep my fingers crossed for somewhere downstream, hopefully.

**Comment by Forceflow** [comment]
They used to have an RSS feed that was somewhat parseable, but that has vanished.

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.432

**Comment by garfield69** [comment]
https://www.mkvcage.com/ currently returning Cloudflare 522 Connection timed out.

**Comment by rrrevin** [comment]
It looks like it was shutdown..
https://torrentfreak.com/popular-torrent-site-mkvcage-faces-lawsuit-and-goes-offline/

**Comment by garfield69** [comment]
https://www.mkvcage.nl/ currently returning
```
Resource Limit Is Reached
The website is temporarily unable to service your request as it exceeded resource limit. Please try again later.
```

**Comment by garfield69** [comment]
https://www.mkvcage.nl/  now returning 
![image](https://user-images.githubusercontent.com/6933240/69451125-85098980-0dc3-11ea-9116-d241959d860f.png)
anyone know if this is it for good this time or has it moved to a new domain?

**Comment by garfield69** [comment]
removed.
