### ISSUE TITLE
[turktorrent] Login failed: No form found on http://turktorrent.us/login.php using form selector form[action=

### ISSUE THREAD

**Issue by kekec777** [Jackett/Jackett#5149]
Jackett Version 0.11.256.0

Hallo forum 

It seems the login / add function is not working proberly ?
Ther is a normally captcha box when you add this index, but when i try to add it theres none?

Thanks for support / help :)

**Comment by garfield69** [comment]
works for me.
![image](https://user-images.githubusercontent.com/6933240/56935397-d8c13680-6b44-11e9-80d4-9a747073542e.png)
what do you see?

**Comment by kekec777** [comment]
Hmm it seems the problem was on my browser, sorry for the interruption 

But BIG THANKS FOR ALL THE THING YOU GUYS DO :) LOVE IT
