### ISSUE TITLE
[rutracker] Exception (rutracker): Authentication failed because the remote party has closed the transport stream.: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by VasilevAndrei** [Jackett/Jackett#5151]
Hi all.
Recently, I often get error "Authentication failed because the remote party has closed the transport stream" when testing a tracker. After some time, the test passes successfully, but then again I get an error.
Jackett Version 0.11.256.0
MonoJIT compiler version 5.20.1.19
[Log.txt](https://github.com/Jackett/Jackett/files/3128217/Log.txt)

**Comment by garfield69** [comment]
consider dumping the mono jackett version and switching to the net core.
pick the appropriate for your platform
https://github.com/Jackett/Jackett#install-on-linux-amdx64
https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above
https://github.com/Jackett/Jackett#installation-on-macos

if you are still getting this error on net core, then enable enhanced logging and provide full log.

**Comment by VasilevAndrei** [comment]
I set up a connection to the trackers through a proxy and this solved the problem. I think the problem was in my internet provider.
