### ISSUE TITLE
RARBG : Error: Only http or https scheme is allowed

### ISSUE THREAD

**Issue by axelantoine** [Jackett/Jackett#5156]
Hi,

When I'm trying to manually download a file from the RARBG indexer, I have the error :

`Error: Only http or https scheme is allowed`

Logs are :

Apr 30, 2019 03:31:33 PM | Info | Executed action method 
Jackett.Server.Controllers.BlackholeController.Blackhole (JackettConsole), returned result Microsoft.AspNetCore.Mvc.JsonResult in 3.865ms.

Apr 30, 2019 03:31:33 PM | Info | 
Executed action method Jackett.Server.Controllers.BlackholeController.Blackhole (JackettConsole), returned result Microsoft.AspNetCore.Mvc.JsonResult in 3.865ms.

Apr 30, 2019 03:31:33 PM | **Error** | 
Error downloading to blackhole rarbg magnet:?xt=urn:btih:2600af8beb71751a6cd223ea25b090e6891a40ed&dn=Thor.The.Dark.World.2013.1080p.BluRay.x264-SPARKS&tr=http:%2F%2Ftracker.trackerfix.com:80%2Fannounce&tr=udp:%2F%2F9.rarbg.me:2710&tr=udp:%2F%2F9.rarbg.to:2710&tr=udp:%2F%2Fopen.demonii.com:1337%2Fannounce

Apr 30, 2019 03:31:33 PM | Debug | 
WebClient(HttpWebClient).GetString(Url:magnet:?xt=urn:btih:2600af8beb71751a6cd223ea25b090e6891a40ed&dn=Thor.The.Dark.World.2013.1080p.BluRay.x264-SPARKS&tr=http:%2F%2Ftracker.trackerfix.com:80%2Fannounce&tr=udp:%2F%2F9.rarbg.me:2710&tr=udp:%2F%2F9.rarbg.to:2710&tr=udp:%2F%2Fopen.demonii.com:1337%2Fannounce)

Apr 30, 2019 03:31:33 PM | Info | 
Executing action method Jackett.Server.Controllers.BlackholeController.Blackhole (JackettConsole) with arguments (rarbg, Q2ZESjhPc1JNOHNWWUYxRW8yRnRDeUJ0Y0U3bDBnQ3p5TjdTUE5acE1yVUJrb3p3cE5idVUyV3NtY2ZabWkyY3ZOSnVmbmN0Tl9kaHZCR1JNaE5LVHF5RnZVdGVBcW9CaVJzQm83RFBZSHZnRGtLSFB2MnJ2SVdJc0FyY182M1JQQndUTkpVak4zVVZ0SmRFLVd3MzJ1b2oyQmRpY2VhandmSC1INDdVbzl6R0FwTVpuRjhUcExUNjNnaC10dzRFdWh2X09Gd0RtYlZqdXRkYXhCQVpjQnAtV3BkUnU3dmVjX3lpdk9xNjVaZW1Fa2J3dFk2UXZpZUZfeGNtaTdGbmFhN1lLN1N0U1VjUTBjMnVsZ2NiUnBmcDlWMnhaLWNsaWE0NUc1S3BCQTUxUXNJUHpPSjYzUEtBZU43b05BdGdBNmkwTmgxa1ptUm1LZldVd3gwX2RDaVV2SUpwT2JFUWFQWkFEN1BmWE1uaVFSVFpIOE9IRXF3cERLYTJ0WjM1QTkzellxcEtvQmpiamR1MEZIbEdtTUhPS1dtUERET242RWlaS1gtZlVkbFN1WHdiNmdQQklTd05uN3ZYRUkyd1F6NWFDRms2WHZBY2MzQ3JXbW4tZTlYVTJQbw, bn8u8sr5gm534ouepbv4crb451l9rqj8, Thor.The.Dark.World.2013.1080p.BluRay.x264-SPARKS) - Validation state: Valid

Weird thing is Sonarr is able to grab releases from Jackett RARBG indexer without any issues. So it seems the problem is related to the BlackHole directory (which is working fine for others indexers by the way..)

Any ideas ?

Thanks :D

(At the bottom of your Jackett Dashboard page) **Jackett version**: 0.11.259.0 
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**: 5.18.0.240-12 (Synology 918+)

-------------------------------

**Comment by garfield69** [comment]
check your jackett rarbg config. is the *generate torrent download link* check box ticked? try switching it on and see if it makes a difference.

**Comment by axelantoine** [comment]
Hi,

It seems to work for now.
You probably don't remember it, but I was one of thus who had problems with the DDoS protection and you created the workaround with magnet files.
Seems it is the contrary now.

I'll keep you updated if anything change.
Seems I will need to switch between magnets and torrent files from now.
