### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by hoshsadiq** [Jackett/Jackett#5160]
Hello, is there any documentation for the API? E.g. what endpoints are there? What options each endpoint has? etc. If not, would it be possible to get something like swagger implemented? Swagger would allow automatic detection of all the endpoints and creates a nice interface for it. This could either be built into the app, or dumped as HTML which can then be added to a website (could potentially be hosted on github pages).

**Comment by flightlevel** [comment]
There is information on the torznab standard here https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer is that what you mean?

**Comment by hoshsadiq** [comment]
Ah! So Jackett follows the torznab APIs? Perfect! Thanks

**Comment by hoshsadiq** [comment]
Hello, sorry to be a pain. Maybe I'm being stupid, but your API doesn't seem to be following what that page is saying at all. There is no `t=` parameter for example. Where can I find a list of all endpoints Jackett implements and their parameters? This is so I can implement a client for Jackett.

**Comment by flightlevel** [comment]
There is a t parameter. I'd download a client that uses torznab like Sonarr and see how it forms its requests in the logs

e.g. `/api/v2.0/indexers/rarbg/results/torznab?t=caps&apikey=yourApiKey`
or
`/api/v2.0/indexers/rarbg/results/torznab?t=tvsearch&q=blacklist&season=6&ep=18&apikey=yourApiKey`

That's all the documentation I know of

**Comment by hoshsadiq** [comment]
Hummm! Okay. I will try my best. And would you guys at all consider adding something like Swagger.io?

**Comment by flightlevel** [comment]
I have no interest in adding swagger, but you are most welcome to submit a pull request for it

**Comment by alxlaxv** [comment]
Hello @hoshsadiq 
Did you find out a bit about the "t" parameter?
What is it used for?

**Comment by hoshsadiq** [comment]
Yes, the page @ghost linked contains all the information. It does get returned using XML but it contains all the data I needed.
