### ISSUE TITLE
Update to standalone from mono instructions do not work

### ISSUE THREAD

**Issue by mattdinsdale** [Jackett/Jackett#5171]
The new version showing the banner on how to update to standalone from mono on linux does nothing the link is to a # anchor

**Comment by GuenMat** [comment]
Same here on Jackett Version 0.11.268.0.
I was trying to find the instructions :( 
Does anybody has them ?

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett#install-on-linux-amdx64 or https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above depending on your platform.

**Comment by GuenMat** [comment]
Thanks

**Comment by Forceflow** [comment]
Did not work for me on Ubuntu 19.04.
Installed all the dependencies, still complains that no usable version of libssl was found.

The version from the Ubuntu repos is libssl1.1, maybe it wants 1.0, but that's out of packaging.

**Comment by garfield69** [comment]
poke.
try https://askubuntu.com/questions/989086/stuck-downgrading-libssl-on-ubuntu-16-04/989089#989089

**Comment by flightlevel** [comment]
My bad, fixed now

@Forceflow See #5179
