### ISSUE TITLE
Jackett won't start, only output is "Bus error"

### ISSUE THREAD

**Issue by henrywhitaker3** [Jackett/Jackett#5173]
The linux amd64 version was working fine for around 2 weeks then stopped working and running `/opt/Jackett/jackett` from the command line produces the output `Bus error`. The mono version still works fine on the same VM.

**Comment by garfield69** [comment]
try installing the latest version manually. 
if it works then turn off the auto-update. 
possible related to #5167

**Comment by henrywhitaker3** [comment]
Yeah that's sorted it

**Comment by jaum20** [comment]
It was working fine for me for months and now I'm getting this error. Already tried to remove the entire folder and downloaded the last version, but the error persists. 

```
./jackett_launcher.sh 
Bus error
```

**Comment by ilike2burnthing** [comment]
@jaum20 please open a new issue and provide the requested information.
