### ISSUE TITLE
Jackett.Tray has stopped working

### ISSUE THREAD

**Issue by MoinFaraz** [Jackett/Jackett#518]
Everytime I open Jackett, I am presented with this error. When I hit 'view problem details' I see this 

```
Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: JackettTray.exe
  Problem Signature 02: 0.7.380.0
  Problem Signature 03: 57d24a8b
  Problem Signature 04: Newtonsoft.Json
  Problem Signature 05: 9.0.1.19813
  Problem Signature 06: 575e9365
  Problem Signature 07: 996
  Problem Signature 08: 0
  Problem Signature 09: Newtonsoft.Json.JsonReader
  OS Version:   6.1.7601.2.1.0.256.4
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

Tried reinstalling jackett a few times, but that didn't work. Any help?

**Comment by kaso17** [comment]
I suspect one of your config files got corrupted, please try clearing your config directory.

**Comment by MoinFaraz** [comment]
@kaso17 Where exactly is the config directory? The nearest match I have is 
C:\ProgramData\Jackett is that what you are referring to?
In this directory there are multiple config files. I am not sure how we clear this directory.

**Comment by kaso17** [comment]
C:\ProgramData\Jackett\Indexers contains the indexer config files (If there's an empty file that most likely causes this)
C:\ProgramData\Jackett\ServerConfig.json contains the main server config

You can also try the most recent release, it contains a small fix to prevent crashed due to corrupted indexer config files.

**Comment by MoinFaraz** [comment]
There was no empty file in Indexers folder, but I have cleared it anyway. I have also deleted server.config.json file but that didn't make any difference either. Finally, I have uninstalled Jackett and reinstalling using the new installer. hopefully, I won't experience this issue with the new version.
