### ISSUE TITLE
[yggtorrent] Login failed: No form found - new domain name YggTorrent.ch

### ISSUE THREAD

**Issue by meuestil0** [Jackett/Jackett#5185]
Hi, 

The tracker YggTorrent is no longer available on the domain name yggtorrent.gg. The new is yggtorrent.ch 

Can you investigate please ? 

Error message:  An error occured while testing this indexer
Exception (yggtorrent): Login failed: No form found on https://www2.yggtorrent.ch/ using form selector #user-login: Parse error

Jackett version: 0.11.245.0

**Comment by Gloird** [comment]
Apres de long essais j'ai réussi a faire passer le test avec cette config.

![image](https://user-images.githubusercontent.com/1530313/57192113-2f57b780-6f2d-11e9-94cc-66932f627c82.png)

**Comment by meuestil0** [comment]
J'avais essayé avant de poster mais ça fonctionne pas :(

**Comment by Gloird** [comment]
J'avais tester plusieurs fois et maintenant ça fonctionne

**Comment by ericlaska** [comment]
je confirme, ca marche, rentrer la config ci dessus, le test ne marche pas, fermer la fenetre de config sans sauvegarder, re-ouvrir ,la config et refaire le test, la ca passe ...

**Comment by meuestil0** [comment]
Je confirme, ça fonctionne en appliquant cette méthode.
