### ISSUE TITLE
[FileList] add multi-page processing.

### ISSUE THREAD

**Issue by a-nunes** [Jackett/Jackett#5190]
I've added a serie on Sonarr (New Amsterdam (2018)) and try to find 1080p releases using FileList indexer, but it didn't work. So I made a manual search in Jackett and was able to see that it was just returning SD releases, except for three 720p. After some comparsions I found this:

1) https://imgur.com/a/ABbAnA8

The searchin term is standard set to 1 and the sort is stardand set to 2, looking into FileList.cs, I found that both are set to 0. When I set both to 0, there's 3 results in 720p and all the others, in first page, are SD, exactly like Jackett manual search. 

Jackett is finding just 20 results, it means that it's not jumping to the other pages, just the first one.

Is there some change that can be made to just overwrite the actual configuration and set a new one to correct these issues?

I'm using  Jackett Version 0.11.279.0 and Mono version 5.18.1.3

**Comment by garfield69** [comment]
try out jackett pre-release  v0.11.294

**Comment by a-nunes** [comment]
It now returns it properly, but still get just the first 20 results. It's not jumping to the next pages to get more results. Every search returns just the first 20 results, after this, nothing more is shown. 

Is it possible to solve this?

**Comment by garfield69** [comment]
this indexer is written in native c# and currently processes just the first page.
While I can easily patch/replace values and whatnot, I'm not up to adding multi page processing.
i'll re-queue this ticket as an enhancement, and maybe someone will volunteer to add that feature.

**Comment by ngosang** [comment]
@IIIspaceIII could you help? We don't have an active maintainer for this tracker.

**Comment by IIIspaceIII** [comment]
I will take a look but I am java developer not a C# dev. ;)

**Comment by garfield69** [comment]
Anybody able to send one of the Jackett team an invite?
ngosang -at- hotmail.es 
or
cadatoiva -at- yahoo.com

**Comment by cadatoiva** [comment]
Java is pretty similar to C#, which is Microsoft's intent. If you can make the needed changes, I can help with the formatting and library api calls.

**Comment by RoloSoze** [comment]
> 
> 
> Anybody able to send one of the Jackett team an invite?
> ngosang -at- hotmail.es
> or
> cadatoiva -at- yahoo.com

@garfield69 I can try contacting FileList's staff if you guys want to. There is also another FileList issue here #7004 - I'm not having any issues whatsoever with FL myself but I can still reach out to staff if needed. Let me know.

CC: @cadatoiva @ngosang

**Comment by garfield69** [comment]
Before we go down this multi page path, two things to consider:
- Does the site account profile provide a torrents per page option, is is simply a matter of increasing the default setting?
- is the ste deliberately limiting results to 20 to prevent server overloading, do we really want to double or triple requests per search to get more results in this way if the site is trying to manage workload or keep within budgetary window?

I don't like for jackett to be rude to sites by deliberately trying to circumvent measures a site may have put in place for a reason, so this should be answered before we commit to adding this feature to the indexer.

**Comment by RoloSoze** [comment]
>     * Does the site account profile provide a torrents per page option, is is simply a matter of increasing the default setting?

No, it does not. However, it's worth mentioning that browsing, not searching, torrents on the website returns 50 torrents per page. Searching returns a maximum of 20 results per page via both the website and Jackett. None of this is user-configurable.



>     * is the ste deliberately limiting results to 20 to prevent server overloading?

I'm assuming the answer is yes but I have not checked with the staff myself. 



> so this should be answered before we commit to adding this feature to the indexer.

I got in touch with the staff months ago regarding a different issue, which the fact that long titles are truncated and appended with .... at the end. While FL is not the only tracker that does that, I noticed that they do it more aggressively than others (i.e. their limit is much shorter than others.). Therefore, much of the release details are not shown in the results page, and are only displayed in the torrent's details page. I asked if this can be fixed on their end and they said they're working on a new version for the website in which that issue is fixed. Since a new version is in the works, I think now is a good time to establish contact with the FL staff and discuss any Jackett or API-related matters. I am willing to make the introduction and ask the staff to invite the C# developers if people are willing to work on things.

**Comment by IIIspaceIII** [comment]
@garfield69 
I've added multi-page support and created a pull request.
Tested locally:
![image](https://user-images.githubusercontent.com/2269678/77851084-8585b700-71df-11ea-9d38-f8f691511403.png)

**Comment by RoloSoze** [comment]
@IIIspaceIII Can you perform this search for Game of Thrones? There should be 209 results.

**Comment by RoloSoze** [comment]
#975

**Comment by IIIspaceIII** [comment]
@RoloSoze 
![image](https://user-images.githubusercontent.com/2269678/77852645-6b040b80-71e8-11ea-8435-3cfcce6984c9.png)

**Comment by RoloSoze** [comment]
@IIIspaceIII One search result is omitted, but that's close enough :) Make sure you have a look at #975 - That's when I first raised Jackett's pagination issue, which applies to all configured indexers, but is most obvious in the ones where the number of results per page is very limited, like FileList. 

I imagine @garfield69 would want us to discuss this with FL's staff before implementing it? Generic search terms (with few hundred results) may overload FL's servers.

**Comment by garfield69** [comment]
Jackett 0.16.54
