### ISSUE TITLE
Search public first if nothing found search private?

### ISSUE THREAD

**Issue by JohnyBeGood** [Jackett/Jackett#5194]
As the subject says can Jackett do this? I've tried searching but could not find anything. 
TIA

**Comment by flightlevel** [comment]
Jackett accepts requests from clients (e.g. Sonarr, Radarr etc) and responds back. It would be upto the client to implement that logic, but yes, the client could definitely do that if desired

**Comment by JohnyBeGood** [comment]
Thanks for the reply! IMO it would make sense if Jackett would have ability to make that determination since its already dealing with the torrents.
