### ISSUE TITLE
[Yggtorrent] Search not working with spaces

### ISSUE THREAD

**Issue by Sayroyten** [Jackett/Jackett#5209]
Hi guys, strange behaviour on jacket search for Yggtorrent.ch (only movies), im not sure if the problem is on your side or on Ygg.

If i search 'iron man 3' jacket doesnt find anything, but if i try 'iron+man+3' i get some result.
Just 'iron man' return also a lot of results (including iron man 3 releases)
(just choosing this movie because its recent upload ^^)

**Jackett version**:  0.11.279.0

**Comment by garfield69** [comment]
its YGG. the new search domain posts cloudflare 502 bad gateways intermittently.
The first search I did also returned nothing, but when I repeated it again it returned results.
there is anything that can be done from Jackett's side.
![image](https://user-images.githubusercontent.com/6933240/57266774-9615d600-70d1-11e9-8e53-60b862173527.png)

**Comment by Sayroyten** [comment]
Nope... Ygg is working, otherway every search request will fail and not only those which number in title.
I tried again right now

**Comment by garfield69** [comment]
yes I'm sure.
![image](https://user-images.githubusercontent.com/6933240/57325941-644b5080-715f-11e9-92d0-e1507aeaf227.png)

**Comment by garfield69** [comment]
the only other alternative is that somehow you are not up to date with your version of the yggtorrent indexer.
consider manually installing the latest version to ensure everything is replaced with the latest version.
