### ISSUE TITLE
Jackett trackers timing out in SickChill and CouchPotato

### ISSUE THREAD

**Issue by nydave69** [Jackett/Jackett#5211]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------
This is the only error in the logs for sickchill;
INFO::SEARCHQUEUE-MANUAL-326124 :: [Jackett] :: Request failed: HTTPConnectionPool(host='192.168.10.75', port=9117): Read timed out

seems like jackett is taking a long time to return results. I timed a manual search for a very popular TV show and it took over a one minute and 45 seconds to return results. I've been trying to narrow down which providers that did return results lagged holding up the process. This just started in the last few weeks.

Edit:   after playing around with manual downloads I found that removing the KATcrs and ISOhunt2 trackers, that the search dropped to just under 20 seconds..  from the one minute 45 seconds it took before.  Also that error has now stopped in sickchill,  I've also noticed that CouchPotato has taken off with many more downloads. (didn't see any errors from CouchPotato but I wasn't getting the download like before, now I think I know why)..  Hope his helps anyone seeing the same symptoms.

 edit: after a few days the error keeps returning, seems that different trackers keeps hanging the process because they take too long to respond. I think that a timeout needs to be added so that a tracker that doesn't respond in so many seconds its discarded so what results that has been returned can be passed to the requesting process. Right now all returns are missed because the process is dropped.

**Comment by flightlevel** [comment]
Are you using the `all` aggregate indexer?

**Comment by flightlevel** [comment]
Are you using the `all` aggregate indexer?

**Comment by nydave69** [comment]
I'm using public indexers, as long as they pass testing, but I have to keep dropping them as they fail to return  results quickly, that include some of the most popular. 
Issue is that even the most popular one may fail or delay a search from time to time depending on factors. Because of that failure no results are returned in time, Sickchill shows an error of a timeout and moves on, Couchpotato just assumes no results was returned and moves on. For Sickchill depending on the search being done you could loose a day in getting a new TV show etc... 
I'm thinking that a countdown timer setting that if an indexer(s) exceeds that time it's dropped for that search and results from other indexer be returned, that way you get some results rather then none. If an indexer were dropped a number of times you may want to then keep a count and report that so the indexer could be looked into.

**Comment by nydave69** [comment]
this is still causing issues with both couchpotato and sickchill missing downloads

**Comment by GamerGun** [comment]
I have the same issue with both SickChill and CouchPotato; it's not working with just 1 tracker (1337x) in Jackett on Synology.

**Comment by nydave69** [comment]
Still having the same problems...  with different trackers
removing a slow tracker will fix it, till you run out of trackers, then you start over.

**Comment by ngosang** [comment]
I think we can't solve this in Jackett. Some sites are slow and we can change that.
I recommend you to open issues in SickChill and CouchPotato to increase the request timeout and link with this issue.

**Comment by cadatoiva** [comment]
In your sickchill & couchpotato settings, do you have an entry for each tracker that you have in Jackett or is it just one entry?

**Comment by RoloSoze** [comment]
@nydave69 It would be great if you're able to respond to @cadatoiva! Thanks!

**Comment by RoloSoze** [comment]
@nydave69 I'll close this issue for now. If you are able to respond to @cadatoiva, please feel free to reopen it!
