### ISSUE TITLE
[REQ] efectodoppler .pw [Private / Music / Spanish]

### ISSUE THREAD

**Issue by RicardoVelaC** [Jackett/Jackett#5222]
Add support for efectodoppler .pw

Spanish private tracker for music.

I have invitations, I've sent one to garfieldsixtynine @ gmail.com

Thanks you!!

**Comment by garfield69** [comment]
registration and login successful. thank you.

**Comment by garfield69** [comment]
regarding download volume factors:
I assume **gold** is *freeleech*
but what is **neutral** ?

Also, can you confirm that there no upload volume multipliers?

**Comment by RicardoVelaC** [comment]
Yes, bonus **gold** (Oro) is _freeleech_
**Neutral** multiplier do not count neither what has been downloaded nor what has been uploaded.

**Comment by garfield69** [comment]
try out Jackett v0.11.316

**Comment by garfield69** [comment]
https://efectodoppler.pw/ is returning a empty response (no html or error)
console shows
![image](https://user-images.githubusercontent.com/6933240/142578621-abdc426f-ee18-4076-82f7-2fc8edf188ec.png)
Just me or is the site broke, gone or moved to a new domain?

**Comment by RicardoVelaC** [comment]
I don't know what happen, few days ago they go to blank page.
Maybe they come back soon

**Comment by ilike2burnthing** [comment]
```none
Trying to get back
```

**Comment by ilike2burnthing** [comment]
https://efectodoppler.pw/ - native login prompt (pressumably not for users)
https://efectodoppler.pw/login.php - Memcache Extension not loaded

**Comment by ilike2burnthing** [comment]
[v0.20.184](https://github.com/Jackett/Jackett/releases/tag/v0.20.184)
