### ISSUE TITLE
RPI New Install Without MONO

### ISSUE THREAD

**Issue by truedevil** [Jackett/Jackett#5223]
hi all,

Ive had my RPI working pretty well for the past year with no issues but now suddenly Jackett stopped working. 

I saw an update saying that it no longer requires mono and that I can install it and it will work.

Using my limited linux knowledge I folled the HTPC guide again to install Jackett over my current install and the whole thing broke. I can no longer log onto or start jackett and im lost as i cant find any guides out there that take you through on how to install jackett without mono on a rpi.

I would really appreciate any help you can give

**Comment by garfield69** [comment]
I believe that RPI runs ARM processors so try following https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above and see how you go.
