### ISSUE TITLE
Access Jackett on Windows Though Sonarr On RPI?

### ISSUE THREAD

**Issue by truedevil** [Jackett/Jackett#5224]
Hi,

As the title says, Is there a way to access Jackett that is installed on a windows PC through sonarr installed on a RPI?

I read somewhere online that this might be possible but I cant find any guides to this.

I have installed jackett on windows and tried to copy the link and past it into sonarr and use the api key but when I test it just failes instantly. I have added the port to my windows firewall for incoming and ticked allows external access on the gui but still no luck.

Any ideas?

**Comment by flightlevel** [comment]
Its definitely possible.
Ensure allow external access is ticked on the Jackett dashboard. Can you hit other web services on the Windows machine from the Pi?
