### ISSUE TITLE
AHD search populates in Jackett, but RSS  feed gives error

### ISSUE THREAD

**Issue by boardwarp** [Jackett/Jackett#5225]
I've only just got started with Jackett, this feels like more of a basic support request than an bug/issue but I couldn't find any other support channels or existing Git issues with the same problem.

In short, after setting up the Awesome-HD tracker, the RSS feed URL gives an error:

```
<error code="900" description="System.ArgumentNullException: Value cannot be null. Parameter name: value at System.Xml.Linq.XAttribute..ctor(XName name, Object value) at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 63 at System.Linq.Enumerable.SelectListIterator`2.MoveNext() at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content) at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content) at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 39 at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 417"/>
```

Using the **[LinuxServer.io Jackett Docker Image](https://hub.docker.com/r/linuxserver/jackett/)**
**Running latest Jackett (0.11.295)**
**Accessing AHD by Web Works**: Can access Awesome-HD.me just fine by browser, no apparent account issues there 
**Manual Search Works**: When running a search on the AHD feed within the Jackett UI, search results are returned as expected. I think this rules out most cookie/auth/tracker related issues.
**Other Trackers Work**: TorrentLeech and BroadcastTheNet have both been configured in the same way as AHD, and their RSS feeds work as expected.

After enabling enhanced logging, restarting the container and attempting to access the RSS URL, this log is produced: **[log.txt]()**

(At the bottom of your Jackett Dashboard page) **Jackett version**:  Jackett Version 0.11.295.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**: N/A

-------------------------------

**Comment by flightlevel** [comment]
If you only everyone created issues so nicely! Its a parsing issue @garfield69 might be able to have a look

**Comment by garfield69** [comment]
unfortunately I don't have a login for this site. Anyone have an invite?
if not, then it may be more useful to have an enhanced log, as apparently the log provided is just a regular one.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by draggy** [comment]
@garfield69 This is still happening in v0.12.1063.0
I opened the rss feed for AHD in my browser and these are the jackett logs
[log.txt](https://github.com/Jackett/Jackett/files/3917523/log.txt)

**Comment by garfield69** [comment]
it looks like the indexer is not able to match the title selector because the rows it is looking for do not include any.
unfortunately, with there being so much output from the row mismatching debug entries, I cannot see the first post of the full html that would preceded all these errors in the log you provided.
could you please do the following:
repeat your enhanced log test, and this time post all the log.txt* files. 
with a bit of luck one of them will have the full search result html.

The better option would be if you could provide an invite so I can test and debug independently. 
Coding solutions without being able to test them makes it difficult to get a working fix published first time.

**Comment by draggy** [comment]
@garfield69 I sent you one, let me know if you need anything from me.

**Comment by garfield69** [comment]
registration and login successful. thank you.

**Comment by garfield69** [comment]
bugger. I should have looked back at the history. :-(

the awsome-hd cardigann indexer was provided by a volunteer in May 2017 #1352 knowing full well the implementation was not a good one, but a better than nothing attempt at the time.
it works more or less if you are using the dashboard search, but not for RSS and Sonarr (or related apps) usage.

the site uses a group header row for movies followed by one or more torrent rows for each related download, and the tv rows have their own layout.
there is not way that the cardigann indexer can handle this site.

Only an indexer written in C# can process this site properly.
there are already several tickets open for this #1943 #1481

I am not a C# developer so I am unable to help with this one.
We will just have to wait for a C# volunteer to code a solution.

**Comment by ngosang** [comment]
@garfield69 we have other trackers with the same software working in c#? If isn't too much work I can request an invite an do the code.

**Comment by garfield69** [comment]
>[do] we have other trackers with the same software working in c#?

At first I thought that AHD might have been a close match for the GazelleTracker abstract, similar to AlphaRatio, but AHD does not appear to support the /ajax.php?action=browse, so that is a bust.

Probably the closest match, with similar login, search path and row selectors might be TVVault, which might provide you with a starting point. 
But I suspect AHD is a customised unicorn.

**Comment by RoloSoze** [comment]
@ngosang

**Comment by garfield69** [comment]
Jackett 0.14.326
