### ISSUE TITLE
Jackett can't find a suitable release

### ISSUE THREAD

**Issue by SuberSeb** [Jackett/Jackett#5229]
I have a problem with a few of TV shows. For example, I have S.W.A.T. series added to Sonarr. Seems like that Sonarr or Jackett removes dots symbols from TV show name and it searches by name SWAT instead S.W.A.T. As a result Sonarr can't find any releases. It happens with all TV shows which has dots in their name, for example Chicago P.D.
Also I have "Unknown series" error when TV show name has a year in their title.
All other TV shows with normal names (without symbols or year) works perfectly.

I'm using Sonarr with Jackett on my XPEnology NAS (both installed from SynoCommunity), torrent tracker is Rutracker.

**Comment by flightlevel** [comment]
Turn debug logging on in Sonarr and perform a search, then provide the log so that we can what url parameters its sending to Jackett
