### ISSUE TITLE
[hush] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#5230]
Can't use Hush tracker. Config failed.
Jackett version : 0.11.296.0
Windows 10 OS

**Comment by garfield69** [comment]
have you tried again recently? Still not working?
then

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by pipopop** [comment]
It works great right now. I close the issue.
