### ISSUE TITLE
qnap TS251 - Error starting jackett with update without mono

### ISSUE THREAD

**Issue by ade05fr** [Jackett/Jackett#5231]
With  alpha version of Jackett i update the qpkg for my qnap ts-251 to make it start without mono but when i launch it, i received this message.

<code> 

[/share/CACHEDEV1_DATA/.qpkg/Jackett] # ./Jackett.sh  start
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)
./Jackett.sh: line 25: 18303 Aborted                 ./jackett
</code>

I check the qnap forum and try the arm version (which is not good since its based on x86 architecture) and i received another error :

<code> 
/share/CACHEDEV1_DATA/.qpkg/Jackett] # ./Jackett.sh start
+ /bin/ln -sf /share/CACHEDEV1_DATA/.qpkg/Jackett /opt/Jackett
ln: /opt/Jackett/Jackett: File exists
+ cd /share/CACHEDEV1_DATA/.qpkg/Jackett/Jackett
+ ./jackett
./Jackett.sh: line 37: ./jackett: cannot execute binary file
+ echo
+ sleep 15
</code>

what is the issue there ?
 Jackett Version 0.11.308.0 : Jackett.Binaries.LinuxAMDx64.tar.gz

-------------------------------

**Comment by flightlevel** [comment]
Don't use the ARM version, that will never work on an Intel

For the AMDx64 version, options are:
-Install the ICU package, this is normally present on Linux (on Ubuntu you'd install by running `apt-get install libicu60` not sure how you do that on a QNAP)
-Use environment variable `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true`

**Comment by ade05fr** [comment]
on qnap there is no ICU library installed by default. i use the environment variable 
<code>
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
</code>
as you mention in my Jackett.sh script like this

<code>
[/share/CACHEDEV1_DATA/.qpkg/Jackett] # cat Jackett.sh 
#!/bin/sh
CONF=/etc/config/qpkg.conf
QPKG_NAME="Jackett"
QPKG_ROOT=`/sbin/getcfg $QPKG_NAME Install_Path -f ${CONF}`
export QNAP_QPKG=$QPKG_NAME
export QPKG_ROOT
export QPKG_NAME
export SHELL=/bin/sh
export LC_ALL=en_US.UTF-8
export USER=admin
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export TERM=xterm
export HOME=$QPKG_ROOT
export DIR=$QPKG_ROOT
export DESC=Jackett
export PIDF=/var/run/jackett.pid
case "$1" in
  start)
    ENABLED=$(/sbin/getcfg $QPKG_NAME Enable -u -d FALSE -f $CONF)
    if [ "$ENABLED" != "TRUE" ]; then
        echo "$QPKG_NAME is disabled."
        exit 1
    fi
/bin/ln -sf $QPKG_ROOT /opt/$QPKG_NAME
cd $QPKG_ROOT/Jackett
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
./jackett
echo $! > $PIDF
sleep 15
    ;;
  stop)
ID=$(more /var/run/jackett.pid)
        if [ -e $PIDF ]; then
            kill -9 $ID
            rm -f $PIDF
        fi
rm -rf /opt/$QPKG_NAME
   ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0
[/share/CACHEDEV1_DATA/.qpkg/Jackett] # 
</code>

and it works fine.
thanks a lot

**Comment by M0CRT** [comment]
Just updated to the new version with my unraid docker.  Yes, in the .sh script /home/nobody (console into the docker).

Add Export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true before the command to run.  Works a treat.  Nice one ade.
