### ISSUE TITLE
[mejortorrent] Sequence contains no elements (Config)

### ISSUE THREAD

**Issue by kesp91** [Jackett/Jackett#5235]
Previous issue #4880 occurring again however methods in that post to fix no longer work.  Using Jackett Version 0.11.279.0 with unraid in a docker. 

An error occurred while configuring this indexer
Sequence contains no elements

Thank you.

**Comment by garfield69** [comment]
working for me.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by kesp91** [comment]
See attached specifically the error

[log.txt](https://github.com/Jackett/Jackett/files/3167585/log.txt)

**Comment by garfield69** [comment]
is there no related debug statements prior to the stack trace?

**Comment by kesp91** [comment]
Attached are 2 more log files unsure which one to use[

Log-1.txt](https://github.com/Jackett/Jackett/files/3169237/Log-1.txt)
[Supervised log-1.txt](https://github.com/Jackett/Jackett/files/3169238/Supervised.log-1.txt)

**Comment by garfield69** [comment]
ok lets try this:
1. start a terminal and connect to your jackett docker `docker exec -it jackett /bin/bash` (replace jackett with whatever you called your Jackett container).
2. then post the output of `curl -vvv http://www.mejortorrent.tv/`

**Comment by garfield69** [comment]
mejortorrent on new domain. try jackett v0.11.338

**Comment by kesp91** [comment]
What is the new domain? Docker has not been updated yet.

**Comment by kesp91** [comment]
![IMG_0023](https://user-images.githubusercontent.com/30266747/57857861-fbe31b80-77bd-11e9-9c7d-59d92a399ee1.JPG)

**Comment by garfield69** [comment]
http://www.mejortorrentt.com/

**Comment by kesp91** [comment]
Can this issue be reopened the problem is not fixed and I even downloaded a new docker and had issues connecting to mejortorrentt.com with the updated version

**Comment by garfield69** [comment]
works for me.

1. start a terminal and connect to your jackett docker `docker exec -it jackett /bin/bash` (replace jackett with whatever you called your Jackett container).
2. then post the output of `curl -vvv http://www.mejortorrentt.com/`

**Comment by kesp91** [comment]
[Log3.txt](https://github.com/Jackett/Jackett/files/3197865/Log3.txt)

**Comment by garfield69** [comment]
so access your jackett dashboard, scroll to the bottom and report the jackett version number.
then edit your mejortorrent config and report what the site link is set to. 
thanks.

**Comment by kesp91** [comment]
Version 0.11.355.0. Where is the config file?

Does the proxy/vpn need to be set to a specific region for Jackett to work with mejortorrent? 1 other indexer won’t work with out a proxy (yts).

**Comment by garfield69** [comment]
>Where is the config file?

the **config** I was referring to is the mejortorrent indexer config you edit on your dashboard with the **wrench** icon ;-)

>Does the proxy/vpn need to be set to a specific region for Jackett to work with mejortorrent?

You did not mention vpn/proxy before. this adds another wrinkle to the problem solving.
But I have no idea about this. I think it unlikely.

All I know is that on my win10 jackett 0.11.356 I can access mejortorrent.
I don't use a vpn or proxy, but I do have to turn off my AVAST Web-shield blocks access, as it claims the site has a suspect iframe in the html ( says its infected with HTML:iframe-inf[Susp] ).
But I cant see that happening with you as your curl -vvv got through without problems.

@kaso17  @flightlevel  any insights on what might be happening here?

**Comment by kesp91** [comment]
Since this issues shows as closed, could that be the reason they have not responded? Also the config was the same url as you listed before.

I tried a fresh install of Jackett and updated it, only added mejor as the only indexer and it worked for a short period of time before the error started (in Jackett) after I added it to Radarr.  Removing the indexer from Radarr did not resolve the problem.

**Comment by garfield69** [comment]
nope, the ticket being closed does not prevent the notices going out to the devs I pinged. They are obviously unavailable at the moment.  I noticed kaso17 has been away for at least a month now, and flightlevel is similarly indisposed.

**Comment by garfield69** [comment]
mejortorrent appearsto be problematic. there are a fe open tickets for this indexer.
if you are finding that mejortorrent works for a bit then stops working, that sounds a bit like some one of the other tickets for mejortorrent that are currently open.
#3869  #4279
