### ISSUE TITLE
Jackett Version 0.11.310.0 wont install service

### ISSUE THREAD

**Issue by BluePhire94** [Jackett/Jackett#5238]
sudo  ./install_service_systemd.sh
Synchronizing state of jackett.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable jackett
ERROR: Could not launch service. The installation might have failed.
Please open an issue on https://github.com/Jackett/Jackett/issues and paste following information:
Mono directory: ``
Jackett directory: `/opt/Jackett`
Jackett user: `UNKNOWN`

**Comment by sagem2000** [comment]
Try this:
change the owner of the now downloaded jackett directory using 'chown -R nonrootuser jackettdirectory'

You can create a new user called jackett or use an existing owner as the user does not have root access.

**Comment by TrentKnight** [comment]
I had the same issue and this fixed it

**Comment by flightlevel** [comment]
@BluePhire94 did the above fix your issue?
