### ISSUE TITLE
Scenetime not working

### ISSUE THREAD

**Issue by normanu** [Jackett/Jackett#524]
Scenetime has a Captcha on the login page.
So adding it gives back that you don't pass the human test.
Anyway around it?

**Comment by SJPadbury** [comment]
I'm also seeing the same issue.

**Comment by kaso17** [comment]
If you can sent an invite to kaso1717 -at- gmail.com I can add support for the new captcha.

**Comment by trentchristopher** [comment]
kaso17, I would really appriciate if you could add the captcha support. Let me know if you still need an invite.

**Comment by kaso17** [comment]
yes, still need an invite
