### ISSUE TITLE
[REQ] WorldofP2P tracker

### ISSUE THREAD

**Issue by staraxis** [Jackett/Jackett#525]
Please add support for 
- WorldofP2P
- UHDBits

They're both currently open for signup

Thanks

**Comment by d2dyno** [comment]
UHDBits already requested: #221

**Comment by staraxis** [comment]
No worries. Thanks and my apologies for not looking closer to see if it had already been requested.

Also do you now when the next release will be available? I see the code has been updated

**Comment by d2dyno** [comment]
I am not sure when the next release will be, I am not a developer on the project (I just help when I can). The developers contribute the time when they can, but are not always constently active in pushing the releases.

**Comment by staraxis** [comment]
I understand, I am more than happy with the service and quality, just inquiring. Thanks!

**Comment by kaso17** [comment]
I'll add them next week

**Comment by staraxis** [comment]
Much appreciated, thanks.

**Comment by garfield69** [comment]
currently https://worldofp2p.net/ is returning ERR_CONNECTION_REFUSED.
Broken, gone or moved to a new domain?
