### ISSUE TITLE
Failed download cookies cfuid

### ISSUE THREAD

**Issue by yoobi** [Jackett/Jackett#5250]
Hello,

I've added Torrent9 as indexer, the search and test from UI are working properly but whenever I try to download a torrent, I get a 404, below logs from Jackett 

![Sans titre 1344](https://user-images.githubusercontent.com/17434735/57575026-12e2e000-7443-11e9-9d8e-24dacca89056.jpg)

Jackett Version 0.11.316.0 
Mono v 5.18.0.240-12 (On my Synology)

If you need more information, ask away :)

-------------------------------

**Comment by garfield69** [comment]
should be resolved with jackett 0.11.325
