### ISSUE TITLE
[showrss] Parse error: The 'link' start tag on line 9 position 2 does not match the end tag of 'head'. Line 44, position 3. (Config)

### ISSUE THREAD

**Issue by therimmer96** [Jackett/Jackett#5252]
Getting this error when after updating my Docker instance using this as the site link https://showrss.info/other/all.rss/
It was working prior to the update

(At the bottom of your Jackett Dashboard page) **0.11.325.0**:  

-------------------------------

**Comment by garfield69** [comment]
works for me.
ok lets try this:
1. start a terminal and connect to your jackett docker `docker exec -it jackett /bin/bash` (replace jackett with whatever you called your Jackett container).
2. then post the output of `curl -vvv https://showrss.info/other/all.rss/`

**Comment by therimmer96** [comment]
Here you go.
[Jackett ShowRSS.txt](https://github.com/Jackett/Jackett/files/3169594/Jackett.ShowRSS.txt)

Additionally, I spotted this in my logs and I believe it's actually the cause rather than an issue with the incoming RSS.
[Jackett ShowRSS 2.txt](https://github.com/Jackett/Jackett/files/3169595/Jackett.ShowRSS.2.txt)

**Comment by garfield69** [comment]
edit your  jackett showrss config and set your site link to `https://showrss.info/`.
the indexer adds `other/all.rss` to its search string so you don't need it on the site link.

**Comment by therimmer96** [comment]
No change.

It was working perfectly before this, sonarr was showing results from ShowRSS with it set with the RSS link added in.

**Comment by therimmer96** [comment]
http://puu.sh/Dr33i/64013706d7.png

**Comment by garfield69** [comment]
its `https://showrss.info/` with a `/` at the end

**Comment by therimmer96** [comment]
Tried that before removing the trailing `/`
http://puu.sh/Dr381/259ea963af.png

**Comment by garfield69** [comment]
the `page not found` that you have in Jackett ShowRSS 2.txt shows that showrss is responding to you using an url of `https://showrss.info/other/all.rss/other/all.rss` which is what you would get if you are using a site link of `https://showrss.info/other/all.rss/` on your jackett indexer.

while previously showrss might have ignored the extraneous stuff on the url it is now not allowing it.
see the browser direct result of using your original site link below:
![image](https://user-images.githubusercontent.com/6933240/57576594-668f1100-74b7-11e9-8024-3b3ff90dae97.png)
nothing to do with jackett.

turn on enhanced logging in jackett and see if you can capture the url and html being used by your current indexer config.
