### ISSUE TITLE
[tntvillage] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by bin83** [Jackett/Jackett#5255]
Hi,
I receive this error 
Found no results while trying to browse this tracker
and the problem I think is the path that contains /src/

Here the log:

May 12, 2019 03:26:50 PM | Debug | WebClient(HttpWebClient): Returning Forbidden => <html> <head><title>403 Forbidden</title></head> <body bgcolor="white"> <center><h1>403 Forbidden</h1></center> <hr><center>nginx</center> </body> </html>
-- | -- | --
May 12, 2019 03:26:50 PM | Debug | WebClient(HttpWebClient).GetString(Url:http://tntvillage.scambioetico.org/src/releaselist.php)

Thanks

**Comment by garfield69** [comment]
most likely your jackett is not up to date. 
upgrade to  v0.11.327 and you should not have any problem.

**Comment by bin83** [comment]
Hi,
I've update my Jackett and now it work.

Thanks,
Vincenzo

Il lun 13 mag 2019, 09:11 garfield69 <notifications@github.com> ha scritto:
