### ISSUE TITLE
[Feature request] Is it possible to use jackett for non-torrent links?

### ISSUE THREAD

**Issue by vkadam** [Jackett/Jackett#5258]
Wanted to see if we can make jackett work to use search feature of non-torrent site like filepursuit.com and get it working with sonarr & radarr.
Thoughts?

**Comment by ngosang** [comment]
As far as I know Sonarr only supports Torrent and Usenet. And for Usenet you don't need aggregators...
I'm closing this, we are focus only on torrents .
