### ISSUE TITLE
IPTorrents searches return incorrect results

### ISSUE THREAD

**Issue by chalur** [Jackett/Jackett#526]
So I've been having an issue with Sonarr where the search results for TV shows are totally unrelated to the episode being searched for. I've spent some time looking over the logs, and it looks like Jackett isn't handling the search properly. 

This is an example request coming into Jackett
`http://serverip:9117/torznab/iptorrents/api?t=tvsearch&cat=5030,5040&extended=1&apikey=apikey&offset=0&limit=100&rid=38796&season=2&ep=13`
As you can see, it's passing in the show ID, the season number, and the episode number. However, when Jackett actually performs the search, it's doing this search
 `https://iptorrents.com/t?q=S02E13&26=&55=&78=&24=&25=&66=&82=&79=&4=&23=&22=&5=`
This search returns all of the most recent torrents uploaded that include S02E13, but it does not actually include the show name anywhere in the search. If I perform a manual search through the Jackett console, it works fine and gives me the correct results. 

I've been having this issue on every show I've tried. I don't know why this is happening, so if anyone does please let me know.

**Comment by flightlevel** [comment]
What version of Jackett and what version of Sonarr?

What to you get from http://serverip:9117/torznab/iptorrents/api?t=caps&apikey=YOURAPIKEY

response should look like

```
<?xml version="1.0" encoding="UTF-8"?>
<caps>
  <searching>
    <search available="yes" supportedParams="q" />
    <tv-search available="yes" supportedParams="q,season,ep" />
  </searching>
  <categories>
    <category id="2000" name="Movies">
      <subcat id="2010" name="Movies/Foreign" />
      <subcat id="2020" name="Movies/Other" />
      <subcat id="2030" name="Movies/SD" />
      <subcat id="2040" name="Movies/HD" />
      <subcat id="2050" name="Movies/3D" />
      <subcat id="2060" name="Movies/BluRay" />
      <subcat id="2070" name="Movies/DVD" />
      <subcat id="2080" name="Movies/WEBDL" />
    </category>
    <category id="2030" name="Movies/SD" />
    <category id="2040" name="Movies/HD" />
    <category id="2010" name="Movies/Foreign" />
    <category id="5000" name="TV">
      <subcat id="5010" name="TV/WEB-DL" />
      <subcat id="5020" name="TV/FOREIGN" />
      <subcat id="5030" name="TV/SD" />
      <subcat id="5040" name="TV/HD" />
      <subcat id="5050" name="TV/OTHER" />
      <subcat id="5060" name="TV/Sport" />
      <subcat id="5070" name="TV/Anime" />
      <subcat id="5080" name="TV/Documentary" />
    </category>
    <category id="5030" name="TV/SD" />
    <category id="5040" name="TV/HD" />
    <category id="3000" name="Audio">
      <subcat id="3010" name="Audio/MP3" />
      <subcat id="3020" name="Audio/Video" />
      <subcat id="3030" name="Audio/Audiobook" />
      <subcat id="3040" name="Audio/Lossless" />
      <subcat id="3050" name="Audio/Other" />
      <subcat id="3060" name="Audio/Foreign" />
    </category>
    <category id="3040" name="Audio/Lossless" />
    <category id="5070" name="TV/Anime" />
    <category id="4000" name="PC">
      <subcat id="4010" name="PC/0day" />
      <subcat id="4020" name="PC/ISO" />
      <subcat id="4030" name="PC/Mac" />
      <subcat id="4040" name="PC/Phone-Other" />
      <subcat id="4050" name="PC/Games" />
      <subcat id="4060" name="PC/Phone-IOS" />
      <subcat id="4070" name="PC/Phone-Android" />
    </category>
    <category id="3030" name="Audio/Audiobook" />
    <category id="8000" name="Books">
      <subcat id="8010" name="Books/Ebook" />
      <subcat id="8020" name="Books/Comics" />
      <subcat id="8030" name="Books/Magazines" />
      <subcat id="8040" name="Books/Technical" />
      <subcat id="8050" name="Books/Other" />
      <subcat id="8060" name="Books/Foreign" />
    </category>
    <category id="8020" name="Books/Comics" />
  </categories>
</caps>
```

**Comment by chalur** [comment]
Jackett Version 0.7.411.0
Sonarr Version 2.0.0.4326

`<?xml version="1.0" encoding="UTF-8"?>
<caps>
  <searching>
    <search available="yes" supportedParams="q" />
    <tv-search available="yes" supportedParams="q,season,ep" />
  </searching>
  <categories>
    <category id="2000" name="Movies">
      <subcat id="2010" name="Movies/Foreign" />
      <subcat id="2020" name="Movies/Other" />
      <subcat id="2030" name="Movies/SD" />
      <subcat id="2040" name="Movies/HD" />
      <subcat id="2050" name="Movies/3D" />
      <subcat id="2060" name="Movies/BluRay" />
      <subcat id="2070" name="Movies/DVD" />
      <subcat id="2080" name="Movies/WEBDL" />
    </category>
    <category id="2030" name="Movies/SD" />
    <category id="2040" name="Movies/HD" />
    <category id="2010" name="Movies/Foreign" />
    <category id="5000" name="TV">
      <subcat id="5010" name="TV/WEB-DL" />
      <subcat id="5020" name="TV/FOREIGN" />
      <subcat id="5030" name="TV/SD" />
      <subcat id="5040" name="TV/HD" />
      <subcat id="5050" name="TV/OTHER" />
      <subcat id="5060" name="TV/Sport" />
      <subcat id="5070" name="TV/Anime" />
      <subcat id="5080" name="TV/Documentary" />
    </category>
    <category id="5030" name="TV/SD" />
    <category id="5040" name="TV/HD" />
    <category id="3000" name="Audio">
      <subcat id="3010" name="Audio/MP3" />
      <subcat id="3020" name="Audio/Video" />
      <subcat id="3030" name="Audio/Audiobook" />
      <subcat id="3040" name="Audio/Lossless" />
      <subcat id="3050" name="Audio/Other" />
      <subcat id="3060" name="Audio/Foreign" />
    </category>
    <category id="3040" name="Audio/Lossless" />
    <category id="5070" name="TV/Anime" />
    <category id="4000" name="PC">
      <subcat id="4010" name="PC/0day" />
      <subcat id="4020" name="PC/ISO" />
      <subcat id="4030" name="PC/Mac" />
      <subcat id="4040" name="PC/Phone-Other" />
      <subcat id="4050" name="PC/Games" />
      <subcat id="4060" name="PC/Phone-IOS" />
      <subcat id="4070" name="PC/Phone-Android" />
    </category>
    <category id="3030" name="Audio/Audiobook" />
    <category id="8000" name="Books">
      <subcat id="8010" name="Books/Ebook" />
      <subcat id="8020" name="Books/Comics" />
      <subcat id="8030" name="Books/Magazines" />
      <subcat id="8040" name="Books/Technical" />
      <subcat id="8050" name="Books/Other" />
      <subcat id="8060" name="Books/Foreign" />
    </category>
    <category id="8020" name="Books/Comics" />
  </categories>
</caps>`

**Comment by kaso17** [comment]
you client uses rid to specify the show which isn't supported by jackett/iptorrents indexer (see supported params in the caps list).
Your client is broken.

**Comment by matteraByte** [comment]
I'm running into this issue with Bit-HDTV and TorrentLeech as well.
 How do I fix this?

**Comment by flightlevel** [comment]
If this is still a problem, please create an issue at Sonarr
TVRage is long dead and the caps clearly don't offer rid as a search option `<tv-search available="yes" supportedParams="q,season,ep" />` only `q,season,ep`, so Sonarr shouldn't be attempting to search via rid
