### ISSUE TITLE
auto upgrade from 0.11.256 to 0.11.325 continually fails

### ISSUE THREAD

**Issue by rrrevin** [Jackett/Jackett#5260]
Using jackett core version (not mono).
Auto-upgrade continually failing. Logs below. Sometimes the undefined symbol error appears, most times it does not. Upgrade fails and version 0.11.256 just starts up again.
_Nothing has changed on my system._

_Update: Looks like any version higher then 0.11.256 has been failing to autoupgrade._
```
May 12 17:44:42 npi jackett[10590]: 05-12 17:44:42 Info Jackett variant: CoreLinuxArm64
May 12 17:44:44 npi jackett[10590]: 05-12 17:44:44 Info New release found.  Current: v0.11.256 New: v0.11.325
May 12 17:45:27 npi jackett[10590]: 05-12 17:45:27 Info Starting updater: /tmp/JackettUpdate-v0.11.325-636932798948507993/Jackett/JackettUpdater --Path "/opt/Jackett" --Type "Conso
le" --Args " " --KillPids "10590"
May 12 17:45:27 npi jackett[10590]: 05-12 17:45:27 Info Updater started process id: 13039
May 12 17:45:27 npi jackett[10590]: 05-12 17:45:27 Info Exiting Jackett..
May 12 17:45:27 npi jackett[10590]: Application is shutting down...
May 12 17:45:28 npi jackett[10590]: Cannot get symbol ucal_getAttribute_55 from libicui18n
May 12 17:45:28 npi jackett[10590]: Error: /tmp/JackettUpdate-v0.11.325-636932798948507993/Jackett/System.Globalization.Native.so: undefined symbol: ucal_getAttribute_55
May 12 17:45:33 npi systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
```

```
May 12 17:55:48 npi jackett[13048]: 05-12 17:55:48 Info Jackett variant: CoreLinuxArm64
May 12 17:55:49 npi jackett[13048]: 05-12 17:55:49 Info New release found.  Current: v0.11.256 New: v0.11.325
May 12 17:56:28 npi jackett[13048]: 05-12 17:56:28 Info Starting updater: /tmp/JackettUpdate-v0.11.325-636932805609717486/Jackett/JackettUpdater --Path "/opt/Jackett" --Type "Console" --Args " " --KillPids "13048"
May 12 17:56:28 npi jackett[13048]: 05-12 17:56:28 Info Updater started process id: 13482
May 12 17:56:28 npi jackett[13048]: 05-12 17:56:28 Info Exiting Jackett..
May 12 17:56:28 npi jackett[13048]: Application is shutting down...
May 12 17:56:34 npi systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
May 12 17:56:34 npi systemd[1]: Stopped Jackett Daemon.
May 12 17:56:34 npi systemd[1]: Started Jackett Daemon.
May 12 17:56:39 npi jackett[13493]: 05-12 17:56:39 Info Starting Jackett v0.11.256.0
May 12 17:56:48 npi jackett[13493]: 05-12 17:56:48 Info Environment version: 4.0.30319.42000 (/opt/Jackett/)
May 12 17:56:48 npi jackett[13493]: 05-12 17:56:48 Info OS version: Unix 4.14.52.0 (64bit OS) (64bit process)
May 12 17:56:48 npi jackett[13493]: 05-12 17:56:48 Info Jackett variant: CoreLinuxArm64
May 12 17:56:48 npi jackett[13493]: 05-12 17:56:48 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
May 12 17:56:48 npi jackett[13493]: 05-12 17:56:48 Info App config/log directory: /home/qbt/.config/Jackett
May 12 17:56:48 npi jackett[13493]: 05-12 17:56:48 Info issue: Ubuntu 16.04.6 LTS \n \l
May 12 17:56:48 npi jackett[13493]: 05-12 17:56:48 Info Using HTTP Client: HttpWebClientNetCore
```

**Comment by rrrevin** [comment]
Other errors:
`
May 10 08:26:12 npi jackett[7858]: 05-10 08:26:12 Info Jackett variant: CoreLinuxArm64
May 10 08:26:13 npi jackett[7858]: 05-10 08:26:13 Info New release found.  Current: v0.11.256 New: v0.11.316
May 10 08:26:55 npi jackett[7858]: 05-10 08:26:55 Info Starting updater: /tmp/JackettUpdate-v0.11.316-636930735875989532/Jackett/JackettUpdater --Path "/opt/Jackett" --Type "Console" --Args " " --KillPids
 "7858"
May 10 08:26:55 npi jackett[7858]: 05-10 08:26:55 Info Updater started process id: 26374
May 10 08:26:55 npi jackett[7858]: 05-10 08:26:55 Info Exiting Jackett..
May 10 08:26:56 npi jackett[7858]: Application is shutting down...
May 10 08:26:56 npi jackett[7858]: Cannot get symbol udatpg_getBestPattern_55 from libicui18n
May 10 08:26:56 npi jackett[7858]: Error: /tmp/JackettUpdate-v0.11.316-636930735875989532/Jackett/System.Globalization.Native.so: undefined symbol: udatpg_getBestPattern_55
May 10 08:27:02 npi systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
May 10 08:27:06 npi jackett[26384]: 05-10 08:27:06 Info Starting Jackett v0.11.256.0
May 10 08:27:16 npi jackett[26384]: 05-10 08:27:16 Info Environment version: 4.0.30319.42000 (/opt/Jackett/)
May 10 08:27:16 npi jackett[26384]: 05-10 08:27:16 Info OS version: Unix 4.14.52.0 (64bit OS) (64bit process)
May 10 08:27:16 npi jackett[26384]: 05-10 08:27:16 Info Jackett variant: CoreLinuxArm64
May 10 08:27:16 npi jackett[26384]: 05-10 08:27:16 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
May 10 08:27:16 npi jackett[26384]: 05-10 08:27:16 Info App config/log directory: /home/qbt/.config/Jackett
May 10 08:27:16 npi jackett[26384]: 05-10 08:27:16 Info issue: Ubuntu 16.04.6 LTS \n \l
May 10 08:27:16 npi jackett[26384]: 05-10 08:27:16 Info Using HTTP Client: HttpWebClientNetCore
`

**Comment by rrrevin** [comment]
Note : a manual upgrade to v0.11.325.0 works.
No undefined symbol errors at all.

**Comment by garfield69** [comment]
let's see if the next auto-update breaks your setup. i've just published 327.

**Comment by rrrevin** [comment]
Errored out on the auto update:

```
May 13 18:25:24 npi jackett[16126]: Cannot get symbol u_getVersion_55 from libicuuc
May 13 18:25:24 npi jackett[16126]: Error: /tmp/JackettUpdate-v0.11.327-636933686945209398/Jackett/System.Globalization.Native.so: undefined symbol: u_getVersion_55
```

**Comment by garfield69** [comment]
@flightlevel  what do you make of this peculiar issue?

**Comment by rrrevin** [comment]
My libicuuc is under /usr/lib/aarch64-linux-gnu/, which is defined in /etc/ld.so.conf.d/aarch64-linux-gnu.conf.

```
[2058 root aarch64-linux-gnu]$ ls -l /usr/lib/aarch64-linux-gnu/libicuuc*
lrwxrwxrwx 1 root root      16 Mar 27  2018 /usr/lib/aarch64-linux-gnu/libicuuc.so.55 -> libicuuc.so.55.1
-rw-r--r-- 1 root root 1611832 Mar 27  2018 /usr/lib/aarch64-linux-gnu/libicuuc.so.55.1
```
And it does indeed contain the u_getVersion_55 symbol

```
[2061 root aarch64-linux-gnu]$ nm -D --defined-only /usr/lib/aarch64-linux-gnu/libicuuc.so.55.1 | grep u_getVersion
0000000000059308 T u_getVersion_55
```

Is there a way to get a "debug" version of the auto-updater script?

**Comment by flightlevel** [comment]
Weird

Are you creating your own systemd script? There should be a `NoRestart` flag present https://github.com/Jackett/Jackett/blob/master/install_service_systemd.sh#L49

What OS? and double check you have all the needed dependencies https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#linux-distribution-dependencies

**Comment by rrrevin** [comment]
You are correct. The "--NoRestart" option was missing from the systemd startup. I added it, did a systemctl deamon-reload, then service jackett restart. Once restarted, I did a check for updates, which used to fail. Now it works. Fingers crossed it remains this way.

What does the "--NoRestart" actually do, and why when not present, would it cause this error?

**Comment by garfield69** [comment]
the NoRestart tells systemd not to restart the service in the event it is shutdown. 
this is needed because during the update cycle the updater kills the service so that it can replace components.
the updater issues its own startup once the update is complete.
if systemd auto-restarts the service just after the updater kills it then the update cycle will fail.
