### ISSUE TITLE
[yggtorrent] 401 Unauthorized, check your credentials (Config)

### ISSUE THREAD

**Issue by FlyeZz** [Jackett/Jackett#5272]
When i try to configure YGG indexer i have a error code : 401 Unauthorized, check your credentials.
But my credentials are good... i can connect to the site always.

Someone can help me pls !! 👍

Thanks in advance,
 
**Jackett Version 0.11.327.0**:  
 **Mono version 5.18.0.240-12**:

![image](https://user-images.githubusercontent.com/44934465/57703374-36cf3d00-7660-11e9-959e-102af507fd06.png)

-------------------------------

**Comment by garfield69** [comment]
on your Jackett dashboard edit the YGGtorrent config and set the **Site Link** to `https://www.yggtorrent.ch/` and the **Search and download URL** to `www2.yggtorrent.ch` then click **OKAY**. if you get an error, click **CLOSE** then edit again and click **OKAY**. it should save the second time.

if you still get problems after that then
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.
