### ISSUE TITLE
Cannot download torrent from PrivateHD

### ISSUE THREAD

**Issue by alex3137** [Jackett/Jackett#528]
Hello.

I am getting an error when I try to download a torrent from PrivateHD:

The error in Jackett is "Error downloading privatehd https://privatehd.to/download/torrent/*********************************.torrent"

My Jackett version is 0.7.398.0

Please find the debug logs here: http://pastebin.com/05nXbjdQ

Thanks !

**Comment by kaso17** [comment]
It's working fine for me, any chance you're still ranked as a newbie (can only download torrents older than 7 days)?

**Comment by alex3137** [comment]
Oups... I feel stupid now. It is indeed the issue, sorry for that !
