### ISSUE TITLE
[divteam] Error: Contraseña Incorrecta (Config)

### ISSUE THREAD

**Issue by VidelaRosa** [Jackett/Jackett#5281]
**Jackett version**:  v0.11.327
It seems to be because of the captcha.

Could you please take a look?

Thanks :)

**Comment by garfield69** [comment]
i don't get a captcha during login.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by garfield69** [comment]
never mind I see it now. 

jackett detects and attempts to solve captcha (unless they are the new variety in which case you should be seeing `specified argument is out of range` errors.

my jackett can solve that captcha and login.

are you certain your password is correct in your jackett config? could it be out of date?

**Comment by RicardoVelaC** [comment]
With Jackett Version 0.11.338.0, [divteam] work perfect for me

**Comment by garfield69** [comment]
with jackett pre-release #0.11.341 onward, now using cookie login to bypass issue.
