### ISSUE TITLE
[yggtorrent] Login Failed, got redirected. Try changing the indexer URL to https://www2.yggtorrent.ch/. Updated site link, please try again. (Config)

### ISSUE THREAD

**Issue by empireages** [Jackett/Jackett#5283]
We get this error when our ratio on yggtorrent is below 1.00, when below 1, the account is disabled and yggtorrent.ch redirect us randomly to 'https://www2.yggtorrent.ch/user/disabled'

It would be cool if this redirection was detected by Jackett correctly (telling us account disabled for example). And that jackett didn't prevent us from searching on ygg when the connection test fail ramdomly from that ratio thing.

Or does removing the "path /" test in yggtorrent.yml can solve the issue ? when on the disabled url, we still have the second test valid as there is still the "selector: div#top_panel:contains("Déconnexion") "

Site link : https://www.yggtorrent.ch/
S&D URL: www2.yggtorrent.ch

Jackett Version 0.11.325.0 from linuxserver.io docker image

-------------------------------

**Comment by garfield69** [comment]
if you can provide the html you get when you are banned, then we should be able to include it in the login test.
best way to do this is :
provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
thanks

**Comment by empireages** [comment]
`<div class="ct"><ul><li><strong style="color:#3dd806"><span class="ico_upload"></span>  900Go</strong>  -  <strong style="color:#ea5656"><span class="ico_download"></span> 1000Go</strong> <strong style="color:#fff"></strong></li>
				<li><a style="color:#fff" href="https://www2.yggtorrent.ch/user/donate"> <strong>Ratio : 0.9</strong></a></li>
									<li><a  href="https://www2.yggtorrent.ch/user/disabled"><strong style="color:#ff3f0b">Compte Inactif</strong></a></li>
								<li><a href="https://www2.yggtorrent.ch/user/notifications" style="color: #efefef; font-weight: bold;">Notifications <span class="bulle" data-balloon="Notifications non lues" data-balloon-pos="down" >0</span> <span class="bulle" data-balloon="Total notifications reçues" data-balloon-pos="down" style="background-color: #4fa034;">0</span></a></li>
				<li><a id="panel-btn" class="active"> Bienvenue <strong>ACCOUNTNAME</strong> ! <i>(Mon compte)</i></a></li>
								<li><a href="https://www2.yggtorrent.ch/user/logout"> Déconnexion</a></li>
			</ul>
		</div>`


This is the html code from the disabled page where we can see our ratio and the "Compte Inactif" if ratio below 1.

I will provide the log shortly.

**Comment by garfield69** [comment]
jackett pre-release v0.11.347 now has https://github.com/Jackett/Jackett/blob/7a77245e2583724aed62703ccedfd9a36436e592/src/Jackett.Common/Definitions/yggtorrent.yml#L156-L166
