### ISSUE TITLE
[torrentslocal] Error: Новинки (Config)

### ISSUE THREAD

**Issue by Prosecutor** [Jackett/Jackett#5284]
Hi there!

So basically getiting this kind of error.

Log file: https://pastebin.com/vmuWvsKz
Version: v0.11.340
Status: `Роль: Пользователь`
Via: https://torrents-local.xyz/tracker.php i get the results and can access them
Using seedbox.

**Comment by garfield69** [comment]
@Prosecutor  do you still have this problem or did you figure out what needed to change in your account to allow jackett to work with this indexer?

**Comment by garfield69** [comment]
the jackett indexer only works with the classic forum style.
on the torrentslocal site, access your profile preferences and set the forum style to Классическая тема
see if that works for you.
