### ISSUE TITLE
[xktorrent] Exception (xktorrent): Object reference not set to an instance of an object.: Parse error (Test)

### ISSUE THREAD

**Issue by Astrem2005** [Jackett/Jackett#5286]
Hello,

xktorrent FR-FR
We need to provide a cookie header, but xktorrent doesn't ask anymore a Captcha on login page.

https://xktorrent.com/login

Can you modify the login way for xktorrent tracker pls?

Thanks!

-------------------------------
Jackett Version 0.11.340.0

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.346
you may need to trashbin your existent config
