### ISSUE TITLE
[torrentseeds] Again not working

### ISSUE THREAD

**Issue by MoeJoe87** [Jackett/Jackett#5292]
**Jackett Version 0.11.340.0

Log: https://pastebin.com/c7jYe9n5

-------------------------------

**Comment by garfield69** [comment]
site is replacing their search engine, results page will be in flux for a while.
i'll update the indexer shortly, but expect will need to update frequently as the changes roll in at the site.

**Comment by garfield69** [comment]
try out jackett v0.11.348

**Comment by MoeJoe87** [comment]
Ok thanks it works again
;)
