### ISSUE TITLE
Jackett 100 limit search

### ISSUE THREAD

**Issue by vdugard** [Jackett/Jackett#5293]
**Jackett version 0.11.279.0**
Hi,
Jackett only return 100 torrents when searching indexers.
Is it normal ?

**Comment by garfield69** [comment]
yes. that is about as many as most sites return in one page of results.

**Comment by Adrillex** [comment]
Ok so there is no way to increase this number ? thank you for the answer

**Comment by garfield69** [comment]
not from the jackett dashboard.
it's down to the individual indexer definitions, the sites default torrents per search, etc.
in general we try to avoid making multiple requests to fetch multiple pages, to avoid getting pinged as a possible DDoS bot.

**Comment by Adrillex** [comment]
Ok I undestand, is there something i can try, like modifying indexer definition ? or to force this multiple page fetch ? I use YGG and their search system is hell. Some of my research should return more than 100 results

**Comment by garfield69** [comment]
sure. find the yggtorrent.yml in the Definitions folder, and read https://github.com/Jackett/Jackett/wiki/Definition-format#search

but be aware, any time you auto-update jackett your custom definition will get replaced, so best if you clone the existing yggtorrent.yml and call it yggtorrent2.yml and update the **site** keyword in the yml header https://github.com/Jackett/Jackett/wiki/Definition-format#header to yggtorrent2 as well

**Comment by Adrillex** [comment]
Ok I will take a look at this, thank you for your help

**Comment by garfield69** [comment]
note: after changing yggtorrent2 you'll need to restart jackett to pick up the changes.

**Comment by Adrillex** [comment]
I succeed to increase number of torrent that jackett find by modifying indexer definition file. It works when I search using jackett UI, however sonarr still get around 100 torrents when it query Jackett, and I can't find why. 
Do you have an Idea ? Is it sonarr related, or something I need to configure Jackett side ?

**Comment by garfield69** [comment]
it's sonarr. it places a limit=100 parm on its requests to jackett
below is the log of a request sonnar made to my jackett using thePirateBay indexer I set up for this test.
`Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/indexers/thepiratebay/results/torznab/api?t=tvsearch&cat=100200,100201,100202,100203,100204,100205,100206,100207,100208,100209,100299&extended=1&apikey=**redacted**&offset=0&limit=100&q=Game%20of%20Thrones&season=8&ep=3`

by the look of it, its hardcoded into the sonarr request procedure
https://github.com/Sonarr/Sonarr/blob/7d06e5d6842e6b81b8d4b4b0ab94f5bfba21cae6/src/NzbDrone.Core/Indexers/Rarbg/RarbgRequestGenerator.cs#L114
![image](https://user-images.githubusercontent.com/6933240/57987278-55f02380-7ad3-11e9-9ecc-f1326146ecc8.png)

**Comment by Adrillex** [comment]
Thank you for the help. After some research I found a related issue : 
https://github.com/Jackett/Jackett/issues/1661#issuecomment-322227361

Here, it is said that sonarr should fetch additional torrent if it detect that the limit has been reached. I guess sonarr should do this using "offset" torznab parameter, then we use it inside the indexer definition using " .Query.Offset " right ? However, I checked Jackett's log, but it looks like sonarr don't try to get more torrent even if the limit is reached.

**Comment by Adrillex** [comment]
For some reason, when I'm trying yo use ".Query.Offset" in the path, I get a cast error.
![image](https://user-images.githubusercontent.com/19326477/57989437-e8c09c00-7a9a-11e9-89a2-11f549b2504e.png)

Here is my path :
      - path: "https://{{ .Config.searchanddlurl }}/new_search/search?category={{ .Config.category }}&name={{if .Config.enhancedAnime}}{{ re_replace .Keywords \"([\\.\\s\\[\\-])(\\d+)$\" \"$1e$2\" }}{{else}}{{ .Keywords }}{{end}}&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&page={{ .Query.Offset }}"

**Comment by garfield69** [comment]
looks like the offset, limit and expanded values are integers in the torznab specs, but the cardigannindexer is trying to use them as string.
your'e the first to use these values in an yml script ;-)
I've amended the cardigannindexer to convert them to string for use in the `{{.query.*}}` 
try out jackett pre-release v0.11.356 and see if that helps.

**Comment by Adrillex** [comment]
Ok Thank you, I will try that :)

**Comment by Adrillex** [comment]
Thank you, I managed to get it working with your help :)

**Comment by WoisWoi** [comment]
> 
> 
> Thank you, I managed to get it working with your help :)

Hi, I have the problem and I'm also using YGGTorrent. Would you mind sending to me the "yggtorrent.xml" and other stuff you used to fix the problem, please ?
