### ISSUE TITLE
Jackett Version 0.11.348.0... Windows 10 1809 fresh VM install will not hold changes

### ISSUE THREAD

**Issue by jeffreyswiggins** [Jackett/Jackett#5297]
So this is a new VM that I am setting up to replace my physical server.  Windows 10 1809 and I have Sonarr working on it and went to Jackett and it installs and runs fine and the indexers will add correctly, however the server settings will not hold.  Such as when i clikc to allow external access it acts like it is making a change then the screen refreshs and nothing happens.  If I set an Administrator password same thing.  If I try to add a proxy server address and port same thing.  Not sure what I am missing.

**Comment by jeffreyswiggins** [comment]
After the 5th uninstall/reinstall it seems to be working now.  Not sure what the difference is as I have tried the uninstall / reinstall 4 times prior to posting this but it is working now and after areboot so seems to be good. closing

**Comment by garfield69** [comment]
when you change a setting using your jackett dashboard, you need to use the **apply server setting** button to store the setting, this also restarts the server so the settings take effect.

**Comment by jeffreyswiggins** [comment]
Thanks but I had done that a dozen times with no effect other than it would state it is redirecting me to the completed page in which settings were set back to stock.
