### ISSUE TITLE
[req] bitseduce.com 

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#5300]
the6step requested the following via a private email.

BitSeduce is a Private Torrent Tracker for SEDUCTION & SELF-IMPROVEMENT E-LEARNING
bitseduce.com 

If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by koushik-sen-vst-au4** [comment]
Please provide me a invite at senkoushik91@gmail.com.

Please help me out.

**Comment by ilike2burnthing** [comment]
ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://bitseduce.com/ returning ERR_CONNECTION_TIMED_OUT or ERR_CONNECTION_REFUSED
is the site gone, broken or moved to a new domain?
