### ISSUE TITLE
Torrentday - not grabbing HEVC in results

### ISSUE THREAD

**Issue by jpichie** [Jackett/Jackett#531]
It seems that Torrentday is not returning any HEVC results even though they exist on the page.
I also use Jackett Public, and TPB returns the HEVC results.
Was hoping this could be looked into as I only download HEVC when possible.
thanks

**Comment by kaso17** [comment]
if you can send an invite to kaso1717 -at- gmail.com I can fix it

**Comment by flightlevel** [comment]
Also, a few examples?

looks good here
![I](https://i.snag.gy/GVLq7I.jpg)

What torrentday category are the missing files in?
Do they appear when manual searching from Jackett dashboard?
What categories do you have set in Sonarr's indexers page
What version of Jackett are you running?

**Comment by jpichie** [comment]
@flightlevel 
I had to add category 5000 for it to show, thanks.

**Comment by flightlevel** [comment]
@jpichie Good to hear

@Azerelat @JigSawFr @kaso17 Sent you a slack message
