### ISSUE TITLE
Install service failed on Raspbian

### ISSUE THREAD

**Issue by Dravenrip** [Jackett/Jackett#5311]
Hi folks !

I'm on a raspberry pi 3, and i try to remove my "mono version" of Jackett for a standalone ARM version.
I've uninstall and removed all mono elements.
I've donwloaded Jackett arm64 package.

Bud when i try to launch "sudo ./install_service_systemd.sh" command, i get an error message that say :
`ERROR: Could not launch service. The installation might have failed.
Please open an issue on https://github.com/Jackett/Jackett/issues and paste following information:
Jackett directory: `/home/pi/Downloads/Jackett`
Jackett user: `draven`
`
I try to change owner by a non root user as described on an issue here, but no effects.

I'm a little noob on linux system, so i probably do somethine wrong ... but what ?
Can you help me please ?

**Comment by flightlevel** [comment]
Are you running a 64bit OS? try the ARM32 version
If that doesn't work
from the jackett directory
Post the output of `./jackett -t -l`

**Comment by Dravenrip** [comment]
oh yeah that's it ! .. i try 32bits one more time and it seems to work this time.

Thanks for help
