### ISSUE TITLE
Karagarga: No download link when saving to black hole or using it with radarr

### ISSUE THREAD

**Issue by xpirat** [Jackett/Jackett#5313]
When doing a manual search on Karagarga through jackett I get results. But when trying to download the .torrent to black hole it’s not working. My other tracker such as avistaz is working downloading the .torrent to black hole.

When I search Karagarga with radarr+jackett (Karagarga torznab) it’s not getting results.

**Comment by ngosang** [comment]
@xpirat I don't have account to test. Is it fixed?

**Comment by ngosang** [comment]
I think this was fixed in #7057 . Test the latest version and I will reopen if it's not working.
