### ISSUE TITLE
jackett.json in qBitorrent not located in qBitorrent folder

### ISSUE THREAD

**Issue by Eyji** [Jackett/Jackett#5316]
The jackett.json needed when using the search engine in qBitorrent is not located in `%localappdata%\qBittorrent\nova3\engines\` as specified [here](https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin). Instead, it is based in a python folder. Had to search it using [Everything](https://www.voidtools.com/). See capture below.

[Jackett.json location using Everything](https://user-images.githubusercontent.com/10639815/58221228-13685a00-7d12-11e9-93e1-102e9acf9aa9.png)

Creating the jackett.json file in the same folder as the jackett.py file would result in an api key missing error.

**Comment by garfield69** [comment]
@Eyji we did not write the qBt jackett plugin, this issue belongs in the https://github.com/qbittorrent/search-plugins repo
