### ISSUE TITLE
[REQ] rocket-hd.me [Private/UNIT3D]

### ISSUE THREAD

**Issue by inasua** [Jackett/Jackett#5317]
please list rocket-hd.me its based on UNIT3D

https://rocket-hd.me/

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by garfield69** [comment]
Registration and login successful. Thank you.

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.365

**Comment by garfield69** [comment]
currently https://rocket-hd.me/ broken
![image](https://user-images.githubusercontent.com/6933240/60934343-f9aec080-a319-11e9-977d-4bee3386b4b1.png)

**Comment by garfield69** [comment]
rocket-hd.me are forcing http only. the next release of Jackett should auto correct.

**Comment by garfield69** [comment]
Hmm. http://rocket-hd.me/ now points to Empornium which uses Project Luminance. 
my rocket-hd login is unknown there so I assume this is a different site.
Empornium is a private tracker for XXX , officially at https://www.empornium.me

so has rocket-hd gone, or is there a  new domain?

**Comment by garfield69** [comment]
its been a couple months, and no news. so presume site has gone. will remove it from jackett.
