### ISSUE TITLE
[REQ] NBTorrents (Private/Indian)

### ISSUE THREAD

**Issue by shakir87** [Jackett/Jackett#5337]
Request to add support for NBTorrents private tracker [https://www.nbtorrents.com](https://www.nbtorrents.com)

Registration is open, but i have an invite if needed.

**Comment by garfield69** [comment]
site is currently broken.
yesterday when accessing the main link it tried to download the *.php code instead of presenting a web page.
today the site is returning cloudflare 522 connection timeout.
a couple weeks ago I did manage to register and login, so when the site comes back up I should be able to start working on a jackett indexer for the site.

**Comment by shakir87** [comment]
Great! Looking forward to this.

**Comment by garfield69** [comment]
currently presenting 
![image](https://user-images.githubusercontent.com/6933240/59312509-8194b100-8d01-11e9-9758-76e3ba02df30.png)

**Comment by shakir87** [comment]
yeah I’m seeing the same. Hopefully it come back online soon...

**Comment by shakir87** [comment]
Looks like it’s back online now

**Comment by garfield69** [comment]
still not working for me. when I access the url I get a download? :/
![image](https://user-images.githubusercontent.com/6933240/59380600-9890dd00-8dad-11e9-99ad-f4787f008ae0.png)

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.431

**Comment by garfield69** [comment]
https://www.nbtorrents.com/ returns DNS_PROBE_FINISHED_NXDOMAIN (domain not found)

**Comment by garfield69** [comment]
@shakir87  do you have any news for this site?
Is it broken, moved to a new domain or gone?

**Comment by garfield69** [comment]
v0.20.929

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/169475460-0c449796-c007-45b1-8dde-cc4a00a00f66.png)

**Comment by ilike2burnthing** [comment]
Weird, working fine here (the login page at least):
![nbtorrents](https://user-images.githubusercontent.com/59480337/169492963-354fa5ee-b9c3-42b4-9396-235f54864c19.png)

Tried a private/incognito window or different browser?

**Comment by garfield69** [comment]
chrome incognito, vivadi, Edge, Opera and Firefox also return the sql error on my windows system.
But when I tried the ubuntu image on my windows virtualbox chrome browser I was able to login !?!

**Comment by ilike2burnthing** [comment]
Very weird! So it's not even a region or IP issue then.

Edge, Opera, Chromium, and Firefox on Windows all working here.

**Comment by garfield69** [comment]
And If I use Jackett on widows the indexer does not work, returning the SQL error during the login attempt.
But my jackett on the ubuntu image works %-/
I cant use hideme on windows to test, the site returns `Fuck OFF!!! You are using Proxy, VPN or DC IP`

**Comment by garfield69** [comment]
Anyway, it looks like the site was restore using a backup from 2020, there are no active torrents, and the latest two torrents date are Aug 7 2021 and Nov 11 2020.
I'll close this ticket, and if anyone raises a ticket about windows jackett we can tell them to go use linux ;-b

**Comment by garfield69** [comment]
v0.20.1092

**Comment by garfield69** [comment]
v0.20.1799

**Comment by garfield69** [comment]
https://www.nbtorrents.com/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.20.2384
