### ISSUE TITLE
Unable to use Torrentday

### ISSUE THREAD

**Issue by PARA60N** [Jackett/Jackett#535]
When I go to add torrentday as a index the recaptcha says "Localhost is not is the list of supported domains for this site key."

**Comment by kaso17** [comment]
Can you send an invite to kaso1717 -at- gmail.com so I can debug it?

**Comment by SirMaggot** [comment]
I have sent you an invite kazo1717 :)

**Comment by kaso17** [comment]
I didn't get it, if you made the same typo as above (it's kaso1717 - not kazo1717) that would explain it.

**Comment by SirMaggot** [comment]
Well, i can't check, so i sent you another one :)

**Comment by kaso17** [comment]
got it, thank you.
Nothing wrong with it.
I just noticed that g-captchas don't work with hostnames.
Try accessing jacket via IP (http://127.0.0.1:9117), that works for me.
I'll have a look at it if we can fix it.

**Comment by armani316** [comment]
@PARA60N TorrentDay has been working fine for me as of late. Is this still an issue?

**Comment by armani316** [comment]
@kaso17 Should this be closed?

**Comment by TheBryGuy** [comment]
No, I'm still having this issue on 0.7.952.0

**Comment by flightlevel** [comment]
@TheBryGuy 
Just tested and it works here
What happens?
Also a full log is needed https://github.com/Jackett/Jackett#troubleshooting and please confirm you are accessing Jackett via address http://127.0.0.1:9117

**Comment by armani316** [comment]
@TheBryGuy It would be great if you could provide the full enhanced log (as per @flightlevel's instructions) to help resolve this issue :) Also, don't forget to update to the latest versions of both Jackett & Mono (if applicable).

**Comment by TheBryGuy** [comment]
@flightlevel @armani316 
Hey guys, meant to respond to this earlier. I will get that info to you in the next day or two.

**Comment by kaso17** [comment]
I've opened #1026 as enhancement ticket

**Comment by doglife007** [comment]
any one a invite on torrentday
