### ISSUE TITLE
Bus error version 0.11.343.0 and server configs ignored on 0.11.379.0

### ISSUE THREAD

**Issue by crescent94** [Jackett/Jackett#5355]
v0.11.343.0 just stopped working after a debian update and only gives "bus error"

When I attempt to go to 0.11.379.0 and copy over ServerConfig.json, Indexers, DataProtection and log, the copied files get ignored and a new config starts instead.  I do not know where that new config is coming from.  

This is not running at root in either instance.

I just one of them working, please advise.

**Comment by ade05fr** [comment]
Hi
i have also this problem since the latest version 0.11.384 (previous version was 0.11.380 which worked fine without mono on my QNAP TS 251)

**Comment by ngosang** [comment]
That version is old. Please update to latest version.
