### ISSUE TITLE
LimeTorrents Search RSS not working as it should

### ISSUE THREAD

**Issue by Wilson2013** [Jackett/Jackett#5365]
Windows 7 64-bit, Latest Jackett

I don't think SearchRSS has ever worked properly in Jackett for LimeTorrents.

For example 

http://127.0.0.1:9117/api/v2.0/indexers/limetorrents/results/torznab/api?apikey={my_api_key}&t=search&cat=&q=x265

should return the most recent results containing "x265". It doesn't, it returns the most-seeded results.

All other indexers I've tried work perfectly except LimeTorrents.

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.383

**Comment by Wilson2013** [comment]
Perfect, thanks very much!!
