### ISSUE TITLE
Jackett Docker

### ISSUE THREAD

**Issue by sparklyballs** [Jackett/Jackett#537]
Hi, I am a member of the linuxserver.io team and we currently have a jackett docker in our repository.

We wondered whether you would be interested in listing us an install option for your project.

you can check out our container stats here for our other images, 

http://tools.linuxserver.io/dockers

our website here

https://www.linuxserver.io/

and on freenode at #linuxserver.io 

looking foward to hearing from you.

**Comment by JigSawFr** [comment]
Hi @sparklyballs,
I'm personnaly using your great images without any problems.
Docker installation is actually missing from our README or Wiki,
And in fact, docker is a great install alternative.
Why not adding your docker image.
We'll think about it.

**Comment by flightlevel** [comment]
Thanks for your great work @sparklyballs 
Have added your docker to the readme
Amazing how many downloads!
