### ISSUE TITLE
Invalid non-ASCII or control character in header: 0x2B50 for magnet link

### ISSUE THREAD

**Issue by MickeMannen** [Jackett/Jackett#5372]
Some torrent links gets a star in their name for 1337x (and also other sites)- ⭐ 

([https://www.fileformat.info/info/unicode/char/2b50/index.htm])

when selecting the magnet link this character is also included but the response from jacket is a internal server error (500)

I am currently using version 0.11.279.0

Error message from server:
{
  "result": "error",
  **"error": "Invalid non-ASCII or control character in header: 0x2B50",**
  "stacktrace": "   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(StringValues& headerValues)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.SetValueFast(String key, StringValues& value)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(String key, StringValues value)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.RedirectResultExecutor.ExecuteAsync(ActionContext context, RedirectResult result)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)\n   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29"
}

**Comment by garfield69** [comment]
similar to #4761

**Comment by Lokukarawita** [comment]
@MickeMannen  I managed to fix this by updating the 1337x.yml definition as below.  
@garfield69 @flightlevel @kaso17 maybe one of you guys can add it to the next update (it does need more testing though)

```
  download:
    # the .torrent url is on the on the details page 
    selector: ul li a[href^="{{ .Config.downloadlink }}"]
    filters: 
      - name: urldecode
      - name: replace
        args: [" ⭐", ""]
      - name: strdump
```

**Comment by MickeMannen** [comment]
thanks - i will test the next update and confirm if this solves the issue

**Comment by garfield69** [comment]
Jackett 0.12.1470
