### ISSUE TITLE
Update SynoCommunity package for Synology NAS to not require Mono

### ISSUE THREAD

**Issue by epheterson** [Jackett/Jackett#5373]
Mono has lead to lots of instability with Jackett on Synology NAS (fortunately not as much lately!), so it's refreshing to see there's a variant of Jackett which doesn't use Mono.

Unfortunately, the de-facto way to install Jacket on Synology is via the SynoCommunity package installer source, which is still pointing to the Mono variant.

Can we please get a SynoCommunity update that removes the dependence on Mono?

Thanks!

**Comment by garfield69** [comment]
we are not responsible for updates by the synoCommunity to their repo.
raise a ticket on their site at https://github.com/SynoCommunity/spksrc/issues
