### ISSUE TITLE
Sportscult download link fails

### ISSUE THREAD

**Issue by manderss99** [Jackett/Jackett#5378]
when pressing the download link in jackett search no torrent file is downloaded.
from the log:

5-31 10:28:40 Error CardigannIndexer (sportscult): Download selector a[href^="download.php?id="] didn't match:
d8:announce81:https://sportscult-announce.org/announce.php?pid=dbd93505f97d036213ba9430ce235d387:comment19:This is the comment10:created by19:Doug using -MO0800-13:creation datei1558281899e8:encoding5:UTF-84:infod6:lengthi2886501220e4:name62:MotoGP 2019 FrenchGP Race 19 05 1080pEN50fps BT Sport 2 HD.mkv12:piece lengthi1048576e6:pieces55060:
05-31 10:28:40 Error Error downloading sportscult https://sportscult.org/download.php?id=08d6c75531b43769cf73bb5c11453c47559e062b System.Exception: Download selector a[href^="download.php?id="] didn't match
   at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1674
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/DownloadController.cs:line 53

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
0.11.384.0

-------------------------------

**Comment by garfield69** [comment]
since this is a private site and I don't have a login, we are going to need to see the html produces with you do your jackett search, so we can see what the download links look like now.

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by manderss99** [comment]
I could send an invite if I have an e-mail adress.

Otherwise I provide mord details tomorrow.

**Comment by garfield69** [comment]
please send an invite to garfieldsixtynine @ gmail.com

**Comment by manderss99** [comment]
Invite sent,  thanks

**Comment by garfield69** [comment]
registration and login successful. thank you.

**Comment by garfield69** [comment]
try out jackett 0.11.385

**Comment by manderss99** [comment]
The download now works in Jackett, many thanks.

However when I try to download from nzbhydra2 I get the following error in nzb log:

java.net.URISyntaxException: Illegal character in query at index 623: http://galaxy-tab-s5e:9117/dl/sportscult/?jackett_apikey=<apikey>&path=Q2ZESjhGYlQ0dHNKaDNGS2lmdmhGLWo0bk85XzE3ZXcxLU5zUUYxX242Y1Iza1hGWGdPOXNKbjRTMk5pSXB5WmpMcDB6dU5mWGJuNURzWm5ZMVRrUGlPR2otVnNfcllHSEM1T3ZyLXlpanVoREhvMVZKLVh2ZlFDaEwxRnJvRkY5MUM5OFFPRF80S0h3ekZWZWNnS0pMamNKQW5yeWhrM0F1Q2pHVHFGQ0RsSHJWYU94SG5XM3ZuNk96bjVUZDBiVjVUOUIzNTVIbnZncnpYeDluMXRZXzNFNWRWOFk3M1lfdzBFRnlETHlnaVEzdjRUa18tLWMzRGg2UjZWWU9JMnZjc2hybVctMlliakJGejlhUVVEM3FpTndISlFfSmw4MTJHcG1ad1h2YXoyUlBuY3R0MjRvaHlZRnhUcnAzNU5Ubk41Wk5aOV9LVldjbmcyRWQ2N0djSHpmMW8&file=MotoGP+2019+ItalianGP+Free+Practice+02+31%2F05+720pEN25fps+|+BT+Sport+2+HD 

Not sure if the problem is with jackett or nzbhydra, please advise

**Comment by garfield69** [comment]
probably something in `&file=MotoGP+2019+ItalianGP+Free+Practice+02+31%2F05+720pEN25fps+|+BT+Sport+2+HD`

if sportscult returns a file name that contains characters which the jackett dashboard is happy to accept but nzbhydra rejects, then i suspect it should be up to nzbhydra to filter it instead of throwing a fit?

**Comment by manderss99** [comment]
I've done some experimenting and files that don't contain the pipe character seem to work fine but those with pipe fails.

After reading up on url encoding it seems the proper way to pass a pipe in an url is by encoding it to %7C
https://developers.google.com/maps/documentation/urls/url-encoding

Since Jackett is providing the URL I think the proper fix would be for Jackett to encode the pipe character to %7C, agree?

**Comment by garfield69** [comment]
>Since Jackett is providing the URL I think the proper fix would be for Jackett to encode the pipe character to %7C, agree?

no, I dont think so. its not jackett that is providing the url, but sportscult. if nzbhydra was accessing sportscult directly, it would probably still run into problems.

the download link provided by sportscult looks like this:
`https://sportscult.org/download.php?id=fb27625a0543ed731f7b3505beebf4c8d530f8f9&f=IIHF+2019-05-26+%7C+Gold+Medal+%7C+Canada+vs+Finland+%7C+1080p+EN.torrent`

sportscult is including the whole title string `IIHF 2019-05-26 | Gold Medal | Canada vs Finland | 1080p EN` from their search result in the filename when it builds the download link without regards for what makes a valid filename

this is really an issue with the site, but never mind.
I suppose we can strip the `+%7C` from the filename so I can get back to watching the tennis.

try out jackett pre-release v0.11.386 and see if that works with your nzbhydra.

**Comment by manderss99** [comment]
tested on .386, the regexp does not seem to work.
If I search in jackett and copy the download link the %7C is still there:

http://galaxy-tab-s5e:9117/dl/sportscult/?jackett_apikey=<apikey>&path=Q2ZESjhGYlQ0dHNKaDNGS2lmdmhGLWo0bk85U0xuWmxVd0xhaGNLZkh4bjVnbXVsZUVhT0tfdnd3eWJ6eXdtYnp0cW44cUtma21VTUNYUGI5a1kwWUtIaVQzLXpJZ3JvLWJyb01URDk4RnJUT3VKTThWQk82T05QXzh0U0c2Q0x6RGNqUTlKZW1MRHZWTklDSFRHN09Gek1HVTNJamtaQ1VMQlVtaWhFLUxVOFdFcVhLaWdCcVFwbVdWd3poaGp2OHE2ZEZDS2N6Y2FUaWx2WGw1aFlzZXRTNXNVOHAzeGNRc1hBRVp2Sm1IZ01iLVk0N3VCUWF6UEhseUo1NnNaby1RS091dlFmbS0yazVVYUFSZ01mTG44dWZXa3ZwaVNQLUFRMjd3azF3ZW10ODFwaGplZ2dWVVQxemgwTXphdkZ5OVF1THdFS0VScTAxT0JYSDZhUzMzM3BlSjg&file=MotoGP+2019+ItalianGP+Free+Practice+02+31_05+720pEN25fps+%7C+BT+Sport+2+HD

the pipe character still appears in nzbhydra as well.

**Comment by garfield69** [comment]
Try out jackett pre-release v0.11.387
I'm stripping the bar from the title as well, see if that makes a difference for you.

**Comment by manderss99** [comment]
387 works fine, many thanks
