### ISSUE TITLE
[REQ] zooqle.com

### ISSUE THREAD

**Issue by xtra-be** [Jackett/Jackett#539]
please add zooqle.com : https://www.zooqle.com
 the provide an api 
https://zooqle.com/help/api.html

**Comment by kaso17** [comment]
This version of Jackett won't support public trackers, try opening an issue with one of the forks supporting public trackers.

**Comment by DejaVu** [comment]
Seeing as this has now changed in the newer releases, is there any chance of including Zooqle and GloDLS now?

**Comment by RoloSoze** [comment]
@DejaVu Already being discussed in #1185 :)
