### ISSUE TITLE
[torrentgalaxyorg] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by groenator** [Jackett/Jackett#5394]
When testing the indexer no results are showing Logs added it in the next thread.

**Comment by groenator** [comment]
Hi,

Sorry about that, I will create a new issue and provide more logs. 

Regards,

**Comment by garfield69** [comment]
should be working again with jackett v0.11.388.
had to change the row selector and drop .torrent support.
magnet only for now.
