### ISSUE TITLE
New Tracker Xtreme Zone

### ISSUE THREAD

**Issue by vulpasin** [Jackett/Jackett#540]
Please add new tracker Xtreme Zone http://myxz.org/

Thank you

**Comment by VadVoci** [comment]
Hi. Some news with this tracker?
When will be introduced in Jackett Indexers?

**Comment by kaso17** [comment]
fixed with 42434c35a156f630d9256b7a5e7afeaa1f555f73

**Comment by armani316** [comment]
@kaso17 Xtreme Zone is semi-private.

**Comment by kaso17** [comment]
fixed
