### ISSUE TITLE
Socks5 proxy causing high CPU using in both windows and linux

### ISSUE THREAD

**Issue by dequeant** [Jackett/Jackett#5400]
I've tried standalone Jackett on 2 different servers running 2 different operating systems.  I've had this issue for over a year now.  I quit running jackett a year ago because of it.  I recently decided to try again hoping the issue had been resolved. 
It hasn't, and its unfair for me to expect a fix to a free product without at least reporting the issue....so here it is.

The first server is running windows 10, which after a day or so inevitably results in 100% CPU usage.  The second on a Raspberry Pi running DietPi 6.24.1 which also, after a day or so, results in around 60% constant CPU usage.  It only happens with Socks5 enabled.....and it ALWAYS happens when it is enabled.

Running Jackett 0.11.385.0 with Socks5 enabled (using PrivateInternetAccess socks5, in case that's useful info).  TPB is the only service I index with jackett.

This is identical to #2602, which has been closed since Feb.  
https://github.com/Jackett/Jackett/issues/2602

**Comment by rrrevin** [comment]
Works fine for me. I'm using several socks5 servers (Torguard) and there is no CPU spike for me, at all.
If you can, perhaps change to different server in the PrivateInternetAccess server list?

**Comment by dequeant** [comment]
Unfortunately, PIA only have a single socks5 server.  Admittedly, it is the only one I've ever used, to include when I originally had the issue over a year ago.

I did a test shortly after opening this.  I rebooted the (linux) server and did not use it to index/search/scrape and it has been running for over 24 hours with no issue (with socks5 enabled).

The issue has only occurred within around 24 hours after being used to search.

I do not have any other sock5 proxies to test with.

**Comment by tsullyman** [comment]
I have this exact same issue, Jackett on Synology docker, CPU useage just always super high while using socks5 proxy with PIA.

Will this be fixed? Was an issue on my Win10 machine when I last used Jackett on that 4-5 months ago as well!!!

Frustrating Hey.

**Comment by dequeant** [comment]
That's certainly a possibility.  

I suspect that it could be consistently reproduced if the devs try PIA's socks5.  It's certainly consistent for me.

**Comment by Baukebrenninkmeijer** [comment]
I have it as well when using PIA.

**Comment by frm1001xplrr** [comment]
I've had the same CPU spiking issue, only when using socks5 with PIA. Whenever if run without socks5 i have no issue at all. Consistent since i started using Jackett over a year ago. 

Would any dev be interested i an enhanced log or some other means to check this out?

**Comment by lsaadeh** [comment]
any workarounds to use a proxy for Jackett without stress testing my cpu out?

**Comment by frm1001xplrr** [comment]
I use ProxyCap as a workaround for Jackett. Haven't had a single CPU spike issue since :)))

Setup: https://imgur.com/a/jFgM7mm
App: http://www.proxycap.com

**Comment by ngosang** [comment]
We don't have specific code to handle proxies. This functionality is provided by C# language and .Net framework.
Since we updated to .Net 5.0 recently, maybe it's already fixed.
