### ISSUE TITLE
Soap4.me new semi-private tracker

### ISSUE THREAD

**Issue by SuberSeb** [Jackett/Jackett#5401]
Soap4.me is russian semi-private tracker. It has a lot of TV shows and torrents for it.

**Comment by garfield69** [comment]
the search on this site returns just the series name.
episodes are buried in subsequent details pages.
this means it is not suitable for cardigann processing.
the indexer will have to be coded in c#

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
