### ISSUE TITLE
Request for HamsterStudio.org semi-private tracker

### ISSUE THREAD

**Issue by SuberSeb** [Jackett/Jackett#5402]
HamsterStudio is russian torrent tracker. It has a lot of TV shows.

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.410

**Comment by SuberSeb** [comment]
Sonarr can't find releases. For example Fear the Walking Dead, there are error: "Found 0 releases from HamsterStudio for: Fear the Walking Dead S05E02". HamsterStudio have this release but it doesn't appear in search result in Sonarr.

**Comment by garfield69** [comment]
doesn't surprise me. didn't know you were going to use sonarr.
will have to add a pre-process step to convert SxxExx into Сезон xx Серия xx so HS can find it

**Comment by garfield69** [comment]
actually, can you login to HS directly please, and do what ever search you would do to find the episode you are after, then post back here the url generated by the site? its in the browsers address box after the search is complete. I can then use it as a basis for the pre-processing to convert sonarrs' SxxExx into something HS can use.
Thanks.

**Comment by SuberSeb** [comment]
Seems like that HS search works a little strange. It can't find SxxExx with original name, only with russian translated name. For example, I was looking for the second series of the fifth season of the Fear the Walking Dead. This query "бойтесь ходячих мертвецов (сезон 5, серия 2)" works fine, but this query "fear the walking dead (сезон 5, серия 2)" returns none. Here is the URL generated by HS, but it seems not suitable to pre-processing: http://hamsterstudio.org/browse.php?search=%E1%EE%E9%F2%E5%F1%FC+%F5%EE%E4%FF%F7%E8%F5+%EC%E5%F0%F2%E2%E5%F6%EE%E2+%28%F1%E5%E7%EE%ED+5%2C+%F1%E5%F0%E8%FF+2%29&incldead=0&cat=0

**Comment by garfield69** [comment]
Bugger.
if HS cannot even find _fear the walking dead 5 2_ then it wold appear that HS is incompatible for use with Sonarr as it expects to be able to use English.
Nothing Jackett can do about this. Sorry.

**Comment by garfield69** [comment]
http://hamsterstudio.org/ returning
![image](https://user-images.githubusercontent.com/6933240/156898195-b9d2514d-35d3-4a1b-86b7-e30efa870de5.png)

**Comment by ilike2burnthing** [comment]
ERR_CONNECTION_TIMED_OUT

**Comment by SuberSeb** [comment]
They have some issues with the website at the moment, for me site is working but very slow. Let's wait some time and check later.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
http://hamsterstudio.org/ domain expired

**Comment by garfield69** [comment]
@SuberSeb  can you confirm if HamsterStudio is gone, moved to a new domain or just broken?

**Comment by garfield69** [comment]
v0.20.1908
