### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by joshedgarva** [Jackett/Jackett#5407]
Incredibly frustrated. Can't get this to work no matter what and the installer seems convinced it wants to use the wrong user.

Jackett directory: `/home/jackett/Jackett`
Jackett user: `smbuser`

I have created a user 'jackett,' added it to wheel and another group named jackett, and run the installer AS JACKETT, and yet it wants to use this irrelevant user I created a year ago for my Samba service?! Why?! I haven't even logged in as that user in months!

No matter what I try, I can't get this to work, and the documentation is zero help. I've tried searching the errors in journalctl (which boil down to it not being able to create a settings file in /home/jackett because it doesn't have access, even though it would if it was _using the username I acted as during install_) and Googling them and no one else seems to have this issue. 

This is CentOS 7.

Absolutely furious and about to just give up.

**Comment by ngosang** [comment]
Closed by #7614

**Comment by garfield69** [comment]
Jackett 0.13.611
