### ISSUE TITLE
[superbits] Exception (superbits): The operation was canceled.: The operation was canceled. (Test)

### ISSUE THREAD

**Issue by sljdhl** [Jackett/Jackett#5409]
Hi, i get this error almost always. If i restart my docker container for jackett and try the Test button it may work for a few minutes. Anyone know what could be wrong?

full enhanced logs: https://pastebin.com/hrYpwTi1

**Comment by WantedFreak** [comment]
Also getting that error on Superbits, all other works normally.

**Comment by ngosang** [comment]
@sljdhl It's working in the latest version?

**Comment by sljdhl** [comment]
@ngosang it works for maybe a few days and then it stops works for a few days just to be magically fixed sometimes :)

**Comment by ngosang** [comment]
> it works for maybe a few days and then it stops works for a few days

Related #6640
