### ISSUE TITLE
[req] lechaudron.net Private French Tracker 

### ISSUE THREAD

**Issue by Arrowblood** [Jackett/Jackett#5411]
Hello,
Could you please add to Jackett supported trackers https://lechaudron.net/index.php, a french private no ratio tracker for movies / general ?
Thank you so much.
AB

**Comment by Arrowblood** [comment]
Sorry no invite available for now.

**Comment by Arrowblood** [comment]
Hello,
Yes, inscriptions are opened since yesterday 06.27, so you could add it to Jackett. Thanks in advance.
The Web address is https://lechaudron.nl/TTV3/Inscription
See you.

**Comment by garfield69** [comment]
lechaudron.nl is not lechaudron.net these are two different sites.

**Comment by pipopop** [comment]
It's two different sites. But it's the same team. lechaudron.net is going to die.

**Comment by garfield69** [comment]
ok, thanks. I'll close this request.

**Comment by pipopop** [comment]
This tracker is dead : [https://lechaudron.nl/](https://lechaudron.nl/)
