### ISSUE TITLE
[torrentnetwork] Exception (torrentnetwork): no access: Parse error (Test)

### ISSUE THREAD

**Issue by MoeJoe87** [Jackett/Jackett#5414]
Hi, This error started now...maybe since yesterday. Can you please fix?

Thanks

Cheers

-------------------------------

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by MoeJoe87** [comment]
Here is the log:

[log.txt](https://github.com/Jackett/Jackett/files/3268617/log.txt)

Had no time yesterday. But i did verify it is still not working and my saccount is working fine on TNT

**Comment by garfield69** [comment]
the log shows that in response to jackett sending
https://tntracker.org/api/browse?orderC=4&orderD=desc&start=0&length=100
the torrentnetwork site's api server replied with ` "error": "no access"`

I do not have an login for this site so I cannot independently test this.
can you use your browser to login to the TN web site, then try the link above and see if you get the same response?
if you get the same response then this is not a jackett issue.

**Comment by MoeJoe87** [comment]
Hi, Yes i got the same response when i try in browser. So i should let them know about that issue?

**Comment by garfield69** [comment]
yes.
