### ISSUE TITLE
Issue with Iptorrents

### ISSUE THREAD

**Issue by silveringking** [Jackett/Jackett#5418]
Hi for some reason I can't seem to update Iptorrents indexer. Could you help me out?

The error it gives me:

> An error occured while testing this indexer
> Found no results while trying to browse this tracker
> Click here to open an issue on GitHub for this indexer.

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.
