### ISSUE TITLE
I am not able to login as it doesn't show up the image I need to select

### ISSUE THREAD

**Issue by surajitrana1985** [Jackett/Jackett#5419]
I am not able to login as it doesn't show up the image I need to select. Refer the screenshot below:

![image](https://user-images.githubusercontent.com/13241573/59088704-dca35e00-8925-11e9-8567-5426d69d2761.png)

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/2076#issuecomment-499791031
duplicate #2076

**Comment by avijit-dutta** [comment]
I am also facing the same issue. I have reset the Chrome Browser, then also not. Even I have reinstalled the browser still not working. It is not showing the image.

**Comment by garfield69** [comment]
you are looking for browser support.
use google search to look for answers or find a browser support forum.
answering questions of this kind is outside the scope and purpose of this GitHub support site for the Jackett app.

**Comment by RishabhKatiyar** [comment]
What's the resolution?

**Comment by garfield69** [comment]
i don't know what the resolution is. 
this has nothing to do with Jackett which is what this support site is all about.

you have a problem with a web site, and its likely your browser or system that is causing the issue.

try looking for javascript settings that have been disabled, or browser plugins that you have enabled that are blocking security check script, or your antimalware blocking scripts  or some think.

My point is, this is not the place to ask for this kind of help.

**Comment by RishabhKatiyar** [comment]
Don't know why but allowing hon3yhd.com specifically to allow cookies and javascript and then refreshing the page for some time after some minutes of interval fixed the issue.
