### ISSUE TITLE
[blutopia] Exception (blutopia): Login failed: No form found on https://blutopia.xyz/login using form selector form: Parse error (Test)

### ISSUE THREAD

**Issue by joydashy** [Jackett/Jackett#5421]
See title, not much to add.

Jackett Version 0.11.388.0 
Mono JIT compiler version 5.20.1.19

**Comment by garfield69** [comment]
works for me so 
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by joydashy** [comment]
Thanks for the reponse. After re-entering my password in Jackett, the test passes. However, it does take very long, while the other tests are all very fast. Not sure if that is related.
Also did not think I changed my password on the site, so not sure what that's about...
