### ISSUE TITLE
YTS: API url changed (now yts.lt )

### ISSUE THREAD

**Issue by 437studios** [Jackett/Jackett#5422]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

YTS returns a permanently redirected (its now yts.lt not yts.am)
Full Enhanced Log:

`

Jun 07, 2019 07:31:29 AM | Info | Executing action method Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole) - Validation state: Valid
-- | -- | --
Jun 07, 2019 07:31:29 AM | Info | Authorization was successful.
Jun 07, 2019 07:31:29 AM | Debug | Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 07, 2019 07:31:29 AM | Debug | Execution plan of exception filters (in the following order): None
Jun 07, 2019 07:31:29 AM | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter
Jun 07, 2019 07:31:29 AM | Debug | Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 07, 2019 07:31:29 AM | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Jun 07, 2019 07:31:29 AM | Info | Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing action Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)
Jun 07, 2019 07:31:29 AM | Debug | Request successfully matched the route with name '(null)' and template 'api/v2.0/server/Logs'
Jun 07, 2019 07:31:29 AM | Debug | AuthenticationScheme: Cookies was successfully authenticated.
Jun 07, 2019 07:31:29 AM | Debug | The request path /api/v2.0/server/logs does not match a supported file type
Jun 07, 2019 07:31:29 AM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.169:9117/api/v2.0/server/logs?_=1559917804329
Jun 07, 2019 07:31:29 AM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.169:9117/api/v2.0/server/logs?_=1559917804329
Jun 07, 2019 07:31:29 AM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.169:9117/api/v2.0/server/logs?_=1559917804329
Jun 07, 2019 07:31:29 AM | Info | Request starting HTTP/1.1 GET http://192.168.1.169:9117/api/v2.0/server/logs?_=1559917804329
Jun 07, 2019 07:31:27 AM | Info | Request finished in 217.8291ms 500 application/json
Jun 07, 2019 07:31:27 AM | Debug | Connection id "0HLNA53PB95K9" completed keep alive response.
Jun 07, 2019 07:31:27 AM | Debug | The response will be compressed with 'gzip'.
Jun 07, 2019 07:31:27 AM | Error | Jackett.Common.IndexerException: Exception (yts): Count cannot be less than zero. Parameter name: count ---> System.Exception: Parse error ---> System.ArgumentOutOfRangeException: Count cannot be less than zero. Parameter name: count    at System.String.Remove(Int32 startIndex, Int32 count)    at Jackett.Common.Indexers.Yts.<PerformQuery>d__12.MoveNext()    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex)    at Jackett.Common.Indexers.Yts.<PerformQuery>d__12.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Indexers.Yts.<PerformQuery>d__11.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext()    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Indexers.BaseWebIndexer.<ResultsForQuery>d__25.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Services.IndexerManagerService.<TestIndexer>d__18.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Server.Controllers.IndexerApiController.<Test>d__15.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.<Execute>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Server.Middleware.CustomExceptionHandler.<Invoke>d__3.MoveNext()
Jun 07, 2019 07:31:27 AM | Info | Executed action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) in 70.5387ms
Jun 07, 2019 07:31:27 AM | Error | Error on 20190607073127 for YTS.txtSystem.ArgumentOutOfRangeException: Count cannot be less than zero. Parameter name: count    at System.String.Remove(Int32 startIndex, Int32 count)    at Jackett.Common.Indexers.Yts.<PerformQuery>d__12.MoveNext()
Jun 07, 2019 07:31:27 AM | Debug | WebClient(HttpWebClient): Returning MovedPermanently => https://yts.lt/api/v2/list_movies.json?sort=date_added&limit=50
Jun 07, 2019 07:31:27 AM | Debug | WebClient(HttpWebClient).GetString(Url:https://yts.am/api/v2/list_movies.json?sort=date_added&limit=50)
Jun 07, 2019 07:31:27 AM | Info | Executing action method Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) - Validation state: Valid
Jun 07, 2019 07:31:27 AM | Info | Authorization was successful.
Jun 07, 2019 07:31:27 AM | Debug | Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 07, 2019 07:31:27 AM | Debug | Execution plan of exception filters (in the following order): None
Jun 07, 2019 07:31:27 AM | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
Jun 07, 2019 07:31:27 AM | Debug | Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 07, 2019 07:31:27 AM | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Jun 07, 2019 07:31:27 AM | Info | Route matched with {action = "Test", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)
Jun 07, 2019 07:31:27 AM | Debug | Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers/{indexerid}/Test'
Jun 07, 2019 07:31:27 AM | Debug | AuthenticationScheme: Cookies was successfully authenticated.
Jun 07, 2019 07:31:27 AM | Debug | POST requests are not supported
Jun 07, 2019 07:31:27 AM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.169:9117/api/v2.0/indexers/yts/test
Jun 07, 2019 07:31:27 AM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.169:9117/api/v2.0/indexers/yts/test
Jun 07, 2019 07:31:27 AM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.169:9117/api/v2.0/indexers/yts/test
Jun 07, 2019 07:31:27 AM | Info | Request starting HTTP/1.1 POST http://192.168.1.169:9117/api/v2.0/indexers/yts/test  0

`

**Comment by garfield69** [comment]
jackett 0.11.391 uses the new api domain.
