### ISSUE TITLE
[yts] Parse error: Count cannot be less than zero.Parameter name: count (Config)

### ISSUE THREAD

**Issue by zquack** [Jackett/Jackett#5428]
Cannot add YTS as a tracker, throws an error. Log is attached,

[log.txt](https://github.com/Jackett/Jackett/files/3267932/log.txt)

Jackett Version 0.11.388.0

**Comment by garfield69** [comment]
update jackett to v0.11.391

**Comment by AardCrowley** [comment]
YTS changed its url to yts.lt recently, which probably is the reason why. I tried changing it in the settings, and it failed.
