### ISSUE TITLE
JPOPSUKI?

### ISSUE THREAD

**Issue by seanvree** [Jackett/Jackett#543]
Any plans to add this as a tracker?

Thanks!

Good job on this guys!

**Comment by kaso17** [comment]
please send an invite to kaso1717 -at- gmail.com

**Comment by armani316** [comment]
@kaso17 Invites are being offered by users in a class-restricted invites forum of another music tracker that you're on :)

**Comment by kaso17** [comment]
@armani316 Thank you for letting me know ;)
Added with e45b3eaaf1193830fa6dcc33f15e50913bafa587
