### ISSUE TITLE
Movie is in tracker but does not show up in manual search.

### ISSUE THREAD

**Issue by j0s3rubio** [Jackett/Jackett#5439]
Tracker is FileList, movie is I am Mother.  There are a couple of files that match when going to the tracker's website directly, but Jackett's manual search gives no results.  Using category "Any"

Other movies from FileList show up when searching for them though, as far as I can tell, it's this particular movie only?

Any help tracking this issue is appreciated!

Jackett Version 0.11.391.0 without Mono.

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by j0s3rubio** [comment]
Here's the log file:

[ttt.txt](https://github.com/Jackett/Jackett/files/3269762/ttt.txt)

**Comment by garfield69** [comment]
looking at the log you provided, the search returned two titles, both in the Romanian releases category `Filme HD-RO`.

the indexer has an optional config to exclude this category from the results if the `IncludeRomanianReleases` option is not ticked.

does this apply to you?
access your Jackett dashboard, and edit your FileList config and check that option.
![image](https://user-images.githubusercontent.com/6933240/59163705-89652180-8b58-11e9-9f26-fcbb137eec6e.png)
