### ISSUE TITLE
Tracker Request: MovCr

### ISSUE THREAD

**Issue by hemlok89** [Jackett/Jackett#5443]
Hello, can we have https://movcr.tv/ added to the list. It is mainly an Indian tracker with a pretty big collection which is excusive to this site.

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.406

**Comment by ilike2burnthing** [comment]
https://movcr.st/ - Error 521 - Web server is down

**Comment by ilike2burnthing** [comment]
back up
