### ISSUE TITLE
[limetorrents] Exception (limetorrents): The server returned an invalid or unrecognized response.: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by DarkMarkus88** [Jackett/Jackett#5444]
Hi, I get this error with every test I make with every indexer there is.

I got mono version 5.20 en jackett version 0.11.391 (tested 399 same problem)

I have everything behind a reverse proxy with https.

I attached my logifle.

[log.txt](https://github.com/Jackett/Jackett/files/3269262/log.txt)

I removed my DNS, but everything is as is.

Can somebody help me with this?

[EDIT]

Now I disabled my proxy within Jackett and now it works.
My socks5 proxy produces this error, can anyone figure out why?

**Comment by ngosang** [comment]
@DarkMarkus88 I'm closing because that version is old. If you are having problems in the latest version I will reopen the issue.
