### ISSUE TITLE
Hounddawgs

### ISSUE THREAD

**Issue by SirMaggot** [Jackett/Jackett#545]
Hiya.

I don't have any luck trying to add Hounddawgs.
The error is "Configuration failed: Found no results while trying to browse this tracker"
I'm using v0.7.418 (tried the release before that yesterday)
Torrentdays and Demonoid is working.

Thanks a lot for this program, it's making my life a bit easier :)

**Comment by supremacy2k** [comment]
I got HD running on 0.7.411 with no problems, same as DB.

**Comment by kaso17** [comment]
unfortunately registration is limited to Denmatark, Norway, Sweden, and Finland. Can someone with an whitelisted IP please contact me at kaso1717 -at- gmail.com to help me getting an account to work on this issue?

**Comment by SirMaggot** [comment]
Did you have time to check? Your account tested and it's working :)

**Comment by kaso17** [comment]
I've been busy with slightly bigger core changes.
For me Hounddawgs is working perfectly fine.
Can you please post a log with tracing enabled (-t option)
