### ISSUE TITLE
[req] MejorTorrent.pw Spanish Public site for Movies and TV

### ISSUE THREAD

**Issue by RicardoVelaC** [Jackett/Jackett#5452]
is a public spanish torrent site with search, https://mejortorrent.pw/

**Comment by garfield69** [comment]
the search results display one entry for each movie or series available.
the site's download links are buried in the details page of each search results entry.

the details page contains one or more download links.

This indexer will require c# as the cardigann processor cannot handle multiple download links on the details page.

**Comment by aferpa94** [comment]
I think this is not needed, mejortorrent.pw is not as updated as descargas2020.org, descargas2020 works with newpct definition if you change the domain, but torrents with descargas2020 are found but not downloaded (empty torrent file with 504 error).

**Comment by DAVIZINH0** [comment]
Hello, i use newpct with domain changed (descargas2020.org) and list correctly but not download the .torrent because is empty. Can i help with some log o something?

**Comment by garfield69** [comment]
@DAVIZINH0  no. this ticket tracks the progress/rejection of the implementation of the mejortorrent.pw indexer.
if you have a problem with newpct, open a new issue ticket and provide the full enhanced logs.

**Comment by snamds** [comment]
https://github.com/Jackett/Jackett/pull/5485

**Comment by JorTurFer** [comment]
https://mejortorrent.pw/ is broken

**Comment by RicardoVelaC** [comment]
The new URL is `https://www.mejortorrents.net/` and it's work ok on Jackett
