### ISSUE TITLE
[transmithenet] Exception (transmithenet): 该字符串未被识别为有效的 DateTime。: Parse error (Config)

### ISSUE THREAD

**Issue by waldens** [Jackett/Jackett#5456]
**Feature request or Bug?**
Seems a bug.

**Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.**
Checked everything I can remember and my account and trackers itself are both good, and I've login in browser.

**latest version of Jackett?**
Yes, using Jackett Version 0.11.403.0, newest version at moment.

**full enhanced log must be included?**
As the reproduce steps the GIF below shows, I believe this seems an issue that can be easily reproduced on other's computer. If not, I will provide log later.

**Jackett version**:  Jackett Version 0.11.403.0
Also tested on v0.11.391.0 and same issue happens.

-------------------------------

GIF: http://tva1.sinaimg.cn/large/0060lm7Tly1g3vlkwb1ung30rn0gyb2e.gif
Reproduce Steps: Add indexer -> search nebulance -> configure -> input Username and Password -> Okay -> wait a second and the error pops out.

![](https://ae01.alicdn.com/kf/HTB1_6h.coKF3KVjSZFE760ExFXas.png)

**Comment by garfield69** [comment]
I don't have an account on nebulance (transmitthenet) so I cant research this.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by waldens** [comment]
@garfield69 Thanks for this quick reply. Here the log is: :_highfive: 
https://notepad.pw/share/ri78b2ia0

**Comment by garfield69** [comment]
your log shows that the date field `<span class="time" title="47 mins ago">Jun 10 2019, 08:31</span>` seems to have changed. 
the c# indexer is expecting `Jun 10 2019, 08:31` to be in the `title=` attribute, but is now found in the text field.
so I've changed the selector, lets see if I have got it right.
Try out jackett pre-release v0.11.405 and report. thanks.

**Comment by waldens** [comment]
@garfield69 Successfully configured Nebulance. Works like a charm! 
Many thanks for your quick and warm help. Have a nice day! <img alt="ghe-emoji" title=":_fist_bump:" src="https://cloud.githubusercontent.com/assets/136959/13559365/0fe4e2a2-e3d9-11e5-9b10-32de5d5988a2.gif">

**Comment by weirdcrap** [comment]
Wanted to let people who are still seeing this issue know that there is a new setting on your Nebulance profile that affects the DateTime issue.

Just went to my profile and discovered my "Time Style" was set to "Display times as time since (date and time is displayed as tooltip)". This was making jackett fail with the same error as OP.

By changing that setting to "Display times as date and time (time since is displayed as tooltip)" I was able to resolve the problem myself.
