### ISSUE TITLE
Newpct fails with descargas2020.org

### ISSUE THREAD

**Issue by DAVIZINH0** [Jackett/Jackett#5460]
Hello,
I use jackett in docker (Version 0.11.404.0)
I have newpct indexer configured with https://www.descargas2020.org
The search works but the .torrent dont download, if i use it with medusa the error is "torrent file is empty".
If i enter in the web i can download the .torrent perfectly (with a lot of advertising :-P )

This is the enhanced log of the serarch and try to download this chapter:
Warrior.​S01E10.​HDTV.​Español.​Spanish
and never download

We are some people affected with this problem
The log:
[log.txt](https://github.com/Jackett/Jackett/files/3273691/log.txt)

**Comment by garfield69** [comment]
if I use newpct with the default site link https://pctnew.site/ I can download .torrents fine.
any reason you cannot use the default site link?

**Comment by garfield69** [comment]
ok I see gateway timeouts on pctnew.site so its being hammered. some of my search and downloads fail as well.

but https://www.descargas2020.org is no good as there is no .torrent link available.
all the click bait links cannot be resolved by jackett before getting to the real download link.
```
Jun 11, 2019 10:39:05 AM Warn Newpct - download link not found in https://torrentlocura.com/descargar/serie/warrior/temporada-1/capitulo-10/
Jun 11, 2019 10:39:05 AM Error Error downloading newpct https://descargas2020.org/descargar/serie/warrior/temporada-1/capitulo-10/
```
is there another domain that is legit?

**Comment by lmctheboss** [comment]
I have the same issue of @DAVIZINH0.
Since the change of the site extension to .org I was downloading perfectly.
If I go to the site manually it download the .torrent perfectly.

**Comment by snamds** [comment]
https://github.com/Jackett/Jackett/pull/5485

Made it to work with descargas2020.org
This indexer is becoming so complex ….

**Comment by DAVIZINH0** [comment]
thanks a lot!!!. works again!!

**Comment by aferpa94** [comment]
You rock @snamds , works again perfectly!
