### ISSUE TITLE
Jackett with One Piece on AnimeBytes shows no results.

### ISSUE THREAD

**Issue by varoOP** [Jackett/Jackett#5461]
If one piece with the episode number is searched on jackett no results show up. 
Example : 
![image](https://user-images.githubusercontent.com/46842159/59242340-c862a800-8c28-11e9-90f5-2321fbfbd9ec.png)
So One piece searched with episode number shows no result. 
If only one piece is searched we get results : 
Example : 
![image](https://user-images.githubusercontent.com/46842159/59242424-2099aa00-8c29-11e9-9106-6e93dfb03f5c.png)

Also, if the prefix E0 option is enabled, we get 4 digit episode number which will confuse sonarr : 
Example : 
![image](https://user-images.githubusercontent.com/46842159/59242697-2cd23700-8c2a-11e9-9c26-03fe98bfd567.png)

Please make one piece search results appear even with the episode number because that is the way sonarr searches and currently no results show up when sonarr searches for one piece episodes! 
Thank you!

**Comment by garfield69** [comment]
included in jackett pre-release 0.11.626
