### ISSUE TITLE
[req]OXTorrent - New public french tracker

### ISSUE THREAD

**Issue by crashseb** [Jackett/Jackett#5465]
Hi, 

This is a new french tracker : https://wwv.oxtorrent.com/

perhaps a gktorrent clone ? 

thx if you can add this one ;)

**Comment by garfield69** [comment]
https://www.smartorrent.tv/ is now redirecting to https://www.gktorrent.biz/
as is the old legacylink https://wwv.oxtorrent.com/
any know if the site has a new domain, or has it been taken over by the gktorrent crowd (like cpasbein  apparently has been)?

**Comment by garfield69** [comment]
https://www.oxtorrent.com/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
online.

**Comment by ilike2burnthing** [comment]
Site is still up, but affected by #8840

**Comment by garfield69** [comment]
https://www.oxtorrent.tv/ returning Error 522 - The tracker seems to be down

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.oxtorrent.be/ returns
![image](https://user-images.githubusercontent.com/6933240/154189710-26fb9b60-a543-4823-97f2-11c82abca817.png)

**Comment by garfield69** [comment]
how did you find the new domain?

**Comment by ilike2burnthing** [comment]
Click the red text, it redirects to https://oxtorrent-support.com/ where it shows the new domain is *.re
