### ISSUE TITLE
Torrentquest as a new tracker

### ISSUE THREAD

**Issue by ghost** [Jackett/Jackett#5468]
I have always used https://torrentquest.com but I can't add it to Jackett. Maybe any future plans to add this one because it is a really good one.

**Comment by MrNicker9** [comment]
I'm kinda new to this. Do I have to reinstall Jackett or how do i get this new tracker in my list?

**Comment by garfield69** [comment]
first I have to publish the next jackett release that will contain the new indexer I built.
to do that I first have to wait for the github bot to build all the jackett packages.

I will post an update when the release is available,  after which you will be able to either:
1. update using the check-for-updates button on your jackett dashboard
or
2. you download the relevant build from https://github.com/Jackett/Jackett/releases or where ever,  and install it manually yourself.

**Comment by MrNicker9** [comment]
Okay thanks a lot sir!!

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.413
if this is your first time using the **check for updates** button, you may first need to check the **update to pre-release** check box, followed by clicking the **apply server settings** button.
Once the page is refreshed you can then do the update.

**Comment by MrNicker9** [comment]
In Jackett i've got the Torrentquest entry and it can connect with the test button. However in Sonarr I get a time out after a while. Is there something to do here or?

**Comment by garfield69** [comment]
Try changing the Sonarr indexer categories to 2000,5000 instead of the default 5030,5040

**Comment by MrNicker9** [comment]
Hmm, still no luck, keep getting the timeout

**Comment by garfield69** [comment]
works for me.
to confirm, the time out is during the set up of the sonarr indexer while its doing the test or can you save the indexer, and are you talking about when you actually go searching for tv episodes on sonarr?

**Comment by garfield69** [comment]
works for me.
![image](https://user-images.githubusercontent.com/6933240/59330224-0228d100-8d45-11e9-80dc-f249bcffbd9a.png)
![image](https://user-images.githubusercontent.com/6933240/59330183-e4f40280-8d44-11e9-9f00-0451996cb25a.png)

**Comment by MrNicker9** [comment]
No, I can't add it to Sonarr, if I click SAVE, it keeps loading until i get the timeout error

**Comment by garfield69** [comment]
I'm on sonarr 2.0.0.5322
are you on the beta v3 version of Sonarr or the stable v2 version?

**Comment by MrNicker9** [comment]
Alright it worked, I figured out my issue i think, in the URL field I was using my dynamic dns name instead of local IP address. Also the default 5030 categories didn't work, but the 5000 and 2000 did work.

**Comment by garfield69** [comment]
removed at the request of the author. See https://github.com/Jackett/Jackett/pull/10347#issue-530982565 for more details.
