### ISSUE TITLE
Issue with 0.11.409 related to CsQuery

### ISSUE THREAD

**Issue by fryfrog** [Jackett/Jackett#5471]
```
An error occured while testing this indexer
Exception (revolutiontt): Could not load file or assembly 'CsQuery, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The module was expected to contain an assembly manifest.: Could not load file or assembly 'CsQuery, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The module was expected to contain an assembly manifest.
```

Upgrading to 0.11.409 and they fail, downgrade to .404 and they're fine, re-upgrade and they fail again. Failed examples are AnimeTorrents, HD-Torrents, IPTorrents, PreToMe, RevolutionTT. Failed trackers are consistent between upgrades/restarts.

**Comment by fryfrog** [comment]
It doesn't seem like there are any obvious commits between .404 and .409, they all seem like adding new trackers or fixing existing ones... :/

**Comment by garfield69** [comment]
probably related to #5208

**Comment by fryfrog** [comment]
Odd, I don't use the built in updater. I'm actually the maintainer of the Arch Linux AUR package and so each "update" is more like a full re-install. I wonder if some files are missed? I'll compare a .404 to .409 package and see if there are any differences.

I am using the .NET binary, not Mono.

What logs or details can I provide in addition? Should I close this one and continue in the other issue?

**Comment by garfield69** [comment]
lets keep this one open for now. 
I'm not a c# dev, so we really need @flightlevel  and/or @kaso17  to pitch in and take a look.
as for logs, the complete set of log*.txt and updater*.txt in the `~/.config/Jackett/` folder may be of use.

**Comment by fryfrog** [comment]
I rebuilt both .404 and .409 packages from scratch and ran `diff -BurN` on extracted folders of my packages to compare them and as expected, its basically nothing. I then stopped Jackett, nuked log files and upgraded from 404 -> 409. Of course now it works fine.

http://sprunge.us/U3ayVH

I have no idea. :/

**Comment by garfield69** [comment]
since it can't be replicated and the logs are now gone I see no point keeping this open.
