### ISSUE TITLE
can't add Danishbits as indexer in jackett

### ISSUE THREAD

**Issue by Coax88** [Jackett/Jackett#5475]
Hi

i having problems adding Danishbits as indexer to jackett on my new seedbox. its just loading and comes with and error after some while. 
had no problems on my other seedbox which was running an older version of jackett.
 
error message:
 An error occured while updating this indexer
Exception (danishbits): The operation was canceled.: The operation was canceled.

Jackett Version 0.11.409.0

**Comment by ngosang** [comment]
@Coax88 is this fixed in latest version?

**Comment by Coax88** [comment]
> @Coax88 is this fixed in latest version?
I'm running v. 0.11.589.0 don't know if it is the latest one, but it works now

**Comment by ngosang** [comment]
Your version is very old => https://github.com/Jackett/Jackett/releases
Since it's working I'm closing.
