### ISSUE TITLE
[REQ ilovetorrents/gimmepeeps.com

### ISSUE THREAD

**Issue by L33B0B** [Jackett/Jackett#548]
Hi,

ILT is no longer known as ilovetorrents.. its now gimmepeeps.com. Is it possible for this to be changed?

Thanks

**Comment by savahu** [comment]
This is a PAID torrent site, which I think Jackett should not want to support.

**Comment by kaso17** [comment]
@L33B0B I guess nobody has access to it.
@flightlevel and @JigSawFr what's the Jackett policy with trackers requiring payment?

My opinion:
I would never use such an offer but I would have no problem if Jackett keeps supporting them (If the same opinion regarding public trackers)

**Comment by flightlevel** [comment]
I don't like these sort of trackers but if the COMMUNITY wants to maintain it, ok with it being included.
Maybe @lowet84 can fix as he implemented it, otherwise @L33B0B why not have a go yourself if you are the one using it

**Comment by lowet84** [comment]
I implemented ILT before the change. I don't like that kind of tracker either and i suggest that we drop the suppport for ILT. That is unless someone else wants to fix it.

**Comment by kaso17** [comment]
fixed with #988
