### ISSUE TITLE
[error] Jackett keeps crashing

### ISSUE THREAD

**Issue by Kennydd88** [Jackett/Jackett#5495]
Hey Guys,

For some reason my jackett doens't seem to be working. It keeps giving the following error:

Jun 16 00:02:37 raspberrypi mono[3179]: 06-16 00:02:37 Info Starting Jackett v0.11.388.0
Jun 16 00:02:38 raspberrypi mono[3179]: 06-16 00:02:38 Error System.IO.FileNotFoundException: Could not load file or assembly 'Autofac, Version=4.9.2.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies.
Jun 16 00:02:38 raspberrypi mono[3179]: File name: 'Autofac, Version=4.9.2.0, Culture=neutral, PublicKeyToken=17863af14b0044da'
Jun 16 00:02:38 raspberrypi mono[3179]:   at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
Jun 16 00:02:38 raspberrypi mono[3179]:   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <6649516e5b3542319fb262b421af0adb>:0
Jun 16 00:02:38 raspberrypi mono[3179]: --- End of stack trace from previous location where exception was thrown ---
Jun 16 00:02:38 raspberrypi mono[3179]:   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices (Microsoft.Extensions.DependencyInjection.IServiceCollection services) [0x00028] in <127e718ac42e4542a71b54cec3ef156b>:0
Jun 16 00:02:38 raspberrypi mono[3179]:   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices () [0x0000e] in <127e718ac42e4542a71b54cec3ef156b>:0
Jun 16 00:02:38 raspberrypi systemd[1]: jackett.service: Main process exited, code=exited, status=1/FAILURE
Jun 16 00:02:38 raspberrypi systemd[1]: jackett.service: Unit entered failed state.
Jun 16 00:02:38 raspberrypi systemd[1]: jackett.service: Failed with result 'exit-code'.
Jun 16 00:02:43 raspberrypi systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
Jun 16 00:02:43 raspberrypi systemd[1]: Stopped Jackett Daemon.
Jun 16 00:02:43 raspberrypi systemd[1]: Started Jackett Daemon.

Jackett version: Jackett v0.11.388.0
Mono version: Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 09:08:44 UTC 2019)

Sorry if the problem is obvious i'm a total noob. Thanks in advance for the help.
[updater.txt](https://github.com/Jackett/Jackett/files/3293599/updater.txt)
[log.txt](https://github.com/Jackett/Jackett/files/3293600/log.txt)

**Comment by Kennydd88** [comment]
any update on this matter or steps that i can take?

**Comment by rrrevin** [comment]
My guess is this is the same as https://github.com/Jackett/Jackett/issues/5208

**Comment by ngosang** [comment]
@Kennydd88 Try this fix => https://github.com/Jackett/Jackett/issues/5208#issuecomment-547709864
