### ISSUE TITLE
[transmithenet] Exception (transmithenet): String was not recognized as a valid DateTime.: Parse error (Config)

### ISSUE THREAD

**Issue by mrberko** [Jackett/Jackett#5501]
I added Nebulance.io as a tracker a couple of months ago. I noticed sonarr couldn't connect to it as of recently so I went to Jackett to see if there was a problem. As the test functionality didn't pass on Nebulance.io,

I tried to re-add it. After having inserted my username and pass, and pressing "okay", I'm getting the following error: " An error occured while updating this indexer
Exception (transmithenet): String was not recognized as a valid DateTime.: Parse error"

**Comment by mrberko** [comment]
I accidentally posted an earlier thread with the same subject title which is why this was probably flagged as a duplicate.

**Comment by garfield69** [comment]
duplicate #5496 
logon to the site directly with your browser and set 
Username > Settings > Time style > Display times as date and time (time since is displayed as tooltip)
