### ISSUE TITLE
[REQ] Add Anti-Captcha From API Providers

### ISSUE THREAD

**Issue by xfouloux** [Jackett/Jackett#5504]
Hi,

some trackers have captcha image, or even recaptcha (metal iplay ro for example, torrenting too)
And after you configure tracker and it has to relogin, it won't work as captcha challenge is not solved this time.

Can you implement https://github.com/AdminAnticaptcha/anticaptcha-csharp from https://anti-captcha.com/apidoc/image ??

Bottom page of jackett would ask for Captcha provider and API Key

Same thing has been implemented in Bazarr for addic7ed recaptcha issue, they have this API, and death by captcha too.

![image](https://user-images.githubusercontent.com/9778409/59647527-38dc6c80-91c7-11e9-8f06-bc804bf1bef0.png)

Thanks !

**Comment by burkasaurusrex** [comment]
Agreed that this would be amazing

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/8245#issue-602389554

**Comment by xfouloux** [comment]
mostly thinking of tracker that need imagecaptcha at login frequently, metal iplay ro for example, some other issue was about torrentccf #6876
i'm more than happy to provide my anti-captcha key for testing, this would be a huge improvment =) !

**Comment by ngosang** [comment]
We are working on externalize Cloudflare/Captcha resolvers in this PR. #9029

**Comment by ilike2burnthing** [comment]
@ngosang close this?
