### ISSUE TITLE
[Channelx] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by goodpunk6** [Jackett/Jackett#5509]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

The site is accessible but jackett doesn't see it

**Comment by garfield69** [comment]
works for me.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by goodpunk6** [comment]
Unfortunately, there is nothing in that linux directory.

**Comment by garfield69** [comment]
what flavour of jackett are you running and what version?

**Comment by goodpunk6** [comment]
i'm unsure of the "flavor" but I am on - Jackett Version 0.11.115.0

**Comment by garfield69** [comment]
by flavour I mean which jackett package flavour did you install, AMDx64, ARM32, ARM64,  MONO, etc.
but that it not relevant now.
your version 0.11.115 is out of date.
Update your jackett to the latest version (current full version is v0.11.420, latest pre-release is v0.11.432 and you should be able to get results from channelx again.

**Comment by Boxer1990** [comment]
Those having issues will need to re-enter their credentials into jackett again due to an update!

Should be fine from that point on.

**Comment by godloth** [comment]
Hello guys, i,ve been struggling for a while with this error as well, it started for a few french indexers and now none of them works. 
The latest that i'm trying to get to work is sharewood.tv.

I'm running the latest version of jackett from June 13 ( Linuxserver.io version:- v0.11.420-ls26 Build-date:- 2019-06-13T23:13:51+00:00
)
there is seems to have a lot of parsing errors in my logs, see attached file 

let me know if you need anything else 
[jackettlog.txt](https://github.com/Jackett/Jackett/files/3317867/jackettlog.txt)

**Comment by garfield69** [comment]
@godloth  your jackett 0.11.420 is out of date. the sharewood.tv site changed their category selector and jackett beginning with 0.11.431 have the fix. current latest jackett is 0.11.441
