### ISSUE TITLE
[1337x] Exception (1337x): Resource temporarily unavailable: Resource temporarily unavailable (Test)

### ISSUE THREAD

**Issue by Goundski** [Jackett/Jackett#5510]
Jackett Version 0.11.432.0 
Certification validation failed:
Can't access any Index. All give same error.
I can access the index site directly via my browser.
I have upgraded to the latest version and moved away from mono to arm7.
Below is the Log:

un 19, 2019 08:27:20 PM | Info | Executing action method Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett) - Validation state: Valid
-- | -- | --
Jun 19, 2019 08:27:20 PM | Info | Executing action method Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett) - Validation state: Valid
Jun 19, 2019 08:27:20 PM | Info | Authorization was successful.
Jun 19, 2019 08:27:20 PM | Info | Authorization was successful.
Jun 19, 2019 08:27:20 PM | Debug | Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 19, 2019 08:27:20 PM | Debug | Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 19, 2019 08:27:20 PM | Debug | Execution plan of exception filters (in the following order): None
Jun 19, 2019 08:27:20 PM | Debug | Execution plan of exception filters (in the following order): None
Jun 19, 2019 08:27:20 PM | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter
Jun 19, 2019 08:27:20 PM | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter
Jun 19, 2019 08:27:20 PM | Debug | Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 19, 2019 08:27:20 PM | Debug | Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 19, 2019 08:27:20 PM | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Jun 19, 2019 08:27:20 PM | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Jun 19, 2019 08:27:20 PM | Info | Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing action Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)
Jun 19, 2019 08:27:20 PM | Info | Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing action Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)
Jun 19, 2019 08:27:20 PM | Debug | Request successfully matched the route with name '(null)' and template 'api/v2.0/server/Logs'
Jun 19, 2019 08:27:20 PM | Debug | Request successfully matched the route with name '(null)' and template 'api/v2.0/server/Logs'
Jun 19, 2019 08:27:20 PM | Debug | AuthenticationScheme: Cookies was successfully authenticated.
Jun 19, 2019 08:27:20 PM | Debug | AuthenticationScheme: Cookies was successfully authenticated.
Jun 19, 2019 08:27:20 PM | Debug | The request path /api/v2.0/server/logs does not match a supported file type
Jun 19, 2019 08:27:20 PM | Debug | The request path /api/v2.0/server/logs does not match a supported file type
Jun 19, 2019 08:27:20 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/api/v2.0/server/logs?_=1560971061975
Jun 19, 2019 08:27:20 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/api/v2.0/server/logs?_=1560971061975
Jun 19, 2019 08:27:20 PM | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=jackett_v0.11.432.0)
Jun 19, 2019 08:27:20 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/api/v2.0/server/logs?_=1560971061975
Jun 19, 2019 08:27:20 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/api/v2.0/server/logs?_=1560971061975
Jun 19, 2019 08:27:20 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/api/v2.0/server/logs?_=1560971061975
Jun 19, 2019 08:27:20 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/api/v2.0/server/logs?_=1560971061975
Jun 19, 2019 08:27:20 PM | Info | Request starting HTTP/1.1 GET http://192.168.1.105:9117/api/v2.0/server/logs?_=1560971061975
Jun 19, 2019 08:27:20 PM | Info | Request starting HTTP/1.1 GET http://192.168.1.105:9117/api/v2.0/server/logs?_=1560971061975
Jun 19, 2019 08:27:19 PM | Error | On attempt 2 checking for results from RARBG: Resource temporarily unavailable
Jun 19, 2019 08:27:19 PM | Info | Request finished in 675.5347ms 200 image/png
Jun 19, 2019 08:27:19 PM | Info | Request finished in 675.5347ms 200 image/png
Jun 19, 2019 08:27:19 PM | Debug | Connection id "0HLNKP6I4962C" completed keep alive response.
Jun 19, 2019 08:27:19 PM | Debug | Connection id "0HLNKP6I4962C" completed keep alive response.
Jun 19, 2019 08:27:19 PM | Info | Request finished in 532.2423ms 200 image/png
Jun 19, 2019 08:27:19 PM | Info | Request finished in 532.2423ms 200 image/png
Jun 19, 2019 08:27:19 PM | Info | Sending file. Request path: '/images/sort_both.png'. Physical path: '/opt/Jackett/Content/images/sort_both.png'
Jun 19, 2019 08:27:19 PM | Info | Sending file. Request path: '/images/sort_both.png'. Physical path: '/opt/Jackett/Content/images/sort_both.png'
Jun 19, 2019 08:27:19 PM | Debug | Connection id "0HLNKP6I4962D" completed keep alive response.
Jun 19, 2019 08:27:19 PM | Debug | Connection id "0HLNKP6I4962D" completed keep alive response.
Jun 19, 2019 08:27:19 PM | Info | Sending file. Request path: '/images/sort_asc.png'. Physical path: '/opt/Jackett/Content/images/sort_asc.png'
Jun 19, 2019 08:27:19 PM | Info | Sending file. Request path: '/images/sort_asc.png'. Physical path: '/opt/Jackett/Content/images/sort_asc.png'
Jun 19, 2019 08:27:18 PM | Debug | Response compression is not enabled for the Content-Type 'image/png'.
Jun 19, 2019 08:27:18 PM | Debug | Response compression is not enabled for the Content-Type 'image/png'.
Jun 19, 2019 08:27:18 PM | Debug | Response compression is not enabled for the Content-Type 'image/png'.
Jun 19, 2019 08:27:18 PM | Debug | Response compression is not enabled for the Content-Type 'image/png'.
Jun 19, 2019 08:27:18 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/images/sort_asc.png
Jun 19, 2019 08:27:18 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/images/sort_asc.png
Jun 19, 2019 08:27:18 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/images/sort_asc.png
Jun 19, 2019 08:27:18 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/images/sort_asc.png
Jun 19, 2019 08:27:18 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/images/sort_asc.png
Jun 19, 2019 08:27:18 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/images/sort_asc.png
Jun 19, 2019 08:27:18 PM | Info | Request starting HTTP/1.1 GET http://192.168.1.105:9117/images/sort_asc.png
Jun 19, 2019 08:27:18 PM | Info | Request starting HTTP/1.1 GET http://192.168.1.105:9117/images/sort_asc.png
Jun 19, 2019 08:27:18 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/images/sort_both.png
Jun 19, 2019 08:27:18 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/images/sort_both.png
Jun 19, 2019 08:27:18 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/images/sort_both.png
Jun 19, 2019 08:27:18 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/images/sort_both.png
Jun 19, 2019 08:27:18 PM | Info | Request finished in 917.0306ms 200 image/x-icon
Jun 19, 2019 08:27:18 PM | Info | Request finished in 917.0306ms 200 image/x-icon
Jun 19, 2019 08:27:18 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/images/sort_both.png
Jun 19, 2019 08:27:18 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/images/sort_both.png
Jun 19, 2019 08:27:18 PM | Debug | Connection id "0HLNKP6I4962D" completed keep alive response.
Jun 19, 2019 08:27:18 PM | Debug | Connection id "0HLNKP6I4962D" completed keep alive response.
Jun 19, 2019 08:27:18 PM | Info | Request starting HTTP/1.1 GET http://192.168.1.105:9117/images/sort_both.png
Jun 19, 2019 08:27:18 PM | Info | Request starting HTTP/1.1 GET http://192.168.1.105:9117/images/sort_both.png
Jun 19, 2019 08:27:18 PM | Info | Sending file. Request path: '/favicon.ico'. Physical path: '/opt/Jackett/Content/favicon.ico'
Jun 19, 2019 08:27:18 PM | Info | Sending file. Request path: '/favicon.ico'. Physical path: '/opt/Jackett/Content/favicon.ico'
Jun 19, 2019 08:27:18 PM | Info | Request finished in 561.9245ms 200 application/json; charset=utf-8
Jun 19, 2019 08:27:18 PM | Info | Request finished in 561.9245ms 200 application/json; charset=utf-8
Jun 19, 2019 08:27:18 PM | Debug | Connection id "0HLNKP6I4962C" completed keep alive response.
Jun 19, 2019 08:27:18 PM | Debug | Connection id "0HLNKP6I4962C" completed keep alive response.
Jun 19, 2019 08:27:18 PM | Info | Executed action Jackett.Server.Controllers.IndexerApiController.Indexers (jackett) in 543.3743ms
Jun 19, 2019 08:27:18 PM | Info | Executed action Jackett.Server.Controllers.IndexerApiController.Indexers (jackett) in 543.3743ms
Jun 19, 2019 08:27:17 PM | Debug | Response compression is not enabled for the Content-Type 'image/x-icon'.
Jun 19, 2019 08:27:17 PM | Debug | Response compression is not enabled for the Content-Type 'image/x-icon'.
Jun 19, 2019 08:27:17 PM | Debug | The response will be compressed with 'gzip'.
Jun 19, 2019 08:27:17 PM | Debug | The response will be compressed with 'gzip'.
Jun 19, 2019 08:27:17 PM | Info | Executing ObjectResult, writing value of type 'System.Linq.Enumerable+SelectIPartitionIterator`2[[Jackett.Common.Indexers.IIndexer, Jackett.Common, Version=0.11.432.0, Culture=neutral, PublicKeyToken=null],[Jackett.Common.Models.DTO.Indexer, Jackett.Common, Version=0.11.432.0, Culture=neutral, PublicKeyToken=null]]'.
Jun 19, 2019 08:27:17 PM | Info | Executing ObjectResult, writing value of type 'System.Linq.Enumerable+SelectIPartitionIterator`2[[Jackett.Common.Indexers.IIndexer, Jackett.Common, Version=0.11.432.0, Culture=neutral, PublicKeyToken=null],[Jackett.Common.Models.DTO.Indexer, Jackett.Common, Version=0.11.432.0, Culture=neutral, PublicKeyToken=null]]'.
Jun 19, 2019 08:27:17 PM | Debug | Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter' and content type 'application/json' to write the response.
Jun 19, 2019 08:27:17 PM | Debug | Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter' and content type 'application/json' to write the response.
Jun 19, 2019 08:27:17 PM | Debug | Attempting to select the first formatter in the output formatters list which can write the result.
Jun 19, 2019 08:27:17 PM | Debug | Attempting to select the first formatter in the output formatters list which can write the result.
Jun 19, 2019 08:27:17 PM | Debug | Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
Jun 19, 2019 08:27:17 PM | Debug | Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
Jun 19, 2019 08:27:17 PM | Debug | No information found on request to perform content negotiation.
Jun 19, 2019 08:27:17 PM | Debug | No information found on request to perform content negotiation.
Jun 19, 2019 08:27:17 PM | Debug | List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter
Jun 19, 2019 08:27:17 PM | Debug | List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter
Jun 19, 2019 08:27:17 PM | Info | Executed action method Jackett.Server.Controllers.IndexerApiController.Indexers (jackett), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 0.1715ms.
Jun 19, 2019 08:27:17 PM | Info | Executed action method Jackett.Server.Controllers.IndexerApiController.Indexers (jackett), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 0.1715ms.
Jun 19, 2019 08:27:17 PM | Info | Executing action method Jackett.Server.Controllers.IndexerApiController.Indexers (jackett) - Validation state: Valid
Jun 19, 2019 08:27:17 PM | Info | Executing action method Jackett.Server.Controllers.IndexerApiController.Indexers (jackett) - Validation state: Valid
Jun 19, 2019 08:27:17 PM | Info | Authorization was successful.
Jun 19, 2019 08:27:17 PM | Info | Authorization was successful.
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of exception filters (in the following order): None
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of exception filters (in the following order): None
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Jun 19, 2019 08:27:17 PM | Info | Route matched with {action = "Indexers", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Indexers (jackett)
Jun 19, 2019 08:27:17 PM | Info | Route matched with {action = "Indexers", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Indexers (jackett)
Jun 19, 2019 08:27:17 PM | Debug | Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers'
Jun 19, 2019 08:27:17 PM | Debug | Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers'
Jun 19, 2019 08:27:17 PM | Debug | AuthenticationScheme: Cookies was successfully authenticated.
Jun 19, 2019 08:27:17 PM | Debug | AuthenticationScheme: Cookies was successfully authenticated.
Jun 19, 2019 08:27:17 PM | Debug | The request path /api/v2.0/indexers does not match a supported file type
Jun 19, 2019 08:27:17 PM | Debug | The request path /api/v2.0/indexers does not match a supported file type
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/api/v2.0/indexers?_=1560971061974
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/api/v2.0/indexers?_=1560971061974
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/api/v2.0/indexers?_=1560971061974
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/api/v2.0/indexers?_=1560971061974
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/api/v2.0/indexers?_=1560971061974
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/api/v2.0/indexers?_=1560971061974
Jun 19, 2019 08:27:17 PM | Info | Request starting HTTP/1.1 GET http://192.168.1.105:9117/api/v2.0/indexers?_=1560971061974
Jun 19, 2019 08:27:17 PM | Info | Request starting HTTP/1.1 GET http://192.168.1.105:9117/api/v2.0/indexers?_=1560971061974
Jun 19, 2019 08:27:17 PM | Info | Request finished in 72.5735ms 200 application/json; charset=utf-8
Jun 19, 2019 08:27:17 PM | Info | Request finished in 72.5735ms 200 application/json; charset=utf-8
Jun 19, 2019 08:27:17 PM | Debug | Connection id "0HLNKP6I4962F" completed keep alive response.
Jun 19, 2019 08:27:17 PM | Debug | Connection id "0HLNKP6I4962F" completed keep alive response.
Jun 19, 2019 08:27:17 PM | Info | Request finished in 64.5111ms 404
Jun 19, 2019 08:27:17 PM | Info | Request finished in 64.5111ms 404
Jun 19, 2019 08:27:17 PM | Info | Executed action Jackett.Server.Controllers.ServerConfigurationController.Config (jackett) in 34.2684ms
Jun 19, 2019 08:27:17 PM | Info | Executed action Jackett.Server.Controllers.ServerConfigurationController.Config (jackett) in 34.2684ms
Jun 19, 2019 08:27:17 PM | Debug | Connection id "0HLNKP6I4962H" completed keep alive response.
Jun 19, 2019 08:27:17 PM | Debug | Connection id "0HLNKP6I4962H" completed keep alive response.
Jun 19, 2019 08:27:17 PM | Debug | The response will be compressed with 'gzip'.
Jun 19, 2019 08:27:17 PM | Debug | The response will be compressed with 'gzip'.
Jun 19, 2019 08:27:17 PM | Info | Executing ObjectResult, writing value of type 'Jackett.Common.Models.DTO.ServerConfig'.
Jun 19, 2019 08:27:17 PM | Info | Executing ObjectResult, writing value of type 'Jackett.Common.Models.DTO.ServerConfig'.
Jun 19, 2019 08:27:17 PM | Debug | Request did not match any routes
Jun 19, 2019 08:27:17 PM | Debug | Request did not match any routes
Jun 19, 2019 08:27:17 PM | Debug | Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter' and content type 'application/json' to write the response.
Jun 19, 2019 08:27:17 PM | Debug | Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter' and content type 'application/json' to write the response.
Jun 19, 2019 08:27:17 PM | Debug | Attempting to select the first formatter in the output formatters list which can write the result.
Jun 19, 2019 08:27:17 PM | Debug | Attempting to select the first formatter in the output formatters list which can write the result.
Jun 19, 2019 08:27:17 PM | Debug | Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
Jun 19, 2019 08:27:17 PM | Debug | Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
Jun 19, 2019 08:27:17 PM | Debug | No information found on request to perform content negotiation.
Jun 19, 2019 08:27:17 PM | Debug | No information found on request to perform content negotiation.
Jun 19, 2019 08:27:17 PM | Debug | List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter
Jun 19, 2019 08:27:17 PM | Debug | List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter
Jun 19, 2019 08:27:17 PM | Info | Executed action method Jackett.Server.Controllers.ServerConfigurationController.Config (jackett), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 0.3339ms.
Jun 19, 2019 08:27:17 PM | Info | Executed action method Jackett.Server.Controllers.ServerConfigurationController.Config (jackett), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 0.3339ms.
Jun 19, 2019 08:27:17 PM | Info | Executing action method Jackett.Server.Controllers.ServerConfigurationController.Config (jackett) - Validation state: Valid
Jun 19, 2019 08:27:17 PM | Info | Executing action method Jackett.Server.Controllers.ServerConfigurationController.Config (jackett) - Validation state: Valid
Jun 19, 2019 08:27:17 PM | Info | Authorization was successful.
Jun 19, 2019 08:27:17 PM | Info | Authorization was successful.
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of exception filters (in the following order): None
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of exception filters (in the following order): None
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Jun 19, 2019 08:27:17 PM | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Jun 19, 2019 08:27:17 PM | Info | Route matched with {action = "Config", controller = "ServerConfiguration"}. Executing action Jackett.Server.Controllers.ServerConfigurationController.Config (jackett)
Jun 19, 2019 08:27:17 PM | Info | Route matched with {action = "Config", controller = "ServerConfiguration"}. Executing action Jackett.Server.Controllers.ServerConfigurationController.Config (jackett)
Jun 19, 2019 08:27:17 PM | Debug | Action 'Jackett.Server.Controllers.ServerConfigurationController.UpdateConfig (jackett)' with id '7dad6d4e-5a52-431d-84db-8cb281b4c29b' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint'
Jun 19, 2019 08:27:17 PM | Debug | Action 'Jackett.Server.Controllers.ServerConfigurationController.UpdateConfig (jackett)' with id '7dad6d4e-5a52-431d-84db-8cb281b4c29b' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint'
Jun 19, 2019 08:27:17 PM | Debug | Request successfully matched the route with name '(null)' and template 'api/v2.0/server/Config'
Jun 19, 2019 08:27:17 PM | Debug | Request successfully matched the route with name '(null)' and template 'api/v2.0/server/Config'
Jun 19, 2019 08:27:17 PM | Debug | AuthenticationScheme: Cookies was successfully authenticated.
Jun 19, 2019 08:27:17 PM | Debug | AuthenticationScheme: Cookies was successfully authenticated.
Jun 19, 2019 08:27:17 PM | Debug | The request path /api/v2.0/server/config does not match a supported file type
Jun 19, 2019 08:27:17 PM | Debug | The request path /api/v2.0/server/config does not match a supported file type
Jun 19, 2019 08:27:17 PM | Debug | AuthenticationScheme: Cookies was successfully authenticated.
Jun 19, 2019 08:27:17 PM | Debug | AuthenticationScheme: Cookies was successfully authenticated.
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/api/v2.0/server/config?_=1560971061973
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/api/v2.0/server/config?_=1560971061973
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/favicon.ico?
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/favicon.ico?
Jun 19, 2019 08:27:17 PM | Debug | The request path /apple-touch-icon-180x180.png does not match an existing file
Jun 19, 2019 08:27:17 PM | Debug | The request path /apple-touch-icon-180x180.png does not match an existing file
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/favicon.ico?
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/favicon.ico?
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/favicon.ico?
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/favicon.ico?
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/apple-touch-icon-180x180.png
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/apple-touch-icon-180x180.png
Jun 19, 2019 08:27:17 PM | Info | Request starting HTTP/1.1 GET http://192.168.1.105:9117/favicon.ico?
Jun 19, 2019 08:27:17 PM | Info | Request starting HTTP/1.1 GET http://192.168.1.105:9117/favicon.ico?
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/apple-touch-icon-180x180.png
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/apple-touch-icon-180x180.png
Jun 19, 2019 08:27:17 PM | Info | Request finished in 739.0622ms 200 image/png
Jun 19, 2019 08:27:17 PM | Info | Request finished in 739.0622ms 200 image/png
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/apple-touch-icon-180x180.png
Jun 19, 2019 08:27:17 PM | Debug | Request is continuing in applying rules. Current url is http://192.168.1.105:9117/apple-touch-icon-180x180.png
Jun 19, 2019 08:27:17 PM | Debug | Connection id "0HLNKP6I4962D" completed keep alive response.
Jun 19, 2019 08:27:17 PM | Debug | Connection id "0HLNKP6I4962D" completed keep alive response.
-------------------------------

**Comment by ngosang** [comment]
@Goundski 1337x is working fine for me in Linux .Net Core. This kind of problems are usually related to network: proxy, vpn or isp blocks. You can try alternative domains.

**Comment by Goundski** [comment]
Sorted. My isp have a similar range ip than my Docker client that stuffed up the routing.
Changed my hosting IP's and all is working 100%
