### ISSUE TITLE
mac-torrents.com: [mactorrents] Exception (mactorrents): Got redirected to another domain. 

### ISSUE THREAD

**Issue by JDiaz11** [Jackett/Jackett#5512]
mac-torrents.com tracker:
Receiving error message the past couple of days (previously it worked correctly). I am able to access the site normally in browser. Log is attached:
> "An error occured while testing this indexer
> Exception (mactorrents): Got redirected to another domain. Try changing the indexer URL to https://www.mac-torrents.com/.: Parse error
> Click here to open an issue on GitHub for this indexer."

[log.txt.20190619.00001.txt](https://github.com/Jackett/Jackett/files/3307822/log.txt.20190619.00001.txt)

 **Jackett version**:  0.11.432.0
 **Mono version**:  5.20.1.19 

-------------------------------

**Comment by garfield69** [comment]
you can resolve this for yourself by editing the mactorrents indexer with your jackett dashboard and changing the site link to `https://www.mac-torrents.com/`
or you can update to the latest pre-release v0.11.433 to pick up the auto- correction
