### ISSUE TITLE
0 results

### ISSUE THREAD

**Issue by gac123** [Jackett/Jackett#552]
couchpotato configured for jackett with rarbg, never seem to get any results even though the console says that same request did yield results

looked at the couchpotato logs to see if any errors, i notice it tries a GET http://127.0.0.1:9117/potato/rarbg?imdbid=tt0775440&user=&passkey=

so i tried this in my browser and indeed:
{
  "results": [],
  "total_results": 0
}

so couchpotato not at fault (i would think)
but the jackett console says that it has found 24 torrentpotato releases from rarbg for: cell (this very same request)

issue? because strangely the same jackett rarbg is used for sonarr and this one does work without any issues, but i don"t know exactly how or what sonarr is quering to make it work

**Comment by kaso17** [comment]
Rarbg is not supported by this official jackett version (public tracker). It looks like you're using a fork with support for it. Please create an issue there or let us know if you can recreate it with this Jackett version. Closing for now.
