### ISSUE TITLE
[REQ] Honey3HD Tracker

### ISSUE THREAD

**Issue by Ahsome** [Jackett/Jackett#5525]
support the public tracker Honey3HD. This would be great as its a huge source of public torrents for Desi films

Link: https://hon3yhd.net/

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.439

**Comment by Ahsome** [comment]
THANK YOU!

**Comment by Ahsome** [comment]
Can this be modified @garfield69? There's a new link for this: https://www.hon3yhd.to/torrents.php

**Comment by garfield69** [comment]
does that link work for you?
using my browser i'm seeing cloudflare 522 connection timeout for  https://www.hon3yhd.to/, https://hon3yhd.net/ and even the private https://hon3yhd.com/

**Comment by garfield69** [comment]
https://hon3yhd.net/ currently returning cloudflare 522 Connection timed out
just me, or is the site broken, gone or moved to a new domain?

**Comment by garfield69** [comment]
back online but running extremely slow. takes over a minute to respond, which exceeds the 30sec timeout on jackett.

**Comment by garfield69** [comment]
https://hon3yhd.net/ currently offline again returning cloudflare 522 Connection timed out

**Comment by garfield69** [comment]
is there any point in keeping this indexer, the site seems to have ongoing issue since 30th June?
