### ISSUE TITLE
[tigers-dl] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#5527]
It looks like the css has changed.

It doesn't work from test nor sonarr nor radarr.

```
System.Exception: Error while parsing field=size, selector=td:nth-child(4), value=<null>: Selector "td:nth-child(4)" didn't match
```

**Comment by garfield69** [comment]
logon to the site with your browser and on the main bar where the cog and mailbox icons are, next on the right is a pull down option to set the torrent display mode.
change it to `torrents mode liste`.
the jackett indexer should now work again.

**Comment by skuizy** [comment]
Once again, that's the solution ! 

Thanks !

**Comment by thiryjer** [comment]
torrents mode liste .... yes it works

**Comment by pipopop** [comment]
Site has change. Can't access right now. I will post a message when I have more news.
