### ISSUE TITLE
Support for LibraNet.org

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5528]
Can we please add support for this tracker?

**Comment by garfield69** [comment]
LibraNet (LN) is a HUNGARIAN Private Torrent Tracker for EBOOKS / LOSSLESS MUSIC
https://libranet.org/

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.441

**Comment by ilike2burnthing** [comment]
https://libranet.org/

> [1226] Connecting:
Mysql_connect status: User 'libranet' has exceeded the 'max_user_connections' resource (current value: 150)

**Comment by ilike2burnthing** [comment]
back up
