### ISSUE TITLE
Linux Service Installation Problem

### ISSUE THREAD

**Issue by dshanks01** [Jackett/Jackett#5533]
I've discovered a small problem at the intersection between the release process and the Linux service installation script. This probably affects Mac and other Unix-like systems too.

The tarball for the current release was created from files owned by UID=1001, GID=1002. On systems where there is a user with UID=1001, the service installation script creates the jackett.service file to run Jackett as that user (whoever it happens to be). This may or may not be what the user desires. On systems where there is no user with UID=1001, the service installation script creates a jackett.service file to run Jackett as user UNKNOWN. Jackett then fails to run as a non-existent user (unless the system happens to have a user named UNKNOWN). The errors produced (see below) are spectacularly unhelpful to anyone who doesn't understand how systemd works. The average user will be stuck with a non-working Jackett service install and no idea of what's gone wrong.

Here's what a user sees on a system with no user with UID=1001:
```
user@computer:/opt/Jackett$ sudo ./install_service_systemd.sh 
Failed to stop jackett.service: Unit jackett.service not loaded.
Unit jackett.service could not be found.
Created symlink /etc/systemd/system/multi-user.target.wants/jackett.service → /etc/systemd/system/jackett.service.
ERROR: Could not launch service. The installation might have failed.
Please open an issue on https://github.com/Jackett/Jackett/issues and paste following information:
Jackett directory: `/opt/Jackett`
Jackett user: `UNKNOWN`

user@computer:/opt/Jackett$
```

Suggestions for resolving the problem:
1) Release tarballs should be created from files with UID=0,GID=0. The service installation script will see that the user is attempting to run Jackett as root and exit with an error message suggesting a fix.
2) The install script could be modified to take a parameter: -u <user>. The error message mentioned above could then tell the user to use the parameter to say which UID Jackett will run as. The service installation instructions in README.md for Linux and Mac (at least) should be updated to mention the install parameter. It looks like ARMv6 has a different service installation script. That script probably needs a similar modification.

**Comment by dshanks01** [comment]
At the time I wrote the above, I didn't realize that Jackett (apparently) needs write permission in its installation directory. At the very least, it will dump core if its installation files are owned by root and it's run as a non-privileged user. It would probably be preferable to have it write into the running user's home directory, perhaps in a .jackett sub-folder rather than risking the running user accidentally overwriting the installed files. That's one of the reasons why, typically in Linux, service install files are owned by root but the service runs as a non-privileged user.

In any case, the service installation instructions should probably be further modified to specify that the Jackett installation directory and files must be owned by whatever user Jackett is going to run as.

**Comment by jasonblewis** [comment]
this bit met too.

**Comment by ngosang** [comment]
Related #5407

**Comment by alexya** [comment]
I met this issue today. With @dshanks01 's comment, I resolved it.

**Comment by garfield69** [comment]
Jackett 0.13.611
