### ISSUE TITLE
[error] login input torrent.ai

### ISSUE THREAD

**Issue by karkaaa** [Jackett/Jackett#5546]
Hello,

Jackett Version 0.11.440.0

I think torrent.ai changed login input.

Need help to fix.

Thx.

**Comment by garfield69** [comment]
have you tried using your jackett dashboard to edit the torrent.LT config and changing the site link to `https://torrent.ai/` ?

**Comment by karkaaa** [comment]
i got error:

![image](https://user-images.githubusercontent.com/34538939/60162462-42d32080-9802-11e9-8803-fb83b06997f4.png)

**Comment by garfield69** [comment]
I take it you are running some form of linux with the mono flavour of jackett?

torrent.TL have renewed their CA on the 19th june 2019 but it looks like your system has not had its certificates updated. 

try refreshing your certificates:
    - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`
  - On QNAP refer to #2111

and reboot (or just restart all Jackett services) after the imports are completed.

**Comment by karkaaa** [comment]
If i use docker?

https://hub.docker.com/r/linuxserver/jackett

**Comment by garfield69** [comment]
Hmm.
try opening a terminal and starting a shell to the docker 
`docker exec -it jackett /bin/bash` 
then action the ca refresh 
`wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
this may not work, I don't use docker.

**Comment by karkaaa** [comment]
error:
![image](https://user-images.githubusercontent.com/34538939/60176831-162e0180-9820-11e9-9b02-78a3958306e4.png)

**Comment by garfield69** [comment]
maybe the next build of docker's jackett will include refreshed certificates.
But just in case it doesn't I've added an override for the current torrentlt certificate in jackett 0.11.450
