### ISSUE TITLE
[req] music-master.ro

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5547]
Another Open Signup tracker

https://www.reddit.com/r/OpenSignups/

**Comment by garfield69** [comment]
registration and login successful.

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.452

**Comment by inasua** [comment]
im on v0.11.522.0 and cant find music-master, am i blind?

**Comment by tkdrob** [comment]
Did you happen to add it already? I've done that. It won't show up in list of trackers to configure if its already configured :)

**Comment by garfield69** [comment]
https://music-master.ro/ returning ERR_NAME_RESOLUTION_FAILED
is the site gone, or has a new domain?

**Comment by garfield69** [comment]
https://music-master.ro/ returning ERR_CONNECTION_REFUSED
just me, or is the site broken, gone or moved to a new domain?

**Comment by garfield69** [comment]
https://music-master.ro/ now returning
![image](https://user-images.githubusercontent.com/6933240/68067320-fc8e5f00-fda9-11e9-8ee2-2bc278e8df49.png)
anyone have any news?
