### ISSUE TITLE
Jackett stops to respond after some days: lots of CLOSED and CLOSE_WAIT connections

### ISSUE THREAD

**Issue by Zamana** [Jackett/Jackett#5549]
Hi!

I'm running Jackett inside a jails (iocage) in FreeNAS (11.2-U4) with success.

But... each 3 or 4 days Jackett stops to respond. The jail is UP, the service is UP and listening on the default port (9117), but the webpage become inaccessible, from the browser and from the clients (Sonarr, Radarr, Lidarr).

Restarting the service restores the connection, but obviously this is not a solution.

What I realize is that, when this happens, there are A LOT of TCP hanging connections with the statuses CLOSED and CLOSE_WAIT.

Do you think that this hanging connections could be causing the problem?

`root@jackett:~ # mono --version
Mono JIT compiler version 5.10.1.57 (5.10.1.57 Sat May 11 02:03:48 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notification:  kqueue
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)`

`Jackett Version 0.11.440.0`

**Comment by Zamana** [comment]
It happened again today...

**Comment by rrrevin** [comment]
It depends on how many connections. IT is possible that there are so many , you've filled your connection limits per process/user, but you'd need ALOT of connections. Next time it happens, count the number of connection of each type, and report back.

**Comment by cadatoiva** [comment]
FreeNAS is built off FreeBSD, and uses the mono version of Jackett. I have the same underlying OS and same issue.
@ngosang, this should be BSD/mono, not Linux. And my issue #6939 should be merged with this one.

**Comment by Zamana** [comment]
Well... I decided to install [monit](https://mmonit.com/monit/), so that's the service is automagically [re]started every time it became inaccessible.

That's the relevant configuration part:

```
check process mono with pidfile /usr/local/jackett/jackett.pid
        start program = "/usr/sbin/service jackett start"
        stop program = "/usr/sbin/service jackett stop"
        if failed host jackett.local port 9117 protocol http then restart
```

In my case, "jackett.local" is 192.168.0.105. Change according with your setup.

It's not a solution, but that's what we have for today.

Regards.

**Comment by ngosang** [comment]
At this time I don't have Mono neither FreeBSD to test it. Maybe we can provide .Net Core builds for FreeBSD => https://github.com/dotnet/core/issues/522
In Linux with .Net Core this issue is not present.

**Comment by cadatoiva** [comment]
It is possible, but for that I'd have to figure out how to modify the FreeBSD port and submit a pull request to their team, as well as get all that working on my system. Might take some time.

**Comment by ngosang** [comment]
@Zamana are you still having this issue?

**Comment by Zamana** [comment]
Yes, it is still happening once in a while, but I'm not following the issue close enough, because I coded a script that restarts the service when that happen.

Thanks.
Regards.

**Comment by garfield69** [comment]
Closed as stale.
