### ISSUE TITLE
YTS indexer stop after three searches by title and seems timed out

### ISSUE THREAD

**Issue by Griphiny** [Jackett/Jackett#5555]
Discovered when searching by title with YTS index i get the follwoing error when doing more than three searches,searches  by imdb number still works though

Jackett.Common.IndexerException: Exception (yts): API error, movies missing ---> System.Exception: Parse error ---> System.Exception: API error, movies missing    at Jackett.Common.Indexers.Yts.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/yts.cs:line 139    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 842    at Jackett.Common.Indexers.Yts.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/yts.cs:line 238    at Jackett.Common.Indexers.Yts.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/yts.cs:line 72    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 367
--
Jun 27, 2019 11:30:01 AM | Error | Error on 20190627113001 for YTS.txtSystem.Exception: API error, movies missing    at Jackett.Common.Indexers.Yts.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/yts.cs:line 139     {"status":"ok","status_message":"Query was successful","data":{"movie_count":1,"limit":50,"page_number":1},"@meta":{"server_time":1561627801,"server_timezone":"CET","api_version":2,"execution_time":"0 ms"}}
Jun 27, 2019 11:29:58 AM | Info | Found 0 releases from YTS for: movie 1 2019
Jun 27, 2019 11:29:55 AM | Info | Found 2 releases from YTS for: movie 2 2019
Jun 27, 2019 11:29:52 AM | Info | Found 0 releases from YTS for: movie 3 2019
Jun 27, 2019 11:29:43 AM | Info | Found 99 (1 new) releases from YTS

Jackett Version 0.11.403.0

**Comment by garfield69** [comment]
works for me just now. I did 6 movie searches and all came back fine.
from your log it looks like the request went to the yts api server and it returned a valid json retry, but it did  not contain any movies.
so what ever was happening it looks to have been at the yts api server side.
nothing jackett can do about that.
