### ISSUE TITLE
Rewrite query invalid

### ISSUE THREAD

**Issue by aguillem** [Jackett/Jackett#5556]
I'm looking for a movie called "Qu'est-Ce Qu'on A Encore Fait Au Bon Dieu ?" also known as "Qu'est-ce qu'on a fait au Bon Dieu 2"

There's my logs from Radarr and Jackett.
Looks like that query losts an "a" after "on" :
```
19-6-27 17:06:10.9|Info|NzbSearchService|Searching 1 indexers for [Qu'est-ce qu'on a encore fait au bon Dieu ?]
2019-06-27 17:06:11.5087 Info Found 0 releases from YGGtorrent for: qu est ce qu on fait au bon dieu 2
2019-06-27 17:06:13.2266 Info Found 0 releases from YGGtorrent for: qu est ce qu on encore fait au bon dieu
```
So no result was found for this movie because indexers is strict and only recognize "qu est ce qu on **a** encore fait au bon dieu"

**Comment by garfield69** [comment]
ygg's web site old search engine is a mess.
if you access your jackett dashboard and edit the yggtorrent config, you'll find an option to enable using the ygg web site's **beta** search engine.
try it and see if it helps.

**Comment by aguillem** [comment]
Seems to work very well. Thank you

**Comment by aguillem** [comment]
in fact no, this mode is too permissive and returns too much unrelated results
