### ISSUE TITLE
[req] Support for asgrd.org

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5562]
Open Signups again

**Comment by tkdrob** [comment]
Old issue was closed by bot because of no description

**Comment by garfield69** [comment]
signups are currently invite only.

**Comment by tkdrob** [comment]
Did you try this url? https://asgrd.org/signup.php?promo=5ff5be0b0b0efca3198b2fe20be95afa8cc782151ef991209c506c493df5bf18

**Comment by garfield69** [comment]
registration and login successful. thanks.

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.493

**Comment by ilike2burnthing** [comment]
Closing Dec 31st - https://github.com/Jackett/Jackett/issues/10630

https://torrentinvites.org/f31/asgaard-news-site-shutting-down-585123/
