### ISSUE TITLE
[torrentleech] Exception (torrentleech): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Parse error (Test)

### ISSUE THREAD

**Issue by cristianmargescu** [Jackett/Jackett#5565]
Error on 20190628224928 for TorrentLeech.txtNewtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   at Jackett.Common.Indexers.TorrentLeech.<PerformQuery>d__15.MoveNext()

<html lang="en" class="html-lights-off">
<head>
    <title>TorrentLeech.org</title>    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="TorrentLeech">
    <meta name="keywords" content="torrent">
    <link rel="stylesheet" href="/common.6d72c9726964e5a294d599c88b89a3b3.css">
    <link rel="stylesheet" href="/main.25c94ec34fd7c7f3f9e64ab1a1032192.css">
</head>

    <body class="html-lights-off">
        <div class="navbar navbar-default tl div-error">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"></a>
                </div>
            </div>
        </div>
        <div id="error">
            <h1>An error occurred</h1> 
            <h2>Application error. Please report to staff.<br/>(Error Code: 1004)</h2> 
          
                    </div>
        <script type="text/javascript" src="/common.7c90a3e821c394526ce5.js"></script>
        <script type="text/javascript" src="/main.a0f672d6fc76e4f96ca8.js"></script>
    </body>
</html>

**Comment by garfield69** [comment]
looks like torrentleech had an outage, as you can see from the html they returned.
nothing to do with jackett.
I just tried it now and it seems to be working for me.
