### ISSUE TITLE
cpasbien clone - Incorrect size returned

### ISSUE THREAD

**Issue by sbeaudoin** [Jackett/Jackett#5567]
Radarr refuse to download some items returned for torrent indexer "cpasbien clone" because the size is inferior of the configured limit.  The returned size is 1000 lower than the real size.  So, a 1.6GB file, who would be accepted, is returned as a 1.6MB file, who is rejected.

**Comment by garfield69** [comment]
yes, it appears that the cpasbienclone returns sizes such as 13.6Go in the main page (used for jackett TEST and searches without keywords), but if using search with keywords it returns size as 13926.4 which appears to be the size converted to MB.
the indexer is not expecting the size to be presented differently hence your discovery.
I'll take a look at the indexer and see if there is some way to cope with both size representations.
