### ISSUE TITLE
[REQ] TamilRockers

### ISSUE THREAD

**Issue by Ahsome** [Jackett/Jackett#5570]
Request for a public Tamil Movie tracker
Website: http://tamilrockers.ws/

**Comment by garfield69** [comment]
this site is not suitable for processing by the cardigann processor as it contains multiple download links for single titles without much other details such as seeders, leechers, files, grabs, size, date etc.
the indexer will need to be written in c#.

**Comment by lyveng** [comment]
I would like to help with writing the indexer for tamilrockers. Its been quite long since I coded in C# though. Also they keep changing the domain extension. For eg., "ci tel to al ch co ws" are some of the recent names that they've had. Sometimes they even change the domain name slightly since local ISPs keep blocking their domains. I've noticed that this regex generally works for the domain name www\.tamilrocker+s+.${ext} where ext is the variable pointing to the extension.

**Comment by Ahsome** [comment]
I would love to help too, since I'm learning C# as well! Have you made any progress on it @lyveng? To fix the problem of getting the domain, we can simply scrap the website http://whereistamilrockers.tk/, since they always post the domain as it change

**Comment by Ahsome** [comment]
EDIT: It looks like they use this JSON file to get the URL, so we could simply deserialise it and get the info:
https://spreadsheets.google.com/feeds/cells/1Ocd4DIpqCVctxZQdtKz3nbuI_DhK3bqfT2arxd0Ub8E/1/public/full/R2C1?alt=json

**Comment by Ahsome** [comment]
@lyveng if you make a fork to start implementing the tracker, I'd be happy to contribute

**Comment by lyveng** [comment]
@Ahsome I've not started working on it. It is better to take some public tracker PR as reference before starting the work. Also better to discuss with @garfield69 regarding the expectations/approach on implementing this.

Is http://whereistamilrockers.tk/ constant or does the tld keep changing here as well?

**Comment by datsunedd** [comment]
I can help with the C#. Let me know what I can do

**Comment by lyveng** [comment]
Sorry folks. I haven't been able to get any time for contributing here. Count me out of this.

**Comment by Ahsome** [comment]
I can help too! @lyveng if you cannot contribute, could you at least guide us on how to start the PR?

**Comment by lyveng** [comment]
> I can help too! @lyveng if you cannot contribute, could you at least guide us on how to start the PR?

I think you've mistaken me for some maintainer of the project. I also have zero clue on how to start the PR.
@garfield69 It would be helpful if there is a wiki page on how to create an indexer in C#.

**Comment by lyveng** [comment]
> I can help too! @lyveng if you cannot contribute, could you at least guide us on how to start the PR?

@Ahsome I found this one other issue #6081 which had the same labels as this issue and the corresponding PR #8040. Maybe you can use this as a reference and try to implement for tamilrockers

**Comment by ngosang** [comment]
If you want to add a new tracker you have some advices here => https://github.com/Jackett/Jackett/issues/8180#issuecomment-613497152
Just copy&paste a working tracker, rename it and start hacking. Open a PR when you have something that works. We will give you feedback in the PR.

**Comment by lyveng** [comment]
AFAIK tamilrockers is no longer active. This issue can be closed.

**Comment by afeedh** [comment]
> AFAIK tamilrockers is no longer active. This issue can be closed.

An alternate version of tamilrockers still available at [https://tamilmv.unblockit.link/](https://tamilmv.unblockit.link/). Is it still possible to add this to jackett?

**Comment by ilike2burnthing** [comment]
https://www.1tamilmv.us/ is what unblockit is mirroring

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/2421
