### ISSUE TITLE
[Req] Support for purovicio.pw

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5573]
Ask for invite here: https://discordapp.com/invite/ENt2sy

**Comment by Yllelder** [comment]
The link says: Invitation not valid.

Has it expired? Is that a mistake?

**Comment by tkdrob** [comment]
Try this one: https://discord.gg/n5Yecn

Leave email address in chat to get invite, hopefully

**Comment by Jroddmqz** [comment]
https://discord.gg/sPvrhj

**Comment by garfield69** [comment]
>ngosang wrote:
>It's a private tracker with content in Spanish language. The layout is really similar to Blutopia.
.You can request an invitation in this Discord channel => https://discordapp.com/channels/441435547882487810/441435547882487812
https://purovicio.pw

**Comment by S3RgY** [comment]
@garfield69 @tkdrob Invitation is expired, I can work on it If I'm able to login.

**Comment by ngosang** [comment]
@garfield69 I can share my account.
I think the engine is UNIT3D.
Language SPANISH LATINO => es-419

**Comment by garfield69** [comment]
sure. sent credentials to the usual address and I'll implement.

**Comment by ngosang** [comment]
Sent

**Comment by garfield69** [comment]
Jackett 0.14.297

**Comment by koushik-sen-vst-au4** [comment]
Please provide me a invite at senkoushik91@gmail.com .

I will also be able to help you.

**Comment by ngosang** [comment]
https://purovicio.pw/

Site down. DNS error. I don't know if they have new domain.
https://www.uptrends.com/tools/uptime

**Comment by ilike2burnthing** [comment]
https://purovicio.in - https://torrentinvites.org/f31/purovicio-news-580568/

Can someone check it's just a simple change of domain?

**Comment by garfield69** [comment]
Its a simple domain change.  
While I don't have an account on the site anymore, a check of the login page source shows they are still using the same unit3d engine from the prior domain.

**Comment by ngosang** [comment]
I confirm it's working fine with the new URL.

**Comment by Jroddmqz** [comment]
New domain: purovicio.in
Discord: https://discord.gg/86Gdx2n

**Comment by garfield69** [comment]
@Jroddmqz wrote:
>New domain: purovicio.in

 hah! you are about 24 hours behind. upgrade your jackett. to 0.16.1472 ;-)

**Comment by garfield69** [comment]
https://purovicio.in/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
Anyone have info on purovicio.in, is the site gone, broken or moved to a new domain?

**Comment by garfield69** [comment]
v0.20.2686
