### ISSUE TITLE
[req] Change configuration with an external program

### ISSUE THREAD

**Issue by jameseck** [Jackett/Jackett#5578]
Hi,

I'm trying to pass configuration to Jackett in a Docker image upon start.
The use-case is that I'm running Jackett, Sonarr, etc in Kubernetes/Openshift.  I want to be able to hand the various API keys around via terraform to the various deployments so I can automate spinning up a complete environment.

For a simple example of my problem, please see my WIP script:
https://github.com/jameseck/docker-jackett/blob/master/run.py

When I write the APIKey to the ServerConfig.json file, once Jackett starts, it's overwritten by whatever Jackett decides it should be - I presume it's being autogenerated.
I've found from digging in the Jackett source code that I can set the API key by writing it to a file in the Data Folder called api_key.txt.  This works fine (although I can't find anywhere else where this is documented, but does not help with Proxy settings which I need to also set.

**Comment by jameseck** [comment]
In addition to this, if there is a way to post the config via the api then I'd love details on how to do this.
The ordering would be:
Deploy Jackett container with api_key.txt file and start Jackett service.
POST config data to Jackett api (authenticating with the api key) to configure proxy, admin password, etc.

I've tried playing around with various POST requests to /api/v2.0/server/config but I haven't been able to make it work.

**Comment by ngosang** [comment]
1. Stop Jackett and make the changes in the configuration file
```
${HOME}/.config/Jackett/ServerConfig.json
```

2. Or change the configuration via API.

First, you need to get the Jackett cookie from response headers.
* Without admin password
```
curl 'http://127.0.0.1:9117/UI/Login'
```
* With admin password
```
curl 'http://127.0.0.1:9117/UI/Dashboard' -H 'Content-Type: application/x-www-form-urlencoded' --data 'password=<YOUR_PASSWORD>'
```
Then you can change the configuration
```
curl 'http://127.0.0.1:9117/api/v2.0/server/config' -H 'Content-Type: application/json' -H 'Cookie: csrftoken=CoVlOuInt0iigZ3Z71........' --data '{"port":9117,"external":true,"updatedisabled":true,"prerelease":false,"blackholedir":"","logging":false,"basepathoverride":"","omdbkey":"","omdburl":"","proxy_type":"0","proxy_url":"","proxy_port":"","proxy_username":"","proxy_password":""}'
```

Related => https://github.com/Jackett/Jackett/issues/5493#issuecomment-573754100

I think you have enough info.
