### ISSUE TITLE
[req] - Ability to modify 'seeder requirements' on individual series

### ISSUE THREAD

**Issue by ned-kelly** [Jackett/Jackett#5579]
Feature request:

When adding in some releases, older and/or less "mainstream" releases often have a lower number of seeders than I would like (and I don't want to lower the settings for minimum seeders globally) - It would be nice to have the ability in a series to add set some additional configuration parameters such as the minimum seeders required etc to be a custom level rather than the default global.

**Comment by garfield69** [comment]
Huh?
I think you have the wrong project.
are you thinking of sonarr or couchpotato or duckietv or some such tool for tracking tv series episodes?
Jackett simply fronts ends the searches on web sites and returns results in an API which the other apps can process.
it does not track series and is not concerned with what those other apps do with the data jackett provides.
