### ISSUE TITLE
[REQ] bj-share.me

### ISSUE THREAD

**Issue by sergiogns** [Jackett/Jackett#558]
One of the biggest brazilian trackers. 
Iam holding a invite right now to help you.

Thanks guys!!

**Comment by kaso17** [comment]
please send the invite to -removed-

**Comment by sergiogns** [comment]
Sent!!

=)

**Comment by kaso17** [comment]
got it, thank you.

Will work on it during the next week.

**Comment by sergiogns** [comment]
Nice. Thank you! 
In case you need some help with portuguese, just let me know.

**Comment by garfield69** [comment]
migrated from C# to yml #16855
