### ISSUE TITLE
Question.. not a bug.. status of flightlevel and kaso17?

### ISSUE THREAD

**Issue by rrrevin** [Jackett/Jackett#5586]
I notice most of the coding issues have been assigned to @flightlevel and @kaso17. Obviously, they know their stuff, and they know the code in Jackett very well.

However, it seems they have been (entirely?) absent since beginning/mid May/April, or may have abandoned this project entirely.

I truly hope they have not decided to leave, as their work here has been exceptional and is greatly missed!! Does anyone know the status of these two coders? 

Can we leave this issue open until we know their status?

**Comment by kaso17** [comment]
I'm still alive. Just very busy with my regular work these days.

**Comment by flightlevel** [comment]
Apologies for being MIA, life has got in the way recently
I just don't have the time (and have lost the desire to make time) to work on Jackett
This will be my last post on Jackett
Really hope others step in to give @garfield69 (doing a fantastic job!) a hand as its hard to keep a project alive when it relies on one individual. And to those that use Jackett but aren't able to contribute, please be courteous and polite. It really discourages people from contributing to open source when you give up your spare time to contribute only to be on the receiving end
Think there is some real benefit to moving to .NET Core 3.0 (single file executables and lower memory use) and it shouldn't be too much work, so hope someone takes that up!
Good luck to all
flightlevel signing off
