### ISSUE TITLE
[Req] www.immortuos.life

### ISSUE THREAD

**Issue by FilmjunkieGF** [Jackett/Jackett#5588]
New private german tracker https://www.immortuos.life/
For invites can be asked here: https://forum.immortuos.live/showthread.php?tid=136

But I could also provide you a working Login for the tracker.

**Comment by garfield69** [comment]
Send details to garfieldsixtynine @ gmail.com. I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by FilmjunkieGF** [comment]
ok, I send you the working Login!

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.611

**Comment by garfield69** [comment]
@ilike2burnthing  immortuos login page shows that the app.js signature has changes which implies that they may have upgraded from unit3d 1.9.3 so something newer (the signature suggests something in the 6.*.* range).
As you still have access can you take a looksee and update if required. 
And if you could grab the unit3d.js signature and update the maintainers unit3d versions ids sheet that would be swell ;-)

**Comment by ilike2burnthing** [comment]
Will take a look in a bit

**Comment by ilike2burnthing** [comment]
They may well be using a more recent version, but as far I can see nothing has changed, there's no API, and it's basically identical to ChileBT. I've updated the unit3d.js source ID though.
