### ISSUE TITLE
[REQ] Blu-Bits

### ISSUE THREAD

**Issue by seanvree** [Jackett/Jackett#559]
Wondering if you could add Blu-Bits??

Thanks, #

**Comment by kaso17** [comment]
please send an invite to kaso1717 -at- gmail.com

**Comment by armani316** [comment]
I was reluctant to join this tracker because it's not one of the indexers of Jackett. I'd like it if it's added, so I'd like to vote for this!

**Comment by seanvree** [comment]
@kaso17 .... I sent you an invite to your gmail

**Comment by kaso17** [comment]
thank you for the invite.
Unfortunately it seems like they have a problem with their registration process, waiting for staff feedback regarding the error message I'm receiving

**Comment by seanvree** [comment]
Good, no worries!  Thanks for the work my man!

**Comment by kaso17** [comment]
Still no feedback on my problem:
https://www.reddit.com/r/Blubits/comments/5ezxc0/this_ip_address_is_already_in_use_on_this_side/
The IRC server doesn't work either, is there any other way of contacting the staff?

**Comment by armani316** [comment]
I just signed up there 5 minutes ago, and it worked fine.

**Comment by kaso17** [comment]
ok, figured it out: you can't register using IPv6 ;)
Works now. Thank you.

**Comment by kaso17** [comment]
is this tracker still alive (getting a Cloud flare error)?
