### ISSUE TITLE
[torrent9] Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by michaelroussel2494** [Jackett/Jackett#5591]
Hello

Torrent9 Don't work since url change:

logs : 

Jul 04, 2019 01:09:40 AM | Error | System.Exception: Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
-- | -- | --
Jul 04, 2019 01:09:40 AM | Info | Found 0 releases from Torrent9
Jul 04, 2019 01:09:40 AM | Info | CardigannIndexer (torrent9): Relogin required

**Comment by garfield69** [comment]
yeah. the official torrent9 domain has been hijacked and now redirects to the .cz  or .lol domains which is not the official site but a clone competitor. 
the .cz site uses the same layout as the torrent9clone indexer at .lol, its probably the same family.

if anyone knows where the official torrent9 domain is now at please post.

you can tell the difference between the official torrent9 and the clones by using your browser.
If clicking on the TopTorrents link of the sites home page takes you to `*/top` it a clone, if it takes you to `*/top_torrent.php` its the official site.

**Comment by Fayyya** [comment]
i found a website talking about new torrent9 url 
https://digitaltendances.com/telechargement/torrent9-la-liste-des-nouveaux-liens-telecharger-films-series/?utm_source=feedburner&utm_medium=twitter&utm_campaign=Feed%3A+Digitaltendances+%28DigitalTendances%29

i just tried to put the url and it seems working . did not tested yet for torrent search .. 
i can't ensure that is a good info but why not 
Maybe you should be able to confirm or not 

https://www.torrent9.is/

BTW just delete my post if it's bullshit

**Comment by garfield69** [comment]
close enough.
needed to switch the domain to ww1. for the search to work, the details link with the magnet are not on the www. domain.
its not exactly the same as the original site, but 99% is better than nothing.
made a few minor amendments to shoehorn the indexer in. ;-)
