### ISSUE TITLE
TorrentBytes ssl error

### ISSUE THREAD

**Issue by manderss99** [Jackett/Jackett#5597]
When trying to add torrentbytes indexer in jackett I get this message in log:

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small

Jackett 0.11.463.0

-------------------------------

**Comment by garfield69** [comment]
assuming that you are using some form of linux platform, please post the output from
`openssl s_client -connect www.torrentbytes.net:443`

**Comment by manderss99** [comment]
pi@raspberrypi:~ $ openssl s_client -connect www.torrentbytes.net:443
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = www.torrentbytes.net
verify return:1
3070009360:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../ssl/statem/statem_clnt.c:2156:
---
Certificate chain
 0 s:CN = www.torrentbytes.net
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFczCCBFugAwIBAgISA+x/f4TRdtiQPiHkcn0glbYrMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xOTA2MzAxNzAzNTZaFw0x
OTA5MjgxNzAzNTZaMB8xHTAbBgNVBAMTFHd3dy50b3JyZW50Ynl0ZXMubmV0MIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA81AVtp3gdv0MKoBN7qVgDOVN
pD6QTYXhfAf/eQSreqCHGrBrP0SZQWgNcJAtpZQLAG6E5oV5JYqPf8Pd0Jx3xsF9
KoTFaYwapQ3ORirBebt0/fLLoNmha1BtRnGrLBwd4wix0HAZCJ1LgpCIEHTABI1B
08f+en2cF6aLPo2TJe4+WvakfWXM4EuhWd1kpSwYFSshV0J0+2trFjUInkyW+nZZ
JMqZ+h/2yHtLr+9npFIrJpxAT6p0+EWWIQCDMuKe0HFjCXGzcJXHJhIr8q6XYvIZ
OYzwN4lKMc+2gVvwHo/CTBQuQGYutwDPI6AYwqJuLTvgvjUJb4M9Afw2mXexbQID
AQABo4ICfDCCAngwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMB
BggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQ8Z2gXhcmNlGB4nS+v
3OD8b6XqsjAfBgNVHSMEGDAWgBSoSmpjBH3duubRObemRWXv86jsoTBvBggrBgEF
BQcBAQRjMGEwLgYIKwYBBQUHMAGGImh0dHA6Ly9vY3NwLmludC14My5sZXRzZW5j
cnlwdC5vcmcwLwYIKwYBBQUHMAKGI2h0dHA6Ly9jZXJ0LmludC14My5sZXRzZW5j
cnlwdC5vcmcvMDEGA1UdEQQqMCiCEHRvcnJlbnRieXRlcy5uZXSCFHd3dy50b3Jy
ZW50Ynl0ZXMubmV0MEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEB
MCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBBQYK
KwYBBAHWeQIEAgSB9gSB8wDxAHYAdH7agzGtMxCRIZzOJU9CcMK//V5CIAjGNzV5
5hB7zFYAAAFrqY7QQgAABAMARzBFAiBf8BaGZaHpYP+XMyMyKItY7c8eoiFDPamB
O2w+JjyDHQIhANpJHIt0M7Wc9Z3QtadLRoP4Gw3eVBPAEpV3ws5PXGAQAHcAKTxR
llTIOWW6qlD8WAfUt2+/WHopctykwwz05UVH9HgAAAFrqY7QMAAABAMASDBGAiEA
xJYzDGcyW+hHkCT4gFE0TjamBNQDCnZdGagWnsgnszkCIQCuwW/j4SgQ0abekhBE
YRF3qZYIKSirgc0vn+jTBA/q/zANBgkqhkiG9w0BAQsFAAOCAQEAdV8szfrCyNuE
YyZInqH7WfU1n4najMre72I+S8YPzlR9NZ+lUY29NFDHWBckdpZpBRuBWCD2OCLD
HBcm2VBxcrOx3uYIeuBEB5BALET+fxIRdfGpKrhP2WzJM0gJzKJQFrJdEthlaBer
AM7NWopnPo64FnKHCJy8Bi3q6nbs0Ksp0zUtYGLzHxSte5k7uA4ejNOAAsevGVYc
FGtS14Z+rOGKL7JS6nujXLDyvAoCwqW7ornL8UsmVwaISziAzcxtcKmOW1XZ/EP4
5pWOfoBjxAQPyvC6yHb/BtF7lTehQeysrzqTFxu28vkatayQn6eEIqalvmb73I7t
AsRlZ5k7gg==
-----END CERTIFICATE-----
subject=CN = www.torrentbytes.net

issuer=C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3

---
No client certificate CA names sent
---
SSL handshake has read 3185 bytes and written 319 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1562355943
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---

**Comment by garfield69** [comment]
so your pi openssl is chocking on the certificate for torrentbytes, which is why jackett also fails.
but openssl on my ubuntu is happy with the certificate, and so is my win10.
no idea how to proceed from here.
 @kaso17  @flightlevel  help?

**Comment by ngosang** [comment]
@manderss99 Try to update the distribution packages and Jackett to see if you can reproduce the issue.

**Comment by manderss99** [comment]
Since the report was made I've started using docker on my pi  (linuxserver/jackett)
I have tested adding torrentbytes successfully on 0.12.898.
Closing, thanks.
