### ISSUE TITLE
Jackett not saving configuration of indexers?

### ISSUE THREAD

**Issue by DavGerm4** [Jackett/Jackett#560]
Whenever I restart the service, or if I reboot the server, I have to add in the indexers again? It's like it's not saving which indexers I use?

I do see this message in red in the logs though:

> Oct 18, 2016 07:45:38 AM    Error  
> Failed loading configuration for {0}, you must reconfigure this indexer

**Comment by JigSawFr** [comment]
We need more informations as:
- OS version
- Jackett version
- Mono version if used
- Full logs
- And Jackett providers used

**Comment by DavGerm4** [comment]
OS: Ubuntu Server 16.04.1
Jackett Version: v0.7.303.0
Mono Version: 4.6.1

For the logs, how do I pull those up? and also, how do i update Jackett? Says a new version is there, but I actually don't know the process to update it...

**Comment by giacomofabbri** [comment]
It happens to me as well! 
OS: Ubuntu Server 16.04.1
Jackett Version: Latest as of today
Mono Version: Latest as of today
And I as well I'm not sure how to find the log!
Thanks anyway

**Comment by giacomofabbri** [comment]
Please help us fix this damn problem, if you need anything just let me know! Thanks for your hardwork

**Comment by kaso17** [comment]
Please run Jacket manually using "mono JackettConsole.exe -t" to get the log any maybe already some useful error message.
Make sure the Jackett user owns the config+child directories (~/.config/Jackett/)

**Comment by mattberther** [comment]
I see the same issue -- and when it happens, Im also unable to delete trackers. A message comes up saying:

```
Delete error for XXX The requested service 'XXX (Jackett.Indexers.IIndexer)' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
```

**Comment by giacomofabbri** [comment]
I obviously checked before the owner and the group of the folder and it's mine and not root and even jackett is mine, not root!
I just run the command that you suggested me, where it's gonna save the log?? 
Anyway I found out that the file in the Indexers folder are available and the only thing that I have to type everytime that "resets" it's the password, I'm using very long password like 40-50 character, that may be the problem?
And second, if the problem appears when you restart how the program be able to log the error??
Thanks anyway

**Comment by kaso17** [comment]
Log's are stored at ~/.config/Jackett/log.txt and should be also printed to the standard output.
Can you please try again with a lear config (`mv ~/.config/Jackett ~/.config/Jackett.bak`)

**Comment by giacomofabbri** [comment]
Just did it! Let's see what happens!

**Comment by giacomofabbri** [comment]
I had to reboot my server and now I have all my Indexers in Jacket working with Sonarr, I have no idea why, but thats good!!

**Comment by kaso17** [comment]
@DavGerm4 and @mattberther is this still a problem for you?

**Comment by armani316** [comment]
@kaso17 Might be a good idea to close this issue since it hasn't had any activity in a while.
