### ISSUE TITLE
[Req] Support for crazys-corner.info

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5604]
http://crazys-corner.info/index.php?page=signup
Private site for Ebooks and AudioBooks.

**Comment by garfield69** [comment]
in future please post the link for the signup directly here. 
We don't want to have to scroll through the reddit posts looking for the link.

**Comment by garfield69** [comment]
http://crazys-corner.info/ returning ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
Jackett 0.16.427
