### ISSUE TITLE
Password fields with "Password (Required)" instead of just "Password" are shown as plain text

### ISSUE THREAD

**Issue by MrDemocracy** [Jackett/Jackett#5607]
**Jackett version**: 0.11.463.0

-------------------------------
A few indexers on Jackett has `Password (Required)` instead of `Password` as the name above the input field. This seems to be causing the input field type to be set to `type="text"` instead of password.

**Comment by garfield69** [comment]
Norbits, NordicBits, Abnormal. Are there any others?

**Comment by garfield69** [comment]
Norbits, NordicBits, Abnormal. fixed with jackett v0.11.471

**Comment by MrDemocracy** [comment]
Thank you! 😁
