### ISSUE TITLE
[transmithenet] Exception (transmithenet): String '1 hour ago' was not recognized as a valid DateTime.: Parse error (Config)

### ISSUE THREAD

**Issue by wonkyfist** [Jackett/Jackett#5608]
-------------------------------

**Comment by wonkyfist** [comment]
For the tracker nebulance

**Comment by garfield69** [comment]
what version of Jackett are you using?
from v0.11.428 onwards a fix should be available.
if you are on a release older than this then upgrade to pick up the fix.
the latest release is v0.11.471 
if you are already on the latest release then say so and I'll take a second look and reopen this ticket.
