### ISSUE TITLE
Jackett log being detected as Trojan:JS/Foretype.A!ml by Windows defender.

### ISSUE THREAD

**Issue by lkjasdlfwe** [Jackett/Jackett#5609]
I have been using Jackett since a couple of months and so far it has worked perfectly. Since last night WIndows defender started detecting Jackett's log as a virus and keeps alerting me all the time. [Here](https://lh3.googleusercontent.com/HHAhP3YpeMKeqg7zvxYSQ_gZsEgMf-lzyzvo-uzucee62Nghi-AZBA5sdxzlFlpSg-2IT05BcE81uT16xgY36Lz-F9qijOVqgTy5wEh3n4t7eu6lPIOC1x08U1D40LOBKcU5ol1AekxwI_yKL1_1Z2AFhStogEHQZet9YcexDXzQGBMcly4FW4zr8kuB_oB4l_e0Sa8X7bcUYOjivOi9QyNljvw6h3POHhAP8I2FFjPC-2wECYm_yB96kW8CX07gEOhD2tfQqg8UpR9BBCroJPdf_GzrRQiS5YNEImWCa1TyDz74Y13MawsXl9lzi9q4efc2x95ITAYTTCwOyhANN_6-RhsLAuwBvDCc_UoE1uiRAFnIwB_W0fVX4Oyg56U9V48AfyoDYlV7uZOShSp3wJlBPGk1Z3ZZAMwNibuZmCvHO77CnknrY02EdbtsptBDt-F7U_rgXf8emrzzUke7SXvqQNbrG3ji5pffkK1Cq2rKHZGOYkgPC6DvGYkD8uGmwbKoYQOuiK5hnU1EfGKmd1hBA2yDpkTZCHlGzwPnddL_-TMpS0d8flWv91z4pXXhqEWNSzs4taH4aqz38wHnkcePhVJWSjd4D7PsARqrvfr7im-c92_mPeD0ik99z2S-2rOis2sneqGhDMMiRwuGbI-1WgkiYF71=w352-h460-no) is the exact message from Defender.

Jackett Version 0.11.471.0
Windows 10, 1903
Log attached
[log.txt](https://github.com/Jackett/Jackett/files/3365652/log.txt)

**Comment by garfield69** [comment]
I don't see what you expect us to do about this.
the log is just a text file. Obviously a false positive.
just load an exception to stop defender scanning it.
