### ISSUE TITLE
[REQ] The Horror Charnel

### ISSUE THREAD

**Issue by savahu** [Jackett/Jackett#561]
Private tracker dedicated to Horror / Cult / Sci-fi movies.

Currently open signup at http://horrorcharnel.org/signup.php

**Comment by garfield69** [comment]
https://horrorcharnel.org/ returns ERR_CONNECTION_REFUSED
http://horrorcharnel.org/ returns a centos cwp control test web panel

**Comment by ilike2burnthing** [comment]
back up

sign ups look open, but just repeatedly fail

**Comment by garfield69** [comment]
Yes, I do not think the rebuild is complete yet, as the site does not recognise my login credentials.

**Comment by ilike2burnthing** [comment]
https://horrorcharnel.org/ - ERR_NAME_NOT_RESOLVED

**Comment by ilike2burnthing** [comment]
Tracker was supposedly left for dead last week - https://torrentinvites.org/f31/thehorrorcharnel-news-608848/

But now showing:
![image](https://user-images.githubusercontent.com/59480337/190513414-39385c48-7cd3-45cb-aa36-d4f4d5af98d1.png)

**Comment by garfield69** [comment]
v0.20.2086

**Comment by ilike2burnthing** [comment]
@garfield69 a somewhat broken login page is up now. Are you able to login? If so, does the old indexer work?

**Comment by garfield69** [comment]
my credentials were not recognized.
