### ISSUE TITLE
[Req] https://tracker.tekno3d.com

### ISSUE THREAD

**Issue by killerqueen619** [Jackett/Jackett#5615]
Tracker Name  Tekno3d.com
Tracker URL  tracker.tekno3d.com
Genre  UHD/HDR

but not available invite, 
can i message my user pass ?

**Comment by garfield69** [comment]
send login details garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by killerqueen619** [comment]
@garfield69 i've sent you the login data
please check

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.761

**Comment by killerqueen619** [comment]
thank you for your work.

**Comment by handokota** [comment]
https://tracker.tekno3d.com/
- Redirected to GoDaddy, domain for sale
- error: 522 No Reason Phrase
- Http Secure Channel Failure
- ERR_SSL_UNRECOGNIZED_NAME_ALERT

using http gets redirected to https://forsale.godaddy.com/forsale/techno3d.com?utm_source=TDFS_BINNS2&utm_medium=parkedpages&utm_campaign=x_corp_tdfs-binns2_base&traffic_type=TDFS_BINNS2&traffic_id=binns2&

**Comment by garfield69** [comment]
v0.24.2451
