### ISSUE TITLE
[Req] ScenePalace

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5617]
Signup link: https://scenepalace.info/signup.php

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.501

**Comment by garfield69** [comment]
https://scenepalace.info/ returning ERR_NAME_RESOLUTION_FAILED
just me, or has the site gone, or is broken, or has moved to a new domain?

**Comment by garfield69** [comment]
back online

**Comment by ilike2burnthing** [comment]
https://scenepalace.info/ - ERR_NAME_NOT_RESOLVED

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://scenepalace.info/ returning DNS_PROBE_FINISHED_NXDOMAIN
domain not found, just me?

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://scenepalace.info/ - ERR_NAME_NOT_RESOLVED

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
oops, its sceneplace that is online NOT scenepalace
scenepalace indexer is due to be removed on jan 11 2023 if not online by then.

**Comment by garfield69** [comment]
v0.20.2614
