### ISSUE TITLE
Newpct dont show/find nothing with Radarr

### ISSUE THREAD

**Issue by nickmers** [Jackett/Jackett#5618]
Hello, sorry for my english. I have this indexer in jackett with the new domain https://descargas2020.org/. Working good in Sonarr but in Radarr dont show/find nothing. Is just my fault or this is happend for more users? Thanks

**Comment by Yllelder** [comment]
If you enter the page, the search is broken. I click the search button and it takes me to the main page.

If it doesn't work normally, I don't think it can work on Jackett.

**Comment by nickmers** [comment]
Yes that its true but work with sonarr good. Just with radarr dont work maybe is cause you golf but its strange

**Comment by DAVIZINH0** [comment]
Hello again.
Now the search works perfect in the jackett web when i search a tvshows. But when i search a movie dont show results.

If i dont search nothing and filter by movies, apears some movies. 
But not if search for a movie.

Maybe the search is broken for movies?
can i give you more info i you say to me what need

Thanks a lot!!

**Comment by ngosang** [comment]
@snamds added a new feature to remove the year => #7597
Could you try this?

**Comment by ngosang** [comment]
@garfield69 #7927 don't fix this issue. I will review this in detail.

**Comment by garfield69** [comment]
Jackett 0.16.127
