### ISSUE TITLE
[pwtorrents] Exception (pwtorrents): Request to https://pwtorrents.net/browse.php?incldead=1

### ISSUE THREAD

**Issue by mouzzampk2014-zz** [Jackett/Jackett#5629]
Hi, was working fine but stopped few days go. But I can visit website and login only Jackett not connecting. Thank you

**Comment by garfield69** [comment]
pwtorrents have added a seedbox download link column to the results, so the seeders and leechers columns are now out by one place. 
the next jackett release will resolve, when ever that gets published.

**Comment by mouzzampk2014** [comment]
Thank you please. You are great
