### ISSUE TITLE
[jpopsuki] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by mouzzampk2014** [Jackett/Jackett#5630]
Hi, I can login to website directly but jackett unable to test and connect. Thank you

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.
