### ISSUE TITLE
Improve definition format documentation

### ISSUE THREAD

**Issue by Yllelder** [Jackett/Jackett#5648]
I don't know if this is the right place to ask for this, but... Would it be possible to improve the documentation on the [definition format](https://github.com/Jackett/Jackett/wiki/Definition-format) of YAML files?

The documentation is rather short and I think that by improving the documentation, many more people could understand how the definitions work and fix the possible errors that arise after each update.

Thank you ;)

**Comment by ngosang** [comment]
@garfield69 do you think we can improve that page? I see a lot of things there...

**Comment by garfield69** [comment]
I'm too used to seeing whats there that I cannot get a perspective on what is apparently wrong with it.
highlight some issue for me and I'll take another look.

**Comment by ngosang** [comment]
I think the doc is enough. You can close the issue.
Just one thing. Document the `andmatch` filter. Maybe there are more filters undocumented.

**Comment by garfield69** [comment]
the andmatch is documented
```json
    rows:
      selector: table#sortabletable > tbody > tr:has(a[href*="/details.php?id="])
      filters: # optional list of row filter
        - name: andmatch # The andmatch filter will make sure that only torrents which
                         # contain all words from the search string are returned.
                         # This is helpful if the tracker returns a lot of unrelated
                         # search results.
```
it is not listed in the filters section further down because this is a **row** filter not a **field** filter.
