### ISSUE TITLE
[nostalgic] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#5654]
Either with test button or with manual search

**Comment by garfield69** [comment]
works for me.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by skuizy** [comment]
Yeah works for me too !

Reading the enhanced log, I understand that I wasn't loged in.... Bad copy/pasta of my credentials...

Sorry about that !
