### ISSUE TITLE
[nordicbits] Cannot add tracker - Parse error?

### ISSUE THREAD

**Issue by Johan1976** [Jackett/Jackett#5659]
Cannot add NordicBits. Test fails.
Seems to be parsing error.

[nordicbits] Exception (nordicbits): Object reference not set to an instance of an object.: Parse error (Config)

Using DarkV2 theme.

[log.txt](https://github.com/Jackett/Jackett/files/3388948/log.txt)

**Jackett version**:   0.11.487.0

**Comment by garfield69** [comment]
your log shows that your torrent listing is spilt by days, which the jackett nordicbits indexer is not set up to handle.
login to your nordicbits account, go to the *torrent options* in your account settings, and **uncheck** the *Split Torrent by Days* option and save.
Then try adding the indexer in Jackett.
Report success or failure.
If failure, then provide the new log again so we can take a look at what next its tripping up on ;-)

**Comment by Johan1976** [comment]
Wow! So simple, yet (for me) impossible to figure out!

Thanks a million. Works perfect now 😘
