### ISSUE TITLE
[BakaBT] Every entry has season 1 appended to it. Also audio and manga are being shown under category tv/anime.

### ISSUE THREAD

**Issue by NGRichter** [Jackett/Jackett#5664]
When searching for anime in BakaBT the word season 1 always get appended to the title. Also manga and audio are being shown under the category of tv/anime. 
When searching for anime in Sonarr these torrents almost never show up or gets selected for download.
Please see the attached screenshot to see what happens.
I am currently on the latest version v0.11.487.
![Example](https://user-images.githubusercontent.com/22129925/61184795-02710080-a652-11e9-8816-95cef5221c18.png)

**Comment by garfield69** [comment]
if you want us to correct the categories then it would be helpful to see the html generated, as I don't have an account on bakabg.
 by enabling `Enhanced logging` via the web interface (followed by clicking on the `Apply Server Settings` button). 
do a search on bakabt.
then find the log.txt stored in `%ProgramData%\Jackett` on Windows and `~/.config/Jackett/` on Linux/macOS and drag drop here, after redacting personal info for security with a plain text editor.

**Comment by MrDemocracy** [comment]
Here are some logs and the html file @garfield69: [Jackett log.zip](https://github.com/Jackett/Jackett/files/4513433/Jackett.log.zip)

**Comment by garfield69** [comment]
None of the team have an account on BakaBT.

It will really be useful if either one of you has an invite you can send to 
garfieldsixtynine -at- gmail.com 
so that I can properly test my changes instead of having to do this blind and publish in the hope I haven't made errors.
If this was an yaml indexer I could do this with my eyes closed, 
but the indexer is written in C# and is more complex. 

Failing an invite, temporary access to an account would also achieve the desired result.

**Comment by MrDemocracy** [comment]
As far as I know the only way to get an invite, is by having an interview on IRC with bakabt staff.
[Here's their wiki page explaining the process.](http://wiki.bakabt.me/index.php/Sign_up)

**Comment by garfield69** [comment]
yeah nah. I am not a contributer I will not pass muster.
I'll bump this to the C# devs who are more familiar with the language.
suggested cats:
```C#
        public BakaBT(IIndexerConfigurationService configService, Utils.Clients.WebClient wc, Logger l, IProtectionService ps)
            : base(name: "BakaBT",
                description: "Anime Comunity",
                link: "https://bakabt.me/",
                caps: new TorznabCapabilities(),
                configService: configService,
                client: wc,
                logger: l,
                p: ps,
                configData: new ConfigurationDataBasicLogin("To prevent 0-results-error, Enable the Show-Adult-Content option in your BakaBT account Settings."))
        {
            Encoding = Encoding.UTF8;
            Language = "en-us";
            Type = "private";
            AddCategoryMapping(1, TorznabCatType.TVAnime, "Anime Series");
            AddCategoryMapping(2, TorznabCatType.TVAnime, "OVA");
            AddCategoryMapping(3, TorznabCatType.AudioOther, "Soundtrack");
            AddCategoryMapping(4, TorznabCatType.BooksComics, "Manga");
            AddCategoryMapping(5, TorznabCatType.TVAnime, "Anime Movie");
            AddCategoryMapping(6, TorznabCatType.TVOTHER, "Live Action");
            AddCategoryMapping(7, TorznabCatType.BooksOther, "Artbook");
            AddCategoryMapping(8, TorznabCatType.AudioVideo, "Music Video");
            AddCategoryMapping(9, TorznabCatType.BooksEbook, "Light Novel");
        }
```

**Comment by ngosang** [comment]
We need an account to test.
Maybe those of you who are inside can contact the administrator and pass this link to them.

**Comment by MrDemocracy** [comment]
There isn't really an easy way to get in contact with the administrator. The quickest way to get an account is [sign up by interview](http://wiki.bakabt.me/index.php/Sign_up#Getting_invited). They mostly just want to see if you know what a private tracker is and how their ratio system works.

**Comment by just-an-alt** [comment]
@garfield69 The "Season 1"  issue is still there, are you sure this issue should be closed?
