### ISSUE TITLE
API KEY Issues

### ISSUE THREAD

**Issue by RikT** [Jackett/Jackett#5667]
It seems that every time I restart My machine Jackett creates a different key rendering all my site unreachable via sonarr.
OS: Ubuntu18.04
Version 0.11.487.0
Frequency every reboot  Log attached

[log.txt](https://github.com/Jackett/Jackett/files/3393465/log.txt)

**Comment by garfield69** [comment]
the answer is in the second line of your log
`Error Error writing config file /home/rikt/.config/Jackett/ServerConfig.json System.UnauthorizedAccessException: Access to the path '/home/rikt/.config/Jackett/ServerConfig.json' is denied. ---> System.IO.IOException: Permission denied`, hence the newly generated api key and settings reset at startup.
so you have a file permission issue.
