### ISSUE TITLE
[Req] Support for theaudioscene.net

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5669]
Signup link: https://theaudioscene.net/registration/registration.php

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.510

**Comment by garfield69** [comment]
https://theaudioscene.net/ returning ERR_CONNECTION_TIMED_OUT
just me, or is the site broken, gone, or moved to a new domain?

**Comment by garfield69** [comment]
back online.

**Comment by garfield69** [comment]
https://theaudioscene.net/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://theaudioscene.net/ returns DNS_PROBE_FINISHED_NXDOMAIN (domain not found)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://theaudioscene.net/ returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://theaudioscene.net/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.20.2486
