### ISSUE TITLE
[REQ] Wordwidetorrents and comics category

### ISSUE THREAD

**Issue by rvansoest** [Jackett/Jackett#567]
Is it possible to add support for worldwidetorrents.eu ? Also a category comics and/or books would be nice.  So I could use it in mylar.

**Comment by kaso17** [comment]
is this a public tracker?

**Comment by rvansoest** [comment]
Yes, the url is https://worldwidetorrents.eu

**Comment by kaso17** [comment]
@flightlevel what's the policy regarding public trackers?

**Comment by kaso17** [comment]
The official Jackett version won't support public trackers. But there are other forks with support for public trackers. Try opening an issue there.
