### ISSUE TITLE
[Req] Add : La Pause Torrents : French private tracker

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#5674]
Name : La Pause Torrents
URL : [https://tempsdepause.eu/](https://tempsdepause.eu/)
Genre : General, Video
Privacy : Private tracker
Language : French tracker

Inscriptions are open right now.

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.513

**Comment by pipopop** [comment]
Work fine ! thank you again !
