### ISSUE TITLE
[Req] Demonoid 

### ISSUE THREAD

**Issue by neuman1812** [Jackett/Jackett#5678]
### Have you read our Contributing Guidelines?

- [ ] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [ ] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: Demonoid
- URL: https://www.demonoid.is
- Description: Demonoid is a Semi-Private torrent site for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): None
- Additional Comments: The site still has a screwed up logging in process.
```
alternates: 
https://www.dnoid.to/

**Comment by garfield69** [comment]
the new demonoid is back by name only, the html while retaining the look/flavour of the original, is different, so the original jackett c# indexer is no good.
I've written a cardigann yaml indexer, but I am currently getting `An error occurred while sending the request.: The request was aborted: Could not create SSL/TLS secure channel. ` when trying to test it with https://www.dnoid.to/files/?c118=1&c115=1&lang=0&incldead=0&search=&sort=id&order=desc which works via browser direct. 
Although I'm also getting cloudflare 502 bad gateway atm using the browser.

Given the site is only 6 days old it is probably going to be many adjustments/changes before it settles down. 
Makes sense for now to wait a bit and try again later.

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.502

**Comment by neuman1812** [comment]
Looks like it might have gone semi-private.   I just upgraded and tried. 

2019-07-26 11:32:04.4956 Info CardigannIndexer (demonoid): Relogin required 
2019-07-26 11:32:05.4662 Info Manual search for "Avengers" on demonoid with 0 results. 
2019-07-26 11:34:07.3683 Info CardigannIndexer (demonoid): Relogin required 
2019-07-26 11:34:07.7566 Info Manual search for "Godzilla" on demonoid with 0 results. 
2019-07-26 11:34:39.6126 Info CardigannIndexer (demonoid): Relogin required 
2019-07-26 11:34:39.7739 Info Manual search for "Godzilla" on demonoid with 0 results. 
2019-07-26 11:36:19.9143 Info CardigannIndexer (demonoid): Relogin required 
2019-07-26 11:36:20.0563 Info Manual search for "Godzilla" on demonoid with 0 results. 

--I checked the site several torrents exist for Godzilla

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/61975786-2c58f880-b03e-11e9-8fae-bc9fd67f3f4e.png)
I thought I would wait to see if they go back to public like they posted.
If it has not happened in a couple days I can set it to private and add the login code.

**Comment by neuman1812** [comment]
Thanks.  If you need an account to test,  mine is  active.

**Comment by garfield69** [comment]
Thanks, but I have an account, I registered on the 20th when I wrote the jackett indexer for the web site.

**Comment by garfield69** [comment]
switched to private mode with jackett 0.11.542

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/62342862-7d845300-b53c-11e9-96a1-59186bb4d58d.png)
reverting back to public. jackett pre-release 0.11.555

**Comment by garfield69** [comment]
https://www.demonoid.is/ returning Error 502 Bad gateway

**Comment by ilike2burnthing** [comment]
back up, but...
```
Newspost - August 31st, 2020
Members only
We are performing some changes to the site code and in order to avoid downtime we are temporarily allowing just registered members to visit.
The access will be restored to everyone as soon as possible.
```
Also currently presenting Cloudflare's DDoS protection hcaptcha challenge.

Not sure if all that is enough to consider it as still being 'down' (or rather, inaccessible for Jackett).

**Comment by ilike2burnthing** [comment]
Back down with Error 502 Bad gateway

**Comment by ilike2burnthing** [comment]
back up, but with Cloudflare and members only

**Comment by ilike2burnthing** [comment]
`Update: Guest access has been restored.`

**Comment by ilike2burnthing** [comment]
https://demonoid.is/top_torrents.php - working

https://demonoid.is/files/?query=720p - members only at the moment

**Comment by ilike2burnthing** [comment]
https://demonoid.is/ - Error 502 - Bad gateway

**Comment by ilike2burnthing** [comment]
https://demonoid.is/ - ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/95685709-0bd28980-0c56-11eb-9c47-b052271084f4.png)

**Comment by garfield69** [comment]
but my indexer (which uses my demonoid account on https://www.demonoid.is/) is working and now so does https://www.demonoid.is/files/?category=0&subcategory=All&quality=All&seeded=2&external=2&query=&uid=0&sort= for me.

**Comment by ilike2burnthing** [comment]
Are you still getting that cert error when you access Demonoid? I'm getting:
![demonoid](https://user-images.githubusercontent.com/59480337/95688130-b4a1ca00-0bff-11eb-92cf-10b5312cc689.png)
Thumbprint: 1BDD21D85DB92A346E91F43EBE79278A23B59B4D

https://www.demonoid.is/files/?category=0&subcategory=All&quality=All&seeded=2&external=2&query=&uid=0&sort= (or just https://www.demonoid.is/files/) and https://www.demonoid.is/top_torrents.php are accessible by guests at the moment, but searching isn't.

Although, given that we currently have Demonoid marked as Semi-private, I suppose that shouldn't actually be a reason to mark it as being down.

**Comment by garfield69** [comment]
cert is valid now, must have been a temporary issue with the demonoid service provider.

**Comment by ilike2burnthing** [comment]
Change is coming...
https://beta.demonoid.is/

**Comment by ilike2burnthing** [comment]
https://www.demonoid.is/ - Error 521 - Web server is down

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.demonoid.is/ - Error 504 - Gateway time-out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.demonoid.is/ returning Error 504 Gateway time-out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.demonoid.is/
![demonoid](https://user-images.githubusercontent.com/59480337/119646193-c9417400-be16-11eb-9dff-82af99c5fcbd.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.demonoid.is/ - Error 523 - Origin is unreachable

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.demonoid.is/ - ERR_NAME_NOT_RESOLVED

Up in a few locations - https://www.uptrends.com/tools/uptime?toolRequestGuid=c28649d9-cf65-43f3-99d3-b2fd69c6cb83

Other domains working fine. I'd guess it'll be back up in a few days. I've mentioned it in the IRC, but didn't get any reply after a few mins.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.demonoid.is/ has been offline since 12 hours prior to this post. 
```
Maintenance

We are currently performing the daily site maintenance.
We will be back soon
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.demonoid.is/ - Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.demonoid.is/ - We are currently performing the daily site maintenance.
We will be back soon.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/5678#issuecomment-1641797143

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/5678#issuecomment-1641797143

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.demonoid.is/ Maintenance We are currently performing the daily site maintenance. We will be back soon

**Comment by ilike2burnthing** [comment]
back up

**Comment by AARON8888** [comment]
It is running. I have just checked now.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/5678#issuecomment-1117578052

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/5678#issuecomment-1731948671

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/5678#issuecomment-1731948671

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/5678#issuecomment-1731948671

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/5678#issuecomment-1731948671

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/5678#issuecomment-1452399354

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/5678#issuecomment-1853160351

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
- https://github.com/Jackett/Jackett/issues/5678#issuecomment-1452399354
- https://github.com/Jackett/Jackett/issues/5678#issuecomment-1117578052

**Comment by garfield69** [comment]
v0.21.2658

**Comment by ilike2burnthing** [comment]
https://www.demonoid.is/ - Maintenance in progress

**Comment by garfield69** [comment]
this indexer was removed with v0.21.2658
are you just marking it as pending restoration?

**Comment by garfield69** [comment]
Wow, zombie.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/15425 is back online

**Comment by garfield69** [comment]
is https://demonoid.torrentbay.st/ working for anybody?
And I presume https://www.dnoid.pw/ is obsolete?

**Comment by garfield69** [comment]
v0.22.164

**Comment by Tmp341** [comment]
> is https://demonoid.torrentbay.st/ working for anybody? And I presume https://www.dnoid.pw/ is obsolete?

* https://www.dnoid.pw/ led to some ad site (blocked by anti-adblock extension)
* https://demonoid.torrentbay.st/ led to blank page, but the main site works it seems. Opening from there is the same result tho.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/7575946030a34e388b3dc60cfa9ff97251703db8

**Comment by garfield69** [comment]
https://www.demonoid.is/ Maintenance in progress

**Comment by garfield69** [comment]
v0.22.497
