### ISSUE TITLE
[Amigos-share] Improve search

### ISSUE THREAD

**Issue by mvnitro** [Jackett/Jackett#5682]
Hi

The search system of this tracker is not very good I would like to know if I can include "%" between the name of the series and the season as I explain below

Search for: "Vikings s04"

He only finds exactly the title "Vikings s04" if he has a result like "Vikings - s04" or "Vikings.s04" or "Vikings (s04)" he can not find the torrent

testing the direct search in the jacket doing as below it can find all the torrent that in the case have the word "vikings" and "s04" even being separated by another term

Correct search: "Vikings% s04"

That way he can find all the torrents correctly, my doubt is how to include this "%" between the name of the series and the season direct on the jackett

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.495
I've replaced spaces with % in search requests, updated the categories and added the grabs column.

**Comment by mvnitro** [comment]
Many thanks @ garfield69 now jackett is locating the torrents! I am with another problem I believe I related to the language but I will open another topic to be more organized!
