### ISSUE TITLE
How to make requests to the indexers from the machine running Jackett?

### ISSUE THREAD

**Issue by ananchev** [Jackett/Jackett#5684]
To what I understand, requests to the added indexers are made from the 'client' machine connected to Jackett. 
What would be the way to configure Jackett so requests go out from the machine where it is running / hosted?

**Comment by rrrevin** [comment]
I have Sonarr, which is using Jackett as it's Indexer, running on the same system. Is that what you are trying to do? You can either setup Sonarr to use its own IP, or "localhost" as the IP to connect to for it's Jackett host. As they are running on the same host, this works.

**Comment by ananchev** [comment]
So far I have only tried the manual search in Jackett. It is running on a VM within home network and I am accessing it via ssh tunnel from another machine outside of  home network. 
The thing is, I observe that the requests to the indexers are go via the client pc (most of indexers blocked from its network), and not the home network IP range from where the indexers are accessible. 
![diagram](https://user-images.githubusercontent.com/34111833/61540736-80604d80-aa3e-11e9-90db-51c7aaae16ad.png)

**Comment by ngosang** [comment]
@ananchev This is not a jackett problem. You have to configure your Client PC to send all your requests through the SSH tunnel. You can install OpenVPN server in the same machine you are running Jackett.
