### ISSUE TITLE
Partial Macthing instead of Full Matching text

### ISSUE THREAD

**Issue by sandi-rizky** [Jackett/Jackett#569]
Hello,

I used this awesome tools integrated with Sonarr. it is cool.
But I have a trouble to grab a return from Jackett.

Sonar always give Season followed by Episode, but not all the show need Season naming in it (just like anime, or any reality show -Running Man in Avistaz.to- in my case)

posted in Sonarr forum, it might be your reference: [https://forums.sonarr.tv/t/better-episode-naming-for-searching-search-episode-naming-jackett/12454](https://forums.sonarr.tv/t/better-episode-naming-for-searching-search-episode-naming-jackett/12454)

Is there any chance to get this working?
Appreciate for any help!

**Comment by kaso17** [comment]
Even if sonarr would return the corresponding results sonarr wouldn't accept them
This needs to be fixed on the sonarr side.
Try setting sonarr to Anime mode for the series.

**Comment by FevLoad** [comment]
any updates regarding this issue,still happening with Avistaz site.
