### ISSUE TITLE
Remove .BAK file from config folder with JSON 

### ISSUE THREAD

**Issue by mouzzampk2014** [Jackett/Jackett#5692]
Hi, I deleted few trackers from my Jackett Web UI. I can see JSON file remove straightaway from config folder but BAK file left on its own. Is it possible to tell Jackett to delete both files? Thank you so much

**Comment by mouzzampk2014** [comment]
Thank you so much. Much appreciated

**Comment by garfield69** [comment]
jackett v0.11.643 should include the requested enhancement.
