### ISSUE TITLE
[mteamtp] Login Failed, got redirected. Try changing the indexer URL to https://pt.m-team.cc/. (Config)

### ISSUE THREAD

**Issue by yimingzhaomath** [Jackett/Jackett#5693]
Hi,

Just found out that there is trouble connecting to MTeam. 

Their site is reachable via browser.

**Comment by yimingzhaomath** [comment]
Looks good now, miraculously. Closing this ticket.

**Comment by hoong7** [comment]
> Looks good now, miraculously. Closing this ticket.

how to fix it? i got the same problem...
