### ISSUE TITLE
[REQ] Add tracker http://zamunda.net/

### ISSUE THREAD

**Issue by recyzzz** [Jackett/Jackett#57]
Add tracker http://zamunda.net/
tnx

**Comment by raspdealer** [comment]
Hi @recyzzz ,

Please take a look here: https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker

**Comment by recyzzz** [comment]
Please, would you send me your email so i can send you invitation.

AddCategoryMapping("12", TorznabCatType.Console);
//AddCategoryMapping("307", TorznabCatType.ConsoleNDS);
AddCategoryMapping("17", TorznabCatType.ConsolePSP);
//AddCategoryMapping("307", TorznabCatType.ConsoleWii);
AddCategoryMapping("40", TorznabCatType.ConsoleXbox);
AddCategoryMapping("40", TorznabCatType.ConsoleXbox360);
//AddCategoryMapping("307", TorznabCatType.ConsoleWiiwareVC);
//AddCategoryMapping("40", TorznabCatType.ConsoleXBOX360DLC);
AddCategoryMapping("17", TorznabCatType.ConsolePS3);
//AddCategoryMapping("239", TorznabCatType.ConsoleOther);
//AddCategoryMapping("245", TorznabCatType.ConsoleOther);
//AddCategoryMapping("246", TorznabCatType.ConsoleOther);
//AddCategoryMapping("626", TorznabCatType.ConsoleOther);
//AddCategoryMapping("628", TorznabCatType.ConsoleOther);
//AddCategoryMapping("630", TorznabCatType.ConsoleOther);
//AddCategoryMapping("307", TorznabCatType.Console3DS);
AddCategoryMapping("317", TorznabCatType.ConsolePSVita);
//AddCategoryMapping("307", TorznabCatType.ConsoleWiiU);
//AddCategoryMapping("40", TorznabCatType.ConsoleXboxOne);
AddCategoryMapping("17", TorznabCatType.ConsolePS4);
//AddCategoryMapping("631", TorznabCatType.Movies);
AddCategoryMapping("24", TorznabCatType.MoviesForeign);
AddCategoryMapping("28", TorznabCatType.MoviesForeign);
//AddCategoryMapping("455", TorznabCatType.MoviesOther);
//AddCategoryMapping("633", TorznabCatType.MoviesOther);
AddCategoryMapping("19", TorznabCatType.MoviesSD);
AddCategoryMapping("5", TorznabCatType.MoviesHD);
AddCategoryMapping("46", TorznabCatType.Movies3D);
AddCategoryMapping("42", TorznabCatType.MoviesBluRay);
AddCategoryMapping("20", TorznabCatType.MoviesDVD);
//AddCategoryMapping("631", TorznabCatType.MoviesWEBDL);
AddCategoryMapping("6", TorznabCatType.Audio);
//AddCategoryMapping("623", TorznabCatType.AudioMP3);
//AddCategoryMapping("400", TorznabCatType.AudioVideo);
//AddCategoryMapping("402", TorznabCatType.AudioVideo);
//AddCategoryMapping("405", TorznabCatType.AudioAudiobook);
AddCategoryMapping("34", TorznabCatType.AudioLossless);
//AddCategoryMapping("403", TorznabCatType.AudioOther);
//AddCategoryMapping("642", TorznabCatType.AudioOther);
//AddCategoryMapping("1", TorznabCatType.AudioForeign);
//AddCategoryMapping("233", TorznabCatType.PC);
//AddCategoryMapping("236", TorznabCatType.PC);
//AddCategoryMapping("1", TorznabCatType.PC0day);
//AddCategoryMapping("1", TorznabCatType.PCISO);
//AddCategoryMapping("235", TorznabCatType.PCMac);
//AddCategoryMapping("627", TorznabCatType.PCPhoneOther);
AddCategoryMapping("4", TorznabCatType.PCGames);
AddCategoryMapping("21", TorznabCatType.PCGames);
//AddCategoryMapping("625", TorznabCatType.PCPhoneIOS);
//AddCategoryMapping("625", TorznabCatType.PCPhoneAndroid);
AddCategoryMapping("7", TorznabCatType.TV);
AddCategoryMapping("33", TorznabCatType.TV);
//AddCategoryMapping("639", TorznabCatType.TVWEBDL);
//AddCategoryMapping("433", TorznabCatType.TVWEBDL);
//AddCategoryMapping("639", TorznabCatType.TVFOREIGN);
//AddCategoryMapping("433", TorznabCatType.TVFOREIGN);
//AddCategoryMapping("639", TorznabCatType.TVSD);
//AddCategoryMapping("433", TorznabCatType.TVSD);
//AddCategoryMapping("639", TorznabCatType.TVHD);
//AddCategoryMapping("433", TorznabCatType.TVHD);
//AddCategoryMapping("635", TorznabCatType.TVOTHER);
//AddCategoryMapping("636", TorznabCatType.TVSport);
//AddCategoryMapping("637", TorznabCatType.TVAnime);
//AddCategoryMapping("634", TorznabCatType.TVDocumentary);
AddCategoryMapping("9", TorznabCatType.XXX);
//AddCategoryMapping("1", TorznabCatType.XXXDVD);
//AddCategoryMapping("1", TorznabCatType.XXXWMV);
//AddCategoryMapping("1", TorznabCatType.XXXXviD);
//AddCategoryMapping("1", TorznabCatType.XXXx264);
//AddCategoryMapping("1", TorznabCatType.XXXOther);
//AddCategoryMapping("1", TorznabCatType.XXXImageset);
//AddCategoryMapping("1", TorznabCatType.XXXPacks);
//AddCategoryMapping("629", TorznabCatType.Other);
//AddCategoryMapping("1", TorznabCatType.OtherMisc);
//AddCategoryMapping("1", TorznabCatType.OtherHashed);
//AddCategoryMapping("408", TorznabCatType.Books);
//AddCategoryMapping("404", TorznabCatType.BooksEbook);
AddCategoryMapping("32", TorznabCatType.BooksComics);
//AddCategoryMapping("410", TorznabCatType.BooksMagazines);
//AddCategoryMapping("1", TorznabCatType.BooksTechnical);
//AddCategoryMapping("1", TorznabCatType.BooksOther);
//AddCategoryMapping("1", TorznabCatType.BooksForeign);

**Comment by armani316** [comment]
Is this tracker still working? When I click on the link, it says forbidden. Access could be geo-restrcited?

**Comment by petercontact** [comment]
yes they have open sing ups at the moment
http://zelka.org/login.php

**Comment by kaso17** [comment]
I'm getting a timeout too.
Are the geo blocking based on the IP?

**Comment by petercontact** [comment]
kaso did you tried http://zelka.org/login.php too?

**Comment by kaso17** [comment]
This site can’t be reached

zelka.org took too long to respond.

**Comment by armani316** [comment]
@kaso17 @petercontact It seems to be down at the moment. 10 days ago, I was getting a 'forbidden' message.

**Comment by eybox** [comment]
Hi, guys. I'm attempting to build it as a 3rd party solution. If it works, I'll just send it over to the creators of Jackett. Cheers!

**Comment by eybox** [comment]
Ok, the indexer definition for Zamunda.net is finished. It would hopefully end up on the repository here soon.

**Comment by kaso17** [comment]
Added via c87f1b3949b9500762f0be468b3835e3b19998ec

Thank you @eybox

**Comment by garfield69** [comment]
@eybox  do you happen to know what's the matter with zelka.org, I've been getting ERR_CONNECTION_TIMED_OUT for a week now ?
I don't suppose they have gone the same way as zamunda.net and geo-blocked access....

**Comment by eybox** [comment]
Hi, @garfield69,

I'm unaware of what is going on with Zelka, but I would imagine that it might be the case.

Here's some background to that claim: Some time ago, there was in fact only one private Bulgarian tracker - Zamunda.net. . One of the devs stole the domain name, which resulted in the original tracker owners needed to purchase another domain, and they went with Zelka.org. So Zamunda is actually a fork of the original Zamunda.net, and Zelka.org being the actual original tracker. So them having the same content, categories, torrents up is to be expected. The same goes as to what types of security they will be utilizing.
