### ISSUE TITLE
Beyond-HD not working?

### ISSUE THREAD

**Issue by seanvree** [Jackett/Jackett#570]
When I try to configure Beyond-HD, I get the following error:

Error: Object reference not set to an instance of an object.

Oct 24, 2016 05:07:01 AM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
Oct 24, 2016 05:07:01 AM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Oct 24, 2016 05:07:01 AM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Oct 24, 2016 05:07:01 AM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Oct 24, 2016 05:07:01 AM	Info	
HttpActionBinding ExecuteBindingAsync 
Oct 24, 2016 05:07:01 AM	Info	
HttpActionBinding ExecuteBindingAsync 
Oct 24, 2016 05:07:01 AM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Oct 24, 2016 05:07:01 AM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Oct 24, 2016 05:07:01 AM	Info	
ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Oct 24, 2016 05:07:01 AM	Info	
ApiControllerActionSelector SelectAction 
Oct 24, 2016 05:07:01 AM	Info	
AdminController ExecuteAsync 
Oct 24, 2016 05:07:01 AM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Oct 24, 2016 05:07:01 AM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Oct 24, 2016 05:07:01 AM	Info	
DefaultHttpControllerActivator Create 
Oct 24, 2016 05:07:01 AM	Info	
HttpControllerDescriptor CreateController 
Oct 24, 2016 05:07:01 AM	Info	
DefaultHttpControllerSelector SelectController Admin
Oct 24, 2016 05:07:01 AM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Oct 24, 2016 05:07:01 AM	Info	
  http://seanvree.com:9117/Admin/GetLogs?_=1477310809969
Oct 24, 2016 05:06:59 AM	Info	
AdminController Dispose 
Oct 24, 2016 05:06:59 AM	Info	
AdminController Dispose 
Oct 24, 2016 05:06:59 AM	Info	
  Content-type='application/json; charset=utf-8', content-length=82
Oct 24, 2016 05:06:59 AM	Info	
AdminController ExecuteAsync 
Oct 24, 2016 05:06:59 AM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync 
Oct 24, 2016 05:06:59 AM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'GetConfigForm()'
Oct 24, 2016 05:06:59 AM	Info	
ApiControllerActionInvoker InvokeActionAsync 
Oct 24, 2016 05:06:59 AM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
Oct 24, 2016 05:06:59 AM	Error	
Exception in GetConfigForm

**Comment by kaso17** [comment]
please send an invite to kaso1717 -at- gmail.com so I can have a look at it

**Comment by seanvree** [comment]
@kaso17 , I don' thave any invites ATM, but I'll try to snag one.

**Comment by Narkyzz** [comment]
I've sent an invite to the email.
Cheers.

**Comment by kaso17** [comment]
got it, thank you.
The indexer code itself is ok.
It's a problem with the CloudflareUtilities/HTTPClient on Windows, on linux it's working fine for me.
I'll look deeper into this.

**Comment by seanvree** [comment]
@kaso17 

Yeah, it WAS working for like 2 months, and then I came to check on it and it was broke.  I know it's not me as everyone on the indexer forum who is using windows is reporting the same thing.

THANKS!

**Comment by kaso17** [comment]
Ok, fixed it.
It's a bug in the CloudFlareUtilities lib
https://github.com/elcattivo/CloudFlareUtilities/pull/6
If you don't want to wait/compile yourself you can find a compiled version of the fixed dll here:
http://www.filedropper.com/cloudflareutilities
Just replace the one in your Jackett directory.

**Comment by seanvree** [comment]
Works! THANK YOU!
