### ISSUE TITLE
[btdigg] Exception (btdigg): (Error BadGateway)

### ISSUE THREAD

**Issue by jhelmink** [Jackett/Jackett#5703]
**Error Message:**

Exception (btdigg): Request to https://btdig.com/search?q=test&order=2 failed (Error BadGateway) - The tracker seems to be down.: Request to https://btdig.com/search?q=test&order=2 failed (Error BadGateway) - The tracker seems to be down.

**Information:**

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.

*Can confirm that visiting the site directly works fine, no login required, including the URL listed in the error message.*

2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.

*Running the latest as at today: Version 0.11.507.0*

3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

*Please advise if logs are still required*

**Comment by garfield69** [comment]
seems btdigg was checking for a user-agent string in the http get header.
this indexer in the next release of jackett should start working again.

**Comment by garfield69** [comment]
getting a log of ERR_CONNECTION_TIMED_OUT on https://btdig.com
what a pain in the rear caboose
