### ISSUE TITLE
Cannot open jackett webui

### ISSUE THREAD

**Issue by memnos** [Jackett/Jackett#5704]
Hello,
i don't know why but i cannot access jackett anymore from webui.
Also radarr anche sonarr cannot access jackett
I have this error on browser:

`{
  "result": "error",
  "error": "Unable to load one or more of the requested types.\nCould not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The module was expected to contain an assembly manifest.",
  "stacktrace": "   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)\n   at System.Reflection.RuntimeAssembly.get_DefinedTypes()\n   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)\n   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()\n   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()\n   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.get_ActionDescriptors()\n   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()\n   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)\n   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)\n   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29"
}`

I'm using it on UBUNTU
Using Jackett without mono 
Jackett v0.11.507.0

What can i do?

**Comment by garfield69** [comment]
its likely that the jackett updater fell over during an auto-update, there are several tickets open with something similar, which the c# devs have yet to fix.
I suggest you manually install the full jackett package from the latest version at https://github.com/Jackett/Jackett/releases and see if that gets you going again.

**Comment by memnos** [comment]
Tnx,
reinstalling now it works.

**Comment by garfield69** [comment]
if it breaks again after the next auto update, you might want to consider turning auto-updates off for a while.
the disable-auto-updates switch is near the bottom of the jackett dashboard, followed by clicking the apply-server-settings button to activate.
