### ISSUE TITLE
[Req] Support for leporno.org

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5709]
Singup link: http://leporno.org/profile.php?mode=register

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.518

**Comment by garfield69** [comment]
site's tracker.php page constantly redirects to other sites
even for users that are logged in.
just me or is the site broken?

**Comment by garfield69** [comment]
now the site is returning ERR_TOO_MANY_REDIRECTS
looks like it's in trouble.

**Comment by tkdrob** [comment]
Regular access seems to work ok for me. Just the indexer doesn't

**Comment by garfield69** [comment]
@tkdrob yes the site is back up for me now, but I still cannot access the tracker.
are you able to search for torrents via the http://leporno.org/tracker.php link?
all I ever get is re-directions.
the jackett indexer uses this link to search and present the torrent list. 
has the site changed to some other way of searching and returning a list of torrents?

**Comment by garfield69** [comment]
http://leporno.org/ returning cloudflare 522 Connection timed out
just me or is the site broken, gone or moved to a new domain?

**Comment by garfield69** [comment]
http://leporno.org/ now returning cloudflare 521 Web server is down

**Comment by ilike2burnthing** [comment]
http://leporno.org/ - ERR_CONNECTION_TIMED_OUT
