### ISSUE TITLE
[REQ] the-movie-cave.eu

### ISSUE THREAD

**Issue by inasua** [Jackett/Jackett#5710]
private german tracker (open registration atm)

https://the-movie-cave.eu

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.528

**Comment by garfield69** [comment]
https://the-movie-cave.eu/ is returning ERR_CONNECTION_REFUSED
just me, or is the site gone, broken, or moved to a new domain?

**Comment by garfield69** [comment]
@tkdrob  is https://the-movie-cave.eu/ working for you?

**Comment by inasua** [comment]
they have been offline for a few days now

**Comment by garfield69** [comment]
ok, well, I'll give it the usual month and if it does not come back online I'll remove the indexer.
In the event they ever reappear we can always restore it again ;-)
