### ISSUE TITLE
[Req] Support for evolution-palace.net

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5713]
Signup: https://evolution-palace.net/signup.php

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.521

**Comment by garfield69** [comment]
site is gone. 
Apparently users are asked to signup to https://tazmania-den.net/index.php instead.

**Comment by dimqua** [comment]
@garfield69 it seems the site is gone completely.
