### ISSUE TITLE
[Amigos-share] Return filename to

### ISSUE THREAD

**Issue by mvnitro** [Jackett/Jackett#5714]
@garfield69 

It helped me a lot and now I'm getting the torrent on jackett due to its correction in the "%" question regarding the searches

However I can download some series and others not to Sonarr returns me with "unknown series" in series where has a title pattern below and does not download it

Deuses Americanos (American Gods) - S02  or Sobrenatural (Supernatural) - S14

But using the same configuration when I have series as

Game Of Thrones - S03 or Vikings - S04

It works perfectly !

GaGame of thrones is so famous that the people do not even translate and Vikings is by its own name is not translated either but most of the series have the "title in Portuguese (original title) - S01" for example

My question is if I can return to the Sonarr only the English title that is inside () and maybe even delete the () it should cause some error also for the torrent title is for example American gods - S01

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.515
seems to work with Sonarr a bit better
I even managed to append to the title the year, quality, and type, for Sonarr to filter on.
the year is mostly for Radarr movies.

**Comment by mvnitro** [comment]
Hello !!!! 

@garfield69 Worked perfectly ! I just have to thank you !!!!!!!!!!!!! I would give you a kiss (face) of so much joy!

Now we Brazilians have at least one working national tracker !!!! for dubbed content!

In the index list pt-br (Brazil) several trackers are offline such as (Speed-Share, Manicomio Share, Brazil Tracker and B2S-Share) "

I would suggest removing them to make the jackett cleaner and more organized! and I will also create a topic to see if I can add at least 1 or 2 public Brazilian trackers !

Very thanks !!!!!!!
