### ISSUE TITLE
[Req] Support for xtremefile.ro

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5720]
Signup: http://xtremefile.ro/signup.php

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.522

**Comment by garfield69** [comment]
https://xtremefile.ro/ returning internal server error
![image](https://user-images.githubusercontent.com/6933240/74564895-f167e380-4fd4-11ea-9bc6-0921a31531c1.png)

**Comment by garfield69** [comment]
back online.

**Comment by garfield69** [comment]
https://xtremefile.ro/ returning server IP address could not be found.
has the site gone, is broken or moved to a new domain?

**Comment by garfield69** [comment]
note that the Registrar Status is PendingDelete so this domain is disabled.
