### ISSUE TITLE
[Nyoo] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5722]
I am getting no results and the test fails with that message

**Comment by garfield69** [comment]
the nyoo domain https://nyoo.moe/ is being redirected to https://animedaisuki.moe/ which is a different site altogether.
does anyone know if nyoo has closed, or moved to a new domain ?

**Comment by garfield69** [comment]
according to #3088 nyoo has been gone since at least may 2018 so I will remove this tracker.
nyoo was a mirror for Nyaa-pantsu so switch to using that indexer instead.
