### ISSUE TITLE
[zamundanet] 

### ISSUE THREAD

**Issue by vtzarkov** [Jackett/Jackett#5723]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by vtzarkov** [comment]
Jackett Version 0.11.507.0 from docker container
tracker is accessible from browser
[log.txt](https://github.com/Jackett/Jackett/files/3427199/log.txt)

**Comment by garfield69** [comment]
@pidov  is zamunda.net working for you?
the OP appears to be in the torrent LIST mode (not the GRID mode which we know does not work with this indexer), but the HTML seems changed, with the title selector failing to match.

**Comment by dbaldzhiev** [comment]
I can confirm I have the same issue. Installed jackett a week ago.. it was working for few days and yesterday suddenly stopped working.
Jackett Version 0.11.507.0

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.529
I do not have access to zamundanet so this fix is untested. please report success or failure. if failure, the relevant enhanced log will be most useful.

**Comment by dbaldzhiev** [comment]
jackett pre-release 0.11.529 did not work. Here are the logs.
[log.txt](https://github.com/Jackett/Jackett/files/3435454/log.txt)
[log.txt.20190726.00000.txt](https://github.com/Jackett/Jackett/files/3435455/log.txt.20190726.00000.txt)

**Comment by dbaldzhiev** [comment]
CORRECTION. After chaning the layout from GRID mode to LIST mode I got a successful test. Thank you!

**Comment by vtzarkov** [comment]
working for me too
Jackett Version 0.11.542.0
