### ISSUE TITLE
[yggtorrent] Login failed: Selector

### ISSUE THREAD

**Issue by raulkeats** [Jackett/Jackett#5724]
Hello there,

I can't add Yggtorrent in jackett on docker.  Some screen-shots below to help

<img width="547" alt="Capture d’écran 2019-07-24 à 19 16 42" src="https://user-images.githubusercontent.com/16153586/61814428-5c3eab00-ae48-11e9-8bdb-88c12713f2b0.png">

<img width="587" alt="Capture d’écran 2019-07-24 à 19 17 05" src="https://user-images.githubusercontent.com/16153586/61814429-5c3eab00-ae48-11e9-9156-c59a221296c0.png">

### More informations:

Jackett version: 0.11.507.0

Log: `
When | Level | Message
-- | -- | --
Jul 24, 2019 07:17:23 PM | Error | Jackett.Common.ExceptionWithConfigData: Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match    at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 703    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 870    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

`

I hope it can help.

**Comment by garfield69** [comment]
I suspect you are being blocked or redirected. but to confirm this you need to do 2 things:
1. using a browser on the same system as the one you are running jackett on, login to ygg and confirm that your account has no outstanding alerts, such as low ratio, suspension, banning, etc.
2. if it looks all clear, then we need to see the html returned while you try to use jackett. 
so please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by raulkeats** [comment]
Sorry for the delay, here is the file.

[log.txt](https://github.com/Jackett/Jackett/files/3458235/log.txt)

Btw: Point 1 is Ok = no ban,low ratio etc...

**Comment by garfield69** [comment]
the log shows that the ygg indexer was not logged in when it checked that the logout link was present.
but I cannot see any explanation for why the login did not succeed, the usual 4 error messages are not present: banned/credentials/confirmation-email-pending/ratio

the only conclusion I can make at this stage is that you did not fill in the username and password fields in the jackett yggtorrent config, as this is one way that I can replicate your problem.

Please edit the ygg config from your jackett dashboard, and enter your username and password again, and see if that returns a good login, or at least a message other than `Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match`

**Comment by raulkeats** [comment]
You right!!!! 
I'm using auto complete with Safari on my mac and it fills the fields.
I enter manually the fields and it works perfectly.
Thank you for your help
