### ISSUE TITLE
Support for public tracker Brazil 

### ISSUE THREAD

**Issue by mvnitro** [Jackett/Jackett#5725]
I would like to know if it is possible to add any of the tracker below, I am putting a list of trackers because in case of error with one can try another, all are public from Brazil.

Today Brazilian tracker on jackett we have Bj-share and Friends-share the rest is not working, BJ-share is extremely difficult to get an invite and friends-share is relatively new and with few seed and torrents compared to BJ and another big one.

So these public trackers would come to complete the national tracker demand (Brazil)

If it is possible to add 2 of these would be very good!

https://www.bludv.tv/
https://www.baixarfilmetorrent.net/
https://piratetorrent.org/
https://www.thepiratefilmeshd.biz/

**Comment by garfield69** [comment]
I would prefer that you raise a separate request for each tracker so I can manage and track the progress of each separately.
label each issue with `[REQ] Brazillian Public  - tracker name`  and put the relevant link in the issue body.

thanks.

**Comment by mvnitro** [comment]
ok thanks i will do that!
