### ISSUE TITLE
[Req] Support for ebookparadijs.org

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5726]
Signup: https://www.ebookparadijs.org/signup.php

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.527

**Comment by garfield69** [comment]
v0.20.492

**Comment by garfield69** [comment]
https://www.ebookparadijs.org/ returns ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
v0.20.2122
