### ISSUE TITLE
[teamhd] Error: Ошибка входа (1)Please check on the reCAPTCHA box. (Config)

### ISSUE THREAD

**Issue by Prosecutor** [Jackett/Jackett#5728]
Heya!

Could you please add reCAPTCHA to TeamHD tracker? Can't add it anymore.

Log: [Pastebin](https://pastebin.com/cAVehGE5)

Regards,
V.B.

**Comment by garfield69** [comment]
jackett cannot solve the google reCaptcha. Best we can do is set up login via cookies.
try out jackett pre-release 0.11.525

**Comment by Prosecutor** [comment]
Login Failed, got redirected. (Config).

Log: https://pastebin.com/7iPWRaMC

**Comment by garfield69** [comment]
works for me.
did you login to teamhd on a browser on the same PC that is running jackett?
did you select and copy the correct cookie string from the request-heasers section on the headers tab of the network page?
the cookie string looks something like this `PHPSESSID=uredactedredactedredacted7; uid=1234; pass=8redactedredactedredacted3; lang=russian`

**Comment by Prosecutor** [comment]
So i should login on the same machine where is jackett up?

**Comment by garfield69** [comment]
yes

**Comment by Prosecutor** [comment]
Okay, that's why it's happening to me.
