### ISSUE TITLE
[REQ] Brazilian Public - megatorrentshd

### ISSUE THREAD

**Issue by mvnitro** [Jackett/Jackett#5730]
http://www.megatorrentshd.org/

**Comment by garfield69** [comment]
this site has single entry search results leading to multiple downloads (one for every TV episode, or one for every quality of movie)
also most of the title are Brazilian without an English equivalent. A few have the English in brackets)

as such it is not suitable for Cardigann processing.
Could be coded in c# but the lack of English titles will not make it useful for Sonarr or Radarr, just for manual searching from the jackett dashboard.

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
