### ISSUE TITLE
[REQ] Comando Torrents

### ISSUE THREAD

**Issue by mvnitro** [Jackett/Jackett#5731]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Comando Torrents
- URL: https://comandotorrents.to/
- Description: Popular Brazilian Tracker
```

**Comment by garfield69** [comment]
this site has single entry search results leading to multiple downloads (one for every TV episode, or one for every quality of movie)

as such it is not suitable for Cardigann processing. Will need coding in c#

**Comment by ilike2burnthing** [comment]
ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
closing as stale.
