### ISSUE TITLE
[Amigos-share] Radarr does not find

### ISSUE THREAD

**Issue by mvnitro** [Jackett/Jackett#5732]
you already got enough amigos-share and in the sonarr it is working very well thanks!

But I installed radarr and the search engine is not locating the movies from what I understand because the friends-share site does not bring the year of the movie in its name.

Example sonar searches for "Split 2019" but the name of the movie on the site is "Fragmented (Split)"

![image](https://user-images.githubusercontent.com/50275537/61876252-d14ec680-aec2-11e9-9e0d-b9b91e91d469.png)

of the many movies I added he could find only 2 of them was the "Bohemian Rhapsody" I think because in that case there is the year in the name of the movie

![image](https://user-images.githubusercontent.com/50275537/61876535-78336280-aec3-11e9-9dd6-327f89d60dde.png)

**Comment by garfield69** [comment]
so we strip the year from the query. amigo-share should then return some movies, and radarr can filter out movies with the same name but different year and give the correct result.
try out jackett pre-release 0.11.526

**Comment by mvnitro** [comment]
Hi

Seems to have resolved in radarr however in the sonarr that was working stopped i think is getting the information twice as date quality etc

19-7-25 22:14:58.3|Debug|AcceptableSizeSpecification|Beginning size check for: The Flash - S05 2019 720p WEB-DL
19-7-25 22:14:58.3|Debug|AcceptableSizeSpecification|Max size is unlimited - skipping check.
19-7-25 22:14:58.3|Debug|AcceptableSizeSpecification|Item: The Flash - S05 2019 720p WEB-DL, meets size constraints.
19-7-25 22:14:58.3|Debug|FullSeasonSpecification|Checking if all episodes in full season release have aired. The Flash - S05 2019 720p WEB-DL
19-7-25 22:14:58.3|Debug|MaximumSizeSpecification|Maximum size is not set.
19-7-25 22:14:58.3|Debug|LanguageSpecification|Checking if report meets language requirements. English
19-7-25 22:14:58.3|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: The Flash - S05 2019 720p WEB-DL
19-7-25 22:14:58.3|Debug|ReleaseRestrictionsSpecification|[The Flash - S05 2019 720p WEB-DL] No restrictions apply, allowing
19-7-25 22:14:58.4|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. WEBDL-720p v1
19-7-25 22:14:58.4|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
19-7-25 22:14:58.4|Debug|RetentionSpecification|Not checking retention requirement for non-usenet report
19-7-25 22:14:58.4|Debug|SeriesSpecification|Checking if series matches searched series
19-7-25 22:14:58.4|Debug|DelaySpecification|Ignoring delay for user invoked search
19-7-25 22:14:58.4|Debug|HistorySpecification|Skipping history check during search
19-7-25 22:14:58.4|Debug|MonitoredEpisodeSpecification|No episodes in the release are monitored. Rejecting
19-7-25 22:14:58.4|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] One or more episodes is not monitored
19-7-25 22:14:58.4|Debug|DownloadDecisionMaker|Processing release 'The Flash S05E11 [2019 - WEB-DL - 1080p - Dual] 2019 1080p WEB-DL' from 'amigos'
19-7-25 22:14:58.4|Debug|Parser|Parsing string **'The Flash S05E11 [2019 - WEB-DL - 1080p - Dual] 2019 1080p WEB-DL'**
19-7-25 22:14:58.4|Debug|Parser|Episode Parsed. The Flash - S05E11 
19-7-25 22:14:58.5|Debug|Parser|Language parsed: English

**Comment by garfield69** [comment]
nope, having the quality data there twice should not cause Sonarr to reject it.
![image](https://user-images.githubusercontent.com/6933240/61924192-db53f080-afba-11e9-9acc-c2e71a21fd91.png)
re-examine your selection criteria on sonarr, perhaps there is something there that now may cause it to reject that particular torrent.
