### ISSUE TITLE
[Req] https://feedthe.club/

### ISSUE THREAD

**Issue by Sytanek** [Jackett/Jackett#5733]
Open Signup, according to WorldOfP2P they are moving to this site...
https://feedthe.club/signup/

**Comment by garfield69** [comment]
unfortunately this site is not compatible with the cardigann processor as it generates torrent results dynamically via javascript.
this indexer will need to be written with c#

**Comment by dimqua** [comment]
The link is dead.

**Comment by garfield69** [comment]
closing. Will reopen if anyone discovered if there is a new domain for the site.
