### ISSUE TITLE
tdonline.org issues

### ISSUE THREAD

**Issue by RageInvader** [Jackett/Jackett#574]
Hey, i'm having a lot of issues with jacket trying to access tdonline.org, and i also sometimes get site blocked while trying to access the site from my browser.

Torrent day have added a new url for the uk which is https://torrentday.it
https://tdonline.org/forums.php?t=32275

If you could implement an option in the tracker settings to set a custom url that would also be a great idea.

Thanks

**Comment by kaso17** [comment]
please send a invite to kaso1717 -at- gmail.com so I can fix it.

**Comment by RageInvader** [comment]
Thanks for the very quick update guys, testing looks good. Wondering how long before the Latest release gets updated so I can implement it on my live server? Thanks

**Comment by MrAmos123** [comment]
Sorry to comment on closed issue - tdonline.org is also blocked for me and https://torrentday.it/ works (UK ISP) how do I go about changing the default URL?

Cheers.

**Comment by kaso17** [comment]
@MrAmos123 with the latest version you can change it in the settings
