### ISSUE TITLE
TVChaos UK - Search Working But Dates Causing Issues

### ISSUE THREAD

**Issue by FS0c13ty-Kodi** [Jackett/Jackett#5741]
Hi guys.. wondering if this has been flagged yet, TVChaos is working fine i have it picking up bits and pieces with no dates in the titles on site.

But i run into an issue with anything including a date like this - https://i.imgur.com/SpTTJgL.png

It then bring back zero results for TVC  -  https://i.imgur.com/oE4DmN9.png

Ive spoken to the sonarr guys on discord and they suggested i ask here..

Thank you..

**Comment by garfield69** [comment]
I don't have a TVchaos account so I cant test this for myself.
But I can certainly have a look using you as a proxy if you want.

For this I would need you to do the following:

A. turn off any Sonarr indexers other than TVchaos (to reduce logging) by accessing each Sonarr indexer in the **Settings** page, in the **Indexers** tab, and editing and saving each indexer after turning off the **Enable RSS sync** and the **Enable Search** options.

B. On Sonarr clear the **log files** which you will find in the Sonarr's **System** page, under the **logs** tab, in the **Files** section and clicking the **clear the log files** button.

C. provide the Jackett **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the search for *Nazi Megastructures s04e04 on Sonarr
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

D. provide the Sonarr **log files**.
