### ISSUE TITLE
[myanonamouse] Your man_id did not work: Parse error (Config)

### ISSUE THREAD

**Issue by mattyams** [Jackett/Jackett#5745]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  0.11.534.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------
I know it has to be something simple....and I am sure I am going to slap myself once it's solved.
Log - https://pastebin.com/8VxpGsPw

**Comment by garfield69** [comment]
did you follow the config instructions:
```
Go to your security preferences and create a new session for the IP used by the Jackett server. Then paste the resulting mam_id value into the mam_id field here.
```
?

**Comment by mattyams** [comment]
Yes. It was a lovely string of 292 characters.

**Comment by garfield69** [comment]
then I will pass this one to the other devs, since I don't have an a/c on this site so I can test it for myself.
@kaso17 any ideas?

**Comment by garfield69** [comment]
possibly related #4567

**Comment by 07416** [comment]
I confirm the issue. I've copied the `mam_id` value from `https://www.myanonamouse.net/preferences/index.php?view=security`:

>The value for mam_id for this session is:

...a "code field" follows.

I can provide my MAM account, if required (I don't have invites).

**Comment by coolius** [comment]
Not quite sure what issue other people were having but this is working for me

**Comment by ngosang** [comment]
Is this fixed?

**Comment by coolius** [comment]
I guess you need one of the users who originally experienced the issue to confirm, but I am using this tracker with Jackett successfully.

**Comment by ngosang** [comment]
@hchighfield This issue is old. Please, open a new issue with the information required by the template.
