### ISSUE TITLE
[Req] Support for pt.upxin.net

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5746]
Signup: http://sign.ns.ci/

**Comment by killerqueen619** [comment]
@garfield69 i've already sent the login data  check ur email

**Comment by garfield69** [comment]
try out jackett 0.12.1091

**Comment by bolach** [comment]
Hello
I cant find on current version. Was upxin removed?

**Comment by garfield69** [comment]
@bolach The indexer is called HDU.
If it is not on your Jackett dashboard's active list, then look for it in the add-an-indexer page.
You may need to refill the config for the indexer.

**Comment by bolach** [comment]
@garfield69 , i got it from HDU name
I guess it was my bad. Thank you!

**Comment by ilike2burnthing** [comment]
https://pt.upxin.net/ - The server load is very high at the moment. Retrying, please wait...

**Comment by ilike2burnthing** [comment]
back up
