### ISSUE TITLE
upgrade problem

### ISSUE THREAD

**Issue by gandalf764** [Jackett/Jackett#5750]
gandalf76@vmi71935:/opt/Jackett$ sudo sh ./install_service_systemd.sh
./install_service_systemd.sh: 24: [: root: unexpected operator
./install_service_systemd.sh: 30: ./install_service_systemd.sh: [[: not found
Synchronizing state of jackett.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable jackett
./install_service_systemd.sh: 67: ./install_service_systemd.sh: [[: not found
ERROR: Could not launch service. The installation might have failed.
Please open an issue on https://github.com/Jackett/Jackett/issues and paste following information:
Jackett directory: `/opt/Jackett`
Jackett user: `root`

**Comment by garfield69** [comment]
what were you on before (jackett version, mono if applicable, platform) and what did you upgrade to (the package for AMDx64, ARM32, ARM64, MAcOS, Mono, Windows) ?
