### ISSUE TITLE
404 Errors when downloading through RSS/Torznab

### ISSUE THREAD

**Issue by wogam** [Jackett/Jackett#5752]
-------------------------------
Jackett version: 0.11.538.0
OS: Ubuntu 18.0.4 LTS

Installed with Jackett.Binaries.LinuxAMDx64.tar.gz

I'm receiving 404 errors when downloading through the RSS/Torznab feeds. If I try downloading from the sites themselves or through the Jackett web ui, there are no issues. 

Below is a snippet of the log, the rest of the log was filled with the web page HTML. I've truncated it. The error happens with MAM and GTru.

[log.txt](https://github.com/Jackett/Jackett/files/3440343/log.txt)

**Comment by garfield69** [comment]
Jackett 0.12.1572
