### ISSUE TITLE
[greekteam] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by valantislevas** [Jackett/Jackett#5758]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

Jackett Version 0.11.542.0

for some reason he stopped working..

**Comment by valantislevas** [comment]
```
CardigannIndexer (greekteam): Error while parsing row '
<tr>
	<td align="center" style="padding: 0px" class="row2">
		<a href="browse.php?cat=39">
			<img border="0" src="pic/xvidmov.png" alt="Movies - DVD/BR-rip ">
		</a>
	</td>
	<td class="row2" align="left">
		<a href="details.php?id=140067&amp;hit=1" class="torname" style="vertical-align: bottom;">
			<b>ΕΚΔΙΚΗΤΕΣ: Η ΤΕΛΕΥΤΑΙΑ ΠΡΑΞΗ - Avengers.Endgame.2019.WEB-DL.XviD.AC3-FGT</b>
		</a>
		<hr>
		<img src="pic/checked2.png" width="17" border="0" alt="" title="Ελεγμένο από MenOo : Το torrent είναι OK">
		<hr>***
		<i>
			<font style="size=" 1'="">Ελέγχθηκε από το staff και μπορείτε να το κατεβάσετε</font>
		</i>
		***</td>
	<td class="row1" align="right">
		<b>
			<a href="details.php?id=140067&amp;hit=1&amp;filelist=1">2</a>
		</b>
	</td>
	<td class="row1" align="right">0</td>
	<td class="row1" align="center">
		<nobr>2019-07-29<br>21:12:06</nobr>
	</td>
	<td class="row1" align="center">23<br>hours</td>
	<td class="row1" align="center">2.99<br>GB</td>
	<td class="row1" align="right">
		<b>
			<a href="details.php?id=140067&amp;hit=1&amp;toseeders=1">
				<font color="#000000">46</font>
			</a>
		</b>
	</td>
	<td class="row1" align="right">
		<b>
			<a href="details.php?id=140067&amp;hit=1&amp;todlers=1">1</a>
		</b>
	</td>
	<td class="row1" align="center">
		<a href="userdetails.php?id=211795">
			<b>DjKostasM</b>
		</a>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=td:nth-last-child(5) > nobr, value=<null>: Selector "td:nth-last-child(5) > nobr" didn't match 
<tr>
	<td align="center" style="padding: 0px" class="row2">
		<a href="browse.php?cat=39">
			<img border="0" src="pic/xvidmov.png" alt="Movies - DVD/BR-rip ">
		</a>
	</td>
	<td class="row2" align="left">
		<a href="details.php?id=140067&amp;hit=1" class="torname" style="vertical-align: bottom;">
			<b>ΕΚΔΙΚΗΤΕΣ: Η ΤΕΛΕΥΤΑΙΑ ΠΡΑΞΗ - Avengers.Endgame.2019.WEB-DL.XviD.AC3-FGT</b>
		</a>
		<hr>
		<img src="pic/checked2.png" width="17" border="0" alt="" title="Ελεγμένο από MenOo : Το torrent είναι OK">
		<hr>***
		<i>
			<font style="size=" 1'="">Ελέγχθηκε από το staff και μπορείτε να το κατεβάσετε</font>
		</i>
		***</td>
	<td class="row1" align="right">
		<b>
			<a href="details.php?id=140067&amp;hit=1&amp;filelist=1">2</a>
		</b>
	</td>
	<td class="row1" align="right">0</td>
	<td class="row1" align="center">
		<nobr>2019-07-29<br>21:12:06</nobr>
	</td>
	<td class="row1" align="center">23<br>hours</td>
	<td class="row1" align="center">2.99<br>GB</td>
	<td class="row1" align="right">
		<b>
			<a href="details.php?id=140067&amp;hit=1&amp;toseeders=1">
				<font color="#000000">46</font>
			</a>
		</b>
	</td>
	<td class="row1" align="right">
		<b>
			<a href="details.php?id=140067&amp;hit=1&amp;todlers=1">1</a>
		</b>
	</td>
	<td class="row1" align="center">
		<a href="userdetails.php?id=211795">
			<b>DjKostasM</b>
		</a>
	</td>
</tr>
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1481
```

**Comment by garfield69** [comment]
this is a result of #5748 
looks like some entry lever users do not get the extra column that you see.
We will see if we can accommodate both user classes in the indexer definition.

**Comment by garfield69** [comment]
I've made some changes to the way the selectors are chosen, but since I don't have an account on the site I cannot test for myself (besides which, as an entry level user I could not test the enhanced-user torrent listing).

Try out jackett pre-release 0.11.550
@valantislevas  as an enhanced-user please test that the indexer still works for you and report result.
@BabisK  as an entry-level-user please test that the indexer still works for you and report result.

If there is a failure, please provide an enhanced-log snippet with the html and error . Thanks.

**Comment by valantislevas** [comment]
hello thanks for reply on
Jackett Version 0.11.551.0

seems to be working...

**Comment by BabisK** [comment]
@garfield69 I was on vacation, just had the chance to test it.

It doesn't work for me, the fields are one column off again. Here's the log:

```
System.Exception: Error while parsing field=files, selector=td:nth-child(3), value=None: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1481
08-08 08:14:31 Error CardigannIndexer (greekteam): Error while parsing row '
<tr>
        <td align="center" style="padding: 0px" class="row2">
                <a href="browse.php?cat=10">
                        <img border="0" src="pic/ebook.png" alt="Books/Magazines">
                </a>
        </td>
        <td class="row2" align="left">
                <a href="details.php?id=140211&amp;hit=1" class="torname" style="vertical-align: bottom;">
                        <b>ΜΑΘΕΤΕ ΟΥΚΡΑΝΙΚΑ</b>
                </a>
                <hr>
                <img src="pic/checked2.png" width="17" border="0" alt="" title="Ελεγμένο από Ambassador : Το torrent είναι OK">
                <hr>***
                <i>
                        <font style="size=" 1'="">Ελέγχθηκε από το staff και μπορείτε να το κατεβάσετε</font>
                </i>
                ***</td>
        <td class="row1" align="center">
                <nobr>None</nobr>
        </td>
        <td class="row1" align="right">
                <b>
                        <a href="details.php?id=140211&amp;hit=1&amp;filelist=1">13</a>
                </b>
        </td>
        <td class="row1" align="right">0</td>
        <td class="row1" align="center">
                <nobr>2019-08-07<br>18:36:31</nobr>
        </td>
        <td class="row1" align="center">16<br>hours</td>
        <td class="row1" align="center">606.84<br>MB</td>
        <td class="row1" align="right">
                <span class="green">7</span>
        </td>
        <td class="row1" align="right">1</td>
</tr>':
```

And here's what I see on the browse page:

[Image](https://imgur.com/patvXsh)

**Comment by garfield69** [comment]
Ahh. Tricky. Advanced users get the *uploader's details* column at the end which regular users do not see.
and regular users get a *wait* column after the *title* column that advanced users don't see.
so I cant count from the bottom up for regular users, and I cant count top down for advanced users.
Back to the drawing board....

**Comment by garfield69** [comment]
I can anchor the selector count for the date, size, seeders and leechers off the files column, but this will only work if the files column **always** has the link to the filelist, even when there are *zero* files. 
can someone please check if this is the case?

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.574

**Comment by BabisK** [comment]
@garfield69 I tried the fix and it works for me.

Also, I checked the browse list and it seems that there are no rows with zero files, maybe it's prohibited by the tracker. So the anchor should be safe.

Let's see if this created problems to privileged users.
