### ISSUE TITLE
audiobookbay returned invalid or unrecognized response

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5773]
An error occurred while sending the request.: The server returned an invalid or unrecognized response. (Config)

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by garfield69** [comment]
also specify which jackett version and which platform you are on.
