### ISSUE TITLE
[newpct] Exception (newpct): La matriz no puede ser nula. Nombre del parámetro: bytes

### ISSUE THREAD

**Issue by zatoshi** [Jackett/Jackett#5774]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

I have a problem with the indexer NEWPTC.

Screenshot: 
![image](https://user-images.githubusercontent.com/16266609/62396265-00280500-b573-11e9-925b-7e1ddcaac6a7.png)

Logs:
[log.txt](https://github.com/Jackett/Jackett/files/3462770/log.txt)
[updater.txt](https://github.com/Jackett/Jackett/files/3462771/updater.txt)

any idea about the problem?. Thx.

**Comment by garfield69** [comment]
there is a cloudfare reCaptcha in front of the site which currently breaks Jackett as it does not have a solution to solve.
can only hope that once the AntiDDoS is lifted access can be restored.

**Comment by garfield69** [comment]
also, the site https://descargas2020.org/ultimas-descargas/ and https://pctnew.org/ultimas-descargas/ are returning a blank page, which is the reason for the array cannot be null error
nothing jackett can do about this either.
just have to wait for the site to start working properly.

**Comment by cubiviman** [comment]
Me too, so we have to wait

**Comment by daveraver** [comment]
The sites has both keep blank these pages in order to avoid the use of these read sites tools as jackett and flexget. There is some paralel link to read the site if you want to add them to jackett pm please, thank you...

**Comment by zatoshi** [comment]
I recieve this comment by email thus a notification from here. Where is the message ?
From whom the pm ?


Para: Jackett/Jackett Cc: Tomás; Author 

The sites has both keep blank these pages in order to avoid the use of these read sites tools as jackett and flexget. There is some paralel link to read the site if you want to add them to jackett pm

 please, thank you...

**Comment by ibanana** [comment]
alguna noticia sobre newpct con el enlace paralelo para jackett?

**Comment by garfield69** [comment]
none of the regular c# devs appear to be available.
Volunteer c# devs are welcome to raise a PR to tap into whatever this parallel link provides.

**Comment by zatoshi** [comment]
> none of the regular c# devs appear to be available.
> Volunteer c# devs are welcome to raise a PR to tap into whatever this parallel link provides.

Thanks.

Do you know any paralel link to read those sites?

**Comment by garfield69** [comment]
@zatoshi  wrote:
>Do you know any paralel link to read those sites?

no I do not.
I'm not involved in maintaining the newpct indexer, it is written in C# and I'm not a C# developer.

You asked earlier about the email notification and who sent it...
it was @daveraver who asked to be PM by anyone wanting more info about paralel newpct access.
I'm presuming it involves a json server or some other API service that would allow Jackett to fetch info without having to scrape the html from the web site as it presumably currently does.
That is all I know.

**Comment by snamds** [comment]
@daveraver, can you provide more info about this parallel access? I could take a look into it

**Comment by ibanana** [comment]
@daveraver, can you provide more info about this parallel access? I could take a look into it

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.592, which includes a possible work around for this issue coded by @javierjp93

**Comment by ibanana** [comment]
@garfield69 As I get this version I am not very set.  Thank you
