### ISSUE TITLE
Immediate terminate in Win10

### ISSUE THREAD

**Issue by santakrooz** [Jackett/Jackett#578]
Hi, have been running jackett for over a year without trouble, until recently upgraded to Win10 and latest ver of Jackett- the tray icon comes up until cursor over it then disappears. Service is "stopped". Any suggestions appreciated. thx

**Comment by JigSawFr** [comment]
We need some logs for debugging purposes :)

**Comment by heelergjammer** [comment]
same issue here. where can i find the logs you need?

**Comment by santakrooz** [comment]
I got it working as a tray app (not service). I had to clean all traces of
previous (older) jackett installation, install clean - and run tray app as
Admistrator. It's working like that. I'll try to run as service to get it
to fail and capture log. Where are the logs stored?

**Comment by heelergjammer** [comment]
i did a complete new installation of my Win10 Machine... after this, I can use Jackett, also as a service. For me it's fixed.

**Comment by mrchadcooper** [comment]
I am still getting this problem even on the newest release. What info do you need to help track down the issue please ELIA5 when saying how to get it.

**Comment by finagle69** [comment]
My Jackett last worked on 10-27, fails now after it updated to v0.7.471 per log.  I've attached the updater.txt and log.txt from mine.  

Bonus points for figuring out why BHD fails (in log as well).  I've got Jackett also running on a Ubuntu server and BHD works correctly through that, so it's apparently Windows (10) related.

[updater.txt](https://github.com/Jackett/Jackett/files/561128/updater.txt)
[log.txt](https://github.com/Jackett/Jackett/files/561132/log.txt)

**Comment by mrchadcooper** [comment]
Any update on this? Jackett not working is killing me

**Comment by santakrooz** [comment]
It fails for me on windows 10 unless I run trayapp manually "as
administrator"

**Comment by kaso17** [comment]
@finagle69 Please create the directory C:\ProgramData\Jackett\Definitions manually.
The BHD issue is resolved in the latest release.

@santakrooz @mrchadcooper Please look for log*.txt and updater.txt files in your jacket directory (usually C:\ProgramData\Jackett) and let us know the content.

**Comment by mrchadcooper** [comment]
[updater.txt](https://github.com/Jackett/Jackett/files/568818/updater.txt)
[log.txt](https://github.com/Jackett/Jackett/files/568819/log.txt)
Here you go

**Comment by kaso17** [comment]
The `Jackett.Services.ServiceConfigService.RemoveService() in C:\projects\jackett\src\Jackett\Services\ServiceConfigService.cs:line 122` exception's are not serious, they occurred if you try to uninstall the service if it's already uninstalled.

It seems like it get's stuck during startup. I'll try to add a little more debugging information to see what's going on in a future release.

One more thing you could try:
Try changing the account which is running the service to administrator.
Please also confirm that the directory " C:\ProgramData\Jackett\Definitions" exists and everything is working fine if you start Jackett via the tray/console exe files.

**Comment by mrchadcooper** [comment]
I tried what you suggested and get the same result. The directory exists and the same thing happens if i start from those files. This is driving me nuts! Thank you for your continued help

**Comment by finagle69** [comment]
@kaso17 Thank you. Manually creating the directory fixed it right up.  And BHD now functions correctly.

**Comment by kaso17** [comment]
@mrchadcooper then please start JacketConsole.exe with the -t option to get additional debug output and post it here.

**Comment by mrchadcooper** [comment]
@kaso17 actually the latest update fixed my issue. Thanks for all the help! All i had to do was reinstall over the older version

**Comment by kaso17** [comment]
then check the log, you might have a broken indexer config file
