### ISSUE TITLE
[yggtorrent] Login failed: No form found on http://www.yggtorrent.ch/ using form selector 

### ISSUE THREAD

**Issue by bxlouis** [Jackett/Jackett#5795]
I know this issue was already reported - and closed - but I read all previous tickets, tried every solution and I am still facing this issue.
My account is correct, I have no ratio issue. 
I am able to log into my account using my browser and download content.
I am using the correct credentials.
I tried modifying the Site Link URL.

Whatever I do, I keep getting this error and cannot use YGGtorrent as a tracker with Jackett anymore. Everything used to work well.

Please find attached the log.txt file. 

Jackett version: 0.11.559.0 (Docker - Synology)

[log.txt](https://github.com/Jackett/Jackett/files/3468694/log.txt)

**Comment by garfield69** [comment]
it appears that you have set your sitelink to www2. which is incorrect.
use your jackett dashboard and edit the yggtorrent config.
USe the copy and paste to set the *Site Link* to `https://www.yggtorrent.ch/` and the *search and download url* to `www2.yggtorrent.ch` and click OKAY.
if you get an error click CLOSE, edit the config and repeat. it should save the second time.

**Comment by garfield69** [comment]
In the unlikely event you still cannot get the jackett dashboard editor to work, the final option is to:
1. use the trashbin icon the detete the active indexer. 
2. then shut down the jackett service or app.
3. navigate to the jackett indexer folder `~/.config/Jackett/Indexers` and delete the yggtorrent.json and yggtorrent.json.bak files.
4. start up jackett and add the yggtorrent afresh.

The config should be pre-loaded with the correct parms to you should be good to go.

**Comment by bxlouis** [comment]
Thanks @garfield69! 
Your solutions worked!
