### ISSUE TITLE
[asiancinema] Request to jackett server failed windows 10

### ISSUE THREAD

**Issue by killerqueen619** [Jackett/Jackett#5797]
while i try to add tracker asiancinema
always showing error
like this https://i.imgur.com/IqXGYmP.png

i am using
win 10 pro.

before its was normal.
after update error.
i try uininstall and install
still same just asiancinema tracker

**Comment by garfield69** [comment]
asiancinema have enabled a cloudflare DDoS protection and jackett is not able to currently solve it.
part of the #4982 family of impacted indexers.

nothing to do with the update just unlucky timing.

when 4982 ever gets solved access will be restored. 
in the mean time you will just have to use your browser and access the site directly.

**Comment by killerqueen619** [comment]
> asiancinema have enabled a cloudflare DDoS protection and jackett is not able to currently solve it.
> part of the #4982 family of impacted indexers.
> 
> nothing to do with the update just unlucky timing.
> 
> when 4982 ever gets solved access will be restored.
> in the mean time you will just have to use your browser and access the site directly.

its already fixed .
i can add the asiancinema now
