### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Could not load file or assembly 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=******'. The module was expected to contain an assembly manifest.

### ISSUE THREAD

**Issue by Iclario** [Jackett/Jackett#5798]
Jackett version : 0.11.566.0

The indexer stopped working yesterday for no reason. The site is still working and I have no trouble logging in.

**Comment by garfield69** [comment]
sounds like you have run afoul of the updater issue #5208
your best bet is to download and install the latest package from https://github.com/Jackett/Jackett/releases

if the updated continues to be a problem then enabling the disable-auto-update option from your jackett dashboard would be a way to prevent further issues until it is resolved.
don't forget to click on the apply-server-settings button to save your settings.

**Comment by Iclario** [comment]
Thanks a lot, that solved it. (I've redownloaded the package)
