### ISSUE TITLE
Change torrentshack to use SSL

### ISSUE THREAD

**Issue by RedshiftZA** [Jackett/Jackett#58]
I'm not quite sure if this is an issue or just not a feature/supported but, for instance, TorrentShack has an SSL tracker but using Jackett & Sonarr it only pulls standard torrents.

Is there a way if any to change this behavior?

**Comment by WhatFox** [comment]
I don't have access to that tracker, is it just a case of getting the link from a different button on the same page?

**Comment by RedshiftZA** [comment]
Hi WhatFox,

Yeah its is just a separate button on the page

**Comment by WhatFox** [comment]
I don't think we have access to the tracker since we have switched owners for the project, do you have an invite or can you send me the html for the torrent list page?  my name at gmx dot com.
