### ISSUE TITLE
unable to add torrentday - Exception in GetConfigForm

### ISSUE THREAD

**Issue by maZuFC** [Jackett/Jackett#580]
hi 

i am unable to add torrentday to jackett, when i click on TD from the indexers it doesnt even pop up with any options.

i get the following error 

Exception in GetConfigForm
Rejected a request to TorrentDay which is unconfigured.

i suspect this is caused by tdonline.org being blocked.

is there a way to edit the url for torrentday?
where is this information stored? is there a config file or xml file i can edit?

i am using Jackett Version 0.7.425.0

cheers!

**Comment by kaso17** [comment]
duplicate of #574

**Comment by RageInvader** [comment]
When do you think we can expect the next release version?

**Comment by kaso17** [comment]
Try one of the latest draft releases
