### ISSUE TITLE
[REQ] acgsou

### ISSUE THREAD

**Issue by IDarkBoss** [Jackett/Jackett#5803]
http://www.acgsou.com/

**Comment by garfield69** [comment]
unfortunately this site uses javascript to populate the Seeders, Leechers and Completed columns on the results page.
but the rest (date, name, magnet, etc) are available in the html.

do you want me to continue with the cardigann indexer (and do without the S L C), or would you rather wait for a c# dev to code the indexer so that the S L C are presented?

**Comment by 472714747** [comment]
to be honest, C# is definitely better.(if you have time)

but i am still grateful for the cardigann version^_^

**Comment by garfield69** [comment]
I am not a c# developer so I can only provide you with the cardigann indexer which you can try out with Jackett pre-release 0.11.573

I've flagged this request with the *need c#* tag, and remind the volunteer that codes the c# indexer to also remember to remove the cardigann version of the indexer when implementing the c# version.

**Comment by ngosang** [comment]
Already implemented

**Comment by garfield69** [comment]
@ngosang  are you closing this because of the yaml indexer?
this ticket was to convert it to c# so that the seeders leechers and grabs could be fetched, as they are generated by JS and cardigann cannot present them.

**Comment by ngosang** [comment]
Sorry, the title was misleading.
Anyway that indexer is making 1 request for each torrent only to get the seeds/leechs. I think this shouldn't be implemented in C# to avoid DDoS the site. What do you think?

**Comment by garfield69** [comment]
not sure I understand.
the current yaml acgsou indexer has seeders and leechers hard coded to one.
on the website it displays in the results up to date seeders and leechers and grabs by invoking some JS.
what am I missing?

**Comment by ngosang** [comment]
If you press F12 in your browser, go to Network tab and press F5 you will see your browser makes 1 request to get the HTML and then it makes a lot of requests to get the seeds/peers (1 for each torrent in the list). This could be implemented in C# but I think it's a bad idea to make so many requests to get that information.

**Comment by garfield69** [comment]
Agreed.

**Comment by garfield69** [comment]
https://www.36dm.com/ and https://www.36dm.club/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
Both back up

**Comment by garfield69** [comment]
https://www.36dm.com/ returns ERR_EMPTY_RESPONSE
https://www.36dm.club/ returns Error 503. The service is unavailable.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.36dm.club/ and https://www.36dm.com/ return DNS_PROBE_FINISHED_NXDOMAIN (domain not found)

**Comment by ilike2burnthing** [comment]
In case it doesn't come back online, there is https://www.36dm.org/, which looks to be a completely unrelated site, but is also a Chinese public tracker for anime.

**Comment by garfield69** [comment]
v0.21.473
