### ISSUE TITLE
Jackett unable to start service after stopping service

### ISSUE THREAD

**Issue by MaurizioRicci** [Jackett/Jackett#5804]
I'm reporting a situation in where Jackett service can't be started. I tried launching Jackett  tray as admin and clicking 'start background service' but the service is still stopped. I also tried from Windows services to locate the service anche manually start it but Win says that the service started and then stopped (maybe crashed?). 

Tried to reinstall Jacket and everything worked as expcted, then i stopped the service (from jackett tray) and tried to restart the service with no luck.

I also tried rebooting but nothing changed. I am using Jackett Version 0.11.566.0

**Comment by garfield69** [comment]
access your windows Event Viewer, and look up the System windows log and see if you can find the event that reports the starting/failure of the Jackett service. 
there may be an explanation for why the service will not start.

**Comment by MaurizioRicci** [comment]
@garfield69 i done it and i found this:

_(unable to launch service)_ Impossibile avviare il servizio. System.ComponentModel.Win32Exception (0x80004005): Impossibile trovare il file specificato _(unable to locate desired file)_
   in System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   in System.Diagnostics.Process.Start()
   in System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   in Jackett.Service.Service.StartConsoleApplication() in C:\projects\jackett\src\Jackett.Service\Service.cs:riga 67  _(row 67)_
   in Jackett.Service.Service.OnStart(String[] args) in C:\projects\jackett\src\Jackett.Service\Service.cs:riga 42  _(row 42)_
   in System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)

Some terms are in italian so i traslated to english and reported in parenthesis in italic font

**Comment by garfield69** [comment]
ok. so check the service properties for jackett again, and note in the General section the Path To Executable. It should be `C:\ProgramData\Jackett\JackettService.exe`

then open explorer and check that the JackettService.exe is in the ProgramData\Jackett folder.
I'm guessing it is no longer there.

My guess is that your Anti-Malware tool is silently moving the exe to its VirusChest folder or even deleting it.
Check your anti-malware app logs for such activity and if necessary add an exception rule.
Then restore the JAckettService.exe if it is in the VirusChest or Install the Jackett package again, and  you should be good to go.

**Comment by MaurizioRicci** [comment]
@garfield69 Thank you, finally i found the truth. The JackettService.exe was still there, is JackettConsole.exe the one which got marked as virus from the antivirus. Now i've restored the files and everything works.

**Comment by garfield69** [comment]
if you want an independent crosscheck that the program is safe (and that your anti-malware is generating a false positive), then load the exe to https://www.virustotal.com/gui/home/upload and have the site check it for you.
better safe then sorry.
