### ISSUE TITLE
[gimmepeers] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by jamesb2147** [Jackett/Jackett#5808]
Running on the LinuxAMDx64 build.
Jackett version is 0.11.566.0 (the latest tagged release).

Logs ahoy! (Copied from the web interface as the server-side logs were more difficult to read. Let me know if server log format is preferred, as I have already saved off the logs for easy access.)

LMK if an invite is required.
-------------------------------

When | Level | Message
-- | -- | --
Aug 08, 2019 11:08:25 AM | Info | Executing action method Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett) - Validation state: Valid
Aug 08, 2019 11:08:25 AM | Info | Authorization was successful.
Aug 08, 2019 11:08:25 AM | Debug | Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Aug 08, 2019 11:08:25 AM | Debug | Execution plan of exception filters (in the following order): None
Aug 08, 2019 11:08:25 AM | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter
Aug 08, 2019 11:08:25 AM | Debug | Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Aug 08, 2019 11:08:25 AM | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Aug 08, 2019 11:08:25 AM | Info | Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing action Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)
Aug 08, 2019 11:08:25 AM | Debug | Request successfully matched the route with name '(null)' and template 'api/v2.0/server/Logs'
Aug 08, 2019 11:08:25 AM | Debug | AuthenticationScheme: Cookies was successfully authenticated.
Aug 08, 2019 11:08:25 AM | Debug | The request path /api/v2.0/server/logs does not match a supported file type
Aug 08, 2019 11:08:25 AM | Debug | Request is continuing in applying rules. Current url is http://streamer.embaucha.com:9117/api/v2.0/server/logs?_=1565280486982
Aug 08, 2019 11:08:25 AM | Debug | Request is continuing in applying rules. Current url is http://streamer.embaucha.com:9117/api/v2.0/server/logs?_=1565280486982
Aug 08, 2019 11:08:25 AM | Debug | Request is continuing in applying rules. Current url is http://streamer.embaucha.com:9117/api/v2.0/server/logs?_=1565280486982
Aug 08, 2019 11:08:25 AM | Info | Request starting HTTP/1.1 GET http://streamer.embaucha.com:9117/api/v2.0/server/logs?_=1565280486982
Aug 08, 2019 11:08:23 AM | Info | Request finished in 2815.7983ms 500 application/json
Aug 08, 2019 11:08:23 AM | Debug | Connection id "0HLOPF8KGN4B7" completed keep alive response.
Aug 08, 2019 11:08:23 AM | Debug | The response will be compressed with 'gzip'.
Aug 08, 2019 11:08:23 AM | Error | System.Exception: Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
Aug 08, 2019 11:08:23 AM | Info | Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 2793.8621ms
Aug 08, 2019 11:08:23 AM | Info | Found 0 releases from GimmePeers
Aug 08, 2019 11:08:23 AM | Debug | WebClient(HttpWebClient2NetCore): Returning Redirect => https://www.gimmepeers.com/verifyemail.php  <script type="text/javascript"> var hoveredElement=null;  function tick(){     $('.ticker').filter(function(item){                    return !$(this).is(hoveredElement)             }).each(function(){         $(this).find('li:first').slideUp(function () {                                    $ticker = $(this).closest('.ticker');                          $(this).appendTo($ticker).slideDown();         });     }); } setInterval(tick, 6500);   $(function(){     $('.ticker').hover(function(){ hoveredElement=$(this);             },function(){         hoveredElement=null;     }); }); </script>
Aug 08, 2019 11:08:23 AM | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://www.gimmepeers.com/browse.php?incldead=0)
Aug 08, 2019 11:08:23 AM | Debug | Saving new config file: /home/jamesb2147/.config/Jackett/Indexers/gimmepeers.json.d3a632c3269442238768f484b3b2f421.tmp
Aug 08, 2019 11:08:23 AM | Debug | WebClient(HttpWebClient2NetCore): Returning OK => 10470 bytes
Aug 08, 2019 11:08:23 AM | Debug | __cfduid=d5577f55d84796cb14f80ce3804ac4d4c1565280501
Aug 08, 2019 11:08:23 AM | Debug | __cfduid=d5577f55d84796cb14f80ce3804ac4d4c1565280501; expires=Fri, 07-Aug-20 16:08:21 GMT; path=/; domain=.gimmepeers.com; HttpOnly
Aug 08, 2019 11:08:21 AM | Debug | WebClient(HttpWebClient2NetCore).GetBytes(Url:https://www.gimmepeers.com/)
Aug 08, 2019 11:08:21 AM | Debug | WebClient(HttpWebClient2NetCore): Returning Redirect => https://www.gimmepeers.com/
Aug 08, 2019 11:08:21 AM | Debug | pass=8620a4e6d7618fb72fbd8b2ae3566069; expires=Tue, 19-Jan-2038 03:14:07 GMT; Max-Age=582203146; path=/
Aug 08, 2019 11:08:21 AM | Debug | uid=13366; expires=Tue, 19-Jan-2038 03:14:07 GMT; Max-Age=582203146; path=/
Aug 08, 2019 11:08:21 AM | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://www.gimmepeers.com/takelogin.php)
Aug 08, 2019 11:08:21 AM | Debug | Saving new config file: /home/jamesb2147/.config/Jackett/Indexers/gimmepeers.json.2933c05e1af24162ad0f2be9770bb6e2.tmp
Aug 08, 2019 11:08:21 AM | Debug | updating Cookies __cfduid=d03bf40d07a281d0581c2cf182536b6701565280392; uid=13366; pass=8620a4e6d7618fb72fbd8b2ae3566069 => __cfduid=d470ae0dae0b925b96dca298c7a24451c1565280501; uid=13366; pass=8620a4e6d7618fb72fbd8b2ae3566069
Aug 08, 2019 11:08:21 AM | Debug | WebClient(HttpWebClient2NetCore): Returning Redirect => https://www.gimmepeers.com/login.php <html><head> <title>GP</title> <META name="description" content="GimmePeers.com the greatest blackhole!">   <link rel="alternate" type="application/rss+xml" title="Latest Torrents" href="/rss.php?passkey="> <link rel="stylesheet" type="text/css" href="/default.css" /> <style> .highlighttext{ background-color:yellow; font-weight:bold; } a.noTab { /* visibility: hidden; display: none; */ } </style> </head> <BODY leftMargin=8 rightMargin=8 topmargin=8> <table width=985 class="gp_sub_nav1" align="center" height="30" cellpadding="4" cellspacing="0" border="0"> <tr><td align=center class=main style="padding-top: 20px; padding-bottom: 20px"> <br><br> </td></tr></table><br> <table class=gp_sub_nav align=center width=80% border=0 cellspacing=0 cellpadding=0><tr valign=top> <td align=center><b>© GimmePeers.com - 2018 - Welcome to the Dark Side</b></td> </tr></table><br> </body></html>
Aug 08, 2019 11:08:21 AM | Debug | __cfduid=d470ae0dae0b925b96dca298c7a24451c1565280501
Aug 08, 2019 11:08:21 AM | Debug | __cfduid=d470ae0dae0b925b96dca298c7a24451c1565280501; expires=Fri, 07-Aug-20 16:08:21 GMT; path=/; domain=.gimmepeers.com; HttpOnly
Aug 08, 2019 11:08:21 AM | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://www.gimmepeers.com/)
Aug 08, 2019 11:08:21 AM | Debug | WebClient(HttpWebClient2NetCore): Returning Redirect => https://www.gimmepeers.com/verifyemail.php  <script type="text/javascript"> var hoveredElement=null;  function tick(){     $('.ticker').filter(function(item){                    return !$(this).is(hoveredElement)             }).each(function(){         $(this).find('li:first').slideUp(function () {                                    $ticker = $(this).closest('.ticker');                          $(this).appendTo($ticker).slideDown();         });     }); } setInterval(tick, 6500);   $(function(){     $('.ticker').hover(function(){ hoveredElement=$(this);             },function(){         hoveredElement=null;     }); }); </script>
Aug 08, 2019 11:08:20 AM | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://www.gimmepeers.com/browse.php?incldead=0)
Aug 08, 2019 11:08:20 AM | Info | Executing action method Jackett.Server.Controllers.IndexerApiController.Test (jackett) - Validation state: Valid
Aug 08, 2019 11:08:20 AM | Info | Authorization was successful.
Aug 08, 2019 11:08:20 AM | Debug | Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Aug 08, 2019 11:08:20 AM | Debug | Execution plan of exception filters (in the following order): None
Aug 08, 2019 11:08:20 AM | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
Aug 08, 2019 11:08:20 AM | Debug | Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Aug 08, 2019 11:08:20 AM | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Aug 08, 2019 11:08:20 AM | Info | Route matched with {action = "Test", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Test (jackett)
Aug 08, 2019 11:08:20 AM | Debug | Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers/{indexerid}/Test'
Aug 08, 2019 11:08:20 AM | Debug | AuthenticationScheme: Cookies was successfully authenticated.
Aug 08, 2019 11:08:20 AM | Debug | POST requests are not supported
Aug 08, 2019 11:08:20 AM | Debug | Request is continuing in applying rules. Current url is http://streamer.embaucha.com:9117/api/v2.0/indexers/gimmepeers/test
Aug 08, 2019 11:08:20 AM | Debug | Request is continuing in applying rules. Current url is http://streamer.embaucha.com:9117/api/v2.0/indexers/gimmepeers/test
Aug 08, 2019 11:08:20 AM | Debug | Request is continuing in applying rules. Current url is http://streamer.embaucha.com:9117/api/v2.0/indexers/gimmepeers/test
Aug 08, 2019 11:08:20 AM | Info | Request starting HTTP/1.1 POST http://streamer.embaucha.com:9117/api/v2.0/indexers/gimmepeers/test  0

**Comment by garfield69** [comment]
the log shows that your attempt to login to gimmepeers is being redirected to https://www.gimmepeers.com/verifyemail.php

this suggests that your either 
a) your registration is not complete, or 
b)  that you changed your email address in your account and need to verify it before being able to complete the login process.

access the site directly with your browser and resolve any account issues.
after which you should be able to use jackett to login and search.

**Comment by jamesb2147** [comment]
I did that prior to opening the bug report. I believe there is something else going on here as there is no redirect in my browser session. Perhaps the page formatting changed at GP?

**Comment by jamesb2147** [comment]
Fascinatingly, I checked now and as soon as I hit the "forums" it prompted for email verification. I was able to browse torrents, but whatever. I'll check it out when I get back to a location where I have access to my Jackett install and report back.

**Comment by jamesb2147** [comment]
Confirmed that it's working now. Thanks for the help!
