### ISSUE TITLE
[mvgroupforum] Login failed: No form found on http://forums.mvgroup.org/index.php?act=Login

### ISSUE THREAD

**Issue by stringer44** [Jackett/Jackett#5813]
tried to login... and got that error
Login failed: No form found on https://forums.mvgroup.org/index.php?act=Login&CODE=00 using form selector form[action^="?act=Login"]

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.575

**Comment by stringer44** [comment]
solved, thanks
