### ISSUE TITLE
[Tracker] Beyond-HD Error Grabbing

### ISSUE THREAD

**Issue by seed1234** [Jackett/Jackett#5814]
[log.txt](https://github.com/Jackett/Jackett/files/3484893/log.txt)

Jackett Cannot Grab any torrent from Beyond-HD

**Comment by garfield69** [comment]
works for me.

the log shows that you are being requested to login prior to downloading, with the following alert
```
                       Important Notice: BHD has migrated to a new platform.
                        If you have logged in after May 9, 2019, log in above.
                        - OR -
                        Click here to transfer your U-232 password.
```

I suggest you use your browser to access the beyond-hd web site directly and confirm that your account is valid and has no outstanding alerts that may prevent downloads.

**Comment by garfield69** [comment]
and my second suggestion is that after confirming your account is good, re-enter you username and password in the Jackett beyond-hd inderxer's config (using your jackett dashboard wrench icon) just to ensure it had valid credentials.

**Comment by seed1234** [comment]
I have issues with the tracker thanks for the help
