### ISSUE TITLE
[REQ] add please Marine Tracker

### ISSUE THREAD

**Issue by ghost** [Jackett/Jackett#5817]
https://seatracker.ru/
Russian Semi-Private tracker

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.581

**Comment by ilike2burnthing** [comment]
https://seatracker.ru/ - 500 Internal Server Error

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://seatracker.ru/ - 500 Internal Server Error

**Comment by ilike2burnthing** [comment]
https://seatracker.ru/ - working
https://seatracker.ru/tracker.php (after logging in) - 500 Internal Server Error

Note to self: use VPN

**Comment by garfield69** [comment]
fully functional again.

**Comment by garfield69** [comment]
https://seatracker.ru/ > Website is temporarily offline due to maintenance. Completion date: 12/10/2023

**Comment by ilike2burnthing** [comment]
Is https://seatracker.org/tracker.php working for you? I just keep getting `Internal Server Error`.

**Comment by garfield69** [comment]
working for me
