### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Connection refused: Connection refused (Test)

### ISSUE THREAD

**Issue by groenator** [Jackett/Jackett#5821]
Hi, 

Piratebay is not working for a while. Testing doesn't do anything. 

I can provide logs, just let me know what info you need.

Regards,

**Comment by garfield69** [comment]
works for me.
most likely your ISP is blocking TPB in your region
try out the proxies at https://proxybay.app/ and see if any one of those works for you.

**Comment by groenator** [comment]
I am using it behind a VPN. I'll check it out.

**Comment by groenator** [comment]
I changed the url and now it works. You can close this issue.

Thanks!
