### ISSUE TITLE
QxR Gone

### ISSUE THREAD

**Issue by majorsl** [Jackett/Jackett#5828]
Just an FYI - looks like QxR is gone:

https://qxr.pw/

Might want to remove it if so.

**Comment by tkdrob** [comment]
Looks like only the forum site is shutting down: https://www.reddit.com/r/Piracy/comments/cn0yc1/end_of_qxr_forums/

Not sure about the new url though

**Comment by garfield69** [comment]
90f3f46b54292dcb3503dfa179229e7790a1d656
