### ISSUE TITLE
[Marine Tracker] Don't work rss

### ISSUE THREAD

**Issue by Deputant** [Jackett/Jackett#5829]
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error code="900" description="System.ArgumentNullException: Значение не может быть неопределенным.
 Имя параметра: value
 в System.Xml.Linq.XAttribute..ctor(XName name, Object value)
 в Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r)
 в System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
 в System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
 в System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
 в Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom)
 в Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext()"/>`

**Comment by garfield69** [comment]
marine tracker displays some torrents without a download link, (because they have been subjected to DMCA) but this trips the RSS processor.
So I've dropped them from the results.
try out jackett pre-release 0.11.588
