### ISSUE TITLE
[torrentleech] Exception (torrentleech): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Parse error (Test)

### ISSUE THREAD

**Issue by JackFrost666** [Jackett/Jackett#5837]
Latest version, Torrentleech doesnt seem to work.
[error.txt](https://github.com/Jackett/Jackett/files/3493953/error.txt)

**Comment by garfield69** [comment]
works for me.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by garfield69** [comment]
this looks similar to #5565, and torrentleech is working for me at the time I posted this comment.

**Comment by garfield69** [comment]
Sorry, you don't need to return the full logs, I was not paying attention, the error.txt has all the data I need.
torrentleech returned http error 1004  Internal Server Error :
```
        <h1>An error occurred</h1> 
        <h2>Application error. Please report to staff.<br/>(Error Code: 1004)</h2> 
```
it is definitely an internal issue with torrentleech and nothing that jackett can do about this.
