### ISSUE TITLE
gktorrent - Error downloading 

### ISSUE THREAD

**Issue by MrLuje** [Jackett/Jackett#5838]
Downloading a file from gktorrent after a successful search results on the following logs :

08-12 22:25:06 Error Error downloading gktorrent https://www.gktorrent.biz/torrent/8694/us-french-bluray-1080p-2019 System.Exception: Download selector a[href*="/get_torrent/"] didn't match    at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1674    at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/DownloadController.cs:line 53
-- | --

Jackett Version 0.11.566.0

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.593

**Comment by MrLuje** [comment]
Perfect, thanks 👍
