### ISSUE TITLE
[fuzer] - Please add a new category for 4K

### ISSUE THREAD

**Issue by BuSHari** [Jackett/Jackett#5839]
Hello,

Can you please add the new category **4K** that the tracker Fuzer added?
Category id: 97

Thank you,
Idan

**Comment by garfield69** [comment]
i take it this is a movie UHD category?
is there one for TV ?

**Comment by BuSHari** [comment]
yes this is UHD category, and they dont have for TV yet.
Thanks...

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.595

**Comment by BuSHari** [comment]
Yes, its working thank you!
