### ISSUE TITLE
[rarbg] Unexpected character encountered while parsing value: <. Path '', line 0, position 0. (Config)

### ISSUE THREAD

**Issue by msalem23** [Jackett/Jackett#5846]
When I try to add the RARBG indexer, I get: "An error occured while configuring this indexer
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
Click here to open an issue on GitHub for this indexer."

Running the latest stable release of Jackett on Windows 10. Enhanced logs attached.

[log.txt](https://github.com/Jackett/Jackett/files/3498068/log.txt)
[updater.txt](https://github.com/Jackett/Jackett/files/3498069/updater.txt)

(At the bottom of your Jackett Dashboard page) **Jackett version**:  0.11.589.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by garfield69** [comment]
you have changed the URL for the RarBG API to `https://rarbg.to/`
this is wrong. the above is the **Site Link**.
the API URL is `https://torrentapi.org/`

so using your jackett dashboard, add RarBG and make sure the config looks like this:
![image](https://user-images.githubusercontent.com/6933240/62971691-8511f900-be66-11e9-8834-252294de5725.png)
