### ISSUE TITLE
[themoviecave] certificate validation failed

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5848]
Exception (themoviecave): certificate validation failed: [Subject]  CN=the-movie-cave.eu[Issuer]  CN=Let's Encrypt Authority X3, O=Let's Encrypt, C=US[Serial Number]  036D642833CA15E657DC7324B5DDA4610A11[Not Before]  5/15/19 2:57:37 PM[Not After]  8/13/19 2:57:37 PM[Thumbprint]  4E4271DA3C65582C37FA3B13C12645F1803A2E8F: The SSL connection could not be established, see inner exception. (Test)

Jackett Version 0.11.593.0

**Comment by garfield69** [comment]
refresh your certificates repo.
themoviecave is now using a new cert issued 8/14/19 thumbrint f2a728658d7a4bc01fce614964d79f0e1b77e6f5 which is valid.
