### ISSUE TITLE
[speedcd] A task was canceled. (Config)

### ISSUE THREAD

**Issue by finchy70** [Jackett/Jackett#5849]
[log.txt](https://github.com/Jackett/Jackett/files/3500342/log.txt)

Jackett Version 0.11.589.0

Can't add Speed.cd or IPTorrents.  I can log into both sites.  I have Geo Locking disabled in speed.cd .  I am using a socks5 proxy.

**Comment by garfield69** [comment]
it is very likely that Jackett got hung up on the cloudflare DDoS protection challenge that speedcd have currently in place. 
Unfortunately the new check breaks Jackett (one of the symptoms is a timeout/cancel) 
a possible solve is pending c# devs becoming available to include a 3rd party library fix.
see #4982

**Comment by garfield69** [comment]
cloudflare solved with Jackett 0.11.635
this should at least let you access speedcd with jackett.
