### ISSUE TITLE
(MkvCage)  An error occured while testing this indexer

### ISSUE THREAD

**Issue by newgithubuser2019** [Jackett/Jackett#5865]
Exception (mkvcage): Specified argument was out of the range of valid values. Parameter name: Unknown operator: : Specified argument was out of the range of valid values. Parameter name: Unknown operator: 
____________________________________________________________________________________________________
 Jackett Version 0.11.608.0 
[log.txt](https://github.com/Jackett/Jackett/files/3511704/log.txt)

**Comment by garfield69** [comment]
this is a duplicate of #4982. that ticket explains the issue for which there is no current fix for jackett.
