### ISSUE TITLE
[torrentdownloads] Exception (torrentdownloads): certificate validation failed: [Subject]  O=Internet Widgits Pty Ltd, S=Some-State, C=AU[Issuer]  O=Internet Widgits Pty Ltd, S=Some-State, C=AU[Serial Number]  00F5BA2E609C91DBB4[Not Before]  10/13/2014 4:46:03 PM[Not After]  11/12/2014 3:46:03 PM[Thumbprint]  5D8A25EB8B9C46981F007D105007113B97CA9BE6: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by newgithubuser2019** [Jackett/Jackett#5868]
Normally i can't access https://www.torrentdownloads.me/. However now i can after configuring dns over https in firefox. Are there any settings in jacket i can change to make it pass the test?
________________________________________________________________________________________________
 Jackett Version 0.11.608.0 
[log.txt](https://github.com/Jackett/Jackett/files/3511824/log.txt)

**Comment by ngosang** [comment]
It's working for me. This exception is related to bad network configuration: proxy, vpn or isp block.
