### ISSUE TITLE
[Req] add please AlexFilm Russian semi-private tracker

### ISSUE THREAD

**Issue by ghost** [Jackett/Jackett#5871]
https://alexfilm.cc/

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.615
note: the search engine on this site does not appear to honour the all-words flag.
if you know of the correct syntax to search and get just `strange angel s01e01` without having the site return the other seasons or other titles with partial matches then please let me know.

**Comment by garfield69** [comment]
https://alexfilm.org/ returning HTTP ERROR 500

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
I'm still seeing HTTP ERROR 500. Just me?

**Comment by ilike2burnthing** [comment]
Working ok here. I'll test over the next while to see if it's an intermittent issue.

**Comment by ilike2burnthing** [comment]
Refreshed periodically over the last hour, navigated the site, all seems to be fine on my end. You still getting an issue?

**Comment by garfield69** [comment]
yes. even with a VPN. %-/
