### ISSUE TITLE
[Req] add BookTracker Russian semi-private tracker

### ISSUE THREAD

**Issue by ghost** [Jackett/Jackett#5872]
https://booktracker.org/

**Comment by garfield69** [comment]
BookTracker
https://booktracker.org/
Russian 
semi-private
try out jackett pre-release 0.11.616

**Comment by garfield69** [comment]
https://booktracker.org/ returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online.

**Comment by garfield69** [comment]
https://booktracker.org/ > Tracker internal error. Sorry.

**Comment by garfield69** [comment]
online
