### ISSUE TITLE
[Req] add please Underverse Russian semi-private tracker

### ISSUE THREAD

**Issue by ghost** [Jackett/Jackett#5873]
https://underverse.su/

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.626

**Comment by garfield69** [comment]
https://underver.se/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
Error 521 - Web server is down

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
The public underverse indexer does not currently work as the site has dropped magnets and .torrents only work for registered users.
The user agreement page states that magnets should be available if users agree  to the agreement, but only a close button is currently showing. 
So for now only the underverseL indexer is working.

**Comment by garfield69** [comment]
v0.20.1196
