### ISSUE TITLE
[Req] add please NetLab Russian private tracker

### ISSUE THREAD

**Issue by ghost** [Jackett/Jackett#5874]
https://torrent.e2k.ru/
To register you need to leave a statement here
https://torrent.e2k.ru/signapp.php

**Comment by Deputant** [comment]
What help is wanted&

**Comment by Deputant** [comment]
UPD: Fill the form. In the field "Comment for administration" write "drobovik" and you will be allowed to register

**Comment by garfield69** [comment]
the help flag is an invitation for any volunteer who has an account on this site  to go ahead and write a jackett indexer for this site.

I personally do not contribute to the scene, and have no history of torrent activity that I can show administrators.
After I create an indexer, if the site requires me to download or upload torrents on a regular basis to keep the account live, then the account will likely expire.
I've created over 150 indexers and do not have to time and interest to keep each and every one active.
So any site that requires me to show what a wonderful contributor I am, and provide links to other sites showing my wonderful ratio, and any other personal details, is just not my cup of tea. ;-)

with all this in mind, do you still want me to fill in the registration form, given that the comment for admin will not contain anything other that the name you provided ?

**Comment by Deputant** [comment]
I talked with staff, he agreed to activate your account without ratio proof. Just enter "drobovik"

**Comment by garfield69** [comment]
registration completed, pending approval.

**Comment by Deputant** [comment]
Approved

**Comment by garfield69** [comment]
login successful. Thank you.

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.633

**Comment by garfield69** [comment]
https://torrent.e2k.ru/ returning DNS_PROBE_FINISHED_NXDOMAIN (domain name not found)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://torrent.e2k.ru/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.20.1250
