### ISSUE TITLE
[REQ] 磁力柠檬(lemencili)

### ISSUE THREAD

**Issue by 472714747** [Jackett/Jackett#5877]
https://lemencili1.xyz/

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.618

**Comment by garfield69** [comment]
https://lemencili1.xyz/ and 2-5, 7-8 and 10 are all showing under maintenance posters.
https://lemencili6.xyz/ and https://lemencili9.xyz/ work via browser directly, but via jackett they bounce with http -> https -> http redirects.
they are probably using some kind of anti-bot security and I cant figure it out.
if this continues after 30 days then i'm deleting the indexer.
