### ISSUE TITLE
[Req] New Indexer - RainbowNation Sharing

### ISSUE THREAD

**Issue by Sytanek** [Jackett/Jackett#5880]
Open Signups - https://rainbownationsharing.net/signup.php

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.627
the indexer is called RNS, the full name takes up too much space in the columns ;-)

**Comment by Sytanek** [comment]
Thanks @garfield69 !

**Comment by garfield69** [comment]
RNS has merged with ABT
![image](https://user-images.githubusercontent.com/6933240/79110227-165ab600-7dce-11ea-9f13-f1c0d1a85405.png)

**Comment by garfield69** [comment]
Jackett 0.16.54
