### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Could not load file or assembly 'CloudFlareUtilities, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.: Could not load file or assembly 'CloudFlareUtilities, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest. (Test)

### ISSUE THREAD

**Issue by moejensen** [Jackett/Jackett#5883]
When i try to test my indexex in jacket i get the following error:

Exception (thepiratebay): Could not load file or assembly 'CloudFlareUtilities, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.: Could not load file or assembly 'CloudFlareUtilities, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.

Any idears of a solution?

**Comment by garfield69** [comment]
sounds like you have run afoul of the updater issue #5208
your best bet is to download and install the latest package from https://github.com/Jackett/Jackett/releases

if the updated continues to be a problem then enabling the disable-auto-update option from your jackett dashboard would be a way to prevent further issues until it is resolved.
don't forget to click on the apply-server-settings button to save your settings.

**Comment by moejensen** [comment]
I worked, thanks a lot :)
