### ISSUE TITLE
[myanonamouse] Your man_id did not work: Error, you are not signed in (Config)

### ISSUE THREAD

**Issue by rohittap** [Jackett/Jackett#5884]
I am not able to understand which IP address to use while creating a connection on myanonamouse.net.

Due to which I am not able to generate mam_id

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by garfield69** [comment]
I do not have an account on myanonamouse so I cannot test this for myself.
there is a similar issue open #5745
and a more detailed exploration at #4567 

I would have thought that the ip to use is the one that associated with the computer that is running jackett. 
if you are using a VPN then this will obviously break this since MAM will see what ever random IP id assigned by the VPN.
Other than that I have no more useful info, except to say it is possible that MAM is broken in this regards, as suggested by the last post in #4567

**Comment by rohittap** [comment]
I am not using VPN. 
Jackett is using 127.0.0.1 (Port 9117).

Once I log into myanonamouse, I log on to http://127.0.0.1:9117/UI/Dashboard
After clicking apply server settings, there should be a log file (this is what I am assuming), that should mention the server / IP used by Jackett, which is to be then used to create a new IP session on myanonamouse website to generate MAM_ID.

Please correct me if I am wrong. And help me out as I think I am following the instructions properly, just missing out on 1 small detail.

**Comment by garfield69** [comment]
please confirm that the browser you use to login to mam is on the same computer that is running jackett.
the ip address used to generate the man_id should be the computer address used to login to mam via the browser, and therefore the same ip as used when jackett tries to login to mam.
and that pretty much exhausts my knowledge of this affair. as I said before I don't have a mam account so I have no practical experience with the site.

**Comment by rohittap** [comment]
> please confirm that the browser you use to login to mam is on the same computer that is running jackett.
> the ip address used to generate the man_id should be the computer address used to login to mam via the browser, and therefore the same ip as used when jackett tries to login to mam.
> and that pretty much exhausts my knowledge of this affair. as I said before I don't have a mam account so I have no practical experience with the site.

Thank you so much for the help 
I was putting the wrong IP address.

Appreciate your help.

One more thing if you can help me out there as well. I am trying to download an ebook from myanonamouse which is available only to VIP, hence after adding the same in qbittorrent under trackers it says VIP access required. Can we bypass this by any chance?

**Comment by garfield69** [comment]
>One more thing if you can help me out there as well. I am trying to download an ebook from myanonamouse which is available only to VIP, hence after adding the same in qbittorrent under trackers it says VIP access required. Can we bypass this by any chance?

No. Think of a download link not as a path to a book on a shelf, but rather as a request to the librarian to fetch a book. If the librarian won't cooperate then you are out of luck.

**Comment by rohittap** [comment]
> > One more thing if you can help me out there as well. I am trying to download an ebook from myanonamouse which is available only to VIP, hence after adding the same in qbittorrent under trackers it says VIP access required. Can we bypass this by any chance?
> 
> No. Think of a download link not as a path to a book on a shelf, but rather as a request to the librarian to fetch a book. If the librarian won't cooperate then you are out of luck.

Understood.

Thank you for your help.

**Comment by Foxtrod89** [comment]
I just use same external IP from home ISP
