### ISSUE TITLE
[REQ] HD4Free

### ISSUE THREAD

**Issue by savahu** [Jackett/Jackett#589]
### Is the indexer private or public? If private, can you provide an invite?

Private, I can provide an invite

### Indexer URL

https://hd4free.xyz/

### Indexer language

English

**Comment by d2dyno** [comment]
There's a request already opened: 396

**Comment by savahu** [comment]
Alright, but I can provide an invite if it's needed. 
Thanks

**Comment by kaso17** [comment]
@savahu please send the invite to kaso1717 -at- gmail.com and I'll add it.
