### ISSUE TITLE
Freshon.tv/TVTorrents is back online but not working in Jackett

### ISSUE THREAD

**Issue by djetaine** [Jackett/Jackett#59]
Freshon was down for a while but came back the day before yesterday. I tried connecting through jackett but im getting an error. 
 Configuration failed: An error occurred while sending the request.

Console shows the following
11-16 15:41:39 Error Exception in Configure System.Net.Http.HttpRequestException
: An error occurred while sending the request. ---> System.Net.WebException: The
 underlying connection was closed: An unexpected error occurred on a send. --->
System.IO.IOException: Unable to read data from the transport connection: An exi
sting connection was forcibly closed by the remote host. ---> System.Net.Sockets
.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, Tr
ansportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar
)
   --- End of inner exception stack trace ---

Windows 10 x64
Jackett 0.6.7.0 / Jackett 0.6.45.0 (same error on both)

**Comment by Sek0n** [comment]
Someone posted on the thread there that they are getting the same error.

fwiw, I had mine still set up from before the site went down, and it still works now. Possibly just happens with new configurations, sense the sites code is probably quite a bit different than when went down maybe? Was restored with a pretty old backup.

**Comment by djetaine** [comment]
I had mine still set up in jackett from before but I had to sign up to
freshon again because I wasn't part of what was restored from january. I'm
sure that has something to do with it.

I tried removing and reading but no go.

**Comment by Sek0n** [comment]
Strange, I had to resign up as well. I used the same login info though, so didn't have to edit any info in Jackett.

Saw a few other people on their forums getting the error as well. So you're def not alone at least.

**Comment by djetaine** [comment]
Weird, same login information for me to, oh well. I'm sure they will
resolve it soon. Meantime I have mtv to hold me over. I like that one a lot
anyway now that I have it

**Comment by flightlevel** [comment]
@djetaine 
Is this still an issue. Just tried adding FreshOn (glad to be back) and it worked perfectly for me.

**Comment by Sek0n** [comment]
Others on their forums are saying it's working, so looks like it.
