### ISSUE TITLE
[feature request] redacted: session cookie support

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [Jackett/Jackett#5912]
If one has 2FA enabled on their RED account, they would not be allowed to login via Jackett.

Enter session cookies. If the user grabs a session cookie from their logged in browser, we can still log in to the account, and therefore, use the API.

See https://github.com/MattRob1nson/REDBetter/commit/b0cf0efa57f47d0c96e7b9737f989a7f226341ad for an implementation in Python (I'd implement it myself but don't know much about Jackett's internals.)

**Comment by garfield69** [comment]
what site is RED ?

**Comment by ThatNerdyPikachu** [comment]
redacted

**Comment by garfield69** [comment]
the redacted indexer is written in c#
jackett supports cookie logins, for example see https://github.com/Jackett/Jackett/blob/060972475f13ffe59fcc09c51ffe91a547a29029/src/Jackett.Common/Indexers/BitHdtv.cs

I'm not a c# developer so I cannot help with this.
calling on any c# volunteers to add an optional cookie login to redacted.

**Comment by bool-** [comment]
Okay I haven't dug deep into the Jackett codebase but it appears to be me an optional cookie config option can be added to the GazelleTracker code and if it's specified, ignore username and password fields. Unless someone with a deeper understanding of the codebase feels for some reason this would cause problems I'll fork the repo and add the cookie options.

**Comment by garfield69** [comment]
go for it.
just to be clear, will the **Redacted** Jackett config end up looking something like this?
```
Redacted -
[A music tracker]

Site Link
[https://redacted.ch/]

Note about 2FA
[- For regular login fill in the username and password and leave 2FA checkbox un-ticked.
 - For 2FA login fill in the Cookie and tick the 2FA checkbox. See https://github.com/Jackett/Jackett/wiki/Finding-cookies] for an example of how to find the cookie.]

Use 2FA [x]

Username
[                     ]
Password
[                     ]

Cookie
[                                                                                                              ]

Use Freeleech Tokens when available [x]
```

**Comment by bool-** [comment]
I created a PR that worked for me locally, give it a look and let me know if you think I should change anything. https://github.com/Jackett/Jackett/pull/7187

**Comment by garfield69** [comment]
I've made minor amendment by adding a cookiehint to provide more explicit help fetching cookies.

**Comment by garfield69** [comment]
Jackett 0.12.1804
