### ISSUE TITLE
[nyaasi] Exception (nyaasi): certificate validation failed: [Subject]  CN=nyaa.si[Issuer]  CN=Let's Encrypt Authority X3, O=Let's Encrypt, C=US[Serial Number]  032EC5D81BCFAD40893D2DA3D8A32B5771C1[Not Before]  8/8/19 3:00:30 AM[Not After]  11/6/19 3:00:30 AM[Thumbprint]  26C7D4B17D896635697DA34245A19D0A8C160E1D: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by klince** [Jackett/Jackett#5913]
I'm using CentOS7 with Jackett-Binary-AMDx64. All indexers of 'https' test failed while 'http' version working normally. Please help !

[curl_openssl.log](https://github.com/Jackett/Jackett/files/3539816/curl_openssl.log)
[jackett.log](https://github.com/Jackett/Jackett/files/3539817/jackett.log)

Jackett Version 0.11.640.0

**Comment by garfield69** [comment]
do you have access to a browser on your centos7 platform where you are running jackett, and can you browse https://nyaa.si without issues?

**Comment by klince** [comment]
![chrome_nyaa](https://user-images.githubusercontent.com/5339995/63674891-23fd0480-c81a-11e9-9c0e-cf06ab898b27.png)
Yes, I can browse it without issues.

**Comment by garfield69** [comment]
in your title you state that all https indexers fail. which other indexers have you tried to use with jackett, and do they all return the same certificate validation failed error?

**Comment by klince** [comment]
I tried https://animetosho.org/ and https://nyaa.si/ and https://www.torlock2.com/ (sorry I said all but not exactly tried all), they all return quite the same error of certificate validation. The difference between them might be the name of certificate. For example, torlock2 returns:
```
Exception (torlock): certificate validation failed: 
[Subject] CN=ssl375919.cloudflaressl.com, OU=PositiveSSL Multi-Domain, 
OU=Domain Control Validated [Issuer] CN=COMODO ECC Domain 
Validation Secure Server CA 2, 
O=COMODO CA Limited, L=Salford, S=Greater Manchester, C=GB 
[Serial Number] 00C98AC219727D74FFE10FEF5E18BC7FE4 
[Not Before] 8/13/19 8:00:00 AM [Not After] 2/20/20 7:59:59 AM 
[Thumbprint] D79BA83ED0C4426342528771A01CD148F5281A07 : 
The SSL connection could not be established, see inner exception.
```
I think there must be something wrong with my platform, but just don't know what is the problem.

**Comment by garfield69** [comment]
Try re-importing the certificates.
I don't have specifics on centos7 but for most linux its similar to:
   - (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
and reboot to ensure all active tasks get restarted with the updated CA repo.

**Comment by klince** [comment]
I've run this command but not reboot, and turns out to be still the same. 
I'll try to reboot later when back home. Thanks for replying. Hope it works =_=

**Comment by klince** [comment]
No luck still. Give up.
