### ISSUE TITLE
v0.11.643.0 Mono => Standalone upgrade instructions unclear, dick caught in ceiling fan

### ISSUE THREAD

**Issue by nSpecter** [Jackett/Jackett#5919]
Jackett Version 0.11.643.0 said,

> **Standalone version of Jackett is now available - Mono not required**
> To upgrade to the standalone version of Jackett, **click here** for install instructions. Upgrading is straight forward, simply install the standalone version and your indexers/configuration will carry over. Benefits include: increased performance, improved stability and no dependency on Mono.

Clicked there and was sent to: https://github.com/Jackett/Jackett#install-on-linux-amdx64

>**Install on Linux (AMDx64)**
>On most operating systems all the required dependencies will already be present. In case they are not, you can refer to this page ...docs.microsoft.com/blahblahblah...

>**Install as service**

>    1. Download and extract the latest Jackett.Binaries.LinuxAMDx64.tar.gz release from the releases page
>    2. To install Jackett as a service, open the Terminal and run sudo ./install_service_systemd.sh You need root permissions to install the service. The service will start on each logon. You can always stop it by running systemctl stop jackett.service from Terminal. You can start it again it using systemctl start jackett.service. Logs are stored as usual under ~/.config/Jackett/log.txt and also in journalctl -u jackett.service."

Downloaded the latest available at that moment,  v0.11.643.0, and extracted to /home/nspecter/Temp and ran: 
sudo ./install_service_systemd.sh

Received: "Agent successfully installed and launched!"

Refreshed Jackett browser window. "Standalone version available" message went away. Still reporting same version number, 0.11.643.0 (though github page **now** says a newer version is available as of 5 minutes ago) 
>v0.11.652 -- @jackettbot jackettbot released this 5 minutes ago

Checked System Monitor | Processes and Jackett now no longer running as a Mono process. **BUT** the new Jackett process properties shows its command line as "/home/nspecter/Temp/Jackett/jacket --NoRestart"
It appears to have NOT upgraded the already existing Jackett installation in /opt/jackett nor /home/nspectre/.config/Jackett. Upgrade instructions are NOT valid. It did not search for and find previous Jackett install and upgrade it. Files in /opt/jackett were not upgraded. 

I guess at this point I have a question and a request:

**Where are _new_ files from the downloaded archive _supposed_ to be extracted _before_ running the "install_service_systemd.sh" upgrade script?** And how would you recommend I proceed at this point?

I'm guessing extracting the new v0.11.652 archive to /opt/jackett and then running the shell script from there?

and can https://github.com/Jackett/Jackett#install-on-linux-amdx64 be made a bit clearer? 

Thanks :D

**Comment by rrrevin** [comment]
Jackett does not have an installer, per se. You must extract the zip/tar file someplace, then manually copy the contents on top of your existing install. If you installed to /opt/Jackett, the you copy the contents to there.

By default the install_system_service service creation script looks for jackett in the folder you are running the script from. If it is not, you'll need to update the service file that it created. Translation: You must run the install_system_service script in the folder where you actually installed jackett to and expect it to run from, not necessarily where you extracted it to.

**Comment by nSpecter** [comment]
That's what I needed to know. Thanks.
