### ISSUE TITLE
[lostfilm] Exception (lostfilm): Connection timed out: Parse error (Test)

### ISSUE THREAD

**Issue by Prosecutor** [Jackett/Jackett#5922]
Getting this type of error.

Logs: https://pastebin.com/5tnVk7J4

**Comment by garfield69** [comment]
working for me.
does appear to be a bit slow though.
could the site have suffered from some sort of overload that caused it to take too long to respond to requests, hence the connection timeouts?
is it working for you now or still broken?
what version of jackett are you on, on what platform?

**Comment by Prosecutor** [comment]
It's working now.

**Comment by SuberSeb** [comment]
У лоста отвалился retre.org, в котором лежат торрент-файлы, из-за этого были эти ошибки, я тоже столкнулся с ними.
