### ISSUE TITLE
[kickasstorrent] Cookie input text box no longer showing

### ISSUE THREAD

**Issue by Heeere-GittyGitty** [Jackett/Jackett#5931]
This is actually pretty simple to describe: When I edit configurations for Kickasstorrent (not katli) I have the URL and the COOKIE inputboxes. But then I tried putting a null string in the cookie inputbox and saving, but now when I go to KAT configurations, the cookie option and it's inputbox, no longer appear. UI bug?

Thanks

**Jackett version**:  Version 0.11.437.0

**Comment by Heeere-GittyGitty** [comment]
![image](https://user-images.githubusercontent.com/3912172/64010038-e5649400-cb10-11e9-8829-6e4bc620d0d8.png)

**Comment by garfield69** [comment]
katcr.co is public and does not need cookies.
the cookie box was removed starting with version v0.11.473
this may have been the first time you edited the indexer since the update so the profile got refreshed on your last save.

**Comment by Heeere-GittyGitty** [comment]
> 
> 
> katcr.co is public and does not need a cookie login.
> the cookie box was removed starting with version v0.11.473
> this may have been the first time you edited the indexer since the update so the profile got refreshed on your last save.
> [edit] correction to specify login.

No, i haven't updated it, I installed straight new right now, and I'm also new to this app, never used it before.

Anyway, at first the cookie option appeared, and the error was the "characters must be ASCII". Then I inserted a null string, and then the option disappeared but the error kept appearing.
I just removed and reinserted KAT, and check the both screens below:

![image](https://user-images.githubusercontent.com/3912172/64012890-83a72880-cb16-11e9-91f3-6b0c1026f9de.png)

and:

![image](https://user-images.githubusercontent.com/3912172/64012915-915cae00-cb16-11e9-8cbe-6e63312b9beb.png)

**Comment by Heeere-GittyGitty** [comment]
somehow it has a dirty configuration for KAT, where can i delete the confs for KAT?

**Comment by garfield69** [comment]
the ASCII issue is a duplicate of problem #5594 which seems to afflict some platforms.
The windows version of jackett seems unconcerned about katcr.co creating non-ascii cookies, but some linux flavours of jackett complain. 
So there is nothing you can do about this for now, other than refraining from using katcr.co with jackett until it is resolved.

**Comment by Heeere-GittyGitty** [comment]
I understand what you are saying, but the bug here seems to be UI related, driven by inconsistency in parsing the configuration when generating the UI.
I'm reinstalling the package from scratch, and will try to reproduce it again. If I can, I'll post a more detailed update here, otherwise, you've already closed it :(

**Comment by Heeere-GittyGitty** [comment]
Well, this is weird.. I tried removing the app (I'm using a QNAP NAS) and installing it again.
Even made sure that the entire package directory is gone, and I've cleared the browser's cache.

But somehow after reinstalling the UI seems to have the old config:
![image](https://user-images.githubusercontent.com/3912172/64052260-c3e9c380-cb75-11e9-8a84-31cfaef66e83.png)

And when for example I try to delete the KAT indexer, there is some kind of internal error with Jackett.

![image](https://user-images.githubusercontent.com/3912172/64052326-fa274300-cb75-11e9-8d5b-9df66c2be31e.png)

this is an old/dirty configuration right? Seems like there is a webserver copy cached somewhere.
Do you have any ideas about this?

**Comment by garfield69** [comment]
jackett on linux style platforms stores logs in ~/.config/Jackett/ folder, and configs for active indexers in the ~/.config/Jackett/Indexers folder.
to remove a config you can either: 
1. shutdown the jackett service and delete the kickasstorrent.json and kickasstorrent.json.bak from the  ~/.config/Jackett/Indexers folder
or
2. upgrade to jackett v0.11.643 - v0.11.659 which has a fix to delete the *.bak files when you use the trashbin on the jackett dashboard to delete an active indexer (older releases left the *.bak file behind and this would get reused when adding the indexer back to the active list).

**Comment by Heeere-GittyGitty** [comment]
Ok, I wasn't able to find the .config folder for jackett but I rebooted the NAS and reinstalled Jackett, and now it's clean (new Key and no confs at all).

When I configure the KAT indexer, there's the cookie option back again!! :)

![image](https://user-images.githubusercontent.com/3912172/64053949-aa984580-cb7c-11e9-8cb8-bc460dfe3ef1.png)

As you told before, wasn't this supposed to be gone on latest version? i'm on 437

**Comment by garfield69** [comment]
437 is not the latest version, and the cookie was removed with 473 :-)
the latest version is 659

**Comment by Heeere-GittyGitty** [comment]
yup, it just updated to 659 and the cookie option is gone.
Strange thing is, the indexer now works.
![image](https://user-images.githubusercontent.com/3912172/64054058-3611d680-cb7d-11e9-93b6-2913110b1276.png)


Let me test it

**Comment by Heeere-GittyGitty** [comment]
![image](https://user-images.githubusercontent.com/3912172/64054068-4de95a80-cb7d-11e9-8f5f-aa364fb3690b.png)

Oooook, so back to the state before. I see what happened now, and I was wrong, it's not a UI bug.
probably clone of #5594 as you mentioned.

Thanks for the support

**Comment by garfield69** [comment]
it only works until katcr.co writes a cookie that contains non-ascii and then you're stuffed, at least you are on linux and macos. for some reason its fine on windows. must be a common library (.net or something else) rather than the jackett code itself maybe.
I'm not a c# dev so I've no idea what if anything can be done about this :-(
