### ISSUE TITLE
[Request] Is possible to modify rss feed?

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#5932]
Hi, is possible to make some little modification to the generated rss feed?
On every feed I see this
```
      <torznab:attr name="category" value="2040" />
      <torznab:attr name="category" value="100024" />
      <torznab:attr name="seeders" value="0" />
      <torznab:attr name="peers" value="0" />
      <torznab:attr name="minimumratio" value="1" />
      <torznab:attr name="minimumseedtime" value="172800" />
      <torznab:attr name="downloadvolumefactor" value="0.5" />
      <torznab:attr name="uploadvolumefactor" value="1" />
```
But if someone try to work with flexget can't use all this custom attribute, because is not possible to import it, this because have to be formatted in this way
```
      <category>3010</category>
      <category>100006</category>
      <seeders>2</seeders>
      <peers>3</peers>
      <downloadvolumefactor>1</downloadvolumefactor>
      <uploadvolumefactor>1</uploadvolumefactor>
```
So, in my case I've a little script that take every rss and do a little sed modification.
So I ask if is possible to make a change.
In this way I can simply put the rss url into flexget configuration and do all the dirty work without use one external script

**Comment by garfield69** [comment]
sorry nope. those additional attributes are part of the torznab xml response specifications.
https://nzbdrone.readthedocs.io/Implementing-a-Torznab-indexer/#torznab-results
the fact that flexget assumes all xml should be in the `<tag></tag>` format is just too bad.
