### ISSUE TITLE
[TheGeeks] RSS feed fails to download

### ISSUE THREAD

**Issue by whitesnakeftw** [Jackett/Jackett#5938]
I'm able to add the RSS feed to my client and it shows correctly, but downloads don't work. I get:

> Cannot download 'http://127...'. The remote content was not found at the server (404)

**Comment by garfield69** [comment]
jackett version and platform?
have you confirmed you can download an ebook using the jackett dashboard manual search from thegeeks?
I don't have an account so I cannot test this for myself.

**Comment by whitesnakeftw** [comment]
@garfield69 Jackett Version 0.11.659.0 and Win 10.0.18362.295 x64

I just tried downloading something from the Jackett search and it doesn't seem to work. It says "This 127.0.0.1 page can’t be found" and so on.

**Comment by garfield69** [comment]
Then something has changed on thegeeks site with the download links.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by whitesnakeftw** [comment]
@garfield69  Here it is: [logthegeeks.txt](https://github.com/Jackett/Jackett/files/3563874/logthegeeks.txt)

Thanks

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.660

**Comment by whitesnakeftw** [comment]
@garfield69 Unfortunately it's still not working. I've taken a look at the diff and can confirm the actual download link looks like:

> `https://thegeeks.click/download.php/25018864/Udacity%20-%20Cloud%20Developer%20v1.0.0.torrent`

I've attached another enhanced log: [logthegeeks2.txt](https://github.com/Jackett/Jackett/files/3564848/logthegeeks2.txt)

**Comment by garfield69** [comment]
Oh, that's the problem when I don't have an account to test my changes on! :-(
Despite adding the new one download link, I fumbled my editing and left the old one in place. duh!
Please try jacket pre-release 0.11.661 and see if I have it correct this time.

**Comment by whitesnakeftw** [comment]
@garfield69 It's working now! Thanks!

Btw, I'm having the same exact issue with its sister site TheShow.click, could you please implement the same fix for that too?

I also have a feeling the same goes for the other sister sites (TheVault.click, ThePlace.click, TheEmpire.click, TheOccult.click), but as I'm in neither of those, I can't confirm.

**Comment by garfield69** [comment]
I really would prefer to see the enhanced log for any site that you are having problems on, just to be certain the issue is the same.
It also gives me a change to update the categories and so forth.
provide the log and i'll do the update no problem.

**Comment by whitesnakeftw** [comment]
@garfield69 Sure, here you go: [logtheshow.txt](https://github.com/Jackett/Jackett/files/3566402/logtheshow.txt)

**Comment by garfield69** [comment]
given that theEmpire's download link was updated exactly the same way nearly 2 years ago (Oct '17), it does not look like this family of indexers get a lot of use on jackett.
but since they are all cookie-cut from the same mould, I'll update the download link on the rest despite not having proof they need changing. 
If it turns out they did not needed, well, I can always change it back ;-)

**Comment by whitesnakeftw** [comment]
@garfield69 Thanks once again! Yeah, I think this is the best decision.

Btw, it's especially weird these indexers are overlooked because these trackers do not support autodownloads through IRC and they also disabled their own RSS feed, so Jackett's feed is the only way to autodl content from there. :)

**Comment by garfield69** [comment]
i'm not too surprised. jackett users tend to mostly be movie and tv followers. not much call for ebook readers.
