### ISSUE TITLE
[iptorrents] Exception (iptorrents): Cannot assign requested address: Cannot assign requested address (Test)

### ISSUE THREAD

**Issue by christronyxyocum** [Jackett/Jackett#5943]
[jackett_container.log](https://github.com/Jackett/Jackett/files/3566699/jackett_container.log)
**Jackett version**:  0.11.659.0

-------------------------------

Using latest Docker image from `linuxserver/jackett` I am unable to do anything with the IPTorrents tracker. The site is working, my account is working, etc. If I remove IPTorrents from Jackett I am unable to add it back and receive a message stating `Request to Jacket server failed` which seems to translate into the error in the subject of the Issue.

**Comment by garfield69** [comment]
works for me with https://iptorrents.com/ on my win10 jackett 0.11.665

maybe something wrong with your jackett setup... are you using a proxy or vpn or something other than the default jackett setup?

I note a few users having trouble with iptorrents, #4624 #4596 #5164, looks like the site is a bit tricky with its login process.

does turning on enhanced logging yield any additional html or messages prior to the stack dump?

**Comment by christronyxyocum** [comment]
Looks like one of the blacklists I use for PiHole updated to include IPT:

```
Sep  2 21:39:01 dnsmasq[7882]: query[A] iptorrents.com from 192.168.1.103
Sep  2 21:39:01 dnsmasq[7882]: /etc/pihole/gravity.list iptorrents.com is 0.0.0.0
Sep  2 21:39:01 dnsmasq[7882]: query[AAAA] iptorrents.com from 192.168.1.103
Sep  2 21:39:01 dnsmasq[7882]: /etc/pihole/gravity.list iptorrents.com is 0.0.0.0
```

Fixed by whitelisting the domain.
