### ISSUE TITLE
[REQ] Nitro.to

### ISSUE THREAD

**Issue by knifers** [Jackett/Jackett#5949]
http://nitro.to/
semi-private
pl-pl

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.698

**Comment by diabl0** [comment]
Unfortunenly it is not working properly.
magnet section works properly extracting url to download page,  ut magnet link itself is in js window.location.href

```html
<html><head>
    <script type="text/javascript">
        window.location.href = "magnet:?xt=urn:btih:62eaad2290063fa9fe7a5341584f9e091a9f5d19&dn=";
        function goBack() {
            window.history.go(-1);
        }
        window.setTimeout("goBack()", 250);
    </script>
</head>
<body>
    <a href=\"$magnetURL\">$torrentFilename</a>
</body></html>
```

**Comment by garfield69** [comment]
i am constrained by the limitations of the jackett cardigann processor.
the site's search results contain a magnet href that is only resolved via a call to a javascript getMagnet(this).
but cardigann does not run js.
and I have not been able to find the magnet hashinfo anyplace in either the primary search results page, or the torrents detail page, so I cannot build the magnet url directly.
so I did the next best thing and replaced the magnet href presented by the site 
```html
<a href="javascript:void(0)" onclick="getMagnet(this)" title="/__DWNMAGNET__?id=852229" class="short-link">
                            <b>Pobierz [Magnet]</b>
                            <img src="/img/style/bright/icons/magnet-icon.png" border="0" alt="Pobierz [Magnet]" title="Pobierz [Magnet]">                        </a>
```
and turned it into 
```
http://nitro.to/download_magnet.php?id=852229
```
which works for me from the jackett dashboard search results page, in that my utorrent is given a magnet to use, even if the magnet filename is not loaded with the torrent name. Better than nothing.

if you are saying that this is not good enough, or does not work for you, then the only option is to recode the nitro indexer as a c# indexer which should be able to call the js script getMagnet(this) and resolve the magnet url.
But I am not a c# dev, so you will need a volunteer c# dev to provide the PR.

**Comment by diabl0** [comment]
i wonder if https://github.com/Jackett/Jackett/wiki/Definition-format#download section can't be used  used to parse that js part with some kind of regexp? From what i understand download->selector . and download->filters->regexp can solve this issue, but i don't have enought experience and dev env to test it out :(

**Comment by garfield69** [comment]
nice out of the box thinking, but unfortunately not.
the details page html has the following script embedded:
```html
    <script type="text/javascript">
    function getTorrent(obj) {
        window.location.href = obj.title.replace("IDXXX/", document.getElementById("jurgen20").value + "/");
    }
    function getMagnet(obj) {
        window.location.href = obj.title.replace("__DWNMAGNET__", "download_magnet.php");
    }
    window.currentRev = 725;
    window.currentLoadedLangID = 2;
    setcookie('ckie', 1, 90000000000);
    </script>
```
which does not yield a magnet hashinfo until the server resolves the download_magnet.php call.
so there is nothing there for the download block to build the magnet href with.
even if i set up a 'before' path to download_magnet.php, this does not result in html being returned, it just sets window.location.href which is not available to the cardigann processor as it is a JS variable.

**Comment by diabl0** [comment]
Maybe using `before` you can try to get whole `head -> script` block via selector and then filter it using regexp to get window.location.href content

**Comment by ngosang** [comment]
@garfield69 I think this was fixed in #6931

**Comment by ilike2burnthing** [comment]
`ERR_CONNECTION_REFUSED` and `ERR_EMPTY_RESPONSE` shown at different times

Anyone else able to confirm?

**Comment by garfield69** [comment]
I'm also seeing ERR_CONNECTION_REFUSED

**Comment by ilike2burnthing** [comment]
```
Unfortunately, our current hosting company has shut down our server without giving us a reason.
We are moving the website to a new hosting.
```

**Comment by ilike2burnthing** [comment]
```
Update 26.05.2020 17:49:
We have obtained a copy of all data, we configure a new server. The return of nitro and filetracker pages should take place within 72 hours.
```

**Comment by garfield69** [comment]
online via https://nitro.to/

**Comment by garfield69** [comment]
https://nitro.to/ returning ERR_CONNECTION_REFUSED

**Comment by ilike2burnthing** [comment]
Working ok here. Temp issue? Try a VPN?

**Comment by garfield69** [comment]
temp issue. online for me too now.

**Comment by garfield69** [comment]
https://nitro.to/ returning 503
```html
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache Server at nitro.to Port 80
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://nitro.to/ returns
![image](https://user-images.githubusercontent.com/6933240/198181478-2016a758-0adb-4f55-a9a2-91d8fd905e45.png)

site closing 11/11/2022

I'll code a bypass so the indexer can be used until we remove it when the site goes.

**Comment by garfield69** [comment]
v0.20.2238
