### ISSUE TITLE
[bigtower] Login failed: Selector

### ISSUE THREAD

**Issue by gipasoft** [Jackett/Jackett#5950]
If I try to add indexer I obtain this error message:

```
Login failed: Selector "a[href="logout.php"]" didn't match
```
**Jackett version**:  0.11.665.0
**Mono version**: no mono

-------------------------------

**Comment by garfield69** [comment]
can you login to the site with your browser?

**Comment by gipasoft** [comment]
Yes I can Login but only with form on the left:

![image](https://user-images.githubusercontent.com/1884550/64201166-4cc27100-ce8e-11e9-8f9a-009689c632aa.png)

**Comment by garfield69** [comment]
@gipasoft  when I use http://bigtower.info/index.php?action=login i get a blank screen
so for me bigtower may be broken or using a "only italian ip addresses" filter.

what address do you use to get your bigtower forum login page?

@Jorman  is your bigtower jackett indexer working for you?

**Comment by gipasoft** [comment]
The address is: http://bigtower.info/smf/index.php

![image](https://user-images.githubusercontent.com/1884550/64201724-9eb7c680-ce8f-11e9-8c18-eda247896938.png)

**Comment by Jorman** [comment]
Bigtower, in the last months, have changed, so need to re-register again. Happen to mee too, the yml file is fine

```
Sep 03, 2019 09:16:40 PM	Info	
Found 150 releases from BigTower
```

**Comment by garfield69** [comment]
@gipasoft  ok, but this path takes you to the forum. where is the torrent search page?
what you you get if you use http://bigtower.info/index.php?action=login with your browser?

@jorman, so after registering, I get access to the forum http://bigtower.info/smf/index.php
but i get a blank screen on http://bigtower.info/index.php?action=login and this is the same path that the bigtower indexer on jackett uses, which for me currently returns the same error the OP reported `Login failed: Selector "a[href="logout.php"]" didn't match`
are you suing an unmodified indexer? Or do users have to do some additional presentation/settings/posting to get access to the tracker search pages?

**Comment by Jorman** [comment]
Torrent searching page is here:
http://bigtower.info/index.php?page=torrents
Log out is here:
http://bigtower.info/logout.php

Maybe is a bigtower problem, I log-off and now I can't log-in, session expired.

**Comment by gipasoft** [comment]
If i go in http://bigtower.info/index.php?action=login  I view a login page (after delete all cookies)

![image](https://user-images.githubusercontent.com/1884550/64203454-babd6700-ce93-11e9-8652-5bea360d5934.png)
 and then after login i am redirect to trhis page:

![image](https://user-images.githubusercontent.com/1884550/64203519-e3ddf780-ce93-11e9-9ca5-93ff095e7c53.png)

**Comment by garfield69** [comment]
yeah something is not right.
I get exactly the same results as you @gipasoft 
so for now I suggest we give it a few days and see if things change.
the bottom line is that I am pretty sure this is not a jackett issue ;-)

**Comment by Jorman** [comment]
I'm actually logged in again, I don't know how, I got session timeout several times, then I refresh the page and I'm logged, so .... 

Jackett side works for now

**Comment by gipasoft** [comment]
I have contacted BigTower admin, new user needs to be activated, now my account is activated and now Jackett works properly ... so for me this issue can be closed, thank for your support
