### ISSUE TITLE
XtremeZone (MyXYZ) API Implementation

### ISSUE THREAD

**Issue by time9x** [Jackett/Jackett#5954]
Hello, right now, myxz.eu has a new api, the old method of page scraping will not work, if someone from the dev team can update the files for this tracker, that will be great. This is the documentation: https://myxz.eu/api/doc 
I think this is all you will need, if you need something more, please tell me in this issue.

**Comment by garfield69** [comment]
will require switching from the cardigann based yaml definition to a c# indexer definition.
ping to any volunteer c# to rewrite.

**Comment by asasinuxp** [comment]
There is also https://scenefz.me/ with api adress https://scenefz.me/api/doc . Same source code, same maintainers, more trackers will be using in the future the same source code.

**Comment by RoloSoze** [comment]
@ngosang Application signup is now open if you're interested in this and #7774  
https://myxz.eu/login

Click on 'Apply'

**Comment by ngosang** [comment]
Notes for me in the future:
* C# abstract => https://myxz.eu/api/doc
* Support for flavors:
  * https://scenefz.me/
  * https://www.myxz.eu
  * https://icetorrent.org

**Comment by garfield69** [comment]
Jackett 0.16.585
