### ISSUE TITLE
[yggtorrent] improve movie search by accepting non-consecutives words

### ISSUE THREAD

**Issue by twolaw** [Jackett/Jackett#5955]
Radarr removes some words of movies title because those words are meaningless (the, and, of,...).
This indexer Yggtorrent has a strange behavior, it treat requests as if they are between double quotes, therefore many requests return 0 results because they don't fit the exact phrase.

Example : **Into the Wild** movie will be requested with **Into Wild** and indexer returns nothing because it searches its database with consecutives words "Into Wild".

A well known workaroud is to put each word between double quotes : **"Into" "Wild"** will return results.

I suggest to add this filter for movies searches.

Something like this :

> keywordsfilters:
>  \- name: re_replace
>      args: ["\b[^\s]+\b", "\"$&\""]`

[Issue #3679](https://github.com/Radarr/Radarr/issues/3679) in radarr

**Comment by garfield69** [comment]
try enabling the beta search engine option in your jackettt yggtorrent indexer config.
introduced with #5487 by @xfouloux  who has been working on the yggtorrent indexer recently.

**Comment by twolaw** [comment]
The beta search engine returns everything that matches at least one word of the request.
This is insane.

Example for the movie The Social Network the request is **social network**  it returns :

The.​Cheyenne.​Social.​Club.​1970.​MULTI.​DVDRip.​x264.​AC3-​Prem
Social Animals 2018 MULTi 1080p NF WEB H264-​NEO
Anti.​Social.​2015.​MULTi.​1080p.​WEB.​H264-​PREUMS.​mkv

4 out of 20 returns matches correctly the requested movie.

**Comment by xfouloux** [comment]
i'm only using the beta form URL in YGGTorrent, not doing something fancy ^^ !

it's the beta search engine in yggtorrent that is configured that way.

**Comment by twolaw** [comment]
So trying enabling the beta search engine is not a solution for now.
I think the suggestion I made on first post, putting each word between quotes, is worth being tried.

**Comment by xfouloux** [comment]
Well indeed it works ith double quote on each words, i will update the yml to do that !

**Comment by xfouloux** [comment]
okay modified on my docker and tried it's working fine now.

```
jackett            | 09-09 10:46:22 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://www2.yggtorrent.ch/engine/search?category=all&name=%22into%22%20%22wild%22&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date)
jackett            | 09-09 10:46:23 Debug WebClient(HttpWebClient2NetCore): Returning TemporaryRedirect => http://www2.yggtorrent.ch/engine/search?category=all&name="into" "wild"&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=1 <html>
jackett            | 09-09 10:46:26 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://www2.yggtorrent.ch/engine/search?category=all&name=%22into%22%20%22wild%22&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date)
jackett            | 09-09 10:46:27 Debug WebClient(HttpWebClient2NetCore): Returning TemporaryRedirect => http://www2.yggtorrent.ch/engine/search?category=all&name="into" "wild"&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=1 <html>
jackett            | 09-09 10:46:27 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://www2.yggtorrent.ch/engine/search?category=all&name=%22into%22%20%22wild%22&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&page=50)
```

**Comment by xfouloux** [comment]
might break the beta search for now unfortunately, i'll update the file

**Comment by xfouloux** [comment]
well i can mess with anime search :/ !!!

but it seems to be a sonarr issue, cause sonarr sends this for example :
```
jackett            | 09-09 11:13:39 Info Found 0 releases from YGGtorrent for: One Punch Man S2 10
jackett            | 09-09 11:13:41 Info Found 0 releases from YGGtorrent for: One Punch Man S2 10
jackett            | 09-09 11:13:45 Info Found 0 releases from YGGtorrent for: One Punch Man 2019 10
jackett            | 09-09 11:13:47 Info Found 0 releases from YGGtorrent for: One Punch Man 2019 10
jackett            | 09-09 11:13:51 Info Found 1 releases from YGGtorrent for: One Punch Man 10
jackett            | 09-09 11:13:53 Info Found 1 releases from YGGtorrent for: One Punch Man 10
```
As you can see it search S2 instead of S02

But for TVShow
```
jackett            | 09-09 11:08:39 Info Found 2 releases from YGGtorrent for: Las Chicas del Cable S02
jackett            | 09-09 11:08:52 Info Found 1 releases from YGGtorrent for: Cable Girls S02
jackett            | 09-09 11:08:56 Info Found 0 releases from YGGtorrent for: Die Telefonistinnen S02
jackett            | 09-09 11:08:58 Info Found 2 releases from YGGtorrent for: Las Chicas del Cable S02
jackett            | 09-09 11:10:11 Info Found 2 releases from YGGtorrent for: Cable Girls S01
jackett            | 09-09 11:10:12 Info Found 0 releases from YGGtorrent for: Die Telefonistinnen S01
jackett            | 09-09 11:10:15 Info Found 2 releases from YGGtorrent for: Las Chicas del Cable S01
```

**Comment by xfouloux** [comment]
Ok i found a workaround for anime in last pull request

**Comment by xfouloux** [comment]
ok, i closed all other pull request and merged all changes in the last one.

**Comment by garfield69** [comment]
jackett pre-release 0.11.683
