### ISSUE TITLE
[audiobooktorrents] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by GrayHogan** [Jackett/Jackett#5965]
If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.

--I am able to login via the website.  They do require you to click on an X among several buttons in order to login.

2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.

--I am running the most current stable version

3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Logs here:  https://pastebin.com/Pc5Dzi3D

Thank you in advance!

**Comment by garfield69** [comment]
the log snippet you provided is just the ordinary log, from the dashboard view-log.
not much help in this case.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by GrayHogan** [comment]
Ok- here it is:

https://pastebin.com/dJxfdwvv


I want it noted that I run Jackett as an admin, and that I have gone into properties to ensure that it has full permissions.

**Comment by garfield69** [comment]
the log shows you are being auto redirected to view your mail.
so login directly to the site with your browser and check and clear your mail and any other outstanding alerts that may interfere with you being able to visit the search-torrents page.

**Comment by GrayHogan** [comment]
That did it!  How very odd.  Will I have to keep deleting mail for it to continue to work, or will it just be ok from here on out?

**Comment by garfield69** [comment]
I don't have an account on ABT so I cannot offer confirmation one way or the other.
But I'm guessing that for this site, anytime there is mail, it will interfere with your jackett search.
Perhaps you can check your ABT account profile and see if there is a dont-notify-me-about-mail option or something similar.
