### ISSUE TITLE
[xtremezone] Exception (xtremezone): Login failed: No form found on https://myxz.eu/login.php using form selector form: Parse error (Test)

### ISSUE THREAD

**Issue by fcmircea** [Jackett/Jackett#5966]
The login works normally via web browser, but they've changed the theme and the login dialogue.

https://myxz.eu/login

Jackett Version 0.11.675.0
Mono Version: 6.0.0.327

**Comment by garfield69** [comment]
I don't have an account on this site so I cant test this for myself. 
try out jackett pre-release 0.11.678

**Comment by valentinolaru** [comment]
I have Jackett Version 0.11.687.0 and still not working, I'll try to commit a fix, but I need to waste some time on tests.

**Comment by garfield69** [comment]
jackett pre-release v0.11.693 includes the latest fixes for xtremezone's new layout.

**Comment by bobytza** [comment]
I'm still having problems with xtremezone, Version 0.11.703.0

`CardigannIndexer (xtremezone): Error while parsing row '
<div class="row mr-0 ml-0 pt-2 pb-2" style="border-top: dotted 1px var(--gray)">
	<div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-7 d-flex">
		<div class="float-left">
			<a href="/browse?categories%5B0%5D=45">
				<svg style="display: inline-block; width: 4em; height: 3em;">
					<use xlink:href="/img/category/metronic_dark.svg#tv_sd"></use>
				</svg>
			</a>
		</div>
		<div class="float-left pl-3" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
			<a href="/browse/471273/t/hot-date-s02e02-proper-webrip-x264-tbs" data-poload="/browse/471273/tooltip" data-html="true" data-placement="top">Hot.Date.S02E02.PROPER.WEBRip.x264-TBS</a>
			<br>
			<span style="font-weight: bolder">Genre:</span>
			<a href="/browse?search=comedy&amp;genre=2">Comedy</a>
			<span class="kt-badge kt-badge--warning kt-badge--inline kt-badge--pill kt-badge--rounded">
				new
			</span>
		</div>
	</div>
	<div class="col-6 col-sm-4 col-md-1 text-center text-muted" data-toggle="kt-tooltip" title="Sep 21, 2019, 8:35:02 AM">10 hours ago</div>
	<div class="d-none d-sm-block col-sm-4 col-md-1 text-center text-muted">1 times</div>
	<div class="col-6 col-sm-4 col-md-1 text-center text-muted">
		128.12 MB
	</div>
	<div class="col-6 col-sm-8 col-md-1 text-center text-success">
		<div class="row mt-auto mb-auto">
			<div class="col-sm-6">
				<span class="text-success">
					2
					<span class="d-md-none">seeders</span>
				</span>
			</div>
			<div class="col-sm-6">
				<span class="text-muted">
					0
					<span class="d-md-none">leechers</span>
				</span>
			</div>
		</div>
	</div>
	<div class="col-6 col-sm-4 col-md-2 col-xl-1 text-right float-right">
		<div class="btn-group btn-group-sm">
			<a href="/dwn.php?id=471273" class="btn btn-success">
				<i class="la la-cloud-download"></i>
			</a>
			<a href="/bookmark.php?torrent=471273&amp;action=add" class="btn btn-warning">
				<i class="la la-star"></i>
			</a>
		</div>
	</div>
</div>':

System.Exception: Error while parsing field=category, selector=a[href] > img, value=<null>: Selector "a[href] > img" didn't match 
<div class="row mr-0 ml-0 pt-2 pb-2" style="border-top: dotted 1px var(--gray)">
	<div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-7 d-flex">
		<div class="float-left">
			<a href="/browse?categories%5B0%5D=45">
				<svg style="display: inline-block; width: 4em; height: 3em;">
					<use xlink:href="/img/category/metronic_dark.svg#tv_sd"></use>
				</svg>
			</a>
		</div>
		<div class="float-left pl-3" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
			<a href="/browse/471273/t/hot-date-s02e02-proper-webrip-x264-tbs" data-poload="/browse/471273/tooltip" data-html="true" data-placement="top">Hot.Date.S02E02.PROPER.WEBRip.x264-TBS</a>
			<br>
			<span style="font-weight: bolder">Genre:</span>
			<a href="/browse?search=comedy&amp;genre=2">Comedy</a>
			<span class="kt-badge kt-badge--warning kt-badge--inline kt-badge--pill kt-badge--rounded">
				new
			</span>
		</div>
	</div>
	<div class="col-6 col-sm-4 col-md-1 text-center text-muted" data-toggle="kt-tooltip" title="Sep 21, 2019, 8:35:02 AM">10 hours ago</div>
	<div class="d-none d-sm-block col-sm-4 col-md-1 text-center text-muted">1 times</div>
	<div class="col-6 col-sm-4 col-md-1 text-center text-muted">
		128.12 MB
	</div>
	<div class="col-6 col-sm-8 col-md-1 text-center text-success">
		<div class="row mt-auto mb-auto">
			<div class="col-sm-6">
				<span class="text-success">
					2
					<span class="d-md-none">seeders</span>
				</span>
			</div>
			<div class="col-sm-6">
				<span class="text-muted">
					0
					<span class="d-md-none">leechers</span>
				</span>
			</div>
		</div>
	</div>
	<div class="col-6 col-sm-4 col-md-2 col-xl-1 text-right float-right">
		<div class="btn-group btn-group-sm">
			<a href="/dwn.php?id=471273" class="btn btn-success">
				<i class="la la-cloud-download"></i>
			</a>
			<a href="/bookmark.php?torrent=471273&amp;action=add" class="btn btn-warning">
				<i class="la la-star"></i>
			</a>
		</div>
	</div>
</div>
   at Jackett.Common.Indexers.CardigannIndexer.<PerformQuery>d__29.MoveNext()`

**Comment by valentinolaru** [comment]
I was expecting that, they are modifying the website everyday, the only way is making native script using their api  https://myxz.eu/api/doc

**Comment by garfield69** [comment]
@bobytza try out jackett pre-release v0.11.712
