### ISSUE TITLE
Sonarr + Searching for Season Packs

### ISSUE THREAD

**Issue by lattedesu** [Jackett/Jackett#597]
Hello,

I've been using Jackett with Sonarr together for a while, and loving it so far. Thanks!

I've a request, I'm not sure where to put this so here goes:

When using Sonarr along with BTN, if there is a season pack of the show, it's shown in the manual search results.

Let's assume a show called "TVShow X", both BTN, morethantv and freshon has s01 bluray packs. BTN is added from sonarr directly, freshon and morethantv is added over Jackett.

From sonarr , when you "manual search" s01e01 from the episodes list at Sonarr, the season pack is shown from along with individual episode from BTN, but not from Jackett and morethantv.

My Jackett Log contains this line:

> Found 0 releases from FreshOnTV for: TVShow X S01E01

When you search at freshon tracker, there isn't a "TVShow X S01E01" indeed, however, there is a season pack if you search "TVShow X S01" without exx part.

How can I also have this season pack appoach using Jackett + Sonarr ?

Thanks in advance,

**Comment by kaso17** [comment]
Unfortunately I don't have an BTN account to test it but the proper way to fix this would be to implement it on the sonarr side.
Something like "if search for season with epsiode number returns no results, try again with just the season number". Either the sonarr BTN implementation already supports this or the BTN search API is intelligent enough to do this.

**Comment by lattedesu** [comment]
Thanks for the reply @kaso17 , appreciated.

Well I can say is that BTN search result doesn't show anything for "TVShow X s02e01" because there isn't one available.

Also, "TVShow X s02" doesn't bring results there.

However, when I search "TVShow X season 3" (not season 03 or s03), I see results of the packs properly.

Just as a side note, here's their indexer code:

https://github.com/Sonarr/Sonarr/tree/master/src/NzbDrone.Core/Indexers/BroadcastheNet

I think something happens at request generator but I'm not a c# programmer myself.

Thank you, I'll move my request to their end.

**Comment by kaso17** [comment]
The sonarr BTN implementation use a proper API provided by BTN (http://api.btnapps.net/) and not the normal search. That might cause the different search behavior.
