### ISSUE TITLE
[torrentnetwork] Exception (torrentnetwork): no access: Parse error (Test)

### ISSUE THREAD

**Issue by MoeJoe87** [Jackett/Jackett#5972]
Hi

There is an issue again with TNT since some days now. 

Is the Problem at TNT? As i see the Tracker is Online.

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
Version 0.11.675.0

-------------------------------

**Comment by MoeJoe87** [comment]
Sorry its working again. Need to relogin with same password. Token is not valid anymore...can that not be fixed in Jackett? If the token is not valid anymore...do a relogin.

**Comment by ngosang** [comment]
@MoeJoe87 I don't have access to that tracker. Is it fixed?

**Comment by MoeJoe87** [comment]
@ngosang 

Did you fix it? It did not happen anymore. Its working now i guess. I think if it would not work i would need to relogin again already.

**Comment by ngosang** [comment]
> Did you fix it?

No

If the problem is you have to re-login manually often, I can do something like this => #6907
But I don't have account to test.

**Comment by MoeJoe87** [comment]
Before it was like every Month or so but now its working. I will let you know if it happens again. 

Thank you
