### ISSUE TITLE
[TorrentSeeds] Results not showing up when there's only one actual result

### ISSUE THREAD

**Issue by whitesnakeftw** [Jackett/Jackett#5973]
I'm guessing this is because when there's only one result on TS, the search lands you directly to the torrent's page (kind of like Google's "I'm Feeling Lucky").

**Comment by garfield69** [comment]
Can you give me an example of a search string that yields only one result so I can take a look. Thanks.

**Comment by garfield69** [comment]
never mind, I see it now.

the yaml indexer does not have conditional blocks to process a details page for one torrent or a search results page for multiple torrents.
so to fix this the yaml indexer would need to be replaced with one written in c#.

**Comment by RoloSoze** [comment]
@garfield69 Shouldn't this be closed now?

**Comment by garfield69** [comment]
This issue is occurring again.
When searching for `galaxy park s02e10` the Jackett torrentseeds indexer is returning 0 results
I can see Jackett doing `https://www.torrentseeds.org/browse_elastic.php?search_in=name&search_mode=all&order_by=added&order_way=desc&query=galaxy+park+s02e10`
and the log shows
```
WebClient(HttpWebClient2): Returning Redirect => https://www.torrentseeds.org/details.php?id=1720739 813 bytes
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
		<html xmlns='http://www.w3.org/1999/xhtml'>
		<head>
		<meta http-equiv='refresh' content="0; url=/details.php?id=1720739" />
		<title>Block Settings</title>
    <link rel='stylesheet' href='/templates/1/1.css' type='text/css' />
    <script type="javascript">
    location.href = location.protocol+protocol.concat("//").concat(window.location.hostname)+details.php?id=1720739;
</script>
    </head>
    <body>
    <div>
	  <div>Redirecting</div>
		<div style='padding:8px'>
		<div style='font-size:12px'>
		<br />
		<br />
		<a href='https://www.torrentseeds.org/details.php?id=1720739'>Found one result, redirecting</a>
		</div>
		</div>
		</div></body></html>
```
followed by
```
Manual search for "galaxy park s02e10" on torrentseeds with 0 results.
```

**Comment by ngosang** [comment]
This feature was never implemented. We have to add some code to detect if the result is the details page and parse the fields for that case. Low priority for me.

**Comment by garfield69** [comment]
I thought that was what PR #7603 was supposed to have achieved?

**Comment by ngosang** [comment]
You are right, I lost that part of the code in another change.

**Comment by garfield69** [comment]
Jackett 0.16.2269
