### ISSUE TITLE
auto updater breaking the installation requiring reinstall

### ISSUE THREAD

**Issue by PabloDons** [Jackett/Jackett#5975]
**Jackett version**:  v0.11.675.0

-------------------------------

I've seen countless issues regarding updater errors, but I still can't resolve the issue. I am having a lot of trouble investigating the issue since manual initialization of the updater (through the web-page) works fine, but when automatically initializing, systemd keeps restarting it and overflowing the logs and the first exception gets deleted. This is what the logs say each restart.

https://pastebin.com/9Wy084z9

The recurring problem here is the file `System.Private.Xml` that fails to load. Here is the updater.txt file:

https://pastebin.com/i2JEmjhE

My setup is as follows:
- Running on debian 9
- Dedicated jackett unix user and group "jackett"
- Jackett installed in directory /opt/Jackett with perms 755 and owned by the above user.
- systemd service setup using `install_service_systemd.sh`
- systemd service file descriptor below

```
[Unit]
Description=Jackett Daemon
After=network.target

[Service]
SyslogIdentifier=jackett
Restart=always
RestartSec=5
Type=simple
User=jackett
Group=jackett
WorkingDirectory=/opt/Jackett
ExecStart=/opt/Jackett/jackett --NoRestart
TimeoutStopSec=20

[Install]
WantedBy=multi-user.target
```
If needed, I can try disabling systemd from restarting the service in order to get the first error.

**Comment by rrrevin** [comment]
This appears to be related to https://github.com/Jackett/Jackett/issues/5208

Auto update on Linux is broken for many people. The auto update process leaves 0 byte files behind when updating, thus breaking the update process.

**Comment by rrrevin** [comment]
Forgot to mention : 
Disable auto update, and do a manual update for any upgrades you want until this is resolved.

**Comment by PabloDons** [comment]
Damn. Can you guys at least mention this in the readme? I've spent way too long fidgeting with this.

**Comment by ngosang** [comment]
@PabloDons @rrrevin  could you test this? thank you!
https://github.com/Jackett/Jackett/issues/5208#issuecomment-546564391

**Comment by ngosang** [comment]
@PabloDons the fix => https://github.com/Jackett/Jackett/issues/5208#issuecomment-547709864
