### ISSUE TITLE
mkvcage shutdown..

### ISSUE THREAD

**Issue by rrrevin** [Jackett/Jackett#5983]
It looks like it was shutdown..
https://torrentfreak.com/popular-torrent-site-mkvcage-faces-lawsuit-and-goes-offline/

**Comment by garfield69** [comment]
back again https://torrentfreak.com/popular-torrent-uploader-mkvcage-returns-but-legal-troubles-remain-191017/ on .nl domain.

**Comment by garfield69** [comment]
gone. domain suspended.
