### ISSUE TITLE
[empornium] Found no results while trying to browse this tracker (test)

### ISSUE THREAD

**Issue by MaDTaZ** [Jackett/Jackett#5991]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

(At the bottom of your Jackett Dashboard page) **newet .689**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Jackett.Binaries.LinuxAMDx64.tar.gz
**:
No search results at all
-------------------------------

**Comment by garfield69** [comment]
I don't have an account on this site so I cannot test for myself.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by MaDTaZ** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/3613357/log.txt)

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.691 and report back success.
if failure, please post new logs so I can see what else needs amending.
thanks.

**Comment by MaDTaZ** [comment]
That fixed it everything is working able to keep sign in and also is searching now
