### ISSUE TITLE
curl: (47) Maximum (50) redirects followed

### ISSUE THREAD

**Issue by NoxInmortus** [Jackett/Jackett#5992]
Hello, I have noticed a strange behaviour that I don't yet understand.

I have a jackett docker container using latest linuxserver.io image, and I cannot curl succeffully the jackett page. This try is with a fresh jackett install on a fresh Debian 9 without anything particular on it :

root@nas:[~]: curl -IL localhost:9117
HTTP/1.1 301 Moved Permanently
Date: Sat, 14 Sep 2019 21:41:51 GMT
Server: Kestrel
Location: /UI/Dashboard

HTTP/1.1 404 Not Found
Date: Sat, 14 Sep 2019 21:41:53 GMT
Server: Kestrel

root@nas:[~]: curl -L localhost:9117
curl: (47) Maximum (50) redirects followed

And as i'm tring to setup monitoring on the web access page, this doesn't works because of that.

But, the weird thing, is that jackett is actually working. I can get to it on firefox and make it fetch trackers without issue.

Anyone?
So I really don't understand.

**Comment by garfield69** [comment]
have you tried using 127.0.0.1 instead of localhost?

**Comment by NoxInmortus** [comment]
Hello @garfield69, of course, and the result is identitcal

The result is also the same if I try from my laptop using the ip adress of the machine.

I first noticed this on a running jackett on a remote machine, and I reproduced the same behavior this newly machine and fresh jackett docker run.

**Comment by garfield69** [comment]
ok wait. so is jackett set up to allow external access, as shown in the jackett dashboard at the bottom of the active list?

**Comment by NoxInmortus** [comment]
@garfield69 Yes it does indeed.

The filled parameters are :
- Server port : 9117
- Proxy type : http
- External acess : checked

**Comment by garfield69** [comment]
I don't run a docker Jackett, mine is running as a native local service. but even with this set up I get the same 301/404 combo when using a terminal to curl the way you did
```
garfield69@Ubuntu-VirtualBox:~$ curl -IL localhost:9117
HTTP/1.1 301 Moved Permanently
Date: Sun, 15 Sep 2019 08:21:42 GMT
Server: Kestrel
Location: /UI/Dashboard

HTTP/1.1 404 Not Found
Date: Sun, 15 Sep 2019 08:21:42 GMT
Server: Kestrel
``` 
so this is not an indication that you cannot reach Jackett, rather it is Jackett not liking the request.

so I tried a curl -vvv http://127.0.0.1:9117/api/v2.0/indexers/zooqle/results/torznab/api?apikey=k***redacted***s&t=search&cat=&q=
```
garfield69@Ubuntu-VirtualBox:~$ curl -vvv http://127.0.0.1:9117/api/v2.0/indexers/zooqle/results/torznab/api?apikey=k***redacted***s&t=search&cat=&q=
[1] 15472
[2] 15473
[3] 15474
[4] 15475
[2]   Done                    t=search
garfield69@Ubuntu-VirtualBox:~$ *   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 9117 (#0)
> GET /api/v2.0/indexers/zooqle/results/torznab/api?apikey=k***redacted***s HTTP/1.1
> Host: 127.0.0.1:9117
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sun, 15 Sep 2019 08:36:42 GMT
< Content-Type: application/rss+xml; charset=utf-8
< Server: Kestrel
< Content-Length: 67109
< Cache-Control: no-store,no-cache
< Pragma: no-cache
< 
<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://127.0.0.1:9117/" rel="self" type="application/rss+xml" />
    <title>Zooqle</title>
    <description>Zooqle is a Public torrent index providing a huge database of verified torrents</description>
    <link>https://zooqle.com/</link>
    <language>en-us</language>
    <category>search</category>
    <image>
      <url>http://127.0.0.1:9117/logos/zooqle.png</url>
      <title>Zooqle</title>
      <link>https://zooqle.com/</link>
      <description>Zooqle</description>
    </image>
    <item>
      <title>CareUEyes Pro 1 1 24 2 (Filters Blue Light) Portable {B4tman}</title>
      <guid>https://zooqle.com/careueyes-pro-1-1-24-2-filters-blue-light-portable-b4tman-xhca6.html?hl=%2A</guid>
      <jackettindexer id="zooqle">Zooqle</jackettindexer>
      <comments>https://zooqle.com/careueyes-pro-1-1-24-2-filters-blue-light-portable-b4tman-xhca6.html?hl=%2A</comments>
      <pubDate>Sun, 15 Sep 2019 20:19:43 +1200</pubDate>
      <size>0</size>
      <description />
      <link>magnet:?xt=urn:btih:E43BE5D21FC3B49C8F7BB6E2572664033090BD4B&amp;dn=%5Bzooqle.com%5D CareUEyes Pro 1 1 24 2 %28Filters Blue Light%29 Portable {B4tman}&amp;tr=http://explodie.org:6969/announce&amp;tr=http://announce.xxx-tracker.com:2710/announce&amp;tr=http://open.acgtracker.com:1096/announce&amp;tr=https://bigfoot1942.sektori.org/announce&amp;tr=https://bigfoot1942.sektori.org:443/announce</link>
      <category>4000</category>
      <enclosure url="magnet:?xt=urn:btih:E43BE5D21FC3B49C8F7BB6E2572664033090BD4B&amp;dn=%5Bzooqle.com%5D CareUEyes Pro 1 1 24 2 %28Filters Blue Light%29 Portable {B4tman}&amp;tr=http://explodie.org:6969/announce&amp;tr=http://announce.xxx-tracker.com:2710/announce&amp;tr=http://open.acgtracker.com:1096/announce&amp;tr=https://bigfoot1942.sektori.org/announce&amp;tr=https://bigfoot1942.sektori.org:443/announce" length="0" type="application/x-bittorrent" />
      <torznab:attr name="category" value="4000" />
      <torznab:attr name="magneturl" value="magnet:?xt=urn:btih:E43BE5D21FC3B49C8F7BB6E2572664033090BD4B&amp;dn=%5Bzooqle.com%5D 
[...etc etc etc...]
      <torznab:attr name="seeders" value="1" />
      <torznab:attr name="peers" value="1" />
      <torznab:attr name="minimumratio" value="1" />
      <torznab:attr name="minimumseedtime" value="172800" />
      <torznab:attr name="downloadvolumefactor" value="0" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>
  </channel>
* Connection #0 to host 127.0.0.1 left intact
</rss>^C
[1]   Done                    curl -vvv http://127.0.0.1:9117/api/v2.0/indexers/zooqle/results/torznab/api?apikey=k***redacted***s
[3]-  Done                    cat=
[4]+  Done                    q=
```
and got results, what about you (replace zooqle with whatever active Jackett indexer you have available) ?

**Comment by NoxInmortus** [comment]
@garfield69 Thanks for your insight, so there is a real issue then.

I clearly prefer not to consider this option for multiples reasons :
- What if the used indexer does not work anymore anymore ?
- What if I want to monitor multiple jacketts using differents indexers ? Because of that and because the api key will be different, I cannot template jackett monitoring. Very annoying.
- Further more, I dont like passing the api key in a monitoring url for just monitoring.

**Comment by garfield69** [comment]
sure.
so the question is what are you trying to monitor: that the Jackett server is up and running?
in which case your `curl -IL` returning 301 proves that the docker Jackett server is active.
if your docker Jackett is not active you would get 
```
garfield69@Ubuntu-VirtualBox:~$ curl -IL localhost:9117
curl: (7) Failed to connect to localhost port 9117: Connection refused
```
so there is no problem is there?

**Comment by NoxInmortus** [comment]
Well, as this is not false, this is not true either.

a 301 return code only indicates there is a permanent redirection going on. If you have a reverse proxy behind, you may have the 301 whether or not you got the container running.
Any monitoring system will grab the last return code and not the first (301 > 404).

But I can configure stuff to not follow redirect and to say OK if there is a 301... So yes, this is not perfect but I will go on that.

I really think that returning 404 is a weird behavior, and such thing should be, but that not of my ressort.

@garfield69 thanks for your help, I consider this as closed.
