### ISSUE TITLE
[Demonoid] Formatting changed 

### ISSUE THREAD

**Issue by send-your-nudes** [Jackett/Jackett#5994]
The format is now:

If someone has time, they should update the code as subcategory is now for gender, while quality is separated.

1. stacked categories...
```
c1&c2&c3
```
etc...

2. quality formatting...
```
?category=X&quality=X
```
etc...

3. category formatting...
```
?category=[min]1 - [max]12
```

4. language formatting...
```
?language=X
```

**Comment by garfield69** [comment]
stacked categories does not seem to work, so i've dropped it for now. 
have added category selection in the profile for those that need to restrict hits to just tv or movies, default is 0 (all).
jackett implements the [Torznab](https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer) (with [nZEDb](https://github.com/nZEDb/nZEDb/blob/dev/docs/newznab_api_specification.txt) category numbering), which I don't think allow for subcategory selection, or at least, the cardigann processor appears to only handle primary categories.
for now quality is hard-coded to 0 (all), as is language. if demand appears, I can add language selection in the profile.
jacket pre-release 0.11.694

**Comment by send-your-nudes** [comment]
I tested it yesterday before posting it worked fine also tested now and still working.

Here's the example: to stack apps and books but it doesn't stack by quality, but with category + subcategory _https://www.dnoid.to/files/?c10&c3_

**Comment by garfield69** [comment]
Yeah, Nah.
For me, when I stack category=2 audio books, and category=4 comics
https://www.dnoid.to/files/?c2&c4
I do not get any results, but I can see 
https://www.dnoid.to/files/?category=2&subcategory=0&language=0&quality=0&incldead=3&search=&sort=
and 
https://www.dnoid.to/files/?category=4&subcategory=0&language=0&quality=0&incldead=3&search=&sort=
has plenty of results.
and 
stacking category=3 books and category=10 music video
https://www.dnoid.to/files/?c3&c10
yields four category=2 audio books and two category=1 apps
which is not what I expected to see.
Are you getting something different?
which is why I sa

**Comment by send-your-nudes** [comment]
c is not a category, c is subcategory.

So you need subcategory values which ranges from [min]1 - [max] 280~ i guess

**Comment by garfield69** [comment]
well in that case the current demonoid yaml indexer cannot support it, as the only reference it can manage is categories.
to do subcategories in the way you describe would probably need for the indexer to be rewritten in c#

**Comment by send-your-nudes** [comment]
i guess stacking is only good if someone wants to include multiple categories and subcategories at once.

**Comment by send-your-nudes** [comment]
Actually @garfield69 I think this needs to be reverted to the first commit just with new numbers.

which should be formated like this...

```
 # Applications
      - {id: 1, cat: PC/Phone-Android, desc: "Applications Android"}
      - {id: 2, cat: PC/Phone-IOS, desc: "Applications Iphone / Ipod touch"}
      - {id: 3, cat: PC, desc: "Applications Linux"}
      - {id: 4, cat: PC/Mac, desc: "Applications Mac"}
      - {id: 5, cat: PC/Phone-Other, desc: "Applications Mobile phone"}
      - {id: 6, cat: PC, desc: "Applications PocketPC"}
      - {id: 7, cat: PC/0day, desc: "Applications Windows"}
      # Audio Books
      - {id: 8, cat: Audio/Audiobook, desc: "Audio Books Action"}
      - {id: 9, cat: Audio/Audiobook, desc: "Audio Books Adventure"}
      - {id: 10, cat: Audio/Audiobook, desc: "Audio Books Biography"}
      - {id: 11, cat: Audio/Audiobook, desc: "Audio Books Childrens"}
      - {id: 12, cat: Audio/Audiobook, desc: "Audio Books Computers and Technology"}
      - {id: 13, cat: Audio/Audiobook, desc: "Audio Books Contemporary"}
```
etc...

And just replace...
`cnumber=1&cnumber=2`
to...
`cnumber&cnumber`
