### ISSUE TITLE
Show not 

### ISSUE THREAD

**Issue by cryptoz** [Jackett/Jackett#5995]
Jackett Version 0.11.689.0 
Mono JIT compiler version 6.0.0.319
Ubuntu 18
no results for Dark on IPT
sonarr shows all the correct tags(IMDB TVDB Trakt etc.) results show up in jackett but not the correct show.

**Comment by garfield69** [comment]
how about you do a screenprint of the browser iptorrents website search results for the show you are talking about, and one of the jackett search using the iptorrents indexer, so we can see what you are talking about, because, honestly, **Dark** is too vague for me to use to figure out what show or movie you are talking about.

**Comment by cryptoz** [comment]
I am not being vague, Dark is literally the name of the show and it is the only show with just that name.  
![Screenshot from 2019-09-17 14-26-56](https://user-images.githubusercontent.com/15572607/65077647-a16aef00-d958-11e9-841c-b82b8f560342.png)
![Screenshot from 2019-09-17 14-27-37](https://user-images.githubusercontent.com/15572607/65077648-a16aef00-d958-11e9-9978-5c8e1f8f4908.png)
![Screenshot from 2019-09-17 14-31-36](https://user-images.githubusercontent.com/15572607/65077650-a16aef00-d958-11e9-84c3-52e2810864ed.png)

Thanks for the software, this is the only issue I've had and its a minor one, just trying to help make it better, best of luck.

**Comment by garfield69** [comment]
i see.
well dark as a single search item is always going to be problematic to find as iptorrents has hundreds of titles with dark in it, and there is no way a general search is ever going to work.
so you have to use the category filter to narrow down the search.
iptorrents lists the show DARK as tv/foreign so when using the dashboard search, select that category to narrow down the results.
![image](https://user-images.githubusercontent.com/6933240/65078654-9021f100-d9f1-11e9-9084-b404d002cea2.png)
