### ISSUE TITLE
Rework definitions/speedtorrentreloaded.yml

### ISSUE THREAD

**Issue by tronotoc** [Jackett/Jackett#5998]
Hello, 
some of the categories from speedtorrentreloaded.yml are missing/wrong, for example
 - {id: 200, cat: Movies/HD, desc: "Filme: UHD"}

Maybe someone can fix it. Here are the actual categorie definitions: 

`|<td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c206" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=206&amp;showsearch=1">Filme_SD</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c94201" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=94201&amp;showsearch=1">Staffeln-SD</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c291" type="checkbox" checked value="1"><a class="catlink" href="browse.php?cat=291&amp;showsearch=1">Filme_Int.SD</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c137" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=137&amp;showsearch=1">Musik: Video</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c211" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=211&amp;showsearch=1">Serien: Staffeln-HD</a></td>
  | </tr><tr><td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c290" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=290&amp;showsearch=1">Filme_Int.HD</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c204" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=204&amp;showsearch=1">Filme_DVD</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c203" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=203&amp;showsearch=1">Filme_HD</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c205" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=205&amp;showsearch=1">Filme_3D</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c603" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=603&amp;showsearch=1">Erotik: XXX PDF</a></td>
  | </tr><tr><td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c116" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=116&amp;showsearch=1">Spiele: Konsolen</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c117" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=117&amp;showsearch=1">Spiele: Windows</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c126" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=126&amp;showsearch=1">Software: Mac / Linux</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c120" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=120&amp;showsearch=1">Musik: Alben/Sampler </a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c121" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=121&amp;showsearch=1">Serien: SD</a></td>
  | </tr><tr><td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c122" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=122&amp;showsearch=1">Erotik: XXX Film</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c123" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=123&amp;showsearch=1">Doku_SD</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c124" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=124&amp;showsearch=1">Spiele: sonstige</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c125" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=125&amp;showsearch=1">Software: Windows</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c129" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=129&amp;showsearch=1">Software: Handy / Navi / Sonst</a></td>
  | </tr><tr><td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c131" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=131&amp;showsearch=1">Serien: HD</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c132" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=132&amp;showsearch=1">Serien: Packs</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c135" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=135&amp;showsearch=1">Musik: Discographie</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c138" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=138&amp;showsearch=1">Doku_HD</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c141" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=141&amp;showsearch=1">A/Ebook: Hoerbook</a></td>
  | </tr><tr><td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c142" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=142&amp;showsearch=1">A/Ebook: EBooks</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c143" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=143&amp;showsearch=1">sonstige:PDF</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c144" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=144&amp;showsearch=1">Erotik: XXX Pics</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c350" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=350&amp;showsearch=1">Sport</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c604" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=604&amp;showsearch=1">XXX-Games</a></td>
  | </tr><tr><td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c201" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=201&amp;showsearch=1">Filme_Remux</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c200" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=200&amp;showsearch=1">Filme_UHD</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c208" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=208&amp;showsearch=1">Erotik Audiobook</a></td>
  | <td class="tablea" style="padding-bottom: 2px;padding-left: 7px" nowrap><input name="c210" type="checkbox" value="1"><a class="catlink" href="browse.php?cat=210&amp;showsearch=1">MAC / Linux</a></td>
  | <td class="tablea" style="padding-left: 5px"><a href="browse.php?all=1&amp;showsearch=1"><b>Alle anzeigen</b></a></td>'

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.698

**Comment by tronotoc** [comment]
Thanks, it's working now.
