### ISSUE TITLE
[REQ] add movies categories to nCore tracker

### ISSUE THREAD

**Issue by gurabli** [Jackett/Jackett#6]
Hi, I'm glad Jackett development is continuing, thank you for all of you!
I would like to ask for your help. I'm having some hard time to add categories mapping for movies support on nCore tracker, just can't figure out how to do this. I don't really understand the code. The indexer is working great, but would be so nice to have movies support for CP too on this very popular tracker. I'm here to help with the site and testing. I guess it is now the matter of mapping the correct categories, but I'm unable to do it on my own.
Edit: @flightlevel Please let me know what support you need from my side, I'm here to help in any way I can!

**Comment by flightlevel** [comment]
Hi @gurabli 
If you look at another indexer eg https://github.com/Jackett/Jackett/blob/master/src/Jackett/Indexers/IPTorrents.cs#L43 see how from line 43 it starts listing all the content types it supports. Whereas if you look at the ncore one there is nothing.
We need to know all the content types ncore supports. Also when you search and the results come back does it tell you what category each result comes from?

**Comment by gurabli** [comment]
HI @flightlevel 

Many thanks for your reply! I will try to help us much as I can. 
Here is a list of content type ncore supports in respect to Movies (Film), Music and e-Book. As with the series, there are two version of each quality, ENG and HUN, you can see that for series, it is the same for movies. When a category is selected, it return the category, added after each one.

Movies (ENG and HUN):

Film (ENG SD) = xvid
Film (ENG DVD) = dvd
Film (ENG DVD9) = dvd9
Film (ENG HD) = hd

Film (HUN SD) = xvid_hun
Film (HUN DVD) = dvd_hun
Film (HUN DVD9) = dvd9_hun
Film (HUN HD) = hd_hun

Music (also ENG and HUN):

Mp3 = mp3
Lossless = lossless

Mp3 (HUN) = mp3_hun
Lossless (HUN) = lossless_hun

e-Book:

e-Book = ebook
e-Book (HUN) = ebook_hun

Do let me know if the above provided information is enough to add the categories and mappings.
Once again, many thanks!

**Comment by gurabli** [comment]
OK, I did the following: https://github.com/gurabli/Jackett/commit/55b5ed49c5395659bfb3b9a99ade598f15a26659

It is possible that it is completely wrong. Now I would need to test it, but don't know how to compile Jackett and test if the things I did are actually working.

**Comment by gurabli** [comment]
@flightlevel 
I managed to add movies to search, but not with adding categories. If you look at the ncore indexer configuration, it is somewhat different then iptorrents or other indexers are where categories are defined. Look at here what I did: https://github.com/gurabli/Jackett/blob/f26ebecc20b1ea28b5aad29474687192c31e0698/src/Jackett/Indexers/nCore.cs

But how can I add Movies, etc. in Jackett webui? 

Could you email me please, my email address is my name at gmail dot com

**Comment by flightlevel** [comment]
@gurabli Getting closer, sent you an email

**Comment by gurabli** [comment]
@flightlevel Got the email, I replied!

**Comment by flightlevel** [comment]
Movies added
