### ISSUE TITLE
Morethantv season search not returning results

### ISSUE THREAD

**Issue by domrin123** [Jackett/Jackett#60]
I noticed this while searching for a season:

 Morethantv does not return any results if for example a search query simply ends in "S05". It looks like the search needs to include an asterisk ("S05*") if you want to search for episodes in that season or "Season 5" if you want the season pack. I don't know if this applies to other trackers, but just something I noticed with morethantv.

**Comment by flightlevel** [comment]
This has been fixed and will be available in the next release.
https://github.com/Jackett/Jackett/pull/68
