### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: Selector

### ISSUE THREAD

**Issue by ArthurKnoep** [Jackett/Jackett#6003]
yggtorrent seems to have changed a little bit their site and it has break jackett

Here the complete log:
```
Exception (yggtorrent): Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match: Parse error
```

**Comment by garfield69** [comment]
um, no, works for me.
going to need to see the html from the login attempts to see if we can spot what's the matter with yours.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by ArthurKnoep** [comment]
I figured it out myself. 

In fact my account was banned 😄 

Sorry for the useless issue

**Comment by garfield69** [comment]
I would still love to get a look at the enhanced log, if you can manage it.
I may be able to identify the error message and add it to the login trap so other users will get a useful error message rather than the useless login-failed-selector one. Thanks.

**Comment by ArthurKnoep** [comment]
https://pastebin.com/UV706Lgx

I think you have what you wants on the line 28
