### ISSUE TITLE
Adding torrentleech as indexer just closes the modal and gives Gateway Time-out

### ISSUE THREAD

**Issue by null4bl3** [Jackett/Jackett#6004]
Jackett Version 0.11.687.0 in the Linux-Server.io docker image. 

clicking on the wrench icon to start to configure the torrentleech indexer closes the modal, and a little while later the console show an error:

504 (Gateway Time-out)

**Comment by garfield69** [comment]
works for me.
from a terminal shelled into your jackett docker container please post the output of 
`curl -vvv https://www.torrentleech.org/`
and 
`openssl s_client -connect www.torrentleech.org:443`

**Comment by null4bl3** [comment]
`curl -vvv https://www.torrentleech.org/
*   Trying 62.61.144.3...
* TCP_NODELAY set
* connect to 62.61.144.3 port 443 failed: Connection timed out
* Failed to connect to www.torrentleech.org port 443: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to www.torrentleech.org port 443: Connection timed out`



`curl -vvv https://www.torrentleech.org/
*   Trying 62.61.144.3...
* TCP_NODELAY set
* connect to 62.61.144.3 port 443 failed: Connection timed out
* Failed to connect to www.torrentleech.org port 443: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to www.torrentleech.org port 443: Connection timed out
root@9cc901fdc5b0:/# openssl s_client -connect www.torrentleech.org:443
140158247948736:error:0200206E:system library:connect:Connection timed out:../crypto/bio/b_sock2.c:110:
140158247948736:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:111:
connect:errno=110`

**Comment by garfield69** [comment]
well then, whatever the problem is, it has nothing to do with Jackett.
perhaps you are being blocked by your ISP?
if you use your browser on the same PC that you run the docker Jackett on, to access https://www.torrentleech.org/ do you get to the website?

**Comment by garfield69** [comment]
its definitely an ISP block.
www.torrentleech.org should resolve to 104.20.196.22 but your curl tried connecting to 62.61.144.3 which is owned by censur.danskkabeltv.dk in Denmark.
