### ISSUE TITLE
[hdolimpo] There is a new tracker in the Spanish scene

### ISSUE THREAD

**Issue by skttbv** [Jackett/Jackett#6005]
Hi recently a new tracker called hdolimpo has appeared with lots of movie premieres and it would be nice to add it to jackett.

The site name is https://hdolimpo.co/

Thanks a lot for your attention!

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by garfield69** [comment]
duplicate of #5142

**Comment by killer1595** [comment]
Can i get invite please ?

**Comment by garfield69** [comment]
I'm sorry but I don't have any.
Also, this is a support site for the Jackett application and not a forum for invites.
There are dedicated sites for such requests, this is not one of them. Looks elsewhere.

**Comment by killer1595** [comment]
ok thanx
i had account but when i try to login it says 403 error
any idea why ? and how tod download torrents

**Comment by garfield69** [comment]
>i had account but when i try to login it says 403 error any idea why ? 

https://github.com/Jackett/Jackett/pull/6828#issuecomment-570904094

**Comment by killer1595** [comment]
Actually i do not know what is this :/
so sad

**Comment by dorukhan84** [comment]
Can i get invite please ?

**Comment by garfield69** [comment]
@durukhan84 I'm sorry but I don't have any.
Also, this is a support site for the Jackett application and not a forum for invites.
There are dedicated sites for such requests, this is not one of them. Look elsewhere.

**Comment by garfield69** [comment]
@dorukhan84 I'm sorry but I don't have any.
Also, this is a support site for the Jackett application and not a forum for invites.
There are dedicated sites for such requests, this is not one of them. Look elsewhere.
