### ISSUE TITLE
[asgaard] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Mange** [Jackett/Jackett#6015]
> 1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.

I can log in, have no issues or warnings and I am in a good standing. It used to work before with no changes, so it's likely they changed their markup somehow.

> 2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.

I'm running 0.11.703.0, which is the latest LinuxServer.io version.

> 3. If it is still not working for you, then a **full enhanced log must be included**.

Log is attached below (with high entropy strings replaced with "REDACTED" in order to prevent leaks/hitlinking/identity disclosion). This might be a good hint, though:

```
System.Exception: Error while parsing field=date, selector=td:nth-child(7), value=4.62GB: DateTime parsing failed for "4.62GB": System.Exception: FromFuzzyTime parsing failed
```

If you need clean, unmodified logs, then I'd like a more secure channel to send them.

**Jackett version**:  0.11.703.0

-------------------------------

[jackett_log.txt](https://github.com/Jackett/Jackett/files/3633055/jackett_log.txt)

**Comment by garfield69** [comment]
update to pre-release 0.11.706

**Comment by Mange** [comment]
Thanks!
