### ISSUE TITLE
Asgrd.org fixed for users, but not for administrator account

### ISSUE THREAD

**Issue by Suiziide** [Jackett/Jackett#6019]
You just fixed the issue with asgrd that arose from changes in browse.php, but only for user accounts. It is still broken for administrator accounts.

I hope you can fix this to work again :)

logs attached
[jackett.txt](https://github.com/Jackett/Jackett/files/3635891/jackett.txt)

**Comment by garfield69** [comment]
Oh! completely forgot about that gotcha from #5754 
fixed with jackett 0.11.709
and this time I made a note in that indexer source code so I wont forget again ;-)
