### ISSUE TITLE
Docker config folder

### ISSUE THREAD

**Issue by mouzzampk2014** [Jackett/Jackett#6022]
Hi,
I am running this image ```docker create \
  --name=jackett \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e RUN_OPTS=run options here `#optional` \
  -p 9117:9117 \
  -v path to data:/config \
  -v path to blackhole:/downloads \
  --restart unless-stopped \
  linuxserver/jackett```

When jackett creates config folder it has `/config/jackett/Jackett/`. Is it possible to make it `/config/jackett/` inside of extra subfolder.

Thank you

![4](https://user-images.githubusercontent.com/44548525/65370834-f8bcd800-dc54-11e9-8ad4-b9264bfbca2d.JPG)

**Comment by xfouloux** [comment]
seems mor elike a question for linuxserver

**Comment by ngosang** [comment]
@mouzzampk2014 If you are still interested, open the issue here => https://github.com/linuxserver/docker-jackett
