### ISSUE TITLE
[Xthor] Add possibility to only chose VFF and not VFQ

### ISSUE THREAD

**Issue by ThomasClemenceau** [Jackett/Jackett#6025]
Hi!

I'm a user of Xthor tracker and see that something is missing on Jackett about this tracker.
The api of Xthor allow to show exclusively VFF torrents (Voix Françaises France/French voices from France) and not VFQ (Voix Françaises Canada/French voices from Canada) using the argument "accent" (values are: 1 for VFF, 2 for VFQ).

I think it can be a good thing to allow us to chose this parameter just like we can chose freeleech or not.

Thank you!

**Comment by garfield69** [comment]
@mrhydejc are you available to implement this?

**Comment by ThomasClemenceau** [comment]
I saw how to implement this in the c# but I just didn't find the file which add checkbox in the settings of the indexers. Thought it was a yml but I didn't find any xthor.yml

**Comment by garfield69** [comment]
the config you are looking for is src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataXthor.cs

**Comment by ThomasClemenceau** [comment]
Ok nice! I will try to do it myself. First time I look at the Jackett code so I'm not sure I will be able to do it

**Comment by ThomasClemenceau** [comment]
It's okay I did it! I will do my pull request. I don't close the issue before it is accepted, just in case

**Comment by garfield69** [comment]
included in jackett pre-release 0.11.714
