### ISSUE TITLE
[REQ] Invite To Tapochek.net

### ISSUE THREAD

**Issue by MellsFromHell** [Jackett/Jackett#6027]
I was just wondering if someone could invite me to the Russian website called:
https://tapochek.net/
I had seen someone else in March had asked and was invited, so I guess it's worth a shot asking.

Cheers!

**Comment by garfield69** [comment]
I was invited so I could build the jackett indexer for tapochek.
but this github support site for jackett is not a forum for invites so please look elsewhere.

**Comment by nightfun** [comment]
Hi Garfield, sorry to bother, but I saw you were invited to Tapochek. Would you be so kind to send me an invite. I am stuck looking for it, and really need this torrent to start working on ps4 scene

**Comment by garfield69** [comment]
@nightfun  Sorry, I cannot help you.
I was invited so I could build the jackett indexer for tapochek.
But I don't  have an invite to give out.
This github support site for jackett is not a forum for invites so please look elsewhere.
