### ISSUE TITLE
[nostalgic] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by nicr4wks** [Jackett/Jackett#6036]
**Jackett version**:  0.11.709.0

Not sure how long this has been going on for as I haven't tested my trackers from Jackett in a while.

[log.txt](https://github.com/Jackett/Jackett/files/3649809/log.txt)

-------------------------------

**Comment by garfield69** [comment]
logon to the nostalgic web site via your browser and go to the settings for your account.
click on the ** Display times as time since (date and time is displayed as tooltip)** radio button of the **Time style** setting, save your profile and logout.

**Comment by nicr4wks** [comment]
That's done the trick, thanks @garfield69
