### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on https://www.yggtorrent.ch/ using form selector 

### ISSUE THREAD

**Issue by Silastar** [Jackett/Jackett#6041]
Hello,

My main tracker is apparently not recognised in Jackett anymore (probably due to a change of hostname?)

Will it update automatically?

**Comment by garfield69** [comment]
normally yes.
but yggtorrent is a peculiar site and requires manual intervention when they change domains.
read #6039 for details.
