### ISSUE TITLE
[RevolutionTT] Results link to comments page instead of main page

### ISSUE THREAD

**Issue by whitesnakeftw** [Jackett/Jackett#6044]
Clicking on results from RTT brings to the torrent's comments page (where you can't see anything but comments) instead of the main torrent page. Basically there's an extra

> &page=0#startcomments

in the URL.

**Comment by TwilightZ0ne** [comment]
garfield69 they have an application process right on the login page. Simple apply and mention Jacket in the app and you are looking to help with integration I'll see you get sorted out.

**Comment by garfield69** [comment]
I've taken a look at the indexer and discovered its not a yaml indexer (my speciality) but a fairly complex C# indexer that is beyond my skills to patch.
I'll assign this ticket to the regular c# devs and invite any volunteers to submit a PR.

**Comment by garfield69** [comment]
try out jackett pre-release 0.12.947
