### ISSUE TITLE
[PassThePopcorn] Freeleech releases not flagges as such

### ISSUE THREAD

**Issue by varac** [Jackett/Jackett#6056]
When doing a query in PTP directly for a particular movie that has one/many `Freeleech` releases, the `Freeleech` tag shows up in the search results.
However, jackett shows all releases with the freeleech flag.

**Jackett version**:  0.11.723.0 (using docker image linuxserver/jackett)

**Comment by garfield69** [comment]
I don'
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.t have an account on PTP but if you provide an enhanced log I may be able to amend the indexer to recognise flreeleech correctly.

**Comment by garfield69** [comment]
on second thought, I've taken a look at the indexer and I see its not a yaml one (my speciality) but a fairly complex C# indexer that is beyond my skills to patch.
I'm assigning this to our regular c# devs and invite anyone to raise a PR.

**Comment by varac** [comment]
Ok, here's the redacted log (I only anoymised the jackett URL and the name of the movie I was searching): 
[log.txt](https://github.com/Jackett/Jackett/files/3685361/log.txt)

I see that `"FreeleechType":"Freeleech"` is an attribute for the one freeleech torrent, so that's correct. However, this information is not shown in the jackett UI (which it should), nor shown in the radarr UI (well that's a different story).

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.777
