### ISSUE TITLE
[yggtorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Sayroyten** [Jackett/Jackett#6063]
Same error for Yggtorrent and Torrent9 since few hours :(

Jackett Version 0.11.751.0

`System.Exception: Found no results while trying to browse this tracker at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222 at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128 at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync() at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync() at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context) at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync() at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context) at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29`

**Comment by Sayroyten** [comment]
Hi, this issue is a dupplicate of #6058 but the 6058 got close because of the lack of information

**Comment by garfield69** [comment]
works for me.
1. check that you are using the latest version of jackett 0.11.751
2. provide two enhanced log files, one for ygg the other for torrent9. 
don't try doing the test for both at once, the log file will not contain both results.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by Sayroyten** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/3667948/log.txt)
Here the full logs for Ygg and Torretn9 :)

**Comment by Miko2708** [comment]
hi
same problem for me, they change the URL address from yggtorrent.gg to yggtorrent.pe 
(sorry for my bad english)
I hope you could solve it 
thanks

**Comment by garfield69** [comment]
@Sayroyten 
### yggtorrent
you log shows that you are using `https://www.yggtorrent.pe/` for the search url. this is incorrect.
1. access your jackett dashboard and use the wrench icon to edit your yggtorrent indexer config.
2. set the **Site Link** to `https://www.yggtorrent.pe/` and 
3. set the **Search and download URL** to `www2.yggtorrent.pe`
4. Click **OKAY**
5. if you get an error, click **CLOSE** then edit again and click OKAY. it should save the second time.

### torrent9
you log shows your torrent9 indexer is currently trying to use `https://ww1.torrent9.sx/ ` which is not working.
edit your torrent9 indexer config and set the **Site Link** to `https://www.torrent9.is/`

let me know how you go.

**Comment by garfield69** [comment]
@Miko2708  follow the instructions I gave Sayroyten  and see if it applies to you.
if it does not work then provide an enhanced log file so I can take a look.

**Comment by Sayroyten** [comment]
@garfield69 wow it works! thx a lot :)

**Comment by Miko2708** [comment]
@garfield69  work very well now thanks a lot
