### ISSUE TITLE
Manual Download Endpoint for IRC Support

### ISSUE THREAD

**Issue by sparky3387** [Jackett/Jackett#6065]
I am trying to get Sonarr/NODE-RED to automatically download from an IRC channel using the code here: https://github.com/Jackett/Jackett/issues/251 ,  it works well for retrieving valid releases, but the issue is if the tracker is not officially supported by Sonarr, it will not automatically download and instead get redirected to the login page, I know Jackett supports a /dl/path url, but am having issues trying to get recreate the path encryption, is there an open api endpoint to this?

**Comment by ngosang** [comment]
@sparky3387 You can't recreate the Jackett download URL. You have to make a Torznab request in first place and use the download URLs from the response.
If you have more questions I will re-open.
