### ISSUE TITLE
Question: Jackett Frontend / Integration with selfhosted search engines ?

### ISSUE THREAD

**Issue by lukasmrtvy** [Jackett/Jackett#6071]
Is there any user frontend for jackett ? I would like to have something like former torrentz2 search box, but of course it will be integrated with Jackett.
I know I can search in Web UI, but its something like admin layer, I would like to have some frontend as user layer.
Thanks

**Comment by garfield69** [comment]
not sure I understand what you mean by user frontend.
but if you mean is there an alternative for searching with jackett indexers that does not use the browser jackett dashboard, then jackett provides the torznab api (which is what all the apps like sonarr, radarr, etc use), to get jackett to search a supported site and get results.
a typical call would look something like this:
`http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab?t=caps&apikey=yourApiKey`
or
`http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab?t=tvsearch&q=blacklist&season=6&ep=18&apikey=yourApiKey`
information on the torznab standard can be found here https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer
that is the only frontend I am aware of.

**Comment by ngosang** [comment]
@lukasmrtvy I don't know any. Jackett has a nice API so anyone with time and knowledge can build a more user friendly UI even a mobile app.
