### ISSUE TITLE
Access to the path 'CommandLine.dll' is denied.

### ISSUE THREAD

**Issue by shaunveto** [Jackett/Jackett#6073]
I ma running Jackett version 0.11.687.0.  For the past couple weeks I've been noticing Jackett crashing randomly and I would need to relaunch the application to kick off the service again.  I finally started looking around the Web UI and found the logs link and discovered what was happening.  It looks as if the app is crashing while it's attempting to delete files as part of a cleanup routine.  The full error message and all of the detail associated with it is below.  The account I'm under is an admin account with full rights. It is the same error every time on the same dll.

```
Oct 2, 2019 09:05:35 PM | Error | System.UnauthorizedAccessException: Access to the path 'CommandLine.dll' is denied.
    at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
    at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
    at System.IO.DirectoryInfo.Delete(Boolean recursive)
    at Jackett.Common.Services.UpdateService.CleanupTempDir()
-- | -- | --
Oct 2, 2019 09:05:35 PM | Error | Error while deleting temp files from C:\Users\me\AppData\Local\Temp\JackettUpdate-v0.11.760-637056049154336564
```

**Comment by garfield69** [comment]
I run win10home and I have never seen this error
what windows are you on?
if you check the Jackett service logon properties, is it set to *logon as local system account*?
![image](https://user-images.githubusercontent.com/6933240/66072892-72888600-e5b2-11e9-990a-30e69ec0ae8e.png)

if you access `C:\Users\me\AppData\Local\Temp\JackettUpdate-v0.11.760-637056049154336564` does the file `CommandLine.dll` exist, and can you delete it manually?

**Comment by shaunveto** [comment]
I'm running Win 10 Pro.

I don't see Jackett in the Services application.  When I look at the
processes running under Task Manager they're all running under the account
that I'm currently logged in as.

When I try to delete the CommandLine.dll file manually I'm getting an error
saying the action cannot be completed because the file is open in
JackettUpdater.

[image: image.png]

--
Shaun Vetovich

**Comment by garfield69** [comment]
Ah. so that is the problem. a lockout because of an active task.
check your TaskManager and see if you can spot the JackettUpdater, has that been suspended?
try ending that task, can it be killed?
when was the last time you rebooted windows?

**Comment by shaunveto** [comment]
When I was sending my previous email I did see the JackettUpdater.exe
process in TaskManager.  However, now that I'm looking again to respond to
this email the JackettUpdater.exe process is no longer running.  Also, I
just tried deleting the CommandLine.dll file manually and I was able to
delete it without an issue.   It looks like it may just be a timing thing
between the JackettUpdater and the CleanupTempDir process running at the
same time.

I just rebooted my PC last night.

--
Shaun Vetovich

**Comment by garfield69** [comment]
I guess that there is always a possibility that if you are launching Jackett manually via the desktop or via the startup folder, that the JackettConsole program and the JackettUpdater could clash.
When both programs are active at the same time, then there is a chance that the JackettUpdater will fail when it tries to replace/update the Jackett programs because they are locked by JackettConsole, and the JackettConsole could fail when it tried to do a cleanup of the temporary updater installation package folder.

Setting Jackett up to use the service reduces the likelihood of a clash as the update process and Jackett service restart are controlled without user interaction.

**Comment by shaunveto** [comment]
That all makes perfect sense to me. How would I go about setting Jackett up
as a service? Would it just require a reinstall or is there a setting for
it somewhere?

--

**Comment by garfield69** [comment]
yes, simply download the latest *Jackett.Installer.Windows.exe*
 release from https://github.com/Jackett/Jackett/releases
make sure you have exited JAckett if it currently running, and run the installer  and choose the *Service* installation option when prompted.

Also, if you have setup a Jackett shortcut in your windows *Startup* folder, remember to remove it as it is no longer needed if you are switching to a service.

**Comment by shaunveto** [comment]
Excellent.  Thank you very much for your help.  I was able to get it
installed as a service so I'm hopeful I won't run into this issue again.  I
have also validated that the Jackett service is now present in the Services
app and it is launching under the SYSTEM account.  I appreciate your quick
and friendly help!

--
Shaun Vetovich
