### ISSUE TITLE
[Request] hdfun (hdzone)

### ISSUE THREAD

**Issue by killerqueen619** [Jackett/Jackett#6078]
web : https://hdzone.me https://hdfun.me

its open signup right now

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.778
the site has a large amount of redirects during login which the cardigann processor cannot follow.
so I have had to resort to using cookie.
note: i have not tested downloading.

**Comment by ilike2burnthing** [comment]
https://hdzone.me/ - 404 Not Found

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://hdzone.me/ - Error 522 - Connection timed out

**Comment by garfield69** [comment]
https://hdzone.me/ returns ERR_CONNECTION_CLOSED

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://hdfun.me/ redirects to https://hdfun.me/lander Domain expired parking page

**Comment by ilike2burnthing** [comment]
https://hdzone.me/ works fine for me, but https://hdfun.me/ doesn't work at all (no captcha no search). Guessing it's dead?

**Comment by garfield69** [comment]
hdfun.me domain is expired, and using that domain with the indexer does not work full stop.
hdzone.me with the indexer gives captcha login ok, and returns search results. but if I click on a search result row name link gets redirected to hdfun.me/lander and download also fails.
on my browser hdzone.me gets redirected to hdfun.me/lander
so are you saying that for you, you can get full function from the indexer with hdzone.me ?
and your browser works too with hdzone?

**Comment by ilike2burnthing** [comment]
Yep, https://hdzone.me/ is fully functional in Jackett and browser. In private window, https://hdzone.me/ redirects to https://hdfun.me/lander, but https://hdzone.me/login.php loads the login page.

**Comment by garfield69** [comment]
Oh. OK. well I can get the login page on the borwser, but after filling the creds nad challenge i get routed to the lander page again ;-)
I'll drop the broken domain and leave this open as restricted in case anyone else has the same issue as I do.

**Comment by garfield69** [comment]
Hah, now that the browser has a cookie I can access hdzone freely.

**Comment by garfield69** [comment]
https://hdzone.me/login.php 404 Not Found nginx

**Comment by garfield69** [comment]
v0.22.372
