### ISSUE TITLE
[nordicbits] Login failed: Error during attempt ! (Config) | NordicBits V2

### ISSUE THREAD

**Issue by tordenflesk** [Jackett/Jackett#6097]
NordicBits V2 support planned?

**Comment by garfield69** [comment]
ping @hallengreenn are you available to adjust the nordicbits indexer to cope with v2 changes?

**Comment by InfAmoUsaeble** [comment]
There seem to be a new API to use, which is called via the following URL:

https://v2.nordicb.org/api/login.php?key=XXX&pkey=XXX

There is no xml output or anything, just looks like it logs you in to the site as normal though ..

**Comment by Johan1976** [comment]
For me it has started to work again!?

**Comment by tordenflesk** [comment]
> 
> 
> For me it has started to work again!?

Yeah, they've had some "interesting" internal  tracker politics involving a previous programmer, causing them to revert to "v1" of the site.
