### ISSUE TITLE
Beyond-HD Exception in GetConfigForm

### ISSUE THREAD

**Issue by 1josh13** [Jackett/Jackett#611]
Still having this error on the beyond-HD tracker. Running 0.7.504 release of jackett on a windows server 2012 R2 box. 

Let me know what else I can provide to assist. 
![error1](https://cloud.githubusercontent.com/assets/16166663/19875991/9b72c1e0-9f9f-11e6-9079-7e0dc9283016.PNG)

**Comment by kaso17** [comment]
Please start Jackett with the -t option and post the full log

**Comment by 1josh13** [comment]
kaso17,

Please see the attached log as requested. Error occurs on Line 630. This occurred from a fresh start with a -t option enabled, no further action was taken after the error occurred. 

[Jackett-Log-20161101.txt](https://github.com/Jackett/Jackett/files/564944/Jackett-Log-20161101.txt)

**Comment by kaso17** [comment]
Looks like the CloudFlare bug which should be fixed in the latest release, please update and try again.

**Comment by 1josh13** [comment]
Can confirm the most recent update resolved the problem, I've now added B-HD successfully!
