### ISSUE TITLE
Ubuntu Installation

### ISSUE THREAD

**Issue by distrax** [Jackett/Jackett#6112]
I've been a user of Jackett for a couple years now. I've had to fix it a few times and very often recently. It would just stop running. I'd have to change the systemd configuration file. I'm running it on Ubuntu Linux 18.04 server. Now it won't work at all. I've removed it from my system and reinstalled it and it won't run.. It just says "activating" in the systemctl status.  What information is required from me for you to help out? I know this isn't enough.

**Comment by garfield69** [comment]
did you follow https://github.com/Jackett/Jackett#install-on-linux-amdx64 ?

**Comment by distrax** [comment]
I did. I'm trying to use the docker container next time.

**Comment by garfield69** [comment]
are you able to launch jackett manually with `./jackett` to show that the issue is just with the systemdctl?

**Comment by acollien** [comment]
> are you able to launch jackett manually with `./jackett` to show that the issue is just with the systemdctl?

I am having same issues. 

.`/jackett` returns "No such file or directory" for me.

`sudo servive jackett start` appears to run without error in terminal, but still doesn't actually start the service.

**Comment by distrax** [comment]
Apologies! I just ended up going the docker route. I appreciate the intended help. This is a great project! I can close the issue unless acollien needs it open

**Comment by acollien** [comment]
> Apologies! I just ended up going the docker route. I appreciate the intended help. This is a great project! I can close the issue unless acollien needs it open

can close thanks.
