### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://www2.yggtorrent.pe/ using form selector 

### ISSUE THREAD

**Issue by Myhrdin** [Jackett/Jackett#6115]
Hello, first thank you for your great work.

Since several days, Jackett isn't able to acces my Indexer, yggtorrent. The site is working well and I can log in on it so that's why i don't understand what is appening, never had this issue before. Jackett tell me that he can"t found log in dorm in the website, any ideas why ?

Thank you for your time

(I use jackett from docker, I have the Jackett Version 0.11.760.0 and other indexers are working)

**Comment by Hotdogszbg** [comment]
@jackettbot[bot]

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6086#issuecomment-538865977
