### ISSUE TITLE
[rarbg] Access to the path

### ISSUE THREAD

**Issue by MohamedDiouane** [Jackett/Jackett#6116]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------
 An error occured while configuring this indexer
Access to the path "/home/mohamed/.config/Jackett/Indexers/rarbg.json.0491c77a838c4a2c98263d90fa3c7b66.tmp" is denied.

Jackett Version 0.11.786.0

**Comment by garfield69** [comment]
works for me on my ubuntu18 with 0.11.786

what platform are you on, which jackett package did you install?
was it working before or is this a new install?
does it always fail or just the one time?

**Comment by MohamedDiouane** [comment]
i am using ubuntu server 18 with Jackett Version 0.11.786.0, and that happens just with some Trackers in this case with rarbg.

**Comment by garfield69** [comment]
that is weird. 
are you saying that you have been able to add other indexers without problems?

if you open a terminal and cd to the `~/.config/Jackett/Indexers` folder, is `rarbg.json.0491c77a838c4a2c98263d90fa3c7b66.tmp` still there or is it gone?
I am not 100% familiar with linux platforms, but access denied would suggest that jackett tried to access a file which is no longer there.
if the file is there but jackett is not authorised, I would have expected a permissions denied error.
but the fact is that I don't know why a .tmp file was created in the first place.
normally the Indexers folder is full of .json (the active indexer profile file) and .json.bak (the previous profile now a backup).

**Comment by MohamedDiouane** [comment]
There is no Jackett folder in  /home/myusername/.config/) !!

**Comment by garfield69** [comment]
really?
I believe that jacket can not operate without one.
 very confusing and beyond my skill to diagnose. Sorry.
assigning to the resident c# dev for help.

**Comment by MohamedDiouane** [comment]
sorry sorry.
I apologize I was login to the wrong VM, actually, the is Jackett/Indexers folder, inside of it 
![Screenshot from 2019-10-08 22-30-28](https://user-images.githubusercontent.com/24755569/66434975-a7199900-ea1b-11e9-9cf6-e1ffa5199531.png)
the is no rarbg.json

**Comment by garfield69** [comment]
ok. 
so you were able to add 1337x and limetorrents but not rarbg.
have you tried more than once to add the indexer?
lets see if the enhanced log can shed more light.

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. try adding rarbg.
4. find the *log.txt* file `~/.config/Jackett/log.txt`
5. drag-drop it here for us to take a look at.

Thanks.

**Comment by MohamedDiouane** [comment]
I tried but always the same error 
here is the log.txt
[log.txt](https://github.com/Jackett/Jackett/files/3704873/log.txt)

**Comment by garfield69** [comment]
yeah, nah. the log you provided does not contain any enhanced logging.
did you enable the switch as described in https://github.com/Jackett/Jackett/issues/6116#issuecomment-539715732 ?

**Comment by MohamedDiouane** [comment]
you are right the enhanced logging is disabled, when i check the enhanced logging and save the web page refresh but the enhanced logging still disable!

**Comment by garfield69** [comment]
i am so confused at the way your jackett is behaving, from the information you are providing.

several things I noted from the log you provided earlier:
1. it appears that you are on 0.11.655 and not 0.11.786 as you stated earlier. don't know why.
2. it appears you are using jacket with mono 6. 

you may benefit from switching to the .net core version.

so I suggest the following: 
if you are running the mono jacket as a service the stop it.
`systemctl stop jackett.service`
then delete your current mono jackett (from /opt/jackett)

and install the latest .net version by following https://github.com/Jackett/Jackett#install-on-linux-amdx64

and see if this improves matters for you.

**Comment by MohamedDiouane** [comment]
the web UI showed me 0.11.786, 
I uninstall jackett and reinstall it using docker and it's now working 
thanks a lot, garfield69!
