### ISSUE TITLE
TorrentLeech commit  from 2 days ago hasn't fixed my issue

### ISSUE THREAD

**Issue by Speaktomenow** [Jackett/Jackett#612]
This issue was closed, but I am still getting the same issue, can't search TL. Downloaded, reinstalled latest commit, checked my u/p which hasn't changed, but the TL error remains.

Sorry if it's just me, but I don't think this has been fixed.

**Comment by kaso17** [comment]
Please provide a FULL log (start JackettConsole with -t option)

**Comment by snupple** [comment]
Just FYI  0.7.504.0 works on TorrentLeech fine for me

**Comment by armani316** [comment]
@Speaktomenow Is this still an issue or can it be closed? TorrentLeech has been running fine for a while.

**Comment by Speaktomenow** [comment]
Yes please, running great now even on the new version of TL
