### ISSUE TITLE
[tvstore] Exception (tvstore): Input string was not in a correct format.: Input string was not in a correct format. (Test)

### ISSUE THREAD

**Issue by SugarDroid** [Jackett/Jackett#6120]
Using docker image by linuxserver/jackett:latest.
Jackett Version 0.11.787.0
[log.txt](https://github.com/Jackett/Jackett/files/3703946/log.txt)

**Comment by garfield69** [comment]
@morpheus133 are you able to use the tvstore jackett indexer? 
as the last chap to make changes to this indexer, are you available to take a look at this ticket?

**Comment by garfield69** [comment]
@SugarDroid  works for me.
please access tvstore with your web browser and confirm that your username and password are correct.
also confirm that you have a good ratio and no outstanding alerts on your account (unread emails, unresolved notices etc) that might prevent you accessing the torrent browse page.
then if all is good, edit your tvstore and reenter your username and password and test.

**Comment by morpheus133** [comment]
Hi!
It is working for me also
@SugarDroid  If the problem is still exist can you send me the content of this url(after logged in to the site):
https://tvstore.me/torrent/br_process.php?gyors=&p=1&now=1570558120

**Comment by SugarDroid** [comment]
> @SugarDroid works for me.
> please access tvstore with your web browser and confirm that your username and password are correct.
> also confirm that you have a good ratio and no outstanding alerts on your account (unread emails, unresolved notices etc) that might prevent you accessing the torrent browse page.
> then if all is good, edit your jacket tvstore indexer and reenter your username and password and test.
Since everything worked fine in browser, i edited the indexer as you mentioned. Adding the same name and password and save it did the trick. Since then also updated to latest image again and still works. Guess something happened with the indexer's saved setting.
