### ISSUE TITLE
[3evils] I have upgraded site.

### ISSUE THREAD

**Issue by 3evils** [Jackett/Jackett#6127]
I am the owner of 3evils. I did not know my site was listed in this. I'm ok with it. I have recently upgraded 3evils to a custom u-232-v6. The cats listed in yaml are all wrong.

ID (3) | TV/x264 
ID (4) | TV/x265
ID (6) | TV/Packs 
ID (8) | TV/Xvid 
ID (11) | Movies/Encodes 2160p 
ID (12) | Movies/Remux 2160p   
ID (13) | Movies/Remux 1080p
ID (14) | Movies/Packs 
ID (16) | Movies/x264 
ID (17) | Movies/X265
ID (32) | Music/Packs  
ID (33) | Music/Audio 
ID (42) | Appz/Android 
ID (43) | Appz/Windows  
ID (65) | Books | Books

**Comment by garfield69** [comment]
thank you for the heads up. 
I've registered anew but have run into a few problems.
the confirmation link in the validation email is not valid, the secret code is missing.
I tried login in but kept getting wrong-username-or-password.
I'll try again tomorrow.

**Comment by 3evils** [comment]
Weird…. Just send me the user deets ya want, and I’ll create the account for you. Did you happen to delete old cookies?

**Comment by garfield69** [comment]
yes I deleted the cookies 
also tried the password recover, which seemed to find my account because it then used my registered challenge to validate me and accepted my new password. but the login still did not accept me.

anyway, I registered as garfield1969 with email garfieldsixtynine@gmail.com

**Comment by 3evils** [comment]
I found ur account, did pass reset and confirmed you.
bb7176d8fb7fb68

**Comment by 3evils** [comment]
I need to finish the reset function sorry. I upgraded the source to use different password encryption. I totally forgot the reset and recover functions. My bad

**Comment by garfield69** [comment]
thank you for sorting out my 3evils account.
the jackett indexer has been updated to handle the site's upgrade.
