### ISSUE TITLE
I receive an error stating "An existing connection was forcibly closed by the remote host" for every one of my trackers on a daily basis

### ISSUE THREAD

**Issue by djmehs17** [Jackett/Jackett#6128]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------
There's actually multiple issues that have been opened relating to this particular error when I do a search, but for some reason, none of the users who opened them provided any description of the issue, so they were all closed due to lack of information.

Anyway, I've been fighting with this issue for a few months now and originally thought the issue was with Radarr or Sonarr, as that's where I originally saw an error about none of my indexers being connectable. When I'd click "Test" they would connect with no issues, but then at some point over the next 24 hours they would disconnect again. Eventually I tracked the issue down to something happening on the Jackett side as the particular error shows up in the Jackett logs. The snippet of interest is:

**Error Jackett.Common.IndexerException: Exception (1337x): An existing connection was forcibly closed by the remote host ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host**

All around the same time, it repeats this error message, replacing 1337x with each of my various trackers. Once I test the trackers, they are fine. There just seems to be some issue causing them to all fail again by the same time the next day.

I've done a complete Uninstall/Reinstall of Jackett including the deletion of the Jackett Program Data folder. I'm also using the latest version of Jackett (0.11.787.0) and running it on Windows 10 as a background service. 

I've attached the "log.txt" file despite it not seeming to contain the error in question, as well as the other "log.txt.20191009.00000#.txt" files I found in the same location, which do contain the error

Thanks in advance for any help you can provide.
[log.txt.20191009.00001.txt](https://github.com/Jackett/Jackett/files/3706623/log.txt.20191009.00001.txt)
[log.txt.20191009.00002.txt](https://github.com/Jackett/Jackett/files/3706624/log.txt.20191009.00002.txt)
[log.txt](https://github.com/Jackett/Jackett/files/3706625/log.txt)
[log.txt.20191009.00000.txt](https://github.com/Jackett/Jackett/files/3706626/log.txt.20191009.00000.txt)

**Comment by garfield69** [comment]
from the logs it appears that jackett is a victim rather than the perpetrator of the issue.
could it be that are you using a vpn or a proxy with jackett to access the web ?
or have a firewall or anti-malware setting that blocks your wan on a scheduled timer?
something is breaking your wan or preventing jackett from accessing your wan after a time-limit has expired...the kind of thing that might happen with the use of vpn or proxies or if a firewall on a schedule is set to block all traffic for a period of time.
other than that I have no idea what might be going on.

**Comment by djmehs17** [comment]
Ahhh I’ll bet I know what it is. I’ve been having issues with connectability/seeding with a Private tracker I use as well. Same behavior, when I initiate a test or something, everything works great, then at some point it just stops working.

I don’t use a VPN but have an accountability software called Covenant Eyes on my computer. Google it if you’re curious what that is, but from a technical standpoint, I believe it is understand it to be a VPN or Tunnel that can monitor all the traffic outgoing from my machine for stuff my kids shouldn’t be accessing.

I’m almost 100% certain that’s the cause. Also explains why nobody else seems to be having the same issue, because nobody has that software. You definitely put me on the right track. Thanks a ton! You can close this issue!
