### ISSUE TITLE
[demonoid] Exception (demonoid): Index was out of range. Must be non-negative and less than the size of the collection.Parameter name: index: Parse error (Test)

### ISSUE THREAD

**Issue by Protektor-Desura** [Jackett/Jackett#6136]
Jackett Version 0.11.793.0

**Comment by garfield69** [comment]
demonoid have introduced "sponsored links" embedded within the results table and this is throwing off the cardigann processors' count of torrents.
standby for fix announcement.

**Comment by garfield69** [comment]
fixed with jackett 0.11.799
