### ISSUE TITLE
Jackett service crashes on launch

### ISSUE THREAD

**Issue by AdamCh132** [Jackett/Jackett#6148]
I just saw on sonarr that the trackers were down, and saw that the Jackett service wasn't running. It crashes as soon as I launch it, and I can't access the web ui. I tried uninstalling and reinstalling with the latest version, but the problem persists.
[log.txt](https://github.com/Jackett/Jackett/files/3720345/log.txt)

**Comment by garfield69** [comment]
hmmmm. the key message is `System.Net.Sockets.SocketException: No such host is known`

are you using a proxy or some other non-default setting in your startup?
do you use http://127.0.0.1:9117 to access the dashboard or something else?
which OS are you running and which jackett package did you install?
can you start jackett manually by cd to the jackett folder and using `./jackett` (linux, macos) `JackettConsole.exe` (windows)?

**Comment by saxicek** [comment]
I may face the same issue. I am using Jackett.Binaries.LinuxARM32.tar.gz and while version v0.11.799 works fine in version v0.11.802 I get exception:
```
$ ./jackett
10-13 06:48:33 Info Starting Jackett v0.11.802.0 
10-13 06:48:35 Error System.BadImageFormatException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The module was expected to contain an assembly manifest.
File name: 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngineServices(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngine(IMvcCoreBuilder builder)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services, Action`1 setupAction)
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services) in /home/appveyor/projects/jackett/src/Jackett.Server/Startup.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)
```

**Comment by AdamCh132** [comment]
Yes, I have to use a proxy as most domains are blocked by my ISP. I'm using a socks5 proxy from nordvpn. I am using http://127.0.0.1:9117/UI/Dashboard to access the dashboard. I am running windows 10, with the v0.11.802 release from yesterday. Starting using JackettConsole.exe still leads to it crashing.

**Comment by garfield69** [comment]
yeah, nah. The video is no use to me I cant read any of the text.
look in the C:\ProgramData\Jackett folder and drag drop the log.txt and updater.txt files here for us to take a look at.

**Comment by AdamCh132** [comment]
Ah right maybe it looks ok on mine because its 1440p.
[log.txt](https://github.com/Jackett/Jackett/files/3722114/log.txt)
[updater.txt](https://github.com/Jackett/Jackett/files/3722115/updater.txt)

**Comment by garfield69** [comment]
ok, need to see enhanced logs for more info.
please start the jackettconsole from the cli again, but this time add the -t -l command line options
then drag/drop the log.txt again.
thanks.

**Comment by AdamCh132** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/3722157/log.txt)

**Comment by garfield69** [comment]
darn. crashes really early. nothing useful in the log.
lets try specifying a client.
please try jackettconsole --useclient httpclient2

**Comment by AdamCh132** [comment]
Sorry will have to elaborate a bit for me, where do I need to enter that, and what do you expect me to see/post?

**Comment by garfield69** [comment]
oh, sorry.
from the cli start jackettconsole with the command line option -t -l --useclient httpclient2
and see it jacket starts or crashes again.
if it crashes drag/drop the log.txt again.
thanks.

**Comment by AdamCh132** [comment]
Crashed again.
[log.txt](https://github.com/Jackett/Jackett/files/3722172/log.txt)

**Comment by garfield69** [comment]
bugger.
lets take a look at your server.config. (its in C:\ProgramData\Jackett).
mine looks like this: (I've redacted for security some stuff)
```json
{
  "Port": 9117,
  "AllowExternal": false,
  "APIKey": "r***redacted***5",
  "AdminPassword": null,
  "InstanceId": "i***redacted***q",
  "BlackholeDir": "",
  "UpdateDisabled": false,
  "UpdatePrerelease": true,
  "BasePathOverride": "",
  "OmdbApiKey": "",
  "OmdbApiUrl": "",
  "ProxyUrl": "",
  "ProxyType": 0,
  "ProxyPort": null,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true
}
```
what does yours look like?

**Comment by AdamCh132** [comment]
I just took out my email address and password.
[ServerConfig.txt](https://github.com/Jackett/Jackett/files/3722185/ServerConfig.txt)

**Comment by garfield69** [comment]
ok so lets try resetting the proxy settings and see if we can get jackett running again.
so set all the proxy ones to my default and start jackettconsole without any additional cli parms and see what happens.

**Comment by AdamCh132** [comment]
Ok so removing the proxy settings, Jackett seems to be able to launch and stay open now. I'm just going to try entering some proxy settings to see if I can encounter the crashing again.
