### ISSUE TITLE
[yggtorrent] Login failed: Selector

### ISSUE THREAD

**Issue by DiviDus** [Jackett/Jackett#6149]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match

**Comment by garfield69** [comment]
first check https://github.com/Jackett/Jackett/issues/6086#issuecomment-538865977

normally, if your login is successful, you would get the logouf link on the page right next your your username.
So if you are still seeing the `Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match` error, then this indicates that something is preventing you from completing the login to ygg.
it probably means that there is something wrong with your ygg account.
so access a browser and login to yggtorrent at https://www3.yggtorrent.pe/ and check that your account ratio is good, that you have not been suspended, and that you do not have any outstanding alerts, emails, or whatever, that could prevent you accessing the ygg torrent browser when logged in.

**Comment by OrpheeGT** [comment]
Hello,

I'm having the same issue, I can login fine online, my ratio is at 4.

website : https://www3.yggtorrent.pe/ 
search and download URL : www3.yggtorrent.pe

**Comment by it31375** [comment]
Hi there. Same problem here. Someone have an issue ?
cheers.

**Comment by garfield69** [comment]
@it31375  have you followed https://github.com/Jackett/Jackett/issues/6086#issuecomment-538865977 ?
everyone so far has it working again, there are no outstanding open ygg tickets apart from this one.
@DiviDus have you sorted this out for yourself yet?

**Comment by antoineguilbert** [comment]
Thanks a lot. Change the download URL by www2.yggtorrent.pe works !

**Comment by piitaya** [comment]
Does not work with www2 URL :'(
