### ISSUE TITLE
[amigosshare] The operation was canceled.: Unable to read data from the transport connection: Operation canceled. (Config)

### ISSUE THREAD

**Issue by TheOzzyman** [Jackett/Jackett#6153]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page)  Jackett Version 0.11.802.0  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

Amigos-Share tracker don't working anymore.

**Comment by garfield69** [comment]
works for me.
can you access https://amigos-share.club/account-login.php?returnto=%2F from a browser running on the same machine has jackett?

**Comment by TheOzzyman** [comment]
Yes, I can !

Is not just me experiencing the same problem.
I have other friends using the tracker and in one time, works, in another
time, doesn'work.
Have too many bugs.

**Comment by garfield69** [comment]
be that as it may, the usual reason for a transport timeout are issues with certificates, or redirections by ISP blockers.
which is why I asked you to check with a browser, to eliminate the SIP blocking or DNS redirection issues.

on what platform are you running jackett, and which jackett package (amdx64, arm64, arm32, mono, macos, windows, docker, something else),  are you using?

**Comment by TheOzzyman** [comment]
Docker

**Comment by garfield69** [comment]
have a read of #5067 and see if anything in that ticket helps you out.
I'm not a c# dev and I don't user docker so I am not going to be much more help to you going forward. sorry.

**Comment by ngosang** [comment]
@TheOzzyman Is this fixed?

**Comment by TheOzzyman** [comment]
yes
