### ISSUE TITLE
[yts] An error occurred while sending the request: Error: SecureChannelFailure (Unable to read data from the transport connection: Connection reset by peer.) (Config)

### ISSUE THREAD

**Issue by ToneStrife** [Jackett/Jackett#6154]
Hi,

When trying to add YTS I get the error on the topic.
I'm running Jackett successfully with other indexers is YTS the one giving the error. Am I missing something?

Jackett Version 0.11.802.0
(if you installed using Jackett.Binaries.Mono.tar.gz) Mono 5.18

-------------------------------

> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: SecureChannelFailure (Unable to read data from the transport connection: Connection reset by peer.) ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
>   at System.Net.Sockets.Socket.EndReceive (System.IAsyncResult asyncResult) [0x00012] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>   at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x00057] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>    --- End of inner exception stack trace ---
>   at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x0009b] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>   at System.IO.Stream+<>c.<BeginEndReadAsync>b__43_1 (System.IO.Stream stream, System.IAsyncResult asyncResult) [0x00000] in <30c1a991558c4064acefa7cee0fc6779>:0 
>   at System.Threading.Tasks.TaskFactory`1+FromAsyncTrimPromise`1[TResult,TInstance].Complete (TInstance thisRef, System.Func`3[T1,T2,TResult] endMethod, System.IAsyncResult asyncResult, System.Boolean requiresSynchronization) [0x00000] in <30c1a991558c4064acefa7cee0fc6779>:0 
> --- End of stack trace from previous location where exception was thrown ---
> 
>   at Mono.Net.Security.MobileAuthenticatedStream.InnerRead (System.Boolean sync, System.Int32 requestedSize, System.Threading.CancellationToken cancellationToken) [0x00104] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>   at Mono.Net.Security.AsyncProtocolRequest.InnerRead (System.Threading.CancellationToken cancellationToken) [0x000ac] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>   at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x00093] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>   at Mono.Net.Security.AsyncProtocolRequest.StartOperation (System.Threading.CancellationToken cancellationToken) [0x0008b] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>   at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x00252] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>   at Mono.Net.Security.MonoTlsStream.CreateStream (System.Net.WebConnectionTunnel tunnel, System.Threading.CancellationToken cancellationToken) [0x00126] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>   at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x001ba] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>    --- End of inner exception stack trace ---
>   at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x0021a] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>   at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x00141] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>   at System.Net.WebOperation.Run () [0x0009a] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>   at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x00094] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>   at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>   at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in <63552ca6ec3f4cb28de3f8c0aa59b164>:0 
>   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <30c1a991558c4064acefa7cee0fc6779>:0 
> --- End of stack trace from previous location where exception was thrown ---
> 
>   at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x0041d] in <d79bb9faee264b669b8825270136bfaa>:0 
>    --- End of inner exception stack trace ---
>   at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00478] in <d79bb9faee264b669b8825270136bfaa>:0 
>   at CloudflareSolverRe.ClearanceHandler.SendRequestAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00090] in <8334974e827e4b4c8eeec8dbf59c24e0>:0 
>   at CloudflareSolverRe.ClearanceHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000a4] in <8334974e827e4b4c8eeec8dbf59c24e0>:0 
>   at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x000ca] in <d79bb9faee264b669b8825270136bfaa>:0 
>   at Jackett.Common.Utils.Clients.HttpWebClient.Run (Jackett.Common.Utils.Clients.WebRequest webRequest) [0x0048c] in <0eb19fb3447348ff8d48c18d2231ee56>:0 
>   at Jackett.Common.Utils.Clients.WebClient.GetString (Jackett.Common.Utils.Clients.WebRequest request) [0x0010b] in <0eb19fb3447348ff8d48c18d2231ee56>:0 
>   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies (System.String url, System.String cookieOverride, System.String referer, System.Collections.Generic.Dictionary`2[TKey,TValue] headers) [0x000cb] in <0eb19fb3447348ff8d48c18d2231ee56>:0 
>   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry (System.String url, System.String cookieOverride, System.String referer, System.Collections.Generic.Dictionary`2[TKey,TValue] headers) [0x00160] in <0eb19fb3447348ff8d48c18d2231ee56>:0 
>   at Jackett.Common.Indexers.Yts.PerformQuery (Jackett.Common.Models.TorznabQuery query, System.Int32 attempts) [0x0011a] in <0eb19fb3447348ff8d48c18d2231ee56>:0 
>   at Jackett.Common.Indexers.Yts.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x00069] in <0eb19fb3447348ff8d48c18d2231ee56>:0 
>   at Jackett.Common.Indexers.Yts.ApplyConfiguration (Newtonsoft.Json.Linq.JToken configJson) [0x00086] in <0eb19fb3447348ff8d48c18d2231ee56>:0 
>   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig (Jackett.Common.Models.DTO.ConfigItem[] config) [0x0012d] in <fddd640fb3ca435bb19b443050de384f>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 
>   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 
>   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 
>   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <fddd640fb3ca435bb19b443050de384f>:0

**Comment by garfield69** [comment]
works for me.
can you access YTS at https://yts.lt/ from a browser on the same machine that is running jackett ?

its probably a clash with the YTS certificate and mono.

is there any change you can ditch the mono version of jackett and upgrade to the .net core version?
pick the installation package that best suits your platform
https://github.com/Jackett/Jackett#install-on-linux-amdx64
https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above
https://github.com/Jackett/Jackett#installation-on-macos

**Comment by ToneStrife** [comment]
Yes,
I can access YTS without a problem. I have a synology Ds215 and I used the package that I found in the Sonarr github.
I don't know how to install Jackett or which version I should use

**Comment by garfield69** [comment]
oh. well if you are using syno then you are stuck with mono, according to #4858 :-(
I don't know how to help you further. assigning to a c# dev.
it possible the next update to mono via the next syno package may resolve this issue with yts for you.

**Comment by ngosang** [comment]
@ToneStrife is this fixed? It's working fine here. Note: I don't have a Synology NAS to test.
