### ISSUE TITLE
[NoName Club] Why is it semi-private?

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#6155]
Why is [NoName Club](https://nnmclub.to/), a Russian tracker, considered semi-private by Jacket? It's possible to use search functionality without using an account, and you could get magnet links as well. Shouldn't it be called 'public' in this case?

**Comment by garfield69** [comment]
probably because at the time the indexer was created nnmclub did not provide a download-link unless you were registered, and no one has thought to check it since.
I've checked and updated the indexer to reflect the current site status and categories.
