### ISSUE TITLE
REQUEST: corsaro.red

### ISSUE THREAD

**Issue by 19Thor92** [Jackett/Jackett#6156]
REQUEST
After the ufficial end of life of the most used italian torrent site TNT Village, the site: https://corsaro.red seems to have included the seeds and link of TNT Village. Is it possible to add it to the indexers?

-------------------------------

**Comment by garfield69** [comment]
was added on the 8th of September beginning with jackett 0.11.675
take a look at your jackett dashboard **add indexer** page. 
it should already be there under *Corsaro.red*

**Comment by 100ferhas** [comment]
**_Corsaro.red_** is not working actually, gives error `Connection refused: Connection refused`.

**Comment by garfield69** [comment]
@100ferhas  its working for me
![image](https://user-images.githubusercontent.com/6933240/92295839-7f5fe780-ef82-11ea-84b9-4131dee616c8.png)

so what ever the problem is it is at your end.
raise a ticket if you want help.
