### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by annomatik** [Jackett/Jackett#6158]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  Not sure how I can find out, cannot start jackett.
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**: Not sure how I can find out, cannot start jackett.

-------------------------------

Hi! I tried updating to the newest jackett version. Now, I can no longer start Jackett. Instead, I get this:

"Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, reference. (Exception from HRESULT: 0x80131040)
Aborted"

System: Raspbian Stretch on a Raspberry Pi 3B+
Update Package: https://github.com/Jackett/Jackett/releases/download/v0.11.802/Jackett.Binaries.Mono.tar.gz

As the automatic jackett update stopped working a while ago, I stopped Jackett (systemctl stop jackett), downloaded the .tar.gz to a temp directory, extracted that .tar.gz, run JackettUpdate -p /opt/jackett and tries starting jackett with systemctl start jackett. The last command failed, I can no longer start jackett.

Please help. Thanks!

**Comment by garfield69** [comment]
Instead of running jackettupdate, manually install the latest package files to the /opt/jackett folder.

**Comment by annomatik** [comment]
So just copy with overwrite?

**Comment by garfield69** [comment]
absolutely :-)

**Comment by annomatik** [comment]
Ok, here's what's happening now:

 # systemctl status jackett
● jackett.service - Jackett Daemon
   Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Sun 2019-10-13 21:55:39 CEST; 2s ago
  Process: 13867 ExecStart=/opt/jackett/jackett --NoRestart (code=killed, signal=ABRT)
 Main PID: 13867 (code=killed, signal=ABRT)

Oct 13 21:55:39 ***** systemd[1]: jackett.service: Unit entered failed state.
Oct 13 21:55:39 ***** systemd[1]: jackett.service: Failed with result 'signal'.

**Comment by garfield69** [comment]
did you use the arm32 package?

**Comment by annomatik** [comment]
No, the mono one.

**Comment by garfield69** [comment]
try the arm32

**Comment by annomatik** [comment]
We have a winner -- thank you! :-)

 # systemctl status jackett
● jackett.service - Jackett Daemon
   Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2019-10-13 22:05:40 CEST; 4s ago
 Main PID: 24548 (jackett)
   CGroup: /system.slice/jackett.service
           └─24548 /opt/jackett/jackett --NoRestart
