### ISSUE TITLE
[req] ultradox

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#6159]
Octopus is a Russian Public Torrent Tracker for Movies and TV.

~~Link: https://m.octopus.bz/~~
~~Legacy Link: http://octopushome.org/~~
~~Legacy link: http://octopushome.su~~

http://my.ultradox.be/

**Comment by garfield69** [comment]
I cant find a search page. is there one?
without a search page this site is not suitable for use with jackett.

**Comment by dimqua** [comment]
It's possible to make search queries like: 
http://octopushome.org/index.php?do=search&subaction=search&showposts=1&story=2018

**Comment by garfield69** [comment]
thanks. 
the ideal result would be if there is a search that returns torrent listing like the top half or the home page
![image](https://user-images.githubusercontent.com/6933240/66725087-31358780-ee8a-11e9-9258-a3631f6f5bc6.png)
is there such a search?
I cant navigate this site at all, maybe its all the red colours I cant tell anything apart ;-)

**Comment by garfield69** [comment]
looks like the search returns a details page link for a series or movie, which in turn can contain one or more torrent links.
as such this site is not suitable for the cardigann processor, and the indexer will need to be coded in c#.

**Comment by dimqua** [comment]
This is what I was afraid of, but isn't it possible to grab just one link? The best quality one, like 720p or 1080p if available.

**Comment by garfield69** [comment]
not using the cardigann yaml processor.
it does not have a logic block that allows you to actively select the best link based on possible criteria.
that kind of logic is only available in a c# indexer where of course you can code any logic you want.

**Comment by ilike2burnthing** [comment]
series of redirects

**Comment by dimqua** [comment]
Unfortunately their URL is changed constantly: http://octopus-zerkalo.ru/

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
