### ISSUE TITLE
[OSX] Install_service_macos

### ISSUE THREAD

**Issue by Eldoc62** [Jackett/Jackett#6164]
Hi All,

Since I repaired my disk permissions on macos I can not get jackett up and running anymore. Against it starts on the terminal. Just in use I have an error:

I'm all update but impossibl to install service macos

`Last login: Mon Oct 14 16:13:13 on ttys000
mkdir: /Volumes/HDD_1/.bash_sessions: Operation not permitted
Mac-Pro-de-Nico:~ toto$ /Volumes/HDD_1/Jackett\ 4/install_service_macos ; exit;
/Volumes/HDD_1/Library/LaunchAgents/org.user.Jackett.plist: Path had bad ownership/permissions
ERROR: Could not launch agent. The installation might have failed.
Please open an issue on https://github.com/Jackett/Jackett/issues and paste following information:
Jackett directory: `/Volumes/HDD_1/Jackett 4`

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Opération terminée]
`

I put the write and read rights to "everyone" on the jackett folder ...

It's not enough I have to put all the volume ??

Thank you

**Comment by garfield69** [comment]
you may also need to change the permissions for the `~/.config/Jackett/` folder.

**Comment by Eldoc62** [comment]
Hi and thank you :)

But i can't find this folder ... 

You know where i cherch ?

**Comment by garfield69** [comment]
the dot folders are hidden by default on macos. 
https://www.howtoisolve.com/guide-to-show-hidden-files-on-macos/

**Comment by Eldoc62** [comment]
Hi and thank you,

I've make :

defaults write com.apple.finder AppleShowAllFiles -boolean true; killall Finder

It's ok i find .config

I make :

sudo chmod -R 777 /Volumes/HDD_1/.config/Jackett 

it's ok... But always the same defaut

**Comment by garfield69** [comment]
well I am out of ideas. macos is not my usual platform so I don't have a lot of experience with it.
Ping to any volunteers that can assist this user with his permissions issue?

**Comment by Eldoc62** [comment]
Ok thanks for your HELPS ;)

I make :

sudo chmod -R 777 /Volumes/HDD_1/Library/LaunchAgents
sudo chmod -R 777 /Volumes/HDD_1/.config/Jackett

and i've :

Last login: Thu Oct 17 09:12:28 on ttys002
mkdir: /Volumes/HDD_1/.bash_sessions: Operation not permitted
/Volumes/HDD_1/Log\'s/Apple/Mac/Jackett\ 4/install_service_macos ; exit;
Mac-Pro-de-Nico:~ nicolasverhaeghe$ /Volumes/HDD_1/Log\'s/Apple/Mac/Jackett\ 4/install_service_macos ; exit;
/Volumes/HDD_1/Library/LaunchAgents/org.user.Jackett.plist: Path had bad ownership/permissions
ERROR: Could not launch agent. The installation might have failed.
Please open an issue on https://github.com/Jackett/Jackett/issues and paste following information:
Jackett directory: `/Volumes/HDD_1/Log's/Apple/Mac/Jackett 4`

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Opération terminée]

**Comment by majorsl** [comment]
Hello, first, you should not chmod things to 777 as a quick way to get things working.  A better way, in the case of LaunchAgents, is to look at what the permissions of the others that are working.

/Library/LaunchAgents are the system agents and are owned by root:wheel so you should chown them to this. The max permissions they should have would be 755.  777 won't work because it is expecting a specific user/group to have access.

If you are just running Jackett as yourself as the user that is logged in all the time, a more appropriate place for it is in your user Library: ~/Library/LaunchAgents which is less restrictive and just has your user permissions so you probably won't have to deal with changing all that.

Hope this helps.

**Comment by Eldoc62** [comment]
Hello and thank you for the return.

I do not understand your advice. Here is the installation log's

Maybe we understand each other better because my rights look good as well as the location of the files. It seems to me no?

`Last login: Mon Nov 11 21:07:28 on ttys000
mkdir: /Volumes/HDD_1/.bash_sessions: Operation not permitted
/Volumes/HDD_1/Log\'s/Apple/Mac/Jackett\ 5/install_service_macos ; exit;
Mac-de-Nico:~ nicolasv$ /Volumes/HDD_1/Log\'s/Apple/Mac/Jackett\ 5/install_service_macos ; exit;
/Volumes/HDD_1/Library/LaunchAgents/org.user.Jackett.plist: Path had bad ownership/permissions
ERROR: Could not launch agent. The installation might have failed.
Please open an issue on https://github.com/Jackett/Jackett/issues and paste following information:
Jackett directory: `/Volumes/HDD_1/Log's/Apple/Mac/Jackett 5`

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Opération terminée]
`

**Comment by elecenet** [comment]
Hello!
I'm having the same problem here but I am not sure if is related to file permissions. The console error executing install_service  through Terminal is:

**/Applications/Jackett/install_service_macos ; exit;                             
dani@Mac-mini-de-Luis ~ % /Applications/Jackett/install_service_macos ; exit;
Removing Jackett executable and all .dylib and .dll files from quarantine...
Load failed: 5: Input/output error
ERROR: Agent could not be loaded. Please open an issue on https://github.com/Jackett/Jackett/issues and paste the output.
*Jackett directory*: /Applications/Jackett
*LaunchAgents permissions*:
drwxr-xr-x  10 dani  staff   320  4 oct 22:59 .
drwxr-xr-x  79 dani  staff  2528 23 sep 21:37 ..
-rw-r--r--@  1 dani  staff  6148 25 sep 22:37 .DS_Store
-rw-r--r--   1 dani  staff   684  4 oct 22:59 org.user.Jackett.plist
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...      59 completed.**

Actually I'm starting Jackett directly from Terminal but that requires an open Terminal window constantly.

**Comment by ilike2burnthing** [comment]
Install and uninstall scripts have been updated by https://github.com/Jackett/Jackett/pull/13626, available in [v0.20.2080](https://github.com/Jackett/Jackett/releases/tag/v0.20.2080). Please check if your issue is resolved.
