### ISSUE TITLE
[1337x] Exception (1337x): certificate validation failed: [Subject]  CN=legal.vodafone.pt, OU=DOS, O=Vodafone-DOS, L=Lisbon, S=Lisbon, C=PT[Issuer]  CN=legal.vodafone.pt, OU=DOS, O=Vodafone-DOS, L=Lisbon, S=Lisbon, C=PT[Serial Number]  00A077F23849697397[Not Before]  3/14/2014 12:29:37 AM[Not After]  3/14/2015 12:29:37 AM[Thumbprint]  D052EB73DF1DBB432CC3FB6D71B5FAC0FE620A92: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by joaofgf** [Jackett/Jackett#6168]
[1337x] Exception (1337x): certificate validation failed: [Subject]  CN=legal.vodafone.pt, OU=DOS, O=Vodafone-DOS, L=Lisbon, S=Lisbon, C=PT[Issuer]  CN=legal.vodafone.pt, OU=DOS, O=Vodafone-DOS, L=Lisbon, S=Lisbon, C=PT[Serial Number]  00A077F23849697397[Not Before]  3/14/2014 12:29:37 AM[Not After]  3/14/2015 12:29:37 AM[Thumbprint]  D052EB73DF1DBB432CC3FB6D71B5FAC0FE620A92: An error occurred while sending the request. (Test)

**Comment by garfield69** [comment]
you are being blocked by your ISP vodafone.pt
try switching your vodafone provided DNS to one of the public ones, such as Cloudflare's 1.1.1.1 or Googles 8.8.8.8

**Comment by joaofgf** [comment]
thanks.
I'm using pihole dns (cloudflare).

**Comment by garfield69** [comment]
so you need to white-list the 1337x.to site on pihole if that is an option.

**Comment by joaofgf** [comment]
no. it's not being blocked by pihole. i don't understand, i have the windows dns configured to pihole and pihole to cloudflare... can the isp still block it? (i also cant access thepiratebay.org, etc)

**Comment by garfield69** [comment]
I know nothing if pi-hole other than what I googled just now, that its some kind of ad blocker?
what I do know is this:
https://1337x.to/ official site uses a certificate with a thumbprint of b3c0e31afd9259f390e14329a7a6fb663444b6d4 and yours is D052EB73DF1DBB432CC3FB6D71B5FAC0FE620A92
so something is causing the wrong certificate to be used.
if you open a browser on the same machine that is running jackett and you access https://1337x.to/ what do you get?

**Comment by joaofgf** [comment]
thank you my friend. it was my isp - they somehow intercept the dns request even if not through their dns servers.
i just "solved" the problem with a vpn. 
kind regards.

**Comment by uonze** [comment]
@joaofgf I had the same issue (I'm also from Portugal).
I ended up solving by using DNS Secure (similar to HTTPS but for DNS)

Here are the intruction for Windows (I ended up using [Simple DNSCrypt](https://simplednscrypt.org/)):
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-Windows
There are also clients for Linux and Mac.

**Comment by MaxPayneFH** [comment]
@joelfoliveira  thanks alot for the solution, it allows to bypass vodafone censorship.
I ended up following this guide to use DNS over TLS:
https://fedoramagazine.org/use-dns-over-tls/
