### ISSUE TITLE
yggtorrent can't find seasons 10 and above for TV Show

### ISSUE THREAD

**Issue by GhostPyxel** [Jackett/Jackett#6172]
**Describe the bug**
Jackett can't find any season above season 9 on any TV Shows. For example: Jackett will find South Park S08 and S09 on tracker but don't see S10, S11, S12..

This issue have been tested on differents series (The Simpsons, South Park, Doctor Who, The Office..) and none of them are able to be grabbed by Jackett. It has been tested on differents trackers like YGGTorrent (mainly), Torrent9, OxTorrents, Sharewood. All seasons requested are available on trackers and can be downloaded manually. 

Nothing on the tracker is changing, for example the names of the seasons are:

South.Park.S08.MULTI.1080p.BluRay.x265.AC3-LCDS
South.Park.S09.MULTI.1080p.BluRay.x265.AC3-LCDS
South.Park.S10.MULTI.1080p.BluRay.x265.AC3-LCDS

_Only the S0X becomes SXX._

For what I've tried, requesting "South Park S10" or "South Park S010" or "South Park Season 10", makes no difference.

Accounts are working, can download, and have ratio below 1 for the semi-privates trackers.

**To Reproduce**
1. Go to Jackett
2. Add a Tracker (YGGTorrent for me, mainly) and test / save it. 
3. Manual Search any TV Shows that have 10 seasons or more, and request season 10 or more.
4. If you are in my case, Jackett should return the statement: "No data available in table."

**Expected behavior**
Jackett should find seasons 10th and above.

**Logs**
Full Debug Log of v0.11.817-ls43: https://pastebin.com/7YW5Z5UK

**System**
OS: NAS Synology DSM 6.2.2-24922 Update 3

**Environement**
Docker Ver.18.09-0-0506 with 4 Containers related
Docker Container Ombi 3.0.4809-ls65
Docker Container Sonarr 3.0.3.644-ls142
Docker Container Radarr 2.0.0.2090-ls29
Docker Container Jackett v0.11.817-ls43

All containers are based on images provided by LinuxServers.io

**Additional context**
At first, I was thinking that I've set the uncorrect Category ID in the tracker settings or that a parameter could disturbed the results, but even if I select all category at once or that I set the parameters to default, Jackett returns nothing.

Jackett is working perfectly fine and as expected in everything that I ask him (Movies, TV Shows or even Anime) but for some reason this happen only when we hit the season 10 and in no other cases.

I've seen that there is a pre-release for Jackett v0.12.824-ls30 posted today. I'll try it soon and keep you update. (Impossible to install it, Docker returns an invalid file format error.

**Comment by garfield69** [comment]
this is most likely an issue with the yggtorrent indexer which has a lot of additional code to pre-edit the keywords before a search takes place
```jaml
    keywordsfilters:
      # Hack For anime Search ! example : replace sonarr search of 
      # One Punch Man S2 10 OR One Punch Man S2 2
      # BY
      # One Punch Man S02E10 OR One Punch Man S02E02
      - name: re_replace #S 1-9 & EP >= 10
        args: ["(.*)[sS]([1-9])\\s(\\d{2,3})$", "$1 S0$2E$3"]
      - name: re_replace #S 1-9 & EP 1-9
        args: ["(.*)[sS]([1-9])\\s(\\d{1})$", "$1 S0$2E0$3"]
      - name: re_replace #S >= 10 & EP >= 10
        args: ["(.*)[sS]([1-9][0-9])\\s(\\d{2,3})$", "$1 S0$2E$3"]
      - name: re_replace #S >= 10 & EP 1-9
        args: ["(.*)[sS]([1-9][0-9])\\s(\\d{1})$", "$1 S0$2E0$3"]
      - name: re_replace #Full season S 1-9
        args: ["(.*)[sS]([1-9])$", "$1 S0$2"]
      - name: re_replace #Full season S >= 10
        args: ["(.*)[sS]([1-9][0-9])$", "$1 S0$2"]
      # END ANIME HACK
      - name: replace
        args: ["\"", ""]
      - name: trim
```
@xfouloux can you please check that none of your changes to this indexer are responsible for this issue and make corrections if they do? thanks.

**Comment by garfield69** [comment]
as for the other indexers you mentioned:
I cant test oxtorrent right now, its either offline or going extremely slow it times out.

the web site torrent9 does not return hits for `south park s11` or `south park saison 11` or `south park season 11` and similarly for 22, so you can't blame the torrent9 indexer for that.

and sharewood does not have any south park tv episodes. a search of just south park returns *South Park Le Film 1999*

**Comment by GhostPyxel** [comment]
Thanks for the quick response @garfield69 
So if I'm not mistaken, there's nothing I can do aside waiting for a new pushed release of Jackett. (a new image of LinuxServers.io for my part)
Do you know if your fix will be available in the pre-release [v0.12.827-ls30](https://github.com/linuxserver/docker-jackett/releases/tag/v0.12.827-ls30) ?

**Comment by garfield69** [comment]
the oxtorrent will be available beginning with jackett pre-release 0.12.831
no work has been done of the yggtorret indexer as yet.
the default docket package is built from the full release. pre-releases are available using the development tag. see https://hub.docker.com/r/linuxserver/jackett/ for details.

**Comment by xfouloux** [comment]
Good catch, i would have looked at that this week end, thanks for the patch.
And my bad for this error ^^

**Comment by GhostPyxel** [comment]
Well, it's definitely working now ! South Park and others series are being found. Thank you guys for your hard work, this is really appreciated.
