### ISSUE TITLE
[kapaki] Error: -ERROR-Έχετε εισάγει ένα άκυρο όνομα χρήστη ή κωδικό πρόσβασης. Παρακαλώ εισάγετε τα σωστά στοιχεία και προσπαθήστε ξανά.Έχετε χρησιμοποιήσει 1 από τις 5 προσπάθειες σύνδεσης. Μετά αφού και οι 5 έχουν χρησιμοποιηθεί, δεν θα μπορείτε να συνδεθείτε για 15 λεπτά. (Config)

### ISSUE THREAD

**Issue by unrealbe** [Jackett/Jackett#6177]
Using v0.12.824 mono version
getting this error trying to add /karagarga.in, not sure why its not in english?
Manually login works.

From the logs:

When | Level | Message
-- | -- | --
Oct 15, 2019 10:14:43 PM | Error | Jackett.Common.ExceptionWithConfigData: Error: -ERROR- 	Έχετε εισάγει ένα άκυρο όνομα χρήστη ή κωδικό πρόσβασης. Παρακαλώ εισάγετε τα σωστά στοιχεία και προσπαθήστε ξανά.Έχετε χρησιμοποιήσει 2 από τις 5 προσπάθειες σύνδεσης. Μετά αφού και οι 5 έχουν χρησιμοποιηθεί, δεν θα μπορείτε να συνδεθείτε για 15 λεπτά.   at Jackett.Common.Indexers.CardigannIndexer.checkForError (Jackett.Common.Utils.Clients.WebClientStringResult loginResult, System.Collections.Generic.IList`1[T] errorBlocks) [0x00079] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:385    at Jackett.Common.Indexers.CardigannIndexer.DoLogin () [0x00ca4] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:640    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration (Newtonsoft.Json.Linq.JToken configJson) [0x00031] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:877    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig (Jackett.Common.Models.DTO.ConfigItem[] config) [0x0012d] in C:\projects\jackett\src\Jackett.Server\Controllers\IndexerApiController.cs:108    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x00042] in C:\projects\jackett\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:29

**Comment by garfield69** [comment]
the error is `You have entered an invalid username or password. Please enter the correct information and try again. You have used 1 of 5 login attempts. After all 5 have been used, you will not be able to log in for 15 minutes.`

its not in English because the site default language is Greek

while you may be able to login manually to the site I suggest that the username or password you used in your kapaki jackett config is wrong.

the only other possibility I can think of is that I am aware of users that use diacritic characters in their username or password have problems with jackett.
could this apply to you?
(diacritics -> https://en.wikipedia.org/wiki/Diacritic)

**Comment by garfield69** [comment]
hold the phone.
karagarga.in is the jackett indexer Karagarga
you are using kapaki :-)

**Comment by unrealbe** [comment]
Ok I found it, this issue can be closed. I tried to setup karagara but clicked kapaki by mistake.
Sorry
