### ISSUE TITLE
[tvchaosuk] Exception (tvchaosuk): Got redirected to another domain. Try changing the indexer URL to https://tvchaosuk.com/.: Parse error (Test)

### ISSUE THREAD

**Issue by emorytaylor** [Jackett/Jackett#6178]
TV Chaos UK had an outage and website redesign. It's now on the UNIT3D platform

**Comment by garfield69** [comment]
really, you surprise me :-b
time you updated your jackett to the latest release. 
we updated the tvchoasuk indexer 4 days ago :-)
