### ISSUE TITLE
Changes to AnimeBytes scrape.php API

### ISSUE THREAD

**Issue by proton-ab** [Jackett/Jackett#6181]
This is a notice that AnimeBytes scrape.php API changed in 3 places:

- Image link provided is no longer thumbnail
- Synonyms are now proper array

```
"Synonymns": [
    "荒ぶる季節の乙女どもよ.",
    "Araburu Kisetsu no Otome-domo yo.",
    "Araburu Kisetsu no Otomedomo yo."
],
```
- Artists are now proper array

```            
"Artists": {
    "1339": {
        "name": "Hikasa Youko",
        "character": {
            "42672": "Maria Cadenzavna Eve"
         }
     }
},
```

The changes are live now and Jackett can start using new features right away. Particularly, this will solve issue where synonyms could not be used if "," character was part of a title.

**Comment by garfield69** [comment]
ping to @proton-ab @wiiaboo  @yuri-moens @seeyabye 
as the last four volunteers to raise a PR for AnimeBytes, is anyone up for amending this indexer to get it working again after the announcement posted by OP? Thanks.
