### ISSUE TITLE
[animebytes] Parse error: Can not convert Object to String. (Config)

### ISSUE THREAD

**Issue by trevjames** [Jackett/Jackett#6186]
Can't add animebytes as an indexer, though can login to the actual site just fine. Logs attached.

Fresh install, Jackett Version 0.11.817.0

[ab_log1.txt](https://github.com/Jackett/Jackett/files/3736029/ab_log1.txt)
[ab_log2.txt](https://github.com/Jackett/Jackett/files/3736030/ab_log2.txt)

**Comment by garfield69** [comment]
most likely related to #6181

**Comment by garfield69** [comment]
try out jackett pre-release 0.12.833

**Comment by tlardner** [comment]
> try out jackett pre-release 0.12.833

It's fixed for me in 0.12.833
