### ISSUE TITLE
[animebytes] Parse error: Can not convert Object to String. (Config)

### ISSUE THREAD

**Issue by tlardner** [Jackett/Jackett#6189]
Jackett Version 0.11.817.0

When trying to re-add AnimeBytes, Jackett throws "Parse error: Can not convert Object to String.". The tracker was previously added and working. 

[jackettErrorLog.txt](https://github.com/Jackett/Jackett/files/3736635/jackettErrorLog.txt)
Username and Passkey redacted from the logs.

**Comment by garfield69** [comment]
try out jackett pre-release 0.12.833
