### ISSUE TITLE
[xwtorrents] Exception (xwtorrents): Login failed: No form found on https://xtremewrestlingtorrents.net/login.php using form selector form[action=

### ISSUE THREAD

**Issue by h2xtreme** [Jackett/Jackett#6196]
XWT has a new website and Jackett now can't connect to it.

 An error occured while testing this indexer
Exception (xwtorrents): Login failed: No form found on https://xtremewrestlingtorrents.net/login.php using form selector form[action="tlogin.php"]: Parse error

**Comment by h2xtreme** [comment]
The original issue was already closed by the bot without feedback. One of these should be open

**Comment by h2xtreme** [comment]
Los from Jackett:


Oct 17, 2019 07:43:38 PM | Error | Jackett.Common.IndexerException: Exception (xwtorrents): Login failed: No form found on https://xtremewrestlingtorrents.net/login.php using form selector form[action="tlogin.php"] ---> System.Exception: Parse error ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://xtremewrestlingtorrents.net/login.php using form selector form[action="tlogin.php"]   at Jackett.Common.Indexers.CardigannIndexer.DoLogin () [0x00491] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:478    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x00984] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:1256     --- End of inner exception stack trace ---   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError (System.String results, System.Exception ex) [0x00059] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:842    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x01beb] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:1579    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x00047] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:331     --- End of inner exception stack trace ---   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x000e6] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:351    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x00024] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:815    at Jackett.Server.Controllers.ResultsController.Torznab (Jackett.Common.Models.DTO.TorznabRequest request) [0x002f0] in C:\projects\jackett\src\Jackett.Server\Controllers\ResultsController.cs:367
-- | -- | --
Oct 17, 2019 07:43:38 PM | Error | Error on 20191017194338 for XWtorrents.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://xtremewrestlingtorrents.net/login.php using form selector form[action="tlogin.php"]   at Jackett.Common.Indexers.CardigannIndexer.DoLogin () [0x00491] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:478    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x00984] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:1256

**Comment by garfield69** [comment]
works for me.
the stack trace you provided is not enough for me to determine what your issue is.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.
