### ISSUE TITLE
Error Exception in Configure System.Exception: Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by staticct** [Jackett/Jackett#62]
I'm receiving the mentioned error when trying to setup my IPTorrents account.

Error Exception in Configure System.Exception: Found no results while trying to browse this tracker

Any ideas how I can fix it? 

Logs attached (password changed to **********)
[error.txt](https://github.com/Jackett/Jackett/files/36205/error.txt)

**Comment by flightlevel** [comment]
Just gave this a try and it works perfectly for me on IPT.
Can you give it another try in case it was a connection issue.

**Comment by staticct** [comment]
So as it turns out, even though the test fails it still works correctly with sonarr. You do have to restart to get the configuration to show up though because the test fails. Even now still, if I click test it still fails.
