### ISSUE TITLE
UbuntuServer 18.04LTS - Jacket has suddenly stopped working today

### ISSUE THREAD

**Issue by acollien** [Jackett/Jackett#6225]
No issues recently. Was there an auto-update that broke Linkux x64 jacket today?

Servies was running most of today. Now it won't start. No other package changes on the server. No permissions changes. Unsure what could have caused this other than a jackett update?

`server@server:~$ service jackett restart 
server@server:~$ service jackett status 
jackett.service - Jackett Daemon 
Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: enabled) 
Active: activating (auto-restart) (Result: exit-code) since Mon 2019-10-21 20:14:05 AEDT; 3s ago 
Process: 18083 ExecStart=/opt/Jackett/Jackett/jackett --NoRestart (code=exited, status=140) 
Main PID: 18083 (code=exited, status=140)`

**Comment by egallis31** [comment]
Downloaded new version from releases fixes the issue.

**Comment by acollien** [comment]
> Downloaded new version from releases fixes the issue.

I ran apt-get update && upgrade. Wouldn't this do the same thing?
Else, how do I replace the exisiting version with new release?

**Comment by egallis31** [comment]
Not exactly sure but it would seem that they may have missed packaging the dll, but it was available on when extracted from the latest binaries release tar.

**Comment by acollien** [comment]
> Not exactly sure but it would seem that they may have missed packaging the dll, but it was available when extracted from the latest binaries release tar. Or possibly may have to run the service reinstall script as I did upon getting the latest binary.

Cheers - fixed for now.
