### ISSUE TITLE
[demonoid] Exception (demonoid): Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'): Parse error (Test)

### ISSUE THREAD

**Issue by scr44tch** [Jackett/Jackett#6226]
[demonoid] Exception (demonoid): Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'): Parse error (Test)

demonoid is not working

Jackett Version 0.12.847.0

**Comment by garfield69** [comment]
works for me.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by scr44tch** [comment]
here is the debug log

https://pastebin.com/raw/u2UJLakX

**Comment by garfield69** [comment]
odd.
the demonoid site's search results html that your log contains  should have be able to be processed by the demonoid indexer in 0.12.847

unless for some reason your copy of the indexer did not get updated (as might occur for a linux platform if the auto-update bug in #5208 bit you.

Please shutdown your jackett service and manually upgrade your jackett with the latest version and try again.

**Comment by scr44tch** [comment]
> odd.
> the demonoid site's search results html that your log contains should have be able to been processed by the demonoid indexer in 0.12.847
> 
> unless for some reason your copy of the indexer did not get updated (as might occur for a linux platform if the auto-updater bug in #5208 bit you).
> 
> Please shutdown your jackett service and manually upgrade your jackett with the latest version and try again.

that worked, 
thx you very much
