### ISSUE TITLE
IgnoreSslErrors defined via ServerConfig is ignored

### ISSUE THREAD

**Issue by tkimball83** [Jackett/Jackett#6229]
As far as I can tell if you set IgnoreSslErrors to true via ServerConfig, the configuration isn't passed along to the web client.  However, if you set this on the command line the option is passed to the web client correctly, but the logs spit out a deprecation error (as expected).

Using command-line option:
```
$ /opt/jackett/jackett --IgnoreSslErrors true --NoRestart

jackett: 10-22 01:00:02 Info Starting Jackett v0.12.847.0
jackett: 10-22 01:00:02 Error The IgnoreSslErrors option has been deprecated, please remove it from your start arguments
jackett: 10-22 01:00:02 Info Environment version: 3.0.0 (/opt/jackett/)
jackett: 10-22 01:00:02 Info OS version: Unix 5.3.7.1 (64bit OS) (64bit process)
jackett: 10-22 01:00:02 Info Jackett variant: CoreLinuxAmdx64
jackett: 10-22 01:00:02 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
jackett: 10-22 01:00:02 Info App config/log directory: Jackett
jackett: 10-22 01:00:02 Info issue: \S
jackett: 10-22 01:00:02 Info Using HTTP Client: HttpWebClient2NetCore
jackett: 10-22 01:00:03 Info Loading Cardigann definitions from: cardigann/definitions/, /etc/xdg/cardigan/definitions/, /opt/jackett/Definitions
jackett: 10-22 01:00:03 Info Loading Cardigann definition {...}
jackett: 10-22 01:00:04 Info Adding aggregate indexer
jackett: 10-22 01:00:04 Info HttpWebClient: Disabling certificate validation
jackett: Hosting environment: Production
jackett: Content root path: /opt/jackett/Content
jackett: Now listening on: http://[::]:9117
jackett: Application started. Press Ctrl+C to shut down.
```

Using ServerConfig option:
```
$ sudo grep IgnoreSslErrors /opt/jackett/Jackett/ServerConfig.json
  "IgnoreSslErrors": true,

jackett: 10-22 01:17:04 Info Starting Jackett v0.12.847.0
jackett: 10-22 01:17:04 Info Environment version: 3.0.0 (/opt/jackett/)
jackett: 10-22 01:17:04 Info OS version: Unix 5.3.7.1 (64bit OS) (64bit process)
jackett: 10-22 01:17:04 Info Jackett variant: CoreLinuxAmdx64
jackett: 10-22 01:17:04 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
jackett: 10-22 01:17:04 Info App config/log directory: Jackett
jackett: 10-22 01:17:04 Info issue: \S
jackett: 10-22 01:17:04 Info Using HTTP Client: HttpWebClient2NetCore
jackett: 10-22 01:17:05 Info Loading Cardigann definitions from: cardigann/definitions/, /etc/xdg/cardigan/definitions/, /opt/jackett/Definitions
jackett: 10-22 01:17:05 Info Loading Cardigann definition {...}
jackett: 10-22 01:17:06 Info Adding aggregate indexer
jackett: Hosting environment: Production
jackett: Content root path: /opt/jackett/Content
jackett: Now listening on: http://[::]:9117
jackett: Application started. Press Ctrl+C to shut down.
```

As you can see in the first log we get a deprecation warning and a log statement saying disabling certificate validation.  However, setting it in ServerConfig you don't get a deprecation warning (as expected), but you also don't get the log statement saying certificate validation is disabled.  It seems the value being set in ServerConfig.json isn't being set/passed correctly.

Please correct me if I should be expecting different behavior here.  Thanks!

**Jackett version**: v0.12.847
**Mono version**: N/A 

-------------------------------

**Comment by garfield69** [comment]
yup, it appears that --IgnoreSslErrors  (or -n) was only ever defined as a run-time option.
cannot find it in the ServerConfig processor.

**Comment by tkimball83** [comment]
What are our options here?  Is this option really being deprecated, or should that error be removed?

I'm fine with either implementation (runtime or serverconfig), as long as the option to ignore ssl errors stays present in some way as not all trackers stay on top of their certs.

**Comment by garfield69** [comment]
way beyond my expertise. I'm not a c# dev and was not party to the original implementation.

my best guess is that the IgnoreSslErrors flag was not meant to be defined a **permanent** option to **always** disable certificate checking, because they never added that option for the serverConfig.

Rather, it was meant to be a **temporary** run-time option, meant to be used in emergency for users, until a certificate bypass was coded for that particular indexer and published.
  
is it possible to update each indexer individually to ignore certain certificates based on their thumbprint. This applies to both the jaml indexers (via the certificates statement)
```yaml
  # If the tracker uses untrusted HTTPS certificates (self signed, expired, etc)
  # you can specify a list of thumbprint hashes which should be accepted as valid anyway.
  # This shouldn't be needed in most cases.
  certificates:
    - D40789207A75EA36B02E255BF7162C8DF9637751
```
and for the c# indexers via the AddTrustedCertificate function
```c#
            webclient.AddTrustedCertificate(new Uri(SiteLink).Host, "B52C043ABDE7AFB2231E162B1DD468758AEEE307");
```

**Comment by garfield69** [comment]
sure. why not.
if the c# devs disagree they can always put it back ;-)

**Comment by tkimball83** [comment]
Excellent, thanks! :)
