### ISSUE TITLE
Jackett was working for two days no issues now throws the following error

### ISSUE THREAD

**Issue by SrBushWookie** [Jackett/Jackett#6231]
Current Setup 100% updated raspbian running on a raspberry pi 4
services installed and working:
-Sonarr
-Radarr
-Deluge
-PIA VPN running as an OpenVPN service on startup
-Pi-Hole

Jackett is starting as a service but provides the following error and fails to start now seemingly out of the blue:

`-- A start job for unit jackett.service has finished successfully.
--
-- The job identifier is 1012.
Oct 21 19:10:19 pi4-4G jackett[987]: Error:
Oct 21 19:10:19 pi4-4G jackett[987]:   An assembly specified in the application dependencies manifest (jackett.deps.json) was not found:
Oct 21 19:10:19 pi4-4G jackett[987]:     package: 'Microsoft.AspNetCore.Mvc.NewtonsoftJson', version: '3.0.0'
Oct 21 19:10:19 pi4-4G jackett[987]:     path: 'lib/netcoreapp3.0/Microsoft.AspNetCore.Mvc.NewtonsoftJson.dll'
Oct 21 19:10:19 pi4-4G systemd[1]: jackett.service: Main process exited, code=exited, status=140/n/a`

Any assistance would be appreciated :)

SrBushWookie

**Comment by garfield69** [comment]
sounds like you have run afoul of the updater issue #5208
your best bet is to download and install the latest package

and then enabling the disable-auto-update option from your jackett dashboard would be a way to prevent further issues until it is resolved.
don't forget to click on the apply-server-settings button to save your settings.

**Comment by garfield69** [comment]
fix is available with stable jackett 0.12.898. but you will need to install manually and run the systemd install script anew.

1. open a terminal and shutdown the jackett service using `systemctl stop jackett.service`
2. download and extract the linux package that applies to your platform from https://github.com/Jackett/Jackett/releases/tag/v0.12.898
3. copy or move/replace all the files from the Jackett folder in the downloaded/extracted package to where ever you have previously put the jackett binaries. Typical locations are `/opt/Jackett` or `~/Jackett`
4. cd to your Jackett binary folder and install the service with `sudo ./install_service_systemd.sh` 
this will start the service (if it ran successfully)
5. access your jackett dashboard with your browser and untick the Disable auto Update check box and press the Apply Server Settings button.
