### ISSUE TITLE
[turktorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by kekec777** [Jackett/Jackett#6232]
Hallo 

It seems this site has updated their site.. ?
https://turktorrent.us

The test fails ....

**Comment by garfield69** [comment]
yes, you are correct, the site has new layout html and new categories.
try out jackett 0.12.863
don't forget to update your site's account profile to use the **Classic** theme and the **English** language or else you will not get any results from this indexer.

**Comment by kekec777** [comment]
Super , thanks for the quick reply 
and we remove or outline this:
#    keywordsfilters:
#      - name: re_replace # S01E01 to X.sezon X.blm
#        args: ["(?i)\\bS0*(\\d+)E0*(\\d+)\\b", "$1.sezon $2.blm"]


#        filters:
#          - name: re_replace # X.sezon X.blm to S01E01
#            args: ["(?i)\\b(\\d+).sezon\\s(\\d+).blm\\b", "S$1E$2"]
#          - name: re_replace # switch (dd.mm.yyyy) to mm.dd.yyyy
#            args: ["\\((\\d+)\\.(\\d+)\\.(\\d+)\\)", " $2/$1/$3 "]

It seems they have changed their way to name the tv shows... :)
