### ISSUE TITLE
Update leads to mono issues.

### ISSUE THREAD

**Issue by packtloss** [Jackett/Jackett#6233]
Hi there! Here are the last few lines in my log files:

`2019-10-20 21:41:02.3545 Info Jackett variant: CoreLinuxAmdx64
2019-10-20 21:41:02.8110 Info New release found.  Current: v0.11.817 New: v0.12.847
2019-10-20 21:41:11.9940 Info Starting updater: /tmp/JackettUpdate-v0.12.847-637072044674409907/Jackett/JackettUpdater --Path "/home/media/Jackett" --Type "Console" --Args " --NoRestart" --KillPids "9787" --NoRestart
2019-10-20 21:41:12.4410 Info Updater started process id: 3451
`
when i run Jackett:

` ./jackett
Error:
  An assembly specified in the application dependencies manifest (jackett.deps.json) was not found:
    package: 'runtimepack.Microsoft.AspNetCore.App.Runtime.linux-x64', version: '3.0.0'
    path: 'System.Windows.Extensions.dll'
`

So it looks like the latest update does something to break mono compatibility for me. Can anyone suggest how i can fix this? There seems to be no Mono update at this time.

`mono-devel is already the newest version (6.4.0.198-0xamarin3+ubuntu1804b1).
`

**Comment by garfield69** [comment]
sounds like you have run afoul of the auto-updater issue #5208
your best bet is to download and install the latest package

and then **enabling** the *disable-auto-update* option from your jackett dashboard would be a way to prevent further issues until it is resolved.
don't forget to click on the *apply-server-settings* button to save your settings.
