### ISSUE TITLE
An assembly specified in the application dependencies manifest (jackett.deps.json) was not found System.Windows.Extensions.dll

### ISSUE THREAD

**Issue by abbasvalliani** [Jackett/Jackett#6235]
After the update, Jackett is failing with the following issue:

Oct 22 16:29:36 ubuntu jackett[18951]:   An assembly specified in the application dependencies manifest (jackett.deps.json) was not found:
Oct 22 16:29:36 ubuntu jackett[18951]:     package: 'runtimepack.Microsoft.AspNetCore.App.Runtime.linux-x64', version: '3.0.0'
Oct 22 16:29:36 ubuntu jackett[18951]:     path: 'System.Windows.Extensions.dll'

**Comment by garfield69** [comment]
sounds like you have run afoul of the auto-updater issue #5208
your best bet is to download and install the latest package

and then **enabling** the *disable-auto-update* option from your jackett dashboard would be a way to prevent further issues until it is resolved.
don't forget to click on the *apply-server-settings* button to save your settings.

**Comment by abbasvalliani** [comment]
Perfect. Thanks.
