### ISSUE TITLE
TeamHD and Russian letters

### ISSUE THREAD

**Issue by kirrmk** [Jackett/Jackett#6241]
Is it possible to implement the Strip Russian Letters function? For example, like at Kinozal, rutracker and other. Thanks.

**Comment by garfield69** [comment]
try  out jackett pre-release 0.12.866
the config option is set to false by default.
use your Jackett dashboard wrench to edit the teamhd config to tick the stripRussianLetters checkbox.
You may also need to renew your cookie (if it shows up blank in the config, or if the cookie has expired).

**Comment by garfield69** [comment]
sure, i'll add it to the list, but I note that neither rutracker or kinozal have this letter stripped. 
do you think I should add it to theirs as well?

**Comment by garfield69** [comment]
i'll answer myself ;-)
yes, I should add ё to kinozal and rutracker stipping, as searching for green book on those sites shows that they also need that letter removed.

**Comment by garfield69** [comment]
jackett 0.12.869 has the additional letter stripping.
