### ISSUE TITLE
XSpeeds query failure

### ISSUE THREAD

**Issue by jonocairns** [Jackett/Jackett#626]
Hi there,

The XSpeeds indexer has been working perfectly until today. I'm getting the following error when attempting to query.

Configuration failed: '', hexadecimal value 0x07, is an invalid character. Line 338, position 1.

Logs only say "Exception in test_indexer"

Let me know if there's anything else I can add to help.

Cheers

**Comment by kaso17** [comment]
This happens if they have a release with some unprintable special chars in their description, by now it's already out of the latest torrents feed and it should work again.

**Comment by kaso17** [comment]
If someone sees the problem please make a copy of the rss feed file so I can fix it for good.

**Comment by jayotterbein** [comment]
I made a PR #633 to address this issue.

**Comment by kaso17** [comment]
thank you, it's part of the latest release
