### ISSUE TITLE
[Req] Tribalmixes

### ISSUE THREAD

**Issue by pgk831** [Jackett/Jackett#6260]
https://www.tribalmixes.com/

TribalMixes is a ratioless Private Torrent Tracker for DJ MIXES

**Comment by garfield69** [comment]
try out jackett pre-release 0.12.883

**Comment by ilike2burnthing** [comment]
https://www.tribalmixes.com/ - site is currently broken
![tribal](https://user-images.githubusercontent.com/59480337/113457574-0f2a1f00-9408-11eb-8291-2f44b024d248.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.tribalmixes.com/ plagued by multiple net::ERR_HTTP2_PROTOCOL_ERROR 200 preventing pages from working
![image](https://user-images.githubusercontent.com/6933240/132316342-818c1718-05e6-4ca9-91a3-4d75b4e122ea.png)
causing Jackett to get back a `Received an unexpected EOF or 0 bytes from the transport stream. ` error

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.tribalmixes.com/ nginx error!  The page you are looking for is temporarily unavailable. Please try again later.

**Comment by garfield69** [comment]
online
