### ISSUE TITLE
[animebytes] Parse error: Can not convert Object to String. (Config)

### ISSUE THREAD

**Issue by AoNoEzreal** [Jackett/Jackett#6261]
Hey, so the animebytes provider stopped working altogether, tried to delete it and add it again but since the testing fails i can't add it anymore. 

i get the "Can not convert object to String" error and indeed looking at the logs, the response seems to come but it's a json 
here's the full log, it contains the error and the object that animebytes returned

seems like an quick fix but that's only my pov 
[logs.txt](https://github.com/Jackett/Jackett/files/3777683/logs.txt)

using Jackett Version 0.11.559.0
on a debian 9 distribution

thanks again for all the work !!

**Comment by garfield69** [comment]
upgrade to the latest jackett 0.12.* and you should be good to go.
