### ISSUE TITLE
Jackett won't start on Linux, Could not load file or assembly 'NLog.Web.AspNetCore,

### ISSUE THREAD

**Issue by maxtheking** [Jackett/Jackett#6262]
I recently setup a fresh VM for Jackett because it can now run without Mono, great! It worked for the first 2 days, but now the service won't start anymore. The OS is Debian 9 x64. The logs are giving me the following error message:
`2019-10-28 10:28:29.0902 Info Starting Jackett v0.12.869.0 
2019-10-28 10:28:29.2352 Error System.BadImageFormatException: Could not load file or assembly 'NLog.Web.AspNetCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=REMOVED'. The module was expected to contain an assembly manifest.
File name: 'NLog.Web.AspNetCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=REMOVED'
   at Jackett.Server.Program.CreateWebHostBuilder(String[] args, String[] urls, String contentRoot)
   at Jackett.Server.Program.Main(String[] args)`

Any ideas?

**Jackett version**:  v0.12.869

-------------------------------

**Comment by garfield69** [comment]
Sounds like you got bit by the linux auto-updater bug in #5208 
A fix is being tested currently, but has not been published in a full release yet.
please read and action https://github.com/Jackett/Jackett/issues/5208#issuecomment-546564391
and then you should be good to go.
Look forward to your feedback on whether you still have this problem in subsequent auto-updates after you have applied0.12.879.

**Comment by maxtheking** [comment]
@garfield69 Yeah i performed a manual update, which fixed it. Disabled auto-update for now. Thanks!

**Comment by garfield69** [comment]
fix is available with stable jackett 0.12.898. but you will need to install manually and run the systemd install script anew.

1. open a terminal and shutdown the jackett service using `systemctl stop jackett.service`
2. download and extract the linux package that applies to your platform from https://github.com/Jackett/Jackett/releases/tag/v0.12.898
3. copy or move/replace all the files from the Jackett folder in the downloaded/extracted package to where ever you have previously put the jackett binaries. Typical locations are `/opt/Jackett` or `~/Jackett`
4. cd to your Jackett binary folder and install the service with `sudo ./install_service_systemd.sh` 
this will start the service (if it ran successfully)
5. access your jackett dashboard with your browser and untick the Disable auto Update check box and press the Apply Server Settings button.
