### ISSUE TITLE
Beyond-HD add indexer fails to prompt for info

### ISSUE THREAD

**Issue by drizuid** [Jackett/Jackett#6267]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett Version 0.11.817.0

-------------------------------
around line 712 is where i click to add the indexer. I search it, then click the gear icon which worked for my other indexers. In this case, nothing happens.  In the logs, i see
`Debug The request path /api/v2.0/indexers/beyond-hd/config does not match a supported file type`
I tried the latest dev branch, the current stable, and i rolled back 10 builds to check. In all cases, I had the same behavior

https://pastebin.com/hfQ6npBW

**Comment by garfield69** [comment]
beyond-hd changed the html to their **classic** theme within the last 28 hours.

1. login to beyond-hd directly with your browser and double check your a/c profile settings still has the **classic** theme selected. (the **modern** theme is not supported by the jackett indexer).
2. then try upgrading to pre-release 0.12.895 which has the latest beyond-hd indexer fixes.
3. if you still get this error, try accessing your Jackett dashboard and removing the beyond-hd indexer from your active list with the trashbin icon, and adding it afresh from the **add indexer** page. 

let me know how you go.

**Comment by drizuid** [comment]
1) I've had the issue for over 2 weeks, so their theme migration is unrelated. 
2) as noted, i've tried the latest dev release, the current stable, and some older releases with the same result.
3) I do not actually make it to the point where jackett communicates to beyond-hd, the prompt for credentials never appears as it does for other trackers. Thus, there is no indexer to remove and re-add. Adding it is the issue.

**Comment by garfield69** [comment]
works for me.
if jackett does not get as far as presenting the indexer config, then something is delaying and timing out jackett's access https://beyond-hd.me/

are you able to access https://beyond-hd.me/ via browser on the same machine that is running jackett?
are you using a proxy/vpn ?

**Comment by garfield69** [comment]
on the same machine that is running Jackett, please open a terminal and post the output of 
`curl -vvv  https://beyond-hd.me/`
 and 
`openssl s_client -connect beyond-hd.me:443` 
thanks.

**Comment by drizuid** [comment]
Sorry for the delay, kids and Halloween. I had assumed the issue was related to `Debug The request path /api/v2.0/indexers/beyond-hd/config does not match a supported file type` but here is the output you've requested.

the curl command seems to work fine - https://pastebin.com/DBC1X156
but the openssl command simply hangs.. i'm going to do some work for a bit and come back and check it, i imagine this is the issue though. My other linux box seems to run this command without a hitch. Interestingly enough, that openssl connection works fine on  PTP (one of my working trackers)

**Comment by garfield69** [comment]
> Is there a flag to disable ipv6 for a specific tracker in jackett?

i'm reasonably certain there is no such a feature.
if you are not using ipv6 for anything else then perhaps disabling that service would help?
I don't know,  this is out of my area of expertise.
To any one out there who can contribute, feel free to volunteer and contribute to this ticket. Thanks.

**Comment by drizuid** [comment]
I do use IPv6, so disabling won't be possible on my side. I've opened a support ticket with BHD for them to look into the issue also. I imagine they just need to ensure things are setup properly to respond to ipv6 in addition to the working ipv4.  That said, I think the issue is a misconfiguration on the BHD side although a nice enhancement could be a checkbox to prevent ipv6 lookups. Since you guys do the lookups prior to displaying the box for input, i suppose it can't be per tracker which would be nice, but maybe a general option would be good either way. I'll close this and you guys can reopen if anything in here is relevant. thanks!
