### ISSUE TITLE
[REQ] fast-torrent.ru

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#6269]
It'd be nice to have this public tracker added.

**Comment by garfield69** [comment]
this site generates its results after the html is delivered using JS.
as such it cannot be processed by the Cardigann processor.
the indexer will need to be written in C#

**Comment by garfield69** [comment]
taking another look at this, with recent cardigann enhancements this may now be doable,

**Comment by garfield69** [comment]
Oh for f**k's sake!
It's single-title-multi-downloads, off the details page.
back to the C# queue.

**Comment by garfield69** [comment]
closing as stale.
