### ISSUE TITLE
[SCENETIME] Jackett doesnt search webdl category 

### ISSUE THREAD

**Issue by pegatron89** [Jackett/Jackett#6272]
I am using jackett mono version. Jackett works and searches scenetime but the category for Movies/Web-Rip is wrong so it wont search it. On scenetime the cat number is 22 but on https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/SceneTime.cs at line 63 the category number is 103 and should be (i think) 22

**Comment by garfield69** [comment]
corrected categories included in jackett pre-release 0.12.901
Not available in the stable jackett release until this is published at a later date.

**Comment by garfield69** [comment]
jackett 0.12.907
