### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://www2.yggtorrent.pe/ using form selector 

### ISSUE THREAD

**Issue by ThomasClemenceau** [Jackett/Jackett#6276]
**Jackett version**:  0.12.898

-------------------------------

I think everything is in the title... Can't access yggtorrent, I tried www2.yggtorrent.pe, www3, none worked...

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6086#issuecomment-538865977
