### ISSUE TITLE
c'ant bind to IP

### ISSUE THREAD

**Issue by albebert** [Jackett/Jackett#6278]
Hello

i try to set the listen address for jacket because it still bind to the ipv6 address.

tried to add a appsettings.json with : { "urls": "http://192.168.12.106:9117" }

in jackett folder but no luck : 

Oct 31 19:44:25 jackett jackett[1291]: Hosting environment: Production
Oct 31 19:44:25 jackett jackett[1291]: Content root path: /opt/Jackett/Content
Oct 31 19:44:25 jackett jackett[1291]: Now listening on: http://[::]:9117

jacket run on a debian 9.11 lxc container (hosted on proxmox)

**Comment by garfield69** [comment]
please provide the path where you saved the appsettings.json file.

**Comment by albebert** [comment]
/opt/Jackett

near the jacket executable file

**Comment by garfield69** [comment]
is that the same folder that contains the ServerConfig.json file?
usually these files reside in `~./config/Jackett`
```cli
garfield69@Ubuntu-VirtualBox:~$ cd ~/.config/Jackett
garfield69@Ubuntu-VirtualBox:~/.config/Jackett$ ls
DataProtection              log.txt.20191026.00000.txt
Indexers                    ServerConfig.json
log.txt                     updater.txt
log.txt.20190915.00000.txt  updater.txt.20191008.00000.txt
log.txt.20190915.00001.txt  updater.txt.20191015.00000.txt
log.txt.20191015.00000.txt  updater.txt.20191026.00000.txt
```
but maybe in your case they are in `/opt/Jackett/Content` ?

**Comment by albebert** [comment]
Ok, 

i put the file near the ServerConfig.json and it's works ! 

Thanks
