### ISSUE TITLE
[req] HDHouse

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#6287]
HDReactor renamed HDHouse #11250

HDReactor is a RUSSIAN Public Torrent Tracker for MOVIES / TV

Links:
- https://hdreactor.net
- https://hdreactor.club
- https://hdreactor.guru
- https://hdreactor.su
```
      - {id: 2001, cat: Movies/HD, desc: "Кино HD"}
      - {id: 5006, cat: Movies/HD, desc: "Кино 4K"}
      - {id: 2007, cat: Movies/Other, desc: "Анимация"}
      - {id: 2006, cat: TV/HD, desc: "Сериалы"}
      - {id: 5005, cat: TV/Sport, desc: "Спорт"}
      - {id: 2004, cat: Audio/Lossless, desc: "Музыка"}
      - {id: 2005, cat: PC/Games, desc: "Игры"}
      - {id: 2003, cat: XXX, desc: "18+"}
```
Example:
[https://hdreactor.net/index.php?do=search&subaction=search&showposts=1&story=2019&catlist[]=2001&catlist[]=2006](https://hdreactor.net/index.php?do=search&subaction=search&showposts=1&story=2019&catlist[]=2001&catlist[]=2006)

**Comment by garfield69** [comment]
try out jackett pre-release 0.12.916

**Comment by ilike2burnthing** [comment]
https://hdreactor.net - MySQL Error - Too many connections
https://hdreactor.club - MySQL Error - Too many connections
https://hdreactor.su - MySQL Error - Too many connections

**Comment by ilike2burnthing** [comment]
all back up

**Comment by ilike2burnthing** [comment]
https://hdreactor.net - ERR_NAME_NOT_RESOLVED
https://hdreactor.club - working
https://hdreactor.su - working

**Comment by garfield69** [comment]
HDHouse using DDOS-GUARD preventing Jackett access to browser results.

**Comment by ilike2burnthing** [comment]
It's working ok here with both site links.

**Comment by garfield69** [comment]
Ah OK. working for me too if I use hide.me

**Comment by garfield69** [comment]
https://hdreactor.net - working
https://hdreactor.club - working
https://hdreactor.su - gone
https://hdhouse.club/ gone

**Comment by garfield69** [comment]
hdhouse offline
https://hdreactor.club/ returns ERR_CONNECTION_REFUSED
https://hdreactor.net/ generates a ddos-guard error
![image](https://user-images.githubusercontent.com/6933240/153731665-af264e22-41f3-4995-afb5-e8e3b22a99b3.png)

**Comment by garfield69** [comment]
v0.20.708
