### ISSUE TITLE
[animebytes] Parse error: Can not convert Object to String. (Config)

### ISSUE THREAD

**Issue by WiseMMO** [Jackett/Jackett#6290]
It just won't update the indexer, which in turn obviously makes me not being able to use AnimeBytes as my anime indexer. I don't know if this is on their part but I thought I'd report it here anyway. I will contact the guys at AnimeBytes themselves to ask for more information on why this might happen.

Jackett Version 0.11.665.0

Let me know if you need more information

**Comment by garfield69** [comment]
your jackett 0.11.* is out of date. Upgrade to the latest jackett (0.12.*) and try again.
