### ISSUE TITLE
won't start after few days

### ISSUE THREAD

**Issue by albebert** [Jackett/Jackett#6291]
Hello,

after few days Jackett stop working. 

error on restart : Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.ComponentModel.Primitives, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'System.ComponentModel.Primitives, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

if i resync from the original archive it rework.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/5208#issuecomment-547709864
