### ISSUE TITLE
[beyond-hd] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by carlosabias** [Jackett/Jackett#6298]
I am being unable to add BeyondHD to jackett, I enabled 2FA and realized it's not supported, then I disabled it, logged out and in, and jackett will still say "An error occured while updating this indexer
Login Failed, got redirected."

Have restarted jackett, made sure 2FA is off, but issue persists. Any help is appreciated.

Jackett version **0.11.689.0**

**Comment by garfield69** [comment]
may be a temporary caching conflict.
try accessing the jackett dashboard and delete the active beyond-hd profile for the indexer with the trashbin icon.
add a new instance if the indexer from the add-indexer page and see if it works now.
