### ISSUE TITLE
Elite-Tracker error when I download the file 

### ISSUE THREAD

**Issue by valentinbourqui** [Jackett/Jackett#6300]
I can't download the with the link and Sonarr as the same issue : 

1: Login OK
2: Jackett Version 0.12.914.0
3: `Downloading torrent file for episode 'Mrs.Fletcher.S01E02.FRENCH.HDTV.x264-AMB3R' failed since it no longer exists (http://192.168.8.150:9117/dl/elitetracker/?jackett_apikey=(removed)&path=Q2ZESjhNcFA2WFNFTlZWS3ZrdGRoTDl4Zms4RV9YMHkxemxxbUJ0NnZBOHc5UTdaVkxBa19wbGFvS24zRXkwNHMtWWNMNXl5cHNsdmhhR2JTQlNjbURkdXB2cUR4QW1RVkNBOGtkUTJrd21MYTZvZU9PV0RhNVFLaS1sSmg1OFBkdzdtczl5LTBGVGUtMHpLTGlkNnhmUW5Ma1RhdDIzUGhJaXEya1NEc19CXzB5c1JLbjBlZ01NUjZBYkxYbjFwZWsxNE1B&file=Mrs.Fletcher.S01E02.FRENCH.HDTV.x264-AMB3R): HTTP request failed: [404:NotFound] [GET] at [http://192.168.8.150:9117/dl/elitetracker/?jackett_apikey=yntsgwxryyaov68unoillyi62n28n1jv&path=Q2ZESjhNcFA2WFNFTlZWS3ZrdGRoTDl4Zms4RV9YMHkxemxxbUJ0NnZBOHc5UTdaVkxBa19wbGFvS24zRXkwNHMtWWNMNXl5cHNsdmhhR2JTQlNjbURkdXB2cUR4QW1RVkNBOGtkUTJrd21MYTZvZU9PV0RhNVFLaS1sSmg1OFBkdzdtczl5LTBGVGUtMHpLTGlkNnhmUW5Ma1RhdDIzUGhJaXEya1NEc19CXzB5c1JLbjBlZ01NUjZBYkxYbjFwZWsxNE1B&file=Mrs.Fletcher.S01E02.FRENCH.HDTV.x264-AMB3R]`

Error log on Jackett : 

`Error downloading elitetracker https://elite-tracker.net/download.php?id=312654&type=ssl`

**Comment by garfield69** [comment]
just curious as to why you closed the ticket. Did you work out what the problem was?

**Comment by valentinbourqui** [comment]
It's was because ma ratio was under than 1 and download torrents were blocked. Maybe you can retrun the cause of why I can't download the torrent than this error.
