### ISSUE TITLE
[NewStudio.tv] Need return back authorisation 

### ISSUE THREAD

**Issue by imm21** [Jackett/Jackett#6305]
because without authorisation tracker shows "access denied, account disabled", sonarr see that as an error and can't manage files.

Thank you.

**Comment by garfield69** [comment]
Huh?
newstudio is a public site.
The Jackett indexer works for me.
But it was set to semi-private 25 days ago.
So assuming you are on the latest version of Jackett, you can try the following:
access your jackett dashboard, and use the trashbin icon to remove your newstudio indexer from the active list.
then add the indexer afresh with the wrench icon on the add-indexer page, and confirm that the indexer  config is not expecting you to enter a username and password.
Click OKAY and you should be good to go.
If however you are being shown a login then something is wrong and we need to dig deeper with you. 
Let me know how it goes.

**Comment by imm21** [comment]
It's old problem with that tracker - in transmission shows "access denied..." if files download without authorisation. It's not problem for me, it's problem for sonarr - files stay in queue. I'm update my jackett container once at month and month ago i have not this problem when the tracker was private. :)

![2019-11-07](https://user-images.githubusercontent.com/10806691/68359431-6a41de80-014e-11ea-9975-87217aa2c925.png)

![2019-11-07 (3)](https://user-images.githubusercontent.com/10806691/68359432-6a41de80-014e-11ea-892b-3c7e8e5de07c.png)

**Comment by garfield69** [comment]
oh I see. Well this has nothing to do with Jackett then.
if you want Sonarr to stop moaning, then access your transmission client, and edit the torrent's tracker list and remove the newstudio tracker.

**Comment by imm21** [comment]
But i need this tracker and when there was authorization everything worked as it should. Maybe there is a chance to make settings with authorization and without for this tracker?

**Comment by garfield69** [comment]
why do you need this tracker?
all the torrents are public so enabling DHT and PEX in transmission should get you all the peers you need.
If you really need some trackers you can always add some in manually 
```
udp://tracker.coppersurfer.tk:6969/announce
udp://tracker.leechers-paradise.org:6969/announce
udp://tracker.opentrackr.org:1337/announce
udp://9.rarbg.to:2710/announce
```
the above are a few of the most popular. plenty more at https://github.com/ngosang/trackerslist/blob/master/trackers_best.txt

>Maybe there is a chance to make settings with authorization and without for this tracker?

i don't understand the question.

**Comment by imm21** [comment]
It seems my knowledge of English is not enough :)

I don't have access to edit trackers in web transmission, and I will have to do it every time I distribute it with newstudio, which is very inconvenient.

> i don't understand the question.

There will be no errors if you use the old method with authorization on newstudio. Is it possible to do with authorization (as private as it was before) and without authorization (as now)? Both?

**Comment by garfield69** [comment]
Ah I see. No, the cardigann processor does not allow for an optional switch in an indexer config so that users can choose to login or not.
But what I can do is clone the newstudio indexer under a new name, with the login block enabled.
So beginning with Jackett pre-release 0.12.928 you will find NewstudioL
After upgrading, use your Jackett dashboard trashbin icon to delete the newstudio indexer, and add newstudiol in its place with the wrench icon, fill in your login details and you should be good to go.

**Comment by imm21** [comment]
Oh thank you very much you really helped a lot :)
