### ISSUE TITLE
[REQ] gamestorrents.tv

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#6310]
public game tracker

**Comment by garfield69** [comment]
try out jackett pre-release 0.12.929

**Comment by garfield69** [comment]
https://www.gamestorrents.nu/ returning cloudflare 522 Connection timed out
just me or is the site gone, broken, or moved to a new domain?

**Comment by ilike2burnthing** [comment]
https://www.gamestorrents.nu/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.gamestorrents.nu/ - Error establishing a database connection

**Comment by ilike2burnthing** [comment]
back up
