### ISSUE TITLE
Jackett v0.12.926.0 won't start on Ubuntu 18.04

### ISSUE THREAD

**Issue by MatthK** [Jackett/Jackett#6312]
Had installed Jackett a week ago and it was running fine. After a reboot of the system this morning, Jackett refused to start up again. Although there is a similar issue posted just recently, I believe this one is different.

When running 

> sudo systemctl status jackett.service 

I get the following:

>● jackett.service - Jackett Daemon
>   Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: enabled)
>   Active: activating (auto-restart) (Result: core-dump) since Fri 2019-11-08 12:17:21 HKT; 4s ago
>  Process: 32545 ExecStart=/opt/Jackett/jackett --NoRestart (code=dumped, signal=ABRT)
> Main PID: 32545 (code=dumped, signal=ABRT)

When I try to start it manually with 

> sudo /opt/Jackett/jackett --NoRestart

I get the following:

>11-08 12:18:45 Info Starting Jackett v0.12.926.0
>Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Threading.Tasks, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
>File name: ''System.Threading.Tasks, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a''
>   at Microsoft.Extensions.Configuration.ConfigurationProvider..ctor()
>   at Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider..ctor(MemoryConfigurationSource source)
>   at Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build(IConfigurationBuilder builder)
>   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
>   at Jackett.Server.Program.Main(String[] args) in /home/appveyor/projects/jackett/src/Jackett.Server/Program.cs:line 111
>
>
>Aborted

**Comment by MatthK** [comment]
I just discovered, that it seems to be due to an automatic update that happened last night:

When I run

>journalctl -u jackett.service 

it shows the following error messages during the update process.

>Nov 08 00:09:33 Ubuntu jackett[1445]: 11-08 00:09:33 Info Jackett variant: CoreLinuxAmdx64
>Nov 08 00:09:35 Ubuntu jackett[1445]: 11-08 00:09:35 Info New release found.  Current: v0.12.914 New: v0.12.926
>Nov 08 00:10:17 Ubuntu jackett[1445]: 11-08 00:10:17 Info Starting updater: /tmp/JackettUpdate-v0.12.926-637087686141239190/Jackett/JackettUpdater --Path "/opt/Jackett" --Type "Console" --Args " --NoRestart" --KillPids "1445" --NoRestart
>Nov 08 00:10:17 Ubuntu jackett[1445]: 11-08 00:10:17 Info Updater started process id: 16763
>Nov 08 00:10:17 Ubuntu jackett[1445]: 11-08 00:10:17 Info Jackett Updater v0.12.926.0
>Nov 08 00:10:17 Ubuntu jackett[1445]: 11-08 00:10:17 Info Options "--Path" "/opt/Jackett" "--Type" "Console" "--Args" " --NoRestart" "--KillPids" "1445" "--NoRestart"
>Nov 08 00:10:17 Ubuntu jackett[1445]: 11-08 00:10:17 Info Jackett variant: CoreLinuxAmdx64
>...
>Nov 08 00:10:19 Ubuntu jackett[1445]: 11-08 00:10:19 Info Copied System.Security.dll
>Nov 08 00:10:19 Ubuntu jackett[1445]: 11-08 00:10:19 Info Attempting to copy System.Security.Permissions.dll from source: /tmp/JackettUpdate-v0.12.926-637087686141239190/Jackett/System.Security.Permissions.dll to destination: /opt/Jackett/System.Security.Permissions.dll
>Nov 08 00:10:19 Ubuntu systemd[1]: jackett.service: Main process exited, code=killed, status=11/SEGV
>Nov 08 00:10:20 Ubuntu systemd[1]: jackett.service: Failed with result 'signal'.
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Copied System.Security.Permissions.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Attempting to copy System.Security.Principal.dll from source: /tmp/JackettUpdate-v0.12.926-637087686141239190/Jackett/System.Security.Principal.dll to destination: /opt/Jackett/System.Security.Principal.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Copied System.Security.Principal.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Attempting to copy System.Security.Principal.Windows.dll from source: /tmp/JackettUpdate-v0.12.926-637087686141239190/Jackett/System.Security.Principal.Windows.dll to destination: /opt/Jackett/System.Security.Principal.Windows.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Copied System.Security.Principal.Windows.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Attempting to copy System.Security.SecureString.dll from source: /tmp/JackettUpdate-v0.12.926-637087686141239190/Jackett/System.Security.SecureString.dll to destination: /opt/Jackett/System.Security.SecureString.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Copied System.Security.SecureString.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Attempting to copy System.ServiceModel.dll from source: /tmp/JackettUpdate-v0.12.926-637087686141239190/Jackett/System.ServiceModel.dll to destination: /opt/Jackett/System.ServiceModel.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Copied System.ServiceModel.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Attempting to copy System.ServiceModel.Web.dll from source: /tmp/JackettUpdate-v0.12.926-637087686141239190/Jackett/System.ServiceModel.Web.dll to destination: /opt/Jackett/System.ServiceModel.Web.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Copied System.ServiceModel.Web.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Attempting to copy System.ServiceProcess.dll from source: /tmp/JackettUpdate-v0.12.926-637087686141239190/Jackett/System.ServiceProcess.dll to destination: /opt/Jackett/System.ServiceProcess.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Copied System.ServiceProcess.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Attempting to copy System.ServiceProcess.ServiceController.dll from source: /tmp/JackettUpdate-v0.12.926-637087686141239190/Jackett/System.ServiceProcess.ServiceController.dll to destination: /opt/Jackett/System.ServiceProcess.ServiceController.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Copied System.ServiceProcess.ServiceController.dll
>Nov 08 00:10:20 Ubuntu jackett[1445]: 11-08 00:10:19 Info Attempting to copy System.Text.Encoding.CodePages.dll from source: /tmp/JackettUpdate-v0.12.926-637087686141239190/Jackett/System.Text.Encoding.CodePages.dll to destination: /opt/Jackett/System.Text.Encoding.CodePages.dll
>Nov 08 00:10:25 Ubuntu systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
>Nov 08 00:10:25 Ubuntu systemd[1]: jackett.service: Scheduled restart job, restart counter is at 1.
>Nov 08 00:10:25 Ubuntu systemd[1]: Stopped Jackett Daemon.
>Nov 08 00:10:25 Ubuntu systemd[1]: Started Jackett Daemon.
>Nov 08 00:10:25 Ubuntu jackett[16779]: 11-08 00:10:25 Info Starting Jackett v0.12.926.0
>Nov 08 00:10:25 Ubuntu jackett[16779]: Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Threading.Tasks, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
>Nov 08 00:10:25 Ubuntu jackett[16779]: File name: 'System.Threading.Tasks, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
>Nov 08 00:10:25 Ubuntu jackett[16779]:    at Microsoft.Extensions.Configuration.ConfigurationProvider..ctor()
>Nov 08 00:10:25 Ubuntu jackett[16779]:    at Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider..ctor(MemoryConfigurationSource source)
>Nov 08 00:10:25 Ubuntu jackett[16779]:    at Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build(IConfigurationBuilder builder)
>Nov 08 00:10:25 Ubuntu jackett[16779]:    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
>Nov 08 00:10:25 Ubuntu jackett[16779]:    at Jackett.Server.Program.Main(String[] args) in /home/appveyor/projects/jackett/src/Jackett.Server/Program.cs:line 111
>Nov 08 00:10:29 Ubuntu systemd[1]: jackett.service: Main process exited, code=dumped, status=6/ABRT
>Nov 08 00:10:29 Ubuntu systemd[1]: jackett.service: Failed with result 'core-dump'.
>Nov 08 00:10:35 Ubuntu systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
>Nov 08 00:10:35 Ubuntu systemd[1]: jackett.service: Scheduled restart job, restart counter is at 2.
>Nov 08 00:10:35 Ubuntu systemd[1]: Stopped Jackett Daemon.
>Nov 08 00:10:35 Ubuntu systemd[1]: Started Jackett Daemon.

And then it keeps trying to start Jackett but keeps failing.

**Comment by garfield69** [comment]
open a terminal and cd to the folder that has your jackett binaries /opt/Jackett
then do `sudo ./install_service_systemd.sh` to refresh the startup script.
if it works the service should be running again.

**Comment by garfield69** [comment]
and if that does not work, then install a full release again by following https://github.com/Jackett/Jackett#install-on-linux-amdx64
and see if that solves the issue.

**Comment by MatthK** [comment]
Thanks for your reply.

The refresh of the startup script didn't help, but the full install one worked.

**Comment by garfield69** [comment]
alright. 
did you run the systemd install script again after refreshing your files from the latest package?
if not then do so, to be sure that you are running on the latest systemd script.

then, if you do get this issue again, we will know there is a problem, because the latest script is supposed to prevent the updater-versus-service clash that must have occurred to cause the crash you first reported.

**Comment by MatthK** [comment]
Not quite sure what you mean. I downloaded the package, extracted it into /opt directory and then ran the 
>sudo ./install_service_systemd.sh
I guess that's what you mean, no?

**Comment by garfield69** [comment]
yes, exactly. thanks.

**Comment by pedrojvaz** [comment]
> and if that does not work, then install a full release again by following https://github.com/Jackett/Jackett#install-on-linux-amdx64
> and see if that solves the issue.

Just a +1 for the fix.  Jackett Version 0.12.1213.0 is running now
I'll monitor for future occurrences of the same issue
