### ISSUE TITLE
[REQ] EstrenosDivx

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#6314]
Spanish public movie, series and games tracker

https://edvok.com/
https://esdvx.com/
https://estrenosok.com/

**Comment by garfield69** [comment]
I have not been able to find a plain torrent listing that references one torrent per title.
the layout appears to be a single poster that links to a details page that contains multiple torrents related to the title.
as such, this site is not suitable for processing by the cardigann processor.
the indexer will need to be coded in c# by a c# dev volunteer.

**Comment by JorTurFer** [comment]
all are broken links

**Comment by ilike2burnthing** [comment]
working fine here

**Comment by garfield69** [comment]
https://edvok.com/ ERR_CONNECTION_REFUSED
https://esdvx.com/ ERR_CONNECTION_REFUSED
https://estrenosok.com/ ERR_CONNECTION_REFUSED

**Comment by ilike2burnthing** [comment]
HTTP equivalents of above links have a `THIS WEBSITE IS NO LONGER AVAILABLE DUE TO COPYRIGHT INFRINGEMENT` message from ACE, so yea it looks pretty dead.
