### ISSUE TITLE
Jackett segfaults on systemctl service restart

### ISSUE THREAD

**Issue by mirolm** [Jackett/Jackett#6315]
Jackett is a great and very useful software. Lately i noticed that it segfaults and message like below is writen in my dmesg log:

````
[  168.991536] jackett[568]: segfault at 10 ip 00007fe998b196c0 sp 00007ffe38a58778 error 4 in libpthread-2.28.so[7fe998b15000+f000]
[  168.991550] Code: ff 48 8d 0d c2 af 00 00 ba b1 01 00 00 48 8d 35 4b ae 00 00 48 8d 3d ff ae 00 00 e8 1a bb ff ff 8b 03 e9 45 fa ff ff 0f 1f 00 <8b> 47 10 89 c2 81 e2 7f 01 00 00 83 e0 7c 0f 85 9c 00 00 00 48 83
[ 6578.448688] jackett[2396]: segfault at 10 ip 00007fbf9d7056c0 sp 00007ffc7d69bad8 error 4 in libpthread-2.28.so[7fbf9d701000+f000]
[ 6578.448693] Code: ff 48 8d 0d c2 af 00 00 ba b1 01 00 00 48 8d 35 4b ae 00 00 48 8d 3d ff ae 00 00 e8 1a bb ff ff 8b 03 e9 45 fa ff ff 0f 1f 00 <8b> 47 10 89 c2 81 e2 7f 01 00 00 83 e0 7c 0f 85 9c 00 00 00 48 83
````

I managed to reproduce this and it usually happens when i stop or restart jackett with the systemd service. It happens too when jackett is auto-updated. There are no messages about the crash in the jackett logfile.

Aside from the messages jackett works fine without issues.

I'm using Debian 10 Buster x86_64 with kernel 5.2.17 from backports, and Jackett is latest stable version 0.12.926.

**Comment by garfield69** [comment]
going to need a linux c# dev volunteer to help with this one. segfault on this platform are beyond my area of expertise.
ping to any volunteers to help diagnose this one.

**Comment by ngosang** [comment]
@mirolm I think this was fixed long time ago. Please follow this instructions with latest Jackett version => https://github.com/Jackett/Jackett/issues/5208#issuecomment-547709864

**Comment by mirolm** [comment]
I updated to latest and will keep a look if it happens again. So far it is okay.

**Comment by jdsaraiva** [comment]
Hey, has this issue been fixed ?

**Comment by mirolm** [comment]
I think it is - have not seen the above errors in dmesg.
