### ISSUE TITLE
[shareisland] tracker migrated to a new platform

### ISSUE THREAD

**Issue by rafuz** [Jackett/Jackett#6321]
Shareisland tracker migrated to UNIT3D platform, I think it needs a new integration.
I can invite if needed.

**Comment by garfield69** [comment]
try out jackett pre-release 0.12.939
note: the site is still in flux as they continue to customise and adapt to their unit3d engine, so report any new categories or other changes that may need to be added to the jackett indexer.

**Comment by squaletta999** [comment]
I was registered in the old site, now it's close and it doesn't let me in. How do a get an invitation ?

**Comment by HDVinnie** [comment]
@squaletta999 this is not the place to ask that.
