### ISSUE TITLE
[shareisland] Login failed: Selector

### ISSUE THREAD

**Issue by gipasoft** [Jackett/Jackett#6322]
After server change, and after password resetting I obtain this error:
```
Login failed: Selector "a[href="logout.php"]" didn't match
```

I have update the url of indexer, the nre url is: `https://shareisland.org/torrents`

**Jackett version**: 0.12.926.0  
**Mono version**: NO MONO

-------------------------------

**Comment by garfield69** [comment]
shareisland have upgraded to using a unit3d web engine. try out jackett pre-release v0.12.939

**Comment by garfield69** [comment]
Oh, and in your case, reset the site link back to `https://shareisland.org/`

**Comment by gipasoft** [comment]
Ok now is all ok!
