### ISSUE TITLE
[shareisland] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#6331]
Jackett Version 0.12.947.0

This's the debug log:
https://pastebin.com/GApNYDMP

maybe is only temporary

**Comment by garfield69** [comment]
they just upgraded to unit3d 2.1.0
I have to apply the same minor changes I had to make for desireleasers
I'll do it after lunch. (my local time ;-b )

**Comment by garfield69** [comment]
09cc37f341bb393f723db6abf7b733e45f7ab75c
