### ISSUE TITLE
HD Dolby

### ISSUE THREAD

**Issue by iceyumao** [Jackett/Jackett#6334]
Please add a new Tracker
http://hddolby.com/

It is a Private Trackers with Nexusphp

**Comment by garfield69** [comment]
try out jackett pre-release 0.12.979

**Comment by ilike2burnthing** [comment]
https://www.hddolby.com/ - HTTP ERROR 403

**Comment by iceyuamao0510** [comment]
This is a membership website. You need cookies to access it

If there are no cookies, you need to use the account and passkey to convert the login entry

**Comment by ilike2burnthing** [comment]
Thanks @iceyuamao0510 

What does the login path look like if you don't have valid cookies? Apparently it's been a while since I last signed in.

Tried https://www.hddolby.com/login.php?username=MyUsername&password=MyPassword but no luck.

**Comment by garfield69** [comment]
https://hddolby.com/index.php returns Bad gateway Error code 502
uptrends reports 503 Service Temporarily Unavailable

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.hddolby.com/ - ERR_NAME_NOT_RESOLVED

**Comment by garfield69** [comment]
Re-opened as status has not been determined

**Comment by garfield69** [comment]
v0.21.1819

**Comment by gc4g40u6** [comment]
Can this please be added back? The site is now back online. Thanks.

**Comment by garfield69** [comment]
I'm seeing https://www.hddolby.com/index.php returning cloudflare Bad gateway Error code 502 
and all uptime checkpoints are returning 403 forbidden
are you using another domain?

**Comment by ilike2burnthing** [comment]
I'm getting 502 for a private/incognito window, but seemingly I still have valid cookies and can access the site file (although I need to set up 2FA). Will take a look at this.

**Comment by garfield69** [comment]
v0.21.2628
