### ISSUE TITLE
Force login on public tracker?

### ISSUE THREAD

**Issue by shohart** [Jackett/Jackett#6335]
so i added the underver.se tracker to jackett, and thus it is public, jacket does not allow me to login, but you actually can download all the torrent on this tracker only when you are logged in. So is it possible to force jacket to login to tracker?

Thank you.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by garfield69** [comment]
Huh.
if you click on the download link or the magnet link from the jackett dashboard search results from underverse you get the .torrent ot magnet delivered.
why do you need to login?

**Comment by shohart** [comment]
Actually it is not true. Sadly without login only magnet links are availiable. Torrents will fail

**Comment by garfield69** [comment]
@dimqua  you submitted commit 1fa421884d7426c99bdf99c8eeb780ab6798ab11 to switch underverse from semi-private to public.
did you test that .torrents work without a login?
I am inclined to reset it back to semi-private based on this ticket.... any comments?

**Comment by garfield69** [comment]
@shohart  I've made UnderverseL available with jackett pre-release 0.12.988 for those that want to use .torrents instead of magnets.

**Comment by dimqua** [comment]
@garfield69 I did, and I was able to download .torrents trough Jackett. That's probably because of Jackett used my login data, until I did clean reinstall. Now, it's indeed not possible. Sorry about that.

Two questions:
* Is it possible to hide .torrent download links for `underverse.yml` (not L)?
* Why don't we generate .torrent files based on hash from magnet links? In such cases.

**Comment by garfield69** [comment]
>Is it possible to hide .torrent download links for underverse.yml (not L)? Since they do not work.

yes, can do. I'll make an update.

>Why don't we generate .torrent files based on hash from magnet links? In such cases, which are quite common.

no idea. 
I just provide and maintain the cardigann indexers.
I am not involved with the jackett program design, or with implementing enhancements which require c# development.

you could raise a enhancement request and see of any c# dev will implement it.

**Comment by dimqua** [comment]
I just found that the same situation applies to [piratbit.yml](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/piratbit.yml) indexer, i.e. it's possible to get magnet-links without a login. Is it allowed to add "public" indexer for this site, as well?

**Comment by garfield69** [comment]
>I just found that the same situation applies to piratbit.yml indexer, i.e. it's possible to get magnet-links without a login. Is it allowed to add "public" indexer for this site, as well?

yes.
