### ISSUE TITLE
Multiple tracker failure error since long time

### ISSUE THREAD

**Issue by yogiee** [Jackett/Jackett#6336]
I have tried quite a few different things, including resetting my network as well as changing TLS settings in Internet Explorer control panel, but nothing seems to work.

On lot of trackers, I keep getting following error.

`Exception (1337x): An existing connection was forcibly closed by the remote host: An error occurred while sending the request.`

I've tried searching for this exact error and haven't really able to sort it out. You can review the debug log here: https://pastebin.com/9854TdwN

**Comment by garfield69** [comment]
the log shows you are using the same windows environment as I am [Microsoft Windows NT 6.2.9200.0 (64bit OS)  Environment version: 4.0.30319.42000] so I think we can exclude a jackett or shared library code issue 

your log shows you are getting these connection-closed errors intermittently, from indexers that worked before and after the problem when they are used again.
you also have several Could-not-create-SSL/TLS-secure-channel errors for a couple indexers that worked before and after.

this suggests to me that either: (1) you are using a proxy or vpn that has an unreliable service, or (2) you have some sort or network reliability issue with your ISP or ethernet hardware that is causing drop outs and disconnecting your sessions temporarily.

**Comment by yogiee** [comment]
Thanks... that sounds plausible. I had suspected pretty close to what you summarized, but probably needed to confirm my suspicion. Now I gotta troubleshoot and figure out what's causing the actual issue. Hopefully not ISP, cause that will be pretty much out of my control to fix.
