### ISSUE TITLE
[RuTracker] Request to Jackett server failed 

### ISSUE THREAD

**Issue by LithiumCFK** [Jackett/Jackett#6337]
When adding the RuTracker indexer, the error "Request to Jackett server failed" appears.
Reinstalling Jackett does not help.

![image](https://user-images.githubusercontent.com/38191359/68594056-d18dc480-04a7-11ea-94b6-e217279ae3c5.png)
![image](https://user-images.githubusercontent.com/38191359/68594077-de121d00-04a7-11ea-8de7-23d534b2b691.png)

**Comment by garfield69** [comment]
what platform are you running jackett on?
what version of jackett are you running?
works for me on windows 10 home, linux ubuntu18 and macos mojave.

**Comment by LithiumCFK** [comment]
jackett v0.12.981
windows 10 pro 1903 (18362.449)

**Comment by garfield69** [comment]
strange one. 
are you using a proxy or vpn?

**Comment by LithiumCFK** [comment]
No, I do not use them.
Prior to reinstalling the system, RuTracker worked

**Comment by garfield69** [comment]
well lets take a look at the log then.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. add rutracker
4. find the *log.txt* file in `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by LithiumCFK** [comment]
[log — back.txt](https://github.com/Jackett/Jackett/files/3848839/log.back.txt)

**Comment by garfield69** [comment]
you are getting
```
Basic connection closed: Unexpected transmission error. ---> System.IO.IOException: Cannot read data from the transport connection: The remote host forcibly terminated the existing connection. ---> System.Net.Sockets.SocketException: Remote host forcibly terminated an existing connection
```
this is usually nothing to do with jackett. i
it is usually something to do with the network, or with a vpn or proxy that got ssiconnected during the attempt to connect to rutracker.
or perhaps with a firewall that is blocking you WAN, or with a ad-blocker or anti-malware that has the rutracker address blacklisted.

**Comment by LithiumCFK** [comment]
@garfield69 
I want to enable openvpn only for Jackett, and all other applications worked through my regular network.

PS: I have windows

**Comment by garfield69** [comment]
I am sorry, but I am the wrong chap to answer this question. I have never used VPNs and know nothing about setting jackett up for use with VPN or proxy.
Ping to any volunteer that can answer the OP's question?
