### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on https://www3.yggtorrent.pe/ using form selector 

### ISSUE THREAD

**Issue by denzovirus** [Jackett/Jackett#6340]
hi all
Since recently the login form for Yggtorrent doesn't work anymore with Jackett.

**Comment by garfield69** [comment]
this is a duplicate of #6341
look to that ticket for updates on the yggtorrent issue, and a possible temporary bypass that may work for some users is also described there.
