### ISSUE TITLE
No form found on https://www3.yggtorrent.pe/ using form selector

### ISSUE THREAD

**Issue by denzovirus** [Jackett/Jackett#6341]
Hi all !
Today i have this issue anyone can help me ?
everything worked before..

My log:

Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www3.yggtorrent.pe/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 478
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 883
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 110
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73

**Comment by garfield69** [comment]
Here we go again. :-(
Jeesh I HATE this site, a never ending hassle to keep up with all the issues they constantly seem to cause ;-b

The problem appears similar to what happened a while back, where as you attempt to login you get a  307-temporary-redirect  from https to http and back to https again.
This breaks the cardigann processor and there is no solution so far.
The good news is that eventually (according to the last time this happened) they changed something on their servers to stop it doing this and jackett was able to start using the yggtorrent indexer again.

In the mean time some users have had success with using the YGGcookie indexer, but it is not guaranteed to work in all cases.

**Comment by tidus692** [comment]
If you have a better french (private) tracker I would take it Garfield69 :-P
Same issue here, I've also tried the cookie way, but none of the solutions seems to work

**Comment by garfield69** [comment]
try out yggcookie. the trick with ygg is that you have to go for it twice.
so user your browser on the same machine as jackett, login to yggtorrent, grab the full cookie string, and in the yggcookie config paste the string and click ok.
if you get an error (expect one the first time), click close, then edit again and click OKAY. it should take the second time.
this will let you carry on until yggtorrent gets sorted.

**Comment by garfield69** [comment]
the cookie string should look like this
```
__cfduid=d***redacted*****9; ga_=b***redacted****a; ygg_=r***redacted****b
```

**Comment by denzovirus** [comment]
unfortunately, even trying twice, the method with cookies does not work.

**Comment by yoyecros** [comment]
Hi,
Problem here with the two methods (YGGtorrent and YGGcookie)

With YGGtorrent : Login failed: No form found on https://www3.yggtorrent.pe/ using form selector #user-login: Parse error

With YGGcookie : Login Failed, got redirected. Try changing the indexer URL to http://www3.yggtorrent.pe/. Updated site link, please try again.: Parse error

**Comment by garfield69** [comment]
@yoyecros  https://github.com/Jackett/Jackett/issues/6341#issuecomment-552698910

**Comment by Robilol** [comment]
Same error
However the login form with id `login-form` exists on https://www3.yggtorrent.pe/

**Comment by Sayroyten** [comment]
same here :(

**Comment by freMea** [comment]
> Same error
> However the login form with id `login-form` exists on https://www3.yggtorrent.pe/

Yes and #user-login exists too. Same on https://www2.yggtorrent.pe

**Comment by Robilol** [comment]
> > Same error
> > However the login form with id `login-form` exists on https://www3.yggtorrent.pe/
> 
> Yes and #user-login exists too. Same on https://www2.yggtorrent.pe
> 
> Edit: the yggcookie tracker works. Use this instead.

I got an error with yggcookie

> Login Failed, got redirected. Try changing the indexer URL to http://www3.yggtorrent.pe/. Updated site link, please try again.

Which url are you using in conf ?

**Comment by freMea** [comment]
> Which url are you using in conf ?

![](https://i.snipboard.io/V3moE9.jpg)

**Comment by Robilol** [comment]
Not working for me, I don't know why 😢
![image](https://user-images.githubusercontent.com/23209925/68679405-17a65f00-0560-11ea-90e0-42ca6aa72e69.png)

**Comment by LeoShivas** [comment]
> Not working for me, I don't know why 😢
> ![image](https://user-images.githubusercontent.com/23209925/68679405-17a65f00-0560-11ea-90e0-42ca6aa72e69.png)

Same as you, I can't login too.

**Comment by kash-git** [comment]
It works for me (**YGGcookie**).

Use **https://www2.yggtorrent.pe/** for **Site Link** and **www2.yggtorrent.pe** for **Search**
If the interface does not work. Try to make changes directly into the file : 

- Stop Jackett
- Log in with your web brower on **https://www2.yggtorrent.pe/** and retrieve cookies
- Modify/Create the file **~/.config/Jackett/Indexers/yggcookie.json** (Below)
- Start Jackett

```json
[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://www2.yggtorrent.pe/"
  },
  {
    "id": "cookieheader",
    "type": "hiddendata",
    "name": "CookieHeader",
    "value": "__cfduid=XXXXXXXXXXXXXXXXXXXXXXXXXXX; ygg_=XXXXXXXXXXXXXXXXXXXXXXXXXXX; ca_=XXXXXXXXXXXXXXXXXXXXXXXXXXX"
  },
  {
    "id": "lasterror",
    "type": "hiddendata",
    "name": "LastError",
    "value": null
  },
  {
    "id": "cookie",
    "type": "inputstring",
    "name": "Cookie",
    "value": "__cfduid=XXXXXXXXXXXXXXXXXXXXXXXXXXX; ga_=XXXXXXXXXXXXXXXXXXXXXXXXXXX; ygg_=XXXXXXXXXXXXXXXXXXXXXXXXXXX"
  },
  {
    "id": "howtogetthecookie",
    "type": "displayinfo",
    "name": "How to get the Cookie",
    "value": "<ol><li>Login to this tracker in your browser<li>Open the <b>DevTools</b> panel by pressing <b>F12</b><li>Select the <b>Network</b> tab<li>Click on the <b>Doc</b> button<li>Refresh the page by pressing <b>F5</b><li>Select the <b>Headers</b> tab<li>Find 'cookie:' in the <b>Request Headers</b> section<li>Copy & paste the whole cookie string to here</ol>"
  },
  {
    "id": "searchanddownloadurl",
    "type": "inputstring",
    "name": "Search and download URL",
    "value": "www2.yggtorrent.pe"
  },
  {
    "id": "catégorie",
    "type": "inputselect",
    "name": "Catégorie",
    "value": "2145",
    "options": {
      "all": "Tous",
      "2145": "Film/Vidéo",
      "2139": "Audio",
      "2144": "Application",
      "2142": "Jeu vidéo",
      "2140": "eBook",
      "2141": "Emulation",
      "2143": "GPS",
      "2188": "XXX"
    }
  },
  {
    "id": "trytonormalizereleasesnamesbymovingyearafterthetitle",
    "type": "inputbool",
    "name": "Try to normalize releases names by moving year after the title",
    "value": true
  },
  {
    "id": "replacemultibyanotherlanguageinreleasename",
    "type": "inputbool",
    "name": "Replace MULTI by another language in release name",
    "value": true
  },
  {
    "id": "replacemultibythislanguage",
    "type": "inputselect",
    "name": "Replace MULTI by this language",
    "value": "MULTI.FRENCH",
    "options": {
      "FRENCH": "FRENCH",
      "MULTI.FRENCH": "MULTI.FRENCH",
      "ENGLISH": "ENGLISH",
      "MULTI.ENGLISH": "MULTI.ENGLISH",
      "VOSTFR": "VOSTFR",
      "MULTI.VOSTFR": "MULTI.VOSTFR"
    }
  },
  {
    "id": "replacevostfrwithenglish",
    "type": "inputbool",
    "name": "Replace VOSTFR with ENGLISH",
    "value": false
  },
  {
    "id": "enhancesonarrcompatibilitywithanimebyrenamingepisode(xxxtoexxx).worksonlyifepisodeisattheendofthequery.candisturbmoviessearch.(backtothefuture3->backtothefuturee3)",
    "type": "inputbool",
    "name": "Enhance sonarr compatibility with anime by renaming episode (xxx to exxx). Works only if episode is at the end of the query. Can disturb movies search. (back to the future 3 -> back to the future e3)",
    "value": false
  },
  {
    "id": "usebetasearchengineurl(lessrestrictive)/sonarrv3fullseriessearchnew",
    "type": "inputbool",
    "name": "Use Beta Search engine URL (Less restrictive) / SonarrV3 Full Series Search NEW",
    "value": false
  }
]
```

**Comment by LeoShivas** [comment]
After a fresh stop/start jackett, the YggCookie works for me. No need editing conf files.

**Comment by sebguilbaud** [comment]
search works after a stop/start, but not download

**Comment by kash-git** [comment]
> search works after a stop/start, but not download

Use https://github.com/Jackett/Jackett/issues/6341#issuecomment-552916575

**Comment by tidus692** [comment]
> 
> 
> It works for me (**YGGcookie**).
> 
> Use **https://www2.yggtorrent.pe/** for **Site Link** and **www2.yggtorrent.pe** for **Search**
> If the interface does not work. Try to make changes directly into the file :
> 
>     * Stop Jackett
> 
>     * Log in with your web brower on **https://www2.yggtorrent.pe/** and retrieve cookies
> 
>     * Modify/Create the file **~/.config/Jackett/Indexers/yggcookie.json** (Below)
> 
>     * Start Jackett
> 
>     * Test
> 
> 
> ![image](https://user-images.githubusercontent.com/54643433/68680331-7c959100-052f-11ea-9ff9-fab95614af05.png)
> 
> ```json
> [
>   {
>     "id": "sitelink",
>     "type": "inputstring",
>     "name": "Site Link",
>     "value": "https://www2.yggtorrent.pe/"
>   },
>   {
>     "id": "cookieheader",
>     "type": "hiddendata",
>     "name": "CookieHeader",
>     "value": "__cfduid=XXXXXXXXXXXXXXXXXXXXXXXXXXX; ygg_=XXXXXXXXXXXXXXXXXXXXXXXXXXX; ca_=XXXXXXXXXXXXXXXXXXXXXXXXXXX"
>   },
>   {
>     "id": "lasterror",
>     "type": "hiddendata",
>     "name": "LastError",
>     "value": null
>   },
>   {
>     "id": "cookie",
>     "type": "inputstring",
>     "name": "Cookie",
>     "value": "__cfduid=XXXXXXXXXXXXXXXXXXXXXXXXXXX; ga_=XXXXXXXXXXXXXXXXXXXXXXXXXXX; ygg_=XXXXXXXXXXXXXXXXXXXXXXXXXXX"
>   },
>   {
>     "id": "howtogetthecookie",
>     "type": "displayinfo",
>     "name": "How to get the Cookie",
>     "value": "<ol><li>Login to this tracker in your browser<li>Open the <b>DevTools</b> panel by pressing <b>F12</b><li>Select the <b>Network</b> tab<li>Click on the <b>Doc</b> button<li>Refresh the page by pressing <b>F5</b><li>Select the <b>Headers</b> tab<li>Find 'cookie:' in the <b>Request Headers</b> section<li>Copy & paste the whole cookie string to here</ol>"
>   },
>   {
>     "id": "searchanddownloadurl",
>     "type": "inputstring",
>     "name": "Search and download URL",
>     "value": "www2.yggtorrent.pe"
>   },
>   {
>     "id": "catégorie",
>     "type": "inputselect",
>     "name": "Catégorie",
>     "value": "2145",
>     "options": {
>       "all": "Tous",
>       "2145": "Film/Vidéo",
>       "2139": "Audio",
>       "2144": "Application",
>       "2142": "Jeu vidéo",
>       "2140": "eBook",
>       "2141": "Emulation",
>       "2143": "GPS",
>       "2188": "XXX"
>     }
>   },
>   {
>     "id": "trytonormalizereleasesnamesbymovingyearafterthetitle",
>     "type": "inputbool",
>     "name": "Try to normalize releases names by moving year after the title",
>     "value": true
>   },
>   {
>     "id": "replacemultibyanotherlanguageinreleasename",
>     "type": "inputbool",
>     "name": "Replace MULTI by another language in release name",
>     "value": true
>   },
>   {
>     "id": "replacemultibythislanguage",
>     "type": "inputselect",
>     "name": "Replace MULTI by this language",
>     "value": "MULTI.FRENCH",
>     "options": {
>       "FRENCH": "FRENCH",
>       "MULTI.FRENCH": "MULTI.FRENCH",
>       "ENGLISH": "ENGLISH",
>       "MULTI.ENGLISH": "MULTI.ENGLISH",
>       "VOSTFR": "VOSTFR",
>       "MULTI.VOSTFR": "MULTI.VOSTFR"
>     }
>   },
>   {
>     "id": "replacevostfrwithenglish",
>     "type": "inputbool",
>     "name": "Replace VOSTFR with ENGLISH",
>     "value": false
>   },
>   {
>     "id": "enhancesonarrcompatibilitywithanimebyrenamingepisode(xxxtoexxx).worksonlyifepisodeisattheendofthequery.candisturbmoviessearch.(backtothefuture3->backtothefuturee3)",
>     "type": "inputbool",
>     "name": "Enhance sonarr compatibility with anime by renaming episode (xxx to exxx). Works only if episode is at the end of the query. Can disturb movies search. (back to the future 3 -> back to the future e3)",
>     "value": false
>   },
>   {
>     "id": "usebetasearchengineurl(lessrestrictive)/sonarrv3fullseriessearchnew",
>     "type": "inputbool",
>     "name": "Use Beta Search engine URL (Less restrictive) / SonarrV3 Full Series Search NEW",
>     "value": false
>   }
> ]
> ```

Thank you for your help, but actually, this seems to work only on "local" Jackett. On my distant server, I still have the error : 
(For info, I logged in with my computer to Yggtorrent, catched the cookie header and I did your solution, so stopped the Jackett server, updated the json file with the cookie + updated the url in this file. Then I've restarted the Jackett server, Test button was checked at first, but after clicking, I got this error)

> Exception (yggcookie): Got redirected to another domain. Try changing the indexer URL to http://www2.yggtorrent.pe/. Updated site link, please try again.: Parse error

**Comment by sebguilbaud** [comment]
> > search works after a stop/start, but not download
> 
> Use [#6341 (comment)](https://github.com/Jackett/Jackett/issues/6341#issuecomment-552916575)

already done, "test" button works, log from jackett tells "11-12 16:00:55 Info Found 100 releases from YGGcookie" but when Medusa tries to download releases from torznab feed, logfile contains "11-12 16:03:26 Error Vous devez vous connecter pour télécharger un torrent "

**Comment by garfield69** [comment]
the YGGTorrent website has changed their domain to www5.
And you should be able to get the Jackett YGGTorrent Indexer working again as follows:  
1. access your jackett dashboard and use the wrench icon to edit your YGGTorrent indexer config.
2. set the **Site Link** to `https://www5.yggtorrent.pe/` and 
3. set the **Search and download URL** to `www2.yggtorrent.pe`
4. Click **OKAY**
5. if you get an error, click **CLOSE** then edit again and click OKAY. it should save the second time.

Works for me. See if it works for you.

**Comment by LeoShivas** [comment]
> the YGGTorrent website has changed their domain to www5.
> And you should be able to get the Jackett YGGTorrent Indexer working again as follows:
> 
> 1. access your jackett dashboard and use the wrench icon to edit your YGGTorrent indexer config.
> 2. set the **Site Link** to `https://www5.yggtorrent.pe/` and
> 3. set the **Search and download URL** to `www2.yggtorrent.pe`
> 4. Click **OKAY**
> 5. if you get an error, click **CLOSE** then edit again and click OKAY. it should save the second time.
> 
> Works for me. See if it works for you.



**Sorry, it doesn't work for me :**


![image](https://user-images.githubusercontent.com/28844182/68743649-33a71080-05f3-11ea-9f92-98160806d6d5.png)

**Comment by sebguilbaud** [comment]
download works again, thanks a lot ! (yggcookie method)

**Comment by garfield69** [comment]
@LeoShivas  try again. 
or upgrade to jackett 0.12.990, trashbin your yggtorrent indexer, add it afresh, and see what happens.

if it still does not work for you then I need more info to diagnose your particular issue, so:
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by LeoShivas** [comment]
> @LeoShivas try again.
> or upgrade to jackett 0.12.990, trashbin your yggtorrent indexer, add it afresh, and see what happens.
> 
> if it still does not work for you then I need more info to diagnose your particular issue, so:
> Please provide the **full enhanced log** file.
> 
> 1. scroll down to the bottom of the Jackett Dashboard and _tick_ the _enhanced Logging_ checkbox
> 2. scroll up a bit and _click_ on the _apply server settings_ button
> 3. repeat the test
> 4. find the _log.txt_ file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
> 5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
> 6. save, then drag-drop it here for us to take a look at.
> 
> Thanks.

You're right, I updated from 0.12.981.0 to 0.12.990.0 and now it works ! Great thanls !!

**Comment by DaGreenX** [comment]
thanks ! yggcookie works for me  on MacOS Safari

**Comment by bentux** [comment]
Thanks it's ok now.
You may probably have to try https://www.sharewood.tv/ that's an new and not bad tracker

**Comment by mattthhdp** [comment]
@LeoShivas method did solve the issus for me
