### ISSUE TITLE
[REQ] Mkvhub

### ISSUE THREAD

**Issue by Theli93** [Jackett/Jackett#6350]
Public index: [www.mkvhub.com](url)

**Comment by garfield69** [comment]
does this site have a search page?
please provide a link to the search page.
if there is none then this site will not be suitable for use with jackett.

**Comment by Theli93** [comment]
There isn't a "search page" per se, but there is a search box on any incividual item page (past the landing page).

Is this what you are after?
`https://www.mkvhub.com/?s=`

**Comment by garfield69** [comment]
this website is not compatible with the cardigann processor as the details page for each search results have one or more magnets.
for example, *the purge S02* leads to a details page with magnets for 
*the purge s02e01*, *the purge s02e01*, etc.

this site will require the jackett indexer to be written in c#

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
