### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on https://www3.yggtorrent.pe/ using form selector 

### ISSUE THREAD

**Issue by computman007** [Jackett/Jackett#6356]
Error : An error occured while testing this indexer
Exception (yggtorrent): Login failed: No form found on https://www3.yggtorrent.pe/ using form selector #user-login: Parse error

I can connect on the tracker
The form user-login exist on the page

Jackett Version 0.12.981.0

**Comment by computman007** [comment]
issue 6339 is now closed and issue not solved

**Comment by garfield69** [comment]
this is a duplicate of #6341
look to that ticket for updates on the yggtorrent issue, and a possible temporary bypass that may work for some users is also described there.
