### ISSUE TITLE
[torrentbytes] The SSL connection could not be established, see inner exception.: Authentication failed, see inner exception. (Config)

### ISSUE THREAD

**Issue by IGhostv12I** [Jackett/Jackett#6359]
Hello ,

I'm a self taught debian user and looking for a solution to add this indexer , advice would be appreciated.
Using Debian 10 , OpenSSL 1.1.1d 
Jackett Version 0.12.990.0

openssl s_client -connect www.torrentbytes.net:443
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = www.torrentbytes.net
verify return:1
139755856913536:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../ssl/statem/statem_clnt.c:2150:
---
Certificate chain
 0 s:CN = www.torrentbytes.net
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFczCCBFugAwIBAgISA46ldju7PVvJbHXyu1EIg1j+MA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xOTA5MjExNzQzMzdaFw0x
OTEyMjAxNzQzMzdaMB8xHTAbBgNVBAMTFHd3dy50b3JyZW50Ynl0ZXMubmV0MIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwpXMK9z4Td8htKFeZJWNDZ2w
zIdf4pK8Qj9zYb8NLnefcLJtFeyDj/iF8r/y7A4jrjAo4vKm3HkoXl2If03d5rLz
8UE1/iZ+QmvKO0Zv00bhh5mwcSEaAzrUaMghjSlU3qyqILvtQtAE1OUGrma85RID
zXJObSjGHgy0oKbfH2OYbJ6R/so+Ou1sYMv+pKm1WBfquixI8VTasi9hRVUUShBI
TAeZbVdh0m2C6iJ8wNW1Dyi96No8slrql/cB7LCft7e17LoGVx0iMQRv8wNQSwwE
IyWKdCV73fDiEm6Vm4Q+CJ98fFu9i81gRk4f5TGQmm/Jdn9KbwUbl8efPst2OwID
AQABo4ICfDCCAngwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMB
BggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQv42rb8vCp/so/zBUF
6NxWj07i/zAfBgNVHSMEGDAWgBSoSmpjBH3duubRObemRWXv86jsoTBvBggrBgEF
BQcBAQRjMGEwLgYIKwYBBQUHMAGGImh0dHA6Ly9vY3NwLmludC14My5sZXRzZW5j
cnlwdC5vcmcwLwYIKwYBBQUHMAKGI2h0dHA6Ly9jZXJ0LmludC14My5sZXRzZW5j
cnlwdC5vcmcvMDEGA1UdEQQqMCiCEHRvcnJlbnRieXRlcy5uZXSCFHd3dy50b3Jy
ZW50Ynl0ZXMubmV0MEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEB
MCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBBQYK
KwYBBAHWeQIEAgSB9gSB8wDxAHcAY/Lbzeg7zCzPC3KEJ1drM6SNYXePvXWmOLHH
aFRL2I0AAAFtVSL1igAABAMASDBGAiEA5ZU0eL1aO4tyDIY86ikZh3PfrvpVwGSW
EEShDYkmlaECIQDiD2F6MwgDpR3FTHVBVFwz4yHn2Udv8jiVbBUB82BExQB2AOJp
S64m6OlACeiGG7Y7g9Q+5/50iPukjyiTAZ3d8dv+AAABbVUi92AAAAQDAEcwRQIg
WTuCmL7zOK/tbk8W0VKzvEQjjdlxFqoNZBaMW5FCeI8CIQD1Rd8i7EAZvuSDQbBy
IEPa63pLA40Rp+R4keYaK1uo/DANBgkqhkiG9w0BAQsFAAOCAQEAHTSx/V9NSqYP
8+nuCwieY+bIdNFsUAIUSFEavz4qy1WKqX2GgPjoMR+zmOUuwEXHTbGKirHP0z3h
OVlLVRAtTBPw62+OtksC9csEgQ3ec5BzhfL/t8ieeIEjER4SfZWTETS1wK2pDoNd
oNKGK4BJDW0gIkPT7r3rMoWdBQ/k+0mxqiF2DOpFiGcB9lHqpmgvhvTiSqFH7JtN
xMp9TrFRZVAMROfkFuuu/LA8GslshzUiCJ9oWo+9SSz61OJnNulfYTt8zm2WVCr2
a8D5vTNBqablhqL7xqmJFZSl0j1/fvZVt3SEgJSV58rrdI1arC/yBRWH7Hc1MNps
baFe1p6O3g==
-----END CERTIFICATE-----
subject=CN = www.torrentbytes.net

issuer=C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3

---
No client certificate CA names sent
---
SSL handshake has read 3185 bytes and written 319 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1573646049
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no

**Comment by garfield69** [comment]
which jackett install package are you using?

**Comment by IGhostv12I** [comment]
I used the latest Jackett.Binaries.LinuxAMDx64.tar.gz. and followed the instructions. Several other indexers work fine.

**Comment by garfield69** [comment]
the linuxamdx64 package does not use mono, its on the .net core, which is good as mono has always been problematic with jackett.

But looks like the problem may be with your openssl 1.1.1d
found a similar hit on google with error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small at
https://www.howtoforge.com/community/threads/openssl-broke-with-1-1-1d-0-deb10u1.82964/

while its for a different certificate, it is the same symptoms, ie. working before now broken.
they bypassed the issue temporarily by going back to openssl 1.1.1c

**Comment by IGhostv12I** [comment]
Very interesting , thank you. I will try that and see if it helps.

**Comment by Jorman** [comment]
I'm running debian buster and I fixed this with a modified version of openssl 1.1.1d
Using this https://packages.sury.org/php/README.txt
So added the repository and:
apt-update, then apt-upgrade to upgrade openssl 1.1.1d-1+0~20191009.15+debian10~1.gbpd6badf
Now torrentbytes is working again

**Comment by IGhostv12I** [comment]
Hello Jorman ,

Confirmed , this made it work again.
Thanks alot for your answer and visual support , awesome.
