### ISSUE TITLE
underverseL less search results than underverse

### ISSUE THREAD

**Issue by shohart** [Jackett/Jackett#6360]
Jackett Version 0.12.990.0
So using underverseL allows to download torrents, but when searching underverseL there are significantly less results in same category/word search  than in underverse-public.

**Comment by garfield69** [comment]
give me an example of what you a searching for so I can compare.

**Comment by shohart** [comment]
okay, so here is example in underverse-public
![public](https://user-images.githubusercontent.com/2156041/68807246-2d0aae80-0670-11ea-86cb-44b8c5792cc5.JPG)
and this is underverseL
![unL](https://user-images.githubusercontent.com/2156041/68807269-37c54380-0670-11ea-9b1c-2e012b3be695.JPG)
situation is the same if i try to search keywords without using a category

**Comment by garfield69** [comment]
interesting.
![image](https://user-images.githubusercontent.com/6933240/68814250-2bc39b00-06dd-11ea-8c56-24bd6744231f.png)
![image](https://user-images.githubusercontent.com/6933240/68814277-3bdb7a80-06dd-11ea-848a-97907376ae1e.png)

I get exactly the same results from both indexers.

which probably means this may have something to do with your underverse account settings?
If you cannot figure out what is going on, then turn on the enhanced logging for the **underverseL** search and post the log and I can compare it with mine.
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the search for UnderverseL
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by shohart** [comment]
Thank you for a quick response! 
I did nothing to my account details for underverse, and i can see all the results, searching tracker via browser.
so here is the [log.txt](https://github.com/Jackett/Jackett/files/3844004/log.txt)
in is full of lines like this: 
```
at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1489 
2019-11-14 02:01:14.2606 Error CardigannIndexer (underversel): Error while parsing row '

```

**Comment by garfield69** [comment]
yes, your a/c on the site is more elevated than mine. I get genmed tags in my html, you have seedmed tags in yours.
I'll update the indexer later today to cope with both a/c states and post here when the update is ready.

**Comment by garfield69** [comment]
try out jackett pre-release 0.12.991

**Comment by shohart** [comment]
oh thank you!
