### ISSUE TITLE
[cpasbien] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by ejalal** [Jackett/Jackett#6365]
Got an error while testing cpabien indexer

`System.Exception: Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 227    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 143    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73
`

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
Jackett Version 0.12.990.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:
Installed from docker image linuxserver/jackett:latest

-------------------------------

**Comment by garfield69** [comment]
works for me.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by ejalal** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/3848088/log.txt)
Log file attached

**Comment by ejalal** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/3848094/log.txt)
Log file attached

**Comment by garfield69** [comment]
from your browser access your jackett dashboard and edit the cpasbien indexer config with the wrench icon.
change the **Site Link** to `https://vww.cpasbien-fr.fr/` and click OKAY.
test and report back ;-)

**Comment by ejalal** [comment]
Interesting, when I edit cpabien tracker it says https://www.gktorrent.biz/

I'm 100% sure I didn't change it

**Comment by garfield69** [comment]
the indexer has a followredirect clause to allow it to keep up with the web sites frequent domain changes automatically.
however, the last domain https://www.cpasbien.lol/ was taken over by a competitor and redirects to gktorrent which is a completely different site hence the no-results-found error.
