### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Name or service not known: Name or service not known (Test)

### ISSUE THREAD

**Issue by PixLzzz** [Jackett/Jackett#6367]
Hi, 
as ygg changed their domain name, i wonder if it changed something on my jackett configuration as it doesn't work anymore now. 
How can i find the search and download url of Ygg ? Thank you for your help

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6341#issuecomment-553271000
