### ISSUE TITLE
[720pier] Can't add indexer

### ISSUE THREAD

**Issue by nbo21** [Jackett/Jackett#6368]
When trying to add the indexer I get this error message: `An error occurred while updating this indexer`

Jackett Version 0.12.993.0 

Full enhanced log: [log.txt](https://github.com/Jackett/Jackett/files/3848753/log.txt)

The indexer worked for me in the past and I can log in to the site without any problems.

**Comment by garfield69** [comment]
yes, this is happening for me too. clearly something has changed at 720pier 
I'll see if I can figure out what is breaking the jackett indexer for this site.

**Comment by garfield69** [comment]
urg. I cannot figure it out, and on top of that,  the 720pier indexer is written in c#, not my specialty :-(

@koper89,  as the author of this indexer, could you please take a look at this issue and perhaps provide a fix?
Thanks.

**Comment by cadatoiva** [comment]
Looking at the website, they've added some autologin blockers that require you to load the login page first. Specifically a `form_token` and `creation_time` data values are needed. These are generated server side each time you navigate to login. Shouldn't be too hard to fix, just have to download the login page once to get valid token data and add it to post data when submitting the login. I'm looking to see how that can be done to fix this tracker and will post a fix.

**Comment by garfield69** [comment]
jackett 0.12.1354

**Comment by bingoxo** [comment]
Still same issue
and i'm on  0.12.1384.0

**Comment by garfield69** [comment]
@bingoxo 
works for me.

perhaps there is a caching issue? try this:
1. access your jackett dashboard and trashbin the 720pier indexer from the active list.
2. reboot your computer
3. add the indexer anew.
