### ISSUE TITLE
[Greek legends] Not seen anywhere

### ISSUE THREAD

**Issue by vavavr00m** [Jackett/Jackett#6369]
This is a recently added tracker and it isn't showing up in Add trackers while nntt and yggtorrents are already in.

**Comment by garfield69** [comment]
go to the add-indexers page and type in greek and there it is.
![image](https://user-images.githubusercontent.com/6933240/68919523-51cd6600-07d7-11ea-90aa-68f94d82c121.png)
been available since jackett v0.12.987

**Comment by vavavr00m** [comment]
Jackett Version 0.12.993.0

![image](https://user-images.githubusercontent.com/4675132/68920082-2171d180-07af-11ea-82b1-2e1e600a79be.png)

**Comment by garfield69** [comment]
are you running jackett on a linux platform by any chance?

**Comment by vavavr00m** [comment]
Windows 10

**Comment by garfield69** [comment]
strange.
have you perhaps already added it and it sitting in your jackett dashboard active list?
once added it does not show up in the add-indexers page.

**Comment by vavavr00m** [comment]
No, I haven't. You can see the list from the SS. EZTV then Horrible Subs.

**Comment by garfield69** [comment]
Hmm.
I presume you have been upgrading via the auto updater... are you short on disk space on the c drive, or had some event during the updater run that interfered with the updater?
have you tried a full manual update from https://github.com/Jackett/Jackett/releases/download/v0.12.993/Jackett.Installer.Windows.exe ?

**Comment by garfield69** [comment]
remember that if you are running jackett as a service, shutdown the service down before running the manual install.

And if you have been launching jackett manually, then this could be a possible reason for the update failing, if you happen to launch jackett manually while the updater was running they could clash....

**Comment by vavavr00m** [comment]
Still have space in c drive. I tried both manually updating and auto-updating. I also reinstalled (multiple times and after you said it) and used the portable version.

**Comment by garfield69** [comment]
ok. lets see the log. 
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. find the *log.txt* file in `%ProgramData%\Jackett`)
4. and  drag-drop it here for us to take a look at.

Thanks.

**Comment by garfield69** [comment]
oh, and if you have the updater.txt drop that here too thanks.

**Comment by garfield69** [comment]
Ah. found the problem. 
my bad!
the indexer has been incorrectly named greeklegends.yaml. should be greeklegends.yml

i'll post a fix presently. 
sorry about that.

**Comment by vavavr00m** [comment]
Don't need the log/updater txt anymore?

**Comment by garfield69** [comment]
correct.
try out jackett pre-release 0.12.994

**Comment by vavavr00m** [comment]
Thank you for the quick fix. Confirming it works.

**Comment by garfield69** [comment]
https://greeklegends.net/ returning File not found.
just me or is the site broken, gone, moved to a new domain?

**Comment by vavavr00m** [comment]
It's the same for me. No idea if it moved to a new domain. It was working before February.

**Comment by dimqua** [comment]
Pending for removal?

**Comment by garfield69** [comment]
its been a month since the site went offline. I am going to remove the indexer.
In the event they return we can always add them back.
