### ISSUE TITLE
[iptorrents] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by plotikai** [Jackett/Jackett#6376]
I am having issues connecting to my only tracker iptorrents

https://pastebin.com/9X2VdhKL

Jackett 0.11.43-8
Mono 5.18.0.240-12

This just started today for whatever reason, jackett is telling me theres a standalone version but im using synology and this is the latest jackett version I can install from the community packages.

I've got a novice level of understanding on this so any help offered please list steps and link howtos.

**Comment by plotikai** [comment]
I should also point out DSM version 6.2.2-24922 update 4

**Comment by garfield69** [comment]
how come you closed the ticket, you got it working again?

**Comment by plotikai** [comment]
> how come you closed the ticket, you got it working again?

Yea. I just reinstalled the package through the synology community and got it up and running again, the dashboard still tells me to upgrade to the standalone, but its working fine now
