### ISSUE TITLE
Torrent-Syndikat some categories not working

### ISSUE THREAD

**Issue by Mitnick84** [Jackett/Jackett#6378]
Hi, since viewe hours  my television categories dont work anymore. I think TS has anything changed.

My settings are: 100049,100053,100043,100054,100030,100055,100044,100056,100020

Movie categories are working!

Jackett Version is: 0.12.1000.0

**Comment by garfield69** [comment]
I dont have a login for this private site so if you want to help me load any changes to the categories I need you to do the following:
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. access the jackett dashboard with your browser and click on the TEST for torrent-syndikat
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by wasgehthierab** [comment]
Hey @Mitnick84,

how did you get it to work in the first place. I get an Error:


```An error occured while testing this indexer
Exception (torrentsyndikat): Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'): Parse error
Click here to open an issue on GitHub for this indexer.```
