### ISSUE TITLE
[REQ] torrentparadise.org

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#6385]
Public tv, movies, software, games, anime and xxx tracker.

**Comment by garfield69** [comment]
try out jackett 0.12.1014

**Comment by garfield69** [comment]
well that did not last long. 
https://torrentparadise.org/ returning Cloudflare 522 Connection timed out
just me, or is the site broken, gone or moved to a new domain?

**Comment by 97carmine** [comment]
When writing this, the website is online.

It seems that website crashes are frequent.

**Comment by garfield69** [comment]
confirmed. thank you for reporting.

**Comment by ilike2burnthing** [comment]
https://torrentparadise.cl/ - Error 524 - A timeout occurred

**Comment by ilike2burnthing** [comment]
Back up

**Comment by ilike2burnthing** [comment]
https://torrentparadise.org/recent - `Oops! Section in maintenance.`

Same for */popular and */top100

Keyword search still works, test/keywordless search fails. Will update when this is restored.

**Comment by ilike2burnthing** [comment]
*/recent back up

The other two are still down, but that doesn't affect Jackett.

**Comment by ilike2burnthing** [comment]
https://torrentparadise.cl/recent and search - TorrentParadise is currently under maintenance. Please check back soon.

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://torrentparadise.cl/recent and search - TorrentParadise is currently under maintenance. Please check back soon.

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrentparadise.to/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://torrentparadise.to/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrentparadise.la/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://torrentparadise.to/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
https://torrentparadise.cc/ - working
https://torrentparadise.cc/recent - 404 Not Found

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://torrentparadise.cc/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://torrentparadise.cc/ - working
> https://torrentparadise.cc/recent - 404 Not Found

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://torrentparadise.cc/recent - 404 Not Found
https://torrentparadise.cc/searchA.php?f=star%20trek%20discovery working

this site is becoming unreliable.
if in the next 25 days we get 10 days of downtime then I am removing this indexer.

**Comment by ilike2burnthing** [comment]
https://torrentparadise.cc/recent - working

Leave open for monitoring over the next month?

**Comment by ilike2burnthing** [comment]
1/10 - https://torrentparadise.cc/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
6/10:
![torrentparadise](https://user-images.githubusercontent.com/59480337/101268994-66252d80-3761-11eb-8625-b5996f5a1d5d.png)

**Comment by ngosang** [comment]
Up

**Comment by ilike2burnthing** [comment]
7//10 - https://torrentparadise.cc/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrentparadise.org/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrentparadise.org/
> ![torrentparadise](https://user-images.githubusercontent.com/59480337/101268994-66252d80-3761-11eb-8625-b5996f5a1d5d.png)

**Comment by garfield69** [comment]
given webmaster@torrentparadise.cc in the screenshot you provided,  I tried https://torrentparadise.cc/ which appears to work.

**Comment by ilike2burnthing** [comment]
Looks like all the legacy links are working, and .org is back up.

Their contact email is .to (no matter what domain you use) so I'll make that the default one for new users - https://torrentparadise.cl/report

**Comment by garfield69** [comment]
v0.17.952

**Comment by ilike2burnthing** [comment]
https://torrentparadise.to/ (and all proxies) - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrentparadise.pm/ - working
https://torrentparadise.pm/recent - `Oops! Section in maintenance.`

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://torrentparadise.pm/ returning 
```
503 Service Unavailable
No server is available to handle this request.
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://torrentparadise.pm/search.php?f=bad+batch returning HTTP ERROR 500

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrentparadise.pm/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
the web site might be up but I cant get anything to work, no recent, no search?
you?

**Comment by ilike2burnthing** [comment]
Now showing `Security check by BitNinja.IO` with a captcha challenge

**Comment by ilike2burnthing** [comment]
https://torrentparadise.pm/ and search - working
https://torrentparadise.pm/recent - Section in maintenance

**Comment by ilike2burnthing** [comment]
https://torrentparadise.pm/ - ERR_NAME_NOT_RESOLVED

**Comment by garfield69** [comment]
v0.18.911

**Comment by ilike2burnthing** [comment]
https://torrentparadise.cc/ and search - working
https://torrentparadise.cc/recent - 404 Not Found

**Comment by garfield69** [comment]
maybe we could use https://torrentparadise.cc/top100 for the keywordless search, with a note here to review occasionally to see if recent gets back online.

**Comment by garfield69** [comment]
v0.20.63

**Comment by garfield69** [comment]
https://torrentparadise.cc/top100 now also returning 404 Not Found nginx
I'm re-establishing the count back to 17 days ago.
if the site is deliberately dropping pages because of unwanted traffic from jackett then if in another couple weeks nothing has changed we will remove this indexer.

**Comment by ilike2burnthing** [comment]
https://torrentparadise.cc/top100 & https://torrentparadise.cc/recent - search box

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/d8dccfcc4762bc0af0fe3b60c11dd0272e29970c - if they block that, we'll take the hint and just remove the indexer

**Comment by ilike2burnthing** [comment]
[v0.20.105](https://github.com/Jackett/Jackett/releases/tag/v0.20.105)

**Comment by garfield69** [comment]
https://torrentparadise.cc/ returning Error 522 Connection timed out

**Comment by garfield69** [comment]
https://torrentparadise.cc/ returns 503 Service Temporarily Unavailable
nginx

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://torrentparadise.cc/ returns Error 522 - The tracker seems to be down

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://torrentparadise.cc/ - ERR_NAME_NOT_RESOLVED

.cl .to .org and .pm all redirect to .cc, and .la is still dead

**Comment by garfield69** [comment]
v0.20.1281
