### ISSUE TITLE
[generationfree] An error occurred while sending the request.: Impossible de se connecter au serveur distant (Config)

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#6394]
Hello,
Jackett version 0.12.1008.0
Windows 10 64 bits.

This tracker was down for 3 days. When the tracker came back, this error occurs.
I think the login page have change.
Do you need some log ?
Thanks for all.
Pipopop.

**Comment by garfield69** [comment]
works for me.
login with your browser and check the status of your account. make sure that there are  no outstanding alerts or unread emails. Any notifications can interfere with the post login check.
if you still cannot got it to work after that, then:
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by pipopop** [comment]
Sorry. It's a problem on my computer.
Thanks for all.
