### ISSUE TITLE
[REQ] FireBit

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#6395]
FireBit is a UKRAINIAN / RUSSIAN Public Torrent Tracker for MOVIES / TV / GENERAL.

Links:
- http://firebit.net
~~http://firebit.info~~
~~http://firebit.name~~
~~http://firebit.pro~~
~~http://firebit.club~~
~~http://firebit.biz~~

Search URL example: 
http://firebit.net/index.php?do=search&type=simple&q=2019

It seems like this tracker doesn't support search by categories.

**Comment by garfield69** [comment]
jackett 0.12.1024

**Comment by ilike2burnthing** [comment]
https://firebit.net/ - Error 522 - Connection timed out
Same for .info and .pro, but .club doesn't resolve.

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://firebit.net/ - site is up but currently showing no results (same for *.info)

**Comment by ilike2burnthing** [comment]
working again

**Comment by garfield69** [comment]
https://firebit.net/ and https://firebit.info/ returning Error 522 Connection timed out

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://firebit.net/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://firebit.net/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://firebit.net/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://firebit.net/ Не удалось соединиться с базой:: Too many connections

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://firebit.net/ - ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://firebit.net/ Не удалось соединиться с базой:: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://firebit.net/ Не удалось соединиться с базой:: Too many connections

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://firebit.net/ - Не удалось соединиться с базой:: Too many connections

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6395#issuecomment-1436046690

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://firebit.net/ - Не удалось соединиться с базой:: Too many connections

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6395#issuecomment-1454661341

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6395#issuecomment-1454661341

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://firebit.net/ Не удалось соединиться с базой:: Too many connections

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6395#issuecomment-1519149795

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6395#issuecomment-1521442559

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://firebit.net/ cloudflare Connection timed out Error code 522

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://firebit.net/ cloudflare Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6395#issuecomment-1624144489

**Comment by garfield69** [comment]
v0.21.747
