### ISSUE TITLE
[tapochek] Exception (tapochek): Login failed: No form found on http://tapochek.net/login.php using form selector form[action$=

### ISSUE THREAD

**Issue by shohart** [Jackett/Jackett#6396]
so, after a while of idle time i get jackett TAPOCKEK.NET tracker error, like 

`Exception (tapochek): Login failed: No form found on http://tapochek.net/login.php using form selector form[action$="/login.php"]: Parse error,` 

when pressing "test" button.
it can be fixed by opening config window and clicking OK.
Here is the debug [log](https://pastebin.com/ANKjCvui).
Jacket version 0.12.1000.0

**Comment by garfield69** [comment]
there is nothing in your log about tapochek, it only has events from thepiratebay and rutracker.

how long an idle time are you talking about.... just hours or days?
the next time you get a test failure, turn on enhanced logging, repeat the test for just that indexer.
Try to avoid using other indexers until you have posted the log here, to avoid loosing the relevant events.

**Comment by shohart** [comment]
> there is nothing in your log about tapochek, it only has events from thepiratebay and rutracker.
> 
> how long an idle time are you talking about.... just hours or days?
> the next time you get a test failure, turn on enhanced logging, repeat the test for just that indexer.
> Try to avoid using other indexers until you have posted the log here, to avoid loosing the relevant events.

yeah about a day, idle.

i tried to do exactly this thing: got failure, turn on enhanced logging and repeated the test... ok i will try again on next failure, thank you

**Comment by shohart** [comment]
so here is the [log](https://pastebin.com/ssqkQDUu)

as far as i can look into it, there are 2 sections that are highlighted red
first: 
`Nov 21, 2019 11:56:23 PM | Error | Error on 20191121235623 for Tapochek.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on http://tapochek.net/login.php using form selector form[action$="/login.php"]    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 478    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1256
-- | -- | --`
second
`Nov 21, 2019 11:56:23 PM | Error | Jackett.Common.IndexerException: Exception (tapochek): Login failed: No form found on http://tapochek.net/login.php using form selector form[action$="/login.php"]  ---> System.Exception: Parse error  ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on http://tapochek.net/login.php using form selector form[action$="/login.php"]    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 478    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1256    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 842    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1579    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 819    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73
-- | -- | --`

**Comment by shohart** [comment]
same behavior is also happends with rutor intdexer

**Comment by garfield69** [comment]
I cannot replicate your issue with tapochek or rutor.
is this still happening for you?

**Comment by shohart** [comment]
yes it is. can it maybe be related to my tor\privoxy proxy?

**Comment by garfield69** [comment]
Oh yes, most probably.
Something to do with the session cookies not being kept by the proxy such that when Jackett tries to re-establish the session with tapochek the next day, the site responds with a re-login required because the session cookies it wants are not available.
I don't think this has anything to do with Jackett in any case.

**Comment by ilike2burnthing** [comment]
Are you also using a VPN/proxy? If so, are you using a single server/IP or changing regularly?

**Comment by ilike2burnthing** [comment]
Are you accessing the tapochek.net in browser from a different IP than Jackett?

Now that the indexer is configured in Jackett, if you access the site in browser are you signed out? If you sign in and then try to use the indexer in Jackett, does it fail again?

**Comment by ilike2burnthing** [comment]
Login in browser, check that there aren't any unread messages, announcements, or notifications which might be causing the issue.

I'm using uBlock Origin and not getting any popups or redirects.

**Comment by ilike2burnthing** [comment]
The site supports HTTPS, both in browser and Jackett. If it doesn't for you, there's some other issue there.

**Comment by ilike2burnthing** [comment]
Yea, there's some other issue there for you, the site is fine.

**Comment by ilike2burnthing** [comment]
If that site doesn't support HTTPS for you, in browser or Jackett, then there's a problem on your end unrelated to Jackett.
