### ISSUE TITLE
[underverseL] torrents are not accessible via RSS feed

### ISSUE THREAD

**Issue by shohart** [Jackett/Jackett#6397]
So, when searching via search dialog i can successfully download .torrent files from underverseL thank to lasest update from @garfield69 (Arigatou gozaimasu, Garfield-sama!).
BUT, when trying to fetch torrents via torznab-rss-feed (from the <link> section) i  am getting error 404 not found
here is the [example rss](https://pastebin.com/ZfFzjZyv)

Jackett Version 0.12.1000.0

**Comment by garfield69** [comment]
Sorry, the rss stuff is out of my area of expertise. 
Ping to any volunteers that can help diagnose this issue?

**Comment by shohart** [comment]
the underverse rss feed is broken by itself - it has link to forum thread (viewtopic?) in <link> variable instead of link to an actual torrent file download, so if jacket uses tracker rss feed, there is nothing we can do about it. i just do not know how it is being managed.

**Comment by garfield69** [comment]
Jackett 0.12.1572
