### ISSUE TITLE
[iptorrents]  (Config)

### ISSUE THREAD

**Issue by bwittgen** [Jackett/Jackett#6402]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  Jackett Version 0.12.1007.0
[log.txt](https://github.com/Jackett/Jackett/files/3865969/log.txt)
[supervisord.log](https://github.com/Jackett/Jackett/files/3865970/supervisord.log)

-------------------------------
So I haven't been able to get IPTorrents to work for several weeks. It looks like they have some sort of DDoS protection in place now that is breaking it?

**Comment by bwittgen** [comment]
There are no details on that other bug, nor has it been acknowledged.

**Comment by garfield69** [comment]
https://iptorrents.com/ works for me with jackett 0.12.2007

but from your logs it appears that your ip block is currently blacklisted, and you are getting a cloudflare test.

you will just have to use your browser to access iptorrents directly until such time as they lift the DDoS protection from your IP block.

**Comment by bwittgen** [comment]
@garfield69 what doesn't make sense is that using the SAME VPN connection, I can navigate to it from my browser? What is Jackett doing differently?

**Comment by bwittgen** [comment]
I have a single VPN docker that all of my internet traffic flows through, including Jackett and my web browser. Someone on the unRAID forums posted they are having this same issue with IPTorrents.

**Comment by garfield69** [comment]
I am sorry, But I cannot help you with this. I have no experience with VPN or proxies, I don't use them myself. 
And I do not understand how jackett uses them. It is outside of my expertise.
I'll reopen the ticket and see if anyone else volunteers to help.

**Comment by ngosang** [comment]
@bwittgen maybe this help https://github.com/Jackett/Jackett/issues/6446#issuecomment-560093162

**Comment by QuiGonLeong** [comment]
Try using https://ipt.beelyrics.net/ in your site link.

![image](https://user-images.githubusercontent.com/41975335/70381974-107d3180-1911-11ea-86e4-3841945ac7a5.png)

**Comment by ngosang** [comment]
We did some changes in IPTorrents code to improve the debug information. Please, could you update to the latest version (Jackett 0.12.1746 or newer) and provide feedback? If there is a exception, enable the `Enhanced logging` and post the logs. Thank you!

**Comment by garfield69** [comment]
Jackett 0.13.173
