### ISSUE TITLE
Indexers failing

### ISSUE THREAD

**Issue by mouzzampk2014** [Jackett/Jackett#6403]
Hello team,

Need your help all indexers in my jackett stopped working. I am not sure what happened.

![3](https://user-images.githubusercontent.com/44548525/69185836-611e1d80-0b0f-11ea-9305-287daddf0d9a.JPG)

Jackett Version 0.12.1007.0

-------------------------------

[Log.txt](https://github.com/Jackett/Jackett/files/3866081/Log.txt)

**Comment by garfield69** [comment]
Sorry but the stack trace is just not enough info to work with in this case.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test on one of the indexers
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by mouzzampk2014** [comment]
I'm really sorry for disturbing you. I recreated the image and everything start working fine. Thanks again :)
