### ISSUE TITLE
[REQ] todocvcd.me

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#6409]
Spanish public tracker of movies, series, music, software and others
https://www.todocvcd.me/

**Comment by garfield69** [comment]
This site's search results only provides a top level entry which leads to a details page that has one or more torrents (especially for tv series).
As such it is not compatible with the cardigann processing which requires a one-to-one reference between titles in the search results and its torrent (be it .torrent or magnet or both).

the indexer for this site will therefore require coding in c#.

**Comment by ngosang** [comment]
@97carmine The latest upload in this site was in 2017. I recommend you to use DivxTotal or Newpct.

**Comment by 97carmine** [comment]
I close for outdated indexer
