### ISSUE TITLE
IPTorrents - Configuration Failed -  CAPTCHA Issue?

### ISSUE THREAD

**Issue by tripout** [Jackett/Jackett#641]
IPTorrents implemented a CAPTCHA kinda deal.  It seems to be failing when I try to configure it in Jackett.

11-04 17:04:19 Debug UnixLibCurlWebClient:GetString(Url:https://iptorrents.com/take_login.php)
11-04 17:04:19 Debug UnixLibCurlWebClient: Posting username=MyUsername&password=MyPassword
**11-04 17:04:19 Debug UnixLibCurlWebClient:GetString Returning OK => Captcha verification failed.<br>please try again!**
11-04 17:04:20 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
11-04 17:04:20 Info ApiControllerActionInvoker InvokeActionAsync
System.Web.Http.Action: ApiControllerActionInvoker InvokeActionAsync

**Comment by d2dyno** [comment]
Odd, I just signed into Jackett not 3 hours ago...

**Comment by tripout** [comment]
I see other comments about a "Configuration Failed" error but this was new and nothing in the Issue tracker about this.  I had a sudden realisation though and will try something and report back.
