### ISSUE TITLE
[audiobookbay] Relogin Required

### ISSUE THREAD

**Issue by leering1** [Jackett/Jackett#6412]
Jackett ver: 0.12.1024.0

ABB hasn't been returning any results and the log file is showing a login error.  I confirmed the credentials and in Jackett and via the website.  I believe ABB recently upgraded the performance of the server and the error could match the timing for this upgrade.  I don't know for sure as most ABB searches would time out in the past.

Tested with a release that was validated with a manual search on the ABB site.  Tested results both logged out and logged in.  Note: there is no access to the magnet link when logged out.

When searching from LL->NZBydra->Jackett  the logs show:

Nov 21, 2019 11:55:32 AM | Info | Found 0 releases from AudioBookBay for: Will Wight Uncrowned
-- | -- | --
Nov 21, 2019 11:55:24 AM | Info | CardigannIndexer (audiobookbay): Relogin required
Nov 21, 2019 11:55:17 AM | Info | CardigannIndexer (audiobookbay): Relogin required
Nov 21, 2019 11:55:09 AM | Info | CardigannIndexer (audiobookbay): Relogin required
Nov 21, 2019 11:55:02 AM | Info | CardigannIndexer (audiobookbay): Relogin required

**Comment by garfield69** [comment]
works for me on my win10 jackett 0.12.1024
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by leering1** [comment]
I did a little more testing with LL and manual searches.  The results look to be an ABB indexing issue with author&title failing and only the author succeeding in this example.

Jackett still has a "relogin required" log entry no matter the searches results. Safe to close or you interested in the relogin entry?

Thanks

[ABB results log.txt](https://github.com/Jackett/Jackett/files/3881148/ABB.results.log.txt)

[ABB log.txt](https://github.com/Jackett/Jackett/files/3881096/ABB.log.txt)

**Comment by garfield69** [comment]
the relogin is expected anytime you initiate a download.
before you can download you have to re-authorise yourself even if you have already logged in previously, don't ask me why, that is how the site apparently works behind the scenes.
and if the site has a short cookie life span, then a relogin could also be forced when you start a search, so this is normal and expected.
