### ISSUE TITLE
[REQ] mejorenvo.me

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#6415]
Spanish public series and movie tracker in original version
http://www.mejorenvo.me/

**Comment by garfield69** [comment]
this site does not produce search results in a title-to-single-torrent presentation.
as such it cannot be processed by a yaml indexer for the cardigann processor.
to add this site to jackett the indexer will need to be coded in C#.

**Comment by JorTurFer** [comment]
http://www.mejorenvo.me/ returns 404

**Comment by ilike2burnthing** [comment]
https://www.mejorenvo1.com/

**Comment by 97carmine** [comment]
I close, the website has closed
