### ISSUE TITLE
[lostfilm] Exception (lostfilm): Object reference not set to an instance of an object.: Parse error (Config)

### ISSUE THREAD

**Issue by mosath-s** [Jackett/Jackett#6416]
Cant add lostfilm.tv - got parse error (see pastebin log)
https://pastebin.com/6q9591rd

**Jackett version**:  v0.12.1026

**Comment by garfield69** [comment]
works for me.
are you using your email address as the username?

**Comment by garfield69** [comment]
last time some one reported a similar error it turned out to be a temporary issue at the site. #5921

**Comment by mosath-s** [comment]
Thats problem with proxy
Can you make possible to disable proxy for specific torrent trackers?

**Comment by garfield69** [comment]
>Can you make possible to disable proxy for specific torrent trackers?

that option is not available right now.
you could raise an enhancement ticket for this option.
but be aware that the regular C# developers have not been available recently so you may be waiting quite a while until a new C# volunteer contributes.
