### ISSUE TITLE
[rutracker] Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by BangisBanginis** [Jackett/Jackett#6419]
When trying to add rutracker.org indexer to jacket I receive this error:
 An error occured while updating this indexer
Found no results while trying to browse this tracker

However I am able to access this site via browser and with same login and password.

I had it added previously but for whatever reason uninstalled jacket and later installed it again. After this I managed to add back all my indexers excep this one.
-------------------------------
Log:

Nov 24, 2019 11:34:21 PM | Error | System.Exception: Found no results while trying to browse this tracker   at Jackett.Common.Services.IndexerManagerService.TestIndexer (System.String name) [0x000e8] in <3f4864bea7054cd2b7e83a28c06c8c3f>:0    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig (Jackett.Common.Models.DTO.ConfigItem[] config) [0x0012d] in <d9cb217c33fa4cc9a9b8489469fe5189>:0    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <d9cb217c33fa4cc9a9b8489469fe5189>:0

rutracker: Error while parsing row ' here go some html TR tags
....
System.NullReferenceException: Object reference not set to an instance of an object
  at Jackett.Common.Indexers.RuTracker.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x002f9] in <3f4864bea7054cd2b7e83a28c06c8c3f>:0 

-------------------------------
Synology DS218+
Jackett Version 0.11.43.0
Mono Version 5.18.0.240-12

**Comment by garfield69** [comment]
the html from ruTracker has changed back on August and the size, seeders, leechers and date selectors needed adjustments. #5781
so to use ruTracket you are going to need jackett 0.11.563 or newer.
current latest jackett release is 0.12.1028 
If the SynoCommunity repo is only making 0.11.43 available then get in touch with them and see if it is possible to get someone to build a more current package.
