### ISSUE TITLE
[REQ] legittorrents.info

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#6426]
Public tracker of legal content with categories such as tv shows, software, movies, music, anime, books and other.

http://www.legittorrents.info/

**Comment by garfield69** [comment]
try out jackett 0.12.1035

**Comment by ilike2burnthing** [comment]
http://www.legittorrents.info/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> http://www.legittorrents.info/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> http://www.legittorrents.info/ - ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
http://www.legittorrents.info/ returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
http://www.legittorrents.info/ - ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.20.3247

**Comment by ilike2burnthing** [comment]
Looks like this did eventually come back online, but is now officially dead - https://torrentfreak.com/legit-torrents-shuts-down-after-17-years-230421/
