### ISSUE TITLE
Cant add xspeeds - failure while loading a type

### ISSUE THREAD

**Issue by manderss99** [Jackett/Jackett#643]
This is version 539 on ubuntu. Also failed on earlier version.

11-05 08:40:18 Info UnixLibCurlWebClient: Received a new CloudFlare challenge 
11-05 08:40:18 Error Exception in Configure System.TypeLoadException: Failure ha
s occurred while loading a type.
  at Jackett.Utils.Clients.UnixLibCurlWebClient+<RunCloudFlare>c__async2.MoveNex
t () <0x40e02000 + 0x003eb> in <filename unknown>:0

**Comment by kaso17** [comment]
Please make sure you've installed the mono-devel package

**Comment by manderss99** [comment]
that solved it, thanks!
