### ISSUE TITLE
[REQ] mitorrent.org

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#6434]
Spanish public tracker of movies and series

https://mitorrent.org/

**Comment by garfield69** [comment]
the TV series results on the search page of this site are for main series title only.
one then has to navigate to the details page of a title, where one finds multiple torrent download links for each episode in one or more seasons.
As such, this site is not compatible with the cardigann processor which requires that torrent search results be one-title-for-one-torrent in its yaml indexer configs.
So to process this site the indexer will have to be written in C#

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
