### ISSUE TITLE
[mteamtp] Exception (mteamtp): Login Failed, got redirected.: Parse error (Test)

### ISSUE THREAD

**Issue by unknown12345678** [Jackett/Jackett#6439]
After enabling 2FA for this indexer, I am unable to login. 

Works fine if 2FA is disabled.

Jackett Version 0.12.1035.0

**Comment by garfield69** [comment]
2FA is not supported.
an enhancement request for 2fa support has been raised, #3345 but as yet no one has volunteered to implement.
