### ISSUE TITLE
Poor linux install instructions

### ISSUE THREAD

**Issue by 0xW1sKy** [Jackett/Jackett#6442]
Request to add the following instructions for linux install:

The link provided in the current readme for linux install to install prerequisites is broken. After finding the correct link, the instructions were somewhat unclear for non-developer type users.

The following is what is actually needed to run jackett on ubuntu. Suggest adding these to the read me:

```
wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

sudo apt-get update
sudo apt-get apt-transport-https dotnet-runtime-3.0
```

**Comment by garfield69** [comment]
can you provide the link to replace the broken one please. thanks.

**Comment by garfield69** [comment]
found https://github.com/dotnet/core/blob/master/Documentation/linux-prereqs.md
have you got a better one?

**Comment by junglebus** [comment]
The steps
```
wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

sudo apt-get update
sudo apt-get apt-transport-https dotnet-runtime-3.0
```
are completely unnecessary and tens of thousands of people have proven it
Jackett gets built as a self contained deployment or 'standalone' i.e. it doesn't require the runtime to be installed on the pc as its already bundled with Jackett https://docs.microsoft.com/en-us/dotnet/core/deploying/#self-contained-deployments-scd
If you go back and read the posts where Jackett was made compatible with .NET Core, the goal was not to require the user to need to install a runtime (e.g. Mono) https://github.com/Jackett/Jackett/issues/1680

The only things you may need to install (and shouldn't be needed for most people unless you are running are very cut down distro) are: https://github.com/dotnet/core/blob/master/Documentation/linux-prereqs.md

**Comment by garfield69** [comment]
@junglebus   thanks for the info. 
readme amended.
