### ISSUE TITLE
[REQ] torrentsdepeliculas.org

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#6444]
Spanish public movie tracker

https://torrentsdepeliculas.org

**Comment by garfield69** [comment]
does this site have actual .torrents or magnet links?
all I have found so far on the detail pages are click bait and 3rd party streaming links.
Jackett can only support sites that provide magnet or .torrent links directly.
please provide an example link that leads to a real download link on this site, I may have missed it.

**Comment by 97carmine** [comment]
The all links redirect to the root folder https://torrentsdepeliculas.org/wp-content/uploads/ _year_

_year_: 2017, 2018 and 2019

They are all torrent files

**Comment by garfield69** [comment]
I'm sorry I don't understand.
suppose you want to search for the movie **captain america**.
https://torrentsdepeliculas.org/?s=captain+america
then you click on a poster to view the details page to presumably get a link to the torrent
https://torrentsdepeliculas.org/descargar-torrent-de-pelicula-captain-america-the-winter-soldier/
is there a direct link to the torrent or magnet on this page?

if you cannot do a search on the site and return a torrent, then there is little point creating a jackett indexer for it.

**Comment by 97carmine** [comment]
You are correct, there is no way to get the torrent file from the page itself. I close

Thank you anyway.
