### ISSUE TITLE
[alexfilm] The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject]  CN=alexfilm.org[Issuer]  CN=Let's Encrypt Authority X3, O=Let's Encrypt, C=US[Serial Number]  03F04C316022CF208B3E0A97CD074A1278FB[Not Before]  8/31/2019 8:06:59 PM[Not After]  11/29/2019 8:06:59 PM[Thumbprint]  9200E15406272061DF1F609A0F40D76282F54295 (Config)

### ISSUE THREAD

**Issue by gilbertbodyb28** [Jackett/Jackett#6445]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by garfield69** [comment]
the alexfilm's site certificate expired today.
bypassed with jackett 0.12.1047
