### ISSUE TITLE
[MejorTorrent] Is not returning results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6449]
Search mp3 in http://www.mejortorrentt.org returns 169 results
Search mp3 in Jackett return 0 results.

The same happens with all searches in Jackett for this site.
The test button is working but shouldn't be. It's a good idea to make a search that we now returns results and check the results list is not empty.

 **Jackett version**:  0.12.1042.0

**Comment by garfield69** [comment]
i cant get this site to work with jackett right now, they have got the cloudflare anti-DDoS activated for my IP block which prevents jackett working since it cannot solve the reCaptcha.
Anyway, the indexer for this site is written in C# so I'm not going to touch this
ping to any C# volunteer to work on this one.

**Comment by ngosang** [comment]
ping @ivanbeldad

**Comment by ivanbeldad** [comment]
I don't have time to work on this, sorry

**Comment by rovik0** [comment]
We lack of indexers in spain and this is the only working with multiple clones along inet.
- Elitetorrent returns unexpected results always
- NEWPCT has the majority of links borken or not maintained
- Mejortorrent seems to be the last hope in Sonarr for Spanish users

**Comment by ngosang** [comment]
ping @alvaro654 @Yllelder

**Comment by rovik0** [comment]
is there any way we can look for other contributors for this?

**Comment by ivanbeldad** [comment]
@ngosang The indexer is working correctly for me. You're searching for _mp3_, but if you see the indexer capabilities it's compatible with Movies and TV Shows, not music or anything else.

The test button is working because the indexer it's working (image below), if you aren't able to get it working with movies or shows, then maybe something is wrong on your end.

![image](https://user-images.githubusercontent.com/10326536/70308116-e17c9800-180a-11ea-927e-bd9d89d41e46.png)

**Comment by ngosang** [comment]
@ivanbeldad You are right about the mp3 search. But is has important problems:
* There isn't download link
* If you click in the name dosn't work.

**Comment by ivanbeldad** [comment]
@ngosang Yeah, that's a real problem, didn't notice before. Gonna check it out this weekend if I see the problem, but I don't make any promises.

**Comment by ivanbeldad** [comment]
Can't download any torrent from the site http://www.mejortorrentt.org
When I try it downloads a `.zip` instead, and the browser stops it because it's detected as a virus.

**Comment by rovik0** [comment]
@ivanbeldad good point. 

For 'http://www.mejortorrentt.org/' there are no torrent files there, at least i couldn't find any. On the other hand if you look at 'mejortorrent1.net' e.g: https://mejortorrent1.net/mr-robot-temporada-4-720p/ there are some. I thought that we are not only looking to a single url but multiple instead.

I suposed wrongly that changing the url in Jackett should work but returns **Sequence contains no elements**

**Comment by ivanbeldad** [comment]
@rovik0 at first I thought that the only problem was the rss url was different 
in https://mejortorrent1.net and I could fix it just adding a new configuration variable, but it has a complete different url scheme. Also the page structure is slightly different.
So, sadly, to make it work would be necessary to create a complete fresh new crawler.

**Comment by rovik0** [comment]
Yaiks! Anything I  can do? I did some C++ in the past but I'm a complete noob/minion. 
Any way/wiki where I could teach myself and help somehow on this or too hard? New crawler sound like really a "THING"

**Comment by ivanbeldad** [comment]
@rovik0 I'm not a C/C++/C# developer and didn't have too much trouble doing it (but I'm an actual developer, if you're not, then it's going to be hard). I'm pretty sure anyone but me could give you better advise in this regard. I just guessed based on others Indexers. Mine must be a complete mess for an experienced C# developer, but it did the work for a time (more than I expected really) :man_shrugging:

Good luck if you're willing to try it.

**Comment by rovik0** [comment]
Cristal clear, i'm not a dev/experienced coder so better I keep out of this. The remain question here I think is. Do we still need help with C# if we need a new "crawler" @ivanbeldad? Just to ensure we tag this story properly.

**Comment by ivanbeldad** [comment]
I don't really know if the YML format is enough, just remember trying it without success with the previous website and finally using C#. Too much tricky parts and requests to make it working so didn't want to try YML just to find out in the middle of the job that I couldn't do it with it.

**Comment by rovik0** [comment]
@ngosang The indexer is working correctly for me. You're searching for mp3, but if you see the indexer capabilities it's compatible with Movies and TV Shows, not music or anything else.

The test button is working because the indexer it's working (image below), if you aren't able to get it working with movies or shows, then maybe something is wrong on your end.

**Comment by rovik0** [comment]
The links delviered are not working or there's no download button.
![image](https://user-images.githubusercontent.com/12533254/71493320-05496180-283e-11ea-9311-d84b243fd5c3.png)

![image](https://user-images.githubusercontent.com/12533254/71493442-fc0cc480-283e-11ea-98fa-5f7e7b1786c7.png)

**Comment by alagos** [comment]
Probably related, but I'm using dockerised sonarr/jackett instances and simply trying to test the connection with MejorTorrent:
![Captura de pantalla_2019-12-29_22-49-54](https://user-images.githubusercontent.com/475834/71563811-8be78400-2a74-11ea-9096-8acdacb9637d.png)

it throws this:

```
12-29 19:45:40 Info Found 44 (0 new) releases from MejorTorrent 
12-29 19:45:40 Error System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 63
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 39
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 417 System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 63
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 39
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 417
```
not happening with other indexers.

**Comment by garfield69** [comment]
Jackett 0.12.1449

**Comment by rovik0** [comment]
Working like a charm, thank you so much!
