### ISSUE TITLE
[REQ] seedpeer.me

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6450]
It has 12,536,757 torrents according this => https://torrentz2.eu/help#indexed

**Comment by garfield69** [comment]
this site appears to generate its search results dynamically using JS
as such it is not compatible with the Cardigann processor which expects fully resolved HTML to process.
This indexer will have to be written in c#

**Comment by ngosang** [comment]
@garfield69 take a look again. I think all you need is in plain html => view-source:https://seedpeer.me/search/harry?page=2

**Comment by garfield69** [comment]
Ah no ;-)
Using the view-source option on a browser is still using the browser's point of view after the javascript has run and generated the results.
to see the actual html that was sent by the site in response to you doing an *http get url*, you need to view the network traffic.

so, click on https://seedpeer.me/search/harry?page=2 from your browser
then press **F12** and click on the **Network** tab.
then click on the **Doc** filter tab
now press **F5** to refresh the page.
click on the **Harry?page=2** entry
click on the **Response** tab
there is the actual HTML that the site returns when you click on the link you provided.
as you can see, its does not contain any results. The results are dynamically generated when the  script
```html
 <script>
    var sc_project=10855751;
    var sc_invisible=1;
    var sc_security="956a49f2";
    var scJsHost = (("https:" == document.location.protocol) ?
      "https://secure." : "http://www.");
    document.write("<sc"+"ript type='text/javascript' src='" + scJsHost+
      "statcounter.com/counter/counter.js'></"+"script>");
  </script>
  <noscript>
    <div class="statcounter"><a title="shopify analytics"
    href="https://statcounter.com/shopify/" target="_blank"><img
    class="statcounter" src="https://c.statcounter.com/10855751/0/956a49f2/1/"
    alt="shopify analytics"></a></div>
  </noscript>
```
 is run.

**Comment by garfield69** [comment]
shit. no. you are right.
i see the html buried in there now. long bloody single line that I missed because it was not wrapped.

I've not had enough sleep. 
I think we can process this after all ;-)

**Comment by garfield69** [comment]
jacket 0.12.1146
