### ISSUE TITLE
[REQ] bittorrent.am

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6452]
It has 13,083,767 torrents according to => https://torrentz2.eu/help#indexed

**Comment by garfield69** [comment]
try out jackett 0.12.1053

**Comment by ngosang** [comment]
It's working well. Thank you!

**Comment by garfield69** [comment]
http://www.bittorrent.am/ returning ERR_NAME_RESOLUTION_FAILED
just me or is the site broken, gone or moved to a new domain?

**Comment by ngosang** [comment]
The site is not working at this moment because they don't have valid DNS. I don't know alternative domains. The site is huge and I expect them to come back. Wait few weeks before removing.

**Comment by garfield69** [comment]
Yeah, no problem. I usually give any site a month before I commit to removing the indexer.

**Comment by garfield69** [comment]
back online.

**Comment by garfield69** [comment]
broken again.
http://www.bittorrent.am/search.php?kwds=katana+astra&cat=100&x=0&y=0
returns ERR_EMPTY_RESPONSE

**Comment by garfield69** [comment]
back online.
