### ISSUE TITLE
[Monova] is not returning correct results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6453]
If I search in https://monova.org almost all queries return results, but in Jackett there are 0 results.
I tried "logan" for example.

**Comment by garfield69** [comment]
try out jackett 0.12.1053

**Comment by ngosang** [comment]
Thank you, the search results improved a lot.

**Comment by 97carmine** [comment]
Only the movie category returns results, the rest of the categories do not return any results

**Comment by garfield69** [comment]
@97carmine  yup. this site does not provide the usual category and search results details that would allow jackett to fully support multi-category searches and category tagging of the results.
So we shoe-horned a best-fit for what we get from the site, and there is nothing more we can do for this site using the cardigann indexer framework.
