### ISSUE TITLE
[zooqle] Exception (zooqle): Clearance failed after 30 attempt(s).: Clearance failed after 30 attempt(s). (Test)

### ISSUE THREAD

**Issue by sbeaudoin** [Jackett/Jackett#6455]
Version 0.12.1047.0.  Added zooqle, tested it, gave this error.

**Comment by garfield69** [comment]
zooqle have enabled the cloudflare anti-DDoS protection for your IP block.
Jackett is not able to solve the cloudflare ReCaptcha hence the 30-attempts-failed message.
you will just have to wait for zooqle to drop the protection before using jackett with this indexer.
