### ISSUE TITLE
[ourbits] Clearance failed after 30 attempt(s). (Config)

### ISSUE THREAD

**Issue by killerqueen619** [Jackett/Jackett#6456]
ss : http://prntscr.com/q4ebfx
thank you

**Comment by garfield69** [comment]
ourbits have enabled cloudflare's anti-DDoS protection for your IP block
jackett is not able to solve the cloudlfare ReCaptcha hence the 30-attempts-failed message.
there is nothing you can do but wait for the site to drop the protection.
