### ISSUE TITLE
My config folder doesn't seem to be where it should

### ISSUE THREAD

**Issue by nununo** [Jackett/Jackett#6457]
Hello,

I installed Jackett over Debian 10 using [this official tutorial](https://github.com/Jackett/Jackett#install-on-linux-amdx64) and am running it as a systemd service. The tutorial says that I should expect to find the config folder at `~/.config` but I don't have this folder. Neither under the user running the Jackett service nor under `root`.

And yet my configuration must be stored somewhere since I already rebooted it and all my indexers are still there!...

What am I missing?

**Jackett version**:  0.12.1047.0

Thank you in advance!

Regards,
Nuno

**Comment by garfield69** [comment]
the dot folders are hidden by default on some linux systems.
most gui file managers use CTRL-H to toggle the view.
for the terminal **ls** command, add the **-a** parm, eg `ls -a ~/.config`

**Comment by nununo** [comment]
Hello @garfield69,

Sorry, I forgot to mention that I know my way around linux systems and that dot files are hidden by default. That this is a headless system so I'm just using command-line:

```
root@jackett:/home/nununo# ll -a
total 112
drwxr-xr-x 3 nununo nununo    8 Nov 17 03:20 .
drwxr-xr-x 3 root   root      3 Nov 17 03:17 ..
-rw------- 1 nununo nununo  497 Nov 17 04:00 .bash_history
-rw-r--r-- 1 nununo nununo  220 Nov 17 03:17 .bash_logout
-rw-r--r-- 1 nununo nununo 3534 Nov 17 03:20 .bashrc
-rw-r--r-- 1 nununo nununo  807 Nov 17 03:17 .profile
-rw-r--r-- 1 nununo nununo  165 Nov 17 03:19 .wget-hsts
drwxr-xr-x 5 nununo nununo  366 Dec  1 01:51 Jackett
```

Also, this is my jackett.service file where you can see that indeed it is user `nununo` that's being used:
```
root@jackett:/home/nununo# cat /etc/systemd/system/jackett.service 
[Unit]
Description=Jackett Daemon
After=network.target

[Service]
SyslogIdentifier=jackett
Restart=always
RestartSec=5
Type=simple
User=nununo
Group=nununo
WorkingDirectory=/home/nununo/Jackett
ExecStart=/home/nununo/Jackett/jackett_launcher.sh
TimeoutStopSec=20

[Install]
WantedBy=multi-user.target
```

Thank you again for any light on this matter.

Regards,
Nuno

**Comment by garfield69** [comment]
ok. so try the following commands at your terimnal:
```
cd /home/nununo/Jackett
/.jackett
```
this will attempt to start jackett in console mode, but will fail since the service is already running.
however, you should see near the top of the output, something similar to the following line:
```
MM-dd hh:mm:ss Info App config/log directory: your-config-folder
```
which should tell you where your logs and active indexers are being kept.

**Comment by nununo** [comment]
Thank you so much @garfield69 ! That worked! Strangely my config folder is this:
`/home/nununo/Jackett/Jackett`

Problem solved! Thanks again!

I don't know how this may have happened as I simply followed the instructions. Maybe it's worth trying to find out. Let me know if there's something I can do in that regard.

**Comment by garfield69** [comment]
there are so many flavours of linux out there and they all do not behave in the same way.
I would not be concerned that your config is in a different location.
I believe the readme was prepared from the results of an Ubuntu install, presumably picking the most common linux variation ;-)

**Comment by nununo** [comment]
Makes senses. I'll just accept it and move on. Thank you again for your precious an swift help!
