### ISSUE TITLE
[Monova] is returning sponsored links

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6459]
jackett 0.12.1053

After https://github.com/Jackett/Jackett/issues/6453 I see sponsored links in the results. I think it will be easy to remove that results. The sponsored links have 0 min published time.
![image](https://user-images.githubusercontent.com/10577978/69912682-0056e500-142d-11ea-997e-345a50b72b9b.png)
![image](https://user-images.githubusercontent.com/10577978/69912692-28dedf00-142d-11ea-8606-eb05d6b1c74a.png)

**Comment by garfield69** [comment]
try out jackett pre-release 0.12.1055

**Comment by ngosang** [comment]
It's working. Thank you!
