### ISSUE TITLE
[hdhome] Login Failed, got redirected. Try changing the indexer URL to http://hdhome.org/. (Config)

### ISSUE THREAD

**Issue by killerqueen619** [Jackett/Jackett#6460]
ss : http://prntscr.com/q4m4md

**Comment by garfield69** [comment]
looks like they are forcing https to http.
but since I don't have an account on this site I cannot test the login to completion.
I've auto-updated the site link to http so try out jackett pre-release 0.12.1055 and report back thanks.

**Comment by killerqueen619** [comment]
still error Mr Garfield

**Comment by killerqueen619** [comment]
i have already sent u an email please check

**Comment by garfield69** [comment]
thank you for the email.
I was able to determine that the only way for Jackett to now login to HDHome is to use the cookie login method, which I have tested successfully.

try out jackett pre-release 0.12.1063

you will need to use the wrench icon on your jackett dashboard to edit the HDHome config and add the cookie string, instructions will be in the config Info section.

You may also need to periodically refresh the cookie, depending on what expiry date HDHome have on their cookies. (Could be daily, weekly or monthly or anything in between).
