### ISSUE TITLE
[scenetime] Your cookie did not work: The 'Value'='login,donateok' part of the cookie is invalid. (Config)

### ISSUE THREAD

**Issue by GrimDevelopment** [Jackett/Jackett#6472]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by garfield69** [comment]
you clearly have copied the wrong cookie. 
the correct cookie string for this site (after you have logged in) will look something similar to:
```
__cfduid=d*****************************0; PHPSESSID=3*****************0; uid=4****8; pass=2******************9
```

**Comment by remailednet** [comment]
I'll second that I received the same message.
Removing 
```
acgroupswithpersist=nada; acopendivids=login,donateok;
```
from the string worked for me.

So it is indeed the correct cookie, but possibly SceneTime updated their site to include more that Jackett now has an issue with.
