### ISSUE TITLE
yggtorrent - new address

### ISSUE THREAD

**Issue by aarsenca** [Jackett/Jackett#6473]
Hi,

yggtorrent just changed its address to https://yggtorrent.ws/.

Has anybody figured out the new settings for jackett?

Thanks.

**Comment by garfield69** [comment]
Oh, not again! 
with the change of domain to .ws,  YGGTorrent has also re-introduced the **307 
Temporary redirect**  issue which breaks Jackett's attempts to login.
until they fix that problem (which the last 3 times this happened was corrected by the site within 1 to 7 days) then there is little that can be done but wait.
we will post here when we know what the working addresses are.

**Comment by garfield69** [comment]
the YGGTorrent website has changed their domain to **.ws**
And you should be able to get the Jackett YGGTorrent Indexer working again as follows:  
1. access your jackett dashboard and use the wrench icon to edit your YGGTorrent indexer config.
2. set the **Site Link** to `https://yggtorrent.ws/` and 
3. set the **Search and download URL** to `www2.yggtorrent.ws`
4. Click **OKAY**
5. if you get an error, click **CLOSE** then edit again and click OKAY. it should save the second time.

Works for me. See if it works for you.

**Comment by aarsenca** [comment]
It works for me too! I tried several combinations before posting my issue, but probably not this one. Thanks!

**Comment by Bluntananas** [comment]
Works fine. Thanks !

**Comment by Miko2708** [comment]
hi when  I change the URL address i have a succesfull message 
Successfully configured YGGcookie
then when I test I  have this error 
"Exception (yggcookie): Invalid URI: The hostname could not be parsed.: Invalid URI: The hostname could not be parsed"
i get the connection cookie like in the jackett exemple 
thanks for your help 
Mikael

**Comment by garfield69** [comment]
@Miko2708 with YGGCookie you will need to also renew your cookie, since with the change to a new domain, your existing cookie is no longer valid.

**Comment by Miko2708** [comment]
hi @garfield69 
i had this error after i renew the cookie 
thank you 
Mikael

**Comment by Miko2708** [comment]
hi @garfield69 my bad i forgot the "https" in the Search and download URL 
everything work ! 
thank you 
Mikael

**Comment by Arrowblood** [comment]
Thanks to garfield69 to solve my problem with YGG.

**Comment by scorsi** [comment]
@garfield69 I don't achieve to connect jackett to yggtorrent even with your instructions. Do you have any advice ?
Got:
```
An error occured while updating this indexer
Login failed: No form found on https://yggtorrent.ws/ using form selector #user-login
```

**Comment by garfield69** [comment]
@scorsi  I suggest you login to yggtorrent with your browser and check that your account is working, with a good ratio, and with no outstanding alerts, notices and unread emails.
then on the jackett dashboard use your trashbin icon to remove yggtorrent from your active list.
then add a fresh one from the add-indexer page.
double check that the site link and search link are set as described in https://github.com/Jackett/Jackett/issues/6473#issuecomment-560978023
enter your username/password (if prefilled enter them again anyway)
and save.
if you get an error click close and then edit and click OKAY it should save the second time.

**Comment by scorsi** [comment]
@garfield69 ok, my ratio was under 1.00 it because of that :(

**Comment by xontik** [comment]
@scorsi how do you relog to ygg to seed ? I'm in the same situation :/

**Comment by scorsi** [comment]
@xontik it's not the place for that ^^ ... but, you can download using a debrider (like real-debrid, all-debrid, seedr...) and then seed them from you torrent client. To do so follow theses steps :
 - download the torrent from a debrider,
 - add the torrent in pause state,
 - download files form the debrider,
 - copy downloaded files where you download the torrents (respect potentials folders, unrar archives...),
 - force check the files of the torrent (you will achieve 100% downloaded, if not check that files are at the right place),
 - and then seed the torrent.
It's working fine but it's not truly allowed however all peoples doing that have still their account active. Do not use that technique everytime.
You should consider seeding last adult-only movies for increasing faster.

**Comment by geekcatfr** [comment]
impossible to add Yggtorrent as a tracker cause adress changed again : https://www.yggtorrent.se/

**Comment by garfield69** [comment]
@geekcatfr  carefully read and implement  https://github.com/Jackett/Jackett/issues/7095#issuecomment-582238746
