### ISSUE TITLE
[eztv] Exception (eztv): /share/CACHEDEV1_DATA/.qpkg/Qmono/lib/../lib/libMonoPosixHelper.so: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by MaskedPilgrim** [Jackett/Jackett#6478]
This issue is happening for all indexers. 

Jackett Version 0.12.1053.0 
Qmono Version: 5.20.1.19

**Comment by garfield69** [comment]
if its happening for all indexers then it is not likely to have anything to do with jackett.
could be a qmono issue or a network issue or maybe a DNS issue.
But to help you further we are going to need more information.

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test for just one indexer (don't need to overload the logs with extra data).
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by MaskedPilgrim** [comment]
So it turned out to be a QMono issue. I rolled it back and the issue went away.
