### ISSUE TITLE
[iptorrents]  (Config) Unable to config

### ISSUE THREAD

**Issue by soldius** [Jackett/Jackett#6485]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues. - i can log in using browsers no problem.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved. - using latest version available in Unraid
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting - included attachement.

(At the bottom of your Jackett Dashboard page) **Jackett version**:  Version 0.12.1053.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------
[log.txt](https://github.com/Jackett/Jackett/files/3918024/log.txt)

I have confirmed that I am using the latest version in Unraid and has checked my iptorrents accounts, which is fine. However, I am unable to add the indexer and config it. Please let me know if you need any other information. Thank you.

**Comment by garfield69** [comment]
works for me on my win10, ubuntu18 and mojave platforms.
But lots of users have trouble with IPTorrents on other platforms.
maybe this will help https://github.com/Jackett/Jackett/issues/6446#issuecomment-560093162

**Comment by JoeMShanahan** [comment]
@garfield69 The help in there did not help me resolve this.

**Comment by garfield69** [comment]
that is unfortunate. 
But given the many open tickets for IPtorrent users on Linux platforms, I am unable to help further. It is beyond my expertise. Sorry.

**Comment by Bodger5002** [comment]
I am receiving the same error. Seems to have stopped working sometime in the last week. I've tried the latest and development versions. Stopped and deleted the docker container, as well as removed the config files. 

As soon as I click configure on IPTorrents, I get "Request to Jackett Server Failed'.

**Comment by ngosang** [comment]
I have IPTorrents in Linux and everything is fine. Configuration, test, empty search, text search...
Update to latest Jackett version and try different domains.

**Comment by tsposato** [comment]
I created my own iptorrents indexer then I was able to add it from the GUI and configure with my username and password.

[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://ipt.lol/"
  },
]

Add the above into /usr/local/jackett/Indexers and call it iptorrents.json then restart and see how you go.

**Comment by ngosang** [comment]
We did some changes in IPTorrents code to improve the debug information. Please, could you update to the latest version (Jackett 0.12.1746 or newer) and provide feedback? If there is a exception, enable the `Enhanced logging` and post the logs. Thank you!

**Comment by soldius** [comment]
Hello, I just got around to testing this. I tried both creating the iptorrents indexer @tsposato and the original iptorrents.json and both give me the error again. The enhanced log is attached. Thank you everyone for your continued efforts :).
[log.txt](https://github.com/Jackett/Jackett/files/4225837/log.txt)

**Comment by jaffa374** [comment]
I also have this issue. Latest jackett updated docker container to latest, all other trackers open up fine if I want to add them, but iptorrents just fails to open at all.

**Comment by garfield69** [comment]
Jackett 0.13.173
