### ISSUE TITLE
Animetorrents error

### ISSUE THREAD

**Issue by totesfabulous** [Jackett/Jackett#649]
Hi,

I am using Jackett Version 0.7.539.0 and I tried to add Animetorrents.me. When I try to sign in (doesn't matter what is entered) I get the following error:

 Configuration failed: Could not load file or assembly 'System.Net.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

**Comment by kaso17** [comment]
In case you're running it on Linux/mono make sure the mono-devel package is installed.

**Comment by kaso17** [comment]
I assume this fixed it.
