### ISSUE TITLE
[REQ] PussyTorrents

### ISSUE THREAD

**Issue by awsms** [Jackett/Jackett#6491]
Would love to see this tracker added to Jackett since it's horrible to browse because of the extremely bloated interface by ads and the shady javascripts.
It's the sister site of TorrentLeech, only for porn. It has the exact same interface as https://classic.torrentleech.org/

Signups are open atm: https://pussytorrents.org/user/account/signupopen

**Comment by garfield69** [comment]
not sure why this was marked as needing c#, the results appear to be regular html.
maybe it was that reference to torrentleech.org which is a c# indexer.
But I will try to write a yaml indexer for it ans see if I can get it to work.

**Comment by garfield69** [comment]
Jackett 0.14.459

**Comment by garfield69** [comment]
https://pussytorrents.org/user/account/login/ while processing the login credits: cloudflare A timeout occurred Error code 524

**Comment by ilike2burnthing** [comment]
back up
