### ISSUE TITLE
[req] BullTorrent

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6497]
~https://www.toros.co/ has 4,319,702 torrents according to https://torrentz2.eu/help#indexed~

https://www.bulltorrent.com/

**Comment by garfield69** [comment]
try out jackett 0.12.1096

**Comment by ngosang** [comment]
@garfield69 It's working fine, but you have to apply the lowercase fix. I tried with `Morty 402 castellano` and returns 0 results.

**Comment by ilike2burnthing** [comment]
https://www.toros.co/  - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.toros.co/ - ERR_CONNECTION_REFUSED

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://www.toros.co/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.toros.co/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
v0.20.756

**Comment by ilike2burnthing** [comment]
https://www.bulltorrent.com/ - Connection timed out - Error code 522

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6497#issuecomment-1460019249

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.bulltorrent.com/ cloudflare Web server is returning an unknown error Error code 520

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
not for me, still seeing https://github.com/Jackett/Jackett/issues/6497#issuecomment-1616812892

**Comment by ilike2burnthing** [comment]
Ah, I should really double-check with Uptrends when it's a more recent report.

What do you think, only keep marked as down if it's down for more than half (third?) of the checkpoints? Or if it's down for even one is that enough to keep it marked as down?

**Comment by garfield69** [comment]
I dun'no. How about majority rules? So if 22of43 or more CP are offline then mark as down?

**Comment by ilike2burnthing** [comment]
Sounds good!

**Comment by garfield69** [comment]
just 6 uptime now with http protocol error, so I'm calling this one back online.

**Comment by garfield69** [comment]
https://www.bulltorrent.com/ cloudflare Web server is returning an unknown error Error code 520

**Comment by garfield69** [comment]
online.
now only 6 uptime are offline

**Comment by garfield69** [comment]
https://www.bulltorrent.com/ cloudflare SSL handshake failed Error code 525

**Comment by garfield69** [comment]
https://www.bulltorrent.com/ redirects to shafeehaque.com a domain parked/forsale page

**Comment by garfield69** [comment]
v0.21.1250
