### ISSUE TITLE
Support changing the base url

### ISSUE THREAD

**Issue by Sparticuz** [Jackett/Jackett#65]
From https://github.com/zone117x/Jackett/issues/133

**Comment by WhatFox** [comment]
Duplicate #10

**Comment by AdamVig** [comment]
@Sparticuz Can we reopen this?

This is not a duplicate of #10. Issue #10 talks about changing the URLs of trackers, whereas this issue talks about changing the base URL of the entire web interface.

This is necessary to support reverse proxying. For example: I have Jackett's web interface behind `example.com/jackett`. It should be looking for its resources (CSS, JS, images) at  `example.com/jackett/filesize.min.js` but instead, it looks for `example.com/filesize.min.js`.

Sonarr has a setting under General -> Start-Up called *URL Base*, which allows you to add a plaintext URL prefix for use with reverse proxies.

Could something like that be implemented in Jackett?

**Comment by Sparticuz** [comment]
@AdamVig I believe that #151 will fix this, but I'm not sure.

**Comment by AdamVig** [comment]
@Sparticuz Yes, that pull request will fix this problem! Thank you.
