### ISSUE TITLE
[yourbittorrent] the domain is fake

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6500]
I think the domain we are using https://yourbittorrent.host/ is fake.
Torrentz2 is using:
* https://yourbittorrent.com/ => https://torrentz2.eu/help#indexed
* https://yourbittorrent2.com/ => https://torrentz2.eu/f4fbf753c720a8860469fbd3326cb4239dc1d01e

The site looks totally different...

**Comment by garfield69** [comment]
yes, was switched to .host knowing it was a clone due to https://github.com/Jackett/Jackett/issues/5417#issuecomment-524074118
but I see that I can now access .com again so I will switch it back.

**Comment by ngosang** [comment]
@garfield69 this is a different issue, but maybe get fixed at the same time. If I search `Morty 402 castellano` in Jacket 0 results. In the website 2 results (in the good one and in the fake)

**Comment by ngosang** [comment]
@garfield69 I see the new domain but please:
1. Add https://yourbittorrent2.com domain too
2. The search `Morty 402 castellano` in Jacket 0 results. In the website 2 results (in the good one and in the fake)

**Comment by garfield69** [comment]
>Add https://yourbittorrent2.com domain too

oh, sorry, forgot while lost in the revert/rework for the new layout. :-( 

>The search Morty 402 castellano in Jacket 0 results. In the website 2 results (in the good one and in the fake)

Hah, same trick as torrentfunk, `morty 402 castellano` works!
 I will convert keywords to lowercase

**Comment by garfield69** [comment]
try out jackett 0.12.1096

**Comment by ngosang** [comment]
All working. Thank you!
