### ISSUE TITLE
[torrentfunk] Add backup link

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6501]
Torrentz2 is using https://www.torrentfunk.com/ => https://torrentz2.eu/help#indexed

**Comment by garfield69** [comment]
and so are we.
https://github.com/Jackett/Jackett/blob/dfc130154ce92e70149ea5a45c9e006b861b177f/src/Jackett.Common/Definitions/torrentfunk.yml#L9

**Comment by garfield69** [comment]
you probably meant https://www.torrentfunk2.com/

**Comment by ngosang** [comment]
Thank you
