### ISSUE TITLE
[torrentfunk] is not returning some results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6502]
The search `Morty 402 castellano`:
* In Jacket 0 results
* In the website 2 results => https://www.torrentfunk2.com/all/torrents/morty-402-castellano.html

**Comment by ngosang** [comment]
@garfield69 It's not working for the case i wrote in the first message.

**Comment by garfield69** [comment]
Hah. I see now. during testing I used `morty 402 castellano`
![image](https://user-images.githubusercontent.com/6933240/70337823-aaf95880-18b0-11ea-8564-f8f10135b566.png)
it is case sensitive!
I'll update the indexer to convert the keywords to lowercase ;-)

**Comment by garfield69** [comment]
try out jackett 0.12.1096

**Comment by ngosang** [comment]
Thank you
