### ISSUE TITLE
[jpopsuki] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by killerqueen619** [Jackett/Jackett#6507]
ss : http://prntscr.com/q6eo0d

**Comment by garfield69** [comment]
jpopsuki is a private site and I do not have an account so I cannot test this for you.
Please provide the **full enhanced log** file. I may be able to see if the error is a simple one I can fix without an account.

1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by killerqueen619** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/3925370/log.txt)

**Comment by garfield69** [comment]
this is the same log as 6508
please turn on enhanced logging, and test one indexer only and drag/drop the log here.

**Comment by garfield69** [comment]
you latest log from 6508 shows
`2019-12-06 01:44:05.7291 Info Found 50 releases from JPopsuki `
which suggest that what ever problem you had with jpopsuki yesterday, it was a temporary issue.
