### ISSUE TITLE
[seedfile] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by killerqueen619** [Jackett/Jackett#6508]
ss : http://prntscr.com/q6eo6x

**Comment by garfield69** [comment]
works for me.
Please provide the **full enhanced log** file so I can get more details on your issue.

1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by killerqueen619** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/3925369/log.txt)

**Comment by garfield69** [comment]
The enhanced-log switch is reset anytime you restart jackett (as may happen after an auto-update for instance).

so the log you provided for your seedfile problem is just a regular one, without the details I need to examine your issue.

Kindly set the enhanced switch on using the jackett dashboard as described in an earlier post, and try again :-)
thanks.

**Comment by killerqueen619** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/3929989/log.txt)

**Comment by garfield69** [comment]
I'm sorry but I am seeing ant debug messages from this log.
```
2019-12-06 08:47:39.7437 Info Found 0 releases from SeedFile 
2019-12-06 08:47:39.7917 Error System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.<TestIndexer>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```
is your Jackett seedfile indexer **Site Link** set to https://www.seedfile.ro/ ?
are you able to access seedfile at address https://www.seedfile.ro/ from your browser?

**Comment by killerqueen619** [comment]
its work now
thank you!
