### ISSUE TITLE
HDCity episode search broken with lasted change

### ISSUE THREAD

**Issue by vinanrra** [Jackett/Jackett#6510]
With this change: https://github.com/Jackett/Jackett/commit/e827ccb52e129e2a807c381ae220945b2eac3987

Sonarr dont detect episode properly i reverted at my jackett the changes and now its working flawless:

This is the pre-changed [HDcity.yml](https://raw.githubusercontent.com/Jackett/Jackett/e5e66bf77001d3f2ae8b14492b746303388d624b/src/Jackett.Common/Definitions/hdcity.yml)

**Comment by garfield69** [comment]
@vinanrra could you give us an example of a tv series and episode that you were searching for on sonarr which no longer works when e827ccb52e129e2a807c381ae220945b2eac3987 was active. Thank you.

@TuGeek  please review and test your hdcity changes from e827ccb52e129e2a807c381ae220945b2eac3987 in light of the report from this ticket. Thanks.

**Comment by vinanrra** [comment]
When i search i get always 0 result of HDCity even if they exist i tried with so many series and all of them give me nothing some examples are:

El padrino de harlem
Mandalorian

But its a "general" bug and its seems with changes at Episode conversion at hdcity.yml

**Comment by TuGeek** [comment]
Fixed with #6519 

Thanks @vinanrra for catch this bug.

**Comment by garfield69** [comment]
try out jackett 0.12.1096
