### ISSUE TITLE
[yggtorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by jvenezia** [Jackett/Jackett#6513]
Tried https://github.com/Jackett/Jackett/issues/6473#issuecomment-560978023

Jackett Version 0.12.1091.0

**Comment by jvenezia** [comment]
Duplicated issue is not solved. The linked comment that proposes a solution does fix the usual "selector" bug due to the domain name changing, but now I have no results.

**Comment by garfield69** [comment]
works for me.
if you want help with this then:

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by krushkin** [comment]
Hi everyone,

same error here : "Found no results while trying to browse this tracker"

[log.txt](https://github.com/Jackett/Jackett/files/3931552/log.txt)

thanks for your help

**Comment by jvenezia** [comment]
My logs are very similar to @krushkin , let me know if you need mine too.

**Comment by mrik974** [comment]
After watching your logs I noticed the YggTorrent URL Jackett was trying to reach was `https://yggtorrent.ws/new_search/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date`
Issue #6473 is the fix you're looking for.
The URL should begin with `www2.yggtorrent.ws` and not `yggtorrent.ws`. To fix this you should change the "search/download URL" in your Jackett settings for Yggtorrent.

**Comment by garfield69** [comment]
@krushkin  you log shows that your jackett tried to use the following url
`https://yggtorrent.ws/new_search/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&page=50`

which tells me that you did not follow all the steps in  https://github.com/Jackett/Jackett/issues/6473#issuecomment-560978023 correctly.

the **Search and download URL** is currently set to `yggtorrent.ws` which will not work.

1. access your jackett dashboard and use the **wrench** icon to edit your YGGTorrent indexer config.
2. set the **Search and download URL** to `www2.yggtorrent.ws`
3. Click **OKAY**
4. if you get an error, click **CLOSE** then edit again and click OKAY. it should save the second time.

thanks.

**Comment by garfield69** [comment]
@mrik974  oh snap! you posted just before mine with exactly the same info. thanks ;-D

**Comment by garfield69** [comment]
@jvenezia  reapply https://github.com/Jackett/Jackett/issues/6473#issuecomment-560978023
if you cant get it to work then provide the logs so I can see what your jackett is doing.
Thanks.

**Comment by krushkin** [comment]
Thank you guys for your help ! It works fine now ^^
Ygg is changing everytime, so I didn't notice this mistake, sorry for this :(
BR

**Comment by jvenezia** [comment]
Got it working after removing and adding it back with the correct urls.

It happens so often with YGG, is there any way we could automate this? When YGG changes domain, jackett would automatically update the configuration.

Thanks for the help

**Comment by garfield69** [comment]
the problem with yggtorrent is that they are the **only** site that uses different url for their login and search engines.
Jackett was built on the assumption that the one address to the server would be enough, as indeed it is for all the other 400 sites it has indexers for.
So there is no Jackett automation option currently available to handle a site that use two addresses, hence the need to manually intervene.
To automate support for yggtorrent will require C# code, and no one has volunteered to provide a solution so far.
