### ISSUE TITLE
Limit in indexer number ?

### ISSUE THREAD

**Issue by dorel14** [Jackett/Jackett#6516]
Hello ,
Is there a limit in adding indexers , i d like to add all free indexers and i can not add more than 74
Jackett Version 0.12.1091.0
Debian 9

**Comment by garfield69** [comment]
strange. I currently have 214 indexers on my active list
![image](https://user-images.githubusercontent.com/6933240/70342560-29a6c380-18ba-11ea-8cf9-2669da6b7561.png)
so I do not know what the problem on your debian... %-/

**Comment by luchmhor** [comment]
I have currently the same behavior. Adding of indexers fails (an I only got 10 in my list). And nothing shows up in the log ...

**Comment by garfield69** [comment]
peculiar.
if you are using a chrome browser, can you press **F12** to open the *development tools* page, and click on the **console** tab to view the session log. anything there?
Also, you say nothing shows up in the jackett log, but is that the **enhanced** log?
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by ngosang** [comment]
I'm using Firefox and I have almost 300 enabled without problems. The search in all trackers at the same time takes a long time, but more realistic use cases are working well.
We need details about the browser you are using and the OS.
