### ISSUE TITLE
Feature request: search from highlighted text in browser

### ISSUE THREAD

**Issue by wellloaded** [Jackett/Jackett#6518]
I have a content I would like to search via Jackett. this content being held within a webpage as a simple text, e.g. say a song title
It would be great if we could just highlight the text on the page itself and perhaps right click+search in Jackett

this would save tons of clicks!

P.S. the utility "Everything" has something similar and they integrated like this: https://www.voidtools.com/forum/viewtopic.php?f=5&t=7099&p=23377#p23377

**Comment by ngosang** [comment]
This will require developing an external browser addon to interact with Jackett API. It's easy to do, but it's out of the scope of this project. Must be done by someone else.

**Comment by garfield69** [comment]
closed as stale.
