### ISSUE TITLE
[shokweb] is not returning results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6536]
Jackett Version 0.12.1099.0
Tracker: shokweb
Searches with results in the web but not in Jackett:
* silicon valley
* Harry Potter
* 1080p thrones

**Comment by garfield69** [comment]
I don't think this site is active anymore. there is nothing newer than 2 years ago, which also coincides with their certificate which expired Dec 2017

**Comment by ngosang** [comment]
I don't use that website, but can be useful to search old content. If they don't change the site, you won't have to update the definition :)
