### ISSUE TITLE
AnimeTorrents: can't add config to Jackett

### ISSUE THREAD

**Issue by Githubtordl** [Jackett/Jackett#654]
I'm running v0.7.555 of Jackett.

Every time I try to add the AnimeTorrents config on Jackett, I get the following message:
![animetorrent issue1](https://cloud.githubusercontent.com/assets/22656503/20055975/c673c9c0-a4db-11e6-9822-76b5a23a6cb8.PNG)

Jackett logs:

![image](https://cloud.githubusercontent.com/assets/22656503/20056014/f6ae4a84-a4db-11e6-8de7-32e07280b8d0.png)

**Comment by kaso17** [comment]
Any chance that you're still a newbie user?

**Comment by Githubtordl** [comment]
Yea, my rank on AnimeTorrent says 'Newbie' is that what's causing this? I can browser/search for a torrent on the AnimeTorrents website without any problem.

Before installing the latest version of Jackett. I was able to add AnimeTorrents to Jackett and also do a manual search from the Jackett dashboard without any problem, it would list the torrents I would search for. The problem in the last build was that I couldn't add AnimeTorrents to Sonarr. (Link to this issue: https://github.com/Jackett/Jackett/issues/644).

But now this issue is different, it doesn't seem to find any results when Jackett is trying to add the AnimeTorrents config.

**Comment by kaso17** [comment]
With this most recent patch it should be usable with newbie users

**Comment by Githubtordl** [comment]
I've tried reinstalling Jackett, re-checked the version number but I'm still getting the above error

**Comment by kaso17** [comment]
There hasn't been a new release yet

**Comment by kaso17** [comment]
It's fixed in the pre-release v0.7.570

**Comment by Githubtordl** [comment]
I can confirm this has been fixed now. Thanks @kaso17
