### ISSUE TITLE
[TorrentFunk] Unrelated results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6548]
Jackett Version 0.12.1099.0
Tracker: TorrentFunk

The search `mientras dure` returns a lot of unrelated results.

**Comment by garfield69** [comment]
Thank you for reporting the faults on all those public trackers.
jackett 0.12.1115 should have fixes.

**Comment by ngosang** [comment]
@garfield69 Thank you for fixing them! I tested all of them and they are working. I will report a few more today but I don't have access to most private trackers so I can't test.
