### ISSUE TITLE
Search all indexer option

### ISSUE THREAD

**Issue by IllMethods** [Jackett/Jackett#6549]
Can we have one call to jackett that will search all indexers for say radarr or sonarr? Or have it so we can set certain indexers into one group to be used in sonarr or radarr?

Just seems like it would be a lot easier than added seperate indexers in sonarr and radarr, just add them to a group within jackett.

**Comment by garfield69** [comment]
there is an aggregate search indexer called **ALL**. see https://github.com/Jackett/Jackett#aggregate-indexers for details.

but it is no recommended for use with Sonarr, particularly these days where many sites fail to respond in a timely manner, which will break the search result response window for Sonnar, and you will fail to get **any** results.
You are far better to invest the time to add the indexers you want to use individually.

Also, as an aside, it is excessive overkill to add so many indexers to Sonarr. Many indexer all produce the same results, so IMO you are better off just picking five or so of your favourites and go with that. Having the rest defined only slows down your result response time for no additional benefit.

**Comment by IllMethods** [comment]
Even grouped search would still be good then.

I only use one indexer for Sonarr which is btn. But radarr is a different matter all together.

**Comment by garfield69** [comment]
already a ticket open for this, #2185 
but no C# dev has volunteered to implement.
