### ISSUE TITLE
torznab - TorrentPotato fail 

### ISSUE THREAD

**Issue by fetzig** [Jackett/Jackett#655]
Description is wrong:

> Adding a Jackett indexer in CouchPotato
> 
> Go to Settings > Searchers.
> Enable TorrentPotato and in the host field enter the TorrentPotato host of one of the indexers.
> For the Passkey use the API key. Leave username blank.

CouchPotato will create an url out of entered data looking like this:
http://localhost:9117/torznab/demonoid?imdbid=tt4196776&user=&passkey=xxx&user=&passkey=xxx

Jackett returns:
`<string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">Incorrect API key</string>`

using url param apikey instead of passkey returns expected response.

Thus I would suggest you accespt apikey and passkey as params for the Api Key.

Thx.

**Comment by mathieugeissler** [comment]
Hi, I have the same problem how do you fix this ?

**Comment by kaso17** [comment]
The original author supplied a torznab url to couchpotato, for couchpotato you've to use the potato feed.

**Comment by kaso17** [comment]
The instructions from the Web Interface are a little outdated, I've updated them with 571a5a073e622a72998bcb8f0d8a01ed5e03d541

**Comment by chmercesmoreira** [comment]
I have the same problem but with another tracker: b2s-share
`<string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">Incorrect API key</string>`
Jackett is returning the queries properly but when I try do add it on sonarr (URL + API key) it doesn't work.
