### ISSUE TITLE
[legittorrents]  Value was either too large or too small for an Int32

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6558]
Maybe is related to this one => https://github.com/Jackett/Jackett/issues/6550

Jackett Version 0.12.1115.0
Tracker: legittorrents
Search: iso

```
Manual search for "iso" on legittorrents with 14 results.
CardigannIndexer (legittorrents): Error while parsing row '
<tr>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="index.php?page=torrents&amp;category=14">
			<img src="http://www.legittorrents.info/style/FreTorLT/images/categories/linux.png" border="0" alt="Linux Distributions">
		</a>
	</td>
	<td class="lista" valign="middle" style="padding-left:10px;overflow:auto;">
		<a href="index.php?page=torrent-details&amp;id=7bf74c4fd609bf288523f7cd51af3bdbc19df610" title="View details: altlinux-7.0.5-centaurus-x86_64-ru-live-cd.iso">altlinux-7.0.5-centaurus-x86_64-ru-live-cd.iso</a>
		(<span style="color:red">EXT</span>)</td>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<a href="download.php?id=7bf74c4fd609bf288523f7cd51af3bdbc19df610&amp;f=altlinux-7.0.5-centaurus-x86_64-ru-live-cd.iso.torrent">
			<img src="images/download.gif" border="0" alt="torrent">
		</a>
	</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">
		<time datetime="2018-09-09">09/09/2018</time>
	</td>
	<td align="center" width="30" class="#FFFF00" style="text-align: center;">4294963141</td>
	<td align="center" width="30" class="#FFFF00" style="text-align: center;">492</td>
	<td align="center" width="30" class="lista" style="text-align: center;">703</td>
	
	<!-- <td align="center" width="45" class="lista" style="text-align: center;">N/A</td> -->
</tr>':

System.Exception: Error while parsing field=seeders, selector=td:nth-of-type(5), value=4294963141: Value was either too large or too small for an Int32.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1489

```

**Comment by garfield69** [comment]
yeah I guess no one thought that seeders would ever exceed max_int (2,147,483,647).
but a torrent with 4 billion seeders seems a little unreal ;-D

**Comment by ngosang** [comment]
Someday we will become an interplanetary specie, hahaha.
If it's easy, you can check the string length < 7 in the .yml or the number of commas < 2. If it's complicated, close the issue.

**Comment by garfield69** [comment]
this is not within the yaml indexer control. its in the cardigann processor.
I'm looking to see if changing the torznab default seeders definition from int to long is not going to have implications for the other c# custom indexers that also use the common torznab definition source.

**Comment by ngosang** [comment]
I know, but the site is wrong and I don't see a reason to change the c# code... I suggested instead to do a trick in the Cardigann processor for that site. But I don't know if it's possible.
If string(2,147,483,647).length < 7 { ok } else { 0 }

**Comment by garfield69** [comment]
nah, the cardigann's yaml support does not currently support conditional blocks of that kind.
that would require adding new c# to the cardigann processor.
as you say, its an error in the data from the site.
not worth following up on. closing.
