### ISSUE TITLE
[torrentdownloads] published date

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6578]
I see `torrentdownloads.info` doesn't provide published date in the web page, but it does in the rss search. It's possible to parse the rss with Cardigann?
https://www.torrentdownloads.info/rss.xml?type=search&search=morty+castellano

**Comment by garfield69** [comment]
No, Cardigann can only handle html.
Parsing a json feed would require a custom c# indexer.
They exists, I am aware of several c# indexers that process json output from sites via the sites' api. 
but I am not up to coding a c# indexer from scratch or adapting the source from a similar site, too much c# for me ;-b

**Comment by ngosang** [comment]
All clear. This is not important enough to rewrite the tracker. :)
