### ISSUE TITLE
[aniRena] the guid field is missing

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6581]
Jackett Version 0.12.1115.0 
Tracker anirena
Search: 720p

I get results with the field guid = null and comments = null. The comments it's ok since the site doesn't provide a link. But I think the guid can be a problem. It doesn't affect the Jackett UI, but I think the RSS feed is not valid without the guid. I used this validator => https://validator.w3.org/feed/

```
{
  "FirstSeen": "0001-01-01T00:00:00",
  "Tracker": "AniRena",
  "TrackerId": "aniRena",
  "CategoryDesc": "TV/Anime",
  "BlackholeLink": null,
  "Title": "[Erai-raws]  Detective Conan - 961 [720p].mkv",
  "Guid": null,
  "Link": "http://127.0.0.1:9117/dl/aniRena/?jackett_apikey=ygm5k29tomyy11df265gio7iouhqx9k4&path=Q2ZESjhBYnJEQUIxeGdOQ21admtZdjAzUVB6YXV0NUxvNXY0UFNYeTFNTDdWRzFrQ3ZMTkdyQ3k1cUxMeURCV1oyMVZ2aGthajQyVlJqZXEwTGdmM3U5cWsxVEVheThsLTdfS1NtbG5laWNka1QtZ05NTGtzVlRIQVJ1QThoVlRHZDdOS1dXb25jQTFEeURTQ2g4ZUxUNlBGM2Q3Znp2WHhUUTNtejQ4MDMwSEJIUkI&file=%5BErai-raws%5D++Detective+Conan+-+961+%5B720p%5D.mkv",
  "Comments": null,
  "PublishDate": "2019-12-11T00:06:23.5546492Z",
  "Category": [
    5070,
    100002
  ],
  "Size": 739172672,
  "Files": null,
  "Grabs": 27,
  "Description": null,
  "RageID": null,
  "TVDBId": null,
  "Imdb": null,
  "TMDb": null,
  "Seeders": 3,
  "Peers": 2,
  "BannerUrl": null,
  "InfoHash": null,
  "MagnetUri": "magnet:?xt=urn:btih:e982bafd68163bebf44f2063cf56b57dbcbd77e7&dn=%5BErai-raws%5D+Detective+Conan+-+961+%5B720p%5D.mkv&tr=http%3A%2F%2Ftracker.anirena.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.uw0.xyz%3A6969%2F&tr=http%3A%2F%2Fanidex.moe%3A6969%2Fannounce&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce",
  "MinimumRatio": 1.0,
  "MinimumSeedTime": 172800,
  "DownloadVolumeFactor": 0.0,
  "UploadVolumeFactor": 1.0,
  "Gain": 2.065224587917328
}
```

**Comment by garfield69** [comment]
tricky. the cardigann processor adds the guid based on the existence of either the comment or details link being available.
```c#
	case "details":
		var url = resolvePath(value, searchUrlUri);
		release.Guid = url;
		release.Comments = url;
		if (release.Guid == null)
			release.Guid = url;
		value = url.ToString();
		break;
	case "comments":
		var CommentsUrl = resolvePath(value, searchUrlUri);
		if (release.Comments == null)
			release.Comments = CommentsUrl;
		if (release.Guid == null)
			release.Guid = CommentsUrl;
		value = CommentsUrl.ToString();
		break;
```
it appears anirena has neither.
I'll have to troll through some of the c# indexers and see if I can find one that has neither ans see if they coded the guid from some other acceptable url or if they also left it null.

**Comment by garfield69** [comment]
seems the magnet URI is an acceptable alternative. I will add it to the Cardigann's magnet case block.

**Comment by garfield69** [comment]
i'm in the process of adding sort order options to the indexer configs of any sites I have access to.
many of the rest may never get updated until some one raises a ticket and can provide access.
So I'll refresh those with my pool and test and check the logs for errors as I go.

**Comment by ngosang** [comment]
@garfield69 IMHO, you are supporting 400 sites that change a lot. The only way to keep this up to date is automation.
1. Have a Jackett instance running 24x7 in some server. This Jackett should have all trackers configured and auto-update enabled. This will test that Jackett updates are working and will be used in the manual/automated tests. If this project have several collaborators, doesn't make sense that everybody has 300 accounts... a shared server makes sense. I can host it.
2. Automatic tests. The automatic tests will be launched everyday in the 24x7 Jackett. For each tracker it will test: 1 word search, 2 word search, uppercase, reverse order, bad search, result fields, backup domains, sort order... The test will be in some git repository and can be updated anytime.
3. Reporting. The automatic tests will generate a report with all the results. Can be an html with colors, email errors... When there are errors you will see clearly the tracker, search term, number of results and exception. Can be automated to open issues in Github if necessary.

Think about this, it will save a lot of time.

**Comment by garfield69** [comment]
what you are proposing sounds wonderful, and if you can provide a server then I applaud your commitment to helping out with Jackett.
Testing for the common site-has-changed-domain would particularly be useful.
I do have one reservation however:
do not include private indexers.
reasons:
public and semi-private are open and if logins on semi-private site get suspended due to errors its no big deal.
But private sites are more fussy about violations, and can suspend or even delete your account.
Many private sites use cookies which expire and require the indexer configs to be reloaded with new cookies at regular intervals. No the kind of thing that can be recovered from with automation perhaps.

Many private sites auto-redirect you to Notices  or unread mail pages after login which Jackett treats as errors.
And finally, in these days of extreme malicious hacking, having profiles with private login data on a server makes me uncomfortable. Stories are published daily about data theft and I would not want anyone's private-site logins made public by accident or intent.

**Comment by ngosang** [comment]
@garfield69 moving the conversation to another issue #6588
