### ISSUE TITLE
Radarr error searching IPTorrents with invalid character

### ISSUE THREAD

**Issue by bclinton** [Jackett/Jackett#6582]
Some torrents requested through Radarr using Jackett with IPTorrents produces an invalid character error, see below:

`HTTP Error - Res: [GET] http://192.168.1.246:9117/api/v2.0/indexers/iptorrents/results/torznab/api?t=movie&cat=2000,2010,2030,2040,2050,2060,2070&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=2334873: 500.InternalServerError
{
  "result": "error",
  "error": "'\u000f', hexadecimal value 0x0F, is an invalid character.",
  "stacktrace": "   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)\n   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)\n   at System.Xml.XmlWellFormedWriter.WriteString(String text)\n   at System.Xml.Linq.ElementWriter.WriteStartElement(XElement e)\n   at System.Xml.Linq.ElementWriter.WriteElement(XElement e)\n   at System.Xml.Linq.XElement.WriteTo(XmlWriter writer)\n   at System.Xml.Linq.XContainer.WriteContentTo(XmlWriter writer)\n   at System.Xml.Linq.XNode.GetXmlString(SaveOptions o)\n   at System.Xml.Linq.XNode.ToString()\n   at Jackett.Server.Controllers.ResultsController.CreateErrorXML(Int32 code, String description) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 444\n   at Jackett.Server.Controllers.ResultsController.GetErrorXML(Int32 code, String description) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 432\n   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 425\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29"
}`

**Comment by garfield69** [comment]
is Blue.Jasmine.2013 the only one that sonarr chokes on or have you found others?
just want to get a feel for whether its just this one title, or if there are more titles in iptorrents that also contain invalid characters, and therefore if I need to try to filter out more than this one invalid char.

**Comment by bclinton** [comment]
I have not. Everything else seems to work fine and I've tested 10 or so titles.

**Comment by garfield69** [comment]
ok thanks. I'll see about adding a replace for that one char then.
it's similar to what we had to do for 1337x and ThePirateBay, but IPTorrents is the first indexer written in C#, which is different from the others which were yaml indexers.
I'll post when I've published the fix.

**Comment by garfield69** [comment]
jacket 0.12.1146

**Comment by bclinton** [comment]
Worked like a charm. Thx a million.
