### ISSUE TITLE
[REQ] TopNow.se

### ISSUE THREAD

**Issue by dausruddin** [Jackett/Jackett#6583]
I want to request for http://topnow.se/ to be implemented. 

Thanks in advanced!

**Comment by garfield69** [comment]
jacket 0.12.1146

**Comment by dausruddin** [comment]
Wow. That was really fast. I really appreciate it. Thanks a lot!

**Comment by ilike2burnthing** [comment]
https://topnow.se/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://topnow.se/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up
