### ISSUE TITLE
[1337x] Download Link 404s from Torznab RSS Feed

### ISSUE THREAD

**Issue by HeroCC** [Jackett/Jackett#6589]
I tried to get 1337x working, however it seems to fail. The link in the RSS feed leads to a 404, and Jackett complains about
```
12-11 17:18:33 Error Error downloading 1337x  System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at Microsoft.AspNetCore.WebUtilities.WebEncoders.Base64UrlDecode(String input)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/DownloadController.cs:line 46
```

I tried messing with the Definition file but couldn't get it to work, and I'm not experienced enough with c# to poke around too elsewhere.

Seems like the 'path' argument is null and so L46 in DownloadController.cs fails
`path = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(path));`

I chatted a bit on the Jackett discord and someone else was able to reproduce the issue so it's not just me. 

Any help would be much appreciated!

To Reproduce:
* Add 1337x.to as a tracker
* Navigate to `http://jackett:9117/api/v2.0/indexers/1337x/results/torznab/api?apikey=yourkey&t=search&cat=&q=qxr`
* Attempt to Navigate to a link inside the `<link>` tags
* Expected: .torrent file download, Actually: 404s

**Jackett version**:  `0.12.1146.0`

**Comment by garfield69** [comment]
yeah. works from the dashboard 1337x search, regardless of setting the 1337x config to fetching magnet or itorrent.org links, but as you say the rss feed links does not work.
however this is beyond my skills to analyse, its all buried deep in c# someplace and I am not familiar with any of it.
ping to any c# dev volunteer who can assist with this ticket.

**Comment by garfield69** [comment]
Jackett 0.12.1572
