### ISSUE TITLE
Tracker notifications scraper

### ISSUE THREAD

**Issue by kaso17** [Jackett/Jackett#659]
Once a tracker is added to Jackett I pretty much only access it via Jackett. That way I often miss notifications about important tracker changes or new personal messages (Some tracker's don't support email notifications).
I would like a feature which allows indexers to push notifications to Jackett so I can regularly check Jackett for new notifications without having to visit all trackers one by one.

**Comment by armani316** [comment]
@kaso17 I have a question related to this point: Does logging in to a tracker through Jackett count as a browsing activity on said tracker? Since some trackers, that do not allow parked accounts, ban idle/dormant/inactive accounts after a certain period of time, I wonder whether logging in and/or searching on Jackett would prevent that.

**Comment by kaso17** [comment]
If you search for a specific torrent it should count as browsing activity.
Some indexers use the rss feed in case the search string is empty (which probably doesn't count as activity)

**Comment by armani316** [comment]
@kaso17 Sounds good. Just to clarify, did you mean manually searching for a specific torrent on one indexer alone, or would manually searching across all indexers at once count as browsing activity in all of them?

**Comment by savahu** [comment]
@kaso17 Couchpotato and Sickrage searching for something (automated), does that also count as browsing activity? :)

**Comment by kaso17** [comment]
All searches for non empty search strings should count as activity (They imitate a normal search like you would do in your browser). It doesn't matter is you search each tracker on it's own or all at once.

**Comment by garfield69** [comment]
Closing as stale.
