### ISSUE TITLE
FAILED with using Script (http://greenfrog.eu5.net/rpildsv3.php)

### ISSUE THREAD

**Issue by waynerigley** [Jackett/Jackett#6598]
root@SRDNJ:/# ./lds-deploy-v3.sh

 -- Setup script is running !!!
 -- Checking User PI Account
 -- Adding Sonarr repository
 -- Adding Mono repository
 -- Refreshing APT Repositories
 -- Updating System - longer stretch here
 -- Removing Unncessary Software Packages
 -- Installing Mono Complete - it takes long do not panic
 -- Installing Audio Fingerprinting Library for Lidarr
 -- Deploying Jackett
 -- Creating and Starting Jackett Service
ERROR DURING: sudo systemctl is-active jackett
Check /tmp/tmp.SPIRK83eHM for details
root@SRDNJ:/#

**Comment by garfield69** [comment]
whats this?

**Comment by waynerigley** [comment]
was output when installing jacket

**Comment by waynerigley** [comment]
^[[1;31mERROR^[[0m: Could not launch service. The installation might have failed.
Please open an issue on https://github.com/Jackett/Jackett/issues and paste following information:
Jackett directory: `/home/pi/Jackett`
Jackett user: `pi`

activating

**Comment by waynerigley** [comment]
or is it due to me trying to run this script on ProxMox in LXC? i have no frikin clue

**Comment by garfield69** [comment]
which distribution package from https://github.com/Jackett/Jackett/releases did you try to install?
whats ProxMox in LXC?

**Comment by garfield69** [comment]
basically we are only responsible for the distribution packages out of this Jackett Github.
if you are using a 3rd party script to install Jackett (from http://greenfrog.eu5.net/) and it does not work, then you need to go back to the provider of the script.
it's likely they are using the wrong package, or something.
but there is little we can do for you here.

**Comment by waynerigley** [comment]
thank you, that being said ill just do it from this GitHub then. i was only trying to short cut the process as im not the best at installing programs, but ill give it a shot ! thanks for the reply

**Comment by garfield69** [comment]
for pi i recommend following https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above using the Jackett.Binaries.LinuxARM32.tar.gz
if you have a 64bit processor you could try Jackett.Binaries.LinuxARM64.tar.gz

in the event neither package works on your machine, then try following https://github.com/Jackett/Jackett#installation-on-linux-armv6-or-below instead.

**Comment by waynerigley** [comment]
thanks, I Have a server with ProxMox and created a LXC and thats where im trying to install
