### ISSUE TITLE
[hdbitscom] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Shutruk** [Jackett/Jackett#6610]
Hello, when trying to search or test for HD-Bits I get an error:

>  Found no results while trying to browse this tracker.

-------------------------------

Jackett Version 0.12.1198.0

Enhanced log:

https://pastebin.com/LqAhYJcs

**Comment by garfield69** [comment]
unfortunately the stack dump you provided is not much use.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.
