### ISSUE TITLE
[blutopia] Login failed: No form found on https://blutopia.xyz/login using form selector form (Config)

### ISSUE THREAD

**Issue by travisboss** [Jackett/Jackett#6611]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**: 0.12.1136.0 
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**: Does not show mono version am using inside of docker found [here](https://hub.docker.com/r/linuxserver/jackett/)

-------------------------------

**Comment by garfield69** [comment]
if you want help with this you are going to need to provide more info so we can try to see what could be going on.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.
