### ISSUE TITLE
[rutracker] Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by Playrok** [Jackett/Jackett#6612]
Website is accessible in any browser, Jackett Version 0.11.496.0.
ran pkg update and pkg upgrade and it was the newest one available

**Comment by garfield69** [comment]
the package you have found is for version 11.496 and is not recent enough to contain the updated ruTracker indexer that  has can support the current ruTracker web site's html.  
You are going to need version  0.11.703 or newer.
Current latest version is 0.12.1198
We only support packages from this GitHub repository.
Any packages you find via 3rd party supplies are not within our purview.
you will need to contact the supplier and ask them to update their package.
