### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://www.yggtorrent.ws/ using form selector 

### ISSUE THREAD

**Issue by pasnox** [Jackett/Jackett#6616]
1- the site is still reachable and working (moved domain extension to ws though, but it's user editable)
2- tried to upgrade latest version, still does not works
3- The log is what is in the title
4- Jackett Version 0.11.760.0

**Comment by garfield69** [comment]
follow https://github.com/Jackett/Jackett/issues/6473#issuecomment-560978023 
and upgrade to jackett 0.12.* to get the latest indexer updates. 0.11 is well out of date.
