### ISSUE TITLE
[myanonamouse] Looks like your cookies are not really enabled for us (Config)

### ISSUE THREAD

**Issue by pranshumaheshwari** [Jackett/Jackett#6618]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  0.8.929.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**: 6.6.0.161-0xamarin7+ubuntu1604b1

-------------------------------
I am using my email instead of username.

**Comment by garfield69** [comment]
the myanonamouse indexer was changed in Nov 2018 to support the web sites API changes.
Your version of Jackett is far too old and does not include support for the current web site requirements.
If you are running Ubuntu then I recommend you upgrade using the instructions at https://github.com/Jackett/Jackett#install-on-linux-amdx64
or if you are not running a AMD processor then maybe https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above
