### ISSUE TITLE
[REQ] muziekfabriek.org

### ISSUE THREAD

**Issue by DutchDamian** [Jackett/Jackett#6619]
Semi-private Dutch torrent tracker for Dutch audio. The website functions in almost exactly the same way as an already existing Dutch torrent tracker does; Film-Paleis.

**Link:** https://www.muziekfabriek.org/

**Comment by garfield69** [comment]
switched to private.
also download links no longer in search results. will need to fetch from torrent details page.

**Comment by garfield69** [comment]
v0.20.492

**Comment by garfield69** [comment]
https://www.muziekfabriek.org/ returns Web server is down Error code 521

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
[https://www.muziekfabriek.org/ cloudflare ](https://github.com/Jackett/Jackett/issues/6619#issuecomment-1753474260)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.muziekfabriek.org/ cloudflare Web server is down Error code 521

**Comment by ilike2burnthing** [comment]
[v0.21.1422](https://github.com/Jackett/Jackett/releases/v0.21.1422)
