### ISSUE TITLE
[extratorrent-ag] Exception (extratorrent-ag): Request to https://extratorrent.ag/ failed (Error 522) - The tracker seems to be down.: Request to https://extratorrent.ag/ failed (Error 522) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by zoomdbz** [Jackett/Jackett#6623]
This page (https://extratorrent.ag/) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. Always Online™ is powered by Cloudflare \| Hide this Alert
--

Seems down I'd if there is a mirror you can swap to or something.

**Comment by garfield69** [comment]
find us an official mirror and we will add it to the alternate domains list.
