### ISSUE TITLE
Permanent fix for ZamundaNET

### ISSUE THREAD

**Issue by errogue** [Jackett/Jackett#6627]
ZamundaNET indexer fails to work if the default `grid` mode display is selected. The user has to log in and set it to `list` for the indexer to work. It would be nice to do this automatically so no such error would exist in the first place. All you have to do is send a GET request to:
```
/bananas?view=list
```
This is a one-time operation, the setting will be saved in the user's profile server-side.

I read the [definition format](https://github.com/Jackett/Jackett/wiki/Definition-format) but found no suitable way to add this extra request. Is there any easy way to do it? If not, at least a notice should be added to the definition description so the user is aware.

Thanks

**Comment by garfield69** [comment]
unfortunately the cardigann processor does not provide the option to send one time http gets.
but adding an info block to the config is available, so I will provide it.
could you provide the wording for a notice to instruct the user correctly, as I don't have access to the site to view for myself.
thanks.

**Comment by errogue** [comment]
We can send the HTTP GET every time, it won't hurt. Is there an option for that? Multi-step search, or a pre-search task?

**Comment by garfield69** [comment]
Oh is it open again!
I had a login once but then they turned on IP filtering for Bulgarian IP addresses only and I could not be bothered setting up a VPN.
But I tried just not and it let me register and login so we shall see how long that lasts.

No, cardigann supports only what is documented in the wiki.

I'll add a notice to the config, now I can see for myself what the instructions need to say. :-)
