### ISSUE TITLE
[iptorrents] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by B3voholic** [Jackett/Jackett#6628]
When attempting to add IPTorrents as an indexer I get the error "Request to Jackett server failed".  I was able to add it by manually creating the json file but now I get the same error when trying to add in my credentials to get it actually set up.

Any help would be appreciated.

**Comment by garfield69** [comment]
what version of Jackett are you on?
from 0.12.1146 onwards JAckett has a fix for an invalid character in the titles that caused the IPTorrents indexer to fail.
upgrade if you are behind.
