### ISSUE TITLE
AnimeTorrents: Configuration failed

### ISSUE THREAD

**Issue by El-Fitz** [Jackett/Jackett#663]
Hi there !

So, I read the solved issue regarding the mono-devel package, fixed the first one.
But now I get "Configuration failed: Found no results while trying to browse this tracker"

Any idea ?

Thanks, and have a great day !

**Comment by El-Fitz** [comment]
Seemed to have solved itself (it's now in the list of trackers), but testing it gives: 

> Test failed for animetorrents: Found no results while trying to browse this tracker

**Comment by kaso17** [comment]
dupliate #654
