### ISSUE TITLE
[scenetime] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by LAP87** [Jackett/Jackett#6632]
jackett gives error
[log.txt](https://github.com/Jackett/Jackett/files/3975449/log.txt)

**Comment by garfield69** [comment]
unfortunately the regular log you provided does not provide enough info to help diagnose this problem.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by LAP87** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/3979714/log.txt)
Done, no idea what i was supposed to redact tho?

**Comment by garfield69** [comment]
the log you provided shows that when Jackett tried to use `https://www.scenetime.com/browse.php?cata=yes&sec=jax` , scenetime responded with a `Returning Redirect => https://www.scenetime.com/login.php`

if the Jackett scenetime indexer was working previously, then most likely the cookie you loaded into the Jackett scenetime config has expired.
You will need to use your browser to login to scenetime directly, clear your mail and any outstanding notices or alerts, and then copy and past/replace the cookie from that browser session to your Jackett scenetime indexer config and you should be good to go, until the next time the cookie expires.

if this is the first time you are setting up the Jackett scenetime indexer, then the cookie string you provided was not accepted by scenetime. your cookie string should look similar to `__cfduid=d*********1; PHPSESSID=p**********d;`
Remember that the cookie has to come from a browser running on the same machine that is running Jackett.

**Comment by LAP87** [comment]
Ah, thanks, i had some issues prior to this with my config files after an auto-update so i made a fresh install and moved over the indexers from the old install, my bad then.
