### ISSUE TITLE
v1245 broke windows service

### ISSUE THREAD

**Issue by LAP87** [Jackett/Jackett#6633]
The latest update of Jackett killed windows services function, it starts and dies immediately even when i try to start it manually via services.msc
The previous version works (v1227), but i had to give it a fresh folder/install for it to work again.
[log.txt](https://github.com/Jackett/Jackett/files/3975467/log.txt)

**Comment by LAP87** [comment]
v1245, After fresh install it pops an windows error, something about user privilegies needing to be upped (regarding the jackett tray starting).

**Comment by ssurfertuga** [comment]
Linux service is broken too! [#6634](https://github.com/Jackett/Jackett/issues/6634)

**Comment by garfield69** [comment]
>The latest update of Jackett killed windows services function

I doubt very much it has anything to do with the last updates, because for the last 10 releases all that has been published are indexer updates. There has been no changes to the Jackett source code, or install scripts or anything else for that matter.

The last time I saw something like Net.Sockets.SocketException it turned out to have something to do with proxy setup changes.
resetting the ServerConfig.json file by editing it and setting the proxy and other related settings to defaults may help to clear the problem.
```json
{
  "Port": 9117,
  "AllowExternal": false,
  "APIKey": "r***redactded***5",
  "AdminPassword": null,
  "InstanceId": "i0***redacted***9q",
  "BlackholeDir": "",
  "UpdateDisabled": false,
  "UpdatePrerelease": true,
  "BasePathOverride": "",
  "OmdbApiKey": "",
  "OmdbApiUrl": "",
  "ProxyUrl": "",
  "ProxyType": 0,
  "ProxyPort": null,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true
}
```

> but i had to give it a fresh folder/install for it to work again.

Hmm. if you are now getting authorisation issues then something has gone wrong with your setup of the fresh folder as you put it.

everything for jackett on windows is usually coming out of C:\ProgramData\Jackett
what do you mean you gave it a fresh folder?

**Comment by LAP87** [comment]
> > The latest update of Jackett killed windows services function
> 
> I doubt very much it has anything to do with the last updates, because for the last 10 releases all that has been published are indexer updates. There has been no changes to the Jackett source code, or install scripts or anything else for that matter.
> 
> The last time I saw something like Net.Sockets.SocketException it turned out to have something to do with proxy setup changes.
> resetting the ServerConfig.json file by editing it and setting the proxy and other related settings to defaults may help to clear the problem.
> 
> ```json
> {
>   "Port": 9117,
>   "AllowExternal": false,
>   "APIKey": "r***redactded***5",
>   "AdminPassword": null,
>   "InstanceId": "i0***redacted***9q",
>   "BlackholeDir": "",
>   "UpdateDisabled": false,
>   "UpdatePrerelease": true,
>   "BasePathOverride": "",
>   "OmdbApiKey": "",
>   "OmdbApiUrl": "",
>   "ProxyUrl": "",
>   "ProxyType": 0,
>   "ProxyPort": null,
>   "ProxyUsername": "",
>   "ProxyPassword": "",
>   "ProxyIsAnonymous": true
> }
> ```
> 
> > but i had to give it a fresh folder/install for it to work again.
> 
> Hmm. if you are now getting authorisation issues then something has gone wrong with your setup of the fresh folder as you put it.
> 
> everything for jackett on windows is usually coming out of C:\ProgramData\Jackett
> what do you mean you gave it a fresh folder?

I renamed v1245 ProgramData/Jackett/ to ProgramData/Jackett.Old/ and reinstalled v1227.
So yeah, it might have been the config that was the problem, i set it up how i wanted it again and we'll see tomorrow after auto-update if it still missbehaves.

**Comment by garfield69** [comment]
@ssurfertuga  extremely unlikely that this ticket and yours are related.
The windows service and updater task share no commonality with the linux versions, and are dependent on completely different control methods. 
And there has been to changes to jackett source code or scripts or whatnot for the last 10 releases.
Only indexers have been updated recently.
