### ISSUE TITLE
[rutracker] fix for movies naming

### ISSUE THREAD

**Issue by underlow** [Jackett/Jackett#6638]
This issue is related to #6111 

rutracker movie naming use following scheme:
`russian name / english name (russian director name / english director name) ... all other stuff` 
now Jackett parses it into `english name (/ english director name) other stuff` and it makes matching movies in sonarr impossible.

example: 
rutracker name: 
`Ирландец / The Irishman (Мартин Скорсезе / Martin Scorsese) [2019, США, криминал, драма, биография, WEB-DL 1080p] Dub (Пифагор) + MVO (Jaskier) + AVO (Юрий Сербин) + Sub Rus, Eng + Original Eng`
parsed into `The Irishman ( /​ Martin Scorsese) [2019, WEB-​DL 1080p] Dub + MVO (Jaskier) + AVO + Sub Rus, Eng + Original Eng`

and it does not match to `The Irishman` in sonarr. 

Disclamer: I'm not .net developer so can someone review PR and point me if something needs to be fixed

**Comment by garfield69** [comment]
Jackett 0.12.1281
