### ISSUE TITLE
Ncore.cc Sonarr dont see the Hungarian categories

### ISSUE THREAD

**Issue by vampywiz17** [Jackett/Jackett#664]
Sonarr find perfectly all of english series/episodes, but not the hungarians. I create new profiles, with hungarian language, but no luck. If i choose the hugarian language in Jackett and do a manual search, i found the hungarian releases, but category say TV/FOREIGN

**Comment by kaso17** [comment]
Please send an invite to kaso1717 -at- gmail.com so I can try to reproduce and fix it.

**Comment by flightlevel** [comment]
Also please confirm what categories you have set in Sonarr

![Image](https://i.snag.gy/OTBz8l.jpg)

**Comment by vampywiz17** [comment]
@flightlevel working thanks! I not check the advenced settings... :) Thanks a lot, please close the issue!
