### ISSUE TITLE
[REQ] https://xwt-classics.net/

### ISSUE THREAD

**Issue by bingoxo** [Jackett/Jackett#6641]
it's the sister site of xtremewrestlingtorrents which is already supported

**Comment by garfield69** [comment]
try out Jackett 0.12.1281

**Comment by ilike2burnthing** [comment]
https://xwt-classics.net/ - redirects to https://xwt.instatus.com/ - down because server is in Russia, new one is being set up

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://xwt-classics.net/ - Connection timed out Error code 522

**Comment by ilike2burnthing** [comment]
back up
