### ISSUE TITLE
[yggcookie] Exception (yggcookie): Invalid URI: The hostname could not be parsed.: Invalid URI: The hostname could not be parsed. (Test)

### ISSUE THREAD

**Issue by maxtop51** [Jackett/Jackett#6644]
Exception (yggcookie): Invalid URI: The hostname could not be parsed.: Invalid URI: The hostname could not be parsed. **And I have this message** Login Failed, got redirected. Try changing the indexer URL to http://www2.yggtorrent.ws/. Updated site link, please try again. **when i try to use www2.**

**Comment by garfield69** [comment]
works for me.
open your yggcookie config on the jackett dashboard.
check that 
1.  the Site Link is set to https://yggtorrent.ws/ and
2. the Search and download URL is set to www2.yggtorrent.ws

from a browser running on the same machine as that is running jackett, login to https://yggtorrent.ws/, access the browser page at https://www2.yggtorrent.ws/new_search/search?do=search
then follow the standard cookie fetch process
- Login to this tracker with your browser
- Open the DevTools panel by pressing F12
- Select the Network tab
- Click on the Doc button
- Refresh the page by pressing F5
- Select the Headers tab
- Find 'cookie:' in the Request Headers section
Copy & paste the whole cookie string to the cookie box in the Jackett yggcookie config.

**Comment by maxtop51** [comment]
Yes is that I dont understand, the cookie is the same

**Comment by garfield69** [comment]
In that case, the problem is most likely not with the cookie but with your account.
login with your browser and check that you have a good ratio, and that you have no outstanding alerts, notices or mail.

**Comment by maxtop51** [comment]
All is okay with my account ratio 4.8 and I have no outstanding alerts, notices or mail.

**Comment by garfield69** [comment]
in that case let see if the enhanced log can provide some more information.

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by garfield69** [comment]
I notice that you are also having trouble with the yggtorrent indexer #6634, so this points to some trouble outside of jackett.

**Comment by maxtop51** [comment]
I try duplicat yggcookie.yml to yggcookie2.yml and the duplicat work

**Comment by garfield69** [comment]
ok then.
so using your Jackett dashboard trashbin your yggcookie and add it afresh. see if that works.

**Comment by maxtop51** [comment]
I try that before so Jackett Remember the setting ... I try to delete directly on the database and now it work for both: YGGTorrent and YGGcookie. The probleme are really on my server. Thanks
