### ISSUE TITLE
[hdtorrents] missing from indexers

### ISSUE THREAD

**Issue by rafuz** [Jackett/Jackett#6647]
HDTorrent Italian is missing from the indexer list. It was ok until a week ago.
Why is it missing? The website is online and working.

**Comment by garfield69** [comment]
so you are saying that  http://hdtorrents.xyz/  returning `404 Not Found nginx` is because they are filtering IP addresses?
No worries, I'll revert it back.

**Comment by garfield69** [comment]
jackett 0.12.1301

**Comment by cipi1965** [comment]
@garfield69 probably yes, it works for me from Italy

**Comment by rafuz** [comment]
It works again, thank you.
