### ISSUE TITLE
Jackett not running - System.BadImageFormatException Could not load file or assembly 'Microsoft.AspNetCore.HostFiltering

### ISSUE THREAD

**Issue by LanternMyWilly** [Jackett/Jackett#6648]
So whenever I install Jackett on my Raspberry pi 4 it works for a few days but then it stops working and I always get a System.BadImageFormatException error in my logs. I've tried disabling auto-update by checking the checkbox on the dashboard but that didn't seem to work. 

Up till now I've always just reinstalled Jackett and started over and over but I'd like a solution so I don't have to reinstall anymore.

I'm running DietPi latest version and right now I'm running Jackett v0.12.1227.0

current error:
` System.BadImageFormatException: Could not load file or assembly 'Microsoft.AspNetCore.HostFiltering, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The module was exp$
File name: 'Microsoft.AspNetCore.HostFiltering, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_2(WebHostBuilderContext hostingContext, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)
`

Thanks in advance

**Comment by garfield69** [comment]
sounds like you are tripping up on the _updater versus service_ issue that cropped up a few month ago.
the solution is to not just replace the binaries, but to also replace the systemd startup script of Jackett.

so after manually installing the latest jackett package (to restore the missing binaries),
- open a terminal,
- cd to where ever you are keeping the jackett binaries,
- and do `sudo ./install_service_systemd.sh`

the install script has been changed to prevent the jackett service from starting while the updater is still running.
afterwards you can enable your updater setting on the Jackett dashboard and be able to get updates without further issue.

given how often you get hit, you should be able to verify this is working after a few days to report back and we can close this ticket.

**Comment by LanternMyWilly** [comment]
I'll give it a go and get back to you in a few days. 
Thanks!

**Comment by LanternMyWilly** [comment]
Jackett hasn't stopped working since my initial issue. I'm hoping it stays this way but for now it seems to be solved.

Thanks!
