### ISSUE TITLE
[passthepopcorn] Please add API user/key support

### ISSUE THREAD

**Issue by eckozen84** [Jackett/Jackett#6649]
Passthepopcorn uses a user generated API User/Key combo. Please implement this.

In the current version of Jackett, it only supports login with passkey and username/password. This is not ideal as it does not work around 2FA, whereas the official API User/Key combo does.

**Comment by cadatoiva** [comment]
I don't have a login to this one, so I can't work on this.

**Comment by takosine** [comment]
I've created a PR adding support for the PTP API login format and verified it works with my own account. https://github.com/Jackett/Jackett/pull/6823

@cadatoiva I'm not sure what the process is for contributing, so please let me know if I should do anything differently.

**Comment by garfield69** [comment]
Jackett 0.12.1470
