### ISSUE TITLE
Jackett 0.12.1301.0 [yggtorrent] Exception (yggtorrent): Login failed: No form found on http://www2.yggtorrent.ws/ using form selector 

### ISSUE THREAD

**Issue by sam37git** [Jackett/Jackett#6653]
Hello, when i add YGGtorrent, i have this:  
An error occured while testing this indexer
Exception (yggtorrent): Login failed: No form found on http://www2.yggtorrent.ws/ using form selector #user-login: Parse error

Or this:

 An error occured while updating this indexer
Login failed: No form found on http://www2.yggtorrent.ws/ using form selector #user-login

Yggtorrent setting:
Site Link: http://www2.yggtorrent.ws/
Search and download URL: www2.yggtorrent.ws
Username: ***********
Password: ••••••••••••••••••••••••
Catégorie: Film/Vidéo

Jackett Version 0.12.1301.0

-------------------------------

**Comment by garfield69** [comment]
take a close look at https://github.com/Jackett/Jackett/issues/6473

**Comment by garfield69** [comment]
and if it still does not work for you then check that your account on yggtorrent is active, has a good ratio, and does not have any outstanding alerts, notices or mail.

**Comment by sam37git** [comment]
Thanks, its work ! Yesterday with this setting, all work...weird
