### ISSUE TITLE
[tapochek.net] Rest API call from Radarr fails while Test works

### ISSUE THREAD

**Issue by Lonli-Lokli** [Jackett/Jackett#6654]
Cannot add tapochek indexer to Radarr due to this exception which happens when Radarr makes API call to Jackett via url
http://192.168.88.69:9117/api/v2.0/indexers/tapochek/results/torznab/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100
<error code="900" description="System.ArgumentNullException: Value cannot be null. (Parameter 'value') at System.Xml.Linq.XAttribute..ctor(XName name, Object value) at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 63 at System.Linq.Enumerable.SelectListIterator`2.MoveNext() at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content) at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content) at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 39 at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 427"/>

**Comment by garfield69** [comment]
Hmm. looks like tapochek is not delivering all the required torznab attributes.
Fails for Sonarr as well.
torznab request to this indexer fail with the unhelpful message `value cannot be null` (why does it not tell me which blinking value, that would be more useful, bah!)

I will investigate.
Should be fairly straight forward to find and the missing selector once I compare the indexer with other ones that work properly.
I'll post an update when I upload the fix.

**Comment by garfield69** [comment]
found it. some tapochek search results on the web site do not have a download link.
fixed the Jackett indexer by excluding results without dl links.

the next release of Jackett will include this fix.

P.S. amend your Radarr tapochek indexer to use only categories 2000,2010,2040,2050,2060,2070,2080
the other default ones 2020,2030,2035,2045 are not supported by the site.

**Comment by garfield69** [comment]
jackett 0.12.1323
