### ISSUE TITLE
[Req] netcosmo.it

### ISSUE THREAD

**Issue by gandalf764** [Jackett/Jackett#6657]
a little help for us Italians who have few trackers! thank you!

**Comment by garfield69** [comment]
try out jackett 0.12.1342

**Comment by gandalf764** [comment]
thanks a lot, it works!
very kind and very fast!

Il giorno sab 21 dic 2019 alle ore 23:04 garfield69 <
notifications@github.com> ha scritto:

**Comment by ilike2burnthing** [comment]
Account has seemingly been deleted, account recovery doesn't recognise my email address, sign up is closed, and my AV flags the site as running a miner (which given the crypto video that pops up on the login page, would make sense).

@gandalf764 are you still able to access your account?

**Comment by gandalf764** [comment]
the site has changed, I no longer have my account and the old one doesn't work anymore. I have long since abandoned netcosm

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
http://netcosmo.it/ returns ERR_CONNECTION_REFUSED
