### ISSUE TITLE
[REQ] argenteam.net

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#6658]
Spanish public film and series tracker.

http://www.argenteam.net/

**Comment by garfield69** [comment]
does this site provide torrent or magnet links?
all I can find are streaming links.
Jackett does not support streaming sites.
can you provide a link to a page on this site that has a torrent or magnet link?

**Comment by 97carmine** [comment]
It mostly provides magnets

http://www.argenteam.net/episode/120257/Vikings.%282013%29.S06E00-The.Saga.of.Floki

**Comment by garfield69** [comment]
it looks like the search results page presents a one-title-one-torrent results table, but 
once you navigate to the details page there are multiple links available, some streaming others from different release groups etc.
this means we cannot use the yaml cardigann processor to support this site.
this site will require the indexer to be written in c#

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
