### ISSUE TITLE
[REQ] cinemamovies.pl

### ISSUE THREAD

**Issue by f0ghqn1ih2** [Jackett/Jackett#6667]
It's Polish tracker for movies and general contents.

Currently open signups: https://cinemamovies.pl/signup.php

**Comment by garfield69** [comment]
jackett 0.12.1354

**Comment by ilike2burnthing** [comment]
https://cinemamovies.pl/ - 502 Bad Gateway

**Comment by ilike2burnthing** [comment]
back up
