### ISSUE TITLE
[REQ] filebase.ws

### ISSUE THREAD

**Issue by f0ghqn1ih2** [Jackett/Jackett#6669]
Semi-public tracker, general content, movies.

Url: http://www.filebase.ws

**Comment by garfield69** [comment]
seems like this is a public site, you can download the torrents without login.
is this correct? any reason to register?

**Comment by f0ghqn1ih2** [comment]
Yea, they allow you to download anything without signups, though as long long time ago it was private one I have account which I keep using.

**Comment by garfield69** [comment]
jackett 0.12.1361

**Comment by garfield69** [comment]
http://www.filebase.ws/ reporting
```html
502 Bad Gateway
nginx
```

**Comment by ilike2burnthing** [comment]
ERR_NAME_NOT_RESOLVED

**Comment by garfield69** [comment]
v0.20.83
