### ISSUE TITLE
When auto-updating "Program Files" becomes "Program%20Files"

### ISSUE THREAD

**Issue by Josephur** [Jackett/Jackett#6671]
Have had this problem for at least the past 4 versions, I have my Jackett set to auto-update and it's installed as a subfolder of my qBittorent folder so "C:\Program Files\qBittorrent\Jackett"

Whenever it updates it doesn't escape the space in the folder name correctly and puts itself in 
"C:\Program%20Files\qBittorrent\Jackett", so I just take the files it's downloaded and paste them over the proper location and all is well.

Should be a pretty simple bug to squish :)

Jackett version:  0.12.1227.0
OS: Windows 10 64-bit

-------------------------------

**Comment by cadatoiva** [comment]
Do you happen to have logs saved from one of these affected updates? There's a couple of places in the code where the folder is grabbed to use for updates, and it'll help me track down the offending section.

**Comment by cadatoiva** [comment]
Never mind, there were only two locations it could have been, and each introduced their own bugs so I fixed them both.

**Comment by Josephur** [comment]
Awesome look forward to the fix in the next build, will report back if the fix didn't solve.

**Comment by garfield69** [comment]
Jackett 0.12.1449
