### ISSUE TITLE
Indexers dissapearing, Tracker.config file shows NULL

### ISSUE THREAD

**Issue by seanvree** [Jackett/Jackett#668]
SO, I've noticed after about a week, 90% of my trackers disappear from the webui. 

I go into the jackett\indexers\ folder and the ones that were previously configured are there, but the file just has a line with "NULL" repeated...

Again, not ALL the indexers do this, but when they do it's all at the same time. 

Nothing in the logs. 

I'm on Windows 10, using Jackett as a service. 

Ideas?

**Comment by kaso17** [comment]
Can you please provide an example file (containing NULL lines).
Making config writes more robust is already on the TODO list.
But the NULLs are a new symptom.

**Comment by seanvree** [comment]
@kaso17 ...Yup.  See file here:

https://drive.google.com/file/d/0B7OujkYtbxFNTmRYc3lNSWQyMXM/view?usp=sharing

They all look like this.

**Comment by seanvree** [comment]
This is still occuring.  

Mostly with these indexers:

Nov 26, 2016 03:22:17 PM	Warn	
Rejected a request to Demonoid which is unconfigured.
Nov 26, 2016 03:22:16 PM	Warn	
Rejected a request to HD-Space which is unconfigured.
Nov 26, 2016 03:22:15 PM	Warn	
Rejected a request to CinemaZ which is unconfigured.
Nov 26, 2016 03:22:14 PM	Warn	
Rejected a request to PrivateHD which is unconfigured.
Nov 26, 2016 03:22:13 PM	Warn	
Rejected a request to TorrentLeech which is unconfigured.


I add them then about 72 hours later, they just drop off...

Current version:  Jackett Version 0.7.639.0

Running on Windows 10

**Comment by kaso17** [comment]
Can you please check/compare the content of the config files at C:\ProgramData\Jackett\Indexers (the .json and the .json.bak files). During Jackett startup you should also get some errors, can you post them please?

**Comment by seanvree** [comment]
@kaso17 I'll have to wait until it errors out again and I'll let you know.

**Comment by seanvree** [comment]
I think this is fixed, I'll reopen if it becomes a problem again.

**Comment by seanvree** [comment]
@kaso17  - I spoke too soon. 

Had a bunch of indexers fall off today. 

Here is one example:
.jason file:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

.bak file:
[
  {
    "id": "username",
    "type": "inputstring",
    "name": "Username",
    "value": "seanvree"
  },
  {
    "id": "password",
    "type": "inputstring",
    "name": "Password",
    "value": "8fkAfgQ6UR6tdYhalsULQrY0XHz6735rZeZe9rPFAWtLOKeLW01FpNwhEikuXfQOSwnUKanMw+s9rNGCzVbGhc47i/P32G/oxT9KnfpW6Sk6i10y9Ixr5LBrULnSLydqtorwfFtbMlBMBweJCtUJ+W5QNutWlfMSJbRzFEs52AMBV62B1JOt8KQBhSpFTgjddfGJV7iV62g3DZoAxI2rlVvdm9PB8uTc6DhtqYQFqZr5r4h8+7VLjDRtjxF2PLXJkAKMOFXnCuEpJKfDMC33lW7JWXMbEOt+zKb7iN76WlJ74PVdaQLHFOU9bQRz0fzo"
  },
  {
    "id": "",
    "type": "displayinfo",
    "name": "",
    "value": null
  },
  {
    "id": "cookieheader",
    "type": "hiddendata",
    "name": "CookieHeader",
    "value": "__cfduid=d4ff63ba6817f745f2df0b1d3cd522d131480219748; XSRF-TOKEN=eyJpdiI6IkJxdWlRUDFCeFRETm5wRTArVSszYXc9PSIsInZhbHVlIjoiUGpHcEV5YStZWFVmaTlzQ1dnN1BEdW9OWmFtR0ZnWXZySzFlYjdXcDZadkJDb25FR3BBRVZZeW5vdTZPV0ZRSjFzQitOWDJNQURZMmNYNExOUDBOSXc9PSIsIm1hYyI6IjdiM2Y4OWRmNGZhOTgzZTg5OTQ3MDBmYmVjNTQzYzI0OGNmYTEzNGRjZTM3MDkyMWQ3ZmIxOTllZWQ3ZTU3MjMifQ%3D%3D; avistazx_session=eyJpdiI6IkkxcmJ1RGNnYStDcEpYd0ZLajViQWc9PSIsInZhbHVlIjoiNFU2Kyt1cmZLbENTU0hsVnZPK2FXUlVWS05uMVwvNHRaY1dIb2x3eUFSMFBiZ2NGR0cwanhxcE1jU2lEc2tNNDY0QjNVRTAyUzZFdUhrS0JSRTRyMjN3PT0iLCJtYWMiOiJjOTJjZTAzYmRkYzA0NjZiOTAxNWI0ZGI3Y2UwZTFiNzYzMzBlOWM2ZTJiZGJlMjg2ZDdhZmY4YTg4YWYwMDRlIn0%3D; remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IkpibEFBSXM2ZmxXMkp5cDd0cDB5Ymc9PSIsInZhbHVlIjoicDhpSllcL2RiNHFha2tLSElWN2RFcXUxSHhqZml1OVhPeWxjYW9OdHZKcXFTOUYxQVF4UTNcL3BrK0hPYUJqbFM3XC9ES09PazI1MGViNGhmWVwvY3RZODNvczdwMERWRWY2dyttRFpVdXgxVzRFPSIsIm1hYyI6Ijk3YmMyZjNlZjBhNWE3MWFiMzQ2YmU0YmMzOWVjZTYyNzQyNGY2ZjFhNGJjOWVhN2IyZTY0ZDk2ZjUzMjU0YTAifQ%3D%3D; love=eyJpdiI6ImJXakRRXC94ZHczUHhxemo2YXFraEN3PT0iLCJ2YWx1ZSI6IlwvdTJITjBRcFQzUnZ0UGhhUEtwcmN3PT0iLCJtYWMiOiJhNGUyMzhmYjAzNGE4YzY2ZWY3OWVhNGQ4NjkwZTA4MjQ5ZjNiZjczMmEzZTRkOTYyNjBmZjRmOWY2OTcxNDQ2In0%3D"
  },
  {
    "id": "lasterror",
    "type": "hiddendata",
    "name": "LastError",
    "value": null
  }
]

**Comment by seanvree** [comment]
@kaso17  - FYI, happened again today. 

Both the .JSON file and the .BAK files show NULL, repeated.  

Following indexers:

Avistaz
Cinemaz
Gormogon
HD-Space
HD4Free
PrivateHD
TorrentBytes
TorrentLeech

**Comment by kaso17** [comment]
Please try v0.7.854
If it still occurs with that version I probably have to start blaming your hard disk causing the data loss ;)

**Comment by armani316** [comment]
@seanvree Is this still an issue?

**Comment by seanvree** [comment]
@armani316  - no, I haven't seen it in a while. I'll close and reopen if it's an issue later.
