### ISSUE TITLE
[freetorrent] Exception (freetorrent): Login failed: No form found on https://freetorrent.tk/login using form selector form: Parse error (Test)

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#6684]
Login fails on this tracker but I can login successfully from my browser

**Comment by garfield69** [comment]
what version of jackett are you on?

**Comment by garfield69** [comment]
freetorrent upgraded 18 days ago to unit3d 2.2.5 which necessitated an support update to the indexer.
if  you are using jackett 0.12.1115 or older then upgrade to a newer version. 
current latest version of jackett is 0.12.1354

**Comment by skuizy** [comment]
Working great with newest version !
