### ISSUE TITLE
[shareisland] Exception (shareisland): Login failed: No form found on https://shareisland.org/login using form selector form: Parse error (Test)

### ISSUE THREAD

**Issue by gandalf764** [Jackett/Jackett#6687]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by garfield69** [comment]
works for me. if you want help with this then 
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by gandalf764** [comment]
thanx at you!
this is my log.txt after enable "enhanced logging" and i have repeat a test
to shareisland:

https://pastebin.com/iGyd32Az

thanx

Il giorno gio 26 dic 2019 alle ore 20:02 garfield69 <
notifications@github.com> ha scritto:

**Comment by garfield69** [comment]
looks like there is a cookie caching issue or something strange.
I  think you should try this:
1. use your jackett dashboard  to delete the active shareisland config by using the trashbin icon (to the right of the shareisland indexer).
2. reboot your computer
3. use your browser to login to shareisland and confirm your account is ok, share ratio good, and that you have no alerts, outstanding notices or unread emails.
4. add the jackett shareisland indexer afresh and provide your current login credentials

see if that sorts the problem out.

**Comment by gandalf764** [comment]
i have insert again my username and my password.. now work...
at this point I believe that the error is mine, for some reason I believe
that the password was wrong even if I didn't change it voluntarily ..
mystery, in any case it works. thanks as always for your timely support

Il giorno ven 27 dic 2019 alle ore 01:04 garfield69 <
notifications@github.com> ha scritto:
