### ISSUE TITLE
[yggcookie] Login failed: Selector "div#top_panel:contains("Déconnexion")" 

### ISSUE THREAD

**Issue by titom1986** [Jackett/Jackett#6688]
Hi guys, it seems that the Déconnexion button is not part of top_panel div anymore, can't configure it anymore

**Comment by garfield69** [comment]
works for me.
your sitelink and/or search url may be out of date.

open your yggcookie config on the jackett dashboard.
check that 
1.  the Site Link is set to `https://yggtorrent.ws/` and
2. the Search and download URL is set to `www2.yggtorrent.ws`

from a browser running on the same machine as that is running jackett, login to https://yggtorrent.ws/, then access the browser page at https://www2.yggtorrent.ws/new_search/search?do=search
 and then follow the standard cookie fetch process
- Login to this tracker with your browser
- Open the _DevTools_ panel by pressing **F12**
- Select the **Network** tab
- Click on the **Doc** button
- Refresh the page by pressing **F5**
- Select the **Headers** tab
- Find 'cookie:' in the **Request Headers** section
- Copy & paste/replace the whole cookie string (everything after the `cookie: `)to the cookie box in the Jackett yggcookie config.

if you get an error the first time, click CLOSE, then try again. Can take two goes to clear the cache.
