### ISSUE TITLE
[req] add tapochek.net/ Private Russian forum

### ISSUE THREAD

**Issue by nightwing847** [Jackett/Jackett#6689]
tapocheck.net 
Russian torrent site 
Invite code needed
Thanks!

**Comment by garfield69** [comment]
tapochek was added to Jackett back in May 2019 #4971 and works for me on the latest jackett.
maybe you need to upgrade?

**Comment by appy01** [comment]
Invite code needed

**Comment by imankit007** [comment]
invite code needed

**Comment by garfield69** [comment]
This is a support site for the Jackett app and not a forum to solicit invites. Please look elsewhere.
