### ISSUE TITLE
jackett blank page after starting successfully

### ISSUE THREAD

**Issue by laundmo** [Jackett/Jackett#6690]
this is not a duplicate of #6244, #5033, #1124

im trying to run jackett usign the linuxserverio/jackett docker image un ubuntu 18.04 LTS.
the jackett version is v0.12.1354.0

the problem is that, even though jackett seems to start fine, im getting no response (blank page 0kb response without response code) when trying to access jackett.
![](https://i.vgy.me/DRABG6.png)
### log:
[log.txt](https://github.com/Jackett/Jackett/files/4003637/log.txt)

### config files:
[ServerConfig.json](https://github.com/Jackett/Jackett/files/4003642/ServerConfig.txt)
[appsettings.json](https://github.com/Jackett/Jackett/files/4003644/appsettings.txt)

am i missing anything? i dont even get a response using curl from within the container, which means that jackett itself is not serving any content.

**Comment by garfield69** [comment]
who set up that appsettings.json content?
is it normal to use 0.0.0.0 as an address?

**Comment by garfield69** [comment]
I would delete that appsetting.json file
its making jackett listen on 0.0.0.0 but clearly you are expecting to use 127.0.0.1 as shown by your curl attempt.
127.0.0.1 or localhost is the usual setup.

**Comment by laundmo** [comment]
0.0.0.0 is a [catch-all ip for any ipv4 address](https://en.wikipedia.org/wiki/0.0.0.0)
the problem was that prior to the appsetting.json jackett was hosting on [::]:9117 which is the same catch all for any ipv6 address.

i have tried using 127.0.0.1 in there to no avail

**Comment by garfield69** [comment]
then perhaps pick one of the two addresses, and see if setting the appsetting url to 192.168.1.1 helps. #6278

**Comment by laundmo** [comment]
one of which two addresses?

using the address 192.168.1.1 leaves me with the error `Fatal Unable to start Kestrel. System.Net.Sockets.SocketException (99): Cannot assign requested address` in the logs

**Comment by garfield69** [comment]
well I am sorry, but this topic is pretty much outside my experience.

we don't support the docker images, they are built by https://hub.docker.com/r/linuxserver/jackett/  by taking what we publish and they do whatever they do to create these docker images.
perhaps you might get better support directing your enquiry at https://discourse.linuxserver.io/ or https://discord.gg/YWrKVTn

**Comment by junglebus** [comment]
docker or docker-compose commands used to create/run container?

**Comment by laundmo** [comment]
it seems this was entirely my fault. after being used to being able to test if a pages works using curl, i did not consider the possibility that `curl` would not show any page content for jackett.

i had a faulty reverse proxy config, and tried testing using curl, which as i now know, doesnt work.
this lead me to believe that jackett was not serving any content, even though it was curl which didnt show any content for some reason.

after configuring my reverse proxy correctly, i was able to access the page using my domain, though curl is still broken.
