### ISSUE TITLE
Search doesn't work 100% for Torrentday and IPTorrents

### ISSUE THREAD

**Issue by adajan** [Jackett/Jackett#67]
Hello,

Could anyone assist me with this. My issue seems to be the search function not working 100%.
What happens is when I add a show that with episodes that aired 2 - 3 months age(age differs a lot between what is getting returned, so don't quote me directly on this), some of them are returned but mostly the majority don't get snatched. The search is being done by Sonarr through Jackett. With Jackett being connected to iptorrents and torrentday.

For instance:
Sonarr searches for monitored episodes such as below. The episode quality is set to 1080p, HDTV, web-dl or bluray:
https://gyazo.com/6fe14b597f7056dcfc9e837074b045b1

It comes back saying, that none of the searches were successful.

But on the private tracker website, every episode is there in the quality it needs to be in.
https://gyazo.com/2273c4f928fb56d4316cea078ab5106f
https://gyazo.com/298c464aa8ad33d3bfd1609297abac2e

Doing a manual search on Jackett, returns everything there is:
https://gyazo.com/13969637941fbe0c725f766221dde499

Logs from Jackett on the search:
https://gyazo.com/2bde1657acf7a5ffa7daea4c31ca58b6

Logs from Sonarr on the search:
https://gyazo.com/76de679f7fc7636c72a5595c5f62c0b7

Proof that nothing got snatched from deluge:
https://gyazo.com/50b8603b93a79b0b7e8fd6d40446fd51

What seems to be working is on the day snatching, I think this means the RSS is working fine.

**Comment by flightlevel** [comment]
@adajan 
If you click on the person (circle in red) do you see a list of available torrents?
http://www.sumopaint.com/images/temp/xzmrjorelprendpf.png
If you click to download the torrent, does it work?

**Comment by adajan** [comment]
@flightlevel 
Clicking the person returns nothing. See below 
https://gyazo.com/59bc0cb1dfd4f698879f0a72745e0fa5

Do you mean download the torrent in Jackett?
If so, yes:
https://gyazo.com/5ee8e456825df19625f12848acd322fe

**Comment by flightlevel** [comment]
Is it all TV shows or just Mr Robot?

**Comment by adajan** [comment]
@flightlevel 

All the shows I've done so far.

Sorry if my edit to my previous post was late. Please take a look at it.

**Comment by flightlevel** [comment]
Jackett is definitely working properly. eg. https://gyazo.com/13969637941fbe0c725f766221dde499
Can't understand why Sonarr is searching by airdate for a tv series with episode numbers?
Not in front of my Sonarr right now, have a look if there is an airbydate setting that you've accidentally flicked on. Otherwise ask on the Sonarr forum how to stop searching by air date.

**Comment by adajan** [comment]
Nothing that I can see currently.

Indexers:
https://gyazo.com/58118890e60e5f6f90367d556aba7dfc 
I tested the restrictions, it didn't affect the search results.

Profiles:
https://gyazo.com/5b645437c3201d04a50a15bc258d4943

Media Management:
https://gyazo.com/752fe0cde252b9b6bf8f380c47b275f3
https://gyazo.com/10451aec507cc4f316278aa68456ae0d

Quality:
https://gyazo.com/6dfa0c52cc80817f5b1bfdf152dde637


Edit:

I found the error. 

In Sonarr when you add a season, you choose how it should be found. Options are daily, standard or anime. I think daily only references RSS. And standard uses the search. Switched to standard, and everything is working.

Anyway, this was completely stupid haha. Thank you for the help and assistance @flightlevel
