### ISSUE TITLE
[REQ] NORDiCHD

### ISSUE THREAD

**Issue by f0ghqn1ih2** [Jackett/Jackett#6708]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: NORDiCHD
- URL: https://nordichd.org/
- Description: NORDiCHD is a Mixed NORDIC Private Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): MR 1.0
- Additional Comments:
Signup currently open
Engine: TSUE 2.2
```

**Comment by garfield69** [comment]
jackett 0.12.1378

**Comment by garfield69** [comment]
http://www.nordichd.eu/ returning ERR_NAME_RESOLUTION_FAILED
just moe, or has the site gone, is broken or moved to a new domain?

**Comment by f0ghqn1ih2** [comment]
Im not sure whats going on with this tracker but its occasionally is down :(

**Comment by f0ghqn1ih2** [comment]
Yea... Seems like its dead fully and I can't find any alternative domains :/

CC: @garfield69

**Comment by garfield69** [comment]
seems to be back online.

**Comment by garfield69** [comment]
http://www.nordichd.eu/ returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
interesting.
you previously requested an indexer for http://www.scenexpress.org/ which I created a while ago.
but recently this domain has been returning  ERR_NAME_RESOLUTION_FAILED
@dimqua  found a domain that appears to be related to scenexpress,  http://scenexpress.zapto.org/ but the site's web engine is different and it would not accept my old scenexpress credentials.
So I registered with new credentials a few days ago.

Today http://www.nordichd.eu/ presented me with a login panel which I recognised as belonging to this alternate SceneXpress at http://scenexpress.zapto.org/  and my new credentials were accepted.

so it looks like http://www.nordichd.eu/ is now an alternate for http://scenexpress.zapto.org/

**Comment by dimqua** [comment]
4 years ago: https://www.reddit.com/r/trackers/comments/3144kd/scenexpress_sex_is_now_nordichd/

**Comment by RoloSoze** [comment]
@garfield69 Wax this indexer deleted? It's back now http://www.nordichd.eu/

**Comment by garfield69** [comment]
Jackett 0.16.127

**Comment by garfield69** [comment]
OK what is going on with this site now?
it has a new engine, used to be TSUE2.2 now its U232v3
my previous account credentials are not on this new site, I have registered again.

It looks to me like someone has take over the domain AGAIN
is there a war going on between operators or something?

I'm going to have to rewrite the indexer.

**Comment by garfield69** [comment]
http://www.nordichd.eu/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
Back up (login page at least)

**Comment by garfield69** [comment]
http://www.nordichd.eu/ returning ERR_NAME_NOT_RESOLVED

**Comment by garfield69** [comment]
https://nordichd.org/ redirects to https://cinefilhd.sytes.net/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
well it looks like nordichd is going through is messy takeovers like it did back in Feb-Mar 2020
https://nordichd.org/ redirects to https://cinefilhd.sytes.net/ which presents a cinifilhd login page
my nordichd creds don't work, nor do my old cinefilhd creds from back on 2019 when that site was last active.
and registration is currently closed, invite only.
@f0ghqn1ih2  any clue what is going on?

**Comment by garfield69** [comment]
ok, cinefilhd now has open signup, so I'm going to remove nordichd and restore the cinefilhd indexer #4908

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://nordichd.org/ ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/6708#issuecomment-1577798233

**Comment by garfield69** [comment]
associated with #4908

**Comment by ilike2burnthing** [comment]
Back up, and I think we can close this as it's the one that's supposed to survive.

**Comment by garfield69** [comment]
https://nordichd.org/ redirecting to http://cinefilhd.xyz/

**Comment by ilike2burnthing** [comment]
Working ok for me, signed in or not.

**Comment by garfield69** [comment]
Bugger. Must be a cloudflare DNS thing then.

**Comment by garfield69** [comment]
%-/
I switched to google DNS but I'm still getting the redirect. Bah.

**Comment by ilike2burnthing** [comment]
Weird. I checked Uptrends, it was only failing for Rome (and that was a timeout, not redirect), but who knows, maybe it's having issue elsewhere and the checkpoints just aren't covering your local area.

Try a VPN server or two?

**Comment by garfield69** [comment]
its going to have to wait, I cant switch networks ATM, I've got active traffic to maintain. I'll try tomorrow.

**Comment by ilike2burnthing** [comment]
Ha! Aaaaaand now it's redirecting for me 🙄

**Comment by garfield69** [comment]
Oh good, so I am not incompetent ;-b

**Comment by ilike2burnthing** [comment]
Back up for you too?

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
here we go again
https://github.com/Jackett/Jackett/issues/6708#issuecomment-1636655755

**Comment by garfield69** [comment]
http://nordichd.org/ ERR_CONNECTION_TIMED_OUT
all uptime checkpoints report TCP Connection Failed

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://nordichd.org/ MySQLi connection error!

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://nordichd.org/ ERR_CONNECTION_TIMED_OUT 
uptime 9 of 43 online the others offline

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://nordichd.org/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://nordichd.org/ redirects to https://nordichd.org/lander which on chrome browser shows a blank page but is probably a domain expired parking page

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://nordichd.org/ Suspended Domain

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://nordichd.org/ 403 Forbidden Access to this resource on the server is denied!

**Comment by garfield69** [comment]
v0.22.809
