### ISSUE TITLE
[REQ] pornbits.org

### ISSUE THREAD

**Issue by f0ghqn1ih2** [Jackett/Jackett#6710]
Pornbits (PB.NET) is a Private Torrent Tracker for XXX

Registration link: https://pornbits.org/register

**Comment by garfield69** [comment]
jackett 0.12.1384

**Comment by f0ghqn1ih2** [comment]
https://github.com/Jackett/Jackett/issues/6920

**Comment by garfield69** [comment]
https://pornbits.net/ returns ERR_CONNECTION_REFUSED
