### ISSUE TITLE
m-team cookie for 2fa

### ISSUE THREAD

**Issue by bingoxo** [Jackett/Jackett#6741]
m-team is one of the trackers that reward for 2fa and since it doesn't seem different from other chinese trackers that work with cookies , if there is not a current solutio to support 2fa in jackett now can you make m-team login with cookies ?

**Comment by garfield69** [comment]
I will not replace the mteamtp indexer's regular login, because users may still want the choice of using 2fa or not.
So I will create mteamtp2fa which will be a clone but with the cookie login in place.

**Comment by garfield69** [comment]
Jackett 0.12.1391

**Comment by bingoxo** [comment]
Is this working for anyone ? because it's not working for me

An error occured while updating this indexer
Login Failed, got redirected
