### ISSUE TITLE
[extratorrent-cd] public tracker

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6742]
The search feature in the website https://extratorrent.ag/ is not working for months.

UPDATE: I sent an email to the owner. Wait few days to see if they respond.

**Comment by ngosang** [comment]
Well, they don't answer.

**Comment by ngosang** [comment]
@garfield69 I have found this site => https://extratorrent.si
I don't know if it's legit, but the site has activity and the search engine works.

**Comment by garfield69** [comment]
ever since extratorrent.cc closed down in 2017 there has been a slew of copycat sites, so technically there are no legit sites. 
the .si is actually the new domain for .cd which is just as popular as the .ag site, but is run by different operators. 
at least these are not fakes in so far as they don't ask you to register or are fishing scammers.
So I will remove the .ag indexer and add a new indexer for .cd, because the html in use is different behind the scenes despite a similar looking presentation.

**Comment by garfield69** [comment]
https://extratorrent.si/ currently returning 500 Internal Server Error

**Comment by garfield69** [comment]
https://extratorrent.si/search/?search=Vikings+S05E05 returning no results despite homepage showing
![image](https://user-images.githubusercontent.com/6933240/85099355-4cdf0200-b251-11ea-9f11-801a01b50087.png)
probably same crappy issue that etag had. would not surprise me if it's the same site with a different domain.

**Comment by ilike2burnthing** [comment]
.si is an ET skinned TPB proxy, see #8186

Though to get the same results as TPB, a `.` has to be placed between search terms (basically their `andmatch`) - https://extratorrent.si/search/?search=Vikings.S05E05

It still finds results without `.` in their title, e.g. https://extratorrent.si/search/?search=vikings.s05 finds `Vikings S05 720p NF...`

**Comment by garfield69** [comment]
https://extratorrent.si/ returning Error 502 Bad gateway

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://extratorrent.si/ - Error 520 - Web server is returning an unknown error

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://extratorrent.si/ - Error 520 - Web server is returning an unknown error

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://extratorrent.si/ - Error 520 - Web server is returning an unknown error

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://extratorrent.si/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://extratorrent.si/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://extratorrent.si/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://extratorrent.si/ - Error 520 - Web server is returning an unknown error

Intermittent problem. Test several times over a few minutes to confirm stability.

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://extratorrent.si/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://extratorrent.si/ - Error 502 - Bad gateway (intermittent)

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://extratorrent.si/ - Error 521 - Web server is down

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://extratorrent.si/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
https://extratorrent.si/ - 404

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://extratorrent.si/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://extratorrent.si/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://extratorrent.si/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://extratorrent.si/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://extratorrent.si/ returning Error 522 Connection timed out

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://extratorrent.si/ returning Error Web server is returning an unknown error

**Comment by ilike2burnthing** [comment]
Now `500 Internal Server Error`

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://extratorrent.si/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
Now redirects to accessworkspace.co

**Comment by garfield69** [comment]
v0.19.147
