### ISSUE TITLE
[FunkyTorrents] add exact match

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6743]
tested with the search: green

**Comment by garfield69** [comment]
I do not have an a/c on this site.
are you saying that searching for **green**  returns titles that do not contain green in them?

**Comment by ngosang** [comment]
Registration is open today => http://funkytorrents.com/inviteme.php

And yes.
![image](https://user-images.githubusercontent.com/10577978/71564624-31661c00-2aa4-11ea-83d0-d89031a342bd.png)

**Comment by garfield69** [comment]
the web site does not appear to have any additional search options to restrict search to words only, as opposed to partials.
the cardigann row filter _andmatch_ will not help in this case.
unless yo can find on the web site additional options (quotes, plus, minus, something else), I'm not sure we can achieve your request.

**Comment by ngosang** [comment]
There is not advanced search.
