### ISSUE TITLE
Mono Jackett

### ISSUE THREAD

**Issue by painless1088** [Jackett/Jackett#6746]
Ive looked everywhere not really an linux expert or anything but ad okay with it. I am having trouble finding a way to remove Jackett Mono version off one of my Servers can some one please help me i havent found details on doing this anywhere.
-------------------------------

**Comment by garfield69** [comment]
there is no un-install tool if that is what you are looking for.
I don't use Linux much myself, but this should give you an idea. hopefully if you run into problems some Linux volunteer can steer you right.

if you installed Jackett as a service, then open a terminal and 

#### removing the systemd startup script 
1. `systemctl stop jackett.service`
2. `cd /etc/systemd/system`
3. `rm jackett.service`
#### removing the binaries 
4. `cd /opt` or `cd ~/` on some systems
5. `rm -r Jackett`
#### removing configs, logs, indexers etc.
6. `cd ~/.config`
7. `rm -r Jackett`

if you installed Jackett as a run-on-demand program, then skip steps 1,2,3

you may need to prefix the commands with `sudo ` if you get complaints about authority.

But as always, given the myriad flavours of Linux out there, you may need to customise commands and folder locations to suit your platform.

**Comment by painless1088** [comment]
Will This remove all Jacket Services or Just Mono version of Jackett

**Comment by garfield69** [comment]
Huh?
there should be only one jackett service running on your server if all you have installed is the mono-jackett.

I got the impression that you just wanted to remove jackett from your server.
is the scenario here that you want to upgrade from the mono-jackett to the .net core version?

**Comment by painless1088** [comment]
No i have 2 jacketts i went and installed the newer jackett but forgot to remove the mono jackett now they are both running different versions on 2 different ports

**Comment by garfield69** [comment]
urg.
In that case **do not** follow my first post as that assumes there is only one jackett on the system and that you just wanted to stop using jackett.

you need to identify the systemd script, binary folder and config folder for each flavour of jackett.

so from a terminal `cd /etc/systemd/system` 
and see how many scripts have jackett in the name `ls *jack*`
then take a look at the scripts with `gedit jackett.service` or what ever the scripts is called.
the **WorkingDirectory** should tell you where the binaries are
and if the **ExecStart** has **mono** in the path then this is the script you want to delete and the binaries folder you want to remove.

**Comment by ngosang** [comment]
Follow the steps above. Reboot the server and run:
`ps aux | grep jackett`
That will list all process called jackett. We can't help you much more...
