### ISSUE TITLE
[bit-titan] No results after Tracker search update

### ISSUE THREAD

**Issue by solidsniper** [Jackett/Jackett#6748]
Tracker updated search. Now jackett finds no results.

relevant log: CardigannIndexer (bit-titan): Error while parsing row

**Comment by garfield69** [comment]
bit-titan are trying out a new search engine, and the search and results html has changed.
```
Unsere neue "Durchsuchen (Beta Version)" Seite ist da mit vielen neuen Funktionen.
Viel Spaß beim testen und teilt uns eure Kritik / Verbesserungen / Bugs mit.

Our new "Browse (Beta Version)" page is there with many new functions.
Have fun testing and tell us your criticism / improvements / bugs.
```

I will need to rewrite the indexer to support the site changes.

**Comment by garfield69** [comment]
Jackett 0.12.1391
