### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on http://www2.yggtorrent.pe/ using form selector 

### ISSUE THREAD

**Issue by nonopubli** [Jackett/Jackett#6749]
Hi all,

I am using Jackett Version 0.12.1146.0 on a Raspberry Pi 2 with OSMC + Radarr + Sonarr.
This config is perfect... until Jackett stop working with YggTorrent(.pe/.ws).
Any idea? Thanks

_EDIT: I tried with [yggcookie] and it seems to work fine!_

**Comment by garfield69** [comment]
read carefully and follow  https://github.com/Jackett/Jackett/issues/6473#issuecomment-560978023
