### ISSUE TITLE
animetorrents.me broken?

### ISSUE THREAD

**Issue by psyoptix** [Jackett/Jackett#675]
For some reason I'm not able to add AnimeTorrents

Account information is definitely correct (e.g. can login using their webpage) but Jackett is giving me the error: "Configuration failed: Found no results while trying to browse this tracker"

**Comment by Githubtordl** [comment]
Update your Jackett installation to v0.7.570. It should solve that issue

**Comment by psyoptix** [comment]
Thanks for responding.

I actually just installed Jackett a few minutes ago. It seems the newest windows release is still v0.7.555.

Besides compiling using the code in git is there any other way for me to upgrade to v0.7.570?

**Comment by kaso17** [comment]
v0.7.570 was a pre release, you have to check update to pre releases in Jackett to get it or install it manually.
I just changed it to a normal release so you can update normally.

**Comment by psyoptix** [comment]
Wow! I really appreciate your help and responsiveness. :-) thanks a lot. I'll install the new version now.

**Comment by psyoptix** [comment]
Everything works. thanks again.
