### ISSUE TITLE
IPtorrents cant add 

### ISSUE THREAD

**Issue by Linwelin** [Jackett/Jackett#676]
Error: An error occurred while sending the request.

Nov 11, 2016 03:03:17 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
Nov 11, 2016 03:03:17 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Nov 11, 2016 03:03:17 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Nov 11, 2016 03:03:17 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Nov 11, 2016 03:03:17 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Nov 11, 2016 03:03:17 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Nov 11, 2016 03:03:17 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Nov 11, 2016 03:03:17 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Nov 11, 2016 03:03:17 PM	Info	
ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Nov 11, 2016 03:03:17 PM	Info	
ApiControllerActionSelector SelectAction 
Nov 11, 2016 03:03:17 PM	Info	
AdminController ExecuteAsync 
Nov 11, 2016 03:03:17 PM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Nov 11, 2016 03:03:17 PM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Nov 11, 2016 03:03:17 PM	Info	
DefaultHttpControllerActivator Create 
Nov 11, 2016 03:03:17 PM	Info	
HttpControllerDescriptor CreateController 
Nov 11, 2016 03:03:17 PM	Info	
DefaultHttpControllerSelector SelectController Admin
Nov 11, 2016 03:03:17 PM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Nov 11, 2016 03:03:17 PM	Info	
  http://127.0.0.1:9117/Admin/GetLogs?_=1478876591855
Nov 11, 2016 03:03:14 PM	Info	
AdminController Dispose 
Nov 11, 2016 03:03:14 PM	Info	
AdminController Dispose 
Nov 11, 2016 03:03:14 PM	Info	
  Content-type='application/json; charset=utf-8', content-length=73
Nov 11, 2016 03:03:14 PM	Info	
AdminController ExecuteAsync 
Nov 11, 2016 03:03:14 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync 
Nov 11, 2016 03:03:14 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'GetConfigForm()'
Nov 11, 2016 03:03:14 PM	Info	
ApiControllerActionInvoker InvokeActionAsync 
Nov 11, 2016 03:03:14 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
Nov 11, 2016 03:03:14 PM	Error	
Exception in GetConfigForm

**Comment by kaso17** [comment]
Which version are you running?

**Comment by Linwelin** [comment]
Jackett Version 0.7.570.0
windows 10

**Comment by archangel00uk** [comment]
Same situation as Linwelin. 

Iptorrents.eu doesn't seem to be available in the torrent list, test appears to be failing in Jackett and Sonarr too.

**Comment by kaso17** [comment]
Added iptorrents.eu via #678.
You should be able to use it anyway.
Please post logs with the -t option enabled.

**Comment by kaso17** [comment]
Should be fixed with v0.7.577.
