### ISSUE TITLE
[torrentbd] Login failed: Selector

### ISSUE THREAD

**Issue by protik77** [Jackett/Jackett#6761]
Torrentbd recently updated their site and Jackett broke as a result. Please see here for the [enhanced log](https://pastebin.com/eSV0Jiev).

I'm using jackett in a docker.

**Jackett version**:  0.12.1391.0

**Comment by garfield69** [comment]
I do not have an a/c on torrentbd so I cannot work on this.
registration is open only to invites currently.
send an invite to garfieldsixtynine @ gmail.com

**Comment by protik77** [comment]
Done!

**Comment by garfield69** [comment]
no email as yet. check my spam and bin too. did you use `garfieldsixtynine@gmail.com`?

**Comment by protik77** [comment]
Yes, let me talk to support and see if I can resend that again.

**Comment by protik77** [comment]
Please check again and let me know.

**Comment by garfield69** [comment]
nothing so far.
perhaps gmail is blocked someplace or they are having trouble with their website's invite email module?
an alternate address should it be useful is `garfield69@outlook.com`

**Comment by garfield69** [comment]
I've just received an invite via the outlook mail.
registration and login successful.
Thanks.
I'll start work on the indexer shortly.

**Comment by garfield69** [comment]
jackett 0.12.1402
