### ISSUE TITLE
[pleasuredome] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by Fireforce001** [Jackett/Jackett#6768]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by Fireforce001** [comment]
How do I create/ fix a tracker in Jackett?

**Comment by garfield69** [comment]
that is a very general question. 
1. are you talking about you implement a temporary fix for pleasuredome yourself locally so you can test a fix, 
2. or are you taking about submitting a fix on github so others can benefit from your fixed pleasuredome indexer in the next release of Jackett, 
3. or are you talking about how you can raise a ticket so that others can fix pleasuredome and include it in the next release of Jackett ?

**Comment by garfield69** [comment]
BTW there is nothing wrong with pleasuredome, it works for me.
if you want help figuring out why you cannot access the site with the indexer, then
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.
