### ISSUE TITLE
Jackett crash after a while on MacOS

### ISSUE THREAD

**Issue by nicolasbisi** [Jackett/Jackett#6769]
Hi there,
I'm running Jackett Version 0.12.1391.0 with Mono Version 6.4.0.198 on MacOs 10.12.6
I'm not running Jackett as a service, and I'm always running on the terminal with ./jackett -t -l

Jackett runs fine for a while. I can do searches with it on Sonarr/Radarr and I get responses. The problem is that after some time it crashes. I haven't figured out a way to force it to crash yet, but it doesn't take more than half an hour.

It crashes with the fallowing message:

```
01-03 00:15:31 Info Request finished in 16.281000000000002ms 200  
01-03 00:15:31 Info Jackett variant: CoreMacOs 
01-03 00:15:31 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://api.github.com/repos/Jackett/Jackett/releases) 
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /Users/user/Downloads/Jackett/System.Native.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /Users/user/Downloads/Jackett/System.Native.dylib
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

**Comment by garfield69** [comment]
looks like Jackett is about to do a check for updates and something breaks.
as a temporary circumvention (and to test i am on the right path), start jackett with 
`./jackett -t -l --NoUpdates`

**Comment by nicolasbisi** [comment]
@garfield69 Yep seems that the update is the problem. I have been running with --NoUpdates and it has not crashed yet.

**Comment by junglebus** [comment]
Any chance you can update macOS to 10.13 or greater to see if it goes way? I should have updated the read me when updating to .NET Core 3
https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md

**Comment by nicolasbisi** [comment]
@junglebus Sorry, no. The system is running a lot of other things and I can't afford anything to break right now.

**Comment by junglebus** [comment]
I’d close this as it’s not an issue with Jackett, user just doesn’t meet the minimum requirements. Others have received this exact same [error](https://github.com/dotnet/core/issues/3148)

Options for user:
- update macOS
- run an old version of Jackett before .NET Core 3
- hope that using noupdates avoids problem
- go back to using the Mono version of Jackett

**Comment by nicolasbisi** [comment]
It's fine with me. I'm happy to run it with --NoUpdates
Thanks for the help.
