### ISSUE TITLE
BaconBits - Have to "resave" settings for it to be searchable

### ISSUE THREAD

**Issue by dhighet** [Jackett/Jackett#677]
Occasionally BB will not be searchable and will fail a test. To fix this I need to open its config, save and it will work again. This will happen infrequently every few days or so.

Running on Windows Server 2012 R2.
Jackett Version 0.7.555.0

**Comment by kaso17** [comment]
Any chance that it's related to IP changes?

**Comment by dhighet** [comment]
No idea. On their end, maybe? My WAN IP hasn't changed lately nor my internals.


Get Outlook for Android






On Sun, Nov 13, 2016 at 1:26 AM -0800, "kaso17" <notifications@github.com> wrote:












Any chance that it's related to IP changes?

**Comment by kaso17** [comment]
Please send an invite to kaso1717 -at- gmail.com and I'll add a check for relogin.

**Comment by dhighet** [comment]
Sent!

**Comment by kaso17** [comment]
@dhighet Thank you but I didn't receive anything (I already checked spam).

**Comment by kaso17** [comment]
got it, thank you.
