### ISSUE TITLE
[digitalcore] Invalid Captcha (Config)

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#6770]
This tracker seems to require captcha at login. Jackett can't login on it

**Comment by Jonathan34** [comment]
I have the same issue, they must have added captcha recently without any option to disable.

**Comment by ERR1R** [comment]
https://github.com/Jackett/Jackett/pull/6779

**Comment by Amras-anon** [comment]
Any update?

**Comment by Jonathan34** [comment]
@Amras-anon The ticket was opened less than a day ago. Be patient. @ERR1R provided a fix (thanks!) Needs review and merge.

**Comment by garfield69** [comment]
jackett 0.12.1415
