### ISSUE TITLE
[REQ] snowfl.com

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#6771]
Snowfl is a torrent search engine that searches across multiple public indexes.

https://snowfl.com/

**Comment by garfield69** [comment]
this site generates its results via javascript after the html has been loaded.
as such it is not compatible for processing by Cardigann with an indexer written in yaml 
this indexer will need to be written in C#

**Comment by NightMachinary** [comment]
@garfield69 How does it return json?

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/79288163-2384bb80-7f1a-11ea-97d6-1c362963182a.png)

**Comment by Sloth-on-meth** [comment]
What's the status on this?

**Comment by garfield69** [comment]
>What's the status on this?

pending a volunteer to write a C# indexer for the site.

**Comment by ngosang** [comment]
@ilike2burnthing @garfield69 I think this can be implemented with Cardigann JSON.

**Comment by ilike2burnthing** [comment]
Request URL for the search for `2022` sorted by date is: https://snowfl.com/KUcebQperQmtMSikfDJXvfHBKmrdXygtUAO/2022/0N0r0hai/0/DATE/NONE/1?_=1659291586124

I have zero idea how or even if we can generate that.

**Comment by ngosang** [comment]
You can see the year in the middle of the URL. That is the only thing you need to change. :smile:

**Comment by ilike2burnthing** [comment]
If only. If you try that same link now you just get `Error`.

The request URL for the same search now is:
https://snowfl.com/elNaUVuBWyYBeIqtXSciWDXrLePMyuKvGnHIN/2022/msdaD9x9/0/DATE/NONE/1?_=1659302057713

So seemingly there are two tokens being generated, and I can't see how. The last number appears to just be a running total of the number of searches, and isn't actually needed.

**Comment by ngosang** [comment]
I looked at the source code.

https://snowfl.com/elNaUVuBWyYBeIqtXSciWDXrLePMyuKvGnHIN/dddd/1fjFq1f7/0/SEED/NONE/1
* elNaUVuBWyYBeIqtXSciWDXrLePMyuKvGnHIN => it looks random but it's fixed. it's hardcoded in the source code
* dddd => my search keyword
* 1fjFq1f7 => is random and it does not depend on the other search params. must be alpha-numeric with 8 characters
* 0 => page number, 0, 1, 2...
* SEED => sort by
* NONE => "top" combo. if you change this option you will see the URL is a bit different. the keyword is disabled
* 1 => nsfw. I don't know what it is. it's only visible on mobile.

![image](https://user-images.githubusercontent.com/10577978/182049085-46971c7e-4fc1-40cf-a913-e0c201034f48.png)

I think it's doable and you have all the information.
If you are curious about the source code I let you 2 fragments:
```js
var oHkfQuTWziJ = 'elNaUVuBWyYBeIqtXSciWDXrLePMyuKvGnHIN';

Sutil = {
  randomString: function () {
    for (var r = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOP1234567890', t = '', e = 0; e < 8; e++) {
      var a = Math.floor(Math.random() * r.length);
      t += r.charAt(a)
    }
    return t
  }
};
```

**Comment by ilike2burnthing** [comment]
While `elNaUVuBWyYBeIqtXSciWDXrLePMyuKvGnHIN` is currently working, previously it was `KUcebQperQmtMSikfDJXvfHBKmrdXygtUAO`, and that no longer works. Presumably then it's a timed token.

If it can be pulled from the source, great, but that will require C#.

`1fjFq1f7` can also be `Jackett1`and still work, so that's not an issue.

**Comment by ngosang** [comment]
You are right. We need C#

**Comment by garfield69** [comment]
closing as not suitable and stale.
