### ISSUE TITLE
[REQ] ibit.to

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#6772]
Public tracker of movies, TV, music, games, software, anime, games and others

https://ibit.to/
https://ibit.uno/
https://ibit.am/
https://ibit.ws/

**Comment by garfield69** [comment]
bugger. this site's torrent details page does not have an actual href with the magnet URI, which means I cannot use the Cardigann's yaml processor to code an indexer for the site.
The magnet appears to be buried in a script, and the magnet needs to be extracted and constructed back into a proper magnet href before it can be used.
```html
    <script>
        $(function () {
            $('.tabs-wrapper h2').hide()
            $('.tabs').tabs()

            
    $('#expand-cast').click(function () {
    $('ul.cast .hide').removeClass('hide')
    $(this).hide()
    })
    $('#expand-trailer').click(function () {
    $('#trailer').css('max-width', '100%')
    $('#trailer').css('min-height', '600px')
    $(this).hide()
    })


            loadScript('//cdnjs.cloudflare.com/ajax/libs/lazysizes/4.1.5/lazysizes.min.js', 0)
            loadScript('//cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js', 1000)
            play('0EF5E7918CX-X540B05B8F2X-X99AE252EA6X-X6C24436CE7', 
            0EF5E7918C540B05B8F299AE252EA66C24436CE7'magnet:?xt=urn:btih:0EF5E7918CX-X540B05B8F2X-X99AE252EA6X-X6C24436CE7\x26dn=%5Bibit.to%5DThe\x2bReal\x2bHousewives\x2bof\x2bOrange\x2bCounty\x2bS14E14\x2bBest\x2bFrenemies\x2bForever\x2b720p\x2bHDTV\x2bx264-CRiMSON\x2bEZTV\x26tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A80\x26tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce\x26tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969\x26tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce\x26tr=udp%3A%2F%2Fexodus.desync.com%3A6969')
        })
    </script>
                            <a href="#" class="waves-effect waves-light btn-floating tooltipped btn-green" id="magnet-link" title="Magnet link download">
                                <i class="fa fa-magnet"></i>
                            </a>
```

this indexer will need to be written in C#

**Comment by ngosang** [comment]
@garfield69 the magnet link is in plain text. It's not possible to grab the `script` tag and then use a regex to find `magnet:[^']+` ?

**Comment by garfield69** [comment]
I believe that the current Cardigann download block (used for processing the details page download link) is hard-coded for a href.
from the wiki https://github.com/Jackett/Jackett/wiki/Definition-format#download
```yaml
    selector: a[href^="download.php?id="] # If an selector is specified the search result
                                          # download URL will be retrieved and parsed as
                                          # HTML.
                                          # The selector is then applied to get the
                                          # actual download URL.
                                          # It must be an a element with href attribute.
```

**Comment by ngosang** [comment]
Yes, it's hardcoded to href. https://github.com/Jackett/Jackett/blob/424370a1c3434a0bdce19900e66e2912658c7443/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1743

Do you think it will be useful to allow select the attribute like in the search? I think this will be easy to do.
```
      category:
        selector:  td[class^="coll-1"] a[href^="/sub/"]
        attribute: href
        filters:
          - name: split
            args: ["/", 2]
```

**Comment by garfield69** [comment]
>Do you think it will be useful to allow select the attribute like in the search?

certainly.

I'm just wondering why @kaso17 hard-coded it in the first place...

but as long as that download block can support the **attribute** clause, and the **filters** block then this will open up support for several issues that are stuck because of this current restriction.

**Comment by ngosang** [comment]
Implemented in #6891

**Comment by garfield69** [comment]
jackett pre-release 0.12.1561

**Comment by garfield69** [comment]
https://ibit.to/ and the other 2 SiteLinks are currently returning 
`Error connecting to backend. We will be back online soon..`

**Comment by garfield69** [comment]
back online.

**Comment by ilike2burnthing** [comment]
https://ibit.to/ - Connection timed out - Error code 522

**Comment by garfield69** [comment]
v0.20.3082
