### ISSUE TITLE
[mejortorrent] Unable to add indexer

### ISSUE THREAD

**Issue by Soyde** [Jackett/Jackett#6774]
I'm using Jackett Version 0.12.1398.0 at Windows

When I try to add mejortorrentt.org indexer I get the following error:

`CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).    en CloudflareSolverRe.ClearanceHandler.<SendAsync>d__20.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    en Jackett.Common.Utils.Clients.HttpWebClient.<Run>d__8.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Jackett.Common.Utils.Clients.WebClient.<GetBytes>d__17.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Jackett.Common.Indexers.BaseWebIndexer.<RequestBytesWithCookies>d__7.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Jackett.Common.Indexers.MejorTorrent.MejorTorrentRequester.<MakeRequest>d__2.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Jackett.Common.Indexers.MejorTorrent.RssPerformer.<PerformQuery>d__5.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Jackett.Common.Indexers.MejorTorrent.<PerformQuery>d__12.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Jackett.Common.Indexers.MejorTorrent.<PerformQuery>d__11.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Jackett.Common.Indexers.MejorTorrent.<ApplyConfiguration>d__10.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Jackett.Server.Controllers.IndexerApiController.<UpdateConfig>d__13.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.<Execute>d__0.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)    en Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    en Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)    en Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    en Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    en Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    en Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext() --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    en Jackett.Server.Middleware.CustomExceptionHandler.<Invoke>d__3.MoveNext()
--
Jan 02, 2020 04:44:27 PM | Info | Checked for a updated release but none was found. Current: v0.12.1398 Latest: v0.12.1398
Jan 02, 2020 04:44:26 PM | Info | Jackett variant: FullFrameworkWindows`

As I can see when I visit the web a Cloudflare security challenge is shown.
Is there any possibility to bypass it?

**Comment by garfield69** [comment]
there is no way to bypass the cloudflare ReCaptcha challenge which Jackett cannot solve. :-(
until the site drops the anti DDoS protection you will just have to use your browser to access the site.
