### ISSUE TITLE
Soundpark path change

### ISSUE THREAD

**Issue by lightglitch** [Jackett/Jackett#6780]
The path music for sound park no longer works (https://sound-park.world/music?q=National&num=50)
https://github.com/Jackett/Jackett/blob/8a6d3c6c2e898d7db3cc3955591c65f64ad3197f/src/Jackett.Common/Definitions/soundpark.yml#L41 
needs to be always search (https://sound-park.world/search?q=National&num=50)

This happens when the Torznab search is made by artist and album. 
I also think the album should be added to the keywords if exists, not just the artist.
https://github.com/Jackett/Jackett/blob/8a6d3c6c2e898d7db3cc3955591c65f64ad3197f/src/Jackett.Common/Definitions/soundpark.yml#L43

**Comment by garfield69** [comment]
yeah.
the root problem here is that soundpark does not allow the use of the search path of you do not supply any keywords.
But I've run into a limitation of the Cardigann processor conditional handling, which does not allow for nested clauses.

I can check if keywords have been entered and use path search else use path music.
but the addition of the lidarr music-search parms means keywords will always be empty when lidarr provides artist.
And I cant code a if-keywords-search-else-if-artist-search-else-music style conditional.

We could opt to code the indexer in C#, in which case we can code however we like to solve this.
But C# volunteers are in short supply, so this could be a long time coming.

a quick and dirty fix would be to create a clone of this indexer dedicated to lidarr. 
call it soundparklidarr and drop the keywords and use the artist in its place.

**Comment by lightglitch** [comment]
Hi,

This doesn't solve the issue:
```
- path: "search"

**Comment by garfield69** [comment]
Jackett 0.12.1470

**Comment by lightglitch** [comment]
Thx
