### ISSUE TITLE
Inside tool for adding tоrrent trаckers...

### ISSUE THREAD

**Issue by romog123** [Jackett/Jackett#6781]
Why don't you just create an inside tool for adding torrent trackers in to the program.. So people don't have to send links here for you to create it..?

"Add indexer" is so routine.. why I can't add all trackers in the same time..?

**Comment by garfield69** [comment]
>Why don't you just create an inside tool for adding torrent trackers in to the program..

because none of the website produce their html in exactly the same way, so the indexers have to be customised to match the web sites presentation. this is not something than can be automated.

>"Add indexer" is so routine.. why I can't add all trackers in the same time..?

because there are 400 indexers in jackett and you will not have accounts for all of them.
some private sites require captcha to be filled, others require cookies, there is no press a button it all happens automatically. 
live with it.

**Comment by romog123** [comment]
@garfield69 i'm actually asking @Jackett
why are you?

> because none of the website produce their html in exactly the same way

So what? what's the problem to make tool that allow me to add selectors and other needed stuff of site that I need?


> this is not something than can be automated.

I wasn't talked about automated, I talking about inside tool that help easy create it.

**Comment by junglebus** [comment]
Show some respect @romog123 , Jackett wouldn’t be in a working state without all @garfield69 hard work

The code is open source, why don’t you make the inside tool if it’s so simple

**Comment by romog123** [comment]
> Jackett wouldn’t be in a working state without all @garfield69 hard work

it is not in a working state curently) I'm just try it, and its awful, I have much batter tool for this.. just pointing on to the problems, I don't know who he is.. it says that autor is @Jackett not him.. so i write all of this to autor...

> The code is open source, why don’t you make the inside tool if it’s so simple

Maybe because i'm not programmer...

**Comment by garfield69** [comment]
@romog123  I'm just a volunteer with enough free time to contribute. But I am not a C# developer. I specialise in writing indexer in the yaml, the language that the Jackett's Cardigann processor uses to parse the html from websites to generate the search query and parse the results.

The author of Jackett is @kaso17 . He has not contributed for several years now. see #5586

kaso17 often posted: https://github.com/Jackett/Jackett/issues/3009#issuecomment-383609215 to questions about coding your own indexer.

so if you want to write your own indexer, the Cardigann yaml indexer is the tool that kaso17 provided. 
When yaml is not flexible enough to handle the web site requirements, then the indexer can be coded in C# instead. The is usually needed when the web sites provides a json response, or has special requirements that yaml cannot handle.
Either way some programming skills will be required.

**Comment by romog123** [comment]
@garfield69 that https://github.com/Jackett/Jackett/issues/3009#issuecomment-383609215 is exactly what i wanted, thanx.. Only bad that developing is not continue.. so inside tool not will be created soon( if it will be ever.
