### ISSUE TITLE
rutracker indexer isn't available in version 0.12.907.0 (docker)

### ISSUE THREAD

**Issue by gridan17** [Jackett/Jackett#6794]
Hello!
It seems like rutracker isn't available from jackett. The site is blocked in my country so I'm using OpenNIC DDNS on my router + rutracker.lib to solve this issue.
But when I press wrench icon I just get a message 'Request to Jackett server failed'.
Any idea how to solve it

**Comment by ngosang** [comment]
@gridan17 I don't have account so my help is limited.
1. Make sure you have the latest Jackett version
2. Use the Test button in the Jackett UI to test the tracker.
3. If there is an error paste the log, or even better, enable the enhanced log.
