### ISSUE TITLE
[req] Add liaorencili (cili180) public tracker

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6795]
It's a DHT search engine like btdb, btdig ...
Domains:
* http://www.cili180.com
* http://www.cilijj.xyz

**Comment by garfield69** [comment]
actually it is nothing like btdb and btdig behind the scenes. bit of a unicorn.

**Comment by garfield69** [comment]
Jackett 0.12.1494

**Comment by ilike2burnthing** [comment]
search fails on all domains except cilinb#.xyz

**Comment by ilike2burnthing** [comment]
https://www.kmsoso1.xyz/ (and all other site links) - ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.18.551
