### ISSUE TITLE
[FireBit] results without categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6803]
Tracker: FireBit
Search: 720p

Show all results, some of them don't have category.

**Comment by ngosang** [comment]
Related to #6721

**Comment by garfield69** [comment]
problem here is that some of the results contain multiple categories, comma delimited.
the indexer was expecting only one so it couldn't match.
the problematic ones are `new , film` or `series , new` or variations on that theme.
I will see if I can remove the **new** and the **comma** and match the remainder.

**Comment by garfield69** [comment]
this indexer does not require noappend as de3894e3dcd2c3cec6c2f22d82aa907bcddd2a08 fixed the issue.
