### ISSUE TITLE
[eztv] noupload tag in web ui

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6804]
Tracker: eztv
Search: 720p

You can see the NOUPLOAD tag near the FREELEECH tag. All other public trackers don't have this tag and I think this is not necessary.

UPDATE: What means the following fields in the Jackett response?
* MinimumRatio
* MinimumSeedTime
* Gain

Should all public trackers have fixed values for these fields?

**Comment by garfield69** [comment]
those fields are part of the torznab specifications: https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer#torznab-results
      minimumratio: # minimum ratio the torrent client must seed
      minimumseedtime: # minimum number of seconds the client must seed
don't know what **gain** is.

the point being that they only apply to private sites as public sites do not track torrent seeding of their users via torrent client tracker monitoring.

Cardigann provides default values for these two when they are not specified in the indexers.
https://github.com/Jackett/Jackett/blob/d85836ce1bc9f2b6c4f4079d7d6225b8a7449ac4/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1326-L1327

**Comment by garfield69** [comment]
the eztv noupload was set in error by myself in one of my recent changes.
fuzzy finger syndrome. I'll correct it.

**Comment by ngosang** [comment]
@garfield69 don't worry. :)
