### ISSUE TITLE
Bluetigers Missing result!!

### ISSUE THREAD

**Issue by thenamelessthing** [Jackett/Jackett#681]
Hi, I have found a bug for Bluetigers.

When I do a search with jackett for:  

The.Secret.Life.of.Pets.2016.MULTI.1080p.3D.BluRay.SBS.x264.ACOOL

Only these result are found:

http://screencloud.net/v/tWA0

If I do the search on Bluetigers I obtain this:

http://screencloud.net/v/z273

**Comment by kaso17** [comment]
Please send an invite to kaso1717 -at- gmail.com so I can investigate it.

**Comment by thenamelessthing** [comment]
@kaso17 unfortunatly invite are closed at the moment. So how can I help to investigate?

**Comment by thenamelessthing** [comment]
Tracker are now closed.. ;-(

Sniff

https://twitter.com/hashtag/bluetigers
