### ISSUE TITLE
Some public trackers have wrong MinimumRatio / MinimumSeedTime

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6811]
Most public trackers have this values (according to #6804 these are the defaults):
* MinimumRatio = 1 
* MinimumSeedTime = 172800

I think in public trackers both values should be 0, but it will take time to change all of them.

These trackers don't follow the default values (both fields are null):
* Anime Tosho
* Corsaro.red
* Horrible Subs
* Newpct
* RARBG
* YTS

I think the behavior should be the same for all public trackers in one way or another.

**Comment by garfield69** [comment]
from sonarr wiki https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer#minimum-ratioseedtime
>Minimum ratio/seedtime
>These two attributes are included to allow a torrent tracker to specify the seeding requirements on a per torrent basis.
>These values should be set to the long term requirements for the torrent. So if it's freeleech for a decade, you can set minimumratio to 0.0, but if it's only for a day, keep it at 1.0. (0.0 is a bit drastic, but you get the point)
>The idea is that if one of the two criteria is satisfied, the torrent client can put the torrent at a lower priority or stop seeding entirely.
>Specifying one or both of these attributes is recommended, because it allows future clients to appropriately adjust the seeding configuration of the torrent client and/or warn the user to avoid HnRs.

I'm inclined to leave the default values in place regardless of the site being public or not. Opinion?

**Comment by ngosang** [comment]
I agree, we should let the current default values for all public trackes:
    MinimumRatio = 1
    MinimumSeedTime = 172800

I can do the changes in the c# indexers of the first post to follow the rule.

I think we should write an article in the wiki with all default values for future references. Also size = 500 MB and publish_date = now
