### ISSUE TITLE
[FileList] (Config) Unable to configure tracker

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#6815]
I get the following error message when trying to configure FileList:

 An error occurred while updating this indexer

Enhanced log attached
[log.txt](https://github.com/Jackett/Jackett/files/4022098/log.txt)

Jackett version: 0.12.1402.0
Mono version: N/A

**Comment by mcmurray** [comment]
https://github.com/Jackett/Jackett/issues/6782

**Comment by garfield69** [comment]
closing as a duplicate of #6782 the C# indexer filelist login's procedure needs amending.
