### ISSUE TITLE
[req] Add a note in all trackers based in xbtit software

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6821]
By default, the number of torrents per page is low in btiteam software.
In some trackers you already added the notice => https://github.com/Jackett/Jackett/blob/74e0d12a724adca7f5c78e60dfced5b4acb0a4c9/src/Jackett.Common/Definitions/finvip.yml#L21
You can increase the number up to 200.
Add in these:
* Torrentland
* Puntotorrent
* xbytes2

**Comment by garfield69** [comment]
usually aim to get 100 results as this is the torznab default.
unless doing so required more than 5 http requests, in which case lower is better than being rude and overloading the site.

so just so I understand your request, you want me to add a tag at the bottom of the indexers for these 3 to indicate its a btiteam engine, and add a info about setting the torrent per page to 100. 
is that right?

also, apart from the 3 above, and presumably finvip, do you know which other btiteam sites we have indexer for?

**Comment by ngosang** [comment]
> so just so I understand your request, you want me to add a tag at the bottom of the indexers for these 3 to indicate its a btiteam engine, and add a info about setting the torrent per page to 100.
is that right?

yes

> also, apart from the 3 above, and presumably finvip, do you know which other btiteam sites we have indexer for?

* totallykids
* cartoonchaos

I think all search results for this query use btiteam => https://github.com/Jackett/Jackett/search?q=%22index.php%3Fpage%3Dtorrent-details%22&unscoped_q=%22index.php%3Fpage%3Dtorrent-details%22

Usually, you can see the software in the bottom of the page.

**Comment by garfield69** [comment]
punto has the xbtit tag in the login so even though I don't have an a/c I can confirm this.
but xbytes2 has hidden any engine details on the login page, and since I don't have an a/c for this one either I cant confirm.
If you have an a/c on xbytes2 can you post the xbtit version? thanks.

**Comment by ngosang** [comment]
* Puntotorrent => xbtit 2.3.0
* xbytes2 => xbtitFM v2.1.08
