### ISSUE TITLE
[req] Add the tracker engine / software in the definition

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6822]
There are few types of tracker software. I think will be interesting add a note in the definition to update all at once. The field can be hidden.

Eg:
* You changed all based on unit3d => https://github.com/Jackett/Jackett/commit/9220efcc180e46cfb65cbf9a68094ff2b5b5c7f1
* I'm requesting this => #6821

**Comment by ngosang** [comment]
@garfield69 check the software in vizuk and hachede. I think they use the same soffware because you applied the same date fix.

**Comment by garfield69** [comment]
forgot to rename the hachede tag to tsue ;-D

**Comment by garfield69** [comment]
completed, as far as it goes for any yaml sites that I have access to.

**Comment by ngosang** [comment]
Thank you!
