### ISSUE TITLE
[req] add torrent kitty (again)

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6833]
The site https://www.torrentkitty.tv/ is working for me. It's really similar to BTSOW
Mirrors:
* http://www.torrentkitty.se/
* http://www.torrentkitty.app/

UPDATE: This tracker was removed in the past => https://github.com/Jackett/Jackett/search?q=torrentkitty&type=Commits

**Comment by garfield69** [comment]
https://www.torrentkitty.tv searches are regularly returning `Unable to connect to Database Server`

**Comment by garfield69** [comment]
seems like service is restored. 10/10 searches without errors.

**Comment by garfield69** [comment]
https://www.torrentkitty.tv/search/2022/ returning Unable to connect to Database Server

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.torrentkitty.tv/search/2022/ and
https://www.torrentkitty.tv/information/FA08F68922708FE11B8D03E07F55F1E59453CC38
return Unable to connect to Database Server
some searches work, star trek, 2021, but details page usually does not.

**Comment by ilike2burnthing** [comment]
I think this back up, able to search and open details pages for about 2min straight.

**Comment by ilike2burnthing** [comment]
> https://www.torrentkitty.tv/search/2022/ and https://www.torrentkitty.tv/information/3CB77D4B88694100EEAD98943525CA8CDF2CA933 return Unable to connect to Database Server some searches work, star trek, 2021, but details page usually does not.

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://www.torrentkitty.tv/search/2022/ and https://www.torrentkitty.tv/information/6352863AD45EB0A8219D58CB351ECB339BEBAEEE return Unable to connect to Database Server some searches work, star trek, 2021, but details page usually does not.

**Comment by ilike2burnthing** [comment]
back up
