### ISSUE TITLE
[Anime Tosho] unrelated results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6836]
Trackers:
- [ ] Anime Tosho
- [x] ~~BigFANGroup~~

Search: salva gato

**Comment by garfield69** [comment]
AnimeTocho is a C# indexer using the newznab feed
https://github.com/Jackett/Jackett/blob/ee37d5b8f028b2ead7b8e87741324bd17b19aea1/src/Jackett.Common/Indexers/Feeds/AnimeTosho.cs#L14
Not my cup of tea, needs a C# dev to enhance if its even possible.

I will look into bigfangroup, its a yaml indexer. if the site does not have a title's only filter then I'll add a row andmatch filter to the indexer.

**Comment by garfield69** [comment]
I don't get anything for `salva gato` on bigfangroup
![image](https://user-images.githubusercontent.com/6933240/71805137-4fe29d80-30ca-11ea-956b-e91c61f0c971.png)

**Comment by ngosang** [comment]
> I don't get anything for salva gato on bigfangroup

Me neither. I swear you yesterday I got results...

I will take a look at Anime Tosho in the future.

**Comment by kanedauy** [comment]
An error occurred while configuring this indexer
Exception (animetosho): Network is unreachable: Network is unreachable

**Comment by ngosang** [comment]
Fixed in #8423
