### ISSUE TITLE
[lostfilm] Exception (lostfilm): Name or service not known: Parse error

### ISSUE THREAD

**Issue by Skyline404** [Jackett/Jackett#6843]
All other indexers are works, but not lostfilm
https://pastebin.com/ZbZ39yMi

Jackett Version 0.12.1449.0
Mono JIT compiler version 6.6.0.161 (tarball Tue Dec 10 10:44:52 UTC 2019)

**Comment by garfield69** [comment]
seen another lostfilm ticket this month #6801
but the indexer works for me.

Since I'm not a C# dev and the lostfilm indexer is written in C# I'm not going to be able to help with this one.
ping to a volunteer to investigate.

**Comment by ngosang** [comment]
@krin-san we have 5 recent issues about lostfilm. Could you help us?
https://github.com/Jackett/Jackett/search?q=lostfilm&state=open&type=Issues

**Comment by krin-san** [comment]
@ngosang, thanks for letting me know. Sure, will take a look on issues on weekends. Normally I don't develop on C# so don't have a build environment set up to quickly check them.

**Comment by krin-san** [comment]
While fixing other issues for lostfilm indexer, I never reproduced this issue. I'm not in Russia and don't have any governmental blocking systems in between.

@Skyline404, the error you get is either related to DNS misconfiguration _(saw Ubuntu threads mentioning an easy fix in hosts file)_ or a country-level DNS blocking. If you use SOCKS proxy, your DNS might still be affected. Please try to see if indexer works with VPN.

**Comment by ngosang** [comment]
We can't do anything to fix this. The error `Name or service not known` is because the DNS domain www.lostfilm.tv is blocked in your country. You will have to find an alternative domain, or use VPN or Proxy.
