### ISSUE TITLE
[req] option in configuration of OxTorrent and GkTorrent

### ISSUE THREAD

**Issue by guillaume-gta** [Jackett/Jackett#6848]
Hi,

could we have an option in configuration of oxTorrent and GkTorrent to be able to choose between etorrent.click and magnet? As it's done for ETTV? 

On download page of OxTorrent we found 2 button, one is a link to a torrent file, one is for magnet. And I have an issue with the magnet. 

I'm working one a couchpotato like application, and I use Jacket to search and launch download in rtorrent. So I get the result of jacket, and if it's a magnet link, I parse this link to get the hash of the torrent, and I use this hash to retrieve info from rtorrent, as the files contained in the torrent and if the download is finished. But in oxTorrent, the hash in the magnet link is not the hash of the torrent that I can see in rutorrent. 
For example, in https://www.oxtorrent.com/torrent/3571/la-vie-scolaire-french-bluray-720p-2019, the hash in magnet link is 4APAS2PBKDATKHWXYZ2IJLDLP7BJ35TK, but in rutorrent it is 234C5BCA662512409CEC596711B1CAD574C2DC1E. And the link for downloading the torrent has the correct hash. So if I have the possibility to choose between torrent link and magnet link for this 2 indexer, it will solve my issue.

Or if someone know how retrieve the final hash from a magnet link, it could help me too.

Regards
Guillaume

(At the bottom of your Jackett Dashboard page) Version 0.12.1449.0 
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by garfield69** [comment]
yeah, nah. I'm restricted by the Cardigann processor's [Download support](https://github.com/Jackett/Jackett/wiki/Definition-format#download), which does not have any yaml statements that would let me fetch a .torrent href from the torrent details page, grab the hash and use it in place of the magnet's hash in its href instead.

But there is no problem adding a Config option to the two yaml indexers that lets you choose to use the href from the telecharger href or the magnet href, just like the ettv yaml indexer got.

I'll post when the next jackett get published with the enhancements.

**Comment by garfield69** [comment]
Jackett 0.12.1486

**Comment by guillaume-gta** [comment]
Thanks a lot for your quick action! I will test as soon as new docker image based in 0.02.1486 will be available.

**Comment by guillaume-gta** [comment]
It works like a charm, thanks again! You solve my issue! Great application by the way!
