### ISSUE TITLE
Support LibreSSL

### ISSUE THREAD

**Issue by mustaqimM** [Jackett/Jackett#6852]
If I try to run the binary, I get:
```zsh
$❯ ./jackett
01-06 20:35:11 Info Starting Jackett v0.12.1470.0
01-06 20:35:11 Info Environment version: 3.0.1 (/home/mustaqim/Downloads/Jackett/)
01-06 20:35:11 Info OS version: Unix 5.3.18.1 (64bit OS) (64bit process)
01-06 20:35:11 Info Jackett variant: CoreLinuxAmdx64
01-06 20:35:11 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
01-06 20:35:11 Info App config/log directory: /home/mustaqim/.config/Jackett
01-06 20:35:11 Info issue: Void \r (\n) (\l)
01-06 20:35:11 Info Using HTTP Client: HttpWebClient2NetCore
No usable version of libssl was found
zsh: abort      ./jackett
```

The libressl binary is named `/usr/bin/openssl` but that doesn't matter so I'm forced to use the mono version

**Comment by junglebus** [comment]
@mustaqimM What operating system?

**Comment by mustaqimM** [comment]
@junglebus
```
$❯ uname -a

Linux void 5.4.8_1 #1 SMP PREEMPT Sun Jan 5 18:00:07 UTC 2020 x86_64 GNU/Linux
```

**Comment by junglebus** [comment]
That makes sense, had never heard of 'Void' OS. Microsoft response [here ](https://github.com/dotnet/corefx/issues/26739) and there is a few reddit/stackoverflow threads as well
'Void' isn't an OS supported by Jackett -> supported OSes in the readme
You are going to hit the same issue for anything written in .NET Core e.g. Jellyfin, Ombi and soon Radarr
@garfield69 I'd remove 'needs c#', this is framework level, would need Microsoft to support it

**Comment by garfield69** [comment]
I'm going to close this ticket, since the OS is unsupported by MS .Net core builds.
It's one of the reasons we are keeping the mono builds available, it's our alternative option, to allow unsupported OS to have a chance to run Jackett if they cannot use the .net core version.

**Comment by mustaqimM** [comment]
Just to make it clear: [LibreSSL](https://en.wikipedia.org/wiki/LibreSSL) isn't supported. Void is just a linux distro (like Ubuntu) that uses LibreSSL instead of OpenSSL.

**Comment by cadatoiva** [comment]
And to be clear, not all versions of linux have support for dotnet-core, which is the bigger problem Microsoft maintains a list [here](https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md) of supported OS versions for different dotnet-core versions. Jackett is currently using dotnet-core 3.0.

It's just not something that a ton of time can be put into to make work, especially since it's possible nothing can be done by us and it has to be corrected upstream in dotnet.
