### ISSUE TITLE
Support for a "sanitized" field for heavily sanitized queries from Sonarr

### ISSUE THREAD

**Issue by curiositycasualty** [Jackett/Jackett#6853]
The distillation of the issue is difficulty using Sonarr and Jackett in combination when you have a heavily sanitized query.

Felt I should create an issue on this project to track the request for this "sanitized" field.

See also:
https://github.com/Sonarr/Sonarr/issues/1225#issuecomment-565821390

**Comment by ngosang** [comment]
We are providing good integration with Sonarr / Radarr but we can't do anything if Sonarr sends us bad queries. I'm closing because this has to be solved in third party apps.
