### ISSUE TITLE
Elite-tracker : Add option "Replace VOSTFR with ENGLISH"

### ISSUE THREAD

**Issue by neoliquid37** [Jackett/Jackett#6855]
Elite-tracker is a french tracker so the torrents with the tag VOSTFR, Fastsub, SUBFRENCH are audio ENGLISH + subtitle FRENCH.

We should then have the option to replace VOSTFR with ENGLISH the same way we can do it for YGG

**Comment by neoliquid37** [comment]
Thanks you again ! @garfield69

**Comment by garfield69** [comment]
Jackett 0.12.1494

**Comment by neoliquid37** [comment]
Hi @garfield69.
Hadn't checked but the tags Fastsub, SUBFRENCH are not replaced by ENGLISH.

**Comment by garfield69** [comment]
oh. 
so if you tick the vostfr box, we should be replacing vostfr, fastsub and subfrench with english?

**Comment by garfield69** [comment]
are you sure about this?
every instance of FASTSUB I see has VOSTFR in the title too
![image](https://user-images.githubusercontent.com/6933240/79937382-d4a4cc00-84ad-11ea-8e4f-b350cba02880.png)
you will end up with `Young.​Sheldon.​S03E20.​ENGLISH.​ENGLISH.​HDTV.​x264-​WEEDS`

**Comment by garfield69** [comment]
Jackett 0.16.103

**Comment by neoliquid37** [comment]
My bad for FASTSUB.
Thank you for taking SUBFRENCH into account. :)
