### ISSUE TITLE
Jackett on VPS changing API keys often.

### ISSUE THREAD

**Issue by Cailerh** [Jackett/Jackett#6858]
So I installed Jackett and numerous other programs with an all in 1 installer on my VPS. About twice a day I have to redo my Sonarr and Radarr indexers because Jackett has changed API key. I am unsure if it is because my VPS puts Jackett to sleep or if the deleting temp files in the logs below is causing it. I don't run Jackett from a command line it auto starts from the all in 1 installers settings. I have googled this issue and some people recommend putting Jackett's config file outside of the original installation area but I can't find any instructions on how to move it or how to have Jackett look in a different spot. Logs are in the screenshot below from the time I redid all the indexers to when I got off my PC the night before.

[http://prntscr.com/qkhmlx](url)

Jackett Version 0.12.1486.0

**Comment by garfield69** [comment]
the api key is saved in the ServerConfig.json file which usually resides on linux systems at `~/.config/Jackett`
If Jackett cannot find the ServerConfig.json file then it assumes this is a first time startup and allocates a new API key.
which Jackett package did you install and from where?
Apart from the apikey, is the jackett dashboard showing the same active indexers that you previously set up of are they also gone?

**Comment by garfield69** [comment]
setting a home directory may be what you need.
https://github.com/Jackett/Jackett#home-directory

**Comment by Cailerh** [comment]
I installed Jackett from a link my friend said to use for all in 1 setup [https://raw.githubusercontent.com/liaralabs/swizzin/master/setup.sh](url) It shows the same active indexers and I'm not sure about the home directory but I do have root access and everything is located in /home/cailerh

**Comment by garfield69** [comment]
look, we don't support friend installation scrips or any Jackett package that does come from this github.
there are just too many flavours of linux out there and many custom jackett version based on our source but with personal tweeks for the relevant platforms that they are trying to run Jackett on.

that said, if you have terminal access to the system, then you have a chance to sort this out yourself.
so first off, see if you can find if your system is using systemd to launch jackett at system startup.
from a terminal `cd /etc/systemd/system/` to see if you have a systemd startup folder
and then see if it contains file '`jackett.service` using the `ls` command.

**Comment by Cailerh** [comment]
Yes it has a Jackett@.service

**Comment by garfield69** [comment]
@ngosang  question for you. with the change of the systemd script to execStart the /jackett_launcher.sh script , if users want to add a custom home directory, do they still put the `Environment=XDG_CONFIG_HOME=/path/to/folder` in the systemd script or does this need to (also) go into the jackett_launcher.sh script?
Actually, before you answer that, with your more extensive linux knowledge than I, can you cast you eye over this ticket and see if I am heading in the right direction or if there is some other angle. Thanks.

**Comment by garfield69** [comment]
@Cailerh can you post the content of that jackett.service so we can check what is being started. thanks.

**Comment by Cailerh** [comment]
Uh don't do much of this stuff so can't figure out how to open the jackett.service to get the content of it lol.

**Comment by garfield69** [comment]
join the club. My platform of choice is windows, but a dabbled in linux and macos for testing jackett.
see if `gedit Jackett.service` works.

**Comment by Cailerh** [comment]
[http://prntscr.com/qkj5qq](url) screenshotted the content of the file

**Comment by garfield69** [comment]
so this is a very customised startup script and not the one we supply. So I am guessing the use of `%I` everyplace is what makes each image startup of jackett unique and causes jackett to think its a fresh install every time you start it.
so lets try this:
1. shutdown the jackett service `systemctl stop jackett@.service`
2. edit that script and add `Environment=XDG_CONFIG_HOME=/home/cailerh/jackett` below the ExecStart line and save
3. create folder `/home/cailerh/jackett` `cd /home/cailerh/` `mkdir jackett`
4. startup jackett service `systemctl start jackett@.service`

in theory, the first run will create the api key and save the ServiceConfig.json file in `/home/cailerh/jackett` and subsequent runs will find it and you should be good to go.
in theory ...

**Comment by garfield69** [comment]
oops, finger trouble, that should be: before the execstart not below or after.

**Comment by Cailerh** [comment]
Getting that error. I also went back into the service file but got a warning that I am using a swap could that be a problem as well?
"Failed to stop jackett@.service: Unit name jackett@.service is missing the instance name."

**Comment by garfield69** [comment]
nah i'm sorry but now we are out of my experience. you are going to have to wait and see if a volunteer with more linux and perhaps VPS experience can help out.

**Comment by Cailerh** [comment]
Ok well thank you for trying to help :)

**Comment by ngosang** [comment]
@garfield69 that installer has more than 500 starts so we should fix the root of the problem. Since this problem is not caused by Jackett, I moved the issue here => https://github.com/liaralabs/swizzin/issues/259

@Cailerh Take a look at that issue and answer there. Just curiosity. Could you execute this and paste the response?
`ls -la /home`

**Comment by Cailerh** [comment]
root@CailerH:~# ls -la /home
total 16
drwxr-xr-x  4 root    root    4096 Dec  3 20:57 .
drwxr-xr-x 19 root    root    4096 Jan  4 02:26 ..
drwxr-x--- 11 cailerh cailerh 4096 Dec  8 21:21 cailerh
drwxr-x---  2 debian  debian  4096 Sep 25 15:27 debian


It was giving me an error when trying to edit the jackett@service file saying that I might have started editing it before and didn't close it. And when I get into editing it, it won't let me add any lines to add that Environment=XDG_CONFIG_HOME=/path/to/folder command so I have just done a reboot. Sorry for delayed answer I had to go to work for a bit.

**Comment by Cailerh** [comment]
After reading that liaralabs put a fix on the swizzin installer I ran it again and redid Jackett and it stayed the same API key through 2 reboots so it seems to have been fixed. Thank you for the help :D
