### ISSUE TITLE
[REQ] SceneXpress

### ISSUE THREAD

**Issue by f0ghqn1ih2** [Jackett/Jackett#6859]
Tracker's Name: SceneXpress

Genre: ~~General~~ Movies

Sign-up Link: http://www.scenexpress.org/?p=signup&pid=16

**Comment by garfield69** [comment]
http://www.scenexpress.org/ returning ERR_NAME_RESOLUTION_FAILED

**Comment by dimqua** [comment]
Is this a working website?

**Comment by garfield69** [comment]
domain was broken 15 days ago. If in another 15 I don't see an alternate posted, then I'll be removing the indexer.

**Comment by dimqua** [comment]
@garfield69 new address: http://scenexpress.zapto.org/

**Comment by dimqua** [comment]
No, I've found an announcement here:
https://www.invitehawk.com/topic/122031-scenexpress-movies/

**Comment by garfield69** [comment]
ok. well its clearly a different site engine, and likely a different operator.
so I will need to build a new indexer to replace the old one.

**Comment by garfield69** [comment]
http://scenexpress.zapto.org/ returning ERR_CONNECTION_TIMED_OUT
this whole nordichd / sex debacle is getting quite stale. 
if by the end of February things are not settled and clear I'm deleting both indexers.

**Comment by dimqua** [comment]
Still doesn't work.
