### ISSUE TITLE
[req] add new public tracker fitgirl

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6862]
Very popular => https://torrentfreak.com/top-10-most-popular-torrent-sites-of-2020-200105/
Based in Wordpress with magnets in the detailed view.
There are few info in the search results... only the title...

http://fitgirl-repacks.site/

**Comment by garfield69** [comment]
not suitable.
this site is for Repacks of selected games done by the site owner.
the links provided are all mirrors of the uploads that she provides at 1337x, KAT, Tutor and Tapochek as well as a few direct download sites.
