### ISSUE TITLE
[req] add new public tracker dytt8

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6863]
It's popular, but I can't understand anything, so I don't know... :)
https://torrentfreak.com/top-10-most-popular-torrent-sites-of-2020-200105/

~~https://dytt8.net/index0.html~~
https://dytt8.net/index.htm

**Comment by garfield69** [comment]
some one else can do this one.

**Comment by garfield69** [comment]
https://dytt8.net/ returning ERR_SSL_VERSION_OR_CIPHER_MISMATCH
and http://dytt8.net/ returning Error 1001 DNS resolution error
