### ISSUE TITLE
[req] add new public tracker etoland

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6864]
It's popular, but I can't understand anything, so I don't know... :)
https://torrentfreak.com/top-10-most-popular-torrent-sites-of-2020-200105/

http://etoland.co.kr

**Comment by garfield69** [comment]
some one else can do this one.

**Comment by garfield69** [comment]
this site is more like a forum than a torrent tracker. 
and its too difficult to make out how its structured.
