### ISSUE TITLE
[ExtraTorrent.cd] found 0 releases

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#6865]
Running latest LinuxServer.io Docker image - v0.12.1486-ls49

Enhanced log provided (hopefully stripped of anything personal) - [log.txt](https://github.com/Jackett/Jackett/files/4033386/log.txt)

--------

P.S. Solid Torrents' search isn't working either, but that's a problem with their site, not Jackett

**Comment by garfield69** [comment]
works for me.
but your IP appears to have been blacklisted.
```
Access denied 
extratorrent.si used Cloudflare to restrict access
Error 1020
What happened?
This website is using a security service to protect itself from online attacks.
```

from a browser on the same machine that is running Jackett can you access https://extratorrent.si/ ?

**Comment by ilike2burnthing** [comment]
Appears they have blocked some NordVPN IPs. Tried a few different servers and eventually found one that worked.
