### ISSUE TITLE
[divxtotal] add support for Sonarr/Radarr

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6869]
Current implementation for DivxTotal doesn't support search in the scene format. Eg:
* American Horror Story S09E08
* Marco Polo 2014 S02E08
* Marco.Polo.2014.S02E08

Since the DivxTotal site neither support it, this has to be done in our side. Something like in Mejortorrent y Newpct.

**Comment by garfield69** [comment]
jackett pre-release 0.12.1561
