### ISSUE TITLE
TFile download torrent file problem

### ISSUE THREAD

**Issue by rainbowjose** [Jackett/Jackett#6870]
Error downloading tfile http://megatfile.cc/forum/link.php?t=17t5i&v=ursb9e65a62a
--
Jan 08, 2020 10:01:06 PM | Error | CardigannIndexer (tfile): Download selector a[href^="download.php?id="] didn't match:

 Jackett Version 0.12.1398.0

**Comment by garfield69** [comment]
works for me. try again?

**Comment by rainbowjose** [comment]
https://pastebin.com/Lxh5VQET
Full log, tried again. Or you mean update jackett and try again?

**Comment by rainbowjose** [comment]
Not working :(

Jan 09, 2020 08:01:24 PM | Error | Error downloading tfile http://megatfile.cc/forum/link.php?t=17t5i&v=ursb9e65a62a
-- | -- | --
Jan 09, 2020 08:01:24 PM | Error | CardigannIndexer (tfile): Download selector a[href^="download.php?id="] didn't match:  <!doctype html> <html lang="ru"> <head> <title>Скачать фильм Волшебная лампа Аладдина (1967) BDRip через торрент</title> <meta name="description" content="Детское / Семейное кино &raquo; Скачать торрент Волшебная лампа Аладдина (Борис Рыцарев) [1967, сказка, фэнтези, BDRip-AVC]"/><meta name="keywords" content="Волшебная лампа Аладдина (Борис Рыцарев), скачать Детское / Семейное кино, скачать торрент, torrent, торент, скачать бесплатно, скачать без регистрации"/><link rel="canonical" href="http://megatfile.cc/forum/viewtopic.php?t=1314778" /><meta http-equiv="Content-Type" content="text/html; charset=windows-1251"> <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> <meta name="robots" content="noarchive"> <link rel="stylesheet" href="http://megatfile.cc/media/screen.1161.css" type="text/css"> <link rel="alternate" type="application/rss+xml" title="RSS Feed" href="/rss/" > <link rel="search" type="application/opensearchdescription+xml" title="Найти на tfile.me" href="http://megatfile.cc/opensearch.xml"> <script type="text/javascript">window.q=[];window.$=function(f){q.push(f)}</script> <script type="text/javascript" src="http://megatfile.cc/js/ads.176.js" charset="UTF-8"></script>  </head><body>  <div id="head" class="full"> <div id="top_info" style="line-height: 24px"> <div class="l">  <a href="/login/" style="border-right:solid 1px #404090;padding:0 5px 0 5px" rel="nofollow">Войти</a> <a href="/forum/profile.php?mode=register" style="border-right:solid 1px #404090;padding:0 5px 0 5px" rel="nofollow">Регистрация</a> <a href="/forum/profile.php?mode=sendpassword" rel="nofollow" style="padding-left:5px">Забыли пароль?</a> </div> <div class="r"> <form action="http://search.tfile.me/" method="get" id="topSearch"> <a href="javascript:$('#topSearch').submit()" title="Найти" class="s_search" rel="nofollow">&nbsp;</a> <input type="text" name="q" id="searchq" size="16" value="" placeholder="Поиск..." autocomplete="off"/> </form> </div> </div> <div id="top_tools"> <a href="http://megatfile.cc/" class="logo"></a> <div id="cats"> <ul id="top-icons"> <li><a href="/forum/?c=2"><i class="top-icons-video"></i>видео</a></li> <li><a href="http://tfile-music.cc/forum/?c=5"><i class="top-icons-music"></i>музыка</a></li> <li><a href="/"><i class="top-icons-soft"></i>софт</a></li> <li><a href="/forum/?c=18"><i class="top-icons-games"></i>игры</a></li> <li><a href="/forum/?c=10"><i class="top-icons-books"></i>книги</a></li> <li><a href="/forum/?c=21"><i class="top-icons-sport"></i>спорт</a></li> <li><a href="/forum/?c=4"><i class="top-icons-other"></i>разное</a></li> </ul> </div> </div> </div>  <div id="table_reduser">  <div id="topicContainer">  <span class="path"><div itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="http://megatfile.cc/forum/" itemprop="url"><span itemprop="title">Каталог торрентов</span></a> &raquo; <div itemprop="child" itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/forum/?c=2" itemprop="url"><span itemprop="title">Видео</span></a> &raquo; <div itemprop="child" itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/forum/viewforum.php?f=1536" itemprop="url"><span itemprop="title">Советское кино</span></a> &raquo; <div itemprop="child" itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/forum/viewforum.php?f=1539" itemprop="url"><span itemprop="title">Детское / Семейное кино</span></a></div></div></div></div></span>    <div id="pageTitle"><h1>Скачать фильм Волшебная лампа Аладдина (Борис Рыцарев) / [1967, сказка, фэнтези, BDRip-AVC] - торрент</h1></div> <p style="color:#666;">Нажмите синюю кнопку, чтобы cкачать бесплатно через торрент <i>фильм</i>. Фильм доступен на нашем торрент-трекере бесплатно, без регистрации и смс.</p>    <div id="topicStats"> <div class="title">Статистика раздачи</div> <span class="c"> <span class="seeders">0 [ 0 <small>b/s</small> ] &uarr;</span> <b>1.7 GB</b> <span class="leechers">&darr; 0 [ 0 <small>b/s</small> ]</span> </span> </div>  	<table id="postList" cellpadding="1" cellspacing="1"> <tr> <th>Автор</th> <th> Сообщение </th> </tr>  			<tr> 				<td class="pI"> 					<span class="name">Astarot999</span> 					<img 							src="http://a.turbopic.org/7521669085c06c36ad17cb.jpg">  </td> 				<td class="pC"> 					<div class="pP"> 						 							<img src="http://megatfile.cc/blueGene/images/icon_minipost.gif" width="12" height="9"> 							 							<span class="date"><a href="http://megatfile.cc/forum/browse/2019/12/06/" title="Все торренты на трекере за 6 декабря 2019 года">2019-12-06</a> 13:48</span> 							</div> 					<div class="pT"> <span style="color:#015781;font-size:20px;display:block;padding-top:7px;">Волшебная лампа Аладдина</span> <br><img src="https://b.radikal.ru/b06/1912/80/d2248de1348b.jpg" class="postImgAligned" alt="Волшебная лампа Аладдина " title="Постер Волшебная лампа Аладдина "/><span class="field">Формат:</span> BDRip-AVC, MKV, H.264, AC3 <br><span class="field">Режиссер:</span> Борис Рыцарев <br><span class="field">Жанр:</span> <a class='postLink' href="/video/genre/сказка/">сказка</a>, <a class='postLink' href="/video/genre/фэнтези/">фэнтези</a> <br><span class="field">Продолжительность:</span> 01:18:31 <br><span class="field">Год выпуска:</span> <a class='postLink' href="/forum/ssearch.php?y=1967"><span style="font-weight:bold"><span style="color: red">1967</span></span></a> <br><span class="field">В ролях:</span> <a class="afterLink" href="/video/actor/борис быстров/">Борис Быстров</a>, <a class="afterLink" href="/video/actor/додо чоговадзе/">Додо Чоговадзе</a>, <a class="afterLink" href="/video/actor/андрей файт/">Андрей Файт</a>, <a class="afterLink" href="/video/actor/отар коберидзе/">Отар Коберидзе</a>, <a class="afterLink" href="/video/actor/екатерина верулашвили/">Екатерина Верулашвили</a>, <a class="afterLink" href="/video/actor/георгий милляр/">Георгий Милляр</a>, <a class="afterLink" href="/video/actor/гусейн садыхов/">Гусейн Садыхов</a>, <a class="afterLink" href="/video/actor/валентин брылеев/">Валентин Брылеев</a>, <a class="afterLink" href="/video/actor/юрий чекулаев/">Юрий Чекулаев</a>, <a class="afterLink" href="/video/actor/отар биланишвили/">Отар Биланишвили</a>, <a class="afterLink" href="/video/actor/сарры каррыев/">Сарры Каррыев</a>, <a class="afterLink" href="/video/actor/яков беленький/">Яков Беленький</a>, <a class="afterLink" href="/video/actor/эммануил геллер/">Эммануил Геллер</a>, <a class="afterLink" href="/video/actor/николай горлов/">Николай Горлов</a>, <a class="afterLink" href="/video/actor/семён сафонов/">Семён Сафонов</a>, Надежда Семенцова <br><span class="field">Описание:</span>  <br><span style="color: green">Злой колдун-магрибинец взывает к звездам, чтобы те поведали ему имя человека, что найдет волшебную лампу, способную творить чудеса. Звезды ответили: «Это Аладдин». В Багдаде живет дочь султана, красавица Будур. Всякий, кто посмеет взглянуть на нее, будет казнен. Но своевольная и капризная принцесса заставляет Аладдина взглянуть на нее. Юноша как увидел принцессу, так сразу в нее и влюбился. А волшебная лампа со всемогущим джином, готовым выполнить любой приказ повелителя, помогла Аладдину сохранить свою любовь и справиться с Магрибинцем...</span> <br> <br><a href="http://www.kinopoisk.ru/level/1/film/45833/" rel="nofollow" target="_blank"><img src="http://www.kinopoisk.ru/rating/45833.gif"/></a> <br> <br><span class="field">Видео:</span> 1024x414 (2.47:1), 25 fps, AVC Н.264 High@L4.1 ~2735 kbps avg, 0.258 bit/pixel <br><span class="field">Аудио:</span> 48 kHz, AC3, 6/0  (L R C LFE Ls R) ch, ~448.00 kbps avg <br> <br><div class="spoiler"><a href="#" class="splink" onclick="$$('.spoiler img').each(function(){var rs=$$(this).attr('rsrc');if(rs!=undefined){this.src=rs;$$(this).css('width','100%');}});return App.Common.spoiler(this)"><b></b>MI</a><div>Общее <br>Уникальный идентификатор                 : 244487425588019294383339705575565605756 (0xB7EE90BDD512928284CC4F22FD2ABB7C) <br>Полное имя                               : D:\VIDEO\Релизы\Волшебная лампа Аладдина\Volshebnaya.lampa.Aladdina.1966.x264.BDRip(AVC).ClubTorrent.koska1.mkv <br>Формат                                   : Matroska <br>Версия формата                           : Version 2 <br>Размер файла                             : 1,75 Гбайт <br>Продолжительность                        : 1 ч. 18 м. <br>Общий поток                              : 3185 Кбит/сек <br>Дата кодирования                         : UTC 2014-05-24 19:17:44 <br>Программа кодирования                    : mkvmerge v5.0.1 ('Es ist Sommer') built on Oct 24 2011 19:45:06 <br>Библиотека кодирования                   : libebml v1.2.2 + libmatroska v1.3.0 <br> <br>Видео <br>Идентификатор                            : 1 <br>Формат                                   : AVC <br>Формат/Информация                        : Advanced Video Codec <br>Профиль формата                          : High@L4.1 <br>Параметр CABAC формата                   : Да <br>Параметр ReFrames формата                : 10 кадров <br>Идентификатор кодека                     : V_MPEG4/ISO/AVC <br>Продолжительность                        : 1 ч. 18 м. <br>Битрейт                                  : 2735 Кбит/сек <br>Ширина                                   : 1024 пикселя <br>Высота                                   : 414 пикселей <br>Соотношение сторон                       : 2,473 <br>Режим частоты кадров                     : Постоянный <br>Частота кадров                           : 25,000 кадров/сек <br>Цветовое пространство                    : YUV <br>Субдискретизация насыщенности            : 4:2:0 <br>Битовая глубина                          : 8 бит <br>Тип развёртки                            : Прогрессивная <br>Бит/(Пиксели*Кадры)                      : 0.258 <br>Размер потока                            : 1,47 Гбайт (84%) <br>Библиотека кодирования                   : x264 core 138 r2358 9e941d1 <br>Настройки программы                      : cabac=1 / ref=10 / deblock=1:-2:-2 / analyse=0x3:0x133 / me=umh / subme=8 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=1 / me_range=32 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-3 / threads=6 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=16 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=2735 / ratetol=1.0 / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=2:1.00 <br>Язык                                     : English <br>Default                                  : Да <br>Forced                                   : Нет <br> <br>Аудио <br>Идентификатор                            : 2 <br>Формат                                   : AC-3 <br>Формат/Информация                        : Audio Coding 3 <br>Расширение режима                        : CM (complete main) <br>Параметр Endianness формата              : Big <br>Идентификатор кодека                     : A_AC3 <br>Продолжительность                        : 1 ч. 18 м. <br>Вид битрейта                             : Постоянный <br>Битрейт                                  : 448 Кбит/сек <br>Каналы                                   : 6 каналов <br>Расположение каналов                     : Front: L C R, Side: L R, LFE <br>Частота                                  : 48,0 КГц <br>Битовая глубина                          : 16 бит <br>Метод сжатия                             : С потерями <br>Размер потока                            : 252 Мбайт (14%) <br>Default                                  : Да <br>Forced                                   : Нет</div></div><div class="spoiler"><a href="#" class="splink" onclick="$$('.spoiler img').each(function(){var rs=$$(this).attr('rsrc');if(rs!=undefined){this.src=rs;}});return App.Common.spoiler(this)"><b></b>Показать скриншоты</a><div style="text-align:center"><img rsrc="https://funkyimg.com/i/Kvj7.png"/> <br> <br><img rsrc="https://funkyimg.com/i/Kvj9.png"/> <br> <br><img rsrc="https://funkyimg.com/i/Kvjb.png"/> <br> <br><img rsrc="https://funkyimg.com/i/Kvjd.png"/> <br></div></div> <br clear="all"/>   </div>  <ul class="nav nav-tabs"> <li class="active"><a href="#torrent" data-toggle="tab">Торрент файл</a></li> <li><a href="#howto" data-toggle="tab">Как качать?</a></li> <li><a href="#files" data-toggle="tab" data-url="/torrent/files/?id=1047402">Файлы в торренте</a></li> </ul> <div class="tab-content torrent"> <div class="tab-pane active" id="torrent">   <div class="info-torrent"> <h5>Информация о торренте:</h5> Размер содержимого: <span style="font-weight:bold">1.7 GB</span><br/> Скачан: <span style="font-weight:bold">122</span> раза<br/> Статус: <span style="font-weight:bold">Проверен</span></br> Зарегистрирован на трекере: <span style="font-weight:bold" class="regDate">2019-12-06 12:48</span><br/> </div>  <div>  <a href="magnet:?xt=urn:btih:8683adf0ba6e26cb1436096035d760d11a44d827&dn=megatfile.cc.1314778.torrent&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969" class="btn btn-primary btn-large" title="Скачать бесплатно и без регистрации" id="dlbt" rel="nofollow" name="0179144_%5Btfile.ru%5D.torrent">Скачать торрент</a> <div class="help" style="padding-top:1em"> <div id="help-links">  <i class="fa fa-magnet" style="color:#A92525"></i> <a href="magnet:?xt=urn:btih:8683adf0ba6e26cb1436096035d760d11a44d827&dn=megatfile.cc.1314778.torrent&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969" title="Магнитная ссылка на торрент" rel="nofollow">Магнитная ссылка</a> </div>  <br><br>Поддержи раздачу &mdash; поставь лайк: <script type="text/javascript" src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js" charset="utf-8"></script> <script type="text/javascript" src="//yastatic.net/share2/share.js" charset="utf-8"></script> <div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,moimir,gplus" data-counter="" style="margin-bottom:0.5em"></div> </div> </div> </div> <div class="tab-pane" id="howto"> <h4>Как качать с торрента?</h4> <a href="viewtopic.php?t=63676" target="_blank" rel="nofollow">Руководство по загрузке файлов с торрент-трекера</a>. </div> <div class="tab-pane" id="files"> <div id="tfiles-holder"></div> </div> <div class="tab-pane" id="log"> <ul>  </ul> </div> </div> </td> 			</tr> 			 <tr> 					<td colspan="2"> 						 					</td> 				</tr> 			 	</table> 	<div style="text-align:center;padding:1em 0;font-size:1.4em;background:#f0f0f0"> 		<i class="fa fa-comment" style="float:left;font-size:3em;color:#ccc;margin-left:1em;"></i> 		Писать комментарии на нашем торрент-трекере могут только зарегистрированные пользователи. 		<br><a href="/forum/profile.php?mode=register" rel="nofollow">Зарегистрируйтесь</a> или 		<a href="/login/" rel="nofollow">авторизируйтесь</a> на сайте.</div> 	 		 	</div> <script>  $(function() { App.Topic.init(); }) </script> </div> <div id="foot_links" class="full"> <div id="cpy" style="padding-top:4px"></div> <a href="//megatfile.cc/forum/newest">новые торренты</a> &middot; <a href="//megatfile.cc/forum/sitemap">карта сайта</a> &middot; <a href="//megatfile.cc/forum/ads.php" rel="nofollow">реклама на сайте</a> &middot; <a href="//megatfile.cc/forum/abuse.php" rel="nofollow">информация для правообладателей</a> &middot; <a href="//vk.com/tfile.party" target="_blank" rel="nofollow">мы ВКонтакте</a> <br/>2006-2017 tfile.me </div> <script type="text/javascript" src="http://megatfile.cc/js/anap.176.js" charset="UTF-8" onload="window.jsOK=1" async></script><script> $(function() {document.write = (function () {for (var i = 0; i < arguments.length; i++) {$(document.body).append(arguments[i]);}});}); </script>      </body></html>

**Comment by garfield69** [comment]
the log  shows that the torrent details page that jackett is fetching from tfile for you does not contain the download link.
when i visit http://megatfile.cc/forum/viewtopic.php?t=1314778 with my browser I get a download button which contains a href for `download.php?id=1047402&ak=11794b6fc1&`
and this is the same when my jackett tfile indexer fetches when I click on the jackett dashboard search results download button for that torrent.

but you are getting a very different torrent details page for this torrent.
if you use your browser on the same machine that is running jackett, and access http://megatfile.cc/forum/viewtopic.php?t=1314778 do you get the download button ?
and does it work?

**Comment by rainbowjose** [comment]
Theres something strange with tfile depends on IP.
 Look:
https://i.imgur.com/mVyIBNr.png
https://i.imgur.com/zl3Kuxu.png(phishing link with torrent.exe file)

I dont understand why, but it seems we need provide ability to login into TFile from jackett

**Comment by rainbowjose** [comment]
but you cant register on TFile: https://i.imgur.com/RsGGzFy.png
What a shitty tracker.

**Comment by garfield69** [comment]
nothing that can be done from this end then. :-(

**Comment by rainbowjose** [comment]
Anyway, thank you!

**Comment by rainbowjose** [comment]
Also, theres a magnet link always available, maybe you can add this?

**Comment by garfield69** [comment]
Hell yes! I had not seen this. I'll take a second look and implement if its suitable.

**Comment by garfield69** [comment]
Jackett pre-release 0.12.1525
