### ISSUE TITLE
[torrentproject2] Exception (torrentproject2): Clearance failed after 30 attempt(s).: Clearance failed after 30 attempt(s). (Test)

### ISSUE THREAD

**Issue by nydave69** [Jackett/Jackett#6882]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by nydave69** [comment]
this with 3 other sites have this issue....  It takes a full minute for the test to fail..

**Comment by nydave69** [comment]
I believe that this issue is causing this with SickChill..
08:16:30 INFO::SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
08:19:20 INFO::SEARCHQUEUE-DAILY-SEARCH :: [Jackett] :: Request failed: HTTPConnectionPool(host='192.168.10.75', port=9117): Read timed out. (read timeout=30) (<type 'str'>)
08:19:26 INFO::SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found

It seems even when just doing an indexer test that it can take a complete minute before it completes if there are sites that then error out. sometimes even when there are no errors, just a slow indexer..

I can get around this be deleting the indexer that has errors or just takes toooooo long to respond.
Wish it could be disabled and also have those indexers that have problems disable themselves.

**Comment by garfield69** [comment]
if the site that jackett is indexing has enabled the cloudflare anti DDoS ReCaptcha challenge, then jackett cannot solve it and fails. this will take as long as it takes to fail and there is nothing we can do about it.
until the site lifts the DDoS protection you will just have to stop using it with jackett.
