### ISSUE TITLE
[REQ] TSC Tracker

### ISSUE THREAD

**Issue by mzlumin** [Jackett/Jackett#689]
Hi Guys,

can i please request the following german private Tracker: https://tsctracker.net
I am not sure about the mapping File though, i have collected the ID's anyway:

[https://gist.githubusercontent.com/mzlumin/ed32cd8de9b0f97498f6d11fa082263a/raw/450ccd4398c6d66f19125228d155cd6b2d7568d5/tsc-tracker](url)

Thanks and cheers,
zuli12

**Comment by kaso17** [comment]
I'll add it, already got access

**Comment by mzlumin** [comment]
Thanks alot kaso!

**Comment by garfield69** [comment]
https://tsctracker.org/ returning ERR_CONNECTION_TIMED_OUT
just me, or is the site broken, gone or moved to a new domain?

**Comment by garfield69** [comment]
back online.

**Comment by garfield69** [comment]
https://tsctracker.org/ ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
online
