### ISSUE TITLE
[torrentscsv] Parse error: Unexpected character encountered while parsing value: E. Path '', line 0, position 0. (Config)

### ISSUE THREAD

**Issue by txtsd** [Jackett/Jackett#6896]
Unable to add torrentscsv to indexers.

**Jackett version**:  0.12.1494.0

**Comment by garfield69** [comment]
looks like torrentscsv no longer supports keyword-less queries.
I'll amend the indexer to provide a default keyword so that the TEST can pass.

**Comment by txtsd** [comment]
Thanks!

**Comment by garfield69** [comment]
Jackett 0.12.1539
