### ISSUE TITLE
[The-Torrents] & [DataScene] Trackers have merged

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#6898]
Both The-Torrents & DataScene have merged and are now under http://datascene.net/

Signups are open:
http://datascene.net/signup.php

When implementing the tracker in Jackett, please include dead torrents in the search results! Thanks!

Jackett version: 0.12.1494.0
Mono version: N/A

-------------------------------

**Comment by garfield69** [comment]
the datascene indexer already exists, been available since well before 2017.
I will remove the-torrents.

**Comment by garfield69** [comment]
Jackett 0.12.1539
