### ISSUE TITLE
Danishbits and hounddawgs dont work

### ISSUE THREAD

**Issue by Ztrust** [Jackett/Jackett#69]
danishbit works in jackett but not in sonar I cant add it 
and hounddawgs dont work in either

**Comment by Kantraz** [comment]
What issues do you have with hounddawgs?

**Comment by Inrego** [comment]
I'm using DanishBits, and pretty sure it's working fine for me. I'll check

**Comment by Ztrust** [comment]
regarding houndawgs when i try to add it in jackett in says connection failed found no result while trying to browse this tracker 

and regarding DanishBits when trying to add it in sonarr it says it returned no results

when adding indexers through torznab i manually fill in the category for series that the indexers provide is this correct ? by default only 5030,5040 is there but i fill in the others too

**Comment by Inrego** [comment]
I usually just leave the defaults

**Comment by Ztrust** [comment]
inrego have you checked if danishbits work for you ?
and thanks

**Comment by Inrego** [comment]
Yes, it does. But sometimes my cookie expires, so I have to go to the config in Jackett and save again (then it gets a new cookie). I will fix this at some point.

**Comment by Kantraz** [comment]
Since Nxtgn has closed down, could you @Inrego, perhaps take a look at the hounddawgs indexer and get it going again, I myself can't really figure it out :)

**Comment by Inrego** [comment]
I'll probably check it out at some point

**Comment by Kantraz** [comment]
Great, I'll Try to see if I can solve it myself, but school is taking up a lot of time

**Comment by Inrego** [comment]
Yeah work is taking most of my time

**Comment by Ztrust** [comment]
@Inrego 
hope you can help.
When I try to add the danishbits tracker in sonar it says no results returned could you help me to figure out how i can fix this  ?
but in jackett it works like its supposed to.

**Comment by Kantraz** [comment]
I got hounddawgs working again, and pull request made

**Comment by nic0dk** [comment]
i have the same problem with danishbits.org, any change that you can have a look at it ? i can do the manual search in Jackett and even download the torrent, but in sonarr it show no result. thanks in advance

**Comment by flightlevel** [comment]
Thanks @Kantraz Now included in latest release

**Comment by Ztrust** [comment]
@nic0dk 
I fixed mine by removeing DB from jackett change password on db and then readding now everything works

**Comment by Ztrust** [comment]
Hi @Kantraz  
Houndawgs is still not working on my end updated Jackett to latest version did a new install to just to be sure but I am still getting configuration failed. 
Is there some setting on HD site I need to set I have tried both enabling and disabeling https but nothing seems to work changed password to on HD.
Any help would be appriciated
Ztrust

**Comment by Kantraz** [comment]
@Ztrust 
Are you running Jackett with "--IgnoreSslErrors true"?

**Comment by Ztrust** [comment]
@Kantraz
no I am not. I am running jackett as a service on windows so have no idea how to do that!
Outlogging ?
Sorry for the late reply but i dont get notied about new responses

**Comment by nic0dk** [comment]
@Ztrust that fixed my problem as well.. that was weird, now is Sonarr running like a charm, thanks for a great API proxy :+1:

**Comment by Kantraz** [comment]
@Ztrust 
No idea on how it works on windows :)
I'm running with the flag on my ubuntu machine :)

**Comment by Ztrust** [comment]
@Kantraz,
Ok thank you I will have to play around

**Comment by ramasjang** [comment]
Can you please add the CouchPotato Host to HoundDawgs? (They have made a TorrentPotato, CouchPotato torrent provider, https://hounddawgs.org/couchpotato.php)

Thanks :-)

**Comment by Kantraz** [comment]
@ramasjang 
I've chosen not to do anything more in this project :)
Focusing on school :)

**Comment by ramasjang** [comment]
OK thanks for your answer. Good luck with your school :)

**Comment by raspdealer** [comment]
@Ztrust if it's working, can you close this topic ?
