### ISSUE TITLE
[REC] eot-forum.net

### ISSUE THREAD

**Issue by mzlumin** [Jackett/Jackett#690]
Hi Guys,

can you please add this german private tracker?
[http://eot-forum.net/](url)

Categories can be found here:

[https://gist.githubusercontent.com/mzlumin/f1bb46114d5c33b149c3f2507a0a0d9f/raw/4b0ae91fbf342bb9f221c511a2c65b8321a340f8/eot](url)

Thanks and cheers,zuli12

**Comment by kaso17** [comment]
I'll add it if you send an invite to kaso1717 -at- gmail.com

**Comment by mzlumin** [comment]
Invite Link sent thanks a lot!

**Comment by kaso17** [comment]
got it, thank you
