### ISSUE TITLE
[beyondhd] imdb search not working

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#6902]
garfield69 BeyondHD should be added to the 2nd list. I kept trying to add it as a task item but couldn't do it properly for some reason.
***
beyondhd will have already had this support implemented ,at the same time as blutopia was, since its a unit3d engine and all those unit3d engine indexers are updated with the same capabilities.
***
garfield69 Blutopia works fine. BeyondHD does not. Searching with an IMDb ID returns a bunch of irrelevant results and no correct ones. I don't think it's searching in the correct/corresponding field.
***
Seems to work for me
![image](https://user-images.githubusercontent.com/6933240/72173486-8b6bc780-343c-11ea-9502-35d6560c040e.png)
***
> 
> 
> Seems to work for me
> ![image](https://user-images.githubusercontent.com/6933240/72173486-8b6bc780-343c-11ea-9502-35d6560c040e.png)

Strange! Here's what I'm getting!

![image](https://user-images.githubusercontent.com/23747425/72173763-49904200-33a6-11ea-8ac2-51134e6d152b.png)

Try searching for tt4154796 (Avengers: Endgame). Do you get accurate results with that?
***
yup.
![image](https://user-images.githubusercontent.com/6933240/72174199-01bcf980-343e-11ea-8a26-5bac2edb8924.png)
is your Jackett up to date?
***
> 
> 
> yup.
> ![image](https://user-images.githubusercontent.com/6933240/72174199-01bcf980-343e-11ea-8a26-5bac2edb8924.png)
> is your Jackett up to date?

It is up to date, yes. Can you figure out what's wrong from the log?

[log.txt](https://github.com/Jackett/Jackett/files/4046987/log.txt)

***
that log has nothing useful. what platform are you running on and which package of jackett have you installed?
***
> 
> 
> that log has nothing useful. what platform are you running on and which package of jackett have you installed?

Windows 10. Jackett 0.12.1525.0
***
I don't understand why your log is so useless in this case. 
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the imdb search with the beyond-hd indexer
4. find the *log.txt* `%ProgramData%\Jackett\log.txt`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.
the enhanced log should contain the html returned by the site, the url used to query beyondhd etc.
***
> 
> 
> I don't understand why your log is so useless in this case.
> Please provide the **full enhanced log** file.
> 
>     1. scroll down to the bottom of the Jackett Dashboard and _tick_ the _enhanced Logging_ checkbox
> 
>     2. scroll up a bit and _click_ on the _apply server settings_ button
> 
>     3. repeat the imdb search with the beyond-hd indexer
> 
>     4. find the _log.txt_ `%ProgramData%\Jackett\log.txt`)
> 
>     5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
> 
>     6. save, then drag-drop it here for us to take a look at.
> 
> 
> Thanks.
> the enhanced log should contain the html returned by the site, the url used to query beyondhd etc.

That was actually the enhanced log. I cleared it right before conducting the search so as to get rid of any irrelevant code.
***
makes no sense. mine has much more info in it when I enabled the enhanced log to compare with yours.

try this: use your tray jackett to stop the backgroup service and close the tray icon.
manually download https://github.com/Jackett/Jackett/releases/download/v0.12.1525/Jackett.Installer.Windows.exe and install as a service.
see if that make any difference.
***
> 
> 
> makes no sense. mine has much more info in it when I enabled the enhanced log to compare with yours.
> 
> try this: use your tray jackett to stop the backgroup service and close the tray icon.
> manually download https://github.com/Jackett/Jackett/releases/download/v0.12.1525/Jackett.Installer.Windows.exe and install as a service.
> see if that make any difference.

Did all that. Same thing. Log pretty much looks the same. I have a feeling this might have to do with the theme I selected on BHD's website, although for the life of me, I can't find how to change themes anymore. Dunno if that's even possible. Do you think that could be it? What does your theme look like?
***
there are no alternate themes on this site. 
![image](https://user-images.githubusercontent.com/6933240/72177951-b3f8bf00-3446-11ea-8658-363675dca8dd.png)
***
> 
> 
> there are no alternate themes on this site.
> ![image](https://user-images.githubusercontent.com/6933240/72177951-b3f8bf00-3446-11ea-8658-363675dca8dd.png)

Yeah I figured. The only thing I have differently from you is a 'No' where it says Show Suggested on List View' and I can't set it to Yes. It keeps returning to No for some reason. I can't figure this out. I tried removing & reconfiguring the tracker multiple times with different settings. Nothing worked!
***
Also, enhanced logs from other trackers & activities look pretty normal to me. I post them here all the time whenever I raise an issue and they've always been helpful. It's only for BHD that it looks weird & useless. It's gotta be related to the fact that I'm not getting the correct results when searching with the IMDb ID.
***
@garfield69 When configuring BHD in Jackett, how did you set things up there (for sorting and ordering the results)? Can you post a screenshot?
***

**Comment by garfield69** [comment]
garfield69 Also, in the Jackett 'Definitions' folder, I have:

beyond-hd.yml
beyond-hd-oneurl.yml

And in the 'Indexers' folder, I have:
beyondhd.json
beyond-hd.json
beyondhd.json.bak
beyond-hd.json.bak

Is this normal or do I have redundant files?

**Comment by garfield69** [comment]
perfectly normal

**Comment by RoloSoze** [comment]
> 
> 
> perfectly normal

Alright, what about this:
When configuring BHD in Jackett, how did you set things up there (for sorting and ordering the results)? Can you post a screenshot?

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/72180519-39cb3900-344c-11ea-97da-2541f1102b05.png)

**Comment by RoloSoze** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/6933240/72180519-39cb3900-344c-11ea-97da-2541f1102b05.png)

Tried that. Nothing.

**Comment by garfield69** [comment]
does searching for titles bring up specific results or do you get the same results that you might get for a keyword-less search?

**Comment by RoloSoze** [comment]
Searching for titles works perfectly fine.

**Comment by garfield69** [comment]
btw, about the .json config files in the indexer
beyondhd.json is the config for the oneurl login indexer
and beyond-hd is the config for the username/password indexer
at one point you must have used either.
apart from the login method, the code for generating requests and processing results is identical, so we can eliminate that as a cause. (I've tested both just to check).

**Comment by garfield69** [comment]
which indexer are you using?
if you are using the username/password indexer, then edit the config and enter the new captcha challenge and click ok.
your previous cookie may have expired.
try the imdb search for `tt4154796` again.
if it does not work, login with your browser, and click on https://beyond-hd.me/torrents?search=&description=&uploader=&imdb=4154796&tmdb=&sorting=created_at&direction=desc&qty=100
do you get relevant results?

**Comment by RoloSoze** [comment]
@garfield69 In that case I'm out of ideas :( 

It might be worth mentioning though that when searching with the IMDb ID, BHD seems to spit out results as per the way I configured it in Jackett without paying any attention to the search string, as in it's ignoring it altogether.

So for example, if I configured BHD to sort results by size descendingly, and then search for any IMDb ID, I'll get largest 100 torrents on the tracker. This is exactly what I would get if I hit search and left the search field blank (both in Jackett and the tracker).

**Comment by garfield69** [comment]
if you are using the oneurl, then login to the site and grab the oneurl again and edit your oneurl jackett config and paste it in and click ok.
you might be using an older oneurl key.
working now?

**Comment by RoloSoze** [comment]
> 
> 
> if you are using the oneurl, then login to the site and grab the oneurl again and edit your oneurl jackett config and paste it in and click ok.
> you might be using an older oneurl key.
> working now?

I was not using OneURL but I just gave it a shot. No use. Same issue.

**Comment by garfield69** [comment]
what about the url I posted earlier... do you get results on the site with it?
is the url that jackett generates when you do a imdb query.

**Comment by RoloSoze** [comment]
@garfield69 SOLVED! 

Here it what was wrong. On the torrent browsing page:
https://beyond-hd.me/torrents

I had certain search settings saved a while back. I saved it so that BHD's website displays 100 torrents per page instead of the default 25. Jackett didn't like that for some reason. As soon as I reset it to the default settings, searching with IMDb ID in Jackett started working fine. If I try to save it again as 100 torrent per page, the IMDb ID search in Jackett breaks.

The URL you sent earlier did not work initially but it does now! Than you very much for helping me debug this.

**Comment by garfield69** [comment]
\o/

**Comment by nlundquist** [comment]
I had this same issue thanks for documenting this so well.
