### ISSUE TITLE
bf.mine.nu broken

### ISSUE THREAD

**Issue by mzlumin** [Jackett/Jackett#691]
Hi Guys,

just noticed that the tracker: http://bf.mine.nu/
is no longer working with jackett, error i see is:

`Configuration failed: Found no results while trying to browse this tracker`

It seems that the Chaptcha needs to be entered first, afterwards User authentication is done...

cheers

**Comment by kaso17** [comment]
It's working fine for me.
You should see the catpcha in the configuration dialog.
Please post a log with tracing enabled (JacketConsole.exe -t)

**Comment by mzlumin** [comment]
hm thats bad, i am running on an Linux Box , may i execute debuglogging from the shell also?

**Comment by kaso17** [comment]
yes, stop the service and run jacket manually, log get's dumped to the stdout and log.txt

**Comment by mzlumin** [comment]
Hi @kaso17 

please find the Log below:
[https://gist.githubusercontent.com/mzlumin/e274f905d9e582222ad51d6a33a1fda7/raw/edbd97fa0a9ec104da3deafe37221b03f52687b5/Jackett.log](url)

**Comment by mzlumin** [comment]
Hey @kaso17 

i have seen the commit has been merged into the master branch, i have updated Jackett already, unfortunately i still see the following error:

`Found no results while trying to browse this tracker`

The complete Log can be found here:

[https://gist.githubusercontent.com/mzlumin/57d39f1cc8443336dbc599cf4eb7eb58/raw/fdd5592dbab56c11e954ecf4d0e85d584424e4ad/gistfile1.txt](url)

Is there anything i need to do else ? It adds the tracker correctly to Jackett, ( havent tried using it though ).

Thanks again, cheers

**Comment by kaso17** [comment]
The log file is from the previous version, make sure you're running v0.7.594

**Comment by mzlumin** [comment]
Just did the update again, works fine now thanks!
