### ISSUE TITLE
[Puntotorrent] Change name series to standard 

### ISSUE THREAD

**Issue by RicardoVelaC** [Jackett/Jackett#6910]
**Jackett version**: 0.12.1525.0
-------------------------------
The new episodes has been uploaded with this name format:

`[.​HDG] Manifest S2 [WEB-​DL HBO][m1080p][Dual DD5.​1][1.​15Gbs][S02/​C01] [Spanish]`

Add replace rule to change `S02/​C01` to standard `S02E01`

**Comment by RicardoVelaC** [comment]
@ngosang Can you help me with this?

**Comment by ngosang** [comment]
@RicardoVelaC I changed the "details link" to point to the tracker instead of the forum (you can find the forum link there) Is that ok?

**Comment by RicardoVelaC** [comment]
> @RicardoVelaC I changed the "details link" to point to the tracker instead of the forum (you can find the forum link there) Is that ok? #6935

Yes, thanks!!

**Comment by garfield69** [comment]
Jackett 0.12.1572
