### ISSUE TITLE
[REQ] YDYPT

### ISSUE THREAD

**Issue by f0ghqn1ih2** [Jackett/Jackett#6917]
Tracker's Name: | YDYPT
Genre: | XXX
Sign-up Link: | https://pt.hdbd.us/signup.php
Closing date: | Open only for a few hours
Additional information: | YDYPT is a Chinese Private Torrent Tracker for XXX Releases

**Comment by garfield69** [comment]
Closed registration already.

**Comment by garfield69** [comment]
@Curtis-L 
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer for YDYPT.

**Comment by garfield69** [comment]
@Curtis-L
I cannot find an existing request for a TJUPT indexer so if you raise a [req] ticket similar to this one for it and send me an invite I can work on that one too.

**Comment by Curtis-L** [comment]
> @Curtis-L
> If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer for YDYPT.

I have asked YDY staff to send you an invite, should be sent within a day, if you have any other problems, contact me.

Credits go to a lovely YDY staff, thanks!

**Comment by garfield69** [comment]
Registration and login successful. thank you.

**Comment by garfield69** [comment]
Jackett 0.16.488

**Comment by garfield69** [comment]
https://pt.hdbd.us/torrents.php?incldead=0&spstate=0&picktype=0&inclbookmarked=0&search=&search_area=0&search_mode=0
generating 
```
SQL Error
Table './pt@002ehdbd@002eus/snatched' is marked as crashed and should be repaired
in /home/wwwroot/pt.hdbd.us/include/functions.php, line 3642
```

**Comment by ilike2burnthing** [comment]
working again

**Comment by garfield69** [comment]
https://pt.hdbd.us/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://pt.hdbd.us/ cloudflare Connection timed out Error code 522

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://pt.hdbd.us/torrents.php?cat420=1&cat423=1&cat421=1&cat424=1 
SQLError Table './pt@002ehdbd@002eus/snatched' is marked as crashed and should be repaired in /home/wwwroot/pt.hdbd.us/include/functions.php, line 3642

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://pt.hdbd.us/  No Sponsors (domain expired, parked)

**Comment by garfield69** [comment]
v0.22.372
