### ISSUE TITLE
[BUG] Torrent Heaven broken

### ISSUE THREAD

**Issue by mzlumin** [Jackett/Jackett#692]
Hey Guys,

clicking on the following tracker leads to an array error and thus does not open the pop up for editing.

Error MEssage:

`Error: Value cannot be null. Parameter name: inArray`
![screen](https://cloud.githubusercontent.com/assets/20663710/20350853/bbe0fca8-ac10-11e6-8d73-db7207c4d67d.png)

**Comment by kaso17** [comment]
This seems to be a client side error, any chance you recently updated jackett? Please try clearing your browser cache.

**Comment by kaso17** [comment]
never mind my previous comment, I can reproduce it.
