### ISSUE TITLE
[newpct] Clearance failed after 30 attempt(s). (Config)

### ISSUE THREAD

**Issue by carotna** [Jackett/Jackett#6922]
NEWPCT tracker is dead. Can you please add dontorrent, descargas2020 and elitetorrent? Thank you

**Comment by ngosang** [comment]
* Newpct = descargas2020 in Jackett. there are some issues that we are working on, but it's working.
* Elitetorrent is already supported in Jackett
* dontorrent => will be added in the future

You can also try divxtotal and mejortorrent in Jackett

**Comment by josopu** [comment]
Same error is happenning now with divxtotal:

[divxtotal] Clearance failed after 30 attempt(s). (Config)

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/TroubleShooting#clearance-failed-after-30-attempts
