### ISSUE TITLE
[estrenosdtl] download links no longer works

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6924]
The added link protection for torrent download.

**Comment by garfield69** [comment]
I do not understand... seems to be working for me.
I click on the jackett dashboard download icon from a keyword-less search results on this indexer, and get presented with the relevant save .torrent file prompt.
![image](https://user-images.githubusercontent.com/6933240/72208555-c3d8d780-3508-11ea-88c8-fb768112747b.png)
so what is a link protection?

**Comment by ngosang** [comment]
The newest results are working for me too.

Search `fast and shaw` => Links to an old domain and can be fixed with replacement.
Search `fast 7 mejor` => Links to an old domain and I think it can't be fixed. There are a lot of old torrents with broken download links.

> so what is a link protection?

It's a external site that hides the download link until you see an advertisement or captcha. I was wrong, there isn't any in this site.

**Comment by garfield69** [comment]
I searched for `fast and shaw` and the dl link works for me
![image](https://user-images.githubusercontent.com/6933240/72213880-7f2a5c00-355b-11ea-8e39-362ae5a13a4b.png)
I confirm `fast 7 mejor` link does not work, but it is not our job to fix them.
