### ISSUE TITLE
Bit-Titan search results don't use search term

### ISSUE THREAD

**Issue by Lubastos** [Jackett/Jackett#6932]
Hello, 
I have some issues with this German tracker. If I search something in Radarr, Sonarr or in Jackett itself, my search results will not include my search term. It doesn't matter, if I provide a search term in Jackett or not, the search results are always the same. In my configuration the results are the one's with highest seeders.

Can someone please investigate this issue?

**Comment by garfield69** [comment]
they are trilaing a new beta engine, it clearly changes frequently while they add functions.
will proabably just nedd to alter the indexer for the newest requirements.
expect this to break often till its stable, so keep reporting between fixes it it breaks again.

**Comment by garfield69** [comment]
jackett pre-release 0.12.1561
