### ISSUE TITLE
Ideafilm new public tracker

### ISSUE THREAD

**Issue by SuberSeb** [Jackett/Jackett#6938]
http://ideafilm.top/ is a russian public torrent tracker with tv shows.

**Comment by garfield69** [comment]
this site does not return search results in a one-title-one-torrent layout.
searches returns a list of posters, after which you then have to access the title details page, on which there are one or more torrents and/or magnets
as such this site is not suitable for processing by the yaml Cardigann engine.
an indexer for this site will need to be coded in C#

**Comment by ilike2burnthing** [comment]
series of redirects
