### ISSUE TITLE
Jackett freezes intermittently

### ISSUE THREAD

**Issue by cadatoiva** [Jackett/Jackett#6939]
Provide a description of the feature request or bug, the more details the better.
After a while (1hour < t > 1week) my Jackett instance seems to freeze, similar to #1931 but for seemingly different reasons. I have Radarr and Sonarr using Jackett, no other apps connect to Jackett directly. Both show Jackett trackers as unavailable, and the web UI refuses to load. Using `service jackett stop` returns with Jackett isn't running, but the pid file still points to a valid jackett instance listening on the port. Using `service jackett start` then complains jackett is already running. Instead I have to use kill and then start the service. I didn't have enhanced logging on with this most recent freeze, but the log is saturated with:

```
2020-01-12 22:16:08.3707 Warn Heartbeat took longer than "00:00:01" at "01/13/2020 04:16:08 +00:00 +00:00". 
2020-01-12 22:16:08.3783 Warn Heartbeat took longer than "00:00:01" at "01/13/2020 04:16:08 +00:00 +00:00". 
2020-01-12 22:16:08.3707 Warn Heartbeat took longer than "00:00:01" at "01/13/2020 04:16:08 +00:00 +00:00". 
2020-01-12 22:16:08.3713 Warn Heartbeat took longer than "00:00:01" at "01/13/2020 04:16:08 +00:00 +00:00". 
2020-01-12 22:16:08.3783 Warn Heartbeat took longer than "00:00:01" at "01/13/2020 04:16:08 +00:00 +00:00". 
2020-01-12 22:16:08.3713 Warn Heartbeat took longer than "00:00:01" at "01/13/2020 04:16:08 +00:00 +00:00". 
2020-01-12 22:16:08.3783 Warn Heartbeat took longer than "00:00:01" at "01/13/2020 04:16:08 +00:00 +00:00". 
2020-01-12 22:16:08.3783 Warn Heartbeat took longer than "00:00:01" at "01/13/2020 04:16:08 +00:00 +00:00". 
2020-01-12 22:16:08.3795 Warn Heartbeat took longer than "00:00:01" at "01/13/2020 04:16:08 +00:00 +00:00". 
```

Radarr version info:
Version 0.2.0.1450
Mono Version 5.10.1.57

Sonarr version info:
Version 2.0.0.5338
Mono Version 5.10.1.57

(At the bottom of your Jackett Dashboard page) **Jackett version**: 
Jackett Version 0.12.1539.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:
$ pkg info mono
mono-5.10.1.57_2
$ uname -a
FreeBSD BSDNAS 11.3-RELEASE-p5 FreeBSD 11.3-RELEASE-p5 #0: Tue Nov 12 08:59:04 UTC 2019     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

Enhanced logs to follow next time the issue presents itself.

**Comment by cadatoiva** [comment]
There were a total of 444 Heartbeat messages with log time spanning from `2020-01-12 22:16:08.3433` to `2020-01-12 22:16:08.4524`

**Comment by garfield69** [comment]
past tickets hint at either a port/socket overload (especially sock5 users), or systems with very little memory running into trouble (although the recent switch to .net core and reduction on search result caching have alleviated this somewhat).

**Comment by cadatoiva** [comment]
Yeah, my OS still requires the mono version, so it might be related to that. I don't use any kind of proxy to access Jackett, and there's 32GB of RAM in the system. I'm still waiting on it to freeze again with enhanced logging enabled.

**Comment by srtviperjr** [comment]
Very similar issue I am having with the same OS and versions. Jackett process is still running but it's no longer listening on 9117. Sometimes a day sometimes just an hour before it stops responding.
Restarting the service doesn't matter, have to restart the whole jail for it to respond.

**Comment by cadatoiva** [comment]
Pretty sure this is not a Jackett bug per se, but a mono bug. https://github.com/Sonarr/Sonarr/issues/2802 and https://github.com/Sonarr/Sonarr/commit/7503ce62af1f1d4796d92ad70a0cbaa52bd95fbf reference the same symptoms.

**Comment by rrrevin** [comment]
Can you update your version of mono? 5.10.1.57 is quite old. Many many bug fixes since then.
I'm running 6.6.0.161 (on Armbian) with Sonarr without any issues. Granted, I'm not using the mono version of Jackett, but it might be a place to start.

**Comment by cadatoiva** [comment]
Not without manually installing. That's the packaged version for freebsd.

**Comment by srtviperjr** [comment]
> Pretty sure this is not a Jackett bug per se, but a mono bug. [Sonarr/Sonarr#2802](https://github.com/Sonarr/Sonarr/issues/2802) and [Sonarr/Sonarr@7503ce6](https://github.com/Sonarr/Sonarr/commit/7503ce62af1f1d4796d92ad70a0cbaa52bd95fbf) reference the same symptoms.

I’m running sonarr with the same version of Mono and never need to restart or touch it. Same build script.

**Comment by srtviperjr** [comment]
I tried running a manually built version of mono 6.4.0.198 and it didn’t seem to matter.
Weird thing - during my many rebuilds of the jail I changed the install method of mono from being supplied as a package to be added when creating the jail to **pkg install -y mono** and since then its been running without an issue... on the same version of Mono 5.10.1.57.... no idea what’s different, but there must be some dependency missing when installed during the jail creation.

**Comment by cadatoiva** [comment]
After updating my Mono version to 6.4.0.198 using [the FreeBSD update patch](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=238089), I've not run into this issue since.
