### ISSUE TITLE
[Blutopia] Error when trying to configure the indexer

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#6941]
An error occurred while updating this indexer:
Error: Swal.fire({ title: 'Error', icon: 'error', html: jQuery("#ERROR_COPY").html(), showCloseButton: true, })

Enhanced log attached
[log.txt](https://github.com/Jackett/Jackett/files/4054714/log.txt)

Jackett version: 0.12.1561.0
Mono version: N/A

**Comment by garfield69** [comment]
something changed with the site's login checking that Jackett cannot deliver with the standard FORM method.
But switching to cookie works so I've implemented this instead.

**Comment by garfield69** [comment]
Jackett 0.12.1572

**Comment by RoloSoze** [comment]
> 
> 
> Jackett 0.12.1572

Working fine now. Thank you, @garfield69!
