### ISSUE TITLE
problem restoring a backup

### ISSUE THREAD

**Issue by bingoxo** [Jackett/Jackett#6943]
I backed up the Jackett/Indexers folder from my previous server and when i pasted it in the new server and restarted Jackett only a few ones were showed , any idea why ?

I suspect only the ones with cookies login method are working but not the ones with login/password

os : debian
Jackett Version 0.12.1539.0

**Comment by garfield69** [comment]
From past tickets it appears that you cannot use the encrypted passwords from one machine to another. 
you will need to renter the credentials for any jackett configs that use the username/password login.

**Comment by bingoxo** [comment]
Can you add the possibility to make a backup encrypted with a password provided by the user ?

**Comment by garfield69** [comment]
you probably just needed to have backed up the DataProtection folder as well as the Indexers folder.
and the ServerConfig.json file.

**Comment by bingoxo** [comment]
yeah i backed up those as well just didn't know that i needed them all good now
