### ISSUE TITLE
[girotorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by gipasoft** [Jackett/Jackett#6946]
Log:
[log.txt](https://github.com/Jackett/Jackett/files/4058203/log.txt)

**Jackett version**:  0.12.1572.0

-------------------------------

**Comment by garfield69** [comment]
looks like they have dropped the download link on the primary results page.
i'll amend the indexer for the new layout.

**Comment by garfield69** [comment]
0.12.1574
