### ISSUE TITLE
[rutracker] Exception (rutracker): Пожалуйста, введите код подтверждения (символы, изображенные на картинке): Пожалуйста, введите код подтверждения (символы, изображенные на картинке) (Test)

### ISSUE THREAD

**Issue by gipasoft** [Jackett/Jackett#6947]
Log: 
[log.txt](https://github.com/Jackett/Jackett/files/4058221/log.txt)

**Jackett version**:  0.12.1572.0

-------------------------------

**Comment by garfield69** [comment]
the log shows that you need to edit the config and enter the verification code challenge.
