### ISSUE TITLE
[enhancement] add sort options to RARBG

### ISSUE THREAD

**Issue by GodsVictory** [Jackett/Jackett#6949]
I tested using general searches like "2160p", including both all indexers and individual indexers. Jacket is returning much fewer results than the individual indexers.

I then tried a more specific search: "spider-man far from home" on indexer 1337x

This returned a few results, but not the top seeded result. I then added "internal" to the end of the search and finally returned the highest seeded result.

Any ideas?

**Comment by cadatoiva** [comment]
From what I understand, there is a cap on the maximum number of results Jackett will gather for display. You might be running into that, and it's filtering out some results.

**Comment by ngosang** [comment]
> From what I understand, there is a cap on the maximum number of results Jackett will gather for display. 

Furthermore, by default Jackett get the newest results (sort by date). You can change that in the configuration of each tracker.

**Comment by garfield69** [comment]
and in addition to all the has been previously said, if the indexer does not currently support sorting, then raise its name and we can take a look to add it (although if it not in the config by now it most likely a) requires an invite because I don't have an a/c on the site, or b) the indexer is written in c# [which I leave to others to code support or c) the site does not provide sort options).

**Comment by GodsVictory** [comment]
WOW! Nice tip on the sorting for each indexer. The only config I checked was rarbg, which doesn't offer a sorting option. I was able to set it on all my other indexers though. Thanks!

**Comment by garfield69** [comment]
rarbg uses the sites' provided API, but the c# indexer coded for it does not make use of the available sorting options.
from  https://torrentapi.org/apidocs_v2.txt?app_id=Jackett the following:
```
Sorting :
sort parameter will sort the results by seeders,leechers,last. Default is last uploaded
mode=search&search_imdb=tt123456&sort=last&token=xxxx
```

ping to any C# dev volunteer to implement the sort option for this indexer.

**Comment by garfield69** [comment]
jackett 0.12.1623
