### ISSUE TITLE
Remove TS Tracker

### ISSUE THREAD

**Issue by mzlumin** [Jackett/Jackett#695]
Hey @kaso17 ,

the following Tracker can be removed or disabled in the UI, as they closed their doors already again:
https://torrent-syndikat.org/

cheers

**Comment by kaso17** [comment]
For me it's still working fine. Have you been a member?

**Comment by mzlumin** [comment]
yes i have been a member there. sure ir works ? the site states to not be actice?
you ger the website and stuff ? Mine was just a cached version i was seeing  

strange though

**Comment by kaso17** [comment]
You've to click on the top right "Sie können die Domain torrent-syndikat.org kaufen!" link.

**Comment by d2dyno** [comment]
For me, I'm directed to a purchase domain page.
![torrent syndikat org this site is for sale information about torrent syndicate](https://cloud.githubusercontent.com/assets/2421939/20407010/93c7f794-acdd-11e6-9d25-72deec6a9ced.png)

**Comment by kaso17** [comment]
The domain for sale is just a "fake". Click on the top right link to get to the login page.

**Comment by d2dyno** [comment]
In that case, I do not know (I'm not a member there).

**Comment by mzlumin** [comment]
totall right kasko  i am sorry
