### ISSUE TITLE
[PassThePopcorn] Display 'Freeleech' 

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#6951]
Some torrents on PassThePopcorn (PTP) receive 'Freeleech' status for a defined period of time then it expires. The word 'Freeleech' is written next to the torrent in question on PTP's website, but Jackett currently does not show that. It would be great if it did.

Jackett version: 0.12.1572.0
Mono version: N/A

**Comment by ngosang** [comment]
I can see in the code there are some torrents with freeleech, but maybe the code is outdated.
https://github.com/Jackett/Jackett/blob/b70f38b8ff487b6aafe65c0b8475f3e6d5637114/src/Jackett.Common/Indexers/PassThePopcorn.cs#L244
I don't have account. Do you have an invitation?

**Comment by RoloSoze** [comment]
> 
> 
> I can see in the code there are some torrents with freeleech, but maybe the code is outdated.
> 
> https://github.com/Jackett/Jackett/blob/b70f38b8ff487b6aafe65c0b8475f3e6d5637114/src/Jackett.Common/Indexers/PassThePopcorn.cs#L244
> 
> I don't have account. Do you have an invitation?

Sorry I don't have an invite.

**Comment by ngosang** [comment]
@RoloSoze if you upload the HTML I can investigate it.

**Comment by cadatoiva** [comment]
I have an account with this one and will be adding it shortly

**Comment by RoloSoze** [comment]
> 
> 
> I have an account with this one and will be adding it shortly

@cadatoiva Any luck with this issue?

**Comment by cadatoiva** [comment]
Haven't had the time, tbh. It's on the list.

**Comment by cadatoiva** [comment]
Just got around to looking for it, and it already tried to do this, but it failed because the result of `(string)torrent["FreeleechType"]` is either `null` or `(string)"Freeleech"` which fails to translate in `bool.TryParse`

**Comment by garfield69** [comment]
Jackett 0.13.483

**Comment by RoloSoze** [comment]
@cadatoiva It seems that this issue back again. For example, all of the School of Rock (tt0332379) torrents are currently Freeleeh (for the next 10 days), but the 'Freeleech' tag isn't show in Jackett. I also tested a few other random titles that are currently Freeleech, same issue.

**Comment by cadatoiva** [comment]
Found the problem, we still filter by free and check for it, but one of the refactors removed the new code that checked added the free tag to the results list.

**Comment by garfield69** [comment]
Jackett v0.14.541

**Comment by RoloSoze** [comment]
All good now. Thanks!
