### ISSUE TITLE
AudioBook Bay is pointlessly requiring login

### ISSUE THREAD

**Issue by NewsGuyTor** [Jackett/Jackett#6958]
I noticed the AudioBook Bay plugin is needlessly requiring an account to be set up. 

As the infohash is displayed publicly, so the login requirement should be removed and a magnet link should be created from the infohash instead.

**Comment by garfield69** [comment]
the Cardigann processor could not previously process the infohash from the torrent details page until 9413006524a7f4b731ea9e5c1103a4244bbfd4fd was published just 5 days ago.
Now however, this is indeed possible, so I can implement your request. I'll post again when published.

**Comment by garfield69** [comment]
jackett 0.12.1582
