### ISSUE TITLE
Customize result titles hdcity

### ISSUE THREAD

**Issue by vinanrra** [Jackett/Jackett#6964]
Is there any way to rename in hdcity.yml:

> El visitante (The Outsider) 1x01   Fish in a Barrel

To

> The Outsider (2020) 1x01   Fish in a Barrel

Because i have done this with **replace at title** (check comment below) and it works, but sonarr didnt catch the result even when searching that.
I have checked logs and it seems fine but it doesn't catch the result.

I would like to be able to customize results to match sonarr and dont wait for them to aprove title changes.

**Comment by vinanrra** [comment]
I have tried:
![imagen](https://user-images.githubusercontent.com/4247187/72536714-0ee14a80-387b-11ea-96e8-e997db43ac5a.png)

```
          - name: replace
            args: ["El visitante (The Outsider)","Outsider 2020"]
```

Manual search at Jackett:

![imagen](https://user-images.githubusercontent.com/4247187/72536745-228cb100-387b-11ea-82a3-8ea6f30c5e84.png)

Sonarr search:

![imagen](https://user-images.githubusercontent.com/4247187/72536778-2f110980-387b-11ea-8113-ac741b129fcc.png)


01-16 16:12:19 Info Found 0 releases from HDCity for: Outsider 2020 S01E01

**Comment by garfield69** [comment]
I do not have an a/c on this site so cannot help with this one. (the site filters out non Spanish IPs).

@TuGeek  has recently been maintaining this indexer so perhaps if he is available, he may have some insight into why your mods are not working as expected.

**Comment by vinanrra** [comment]
> 
> 
> I do not have an a/c on this site so cannot help with this one. (the site filters out non Spanish IPs).
> 
> @TuGeek has recently been maintaining this indexer so perhaps if he is available, he may have some insight into why your mods are not working as expected.

I have found how customize search, you need to add at `keywordsfilters:`

      - name: replace
        args: ["THE QUERY","THE SEARCH"]

Example:

```
      - name: replace
        args: ["Outsider 2020","El visitante (The Outsider)"]
```

If u search:

> Outsider 2020

Will be "translated to"

> El visitante (The Outsider)
