### ISSUE TITLE
[girotorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by gipasoft** [Jackett/Jackett#6966]
The index page seems changed again :(

Log: 
[log.txt](https://github.com/Jackett/Jackett/files/4072197/log.txt)

**Jackett version**:  0.12.1574.0

-------------------------------

**Comment by gipasoft** [comment]
This is not a duplicate, I have already updated Jackett to 0.12.1574.0 version, for some days all ok but now is already ko

**Comment by garfield69** [comment]
jackett 0.12.1582
