### ISSUE TITLE
[REQ] OMGWTFNZBS

### ISSUE THREAD

**Issue by stkthree4879** [Jackett/Jackett#6967]
[edit] 
OMGWTFNZBS Private https://omgwtfnzbs.me/login

**Comment by stkthree4879** [comment]
I think this should be what you need

Site Name	RSS and Legacy	Newznab	NZB Header
Apps: All	1,2,4,5,6	4000	*
Apps: Linux	4	4080	Apps > Linux
Apps: MAC	2	4030	Apps > MAC
Apps: Other	6	4090	Apps > Other
Apps: PC	1	4010	Apps > PC
Apps: Phone	5	4040	Apps > Phone
Audiobook	29	3030	Audiobook
Games: All	12,13,14	8000	*
Games: MAC	13	8020	Games > MAC
Games: Other	14	8030	Games > Other
Games: PC	12	8010	Games > PC
Movies: All	15,16,31,35,17,18	2000	*
Movies: DVD	17	2070	Movies > DVD
Movies: Full BR	35	2050	Movies > Full BR
Movies: HD	16	2040	Movies > HD
Movies: Other	18	2020	Movies > Other
Movies: SD	15	2030	Movies > SD
Movies: UHD	31	2045	Movies > UHD
Music: All	7,22,8,3,29	3000	*
Music: FLAC	22	3040	Music > FLAC
Music: MP3	7	3010	Music > MP3
Music: MVID	8	3020	Music > MVID
Music: Other	3	3050	Music > Other
Other: All	9,11	7000	*
Other: E-Books	9	7020	Other > E-Books
Other: Other	11	7010	Other > Other
TV: All	19,20,30,21	5000	*
TV: HD	20	5040	TV > HD
TV: Other	21	5060	TV > Other
TV: SD	19	5030	TV > SD
TV: UHD	30	5045	TV > UHD
XXX: All	25,24,32,26,27,22,34,36,28,23	6000	*
XXX: DVD	28	6010	XXX > DVD
XXX: Gay/Trans	36	6080	XXX > Gay/Trans
XXX: HD-CLIPS	24	6050	XXX > HD-CLIPS
XXX: IMAGESETS	34	6060	XXX > IMAGESETS
XXX: MOVIES-HD	27	6040	XXX > MOVIES-HD
XXX: MOVIES-SD	26	6030	XXX > MOVIES-SD
XXX: MOVIES-UHD	33	6045	XXX > MOVIES-UHD
XXX: Packs/Other	23	6070	XXX > Packs/Other
XXX: SD-CLIPS	25	6020	XXX > SD-CLIPS
XXX: UHD-CLIPS	32	6055	XXX > UHD-CLIPS

Items marked with * return the actual sub category (for example TV > SD)

**Comment by garfield69** [comment]
what I really need is the full domain path so I can access the site ;-)
thanks.

**Comment by stkthree4879** [comment]
Sorry...also send me email so I can send an invite.  Thanks!

https://omgwtfnzbs.me/login

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by stkthree4879** [comment]
just login as me for now

stkthree
Welcomejo1!

invite window is closed right now... there is a tab for API info and it gives all the relevant info

**Comment by garfield69** [comment]
ok lets get some facts.
does the site allow us to scrape their html for search and results, or do they insist on us using their API?
if html scraping is allowed I can write the indexer using the jackett Cargigan yaml processor.
if the API is required, then the indexer will need to written in C#, so a c# dev volunterr will be required.

**Comment by stkthree4879** [comment]
Ok can you login as me and check the api tab it can be done both ways but it should have all the answers

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by garfield69** [comment]
The site's FAQ strictly forbids the use of scraping. So coding the indexer for the Cardigann yaml processor is not an option.
This leaves the site's API which supports both Newznab and JSON
AnimeTosho.cs is an existing example of a Newznab indexer.
And there are many indexer written to handle JSON style queries.
This indexer will need to be written in C#.

**Comment by dimqua** [comment]
Does this indexer have torrents at all? If not, what's the purpose to add it?

**Comment by garfield69** [comment]
with the introduction of JSON support from a yaml indexer it may be now possible to access this site's API without resorting to C#.
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.

**Comment by sarjil01** [comment]
Can i get an invite ?

**Comment by ilike2burnthing** [comment]
This isn't an invite forum, don't use it as one.

**Comment by bakerboy448** [comment]
why should a usenet site be added to jackett?

**Comment by garfield69** [comment]
closing as not suitable.
