### ISSUE TITLE
[REQ] Add semi-private french tracker ShareWood

### ISSUE THREAD

**Issue by cadavor** [Jackett/Jackett#6972]
Semi-Private French Tracker
https://www.sharewood.tv

No invitation needed, just register and validate your account with link in received mail

**Comment by garfield69** [comment]
the sharewood indexer has been available on Jackett since March 2019.
Can you not find it in the Jackett Dashboard's add-indexer page?
Duplicate of #4898

**Comment by cadavor** [comment]
My bad, sorry for inconvenience
