### ISSUE TITLE
WIndows - password not accepted any more

### ISSUE THREAD

**Issue by wellloaded** [Jackett/Jackett#6973]
Using today's build as far as I can tell - v0.12.1590

Long story short I can't use Jackett any more as the usual URL on port 9117 is now asking for a password. I have a saved one in my browser but Jackett doesn't like it. I totally did not touch the password settings of Jackett since the initial installation and it was working yesterday fro sure.

I browsed the C:\ProgramData\Jackett folder and look into the .json files but can't find any reference to passwords.

Any help on how to get this back working please?

Thanks!

**Comment by garfield69** [comment]
shutdown your Jackett service.
then in `C:\ProgramData\Jackett` edit `ServerConfig.json` with a plain text editor
and set/change `  "AdminPassword": null,`
restart and you should be good to go.
