### ISSUE TITLE
[yggtorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Alphachoups** [Jackett/Jackett#6978]
Hi,

I can't edit the tracker indexer for YGGTORRENT into Jackett. 
I'm able to edit permanently the "search and download URL" but when I edit/change the "Site Link" it revert back to the default URL (https://yggtorrent.ws/) after I Click on "Okay". 
In the edit Panel it validate the settings but when the defualt page appear, when I click on the test button, it failed. I go back in the settings of the tracker and (only) the site Link have been automatically changed...
(Didn't find any already case on this problem).

(At the bottom of your Jackett Dashboard page) **Jackett version**:  0.12.1590.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**: 5.18.0.240-12
-------------------------------

**Comment by Alphachoups** [comment]
Not a dublicated - Other post is not over an edit problem

**Comment by garfield69** [comment]
read carefully and follow  https://github.com/Jackett/Jackett/issues/6473#issuecomment-560978023
the site link and search url in the comment-link I provide above  are the correct values to access yggtorrent.
if you are trying to alter the site link to an address that has previously been determined as invalid, the indexer will switch back to the default value.
previous obsolete links are:
```yaml
  legacylinks:
    - https://yggtorrent.com/
    - https://ww1.yggtorrent.com/
    - https://yggtorrent.is/
    - https://www.yggtorrent.is/
    - https://ww1.yggtorrent.is/
    - https://ww2.yggtorrent.is/
    - https://ww3.yggtorrent.is/
    - https://ww4.yggtorrent.is/
    - https://yggtorrent.to/
    - https://www3.yggtorrent.to/
    - https://www6.yggtorrent.to/
    - https://www8.yggtorrent.to/
    - https://www9.yggtorrent.to/
    - https://ygg.to/
    - https://www.ygg.to/
    - https://ww3.yggtorrent.gg/
    - http://www2.yggtorrent.gg/
    - https://www.yggtorrent.gg/
    - https://www.yggtorrent.ch/
    - https://www.yggtorrent.pe/
    - https://www3.yggtorrent.pe/
    - https://www5.yggtorrent.pe/
```
