### ISSUE TITLE
Cannot add indexer BlueTigers

### ISSUE THREAD

**Issue by nabot93** [Jackett/Jackett#699]
I am trying to add BlueTigers to my Jackett. When I set the username and password and then click on Okay, I get an error: "Configuration failed: Error while trying to login". Howerver, I am sure of my password, it works on BlueTigers...

Thank you for your help,
Tell me if I can do some tests to help you investigate.

**Comment by maxcore** [comment]
Site was shutdown ...

**Comment by nabot93** [comment]
I did not know... This is too bad.
