### ISSUE TITLE
[filelist] Exception (filelist): :  (Test)

### ISSUE THREAD

**Issue by nirolfp3** [Jackett/Jackett#6990]
Tracker apparently changed it's API:
------------------------------
FileList offers a JSON/XML API that will allow you to get information from our website.
The API is available at the following URL: https://filelist.ro/api.php

Quote:
General Info

All calls to the API have to be sent as a GET request;
All the arguments listed below are set as parameters in the call URL;
Every API call requires authentication with Username and Passkey (can be found here);
Every user is limited to 150 API calls per hour;
Red highlighted parameters are required!

Quote:
Authentication

Parameters:
   username
   passkey
Example: https://filelist.ro/api.php?username=ToXiC&passkey=1234567890

OR you can set the "Authorization" header:
Value:
  Basic username:passkey - "username:passkey" must be encoded in base64
Example: taking "ToXiC:1234567890" as "username:passkey", you must set the value as: Basic VG9YaUM6MTIzNDU2Nzg5MA==

Quote:
Parameters / Endpoints

Parameters:
   action
Valid values: search-torrents, latest-torrents
Example: https://filelist.ro/api.php?username=ToXiC&passkey=1234567890&action=search-torrents

Additional parameters for action=search-torrents
   type                Valid values: imdb, name
   query              If you choose imdb as type, it is accepted in two forms: tt4719744 or 4719744;
   name              Accepted as an optional parameter if type=imdb. Also searches in the name field.
   category          Valid values: IDs from categories, multiple values ​​separated by a comma are accepted.
   moderated       Valid values: 0,1
   internal            Valid values: 0,1
   freeleech          Valid values: 0,1
   output              Valid values: json, rss. Default is JSON.

Additional parameters for action=latest-torrents
   limit          Maximum number of torrents displayed in the request. Can be 1-100. Default value: 100
   imdb         Accepted as: tt4719744 or 4719744
   category    Valid values: IDs from categories, multiple values ​​separated by a comma are accepted.
   output       Valid values: json, rss. Default is JSON.

Example:
   https://filelist.ro/api.php?username=ToXiC&passkey=1234567890&action=search-torrents&type=name&query=Gemini
   https://filelist.ro/api.php?username=ToXiC&passkey=1234567890&action=search-torrents&type=imdb&query=tt4719744&category=4,19
   https://filelist.ro/api.php?username=ToXiC&passkey=1234567890&action=latest-torrents
   https://filelist.ro/api.php?username=ToXiC&passkey=1234567890&action=latest-torrents&output=rss

Categories
If you need the category IDs (they can also be found on the browse page), here they are:
Spoiler (ascunde)

+----+------------------+
| id | name             |
+----+------------------+
|  1 | Filme SD         |
|  2 | Filme DVD        |
|  3 | Filme DVD-RO     |
|  4 | Filme HD         |
|  5 | FLAC             |
|  6 | Filme 4K         |
|  7 | XXX              |
|  8 | Programe         |
|  9 | Jocuri PC        |
| 10 | Jocuri Console   |
| 11 | Audio            |
| 12 | Videoclip        |
| 13 | Sport            |
| 14 | TV               |
| 15 | Desene           |
| 16 | Docs             |
| 17 | Linux            |
| 18 | Diverse          |
| 19 | Filme HD-RO      |
| 20 | Filme Blu-Ray    |
| 21 | Seriale HD       |
| 22 | Mobile           |
| 23 | Seriale SD       |
| 24 | Anime            |
| 25 | Filme 3D         |
| 26 | Filme 4K Blu-Ray |
| 27 | Seriale 4K       |
+----+------------------+

Quote:
Error codes

400 - Invalid search/filter
401 - Username and passkey cannot be empty.
403 - Too many failed authentications
403 - Invalid passkey/username
404 - No results
429 - Rate limit reached
503 - Service unavaible

Last edited by ToXiC at 14/01/2020 - 09:04:11 GMT
[log.txt](https://github.com/Jackett/Jackett/files/4088536/log.txt)

**Comment by Emtrixx** [comment]
Where can you find the passkey?

**Comment by garfield69** [comment]
@Emtrixx 
Note this is not your password.
- Login to the FileList Website
- Click on the **Profile** link
- Scroll down to the **Reset Passkey** section
- Copy the **passkey**.
- Also be aware of not leaving a trailing blank at the end of the passkey after pasting it here.

**Comment by garfield69** [comment]
I don't have access to the site so I cannot see for myself.
But could the note in the indexer to fetch the passkey be improved, is it out of date?

**Comment by Emtrixx** [comment]
Sry to be honest I use prowlarr. I was just too stupid to see the profile link on filelist.io
