### ISSUE TITLE
[REQ] shanaproject.com

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [Jackett/Jackett#6995]
just saw this in pyMedusa, https://www.shanaproject.com should be added to jackett as well (if possible)

**Comment by garfield69** [comment]
this site does not conform to the one-title-one-torrent presentation in its search results, which means it is not suitable for processing by the Cardigann yaml processor.
This indexer will need to be written in C#.

**Comment by garfield69** [comment]
seems to have changes layout. the search page presents torrent titles with a a single download .torrent link.

**Comment by garfield69** [comment]
Wonder if I should try to add SxxExx stripping on incoming torznab queries so that the indexer could be used with Sonarr, or is that just not worth the effort?

**Comment by ilike2burnthing** [comment]
We do it on a few other indexers, so it's worth a shot I suppose.

**Comment by garfield69** [comment]
v0.20.1038

**Comment by ilike2burnthing** [comment]
https://www.shanaproject.com/ - Gateway time-out - Error code 504

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6995#issuecomment-1242885623

**Comment by ilike2burnthing** [comment]
back up but slow
