### ISSUE TITLE
[REQ] [FileList] Add API functionality

### ISSUE THREAD

**Issue by ophishil** [Jackett/Jackett#7004]
FileList.ro now has an API. At the moment authentication in Jackett is done with username/password, which may break again in future site updates and is also something I'd like to avoid using. 
The API could be used as an alternative. Authentication can be done with username/passkey in the query or encoded as Base64 in the header.

I will leave the API description bellow. Can also offer invite if needed.

Thank you!

------------------------

> FileList offers a JSON/XML API that will allow you to get information from our website.
The API is available at the following URL: https://filelist.ro/api.php

**General Info**
- All calls to the API have to be sent as a GET request;
- All the arguments listed below are set as parameters in the call URL;
- Every API call requires authentication with Username and Passkey (can be found [here](https://filelist.ro/my.php));
- Every user is limited to 150 API calls per hour;
- _Italic_ parameters are required!

**Authentication**
- Parameters: 
    _username_
    _passkey_
- Example: https://filelist.ro/api.php?username=ToXiC&passkey=1234567890

**OR** you can set the "Authorization" header:
- Value:
   _Basic **username:passkey**_ - "**username:passkey**" must be encoded in base64
- Example: taking "**ToXiC:1234567890**" as "**username:passkey**", you must set the value as: Basic **VG9YaUM6MTIzNDU2Nzg5MA==**

**Parameters / Endpoints**
- Parameters:
    _action_ 
- Valid values: search-torrents, latest-torrents
- Example: https://filelist.ro/api.php?username=ToXiC&passkey=1234567890&action=search-torrents

- Additional parameters for **action=search-torrents**
    _type_                Valid values: imdb, name
    _query_              If you choose imdb as type, it is accepted in two forms: tt4719744 or 4719744;
    name              Accepted as an optional parameter if type=imdb. Also searches in the name field.
    category          Valid values: IDs from categories, multiple values ​​separated by a comma are accepted.
    moderated       Valid values: 0,1
    internal            Valid values: 0,1
    freeleech          Valid values: 0,1
    output              Valid values: json, rss. Default is JSON.

- Additional parameters for **action=latest-torrents**
    limit          Maximum number of torrents displayed in the request. Can be 1-100. Default value: 100
    imdb         Accepted as: tt4719744 or 4719744
    category    Valid values: IDs from categories, multiple values ​​separated by a comma are accepted.
    output       Valid values: json, rss. Default is JSON.

- Example: 
    https://filelist.ro/api.php?username=ToXiC&passkey=1234567890&action=search-torrents&type=name&query=Gemini
    https://filelist.ro/api.php?username=ToXiC&passkey=1234567890&action=search-torrents&type=imdb&query=tt4719744&category=4,19
    https://filelist.ro/api.php?username=ToXiC&passkey=1234567890&action=latest-torrents
    https://filelist.ro/api.php?username=ToXiC&passkey=1234567890&action=latest-torrents&output=rss

- Categories 
If you need the category IDs (they can also be found on the browse page), here they are:
```
+----+------------------+
| id | name             |
+----+------------------+
|  1 | Filme SD         |
|  2 | Filme DVD        |
|  3 | Filme DVD-RO     |
|  4 | Filme HD         |
|  5 | FLAC             |
|  6 | Filme 4K         |
|  7 | XXX              |
|  8 | Programe         |
|  9 | Jocuri PC        |
| 10 | Jocuri Console   |
| 11 | Audio            |
| 12 | Videoclip        |
| 13 | Sport            |
| 14 | TV               |
| 15 | Desene           |
| 16 | Docs             |
| 17 | Linux            |
| 18 | Diverse          |
| 19 | Filme HD-RO      |
| 20 | Filme Blu-Ray    |
| 21 | Seriale HD       |
| 22 | Mobile           |
| 23 | Seriale SD       |
| 24 | Anime            |
| 25 | Filme 3D         |
| 26 | Filme 4K Blu-Ray |
| 27 | Seriale 4K       |
+----+------------------+
```

**Error codes**
- **400** - Invalid search/filter
- **401** - Username and passkey cannot be empty.
- **403** - Too many failed authentications
- **403** - Invalid passkey/username
- **404** - No results
- **429** - Rate limit reached
- **503** - Service unavaible

**Comment by ngosang** [comment]
@IIIspaceIII could you help? We don't have an active maintainer for this tracker.

**Comment by RoloSoze** [comment]
@ngosang Maybe you or @cadatoiva could get the invite from @ophishil to work on this? FileList is a great tracker.

**Comment by IIIspaceIII** [comment]
Some points from my side:
Is the limit of 150 req/hour enough for an average jackett user?
We could could use the api with a fallback to the current implementation if the limit is reached. 
What do you think about this?

**Comment by RoloSoze** [comment]
Seeing how #5190 and #7924 will not go through since the priority is to work on the API integration, is anyone willing to implement the FileList API? I can contact the FL staff & get an invite if there is a volunteer. Thanks!

**Comment by ngosang** [comment]
@ophishil I will do the work, send me an invite.
ngosang -at- hotmail.es

**Comment by RoloSoze** [comment]
> 
> 
> @ophishil I will do the work, send me an invite.
> ngosang -at- hotmail.es

@ngosang If you don't get an invite for any reason, let me know.

**Comment by IIIspaceIII** [comment]
I could also work on the implementation. Don't need an account.

**Comment by garfield69** [comment]
Jackett 0.16.54

**Comment by ilike2burnthing** [comment]
Site shutting down in January 2024:

![filelist](https://github.com/Jackett/Jackett/assets/59480337/74671fab-6ae1-4d58-a9ba-d7b3bae345af)

**Comment by ilike2burnthing** [comment]
FL will live on:

![fl](https://github.com/Jackett/Jackett/assets/59480337/bf4c8bfa-00eb-45da-8a25-dfbf1604ee01)
