### ISSUE TITLE
[Request] indexer Microbit.eu

### ISSUE THREAD

**Issue by pgk831** [Jackett/Jackett#7007]
http://microbit.eu/signup.php   now opened the free reg!!! 
MicroBit (uBit) is a HUNGARIAN Private Torrent Tracker for MOVIES / TV / GENERAL

**Comment by garfield69** [comment]
jackett 0.12.1732

**Comment by garfield69** [comment]
http://microbit.eu/ returning DNS lookup failed

**Comment by garfield69** [comment]
is the site broken, moved to a new domain or gone?

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://microbit.eu/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.20.1825
