### ISSUE TITLE
[req] LeagueHD CHINESE Private https://leaguehd.com/

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#7016]
LeagueHD is a CHINESE Private Torrent Tracker for HD MOVIES / TV

**Comment by vans2456** [comment]
hello someone to invite me to this great tracker I have many films to share

**Comment by garfield69** [comment]
@vans2456  this is not a forum for requesting invites.
this is a support site for the jackett app.
please look elsewhere for invite requests.
