### ISSUE TITLE
[req] HDDisk CHINESE Private https://hddisk.life/

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#7018]
HDDisk (HDD) is a CHINESE Private Torrent Tracker for HD MOVIES / TV

**Comment by garfield69** [comment]
https://hddisk.life/ returning
```
服务器负载过高，正在重试，请稍后...
```
google translation
```
Server load is too high, retrying, please wait...
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://hddisk.life/ - ERR_CONNECTION_CLOSED

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://hddisk.life/ returning 
```
The server load is very high at the moment. Retrying, please wait...
```

**Comment by ilike2burnthing** [comment]
Login page is back up. Are you able to actually log in?

**Comment by garfield69** [comment]
The login page is operating but I've lost my account on the site so I cant test to completion anymore.

**Comment by garfield69** [comment]
Hah!
registration is open ATM so I recreated the account and I am back in.
Tested the indexer, working. :-)

**Comment by ilike2burnthing** [comment]
> https://hddisk.life/ returning
> 
> ```
> The server load is very high at the moment. Retrying, please wait...
> ```

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://hddisk.life/ returning
> 
> ```
> The server load is very high at the moment. Retrying, please wait...
> ```

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://hddisk.life/ - working, but:
```
2020.12.09 - This site will cease operations on January 10th and be merged with HDATMOS
Important Notice: This site will be merged with HDATMOS, please members as soon as possible to the https://hdatmos.club registered account.
Please submit this site data screenshot and new station registration ID to QQ group:868577058 private letter group owner for data migration merge processing, this site will cease operation on January 10. HDDisk Thank you for your continued support, so please understand that you are in unnecessary trouble.
```
Remove in a month.

**Comment by ilike2burnthing** [comment]
> https://hddisk.life/ returning
> ```
> The server load is very high at the moment. Retrying, please wait...
> ```
