### ISSUE TITLE
[mejortorrent] Clearance failed after 30 attempt(s). (Config)

### ISSUE THREAD

**Issue by sirinath** [Jackett/Jackett#7019]
When adding the index it gives an error. This could be due to the fact that http://www.mejortorrentt.org/ site is behind captcha protection.

Jackett Version 0.12.1632.0

**Comment by garfield69** [comment]
that is correct.
mejortorrents have enabled cloudflare's full anti-DDoS ReCaptcha challenge, which jackett cannot solve.
there is nothing that can be done until the site removes this protection.
