### ISSUE TITLE
[HDBits] Please add username/passkey login

### ISSUE THREAD

**Issue by eckozen84** [Jackett/Jackett#7020]
Currently, Sonarr and Radarr (at least in v3) allow the use of username/passkey login (passkey is referred to as API key in Sonarr/Radarr). 

This method works with 2FA whereas the current Jackett implementation of username/password login does not.

**Comment by garfield69** [comment]
Look for **HDBits (API)** on the add-indexer page of your Jackett dashboard.

**Comment by eckozen84** [comment]
Crap, how did I miss that! Sorry about that. Thanks.
