### ISSUE TITLE
[Request] RARBG Proxy Support

### ISSUE THREAD

**Issue by dhruvbhutani** [Jackett/Jackett#7029]
As the title suggests, RARBG is blocked in several countries. It would be really helpful to have support for proxyrarbg.org or some of the other mirror sites available.

**Comment by garfield69** [comment]
We are obliged by the official RARBG site rules to use their API at https://torrentapi.org/ instead of the usual web scraping method.

if you can find a proxy for https://torrentapi.org/ then we should be able to add it to the indexer.
