### ISSUE TITLE
[shareisland] Exception (shareisland): Login failed: No form found on https://shareisland.org/login using form selector form: Parse error (Test)

### ISSUE THREAD

**Issue by gipasoft** [Jackett/Jackett#7044]
log: 
[log.txt](https://github.com/Jackett/Jackett/files/4130476/log.txt)

**Jackett version**:  0.12.1638.0

-------------------------------

**Comment by garfield69** [comment]
the log you provided is for netcosmo and shows a successful 50 results returned.
there is nothing in there for shareisland.
note that the shareisland indexer works for me.

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test for shareisland.
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by gipasoft** [comment]
Sorry my fault I have re-entered the password in the form and now everything works!
