### ISSUE TITLE
Decrypt Tracker passwords

### ISSUE THREAD

**Issue by kaine420** [Jackett/Jackett#7050]
There was already an issue made on a similar issue but was on a NAS device. 

I'm contacting you because I'm struggling with a problem of encrypted passwords.
I have redefine one of my indexer password on the tracker website and in Jackett and everything is working fine.

The issue is that my password manager didn't get the password change... so I have no idea what the new password is to connect myself to the website.
I am running Ubuntu Server 18.04.3

I have my private keys I just dont know what do to from here.

**Comment by garfield69** [comment]
I recommend you access the login page of the website in question, and use the *forgot my password* link to get your password reset.
It will far far easier than attempting to decrypt the one in Jackett.

**Comment by kaine420** [comment]
only if it was this easy, thats the first thing i did and no email, i have even emails their support team i figured this may be quicker

**Comment by garfield69** [comment]
then perhaps the next easiest method is to use a packet analyser, and hopefully you can snag the http outgoing packet from Jackett to the site, and spot the username password in the header.
something like https://www.wireshark.org/ for instance.

**Comment by cadatoiva** [comment]
Since some people use Jackett on a seedbox and/or use reverse proxy + public facing access, it's better if we don't implement this. It could expose their usernames **and** passwords to someone randomly stumbling across their jackett on the open web.

**Comment by cadatoiva** [comment]
However, if we're using Microsoft.Net security best practices for encrypted storage of the passwords, it shouldn't be too difficult for someone with access to the OS directly to grab the passwords out of encrypted storage, since it's done on an OS level. I'll look into building a guide after reviewing the code to see if that would be possible.

**Comment by garfield69** [comment]
to be clear, no one is asking us to provide decrypted passwords in jackett as a permanent option.
and if they we would refuse as an unsafe practice.
the op is however looking for a possible way to sort his own problem out, and since he is not running on windows, I did not suggest using the visual studio in debugger mode, which would provide the simplest way for the OP to see the password for this one time use.

**Comment by cadatoiva** [comment]
Gotcha, well there may be a way to find it in the Ubuntu keys where things like saved passwords for Chrome live, that's what I'll be checking once I get off work to see where either the passwords themselves or their decryption keys might be stored for non-Windows OS's.

**Comment by garfield69** [comment]
on unbuntu I expect the folder `~/.config/Jackett/DataProtection` is where keys and such are kept.

**Comment by kaine420** [comment]
I have my keys from the dataprotection folder now i dont know what to do with them to decrypted my passwords.

**Comment by cadatoiva** [comment]
The code is using the [ASP.NET Core Data Protection APIs](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/using-data-protection?view=aspnetcore-3.1) which makes it a lot more complicated than just applying some function to the existing code, because the data is separated by application. I'm digging into [the source code](https://github.com/dotnet/aspnetcore/tree/master/src) of the whole thing to see if there is a way to reverse the encryption.

**Comment by kaine420** [comment]
crap didnt realize its that involved.

**Comment by cadatoiva** [comment]
Well, it looks like the .xml files in the folder @garfield69 mentioned can be [pointed to as a key ring](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-3.1&tabs=visual-studio), and theoretically we can use the service from there independent of the application, but I have zero experience in this type of app so I'm getting stuck trying to make it work.

**Comment by cadatoiva** [comment]
As a random dude on the internet, I make no guarantee that this will not mess up your config or even attempt to work. But this is a self contained linux binary that uses the Jackett service keys in the source an the APIs above. Theorectically extracting this file into ~/.config/Jackett and running it from terminal should allow you to paste in the encrypted password and get the decrypted password back. I do not own a linux machine, so I have not tested it to confirm it works on Linux or with Jackett there, it's all theory.

https://drive.google.com/file/d/1tYy6eGvN4p-bjAxHEiyHZP6EFcOZ2Fy2/view?usp=sharing

**Comment by garfield69** [comment]
```
Unhandled exception. System.Security.Cryptography.CryptographicException: The key {****REDACTED****} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Decryptor.MyClass.RunSample()
   at Decryptor.Program.Main(String[] args)
Aborted (core dumped)
```
I think the tool may needs to be told its dealing with a CustomKeyRepository  in the DataProtection folder  rather than the system default key ring?

**Comment by cadatoiva** [comment]
Yeah, I found an article on [sharing protected data](https://www.paraesthesia.com/archive/2016/06/15/set-up-asp-net-dataprotection-in-a-farm/) across computers and applications and found the problem.

I've uploaded my source and a new compiled binary that incorporates the information, which can be found here: https://github.com/cadatoiva/ASP.Net-Decryptor/releases/tag/v0.1

**Comment by garfield69** [comment]
```
garfield69@Ubuntu-VirtualBox:~/Downloads/Jackett$ ./Decryptor
Enter full path for Jackett binary: ~/Downloads/Jackett
Enter the path for DataProtection Keys (should be [ConfigDir]/DataProtection): ~/.config/Jackett/DataProtection
Enter input: ***REDACTED***
Unhandled exception. System.Security.Cryptography.CryptographicException: The key {***REDACTED***} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Decryptor.MyClass.DecryptData()
   at Decryptor.Program.Main(String[] args)
Aborted (core dumped)
```
I put the decryptor in the binary folder of my jackett and I think I have the correct paths for the first two questions. and the missing key that was not found matches one of the ones in the .config/DataProtection folder, so I'm reasonably confident I have all the inputs correct.

**Comment by cadatoiva** [comment]
Full path to the Jackett binary is supposed to be the JackettConsole.exe file that runs on your computer + the full directory path from / to get to it. On FreeBSD that looks like /usr/local/share/jackett/JacketConsole.exe

**Comment by garfield69** [comment]
```
garfield69@Ubuntu-VirtualBox:~/.config/Jackett/DataProtection$ ls
key-redacted.xml  
garfield69@Ubuntu-VirtualBox:~/.config/Jackett/DataProtection$ cd ~/Dow*/Jackett
garfield69@Ubuntu-VirtualBox:~/Downloads/Jackett$ ls j*
jackett  jackett.deps.json  jackett.dll  jackett_launcher.sh  jackett.pdb  jackett.runtimeconfig.json

garfield69@Ubuntu-VirtualBox:~/Downloads/Jackett$ ./Decryptor
Enter full path for Jackett binary: ~/Downloads/Jackett/jackett
Enter the path for DataProtection Keys (should be [ConfigDir]/DataProtection): ~/.config/Jackett/DataProtection
Enter input: ***REDACTED***
Unhandled exception. System.Security.Cryptography.CryptographicException: The key {***redacted***} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Decryptor.MyClass.DecryptData()
   at Decryptor.Program.Main(String[] args)
Aborted (core dumped)

garfield69@Ubuntu-VirtualBox:~/Downloads/Jackett$ ./Decryptor
Enter full path for Jackett binary: /home/garfield69/Downloads/Jackett/jackett
Enter the path for DataProtection Keys (should be [ConfigDir]/DataProtection): ~/.config/Jackett/DataProtection
Enter input: ***redacted***
Unhandled exception. System.Security.Cryptography.CryptographicException: The key {***REDACTED***} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Decryptor.MyClass.DecryptData()
   at Decryptor.Program.Main(String[] args)
Aborted (core dumped)
```

**Comment by cadatoiva** [comment]
https://github.com/cadatoiva/ASP.Net-Decryptor/releases

Test release 2 should fix this problem. Make sure the binary you're pointing to is the one that was used to initially encrypt the string and that it wasn't moved after encrypting.

**Comment by garfield69** [comment]
I put the decryptor program in the /home/garfield69/Downloads folder and chmod the program for exec rights `chmod u+wrx  Decryptor`.
to be clear, the password string for the input is from the ~/.config/Jackett/Indexers/3evils.json file, from the **value** field of the **password** block, which I copy/paste without the quotes, correct?
```json
  {
    "id": "password",
    "type": "inputstring",
    "name": "Password",
    "value": "encrypted password that I copy  / paste into the input query of the decryptor program"
  },
```
new error: 
```
garfield69@Ubuntu-VirtualBox:~/Downloads$ ./Decryptor
Is this the computer that was used to encrypt the data string? [y/n]: y
Enter full path for Jackett binary: /home/garfield69/Downloads/Jackett/jackett
Enter the path for DataProtection Keys (should be [ConfigDir]/DataProtection): /home/garfield69/.config/Jackett/DataProtection
Enter input: ***redacted***
Unhandled exception. System.Security.Cryptography.CryptographicException: The payload was invalid.
   at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor.Decrypt(ArraySegment`1 protectedPayload, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Decryptor.MyClass.DecryptData()
   at Decryptor.Program.Main(String[] args)
Aborted (core dumped)
```

**Comment by garfield69** [comment]
@kaine420  since this is for your benefit, why don't you have a go at this and see if it works for you.
this way we get some alternate feedback, just in case then problem is with me ;-)

**Comment by garfield69** [comment]
@cadatoiva  btw, I had previously been using `~/.config/Jackett/DataProtection` but this is now not accepted, which might account for the earlier failures...
```
garfield69@Ubuntu-VirtualBox:~/Downloads$ ./Decryptor
Is this the computer that was used to encrypt the data string? [y/n]: y
Enter full path for Jackett binary: /home/garfield69/Downloads/Jackett/jackett
Enter the path for DataProtection Keys (should be [ConfigDir]/DataProtection): ~/.config/Jackett/DataProtection
DataProtection folder does not exist: /home/garfield69/Downloads/~/.config/Jackett/DataProtection
```

**Comment by cadatoiva** [comment]
That is the correct string to try and decrypt, but it seems the change I made in test release 2 has shown us where the problem was this whole time. Instead of using ~ as the shortcut for /home/garfield69 for the DataProtection folder, try using the full path.

**Comment by cadatoiva** [comment]
The new error you got, though, was the same one I was getting in Windows before I uploaded Test Release 1. I'm not sure why that's the case, I'll have to go back to the drawing board, because I must be missing something. Such a pain, it'd almost just be easier to make a drop in Jackett binary that does the insecure thing.

**Comment by cadatoiva** [comment]
I'm going to try to just migrate the whole https://github.com/Jackett/Jackett/blob/master/src/Jackett.Server/Services/ProtectionService.cs file to this decryptor in the morning and see if that makes a difference.

**Comment by rrrevin** [comment]
Give it up. Seriously.

The whole idea with encrypting passwords is that they CAN'T be decrypted and figured out
This is Security Fundamentals 101. 

Just create a new account with a new login and password, Use a stronger/better password manager in the future. If you don't want to create a new account, then chalk this up to experience.

**Comment by kaine420** [comment]
you should be able to decrypted with your keys. you have a lock you should be able to unlock it if need be right? No thats not security fundamentals 101 when they talk about encryption they also talk about decryption.

**Comment by junglebus** [comment]
You guys are over complicating it
Create a PR and immediately cancel it and download the artifact and run it
Just add one line here https://github.com/Jackett/Jackett/blob/a89c7dedeb1ad1ce50e83acec04ad4ad211ff9c0/src/Jackett.Common/Indexers/BaseIndexer.cs#L222
`logger.Info("password:" + protectionService.UnProtect(passwordValue));`
and the password should appear in your logs

**Comment by ngosang** [comment]
Passwords are encrypted for security reasons and we can't add a feature to show them in plain text.
If someone needs to recover passwords, the @junglebus hack works.

**Comment by cadatoiva** [comment]
@rrrevin Jackett has to decrypt the password stored in config if it wants to log in to the website, so it has to decrypt it each time. Therefore it is possible. All the links I provided talk about how to share the (en/de)cryption keys across multiple applications for a variety of reasons.

@junglebus that is a quick solution for sure, and I thought about doing something similar. I wanted an external tool that people could use, and thought I could find it, but it's harder to do than originally thought. Not sure why, as everything I read said it should work.

@ngosang we mentioned early on that no one was asking for this feature in the main Jackett application. The solution by @junglebus works well enough for those very rare cases where this becomes an issue, so I'm done sinking effort into this anyway. Would have been cool to get my app running though. Oh well.

@kaine420 if you need help implementing the solution by @junglebus, just let me know and I'll help out.

**Comment by kaine420** [comment]
@cadatoiva I gave up hope lol fi you dont mind helping me with this that would be great.
