### ISSUE TITLE
[torrentlt] Error: Suveikė prisijungimo apsaugą. Pažymėkite, kad nesate robotas (Config)

### ISSUE THREAD

**Issue by slavkan9** [Jackett/Jackett#7051]
Torrent.lt have enabled ReCaptcha on their login page.
![image](https://user-images.githubusercontent.com/6933240/73568996-66fc8b80-44ce-11ea-967a-efa0ecd4bd11.png)

the indexer will need to have its login section switched to the cookie method.

**Comment by garfield69** [comment]
jackett 0.12.1701
