### ISSUE TITLE
[Request] New tracker korsar.tv

### ISSUE THREAD

**Issue by Lonli-Lokli** [Jackett/Jackett#7052]
New russian tracker http://korsar.tv/

**Comment by garfield69** [comment]
Jackett 0.12.1804

**Comment by dimqua** [comment]
Is it currently private?

**Comment by garfield69** [comment]
https://korsar.info/ returning `This site can’t be reached`
site gone, or broken, or moved to a new domain?

**Comment by Lonli-Lokli** [comment]
Why korsar.info? Initial request has been created for korsar.tv which works now.

**Comment by garfield69** [comment]
korsar.tv used to redirect to korsar.info when the indexer was first added 6 months ago.
I'll update the indexer to use *.tv instead of *.info

**Comment by garfield69** [comment]
korsar.tv seems to redirect to korsar.rest now.
Also public ? do not see m to need to login to download .torrents ?

**Comment by garfield69** [comment]
hmm. nope, the first few DL worked then adverts started kicking in, so login still needed for clear .torrent DLing.
but I am seeing tons of ERR_TOO_MANY_REDIRECTS errors from my browser when trying to login via http://korsar.rest

occasionally getting dumped to https://www.punktorrents.com/member.php?action=register WTF?

**Comment by garfield69** [comment]
korsar sent me a notice that the domain had changed to http://filbi1976.org/
but a login via browser ends up returning 404
![image](https://user-images.githubusercontent.com/6933240/95687388-dd59ac00-0c5f-11eb-8ed7-2bd103dfef35.png)

**Comment by Lonli-Lokli** [comment]
@garfield69 it's not too stable tracker unfortunately

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/fcbd612299fd06366277bf34a4dbdcf478dc544c

**Comment by garfield69** [comment]
no, i left the ticket open on purpose.
I still cannot login to the site, I end up with the error I reported in https://github.com/Jackett/Jackett/issues/7052#issuecomment-706751022.
I can reset my password via the login reset options, so I have an account and good credentials
Just me?

**Comment by garfield69** [comment]
@Lonli-Lokli  are you getting the 404 error when trying to access http://filbi1976.org/ after the login page?

**Comment by ilike2burnthing** [comment]
Whoops, my bad

**Comment by Lonli-Lokli** [comment]
@garfield69 yep.

**Comment by garfield69** [comment]
Was able to login again on Korsar today, I will look into reinstating the indexer.

**Comment by garfield69** [comment]
v0.20.667
