### ISSUE TITLE
[iptorrents]  (Config)

### ISSUE THREAD

**Issue by Lipora** [Jackett/Jackett#7063]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------
Jackett Version 0.12.1669.0

Error Log:
```
Jackett.Common.ExceptionWithConfigData
   at Jackett.Common.Indexers.IPTorrents.<>c__DisplayClass15_0.<ApplyConfiguration>b__0() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/IPTorrents.cs:line 219
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 267
   at Jackett.Common.Indexers.IPTorrents.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/IPTorrents.cs:line 222
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 110
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73
```

**Comment by Lipora** [comment]
Found this in the Enhanced Logging (Noticing the WebServiceUnavailable):  


Feb 01, 2020 02:21:39 PM | Debug | Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett)
-- | -- | --
Feb 01, 2020 02:21:39 PM | Debug | Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett)
Feb 01, 2020 02:21:39 PM | Info | Authorization was successful.
Feb 01, 2020 02:21:39 PM | Debug | Execution plan of result filters (in the following order): None
Feb 01, 2020 02:21:39 PM | Debug | Execution plan of exception filters (in the following order): None
Feb 01, 2020 02:21:39 PM | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter
Feb 01, 2020 02:21:39 PM | Debug | Execution plan of resource filters (in the following order): None
Feb 01, 2020 02:21:39 PM | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Feb 01, 2020 02:21:39 PM | Info | Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing controller action with signature System.Collections.Generic.List`1[Jackett.Common.Models.CachedLog] Logs() on controller Jackett.Server.Controllers.ServerConfigurationController (jackett).
Feb 01, 2020 02:21:39 PM | Info | Executing endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)'
Feb 01, 2020 02:21:39 PM | Debug | Request matched endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)'
Feb 01, 2020 02:21:39 PM | Debug | Endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)' with route pattern 'api/v2.0/server/Logs' is valid for the request path '/api/v2.0/server/logs'
Feb 01, 2020 02:21:39 PM | Debug | 1 candidate(s) found for the request path '/api/v2.0/server/logs'
Feb 01, 2020 02:21:39 PM | Debug | AuthenticationScheme: Cookies was successfully authenticated.
Feb 01, 2020 02:21:39 PM | Debug | The request path /api/v2.0/server/logs does not match a supported file type
Feb 01, 2020 02:21:39 PM | Debug | Request is continuing in applying rules. Current url is http://10.0.1.2:9117/api/v2.0/server/logs?_=1580591980241
Feb 01, 2020 02:21:39 PM | Debug | Request is continuing in applying rules. Current url is http://10.0.1.2:9117/api/v2.0/server/logs?_=1580591980241
Feb 01, 2020 02:21:39 PM | Debug | Request is continuing in applying rules. Current url is http://10.0.1.2:9117/api/v2.0/server/logs?_=1580591980241
Feb 01, 2020 02:21:39 PM | Info | Request starting HTTP/1.1 GET http://10.0.1.2:9117/api/v2.0/server/logs?_=1580591980241
Feb 01, 2020 02:21:33 PM | Info | Request finished in 960.6192ms 500 application/json
Feb 01, 2020 02:21:33 PM | Debug | Connection id "0HLT7B6MAPG2I" completed keep alive response.
Feb 01, 2020 02:21:33 PM | Debug | The response will be compressed with 'gzip'.
Feb 01, 2020 02:21:33 PM | Error | Jackett.Common.ExceptionWithConfigData    at Jackett.Common.Indexers.IPTorrents.<>c__DisplayClass15_0.<ApplyConfiguration>b__0() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/IPTorrents.cs:line 219    at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 267    at Jackett.Common.Indexers.IPTorrents.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/IPTorrents.cs:line 222    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 110    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73
Feb 01, 2020 02:21:33 PM | Info | Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
Feb 01, 2020 02:21:33 PM | Info | Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 943.025ms
Feb 01, 2020 02:21:33 PM | Debug | WebClient(HttpWebClient2NetCore): Returning ServiceUnavailable => <!DOCTYPE HTML> <html lang="en-US"> <head>   <meta charset="UTF-8" />   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />   <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />   <meta name="robots" content="noindex, nofollow" />   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />   <title>Just a moment...</title>   <style type="text/css">     html, body {width: 100%; height: 100%; margin: 0; padding: 0;}     body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif; font-size: 100%;}     h1 {font-size: 1.5em; color: #404040; text-align: center;}     p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;}     #spinner {margin: 0 auto 30px auto; display: block;}     .attribution {margin-top: 20px;}     @-webkit-keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }     @keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }     .bubbles { background-color: #404040; width:15px; height: 15px; margin:2px; border-radius:100%; -webkit-animation:bubbles 0.6s 0.07s infinite ease-in-out; animation:bubbles 0.6s 0.07s infinite ease-in-out; -webkit-animation-fill-mode:both; animation-fill-mode:both; display:inline-block; }   </style>      <script type="text/javascript">   //<![CDATA[   (function(){     var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },     b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};     b(function(){       var a = document.getElementById('cf-content');a.style.display = 'block';       setTimeout(function(){         var s,t,o,p,b,r,e,a,k,i,n,g,f, TwsWiVr={"opyI":+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![])+(+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+!![]))/+((+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+!![])+(+!![])+(!+[]+!![]))};         g = String.fromCharCode;         o = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";         e = function(s) {           s += "==".slice(2 - (s.length & 3));           var bm, r = "", r1, r2, i = 0;           for (; i < s.length;) {               bm = o.indexOf(s.charAt(i++)) << 18 \| o.indexOf(s.charAt(i++)) << 12                       \| (r1 = o.indexOf(s.charAt(i++))) << 6 \| (r2 = o.indexOf(s.charAt(i++)));               r += r1 === 64 ? g(bm >> 16 & 255)                       : r2 === 64 ? g(bm >> 16 & 255, bm >> 8 & 255)                       : g(bm >> 16 & 255, bm >> 8 & 255, bm & 255);           }           return r;         };         t = document.createElement('div');         t.innerHTML="<a href='/'>x</a>";         t = t.firstChild.href;r = t.match(/https?:\/\//)[0];         t = t.substr(r.length); t = t.substr(0,t.length-1);          a = document.getElementById('jschl-answer');         f = document.getElementById('challenge-form');         ;TwsWiVr.opyI+=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]));TwsWiVr.opyI-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(+!![]))/+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));TwsWiVr.opyI+=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]))/+((+!![]+[])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]));TwsWiVr.opyI*=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(+!![])+(!+[]+!![]));TwsWiVr.opyI-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]));TwsWiVr.opyI-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]));TwsWiVr.opyI+=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]))/+((+!![]+[])+(!+[]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]));TwsWiVr.opyI+=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]))/+((!+[]+!![]+[])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(+[]));TwsWiVr.opyI-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));a.value = (+TwsWiVr.opyI + t.length).toFixed(10); '; 121'         f.action += location.hash;         f.submit();       }, 4000);     }, false);   })();   //]]> </script>   </head> <body>   <table width="100%" height="100%" cellpadding="20">     <tr>       <td align="center" valign="middle">           <div class="cf-browser-verification cf-im-under-attack">   <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1></noscript>   <div id="cf-content" style="display:none">          <div>       <div class="bubbles"></div>       <div class="bubbles"></div>       <div class="bubbles"></div>     </div>     <h1><span data-translate="checking_browser">Checking your browser before accessing</span> iptorrents.com.</h1>          <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>     <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>   </div>       <form id="challenge-form" action="/take_login.php?__cf_chl_jschl_tk__=13f128b8f09a4bddeed647dc1b44c59de1029993-1580592093-0-AUaq40LIAklA3xia41P90oKqP1uh4ffz_D7k02J9UzEE0BQRcDI7UI7YdKjsPHi324FJUrH-_f-V-wWMxyv2wWE4ZTNZdvZ0R1_jTy0y9B9QySXjU4N6ZBomi4sG_me4869UCX68Rmnx6UF8xU8HnWsW6vSmtO_-IkfAbomq0VdYl6Hr5TGtF-Zl-WuTcnAAXHMo108fsrqkPCPli3Kf9UVHMIZlVBKbFX36OdcvrWsKeh5Kh0t2sZGLdi3gzo7V_Vr6Z_T3MSc5Q0kB3vUHUgBF3jUtC8y9O6jOx8KtsTE4H8sHjhW6T6G9ObGj36uvVKMbcoVrn2pS7FlrSWm3KvI" method="POST" enctype="application/x-www-form-urlencoded">     <input type="hidden" name="r" value="9309e28eb5a88393f68a805bbc6f7142c353e4a8-1580592093-0-AT3baG96ubC/OE2D9gTff1qVcns/PNetOwS11v1uOmJjptUTrAwiAyzNvx6aIl+oZVk1wHdBfFeLovp6OTjJTrHTZGddLu93sQEU2KdvYw/SC3jIMonN9ChSq83rz7tYJNMLw2bI6/DJmv6erUYLAm/2qxa8tzdK9JCYSlYduSpdNGCsL2ImOTWcrV+DWBie5K3a2so2pdemGKPrs3xOToUqkXSd3BQ4FjqzkVSinRI8V1aUZWgOiRror2I/5P5i0mMe3hKqLEayyWQSQjRRclXE4RHtGmImxaRqfG4p2TaJVUJHFD4RJjswORWowIxjWIzuU+6tjgJ7zkNJ6mUbBVJNPXLqcIKTQCpUSZ4rULDFfggZmd6G6jm03mDxOCkcqlMkEgI3OaAjP0RKAwMjhOQ0tInNDF/GWE1uq8ARVInAmzwMF+8UgV4o1h0ph/TS0araOJSCeHEHh6hrAlPiFzxYOxAdtjlI0HdQrimbrH4DlDlPLLDLoJhkae0wmPvC4jaE443WNtjYPVOc30MoCZR1+pp3ywMHYI35GNh8FMNgFq5DQ4kbHK92GQczdeSwFClJskRRsHmslzM6WNSkgqrV8nsqpEcmDJhhQLfzzrcAKN2N/LXH0U+VF+GLtxhEHsnIi4zj3s27YsYt0m7yKd6BsgOvB/bZxh0fvxOjsLuolbLcFpdr+XAkL2TRKvdIXqw4KirZuX8tRY73sNtuAbmewY/z1lUnSe8XLxpNIPO6CvNfTM8yoc8sjiBbVWl5XQLDaErUDac9ue1AbPc3C6mcmgnGkJobnR0fpdQOtPyQwb5Tjbp6FA4Fe0AtZLrb39n7jBiWr2RI5YDTvyGxg+c/cWX/GxtkznJO4vgJhZgEnrXqQRCwrOlunQBFoDMH0Ck7ueWASHH3pvItjBlSMo4E3A5ayXo3LdmOtSS4w12vPTqwGzv+eul+ZInfou5mOjdoQvzwJE0uyCGtTBa0SGrVvtm6NgiCNUWhq1CWDdWmpPvD+U29yn7eeXnFo4w4uo9GB5PDlGDgpGWpfEE6jbirYXRNTvVkRQq5HQoAzAlcxRZQsQAGGBWjxXxb8qWCL5PCBVSv+tf8m9dpa3XLGAtS4L/RzUVDuPkiDHwJGkP2wKgeUDfcadb97+9Urs7+9z136vAzkyA5XYMFbQpoy6ThOQ+rqF2Fu+S/CXRENdVwzt30lZrVnr4MvoYVSeEbvROtUW10HTfHbJohKNg3k6YwYHR0bbb27W/UGUHG2DUuyBcHF7qz4Z9kdHDhblHqpjez4gybH9ouoRSXNGPm8SgC97ra//KFTlDCMztFG0AoUq4kg21M63pfndZHL1tR9yK53J6WECrnguRKFOSc05Dutp1+lPYVRjeDdyu+gpN1Awr1Mkd4JWA6ozIXWDFvM/apcnjGkXxJJRB/0Vv2+U1FU/HbKXss0ouVhVh4ol+GBxoIMRn1AuhIYF+R1vnGIzo7pPEAsF+ujQ4tjv0oUICcbjqmPAr7JNfGk/Y3CaL5rqAk0TvGDDLrED/rfffUCCwjNJxCxB7ggCkkrlXFAfSyby9vsvDU18IB1WjrGh/xA69qscp50mtDdujEjhPy20XrC1Ga+SgV3VTbYw34QT5JlTFByrwPsVIGBwypy+fVjIt/1wl4DRAOTon5Hoj3VpOt9Ixl9AtIqQhOtjAjQh/9C/RuV1jyQwsca6Z64Qvq"></input>     <input type="hidden" name="jschl_vc" value="e596782bcc3085a455b2ba08841a3090"/>     <input type="hidden" name="pass" value="1580592097.511-ba+KYkLTyc"/>     <input type="hidden" id="jschl-answer" name="jschl_answer"/>   </form>    </div>                       <div class="attribution">             <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=iuam" target="_blank" style="font-size: 12px;">DDoS protection by Cloudflare</a>             <br>             Ray ID: 55e6f9c85f4decea           </div>       </td>           </tr>   </table> </body> </html>
Feb 01, 2020 02:21:33 PM | Debug | cf_clearance=459c4dde587f4a72cdcab5fc15c759b518d4dd35-1580591760-0-150
Feb 01, 2020 02:21:33 PM | Debug | __cfduid=da5d081d903362e5cbf237f31f2a1381a1580591756
Feb 01, 2020 02:21:32 PM | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://iptorrents.com/take_login.php)

**Comment by Lipora** [comment]
Tried with and without Proxy and with and without VPN and multiple endpoints...All with the same error.

**Comment by cadatoiva** [comment]
Thank you for this information. It should help us track down the bug. We should merge this ticket into #6485 so all the information is together in one place.

**Comment by ngosang** [comment]
We did some changes in IPTorrents code to improve the debug information. Please, could you update to the latest version (Jackett 0.12.1746 or newer) and provide feedback? If there is a exception, enable the `Enhanced logging` and post the logs. Thank you!

**Comment by garfield69** [comment]
Jackett 0.13.173
