### ISSUE TITLE
[firebit] review latest releases

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7067]
If I perform an empty search in firebit, I get really old results. I think they are wrong.

**Comment by garfield69** [comment]
firebit does not allow keywordless search, and the new-items page http://firebit.net/%D0%BD%D0%BE%D0%B2%D0%B8%D0%BD%D0%BA%D0%B8/ appears unsorted.

so instead, when you do a keywordless search, the indexer currently fetches the movies page http://firebit.net/%D1%84%D0%B8%D0%BB%D1%8C%D0%BC/ and the series page http://firebit.net/%D1%81%D0%B5%D1%80%D0%B8%D0%B0%D0%BB/ and presents those results.

the site does not appear to support any kind of sorting.

I would welcome suggestions for improving this indexer if you can think of some better way.

**Comment by ngosang** [comment]
Sorry, no ideas.
