### ISSUE TITLE
Kaspersky flag

### ISSUE THREAD

**Issue by d2dyno** [Jackett/Jackett#707]
Kaspersky is flagging jackettservice.exe as a Trojan/PDM, and thus removing it. Full logs/info to follow when I get access to my machine.

**Comment by d2dyno** [comment]
Here is the line I pulled from the Kaspersky report:

19.11.2016 01.46.23	Detected object (process memory) deleted.	c:\programdata\jackett\jackettservice.exe	Process memory: c:\programdata\jackett\jackettservice.exe	Object name: PDM:Trojan.Win32.Generic	Object type: Other malware	Time: 11/19/2016 1:46 AM

**Comment by kaso17** [comment]
Did this change with a recent signature update or did you install kaspersky for the first time?
Definitely no malware included...
I assume they blacklisted it just because it's P2P related, like they blacklist cracks, etc.

**Comment by kaso17** [comment]
According virtustotal it's not flagged  by any anti virus scanner.
https://www.virustotal.com/en/file/e41fa9c46e1b42328b34e1408cd25ccc3a920603cc48896ccecb83f3c1100442/analysis/1479632690/
https://www.virustotal.com/en/file/7c78451be302f1cfef0d08178c25e237be46295ec602e20b0dd711d458c84360/analysis/1479632630/

Only for JackettConsole.exe the Qihoo-360 heuristic picks up "HEUR/QVM03.0.0000.Malware.Gen", no idea why...
https://www.virustotal.com/en/file/42e48b097cb2d013c7b428be78272c0eeacb8fd389dec12fed1fe868077732a6/analysis/1479632752/

Any chance that some other real malware infected your jackett installation?

**Comment by d2dyno** [comment]
Hmm, that's very odd then. I'll try and see what I can do to re-produce this. Could have also been a false positive that was fixed in a definitions update, not sure.
