### ISSUE TITLE
[REQ] pirateiro.com

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#7070]
Public tracker of movies, anime, tv, music, xxx and others

http://pirateiro.com/

**Comment by garfield69** [comment]
Jackett 0.12.1811

**Comment by RicardoVelaC** [comment]
http://pirateiro.com/ It's not a Spanish site, it only provides English content.

**Comment by garfield69** [comment]
https://pirateiro.eu/torrents/?search= returns
![image](https://user-images.githubusercontent.com/6933240/152233904-9c2e962f-7918-4b80-9f1a-83d1660d6de7.png)

**Comment by garfield69** [comment]
now https://pirateiro.eu/ returns the same message. removing indexer now.

**Comment by garfield69** [comment]
v0.20.521
