### ISSUE TITLE
[REQ] torrent4you.me

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#7071]
Public tracker of movies, series, anime, apps, games, books, music and xxx

http://torrent4you.me

**Comment by garfield69** [comment]
Jackett 0.12.1811

**Comment by ilike2burnthing** [comment]
https://torrent4you.me/ - Error 523 - Origin is unreachable

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrent4you.me/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrent4you.me/ - Error 523 - Origin is unreachable

**Comment by ilike2burnthing** [comment]
back up

**Comment by ngosang** [comment]
Down  Error 521

**Comment by garfield69** [comment]
https://torrent4you.me/ - Error 523 - Origin is unreachable
