### ISSUE TITLE
[REQ] Filtering non existing torrents from results - plugin NewPct

### ISSUE THREAD

**Issue by brainstormi** [Jackett/Jackett#7074]
Is there any way to filter those links which doesn't have associated a torrent link?. There are many old pages in NewPct webpage, that are not linked anymore to a torrent file, for example: https://descargas2020.org/descargar-seriehd/big-little-lies/capitulo-16/hdtv-720p-ac3-5-1/
The issue is that returning these results back to Meduse/Sonarr, causes them to fail, not continuing with other candidates.

**Comment by garfield69** [comment]
@ngosang  can you take a look at this please?
we should already be dropping any titles that do not have download links, as presenting torznab apps with link-less titles goes against specs.

**Comment by garfield69** [comment]
Jackett 0.12.1746
