### ISSUE TITLE
Update notification every few hours [BUG?]

### ISSUE THREAD

**Issue by PanoptesDreams** [Jackett/Jackett#7075]
Ever since I've started using Jackett (about 2 years) on Windows, I receive constant hourly notifications saying Jackett has updated to a newer version (0.12.1669.0), it doesn't/hasn't.
I'm currently on 0.10.314.0

I don't pay attention to updates because if it's automatically handled I don't care, but I start to care when I get constant notifications about something that isn't happening.

Notification Image
![image](https://user-images.githubusercontent.com/55162814/73618926-a58d7400-468f-11ea-9912-507dc732c7c4.png)

**Comment by garfield69** [comment]
if you are getting an update notification, but are not seeing the latest version number at the bottom of your jackett dashboard,  then this means the update is not succeeding, and would explain why you are seeing regular update attempts and notices.

I suggest that you manually install as a service from the latest version at https://github.com/Jackett/Jackett/releases following the notes at https://github.com/Jackett/Jackett#installation-on-windows

and keep an eye of subsequent update notifications.
You Jackett dashboard should reflect the update version number if the update was successful.
if it has not changed then report it here and I will re-open this ticket and dig deeper with you.
