### ISSUE TITLE
[hachede] Login failed: Selector

### ISSUE THREAD

**Issue by vinanrra** [Jackett/Jackett#7077]
Login failed: Selector "div#member_info_bar" didn't match

Jackett version:

Version 0.12.1669.0

I was able to log in 1-2 weeks ago, but now im unable to do it, seems like they change a bit the webpage.

LOG: 

[log.txt](https://github.com/Jackett/Jackett/files/4146932/log.txt)

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by vinanrra** [comment]
> 
> 
> Please provide the **full enhanced log** file.
> 
>     1. scroll down to the bottom of the Jackett Dashboard and _tick_ the _enhanced Logging_ checkbox
> 
>     2. scroll up a bit and _click_ on the _apply server settings_ button
> 
>     3. repeat the test
> 
>     4. find the _log.txt_ file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
> 
>     5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
> 
>     6. save, then drag-drop it here for us to take a look at.
> 
> 
> Thanks.

Added

**Comment by garfield69** [comment]
nope, the log you posted is just the regular log. you did not activate the enhanced log switch.
you will know when you have it right as you will see many messages with the **Debug** keyword.
please read my prior post more carefully and try again. thanks.

**Comment by vinanrra** [comment]
> 
> 
> nope, the log you posted is just the regular log. you did not activate the enhanced log switch.
> you will know when you have it right as you will see many messages with the **Debug** keyword.
> please read my prior post more carefully and try again. thanks.

True i forgot to press "Apply to server"

**Comment by garfield69** [comment]
the log shows that the cookie you provided was not accepted by the site and it returned you back to the login page, which is why the Selector "div#member_info_bar" didn't match

cookies have expiry dates. you will regularly have to refresh them. 
Have you tried using your browser to login and capturing a fresh cookie to try on the Jackett config page?

**Comment by vinanrra** [comment]
It's strange because I already did what you said and worked, because cookie expire once a week and I have already done 5 times and this time Gabe me that error, will check againt later.

**Comment by vinanrra** [comment]
Okay seems to work, dunno what happended but i tried the same cookie because i copy and paste from a file the same and now works, sorry to bother.
