### ISSUE TITLE
[REQ] Add new private tracker Twilights Zoom

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7080]
Add Twilights Zoom, the music sister of ScenePalace

@garfield69 Open registrations today => 
http://twilightzoom.org/signup.php

Twilights Zoom is a Private Torrent Tracker for MUSIC

**Comment by garfield69** [comment]
Jackett 0.12.1811

**Comment by ilike2burnthing** [comment]
https://twilightzoom.org/ - ERR_NAME_NOT_RESOLVED

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://twilightzoom.org/ retuning DNS_PROBE_FINISHED_NXDOMAIN 
domain not found, just me?

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://twilightzoom.org/ returns DNS_PROBE_FINISHED_NXDOMAIN (DNS domain not found)

**Comment by garfield69** [comment]
v0.20.2486
