### ISSUE TITLE
[REQ] Public DHT - 7torrents.cc

### ISSUE THREAD

**Issue by ward0** [Jackett/Jackett#7098]
Hello,

Can you add this public DHT tracker pls.

Thanks!

I love your work!

-------------------------------

**Comment by garfield69** [comment]
Jackett 0.12.1811

**Comment by ward0** [comment]
@garfield69  Thanks for your work sir!

**Comment by garfield69** [comment]
https://www.7torrents.cc/ returning Error 502 Bad gateway

**Comment by ilike2burnthing** [comment]
Back up!

**Comment by ilike2burnthing** [comment]
https://www.7torrents.cc/

![7torrents](https://user-images.githubusercontent.com/59480337/89730201-8273c080-da34-11ea-8067-93ecce2cd9c1.png)

Intermittent problem. Test several times over a few minutes to confirm stability.

**Comment by ilike2burnthing** [comment]
https://www.7torrents.cc/
Error 520 - Web server is returning an unknown error
Error 524 - A timeout occurred
Error 525 - SSL handshake failed

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://www.7torrents.cc/
> 
> ![7torrents](https://user-images.githubusercontent.com/59480337/89730201-8273c080-da34-11ea-8067-93ecce2cd9c1.png)
> 
> Intermittent problem. Test several times over a few minutes to confirm stability.

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
sigh... nope

**Comment by ilike2burnthing** [comment]
Lets try this again... back up...

Tested regularly over half an hour in browser and Jackett, seems to be fine now

**Comment by ilike2burnthing** [comment]
> https://www.7torrents.cc/
> ![7torrents](https://user-images.githubusercontent.com/59480337/89730201-8273c080-da34-11ea-8067-93ecce2cd9c1.png)
> Intermittent problem. Test several times over a few minutes to confirm stability.

Nope 🙄

**Comment by ilike2burnthing** [comment]
Checked over the last few days, and pretty constantly over the last hour, with no issues. So I'll hesitantly say that it's back up...

**Comment by ilike2burnthing** [comment]
> https://www.7torrents.cc/
> ![7torrents](https://user-images.githubusercontent.com/59480337/89730201-8273c080-da34-11ea-8067-93ecce2cd9c1.png)
> Intermittent problem. Test several times over a few minutes to confirm stability.

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://www.7torrents.cc/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://www.7torrents.cc/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://7torrents.cc/ - ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://www.7torrents.cc/ - ERR_NAME_NOT_RESOLVED

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.7torrents.cc/  returning 502 Bad Gateway nginx

**Comment by ilike2burnthing** [comment]
ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.20.555
