### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Name or service not known: Name or service not known (Test)

### ISSUE THREAD

**Issue by guicha910** [Jackett/Jackett#7099]
Hi there,

Yggtorrent changed their website adress from .ws to .se

Thus not being available on Jackett anymore. 

Could you solve this or give directive to help resolve it ?

Regards and thanks for your work.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/7095#issuecomment-582238746
