### ISSUE TITLE
[myamity] Exception (myamity): Object reference not set to an instance of an object: Parse error (Config)

### ISSUE THREAD

**Issue by karbrueggen1** [Jackett/Jackett#7100]
Hey there!

i'm trying to add the private Tracker "myamity" but it's not working.
I can log in to the tracker via webbrowser without any problems.
Also downloading a torrent file is working fine.
I removed the HTML sourcecode from the Logfile, because it contains private informations.
If you need them anyway, i can anonymize it.

Jackett Version: 0.12.1669.0
Mono JIT compiler version: 5.20.1.34
Small Log File Pastebin: https://pastebin.com/M9bZiTG7

**Comment by fnk93** [comment]
Alos happening on Jackett Version: 0.12.1681.0

**Comment by garfield69** [comment]
I don't have an account on this site so I cannot test for myself. @ngosang  have you access?
@karbrueggen1  judging by the stack trace the issue appears related to `at Jackett.Common.Models.TorznabQuery.MatchQueryStringAND` which would put it in this section of the code
https://github.com/Jackett/Jackett/blob/dbb3234bf1f53ed0e7af5c53da04aabfc2fe7a6d/src/Jackett.Common/Indexers/myAmity.cs#L129-L142

the full enhanced log with the returned html would definitely be useful in this case.

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by ngosang** [comment]
> have you access?

no, sorry

**Comment by karbrueggen1** [comment]
> Please provide the **full enhanced log** file.
> 
> 1. scroll down to the bottom of the Jackett Dashboard and _tick_ the _enhanced Logging_ checkbox
> 2. scroll up a bit and _click_ on the _apply server settings_ button
> 3. repeat the test
> 4. find the _log.txt_ file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
> 5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
> 6. save, then drag-drop it here for us to take a look at.
> 
> (Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).
> 
> Thanks.

I tried to redact every personal detail, hope i got everything.
If required, i could provide access to the tracker.

[log.txt](https://github.com/Jackett/Jackett/files/4161522/log.txt)

**Comment by garfield69** [comment]
Hmm. looks like the site html has a broken tag.
the Jackett indexers' code looks for the first `<a>` tag with a `href` that starts with `torrents-details.php?id=` and then expects to find the `title` attribute.
but the site html no longer has the `title` attribute, and the `<a>` tag does not have a matching `</a>`, so things are a bit awry.
```html
    <td class=ttable_col2 nowrap>&nbsp; 
       <a href="torrents-details.php?id=223093&hit=1" 
          onmouseover="return overlib('<table width=100% class=account align=center><tr><td class=css-right colspan=2 align=center>Fussball.DFB.Pokal.2019-2020.Achtelfinale.FC.Schalke.04.vs.Hertha.BSC.German.1080p.HDTV.x264-SPORTY</td></tr><tr valign=top><td align=center class=css><img border=0 width=220  src=images/nocover.png class=poster></td><td class=css-right><div align=left class=torrent-category-detail clearfix><ul class=list><li><h3 align=center>Torrent übersicht </h3></li><li><b>Hochgeladen am : </b>05-02-2020</li><li><b>Seeder : </b><font color=#2F12E6>1</font></li><li><b>Leecher : </b><font color=#FF0000>0</font></li><li><b>Fertiggestellt : </b><font color=#0D8604>0</font></li><li><b>Sprache : </b>  <img border=0 width=32  src=/images/languages/unknown.gif> </li></ul><br><br></div></td></tr></table>')"; 
          onmouseout="return nd()"><b>Fussball.DFB.Pokal.2019-2020.Achtelfinale.FC.Schalke.04.vs.Hertha.BSC.German.1080p.HDTV.x264-SPORTY</b>
   </td>
```

Trying to code a solve without being able to test and correct between publishing fixes is an error laden way to work.
It would really be helpful if you could send an invite to garfieldsixtynine @ gmail.com and I should then be able to get a solution for the current site's html.

But it would not surprise me to find that soon after publishing a fix, the site changes the html again to fix up their code.

**Comment by karbrueggen1** [comment]
> It would really be helpful if you could send an invite to garfieldsixtynine @ gmail.com and I should then be able to get a solution for the current site's html.

I just send you the Invite, hope this helps solve the Problem! 👍

**Comment by garfield69** [comment]
registration and login successful. thank you.

**Comment by garfield69** [comment]
jackett 0.12.1701
