### ISSUE TITLE
OpenVPN integration

### ISSUE THREAD

**Issue by elliotpryde** [Jackett/Jackett#7103]
I just started using Jackett my first attempt to set up a tracker for Radarr/Sonarr was hit with an ISP block. In this case it's https://1337x.to/. Similar to how some BitTorrent clients like [Transmission](https://github.com/transmission/transmission) have a form of [OpenVPN integration](https://github.com/haugene/docker-transmission-openvpn) it would be useful for Jackett too. This should be an issue for anyone in a country with ISP blocks who doesn't want to run all their traffic through a VPN and doesn't have the know-how to set up a proxy specifically for Jackett.

**Comment by ngosang** [comment]
If you install and configure the OpenVPN client in your server, all the server traffic will be routed through OpenVPN tunnel. All services, Jackett, Sonarr, Bittorrent... you don't have to configure anything in Jackett.
