### ISSUE TITLE
error running on ubuntu 19.04

### ISSUE THREAD

**Issue by denbeiren** [Jackett/Jackett#7109]
I installed Jackett on a 19.04 Ubuntu server. 
When starting Jackett trough commandline i get this error: 

https://pastebin.com/YcRbvwgH

Where should i start to look?

**Comment by garfield69** [comment]
I believe that you can ditch the mono flavour of Jackett in favour of the .core net version.
follow the install as a service notes from https://github.com/Jackett/Jackett#install-on-linux-amdx64
there was an issue early on with ubuntu 19.04, #5179 back in May 2019, but that should be fixed.
