### ISSUE TITLE
[Downloadville] Wrong torrent sizes returned

### ISSUE THREAD

**Issue by SuissoNaBisso9** [Jackett/Jackett#7121]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

**Jackett Version**: 0.12.1701.0

### Description

When searching for a media on Radarr or Sonarr (v3) through Torznab indexers from Jackett, results from Downloadville.net tracker are returned with a wrong size usually over 200 GB (for a movie and up to 60 GB for a tv episode) which prevent Radarr / Sonarr to grab it as it's over size limit depending on user settings.

### Screenshots

Sonarr screenshot : https://ibb.co/F8N1vJv
Radarr Screenshot : https://ibb.co/7tjTRkd

**Comment by garfield69** [comment]
Thank you for spotting this.
The downloadville site uses the comma for decimals,  such as 2,67 GB
but the indexer has not been set up for this, so the value extracted ends up being 267 GB !!
I will add the required support shortly.

**Comment by SuissoNaBisso9** [comment]
Perfect thank you !

**Comment by garfield69** [comment]
jackett 0.12.1732
