### ISSUE TITLE
[REQ] p2pelite

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#7126]
p2pelite is a private e-learning tracker, the registration is [currently open](https://p2pelite.com/signup.php).

**Comment by garfield69** [comment]
Jackett 0.12.1811

**Comment by garfield69** [comment]
https://p2pelite.com/ returning DNS_PROBE_FINISHED_NXDOMAIN
domain not found, just me?

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
i am seeing 
![image](https://user-images.githubusercontent.com/6933240/132749006-b161f2d3-5a69-4cfb-9458-fc6c6a19af35.png)

**Comment by ilike2burnthing** [comment]
Login page page is down, seemingly I was already signed in.

**Comment by garfield69** [comment]
long life cookies?

**Comment by ilike2burnthing** [comment]
Seemingly so, as I don't think I've been on the site since I set up the account and downloaded a few torrents.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://p2pelite.com/ returns DNS_PROBE_FINISHED_NXDOMAIN (DNS domain not found)

**Comment by garfield69** [comment]
v0.20.2486
