### ISSUE TITLE
[REQ] DC++ as a feature or some guidance please?

### ISSUE THREAD

**Issue by AtariBaby** [Jackett/Jackett#7127]
ver. .012.1701 and windows 10 pro 1903

I have been thinking lately it would be awesome to have an "indexer simulator" similar to jackett, but for dc++. 

Is there any interest in adding that to jackett? I am tech savvy but no coder or developer. How hard is it to learn how to do this? Any response or suggestions will be greatly appreciated.

**Comment by garfield69** [comment]
>it would be awesome to have an "indexer simulator" similar to jackett, but for dc++.

not sure I understand what an _indexer simulator_ is.
Jackett works as a proxy server: it translates queries from apps (Sonarr, Radarr, SickRage, CouchPotato, Mylar, Lidarr, DuckieTV, qBittorrent, Nefarious etc.) into tracker-site-specific http queries, parses the html response, then sends results back to the requesting software. This allows for getting recent uploads (like RSS) and performing searches. Jackett is a single repository of maintained indexer scraping & translation logic - removing the burden from other apps.
This is what the Jackett indexers are, a method to search and process torrent/magnet lists from other web sites, and return results to either the Jackett dashboard or apps that interface via Jackett's torznab API.

Assuming that DC++ is a file transfer app, it seems unlikely that DC++ can produce torrent/magnet lists in response to search queries (like torrent tracker web sites do), and so we could not create an DC++ indexer for Jackett.

In all probability, you have the purpose of Jackett backwards. 
You are more likely to have DC++ submit queries to Jackett (like qBitTorrent can be made to do) and have Jackett's list of magnets returned back to DC++ after Jackett scrapes the data off web sites using the indexers that you have enabled on Jackett.
You are not likely to add an indexer to Jackett to fetch magnet lists off DC++ for other apps to use (or for a human to be using the jackett dashboard to do searches from a DC++ indexer).

Given the above, there seems little point answering the remaining two questions you raised in your post.

**Comment by AtariBaby** [comment]
Thank you for that very logical and detailed response. I understand better now. Looks like it’s back to the drawing board for me.

**Comment by cadatoiva** [comment]
I'm just curious, but looking at the DC++ website, it looks like it's basically an open source clone of LimeWire/Morpheus, is that correct?

**Comment by AtariBaby** [comment]
> I'm just curious, but looking at the DC++ website, it looks like it's basically an open source clone of LimeWire/Morpheus, is that correct?

Thank you for asking. I am just starting to think about this and I’m not sure. It is decentralized as perhaps they were, with each user designating folders to share with everyone else on a hub. The interface is very much like IRC— you see everyone in a room and can chat publicly and privately. Then there is a search feature, and in the bottom of the search you see your downloads and others’ uploading from you, when active.

**Comment by cadatoiva** [comment]
The interface, your description, and the Wikipedia pages on the client and protocol all suggest it is similar in format, but standardized and brought to open source. There's extra features, like the chat, but it's essentially the same from a raw file sharing viewpoint.

With that said, I second that Jackett isn't going to be useful in any way with this client. We won't be able to parse for searching through the DC++ files made available to you, and DC++ will be entirely unable to use our results to add downloads into it. It was a good thought though, and I wish you luck on finding what you're looking for.

**Comment by AtariBaby** [comment]
@cadatoiva Cadatovia I don’t know how to contact you so I’ll ask here.

How would I get started? I need to design before I code, right?  I figure first I need to understand how services like Sonarr and Mylar search and interact, right? Would I read debug logs to understand? How did you guys get started creating Jackett? I hope the creator of this repository will forgive me for continuing on this topic.
