### ISSUE TITLE
2 Fast 4 You torrent age appearing wrong on Radarr / Sonarr

### ISSUE THREAD

**Issue by SuissoNaBisso9** [Jackett/Jackett#7128]
**Jackett Version**: 0.12.1732.0

### Description

For the tracker 2 Fast 4 You, all results that are returned into Radarr / Sonarr via Torznab have an issue with the age of torrent. Any results coming from this tracker would always have an age of 0 minutes. 
So if you have RAdarr / Sonarr settings to avoid torrents that were just published, this will prevent you from downloading from this tracker.

### Screenshots

https://ibb.co/vDn9VcT

**Comment by garfield69** [comment]
there is nothing that can be done about this.
the 2F4Y site's torrents page does not have the created/uploaded date in its primary search results table.
And we are not going to fetch the details page for every torrent listed in the results to get the date, as this would generate up to 100 http get requests, which would most likely get you blacklisted as a DDoS attacker.
the default for Jackett in this case is to provide the date **now** i.e. 0 minutes.
