### ISSUE TITLE
[REQ] EggMeOn

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#7133]
This is a new private tracker, the registration is currently closed. Invites are giving by the staff.

https://www.eggmeon.xyz/

**Comment by dimqua** [comment]
@garfield69 could you give an address where to send invite?

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by garfield69** [comment]
registration and login successful. thank you.

**Comment by garfield69** [comment]
Jackett 0.13.127

**Comment by garfield69** [comment]
well that did not last long.
https://eggmeon.xyz/ returning ERR_CONNECTION_REFUSED
and http://eggmeon.xyz/ returns
```
404 Not Found
nginx/1.15.8
```
just me, or is the site gone, broken or moved to a new domain?

**Comment by dimqua** [comment]
There are some issues with the site. Should be fixed ASAP.

**Comment by garfield69** [comment]
EggMeOn have migrated to the unit3d 2.2.7 engine.
unfortunately the site does not recognise my prior credentials, or my email for user/pswd recovery,
and you cannot register as it is not open for registration.
@HDVinnie  do you know if this is just an oversight by admin or a problem or deliberate?

**Comment by dimqua** [comment]
>EggMeOn is now closed for good due to the malicious and false allegations on r/trackers
