### ISSUE TITLE
[Channelx] Login failed: No form found on https://channelx.online/login using form selector form (Config)

### ISSUE THREAD

**Issue by Absolute-Garbage** [Jackett/Jackett#7150]
https://i.imgur.com/SHDnlkY.png

**Comment by garfield69** [comment]
channelx have changed domain. af6c7b530b933df9557c4108be3f4244fe18a778 will get publish in due course.
in the mean time https://github.com/Jackett/Jackett/issues/7131#issuecomment-583712621

**Comment by garfield69** [comment]
0.12.1765
