### ISSUE TITLE
[corsarored] {"ok":false,"err":"MongoError: Topology was destroyed"}

### ISSUE THREAD

**Issue by alberto-bracci** [Jackett/Jackett#7151]
### Environment

**OS**: Manjaro Linux

**Jackett Version**: 0.12.1746.0

I am trying to add the indexer CORSARO.RED but I receive the following error:

[corsarored] {"ok":false,"err":"MongoError: Topology was destroyed"}

Is it something due to my system or jackett? Every other indexer seems to work fine.

**Comment by garfield69** [comment]
duplicate #7061 
That is an internal error in the website. They have to fix that.
