### ISSUE TITLE
Feature Request - Individual proxies per tracker

### ISSUE THREAD

**Issue by Goob00000** [Jackett/Jackett#7168]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Description

Please add the ability to add specific proxies for each tracker. Some trackers at times are only accessible via tor, anonymization proxy or other means.  Oh yeh and Jackett is awesome.

**Comment by Goob00000** [comment]
This seems different than the other requests

**Comment by YurikaL** [comment]
A similar idea in another issue: https://github.com/Jackett/Jackett/issues/2539#issuecomment-398665780
