### ISSUE TITLE
TSC Tracker Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by mzlumin** [Jackett/Jackett#717]
Hey @kaso17 

i just tried the new release with the TSC Tacker included, unfortunately it seems that there is no result getting back.

Log can be found here:

[https://gist.githubusercontent.com/mzlumin/d8db7057168b2be030fe2156488e1ab5/raw/53e0140949a14a5e1d7a2359d69ec73036aa8389/TSC](url)

Short Information from the Log:

`11-21 07:31:26 Info Starting Jackett 0.7.618.0 
`

`11-21 07:42:59 Debug UnixLibCurlWebClient:GetBytes(Url:https://tsctracker.net/browse.php?&search=&incldead=1&orderby=added&sort=desc)
11-21 07:43:01 Debug UnixLibCurlWebClient:GetBytes Returning OK => 350461 bytes
11-21 07:43:01 Info Found 0 releases from Torrent Sector Crew
11-21 07:43:01 Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker
  at Jackett.Services.IndexerManagerService+<TestIndexer>c__async0.MoveNext () [0x000fa] in <3bd215b3065e455389731ff3bc6a55d9>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <8f2c484307284b51944a1a13a14c0266>:0
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
  at Jackett.Controllers.AdminController+<Test>c__async5.MoveNext () [0x00108] in <3bd215b3065e455389731ff3bc6a55d9>:0
11-21 07:43:01 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]'
System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]'
`

The Profile is set to have 100 releases shown, as well as all categories on the browse page are ticked.

![unbenannt](https://cloud.githubusercontent.com/assets/20663710/20473102/9498ebc2-afbe-11e6-8f19-acce600d2ed4.JPG)

Is there anything to have an eye on or needs to be set ?

Thanks and cheers

**Comment by mzlumin** [comment]
Additional INformation, i have also tried all 3 Layouts (Pop UP, Table, Classic) makes unfortnately no change.

**Comment by kaso17** [comment]
Layout must be set to Classic. I've no categories set but that shouldn't make a difference.
Please provide a log with tracing enabled (-t option).

**Comment by mzlumin** [comment]
Log is already attached in first post with debug enabled, not sure why the link is not working...

Please find it here:

[https://gist.githubusercontent.com/mzlumin/d8db7057168b2be030fe2156488e1ab5/raw/53e0140949a14a5e1d7a2359d69ec73036aa8389/TSC](url)

I will try again using Classic Mode once

**Comment by kaso17** [comment]
ok, sorry, please send a copy of the html code of "https://tsctracker.net/browse.php?&search=&incldead=1&orderby=added&sort=desc"

**Comment by mzlumin** [comment]
What you mean with that ? The Source Code of the Website or any special output ?

**Comment by mzlumin** [comment]
This is the complete html page from your requested page:

`https://gist.githubusercontent.com/mzlumin/5e2c8d9b29954b96e3d042683b167445/raw/f3f4bc09c65566dfa8b84ec4a71653197291499f/TSC-request`

**Comment by kaso17** [comment]
Try enabling "Empfohlene Torrents in der Liste anzeigen" in your profile, that should make it work.
With the next Jackett release you can disable it again.

**Comment by mzlumin** [comment]
Damn you re quick ?!
Not thought about the suggested torrents, thanks a lot Kaso!

**Comment by mzlumin** [comment]
Confirmed, with classic layout and 'suggested torrents' enabled it works!
Thankns a lot!
