### ISSUE TITLE
[REQ] Add tags to trackers and allow searching / sorting based on the tags

### ISSUE THREAD

**Issue by Goob00000** [Jackett/Jackett#7170]
### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

Add the ability to add arbitrary tags to trackers for sorting and organization. For example, ratiosite, lowratio, goodratio so the user could determine where to steer a search or automated download based on this criteria. Premium trackers with stringent ratio requirements might be a last resort for example.

The tag could also be used to disable the tracker or skip it in a search.

**Comment by ngosang** [comment]
I would like to have this but for other use case. I have several trackers enabled with different languages (English, Spanish and French) and I will group them by language (with tags). I will search only in trackers with English tag/language.

**Comment by ilike2burnthing** [comment]
[v0.18.7](https://github.com/Jackett/Jackett/releases/tag/v0.18.7) - tags can now be added to indexers to group them together however you want.

You can then filter indexers for searches by these tags. Indexers can also be filtered by type (public, semi-private, and private). The API can also filter by language.

See more info here - https://github.com/Jackett/Jackett#filter-indexers
