### ISSUE TITLE
[HD-Torrents] Search not working

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7176]
Searching HD-Torrents takes an unusually long amount of time and returns no results. The website & tracker both work fine. Enhanced log attached.

### Environment

**OS**: Windows 10 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.12.1765.0

**Last Working Jackett Version**: Not sure, but the error started within the past week or so

### Logged Error Messages

No specific error message is displayed. 

[log.txt](https://github.com/Jackett/Jackett/files/4179081/log.txt)

**Comment by cadatoiva** [comment]
Looks like a network connection issue. If your jackett is running through a proxy or VPN then that's the issue.

**Comment by RoloSoze** [comment]
> 
> 
> Looks like a network connection issue. If your jackett is running through a proxy or VPN then that's the issue.

I don't use a VPN or a proxy, and all my other trackers are working fine.

**Comment by RoloSoze** [comment]
Solved! I changed the URL to one of the other available alternatives and it now works fine! Strange because I tried doing that but it didn't work initially!
