### ISSUE TITLE
[immortuos] Exception (immortuos): Login failed: Selector "a[href$="/logout"]" didn't match: Parse error

### ISSUE THREAD

**Issue by FilmjunkieGF** [Jackett/Jackett#7177]
**OS**: Linux

**Jackett Version**: Version 0.12.1765.0

### Description
When testing the tracker Immortuos.life I get this error:
An error occured while testing this indexer
Exception (immortuos): Login failed: Selector "a[href$="/logout"]" didn't match: Parse error

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by FilmjunkieGF** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4185351/log.txt)

**Comment by garfield69** [comment]
I think the log shows that you are logging into the forum (it uses the MyBB engine) rather that the expected tracker (which was using the unit3d engine when the Jackett indexer was built in Aug 2019).

I recall running into registration issues with this site with #5815 and you helped me out with #5588

can you log in via your browser and confirm your account on the site is still valid and that you are able to access the tracker and not the forum?

**Comment by fnk93** [comment]
If I remember correctly, they changed server location.
As of now, whenever I'm trying to log into the tracker, I'm redirected to the forum (via current url).
Removing the "www" got me to the correct login page.

Will submit a PR fixing this shortly.

**Comment by garfield69** [comment]
Jackett 0.12.1804
