### ISSUE TITLE
[yts]  An error occured while configuring this indexer Parse error: Unexpected character encountered while parsing number: %. Path 'width', line 1, position 11.

### ISSUE THREAD

**Issue by Crackpotpower56** [Jackett/Jackett#7184]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:unriad

**.Net Runtime**: [Mono/.Net-Core/.Net-Framework]

**.Net Version**:

**Jackett Version**:0.12.1779.0

**Last Working Jackett Version**:

### Description

Add YTS

### Logged Error Messages

 An error occured while configuring this indexer
Parse error: Unexpected character encountered while parsing number: %. Path 'width', line 1, position 11.

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
works for me.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by Crackpotpower56** [comment]
System.Exception: Parse error
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing number: %. Path 'width', line 1, position 11.
   at Newtonsoft.Json.JsonTextReader.ReadNumberCharIntoBuffer(Char currentChar, Int32 charPos)
   at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Jackett.Common.Indexers.Yts.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/yts.cs:line 101
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 849
   at Jackett.Common.Indexers.Yts.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/yts.cs:line 210
   at Jackett.Common.Indexers.Yts.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/yts.cs:line 76
   at Jackett.Common.Indexers.Yts.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/yts.cs:line 64
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70

**Comment by garfield69** [comment]
the reason I asked for the **full** enhanved log is that I was hoping to see info prior to the stack dump (which on its own is of little use in diagnosing your problem).
are you telling me there is nothing prior to this error message that can be useful to us?

**Comment by Crackpotpower56** [comment]
this poped up but i have tried reinstalling it and it still docent work
Error on 20200210195150 for YTS.txtNewtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing number: %. Path 'width', line 1, position 11.
   at Newtonsoft.Json.JsonTextReader.ReadNumberCharIntoBuffer(Char currentChar, Int32 charPos)
   at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Jackett.Common.Indexers.Yts.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/yts.cs:line 101




<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif; font-size: 100%;}
    h1 {font-size: 1.5em; color: #404040; text-align: center;}
    p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 20px;}
    @-webkit-keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }
    @keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }
    .bubbles { background-color: #404040; width:15px; height: 15px; margin:2px; border-radius:100%; -webkit-animation:bubbles 0.6s 0.07s infinite ease-in-out; animation:bubbles 0.6s 0.07s infinite ease-in-out; -webkit-animation-fill-mode:both; animation-fill-mode:both; display:inline-block; }
  </style>

    <script type="text/javascript">
  //<![CDATA[
  (function(){
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      var a = document.getElementById('cf-content');a.style.display = 'block';
      setTimeout(function(){
        var s,t,o,p,b,r,e,a,k,i,n,g,f, tHDfsMt={"FK":+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]))};
        g = String.fromCharCode;
        o = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
        e = function(s) {
          s += "==".slice(2 - (s.length & 3));
          var bm, r = "", r1, r2, i = 0;
          for (; i < s.length;) {
              bm = o.indexOf(s.charAt(i++)) << 18 | o.indexOf(s.charAt(i++)) << 12
                      | (r1 = o.indexOf(s.charAt(i++))) << 6 | (r2 = o.indexOf(s.charAt(i++)));
              r += r1 === 64 ? g(bm >> 16 & 255)
                      : r2 === 64 ? g(bm >> 16 & 255, bm >> 8 & 255)
                      : g(bm >> 16 & 255, bm >> 8 & 255, bm & 255);
          }
          return r;
        };
        t = document.createElement('div');
        t.innerHTML="<a href='/'>x</a>";
        t = t.firstChild.href;r = t.match(/https?:\/\//)[0];
        t = t.substr(r.length); t = t.substr(0,t.length-1); 
        a = document.getElementById('jschl-answer');
        f = document.getElementById('challenge-form');
        ;tHDfsMt.FK*=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![])+(+[])+(+[])+(+!![])+(+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));tHDfsMt.FK-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(+!![]))/+((!+[]+!![]+[])+(!+[]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]));tHDfsMt.FK*=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+!![]+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));a.value = (+tHDfsMt.FK + t.length).toFixed(10); '; 121'
        f.action += location.hash;
        f.submit();
      }, 4000);
    }, false);
  })();
  //]]>
</script>


</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1></noscript>
  <div id="cf-content" style="display:none">
    
    <div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> yts.mx.</h1>
    
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>
  </div>
   
  <form id="challenge-form" action="/api/v2/list_movies.json?sort=date_added&amp;limit=50&amp;__cf_chl_jschl_tk__=cbb356fc568bc01a6b5b3d7ce741a1a40698e0c7-1581393110-0-AeaxFj-wK3ANdNixLkpkR1SRfUpKiF-fOhR0UaI5kZTIC7kOrvHYCYfX3y81PZND7O0X2nXpaYah19YABMFaJ4ZdcKbAcdYFREttbSZZMyUMjmm8novLJD9udN_blsBJPxEP7oC4ZOeOdK-bRdkyUX-4-cuY3mMY1yFVuIlXfAvkjXkGqKBmAUKiHtIu8jJKBnmbBRRDvBr0c2V8T-0fe_OcCn11wpTQQ01g7jn35azD5llJyDOpGxP7fLCNqbMVaz7a6QxKuiZPQnRMHggHswvutWbnzeD7KoZIsaTcRyKh5AQdXyKldzVkG0oi3YB2TefVhq8JKtzKJaGd4RLqbyE" method="POST" enctype="application/x-www-form-urlencoded">
    <input type="hidden" name="r" value="72465c939778b6bafb404c18716e703c0a60294a-1581393110-0-AeqznjqsCEuMv9NQqgWFQJAixiHUvnSEZSZ3S48aL/AhesSnZjKbIeMloZca4WYKsmQuclKljeoFnRdyabb1LMrZKbxE3fMSkj4A1Fnf/K+xJ9LAolZIk9U4RwWNVZK7mrobAfIJY3E/QVxAjX1joP5xNkRGrJA430E8fOca+7cATHxRfTyDDQbzVyNdqhRzle8NKYNP5/Dgc/xMSKN+b8RpbBAJ1ePtxmnQ4ZRNyt0y4tvLsTSWX8J50VNPohWHXzZ0z368LngfaTe+51H3CzVBwXk7X1KY1Wxf50TzKhwnOmXz0p1fYcIf82H5nTVr3u1LGD/ZHOPaIx7zHNOrZGUg93l3yn2Mdyc7I1DZNNe5PDWQqWr5fYbADyDJeahCv8ROp0dePBmRkylyKxL2o1gDY0Gmjf90fdfD5Ot5Gm/NpP6A0XWn5C6vKRDEe36oY5q6tK9YTw7TShkQsKEomtfWDKPjqdMWpugQRhF5hxZu9IsTxyHgATIpujiEuyRpSqiWtrBofxUCpGqkHhAZaJobFGgd2ST5uAPxDPKcFpo/yVxl4VZBKT0esu+84fR1RMVpyMcLasq7OQRqzpvx17bs+mDJgVVetHqmnycG9iFNtEbQuw/jkpTB+nYdkuPHtg527uarRZeaN73H2NyiTFppgDLicZDnBU0BxHEXcvTR2Za6/fmJxOTgRRQLZKCsuF0ctLBIkyjTwAKWUh/peNhfeWvjGB6Euq7y2haVNaxd95mGX3bcyusgnMFH0HkCOn/q5GuP9l4f2HVCSSGM4Hfc8WL0dPOr/wUeFiu+WjeG++lFEjo35hW+zktu8I0g6zd6HWdbQxej2Q4RNtlN4N+VNyBfqG4JghmqDpc5GlO8IHuT0/6VdrbsE0FYoLanObqoPWdMlE/ThsjxZXuDq0SAMKvaB5fN9vmFifyI70vMhr/hOr2jKl1st2Ul4rMUnhd856isAibVDtNo6pA2ZCASjhWTHv0D7OVbOBX8oCSEmCIfiHoIhdq83YJ5lIOD/zn0NZYo+sn/OYKwUECDjc4rp4Ncwuye+oH1E04Orb9T7a07w6K+Bms1yajlYWB9mEQzDeON0QBoPG+4sJdvphU1mXRZFVIc/zECOsZCqj4s1Eo/kQYyKmZIVXyNw1YjobbsXrGo7YrRrx/t5pulQVkNUS/PFRjwKFOGxGg7cSqmPMf29BZTVbhDWQsJn2Dpn6E0g6FhaeXkXK/XtXw5B0nlRU0bmHe3FhVyiNOGkWai3l5ZL0+rRmyB2WDDS9PXIwnxdl/OafuUyOkS4PLZZOs5M9Skh/ajHNClhaSnTqTQ/95UVkd8rirWtzo3kUGSVSjUzfE1kRCm1+lGPdFfksBROS7AqXTUFXktkZme4EvnTXlXgYYBNkaXB7ImffLr1288zYEdrxWjWt2wLrFpm9HA8dAK3iAcWwRx6UTqSs/xNr9HmSF4NNGGzAtYuZbeIw=="></input>
    <input type="hidden" name="jschl_vc" value="2ab55c87298bdf0b01382f9bce7a2416"/>
    <input type="hidden" name="pass" value="1581393114.836-EMMckiGF1D"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
  
</div>

          
          <div class="attribution">
            <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=iuam" target="_blank" style="font-size: 12px;">DDoS protection by Cloudflare</a>
            <br>
            Ray ID: 56335ddebcfced13
          </div>
      </td>
     
    </tr>
  </table>
</body>
</html>

**Comment by Crackpotpower56** [comment]
[New Text Document (2).txt](https://github.com/Jackett/Jackett/files/4184076/New.Text.Document.2.txt)

**Comment by Crackpotpower56** [comment]
just found that it only fails through VPN

**Comment by garfield69** [comment]
The jackett YTS indexer uses the web site's API to gets a JSON response 
so jackett sends https://yts.mx/api/v2/list_movies.json
and expects to see something like this:
```json
{"status":"ok","status_message":"Query was successful","data":{"movie_count":14924,"limit":20,"page_number":1,"movies":[{"id":15337,"url":"https:\/\/yts.mx\/movie\/frozen-ii-2019","imdb_code":"tt4520988","title":"Frozen II","title_english":"Frozen II","title_long":"Frozen II (2019)","slug":"frozen-ii-2019","year":2019,"rating":7.2,"runtime":103,"genres":["Adventure","Animation","Comedy","Family","Fantasy","Musical"],"summary":"blahblahbla","yt_trailer_code":"eSLe4HuKuK0","language":"English","mpa_rating":"PG","background_image":"https:\/\/yts.mx\/assets\/images\/movies\/frozen_ii_2019\/background.jpg","background_image_original":"https:\/\/yts.mx\/assets\/images\/movies\/frozen_ii_2019\/background.jpg","small_cover_image":"https:\/\/yts.mx\/assets\/images\/movies\/frozen_ii_2019\/small-cover.jpg","medium_cover_image":"https:\/\/yts.mx\/assets\/images\/movies\/frozen_ii_2019\/medium-cover.jpg","large_cover_image":"https:\/\/yts.mx\/assets\/images\/movies\/frozen_ii_2019\/large-cover.jpg","state":"ok","torrents":[{"url":"https:\/\/yts.mx\/torrent\/download\/1E4AB093500633810EC47CCB097FA70D0B288A4F","hash":"1E4AB093500633810EC47CCB097FA70D0B288A4F","quality":"720p","type":"web","seeds":4516,"peers":5276,"size":"954.78 MB","size_bytes":1001159393,"date_uploaded":"2020-02-10 21:16:35","date_uploaded_unix":1581365795},{"url":"https:\/\/yts.mx\/torrent\/download\/91749F30BCA789524E161FC159931FC4EE554BF0","hash":"91749F30BCA789524E161FC159931FC4EE554BF0","quality":"1080p","type":"web","seeds":4301,"peers":8132,"size":"1.85 GB","size_bytes":1986422374,"date_uploaded":"2020-02-10 22:45:59","date_uploaded_unix":1581371159}],"date_uploaded":"2020-02-10 21:16:35","date_uploaded_unix":1581365795},
[etc...etc...]
```

but because your VPN Proxy IP address is in the address block of a currently blacklisted group, YTS is currently doing a cloudflare anti-DDoS check.

If you intend to continue using VPN with YTS you will need to try to change your VPN settings to select a different IP area so you don't get the challenge.

in any case this has nothing to do with Jackett and there is little Jackett can do for you in this instance.
