### ISSUE TITLE
[torrentday] Your cookie did not work: An error occurred while sending the request. (Config)

### ISSUE THREAD

**Issue by meskafonas** [Jackett/Jackett#7185]
None of www.torrentday.com indexers work. I have checked my cookie 3 times.

**OS**: windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: newest

**Last Working Jackett Version**: i just installed newest

**Are you using a proxy or VPN?** [no]

**Comment by garfield69** [comment]
is this the first time you are adding the TorrentDay indexer to Jackett?
try following these instructions for getting the cookie, just to be sure you are fetching the correct string.
1. Login to the TorrentDay tracker with your browser using the **Site Link** address you have chosen to use from the Jackett TorrentDay indexer config
2. Open the **DevTools** panel by pressing **F12**
3. Select the **Network** tab
4. Click on the **Doc** button
5. Refresh the page by pressing **F5**
6. Select the **Headers** tab
7. Find 'cookie:' in the **Request Headers** section
8. Select and Copy the whole cookie string (everything after the `cookie: `)
9. In the TorrentDay Jackett indexer config cookie box Delete anything already there
10. Paste your copied cookie string from (8)
11 click **OKAY**
