### ISSUE TITLE
[tvchaosuk] Exception (tvchaosuk): Login failed: No form found on https://tvchaosuk.com/login using form selector form: Parse error (Test)

### ISSUE THREAD

**Issue by EliRobinson** [Jackett/Jackett#7194]
# Environment

**OS**:
Synology DSM 6.2.2-24922 Update 4

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
Mono

**.Net Version**:
5.18.0.240

**Jackett Version**:
0.12.1795.0

**Last Working Jackett Version**:
Same

**Are you using a proxy or VPN?** [yes/no]
No

### Description
Try to test a connection to TVChaosUK and it fails saying `Exception (tvchaosuk): Login failed: No form found on https://tvchaosuk.com/login using form selector form: Parse error`

This seems to happen intermittently, as I re-tested 10-15 times and one of them finally went through.

### Logged Error Messages
```
Exception (tvchaosuk): Login failed: No form found on https://tvchaosuk.com/login using form selector form: Parse error
```

[Make sure you attach the full logs with your personal information removed in case we need more information]

**Comment by EliRobinson** [comment]
This issue isn't a duplicate as I've actually provided information unlike the previous posted on #7193.

**Comment by garfield69** [comment]
works for me.
Please provide the **full enhanced log** file the next time you get the issue.

1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test. if you get the failure, then
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by phever** [comment]
Also seeing this issue, thought I could contribute some logs.
[log.txt](https://github.com/Jackett/Jackett/files/4196466/log.txt)

**Comment by garfield69** [comment]
@phever your log is full of `Redirecting to https://tvchaosuk.com/login` messages.

Please confirm that your login credentials are valid by logging onto the web site with your browser.
while you are there, check that your ratio is good, and that you do not have any outstanding alerts, notices or unread mail.
then on Jackett, use the trashbin button to delete your active tvchaosuk indexer config, and add a fresh one from the add-indexer page.
Enter your username and password (even if they appear filled in) and see if that works.
let me know how you go.

**Comment by phever** [comment]
I feel like an idiot for not trying that first, thank you. **It connected fine after re-adding it.** Their site is going through a lot of changes right now and I assumed something was wrong.

Thank you so much @garfield69

**Comment by rrrevin** [comment]
They are still having loads of "load" issues on the site. CloudFlare, tracker, server timeouts, etc.
They are getting closer to solving things.
