### ISSUE TITLE
[newrealworld] Exception (newrealworld): Input string was not in a correct format.: Parse error (Test)

### ISSUE THREAD

**Issue by loibi93** [Jackett/Jackett#7195]
### Environment

**OS**: Debian 9

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Don't know, using linuxserver.io docker image

**.Net Version**: Don't know, using linuxserver.io docker image

**Jackett Version**: 0.12.1795.0

**Last Working Jackett Version**: Not sure but issue appeared since about a month or so.

**Are you using a proxy or VPN?** [yes/no] yes (Traefik)

### Description
Requesting anything from newrealworld tracker yields no result/error when pressing the test button.

### Logged Error Messages

Relevant lines:
2020-02-12 19:13:33.1120 Error Jackett.Common.IndexerException: Exception (newrealworld): Input string was not in a correct format.
 ---> System.Exception: Parse error
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Jackett.Common.Utils.ParseUtil.CoerceFloat(String str) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/ParseUtil.cs:line 47
   at Jackett.Common.Models.ReleaseInfo.GetBytes(String str) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ReleaseInfo.cs:line 86
   at Jackett.Common.Indexers.NewRealWorld.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/NewRealWorld.cs:line 197

Full Log: https://pastebin.com/K4gGK865

**Comment by garfield69** [comment]
I don't have an account on this site so research and fixing is difficult.
but from what I can tell looking at the code and the html you provided in the log, it appears that the indexer is looking for `table.testtable`, but the site is now generating `table.testtable2` among other changes.
to any Jackett c# devs:  any of you have an account on this site?

**Comment by loibi93** [comment]
If it is any help to you I can provide you with some more test pages. If no one is able to fix it I may docit myself, currently I just do not have the time, sorry :)

**Comment by garfield69** [comment]
the most efficient way to fix this is with an account. Using static test pages is a hit and miss affair. I often find it takes me several live debugging test after I've made changes to an indexer, to pick up all the bugs from an update.

If you send an invite to garfieldsixtynine @ gmail.com I should be able to sort it out.

**Comment by loibi93** [comment]
I would love to, but I do not have any Invitecodes currently :(

I hope I have time this weekend, maybe I can fix it myself :)

**Comment by garfield69** [comment]
Jackett pre-release 0.13.122
