### ISSUE TITLE
[3evils] Login Failed, got redirected.

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#7205]
I can't login with a website either, I always redirected to a blank webpage: https://www.3evils.com/takelogin.php And nothing happen.

**Comment by garfield69** [comment]
the 3evils indexer works for me.
the correct **Site Link** is `https://www.3evils.com/`

use your browser to access https://www.3evils.com/ and check your account credentials, and ensure that your ratio is good and that you have no outstanding alerts, notices or unread emails.
then on your Jackett dashboard use the trashbin to delete your 3evils config and add one afresh from the add-indexer page. Enter your credentials (even if the appear pre-loaded) and click OKAY.
let me know you go.
