### ISSUE TITLE
[REQ] Shellife

### ISSUE THREAD

**Issue by jaredbidlow** [Jackett/Jackett#721]
Music tracker 
https://shellife.eu

**Comment by kaso17** [comment]
Added with 2baf6453517b7e621229ccf4e5d72c937b51b78e

**Comment by ilike2burnthing** [comment]
https://shellife.eu/ - ERR_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

using TLS 1.0 only, not sure if that creates any issues for Jackett

**Comment by ilike2burnthing** [comment]
https://shellife.eu/ - ERR_CONNECTION_TIMED_OUT
