### ISSUE TITLE
[film-paleis] Error: Beste leden van Film Paleis,We zijn aan het uitbreiden en dringend op zoek naar creatieve leden.Specifiek als het gaat om het aanmaken van avatars middels photoshop.Bij een nieuwe achtergrond horen namelijk ook mooie ava's bij onze users.Dus denk je een waardevolle aanwinst te kunnen zijn, meld je dan bij Administrator VENOM.In overleg krijg je dan ook een speciaal plekje op onze stafflijst als Designer.En uiteraard per creatie 1 kredietpunt die je kan gebruiken voor donateurschap.Dus meld je aan en wordt een waardevolle aanwinst in ons superteam! VENOM 

### ISSUE THREAD

**Issue by thoogveldHU** [Jackett/Jackett#7216]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: unraid

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 

**Jackett Version**: latest

**Last Working Jackett Version**: none

**Are you using a proxy or VPN?** [yes/no] tried both

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

1. Add tracker Film-Paleis
2. Get error.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Hah!
looks like the site has added a promotion that the indexer login is trapping as an error.
I'll try to refine the login error trap to avoid this issue.

**Comment by thoogveldHU** [comment]
That was fast, great!

**Comment by garfield69** [comment]
Jackett pre-release 0.13.122
