### ISSUE TITLE
YTS unable to add

### ISSUE THREAD

**Issue by melbasuonyy** [Jackett/Jackett#7222]
hi
when I'm adding YTS.mx to indexers nothing happening and log show this line only

On attempt 1 checking for results from YTS: The operation was canceled.

using latest release was working perfect earlier (ONLY YTS others are ok)

**Comment by garfield69** [comment]
works for me.
the YTS indexer uses the website's API. what happens when you use a browser on the same machine that is running jackett, to access https://yts.mx/api/v2/list_movies.json ?
you should get something like
```json
{"status":"ok","status_message":"Query was successful","data":{"movie_count":14983,"limit":20,"page_number":1,"movies":[{"id":15381,"url":"https:\/\/yts.mx\/movie\/mickey-and-the-bear-2019","imdb_code":"tt9614440","title":
[etc etc etc]
```
The enhanced log may yield additional information, so 

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by melbasuonyy** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4208759/log.txt)

getting same result
{"status":"ok","status_message":"Query was successful","data":{"movie_count":14983,"limit":20,"page_number":1,"movies":[{"id":15381,"url":"https:\/\/yts.mx\/movie\/mickey-and-the-bear-2019","imdb_code":"tt9614440","title":

**Comment by garfield69** [comment]
the log does not shed any light on the issue.
which jackett build are you using (windows, amdx64, arm32, arm64, mono, docker, other)?
on which platform?
which specific version of jackett (see bottom of the jackett dashboard)?

**Comment by melbasuonyy** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4208788/log.txt)

check the new log file (using Jackett on windows) and tried also synology (using latest version)Jackett Version 0.12.1815.0

**Comment by garfield69** [comment]
i can see the cancelled error in the log, but unfortunately no explanation for the cause :-(

turn on the **update to pre-release** checkbox on your jackett dashboard, and click on the **apply server settings** button.
after the refresh then click on the **check for updates** button to upgrade to 0.13.122
lets see if that version works any better (0.12 on windows is the FullFramework variant, and 0.13 is the CoreWindows variant).

**Comment by melbasuonyy** [comment]
same issue 
only one line log :(
2020-02-15 21:35:26.6494 Error On attempt 1 checking for results from YTS: The operation was canceled.

**Comment by melbasuonyy** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4208818/log.txt)

**Comment by melbasuonyy** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4208825/log.txt)

**Comment by garfield69** [comment]
then I do not know how to resolve this one.
as I said before, YTS works for me on Windows, Ubuntu and Mojave macos using the latest 0.13.122

are you using a proxy or vpn with jackett?

**Comment by melbasuonyy** [comment]
No website is not blocked by ISP 😔

**Comment by garfield69** [comment]
I'd welcome input from any volunteer with a clue to how to progress this ticket. I'm out of ideas.

**Comment by melbasuonyy** [comment]
Is it allowed to share yts.json from ur side to added for time being?

**Comment by garfield69** [comment]
use a plain text editor and paste the following and save to `C:\ProgramData\Jackett\Indexers\yts.json`
```json
[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://yts.mx/"
  }
]
```
then restart the jackett service to load.

**Comment by melbasuonyy** [comment]
you can close the ticket now as it's working back may be was something in the tracker it self
Thanks alot

**Comment by sbaird02** [comment]
Melba what ended up being the resolution? I am also having this exact issue with yts on windows jackett and have not been able to resolve. Running latest jackett build. Did you follow Garfield's last step of adding content directly to json file?

**Comment by melbasuonyy** [comment]
it worked next day it was issue from YTS it self
