### ISSUE TITLE
[leporno] Exception (leporno): Request to http://leporno.org/tracker.php

### ISSUE THREAD

**Issue by 3xploitzer0** [Jackett/Jackett#7226]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: all version

**Jackett Version**: update

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

 An error occured while testing this indexer
Exception (leporno): Request to http://leporno.org/tracker.php#results failed (Error 521) - The tracker seems to be down.: Request to http://leporno.org/tracker.php#results failed (Error 521) - The tracker seems to be down.
### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
here is a tip. if you cannot access http://leporno.org/ with your browser then odd are good that Jackett will not be able to either ;-)
