### ISSUE TITLE
Request add http://pornleech.io/

### ISSUE THREAD

**Issue by 3xploitzer0** [Jackett/Jackett#7227]
Top list torrent search

https://theporndude.com/top-porn-torrents-sites

**Comment by garfield69** [comment]
Jackett 0.13.127

**Comment by ilike2burnthing** [comment]
Following up on https://github.com/Jackett/Jackett/issues/8294, it's still down.

Shows either:
![pl1](https://user-images.githubusercontent.com/59480337/80145166-a7d4df80-85a7-11ea-913a-2ddea61652e2.png)
or Cloudflare Error 502 page

**Comment by ilike2burnthing** [comment]
Back online

**Comment by ilike2burnthing** [comment]
Back down, same error

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
http://pornleech.io/ - Error 524 - A timeout occurred

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
http://pornleech.io/ intermittent issues:
```
[0] dbconn: mysqli_connect:
```
```
Connection to DB was not possible!No DB with that name seems to exist on the server!
```
```
Error 524 - A timeout occurred
```
Also check http://pornleech.io/index.php?page=torrents&search=&options=0&active=0

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://pornleech.io/ returning Error 524 A timeout occurred

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://pornleech.io/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
```
This domain is expired. If you are the domain owner please click here to renew it.
pornleech.io
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://pornleech.io/  returning This site can’t be reached

**Comment by garfield69** [comment]
v0.18.273

**Comment by garfield69** [comment]
https://pornleech.ch/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://pornleech.ch/ returns Max connect timeout reached while reaching hostgroup 1 after 10000ms

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://pornleech.ch/ - working
https://pornleech.ch/index.php?page=torrents - `Max connect timeout reached while reaching hostgroup 1 after 10000ms`

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://pornleech.ch/index.php?page=torrents
```
Error 503 Backend fetch failed
Backend fetch failed

Guru Meditation:
XID: 125239299

Varnish cache server
```

**Comment by garfield69** [comment]
v0.20.3444
