### ISSUE TITLE
[yggcookie] Exception (yggcookie): Login failed: Selector

### ISSUE THREAD

**Issue by TaharIBRI** [Jackett/Jackett#7230]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Read of https://github.com/Jackett/Jackett/issues/7095#issuecomment-582238746 to check you have the correct site and search links loaded in the config.
also login in to the site with your browser to confirm your account is still good, and that you have a good ratio, and no outstanding alerts, notices or unread mail.
grab a fresh copy of the current cookie and paste that in your yggcookie config.
remember that the cookies expire and need to be replaced regularly.

**Comment by grostim** [comment]
> Read of [#7095 (comment)](https://github.com/Jackett/Jackett/issues/7095#issuecomment-582238746) to check you have the correct site and search links loaded in the config.
> also login in to the site with your browser to confirm your account is still good, and that you have a good ratio, and no outstanding alerts, notices or unread mail.
> grab a fresh copy of the current cookie and paste that in your yggcookie config.
> remember that the cookies expire and need to be replaced regularly.

I face the same error message. Apparrently, this is the cookie expiring. The issue is that the cookie expire very often, making this indexer not really useable in an automated framework.

**Comment by garfield69** [comment]
In that case switch to using the **YGGTorrent indexer**, which uses the regular login method.
_YGGCookie_ is mean to be used in situations when YGGTorrent make changes to their site and break the _YGGTorrent_ indexers ability to login.
As you have already discovered, _YGGCookie_ is not suitable as a full time replacement for the _YGGTorrent_ indexer.
