### ISSUE TITLE
Can't Access Jackett Remotely

### ISSUE THREAD

**Issue by paulr24** [Jackett/Jackett#7233]
### Environment

**OS**:
Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
.Net-Framework

**.Net Version**:
4.8

**Jackett Version**:
0.12.1815.0

**Last Working Jackett Version**:
This is my first install

**Are you using a proxy or VPN?** [yes/no]
No

### Description
I would like to be able to access Jackett remotely (via WAN IP or Dynamic DNS), but I seem to be having issues. I do have this sort of thing working with Sonarr, etc, so I'm pretty sure I've done everything correctly as far as port forwarding, etc. I ran "netstat -aon" and I see that port 9117 as listening. I have "external access" checked in Jackett. When I try to browse to it I get "ERR_CONNECTION_TIMED_OUT." Any ideas?

**Comment by garfield69** [comment]
Access your jackett dashboard, scroll down to the *jackett configuration* section and tick the **external access** check box. Then scroll up a bit and click the **apply server settings** button.
Does that solve?

**Comment by paulr24** [comment]
Thanks for the response! The **external access** box was already checked, but just for grins I tried unchecking it, saving, rechecking it, saving, but that didn't fix the issue.

**Comment by garfield69** [comment]
ok lets recap.
you say you have 9117 as an open port on the outward facing router, and jackett service running with the external access enabled.
you've tested Jackett locally your browser and can access the dashboard, but when you use a remote browser to access your PC's IP address with the 9117 port you get no response.
so your next check is to look for firewall or other software that is blocking incoming wan on 9117?

**Comment by paulr24** [comment]
Thanks for the tips @garfield69! I actually hadn't seen your response yet and thought to check out the Windows firewall. I manually added the Jackett Service and Client and it's working now. I guess I'm just used to the hand holding a lot of software does where it automatically adds itself to the firewall during install, whoops. Anyway, thanks again!
