### ISSUE TITLE
yggtorrent stopped using Cloudflare

### ISSUE THREAD

**Issue by aarsenca** [Jackett/Jackett#7236]
I am running version 0.13.127.0.

In Jackett, I am testing yggtorrent and I get this error:

`
Exception (yggtorrent): Request to https://www2.yggtorrent.se/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date failed (Error BadGateway) - The tracker seems to be down.: Request to https://www2.yggtorrent.se/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date failed (Error BadGateway) - The tracker seems to be down.
`

The tracker is not down. All my ygg torrents are seeding normally.

I read on Twitter that they have disabled their Cloudflare rules page because it was blocked by adblockers. They said they were going to use other means to mitigate DDoS attacks.

I have no idea what this all means. Hopefully, someone here knows what to do about it.

Sounds like yggtorrent's issue of the month :-(

Thanks.

**Comment by garfield69** [comment]
odd. the indexer is working for me.
but that is not unusual.
i often have indexers that keep working for at least a day longer than others who report problems, (no idea why!), so we shall see if we get more reports as time goes on.

**Comment by aarsenca** [comment]
Yeah, it just started working again. I was trying to setup yggcookie as an alternative and I couldn't find the cookie. All of a sudden, the headers were updated and the cookie was there. After I successfully set up yggcookie, I came back here to update my post and I saw yours. I tested the regular indexer and it is OK. Go figure...

Thanks.
