### ISSUE TITLE
Configuration failed on Animetorrents.me

### ISSUE THREAD

**Issue by joshuasm** [Jackett/Jackett#724]
i tired to add the animetorrents index after adding TPB and just get: "Configuration failed: "

attached is the log file using the -t command
[Jackett Log 2016.11.21.txt](https://github.com/Jackett/Jackett/files/604752/Jackett.Log.2016.11.21.txt)

**Comment by kaso17** [comment]
Try hitting the Okay button twice, that works for me most of the time.

@rilwal you've any idea what's going on with the login oddness?

**Comment by rilwal** [comment]
I'm not sure, I didn't write the actual tracker handling, I pulled it from an old version of Jackett and fixed the issues I ran into with it.

**Comment by joshuasm** [comment]
I think that animetorrents RSS feed may be down. not sure why or how, I'm going to contact the admins about it later.

**Comment by kaso17** [comment]
The rss feed isn't used so it shouldn't be a problem.
But please let us know once they released the new side, that most likely will require bigger changes anyway.

**Comment by flightlevel** [comment]
This issue hasn't had activity for a while. If the issue still exists, please reopen and include full logs. https://github.com/Jackett/Jackett#troubleshooting

**Comment by techprowizard** [comment]
I know this is a little bit old of a post, but i am having this same issue on my setup (fresh Jackett install on Ubuntu 16.0.4.2).
[log.txt](https://github.com/Jackett/Jackett/files/998674/log.txt)

**Comment by Degovxx** [comment]
Although I am not the original poster I am having the same issue. Included are the "enhanced logging" enabled logs.
Server Logs
When	Level	Message
Sep 26, 2017 10:36:49 AM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
Sep 26, 2017 10:36:49 AM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Sep 26, 2017 10:36:49 AM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Sep 26, 2017 10:36:49 AM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Sep 26, 2017 10:36:49 AM	Info	
HttpActionBinding ExecuteBindingAsync 
Sep 26, 2017 10:36:49 AM	Info	
HttpActionBinding ExecuteBindingAsync 
Sep 26, 2017 10:36:49 AM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Sep 26, 2017 10:36:49 AM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Sep 26, 2017 10:36:49 AM	Info	
ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Sep 26, 2017 10:36:49 AM	Info	
ApiControllerActionSelector SelectAction 
Sep 26, 2017 10:36:49 AM	Info	
AdminController ExecuteAsync 
Sep 26, 2017 10:36:49 AM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Sep 26, 2017 10:36:49 AM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Sep 26, 2017 10:36:49 AM	Info	
DefaultHttpControllerActivator Create 
Sep 26, 2017 10:36:49 AM	Info	
HttpControllerDescriptor CreateController 
Sep 26, 2017 10:36:49 AM	Info	
DefaultHttpControllerSelector SelectController Admin
Sep 26, 2017 10:36:49 AM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Sep 26, 2017 10:36:49 AM	Info	
  http://192.168.1.215:9117/Admin/GetLogs?_=1506447341643
Sep 26, 2017 10:36:40 AM	Info	
AdminController Dispose 
Sep 26, 2017 10:36:40 AM	Info	
AdminController Dispose 
Sep 26, 2017 10:36:40 AM	Info	
  Content-type='application/json; charset=utf-8', content-length=118
Sep 26, 2017 10:36:40 AM	Info	
AdminController ExecuteAsync 
Sep 26, 2017 10:36:40 AM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync 
Sep 26, 2017 10:36:40 AM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()'
Sep 26, 2017 10:36:40 AM	Info	
ApiControllerActionInvoker InvokeActionAsync 
Sep 26, 2017 10:36:40 AM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
Sep 26, 2017 10:36:40 AM	Error	
Exception in Configure
Sep 26, 2017 10:36:40 AM	Error	
On attempt 3 checking for results from AnimeTorrents: Error: TrustFailure (The authentication or decryption has failed.)
Sep 26, 2017 10:36:40 AM	Debug	
IWebClient.GetString(Url:https://animetorrents.me/login.php)
Sep 26, 2017 10:36:39 AM	Error	
On attempt 2 checking for results from AnimeTorrents: Error: TrustFailure (The authentication or decryption has failed.)
Sep 26, 2017 10:36:39 AM	Debug	
IWebClient.GetString(Url:https://animetorrents.me/login.php)
Sep 26, 2017 10:36:39 AM	Error	
On attempt 1 checking for results from AnimeTorrents: Error: TrustFailure (The authentication or decryption has failed.)
Sep 26, 2017 10:36:39 AM	Debug	
IWebClient.GetString(Url:https://animetorrents.me/login.php)
Sep 26, 2017 10:36:39 AM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Configure()'
Sep 26, 2017 10:36:39 AM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='Configure()'
Sep 26, 2017 10:36:39 AM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Sep 26, 2017 10:36:39 AM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Configure()'
Sep 26, 2017 10:36:39 AM	Info	
HttpActionBinding ExecuteBindingAsync 
Sep 26, 2017 10:36:39 AM	Info	
HttpActionBinding ExecuteBindingAsync 
Sep 26, 2017 10:36:39 AM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Sep 26, 2017 10:36:39 AM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Sep 26, 2017 10:36:39 AM	Info	
ApiControllerActionSelector SelectAction Selected action 'Configure()'
Sep 26, 2017 10:36:39 AM	Info	
ApiControllerActionSelector SelectAction 
Sep 26, 2017 10:36:39 AM	Info	
AdminController ExecuteAsync 
Sep 26, 2017 10:36:39 AM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Sep 26, 2017 10:36:39 AM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Sep 26, 2017 10:36:39 AM	Info	
DefaultHttpControllerActivator Create 
Sep 26, 2017 10:36:39 AM	Info	
HttpControllerDescriptor CreateController 
Sep 26, 2017 10:36:39 AM	Info	
DefaultHttpControllerSelector SelectController Admin
Sep 26, 2017 10:36:39 AM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'

**Comment by Degovxx** [comment]
I updated to the pre-release candidate the the problem was solved.
