### ISSUE TITLE
[extremlymtorrents] Error: Password Incorrect (Config)

### ISSUE THREAD

**Issue by extremlymtorrents** [Jackett/Jackett#7245]
[REQ] XTRTorrents.ws

**Comment by garfield69** [comment]
>Works for me.
Have you logged onto the site with your browser and confirmed you password is what you think it is?

If you recently changed your password, you may need to logout of the web site before you can use it with Jackett... some web sites do not save the password until you logout.

If you have done both these things and you still have trouble post here and we will reopen the ticket.

**Comment by extremlymtorrents** [comment]
Yes works. Thx for your work ... Do you know how to make this on Kodi elementum ???

**Comment by garfield69** [comment]
unless there is an existing add-on plugin for kodi that provides a torznab interface, which you can then set elementum to use, then you are out of luck.
if there is such a plugin, then you can set up a Jackett indexer on it, and set elementum up to use that as a source for your searches.
But we don't support kodi or elementum and I have not used either product, so I've no idea if such an add-on exists.

**Comment by extremlymtorrents** [comment]
Ok! I will try there is a way to add it as provider.. Thx again for supporting Us!

**Comment by chicungunya** [comment]
@extremlymtorrents  did you find a solution to add Jackett as a provider ?
