### ISSUE TITLE
[REQ] bteye.org

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#7247]
BTeye is a DHT torrent search engine providing torrent magnet links for downloading.

https://www.bteye.org/

**Comment by garfield69** [comment]
Jackett 0.13.201

**Comment by garfield69** [comment]
https://www.bteye.org/ returning Error 502 Bad gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://www.bteye.org/ returning Error 502 Bad gateway

**Comment by ilike2burnthing** [comment]
https://www.bteye.org/ - Error 521 - Web server is down
