### ISSUE TITLE
Bit-City not working

### ISSUE THREAD

**Issue by mzlumin** [Jackett/Jackett#725]
Hey kaso

i am having troubles currently using the Tracker Bit-City which has worked once already.
I get again the Error: Found no results while trying to browse this tracker

The full log with debug enabled is here:
[https://gist.githubusercontent.com/mzlumin/1a73a0d1b3c12d41673aa978e3c025be/raw/dc580b250f667da0a0c0c6807378e61550950721/bc_debug_complete](url)
Timeframe where it starts is:  2016-11-22 21:49:04.8079

Copy of the html code is here:
[https://gist.githubusercontent.com/mzlumin/9f98a7587863be3d0cd2841775232632/raw/110325c0cd52fa8864f80070151069ef9d761349/bc_html](url)

The page used for the html code is the following:
`https://bc-reloaded.net/uebersicht.php?showsearch=0&incldead=1&blah=0&team=0&orderby=added&sort=desc`

I have tried to change the Styles again, changed the number of shown torrents, also ticket all categories to be shown 

It has worked with 0.7.618.0 already as seen in this older Log File though...
`
2016-11-21 08:48:31.1483 Info Starting Jackett 0.7.618.0 

2016-11-21 08:48:33.1564 Info Starting web server at http://127.0.0.1:9117/ 

2016-11-21 08:54:57.6417 Info Found 100 (1 new) releases from Bit-City Reloaded `

Thanks again :)

**Comment by mzlumin** [comment]
As per the Logs it seems we ge an internal Server Error back:

`
2016-11-22 22:12:58.6001 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()' 

2016-11-22 22:12:58.6015 Debug UnixLibCurlWebClient:GetString(Url:https://bc-reloaded.net/uebersicht.php?showsearch=0&incldead=1&blah=0&team=0&orderby=added&sort=desc) 

2016-11-22 22:12:58.7773 Debug UnixLibCurlWebClient:GetString Returning InternalServerError =>  

2016-11-22 22:12:58.7925 Info Found 0 releases from Bit-City Reloaded 

2016-11-22 22:12:58.7925 Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker
`
Seems strange to me, opening the same page in the Browser works fin ( loads long, but it gets loaded completely...

**Comment by kaso17** [comment]
Currently it's working for me.
Is it still problem for you?
Was the bit city website working normally while you tried to use it?

**Comment by mzlumin** [comment]
Yes it is still an ongoing problem, just tried it 1 Minute ago.
Yes the Website loads fine though...

**Comment by kaso17** [comment]
v0.7.639 should print additional error messages in case of the InternalServerError, please try it and send me the log.

**Comment by mzlumin** [comment]
Hey @kaso17 

log from version 639 is here:

[https://gist.githubusercontent.com/mzlumin/3062b2ab33df8abf3c1ccc3bcb071ebd/raw/64aa16a1b2cc1549aadc7b39db8c5dd6e23c6e08/bc-internal%2520error](url)

Thanks and regards,
Mario

**Comment by kaso17** [comment]
ok, thank you it seems like curl is not getting any response content.
Can you please describe your environment a little bit so I can try to reproduce it (Which distribution, emono/curl version, ...).

**Comment by mzlumin** [comment]
Hey Kaso,

sure i am running an Ubuntu Server 16.04 within an VmWare Workstation.

Curl is on the following Version:

`curl 7.47.0 (x86_64-pc-linux-gnu) 
libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets`

There is no curl version available as per apt:

`QuickBox:/# apt-cache policy show curl
curl:
  Installed: 7.47.0-1ubuntu2.2
  Candidate: 7.47.0-1ubuntu2.2
  Version table:
 *** 7.47.0-1ubuntu2.2 500
        500 http://archive.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     7.47.0-1ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
`

Mono Version:

`mono --version
Mono JIT compiler version 4.6.2 (Stable 4.6.2.7/08fd525 Mon Nov 14 12:30:00 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
`

I have not made any updates recently...
I can give you direct root access if that would help maybe ?

NOt sure if that could be the Issue, but i have run an tcpdump, the dump shows an fatal error regarding the certificate has no Certificate Authority:

`8	0.121623	192.168.0.145	178.175.135.66	75	Alert (Level: Fatal, Description: Unknown CA)`

Afterwards the Box sends an RST ACK to the Server :
`9	0.123299	192.168.0.145	178.175.135.66	68	50180 → 443 [RST, ACK] Seq=525 Ack=2268 Win=33792 Len=0 TSval=74579018 TSecr=1581732881`


Thanks for your help! :)

**Comment by mzlumin** [comment]
Hey @kaso17 

Not sure if my recent change fixed this Usse, however i can now defenetly use BC again oO

11-25 11:58:26 Info Found 50 (2 new) releases from Bit-City Reloaded

What i have done is, created and imported the certificate chain to /etc/ssl/certs
rebooted the Box and looking today seems to work...

I consider curl terminated due to the CA Errors..

**Comment by kaso17** [comment]
Thank you for debugging it.

BC changed SSL certificates on November 22 which caused the problem for you.
It seems like they don't send the intermediate certificate. BC admins need to fix that.
https://www.ssllabs.com/ssltest/analyze.html?d=bc-reloaded.net
