### ISSUE TITLE
Bitdefender detected Trojan.GenericKD.42603339 in JackettService.exe

### ISSUE THREAD

**Issue by zutch93** [Jackett/Jackett#7250]
OS:OS Name	Microsoft Windows 10 Enterprise N 2016 LTSB

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] 1.1

**.Net Version**:  2 3.0 3.5 4.0

**Jackett Version**: Jackett Version 0.13.135.0
 
**Last Working Jackett Version**: Jackett Version 0.13.135.0

**Are you using a proxy or VPN?** [yes/no] YES, torrent proxy from TorGuard

### Description

HitmanPro scans my pc on boot, i have had Jackett installed and on autorun for approximately 2 months, and Hitman never caught anything malicious with it. until today.

### Logged Error Messages

none

### Screenshots

![image](https://user-images.githubusercontent.com/31257994/74832028-18991a80-531f-11ea-8de5-16dfb0523687.png)

**Comment by hed0n1st** [comment]
Windows Defender became crazy too...
Trojan:Win32/Detplock detected in JackettService.exe. I can't say if it was related to jackett autoupdate or virus signatures update. At least first time i have an alert like this.

**Comment by garfield69** [comment]
Fairly confident this is a false hit. virustotal.com reported that 3 of 72 anti-malware tools reported a hit
https://www.virustotal.com/gui/file/1f9ccd6dfdeacea2c885af82050bc6d9dfdd70447b32dfb2046b857a26bcc195/detection

**Comment by garfield69** [comment]
if this continues for the next release, then consider using your anti-malware reporting tool to send a false-hit report to the apps support team.
there is nothing we can do in Jackett about this.
