### ISSUE TITLE
[REQ] Russian adult torrent website Erzsebet

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#7252]
https://erzsebet.org/
This web site has account system but haven't torrent limit or range limit free like rutracker. Can you add this site on jackett ?

**Comment by garfield69** [comment]
Jackett 0.13.188

**Comment by ilike2burnthing** [comment]
https://erzsebet.org/ - HTTP ERROR 500

**Comment by ilike2burnthing** [comment]
`Технические работы. Скоро вернемся`
`Technical work. We'll be back soon.`

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://erzsebet.org/ - blank page

HTML:
```
</div><!--/body_container-->
</body>
</html>
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://erzsebet.org/
> `Технические работы. Скоро вернемся`
> `Technical work. We'll be back soon.`

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://erzsebet.org/ - HTTP ERROR 500 (only when logged in)

**Comment by berat1397** [comment]
back up

**Comment by garfield69** [comment]
https://erzsebet.org/ returning Error 523 Origin is unreachable
