### ISSUE TITLE
Within the query string, the plus sign is reserved as shorthand notation for a space.

### ISSUE THREAD

**Issue by actionless** [Jackett/Jackett#7265]
### Environment

**Jackett Version**: any

### Description

1) Manually form a search url for "foo bar":
    http://127.0.0.1:9117/UI/Dashboard#search=foo+bar&tracker=&category=

Actual result:
Jackett is searching for "foo+bar"

Expected result:
Jackett should search for "foo bar"

> Note that https://www.w3.org/Addressing/URL/uri-spec.html says
"Within the query string, the plus sign is reserved as shorthand notation for a space. Therefore, real plus signs must be encoded. This method was used to make query URIs easier to pass in systems which did not allow spaces."

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1613137#c7

**Comment by ngosang** [comment]
We are doing it right according to the text you pasted.
If you write "foo bar" in Jackett, we are sending "query=foo+bar". The remote site will decode the string and search for "foo bar".
I'm closing, if you have a concrete example (indexer + query) that doesn't return the expected results show me and I will reopen.

**Comment by actionless** [comment]
i'm talking not about indexers, but about jackett itself (http://127.0.0.1:9117/UI/Dashboard#search=foo+bar&tracker=&category= should search for `foo bar`, not for `foo+bar`) according to the URI spec pasted above

**Comment by ngosang** [comment]
I understand now. I'm on it.

**Comment by garfield69** [comment]
Jackett 0.13.173

**Comment by actionless** [comment]
thanks a lot!
can confirm it works as expected now
