### ISSUE TITLE
Download locally fails

### ISSUE THREAD

**Issue by smurfster** [Jackett/Jackett#7266]
Debian Buster x64
Docker instance
Version 0.12.1815.0
No proxy or vpn

Hey,

When I search manually in the jackett web interface, the results appear. When I try and download locally I recieve the following in firefox
```
The address wasn't understood

Firefox doesn't know how to open this address, because one of the following protocols (http) isn't associated with any program or is not allowed in this context.

    You might need to install other software to open this address.
```

Download to server blackhole does work
If i copy the link in the download locally icon and paste it into my utorrent nothing happens
The log doesnt show any error.

What am I doing wrong?

**Comment by garfield69** [comment]
start by providing an example of which indexer you used to search with, what you searched for, and which torrent you attempted to download. this way I can replicate and check that I also get or do not get what you reported.
