### ISSUE TITLE
Jacket installed on windows 7 failed Microsoft Security Essentials quarantined  Behavior:Win32/Persistence.WU!ml

### ISSUE THREAD

**Issue by nydave69** [Jackett/Jackett#7273]
Jacket was working ok till the other day when i couldn't bring up the browser window for it.
The ip address to it (bookedmarked) would just say ops couldn't find the address your looking for,
Jacket was on the taskbar, right click and it said to start background service. (thought it was running)
OK so I tried to start the service, got a popup saying I need admin rights to start that service.
I am admin.. was installed through this account a while back.
Everything I tried was blocked...  So I downloaded the latest version and installed it.  Installation went smooth no errors.. Open jacket it looked good, still had all the trackers listed. Open SickChill and re-enabled jacket. did a little testing all looked good.  After a few hours I went and looked at SickChill to see what it was downloading etc....  Found nothing but errors related to jacket.  Looked at Jacket in the browser window it looked normal. Right clicked the Jacket icon on the taskbar and once again it showed start background service...   Strange...  Open a Web UI was grayed out again. So I tried to start one using my bookmark next to the one that was already open and once again I get the Oops we can't find the address your looking for.  So we are back to before the last install.  Went into SickChill disabled Jacket.  Tried everything to get that service to start and that includes going to Windows service and checking rights etc.. would not let me start it.  Kept tell me I needed Admin rights.

After much messing around I found this;
![image](https://user-images.githubusercontent.com/14140816/75033035-f070ff00-5477-11ea-880e-5b9f295886ad.png)

Microsoft Security Essentials see it as a
**Behavior:Win32/Persistence.WU!ml** 

Severe threat remove this software.

So what is next?

OS Windows 7 64bit

Jacket was installed again yesterday not sure what version that is.
Can't do anything with the one thats running.

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by mad-tunes** [comment]
I've just found similar with windows defender on server 2019, after jackett updated itself to v0.13.144
It says its found win32/Detplock in jackettconsole.exe. Same if I manually dowload the 0.13.144
release and scan what it contains.

Scanning it with Avast doesnt highlight anything though, so its likely a false positive?

**Comment by garfield69** [comment]
duplicate of #7246 
I am confident this is a false positive
only 3 of 73 checks on virustotal complained a47343909aba3eab0584d3370bcb19aa95829bbbb02673fd1425df150bc736be
I suggest reporting it as a false positive via your MSE reporting page and setting up a temporary exclusion rule so you can carry on.

**Comment by mad-tunes** [comment]
https://www.microsoft.com/en-us/wdsi/submission/b2135908-d7ab-4525-8f67-5a23e68ad330
