### ISSUE TITLE
(leporno): The tracker seems to be down

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7284]
The site is not working. Tested 2020/02/21. Remove after 1 month down from now.
URL: http://leporno.org/
Tested in: https://www.uptrends.com/tools/uptime

**Comment by garfield69** [comment]
back online

**Comment by ngosang** [comment]
It's down again => http://leporno.org/
502 Bad Gateway

**Comment by garfield69** [comment]
back online
![image](https://user-images.githubusercontent.com/6933240/77260405-ab492280-6cec-11ea-84d0-a6ac638a35cc.png)
