### ISSUE TITLE
(torrentwal) is not returning results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7286]
I only see advertisements in https://torrentwal.com/
Jackett is returning 0 torrents.
@garfield69  Should we wait a month before removal?

**Comment by garfield69** [comment]
yup. it may be they have switched to a new domain that someone will discover and report.
if not then after a month we will remove.

**Comment by garfield69** [comment]
its nearly 30 counting from https://github.com/Jackett/Jackett/pull/5881#issuecomment-586547034
so I'm removing this tracker now.
