### ISSUE TITLE
[REQ] films.club

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#7289]
[films.club](https://films.club/) is a Russian Semi-Private Torrent Tracker for Movies and TV.

**Comment by garfield69** [comment]
@dimqua 
can you test on this website how to search for tv serials such as **the flash s04e01**
I cannot figure out what works
`the flash сезон 4 серии 1`
`the flash сезон 4`
`the flash 4 1`
`the flash сезон: 4 серии: 1`
`the flash S04E01`
all return nothing.
`the flash` works...

also, can you see if sorting results is supported, I can't seem to find those options either.
thanks.

**Comment by dimqua** [comment]
It seems, both features aren't supported. :/

Series info isn't actually included in the name.
![](https://i.imgur.com/kZtaWkQ.png)

**Comment by garfield69** [comment]
oh well. 
I guess the next best thing would be to strip the s01e01 from the keywords and thus return any and all hits.
not being able to sort could result in lost hits, but that is just the way it is.
I'll put an info note in the config warning of the restrictions for sonarr users.

**Comment by garfield69** [comment]
Jackett 0.13.222

**Comment by SuberSeb** [comment]
Can you strip year from title? Sonarr can't handle any of tv shows posted in FilmsClub because of year in the title. Maybe add FilmsClub(no year) indexer along with already existing FilmsClub indexer?

**Comment by garfield69** [comment]
no need for a separate indexer, I can set up a config option checkbox to provide a year-less title.

**Comment by garfield69** [comment]
Jackett 0.13.446

**Comment by SuberSeb** [comment]
For some reason Sonarr can't handle any of TV shows from FilmsClub... Parsing error

**Comment by SuberSeb** [comment]
Maybe you should put season and episode number before quality profile? Now it looks like this: "Blue Bloods WEBDL 1080p S1E1-22 rus". I suggest make this string like this "Blue Bloods - S1E1-22 - WEBDL 1080p - rus"

**Comment by garfield69** [comment]
Jackett 0.13.467

**Comment by SuberSeb** [comment]
Now it works, thank you!

**Comment by SuberSeb** [comment]
All TV shows in FilmsClub translated and voiced by the studio "TVShows". Can you add another checkbox, which will add "(TVShows)" string to the title (for Sonarr restrictions)? String should look like this "Chicago Fire - S8E1-15 - rus (TVShows) WEBDL 1080p" for example.

**Comment by garfield69** [comment]
if every filmclub tv show has been processed by this studio, just what is it what you are going to restrict? i don't get it. Its not like you have a choice in what filmclub is providing...?

**Comment by SuberSeb** [comment]
In Sonarr I have a lot of indexers, most of them puts studio name in the title. I'm using tags to prevent Sonarr of grabbing wrong releases. So FilmsClub don't have studio name in the title, Sonarr can grab not appropriate release. For example grab release from another indexer and another studio. "(TVShows)" in the title can help Sonarr understand that this is appropriate release.

**Comment by garfield69** [comment]
I see. ok.

**Comment by SuberSeb** [comment]
Thank you!

**Comment by garfield69** [comment]
Jackett 0.13.506

**Comment by garfield69** [comment]
https://films.club/ returning ERR_CONNECTION_TIMED_OUT

**Comment by SuberSeb** [comment]
Try films4.club domain

**Comment by garfield69** [comment]
Excellent!

**Comment by garfield69** [comment]
Jackett 0.16.127

**Comment by SuberSeb** [comment]
Tracker is dead... FilmsClub no longer upload torrents on this website. Only paid site for online watching.

**Comment by garfield69** [comment]
wait 3 days to see if an alternate domain shows up pointing to the original film.club site

**Comment by SuberSeb** [comment]
> wait 30 days to see if an alternate domain shows up pointing to the original films.club site

No, thats not a problem. Creators of the tracker no longer support it. They closed this tracker, content will no longer be published there. 

Alternative domain films4.club still works. Just try click on button "Сериалы" (TV shows) there. Site redirects you to online cinema filmsclub.tv, where you need to pay for subscription. Also there only online watching, no support for torrents or downloads at all.

So this tracker is officially dead.

**Comment by dimqua** [comment]
> Just try click on button "Сериалы" (TV shows) there. Site redirects you to online cinema filmsclub.tv, where you need to pay for subscription.

Movie torrents are still there.

**Comment by ilike2burnthing** [comment]
The .yml needs to be redone for films only

**Comment by ngosang** [comment]
@ilike2burnthing what we should do?

**Comment by ilike2burnthing** [comment]
I'll play about with the .yml to get it stripped down

**Comment by ilike2burnthing** [comment]
It may just be that the only thing which needs removed is the Series cat, as their Documentary, Anime, and Cartoon cats are a rather annoying mix of films and series.

My only question would be can we/do we need to change the category mappings to reflect that? @garfield69?

Documentaries - all listed on the site as films, but I think most, if not all, were single episode TV/Netflix specials
Anime - 50/50 split between films and TV series
Cartoons - about a fifth are TV series

Everything else is working fine.

**Comment by garfield69** [comment]
delete the indexer.
as SuberSeb reported and the Jackett keywordless search returns, there has been nothing new loaded for at least 136 days.
