### ISSUE TITLE
[siambit] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by c0r0na666** [Jackett/Jackett#7295]
![Screenshot_1](https://user-images.githubusercontent.com/61356908/75095494-d8a89080-55c7-11ea-8f10-d37bd784b337.png)
what is your email ?
i will sent the user and pass

**Comment by garfield69** [comment]
When your siambit account has unread mail, it interferes with torrent searching.
then stops the indexer from accessing the torrent search page.
So be sure to read any outstanding mail and then try using the indexer again.
works for me.
