### ISSUE TITLE
Please modify URL in tracker TVTorrents.ro to Freshon.TV 

### ISSUE THREAD

**Issue by sethwarsh** [Jackett/Jackett#73]
Please modify URL in tracker TVTorrents.ro to Freshon.TV 

The site has remained the same and the subscriber base (username/passwords) all remain the same, they just relocated their URL. Can you please modify the URL in Jackett.

Thank you

Seth

**Comment by flightlevel** [comment]
It's always been using freshon.tv https://github.com/Jackett/Jackett/blob/master/src/Jackett/Indexers/Freshon.cs#L39

**Comment by sethwarsh** [comment]
My apologies, I entered my credentials incorrectly, and assumed the URL was TVtorrent.ro

Sorry again,

Seth
