### ISSUE TITLE
[scenetime] Your cookie did not work: The 'Value'='login,donateok' part of the cookie is invalid. (Config)

### ISSUE THREAD

**Issue by doc-jay** [Jackett/Jackett#7300]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:  CENTOS 7

**.Net Runtime**:  .Net-Core

**.Net Version**: 

**Jackett Version**: 0.13.163

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] NO

### Description

I upgraded to the latest version of Jackett from using an older Mono version.  I kept the indexers and the 'scenetime' indexer would not validate.  I edited the indexer and grabbed the cookie again from the dev console in Firefox and it complained with the error message below.

### Logged Error Messages

 An error occured while updating this indexer
Your cookie did not work: The 'Value'='login,donateok' part of the cookie is invalid.

### Error in Log File

b 22, 2020 02:34:24 PM | Error | System.Exception: Your cookie did not work: The 'Value'='login,donateok' part of the cookie is invalid.    at Jackett.Common.Indexers.SceneTime.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SceneTime.cs:line 158    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
-- | -- | --

### Screenshots

![ST error](https://user-images.githubusercontent.com/11081155/75098856-c35c4380-5580-11ea-8def-7b01407d59a0.PNG)

**Comment by garfield69** [comment]
works for me.
your cookie should look something like this:
`__cfduid=d***********0; PHPSESSID=3*********0; uid=4****8; pass=2*********9; acopendivids=login,donateok; acgroupswithpersist=nada`
but if you are on a Linux system, it will need to remove the `acopendivids=login,donateok;` because that cookie value get rejected on that platform.

**Comment by Jerrk** [comment]
@garfield69's fix worked for me, removed the `acopendivids=login,donateok;` line and it now works.
