### ISSUE TITLE
[REQ] TTsWeb

### ISSUE THREAD

**Issue by bubmann** [Jackett/Jackett#7301]
https://ttsweb.org/ is a private tracker mostly for film and TV

TTSWeb is a Private Torrent Tracker for MOVIES / TV / GENERAL

**Comment by garfield69** [comment]
registration and login successful. thank you.

**Comment by garfield69** [comment]
Jackett 0.13.222

**Comment by garfield69** [comment]
https://ttsweb.org/ returning Error 521 Web server is down
https://www.uptrends.com/tools/uptime reports Http Protocol Error across 43 checkpoints worldwide

**Comment by garfield69** [comment]
v0.19.116
