### ISSUE TITLE
[eztv] Exception (eztv): The response ended prematurely.: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by XcOM987** [Jackett/Jackett#7304]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows Server 2016 - Docker 2.0.0.2

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] .Net-Core

**.Net Version**: Unknown

**Jackett Version**: 0.12.1590.0

**Last Working Jackett Version**: 0.12.1590.0

**Are you using a proxy or VPN?** [yes/no] Yes (Nord via Socks)

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Tried default EZTV settings, was previously working, no indication what caused it to stop, removed and re-added EZTV to no success, other trackers work fine with no issues, tried with and without VPN connected

### Logged Error Messages

Not sure if related but the below has been seen and seems suspect:
[39;49m   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)[39;49m[39;49m
[39;49m   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73 Jackett.Common.IndexerException: Exception (eztv): The response ended prematurely.[39;49m[39;49m
[Jackett Logs.txt](https://github.com/Jackett/Jackett/files/4240767/Jackett.Logs.txt)

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

### N/B
Searched for related tickets, seen a few but all missing details to assist with investigations.

**Comment by garfield69** [comment]
the regular log provides little info on what might be going on with your eztv indexer other than the fact that for some reason the indexer is not getting the response it is expecting.
give that other indexer are still working, this suggests something specific with he eztv site, an outage or server issue.
eztv is working for me right now.
lets see of the **enhanced** log can yield a little more info
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test for eztv
4. find the *log.txt* file `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.
