### ISSUE TITLE
New tracker not available when try to add them

### ISSUE THREAD

**Issue by thenamelessthing** [Jackett/Jackett#731]
I juste updated to the latest version to use Ethor, tspate,etc and when I click on add, I don't see them in the choice..

http://screencloud.net/v/n6LQ
http://screencloud.net/v/lj0U

**Comment by maxcore** [comment]
strange , mine i see all the news providers and they work perfectly

**Comment by thenamelessthing** [comment]
you update it by the button on the web page?

**Comment by maxcore** [comment]
no with my synology i stop jackett i upload the new jackett and i restart

**Comment by fana13** [comment]
I've got the same issue.
Bluetigers has been disappeared but new trackers are not here.
I do my update on web page for information

**Comment by kaso17** [comment]
please post a log

**Comment by thenamelessthing** [comment]
Maybe fana13 can post his log. I have already reinstalled from scratch and it's working...

**Comment by fana13** [comment]
Sorry for this question but where can i find the log file ?

**Comment by mzlumin** [comment]
Running on same version, all fine on my site here though...
Can you try using your browser in Inkognito Mode and/or clear your Browsers cache ?

**Comment by fana13** [comment]
@mzlumin I try with another browser and same issues

**Comment by mzlumin** [comment]
You can start logging by executing the .exe with -t

`JackettConsole.exe -t`

Also have you restarted Jackett already once after the Update ?

Are you running on Windows or Linux ?

**Comment by fana13** [comment]
When I start -t it listen port 9116 or I modify this port to another, so I can't give the log.
So  I make new install and it's allright, new trackers are here.
It's on Linux :)
Close for me and sorry for logs.

**Comment by thenamelessthing** [comment]
It's not a browser cache issu I have try to reset cache and it doesn't fix anything. Well. I close the issue.
