### ISSUE TITLE
[newrealworld] Exception (newrealworld): Input string was not in a correct format.: Parse error (Config)

### ISSUE THREAD

**Issue by doopeldedoo** [Jackett/Jackett#7314]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu Linux

**.Net Runtime**: Mono

**.Net Version**:

**Jackett Version**: Version 0.12.1815.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** yes

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by loibi93** [comment]
Hi, having the same issue, here is the enhanced [LOG](https://pastebin.com/hs5KCvPK) on pastebin

What is weird, when I start Jackett locally on master branch it works ok, only on my Server it does not work!

Version:
0.14.418.0 (docker running on Unraid)

The error happens when adding the indexer.


If any other information or anything else is needed (I could develop a fix myself but it is not happening locally) please ping me! :)

**Comment by garfield69** [comment]
Jackett 0.14.447
