### ISSUE TITLE
Apache2 reverse Proxy

### ISSUE THREAD

**Issue by TMTYD** [Jackett/Jackett#7316]
Hi

how do I configure a reverse proxy for jacket with apache? What is in the wiki is unfortunately not possible.

My OS is Debian Strech

**Comment by garfield69** [comment]
what is it about the Apache section at https://github.com/Jackett/Jackett/wiki/Reverse-Proxy that is not possible?

**Comment by TMTYD** [comment]
Hi

I entered and modified it on my server. When I call nas/jackett only nas/UI/Dashboard and this message "Not Found

The requested URL was not found on this server.
Apache server at nas port 80 "

**Comment by garfield69** [comment]
>When I call nas/jackett only nas/UI/Dashboard

access your jackett `ServerConfig.json` file and check that you have set the  `"BasePathOverride": "/jackett",` (or what ever path you used in your Apache location)
the file normally resides in your jackett config folder, typically `~/.config/Jackett`

if you have it set correctly, and you have restarted the jackett service to pick up the change, and its not working, try this alternate Apache proxy setting from https://github.com/Jackett/Jackett#running-jackett-behind-a-reverse-proxy
```
<Location /jackett>
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
    ProxyPass http://127.0.0.1:9117
    ProxyPassReverse http://127.0.0.1:9117
</Location>
```
