### ISSUE TITLE
[ourbits] Error parsing JS challenge html (Config)

### ISSUE THREAD

**Issue by mmiluy** [Jackett/Jackett#7322]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.12.943.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] yes

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
[ourbits] Error parsing JS challenge html (Config)

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Your version of Jackett 0.12.943 is too old. 
The CloudFlareRe library was updated to 1.0.6 to resolve the `error parsing JS clallenge html` beginning with Jackett 0.12.1042
The Current latest version of Jackett is 0.13.201

**Comment by mmiluy** [comment]
thank you！

**Comment by mmiluy** [comment]
> Your version of Jackett 0.12.943 is too old.
> The CloudFlareRe library was updated to 1.0.6 to resolve the `error parsing JS clallenge html` beginning with Jackett 0.12.1042
> The Current latest version of Jackett is 0.13.201

thank you！
