### ISSUE TITLE
[req] Boxing Torrents (TC-Boxing)

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7323]
Boxing Torrents 3.0 (TC-Boxing) is a Private Torrent Tracker for Boxing.

Sign-up is open for now https://tc-boxing.com/signup.php

**Comment by garfield69** [comment]
Jackett 0.13.228

**Comment by garfield69** [comment]
https://tc-boxing.com/ ERR_TIMED_OUT

**Comment by garfield69** [comment]
online
