### ISSUE TITLE
[tvchaosuk] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by bmn001** [Jackett/Jackett#7327]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Raspbian

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
not sure...

**.Net Version**:
not sure...

**Jackett Version**:
0.13.201.0

**Last Working Jackett Version**:
unknown...maybe within the last week or two it broke

**Are you using a proxy or VPN?** [yes/no]
yes

### Description

TVChaosUK started failing Jackett tests recently:
"An error occured while testing this indexer
Found no results while trying to browse this tracker"

I think the site design changed slightly, so Jackett search isn't working.  (See error msg)

### Logged Error Messages
System.Exception: Error while parsing field=description, selector=a[href*="/categories/"] div i, value=<null>: Selector "a[href*="/categories/"] div i" didn't match 

### Screenshots
n/a

**Comment by garfield69** [comment]
Jackett 0.13.211
