### ISSUE TITLE
Need clarification with Sickrage

### ISSUE THREAD

**Issue by thenamelessthing** [Jackett/Jackett#733]
Hi, I see in the readme it's supposed to support sickrage. But I don't find how.  Anybody can explain how I can use jackett with sickrage?
Thanks you.

**Comment by kaso17** [comment]
According to https://github.com/rembo10/headphones/issues/2329 it should be supported.
But as I never used it I don't know how to add a new torznab indexer in sickrage.

**Comment by duramato** [comment]
You  just add it as a normal newznab indexer,  and have the torrent client you wish set and if you don't use usenet just set blackhole for it.

**Comment by thenamelessthing** [comment]
can you @duramato can you post a screenshoot? I'm not sure I understand correctly what you mean.

**Comment by duramato** [comment]
A screenshot of what exactly?

**Comment by thenamelessthing** [comment]
@duramato I mean an example of sickrage configured with jackett.

**Comment by duramato** [comment]
Just add it here with the URL, api key of jackett and select the cats you want. 
![image](https://img.cla46.com/up/1480079385e0228f9.png)

**Comment by thenamelessthing** [comment]
@duramato  Thanks you it's what I needed

**Comment by saitoh183** [comment]
Since the image from @duramato  doesnt show anymore, can someone explain how to add to sickrage

**Comment by haxcop** [comment]
Quick question @duramato Will have any problems if also you are using Usenet? .
Cheers!

**Comment by duramato** [comment]
Nope, torznab will use whichever torrent client you set while usenet the client you have set for it.

**Comment by haxcop** [comment]
Cool Thanks for the info! @duramato

**Comment by na-ji** [comment]
@duramato : Your screenshot is dead. Is it possible to have a real doc to configure sickrage ?

**Comment by duramato** [comment]
Image fixed

**Comment by na-ji** [comment]
Thank you for your help!
