### ISSUE TITLE
Can't search if select all tracker one time

### ISSUE THREAD

**Issue by c0r0na666** [Jackett/Jackett#7332]
**OS**: Raspberry 

**.Net Runtime**: MONO

**.Net Version**:

**Jackett Version**: v0.13.201.0

**Are you using a proxy or VPN?** [no]

while i select all tracker to search...its not showing anything just a loading
its work if i select 1 track to search..

![Screenshot_1](https://user-images.githubusercontent.com/61356908/75321210-d766b480-58a2-11ea-86b4-986dba887631.png)

**Comment by garfield69** [comment]
>while i select all tracker to search...its not showing anything just a loading

I sometimes think folks underestimate the resources that get used in polling multiple web sites simultaneously, fetching results and processing then for presentation...

processing 43 trackers is going to take time...and if any one or more of these web sites has an isse that delays the return of results (slow server becuase of DDoS attacks, Cloudflare challenges, poor routing or node overloads), that cause the requests to have to wait until the 90 second timeout to kick in, the the final presentation of results can take quite some time.

And you may be running into hardware storage constraints, or network overload or any number of resource issues, especially on a rasp... these are not usually loaded with abundant memory, network capacity, etc. or is yours the exception?
How much memory do you have (1,2,4,8,16 32GB?), 1GB ethernet or only wireless, multi CPU higfh speed engine?
 
if you leave the tracker selector set to ALL do you get the same reaction?
does it work if you select two? 
if continue adding trackers until it stops working...how many before it fails?

I don't think this is an issue with Jackett, most likely its an issue with device resources...prove me wrong.

**Comment by c0r0na666** [comment]
ram 1 GB
i am using wireless
yesterday work well.

if i select 2 still work and to 5
but when select its stil keep searching

the usage while i use jackett just to 30-65% resource it enough..

**Comment by cadatoiva** [comment]
Run a test all and make sure all your trackers are working. With my 33 trackers, I regularly have to wait 3-5 minutes for the results to come back because public trackers are notoriously error prone.

**Comment by cocokola** [comment]
About a week ago the ALL feed stopped working after a year of working fine.  A recent update on the Dev (or nightly - whatever the most up to date is) made this stop woking in Sonarr and Radarr.  

I can manually go to the URL and get the familiar 'wrong key' message (verify not a network layer or firewall layer issue).  Using one tracker works fine. 

This happened in the past, and after about a week it started working again, presumably, jackett found the problem and fixed it- - I forget exactly.

Jackett tests fine,   I can provide logs, but since this describes the problem and is able to be recreated , (*I tried jackett on TWO machines with same result. - BOTH of these worked previously.)

please advise, I'll be happy to help, but dont want to waste my time when it should be clear.

**Comment by garfield69** [comment]
>I can manually go to the URL and get the familiar 'wrong key' message

can you show is the exact message you are referring to here?

**Comment by ngosang** [comment]
@c0r0na666 This is not a real fix, but the Mono version requires more memory than .NetCore version. Try installing `Jackett.Binaries.LinuxARM***.tar.gz` release instead.

**Comment by cadatoiva** [comment]
@garfield69  he's talking about this error that comes up when you copy the feed and paste it into a browser without adding the API key.

> This XML file does not appear to have any style information associated with it. The document tree is shown below.
> <error code="100" description="Invalid API Key"/>

When you press "Test All"
![image](https://user-images.githubusercontent.com/2086652/75628182-34f94a80-5b9c-11ea-8732-01d2c56c1960.png)

And you get back any with an error
![image](https://user-images.githubusercontent.com/2086652/75628202-50645580-5b9c-11ea-809e-805897127243.png)
Or any that get stuck:
![image](https://user-images.githubusercontent.com/2086652/75628210-5eb27180-5b9c-11ea-8f6e-db8f90f6963a.png)

That slows down your /All indexer. You have to wait for Jackett to give up on those trackers returning results before you'll see the feed. On the JackettUI this is easy enough to do, by just waiting for the results to come back. External applications like Sonarr/Radarr have their own timeouts, which can be much shorter than the wait on /All if more than one tracker is hanging.
