### ISSUE TITLE
[BTDB] only working when Sort is set to Seeders

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#7335]
Docker container v0.13.211-ls55, also an issue when using a fresh Windows sandbox (not Docker) install. Using previous versions doesn't seem to resolve this, so I'm assuming it's another change to the site.

[log - created.txt](https://github.com/Jackett/Jackett/files/4254833/log.-.created.txt)
[log - size.txt](https://github.com/Jackett/Jackett/files/4254834/log.-.size.txt)
[log - seeders.txt](https://github.com/Jackett/Jackett/files/4254835/log.-.seeders.txt)

**Comment by garfield69** [comment]
Jackett 0.13.222
