### ISSUE TITLE
[REQ] U2.dmhy.org

### ISSUE THREAD

**Issue by jerry048** [Jackett/Jackett#7337]
Address to the site; https://u2.dmhy.org/
Private Tracker
One of the best tracker for anime content

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by jerry048** [comment]
Sent

**Comment by garfield69** [comment]
Registration and login successful. Thank you.

**Comment by garfield69** [comment]
Jackett 0.13.280

**Comment by Zero3K** [comment]
Can someone please send me an invite? My email address is zero3K at teknik.io.

**Comment by Canz2** [comment]
If possible I would like an invite to Canz2.ani at Gmail dot com

**Comment by fasaol** [comment]
Please, send me invite for u2.dhmy
fabsanoli@gmail.com

**Comment by garfield69** [comment]
This is a support site for the Jackett app, **NOT** a forum to solicit invitations. Please look elsewhere.

**Comment by amdradeonhd6950** [comment]
Hello. I'm begging to you. Would you send me the invitation code for U2-share? I'm trying to save and seed BDMV files on dozens of hard disks connected to a private server, but it's difficult without U2's help. Invite code please.
my email is trolling2004000 @ gmail.com
please...

**Comment by garfield69** [comment]
@amdradeonhd6950 I am sorry, but this is **not** a forum for invites, this is a support site for the Jackett indexers only.
If we permitted invite requests posts here, we would be inundated with posts that are off topic to this support site.
Please use the appropriate web forums for your invitation requests, there are easily found with some basic google searching.

**Comment by Riskus2** [comment]
Hey, I  was also kinda looking  for an invitation  for u2. Heard they got remuxes for old animes. See if anyone  can invite me!

**Comment by ilike2burnthing** [comment]
For the third time now, "this is **not** a forum for invites"...

**Comment by KingSton91** [comment]
Guys anyone could share an invite pls?

**Comment by garfield69** [comment]
@KingSton91  this is a support site for the Jackett app.
It is not a forum for soliciting invites.
Please look elsewhere.
