### ISSUE TITLE
[REQ] Xanax

### ISSUE THREAD

**Issue by savahu** [Jackett/Jackett#734]
Tracker: xanax.rip
Genre: Music

Currently open for signup

**Comment by kaso17** [comment]
Replaced what.cd on my todo list ;)

**Comment by maxcore** [comment]
👍👍

**Comment by ideaprison** [comment]
I want this one added too but just as a heads up, they're going to change the name real soon, so a new domain, but without a doubt the same backend: Gazelle.

**Comment by jaredbidlow** [comment]
looks like its signups are closed?

**Comment by maxcore** [comment]
20 000 users in one day ! ;)

**Comment by ideaprison** [comment]
Does @kaso17 need help with adding the code, I can test it for him, or provide what the pages are like pre/after login, the browse page etc..

Like I mentioned it runs on Gazelle

**Comment by kaso17** [comment]
I was one of the first 1000 users, working on it right now

**Comment by kaso17** [comment]
Added it with it's future "Apollo" name
