### ISSUE TITLE
[generationfree] Exception (generationfree): Login failed: Selector

### ISSUE THREAD

**Issue by gwenvador** [Jackett/Jackett#7341]
**OS**: Windows 10

**Jackett Version**: 0.13.211.0

### Description
Generation-Free tracker is not working: 
Exception (generationfree): Login failed: Selector "a[href="account-logout.php"]" didn't match: Parse error

###  Logged Error Messages

02-27 09:09:17 Info CardigannIndexer (generationfree): Relogin required
02-27 09:09:18 Error Error on 20200227090918 for Generation-Free.txtJackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="account-logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 811
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1342

**Comment by garfield69** [comment]
yes, the web site has changed their login page.
I will code a fix when I next have some free time.

**Comment by garfield69** [comment]
Jackett 0.13.222

**Comment by gwenvador** [comment]
The change is not correct. The login page is name_login not namelogin. Pull request done

**Comment by gwenvador** [comment]
Looks like there are constantly changing the login again. Now it is login_name. I will do another pull request.

**Comment by cadatoiva** [comment]
Hopefully they settle with one soon.

**Comment by garfield69** [comment]
Jackett 0.13.228
