### ISSUE TITLE
[request] https://myporn.club/

### ISSUE THREAD

**Issue by 3xploitzer0** [Jackett/Jackett#7344]
THE GOOD
Free HD premium porn downloads
Good search engine
Almost no ads
Mobile Support

THE BAD
Minimalist, high-contrast layout
No comment section

**Comment by garfield69** [comment]
Jackett 0.13.378

**Comment by garfield69** [comment]
https://myporn.club/ > cloudflare Gateway time-out Error code 504

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://myporn.club/ > cloudflare A timeout occurred Error code 524

**Comment by garfield69** [comment]
online
