### ISSUE TITLE
[req] OneJAV

### ISSUE THREAD

**Issue by 3xploitzer0** [Jackett/Jackett#7345]
https://onejav.com/
Public

Pros
access to thousands of full-length jav movies
unlimited torrents
plenty of seeders make for faster downloads
modern and simple site design
lots of fetish tags

Cons
mobile site blows

**Comment by garfield69** [comment]
Jackett 0.13.405

**Comment by ilike2burnthing** [comment]
https://onejav.com/ - Web server is down - Error code 521

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://onejav.com/ cloudflare Connection timed out Error code 522
uptime has 11 checkpoints timeout the other 32 online

**Comment by ilike2burnthing** [comment]
back up here and for most checkpoints
