### ISSUE TITLE
[req] http://www.javjunkies.com/

### ISSUE THREAD

**Issue by 3xploitzer0** [Jackett/Jackett#7346]
Pros
free downloads
thousands of hd jav
tag cloud
some western porn

cons
shitty design
stupid security checks
ads
no information about torrents

**Comment by garfield69** [comment]
not compatible with cardigann.
requires c#

**Comment by imTHAI** [comment]
Are u sure this website is even working ? 
Every rlz I click send me to Error 404 page

**Comment by Janco2049** [comment]
This site has problems with ipv6, connect through a vpn to analyze, or disable ipv6

**Comment by Janco2049** [comment]
Download link example: http://www.javjunkies.com/main/Jl.php?kEy=2312&file=8814a756c31392f5975695f54616b61686174612e4b415744393939

**Comment by Janco2049** [comment]
Source code: view-source:http://www.javjunkies.com/main/2019/07-20-10/ 
![Captura de pantalla (110)](https://user-images.githubusercontent.com/12991906/115803568-89bade80-a3b7-11eb-8974-3fa5e8884c08.png)

**Comment by Janco2049** [comment]
direct download no VPN required

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
