### ISSUE TITLE
Could not load type 'CloudFlareUtilities.ClearanceHandler' error when adding AnimeTorrents

### ISSUE THREAD

**Issue by tech6** [Jackett/Jackett#735]
When trying to add AnimeTorrents to Jackett I receive the following error:

 Configuration failed: Could not load type 'CloudFlareUtilities.ClearanceHandler' from assembly 'CloudFlareUtilities, Version=0.3.3.0, Culture=neutral, PublicKeyToken=null'.

This doesn't appear to be related to the existing AT issue, so I created a new one. I have tried numerous times and received the same message. My logs do not contain any additional details.

I'm running Jackett on Ubuntu 16 with mono version 4.6.2. My jackett version is 0.7.577.0.

**Comment by kaso17** [comment]
Please make sure the "mono-devel" package is installed

**Comment by tech6** [comment]
That fixed it. Sorry, I followed the instructions in the readme from HTPCGuides and they didn't mention installing mono-devel separately .
