### ISSUE TITLE
Issue with Jackett and Torpotato (Couchpotato) searches

### ISSUE THREAD

**Issue by testarea1** [Jackett/Jackett#736]
Using Jackett 0.7.639.0 on ubuntu w/mono 4.6.2. Couchpotato dev version from 11/12.

When Couchpotato searches via the torpotato connection to jackett, it's searching on title and finding any releases that contain ANY instead of ALL of the words. It doesn't matter on what date the release or the rest of the title, if it finds ANY part of the title in the results, it grabs that release even if the title doesn't fully match on title or year. This happens on any trackers I've added in jackett. The built in trackers to CP don't have this issue, it's only through the TP connection to jackett.

Is this an issue with the jackett results or is this a problem with CP and torpotato connection to jackett not properly searching the full title and year?

**Comment by kaso17** [comment]
Sometimes trackers return non relevant results if they don't find an exact match.
Please let us know which exact tracks have this problem, it can be fixed easily.

**Comment by testarea1** [comment]
The trackers I've seen the issue with are:

1. PrivateHD
2. UHDBits
3. PirateTheNet

**Comment by kaso17** [comment]
For me it looks like the result is properly AND filtered.
Can you please provide an example search query causing the problem?

**Comment by Nyghto** [comment]
Having issue with CouchPotato and Jackett as well: 
If you search for Rings 2016, it will return results like: Kubo and the Two Strings 2016.

Actually first Couch didnt send year in the request, what a lot of fakes beeing returned, this is fixed now. But above issue is still there, and I think Jackett should not return Kubo and the Two Strings to CouchPotato because rings is part of strings.

**Comment by kaso17** [comment]
I opened an enhancement issue for this (#810)

**Comment by raspdealer** [comment]
I can complete with XThor, ABN, T411.

Looking for Sing (2016) => Neighbors.2.Sorority.Rising.2016
Looking for Moana (2016) => Money Monster 2016             (WTF?!)

**Comment by kaso17** [comment]
Looking for Moana (2016) => Money Monster 2016 (WTF?!)
can be fixed with the existing ANDMAtch filters, it shouldn't show up with T411
With xthor/ABN it might as they don't use the filter (I can't test, no access)

**Comment by kaso17** [comment]
Did anyone test if the couchpotateo replacement  https://github.com/Radarr/Radarr has the same issue?

**Comment by testarea1** [comment]
I actually switched over to Radarr and stopped using CP, but only have movies added that haven't been released for dl yet. I haven't had any false results though so far using it with Jackett.

**Comment by kaso17** [comment]
Would appreciate if you could test it using one of the examples mentioned.

**Comment by testarea1** [comment]
Same issue with Radarr. I searched for "Sing 2016" and it came back with ANY results that had the the letters "sing" in it on all indexers I have added, so it's not specific to any 1 indexer:

![image](https://cloud.githubusercontent.com/assets/2273360/22393643/90f65d20-e4bf-11e6-8df9-25b5ea27f922.png)

**Comment by kaso17** [comment]
According too https://github.com/Radarr/Radarr/issues/508#issuecomment-275902297 Radarr shouldn't download the movies. Can someone confirm/deny that?

**Comment by chris0101** [comment]
i have the same problem with IP torrents .. is there no way to fix ?

**Comment by kaso17** [comment]
with IPT imdb shoud be used. please post a log.

**Comment by chris0101** [comment]
sorry i'm not followed, what do you mean imdb should be used  ? i literally have the same issues as the guys above ,

**Comment by chris0101** [comment]
anything?

**Comment by kaso17** [comment]
Using the Sing example the result would be the following query URL:
http://127.0.0.1:9117/potato/iptorrents/api?imdbid=tt3470600&search=Sing%202016&user=&passkey=XXX
This only returns 3 valid releases as it sends "tt3470600" as search query to IPT.
Please provide a log if you're getting different results.

**Comment by chris0101** [comment]
Oh you're right?! is this new ?  the other day couchpotato downloaded " how to be single " after looking for sing . i assume the " sing " in " single " triggered it . did you update recently ?

**Comment by kaso17** [comment]
For IPT it was added 21 days ago with ef7902b378764b7acaa77c44631d329ef939009e.

**Comment by chris0101** [comment]
Ah ok .it seems to be working now, sorry about that

**Comment by armani316** [comment]
@kaso17 Should this be closed or are you still waiting for more tests/confirmations?

**Comment by testarea1** [comment]
Seems ok now, I stopped using couch and switched to radarr and the radarr nightlys looked to have fixed most of the earlier issues. I'll close this, thanks all.
