### ISSUE TITLE
JAckett does not clean up /dev/shm - linux with systemd

### ISSUE THREAD

**Issue by phoenixv** [Jackett/Jackett#7361]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux with systemd (Fedora 31)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono 6.8.0.105

**.Net Version**:

**Jackett Version**: 21.1-testing-r2311

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?** [yes/no] no

### Description

When started by systemd Jackett does not clean up /dev/shm on shutdown leaving behind two files. 

Setting RemoveIPC=yes in the systemd unit file is a workaround/fix.

### Logged Error Messages

N/A

### Screenshots

N/A

**Comment by garfield69** [comment]
Since Jackett does not look for, or make use of your ramdisk by design, and does not deliberately save files for use with IPC, I presume that you have simply routed /tmp to /dev/shm to have a performance boost.
But files saved by Jackett to /tmp are not required to be deleted by Jackett when it is shutdown.
The system usually cleans up /tmp on reboot.
IMO therefore, you are responsible for cleaning up your ramdisk since the system will not do it for you, and Jackett is not required to do so.
But since I am not an expect on Linux I will now give way to the other team members with more knowledge on this topic.

**Comment by phoenixv** [comment]
/dev/shm is a location used by default for shared memory on unix systems. It is not a user defined ramdisk.

/tmp is still used normally on my system.

**Comment by garfield69** [comment]
so can you list which files have apparently been left behind on your ramdisk by jackett?

**Comment by phoenixv** [comment]
The files in the shared memory device /dev/shm, which is not user configurable or a ramdisk are

[usr@cine ~]$ ls -lZ /dev/shm
-rw-rw-rw-. 1 jackett jackett system_u:object_r:jackett_tmpfs_t:s0 4096 Feb 28 13:56 lttng-ust-wait-7
-rw-r-----. 1 jackett jackett system_u:object_r:jackett_tmpfs_t:s0 4096 Feb 28 13:56 lttng-ust-wait-7-1160200036

They seem to be consistently named across runs of the service. 

If you are unused to it *everything* in unix/linux systems is a file, it may not be a drive or device at all. For example /dev/kmem (typically not enabled, but still available) is a "file" that points to the entirety of your RAM. It takes a bit of getting used to.

**Comment by garfield69** [comment]
@ngosang  @cadatoiva  @junglebus this one is for you, its out of my area of expertise.

**Comment by cadatoiva** [comment]
I don't use Linux, only FreeBSD and Windows so I can't help with this one. @ngosang has a linux test box.

**Comment by ngosang** [comment]
@phoenixv those files are created by Mono runtime. We recommend you to use .Net builds instead of Mono btw.

Is this causing any problem/malfunction? Are those files removed after reboot?
I'm not an expert in IPC, if you think it's important and it's safe, I can add `RemoveIPC=yes` in the unit file.

**Comment by phoenixv** [comment]
>We recommend you to use .Net builds

I am able to make that switch. I will test with that version. 

The files being leftover were found in the context of developing an SElinux policy to contain Jackett and friends (Plex, Sonar, Radarr etc.) Their not being removed cause 30 minutes of head scratching as to why the proper context was not being assigned on creation. (answer: they were not being created as they were not being destroyed on shutdown.) So only a few hairs in my head were harmed.

**Comment by ngosang** [comment]
When you finish your tests tell me if you want to add `RemoveIPC=yes` in the unit file (Mono build only) and I will.

**Comment by phoenixv** [comment]
My initial version which produced the files in /dev/shm was already the AMDx64 version, which I believe is compiled with .NET. Apparently it is .NET which pulls in lttng-ust as a dependency and that is what creates the files in /dev/shm.

uninstalling lttng-ust on the runtime host makes them stop appearing. Compiling it on a host without lttng-ust installed works fine and no longer produces the tracepoints in syslog or the /dev/shm files.

The mono version creates /dev/shm/mono.<pid> I have not yet tracked the purpose/cause of that file. 

Both seem to be somewhat at risk of a symlink attack as the filenames are fixed or highly predictable, if the debug can be disabled it may tighten things up a bit security wise. But ideally these servers have no local users as somewhat of a mitigation. 

It appears for an SElinux policy Ill need to include a few conditionals to cover both since the files and exe's between the two versions are slightly different. Thanks for helping me find that fact, saves a few bugs down the road.

**Comment by ngosang** [comment]
Since these files are created by Mono/.Net runtime I prefer to not touch them. If someone is having problems with SElinux he can change the policies as you did.
