### ISSUE TITLE
Inability to show dead torrents from IPTorrents (IPT) & HD-Torrents (HDT)

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#737]
Hey guys!

As the title suggests, when I use Jackett to search for torrents, either specifically on IPT & HDT, or across all the trackers/indexers that I have configured, dead torrents from IPT & HDT are not shown in the search results. When I search using the same keywords on IPT's & HDT's websites, I'm able to find the dead torrents in question. It's kinda odd because I'm able to see most (if not all) dead torrents from other trackers, except for these two.

**Comment by kaso17** [comment]
It should be an easy fix.
Can you please give me some search examples.
I tried e.g. "RegionFrii GUI v1 1 READNFO WII-SYNDiCATE" on IPtorrents and it shows up just fine in jackett.

For HDT I would also need an invite to fix it (kaso1717 -at- gmail.com)

**Comment by armani316** [comment]
With IPT, it tends to be fairly random. I just did a bunch of manual search queries (both on IPT specifically and across all my configured indexers), and the dead IPT torrents should up fine. I will report back once I find an example of this.

For HDT, it always happens. If it's dead, it won't show up. Unfortunately, I do not have an invite at the moment. Maybe someone else can help out with this?

**Comment by armani316** [comment]
@kaso17 You should be getting an invite on kaso1717 -at- gmail dot com later today :) Awaiting your confirmation!

This should take care of all open HDT issues!

**Comment by armani316** [comment]
@kaso17 You should be getting an invite on kaso1717 -at- gmail dot com later today :) Awaiting your confirmation!

This should take care of all open HDT issues!

**Comment by kaso17** [comment]
I just got one yesterday evening already, thank you anyway.

**Comment by kaso17** [comment]
@armani316 got the invite but I don't need it anymore, let me know if I should send it to someone else

**Comment by armani316** [comment]
@kaso17 Ignore it. It's been canceled.

**Comment by armani316** [comment]
@kaso17 For the IPT part of this issue, I did some more testing, and it might be part of a larger problem. Unlike HDT, it's not about dead torrents. Try the following:

- Do a manual search for '**Homeland**' across all your reconfigured indexers 
- Show 'all' entries, and then filter the output using the keywords 'Homeland **'S04 REMUX**'
- There are no results from IPT & TorrentLeech (at least at my end)
- Search for **Homeland S04 REMUX** on IPT's & TL's websites - you'll find it there, even though it didn't show up in Jackett. 

If you search for **Homeland S04 REMUX** on Jackett in the first place, the IPT & TL results will show up, However, I typically do not use keywords that are too specific since some trackers (e.g. BeyondHD) will not return results if you enter anything other than the actual movie/show title. For example, entering. season number, rip type, resolution, etc. will cause BeyondHD [and maybe others trackers?] not to return results, However, that's how BHD's search works on the website, and I do not think anything can be done about it in Jackett)

**Comment by armani316** [comment]
EDIT: The IPT & TL problem seems to be caused by the 'number of torrents displayed on each page' option in my profile in each tracker. I believe other trackers may be suffering from the same issue - Hidden results due to the low number of torrents per page in profile settings. 

Jackett doesn't display a note on this for IPT (but it does for TL). Might be a good idea to check for the consistency/presence of this message for the trackers in which torrents per page matters?

**Comment by kaso17** [comment]
I guess I'll put it as a general hint on all indexers

**Comment by armani316** [comment]
@kaso17 Is there a way to circumvent the tracker's max torrents per page limitation on Jackett? Even if the no. is set to max on the profile settings, sometimes the search results from a single tracker are higher than that number, and so the extra torrent results never get displayed in Jackett. For example, try searching for REMUX on Freshon.TV and compare the number of results to that in Jackett. Jackett only displays 100 (which is the max torrents / page on FreshonTV).

**Comment by kaso17** [comment]
Of course jackett could parse more/all pages. but that would put extra load on the tracker.
Very few indexers support this currently. 
I personally would never search for generic keywords like "REMUX", that could easily result in 10000 of results.
If you notice that indexers doesn't support searching for season/episode (beyond HD?) please let us know. The workaround for this is to strip the SXXEXX from the search string sent to the tracker and filter the results in jackett.

**Comment by armani316** [comment]
@kaso17 I agree. I don't usually use generic keywords either. In this case (REMUX), I wanted an example that would result in something a little higher than a 100 [160ish results on FOTV], to see how Jackett would respond.

Only 100 entries came out, 60ish were left out. Apply this example to other (more reasonable) searches with similar number of results (either on a single tracker or multiple ones), and we end up omitting a number of results when searching on Jackett.

As for indexers that do not support certain search keywords, for now I only know of BeyondHD - doesn't like rip type and resolution in keywords. Even searching on BHD's page doesn't output anything when such keywords are used alongside the movie's or show's title.
