### ISSUE TITLE
ImmortalSeed, FunFile & AlphaReign keep signing me out

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#738]
Hey guys! For some odd reason, ImmortalSeed, FunFile & AlphaReign keep signing me out all the time. Whenever I need to start a new manual search session, these are the only tackers for which I have to sign back in over and over again. They'll keep me signed in while I'm still conducting a search, but if I exit and come back in a few hours, they will have both signed me out. All my other indexers work fine, and do not require me to sign in so often. Can this be fixed? Thank you!

**Comment by kaso17** [comment]
should be fixed

**Comment by armani316** [comment]
Fixed for IS & FF (THANK YOU!) but the problem is still there for AlphaReign.

**Comment by kaso17** [comment]
Did you compile it yourself (The changes aren't released yet)?

**Comment by armani316** [comment]
No, but it seems that FF & IS are working fine (for now)! They haven't worked fine for weeks (since I joined them).

**Comment by kaso17** [comment]
It's broken again in the latest stable release, should be fixed with the pre releases.
