### ISSUE TITLE
Change in Cloudflare anti-DDoS breaking Jackett 

### ISSUE THREAD

**Issue by cadatoiva** [Jackett/Jackett#7397]
This is caused by a new Cloudflare challenge that affect many sites => https://github.com/RyuzakiH/CloudflareSolverRe/issues/14
Affected so far:
* badasstorrents
* extratorrent-cd
* bteye
* limetorrents
* Torrentz2
* 1337x
* SpaceTorrent
* Pirateiro

_Originally posted by @ngosang in https://github.com/Jackett/Jackett/issues/7325#issuecomment-592773894_

**Comment by ashanrath** [comment]
Also appears to be impacting 1337x.

**Comment by thorrrr** [comment]
After update today Torrents HD fixed but 1337x & Torrentz2 still failing see [here](https://nextcloud.daddycloud.co.uk/s/7ZHfFDoi534Y723)

New log [here ](url)https://nextcloud.daddycloud.co.uk/s/FM6isJE4fCg8TCy

**Comment by fadedmartian** [comment]
This still appears to be broken as of v0.13.506... This is the most recent update that I am able to update to.. Am I missing something here? I am getting the following error in my logs relating to Torrentz2; https://pastebin.com/g49kDrNJ.

**Comment by garfield69** [comment]
yes, you are missing something ;-b
the release that includes the fix has not been published yet ;-D
expect the fix to be available when the next released is published in about 10 hours or so.

**Comment by fadedmartian** [comment]
> yes, you are missing something ;-b
> the release that includes the fix has not been published yet ;-D
> expect the fix to be available when the next release is published in about 10 hours or so.

ahhh that makes sense-- I appreciate the info and dedication! :)

**Comment by garfield69** [comment]
Jackett 0.13.529

**Comment by alpe12** [comment]
Still an issue on 0.16.252.0.

**Comment by garfield69** [comment]
@alpe12  no, not `still an issue`, but a **new** issue, with cloudflare changing their challenge a few days ago.
follow #8464 for progress/updates on this issue.
