### ISSUE TITLE
Configuration failed: Found no results while trying to browse this tracker 

### ISSUE THREAD

**Issue by laxstar18** [Jackett/Jackett#74]
2 of my trackers added no issue, 2 others Bitme and Scenetime gave this error. After restarting Jackett they do now show up however when I try to add them into Sonarr I get the same No results while trying to browse this tracker error

**Comment by flightlevel** [comment]
We need logs
https://github.com/Jackett/Jackett#troubleshooting

**Comment by slim186** [comment]
I'm getting the same error trying to set up BitMeTV in Jackett.  I have Force SSL off and Login Type = Normal in the BitMeTV profile settings.

Log:
12-17 10:34:11 Debug UnixLibCurlWebClient:GetBytes(Url:http://www.bitmetv.org/index.php)
12-17 10:34:12 Debug UnixLibCurlWebClient:GetBytes Returning OK => 61948 bytes
12-17 10:34:12 Debug UnixLibCurlWebClient:GetString(Url:https://www.bitmetv.org/browse.php?search=&cat=0)
12-17 10:34:12 Debug UnixLibCurlWebClient:GetString Returning InternalServerError =>
12-17 10:34:12 Info Found 0 releases from BitMeTV
12-17 10:34:12 Error Exception in Configure System.Exception: Found no results while trying to browse this tracker
  at Jackett.Services.IndexerManagerService+<TestIndexer>c__async0.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>:0
  at Jackett.Controllers.AdminController+<Configure>c__async4.MoveNext () [0x00000] in <filename unknown>:0
12-17 10:34:12 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
12-17 10:34:12 Info ApiControllerActionInvoker InvokeActionAsync
System.Web.Http.Action: ApiControllerActionInvoker InvokeActionAsync
12-17 10:34:12 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()'
System.Web.Http.Filters: JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()'
12-17 10:34:12 Info JackettAPINoCacheAttribute OnActionExecutedAsync
System.Web.Http.Filters: JackettAPINoCacheAttribute OnActionExecutedAsync
12-17 10:34:12 Info AdminController ExecuteAsync
System.Web.Http.Controllers: AdminController ExecuteAsync
{"name":"BitMeTV","result":"error","error":"Found no results while trying to browse this tracker"}
12-17 10:34:12 Debug Response: {"name":"BitMeTV","result":"error","error":"Found no results while trying to browse this tracker"}
12-17 10:34:12 Info WebAPIRequestLogger SendAsync
System.Web.Http.MessageHandlers: WebAPIRequestLogger SendAsync
12-17 10:34:12 Info   Content-type='application/json; charset=utf-8', content-length=98
System.Web.Http.Request:   Content-type='application/json; charset=utf-8', content-length=98
12-17 10:34:12 Info AdminController Dispose
System.Web.Http.Controllers: AdminController Dispose
12-17 10:34:12 Info AdminController Dispose
System.Web.Http.Controllers: AdminController Dispose

**Comment by Mochaka** [comment]
I get the same error as above ^

**Comment by xllnk** [comment]
I'm getting the same error as well with Bitmetv. Running Windows 10 with firewall disabled for troubleshooting. 
I have bitmetv set up properly in sonarr, however it doesn't have search functionality. Here are my logs: http://pastebin.com/LwnZWwRe

**Comment by raspdealer** [comment]
Have you tried with the last version?

**Comment by slim186** [comment]
Same error here.  Using 0.7.121 mono release.

**Comment by flightlevel** [comment]
@slim186  Do you have Force SSL ticked in your Bitmetv profile page?

**Comment by kaso17** [comment]
I assume this is no longer a problem
