### ISSUE TITLE
[req] Add new public tracker Academic Torrents

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7405]
Academic Torrents
http://academictorrents.com

Related:
* https://github.com/qbittorrent/search-plugins/issues/121#issuecomment-592998792
* https://raw.githubusercontent.com/solenskiner/search-plugins/master/nova3/engines/academictorrents.py

**Comment by garfield69** [comment]
Jackett 0.13.405

**Comment by ilike2burnthing** [comment]
https://academictorrents.com/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
aaaaand back up

**Comment by garfield69** [comment]
the site has introduced a browser checking intermediate stage https://academictorrents.com/check.htm before results from a search from https://academictorrents.com/browse.php?search=&sort_field=added&sort_dir=DESC is returned

this breaks the cardigann yaml indexer's ability to process results
.
Assuming this is a DDoS security measure, then hopefully it will be lifted.

**Comment by ilike2burnthing** [comment]
Skinned Cloudflare?

```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
--
  | <meta name="robots" content="noindex, follow">
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
  | <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
  | <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap-theme.min.css" rel="stylesheet">
  | <script async src="https://media.ethicalads.io/media/client/ethicalads.min.js"></script>
  | <script async src="/res/adlogic.js?asa"></script>
  | <link href="/res/carbon.css" rel="stylesheet">
```

**Comment by ieee8023** [comment]
Hey, I am representing Academic Torrents here. We added the simple browser check because our server was becoming overloaded with irrelevant search traffic that seemed to be scripts. We cannot handle the search used as an API at this time. 

I can imagine that your users are interested in the video lectures on the site? Maybe there is a better way of integrating? Maybe we can offer a full RSS feed of all torrents with a title and description and you can perform a local search?

**Comment by garfield69** [comment]
@ieee8023 Apologies if we have contributed towards overloading your server.

I think it best for now that we remove this indexer from Jackett to avoid further issues.

If any C# developer on the Jackett side gets the free time and interest to rework this indexer, we can initiate a dialogue with you about better integration.
