### ISSUE TITLE
[req] Add new public tracker ali213.net

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7406]
ali213.net
https://down.ali213.net/

Related:
* https://github.com/qbittorrent/search-plugins/issues/121#issuecomment-592998792
* https://raw.githubusercontent.com/hannsen/qbittorrent_search_plugins/master/ali213.py

**Comment by garfield69** [comment]
there is no .torrent or magnet on the torrent details page, rather further links that take you to still other pages where eventually there is something, maybe.
too many steps for the current Cardigann processor which expects a href on the details page to point to the .torrent or magnet without additional html to process.
This indexer will need to be written in C#

**Comment by ilike2burnthing** [comment]
ERR_CONNECTION_TIMED_OUT
