### ISSUE TITLE
[req] Add new public tracker small-games.info

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7408]
small-games.info
https://small-games.info/

Related:
* https://github.com/qbittorrent/search-plugins/issues/121#issuecomment-592998792
* https://raw.githubusercontent.com/hannsen/qbittorrent_search_plugins/master/smallgames.py

**Comment by garfield69** [comment]
this site is not compatible with the cardigann processor.
the reason being that if the search keywords are sufficiently unique to isolate a particular game then the site will jump to the details page for that game instead of presenting a results page.
this indexer will need to be coded in c#

**Comment by garfield69** [comment]
closing as stale.
