### ISSUE TITLE
xspeeds - unhandled exception

### ISSUE THREAD

**Issue by manderss99** [Jackett/Jackett#741]
attaching log output

[xspeeds.zip](https://github.com/Jackett/Jackett/files/614081/xspeeds.zip)

**Comment by kaso17** [comment]
looks like you're getting a HTML page returned instead of the RSS feed.
It's not a general issue, it works for me.
Please try deleting/reading xspeeds.

**Comment by manderss99** [comment]
it suddenly started working again without any change from my part ....  closing.
