### ISSUE TITLE
Proxy settings not being removed until manual restart of tray or container

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#7411]
"So I started up a sandbox and ran a fresh copy of the Windows binaries for Jackett in it [...and added a NordVPN server for the proxy. It worked as it should].

I removed the proxy [...], applied and let it refresh, tested again [...but it behaved as if the proxy settings were still applied]. It wasn't until I shutdown the tray program and restarted it that [...it behaved as if the proxy settings were removed].

To test this in my actual Docker Jackett install I removed the proxy, applied, let it refresh, tested, [...and it behaved as if the proxy settings were still applied]. Applying server settings multiple times didn't help. So I restarted the container via Portainer, and only then did [...it behave as if the proxy settings were removed].

Whatever is happening during that refresh isn't actually removing the proxy settings. I've confirmed this by successfully running tests on indexers which should fail without the proxy, [and having a test fail which should succeed - BadassTorrents,] both in the Docker container and the sandboxed Windows install."

https://github.com/Jackett/Jackett/issues/7325#issuecomment-591221455

**Comment by cadatoiva** [comment]
I'll test with my VPN-Secure proxy soon and see why this isn't working

**Comment by ilike2burnthing** [comment]
Small update. It seems you can change the specific server and it will apply on refresh (e.g. test when having changed from uk####.nordvpn.com to au###.nordvpn.com take noticeably longer). So it's just removing the proxy altogether which doesn't apply, until Jackett is manually restarted.

**Comment by cadatoiva** [comment]
What about when going from no proxy to any proxy? Does that work as expected?

**Comment by ilike2burnthing** [comment]
Oh, yea, that works fine.

Likewise, if you go from a non-existent URL (which I definitely did on purpose as a test, and not at all by accidental typo...) to a real proxy, it applies on refresh and works as it should.

**Comment by cadatoiva** [comment]
So the proxy settings work as expected for every situation except for removing a proxy that was already applied. This really helps narrow it down, thanks!

Because I was having trouble finding a problem with the code in those other scenarios.

**Comment by cadatoiva** [comment]
Ok, I think I found it. Last question to make sure, your proxy type is http? or socks(4/5)?

**Comment by ilike2burnthing** [comment]
http

Thanks for all your work!

**Comment by cadatoiva** [comment]
I thought so. Literally the only way the code would break is if you tried to remove an http proxy, no wonder it was left uncaught for so long, and so hard to track down...

**Comment by garfield69** [comment]
Jackett 0.14.49
