### ISSUE TITLE
[torrentgalaxyorg] The operation was canceled. (Config)

### ISSUE THREAD

**Issue by VulcanTourist** [Jackett/Jackett#7414]
### Environment
**OS**: Asustor 6510T, latest ADM
**.Net Runtime**: unknown
**.Net Version**: unknown
**Jackett Version**: 0.13.201.0
**Last Working Jackett Version**: n/a
**Are you using a proxy or VPN?** yes (NordVPN)

### Description
I am unable to add this indexer in Jackett.  I tried experimenting with manual configuration, but no changes had any positive effect.  Selecting the [+] button next to it results in a brief delay and then a return to the Dashboard and Configured Indexers with no (toast) error.  Only manual configuration results in an error.

### Logged Error Messages
An error occured while configuring this indexer
The operation was canceled.

(BTW, the proper spelling is **occurred**, not "occurred"; someone might want to correct that.)

**Comment by cadatoiva** [comment]
This might be related to #7397 please post the full logs surrounding the configuration to confirm
