### ISSUE TITLE
[TorrentLeech.pl] Returning irrelevant results & returning no results when the release year is entered

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7424]
### Environment

**OS**: Windows 10 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.13.280.0

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?** No

### Description

Searching TorrentLeech. pl via Jackett returns a large number of irrelevant results. E.g. Try searching the indexer for 'The Morning Show'. The tracker will return 14 results, none of which is relevant. Would 'andmatch' solve this?

### Logged Error Messages

N/A

### Screenshots

N/A

### Enhanced Log

N/A

**Comment by garfield69** [comment]
Jackett 0.13.405

**Comment by RoloSoze** [comment]
@garfield69 I just realized that this tracker does not return any results when the year is entered in the search string. This is actually consistent with the search behavior via the website. Is this fixable?

**Comment by garfield69** [comment]
yes, we could use the keywords filter to strip out 4-digit strings.

**Comment by garfield69** [comment]
but its not specific so it will do this for all titles, be they movies, series or music.
still want to strip it?

**Comment by RoloSoze** [comment]
> 
> 
> but its not specific so it will do this for all titles, be they movies, series or music.
> still want to strip it?

I guess it'll work well most of the time? I can see it being a problem for something like the movie 1917 where the whole title only consists of 4 digits, but the for the most part, I think it'll work well.

What do you think?

**Comment by garfield69** [comment]
so don't strip the year if its the first keyword? yes I think we can do that... i'll do some research.

**Comment by RoloSoze** [comment]
> so don't strip the year if its the first keyword?

Exactly. This way, in titles like `2019: After the Fall of New York`, and `1990: The Bronx Warriors` the digits won't be affected, and in titles like, `The Exterminators of the Year 3000`, removing 3000 won't impact the search results much since the rest remains intact.

**Comment by RoloSoze** [comment]
@ngosang Can something similar be done for AHD Issue A in https://github.com/Jackett/Jackett/issues/7829#issue-586750395? At least temporarily until it's fixed in the API.

**Comment by cadatoiva** [comment]
re_replace can use `^` to indicate beginning of the text. So something like `^\D.*(\d{4})` would say at least one non-digit character has to come between the beginning of the string and 4 digits in a row.

**Comment by RoloSoze** [comment]
The only issue I can think of, which I guess is very rare, is when the user searches for something like `The 4400` which is a television series. 

This is a case of a non-digit character that has come before 4 digits in a row, the 4 digits are mistaken for a year, are removed, and so now the search is only for the word `The`. The solution, if at all possible, is to remove the 4 digits if they are not the first keyword - as we mentioned before - AND they start with either `19` or `20`.

I'm bringing this up in case this needs to be extrapolated and implemented for other trackers that do not like the year in the search string, and from my experience, the only other one I know of is Awesome-HD.

**Comment by garfield69** [comment]
when we go looking for the year we can use a mask to narrow down the 4 digits to those most likely to be a year
`((?:20|1[7-9])\\d{2})`

**Comment by RoloSoze** [comment]
Is there a need for the 7 & 8 in the range?

**Comment by garfield69** [comment]
I just grabbed an example out of an exiting indexer to illustrate the possibility. 
it could just as easily be 19|20\d{2}

**Comment by garfield69** [comment]
so give me an example of titles that you believe torrentleech.pl is choking on when the year is included?

**Comment by RoloSoze** [comment]
> 
> 
> so give me an example of titles that you believe torrentleech.pl is choking on when the year is included?

`Little Women 2019` - Returns 0 instead of 8
`Coco 2017`- Returns 2 instead of 10
`Avengers: Endgame 2019` - Returns 0 instead of 36
`1917 2019` - Returns 6 instead of 15

On the contrary:
`Titanic 1997` - All 4 results are returned

**Comment by garfield69** [comment]
I can fix everything but `1917 2019` since that is two sets of years and so the filter will leave them both in since the query does not begin with a non-digit.
still, better than nothing for the rest.

**Comment by RoloSoze** [comment]
> 
> 
> I can fix everything but `1917 2019` since that is two sets of years and so the filter will leave them both in since the query does not begin with a non-digit.
> still, better than nothing for the rest.

That would be good enough, but if I understand correctly, only 1917 will be left in; 2019 will be removed because it is preceded by a numeric string. @cadatoiva mentioned that the check can be done/restricted only for non-numric chcaratcers.

**Comment by garfield69** [comment]
no, re-read 
https://github.com/Jackett/Jackett/issues/7424#issuecomment-618169741

**Comment by RoloSoze** [comment]
> 
> 
> no, re-read
> [#7424 (comment)](https://github.com/Jackett/Jackett/issues/7424#issuecomment-618169741)

Got it. Is it possible to instruct that in the case two sets of 4-digits, that are possibly years (i.e. 19 or 20), remove only the latter set? Is it worth doing that, or will it be overly complicated?

**Comment by garfield69** [comment]
I'll mull it over in the next few days and see if I can improve it.

**Comment by ngosang** [comment]
@garfield69 try this: `[" (?:19|20)\\d{2} *$", ""]`

**Comment by RoloSoze** [comment]
https://en.wikipedia.org/wiki/List_of_television_programs:_numbers
https://en.wikipedia.org/wiki/List_of_films:_numbers

I'll use some titles from these lists to test later when I get the chance for both TL.pl & AHD in #8342. Thought you guys might find it handy.

**Comment by garfield69** [comment]
Jackett 0.16.127

**Comment by handokota** [comment]
Looks like https://torrentleech.pl is gone and the domain now just redirects to https://aftermarket.pl

**Comment by garfield69** [comment]
#7014
