### ISSUE TITLE
[REQ] kinonavse100.com

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#7425]
KINONAVSE100 is a RUSSIAN Semi-Private Torrent Tracker for MOVIES.

Example URL: http://kinonavse100.com/search.php?sr=topics&tracker_search=torrent&fid[]=61&keywords=2019

**Comment by garfield69** [comment]
Jackett 0.13.446

**Comment by garfield69** [comment]
http://kinonavse100.com/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
the web sites search engine is not returning any results, appears to be broken?

**Comment by ilike2burnthing** [comment]
Working ok here, though keywordless search doesn't as there are no results for `2021` on the site - http://kinonavse100.com/search.php?tracker_search=torrent&keywords=2021&terms=all&author=&sc=1&sf=titleonly&sr=topics&sk=t&sd=d&st=0&ch=300&t=0&submit=Search (change that to `2020`, `720p`, or something else and you get results)

**Comment by garfield69** [comment]
ah. 
going to new a new keyword-less search default then.... any suggestions?

**Comment by ilike2burnthing** [comment]
If we change to:
`tracker_search: "{{ if .Keywords }}torrent{{ else }}tracker{{ end }}"`
we get recent results while still using `.Today.Year`.

http://kinonavse100.com/search.php?tracker_search=tracker&keywords=2021&terms=all&author=&sc=1&sf=titleonly&sr=topics&sk=t&sd=d&st=0&ch=300&t=0&submit=Search

**Comment by garfield69** [comment]
Hah, nice find.

**Comment by garfield69** [comment]
http://kinonavse100.com/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
http://kinonavse100.com/ returns domain expired

**Comment by garfield69** [comment]
v0.20.2318
