### ISSUE TITLE
[ncore] tracker is not working after convert to AngleSharp

### ISSUE THREAD

**Issue by likeaRAINBOW** [Jackett/Jackett#7430]
#6840 # Environment

**OS**: Ubuntu 18.04

**.Net Runtime**: [Mono]

**Jackett Version**: 0.13.378.0

**Last Working Jackett Version**: v0.13.280

**Are you using a proxy or VPN?** reverse proxy

### Logged Error Messages
[jackett_ncore.log](https://github.com/Jackett/Jackett/files/4271963/jackett_ncore.log)

see in attached file

**Comment by garfield69** [comment]
Jackett 0.13.405
