### ISSUE TITLE
[funfile] Exception (funfile): The string did not match the expected pattern.: Parse error (Test)

### ISSUE THREAD

**Issue by jashzen** [Jackett/Jackett#7436]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: CentOS 7

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:  0.13.378.0

**Last Working Jackett Version**: Not sure, was working yesterday.

**Are you using a proxy or VPN?** no
### Description

Test FunFile connection and fails

### Logged Error Messages

Jackett.Common.IndexerException: Exception (funfile): The string did not match the expected pattern.
 ---> System.Exception: Parse error
 ---> AngleSharp.Dom.DomException: The string did not match the expected pattern.
   at AngleSharp.Dom.QueryExtensions.CreateSelector(INodeList nodes, INode scope, String selectorText)
   at AngleSharp.Dom.QueryExtensions.QuerySelector(INodeList nodes, String selectorText, INode scopeNode)
   at AngleSharp.Dom.Element.QuerySelector(String selectors)
   at Jackett.Common.Indexers.FunFile.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/FunFile.cs:line 122

**Comment by garfield69** [comment]
likely due to #7369

**Comment by garfield69** [comment]
Jackett 0.13.405

**Comment by jashzen** [comment]
This was resolved, but is now a issue again.

**Comment by garfield69** [comment]
@jashzen  Could you upload the HTML source code?

- Please, open funfile in your browser and go to the list of torrents and perform the same search as in Jackett
- Right click, save page as HTML
- Remove personal information from the HTML file (without breaking the code)
- drag/drop the html file here (use txt extension)

Thanks.

**Comment by jashzen** [comment]
[FunFile-Search.txt](https://github.com/Jackett/Jackett/files/4308871/FunFile-Search.txt)

**Comment by jashzen** [comment]
Let me know if you need anything else

**Comment by ngosang** [comment]
@jashzen In your HTML the download links are disabled (not found). I don't know if you don't have enough ratio or something.
@garfield69 What should we do in this case? If there isn't download link we should skip the torrent and not return in the results?

**Comment by jashzen** [comment]
Sorry I was disabled for downloads, that was the issue.

**Comment by cadatoiva** [comment]
@ngosang if we do filter results that are missing a download link, this should be done in the BaseIndexer so it applies to all trackers. Preferably here I think: https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/BaseIndexer.cs#L317-L345

**Comment by garfield69** [comment]
>What should we do in this case? If there isn't download link we should skip the torrent and not return in the results?

the torznab specs expect that we always return a download link when we provide a torrent result, whether that is a direct link for a .torrent or magnet from the primary search page results from the site, or a link to the Jackett cache that subsequently resolves a download link from the details page.

So in cases where a download link is not available we normally drop the torrent result, because apps using the torznab Jackett api expect a download link to be resolvable or they will generate an error.

**Comment by ngosang** [comment]
> if we do filter results that are missing a download link, this should be done in the BaseIndexer so it applies to all trackers.

I prefer to treat this case as an exception. In most cases, when we can't find the download link is due to a change in the webpage.

**Comment by garfield69** [comment]
Jackett 0.13.625
