### ISSUE TITLE
[FunFile] Exception (FunFile): Input string issue

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7451]
### Environment

**OS**: Windows 10 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.13.405.0

**Last Working Jackett Version**: Not sure

**Are you using a proxy or VPN?** No

### Description

I'm unable to configure FunFile anymore.

### Logged Error Messages

Exception (funfile): Input string was not in a correct format.: Parse error

### Screenshots

N/A

### Enhanced Log
[log.txt](https://github.com/Jackett/Jackett/files/4274999/log.txt)

**Comment by dannymichel** [comment]
i have the sme issue

**Comment by garfield69** [comment]
caused by #7369 
uploadvolumefactor can be missing from results. for that matter, so could downloadvolumefactor.
https://github.com/Jackett/Jackett/blob/1563418d88cf61e7178b725877c8bcefd3fdc21d/src/Jackett.Common/Indexers/FunFile.cs#L153-L156

**Comment by ngosang** [comment]
@RoloSoze @benburdick @jashzen Could you upload the html source code? That will help a lot.

1. Please, open funfile in your browser and go to the list of torrents
2. Right click, save page as html
3. Remove personal information from the HTML file (without breaking the code)
3. Upload the html file here.

**Comment by RoloSoze** [comment]
@ngosang Here you go.
[FunFile   Browse Torrents.zip](https://github.com/Jackett/Jackett/files/4277962/FunFile.Browse.Torrents.zip)

**Comment by ngosang** [comment]
Thank you. I'm on it.

**Comment by garfield69** [comment]
Jackett 0.13.427
