### ISSUE TITLE
Jacket Error with HDTS and every other Torrentsite 

### ISSUE THREAD

**Issue by thorrrr** [Jackett/Jackett#7452]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment Docker

**OS**: Unraid 

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Version 0.13.378.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] No

### Description

Getting an error on every connection bar 1 torrent

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots  [HERE](https://nextcloud.daddycloud.co.uk/s/sC4TowwYZrjTYRT)

[Place any screenshots of the issue here if needed]

**Comment by cadatoiva** [comment]
Please post your logs from $data-dir/log.txt with the errors included.

**Comment by thorrrr** [comment]
Please see log [HERE](https://nextcloud.daddycloud.co.uk/s/ZfKs37NYSrXym6q)

**Comment by garfield69** [comment]
This is likely related to #7397

**Comment by ngosang** [comment]
Closed by #7546
