### ISSUE TITLE
[animetosho] Exception (animetosho): The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3.: The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3. (Test)

### ISSUE THREAD

**Issue by shimmyshine** [Jackett/Jackett#7456]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.13.405.0

**Last Working Jackett Version**: 0.13.405.0

**Are you using a proxy or VPN?** [yes/no] no

### Description

Looks like the site got updated and the scraper hasn't been yet.  Information is in the title and listed below.

### Logged Error Messages

[animetosho] Exception (animetosho): The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3.: The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3. (Test)

**Comment by ngosang** [comment]
This is not caused by recent changes in Jackett.

@shimmyshine Could you upload the HTML source code? That will help a lot.

1. Please, open animetosho in your browser and go to the list of torrents
2. Right click, save page as HTML
3. Remove personal information from the HTML file (without breaking the code)
4. Upload the html file here.

**Comment by ngosang** [comment]
@soulvoid86 could you provide the information requested in the previous comment?

**Comment by mirolm** [comment]
Here is the html content of the main page. It has torrents listed in there. Hope it helps.

[Anime Tosho _ Anime Tosho.html.zip](https://github.com/Jackett/Jackett/files/4281338/Anime.Tosho._.Anime.Tosho.html.zip)

**Comment by ngosang** [comment]
Thank you! I will take a look later.

**Comment by ngosang** [comment]
@mirolm Sorry, but I need the XML instead => https://animetosho.org/feed/api

**Comment by garfield69** [comment]
@ngosang  animetosho is public, surely you can fetch the xml yourself ;-)

**Comment by mirolm** [comment]
Attaching the xml too if needed.

[api.txt.zip](https://github.com/Jackett/Jackett/files/4283598/api.txt.zip)

**Comment by garfield69** [comment]
Jackett 0.13.446
