### ISSUE TITLE
[bitcityreloaded / myamity] Exception (bitcityreloaded / myamity): Input string was not in a correct format.: Parse error (Config)

### ISSUE THREAD

**Issue by karbrueggen1** [Jackett/Jackett#7459]
Hey there,

the current Jackett Version (v0.13.405) broke two of the private Trackers i'm using: Bit-City and MyAmity.
Last working Version is: v0.13.228
I'm using Mono JIT compiler version: 5.20.1.34

Here is the Error Log for MyAmity: https://pastebin.com/raw/WbZax7A5

**Comment by garfield69** [comment]
bitcityreloaded broken by #7357 
myamity broken by #7377 but hopefully fixed with 9826e2c2afe3c00aa519c1ada1457d83cc5417da but should be checked again just to be sure.

**Comment by ngosang** [comment]
@karbrueggen1 Could you upload the html source code? That will help a lot.

1. Please, open bitcityreloaded / myamity in your browser and go to the list of torrents
2. Right click, save page as html
3. Remove personal information from the HTML file (without breaking the code)
3. Upload the html file here.

Do it for both sites please.

**Comment by karbrueggen1** [comment]
> @karbrueggen1 Could you upload the html source code? That will help a lot.
> 
> 1. Please, open bitcityreloaded / myamity in your browser and go to the list of torrents
> 2. Right click, save page as html
> 3. Remove personal information from the HTML file (without breaking the code)
> 4. Upload the html file here.
> 
> Do it for both sites please.

Here you go, hope this is what you need:

[bitcityreloaded_uebersicht.php.txt](https://github.com/Jackett/Jackett/files/4277499/bitcityreloaded_uebersicht.php.txt)
[myamity_torrents-search.php.txt](https://github.com/Jackett/Jackett/files/4277500/myamity_torrents-search.php.txt)

**Comment by ngosang** [comment]
That's perfect. I'm working on it.

**Comment by ngosang** [comment]
@garfield69 I confirm myamity is fixed with 9826e2c (at least for the html provided by the user)

**Comment by garfield69** [comment]
Jackett 0.13.427
