### ISSUE TITLE
[REQ] Secret-Cinema

### ISSUE THREAD

**Issue by savahu** [Jackett/Jackett#746]
Tracker: secret-cinema.net
Genre: movie tracker that specializes in obscure content including silent films, classics, cult, arthouse.

I currently have no invites, but in the next week I will.

**Comment by armani316** [comment]
@savahu Got an invite yet? Would love it if Secret-Cinema is added!

**Comment by savahu** [comment]
Yes, I sent it to @kaso17 just now!

**Comment by kaso17** [comment]
got it, thank you

**Comment by savahu** [comment]
@kaso17 Thanks very much.
Does it work correctly for you, also using the 'Test' button?
Currently I get ' Test failed for secretcinema: Found no results while trying to browse this tracker' when clicking the test button.

**Comment by kaso17** [comment]
Works fine for me. please make sure you're running the latest pre-release.
If you're already doing send me a log.

**Comment by armani316** [comment]
@kaso17 Works fine for me on pre-release v0.7.754. Test passed. Search results obtained.

**Comment by savahu** [comment]
@kaso17 Thanks, I updated to that version, re-entered my credentials and now it works :)

**Comment by garfield69** [comment]
https://secret-cinema.pw/ ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up
