### ISSUE TITLE
[ImmortalSeed] Exception (immortalseed): String was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by geoffgs** [Jackett/Jackett#7461]
### Environment
**OS**: 
FreeBSD
**.Net Runtime**: 
Mono
**.Net Version**: 
mono 5.20.1.34
**Jackett Version**: 
v0.13.405.0
**Last Working Jackett Version**: 
v0.13.378
**Are you using a proxy or VPN?** 
No

### Description
Testing the connection from GUI to ImmortalSeed and it fails

### Logged Error Messages
An error occured while updating this indexer
Exception (immortalseed): String was not recognized as a valid DateTime.: Parse error
[jackett.log](https://github.com/Jackett/Jackett/files/4277224/jackett.log)

### Screenshots
![image](https://user-images.githubusercontent.com/14260308/75704864-2e480180-5c88-11ea-88e3-f11f4077000e.png)

**Comment by ngosang** [comment]
Probably caused by #7375

@geoffgs Could you upload the html source code? That will help a lot.

Please, open https://immortalseed.me/browse.php in your browser (the list of torrents), right click, save page as html and upload the html file here. Remove personal information.

**Comment by geoffgs** [comment]
Hi @ngosang, the jackett.log I attached to the original appeared to have the browse page requested. Please let me know if you need another.

**Comment by ngosang** [comment]
@geoffgs I didn't see, its enough for now. I'm on it.

**Comment by garfield69** [comment]
Jackett 0.13.427
