### ISSUE TITLE
404 on DL link for Elite-Tracker

### ISSUE THREAD

**Issue by bilyboy785** [Jackett/Jackett#7463]
### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono

**.Net Version**:

**Jackett Version**: 0.13.405.0

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?** [yes/no] yes

### Description

Start a search on Jackett based on Elite Tracker. In the result lits, click on the download Button.

### Logged Error Messages

404

`Aucune page Web trouvée à l'adresse :https://jackett.domain.com/dl/elitetracker/?jackett_apikey=dsssssssssssssssssssssssssssssssddsdsds&path=[LONG_QUERY]&file=Homeland.S08E04.SUBFRENCH.720p.WEB.H264-CiELOS`

**Comment by garfield69** [comment]
works for me.
![image](https://user-images.githubusercontent.com/6933240/75711440-4a50af00-5d2b-11ea-9a95-c0144f269dd9.png)

logon to the site with your browser and check that your ratio is good.
if that is OK, then look for any alerts that might prevent you from downloading. 
if necessary try to start a download from the site directly (click on a link but don't save, you just want to test not actually commit to a download).
let me know what you find out.

**Comment by bilyboy785** [comment]
OK my bad. it's my IDs.
Sorry for this.
