### ISSUE TITLE
[filelist] Exception (filelist): Object reference not set to an instance of an object: Parse error (Config)

### ISSUE THREAD

**Issue by sobmalag** [Jackett/Jackett#7474]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Freenas

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.13.427.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Probably broken by #7360
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by elvinu** [comment]
[jackett_log.txt](https://github.com/Jackett/Jackett/files/4280197/jackett_log.txt)

Environment
OS: Windows 10

.Net Runtime: [.Net-Core/.Net-Framework/Mono]

.Net Version: v4.0.30319

Jackett Version: 0.13.427.0

Last Working Jackett Version:

Are you using a proxy or VPN? [yes/no] no

Description
[List steps to reproduce the error and details on what happens and what you expected to happen]
I wanted to add FL to Sonarr and it gave an error. Opened Jackett and hitting test gives the error
` An error occured while testing this indexer
Exception (filelist): Object reference not set to an instance of an object.: Parse error
Click here to open an issue on GitHub for this indexer.`

Logged Error Messages
[Place any relevant error messages you noticed from the logs here.]

> 2020-03-03 10:44:24.7616 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) in 829.7117ms 
> 2020-03-03 10:44:24.9985 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)' 
> 2020-03-03 10:44:25.2331 Error Jackett.Common.IndexerException: Exception (filelist): Object reference not set to an instance of an object.
>  ---> System.Exception: Parse error
>  ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Jackett.Common.Indexers.FileList.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\FileList.cs:line 163
>    --- End of inner exception stack trace ---
>    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 830
>    at Jackett.Common.Indexers.FileList.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\FileList.cs:line 210
>    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 323
>    --- End of inner exception stack trace ---
>    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 343
>    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 803
>    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 220
>    at Jackett.Server.Controllers.IndexerApiController.Test() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 129
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70 Jackett.Common.IndexerException: Exception (filelist): Object reference not set to an instance of an object.
>  ---> System.Exception: Parse error
>  ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Jackett.Common.Indexers.FileList.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\FileList.cs:line 163
>    --- End of inner exception stack trace ---
>    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 830
>    at Jackett.Common.Indexers.FileList.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\FileList.cs:line 210
>    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 323
>    --- End of inner exception stack trace ---
>    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 343
>    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 803
>    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 220
>    at Jackett.Server.Controllers.IndexerApiController.Test() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 129
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70
> 2020-03-03 10:44:25.2555 Debug The response will be compressed with 'br'. 
> 2020-03-03 10:44:25.2555 Debug Connection id "0HLTV82MGHT2F" completed keep alive response. 
> 2020-03-03 10:44:25.2704 Info Request finished in 1445.899ms 500 application/json 
> 2020-03-03 10:45:49.7255 Debug Connection id "0HLTV82MGHT2G" disconnecting. 
> 2020-03-03 10:45:49.7477 Debug Connection id "0HLTV82MGHT2G" stopped. 
> 2020-03-03 10:45:49.7660 Debug Connection id "0HLTV82MGHT2G" sending FIN because: "The Socket transport's send loop completed gracefully." 
> 2020-03-03 10:46:26.7257 Debug Connection id "0HLTV82MGHT2F" disconnecting. 
> 2020-03-03 10:46:26.7257 Debug Connection id "0HLTV82MGHT2F" stopped. 
> 2020-03-03 10:46:26.7396 Debug Connection id "0HLTV82MGHT2F" sending FIN because: "The Socket transport's send loop completed gracefully."

 

[Make sure you attach the full logs with your personal information removed in case we need more information]

Screenshots

**Comment by ngosang** [comment]
I take this one.

**Comment by garfield69** [comment]
Jackett 0.13.446
