### ISSUE TITLE
new tracker freedom hd 

### ISSUE THREAD

**Issue by bidulle95** [Jackett/Jackett#750]
french tracker private 
http://freedom-paradise.eu

**Comment by kaso17** [comment]
added with 0e7ce1d38d49a5e58e60346bc14ac627a8da847a

**Comment by bidulle95** [comment]
hello is it possible to put an option for freeleech token please ?
I wish I could use them

**Comment by garfield69** [comment]
http://freedom-paradise.eu/ returning ERR_CONNECTION_TIMED_OUT 
anyone else having this issue ?

**Comment by garfield69** [comment]
still getting ERR_CONNECTION_TIMED_OUT from http://freedom-paradise.eu/
broken, gone or moved to new domain?
