### ISSUE TITLE
Jackett seems to no longer work at all?

### ISSUE THREAD

**Issue by miniliQuid** [Jackett/Jackett#7500]
**OS**:
Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
No clue

**.Net Version**:
No clue

**Jackett Version**:
0.11.723.0

**Last Working Jackett Version**:
Unknown

**Are you using a proxy or VPN?** [yes/no]
No

### Description
Simply put, every jackett indexer put into sonarr has suddenly stopped working (think since 2 or 3 days): Zooqle, 1337x, Torrentfunk, Torrentproject, ettv, eztv.

Now I do notice I can also no longer open the WEB UI when i press right mouse button on the tray Icon. It has been grayed out since the problems started. This makes me think jackett simply stopped booting correctly or so. Thus after checking the latest log, I noticed it stopped after 29-2-2020, right about the time the error's popped up and there is no error message, just an update message and I guess the update went wrong:

> 2020-02-29 13:38:57.6260 Info Jackett variant: CoreWindows 
> 2020-02-29 13:38:58.3979 Info New release found. Current: v0.13.228 New: v0.13.280 
> 2020-02-29 13:38:58.3979 Info Downloading release v0.13.280 It could take a while... 
> 2020-02-29 13:39:41.2782 Info Starting updater: C:\WINDOWS\TEMP\JackettUpdate-v0.13.280-637185803680814633\Jackett\JackettUpdater.exe --Path "C:\ProgramData\Jackett" --Type "WindowsService" --Args " " --KillPids "6628" 
> 2020-02-29 13:39:41.3273 Info Updater started process id: 9304 
> 2020-02-29 13:39:41.3368 Info Signal sent to lock service 
> 2020-02-29 13:39:43.3483 Info Exiting Jackett.. 

After this no more log info, and no more jackett it seems. Can I correct this by manually updating again to the latest edition somehow? And how would I go about this, simply download the latest version files and replace everything? I would like to keep my settings though (the current links for sonarr etc), how would I go about doing that? Any help would be appreciated.

### Logged Error Messages
Not Available it seems

### Screenshots
Ehm, ask if you need anything screenshotted to clear things up, but I had no clue in this case which screenshots would help with the issue.

**Comment by cadatoiva** [comment]
If you uninstall Jackett and install using the latest version installer, it will keep all your settings and update to the latest version. There isn't enough information in your log to really do much more than that.

Did you try rebooting the computer?

**Comment by miniliQuid** [comment]
Hey, thanks for the swift reply.
As for rebooting: yeah, first thing I often try hehe 😄 

Oh, that's awesome, didn't know it would simply keep all settings when you uninstall. Thanks!

**Comment by miniliQuid** [comment]
Worked like a charm!
Thanks a bunch 😃
