### ISSUE TITLE
[REQ] Spirit of Revolution

### ISSUE THREAD

**Issue by Winblackka** [Jackett/Jackett#7503]
Title : Spirit of Revolution
URL : https://sor-next.tk
Type : 0day
Language : German
Privacy : Private tracker
Invite avaible, pm me.

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by Winblackka** [comment]
Thx, mail was sent.

**Comment by garfield69** [comment]
Registration and login successful. Thank you.

**Comment by Winblackka** [comment]
My pleasure. I have to thank you.

**Comment by garfield69** [comment]
Jackett 0.13.467

**Comment by Mayflower7482** [comment]
Neue URL: https://sor-next.org

mfg

**Comment by lordduckstein** [comment]
Hello,
they are move to:
**https://sor-next.org**
cu
lordi
