### ISSUE TITLE
filelist.ro broken?

### ISSUE THREAD

**Issue by masterpae** [Jackett/Jackett#751]
Hello, It seems that Jakett functionality with filelist.ro tracker is broken.
Neighter sonarr nor couchpotato or the manual search in jackett can't return the actual torrent file.

The search works perfectly, but the torrent can't be retrieved for some reason.
Here is the error that show's up in the log : "Error downloading filelist http://filelist.ro/"

2 days ago it seems they have upgraded from a XBT to Ocelot tracker...

Thank you.

**Comment by kaso17** [comment]
I guess it broke during the upgrade.
Should be an easy fix.
Can you send an invite to kaso1717 -at- gmail.com?

**Comment by masterpae** [comment]
I have sent you the email.
Let me know if there any problems with it.

Thank you.
