### ISSUE TITLE
[REQ] torrentrex.com

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#7515]
Public tracker of movies, games, apps, tv, anime, xxx, others and books

https://torrentrex.com/

**Comment by garfield69** [comment]
Jackett 0.13.506

**Comment by garfield69** [comment]
https://torrentrex.com has been returning Error 522 Connection timed out
for the last 9 days
Is the site Broken, gone, moved to a new domain?

**Comment by 97carmine** [comment]
It is down
