### ISSUE TITLE
[REQ] btmon.com

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#7516]
Public tracker of verified torrents

http://www.btmon.com/

**Comment by garfield69** [comment]
I cannot get the site's search to find anything

latest tv
![image](https://user-images.githubusercontent.com/6933240/76135095-ca0eae80-6088-11ea-8412-7c690b93fd03.png)

search for `keen eddie`
![image](https://user-images.githubusercontent.com/6933240/76135107-f0cce500-6088-11ea-8622-0e0cb36b8872.png)

can you get the search to work?
if the search engine does not work there is little point adding an indexer for it.

**Comment by berat1397** [comment]
Search engine is broken.
