### ISSUE TITLE
[SpeedTorrent Reloaded] New website / Tracker (URL)

### ISSUE THREAD

**Issue by LsHallo** [Jackett/Jackett#7517]
SpeedTorrent Reloaded has moved to https://st-tracker.eu/ with a new site and a new URL
Update to the search code is probably necessary.

Old tracker url for reference:
https://speedtorrent-tracker.mine.nu/

**Comment by fnk93** [comment]
Already on it.

**Comment by garfield69** [comment]
Jackett 0.13.483
