### ISSUE TITLE
Result links from Bit-HDTV are not directing properly

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#752]
Hey guys!

Not sure if others are facing the same problem, but if I click on the link of any Bit-HDTV search result, it never takes me to the proper page on Bit-HDTV.com. All the links from Bit-HDTV search results are preceded by https://www.bit-hdtv.com. For example, instead of going to:

https://www.bit-hdtv.com/details.php?id=116908

I'd be directed to:

https://www.bit-hdtv.com/https://www.bit-hdtv.com/details.php?id=116908

Thought it's important to bring up :) Thanks!

**Comment by kaso17** [comment]
Can you send an invite to kaso1717 -at- gmail.com?
Should be an quick fix.

**Comment by armani316** [comment]
@kaso17 Do you still need an invite to Bit-HDTV to fix this?

**Comment by kaso17** [comment]
yes

**Comment by armani316** [comment]
@kaso17 Emailing it now. Please confirm once received and registered.

**Comment by kaso17** [comment]
got it, thank you

**Comment by kaso17** [comment]
please try the latest v0.7.754 pre release

**Comment by armani316** [comment]
@kaso17  OK so the pre-release doesn't get pushed automatically. If I download the .exe file and install it on top of my current version, will all my indexers remain intact?

**Comment by kaso17** [comment]
you've to enable "update to pre-releases" in the jackett settings. Then automatic updates should work.
You can also just replace the current installation
