### ISSUE TITLE
[XtremeZone AKA MyXYZ] Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7520]
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.13.467.0

**Last Working Jackett Version**: Not sure

**Are you using a proxy or VPN?**: No

### Description

Searching XtremeZone returns no results. Instead, I get the following message:
An error occurred while testing this indexer. Found no results while trying to browse this tracker.

### Logged Error Messages
Here's the enhanced log.
[log.txt](https://github.com/Jackett/Jackett/files/4295988/log.txt)

### Screenshots
Not needed.

**Comment by garfield69** [comment]
is this the first time you are using this indexer or was it working before?

**Comment by RoloSoze** [comment]
> 
> 
> is this the first time you are using this indexer or was it working before?

I've been using it for a while via Jackett and it used to work fine. I'm not sure when exactly it stopped working. I noticed earlier that it wasn't returning results in group searches so I tested it individually and found the abovementioned error.

**Comment by garfield69** [comment]
from what I can tell by looking at the html in your log, the indexer is expecting rows under the `<div class="kt-container  kt-grid__item">` selector, but it appears that you are getting rows under the `<div class="kt-portlet kt-portlet--mobile">`

the html appears to have code that sets the display for either desktop or mobile
and it would appear you are currently using the mobile mode.

Logon with your browser directly to the site. 
is there any options in the account settings, or buttons on the main or torrent pages that switches from desktop to mobile and back?

**Comment by garfield69** [comment]
or from poster to grid?

**Comment by RoloSoze** [comment]
> is there any options in the account settings, or buttons on the main or torrent pages that switches from desktop to mobile and back?

> or from poster to grid?

No to both.

**Comment by garfield69** [comment]
Any chance you have an invite so I can do some testing?
send an invite to garfieldsixtynine -at- gmail.com

**Comment by RoloSoze** [comment]
> 
> 
> Any chance you have an invite so I can do some testing?
> send an invite to garfieldsixtynine -at- gmail.com

Check your email.

**Comment by garfield69** [comment]
Jackett 0.13.483

**Comment by RoloSoze** [comment]
> 
> 
> Jackett 0.13.483

@garfield69 Thank you. Normal search works well now. IMDb search does not. I need to remove the 'tt' part of the ID for it to work.

**Comment by garfield69** [comment]
Really? Because when I first tested this I used a ttnumber and got 6 hits.
Maybe it depends on who loaded the torrent ...
So you closed the ticket again, do you still want me to drop the tt ?

**Comment by RoloSoze** [comment]
> Really? Because when I first tested this I used a ttnumber and got 6 hits.
That's strange 'cause I tested over half a dozen IDs, and none worked with tt. In that case, it might be a good idea to conduct both searches for this particular tracker since it seems inconsistent.

> So you closed the ticket again, do you still want me to drop the tt ?
Sorry for the confusion. I closed it 'cause I figured that this ticket was not for the IMDb part of the issue, but it might be better to reopen it and have this discussion here as opposed to cluttering the general IMDb ticket,

**Comment by cadatoiva** [comment]
I'm getting the same thing. Using the new Sonic movie (tt3794354) I get results on the website, but the Console when testing in VS says `0 results for ""` when I put that in the Jackett search.

**Comment by cadatoiva** [comment]
I found it, testing and will PR in a minute

**Comment by garfield69** [comment]
Oh, my bad. I forgot to add the imdb parm to the modes block :-D

**Comment by garfield69** [comment]
Jackett 0.13.506
