### ISSUE TITLE
[REQ]pornotor.org

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#7523]
Russian public porn share torrent site: http://pornotor.org/
Can you add this site from jackett ?
I tested. Search engine is running.

**Comment by garfield69** [comment]
Jackett 0.13.506

**Comment by garfield69** [comment]
http://pornotor.org/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.20.2617
