### ISSUE TITLE
[Torrentbytes] AngleSharp.Dom.TextNode as releasename when searching

### ISSUE THREAD

**Issue by hnnweb** [Jackett/Jackett#7527]
### Environment

**OS**: Ubuntu 19.10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono

**.Net Version**: Mono JIT compiler version 5.18.0.240 (Debian 5.18.0.240+dfsg-3 Mon Jun 24 08:50:44 UTC 2019)

**Jackett Version**:  Jackett Version 0.13.467.0 

**Last Working Jackett Version**: Unknown

**Are you using a proxy or VPN?** [yes/no] NO

### Description

When searching On Tby the results showing up with correct categories, but the name is AngleSharp.Dom.TextNode on every row

1. Add torrentbytes as tracker
2. Click on the magnifying glass to do manual search
3. Enter "The.Rookie" as term for example
4. Select categories 5000,5030,5040,5045
5. Click on magnifying glass to do search

### Logged Error Messages
No logs produced relevant to search 

### Screenshots
![image](https://user-images.githubusercontent.com/3874960/76069994-20e68c00-5f94-11ea-8e73-b1ac3d7528bc.png)

**Comment by garfield69** [comment]
Jackett 0.13.506
