### ISSUE TITLE
Result links from HD-Torrents (HDT), TehConnection (TEH) & UHDBits (UHD) direct to the comments/description section of the torrent's page

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#753]
This is a minor issue, but for HDT, TEH & UHD, links from manual search results direct to the comments or description section of the torrent's page.

For example, the link would look like this:
https://tehconnection.eu/torrents.php?id=28438#comments

Instead of simply this:
https://tehconnection.eu/torrents.php?id=28438

The same goes for HDT (also comments section) and UHD (description section). It's essentially the same page, but a different section. Minor, but worth bringing up. Thanks!

**Comment by kaso17** [comment]
Fixed it for UHDBits, for the other two I would need an invite (kaso1717 -at- gmail.com)

**Comment by armani316** [comment]
Unfortunately, I'm yet to earn an invite there in either of them. I hope someone else can help out!

**Comment by armani316** [comment]
@kaso17 Same thing happens now with TorrentBD. Jackett directs to the comments section. Very minor, but worth fixing.

**Comment by kaso17** [comment]
Fixed with 069c64f504a735c91113d4febb2472e3f527da1a
