### ISSUE TITLE
Jacket Not Starting (Missing method get_FrameworkDescription)

### ISSUE THREAD

**Issue by juhenriquez** [Jackett/Jackett#7539]
### Environment

**OS**:PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] 
Mono JIT compiler version 3.10.0 (mono-3.10.0-branch/ce003f4 Tue Nov 25 20:18:29 UTC 2014)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

**.Net Version**:

**Jackett Version**: v0.13.483

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

Missing method get_FrameworkDescription in assembly /opt/jackett/Jackett.Common.dll, type System.Runtime.InteropServices.RuntimeInformation

Unhandled Exception:
System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.RuntimeInformation' from assembly 'Jackett.Common'.
  at Jackett.Server.Program+<>c__DisplayClass9_0.<Main>b__2 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00000] in <filename unknown>:0
  at CommandLine.ParserResultExtensions.WithParsed[ConsoleOptions] (CommandLine.ParserResult`1 result, System.Action`1 action) [0x00000] in <filename unknown>:0
  at Jackett.Server.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.RuntimeInformation' from assembly 'Jackett.Common'.
  at Jackett.Server.Program+<>c__DisplayClass9_0.<Main>b__2 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00000] in <filename unknown>:0
  at CommandLine.ParserResultExtensions.WithParsed[ConsoleOptions] (CommandLine.ParserResult`1 result, System.Action`1 action) [0x00000] in <filename unknown>:0
  at Jackett.Server.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0

[Make sure you attach the full logs with your personal information removed in case we need more information]

Already Tried, installing mono-complete through apt-get mono-complete, no luck. Fresh Raspian Install.

**Comment by garfield69** [comment]
Mono 3.10 !?! The minimum mono for Jackett is at least [Mono 5.8]{http://www.mono-project.com/download/#download-lin}, but the newer the better. Current latest is 6.8

Time to try ditching mono anyway. We recomend using the .core net version of Jackett.

most raspbian users have had success using the ARM32 version and by following the instructions at https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above
