### ISSUE TITLE
HD-Torrents (HDT) & BeyondHD (BHD) search results containing '@' symbol are not parsed/displayed correctly

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#755]
**With HDT.**

![hdt](https://cloud.githubusercontent.com/assets/23747425/20656729/c7eef75a-b540-11e6-819e-4687bf86777e.jpg)

**With BHD**
![bhd](https://cloud.githubusercontent.com/assets/23747425/20862987/284c9b86-b9cc-11e6-8e78-b06d57efddd9.jpg)

**Comment by kaso17** [comment]
To fix it I would need an invite (kaso1717 -at- gmail.com)

**Comment by armani316** [comment]
Unfortunately, I'm yet to earn an invite there. I hope someone else can help out! There seems to be at least 3 issues with HDT.

**Comment by armani316** [comment]
@kaso17 BHD has the same issue.

**Comment by kaso17** [comment]
Should be fixed for all trackers with 3f629ba7d2c2fa3d1759e7226711f0bee3dfca27
