### ISSUE TITLE
[REQ]rus-media.org

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#7554]
Russian mix public torrent site: http://rus-media.org
Search page: http://rus-media.org/search.php

**Comment by garfield69** [comment]
already esists
https://github.com/Jackett/Jackett/blob/699941061756d900ae1b22697be58107f6f192c5/src/Jackett.Common/Definitions/rus-media.yml

**Comment by garfield69** [comment]
http://rus-media.org/ returning
```
SQL ERROR [ mysql4 ]

Too many connections [1040]

An sql error occurred while fetching this page. Please contact an administrator if this problem persists.
```
rather suspicious that this site is returning the exact same error as nntt #6345 and parnuxi #7558 
are these the same site with different skins?

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> http://rus-media.org/ returning
> 
> ```
> SQL ERROR [ mysql4 ]
> 
> Too many connections [1040]
> 
> An sql error occurred while fetching this page. Please contact an administrator if this problem persists.
> ```

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
http://rus-media.org/ - ERR_NAME_NOT_RESOLVED

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://rus-media.org/ returning DNS_PROBE_FINISHED_NXDOMAIN

**Comment by ilike2burnthing** [comment]
back up
