### ISSUE TITLE
[REQ] iv-torrents.ru

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#7556]
Russian mix semi-private torrent site like pornolab or erzsebet.
~~http://iv-torrents.com~~ https://iv-torrents.ru
I register this site and I tested search engine. Torrent and search engine running. 
Search page: https://iv-torrents.ru/tracker.php

This site is haven't ratio limit. Free all torrents.

**Comment by garfield69** [comment]
Jackett 0.13.560

**Comment by garfield69** [comment]
https://iv-torrents.com/ returning Error 521 Web server is down
just me or is the site gone, broken or moved to a new domain?

**Comment by garfield69** [comment]
Ahh. http works, so it looks like its just the https that's broken.
I'll amend the indexer.

**Comment by ilike2burnthing** [comment]
http://iv-torrents.com/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> http://iv-torrents.com/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://iv-torrents.com/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://iv-torrents.com/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://iv-torrents.com/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://iv-torrents.com/ returning Error Connection timed out
https://www.uptrends.com/tools/uptime reports Http Timeout across all 43 checkpoints worldwide

**Comment by garfield69** [comment]
now http://iv-torrents.com/ is returning
```
This domain is expired. If you are the domain owner please click here to renew it.
iv-torrents.com
2021 Copyright. All Rights Reserved.

Privacy Policy
```

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
I'm still getting:
```
iv-torrents.com
2021 Copyright. All Rights Reserved.
Privacy Policy
```
Not a cache issue, getting the same in a private window.

**Comment by garfield69** [comment]
v0.18.940

**Comment by garfield69** [comment]
https://iv-torrents.ru/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
Error 502 - Bad gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://iv-torrents.ru/ returns Error 522 Connection timed out

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://iv-torrents.ru/ returns http error 500 (Internal Server Error)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://iv-torrents.ru/ returns ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
v0.20.1778
