### ISSUE TITLE
[1337x] Exception (1337x): No such host is known.: No such host is known. (Test)

### ISSUE THREAD

**Issue by heliosmate019** [Jackett/Jackett#7572]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
works for me.
you have given us nothing to work with.
if you want help then supply the requested info in the first post. 
also tell us what the 1337x SiteLink in your indexer is set to.
Otherwise, forget it. No info no help.

**Comment by heliosmate019** [comment]
OS: Windows 10

Jackett Version: Latest

Are you using a proxy or VPN? No

Description:
Not able to use 1137x.to or any other site links for 1337x as an Indexer.
I also tried using a 

VPN but doesn't work.
This is the error I get.
![Annotation 2020-03-08 174126](https://user-images.githubusercontent.com/60848164/76162487-44f8c780-6164-11ea-9621-f018da3d5e5f.png)

**Comment by garfield69** [comment]
So can you confirm that you can access https://1337x.to/ from a browser running on the same win10 system that is running Jackett?
Also, are you only getting this issue for 1337x or are other indexer suffering the same issue?

**Comment by heliosmate019** [comment]
Yes i confirmed it is working in my browser other indexer like torrentz2 and yourbittorrent also not working

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.
