### ISSUE TITLE
[REQ] torrentv.org

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#7575]
Public tracker of movies

https://torrentv.org/

**Comment by garfield69** [comment]
Jackett 0.13.625

**Comment by garfield69** [comment]
https://torrentv.org/ returning Error 522 plus cloudflare retry-for-a-live-version page

**Comment by ilike2burnthing** [comment]
Back up

**Comment by ilike2burnthing** [comment]
http://torrentv.org/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrentv.org/ - HTTP Error 503. The service is unavailable.

**Comment by garfield69** [comment]
https://torrentv.org/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrentv.org/ - Web server is down - Error code 521

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://torrentv.org/
![image](https://user-images.githubusercontent.com/6933240/217134358-a04e8d21-910a-4960-ae5c-0bca4a980d03.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://torrentv.org/
```
Server Error

500 - Internal server error.
There is a problem with the resource you are looking for, and it cannot be displayed.
```

**Comment by garfield69** [comment]
v0.20.4071
