### ISSUE TITLE
bithdtv: bad search with category

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7577]
Steps to reproduce:
* Empty search
* Select one category (this works only in categories with many results tv/movies)

The cause is we are post-filtering. We should include the categories in the request.

**Comment by ngosang** [comment]
@cadatoiva could you take this too?

**Comment by cadatoiva** [comment]
I had to do something similar with another tracker, because it only supported one category at a time. Set cat if only one cat is matched, else search all and post-filter. Might be good to request new pages until ~100 results are queued into the list when pages are available.

**Comment by ngosang** [comment]
> Set cat if only one cat is matched, else search all and post-filter.

I think this is good enough. I prefer to not make more requests.

**Comment by cadatoiva** [comment]
Post filtering already exists further down the chain anyway, so I've completely removed it from here https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/BaseIndexer.cs#L323

I've also implemented category search so that it'll search from a single category if only one exists.

**Comment by garfield69** [comment]
Jackett 0.14.79
