### ISSUE TITLE
Radarr: unable to grab torrent file from YGG tracker

### ISSUE THREAD

**Issue by thenamelessthing** [Jackett/Jackett#7582]
### Environment

**OS**: Ubuntu 16.04.3

**.Net Runtime**: mono 6.8.0.105

**.Net Version**:

**Jackett Version**: 13.506

**Last Working Jackett Version**: Not sure but, but this bug was already fixed in the past. Look this: https://github.com/Jackett/Jackett/issues/2227

**Are you using a proxy or VPN?** No

### Description

If I do search direct in Jacket and try to download the torrent files manually, this is working. But If I try to download the same torrent from Radarr, Sickrage,etc. I obtain the error not a valid torrent file...

### Logged Error Messages
Here is the log in Radarr:
```
2020-3-6 20:27:43.4|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. King Kong Extended Edition 2005 FRENCH 1080p BluRay x264 DTS-SoSo

[v0.2.0.1480] MonoTorrent.TorrentException: Invalid torrent file specified ---> MonoTorrent.BEncoding.BEncodingException: Could not find what value to decode
  at MonoTorrent.BEncoding.BEncodedValue.Decode (MonoTorrent.BEncoding.RawReader reader) [0x0005f] in <ae312fb8a3344a4cbaa8e26ab9c29717>:0 
  at MonoTorrent.BEncoding.BEncodedValue.Decode (System.IO.Stream stream) [0x00015] in <ae312fb8a3344a4cbaa8e26ab9c29717>:0 
  at MonoTorrent.Torrent.Load (System.IO.Stream stream, System.String path) [0x0000c] in <ae312fb8a3344a4cbaa8e26ab9c29717>:0 
   --- End of inner exception stack trace ---
  at MonoTorrent.Torrent.Load (System.IO.Stream stream, System.String path) [0x00032] in <ae312fb8a3344a4cbaa8e26ab9c29717>:0 
  at MonoTorrent.Torrent.Load (System.Byte[] data) [0x0000d] in <ae312fb8a3344a4cbaa8e26ab9c29717>:0 
  at NzbDrone.Core.MediaFiles.TorrentInfo.TorrentFileInfoReader.GetHashFromTorrentFile (System.Byte[] fileContents) [0x00000] in <fd6dc903261f46d49ff7a60364fd04b3>:0 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, System.String torrentUrl) [0x001ac] in <fd6dc903261f46d49ff7a60364fd04b3>:0 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie) [0x00148] in <fd6dc903261f46d49ff7a60364fd04b3>:0 
  at NzbDrone.Core.Download.DownloadService.DownloadReport (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, System.Boolean foceDownload) [0x000a3] in <fd6dc903261f46d49ff7a60364fd04b3>:0 
  at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions (System.Collections.Generic.List`1[T] decisions) [0x00183] in <fd6dc903261f46d49ff7a60364fd04b3>:0 
```

### Screenshots

![image](https://user-images.githubusercontent.com/10235448/76170431-415f4380-6158-11ea-86cb-e50c1ad07354.png)

![image](https://user-images.githubusercontent.com/10235448/76170500-de21e100-6158-11ea-8067-8d362a0e71f8.png)

**Comment by garfield69** [comment]
works for me on my win10
![image](https://user-images.githubusercontent.com/6933240/76173100-1977ea80-6201-11ea-847d-f0ca14dc2f07.png)

the mention of #2227 in not relevant to this issue, that ticket was for a problem with the indexer itself where the download link selector was in erorr, and **no** downloads were possible.
Clearly this is not the case here, as I can download fine.

Have you tried recently again? perhaps it was a genuine issue at yggtorrent?
can you start a download (you don't have to finish it, just prove it can get started) for any other yggtorrent movie?

**Comment by thenamelessthing** [comment]
Problem still there..

**Comment by garfield69** [comment]
in that case we are going to need more info. the Radarr log is not useful to use, the Jackett enhanced log should be more useful, as it will contain the html from the site and hopefully show what it is that is preventing the download.

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by thenamelessthing** [comment]
Hi @garfield69 , here is the full log. I have try with "king kong (1976)".

[log.txt](https://github.com/Jackett/Jackett/files/4341355/log.txt)

**Comment by garfield69** [comment]
I cannot find anything that suggests a problem.
It is beyond my skills to diagnose.
passing it on to the c# team who may have some further insight into how to diagnose further.

**Comment by thenamelessthing** [comment]
OK thank you,

If I try directly in jackett the torrent download correctly. But if I try in radarr, I obtain Invalid torrent file specified...

**Comment by cadatoiva** [comment]
The previous bug you reference was a change in the download link for the site, see https://github.com/Jackett/Jackett/commit/ed8deaa1ba21ebe875fdec6acd34455844cde6f7 for the relevant changes to the source. As @garfield69 said though, it's not relevant to this issue.

According to the Radarr log, it also is able to download the .torrent file, but it finds it's in an invalid format. The .torrent file you get from Jackett, does your torrent client pick it up and start downloading, or does it give an error like Radarr about being invalid?

Is it just that specific release, or is it all torrents on the site that are affected?

**Comment by thenamelessthing** [comment]
@cadatoiva I have do more test and I found that it's not ygg specific. I have try even with ethor and I have the same behavior. For all results.

**Comment by cadatoiva** [comment]
Is this still an issue?

**Comment by thenamelessthing** [comment]
Yes it is!

**Comment by cadatoiva** [comment]
Were you able to test the downloads from the Jackett search page to make sure they open in your torrent client?

**Comment by thenamelessthing** [comment]
Yes, in the search page of jackett, for every tracker. It work fine. In radarr, no download work.

**Comment by cadatoiva** [comment]
To double check, you opened the downloaded torrent files from the search page in Jackett and they were added to your torrent downloader without issue?

**Comment by thenamelessthing** [comment]
Yes, it work like a charm.

**Comment by cadatoiva** [comment]
Ok, well it sounds like Jackett is working fine then and giving valid torrents. Radarr appears to be the issue because:

- Jackett manual search is working fine
- The torrents being returned are valid
- It's working in radarr for other users
- Radarr's logs say they've downloaded the torrent file
- Radarr is the one saying the torrent file is invalid

I recommend going to https://github.com/Radarr/Radarr/issues and seeing if they can help.

**Comment by thenamelessthing** [comment]
Well, after a little more search in my setup. I have found the problem. In radarr, we must use 

![image](https://user-images.githubusercontent.com/10235448/77342501-a5f8d180-6d06-11ea-990e-42924c75c29b.png)


http://localhost:9117/torznab/YOURINDEXER

my settings was: https://mydomain.com/torznab/YOURINDEXER

In both situation the "test connection" are working but if I use https it doesn't.
