### ISSUE TITLE
[avistaz] Value cannot be null. (Parameter 'node') (Config)

### ISSUE THREAD

**Issue by absywabsy** [Jackett/Jackett#7583]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
update your jackett to 0.13.560

**Comment by fent** [comment]
I'm getting the same error on 0.13.611.0

**Comment by garfield69** [comment]
@fent 
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by fent** [comment]
@garfield69 here

[log.txt](https://github.com/Jackett/Jackett/files/4322058/log.txt)

**Comment by garfield69** [comment]
it appears that you have enabled 2FA on your AvistaZ account.
The jackett indexer does not currently support 2FA

**Comment by garfield69** [comment]
enhancement request #3345 may get action if anyone volunteers.
