### ISSUE TITLE
[torrentheaven] Exception (torrentheaven): Object reference not set to an instance of an object.: Parse error (Config)

### ISSUE THREAD

**Issue by Mitnick84** [Jackett/Jackett#7586]
Cant login anymore after  jackett update

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
You did not specify which version of jackett you are on, which makes it difficult for us to determine if the problem has already been fixed and you are simply on an out of date version, or if this is a new issue that required investigation.
Please report the version at the bottom of your Jackett Dashboard to confirm you are using the latest version available.

Assuming that you are indeed on the latest version, it would be very helpful if you could upload the HTML source code.

- Please, open torrentheaven in your browser and go to the list of torrents and perform the same search as in Jackett
- Right click, save page as HTML
- Remove personal information from the HTML file (without breaking the code)
- drag/drop the html file here (use txt extension)

Thanks.

**Comment by Mitnick84** [comment]
sorry, im on v0.13.560

**Comment by wasgehthierab** [comment]
for me it is broken as well. I do not see the Captcha

**Comment by Mitnick84** [comment]
I think also its the Captcha, i dont see it.

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by garfield69** [comment]
The Captcha image is only ever present if the site's login actually wants to challenge you.
When they do not, you usually just leave the Captcha text field in the config empty and continue with the login.
if you are saying that leaving it empty is not allowing you to login then provide the **enhanced log** so we can take a look.

But I think you will find this is a red herring, and the issue is with the search page generating results that the indexer is unable to parse properly since #7387 was applied.

in any case, the **enhanced log** is what we need to progress the issue.
This is because we don't have anyone on the team with an account for the site so we cannot test this for ourselves.

**Comment by Mitnick84** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4311615/log.txt)

**Comment by cadatoiva** [comment]
Sorry about that, forgot which branch I was on. PR submitted. Also fixes an issue with the FreeLeech detection.

**Comment by garfield69** [comment]
Jackett 0.13.611
