### ISSUE TITLE
[vizuk] add missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7588]
Search for `Testigo Protegido`

**Comment by garfield69** [comment]
I do not get any hit using for `Testigo Protegido` in the web site or the Jackett indexer.
crosschecking the categories from website with the indexer shows all cats are present.

?

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/76250832-48647f80-6246-11ea-9676-3ee4bcb7bd77.png)

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/76251631-34ebff80-62ac-11ea-9e1a-affb104ade15.png)
![image](https://user-images.githubusercontent.com/6933240/76251716-62d14400-62ac-11ea-91e3-8ad08b858b7b.png)

what is going on?

**Comment by ngosang** [comment]
That's weird...
![image](https://user-images.githubusercontent.com/10577978/76251961-43083480-6248-11ea-9003-6fd91885e12a.png)
I have language set to Spanish. Could be that?

**Comment by garfield69** [comment]
nope
![image](https://user-images.githubusercontent.com/6933240/76252357-7a5cfc80-62ad-11ea-8d0e-54b992ea207d.png)

**Comment by garfield69** [comment]
if you provide your html I can compare, and at the very least, I can see what the cat is you are getting and add it to the indexer.

**Comment by ngosang** [comment]
https://jsfiddle.net/qeu5zstj/

**Comment by RicardoVelaC** [comment]
@ngosang @garfield69 

Same result for me, but if I activate suggestions option I get one result I do not why.
<img width="970" alt="Captura de pantalla 2020-03-10 a las 1 25 03" src="https://user-images.githubusercontent.com/6016812/76268463-807fb880-626e-11ea-9184-33fcd83a9416.png">

<img width="978" alt="Captura de pantalla 2020-03-10 a las 1 28 09" src="https://user-images.githubusercontent.com/6016812/76268484-8d9ca780-626e-11ea-8e89-e4a926a0e66c.png">

**Comment by RicardoVelaC** [comment]
Ok, you need to update selected categories, go to:

> My Profile > Preferences > Default categories

If you select all categories again, you get results in normal search in the web and Jackett too

**Comment by RicardoVelaC** [comment]
Fixed in #7605

**Comment by garfield69** [comment]
Jackett 0.13.581
