### ISSUE TITLE
[puntotorrent] add missing categories and banner

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7592]
Example search: `Mari Jungstedt`
The banner appears if you click in the title.

**Comment by garfield69** [comment]
@RicardoVelaC  are you available to update this indexer as per this ticket request?
I do not have an account on the site to cannot do it myself unless an invite is forthcoming ;-)

**Comment by RicardoVelaC** [comment]
- I fixed the category id for Books/Other in #7613 
- I don't have idea how to add the banner 

@garfield69 The last year Puntotorrent close the doors, they remove the invites, only the staff can to do it.... sorry :(

**Comment by garfield69** [comment]
@RicardoVelaC 
> The last year Puntotorrent close the doors, they remove the invites, only the staff can to do it.... sorry :(

no problem, just thought I'd ask ;-)

>I don't have idea how to add the banner

if you could upload the HTML source code then I can whip up an example banner for you to include and test.

- Please, open torrentheaven in your browser and go to the list of torrents and perform the same search as in Jackett
- Right click, save page as HTML
- Remove personal information from the HTML file (without breaking the code)
- Drag/Drop the html file here (use txt extension)

Thanks.

**Comment by ngosang** [comment]
@garfield69 html => [puntotorrent.txt](https://github.com/Jackett/Jackett/files/4315271/puntotorrent.txt)

I don't know if it's possible to grab the banner because it's in the next row:
![image](https://user-images.githubusercontent.com/10577978/76367672-ff87f600-632d-11ea-98ef-08553079d4c6.png)

**Comment by garfield69** [comment]
sure. you can use the **after** statement in the **row** section. basically this concatenates however many selectors you want into one.
so you could try:
```yaml
    rows:
      selector: "#mcol .block-content-l table table.lista > tbody > tr:not(:first-child)"
      after: 1
```
then all you need is the **banner** in the **fields** section
```yaml
      banner:
        selector: img[name="img1"]
        attribute: src
```

**Comment by ngosang** [comment]
@garfield69 the `after` trick works, but the details are loaded async from other page so I can't get the banner. You can merge the PR as is.
![image](https://user-images.githubusercontent.com/10577978/76455631-2d287a00-63d6-11ea-9059-c0c4de164452.png)

**Comment by garfield69** [comment]
Jackett 0.13.625
