### ISSUE TITLE
[morethantv] add banner

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7594]

**Comment by garfield69** [comment]
this is a c# indexer,  and additionally I do not have an account on the site.

**Comment by RoloSoze** [comment]
> 
> 
> this is a c# indexer, and additionally I do not have an account on the site.

@garfield69 I think @ngosang opened this ticket as a reminder for himself. He's an MTV member. I'll assign him to eliminate any confusion.

**Comment by RoloSoze** [comment]
Can someone please clarify what you guys mean by banner?

**Comment by garfield69** [comment]
>Can someone please clarify what you guys mean by banner?

Banner is the Torznab keyword for the Poster image link ;-)

**Comment by ngosang** [comment]
@RoloSoze in the Jackett UI you can see as a tooltip in the link.
![image](https://user-images.githubusercontent.com/10577978/76451894-72e24400-63d0-11ea-84fd-a3c47b137db2.png)
