### ISSUE TITLE
torrentseeds: add imdb search and imdb links

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7624]
1. Some torrents have imdb link in the torrent list
![image](https://user-images.githubusercontent.com/10577978/76368313-16c7e300-6330-11ea-9762-6848e5aa4b46.png)
2. It's possible to search by imdb id
![image](https://user-images.githubusercontent.com/10577978/76368340-319a5780-6330-11ea-94c5-4552eb8c5cd8.png)

@fnk93 could you help with this? There are several trackers with this functionality, take a look at IPTorrents for example.

UPDATE: The second point is not working, only returns the first match.

**Comment by fnk93** [comment]
Yes will take a look, probably tomorrow or the day after.

**Comment by fnk93** [comment]
Just added to #7611 
Single-Results may even have the imdb-id in its nfo. This is checked as well.

**Comment by RoloSoze** [comment]
@ngosang In addition to opening separate tickets, it might be a good idea to also add any tracker with IMDb ID search capability to this ticket #4859 to keep all things IMDb-related in one place. You can also add whether or not the IMDb links are displayed/supported by the tracker.

**Comment by ngosang** [comment]
Part 1 implemented #7611
Part 2 is not doable at this moment.
