### ISSUE TITLE
[SceneFZ] Login failed: No form found

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7625]
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.13.611.0

**Last Working Jackett Version**: Not sure

**Are you using a proxy or VPN?**: No

### Description

When trying to configure SceneFZ, I get the following message:
Login failed: No form found on https://www.scenefz.me/login using form selector form (Config)

### Logged Error Messages
Here's the enhanced log.
[log.txt](https://github.com/Jackett/Jackett/files/4320178/log.txt)

### Screenshots
Not needed.

**Comment by RoloSoze** [comment]
It would also be great if the IMDb ID search could be implemented if it hasn't been already (can't test at the moment). 

I believe this tracker uses the same template as #7520

**Comment by RoloSoze** [comment]
If someone wishes to join this tracker to fix this issue, applications are open:
https://scenefz.me/login

Click on 'Apply'. You do not need to provide proofs of activity from other trackers, just your desired username, email address, and a speed test link.

**Comment by garfield69** [comment]
the apply page is broken.
![image](https://user-images.githubusercontent.com/6933240/76472966-fd23ba00-645b-11ea-9420-e260f57b4a14.png)
after filling in the details and clicking the apply button, it spins its wheels.
The recapcha challenge is broken and it is probably this that prevents the form from being processed.

**Comment by garfield69** [comment]
the logs shows that the site is redirecting  https://www.scenefz.me/ to https://scenefz.me/

back in March 2018 we switched from  https://scenefz.me/ to https://www.scenefz.me/ 3848a0bcd65a8f38f3084e063b8139b349c6d438 and now looks like the have switched back around again.

**Comment by RoloSoze** [comment]
> the logs shows that the site is redirecting https://www.scenefz.me/ to https://scenefz.me/

I tried. Still doesn't work. I wasn't aware that the application page doesn't work since I've had the account for a while and didn't need to use it recently.

Please check your email.

**Comment by garfield69** [comment]
Are you attempting to simply edit the config using the jackett dashboard to replace the SiteLink?

That is not going to work. part of 3848a0bcd65a8f38f3084e063b8139b349c6d438 was to automatically switch from the old domain to the new, so that users did not have to make any changes to their indexer config.

If you don't want to wait for the Jackett fix ed763fe7e117523e4cd640a1d3923e88373cc3d4 in the next release, the you can fix this yourself by  editing your indexer source directly and make to correction. Restart the Jackett service to pick the modified indexer.

**Comment by garfield69** [comment]
seems that as in addition to altering their domain, they have also made changes to their engine.

The indexer is trying to use https://scenefz.me/torrents to search the site but that is now returning
`Sorry we can't seem to find the page you're looking for.`
the Site is now using https://scenefz.me/browse

I'll update the indexer and make any other additional changes for the new engine.

**Comment by garfield69** [comment]
Jackett 0.13.625

**Comment by RoloSoze** [comment]
Everything seems to be working well. Thank you.
