### ISSUE TITLE
[Enhancement] Adding a 'Test All' button

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#763]
Hey guys! 

Every time I start a series of manual search sessions across all my configured indexers, I find myself having to manually test the connection for every tracker beforehand to make sure that they're all working fine so I don't miss out on their search results. As the number of my trackers increases, I find that this is becoming increasingly tedious. 

I therefore suggest that a 'Test All' button gets added next to the 'Manual Search' button so that the user can test the connectivity of all their trackers at once before conducting a search. Trackers that are not connectable, for one reason or the other, should be highlighted, and a descriptive error message should get displayed next to them. This way the user ensures, with one click, that all configured indexers are working fine instead of testing trackers one by one.

**Comment by kaso17** [comment]
Would be a nice feature.
