### ISSUE TITLE
[mejortorrent] Clearance failed after 30 attempt(s). (Config)

### ISSUE THREAD

**Issue by coboda** [Jackett/Jackett#7630]
peace hombre

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by joaoptc** [comment]
I dont see any tkt opened for this issue in here.
Please check when possible.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/TroubleShooting#clearance-failed-after-30-attempts

**Comment by joaoptc** [comment]
Hey Garfield,
that does not seems the case. I am trying to add this indexer since I started to use Jacket (2 months). And every attempt was made with a different IP.

**Comment by garfield69** [comment]
yeas I know.
That does not change the fact that mejortorrent has enabled anti-DDoS protection via Cloudflare, and if they have chosen to **permanently** keep that protection active, there is still nothing that Jackett can do about it.

**Comment by joaoptc** [comment]
I see your point .... really doenst make sense to have a tkt here .... Let me close it then.
Thanks for the inputs :)
