### ISSUE TITLE
[bithdtv] Your cookie did not work: Your cookie did not work (Config)

### ISSUE THREAD

**Issue by tommyvange** [Jackett/Jackett#7634]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
[Docker Container](https://hub.docker.com/r/linuxserver/jackett/) (Ubuntu 18.04.4 LTS)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
[Docker Container](https://hub.docker.com/r/linuxserver/jackett/) (Not Sure)

**.Net Version**:
[Docker Container](https://hub.docker.com/r/linuxserver/jackett/) (Not Sure)

**Jackett Version**:
0.13.625.0

**Last Working Jackett Version**:
I just installed it.

**Are you using a proxy or VPN?** [yes/no]
No

### Description

I try to add Bit-HDTV by copying my PHPSESSID as the instructions told me, but I am still getting the **Your cookie did not work: Your cookie did not work** error.

### Logged Error Messages

https://gist.github.com/tommyvange/73253fd61e5333bbcb909fd388fd8c2e

**Comment by garfield69** [comment]
whats in the config as a default cookie string is just an example but it may not be the complete cookie.

- copy the entire cookie string, everything after the `cookie: ` from your browser, however many keywords there are, not just the phpsesid.
- to fetch the cookie make ensure that you use a browser running on the same computer that is also running jackett.

Does that solve?

**Comment by tommyvange** [comment]
> whats in the config as a default cookie string is just an example but it may not be the complete cookie.
> 
> * copy the entire cookie string, everything after the `cookie: ` from your browser, however many keywords there are, not just the phpsesid.
> * to fetch the cookie make ensure that you use a browser running on the same computer that is also running jackett.
> 
> Does that solve?

Copying all the cookies solved it, thank you!
