### ISSUE TITLE
[yggtorrent] 401 Unauthorized, check your credentials (Config)

### ISSUE THREAD

**Issue by gecotoine** [Jackett/Jackett#7635]
*
### Environment

**OS**: debian 10

**Jackett Version**: last
### Description
Hello
I don't understand where are the error :/
I need help x)

### Screenshots
![image](https://user-images.githubusercontent.com/26250412/76641525-0e4ef280-6552-11ea-8e21-2019d140c1c1.png)

![image](https://user-images.githubusercontent.com/26250412/76641346-c039ef00-6551-11ea-89fe-c92550897f5a.png)

**Comment by garfield69** [comment]
use your browser to logon to yggtorrent directly and check that your account credentials a correct, and that you have not been suspended and that you have a good ratio.
