### ISSUE TITLE
REQ: Add new tracker RapideTracker

### ISSUE THREAD

**Issue by thenamelessthing** [Jackett/Jackett#764]
Please add this generale french tracker RapideTracker

https://rapidetracker.net/index.php

For a limited time the invitation are open, but they will close soon...

Thanks you in advance!

**Comment by thenamelessthing** [comment]
Can I help you for something for adding this one?

**Comment by kaso17** [comment]
It's on my todo list

**Comment by kaso17** [comment]
added with 62f0bdc19cb5958a9625c143e8a1f558f2e6c0ae

**Comment by kaso17** [comment]
will this tracker come back or stay offline?

**Comment by thenamelessthing** [comment]
Unfortunatly, I think it's definitly closed.

**Comment by kaso17** [comment]
ok, thank you.
Removed via 8f869995e9acd631c685fa77ccc4ec552a46b922
