### ISSUE TITLE
Endless Redirect in Organizr for Jackett

### ISSUE THREAD

**Issue by Nostang3** [Jackett/Jackett#7642]
**OS**: 
Freenas 11.2u1

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
Mono version: 5.10.1.57

**Jackett Version**:
v0.13.633.0

**Last Working Jackett Version**:
Not sure, it's was a few versions ago. I think a version from a couple weeks ago. 

**Are you using a proxy or VPN?** [yes/no]
No proxy or reverse proxy.

### Description
Freenas Jail 1: Organizr 192.168.1.9
Freenas Jail 2: Jackett 192.168.1.8:9117
Windows 10 Desktop: Webgui in ANY browser 192.168.1.2

When using Organizr and trying to load Jackett as an iFrame, it tries to redirect back to the dashboard but fails. I put a ticket [1327](https://github.com/causefx/Organizr/issues/1327#issuecomment-598849199) into Organizr and they said it 

> from what i have observered in this very short time is that jackett is trying to write a cookie to the browser using the Lax flag on SameSite

Jackett has worked in organizr for a long time but something recently has changed and it's not allowing something to happen. 

### Logged Error Messages
I saw a couple of competing errors
`AuthenticationScheme: Cookies was not authenticated.`
`Executing ChallengeResult with authentication schemes ().`
`AuthenticationScheme: Cookies was challenged.`
`AuthenticationScheme: Cookies was successfully authenticated.`

Attached log, did not see any identifiers but wasn't sure what to look for. 

### Screenshots
[jackett_log.txt](https://github.com/Jackett/Jackett/files/4332012/jackett_log.txt)

**Comment by garfield69** [comment]
yes, this is a results of #7269 introduced with Jackett 0.13.163
read the ticket for the explanation why.

**Comment by Nostang3** [comment]
Thanks for the quick response. 

I'm assuming this qualifies as duplicate or similar and will close case.
