### ISSUE TITLE
[ICE Torrent] Implement IMDb ID search & eliminate duplicate results

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7651]
1. Currently in Jackett, the IMDb ID search exists in ICE Torrent. However, It retrieves some but not all results vs. searching with the IMDb ID via the website.

e.g. Try searching for tt8579674 - 2 results in Jackett vs. 14 on the website.

![image](https://user-images.githubusercontent.com/23747425/76683812-48b1a180-65dd-11ea-8c18-2336b6c9cf44.png)

![image](https://user-images.githubusercontent.com/23747425/76683800-3e8fa300-65dd-11ea-8749-bbb0f3c78fba.png)

2. I also noticed that ICE Torrent returns duplicate results in Jackett.
Try searching for '1917 2019', you'll get 2 instances for each release.

![image](https://user-images.githubusercontent.com/23747425/76683750-e35db080-65dc-11ea-96af-82b0fa33c77b.png)

**Comment by garfield69** [comment]
>Currently in Jackett, the IMDb ID search exists in ICE Torrent. However, It retrieves some but not all results vs. searching with the IMDb ID via the website.

fixed.

>I also noticed that ICE Torrent returns duplicate results in Jackett.
Try searching for '1917 2019', you'll get 2 instances for each release.

the web site has two search engines, browse.php, and browseadult.php
the indexer searches with both engines
however, while the browse.php does not return the adult categories, the browseadult.php does return non-adult categories.
In addition, the browseadult.php does not return the imdb info when it returns non-adult categories.
so as far as cardigann is concerned these results are different and are included.
hence the double listings, one with imdb the other without.

the only way to prevent this is to set up a config to ask which engine to use, with the proviso that the adult engine will not return imdb searches.

So I will set that up and see what happens.

**Comment by garfield69** [comment]
Jackett 0.14.49
