### ISSUE TITLE
[req] [elite-tracker] Add torznab category for Nintendo Switch

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7656]
Used by Elite-Tracker
Category: NSW

**Comment by garfield69** [comment]
there is no such category as ConsoleNSW
https://github.com/Jackett/Jackett/blob/699941061756d900ae1b22697be58107f6f192c5/src/Jackett.Common/Models/TorznabCatType.tt#L9-L23
I will add cat=96 as ConsoleOther

**Comment by garfield69** [comment]
actually its already defined, as Console. so closing as wontfix.

**Comment by garfield69** [comment]
oh, I see you have raised PR #7657 
Please try to remember to self-assign a ticket if you are working on a related PR, it will prevent this kind of interference by me ;-)

**Comment by ngosang** [comment]
I explain myself bad, I was requesting to edit `TorznabCatType.tt``to add the switch.
Where is the official/specification categories list published?

**Comment by garfield69** [comment]
as described in our readme:
The software implements the [Torznab](https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer) (with [nZEDb](https://github.com/nZEDb/nZEDb/blob/dev/docs/newznab_api_specification.txt) category numbering)

**Comment by garfield69** [comment]
although that does not explain how we ended up supporting UHD ... I'm trying to find out how that came about, I think I had a hand in that  a while ago, but I don't remember now ;-(
I'll do some research.

**Comment by ngosang** [comment]
Maybe https://newznab.readthedocs.io/en/latest/misc/api/#predefined-categories ?
