### ISSUE TITLE
HD-Space missing category mappings

### ISSUE THREAD

**Issue by cadatoiva** [Jackett/Jackett#7664]
I'm working on updating HD-Space's tracker for IMDB + general refactoring, and there's three categories I'm not sure where they'd be placed.

- **36 - Trailers** Appears to be movie and tv-show trailers
- **27/28 - Animation** Appears to be a cluster of animated movies and tv shows

Since these aren't mapped, and each torrent on the site can only have one category, we miss out on finding these results on the site especially 27/28 categories. Is there a way to add these categories to the tracker? Can a tracker category be mapped to multiple torznab categories?

**Comment by garfield69** [comment]
Only 1 Torznab category can be mapped to any 1 Site category. 

My general rule of thumb is that if there is no best matching Torznab subcategory to match the sites' category, I pick the closest parent category that fits the majority of torrents for that sites' cat.
So for instance, if there are generally more Movie trailers on the site than Series trailers, and both are under the Site as cat 36, then I map 36 to the Torznab Movies and that is good enough.

**Comment by RoloSoze** [comment]
@ngosang I'm able to invite you to HD-Space if you're intrested it in working on this issue.

**Comment by cadatoiva** [comment]
I already have access to HD-Space. This was more a dev question. I got my answer that we can actually double up on categories so that all the Torznab/Sonarr/Radarr queries work correctly, and super low priority will implement this at some point in the future.
