### ISSUE TITLE
checking for updates crashes headless UI

### ISSUE THREAD

**Issue by Commissar0617** [Jackett/Jackett#7682]
### Environment

**OS**: freenas jail

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: n/a

**Jackett Version**: Version 0.13.122.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description
"check for updates" button crashes headless jackett. attempting to restart the jackett service fails saying jackett not running, but then fails to start jackett saying it is running. 

![2020-03-15 13_28_50-FreeNAS - stormax imperiumom xyz](https://user-images.githubusercontent.com/5993529/76707917-02ce0980-66c1-11ea-9375-f872132edd0f.png)

**Comment by garfield69** [comment]
why did you close this?

**Comment by Commissar0617** [comment]
it came back, but was not updated. i just updated it the hard way, by fetching and reinstalling it

**Comment by cadatoiva** [comment]
If this is using the standard *BSD port underneath the jail package, a `sudo killall -u jackett` resets it. This is usually a transient issue that doesn't happen every update. I've been unable to find a specific reason why it does this.

**Comment by garfield69** [comment]
@cadatoiva  is this the old classic service versus updater clash?
for systemd users the launch script was updated to prevent this, but users needed to actually run the script that the update implemented, which many did not do.
Could something similar apply on this platform, or does this not apply?

**Comment by cadatoiva** [comment]
FreeBSD and deriviatives (like FreeNAS) use the old init.d system, so this isn't the same. It's probably that the PID file doesn't match the PID for the service. The service manager checks the pid file and doesn't see it since it doesn't match, but when trying to start the service the process finds the running version and aborts starting it a second time.

It only really seems to happen when Jackett crashes in a way that it recovers or otherwise doesn't completely exit.

**Comment by Commissar0617** [comment]
issue does persist on the .14.49 update. how do i fix this? (can I fix it?) the release tempo makes it rather tedious to do a manual download and update every time.

**Comment by cadatoiva** [comment]
This is going to require changes to the Jackett package in FreeBSD to fix, I'm pretty sure. https://www.freshports.org/net-p2p/jackett

Let me look into it more, and see if I can find a more robust way to check for the pid in *BSD distros

**Comment by Commissar0617** [comment]
i mean, im not even using the pkg. i manually installed the mono binary.

**Comment by cadatoiva** [comment]
Mono may be manually installed, but is Jackett?

**Comment by cadatoiva** [comment]
Oh, wait, I remember now. Mine used to do this as well, until I updated lang/mono from the default FreeBSD version 5.10 to 6.4. This is a mono bug in the very old version they're using. I never could localize it, just manually updated it away.

Instructions on how to manually update can be found here; https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=238089

**Comment by Commissar0617** [comment]
yeah... ill just throw it in a docker container. screw BSD's weird crap. swear to god, i have more problems with bsd than any other OS.

**Comment by cadatoiva** [comment]
It looks like between that link and https://reviews.freebsd.org/D23300 that a couple of people have picked up the torch on updating Mono for FreeBSD distros. There's activity as recently as yesterday on both for testing and patching. It should only be a couple weeks to get a much needed update to this issue in the automatic pipeline.

Until then, let me know if you need help manually updating Mono on your system. I'll do what I can.

**Comment by cadatoiva** [comment]
Yeah, BSD is a weird one as it's consumer side isn't strongly supported, especially the ports system. It's all volunteer, and a ton of people have abandoned their projects.

**Comment by Commissar0617** [comment]
ok, so i went full reliability and just spun up a debian VM.... i used the install script, much easier... but i think the external UI isn't turned on... but im running headless... how does one turn on the external ui then?

**Comment by garfield69** [comment]
edit `~/.config/Jackett/ServerConfig.json` file and set the **AllowExternal** key to **true**
restart the Jackett service to load the new setting.

**Comment by Commissar0617** [comment]
doesn't exist

**Comment by garfield69** [comment]
the file or the folder?

**Comment by Commissar0617** [comment]
both

**Comment by garfield69** [comment]
implies you have not started jackett at all yet.
need a first run to create the default file and allocate an api key.
so open a terminal and cd to your jackett binary folder and start jackett manually `./jackett` this one time so that the default settings are created.

**Comment by Commissar0617** [comment]
commissar@Jackett:~/Jackett$ ./jackett
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_InvariantCulture()
   at CommandLine.ParserSettings..ctor()
   at CommandLine.Parser..ctor(System.Action`1<CommandLine.ParserSettings>)
   at Jackett.Server.Program.Main(System.String[])
Aborted

**Comment by Commissar0617** [comment]
thinking that's a dotnet weirdness

**Comment by Commissar0617** [comment]
ok, installed libicu-dev,  ran it again, says jackett already running

**Comment by garfield69** [comment]
I'm behind the eight ball on this topic. which jackett package did you end up installing, and from where?

**Comment by Commissar0617** [comment]
the amd64 for linux. wget from the github here
i had issues with docker, so i decided to spin up a debian VM.

**Comment by garfield69** [comment]
ok. so see if the jackett service is running, by trying to shut it down with `systemctl stop jackett.service`

**Comment by Commissar0617** [comment]
and so, i stopped the jackett service, and ran it manually, and i still don't have the

**Comment by Commissar0617** [comment]
-bash: cd: /home/commissar/.config: No such file or directory

**Comment by garfield69** [comment]
look back at the output from your manual jackett run.
try to find 
`MM-dd hh:mm:ss Info App config/log directory: your-config-folder`
that should point to where the jackett is storing its config

**Comment by Commissar0617** [comment]
`commissar@Jackett:~/Jackett$ ./jackett
03-22 22:19:46 Info Starting Jackett v0.14.222.0
03-22 22:19:47 Info Environment version: 3.1.2 (/home/commissar/Jackett/)
03-22 22:19:47 Info OS version: Unix 4.19.0.8 (64bit OS) (64bit process)
03-22 22:19:47 Info Jackett variant: CoreLinuxAmdx64
03-22 22:19:47 Info File /etc/issue: Debian GNU/Linux 10 \n \l
03-22 22:19:47 Info Running in Docker: No
03-22 22:19:47 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionP                                                                          ortThreads
03-22 22:19:47 Info App config/log directory: Jackett
03-22 22:19:47 Info Using Proxy: No
03-22 22:19:47 Info Using HTTP Client: HttpWebClient2NetCore
03-22 22:19:47 Info Loading Cardigann definitions from: cardigann/definitions/,                                                                           /etc/xdg/cardigan/definitions/, /home/commissar/Jackett/Definitions
03-22 22:19:49 Info Cardigann definitions loaded: pier720, abnormal, alpharatio,                                                                           anidex, anidub, animebytes, animetorrents, tehconnectionme, avistaz, bakabt, bb                                                                          , bitcityreloaded, bithdtv, bjshare, broadcastthenet, brokenstones, cgpeers, cin                                                                          emaz, corsarored, danishbits, digitalcore, digitalhive, divxtotal, elitetracker,                                                                           epublibre, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdoli                                                                          mpo, hdonly, hdspace, hdtorrents, hebits, horriblesubs, immortalseed, internetar                                                                          chive, iptorrents, lostfilm, mejortorrent, morethantv, myamity, myanonamouse, nc                                                                          ore, newpct, newrealworld, norbits, nordicbits, notwhatcd, orpheus, partis, pass                                                                          thepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd,                                                                           psytorrents, rarbg, passtheheadphones, revolutiontt, rutracker, scenehd, sceneti                                                                          me, secretcinema, shazbat, showrss, solidtorrents, speedcd, superbits, toloka, t                                                                          orrentbytes, torrentday, torrentech, torrentheaven, torrentleech, torrentnetwork                                                                          , torrentscsv, torrentseeds, torrentsyndikat, transmithenet, tvstore, tvvault, x                                                                          speeds, xthor, yts, animetosho, estrenosdtl, ourbits, isohunt2, torrentz2, twili                                                                          ghtszoom, torrent-turk, torrentsectorcrew, torrent9, filmsclub, gay-torrentsorg,                                                                           nyaasi, riperam, tapochek, hdu, 2fast4you, cpasbienclone, cpasbien, funkytorren                                                                          ts, torrentslocal, diablotorrent, academictorrents, hdhome, yourexotic, gktorren                                                                          t, ccfbits, pornbay, bitspyder, pthome, underversel, wihd, bithumen, tlfbits, ki                                                                          ckasstorrent-kathow, frozenlayer, Das-Unerwartete, ast4u, thefallingangels, craz                                                                          yscorner, thegeeks, prostylex, idope, tekno3d, scenefz, tenyardtracker, nntt, ki                                                                          ckasstorrent, rapidzona, mteamtp, tellytorrent, onlineselfeducation, takeabyte,                                                                           learnflakes, hdbitscom, gay-torrents, hdtime, badasstorrents, backups, hdcity, g                                                                          aytorrentru, arenabg, theshinning, alexfilm, wdt, pleasuredome, casstudiotv, bts                                                                          chool, trancetraffic, sharespacedb, btgigs, concen, rodvd, filebase, rptorrents,                                                                           acgsou, pornotor, dmhy, classix, 0daykiev, pirateiro, polishsource, femdomcult,                                                                           majomparade, underverse, galeriens, pornorip, torrentland, torrent4you, torrent                                                                          quest, carpathians, xtremezone, xiteme, parnuxi, nitro, exkinoray, siambit, kino                                                                          zal, audiobookbay, btetree, ptfiles, bittorrentam, generationfree, piratbit, tea                                                                          mos, hdroute, yggtorrent, torrenting, peersfm, empornium, lastfiles, unlimitz, f                                                                          anoin, torrenthr, hddolby, beitai, yourbittorrent, hdforever, piratbitl, ibit, k                                                                          inonavse100, unionfansub, bigfangroup, newretro, vizuk, rustorka, pornleech, tor                                                                          rentparadise, torrentdownloads, fullmixmusic, metaliplayro, pornolive, torrentga                                                                          laxyorg, u-torrents, hdme, shareisland, desitorrents, spacetorrent, torrent9clon                                                                          e, nethd, r3vwtf, sharewood, esharenet, rns, turktorrent, crazyhd, myspleen, cin                                                                          emamovies, tvchaosuk, netcosmo, pornbits, lechaudron, libranet, sporthd, the-mad                                                                          house, cinematik, theempire, zooqle, toros, mma-torrents, snowpt, 7torrents, ilc                                                                          orsaronero, seedpeer, hqsource, efectodoppler, bluebirdhd, moviesdvdr, gamestorr                                                                          ents, scenepalace, itorrent, theaudioscene, hdreactor, cartoonchaos, racing4ever                                                                          yone, cztorrent, hdturk, blutopia, deildu, rstorrent, divteam, shokweb, leaguehd                                                                          , bteye, audionews, torrentfactory, bibliotik, acidlounge, cili180, ebookparadij                                                                          s, estone, seedfile, tfile, rus-media, hachede, crnaberza, zamundanet, audiobook                                                                          torrents, datascene, hon3yhd, uniondht, beyond-hd-oneurl, 3evils, onejav, xwtcla                                                                          ssics, marinetracker, losslessclub, freetorrent, baibako, btsow, legittorrents,                                                                           lesaloon, pixelcove, theplace, skytorrentsclone, torrentkitty, erzsebet, ilcorsa                                                                          roblu, sosulki, hdtorrentsit, p2pelite, Channelx, torrent-pirat, desireleasers,                                                                           ethor, fantasticheaven, bit-titan, broadcity, casatorrent, ztracker, gfxpeers, e                                                                          xtremetorrents, newstudio, torrentv, 1337x, asiancinema, hddisk, sukebei-pantsu,                                                                           teamhd, magnet4you, moecat, feedurneed, glodls, boxingtorrents, hdcenter, retro                                                                          flix, rutor, leporno, hamsterstudio, metaltracker, nyaa-pantsu, magico, torrentp                                                                          roject2, karagarga, mypornclub, finvip, zelkaorg, aniRena, btdb, cinemageddon, s                                                                          hareuniversity, mvgroupmain, sdbits, jpopsuki, chdbits, thepiratebay, pt99, torr                                                                          entdownload, focusx, legacyhd, hd4fans, demonoid, uhdbits, hdsky, dxdhd, torrent                                                                          lt, xtremefile, xwtorrents, trezzor, yggcookie, spiritofrevolution, hdchina, mic                                                                          robit, springsunday, muziekfabriek, puntorrent, hush, acgrip, icetorrent, iv-tor                                                                          rents, twilight, sportscult, theshow, torrentfunk, sukebeinyaasi, netlab, tribal                                                                          mixes, totheglory, torrentccf, documentarytorrents, crazyspirits, mactorrents, t                                                                          tsweb, 52pt, firebit, totallykids, shellife, film-paleis, linkomanija, proaudiot                                                                          orrents, movcr, booktracker, limetorrents, linuxtracker, bigtorrent, 3dtorrents,                                                                           rutracker-ru, nnm-club, u2, insanetracker, torrentview, xxxtor, aftershock, tor                                                                          rentoyunindir, thevault, oxtorrent, tasmanit, hdarea, extratorrent-cd, mteamtp2f                                                                          a, asgaard, world-of-tomorrow, brasiltracker, tokyotosho, korsar, thehorrorcharn                                                                          el, p2pbg, girotorrent, bitru, sktorrent, nbtorrents, racingforme, speedtorrentr                                                                          eloaded, dragonworldreloaded, elitetorrent-biz, hdspain, eztv, RockBox, torrentr                                                                          ex, nostalgic, btnext, torrentleech-pl, monova, Bittorrentfiles, amigosshare, hd                                                                          bits, awesomehd, dxp, hdzone, arabafenice, extremlymtorrents, eniahd, exttorrent                                                                          s, ebooks-shares, immortuos, topnow, scenerush, mononokebt, xbytesv2, theoccult,                                                                           kapaki, beyond-hd, gigatorrents, 4thd, newstudiol, mvgroupforum, concertos, big                                                                          tower, inperil, torlock, horrorsite, pwtorrents, greekteam, magnetdl, downloadvi                                                                          lle, torrentbd, torrent-explosiv, bitturk, btdigg, uniongang, ettv, zetorrents,                                                                           brobits, soundpark, bithorlo
03-22 22:19:49 Info Adding aggregate indexer
03-22 22:19:49 Info Jackett startup finished in 3.249 s
Hosting environment: Production
Content root path: /home/commissar/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
^CApplication is shutting down...
`

**Comment by Commissar0617** [comment]
ope i see it now

**Comment by Commissar0617** [comment]
aaand ther is no ServerConfig.json

**Comment by Commissar0617** [comment]
nvm. i found it

**Comment by garfield69** [comment]
\o/

**Comment by Commissar0617** [comment]
allow external is already true...

**Comment by garfield69** [comment]
what url are you using to access jackett externally?
is the port open to for WAN access on your firewall, router, etc.

**Comment by Commissar0617** [comment]
im using 192.168.1.18:9117

that's what is show when i do ip addr when i set the reservation
there shouldn't be any firewall issues. i manually added the port to open for tcp in and out in the hypervisor just in case. only thing between me and the host is a switch

**Comment by garfield69** [comment]
and what kind of error are you getting from your browser when you try to connect?
and btw, obviously, you restarted the jackett service or have the on-demand jackett running ;-) ?

**Comment by Commissar0617** [comment]
(－‸ლ)
restarting the service made it works. idkwtfbbq....
