### ISSUE TITLE
Cannot add TorrentDay to Jackett

### ISSUE THREAD

**Issue by kevindd992002** [Jackett/Jackett#7696]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: https://hub.docker.com/r/linuxserver/jackett

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] https://hub.docker.com/r/linuxserver/jackett

**.Net Version**: https://hub.docker.com/r/linuxserver/jackett

**Jackett Version**: 0.14.79.0

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?** [yes/no] Proxy, yes, but I've tried it without the proxy and it's still not working

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

I just installed the linuxserver/jackett container in my Synology NAS and it won't add the TorrentDay tracker and has an error of "Request to Jackett server failed".

I have an exact setup of Jackett on another NAS on another network (same ISP) and it works just fine there. They have the same Jackett version too. I already tried disabling the proxy and it still has the same issue.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

https://pastebin.com/BgdyXbse

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by cadatoiva** [comment]
Known DNS problem with your docker image. Steps to fix here: https://github.com/Jackett/Jackett/wiki/Troubleshooting#resource-temporarily-unavailable

**Comment by kevindd992002** [comment]
I solved the problem. It wasn't an issue specific to the image. It was an issue with my Syno's firewall. Thanks for the tip though.
