### ISSUE TITLE
New Kaspersky alert: Trojan 

### ISSUE THREAD

**Issue by Theli93** [Jackett/Jackett#7698]
Not actually and issue, as far as I'm concerned, but more of a heads-up.

Today, Kaspersky gave an alert for _jackettconsole.exe_ on Windows 10 device as **Trojan.Win32.Generic** (image linked below).

[Kaspersky Alert Image](https://ibb.co/NYczG5y)

**Comment by garfield69** [comment]
Clearly a false hit.
VirusTotal.com's multi engine test gave two red flags out of 72, and the Kaperski engine was green :-D
https://www.virustotal.com/gui/file/cbf1437b0b4d28dbeaed641ce56894dee2c451574b38ad8daa78a79db089eff3/detection
