### ISSUE TITLE
[REQ] NetHD (NHD)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#770]
One of my earliest trackers. A very underrated Vietnamese tracker. I believe sign up is currently open.
https://nethd.org/

Upon signing up, you'll need to send an email to cuongctcclh - at - gmail dot com to activate your account.

**Comment by kaso17** [comment]
Currently doesn't load for me

**Comment by kaso17** [comment]
ok, registered, activation email sent

**Comment by armani316** [comment]
@kaso17 Did it get activated?

**Comment by kaso17** [comment]
According to http://nethd.org/activeuser.php it's not activated but it seems like I can use the tracker normally. What's the point of the activation?

**Comment by armani316** [comment]
@kaso17 Try downloading a torrent, if that works, then you're good to go. If you can't download it, then it's yet to be activated. It's kinda random, they ask people living outside of Vietnam to send an email to manually have their accounts activated by the Admin, and you have to do that once every six months!

**Comment by kaso17** [comment]
or I don't see the download links, everything else is done

**Comment by armani316** [comment]
@kaso17 Then your account hasn't been activated yet. Could take a couple of days. Thanks!

**Comment by armani316** [comment]
@kaso17 Was your account activated? I requested the reactivation of my account yesterday. and received an answer earlier today.

**Comment by kaso17** [comment]
mine was activated today too

**Comment by garfield69** [comment]
http://nethd.org/ returning 404 Not Found
The resource requested could not be found on this server!

**Comment by ilike2burnthing** [comment]
Now showing `OpenLiteSpeed is functioning normally`

**Comment by RoloSoze** [comment]
Working fine for me. @garfield69 Please check when you get the chance.

**Comment by ilike2burnthing** [comment]
https://nethd.org/ - ERR_CONNECTION_TIMED_OUT

Server maintenance yesterday, so guessing it's connected - https://torrentinvites.org/f31/nethd-news-maintenance-585654/

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://nethd.org/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://nethd.org/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://nethd.org/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://nethd.org/

> Come Back Later
Currently, the server is having the flu in the process of processing. You wait for the notification to access again after a few hours.

**Comment by ilike2burnthing** [comment]
Well that was quick.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/770#issuecomment-1537252361

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/770#issuecomment-1537252361

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/770#issuecomment-1537252361

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/770#issuecomment-1537252361

**Comment by garfield69** [comment]
online
