### ISSUE TITLE
[1337x] Exception (1337x): An existing connection was forcibly closed by the remote host.: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by spoonia1** [Jackett/Jackett#7702]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 4.8

**Jackett Version**:  0.14.79.0

**Last Working Jackett Version**: 0.14.79.0

**Are you using a proxy or VPN?** [yes/no] NO

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
1337x and Thepiratebay give the same message

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
read this https://github.com/Jackett/Jackett/wiki/Troubleshooting#an-existing-connection-was-forcibly-closed-by-the-remote-host
