### ISSUE TITLE
Trackers are no longer working in BiglyBT

### ISSUE THREAD

**Issue by ReinerS10** [Jackett/Jackett#7703]
[updater.txt.20200316.00000.txt](https://github.com/Jackett/Jackett/files/4341616/updater.txt.20200316.00000.txt)

### Environment

**OS**: Windows 10 Home

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Version 0.14.49.0

**Last Working Jackett Version**: Prior Version

**Are you using a proxy or VPN?** [yes/no] Yes, VPN only

### Description

I've been using Jackett with BiglyBT without issues for months. About 10 days ago all the trackers stopped working and no torrents are listed within BiglyBT. No changes were made prior to that time. I have verified that the API is the same in both the web UI & subscription JSON file. They are still the same. I'm thinking the API is no longer valid but unable to change (if possible).

I can open all the torrent sites via my browsers. I can also manually search for torrents in the Jackett UI and download from there. 
[log.txt.20200317.00038.txt](https://github.com/Jackett/Jackett/files/4341614/log.txt.20200317.00038.txt)

I can not manually Update to the newest version but will update automatically. "Error performing update."

All the indexers are working (except TPB right now)

### Logged Error Messages

This is a typical error message that shows up on every tracker:

Jackett.Common.IndexerException: Exception (cpasbien): Clearance failed after 30 attempt(s).  ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in d:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2NetCore.cs:line 237    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in d:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 164    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 442    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1321    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 345    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 345    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 807    at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 224
--

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
read this https://github.com/Jackett/Jackett/wiki/TroubleShooting#clearance-failed-after-30-attempts
It explains what the error means and what you can do about it.

**Comment by ReinerS10** [comment]
Thanks for the information but it did not work. I have even been working with my VPN to resolve the issue but it is not working without a VPN either. I can search and download within the Web UI but that is time-consuming. I have gone back to BiglyBT to see if it is an issue since its latest release. Any other ideas would be appreciated tho. Thanks again!

**Comment by garfield69** [comment]
since this was closed there have been some developments.
cpasbien changed the way their search works for keyword searches.
a fix has been applied today and will be released in a couple hours or there about.
Also, a spate of clearance-failed-after-30-attempts have been reported across other indexers, 1337x, demonoid, to name a few.
a change has also been applied which may solve.

please wait for the next release to be published, and see if it solves your issue.

**Comment by ReinerS10** [comment]
FYI... Issue solved.

RSS Feeds, Subscription, Trackers, Torrents not updating.
When there are a lot of subscriptions trying to update at the same time you will receive a timeout or retrying, etc. error (can be confused with other issues like IP address blocked). 
Solution for BiglyBT (probably Vuze): Tools -> Options -> Search -- Timeout for search templates and feeds [*increase seconds*] 

also

For each subscription change the Update Period in Seconds so that no two subscriptions are trying to update and the same time.

**Comment by ReinerS10** [comment]
Sorry, I Closed this before I saw that you Reopened. It appears to be fixed on my side with the changes I made but will reopen to post any comments to the upcoming fixes.

**Comment by garfield69** [comment]
you can post comments to closed tickets.
reopen only if issue is still outstanding ;-)
