### ISSUE TITLE
SDBits.org

### ISSUE THREAD

**Issue by poplolnman** [Jackett/Jackett#771]
Hi!

I have an invite to SDbits.org if you want to add it as a provider...

**Comment by kaso17** [comment]
Send it to kaso1717 -at- gmail.com and I'll add it.

**Comment by poplolnman** [comment]
sent, hey can i email u as well?

**Comment by kaso17** [comment]
got it, ofcouse you can email me

**Comment by poplolnman** [comment]
ty :)

**Comment by kaso17** [comment]
someone knows if they'll come back or did they shutdown permanently?

**Comment by garfield69** [comment]
https://sdbits.org/ ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
v0.21.532
