### ISSUE TITLE
HDTorrents fails only when Proxy is Enabled.

### ISSUE THREAD

**Issue by bluasoar** [Jackett/Jackett#7713]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: unRAID [Docker]

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.14.79.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** I am using a Proxy.

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

When testing all my indexers in Jackett I noticed that HD-T was failing and found out the cause was the Proxy. When the Proxy is Enabled HD-T is the only Indexer to fail, when disabling my Proxy HD-T works. I am not entirely sure what could be causing this. Any help is appreciated. Thank you.

Pastebin containing the logs. https://pastebin.com/NSGdx75z

**Comment by cadatoiva** [comment]
Do you have a specific error message that pops up when the test fails? This will help in troubleshooting why the proxy causes it to fail

**Comment by bluasoar** [comment]
Other than what I posted in the pastebin I get the following error

Exception (hdtorrents): Object reference not set to an instance of an object.: Parse error

**Comment by garfield69** [comment]
The log shows that the indexer is being presented with the cloudflare DDoS challenge 
which means that your proxy is using an IP address that has been blacklisted by cloudflare.
You may need to config your proxy to allocated a different IP address, one from a different region server that has not been blacklisted.

**Comment by bluasoar** [comment]
> 
> 
> The log shows that the indexer is being presented with the cloudflare DDoS challenge
> which means that your proxy is using an IP address that has been blacklisted by cloudflare.
> You may need to config your proxy to allocated a different IP address, one from a different region server that has not been blacklisted.

The Proxy is being provided by my Torrent client via Privoxy. I can access the site fine when I use the same proxy address on Firefox with no errors. Assuming you are right and the IP is blacklisted wouldn't Firefox also not work? It's the same IP. I will try different regions and see if that solves anything. Thanks for the reply!

**Comment by cadatoiva** [comment]
Firefox is able to solve certain anti-bot/DDoS challenges that Jackett simply isn't able to because we're not a web browser and don't use a browser to access the sites. When you see the "Redirecting you in 5 Seconds" there are certain things that page does that can block Jackett without blocking Firefox. There are certain cookies, and the ReCaptcha challenge that we can't capture or duplicate.

The blacklist isn't meant to stop humans, only bots, and it works as designed.

**Comment by bluasoar** [comment]
> 
> 
> Firefox is able to solve certain anti-bot/DDoS challenges that Jackett simply isn't able to because we're not a web browser and don't use a browser to access the sites. When you see the "Redirecting you in 5 Seconds" there are certain things that page does that can block Jackett without blocking Firefox. There are certain cookies, and the ReCaptcha challenge that we can't capture or duplicate.
> 
> The blacklist isn't meant to stop humans, only bots, and it works as designed.

That makes a lot more sense! Thank you for explaining that.

**Comment by jstever** [comment]
I’ve been having the same issue. I use PIA as a VPN with privoxy to pass Jackett data. None of the four links work with mine unfortunately.  Without privoxy, it work fine.

**Comment by bluasoar** [comment]
> 
> 
> I’ve been having the same issue. I use PIA as a VPN with privoxy to pass Jackett data. None of the four links work with mine unfortunately. Without privoxy, it work fine.

The issue has also returned for me. I know we have an explanation as to what is causing it, but is there any work arounds? Thank you.

**Comment by garfield69** [comment]
are you on Jackett  v0.14.164 through v0.14.287 ?
if not then upgrade to the latest version.
if you are on the latest version and you still have this issue then no, there is not current work around that I am aware of.

**Comment by bluasoar** [comment]
I was not, but updating didn't solve the issue unfortunately.

**Comment by garfield69** [comment]
@cadatoiva @ngosang  when you have some free time again ;-) can either of you clone the HDTorrents as HDTorrentsCookie, or provide an optional use-cookie switch in the config, and use the cookie method so we can see if that helps these proxy users out?
Or are we guaranteed to run into that sessions-miss-match between proxy and regular that makes this pointless?

**Comment by cadatoiva** [comment]
Pretty sure #7325 suggests that proxy use is currently buggy and not expected to work correctly yet.

**Comment by bluasoar** [comment]
Awesome thank you I will keep an eye on that thread.

**Comment by bluasoar** [comment]
Not too sure if it was fixed but I updated to Version  0.14.501.0 and HD-T is working again.

**Comment by cadatoiva** [comment]
We haven't done anything in particular to fix it, but the consensus on the proxy issues tends to be that proxy + Cloudflare protection is the biggest no-go. Could be that HDT removed their 3rd party protections for now.
