### ISSUE TITLE
"Copy Torznab Feed" button not working on multiple browsers. 

### ISSUE THREAD

**Issue by CrumpThePenguin** [Jackett/Jackett#7720]
### Environment

**OS**: Windows

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.14.112.0

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?** No

### Description

On Jackett dashboard clicking any of the "Copy" buttons do nothing. Right click --> Inspect Element also seem to show nothing if interest on either of the three buttons. I found #1068 (Closed) that seems to have the same problem as me but that's the only one. I'm new to Jackett and ran into this problem pretty quickly upon trying to set it up with Sonarr. I tried Chrome, Firefox, and IE to no avail, as well as restarting Jackett and my computer.

### Screenshots
![image](https://user-images.githubusercontent.com/24972809/77005024-17fba000-692e-11ea-9d43-4aed486cd365.png)

![image](https://user-images.githubusercontent.com/24972809/77005097-3d88a980-692e-11ea-8849-86cabcb2638e.png)

**Comment by garfield69** [comment]
Given you closed this, I guess you finally figured out that by clicking the button the torznab string gets placed into your clipboard. The green popup should help confirm that this was the case ;-)
![image](https://user-images.githubusercontent.com/6933240/77039957-e06b2180-6a1b-11ea-81d9-0ba1da71981e.png)

**Comment by spuder** [comment]
This is not working in Chrome or Safari. Is there a way to manually extract the feed?
