### ISSUE TITLE
[digitalcore] Your cookie did not work: Parse error (Config)

### ISSUE THREAD

**Issue by apcrcom** [Jackett/Jackett#7722]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux (buster)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 
 Jackett Version 0.12.1804.0 

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

PHPSESSID does not work

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by cadatoiva** [comment]
Please update to the latest version of Jackett.

**Comment by apcrcom** [comment]
unhg, sorry. I didnt realise it had gotten so out of date.

Thanks for getting back to me. Appreciate it..

J
