### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://www2.yggtorrent.se/ using form selector #user-login

### ISSUE THREAD

**Issue by Darkfried** [Jackett/Jackett#7732]
Hi, all is in the title, jackett seems to not find the login form

**Comment by garfield69** [comment]
Please read and apply https://github.com/Jackett/Jackett/issues/7095#issuecomment-582238746
let me know how you go.

**Comment by valentinbourqui** [comment]
I always follow your message but this time I think It doesn't work anymore.

**Comment by garfield69** [comment]
If you cannot get it to work then follow https://github.com/Jackett/Jackett/wiki/TroubleShooting#login-failed-no-form-found-on-url
let me knoew how you go.

**Comment by Darkfried** [comment]
sorry, i responded by mail but it doesnt worked.
the solution above, worked for me,  thank u
