### ISSUE TITLE
HD-Torrents (HDT) - Display 'Freeleech' label

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7734]
Every now and then, HDT does a global freeleech where all torrents on the tracker have a 'FREE' label right next to them. It temporarily replaces any other discount label (e.g. 25%, 50%, 75%) the torrent may have. There's a global freeleech going on right now for the next 34 hours or so. However, Jackett does not display the 'Freeleech' label.

@cadatoiva Can this be fixed?

**Comment by cadatoiva** [comment]
It should be able to, as long as how they announce global freeleech is visible from the search results and they don't change how we detect it from freeleech to freeleech

**Comment by RoloSoze** [comment]
> 
> 
> It should be able to, as long as how they announce global freeleech is visible from the search results and they don't change how we detect it from freeleech to freeleech

It's visible in the search results on the website but is not shown in Jackett. I noticed the same issue last time they had a global freeleech. Other trackers (e.g. Blutopia) have global freeleech every now and then and it's reflected correct in Jackett, but not HDT.

Check it out if you have the chance while global freeleech is still on

**Comment by cadatoiva** [comment]
Well, I'm currently homebound with nothing better to do because of the pandemic. I'll look at it today.

**Comment by RoloSoze** [comment]
> 
> 
> Well, I'm currently homebound with nothing better to do because of the pandemic. I'll look at it today.

Haha! Stay safe. 18 more hours are left on the global freeleech!

**Comment by garfield69** [comment]
Jackett 0.14.164
