### ISSUE TITLE
[req] witch-hunter (Demon-Site) Private https://witch-hunter.eu

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#7752]
Replaces FilmPlus Tracker.
promoted by microBit.
[edit] Demon-Site taken over by Witch-Hunter https://witch-hunter.eu

**Comment by garfield69** [comment]
https://demon-site.eu/ returning
```
Az oldal bezárt, köszönjük mindenkinek aki jelen volt az oldal életében!
Független információ:
Az oldal hamarosan átirányít egy fejlesztés alatt álló képfeltöltő oldal projectjéhez, melyet az oldal korábbi fejlesztője kezdett el készíteni. Használjátok egészséggel!
```
google translation
```
The site is closed, thank you to everyone who was present in the life of the site!
Independent information:
The site will soon redirect you to an image upload page project under development, which was started by a previous developer of the site. Use it healthily!
```

**Comment by garfield69** [comment]
https://witch-hunter.eu/ returning NET::ERR_CERT_AUTHORITY_INVALID
bypassing the certificate reveals
```html
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
Looks like the site is gone or broken or moved to a new domain.

**Comment by ilike2burnthing** [comment]
I'm getting:
> Minden bizonnyal azért látod ezt az üzenetet mert közvetlenül a szerver egyik ip címét nyitottad meg vagy a domain névhez a szerveren még nincs hozzárendelve ip cím.

> You must see this message because you have opened one of the ip addresses directly on the server or the domain name on the server has not yet been assigned an IP address.

**Comment by garfield69** [comment]
v0.18.402
