### ISSUE TITLE
magnetdl: Error while parsing Cardigann definition

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7766]
Error while parsing Cardigann definition /home/XXX/jackett/Definitions/magnetdl.yml: (Line: 8, Col: 19, Idx: 180) - (Line: 8, Col: 19, Idx: 180): Mapping values are not allowed in this context.

**Comment by LexJackson** [comment]
It appears MagentDL is now completely missing in Jackett as of the latest version.
