### ISSUE TITLE
itorrent: the tracker seems to be down 

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7769]
URL: https://itorrent.ws/

Error 522 Connection timed out

Tested in: https://www.uptrends.com/tools/uptime

**Comment by garfield69** [comment]
back online
![image](https://user-images.githubusercontent.com/6933240/77260319-f878c480-6ceb-11ea-9723-90fb1770724e.png)

**Comment by ngosang** [comment]
Down again

**Comment by ilike2burnthing** [comment]
Aaaaand back up again 😐
