### ISSUE TITLE
Add RSS endpoint

### ISSUE THREAD

**Issue by kaso17** [Jackett/Jackett#777]
In some cases a simple RSS endpoint (in addition to torznap/couchpotato) would be helpful (not every tracker supports rss feeds). Additional it could have a search argument.

**Comment by kaso17** [comment]
@flightlevel what's your opinion for this?

**Comment by flightlevel** [comment]
Unsure what the use case for this would be? Torznab was created because of the limitations with rss feeds

**Comment by kaso17** [comment]
My motivation is simple:
For content other than movies/TV shows I use the RSS feature of my torrent client.
But a few trackers don't offer RSS feeds.

**Comment by kaso17** [comment]
never mind, I'll patch the client to ignore the unknown torznab attributes.

**Comment by kaso17** [comment]
For others who find this issue:
Jackett had some encoding issues causing incompatibility with some clients. By now every RSS client should be able to use the torznab feed as normal RSS feed too. Just add your apikey to the torznab feed URL:
Example: `http://127.0.0.1:9117/api/v2.0/indexers/thepiratebay/results/torznab/?apikey=YourJackettApiKey`
