### ISSUE TITLE
torrentrex: the tracker seems to be down

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7770]
URL: https://torrentrex.com

Error 522 Connection timed out

Tested in: https://www.uptrends.com/tools/uptime

**Comment by RoloSoze** [comment]
Still down. Time to remove it?

**Comment by ngosang** [comment]
We have 1 month timeout.

**Comment by RoloSoze** [comment]
> 
> 
> We have 1 month timeout.

Thank you for letting me know.
