### ISSUE TITLE
[REQ] New tracker: aox.to

### ISSUE THREAD

**Issue by drtrotusk** [Jackett/Jackett#778]
aox.to has open registration until Tuesday (5/12).

AOX is a Private Torrent Tracker for Asian Torrents. Japanese, Korean, Chinese, Anime, XXX 

Would be great if you could add it.

Thank you!!!

**Comment by kaso17** [comment]
got an account, added to the todo list

**Comment by kaso17** [comment]
Seems like my account got deleted due to inactivity. Now an invite is required to register.

**Comment by drtrotusk** [comment]
They had some weird issues with their website and many accounts were deleted (such as mine).
They have an open signup right now.

**Comment by kaso17** [comment]
re-registered

**Comment by kaso17** [comment]
added with cf4b3eb2c16d284d563fb0faba1705a7bbe6a324
