### ISSUE TITLE
torrentdownload: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7784]
![image](https://user-images.githubusercontent.com/10577978/77235052-f9f2a180-6bb2-11ea-84a2-fa59084783dc.png)

**Comment by garfield69** [comment]
the site appears to only provide categories when doing keyword searches.
for the keyword-less search we access the /latest page which does not appear to have any categories.

not sure that cardigann can handle providing a default category in this case.
currently the code looks like this:
https://github.com/Jackett/Jackett/blob/401c3a3f41563866417b8a54c8d410cf62e2a1d3/src/Jackett.Common/Definitions/torrentdownload.yml#L55-L60
so we currently fetch the data from the selector which always contains a `»` and strip it and other non-characters so we can extract a category text-name
missing-cat example
```
2020-03-22 10:20:09 | Debug | CardigannIndexer (torrentdownload): strdump(input): »
2020-03-22 10:20:09 | Debug | CardigannIndexer (torrentdownload): strdump(output):
```
found-cat example
```
2020-03-22 10:23:28 | Debug | CardigannIndexer (torrentdownload): strdump(input): » TV shows
2020-03-22 10:23:28 | Debug | CardigannIndexer (torrentdownload): strdump(output): TVshows
```

we would need to somehow determine that after we filter in any letters, if the remainder is empty then provide `Other` as a replacement.

**Comment by ngosang** [comment]
Related #6721

**Comment by garfield69** [comment]
bypassed the missing category by using dropping the /latest page in favour of the default / page
when is good enough.
but cloudflare is interfering when I do a keyword-less search, returning a 520 error.
using the url directly on the browser works, https://www.torrentdownload.info/ or https://www.torrentdownload.info/latest and keyword searches from jackett work.
so I have enabled the cookie method to continue for now.
if you want to research how to drop the cookie method then open a new ticket for this indexer.
