### ISSUE TITLE
torrentz2: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7785]
![image](https://user-images.githubusercontent.com/10577978/77235065-0e369e80-6bb3-11ea-91a2-78c51f4d956a.png)

**Comment by garfield69** [comment]
similar issue to #7784 
in this case the selector is empty, but only after the `a` html tag is removed
so the css selector `:empty` is false at the time that the selector is fetched, and there is no check post removal of the `a` tag that the results is now empty.
https://github.com/Jackett/Jackett/blob/401c3a3f41563866417b8a54c8d410cf62e2a1d3/src/Jackett.Common/Definitions/torrentz2.yml#L127-L134
```
2020-03-22 10:35:58 | Debug | CardigannIndexer (torrentz2): strdump(input):
2020-03-22 10:35:58 | Debug | CardigannIndexer (torrentz2): strdump(output):
2020-03-22 10:35:58 | Debug | CardigannIndexer (torrentz2): strdump(input): » application
2020-03-22 10:35:58 | Debug | CardigannIndexer (torrentz2): strdump(output): application
```
```html
                    <dt>
                        <a href=/7fc2dc24b028c92b8141efd83105d63e7aaa79c4>4D.Studio.20.030</a>
                    </dt>
```
```html
                    <dt>
                        <a href=/7916e56bfd5ae4c3e47c3637134d1ac070fea1f2>CINEMA 4D Studio R19.024 macOS [dada]</a>
                        &#187;application
                    </dt>
```

**Comment by ngosang** [comment]
Related #6721
