### ISSUE TITLE
[enhancement] make user-agent configurable by the user

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7786]
Currently the user-agent header is fixed in the code. Make that value can be overwritten by the user.
Related #7771

**Comment by janot** [comment]
Maybe this should be a bug instead of enhancement? Since setting `search: headers: User-Agent:` in yml doesn't work.

**Comment by cadatoiva** [comment]
@janot this is an enhancement because `search: headers: User-Agent:` has never been a supported option for the yml, as well as any other form of modifying the User-Agent for individual trackers or Jackett as a whole. User-Agent is hardcoded in.

**Comment by ngosang** [comment]
After #10528 and #10590 it's possible to change the User-Agent header in each indexer. The User-Agent can be configured by the user (we support goTemplates in the headers). It works with FlareSolverr too.

I don't think it is a good idea to allow setting a global User-Agent for all indexers. That can cause other problems that are difficult to debug.

**Comment by Lonli-Lokli** [comment]
@ngosang I think specifying global UserAgent allows users on Docker to easy integrate this feature, while with current approach it will require special mapping for docker volumes.

What drawbacks do you see with proposal:
a) If specified custom yml header - use it, otherwise b
b) If specified global UserAgent z use it, otherwise c
3) Use hardcoded UserAgent

**Comment by ngosang** [comment]
`Custom yml header` and `hardcoded UserAgent` are well tested by Jackett' developers.
If the user can change the global user-agent, some sites may stop working, the user will open an issue and we will spend precious time to help the user to finally discover it was his fault. We have been there in the past.
The user-agent is a tricky thing. There are many sites that have different behaviour based on the user-agent.
