### ISSUE TITLE
ebooks-shares: add informative message

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7787]
Add a message similar to => https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/audiobooktorrents.yml#L57

"If you are not getting results, then access the site with your browser and <b>mark as read</b> all PMs."

**Comment by cadatoiva** [comment]
We should maybe look into adding the link to the TroubleShooting wiki page in the error popup on the Jackett page with the specific exceptions there. It wouldn't be too hard I don't think. I'll look into doing that.
