### ISSUE TITLE
xbytesv2: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7793]
![image](https://user-images.githubusercontent.com/10577978/77237135-ca996000-6bc5-11ea-94f2-077d6e6ab3b8.png)

**Comment by garfield69** [comment]
I don't have an account on this site, so this one is yours.

**Comment by cadatoiva** [comment]
While you're in there, see what you can do about #7790 & #3290

**Comment by garfield69** [comment]
Jackett 0.14.243
