### ISSUE TITLE
torrentseeds: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7794]
![image](https://user-images.githubusercontent.com/10577978/77237164-16e4a000-6bc6-11ea-8c16-b8575d778e3c.png)

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/96045872-e373a680-0e72-11eb-86b8-4a8ab4bff935.png)

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/101216409-bd52d180-367f-11eb-8484-beedca747438.png)

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/101405126-ecfc1680-38d7-11eb-8dbb-0dd108981b6a.png)

**Comment by garfield69** [comment]
this one is yours. C# 
the single-result-jump-to-details page uses the match cat via description method, but even after changing cat 32 description to E-books I still cannot get a cat match ;-/
