### ISSUE TITLE
[1337x] Exception (1337x): No connection could be made because the target machine actively refused it.: No connection could be made because the target machine actively refused it. (Test)

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#7798]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: windows 10 Pro

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 2, 3, 4.8

**Jackett Version**: 0.14.164.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

 An error occured while testing this indexer
Exception (1337x): No connection could be made because the target machine actively refused it.: No connection could be made because the target machine actively refused it.

### Screenshots

https://i.imgur.com/GAfvm16.png

**Comment by Commissar0617** [comment]
so, not related to this, but you can put a proxy url in for TPB and it will work.

**Comment by Commissar0617** [comment]
also, it may be 1337x. im having issues as well
Exception (1337x): Clearance failed after 30 attempt(s).: Clearance failed after 30 attempt(s).

**Comment by garfield69** [comment]
@3xploiton3  read https://github.com/Jackett/Jackett/wiki/Troubleshooting#an-existing-connection-was-forcibly-closed-by-the-remote-host for an explanation and what to do.

Also, both 1337x and TPB have alternate working proxies available in their respective Config SiteLink, which may allow you to have access without resorting to a vpn.
Update Jackett to 0.14.222 to take advantage of this option.
