### ISSUE TITLE
Option to specify cached categories per tracker

### ISSUE THREAD

**Issue by mundfrem** [Jackett/Jackett#780]
This option would allow the user to specify which categories should be cached on a configured tracker. It would save bandwidth for the user and tracker. It would also reduce bad results on the client side(sonarr and couchpotato).

It might be better to instead allow a manual entry of one or more category ids. Or allow manual specification of the RSS URL.

For example, I am using a tracker specifically for downloading movies with couchpotato. The only thing I'm interested in from this tracker is bluray movies, which is category id 10. The RSS URL would look like rss.php?feed=dl&cat=10 etc.

**Comment by kaso17** [comment]
With the torznab (sonarr) API you can already specify the categories (cat argument).
I believe the couchpotato API internally limits the search to Movie categories (Can't be configured).
I don't think limiting the categories makes a big difference for trackers. Actually sending an unfiltered query is probably faster as the result is most likely cached by the database server (a more specific search might not be cached).

**Comment by flightlevel** [comment]
Very unlikely to implement
