### ISSUE TITLE
[demonoid] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by daledali** [Jackett/Jackett#7802]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by JohanSF** [comment]
I second this issue.

**Comment by cadatoiva** [comment]
@JohanSF would you be able to provide the information from our issue template? It would help in tracking down why Jackett is finding no results

**Comment by JohanSF** [comment]
Well all I can say is that the test fails when you add demonoid and test it. My guess would be that it needs login information or something? What template is needed to fill out?

**Comment by cadatoiva** [comment]
You can find the blank template above your comment by the Jackett bot. The original creator of the issue also left the template blank. Basically, version, OS, and log messages (from view logs or from log.txt in the data folder) are the most important
