### ISSUE TITLE
FinElite

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7803]
Please add FinElite to Jackett. The tracker's website is in Finnish. 

Registration is currently open, but for a limited period of time:
https://finelite.org/login.php?returnto=%2F#register

IMDb ID search is supported. IMDb URL is displayed in the search results.

**Comment by garfield69** [comment]
This site's registration is broken.
I have registered three times, once each over the last 3 days, the latest using my alternate email address to exclude the possibility of a block, and while the site accepts my registration every time, it does not send me any emails.
And attempting to login returns
![image](https://user-images.githubusercontent.com/6933240/77259897-4dffa200-6ce9-11ea-8f53-a132199c613b.png)

**Comment by RoloSoze** [comment]
@garfield69 Strange! I registered right before I opened this issue and things went well!

**Comment by garfield69** [comment]
got it. 
my password was 20 chars, clearly too long. 
reduced the length and the registration and login was successful.

**Comment by garfield69** [comment]
the registration page ways that registration is free now and always.
I presume this means its semi-private.
or do you think they just mean it will not cost any $ to register?

**Comment by RoloSoze** [comment]
> 
> 
> the registration page ways that registration is free now and always.
> I presume this means its semi-private.
> or do you think they just mean it will not cost any $ to register?

I'm not entirely sure but I can keep an eye on it and double-check the registration status in a few weeks. I'll post an update here confirming whether the registration has closed.

**Comment by garfield69** [comment]
Jackett 0.14.287

**Comment by RoloSoze** [comment]
@garfield69 Registration is now closed. It's a private tracker.

**Comment by garfield69** [comment]
yeah the indexer is already set to private ;-)
