### ISSUE TITLE
torrentdownload: empty search is not returning results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7804]
It works with keyword search but not with empty search.

**Comment by garfield69** [comment]
Huh?
![image](https://user-images.githubusercontent.com/6933240/77260033-38d74300-6cea-11ea-9a22-74be808edacd.png)

**Comment by garfield69** [comment]
oh, sorry, read the comment not the title.
let me research ;-)

**Comment by garfield69** [comment]
no, I stand my my first post. I'm getting tired.

**Comment by ngosang** [comment]
I fixed it removing and re-adding the tracker. I saw a Cloudflare HTML in the enhanced log.
