### ISSUE TITLE
torrentproject2: error while parsing row (size)

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7806]
```
Manual search for "silicon valley" on torrentproject2 with 19 results.
CardigannIndexer (torrentproject2): Error while parsing row '
<div>
	<span>
		<a href="/t3-4189665/Silicon-Valley-S00E04-1080p-AMZN-WEB-DL-x265-HEVC-10bit-AC3-5-1-Qman-UTR-torrent.html" title="Silicon Valley S00E04 (1080p AMZN WEB-DL x265 HEVC 10bit AC3 5.1 ... torrent">Silicon Valley S00E04 (1080p AMZN WEB-DL x265 HEVC 10bit AC3 5.1 ...</a>
		<span></span>
	</span>
	<span>9</span>
	<span>0</span>
	<span>2 months ago</span>
	<span>1.014.2 MB</span>
</div>':

System.Exception: Error while parsing field=size, selector=div > span:nth-child(5), value=1.014.2 MB: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1580
```

**Comment by garfield69** [comment]
That size `1.014.2 MB` is an invalid number so it's hardly surprising it's being rejected.
Presumably its meant to be 1014.2
How to fix 1.014.2 without breaking 999.2 ?

**Comment by ngosang** [comment]
regex? I don't know the syntax in C# but try to replace only if there are 3 digits after the point.
`[.]([0-9]{3})  => \1`
Eg `1.014.2 MB  => 1014.2 MB`

**Comment by cadatoiva** [comment]
I don't know of a single country's numbering system that uses a `.` for both the digit separator **and** the decimal separator. It's almost always `.` for one `,` for the other. int.Parse can use a culture argument in order to properly parse numbers with separators and such, so it would just be a matter of finding that culture

**Comment by cadatoiva** [comment]
I found this which might help https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo?view=netframework-4.8

**Comment by ngosang** [comment]
> I don't know of a single country's numbering system that uses a . for both the grouping separator and the decimal separator.

There aren't. This is an error in the site and we don't have to provide a global solution. If the regex works it's enough.

**Comment by cadatoiva** [comment]
Yeah, after testing the library version of this, the number format is completely unusable as is. Only a RegEx solution can solve this. Not sure why this site decided to write their numbers all stupid though...

**Comment by garfield69** [comment]
I think this is a one time aberration and not a regular occurrence in the torrentproject2 results.
Since the indexer is yaml, I could work out a regex fix, but its low on my priority list, and I will take this one, and action it when I've run out of other tasks.
