### ISSUE TITLE
[Bug]tracker: danishbits.org

### ISSUE THREAD

**Issue by nic0dk** [Jackett/Jackett#781]
i cant grab torrent via sonarr anymore, but no problem searching for it.

16-12-1 21:32:27.2|Error|ReleaseModule|Downloading torrent failed

[v2.0.0.4409] NzbDrone.Core.Exceptions.ReleaseDownloadException: Downloading torrent failed ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://localhost:9117/dl/danishbits/jcidykjxulz6pk639xgkrey4gz6t0hqz?path=aHR0cHM6Ly9kYW5pc2hiaXRzLm9yZy90b3JyZW50cy5waHAvVGFraW5nLkZpcmUuUzAxRTAzLkZsaXBwaW5nLnRoZS5Td2l0Y2guNzIwcC5IRFRWLngyNjQtREhELnRvcnJlbnQvP2FjdGlvbj1kb3dubG9hZCZhdXRoa2V5PSZ0b3JyZW50X3Bhc3M9JmlkPQ2&file=Taking.Fire.S01E03.Flipping.the.Switch.720p.HDTV.x264-DHD.torrent]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x001a1] in <72ef4295e48b4c9093ad258ad9c4a51f>:0 
  at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in <72ef4295e48b4c9093ad258ad9c4a51f>:0 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String torrentUrl) [0x00024] in <a9d7b78e790d4c1ca8893ac8cc34bb4e>:0 
   --- End of inner exception stack trace ---
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String torrentUrl) [0x00141] in <a9d7b78e790d4c1ca8893ac8cc34bb4e>:0 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x00148] in <a9d7b78e790d4c1ca8893ac8cc34bb4e>:0 
  at NzbDrone.Core.Download.DownloadService.DownloadReport (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x00171] in <a9d7b78e790d4c1ca8893ac8cc34bb4e>:0

**Comment by kaso17** [comment]
Please send an invite to kaso1717 -at- gmail.com. Shouldn't be to hard to fix it.

**Comment by nic0dk** [comment]
sent 👍  thanks

**Comment by kaso17** [comment]
thank you. I can download the torrent files perfectly fine.
Please try the following:
Try downloading directly from danishbits via your webbrowser
Try searching via jackett manal search and try to download a torrent file from there.
Please run "JackettConsole.exe -t" and send me the log output.

**Comment by nic0dk** [comment]
weird..

ok just did it, and getting a black page when downloading from jackett compare to directly on danishbits.org:
i hope the output is enough else i can dump it to a file :)




`12-03 00:09:01 Info   http://192.168.100.3:9117/dl/danishbits/jcidykjxulz6pk639xgkrey4gz6t0hqz?path=aHR0cHM6Ly9kYW5pc2hiaXRzLm9yZy90b3JyZW50cy5waHAvTWlzcy5QZXJlZ3JpbmVzLkhvbWUuRm9yLlBlY3VsaWFyLkNoaWxkcmVuLjIwMTYuREtTdWJzLkRWRFJpcC5YdmlELkFDMy1VTmlUQWlMLnRvcnJlbnQvP2FjdGlvbj1kb3dubG9hZCZhdXRoa2V5PSZ0b3JyZW50X3Bhc3M9JmlkPQ2&file=Miss.Peregrines.Home.For.Peculiar.Children.2016.DKSubs.DVDRip.XviD.AC3-UNiTAiL.torrent
System.Web.Http.Request:   http://192.168.100.3:9117/dl/danishbits/jcidykjxulz6pk639xgkrey4gz6t0hqz?path=aHR0cHM6Ly9kYW5pc2hiaXRzLm9yZy90b3JyZW50cy5waHAvTWlzcy5QZXJlZ3JpbmVzLkhvbWUuRm9yLlBlY3VsaWFyLkNoaWxkcmVuLjIwMTYuREtTdWJzLkRWRFJpcC5YdmlELkFDMy1VTmlUQWlMLnRvcnJlbnQvP2FjdGlvbj1kb3dubG9hZCZhdXRoa2V5PSZ0b3JyZW50X3Bhc3M9JmlkPQ2&file=Miss.Peregrines.Home.For.Peculiar.Children.2016.DKSubs.DVDRip.XviD.AC3-UNiTAiL.torrent
12-03 00:09:01 Info DefaultHttpControllerSelector SelectController Route='indexerID:danishbits,apiKey:jcidykjxulz6pk639xgkrey4gz6t0hqz,controller:Download,action:Download'
System.Web.Http.Controllers: DefaultHttpControllerSelector SelectController Route='indexerID:danishbits,apiKey:jcidykjxulz6pk639xgkrey4gz6t0hqz,controller:Download,action:Download'
12-03 00:09:01 Info DefaultHttpControllerSelector SelectController Download
System.Web.Http.Controllers: DefaultHttpControllerSelector SelectController Download
12-03 00:09:01 Info HttpControllerDescriptor CreateController
System.Web.Http.Controllers: HttpControllerDescriptor CreateController
12-03 00:09:01 Info DefaultHttpControllerActivator Create
System.Web.Http.Controllers: DefaultHttpControllerActivator Create
12-03 00:09:01 Info DefaultHttpControllerActivator Create Jackett.Controllers.DownloadController
System.Web.Http.Controllers: DefaultHttpControllerActivator Create Jackett.Controllers.DownloadController
12-03 00:09:01 Info HttpControllerDescriptor CreateController Jackett.Controllers.DownloadController
System.Web.Http.Controllers: HttpControllerDescriptor CreateController Jackett.Controllers.DownloadController
12-03 00:09:01 Info DownloadController ExecuteAsync
System.Web.Http.Controllers: DownloadController ExecuteAsync
12-03 00:09:01 Info ApiControllerActionSelector SelectAction
System.Web.Http.Action: ApiControllerActionSelector SelectAction
12-03 00:09:01 Info ApiControllerActionSelector SelectAction Selected action 'Download(String indexerID, String path, String apikey, String file)'
System.Web.Http.Action: ApiControllerActionSelector SelectAction Selected action 'Download(String indexerID, String path, String apikey, String file)'
12-03 00:09:01 Info HttpActionBinding ExecuteBindingAsync
System.Web.Http.ModelBinding: HttpActionBinding ExecuteBindingAsync
12-03 00:09:01 Info ModelBinderParameterBinding ExecuteBindingAsync Binding parameter 'indexerID'
System.Web.Http.ModelBinding: ModelBinderParameterBinding ExecuteBindingAsync Binding parameter 'indexerID'
12-03 00:09:01 Info ModelBinderParameterBinding ExecuteBindingAsync Parameter 'indexerID' bound to the value 'danishbits'
System.Web.Http.ModelBinding: ModelBinderParameterBinding ExecuteBindingAsync Parameter 'indexerID' bound to the value 'danishbits'
12-03 00:09:01 Info ModelBinderParameterBinding ExecuteBindingAsync Binding parameter 'path'
System.Web.Http.ModelBinding: ModelBinderParameterBinding ExecuteBindingAsync Binding parameter 'path'
12-03 00:09:01 Info ModelBinderParameterBinding ExecuteBindingAsync Parameter 'path' bound to the value 'aHR0cHM6Ly9kYW5pc2hiaXRzLm9yZy90b3JyZW50cy5waHAvTWlzcy5QZXJlZ3JpbmVzLkhvbWUuRm9yLlBlY3VsaWFyLkNoaWxkcmVuLjIwMTYuREtTdWJzLkRWRFJpcC5YdmlELkFDMy1VTmlUQWlMLnRvcnJlbnQvP2FjdGlvbj1kb3dubG9hZCZhdXRoa2V5PSZ0b3JyZW50X3Bhc3M9JmlkPQ2'
System.Web.Http.ModelBinding: ModelBinderParameterBinding ExecuteBindingAsync Parameter 'path' bound to the value 'aHR0cHM6Ly9kYW5pc2hiaXRzLm9yZy90b3JyZW50cy5waHAvTWlzcy5QZXJlZ3JpbmVzLkhvbWUuRm9yLlBlY3VsaWFyLkNoaWxkcmVuLjIwMTYuREtTdWJzLkRWRFJpcC5YdmlELkFDMy1VTmlUQWlMLnRvcnJlbnQvP2FjdGlvbj1kb3dubG9hZCZhdXRoa2V5PSZ0b3JyZW50X3Bhc3M9JmlkPQ2'
12-03 00:09:01 Info ModelBinderParameterBinding ExecuteBindingAsync Binding parameter 'apikey'
System.Web.Http.ModelBinding: ModelBinderParameterBinding ExecuteBindingAsync Binding parameter 'apikey'
12-03 00:09:01 Info ModelBinderParameterBinding ExecuteBindingAsync Parameter 'apikey' bound to the value 'jcidykjxulz6pk639xgkrey4gz6t0hqz'
System.Web.Http.ModelBinding: ModelBinderParameterBinding ExecuteBindingAsync Parameter 'apikey' bound to the value 'jcidykjxulz6pk639xgkrey4gz6t0hqz'
12-03 00:09:01 Info ModelBinderParameterBinding ExecuteBindingAsync Binding parameter 'file'
System.Web.Http.ModelBinding: ModelBinderParameterBinding ExecuteBindingAsync Binding parameter 'file'
12-03 00:09:01 Info ModelBinderParameterBinding ExecuteBindingAsync Parameter 'file' bound to the value 'Miss.Peregrines.Home.For.Peculiar.Children.2016.DKSubs.DVDRip.XviD.AC3-UNiTAiL.torrent'
System.Web.Http.ModelBinding: ModelBinderParameterBinding ExecuteBindingAsync Parameter 'file' bound to the value 'Miss.Peregrines.Home.For.Peculiar.Children.2016.DKSubs.DVDRip.XviD.AC3-UNiTAiL.torrent'
12-03 00:09:01 Info HttpActionBinding ExecuteBindingAsync Model state is valid. Values: indexerID=danishbits, path=aHR0cHM6Ly9kYW5pc2hiaXRzLm9yZy90b3JyZW50cy5waHAvTWlzcy5QZXJlZ3JpbmVzLkhvbWUuRm9yLlBlY3VsaWFyLkNoaWxkcmVuLjIwMTYuREtTdWJzLkRWRFJpcC5YdmlELkFDMy1VTmlUQWlMLnRvcnJlbnQvP2FjdGlvbj1kb3dubG9hZCZhdXRoa2V5PSZ0b3JyZW50X3Bhc3M9JmlkPQ2, apikey=jcidykjxulz6pk639xgkrey4gz6t0hqz, file=Miss.Peregrines.Home.For.Peculiar.Children.2016.DKSubs.DVDRip.XviD.AC3-UNiTAiL.torrent
System.Web.Http.ModelBinding: HttpActionBinding ExecuteBindingAsync Model state is valid. Values: indexerID=danishbits, path=aHR0cHM6Ly9kYW5pc2hiaXRzLm9yZy90b3JyZW50cy5waHAvTWlzcy5QZXJlZ3JpbmVzLkhvbWUuRm9yLlBlY3VsaWFyLkNoaWxkcmVuLjIwMTYuREtTdWJzLkRWRFJpcC5YdmlELkFDMy1VTmlUQWlMLnRvcnJlbnQvP2FjdGlvbj1kb3dubG9hZCZhdXRoa2V5PSZ0b3JyZW50X3Bhc3M9JmlkPQ2, apikey=jcidykjxulz6pk639xgkrey4gz6t0hqz, file=Miss.Peregrines.Home.For.Peculiar.Children.2016.DKSubs.DVDRip.XviD.AC3-UNiTAiL.torrent
12-03 00:09:01 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Download(String indexerID, String path, String apikey, String file)'
System.Web.Http.Filters: JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Download(String indexerID, String path, String apikey, String file)'
12-03 00:09:01 Info JackettAPINoCacheAttribute OnActionExecutingAsync
System.Web.Http.Filters: JackettAPINoCacheAttribute OnActionExecutingAsync
12-03 00:09:01 Info ApiControllerActionInvoker InvokeActionAsync Action='Download(indexerID=danishbits, path=aHR0cHM6Ly9kYW5pc2hiaXRzLm9yZy90b3JyZW50cy5waHAvTWlzcy5QZXJlZ3JpbmVzLkhvbWUuRm9yLlBlY3VsaWFyLkNoaWxkcmVuLjIwMTYuREtTdWJzLkRWRFJpcC5YdmlELkFDMy1VTmlUQWlMLnRvcnJlbnQvP2FjdGlvbj1kb3dubG9hZCZhdXRoa2V5PSZ0b3JyZW50X3Bhc3M9JmlkPQ2, apikey=jcidykjxulz6pk639xgkrey4gz6t0hqz, file=Miss.Peregrines.Home.For.Peculiar.Children.2016.DKSubs.DVDRip.XviD.AC3-UNiTAiL.torrent)'
System.Web.Http.Action: ApiControllerActionInvoker InvokeActionAsync Action='Download(indexerID=danishbits, path=aHR0cHM6Ly9kYW5pc2hiaXRzLm9yZy90b3JyZW50cy5waHAvTWlzcy5QZXJlZ3JpbmVzLkhvbWUuRm9yLlBlY3VsaWFyLkNoaWxkcmVuLjIwMTYuREtTdWJzLkRWRFJpcC5YdmlELkFDMy1VTmlUQWlMLnRvcnJlbnQvP2FjdGlvbj1kb3dubG9hZCZhdXRoa2V5PSZ0b3JyZW50X3Bhc3M9JmlkPQ2, apikey=jcidykjxulz6pk639xgkrey4gz6t0hqz, file=Miss.Peregrines.Home.For.Peculiar.Children.2016.DKSubs.DVDRip.XviD.AC3-UNiTAiL.torrent)'
12-03 00:09:01 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Download(indexerID=danishbits, path=aHR0cHM6Ly9kYW5pc2hiaXRzLm9yZy90b3JyZW50cy5waHAvTWlzcy5QZXJlZ3JpbmVzLkhvbWUuRm9yLlBlY3VsaWFyLkNoaWxkcmVuLjIwMTYuREtTdWJzLkRWRFJpcC5YdmlELkFDMy1VTmlUQWlMLnRvcnJlbnQvP2FjdGlvbj1kb3dubG9hZCZhdXRoa2V5PSZ0b3JyZW50X3Bhc3M9JmlkPQ2, apikey=jcidykjxulz6pk639xgkrey4gz6t0hqz, file=Miss.Peregrines.Home.For.Peculiar.Children.2016.DKSubs.DVDRip.XviD.AC3-UNiTAiL.torrent)'
System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Download(indexerID=danishbits, path=aHR0cHM6Ly9kYW5pc2hiaXRzLm9yZy90b3JyZW50cy5waHAvTWlzcy5QZXJlZ3JpbmVzLkhvbWUuRm9yLlBlY3VsaWFyLkNoaWxkcmVuLjIwMTYuREtTdWJzLkRWRFJpcC5YdmlELkFDMy1VTmlUQWlMLnRvcnJlbnQvP2FjdGlvbj1kb3dubG9hZCZhdXRoa2V5PSZ0b3JyZW50X3Bhc3M9JmlkPQ2, apikey=jcidykjxulz6pk639xgkrey4gz6t0hqz, file=Miss.Peregrines.Home.For.Peculiar.Children.2016.DKSubs.DVDRip.XviD.AC3-UNiTAiL.torrent)'
12-03 00:09:01 Debug UnixLibCurlWebClient:GetBytes(Url:https://danishbits.org/torrents.php/Miss.Peregrines.Home.For.Peculiar.Children.2016.DKSubs.DVDRip.XviD.AC3-UNiTAiL.torrent/?action=download&authkey=&torrent_pass=&id=)
12-03 00:09:01 Debug UnixLibCurlWebClient:GetBytes Returning OK => 15697 bytes
12-03 00:09:01 Error Error downloading danishbits https://danishbits.org/torrents.php/Miss.Peregrines.Home.For.Peculiar.Children.2016.DKSubs.DVDRip.XviD.AC3-UNiTAiL.torrent/?action=download&authkey=&torrent_pass=&id= MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
  at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent (MonoTorrent.BEncoding.RawReader reader) [0x0001e] in <2bea12db43634c238e7bd39fb9f0ca6a>:0
  at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent (System.IO.Stream s) [0x00006] in <2bea12db43634c238e7bd39fb9f0ca6a>:0
  at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent (System.Byte[] bytes) [0x00006] in <2bea12db43634c238e7bd39fb9f0ca6a>:0
  at Jackett.Controllers.DownloadController+<Download>c__async0.MoveNext () [0x00179] in <bdea995173434d0c9df172ea4b0d509a>:0
12-03 00:09:01 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: <null>, Headers:
{
}'
System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Action returned 'StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: <null>, Headers:
{
}'
12-03 00:09:01 Info ApiControllerActionInvoker InvokeActionAsync
System.Web.Http.Action: ApiControllerActionInvoker InvokeActionAsync
12-03 00:09:01 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Download(String indexerID, String path, String apikey, String file)'
System.Web.Http.Filters: JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Download(String indexerID, String path, String apikey, String file)'
12-03 00:09:01 Info JackettAPINoCacheAttribute OnActionExecutedAsync
System.Web.Http.Filters: JackettAPINoCacheAttribute OnActionExecutedAsync
12-03 00:09:01 Info DownloadController ExecuteAsync
System.Web.Http.Controllers: DownloadController ExecuteAsync
12-03 00:09:01 Info   Content-type='none', content-length=unknown
System.Web.Http.Request:   Content-type='none', content-length=unknown
12-03 00:09:01 Info DownloadController Dispose
System.Web.Http.Controllers: DownloadController Dispose
12-03 00:09:01 Info DownloadController Dispose
System.Web.Http.Controllers: DownloadController Dispose
`

**Comment by nic0dk** [comment]
btw. running Jackett Version 0.7.653.0 via mono on ubuntu, but you properly already know :D

**Comment by kaso17** [comment]
can you please send me the HTML code you're getting when accessing the following link.
https://danishbits.org/torrents.php?action=newbrowse&search=&pre_type=torrents&type=

**Comment by nic0dk** [comment]
do you mean view source of the site?

something like this?: 
`
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title>Torrents :: Danishbits.org</title>
	<meta http-equiv="X-UA-Compatible" content="chrome=1;IE=edge" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<script type="text/javascript">
	    var authkey = 'xxxxxxxxxxx';
	    var userid = 90979;
	</script>

		<script type="text/javascript" src="min/?g=default&v=5"></script>
		<meta name="google" value="notranslate">

	<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

	<link rel="shortcut icon" href="favicon.ico?v=3" />
	<link rel="stylesheet" type="text/css" href="min/?g=style-default&v=5" />
	<link rel="search" type="application/opensearchdescription+xml" title="Danishbits.org Torrents" href="opensearch.php?type=torrents" />
	<link rel="search" type="application/opensearchdescription+xml" title="Danishbits.org Requests" href="opensearch.php?type=requests" />
	<link rel="search" type="application/opensearchdescription+xml" title="Danishbits.org Forums" href="opensearch.php?type=forums" />
	<link rel="search" type="application/opensearchdescription+xml" title="Danishbits.org Wiki" href="opensearch.php?type=wiki" />
	<link rel="alternate" type="application/rss+xml" href="feeds.php?feed=feed_news&amp;user=90979&amp;auth=ba04ab2366f16b4f5b4fa0e0183c954b&amp;passkey=ls1n9ood14ua5r7tah6ngy1zz5wwicd2&amp;authkey=9ac5cbdb6e9660a33ba9e47676b27641" title="Danishbits.org - News" />`

**Comment by oshh94** [comment]
I having this problem as well, it also affects couchpotato.
Let me know if there's anything i can do to help.
Logfiles also show 404 not found.

**Comment by nic0dk** [comment]
yeah im getting 404 file not found... maybe i should try to reinstall jackett, maybe fire it up in a docker and see if that does any change :)

**Comment by kaso17** [comment]
@nic0dk exactly, but for debugging the table containing the search results is important.

**Comment by nic0dk** [comment]
@kaso17 i agree - let me know what else you need, to get deeper with the troubleshooting :)

**Comment by kaso17** [comment]
@nic0dk please send the complete HTML page of the search results (you only posted a few header lines)

**Comment by nic0dk** [comment]
got it. i removed the passkey FYI.

http://pastebin.com/D0BStmGr

**Comment by kaso17** [comment]
Somehow you've a button next to the DL link button which shows the poster on mouseover.
That caused the problem.
