### ISSUE TITLE
[tenyardtracker] The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject]  CN=talk.tenyardtracker.com[Issuer]  CN=Let's Encrypt Authority X3, O=Let's Encrypt, C=US[Serial Number]  03838E75D49D27AC729F786ABF82723B4D7C[Not Before]  2/26/2020 1:23:16 AM[Not After]  5/26/2020 2:23:16 AM[Thumbprint]  C77A88F4AC9798E3E5B18C4AA6CE2ABF32ECF025 (Config)

### ISSUE THREAD

**Issue by binyaminyblatt** [Jackett/Jackett#7812]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by cadatoiva** [comment]
None of our maintainers have access to this private torrent. If you could provide us with more information as outlined in our template above we can help with your issue.

**Comment by garfield69** [comment]
the certificate used by this site is invalid, generating error: **NET::ERR_CERT_COMMON_NAME_INVALID**
The cert with a thumb print of **C77A88F4AC9798E3E5B18C4AA6CE2ABF32ECF025** was issued by **Let's Encrypt** for **talk.tenyardtracker.com** but the site domain is actually **tenyardtracker.com**
I will load a certificate ignore for the indexer to ignore the invalid cert.

**Comment by garfield69** [comment]
Jackett 0.14.253
