### ISSUE TITLE
[scenetime] Your cookie did not work: The 'Value'='signup,donateok' part of the cookie is invalid. (Config)

### ISSUE THREAD

**Issue by binyaminyblatt** [Jackett/Jackett#7813]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Use your dashboard to trashbin the scenetime config and add the indexer config afresh.
when you paste your fresh cookie, double check that the cookie string does not contain any key that has the signup,donateok. if you find one then remove it before saving the config. 
for example: if the cookie looks something like:
```
__cfduid=d***4; cf_clearance=7***0; PHPSESSID=d***j; uid=4***8; akey=signup,donateok; pass=2****9
```
then remove `akey=signup,donateok;`
