### ISSUE TITLE
Ncore - Ncore now support IMDB searching.

### ISSUE THREAD

**Issue by vampywiz17** [Jackett/Jackett#7822]
Ncore private tracker now support IMDB search, It possible to update Jackett to support it?

**Comment by RoloSoze** [comment]
@vampywiz17 Thank you for highlighting this. nCore is already listed here - #4859 - However, a C# developer needs access to nCore to implement this feature. Do you have an invite you can share?

**Comment by vampywiz17** [comment]
@RoloSoze 

Yes, i able to send invite. What is the email that i send it?

**Comment by RoloSoze** [comment]
@ngosang @cadatoiva Is one of you guys able to take this?

**Comment by cadatoiva** [comment]
I can take this one. cadatoiva -at- yahoo.com

**Comment by RoloSoze** [comment]
> 
> 
> I can take this one. cadatoiva -at- yahoo.com

@vampywiz17 Here you go :)

@cadatovia Thanks for taking this. No one has maintained nCore for a long time. It would be great if you could also check the category mappings!

**Comment by RoloSoze** [comment]
@cadatoiva Thanks for taking this. No one has maintained nCore for a long time. It would be great if you could also check the category mappings!

**Comment by vampywiz17** [comment]
> > I can take this one. cadatoiva -at- yahoo.com
> 
> @vampywiz17 Here you go :)

OK i will send the invite tomorrow!

**Comment by RoloSoze** [comment]
> OK i will send the invite tomorrow!

@vampywiz17 Did you manage to send the invite to @cadatoiva?

**Comment by vampywiz17** [comment]
@RoloSoze @cadatoiva 

I sent the invite.

**Comment by morpheus133** [comment]
> @cadatoiva Thanks for taking this. No one has maintained nCore for a long time. It would be great if you could also check the category mappings!

@RoloSoze  What is the problem with category mappings?

**Comment by RoloSoze** [comment]
> 
> 
> > @cadatoiva Thanks for taking this. No one has maintained nCore for a long time. It would be great if you could also check the category mappings!
> 
> @RoloSoze What is the problem with category mappings?

Hi @morpheus133. I'm not saying there is necessarily a problem with the mappings. It's just that as far as I know, nCore has not been maintained in Jackett for a while, so it might be the case that new categories have not been mapped yet. If you checked, and eveything looks good, then we're fine.

**Comment by dimqua** [comment]
What are these checkboxes for?
![](https://i.imgur.com/9AUHPpr.png)

**Comment by garfield69** [comment]
apparently they are language filters.
so only results with the specified language are returned.
It would be helpful to have a info block with a description

**Comment by RoloSoze** [comment]
Closed with f7aa23b6ddd00cc5e9e269469bf7da421ef987c4

**Comment by garfield69** [comment]
Jackett 0.16.54
