### ISSUE TITLE
[Bug] ProStyleX Login

### ISSUE THREAD

**Issue by zero77** [Jackett/Jackett#7823]
ProStyleX does not require a login to use magnets, therefore can you please make the username and password optional, thanks.
https://prostylex.org/

**Comment by garfield69** [comment]
The site went from public to semi-private back in 20th Feb 2020 #7248 
The Browse torrents page can be accessed freely, and if you know the details page of the torrent you can get the magnet without login.
If you use the Search box you get presented with a login request.
So if you use the dashboard search to search for a torrent, or use an app like Sonarr, Radarr etc to access the site via Jackett to search for torrents, then you need an account on the site.
So I cannot implement your request.
