### ISSUE TITLE
M-Team TP (MTTP) Category Mapping Needs to be Updated

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7824]
I mistakenly thought MTTP does not return dead torrents. That's not the case. It omits certain search results due to certain categories not being mapped in Jackett. The category mapping needs to be updated.

**Comment by garfield69** [comment]
no one on the jackett team has an account on this site, so you are going to have to provide the html of the torrent search page so we can update the categories.
follow https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source
the relevent pages should be at https://pt.m-team.cc/torrents.php and https://pt.m-team.cc/adult.php
Thanks.

**Comment by RoloSoze** [comment]
@garfield69 Here you go:
[M-Team - TP   Search results for The Rise of Skywalker - Powered by NexusPHP.zip](https://github.com/Jackett/Jackett/files/4371096/M-Team.-.TP.Search.results.for.The.Rise.of.Skywalker.-.Powered.by.NexusPHP.zip)
![image](https://user-images.githubusercontent.com/23747425/77347714-a39a7580-6d0e-11ea-9900-0c0bd12fd2a1.png)

**Comment by RoloSoze** [comment]
I believe the adult categories do no exist anymore. I can't find them anywhere, and the adult link leads back to the homepage.

**Comment by garfield69** [comment]
Can you check your account settings on the site, is it possible that you have a profile option that enables/disables access to the adult page?

**Comment by RoloSoze** [comment]
Huh! You're right: 
[M-Team - TP   Search results for Tokyo - Powered by NexusPHP.zip](https://github.com/Jackett/Jackett/files/4371205/M-Team.-.TP.Search.results.for.Tokyo.-.Powered.by.NexusPHP.zip)
![image](https://user-images.githubusercontent.com/23747425/77349563-92069d00-6d11-11ea-8640-57cda804c60c.png)

**Comment by garfield69** [comment]
going to need the adult html so I can check the cat numbers ;-)

**Comment by garfield69** [comment]
oh sorry, didnt see the link above the pic.
need new lenses ;-D

**Comment by garfield69** [comment]
the only changes to the cats that I can see is that they have dropped the audio cats, 
```yaml
      - {id: 406, cat: Audio/Video, desc: "MV(演唱)"}
      - {id: 408, cat: Audio/Other, desc: "Music(AAC/ALAC)"}
      - {id: 434, cat: Audio, desc: "Music(無損)"}
```
all the adult cats are there.
what I did find is that the current indexer is using incldead=1 in its search url
and the html has 
```html
<td class="bottom" style="padding: 1px; padding-left: 10px">
  <select class="med" name="incldead" style="width: 100px;">
    <option value="0">including dead</option>
    <option value="1">active </option>
    <option value="2">dead</option>
  </select>
</td>
```
so the indexer needs to be set to incldead=0 to include dead torrents in searches.

before I remove the audio cats can you do a search for MP3 , FLAC, Music, and anything else audio related, just to confirm that they have in fact no torrents under the cats 406, 408, 434.
Otherwise the indexer will report null cats for those torrents.

**Comment by RoloSoze** [comment]
I'll do that shortly. In my tests, results from cat 404 seem to have been missing. Is it implemented in Jackett?

**Comment by garfield69** [comment]
yes.
```yaml
      - {id: 404, cat: TV/Documentary, desc: "紀錄教育"}
```
but if all the 404 torrents are inactive they would not show up in the indexer results since incldead is currently set to 1 (active only) instead of 0 (include dead)

Also, I'd like to get the nexusphp version. can you click on that link at the bottom of the page (powered by NexusPHP). it should take you to a version page with something like
 `Standard v1.5 Beta 4` or whatever.
Thanks.

**Comment by RoloSoze** [comment]
> Also, I'd like to get the nexusphp version. can you click on that link at the bottom of the page (powered by NexusPHP). it should take you to a version page with something like
> `Standard v1.5 Beta 4` or whatever.

![image](https://user-images.githubusercontent.com/23747425/77353483-6dadbf00-6d17-11ea-9144-ad8985b722ab.png)

**Comment by garfield69** [comment]
excellent. I can now cross check one of the other nexusphp 1.5b indexers and see if there is anything we can add that might be missing on the mttp indexer since it was last updated.

**Comment by RoloSoze** [comment]
Music still exists but the reason why you didn't see it is that, for whatever reason, the music categories do not appear on the default torrents page. They have their own tab (like adults):

https://pt.m-team.cc/music.php

![image](https://user-images.githubusercontent.com/23747425/77353739-e6ad1680-6d17-11ea-8645-991f9be10421.png)

![image](https://user-images.githubusercontent.com/23747425/77353825-16f4b500-6d18-11ea-8656-3d1908871933.png)
[M-Team - TP   Search results for aerosmith - Powered by NexusPHP.zip](https://github.com/Jackett/Jackett/files/4371443/M-Team.-.TP.Search.results.for.aerosmith.-.Powered.by.NexusPHP.zip)

**Comment by RoloSoze** [comment]
Here's the 'Movie' tab:
![image](https://user-images.githubusercontent.com/23747425/77354323-0264ec80-6d19-11ea-81d1-8581b1b7e134.png)

[M-Team - TP   Search results for tt2527338 - Powered by NexusPHP.zip](https://github.com/Jackett/Jackett/files/4371457/M-Team.-.TP.Search.results.for.tt2527338.-.Powered.by.NexusPHP.zip)

The '4K' and 'TV' tabs just pre-tick existing categories to narrow the search. 'Collages' and 'Artists' do not browse/search torrents

**Comment by RoloSoze** [comment]
![image](https://user-images.githubusercontent.com/23747425/77356086-0cd4b580-6d1c-11ea-9777-b9ad14dcc51b.png)

Here's a look at all the categories as they appear on my profile/user cp page.

**Comment by garfield69** [comment]
additional research please.
search for a movie on the site that has an imdb link in the torrent description, grab the imdbid and use it in the search to see if you can find the same torrent with either the search-in imdburl or description and report which one works if any. 
Beitai for instance only returns imdbid searches when looking at descriptions rather than imdburl.

**Comment by garfield69** [comment]
Oh, you already done this ;-)
I'm falling behind on the email trail
Thanks.

**Comment by garfield69** [comment]
Jackett 0.14.253

**Comment by RoloSoze** [comment]
> 
> 
> Jackett 0.14.253

![image](https://user-images.githubusercontent.com/23747425/77394006-b34ca500-6d74-11ea-8691-8809c11ad3e0.png)

Jackett displays no names whatsoever for entries with IMDb info :(

**Comment by garfield69** [comment]
that is what can happen when one does not have an account to a site to test when one is making changes by touch like this :-(
I'll push a pre-release with a possible fix lets see if that sorts it out.

**Comment by garfield69** [comment]
try Jackett pre-release 0.14.254

**Comment by RoloSoze** [comment]
> 
> 
> try Jackett pre-release 0.14.254

I'll get the chance to test this later today. Thanks.

**Comment by RoloSoze** [comment]
> 
> 
> > try Jackett pre-release 0.14.254
> 
> I'll get the chance to test this later today. Thanks.

All good now! Thank you!
