### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down.: Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by goodpunk6** [Jackett/Jackett#7825]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: ubuntu 18

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: NA

**Jackett Version**: Jackett Version 0.14.222.0

**Last Working Jackett Version**: don't know

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
when i try to search for a torrent via piratebay, i get this [thepiratebay] Exception (thepiratebay): Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down.: Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down. (Test)

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
The official ThePirateBay site domain is offline, accessible currently only via tor.
But if you use your Jackett dashboard to edit the config for that indexer, you will see alternate links you can try out instead that may work for you. These are unofficial proxy sites that run off the feed from TPB, and should work with the Jackett indexer, but can break at any time.
