### ISSUE TITLE
Improving the search functionality & API Integration in Awesome-HD [AHD]

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7829]
I'm just gonna cut, paste and modify the AHD-related posts from #6783 - This issue will be AHD-specific, whereas #6783 will now be MTV-specific:
***
@RoloSoze 
Searching AHD is different from searching most other well-known trackers. For example, if I wanted to search for a show like Sons of Anarchy, almost all other trackers will return the release name for each season.

However, Awesome-HD only returns something like this 'Sons of Anarchy: Season 01', one for each S01 release that's available on the tracker. I have to click on it & go to the website to see the release's full name.

I get that this might have to do with the nested nature of Gazelle trackers, but the search functionality in other Gazelle trackers (e.g. Nebulance, Orpheus) works accurately and does return the correct release name.

Can this be fixed? It's a problem because when manually searching multiple trackers at once, the release I'm after may very well be on one of these two trackers but it's easy to miss if I don't look for it there specifically.
***
@garfield69 
the awsome-hd indexer was written by the author in yaml knowing it was a piecemeal solution. #1481 #1943 #5225 
its been agreed that the only solution is for the indexer to be rewritten in C#, but a volunteer has yet to contribute.
***
@RoloSoze 
@garfield69 PTP is implemented perfectly and it's very similar to both AHD & MTV. Whoever worked on that is more than welcome to work on these two :)
***

List of remaining AHD issues in Jackett:

**A) Issues related to searching for movies:**
-	[x] AHD currently does not return any results when the year is entered. For example, 'Jojo Rabbit 2019' returns no results. However, 'Jojo Rabbit' works fine [c508177]

**B) Issues related to searching for TV series:**
-	[x] AHD does not always return all relevant results when searching for a specific season. For example, this applies to all Game of Thrones seasons (Game of Thrones S02 does not return all results, and Game of Thrones S05 returns no results at all) [2672ade]
-	[ ] When searching for a specific season, Jackett is unable to return the audio track(s) related to that season due to the inability to associate the audio track of each season with the year

**C) General issue - Processing search keywords:** 
-	[ ] Searching for ‘Avengers Endgame’ returns nothing; the exact movie title must be used ‘i.e. Avengers: Endgame’ with the colon – Special characters are often ignored by users, so this could potentially create an issue
-	[ ] Searching AHD only works if the title/torrent name starts with the keyword used. For example, ‘Harry Potter’ works, but ‘Potter’ does not 
-	[ ] Much like the movie year, adding the resolution in the search term (e.g. 2160p, 1080p) returns nothing 

**D) General issue - Others:**
-	[ ]  Search results are only limited to 30 entries, which is very limiting. This is especially evident when searching for shows/movies that have many entries (e.g. The Walking Dead, Game of Thrones, Harry Potter)
-	[ ]  The number of files in each search result is available on the website but not in the API, so it’s not shown in Jackett
-	[ ]  We cannot grab the latest TV series. The API `latestmovies` only reruns movies, and a keyword-less search in the `titlesearch` API raises an error. This is really important for Sonarr

-	[ ]  The API does not return the category, so the correct category had to be guessed in the implementation. For example, if the title contains Season XX, it is considered a TV series, otherwise it’s a movie. A similar workaround has been implemented to guess the audio track category

**Comment by RoloSoze** [comment]
@ngosang 
I will take a look if someone invites me. ngosang @ hotmail .es
***
@RoloSoze 
#7553 @ngosang Related :)

**Comment by RoloSoze** [comment]
@ngosang 
@RoloSoze I think AHD is fixed in #7827

**Comment by RoloSoze** [comment]
@ngosang This is now the AHD-specific issue. Issue #6783 had much more details about MTV so I decided to make that one MTV-specific.

**Comment by ngosang** [comment]
No need. Just add the remaining features to this issue after you test the PR.
Btw, you can download the binaries from the PR from https://dev.azure.com/jackett/jackett/_build/results?buildId=248&view=artifacts&type=publishedArtifacts
Download the `drop` folder if you want to test.

**Comment by RoloSoze** [comment]
>  Just add the remaining features to this issue after you test the PR.

@ngosang Got it. You mean the 3-4 issues you reported to the SYSOP, right? Did they say they plan to work on fixing them?

**Comment by RoloSoze** [comment]
List of remaining AHD issues in Jackett:

A) Issues related to searching for movies:
-	[ ] AHD currently does not return any results when the year is entered. For example, 'Jojo Rabbit 2019' returns no results. However, 'Jojo Rabbit' works fine


B) Issues related to searching for TV series:
-	[ ] AHD does not always return all relevant results when searching for a specific season. For example, this applies to all Game of Thrones seasons (Game of Thrones S02 does not return all results, and Game of Thrones S05 returns no results at all)

C) General issue - Processing search keywords: 
-	[ ] Searching for ‘Avengers Endgame’ returns nothing; the exact movie title must be used ‘i.e. Avengers: Endgame’ with the colon – Special characters are often ignored by users, so this could potentially create an issue
-	[ ] Searching AHD only works if the title/torrent name starts with the keyword used. For example, ‘Harry Potter’ works, but ‘Potter’ does not 
-	[ ] Much like the movie year, adding the resolution in the search term (e.g. 2160p, 1080p) returns nothing 

D) General issue - Others:
-	[ ]  Search results are only limited to 30 entries, which is very limiting. This is especially evident when searching for shows/movies that have many entries (e.g. The Walking Dead, Game of Thrones, Harry Potter)
-	[ ]  The number of files in each search result is available on the website but not in the API, so it’s not shown in Jackett
-	[ ]  We cannot grab the latest TV series. The API `latestmovies` only reruns movies and a keyword-less search in the `titlesearch` API raises an error. This is really important for Sonarr

-	[ ]  The API does not return the category, so the correct category had to be guessed in the implementation. For example, if the title contains Season XX, it is considered a TV series, otherwise it’s a movie. This does not always work accurately (e.g. it does not work with audio tracks).

**Comment by RoloSoze** [comment]
@ngosang I know all of the above issues cannot be fixed from our part, except maybe for Issue B regarding TV seasons. Can something be done about that or should it be added to the list of issues to be sent to the SYSOP?

**Comment by ngosang** [comment]
> AHD does not always return all relevant results when searching for a specific season. 

Fixed in #7947

> Search results are only limited to 30 entries, which is very limiting.

This point is important, they should increase it to 100.

I think that's all.

**Comment by RoloSoze** [comment]
> Fixed in #7947

Thank you. I'll test it tomorrow. One point regarding season packs: When uploading a full season pack, AHD asks users to keep the year of the original series release. 

For example, Game of Thrones came out in 2011, so AHD likes to keep that year for all seasons. However, some users make the mistake of entering the release year of each season (e.g. for S05, they would enter 2015 instead of keeping the original year 2011).

So when searching for Game of Thrones Season 05 on AHD, you'll find some releases under 2011 and some under 2015. 

Does this fix account for this and return all relevant results? There should be 12 results including audio tracks.

**Comment by ngosang** [comment]
It's working because I'm not using the year. I think they don't return audio tracks in the API.

1.  S05 I'm getting 9 results 
2.  S01 I'm getting 11 results

**Comment by RoloSoze** [comment]
> They are returning the Audio tracks, but I can't search for audio tracks because I don't know the year. If you search just "Game of Thrones" you will get some audio tracks.

OK. Yeah, you're getting the correct number of results, minus the audio tracks. I'll mention this to them: Audio tracks for movies work fine but we cannot return them for shows due to the inability to associate the audio track of each season with the year. 

Last question, with #7947 how many results are you getting for S07? You should be getting 7 results (one for the Extras). Right now in Jackett, I'm only getting 6 results.

**Comment by ngosang** [comment]
> how many results are you getting for S07?

7

I added another change to add audio track category.
Btw, I included the "best" way to implement the missing features in the API, you should include that in your email => https://github.com/Jackett/Jackett/pull/7827

**Comment by RoloSoze** [comment]
> 7

Perfect!




> I added another change to add audio track category.

Perfect. I'll test it tomorrow before contacting them with the full list. Thank you.

> Btw, I included the "best" way to implement the missing features in the API, you should include that in your email => #7827

Yes, you mentioned two best solutions for a couple of issues. I will include them. The list of issues I'm sending them is the same as what I listed above, but with more details, including your solutions.

**Comment by ngosang** [comment]
> AHD currently does not return any results when the year is entered. For example, 'Jojo Rabbit 2019' returns no results. However, 'Jojo Rabbit' works fine

@RoloSoze Fixed in #8342

**Comment by RoloSoze** [comment]
> @RoloSoze Fixed in #8342

Works really well! Thank you! The rest is now is on hold pending changes from their end!

**Comment by RoloSoze** [comment]
Tracker is sadly gone for good :( Closing this issue.
