### ISSUE TITLE
beyond-hd changes required

### ISSUE THREAD

**Issue by stokedcrf** [Jackett/Jackett#783]
BHD recently changed the domain in which their tracker is on. 
Since then, jackett fails to connect and aquire search results. :(

(perhaps the announce url changing is hindering jackett from working?)

This is a confirmed issue as per multiple users reporting via IRC

**Comment by kaso17** [comment]
It's working fine for me, please try re configuring the tracker.

**Comment by mooseflunky** [comment]
I'm having the same problem as well. Hitting the test button results in: Test failed for BeyondHD. Found no results while trying to browse this tracker. I'm also getting no hits when attempting searches in both sonarr and couchpotato.

**Comment by kaso17** [comment]
they invalidated the cookies recently, you've to configure and save the tracker again, that should fix it.

**Comment by mooseflunky** [comment]
You were right.  Selecting the new cookie and entering it into jackett cured what ailed it.

Thanks!

**Comment by stokedcrf** [comment]
I also agree, this fixed the issue for me as well! Cookie problem. Thank you!
