### ISSUE TITLE
[frozenlayer] Exception (frozenlayer): Authentication failed because the remote party has closed the transport stream.: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by Ramshu** [Jackett/Jackett#7832]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows [Versión 10.0.18363.720]

**.Net Runtime**: .Net-Framework

**.Net Version**: 3.5 & 4.8

**Jackett Version**:  v0.14.257.0 

**Last Working Jackett Version**:  v0.14.222

**Are you using a proxy or VPN?**: NO

### Description

Test

### Logged Error Messages

An error occured while testing this indexer
Exception (frozenlayer): Authentication failed because the remote party has closed the transport stream.: The SSL connection could not be established, see inner exception.

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by Ramshu** [comment]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows [Versión 10.0.18363.720]

**.Net Runtime**: .Net-Framework

**.Net Version**: 3.5 & 4.8

**Jackett Version**:  v0.14.257.0 

**Last Working Jackett Version**:  v0.14.222

**Are you using a proxy or VPN?**: NO

### Description

Test


### Logged Error Messages

An error occured while testing this indexer
Exception (frozenlayer): Authentication failed because the remote party has closed the transport stream.: The SSL connection could not be established, see inner exception.

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
This indexer works for me.
Read https://github.com/Jackett/Jackett/wiki/Troubleshooting#an-existing-connection-was-forcibly-closed-by-the-remote-host
if none of the items apply to you then provide the enhanced log so we can dig deeper.

**Comment by Ramshu** [comment]
> 
> 
> This indexer works for me.
> Read https://github.com/Jackett/Jackett/wiki/Troubleshooting#an-existing-connection-was-forcibly-closed-by-the-remote-host
> if none of the items apply to you then provide the enhanced log so we can dig deeper.

Thanks, my antivirus blocked this url thinking it was phishing.
