### ISSUE TITLE
[estrenosdtl] Exception (estrenosdtl): The operation was canceled.: The operation was canceled. (Test)

### ISSUE THREAD

**Issue by Ramshu** [Jackett/Jackett#7833]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows [Versión 10.0.18363.720]

**.Net Runtime**: .Net-Framework

**.Net Version**: 3.5 & 4.8

**Jackett Version**:  v0.14.257.0 

**Last Working Jackett Version**:  v0.14.222

**Are you using a proxy or VPN?**: NO

### Description

Test

### Logged Error Messages

An error occured while testing this indexer
Exception (estrenosdtl): The operation was canceled.: The operation was canceled.

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
The indexer works for me.
Have a read of https://github.com/Jackett/Jackett/wiki/TroubleShooting#a-task-was-canceled
if none of the items apply to you then provide the enhanced log so we can dig deeper.

**Comment by Ramshu** [comment]
It worked on its own, I suppose it would be a problem on the web.
Thanks :)
