### ISSUE TITLE
[animetosho] Exception (animetosho): The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 5, position 36.: The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 5, position 36. (Test)

### ISSUE THREAD

**Issue by Koyakami** [Jackett/Jackett#7835]
### Environment

**OS**: Unknown (Seedhost.eu)

**.Net Runtime**: Mono I think

**.Net Version**: Unknown

**Jackett Version**: 0.12.1486.0

**Last Working Jackett Version**: 0.12.1486.0

**Are you using a proxy or VPN?** None

### Description

Anime Tosho site wasn't reachable using Jackett, so I did a test on Jackett and it gave this error. Not sure when it started but I only noticed about a week ago and now I'm actually raising it as I didn't see anything in the issues.

### Logged Error Messages

Logs don't seem to state any errors.

Not sure how to get the logs as it's going through a seedbox.

**Comment by garfield69** [comment]
Time you upgraded from Jackett 0.12.* to 0.14.* 
the newest release will contain the fix you need to access animetosho again.
