### ISSUE TITLE
Test failed for torrentbd: Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by ShahadatRD** [Jackett/Jackett#784]
Hey, everything was perfectly alright till last night. but today while testing TorrentBD i am getting the error, "Test failed for torrentbd: Found no results while trying to browse this tracker".

**Comment by kaso17** [comment]
try running jackettconsole with the -t option to dump the HTML responses.
Most likely you've to re-configure the tracker to solve the cloudflare captcha again.

**Comment by ShahadatRD** [comment]
Yes! it works for me when i have re-configured tracker.

**Comment by kaso17** [comment]
ok, seems like everyone has to resolve the captcha sooner or later. If it's to annoying for you you've to convince the site op to change their cloud flare settings to something without captcha or add an exception for http://www.torrentbd.com/torrent/torrents-search.php
