### ISSUE TITLE
Does not work with couchpotato

### ISSUE THREAD

**Issue by ameel** [Jackett/Jackett#7843]
### Environment

**OS**: Ubuntu (4.15.0-91-generic)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.14.257.0

**Last Working Jackett Version**: 0.14.257.0

**Are you using a proxy or VPN?** no

### Description

1. Setup torrentpotato on couchpotato using Jackett
2. Download selected torrent from couchpotato
3. Couchpotato states it has snatched the torrent. However, couchpotato shows error logs as follows:

### Logged Error Messages
```
[hpotato.core.plugins.base] Opening url: get http://127.0.0.1:9117/dl/ettv/?jackett_apikey=ce5nd31ndxgge6jfot6lidq2cyz91hf9&path=Q2ZESjhDZS1HaVROdEZwSWlDeGF1eTFKUjZENzFkR29Kc0gzUGxPMnZodC13d25uQm9OdUpxYmY0bG5ueHV5ZXVUR0VQa01odTBxeTRZSW00cXZyc0VIYTBJX29SOWxvZnRVX3ZJQ2VMZnVLcURRX1B6X0ZLdFlIcTlfOHdIZFgzOFpJWTVtY3BEWGYtUWVjQTlxYmU3bGRibWNaM25zWDFyOUtqZUZkNExZOTJQUTRoeGZyZTYtSEVFU1E0TzlvMkN4dHVaaGRfeEo2WW9DajdZemVJOUJ5aVdpTGxDWUlGT3VXamRTRUQ1NDNnUC04&file=47.Meters.Down.Uncaged.2019.1080p.WEB-DL.DD5.1.H264-FGT, data: []
03-25 10:02:39 ERROR
[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last): File "/opt/couchpotato/couchpotato/core/media/_base/providers/base.py", line 207, in download return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False) File "/opt/couchpotato/couchpotato/core/plugins/base.py", line 221, in urlopen response = r.request(method, url, **kwargs) File "/opt/couchpotato/libs/requests/sessions.py", line 469, in request resp = self.send(prep, **send_kwargs) File "/opt/couchpotato/libs/requests/sessions.py", line 598, in send history = [resp for resp in gen] if allow_redirects else [] File "/opt/couchpotato/libs/requests/sessions.py", line 194, in resolve_redirects **adapter_kwargs File "/opt/couchpotato/libs/requests/sessions.py", line 571, in send adapter = self.get_adapter(url=request.url) File "/opt/couchpotato/libs/requests/sessions.py", line 645, in get_adapter raise InvalidSchema("No connection adapters were found for '%s'" % url) InvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:97066f9cd98e68b67c0cb321292af6e2b78382d3&dn=47.Meters.Down.Uncaged.2019.1080p.WEB-DL.DD5.1.H264-FGT&xl=3287579152&tr=http://tracker.trackerfix.com:80/announce&tr=udp://9.rarbg.me:2750/announce&tr=udp://9.rarbg.to:2790/announce'
03-25 10:04:52 ERROR
[chpotato.core.plugins.log] API log: {'file': u'http://HOST/static/scripts/combined.plugins.min.js?1585052020', 'message': u"chrome 80: \nUncaught TypeError: Cannot read property 'length' of undefined", 'line': u'1288', 'page': u'http://HOST/home/', '_request': <couchpotato.api.ApiHandler object at 0x7f7661b2b610>}
```

**Comment by garfield69** [comment]
I do not believe this has anything to do with jackett.
CP has received the magnet from Jackett which is valid (If I copy and paste the magnet URL you provided in this post to my torrentclient it likes it),
but then CP complains `No connection adapters were found for magnet`

Which implies you have a setup issue.

This is not a forum for couchpotato support or ubuntu support, but hopefully this will get you going in the right direction.
If it does not work then google and research elsewhere.

- Either  you have not setup CP correctly  (read up on the couchpotato support site for anything to do with magnet support).
- or you have not associated magnet with your torrentclient and your OS does not know what to do with it (see below fora possible solve).

Test this for yourself. 
Open a browser and paste the following in the address bar and see if the magnet gets routed to your torrentclient.
```
magnet:?xt=urn:btih:97066f9cd98e68b67c0cb321292af6e2b78382d3&dn=47.Meters.Down.Uncaged.2019.1080p.WEB-DL.DD5.1.H264-FGT&xl=3287579152&tr=http://tracker.trackerfix.com:80/announce&tr=udp://9.rarbg.me:2750/announce&tr=udp://9.rarbg.to:2790/announce
```

if it did not work then there is your problem.

you can check your magnet association defaults with:
```
xdg-mime query default x-scheme-handler/magnet
gvfs-mime --query x-scheme-handler/magnet
```

and set them with
```
xdg-mime default qbittorent.desktop x-scheme-handler/magnet
gvfs-mime --set x-scheme-handler/magnet qbittorrent.desktop
```
Assuming you have a `qbittorrent.desktop` file at `/usr/share/applications/`

**Comment by zazizou** [comment]
My two cents
 
I found that the issue come probably from retrieving the magnet link like :

http://127.0.0.1:9117/dl/ettv/?jackett_apikey=**** , as for ETTV.

Some providers like Zoogle exposes the magnet link directly  and those can be retrieve by couchpotato with no issue.  You can check this by doing a manual search  on jackett and look at the icon of last column "Download" .

On a headless server  couchpotato  does not rely on "*-mime". Maybe there is something to consider in order to improve how the torrent (magnet) link is sent via  http://jackett:9117/dl/****

Regards
