### ISSUE TITLE
[REQ]torrenthane.com

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#7853]
Turkish public movie torrent site.
https://torrenthane.com
Seach engine is running.

**Comment by garfield69** [comment]
Jackett 0.14.297

**Comment by garfield69** [comment]
https://torrenthane.com/ returning
![image](https://user-images.githubusercontent.com/6933240/86326415-c6391480-bc95-11ea-928c-0750e037b2b9.png)

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://torrenthane.com/
![th](https://user-images.githubusercontent.com/59480337/86515723-02de4a80-be13-11ea-9900-8f6ef4def3cb.png)

**Comment by ilike2burnthing** [comment]
> https://torrenthane.com/ returning
> ![image](https://user-images.githubusercontent.com/6933240/86326415-c6391480-bc95-11ea-928c-0750e037b2b9.png)

back to this

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
the site has switched to a one title many torrents and so the yml indexer will be removed.
a c# indexer for this site will need to be written by a volunteer.

**Comment by garfield69** [comment]
https://torrenthane.com/ returns ERR_CONNECTION_TIMED_OUT
