### ISSUE TITLE
[req] Falkon Vision Team private Croatian http://falkonvision-team.com/

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#7856]
Falkon Vision Team is a CROATIAN Private Torrent Tracker for MOVIES / TV / GENERAL

my registration is currently pending admin approval.
update (5 day later): no signs of an activation email, login rejected stating I should activate my account!
![image](https://user-images.githubusercontent.com/6933240/77953410-bb36b700-7329-11ea-83f7-38ec5599a96b.png)
but there does not appear to be any way to get the activation mail resent

**Comment by garfield69** [comment]
Registered afresh yesterday and got accepted.
https CA expired March 2018 so only http supported
engine: TS Special Edition v.7.4
MST: 60 hours

**Comment by garfield69** [comment]
v0.18.812

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
i am still getting ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
Ah, I'm getting a mix of it working fine, time outs, pages taking forever to load, and pages half loading

**Comment by ilike2burnthing** [comment]
back up for at least the past hour

**Comment by ilike2burnthing** [comment]
http://falkonvision-team.com/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
http://falkonvision-team.com/ - ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.21.2658
