### ISSUE TITLE
[torrentz2] Exception (torrentz2): The operation was canceled.: The operation was canceled. (Test)

### ISSUE THREAD

**Issue by nfrignani** [Jackett/Jackett#7858]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by nfrignani** [comment]
Environment
OS: docker unraid
Jackett Version: Jackett Version 0.14.164.0
Last Working Jackett Version:
Are you using a proxy or VPN? yes through a proxy

Description
pressing test button

Logged Error Messages
 An error occured while testing this indexer
Exception (torrentz2): The operation was canceled.: The operation was canceled.
Click here to open an issue on GitHub for this indexer.
[Make sure you attach the full logs with your personal information removed in case we need more information]

[log.txt](https://github.com/Jackett/Jackett/files/4385853/log.txt)

thanks

**Comment by garfield69** [comment]
TorrentZ2 have activated the Cloudflare Anti-DDoS ReChallenge.
1. upgrade to the latest Jackett 0.14.287
2. from your Jackett Dashboard, edit the TorrentZ2 config and try out any of the alternate site links, which may not have the Cloudflare challenge activated.

But be aware that these proxies are unofficial, may not work or may not provide the latest releases.
