### ISSUE TITLE
[xspeeds] Exception (xspeeds): String 'Pre Release Time: 25-03-2020 18:00  Uploaded: 13 Hours, 12 Minutes, 48 Seconds after Pre' was not recognized as a valid DateTime.: Parse error (Test)

### ISSUE THREAD

**Issue by Tsume** [Jackett/Jackett#7860]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Works for me on Windows 10 Jackett 0.14.287
if you want help diagnosis this then provide all the requested info (especially the jackett version) in the first post and especially the enhanced-log file so we can look at the web site's html to see what may be going on.
