### ISSUE TITLE
[torrentz2] Exception (torrentz2): Input string was not in a correct format.: Input string was not in a correct format. (Test)

### ISSUE THREAD

**Issue by elderwolf123** [Jackett/Jackett#7868]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

Windows 7

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

Yes

### Description
Was having sonarr problems and decided to check jackett

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
you should not be seeing this if you are on a version of Jackett of at least 0.13.529
the current latest version is 0.14.287 and the indexer is working for me on my win 10 Jackett 0.14.287

access your Jackett Dashboard and scroll to the bottom and confirm you are on the latest version.
If not, manually update your jackett from https://github.com/Jackett/Jackett/releases and if you are on a linux system be sure to refresh your systemd script by following https://github.com/Jackett/Jackett#install-as-service

if you have done the above and you still have this issue then please provide an enhanced log so we can look into this further. see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-turn-on-enhanced-logging

**Comment by elderwolf123** [comment]
im running the newest now, to fix it i had to delete the index and add it
back

**Comment by garfield69** [comment]
Thanks for the update. I'll update our notes on possible recovery steps.
