### ISSUE TITLE
-- Error with RSS FEED --

### ISSUE THREAD

**Issue by Eldoc62** [Jackett/Jackett#7869]
Jackett variant: CoreMacOs
OS version: Unix 18.7.0.0 (64bit OS) (64bit process)
Environment version: 3.1.3 (/Volumes/Mac/Jackett/)
Starting Jackett v0.14.287.0

### Description

Hi all,

I recover the RSS feed of a tracker without problem but I would like to use this feed to download with "transmissionbt" except I get this error in the logs and the download is not added:

In terminal : 
`transmission-remote 192.168.1.10:9090 --auth=xxx:xxx -a http://192.168.1.10:9117/dl/oxtorrent/?jackett_apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxx&path=Q2ZESjhESTg1Tk02NlR0S25ZSXZ2ZV9HY`
response:

`
[1] 8396
[2] 8397
root@xxx:~# Error: gotMetadataFromURL: http error 404: Not Found
`

### Logged Error Messages

`

2020-03-27 05:06:25 | Error | Error downloading oxtorrent
-- | -- | --

`

if i past a magnet link or a direct .torrent download it's OK ?

You think it's a PB with Jackett ?

**Comment by ngosang** [comment]
Is this happening with all torrent sites or just oxtorrent?
Could you do the same search in the same tracker and try to download the .torrent from the Jacket UI? Maybe the .torrent is not available in the website.

**Comment by Eldoc62** [comment]
If i past the direct link dl it's ok. But if i past the jackett link it's not ok. With all trackers ;)

**Comment by ngosang** [comment]
Well, this is working for me. If you can't download from the Jackett UI maybe you have a problem with the reverse proxy or something like that => https://github.com/Jackett/Jackett#running-jackett-behind-a-reverse-proxy

**Comment by cadatoiva** [comment]
This likely has to do with the fact that a number of trackers have download links on a details page, so the download link Jackett provides results in a 302 redirect to the actual .torrent download. A lot of clients aren't equipped to handle this redirection

**Comment by ngosang** [comment]
May be related  #5875

**Comment by Eldoc62** [comment]
I'm using Jackett on OSX.

Via the terminal, if I use the wget command. I also get 404.

Example, a link works from SAFARI. In the bar I paste it, opens the popup of choice of destination of folder of the .torrent links, so ok

If I do this

wget http://192.168.1.53:9117/dl/oxtorrent/?jackett_apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&path=Q2ZESjhMUFpZU05VMHd0Sm9JS1pQU3Qwa1BVeHhMc2syZGZPeGRZd3J6dzZxOWFXcmVGb2dRYU5NTjdEV2N3elB3WGFtOUhfNklNRUpXZHNoUzd4QWxBckZZZzFhdE1KYzgzdVFzX3l2d0dEblBrNzdoRWZqT2I0VkxCYi1LQ19XMFBpbGRfWTlFcklWZi1sWjdrNy1qSXFRVWw5Y3pCM2V0VWgwQ0hmNzkydG9NcWhub0x5ejBfM05LUC1fdWhqdUJFYzlhY1hIWEJHbHk1MEg0aWxxdHdEUFJydkIzNHU2T0ZCVklOeHctbDVfTnVlY2NKaWtRdF9RMkZrc1BuN2l0dFNHY05YQlpQRkgxM0tGNnU5TTVSNE4zTQ&file=BBFL -O /Volumes/HDD_4/Torrents/

So I get this:
--2020-04-12 05:35:23--  http://192.168.1.53:9117/dl/oxtorrent/?jackett_apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Connexion à 192.168.1.53:9117… connecté.
requête HTTP transmise, en attente de la réponse… 404 Not Found
2020-04-12 05:35:23 erreur 404 : Not Found.

**Comment by garfield69** [comment]
possibly fixed with Jackett 0.15.36

**Comment by Eldoc62** [comment]
I do update now ;)

but result : 

--2020-04-14 07:58:52--  http://192.168.1.53:9117/dl/oxtorrent/?jackett_apikey=xxxxxxxxxxxxxxxxxxxxxx
Connexion à 192.168.1.53:9117… connecté.
requête HTTP transmise, en attente de la réponse… 404 Not Found
2020-04-14 07:58:52 erreur 404 : Not Found.

**Comment by Eldoc62** [comment]
Hi, i test now in Jackett Version 0.16.18.0 but i's the same ;)

**Comment by garfield69** [comment]
FYI
unless we post specifically to let you know that a particular release will include a fix, then assume that any new releases will not correct this problem, they were releases to fix other issues.

**Comment by ngosang** [comment]
This can't be fixed but I let you some tips.
1. oxtorrent provides magnet links so you won't be able to download a .torrent file using wget.
2. The 404 means you are copying wrong the URL or you are not escaping the ÙRL. you have to put simple quotes around the URl. `wget 'http......'`
3. The response in wget should be something like this.
```
HTTP request sent, awaiting response... 302 Found
Location: magnet:?xt=urn:btih:UZM5CONCYZFHRDZ6VFIZ5FFHIJUF7FKQ&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://open.stealth.si:80/announce&tr=http://tracker3.itzmx.com:8080/announce: Unsupported scheme ‘magnet’.
```
As you see the response is a magnet, you should write bash script or something if you want to send it to the bittorrent client.

4. Some bittorrent clients like qBittorrent works well with the Jackett URL, it's able to handle this magnet redirects.
