### ISSUE TITLE
Improving search functionality on HD-Only

### ISSUE THREAD

**Issue by SuissoNaBisso9** [Jackett/Jackett#7879]
### Description

Hi, is there any way to improve the search funtionality on HD-Only.org please ?
As this tracker CMS is grouping all releases of a single movies under the same page, the release name appeared as modified versus the torrent name into jackett and radarr. And because of that this not matching Radarr Custom Formats very sueful in the case of French releases. E.i to differenciate releases in french from France vs french from Canada, many of us are using Custom Formats to search for "truefrench" in the torrent name. And currently Radarr can't find this on this tracker because Jackett is not pulling the torrent name itself but just what seems to be the movie title harmonized for all releases.

here is a concrete example with "The 4 fantastics" : 
Radarr find this as a name (for 1080p remux) : Les 4 Fantastiques [2015] [Film] AVC / 1080p / Blu-Ray Remux
While the exact same release on the tracker is announced with important tags like "VFF" (equivalent of truefrench) : https://ibb.co/BPPSLzK

Is there anyway to improve this please ?
FYI there is a similar French tracker using this CMS and announcing / organising releases the same way and works perfectly with Jackett, this is HD-Forever.

Thank you !

**Comment by RoloSoze** [comment]
@SuissoNaBisso9 None of the current developers is a member of HD-Only. Would you be able to send an invite to one of them? Or alternatively, is HD-Only recuriting anywhere?

**Comment by SuissoNaBisso9** [comment]
> @SuissoNaBisso9 None of the current developers is a member of HD-Only. Would you be able to send an invite to one of them? Or alternatively, is HD-Only recuriting anywhere?

Don't have any invite personnaly and tracker is only recruiting on KKT as I'm aware. Let me check with the staff if there is anything they can do ! Thanks

**Comment by RoloSoze** [comment]
> Let me check with the staff if there is anything they can do ! Thanks

Let us know!

**Comment by SuissoNaBisso9** [comment]
Hey, that's good the staff created an access for you, how can I share this with you ?

Thanks

**Comment by RoloSoze** [comment]
@ngosang @cadatoiva Is one of you guys willing to take this?

**Comment by ngosang** [comment]
You can send the invites to these emails, but I don't know when I will have time.

ngosang -at- hotmail.es

cadatoiva -at- yahoo.com

**Comment by cadatoiva** [comment]
I've got a growing backlog of trackers I'm trying to update, but the second email in @ngosang's post is mine.

**Comment by RoloSoze** [comment]
> 
> 
> Hey, that's good the staff created an access for you, how can I share this with you ?
> 
> Thanks

You've got two emails! Let us know once you've sent the invites! Thanks! :)

**Comment by SuissoNaBisso9** [comment]
Email with ligin details sent :)
Thanks for your time guys, really appreciate !

**Comment by SuissoNaBisso9** [comment]
hi guys, tracker wad down for few days last week but went back to normal about 3/4 days ago, did you have any time to check it by chance ?
Thanks

**Comment by RoloSoze** [comment]
@ngosang @cadatoiva This is on your to-do list, guys. Right?

**Comment by SuissoNaBisso9** [comment]
hi guys, any news on this ?

**Comment by ngosang** [comment]
I have the login details but I don't have time to work in this at this time. Sorry.

**Comment by RoloSoze** [comment]
@ngosang I'll assign you to this ticket since you're the one who has access to this tracker. Whenever you have the chance to work on it, that'll be great. Thanks!

**Comment by ngosang** [comment]
The information you are requesting is not available in the API => `VO / stFR / VFF`
They will have to change their API to add support.

Example API response:
```json
{
  "groupId": 4321,
  "groupName": "Les 4 Fantastiques",
  "artist": "",
  "cover": "http://fr.web.img5.acsta.net/pictures/15/07/10/12/04/290362.jpg",
  "tags": [
    ""
  ],
  "bookmarked": false,
  "vanityHouse": false,
  "groupYear": 2015,
  "releaseType": "Film",
  "groupTime": "1541105305",
  "maxSize": 38025587763,
  "totalSnatched": 258,
  "totalSeeders": 4,
  "totalLeechers": 1,
  "torrents": [
    {
      "torrentId": 7524,
      "editionId": 1,
      "artists": [],
      "remastered": false,
      "remasterYear": 0,
      "remasterCatalogueNumber": "",
      "remasterTitle": "",
      "media": "Blu-Ray Remux",
      "encoding": "1080p",
      "format": "AVC",
      "hasLog": false,
      "logScore": 0,
      "hasCue": false,
      "scene": false,
      "vanityHouse": false,
      "fileCount": 1,
      "time": "2015-12-03 09:36:49",
      "size": 26754331400,
      "snatches": 79,
      "seeders": 1,
      "leechers": 1,
      "isFreeleech": false,
      "isNeutralLeech": false,
      "isPersonalFreeleech": false,
      "canUseToken": false,
      "hasSnatched": false
    },
    {
      "torrentId": 19525,
      "editionId": 2,
      "artists": [],
      "remastered": false,
      "remasterYear": 0,
      "remasterCatalogueNumber": "",
      "remasterTitle": "",
      "media": "Blu-Ray Remux 4K",
      "encoding": "2160p",
      "format": "HEVC",
      "hasLog": false,
      "logScore": 0,
      "hasCue": false,
      "scene": false,
      "vanityHouse": false,
      "fileCount": 1,
      "time": "2018-11-01 20:48:25",
      "size": 38025587763,
      "snatches": 13,
      "seeders": 1,
      "leechers": 0,
      "isFreeleech": false,
      "isNeutralLeech": false,
      "isPersonalFreeleech": false,
      "canUseToken": false,
      "hasSnatched": false
    },
    {
      "torrentId": 7262,
      "editionId": 3,
      "artists": [],
      "remastered": false,
      "remasterYear": 0,
      "remasterCatalogueNumber": "",
      "remasterTitle": "",
      "media": "Blu-Ray Rip",
      "encoding": "1080p",
      "format": "x264",
      "hasLog": false,
      "logScore": 0,
      "hasCue": false,
      "scene": false,
      "vanityHouse": false,
      "fileCount": 1,
      "time": "2015-11-23 15:06:47",
      "size": 13290158658,
      "snatches": 166,
      "seeders": 2,
      "leechers": 0,
      "isFreeleech": false,
      "isNeutralLeech": false,
      "isPersonalFreeleech": false,
      "canUseToken": false,
      "hasSnatched": false
    }
  ]
}
```

**Comment by SuissoNaBisso9** [comment]
> The information you are requesting is not available in the API => `VO / stFR / VFF`
> They will have to change their API to add support.
> 
> Example API response:
> 
> ```json
> {
>   "groupId": 4321,
>   "groupName": "Les 4 Fantastiques",
>   "artist": "",
>   "cover": "http://fr.web.img5.acsta.net/pictures/15/07/10/12/04/290362.jpg",
>   "tags": [
>     ""
>   ],
>   "bookmarked": false,
>   "vanityHouse": false,
>   "groupYear": 2015,
>   "releaseType": "Film",
>   "groupTime": "1541105305",
>   "maxSize": 38025587763,
>   "totalSnatched": 258,
>   "totalSeeders": 4,
>   "totalLeechers": 1,
>   "torrents": [
>     {
>       "torrentId": 7524,
>       "editionId": 1,
>       "artists": [],
>       "remastered": false,
>       "remasterYear": 0,
>       "remasterCatalogueNumber": "",
>       "remasterTitle": "",
>       "media": "Blu-Ray Remux",
>       "encoding": "1080p",
>       "format": "AVC",
>       "hasLog": false,
>       "logScore": 0,
>       "hasCue": false,
>       "scene": false,
>       "vanityHouse": false,
>       "fileCount": 1,
>       "time": "2015-12-03 09:36:49",
>       "size": 26754331400,
>       "snatches": 79,
>       "seeders": 1,
>       "leechers": 1,
>       "isFreeleech": false,
>       "isNeutralLeech": false,
>       "isPersonalFreeleech": false,
>       "canUseToken": false,
>       "hasSnatched": false
>     },
>     {
>       "torrentId": 19525,
>       "editionId": 2,
>       "artists": [],
>       "remastered": false,
>       "remasterYear": 0,
>       "remasterCatalogueNumber": "",
>       "remasterTitle": "",
>       "media": "Blu-Ray Remux 4K",
>       "encoding": "2160p",
>       "format": "HEVC",
>       "hasLog": false,
>       "logScore": 0,
>       "hasCue": false,
>       "scene": false,
>       "vanityHouse": false,
>       "fileCount": 1,
>       "time": "2018-11-01 20:48:25",
>       "size": 38025587763,
>       "snatches": 13,
>       "seeders": 1,
>       "leechers": 0,
>       "isFreeleech": false,
>       "isNeutralLeech": false,
>       "isPersonalFreeleech": false,
>       "canUseToken": false,
>       "hasSnatched": false
>     },
>     {
>       "torrentId": 7262,
>       "editionId": 3,
>       "artists": [],
>       "remastered": false,
>       "remasterYear": 0,
>       "remasterCatalogueNumber": "",
>       "remasterTitle": "",
>       "media": "Blu-Ray Rip",
>       "encoding": "1080p",
>       "format": "x264",
>       "hasLog": false,
>       "logScore": 0,
>       "hasCue": false,
>       "scene": false,
>       "vanityHouse": false,
>       "fileCount": 1,
>       "time": "2015-11-23 15:06:47",
>       "size": 13290158658,
>       "snatches": 166,
>       "seeders": 2,
>       "leechers": 0,
>       "isFreeleech": false,
>       "isNeutralLeech": false,
>       "isPersonalFreeleech": false,
>       "canUseToken": false,
>       "hasSnatched": false
>     }
>   ]
> }
> ```

Thanks for checking ! i'll the share the info with tracker's staff !

**Comment by ngosang** [comment]
any news?

**Comment by SuissoNaBisso9** [comment]
> any news?

Staff has been informed but unfortunately they don't have any dev to improve the API

**Comment by ngosang** [comment]
Site down => Problème d'accès à la base de données... réparations en cours.

**Comment by ilike2burnthing** [comment]
https://hd-only.org/
```
Nous ne sommes pas partis !
Le site et un de nos serveurs ont connu quelques soucis et nous travaillons dessus.
Il nous faut du temps mais nous sommes toujours la, pour vous, nous reviendrons :)
IRC est en ligne
Le Staff
```
```
We didn't leave!
The site and one of our servers have experienced some problems and we are working on it.
We need time but we are always here, for you, we will come back :)
IRC is online
The Staff
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by RoloSoze** [comment]
@ilike2burnthing Was this reopened due to the website being down? It doesn't seem to be down anymore.

**Comment by ilike2burnthing** [comment]
Oh, no idea why I reopened it, assuming it was by accident given the timestamps.
