### ISSUE TITLE
[galeriens] too too long to respond

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#7887]
https://galeriens.com/ currently returning 
```
This site can’t be reached
galeriens.com took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_TIMED_OUT
```

**Comment by ilike2burnthing** [comment]
I don't have an account, but the site itself loads for me.

**Comment by garfield69** [comment]
back online.

I am guessing, judging by the dozen sites I've tested today that have come up with either 522, 523 and err_time_out (temporarily as it now turns out), that the covid19 lock-down or stay-at-home rules most countries have implemented,  is causing worldwide increased loading on WAN servers, leading to these outages.

**Comment by garfield69** [comment]
https://galeriens.com/ returning This site can’t be reached
