### ISSUE TITLE
[torrentday] Your cookie did not work: Parse error (Config)

### ISSUE THREAD

**Issue by PureSp1r1t** [Jackett/Jackett#7889]
Howdy, I've tried enough times now to think there's something wrong here.

I can't add TorrentDay as an indexer, my cookie fails to parse every single time. I've tried 3 different browsers with the same result each time. I'm putting all the cookie information in, although each browser gives me a different selection of options. I'm not super great at all this, especially Git, but I'd really appreciate some help.

Edit: Sorry for the dupe, I thought I looked well enough!

**Comment by garfield69** [comment]
try out Jackett pre-release 0.14.302

**Comment by PureSp1r1t** [comment]
It was me who tested :) Thanks for taking the time to comment though.

**Comment by PureSp1r1t** [comment]
Bad bot
