### ISSUE TITLE
The Piratebay

### ISSUE THREAD

**Issue by joshuasm** [Jackett/Jackett#789]
ThePiratebay isn't in the listings a an available indexer

**Comment by savahu** [comment]
Because it's a public indexer.. Jackett is (as of this moment) only for private trackers.

**Comment by joshuasm** [comment]
will it be getting support again in future?

**Comment by kaso17** [comment]
The definition file from Cardigann can be used with Jackett.
Just place the yml file in Jackets Definition directory.
