### ISSUE TITLE
[REQ] Nipponsei

### ISSUE THREAD

**Issue by Noirvent** [Jackett/Jackett#7894]
I would like to suggest the add of a new Tracker: Nipponsei
It contains only anime opening/ending/OSTs

URL : https://nipponsei.minglong.org/tracker/
type: public, no need for registration

**Comment by garfield69** [comment]
its just music right?

**Comment by garfield69** [comment]
this site is not suitable for processing  by the cardigann processor.
it has two results page layouts, depending on whether or not you are searching with keywords

keyword-less search
![image](https://user-images.githubusercontent.com/6933240/77814388-75a1a080-7115-11ea-8801-38cd1dbdfdfb.png)

with html
```html
<tr class="odd">
	<td class="name">
		<a class="download" href="http://tracker.minglong.org/torrents/%5BNipponsei%5D%20Show%20By%20Rock!!%20Mashumairesh!!%20Original%20Soundtrack.zip.torrent">[Nipponsei] Show By Rock!! Mashumairesh!! Original Soundtrack.zip</a>
	</td>
	<td class="date">2020-03-21 13:50</td>
	<td class="bytes">224.59 MB</td>
	<td class="number_green">19</td>
	<td class="number_red">0</td>
	<td class="number">374</td>
	<td class="bytes">82.03 GB</td>
</tr>
<tr class="even">
	<td class="name">
		<a class="download" href="http://tracker.minglong.org/torrents/%5BNipponsei%5D%20Nekopara%20Original%20Soundtrack.zip.torrent">[Nipponsei] Nekopara Original Soundtrack.zip</a>
	</td>
	<td class="date">2020-03-21 13:50</td>
	<td class="bytes">156.34 MB</td>
	<td class="number_green">26</td>
	<td class="number_red">0</td>
	<td class="number">418</td>
	<td class="bytes">63.82 GB</td>
</tr>
```
keywords search
![image](https://user-images.githubusercontent.com/6933240/77814373-64f12a80-7115-11ea-9d6e-b35a2d7d93e7.png)
with html
```html
<tr class="odd">
	<td>
		<a href="http://tracker.minglong.org/torrents/%5BNipponsei%5D%20BLEACH%20ED15%20Single%20-%20Orange%20%5BLil%27B%5D.zip.torrent">[Nipponsei] BLEACH ED15 Single - Orange [Lil'B].zip</a>
	</td>
	<td class="number_yellow">2</td>
	<td class="number_red">0</td>
	<td class="number">15330</td>
</tr>
<tr class="even">
	<td>
		<a href="http://tracker.minglong.org/torrents/%5BNipponsei%5D%20Bleach%20OP%20Single%20-%20Asterisk%20%5BOrange%20Range%5D.zip.torrent">[Nipponsei] Bleach OP Single - Asterisk [Orange Range].zip</a>
	</td>
	<td class="number_yellow">2</td>
	<td class="number_red">0</td>
	<td class="number">10730</td>
</tr>
```
There is no way for Cardigann to choose which selectors to use for fields because the HTML behind the scenes is so different between layouts.

This indexer will therefore need to be coded in c#

**Comment by garfield69** [comment]
I've updated the cardigann processor to allow variable substitution in the search block selector statements
this will allow us to choose which field we want to select depending on whether keywords were used in the search or not.
so now we can do:
```yaml
    seeders:
      selector: "{{ if .Keywords }}td:nth-child(2){{ else }}td:nth-child(4){{ end }}"
    leechers:
      selector: "{{ if .Keywords }}td:nth-child(3){{ else }}td:nth-child(5){{ end }}"
```

**Comment by garfield69** [comment]
v0.18.896

**Comment by garfield69** [comment]
https://nipponsei.minglong.org/ > cloudflare  Bad gateway Error code 502  or 504 Gateway Timeout or Http Timeout or TCP Connection Error

**Comment by ilike2burnthing** [comment]
back up
