### ISSUE TITLE
Unable to add TorrentLeech on QNAP

### ISSUE THREAD

**Issue by vonny3** [Jackett/Jackett#79]
Greetings,

I have installed Jackett on my QNAP device (http://forum.qnap.com/viewtopic.php?f=320&t=116660&p=518007#p518007) and am running 0.7.27.0 with Mono 4.0.4.1. I can add some trackers (Demonoid for example) but get "Configuration Failed:" when trying to setup TorrentLeech.

I am happy to gather logs to help resolve - unfortunately I am not sure where these are located. The "View Logs" option in the UI returns no errors and very little information in general. The log file in my user/.config/Jackett also has limited information:

"
LibCurl init Ok
LibCurl version libcurl/7.41.0 OpenSSL/1.0.2a zlib/1.2.8 libidn/1.29 libssh2/1.4.3
Starting web server at http://______
"

Any assistance would be greatly appreciated!

**Comment by WhatFox** [comment]
https://github.com/Jackett/Jackett#Troubleshooting

**Comment by vonny3** [comment]
Thanks for the reply. I had read through those notes, but I admit I wasn't sure where I was to specify the "--SSLFix true" flag. Could a newb trouble you all for some guidance?

**Comment by WhatFox** [comment]
mono JackettConsole.exe --SSLFix true

**Comment by vonny3** [comment]
I believe I need an update tweeked for the QNAP before I can update

**Comment by vonny3** [comment]
I am getting the following error when I try to add TorrentLeech now running Jackett 0.7.33:

"
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
UnixLibCurlWebClient:GetString Returning InternalServerError => 
UnixLibCurlWebClient: Posting username=----&password=------&remember_me=on&login=submit
UnixLibCurlWebClient:GetString(Url:https://www.torrentleech.org/user/account/login/)
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Configure()
"

**Comment by vonny3** [comment]
Looking at the logs from additional attempts - could this be caused by a special character in the password perhaps? Is there a way escape a character in the password entry? Torrentleech requires a special character in their password policy so I don't have a way to test without.

**Comment by vonny3** [comment]
Strike the last post - this was not at all related. I tested this with an install on my Windows workstation and was able to add it without issue. My best (newbish) guess is this is something to with Curl's configuration on the QNAP? Anyone have any thoughts on next steps by chance?

The error is consistently "UnixLibCurlWebClient:GetString Returning InternalServerError"

**Comment by flightlevel** [comment]
@vonny3 In Firefox can you click the padlock next to the address bar and report result to see if it is the same issue as https://github.com/Jackett/Jackett/issues/82#issuecomment-158703868

**Comment by vonny3** [comment]
Torrentleech's cert indeed reports that "This website does not supply ownership information."

**Comment by vonny3** [comment]
I am running Mono 4.2.1.0 and Curl 7.45 at this point if it is important to the troubleshooting/suggestions.

**Comment by flightlevel** [comment]
The latest release should fix this issue.

**Comment by vonny3** [comment]
Confirmed - latest release packaged for QNAP with flag set resolved this issue.

Thanks all!
