### ISSUE TITLE
Downloads wrong movie.

### ISSUE THREAD

**Issue by TheMonDon** [Jackett/Jackett#790]
I put "Trolls (2016)" Into CouchPotato, and Jackett went and searched and downloaded "The Boxtrolls (2014)" This isn't right.

**Comment by kaso17** [comment]
please provide the jackett log showing the search request

**Comment by armani316** [comment]
@TheMonDon Are you able to provide an enhanced Jackett log? That would be very helpful to analyze this issue if it's still happening.

**Comment by raspdealer** [comment]
Hi @TheMonDon 

I have frenquently this issue and for me, it's a CouchPotato issue.
It seems to track "include" strings and never check the year.

Look at your film, it contains "Trolls" in the name.
Recently I add this issue with the film "Sing" you can't imagine how many film contains "sing" in their title...
(Rising, ...)

**Comment by kaso17** [comment]
dupe #736
