### ISSUE TITLE
[torrentday] Exception (torrentday): The best overloaded method match for 'Jackett.Common.Models.TorznabQuery.MatchQueryStringAND(string, int?, string)' has some invalid arguments: Parse error (Test)

### ISSUE THREAD

**Issue by cyrixdx4** [Jackett/Jackett#7900]
### Environment

**OS**: Linux (Docker container)

**Jackett Version**: Jackett Version 0.14.299.0

**Last Working Jackett Version**: Unknown, first time this error occured

**Are you using a proxy or VPN?** [yes/no] No

### Description

Saw an error on Sonarr, went back to Jackett found this error. Tested, error acknowledged

### Logged Error Messages

An error occured while testing this indexer
Exception (torrentday): The best overloaded method match for 'Jackett.Common.Models.TorznabQuery.MatchQueryStringAND(string, int?, string)' has some invalid arguments: Parse error

Snippet from Log:
2020-03-28 10:26:45,063 DEBG 'jackett' stdout output:
03-28 10:26:45 Error Error on 20200328102645 for TorrentDay.txtMicrosoft.CSharp.RuntimeBinder.RuntimeBinderException: The best overloaded method match for 'Jackett.Common.Models.TorznabQuery.MatchQueryStringAND(string, int?, string)' has some invalid arguments

**Comment by garfield69** [comment]
upgrade to the latest Jackett 0.14.303
