### ISSUE TITLE
[yggcookie] Login Failed, got redirected. Try changing the indexer URL to http://www2.yggtorrent.se/. Updated site link, please try again. (Config)

### ISSUE THREAD

**Issue by SkYNewZ** [Jackett/Jackett#7904]
yggcookie stop working. When I am trying to reconfigure, I have got this error message

```
Login Failed, got redirected. Try changing the indexer URL to http://www2.yggtorrent.se/. Updated site link, please try again.
```

<img width="660" alt="image" src="https://user-images.githubusercontent.com/26750012/77828012-76d4cc80-7119-11ea-89cb-757a89b9a7b3.png">

**Comment by garfield69** [comment]
login to the yggtorrent site to confirm that
- your credentials are good
- you have a good ratio
- you do not have any outstanding alerts, notices or unread PM
- you have not been suspended, deleted, frozen, blasted, nuked, you get the picture.

grab a fresh cookie from that session then 
- edit your yggcookie config and 
- change your site link to https://yggtorrent.se/
- refresh/replace the cookie
- click okay.

if it fails, repeat, it should save the second time

report back success or failure.

**Comment by SkYNewZ** [comment]
Effectively, my account was suspended due to a bad ratio. I increase it and setup site link with the one you provided to me.

All works again,
Thanks !!
