### ISSUE TITLE
The response ended prematurely.: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by callahan22** [Jackett/Jackett#7905]
**Description of problem**
Jackett has been working flawlessly for about a year. Suddenly, none of my indexers work. The log files are full of the following err for each indexer when I try to test them. This is the same for all indexers.

```
Jackett.Common.IndexerException: Exception (rarbg): The response ended prematurely.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 458
   at Jackett.Common.Indexers.Rarbg.CheckToken() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Rarbg.cs:line 134
   at Jackett.Common.Indexers.Rarbg.PerformQuery(TorznabQuery query, Int32 attempts) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Rarbg.cs:line 157
   at Jackett.Common.Indexers.Rarbg.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Rarbg.cs:line 152
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 804
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 370
```
Nothing has changed on the docker stack other than Watchtower keeping the containers up to date and the normal security updates for the Ubuntu 18.04 server.

I get the same error whether I use a SOCKS5 proxy or not.
I've exec'd into the container, installed ping and I can ping external servers so the routing is not the issue. I'm kind of stumped as the logs give very little to go on.

**Environment**
Ubuntu 18.04
Docker stack running:
- nextcloud
- phpmyadmin
- transmission-vpn
- sonarr
- mariadb
- radarr
- ombi
- tautulli
- portainer
- jackett
- watchtower
- pihole

- 2.5GB RAM on on server shared between the containers.

**Jackett Version**:
Version 0.14.303.0

Is anyone else seeing the same issues or have any suggestions as to what the cause is?

Thanks.

**Comment by garfield69** [comment]
My first reaction is that some external issue is interfering with Jackett getting a complete response from the sites the indexers are trying to fetch results from.
So Lets see if the enhanced log can provide a little more detail to events just prior to the final error message you are reporting.

https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by callahan22** [comment]
Hi Garfield,

I thought the same but none of my other containers on the same host have this issue.
I'd already switched on the advanced logging but was expecting to see it in the Web console log reporter. So, I've chopped down the logs to make them readable/bearable and attached them rather than pollute this post.
2 files, one (rarbg.log) shows the logs from when I try to add RARBG as an indexer to a clean docker deployment (the RARGB indexer just never shows up in Jackett when you try and add it).
The second file (EZTV.log) is a log file of what happens after I add the EZTV indexer to Jackett but when I then test that indexer it fails.

[rarbg.log](https://github.com/Jackett/Jackett/files/4397794/rarbg.log)
[EZTV.log](https://github.com/Jackett/Jackett/files/4397790/EZTV.log)

Does that help any? Please let me know if you need more info, happy to provide it.

Thanks again for your help.

**Comment by garfield69** [comment]
Adding public indexers to jackett always appear to succeed since there is no need for Jackett to do a test of login credentials. Its not until you try to do a search that you discover the issue.
Semi-Private and Private indexers a different, as before you can add them you first need to fill in credentials and therefore you discover much earlier something is not working.

As you say, little in the logs that is helpful.
Lets see if we can determine if this is a Jackett issue or a docker container issue.

- Start a terminal and connect to your jackett docker `docker exec -it jackett /bin/bash` (replace jackett with whatever you called your Jackett container).
- then post the output of `curl -vvv https://eztv.io/search/crimewatch`

**Comment by callahan22** [comment]
Yep, that works. I'd already tired this (without having a good link to test it with so thank you for that!). That returns the full webpage as you'd expect. When I tested this before and could ping and curl normal websites, I asumed the container was fine. That pushed me back to asuming the host was at fault but all my other containers on the same host work and can access the the web. The same host can also get to the webpage: https://eztv.io/search/crimewatch via curl.

It's really odd. Nothing stands out as being the obvious reason I can't connect. I've even wiped out the host jackett folder/files and binned the container. Rebuilt from nothing but with the same result.

**Comment by garfield69** [comment]
@ngosang  @cadatoiva  @junglebus  Anyone have thoughts on what might be going on here?

**Comment by callahan22** [comment]
Abort! I've found the issue! I can't tell you why it stopped working in the first place after nearly a year of service but the solution was to bin the radarr folder on the host that I was bind mapping the container to and let it create itself on creation of the container. That's kind of a kick in the teeth as it now seems the most obvious thing I should have tried. Never mind, hopefully this chain serves to help others that might come accross this.

@garfield69  - Thank you very much for persisting with the problem/me!

**Comment by cadatoiva** [comment]
Proxy use is currently considered unstable within Jackett, with several strange issues that have seemingly no rhyme or reason. We're working on a major overhaul of the entire sub-system and keeping an eye on these issues while we test and improve.
