### ISSUE TITLE
[ettv] CardigannIndexer (ettv): Download selector a[href^="{{ .Config.downloadlink }}"] didn't match

### ISSUE THREAD

**Issue by kevinpascoe** [Jackett/Jackett#7922]
### Environment

**OS**: Raspberry Pi

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono 6.6.0.161

**Jackett Version**: 0.14.326.0

**Last Working Jackett Version**: Not sure

**Are you using a proxy or VPN?** [yes/no] yes (Private Internet Access)

### Description

Downloading anything from ettv results in the error in subject. Possible change in their html source?

### Logged Error Messages

CardigannIndexer (ettv): Download selector a[href^="{{ .Config.downloadlink }}"] didn't match:

**Comment by kevinpascoe** [comment]
Not sure if it helps, but the magnet links now have this html

<a href="magnet:?xt=<link>" class="download_link magnet">Download Torrent (Magnet)</a>

**Comment by ngosang** [comment]
Please, share with us the search term.

**Comment by kevinpascoe** [comment]
http://192.168.2.79:9117/dl/ettv/?jackett_apikey=h3qmmwqhxrob9nhh4rhob5obieq01ado&path=Q2ZESjhLZWxta1ZIQXZKQ2h0S2phVUlZRnA0ZVVIdThIRFlCU1R6VGdPRmY2bUdUamVZUU4zRFRPREE3UzU1eEkyYWExV0tpSE9pWjB0RkxwaFNINTNaTmhOUW92NTdHQmJiYUF1LTd5TkppU2xtN1I0UW1FMWN0U0RBWUF3R3A5Uy1yX3pmT0p2UTAxb0pNeHk5QnZWeUpkdmk5cUJUbkk3Y1UwQ19WVVFsY05KS3N0ZFBRQWZKcWoyc0I2TGFyNl9MOGhFemNSd1N5Tm1JUWdCTHZ0R3Njd25HbTlzM2ZVaV9BZ0pZNnhNVkxpTUhhZXg3MExEdGViam83SDhBczhxVWNoQQ&file=Emergence.S01E13.Killshot.Pt.2.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb%5Beztv%5D.mkv

Is this what you mean by search term?

**Comment by ngosang** [comment]
yes, someone will take care soon.

**Comment by ilike2burnthing** [comment]
@kevinpascoe if you click the configuration (spanner) icon for ETTV in Jackett, under `Download link` do you have magnet or eTorrent.click selected?

ETTV's site appears to be having issues at the moment, but when I eventually got it to work in Jackett it downloaded magnet links fine using that search and others. However, eTorrent.click fails every time, giving that error. Looking at their site, I only see magnet links available, so I think that option may need to be removed.

**Comment by garfield69** [comment]
ETTV have switching to providing magnet only.
I will amend the indexer to drop the .torrent support since this is now obsolete.

**Comment by kevinpascoe** [comment]
Thank you. I can confirm that changing it to magnet solves the problem

**Comment by garfield69** [comment]
Jackett 0.14.358

**Comment by garfield69** [comment]
regarding ettv and the change to use only magnets, you may find this article in TorrentFreak enlightening
https://torrentfreak.com/ettv-moves-to-new-domain-name-after-operator-goes-missing-200104/

**Comment by ilike2burnthing** [comment]
Oh damn :-/
