### ISSUE TITLE
[Anthelion] Add IMDb ID Search | Display 'Remux' Tag | Show Full Filename

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7923]
Anthelion requires the following improvements:

- [x] IMDb ID search capability needs to be added, which is already mentioned in #4859. 

- [x] The IMDb URL appears on the movie's homepage but not next to each individual torrent. If it can be displayed in Jackett, that would be ideal.

- [x] Jackett displays the tags of each release (e.g.  x264 / MKV / Blu-ray / 1080p / DTS) but omits the `Remux` tag for some reason. It replaces 'Remux' with the video codec - H.264 for 1080p & H.265 for 2160p. While displaying the video codec is fine, Jackett also needs to show `Remux`.

- [ ] In addition to displaying tags, Jackett also needs to display the full release/filename - e.g. `Avengers.Endgame.2019.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.REMUX-FraMeSToR`. The filename needs to appear first, followed by all the relevant tags mentioned in the second point above, preferably between square brackets [ ]. This approach should be very similar to how PTP displays tags and filenames - see https://github.com/Jackett/Jackett/issues/6783#issuecomment-599278807 - Start reading from where it says, "The best implementation example I've seen in Jackett." So in the above example, the Jackett search result should look like the following:
`Avengers.Endgame.2019.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.REMUX-FraMeSToR [H265 / MKV / Blu-ray / 2160p / Remux / True-HD / Subs]` [Cannot be done through the API or HTML scraping]

**Comment by RoloSoze** [comment]
@cadatoiva Would you be able to take a look at this? Whenever you get the chance; nothing urgent here.

**Comment by cadatoiva** [comment]
Yup, it's in my saved queue.

**Comment by RoloSoze** [comment]
@cadatoiva Still on your radar?

**Comment by cadatoiva** [comment]
Yeah, it is. Unfortunately, it's not a straight forward fix. They use the Gazelle tracker abstract, which makes a lot of assumptions which don't seem to be true for anthelion.

**Comment by cadatoiva** [comment]
I think I'll need to cleanup Gazelle as an abstract in general to continue. To do that, I need access to several existing Gazelle indexers to make sure I don't break anything. That list is:

* AlphaRatio
* Anthelion
* BrokenStones
* cgpeers
* HDOnly
* Notwhatcd
* Orpheus
* psytorrents
* redacted
* SecretCinema

I only have anthelion right now

**Comment by RoloSoze** [comment]
@cadatoiva I could be wrong but I think there are more Gazelle trackers. Are you saying this list comprises only the ones that will be affected by your changes?

Also, unfortunately I don't have any invites to the ones of which I'm a member, so I'm not sure how to proceed from here.  Getting access to all of these to test things isn't going to be easy.

**Comment by garfield69** [comment]
I can provide temp access to alpharatio
no one on the team has accounts in brokenstones, hd-only, pstorrents, secret-cinema
RoloSoze has an a/c on cgpeers, nowhat.cd, orpheus
ngosang has an a/c on redacted

**Comment by cadatoiva** [comment]
> cadatoiva I could be wrong but I think there are more Gazelle trackers. Are you saying this list comprises only the ones that will be affected by your changes?

@RoloSoze This list is all the current C# trackers that utilize the "template" (similar to Cardigann) for Gazelle. So these would be the only ones affected by updating the template code. If there are other C# trackers that also use the Gazelle backend, it would be a good idea to list them in (a/this) ticket to get rolled into the template during this change. Cutting down on code repeated for no good reason is always a good thing.

> Also, unfortunately I don't have any invites to the ones of which I'm a member, so I'm not sure how to proceed from here. Getting access to all of these to test things isn't going to be easy.

I probably won't need access to all of them, but I will need access to more than just the single one I do have access to (anthelion), especially since the Gazelle template code is heavily commented to suggest that there's a lot of code specific to this tracker buried into the functionality. The more, the better, but even just having access to 2-4 will exponentially increase the odds of not breaking things for all of them.

**Comment by cadatoiva** [comment]
temp access to the 5 we do have access to as listed by @garfield69 should be enough to update it without breaking the last 4. But I won't be able to get to this until later in the week anyway, so we can coordinate some kind of access later.

**Comment by RoloSoze** [comment]
I am willing to test changes when you make them. I very much prefer that over temporary access. Let me know if that's possible.

**Comment by RoloSoze** [comment]
> If there are other C# trackers that also use the Gazelle backend, it would be a good idea to list them in (a/this) ticket to get rolled into the template during this change.

I could be wrong, but I think 32Pages, GazelleGames, GFXPeers, Nebulance, UHDBits, MoreThanTV, and TV-Vault are all Gazelle-based.

Others like PTP, AHD, BTN use are also Gazelle, I think, but they all have their own API so I don't think your changes will affect any of them

Here's a list from Reddit, albeit a dated one:
[https://www.reddit.com/r/trackers/comments/bm1bx/comprehensive_list_of_gazelle_based_trackers_with/](url)

**Comment by cadatoiva** [comment]
Yeah, it should be fine with my anthelion, garfield's alpharatio, and ngosang's redacted, and if they are gazelle based (so I can add them into this remake) my Nebulance, MoreThanTV, and PTP should be a large enough sample size to make the changes. And with your testing on the other three, that should be enough to make sure nothing broke in the process.

**Comment by RoloSoze** [comment]
Sounds good. Just don't change MTV since we're putting things on hold for that tracker. Details were in an email I sent a while back.

**Comment by RoloSoze** [comment]
This question might be a little generic but it's related to this ticket: Trackers that are Luminance-based, do they require a C# or YAML indexer?

**Comment by garfield69** [comment]
so far I've 4 luminance indexers written in yml and none in c#

**Comment by RoloSoze** [comment]
@cadatoiva @garfield69 FYI GFXPeers has open signups right now:
https://gfxpeers.net/register.php

**Comment by RoloSoze** [comment]
#8508

**Comment by cadatoiva** [comment]
@RoloSoze missed the signup apparently. Was unavailable to check Github the past few days.

**Comment by RoloSoze** [comment]
@cadatoiva The changes that will be made here, how much are they likely to impact the changes needed to resolve #8508?

**Comment by RoloSoze** [comment]
@ngosang Is cadatovia not around anymore?

**Comment by ngosang** [comment]
He hasn't said goodbye, I guess at some point he'll be back.

**Comment by garfield69** [comment]
@ngosang  if you are interested in taking over work on this let me know.

**Comment by just-an-alt** [comment]
If any of you are on Orpheus, there's an invite thread for Nebulance, and Nebulance allows you to join Anthelion after 7 days.

**Comment by RoloSoze** [comment]
@ngosang Sent you an email about this.

**Comment by ngosang** [comment]
Bad news. None of the requested features can be implemented in Jackett without changes in the Anthelion API.

1) IMDB search is working in the web page but not in the GazelleAPI (ajax.php)
2) IMDB id is not available in the API response
3) Remux tag is not available in API response. We are not removing it.
4. Full release name is not availabe in the API response. We don't have enough information to build the full name. eg, the release group is not available.

**Comment by RoloSoze** [comment]
My understanding was that these issues can be solved but changes need to be made to the Gazelle abstract for it to work. That's what @cadatoiva said here https://github.com/Jackett/Jackett/issues/7923#issuecomment-619615642

I hope @cadatoiva can spare a couple of minutes to share his thoughts on this issue.

@ngosang If nothing can be done, would it be a good idea to use HTML scraping instead?

**Comment by ngosang** [comment]
> My understanding was that these issues can be solved but changes need to be made to the Gazelle abstract for it to work.

I think he saw that in the website you can use the "searchstr" parameter to search by imdb. That requires a small change in the Gazelle abstract (that I already did and doesn't work). If he had continued with the investigations he would have concluded that this parameter does not work in the API.

> If nothing can be done, would it be a good idea to use HTML scraping instead?

This will fix 1) 2) and 3)
Point 4) can't be fixed because the release name is only available in the torrent description.

**Comment by RoloSoze** [comment]
> This will fix 1) 2) and 3)
> Point 4) can't be fixed because the release name is only available in the torrent description.

If you think it's a good idea to do that, go ahead & do it, please. 3 is better than nothing.

**Comment by ngosang** [comment]
2) and 3) fixed in #9023
1) can be fixed too but it requires some work. let this open, maybe someday I will be in the mood.

**Comment by RoloSoze** [comment]
@ngosang Thank you. You've already done so much over the past few months.
 
Point number 1 above is the very last issue I have right now for which something can be done, and also the penultimate IMDb ID search that needs to be completed from the list in #4859. 

I'll leave this ticket open, and hopefully you can work on it soon! Thanks again!

**Comment by RoloSoze** [comment]
@ngosang Any updates on point number 1?

**Comment by ngosang** [comment]
No sorry. It's not in my backlog, there are more important issues in Jackett.

**Comment by RoloSoze** [comment]
@ngosang Is this now in your backlog by any chance :)

**Comment by ngosang** [comment]
Not yet, it requires a lot of work :(

**Comment by kzmgd** [comment]
Hello there! I'm a dev at Anthelion, and we're in the process of implementing a direct torznab-based API search. Happy to discuss if it would make sense to update the entire indexer class to use it in the future, but in the meantime, I've also implemented imdb and tmdb search parameters on the main search page. They're not documented / used on-site (yet), but the params are just `imdb` and `tmdb` and they take numbers (in the case of `imdb` it accepts either a number or the `tt####` string). This will result in a standard search response as opposed to the "details" page you get when querying for an imdb string directly.

I'd make a PR, but my C# skills are a few years rusty and it might be more trouble than it's worth!

**Comment by ngosang** [comment]
@kzmgd thank you. imdb and tmdb search already implemented in  #13195
When you have the Torznab API ready let us know, we will refactor the code to use the API instead of scrapping the HTML.

**Comment by kzmgd** [comment]
Thanks! It's actually in production now, though I have zero experience with it, and am calling for others on-site to help test it out, so it's a bit beta. I tried as best as I could to follow spec, and have it working with Radarr and Prowlarr, but am certainly amenable to fixing it up if something is amiss. I've implemented the t=caps method with standard categories as well as site categories, and search results seem to be working as best I can understand them. I'm not 100% sure what the title format needs to be; I tried to reverse-engineer what Radarr was expecting, but I might've gone overboard with the brackets.

Do you have/need an account there to test it out?

**Comment by ngosang** [comment]
I have an account. Could you post some information? Links, parameters, documentation...

**Comment by kzmgd** [comment]
It's just a forum thread right now; if it works for people, I'll add it to the API wiki.

https://anthelion.me/forums.php?action=viewthread&threadid=1026 

As for torznab attributes I'm returning right now:
* imdb
* year
* seeders
* leechers
* peers
* grabs
* infohash
* minimumratio (though we don't really enforce this yet, so for now it's always set to 1)
* minimumseedtime (ditto, at 259200)

But happy to add more if they'd be useful.

I can also enumerate the containers / codecs / audioformats / other tags that right now are just coming in as [] in the title, but if there's a more standardized list, I'd be happier to map to it and/or return them as discrete elements.

**Comment by ilike2burnthing** [comment]
Related? https://github.com/Jackett/Jackett/pull/13126

**Comment by garfield69** [comment]
v0.20.959 anthelion: implement imdb and tmdb search.

**Comment by RoloSoze** [comment]
@kzmgd With regards to the last point in my original post, when this was last checked by @ngosang, implementation was not possible. Is that still the case? I believe that displaying the full filename in Jackett is crucial. The PTP method of doing it is ideal as detailed above.

@ngosang With regards to my third point in the original post, the word 'REMUX' still does not appear in Jacket's search results. Other relevant tags such as HDR10 & Atmos are also missing. Can this be fixed?

**Comment by RoloSoze** [comment]
@twizt3dkitty I believe @ngosang has an account there; not sure if he still has it. Hopefully he can respond when he sees this.

**Comment by ngosang** [comment]
@garfield69 @ilike2burnthing I think we can implement the integration with the new API using Cardignann JSON instead of C#. Do you have an account? I can share mine if you want.

API DOC => https://anthelion.me/forums.php?action=viewthread&threadid=1026

**Comment by ilike2burnthing** [comment]
@garfield69 has an account

**Comment by garfield69** [comment]
v0.20.1649 Anthelion (API)

**Comment by garfield69** [comment]
all of the data available in the json response form the api is strung together into the title.
search for reincarnation shows that remux was available as part of the returned *Flags* field.

**Comment by garfield69** [comment]
**tags** in not a field in the json response.

**Comment by garfield69** [comment]
results from json for the previous search
```json
{"response":{"offset":"0","total":1},"item":[{"title":"The Reincarnation of Peter Proud","year":1975,"imdb":"tt0073615","tmdb":"101422","link":"https:\/\/anthelion.me\/api.php?action=download&amp;id=16384&amp;api_key=redacted","guid":"https:\/\/anthelion.me\/torrents.php?torrentid=16384","fileName":"The.Reincarnation.of.Peter.Proud.1975.1080p.Blu-ray.REMUX.MKV.16384.torrent","pubDate":"2022-08-04T02:09:49+0200","size":27909906942,"category":[2000,100001,2040,2050],"infohash":"73A301CD197740DD52EBDD5D413AB704C6D062EC","codec":"H264","container":"MKV","media":"Blu-ray","resolution":"1080p","audioFormat":"FLAC","subbing":true,"flags":["Commentary","Remux"],"releaseGroup":"aCant","seeders":1,"leechers":0,"peers":1,"grabs":0}]}
```

**Comment by RoloSoze** [comment]
@kzmgd Is it possible to update the API so that search results in Jackett return keywords such as Remux, Commentary, HDR10, Atmos, etc. Basically all the keywords shown on the website should ideally be displayed in Jackett as well.

**Comment by garfield69** [comment]
@RoloSoze  all those keywords are in the flags field.
show me a search where you see a discrepancy so I can see what you mean.

**Comment by RoloSoze** [comment]
Jackett:
![image](https://user-images.githubusercontent.com/23747425/183379305-72a31bf5-1357-4c38-bc4e-1c830e0506bd.png)

Anthelion: 
![image](https://user-images.githubusercontent.com/23747425/183379435-ce387bb2-50ef-4810-ae56-a48364aa7629.png)

I'm not entirely sure what you mean by the flags field, but if the aforementioned keywords don't appear in Jackett, users can't use the search field to filter out the search results using said keywords.

**Comment by garfield69** [comment]
you are using the anthelion indexer.
switch to the Anthelion (API) indexer ;-)

**Comment by RoloSoze** [comment]
> you are using the anthelion indexer. switch to the Anthelion (API) indexer ;-)

And that it precisely where I messed up!! All is good now! Thank you, @garfield69

**Comment by garfield69** [comment]
\o/

**Comment by garfield69** [comment]
@kzmgd could you add the files and tags to the api results at some point please.
non urgent request, just let me know if they become available here and I'll update the jackett anthelion-api indexer to use them. Thanks.

**Comment by kzmgd** [comment]
Hello there!

Sorry, I've been out for a month, but I just added these. Actually, my first stab at adding files used a function that included the sizes. I thought that might be helpful for some users, so I kept it, but if a flat array would be better, I can update it. Let me know if this works or if you'd like any tweaks!

Tags _should_ always be non-space, using `.` instead (like `sci.fi`) to match the display on-site; again - happy to tweak that if needed, too.

Example output for a torrent with multiple files:

```
...
"flags": [
    "HDR10"
],
"releaseGroup": "CMRG",
"tags": [
    "comedy",
    "adventure",
    "fantasy",
    "animation"
],
"files": [
    {
        "size": "10224540674",
        "name": "Minions.The.Rise.of.Gru.2022.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-CMRG.mkv"
    },
    {
        "size": "67",
        "name": "Minions.The.Rise.of.Gru.2022.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-CMRG.nfo"
    }
],
...
```

**Comment by garfield69** [comment]
Oh  sorry, by Files we usually mean a count of the files. Using the example you provided,
```json
...
"flags": [
    "HDR10"
],
"releaseGroup": "CMRG",
"tags": [
    "comedy",
    "adventure",
    "fantasy",
    "animation"
],
"files": "2",
...
```

**Comment by garfield69** [comment]
perhaps you would like to keep the existing files, and add a new keyword
```json
"filecount": "2",
```
?

**Comment by kzmgd** [comment]
Sure, I'm happy to do that. Unless you wanted to just do something like `item.files.length()`. The array will always be there in the JSON response, and everything has at least one file. But either way...

**Comment by garfield69** [comment]
I think, using your first example, the following would be in keeping (more or less) with other JSON API responses we process

```
...
"flags": [
    "HDR10"
],
"releaseGroup": "CMRG",
"tags": [
    "comedy",
    "adventure",
    "fantasy",
    "animation"
],
"fileCount: "2",
"files": [
    {
        "size": "10224540674",
        "name": "Minions.The.Rise.of.Gru.2022.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-CMRG.mkv"
    },
    {
        "size": "67",
        "name": "Minions.The.Rise.of.Gru.2022.2160p.AMZN.WEB-DL.DDP5.1.HDR.HEVC-CMRG.nfo"
    }
],
...
```
Thank you.

**Comment by kzmgd** [comment]
Added!

**Comment by garfield69** [comment]
Thank you!

**Comment by garfield69** [comment]
v0.20.2273
