### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://www2.yggtorrent.se/ using form selector 

### ISSUE THREAD

**Issue by imval** [Jackett/Jackett#7929]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Freenas 12.1

**.Net Runtime**: Mono

**.Net Version**:

**Jackett Version**: Version 0.14.299.0

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?** [yes/no] no

### Description

Can't get the Indexed ygg torrent to work.

### Logged Error Messages

Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www2.yggtorrent.se/ using form selector #user-login

**Comment by ilike2burnthing** [comment]
Change site link to https://yggtorrent.se/

**Comment by garfield69** [comment]
@imval  please read and implement https://github.com/Jackett/Jackett/issues/7095#issuecomment-582238746
if you continue to have an issue after that then read https://github.com/Jackett/Jackett/wiki/TroubleShooting#login-failed-no-form-found-on-url which should help on what to do next.
