### ISSUE TITLE
[REQ] ProFilm

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#7934]
Russian public movie sites.
~~http://filmplace.ru/~~ http://kinomuch.ru/

**Comment by garfield69** [comment]
This site has a one-title-many-torrents scheme which is unsuitable for processing by Cardigann which expects a one-title-one-torrent/magnet. 
this indexer will need to be written in c#

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
