### ISSUE TITLE
Unable to add YGGTorrent Indexers (no form foun)

### ISSUE THREAD

**Issue by NinjaAway** [Jackett/Jackett#7939]
Hello ! 
I'm unable to add YGGTorrent indexer to Jackett
The error is : 
Login failed : No form found on https://www2.yggtorrent.se/ using form selector #user-login

I've seen several topic talk about the same issue, unfortunatly, those issues wasn't on the same version of Jackett as me. (Or I'm dumb.)
And even if I try those solutions, I can't fix my problem.

OS : Windows 10
Jackett Version : 0.14.326.0

Settings : 
![jackett YGGtorrent](https://user-images.githubusercontent.com/54434791/77900541-7f92e300-727e-11ea-9110-abf99a442843.PNG)

Logs : 
![jackett YGGtorrent Log](https://user-images.githubusercontent.com/54434791/77900967-1fe90780-727f-11ea-8d34-c4ed70375c8b.PNG)

Thank's !

**Comment by garfield69** [comment]
Have a read of https://github.com/Jackett/Jackett/wiki/TroubleShooting#login-failed-no-form-found-on-url and see if that applies to you.

**Comment by garfield69** [comment]
Also your sitelink and search link are back to front
Read carefully and apply https://github.com/Jackett/Jackett/issues/7095#issuecomment-582238746

**Comment by NinjaAway** [comment]
Hey !
Yeah already see #7095 ...
Unfortunately, the solution does't apply to me...
I'm updating with the new realese (out 6h ago).
It could be the ratio maybe... If I don't have a good ratio, could it block the authentification ?
I was testing with a pretty old account...

**Comment by NinjaAway** [comment]
I've create a new account (with 15 ration). Jackett updated to version 0.14.358.0
Same issue. Can't login to YggTorrent.

**Comment by NinjaAway** [comment]
Ok with the new version and a new account, YggCookie works fine ! 
Wans't able to make YggTorrent works by the way..
Thank's for help :).
