### ISSUE TITLE
[1337x] Exception (1337x): The operation was canceled.: The operation was canceled. (Test)

### ISSUE THREAD

**Issue by Sturmkater** [Jackett/Jackett#7942]
[log.txt](https://github.com/Jackett/Jackett/files/4404098/log.txt)
### Environment
**OS**: Synology DSM 6.2.2-24922
**.Net Runtime**: CoreLinuxAmdx64
**Jackett Version**: 0.14.358.0

**Are you using a proxy or VPN?** yes
### Description
I can't connect to any index provider. Tried around 6. Reinstalled the docker container several times. All my other docker apps are running smoothly with internet access. Did websearch, but didn't figure out if jackett needs seartent ports open.
### Logged Error Messages
 An error occured while testing this indexer
Exception (1337x): The operation was canceled.: The operation was canceled.

**Comment by garfield69** [comment]
OK. 
the first thing to note is that you are not using the mono variant of Jackett.
As a docker user, you are actually on the latest **CoreLinuxAmdx64** variant, which is good.
But the log also shows **Using Proxy: No**
yet you state you are using a VPN so are you using a system wide VPN like Hide.me rather than a docker inclusive proxy that only proxies Jackett traffic?

Lets see if we can determine if this is a Jackett issue or a docker container issue.
- Start a terminal and connect to your jackett docker `docker exec -it jackett /bin/bash` (replace jackett with whatever you called your Jackett container).
- then post the output of `curl -vvv https://1337x.to/sort-search/bad%20boys%20for%20life%20soundtrack/time/desc/1/`

Thanks.

**Comment by Sturmkater** [comment]
Hey thank you for that super fast replay!!
Right, Mono I did install via Synology App, together with Sonarr. Since I couldn't find a Synology App for Jackett I tried it with docker, but did not set up an other Mono. I followed some instructions I found for linuxserver/jackett.
The PureVPN is in my router, all the traffic goes over it.

The output is:
* Trying 2606:4700:3036::681f:5941...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:3036::681f:5941: Cannot assign requested address

do I have to set more ports? I just set up the webacess port 9117
Here are the commands witch I used to set up docker:
sudo docker create --name=Jackett --restart=always -v /volume1/docker/jackett/config:/config -v /volume1/docker/jackett/downloads:/downloads -e PGID=1001 -e PUID=1001 -e TZ=Europe/London -p 9117:9117 linuxserver/jackett

Thanks again for your help and time!

**Comment by garfield69** [comment]
I think that the issue here may be that the docker image is trying to use IPv6 instead of IPv4 when accessing the WEB.
I don't use IPv6 or Docker so have little experience with either.
@junglebus  @cadatoiva  @ngosang  has anyone experience with IPv6 in combination with docker and can advise if this is an issue or not.

We don't support the docker images, they are built by https://hub.docker.com/r/linuxserver/jackett/ by taking what we publish and they do whatever they do to create these docker images.
Perhaps you might get better support directing your enquiry at https://discourse.linuxserver.io/ or https://discord.gg/YWrKVTn

**Comment by ngosang** [comment]
In my experience the Docker container uses the Host network configuration. So shouldn't be a problem in the container, just in the host.

> The PureVPN is in my router, all the traffic goes over it.

1. You are using VPN for all traffic. It's possible to disable it for a while and do some tests?


2. Do some testing with curl. You can choose IPv4 or IPv6 to see if there are differences:
* `curl -4 -vvv https://1337x.to/sort-search/bad%20boys%20for%20life%20soundtrack/time/desc/1/`
* `curl -6 -vvv https://1337x.to/sort-search/bad%20boys%20for%20life%20soundtrack/time/desc/1/`

3. You can try to disable IPv6 in the host (systemctl + make changes permanent) and restart the host. Be careful with this option, it's safe if your ISP provides you a public IPv4 address. If the ISP traffic is IPv6 this can cause some troubles...

**Comment by Sturmkater** [comment]
Hey guys, sorry for the late response. I think IPv6 is disabled in my system. VPN on and off doesen't make a difference as fare as I can tell. First output over ISP:
curl -4 -vvv https://1337x.to/sort-search/bad%20boys%20for%20life%20soundtrack/time/desc/1/
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
> GET /sort-search/bad%20boys%20for%20life%20soundtrack/time/desc/1/ HTTP/2
> Host: 1337x.to
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/2 200
< date: Thu, 02 Apr 2020 17:57:55 GMT
< content-type: text/html
< set-cookie: __cfduid=da9c7d1959a54ebfcc7b7f10bc8914d871585850275; expires=Sat, 02-May-20 17:57:55 GMT; path=/; domain=.1337x.to; HttpOnly; SameSite=Lax; Secure
...
and:
curl -6 -vvv https://1337x.to/sort-search/bad%20boys%20for%20life%20soundtrack/time/desc/1/
curl: (7) Error

with VPN enabled the same result.
curl -4 -vvv https://1337x.to/sort-search/bad%20boys%20for%20life%20soundtrack/time/desc/1/
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
> GET /sort-search/bad%20boys%20for%20life%20soundtrack/time/desc/1/ HTTP/2
> Host: 1337x.to
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/2 200
< date: Thu, 02 Apr 2020 17:59:19 GMT
< content-type: text/html
< set-cookie: __cfduid=d62fe7c83511d47d8b33848c1a763ff911585850358; expires=Sat, 02-May-20 17:59:18 GMT; path=/; domain=.1337x.to; HttpOnly; SameSite=Lax; Secure
...
and no connection with -6

I will be gone tomorrow for a few days and I haven't managed to get the VPN to my home network running. But afterwards I can contact the guys form the docker image and look if they have an idea. If you have any other ideas, let me know. But anyway, thanks a lot for your effort!
--

Sturmkater
„Rhythmic sets, psychedelic enough to trip soberly.“
www.mixcloud.com/sturmkater/

**Comment by RoloSoze** [comment]
@Sturmkater Is this still an issue?

**Comment by Sturmkater** [comment]
Yea, but I'm still at my parents place helping them with the farm during the look down. So I can't work on it:-( Will take a look once I'm back in one/two weeks.

--

Sturmkater
„Rhythmic sets, psychedelic enough to trip soberly.“
www.mixcloud.com/sturmkater/

**Comment by prior-l** [comment]
I'm seeing the same issue.

I'm also on Synology running jackett via docker  (linuxserver/jackett) with no VPN

```
04-16 17:53:21 Info Starting Jackett v0.16.23.0 | stdout
04-16 17:53:24 Info Environment version: 3.1.3 (/app/Jackett/) | stdout
04-16 17:53:24 Info OS version: Unix 3.10.105.0 (64bit OS) (64bit process) | stdout
04-16 17:53:24 Info Jackett variant: CoreLinuxAmdx64 | stdout
```

When i connect to the docker image `curl -4` works but `curl -6` does not.

**Comment by garfield69** [comment]
@prior-l  
>Fixed my problem by adding `network_mode: host`

can you please indicate where / how this keyword should be added?
Thanks.

**Comment by prior-l** [comment]
I added it to my docker-compose.yml file but it can also be passed to docker with `--network host`

**Comment by Sturmkater** [comment]
Sweeeeet, now it works like charm. Thanks for the help!!!

--

Sturmkater
„Rhythmic sets, psychedelic enough to trip soberly.“
www.mixcloud.com/sturmkater/
