### ISSUE TITLE
toros: empty search retuns 0 results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7957]
Manual search for "" on toros with 0 results.

**Comment by ilike2burnthing** [comment]
Only the homepage currently works. Been like that for a few days.

**Comment by garfield69** [comment]
site is broken.

**Comment by ilike2burnthing** [comment]
Back up now. Test, search, and download all working.

**Comment by garfield69** [comment]
confirmed. back online and fully functional.
