### ISSUE TITLE
cpasbienclone: torrents without title

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7962]
Empty search (and sort by title in Jackett UI)
![image](https://user-images.githubusercontent.com/10577978/78077182-32ab2b80-73a8-11ea-97ed-349c60c5cb38.png)

**Comment by ilike2burnthing** [comment]
Seems like it's removing the last word from the title, so one word titles are empty.

Torrents from screenshot in order:
- usbtrace-130099.html
- clonos-131416.html
- reactos-131415.html
- arch-linux-141550.html
- auto-plus-27-mars-2020-142875.html
