### ISSUE TITLE
piratebit: some results don't have category

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7965]
![image](https://user-images.githubusercontent.com/10577978/78078127-e234cd80-73a9-11ea-97a1-b21550f366f0.png)

**Comment by ilike2burnthing** [comment]
Seems to be the category `Фильмы (HD 720p, 1080p) (48-60 fps)` which is in the .yml file as `{id: Movies, cat: Movies/HD, desc: " |- Фильмы (HD 720p, 1080p) (48-60 fps)"}` - id should be 1717.

https://github.com/Jackett/Jackett/pull/7967
