### ISSUE TITLE
[Nostalgic] no results

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#7968]
The indexer is returning no results, for me.
This is because the download link has been removed from the primary results page.
But when I checked the details page there is no download link there either !?!

@ngosang  could you access the web site https://vhstapes.org/ and confirm that this is the case for you too,
that is,
no download link in results page or details page ?
Thanks.
[edit] its possible my download links have been revoked since I don't contribute.

**Comment by ngosang** [comment]
> its possible my download links have been revoked since I don't contribute.

It seems.
It's working fine, both website and Jackett. I can see the download link in the torrents list.

**Comment by garfield69** [comment]
It seems it was a glitch at the Web Site. I just checked again now, and the download links are back!
