### ISSUE TITLE
[torrentdownloads] Exception (torrentdownloads): Request to https://www.torrentdownloads.me/today/?new=1

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#7970]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Manjaro Linux KDE

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:  0.14.376.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Screenshots

![image](https://user-images.githubusercontent.com/19517680/78138413-0eeff000-7451-11ea-9bb0-bb983856ff01.png)

& magnet download link didnt work

**Comment by ilike2burnthing** [comment]
Does the primary domain .info work for you?

**Comment by garfield69** [comment]
@3xploiton3 
the following **do not work** currently for me:
https://www.torrentdownloads.me/
https://torrentdownloads.unblockit.pro/
These are blocked by CloudFlare ReCaptca and Jackett cannot solve the challenge and there is nothing Jackett can do about this.

the following domains work for me:
https://www.torrentdownloads.info/
https://torrentdownloads.black-mirror.xyz/
https://torrentdownloads.unblocked.casa/
https://torrentdownloads.proxyportal.fun/
https://torrentdownloads.uk-unblock.xyz/
https://torrentdownloads.ind-unblock.xyz/

So access your Jackett Dashboard, edit your torrentdownloads config, and select and try any of the above SiteLinks until you get one that works for you.

If none work, then either
- just use your browser
- consider trying a VPN
- use another indexer
