### ISSUE TITLE
[cpabien] Clearance failed after 30 attempt(s). error.

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#7974]
this public site https://wvw.cpasbien-fr.fr/ is presenting a new cloudflare challenge
and since there is just the one SiteLink I tried switching to using the cookie method to access the site, but I still end up with the `Clearance failed after 30 attempt(s).` error :-(

**Comment by ngosang** [comment]
I see a new re-captcha. Not the Google one. The cookie doesn't work if the User-Agent changes.
![image](https://user-images.githubusercontent.com/10577978/78399936-1dc3d780-75f6-11ea-9ebc-cdceeb2e0639.png)

The cookie doesn't work if the User-Agent changes.
This solution is working but it's a bit complex for the average user:
1. Change browser User-Agent to match the Jackett User-Agent (there are plugins/addons for doing that).
* Linux/Mac Jackett => "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" :
* Windows Jackett => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36";
2. Open https://wvw.cpasbien-fr.fr/  and solve the challange.
3. Copy the cookie to Jackett, it should work.

If more sites keep increasing the security, we will have to adopt something like this => #7643
If you have some free time I would like to hear your thoughts about.

**Comment by garfield69** [comment]
I think 7643 is over the top for the majority of user cases.
Would not the simpler method of expanding the cookie instructions to include grabbing the user-agent string as well as the cookie string and adjusting the cookie-method to use the supplied agent string if provided, work?

**Comment by ngosang** [comment]
> I think 7643 is over the top for the majority of user cases.

I know it's a bit overkill but it also will fix other problems like the users with different IP at home and in Jackett server. Maybe it can be a bit hidden in the UI as advanced option or something like that. Totally optional just for extreme cases. Anyway we have to find a different solution for cpabien, I don't want to force all users to use the proxy for cpabien, that makes no sense. I was talking globally, as a helper feature for all trackers in the future.

Changing the user-agent per indexer it too much work for most people, if it's only for cpabien it's ok. When #7786 is implemented the user could apply the user-agent globally and the cookie method will work, but that will add complexity for us too. Now all the users are using the same User-Agent so they don't have to include it in the bug report. Changing the user-agent can bring more issues, remember #7771

Could you test the proposed solution in https://github.com/Jackett/Jackett/issues/7974#issuecomment-608634322 ? It it works maybe I can add more functionality in the Cardigann definition to overwrite headers in general. This could be useful for other cases.

**Comment by garfield69** [comment]
>Could you test the proposed solution in #7974 (comment) ?

yes, I can confirm that grabbing the cookie from cpasbien while using the user-agent string from the Jackett.Common/Utils/BrowserUtil
https://github.com/Jackett/Jackett/blob/3f01a615108f08e6665c6702590c513e19725ed4/src/Jackett.Common/Utils/BrowserUtil.cs#L11
works.

I have also successfully tested grabbing the cookie with the default browser user-agent and saving them in the indexer config and using the cookie-method + user-agent in the login block.

So I will add this combo setting to both cpasbien and pirateiro, which will get the job done for now.

And should this become more popular then we can revisit this and you can make it more official with a cardigann enhancement.
