### ISSUE TITLE
[magico] is offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#7981]
![image](https://user-images.githubusercontent.com/6933240/78216706-f0ecc300-7516-11ea-9ad3-0c8c6d115914.png)

**Comment by ilike2burnthing** [comment]
It's being really slow, but it's working here
![Magico](https://user-images.githubusercontent.com/59480337/78246438-11018f80-74e1-11ea-8b7c-44abc2f59af3.png)

**Comment by garfield69** [comment]
@vlevas
http://magico.one/ now showing
![image](https://user-images.githubusercontent.com/6933240/78284266-a2bddb00-757b-11ea-815b-64d8b3593e79.png)
Is the site gone, broken, or moved to a new domain?

**Comment by vlevas** [comment]
they say that they will move the tracker to new server so we must wait to see if it will be back.. i will inform you when i have news 1-2 days..

**Comment by vlevas** [comment]
it will come back https://prnt.sc/rrs3az lets wait..

**Comment by cadatoiva** [comment]
@vlevas These down tickets are held for 30 days from when the devs notice the outage before being removed from Jackett. Thanks for the status update on the move, we'll keep our eye on it and close this ticket when the site comes back.

**Comment by vlevas** [comment]
hello the tracker is back..

http://prntscr.com/rs1mpi
