### ISSUE TITLE
[REQ] Speedmaster HD

### ISSUE THREAD

**Issue by Winblackka** [Jackett/Jackett#7982]
Title : Speedmaster HD
URL : https://speedmaster-hd.net
Type : HD
Language : German
Privacy : Private tracker
Login available, pm me.

**Comment by garfield69** [comment]
If you send an invite or credentials to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by Winblackka** [comment]
Check your mail. :)

Thx again for your fantastic work!

**Comment by connectfibra** [comment]
patrão manda um convite ai também jcafeitosa@outlook.com

**Comment by garfield69** [comment]
@connectfibra  my google translate did not do a great job interpreting your comment, but I am going to assume you are requesting someone to send you an invite to the Speedmaster Web Site.
If that is the case, then please know that this is **not** a forum for invites.
This GitHub repo is a support site for the Jackett app.
Unless you are going to work on the Jackett Indexer for Speedmaster and thus require an invite so you can build and test the Jackett indexer, then please look elsewhere for a forum to request invites.

**Comment by garfield69** [comment]
Jackett 0.14.396

**Comment by TWaco** [comment]
> Title : Speedmaster HD
> URL : https://speedmaster-hd.net
> Type : HD
> Language : German
> Privacy : Private tracker
> Login available, pm me.

invite?

**Comment by garfield69** [comment]
@TWaco  this is a support site for the Jackett app and not a forum to solicit invites.
Please look elsewhere.
