### ISSUE TITLE
[torrentheaven] Exception (torrentheaven): DateTime parsing failed for

### ISSUE THREAD

**Issue by Mitnick84** [Jackett/Jackett#7983]
Exception (torrentheaven): DateTime parsing failed for "Today 13:57   Uploader: Invisible": System.FormatException: The string '13:57   Uploader: Invisible' was not recognized as a valid DateTime. There is an unknown word starting at index '16'. at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles) at System.DateTime.Parse(String s) at Jackett.Common.Utils.DateTimeUtil.ParseTimeSpan(String time) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 291 at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 118: Parse error

**Comment by garfield69** [comment]
Looks like the site has changed their torrent search html.
unfortunately no one on the team has an account for this site.

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by Mitnick84** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4425370/log.txt)

**Comment by Mitnick84** [comment]
Need you more logs? 

i get now another message: Exception (torrentheaven): Specified argument was out of the range of valid values. (Parameter 'index'): Parse error

im on Jackett Version 0.14.384.0

**Comment by garfield69** [comment]
Probably. Actually waiting on the c# dev to have a free slot to look into the first problem.
But a full log for the second issue will be good, might as well kill 2 birds with the one stone ;-)

**Comment by Mitnick84** [comment]
here is the new debuglogfile

[log.txt](https://github.com/Jackett/Jackett/files/4433911/log.txt)

**Comment by Mitnick84** [comment]
i cant find the fixes in the latest builds

**Comment by garfield69** [comment]
I have not published the latest build yet. 
the fix I posted 3 hours ago is due to be included in jackett 0.14.459 which I am in the middle of organising as we speak, if only I wouldn't get interrupted every other minute ;-b
Stand by ;-)

**Comment by garfield69** [comment]
Jackett 0.14.459
