### ISSUE TITLE
[dxdhd] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Norin-Radd** [Jackett/Jackett#7985]
### Environment

**dunno is docker on sb**:

**dunno**: [.Net-Core/.Net-Framework/Mono]

**dunno**:

**0.14.384.0**:

**previous release dxdhd was not working either**:

**no** [yes/no]

### Description

when added it says ok, then when tested gives error on test.

**Comment by garfield69** [comment]
Works for me on my win10 Jackett  0.14.384

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by garfield69** [comment]
find the version of Jackett by accessing your Jackett dashboard and scrolling to the bottom.

**Comment by Norin-Radd** [comment]
version is there its the lateste version

**Comment by garfield69** [comment]
good. was confused by all the **dunno** in your original post ;-)
don't forget to provide the enhanced log. it should contain the html returned by the site and  additional debug messages prior to the stack trace you provided in your first post, that may help determine why you are having problems.
Thanks.

**Comment by Norin-Radd** [comment]
here is part of the log. log is too big for hastebin
https://hastebin.com/iwusiwosud.xml

**Comment by garfield69** [comment]
ok. 
it appears that the indexer is currently not supporting the language you are using.
So the date processing for the search results is falling over.
I can add that support once I know which language you are using on the site.
Thanks.

**Comment by Norin-Radd** [comment]
Its portuguese
but if changing to english fixes I can change.

You say its because of site settings. ill test.

**Comment by Norin-Radd** [comment]
yes, i changed the language and now the test is ok.

seems to change language fixed it.

DXDHD supports a lot of site languages... i don't believe you will address all of them.

i believe you can close this if you want.

**Comment by garfield69** [comment]
We already support Portuguese as well as Turkish, Estonian, Danish, Italian, Polish, Norwegian, Czech, Russian, Romanian, Spanish, French, German, Bulgarian, Dutch, Chinese
So it's likely the site has changed their translation of one of the date terms and it should be a simple matter to update our indexer for the correction.

**Comment by garfield69** [comment]
Jackett 0.14.396
