### ISSUE TITLE
[REQ] AutoUpdater

### ISSUE THREAD

**Issue by duramato** [Jackett/Jackett#8]
Add an auto update ,  or just a in app updater

**Comment by raspdealer** [comment]
I will post my script this evening or this weekend.
Feel free to improve it or too cron it.

**Comment by maxcore** [comment]
+1 !

**Comment by raspdealer** [comment]
Here is mine.
https://github.com/Jackett/Jackett/pull/9/commits

Script to automatically update Jackett.
This script is based on the main repo (https://github.com/zone117x/Jackett).
Feel free to adapt for another one, to improve it (and share) or to cron it in your system.

**Comment by WhatFox** [comment]
That doesn't kill or relaunch the app?

I can write an auto update that deals with both platforms but it really needs the build system sorting out first.  Can someone else do that? https://github.com/integrations/feature/build 

My only thoughts are if people run using screen on Linux and the app relaunches itself as a separate process, will that cause issues?

**Comment by flightlevel** [comment]
@WhatFox or anyone else, any experience with the build/ci options in the link above. From my reading appveyor looks like the way to go but I've never used it before.

**Comment by raspdealer** [comment]
I'm used to reboot my rpi after the update... thats enough!!!

**Comment by WhatFox** [comment]
I have no experience to make suggestions for building

**Comment by raspdealer** [comment]
May be we should ask to @kayomani or to markus in sonarr team...

**Comment by flightlevel** [comment]
Well done to @WhatFox 
This is now included in the latest release https://github.com/Jackett/Jackett/releases/tag/v0.7.27

**Comment by duramato** [comment]
Thanks
