### ISSUE TITLE
Jackett not starting in Docker (MyCloudEX2 Ultra)

### ISSUE THREAD

**Issue by KWHgit** [Jackett/Jackett#8005]
Hello,

I'm new to using docker but was previously using jackett on my home computer before i decided to move it to my NAS server for easier use. I am currently having an issue where the jackett container will not start and i am not sure why. 

Here is the log output i receive in portainer:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

**(IMAGE)**

GID/UID

-------------------------------------

User uid:    500

User gid:    1000

-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

Nothing happens after this point. I have researched and read that its possible you dropped support for the processor but mine is a "linux armv7l" according to portainer and the arm32v7 version of jackett does not seem to work.

Would you guys be able to provide any help with this?

Thanks

**Comment by garfield69** [comment]
The docker Jackett images are not supported by us directly, as they are builds created by the [LinuxServer.io](https://hub.docker.com/r/linuxserver/jackett/) group. 
So usually your first call would be to either their [discord](https://discord.gg/YWrKVTn) channel or their [discourse](https://discourse.linuxserver.io/) forum.
@cadatoiva  or @ngosang  either of you free to take a look and offer some diagnosis suggestions?

**Comment by KWHgit** [comment]
I just contacted them and they have said that its not a cpu architecture issue. Waiting on their reply but any other help in the meantime would be useful :)

Thanks

**Comment by garfield69** [comment]
it's likely to be a setup issue or a network issue.
You could see if you can get more info directly from Jackett, as than portainer log is no use whatsoever.
- Start a terminal and connect to your jackett docker `docker exec -it jackett /bin/bash` (replace jackett with whatever you called your Jackett container).
- see if you can find where the Jackett binaries are located, typically `/opt/Jackett` but it could be different for docker, 
- then cd to that folder `cd /opt/Jackett` 
- then try to run Jackett on demand with `./jackett` or if that does not work, then perhaps just `jackett` 
- copy&paste the console output here for us to take a look at.

**Comment by ilike2burnthing** [comment]
@KWHgit is this what you were referring to when you said it could be CPU architecture related? https://github.com/linuxserver/docker-jackett/issues/90#issuecomment-526932288

You could try lsioarmhf/jackett:latest as a test, but I wouldn't recommend using it, as it's over a year out of date.

**Comment by garfield69** [comment]
oh, may also be useful to see the output from `docker version`

**Comment by KWHgit** [comment]
@garfield69 Thanks for replying,

I tried what you said above and when i ran the command (./jackett) the command line replied with "killed". I Then tried just jackett and it said command not found.

@ilike2burnthing Thanks for replying,

I did come across that yesterday and yes it is similar and that is why i suspected it was CPU architecture related. Although after contacting linuxserver on their discord and being told it is not a CPU architecture related issue, im not sure what to think. Also i did try lsioarmhf/jackett:latest and was able to get jackett running but as you said it is out of date and would let me add many indexers.

Also @garfield69 here is the docker version:

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:
 Built:             Sat Nov 16 02:40:36 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Sat Nov 16 10:50:03 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657-dirty
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by KWHgit** [comment]
Linuxserver seemed to have ignored my request asking for potential ways to fix the issue.
In saying that, moving this from a docker issue, would there be anyway to install jackett directly onto the NAS? I tried earlier but only failed as there’s a lot of commands I’m unable to use such as, apt-get etc.

This is probably my last shot at installing the latest jackett otherwise I’ll just move to the deprecated version and use that for as long as possible.

Thanks :)

**Comment by ilike2burnthing** [comment]
I don't think so, though I could be wrong. Googling it didn't bring anything up other than running a full VM on the NAS, which is what Docker tries to get around having to do.

I would think that Brysky's response from that other thread is the only way to go - run Jackett off another device and use the WD as the storage. That or get a different NAS if you can still return or resell the WD. If you need any recommendations let me know.

**Comment by ilike2burnthing** [comment]
Quick after-thought. I have no idea if this would work, but how about running an OS container? https://hub.docker.com/search?q=&type=image&category=os

Then install Jackett in that?

**Comment by usman-umer** [comment]
> otherwise I’ll just move to the deprecated version and use that for as long as possible.

I am having the same issue as you, (Wd ex2 ultra) how would you get an older version of Jackett?

**Comment by KWHgit** [comment]
> Quick after-thought. I have no idea if this would work, but how about running an OS container? https://hub.docker.com/search?q=&type=image&category=os
> 
> 
> 
> Then install Jackett in that?

I didn’t think about that. I’ll try it in the morning and let you know happens



> > otherwise I’ll just move to the deprecated version and use that for as long as possible.
> 
> 
> 
> I am having the same issue as you, (Wd ex2 ultra) how would you get an older version of Jackett?

Install jackett through docker (lsioarmhf/jackett:latest) it will be version 12 probably, which is years out of date. I will try the suggestion above and get back to you.

**Comment by KWHgit** [comment]
> Quick after-thought. I have no idea if this would work, but how about running an OS container? https://hub.docker.com/search?q=&type=image&category=os
> 
> 
> 
> Then install Jackett in that?

Unfortunately my test to install an OS into docker and then install jackett inside has failed. Turns out docker is not meant for OSs to be installed on so there were only a couple of OSs I could choose from, I tried all of them but none worked :/ 

I also forgot to mention that I installed DSM (Synology) onto my EX2 Ultra and tried docker through there which was harder than I thought. Couldn’t get anything to run so I’m back onto the main WD firmware. Unsure of what to do next unfortunately.

**Comment by ilike2burnthing** [comment]
Apologies, I had misunderstood the purpose of these base OS images.

At the risk of misunderstanding something else, would this be of any help? https://github.com/WDCommunity/wdpksrc
Either compiling your own, or making a request with them?

**Comment by KWHgit** [comment]
> Apologies, I had misunderstood the purpose of these base OS images.
> 
> 
> 
> At the risk of misunderstanding something else, would this be of any help? https://github.com/WDCommunity/wdpksrc
> 
> Either compiling your own, or making a request with them?

Had a quick look and seems it could be an option. Will try later and get back to you

**Comment by KWHgit** [comment]
> I myself has just started to try jackett in docker on MycloudEX2 Ultra.  It never seems to work not matter what I try. If you ever have any luck let me know.  I am lost.  It took some time to get sonarr correct but  i can not run both sonarr and radarr at the same time. Seems to much for the MyCloudEX2 Ultra CPU.
> 
> 

What docker images are you using for both sonarr and radarr? I’m able to run both fine, it’s when I use nzbget that things start to drastically slow down.

As for jackett, I have tried every possible solution that I can think of and none have worked. Although something did change.

I was originally using the WDMyCloudEX2Ultra docker image that was provided by WD community, I uninstalled that and used the My Cloud Gen2 Mirror image instead (they are both the same machines, just marketed differently - according to fox_exe). When I tried to install jackett again from linuxserver it ended up sending the EX2 Ultra into a reboot, took like 15minutes for it to reboot. But besides that, it doesn’t seem to work. 

Have you tried using other docker images from different publishers?

**Comment by dtammons** [comment]
I did have both sonarr and radarr running at once but it was very slow.  That is when I notice it was taxing the the CPU to 100%  and never come off of it. I did set the limits on the their containers but for some reason it they would always put the CPU to 100% so I gave up on radarr since I have couchpotato installed too.

**Comment by KWHgit** [comment]
> I did have both sonarr and radarr running at once but it was very slow.  That is when I notice it was taxing the the CPU to 100%  and never come off of it. I did set the limits on the their containers but for some reason it they would always put the CPU to 100% so I gave up on radarr since I have couchpotato installed too.

Ahh okay. I don’t like Couchpotato so that wasn’t an option for me. I have decided to switch from torrents to Usenet and honestly I recommend it 100%. It’s a pain to get setup but once everything is working it is amazing how fast and easy it is.
