### ISSUE TITLE
[New Tracker REQ] Gormogon

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#801]
Specializes in old/rare/classic movies & TV series: 
http://www.gormogon.com/

I personally don't have an invite right now, but maybe someone else does?

**Comment by armani316** [comment]
@kaso17 Invite sent.

**Comment by kaso17** [comment]
nothing received

**Comment by armani316** [comment]
Check Spam folder?

**Comment by kaso17** [comment]
already did that, nothing there

**Comment by armani316** [comment]
@kaso17 Still nothing?

**Comment by armani316** [comment]
@kaso17 Staff contacted! Stay tuned :)

**Comment by kaso17** [comment]
got the invite, thank you

**Comment by armani316** [comment]
@kaso17 Confirmation email received after registering?

**Comment by kaso17** [comment]
yes

**Comment by kaso17** [comment]
fixed with 1cde5c514268fc395d8b4d7a1f8838ba2e9508bd, requires the latest v0.7.807 pre-release, please try it

**Comment by armani316** [comment]
@kaso17 Seems to be working fine for now. I'll report back if there are any issues. Thanks a lot.

**Comment by kaso17** [comment]
removed via e3d9c68f5aaf33619d722748d31c7766d45ae989 (shutdown)
