### ISSUE TITLE
bittorrentam: the tracker seems to be down

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8017]
https://bittorrent.am/
Tested in https://www.uptrends.com/tools/uptime

**Comment by ilike2burnthing** [comment]
Site is back online, but search fails there and in Jackett

**Comment by garfield69** [comment]
even though its been offline/online intermittently several times since early March, in reality its been broken since it went offline the first time on 15th of February.
Even now, the page of the latest torrents has only a new date of 27th January.
I'm going to remove it.
