### ISSUE TITLE
bj-share: search pattern

### ISSUE THREAD

**Issue by eduardomoroni** [Jackett/Jackett#8032]
### Environment
I am ignoring the environment session given that the issue I am raising is related to the tracker search engine.

### Description
BJ-Share has a very peculiar (maybe fragile) search engine, when you search for SERIE_NAME EPISODE they do not return any result. But if you search for SERIE_NAME you can find the episode in the results.
I am no sure if this is a problem that we want to solve on Jackett level, I am using pyMedusa and they have their own implementation of BJ-Share that kind of works.
Is there a way to translate jacket's incoming request to be a query that only has serie name, and filter the results based on episode name Or Episode number?

### Logged Error Messages
No error

### Screenshots
In the first query I search for *Star Trek Picard* and I am able to find *S01E10*
![image](https://user-images.githubusercontent.com/823150/78436367-e5181280-7676-11ea-86e8-2a06ddf26491.png)
If I change the query to *Star Trek Picard S01E10* I can't find anything
![image](https://user-images.githubusercontent.com/823150/78436532-f103d480-7676-11ea-9cf1-906542857a0c.png)

Another example is
![image](https://user-images.githubusercontent.com/823150/78438122-65d70e80-7677-11ea-808c-f1c987160b5f.png)
![image](https://user-images.githubusercontent.com/823150/78438284-712a3a00-7677-11ea-8b15-6a69cd369178.png)

I could go on and on, but basically the problem is that it's doesn't work consistently

**Comment by RoloSoze** [comment]
@eduardomoroni Are  you able to provide an invite to a C# developer?

**Comment by garfield69** [comment]
perhaps @DarkSupremo  or @christianfds  can provide an invite or even contribute as they both have since Dec 2019

**Comment by DarkSupremo** [comment]
It's done already, but maybe it's another problem... i'll take a look tomorrow.
`private string StripSearchString(string term, bool isAnime)
        {
            // Search does not support searching with episode numbers so strip it if we have one
            // Ww AND filter the result later to archive the proper result
            term = Regex.Replace(term, @"[S|E]\d\d", string.Empty).Trim();
            return isAnime ? term.TrimEnd(_digits) : term;
        }`

**Comment by DarkSupremo** [comment]
Tested it today, and it seens to be working fine, maybe you can explain exactly what problem you're experiencing?

It already strip the season and episode from search and filter it later (it may cause problem if the result is not on the first page, but it's the only way for now on BJ-Share), the season and episode letter must be in uppercase to be striped correctly.

This is an search running directly in Jackett:
![image](https://user-images.githubusercontent.com/7059651/79057861-74f02a80-7c3c-11ea-9b19-66cfa1b5407e.png)

**Comment by eduardomoroni** [comment]
Thanks @DarkSupremo for looking into this issue.

As you state if you manually search on Jackett it works fine, I don't know the difference but seems like when it's an external query (not UI) something is odd.

App logs can be found here: https://pastebin.com/2i2rAEcf

I tried to use both pyMedusa and Sonarr, similiar error happened to me.

This is the log I receive when Jackett receives a query from and external app
`
2020-04-12 10:58:17.7963 Info Found 0 releases from BJ-Share for: Star Trek Picard S01E10 
`

and this is the log I receive when I manualy query (using jackett UI)
`
2020-04-12 11:08:15.1424 Info Manual search for "Star Trek Picard" on bjshare with 3 results. 
`

The query I do is "Star Trek Picard S01E10"
![image](https://user-images.githubusercontent.com/823150/79065121-24191a00-7cae-11ea-95b0-611b5120a9d0.png)

My guess is that through manual search we strip off the `S01E10` before querying, then we run the query with `Star Trek Picard` and search for `S01E10` in the results. But when it's not a manual search we just search for `Star Trek Picard S01E10`

**Comment by eduardomoroni** [comment]
> 
> 
> @eduardomoroni Are you able to provide an invite to a C# developer?

If needed yes,

**Comment by DarkSupremo** [comment]
I don't have pyMedusa anymore to test it, but i'll do some tests on Sonarr

**Comment by DarkSupremo** [comment]
I noticed this message in your log (from bj-share):

> 
        Verificamos que você está utilizando o domínio antigo do BJ-Share.<br />
        Atualize pois em breve ele deixará de funcionar e você poderá ficar sem acesso.<br /><br />
        Altere também nos seus favoritos.<br /><br />
        O novo endereço é: <a href="https://bj-share.info/" style="color: red">https://bj-share.info/</a>

Maybe you're using an outdated version of Jackett? because we already updated this address on Jackett long time ago... Can you check your Jackett version and the address inside BJ-Share config on Jackett ?

**Comment by DarkSupremo** [comment]
Tested on pyMedusa here and it worked fine aswell, but in the case of Star Trek: Picard, i had to add an Scene Exception as "Star Trek: Picard 2020", because pyMedusa didn't parsed it propely.

![image](https://user-images.githubusercontent.com/7059651/79075733-fee6d480-7cca-11ea-8154-eb304566aa07.png)

![image](https://user-images.githubusercontent.com/7059651/79075766-2178ed80-7ccb-11ea-85f3-80002a21720e.png)

![image](https://user-images.githubusercontent.com/7059651/79075791-42d9d980-7ccb-11ea-8c1c-204900dbf24f.png)

**Comment by DarkSupremo** [comment]
Found some problems related to group options turned off, could you try enable it in bj-share options and check if it solve your problem? i'll look into that...

![image](https://user-images.githubusercontent.com/7059651/79080572-6e20f080-7cec-11ea-99c8-8288e34190b5.png)

**Comment by eduardomoroni** [comment]
@DarkSupremo I appreciate your help. I believe we can close this issue.

cheers
