### ISSUE TITLE
bj-share: parsing error

### ISSUE THREAD

**Issue by bernardojanes** [Jackett/Jackett#8033]
### Environment

**OS**: Win 10
**.Net Runtime**: .Net framework
**.Net Version**: 4.0
**Jackett Version**: 0.14.418.0
**Last Working Jackett Version**:
**Are you using a proxy or VPN?** yes

### Description
I usually get two errors while using bj-share indexer:
`bjshare: Error while parsing row '': Object reference not set to an instance of an object.`
` Index was outside the bounds of the array.`

But I am still see results
### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots
![image](https://user-images.githubusercontent.com/63149904/78449898-e64b3e80-767a-11ea-84a5-21dd8d3b219f.png)
![image](https://user-images.githubusercontent.com/63149904/78449903-ee0ae300-767a-11ea-87d3-42e707f5d2a1.png)

**Comment by garfield69** [comment]
seems ok to me, albeit I can only get as far as the login page since I do not have an account
https://bj-share.info/login.php
![image](https://user-images.githubusercontent.com/6933240/78462734-ffaac400-7728-11ea-89a9-0aff48de055e.png)
is it broken deeper thank this?

**Comment by eduardomoroni** [comment]
This is a private tracker, so I think that being behind authentication is not the problem.
How could I help you in solving this issue? Sharing an account? A screen sharing would be enough?

**Comment by RoloSoze** [comment]
@DarkSupremo Can you take a look at this as well?

**Comment by garfield69** [comment]
Jackett 0.16.18
