### ISSUE TITLE
[req] DimeADozen / EZTorrent

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#8036]
DimeADozen (EZTorrent) is a Semi-Private Torrent Tracker for BOOTLEG MUSIC.

http://www.dimeadozen.org/

**Comment by garfield69** [comment]
as a guest I don't see the download links.
can you access the site, and use
http://www.dimeadozen.org/torrents-browse.php?search=%2Btalk+%2Bparis&cat=0&incldead=1&searchscope=1
and return the html (refer https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source if you need to)
if the results page does not have any DL links can you click on the details of one of the torrents and provide that html instead.
Thanks.

**Comment by dimqua** [comment]
> if the results page does not have any DL links can you click on the details of one of the torrents and provide that html instead.

http://www.dimeadozen.org/torrents-details.php?id=673256

[Torrent details for 'Talk Talk - 1986-07-05 Paris (Reseed)'.txt](https://github.com/Jackett/Jackett/files/4464586/Torrent.details.for.Talk.Talk.-.1986-07-05.Paris.Reseed.txt)

**Comment by garfield69** [comment]
Jackett 0.15.5

**Comment by ilike2burnthing** [comment]
http://www.dimeadozen.org/
```
Sorry!
EzTorrent is stopped due to hardware/software/DB maintenance.
Please try again sometime later this day. Thank you!
Take care!
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://www.dimeadozen.org/ returning
```
Sorry!

EzTorrent is stopped due to hardware/software/DB maintenance.
Please try again sometime later this day. Thank you!

Take care!

webmaster@dimeadozen.org
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/8036#issuecomment-716314793 again

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
```
Sorry!

EzTorrent is stopped due to hardware/software/DB maintenance.
Please try again sometime later this day. Thank you!

Take care!

webmaster@dimeadozen.org
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/8036#issuecomment-977547633

**Comment by ilike2burnthing** [comment]
back up

**Comment by KoenBoone** [comment]
dimeadozen creates torrent links with an unique ID for each user, one can not just copy a torrent link as it is linked to the login and password.

**Comment by ilike2burnthing** [comment]
Are you reporting an issue you've come across, or are you speaking generally without knowing how Jackett works?

**Comment by garfield69** [comment]
http://www.dimeadozen.org/ ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://www.dimeadozen.org/ ERROR 503 The requested URL could not be retrieved

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://www.dimeadozen.org/ ERROR 503 The requested URL could not be retrieved

**Comment by ilike2burnthing** [comment]
back up
