### ISSUE TITLE
Cannot add hdtorrents indexer

### ISSUE THREAD

**Issue by imTHAI** [Jackett/Jackett#8043]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
QNAP OS 4.4.2.1262

**Jackett Version**:
Version 0.13.228.0
**Are you using a proxy or VPN?** [yes/no]
no
### Description
I tried to add indexx HD-TORRENTS
I can connect directly on the website. ( means the website is working, my account is ok )
I've tried with the different available url.
### Logged Error Messages
[hdtorrents] Exception (hdtorrents): Input string was not in a correct format.: Input string was not in a correct format. (Config)

### Screenshots

[Place any screenshots of the issue here if needed]
![image](https://user-images.githubusercontent.com/36070606/78471958-7b127280-7735-11ea-8e0b-cd75856490c4.png)

**Comment by garfield69** [comment]
please read and follow https://github.com/Jackett/Jackett/wiki/Troubleshooting#input-string-was-not-in-a-correct-format
and let us know how you go.

**Comment by imTHAI** [comment]
It works, thank you. Sorry I should have checked for an update before I open an issue.
