### ISSUE TITLE
[yts] No connection could be made because the target machine actively refused it.: No connection could be made because the target machine actively refused it. (Config)

### ISSUE THREAD

**Issue by DrakeJones** [Jackett/Jackett#8045]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
works for me.
please read and follow https://github.com/Jackett/Jackett/wiki/Troubleshooting#no-connection-could-be-made-because-the-target-machine-actively-refused-it

**Comment by DrakeJones** [comment]
Well. if it works you then I guess we should all be satisfied.

**Comment by garfield69** [comment]
I will rephrase my comment in future.
The _works for me_ statement was meant as a pointer that the issue is not with the Jackett YTS indexer, since the indexer is working for me.
Therefore the issue is external to Jackett.

**Comment by DrakeJones** [comment]
Thank you.  I appreciate that.
