### ISSUE TITLE
[REQ] Kaztorka

### ISSUE THREAD

**Issue by ionedji** [Jackett/Jackett#8046]
If it is possible please add following tracker to your list:

https://kaztorka.org/
semi-private  (0day/general) (russian)

**Comment by garfield69** [comment]
Jackett  0.14.501

**Comment by ionedji** [comment]
Thank you!

пт, 10 апр. 2020 г. в 13:09, garfield69 <notifications@github.com>:

**Comment by garfield69** [comment]
https://kaztorka.org/ returning ERR_CONNECTION_REFUSED
Just me or is the site down, broken or moved to a new domain?

**Comment by ionedji** [comment]
Seems that torrent tracker is closed. It’s unreachable for several days. I think we can wait about 1 week, if there would be no changes you can delete it :(

**Comment by ilike2burnthing** [comment]
Closed apparently.
![](https://sun9-65.userapi.com/TRnVlY1g7j1F73kGxsv5UKXnG3ZQIZbM65Arxg/rFtmT5e8qt4.jpg)
```
The project is closed. Thanks to everybody, you're free.
```
https://vk.com/topic-3485797_29703541

**Comment by ilike2burnthing** [comment]
```
Guys, good afternoon to all! The site has closed. The decision was unexpected. Not all administrators and moderators were notified.
Unfortunately, the project has come to an end. Many of us loved this site, invested a lot of time and attention in it.
It's sad and sad. But these are the realities of today.
We will miss the golden times of our beloved Kaztorka and our users!
With Respect, the administration of the
site.
```
```
Closed because of non-profit. We supported the server at our own expense. The end cause was a server malfunction.
```
https://vk.com/kaztorka_official
