### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on https://yggtorrent.se/ using form selector 

### ISSUE THREAD

**Issue by gchapeyrout** [Jackett/Jackett#8059]
### Environment

**OS**: Docker linuxserver/radarr:lastest

**Are you using a proxy or VPN?** [yes/no] no

### Description

Login to Yggtorrent fails since about one hour now

### Logged Error Messages

Jackett.Common.IndexerException: Exception (yggtorrent): Login failed: No form found on https://yggtorrent.se/ using form selector **#user-login**
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://yggtorrent.se/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 562
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1353

### ADDITIONNAL INFORMATION ###

YGG Form:
` form action="/user/login" method="post" id="user-login"`

**Comment by garfield69** [comment]
please follow #8056 for updates on this issue.
