### ISSUE TITLE
[yggtorrent] Resource temporarily unavailable: Resource temporarily unavailable (Config)

### ISSUE THREAD

**Issue by Guiboui77** [Jackett/Jackett#8060]
### Environment

**OS**: Windows 10 / Synology DS218+ DSM 6.2.2

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.14.433.0

**Last Working Jackett Version**: 0.14.396

**Are you using a proxy or VPN?** no

### Description

I saw this issue many times on github, and I tried to fix my Docker's DNS with this tutorial : https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/ 
But I'm starting with my NAS, and this isn't that simple for me. I'm using Putty connected in SSH to my NAS, and most of commands are not recognized. I also changed my status with the sudo -i, but same thing, I dont get the same results as in the tutorial. Finally I don't really know how to create the daemon configuration file. Can you explain to me the procedure step by step or rephrase it an other way ?
Thanks in advance

**Comment by garfield69** [comment]
Yeah, nah. sorry.
Basically, tickets raised in this site relate to issues that are a direct results of bugs in the Jackett app.
The use of docker (supported by the LinuxServer.io people),  the re-interpretation of an article written by someone not from the Jackett team, and the education of how to use commands on your NAS, do not fall within the scope of this support site.
I am sorry but you are going to have to look elsewhere for the answers to your questions.
