### ISSUE TITLE
[Demonoid] Search temporarily disabled for guests

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8070]
![Demonoid](https://user-images.githubusercontent.com/59480337/78607489-0f282b00-7857-11ea-8790-b4ce36bf5b59.png)

Will check periodically and update when it's back up.

**Comment by ilike2burnthing** [comment]
```
Update: The malfunctioned servers are currently being replaced. Further downtime is expected.
```

**Comment by garfield69** [comment]
Update 2: Servers migration have been completed. Search query is now available to the guests and site should work as intended.
