### ISSUE TITLE
[ICETorrent] Login failed: Selector didn't match

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8071]
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.14.447.0

**Last Working Jackett Version**: 0.14.433 [Although I don't think this is a version-related issue]

**Are you using a proxy or VPN?** No

### Description
I am unable to configure ICETorrent in Jackett. The issue seems very recent as I was able to use this tracker a couple of days ago.

### Logged Error Messages
`An error occured while updating this indexer
Login failed: Selector "a[href^="/logout?_csrf_token="]" didn't match`

Enhanced log:
[log.txt](https://github.com/Jackett/Jackett/files/4441684/log.txt)

### Screenshots
Not needed

**Comment by garfield69** [comment]
I'm am seeing this too. I shall investigate.

**Comment by garfield69** [comment]
they have upgraded to a new engine, with complete overhaul of login, search, categories et.al.

**Comment by garfield69** [comment]
Jackett 0.14.459

**Comment by RoloSoze** [comment]
Works well. Thanks!
