### ISSUE TITLE
Jackett in OSX

### ISSUE THREAD

**Issue by Eldoc62** [Jackett/Jackett#8073]
Hi all,

Here's what I did:

I installed Brew (https://brew.sh) and mono (brew update && brew install mono)

mac-pro-de-nico:~ nico$ which mono
/usr/local/bin/mono
mac-pro-de-nico:~ nico$ mono --version
Mono JIT compiler version 6.8.0.105 (tarball Tue Feb  4 20:28:59 GMT 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
mac-pro-de-nico:~ nico$ which curl
/usr/bin/curl
mac-pro-de-nico:~ nico$ curl --version
curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy 
mac-pro-de-nico:~ nico$ 

After :

https://github.com/Jackett/Jackett#installation-on-macos

in terminal :

/Volumes/HDD_1/Log\'s/Apple/Jackett/Jackett/install_service_macos ; exit;
mac-pro-de-nico:~ nico$ /Volumes/HDD_1/Log\'s/Apple/Jackett/Jackett/install_service_macos ; exit;
Agent successfully installed and launched!
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Opération terminée]

in http://localhost:9117/

I have nothing

what can i do please ??

**Comment by garfield69** [comment]
what macos are you running?
if you are on High Sierra, Mojave or Catalina then you do not need brew or mono as Jackett for macos is a .net core package that should work for all Macos 10.13+

lets see if we can get more info with this method:
- open a terminal
- `cd /usr/local/bin/Jackett`
- `./jackett`

select and copy the console log and paste it here so we can take a look

**Comment by Eldoc62** [comment]
Hi, it's ok !
After one reboot of macOS it's OK for jackett
Thanks
