### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Specified argument was out of the range of valid values.Parameter name: Unknown operator: : Specified argument was out of the range of valid values.Parameter name: Unknown operator:  (Test)

### ISSUE THREAD

**Issue by s20coeur** [Jackett/Jackett#8074]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
I've no idea how you managed to generate this error.
I suggest you use your jackett dashboard and trashbin the yggtorrent config and start a fresh one from the add-indexers page using the wrench.
then add your credentials anew even if the appear pre-filled and see if that works for you.

**Comment by s20coeur** [comment]
Hello,

Thx for your answer, unfortunately i already have tried this and it don't work :(.

It seem's that Ygg add an anti DDOS page when you click on a link before you are redirected to the requested page.

**Comment by garfield69** [comment]
In that case, while your IP address remains blacklisted by CloudFlare, you can
use the YGGCookie indexer instead.
This will allow you to access the YGGTorrent Web Site by an alternate method
.
But first, you need to upgrade your Jackett to the latest version 0.14.459

**Comment by s20coeur** [comment]
Thank you very much garfield69 for your help ;)
I'm not sure how to update my jackett (NAS image docker :/) but i'll find out one way or other ;)

Have a nice day !

**Comment by s20coeur** [comment]
Ok Update to the latest Jackett docker works perfectly ;)

Again thank you ! :)
