### ISSUE TITLE
[iptorrents] Your cookie did not work: An error occurred while sending the request (Config)

### ISSUE THREAD

**Issue by mixednutts** [Jackett/Jackett#8076]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

Linux XXXX 3.4.26 #1 SMP PREEMPT Wed Oct 18 03:00:23 CST 2017 i686 GNU/Linux

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

Mono JIT compiler version 5.18.1.0 (explicit/9cb3348 Fri Mar 22 18:09:43 CST 2019)

**.Net Version**:

**Jackett Version**:

Jackett Version 0.14.447.0

**Last Working Jackett Version**:

New install

**Are you using a proxy or VPN?** [yes/no]

No external proxy or VPN

### Description
-Open Jackett Web UI

[List steps to reproduce the error and details on what happens and what you expected to happen]
-Open Jackett Web UI
- Add Indexer
- Select IPTorrents
- Use standard site address (http://iptorrents.com) (can access this from PC and via proxy on same box as Jackett)
- Use cookie obtained through instructions
- Click OK to add indexer
- Error message displayed

I tried with alternative sites but same result.

### Logged Error Messages

 An error occured while updating this indexer
Your cookie did not work: An error occurred while sending the request

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

[log.txt](https://github.com/Jackett/Jackett/files/4443009/log.txt)

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Is this only happening with that build? If so, what is the latest build where it works?

If it's happening on all builds, double check the link below to make sure:
https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work

**Comment by mixednutts** [comment]
@ilike2burnthing Went backwards through the releases and received same error until version 0.13.163.0.  I think there was a major change to authentication with IPTorrents at this stage.

I went through the troubleshooting guide before logging the issue including using the Jackett app server as the proxy to ensure the cookie was relevant to that machine.

Error for version 0.13.163.0

[0.13.163.0.txt](https://github.com/Jackett/Jackett/files/4447168/0.13.163.0.txt)

Error for version 0.13.173.0

[0.13.173.0.txt](https://github.com/Jackett/Jackett/files/4447169/0.13.173.0.txt)

**Comment by cadatoiva** [comment]
There was a change in IPTorrents code at that time in https://github.com/Jackett/Jackett/commit/12b2de272500831c8817388994972247522fdc56

@ngosang would you be able to investigate this?

**Comment by ilike2burnthing** [comment]
See also: https://github.com/Jackett/Jackett/issues/7852

**Comment by mixednutts** [comment]
I've tracked my problem down to mono failing to establish SSL connections on my system architecture so I am looking at downgrading the mono version to see if that can sort it out.  I'll post any update here if I get it working.

**Comment by ilike2burnthing** [comment]
> I've tracked my problem down to mono failing to establish SSL connections on my system architecture so I am looking at downgrading the mono version to see if that can sort it out. I'll post any update here if I get it working.

Relevant? https://github.com/Jackett/Jackett/issues/7223 - related PR was implemented in v0.13.163.0

**Comment by cadatoiva** [comment]
It might be worthwhile to attempt to install the standalone version instead of the mono version. Instructions are on our wiki

**Comment by garfield69** [comment]
>Instructions are on our wiki

which wiki are you referring to?

**Comment by cadatoiva** [comment]
I thought we had something dedicated, but there's this: https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work-the-ssl-connection-could-not-be-established

**Comment by mixednutts** [comment]
I've exhausted my options here and doubt anything would provide for a longer term solution on my system being as old as she is.    Time to upgrade me thinks.  Thanks for your help guys.
