### ISSUE TITLE
7torrents

### ISSUE THREAD

**Issue by vamp911** [Jackett/Jackett#8082]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
this is a genuine issue with the web site
![image](https://user-images.githubusercontent.com/6933240/78724083-c4a2cd80-7980-11ea-97b8-88a85ae77dda.png)

**Comment by ilike2burnthing** [comment]
@garfield69 the site has been down for a few days now, do we want to create a `Down / Waiting for removal` post?

**Comment by garfield69** [comment]
there already is.
use the labels filter to check on these
![image](https://user-images.githubusercontent.com/6933240/78726607-86101180-7986-11ea-9c6d-57eadc12154d.png)

**Comment by ilike2burnthing** [comment]
Missed that, ta!
