### ISSUE TITLE
[torrentdownloads] Exception (torrentdownloads): The operation was canceled.: The operation was canceled. (Test)

### ISSUE THREAD

**Issue by kevindd992002** [Jackett/Jackett#8085]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by kevindd992002** [comment]
I didn't cancel the operation but it looks like the test is not finishing.

**Comment by garfield69** [comment]
The torrentdownloads  indexer works for me using the following SiteLinks
https://www.torrentdownloads.info/
https://torrentdownloads.black-mirror.xyz/
https://torrentdownloads.unblocked.casa/
https://torrentdownloads.proxyportal.fun/
https://torrentdownloads.uk-unblock.xyz/
https://torrentdownloads.ind-unblock.xyz/

I get clearance-failed for https://www.torrentdownloads.me/
and failed,redirected for https://torrentdownloads.unblockit.pro/

you did not tell us which version of Jackett you are on so access your Jackett Dashboard and scroll to the bottom.
Assuming you are on any version between  v0.14.253  and v0.14.459 
then edit the torrentdownloads config with your wrench and try out any of the proxies and see if they work for you.
And if you are on  0.14.252 or older then its about time you updated your Jackett ;-)

**Comment by kevindd992002** [comment]
Sorry about that. Yes, I'm on 0.14.459.0 and was using the https://torrentdownloads.black-mirror.xyz/ site when it failed for me. Changing to another site fixed the issue. Not sure why, but can this be an ISP routing issue?

**Comment by kevindd992002** [comment]
Although I can ping that server:

![image](https://user-images.githubusercontent.com/3907957/78741997-5f090e00-798d-11ea-8264-618b68cdb2fc.png)

**Comment by garfield69** [comment]
Apart from the official site (usually the first on the list of SiteLinks), the others are usually un-official proxies provided by 3rd parties.
As such they are potentially unreliable as far as service is concerned.
That said, they are better than nothing.
Have a read of [this wiki article](https://github.com/Jackett/Jackett/wiki/TroubleShooting#the-operation-was-canceled) which may give you some insights into what could cause a task canceled.
