### ISSUE TITLE
[req]: SportHD

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8090]
http://sporthd.org/signup.php

@garfield69 @ngosang The tracker is supported in Jackett but there are no active maintainers. It rarely opens, so I recommend signing up.

**Comment by RoloSoze** [comment]
@cadatoiva Thanks! Also, check your email, please!

**Comment by garfield69** [comment]
http://sporthd.org/ returning server IP address could not be found.
has the site gone, is broken or moved to a new domain?

**Comment by RoloSoze** [comment]
Server is unreachable for now. I also found the following after a quick Google search:

Site is blocked in Russia

In this regard The Federal Service For Supervision Of Communications, Information Technology and Mass Media has taken measures aimed at permanent restriction of the access to the web-site sporthd.org in order of the article 15.6-1 of the Federal Law No. 149-FZ of July 27, 2006 “On Information, Information Technology and Protection of Information”.

try bt.sporthd.org 

The above URL did not work for me, but keep an eye on it.

**Comment by KronK0321** [comment]
sporthd has a new URL: satsporthd.org

**Comment by garfield69** [comment]
Thanks for the info

**Comment by garfield69** [comment]
v0.16.1668

**Comment by ArunB7105** [comment]
Hey, any idea when the registration will be open again?
Need it badly now

**Comment by ilike2burnthing** [comment]
http://satsporthd.org/ - ERR_CONNECTION_REFUSED (with and without VPN)

**Comment by KronK0321** [comment]
Site was sold an/or taken down on June 21st. This tracker is no more.

**Comment by ilike2burnthing** [comment]
Back up with the notice (from 2wks ago):

> The site is closed!!!!
sale sale sale!!!!!!
the sale of the site and the entire archive of 40 hard discs is open!!!

Leaving open and labelled  as down to monitor.

**Comment by garfield69** [comment]
Now presenting a login page.
online?

**Comment by ilike2burnthing** [comment]
Yea, once logged in you see https://github.com/Jackett/Jackett/issues/8090#issuecomment-1615928349 from 3wks ago. Forum is still closed and there have been no new uploads, so was waiting to see if there was any change over the next few days. Well it's been a few days and the site is still up, so 🤷

**Comment by KronK0321** [comment]
I've tried almost daily since posting here 2 weeks ago and cannot access the site. I don't get a login page at all. Is it still working for you? I'm in Canada.

**Comment by ilike2burnthing** [comment]
Currently getting ERR_CONNECTION_TIMED_OUT, but had been fine for the last 4 days.

**Comment by ilike2burnthing** [comment]
back up, and up for all Uptrends checkpoints - https://www.uptrends.com/tools/uptime?toolRequestGuid=ffffce3b-705e-4934-b30b-4026d075037a

**Comment by KronK0321** [comment]
I'm able to access the site through a proxy. Looks like it was my ISP the whole time. Sorry for the erroneous info!

**Comment by ilike2burnthing** [comment]
http://satsporthd.org/ - ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.21.1446
