### ISSUE TITLE
Add option to filter results more strictly

### ISSUE THREAD

**Issue by kaso17** [Jackett/Jackett#810]
The problem is described in #736
Essentially we would have to extend the existing AND filter used for some indexers to work on word boundaries.
As this might cause unwanted side effects it should be configurable for each indexer.

**Comment by Nyghto** [comment]
thanks for adding this 👍

**Comment by armani316** [comment]
I have noticed that trackers like WorldOfP2P and RockHard Lossless return results using all search keywords, so most of them are irrelevant to the search being conducted.

**Comment by kaso17** [comment]
WorldOfP2P and RockHard Lossless results should be fixed since both are using the andmatch filter by now

**Comment by garfield69** [comment]
closing as stale. Open a fresh ticket if this is still relevant.
