### ISSUE TITLE
[isohunt2] Exception (isohunt2): Clearance failed after 30 attempt(s).: Clearance failed after 30 attempt(s). (Test)

### ISSUE THREAD

**Issue by geofferiswheel** [Jackett/Jackett#8109]
### Environment

**OS**: Docker container v0.2.0.1480-ls57

**Jackett Version**: 0.14.136.0

**Are you using a proxy or VPN?** [yes/no] No

### Description

Adding indexer returns this error when testing indexer. Also having the same issue when adding and then testing other indexers (Kat.li, torrentProject2).

I've attempted restarting the container, rebuilding the container, and checking for updates. Opening sites and searching works. Site is not down.

### Logged Error Messages

[docker-jackett-error.txt](https://github.com/Jackett/Jackett/files/4457120/docker-jackett-error.txt)

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/TroubleShooting#clearance-failed-after-30-attempts
