### ISSUE TITLE
[LeagueHD+MoeCat] Move to cookie-based authentication

### ISSUE THREAD

**Issue by budgetfermium** [Jackett/Jackett#8111]
Please move to cookie-based authentication for LeagueHD and MoeCat. LeagueHD will likely move to cookie-based authentication in the near future, and MoeCat already has. Here are the official messages from both, along with corresponding translated versions.

LeagueHD:
1.登录后不要退出，站点随时可能关闭登录页面。
Google Translate: 
1.Do not log out after logging in. The site may close the login page at any time.

MoeCat:
登陆后请保存好cookie，不要退出登录
Google Translate:
Please save cookies after logging in, do not log out

**Comment by garfield69** [comment]
Thanks for the heads up.
I think this is a bad move by these sites, how is a user supposed to recover their lost cookie session if they loose it due to a computer issue?
But anyway, I'll remove the login and switch to cookie session.

**Comment by garfield69** [comment]
already using cookie method for loginHD.

**Comment by budgetfermium** [comment]
My bad. Apologies for the mistake.

**Comment by garfield69** [comment]
Jackett  0.14.501
