### ISSUE TITLE
[REQ] TorrentDB

### ISSUE THREAD

**Issue by EvilHidden** [Jackett/Jackett#8112]
If possible, please add private tracker TorrentDB. Open signups currently.
https://torrentdb.net

**Comment by garfield69** [comment]
This indexer was added to Jacket back in Nov 2016

closing as a duplicate of #7660 

Please check before posting requests, use your Jackett Dashboard add-indexer page !

**Comment by EvilHidden** [comment]
It's literally a brand new tracker made yesterday and it does not exist in the Indexer list.

**Comment by garfield69** [comment]
Oh, my apologies.
got torrent**DB** and torrent**BD** looking the same to my dyslexic eyes :-D

**Comment by garfield69** [comment]
Jackett 0.16.18

**Comment by garfield69** [comment]
note: switched from using a login form to a cookie as a results of #8243

**Comment by ilike2burnthing** [comment]
https://torrentdb.net/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://torrentdb.net/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://torrentdb.net/ returns fwrite(): Write of 2116 bytes failed with errno=28 No space left on device

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://torrentdb.net/ returns DNS_PROBE_FINISHED_NXDOMAIN (DNS domain not found)

**Comment by garfield69** [comment]
@EvilHidden  do you have any news on the state of torrentDB, is the site gone, moved to a new domain or just broken?

**Comment by ilike2burnthing** [comment]
Unconfirmed explanation about the drama behind the scenes - https://torrentinvites.org/f23/sorry-see-torrentdb-go-what-happened-what-should-u-do-next-610473/

Post from a mod 2wks ago - https://i.imgur.com/oDw6E0Z.png

If it gets to 30 days and there's no signs of life, it's probably not coming back.

**Comment by garfield69** [comment]
v0.20.2225
