### ISSUE TITLE
[eztv] Exception (eztv): Ssl error:0f000078:elliptic curve routines:OPENSSL_internal:POINT_IS_NOT_ON_CURVE  at /spksrc/spk/mono/work-aarch64-6.1/mono-5.20.1.34/external/boringssl/crypto/ec/ec.c:835: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by mridude23** [Jackett/Jackett#8121]
### Environment

**OS**: Synology NAS DSM 6.2

**.Net Runtime**: Mono 

**.Net Version**: 5.20.1.34 

**Jackett Version**: 0.14.485

**Last Working Jackett Version**: previous one (it might have been 0.12, not sure on this one)

**Are you using a proxy or VPN?** no

### Description

Saw in Sonarr that there's a new version available for Mono and it was saying that my version (I'm gonna say 5.18, I think this one was the previous one) is no longer supported. Updated Mono to 5.20 then Jackett to 0.14. After the update Jackett refuses to work with any of my 3 indexers (2 public, 1 private). Sonarr v3 is still working. 

I removed Mono, Jackett and Sonar and reinstalled the previous packages I could find here https://synocommunity.com/packages for Mono and Jackett (I think these are not actually the previous packages, at least for Jackett; can't say for sure). Still not working. Tried a mix of Mono 5.20 and Jackett 0.11, still does not work. Tried latest Jacket with previous Mono, it makes me update to the latest Mono as well. 
Right now I don't know what to try and I'm left with nothing working :)
Any ideas?

### Logged Error Messages

> An error occured while testing this indexer
> Exception (eztv): Ssl error:0f000078:elliptic curve routines:OPENSSL_internal:POINT_IS_NOT_ON_CURVE at /spksrc/spk/mono/work-aarch64-6.1/mono-5.20.1.34/external/boringssl/crypto/ec/ec.c:835: An error occurred while sending the request

### Screenshots

![jackett_error](https://user-images.githubusercontent.com/35563212/79017004-fed6bf80-7b78-11ea-925a-015c77b5b3d4.png)

**Comment by ilike2burnthing** [comment]
The solution provided [here](https://github.com/Jackett/Jackett/issues/2173) and [elsewhere](https://www.google.com/search?q=Ssl+error%3A0f000078%3Aelliptic+curve+routines%3AOPENSSL_internal%3APOINT_IS_NOT_ON_CURVE) is to downgrade your installed mono version.

Given that this doesn't seem to be an option for you, the next recommendation is to uninstall the packages (mono, jackett, sonarr, etc.) and reinstall them using Docker (which should hopefully be available for your NAS in [DSM's repository](https://www.synology.com/dsm/packages/Docker)).

Up to you if you want to backup your settings or start from scratch.

**Comment by mridude23** [comment]
Unfortunately Docker is not an option. Closing as it seems only Mono is to blame.
