### ISSUE TITLE
v0.12 to v0.14 upgrade failed: Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime'. The located assembly's manifest definition does not match the assembly reference.

### ISSUE THREAD

**Issue by nSpecter** [Jackett/Jackett#8123]
**OS**: 
Ubuntu\** 18.04.4 LTS
Linux 4.15.0-96-generic (x86_64) - #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020

**.Net Runtime**: 
Mono JIT compiler version 6.8.0.105

**Jackett Version**:
Upgrading from v0.12.1470 to v0.14.501

**Last Working Jackett Version**:
v0.12.1470

**Are you using a proxy or VPN?**
No

### Description
Prompted in GUI to upgrade, selected option to do so. Jackett did not come back up.
Rebooted. Jackett service does not start.

### Logged Error Messages
**Jackett:**
2020-04-10 12:10:12.6101 Info New release found. Current: v0.12.1470 New: v0.14.501 
2020-04-10 12:10:12.6101 Info Downloading release v0.14.501 It could take a while... 
2020-04-10 12:11:02.1627 Info Found 100 (43 new) releases from RARBG 
2020-04-10 12:11:16.3129 Info Starting updater: /tmp/JackettUpdate-v0.14.501-637221174693755108/Jackett/JackettUpdater --Path "/opt/jackett" --Type "Console" --Args " --NoRestart" --KillPids "839" --NoRestart 
2020-04-10 12:11:16.3579 Info Updater started process id: 18505 
2020-04-10 12:11:19.2076 Info Found 50 (3 new) releases from EZTV 

*No further log entries since upgrade.*

**Syslog:**
Apr 10 13:12:37 HTPC systemd[1]: Started Jackett Daemon.
Apr 10 13:12:37 HTPC jackett[21761]: Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=[REDACTED]'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
Apr 10 13:12:37 HTPC jackett[21761]: File name: 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=[REDACTED]'
Apr 10 13:12:37 HTPC systemd[1]: jackett.service: Main process exited, code=dumped, status=6/ABRT
Apr 10 13:12:37 HTPC systemd[1]: jackett.service: Failed with result 'core-dump'.
Apr 10 13:12:43 HTPC systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
Apr 10 13:12:43 HTPC systemd[1]: jackett.service: Scheduled restart job, restart counter is at 551.
Apr 10 13:12:43 HTPC systemd[1]: Stopped Jackett Daemon.

**Systemctl:**
jackett.service - Jackett Daemon
   Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: 
   Active: activating (auto-restart) (Result: core-dump) since Fri 2020-04-10 12
  Process: 14490 ExecStart=/opt/jackett/jackett --NoRestart (code=dumped, signal
 Main PID: 14490 (code=dumped, signal=ABRT)

Apr 10 12:52:59 HTPC systemd[1]: jackett.service: Main process exited, code=dump
Apr 10 12:52:59 HTPC systemd[1]: jackett.service: Failed with result 'core-dump'
Apr 10 12:53:04 HTPC systemd[1]: jackett.service: Service hold-off time over, sc
Apr 10 12:53:04 HTPC systemd[1]: jackett.service: Scheduled restart job, restart
Apr 10 12:53:04 HTPC systemd[1]: Stopped Jackett Daemon.
Apr 10 12:53:04 HTPC systemd[1]: Started Jackett Daemon.
Apr 10 12:53:04 HTPC jackett[14532]: Unhandled exception. System.IO.FileLoadExce
Apr 10 12:53:04 HTPC jackett[14532]: File name: 'System.Runtime, Version=4.2.2.0
Apr 10 12:53:05 HTPC systemd[1]: jackett.service: Main process exited, code=dump
Apr 10 12:53:05 HTPC systemd[1]: jackett.service: Failed with result 'core-dump'

**Comment by garfield69** [comment]
you most likely have been caught by an old 0.12.* updater bug, which while fixed in Oct 2019 0.12.879, did however require you to update the systemd install script manually, so that the systemd launcher could prevent the jackett updater and the jackett service from being active at the same time, and prevent the two tasks interfering with each other with locked files blocking the updater.

so the way out for you now, is to manually update from the latest jackett amdx64 build from https://github.com/Jackett/Jackett/releases/latest by following the installation instructions from https://github.com/Jackett/Jackett#install-on-linux-amdx64
and in particular, make sure you install_service_systemd.sh script run.
let me know how you go.

**Comment by nSpecter** [comment]
Thanks! 

I'll update when done.

**Comment by nSpecter** [comment]
That appears to have done the trick. Thanks again, Gar. \*thumbs-up\*

**For future intrepid explorers, here's what I did:**

Downloaded the latest binaries gzip to a Temp folder
Decompressed the gzip file, which resulted in a Jackett folder of shtuff
Opened a terminal window
Grabbed root privileges ("Sudo su" on Lubuntu)
cd /home/myusername/Temp
cp -v ./Jackett/* /opt/jackett
cd /opt/jackett
./install_service_systemd.sh (note the leading ./)
systemctl status jackett

Confirmed service is up and running. 

Violin! :D
