### ISSUE TITLE
[YourBittorrent] Found no results while trying to browse this tracker - Category seems to have moved

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8124]
v0.14.501.0 Docker and Sandbox, also checked earlier versions to make sure it wasn't a recent change (problem just started today). VPN/proxy used for all, no VPN/proxy also used for .host

Logs show search for 'cats' and then a test:
[log- .com.txt](https://github.com/Jackett/Jackett/files/4463423/log-.com.txt)
[log - 2.com.txt](https://github.com/Jackett/Jackett/files/4463422/log.-.2.com.txt)
[log - .host.txt](https://github.com/Jackett/Jackett/files/4463421/log.-.host.txt)

.com and 2.com both have `Error while parsing field=category`, all three have `Could not find a value in the request with name 'Category'`

**Comment by garfield69** [comment]
Jackett v0.14.541
