### ISSUE TITLE
[DivxTotal] clicking configuration after a failed test leads to blank page with plain text

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8125]
v0.14.501.0 Docker, but also happened a few weeks ago and I couldn't replicate it until now.

If DivxTotal fails a test (for me it was because of https://github.com/Jackett/Jackett/issues/7325), and then I try to click its config button, the page blanks out with one of the lines below in plain text:
```
- Las mejores series y peliculas en una plataforma.
- Para los amantes de las películas.
- Películas y Series Torrent en HD.
- La web numero #1 de Torrents en España.
```
It doesn't open a new tab or open a link in the current one (i.e. Jackett), it just replaces Jackett. I have to refresh to get back to Jackett, clicking the browser's back button brings me to whatever I was on before Jackett. No log entry is created, even with enhanced logging enabled.

If I remove the VPN/proxy, apply, and then click DivxTotal's config button, it does the same thing. The issue isn't resolved until I run a successful test, then I can open the config without issue.

I'm assuming it's because of the error recorded in the .json (extension changed to allow uploading to GH):
[divxtotal.txt](https://github.com/Jackett/Jackett/files/4463835/divxtotal.txt)

Not sure if this is DivxTotal specific, or a formatting issue with the .json template, but it's the only one I have come across.

**Comment by ilike2burnthing** [comment]
@ngosang if you get a sec, can you have a look at this? Thanks!

**Comment by ngosang** [comment]
I can't reproduce this error. The tracker is working well for me. I see there is a Cloudflare error in your log but it doesn't give clues.
Try to remove the tracker and add it again.

**Comment by ilike2burnthing** [comment]
Is it possible to transplant the .json I uploaded into your own setup and test it?

I also managed to make this (orange spinny circle thing) happen with a quick edit (read: deleting half of it to see what would happen) - [divxtotal.json.txt](https://github.com/Jackett/Jackett/files/4488355/divxtotal.json.txt)
![divxtotal](https://user-images.githubusercontent.com/59480337/79478485-6078ad00-8003-11ea-9ced-ade493cec69d.png)

Stripping < and > from the .json stops the problem. Could that be automated?

**Comment by cadatoiva** [comment]
Is there anything in your Jackett logs about the issue?

**Comment by ilike2burnthing** [comment]
Nope, annoyingly not. Turned on enhanced logging as well, didn't get a single line.

**Comment by ilike2burnthing** [comment]
Apologies, I hadn't tried enhanced logging with that second .json file. It records something at least, though I don't know if it's at all helpful. It starts at the moment I click the configuration button - [log - DivxTotal.txt](https://github.com/Jackett/Jackett/files/4490049/log.-.DivxTotal.txt)

**Comment by ngosang** [comment]
> Is it possible to transplant the .json I uploaded into your own setup and test it?

No is not.

I think the issue is that the error message contains HTML code that breaks the Jackett UI when it's displayed. We should sanitize/escape the HTML in the WebUI to avoif this kind of problems but with the current codebase it can be difficult. There are to many places to touch.

**Comment by garfield69** [comment]
v0.20.912
