### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Got redirected to another domain. Try changing the indexer URL to https://thepiratebay.org/. Updated site link, please try again.: Parse error (Test)

### ISSUE THREAD

**Issue by mattispantone81** [Jackett/Jackett#8129]
### Environment

**OS**: Unraid 6.8.1
**Jackett Version**:  0.14.501.0

**Last Working Jackett Version**: ?

**Are you using a proxy or VPN?** Yes - PIA

### Description

When performing a test of "The Pirate Bay" torrent site and error appears (below)
### Logged Error Messages

An error occurred while testing this indexer
Exception (thepiratebay): Got redirected to another domain. Try changing the indexer URL to http://thepiratebay.org/. Updated site link, please try again.: Parse error

### Screenshots

<img width="486" alt="Screen Shot 2020-04-11 at 4 58 19 pm" src="https://user-images.githubusercontent.com/20289796/79037573-bc16f500-7c15-11ea-82d9-a6b5b71dac5b.png">

**Comment by garfield69** [comment]
Ah yes, saw an article on TF earlier, https://torrentfreak.com/pirate-bay-no-longer-uses-cloudflare-visitors-sent-to-black-hole200410/
but forgot to fix the indexer when I go sidetracked with covid19 news, house chores and lunch. 
will implement an update, thanks for the reminder.

**Comment by mattispantone81** [comment]
Seems to be ok if I switch over to an alternate though. FYI. Sorry should have mentioned that.

**Comment by garfield69** [comment]
thats right.
this is because while TPB https official .org domain is broken, the site is still able to be access with its onion domain on TOR.
the alternate domains we added to the indexer all fetch their updates from that site so that is why you can still get magnets from TPB.

**Comment by garfield69** [comment]
Jackett v0.14.541
