### ISSUE TITLE
[Enhancement] Allow users to select specific trackers for Manual Search

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#813]
For Manual Search, Jackett allows users to either search one configured tracker, or all of them, but it doesn't provide the option to select specific trackers to search. I think this would be a handy feature - checkboxes might be a good idea in this case. 

This might fit in nicely with the revamped interface.

**Comment by armani316** [comment]
Are there plans to implement this in the future?

**Comment by kaso17** [comment]
definitly, most likely together with grouping (#921)

**Comment by armani316** [comment]
Related to #661

**Comment by adamwinn** [comment]
This has been added now, right?

**Comment by kaso17** [comment]
yes, added via 00027a41c1471a9c6a8ecd004b51a8869610c962
