### ISSUE TITLE
[ztracker] Error: Hiba: Hibás felhasználónév vagy jelszó! Kérem győződj meg a helyességükől vagy próbáljd a jelszóemlékeztetőt.Még [2014] alkalommal próbálkozhatsz. (Config)

### ISSUE THREAD

**Issue by BLACK-FOX** [Jackett/Jackett#8132]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by BLACK-FOX** [comment]
![Снимок](https://user-images.githubusercontent.com/13501984/79046982-4199a580-7c14-11ea-864c-c4748e2ab88b.JPG)

**Comment by BLACK-FOX** [comment]
Not included but an account  
 Потребител: BLACKFOXpro
    Парола:  zB8aXmzXf7

**Comment by garfield69** [comment]
The Jackett ztracker indexer works for me with my credentials, therefore the problem is external to Jackett.

Your credentials are not correct and therefore either your username or password is in error.
follow the guide at https://github.com/Jackett/Jackett/wiki/TroubleShooting#401-unauthorized-check-your-credentials
