### ISSUE TITLE
[AsianCinema] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8134]
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.14.541

**Last Working Jackett Version**: 0.14.501

**Are you using a proxy or VPN?** No

### Description

I'm unable to search AsianCinema. It fails the test and returns 0 results for all search queries. 

### Logged Error Messages

`An error occurred while testing this indexer`
`Found no results while trying to browse this tracker`

Enhanced log:
[log.txt](https://github.com/Jackett/Jackett/files/4464872/log.txt)

### Screenshots
Not needed

**Comment by garfield69** [comment]
asiancinema have upgraded from unit3d 1.9.3 -> 2.2.7 necessitating the indexer to be updated.

**Comment by garfield69** [comment]
Jackett 0.15.5

**Comment by handokota** [comment]
AsianCinema has upgraded UNIT3D to the latest version.

**Comment by garfield69** [comment]
Thanks. I'll update the indexer.

**Comment by garfield69** [comment]
v0.24.1178
