### ISSUE TITLE
[1337x] [RSS] Entries for Items with long titles are warped (cut short) in the feed.

### ISSUE THREAD

**Issue by PaulinoRBJ** [Jackett/Jackett#8137]
### Environment

**OS**: Windows 10

**Jackett Version**: 0.14.485.0

**Last Working Jackett Version**: N/A

### Description
1337x warps long titles, for example on [this](https://1337x.to/torrent/4402328/My-Own-Private-Idaho-1991-Criterion-1080p-BluRay-x265-HEVC-10bit-AAC-5-1-Tigole-QxR/) page, on the torrent page's infobox. Jackett's RSS feed currently inherits this problem, causing problems with filtering the RSS feed and viewing it. A simple solution would be to use other tags in the torrent page source (which reference the complete torrent name) as the RSS item title. The torrent page's header title. for example, has the complete torrent name along with some fixed keywords that can be filtered out before use by the feed. 

Also noteworthy that this behavior is not observed when I use a query term in the RSS URL, in which case the full title is correctly displayed as it's meant to be.

### Screenshots

1. Warped title on a 1337x torrent page:
![Example](https://i.ibb.co/4dW2TkD/image.png)
 
2. Warped entry title in Jackett's RSS feed for 1337x:
![Example](https://i.ibb.co/YWv58MD/image.png)

**Comment by garfield69** [comment]
this occurs because the indexer fetches from the web site the first pages of each of the movies, tv and music categories when a **keywordless** search is used, and these pages abbreviate the title
```html
<tr>
    <td class="coll-1 name">
        <a href="/sub/42/0/" class="icon">
            <i class="flaticon-hd"></i>
        </a>
        <a href="/torrent/4403373/Patterns-of-Evidence-The-Moses-Controversy-2019-720p-AMZN-WEBRip-800MB-x264-GalaxyRG/">Patterns.of.Evidence.The.Moses.Controversy.2019.720p.AMZN.WEBRip.800MB.x264-Gala...</a>
    </td>
    <td class="coll-2 seeds">0</td>
    <td class="coll-3 leeches">0</td>
    <td class="coll-date">5:01am</td>
    <td class="coll-4 size mob-vip">
        798.2 MB<span class="seeds">0</span>
    </td>
    <td class="coll-5 vip">
        <a href="/user/mazemaze16/">mazemaze16</a>
    </td>
</tr>
```
whereas a **keyword** search invokes the site's search engine which always presents the full title.
```html
<tr>
	<td class="coll-1 name">
		<a href="/sub/4/0/" class="icon">
			<i class="flaticon-video-dual-sound"></i>
		</a>
		<a href="/torrent/3281668/Herbie-Goes-To-Monte-Carlo-1977-x264-720p-Esub-BluRay-Dual-Audio-English-Hindi-GOPISAHI/">Herbie Goes To Monte Carlo 1977 x264 720p Esub BluRay Dual Audio English Hindi GOPISAHI</a>
	</td>
	<td class="coll-2 seeds">5</td>
	<td class="coll-3 leeches">2</td>
	<td class="coll-date">Oct. 8th '18</td>
	<td class="coll-4 size mob-uploader">
		843.5 MB<span class="seeds">5</span>
	</td>
	<td class="coll-5 uploader">
		<a href="/user/PENDUDESI/">PENDUDESI</a>
	</td>
</tr>
```

we are not going to fetch the details page of every search results in order to provide a full title, that would generate up to 100 additional http get request to the web site which is undesirable.

on all the returned pages, the only other selector that has the full title, albeit in a url-encoded string, is the **href** itself.
I suppose I can strip and clean up the href for use as the title.
let me see what I can do.

**Comment by garfield69** [comment]
Jackett 0.15.5

**Comment by PaulinoRBJ** [comment]
Wonderful, I was aware the href's have them in full but didn't consider them and that we don't fetch the item pages! Thanks a bunch for the quick fix @garfield69!

**Comment by cadatoiva** [comment]
@garfield69 there's a `urldecode` filter you can apply to decode the string after pulling it out.
