### ISSUE TITLE
[enhancement] change disabling proxy to - Proxy type: None (disabled)

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8138]
Rather than removing the proxy URL to disable it (which is then a minor annoyance to retype each time you want to re-enable, more so if only certain ones work), is it possible to add `None (disabled)` to `Proxy type` as a simple off switch?

Thanks!

**Comment by cadatoiva** [comment]
I'll look into this when I can get back to the major overhaul of the web engine.
