### ISSUE TITLE
[New Tracker REQ] Nostre.am

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#814]
**Indexer Name**
Nostre.am

**Type**
Music

**Indexer URL**
https://nostre.am/

**Indexer language**
English

**Invite**
Sent to -removed- :)

**Comment by kaso17** [comment]
got the invite, I heard a lot of bad things about this one. I'll add it anyway.

**Comment by armani316** [comment]
@kaso17 I think they got off to a bad start when they got hacked and their user info got leaked. They've tightened their security ever since.

**Comment by kaso17** [comment]
Fixed with 49fd078a4c3ab846c134cb6392412ab0d8195461

**Comment by armani316** [comment]
Looks like Nostre.am has been hacked. It now redirects to PassTheHeaphones,me, and it may be gone for good. It might make sense to remove it in a few days if things don't go back to normal.

**Comment by kaso17** [comment]
As the siteop already stated he won't restore the backup I've removed with with 1215548b31bb348ab0761c79679be22eb0a39b2f

**Comment by armani316** [comment]
So Nostre.am is back now under new ownership. Hope it doesn't get hacked again. Is it possible to add it back to Jackett?

**Comment by kaso17** [comment]
readded with 99c0de285e853151fd24523ece916a0108573b8e

**Comment by armani316** [comment]
@kaso17 Gone for good.

**Comment by kaso17** [comment]
removed via 53a1161dda388a9722b01870076e48d79bc06add
