### ISSUE TITLE
solidtorrents: the tracker seems to be down

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8149]
https://solidtorrents.net/
Tested in https://www.uptrends.com/tools/uptime

**Comment by ilike2burnthing** [comment]
Back up

**Comment by garfield69** [comment]
down with bad gateway
![image](https://user-images.githubusercontent.com/6933240/81023472-a0c1a180-8ec4-11ea-8080-68ca624ab99e.png)

**Comment by ilike2burnthing** [comment]
back again

**Comment by AARON8888** [comment]
Site is down.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/4751#issuecomment-1868238489
