### ISSUE TITLE
[req] TREc

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#8155]
TREc.to is a Russian Semi-Private Torrent Tracker for BOOKS / E-LEARNING

http://trec.to/

**Comment by garfield69** [comment]
site has been returning http error 500 (internal server error) for the last 2 days now so I cannot work in this indexer.

**Comment by garfield69** [comment]
now returning 
```
Could not connect to the server
```

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
bah. the act of login in generates 
![image](https://user-images.githubusercontent.com/6933240/81013533-639ee480-8eaf-11ea-9fbe-43908eba6fd0.png)

forget it.
