### ISSUE TITLE
Can't add tracker

### ISSUE THREAD

**Issue by sreusr** [Jackett/Jackett#8156]
**OS**: Linux

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.15.5.0 

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?** no

### Description

Adding an indexer doesn't put it into the list, just closes the view.

### Logged Error Messages

None

**Comment by ilike2burnthing** [comment]
Does this affect all trackers or one/some specifically? If the latter, which one/s?

Have you enabled enhanced logging?

**Comment by sreusr** [comment]
just updated, works again with version 0.16.18.0
