### ISSUE TITLE
[PassThePopcorn] Show Missing Release Tags/Information

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8157]
PTP returns results in Jackett by displaying the filename/release name followed by relevant release tags/information between square brackets. For example:

`Avengers.​Endgame.​2019.​UHD.​BluRay.​2160p.​HEVC.​Atmos.​TrueHD7.​1-​CHDBits` 
`[2160p /​ Blu-​ray /​ BD66 /​ m2ts /​ Checked]`

However, Jackett does not return all relevant release tags that are shown on PTP's website. While I understand that not all tags should be returned (e.g. `Trumpable`), I believe most of the currently omitted tags should ideally be shown in Jackett.  

The reason why I think this is important is because I imagine a lot of users do post-search filtering in Jackett using specific keywords. If these keywords aren't shown, either as part of the release name or the tags, relevant releases may be omitted from the filtered results. Moreover, I believe the experience of searching in Jackett should be as close as possible to that of searching the tracker's website, so if important information is shown as part of the release name on the website, it should also be shown in Jackett, especially if the API supports it. 

I understand that the argument against displaying such tags could be that there is no need to show them since they are already part of the filename, in which case it would be redundant. While I somewhat agree with this logic, we can't always depend on the accuracy of the filenames. Also, not all of these tags are standard parts of filenames, so showing them in Jackett would save users the effort of having to view the full release tags on the website. Additionally, I don't see the logic behind showing some tags (e.g. `BD66 /​ m2ts /​ Checked`) and not others.

I noticed this particular issue when I was searching multiple trackers for `As Good As It Gets 'tt0119822'`. I filtered in Jackett using the word 'REMUX' and the filtered results didn't include anything from PTP which surprised me. That was because despite the fact that the word REMUX is a standard part of Remux release names, this particular filename `As Good as It Gets (1997).mkv` did not include it, so the relevant search result from PTP was omitted. If the `Remux` tag was shown in Jackett, this issue wouldn't have happened. 

PTP's upload page includes a list of standard/most common tags. Here's a screenshot of this list:

![image](https://user-images.githubusercontent.com/23747425/79080057-cfdb5d80-7ce0-11ea-998e-5ce3cc84a958.png)

This is not a complete list by any means (e.g. it does not include `IMAX Version` which should be shown in Jackett), but at the very least, I think Jackett should display most, if not all of them.

Thoughts?

**Comment by garfield69** [comment]
I don't have a PTP a/c so I cannot comment with any authority right now.

what would be useful, is to see the HTML from the PTP website, so we can see what is actually available in the row that PTP presents for search results.

I am aware of many sites where what appears to be tags in the **title** turns out to be just a display trick, where the title actually comprises just the name of the series and episode, and the tags are a separate field in the row, and presented (aligned) by the website as if they were part of the title.
Then it turns out that if you try to search with those tags thinking they are part of the title, you discover you get no results, because usually the website has a separate search field for tags separate from title-only searches.
Since the Jackett indexer cannot distinguish a tag from part of a title in one query, this is problematic. And trying to keep an indexer up to date with potentially ever changing/additional tags is an overhead no one wants to get involved with maintaining.

That is why seeing the HTML will allow us to make an informed decision on what is possible with regard to what you have raised with the PTP indexer.

**Comment by RoloSoze** [comment]
@garfield69 Let me share some relevant parts of the HTML rather than the whole page, since the code is full of private information, and I can't ensure redacting it all.

Here's a partial screenshot of the search results for Black Panther on PTP's website
![image](https://user-images.githubusercontent.com/23747425/79085613-3ffcda00-7d07-11ea-9e5d-30ff55f68adf.png)

Take a look at the 7th result with the following tags:
` H.264 / MKV / Blu-ray / 1080p / Remux / 2D/3D Edition / Dolby Atmos / IMAX Version`

Here's what that result looks like in Jackett:
![image](https://user-images.githubusercontent.com/23747425/79086120-ec8b8b80-7d08-11ea-81c0-c0ad897fe055.png)

Here's what the HTML code for that row looks like:
`<a href="#" onclick="$jq('#torrent_569582').ToggleHC(); show_description('172976', '569582'); return false;" class="torrent-info-link">H.264 / MKV / Blu-ray / 1080p / Remux / 2D/3D Edition / Dolby Atmos / IMAX Version</a>`

So all the tags are right there but Jackett displays the first 4 and omits the latter 4. I don't know if this was an implementation choice or an API restriction.

**Comment by garfield69** [comment]
here is the relevant indexer section, its fairly straight forward
https://github.com/Jackett/Jackett/blob/5ce1907da10f5997009f4dcf538fcbe0353575be/src/Jackett.Common/Indexers/PassThePopcorn.cs#L122-L240

**Comment by RoloSoze** [comment]
I can see that the defined variables are quality, container, codec, resolution, and source, which are the standard ones that are returned currently for all results. In addition, it also shows whether the torrent is a 'Scene' release, has been 'Checked' by staff, or is a 'Golden Popcorn' release. 

What I do not know is whether additional variables can be defined to show all other relevant tags that are not currently being shown in Jackett.

**Comment by garfield69** [comment]
to answer that question I would need access to an account so I can run the indexer in my visual studio 2019 c# in debug mode and dump the returned jsResults to see what additional data is there.
or you can wait for @cadatoiva to do it when he has some free time from his current workload, as he has an a/c

**Comment by cadatoiva** [comment]
We don't use the HTML, we use the API for PTP. To see what's available, add `&json=noredirect` to the end of a search url in your browser. Pretty sure the tags that are missing aren't available in the API in a useful way to get, but I can check later.

**Comment by RoloSoze** [comment]
> add `&json=noredirect` to the end of a search url in your browser.

I just did that and I'm getting the exact same page with no changes at all. Everything is displayed the exact same way.

**Comment by cadatoiva** [comment]
Huh, it's working for me.
![image](https://user-images.githubusercontent.com/2086652/79089529-12fef600-7d0c-11ea-8e04-c488caa53010.png)

**Comment by RoloSoze** [comment]
Ah, now I know was I was doing wrong. I was searching so specifically that it was taking me straight to the movie's homepage as opposed to the search page. 

So yes, the tags I was asking for are all under one variable `RemasterTitle` - I guess the implementation is easier than I thought!

**Comment by cadatoiva** [comment]
Ok, so we're missing `RemasterTitle` in the tags. Are there any tags in `RemasterTitle` that we **don't** want and would need to be filtered/removed (i.e. Trumpable)?

**Comment by RoloSoze** [comment]
> 
> 
> Ok, so we're missing `RemasterTitle` in the tags. Are there any tags in `RemasterTitle` that we **don't** want and would need to be filtered/removed (i.e. Trumpable)?

No, they're all relevant. Lucky for us, the 'Trumpable' tag is not included in `RemasterTitle` and does not even appear anywhere in the code.

**Comment by garfield69** [comment]
Jackett 0.15.36

**Comment by RoloSoze** [comment]
Works well! Thanks!
