### ISSUE TITLE
Happy Birthday Jackett!

### ISSUE THREAD

**Issue by cadatoiva** [Jackett/Jackett#8160]
Jackett is 5 years old today. Thanks to everyone who made this possible!
![image](https://user-images.githubusercontent.com/2086652/79090244-9cafc300-7d0e-11ea-9fe6-3099b9d8fd15.png)

**Comment by RoloSoze** [comment]
A HUGE shout-out to @kaso17 @garfield69 @ngosang @cadatoiva - and every single person who has ever contributed to this project - for all the insanely hard work they have put into it! Jackett has come a long with, and it would not have been possible without you guys.

THANK YOU! 🥇

**Comment by ngosang** [comment]
:1st_place_medal:

**Comment by ilike2burnthing** [comment]
🍰

**Comment by ilike2burnthing** [comment]
Rolo, lets not forget about the unsung hero of this community, @jackettbot

60% of the time, it works every time!

**Comment by ngosang** [comment]
@jackettbot the third. There have been several casualties along the way. :smile:

**Comment by ilike2burnthing** [comment]
And I thank them for their sacrifices

**Comment by garfield69** [comment]
I am a bit late to the party, but Happy Birthday Jackett 🍾 

Also a big thank you from me goes out to the many contributors, but especially  to @ngosang  and @cadatoiva  for injecting a much needed burst of enthusiasm and activity that has revived Jackett again.
And a special mention to long time activist @RoloSoze for continuing to push buttons  ;-)
👍

**Comment by onlytanmoy** [comment]
Belated happy birthday Jackett 🎂🎉😊
