### ISSUE TITLE
[FileList] Change Site Link

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8161]
**Announcement from FileList:**

As some of you may have already noticed the announce domain for the tracker has changed into filelist.io. Also, the option to enable SSL for the tracker has been added to the profile page.

The next phase will be migrating everything to filelist.io.

That's why, starting 1st of May 2020 the filelist.ro and flro.org domains will start redirecting to filelist.io. Both of those domains will remain active and redirecting until they expire, however as of this moment you can consider filelist.io being the only domain FileList has.

**Comment by garfield69** [comment]
Jackett 0.15.36
