### ISSUE TITLE
tracker: magico.one problem search results

### ISSUE THREAD

**Issue by vlevas** [Jackett/Jackett#8171]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: ubuntu 18.04 docker version of jackett

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Jackett Version 0.15.36.0

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?** [yes/no] no

### Description

I remove and re-add the tracker it logins after i try to search for a result it says (0 no results) but also in all searches says that.. on rss i can see the retrieved torrents and its ok.. but on search is like a broken without any error

### Logged Error Messages

Manual search for "game of thrones" on magico with 0 results.
--

Manual search for "Succession  HDTV" on magico with 0 results.

http://prntscr.com/rycv6d

### Screenshots

http://prntscr.com/rycrb9
http://prntscr.com/ryct0h

http://prntscr.com/ryctkf
http://prntscr.com/rycu21

**Comment by garfield69** [comment]
It is likely that Magico have changed the results page on their web site and the Jackett indexer just needs an update to pick the correct selectors.

Unfortunately none of the team have an account on Magico so we cannot easily fix this.
If you send an invite to garfieldsixtynine -at- gmail.com I can sort this out fairly quickly.

If not, then the next best thing is for you to provide an **enhanced** log, which will contain the html returned from magico in response to the Jackett query, and should help determine what needs changing.
https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by vlevas** [comment]
thanks for reply @garfield69 at this moment signups are open..

**Comment by garfield69** [comment]
Excellent.
So I have registered and logged in successfully.

**Comment by garfield69** [comment]
found the issue. the search wildcard needed adjusting. 
The fix should be included in the next release due in about a couple hours.

**Comment by garfield69** [comment]
Jackett 0.16.7

**Comment by vlevas** [comment]
awesome thanks for this!!!!! :D
