### ISSUE TITLE
[extratorrent-cd] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Dispose1966** [Jackett/Jackett#8172]
### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 

**Jackett Version**: 0.14.447.0

**Last Working Jackett Version**: Unknown

**Are you using a proxy or VPN?** [yes/no] Tried both with and without

### Description

1. Tried all available Site Links
2. Tried deleting and re-adding

### Screenshots

![image](https://user-images.githubusercontent.com/63589870/79117724-31a4d180-7d8c-11ea-8ba9-e905ef6ae9de.png)

**Comment by ilike2burnthing** [comment]
Update to latest version, currently v0.15.36

Try extratorrent.si again, in Jackett and browser. Both are working here, so it may have been a temporary issue.

The unblockit.one proxy shows an empty page when using `/search/?search=` but is fine with a keyword search. I'll keep an eye on that, hopefully it gets resolved.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/8186
