### ISSUE TITLE
[torrent-turk] Exception (torrent-turk): Login failed: No form found on https://torrent-turk.de/?p=home

### ISSUE THREAD

**Issue by bingoxo** [Jackett/Jackett#8176]
log : https://bin.privacytools.io/?139409e361838edd#PCSpQjaix/bMsP7H8dpWj4s/7NYqFVCS52azkqRASSg=

**Comment by garfield69** [comment]
I am able to use my torrent-turk indexer without issues, so this suggest the problem is external to Jackett.
Is this the first time you are setting up this indexer, or was it working for you previously?

**Comment by bingoxo** [comment]
working now , closing

**Comment by garfield69** [comment]
Seeing from this indexer today
```
Exception (torrent-turk): Login failed: No form found on https://torrent-turk.de/?p=home&pid=1 using form selector form#loginbox_form: Parse error
```

Accessing the web site directly presents
![image](https://user-images.githubusercontent.com/6933240/97065094-94aed500-1607-11eb-8d1d-75e4111f2dd2.png)
which looks like the web development page for a host service

@bingoxo  @bpikap
is it just me or is the site gone, broken, moved to a new domain?

**Comment by ilike2burnthing** [comment]
Seems to be back up, but I don't have an account to login.

**Comment by garfield69** [comment]
@ilike2burnthing  I am still seeing the plesk login, are you getting something different?

**Comment by ilike2burnthing** [comment]
![turk](https://user-images.githubusercontent.com/59480337/97067349-65bb4380-15b4-11eb-81ff-0400d1fa349c.png)

I can navigate through the site as well.

**Comment by garfield69** [comment]
Thanks for the info.
I enabled a VPN  and now I can see the site too.
