### ISSUE TITLE
NordicBits Issues: Extra leading space | IMDb ID search implementation | Search discrepancies

### ISSUE THREAD

**Issue by best-74** [Jackett/Jackett#8178]
- [ ] The search results returned from Jackett has an added "space" / empty character before the actual search result. This sometimes confuses further processing of the result. 

Here's an example...

![image](https://user-images.githubusercontent.com/49064677/79143936-5fa30980-7dbe-11ea-8e09-b013add2f38b.png)

***
@RoloSoze Edit:

I was actually going to open a new ticket for NordicBits just now, but since you opened one, I'll add a couple more issues:

- [ ] Searching with the IMDb ID in NordicBits is the same as doing an empty string search - It returns the last 100 torrents. It needs to be configured correctly - https://github.com/Jackett/Jackett/issues/4859#issuecomment-613002060

- [ ] I tried searching for 'Avengers' in Jackett - Got 36 results (including some dead torrents). Searching NordicBits' website using the same word returns 40 results. It appears that Jackett returns some but not all dead torrents, probably depending on the category. However, I'm not entirely sure that this is the only issue, but that's what I found through a series of tests.

**Comment by RoloSoze** [comment]
Just searched multiple indexers using the IMDb ID and NordicBits spammed the results with 100 unrelated releases, all of which have a leading space 👎 This needs serious attention. I have a spare invite if a C# developer is willing to work on these issues.

**Comment by garfield69** [comment]
invites should not be required, both c# devs and I have a/c on this site.
you also assigned ngosang so now you just have to wait for him to free up time to investigate.

**Comment by RoloSoze** [comment]
Resolved with #8343. Thanks, @ngosang!

**Comment by garfield69** [comment]
Jackett 0.16.127

**Comment by best-74** [comment]
Thanks, working perfect now
