### ISSUE TITLE
[New Tracker REQ] NotWhat.CD

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#818]
Indexer Name
NotWhat.CD

Type
Music

Indexer URL
https://notwhat.cd/

Indexer language
English

Invite
Open for applications through IRC channel:

IRC:
Server: irc.notwhat.cd
Port: 6697
SSL: On - Accept all certificates
Channel: #notwhat

Provide proof of what.cd membership, and you'll be invited

**Comment by kaso17** [comment]
IRC doesn't work for me:
```
* Connecting to irc.notwhat.cd (185.159.131.100:6697)
* Connected. Now logging in.
* Disconnected (Connection reset by peer)
```

**Comment by armani316** [comment]
@kaso17 Try using a VPN to change your location (I used Australia). Make sure SSL is on. I used http://kiwiirc.com as a client - Took a few tries, worked eventually.

**Comment by armani316** [comment]
@kaso17 Did it work?

**Comment by kaso17** [comment]
tried two different recruiters, never got an answer, they just ping timeouted, trying the next one

**Comment by kaso17** [comment]
got invited

**Comment by armani316** [comment]
Heads up: Looks like NoWhat.CD is about to introduce CloudFlare as well.

**Comment by kaso17** [comment]
Fixed with 3dfba7c2043630a0b113365a7358874326e9b9e2

**Comment by captainkyd** [comment]
'

**Comment by captainkyd** [comment]
they don't reply to the irc... it's a waste of time

**Comment by RoloSoze** [comment]
This has been down for a long time. Not sure if it's ever coming back up.

**Comment by garfield69** [comment]
v0.17.788
