### ISSUE TITLE
Problem of streaming on Stremio

### ISSUE THREAD

**Issue by chicungunya** [Jackett/Jackett#8181]
### Environment

**OS**: Android

**.Net Runtime**: [Mono]

**Jackett Version**: 0.15.36

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

Hello guys,
I answered on reddit (Darnaga) but nobody answered to me : https://www.reddit.com/r/StremioAddons/comments/fvurek/jackett_addon_streams_not_loading/
I use Stremio and Jackett with PMS on my Android TV with this guide : https://gist.github.com/sleeyax/e9635eb352a4fcdf94194f763d743689
All works but there is a problem with my private trackers (YGG, Torrentleech and IPTorrents)
Depend of movies but sometimes it works but sometimes not. I saw on reddit it might be problem of DHT.
I use Jacket in mono (cannot install the other version AMD64), is that a problem ? 
Anyway, do you have a solution for this problem of stream ? I did not find the setting to disable the DHT.
Thanks a lot

**Comment by garfield69** [comment]
The option the enable or disable DHT is not anything that has to do with Jackett.
Jackett is simply fetching the .torrent file from the web site that you are using Jackett to search, and saving the .torrent file to disk or passing it on to the torrent client via the OS file type launch app mechanism. Jackett does not examine the content of the .Torrent file and has no control over what the apps that call Jackett do with the .torrent file.

There are two methods to control DHT that I am aware of.
- One is directly on your torrent client that you are using to download the files that the .torrent file specifies. So for example, uTorrent or qBitTorrent will have a setting to disable DHT either on a per-torrent request basis or globally for all torrents.
- The second method is in the .torrent file itself, which can specify if DHT is allowed or not.
Once again, it is the torrent client that reads the .torrent file and actions the disabling of DHT if it find that setting in the .torrent file.

So there is nothing that Jackett can do for you.
