### ISSUE TITLE
[XtremeWrestlingTorrents] & [XtremeWrestlingTorrents-Classics] - Change HTTPS to HTTP

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8184]
I had to change the URLs for both XWT & XWT-C from HTTPS to HTTP to be able to configure & use them. @garfield69 Check it out at your end. Site Links may need to be changed if it's also the case for you.

**Comment by garfield69** [comment]
Jackett 0.16.7

**Comment by RoloSoze** [comment]
@garfield69 Looks like they now both support HTTPS again.
