### ISSUE TITLE
[yggcookie] Exception (yggcookie): Clearance failed after 30 attempt(s).: Clearance failed after 30 attempt(s). (Test)

### ISSUE THREAD

**Issue by Robilol** [Jackett/Jackett#8189]
### Environment

**OS**: Debian 9.12

**.Net Runtime**:  Mono

**.Net Version**: 4.6.2

**Jackett Version**: 0.16.7.0

**Last Working Jackett Version**: 0.16.7.0

**Are you using a proxy or VPN?** no

### Description

I've tried to add Yggcookie indexer with my cookie and my user-agent but when I test the connection, I got this error.

I have the same issue with Yggtorrent indexer.

### Logged Error Messages

```
Jackett.Common.IndexerException: Exception (yggcookie): Clearance failed after 30 attempt(s).
---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
```

**Comment by palalex38** [comment]
I also have the same problem with the both YGG indexers under Jackett version 0.16.7.0

**Comment by akatimike** [comment]
I also have the same problem :( with the both indexer and cookie try all i can and noting work stuck now :(

**Comment by garfield69** [comment]
@Robilol The Jackett 0.16.7 YGGCookie indexer works for me on win10, ubuntu18 and mojave macos.
 
So if you have entered the correct cookie and user-agent info and are still getting a challenge then this means that for some reason YGG is still not accepting your session.

The only difference between my three platform of jackett and yours, is that mine are all Jackett .net core versions, while you are apparently still using a mono dependent version of Jackett.

Are you sure you are using the mono version? restart your Jackett service and then view the log from the dashboard. one of the first lines should contain `Jackett variant:` and if it contains `Core<platform>` then you are not using mono.
if however you are really on a mono dependent Jackett, then its likely that this is an issue with mono, so see if you can upgrade your mono to the latest version and see if that helps.

The YGGTorrent indexer will work only for those users that are not getting a Cloudflare anti-DDoS challenge, but before you use it make sure that the SiteLink and SearchLink are correctly set as shown in https://github.com/Jackett/Jackett/issues/7095#issuecomment-582238746

IF you cannot get either indexers working then I am sorry I cannot help you further, the issue external to Jackett and nothing that Jackett can control :-(

**Comment by akatimike** [comment]
hi i tcheck all cookie and user agent and Still get the same error
Jackett variant: CoreLinuxAmdx64
Im not mono right ?

**Comment by garfield69** [comment]
@akatimike 
>Jackett variant: CoreLinuxAmdx64 Im not mono right ?

Correct, you are using the .net core version of Jackett.

>I think the IP got blacklisted.. should think to take vpn ? Or proxy?

that would seem the only alternative for you right now. try the free option of a VPN service like https://hide.me/ for instance.
