### ISSUE TITLE
How to hidden column "files" & "grabs"?

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#8191]
![image](https://user-images.githubusercontent.com/19517680/79235347-af083900-7e95-11ea-8aaf-3e7d042056f1.png)

**Comment by RoloSoze** [comment]
At the moment, this is not possible.

**Comment by RoloSoze** [comment]
@garfield69 @ngosang Does this go under `Won't Fix` or do you think the overhauled UI will include the option to hide certain non-essential columns?

**Comment by ngosang** [comment]
Columns could be rearrange and removed, but it will take time. Let the WebUI issues as they are, if someone is willing to implement meanwhile is ok.

**Comment by RoloSoze** [comment]
OK, in this case, I'll open a new Web UI issue for rearranging columns and hiding nonessential ones. I'll close this one since that ticket will encompass this.

**Comment by RoloSoze** [comment]
@3xploiton3 I have made a more generic suggestion in #8196 to enable users to rearrange & hide columns. Therefore, I'll close this ticket.
