### ISSUE TITLE
[HD-Torrents] Jackett incorrectly shows 'Freeleech'

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8197]
Jackett [Freeleech]:
![image](https://user-images.githubusercontent.com/23747425/79283650-7ad94c00-7e86-11ea-8d28-8dd46620d019.png)

HDT's website [50%]:
![HDT](https://user-images.githubusercontent.com/23747425/79283795-e91e0e80-7e86-11ea-9743-7feb0d288718.png)

There must be more, but that's the only one I found.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/blob/fa7e808c73cb5f618f0341480dfdd456bb1c7389/src/Jackett.Common/Indexers/HDTorrents.cs#L189-L203
I suspect that the gold/silver/bronze should be adjusting ULVF not DLVF

**Comment by RoloSoze** [comment]
Another example:
![image](https://user-images.githubusercontent.com/23747425/79285878-d4dd1000-7e8c-11ea-94d6-317c1d92c931.png)

![image](https://user-images.githubusercontent.com/23747425/79285898-e9b9a380-7e8c-11ea-9bdd-10e81cff33b0.png)

**Comment by garfield69** [comment]
Yes, it's the ones with 25 50 75 percent upload which the code is incorrectly setting to download volume factor (dlvf) instead of ulvf

**Comment by RoloSoze** [comment]
@ngosang Could this have happened during the recent code cleanup #8089? 'Cause I'm only noticing it now.

**Comment by garfield69** [comment]
@RoloSoze  can you access the web site directly and hover your mouse over the 75 50 and 25 icons and see what the tooltip says these values represent?

**Comment by RoloSoze** [comment]
25% `Count 75% of Download`
50% `Count 50% of Download`
75% `Count 25% of Download`

Yes, 25% & 75% carry the opposite definition of Jackett's Download Discount

**Comment by RoloSoze** [comment]
From HDT's FAQ page:

![image](https://user-images.githubusercontent.com/23747425/79288642-4620c100-7e95-11ea-9553-2f30ca89dd7a.png)

**Comment by garfield69** [comment]
yes good, that means that my earlier comments about ulvf are irrelevant.
the 8089 code did however restructure the if then else logic, so its likely this is the cause, as the relevant code had been unchanged for 3 year prior to that.

**Comment by RoloSoze** [comment]
Other than #8089, the only other recent HDT-related ticket is #7734 but I doubt the change made there had anything to do with this issue.

**Comment by garfield69** [comment]
it possible that the problem is simply that
https://github.com/Jackett/Jackett/blob/fa7e808c73cb5f618f0341480dfdd456bb1c7389/src/Jackett.Common/Indexers/HDTorrents.cs#L189-L190
these assignments should be for 1 not 1.0 ;-D

**Comment by RoloSoze** [comment]
@ngosang @cadatoiva What do y'all think?

**Comment by cadatoiva** [comment]
#8089 doesn't appear to change the layout of the code logic, as all the same assignments are done within the if statements. But just in case, can someone test https://github.com/Jackett/Jackett/releases/tag/v0.14.501 to see if it works correctly?

**Comment by garfield69** [comment]
Team members with a/c are cadatoiva, ngosang  and RoloSoze, so I cant help with testing, sorry.

**Comment by cadatoiva** [comment]
Oh, 🤦‍♂️I do have an account with this one. I can test it myself

**Comment by garfield69** [comment]
how handy is that spreadsheet of yours ;-D

**Comment by cadatoiva** [comment]
I reverted #8089 locally and am getting the same issue.
![image](https://user-images.githubusercontent.com/2086652/79293137-7f0e6500-7e98-11ea-8e93-629d1c483a89.png)

I'll look into it.

**Comment by RoloSoze** [comment]
@cadatoiva Haha, you worked on #7734 😂 Just be careful with HDT because if you don’t download at least 15GB every quarter, your account will be disabled.

**Comment by cadatoiva** [comment]
@RoloSoze thanks for the heads up. Testing this wasn't working without #8089 but running on the latest commit and my 16.7 official install is working fine here.

**Comment by garfield69** [comment]
@RoloSoze  double check your Jackett version, what are you on?

**Comment by RoloSoze** [comment]
0.16.7. I’m always on the latest version.

**Comment by garfield69** [comment]
what about language, are you using something other than English, does the site even support multi languages?
the code is looking for "Silver Torrent" but yours might be different.
to confirm,  on the web site right click over the 50 25 or 75 and select inspect and look for the 
**Alt=** keyword in the **img** selector

**Comment by cadatoiva** [comment]
I only see one language option in the settings, so I don't think it's that. Maybe you're account is triggering the global freeleech for some reason?

**Comment by cadatoiva** [comment]
If you're one of these ranks, your download doesn't count and you have automatic global freeleech.
https://github.com/Jackett/Jackett/blob/fa7e808c73cb5f618f0341480dfdd456bb1c7389/src/Jackett.Common/Indexers/HDTorrents.cs#L25-L33

**Comment by RoloSoze** [comment]
I’m using English, and it’s not showing me Freeleech for all torrents, so no to Global Freeleech. I can check what @garfield69 asked for later when I get the chance, but for now, could it some have something to do with the ‘bumped’ icon (displayed after the discount %)? Notice how both of the examples I posted above are for torrents that have been bumped.

**Comment by RoloSoze** [comment]
> If you're one of these ranks, your download doesn't count and you have automatic global freeleech.
> 
> https://github.com/Jackett/Jackett/blob/fa7e808c73cb5f618f0341480dfdd456bb1c7389/src/Jackett.Common/Indexers/HDTorrents.cs#L25-L33

I am not any of these either.

**Comment by cadatoiva** [comment]
Yup, that's the problem. The Bumped image has alt="Golden Torrent" which is the first check in the list, so it set's the download to 0% counted and then stops.

**Comment by garfield69** [comment]
its not a problem then, it is working as intended by the web site.

**Comment by cadatoiva** [comment]
So, here's the situation, according to the site, bumped torrents are ones in danger of having 0 seeds, and are pushed to the top in an effort to give it a boost of downloaders. They might be taking advantage of how our system checks for freeleech to try and boost it with us too (although it would be nice if they communicated that if its the case). It doesn't override the counting system though, so it's not really freeleech.

So I can fix this to the correct numbers by looking for the `img src=` tag instead, but do we really want to?

**Comment by RoloSoze** [comment]
> its not a problem then, it is working as intended by the web site.

How so? There's nothing in the FAQ that says bumped torrents are freeleech. This is all it says:

![image](https://user-images.githubusercontent.com/23747425/79297251-9d319080-7eab-11ea-8378-0da6208315c9.png)




> So I can fix this to the correct numbers by looking for the `img src=` tag instead, but do we really want to?

Why wouldn't we? Otherwise, it would be misleading. What am I missing?

**Comment by cadatoiva** [comment]
> Why wouldn't we? Otherwise, it would be misleading. What am I missing?

Because Jackett has no other way to communicate the site's desire to prefer this torrent. This seems like a deliberate choice by the admins to create this behavior.

**Comment by RoloSoze** [comment]
> So I can fix this to the correct numbers by looking for the `img src=` tag instead,

Wouldn't this fix this issue?

**Comment by garfield69** [comment]
IMO, if the site is marking torrents as golden via the `alt=` tag, but they are not in fact freeleech, and we have the ability to correctly identify the real dlvf and ulvf by using the `img src=`, then we should do so.
the important factor here it to display the actual cost/benefit to the user of downloading this torrent.
we don't care if the site is bumping the torrent if there is no change to the rations.

**Comment by RoloSoze** [comment]
> 
> 
> IMO, if the site is marking torrents as golden via the `alt=` tag, but they are not in fact freeleech, and we have the ability to correctly identify the real dlvf and ulvf by using the `img src=`, then we should do so.
> the important factor here it to display the actual cost/benefit to the user of downloading this torrent.
> we don't care if the site is bumping the torrent if there is no change to the rations.

+1

**Comment by RoloSoze** [comment]
> 
> 
> IMO, if the site is marking torrents as golden via the `alt=` tag, but they are not in fact freeleech, and we have the ability to correctly identify the real dlvf and ulvf by using the `img src=`, then we should do so.
> the important factor here it to display the actual cost/benefit to the user of downloading this torrent.
> we don't care if the site is bumping the torrent if there is no change to the ratios.

+1

**Comment by cadatoiva** [comment]
It would seem I'm out voted. Fixed.

**Comment by garfield69** [comment]
Jackett 0.16.18

**Comment by RoloSoze** [comment]
Works well! Thanks!
