### ISSUE TITLE
[1337x] Exception (1337x): No such host is known.: No such host is known. (Test)

### ISSUE THREAD

**Issue by jackmeat** [Jackett/Jackett#8198]

**Comment by garfield69** [comment]
access your Jackett dashboard and edit the 1337x SiteLink and pick an alternate domain.

**Comment by jackmeat** [comment]
Thank you. I was attempting to remove this since I did not intend on posting a question yet anyway, but I hit enter twice and instead it created this. Sorry about that, but thank you for responding. I am unable to access 1337x in browser right now either, so that is why I wasn't going to ask here yet.
