### ISSUE TITLE
Unable to add TehConnection

### ISSUE THREAD

**Issue by testarea1** [Jackett/Jackett#82]
Error: Configuration failed: Unable to login to TehConnection

Logs: 
```
Nov 20, 2015 09:55:57 PM	Debug	
UnixLibCurlWebClient:GetString Returning InternalServerError => 
Nov 20, 2015 09:55:57 PM	Debug	
UnixLibCurlWebClient: Posting username=removed&password=removed&keeplogged=1&login=Log+In%21
Nov 20, 2015 09:55:57 PM	Debug	
UnixLibCurlWebClient:GetString(Url:https://tehconnection.eu/login.php)
```
I did a web trace when logging in and the post url was:
https://tehconnection.eu/index.php?username=removed&password=removed&keeplogged=1&login=Log+In%21

Also, can there be a change to the logs display that strips out anything after username= or password= for making pasting logs without login info?

Thanks

**Comment by flightlevel** [comment]
Can you try again. I just tried and it worked perfectly.
The error you are getting InternalServerError is on TehConnection end not Jackett.
http://pcsupport.about.com/od/findbyerrormessage/a/500servererror.htm

**Comment by testarea1** [comment]
I tried again and same error, I can login fine via chrome.

**Comment by flightlevel** [comment]
Sorry, no idea. Works perfectly on Windows & Mono (Ubuntu) here

**Comment by testarea1** [comment]
Yeah, I'm not able to figure out why I can't add teh. I've add my other private trackers no problem (freshon, scc) but teh is the only one I can't add. Just updated to v0.7.33 but still not able to add.

**Comment by testarea1** [comment]
Running this on Mono. I tried changing the -c client option for the console to each one to see if that would help, they all give the configuration error. Another debug from the log:

```
Nov 21, 2015 04:18:37 PM	Debug	
Response: {"name":"TehConnection","result":"error","error":"Unable to login to TehConnection","config":[{"id":"username","type":"inputstring","name":"Username","value":"removed"},{"id":"password","type":"inputstring","name":"Password","value":"removed"},{"id":"filters(optional)","type":"inputstring","name":"Filters (optional)","value":""},{"id":"cookieheader","type":"hiddendata","name":"CookieHeader","value":""}]}
```

**Comment by flightlevel** [comment]
Tried this again, still works perfectly on Windows but now same error on Mono. Looks to be the same issue as https://github.com/Jackett/Jackett/issues/79
Pretty sure I've found the problem. It's SSL related. http://snag.gy/5ZmqI.jpg Not sure why SSLFix doesn't help though.

**Comment by testarea1** [comment]
The teh main index.php frontpage contains an http link from imgur (the graduate movie poster) so you'll get mixed secure messages for that I believe since it's not https like the rest of the site (not sure why they didn't link the https img path.

**Comment by flightlevel** [comment]
Yep, its either that image (although pretty sure curl doesn't try to download images) or its the SSL certificate not supplying ownership information.
Anyway, I set curl to not verify the SSL and it now works on mono.
Just need to work out the best way to implement.

**Comment by vonny3** [comment]
I am having the same issue with Torrentleech as a tracker - their cert also provides no ownership. Trying to get this up and running on a QNAP (Linux based) at this point - would be very interested to know if you make any progress with how to implement.

**Comment by vonny3** [comment]
@flightlevel can you provide steps for setting curl to not verify SSL by chance?

**Comment by WhatFox** [comment]
That is due to be implemented shortly

**Comment by flightlevel** [comment]
The latest release should fix this issue.

**Comment by testarea1** [comment]
Resolved now. I had to use just `--IgnoreSslErrors true` on startup and it was able to connect
