### ISSUE TITLE
[Req] WorldFree4u Public https://worldfree4u.ink/

### ISSUE THREAD

**Issue by onlytanmoy** [Jackett/Jackett#8208]
Please consider my request to add this movies/web series indexer - https://worldfree4u.ink/
legacylink: https://worldfree4u.trade/

**Comment by onlytanmoy** [comment]
@garfield69 thanks mate, really appreciate that.

**Comment by garfield69** [comment]
this site is not suitable for use with Jackett.
there is no direct download link to either a .torrent or a magnet on the site.
to download you have to do multiple manual steps including a Captcha challenge.
It is not possible to solve these challenges automatically.

**Comment by onlytanmoy** [comment]
@garfield69 hey mate, a diff request - can you please send me an invite to TorrentBD from your garfield69@outlook.com id? :)

**Comment by garfield69** [comment]
>can you please send me an invite to TorrentBD

Thank is not possible sorry. I get invites to sites just to create the indexer, but I do not contribute to the site or maintain the account to build up credit, download or upload anything. With close to 200 indexers I maintain there is not enough time in the day to spend keeping rations balanced or accounts active. On some sites that keep strict accounting of contributions or activity, my account is likely to get suspended or deleted in 30 days anyways.

**Comment by onlytanmoy** [comment]
Yeah right, I get it...no worries, thanks for your response...appreciate it.
