### ISSUE TITLE
Asthetics suggestions - Pre-release v0.7.754

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#821]
Since the interface now has tabulated format, I suggest the following:

1. Add (No.) column for serial numbers. This is very minor, but helps keep track of how many indexers there are in both 'Configured Indexers' and the 'Select an indexer to setup' dialogs.

2. Might be a good idea to use 2 different colors for the 'Potato' & 'Torznab' buttons? What do people think? Keep the current baby blue/sky blue color for one of them though - looks great! Purple might be a nice touch for the additional color! Also, having 2 different colors for 'Add Indexer' and 'Manual Search' buttons may be worth exploring. 

3. When hovering over a particular row (any cell on the row), it would be great if that row is highlighted so as to clearly differentiate it from the previous and next rows. This does happen in the current version, but it's too subtle to notice, at least on my display. The suggestion can be applied not only on the 'Configured Indexers' and 'Select an indexer to setup', but also on the 'Cached Releases' and 'Manual Search' results. 

@kaso17 MAJOR PROPS on the new design, bug fixes, and functionalities - especially the 'Test All' function! Handy & satisfying!

**Comment by kaso17** [comment]
1) that feels like wasted space to me. How about a total indexers configured/unconfigured counter below the list?

**Comment by armani316** [comment]
@kaso17 Yes, I think that's better.

**Comment by kaso17** [comment]
2) currently using pretty much all of the standard bootstrap colors (https://v4-alpha.getbootstrap.com/utilities/colors/).  As the two buttons are similar I gave them the same color.
Search was already green and for add green felt natural. 
If you've a specific suggestion (color codes/mockups) we could let people vote for it.

3) it's the standard boostrap hover effect, but once again if you come up with specific color codes people could decide.

**Comment by armani316** [comment]
2 & 3 are not too essential to be honest, they were my first thoughts upon seeing the new design. Unless others make similar suggestions in the future, I think we can close this issue (2 & 3), and just add a configured/unconfigured counter below each respective list (1). @kaso17
