### ISSUE TITLE
[req] Blackhole torrent (BHT) Private French tracker https://bht.is/

### ISSUE THREAD

**Issue by SuissoNaBisso9** [Jackett/Jackett#8210]
### Description

Hi 

a new and nice looking French tracker recently opened and is now open for registration, would be great to see it added to Jackett !
https://bht.is/

Thanks :)

**Comment by garfield69** [comment]
This web site is completely (top to bottom) generated from Javascript run dynamically after the initial HTML is sent.
as such it is not possible to process this site with the Cardigann yaml processor.
The indexer for this site will need to be coded in C#

**Comment by SuissoNaBisso9** [comment]
Hey
is there any plan to code the indexer in C# ?

Thanks

**Comment by garfield69** [comment]
as soon as a C# volunteer contributes. I just do yaml indexers.

**Comment by garfield69** [comment]
https://bht.is/ returning 
```html
502 Bad Gateway
nginx/1.19.2
```
Just me or is the site Gone, broken or moved to a new domain?

**Comment by ilike2burnthing** [comment]
`We have therefore, after careful consideration, decided to close the tracker as it is, to start again on a healthy basis and come back as soon as possible with a new version.`
http://torrentinvites.org/f31/bht-blackholetorrent-news-579874/

Close this and let someone make a new request when its successor arises from the flames?

**Comment by garfield69** [comment]
definitely.

**Comment by pipopop** [comment]
BHT is dead !

_Au vu de l'actualité récente, la fermeture d'Ethor... 

Au vu de l'actualité, la protection Cloudfare assignée par la justice afin de donner les noms de ceux qui souscrivent des protections pour leur site (C'est un poil plus compliqué que ça, mais inutile de rentrer dans les détails).

Je viens ici vous annoncer que BHT ne rouvrira pas ses portes.

Alors BHT n'était pas chez Clouflare, sauf que notre entreprise de protection est aux US. Au même titre que Cloudflare, elle peut, et sera certainement, assignée pour donner les mêmes éléments.

Nous ne voulons pas rouvrir BHT, nous estimons qu'il y a trop de risques. La chasse aux sorcières a prit un niveau de dangerosité que nous ne voulons pas accepter.

Merci de nous avoir suivi pendant cette trop courte existence.

Nous souhaitons à tous les sites encore debout de tenir le plus longtemps possible. Longue vie à tous.

Le Staff BHT_
