### ISSUE TITLE
[req] Torrenti public  https://torrenti.xyz/

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#8212]
![image](https://user-images.githubusercontent.com/19517680/79377159-76e02380-7f85-11ea-8730-c01e95525a68.png)

**Comment by garfield69** [comment]
This is torrent2k with a different skin
if you look up the latest page you get exactly the same results
https://torrenti.xyz/
![image](https://user-images.githubusercontent.com/6933240/79544344-fd5e4780-80e2-11ea-9ba6-92d1414e8e51.png)
![image](https://user-images.githubusercontent.com/6933240/79544364-051dec00-80e3-11ea-921f-24e28155e9aa.png)
