### ISSUE TITLE
[req] Torrentz2K public https://torrentz2k.xyz/

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#8213]
![image](https://user-images.githubusercontent.com/19517680/79377394-ce7e8f00-7f85-11ea-92d7-93ddedffce39.png)

**Comment by garfield69** [comment]
Jackett 0.16.34

**Comment by ilike2burnthing** [comment]
https://torrentz2k.xyz/ may be changing to https://torrentz2k.pw/ (any search redirects, and a lot of the links are to .pw)

.xyz is also using CF's DDoS protection, whereas .pw isn't, so at least it would be usable in Jackett. However, it appears to be incompatible with the current YAML and there are noticeable differences in the HTML.

@garfield69 if you get a chance, would you be able to have a look?

**Comment by ilike2burnthing** [comment]
https://torrentz2k.pw/ - Error 522 - Connection timed out

**Comment by iz8mbw** [comment]
@ilike2burnthing hi, it seems that https://torrentz2k.xyz/ has changed into https://torrentz2k.pw/.
Anyway both domains seems to do not work after a search, it seems only home pages works.
Is it the case to remove?

Thanks!

**Comment by ilike2burnthing** [comment]
Changed the indexer to work with *.pw and dropped *.xyz - https://github.com/Jackett/Jackett/commit/86cdecf4185438e0de753692231906d80769736c

**Comment by iz8mbw** [comment]
Ok, good!
