### ISSUE TITLE
[empornium] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Winblackka** [Jackett/Jackett#8220]
### Logged Error Messages

[An error occurred while testing this indexer
Found no results while trying to browse this tracker]

**Comment by garfield69** [comment]
none of the team have an account on this site so we cannot investigate independently.
If you send an invite to garfieldsixtynine -at- gmail.com I can look into this.
If an invite is not possible, then provide an full enhanced log file.
https://github.com/Jackett/Jackett/wiki/TroubleShooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Winblackka** [comment]
Sry, for my late response, im not at home right now. Maybe another EMP member can upload a full log.
