### ISSUE TITLE
Error performing update.

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#8225]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Manjaro KDE 19

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:  0.16.7.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [no]

### Description
Need improve when update from http://127.0.0.1:9117/UI/Dashboard#
always getting error, 

### Screenshots

![image](https://user-images.githubusercontent.com/19517680/79492912-e8ce7080-804a-11ea-9a43-40981219436b.png)

**Comment by garfield69** [comment]
Please provide the updater.txt file which on most linux systems should reside in the `~/.config/Jackett/` folder.
Thanks.

**Comment by 3xploiton3** [comment]
https://drive.google.com/drive/folders/1ZPKS8MloMChihgg7LcfaGf151ubcsq9d?usp=sharing

**Comment by garfield69** [comment]
OK so the updater never got invoked, so that means the previous step to fetch the latest package from GitHub is failing.
```
2020-04-17 01:28:18.9375 Info Jackett variant: CoreLinuxAmdx64 
2020-04-17 01:28:19.8992 Info New release found. Current: v0.16.7 New: v0.16.23 
2020-04-17 01:28:19.8992 Info Downloading release v0.16.23 It could take a while... 
2020-04-17 01:30:00.6094 Error Error performing update. System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
```

open a terminal and try 
```
wget https://github.com/Jackett/Jackett/releases/download/v0.16.23/Jackett.Binaries.LinuxAMDx64.tar.gz
```

does that work?

**Comment by 3xploiton3** [comment]
work again,
