### ISSUE TITLE
[extratorrent-cd] cat change needed

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8228]
All results for ET-cd in Jackett and on .si are listed as `Other` (despite what their homepage shows).

![et-cd](https://user-images.githubusercontent.com/59480337/79509330-36d77a00-8033-11ea-9733-3ed6747eb78d.png)

Not a small change to the .yml so I'll leave this to someone more qualified.

**Comment by cadatoiva** [comment]
Should just be a matter of updating all of the category lines to match what's on the site, unless it's a website change so our category selector isn't working.

**Comment by garfield69** [comment]
if you take a close look at the screenshot you provided, the keyword-less search results are stated as being in **Other** (gray test `in Other by <uploader>` which is what Jackett is also reporting.
I don't see a problem?

**Comment by ilike2burnthing** [comment]
That seems to be the _only_ category on the site though. I did several keyword searches before that, and everything was Other, not any of the other ~900 we have listed.

**Comment by garfield69** [comment]
They used to have categories and now they are dumping everything into Other.
they may return to properly categorising later, it could be some issue at their end.
But either way, Jackett is reporting what the site is presenting and I don't see that there is anything we need to do (or even can do) about this.
Or are you proposing we remove all the cats and just have Other?

**Comment by ilike2burnthing** [comment]
> Or are you proposing we remove all the cats and just have Other?
Yes. And revert if needed.

Currently, unless you include 7000 and/or 100009, you get no results back.

**Comment by ilike2burnthing** [comment]
Ta 👍
