### ISSUE TITLE
[TorrentLeech] Interesting note about search string processing

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8230]
I was searching for the following movie titles, both of which work fine and as expected:
`The Innocents 1961`
`The Revival 2017`

However, when the year is removed from the search query, searching Jackett returns nothing, and searching TL's website returns a barrage of irrelevant results: 
`The Innocents`
`The Revival`

This is a strange behavior that I have not noticed in other trackers, so I tried inserting an underscore:
`The_Innocents`
`The_Revival`

To my surprise, the underscore worked very well in Jackett, with no unrelated results being returned. On TL's website, it reduced the number of search results. They're still mostly irrelevant but at least the desired release was listed among them.

Any idea why an underscore is necessary in this case? And can it be fixed so that the Jackett user gets the right result(s) sans the year and without having to use an underscore? You can also try searching for `Will and Grace` vs. `Will_and_Grace` for further illustration of this issue.

I should also note that underscores do not always work well in TL. I tried inserting them in search strings where I was already getting relevant results, and it actually resulted in eliminating a bunch of releases from the Jackett search results - e.g. `Last Year` = 29 results vs. `Last_Year` = 14 results, so the underscore in this example ensured that releases are only returned if the words Last & Year are right next to each other & in that order.

**Comment by garfield69** [comment]
The TorrentLeech website search engine is searching not only the **title**, but the content of any **NFO**  as well.
If you access the web site from your browser and search for `david carroll` you get one hit, for title `VA - N A R P 565 (2) 8 04 2020 - Spaceman3` which happens to have `David Carroll - Let's Dance (2020)` as text in the NFO description on that torrent's details page.

This means that when you search for `The Revival` you are getting any torrents that have the keyword `the` in either the title or the nfo file.

as to the business of the underscore, that is probably the result of the MatchQueryStringAND that the code does against the title, where the routine splits the title into words (replacing all non alphanumeric letters with spaces) and thus excluding all the hits that do not have all the keywords.

and that concludes my interest in this ticket, as the rest is C# stuff.

**Comment by RoloSoze** [comment]
@garfield69 Thank you for the clarification. I just used the TL website search results as an illustration; Jackett does a much better job at returning relevant results. My whole point behind this ticket is the underscore issue since the user should not have to insert one to get the right results. I have also added another example to my OP for Will and Grace.

**Comment by RoloSoze** [comment]
I'm closing this issue since it was more of an observation than anything else. As long as the user enters the Movie Title + Year, they should get the right results.

**Comment by ngosang** [comment]
@RoloSoze fixing this issue in Jackett doing several requests is a bad approach. Maybe you can talk to the staff to add a checkbox or something to search only in title. That will fix all our problems.

**Comment by RoloSoze** [comment]
> 
> 
> @RoloSoze fixing this issue in Jackett doing several requests is a bad approach. Maybe you can talk to the staff to add a checkbox or something to search only in title. That will fix all our problems.

Yeah I figured as much. For such large trackers, it's hard to establish contact with the staff or get them to care about such small things, so we'll just have to live with it I guess.

**Comment by RoloSoze** [comment]
@ngosang I think I figured out where the problem is. It has to do the categories. Take the following example:

Search for the example I used above, i.e. `The Innocents` when 'Any' is selected for the Category - You get no results:
![image](https://user-images.githubusercontent.com/23747425/83316802-1e43ad80-a1f6-11ea-82fa-dc9ca10353a7.png)

Now repeat the search using only the categories in which there are results, in this case 'Movies BluRay' and 'Movies BluRay Rip' - You get all the correct results (you actually get a few more relevant ones but I filtered by year):

![image](https://user-images.githubusercontent.com/23747425/83316866-85f9f880-a1f6-11ea-853e-a0432e4230b4.png)

This actually mirrors the same behavior as TorrentLeech's website.

I'll give you another example, which actually includes the release year. Try searching for `Frequency 2000` using 'Any' for the Category. Again, no results:

![image](https://user-images.githubusercontent.com/23747425/83316935-27814a00-a1f7-11ea-9257-ea482e04f3a4.png)

Now try again using 'Movies BluRay' and 'Movies BluRay Rip' for the Category. These are the only two categories for which there are results for this movie - You get all the relevant results:

![image](https://user-images.githubusercontent.com/23747425/83316965-5e576000-a1f7-11ea-80a9-8196cf27d8e0.png)

It's worth noting that when searching with the IMDb ID for the two examples I used, there is no need to select specific categories.

I realize this is a flaw from TL's side, but since the results are actually retrievable, can it be fixed in Jackett?

**Comment by ngosang** [comment]
I can't guess the category from the title. The only solution is with changes in his server. https://github.com/Jackett/Jackett/issues/8230#issuecomment-633220443

**Comment by RoloSoze** [comment]
@ngosang Can you please email me your TL username? I'll need to loop you in on a conversation I started over there with the concreted staff members. Thank you.

**Comment by RoloSoze** [comment]
@ngosang Got a message from the TL staff about a possible solution.

**Comment by ngosang** [comment]
@RoloSoze test the next release

**Comment by RoloSoze** [comment]
@ngosang Works exactly as expected! Funny how this flaw has gone unnoticed for so long! As always, thank you for your hard work!

**Comment by garfield69** [comment]
Jackett 0.16.605
