### ISSUE TITLE
Sickchill + Jackett: Errors + some trackers don't have data

### ISSUE THREAD

**Issue by Tiwas** [Jackett/Jackett#8233]
### Environment

**OS**: Windows 10

**.Net Runtime**: .Net-Framework

**.Net Version**:

**Jackett Version**: 0.16.23.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** yes

### Description

Added indexers to sickchill, searched. No results for x265 downloads.

Manual search yields some results and if I filter for x265 I find multiple versions.

Is jackett not compatible with sickchills option to only search for x265 releases?

### Logged Error Messages

See attached file.

### Screenshots
![image](https://user-images.githubusercontent.com/17053402/79544626-9b282700-808f-11ea-84de-e9143589cfcb.png)
![image](https://user-images.githubusercontent.com/17053402/79544678-abd89d00-808f-11ea-8c48-54337ac4406a.png)
[jackett_log.txt](https://github.com/Jackett/Jackett/files/4491612/jackett_log.txt)

**Comment by garfield69** [comment]
>Is jackett not compatible with sickchills option to only search for x265 releases?

That's a leading question if ever I saw one.
The truth is that I do not come across many sickchill users and I personally don't use the product, so I cannot answer that question off the top of my head withot a lot of research I don't have the time to set aside for.

The pertinent question is: what does sickchill's option to search for only x265 actually mean?

to begin to find out more, you need to set up the following test conditions:
- enable Jackett enhanced log to capture more debug details during queries
so access the Jackett Dashboard, scroll to the bottom, tick the **enhnaced logging** box, scroll up a bit and click on the **apply server settings**.
- then on sickchill, using just a **single** Jackett indexer (to avoid log overload) do a single episode search with whatever option sickchill has for searching only x265

now look at the Jackett dashboard log, scroll to the bottom and work up and see if you can find the query that sickchill sent to Jackett to search for the episode.
it will be an **Info** record that may look at bit like this 
`Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/indexers/...etc...`

Jackett will return all available titles that match those parameters.

It is then up to sickchill to examine the title and other Torznab fields that Jackett returned, and decide which records meet its criteria.

Most apps that are capable of making queries to Jackett via the Torznab API (Im familiar with Sonarr, Radarr, Lidarr, and DuckieTV) have several sets of logs, including ones that can be turned on to provide a more detailed debugging look at what decisions the app made when analysing the results returned by Jackett and whether the title was rejected as not suitable for  whatever reason.

So your next step would be to see if you can turn on such logs in sickshill so you can dig deeper into why you are not seeing the results you expected.

Re: the errors caption in your title.
The Jackett log you provided shows that extratorrent-cd was interrupted by a cloudflare anti-DDoS challenge, and its likely some of the other indexers that generated errors are suffering the same.
For most indexers, there are alternate links you can use by editing the indexer config using the jackett dashboard and selecting one of the alternate sitelinks.
then test with the TEST button to prove the indexer works.
If none of the alternate sitelinks of an indexer work, then a VPN that allows you to specify a different world location may allow you to get assigned an IP address that is not being blacklisted and return results.

And finally, (please do not be offended), IMO, searching 40 public indexer every time you go looking for an episode is a complete waste of time and resources.
Most public sites all return pretty much the same results, and searching them all every time you make a sickchill query for an episode only increases the wait time, the network traffic, and computer resources used, and when Jackett finally returns results, probably 3 quarters or more of them will be duplicate records for the same magnet/.torrent titles anyway.
At the most, 5 indexers should be enough to cover the widest range of results gathered and provide enough redundancy to grantee a relevant result is returned in a fairly prompt manner.
Just pick the ones that consistently work for you and return what you look for. The rest (especially the ones that are generating errors) could be removed.

**Comment by Tiwas** [comment]
Thanks.

First of all - the reason I added all of them was for statistics. x265 releases don't pop up nearly as often as h264 and some indexers are really slow adding them. So by searching all of them for a week or two I should be seeing which ones get them first and then disable the rest. So yeah - I totally agree with you on all accounts. It's a waste if someone keep doing it.

For my question, it seems it just needed to sit for a couple of days. Yesterday I got some hits and today I got a lot. Not sure why, but loving it now that it has warmed up.

And thanks for a really good reply. Do you have a donation link?

**Comment by garfield69** [comment]
>Do you have a donation link?

No I do not. But thank you for the thought.
