### ISSUE TITLE
[Req] BWTorrents

### ISSUE THREAD

**Issue by datsunedd** [Jackett/Jackett#8241]
Wanted to request a Bollywood tracker: https://bwtorrents.tv/signup.php to be added to Jackett

**Comment by datsunedd** [comment]
If someone can point me in the right direction I can help get this started. I have some experience with C#

**Comment by cadatoiva** [comment]
Before we jump into implementing a C# tracker, we need to see if it can be implemented in our Cardigann YAML definitions. See [this link](https://github.com/Jackett/Jackett/wiki/Definition-format) for how the formatting, and anything in [src/Jackett.Common/Definitions](https://github.com/Jackett/Jackett/tree/master/src/Jackett.Common/Definitions) for examples. @garfield69 will be able to help you with any questions you have on the formatting.

If you want to get started on that, I'll assign you this ticket so no one else doubles up on your work.

**Comment by datsunedd** [comment]
Sure, I can look at that

**Comment by cadatoiva** [comment]
Ok, @datsunedd, it's all yours for now. Let us know if you have any questions.

**Comment by datsunedd** [comment]
@garfield69  
Question about the Category Mappings section. How do I find the category mappings specific to the tracker I am trying to add ?

**Comment by cadatoiva** [comment]
The category mappings are any kind of filter that can specify download types. Like in TPB, it's this dropdown next to the search
![image](https://user-images.githubusercontent.com/2086652/79644935-be2b0780-8171-11ea-9dee-8ddb3a2724a7.png)

You can get the values by inspecting that dropdown giving you all the values and names. 
![image](https://user-images.githubusercontent.com/2086652/79644960-e9155b80-8171-11ea-8d4b-9e62086f9d3a.png)

**Comment by garfield69** [comment]
are you still working on this or do you want to hand it over?

**Comment by datsunedd** [comment]
@garfield69 hey, apologies. I have not been able to give time to this. I would like to hand it over

**Comment by garfield69** [comment]
Jackett 0.16.373

**Comment by garfield69** [comment]
https://bwtorrents.tv/ cloudflare Web server is down Error code 521

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
I'm getting `HTTP Test Page powered by CWP | CentOS-WebPanel.com`
Just me?

**Comment by ilike2burnthing** [comment]
Well I'm now getting a Cloudflare check followed by a 404 forbidden error page.

**Comment by garfield69** [comment]
Same here. Cleary stuff happening. I'll check later.

**Comment by garfield69** [comment]
online albeit slow as molasses with browser, and exceeding 100sec timeout on indexer.

**Comment by garfield69** [comment]
https://bwtorrents.tv/ cloudflare A timeout occurred Error code 524

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/8241#issuecomment-1742162502

**Comment by garfield69** [comment]
online
