### ISSUE TITLE
[TorrentBD] Login failed: Selector "a[href="account-logout.php"]" didn't match

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8243]
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.16.34.0

**Last Working Jackett Version**: 0.16.23

**Are you using a proxy or VPN?** No

### Description
I am unable to configure TorrentBD in Jackett. It looks like they changed something on their end. 

### Logged Error Messages
`An error occurred while updating this indexer`
`Login failed: Selector "a[href="account-logout.php"]" didn't match`

Enhanced log:
[log.txt](https://github.com/Jackett/Jackett/files/4495510/log.txt)

### Screenshots

Not needed

**Comment by garfield69** [comment]
cant work out why the login form is no longer working.
switching to the cookie method.

**Comment by garfield69** [comment]
Jackett 0.16.54
