### ISSUE TITLE
[Alpharatio] Season wide searches return no results. 

### ISSUE THREAD

**Issue by monestri** [Jackett/Jackett#8244]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: docker / synology / linuxserver.io

**Jackett Version**: :v0.16.34-ls63

**Last Working Jackett Version**: ??

**Are you using a proxy or VPN?** [yes/no]: No

### Description

1. When searching via sonarr using the season search feature, it generates a URL like this, which looks reasonable. However, I get no results when using the Alpharatio indexer. 
torznab/api?t=tvsearch&cat=5040,5045&extended=1&apikey=(removed)&offset=0&limit=100&q=Westworld&season=3

2. When I do an episode search, it generates a URL like this, which works fine: 
torznab/api?t=tvsearch&cat=5040,5045&extended=1&apikey=(removed)&offset=0&limit=100&q=Westworld&season=3&ep=3

Repeating these steps with the HDME indexer works fine. That is, when I drop the ep query parameter, I still get results, so I'm pretty sure this bug is specific to the alpharatio indexer. If alpharatio doesn't support a season search, I'd suggest doing a series search and filtering the results locally to emulate one.

**Comment by monestri** [comment]
I have an alpharatio only fix that drops the season query param if it isn't accompanied by an episode. Since this type of search doesn't work with alpharatio, it's better to return more results than none at all. Sonarr should be able to filter out results it doesn't need. I think I'd need permission to make a PR.

**Comment by RoloSoze** [comment]
> I think I'd need permission to make a PR.

@garfield69

**Comment by RoloSoze** [comment]
@monestri I hid your comment from the recruitment ticket since it's off-topic. @garfield69 will let you know here when he gets the chance.

**Comment by monestri** [comment]
Asking about the process for submitting code in a ticket asking for help with code is off topic? Interesting. Anyway I figured out how to do it.

**Comment by RoloSoze** [comment]
> Asking about the process for submitting code in a ticket asking for help with code is off-topic? Interesting.

I see your point, but we're trying to gear that ticket more toward general recruitment-related areas. The PR comment might lead to more discussions about this specific issue, so I thought it might be better to keep the discussion here :) Thanks for your help!

**Comment by garfield69** [comment]
Jackett 0.16.127
