### ISSUE TITLE
Extra torznab query parameter for true series titles

### ISSUE THREAD

**Issue by Taloth** [Jackett/Jackett#8246]
I was working on the newznab search code to deal with some scene naming exceptions when I remembered the ongoing issue users experience with full title searches for series with apostrophes and diacritics.

I'm thinking about adding support for a `title` query parameter. If specified in `supportedParams`, sonarr would use `title` instead of `q`, and provide the original series title (and scene naming exceptions in separate api calls) rather than the cleaned one.
`q` remains in use for certain other cases, such as specials and anime.
_(Note that you should be prepared for both `q` and `title` at the same time, although I'm not planning to use that combo right now it could be useful for searching for specials in the future)_

An alternative would be a new attribute in the caps that specifies the search engine used, which could be used to modify the behavior of `q`.
Most Newznab sites uses sphinx for text indexing, but I think some use elasticsearch or just mysql fulltextsearch.
Maybe a `searchEngine` attribute with the value `raw` would be sufficient.

Either approach is fine by me, we just need a way to convey the right capabilities.
What do you guys think?

**Comment by seeyabye** [comment]
This would definitely be very helpful.

Particularly, this would solve various impending issues related to trackers that performs sanitazation on their end, resulting in very poor searches. For example, Animebytes does not support numbers and other characters in their API search, which has been causing poor search results.

By any chance, do you have an update on this? In the meantime, I will take a look at the code in Jackett and see if I can propose the above capabilities.

**Comment by Taloth** [comment]
Back in April I added the `title` one to Sonarr v3: https://github.com/Sonarr/Sonarr/commit/05dd17aacbaff4021a843533b8f22bc168aca321

**Comment by seeyabye** [comment]
Thanks for pointing me in the right direction.

On the side note, may I know why is Anime and Specials left out?
I think this feature is relatively important for Anime especially a slight difference in naming could totally mean a different Season.
For instance, Gintama is a good example of Anime that messes around with symbols.

If it's not a problem, I would like to consider adding the same capabilities to Anime. I can create a pull request for this if required, but I am interested in hearing your thoughts.

**Comment by Taloth** [comment]
Both Anime and Specials uses a full text search already. 
It was discussed to add something like `absnr` episode number to the newznab standard so it could be indexed properly, however we never actually did that. Mostly because we didn't have time to work on it (it would require a ton of extra regexes for indexers to actually parse em). I don't think I want to add that at this time.

**Comment by seeyabye** [comment]
Thank you for the explanation. 

I'm afraid, I'm still not too sure if I understand what it means by full-text search.
Would you mind elaborating a little more?

--

As per my understanding,

From https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs

The following function clearly returns a Sanitized title and the resulting result is indifferentiable on Jackett's end.

```c#
public virtual IndexerPageableRequestChain GetSearchRequests(AnimeEpisodeSearchCriteria searchCriteria)
        {
            var pageableRequests = new IndexerPageableRequestChain();

            if (SupportsSearch)
            {
                foreach (var queryTitle in searchCriteria.QueryTitles)
                {
                    pageableRequests.Add(GetPagedRequests(MaxPages, Settings.AnimeCategories, "search",
                        string.Format("&q={0}+{1:00}",
                        NewsnabifyTitle(queryTitle),
                        searchCriteria.AbsoluteEpisodeNumber)));
                }
            }

            return pageableRequests;
 }
```

For instance, if I were to do an anime search with `Shinryaku!? Ika Musume 01` and `Shinryaku! Ika Musume 01`, the search query becomes `Shinryaku Ika Musume 01` for the both of them. 

When a Manual Search is done on Episode 1,  Season 1 of "Squid Girl"
`http://localhost:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Shinryaku%20Ika%20Musume+01`

When a Manual Search is done on Episode 1, Season 2 of "Squid Girl"
`http://localhost:9117/api/v2.0/indexers/animebytes/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Shinryaku%20Ika%20Musume+01
`

**Comment by Taloth** [comment]
It's a title, you cannot abuse that for title + absolute episode number.

If you want title, then you need a separate absnr and appropriate code in jackett to handel it, that name (absnr) needs to be formalized with newznab upstream too and as I said I wasn't ready to do that yet, because it involves analyzing anime releases and provide appropriate regexes to actual newznab indexers as well, including support for ranged releases, it gets complicated fast.
Which is why I said I didn't want to add title (and thus absnr) to anime at this time. I'm sorry but I cannot accept that pull request.

**Comment by seeyabye** [comment]
Thank you for taking the time to explain it.

I understand the reasoning and will close the PR accordingly.

I guess there is really no solution for now but to consider a separate `absnr` caps, and that would take a lot of work to support it.

**Comment by Taloth** [comment]
It is possible, but someone will have to get a ton of regexes that work on animetosho or one of the other anime sites, so it's a package (it'll also make it more worth while for newznab upstream).
I think the only alternative that doesn't involve that kind of work is to add searchEngine as suggested in the original post.

**Comment by seeyabye** [comment]
I have actually implemented the first option of supporting `title`, but it may not be the best choice as it may not be explicit enough.

That said, I am in agreement with adding the additional attribute `searchEngine` with `raw`. I will consider PR for Jackett to support this additional attribute.

**Comment by Taloth** [comment]
`title` is explicit enough for regular series, so I think it's a good thing to have. but `searchEngine` is the only way to change the behavior of `q` in a reliable way.
`searchEngine` can be added, while keeping `title`. but since nobody uses 'title' yet we could also just replace it. The problem is specials. having `title` is a benefit there, `title` for the series, and `q` for the episode title.

regular episode searches:
- tvdbid + season + ep 
- q + season + ep
- title + season + ep

regular season searches:
- tvdbid + season
- q + season
- title + season

regular special searches:
- q (series query title + episode query title)
- Not implemented yet: title (series title) + q (episode query title)

daily episode searches:
- tvdbid + season=year + ep=month/day
- title + season=year + ep=month/day
- q + season=year + ep=month/day

daily season searches:
- tvdbid + season=year + ep=month/day
- title + season=year + ep=month/day
- q + season=year

daily special searches:
- treated as regular daily episode search iirc

anime episode searches:
- q (title + absnr)
- One day maybe: tvdbid + absnr / anidbid + absnr
- One day maybe: q + absnr
- One day maybe: title + absnr

anime season searches:
- doesn't exist, simply does multiple anime episode searches

anime special searches:
- treated as anime episode search iirc

**Comment by seeyabye** [comment]
Thanks for providing the definitions.

My only concern now is the values of `searchEngine`. So far, it's only `raw`. What other values would you be considering to add?

**Comment by Taloth** [comment]
I'd consider 'sphinx' to be the default since that's what newznab generally uses. Some use elasticsearch but we'll cross that bridge when we have to.

**Comment by garfield69** [comment]
v0.20.1485
