### ISSUE TITLE
[M-Team TP] Possibility of fetching the full release name from the torrent's details page

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8253]
M-Team TP is perhaps the only remaining major private tracker that shortens long release names by appending `...` to the end of the torrent's name. I believe the maximum length on the browse/search page is 70 characters. Here's an example:

![image](https://user-images.githubusercontent.com/23747425/79645220-ee77a380-817b-11ea-9f59-b2113324acc0.png)

And of course, MTTP's website shows the results exactly the same way as Jackett:

![image](https://user-images.githubusercontent.com/23747425/79645272-4f9f7700-817c-11ea-8955-83297c7343dc.png)

If the user does a post-search filtration using a keyword that's been truncated (e.g. Remux, release group), relevant torrents will not appear among the filtered results because Jackett can only process words that are actually displayed on the browse/search results page.

I have spoken in the past to the MTTP staff about increasing the maximum character length beyond 70, but nothing was done probably due to the lack of interest.

Is it possible for Jackett to fetch the full release name from the secondary/torrent's details page without overloading the MTTP server and/or generating unwanted traffic?

**Comment by garfield69** [comment]
Note no one on the team has an account of this site. So we cannot do any independent research.

The first thing to do would be to dump the html from the web site search results page, so that we can check if the full title is available. 
Some site provide the full title as a tooltip when you hover over the title in the row, or as a popup with a picture and full title and other data displayed.
if the full title is available someplace in the row, we can extract it and use it.

if that full title is not available there, then the only way would be to issue a separate requests to fetch the details page, for each and every row on the results page, every time you do a search.
We try to avoid that if at all possible as you are now talking about potentially 101 http gets in order to present a full search page, but to do that, this indexer would need to be rewritten in C# as the Cardigann yaml processor does not support that kind of processing.

The only other alternate way, is if the web site has an API that returns json or xml when queries are made to it, and hopefully the data from that service has the full title. But once again a rewrite into C# would be required if such an API was available at the site.

**Comment by RoloSoze** [comment]
> The first thing to do would be to dump the html from the web site search results page, so that we can check if the full title is available.

I looked at the HTML code before posting this question, and I found that the page does not contain the full release names. Here's the code for the abovementioned example:

[M-Team - TP   Search results for tt0421715 - Powered by NexusPHP.zip](https://github.com/Jackett/Jackett/files/4497507/M-Team.-.TP.Search.results.for.tt0421715.-.Powered.by.NexusPHP.zip)


> Some site provide the full title as a tooltip when you hover over the title in the row, or as a popup with a picture and full title and other data displayed.

Hovering over some short titles, which are already displayed fully, shows the title again. Hovering  over truncated titles does nothing. 



> if that full title is not available there, then the only way would be to issue a separate requests to fetch the details page, for each and every row on the results page, every time you do a search.

That's the exact scenario that I want to avoid.



> The only other alternate way, is if the web site has an API that returns json or xml when queries are made to it,

I don't know for sure, but I don't think any of the Chinese NexusPHP trackers has an API. How can I double check?

**Comment by RoloSoze** [comment]
I also forgot to mention that some titles are not restricted by the maximum character length for some reason. The first result below is an example:

![image](https://user-images.githubusercontent.com/23747425/79670323-0b1dd680-8190-11ea-9c86-eaa0c73a125c.png)

[M-Team - TP   Search results for tt0443680 - Powered by NexusPHP.zip](https://github.com/Jackett/Jackett/files/4497543/M-Team.-.TP.Search.results.for.tt0443680.-.Powered.by.NexusPHP.zip)

**Comment by garfield69** [comment]
>I don't think any of the Chinese NexusPHP trackers has an API. How can I double check?

only by reading the FAQ or looking for an API tag in the footer, or asking a question from the admins if they have such a service or not.

**Comment by RoloSoze** [comment]
> Only by reading the FAQ or looking for an API tag in the footer, or asking a question from the admins if they have such a service or not.

Negative to all, and I guess there's nothing in the HTML that can be used? 

I'll put this on hold for now and will try again to get the staff to increase the maximum character limit.

**Comment by RoloSoze** [comment]
> The first thing to do would be to dump the HTML from the web site search results page so that we can check if the full title is available. Some sites provide the full title as a tooltip when you hover over the title in the row, or as a popup with a picture and full title and other data displayed. If the full title is available someplace in the row, we can extract it and use it.

@garfield69 I figured out what the issue was. I'll document it here in case someone faces this problem in the future:

On MTTP's website, go to User CP > Tracker Settings > Torrents Page > Tooltip type on torrent name: 'Off'

Tooltip type needs to be turned off in order for the full name to be displayed when hovering over the shortened link. The website will still shorten long torrent names, but now the HTML code includes the full release name, so I guess names can now be displayed in full in Jackett as long as the tooltip is set to 'Off'

Here's the updated HTML code when the tooltip is turned off:
[M-Team - TP   Search results for tt0421715 - Powered by NexusPHP.zip](https://github.com/Jackett/Jackett/files/4499721/M-Team.-.TP.Search.results.for.tt0421715.-.Powered.by.NexusPHP.zip)

**Comment by garfield69** [comment]
this is already an info block in the config panel for this indexer
```
About Titles
      For best results disable the torrent name tooltip (User CP/Tracker Settings/Torrents Page). Otherwise long release names will be cut off.
```
no one thought to check/read this I guess ;-b

**Comment by RoloSoze** [comment]
*Facepalm*
