### ISSUE TITLE
[enhancement] have Cadigann provide .Config.currentyear

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#8258]
there are many yaml indexers that do not allow keyword-less searches
and for most of these we supply the year as a way to get at least some current results
however these are hard-coded, usually with the year the indexer was created.
Which obviously means that currently I need to refresh these indexers yearly to update 2019 to 2020 
It would be really useful, if Cardigan could provide a default variable, such as .Config.currentyear
so that this routine update is no longer required.

**Comment by cadatoiva** [comment]
Is this the only kind of date data you need is CurrentYear? The way C# accesses this information is `DateTime.Today.Year` or `DateTime.Now.Year` with the difference being `.Now` includes the current time and `.Today` is (as example) 4/19/2020 at 12:00am (midnight)

So we could add `.Today.Year` as your CurrentYear variable, but if needed we could add other Date/Time variables as needed as well under either `.Today` or `.Now` as appropriate.

**Comment by garfield69** [comment]
For now, the only date info I have need of, is the yyyy so I can use it in place of the keywordless search the TEST button invokes, for some of the indexers that currently have 2019 hard-coded.
In whatever delivery method is available. Thanks.

**Comment by garfield69** [comment]
Jackett 0.16.71
