### ISSUE TITLE
[req] Fou-Du-Cinema

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#8260]
Name : Fou Du cinema
~~Private~~ Semi-Private
URL : ~~https://fou-du-cinema.net/~~ https://fou-du-cinema.ca/
Language : French
Type : Movies, TV Series, Documentaries, General.

**Comment by garfield69** [comment]
public, semi-private, private?
if private, is registrations open currently or invite only?
if invite only, are you able to provide one?

**Comment by pipopop** [comment]
Seems that registrations are currently open. If you got any problem, I can send you an invitation.
More information : seems to be the same architecture as Galeriens and Le Chaudron.

**Comment by garfield69** [comment]
registration and login successful.

**Comment by garfield69** [comment]
Jackett 0.16.71

**Comment by pipopop** [comment]
Works great ! thank you !

**Comment by pipopop** [comment]
Site rewrited. Users deleted
registration are opened : https://fou-du-cinema.net/

thanks for all !

**Comment by garfield69** [comment]
the sites engine has been upgraded. 
new registration required. 
todo: update indexer

**Comment by garfield69** [comment]
@pipopop  have you've taken a look at the new site requirements?
My French is poor and Google's translate is not very good at capturing those subtle meanings in phrases.
What is my minimum obligation to keep an account active on this site?
Thanks.

**Comment by garfield69** [comment]
2 days 28 hours and my account gets disabled :-D
I'd better finish the conversion for the site before then ;-)

**Comment by pipopop** [comment]
I think it's 2 months, 28 days ;)

**Comment by pipopop** [comment]
thanls a lot !

**Comment by garfield69** [comment]
so what did you have to do to stop your countdown clock?

**Comment by garfield69** [comment]
Jackett 0.16.1842

**Comment by pipopop** [comment]
Already ! Whaou god job !
Tested. Works great.
I download a torrent perhaps ?
Bu I think you have 2 months before closing your account:
0000 - 02 - 28 - 10 - 11 - 38 (2 months, 28 days, 10 hours, 11 minutes, 38 seconds).
Thanks again.

**Comment by pipopop** [comment]
Hello @garfield69 .
Sorry, I made a mistake. It's not a private tracker, it's a semi-private tracker.
Have a good day !

**Comment by garfield69** [comment]
no problem its a simple update.

**Comment by garfield69** [comment]
Jackett 0.16.2256

**Comment by garfield69** [comment]
https://fou-du-cinema.net/ returns HTTP ERROR 500 when trying to login
I get the login page if I remove all the cookies, but after entering credentials I get 500
just me or is the site broken?

**Comment by pipopop** [comment]
Same for my. I will post more informations this afternoon.

**Comment by ilike2burnthing** [comment]
Login page is backup, but it has changed. I can't login, and trying to recover my account says it doesn't exist.

There's no signup/register/application page, just a contact form, so I'll give it a few days and if I still can't sign in then I'll use that.

**Comment by garfield69** [comment]
Looks like they have had to start from scratch, and installed a new Engine cloned off a German source, the login page is similar to fantasticheaven.yml
Expect it all to become French at some point which may then indicate a return to normality.

**Comment by garfield69** [comment]
login is now all in French and Registration form is available. 
I've filled mine in and am waiting for the confirmation email which has yet to arrive.

**Comment by ilike2burnthing** [comment]
Just after doing the same. Email never came, but was able to log in anyway. Bad news though, that stupid countdown clock is back.

**Comment by ilike2burnthing** [comment]
@garfield69 can you check the torrent download is working? There are only 2 torrents so far, and only one actually has a 'thank you' button, and I've already used it in browser.

**Comment by garfield69** [comment]
v0.20.1117

**Comment by ilike2burnthing** [comment]
Looks like my account has been deleted... Same for you? Registration has been closed as well.

**Comment by garfield69** [comment]
>Looks like my account has been deleted... Same for you? 

Yes.

**Comment by pipopop** [comment]
Tracker has reoppen : https://fou-du-cinema.ca
Everything was deleted. Restart from 0.
You have to signup with an account.

**Comment by ilike2burnthing** [comment]
[v0.20.1125](https://github.com/Jackett/Jackett/releases/tag/v0.20.1125)

**Comment by garfield69** [comment]
https://fou-du-cinema.ca/ redirects to https://fou-du-cinema.ca/cgi-sys/suspendedpage.cgi

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://fou-du-cinema.ca/  HTTP ERROR 500

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
as long as you are already logged into the site you are good.
however, if you need to login the captcha is not working so login fails because you did not add the numbers!
console log shows the captcha image gets a 403

**Comment by ilike2burnthing** [comment]
Opening it in a private window, I'm not being asked for a captcha answer and am able to log in without it.

**Comment by ilike2burnthing** [comment]
https://fou-du-cinema.ca/ - Account Suspended

**Comment by garfield69** [comment]
@pipopop  do you have any info on fou-du-cinema.ca, is the site gone, broken, or moved to a new domain?

**Comment by ilike2burnthing** [comment]
Given we have les-cinephiles now, do we want to remove fou?

**Comment by garfield69** [comment]
IF you want to go early have at it. 😁

**Comment by garfield69** [comment]
v0.20.2670

**Comment by ilike2burnthing** [comment]
Looks like https://fou-du-cinema.ca is back, now using TorrentTrader v2. Though registration is currently closed and there's only 3 torrents on it.

**Comment by garfield69** [comment]
https://fou-du-cinema.ca/ domain not found. Closing.
