### ISSUE TITLE
[REQ] [myanonamouse] Option to use with dynamic IP

### ISSUE THREAD

**Issue by janot** [Jackett/Jackett#8265]
E.g. login/password

Current `mam_id` method requires static IP

**Comment by cadatoiva** [comment]
We currently do not have any developers with access to this tracker to make changes. An invite will need to be sent to a dev that volunteers to update the tracker.

**Comment by garfield69** [comment]
FYI 
the myanonamouse indexer was changed in Nov 2018 to support the web sites API changes.
this required the use of the mam_id instead of the username/password that you might use to access the website via browser. see #4118

**Comment by janot** [comment]
Sorry, I should've tested it before creating issue. It works on dynamic IP
