### ISSUE TITLE
core: remove recaptcha legacy code

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8268]
All the code in the WebUI to resolve the reCaptcha challenge is disabled (because it's not working). We are always displaying the cookie as fallback.
![image](https://user-images.githubusercontent.com/10577978/79696376-9f656780-827c-11ea-9589-b44240c6cd18.png)
We have to remove related code in the Server too. `RecaptchaItem` and a lot of code in `CardigannIndexer`.

**Comment by MalaGaM** [comment]
Maybe replace with hCaptcha rather than delete. See [issues:8270](https://github.com/Jackett/Jackett/issues/8270)

[How to switch from reCAPTCHA to hCaptcha]( https://docs.hcaptcha.com/switch#clientside)
