### ISSUE TITLE
[filelist] Error calling provider filelist: Clearance failed after 30 attempt(s). (Config)

### ISSUE THREAD

**Issue by stefanelul2000** [Jackett/Jackett#8287]
### Environment

Using Docker container linuxserver/jackett:latest

**Are you using a proxy or VPN?** [yes/no]
NO

### Description

I tried to update the password on the Filelist Tracker and I got the error in the title.

**Comment by garfield69** [comment]
The FileList's Jackett integration was updated a couple of days ago to use the API. If you have version 0.16.54 or newer, you'll need to reconfigure FileList in Jackett using your 'Passkey' instead of your password, which you can get from your FL profile settings page: https://filelist.io/my.php
