### ISSUE TITLE
[req] add the same indexer several times

### ISSUE THREAD

**Issue by tchirou** [Jackett/Jackett#8290]
Hello
Sorry if this is not the proper way to ask for a feature, I have searched but haven’t found this request before
If we run multiples sonarrs and radarrs for multi languages, it would be great to be able to add the same indexer multiples times to set them up differently according to the different options. 
Is this something possible to consider ?
Thanks a lot

**Comment by ilike2burnthing** [comment]
If you're already running multiple instances of Sonarr and Radarr, why not do the same for Jackett?

**Comment by cadatoiva** [comment]
There is another request ticket already open for this kind of functionality. #7163

**Comment by tchirou** [comment]
> If you're already running multiple instances of Sonarr and Radarr, why not do the same for Jackett?

Actually, there is one sonarr and one radarr on my home nas and one sonarr and one radarr on a foreign server
All of them points to my home jackett as my main indexer is a semi private tracker.
Home is for English and the foreign one is for multi+French.
I don’t have docker so I cannot run several instances of jackett on my nas.

I hadn’t seen Ticket 7163 And it is closed. I understand the enhancement is declined if it is too much work. 

Anyway, I managed for now to reach my goal by manipulating the « multi » options in the indexers.

Thanks
