### ISSUE TITLE
Groups of trackers

### ISSUE THREAD

**Issue by vonProteus** [Jackett/Jackett#8298]
i use radarr and jackett
at the moment jackett is added to the radar by http://jackett:9117/api/v2.0/indexers/all/results/torznab/ 
it is brilliant but I would like to create a my own groups of trackers like *all* but from selected trackers
something like this

* *all* http://jackett:9117/api/v2.0/indexers/all/results/torznab/ 
* *myPrivateTrackers1* http://jackett:9117/api/v2.0/indexers/myPrivateTrackers1/results/torznab/ 
* *myTrackersGroup2* http://jackett:9117/api/v2.0/indexers/myTrackersGroup2/results/torznab/ 
* *myPublicTrackers3* http://jackett:9117/api/v2.0/indexers/myPublicTrackers3/results/torznab/

**Comment by RoloSoze** [comment]
Similar to #4787 #2185

**Comment by cadatoiva** [comment]
Not just similar, it is a duplicate of the functionality to be implemented by #2185. Follow that issue for updates

**Comment by vonProteus** [comment]
thanks
