### ISSUE TITLE
Cloudflare anti-ddos [yggcookie] Exception (yggcookie): Clearance failed after 30 attempt(s).: Clearance failed after 30 attempt(s). (Test)

### ISSUE THREAD

**Issue by CyberPoison** [Jackett/Jackett#8305]
# Environment

**OS**: Ubuntu 18.04 (Docker)

**Jackett Version**: Version 0.16.96.0

**Last Working Jackett Version**: Version 0.16.96.0

**Are you using a proxy or VPN?** no

### Description

Go to Jacket and after go to the YggCookies follow the tutorial and after you put the cookie and the user-agent you will get the issue related above.

### Logged Error Messages
```
Jackett.Common.IndexerException: Exception (yggcookie): Clearance failed after 30 attempt(s).
 ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 164
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 442
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1341
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 803
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 223
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```

### Screenshots

![image](https://user-images.githubusercontent.com/60718477/79940989-866adb00-8463-11ea-85cf-b4e556b08379.png)

###NOTE:
**This issue is related with my previous issue #8304 #8229 ** 

I alos used xorg to acess to my remote machine and use firefox to get the cookie string and user-agent btw this doesn't have fixed my issue.

**Comment by garfield69** [comment]
Unfortunately, there is nothing further the team can do for you about this at the moment.
#8270 may provide relief if it gets implemented.

**Comment by drloser123** [comment]
Same problem here.

**Comment by xfouloux** [comment]
hi, I hope #8270 could be implemented soon and easily :/ ! This is the main/biggest french tracker for most of us french users ^^ !
In any case, implementing captcha bypass solution via paying sites will be beneficial for other trackers that use or will use this cloudflare protection in the future, or other captcha login pages like metaltracker.

Thanks in advance =)

**Comment by tchirou** [comment]
Even from my home nas, it doesn’t work anymore. I regularly manually connect from my browser with the same ip but the ip is not whitelisted.

**Comment by pinedours** [comment]
Even from my home too .. !

**Comment by CyberPoison** [comment]
@xfouloux a paid service can be bad for who have a large monitored/indexed movies to search through the ygg cuz you hit the captcha in few days/hours.
Not sure how it works but in my case I downloaded 5K movies in 3 month from ygg so imagine how much I will pay to grab 5K movies and I have 6K missing in radarr so after some hours the radarr scan the ygg to check if the movies as been uploaded and for in many times it doesn't grab nothing only 4 in 6K missing movies so 5.996 request is done for nothing so recaptcha for every 5.996 request for getting nothing is not helpful.
A way to bypass the hcaptcha for unlimited request will be nice I use also xthor but many movies / spectacle are missing ex:. Riverdace: live in Beijing .
So yeah I agree than ygg as and is the best tracker but maybe there was a reason why they have enabled the (Under attack option) in cloudflare but no idea why.

So to resume:
A cloudflare bypass unlimited token/request will be nice. 
And why ygg have enabled the Under attack in cloudflare this is a good question. 

I presume than the ygg moderation have enabled it to prevent scraping ** but ** why they don't do a pay option like 20€ year unlimited request to the website.

BTW, I enjoy this tracker and I pretty sure than their web hosting have ddos protection so pretty sure they use it again scraping, but there will be alternatives like bypass cloudflare hcaptcha

@garfield69 what do think can you give us your opinion.

**Comment by foux** [comment]
Same for me, since this morning, doesn't works be it cookie or password :/

**Comment by fl4shback** [comment]
There is a thread (French language) going on on ygg forum, it might grab staff attention at some point..
https://www2.yggtorrent.se/forum/index.php?threads/probleme-jackett.31799/
Let's hope for it

**Comment by foux** [comment]
> There is a thread (French language) going on on ygg forum, it might grab staff attention at some point..
> https://www2.yggtorrent.se/forum/index.php?threads/probleme-jackett.31799/
> Let's hope for it

Not a lot to hope on that side. ygg team certainly won't do anything to help scraping the site, that's against their interest. On the contrary, a post like this tells them that they are doing the right thing.

**Comment by Bastien42** [comment]
Same for me here + 1337x as the same issue with cloudflare anti-DDos protection

**Comment by cadatoiva** [comment]
@foux it's not necessarily against their interests. There are quite a few sites that open up automation APIs and passkeys to make using programs like Jackett easier to use with their site. If people get upset enough about not being able to use Jackett or similar, they'll leave the site. Fewer members means fewer donations, fewer seeders, and a worse experience for everyone on the site.

**Comment by foolishjedi** [comment]
im get this on on torrentday. with and without vpn/proxy 
![Screenshot_2020-04-22 Jackett](https://user-images.githubusercontent.com/64152568/80008560-cf507d00-84bf-11ea-96f1-aae807e7bbb0.png)

**Comment by garfield69** [comment]
Try out Jackett 0.16.105 and see if that resolves the issue with using the YGGTorrent Indexer.
Don't forget after upgrading, to first check the indexer's config with the Wrench to ensure that the 
**SiteLink** is still set to `https://yggtorrent.se/` and that the
**SearchURL** is still set to `www2.yggtorrent.se`
Works for me.

**Comment by Bastien42** [comment]
+1 it works solved

**Comment by navycrow** [comment]
+2 YGGCookie and YGGTorrent work !!!

**Comment by drloser123** [comment]
It's working. Many thanks.

**Comment by tchirou** [comment]
Wonderful ! Thanks a lot 🙏🏻

**Comment by xfouloux** [comment]
> @xfouloux a paid service can be bad for who have a large monitored/indexed movies to search through the ygg cuz you hit the captcha in few days/hours.
> Not sure how it works but in my case I downloaded 5K movies in 3 month from ygg so imagine how much I will pay to grab 5K movies and I have 6K missing in radarr so after some hours the radarr scan the ygg to check if the movies as been uploaded and for in many times it doesn't grab nothing only 4 in 6K missing movies so 5.996 request is done for nothing so recaptcha for every 5.996 request for getting nothing is not helpful.
> A way to bypass the hcaptcha for unlimited request will be nice I use also xthor but many movies / spectacle are missing ex:. Riverdace: live in Beijing .
> So yeah I agree than ygg as and is the best tracker but maybe there was a reason why they have enabled the (Under attack option) in cloudflare but no idea why.
> 
> So to resume:
> A cloudflare bypass unlimited token/request will be nice.
> And why ygg have enabled the Under attack in cloudflare this is a good question.
> 
> I presume than the ygg moderation have enabled it to prevent scraping ** but ** why they don't do a pay option like 20€ year unlimited request to the website.
> 
> BTW, I enjoy this tracker and I pretty sure than their web hosting have ddos protection so pretty sure they use it again scraping, but there will be alternatives like bypass cloudflare hcaptcha
> 
> @garfield69 what do think can you give us your opinion.

Well, paid services for captcha are about 1000 captcha for less than 1$ so not an issue, it's really cheap, i already have such a service for bazarr and addict7d, i've put 10$ in it since and not even reached 1$ spend in more than a year.
When you solve a captcha, your IP (feederbox) is then ok for some time, you don't get the captcha on every request

But yeah i agree, why trackers does not go the same way as usenet indexer, and gives us like a paid service for a good unlimited API

**Comment by xfouloux** [comment]
> Try out Jackett 0.16.105 and see if that resolves the issue with using the YGGTorrent Indexer.
> Don't forget after upgrading, to first check the indexer's config with the Wrench to ensure that the
> **SiteLink** is still set to `https://yggtorrent.se/` and that the
> **SearchURL** is still set to `www2.yggtorrent.se`
> Works for me.

Hey @garfield69 any changes to Jackett or just YGG stopped using the cloudflare protection ?

Regards

**Comment by garfield69** [comment]
ngosang  updated the custom CloudflareSolverRe that Jackett is using to handle the new challenge.

**Comment by Nicode70** [comment]
It doesn't seems to have solved the issue. i have this error message after upgrading to 0.16.105.0
![Capture d’écran 2020-04-23 à 17 37 29](https://user-images.githubusercontent.com/16838672/80118940-5a497a00-8589-11ea-91c1-8f6aca0534b8.jpg)

**Comment by bossovitch** [comment]
same here..
the new version of ygg indexer don't solve the problem for me too..both on torrent or cookie, on my server, but on my home nas, it seem to be ok with the new version for the moment

**Comment by fl4shback** [comment]
> It doesn't seems to have solved the issue. i have this error message after upgrading to 0.16.105.0
> ![Capture d’écran 2020-04-23 à 17 37 29](https://user-images.githubusercontent.com/16838672/80118940-5a497a00-8589-11ea-91c1-8f6aca0534b8.jpg)


> same here..
> the new version of ygg indexer don't solve the problem for me too..both on torrent or cookie, on my server, but on my home nas, it seem to be ok with the new version for the moment

Are you using any proxy/vpn ?
Just disabled my VPN to test and it worked. If I leave it on, same error as yours.

**Comment by Nicode70** [comment]
it's running on a seedbox, there might be a vpn, but i can't say for sure.

**Comment by tchirou** [comment]
I agree with fl4shback
Best course of action is to put jackett on a nas or a raspberry at home and point sonarr/radarr to the home jackett

**Comment by Sebclem** [comment]
The issue is back for me too, hosted at home...

**Comment by bossovitch** [comment]
No proxy or vpn for me, I'm on the 0.16.105.0 (the last no?), and the issue is present, but not on my home Nas..with the same version
It seem that CloudFare have banned some group of server IP...I'm on a dedibox in a datacenter somewhere in Amsterdam...

**Comment by tchirou** [comment]
Another solution could be (not tested) using a vpn with a french ip

**Comment by bossovitch** [comment]
Yes,this could be a solution, but how? Jackett doesn't support vpn no? Or it is the entire linux system...or with some IP rule,but i don't know how...

**Comment by tchirou** [comment]
You would need to install openvpn on the server I guess

**Comment by bossovitch** [comment]
Yes..i don't want to route all the traffic trough the vpn.i will try the proxy of my NAS, perhaps it will work ..

**Comment by tchirou** [comment]
If you have a nas, why don’t you install jackett on it and point the sonarr and radarr of your dedibox on it ? Simple and free

**Comment by bossovitch** [comment]
oh, i've doing that for the moment, but my nas is so slowly compare to my server....but it work yes!i can stay like that and waiting and bypass method or still CloudFare clear their list
I will probably test the proxy, just for the test!

**Comment by tchirou** [comment]
You should remove ygg from your dedibox jackett for now to prevent it to regularly make test connexions and keep the ban alive

**Comment by bossovitch** [comment]
yes, good idea!
thanks

**Comment by SkYNewZ** [comment]
So what can we do for ?

**Comment by Sbassava** [comment]
I have the same issue on a nas running at home with a french IP so I don't know if running Jackettt at home can help bypassing the cloudflare check..
