### ISSUE TITLE
Norbits - Better search function

### ISSUE THREAD

**Issue by DiseaseNO** [Jackett/Jackett#831]
Hi

Because of both special characters and the "replacements" used in releases in this site we need to do a second search if the searchstring contains one of them. Then combine the result. An example:

Nytt.På.Nytt.S01E01.Release.something
and
Nytt.Paa.Nytt.S01E01.Release.something

So if the search contains æ - ø  - å, we need to replace them in a second search and search for ae - o - aa also. If not, alot of episodes is missing. 

I tried to do it, but failed. 

Have no invite, but I can do the testing.

**Comment by kaso17** [comment]
You'll have to essentially move the request/parsing code from PerformQuery() to a new method and call that method twice with the different searchTerms and finally merge the results.

**Comment by DiseaseNO** [comment]
Okei. Thanks. 

And btw the language parameter in norbits.cs should be nb-no. Not nn-no :)

**Comment by kaso17** [comment]
fixed the language, thank you.

**Comment by flightlevel** [comment]
@DiseaseNO Can this be closed now?

**Comment by armani316** [comment]
@DiseaseNO Has this enhancement been implemented yet?

**Comment by armani316** [comment]
As far as I know, the alphabet replacements that @DiseaseNO suggested are the only applicable ones in the Norwegian & Danish alphabet:

æ = ae
Æ = AE 	

Ø  = O	
ø = o

å = a
Å = A

If we are to include the Swedish alphabet, the following replacements are applicable:

å = a
Å = A

ä = a
Ä = A

ö = o
Ö = O

For the Finnish alphabet:

å = a
Å = A

ä = a
Ä = A

ö = o
Ö = O

š = s
Š = S

ž = z
Ž = Z

I'm not entirely sure about the Icelandic alphabet. Maybe a native speaker can help out with this one. I suggest applying these to all Nordic trackers supported by Jackett (DanishBits, HoundDawgs, SuPerBits). 

I'll also try to suggest similar alphabet replacements for European trackers whose native language is not English.

**Comment by kaso17** [comment]
Searching twice (with/without diacritics) has been added with a34a3fb4b682e2b25dcd210d0c8db7d45fb3603e
also added missing categories with 34cdedae12f84cee19b0da33d8149f18f8fb2459
