### ISSUE TITLE
[DivxTotal] & [BTeye] - Clearance failed after 30 attempt(s)

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8314]
0.16.103.0 Docker and Windows sandbox, tried previous builds with same result.

Tried deleting indexers, restarting Jackett, and re-adding - same result.

No VPN or proxy.

Sites work in browser - Cloudflare anti-DDOS wait page, no visible captcha.

Issue started today.

[log - divxtotal.txt](https://github.com/Jackett/Jackett/files/4517100/log.-.divxtotal.txt)
[log - bteye.txt](https://github.com/Jackett/Jackett/files/4517101/log.-.bteye.txt)

#8270 related?

**Comment by foux** [comment]
Related #8300 , #8270 and #8274 yes

**Comment by RoloSoze** [comment]
and Torrentz2
