### ISSUE TITLE
Enabling/disabling external access or proxy, while enhanced logging is enabled, unticks enhanced logging but leaves it enabled

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8315]
0.16.103.0 Dockers and Windows sandbox. Happens on earlier versions too.

Steps to reproduce:
1. enable enhanced logging, apply - enhanced logging is ticked on refresh
2. run test - log shows enhanced logging working
3. enable or disable external access (or proxy), apply - enhanced logging is unticked on refresh
4. run test - log shows enhanced logging still enabled (running multiple tests doesn't change this)
5. apply server setting again or restart Jackett - enhanced logging is unticked on refresh
6. run test - log shows enhanced logging now disabled

Also occurs if you enable enhanced logging and external access or proxy at the same time:
1. enable enhanced logging and external access (or proxy), apply - enhanced logging is unticked on refresh
2. run test - log shows enhanced logging working
3. apply server settings again or restart Jackett - enhanced logging is unticked on refresh
4. run test - log shows enhanced logging now disabled

Not sure if the intended behaviour is to disable enhanced logging on these changes, and that's not happening, or if enhanced logging is supposed to remain enabled and it's simply a webUI error.

Disable auto update and Update to pre-release do not seem to be affected. Not sure about other options.

**Comment by cadatoiva** [comment]
It's likely a bit of both. When applying server settings, Jackett does a half-restart, and enhanced logging is disabled on full-restart of the server. The web-UI is likely taking cues from the half-restart and treating it like a full restart, thus clearing the checkbox, but it's likely that these half restarts should also disable enhanced logging, or maybe not.
