### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): L’opération d’entrée/sortie a été abandonnée en raison de l’arrêt d’un thread ou à la demande d’une application.: The operation was canceled. (Test)

### ISSUE THREAD

**Issue by RaphaelDucay** [Jackett/Jackett#8316]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Win 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] .Net-Framework

**.Net Version**: 4.0

**Jackett Version**: 0.16.96.0

**Last Working Jackett Version**: 0.16.96.0

**Are you using a proxy or VPN?** [yes/no] no

### Description

Yggtorrent Indexer is broken since today (last functionning attempt was yesterday)

### Logged Error Messages
[yggtorrent] Exception (yggtorrent): L’opération d’entrée/sortie a été abandonnée en raison de l’arrêt d’un thread ou à la demande d’une application.: The operation was canceled. (Test)
[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots
![image](https://user-images.githubusercontent.com/9933141/80021870-7d1d5500-84db-11ea-9e3b-daf74b3ffd1c.png)
![image](https://user-images.githubusercontent.com/9933141/80022120-e309dc80-84db-11ea-856d-7434c2156f59.png)

[Place any screenshots of the issue here if needed]

**Comment by RaphaelDucay** [comment]
updated to last release version 0.16.103.0 and still not working

**Comment by RaphaelDucay** [comment]
the yggtorrent website and its search api is still fully fontionnal 
![image](https://user-images.githubusercontent.com/9933141/80023255-8b6c7080-84dd-11ea-9621-b45b3493e665.png)

**Comment by lebnet** [comment]
Check issue #8305

**Comment by garfield69** [comment]
YGGTorrent have changed their cloudflare anti-DDoS again, and now neither the Jackett YGGTorrent or the YGGCookie will work.
Follow #8305 for updates.
In the mean time you are just going to have to use your browser.
