### ISSUE TITLE
[HD-Torrents] Exception (hdtorrents): Specified argument was out of the range of valid values. (Parameter 'index'): Parse error (Config)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8323]
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.16.103

**Last Working Jackett Version**: 0.16.96

**Are you using a proxy or VPN?** No

### Description

I'm unable to configure HD-Torrents.

### Logged Error Messages
I get the following error when trying to configure HD-Torrents:

`Exception (hdtorrents): Specified argument was out of the range of valid values. (Parameter 'index'): Parse error`

Enhanced log:
Will provide it if needed, but it seems like it's an issue due to changes made by HDT, so it's probably affecting everyone?

### Screenshots
Not needed

**Comment by ngosang** [comment]
@RoloSoze I tested it and it's ok. I can't make it fail.

**Comment by RoloSoze** [comment]
@ngosang That's because it's fixed now! It was an issue for a couple of days, now it's working fine for me, too. Looks like they fixed it on their end. Thanks!
