### ISSUE TITLE
[passthepopcorn] Parse error (Config)

### ISSUE THREAD

**Issue by Gatewayy** [Jackett/Jackett#8325]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
@cadatoiva  are you having any issues with PTP?

**Comment by RoloSoze** [comment]
Working fine for me.

**Comment by garfield69** [comment]
@Gatewayy  if you want help with this then please provide as best you can the info requested in the first post of this ticket and a full enhanced log so we can look into this for you
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
oh, and before starting in the details, make sure you upgrade to the latest Jackett 0.16.105 to be sure that the issue has not already been resolved
