### ISSUE TITLE
[NordicBits] No connection could be made because the target machine actively refused it (Config)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8333]
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.16.105

**Last Working Jackett Version**: 0.16.96

**Are you using a proxy or VPN?** No

### Description
I'm unable to configure NordicBits. The problem started happening when the domain came back up after briefly going offline https://github.com/Jackett/Jackett/issues/2348#issuecomment-618078245 I'm able to access and search the website just fine and have changed nothing in the configuration settings since the last time it worked.

### Logged Error Messages
`An error occurred while updating this indexer`
`No connection could be made because the target machine actively refused it.` 
`No connection could be made because the target machine actively refused it.`

Enhanced log:
[log.txt](https://github.com/Jackett/Jackett/files/4523475/log.txt)

### Screenshots
Not needed

**Comment by samip5** [comment]
My Jackett works fine.

![image](https://user-images.githubusercontent.com/1703002/80119349-40606500-8592-11ea-9d32-d83499e9a0e9.png)

**Comment by RoloSoze** [comment]
@samip5 It's working fine for @garfield69 as well. The issue seems to be happening on my end but I don't know why.

**Comment by samip5** [comment]
Is Jackett trying to access it though a VPN? DNS resolution works correctly?

**Comment by RoloSoze** [comment]
I'm not using a VPN or proxy. DNS works fine; I'm able to browse the website with no issues.

**Comment by samip5** [comment]
Have you tried simply restarting Jackett? I don't know why that could help but it might.

**Comment by ilike2burnthing** [comment]
> Have you tried simply restarting Jackett? I don't know why that could help but it might.

'Turn it off and on again' fixes 90% of problems 😉

**Comment by RoloSoze** [comment]
I stopped the background service, turned Jackett completely off, closed all running instances, and manually deleted the NordiBits indexer files... Nothing worked.

**Comment by ilike2burnthing** [comment]
If you revert to 0.16.96 does it work again, or was that just the last time it worked?

**Comment by RoloSoze** [comment]
> 
> 
> If you revert to 0.16.96 does it work again, or was that just the last time it worked?

That was just the last time it worked. I tried it now just in case... Negative.

**Comment by ilike2burnthing** [comment]
I think the second point here is the only one we haven't covered yet - https://github.com/Jackett/Jackett/wiki/Troubleshooting#an-existing-connection-was-forcibly-closed-by-the-remote-host

Any ideas from that?

Also, can you access the site if you use Internet Explorer? Trying to rule out that an extension is allowing you access (e.g. using IP header spoofing).

**Comment by RoloSoze** [comment]
@ilike2burnthing I was typing the following when you posted right above me: 
Here's an interesting point: I'm able to access the website `https://nordicb.org/` but not with any Firefox. No other browser, or my phone, is working.

**Comment by ilike2burnthing** [comment]
Not with Firefox? Which browser is working?

**Comment by RoloSoze** [comment]
Sorry, I meant to say, "but only with Firefox" - The other browsers didn't work. I turned my VPN on, and I was able to access the website from all browsers, but when I tried to configure NordicBits in Jackett while the VPN was on, it failed to log me in. Turned the VPN back off, and now it's back to the same 'target machine actively refused it' issue.

**Comment by ilike2burnthing** [comment]
Can you run Firefox in safe mode and see if you still have access to the site?

If you go to Firefox settings, General, Network Settings, are you using system proxy settings, and do you have DNS over HTTPS enabled?

**Comment by RoloSoze** [comment]
> Can you run Firefox in safe mode and see if you still have access to the site?

Yes I can still access it in Safe Mode.

> are you using system proxy settings

Yes



> do you have DNS over HTTPS enabled?

Yes - User Provider: Cloudflare (Default)

**Comment by ilike2burnthing** [comment]
Disable DoH, restart Firefox, see if you still have access?

**Comment by RoloSoze** [comment]
> 
> 
> Disable DoH, restart Firefox, see if you still have access?

Lost access to the website after disabling DoH.

**Comment by ilike2burnthing** [comment]
Windows Control Panel > Network and Internet > Network and Sharing Centre > Change adapter settings > right-click your connection and click Properties > double-click Internet Protocol Version 4 > are you using 1.1.1.1 and 1.0.0.1 for DNS servers?

Same for IPv6 - 2606:4700:4700::1111 and 2606:4700:4700::1001?

I'm assuming yes, but just checking.

**Comment by RoloSoze** [comment]
> are you using 1.1.1.1 and 1.0.0.1 for DNS servers?

No. Both are set to obtain automatically. 



> Same for IPv6 - 2606:4700:4700::1111 and 2606:4700:4700::1001?

No, also set to obtain automatically for both.

**Comment by ilike2burnthing** [comment]
Try enabling both (shouldn't have to restart your computer or flushdns) and try again

**Comment by RoloSoze** [comment]
> Try enabling both (shouldn't have to restart your computer or flushdns) and try again

These settings caused me to lose my Internet connection; had to revert.

**Comment by ilike2burnthing** [comment]
Huh... try just IPv4

**Comment by RoloSoze** [comment]
Gotta deal with another problem first - Ethernet doesn’t have a valid IP configure. Still can’t manage to get my connection back after applying those settings *facepalm*

**Comment by ilike2burnthing** [comment]
In case you need it - 
https://support.pearson.com/getsupport/s/article/Reset-an-Internet-Connection-Flush-DNS

**Comment by ilike2burnthing** [comment]
And just so you know I didn't play a prank on you -
https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/

**Comment by RoloSoze** [comment]
Internet back on. I connected my PC directly to the router instead of the switch, and that solved things. I applied the IPv4 and IPv6 settings you suggested, together. I tried to configure NordicBits while DoH was on, and off. Nothing worked. Still getting the same error message.



> 
> 
> And just so you know I didn't play a prank on you -
> https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/

Haha, don't worry, didn't think you were.

**Comment by RoloSoze** [comment]
As a reminder, this issue started happening only after NordicBits went down and came back up https://github.com/Jackett/Jackett/issues/2348#issuecomment-618078245. While it was down, I didn't change anything at all, and all my other trackers work fine.

**Comment by ilike2burnthing** [comment]
Looks like an ISP block then 😒 

You can either wait for Microsoft to implement DoH (it will be a [while](https://techcommunity.microsoft.com/t5/networking-blog/windows-will-improve-user-privacy-with-dns-over-https/ba-p/1014229)), or use [DNSCrypt](https://dnscrypt.info/implementations).

A possible alternative would be [DPI circumvention](https://github.com/ValdikSS/GoodbyeDPI). But seeing as we know DoH works for Firefox, might as well start there.

**Comment by RoloSoze** [comment]
> 
> 
> Looks like an ISP block then 😒
> 
I doubt it. When my ISP blocks a website, a specific message is shown. That's not the case here. I'll DM the staff and see what they say.

**Comment by RoloSoze** [comment]
I tried, for the second time, to configure it while my VPN was on, and this time it worked. I can search NordicBits in Jackett just fine but only while the VPN is on. As soon as I turn it off, the issue is back again. I know it's not an ISP block, but something's gone wrong on their end for sure. I sent a staff DM to get to the bottom of this.

**Comment by ilike2burnthing** [comment]
If you find out let me know. I don't use NordicBits, but I have some sites that don't work unless I'm using a VPN.

For example, http://thepiratebay.org/ will redirect to https://assets.virginmedia.com/site-blocked.html due to the block, but https://thepiratebay.org/ will give the browser error page `ERR_CONNECTION_CLOSED` (which can be the result of an ISP block, among other things).

Demonoid used to do that, but since it went down (and came back) I can access it fine, no VPN needed.

So it would be useful to know what changed, and if there is anything I can do to resolve it.

I don't suppose http://nordicb.org/login.php results in an ISP block page?

**Comment by RoloSoze** [comment]
> If you find out let me know.

Will do




> I don't suppose http://nordicb.org/login.php results in an ISP block page?

It does not in any browser. The URL/domain is not blocked by my ISP for sure. 

In Firefox, it directs me to the website since I'm logged in already. In Chrome, interestingly I'm getting a `404 Not Found` for both the HTTP and HTTPS versions of the login page, whereas the homepage in Chrome returns the following error `This site can’t be reachednordicb.org refused to connect.`



> 
> 
> EDIT: turn off HTTPS Everywhere/Smart HTTPS if you use it.

I tried accessing the website both using HTTP and HTTPS. There's also an option in the user CP to turn SSL on or off for browsing; tried with both. Same issue.

**Comment by ilike2burnthing** [comment]
Oh, you said you tested accessing it on your phone. Was that while your phone was connected to your wifi? What about mobile data? Just in case the site has blocked your IP address.

**Comment by RoloSoze** [comment]
It was connected to mobile data, so it's not an IP block either.

**Comment by RoloSoze** [comment]
This issue is not too dissimilar from what's currently happening with some Chinese trackers https://github.com/Jackett/Jackett/issues/7950#issuecomment-615231734. If you're not logged in already, you cannot log in until some time in early May. In fact, for some, even existing members, if they try to access the website, they won't be able to. 

The difference here is that I'm actually able to log out and back in, but only with Firefox and only when DoH is on. For other browsers and Jackett, VPN needs to be on for me to be able to log in.

**Comment by ilike2burnthing** [comment]
Also somewhat similar to [this](https://forum.asustor.com/viewtopic.php?f=27&t=11012).

Turned out it was a problem at their end, and got fixed in a day. So fingers crossed it's that simple here.

**Comment by samip5** [comment]
@RoloSoze It seems to me like you're facing a DNS issue.

Can you use https://37.187.94.51 as the address in Jackett and/or other browsers without DoH on? Ignore the SSL warning, as it will complain but say it's nordicb.org which is true.

Proof I'm not tricking you:
```
; <<>> DiG 9.11.5-P4-5.1-Debian <<>> nordicb.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9927
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;nordicb.org.                   IN      A

;; ANSWER SECTION:
nordicb.org.            300     IN      A       37.187.94.51

;; AUTHORITY SECTION:
nordicb.org.            1739    IN      NS      pdns1.registrar-servers.com.
nordicb.org.            1739    IN      NS      pdns2.registrar-servers.com.

;; Query time: 0 msec
;; SERVER: 91.232.156.50#53(91.232.156.50)
;; WHEN: Fri Apr 24 00:36:01 EEST 2020
;; MSG SIZE  rcvd: 117
```

**Comment by RoloSoze** [comment]
> Can you use https://37.187.94.51 as the address in Jackett and/or other browsers without DoH on?

Yes, I'm able to access this address in Firefox with DoH turned off.

**Comment by samip5** [comment]
So yes, it's a DNS issue.

You're using your ISP's DNS servers and changing them makes you loose internet access (well DNS access, not internet)?

**Comment by RoloSoze** [comment]
> So yes, it's a DNS issue.

Alright, but it's always been this way. I haven't had any similar issues with any website, including trackers, until NB went down yesterday. 





> You're using your ISP's DNS servers and changing them makes you loose internet access (well DNS access, not internet)?

Yeah, when I changed the DNS servers, I lost internet for a while, but now I fixed it. 



> If you're using Windows, open up a CMD, and type in `nslookup nordicb.org`. Does it give you an address?

`Microsoft Windows [Version 10.0.18363.778]
(c) 2019 Microsoft Corporation. All rights reserved.`

`C:\Users\Username>nslookup nordicb.org
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  fe80::ca51:95ff:fe96:c3c6`

`DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to UnKnown timed-out`

**Comment by samip5** [comment]
Huh, so it's using wrong address probably for probing the DNS server.

Try this then: `nslookup nordicb.org @ROUTER-IP`

Replace router IP with your actual router, most likely 192.168.1.1 or something like that.

**Comment by samip5** [comment]
> > So yes, it's a DNS issue.
> 
> Alright, but it's always been this way. I haven't had any similar issues with any website, including trackers, until NB went down yesterday.
> 
The thing is that DNS progonation takes a while and when you're using DoH and go to the website, you're actually sending the DNS request at Cloudflare, which already has the correct nameserver to ask from, and thus it works.

Your ISP's nameserver's have greater TTL (keep-alive) to keep those records in cache so it takes longer for DNS to propagate to other resolvers.

https://dnschecker.org/#A/nordicb.org

**Comment by RoloSoze** [comment]
So.... the problem seems to have resolved itself! I am now able to configure NB normally in Jackett and access it with my browser, with DoH both on and off! I did nothing differently. Not sure what happened, but it seems to work fine now!

**Comment by samip5** [comment]
Probably DNS propagation reached your ISP's resolver which fixed it, but that's good. :)
Just so you know next time, that after a domain name expires, it takes about 48 hours for it to start working properly again.

**Comment by RoloSoze** [comment]
>Just so you know next time, that after a domain name expires, it takes about 48 hours for it to start working properly again.

That must've been it then! I thought I'd wait for a while before opening this issue, but evidently, I didn't wait long enough! 

Thank you, @samip5 and @ilike2burnthing for helping me with this! I sincerely appreciate your time!
