### ISSUE TITLE
[req] UniOtaku

### ISSUE THREAD

**Issue by fevecn** [Jackett/Jackett#8340]
UniOtaku is a brazillian semi-private tracker for Animes that supports a ton of fansubs

- Site: https://tracker.uniotaku.com/
- PT_BR subtitles

UniOtaku is a BRAZILIAN Semi-Private Torrent Tracker for ANIME

**Comment by garfield69** [comment]
is this site working for you?
I cannot get the search to do anything, I click on the Buscar button and nothing happens.

**Comment by fevecn** [comment]
The search wasn´t working for me too, but somehow it´s working now

If the problem persists try a search filter like this:
https://i.imgur.com/4rUUA8K.png

**Comment by garfield69** [comment]
they must have had some kind of internal server issue because, as  you said, its working now.
which means I can start work assessing the site for building an indexer.

**Comment by garfield69** [comment]
Jackett 0.16.137

**Comment by garfield69** [comment]
seems the site is no longer providing results via direct HTML
https://tracker.uniotaku.com/torrents.php?categoria=0&grupo=0&status=0&busca=
generates HTML for the outer-body of the results (Doc) but the torrents list is now JSON (XHR)
```
{"recordsTotal":25,"recordsFiltered":2017,"data":[["<a target=\"_blank\" href=\"torrents-details.php?id=2902\">Tenki no Ko [4K][BD]<\/a>  <img class='tipr' title='Gold Coin' src='images\/free.gif' border='0' alt='' \/>","<img border=\"0\" src=\".\/images\/categories\/filme.png\" alt=\"Filme\">","<a href=\"https:\/\/emmidsubs.fansubs.com.br\/tenki-no-ko\/\" target=\"_blank\"><i class=\"fas fa-lg fa-fw m-r-10 fa-download\"><\/i><\/a>","73","1","183","7.2 GB","<a target=\"_blank\" href=\"https:\/\/tracker.uniotaku.com\/teams-view.php?id=40\">EmmidSubs<\/a>","<a href=\"account-details.php?id=774\">Emmid<\/a>"],[etc etc etc]]}
```
this indexer will need to be re-written in C#

**Comment by garfield69** [comment]
bugger, that json set is not the standard key:value layout but something else.
back on the C# queue :-(

**Comment by garfield69** [comment]
v0.20.3105

**Comment by garfield69** [comment]
https://tracker.uniotaku.com/torrents.php  Servidor sobrecarregado  1203

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://tracker.uniotaku.com/ Origin is unreachable Error code 523

**Comment by garfield69** [comment]
online
