### ISSUE TITLE
[PreToMe] Tracker down?

### ISSUE THREAD

**Issue by cadatoiva** [Jackett/Jackett#8344]
https://pretome.info

No login page, doesn't look like it's up anymore.

**Comment by garfield69** [comment]
Its up and working fine. you enter a code in the search box to activate the login

**Comment by RoloSoze** [comment]
You need to enter the passcode you created when you first signed up in the search box on the left, and wait for a few seconds. The username & password will then appear. If this doesn't work in Firefox, try Chrome.

**Comment by cadatoiva** [comment]
Gotcha. I haven't logged in since I got it for Jackett.

**Comment by robertfrain** [comment]
Where is pretome sign up page pls if anyone knows
