### ISSUE TITLE
Rename BTN

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8345]
BTN is currently called `BroadcastTheNet` in Jackett. The correct name is `BroadcasTheNet` wihout the extra `t`.

**Comment by garfield69** [comment]
its been this way since BTN was added in v.0.6.7 back in Oct 2015
... and no one cares

**Comment by RoloSoze** [comment]
Or no one noticed 👀 😆

**Comment by garfield69** [comment]
the thing is that making a change to the name will cause the indexer configs to be dropped for existing users, and force them to create a new one.
I'm not sure its worth putting them through the inconvenience, we don't have an automated way of renaming the config files behind the covers.

**Comment by RoloSoze** [comment]
Gotcha. Forget about it then.

**Comment by cadatoiva** [comment]
Having seen a few trackers merge or rename in the past, it might be worth implementing a system to allow renames without breaking all the existing users' configs

**Comment by garfield69** [comment]
raise an enhancement request then.
