### ISSUE TITLE
BeyondHD [BHD] search issues - Special characters, resolution, rip type/codec & release groups

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#835]
This is an issue because of the way BeyondHD handles search queries, not because of a problem with Jackett. This was discussed briefly before, and I believe a workaround can be done by stripping certain keywords from the search string sent to the tracker and filtering the results in Jackett (credit to @kaso17 for this idea). This is what I found so far:

- Special characters - E.g. Searching for 'Mad Max Fury Road Black & Chrome' returns no results, even when '&' is removed from the search string. Tried searching for this on BHD's website, no results either. However, adding the year (**2015**) to the search string returns results - strange!

- Resolution - E.g. Game of Thrones **1080p** returns no results (both in Jackett & BHD)

- Rip type / codec - E.g. Game of Thrones **REMUX** or Game of Thrones **AVC** returns no results (both in Jackett & BHD) [Codec is probably the least relevant as I never search using codec as a keyword - I'm only mentioning it for the sake of completeness]

- Release group - E.g. Game of Thrones **NTb** returns no results (both in Jackett & BHD) [Is the workaround practical with release groups? Not sure]

If anyone is having similar issues with other trackers, please let us know! Thanks!

**Comment by armani316** [comment]
Any chance of looking into this in the future? From my experience so far, BeyondHD is the only tracker that has such search limitations.

**Comment by kaso17** [comment]
I looked into it and it turns out you can use % as wildcard character.
dbe75616425aa7c001f17d2fe64229bcc592a493 will replace any non standard A-Z/0-9 charcater with % automatically.
That should cover all the examples you provided :)

**Comment by armani316** [comment]
Seems to be working better now, thanks! It actually returns more accurate results compared to searching on BHD's. 

However, I tried searching for Captain America Civil War REMUX and nothing came out. Seems to work in certain instances, but not all. Another example is searching for Mad Max REMUX. Jackett returns 4 results. Searching for Mad Max, and then filtering on keyword REMUX  returns 7 results. Same thing when searching for Mad Max 720p - less results than expected. 

dbe7561 seems to work for certain instances but not all.

**Comment by kaso17** [comment]
Theiy search is really broken...
I'll implement stripping for certain keywords as initially planned

**Comment by armani316** [comment]
@kaso17 Let me know if you'd like me to attach an exhaustive list of those keywords. I can try to cover the 4 categories I mentioned.

**Comment by kaso17** [comment]
that would be appreciated

**Comment by armani316** [comment]
@kaso17 Keywords attached. I left you a couple of notes for audio/video codec and release groups. Let me know if you have any questions or if you need something else. Thanks for your help.

[BHD Keywords.txt](https://github.com/Jackett/Jackett/files/695030/BHD.Keywords.txt)

**Comment by kaso17** [comment]
40978fbce1ba41583ecf666addda0953ea7b7e35 implements the keyword filter

**Comment by armani316** [comment]
@kaso17 Thanks a lot for this, much appreciated. Did you use a particular set of release groups or automatically scanned through all 3 sets and eliminated the dupes?  

A couple of instances where search queries still failed my tests:

- Captain America Civil Wars REMUX returns nothing - should return 2 results. However, using 'REMUX' or REMUX' instead (between apostrophes o with an apostrophe at the end) seems to work. Same thing with The Walking Dead REMUX vs 'REMUX' or REMUX' - more accurate results when apostrophes.

This seems to have something to do with the way BHD's search handles dots (.) and dashes (-), and the presence or absence of spaces.

**Comment by kaso17** [comment]
' get's converted to a wildcard.
Thank you for the hint, we were just missing a tailing wildcard to fix the search, no need for the big keyword lists.
ef3dfad4aa04a8f0f5e8d51bb73fa8617a787142 should take care of the issue.

**Comment by armani316** [comment]
@kaso17 This seems to have fixed the issue completely! Thanks a lot!

One final point, and this is mostly out of curiosity, why does searching for something like FraMeSToR REMUX return only 1 result, while searching using each word individually returns the expected results?

**Comment by kaso17** [comment]
keywords still have to be in the correct order as they appear in the names. Try searching for "REMUX FraMeSToR"

**Comment by armani316** [comment]
Works fine that way, thank you, @kaso17!

**Comment by armani316** [comment]
@kaso17 If you try searching for Arrival 2016 1080p on BHD, the search results do not return the REMUX release. If you remove the 1080p part, you'll find it. Any idea why?

**Comment by kaso17** [comment]
I assume it's related to https://beyond-hd.me/forums.php?action=view_topic&topic_id=1409
Seems like they're handling 720p and 1080p tags in a special way now.
I suggest we just strip the p in Jackett searches?

**Comment by armani316** [comment]
@kaso17 Yeah that works! Thanks! I guess for the sake of completeness, the 'p' & 'i' should be stripped from the search string in Jackett. It's probably a good idea to refer to 'BHD Keywords.txt' I attached up there a while back.

**Comment by kaso17** [comment]
They fixed it (see the forum post). No need for the workaround.

**Comment by RoloSoze** [comment]
@kaso17 Seems like the 'p' and 'i' problem is back. Try searching for something like Manchester by the Sea 1080p and compare the results with Manchester by the Sea 1080. 

Looks like stripping the 'p' and 'i' might be necessary after all. Feel free to refer to the 'BHD Keywords.txt' I attached up there a while back.

**Comment by kaso17** [comment]
fixed with 342cfedcd881f6459575b2bfd6ae54b6ae18f8cb
