### ISSUE TITLE
[req] new public tracker share.xfapi.top

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8351]
http://share.xfapi.top:88/
    466,394 torrents
->
https://bt.xfsub.org/

**Comment by garfield69** [comment]
Jackett 0.16.164

**Comment by ilike2burnthing** [comment]
http://share.xfapi.top:88/ - ERR_CONNECTION_TIMED_OUT

https://bt.xfsub.org/ still times out with 504 error

**Comment by garfield69** [comment]
http://share.xfapi.top:88/ online.
note https://bt.xfsub.org/ is not valid and already in the legacylink.

**Comment by ilike2burnthing** [comment]
https://bt.xfsub.org/ is back online now too

**Comment by garfield69** [comment]
https://bt.xfsub.org/ returning Error 504 Gateway time-out
http://share.xfapi.top:88/ returning ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
> https://bt.xfsub.org/ returning Error 504 Gateway time-out
> http://share.xfapi.top:88/ returning ERR_CONNECTION_REFUSED

Down, same as before

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://bt.xfsub.org/ - Error 504 - Gateway time-out
http://share.xfapi.top:88/ - working

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://bt.xfsub.org/ returning Error 504 Gateway time-out
> http://share.xfapi.top:88/ returning ERR_CONNECTION_REFUSED

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://bt.xfsub.org/ - Error 522 - Connection timed out
http://share.xfapi.top:88/ - working

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://bt.xfsub.org/ - Error 504  - Gateway time-out
http://share.xfapi.top:88/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://bt.xfsub.org/ - ERR_CONNECTION_CLOSED
http://share.xfapi.top:88/ - working

**Comment by garfield69** [comment]
http://bt.xfsub.org/ has been de-registered
![image](https://user-images.githubusercontent.com/6933240/87618203-60f12300-c76d-11ea-86a0-687bbbdb2519.png)
i'll move it to the legacylinks

**Comment by ilike2burnthing** [comment]
http://share.xfapi.top:88/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> http://share.xfapi.top:88/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> http://share.xfapi.top:88/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
http://share.xfapi.top:88/
![xfsub](https://user-images.githubusercontent.com/59480337/90843789-5ae8f600-e35a-11ea-9f38-8c67de70e888.png)

```
XFSUB Tip: Something went wrong! Please try again later!
Possible causes:
The network signal is weak.
The requested page could not be found.
The URL entered is incorrect.
Go back to the previous page or return to the home page.
```

**Comment by ilike2burnthing** [comment]
> http://share.xfapi.top:88/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
whoops

**Comment by ilike2burnthing** [comment]
both now working

**Comment by ilike2burnthing** [comment]
http://share.xfapi.top:88/ - ERR_CONNECTION_TIMED_OUT
https://bt.xfsub.org/ - Error 504 - Gateway time-out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
http://share.xfapi.top:88/ - 404 Not Found
https://share.xfsub.org/ - 404 Not Found

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> http://share.xfapi.top:88/ - ERR_CONNECTION_TIMED_OUT
> https://bt.xfsub.org/ - Error 504 - Gateway time-out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> http://share.xfapi.top:88/ - ERR_CONNECTION_TIMED_OUT
> https://bt.xfsub.org/ - Error 504 - Gateway time-out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://bt.xfsub.org/ - Error 502 - Bad gateway
http://share.xfapi.top:88/ - working

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
http://share.xfapi.top:88/ & https://bt.xfsub.org/
`XFSUB提示：出错了！请稍后再试！`
`XFSUB Tip: Something went wrong! Please try again later!`

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> http://share.xfapi.top:88/ - ERR_CONNECTION_TIMED_OUT
> https://bt.xfsub.org/ - Error 504 - Gateway time-out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> http://share.xfapi.top:88/ - ERR_CONNECTION_TIMED_OUT
> https://bt.xfsub.org/ - Error 504 - Gateway time-out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
http://share.xfapi.top:88/ - ERR_CONNECTION_TIMED_OUT
https://bt.xfsub.org/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
http://share.xfapi.top:88/ - working
https://bt.xfsub.org/ - Error 522 - Connection timed out

**Comment by garfield69** [comment]
both links are timing out for me.
enough.
the site is unreliable and I don't see the point of constantly updating this ticket to list its up and down ever other day.
I am going to remove the indexer.
