### ISSUE TITLE
trackers returning too many or too few results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8359]
Empty search

Name|Results
-- | --
Ebooks-Shares | 0 results
ExoticaZ | 0 results
SceneTime | 0 results
Torrent Downloads | 605 results

**Comment by garfield69** [comment]
you are the only one in the team with an account on ebook-shares so you're best place to research this one yourself.
In the mean time I will look into the rest.

**Comment by garfield69** [comment]
a keyword-less search on torrentdownloads calls https://www.torrentdownloads.info/today
and we have no control on how many results the site returns on this page but clearly it varies from day to day depending on the volume loaded on the day. 
I'm not sure we can do anything about this.

**Comment by garfield69** [comment]
I get exactly 100 results when I do a keyword-less on scenetime
show me your enhanced log to see why you are getting something different.

**Comment by garfield69** [comment]
I get exactly 50 results when I do a keyword-less search on exoticaz
show me your enhanced log to see why you are getting something difference
what is going on here with you and these four sites!?

**Comment by ngosang** [comment]
> Ebooks-Shares

I had unread messages and when that happens you can't show the torrents list. I think this can't be fixed in Cardigann. In C# is possible to check the unread messages, even mark them as read. I think It's ok as it is by now.

> ExoticaZ

Fixed in #8360

> Torrent Downloads

It's ok. I was concerned that we were making many requests. My fault for not looking at the code.

> SceneTime

Still 0 results. I'm on it.

**Comment by ngosang** [comment]
> Scenetime

I had an expired cookie for long time and we were not informing. Fixed in #8374
