### ISSUE TITLE
TorrentLeech - Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by mrangryoven** [Jackett/Jackett#836]
Im trying to use torrentleech but i keep getting the Found no results while trying to browse this tracker error. I have looked around and i have seen many issues with this but they get closed because people dont reply so im not sure what the fix is. I have tried using Latest version (0.7.791) and 0.6.45(On a different machine) (Want to use PirateBay).

Username and Password is correct, not sure why this isn't working. 

https://puu.sh/sLF4j/3520886cd2.png

**Comment by llawwehttam** [comment]
Torrentleech have just gone live with their new site so the scraper is likely broken by this.

**Comment by kaso17** [comment]
Fixed with a854771950a24096aa58f325776ac4604bfe5b78 and adbd6c9d0dd04df47d700239d5540b7073465c8e. Please try v0.7.797
