### ISSUE TITLE
New semi-public italian tracker

### ISSUE THREAD

**Issue by VMax4** [Jackett/Jackett#8364]
Here is the link http://mircrew-releases.org/

It require a valid email (temporary emails are not allowed) but it doesn't require to check the mail box and click a link to be registered.
To become a member with all privileges it's just needed to open a new argument in this section http://mircrew-releases.org/viewforum.php?f=6 
It's only a presentation, after some admin will approve the message the new user is activated and allowed to do everything.
Magnet links sometimes are not under a link but under a text format , anyway you find one kind or the other into the same page of the description and without the "thank you"

**Comment by garfield69** [comment]
until the search engine is working there is little point devoloping an indexer for this site
```
Problema con la funzione di ricerca
Ci scusiamo per i disagi che si stanno verificando con questa funzionalità, ma stiamo lavorando per cercare di risolverli nel più breve tempo possibile.
Il modo migliore per superare il problema è quello di eseguire la ricerca dal box che trovate nel topic con l'elenco alfabetico delle releases (ogni sezione ha il suo topic).
Cliccare qui per vedere un esempio.
Lo Staff
```
post a notice when this is fixed.

**Comment by VMax4** [comment]
Ok i will

**Comment by garfield69** [comment]
search engine is now available.

**Comment by garfield69** [comment]
On closer look this site is not suitable for use with Jackett.
The posts are totally free form, with no consistency regarding whether there will be a magnet or torrent link in the content or the first message, or even if it will be presented as a href or embedded as code.
Some posts require a thank you to reveal a magnet others do not.

The search engine is abysmal requiring users to use four characters or more per word
`+into +the +dark` will not work, but `+into +dark` does.
the results do not include size, seeders, leechers or much else other than the title and a date.
I don;t see the point of adding an indexer for this site.
