### ISSUE TITLE
[torrentz2] Exception (torrentz2): Clearance failed after 30 attempt(s).: Clearance failed after 30 attempt(s). (Test)

### ISSUE THREAD

**Issue by mgowen55** [Jackett/Jackett#8367]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux   (Ultraseedbox)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.14.222.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** yes
### Description

When trying to add 'Torrentz2' to Jackett, after adding it, I get the message 'Test Failed'. I have 8 other trackers added that work well. 

### Logged Error Messages
[Logs.txt](https://github.com/Jackett/Jackett/files/4534590/Logs.txt)

Jackett.Common.IndexerException: Exception (torrentz2): Clearance failed after 30 attempt(s).

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
since your 0.14.222 came out we upgraded our custom cloudflareSolverRe library
upgrade to Jackett 0.16.127 and see if that helps. report back results.

**Comment by mgowen55** [comment]
Thanks. I am working with seedbox people to try to get the update. The 0.14.222 version is the latest that USB will load for me. I will let you know when I hear back.

**Comment by zorglan** [comment]
Hi, from my side version jackett 0.16.127 and same issue with ultraseedbox for YGG

**Comment by garfield69** [comment]
@zorglan  you raised the same report in #8339 so I'm not going to write a response twice.

**Comment by s20coeur** [comment]
Hello,

Same issue here on YGGtorrent

Jackett Version 0.14.459.0

**Comment by garfield69** [comment]
yeah, do you see the title on this ticket... it reads torrentz2. 
for yggtorrent go to #8339

**Comment by sotiris-bos** [comment]
Fix works for me with linuxserver.io docker image
 Jackett Version 0.16.137.0

**Comment by mgowen55** [comment]
I was able to upgrade to Jackett Version 0.16.137.0 and all is well now.
