### ISSUE TITLE
[BitMeTV] (BMTV) - Searching does not return dead torrents | Update: Need to use andmatch filter

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#838]
Similar to the problem we had before with HDT, searching on Jackett will ignore all dead torrents.

**Comment by kaso17** [comment]
Fixed with be542272d163de997b17a9fe05db31590a4b4dbe

**Comment by RoloSoze** [comment]
@kaso17 It also seems like BitMeTV needs an andmatch filter. The tracker has the tendency to spit out so many irrelevant results, particularly when searching multiple trackers.

**Comment by garfield69** [comment]
kaso17 committed on 24 Oct 2017  e6a2646a981bde95bd2cbf46562cc4a04ff4c07d BitMeTV: use and filter
