### ISSUE TITLE
[extratorrent-cd] Exception (extratorrent-cd): The handshake failed due to an unexpected packet format.: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by Przemek458** [Jackett/Jackett#8382]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
you are most likely being blocked by your ISP and being redirected to a blackhole whose certificate is invalid, thus breaking the client-server handshaking negotiation for a secure https session.
If you have a browser running on the same machine as jackett then see what you get when you use the same sitelink as the indexer in your browser.
alternatively/additionally, turn on jackett's **enhanced** logging to get a more detailed log of the traffic leading to the error, as this may provide clues to the issue.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
