### ISSUE TITLE
[SpeedCD] Your cookie did not work: Parse error (Config)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8392]
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.16.156

**Last Working Jackett Version**: N/A since the cookie method has just been introduced in this version of Jackett due to #8366

**Are you using a proxy or VPN?** No

### Description
I'm unable to configure SpeedCD since switching to the cookie method. I made sure to turn off the newly introduced Geo Locking under the Privacy & Security tab, but it didn't help. I also tried both Site Links and tried logging out and back in. I made sure the entire cookie is copied correctly, and tried clearing cookies & site data in Firefox. None of it worked.

### Logged Error Messages
`An error occurred while updating this indexer`
`Your cookie did not work: Parse error`

Enhanced log:
[log.txt](https://github.com/Jackett/Jackett/files/4538868/log.txt)

### Screenshots
Not needed

**Comment by garfield69** [comment]
I am also getting this error, but I don't think its the cookie. 
there is an issue processing the search page which is generating 
**Error on 20200428072534 for Speed.cd.txtSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.SpeedCD.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\SpeedCD.cs:line 148**

Also the site has changed their search engine path
indexer uses https://speed.cd/browse.php?search=lodge+bdrip&c[]=43&c[]=48&c[]=28&c[]=40
but there is a redirect and the site uses  https://speed.cd/browse/43/48/28/40/q/lodge+bdrip
so that should be fixed too.

**Comment by austinwbest** [comment]
`                foreach (var row in rows)
                {
                    var cells = row.QuerySelectorAll("td");

                    var title = row.QuerySelector("td[class='lft'] > div > a").TextContent.Trim();
                    var link = new Uri(SiteLink + row.QuerySelector("img[title='Download']").ParentElement.GetAttribute("href").TrimStart('/'));
                    var comments = new Uri(SiteLink + row.QuerySelector("td[class='lft'] > div > a").GetAttribute("href").TrimStart('/'));
                    var size = ReleaseInfo.GetBytes(cells[4].TextContent);
                    var grabs = ParseUtil.CoerceInt(cells[5].TextContent);
                    var seeders = ParseUtil.CoerceInt(cells[6].TextContent);
                    var leechers = ParseUtil.CoerceInt(cells[7].TextContent);

                    var pubDateStr = row.QuerySelector("span[class^='elapsedDate']").GetAttribute("title").Replace(" at", "");
                    var publishDate = DateTime.ParseExact(pubDateStr, "dddd, MMMM d, yyyy h:mmtt", CultureInfo.InvariantCulture);

                    var cat = row.QuerySelector("a[href^='?c[]=']").GetAttribute("href").Replace("?c[]=", "");
                    var downloadVolumeFactor = row.QuerySelector("span:contains(\"[Freeleech]\")") != null ? 0 : 1;`

You'll need to focus on this section to fix the speed scraping.

**Comment by austinwbest** [comment]
FYI, the site is getting an overhaul which will again change the table you are scraping so expect another change to this soon enough.

**Comment by garfield69** [comment]
Jackett 0.16.175
