### ISSUE TITLE
[JackettTray] appcrash during updater run and requires manual launch 

### ISSUE THREAD

**Issue by Atario** [Jackett/Jackett#8398]
### Environment

**OS**:  Win 7 64-bit

**.Net Runtime**: .Net Core and .Net Framework are both installed…?  ¯\\\_(ツ)\_/¯ 

**.Net Version**:
>\>DotNetVersions.exe
>Currently installed "classic" .NET Versions in the system:
>2.0.50727.5420 Service Pack 2
>3.0.30729.5420 Service Pack 2
>3.5.30729.5420 Service Pack 1
>4.0.0.0
>4.7.03062
>
>\>dotnet --version
>3.1.201

**Jackett Version**:  0.16.164.0

**Last Working Jackett Version**:  No idea, but this problem has been going on for months now

**Are you using a proxy or VPN?** no

### Description

Steps:

1. Leave running as normal
2. Wait, usually anywhere from half a day to a day

Actual:

This error; must run Jackett shortcut again to get tray icon back (service keeps running though)

Expected:

No error; JackettTray continues to run

### Logged Error Messages

Didn't notice any relevant message in [the log](https://github.com/Jackett/Jackett/files/4546467/jackett.log)

### Screenshots

![Error dialog box](https://i.imgur.com/IWZ5ym9.png)

Details text:

```Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	JackettTray.dll
  Application Version:	0.16.164.0
  Application Timestamp:	a2bdd04c
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.23677
  Fault Module Timestamp:	589c9620
  Exception Code:	e0434352
  Exception Offset:	0000c54f
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

**Comment by janot** [comment]
I have similar problem on Win10. Only it dies silently without any error messages.

```
Application: JackettTray.dll
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeLoadException
```

```
Faulting application name: JackettTray.dll, version: 0.16.156.0, time stamp: 0xf86c3940
Faulting module name: KERNELBASE.dll, version: 10.0.18362.778, time stamp: 0x692cf0ab
Exception code: 0xe0434352
Fault offset: 0x00114192
Faulting process id: 0x4fc8
Faulting application start time: 0x01d61d3321e0708c
Faulting application path: C:\ProgramData\Jackett\JackettTray.dll
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 7436fbf0-8424-4481-804d-0a882bb4fd39
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by garfield69** [comment]
I see the same error in my win10 event log as janot 
it occurs whenever the updater is running.

**Comment by gin9980** [comment]
mines crashing randomly too, using windows 7

**Comment by garfield69** [comment]
From the TrayLog.txt
```
2020-02-14 19:19:56.2976 Info Starting Jackett Tray v0.12.1815.0 
2020-02-14 19:19:56.4672 Info Display balloon tip, updated to 0.12.1815.0 
2020-02-15 15:44:06.0731 Info Received signal from tray lock service 
2020-02-15 15:44:06.0731 Info Starting 20 second delay tray launch as Jackett is running as a Windows service: cmd.exe /c timeout 20 > NUL & "C:\ProgramData\Jackett\JackettTray.exe" --UpdatedVersion yes 
2020-02-15 15:44:06.0975 Info Close of tray application initiated 
2020-02-15 15:44:47.8625 Info Starting Jackett Tray v0.13.122.0 
2020-02-15 15:44:47.9951 Info Display balloon tip, updated to 0.13.122.0 
2020-02-17 18:00:40.9849 Info Received signal from tray lock service 
2020-02-17 18:00:40.9899 Info Starting 20 second delay tray launch as Jackett is running as a Windows service: cmd.exe /c timeout 20 > NUL & "C:\ProgramData\Jackett\JackettTray.dll" --UpdatedVersion yes 
```

the log shows that beginning with 0.12.1815 Jackett has been trying to run the .dll instead of the .exe and this is likely the cause of the crash we are seeing in the system events log.

**Comment by garfield69** [comment]
I don't understand
https://github.com/Jackett/Jackett/blob/889a8da4e5f046d029d86aa34b35f2854c9f67ed/src/Jackett.Tray/Main.cs#L100-L109
how does trayExePath end up pointing to `C:\ProgramData\Jackett\JackettTray.dll` instead of `C:\ProgramData\Jackett\JackettTray.exe` ?

**Comment by garfield69** [comment]
@ngosang 
https://github.com/Jackett/Jackett/blob/889a8da4e5f046d029d86aa34b35f2854c9f67ed/src/Jackett.Tray/Main.cs#L100-L109
the trayExePath end up pointing to `C:\ProgramData\Jackett\JackettTray.dll` instead of `C:\ProgramData\Jackett\JackettTray.exe`

would 
```c#
                var trayExePath = Assembly.GetEntryAssembly().Location.Replace(".dll", ".exe");
```
be a suitable solve for this?

**Comment by garfield69** [comment]
Jackett 0.16.1350
