### ISSUE TITLE
TorrentDay Failure

### ISSUE THREAD

**Issue by MrAmos123** [Jackett/Jackett#840]
Downloaded latest version of Jackett v0.7.797 and when setting up the indexer in Jackett, it's trying to connect to TorrentDay - https://www.torrentday.com/.

In the UK torrentday.com is blocked, however https://torrentday.it/ works fine.

I'm unable to add the cookie as it isn't pointing to the correct location.

Cheers,
Amos.

**Comment by kaso17** [comment]
They really can't decide, yesterday they redirected everything back to .com...
According to their forums the .it domain got blocked in UK to:
https://www.torrentday.com/forums.php?t=32275&page=7
If it's still working for you try changing it in the config file manually. That should work for now.

What are the symptoms of the blocking in the UK, does it load forever until you get a timeout or does it get redirected to a information page?

**Comment by MrAmos123** [comment]
Basically... For example, tdonline.org will just time out with "This site can’t be reached tdonline.org unexpectedly closed the connection."

However, when trying to access thepiratebay.se it will return this (from my ISP) http://i.imgur.com/5F3ggYd.png

But yeah, currently torrentday.it is working fine. 

Can you tell me what config file I need to edit to change it?

**Comment by kaso17** [comment]
Location:
Linux: ~/.config/Jackett/Indexers/torrentday.json
Windows: C:\ProgramData\Jackett\Indexers\torrentday.json

If it's empty/non existent create it with the following content:
```
[
  {
    "id": "alternatelink",
    "type": "inputstring",
    "name": "Alternate Link",
    "value": "https://torrentday.it/"
  },
]
```

**Comment by maZuFC** [comment]
i got the same issue with Jackett ... fails on torrentday

but i can still access the .it domain.

**Comment by MrAmos123** [comment]
v0.7.813 - resolves this issue.
