### ISSUE TITLE
awesomehd: site down

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8403]
https://awesome-hd.me/
Tested in https://www.uptrends.com/tools/uptime

**Comment by ilike2burnthing** [comment]
![awesomehd](https://user-images.githubusercontent.com/59480337/80558070-e7992e00-89d0-11ea-8b1e-e1d9a44fbcdd.png)

**Comment by RoloSoze** [comment]
Back up now.

**Comment by ngosang** [comment]
@RoloSoze I see 404..

**Comment by ilike2burnthing** [comment]
Well that was short lived, was up this morning :/

**Comment by RoloSoze** [comment]
It's up now. It might keep doing that for a while since they're undergoing maintenance. There's probably no point in reopening this ticket every time it goes down.
