### ISSUE TITLE
torrentview: result without title

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8405]
![image](https://user-images.githubusercontent.com/10577978/80543772-ee637900-89af-11ea-9613-f1906a48d55a.png)

**Comment by ngosang** [comment]
@garfield69 I still have the problem after your change.

**Comment by garfield69** [comment]
urg. turns out the media-content div is unreliable, but the media-heading div has the same data plus title, so I'll use that instead. Damn difficult to spot the row with the missing name when its all in a foreign language.
