### ISSUE TITLE
Newpct qualities

### ISSUE THREAD

**Issue by fexxall** [Jackett/Jackett#8407]
**Jackett Version**: 0.16.164.0

### Description
Hi, I have some suggestions about the new code of Newpct indexer. It is about how you have renamed the quality of the movies.

### Screenshots
![photo_2020-04-28_22-12-27](https://user-images.githubusercontent.com/64475162/80580054-3c599a80-8a0b-11ea-88a2-60719f7d8e11.jpg)

There are some categories of movies that have the same name when they are different qualities and sizes. Can be fixed?

For example:
![jackett](https://user-images.githubusercontent.com/64475162/80580414-c7d32b80-8a0b-11ea-901d-6113d5fbd671.PNG)

**Comment by ngosang** [comment]
I did the rename because Sonarr/Radarr can't understand some Newpct qualities like MicroHD.
Could you give me specific examples of bad renaming?

**Comment by fexxall** [comment]
Ok, perfect, I'll try to help.
Check this:
![jackett2](https://user-images.githubusercontent.com/64475162/80601312-efd38680-8a2d-11ea-96e4-127519c0f1df.PNG)
Right now, that group of qualities have the same name and quality.

We can try to add more types. I suggest something like this:

Web Screener -------------> TS Screener
Web Screener 720p -------------> DVDSCR
BluRay Rip -------------> BluRay 480p
BluRay 720p -------------> 
-------------> 
-------------> 
-------------> 
------------->

**Comment by fexxall** [comment]
Ok, perfect, I'll try to help. 
Check this:
![jackett2](https://user-images.githubusercontent.com/64475162/80604624-417e1000-8a32-11ea-9b68-db37876fc57e.PNG)

Right now, that group of qualities have the same name and quality.

We can try to add more types. I suggest something like this:

Web Screener ----------------> TS Screener
Web Screener 720p ----------> DVDSCR
BluRay Rip -------------------> BluRay 480p
BluRay 720p -----------------> BluRay 720p
MicroHD 1080p --------------> BluRay 1080p MicroHD or BluRay 1080i
BluRay 1080p ----------------> BluRay 1080p
BluRay 1080p HEVC X265 ----> BluRay 1080p x265
BDremux 1080p --------------> Remux 1080p
4K UHDrip -------------------> BluRay 2160p
4K UHDremux ----------------> Remux 2160p

**Comment by fexxall** [comment]
About Radarr, it is not able to recognize the qualities.
But only in the titles with "SPANISH DUAL".
![radarr2](https://user-images.githubusercontent.com/64475162/80607302-a25b1780-8a35-11ea-880e-d8e5932d4609.PNG)

Perhaps changing the order of this line? Title - Quality - Language

 return $"{fixedTitle} {fixedLanguage} {fixedQuality}";
        }

**Comment by ngosang** [comment]
I will do requested changes but give me a couple of days.

**Comment by fexxall** [comment]
any update for this?  ;)

**Comment by ngosang** [comment]
It's easy to fix, It will take me few minutes but I don't have time with the lockdown. Just be patient.

**Comment by ngosang** [comment]
@fexxall fixed. It will be included in the next release. Remember to post feedback.

**Comment by garfield69** [comment]
Jackett 0.16.304

**Comment by fexxall** [comment]
I've checked the latest changes, they are pretty good.
As a point, check this out:
![Screenshot_2020-05-08 Onward - Radarr](https://user-images.githubusercontent.com/64475162/81399142-c7811180-912a-11ea-973e-7602f48ca8c8.png)

Screener 720p = Web Screener 720p
Screener 1080p = Web Screener
I think it is the opposite.

**Comment by ngosang** [comment]
Fixed in the next release
![image](https://user-images.githubusercontent.com/10577978/81467968-9fea8180-91dc-11ea-94b3-15b9f83067df.png)

Btw, I don't know what is wrong in your Radarr but the year is not working well. See my screenshot with latest version of Jackett and Radarr

**Comment by garfield69** [comment]
Jackett 0.16.324
