### ISSUE TITLE
[NexusPHP Trackers] Configure IMDb ID search to look in both 'IMDb URL' and 'Description' fields

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8410]
This is identical to the suggestion I made in #7596. 

In NexusPHP trackers, almost all of which are Chinese, there is always a dedicated IMDb URL/External URL field in the torrent upload page. When searching with the IMDb ID, both on the trackers' websites and in Jackett, the query looks up that field. However, it is almost always an optional field, and as such, not all uploaders fill it properly.

Nevertheless, Chinese trackers encourage - and sometimes require - inserting the IMDb URL as part of the torrent's description. In fact a lot of uploaders insert the full IMDb URL in the description, but not in the IMDb URL field where it should ideally go. 

I tested a few IMDb ID searches in multiple trackers via their websites. I tried restricting the search to the 'IMDb URL' field first, and then repeated the same search in the 'Description' field. While I would sometimes get identical results in both searches. there are many instances where searching the 'Description' yields more relevant results than searching the IMDb URL. The opposite can also happen.

To avoid the exclusion of relevant results, I propose that the IMDb ID search in Jackett should look up both the 'IMDb URL' and 'Description' fields in all NexusPHP trackers, return the combined results from both, and eliminate duplicate results, as was done for BIT-HDTV in #7596. 

However, I realize that the BIT-HDTV indexer in written in C# while all the NexusPHP indexers are in YAML, so the first question I will ask is: Is it this even possible? And if the answer is yes, will searching both fields result in increased server load on these trackers? 

I should also note that if we decide to go ahead with including the 'Description' field in IMDb ID searches, that should be an option configurable by the user for each tracker. This is because I noticed that searching the description takes more time than the other 'normal' searches (i.e. Title & IMDb URL). Users must be aware of this fact, and should make a decision accordingly; it should not be forced on them. 

I imagine it would be something like a checkbox in the configuration page of each NexusPHP tracker that says something like, "Include the torrent description field in IMDb ID search queries." with a note saying that doing so will slow down the results retrieval time. Users can test it out, and if they don't like the fact that it takes longer to fetch the results, they can always uncheck the box.

@garfield69 What are your thoughts on this?

**Comment by garfield69** [comment]
>However, I realize that the BIT-HDTV indexer in written in C# while all the NexusPHP indexers are in YAML, so the first question I will ask is: Is it this even possible? 

Yes, its possible for yaml, you just have two paths defined, one with inputs for the description, the other for the imdbid field

>And if the answer is yes, will searching both fields result in increased server load on these trackers?

yes, you have effectively doubled the number of queries made every time a search is performed.

Also, cardigann does not currently drop duplicate results, so if both searches return the same rows, you will see all the duplicates in the results.

>I should also note that if we decide to go ahead with including the 'Description' field in IMDb ID searches, that should be an option configurable by the user for each tracker. 
>something like a checkbox in the configuration page 

however this is not possible currently, as Cardigann does not have the ability to drop a search path based on a conditional.

**Comment by RoloSoze** [comment]
> yes, you have effectively doubled the number of queries made every time a search is performed.
> 
> Also, cardigann does not currently drop duplicate results, so if both searches return the same rows, you will see all the duplicates in the results.

This renders the suggestion irrelevant then. Increased server load + duplicate results is not an improvement over the current situation.
