### ISSUE TITLE
sexy-pics: doesn't return results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8412]
Search: ​Angie ​Lynx

We can use this URL in Jackett => www.sexy-pics.us/search/?m=1&q=​Angie ​Lynx

**Comment by garfield69** [comment]
I don't understand
![image](https://user-images.githubusercontent.com/6933240/80653331-16e19500-8ace-11ea-8039-cfc6eb0c1436.png)

**Comment by garfield69** [comment]
why does typing `Angie Lynx` work
but pasting `Angie Lynx` does not?

**Comment by garfield69** [comment]
actually, pasting from `Angie ​Lynx` works but pasting from Angie ​Lynx does not. %-/

**Comment by ngosang** [comment]
It's working well. I copied the text from another website and I think it has a https://en.wikipedia.org/wiki/Non-breaking_space
