### ISSUE TITLE
some trackers return unrelared results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8413]
It's better if we can use an advanced search instead of AndMatch.

query => bad result title

**animetosho**
"Harry Potter" => "Bleach Season 02 [Dual Audio] [DVD-RIP] [H.264] [HP]"

**extratorrent-cd**
"silicon valley", "Stardew Valley v1.4.5"
"Harry Potter", "The.Thing.About.Harry.2020.720p.HULU.WEBRip.800MB.x264-GalaxyRG"

**mactorrents**
"silicon valley", "Chatty for Facebook 2.0"
"Harry Potter", "Boris FX Continuum Complete OFX 2020 13.0.3"

**tokyotosho**
"Harry Potter", "[Doremi]. Maho. Girls. Precure!. 01. [1280x720][C0D05906]. mkv"

**Comment by garfield69** [comment]
yeah, they have switched all their links to a 3rd party provider https://redirector.desbloqueador.vip
and that site is using an expired certificate.
and this year there has been just one upload, everything else is older that 28-Dec-2019

**Comment by garfield69** [comment]
show me a link on each of these sites where an advanced-search returned desired results.
I cant make any of them work.

**Comment by ngosang** [comment]
I have reviewed the websites and they don't have an advanced search engine or anything that allows us to better adjust the search. Can you apply the and match filter?

**Comment by garfield69** [comment]
animetosho is c#
https://github.com/Jackett/Jackett/blob/ada079dba7e079aa4b8091acd28688bcf3b3babe/src/Jackett.Common/Indexers/Feeds/AnimeTosho.cs

I'll do the other yaml

**Comment by ngosang** [comment]
efectodoppler
search "luis perales"
"Isabel Pantoja - Esencial Isabel Pantoja"

passtheheadphones
"query": "Harry Potter"
Various Artists - Freakin' ADE 2019 [2019] [Compilation] FLAC / Lossless / WEB / 2019

**Comment by garfield69** [comment]
redacted is a c# indexer using the gazelleTracker abstract.
I'll leave this one to you to modify as I don't even have an account on the site to test.
