### ISSUE TITLE
estrenosdtl: remove the site

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8415]
This site is outdated and only the links in the first page are working.

Try to download:
* Fast & Furious: Hobbs & Shaw
* Mujer Maravilla (BR-Scree)
* Harry Potter Y Las Reliquias De La Muerte: Parte 2  (Mejor Calidad)

**Comment by garfield69** [comment]
yeah, they have switched all their links to a 3rd party provider https://redirector.desbloqueador.vip
and that site is using an expired certificate.
and this year there has been just one upload, everything else is older that 28-Dec-2019
