### ISSUE TITLE
Stremio doesn't work with private trackers 

### ISSUE THREAD

**Issue by tomwaits00** [Jackett/Jackett#8416]
### Environment

**OS**: Windows

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.164.0

**Last Working Jackett Version**: 0.16.164.0

**Are you using a proxy or VPN?** [yes/no] No

### Description

[I'm using Jackett with PMP. Added some private tracker (zamunda, filelist, secretcinema) yet I couldn't make it stream any files but Zamunda's. Zamunda works well but other ones doesn't work. It can find torrent files but cannot play. 
Help please.]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]
![image](https://user-images.githubusercontent.com/64563646/80657247-c34e5780-8a8b-11ea-8656-b34d936949d3.png)
![image](https://user-images.githubusercontent.com/64563646/80657832-5d62cf80-8a8d-11ea-9d55-6f4af7221edf.png)
![image](https://user-images.githubusercontent.com/64563646/80657992-a581f200-8a8d-11ea-82db-3b325ba53c75.png)

**Comment by garfield69** [comment]
Jackett provides the torrent/magnet links to any app using the torznab API specifications.
If you can get the zamunda site to pass torrents to your app via the Jackett zamunda indexer, 
but with some other sites you can only get the app to see the torrent listed, but not be able to fetch the torrent, then it is likely the issue is not with Jackett but with something external to Jackett, such as
- your account status on which ever private sites you are using
- bugs in the app you are using

so to diagnose this issue you need to:
- (1)  login via a browser to those private sites and check that your ratio is good, and that there is nothing that could prevent you downloading a file on that site with your browser.
- (2) if step (1) works, the turn on the Jackett enhanced logging to see additional debug messages that may explain why the download link Jackett passed to your app did not work.
- (3) look for and enable logging on your app to see what the app thinks the problem might be

other than that, there is nothing further we can do for you, since we have no open tickets on filelist or secretcinema, so it's unlikely the issue is with the jackett indexers for those sites.

**Comment by tomwaits00** [comment]
First of all, thanks for your reply. I just wonder that is there anyone else like me having this problem? I think no. Thats why I dont get it why I am having this trouble. As far as I know, filelist has a dowload limit per hour. This one maybe the source of problem. Anyway, Im adding log files. I hope they will work.
[debug zamunda.txt](https://github.com/Jackett/Jackett/files/4555614/debug.zamunda.txt)
[filelist debug.txt](https://github.com/Jackett/Jackett/files/4555615/filelist.debug.txt)

**Comment by garfield69** [comment]
I'm sorry but the logs you provided are of no use.
I thought you said that the zamunda indexer was working with your app, so I do not understand why  you provided a log for zamunda.
as for the filelist log, you provided the json returned by the web site, but none of the following debug messages that show a torrent being passed to your app.

**Comment by tomwaits00** [comment]
Sorry, I really don't know what am I supposed to do. This time, I followed this steps;
- scroll down to the bottom of the Jackett Dashboard and tick the enhanced Logging checkbox
- scroll up a bit and click on the apply server settings button
- perform the test with the relevant indexer (avoid using any other indexers to prevent log clutter)

I just did run only Filelist. This is my log file in the ProgramData%\Jackett...
[log.txt](https://github.com/Jackett/Jackett/files/4555689/log.txt)

**Comment by garfield69** [comment]
the latest log is better. but did you try to use your app to stream a file?
the log ends after the results were sent to the app but has nothing more.
so if you tried your app to viw a torrent, then check the log again.
if necessary, perhaps using your jackett tray to stop the background service will close the log and show the rest.

**Comment by tomwaits00** [comment]
Sorry, Im really bad at this tech tools. I streamed a file. Did I properly this time?
[log.txt](https://github.com/Jackett/Jackett/files/4555754/log.txt)

**Comment by garfield69** [comment]
the log shows that in response to your request to download a file the site returned
`Numarul maxim permis de actiuni a fost depasit. Reveniti peste o ora.`

**Comment by garfield69** [comment]
@ngosang  can you take a look at the log provided in the ticket.
apart from the last attempt which failed due to rejection by the filelist site, do the other attempts look like they are successfully sending the torrent to the app?
I don't have an account on the site so I cannot compare the log with what a good torrent request/return sequence looks like.

**Comment by tomwaits00** [comment]
Yes I know this error, I told you before. But now, I can dowload torrent file from the filelist web site, there is no problem. I streamed again, another movie. Adding new log. Maybe help to understand.

[log.txt](https://github.com/Jackett/Jackett/files/4555823/log.txt)

**Comment by garfield69** [comment]
the log shows
```
2020-04-30 05:28:37.8062 Debug WebClient(HttpWebClient2NetCore).GetBytes(Url:https://filelist.io/download.php?id=660551&passkey=*****redacted******) 
2020-04-30 05:28:38.0352 Debug WebClient(HttpWebClient2NetCore): Returning OK => 116699 bytes 
2020-04-30 05:28:38.0515 Info Executing Microsoft.AspNetCore.Mvc.FileContentResult, sending file with download name 'It.Chapter.Two.2019.2160p.UHD.Blu-ray.HEVC.Atmos.TrueHD.7.1-AAAUHD.torrent' ... 
2020-04-30 05:28:38.0619 Debug The file result has not been enabled for processing range requests. To enable it, set the property 'EnableRangeProcessing' on the result to 'true'. 
2020-04-30 05:28:38.0696 Debug Response compression is not enabled for the Content-Type 'application/x-bittorrent'. 
2020-04-30 05:28:38.0696 Info Executed action Jackett.Server.Controllers.DownloadController.Download (JackettConsole) in 494.9574ms 
2020-04-30 05:28:38.0910 Info Executed endpoint 'Jackett.Server.Controllers.DownloadController.Download (JackettConsole)' 
2020-04-30 05:28:38.0910 Info Request finished in 682.3074ms 200 application/x-bittorrent 
2020-04-30 05:28:38.0999 Debug Connection id "0HLVCKQ9QC6QR" received FIN. 
2020-04-30 05:28:38.0999 Debug Connection id "0HLVCKQ9QC6QR" disconnecting. 
```
looks good to me.
what ever the problem is, its wit your app not jackett.
@ngosang  do you concur?

**Comment by tomwaits00** [comment]
So, the problem is my app (stremio) then, right? I can uninstall and install again. Apart from this do you any suggest sir?

**Comment by garfield69** [comment]
>So, the problem is my app (stremio) then, right?

it looks that way, although I am waiting for one of my peers to review to confirm.

See if the app has any kind of option to turn on logging of some kind, and maybe it will report the reason why it did not like the torrent file it was given.
I doubt reinstalling will fix it, unless it is to upgrade to a newer release.
Try to find the support site for the app and see if they have any way to report an issue.

**Comment by tomwaits00** [comment]
It didn't work anyway. Thanks for your support. 
Have a nice day :)

**Comment by tomwaits00** [comment]
Well, it didnt work. But thanks for your support.
Have a nice day 👍

**Comment by ngosang** [comment]
@tomwaits00 This issue is caused by Stremio. Please, open an issue here https://github.com/Stremio/stremio-bugs and link this issue.
