### ISSUE TITLE
IPTorrents Doesn't Work

### ISSUE THREAD

**Issue by houdini3009** [Jackett/Jackett#842]
My username/password for IPTorrents doesn't work in Jackett. I can confirm the credentials are correct and that my account is working properly.

The error shown is: **Configuration failed: Sign Up « » Forgot your password? If your account was disabled or you simply can't log in,Click here to join our live irc #support channel. If you need help please contact us at: ipthelp@protonmail.com**

**Comment by kaso17** [comment]
works fine for me, which version are you running? Please post a log with the -t option enabled.

**Comment by archangel00uk** [comment]
I think some isp have blocked more mirror sites, so mirror sites needs amending again. Trying to locate some for you.

**Comment by maZuFC** [comment]
all ipt domains in the uk have been blocked

admins will need to setup a new domain ....

**Comment by flightlevel** [comment]
This issue hasn't had activity for a while. If the issue still exists, please reopen and include full logs. https://github.com/Jackett/Jackett#troubleshooting
