### ISSUE TITLE
[scenefz] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by zalex88** [Jackett/Jackett#8422]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: ubuntu 20.04 LTS

**.Net Runtime**: Mono

**.Net Version**: 

**Jackett Version**: Jackett Version 0.16.175.0

**Last Working Jackett Version**: i dont know

**Are you using a proxy or VPN?** NO

### Description

1. go to jackett
2. search for scenfz.me
3. login to scenefz
4. go to dev mode -> Network -> HTML -> Cookies
5. copy the cookie
6. provide cookie in jackett
7. error message displayed

### Logged Error Messages

 An error occurred while updating this indexer
Login Failed, got redirected.
Click here to open an issue on GitHub for this indexer.

If logs are necessary please let me know and please provide the path were i can find them in linux.

### Screenshots

![tempsnip](https://user-images.githubusercontent.com/25932246/80694489-7c348680-8acc-11ea-9ec4-3e151689cf89.png)

**Comment by zalex88** [comment]
Hello @jackettbot,

It is not a duplicate, in the previous ticket i forgot to add the information. 

Please reopen the ticket.

Kind regards,
Zalex

**Comment by garfield69** [comment]
@zalex88  the cookiefrom websites is not normally just the cfduid.
have a read of https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work and see if that helps you.
let me know how you go.

**Comment by zalex88** [comment]
@garfield69 - I don't know how to compose it, because in the browser I'm seeing more lines (please see attached)
![Capture](https://user-images.githubusercontent.com/25932246/80751514-986b0e80-8b32-11ea-8264-aa45d33f99a6.PNG)
. If you know how to compose it please let me know.

**Comment by garfield69** [comment]
You are looking at the wrong tab. ;-)
take a closer look at the instructions.
https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work
you want the **headers** tab (not the _cookie_ tab).

**Comment by zalex88** [comment]
@garfield69 - thank you for pointing that out, I have managed to get the info and test the connectivity in Jackett. 
The new issue that I'm facing is that after 30-1h the value that I have inputted disappear and as a result, the connectivity is lost. Do you have any idea regarding this?

**Comment by garfield69** [comment]
Anytime you edit the config panel an empty cookie box is presented.
It is assumed you would only ever need to edit the config because a search failed when using a now expired cookie, and the config needs updating with a new one.
The expiry of a cookie is set by the web site and is out of our control, but usually lasts at least a day, on some sites it can be good for months.
So do not edit the config unless its to replace the cookie.
