### ISSUE TITLE
[bitturk] Login failed: No form found on http://bitturk.net/?p=home

### ISSUE THREAD

**Issue by bingoxo** [Jackett/Jackett#8432]
using Jackett Version 0.16.175.0 , i'll supply logs if needed

**Comment by garfield69** [comment]
they changed domain. next release in about 10 hours will include fix.
or you could edit your jackett dashboard indexer config and change sitelink to `http://bitturk.net/`

**Comment by garfield69** [comment]
Jackett 0.16.227
