### ISSUE TITLE
TSPATE error 

### ISSUE THREAD

**Issue by bidulle95** [Jackett/Jackett#844]
j'ai cette erreur 

Error	
headerString:
Dec 12, 2016 09:18:57 PM	Error	
cookies: 
Dec 12, 2016 09:18:57 PM	Error	
request.RawPOSTDdata: 
Dec 12, 2016 09:18:57 PM	Error	
request.Referer: 
Dec 12, 2016 09:18:57 PM	Error	
request.Cookies: pass=cbaba80406d80011aef0a64c1e6f2b82ab83cdac; uid=23306
Dec 12, 2016 09:18:57 PM	Error	
request.Url: https://www.tspate.me/torrents-search.php?c14=1&c64=1&c21=1&c18=1&c57=1&c19=1&c60=1&c61=1&&search=Walking+Dead+S07E06&incldead=1
Dec 12, 2016 09:18:57 PM	Error	
request.Method: GET
Dec 12, 2016 09:18:57 PM	Error	
got NotImplemented/InternalServerError

**Comment by kaso17** [comment]
Please try running jackett with the "--IgnoreSslErrors true" option

**Comment by bidulle95** [comment]
comment on change  jai un nas qnap et cela tourne en qpkg ?

**Comment by kaso17** [comment]
english please

**Comment by kaso17** [comment]
As i understand tspate is down and won't come back, it has been removed with ecf295873fb8b34f1abb3897a484a27992713b7c
