### ISSUE TITLE
[req] HDStreet  CHINESE Private https://hdstreet.club/

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8450]
**Indexer Name**
HDStreet

**Indexer URL**
https://hdstreet.club/

**Interface Language**
Chinese (No English interface)

**Description**
HDStreet is a CHINESE Private Torrent Tracker for Movies, TV, Music

**Type**
YAML (NexusPHP)

**Access**
Private - Currently has open signups:
https://hdstreet.club/signup.php?type=normal

**Notes**
- Supports IMDb ID Search
- Note the different torrent pages available
- Please ensure the inclusion of dead torrents for all categories

**Comment by garfield69** [comment]
Jackett 0.16.284

**Comment by ilike2burnthing** [comment]
https://hdstreet.club/ - redirects to spam

**Comment by garfield69** [comment]
I get ERR_CONNECTION_TIMED_OUT which amounts to the same thing
