### ISSUE TITLE
[req] PTMSG CHINESE Private https://pt.msg.vg/

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8452]
**Indexer Name**
PTMSG

**Indexer URL**
https://pt.msg.vg/

**Interface Language**
Chinese (No English interface beyond the signup page)

**Description**
PTMSG is a CHINESE Private Torrent Tracker for HD Movies, TV, Music

**Type**
YAML (NexusPHP Standard v1.5 Beta 4)

**Access**
Private - Currently has open signups:
https://pt.msg.vg/signup.php

**Notes**
- Supports IMDb ID Search
- Please ensure the inclusion of dead torrents for all categories
- Download a small file when you join to avoid losing your account

**Comment by garfield69** [comment]
Jackett 0.16.296

**Comment by garfield69** [comment]
https://pt.msg.vg/ DNS_PROBE_FINISHED_NXDOMAIN (DNS Lookup Error)

**Comment by garfield69** [comment]
@RoloSoze  do you have any info on PTMSG, has the site moved to a new domain, is just broken, or has gone?

**Comment by garfield69** [comment]
v0.20.3642
