### ISSUE TITLE
[yts] Exception (yts): Connection refused: Connection refused (Test)

### ISSUE THREAD

**Issue by jokerigno** [Jackett/Jackett#8453]
### Description

yts.mx is no longer available. Maybe it's time to change it to yts.ms.

**Comment by garfield69** [comment]
works for me, so the problem is at your end.
![image](https://user-images.githubusercontent.com/6933240/80781728-98691e00-8bc7-11ea-9ecf-7ed5b0256844.png)

**Comment by ngosang** [comment]
yts.mx is working fine
yts.ms is copycat

**Comment by garfield69** [comment]
while not an exact error match, see https://github.com/Jackett/Jackett/wiki/Troubleshooting#an-existing-connection-was-forcibly-closed-by-the-remote-host for ideas on how to proceed.

**Comment by jokerigno** [comment]
Changing dns solved the issue
