### ISSUE TITLE
Jackett fails to update

### ISSUE THREAD

**Issue by robertocaldas** [Jackett/Jackett#8460]
### Environment

**OS**:
raspbian 
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
Mono
**.Net Version**:
Mono JIT compiler version 6.4.0.198
**Jackett Version**:
 0.8.929.0
**Last Working Jackett Version**:
 0.8.929.0
**Are you using a proxy or VPN?** [yes/no]
no

### Description
1. Press "Check for update" button;
2. Check log, it says "New release found.  Current: v0.8.929 New: v0.16.227";
3. Wait, it will restart server;
4. Notice Jackett version remains the same 0.8;
5. Check log, it says "Deleting JackettUpdate temp files from /tmp/JackettUpdate-v0.16.227-637239711315462230"
6. Press "Check for update" button again;
7. Check log, it still says says "New release found.  Current: v0.8.929 New: v0.16.227".

I have enabled Enhanced logging but every time the server restarts it disables it.
[log.txt](https://github.com/Jackett/Jackett/files/4563931/log.txt)

### Logged Error Messages
Didn't notice any errors.

**Comment by garfield69** [comment]
jackett 0.8 is too old.
your best bet is to upgrade to the latest jackett manually by following
https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above
(most rasp users have success installing the arm32).
this also has the benefit of ditching the dependency on mono, as you will be upgrading to .net core

**Comment by robertocaldas** [comment]
Thank you. I was afraid to just install it on top of the existing installation but it just worked.
