### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Input string was not in a correct format.: Input string was not in a correct format. (Test)

### ISSUE THREAD

**Issue by RaphaelDucay** [Jackett/Jackett#8463]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Win10
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
0.16.185.0
**Last Working Jackett Version**:
0.16.185.0
**Are you using a proxy or VPN?** [yes/no]
no
### Description
Test yggtorrent indexer is failing since  minutes

### Logged Error Messages

Exception (yggtorrent): Input string was not in a correct format.: Input string was not in a correct format. (Test)

### Screenshots

![image](https://user-images.githubusercontent.com/9933141/80803689-5afa9580-8bb3-11ea-8abb-f908b5cefba9.png)

**Comment by garfield69** [comment]
follow #8464 for progress/updates on this issue.
