### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Input string was not in a correct format.: Input string was not in a correct format. (Test)

### ISSUE THREAD

**Issue by ced455** [Jackett/Jackett#8465]
**OS**:
Docker

**Jackett Version**:
 0.16.227.0

**Last Working Jackett Version**:
No Idea 

**Are you using a proxy or VPN?** [yes/no]
no
### Description

Didn't change any setting
site link to : https://yggtorrent.se/
Search and DL URL : www2.yggtorrent.se

### Logged Error Messages

Yggtorrent : 
Exception (yggtorrent): Error parsing JS challenge html: Error parsing JS challenge html

YggCookie :
Exception (yggcookie): Input string was not in a correct format.: Input string was not in a correct format.

**Comment by garfield69** [comment]
follow #8464 for progress/updates on this issue.
