### ISSUE TITLE
nnm-club / noname club: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8476]
![image](https://user-images.githubusercontent.com/10577978/80824103-0fa9ac80-8bde-11ea-9793-973300089c1e.png)

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/85217260-02639f80-b38f-11ea-8099-5d361e092075.png)

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/90427373-bac56f80-e0c2-11ea-809c-914d7da8bcb4.png)

**Comment by ilike2burnthing** [comment]
Another hiccup - https://dev.azure.com/Jackett/Jackett/_build/results?buildId=1023&view=results
