### ISSUE TITLE
uniondht: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8479]
![image](https://user-images.githubusercontent.com/10577978/80825301-60220980-8be0-11ea-8300-63f588d440dc.png)

**Comment by ngosang** [comment]
@RoloSoze why reopening?

**Comment by RoloSoze** [comment]
@ngosang It was a glitch in GitHub where even though this issue was closed, it was being filtered as an open issue for some reason, so I had to reopen and close it to fix the glitch. Don't worry about it.
