### ISSUE TITLE
[nyaa-pantsu.net] down

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8484]
https://nyaa.net/
![nyaa](https://user-images.githubusercontent.com/59480337/80858571-e165b480-8c51-11ea-86bc-7a03d4fc9094.png)

**Comment by ngosang** [comment]
up

**Comment by ilike2burnthing** [comment]
502 again

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://nyaa.net/ - 502 again

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://nyaa.net/ - 502 Bad Gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://nyaa.net/ returning 
```html
502 Bad Gateway
nginx
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://nyaa.net/ - 502 Bad Gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://nyaa.net/ - 502 Bad Gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://nyaa.net/ - 502 Bad Gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://nyaa.net/ - 502 Bad Gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://nyaa.net/ - Error 522 - Connection timed out (Bitmitigate)

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://nyaa.net/ - Error 522 - Connection timed out (Bitmitigate)

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://nyaa.net/ - 502 Bad Gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://nyaa.net/ returning Error 502 Bad gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://nyaa.net/ and https://nyaapantsu.nocensor.space/ returning
This page isn’t working HTTP ERROR 500

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://nyaa.net/ - Error 502 - Bad gateway
(sukebei.* is still up)

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://nyaa.net/ - Error 502 - Bad gateway
> (sukebei.* is still up)

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://nyaa.net/ returning 522 connection timed out

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://nyaa.net/ (and any search) - No results found

**Comment by ilike2burnthing** [comment]
redirects to https://zz.ht/

**Comment by garfield69** [comment]
for ERR_CONNECTION_REFUSED I'm now getting ERR_CONNECTION_REFUSED

**Comment by ilike2burnthing** [comment]
http://nyaa.net/ - `This domain may be for sale.`
