### ISSUE TITLE
[New Tracker REQ] TranceTraffic

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#849]
**Indexer Name**
TranceTraffic

**Type**
Music

**Indexer URL**
http://www.trancetraffic.com/

**Indexer Language**
English

**Invite**
Maybe someone can help out with an invite?

**Comment by kaso17** [comment]
fixed with 82fd53226cf0d886d1b957f83ed62dea148e7943

**Comment by armani316** [comment]
@kaso17 Thank you for adding TranceTraffic! However, it seems that Jackett doesn't return certain results or doesn't like certain keywords. For example, searching for 'Dream Dance', 'Hardwell', or 'Future Trance' doesn't return anything in Jackett, whereas searching for Armin or Tiesto works fine.

**Comment by kaso17** [comment]
fixed with 650b6986f9a447a7af864853af823528cfce4ae1
Occured if the search only returned a single page of results
