### ISSUE TITLE
[yggcookie] Exception (yggcookie): Clearance failed after 30 attempt(s).: Clearance failed after 30 attempt(s). (Test)

### ISSUE THREAD

**Issue by Benfosse** [Jackett/Jackett#8498]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Jackett Version 0.14.476.0

**Last Working Jackett Version**: Jackett Version 0.14.476.0

**Are you using a proxy or VPN?** [yes/no] No

### Description

YGGCookie stop working.

### Logged Error Messages

 Clearance failed after 30 attempt(s).: Clearance failed after 30 attempt(s)

**Comment by garfield69** [comment]
follow #8464 for progress/updates on this issue.
