### ISSUE TITLE
TorrentShack catergories

### ISSUE THREAD

**Issue by poplolnman** [Jackett/Jackett#85]
torrentshack is a general tracker, why are tv categories only included?

**Comment by flightlevel** [comment]
Don't have access to TorrentShack. Fill in the categories and they will be added.

https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#3-prepare-the-category-mapping

**Comment by kaso17** [comment]
fixed with #585

**Comment by armani316** [comment]
@kaso17 Gone for good.
