### ISSUE TITLE
[New Tracker REQ] Torviet.com

### ISSUE THREAD

**Issue by neilicious** [Jackett/Jackett#850]
Indexer Name
Torviet

Type
Movies, TV
(is a sister site to HDB and so tends to have early releases of their internal movie encodes)

Indexer URL
http://www.torviet.com

Indexer Language
English/Vietnamese

Invite
Sent via email

**Comment by kaso17** [comment]
got it, added to TODO

**Comment by kaso17** [comment]
added with 15064810f8768727f7ad1993910d6f0b7699e669

**Comment by garfield69** [comment]
http://torviet.com/ returning ERR_NAME_NOT_RESOLVED
just me, or is site broken, gone or moved to a new domain?

**Comment by garfield69** [comment]
http://torviet.com/ returning ERR_NAME_NOT_RESOLVED
anyone have any news?
