### ISSUE TITLE
[extratorrent-ag] Exception (extratorrent-ag): Input string was not in a correct format.: Input string was not in a correct format. (Test)

### ISSUE THREAD

**Issue by elpardua** [Jackett/Jackett#8500]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Arch Linux - Docker container from linuxservers via compose

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.252.0

**Last Working Jackett Version**: 0.16.252.0

**Are you using a proxy or VPN?** [yes/no] No

### Description

This tracker was working i think. Last massive test run, said no errors. Now it fails all of a sudden.

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by elpardua** [comment]
Environment

OS: Arch Linux - Docker container from linuxservers via compose

.Net Runtime: [.Net-Core/.Net-Framework/Mono]

.Net Version:

Jackett Version: 0.16.252.0

Last Working Jackett Version: 0.16.252.0

Are you using a proxy or VPN? [yes/no] No
Description

This tracker was working i think. Last massive test run, said no errors. Now it fails all of a sudden.

[List steps to reproduce the error and details on what happens and what you expected to happen]
Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]
Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
follow #8464 for progress/updates on this issue.
