### ISSUE TITLE
[downloadville] Error: Mot de passe Incorrect (Config)

### ISSUE THREAD

**Issue by cdtkoenig** [Jackett/Jackett#8505]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
the downloadville indexer is working for me which suggest this is a problem at your end.
the error indicates you have the wrong password.
- login to the site with your browser to confirm your credentials then logout.
(if you recently changed your password, some sites do not save it until you logout).
- then access your jackett dashboard, remove the indexer with the trashbin,
- add the indexer afresh with the wrench
- and re-enter your credentials (even if they appear pre-filled)

if you still have a problem then provide a full enhanced log
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by cdtkoenig** [comment]
Got it
disconnect / reconnect did the job

Thank you very much

Stay Home

Regards
