### ISSUE TITLE
Jackett through Docker on a Mac: Randomized Ports

### ISSUE THREAD

**Issue by pixelrogue1** [Jackett/Jackett#8507]
**OS**: MacOS 10.15.4/ Catalina

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]. Mono: 5.20.1.34 (per sonarr panel)

**.Net Version**: n/a

**Jackett Version**: 0.16.127.0

**Last Working Jackett Version**: 0.16.127.0

**Are you using a proxy or VPN?** [yes/no] Both (off for testing/config)

### Description

**EXPECTED BEHAVIOR**
Ability to use http://jacket:9117 in the related tracker URLs for Sonarr/Radarr.
Sonarr/Radarr stay connected to Jackett.

**CURRENT BEHAVIOR**
Sonarr/Radarr will not accept http://jacket:9117 in the URL.
Sonarr/Radarr WILL accept the IP number of Jackett and work as expected, until Jacket IP port changes. Once changed, one must go into every index and change the port. 

**ATTEMPTS TO FIX**
• Granted Full Disk Access & Folders to bash, sh, smbd,sshd,Terminal, Docker. 
(temporary btw to find a fix)
• Full Read/Write permissions to MacOS target folders (and everything enclosed)
• Redirected downloads to less secured public shared space
• Failed attempts at command line fixes from others w/this problem
• Reboots

**TEMPORARY FIX**
Go into Jackett shell, pull new IP...update all indexers w/new port number.
Not sustainable. 

### Logged Error Messages
Error messages are from Sonarr/Radarr, Indexer Name Error: Connect Failure (not route to host): IP.

**Comment by garfield69** [comment]
this is a docker issue and nothing to do with Jackett.
Docker images are supported by the [LinuxServer.io](https://linuxserver.io/) team who supply a docket image of jackett they build and maintain. [LinuxServer.io Jackett Docker](https://hub.docker.com/r/linuxserver/jackett/)
access the support site and read about setting the port internally on the image and externally for access for browsers and apps.
for support contact them via [Discord](https://discord.gg/YWrKVTn) or their forum [Discourse](https://discourse.linuxserver.io/)

**Comment by pixelrogue1** [comment]
It would be helpful if we could maintain a fixed IP for Jackett. 
Fixed port, I am not referencing the :9117, rather that internal IP port of 172.17.0.X:9117

That .X keeps changing.

**Comment by garfield69** [comment]
I don't see that this has anything to do the the Jackett app. port, ip, whatever, that is a docker configuration problem you need to resolve at the docker support site.

**Comment by pixelrogue1** [comment]
Any way to havertown Jackett to stop changing its ip?

>

**Comment by garfield69** [comment]
jackett is not responsible for changing its IP.
it is all to do with your docker set up.

**Comment by pixelrogue1** [comment]
OK. Thank you.
