### ISSUE TITLE
Xspeeds Not Working Raspi 3

### ISSUE THREAD

**Issue by H4ckey** [Jackett/Jackett#851]
Configuration failed: Missing or incorrect header for method CloudFlareChallengeSolverSolve

Working in windows just not on Raspbain

**Comment by kaso17** [comment]
Is the mono-devel package installed?
Which mono version are you running?

**Comment by kaso17** [comment]
I assume it's fixed

**Comment by H4ckey** [comment]
Yes sorry I installed Ubuntu mate and reran all the instalations and it ended up working :)
