### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Input string was not in a correct format.: Input string was not in a correct format. (Test)

### ISSUE THREAD

**Issue by jfperrin** [Jackett/Jackett#8510]
I'am running jackett (Jackett Version 0.16.252.0) under docker with image binhex/arch-delugevpn:latest

Both inders yggtorrent and yggcookies raise the same exception.

**Comment by garfield69** [comment]
upgrade to v0.16.256 which has an updated cloudflareSolverRe library which will fix your problem.
