### ISSUE TITLE
hdspace: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8512]
"query": "tot"
"query": "disney"
"query": "up"
"query": "notre"
"query": "pie"

**Comment by RoloSoze** [comment]
Might be related to #7664

**Comment by garfield69** [comment]
I dont have an account on this site, and its also a c# indexer.
so either supply some html or fix it yourself ;-)

**Comment by ngosang** [comment]
@garfield69 thank you for your excellent work. Without you Jackett will get outdated in one week and obsolete in one month. :smile: 
I'm reporting all issues I find but that doesn't mean you have to fix all of them. If you can't someone else will do, eventually.

**Comment by garfield69** [comment]
No problem. I am in covid19 lock-down so this work keeps me busy and sane until its over.
