### ISSUE TITLE
torrentland: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8516]
"query": "maisie"
"query": "professional"
"query": "crack"
"query": "sports"
"query": "road"
"query": "robert"
"query": "golo"
"query": "women"
"query": "pdf"
"query": "tot"
"query": "iphone"
"query": "disney"
"query": "game"
"query": "dallas"
"query": "love"
"query": "kate"

**Comment by ngosang** [comment]
@garfield69 
05-04 00:12:46 Error CardigannIndexer (torrentland): invalid Torznab category for id 17: PC/Other

**Comment by garfield69** [comment]
oops.

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/81497105-8b7db600-92bc-11ea-928b-e009bb39632c.png)

![image](https://user-images.githubusercontent.com/10577978/81497109-95071e00-92bc-11ea-9a8d-cf3ee89d7995.png)

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/81750803-7b2d2d00-94ae-11ea-9ae4-1530444e2427.png)

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/93014730-ccac0c80-f5b3-11ea-86c9-00a7fcafec4c.png)
