### ISSUE TITLE
[New Tracker REQ] eztv.ag

### ISSUE THREAD

**Issue by blackley** [Jackett/Jackett#853]
open site

**Comment by armani316** [comment]
@blackley Before you add more open trackers to the list, I think it's worth mentioning that Jackett only works with private trackers at the moment. However, you may want to try Cardigann, which works with public trackers including EZTV.

https://github.com/cardigann

**Comment by kaso17** [comment]
Jackett won't support public trackers but you can use the cardigann EZTV definition with Jackett.
