### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Error parsing JS challenge HTML: Error parsing JS challenge HTML (Test)

### ISSUE THREAD

**Issue by pegasejames** [Jackett/Jackett#8530]
Bonjour,

J ai ce message la depuis quelques jours pour yggtorrent 

Avez vous des informations ?

Merci d avance

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
>J ai ce message la depuis quelques jours pour yggtorrent
>Avez vous des informations ?
>google translation
>I have this message for a few days for yggtorrent
>Do you have any information?

upgrade to v0.16.256 which has an updated cloudflareSolverRe library which may fix your problem.

**Comment by pegasejames** [comment]
thanks

**Comment by Mrmel94** [comment]
Same error with jacket Jackett Version 0.16.284.0.

Jackett.Common.IndexerException: Exception (yggtorrent): Error parsing JS challenge HTML ---> System.Exception: Error parsing JS challenge HTML

It's not happens every test, it's a little bit random.. sometimes the test success and sometimes nope.

But when I'm using sonarr v3 and do research in sonarr it's failed automatically.

**Comment by mishka81** [comment]
same problem, with 0.16.296.0 / Windows 10.
