### ISSUE TITLE
Searching in All trackers through Manual search cuts last keyword for many trackers

### ISSUE THREAD

**Issue by janot** [Jackett/Jackett#8531]
e.g. "harry potter azkaban" will search only for "harry potter" at bakabt, beyond-hd, bibliotik. bigfangroup, bitru ... passthepopcorn, redacted, kinozal ... lots of them

**Comment by garfield69** [comment]
yeah, nah.
need some proof of what you are reporting so we can see what you mean and have something to work with.

I suggest the following:
- shutdown the jackett service
- backup your indexers folder to a safe place
- delete all but a couple indexers configs to keep things manageable
- startup jackett
- enabled enhanced logging
- do your search
- screencapture the search results page
- save the log
- now search each indexer separately
- screencapture those results
- save those logs
- show us how they differ 
- if the indexers you have chosen work as expected, then pick another bunch until you have proof of what you have reported.
- post all screencaptures and logs for us to examine.

**Comment by janot** [comment]
Here are logs and screenshots with 3 indexers enabled: badasstorrents (not affected by this issue), bakabt, beyond-hd
Not all combinations of enabled indexers produce this. E.g. when if I chose 2 other trackers and bakabt, it worked as expected.

All trackers search:
![Capture](https://user-images.githubusercontent.com/1689966/81050937-8f2ec880-8ec9-11ea-9086-eceb28fe7277.PNG)
[all.log](https://github.com/Jackett/Jackett/files/4580117/all.log)

bakabt:
![Capture](https://user-images.githubusercontent.com/1689966/81056612-7b885f80-8ed3-11ea-9fa2-3edc4c62db34.PNG)
[bakabt.log](https://github.com/Jackett/Jackett/files/4580851/bakabt.log)

beyond-hd:
![Capture](https://user-images.githubusercontent.com/1689966/81068488-1e97a400-8ee9-11ea-8f67-59a97542424a.PNG)
[beyond-hd.log](https://github.com/Jackett/Jackett/files/4580879/beyond-hd.log)

**Comment by garfield69** [comment]
@cadatoiva  @ngosang  
the following code in bakabt is impacting on all subsequent indexers when the **ALL** aggregate search is performed
https://github.com/Jackett/Jackett/blob/162ad104ef0b8ac92bf004664c24de292d0e44e7/src/Jackett.Common/Indexers/BakaBT.cs#L82-L90
in the test provided by @janot  where the indexers available are badasstorrents, bakabt, beyond-hd,  in that order, this code results in the following query urls being generated
```
2020-05-05 12:28:13.3117 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://badasstorrents.com/torrents/search/harry%20potter%20azkaban)
2020-05-05 12:28:13.4858 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://bakabt.me/browse.php?only=0&hentai=1&incomplete=1&lossless=1&hd=1&multiaudio=1&bonus=1&reorder=1&q=harry+potter)
2020-05-05 12:28:13.5564 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://beyond-hd.me/torrents?search=harry+potter&description=&uploader=&imdb=&tmdb=&sorting=created_at&direction=desc&qty=100)
```
as you can see, bakabt is editing not just its own query.SearchTerm, but the global query.SearchTerm 

this also goes a long way to explaining why some indexers do a **copy** of the query.SearchTerm, and any c# indexers that modify the query.SearchTerm need amending to avoid overwriting the global query.SearchTerm.

**Comment by garfield69** [comment]
Jackett 0.16.485

**Comment by garfield69** [comment]
v0.20.959
