### ISSUE TITLE
[mejortorrent] Clearance failed after 30 attempt(s). (Config)

### ISSUE THREAD

**Issue by karakatunga** [Jackett/Jackett#8554]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: debian 10 (console)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] last

**.Net Version**: 

**Jackett Version**: last

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?** [yes/no] no

### Description

An error occurred while configuring this indexer
Clearance failed after 30 attempt(s).

### Logged Error Messages

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
upgrade to v0.16.310 which has an updated cloudflareSolverRe library which may fix your problem.

**Comment by karakatunga** [comment]
I have updated yo this version but still the problem

**Comment by garfield69** [comment]
the mejortorrent indexer works for me which suggests that the issue is at your end.
 please provide  an **enhanced** log which will have debug and html that may provide clues to what is going on.
see https://github.com/Jackett/Jackett/wiki/TroubleShooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
also fill in as many of the questions in the first post of this ticket, it is info that is useful to us.

**Comment by karakatunga** [comment]
> the mejortorrent indexer works for me which suggests that the issue is at your end.
> please provide an **enhanced** log which will have debug and html that may provide clues to what is going on.
> see https://github.com/Jackett/Jackett/wiki/TroubleShooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

[log.txt](https://github.com/Jackett/Jackett/files/4595853/log.txt)

Here you go! Thanks!

**Comment by karakatunga** [comment]
> also fill in as many of the questions in the first post of this ticket, it is info that is useful to us.

Updated!

**Comment by garfield69** [comment]
Darn. Other than confirming that jackett was blocked by the cloudflare anti-DDoS challenge there is little else to help.
this suggests that for your IP address, cloudflare is not presenting the regular i'm-in-protection-mode challenge (which looks like this)
![image](https://user-images.githubusercontent.com/6933240/81347320-00f85380-9110-11ea-9b1e-399e2ae4ab65.png)
but that you might be seeing the i'm-under-attack-mode challenge (which might look a bit like this)
![image](https://user-images.githubusercontent.com/6933240/81347432-3b61f080-9110-11ea-9a73-4f3d4b2a95ef.png)
and which the cloudflareSolverRe library has never been able to automatically solve.

to confirm this theory, use a browser running on the same machine that is running Jackett, and click on the link below and see what sort of cloudflare challenge you get.
https://www.mejortorrentt.net/secciones.php?sec=ultimos_torrents

if it is the latter challenge, then one possibility is to change your IP address. The simplest way to do this is to use a VPN.
Let me know what you discover.

**Comment by karakatunga** [comment]
> Darn. Other than confirming that jackett was blocked by the cloudflare anti-DDoS challenge there is little else to help.
> this suggests that for your IP address, cloudflare is not presenting the regular i'm-in-protection-mode challenge (which looks like this)
> ![image](https://user-images.githubusercontent.com/6933240/81347320-00f85380-9110-11ea-9b1e-399e2ae4ab65.png)
> but that you might be seeing the i'm-under-attack-mode challenge (which might look a bit like this)
> ![image](https://user-images.githubusercontent.com/6933240/81347432-3b61f080-9110-11ea-9a73-4f3d4b2a95ef.png)
> and which the cloudflareSolverRe library has never been able to automatically solve.
> 
> to confirm this theory, use a browser running on the same machine that is running Jackett, and click on the link below and see what sort of cloudflare challenge you get.
> https://www.mejortorrentt.net/secciones.php?sec=ultimos_torrents
> 
> if it is the latter challenge, then one possibility is to change your IP address. The simplest way to do this is to use a VPN.
> Let me know what you discover.

Thanks for your answer but i have changed my IP and It didn't work... I dont know waht ti do...

**Comment by garfield69** [comment]
so did you get a challenge using your browser, and which one was it?

**Comment by karakatunga** [comment]
> so did you get a challenge using your browser, and which one was it?

Im in debian console only i cant or I dont know how to do it

**Comment by garfield69** [comment]
I don't know either, I'm not a linux man. @cadatoiva  @ngosang  what was that trick with the terminal and tunnelling and stuff that let a user do browser style queries?

**Comment by karakatunga** [comment]
> I don't know either, I'm not a linux man. @cadatoiva @ngosang what was that trick with the terminal and tunnelling and stuff that let a user do browser style queries?

I have made an ssh tunnel and I have been able to verify that Cloudflare denies me access (Error 1020) What can I do? Changing my ip doesn't work... Please help!

**Comment by garfield69** [comment]
If you are getting 1020 that means that the site has blacklisted your access.
I don't know that there is anything we can do for you. @cadatoiva  @ngosang  any suggestions?

**Comment by karakatunga** [comment]
> If you are getting 1020 that means that the site has blacklisted your access.
> I don't know that there is anything we can do for you. @cadatoiva @ngosang any suggestions?

I know, and i cant ontact with the web admin for ask unban because he hasn't any contact form or email

**Comment by ngosang** [comment]
The site is working fine for me. This issue is not general, just for users with blocked IP.
@karakatunga you have to get another IP. If the server is at home you can turn off the router (all network equipment) for a few hours. Maybe you have lucky. If its in some datacenter you can call them but you will have to answer a lot of questions... the alternative is to buy a proxy/vpn.

**Comment by karakatunga** [comment]
> The site is working fine for me. This issue is not general, just for users with blocked IP.
> @karakatunga you have to get another IP. If the server is at home you can turn off the router (all network equipment) for a few hours. Maybe you have lucky. If its in some datacenter you can call them but you will have to answer a lot of questions... the alternative is to buy a proxy/vpn.

Thanks for reply, my machine is a Google Cloud virtual machine with a estatic IP reserved for me. I have changed this IP but It didn't solve the problem... There are something more that can identify me? Cache, cookies? I dont know waht yo do, i have searched for method yo bypass Cloudflare but its impossible....

**Comment by ngosang** [comment]
Try to remove mejortorrent from Jackett, restart the service and add it again. That should remove the cookies.

**Comment by karakatunga** [comment]
> Try to remove mejortorrent from Jackett, restart the service and add it again. That should remove the cookies.

Mejortorrentt it's not added yo my indexers lista, i have rebooted several times
