### ISSUE TITLE
[REQ]pornforall.net

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#8557]
Russian public big adult torrent site: http://pornforall.net
Search engine page: http://pornforall.net/browse.php
Search engine is running.

**Comment by garfield69** [comment]
Jackett 0.16.485

**Comment by ilike2burnthing** [comment]
https://pornforall.net/ - Error 521 - Web server is down

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://pornforall.net/ returning Error 522 Connection timed out
https://www.uptrends.com/tools/uptime reports Http Timeout across all 42 checkpoints worldwide

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://pornforall.net/ - Error 523 - Origin is unreachable

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://pornforall.net/ reporting Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://pornforall.net/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://pornforall.net/ - Error 521 - Web server is down

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://pornforall.net/ returns cloudflare Gateway time-out Error code 504

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://pornforall.net/ - Gateway time-out - Error code 504

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://pornforall.net/ 404

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://pornforall.net/ 404

**Comment by garfield69** [comment]
v0.20.3593
