### ISSUE TITLE
Can't add IPTorrents

### ISSUE THREAD

**Issue by danmed** [Jackett/Jackett#856]
When i click the + symbol it just takes me back to the main page..

I get the below error in the logs : 
Exception in GetConfigForm

I can click other sites fine though..
I'm on the latest full release

**Comment by maZuFC** [comment]
are you in the UK?

all ipt domains have been blocked

**Comment by danmed** [comment]
Yes, sorry i did mean to reply.. I've got this sorted now by running it on
my seedbox.. it seems that if it can't grab the capture it just fails..
