### ISSUE TITLE
epizod: download links not working

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8576]
Empty search
Try to download `Salem Saison 1 FRENCH HDTV`

**Comment by garfield69** [comment]
it seems that the site has switched direct magnet URI in the details page to indirect magnets URL, for example:
a[href="/telecharger/CB8C29F650142F396FFAE91F7DFAE4BB5F31B78B"]
and they are all failing on the web site with 404 Not Found

so the site is currently broken.
We will give them the usual 30 days to fix after which we will drop the site.

**Comment by garfield69** [comment]
so most of the magnets work
but some are still indirect, like the series you found in your first post.
unfortunately the current Cardigann does not have any way to selectively choose to 
- fetch the magnet URI when its there, 
- or build its own URI when the href starts with /telecharger/ 

so we either drop the whole site 
or let it be and accept the failures
or add conditional block processing for the download section.

**Comment by ngosang** [comment]
#8590 will help to fix this kind of issues too. My idea is if infohash field is present but magnet is not, I can generate the magnet with some public trackers. That will do the trick for this one.

**Comment by ngosang** [comment]
@garfield69 I think this can be fixed

**Comment by ngosang** [comment]
Downloads are working fine in this site.
