### ISSUE TITLE
Uninstall script for MacOS

### ISSUE THREAD

**Issue by skywqr** [Jackett/Jackett#8577]
Hi, Is there an uninstall script for MacOS? I couldn't find it anywhere on google either.

**Comment by garfield69** [comment]
nope. if you want to upgrade just let it run over the top.
if you want to quit using it, then
- launchctl unload ~/Library/LaunchAgents/org.user.Jackett.plist
- delete ~/Library/LaunchAgents/org.user.Jackett.plist
- delete ~/.config/Jackett/
- delete where ever you put the jackett binaries, typically /Applications/Jackett
