### ISSUE TITLE
[req] [divteam] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by qg0** [Jackett/Jackett#8579]
Jackett Version 0.16.324.0

![image](https://user-images.githubusercontent.com/919099/81493991-38f9c500-92cf-11ea-9b01-89e2a3890f65.png)

I think some help is needed for the cookie field (with a tracker divteam and others). At least a placeholder like "**pass=112233449038d8d6b1be27f655667788;uid=12345;xbtitAC=1;xbtitFM=1122aabbccddlut6iksi2q4488;**"

Because it's not clear what you should write there: only the value of the "pass" or the "xbtitFM", should it contain white spaces or not, should it be the colon ":" or equal sign "=" with a white space, should it be in quotes or not.

Maybe some auto replacement is needed to delete white spaces and quotes and replace the ":" with "="?

Also some help is needed where you could get this cookies, like press the "F12 and choose Storage->Cookies" and then combine it into a single string".

![image](https://user-images.githubusercontent.com/919099/81493912-b244e800-92ce-11ea-8d74-59123bd26bd7.png)

**Comment by garfield69** [comment]
believe it or not, the info on how to grab the cookie is in the indexer code, but due to a mistake in the labelling, it does not show up.
I will correct this mistake.
