### ISSUE TITLE
[Tracker Request] PassTheHeadphones

### ISSUE THREAD

**Issue by animeai** [Jackett/Jackett#858]
Site is gazelle and uses the same API as WCD did. I presume it is the same API as Xanax currently uses.

I should be able to supply an invite in a week or so if required but need an email address to send it to - I couldn't find this information anywhere.

**Comment by armani316** [comment]
Jacket now supports PassTheHeadphones - just make sure you're on the latest version (v0.7.813) and add it as an indexer.

**Comment by kaso17** [comment]
added with c2f4cc97ab50ec5c868364b558e8ff57ea3bdcfc
