### ISSUE TITLE
torrentgalaxyorg: empty title

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8585]
![image](https://user-images.githubusercontent.com/10577978/81497072-61c48f00-92bc-11ea-9827-1f7ce8e82f3c.png)

**Comment by ilike2burnthing** [comment]
Looks like anything after quotation marks isn't being being picked up.

The first result starts with `"` , followed by more text, and the second one has `"` after `+++ FERA-​111`, followed by more text.

**Comment by garfield69** [comment]
```html
            <div class='tgxtablecell clickable-row click' id='click' data-href='/torrent/13913767/-quot-Stop-It--What-Are-You-Thinking---I-m-Your-Stepmother---quot--She-Was-Overwhelmed-By-His-Furious-Kisses-And-Hard-Piston-Thrusts-And-Finally-She-W' id='rounded' style='word-break:break-all;'>
                <div>
                    <a title="" Stop It! What Are You Thinking!? I 'm Your Stepmother!!" She Was Overwhelmed By His Furious Kisses And Hard Piston Thrusts And Finally She Was Creampie Fucked By Her Stepson Aika Satozaki [FERA-115] (Daichi Minami, Center Village) [cen]" href="/torrent/13913767/-quot-Stop-It--What-Are-You-Thinking---I-m-Your-Stepmother---quot--She-Was-Overwhelmed-By-His-Furious-Kisses-And-Hard-Piston-Thrusts-And-Finally-She-W"><b>&quot;Stop It! What Are You Thinking!? I' m Your Stepmother!!&quot; She Was Overwhelmed By His Furiou...</b></a>
                </div>
            </div>
```
issue with the web site means double quotes in titles breaks html
we could process the href, dropping`-quot-` and replacing `-` with space, but the title will be missing any non-alphabetic characters `!?' as well as being restricted to a max length of 156 chars

worth it?

**Comment by ilike2burnthing** [comment]
I take it there's no way to process that whole div section, drop `<a title=` and stop at the href?

Can https://github.com/Jackett/Jackett/commit/d26e7af2960012e043155c05c8a3ba143ee78eb3 be used here? Would at least give users something to click on. Or rather than only switching on an empty result, can a minimum number of characters be set?

**Comment by garfield69** [comment]
i'd rather just delete the whole indexer. ;-b
i'll spend some time sorting out this useless site's html when I'm in a better mood to look at it, tomorrow.

**Comment by ilike2burnthing** [comment]
Feels ya 😋
