### ISSUE TITLE
torrentscsv: empty search is not working

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8587]
torrentscsv: empty search is not working
@RoloSoze could you talk with the admin to add this feature? he already has the publish date...

**Comment by RoloSoze** [comment]
The admin of which tracker?

**Comment by ngosang** [comment]
https://torrents-csv.ml/

**Comment by RoloSoze** [comment]
I'm not a member.

**Comment by ngosang** [comment]
No one is, it's public.
I have already contacted the owner.

**Comment by RoloSoze** [comment]
Ha! Never tried getting in touch with public tracker staff. Not sure that would even work. Good luck!

**Comment by garfield69** [comment]
temp fix Jackett 0.16.427

**Comment by ngosang** [comment]
no answer from owner

**Comment by dessalines** [comment]
I'm here, I don't get good notifications over at gitlab, sorry.

**Comment by ngosang** [comment]
Gitlab: https://gitlab.com/dessalines/torrents.csv/-/issues/85

In Jackett we provide RSS feeds to torrent clients. If the user don't set a search term, we have to return the newest torrents. Currently we are searching 2020 because the empty search is not working.
We don't want to abuse the site so we will follow your desires. Could you add a hidden endpoint for Jackett or something so we can get the newest torrents?

**Comment by dessalines** [comment]
Okay this is deployed now. You can use http://torrents-csv.ml/service/new?size=[NUMBER_OF_RESULTS]&offset=[PAGE]&type=[torrent | file]

or just https://torrents-csv.ml/service/new

Be aware that if this pummels the server again and locks everything up, I will disable it.

**Comment by ngosang** [comment]
@dessalines thank you!

**Comment by dessalines** [comment]
No probs :)

**Comment by garfield69** [comment]
Jackett 0.16.640
