### ISSUE TITLE
AlphaReign not returning results from a couch potato search - but works on manual search

### ISSUE THREAD

**Issue by zeflash** [Jackett/Jackett#859]
Using the very latest versions of Jackett & the definition files.

When querying 
`http://10.0.0.222:9117/potato/alphareign?imdbid=tt4624424&search=Storks&user=&passkey=<redacted>`
It returns no results. When doing a manual search I get plenty.

It might be related - I tried Cardigann also (seems you use the exact same definition files) and the reason is the HTML tags don't seem to have the same attributes depending on who does the query (see https://github.com/cardigann/cardigann/issues/275)

But here in Jackett, given I see parsing succeeds with a manual search, I'm kinda at lost. And I can't debug that myself given it's mono & I'm on a mac & it's just too much of a hassle to figure out the dev environment I'd have to set up :)

**Comment by kaso17** [comment]
it seems like the category mapping is broken. The potato API filters the results by category "movies". If you run a manual search for Storks you'll see they all map to Other.

**Comment by kaso17** [comment]
Fixed with 7db50dba4935ff44d4571423797adac4af1a47d5
