### ISSUE TITLE
core: review alternative links in all trackers

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8591]
This is just a list of domains. It has to be reviewed manually because it can be wrong (it's wrong).
Some errors 503 are caused by Couldflare (Jackett can solve it but my script can't), others can be caused by my server DNS, other domains can be down temporary....

I think the best way to test is in Jackett if it's possible.

**Tracker || link || error**

- [x] 1337x  ||  https://1337x.gd/  ||  Bad HTTP response code: 503
- [x] 1337x  ||  https://1337x.is/  ||  Bad HTTP response code: 503
- [x] 1337x  ||  https://1337x.st/  ||  Bad HTTP response code: 503
- [x] 1337x  ||  https://x1337x.ws/  ||  Bad HTTP response code: 503
- [x] 1337x  ||  https://x1337x.eu/  ||  Bad HTTP response code: 503
- [x] 1337x  ||  https://x1337x.se/  ||  Bad HTTP response code: 503
- [x] 1337x  ||  https://1337x.unblockit.me/  ||  Bad HTTP response code: 503
- [x] 7torrents  ||  https://www.7torrents.cc/  ||  Bad HTTP response code: 500
- [x] anidex  ||  https://anidex.info/  ||  Bad HTTP response code: 403
- [x] baibako  ||  http://baibako.tv/  || connect timeout 60s
- [x] brobits  ||  https://brobits.cc/  ||  Bad HTTP response code: 302
- [x] btdb  ||  https://btdb.unblockit.me/  ||  Bad HTTP response code: 503
- [x] bteye  ||  https://www.bteye.org/  ||  Bad HTTP response code: 503
- [x] btschool  ||  https://pt.btschool.club/  ||  Bad HTTP response code: 503
- [x] cpasbienclone  ||  https://cpasbien.to/  ||  Bad HTTP response code: 301
- [x] crnaberza  ||  http://www.crnaberza.com/  ||  Bad HTTP response code: 301
- [x] ettv  ||  https://ettv.unblockit.me/  ||  Bad HTTP response code: 503
- [x] extratorrent-ag  ||  https://extratorrent.unblockit.me/  ||  Bad HTTP response code: 503
- [x] eztv  ||  https://eztv.unblockit.me/  ||  Bad HTTP response code: 503
- [x] firebit  ||  https://firebit.name/  ||  Bad HTTP response code: 502
- [x] firebit  ||  https://firebit.biz/  || connection refused
- [x] funkytorrents  ||  http://funkytorrents.com/  ||  Bad HTTP response code: 301
- [x] glodls  ||  https://gtdb.to/  ||  Bad HTTP response code: 301
- [x] glodls  ||  https://glotorrents.unblockit.me/  ||  Bad HTTP response code: 503
- [x] hdonly  ||  https://hd-only.org/  ||  Bad HTTP response code: 500
- [x] hdarea  ||  https://www.hdarea.co/  ||  Bad HTTP response code: 403
- [x] hdchina  ||  https://hdchina.org/  ||  Bad HTTP response code: 302
- [x] hddolby  ||  https://www.hddolby.com/  ||  Bad HTTP response code: 503
- [x] hdhome  ||  https://hdhome.org/  ||  Bad HTTP response code: 302
- [x] hdreactor  ||  https://hdreactor.guru/  ||  Bad HTTP response code: 302
- [x] hdstreet  ||  https://hdstreet.club/  ||  Failed to parse headers 'Location : login.php\r\nContent-Encoding: gzip\r\n\r\n'
- [x] hdtorrentsit  ||  https://hdtorrents.xyz/  ||  Bad HTTP response code: 404
- [x] hdu  ||  https://pt.upxin.net/  ||  Bad HTTP response code: 302
- [x] hdzone  ||  https://hdzone.me/  ||  Bad HTTP response code: 302
- [x] iptorrents  ||  https://ipt-update.com/  ||  Bad HTTP response code: 301
- [x] iptorrents  ||  http://ipt.read-books.org/  || connect timeout 60s
- [x] iptorrents  ||  http://alien.eating-organic.net/  || connect timeout 60s
- [x] iptorrents  ||  http://kong.net-freaks.com/  || connect timeout 60s
- [x] iptorrents  ||  http://ghost.cable-modem.org/  || connect timeout 60s
- [x] iptorrents  ||  http://logan.unusualperson.com/  || connect timeout 60s
- [x] iptorrents  ||  http://baywatch.workisboring.com/  || connect timeout 60s
- [x] kickasstorrent  ||  https://kat.unblockit.me/  ||  Bad HTTP response code: 503
- [x] kickasstorrent-kathow  ||  https://kickass.unblockit.me/  ||  Bad HTTP response code: 503
- [x] kinorun  ||  http://kinorun.top/  ||  Bad HTTP response code: 403
- [x] libranet  ||  https://libranet.org/  ||  Bad HTTP response code: 502
- [x] limetorrents  ||  https://www.limetor.pro/  ||  Bad HTTP response code: 503
- [x] limetorrents  ||  https://www.limetorrents.info/  ||  Bad HTTP response code: 502
- [x] limetorrents  ||  https://www.limetorrents.asia/  ||  Bad HTTP response code: 503
- [x] limetorrents  ||  https://www.limetorrents.co/  ||  Bad HTTP response code: 503
- [x] limetorrents  ||  https://www.limetor.pro/  ||  Bad HTTP response code: 503
- [x] limetorrents  ||  https://limetorrents.unblockit.me/  ||  Bad HTTP response code: 503
- [x] magnetdl  ||  https://www.magnetdl.com/  ||  Bad HTTP response code: 502
- [x] magnetdl  ||  https://magnetdl.unblockit.me/  ||  Bad HTTP response code: 503
- [x] moecat  ||  https://moecat.best/  ||  Bad HTTP response code: 503
- [x] monova  ||  https://monova.unblockit.me/  ||  Bad HTTP response code: 503
- [x] nordichd  ||  http://www.nordichd.eu/  || connect timeout 60s
- [x] oshenpt  ||  https://www.oshen.win/  ||  Bad HTTP response code: 302
- [x] ourbits  ||  https://ourbits.club/  ||  Bad HTTP response code: 503
- [x] pt99  ||  https://pt.j99.info/  ||  Bad HTTP response code: 302
- [x] rodvd  ||  https://rodvd.net/  || connect timeout 60s
- [x] spacetorrent  ||  https://www.spacetorrent.cloud/  ||  Bad HTTP response code: 503
- [x] tenyardtracker  ||  https://tenyardtracker.com/  ||  Bad HTTP response code: 301
- [x] thepiratebay  ||  https://thepiratebay10.org/  ||  Bad HTTP response code: 502
- [x] tntvillage  ||  http://tntvillage.scambioetico.org/  || connection refused
- [x] torlock  ||  https://torlock.unblockit.me/  ||  Bad HTTP response code: 503
- [x] torrentdownloads  ||  https://www.torrentdownloads.me/  ||  Bad HTTP response code: 502
- [x] torrentdownloads  ||  https://torrentdownloads.unblockit.me/  ||  Bad HTTP response code: 503
- [x] torrent9  ||  https://ww1.torrent9.is/  ||  Bad HTTP response code: 302
- [x] torrent9  ||  https://ww1.torrent9.to/  ||  Bad HTTP response code: 301
- [x] torrentccf  ||  https://et8.org/  ||  Bad HTTP response code: 302
- [x] torrentday  ||  https://tdonline.org/  ||  Bad HTTP response code: 301
- [x] torrentday  ||  https://torrentday.eu/  ||  Bad HTTP response code: 301
- [x] torrentday  ||  https://td-update.com/  ||  Bad HTTP response code: 301
- [x] torrentday  ||  https://www.torrentday.me/  || connection refused
- [x] torrentday  ||  https://www.torrentday.ru/  ||  Name or service not known
- [x] torrentday  ||  https://www.td.af/  ||  Name or service not known
- [x] torrentdownload  ||  https://torrentdownload.unblockit.me/  ||  Bad HTTP response code: 503
- [x] torrentfunk  ||  https://torrentfunk.unblockit.me/  ||  Bad HTTP response code: 503
- [x] torrentgalaxyorg  ||  https://torrentgalaxy.unblockit.me/  ||  Bad HTTP response code: 503
- [x] torrentz2  ||  https://torrentz2.eu/  ||  Bad HTTP response code: 503
- [x] torrentz2  ||  https://torrentz.unblockit.me/  ||  Bad HTTP response code: 503
- [x] xiteme  ||  https://x-ite.me/  ||  Read timed out. (read timeout=60)
- [x] zelkaorg  ||  http://zelka.org/  || connect timeout 60s
- [x] zelkaorg  ||  http://zamunda.se/  || connect timeout 60s
- [x] zooqle  ||  https://zooqle.unblockit.me/  ||  Bad HTTP response code: 503

**Comment by ilike2burnthing** [comment]
Can only test public indexers in Jackett (0.16.347 in Windows Sandbox with external VPN), but will comment if issue is found in browser for any (any not commented on allowed access to home or login page).

black-mirror.xyz has split into https://unblocked.bar/ , https://proxyportal.pw/ and  https://uk-unblock.pro/ since I last checked a few days ago, affects all indexers using its proxies. Will test those and post a PR later.

https://brobits.cc/ - `Site shutdown maintenance, please visit later... Thank you`

https://www.bteye.org/ - currently down, but had been working fine before that

http://crazys-corner.info/ - down and likely will be removed in a few days

https://firebit.name/ - `502 Bad Gateway`
https://firebit.biz/ - `ERR_NAME_NOT_RESOLVED`

https://www.hdarea.co/ - hcaptcha challenge

https://ipt-update.com/ - `ERR_CONNECTION_CLOSED`
http://ipt.read-books.org/ - `ERR_CONNECTION_TIMED_OUT`
http://alien.eating-organic.net/ - `ERR_CONNECTION_TIMED_OUT`
http://kong.net-freaks.com/- `ERR_CONNECTION_TIMED_OUT`
http://ghost.cable-modem.org/ - `ERR_CONNECTION_TIMED_OUT`
http://logan.unusualperson.com/ - `ERR_CONNECTION_TIMED_OUT`
http://baywatch.workisboring.com/ -  `ERR_CONNECTION_TIMED_OUT`

...will keep updating this post...

**Comment by garfield69** [comment]
Jackett 0.16.463
