### ISSUE TITLE
[Bug] Testing HD-Torrents (HDT) keeps loading without passing or failing

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#861]
I'm not sure if others are facing the same problem with HDT, but for the past couple of days, testing the tracker doesn't result in anything - it keeps showing the 'in progress' animation but doesn't pass or fail the test. On a couple of occupations it failed the test, saying that a task was canceled, so I'm assuming it timed out.  However, manually searching HDT still works fine.

UPDATE: I tried deleting the indexer and initially I couldn't add it back. The configuration dialog kept loading in the same way as testing. I restarted Jackett and HDT showed up again on my list of configured indexers, despite not being able to successfully add it back. Searching still works fine, but testing does not.

**Comment by kaso17** [comment]
works perfectly for me.
Try searching without a keyword. That's results in the same query as during the test. Does it work too?
Does http://hdts.ru/torrents.php?active=0&options=0 work in your browser?

**Comment by armani316** [comment]
Clicking on the link you provided, and doing an empty search (directly on HDT's website) seem to be working on and off. It times time out on every other try or so. It seems to work a little more consistently with the hd-torrents.org domain. 

Anyone else getting this problem?

**Comment by armani316** [comment]
Like IPT, HDT also has multiple URLs. It might be a good idea to give HDT the same treatment as IPT - allow the user to enter an alternative URL if the default one isn't working. Here are the 4 URLs of HDT:

https://hdts.ru/
https://hd-torrents.org/
https://hd-torrents.net/
https://hd-torrents.me/

**Comment by kaso17** [comment]
added with 5c855d3b50db205dc1a8a3da664c386c31b0ce54
