### ISSUE TITLE
Error while parsing Cardigann definition - Exception during deserialization

### ISSUE THREAD

**Issue by pax0707** [Jackett/Jackett#8624]
### Environment

**OS**:
Raspbian GNU/Linux 10 \n \l
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
Mono JIT compiler version 6.8.0.105 (tarball Tue Feb  4 21:51:48 UTC 2020)
**Jackett Version**:
Jackett Version 0.16.427.0
**Last Working Jackett Version**:
No idea.
**Are you using a proxy or VPN?** [yes/no]
No
### Description
I've noticed that recently some of the indexers are not working.
When I check the logs I see this error.

### Logged Error Messages
```

May 13, 2020 01:45:28 PM | Error | Error while parsing Cardigann definition /opt/jackett/Definitions/hddolby.yml: (Line: 2, Col: 3, Idx: 6) - (Line: 2, Col: 3, Idx: 6): Exception during deserialization
-- | -- | --
May 13, 2020 01:45:28 PM | Error | Error while parsing Cardigann definition /opt/jackett/Definitions/bitru.yml: (Line: 2, Col: 3, Idx: 6) - (Line: 2, Col: 3, Idx: 6): Exception during deserialization
May 13, 2020 01:45:28 PM | Error | Error while parsing Cardigann definition /opt/jackett/Definitions/mteamtp.yml: (Line: 2, Col: 3, Idx: 6) - (Line: 2, Col: 3, Idx: 6): Exception during deserialization
May 13, 2020 01:45:28 PM | Error | Error while parsing Cardigann definition /opt/jackett/Definitions/yggtorrent.yml: (Line: 2, Col: 3, Idx: 6) - (Line: 2, Col: 3, Idx: 6): Exception during deserialization
May 13, 2020 01:45:28 PM | Error | Error while parsing Cardigann definition /opt/jackett/Definitions/speedtorrentreloaded.yml: (Line: 2, Col: 3, Idx: 6) - (Line: 2, Col: 3, Idx: 6): Exception during deserialization
May 13, 2020 01:45:28 PM | Error | Error while parsing Cardigann definition /opt/jackett/Definitions/trezzor.yml: (Line: 1, Col: 3, Idx: 2) - (Line: 1, Col: 3, Idx: 2): Exception during deserialization
May 13, 2020 01:45:28 PM | Error | Error while parsing Cardigann definition /opt/jackett/Definitions/xtremezone.yml: (Line: 2, Col: 3, Idx: 6) - (Line: 2, Col: 3, Idx: 6): Exception during deserialization
```

**Comment by ngosang** [comment]
I have tested .NetCore and Mono in Linux and I can't reproduce those errors. All trackers are working for me.

Could you upload those files here or somewhere so we can see the content?

@garfield69 ping

**Comment by pax0707** [comment]
https://drive.google.com/open?id=18SVaeSd31LvOOyuWLBOUs0ZY40e1f_0G

**Comment by pax0707** [comment]
Full log.

[log.txt](https://github.com/Jackett/Jackett/files/4624462/log.txt)

**Comment by ngosang** [comment]
[hddolby.txt](https://github.com/Jackett/Jackett/files/4624524/hddolby.txt)
yep, that file wasn't updated hum.
I think the updater is ok, maybe he is suffering the old bug in the linux updater.

@pax0707 wait until the next automatic update and report back. it may fix itself.

**Comment by garfield69** [comment]
You are likely suffering from the old service vs. updated bug that was fixed a while ago, but which required the systemd launcher script to be replaced (which has to be done manually).

Please install the Jackett ARM32 0.16.427 package by following the notes at https://github.com/Jackett/Jackett#install-as-service-1 
And ensure you run the systemd install script to replace the current one.
This should restore you to a fully working Jackett and allow the updater to work properly in future.
Thanks.

**Comment by pax0707** [comment]
@garfield69 This did the trick.
Working fine after this.
