### ISSUE TITLE
[enhancement] totheglory 2FA support

### ISSUE THREAD

**Issue by Alvinnfly** [Jackett/Jackett#8625]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

jackett doesn't support ttg with 2fa and safe questions, request to add an cookie way to add ttg to jackett.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
when you are presented with the login page,
![image](https://user-images.githubusercontent.com/6933240/81866401-3fd05280-95c3-11ea-88e5-7cd8fab96ab8.png)
is it just a matter of entering the 2fa and security answer at the same time as the user and pwsd, 
or are there additional steps and challenges to complete the login?

**Comment by Alvinnfly** [comment]
there's no additional steps, just filling the 2fa code and the security answer.

**Comment by garfield69** [comment]
in which case we just need to add those boxes to the config, no need to use cookies.
I'll cook something up.

**Comment by garfield69** [comment]
Jackett 0.16.438
note I don't have an account so I could not test this change. 
As this is significantly different to some other sites' 2fa with the introduction of the security question, your feedback is important. 
So please report success or failure. Thanks.

**Comment by Curtis-L** [comment]
succceed, thanks a lot!
