### ISSUE TITLE
2fa support for ourbits

### ISSUE THREAD

**Issue by Alvinnfly** [Jackett/Jackett#8626]
ourbits has 2fa, so can we add ourbits through cookies?

**Comment by garfield69** [comment]
when you get the login page for this site, 
![image](https://user-images.githubusercontent.com/6933240/81865902-925d3f00-95c2-11ea-85d2-c0695f97d4e2.png)
is it just a matter of entering the 2fa code at the same time as you enter the user and pswd
or are there additional challenges or steps required to complete the loging for 2FA?

**Comment by Alvinnfly** [comment]
just enter the 2fa code in the login page, no additional steps.

**Comment by garfield69** [comment]
in which case we just need to add those boxes to the config, no need to use cookies.
I'll cook something up.

**Comment by garfield69** [comment]
Jackett 0.16.438
note I don't have an account so I could not test this change. 
But it is fairly straight forward and similar to others of the same style so I'm hopeful it should work.
Please report success or failure.

**Comment by Curtis-L** [comment]
i guess this would work but at this moment ourbits has cloudflare protection, unable to login though jackett
