### ISSUE TITLE
[rutracker] incorrect number of seeders

### ISSUE THREAD

**Issue by janot** [Jackett/Jackett#8629]
When there are no seeders Jackett displays number of "days without seeders" as "seeders":
![Capture](https://user-images.githubusercontent.com/1689966/81855086-8001e780-9567-11ea-92f0-b602942aa668.PNG)

![Capture](https://user-images.githubusercontent.com/1689966/81855194-a9bb0e80-9567-11ea-9ef2-c6044a677208.PNG)

"Angus & Julia Stone. Montreux Jazz Festival 2014"

**Comment by ngosang** [comment]
@janot Could you upload the HTML code from that search in rutracker?

**Comment by janot** [comment]
@ngosang https://pastebin.com/x5BS9Q1j

**Comment by garfield69** [comment]
Jackett 0.16.485
