### ISSUE TITLE
[ncore] wrong details link

### ISSUE THREAD

**Issue by janot** [Jackett/Jackett#8630]
leads to 404 page

e.g. should be not
ncore.cc/torrents.php?action=**download**&id=1498434
but 
ncore.cc/torrents.php?action=**details**&id=1498434

![Capture](https://user-images.githubusercontent.com/1689966/81856808-fc95c580-9569-11ea-8350-ea5233b84cc1.PNG)

**Comment by garfield69** [comment]
Jackett 0.16.449
