### ISSUE TITLE
HDCiTY

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8632]
**Indexer Name**
HDCiTY

**Indexer URLs**
https://hdcity.city/
https://hdcity.work/
https://hdcity.leniter.org/
https://hdcity4.leniter.org/

**Interface Language**
English, Chinese (Simplified, Traditional)

**Description**
HDCiTY is a CHINESE Private Torrent Tracker for HD Movies, TV, General

**Type**
YAML

**Access**
Private

**Notes**
- Supports IMDb ID Search (Using only the numerical part of the ID, minus the `tt`)
- Displays the IMDb URL in the search results
- Please ensure the inclusion of dead torrents for all categories

_This is the Chinese HDCiTY, not the Spanish one that's already supported. We should somehow differentiate their names on the indexer list UI to avoid confusion._

**Comment by garfield69** [comment]
Jackett 0.16.535

**Comment by RoloSoze** [comment]
Thank you!
