### ISSUE TITLE
[Bug] SpeedCD Doesn't Work 

### ISSUE THREAD

**Issue by VadVoci** [Jackett/Jackett#864]
[Bug] SpeedCD Doesn't Work 

Configuration failed: body{height:100%;background:url("/V3/img/index.png");font-family:"tahoma","arial","helvetica","sans-serif";font-size:8pt}h5{font-size:16px}Wrong Captcha!Please press back and try again.

**Comment by kaso17** [comment]
duplicate #417 (invite needed)
