### ISSUE TITLE
[ToTheGlory] Implement IMDb ID search & display IMDb URL in the search results | Update category mapping

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8642]
TTG allows searching via the IMDb ID, but it does things differently. The `tt` part needs to be replaced with the word `imdb` - For example: `tt4154796` needs to be entered as `imdb4154796` to return results. I assume Jackett can perform this change on the fly? I don't think the user should be forced to conform to this search format; it should be streamlined like all other IMDb ID search queries. 

The IMDb ID search is done via the main search box like any other normal search, and unlike NexusPHP trackers, there's no way to choose 'IMDb URL' as a search option - you just search directly.

Also, TTG returns the IMDb URL in the search results/browse page. Attached in an HTML example of the results of an IMDb ID search using the aforementioned format.

[TTG.zip](https://github.com/Jackett/Jackett/files/4629558/TTG.zip)

EDIT: The IMDb URL is actually already shown in Jackett, but I'll leave the HTML in case you need it.

**Comment by RoloSoze** [comment]
It also seems that the category mapping is out of date. I can see that results in the 4K UHD categories aren't returned in Jackett. If I post detailed screenshots of the categories and subcategories, would you be able to update the category mapping based on the existing code?

**Comment by garfield69** [comment]
>There are also more omitted results aside from the 4K ones. If I post detailed screenshots of the categories and subcategories, would you be able to update the category mapping based on the existing code?

The html you provided shows that there were just two additional cats, uhd-movie and uhd-bluray
I've added those two. If after this update you see additional missing cats then that means the new cats are undocumented (not in the pulldown menu), so if that happens we will need to see the html of the search results rows with the offending cats in order to add them to the mapping. 

>TTG allows searching via the IMDb ID, but it does things differently. The tt part needs to be replaced with the word imdb

I've added the requested support but cannot test as I don't have an account. Once published please test to check it works as intended. Provide log with debug and html in the event it does not work.
Thanks.

**Comment by RoloSoze** [comment]
> If after this update you see additional missing cats then that means the new cats are undocumented (not in the pulldown menu), so if that happens we will need to see the html of the search results rows with the offending cats in order to add them to the mapping.

I was referring to missing results from other searches I made, not this particular one. I'll attach screenshots of all search categories available so you can double check against existing ones.  

[TTG Categories.zip](https://github.com/Jackett/Jackett/files/4631034/TTG.Categories.zip)

Notice that under 'TV' and 'Other' there is one subcategory that spills over to the second line and might not be clearly visible. Also, the WiKi, NGB, DoA, etc are just the names of internal release groups that can be used as filtration search parameters, they're not subcategories,

**Comment by RoloSoze** [comment]
@garfield69 I did a quick comparison between the existing categories vs. the screenshots I sent, I can see that 'Documentary' and 'Others' are also missing some. These are the ones I spotted. There might be more.

**Comment by garfield69** [comment]
Pictures are of no use. I need to see the html so I can extract the actual selectors.
But is these are just the pictures of the pull down menu in the search page, then the html you provided in the first post already has these cats and I cross checked then against the indexer mapping, and only the two new UHD cats are found.
Just check again after the new release.

**Comment by garfield69** [comment]
Jackett 0.16.449

**Comment by RoloSoze** [comment]
Everything seems to work fine. I'll reopen this issue if I find anything. As always, thank you!
