### ISSUE TITLE
[turkseed] Exception (turkseed): Login failed: Selector "a[href*="/logout.php?logouthash="]" didn't match: Parse error

### ISSUE THREAD

**Issue by bingoxo** [Jackett/Jackett#8643]
using Jackett Version 0.16.438.0

**Comment by garfield69** [comment]
The indexer works for me, which suggest that this is something specific to your turkseed account.
Use your browser to login to the web site and confirm your credentials are correct, that you have a good ratio, and that you do not have any outstanding alerts, notices, unread PM, anything that could prevent Jackett from seeing the torrent search page.
Test this by trying to access the torrent search page on the web site.
If you are able to access the torrent search page on the web site with your browser, but the Jackett indexer continues to generate the same error in the title on this ticket, then please provide a full **enhanced** log so we can investigate further.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
Report back your findings. Thanks.

**Comment by bingoxo** [comment]
i hope this is enough : https://bin.privacytools.io/?ba454843be96b55b#Qle8vf0yOJNAsi9AoB3YryXYJBuzSOanJhoMBeVMIPM=

**Comment by garfield69** [comment]
not of any use sorry. really need to see the debug messages and html dumps that the enhanced log contains prior to the stack trace that you supplied.

**Comment by mkay1905** [comment]
i got the same issue and now account is banned.
check if you can log with your navigator first bingoxo

**Comment by bingoxo** [comment]
i didn't think enhanced logs are always needed so i'm sorry if you have to ask them every time , next time (hopefully there wont be any) , i'll add them to save us both time , here they are : https://bin.privacytools.io/?b0ebdf375b44edcd#4+A/KJPftpzByhxIrNPBbOBWefk94qUcNnJpOhMngcE=

**Comment by garfield69** [comment]
the log you provided is full of entries from torrent-turk, mvgroupforum, bluebirdhd, mteamtp, beyond-hd-oneurl, hon3yhd ...
but not turkseed.
It seems you did not restrict yourself to just testing turkseed but did additional activity when meant that the log overflowed.

But as it happens, I have today also got the same error you reported in your first post while testing turkseed again.

I see that the site has enabled an image captcha challenge on their login page, so we will need to incorporate that into the login code for the indexer.

**Comment by bingoxo** [comment]
![tss](https://user-images.githubusercontent.com/49401307/82126436-7ff72700-97b5-11ea-8f22-cf9ee34815bf.png)

i don't think the captcha is being detected with jackett

**Comment by garfield69** [comment]
works for me.
![image](https://user-images.githubusercontent.com/6933240/82128755-8fa45900-9811-11ea-9a3d-c197942e3725.png)
upgrade to Jackett 0.16.485

**Comment by garfield69** [comment]
if you don't get an image then this usually means that you are not being required to provide one.
