### ISSUE TITLE
[rutracker] Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by dam57950** [Jackett/Jackett#8646]
The captcha don't load

**Comment by garfield69** [comment]
If there is no captcha image then that simply means that you are not being challenged.
Take a look at the config, there is a **Captcha Info** description explaining this.
So leave the captcha text box empty and continue.
The Indexer works for me.
If your indexer fails to login, and the error message is about having not answered the captcha challenge correctly, then provide a full **enhanced** log so we can investigate.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
