### ISSUE TITLE
[REQ] New tracker: icetorrent.org

### ISSUE THREAD

**Issue by VadVoci** [Jackett/Jackett#865]
Please, could you add the tracker http://icetorrent.org (Romanian tracker / Lot of English Content) ?

Open Signups are closed but i have invitations for you .

Thanks you in advance!

**Comment by kaso17** [comment]
Please send the invite to kaso1717 -at- gmail.com

**Comment by VadVoci** [comment]
Invite Code Sent to kaso1717 -at- gmail.com !

**Comment by kaso17** [comment]
Fixed with 9795587e4de6777ef196dd06222956f19885e99b

**Comment by VadVoci** [comment]
I have this error:

"Found no results while trying to browse this tracker"

Please fix it when you have time.
