### ISSUE TITLE
[Nebulance] 2FA Support | Show 'Freeleech' for all releases

### ISSUE THREAD

**Issue by Curtis-L** [Jackett/Jackett#8651]
just need to enter 2fa code in login page, no other procedures.

**Comment by ngosang** [comment]
Please, send me an invite if you have.

**Comment by RoloSoze** [comment]
@cadatoiva If you're still around and have some time, you may want to look at this since you're a Nebulance member.

**Comment by just-an-alt** [comment]
I don't have any invites, but I'd happily help testing, as I also want this feature.

**Comment by RoloSoze** [comment]
@ngosang I will also add another small change for Nebulance. It's a ratioless tracker, and so all releases need to display 'Freeleech' next to them.

**Comment by RoloSoze** [comment]
@ngosang Did you manage to join Nebulance?

**Comment by ngosang** [comment]
Not yet

**Comment by RoloSoze** [comment]
> 
> 
> Not yet

No problem. It's just a matter of sending a DM like I mentioned to you in my email. Whenever you get the chance. Thanks.

**Comment by garfield69** [comment]
Jackett 0.16.1412
