### ISSUE TITLE
[REQ] New tracker: www.myxz.org

### ISSUE THREAD

**Issue by VadVoci** [Jackett/Jackett#866]
Please, could you add the tracker http://www.myxz.org (Romanian tracker XtremeZone / Lot of English Content) ?

Open Signups are closed but i have invitations for you .

Thanks you in advance!

**Comment by kaso17** [comment]
Please send the invite to kaso1717 -at- gmail.com

**Comment by VadVoci** [comment]
Invite Code Sent to kaso1717 -at- gmail.com !

**Comment by VadVoci** [comment]
Oups ... Duplicate? https://github.com/Jackett/Jackett/issues/540

**Comment by kaso17** [comment]
fixed with 42434c35a156f630d9256b7a5e7afeaa1f555f73
