### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s). (Test)

### ISSUE THREAD

**Issue by 3th3r** [Jackett/Jackett#8660]
### Environment

OS: Centos

Mono

Net Version: 6.80.105

Jackett Version: 0.16.449

Last Working Jackett Version**: 0.16.438.0

VPN: No

### Description

With a previously set yggtorrent (working) click on test.
Test not working an error occured: " An error occurred while testing this indexer
Exception (yggtorrent): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s)."
Same behavior after update
same behavior after recreating the indexer (deleting and recreating)
ID and password are correct.

Must be yggtorrent messing arround with their api again .....

### Logged Error Messages

An error occurred while testing this indexer
Exception (yggtorrent): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s).

**Comment by 3th3r** [comment]
Sorry I've search if their was already an issues...
Github didn't return a recent issue with ygg.

**Comment by ilike2burnthing** [comment]
See the tagged issue from jackettbot. Fix will be out with the next release
