### ISSUE TITLE
zelkaorg: site down

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8663]
- http://zelka.org/ # Bulgarian IP address filtering
  - http://zamunda.se/ # Bulgarian IP address filtering

Tested with: https://www.uptrends.com/tools/uptime

@ilike2burnthing could you confirm that it can't be accessed from Bulgaria?

**Comment by ilike2burnthing** [comment]
I eventually found a server that it worked on. Yea it's up, just also appears to be blocking known VPN IPs.

Note to self: 19
