### ISSUE TITLE
[REQ] New tracker: www.torrentsmd.com

### ISSUE THREAD

**Issue by VadVoci** [Jackett/Jackett#867]
Please, could you add the tracker http://www.torrentsmd.com / http://www.torrentsmd.eu (Moldavian tracker / Lot of English Content) ?

(Registration is currently closed, but is open every Saturday.)
Open Signups are closed but i have invitations for you . 

Thanks you in advance!

**Comment by kaso17** [comment]
Please send the invite to kaso1717 -at- gmail.com

**Comment by VadVoci** [comment]
Invite Code Sent to kaso1717 -at- gmail.com !

**Comment by kaso17** [comment]
Fixed with 849b9e9765fad9826532484103d0c4130a1d9620
