### ISSUE TITLE
[REQ] ViaTorrents

### ISSUE THREAD

**Issue by lunks** [Jackett/Jackett#8672]
Full Website URL: https://viatorrents.com/
Search URL: https://viatorrents.com/index.php?s=
It's a public website
It only supports movies and tv series

There can be multiple links on each page for a given release (i.e. all seasons for a show). You need to enter the pages for each of them and then there's the magnet link.

Thanks!

**Comment by garfield69** [comment]
https://viatorrents.com/ returns Error 520 Web server is returning an unknown error
