### ISSUE TITLE
pornleech: site down

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8676]
http://pornleech.io/

![image](https://user-images.githubusercontent.com/10577978/82103851-f2fc9100-9714-11ea-9f7a-1dfce41d918a.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
Aaaaaand back down - times out with 524 error

**Comment by ilike2burnthing** [comment]
back up, for now

**Comment by garfield69** [comment]
http://pornleech.io/ returniung cloudflare Error 524 A timeout occurred
its offline

**Comment by ilike2burnthing** [comment]
Back up but with no local images displayed. Site is clearly borked, so I'll leave as being down for now.

**Comment by ilike2burnthing** [comment]
working again, so I'll hesitantly close (again)

**Comment by garfield69** [comment]
seeing Error 524 A timeout occurred

**Comment by garfield69** [comment]
working so far.

**Comment by garfield69** [comment]
http://pornleech.io/ not returning from the 5 second cloudflare DDoS protection check
Error 524 A timeout occurred

**Comment by ilike2burnthing** [comment]
Works for me after ~20s

**Comment by garfield69** [comment]
clearly an intermittent server overloaded issue. 
not reliable atm.

**Comment by ilike2burnthing** [comment]
Been working consistently over the past 2 days, so while I can just see this failing as soon as I comment, going to mark this as closed...for now...
