### ISSUE TITLE
[REQ] New tracker: www.u-torrents.ro

### ISSUE THREAD

**Issue by VadVoci** [Jackett/Jackett#868]
Please, could you add the tracker http://www.u-torrents.ro (Romanian tracker / Lot of English Content) ?

Open Signups are closed, but i have invitations for you .

Thanks you in advance!

**Comment by kaso17** [comment]
Please send the invite to kaso1717 -at- gmail.com

**Comment by VadVoci** [comment]
Invite Code Sent to kaso1717 -at- gmail.com !

**Comment by kaso17** [comment]
fixed with eacfd53466d324c641680b020d769013b3d922c7

**Comment by garfield69** [comment]
https://www.u-torrents.ro/ returning Error 522 Connection timed out
