### ISSUE TITLE
[req][animebytes] ability to exclude specific alternative titles

### ISSUE THREAD

**Issue by giosann** [Jackett/Jackett#8683]
### Environment

**Jackett Version**: 0.16.793.0

### Description

The torrents have up to 4 title fields: Main title, Japanese title, romaji title and Alternative Title.
The problem is that the "Alternative Title" is used as "Alternative Title**s**" and the resulting query is not good.

For example here: https://animebytes.tv/torrents.php?id=64975

![1](https://user-images.githubusercontent.com/10052873/82126357-8208b800-97ac-11ea-95e5-8dfc6671c91f.png)

```
Main title: "Kaguya-sama: Love is War?"
Japanese Title: "かぐや様は告らせたい？～天才たちの恋愛頭脳戦～"
Romaji Title: "Kaguya-sama wa Kokurasetai? ~Tensai-tachi no Ren'ai Zunousen~"
Alternative Title: "Kaguya-sama: Love is War Season 2, Kaguya-sama: Love is War 2nd Season, Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen 2nd Season"

```
If I enable the "Add releases for each synonym title" flag it adds all 3 additional fields and the query for the alternative title is useless.

I'd like to either be able to select in more detail the titles I want to use.
It would also be nice to have an option to comma separate the Alternative Title field into separate queries.

Thanks for your hard work

edit: an option to list by filename could also be interesting.

edit2: I've made this image of what I think would be something really good.
![2020-05-24_11-51-02](https://user-images.githubusercontent.com/10052873/82751248-3c547c80-9db6-11ea-97b8-9272da2e9bf0.png)

**Comment by giosann** [comment]
If you accept bounties I'll put a 50 € one on this request.

**Comment by seeyabye** [comment]
@giosann is this offer still standing?

**Comment by giosann** [comment]
Yes, it's still standing, what do you think of the last image I attached?

**Comment by seeyabye** [comment]
I agree with the options you included in the screenshot except for the following two additions:

- Add Main Title
- Subcheck-box for Comma separate alternatives

I think removing Main Title would break the indexer if users are not careful, and it should be a default option included regardless.

Comma separation is redundant and I don't quite see the need to add that option. 

On the side note, I'm just curious about this particular use case. The returned results from Jackett would be quite many, what software are you using that requires this addition?

**Comment by giosann** [comment]
No problem excluding the "Add Main Title"

I'd like to have the "Comma separate" options because since the filed is used 1 or more titles inside the resulting entry in sonarr is always marked as unknown series in those cases.

For example, https://animebytes.tv/torrents.php?id=64970 has 3 titles:

`
Main Title: "Yahari Ore no Seishun Lovecome wa Machigatte Iru. Kan"
Japanese: "やはり俺の青春ラブコメはまちがっている. 完"
Alternative Title: "My Teen Romantic Comedy SNAFU Climax, Oregairu S3"
`

if I search in sonarr for an episode this is the result:

![NBjilln46m](https://user-images.githubusercontent.com/10052873/92700609-4ee7c700-f34f-11ea-8a42-e5250308c5bf.png)

both the Japanese title and the alternative title get rejected as "unknown series", this is usually a non-issue since normally it correctly matches the main title but this is not always the case and the main title sometimes also gets marked as unknown series. I think it's completely useless to have a query with multiple titles inside because it will never be correctly matched.

**Comment by seeyabye** [comment]
Absolutely, the comma separation shouldn't be an option, but rather, by default it will use comma separation, and there is no need to half another sub-check box.

For example, this is what I have right now:

![Annotation 2020-09-10 172905](https://user-images.githubusercontent.com/36906720/92701720-4b723100-f38b-11ea-8458-b2c0a9acb974.jpg)

And the following is the result of this:

![animebytes](https://user-images.githubusercontent.com/36906720/92701814-6b095980-f38b-11ea-9ef2-5168b0593563.png)

I'll be submitting this pull request later.

**Comment by giosann** [comment]
Ah, then sure, I misunderstood at first.
Looks good!

**Comment by seeyabye** [comment]
Filenames are not returned via AB's API. 

We could do it through a different method, but it wouldn't be ideal partly because of several reasons. One of them mainly being, that AB may not like it and it may cause some repercussions towards your account.

**Comment by giosann** [comment]
It's fine without the filename, thanks

**Comment by ngosang** [comment]
@yuri-moens @giosann tomorrow will be published a new release with a fix for this issue. Could you test it and give us some feedback?

**Comment by giosann** [comment]
sorry for the delay, everything works perfectly. Thanks

I've opened a request to add the file name in the APIs.

https://animebytes.tv/forums.php?action=viewthread&threadid=26575
