### ISSUE TITLE
Error Adding Torrentleech.me

### ISSUE THREAD

**Issue by iSteeb** [Jackett/Jackett#8685]
### Environment

**OS**: Windows 10

**Jackett Version**: 0.16.487

No proxy, no VPN.

### Description
In the WebUI, when I try to add Torrentleech, I get an error that Jackett cannot connect to server.  It looks like from my very limited understanding of the logs, that there's an SSL error?  Only seems to happen with Torrentleech though.

[log.txt](https://github.com/Jackett/Jackett/files/4639593/log.txt)

**Comment by garfield69** [comment]
It appears that your ISP is blocking your access to the official domain https://www.torrentleech.org/ whose certificate has a thumbprint of 
68c2d583a28eeb05ec4b0391d8421db2ecc9744f
the certificate your Jackett is being asked to use has a thumbprint of 
5405A6E565FB1C3DE67D63136832094A8B141BF9

A possible solution you can try is to stop using the DNS provided by your ISP and switch to one of the public ones from Google (8.8.8.8 and 8.8.4.4) or Cloudflare (1.1.1.1 and 1.0.0.1). 
An alternate approach is to use a VPN or proxy.
