### ISSUE TITLE
kinozal: missing search results

### ISSUE THREAD

**Issue by janot** [Jackett/Jackett#8686]
letter "й" is replaced with "и"

![Capture](https://user-images.githubusercontent.com/1689966/82140464-9b0a7b00-9837-11ea-8724-33a38cfe495c.PNG)

![Capture](https://user-images.githubusercontent.com/1689966/82140371-862de780-9837-11ea-8c6b-b53d57e411fb.PNG)

**Comment by garfield69** [comment]
probably a blowback from this code in the indexer
https://github.com/Jackett/Jackett/blob/fd7a47e45d64996c04ebeab789e07a83acfaed49/src/Jackett.Common/Definitions/kinozal.yml#L107-L117
which calls this routine in Cardigann
https://github.com/Jackett/Jackett/blob/6156ad0cd5c35e60d7a1c827fbc690de475667a8/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1082-L1103

the whole keywords filter section with the diacritics was added for Sonarr support #4767 67d7562882b8764d969294deb75a707bc8e22902
lifted out of some other Russian indexers

I suppose we could drop the diacritics, but if any Sonarr users complains then we have a conflict, as we cannot code exceptions with cardigann.

**Comment by garfield69** [comment]
Jackett 0.16.511
