### ISSUE TITLE
[REQ] New tracker: datascene.net

### ISSUE THREAD

**Issue by VadVoci** [Jackett/Jackett#869]
Please, could you add the tracker http://datascene.net (Romanian tracker / Lot of English Content) ?

Open Signups are opened, but .. if somehow will be closed, i have invitations for you .

Thanks you in advance!

**Comment by kaso17** [comment]
registered, added to TODO

**Comment by kaso17** [comment]
Fixed with 94872affa946c96e63ced127bae4f08b51bd5232

**Comment by ilike2burnthing** [comment]
https://datascene.net/ - ERR_NAME_NOT_RESOLVED

**Comment by garfield69** [comment]
v0.18.551
