### ISSUE TITLE
[passthepopcorn] Parse error (Config)

### ISSUE THREAD

**Issue by Mike-Spray** [Jackett/Jackett#8691]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: UNRAID docker 

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:0.16.488.0

**Last Working Jackett Version**: none, first setup

**Are you using a proxy or VPN?** No

### Description

Filled out form, submit. Fails with parse error. 

### Logged Error Messages

Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70 Jackett.Common.ExceptionWithConfigData: Parse error
   at Jackett.Common.Indexers.PassThePopcorn.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/PassThePopcorn.cs:line 85
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.

**Comment by Mike-Spray** [comment]
I have edited the issue with more details. 

The referenced issue by the bot was closed.

**Comment by garfield69** [comment]
@RoloSoze  is passthepopcorn working for you?

**Comment by RoloSoze** [comment]
> 
> 
> @RoloSoze is passthepopcorn working for you?

Yessir, it's working fine.

**Comment by garfield69** [comment]
@Mike-Spray  to investigate this further for you, we are going to need the full **enhanced** log file which when activated should record the debug and html returned from the site and hopefully provide the clue to your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Mike-Spray** [comment]
> @Mike-Spray to investigate this further for you, we are going to need the full **enhanced** log file which when activated should record the debug and html returned from the site and hopefully provide the clue to your issue.
> See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

See attached log in the first comment.

**Comment by Mike-Spray** [comment]
Edited log with my keys out

**Comment by Mike-Spray** [comment]
Shorter log. Maybe it's because PTP is throwing my IP an error today. Perhaps I just need to wait a bit.

**Comment by garfield69** [comment]
the logs shows that the PTP web site returned `Returning TooManyRequests => Your popcorn quota has been reached, come back later!`

Are you able to use your browser from the same machine that is running Jackett, and access the website, login, and access the torrent search page? Or are you being blocked there too?

I think you may be right. wait and try again tomorrow. check that the enhanced logging is enabled on your dashboard tomorrow before starting a fresh attempt, so you can capture as much activity as you can in the log. Lets see what happens tomorrow.

**Comment by garfield69** [comment]
found this in a previous ticket https://github.com/Jackett/Jackett/issues/380#issuecomment-230134677

**Comment by RoloSoze** [comment]
> 
> 
> The logs shows that the PTP web site returned `Returning TooManyRequests => Your popcorn quota has been reached, come back later!`
> 

PTP has a limit on the number of searches - or the amount of traffic, not sure which one - each user can make every day. There's nothing wrong with Jackett, you just need to wait until tomorrow - however that's defined - to be able to use it. If you try to access PTP's website, you'll see the same message.
