### ISSUE TITLE
[REQ] Please add new tracker x264.me

### ISSUE THREAD

**Issue by sethwarsh** [Jackett/Jackett#87]
Please add new tracker x264.me , I can provide an invite upon reques. Skype 'sethmw' email 'setmw@'gmail.com'

Torznab categories:

//AddCategoryMapping("1", TorznabCatType.Console);

//AddCategoryMapping("1", TorznabCatType.ConsoleNDS);

//AddCategoryMapping("1", TorznabCatType.ConsolePSP);

//AddCategoryMapping("1", TorznabCatType.ConsoleWii);

//AddCategoryMapping("1", TorznabCatType.ConsoleXbox);

//AddCategoryMapping("1", TorznabCatType.ConsoleXbox360);

//AddCategoryMapping("1", TorznabCatType.ConsoleWiiwareVC);

//AddCategoryMapping("1", TorznabCatType.ConsoleXBOX360DLC);

//AddCategoryMapping("1", TorznabCatType.ConsolePS3);

//AddCategoryMapping("1", TorznabCatType.ConsoleOther);

//AddCategoryMapping("1", TorznabCatType.ConsoleOther);

//AddCategoryMapping("1", TorznabCatType.ConsoleOther);

//AddCategoryMapping("1", TorznabCatType.ConsoleOther);

//AddCategoryMapping("1", TorznabCatType.ConsoleOther);

//AddCategoryMapping("1", TorznabCatType.ConsoleOther);

//AddCategoryMapping("1", TorznabCatType.Console3DS);

//AddCategoryMapping("1", TorznabCatType.ConsolePSVita);

//AddCategoryMapping("1", TorznabCatType.ConsoleWiiU);

//AddCategoryMapping("1", TorznabCatType.ConsoleXboxOne);

//AddCategoryMapping("1", TorznabCatType.ConsolePS4);

//AddCategoryMapping("1", TorznabCatType.Movies);

//AddCategoryMapping("1", TorznabCatType.MoviesForeign);

//AddCategoryMapping("1", TorznabCatType.MoviesOther);

//AddCategoryMapping("1", TorznabCatType.MoviesOther);

AddCategoryMapping(“33”, TorznabCatType.MoviesSD);

AddCategoryMapping(“53”, TorznabCatType.MoviesHD);

//AddCategoryMapping("1", TorznabCatType.Movies3D);

//AddCategoryMapping(“1”, TorznabCatType.MoviesBluRay);

AddCategoryMapping(“50”, TorznabCatType.MoviesDVD);

AddCategoryMapping("31", TorznabCatType.MoviesWEBDL);

//AddCategoryMapping(“1, TorznabCatType.Audio);

//AddCategoryMapping("1”, TorznabCatType.AudioMP3);

//AddCategoryMapping("1", TorznabCatType.AudioVideo);

//AddCategoryMapping("1", TorznabCatType.AudioVideo);

//AddCategoryMapping("1", TorznabCatType.AudioAudiobook);

AddCategoryMapping(“434”, TorznabCatType.AudioLossless);

//AddCategoryMapping("1", TorznabCatType.AudioOther);

//AddCategoryMapping("1", TorznabCatType.AudioOther);

//AddCategoryMapping("1", TorznabCatType.AudioForeign);

//AddCategoryMapping("1", TorznabCatType.PC);

//AddCategoryMapping("1", TorznabCatType.PC);

//AddCategoryMapping("1", TorznabCatType.PC0day);

//AddCategoryMapping("1", TorznabCatType.PCISO);

//AddCategoryMapping("1", TorznabCatType.PCMac);

//AddCategoryMapping("1", TorznabCatType.PCPhoneOther);

//AddCategoryMapping("1", TorznabCatType.PCGames);

//AddCategoryMapping("1", TorznabCatType.PCPhoneIOS);

//AddCategoryMapping("1", TorznabCatType.PCPhoneAndroid);

//AddCategoryMapping("1", TorznabCatType.TV);

//AddCategoryMapping("1", TorznabCatType.TV);

AddCategoryMapping("1", TorznabCatType.TVWEBDL);

//AddCategoryMapping("30", TorznabCatType.TVWEBDL);

//AddCategoryMapping("1", TorznabCatType.TVFOREIGN);

//AddCategoryMapping("1", TorznabCatType.TVFOREIGN);

//AddCategoryMapping(“1“, TorznabCatType.TVSD);

AddCategoryMapping(“25”, TorznabCatType.TVSD);

AddCategoryMapping(“51”, TorznabCatType.TVHD);

AddCategoryMapping(“54”, TorznabCatType.TVHD);

//AddCategoryMapping("1", TorznabCatType.TVOTHER);

//AddCategoryMapping(“1”, TorznabCatType.TVSport);

//AddCategoryMapping(“1”, TorznabCatType.TVAnime);

//AddCategoryMapping("1", TorznabCatType.TVDocumentary);

//AddCategoryMapping(“1”, TorznabCatType.MoviesBBC);

//AddCategoryMapping("1", TorznabCatType.XXX);

AddCategoryMapping(“41, TorznabCatType.XXXHD);

//AddCategoryMapping(“429”, TorznabCatType.XXXHD);

//AddCategoryMapping(“1”, TorznabCatType.XXXDVD);

//AddCategoryMapping(“1”, TorznabCatType.XXXDVD);

//AddCategoryMapping(“1”, TorznabCatType.XXXBluRay);

//AddCategoryMapping(“1”, TorznabCatType.XXXBluRay);

//AddCategoryMapping("1", TorznabCatType.XXXWMV);

//AddCategoryMapping(“424”, TorznabCatType.XXXXviD);

//AddCategoryMapping(“1”, TorznabCatType.XXXXviD);

//AddCategoryMapping(“1”, TorznabCatType.XXXTV);

//AddCategoryMapping(“1”, TorznabCatType.XXXTV);

//AddCategoryMapping("1", TorznabCatType.XXXx264);

//AddCategoryMapping("1", TorznabCatType.XXXOther);

//AddCategoryMapping("1", TorznabCatType.XXXImageset);

//AddCategoryMapping("1", TorznabCatType.XXXPacks);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.OtherMisc);

//AddCategoryMapping("1", TorznabCatType.OtherHashed);

//AddCategoryMapping(“1”, TorznabCatType.Books);

//AddCategoryMapping("1", TorznabCatType.BooksEbook);

//AddCategoryMapping("1”, TorznabCatType.BooksComics);

//AddCategoryMapping("1", TorznabCatType.BooksComics);

//AddCategoryMapping("1", TorznabCatType.BooksComics);

//AddCategoryMapping("1", TorznabCatType.BooksMagazines);

//AddCategoryMapping("1", TorznabCatType.BooksTechnical);

//AddCategoryMapping("1", TorznabCatType.BooksOther);

//AddCategoryMapping("1", TorznabCatType.BooksForeign);

//AddCategoryMapping("1”, TorznabCatType.Software);

/AddCategoryMapping(“1”, TorznabCatType.Game);

//AddCategoryMapping(“1”, TorznabCatType.TVDVD);

//AddCategoryMapping(“1”, TorznabCatType.TVBluRay);ok

**Comment by conihorse** [comment]
Site uses reCapcha validation, so automated access not viable

**Comment by WhatFox** [comment]
So does TD, it can be done :)

**Comment by testarea1** [comment]
Anyone tried to take a stab at adding this? Would it appear to be the same as TorrentDay with the captcha, maybe equires us to manually get cookie like TD? https://github.com/zone117x/Jackett/wiki/Finding-cookies
