### ISSUE TITLE
[REQ] New tracker: rodvd.net

### ISSUE THREAD

**Issue by VadVoci** [Jackett/Jackett#870]
Please, could you add the tracker http://rodvd.net (Romanian tracker / Lot of English Content) ?

Open Signups are closed but i have invitations for you . (Fake 404 index page! ;) )

Thanks you in advance!

**Comment by kaso17** [comment]
Please send the invite to kaso1717 -at- gmail.com

**Comment by VadVoci** [comment]
Invite Code Sent to kaso1717 -at- gmail.com !

**Comment by kaso17** [comment]
for some reason it's automatically logging me off again after logging in. I've put it on hold for now. Will look into it later again.

**Comment by VadVoci** [comment]
If they do not allow access to you, it's not worth it.

Let them in their darkness . They remain forever in obscurity.

**Comment by VadVoci** [comment]
Any news/updates about RoDVD?

**Comment by kaso17** [comment]
no time to look into it yet

**Comment by VadVoci** [comment]
Thanks for all your work kaso17.  
When you have a free time, please look over RoDVD ;)

**Comment by kaso17** [comment]
seems like some other change fixed the problem. Added with e2937762d4084de3af74dd0a5c1f529f0a3a8c4e
