### ISSUE TITLE
Cardigann Questions

### ISSUE THREAD

**Issue by masterwok** [Jackett/Jackett#8707]
### Description

I'm currently trying to port the `CardigannIndexer.cs` to Kotlin. However, I'm running into issues due to duplicate keys in many of the YAML definitions. 

- Why are keys duplicated rather than nested in a list?
- Why not use JSON?
- Should these be fixed and/or converted to JSON?

**Comment by garfield69** [comment]
The original authors of the Cardigann engine are not contributing any longer, so there is no one left to ask about their design choices.
Originally, the Jackett Indexer were all written in C#, and some still are, when indexers need more complex coding than the current Cardigann YAML indexer can provide.
So the Cardigann processor was created to provide a simpler way to code indexers, using a YAML style coding structure, for indexers that do not require complex processing to make queries to web sites and process the returned HTML.

>Why are keys duplicated rather than nested in a list?

no idea what you mean, please expand with examples.

>Why not use JSON?

YAML has many additional features lacking in JSON, including comments, extensible data types, relational anchors, strings without quotation marks, and mapping types preserving key order.

>Should these be fixed and/or converted to JSON?

Nope. The current Cardigann engine is constantly being enhanced by the current crop of C# dev volunteers, and while the indexers code that the Cardigann processor parses may have started out as true YAML compliant structures in the early days, the code is probably by now divergent from true YAML standards.  And as long as the indexers code meets the requirements of Jackett then I really don't care that they may no longer follow YAML guidelines. It meets our needs.

**Comment by masterwok** [comment]
Thank you for the quick and detailed response.

> no idea what you mean, please expand with examples.

One instance this occurs is within `1337x.yml` in the `fields` section. The key `date` occurs 3 times. Most YAML parsers I've found and either fail to deserialize the graph altogether or replace the value for the key with the last instance. I'll be able to work around this, I just thought it was odd.

>  YAML has many additional features lacking in JSON, including comments, extensible data types, relational anchors, strings without quotation marks, and mapping types preserving key order.

That's neat, I've never worked with YAML before. Those are some cool features.

> And as long as the indexers code meets the requirements of Jackett then I really don't care that they may no longer follow YAML guidelines. It meets our needs.

I totally agree.
