### ISSUE TITLE
Long titles getting cut off in search results (qbitorrent)

### ISSUE THREAD

**Issue by alystair** [Jackett/Jackett#8708]
### Environment

**OS**: Win 10 64

**.Net Runtime**: ?_?

**.Net Version**: latest

**Jackett Version**: 0.16.496.0

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?** no

### Description

Long titles are cut off, breaking search and manual selection - see screenshot.
Need to increase maximum length or provide an option to change it, can't see episode #s etc.

### Logged Error Messages

N/A

### Screenshots

[Place any screenshots of the issue here if needed]
![image](https://user-images.githubusercontent.com/159109/82293804-22143c00-997b-11ea-80a8-bbc188c6e875.png)

**Comment by garfield69** [comment]
The length of the titles is totally dependent on what the web site sends to the corresponding Jackett indexer.
The Jackett indexers do not deliberately crop the length of the titles it is given, but it is possible that a particular indexer for a web site may be selecting a cropped title rather than a full length one, assuming that such a full title was available in the results provided by the web sites search page in the first place.

So in order to investigate this, you are going to need to identify the name of the indexer that you are reporting is showing cropped titles, so we can check of the related web site and investigate if full titles are available there in the results of its search page.

**Comment by alystair** [comment]
The name of the indexer is right there...? LimeTorrents

**Comment by garfield69** [comment]
Oh, I thought [limetorrents] was part of the title, as many web site have torrents from other sites and tag them with the source site name, so I was not sure. ;-)

So as you can see, the limetorrents web site crops the titles in its results
![image](https://user-images.githubusercontent.com/6933240/82299313-78c85700-9a09-11ea-823d-d858343e9508.png)
which is what the jackett limetorrents indexers also returns
![image](https://user-images.githubusercontent.com/6933240/82299381-8e3d8100-9a09-11ea-8350-0da7a7242378.png)
Behind the scenes, this is the HTML from one of the cropped rows that limetorrents returns
```html
                        <tr bgcolor="#F4F4F4">
                            <td class="tdleft">
                                <div class="tt-name">
                                    <a href="/20200515m-(HD720P-H264)(GANA)(200GANA-2292-dn6g6521)百戦錬磨のナンパ師のヤリ部屋で、連れ込みSEX  -   -torrent-14692311.html">20200515m (HD720P H264)(GANA)(200GANA-2292 dn6g6521)百戦錬磨のナンパ師�..</a>
                                </div>
                                <div class="tt-options"></div>
                            </td>
                            <td class="tdnormal">8 minutes ago</td>
                            <td class="tdnormal">1.48 GB</td>
                            <td class="tdseed">14</td>
                            <td class="tdleech">14</td>
                            <td class="tdright">
                                <div class="hb2"></div>
                            </td>
                        </tr>
```
as you can see, there is no full version of the title available anywhere in the html sent by the web site to the Jackett indexer, so unfortunately there is no way for us to present the full title.

**Comment by garfield69** [comment]
wait, took a second look. the full title is in the href not the title text.
I think we can do something with this.
I'll get back to you shortly.

**Comment by garfield69** [comment]
Yes. I can use the href. I will have to clean it up a bit, drop the `-torrent-1234567.html` at the end, and the forward slash at the start,  and switch dashes with spaces for the rest, but it should be good enough to pass as a full title. 
Albeit will not be a perfect match for the abbreviated title, as the href drops all the special characters such as exclamation marks, commas etc, but it should work.

**Comment by garfield69** [comment]
will be available in the next release due to be published in about 23 hours.

**Comment by alystair** [comment]
I gotta say this entire series of events and turn around has been mighty impressive - great velocity!

**Comment by garfield69** [comment]
Jackett 0.16.511
