### ISSUE TITLE
Sceneaccess tracker not working. .eu closed, .org open.

### ISSUE THREAD

**Issue by darksidedora** [Jackett/Jackett#871]
Sceneaccess tracker isn't working. It seems to be an easy fix, currently the configured tracker in Jackett points to Sceneaccess.eu. This domain is defunct, but Sceneaccess is still active at sceneaccess.org.

Should be as simple as replacing .eu with .org in the configs.

**Comment by VadVoci** [comment]
even sceneaccess.org not working...

**Comment by savahu** [comment]
SCC just has a lot of downtime nowadays. None of the domains work; the server is down.

**Comment by armani316** [comment]
They've been having a lot of problems due to faulty hardware but things should be fine now. I suggest allowing users to use both URLs (same as HDT & IPT):

https://sceneaccess.eu/
https://sceneaccess.org/

Both are working fine for me at the moment.

**Comment by kaso17** [comment]
With the new Site Link field for all trackers it should be fixed
