### ISSUE TITLE
[REQ] punktorrents

### ISSUE THREAD

**Issue by nukepaste** [Jackett/Jackett#8713]
https://www.punktorrents.com/

semi-private

**Comment by garfield69** [comment]
does the site have a search that returns results in the same layout as the https://www.punktorrents.com/torrents.php page ?
all i can find is a general search that presents topics which is not ideal.

**Comment by nukepaste** [comment]
I guess not.  I've poked around for 5-10 minutes and the only results are forums/message posts, that then link to the torrent/magnet.  I/We could try sending the question to the site admin/owners.


________________________________

**Comment by garfield69** [comment]
With the thread posts from the search having nothing but titles, and the torrents page useful only for the keyword-less search, I don't think a yaml indexer is right for this site.
Lets see if anyone volunteers to write an indexer in C#.
My initial feeling is that this site is not suitable for use with Jackett.

**Comment by garfield69** [comment]
strange goings on. why does karsar.tv (korsar.rest ?) sometimes complain about too many redirects and ends up landing on https://www.punktorrents.com/member.php?action=register !??

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
