### ISSUE TITLE
FunFIle can't sign in

### ISSUE THREAD

**Issue by Mahmoud87** [Jackett/Jackett#872]
Hello guys, am having issues with funfile I can login fine on the web but when I configure it on Jackett I get this errors

```
When	Level	Message
Dec 19, 2016 06:59:36 PM	Error	
headerString:
Dec 19, 2016 06:59:36 PM	Error	
cookies: 
Dec 19, 2016 06:59:36 PM	Error	
request.RawPOSTDdata: 
Dec 19, 2016 06:59:36 PM	Error	
request.Referer: https://www.funfile.org/takelogin.php
Dec 19, 2016 06:59:36 PM	Error	
request.Cookies: 
Dec 19, 2016 06:59:36 PM	Error	
request.Url: https://www.funfile.org/takelogin.php
Dec 19, 2016 06:59:36 PM	Error	
request.Method: POST
Dec 19, 2016 06:59:36 PM	Error	
got NotImplemented/InternalServerError
```

Thanks 👍

**Comment by kaso17** [comment]
Usually happens on certificate issues.
Please try running the following command on your server:
curl -v https://www.funfile.org/

**Comment by Mahmoud87** [comment]
I have had a chat with one of the admins on the tracker and they mentioned they issues with their servers in Oceania, so maybe its the  problem their end not 100% sure, also I originally had troubles to login to the website and had to add their ip address to my hosts file so it can resolve. Thanks mate for looking into this. 
Here is the output.
```
~]# curl -v https://www.funfile.org/
* About to connect() to www.funfile.org port 443 (#0)
*   Trying 118.88.20.194...
* No route to host
* Failed connect to www.funfile.org:443; No route to host
* Closing connection 0
curl: (7) Failed connect to www.funfile.org:443; No route to host

```

**Comment by kaso17** [comment]
with that error it's definitely an error on their side or your ISPs. You can't connect to funfile at all.

**Comment by Mahmoud87** [comment]
Awesome mate I thought this would be the case. Thanks for getting back to me. Feel free to close this one off
