### ISSUE TITLE
[rarbg] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by electrona** [Jackett/Jackett#8720]
### Environment

**OS**: Debian buster

**.Net Runtime**: Mono

**Jackett Version**: 0.16.511

**Last Working Jackett Version**: 0.16.496

**Are you using a proxy or VPN?** no

**Comment by ilike2burnthing** [comment]
Working ok here. Can you test again just in case it was a temporary issue?

**Comment by electrona** [comment]
It's working. Removing and adding it again worked. Closing issue.
