### ISSUE TITLE
Indexer parsing errors - Docker image (linuxserver/jackett - 21/05/2020)

### ISSUE THREAD

**Issue by DarkPsionix** [Jackett/Jackett#8726]
### Environment

**OS**: Docker Image _running on Synology Diskstation_  

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.16.515.0

**Are you using a proxy or VPN?** : No

### Description

After upgrading to the last published docker image (linuxserver/jackett - 21/05/2020), most of the indexer are not working anymore with the following errors in the log file.

` Error while parsing Cardigann definition /app/Jackett/Definitions/\<indexer\>.yml: (Line: 2, Col: 3, Idx: 6) - (Line: 2, Col: 3, Idx: 6): Exception during deserialization
`

### Screenshots

![image](https://user-images.githubusercontent.com/65708874/82544157-fba9f880-9b54-11ea-8213-4871977a8d87.png)

**Comment by garfield69** [comment]
is the app/Jackett/Definitions folder located in the docker image or on your system with some kind of docker startup parm pointing to it?

**Comment by garfield69** [comment]
I just fetched and ran the latest docker Jackett 0.16.515 image (on my ubuntu18 image on the windows10 VirtualBox) and it runs without issue, so the problem is particular to your set up somehow.

I would suggest shutting down your docker jackett image, updating the docker service to the latest version if you are not already on it, purge any docker Jackett images and fetch the **latest** tag image again and see if that sorts it out.

**Comment by ilike2burnthing** [comment]
Can confirm that my long running and regularly updated Jackett container (now 0.16.515) is working as normal.

**Comment by DarkPsionix** [comment]
Sorry guys, I confirm that **all is working properly**. My Fault.

For testing purpose, I've mount my own Jackett/Definition in the docker image as mention by @garfield69.

@ilike2burnthing I can confirmed that your work on that release was perfect as usual.

Sorry once again for the time spent on this issue.
Thanks to the whole team for the work done on jackett 

```
     ██  █████   ██████ ██   ██ ███████ ████████     
     ██ ██   ██ ██      ██  ██  ██         ██        
     ██ ███████ ██      █████   █████      ██        
██   ██ ██   ██ ██      ██  ██  ██         ██        
 █████  ██   ██  ██████ ██   ██ ███████    ██        
                                                     
                                                     
██ ███████                                           
██ ██                                                
██ ███████                                           
██      ██                                           
██ ███████                                           
                                                     
                                                     
 ██████  ██████  ███████  █████  ████████            
██       ██   ██ ██      ██   ██    ██               
██   ███ ██████  █████   ███████    ██               
██    ██ ██   ██ ██      ██   ██    ██               
 ██████  ██   ██ ███████ ██   ██    ██

**Comment by ilike2burnthing** [comment]
Oh sorry lol I meant my personal copy, I have absolutely nothing to do with LS.io 😛
