### ISSUE TITLE
IPTorrents not finding anything

### ISSUE THREAD

**Issue by sweco-secfha** [Jackett/Jackett#873]
When searching IPTorrents nothing is found.
No errors in log or anything.
It worked yesterday.

**Comment by SilverSix311** [comment]
Getting same behavior.

**Comment by kaso17** [comment]
They started redirecting back to.
Set the alternative URL to "https://iptorrents.com/" to fix it for now.

**Comment by sweco-secfha** [comment]
Perfect, worked for me.

**Comment by kaso17** [comment]
the default url has been changed to https://iptorrents.com/, this should be "fixed"
