### ISSUE TITLE
torrentbomb: error in empty search

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8730]
Empty search returns Cloudflare error.
Other searches are working fine.

**Comment by garfield69** [comment]
in response to https://torrent.vet/search.php?keyword=2020
torrentbomb is returning Jackett.Common.IndexerException: Exception (torrentbomb): Clearance failed after 10 attempt(s).

**Comment by ilike2burnthing** [comment]
Seems to be the only result this occurs for. Could we have triggered Cloudflare by the overuse of a single URL?

Can be bypassed by using - https://torrent.vet/search.php?keyword=%2B2020

In browser, adding a plus sign at any point in the keyword (except the end) still just searches for the keyword, e.g. `+2020` , `2+020` , `20+20` , and `202+0` all show the search results page for `2020`. `2020+` results in the same Cloudflare check.

This seems to work for many non-alphanumeric characters. Exceptions I've come across so far are `.` `@`  `£` `_` `¬` `¦` '>` and `-` which are included in the searched keyword (20>20 searches for 20>20), and `<` cutting off the searched keyword where it is entered (20<20 searches for 20).

**Comment by ngosang** [comment]
@garfield69 could you try the @ilike2burnthing search?

**Comment by garfield69** [comment]
Whats the point. If the addition of the plus is, as ilike2burnthing speculates, just a way of making the search url different from the default 2020 search, simply because the 2020 search url has been flagged as overused, then it will take no time at all to make the url variations with the plus flagged as overused as well, and then we are back to square one.
I'm for deleting this useless web site from our indexer list.

**Comment by ilike2burnthing** [comment]
Is there a way to randomise what search is used?

Either by switching the placement:
=%2B2020
=2%2B020
=20%2B20
=202%2B0

Or using any of the other working characters:
=%2B2020
=%2C2020
=%272020
=%212020
=%7C2020
=%5E2020
etc.

I agree that changing to another single link is just moving the same issue to next week/month/whatever, and if we can't spread the load, then the indexer is ultimately non-functional, and so should be removed.
