### ISSUE TITLE
HDME Open signup + IMDb ID search implementation

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8742]
@garfield69 @cadatoiva @ngosang HDME's signup is open right now, which is rare. It has no active maintainers:

http://hdme.eu/signup.php

@garfield69 Would you be able to implement the IMDb ID search (search in description) and check the category mapping, inclusion of dead torrents, download factor, etc? I'm guessing it has not been maintained in a while.

**Comment by RoloSoze** [comment]
@garfield69 Thank you. Per their browse page, Double Upload is currently on. I'm not sure if it can be implement in Jackett.

**Comment by ngosang** [comment]
@garfield69 could you add a message to increase torrents per page to 100? by default is 15

**Comment by garfield69** [comment]
Jackett 0.16.524

**Comment by garfield69** [comment]
@RoloSoze  Thanks.
