### ISSUE TITLE
[turkseed] Error: Login Giriş Kilitlendi! ( Login deneme hakkınızı da kullandınız ) (Config)

### ISSUE THREAD

**Issue by bingoxo** [Jackett/Jackett#8745]
Jackett Version 0.16.521.0
Debian

full logs : https://bin.privacytools.io/?0bd39da07e4b3a54#S0KPBzNqrPpSfPnD9CvYEiIp3m7T4FtDGlq8uD3MkCs=

and as i said before , it doesn't show any captcha image for me

**Comment by garfield69** [comment]
I am not fluent in Turkish, and Google does not do a good job translating.
But it looks to me like 
`Giriş Kilitlendi! ( Login deneme hakkınızı da kullandınız )`
which Google translates as 
`Login Locked! (You have also used your login right)`
 means that you have been locked out.
Additionally there is this
```
Sistemimize saldırmaya çalıştığınız tespit edildi, ayırca ip adresini banlandı!
https://turkseed.com/unbaniprequest.php Buraya tıklayaran IP Ban Kaldırma İsteği Formunu doldurabilirsiniz!
https://turkseed.com/contactus.php Buraya tıklayarak bizimle iletişime geçebilirsiniz!
```
which Google translates as 
```
It has been detected that you are trying to attack our system, and also the IP address has been banned!
You can fill out the IP Ban Removal Request Form by clicking https://turkseed.com/unbaniprequest.php here!
You can contact us by clicking https://turkseed.com/contactus.php here 
```

So use your browser to login to turkseed and follow the directions to release your account / IP address.
