### ISSUE TITLE
Incorrect Version Number displayed on Jackett Web UI

### ISSUE THREAD

**Issue by ChuckNozzle** [Jackett/Jackett#8746]
### Environment

**OS**: Ubuntu 18.04

**Jackett Version**: 0.16.524.0

### Description

After update from 0.16.521.0 to 0.16.524.0 using Jackett.Binaries.LinuxAMDx64.tar.gz, the version displayed on the Web UI is still showing as 0.16.521.0.

When update is launched, the log shows that 0.16.524.0 is installed.

### Screenshots

![image](https://user-images.githubusercontent.com/29411770/82727357-47da7180-9cea-11ea-8195-db8185b57949.png)
![image](https://user-images.githubusercontent.com/29411770/82727369-5b85d800-9cea-11ea-8680-bacf38c3e119.png)

**Comment by garfield69** [comment]
refresh the page.

**Comment by ChuckNozzle** [comment]
That is after refresh/reload of the page.

**Comment by garfield69** [comment]
Odd.
I suggest you 
- shutdown the Jackett service.
- Manually install using the https://github.com/Jackett/Jackett#install-as-service instructions
- And especially make sure you run the systemd install script to replace the launcher startup.
The current release is 0.16.526

**Comment by ChuckNozzle** [comment]
The issue was related to me being a cowboy when updating manually, as I was just extracting the data straight to the Jackett directory without stopping & starting the service.
After restarting the service, all is well.
The reason I update manually is that the auto update seems to break Jackett more often than not, so is that something I should post as a separate issue?

**Comment by garfield69** [comment]
If the auto update is dodgy on your ubuntu, then you are probably suffering from an old bug that was fixed a while ago, but which needs a one time manual intervention from yourself to fix.
- shutdown the service and
- access the folder with your jackett binaries, and run the systemd install script as described in https://github.com/Jackett/Jackett#install-as-service

this will replace the existing launch script with one that prevents the service and the updater from running at the same time, thus avoiding the lockout that prevents modules being updated causing those missing-module errors.
You can then access your dashboard and un-tick the **disable auto update** checkbox, followed by the **apply server settings** button, to enable auto updating again.

**Comment by ChuckNozzle** [comment]
Thanks for that. I did all of that and the first update went through with no issues today.
