### ISSUE TITLE
[eztv] Exception (eztv): Authentication failed because the remote party has closed the transport stream.: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by DrJon85** [Jackett/Jackett#8750]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:win10pro

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:0.16.521.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] vpn

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
various country vpns tried

### Logged Error Messages

 An error occurred while testing this indexer
Exception (eztv): Authentication failed because the remote party has closed the transport stream.: The SSL connection could not be established, see inner exception.
[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by DrJon85** [comment]
this is not duplicate, this one is filled in

**Comment by garfield69** [comment]
This is unlikely to be an issue with Jackett, but an issue with CA handshaking failing to  agree in a security protocol for https connection.
There are multiply possible reasons for such a failure.
But there is not enough info in what you have provided for an explanation.
You could try providing a full **enhanced** log, it may provide additional info.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
the most common reason is that the ISP your VPN is using is blocking your access.
Try any of the other site links in the config.
If they all fail, try switching to another VPN.
