### ISSUE TITLE
[divxtotal] Exception (divxtotal): Request to https://www.divxtotal.la/page/1/?s= failed (Error 522) - The tracker seems to be down.: Request to https://www.divxtotal.la/page/1/?s= failed (Error 522) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by DrJon85** [Jackett/Jackett#8751]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:win10pro

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] yes
various vpn countried tried

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

 An error occurred while testing this indexer
Exception (divxtotal): Request to https://www.divxtotal.la/page/1/?s= failed (Error 522) - The tracker seems to be down.: Request to https://www.divxtotal.la/page/1/?s= failed (Error 522) - The tracker seems to be down.

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/1293
