### ISSUE TITLE
Sites not working

### ISSUE THREAD

**Issue by PROBLEMCHYLD** [Jackett/Jackett#8754]
Badass Torrents
BTeye
ExtraTorrent.ag
Nitro
Pirateiro
PornLeech
TNTVillage
Torrent9
TorrentBomb
XFSUB

**Comment by garfield69** [comment]
Badass Torrents duplicate #8709
BTeye duplicate #7247
ExtraTorrent.ag duplicate #2478
Nitro duplicate #5949
Pirateiro pending PR #8431 
PornLeech duplicate #8676
TNTVillage duplicate #7926
Torrent9 change your site link to https://ww1.torrent9.is/
TorrentBomb duplicate #8730
XFSUB change your site link to http://share.xfapi.top:88/

this ticket adds no value.
We prefer to track each indexer problem separately do they can be tracked and resolves as they get fixed /  removed / whatever.
