### ISSUE TITLE
Xthor tracker : Add option "Replace VOSTFR with ENGLISH"

### ISSUE THREAD

**Issue by swacquie** [Jackett/Jackett#8759]
Hi,

Xthor tracker is a french tracker so the torrents with the tag VOSTFR, SUBFRENCH are audio ENGLISH + subtitle FRENCH.

like for YGG and Elite-Tracker, it would be nice to be able to replace (VOSTFR|SUBFRENCH) with ENGLISH.

A similar Issue was open for Elite-tracker, #6855 , and was handled with commit 6e9c3126791edb7ce58b4accbf923bb4fe3cfc4e and ebc687a467c2e637b3c2a2dffc099b73cfd510db

**Comment by Tawagot0** [comment]
Done, just wait the MR #8797 
If @ngosang or @garfield69 can link the PR for this issue, thanks!

**Comment by ngosang** [comment]
Closed by #8797
In the future you can add "resolve #xxxx" in the PR to auto close

**Comment by garfield69** [comment]
Jackett 0.16.566
