### ISSUE TITLE
[lechaudron] Login failed: Selector

### ISSUE THREAD

**Issue by neo62248** [Jackett/Jackett#8760]
### Environment

**OS**: Win 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.14.485-10

**Are you using a proxy or VPN?** [yes/no] NO

### Description

Hello, 

when i use Jackett to configure my provider LECHAUDRON, i've got this error : 'Login failed: Selector "a[href$="/TTV3/Deconnexion"]" didn't match'.

### Screenshots

![jackett](https://user-images.githubusercontent.com/5675981/82764315-11961280-9e0e-11ea-9b70-0b96f3f667c2.png)

**Comment by garfield69** [comment]
this is likely due to your cookie not being valid.
follow https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work and see if that helps you fetch the correct cookie string.

**Comment by neo62248** [comment]
Precisely, with my version of Chrome, I cannot follow these instructions (I have Chrome in the latest version available). I don't have the "Headers" tab.

**Comment by garfield69** [comment]
you are on windows 10 running the standard Chrome browser?
I am on win10 home, using Chrome 83.0.4103.61
Which version of Chrome are you on?

**Comment by neo62248** [comment]
Version 81.0.4044.138.
I do not understand the explanations on the page on how to recover cookies. The instructions don't match what I see.

**Comment by garfield69** [comment]
are you stuck between steps 5 and 6?
click on the name **Bienvenue**
![image](https://user-images.githubusercontent.com/6933240/82765155-5babe200-9e68-11ea-8e4d-20d3667d84f2.png)
see the header tab?
if not, Printscreen and paste here so I can see what you are looking at.

**Comment by neo62248** [comment]
OK. There were two things: the wrong URL (I had to indicate https://lechaudron.nl), and I finally found the Headers tab, which is actually a sub-tab,  as you told me.
I will have to change my glasses one day ;)
Now, it works. Thank you :)
