### ISSUE TITLE
[REQ] ONLYscene

### ISSUE THREAD

**Issue by jns-fr** [Jackett/Jackett#8763]
ONLYScene.org is a new general tracker for French releases (Movies, TV, Games, Anime)
Address => https://www.onlyscene.org/
Type =>Private
Registration => https://www.onlyscene.org/register/null

**Comment by garfield69** [comment]
https://www.onlyscene.org/ returning ERR_CONNECTION_REFUSED
and via vpn ERR_CONNECTION_RESET

just me, or is the site down, broken or moved to a new domain?

**Comment by jns-fr** [comment]
Tracker is down

**Comment by garfield69** [comment]
Thanks.
Well keep this open for about 30 days, and then, if its still offline we will remove the indexer.
