### ISSUE TITLE
Request for Learnflakes Invite

### ISSUE THREAD

**Issue by koushik-sen-vst-au4** [Jackett/Jackett#8765]
Need a learnflakes invite. Hoping somebody would invite me. I want to help this tracker.

**Comment by koushik-sen-vst-au4** [comment]
Please somebody provide me a invite on learnflakes tracker.
It will be a great help. 
Comment me here,if somebody can invite me..

**Comment by RoloSoze** [comment]
You're not here to help. You're here to ask for invites by spamming this repository, despite being asked not to do so. You've been reported to GitHub and to the admins of this repository.
