### ISSUE TITLE
myanonamouse and  LazyLibrarian Please check the capabilities (t=caps) 

### ISSUE THREAD

**Issue by Viper911** [Jackett/Jackett#8769]
LL reports back:

"myanonamouse does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported."

Went to Jackett and test passed.  Did manual search of same thing and results comeback, but when LL points to Jackett to do the same thing, it reports the t=caps error

**Comment by garfield69** [comment]
what is LL?

**Comment by Viper911** [comment]
Sorry. Lazy Librarian
________________________________

**Comment by garfield69** [comment]
can you provide a link to the support site?

**Comment by garfield69** [comment]
So have you got any other Jackett indexers working with LL?

The Jackett MyAnonamouse indexer supports the following Torznab categories
```
3030 Audio/Audiobook
8010 Books/Ebook
8020 Books/Comics
8030 Books/Magazines
8040 Books/Technical
```
and supports only the `t=search` search mode.

so if LL has a way of specifying which cats and which search mode to use, then those are the ones supported.

**Comment by Viper911** [comment]
I did find some backend setting that let me set these and seems to be getting later in the process now.  Now I am just getting a LL error.

I am guessing this is an LL issue and have submitted it to them unless something jumps out at you.  It looks like Jackett replied back with Seeders=3 so seems to be ok, not sure why LL is erroring out.

Unhandled exception in search_book: Traceback (most recent call last): File "C:\Users\htpc\lazylibrarian\LazyLibrarian\lazylibrarian\searchbook.py", line 333, in search_book resultlist, nprov = IterateOverNewzNabSites(book, 'shortgeneral' + searchtype) File "C:\Users\htpc\lazylibrarian\LazyLibrarian\lazylibrarian\providers.py", line 533, in IterateOverNewzNabSites resultslist += NewzNabPlus(book, provider, searchType, "nzb") File "C:\Users\htpc\lazylibrarian\LazyLibrarian\lazylibrarian\providers.py", line 1333, in NewzNabPlus if check_int(thisnzb['seeders'], 0) >= check_int(provider['SEEDERS'], 0): KeyError: 'SEEDERS'

**Comment by garfield69** [comment]
closing as stale.
