### ISSUE TITLE
secretcinema: unrelated results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8779]
"query": "Harry Potter"

**Comment by RoloSoze** [comment]
@ngosang andmatch?

**Comment by ngosang** [comment]
I want to investigate a bit more because I'm getting different results in Jackett than in the web page.

**Comment by RoloSoze** [comment]
In some other trackers where everything else seemed fine - all categories were mapped correctly, dead torrents were returned in Jackett, etc - I found that surrounding the search string with quotation marks when searching the website ended up solving any search-related issues I had. I can't test it myself in SC but give it a shot?
