### ISSUE TITLE
[HDDolby] Login failed. Need to input captcha for login

### ISSUE THREAD

**Issue by InnerPeaceKR** [Jackett/Jackett#8783]
**Jackett Version**: 0.16.548

I got chinese error message when I try to login.
登录 / 注册 失败 图片代码无效！不要返回，图片代码已被清除！点击这里获取新的图片代码。
Google translator: Login / Registration failed Picture code is invalid! Don't go back, the picture code has been cleared! Click here for the new image code.

**Comment by garfield69** [comment]
jackett 0.16.551
