### ISSUE TITLE
[privatehd] Login Failed: Invalid username, password or PID (Config)

### ISSUE THREAD

**Issue by bbalz** [Jackett/Jackett#8786]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]: N/A

**.Net Version**:  N/A

**Jackett Version**: 0.16.551.0

**Last Working Jackett Version**:  Uncertain

**Are you using a proxy or VPN?** [yes/no]:  No

### Description

Trying to test the indexer and it fails.

The username/password is not incorrect.  I have verified this many times.  There is no 2FA currently setup which caused issues in the past.  The proper settings are selected for the RSS feed as well as the PID inclusion in the setup. 

This worked maybe last week without a hitch and now it continually fails and cannot be configured. 

### Logged Error Messages

> System.Exception: Login Failed: Invalid username, password or PID
>    at Jackett.Common.Indexers.Abstract.AvistazTracker.RenewalTokenAsync() in d:\a\1\s\src\Jackett.Common\Indexers\Abstract\AvistazTracker.cs:line 91
>    at Jackett.Common.Indexers.Abstract.AvistazTracker.ApplyConfiguration(JToken configJson) in d:\a\1\s\src\Jackett.Common\Indexers\Abstract\AvistazTracker.cs:line 70
>    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by RoloSoze** [comment]
I'm assuming you're able to login just fine via the website and have the ability to download torrents? Can you check whether there is a leading or trailing space in the PID you entered in Jackett?

**Comment by bbalz** [comment]
> I'm assuming you're able to login just fine via the website and have the ability to download torrents? Can you check whether there is a leading or trailing space in the PID you entered in Jackett?

Yes, I can log in fine to the website and download a torrent.  I verified there aren't any trailing or leading spaces in the PID when entering it into Jackett.

**Comment by bbalz** [comment]
I've talked with someone who has the same setup and no problems so it must be on my end.  You can close this.  I'll dig around to see what is going on.

**Comment by RoloSoze** [comment]
@bbalz I also have the same setup as you (Windows 10 Pro 64-bit, latest Jackett version), but it's working fine for me. 

Do let us know if you figure out what's wrong. Try deleting and reconfiguring PHD's indexer, including deleting the 2 privatehd files from your hard drive `C:\ProgramData\Jackett\Indexers`. 

Also try reinstalling Jackett using the .exe file `https://github.com/Jackett/Jackett/releases/download/v0.16.551/Jackett.Installer.Windows.exe`

These simple steps have solved a lot of my issues in the past.

**Comment by bbalz** [comment]
I ended up actually force stopping Jackett, since it didn't when I tried to stop it via the icon in the tray. 

Once I restarted it up and removed PrivateHD and tried to re-add PrivateHD it ended up coming back up with cleared credentials.  Previously when I did this before force closing the service, it would come up with my previous entered credentials.  

After restarting the service and re-adding my credentials it passed through without a problem. 

Not sure what caused it to stop working, nothing had changed login wise for me but it's resolved and working great now. 

I should've ensured it closed versus just trusting the 'stop background service' click in the tray icon.

**Comment by RoloSoze** [comment]
Yeah that's why I suggested reinstalling Jackett, since this would ensure that the service is stopped and that no instance of Jackett is running in the background, otherwise the installation process will not proceed. When I don't need to reinstall Jackett, force-stopping every instance of it from the Task Manager also helps solve some issues. Glad you managed to resolve this.
