### ISSUE TITLE
Couchpotato download links to Jackett often don't work

### ISSUE THREAD

**Issue by plumber-craic** [Jackett/Jackett#8788]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: ubuntu 20 LTS

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] mono

**.Net Version**:

**Jackett Version**: 0.16.551.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
1. Add a public tracker such as 1337x or torrentz2 to jackett with default settings
2. Add these trackers to couchpotato
3. Click on a movie in CP, then choose the Download button on one of the jackett releases
4. Mostly, you get an error like this (most releases for most movies for both trackers)
```
05-27 18:33:11 ERROR ESC[31m[chpotato.core.plugins.log] API log: {'file': u'http://HOST/static/scripts/combined.plugins.min.js?1590089339', 'message': u'firefox 76: \nTypeError: json.items is undefined', 'line': u'1288', 'page': u'http://HOST/home/', '_request': <couchpotato.api.ApiHandler object at 0x7f98ea63b3d0>}ESC[0m
05-27 18:33:14 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get http://192.168.1.2:9117/dl/1337x/?jackett_apikey=xxx&path=Q2ZESjhPcG4tbDhEaXI5Tm1obC1jNEUydlVSNTBaUjVhaFlyMTRyQUQxem1Fc1NET3JjcU1BSzVnSURPODJEMGowSTlTelJqV3E1ZmN3UVVOMV9HZGQ3UTljT2V3SnBnS1FhTWZDMTlhZDkxS1NqdGNGcFc5V2MtWFQ0MkRrR3J6NlE5TU4zaEVJWG50TlA4SXE4ekNOU1RaVkZRQ09ER2J3YmROdmhRSG44bmgxTHlIVl9TNjhzRTBXOWx3V1BPZUxwWnM1UG5hTFNpcl94eXVxNmpsZHRZUUk4&file=Uncut+Gems+2019+720p+BluRay+x264+YOL0W, data: []ESC[0m
05-27 18:33:14 ERROR ESC[31m[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last):
  File "/opt/couchpotato/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 207, in download
    return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False)
  File "/opt/couchpotato/CouchPotatoServer/couchpotato/core/plugins/base.py", line 221, in urlopen
    response = r.request(method, url, **kwargs)
  File "/opt/couchpotato/CouchPotatoServer/libs/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/couchpotato/CouchPotatoServer/libs/requests/sessions.py", line 598, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/opt/couchpotato/CouchPotatoServer/libs/requests/sessions.py", line 194, in resolve_redirects
    **adapter_kwargs
  File "/opt/couchpotato/CouchPotatoServer/libs/requests/sessions.py", line 571, in send
    adapter = self.get_adapter(url=request.url)
  File "/opt/couchpotato/CouchPotatoServer/libs/requests/sessions.py", line 645, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:5413D5B9E087F2614228EEFB44884277CA13E15E&dn=Uncut.Gems.2019.720p.BluRay.x264-YOL0W&tr=http://tracker.trackerfix.com:80/announce&tr=udp://9.rarbg.me:2730/announce&tr=udp://9.rarbg.to:2710/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce'
```
5. Changing from magnet to one of the other URL fails with a different error
```
05-27 18:30:58 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get http://192.168.1.2:9117/dl/1337x/?jackett_apikey=xxx&path=Q2ZESjhPcG4tbDhEaXI5Tm1obC1jNEUydlVSNTBaUjVhaFlyMT
RyQUQxem1Fc1NET3JjcU1BSzVnSURPODJEMGowSTlTelJqV3E1ZmN3UVVOMV9HZGQ3UTljT2V3SnBnS1FhTWZDMTlhZDkxS1NqdGNGcFc5V2MtWFQ0MkRrR3J6NlE5TU4zaEVJWG50TlA4SXE4ekNOU1RaVkZRQ09ER2J3YmROdmhRSG44bmgxTHlIVl9TNjhzRTBXOWx3V1BPZUxwW
nM1UG5hTFNpcl94eXVxNmpsZHRZUUk4&file=Uncut+Gems+2019+720p+BluRay+x264+YOL0W, data: []ESC[0m
05-27 18:30:58 ERROR ESC[31m[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last):
  File "/opt/couchpotato/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 207, in download
    return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False)
  File "/opt/couchpotato/CouchPotatoServer/couchpotato/core/plugins/base.py", line 227, in urlopen
    response.raise_for_status()
  File "/opt/couchpotato/CouchPotatoServer/libs/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: http://192.168.1.2:9117/dl/1337x/?jackett_apikey=xxx&path=Q2ZESjhPcG4tbDhEaXI5Tm1obC1jNEUydlVSNTBaUjVhaFlyMTRyQUQxem1Fc1NET3JjcU1BS
zVnSURPODJEMGowSTlTelJqV3E1ZmN3UVVOMV9HZGQ3UTljT2V3SnBnS1FhTWZDMTlhZDkxS1NqdGNGcFc5V2MtWFQ0MkRrR3J6NlE5TU4zaEVJWG50TlA4SXE4ekNOU1RaVkZRQ09ER2J3YmROdmhRSG44bmgxTHlIVl9TNjhzRTBXOWx3V1BPZUxwWnM1UG5hTFNpcl94eXVxNmps
ZHRZUUk4&file=Uncut+Gems+2019+720p+BluRay+x264+YOL0W
```
6. Workaround by using itorrent.org links
### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
see above
[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ngosang** [comment]
This can't be fixed by Jackett. Please, open a new issue in CouchPotato. This is the fix done by qBittorrent. https://github.com/qbittorrent/qBittorrent/issues/11877

@RuudBurger Could you help?

Related #7843 #5267 #5875

**Comment by nydave69** [comment]
RuudBurger hasn't responded to CP issues in a while..
He remove the issue tracker and most of the other links.

I hope something happens with CP, was a nice software app when it was working correctly.

**Comment by RuudBurger** [comment]
You are correct, I don't do much anymore.
But what can I do to get this fixed? I merged some PRs related to qBittorrent, so if there are more that solve the issue, please let me know.

**Comment by ngosang** [comment]
@RuudBurger 
1. Jackett returns an HTTP download link like this for each torrent `http://127.0.0.1:9117/dl/1337x/?jackett_apikey=ygm5k29tomyy165gio7iouhqx9k4&path=Q2ZEUyS0lmQjcxQTlmYVJ2eENWWVR1WnhUY2FPZw&file=Dope+(2015)+%5BQxR%5D`
2. CP tries to download that URL
3. In some torrent sites, the .torrent file is not available and Jacket returns a redirect to a magnet link.
4. `requests` is automatically following the redirection and it can't handle the magnet protocol. Take a look at the traces provided by the OP.

There are different possible solutions.
1. Disable redirects https://requests.readthedocs.io/en/master/user/quickstart/#redirection-and-history and implement some logic to detect if the redirect is a magnet link. Take a look at SickChill fix => https://github.com/SickChill/SickChill/commit/82b895394dbe27f6b6dbd474493b231e77e18f3b
2. Implement a network adapter in Python to handle the magnet protocol (just a dummy adapter that return the URL in the body or something like that). I never did one => https://www.google.com/search?q=python+No+connection+adapters+were+found+for

**Comment by ilike2burnthing** [comment]
Looks like the PR for this (https://github.com/CouchPotato/CouchPotatoServer/pull/7325) was closed without review ~2 months ago, along with all other open PRs at the time. However the fix can be manually applied and numerous reports confirm it is working.
