### ISSUE TITLE
[New Tracker REQ] HDClub (HDC)

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#879]
**Indexer Name**
HDClub (HDC)

**Type**
Movies, TV, Audio - All in HD

**Indexer URL**
http://hdclub.org/

**Indexer Language**
Russian (Also available in Ukrainian & English)

**Invite**
I do not have one at the moment. Maybe someone can help out with an invite?

**Comment by VadVoci** [comment]
HDClub Invite sent!

**Comment by kaso17** [comment]
got it

**Comment by kaso17** [comment]
added with a0aa77519b16f6bf71511e90b08fa7fa9bc9182f

**Comment by Mavrag** [comment]
Hey, when i search with Russian letters i don't get any results back in jackett
