### ISSUE TITLE
MejorTorrent and Divxtotal unavailable

### ISSUE THREAD

**Issue by northernpowerhouse** [Jackett/Jackett#8814]
### Environment

**OS**: Docker (latest stable)
Info | File /etc/issue: Ubuntu 18.04.4 LTS \n \l
-- | --
Info | Jackett variant: CoreLinuxAmdx64
Info | OS version: Unix 5.5.0.0 (64bit OS) (64bit process)
Info | Environment version: 3.1.4 (/app/Jackett/)
Info | Starting Jackett v0.16.571.0

**Are you using a proxy or VPN?** [yes - issue present with or without]

### Description
Mejortorrent and DivX Total not successfully configured. 

Worked until a couple of days ago, today they both sent errors to my client (sonarr) and would not test successfully, the configuration screen just showed the title text of the websites. Removed both indexers and attempted to re-add to jackett, now I get " An error occurred while configuring this indexer"

### Logged Error Messages

See attached

[Untitled spreadsheet.xlsx](https://github.com/Jackett/Jackett/files/4705650/Untitled.spreadsheet.xlsx)

**Comment by ngosang** [comment]
Both are working for me. Check you can access from web browser.
* https://www.divxtotal.la/
* https://www.mejortorrentt.net/

**Comment by northernpowerhouse** [comment]
I can access both sites from a browser with and without the same proxy.

Is there anything else I can provide besides the log I've already attached?

**Comment by ilike2burnthing** [comment]
Are you using the internal proxy in Jackett, or an external VPN?

Provide [enhanced logs](https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket) (not in a spreadsheet) testing both sites with and without the proxy/VPN.

If you're using the internal proxy, these sites may also fail - https://github.com/Jackett/Jackett/issues/7325#issuecomment-603887196 (no need to post enhanced logs, just test a few, with and without proxy, and let me know)
