### ISSUE TITLE
YingK

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8823]
**Indexer Name**
YingK

**Indexer URL**
https://yingk.com/

**Interface Language**
Chinese (No English interface)

**Description**
YingK is a CHINESE Private Torrent Tracker for HD Movies, TV, General

**Type**
YAML (NexusPHP)

**Access**
Private

**Notes**
- Supports IMDb ID Search
- Please ensure the inclusion of dead torrents for all categories
- Like Keep Friends https://github.com/Jackett/Jackett/issues/8299#issuecomment-630327591, this tracker shows the English name of most (not all) releases in the subtitle/small description section. I think it'll need this as well https://github.com/Jackett/Jackett/issues/8299#issuecomment-630407234

**Comment by garfield69** [comment]
Jackett 0.16.589

**Comment by ilike2burnthing** [comment]
https://yingk.com/ - ERR_NAME_NOT_RESOLVED
