### ISSUE TITLE
[Anthelion] Remuxes not recognized

### ISSUE THREAD

**Issue by just-an-alt** [Jackett/Jackett#8825]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Armbian Buster

**Jackett Version**: 0.16.585.0 (Linuxserver.io docker image)

**Are you using a proxy or VPN?** yes

### Description
When searching for a movie on Anthelion, the "Remux" part doesnt get recognized, see screenshots for what I mean.

### Screenshots

Jackett: https://i.imgur.com/NuaKNCR.png
Anthelion: https://i.imgur.com/4Ubz7t8.png

**Comment by just-an-alt** [comment]
Sorry, noticed its a dupe of #7923

**Comment by RoloSoze** [comment]
@just-an-alt Do you have an invite that you can share with @ngosang by any chance?

**Comment by just-an-alt** [comment]
Sadly not, but I'd be happy to help by testing stuff.

**Comment by garfield69** [comment]
@ngosang  if you want to work on this ticket let me know.
