### ISSUE TITLE
[BakaBT] Movies and OVAs marked as "Season 1"

### ISSUE THREAD

**Issue by just-an-alt** [Jackett/Jackett#8827]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**Jackett Version**: Linuxserver's Jackett image (Version 0.16.585.0)

### Description
All searches on BakaBT get marked as Season 1, if no Season info is available.
This leads to movies and OVAs being marked as Season 1, breaking Sonarr and Radarr in the process.

Furthermore, series like "Himouto! Umaru-chan R" get the Season 1 appended, which is wrong, as it's the second season of "Himouto! Umaru-chan"

Therefore I suggest completely dropping the "Season 1" in the name, keeping the original name.
Multi-season Anime usually already have "Season 1" in their name, or at least their sequels are numbered: https://i.imgur.com/oohtxqG.png

### Screenshots

BakaBT 1: https://i.imgur.com/EFHm9v8.png
BakaBT 2: https://i.imgur.com/nzhAz3C.png
Jackett 1: https://i.imgur.com/ijaUiAC.png
Jackett 2: https://i.imgur.com/Nos0AlP.png

**Comment by just-an-alt** [comment]
Another reason the "Season 1" should be removed:
![](https://i.imgur.com/AqSuKu1.png)
None of those series are actually the first Season.

**Comment by jellofishi** [comment]
@just-an-alt can you give me a list of correct/incorrect examples for:
* series with no seasons
* series which are considered a second season of a different show but have a different name
* series with actual seasons

I can test and see if it make sense to remove the "Season 1" which is automatically added to each title.

**Comment by just-an-alt** [comment]
1. "Spirited Away" is a movie, and the title in BakaBT is "Sen to Chihiro no Kamikakushi | Spirited Away (BD 1080p) [Coalgirls]"
Jackett lists it as two torrents (#8828) "Sen to Chihiro no Kamikakushi Season 1 (BD 1080p) [Coalgirls]" and "Spirited Away Season 1 (BD 1080p) [Coalgirls]"

2. "JoJo no Kimyou na Bouken" is a series with multiple Seasons, which each have different names.
BakaBT lists the seasons like this: "JoJo no Kimyou na Bouken", which is Season 1, "JoJo no Kimyou na Bouken: Stardust Crusaders", which is Season 2, and so on. Note the absence of "Season 1" and "Season 2" in the titles.
Jackett lists those releases as "JoJo no Kimyou na Bouken Season 1" and "JoJo no Kimyou na Bouken: Stardust Crusaders Season 1"

3. "Gintama" is a series with multiple seasons, which are listed in BakaBT as "Gintama Season 1", "Gintama Season 2" and so on. Jackett correctly parses this, and lists them exactly the same.

On BakaBT, series with multiple seasons actually have "Season X" in their name, as seen with Gintama. If a BakaBT release does not have "Season X" in it's title, Jackett should not show "Season 1" by default.
There are some series with only one season, which do not have "Season 1" in their title on BakaBT. I don't know how Sonarr would handle those, although I think it should work correctly. An example of a series with only one season is "Genocyber".

**Comment by just-an-alt** [comment]
Another thing: _Manga are labeled as Season 1, too_

**Comment by RoloSoze** [comment]
@seeyabye Since you're a member of BakaBT, do you think you can work on this issue?

**Comment by garfield69** [comment]
Jackett 0.16.1549
