### ISSUE TITLE
[Bug] Links on HDClub (HDC) search results do not direct to HDC's website

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#883]
They all direct to Jackett's Dashboard instead.

**Comment by kaso17** [comment]
Fixed with 357be7dda9c5f58d587b71cb3ef658a412b3d616

**Comment by armani316** [comment]
I think there's a different bug now with v0.7.826 - Searching HDClub returns no results at all. @kaso17

**Comment by armani316** [comment]
Disregard the above comment. Deleting & reconfiguring the indexer solved the issue.
