### ISSUE TITLE
[thefallingangels] Exception (thefallingangels): Login failed

### ISSUE THREAD

**Issue by GekoCH** [Jackett/Jackett#8830]
This site has probably changed the login form so we can't login anymore...

Here the error:
Exception (thefallingangels): Login failed: No form found on https://tfa.tf/login.php using form selector form[action="/login.php"]: Parse error

**Comment by garfield69** [comment]
Jackett 0.16.598

**Comment by GekoCH** [comment]
wow what a service! Works great thx!
