### ISSUE TITLE
IPTorrent adding Indexer Error

### ISSUE THREAD

**Issue by Ryanevans94** [Jackett/Jackett#884]
When I am trying to add IPTorrents as an Indexer It comes up with the error " Error: An error occurred while sending the request." I am running Jackett Version 0.7.825.0

**Comment by kaso17** [comment]
Can you access https://iptorrents.com/ in your browser or is it blocked by your ISP?
Please enable Enhanced logging and post a log

**Comment by kaso17** [comment]
I assume this was a ISP blocking issue
