### ISSUE TITLE
[mteamtp] Exception (mteamtp): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /home/thoradia/Projects/thoradia/coreelec-9.2/build.CoreELEC-Amlogic.arm-9.2-devel/mono-6.4.0.198/external/boringssl/ssl/handshake_client.c:1132: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by potatoxbe** [Jackett/Jackett#8845]
using Jackett 0.16.598.0 . Got this error after updating to the newest version 2 days ago. Worked before with a version from at least 2 weeks back.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#exception--ssl-errorssl-routinesopenssl_internalcertificate_verify_failed
