### ISSUE TITLE
[New Tracker REQ] 7tor.org

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#885]
Indexer Name
7tor

Type
General

Indexer URL
http://7tor.org/

Indexer Language
Russian

Invite
Registration is now open:
http://7tor.org/ucp.php?mode=register

**Comment by kaso17** [comment]
registered

**Comment by kaso17** [comment]
Basic support was added with 0a8675ea7c515b68d2201b3c2784847b0b8b3ab0
Category mapping is missing

**Comment by armani316** [comment]
@kaso17 No problem! Take your time with the category mapping. Thanks a lot!

**Comment by kaso17** [comment]
basic category mapping added with 74d0e022ae76e5c1bee56ea4b089161ad16fe5f9

**Comment by RoloSoze** [comment]
@kaso17 Is 7tor working for you? It seems like they switched from https to http but when I try to use the latter, I get redirected!

**Comment by RoloSoze** [comment]
@kaso17 UPDATE: The issue has now been resolved. Ignore my above comment.

**Comment by garfield69** [comment]
https://7tor.org returning (Error Bad Gateway) - The tracker seems to be down

**Comment by garfield69** [comment]
7tor is closed for now.
![image](https://user-images.githubusercontent.com/6933240/63904562-99104a00-ca65-11e9-8283-de6339d16017.png)
if/when they get their new server up we will add it back.
