### ISSUE TITLE
It is required to correct the description of adding a Rustorka tracker

### ISSUE THREAD

**Issue by Korb** [Jackett/Jackett#8856]
> Click on the first entry in the Left panel under the Name column

The site’s interface is Russian-language, without the ability to switch it to English. On which page do you need to search for the "left panel" under the "name column"? It is "Мини профиль"? "Последние новости"? "Горячие темы"? "Важные объявления"?..

> Select the Headers tab on the Right panel

Firefox 78.0b2 (64-bit) - only
> All HTML CSS JS XHR Fonts Images Media WS Other

![2020-06-04_14-35-59](https://user-images.githubusercontent.com/3509797/83752273-eebaf800-a670-11ea-9f08-a81795941a85.png)

### Environment
Microsoft Windows [Version 10.0.18363.836]
.Net Runtime: not installed
Jackett 0.16.609.0
Are you using a proxy or VPN: no

**Comment by garfield69** [comment]
Yes, the instructions were aimed for the chrome browser. Now amended to include firefox.
