### ISSUE TITLE
[New Tracker REQ] CHDBits

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#886]
Indexer Name
CHDBits

Type
Movies, TV & Audio

Indexer URL
https://chdbits.co/

Indexer Language
Mandarin

Invite
I don't have one at the moment. Maybe someone can help out with an invite?

**Comment by VadVoci** [comment]
If you have an account there, you have two invitations.
Spend one for Jackett, as I did with HDClub and others

**Comment by armani316** [comment]
@VadVoci You're right! I just checked and it turns out I had an invite! I'm still getting used to the interface since it's all in Mandarin, so I didn't notice the invites I had! Thanks for pointing it out!

Invite sent!

**Comment by kaso17** [comment]
got it, thank you

**Comment by kaso17** [comment]
fixed with 65c1aed2513afc259408e0964078b40b6b11a100
