### ISSUE TITLE
[ourbits] Clearance failed after 10 attempt(s). (Config)

### ISSUE THREAD

**Issue by Curtis-L** [Jackett/Jackett#8881]
maybe switch to cookie method so we won't face Cloudflare challenge again.

**Comment by RoloSoze** [comment]
@ngosang Is it possible to do the cookie method for OurBits like @Curtis-L suggested?

**Comment by RoloSoze** [comment]
@garfield69 I'm mentioning you here since OurBits indexer is written in YAML.

**Comment by garfield69** [comment]
I don't have an account so I cannot test this to conclusion. 
@RoloSoze  test PR #8891 to check if the cookie method will work to bypass the cloudflare for this site.

**Comment by RoloSoze** [comment]
@garfield69 YES! Problem solved, thank you! 
@Curtis-L Thank you for suggesting the idea! This fix should be available in the next update.

**Comment by garfield69** [comment]
Jackett 0.16.640
