### ISSUE TITLE
Girotorrent - very strange search

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#8882]
Hi to all, Jackett .net core under debian 10 machine

I just found a strange behavior during a manual search on girotorrent. For example I search harrow
and I can't see any results, but if I search harrow inside giro, I can see 12 results.
So I enabled the Enhanced log and I search again, this's the log
[log.txt](https://github.com/Jackett/Jackett/files/4740016/log.txt)
If I open the log I see that the request url is:
`http://girotorrent.org/index.php?search=harrow&category=&page=torrents&active=0&options=0&order=3&by=1&pages=1`
So I copy paste this and girotorrent show me nothing, but if I hit the search button in the same "empty" page I can see the 12 results. The url now is `http://girotorrent.org/index.php?page=torrents&search=harrow&category=0&options=0&active=0` for me is the same

What can be the problem?

**Comment by garfield69** [comment]
the problem is that the site's server does not like getting 5 requests to fetch pages 1 to 5.
I am going to drop the multi page fetching.

**Comment by Jorman** [comment]
Never noticed.
Do you think this happens from very beginning? I don't remember this problem.
On girotorrent, like others trackers, I can set the torrent for page, now is set to 15, I try to set it to 100 like some other trackers, maybe this modify the result page too

**Comment by garfield69** [comment]
I don't recall being able to change the torrents per page previously, so this may be a recent change.
I notice that my profile changes on the site does not take effect until I logout.
I still got 15 rows even after setting it to 50, but after logging out, then I started getting 50.

**Comment by Jorman** [comment]
I tried without logout, simply close and re-open the windows. 100 in my case and now 100 record are loaded.
I tried on jackett side, making a simple empty search, and I got 500 results, 100 for 5 pages.
Why fetching 5 pages with empty search works, but don't if I do a real search?

**Comment by garfield69** [comment]
I don't know, its an issue with the site.
In the next release we will only use the one fetch and the config will remind users to update their torrents per page. 
end of problem.

**Comment by Jorman** [comment]
Ok, perfect! Thanks!

**Comment by garfield69** [comment]
Jackett 0.16.640
