### ISSUE TITLE
[Feature request / Idea] Create Jackett Groups

### ISSUE THREAD

**Issue by Malakai-DB** [Jackett/Jackett#8884]
Hello,

First of all, thank you for this wonderful project that makes life easier for lots of people.
It is my first feature request opened on Github (I just created my account) so if I am not doing things as I should, please let me know so I can correct them.

I have an idea that could help Jackett users in maintaining their infrastructure. I don't know if it is doable as I am not a developer (I count on you to tell me if it is not).

Because a (fairly simplified) example is better than a long explanation :

I use a single instance of Jackett for multiple "clients" (Couchpotato, Sonarr, Radarr, Headphones, etc). Some are for me and some for a friend. For the example, lets say that I prefer English and French movies and my friend likes English and Spanish movies.

In Jackett I will have the following : 
- EnglishTracker1
- FrenchTracker1
- SpanishTracker1

In my Couchpotato I will have : 
- EnglishTracker1
- FrenchTracker1

In my friends Couchpotato there will be : 
- EnglishTracker1
- SpanishTracker1

Lets say that the EnglishTracker1 is not supported by Jackett anymore and a new FrenchTacker2 becomes supported. In this case, I have to delete from both Couchpotatoes the EnglishTracker1 (and eventually configure an EnglishTracker2 after adding it in Jackett), and add the FrenchTacker2 to my Couchpotato. The more tracker you add/delete and the more "clients" you have, the more complicated and time consuming it gets.

The idea is to add GROUPS in Jackett. In this way I could have a group for myself and a group for my friend. Only this 2 groups would be configured in my "clients" and his "clients". Each time I have to add/delete a tracker, I could do it on my/his group and don't have to touch to "clients" configuration (all the maintenance is done in Jackett).
So "clients" could call something like _http://mydomain/api/v2.0/indexers/mygroup/results/potato/_ and Jackett transforms this request in multiple requests to the different trackers that are part of that group.
I think this idea (if it could be implemented without too much hassle) would help lots of people in maintaining their infrastructure without too much effort.

If this is not doable (from a code point of view), maybe another solution to ease configuration and changes could be found...

Anyway, thank you for creating and maintaining Jackett.

**Comment by ngosang** [comment]
Related #4787 #2185

**Comment by ilike2burnthing** [comment]
[v0.18.7](https://github.com/Jackett/Jackett/releases/tag/v0.18.7) - tags can now be added to indexers to group them together however you want.

You can then filter indexers for searches by these tags. Indexers can also be filtered by type (public, semi-private, and private). The API can also filter by language.

See more info here - https://github.com/Jackett/Jackett#filter-indexers
