### ISSUE TITLE
Incorrectly Encoded Magnet Links for Some Indexers (ex. 1337x)

### ISSUE THREAD

**Issue by Qstick** [Jackett/Jackett#8889]
### Environment

![image](https://user-images.githubusercontent.com/376117/83953197-4346aa80-a80c-11ea-811b-65f496107490.png)

**Are you using a proxy or VPN?** No

### Description

Magnet links for certain indexers are not correctly URI Escaped. This results in sending invalid magnet link to -arr and causing a format error below

```
System.FormatException: A field-value pair of the magnet link contain more than one equal'.
  at MonoTorrent.MagnetLink.ParseMagnetLink (System.String url) [0x00071] in <ae312fb8a3344a4cbaa8e26ab9c29717>:0 
  at MonoTorrent.MagnetLink..ctor (System.String url) [0x00022] in <ae312fb8a3344a4cbaa8e26ab9c29717>:0 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromMagnetUrl (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, System.String magnetUrl) [0x00004] in <fd6dc903261f46d49ff7a60364fd04b3>:0 
```

I believe the intention was to fix here:

https://github.com/Jackett/Jackett/commit/7e93a86ae0997bc07dafed3df439c0eacc2b12db

However this can still be reproduced as follows (for 1337x at least):

- Add indexer 1337x
- Make request to Jackett 
  - (`http://192.168.1.100:9117/api/v2.0/indexers/1337x/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=mary%20witch%20s%20flower`)
- Get back Jackett download link
- Request Jackett link in Postman
- See Postman complain about bad redirect URI
  - `Error: Invalid URI "magnet:/?xt=urn:btih:8759D72668F503D20AE8E5A6DCBD9A33A531130A&dn=Mary+and+the+Witch&#039;s+Flower+(2017)+(1080p+BluRay+x265+HEVC+10bit+AAC+5.1+Japanese+Tigole)+[QxR]&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce". This can be caused by a crappy redirection.`

The issue here of course being the `&#039;s` in the display name `dn` field.

Copying the link from the 1337x site gives the correct encoded magnet (as seen below), thus seems Jackett is somehow encoding improperly before sending back in the download redirect

- `magnet:?xt=urn:btih:8759D72668F503D20AE8E5A6DCBD9A33A531130A&dn=Mary+and+the+Witch%26%23039%3Bs+Flower+%282017%29+%281080p+BluRay+x265+HEVC+10bit+AAC+5.1+Japanese+Tigole%29+%5BQxR%5D....`

We continue to get issue reports from Radarr/Sonarr/Lidarr related to this issue. Would appreciate help in getting it fixed on Jackett side. Thanks

## Related issues
https://github.com/Sonarr/Sonarr/issues/3573
https://github.com/Radarr/Radarr/pull/4351

**Comment by ngosang** [comment]
@Qstick please, try the latest release.

**Comment by Qstick** [comment]
Thanks, I’ll give it a go
