### ISSUE TITLE
[Redacted.ch] Support API token in place of uname+pass(+cookie)

### ISSUE THREAD

**Issue by flying-sausages** [Jackett/Jackett#8898]
I removed the default template as this is a feature request and not a bug.

Redacted.ch has an API that will be sub-classing the existing Gazelle API which is being currently used. [API Keys are now available and documentation as well.](https://redacted.ch/wiki.php?action=article&id=455) This method of authentication will be deprecated over time. The API has additional endpoints that will only work when API keys are used.

The use of an API key is a lot more easier to maintain, and 2FA users do not have to pass through the whole DevTool Cookie retrieval procedure which is quite sub-optimal.

@ngosang I saw the git blame and have noticed you have made multiple commits against the Redacted.cs file, so I'd like to give you a small ping with this one. I'm sorry if it's unsolicited.

**Comment by garfield69** [comment]
Jackett 0.16.1472

**Comment by ngosang** [comment]
Reverted due to #9751 and #9753

**Comment by garfield69** [comment]
Jackett 0.16.1621

**Comment by LennyPenny** [comment]
since the implementation of this got reverted could we reopen this issue? 
Or is there a new tracking issue I missed?

**Comment by LennyPenny** [comment]
It seems that #9666 was reverted due to #9751, which mentions a user agent issue
It seems that #10528 fixed the user agent issue. 

Is there anything else preventing a resubmission of #9666 from being merged?

**Comment by garfield69** [comment]
v0.18.709
