### ISSUE TITLE
[REQ] Pleae add new tracker TOTheglory.IM

### ISSUE THREAD

**Issue by sethwarsh** [Jackett/Jackett#89]
Please add new tracker ToTheGlory.IM, I can provide an invite upon request skype'sethmw' email 'sethmw@gmail.'com

Torznab Categories

/AddCategoryMapping("1", TorznabCatType.Console);

AddCategoryMapping("NDS", TorznabCatType.ConsoleNDS);

AddCategoryMapping("`PSP", TorznabCatType.ConsolePSP);

AddCategoryMapping("WII", TorznabCatType.ConsoleWii);

//AddCategoryMapping("1", TorznabCatType.ConsoleXbox);

AddCategoryMapping("XBOX360", TorznabCatType.ConsoleXbox360);

//AddCategoryMapping("1", TorznabCatType.ConsoleWiiwareVC);

AddCategoryMapping("XBOX to XBOX360", TorznabCatType.ConsoleXBOX360DLC);

AddCategoryMapping("PS3", TorznabCatType.ConsolePS3);

//AddCategoryMapping("1", TorznabCatType.ConsoleOther);

//AddCategoryMapping("1", TorznabCatType.ConsoleOther);

//AddCategoryMapping("1", TorznabCatType.ConsoleOther);

//AddCategoryMapping("1", TorznabCatType.ConsoleOther);

//AddCategoryMapping("1", TorznabCatType.ConsoleOther);

//AddCategoryMapping("1", TorznabCatType.ConsoleOther);

//AddCategoryMapping("1", TorznabCatType.Console3DS);

//AddCategoryMapping("1", TorznabCatType.ConsolePSVita);

//AddCategoryMapping("WIIU", TorznabCatType.ConsoleWiiU);

//AddCategoryMapping("XBOX1", TorznabCatType.ConsoleXboxOne);

//AddCategoryMapping("PS4", TorznabCatType.ConsolePS4);

//AddCategoryMapping("1", TorznabCatType.Movies);

//AddCategoryMapping("1", TorznabCatType.MoviesForeign);

//AddCategoryMapping("1", TorznabCatType.MoviesOther);

//AddCategoryMapping("电影720p", TorznabCatType.MoviesOther);

//AddCategoryMapping(“1”, TorznabCatType.MoviesSD);

AddCategoryMapping(“电影1080i/p”, TorznabCatType.MoviesHD);

//AddCategoryMapping("1", TorznabCatType.Movies3D);

AddCategoryMapping(“BluRay原盘”, TorznabCatType.MoviesBluRay);

AddCategoryMapping(“电影DVDRip”, TorznabCatType.MoviesDVD);

//AddCategoryMapping("1", TorznabCatType.MoviesWEBDL);

//AddCategoryMapping(“1, TorznabCatType.Audio);

//AddCategoryMapping("1”, TorznabCatType.AudioMP3);

//AddCategoryMapping("1", TorznabCatType.AudioVideo);

//AddCategoryMapping("1", TorznabCatType.AudioVideo);

//AddCategoryMapping("1", TorznabCatType.AudioAudiobook);

AddCategoryMapping(“无损音乐FLAC&APE`”, TorznabCatType.AudioLossless);

//AddCategoryMapping("1", TorznabCatType.AudioOther);

//AddCategoryMapping("1", TorznabCatType.AudioOther);

//AddCategoryMapping("1", TorznabCatType.AudioForeign);

//AddCategoryMapping("1", TorznabCatType.PC);

AddCategoryMapping("APPZ", TorznabCatType.PC);

AddCategoryMapping("1", TorznabCatType.PC0day);

//AddCategoryMapping("1", TorznabCatType.PCISO);

AddCategoryMapping("`MAC", TorznabCatType.PCMac);

//AddCategoryMapping("1", TorznabCatType.PCPhoneOther);

AddCategoryMapping("PC", TorznabCatType.PCGames);

AddCategoryMapping("iPhone/iPad视频", TorznabCatType.PCPhoneIOS);

AddCategoryMapping("1", TorznabCatType.PCPhoneAndroid);

//AddCategoryMapping("1", TorznabCatType.TV);

//AddCategoryMapping("1", TorznabCatType.TV);

AddCategoryMapping("1", TorznabCatType.TVWEBDL);

//AddCategoryMapping("1", TorznabCatType.TVWEBDL);

AddCategoryMapping("高清日剧`", TorznabCatType.TVFOREIGN);

AddCategoryMapping("高清韩剧", TorznabCatType.TVFOREIGN);

//AddCategoryMapping(“1“, TorznabCatType.TVSD);

AddCategoryMapping(“1”, TorznabCatType.TVSD);

AddCategoryMapping(“欧美剧720p”, TorznabCatType.TVHD);

AddCategoryMapping(“欧美剧1080i/p`, TorznabCatType.TVHD);

AddCategoryMapping("欧美剧包`", TorznabCatType.TVOTHER);

AddCategoryMapping(“高清体育节目`”, TorznabCatType.TVSport);

AddCategoryMapping(“高清动漫”, TorznabCatType.TVAnime);

AddCategoryMapping("`纪录片1080i/p", TorznabCatType.TVDocumentary);

//AddCategoryMapping(“1”, TorznabCatType.MoviesBBC);

//AddCategoryMapping("1", TorznabCatType.XXX);

//AddCategoryMapping(“1, TorznabCatType.XXXHD);

//AddCategoryMapping("1”, TorznabCatType.XXXHD);

//AddCategoryMapping(“1”, TorznabCatType.XXXDVD);

//AddCategoryMapping(“1”, TorznabCatType.XXXDVD);

//AddCategoryMapping(“1”, TorznabCatType.XXXBluRay);

//AddCategoryMapping(“1”, TorznabCatType.XXXBluRay);

//AddCategoryMapping("1", TorznabCatType.XXXWMV);

//AddCategoryMapping(“1”, TorznabCatType.XXXXviD);

//AddCategoryMapping(“1”, TorznabCatType.XXXXviD);

//AddCategoryMapping(“1”, TorznabCatType.XXXTV);

//AddCategoryMapping(“1”, TorznabCatType.XXXTV);

//AddCategoryMapping("1", TorznabCatType.XXXx264);

//AddCategoryMapping("1", TorznabCatType.XXXOther);

//AddCategoryMapping("1", TorznabCatType.XXXImageset);

//AddCategoryMapping("1", TorznabCatType.XXXPacks);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.Other);

//AddCategoryMapping("1", TorznabCatType.OtherMisc);

//AddCategoryMapping("1", TorznabCatType.OtherHashed);

//AddCategoryMapping(“1”, TorznabCatType.Books);

//AddCategoryMapping("1", TorznabCatType.BooksEbook);

//AddCategoryMapping("1”, TorznabCatType.BooksComics);

//AddCategoryMapping("1", TorznabCatType.BooksComics);

//AddCategoryMapping("1", TorznabCatType.BooksComics);

//AddCategoryMapping("1", TorznabCatType.BooksMagazines);

//AddCategoryMapping("1", TorznabCatType.BooksTechnical);

//AddCategoryMapping("1", TorznabCatType.BooksOther);

//AddCategoryMapping("1", TorznabCatType.BooksForeign);

//AddCategoryMapping("1”, TorznabCatType.Software);

/AddCategoryMapping(“1”, TorznabCatType.Game);

//AddCategoryMapping(“1”, TorznabCatType.TVDVD);

//AddCategoryMapping(“1”, TorznabCatType.TVBluRay)

**Comment by savahu** [comment]
Maybe you can invite @kaso17 if you still want TTG to be supported!

**Comment by sethwarsh** [comment]
I can get you an invitation, please send me your email.

S

**Comment by kaso17** [comment]
please send the invite to kaso1717 -at- gmail.com

**Comment by kaso17** [comment]
got the invite, thank you

**Comment by sethwarsh** [comment]
You're very welcome.

Thank you!

S

**Comment by kaso17** [comment]
fixed with 606e629cc680601aba24ef4e03165f10a78479d4

Please double check the category mapping

**Comment by kaso17** [comment]
Another short question:
I'm getting these "warnings":
目前下载量：0.00 kB (未达标，请保证下载量在40GB以上)
目前上传量：12.06 MB (未达标，请保证上传量在40GB以上)
目前做种积分：80.59 (未达标，请保证做种积分在5000以上)
目前分享率： (未达标，请保证整体分享率>1)
亲，距离新人考核结束还有27天，请务必改善，否则将会被系统禁用

I'm not sure if google translated it correctly.
Does it mean that I've to up and download + get 5000 seed points within 27 days?

**Comment by sethwarsh** [comment]
I don't know either, should I PM the sysop and ask?

S

**Comment by kaso17** [comment]
that would be nice. I intend to keep the account active but it seems like my European seedbox has a very bad connection towards china (not uploading more than a few kBit/s)

**Comment by armani316** [comment]
Though I don't speak Mandarin , but this is standard of al Chinese trackers. It's a 'newbie test' that you have to pass within 30 days of signing up. You'll need to upload at least 40 GB, download at least 40 GB, and earn a minimum of 5000 points in the process. Otherwise, your account will get disabled.

**Comment by kaso17** [comment]
thank you for the clarification, maybe you  know what are the rules regarding multi IP seeding (multiple seedboxes)?
上传下载不能同时出现3台电脑（最多2台），具体说来：
上传：
不同种子，允许1-2台电脑同时上传（最多2台）。
同一个种子，发布人允许1-2台电脑同时上传（特殊热门大作为了保证分流速度,不做任何限制），非发布人不允许。
下载：
不同种子，允许1-2台电脑同时下载（最多2台）
同一个种子，不允许2台电脑同时下载。
Translation doesn't make it 100% clear to me. Does it mean as a normal user I'm allowed to download/seed the torrents from two computers but not the same torrent?

**Comment by armani316** [comment]
Honestly I'm not sure, @kaso17. With the first one, I knew what it meant because the newbie test is a general rule in most Chinese trackers. With the upload/download rules, I'm also confused by the translation, so I can't give you a definitive answer on what it means. 

I'm not a member of TTG, but I read that you can choose to display the website in English. Try that and see if the rules are explained clearly in English. Alternatively, you can either ask the Mods or ask a question in the English section of the forums.

**Comment by sethwarsh** [comment]
I've already asked the sysop for you. She may just waive the test for you. She knows you we're adding the site to Jackett, let's wait for her response.

Any interest in doing HD China or M Team?

S

**Comment by kaso17** [comment]
Shouldn't be necessary to waive them. I already did 73 GB upload yesterday after changing to my home connection. Download and seedpoints shouldn't be a problem. I was just a little bit confused about that rule, but as armani316 clarified, it seems to be the normal procedure.

If you send me invites (kaso1717 -at- gmail.com) for HDChina/MTeam I'll add them.

**Comment by kaso17** [comment]
one more question:
Does the 30% label on torrents mean only 30% of the download is counted or does it mean 30% is free (70% counted)?

**Comment by sethwarsh** [comment]
30% is counted
