### ISSUE TITLE
New TVChaos Search error (might be in Sonarr)

### ISSUE THREAD

**Issue by MisterC925** [Jackett/Jackett#891]
There's a new series on this server called "The Witness for the Prosecution"

Added in Sonarr, it attempts to search tvchaos with "Witness for the Prosecution 2016 S01E01" which fails.

"Witness for the Prosecution S01E01" works, as does "Witness for the Prosecution S01E01 2016"

I know TVchaos uses weird naming schemes but figured it wouldn't hurt to see if it's something that can be managed from Jackett w/o too much trouble

Thanks!

Dec 26, 2016 08:30:32 PM 	Info 	

Manual search for "Witness for the Prosecution S01E01 2016" on TV Chaos with 2 results.

Dec 26, 2016 08:30:24 PM 	Info 	

Manual search for "Witness for the Prosecution S01E01" on TV Chaos with 2 results.

Dec 26, 2016 08:30:15 PM 	Info 	

Manual search for "Witness for the Prosecution 2016 S01E01" on TV Chaos with 0 results.

**Comment by kaso17** [comment]
The proper way to fix it is to fix the non standard naming scheme of the TVChaos release.
Even if we would e.g. strip the year from the search query in Jackett I'm not 100% sure if sonarr would pick it up. If that's not an option you might want to try requesting an "don't include the year in search" option on the sonarr side.
Working around the problem using Jackett is a bad idea.
I've opened #893 as enhancement ticket anyway.
