### ISSUE TITLE
[LEChaudron] too many search result

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#8920]
### Environment

**OS**: Windows 10

**Jackett Version**: 0.16.609.0

**Are you using a proxy or VPN?** No

### Description
When I use manual or automatique search with this tracker, I have too many unrelated results : 

Request in Jackett : https://lechaudron.nl/TTV3/Torrents/Recherche?recherche=aladdin&type=tout&endroit=nomtorrent&langue=0&tl=peuimporte
Too many results that doesn't contain "aladdin"

Same request on LeChaudron : https://lechaudron.nl/TTV3/Torrents/Recherche?search=aladdin&cat=0&incldead=0&freeleech=0&lang=0
1 result : the good one.

### Logged Error Messages

No error messages

### Screenshots

No screenshots.

Thanks for all !

**Comment by loulich** [comment]
Hey,

Same here !

**Comment by garfield69** [comment]
Looks like they have upgraded their web engine recently. I'll bring the indexer up to date.

**Comment by garfield69** [comment]
Jackett 0.16.656

**Comment by pipopop** [comment]
Works perfectly !
Great thanks !

**Comment by loulich** [comment]
Thanks for this great job !
