### ISSUE TITLE
Search query/result rewrite rules

### ISSUE THREAD

**Issue by kaso17** [Jackett/Jackett#893]
Sometimes e.g. Sonarr won't find releases due to non standard naming schemes of releases.
Examples: #891 and #569/#806

Working around this problem in Jackett is a bad idea but if someone implements a generic solution for it i guess it could be added.

One possible solution could be a list of search/replace regular expressions to translate the sonarr search query into an non standard search query and a second list to translate the search results back to sonarr format.

I'm not sure if the lists should be global or indexer specific.

Fell free to discuss/implement.

**Comment by MisterC925** [comment]
I"ll see if I can't figure something like this out.  I opened an issue with Sonarr but they responded that the fields are passed separately so Jackett should be able to have a custom query per tracker w/o a change at the Sonarr level. (https://github.com/Sonarr/Sonarr/issues/1602)

**Comment by kaso17** [comment]
Sonarr passes season and episode separately, but the year is included in the search string (show title).

**Comment by kaso17** [comment]
For Cardigann definitions this can be done with Keywordfilters now
See https://github.com/Jackett/Jackett/commit/3bef41aeb6a6cf8af4d67075bc5f775f6ce617a0 for an example.
If someone is willing to implement it as a more generic version (with GUI support?) that would be appreciated.

**Comment by garfield69** [comment]
Closing as stale.
