### ISSUE TITLE
[Bug] Nostre.am Configuration Failed

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#894]
Enhanced log attached.

[log.txt](https://github.com/Jackett/Jackett/files/674612/log.txt)

**Comment by kaso17** [comment]
it's working fine for me.

Looks like they return an empty document when opening https://nostre.am/ajax.php?action=browse&order_by=time&order_way=desc
What happens if you open it in your browser?
It should return a lot of text starting with {"status":"success","response":...

**Comment by armani316** [comment]
Working fine now! Thanks!
