### ISSUE TITLE
[pirateiro] Exception (pirateiro): Clearance failed after 10 attempt(s)

### ISSUE THREAD

**Issue by Luis-Lourenco** [Jackett/Jackett#8942]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker on Linux

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] I don't know

**.Net Version**:

**Jackett Version**: Version 0.16.521.0

**Last Working Jackett Version**: Version 0.16.521.0

**Are you using a proxy or VPN?** NO

### Description

Exception (pirateiro): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s).

### Logged Error Messages

[log.txt](https://github.com/Jackett/Jackett/files/4757135/log.txt)
[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

N/A

**Comment by garfield69** [comment]
closing as a duplicate and/or as related to #7973 and #8840
