### ISSUE TITLE
[New Tracker REQ] BitHQ

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#895]
**Indexer Name**
BitHQ

**Type**
Movies

**Indexer URL**
http://www.bithq.org/

**Indexer Language**
English

**Invite**
Sent

**Note**
If sign up fails, try to manually copy and paste the Promotional Code & Inviter ID from the email's body into the signup form

**Comment by kaso17** [comment]
got the invite, thank you

**Comment by kaso17** [comment]
fixed with eb0e82494cf9c0a47497d81f1c72c842d04ace4f
