### ISSUE TITLE
[REQ] pcgamestorrents

### ISSUE THREAD

**Issue by fensoft** [Jackett/Jackett#8950]
URL => https://pcgamestorrents.com/
type => public

Thanks !

**Comment by garfield69** [comment]
this site does not have an .torrent or magnet itself.
it farms them off to a third party site which, after a 10 second count down delay, and a random number of multiple redirects, at some point, you eventually may get to a magnet link or optional .torrent link.

as such this site is not suitable for use with Jackett which requires a direct magnet or .torrent link for users to download on the first click.
