### ISSUE TITLE
Issue with limetorrents, torrents2k

### ISSUE THREAD

**Issue by rottenCoder** [Jackett/Jackett#8961]
limetorrnets connot connect with sonarr or radarr.
Error: index returned no results while test, so can's be saved.
torrents2k works and connect and provide torrent search result but no torrent get downloaded and added to torrent client when clicked on auto or manual download button on radarr but return success response means download button toggle to download mode.

**Comment by ilike2burnthing** [comment]
What versions of Jackett, Sonarr, and Radarr are you running?

Does testing and searching work in Jackett for those indexers?

What categories are you using for each in Sonarr and Radarr?

**Comment by rottenCoder** [comment]
Both latest version. Yes work from inside jackett. Used categories defined in respective index setting.

**Comment by ilike2burnthing** [comment]
Version numbers please, 'latest' does not really help.

Category numbers too.

**Comment by rottenCoder** [comment]
Jackett Version 0.16.700.0
Sonarr Ver. 2.0.0.5344
Radarr Ver. 0.2.0.1480 develop
-----------------------------------
Torrentz2k Categories Used: 2000,5000
LimeTorrents Categories Used: 2000,5000
Kickass Torrents (KATcr) Categories Used: 2000

**Comment by ilike2burnthing** [comment]
Thanks.

In Jackett, perform an empty search using only LimeTorrents (this is the same as running a test). It should return 150 results. Do any of them use the TV or Movies categories? If not, running a test in Sonarr/Radarr will fail if only using using 5000/2000.

This regularly happens with LimeTorrents unfortunately, they all just end up being Other/Misc for a while, so you either have to get lucky, wait, or add 7010 to the categories you already have (I've gone for the latter, as there are often TV and Movies in that category as well).

Does downloading a torrent from Torrentz2k work in Jackett? I haven't had that issue with it before, but I'll double check.

**Comment by ilike2burnthing** [comment]
Torrentz2k - https://github.com/Jackett/Jackett/issues/8889

**Comment by rottenCoder** [comment]
The solution for  limetorrents worked like a charm but no luck with torrents2k i have rechecked. magnet link works inside jackett but from sonarr or raddar search results appears from torrents2k but when click download icon the icon  changes to  downloading mode but no torrent is added to the download client.

**Comment by ilike2burnthing** [comment]
@garfield69 @Qstick just wanting to check that this issue with Torrentz2k is related to #8889

**Comment by Qstick** [comment]
Looks like it

**Comment by ilike2burnthing** [comment]
Thanks.

@rottenCoder you can follow that issue and we'll close this one
