### ISSUE TITLE
[New Tracker REQ] TorrentProject

### ISSUE THREAD

**Issue by wcomartin** [Jackett/Jackett#897]
Indexer Name
TorrentProject

Type
TV,Movies

Indexer URL
https://torrentProject.se/

Indexer Language
English

Invite
Not Required

Note
what is the possibility of adding some public indexers?

**Comment by crafty35a** [comment]
Is there a reason you closed this request, @wcomartin ? I would love to have support for TorrentProject as well. Did you find a way?

**Comment by wcomartin** [comment]
I actually don't remember why I closed this ticket

**Comment by armani316** [comment]
@wcomartin & @crafty35a It was probably closed because Jackett did not support public trackers at the time. It does now, and as such, I've added the 'New tracker' label.

**Comment by crafty35a** [comment]
Thanks -- it would be great to see this added.
