### ISSUE TITLE
[REQ] oMg[WtF]trackr private https://omg.wtftrackr.xyz/

### ISSUE THREAD

**Issue by z3r0byt3s** [Jackett/Jackett#8970]
https://omg.wtftrackr.xyz/

```
    Torrents: 130,043
    Requests: 0 (0.00% filled)
    Files size: 212.7743 TB
    Completed: 270,631,318
    Transferred: 606.04375 PB
    Peers: 2,819,441
    Seeders: 1,763,166
    Leechers: 1,056,275
    Seeder/leecher ratio: 1.66
```

**Comment by garfield69** [comment]
currently invite only.
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by z3r0byt3s** [comment]
Check your mail :-)

**Comment by garfield69** [comment]
Registration and login successful. Thank you.

**Comment by garfield69** [comment]
Jackett 0.16.722

**Comment by garfield69** [comment]
https://omg.wtftrackr.xyz/ returning Error 521 Web server is down

**Comment by garfield69** [comment]
still offline but now getting Error 522 Connection timed out

**Comment by garfield69** [comment]
@z3r0byt3s  do you have any info on https://omg.wtftrackr.xyz/
is the site gone, broken or moved to another domain?

**Comment by z3r0byt3s** [comment]
gonna be online soon

**Comment by ilike2burnthing** [comment]
back up

**Comment by z3r0byt3s** [comment]
:-)

**Comment by garfield69** [comment]
https://omg.wtftrackr.xyz/ returning Error 521 Web server is down

**Comment by garfield69** [comment]
@z3r0byt3s do you have any info on https://omg.wtftrackr.xyz/
is the site gone, broken or moved to another domain?

**Comment by garfield69** [comment]
Jackett 0.17.15

**Comment by z3r0byt3s** [comment]
Online :]

**Comment by ilike2burnthing** [comment]
re-added

**Comment by ilike2burnthing** [comment]
https://omg.wtftrackr.xyz/ - 404 Not Found

**Comment by garfield69** [comment]
https://omg.wtftrackr.xyz/ returning Error 521 Web server is down
https://www.uptrends.com/tools/uptime reporting Http Protocol Error across all 43 site globally

**Comment by garfield69** [comment]
now returning apache2 default page
![image](https://user-images.githubusercontent.com/6933240/132937015-ff3cf072-f6ea-457b-82ae-8b1f11c53219.png)

**Comment by garfield69** [comment]
back to Error 521 Web server is down

**Comment by z3r0byt3s** [comment]
Sorry for a downtime.

But we had to rewrite all the old code of gazelle to make it work on newest distro of ubuntu due that the main gazelle code is outdated as hell...

Now also rocking on ssd, then we switch to nvme in future

```
Torrents: 741,169
Files size: 1.45 PB
Completed: 1,410,499,927
Transferred: 3.04 EB
Peers: 110,342,457
Seeders: 50,838,251
Leechers: 59,504,206
```

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://omg.wtftrackr.xyz/ returning Error 521 Web server is down

**Comment by z3r0byt3s** [comment]
https://github.com/Jackett/Jackett/issues/8970#issuecomment-925986587

"Now also rocking on ssd, then we switch to nvme in future"

Future is now :D We are rocking on nvme disk!

**ONLINE**

**Comment by garfield69** [comment]
\o/ online

**Comment by ilike2burnthing** [comment]
https://omg.wtftrackr.xyz/ - Error 524 - A timeout occurred

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://omg.wtftrackr.xyz/ returns Error 500 
Uptime reports 403 forbidden across all checkpoints.

**Comment by garfield69** [comment]
v0.20.1316
