### ISSUE TITLE
Error performing update on Windows 10

### ISSUE THREAD

**Issue by adem4ik** [Jackett/Jackett#8975]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10 x64 2004

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.700.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
- Start Jackett
- Open Web UI
- Run "Check for updates" and wait a bit
Result: 
```
2020-06-14 08:33:38 | Error | Error performing update.
-- | -- | --
2020-06-14 08:31:58 | Info | Downloading release v0.16.704 It could take a while...
2020-06-14 08:31:58 | Info | New release found. Current version: v0.16.700 New version: v0.16.704
```
Expected result: Sucsessful update to v0.16.704

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
I've had this once before a couple weeks ago.
It's likely that the GitHub servers were busy or there was a network error.

Try again.
If it continues to fail, then provide a **full enhanced** log which should contain additional debugs that may contain more details on the cause of the error.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by adem4ik** [comment]
It happens for me constantly for the last 3 months or so. 

About `%ProgramData%\Jackett\log.txt`, unfortunately it looks useless since it has only this:
```
2020-06-14 08:28:56.8929 Info Starting Jackett v0.16.700.0 
2020-06-14 08:28:57.4388 Info Initiating Jackett service uninstall 
2020-06-14 08:28:58.5454 Warn The service is already uninstalled 
2020-06-14 08:28:58.6595 Info The service was uninstalled. 
2020-06-14 08:28:59.0102 Info Starting Jackett v0.16.700.0 
2020-06-14 08:28:59.1671 Info Initiating ReserveUrls 
```
Though WebUI's log looks useful, I've saved it as HTML: 
[Jackett WEBUI log.zip](https://github.com/Jackett/Jackett/files/4775942/Jackett.WEBUI.log.zip)

**Comment by garfield69** [comment]
Strange. I run the same windows 10 home x64 build 2004 and I don't have issues performing the Jackett check-for-update, so the problem would appear to be at your end.
you say its been happening for 3 months? 
Have you checked your firewall logs or anti malware logs for possible blocking?
@cadatoiva  @ngosang  any thoughts on this topic?

**Comment by ngosang** [comment]
#9025 won't solve the issue, but it will provide the full exception in the jackett ui.

**Comment by ngosang** [comment]
@adem4ik Try Jackett 0.16.759 and share the logs.
