### ISSUE TITLE
Add jackett to sickrage

### ISSUE THREAD

**Issue by saitoh183** [Jackett/Jackett#898]
i found #733  but since the image from @duramato doesnt show anymore, can someone explain how to add to sickrage.

thanks

**Comment by kaso17** [comment]
I believe the following instructions might still be correct:
http://www.htpcguides.com/configure-sickrage-usenet-torrent-tv/
See the "Add Custom Newznab Search Provider" section

**Comment by saitoh183** [comment]
But that would be for usenet and not torrents?

**Comment by kaso17** [comment]
AFAIK they call it NEWZNAB in sickrage but it also supports torrents (torznap is based on newznap).
If you managed to get it to work please document it in the wiki.

**Comment by saitoh183** [comment]
ah ic...its cuz i only see it if a enable usenet

**Comment by flightlevel** [comment]
@saitoh183 
If it doesn't work using newznab, ask over at https://github.com/pymedusa/Medusa , they seem very active, its all the previous sickgrage guys minus one

**Comment by kaso17** [comment]
"Configure Custom Newznab Providers" seems to be correct. For me the picture from #733 shows up perfectly fine (again?).

**Comment by duramato** [comment]
The image not showing was partially my fault :P but just fixed it. Feel free to ping me if you need any help.

**Comment by saitoh183** [comment]
@duramato and @kaso17 
well this doesnt seem to work for me in scikrage
`WARNING SEARCHQUEUE-MANUAL-316544 :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.`

![image](https://cloud.githubusercontent.com/assets/1534197/21789302/03ee3504-d6a2-11e6-920a-b466d40b2a7a.png)

![image](https://cloud.githubusercontent.com/assets/1534197/21789318/15da89de-d6a2-11e6-8743-2ba058e5e429.png)

In Cardigann and Jackett i can search and find the episode of the show im using for testing

![image](https://cloud.githubusercontent.com/assets/1534197/21789364/636f7a92-d6a2-11e6-8ed2-5795b234d688.png)

**Comment by duramato** [comment]
You have to enabled the provider for daily and backlog searches to be able to use it:
![image](https://pls.gtfo.accountant/AaNRw.png)

**Comment by saitoh183** [comment]
@duramato 

lol..i completely forgot about there :)...thank you sir :)

**Comment by Jamyz** [comment]
No work for me.
Exemple, i try with Star Trek Discovery, in Jackett work fine.
But with Sickrage no. Because Sickage search like that "Star Trek Discovery - S10-E01 - Episode Name"
And if you try with Jackett like "Star Trek Discovery - S10-E01 - Episode Name" doesn't work..
Any ideas ?

**Comment by duramato** [comment]
@Jamyz Sickrage doesn't do a search like that. It seraches as `Show name S01E01`, that just sounds like you need to add a scene exception.

**Comment by Jamyz** [comment]
I think that first. I try with "Supergirl" because no need scene eception. and i have that.
`2018-01-22 16:33:33 INFO SEARCHQUEUE-MANUAL-295759 :: Unable to find a download for: [Supergirl - S03E10 - Legion of Super-Heroes]
2018-01-22 16:33:22 INFO SEARCHQUEUE-MANUAL-295759 :: [Jackett-Torrent9] :: Performing episode search for Supergirl
2018-01-22 16:33:22 INFO SEARCHQUEUE-MANUAL-295759 :: Beginning manual search for: [Supergirl - S03E10 - Legion of Super-Heroes]`

**Comment by duramato** [comment]
The scene exception is only for the `Show name` part. Check your jackett configuration within SickRage, like if the categories are set and api key correct.

**Comment by kaso17** [comment]
@Jamyz 
You're probably affected by https://github.com/SickRage/SickRage/issues/3526

**Comment by saitoh183** [comment]
> Probably yes.
I'm not sure if the medusa sickrage fork already fixed this problem.

I dont have this problem on Medusa. They fixed the issue with jackett and since it has worked fine with request coming from jackett

**Comment by Jamyz** [comment]
In Medusa with Jackett, in Jackett Log he found but no download.
`Found 2 releases from Torrent9 for: Arrow S06E10`
In Medusa Log i have,
`2018-01-23 09:48:38 INFO     SEARCHQUEUE-FORCED-257655 :: [bd08325] Unable to find forced results for: Arrow - S06E10 - Divided
2018-01-23 09:48:12 INFO     SEARCHQUEUE-FORCED-257655 :: [jackett-torrent9] :: [bd08325] Performing episode search for Arrow
2018-01-23 09:48:12 INFO     SEARCHQUEUE-FORCED-257655 :: [bd08325] Using backlog search providers
2018-01-23 09:48:11 INFO     SEARCHQUEUE-FORCED-257655 :: [bd08325] Building internal name cache for Arrow
2018-01-23 09:48:11 INFO     SEARCHQUEUE-FORCED-257655 :: [bd08325] Finished processing 2636 scene exceptions.
2018-01-23 09:48:11 INFO     SEARCHQUEUE-FORCED-257655 :: [bd08325] Updating exception_cache and exception_season_cache
2018-01-23 09:48:11 INFO     SEARCHQUEUE-FORCED-257655 :: [bd08325] Beginning forced search for: Arrow - S06E10 - Divided`
I forget something ?

**Comment by duramato** [comment]
Info logs don't have any info, but I only debug logs will tell what's going on.
Also Medusa will have support for torznab as a built in provider without needing to use newznab https://github.com/pymedusa/Medusa/pull/3513

**Comment by Andreasav** [comment]
Can someone please help me. 

I cant get Jackett, sickrage and deluge to work. I have enable nzb search and tested both with a map and without a map, when I´m using blackhole.

When sickrage get a magnet , I got error, 
request failed no connection adapters were found for....... and then torrent file content is empty 

![skarmklipp](https://user-images.githubusercontent.com/36073851/37416290-af3d36dc-27ad-11e8-8c92-9086e6d1ccf6.JPG)
![skarmklipp_](https://user-images.githubusercontent.com/36073851/37416291-af69de94-27ad-11e8-81c0-3c5f934ef21b.JPG)

**Comment by kaso17** [comment]
sickrage can't handle magnet URIs, not sure if the medusa fork can handle it.

**Comment by Andreasav** [comment]
OK, but why will it works time to time?
What do I do "wrong" ?

![skarmklipp__](https://user-images.githubusercontent.com/36073851/37480745-5958a58e-2880-11e8-85a6-c2cbe8ccb4e3.JPG)

**Comment by Andreasav** [comment]
I found the issues. torlock use torrents instead of magnets. 
So can I change tex 1337x to use torrents enstead of magnets via jackett?

**Comment by kaso17** [comment]
you can change the download link option in the configuration dialog to itorrents. But it won't work for all torrents.

**Comment by Lichtenshtein** [comment]
I think i'm going crazy, but i don't see a "Configure Custom Newznab Providers" tab in Search Providers. There said that "NZB/Torrent and NZB providers can be toggled in Search Settings", but i don't see any options how to add custom provider with API key as shown on Duramato's (commented on Jan 10, 2017) screenshot, and so i can't connect Jackett to Sickrage...

**Comment by flightlevel** [comment]
@Lichtenshtein Did you tick the box 'enable NZB search providers' and then save?
Also, consider trying Medusa, much more active development

![image](https://user-images.githubusercontent.com/9430010/43711425-fe703450-99b5-11e8-843d-b0a4a4944ba4.png)

**Comment by Lichtenshtein** [comment]
@flightlevel оооhhh, i see the tab appeared now :D 
I will try Medusa as well...
