### ISSUE TITLE
[sukebei-pantsu] - HTTP ERROR 500

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8984]
https://sukebei.nyaa.net/ - HTTP ERROR 500

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://sukebei.nyaa.net/ - HTTP ERROR 500

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://sukebei.nyaa.net/ - Error 522 - Connection timed out (Bitmitigate)

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://sukebei.nyaa.net/ - Error 522 - Connection timed out (Bitmitigate)

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://sukebei.nyaa.net/ - Error 502 - Bad gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
sukebei.nyaa.net returning Error 502 Bad gateway

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
here we go again, http 500 (internal server error)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://sukebei.nyaa.net/ returning Error 522 Connection timed out

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://sukebei.nyaa.net/ - No results found (same for any search)

**Comment by ilike2burnthing** [comment]
redirects to https://zz.ht/

**Comment by garfield69** [comment]
v0.18.1041
