### ISSUE TITLE
Error when setting blackhole location to mapped network drive

### ISSUE THREAD

**Issue by elvismerrick** [Jackett/Jackett#899]
When I try an set the manual download blackhole directory to a mapped network drive I get an error

 Error: Blackhole directory does not exist

The directory does exist, the only error in the logs is 	

Exception in set_port

I haven't changed the default port so not sure what that error is referring to. If I set the location to somewhere on the C: drive however it does work.

**Comment by flightlevel** [comment]
Why can't you use the UNC path?
Google Sonarr mapped drive for the full explanation

**Comment by elvismerrick** [comment]
I previously tried a UNC path got the same error. Just changed the account the service runs as and it's all good, thanks for pointing me in the right direction.
