### ISSUE TITLE
Jackett needs to reinstalled when I reboot MacOS

### ISSUE THREAD

**Issue by billbennettnz** [Jackett/Jackett#8992]
MacOS, up-to-date everything. 

Jackett works., but can't get back to the web page after a system reboot. From the terminal I can see the software is running, but something resets the web page. 

It's probably a trivial thing, but I can't find any helpful documentation.

**Comment by garfield69** [comment]
which flavour of macos are you running? High Sierra, Mojave, Catalina?

**Comment by billbennettnz** [comment]
Catalina 10.15.5

I'm certain everything is patched and up-to-date.

**Comment by garfield69** [comment]
@thebluepotato  insights?

**Comment by thebluepotato** [comment]
Hi! Sorry to hear Jackett isn’t working as expected!
To give us some more info, could you please explain what you mean when you say « Jackett is running » after reboot? Do you check with `launchctl` or with running processes?
Can you please run the following commands after a reboot, i.e. while it’s running but not showing the webpage:

- `launchctl list org.user.Jackett` (to get some basic info about the agent)
- `launchctl print gui/501/org.user.Jackett` to get even more info

Please note also that Jackett might need some time to load everything after reboot but it is unlikely that this would take more than a minute or two.

**Comment by billbennettnz** [comment]
Thanks for dealing with this. 

It seems the fault is unreproducible. I think, but don't know for sure, the problem I encounter is down to the last par in your reply: "Please note also that Jackett might need some time to load everything after reboot but it is unlikely that this would take more than a minute or two."

I've rebooted three times since and everything seems fine.
