### ISSUE TITLE
Jackett seemingly randomly dying after a day or so

### ISSUE THREAD

**Issue by eob2000** [Jackett/Jackett#8997]
Note: Sorry for not filling out the default issue sheet, i'm not sure on a lot of these categories.

OS: Ubuntu 20.04
Jackett Version: 0.16.728 (Also previous versions that I updated from when reinstalling)

I've been having this issue ever since I installed jackett a few weeks back, using the AMDx64 Linux download I got Jackett set up and working as a service on my machine, all seemed fine until jackett quit and refused to restart, I don't remember the exact issue now but journalctl was telling me it had something to do with NewtonSoft(?). I fixed it by reinstalling (Simply replacing the files in my jackett directory with fresh ones), then just yesterday, same issue, randomly quit, but this time it's a different issue in journalctl (Something to do with a different file, I don't remember the file for this one, sorry!), I put it down to a potential autoupdate issue so I reinstalled jackett and disabled autoupdate and then today. dead again, see the below journalctl screenshot (I would upload a full log but I cannot for the life of me figure out where it is stored, I would appreciate if someone could point me in the right direction!). This time around it isn't even mentioning a file at fault, just that it dumped. I am completely at a loss for what to do, when it's working, it works fine, I have my trackers set up in sonarr and they work just fine, it just dies after a while, I am happy to provide more information where required, thank you!

![image](https://user-images.githubusercontent.com/17178863/84946045-f7371800-b0df-11ea-8a2d-12c293a36d51.png)

**Comment by garfield69** [comment]
on a vanilla Jackett installation, you should find configs and logs in the `~/.config/Jackett/` folder.

**Comment by eob2000** [comment]
Just checked there, there is a log file but I have nothing after the 6th of June which is really odd (and the contents of the logs was purely 'starting jacket vx.x.x', maybe I messed with the config in one of the updates, deleting that log and rerunning is not generating a log file, I did change my systemd service around that time to one with more sandboxing which I have now reverted and it's still not generating a new log on run, i'm really confused now!

**Comment by garfield69** [comment]
I suggest you install afresh, by following all the steps in https://github.com/Jackett/Jackett#install-as-service

**Comment by ngosang** [comment]
I'm pretty sure this bug is caused by the updater in Linux. It was fixed long time ago.
Download the latest version of Jackett and reinstall the systemd service following the @garfield69 instructions.
If that doesn't solve your problem page the contents of `/etc/systemd/system/jackett.service` here.

**Comment by eob2000** [comment]
Just reinstalled and recreated my systemd using the script in the jackett directory, still doesn't work

![image](https://user-images.githubusercontent.com/17178863/85221760-7d887e00-b3ae-11ea-96a5-b333c5711d09.png)
![image](https://user-images.githubusercontent.com/17178863/85221770-8f6a2100-b3ae-11ea-99b2-41b9391116e7.png)
![image](https://user-images.githubusercontent.com/17178863/85221782-a3ae1e00-b3ae-11ea-89e1-168827ed9159.png)

I'm not sure why I can't make it work at all anymore, reinstalling used to make it work for a short period, for whatever reason this still isn't creating a logfile in the nzbdrone home directory

**Comment by ngosang** [comment]
Could you remove the folder `/opt/Jackett` and start again?

**Comment by eob2000** [comment]
Alright, it's running now, I guess I just wait and see if it's gonna quit again, shouldn't take more than a couple of days if it will, thanks for the help!

**Comment by ngosang** [comment]
I will reopen if the problems persist.
