### ISSUE TITLE
CPasbien Categories are not working

### ISSUE THREAD

**Issue by matt789456** [Jackett/Jackett#9003]
Hello! 
This is a very small bug that should be easy to fix.

I was having trouble adding "CPasBien" to Radarr. The problem was that the provided Categories by Jackett for "CPasBien Clone" (I don't know about the other) for Movies is said to be "2000" but that was not working and I had to replace it by "Other" which was "7000".

**Comment by garfield69** [comment]
Neither site shows categories in the search results. Added info in the configs. only 7000 is supported.
