### ISSUE TITLE
Hachedeme Login failed: Selector "div#member_info_bar" didn't match

### ISSUE THREAD

**Issue by vinanrra** [Jackett/Jackett#9004]
Seems like the change something and i am getting this error:

An error occurred while updating this indexer
Login failed: Selector "div#member_info_bar" didn't match

I am using latest version

**Comment by garfield69** [comment]
@RicardoVelaC  is hachede working for you?

**Comment by garfield69** [comment]
@vinanrra  it is likely that this is due to your cookie not being accepted by the site.
have a read of https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work and check that you are grabbing the correct cookie string.

**Comment by vinanrra** [comment]
I will check it
