### ISSUE TITLE
[hachede] Login failed: Selector

### ISSUE THREAD

**Issue by catraba** [Jackett/Jackett#9006]
### Environment

**OS**: Ubuntu 20.04

**Jackett Version**: 0.16.734

**Are you using a proxy or VPN?** [yes/no] no

### Logged Error Messages

 An error occurred while updating this indexer
Login failed: Selector "div#member_info_bar" didn't match

**Comment by garfield69** [comment]
it is likely that this is due to your cookie not being accepted by the site.
have a read of https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work and check that you are grabbing the correct cookie string.
