### ISSUE TITLE
Allow other/multiple season/episode search string formats

### ISSUE THREAD

**Issue by kaso17** [Jackett/Jackett#901]
It would be useful if we could specify the season/episode search string format.

Currently SXXEYY is hard coded but e.g. in Italy it seems like XXxYY format is more popular (See #492).
E.g. the Shareisland indexer contains mostly XXxYY rleases, but also some SXXEYY and some XXxEYY releases.
An option to specify other or multiple patterns for each indexer should fix this. In case of multiple patterns we would have to perform multiple searches and merge the results.

Possibly related: #893

**Comment by kaso17** [comment]
If the tracker supports wildcard search it's possible to workaround the problem by stripping S/E prefixes from the search keywords and normalize the results later (andmatch filter should be used).
Example: https://github.com/Jackett/Jackett/commit/ba14fab0a1c971404d9f26dd30c7b81ae0434f83

**Comment by mueslo** [comment]
This is/was also a big issue for me. There are trackers, where e.g. season packs are not labeled "S01" but rather "Season 1". These are then not found by Jackett, which tries to download episodes individually, where many are missing.

I patched it for my particular tracker: https://github.com/Jackett/Jackett/pull/1632

Maybe it is useful to you.

**Comment by garfield69** [comment]
Closing as stale.
