### ISSUE TITLE
[TopNow] Unrelated results

### ISSUE THREAD

**Issue by janot** [Jackett/Jackett#9027]
Search for "Hambone and Hillie":
![Capture](https://user-images.githubusercontent.com/1689966/85229311-a0885180-b3f1-11ea-9510-67ec95b51c5b.PNG)
When searching on site manually I get this url: https://topnow.se/index.php?search=Hambone+and+Hillie

While Jackett uses this one:
2020-06-21 18:56:44 | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://topnow.se/index.php?search=Hambone%25and%25Hillie)
-- | -- | --

**Comment by garfield69** [comment]
Jackett 0.16.759
