### ISSUE TITLE
[New Tracker REQ] M-Team TP (MTTP)

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#903]
Indexer Name
M-Team TP (MTTP)

Type
General - Music, TV, Movies 

Indexer URL
https://tp.m-team.cc/

Indexer Language
Mandarin, some English  

Invite
Lottery applications / preregistrations are open (link below) - Enter your email (only the part before the @ sign), and you'll receive a confirmation email with a link and a code. Follow the link in the email, and use the code. 

If you're a lucky winner, MTTP will be supported by Jackett :) **You won't be able to use the code immediately; you must wait for the lottery event to end.** No end date has been specified for the current lottery event. Good luck!

https://tp.m-team.cc/preregistered.php

**Comment by kaso17** [comment]
will be added soon

**Comment by kaso17** [comment]
added with b8d40b525969518b364d949c8eac7715f37f4407

**Comment by RoloSoze** [comment]
@kaso17 Jackett does not return dead torrents from M-Team. Can this be fixed?

**Comment by kaso17** [comment]
should be fixed with 0fe06c4cd2a906528376b4f9e0f3723af6e20146
