### ISSUE TITLE
Errors when trying to build from source..

### ISSUE THREAD

**Issue by ERR1R** [Jackett/Jackett#9033]
trying to build the solution to check out some errors for a couple of trackers but i cant seem to build it again..

I use:

Microsoft Visual Studio Community 2019
Version 16.6.2
VisualStudio.16.Release/16.6.2+30204.135
Microsoft .NET Framework
Version 4.8.03752

I get these errors when build or restore the nuget.  Anyone knows what to do to fix this?

**Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'D:\Jackett\Jackett-master\Jackett-master\src\Jackett.IntegrationTests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Jackett.IntegrationTests	C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	
Error	NETSDK1004	Assets file 'D:\Jackett\Jackett-master\Jackett-master\src\DateTimeRoutines\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	DateTimeRoutines	C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	
Error	NETSDK1004	Assets file 'D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Common\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Jackett.Common	C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	
Error	NETSDK1004	Assets file 'D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Service\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Jackett.Service	C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	
Error	NETSDK1004	Assets file 'D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Tray\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Jackett.Tray	C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	
Error	NETSDK1004	Assets file 'D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Updater\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Jackett.Updater	C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	
Error	NETSDK1004	Assets file 'D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Server\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Jackett.Server	C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	
Error	NETSDK1004	Assets file 'D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Test\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Jackett.Test	C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	
Error	CS0006	Metadata file 'D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Common\bin\Debug\netstandard2.0\Jackett.Common.dll' could not be found	Jackett.Server (netcoreapp3.1)	D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Server\CSC	1	Active
Error	CS0006	Metadata file 'D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Common\bin\Debug\netstandard2.0\Jackett.Common.dll' could not be found	Jackett.Test (netcoreapp3.1)	D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Test\CSC	1	Active
Error	CS0006	Metadata file 'D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Server\bin\Debug\net461\JackettConsole.exe' could not be found	Jackett.Test (netcoreapp3.1)	D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Test\CSC	1	Active
Error	CS0006	Metadata file 'D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Common\bin\Debug\netstandard2.0\Jackett.Common.dll' could not be found	Jackett.Updater (net461)	D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Updater\CSC	1	Active
Error		Error occurred while restoring NuGet packages: Invalid restore input. Missing required property 'Name'. Input files: D:\Jackett\Jackett-master\Jackett-master\src\Jackett.Server\Jackett.Server.csproj.**

**Comment by garfield69** [comment]
I followed https://github.com/Jackett/Jackett#windows which works for me.
When I first start Microsoft Visual Studio Community 2019 Version 16.6.2, I regularly get
```
Error occurred while restoring NuGet packages: Invalid restore input. Missing required property 'Name'. Input files: C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Server\Jackett.Server.csproj.
``` 
But this does not prevent me building a debug run for testing.

I suggest you start by deleting and cloning your local jackett repo so as to start with a fresh VS config, by following the above link instructions.

**Comment by ERR1R** [comment]
Thanks mist this one! 

dotnet restore
