### ISSUE TITLE
[Request] Add Audio to Demonoid

### ISSUE THREAD

**Issue by AdeHub** [Jackett/Jackett#905]
Hi, seems like it could be possible to add Music categories to demonoid by using ```&category=2``` in the search url and then filtering the Torrent listing for the Quality - Lossless, MP3 etc

Thanks

**Comment by kaso17** [comment]
Added category mapping in pre-release v0.7.841, please try it

**Comment by AdeHub** [comment]
Cool, any chance you could enhance it further by adding 3040 Lossless, this is ```&category=2&quality=62``` or filtering the summary for 'Lossless'. Could also add 3010 for MP3 by filtering the summary

Thanks

**Comment by kaso17** [comment]
a399e8d0a5ecc3859a7d8b906031d7502b6862ba adds more detailed audio category mapping
