### ISSUE TITLE
[Bug] TV Chaos UK (TVCUK) - Unable to find info

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#906]
I get a 'Test failed for tvchaosuk: Unable to find info' error message. Enhanced log attached. 
[log.txt](https://github.com/Jackett/Jackett/files/680835/log.txt)

**Comment by thegroke** [comment]
I'm also experiencing this.

**Comment by kaso17** [comment]
fixed in the latest pre release, please try v0.7.841
