### ISSUE TITLE
[New Tracker REQ] HDSky (HDS)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#908]
Indexer Name
HDSky

Type
Movies, TV, Music

Indexer URL
https://hdsky.me/

Indexer Language
Mandarin, some English 

Invite
Sent

**Comment by kaso17** [comment]
added with db049b24784cce76b766dd78b0e1635b721dcafe

**Comment by garfield69** [comment]
https://hdsky.me/ returns Error 525 SSL handshake failed
since the cloudflare CA is valid, this is the CA on the host, so we don't get to see the thumbprint to add a bypass.

**Comment by ilike2burnthing** [comment]
back up
