### ISSUE TITLE
[bj-share] Jackett is not closing connections to the tracker

### ISSUE THREAD

**Issue by Nottt** [Jackett/Jackett#9082]
**OS**: Ubuntu 18.04

**.Net Runtime**: hotio/jackett image

**.Net Version**: hotio/jackett image

**Jackett Version**: 0.16.788.0

**Last Working Jackett Version**: Unknown

**Are you using a proxy or VPN?** no

### Description

Add bj-share to jackett, add it to sonarr/radarr and search all missing. It will starting creating lots of new sessions to the tracker and never close them

### Screenshots

![image](https://user-images.githubusercontent.com/13532436/86259178-15961c80-bb92-11ea-8025-6c1c38556c64.png)

**Comment by ngosang** [comment]
@christianfds could you take a look?

**Comment by christianfds** [comment]
Sure, i'm looking into it.

**Comment by garfield69** [comment]
Jackett 0.16.814
