### ISSUE TITLE
Jackett search plug in is suitable for QBittorrent PORTABLE vers 4.1.2..?

### ISSUE THREAD

**Issue by p060477** [Jackett/Jackett#9093]
i have qbittorrent portable 4.1.2 and i try to search with jackett but i always get api key error that leads to the help github page:
https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin

but i have already the .jason file right exactly as the example given in that page..
so i ask you:
this search plugin is suitable for my PORTABLE QBittorrent vers..??
thxs so much in adv
cheers

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
This is a support repo for the Jackett app.
We are not responsible for maintaining or supporting anybody's plugin for qBitTorrent so we cannot answer your question as to whether Jackett is compatible or not.

That said, the Jackett API key should remain constant as long as the ServerConfig.json file is available when Jackett is started. If the file is not found, Jackett creates a new SeverConfig.json file with a new API key.
So this is where you need to concentrate your investigation.
Usually the ServerConfig.json file resides in (windows) `%ProgramData%\Jackett`, (Linux/MacOs) `~/.config/Jackett/`

**Comment by p060477** [comment]
maybe this is the right place..?..:
https://github.com/qbittorrent/search-plugins/issues/92
