### ISSUE TITLE
[KickAssTorrent] down - ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#9095]
https://katcr.co/ - ERR_CONNECTION_TIMED_OUT

no initial req, commit only - https://github.com/Jackett/Jackett/commit/7830b426418cffaa6dbb684d4374f86577de316e

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://katcr.co/ - ERR_NAME_NOT_RESOLVED

**Comment by ilike2burnthing** [comment]
https://newkatcr.co/ - https://github.com/Jackett/Jackett/issues/9132
