### ISSUE TITLE
jackett api key error

### ISSUE THREAD

**Issue by p060477** [Jackett/Jackett#9100]
hi,
i  got a jackett api key  error
configuration file is : 
 jackett.jason
in nova3\engines i'm talking about this:

https://github.com/qbittorrent/search-plugins/tree/master/nova3/engines

i look closely and i see this:

{
    "api_key": "YOUR_API_KEY_HERE",
    "tracker_first": false,
    "url": "http://127.0.0.1:9117"
}

up till yesterday there was a specific page here:
https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin

..now is -strangely- blanck...
anyway could you help me?

now maybe is here..till someone wouldn't cancel it strangely again..:
https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin/_compare/f6117d94bc69bfb7022e2c2dcbab141570fef664...e1755e1d77deaf5eed7c12d8ef07f43b2fca76b5?short_path=1740788#diff-17407887f522b538160faa7da5690fc0
if this should not be the RIGHT place , i pray you INSTEAD of brutally close the issue
to give me the exact link of the place where should i have to post this issue

so many thxs in adv
cheers

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
cannot help you. we know nothing about the qbittorrent plugin you are trying to configure and this is not a jackett problem.
The place to raise your question is where ever you found the qbittorrent plugin.
the jackett.json file you are referring to has nothing to do with jackett and everything to do with the qbitttorrent plugin.
access your jackett dashboard http://127.0.0.1:9117/UI/Dashboard, and select and copy the api key.
then replace YOUR_API_KEY_HERE with the one from the jackett dashboard and save.
That is all the help I can give you.

**Comment by p060477** [comment]
http://127.0.0.1:9117/UI/Dashboard,
unreacheable....
maybe you misunderstood..i've NO jackett INSTALLED...but only the .py and .jason jackett's files in my c users appdata local qbittorent nova3 engines..
maybe this is the right place to have an help:
https://github.com/qbittorrent/search-plugins/issues/92

what do you think..?
is that the right place..?
thxs cheers

**Comment by garfield69** [comment]
The whole point of the qBitTorrent plugin that you are using, is so that you can search for torrents on qBitTorrent via any of the Jackett indexers that you set up to access the relevant torrent web sites.
No Jackett = no point using the qbittorrent plugin.

**Comment by p060477** [comment]
what you really mean : "no jackett"...?...that jackett has to be INSTALLED in the pc..??..if so what is its .py and it .jason files worth on qbittorrent search plugins..??..all the plugins works fine..except of jackett..and NO plugin is installed...so why this weird strange behaviour about jackett??

**Comment by garfield69** [comment]
do you understand what jackett is for?
Jackett works as a proxy server: it translates queries from apps (Sonarr, Radarr, SickRage, CouchPotato, Mylar, Lidarr, DuckieTV, qBittorrent, Nefarious etc.) into tracker-site-specific http queries, parses the html response, then sends results back to the requesting software. This allows for getting recent uploads (like RSS) and performing searches. Jackett is a single repository of maintained indexer scraping & translation logic - removing the burden from other apps.

qBitTorrent is a torrent client. it performs the actual data transfer of files using magnet or .torrent files.
But before you can start a download you have to provide a magnet or a .torrent.
The plugin for qBitTorrent that you are trying to use allows you to search for magnet or .torrent files, using Jackett as the proxy search engine.

So yes, in order to use the qBitTorrent plugin, you first need to install the Jackett app, then add what ever web site indexers to want to search magnets or .torrents with, and then you will be able to do so directly from qBitTorrent instead of browsing web sites directly via your browser.

**Comment by p060477** [comment]
so if it must be INSTALLED it should be CLEARLY stated in the qbittorent search plugins GitHub web page..
cause is the really THE ONLY one ,among the -ALL search plugins-,
that has this very weird and so strange behaviour

**Comment by garfield69** [comment]
As I have mentioned before, we (the Jackett team) have nothing to do with the qBitTorrent app or any of the Plugins that are created by volunteers for the qBitTorrent app.

**Comment by p060477** [comment]
..but they use yrs app's name...and its aim...
so the confusion is really near round the corner..

**Comment by p060477** [comment]
if -all- the search plugins really DONT need to be installed except jackett the situation,as you can imagine, is really weird and strange..

**Comment by p060477** [comment]
the Tor project use mozilla firefox as browser..and if there was an issue or bug or problem i really was able to post a topic on -mozilla forum- and i was helped without any scuses...
