### ISSUE TITLE
[req] add new polish indexer cool-torrent.pl

### ISSUE THREAD

**Issue by lukjod** [Jackett/Jackett#9105]
Request

Can You please add a nice Polish indexer
http://cool-torrent.pl

**Comment by garfield69** [comment]
is the site semi-private, or is it a private site with temporary open registration?

**Comment by lukjod** [comment]
its semi private with free open registration

**Comment by lukjod** [comment]
Big thank You

**Comment by garfield69** [comment]
Jackett 0.16.817

**Comment by ilike2burnthing** [comment]
http://cool-torrent.pl/
```
Not Found
The requested URL was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an
ErrorDocument to handle the request.
```

**Comment by garfield69** [comment]
I'm seeing
```
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```

**Comment by ilike2burnthing** [comment]
Yea, I'm getting that 503 error now too

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> http://cool-torrent.pl/
> 
> ```
> Not Found
> The requested URL was not found on this server.
> Additionally, a 404 Not Found error was encountered while trying to use an
> ErrorDocument to handle the request.
> ```

**Comment by lukjod** [comment]
Its back online

**Comment by ilike2burnthing** [comment]
http://cool-torrent.pl/ - ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
I don't see the point. The site gives the appearance of having been abandoned. There are no new torrents since 2019, login returns    not found as does the registration page once completed., comments and forum have not been updated since 2019.
It looks like a private site that is improperly switched to public.
looks dead to me.
