### ISSUE TITLE
[torrentday] Add some more site addresses

### ISSUE THREAD

**Issue by niftienev** [Jackett/Jackett#9106]
The current Jackett Site addresses for Torrentday have all been blocked by Australia Gov. 

Please update, the one I am using is torrentday.cool.  There are many others.

Or let me know how I can add it. Making a json file for Iptorrents works for me but not for torrentday

Thanks.

### Environment 

**OS**: Unix

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
@garfield69 the 3 proxies removed in https://github.com/Jackett/Jackett/commit/d6a412b01d5ab8548d017506ce521386c9f5e067 due to `looping on cloudflare checking page` seem to be up again, though I'm only going as far as the login page. Are you able to confirm they're definitely working and re-add?
https://tday.love/
https://torrentday.cool/
https://torrentday.it/

**Comment by garfield69** [comment]
not me. the only team members that have an account on torrentday are @ngosang  and @RoloSoze

**Comment by RoloSoze** [comment]
@ilike2burnthing I can access the website via all 3 URLs that you mentioned.

@garfield69 It's a C# indexer but if you need an invite, let me know.

**Comment by garfield69** [comment]
no that's fine. if the 3 sitelinks you tested are good I can add them back in no problem.

**Comment by RoloSoze** [comment]
> 
> 
> no that's fine. if the 3 sitelinks you tested are good I can add them back in no problem.

Yes, I tested all 3 in Jackett as well, and they all work fine.

**Comment by niftienev** [comment]
Maybe it is Qnap that is the problem, slow updates.

**Comment by ilike2burnthing** [comment]
Might be worth changing to the Docker image instead - https://github.com/linuxserver/docker-jackett

**Comment by niftienev** [comment]
I did and it made no difference. I have tried installing your ARM7 version over the QNAP Club version and it gave me the correct version number but the Torrentday indexer still did not have the new sites, see attached pics. I added a json file the same way I did for IPTorrents 2 years ago and that did not work either.
![Jackett 01](https://user-images.githubusercontent.com/35582574/86849035-69ed4f00-c0f2-11ea-9f44-c66a0d4959b5.jpg)
![Jackett 02](https://user-images.githubusercontent.com/35582574/86849065-75407a80-c0f2-11ea-847b-2b5f6ec2cf0e.jpg)

**Comment by garfield69** [comment]
the new sitelinks were loaded with 0.16.800

**Comment by niftienev** [comment]
Thanks for that garfield69, but that does not help as I cannot install it. But I will try again.

**Comment by ilike2burnthing** [comment]
The Docker image is on v0.16.800, I'm using it and it has those restored URLs. It was updated 15hrs ago, when did you try it?

When you scroll to the bottom, does it say `Jackett Version 0.16.800.0`?

**Comment by niftienev** [comment]
Thanks. I will try today.

**Comment by niftienev** [comment]
Hi again, we will get there or die trying.

I killed everything including the Jackett directory. I downloaded 0.16.800 (Jackett.Binaries.LinuxARM32.tar.gz)

Extracted to .qpkg 
Set permissions

As per the instructions ran ./jackett

It does not exist.

**Comment by ilike2burnthing** [comment]
Next up, Docker!
