### ISSUE TITLE
[Req] darmowe torenty

### ISSUE THREAD

**Issue by lukjod** [Jackett/Jackett#9115]
I have request to add decent polish tracker https://darmowe-torenty.pl/
it is semi private with open registration torrent indexer

**Comment by garfield69** [comment]
Jackett 0.16.821

**Comment by lukjod** [comment]
Thank You very much

**Comment by ilike2burnthing** [comment]
https://darmowe-torenty.pl/
```
Forbidden - You don't have permission to access / on this server.
```

https://darmowe-torenty.pl/torrenty.php?search=&category=0
```
Not Found
The requested URL /torrenty.php was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an
ErrorDocument to handle the request.
```

**Comment by lukjod** [comment]
back online

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://darmowe-torenty.pl/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://darmowe-torenty.pl/ - Error 522 - Connection timed out

**Comment by garfield69** [comment]
https://darmowe-torenty.pl/ - Error 521 - Web server is down

**Comment by garfield69** [comment]
online
but jackett returning

Exception (darmowetorenty): Specified argument was out of the range of valid values. (Parameter 'index'): Parse error

**Comment by garfield69** [comment]
more details
```
Error on 20210726173921 for Darmowe torenty.txtSystem.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at AngleSharp.Common.ObjectExtensions.GetItemByIndex[T](IEnumerable`1 items, Int32 index)
   at AngleSharp.Dom.HtmlCollection`1.get_Item(Int32 index)
   at Jackett.Common.Indexers.DarmoweTorenty.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\DarmoweTorrenty.cs:line 227




<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```

**Comment by garfield69** [comment]
oops, my bad. was using an incorrect domain when last testing the previous offline state and forgot to reset afterwards.

https://darmowe-torenty.pl/  online and operational.

**Comment by garfield69** [comment]
https://darmowe-torenty.pl/ returning ERR_CANT_CONNECT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://darmowe-torenty.pl/ - very slow to load
https://darmowe-torenty.pl/torrenty.php - Gateway time-out - Error code 504

**Comment by ilike2burnthing** [comment]
very slow, but back up

**Comment by garfield69** [comment]
https://darmowe-torenty.pl/ ERR_CANT_CONNECT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13741#issuecomment-1642636743

**Comment by garfield69** [comment]
v0.21.510
