### ISSUE TITLE
[req] Request on adding a French public indexer: streaming-download.net/

### ISSUE THREAD

**Issue by Puled** [Jackett/Jackett#9119]
http://streaming-download.net/ is a very good website.

**Comment by garfield69** [comment]
this site does not appear to have any direct .torrent or magnet files.
It's also slow as molasses, taking over 30 seconds to present the main page or a title's details page.
links on a title's details page seems to take you to a secondary sites which requires additional page navigation and click bait obstacles.

as such this site is not suitable for use with Jackett.
