### ISSUE TITLE
[jpopsuki] Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by handlerdigits** [Jackett/Jackett#9125]
## Environment

**Jackett Version**: 0.16.814.0

### Description

I have no idea what #9074 was doing. After updating with these changes, jpopsuki no longer works. Reverting this PR completely causes jpopsuki to function correctly. Below are the logs with the current (broken) jpopsuki definition.

### Logged Error Messages

[jpopsuki_fail_log.txt](https://github.com/Jackett/Jackett/files/4899387/jpopsuki_fail_log.txt)

**Comment by garfield69** [comment]
@KaiSforza  this issue likely caused by your last PR. Please investigate. Thanks.

**Comment by Peechaya** [comment]
Having the same error afin updating Jackett.

**Comment by garfield69** [comment]
I don't have an account on this site, so I cannot independently test and research.
But looking at the log provided, it appears that for some reason @KaiSforza  is not seeing an extra field neat the top of the search results row that @handlerdigits  and @Peechaya  are getting.
Presumably this is due to either a difference in user status, or some profile option setting.
The indexer has been set up  to be hard-coded to select the fields in a row by counting from the top down.

I propose counting from the bottom up which should account for the differences between your row results. The change should be included in the next release of Jackett due in about 12 hours or so.

**Comment by garfield69** [comment]
Jackett 0.16.821

**Comment by handlerdigits** [comment]
@garfield69 just updated to 0.16.821 and it's still not working. Looks like this line is causing the issue: https://github.com/Jackett/Jackett/commit/4e5efb08594eff6f6dd191f565dabb34222c525a#diff-79f743519cf5d89e9ecbfb40aca4732eR62

That ends up searching for the literal tag '0' in the default 'Any' mode which leads to no results.

It looks like the option you were looking for is `tags_type=0` which is tag in 'Any' mode, where `tags_type=1` is tag in 'All' mode (at least on jpopsuki).


At this point it might be worth noting that using ajax.php might be a better option here since it will just give you the results table rather than the whole site. The jpopsuki.yml definition says it's disabled, but the url just needs an additional `section=torrents` query parameter to work properly with ajax.php (all the other query parameters from torrent.php remaining the same). When you use the actual 'search' button through the site on torrents.php in a browser, it's making a call to ajax.php, not torrents.php

Hitting the ajax.php with these parameters produces the following HTML which is a lot simpler to parse through than the torrents.php which renders the whole site as it's meant for the whole web page in a browser:

`https://jpopsuki.eu/ajax.php?section=torrents&searchstr=&order_by=s3&order_way=desc&disablegrouping=1`

[jpopsuki_ajax_query_html.txt](https://github.com/Jackett/Jackett/files/4906457/jpopsuki_ajax_query_html.txt)

**Comment by garfield69** [comment]
reopened pending #9131

**Comment by garfield69** [comment]
according to https://github.com/Jackett/Jackett/pull/9131#issue-447741118
keywordless searching is an issue on this site.
But we are going to need a search string that will provide results for the TEST button.
Usually we do a keywordless search, but if that is not available, we could do a search for `2020` or some other keyword that is relevant at the site such as `mp3` perhaps?
Can someone suggest a search term that will generally bring up the latest results?

**Comment by handlerdigits** [comment]
mp3 doesn't really work, but 2020 works great, showing anything that was uploaded in 2020, or that has 2020 in the title, so there will always be plenty of results with that search term

**Comment by garfield69** [comment]
Available in the next release due out in about 4 hours or so.
Please check that the Jackett dashboard TEST for the indexer works, and that searches are returning results. Thanks.

**Comment by garfield69** [comment]
Jackett 0.16.836

**Comment by handlerdigits** [comment]
seems to work fine now both for the test button and manual searching

**Comment by Peechaya** [comment]
It's working fine for me as well now. Thank you so much for the quick fix!
