### ISSUE TITLE
[req] 4movierulz https://4movierulz.mx/ public 

### ISSUE THREAD

**Issue by narniamandela** [Jackett/Jackett#9138]
Add Index https://4movierulz.mx/

**Comment by garfield69** [comment]
HOLLYWOOD, BOLLYWOOD, TAMIL, TELUGU, MALAYALAM
site has a multiple magnet releases under the one torrent title on its details page
will require the indexer to be written in c#

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
