### ISSUE TITLE
Torrent Leech test does not work

### ISSUE THREAD

**Issue by degardiu** [Jackett/Jackett#914]
When trying to test torrent leech after configuring it in Jackett, an error message is shown. I've took a look at the code and there was a change on torrent leech side and the html returned is a little bit different. 

If you look at TorrentLeech.cs, line 184 you can see it is trying to find the element "span.addedinline", however, that span element is not part of the returned html, I've changed it locally to "td.name" and it seems to be working.

Edgar.

**Comment by kaso17** [comment]
I assume they reverted their change?
For me it's working (again?) using span.addedinline.
Thank you for the PR anyway.
