### ISSUE TITLE
Error while loading Cardigann definitions for tracker t411 from the cardigann repository

### ISSUE THREAD

**Issue by maddestructor** [Jackett/Jackett#916]
Hi! I am having trouble loading the cardigann definition for the tracker T411. 

Here is the error message I am receiving in the log: Error while loading Cardigann definitions: (Line: 50, Col: 7, Idx: 1025) - (Line: 50, Col: 7, Idx: 1025): Expected 'SequenceStart', got 'MappingStart' (at Line: 50, Col: 7, Idx: 1025).

Thanks in advance for your kind help! If I can help you guys in any way, just let me know!

**Comment by kaso17** [comment]
I pushed a minor change to make it compatible to the cardigann repo.
Please redownload the definition, that should fix it.
