### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by paulmaines** [Jackett/Jackett#9160]
### Environment

**OS**:
Linux ARM32
**Jackett Version**:
0.16.838

**Are you using a proxy or VPN?** [yes/no]
no
### Description
Had Jackett installed for months without issue. Today when I visited the web interface, the page loaded, but my indexers don't show, and none of the buttons on the page work. I tried manually reinstalling older versions, in case it was broken by an update, but, for some reason I keep getting the same problem.

### Logged Error Messages

from the JS Console, I get the following:

Uncaught SyntaxError: Unexpected token ','
handlebars.min.js?changed=2017083001:27 Uncaught SyntaxError: Invalid or unexpected token
handlebarsmoment.js?changed=2017083001:2 Uncaught ReferenceError: Handlebars is not defined
    at handlebarsmoment.js?changed=2017083001:2
(anonymous) @ handlebarsmoment.js?changed=2017083001:2
handlebarsextend.js?changed=2017083001:1 Uncaught ReferenceError: Handlebars is not defined
    at handlebarsextend.js?changed=2017083001:1
(anonymous) @ handlebarsextend.js?changed=2017083001:1
jquery.min.js?changed=2017083001:2 Uncaught ReferenceError: Handlebars is not defined
    at HTMLDocument.<anonymous> (custom.js?changed=20200410:30)
    at j (jquery.min.js?changed=2017083001:2)
    at k (jquery.min.js?changed=2017083001:2)
(anonymous) @ custom.js?changed=20200410:30
j @ jquery.min.js?changed=2017083001:2
k @ jquery.min.js?changed=2017083001:2
setTimeout (async)
r.readyException @ jquery.min.js?changed=2017083001:2
(anonymous) @ jquery.min.js?changed=2017083001:2
j @ jquery.min.js?changed=2017083001:2
k @ jquery.min.js?changed=2017083001:2
setTimeout (async)
(anonymous) @ jquery.min.js?changed=2017083001:2
i @ jquery.min.js?changed=2017083001:2
fireWith @ jquery.min.js?changed=2017083001:2
fire @ jquery.min.js?changed=2017083001:2
i @ jquery.min.js?changed=2017083001:2
fireWith @ jquery.min.js?changed=2017083001:2
k @ jquery.min.js?changed=2017083001:2
setTimeout (async)
(anonymous) @ jquery.min.js?changed=2017083001:2
i @ jquery.min.js?changed=2017083001:2
fireWith @ jquery.min.js?changed=2017083001:2
fire @ jquery.min.js?changed=2017083001:2
i @ jquery.min.js?changed=2017083001:2
fireWith @ jquery.min.js?changed=2017083001:2
ready @ jquery.min.js?changed=2017083001:2
R @ jquery.min.js?changed=2017083001:3

**Comment by garfield69** [comment]
check your browser plugins or web anti-malware ... could it be preventing handlebarsmoment.js from being loaded or its getting blocked?
access your Jackett dashboard and press F12, then click on the source tab
see handlebarsmoment.js in the libs?
![image](https://user-images.githubusercontent.com/6933240/87729787-47f27b80-c81a-11ea-8237-75fd33e42707.png)

**Comment by garfield69** [comment]
or handlebars.min.js
![image](https://user-images.githubusercontent.com/6933240/87730037-d535d000-c81a-11ea-90d0-936be6649456.png)

**Comment by paulmaines** [comment]
Yes, handlebars.min.js was loaded, but I was still getting an error. Can't be a browser issue, as the browser settings never changed. It now seems to have corrected itself since the last update though, so this matter can be closed.

**Comment by garfield69** [comment]
possibly the copy of the JS in your browser cache was corrupted, and a refresh may have occurred to load a clean one...

**Comment by paulmaines** [comment]
on 3 browsers across 2 devices? I would consider that unlikely

**Comment by garfield69** [comment]
yes you are right. you didn't mention this in your prior report.
in which case that is a very strange error.
we last changed those scripts back in 2017

**Comment by paulmaines** [comment]
I think it was possibly caused by a corrupted file somewhere. Over the last 24 hours I have found a few corrupted files. Running on a Pi 4. Gonna switch to USB drive, as there are too many issues with SD.
