### ISSUE TITLE
NewPCT indexer fails because of a change in the website

### ISSUE THREAD

**Issue by egrueda** [Jackett/Jackett#9164]
NewPCT (aka: tvsinpagar, descargas2020, torrentlocura, torrentrapid, tumejortorrent, pctnew, etc) is not working.
Main domain descargas2020.com returns a "301Moved Permanently"
It auto-redirects to https://pctnew.org/ wuthout url parameters.
Hope you can adapt the new domain name from descargas2020.org to pctnew.org
Thanks!

**Comment by ilike2burnthing** [comment]
https://descargas2020.com/
```
Nos hemos mudado, ahora estamos en: https://dontorrent.org/
We have moved, now we are in: https://dontorrent.org/
```
https://dontorrent.org/ - working
https://pctnew.org/ - Error 522 - Connection timed out

**Comment by egrueda** [comment]
Sorry, not .com but .org
descargas2020.org

**Comment by garfield69** [comment]
none of the domains are working.
https://pctreload.com/ returning ERR_CONNECTION_REFUSED
https://pctnew.org/ returning ERR_CONNECTION_REFUSED
https://descargas2020.org/ redirecting to https://pctnew.org/

so none of the available sitelinks are working for me.
https://descargas2020.com/ (a previous legacylink) redirects to https://dontorrent.org/ but this domain generates a **Clearance failed after 10 attempt(s)** error for me.

does anyone have a working domain?

**Comment by ilike2burnthing** [comment]
All 3 current domains are back up now

**Comment by garfield69** [comment]
really. i get for all three via my chrome browser **Error 521 Web server is down**

**Comment by ilike2burnthing** [comment]
Current notice on the sites:
```
Si tienes problemas para visualizar el contenido , actualiza la web Ctrl+F5 y descargate lo nuevo !!!!
If you have trouble viewing the content, update the website Ctrl+F5 and download the new !!!!
```
I've opened these in a private session as well, working fine.

**Comment by garfield69** [comment]
okely dokely.

**Comment by egrueda** [comment]
@garfield69 You are right, yesterday all "group" sites were having intermitente stability issues.
Today I can access https://descargas2020.org/ without the 301 redirect.
So nevermind, nothing to do :-D
Thank you any way.
