### ISSUE TITLE
ProWrestlingTorrents not pulling results

### ISSUE THREAD

**Issue by b101marc** [Jackett/Jackett#9167]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.849.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

When adding PWT tracker to Sonarr, no results are pulling but the tracker it working.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
I don't think pwt is suitable for use with Sonarr.
example: Sonarr looks for `All Elite Wrestling Dynamite S02E29` and `AEW Dynamite S02E29`
but the site only has titles like `All.​Elite.​Wrestling.​Dynamite.​2019.​12.​18` and `AEW.​Dynamite.​2020.​07.​15`
