### ISSUE TITLE
Releases showing in logs but not in Sonarr/CP

### ISSUE THREAD

**Issue by bigjohns97** [Jackett/Jackett#917]
Maybe I am not doing this correctly but i followed the install instructions and everything tests ok in each application but when i try and do a manual search (initiated from the app) i show 50 releases in the logs of Jackett but i never see the releases show up in CP or Sonarr.

**Comment by kaso17** [comment]
please post a log

**Comment by bigjohns97** [comment]
CP log
01-05 13:56:55
INFO
[ie.providers.info.omdbapi] Found: Doctor Strange (2016)
01-05 13:56:55
INFO
[core.media.movie.searcher] Search for Doctor Strange in 1080p ignoring ETA
01-05 13:56:56
INFO
[core.media.movie.searcher] Search for Doctor Strange in 720p ignoring ETA
01-05 13:56:56
INFO
[core.media.movie.searcher] Search for Doctor Strange in BR-Rip ignoring ETA
01-05 13:56:56
INFO
[edia._base.providers.base] Found: score(79) on Newznab, api.nzbgeek.info: Doctor.Strange.(2016). HDRip.x264.AC3-CPG
01-05 13:56:56
INFO
[edia._base.providers.base] Found: score(78) on Newznab, api.nzbgeek.info: Doctor Strange 2016 HDRip XviD AC3-EVO
01-05 13:56:56
INFO
[tato.core.plugins.release] Ignored: Doctor.Strange.(2016). HDRip.x264.AC3-CPG
01-05 13:56:56
INFO
[tato.core.plugins.release] Ignored: Doctor Strange 2016 HDRip XviD AC3-EVO
01-05 13:56:56
INFO
[core.media.movie.searcher] Search for Doctor Strange in DVD-R ignoring ETA
01-05 13:56:56
INFO
[core.media.movie.searcher] Search for Doctor Strange in DVD-Rip ignoring ETA
01-05 13:56:56
INFO
[core.media.movie.searcher] Search for Doctor Strange in Screener ignoring ETA

Jackett
Jan 05, 2017 01:56:42 PM	Info	
Found 50 (1 new) releases from IPTorrents

**Comment by kaso17** [comment]
CP ignores the results as Doctor Strange hasn't been yet released officially ("ignoring ETA"). You can disable that somewhere in CP.
