### ISSUE TITLE
[Bug] Elite-Tracker: Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#918]
Enhanced log attached. Also, when trying to reconfigure the indexer, I get a 'Configuration failed' error. 
[log.txt](https://github.com/Jackett/Jackett/files/688877/log.txt)

**Comment by maxcore** [comment]
same way for me and @bourgeois

**Comment by kaso17** [comment]
fixed with 08b3ba0f02ea272f1c33f4ee24440de9765d522d

**Comment by maxcore** [comment]
thx @kaso17
