### ISSUE TITLE
[REQ]torrentmafya.org

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#9181]
Turkish movie share torrent site.
Link: https://www.torrentmafya.org/
Search engine and magnets running.
Site is have big database.

**Comment by garfield69** [comment]
site has a one title one many torrents structure, so this indexer will need to be written in c#

**Comment by ertugrulk** [comment]
Hey  @garfield69 , I can take this one as well.

**Comment by garfield69** [comment]
Contributions are always welcome. Thank you.

**Comment by garfield69** [comment]
Jackett 0.16.1724

**Comment by ilike2burnthing** [comment]
https://www.torrentmafya.org/ - Error 1020 - Access denied
Same when using VPN.
403 Forbidden - https://www.uptrends.com/tools/uptime?toolRequestGuid=37b0b299-3ed5-485b-9356-f401f41e7820

**Comment by ilike2burnthing** [comment]
https://www.torrentmafya.org - ERR_NAME_NOT_RESOLVED

**Comment by garfield69** [comment]
@berat1397  Do  you know if this site is gone, broken or moved to a new domain?
It will be removed in a weeks time if we get no news.

**Comment by garfield69** [comment]
v0.20.929
