### ISSUE TITLE
Stuck on activating systemd service

### ISSUE THREAD

**Issue by kcanterbury11** [Jackett/Jackett#9182]
I have been trying to get this installed on a new CentOS 8 VM with no luck. I had it working previously but had to rebuild this VM.

● jackett.service - Jackett Daemon
   Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) since Sat 2020-07-18 20:06:42 EDT; 4s ago
  Process: 28547 ExecStart=/bin/sh /apps/jackett/jackett_launcher.sh (code=exited, status=0/SUCCESS)
 Main PID: 28547 (code=exited, status=0/SUCCESS)
~
I followed the Install on Linux (AMDx64) the run it as a service.

**Comment by ngosang** [comment]
Paste the contents of `/etc/systemd/system/jackett.service`
What happens if you run `/bin/sh /apps/jackett/jackett_launcher.sh` in the shell?

**Comment by kcanterbury11** [comment]
[Unit]
Description=Jackett Daemon
After=network.target

[Service]
SyslogIdentifier=jackett
Restart=always
RestartSec=5
Type=simple
User=kristin
Group=kristin
WorkingDirectory=/apps/jackett
ExecStart=/bin/sh /apps/jackett/jackett_launcher.sh
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target


[kristin@kserver log]$ /bin/sh /apps/jackett/jackett_launcher.sh 
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_InvariantCulture()
   at CommandLine.ParserSettings..ctor()
   at CommandLine.Parser..ctor(System.Action`1<CommandLine.ParserSettings>)
   at Jackett.Server.Program.Main(System.String[])
/apps/jackett/jackett_launcher.sh: line 10: 1029741 Aborted                 (core dumped) "${JACKETT_DIR}/jackett" --NoRestart "$@"

**Comment by ngosang** [comment]
I think you have to install the library `libicu` in your system. => https://pkgs.org/search/?q=libicu

https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos#dependencies

**Comment by kcanterbury11** [comment]
Yup, that worked!
