### ISSUE TITLE
[XbytesV2] Auto-login when the cookie expires is not working

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9200]
After 1 month, the tracker XbytesV2 returns 0 results in every request (without errors). I have to open the tracker configuration and click "okay" to do manual login. Will be nice if we can enable auto-login (detect the logout). I think we already have this feature in other xbtitFM trackers.

**Comment by garfield69** [comment]
I don't have an account on this site.
please confirm that index.php has an `a[href="logout.php"]` and I'll add it to the login test section.
