### ISSUE TITLE
btdb: unexpected result

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9201]
I don't know why there is a result called "email protected". Maybe is not our fault. Could you check it?
This is the torrent in the site. It has title => https://btdb.eu/search/33D6320BBA/0/
![image](https://user-images.githubusercontent.com/10577978/88102792-6d77e000-cba0-11ea-8205-99de4055eb5f.png)

**Comment by garfield69** [comment]
this is the web site. is uses JS to obfuscate the title because it contains an `@`
```html
<a href="//btdb.eu/torrent/8cf7d367f20a94f7294fbfbe21b0c0232dd698a9" title="Harry.Potter.Blu-ray.1080p.33D6320BBA@okfun.org"><span class="__cf_email__" data-cfemail="3d755c4f4f44136d524949584f137f5148104f5c44130c0d050d4d130e0e790b0e0f0d7f7f7c7d52565b485313524f5a">[email&#160;protected]</span></span></a>
```
I'll change the indexer to use the title attribute, which should solve the issue.
