### ISSUE TITLE
rutracker: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9203]
![image](https://user-images.githubusercontent.com/10577978/88104450-bc267980-cba2-11ea-8a37-632ff7273d8e.png)

![image](https://user-images.githubusercontent.com/10577978/88104496-ccd6ef80-cba2-11ea-862e-c2f075e4bf66.png)

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/93014596-9ae67600-f5b2-11ea-842d-096fa74b2bfc.png)
![image](https://user-images.githubusercontent.com/10577978/93014614-b2256380-f5b2-11ea-8b16-b57097001592.png)
![image](https://user-images.githubusercontent.com/10577978/93014618-bb163500-f5b2-11ea-8ce8-d633d0a79d05.png)
![image](https://user-images.githubusercontent.com/10577978/93014625-cb2e1480-f5b2-11ea-8102-b102b0490e9d.png)

**Comment by ngosang** [comment]
Query: Бондарчук

![image](https://user-images.githubusercontent.com/10577978/95511243-7c0faf80-09b7-11eb-9c66-b6b81700103e.png)

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/97791784-6b2d1500-1bd6-11eb-95bd-621d60b366c0.png)

**Comment by garfield69** [comment]
pending #7526
