### ISSUE TITLE
torrenthane: invalid download links

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9205]
Empty search. Eg:
![image](https://user-images.githubusercontent.com/10577978/88104836-4f5faf00-cba3-11ea-8505-da66af10afd6.png)

**Comment by garfield69** [comment]
The site has switched to presenting one title many torrents.
The indexer will need to be rewritten in c#.
closing this ticket in favour of #7853 
the yml indexer for this site will be removed.
