### ISSUE TITLE
[movcr] Exception (movcr): Got redirected to another domain. Try changing the indexer URL to https://movcr.st/.: Parse error (Test)

### ISSUE THREAD

**Issue by hemlok89** [Jackett/Jackett#9212]
### Environment

**OS**: Windows 10 2004

**Jackett Version**: 0.16.891.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** No

### Description

The site MovCr.to has changes to MovCr.st.

**Comment by garfield69** [comment]
#9210 resolves. 
the next release of jackett in about 10 hours or so will auto-correct.
in the mean time you can edit the indexer config with your dashboard and change the site link manually to access the new domain.
