### ISSUE TITLE
[World of Tomorrow] upgraded the frontend

### ISSUE THREAD

**Issue by luebke-dev** [Jackett/Jackett#9213]
world-of-tomorrow.eu doesnt work anymore since they upgraded their frontend. registry is open right now

**Comment by garfield69** [comment]
awaiting registration confirmation email.
So far the site has rejected by login attempts.

**Comment by garfield69** [comment]
just noticed `Sorry, das Benutzerlimit wurde erreicht. Bitte versuche es später erneut.` further down in the page.
So it looks like I'm out of luck.

I've submitted an indexer update based on the login panel currently presented, but it is untested  so it may not work. But given that the current indexer is not working anyway its worth a try.
The next Jackett release due in about 10 hours will contain the update indexer.

**Comment by SebastianLuebke** [comment]
what is the name you registered with? i will notify the mods

**Comment by garfield69** [comment]
uid=garfield1969 email=garfieldsixtynine@gmail.com

**Comment by SebastianLuebke** [comment]
closing this, the owners of world of tomorrow dont want jackett to work again.

**Comment by Rafaelrico7** [comment]
@garfield69 I can provide temporary access with an account of mine to this torrent for you. WOT is still in the Jackett Sources, so I think its a good idea to fix it, if you find time for that :)

**Comment by garfield69** [comment]
@Rafaelrico7  thanks, but I just found this https://github.com/Jackett/Jackett/issues/9213#issuecomment-674050876 so I shall be removing WOT from Jackett shortly.

**Comment by garfield69** [comment]
Jackett 0.16.1709

**Comment by LN86** [comment]
registry is open right now. Please look again. Thanks

**Comment by ilike2burnthing** [comment]
@LN86 see https://github.com/Jackett/Jackett/issues/9213#issuecomment-674050876

**Comment by desilent** [comment]
Is there a chance to try this again? According to the owner they updated their system, it just had no prio back then but they are generally open to it.

**Comment by garfield69** [comment]
The only way this is going to happen is if you can persuade WOT admin to reactivate my account which I do not use for personal downloading but only for testing to maintain the WOT Jackett indexer.
If they don't agree then you have your answer ;-)

`uid=garfield1969 email=garfieldsixtynine@gmail.com`

**Comment by desilent** [comment]
> The only way this is going to happen is if you can persuade WOT admin to reactivate my account which I do not use for personal downloading but only for testing to maintain the WOT Jackett indexer. If they don't agree then you have your answer ;-)
> 
> `uid=garfield1969 email=garfieldsixtynine@gmail.com`

I'm on it - will get back with results

**Comment by desilent** [comment]
> The only way this is going to happen is if you can persuade WOT admin to reactivate my account which I do not use for personal downloading but only for testing to maintain the WOT Jackett indexer. If they don't agree then you have your answer ;-)
> 
> `uid=garfield1969 email=garfieldsixtynine@gmail.com`

Can you try to login again? I had it reactivated.

**Comment by garfield69** [comment]
Confirming I've been re-activated. I'll start work on the replacement indexer.

**Comment by garfield69** [comment]
v0.20.1845

**Comment by desilent** [comment]
Hi garfield69, works fine except for OnlyUpload. If the filter is checked, no torrents can be found. Do you have a fix for this? Or a solution I can communicate to the admins?

Thanks again btw.

**Comment by garfield69** [comment]
@desilent it appears that the browse.php page on the web site is not showing the OnlyUpload flag in its result row despite some of torrents having this flag enabled in their details page, so perhaps there is a problem or omission in showing OnlyUpload and FreeLeech flags at the site?

**Comment by virusperfect** [comment]
They completely reworked the site. The new url is: wotreworked.xyz. Currently both the new and old site (world-of-tomorrow.eu) are online but eventually they will turn off the old site.

Registered users should be able to login into the new site. If that doesn't work you should write the team ("Team Nachricht") on the old site and they will send you new credentials.

Would be nice if you could try getting the new site working.

**Comment by fr31wild** [comment]
Hallo Garfield, bitte melde dich bitte bei uns support@world-of-tomorrow.eu wegen der API (Sonarr usw)

**Comment by garfield69** [comment]
@fr31wild  I have sent an email to [support@world-of-tomorrow.eu](mailto:support@world-of-tomorrow.eu) but have yet to receive a reply.
In the mean time I have update the Jackett indexer for use with the new domain. It will be published in the next release of Jackett.

**Comment by garfield69** [comment]
v0.20.3127

**Comment by w0d4** [comment]
Hi, world-of-tomorrow again changed their URL.
The new one is w-o-t.pro
It would be great if this could be implemented.
It seems to be the same software revision as with the last old URL wotreworked.xyz

**Comment by garfield69** [comment]
v0.20.3411

**Comment by siam7th** [comment]
Halli Hallo, ich kann mich nicht mehr einloggen bei  WOT ... weder bei der alten noch der neuen domain ... kann mir bitte jemand helfen .. mein username war siam7 ... vielen dank im voraus für die hilfe

**Comment by ilike2burnthing** [comment]
If you mean you can't log into the site itself, use their support form.

If you mean you can't add the WOT indexer in Jackett, open a new issue and provide the information requested.

**Comment by siam7th** [comment]
@ilike2burnthing 
thank you for your answer. 
i cant login into the site nor at the support form. 
i filled it out multiple times ... but nothing happens. 
i am member since many years.
https://w-o-t.pro/login.php?login

**Comment by garfield69** [comment]
There is nothing we can do for you here. 
We are not a support site for WOT, we support the Jackett indexer which we wrote to access the WOT site.

**Comment by garfield69** [comment]
I'll update the indexer. It does appear that they have renumbered the categories.

**Comment by garfield69** [comment]
As for the freeleech and onlyupload flags not working, the web site has enabled global OnlyUpload, which does not show up on the torrent rows of the search page results. So the Indexer is not able to detect this.
And none of the rows are currently showing FreeLeech either. So there is nothing we can do about that.

**Comment by garfield69** [comment]
v0.21.1585

**Comment by garfield69** [comment]
v0.22.84

**Comment by garfield69** [comment]
@Mayflower7482  all the cats on the WOT indexer were updated to 4 digits 6 months ago, beginning with Jackett version v0.21.1585
We are currently on v0.22.393
Update your Jackett.
OR if you are seeing this on one of the *arr apps, delete that apps indexer for WOT, restart the app to flush its cache, and add the indexer afresh to pick up the new cats.

**Comment by garfield69** [comment]
Yeah.  The indexer was working for me when I checked before replying to your original post, but now it is also returning no results, so it looks like we will need to see if the indexer can be updated for the new search engine.

**Comment by garfield69** [comment]
v0.22.404
