### ISSUE TITLE
Add check box to select multiple torrent URL [feature request]

### ISSUE THREAD

**Issue by alculete** [Jackett/Jackett#9214]
### Environment

**OS:** Ubuntu-server 20.04 LTS x86_64 
**Host:** HP Compaq 6200 Pro MT PC 
**Kernel:** 5.4.0-40-generic 
**Shell:** bash 5.0.17 
**Terminal:** /dev/pts/1 
**CPU:** Intel i3-2120 (4) @ 3.300GHz 
**GPU:** Intel 2nd Generation Core Processor Family 
**Memory:** 3234MiB / 7849MiB 

**Are you using a proxy or VPN?** [no]

### Description

When adding torrent URLs I have to add one by one and always return to the main page. Please add a checkbox to select all URLs at once.

**Comment by ngosang** [comment]
This request is not clear to me. You mean checkboxes to download more than 1 torrent at once?

**Comment by ilike2burnthing** [comment]
I assume they were referring to indexers, given the description of it returning to the main page upon adding one, i.e. https://github.com/Jackett/Jackett/issues/7311

**Comment by alculete** [comment]
Yes, that's it @ilike2burnthing

**Comment by ilike2burnthing** [comment]
OK, you can follow that request and we'll close this one.
