### ISSUE TITLE
[totheglory] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#9220]
### Logged Error Messages
```
07-23 12:51:54 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://totheglory.im/login.php?returnto=) 
07-23 12:51:55 Debug __cfduid=d30db541bc3199505e8f6057e139e0ec51595497915; expires=Sat, 22-Aug-20 09:51:55 GMT; path=/; domain=.totheglory.im; HttpOnly; SameSite=Lax; Secure 
...
07-23 12:51:55 Debug CardigannIndexer (totheglory): Cookies after login: __cfduid=d30db541bc3199505e8f6057e139e0ec51595497915 
07-23 12:51:56 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://totheglory.im/my.php) 
07-23 12:51:56 Debug WebClient(HttpWebClient2NetCore): Returning Redirect => https://totheglory.im/login.php?returnto=%2Fmy.php  
```

**Comment by garfield69** [comment]
you are aware that cookies expire based on what ever period the web site sets.
Have you tried refreshing your cookie?

**Comment by dimqua** [comment]
No. How can I do this?

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work

**Comment by dimqua** [comment]
@garfield69 but there's no field to enter cookie string:
![](https://i.imgur.com/eLViJ07.png)

**Comment by garfield69** [comment]
sorry. didn't check.
I presume you filled in the user ans pswd and left the 2fa empty unless you enabled it on the site?
then login to the site with your browser and confirm that your credentials are good, that your ratio is good and that nothing is preventing you accessing the torrents search page.
its possible there is a system alert or notices or perhaps unread PM that you must read before accessing the torrents search page?

**Comment by dimqua** [comment]
> I presume you filled in the user ans pswd and left the 2fa empty unless you enabled it on the site?

Yes.

> nothing is preventing you accessing the torrents search page.

When I login I always redirected to `/my.php`, I don't know why.

**Comment by garfield69** [comment]
well the indexer is expecting the first page after login to be my.php so that is fine.
but after that you should be able to access browse.php

Do you mean the site will not let you out of the my.php page?
perhaps it is expecting you to update your profile... are you missing some setting (city, birthday, other personal details) that is being highlighted in red or something, or perhaps its expecting you to change your password?
There should be some highlighted message requesting this on that page I would have thought...

**Comment by dimqua** [comment]
> Do you mean the site will not let you out of the my.php page?

No, I'm able to access browse.php

**Comment by dimqua** [comment]
Besides (if I understand it correctly), browse.php access isn't required for login, but rather for retrieving search results. And I'm unable to login...

**Comment by garfield69** [comment]
the indexer tries to log you in with the form at login.php?returnto=, then checks that login did not generate specific errors, then checks for the presence of the my.php page, and if found then tries to access the browse.php to retrieve a search.

please provide a full **enhanced** log which will have debug message s and html sent by the site,  so I can hopefully see what might be going on.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by dimqua** [comment]
https://github.com/Jackett/Jackett/files/4971285/log.txt

**Comment by garfield69** [comment]
@RoloSoze  is the totheglory indexer working for you?

**Comment by RoloSoze** [comment]
@garfield69 It's working fine, yes.

**Comment by garfield69** [comment]
dimqua are you using 2fa or the security question?
given that it is working for RoloSoze we can presume the issue is specific to your setup somehow.
I'll dive into the log later and see if I can glean something, but a quick look just now did not smack me in the face with anything obvious. :-(

**Comment by garfield69** [comment]
also, are you using a vpn or proxy?
what version of jackett, and on what platform?

**Comment by dimqua** [comment]
I don't use 2fa, only the security question. I tried to disable it, but it didn't help.

**Comment by garfield69** [comment]
@RoloSoze  are you using 2fa or the security question during your login, or just plain user / pswd?

**Comment by garfield69** [comment]
@dimqua  when you use the browser to login, what language have you set on the login page?

**Comment by RoloSoze** [comment]
> 
> 
> @RoloSoze are you using 2fa or the security question during your login, or just plain user / pswd?

Plain username & password only. No 2FA, no security questions, no VPN or proxy. Jackett 0.16.896 on Windows 10 Pro 64-bit. I don't recall ever having any configuration or login issues with TTG in Jackett.

**Comment by garfield69** [comment]
@dimqua something to try
access your jackett dashboard and trashbin your totheglory config.
shutdown and restart your jackett service
access the dashboard and add totheglory afresh
see if that helps.

**Comment by dimqua** [comment]
@garfield69 I have no config since I can't login.
Could you add a support of cookieId login? Who knows probably it can resolve my issue.

**Comment by garfield69** [comment]
@dimqua  try out totheglorycookie with Jackett 0.16.909 and see if that helps you.

**Comment by dimqua** [comment]
@garfield69 wow, it works! Thanks.
