### ISSUE TITLE
aftershock server IP address could not be found.

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#9221]
https://aftershock-tracker.eu/ returning server IP address could not be found.
Has the site gone, is broken, or moved to a new domain?

**Comment by garfield69** [comment]
registrar status: Quarantine
This name is currently unavailable because it is quarantined. A domain name holder may decide to give up a name and delete its registration. When that happens, the domain name is put into a 40-day quarantine as a safety measure.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
needs .eu -> .net sitelink update

**Comment by garfield69** [comment]
Jackett 0.16.938
