### ISSUE TITLE
how to use the not-installed / portable .zip jackett

### ISSUE THREAD

**Issue by p060477** [Jackett/Jackett#9228]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
win 10 home 64
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

hi i've dl the .zip choice for win 10
how to use it?
i ask cause i want to have my jackett search-plugin of qbittorrent finally working..
so i've to put in browser 
http://127.0.0.1:9117
open the jackett UI
and have my api key to put in jackett.jason file of qbittorrent 4.2.5:
{
"api_key": "YOUR_API_KEY_HERE",
"tracker_first": false,
"url": "http://127.0.0.1:9117"
}

thxs in adv

**Comment by garfield69** [comment]
The zip archive is simply the content of `%ProgramData%\Jackett` 
the only difference as far as I can tell between the zip and the exe downloads, is that the exe installer sets up Jackett ready for use, while the zip just has the binaries so if this is a first time install, you still need to set Jackett up, but you would have to do it manually yourself.

I see no benefits for first time installers in using the zip archive. You are much better off using the exe archive and installing Jackett as a service.

**Comment by p060477** [comment]
hi, first so many thxs for yr kind reply,
i'd like to use jackett in a -portable- way..not to install it..
so i ask you if this is possible..
so i'm asking how to set up jackett -manually-
thxs so much again in advance for yr precious helping

**Comment by garfield69** [comment]
There is no **portable** version of Jackett
Jackett can be used as a service or run-on-demand 
You choose which mode when you answer the install-as-service yes/no at installation time.
We recommend you install Jackett as a service so that it is always available to respond to search queries from 3rd party apps (such as your qBt plug in, or Sonarr, Radarr, DuckieTV, etc), and also so you can keep Jackett auto-updated with the daily releases that contain updates for the indexers that are used to search which ever web sites you are searching for torrents with through Jackett.

**Comment by p060477** [comment]
thxs again for yr helping and patience
so when you say: "run on demand" you mean that anyway jackett as to be-installed- on the pc?
so there is no way to use it every time clicking on the 4 jackett exe files inside the .zip folder
i mean by clicking on:
jackett console exe
jackett service exe
jackett tray exe
and jackett updater exe
without having it previously installed?
apologize for my very few skills and the level of my questions
but for me is important to understand
thxs so much indeed again for yr kind cooperation

**Comment by garfield69** [comment]
You could choose to run the JackettConsole from a cmd shell, then you can access the Jackett dashboard via the browser to set up the indexers for searching, and as long as the cmd shell is open and JackettConsole is running, then Jackett will respond to 3rd party queries from the qBt plug in or other programs, or you can use the browser dashboard to do manual searches that way.

But from a practical point of view, if you are going to use the qBt plugin to make queries of Jackett to find torrents, there really is no benefit running jackett on-demand. 
Just install the thing as a service and then you don't have to remember to launch Jackett every time you want to search for torrents via the qBt plug in.

**Comment by p060477** [comment]
thxs so much indeed again
which is the command to run the console?
i mean if i use windows powershell with admin rights
and i have the console.exe in:
G:\back up 29.04.2010\C\Documents and Settings\Administrator\Dati applicazioni\Jackett\JackettConsole.exe
which command should i have to write in the powershell adminrights win 10 home 64:
if i open it i have:
C:\WINDOWS\system32>

thxs so much indeed again for yr kind helping and patience too

**Comment by garfield69** [comment]
I do not recommend running jackett from any other location but `%ProgramData%\Jackett`, you are just making things more complicated that they need to be.
Move the Jackett directory from that temporary path on your G drive to `C:\ProgramData`
the from your shell `cd %ProgramData%\Jackett` and then run `JackettConsole`

**Comment by p060477** [comment]
understand i moved the jackett folder to %ProgramData%\Jackett
in start run i type:
cmd
then:
Microsoft Windows [Versione 10.0.19041.388]
(c) 2020 Microsoft Corporation. Tutti i diritti sono riservati.

C:\Users\Administrator>cd %ProgramData%\Jackett

C:\ProgramData\Jackett>

at this point which command should i have to type to run the jackettconsole.exe ?
thxs so much really indeed again for yr kind and precious cooperation and yr patience too

**Comment by garfield69** [comment]
`JackettConsole`

**Comment by p060477** [comment]
in the same way i should be able to run also the other 3 exe files:
jackett service exe
jackett tray exe
and jackett updater exe
or i could only run the console and then from that run the tray,service and updater?

thx you so much for yr helping and so kind patience too

cheers

**Comment by garfield69** [comment]
you only need to start the jackettconsole program.
the other 3 will be used by the jackettconsole when if they are required based on your dashboard settings.
