### ISSUE TITLE
[torrentz2k] Exception (torrentz2k): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s). (Test)

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#9235]
![image](https://user-images.githubusercontent.com/19517680/88482736-86600700-cf8d-11ea-90de-8a29302ea776.png)

Jackett Version 0.16.895.0

**Comment by garfield69** [comment]
torrentz2k have enabled cloudflare anti-DDoS protection which Jackett cannot solve currently.
Until the web site lift the protection you will just have to use your browser to access the site.
Work on an experimental solution for this issue #9029 is not likely to be available any time soon.
