### ISSUE TITLE
[req] SDKino

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#9244]
SDKino.Net is a RUSSIAN Semi-Private Tracker for TV / MOVIES.

**Comment by garfield69** [comment]
problem.
the sites search engine does not appear to support free form search using keywords
it appears to only support a selection as you type, and once the pull down list is created, then it takes you directly to the details page of the selected entry.

are you able to generate a list of search results?

**Comment by dimqua** [comment]
Yes, it seems that you need to click this button at the top right of the page to change the default settings.

![](https://i.imgur.com/KHzOuVD.png)

**Comment by garfield69** [comment]
that button just switches the presentation from poster grid to card grid
but searching is still a problem.
example, you can search for `ghost` but not `ghost whisperer` ?

**Comment by dimqua** [comment]
Sorry, I don't get it. Why would you want to exclude `ghost whisperer` from the results?

http://sdkino.net/browse.php?search=ghost

**Comment by garfield69** [comment]
ok. sorry.
found the issue. 
which was that the web site keeps resetting to only search for **paid releases**.

I'm handicapped in that I keep having to translate Russian into English to read the settings
doing foreign language web sites is such a pain in the backside for me!

that is why I can search for ghosts and get results but searching for ghost whisperer was not returning results.
but now I'm remembering to set incldead=1 things are working.

I'll carry on building the indexer.

**Comment by garfield69** [comment]
Jackett 0.16.922

**Comment by garfield69** [comment]
site returning
```
The project is closed. More in telegram @sdkino
```

**Comment by garfield69** [comment]
v0.18.410
