### ISSUE TITLE
[hdsky] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by bearxbeat** [Jackett/Jackett#9246]
An error occurred while testing this indexer
Found no results while trying to browse this tracker
[log.txt](https://github.com/Jackett/Jackett/files/4992328/log.txt)

**Comment by bearxbeat** [comment]
An error occurred while testing this indexer
Found no results while trying to browse this tracker

sorry i late the post

[log.txt](https://github.com/Jackett/Jackett/files/4992345/log.txt)

**Comment by garfield69** [comment]
looks like they have changed their download links from
```html
<form action="download.php?id=******&t=******&sign=******" method="POST">
```
to 
```html
<form action="https://hdsky.me/download.php?id=******&t=******&sign=******" method="POST">
```
I will update the indexer to handle the new links.

**Comment by bearxbeat** [comment]
Thank you mr Garfield.

**Comment by garfield69** [comment]
try out Jackett 0.16.916
