### ISSUE TITLE
[Bug] HDSky Configuration/login failed: No form found

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#925]
Enhanced log attached. Thanks.
[log.txt](https://github.com/Jackett/Jackett/files/697785/log.txt)

**Comment by armani316** [comment]
Fixed. IP-related problem.

**Comment by armani316** [comment]
The problem seems to keep reoccurring. Is anyone else having this issue?

**Comment by kaso17** [comment]
The log shows some error message with "IP" in it. Unfortunately it seems like the log can't handle Chinese characters, so the meaning is lost.
Try visiting https://hdsky.me/login.php while it occurs.
Might be some kind of rate limiting?!?

**Comment by armani316** [comment]
Yeah I believe that's exactly what it is. Just tried to log in, and it wouldn't let me because I logged in too many times today. I can access the website just fine, but the login page doesn't work. 

Not Jackett-related, so I'll close this again. As always, thanks for your help, @kaso17.

**Comment by armani316** [comment]
This happened to me again. Apparently, testing HDSky in Jackett and doing a few manual search queries can cause HDSky to lock the user's login, citing 'maximum number of failed login attempts is reached during reauthentication'. Note that none of my 'login attempts' failed (the correct username and password are saved in Jackett), and I never needed to enter the captcha image authentication after the initial setup (save for the occasional reconfigurations). 

This actually causes the user's IP address to get banned (can't relogin, can't use HDSky in Jackett, but can surf the website normally since I'm already logged in). I had to contact the SYSOP to unban my IP manually on both occasions. 

Is Jackett trying to login to HDSky every time a search or test is conducted? Even if that's the case, a failed login does not make sense when I'm not even prompted to validate using captcha, Can logins be done only when necessary?

**Comment by kaso17** [comment]
a89631aec45debeadebdb09b10ddf49903eaf619 will prevent automated login attempts in case of an captcha, that should fix the problem.

**Comment by armani316** [comment]
@kaso17 Now that auto re-login doesn't happen anymore, I find myself having to reconfigure (i.e. solve the captcha) both HDSky & HDHome every few hours. It sounds identical to the issue you're facing in #910. Out of all trackers with captcha-based security, I'm only facing this issue with HDS & HDH. 

Is this normal/expected? Why does it affect only some users or some trackers that use captcha?

**Comment by kaso17** [comment]
#910 is just the cloudflare limitation
I noticed it for HDsky too (often reconfigure required). I'm trying it now with my desktop browser cookie to see if that helps with the frequent reconfigures.

**Comment by armani316** [comment]
@kaso17 If you figure out a way to resolve the frequent reconfiguration issue (for HDSky & HDHome), let me know :)

**Comment by kaso17** [comment]
For me using the cookie from the browser seems to work.
Can you please try stopping jackett, edit the hdsky config file ($JACKET_CONFIG_DIR/Indexers/hdsky.json) manually and replace the cookieheader value with the value from your browser (in my case it contained 3 extra cookies) and see if that fixes it for you.
Please try the same for hdhome (where I can't reproduce this issue)

**Comment by armani316** [comment]
@kaso17 For HDSky, I copied all the cookieheader fields under "value", including c_secure_uid, c_secure_pass, c_secure_ssl, c_secure_tracker_ssl, and c_secure_login. Did the same for HDHome, which is slightly different in that it has a __cfduid value as well. 

They're both working fine for now, but I'll give this a few days. I'll close this for now, and will reopen it if I encounter any issues. As always, thanks a lot for your help!

**Comment by kaso17** [comment]
This is how my browser cookie was looking:
`c_lang_folder=en; do3nbfaOIHDmdo=ddd; c_secure_uid=XXX; c_secure_pass=XXX; c_secure_ssl=XXX; c_secure_tracker_ssl=XXX; c_secure_login=XXX; CNZZDATA5476511=XXX`

**Comment by armani316** [comment]
I also had the CNZZDATA5476511 value in my browser, but it doesn't exist in Jackett so I didn't copy it. Should I?

**Comment by kaso17** [comment]
CNZZDATA5476511 is probably just a tracking cookie
do you have a random cookie like do3nbfaOIHDmdo=ddd ?

**Comment by armani316** [comment]
No, for HDSky, in my browser I have 7 of the 8 you listed, all but the random one [do3nbfaOIHDmdo]. 

In Jackett I have 5 of those 8, all but [do3nbfaOIHDmdo], [CNZZDATA5476511], and [c_lang_folder].

**Comment by kaso17** [comment]
ok, try with the 5 cookies, if it doesn't work use all

**Comment by armani316** [comment]
Will do. Thanks, @kaso17!
