### ISSUE TITLE
[REQ] Torrentube.net - Korean Torrent site.

### ISSUE THREAD

**Issue by SuperKumKum** [Jackett/Jackett#9256]
**Description:**
Korean torrent tracker for K-Dramas

**Website:**
- https://15.torrentube.net/
- https://14.torrentube.net/

**Type:**
- Public 

**Additional notes:** 

- Works with search engine 
- .torrent files and magnets available

**Comment by garfield69** [comment]
the indexer for this site will need to be written in c# as the search results are generated using Javascript after the html is presented.

**Comment by garfield69** [comment]
closing as stale.
