### ISSUE TITLE
ERROR: No encoding detected, defaulting to UTF-8 ??

### ISSUE THREAD

**Issue by seanvree** [Jackett/Jackett#926]
I get these errors a lot recently:

IWebClient.GetString(Url:http://www.omdbapi.com/?type=movie&i=tt1711525): No encoding detected, defaulting to UTF-8

**Comment by kaso17** [comment]
No problem in this case but fixed anyway with 7a25d94b959a0017a9dc771e77a440f87a6f3e3d
