### ISSUE TITLE
Sky, 1337x and Limetorrent indexer not working

### ISSUE THREAD

**Issue by chrisjc76** [Jackett/Jackett#9268]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**Windows**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.933.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

Sky, 1337x and Limetorrent indexer not working

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
From your previous attempts to raise tickets which the bot has closed, you are running into the `Clearance failed after 10 attempt(s).`
This means that the domains you are using are under DDoS attack, and the sites have invoked the cloudflare anti-DDoS check, which Jackett cannot solve.
Some options:
- edit the relevant indexer configs, and try any (if available) of the alternate site links, which may provide access to domains not under attack.
- use a VPN to allocate an IP from a different region of the world which hopefully will not be registered by cloudflare as belonging to a suspect DDoS IP group.
- while the attack is still ongoing, just use your browser, and way for the checks to be lifter so you can use Jackett again.
- there is experimental work #9029 but this is a long way from being ready for general release.
