### ISSUE TITLE
[New Tracker REQ] Hyperay

### ISSUE THREAD

**Issue by BFDZ** [Jackett/Jackett#927]
**Indexer Name**
Hyperay

**Type**
Movies / TV / Music

Indexer URL
https://www.hyperay.cc/

Indexer Language
English

Invite
If you need to, give me your email.

**Comment by kaso17** [comment]
Please send the invite to kaso1717 -at- gmail.com

**Comment by BFDZ** [comment]
@kaso17 The invite has been sent.

**Comment by kaso17** [comment]
Got it, thank you.
One question:
Do the different torrent background colors mean anything?
How do I identify freeleech, etc. torrents from the search?

**Comment by BFDZ** [comment]
Different torrent background colors indicate different levels of placement.

After the torrent title will add a free tag that freeleech, but now the website canceled all the torrent promotion.

Before that, use the search promotion box in the search box to search for free torrents.

**Comment by kaso17** [comment]
ok, in case you notice that the promotions are back, please let us know.
