### ISSUE TITLE
[broadcity] Can't add indexer

### ISSUE THREAD

**Issue by janot** [Jackett/Jackett#9271]
Getting this error when trying to add it:
![Capture](https://user-images.githubusercontent.com/1689966/89110798-0affc900-d457-11ea-9740-4614194d4e40.PNG)

Log:

Error | {0} Jackett.Common.ExceptionWithConfigData: Error: Konu başlığı			 			Son Yazan 			Cevaplanma 			Görüntülenme			 		  		 			 				 			 			 				 			 			 				135+ TB Devasa Arşiv \| En Güncel Film/Diziler \| Kaliteli Encodeler & BluRay Disc \| Kişiye Özel Hizmet \| BdC Farkı  				TarafındanAraGoRN 				17-05-2020 19:58 						 			 				Bugün 20:00	 				TarafındanAraGoRN 				 				 			 			 				14 			 			 				748 			 		 	 		 			 				 			 			 				 			 			 				Kurban Bayramı Bayram Hediyesi  				TarafındanTaGoRe 				30-07-2020 19:10 						 			 				Bugün 17:50	 				Tarafındanangarabebesi 				 				 			 			 				11 			 			 				155 			 		 	 		 			 				 			 			 				 			 			 				Katarlı Yayıncı Kuruluş İçin Bu da Yapıldı! Süper Ligde Küme Düşme Kaldırıldı  				TarafındanQUARESMA25 				29-07-2020 18:33 						 			 				Bugün 14:20	 				Tarafından👑hakan1987 				 				 			 			 				6 			 			 				74 			 		 	 		 			 				 			 			 				 			 			 				Komikmi Bence Komik  				Tarafındanangarabebesi 				Dün 14:34 						 			 				Bugün 08:24	 				Tarafından👑Anubis 				 				 			 			 				6 			 			 				58 			 		 	 		 			 				 			 			 				 			 			 				Sosyal Medya Düzenlenmesi Neleri İçeriyor? Madde Madde Anlatım  				TarafındanQUARESMA25 				30-07-2020 19:07 						 			 				Dün 06:51	 				Tarafından👑Anubis 				 				 			 			 				1 			 			 				23 			 		 	 		 			 				 			 			 				 			 			 				Fatih Karagümrük Süper Lig'e Yükselen Son Takım Oldu  				TarafındanQUARESMA25 				Dün 00:05 						 			 				Dün 00:28	 				Tarafındansolofurky 				 				 			 			 				1 			 			 				23 			 		 	 		 			 				 			 			 				 			 			 				Eksiğimizi Söyleyin, Hediye Kazanın !!!  (  1  2  3  4 ...  Son) 				TarafındanTuser 				20-01-2019 21:25 						 			 				30-07-2020 16:45	 				Tarafındanblackreaper 				 				 			 			 				146 			 			 				3,924 			 		 	 		 			 				 			 			 				 			 			 				 VIP + IPTV (4.500+ Kanal,3.700+ Film,15.000+ Dizi !)  (  1  2  3  4 ...  Son) 				TarafındanTaGoRe 				24-08-2019 17:31 						 			 				30-07-2020 13:37	 				TarafındanAhmetozmen73 				 				 			 			 				93 			 			 				3,401 			 		 	 		 			 				 			 			 				 			 			 				Kamu Çalışanlarının İş İçin WhatsApp ve Telegram Kullanmaları Yasaklandı  				Tarafındandiji 				29-07-2020 10:57 						 			 				29-07-2020 17:28	 				Tarafındandiji 				 				 			 			 				3 			 			 				61 			 		 	 		 			 				 			 			 				 			 			 				Türkiye’nin Koronavirüs Öncesi ve Sonrası İnternet Hızı Açıklandı  				TarafındanKnockOut 				28-07-2020 21:47 						 			 				28-07-2020 21:47	 				TarafındanKnockOut 				 				 			 			 				0 			 			 				28 			 		 	 		 			 				 			 			 				 			 			 				Saygı İlk Teaser Yayınlandı \| Saygı Yakında BluTv'de  				TarafındanQUARESMA25 				28-07-2020 20:32 						 			 				28-07-2020 20:32	 				TarafındanQUARESMA25 				 				 			 			 				0 			 			 				25 			 		 	 		 			 				 			 			 				 			 			 				Chrome'a, Çorap Çekmecesine Dönen Yer İmlerini Temizletecek Bir Özellik Geliyor  				TarafındanKnockOut 				28-07-2020 19:27 						 			 				28-07-2020 19:27	 				TarafındanKnockOut 				 				 			 			 				0 			 			 				20 			 		 	 		 			 				 			 			 				 			 			 				Captain Marvel 2, Mr. Marvel'ı da İçeren Bir 'Mini-Avengers' Filmi Olabilir  				TarafındanKnockOut 				28-07-2020 19:23 						 			 				28-07-2020 19:23	 				TarafındanKnockOut 				 				 			 			 				0 			 			 				11 			 		 	 		 			 				 			 			 				 			 			 				vcruntime140.dll Hatası Nasıl Çözülür? [ Resimli Anlatım ]  				TarafındanKnockOut 				28-07-2020 17:17 						 			 				28-07-2020 17:17	 				TarafındanKnockOut 				 				 			 			 				0 			 			 				9 			 		 	 		 			 				 			 			 				 			 			 				Android ROM Nedir, Nasıl Yüklenir?  				TarafındanKnockOut 				26-07-2020 18:57 						 			 				28-07-2020 14:32	 				Tarafındanblackreaper 				 				 			 			 				5 			 			 				40 			 		 	 		 			 				 			 			 				 			 			 				Windows.old Silme İşlemi Nasıl Yapılır?  				TarafındanKnockOut 				26-07-2020 20:00 						 			 				27-07-2020 21:45	 				Tarafından👑sTyLe 				 				 			 			 				1 			 			 				32 			 		 	 		 			 				 			 			 				 			 			 				Netflix, Türkiye'de Ağustos Ayında Yayınlanacak İçerikleri Açıkladı  				Tarafındandiji 				27-07-2020 15:45 						 			 				27-07-2020 15:45	 				Tarafındandiji 				 				 			 			 				0 			 			 				56 			 		 	 		 			 				 			 			 				 			 			 				Kutup Ayıları, 80 Yıl İçerisinde Yok Olma Tehlikesiyle Karşı Karşıya Kalacak  				TarafındanKnockOut 				26-07-2020 10:59 						 			 				27-07-2020 07:13	 				Tarafından👑Anubis 				 				 			 			 				1 			 			 				8 			 		 	 		 			 				 			 			 				 			 			 				'Neredeyse Hacklenemeyen' Kuantum İnternetin Detayları Paylaşıldı  				TarafındanKnockOut 				26-07-2020 13:44 						 			 				26-07-2020 13:44	 				TarafındanKnockOut 				 				 			 			 				0 			 			 				29 			 		 	 		 			 				 			 			 				 			 			 				Linux Nedir, Ne İşe Yarar, Kimler Kullanır?  				TarafındanKnockOut 				26-07-2020 12:23 						 			 				26-07-2020 13:30	 				Tarafından👑Teaqaria 				 				 			 			 				1 			 			 				14 			 		 	 		 			 				 			 			 				 			 			 				Apple, Mac'lere FaceID Teknolojisini Getiriyor  				TarafındanKnockOut 				26-07-2020 13:23 						 			 				26-07-2020 13:23	 				TarafındanKnockOut 				 				 			 			 				0 			 			 				5 			 		 	 		 			 				 			 			 				 			 			 				Bilim İnsanları, 2.500 Yıl Önce Yok Olan Devasa Bir Güvercinin İzlerini Buldu  				TarafındanKnockOut 				26-07-2020 13:09 						 			 				26-07-2020 13:09	 				TarafındanKnockOut 				 				 			 			 				0 			 			 				7 			 		 	 		 			 				 			 			 				 			 			 				İçişleri Bakanlığı, Kurban Bayramı’nda Alınacak Tedbirleri Açıkladı  				TarafındanKnockOut 				26-07-2020 12:56 						 			 				26-07-2020 12:56	 				TarafındanKnockOut 				 				 			 			 				0 			 			 				13 			 		 	 		 			 				 			 			 				 			 			 				The Walking Dead: World Beyond’ın Fragmanı ve Vizyon Tarihi Yayınlandı  				TarafındanKnockOut 				26-07-2020 12:47 						 			 				26-07-2020 12:47	 				TarafındanKnockOut 				 				 			 			 				0 			 			 				7 			 		 	 		 			 				 			 			 				 			 			 				Netflix, Dark'ın Sezonları Arasındaki Bağlantıyı Gösteren Yeni Bir Video Yayınladı (Spoiler)  				TarafındanKnockOut 				26-07-2020 12:29 						 			 				26-07-2020 12:29	 				TarafındanKnockOut 				 				 			 			 				0 			 			 				9    at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebClientStringResult loginResult, IList`1 errorBlocks) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 473    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 730    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 987    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 110    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70
-- | --

**Comment by garfield69** [comment]
I have switched the indexer to using the cookie method. The update will be available in the next release of Jackett due out on about 8 hours or so.

**Comment by garfield69** [comment]
try out Jackett 0.16.938
