### ISSUE TITLE
[bteye] Exception (bteye): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s). (Test)

### ISSUE THREAD

**Issue by mprachar** [Jackett/Jackett#9276]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

WinSrvr 2019
VPN - PrivateVPN

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

Failed Test 

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
assuming you are using a sitelink of https://www.bteye.org/ then you are unlucky enough for your IP to be considered a possible suspect in a DDoS attempt by bteye.
Your only hope of proceeding, other than waiting for the anti-DDoS period to be lifted, is to try a VPN with an IP from another region of the world.
There is currently no way for Jackett to solve the cloudflare anti-DDoS reCaptcha challenge other than some experimental work being trailed with #9029 but this is not going to be available for general release for some time yet.

**Comment by droopified** [comment]
> assuming you are using a sitelink of https://www.bteye.org/ then you are unlucky enough for your IP to be considered a possible suspect in a DDoS attempt by bteye.
> Your only hope of proceeding, other than waiting for the anti-DDoS period to be lifted, is to try a VPN with an IP from another region of the world.
> There is currently no way for Jackett to solve the cloudflare anti-DDoS reCaptcha challenge other than some experimental work being trailed with #9029 but this is not going to be available for general release for some time yet.

possibly my issue also using PIA in the EAST region.
