### ISSUE TITLE
[btdigg] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by droopified** [Jackett/Jackett#9277]
connection is successful but not returning any results

**Comment by garfield69** [comment]
the indexer works for me.
to see what might be happening for you we are going to need to see a **full enhanced** log with debug and HTML so that we may get useful data to look at.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by droopified** [comment]
log attached 
[log.txt](https://github.com/Jackett/Jackett/files/5013249/log.txt)

**Comment by garfield69** [comment]
your IP address is being challenged by btddig
```
<title>Attention Required!</title>
       One more step
          Why do I have to complete a CAPTCHA?
          Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.
```
Jackett cannot solve this challenge.

try using your browser on the same mackine that is running jackett, and solve the challenge manually then try jackett again
if that does not work, then use a VPN to allocate an IP from a different region on the world than your current IP, maybe you can bypass the check that way.
