### ISSUE TITLE
[extratorrent-cd] Exception (extratorrent-cd): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s). (Test)

### ISSUE THREAD

**Issue by droopified** [Jackett/Jackett#9278]
[log.txt](https://github.com/Jackett/Jackett/files/5013251/log.txt)
url work but if changed to https://extratorrent.si/ except it isnt connecting or finding results

**Comment by garfield69** [comment]
https://extratorrent.si/ is the only valid domain for this indexer.
https://extratorrent.ag/ is for a different ET site which this indexer does not support.
Assuming you are using a sitelink of https://extratorrent.si/ then you are unlucky enough for your IP to be considered a possible suspect in a DDoS attempt by ETcd.
Your only hope of proceeding, other than waiting for the anti-DDoS period to be lifted, is to try a VPN with an IP from another region of the world.
There is currently no way for Jackett to solve the cloudflare anti-DDoS reCaptcha challenge other than some experimental work being trailed with #9029 but this is not going to be available for general release for some time yet.
