### ISSUE TITLE
Category Request IPTorrents/Add Custom Categories from WebUI

### ISSUE THREAD

**Issue by mommalongnips** [Jackett/Jackett#928]
Can we get TV Packs category added for IPT?

AddCategoryMapping("65", TorznabCatType.TV);

On a side bar, do you have any plans to make it so we can add custom categories right from the WebUI?

**Comment by kaso17** [comment]
Fixed with 538c455c6a0dc851cce28981d8bc81babf590681

No plans to make them configurable. What's your use case?
