### ISSUE TITLE
[abnormal] The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject]  CN=abnormal.ws[Issuer]  CN=Let's Encrypt Authority X3, O=Let's Encrypt, C=US[Serial Number]  04E2C750F72A33899BAA5EA15B7B1FA8E7B9[Not Before]  4/30/2020 11:57:46 AM[Not After]  7/29/2020 11:57:46 AM[Thumbprint]  9CB32582B564256146616AFDDBDB8E7C94C428ED (Config)

### ISSUE THREAD

**Issue by McFlyPartages** [Jackett/Jackett#9287]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Jackett 0.16.946
