### ISSUE TITLE
[Bug] TranceTraffic (TT) - Configuration failed: An error occurred while sending the request

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#929]
I had to add a security exception to my browser to be able to surf their website. No sure what exactly changed. Enhanced log attached.

[log.txt](https://github.com/Jackett/Jackett/files/703456/log.txt)

**Comment by kaso17** [comment]
Their certificate expired.
They'll probably replace it soon which will fix the issue.
If you need it urgently you can run jackett with "-n true" to ignore certificate errors (not recommended)

**Comment by RoloSoze** [comment]
@kaso17 Has TT's certificate expired again? Log attached. 
[log.txt](https://github.com/Jackett/Jackett/files/840401/log.txt)

**Comment by kaso17** [comment]
yes, added an exception with 75dccd186be5acdc20c218de6dd74b37a04ae830
