### ISSUE TITLE
[REQ] eztv.yt

### ISSUE THREAD

**Issue by lordjippo** [Jackett/Jackett#9293]
https://eztv.yt/

semi-private

**Comment by garfield69** [comment]
offline
![image](https://user-images.githubusercontent.com/6933240/89336656-d78a9c00-d6ed-11ea-9ed5-7fd0a48f1422.png)

**Comment by garfield69** [comment]
we already have an EZTV indexer using the domain https://eztv.io/
you can access your jackett dashboard and edit the eztv indexer config and change the site link to eztv.yt if you want to, this works.
I'm not going to add a separate indexer for a clone that works with the exiting indexer.
