### ISSUE TITLE
[myspleen] Login failed: Selector

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#9295]
An error occurred while updating this indexer:
```
Login failed: Selector "span.key:contains("Ratio") + span.value" didn't match
```
What can I do? Should I provide full logs for you to see?

**Comment by garfield69** [comment]
none of the team have an account on this site.
please provide **full enhanced** log with debug and HTML as described at https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket and hopefully thiswill provide enough data to amend the indexer.
thanks.
