### ISSUE TITLE
Found a problem while using the Windows installer

### ISSUE THREAD

**Issue by kamekku14** [Jackett/Jackett#9297]
### Environment

**OS**: Windows 10, version 2004

**.Net Runtime**: .Net-Framework

**.Net Version**: 4.0

**Jackett Version**: v0.16.949

**Last Working Jackett Version**: v0.16.863

**Are you using a proxy or VPN?** No

### Description

While installing the latest version of Jackett, I got a `MoveFile` error.

### Screenshots
![image](https://user-images.githubusercontent.com/66167734/89400552-a68a8580-d746-11ea-802f-f52ef80e3d30.png)

**Comment by ilike2burnthing** [comment]
Was Jackett running at the time?

Did you try temporarily disabling your AV and then installing?
