### ISSUE TITLE
[Question] Why did you drop all the public trackers?

### ISSUE THREAD

**Issue by sammy2142** [Jackett/Jackett#93]
Hi
I've been using jackett for a while to add some more indexers to sonnar. I noticed in one of the latest updates you removed all the public indexers (showrss, torrentz etc):
https://github.com/Jackett/Jackett/commit/61a8585e4352c6a79670a07d952d7cce0d2e4a5c

I'm just wondering why this happened?

Thanks

Sammy

**Comment by WhatFox** [comment]
In a climate of tools such as popcorn it has shown what can happen where the users choose to use provided software for illegitimate purposes.  We can only do our best to prevent public file sharing whilst still letting people monitor their interests.  If further forks of the app popup with the trackers re-added and supported there isn't anything I can do to stop it.

Our decision is final.
