### ISSUE TITLE
error "Too many open files"

### ISSUE THREAD

**Issue by Blisk** [Jackett/Jackett#9315]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:  QNAP

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Qmono 6.8.0.105

**.Net Version**:

**Jackett Version**: 0.16.817

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Whe I open web page (GUI) I get this error

result	"error"
error	"Too many open files"
stacktrace	"  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <570a1d5038274309abafc2a0593db5e2>:0 \n  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) [0x00000] in <570a1d5038274309abafc2a0593db5e2>:0 \n  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)\n  at Microsoft.AspNetCore.Mvc.Infrastructure.PhysicalFileResultExecutor.GetFileStream (System.String path) [0x0000e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Infrastructure.PhysicalFileResultExecutor.WriteFileAsync (Microsoft.AspNetCore.Mvc.ActionContext context, Microsoft.AspNetCore.Mvc.PhysicalFileResult result, Microsoft.Net.Http.Headers.RangeItemHeaderValue range, System.Int64 rangeLength) [0x000dc] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Infrastructure.PhysicalFileResultExecutor.ExecuteAsync (Microsoft.AspNetCore.Mvc.ActionContext context, Microsoft.AspNetCore.Mvc.PhysicalFileResult result) [0x000b5] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.PhysicalFileResult.ExecuteResultAsync (Microsoft.AspNetCore.Mvc.ActionContext context) [0x0001e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync (Microsoft.AspNetCore.Mvc.IActionResult result) [0x00049] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync] () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResultExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync] (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x003df] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters () [0x00030] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 \n  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 \n  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 \n  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 \n  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <3e78add7560946d19a08fac09a5a864f>:0 "

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ngosang** [comment]
I think this issue is not caused by Jackett. In Unix* systems there is a limit in the number of open files per application, user and system wide. I think other app is causing this issue in Jackett but I'm not sure. Search in Google how to increase the open files limit (and make it permanent between restarts). Set the current numbers x 10.
https://www.tecmint.com/increase-set-open-file-limits-in-linux/
