### ISSUE TITLE
IPTorrents Searching Issue

### ISSUE THREAD

**Issue by mommalongnips** [Jackett/Jackett#932]
I'm not sure why this is happening but when Sonarr searches for "Sopranos S03" it returns no results. However when I manually do it, its fine.

From the logs;
2017-01-13 23:04:57.1450 Info Manual search for "The Sopranos S02" on IPTorrents with 5 results.
2017-01-13 23:05:45.0296 Info Found 0 releases from IPTorrents for: Sopranos S03
2017-01-13 23:05:46.8885 Info Found 0 releases from IPTorrents for: Sopranos S03
2017-01-13 23:05:51.4515 Info Found 0 releases from IPTorrents for: Sopranos S03E13
2017-01-13 23:05:53.4366 Info Found 0 releases from IPTorrents for: Sopranos S03E13
2017-01-13 23:08:53.3605 Info Manual search for "Sopranos S03" on IPTorrents with 3 results.
2017-01-13 23:09:47.3339 Info Found 0 releases from IPTorrents for: Sopranos S03
2017-01-13 23:09:49.1661 Info Found 0 releases from IPTorrents for: Sopranos S03
2017-01-13 23:09:56.9924 Info Manual search for "Sopranos S03" on IPTorrents with 3 results.

**Comment by mommalongnips** [comment]
Here is the advanced log;

> 2017-01-13 23:19:57.2841 Info   http://10.0.0.5:9117/torznab/iptorrents/api?t=tvsearch&cat=5030,5040&extended=1&apikey=3nqa2k8nqxokfxn5u7jd0h5d1mtf5y51&offset=0&limit=100&q=Sopranos&season=3
> 2017-01-13 23:19:57.2846 Info DefaultHttpControllerSelector SelectController Route='indexerID:iptorrents,controller:Torznab,action:Call'
> 2017-01-13 23:19:57.2846 Info DefaultHttpControllerSelector SelectController Torznab
> 2017-01-13 23:19:57.2846 Info HttpControllerDescriptor CreateController
> 2017-01-13 23:19:57.2846 Info DefaultHttpControllerActivator Create
> 2017-01-13 23:19:57.2846 Info DefaultHttpControllerActivator Create Jackett.Controllers.TorznabController
> 2017-01-13 23:19:57.2857 Info HttpControllerDescriptor CreateController Jackett.Controllers.TorznabController
> 2017-01-13 23:19:57.2857 Info TorznabController ExecuteAsync
> 2017-01-13 23:19:57.2857 Info ApiControllerActionSelector SelectAction
> 2017-01-13 23:19:57.2857 Info ApiControllerActionSelector SelectAction Selected action 'Call(String indexerID)'
> 2017-01-13 23:19:57.2867 Info HttpActionBinding ExecuteBindingAsync
> 2017-01-13 23:19:57.2867 Info ModelBinderParameterBinding ExecuteBindingAsync Binding parameter 'indexerID'
> 2017-01-13 23:19:57.2867 Info ModelBinderParameterBinding ExecuteBindingAsync Parameter 'indexerID' bound to the value 'iptorrents'
> 2017-01-13 23:19:57.2867 Info HttpActionBinding ExecuteBindingAsync Model state is valid. Values: indexerID=iptorrents
> 2017-01-13 23:19:57.2876 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Call(String indexerID)'
> 2017-01-13 23:19:57.2876 Info JackettAPINoCacheAttribute OnActionExecutingAsync
> 2017-01-13 23:19:57.2876 Info ApiControllerActionInvoker InvokeActionAsync Action='Call(indexerID=iptorrents)'
> 2017-01-13 23:19:57.2876 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Call(indexerID=iptorrents)'
> 2017-01-13 23:19:57.2886 Debug IWebClient.GetString(Url:https://iptorrents.com/t?q=Sopranos+S03&26=&55=&78=&24=&25=&66=&82=&79=&4=&23=&22=&5=&99=)
> 2017-01-13 23:19:57.7306 Debug IWebClient: Returning OK => <!DOCTYPE html><html><head><title>Torrents - IPTorrents - #1 Private Tracker</title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><link rel="shortcut icon" href="/favicon.ico"><link rel="stylesheet" href="/css/font-awesome.min.css"><link rel="stylesheet" href="/rsrc/css/start.css?24"><script type="text/javascript" src="/rsrc/js/jq.js?111111"></script><script type="text/javascript" src="/rsrc/j$
> 2017-01-13 23:19:57.7409 Info Found 0 releases from IPTorrents for: Sopranos S03
> 2017-01-13 23:19:57.7409 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StringContent, Headers:
> {
> Content-Type: application/rss+xml; charset=utf-8
> }'
> 2017-01-13 23:19:57.7418 Info ApiControllerActionInvoker InvokeActionAsync
> 2017-01-13 23:19:57.7418 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Call(String indexerID)'
> 2017-01-13 23:19:57.7418 Info JackettAPINoCacheAttribute OnActionExecutedAsync
> 2017-01-13 23:19:57.7418 Info TorznabController ExecuteAsync
> 2017-01-13 23:19:57.7427 Info   Content-type='application/rss+xml; charset=utf-8', content-length=656
> 2017-01-13 23:19:57.7427 Info TorznabController Dispose
> 2017-01-13 23:19:57.7427 Info TorznabController Dispose
> 2017-01-13 23:20:04.7421 Info   http://10.0.0.5:9117/Admin/search
> 2017-01-13 23:20:04.7428 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
> 2017-01-13 23:20:04.7428 Info DefaultHttpControllerSelector SelectController Admin
> 2017-01-13 23:20:04.7428 Info HttpControllerDescriptor CreateController
> 2017-01-13 23:20:04.7436 Info DefaultHttpControllerActivator Create
> 2017-01-13 23:20:04.7436 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
> 2017-01-13 23:20:04.7436 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
> 2017-01-13 23:20:04.7436 Info AdminController ExecuteAsync
> 2017-01-13 23:20:04.7447 Info ApiControllerActionSelector SelectAction
> 2017-01-13 23:20:04.7447 Info ApiControllerActionSelector SelectAction Selected action 'Search(AdminSearch value)'
> 2017-01-13 23:20:04.7447 Info JackettAuthorizedAttribute OnAuthorizationAsync
> 2017-01-13 23:20:04.7447 Info JackettAuthorizedAttribute OnAuthorizationAsync
> 2017-01-13 23:20:04.7458 Info HttpActionBinding ExecuteBindingAsync
> 2017-01-13 23:20:04.7458 Info FormatterParameterBinding ExecuteBindingAsync Binding parameter 'value'
> 2017-01-13 23:20:04.7468 Info JQueryMvcFormUrlEncodedFormatter ReadFromStreamAsync Type='AdminSearch', content-type='application/x-www-form-urlencoded; charset=UTF-8'
> 2017-01-13 23:20:04.7478 Error JQueryMvcFormUrlEncodedFormatter ReadFromStreamAsync A value is required.
> 2017-01-13 23:20:04.7478 Info JQueryMvcFormUrlEncodedFormatter ReadFromStreamAsync Value read='Jackett.Models.AdminSearch'
> 2017-01-13 23:20:04.7489 Info FormatterParameterBinding ExecuteBindingAsync Parameter 'value' bound to the value 'Jackett.Models.AdminSearch'
> 2017-01-13 23:20:04.7504 Info HttpActionBinding ExecuteBindingAsync Model state is invalid. value.Category: A value is required.
> 2017-01-13 23:20:04.7506 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Search(AdminSearch value)'
> 2017-01-13 23:20:04.7506 Info JackettAPINoCacheAttribute OnActionExecutingAsync
> 2017-01-13 23:20:04.7506 Info ApiControllerActionInvoker InvokeActionAsync Action='Search(value=Jackett.Models.AdminSearch)'
> 2017-01-13 23:20:04.7506 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Search(value=Jackett.Models.AdminSearch)'
> 2017-01-13 23:20:04.7518 Debug IWebClient.GetString(Url:https://iptorrents.com/t?q=Sopranos+S03)
> 2017-01-13 23:20:05.0232 Debug IWebClient: Returning OK => <!DOCTYPE html><html><head><title>Torrents - IPTorrents - #1 Private Tracker</title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><link rel="shortcut icon" href="/favicon.ico"><link rel="stylesheet" href="/css/font-awesome.min.css"><link rel="stylesheet" href="/rsrc/css/start.css?24"><script type="text/javascript" src="/rsrc/js/jq.js?111111"></script><script type="text/javascript" src="/rsrc/j$
> 2017-01-13 23:20:05.0452 Info Manual search for "Sopranos S03" on IPTorrents with 3 results.
> 2017-01-13 23:20:05.0457 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'Jackett.ManualSearchResult'
> 2017-01-13 23:20:05.0457 Info DefaultContentNegotiator Negotiate Type='ManualSearchResult', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer]
> 2017-01-13 23:20:05.0457 Info JsonMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'JsonMediaTypeFormatter' for type='ManualSearchResult', mediaType='application/json; charset=utf-8'
> 2017-01-13 23:20:05.0466 Info JsonMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'JsonMediaTypeFormatter' formatter
> 2017-01-13 23:20:05.0466 Info DefaultContentNegotiator Negotiate Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8'
> 2017-01-13 23:20:05.0466 Info ApiControllerActionInvoker InvokeActionAsync
> 2017-01-13 23:20:05.0466 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Search(AdminSearch value)'
> 2017-01-13 23:20:05.0466 Info JackettAPINoCacheAttribute OnActionExecutedAsync
> 2017-01-13 23:20:05.0478 Info AdminController ExecuteAsync
> 2017-01-13 23:20:05.0478 Info   Content-type='application/json; charset=utf-8', content-length=unknown
> 2017-01-13 23:20:05.0487 Info JsonMediaTypeFormatter WriteToStreamAsync Value='Jackett.ManualSearchResult', type='ManualSearchResult', content-type='application/json; charset=utf-8'
> 2017-01-13 23:20:05.0487 Info JsonMediaTypeFormatter WriteToStreamAsync
> 2017-01-13 23:20:05.0619 Info AdminController Dispose
> 2017-01-13 23:20:05.0619 Info AdminController Dispose
>

**Comment by kaso17** [comment]
Make sure you add category 5000 to the category list in the sonarr indexer config
