### ISSUE TITLE
Torrent-Syndikat search with more than one category shows no results

### ISSUE THREAD

**Issue by pluusla** [Jackett/Jackett#9324]
### Environment

**OS**:

Ubuntu

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
idk, no root access. No mono

**.Net Version**:

**Jackett Version**:

v0.16.979

**Last Working Jackett Version**:
v0.16.976

**Are you using a proxy or VPN?** [yes/no]

No

### Description

Since the last update, it seems multiple cat search for torrent-syndikat shows no results. 

Search string (working via site):
browsep.php?**cat[]=53&cat[]=54**&search=&searchin=title&incldead=1&rel_type=0&lb=

Search string vom jackett (see log):
browse.php?incldead=1&rel_type=0&searchin=title&**cat[]=53%2C54**)

### Logged Error Messages

`
Date 	Level 	Message
2020-08-11 12:54:26 	Debug 	

Executed controller factory for controller {Controller} ({AssemblyName})

2020-08-11 12:54:26 	Debug 	

Executing controller factory for controller {Controller} ({AssemblyName})

2020-08-11 12:54:26 	Info 	

Authorization was successful.

2020-08-11 12:54:26 	Debug 	

Execution plan of {FilterType} filters (in the following order): {Filters}

2020-08-11 12:54:26 	Debug 	

Execution plan of {FilterType} filters (in the following order): {Filters}

2020-08-11 12:54:26 	Debug 	

Execution plan of {FilterType} filters (in the following order): {Filters}

2020-08-11 12:54:26 	Debug 	

Execution plan of {FilterType} filters (in the following order): {Filters}

2020-08-11 12:54:26 	Debug 	

Execution plan of {FilterType} filters (in the following order): {Filters}

2020-08-11 12:54:26 	Info 	

Route matched with {RouteData}. Executing controller action with signature {MethodInfo} on controller {Controller} ({AssemblyName}).

2020-08-11 12:54:26 	Info 	

Executing endpoint '{EndpointName}'

2020-08-11 12:54:26 	Debug 	

Request matched endpoint '{EndpointName}'

2020-08-11 12:54:26 	Debug 	

Endpoint '{Endpoint}' with route pattern '{RoutePattern}' is valid for the request path '{Path}'

2020-08-11 12:54:26 	Debug 	

{CandidateCount} candidate(s) found for the request path '{Path}'

2020-08-11 12:54:26 	Debug 	

AuthenticationScheme: {AuthenticationScheme} was successfully authenticated.

2020-08-11 12:54:26 	Debug 	

The request path {Path} does not match a supported file type

2020-08-11 12:54:26 	Debug 	

Request is continuing in applying rules. Current url is {currentUrl}

2020-08-11 12:54:26 	Debug 	

Request is continuing in applying rules. Current url is {currentUrl}

2020-08-11 12:54:26 	Debug 	

Request is continuing in applying rules. Current url is {currentUrl}

2020-08-11 12:54:26 	Info 	

Request starting HTTP/1.1 GET http://yyy.zz/api/v2.0/server/logs?_=1597143248947

2020-08-11 12:54:22 	Info 	

Request finished in 584.7819ms 200 application/json; charset=utf-8

2020-08-11 12:54:22 	Debug 	

Connection id "{ConnectionId}" completed keep alive response.

2020-08-11 12:54:22 	Info 	

Executed endpoint '{EndpointName}'

2020-08-11 12:54:22 	Info 	

Executed action {ActionName} in {ElapsedMilliseconds}ms

2020-08-11 12:54:22 	Debug 	

No response compression available for HTTPS requests. See ResponseCompressionOptions.EnableForHttps.

2020-08-11 12:54:22 	Info 	

Executing JsonResult, writing value of type '{Type}'.

2020-08-11 12:54:22 	Info 	

Manual search for "" on torrentsyndikat with 0 results.

2020-08-11 12:54:22 	Debug 	

WebClient(HttpWebClient2NetCore): Returning OK => Oha, da hats gekracht. Staff wurde informiert ...

2020-08-11 12:54:21 	Debug 	

**WebClient(HttpWebClient2NetCore).GetString(Url:https://torrent-syndikat.org/browse.php?incldead=1&rel_type=0&searchin=title&cat[]=53%2C54)**

2020-08-11 12:54:21 	Debug 	

Done attempting to validate the bound parameter '{ParameterName}' of type '{ModelType}'.

2020-08-11 12:54:21 	Debug 	

Attempting to validate the bound parameter '{ParameterName}' of type '{ModelType}' ...

2020-08-11 12:54:21 	Debug 	

Done attempting to bind parameter '{ParameterName}' of type '{ModelType}'.

2020-08-11 12:54:21 	Debug 	

Done attempting to bind parameter '{ParameterName}' of type '{ModelType}'.

2020-08-11 12:54:21 	Debug 	

Done attempting to bind property '{PropertyContainerType}.{PropertyName}' of type '{ModelType}'.

2020-08-11 12:54:21 	Debug 	

Done attempting to bind model of type '{ModelType}' using the name '{ModelName}'.

2020-08-11 12:54:21 	Debug 	

Could not find a value in the request with name '{ModelName}' of type '{ModelType}'.

2020-08-11 12:54:21 	Debug 	

Attempting to bind model using indices. Example formats include: [0]=value1&[1]=value2, {ModelName}[0]=value1&{ModelName}[1]=value2, {ModelName}.index=zero&{ModelName}.index=one&{ModelName}[zero]=value1&{ModelName}[one]=value2

2020-08-11 12:54:21 	Debug 	

Could not bind to collection using a format like {ModelName}=value1&{ModelName}=value2

2020-08-11 12:54:21 	Debug 	

Attempting to bind property '{PropertyContainerType}.{PropertyName}' of type '{ModelType}' using the name '{ModelName}' in request data ...

2020-08-11 12:54:21 	Debug 	

Done attempting to bind property '{PropertyContainerType}.{PropertyName}' of type '{ModelType}'.

2020-08-11 12:54:21 	Debug 	

Done attempting to bind model of type '{ModelType}' using the name '{ModelName}'.

2020-08-11 12:54:21 	Debug 	

Could not find a value in the request with name '{ModelName}' of type '{ModelType}'.

2020-08-11 12:54:21 	Debug 	

Attempting to bind model using indices. Example formats include: [0]=value1&[1]=value2, {ModelName}[0]=value1&{ModelName}[1]=value2, {ModelName}.index=zero&{ModelName}.index=one&{ModelName}[zero]=value1&{ModelName}[one]=value2

`

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by cola32** [comment]
Since v0.16.979 TS isn’t working anymore

**Comment by garfield69** [comment]
I've reverted #9314
