### ISSUE TITLE
Torrent9 clone: Got redirected to another domain. https://www.torrent9.so/

### ISSUE THREAD

**Issue by hegyre** [Jackett/Jackett#9328]
### Environment

**OS**: Windows 10

**Jackett Version**: 0.16.979.0

### Description

Running test for torrent9 clone

### Logged Error Messages

An error occurred while testing this indexer
Exception (torrent9clone): Got redirected to another domain. Try changing the indexer URL to https://www.torrent9.so/. Updated site link, please try again.: Parse error

### Screenshots

The strange thing is that it automagicall updates indexer config with .so, but if I validate the config, it switch back to .ac
However, f I run the test twice, the first fails, but the second test succeed !

**Comment by garfield69** [comment]
closed with #9325
