### ISSUE TITLE
magico.one problem snatch from apps

### ISSUE THREAD

**Issue by vlevas** [Jackett/Jackett#9345]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: ubuntu 18.04

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Jackett Version 0.16.998.0 docker

**Last Working Jackett Version**: dont remember

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

Hello the problem is that the link from jackett it works also manual search on jackett app all is ok..
On sonarr and radarr i put the link of magico indexer says succesfully but no result when i do manual search or search to find something.. i get only results from other jackett provider but not from there and the content is there as i can see on website tracker also on jackett manual search.. can someone tell what is the problem?

i tried on
radarr/sonarr/couchpotato also develop branch no result from app on this jackett tracker.
can we do something?

also i cant debug it it says that searching 3 indexers and of them is magico.one from jackett but no result no error :+1:

**Comment by garfield69** [comment]
My first observation is that magico is a non-english site so the Greek alphabet in titles may prevent Sonarr and Radarr from matching titles.

But start by reporting which version of Radarr and Sonarr you are using.
then provide one or two search titles for both apps that you are not getting results from the Jackett magico indexer.

I can then take a look and see if there is anything can be done.

**Comment by vlevas** [comment]
as i can see again on sonarr it works on preview image.. on radarr doesnt 
i provide some pictures and tell me if u want anything more
thanks a lot for your time!!

https://prnt.sc/u0i7zj
https://prnt.sc/u0iamy
https://prnt.sc/u0ib9x

**Comment by garfield69** [comment]
The problem is that the Magico website cannot find `project%power%2020` (the percent symbol is a wildcard on this site).
but it can find `project%power%(2020)` 
so I will see if I can amend the indexer to  surround the year with `(` and `)` year in the search query.

**Comment by garfield69** [comment]
Jackett 0.16.1012
