### ISSUE TITLE
[Bug] BitSpyder - Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#935]
Enhanced log attached. Thanks.
[log.txt](https://github.com/Jackett/Jackett/files/706444/log.txt)

**Comment by kaso17** [comment]
They've two different "styles".
Go to http://bitspyder.net/browse.php click on "switch style" and it should work.
Will try to make it work with both styles.

**Comment by armani316** [comment]
@kaso17 Works fine with the other styles. Thanks!

**Comment by kaso17** [comment]
208761f28c38b5276b4f25eefbb33e8d39818e78 adds support for both styles
