### ISSUE TITLE
GimmePeers: outdated categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9351]
https://github.com/Jackett/Jackett/issues/8180#issuecomment-668812624

Only @cadatoiva has access.
@alanfrazier maybe you can help, just edit this file and open a PR. We will give you more instructions then. https://github.com/Jackett/Jackett/blob/1e5ef0f48afffea7050c65174fd0ed4be5c211fa/src/Jackett.Common/Indexers/GimmePeers.cs#L48

**Comment by garfield69** [comment]
have guest access for 24h so I will update the cats and test.

**Comment by garfield69** [comment]
[v0.20.723](https://github.com/Jackett/Jackett/releases/tag/untagged-47af126ef822c9bee2b0)
