### ISSUE TITLE
[1337x] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Tdotsown** [Jackett/Jackett#9366]
**all other index work but 1337x. their website works**

![image](https://user-images.githubusercontent.com/14135474/90498063-da39b800-e115-11ea-856d-c2d94c22c2b7.png)

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
answer this question: access your Jackett dashboard and scroll down to the bottom and report what the Jackett version is ?
then edit the 1337x config and report what the site link is set to ?

**Comment by Tdotsown** [comment]
That’s what I did and I selected the other websites and it started working

________________________________
