### ISSUE TITLE
[rarbg] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by gw1gw1** [Jackett/Jackett#9368]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu server 18.04 / docker 5:19.03.12~3-0~debian-buster

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:  0.16.1017.0

**Last Working Jackett Version**: UNKNOWN

**Are you using a proxy or VPN?** No

### Description

I added RARBG as a new index and whedn testing the connection I got this error popup message

**An error occurred while testing this indexer
Found no results while trying to browse this tracker
Click here to open an issue on GitHub for this indexer.**

**Comment by garfield69** [comment]
Upgrade your Jackett from 0.16.1017 to the latest version.
Starting with 16.1163 there is a fix that should help prevent this.
The current latest version at the time of this post is  0.16.1218
