### ISSUE TITLE
[Bug] ABNormal

### ISSUE THREAD

**Issue by Dark-pho3nix** [Jackett/Jackett#937]
Hi, Sorry for my imperfect English.

There are some errors after the search process with jackett : 

Error | IWebClient.GetString(Url:https://abnormal.ws/torrents.php?search=%25): No encoding detected, defaulting to UTF-8

Error | IWebClient.GetString(Url:https://abnormal.ws/torrents.php?search=%25): Got header without charset: https://abnormal.ws/torrents.php?search=%25 

Jackett version : 0.7.876.0
Thanks.

**Comment by kaso17** [comment]
fixed with 3a40e73d43f4be3524f47975991dede79a93f4a3
