### ISSUE TITLE
[HACHEDE] Wrong Languaje Parsing to Radarr

### ISSUE THREAD

**Issue by jasimancas** [Jackett/Jackett#9373]
Spanish provider HacheDe have a problem with languaje in Radarr: https://github.com/Radarr/Radarr/issues/4793

With [spanish] at end of title:
![image](https://user-images.githubusercontent.com/15717847/90731349-dea6d200-e2c9-11ea-8a18-216da5169e9d.png)

With SPANISH at end of title:
![image](https://user-images.githubusercontent.com/15717847/90731725-57a62980-e2ca-11ea-8255-12f34749ff4b.png)

It possible change [spanish] to SPANISH here: https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/hachede.yml#L173

**Comment by garfield69** [comment]
when the next release of Jackett is released in about 22 hours from now, it will include your request.

**Comment by garfield69** [comment]
Jackett 0.16.1021
