### ISSUE TITLE
1337x not working

### ISSUE THREAD

**Issue by corkerss** [Jackett/Jackett#9374]
### Environment

**OS**: Ubuntu Server

**Jackett Version**: 0.16.1002.0 via Linux Server Docker

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

Add 1337x as indexer. Test. Other indexers working fine 

### Logged Error Messages

[1337x] Exception (1337x): Connection reset by peer: The SSL connection could not be established, see inner exception. (Test)

### Screenshots

<img width="875" alt="Screenshot 2020-08-20 at 17 35 28" src="https://user-images.githubusercontent.com/36156736/90799792-a2946100-e30b-11ea-875a-98112208e3ce.png">

**Comment by corkerss** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/5105107/log.txt)

Thanks very much

**Comment by garfield69** [comment]
`SocketException (104): Connection reset by peer`
Your access to https://1337x.to is being blocked by your ISP or the network uoi are using or a security app or something.
My suggestion is that you access your Jackett dashboard, edit the 1337x config and try out each of the alternate site links until you find one that works for you.

**Comment by corkerss** [comment]
Thanks, strange they aren't blocking the more popular sites
