### ISSUE TITLE
[REQ] torhd.cc

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#9378]
Public site of movies: https://torhd.cc

**Comment by garfield69** [comment]
the web site presents one title that leads to a details page that has multiple .torrents and magnets.
which means an indexer for this site will need to be written in c# as the yaml processor only handles a one-to-one title-to-torrent presentation.

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
