### ISSUE TITLE
[REQ] yuptorrents.com

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#9379]
Public site of movies, tv series and documentaries: https://yuptorrents.com/

**Comment by garfield69** [comment]
note: currently forces http to https, but is using a certificate that expired 6/may/2019 !!!
the web site presents titles that lead to a details page that has multiple .torrents and magnets.
which means the indexer will need to be written in c# as the yml processor only handles a one-to-one title-to-torrent presentation.

**Comment by ilike2burnthing** [comment]
ERR_CONNECTION_CLOSED (using proxies just error out)
