### ISSUE TITLE
"Add Indexer" button doesn't work and indexers don't appear on Chrome

### ISSUE THREAD

**Issue by LucasVon** [Jackett/Jackett#938]
As title states, the Add Indexer button won't work on Chrome (version 55.0.2883.87). Also, the indexer list won't appear.

Tested on Firefox and Intenet Explorer. Both work.

I've also attached the Chrome inspector log showing an Uncaught error.

[127.0.0.1-1484523359910.txt](https://github.com/Jackett/Jackett/files/706993/127.0.0.1-1484523359910.txt)

**Comment by kaso17** [comment]
Which version of jackett are you running (The lines mentioned in the error don't make much sense with the latest version)?
Any fancy JS blockers which might cause trouble?
I'm running the same version of chrome and have no problem with it.
Please send the output http://127.0.0.1:9117/Admin/get_indexers so I can try to reproduce it.

**Comment by xevildoerxx** [comment]
i can confirm same issue .

**Comment by LucasVon** [comment]
I'm running version 0.7.876.0, but the problem appears to be gone now after removing and restoring my Chrome profile. It might have been trying to load a JS file from a previous version that was cached somewhere. Odd since I cleared the cache multiple times, but apparently completely resetting Chrome did the trick.

**Comment by xevildoerxx** [comment]
that seems to have done the trick thanks.

**Comment by CraigBHCM** [comment]
How or where did you remove your Chrome Profile I am having the issue in both safari and also in Chrome.

**Comment by xevildoerxx** [comment]
i had the issue with edge and chrome.. went into chrome settings, wiped and removed profile and browsing data and reset to default.

**Comment by CraigBHCM** [comment]
tried that and its still not allowing me to add IPtorrents

**Comment by kaso17** [comment]
Looks like it was a caching related issue.
@CraigBHCM The IPT issue was not related to this one.

**Comment by Nis158** [comment]
Yup having the same issue
