### ISSUE TITLE
[hebits] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (Config)

### ISSUE THREAD

**Issue by shaulbarlev** [Jackett/Jackett#9388]
Hello. Hebits is an israeli tracker. I tried to add it to my tracker list and jackett failed.
Error message:
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Jackett 0.16.1038.0

No VPN

**Comment by garfield69** [comment]
the hebits indexer is working for me so the issue appears to be at your end.
I assume you are able to access https://hebits.net/ from a browser running on the same machine as Jackett?
