### ISSUE TITLE
 Why were the public trackers removed?

### ISSUE THREAD

**Issue by viking2** [Jackett/Jackett#94]
Why were the public trackers removed in v0.7.27 and above? I was using those trackers.....

**Comment by WhatFox** [comment]
#93

**Comment by viking2** [comment]
I am now running v.0.6.45.0 and have added the public trackers. If I upgrade, will I loose those trackers or will they remain since they have already been added?

**Comment by eyotiste** [comment]
You will loose them
On my linux headless server I run two instance of Jackett, the last version with public and the last version

**Comment by viking2** [comment]
Good to know. I didn't realize that I could run two versions simultaneously. Would it also work in Windows? Did you just install them in different directories?

**Comment by eyotiste** [comment]
Install in to different directories and changed the port on the second instance

**Comment by raspdealer** [comment]
Good to know.

**Comment by raspdealer** [comment]
@eyotiste how did you managed the .config folder path?
they are using the same...

**Comment by eyotiste** [comment]
I have 2 services that I launch in two diffrents folders so the .config is not the same
[Unit]
Description=Jackett Daemon 
After=network.target

[Service]
User=[user]
Restart=always
RestartSec=5
Type=simple
//First Instance
ExecStart=/usr/bin/mono --debug /opt/Jackett/Jackett.console.exe
//Second Instance
ExecStart=/usr/bin/mono --debug /opt/Jackett-up/Jackett.console.exe
TimeoutStopSec=20

[Install]
WantedBy=multi-user.target

Obviously in two diffrents systemd script

**Comment by viking2** [comment]
Can something similar be done in Windows?

**Comment by raspdealer** [comment]
On my side, I've updated the code to target two different .config folder.

**Comment by raspdealer** [comment]
Check my fork. I'll release it for Linux.

**Comment by raspdealer** [comment]
https://github.com/raspdealer/Jackett/releases

**Comment by viking2** [comment]
Could you release one for Windows please? What are the changes vs 0.6.45.0?

**Comment by raspdealer** [comment]
I changed the path of config files to be able to run two instances. I will try yes.

**Comment by ldexterldesign** [comment]
https://www.reddit.com/r/sonarr/comments/4vp6a7/sonarr_jackett_06450_tpb/

Hey @raspdealer,

Are you still actively maintaining https://github.com/raspdealer/Jackett/ or is there another tool one should know about?

Hope to hear back

Kind thanks

**Comment by raspdealer** [comment]
I didn't have to update it but I'm still here :)

**Comment by ldexterldesign** [comment]
Cheers for reply

Will try the install tomorrow

Kind thanks
