### ISSUE TITLE
Trouble adding IPTorrents 0.7.884.0

### ISSUE THREAD

**Issue by Jdiesel87** [Jackett/Jackett#942]
I updated to the latest version (0.7.884.0) and IPTorrents was not finding an releases. Deleted the indexer and tried to re-add it but now I am unable to add the IPTorrent indexer at all. Debug log is attached.

[log.txt](https://github.com/Jackett/Jackett/files/709417/log.txt)

**Comment by Jtekt** [comment]
Same issue with latest version (0.7.884.0) to IPTorrents.

**Comment by Jdiesel87** [comment]
I tried reverting back to version 0.7.824.0 which was previously working as of yesterday and I am also no longer able to add IPTorrents as an indexer. Perhaps there was a change on IPTorrents end.

**Comment by Doginal** [comment]
Version 0.7.876.0 - I'm also having an issue adding IPTorrents. I get stuck at a Recaptcha that doesn't appear or seem to exist!

**Comment by CraigBHCM** [comment]
Having the same issue was working fine and now has stopped

**Comment by mcrommert** [comment]
same here exact same issue started today

**Comment by AliShaikh94** [comment]
Getting same issue

**Comment by nikhilgupta345** [comment]
Same issue here

**Comment by nafeasonto** [comment]
Same exact issue here.

**Comment by jiantjon** [comment]
Same here

**Comment by vertigo235** [comment]
+1

**Comment by CraigBHCM** [comment]
i tried wiping my profile in chrome and reset the profile and it still did nothing. 

Jan 17, 2017 04:08:56 PM	Warn	
Rejected a request to IPTorrents which is unconfigured.
Jan 17, 2017 04:04:44 PM	Error	
Exception in test_indexer

**Comment by crabchucker** [comment]
also having the same issue as above

**Comment by kaso17** [comment]
They made a minor change to their website.
Jackett v0.7.885 should fix it.
