### ISSUE TITLE
[iptorrents] Your cookie did not work: The requested name is valid, but no data of the requested type was found. (Config)

### ISSUE THREAD

**Issue by Jonagesh** [Jackett/Jackett#9429]
### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Net Framework

**.Net Version**: 4.8

**Jackett Version**: v0.16.1050

**Last Working Jackett Version**: Not sure

**Are you using a proxy or VPN?** [yes/no] yes(sometimes) and no

### Description

I am not able to use IPT tracker.. It was working for years with cookie.
I have removed it and getting error when I am adding it back. Attached the snip.
Trace added below.

### Logged Error Messages
{0} System.Exception: Your cookie did not work: The requested name is valid, but no data of the requested type was found.
   at Jackett.Common.Indexers.IPTorrents.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\IPTorrents.cs:line 163
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
### Screenshots

![image](https://user-images.githubusercontent.com/24497457/91942516-b59a2e80-ed18-11ea-8d66-02fe99574fab.png)

**Comment by garfield69** [comment]
@ngosang  @RoloSoze  is the IPTorrents indexer working for you, and if so with which domain?

**Comment by RoloSoze** [comment]
> 
> 
> @ngosang @RoloSoze is the IPTorrents indexer working for you, and if so with which domain?

It's working fine. Mine is using https://iptorrents.com/

**Comment by RoloSoze** [comment]
@garfield69 Lemme know if you need an invite to IPT.

**Comment by garfield69** [comment]
@Jonagesh the trace is next to useless in a situation like this. We may have better luck figuring out what is going on if you enabled the **full enhanced** log and provided it here with the debug and HTML included.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Jonagesh** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/5166600/log.txt)

Full Logs attached

**Comment by Jonagesh** [comment]
[Torrents - IPTorrents - #1 Private Tracker.txt](https://github.com/Jackett/Jackett/files/5166634/Torrents.-.IPTorrents.-.1.Private.Tracker.txt)
HTML attachedd

**Comment by Jonagesh** [comment]
> > @ngosang @RoloSoze is the IPTorrents indexer working for you, and if so with which domain?
> 
> It's working fine. Mine is using https://iptorrents.com/

![image](https://user-images.githubusercontent.com/24497457/92079978-68809000-edde-11ea-953a-b59fe45df539.png)

Do you have similar cookie being used for IPT? I m not sure why it stopped working.. :(

**Comment by garfield69** [comment]
thanks for providing the enhanced log.
the debug log for the last attempt you made to use IPT is showing a different error than the one you first reported
you are now getting
`Error System.Exception: Your cookie did not work: The SSL connection could not be established`
which is an error you had before back in 2020-08-04
```
The SSL connection could not be established
An existing connection was forcibly closed by the remote host.
```

unfortunately the log does not yield any more useful info :-(

As you may know, cookies expire.
have you tried 
- removing the active config from you jackett dashboard using the trashbin icon, 
- shutting down the Jackett service and 
- starting it afresh (to flush caches) and 
- adding the IPT config afresh with a newly fetched cookie?

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/24497457/92079978-68809000-edde-11ea-953a-b59fe45df539.png)
BTW when you copy your cookie string to the indexer config, are you copying the `cookie: ` as well?
because if you are then that is wrong. you select and paste everything **after** the `cookie: ` .

**Comment by Jonagesh** [comment]
> ![image](https://user-images.githubusercontent.com/24497457/92079978-68809000-edde-11ea-953a-b59fe45df539.png)
> BTW when you copy your cookie string to the indexer config, are you copying the `cookie: ` as well?
> because if you are then that is wrong. you select and paste everything **after** the `cookie: ` .

Yes. I was using the cookie starting with underscore. Not with cookie text :)

**Comment by Jonagesh** [comment]
> ![image](https://user-images.githubusercontent.com/24497457/92079978-68809000-edde-11ea-953a-b59fe45df539.png)
> BTW when you copy your cookie string to the indexer config, are you copying the `cookie: ` as well?
> because if you are then that is wrong. you select and paste everything **after** the `cookie: ` .



> thanks for providing the enhanced log.
> the debug log for the last attempt you made to use IPT is showing a different error than the one you first reported
> you are now getting
> `Error System.Exception: Your cookie did not work: The SSL connection could not be established`
> which is an error you had before back in 2020-08-04
> 
> ```
> The SSL connection could not be established
> An existing connection was forcibly closed by the remote host.
> ```
> 
> unfortunately the log does not yield any more useful info :-(
> 
> As you may know, cookies expire.
> have you tried
> 
> * removing the active config from you jackett dashboard using the trashbin icon,
> * shutting down the Jackett service and
> * starting it afresh (to flush caches) and
> * adding the IPT config afresh with a newly fetched cookie?

Yes.. I have removed it already as it was not working before. Created this issue as adding no longer work for IPT

**Comment by garfield69** [comment]
when you access the site with a browser running on the same system that is running Jackett, are you seeing any signs that the site is using cloudflare DDoS protection?
this may be in the form of a page stating `please wait while we check...` or a full prove-you-are-human puzzle challenge?

Have you tried using any of the alternate domain links from the IPT config?

**Comment by jfeulner** [comment]
Having a similar issue on Ubuntu - Sorry to piggyback.
@garfield69 when visiting the site while already logged in, had no Cloudflare prompt.

Just for shiggles, I logged out, and upon the login page, Cloudflare was doing a DDoS protection.

**Comment by garfield69** [comment]
@jfeulner  thanks for your report.

@Jonagesh  then there is your answer. 
jfeulner wrote:
>when visiting the site while already logged in, had no Cloudflare prompt.
>Just for shiggles, I logged out, and upon the login page, Cloudflare was doing a DDoS protection.

Jackett cannot handle the cloudflare challenge, so until the DDoS protection is lifted you will not be able to access IPT via Jackett.
An experimental solve was being worked on with #9029 but this has stalled for now.
