### ISSUE TITLE
Freedom-hd date 2016 years

### ISSUE THREAD

**Issue by kornesque** [Jackett/Jackett#943]
hello

in jackett log 
Jan 16, 2017 11:41:29 PM	Error Unable to detect release date of torrent

or in manual search

2016y ago	Freedom-HD

there is no date grab in the yml file

i m in linux version

**Comment by kaso17** [comment]
Their torrent search result page doesn't include the publish date. So we can't grab it.
You've to convince their site staff to include it in the output (can be a hidden field).
If you're successful let us know please :)
