### ISSUE TITLE
Wrong files count for IPT, no files at all for others trackers.

### ISSUE THREAD

**Issue by awsms** [Jackett/Jackett#9434]
I noticed IPT files count is never accurate (it's always the number of seeders showing up instead), and most of the trackers don't have a filecount showing up at all.
 
I'm using the latest version of Jackett (v0.16.1054)
![jcktt](https://user-images.githubusercontent.com/48278661/92021834-a89e2f00-ed5a-11ea-9772-062ca319337a.png)

**Comment by garfield69** [comment]
Jackett can only show the file-count if the web site being searched provides this value in their search results page.

When such a column is not available, then Jackett leaves that column empty when it presents the dashboard search results.

For instance, the **TorrentLeech** web site does not supply a file count in its search results
![image](https://user-images.githubusercontent.com/6933240/92028666-8804c200-edb8-11ea-8896-27a999384458.png)
there's title, tags, download-link, date, comments, size, grabs, seeders and leeches

and neither does **XSpeeds** web site
![image](https://user-images.githubusercontent.com/6933240/92029127-301a8b00-edb9-11ea-938f-6369a7713978.png)
I see title and date, tags, comments, size,grabs, seeders and leeches

I don't have access to the others so I cannot confirm.


That said, if you have access to a web site via your browser, and know that the site has a file-count column in its results, but that the corresponding Jackett indexer is not showing it, then the indexer needs to be updated. 
Raise a ticket for the relevant indexer and we can update it in most cases to include the file-count.


With regards to **IPT**, the indexer is expecting the file-count to be the sixth column in the row,
https://github.com/Jackett/Jackett/blob/dfebbe3b7926de6e0be52b9d9585e2470280b468/src/Jackett.Common/Indexers/IPTorrents.cs#L228
which happens to also be the seeders column
https://github.com/Jackett/Jackett/blob/dfebbe3b7926de6e0be52b9d9585e2470280b468/src/Jackett.Common/Indexers/IPTorrents.cs#L229


so if you browser the IPT web site and you find that there is a file-count column in its search results page, then the Jackett indexer needs updating.
I don't have an a/c on this site, so if you want to help me update the indexer you are going to need to provide the HTML from the web site so I can take a look.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by awsms** [comment]
oh yeah that makes sense. i'll take care of IPT and all the chinese trackers (mteam, skyhd, ourbits etc) running NexusPHP since the filecount is shown for each torrent.

**Comment by garfield69** [comment]
Jackett 0.16.1350
