### ISSUE TITLE
New Tracker: 1337x

### ISSUE THREAD

**Issue by danielh60** [Jackett/Jackett#944]
Hi
Can you add 1337x.to as a new tracker please.
Regards

**Comment by armani316** [comment]
@danielh60 Jackett is only meant to support private trackers. You could try opening an issue in Cardigann & see if anyone is willing to write a definitions file for 1337x that you can then copy to Jackett's directory. 

https://github.com/cardigann/cardigann/issues

I'm using The Pirate Bay's file in Jackett at the moment, and it works fine.

**Comment by kaso17** [comment]
Jackett won't support public trackers:
It has been already requested for cardigann: https://github.com/cardigann/cardigann/issues/204

**Comment by danielh60** [comment]
Thank you!  I opened a request for 1337x on Cardigann, will now close it as a duplicate.
