### ISSUE TITLE
Aither : Inconsistent results between searches

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#9443]
It seems filters make some entries disapear from search results :
If I search an empty string without filter i get plenty of results, esspecially on TV category :

![image](https://user-images.githubusercontent.com/531336/92125183-01bf9e80-edff-11ea-8186-7f3d2a4a9b18.png)

Now if I search the same empty string only on TV categories I don't get any result :
![image](https://user-images.githubusercontent.com/531336/92125297-2ca9f280-edff-11ea-9bdb-89cd21e16679.png)

**Comment by garfield69** [comment]
I cannot replicate your results.
However it does appear that Aither have changed their categories, dropping 6 of the cats that were there previously.
So I'll update the indexer and you can test the next Jackett release (due out in about 10 hours or so) and see if that resolves the issue for you.

**Comment by skuizy** [comment]
Thanks for the update.

I've had the same issue for a few minutes after the update and then no more problem... Maybe a cache issue ?
