### ISSUE TITLE
Malware: Kaspersky flagging jackett installer AGAIN Sept3,2020 kaspersky 20.0.14.1085

### ISSUE THREAD

**Issue by cocokola** [Jackett/Jackett#9445]
[See:]( https://github.com/Jackett/Jackett/issues/9377)

The same issue, except it's with the latest version of virus/app versions.   Can you PLEASE reach out to Kaspersky and have the false positive 'issue' identified/resolved so this stops happening?   

Kaspersky ONLY allows Delete/BLOCK as options, so this is being flagged as a major issue despite it being just; heuristics and no big deal.  What code is being executed that is flagging the detector?  Either get Kaspersky to whitelist thee code snippet, or stop doing the task that triggers the concern.

See the link for the normal questions asked/answered.  Let's get this fixed for good!

**Comment by garfield69** [comment]
I am sorry, but there is **nothing** we can do about any security app flagging Jackett with a false positive, other than do what you should be able to do for yourself, which is to use your security app to raise a false positive report.
All security apps should have this feature, its a basic function for feedback to the security app providers.

It is not practical to ask us to change the Jackett code in an attempt to avoid a false positive hit from **one** security app.

@ilike2burnthing  is your KAS red-alerting 0.16.1057 too? ... If so, can you raise a false-positive report? Thanks.

**Comment by ilike2burnthing** [comment]
Of the last 10 releases, only [v0.16.1049](https://github.com/Jackett/Jackett/releases/tag/v0.16.1049) is flagged (.exe and .zip) for Jackett's console executable.

I'm yet to see any pattern to the type of changes made which cause a detection.

https://www.virustotal.com/gui/file/30b34baefd35f71427a253d68da97648d04e0fa6a0cd6ad5c639c11611853df0/detection

https://opentip.kaspersky.com/30B34BAEFD35F71427A253D68DA97648D04E0FA6A0CD6AD5C639C11611853DF0/ - I've submitted it for manual reanalysis.

**Comment by ilike2burnthing** [comment]
Well that was quick:
```
Hello,
Sorry, it was a false detection. It will be fixed.
Thank you for your help.
Best regards, [name], Malware Analyst
```

**Comment by cocokola** [comment]
Thanks, I did report it last time, and again this time.   My hope was you could raise a concern with Kaspersky, as the Developer, to get clarification WHY they keep flagging the app, perhaps they can make a change on their side.  I just wanted you to know I have had three releases that were flagged.   But hopefully, this IS fixed now..??

**Comment by ilike2burnthing** [comment]
If this happens again, let us know. I'll submit additional detail with the sample to see if there is some solution on their part or ours which can can be made. As none are currently flagged, there's nothing for me to submit (doing so through TIP would be seen as me saying that a clean file is actually malicious).

**Comment by cocokola** [comment]
Roger, will do. Thanks close as needed

**Comment by LycanHD** [comment]
https://pastebin.com/t6NbqrEu

So nobody thinks I'm lying, here is KIS 2020 LOG

**Comment by ilike2burnthing** [comment]
No one suggested you were lying, in fact I found one of those detections 9 days ago, submitted it to Kaspersky, and they confirmed it was a false positive 2hrs later.

As I said, if it happens again, let me know so I can raise it with Kaspersky, as right now I can't do anything.
