### ISSUE TITLE
[REQ] New Private tracker pirata.digital

### ISSUE THREAD

**Issue by MarcelCosta79** [Jackett/Jackett#9448]
Hi, 

There is a new Brazillian tracker. Could it be possible to be included ?
https://pirata.digital

Right now the registrations are Open.

Thank you !!

**Comment by garfield69** [comment]
Jackett 0.16.1072

**Comment by ilike2burnthing** [comment]
https://pirata.digital/ - Error 522 - Connection timed out

May be dead - https://github.com/Jackett/Jackett/issues/13315#issuecomment-1165661658

**Comment by garfield69** [comment]
v0.20.1220
