### ISSUE TITLE
[REQUEST] new indexer bt4g

### ISSUE THREAD

**Issue by TuxNuX** [Jackett/Jackett#9449]
Hi,

can you please add the public index for the site https://bt4g.org/

Sorry if I posted my request in the wrong place :(

**Comment by garfield69** [comment]
we can add this site, but it is not going to be particularly useful to users because the results page only contains the title and magnet link. 
the category, size, release-date, seeders, leechers, grabs, and file count are not available.

There is a details page for each title, but it is not practical to fetch the details page for every title in the search results page in order to fill in the details, as that would generate up to 100 additional http GET requests, which the site may interpret as a DDoS attack.

given this, do you still want us to add this site as an indexer?

**Comment by gua1** [comment]
The results page now shows:
Type, Create time, File count, Total size, Seeders, and Leechers

https://bt4g.org/search/linux%20iso

Although the seeder and leecher count tend to be lower than the actual counts (a torrent will say 0 seeders and 4 leechers but will actually have something like 6 seeders and 10+ leechers). I'm not sure how that issue could be remedied but it should be added as a source as the original objections are solved.

**Comment by garfield69** [comment]
v0.17.605

**Comment by garfield69** [comment]
https://bt4g.org/ returns Error 502 Bad gateway

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://bt4g.org/ returning Error 502 Bad gateway

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
Down with Error 504 Ray - Gateway time-out

**Comment by ilike2burnthing** [comment]
back up

**Comment by fabh2o** [comment]
The site is back up

**Comment by ilike2burnthing** [comment]
No one said it was down.

**Comment by garfield69** [comment]
https://bt4g.org/search/2023 generates a cloudflare block
![image](https://user-images.githubusercontent.com/6933240/234106036-e96c6bc4-1ac9-4670-ab85-93cc4faff585.png)
searching for other keywords works fine.

will need to come up with some other TEST keyword that can also be used to generate the closest equivalent of the latest results, as the site does not have that page, and a black search returns not-found.

**Comment by ilike2burnthing** [comment]
The link for page 1 of results (or any other page) isn't blocked - https://bt4g.org/search/2023/1

**Comment by ilike2burnthing** [comment]
It could be an automated block, but either way we're obviously causing them an issue and so should remove it.

**Comment by garfield69** [comment]
v0.20.4013

**Comment by hbednar** [comment]
it looks like the domain has changed.
https://bt4gprx.com/

**Comment by ilike2burnthing** [comment]
@hbednar https://github.com/Jackett/Jackett/issues/14624

**Comment by kuolemaaa** [comment]
Is this site still non eligible to be on jackett? I tried to get a result page via flaresolverr and it worked. I don't get the "automation not welcomed" if flaresolverr is baked in jackett already

**Comment by ilike2burnthing** [comment]
Unless we hear from the site devs, we're not bringing it back, as they previously repeatedly blocked us.
