### ISSUE TITLE
Port change not retained through restart on Qnap

### ISSUE THREAD

**Issue by TooUnCool** [Jackett/Jackett#9453]
The title pretty much says it all. Running Jackett v0.16.1062.0 on a Qnap TS-453Pro, firmware 4.4.3

The default port is set to 25633, which I change back to 9117 but this isn't retained through a restart of Jackett, which is required quite often as it seems to crash on a daily basis (the logs don't tell me why - I do see rarbg errors but they aren't causing the crash).

One thing at a time, is there a fix for the port issue? I tried changing it manually in the qpkg config file but it made no difference.

**Comment by ilike2burnthing** [comment]
You'll need to take this up with the QNAP maintainer, but hopefully this will help - https://forum.qnap.com/viewtopic.php?t=116660&p=687827#p721558
```
When I take a look at /share/CACHEDEV1_DATA/.qpkg/JackettdotNET/JackettdotNET.sh
then I see, that Jackett is started with './jackett --IgnoreSslErrors true --Port 25633 &'.
So looks like it is ignoring the port setting in the ServerConfig.json file and using the
port in the JackettdotNET.sh file at start.
```
Presumably something similar will be happening for you, and `--Port 9117` is being used. Hopefully a simple edit will just be needed.

**Comment by TooUnCool** [comment]
Thanks. I should have checked the Qnap forum first, mea culpa.

**Comment by ilike2burnthing** [comment]
S'all good
