### ISSUE TITLE
IPTorrents - Anime Category Not Working

### ISSUE THREAD

**Issue by r1nzl3r9991** [Jackett/Jackett#946]
IPTorrents is searching for Anime under TV/Anime in Jackett. According to the website, Anime has it's own category without TV/. Can this be fixed?

**Comment by kaso17** [comment]
There's only a limited amount of predefined categories. TV/Anime is mapped to the IPT Anime category.
If you search for the TV/anime it should work perfectly fine. If it doesn't please include an enhanced log.

**Comment by sideoutdude16** [comment]
It doesn't really get mapped. I searched for Garden of Words and it did not show up in search then i searched under Anime, 4 results showed up. I would want to get this ticket re-opened again and revisit the issue.

**Comment by kaso17** [comment]
please provide the torznab query string which is used.

**Comment by sideoutdude16** [comment]
I'm not sure what you're asking and i don't know where to look 

but that is anime when i search for the anime movie, pulled from this URL

https://iptorrents.com/t?60=&q=garden+of+words&qf=#torrents

**Comment by kaso17** [comment]
Check the sonarr log for the request URL to jackett for your search.
Which one of the IPtorrents is missing from your search results?

**Comment by garfield69** [comment]
no reply. closing.
