### ISSUE TITLE
"Thank You Comment" field

### ISSUE THREAD

**Issue by vveeger** [Jackett/Jackett#9465]
Ls,
Like to use ebookparadijs.org indexer within Jacket.
This site requires a "Thank You Comment" before releasing a download.
When configurating this site with Jackett the field "Thank You Comment" is not available:
![image](https://user-images.githubusercontent.com/17788191/92356508-899af680-f0e6-11ea-9491-48dfbb97bc30.png)

Please find below a site where the field is presented correctly:
![image](https://user-images.githubusercontent.com/17788191/92356745-e5657f80-f0e6-11ea-862b-c69a49d563d9.png)

Is there a way to add this field for ebookparadijs.org ?

**Comment by garfield69** [comment]
The site must have introduced this thank-you requirement recently.

There is more to this that just adding a field in the config. 
The indexer needs to be updated to pre-post the thank you request, before initiating the download fetch.
I'll take a look and see if I can work out the necessary support code.

**Comment by vveeger** [comment]
Thanks a lot @garfield69, much appreciated!

**Comment by vveeger** [comment]
All fine now, guess was not patient enough :-)
Thanks so much!
