### ISSUE TITLE
Virus detected - Gen:Suspicious.Cloud.2.Bu0@aOylAJj

### ISSUE THREAD

**Issue by ashrafmr** [Jackett/Jackett#9478]
From the release page,
https://github.com/Jackett/Jackett/releases/tag/v0.16.1114

Installation of the Windows executable, Jackett.Installer.Windows.exe is blocked by BitDefender. BitDefender reports the presence of a virus in  C:\ProgramData\Jackett\JackettConsole.exe.

Gen:Suspicious.Cloud.2.Bu0@aOylAJj

**Comment by garfield69** [comment]
use your BitDefender app to report a false positive.
VirusTotal reports 0 hits from all its 79 detectors for both the zip and exe packages of 0.16.1114
https://www.virustotal.com/gui/url/d53b503177ab8341f3a11cc377a021a01950df828973b81f93370b10374a0efe/detection
https://www.virustotal.com/gui/url/1c80c2e4d99878f2465b990dfba45526a7d8d7f7ddf8e05e3de8c249a8add37a/detection
