### ISSUE TITLE
IPTorrents not working on 0.7.885

### ISSUE THREAD

**Issue by hdubb** [Jackett/Jackett#948]
I updated Jackett on Windows 10 and I try to add indexer.

I click on add indexer-IPTorrents- and enter my username and password.

They are correct and when I press Okay, it says configuration failed.

I suspect that the Recaptcha is the problem. It says Localhost is not in the list of supported domains for this site key.

The log says:
	Warn	
Rejected a request to IPTorrents which is unconfigured.

**Comment by kaso17** [comment]
access jackett using the ip (127.0.0.1) instead of localhost to workaround the recaptcha issue.
