### ISSUE TITLE
[demonoid] Clearance failed after 10 attempt(s). (Config)

### ISSUE THREAD

**Issue by RossDanbyGamer** [Jackett/Jackett#9480]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker - Linuxserver

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: N/A

**Jackett Version**:  Latest

**Are you using a proxy or VPN?** [no]

### Description

Followed the instructions to add Demonoid to Jackett via Cookies but after hitting okay I get a message which says:

An error occurred while updating this indexer
Clearance failed after 10 attempt(s).

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
demonoid have enabled full anti-DDoS protection ATM.
There is nothing Jackett can do as there is currently no automated way to solve the challenge.
there is an experimental ticket #9029 but this has stalled so do not expect a solve anytime soon.
for now you will not be able to use the demonoid Jackett indexer until the site lifts the protection.
access the site with your browser instead.
