### ISSUE TITLE
[turkseed] Login failed: Selector

### ISSUE THREAD

**Issue by buhtig176** [Jackett/Jackett#9482]
### Environment

**OS**: Windows 7

**.Net Runtime**: [.Net-Framework]

**.Net Version**: 4.8

**Jackett Version**: Jackett Version 0.16.1114.0

**Last Working Jackett Version**: Not Sure

**Are you using a proxy or VPN?** [yes]

### Description

Cannot add this indexer although logged in in another tab.

### Logged Error Messages

 An error occurred while updating this indexer
Login failed: Selector "a[href*="/logout.php?logouthash="]" didn't match
Click here to open an issue on GitHub for this indexer.

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
the turkseed indexer works for me which suggest the problem is at your end.
review how to fetch the cookie for the turkseed config cookie box, see https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work

**Comment by buhtig176** [comment]
I already did that, and repeated several times after your response, but no luck - same issue, Any hint would be appreciated.

**Comment by garfield69** [comment]
Please provide an full **enhanced** log. Perhaps the extra debug and HTML included may yield a clue.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by buhtig176** [comment]
Thanks for your response. Here it is.
[log2.txt](https://github.com/Jackett/Jackett/files/5204748/log2.txt)

**Comment by garfield69** [comment]
looks like turkseed is responding with 
```
Sunucu şu anda çok meşgul. Lütfen daha sonra tekrar deneyiniz.
```
google translate
```
The server is currently too busy. Please try again later.
```
when you fetch the cookie, are you using a browser running on the same machine that is running Jackett and going through the same active VPN?
when you copy the cookie, you are selecting everything after the `cookie: ` from the correct **network** page **Headers** tab, and not from the _cookie_ tab on that _network_ page?

**Comment by garfield69** [comment]
looks like the site is genuinely offline ATM
using https://turkseed.com/ returns
![image](https://user-images.githubusercontent.com/6933240/92826912-5b3e5380-f425-11ea-813f-e67f98d0e340.png)

**Comment by buhtig176** [comment]
I have definitely picked proper cookie, selecting everything after the cookie: from the correct network page Headers tab, and not from the cookie tab on that network page. Also, as I wrote in the first message, it happens in the same browser, while I am logged in in another tab. Both tabs  use the same connection (over VPN). I'd be veru grateful for any further hint (maybe my umatrix and Trace plugins cause some problems with this particular site?)

I am aware of the current dificulties with the site, but the issue happened before this started. It looks like Turkish trackers have problems recently. BroadCity went offline for good it seems, for example...

**Comment by garfield69** [comment]
so the VPN you are using is active across the whole machine, so that when you start your browser session the VPN has already allocated one server?
and when you run Jackett you are not using the proxy options, just relying on the same VPN using the same session server that was used when you grabbed the cookie from the browser?

I'm asking, because some web sites cookies lock the IP address, so if the VPN session used for the browser is not using the same VPN server as the one that gets used for Jackett, then the cookie will not be accepted when Jackett uses it to access the server.

So to confirm, the enhanced log you provided earlier was taken when you had freshly logged into the turkseed website with your browser, captured the cookie then edited the jackett config and pasted the cookie there? 

if not then please retry the enhanced log capture. Remember, we need a fresh login on the site with your browser, and that cookie used in the Jackett while the enhanced logging is enabled. I'm not saying this will provide an answer but it may be of use.

**Comment by garfield69** [comment]
re: broadcity the website has just come back online.

**Comment by buhtig176** [comment]
Sorry fro English is not my first language, but please let me know if my answer properly reflects your questions.

VPN was already on. Browser opened. Jackett upped and tested Turkseed there - issue happens. Opened Turkseed under such conditions in a new tab -so fresh session on the tracker, and logged in. Picked up cookie there, and pasted it back into Jackett's Turkseed config window, No VPN servers changes in between. Issue remains. The only other thing that comes to my mind now is that I will check under which country I have registered there on Turkseed, I will then choose server from that country and will do a fresh new session to Turkseed to pick up a cookie (although it shiuld be the same, right?), once if it became online again.

If I misunderstood your message, I sincerely apologize for wasting your time.

**Comment by buhtig176** [comment]
Changing server to IP from a country I registered on didn't help. Now if I can recall it, I have actually succede to logon to Turkseed via Jackett...

**Comment by garfield69** [comment]
I am sorry but there is nothing more I can suggest other than to try a different VPN provider.
@ngosang  @cadatoiva  @ilike2burnthing  any input for this ticket you can provide?

**Comment by ilike2burnthing** [comment]
Same process as #9490 with the same result - IP restricted only

Cookie format:
```
__cfduid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; countrytabs=0; users_resolution=1920x1080; c_secure_uid=nnnnn; c_secure_pass=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
n = numbers only
x = numbers and letters

You mentioned using the extension Trace, depending on your settings it can screw with referer headers, cookies, reported screen resolution, and a bunch more. May be worth logging out, disabling Trace (or adding the site to its whitelist), logging back in, and getting a new cookie to use in Jackett.

**Comment by garfield69** [comment]
turkseed down for maintenance ATM #7753

**Comment by buhtig176** [comment]
Thanks for all the responses.

For both turkseed.com and broadcity.in the solution was to whitelist them in Trace, and in umatrix to allow ajax.cloudflare script for turkseed, beside everything for the domain. On refresh, I was automatically logged out, logged in picked up the cookie, pasted it in Jacket and eeverything worked. I think mismatches in resolution caused the issue (diffirenet onese were reported in cookice under Trace and after whitelisted), but I'll try to fine tune Trace to allow as minimum as possible.

Thank you for the ideas. Closing the issue.

**Comment by ilike2burnthing** [comment]
In Trace's whitelist entry for the site you should be able to leave most enabled. Those you might want to test disabling would be Referer Controller, Proxy IP Header Spoofing, User-Agent Randomiser, and Screen Resolution Tracking.

You can play about with those to see which, if any, can be enabled or tweaked. In the Cookie Eater's cookie list, I have them all enabled apart from __cfduid, and in Referer Controller I have header and full URL enabled for same hostname and domain, both disabled for third party - plays better with Cloudflare.

**Comment by buhtig176** [comment]
Thnaks for the tips!
