### ISSUE TITLE
Feature/web client Rename RSS

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#9489]
@moralia wrote in #9488 Hi. Would it be possible to use a rename for specific Sonarr searches?

All of us who are not English, in my case Spanish, have problems with the names of the series in Sonarr, different titles and with which, it cannot be found in the trackers. An example is :

Combat Hospital / Hospital de Campaña

It's possible to add a "dictionary" to change those titles?

Thank you so much !

**Comment by ngosang** [comment]
@moralia Sonarr does it for you. If you configure the language to "Spanish" in Sonarr for one TV series, Sonarr will try several searches:
* Original title (english)
* Alternative titles (english)
* Spanish title

It's working well with DivxTotal and Newpct trackers for example.
