### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Got redirected to another domain. Try changing the indexer URL to https://pirateproxy.cloud/. Updated site link, please try again.: Parse error (Test)

### ISSUE THREAD

**Issue by ZakaRehman** [Jackett/Jackett#9491]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu 20.04

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono

**.Net Version**: 6.12.0.90 

**Jackett Version**: 0.16.1128.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
change url for thepiratebay indexer using the wrench icon but it fails the test.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
[log.txt](https://github.com/Jackett/Jackett/files/5208525/log.txt)

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
pirateproxy.cloud uses TPB's new HTML and therefore isn't currently compatible with Jackett.

Do none of the listed proxies work for you either in Jackett or in browser?

**Comment by ZakaRehman** [comment]
i get this exception on every other proxies listed for thepiratebay
Exception (thepiratebay): The handshake failed due to an unexpected packet format.: The SSL connection could not be established, see inner exception.

**Comment by ilike2burnthing** [comment]
And in browser?

**Comment by ZakaRehman** [comment]
the browser doesn't work either gives SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by ilike2burnthing** [comment]
K, so presumably your ISP is blocking them then. You'll either need to find another TPB proxy which uses the old HTML (I will have a look as well), or use a VPN to allow you to access those sites.

**Comment by ilike2burnthing** [comment]
https://piratebay.live/ is the only other one I could find which is still using the old HTML without significant changes of its own

**Comment by ilike2burnthing** [comment]
From [v0.16.1340](https://github.com/Jackett/Jackett/releases/tag/v0.16.1340) TPB now uses the new API with other proxy sites available, e.g. pirateproxy.cloud, so it should now work for you.
