### ISSUE TITLE
[REQ] Add tracker Libertalia

### ISSUE THREAD

**Issue by itdaboyz** [Jackett/Jackett#95]
Hi,

I would like to have Libertalia.me (french private tracker) added.

Here is the mapping:
AddCategoryMapping("5", TorznabCatType.Console);
AddCategoryMapping("5.0", TorznabCatType.ConsoleNDS);
AddCategoryMapping("5.2", TorznabCatType.ConsolePSP);
AddCategoryMapping("5.5", TorznabCatType.ConsoleWii);
AddCategoryMapping("5.6", TorznabCatType.ConsoleXbox);
AddCategoryMapping("5.6", TorznabCatType.ConsoleXbox360);
AddCategoryMapping("5.3", TorznabCatType.ConsolePS3);
AddCategoryMapping("5.0", TorznabCatType.Console3DS);
AddCategoryMapping("5.2", TorznabCatType.ConsolePSVita);
AddCategoryMapping("5.5", TorznabCatType.ConsoleWiiU);
AddCategoryMapping("5.6", TorznabCatType.ConsoleXboxOne);
AddCategoryMapping("5.4", TorznabCatType.ConsolePS4);
AddCategoryMapping("3", TorznabCatType.Movies);
AddCategoryMapping("4", TorznabCatType.Movies);
AddCategoryMapping("12", TorznabCatType.MoviesOther);
AddCategoryMapping("3.1", TorznabCatType.MoviesSD);
AddCategoryMapping("3", TorznabCatType.MoviesHD);
AddCategoryMapping("3.5", TorznabCatType.MoviesBluRay);
AddCategoryMapping("3.0", TorznabCatType.MoviesDVD);
AddCategoryMapping("8", TorznabCatType.Audio);
AddCategoryMapping("8.0", TorznabCatType.AudioMP3);
AddCategoryMapping("8.1", TorznabCatType.AudioMP3);
AddCategoryMapping("8.3", TorznabCatType.AudioMP3);
AddCategoryMapping("6.2", TorznabCatType.AudioAudiobook);
AddCategoryMapping("8.2", TorznabCatType.AudioLossless);
AddCategoryMapping("8.4", TorznabCatType.AudioLossless);
AddCategoryMapping("8.5", TorznabCatType.AudioOther);
AddCategoryMapping("11", TorznabCatType.PC);
AddCategoryMapping("7", TorznabCatType.PCMac);
AddCategoryMapping("5.1", TorznabCatType.PCGames);
AddCategoryMapping("9", TorznabCatType.TV);
AddCategoryMapping("2", TorznabCatType.TV);
AddCategoryMapping("9.0", TorznabCatType.TVSD);
AddCategoryMapping("9.1", TorznabCatType.TVHD);
AddCategoryMapping("10", TorznabCatType.TVAnime);
AddCategoryMapping("1", TorznabCatType.TVDocumentary);
AddCategoryMapping("0", TorznabCatType.OtherMisc);
AddCategoryMapping("6", TorznabCatType.Books);

You can PM me for other information or for an invite.

Thanks in advance !

**Comment by flightlevel** [comment]
Duplicate https://github.com/Jackett/Jackett/issues/22
