### ISSUE TITLE
[Req] eStone

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#950]
Indexer Name
eStone

Type
General - Movies, TV, Audio, PC, XXX, Other

Indexer URL
http://estone.cc/

Indexer Language
Hungarian

Invite
Sent

**Comment by kaso17** [comment]
added with d46fe3f3c7d46f79ab332792180adf5c527bda0c

**Comment by garfield69** [comment]
http://estone.cc/ ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online
