### ISSUE TITLE
Review alternative site domains

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9500]
Some of them are OK. Most 503 errors are caused by Couldflare but we can keep those links.
@garfield69 @ilike2burnthing Could you handle this? I have recently changed my place of residence and I have a lot of backlog on this and other projects.

- [x] 1337x || https://1337x.gd/ || Bad HTTP response code: 503
- [x] 1337x || https://1337x.is/ || Bad HTTP response code: 503
- [x] 1337x || https://1337x.st/ || Bad HTTP response code: 503
- [x] 1337x || https://x1337x.ws/ || Bad HTTP response code: 503
- [x] 1337x || https://x1337x.eu/ || Bad HTTP response code: 503
- [x] 1337x || https://x1337x.se/ || Bad HTTP response code: 503
- [x] abnormal || https://abnormal.ws/ || HTTPSConnectionPool(host='abnormal.ws', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(, 'Connection to abnormal.ws timed out. (connect timeout=60)'))
- [x] anidex || https://anidex.info/ || Bad HTTP response code: 403
- [x] animebytes || https://animebytes.tv/ || Bad HTTP response code: 522
- [x] broadcity || http://broadcity.in/ || HTTPConnectionPool(host='broadcity.in', port=80): Read timed out. (read timeout=60)
- [x] brobits || https://brobits.cc/ || Bad HTTP response code: 522
- [x] btdb || https://btdb.eu/ || Bad HTTP response code: 503
- [x] btdigg || https://btdig.com/ || Bad HTTP response code: 503
- [x] btschool || https://pt.btschool.club/ || Bad HTTP response code: 503
- [x] btsow || https://btsow.website/ || Bad HTTP response code: 302
- [x] cztorrent || https://tracker.cztorrent.net/ || Bad HTTP response code: 301
- [x] digitalhive || https://www.digitalhive.org/ || Bad HTTP response code: 522
- [x] documentarytorrents || http://www.documentarytorrents.com/ || HTTPConnectionPool(host='www.documentarytorrents.com', port=80): Read timed out. (read timeout=60)
- [x] epizod || https://wwv.epizod.tv/ || Bad HTTP response code: 403
- [x] exttorrents || https://t.extto.com/ || Bad HTTP response code: 301
- [x] eztv || https://eztv.unblockit.top/ || Bad HTTP response code: 503
- [x] glodls || https://gtdb.to/ || Bad HTTP response code: 301
- [x] hdarea || https://www.hdarea.co/ || Bad HTTP response code: 403
- [x] hdchina || https://hdchina.org/ || Bad HTTP response code: 302
- [x] hddisk || https://hddisk.life/ || HTTPSConnectionPool(host='hddisk.life', port=443): Max retries exceeded with url: / (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused'))
- [x] hdhome || https://hdhome.org/ || Bad HTTP response code: 302
- [x] hdtorrentsit || https://hdtorrents.xyz/ || Bad HTTP response code: 404
- [x] hdturk || https://hdturk.de/ || HTTPSConnectionPool(host='hdturk.de', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(, 'Connection to hdturk.de timed out. (connect timeout=60)'))
- [x] hdu || https://pt.upxin.net/ || Bad HTTP response code: 302
- [x] hdzone || https://hdzone.me/ || Bad HTTP response code: 302
- [x] iptorrents || https://ipt.rocks/ || HTTPSConnectionPool(host='ipt.rocks', port=443): Max retries exceeded with url: / (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known'))
- [x] kickasstorrent || https://newkatcr.co/ || HTTPSConnectionPool(host='newkatcr.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(, 'Connection to newkatcr.co timed out. (connect timeout=60)'))
- [x] kickasstorrent || https://kat.root.yt/ || Bad HTTP response code: 403
- [x] kickasstorrent || https://kat.unblockit.top/ || Bad HTTP response code: 302
- [x] kickasstorrent || https://katcr.unblocked.rest/ || Bad HTTP response code: 504
- [x] leporno || http://leporno.org/ || HTTPConnectionPool(host='leporno.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(, 'Connection to leporno.org timed out. (connect timeout=60)'))
- [x] moecat || https://moecat.best/ || Bad HTTP response code: 523
- [x] monova || https://monova.org/ || Bad HTTP response code: 503
- [x] monova || https://monova.to/ || Bad HTTP response code: 503
- [x] monova || https://monova.unblockit.id/ || Bad HTTP response code: 301
- [x] monova || https://monova.unblocked.rest/ || Bad HTTP response code: 503
- [x] nyaasi || https://nyaa.root.yt/ || Bad HTTP response code: 402
- [x] oshenpt || https://www.oshen.win/ || Bad HTTP response code: 302
- [x] pt99 || https://pt.j99.info/ || HTTPSConnectionPool(host='pt.j99.info', port=443): Max retries exceeded with url: / (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -5] No address associated with hostname'))
- [x] shellife || https://shellife.eu/ || HTTPSConnectionPool(host='shellife.eu', port=443): Read timed out. (read timeout=60)
- [x] spacetorrent || https://www.spacetorrent.cloud/ || Bad HTTP response code: 503
- [x] tenyardtracker || https://tenyardtracker.com/ || Bad HTTP response code: 301
- [x] torrent-turk || https://torrent-turk.de/ || Bad HTTP response code: 521
- [x] torrent9 || https://www.torrent9.is/ || Bad HTTP response code: 301
- [x] torrentbomb || https://torrent.movie/ || Bad HTTP response code: 403
- [x] torrentccf || https://et8.org/ || Bad HTTP response code: 302
- [x] torrentproject2 || https://torrentproject.cc/ || Bad HTTP response code: 302
- [x] torrentseed || https://torrentseed.cl/ || HTTPSConnectionPool(host='torrentseed.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
- [x] zelkaorg || http://zelka.org/ || HTTPConnectionPool(host='zelka.org', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(, 'Connection to zelka.org timed out. (connect timeout=60)'))
- [x] zelkaorg || http://zamunda.se/ || HTTPConnectionPool(host='zamunda.se', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(, 'Connection to zamunda.se timed out. (connect timeout=60)'))

**Comment by ilike2burnthing** [comment]
**Down**
https://abnormal.ws/ - ERR_CONNECTION_CLOSED
https://brobits.cc/ - Error 522 - Connection timed out
https://www.digitalhive.org/ - Error 522 - Connection timed out
https://hddisk.life/ - ERR_CONNECTION_CLOSED
https://hdtorrents.xyz/ - 404 Not Found
https://ipt.rocks/ - ERR_NAME_NOT_RESOLVED
https://moecat.best/ - Error 523 - Origin is unreachable
https://nyaa.root.yt/ - 402 Payment Required
https://shellife.eu/ - ERR_TIMED_OUT
https://torrent-turk.de/ - Error 526 - Invalid SSL certificate
https://torrentseed.cl/ - ERR_NAME_NOT_RESOLVED
http://zelka.org/ - ERR_EMPTY_RESPONSE
http://zamunda.se/ - ERR_EMPTY_RESPONSE

**Down with open issue**
https://tracker.cztorrent.net/ - #1151 
https://newkatcr.co/ and proxies - #9132 
http://leporno.org/ - #5709 
https://monova.org/ and proxies - #4447 
https://pt.j99.info/ - #4147 (site closed)

**Back up**
http://broadcity.in/ - #6662 

**Alternate DDoS Protection**
https://anidex.info/ - up, but uses DDoSGuard

**Up, but I have no account**
https://animebytes.tv/
http://www.documentarytorrents.com/
https://www.hdarea.co/
https://hdchina.org/
https://hdhome.org/
https://hdturk.de/
https://pt.upxin.net/
https://hdzone.me/
https://www.oshen.win/
https://www.spacetorrent.cloud/
https://et8.org/

**Needs updated**
https://btsow.website/ - `*.online` - https://tellme.pw/btsow
https://t.extto.com/ - `torrent.*`
https://gtdb.to/ - `www.*`
https://tenyardtracker.com/ - `talk.*` - I have no account
https://www.torrent9.is/ - `*.gg`
https://torrentproject.cc/ - `*2.com`

**Comment by ngosang** [comment]
Thank you both. Can it be closed?
