### ISSUE TITLE
[xspeeds] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by Jayark365** [Jackett/Jackett#9507]
I submitted this exact issue a long time ago, and it still doesn't work. Is it ever going to get fixed? Or is it just permanently broken?

### Environment

**OS**: windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] latest

**.Net Version**: latest

**Jackett Version**: latest

**Last Working Jackett Version**: none

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
input login, click okay. Error.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
Object reference not set to an instance of an object.

[Make sure you attach the full logs with your personal information removed in case we need more information]
[log.txt](https://github.com/Jackett/Jackett/files/5213046/log.txt)

### Screenshots

[Place any screenshots of the issue here if needed]
![Screenshot_1](https://user-images.githubusercontent.com/637445/93001544-5c3eb600-f4f5-11ea-8cf5-8f600afb1cc5.png)

**Comment by Jayark365** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/637445/93002078-afb30300-f4f9-11ea-9556-66187fbdec0e.png)

Now its saying this.... Please fix this. I will be livid if my account gets banned because of bad code.

**Comment by seeyabye** [comment]
If you have an invite, I can take a look and fix this (send it to seeyable @ protonmail.com)

Otherwise, you will need to wait for @cadatoiva to fix this.

**Comment by JakeShirley** [comment]
@Jayark365 it looks like your IP may have already been banned from the looks of that last image.

**Comment by Jayark365** [comment]
> 
> 
> @Jayark365 it looks like your IP may have already been banned from the looks of that last image.

Luckily I was using a socks5 proxy from one of my personal servers, so that was banned and not my account. You can close this, leave it open or whatever. I have no intention on attempting to use this again. I still have my account and as this is my only private tracker, I'd prefer to keep it alive.
