### ISSUE TITLE
Kaspersky + Jackett = Removed Virus

### ISSUE THREAD

**Issue by LycanHD** [Jackett/Jackett#9510]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10 Pro x64

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Any of them

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] No

### Description

This has been a problem for years. No matter how many exclusions I set, Kaspersky and even defender will delete parts of it.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
And the only solution is to use your security app to report a false positive and get the signature update when its next published for the app.
there is nothing than can be done from the Jackett code side, since there is not fault with the Jackett app, and other security apps do not currently flag Jackett incorrectly.

**Comment by LycanHD** [comment]
Defender does the same. No other software does this; NZBHydra2, Sonarr or Radarr.

**Comment by garfield69** [comment]
virustotal gives a clean bill of health to all the pachages in 0.16.1138
v0.16.1138/Jackett.Binaries.LinuxAMDx64.tar.gz https://www.virustotal.com/gui/url/c9420b5368499738c813b6cc8210a12b9b02bde53b7329f8d8461420f0ae2a1b/detection
v0.16.1138/Jackett.Binaries.LinuxARM32.tar.gz https://www.virustotal.com/gui/url/2a3461b91a69c15e3d13f4a6dc3a2afadbe96aa2d06d5d6756d0151421fb2123/detection
v0.16.1138/Jackett.Binaries.LinuxARM64.tar.gz https://www.virustotal.com/gui/url/d853109220d84a862eb1833cf1a89f80705e86c212f6e58c23d421b66b0d287e/detection
v0.16.1138/Jackett.Binaries.macOS.tar.gz https://www.virustotal.com/gui/url/0ef317ceddd93ed5604143c69542596618a4d138629f520d6d5cd72f7d85461a/detection
v0.16.1138/Jackett.Binaries.Mono.tar.gz https://www.virustotal.com/gui/url/eccaf087171ef9fc60ff235efca869ccecf24a1ecd7f2ff316e1dd05d02e9b6b/detection
v0.16.1138/Jackett.Installer.Windows.exe https://www.virustotal.com/gui/url/9ffb881f2796fa855c3c6e7c40838549eb9df5f5b5d82f67781189c146e21a16/detection
v0.16.1138/Jackett.Binaries.Windows.zip https://www.virustotal.com/gui/url/f4924b46ba593b77f648c2fbbf59b1c9b751103ff61b76b82e348447c3590ce8/detection

**Comment by ilike2burnthing** [comment]
LycanHD, please see my comment here - https://github.com/Jackett/Jackett/issues/9445#issuecomment-689785387

I've just scanned the last 10 releases, plus the current pre-release, (.exe .zip and unpacked) with KIS 2021 using deep heuristics and the latest signatures; 0 detections from over 37k objects scanned.

v0.16.1138 .zip - https://www.virustotal.com/gui/file/2e4604e2d9167ee19931e0496129793da2247c207209854ca16cfbc2a684916e/detection

v0.16.1138 .exe - https://www.virustotal.com/gui/file/f36114abeccc9e77ac84bac18a73cc00ff576bf09caf59cc75776768ef74a6d8/detection
https://www.hybrid-analysis.com/sample/f36114abeccc9e77ac84bac18a73cc00ff576bf09caf59cc75776768ef74a6d8
https://app.any.run/tasks/aa05fd4a-2bca-4988-b856-8151e42174f5

There's nothing actually malicious to be found, it's just MS Defender being MS Defender. Hopefully Kaspersky has resolved the issue on their end, but if it happens again then let me know.
