### ISSUE TITLE
ebooks-shares: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9512]
![image](https://user-images.githubusercontent.com/10577978/93013738-979bbc00-f5ab-11ea-90fa-9163e5616af4.png)
![image](https://user-images.githubusercontent.com/10577978/93013749-a71b0500-f5ab-11ea-829e-df2561443bf5.png)

**Comment by garfield69** [comment]
I don't have an A/C on this site. can you dump the search page with the categories?
