### ISSUE TITLE
[New Tracker REQ] UltraHDClub 

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#953]
Indexer Name
UltraHDClub

Type
TV, Movies in 2160p / 4K / UHD

Indexer URL
http://ultrahdclub.org/

Indexer Language
Russian, Ukrainian, English

Invite
To receive an invite, go to: http://ultrahdclub.org/signup.php. Choose option 1, and send a message to the Admin stating the purpose of becoming a member of UltraHDClub. Provide the link to your HDClub profile, as well as links to other profiles of yours on a few HD trackers. You should receive an email within a week or so with an invite link.

**Comment by kaso17** [comment]
application sent

**Comment by kaso17** [comment]
added with 0a6d2b30b560cd633c2b6a05235e7f0b6ddf48a4

**Comment by kaso17** [comment]
anyone knows if the're gone for good?
