### ISSUE TITLE
[lostfilm] Exception (lostfilm): certificate validation failed: [Subject]  O=Internet Widgits Pty Ltd, S=Some-State, C=AU[Issuer]  O=Internet Widgits Pty Ltd, S=Some-State, C=AU[Serial Number]  00F5BA2E609C91DBB4[Not Before]  10/13/2014 4:46:03 PM[Not After]  11/12/2014 3:46:03 PM[Thumbprint]  5D8A25EB8B9C46981F007D105007113B97CA9BE6: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by SuberSeb** [Jackett/Jackett#9537]
Got this error with lostfilm. Jackett in docker.

**Comment by garfield69** [comment]
https://www.lostfilm.run/ uses a certificate with thumbpirnt 25234600906df82792de9f4aa75a5aed2f226577 which is a valid certificate.

your indexer is reporting a certificate with a thumbprint of 5D8A25EB8B9C46981F007D105007113B97CA9BE6

so either you ar not using https://www.lostfilm.run/ as a SiteLink in you lostfilm config, 
OR
your ISP (or the one your VPN provider is using, or a security app) is blocking your access to the site and presenting a blocking page or blackhole that uses that invalid certificate.

**Comment by garfield69** [comment]
I see that the lostfilm indexer has an alternate Sitelink for https://www.lostfilm.tv/ that uses 5d8a25eb8b9c46981f007d105007113b97ca9be6

since this domain is returning ERR_TIMED_OUT I'll drop it from the indexer in the next releat of Jackett.
