### ISSUE TITLE
Add https://www.kinopoisk.ru as optional source for metadata

### ISSUE THREAD

**Issue by T-REX-XP** [Jackett/Jackett#954]
Please add new metadata source https://www.kinopoisk.ru, that will be used for russian(ru-ru) trackers (cardigans). Now ru-ru cardigans are worked, but Sonarr wasnt found updates for tv shows (( thanks

**Comment by kaso17** [comment]
what is jackett supposed to do with kinopoisk?

**Comment by T-REX-XP** [comment]
sorry, its my mistake, its feature request for Sonarr, but not for jackett.
