### ISSUE TITLE
[bB] Clicking on description link results in torrent file download

### ISSUE THREAD

**Issue by janot** [Jackett/Jackett#9541]
Should open corresponding webpage instead

**Comment by garfield69** [comment]
Are you're talking about the Jackett dashboard indexer results page, and clicking on the name link not taking you to the torrent details page on the web site?

If so, can you dump the HTML from a search result page on the bb website, so I can take a look?
Follow https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source
thanks.

**Comment by janot** [comment]
Yes

https://pastebin.com/6JdtawvZ

**Comment by garfield69** [comment]
try out Jackett 0.16.1269 and see if I managed to get it right.

**Comment by janot** [comment]
fixed
