### ISSUE TITLE
[CrazySpirit] search works but download failed

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#9548]
Hello !
Jackett Version 0.16.1231.0
Windows 10 x64
When we click on manual download on a manual search, we are unable to download the torrent file. When I try from Radarr, same problem.
Thanks !

**Comment by garfield69** [comment]
looks like the web site has changed their download link signature. 
I'll see if I can get the indexer working with the new download method.

**Comment by pipopop** [comment]
Works great ! Thanks !
