### ISSUE TITLE
[LeChaudron] search works but download failed

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#9550]
Hello !
Jackett Version 0.16.1231.0
Windows 10 x64
When we click on manual download on a manual search, we are unable to download the torrent file.
Thanks !

P.S. : same "front end site"(sorry I don't know the word for this) as Galeriens, and CrazySpirit. I think it's Torrent Trader. And I think it's an old issue.

**Comment by garfield69** [comment]
looks like the web site has implemented a thankyou requirement before downloading can begin.
but this one is different yet again from either CrazySpirit or Galeriens.
the thankyou is a form and looks like
```html
    <form method="post" action="https://lechaudron.nl/TTV3/Torrents/5610/remercier">
        <input type="hidden" name="torrent" value="5610">
        <button type="submit" title="Remercier l&apos;utilisateur pour son travail" value="Remercier l&apos;utilisateur pour son travail" style="border='0' background: transparent">
            <img src="https://lechaudron.nl/images/Généralités/remercier.gif'' width="85" height="20"/>
        </button>
    </form>
```
The current Cardigann indexer cannot extract the 5610 from the details path that the download block is given, so I cannot build the thankyou path or the hidden input torrent value.
This indexer will need to be rewritten on c#

**Comment by garfield69** [comment]
found yaml indexer  fouducinema is using similar method as LeChaudron.
I will take another look at this indexer.

**Comment by garfield69** [comment]
Ah, but the issue raised in #9549 is a factor. Awaiting @ngosang  response to variable substitution on the download block before path.

**Comment by garfield69** [comment]
Got this one working! Yay.

**Comment by garfield69** [comment]
Jackett 0.16.1252

**Comment by pipopop** [comment]
Works great ! Thanks !
