### ISSUE TITLE
Add opportunity for update definitions(cardigans) from github without update main distributive 

### ISSUE THREAD

**Issue by T-REX-XP** [Jackett/Jackett#956]
Add opportunity for update definitions(cardigans) from github without update main distributive.

**Comment by T-REX-XP** [comment]
sorry, its my mistake, its feature request for Sonarr, but not for jackett.

**Comment by kaso17** [comment]
Currently we're still adding new features/fixing bugs to the cardigann parser making jackett base updates mandatory in many cases. Besides that not all trackers can be implemented as cardigann definitions.

**Comment by T-REX-XP** [comment]
Thanks for your reply. in my case, i use Jackett on Synology nas, and package Jackett that updates very slowly for my platform.

**Comment by kaso17** [comment]
As far as I understand the auto update feature works fine with the synology packages.

**Comment by Dr-Bean** [comment]
@kaso17 Correct :)...and the initial version isn't _that_ old, is it? We're at 0.7.806

**Comment by T-REX-XP** [comment]
Thanks, now i test update function in jackett. Its work fine))
