### ISSUE TITLE
[Horrible Subs] found no results after refactor of webclient

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#9568]
Works - v0.16.1252 - both Docker and Windows, with or without proxy/VPN, httpwebclient or netcore

Fails - v0.16.1260 - both Docker and Windows, with or without proxy/VPN

LiaorenCili also fails (all other public indexers seem to be OK), and apparently so does speed.cd - #9563 

[log - HS - 1260.txt](https://github.com/Jackett/Jackett/files/5251890/log.-.HS.-.1260.txt)
[log - LC - 1260.txt](https://github.com/Jackett/Jackett/files/5251891/log.-.LC.-.1260.txt)

**Comment by ngosang** [comment]
@ilike2burnthing Ok, they are not working for me, but I don't get the error, just "0 results".
I need more details. Are you running Docker on Windows or Linux?

**Comment by garfield69** [comment]
Jackett 0.16.1269 should restore functionality.

**Comment by ilike2burnthing** [comment]
Docker is on a Linux-based NAS
