### ISSUE TITLE
not run:  /proc/self/fd/9: line 2: chdir: command not found

### ISSUE THREAD

**Issue by kestouf** [Jackett/Jackett#958]
Hi I try install Jackett ok Synology (DSM 6) And I have this error on jackett log:
2017-01-18T13:37:19+0100 /proc/self/fd/9: line 2: chdir: command not found
Please.
Kestouf

**Comment by kaso17** [comment]
Please try the instructions in #913

**Comment by armani316** [comment]
@kestouf Did you manage to follow the instructions in #913? Did that solve the issue?

**Comment by armani316** [comment]
@kestouf I'll close this issue for now. If the instructions in #913 did not help solve the problem, please feel free to reopen this issue.
