### ISSUE TITLE
oxtorrent : bad definition for download link

### ISSUE THREAD

**Issue by guillaume-gta** [Jackett/Jackett#9585]
Jackett Version 0.16.1260.0 

in oxtorrent.yml, in : 

settings:
  - name: downloadlink
    type: select
    label: Download link
    default: "magnet:?xt="
    options:
      "/telecharger/": ".torrent"
      "magnet:?xt=": "magnet"

"/telecharger/" should be replaced by "get_torrents".

I have modify the file in my local env and tested, I am able to download torrent files from oxtorrent.

Thanks in advance
Guillaume

**Comment by garfield69** [comment]
Jackett 0.16.1307

**Comment by guillaume-gta** [comment]
Thanks a lot for the quick fix.

Regards
