### ISSUE TITLE
Internal log view broken after v0.16.759

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#9590]
Just noticed that when viewing the log from within Jackett it reads as:
`Executed action {ActionName} in {ElapsedMilliseconds}ms`
`Connection id "{ConnectionId}" sending FIN because: "{Reason}"`

Whereas in the log file it reads correctly as:
`Executed action Jackett.Server.Controllers.ServerConfigurationController.Config (JackettConsole) in 8.9645ms`
`Connection id "0HM2UGUCC41M3" sending FIN because: "The Socket transport's send loop completed gracefully."`

Only placeholder labels are displayed in Jackett's log view, instead of the relevant values like in the actual log file.

I tracked it back to [v0.16.759](https://github.com/Jackett/Jackett/releases/tag/v0.16.759) being the start of the issue (v0.16.745 and before work fine, those after don't), with https://github.com/Jackett/Jackett/commit/d1c41ab5859c6ba35a7a019372b3ee08f88aacc3 seeming to be responsible.

**Comment by garfield69** [comment]
Good find! And back tracking 77 generations was rather persistent of you 8-)
