### ISSUE TITLE
[eztv] Exception (eztv): The method or operation is not implemented.: The method or operation is not implemented. (Test)

### ISSUE THREAD

**Issue by DevilXSasuke** [Jackett/Jackett#9594]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:Synology  DSM 6.2.3-25426 Update 2

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono

**.Net Version**:

**Jackett Version**:0.14.485-10

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]no

### Description

i can't do any search or test

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

 An error occurred while testing this indexer
Exception (1337x): The method or operation is not implemented.: The method or operation is not implemented.

### Screenshots

[Place any screenshots of the issue here if needed]
![image](https://user-images.githubusercontent.com/43011263/93851501-4d0ff300-fcc1-11ea-9840-2e223882a185.png)

**Comment by garfield69** [comment]
Update your Jackett to version 0.16.1307
