### ISSUE TITLE
[1337x] Exception (1337x): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /spksrc/spk/mono/work-x64-6.1/mono-5.20.1.34/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by DevilXSasuke** [Jackett/Jackett#9606]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: DSM 6.2.3-25426 Update 2

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:v0.16.1269

**Last Working Jackett Version**:v0.16.1269

**Are you using a proxy or VPN?** [yes/no]no

### Description

sometimes I need to stop the service and restart it to work again

### Logged Error Messages

Exception (1337x): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /spksrc/spk/mono/work-x64-6.1/mono-5.20.1.34/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request
### Screenshots

![image](https://user-images.githubusercontent.com/43011263/93933754-2ee2db00-fd33-11ea-89de-ec760ead3655.png)

**Comment by ilike2burnthing** [comment]
See if https://github.com/Jackett/Jackett/issues/2491#issuecomment-441560429 or https://github.com/Jackett/Jackett/issues/7237#issuecomment-592222874 help

**Comment by garfield69** [comment]
this is an issue with your certificate store being out of date, or with mono 5 (so old!) not being capable of handling the certificates being used by this site.
in any case, there is nothing Jackett can do about it.
