### ISSUE TITLE
"The method or operation is not implemented" in 0.16.1260.0 Mono version

### ISSUE THREAD

**Issue by Crowmeister** [Jackett/Jackett#9615]
I'm using the Jackett package on my Synology. It's the Mono version 0.16.1260.0.

Every action that requires the webclient gives this error: "**The method or operation is not implemented**". Seems like an unspecified ,NET framework error.
When testing an indexer, when calling a Jackett Indexer via Sonarr, even when checking for Jackett updates, I get this error every time.
Seems like some webclient changes were done in version 0.16.1260.0. I'm also unable to update at the moment. Any idea how to fix this?
(And yes updating to the non-Mono version is an option, but I'd like to keep that as a last resort thing)

**Comment by ilike2burnthing** [comment]
Uninstall from DSM, reinstall, and update in Jackett.

If that doesn't work - https://github.com/Jackett/Jackett/issues/9569#issuecomment-696438169
