### ISSUE TITLE
[1337x] Exception (1337x): The method or operation is not implemented.: The method or operation is not implemented. (Test)

### ISSUE THREAD

**Issue by kidconway** [Jackett/Jackett#9616]
Just starting out with using Jackett along with Sonarr.  So far things have been working great.  Pardon me for not knowing the protocol of getting a solution, but can anyone help me?  All of my indexers stopped working over the passed week all at once.  I'm not sure what the issue is.  Let me know if you need any additional information such as logs or whatevers

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
QNAP QTS 4.4.3
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
0.16.817
**Last Working Jackett Version**:
0.16.817
**Are you using a proxy or VPN?** [yes/no]
Express VPN software on an Netgear 5700
### Description
Just starting out with using Jackett along with Sonarr.  So far things have been working great.  Pardon me for not knowing the protocol of getting a solution, but can anyone help me?  All of my indexers stopped working over the passed week all at once.  I'm not sure what the issue is.  Let me know if you need any additional information such as logs or whatevers
[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/9569#issuecomment-696409682
