### ISSUE TITLE
The method or operation is not implemented.: The method or operation is not implemented.

### ISSUE THREAD

**Issue by mahjohn** [Jackett/Jackett#9621]
### Environment

**OS**: Ubuntu

**.Net Runtime**: Mono

**.Net Version**:

**Jackett Version**: 0.16.1260.0

**Last Working Jackett Version**: Prvious one

**Are you using a proxy or VPN?** [yes/no] NO

### Description
Suddenly stopped working. Error is the same as listed in the ticket below except this is in Ubuntu
https://github.com/Jackett/Jackett/issues/9569

### Screenshots
![image](https://user-images.githubusercontent.com/17912716/94079843-a0bb3300-fdcc-11ea-87fb-b0b3dcc17a8c.png)

**Comment by ilike2burnthing** [comment]
Can you update to v0.16.1327?

**Comment by garfield69** [comment]
if you are on ubuntu then ditch the mono version of jackett.
install the latest jackett by following the instructions at https://github.com/Jackett/Jackett#install-on-linux-amdx64
