### ISSUE TITLE
[REQ] music-torrent.net

### ISSUE THREAD

**Issue by jessetn** [Jackett/Jackett#9624]
Please add http://music-torrent.net/ , music-only torrent site

**Comment by garfield69** [comment]
is this a public, private or semi private (requires registration for downloads) site?
does it have a search page?

**Comment by jessetn** [comment]
Public, doesn't require login to download.  Doesn't look like there's a search page

**Comment by garfield69** [comment]
If there is no search page then this site is not suitable for use with Jackett.
Users using the Jackett dashboard search or apps like Lidarr that use Jackett for indexing will want to look up a particular album title or artist and expect results ;-(
