### ISSUE TITLE
[ncore] Error while trying to login. (Config)

### ISSUE THREAD

**Issue by zsoltsuhajda** [Jackett/Jackett#9628]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Unraid

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono 6.10

**.Net Version**:

**Jackett Version**: 0.16.1260.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
I cannot login to nCore, however my pw did not changed

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by zsoltsuhajda** [comment]
An error occurred while updating this indexer
Error while trying to login.

**Comment by garfield69** [comment]
The first think you should do is get off 0.16.1260 as this is not a good version to be on for mono users.
Upgrade your Jackett to 0.16.1340
If the auto-update is not working then manually upgrade Jacket to resolve the problem.
If on Syno see https://github.com/Jackett/Jackett/issues/9569#issuecomment-696438169
If on Qnap NAS see https://github.com/Jackett/Jackett/issues/9569#issuecomment-696409682

**Comment by ngosang** [comment]
I would like to join this tracker. If someone has an invite, please, send me. 😄

**Comment by RoloSoze** [comment]
> I would like to join this tracker. If someone has an invite, please, send me. 😄 

@ngosang I sent an email to your Hotmail on May 24th with instructions on how to get an invite :) I think it's still valid.
