### ISSUE TITLE
Add ordering and filtering for Indexers list. 

### ISSUE THREAD

**Issue by T-REX-XP** [Jackett/Jackett#963]
Add ordering and filtering for Indexers list.

**Comment by armani316** [comment]
@T-REX-XP If I understand you correctly, what you're suggesting is related to #921, #813, #661 + the sorting/ordering of indexers you're suggesting.

**Comment by T-REX-XP** [comment]
Thanks

**Comment by T-REX-XP** [comment]
I mean about main list of Indexers [https://db.tt/8wQjXazuVF](url) and table header like this [https://db.tt/qV6Lgvw0Q9](url). Link to bootstrap plugin: [https://datatables.net/examples/styling/bootstrap.html](url)

**Comment by armani316** [comment]
@T-REX-XP The 3 links you provided are dead. Can you correct that, please?

**Comment by T-REX-XP** [comment]
@armani316, please use this url: https://datatables.net/examples/styling/bootstrap.html

**Comment by kaso17** [comment]
Datatables are already used for the manual/cached search results. Shouldn't be hard to add sorting/filtering to the indexer lists.

**Comment by kaso17** [comment]
done with 5863bf18089b0f791499d4a3b56d0c6ee8ca8cf9
