### ISSUE TITLE
[torrentz2k] Exception (torrentz2k) Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s).

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#9640]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: win 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 16.1307.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

![image](https://user-images.githubusercontent.com/19517680/94231913-222ad680-ff2f-11ea-8a86-5ecb9d78b0b7.png)

**Comment by 3xploiton3** [comment]
edit

**Comment by garfield69** [comment]
The cloudflare anti-DDoS challenge is not currently solvable by Jackett.
A experimental solution is being tested with #9029 but this is a long way from getting published.
