### ISSUE TITLE
[req] alexfilm switch to Public https://alexfilm.org/

### ISSUE THREAD

**Issue by Maika73** [Jackett/Jackett#9647]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
when I try to access https://alexfilm.org/ with a browser I get 
```html
This page isn’t working
alexfilm.org is currently unable to handle this request.
HTTP ERROR 500
```
Does this happen to you?

**Comment by ilike2burnthing** [comment]
Looks like it needs a bit of a rewrite, and I think it's public now.

**Comment by garfield69** [comment]
@ilike2burnthing  I still get this darn http 500 error so I cannot check for myself or test anything.
IF you have access then it is straight forward enough to drop the login and relevant settings, and switch the type to public.
But only if the search page shows up and the download link works  without having a registered account.

**Comment by ilike2burnthing** [comment]
Yea, I have access. I stripped those out earlier, and changed the search path from `tracker.php` to `release.php` (one of the many changes to the site), but was still having issues.

Though I've just realised that it returns multiple torrents per title.
![alexfilm](https://user-images.githubusercontent.com/59480337/94350646-23035b80-0048-11eb-851c-ab720efd0800.png)

**Comment by garfield69** [comment]
yes, please drop the yml since its not working anyway.

**Comment by ilike2burnthing** [comment]
#9664

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
