### ISSUE TITLE
[Bug] Elite-Tracker requires frequent reconfiguration

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#966]
I've had this problem before with the likes of PreToMe, House-of-Torrents & AlphaReign. It might need to be configured to re-login when required?

**Comment by kaso17** [comment]
fixed with cc4337b5888b1e315a43d4e7c75e5db055fd23b4

**Comment by armani316** [comment]
@kaso17 myAmity also has the same issue!

**Comment by kaso17** [comment]
fixed with 732878a64f526ea58c5e36103f6e3ab32c5dc3a9
