### ISSUE TITLE
[req] AsylumShare Private Brazilian https://asylumshare.net/

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#9667]
Asylum Share is a BRAZILIAN Private Torrent Tracker for MOVIES / TV / GENERAL
MinimumRatio 1.0

server not particularly reliable, 
https://asylumshare.net/ returning Error 504 Gateway time-out
or 
DATABASE: mysql_connect: User asylum_linux already has more than 'max_user_connections' active connections
quite frequently.

probably due to their current open registration soliciting more active users than they are capable of handling

**Comment by garfield69** [comment]
Jackett 0.16.1412

**Comment by ilike2burnthing** [comment]
https://asylumshare.net/ - Error 522 - Connection timed out

**Comment by garfield69** [comment]
official facebook page has a post on 8th July
```
redacted-user to Asylum Share - Seeding Friendships: What happened to Asylum? I can't access the site anymore
Asylum Share - Sowing Friendships: Closed friend no more high expenses to fund alone
```

**Comment by garfield69** [comment]
v0.18.463
