### ISSUE TITLE
[Bug] RockHard Lossless & The Horror Charnel - Configuration failed: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#967]
This is the error I get when trying to add both RockHard Lossless & The Horror Charnel: 
Configuration failed: Object reference not set to an instance of an object.

They both used to work fine. Enhanced log for both is attached.
[log.txt](https://github.com/Jackett/Jackett/files/718580/log.txt)

**Comment by kaso17** [comment]
I broke form login in the latest stable version, fixed with f96a493c0808bf67a948ea0d31cc96596a0646bf
Please try the latest pre release

**Comment by armani316** [comment]
Both seem to work fine with v0.7.899. Thanks, @kaso17!
