### ISSUE TITLE
morethantv: replace c# with yaml modelled on a luminance engine indexer (empornium)

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9670]
~~https://www.morethan.tv/~~
~~Error 525~~
https://www.morethantv.me/

**Comment by ilike2burnthing** [comment]
```
A higher-up staff member has mentioned that the new site will likely launch in the next 1-3 weeks. They're doubtful
we'll be waiting more than a month.
Old site going down was expected but timing was unplanned so there was no way to inform of this ahead of time
but it doesn't change anything in the way things go from here.
```
https://torrentinvites.org/f31/morethan-tv-mtv-news-580287/

**Comment by RoloSoze** [comment]
When they come back, they may do so under a different URL/domain name. Please update us here if that's the case.

**Comment by Ayfteyd7Od** [comment]
https://www.morethantv.me/

**Comment by RoloSoze** [comment]
> 
> 
> https://www.morethantv.me/

@Ayfteyd7Od Thank you!

@garfield69 Now that the website is back, I just sent an invite to your Gmail. They may have restructured the whole thing, and I was told months ago that it was going to use Luminance. I believe that's your lane.

**Comment by ilike2burnthing** [comment]
Site has, "...transition[ed] from Gazelle to Luminance..." - https://torrentinvites.org/f31/morethan-tv-mtv-news-580715/
2FA has also been added.

Also, users should note that your password needs to be reset in site and then in Jackett.

**Comment by garfield69** [comment]
@RoloSoze  Registration and logon to MTtv successful.

**Comment by RoloSoze** [comment]
> @RoloSoze Registration and logon to MTtv successful.

@garfield69 Great! I asked my staff contact over at MTV to let me know when it’s a good time to start updating the indexer since the website is still a WIP. Waiting to hear back.

Prior to this transition, the only remaining issue that Jackett had with MTV was the inability to return the proper release name, appending “-MTV” at the end of season packs instead of the group name as detailed in #6783

**Comment by RoloSoze** [comment]
> 
> 
> @RoloSoze Registration and logon to MTtv successful.

Just download a small file to generate some activity, please. A one-off thing.

**Comment by antigravity83** [comment]
Should the new MTV site work with Jackett now? Or is more work required?

**Comment by garfield69** [comment]
>Just download a small file to generate some activity, please. A one-off thing.

I'm not seeing a torrent browser option yet on the luminance site, and from what I can tell its not due till end of month.
Is this correct?

**Comment by garfield69** [comment]
>Should the new MTV site work with Jackett now? Or is more work required?

I'm working on the luminance engine indexer for MTV, but since the new luminance site does not yet have a torrent search page I cannot proceed. I thing it's due at end of this month after which I can proceed with coding.

When the indexer is ready I will post a notice here. Until then assume it is not available.
The current Jackett MTV indexer is the old gazelle one pointing to the old site which is no longer working.
I don't want to delete it because I want to preserve the config for use with the new indexer when I make it available.

**Comment by RoloSoze** [comment]
> 
> 
> > Just download a small file to generate some activity, please. A one-off thing.
> 
> I'm not seeing a torrent browser option yet on the luminance site, and from what I can tell it's not due till end of month.
> Is this correct?

Yeah I should have probably clarified - Download a small file when torrents are loaded onto the new website as there are none now.

**Comment by garfield69** [comment]
for those with access, https://www.morethantv.me/forum/thread/2581 details Site's progress and plans going forward.
As far as this indexer is concerned, on hold until that torrent search page shows up and stays unchanged log enough to be worth while coding yaml.

**Comment by whodean** [comment]
FYI-MTV has completed the move to new engine

https://www.morethantv.me/forum/thread/2593

**Comment by garfield69** [comment]
@whodean  I'm keeping an eye on this, thanks.
HoBut until the site makes the torrent search page available there is nothing for us to do but wait.

**Comment by rottdog** [comment]
I see this was blocked? What does that mean? Will i not be able to add this to jackett any more?

**Comment by ilike2burnthing** [comment]
Progress is blocked (temporarily hopefully) due to something out of our control (in this case, https://github.com/Jackett/Jackett/issues/9670#issuecomment-735446617). The indexer is still available.

**Comment by garfield69** [comment]
the site's new torrent search page appears to have rows for a season title that contain multiple download links.
This means that this ticket (replace c# with yaml modelled on a luminance engine indexer (e.g. empornium)) cannot be done, as yaml only supports 1-title-1-download rows.

The existing c# indexer will need to be rewritten for the new site's engine by a volunteer. see #6783 
This concludes my involvement with this site.

**Comment by garfield69** [comment]
https://www.morethantv.me/ returning This site can’t be reached

**Comment by ilike2burnthing** [comment]
back up
