### ISSUE TITLE
[Bug] Norbits - Configuration failed: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by M0kkisjeva** [Jackett/Jackett#968]
As title says, when I try to add Norbits I get this error =(

**Comment by kaso17** [comment]
Do you have an invite available?
Otherwise we've to wait for @DiseaseNO to have a look at it.

**Comment by DiseaseNO** [comment]
I will update and test to re-add mine when I come home to see if I get the same message.

**Comment by M0kkisjeva** [comment]
Jackett Version 0.7.893.0

I've only filled in the required fields. I've tried adding in the rest to see if it solved any problems but didn't.
Already using jacket for Torrentbytes and Torrentshack, works flawlessly.

**Comment by armani316** [comment]
@M0kkisjeva @DiseaseNO Is this still an issue?

**Comment by M0kkisjeva** [comment]
@armani316 
Just tried, and yes. For me this is still an issue.

**Comment by kaso17** [comment]
@M0kkisjeva please post a log with enhanced logging enabled.

**Comment by armani316** [comment]
@M0kkisjeva It would be great if you could post an enhanced log showing this issue. @kaso17 now has access to NorBits and should be able to fix it if you could provide a log.

**Comment by RoloSoze** [comment]
@M0kkisjeva Are you able to provide an enhanced log showing the error you're describing here?

**Comment by kaso17** [comment]
closing this due to no response

**Comment by WildCard1** [comment]
Hi. I still have this problem. Did anyone find a solution for this? Here is the relevant part from the enhanced log file (some of it are translated from norwegian to english as best as I could). Thanks!

```
2017-04-11 23:29:01.5449 Error Exception in Configure System.NullReferenceException: Object reference not set to an instance of an object
   at Jackett.Indexers.Norbits.<DoLogin>d__26.MoveNext() i C:\projects\jackett\src\Jackett\Indexers\Norbits.cs:line179
--- End of the stack from the previous location where exception happened   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Indexers.Norbits.<ApplyConfiguration>d__25.MoveNext() i C:\projects\jackett\src\Jackett\Indexers\Norbits.cs:line115
--- End of the stack from the previous location where exception happened   
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Configure>d__16.MoveNext() i C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:linje 188
```

**Comment by kaso17** [comment]
please post more of the log and enable enhanced logger (-t)

**Comment by WildCard1** [comment]
I managed to circumvent this problem by adding the indexer for Norbits on a Ubuntu VM (where this bug didnt happen), and copying the contents of the file, norbits.json, to the windows intallation (editing the http headers afterwards). 

Tomorrow or Saturday I will try to force this bug to happen again, so I can show you the enhanced log file.

**Comment by WildCard1** [comment]
Today I was successful in adding Norbits as an indexer. Maybe this problem has been fixed in one of the recent patches? I also noticed that Norbits authentication system has the user name as case sensitive, and when I used the wrong name, i got the same error message (" Configuration failed: Object reference not set to an instance of an object"). Maybe that was the reason.

**Comment by kaso17** [comment]
Yes, the "Object reference not set to an instance of an object" error most likely is caused by incorrect credentials. a9c5477003ca499b0dee7fbc485ea5fbb93ee3f0 should slightly improve the problem.

**Comment by enwyn** [comment]
This is still an issue, i will atempt Wildcard1 workaround.

**Comment by enwyn** [comment]
> Jackett.Common.IndexerException: Exception (norbits): Object reference not set to an instance of an object ---> System.Exception: Parse error ---> System.NullReferenceException: Object reference not set to an instance of an object   at Jackett.Common.Indexers.Norbits.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x0040c] in <a72f10b9deaa459e9dc18b71fbc14a32>:0     --- End of inner exception stack trace ---   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError (System.String results, System.Exception ex) [0x00064] in <a72f10b9deaa459e9dc18b71fbc14a32>:0    at Jackett.Common.Indexers.Norbits.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x009ed] in <a72f10b9deaa459e9dc18b71fbc14a32>:0    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x00091] in <a72f10b9deaa459e9dc18b71fbc14a32>:0     --- End of inner exception stack trace ---   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x000ee] in <a72f10b9deaa459e9dc18b71fbc14a32>:0    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x0006b] in <a72f10b9deaa459e9dc18b71fbc14a32>:0    at Jackett.Common.Services.IndexerManagerService.TestIndexer (System.String name) [0x000a3] in <a72f10b9deaa459e9dc18b71fbc14a32>:0    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig (Jackett.Common.Models.DTO.ConfigItem[] config) [0x0012d] in <824d5f7b3a1542e1a29bda8231b9cb80>:0    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <f5622e7f79be469e83d9e2bde9addd07>:0    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00115] in <560d56f8376d4258a59ad5478913c777>:0    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <824d5f7b3a1542e1a29bda8231b9cb80>:0

> Error on 20181223003133 for Norbits.txtSystem.NullReferenceException: Object reference not set to an instance of an object   at Jackett.Common.Indexers.Norbits.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x0040c] in <a72f10b9deaa459e9dc18b71fbc14a32>:0      Error, unable to parse result    at Jackett.Common.Indexers.Norbits.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x0040c] in <a72f10b9deaa459e9dc18b71fbc14a32>:0

**Comment by enwyn** [comment]
Tested on a freshly installed and fully updated ubuntu 18.10 VM. The restult is exacly the same.
Jackett version: v0.10.533

**Comment by enwyn** [comment]
I found the solution: The indexer for Norbits is theme and/or icon pack sensitive.
workaround: change theme to CurrentWhite (Default) and icon type A6.

https://postimg.cc/67VR79kn

Conclusion: The indexer does not support some themes.
