### ISSUE TITLE
[spacetorrent] Clearance failed after 10 attempt(s). (Config)

### ISSUE THREAD

**Issue by jns-fr** [Jackett/Jackett#9681]
### Environment

**OS**: Ubuntu (docker)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.1389.0 

**Last Working Jackett Version**: 0.16.1389.0

**Are you using a proxy or VPN?** [yes/no] No

### Description

I try to add SpaceTorrent indexer but when i fill up username et password (i don't change anything) and I submit (Okay) i have the following error.

### Logged Error Messages

An error occurred while updating this indexer
Clearance failed after 10 attempt(s).
Click here to open an issue on GitHub for this indexer.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/TroubleShooting#clearance-failed-after-10-attempts
