### ISSUE TITLE
alpharatio gazelletracker setting minimumratio and minimumseedtime

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#9689]
@ngosang 

AlphaRatio uses the GazelleTracker abstract

is it possible to set an AlphaRatio override in its C# indexer to set  release.MinimumRatio = 1 and release.MinimumSeedTime = 259200 ?

How would one go about this?

**Comment by seeyabye** [comment]
@garfield69 it's not too difficult to be added if the values are fixed. I've submitted a PR. You can test it.

**Comment by garfield69** [comment]
Ah, that's terrific. Thanks.
In my head I always assumed an override would actually replace the same named routine in the abstract rather than supplement it like it obviously does. Cool.
