### ISSUE TITLE
Can't connect to trackers using HTTP-proxy

### ISSUE THREAD

**Issue by helperman** [Jackett/Jackett#9696]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Window 8

**.Net Runtime**: .Net-Framework

**.Net Version**: 

**Jackett Version**:  v0.16.1431 

**Last Working Jackett Version**: all versions have this issue

**Are you using a proxy or VPN?** yes

### Description

1. Use proxy URL: https://antizapret.prostovpn.org/proxy.pac
2. Press "Test" button to test connection to https://1337x.to

An error occurs as well as for many other trackers.
This site https://1337x.to works in my browser with the "proxy.pac" setting but doesn't work in Jackett.

### Logged Error Messages
[log.txt](https://github.com/Jackett/Jackett/files/5301986/log.txt)

### Screenshots

Here is my options.
I chose only HTTP-proxy and set its url: https://antizapret.prostovpn.org/proxy.pac
![00000572](https://user-images.githubusercontent.com/8351863/94619242-35360180-02b5-11eb-8192-b0998eb48e19.png)

Test button with error:
![00000571](https://user-images.githubusercontent.com/8351863/94617470-48939d80-02b2-11eb-8eec-6fe79c40f286.png)

**Comment by garfield69** [comment]
your error message (once translated by google) reads `Remote host forcibly terminated existing connection`
this implies that you are being blocked from accessing 1337x.to.

Your log shows that in response to Jackett trying `https://1337x.to/cat/Movies/time/desc/1/` the 1337x server is returning 
```html
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html> 
```

something about the proxy you are using is not compatible with 1337x web site.
@ngosang  @ilike2burnthing  have you anything to add regarding this user's issue?

**Comment by ilike2burnthing** [comment]
Jackett can't process the script (to my knowledge it has no way of doing so). You would have to use the actual proxy URL, however:
```
    // WARNING! WARNING! WARNING!
    // You should NOT use these proxy servers outside of PAC file!
    // DO NOT enter it manually in any program!
    // By doing this, you harm the service!
    return "HTTPS proxy-ssl.antizapret.prostovpn.org:3143; PROXY proxy-nossl.antizapret.prostovpn.org:29976; DIRECT";
```
What you do with that warning is up to you.
