### ISSUE TITLE
[ebookparadijs] Login failed: Selector "a[href="logout.php"]" didn't match

### ISSUE THREAD

**Issue by mtae** [Jackett/Jackett#9697]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**Are you using a proxy or VPN?**  no

### Description
On trying to login the error message is shown

### Logged Error Messages
Selector "a[href="logout.php"]" didn't match

**Comment by garfield69** [comment]
looks like the site has activate a custom anti-DDoS protection that appears before the login panel
I shall see if switching to the cookie method allows access.

**Comment by garfield69** [comment]
Jackett 0.16.1451
