### ISSUE TITLE
No results from Speed.cd

### ISSUE THREAD

**Issue by OriginalFool** [Jackett/Jackett#97]
When searching speed.cd about once a week I have had to re-enter my password in Jackett. However as of recently I am both unable to get results or re-enter my password. I have tried deleting and adding it again but Jackett reports "configuration failed". 

[log.txt](https://github.com/Jackett/Jackett/files/43099/log.txt)

**Comment by OriginalFool** [comment]
Here's an updated log, enhanced logging is on. This is an attempt to add speed.cd as a tracker.
[log.txt](https://github.com/Jackett/Jackett/files/46489/log.txt)

**Comment by polyneux** [comment]
Attempting to add Speed.cd uname and pw returns:  Configuration failed:

UnixLibCurlWebClient:GetString(Url:http://speed.cd/take_login.php) also shows

**Comment by Sytanek** [comment]
Looks like the url changed slightly...take.login.php

**Comment by sethwarsh** [comment]
I can provide an invite please provide me with the developers details.

S

**Comment by flightlevel** [comment]
I've tried changing the login url in the new release. https://github.com/Jackett/Jackett/releases/latest
If that doesn't fix it, invite to jackettapp at gmail

**Comment by sethwarsh** [comment]
Ok will be home in 30 minutes, will try and if it doesn't solve the problem send the invite straight away.

Thanks

**Comment by sethwarsh** [comment]
Will this release come on auto update ?

**Comment by flightlevel** [comment]
Yep, just click the orange check for update button

**Comment by sethwarsh** [comment]
No luck, I'll send the invite momentarily.  You're not ready for an invite for M-Team yet are you? :)

**Comment by BramRoets** [comment]
I'm having the same problem over here. If a dev need's an invite, please let me know.

**Comment by sethwarsh** [comment]
Please confirm you received the invite

Thanks
S

**Comment by BramRoets** [comment]
I fixed it myself, it's working now. I did a pull request.

**Comment by sethwarsh** [comment]
Can you please share how you fixed it so the rest of us can get it working as well?

Thanks
Seth

**Comment by sethwarsh** [comment]
@ Bram on mobile so I can't edit post can you please share how you fixed the problem?

**Comment by BramRoets** [comment]
Nothing special, I just changed the url (which was outdated) : https://github.com/Jackett/Jackett/pull/112/files

**Comment by flightlevel** [comment]
Thanks @BramRoets 
This change is in the latest release https://github.com/Jackett/Jackett/releases/latest
Can others let us know if this fixes your issue.

**Comment by sethwarsh** [comment]
Fixed Thanks!
