### ISSUE TITLE
[LeagueHD] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#9702]
### Environment

**OS**: Windows 10 Pro 64-Bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.16.1451 [Latest]

**Last Working Jackett Version**: Not sure

**Are you using a proxy or VPN?** No

### Description

I am able to configure LeagueHD but testing/searching the indexer returns nothing

### Logged Error Messages

`An error occurred while testing this indexer`
`Found no results while trying to browse this tracker`

### Screenshots

Note needed

@garfield69 I don't believe any developer is a member? If you're not, I can invite you. I won't include a log since this seems like it's affecting everyone. LHD recently changed their website design.

**Comment by garfield69** [comment]
@RoloSoze  I had an account but it was disabled, so I do not think you can re-invite me using garfieldsixtynine@gmail.com.

Start by providing a full **enhanced** log and we can take a look to see if its something simple
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by RoloSoze** [comment]
@garfield69 Will post it once I’m sitting at my PC. If the issue requires you to access LHD, I can always invite you through your Outlook. Most Chinese trackers completely delete accounts that have been disabled due to inactivity, so there shouldn’t be an issue even if I send the invite to your Gmail.

**Comment by garfield69** [comment]
seems you are correct.
a logon attempt just now with my old credentials returned
```
Error : The username or password is incorrect! Or you have not passed the verification and
forgot your password? Retrieve your password?
```
and a password reset request using that email returned
```
The email address was not found in the database.
```

**Comment by RoloSoze** [comment]
@garfield69 Alright let's try this - Enhanced log below:

[log.txt](https://github.com/Jackett/Jackett/files/5310943/log.txt)

**Comment by garfield69** [comment]
looks like leaguehd have changed their download link on their torrent search page results. 
Should be straight forward enough to change the indexer selector to match the new link template.

**Comment by RoloSoze** [comment]
Solved the issue. Thank you!
