### ISSUE TITLE
[broadcasthenet] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by wastingaeons** [Jackett/Jackett#9710]
### Environment

**OS**: Unraid 

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: Unsure? Whatever comes in the amd64 linux binary package Linuxserver.io uses

**Jackett Version**: 0.16.1472

**Last Working Jackett Version**: 0.16.1451

**Are you using a proxy or VPN?** no

### Description

Looks like pull request #9680 may have broken BTN on 0.16.1472 using latest linuxserver's docker image. Reverting back to 0.16.1451 works normally

### Logged Error Messages
[btnError.txt](https://github.com/Jackett/Jackett/files/5314627/btnError.txt)

**Comment by garfield69** [comment]
@seeyabye as the author of the last set of changes, please investigate.
I presume you tested your changes after completing the review recommendations from #9680 ? ;-b

**Comment by garfield69** [comment]
Jackett 0.16.1523
