### ISSUE TITLE
Season Pack for Sonarr doesn't work

### ISSUE THREAD

**Issue by LoicAuge** [Jackett/Jackett#9712]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**Jackett Version**: Version 0.16.1472.0

**Are you using a proxy or VPN?** no

### Description

With Sonarr, when i start a search for a whole season, it launch a search with an URL like :

http://host:9117/api/v2.0/indexers/gktorrent/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Esta%20mierda%20me%20supera&season=1
http://host:9117/api/v2.0/indexers/oxtorrent/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Esta%20mierda%20me%20supera&season=1
http://host:9117/api/v2.0/indexers/gktorrent/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=I%20Am%20Not%20Okay%20With%20This&season=1
http://host:9117/api/v2.0/indexers/oxtorrent/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=I%20Am%20Not%20Okay%20With%20This&season=1

The mention "season=1" seems to not be implemented. When I search without this mention, i have good returns but with this mention, i don't have any return, but I should have the results for the season 1 and only season 1.

Thank you, do not hesitate if you need more information.

**Comment by LoicAuge** [comment]
Any update ?

**Comment by garfield69** [comment]
There are no results at the gktorrent web site for `Esta mierda me supera`
![image](https://user-images.githubusercontent.com/6933240/96648880-8f922180-138c-11eb-9c93-501d8988c75b.png)
so you cannot expect Jackett to return results for this.

there are results for `I Am Not Okay With This`
![image](https://user-images.githubusercontent.com/6933240/96649130-07604c00-138d-11eb-93c6-a4914c10938a.png)

when Sonarr sends `http://localhost:9117/api/v2.0/indexers/gktorrent/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=I%20Am%20Not%20Okay%20With%20This&season=1` to Jackett,
Jackett generates the following query to the gktorrent website
https://wvw.gktorrent.pw/recherche/I%20Am%20Not%20Okay%20With%20This%20S01 

But as you can see from the prior image ,the web site uses saison 1 in its titles not S01 
so for the indexer to work it will need to generate 
https://wvw.gktorrent.pw/recherche/I%20Am%20Not%20Okay%20With%20This%20saison%201

I can implement this, but not right now, I've other work ahead of yours that needs completing first.
I will post here when the update is available and released.

**Comment by garfield69** [comment]
Jackett 0.16.1844
