### ISSUE TITLE
[iptorrents] Your cookie did not work: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings. (Config)

### ISSUE THREAD

**Issue by arbourp** [Jackett/Jackett#9713]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux

**.Net Runtime**: Mono
**.Net Version**:6.8.0.105

**Jackett Version**:

**Last Working Jackett Version**: v0.16.1472.0

**Are you using a proxy or VPN?** [yes/no] No

### Description

Attempting to add iptorrents.com as a tracker.
Get the input window for the iptorrents details, and insert the cookie information as best I can determine but it fails.

Noting that the cookie output in Chrome and Firefox versions today do not look like what is listed in the wiki.
I copied out each of the fields manually and put them together with ; to see if that would work but nothing doing.

### Logged Error Messages

 10-02 01:12:08 Error System.Exception: Your cookie did not work: The user is not logged in. It is possible that the cookie has expired or you made a mistake w>
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Jackett.Common.Indexers.IPTorrents.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 164
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiContro>
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor ex>
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 ac>
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastT>
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, >
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, S>
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHan>
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Jackett.Common.Indexers.IPTorrents.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 164
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiContro>
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor ex>
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 ac>
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastT>
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, >
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, S>
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Oct 02 01:12:08 omegasupreme jackett[68745]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHan>

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![image](https://user-images.githubusercontent.com/4433169/94878391-312bf000-042b-11eb-8d09-17610b5518a9.png)

**Comment by garfield69** [comment]
see https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work
select and copy the whole cookie string (everything after the `cookie: ` and paste it onto the cookie box of the config.
do not edit the cookie string.

**Comment by arbourp** [comment]
This is what I get when I try to see the cookie. 
![image](https://user-images.githubusercontent.com/4433169/94927824-cca37c00-0490-11eb-832e-870472d4c0b5.png)

**Comment by arbourp** [comment]
Okay, somehow the manual copy and pasting didn't work.

What I did to find the cookie properly was to do this:
![image](https://user-images.githubusercontent.com/4433169/94929301-e6de5980-0492-11eb-8509-802843cb30ef.png)

THen the HAR gives you a json file, you can find the cookie from there and it works.

**Comment by garfield69** [comment]
you were looking at the incorrect tab ;-)
you were using the **cookies** tab, but the instructions were to use the **Headers** tab and to scroll down to the cookie.
I've highlighted the **Headers** tab for you here
![image](https://user-images.githubusercontent.com/6933240/94958284-c1f9ed00-054b-11eb-92f4-7c61116cbbd8.png)
no matter. you got the job dome using your alternate method.

**Comment by pfSecure** [comment]
Still doesn't work, IPTorrent have changed the homepage today

**Comment by garfield69** [comment]
@pfSecure  update your Jackett to 0.16.1999
