### ISSUE TITLE
[crazyspirits] Login failed: Selector

### ISSUE THREAD

**Issue by neo62248** [Jackett/Jackett#9721]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Synology

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: last stable

**Last Working Jackett Version**: last stable

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
I try to add indexer CrazySpirits to my Jackett dashboard. The config asks me a cookie that i recover from being connected to the site. 
When I enter my config, an error message comes : "Login failed: Selector "a[href="account-logout.php"]" didn't match". 

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]
![001](https://user-images.githubusercontent.com/5675981/94924513-eeffbe80-04bd-11eb-9f29-e98d46b18ba9.png)

**Comment by garfield69** [comment]
The indexer works for me which suggests the problem is at your end.
see https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work for typical issues with cookie use.

**Comment by neo62248** [comment]
It was a cookie misconfiguration on my Jackett. Thanks

**Comment by skuizy** [comment]
@neo62248 : How did you set it up ? I'm having the same problem as you despite grabbing the cookie from my browser.

**Comment by neo62248** [comment]
Hello, 

cookie must be like this : pass=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; uid=yyyy

**Comment by skuizy** [comment]
Thanks for the follow up ! 

Looks like this isn't the source then, mine is `PHPSESSID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; pass=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy; uid=zzz`

**Comment by BK-STAR77** [comment]
Hello people,

I have this issue too. My cookie look like this:

PHPSESSID=xxxxxxxxxxxxxxxxx; pass=xxxxxxxxxxxxxxxxxxxx; uid=xxxx

but still don't work

thank you for your help

**Comment by garfield69** [comment]
Please read the wiki https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work carefully and especially the notes section.
Basically, if you are using Docker, or a headless server where you cannot run a browser in the same image that is running Jackett, then you are going to have problems.
Also some VPN/proxies can cause issues.
And there is nothing we can do to help you with that.

**Comment by BK-STAR77** [comment]
> Please read the wiki https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work carefully and especially the notes section.
> Basically, if you are using Docker, or a headless server where you cannot run a browser in the same image that is running Jackett, then you are going to have problems.
> Also some VPN/proxies can cause issues.
> And there is nothing we can do to help you with that.

Thank you effectively I'm using a seedbox. I will try the ssh trick maybe it will work
