### ISSUE TITLE
[film-paleis] Login failed: Selector "a[href="logout.php"]" didn't match

### ISSUE THREAD

**Issue by guuskeDL** [Jackett/Jackett#9722]
**Jackett Version**: 0.16.1523.0

**Are you using a proxy or VPN?** No

### Description

On trying to login the error message is shown
Same issue as https://github.com/Jackett/Jackett/issues/9697 but for film-paleis.me

### Logged Error Messages

Selector "a[href="logout.php"]" didn't match

**Comment by garfield69** [comment]
confirmed. I'll switch the indexer to using the cookie method

**Comment by garfield69** [comment]
Jackett 0.16.1549
