### ISSUE TITLE
core: improve torznab search support

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9723]
This should be an internal discussion but since there is no c# team, here will be. :smile: 

Lately there have been many changes to improve the support for torznab searches:
* Book search #9306 
* TVDbId, TMDbId queries #9102 
* Raw search #9719

The current support for torznab is good but the code is getting very hard to maintain:
1. Jackett UI doesn't show the torznab caps for each indexer and it doesn't allow to make torznab queries with specific parameters (only IMDB is supported). Sonarr and related apps uses Torznab and some users find that the results in Jackett UI/Sonarr are different.
2. Related to 1) we don't have a reference index/doc to see the supported caps for each tracker. At this moment we have 500 trackers and it's almost impossible to keep them updated with all torznab caps. This is not because the lack of time, but because the users don't report the issues or changes related to torznab. Jackett is a blackbox foir them and they only complain if Sonarr stops working.
3. Jackett code related to torznab is in bad shape, it needs a good refactor, but most important is the lack of unit/integration tests. After the changes in the previous PRs we can't be sure we are not breaking something (see additional note #9719 )
4. I think the documentation for developers is not good enough. For Cardigann indexers is ok but there are some parts outdated (or example caps / modes) => https://github.com/Jackett/Jackett/wiki/Definition-format#caps We have to write similar documentation for C# indexers.

I think that improving test support will be a good start because it's easier than touching the UI. We have already some unit/integration tests working in the CI/CD pipeline, but the code coverage is really low. I'm thinking in adding a dummy/test indexer with all features (mock requests) and several use cases of torznab searches.

Do you have more ideas to improve torznab support? How are other projects handling this? Could you help with some code?
@Taloth @seeyabye @ta264 @Qstick @cadatoiva @garfield69 @ilike2burnthing @RoloSoze 

This is a technical discussion, please don't talk about concrete trackers/implementations to not lose the focus.

**Comment by seeyabye** [comment]
I totally agree that having unit testing is very important and you're absolutely right about getting the torznab protocol nailed correctly. 

I'm basing the protocol on links shared by @Taloth which pretty much links back to the specifications on newsznab.

I had a look at Sonarr's unit testing for trackers, and noticed that there's a couple of mockings. Perhaps we could do the same, like how you suggested. 

I don't have much to add at this point, but I could help as much as I can with the unit test coverage.

**Comment by ngosang** [comment]
> I don't have much to add at this point, but I could help as much as I can with the unit test coverage.

I tried to test `ResultsController.Torznab` to see the caps of one indexer but we have to mock a lot of things before.. Maybe it's a good idea to start testing the classes `TorznabCapabilities` and `BaseIndexer`, then move to more complicated things. I'm not a C# coder so I will appreciate some PRs from you. When we have a solid foundation to work on, I will be more helpful.

**Comment by ilike2burnthing** [comment]
Happy to help however I can, but I'd imagine that might come later. I have an idea or two on the UI side of things for 1), but I'm assuming that's a long way off.

**Comment by ngosang** [comment]
Some unit tests => #9821
The code is really ugly but this is the first step for refactor the code.

**Comment by ngosang** [comment]
I did most of the work in the following PRs: #9831 #9862 #9893 #9895 #9897 #10031

These are the issues for remaining tasks: #10051 #10048
