### ISSUE TITLE
Lostfilm indexer issue - can't find tv show

### ISSUE THREAD

**Issue by SuberSeb** [Jackett/Jackett#9725]
For some reason indexer Lostfilm.tv can't find series Fargo. Site search works well.

**Comment by garfield69** [comment]
really?
![image](https://user-images.githubusercontent.com/6933240/94986899-f1960d00-05be-11eb-82bf-d11534822bf4.png)

what was your search string?
what version of Jackett are you on?

**Comment by SuberSeb** [comment]
![image](https://user-images.githubusercontent.com/49331864/94986951-8f5fec80-056b-11eb-80a0-0dffea3954be.png)
Just 'Fargo'
Docker with development branch

**Comment by garfield69** [comment]
access your jackett dashboard and report the version at the bottom.

**Comment by SuberSeb** [comment]
Jackett Version 0.16.1549.0

**Comment by garfield69** [comment]
access your Jackett dashboard and Edit your lostfilm config and check that the sitelink is set to `https://www.lostfilm.run/`
and don't forget to enter the Captcha image text before clicking OKAY.

**Comment by SuberSeb** [comment]
> access your Jackett dashboard and Edit your lostfilm config and check that the sitelink is set to `https://www.lostfilm.run/`
> and don't forget to enter the Captcha image text before clicking OKAY.

It's already `https://www.lostfilm.run/`

**Comment by garfield69** [comment]
Hmm.
So lets have a look at your **full enhanced** log and maybe something will indicate what is going on with a bit of luck.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
Thanks.

**Comment by SuberSeb** [comment]
Got this error while searching Fargo: `

lostfilm: Error while parsing row '<tr> 					<td class="placeholder"></td> 					<td class="alpha"> 						<div class="haveseen-btn" title="Пометить серию как просмотренную" onclick="markEpisodeAsWatched(this);" data-episode="208001001" data-season="208001999" data-code="208-1-1"></div> 					</td> 					<td class="beta" onclick="goTo('/series/Fargo/season_1/episode_1/',false)" title="Перейти к серии">1 сезон 1 серия</td> 					<td class="gamma" onclick="goTo('/series/Fargo/season_1/episode_1/',false)" title="Перейти к серии"> 						 						<div> 						Дилемма крокодила<br> 						<span class="gray-color2 small-text">The Crocodile's Dilemma</span> 						</div> 					</td> 					<td class="delta" onclick="goTo('/series/Fargo/season_1/episode_1/',false)" title="Перейти к серии">Ru: 13.05.2014<br><span class="gray-color2 small-text">Eng: 15.04.2014</span></td> 					<td class="epsilon" onclick="goTo('/series/Fargo/season_1/episode_1/comments/',false)" title="Перейти к обсуждению серии"> 						<div class="comment-blue-box"> 							<div class="tail"></div> 							636 						</div> 					</td> 					<td class="epsilon" onclick="goTo('/series/Fargo/season_1/episode_1/',false)" title="Оценка серии пользователями Lostfilm.TV"> 						<div class="mark-green-box">9.5</div> 					</td> 					<td class="zeta"> 						<div class="external-btn2" title="" onclick="copyrightedEpisode()"></div> 					</td> 					<td class="placeholder"></td> 				</tr>':  System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Indexers.LostFilm.TrackerUrlDetails..ctor(IElement button) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 63    at Jackett.Common.Indexers.LostFilm.FetchSeriesReleases(String url, TorznabQuery query, String filter) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 583
--


`

**Comment by garfield69** [comment]
@ngosang  can you take a look at the lostfilm indexer and see if you can adjust it to cope with the row parse error reported. Thanks.

**Comment by ngosang** [comment]
@garfield69 the issue is in this line:
`var playButton = row.QuerySelector("td.zeta > div.external-btn");`
This row has a different button:
`<td class="zeta"><div class="external-btn2" title="" onclick="copyrightedEpisode()"></d</td>`
What I should do in this case? Skip the row? I don't have account.

**Comment by garfield69** [comment]
lostfilm is a semi private site with open registration.

**Comment by SuberSeb** [comment]
I found the issue. This particular series is not available in Russia but available in the US and Europe.

**Comment by garfield69** [comment]
I would skip the row.

**Comment by garfield69** [comment]
re-opened because we want to prevent the error by not including these results in searches.

**Comment by garfield69** [comment]
Jackett 0.16.1583
