### ISSUE TITLE
TorrentHeaven broken

### ISSUE THREAD

**Issue by Mitnick84** [Jackett/Jackett#9726]
**Jackett Version**:
0.16.1523.0

Cant add Torrent Heaven as indexer.

See enhanced logfile please.

[log.txt](https://github.com/Jackett/Jackett/files/5321290/log.txt)

**Comment by garfield69** [comment]
unfortunately no one on the team appears to have an account on this site.
let us know if you have an invite available.

a quick look at the log shows what appears to now be a mismatch in selectors for size, seeders, leechers and grabs
looks the the site has shifted their results columns.

**Comment by Mitnick84** [comment]
Hi, the invitesystem is closed since long time.

**Comment by garfield69** [comment]
Jackett 0.16.1583

**Comment by SkalCore** [comment]
https://github.com/Jackett/Jackett/pull/9740#issuecomment-720114711

**Comment by SkalCore** [comment]
linuxserver/jackett:v0.13.280-ls55 is working with Torrentheaven, so please update settimngs in actual version

**Comment by garfield69** [comment]
@SkalCore  fetch the latest Docker Jackett image (using either the **latest** tag or the **development** tag, I don't know which the linuxserver guys are using) so that you are on 0.16.1999

**Comment by Mitnick84** [comment]
I have installed the new Jackett Version 0.16.2220.0 on my ubuntu server and its also not working.
I think its a captcha Problem, its not show me the captcha. Tested with different browsers and machines.

[log.txt](https://github.com/Jackett/Jackett/files/5585811/log.txt)

**Comment by garfield69** [comment]
@Mitnick84  when I edit my torrentheaven config I see the captcha code presented 
![image](https://user-images.githubusercontent.com/6933240/100020367-978a2900-2e44-11eb-8c0e-91c836c049ae.png)
are you not seeing this?

**Comment by SkalCore** [comment]
What changes have you made to the settings in the config file?

**Comment by SkalCore** [comment]
> @Mitnick84 when I edit my torrentheaven config I see the captcha code presented
> ![image](https://user-images.githubusercontent.com/6933240/100020367-978a2900-2e44-11eb-8c0e-91c836c049ae.png)
> are you not seeing this?

What changes have you made to the settings in the config file?

**Comment by Mitnick84** [comment]
very strange i cant see the captch. 

this is the torrentheaven.json:

`
[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://newheaven.nl/"
  },
  {
    "id": "username",
    "type": "inputstring",
    "name": "Username",
    "value": "xxxxxxxxxxxxxx"
  },
  {
    "id": "password",
    "type": "inputstring",
    "name": "Password",
    "value": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  },
  {
    "id": "captchatext",
    "type": "inputstring",
    "name": "Captcha Text",
    "value": ""
  },
  {
    "id": "captchacookie",
    "type": "hiddendata",
    "name": "Captcha Cookie",
    "value": "PHPSESSID=xxxxxxxxxxxxxxxx;"
  },
  {
    "id": "",
    "type": "displayinfo",
    "name": "",
    "value": null
  },
  {
    "id": "cookieheader",
    "type": "hiddendata",
    "name": "CookieHeader",
    "value": "uid=71157; pass=xxxxxxxxxxxx"
  },
  {
    "id": "lasterror",
    "type": "hiddendata",
    "name": "LastError",
    "value": "Exception (torrentheaven): Specified argument was out of the range of valid values. (Parameter 'index'): Parse error"
  }
]

`

**Comment by garfield69** [comment]
@SkalCore  is your question directed at me?

the capcha image only appears when the login page has one. 
If it is not there when you use the dashboard to edit the config, then make sure to erase any text in the captcha text box left over from the last attempt, and click okay.

**Comment by SkalCore** [comment]
hmmmm, so i´m logged in at TH, so the cookie is set on my browser. So i must log out to get jackett to work with TH?

**Comment by Mitnick84** [comment]
> 
> 
> hmmmm, so i´m logged in at TH, so the cookie is set on my browser. So i must log out to get jackett to work with TH?

**Comment by Mitnick84** [comment]
@SkalCore 

i think not. I tested this also, but no luck. its the only tracker that make so hard problems.

**Comment by Mitnick84** [comment]
Update:

I wrote a Message to the Staff from Torrent Heaven and they say me he block active Jackett.
