### ISSUE TITLE
[Question] How to use 'Manual search' and access search result with python?

### ISSUE THREAD

**Issue by water5** [Jackett/Jackett#9741]
I want to use 'Manual search' function and access search result with python, please give some suggestion or examples, or documents .
I can't find more documents or discussion for Jackett, #Jackett channel on freenode closed, so I post this to here.

**Comment by ngosang** [comment]
Should be easy but we don't have documentation. I recommend you to use `requests` library in python.

Internal API = > http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=**redacted**&Tracker%5B%5D=1337x&Query=harry
It returns a JSON

Torznab API => 127.0.0.1:9117/api/v2.0/indexers/1337x/results/torznab/?apikey=**redacted**&q=harry
It returns a XML with the same information. This is the recommended way but parsing the XML is a bit harder than the JSON.

**Comment by water5** [comment]
Useful, thanks.
