### ISSUE TITLE
[film-paleis] Login failed: Selector

### ISSUE THREAD

**Issue by 1985kasper** [Jackett/Jackett#9745]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux (Mint)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:Version 0.16.1549.0 (docker contrainer)

**Last Working Jackett Version**: Version 0.16.1549.0

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
This used to work in the last week.

This doesn't work today anymore. 
get the cookie like it says in the instructions
try to save the tracker
Error as below:
An error occurred while updating this indexer
Login failed: Selector "a[href="logout.php"]" didn't match

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

An error occurred while updating this indexer
Login failed: Selector "a[href="logout.php"]" didn't match

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
This indexer is working for me so the issue would appear to be at your end.
have a read of https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work and in particular the notes section.
make sure you are copying the cookie from the Headers tab not the Cookie tab. see the pictures in the same link I provided.

**Comment by bruvv** [comment]
I had this issue too, followed the steps and now it is working fine. Thanks @garfield69

**Comment by 1985kasper** [comment]
Okay. I followed the notes. However it turns out the browser and the machine running jackett need to be on the same IP. 

Thing is the machine running jackett is behind a VPN and the machine i am visiting their website with is not. 
So found the issue. But maybe this can be added to the notes on adding the cookie?
