### ISSUE TITLE
[pornbay] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Deflated-Criossant** [Jackett/Jackett#9749]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10 x64 1909

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] .Net-Core

**.Net Version**: 3.1.402 x64

**Jackett Version**:  0.16.1559.0 

**Last Working Jackett Version**:  0.16.1559.0 

**Are you using a proxy or VPN?** [no] 

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

pornbay never showed results, although returns results on the site 

### Logged Error Messages

" An error occurred while testing this indexer
Found no results while trying to browse this tracker"

### Screenshots

![Screenshot_67](https://user-images.githubusercontent.com/16240121/95083238-db608c00-0739-11eb-955d-83136f3e59eb.jpg)

**Comment by garfield69** [comment]
None of the team have an account on this site ATM.
If you want to help us resolves this then please provide a **full enhanced** log with the debug and HTML included so we can try to take a look and see if the issue is simple enough to resolve without needing an account for full testing.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
Thanks.

**Comment by Deflated-Criossant** [comment]
pornbay uses session cookie

I hope `|||%%PREVJACKPASSWD%%|||` is n't the problem

[pornbay html.txt](https://github.com/Jackett/Jackett/files/5338940/pornbay.html.txt)
[enhanced_log.txt](https://github.com/Jackett/Jackett/files/5338974/enhanced_log.txt)

**Comment by garfield69** [comment]
the html you provided shows that the browser search you performed is displaying results in a grid layout, while the Jackett indexer is expecting a torrent table (table#torrent_table).

has pornbay got an account profile setting that lets you switch your torrent search page view, from grid (posters) to list (tables) ?
or perhaps the torrent search page itself has a button to switch from grid view to list view?

if you cant find any, then I will update the indexer to process the html you loaded.

**Comment by Deflated-Criossant** [comment]
> 
> 
> the html you provided shows that the browser search you performed is displaying results in a grid layout, while the Jackett indexer is expecting a torrent table (table#torrent_table).
> 
> has pornbay got an account profile setting that lets you switch your torrent search page view, from grid (posters) to list (tables) ?
> or perhaps the torrent search page itself has a button to switch from grid view to list view?
> 
> if you cant find any, then I will update the indexer to process the html you loaded.

Yes, there is a profile setting to toggle GRID view ON and OFF

torrent search page does NOT have any switch button


this when I disabled GRID View

 <table class="torrent_table grouping" `id="torrent_table"> 

 <table class="noborder">

**Comment by garfield69** [comment]
so have you tried using the Jackett indexer when you have the grid view OFF in your account profile?

**Comment by Deflated-Criossant** [comment]
So, I re-ran and checked enhanced log

no write access to change config

**ran Jackett as admin**
now its working

![Screenshot_65](https://user-images.githubusercontent.com/16240121/95329197-3625ef00-08c4-11eb-8bda-6c680a1b46db.jpg)

**Comment by garfield69** [comment]
I will add a note to the pornbay indexer config reminding users to turn GRID view OFF in their account settings, and update the indexer with a missing categories while I'm there.

**Comment by garfield69** [comment]
Jackett 0.16.1635
