### ISSUE TITLE
xxxadulttorrent: torrents without download links

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9756]
The download link is not working in some torrents with 0B size.

![image](https://user-images.githubusercontent.com/10577978/95130023-3acf9380-075c-11eb-94e1-ece3b9245d9f.png)

Same thing in trupornolabs

![image](https://user-images.githubusercontent.com/10577978/95130297-a580cf00-075c-11eb-99ad-682e40a3303b.png)

**Comment by garfield69** [comment]
entries with size 0B on these sites are torrents which no longer have a details page
![image](https://user-images.githubusercontent.com/6933240/95147339-f9cb9380-07dc-11eb-9321-f07588308ce6.png) and therefore have to details page download link.

so we need to exclude them from the results by row filtering out these ones if the size is 0B. I'll research if this is possible.
