### ISSUE TITLE
torrentfactory: add an option to exclude vip torrents

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9757]
Regular users can't download VIP torrents (4K category). We should add a configurable option to exclude results from this category.

**Comment by ngosang** [comment]
@garfield69 I have  account in this site but I don't know how to do it in Cardigann. Do you have some example?

**Comment by garfield69** [comment]
Closest yml indexer I can find is BigTower's donor config.
test PR #9759  and see if it does the job.

**Comment by ngosang** [comment]
Fixed in #9757
