### ISSUE TITLE
firebit: download links not working for any torrent

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9758]
The download link is not working for this torrent => https://firebit.net/141291-%D1%97%D0%B6%D0%B0%D0%BA-%D1%81%D0%BE%D0%BD%D1%96%D0%BA-2020-bdrip-720p-ukr

**Comment by garfield69** [comment]
none of the download links are working for me. I'll investigate.

**Comment by garfield69** [comment]
Hmmm. 
details page .torrent download link
```html
<div class="link-download2">
  <a class="link download-links download" file_name="Їжак Сонік (2020) BDRip 720p {Ukr}" rel="nofollow" href="/download.php?id=162996">Скачать торрент</a>
</div>
```
which was matched by the indexer according to the enhanced log:
```html
2020-10-06 15:21:13 | Debug | CardigannIndexer (firebit): Download selector a[href^="/download.php?id="] matched: <a class="link download-links download" file_name="Їжак Сонік (2020) BDRip 720p {Ukr}" rel="nofollow" href="/download.php?id=162996">Скачать торрент</a>
2020-10-06 15:21:13 | Debug | WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://firebit.net/download.php?id=162996)
2020-10-06 15:21:14 | Debug | WebClient(HttpWebClient2): Returning OK => 0 bytes
```
the site is returning 0 bytes so is the site is recognising jackett is not a browser?
the same link from my browser https://firebit.net/download.php?id=162996 works fine.

this one is for you to look into I think, its not a yaml issue but cardigann.
If you cant figure it out then we can always use the magnet from the details page instead, albeit some users with blackholes will complain ;-b

**Comment by ngosang** [comment]
I think it's not caused by the user-aget, it's the referer. Could you add some referer to the download query?

**Comment by garfield69** [comment]
the yaml download block does not appear to support adding headers
https://github.com/Jackett/Jackett/wiki/Definition-format#download

**Comment by ngosang** [comment]
It's easy to add the headers block but I don't think it's necessary.
I'm going to add the Referer link for all trackers instead because I think it can solve related issues in other trackers too. If downloads stop working in other trackers let me know.

**Comment by garfield69** [comment]
Jackett 0.16.1664
