### ISSUE TITLE
Jackett searching with movie year brings up no results.

### ISSUE THREAD

**Issue by katsikhs** [Jackett/Jackett#976]
Hello,

I have been using Jackett for quite some time, and I just added an account on HDClub. I'm not sure whether this is an issue with CP, Jackett or the tracker search (probably the latter), but Jackett searches for <Movie title> <year>, and the search brings up no results. Searching manually on the site using this format indeed brings no results, while searching with <movie title> only does bring up results.
This seems relevant to issue #736 in case this helps.

Is there a way to remove the year from the search query?

Thanks

Jackett version:  0.7.902.0
Mono version (if not using Windows):  Stable 4.6.2

-------------------------------

**Comment by kaso17** [comment]
It seems like you're missing the example search keywords #893.
If the additional year is the problem then it seems like it's possible to disable it (based on #736) in couchpotato.
#893 probably would be also a solution for this problem.

**Comment by kaso17** [comment]
I assume disabling the year fixed it for you.
