### ISSUE TITLE
[REQ] manual search profiles

### ISSUE THREAD

**Issue by fejjj** [Jackett/Jackett#9767]
for example, i don't want to include public trackers in most of my manual searches, but i don't want to remove them from jackett entirely.  so preset profiles for various trackers would be nice i think.  even just an option added to the 'tracker' dropdown in manual search - "exclude public trackers"

**Comment by ilike2burnthing** [comment]
For requests regarding indexer profiles, see #2185, #8884, and #4787, with the latter detailing a current workaround (also described in #661).
