### ISSUE TITLE
[req] DariusTracker

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#9768]
DariusTracker a Private Hungarian site. https://dariustracker.hu/
MST 3days
tpp default 30

**Comment by garfield69** [comment]
Jackett 0.16.1621

**Comment by garfield69** [comment]
https://dariustracker.hu/ returns 
![image](https://user-images.githubusercontent.com/6933240/180590959-f2c8af50-161e-4617-acde-37a4286aa0bc.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://dariustracker.hu/ ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
v0.21.446

**Comment by garfield69** [comment]
There are no torrents on the site. If after 30 days none appear then I see little point indexing the site.

**Comment by ilike2burnthing** [comment]
80 torrents up now

**Comment by garfield69** [comment]
https://dariustracker.hu/ redirects to https://bitvalor.hu/

**Comment by garfield69** [comment]
v0.21.716

**Comment by garfield69** [comment]
v0.21.1781

**Comment by garfield69** [comment]
https://dariustracker.hu/ invalid CA redirects to https://xider.eu/

**Comment by garfield69** [comment]
v0.22.685
