### ISSUE TITLE
[Pornbay] Include Freeleech torrents only in setting

### ISSUE THREAD

**Issue by Deflated-Criossant** [Jackett/Jackett#9772]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:  Windows 10 x64 1909

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] .Net-Core

**.Net Version**: 3.1.402 x64

**Jackett Version**: 0.16.1621.0

**Last Working Jackett Version**: 0.16.1621.0

**Are you using a proxy or VPN?**  no

### Description

Pornbay : Include 'Freeleech torrents only'  option in setting

-   https://pornbay.org/torrents.php?filter_cat%5B51%5D=1&order_by=time&order_way=desc&filter_freeleech=1&searchtext=&action=advanced&title=&sizeall=&sizetype=gb&sizerange=0.01&filelist=&taglist=

Include `&filter_freeleech=1 ` when query is passed

Freeleech torrent HTML Code
`      <img src="static/common/symbols/freedownload.gif" alt="Freeleech" title="Unlimited Freeleech" />`
Hope it helps

Optional : Is it possible to include Advanced Filters available on the site ? Similar to empornium

-   https://pornbay.org/torrents.php?filter_cat%5B51%5D=1&order_by=time&order_way=desc&filter_freeleech=1&limit_matches=1&searchtext=&action=advanced&title=&sizeall=&sizetype=gb&sizerange=0.01&filelist=&taglist=

limit_matches=1

max 100 results
  
### Screenshots
 
Advanced Filters : 

![Screenshot_67](https://user-images.githubusercontent.com/16240121/95330070-9ec19b80-08c5-11eb-9102-962a21d619d8.jpg)

Jackett Freeleech torrent table list
![Screenshot_66](https://user-images.githubusercontent.com/16240121/95329763-19d68200-08c5-11eb-8c44-2fc5020ebd8f.jpg)

thanks in advance

**Comment by Deflated-Criossant** [comment]
taken from emp

` {
    "id": "searchfreeleechonly",
    "type": "inputbool",
    "name": "Search freeleech only",
    "value": true
  } `

this needs to be added to `\Indexers\pornbay.json`

I was able to do it locally and test successfully
![Screenshot_69](https://user-images.githubusercontent.com/16240121/95336406-45aa3580-08ce-11eb-91c6-85be08ac363c.jpg)

![Screenshot_68](https://user-images.githubusercontent.com/16240121/95335957-aa18c500-08cd-11eb-9741-5628494094de.jpg)

I read something about index manager....does it generate automatically?

**Comment by garfield69** [comment]
Jackett 0.16.1635
