### ISSUE TITLE
[sharewood tracker] 1 result but not visible in array

### ISSUE THREAD

**Issue by neo62248** [Jackett/Jackett#9774]
Hello, 

## Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: last stable

**Last Working Jackett Version**: last stable

**Are you using a proxy or VPN?** [yes/no] no

### Description

I have configured sharewood provider (generalist french tracker), and when i search manually with this provider, it indicates a result found but this result is not shown in the array : 

![001](https://user-images.githubusercontent.com/5675981/95345306-e262d800-08ba-11eb-9f40-72635d832d6d.png)

### Logged Error Messages

Only two log messages in the log.txt : 

2020-10-07 16:27:26.4138 Info Fetching: https://www.sharewood.tv/filterTorrents?search=alias&description=&uploader=&sorting=created_at&direction=desc&qty=100&freeleech=
2020-10-07 16:27:27.3355 Info Manual search for "alias" on sharewood with 1 results.

Seems that Jackett does not fetch results with the correct url, the url from sharewood website is [https://www.sharewood.tv/torrents?recherche=alias]

**Comment by garfield69** [comment]
On Sharewood, the search for **alias** returns one torrent that has **zero** seeds.
![image](https://user-images.githubusercontent.com/6933240/95377345-ed5f4c00-093e-11eb-81ef-2c1c07b9602e.png)

On your Jackett dashboard search panel you will find a checkbox for **show dead torrents**
Yours is currently **not** ticked, and therefore the panel is hiding results with zero seeders.
**Tick the box** and the results will be displayed.

**Comment by neo62248** [comment]
Thanks for this response. Indeed, I did not think of that. Checking this box allows you to get the results. But is it relevant to display a counter at 1 for Sharewood if the box is not checked and the result does not appear in the table?
Anyway I haven't said it yet, but I find Jackett very powerful and practical :). Thanks again.

**Comment by garfield69** [comment]
>But is it relevant to display a counter at 1 for Sharewood if the box is not checked and the result does not appear in the table?

yes it is relevant, because that counter is telling you how many results the Web site returned, not how many are being displayed.

The search filters (search: on the right of the _show dead torrents_, and the _dead_ check box itself), apply display filters **after** the results have been fetched, so if you searched for **alias** and then filtered the display for _harry_  you would see zero torrents, but the counter would remind you that there are in fact results available from the **alias** search ;-)
