### ISSUE TITLE
[New Tracker REQ] LosslessClub (LC)

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#978]
Indexer Name
LosslessClub (LC)

Type
FLAC Audio

Indexer URL
https://losslessclub.com/

Indexer Language
Russian, Ukrainian, English, Bulgarian

Invite
You can request an invite directly from the Admin by filling up the following form:
http://losslessclub.com/invite.php?type=request

After answering the questions and submitting the form, you'll receive an email. Make sure you confirm your application by clicking on the link found in the email.  Within a few hours, you should receive another email with a link and an invite code.

**Comment by kaso17** [comment]
applied

**Comment by armani316** [comment]
@kaso17 Did they Admin get back to you with an invite?

**Comment by kaso17** [comment]
not yet

**Comment by kaso17** [comment]
added with fb5b5dc99c68bb2c00aa89b7186ffade97badda7

**Comment by ilike2burnthing** [comment]
This is not an invite request forum, do not use it as one.
