### ISSUE TITLE
mejortorrent: error downloadling torrent

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9783]
"query": ""

{"FirstSeen": "0001-01-01T00:00:00", "Tracker": "MejorTorrent", "TrackerId": "mejortorrent", "CategoryDesc": "Other", "BlackholeLink": null, "Title": "Aute Retrato.: Aute Retrato", "Guid": "https://www.mejortorrentt.net/secciones.php?sec=descargas&ap=documentales_extend&id1=2398&id2=2399&titulo=Aute-Retrato", "Link": "http://192.168.1.191:9119/jackettqa/dl/mejortorrent/?jackett_apikey=04x8qe2rdz5zpynt5cazhemvs9nk5n8u&path=Q2ZESjhELVhMWHlqR1FkRnFOSTdGdDhSZk5ULTEzRGwwNFlQMzRYUWpUTVRRb0tQUGQ2VEROUmJMdy1Zb1kzcHdxWDU1bF9XWUpYRHRSNXl4cHlzMmJrZGgyQU1RWXJ1NVktSV9MSXc3VndvbllueWJZeGJ2V05UN1FJb242UDhPMXkxNlgwc3kyeU9uT3N5ak5HcUluZi03QmxCbS1lMjRTeVp1TjdCVjUtSVhJdTVrZVJkQWhWR2Vpb0tkQmVmQ1dDc2xIak5oaHRvQkpOa1FnNXRKMS1yWlhFcC1HSnplRmRtUk42dTE4eWdkZU1CMXNNekx3YVdVemFCXzJXMTBsc0JhUUs5c2kyZnBQbTlfNmtINjZ1Y3JaMA&file=Aute+Retrato.%3A+Aute+Retrato", "Comments": "https://www.mejortorrentt.net/secciones.php?sec=descargas&ap=documentales_extend&id1=2398&id2=2399&titulo=Aute-Retrato", "PublishDate": "2020-10-07T00:00:00", "Category": [7000], "Size": 104857600, "Files": 1, "Grabs": null, "Description": null, "RageID": null, "TVDBId": null, "Imdb": null, "TMDb": null, "Author": null, "BookTitle": null, "Seeders": 1, "Peers": 1, "BannerUrl": null, "InfoHash": null, "MagnetUri": null, "MinimumRatio": null, "MinimumSeedTime": null, "DownloadVolumeFactor": 0.0, "UploadVolumeFactor": 1.0, "Gain": 0.09765625}, [{"Level": "Error", "Message": "Error downloading. indexer: mejortorrent path: https://www.mejortorrentt.net/secciones.php?sec=descargas&ap=documentales_extend&id1=2398&id2=2399&titulo=Aute-Retrato\nSystem.NullReferenceException: Object reference not set to an instance of an object.\n   at Jackett.Common.Indexers.MejorTorrent.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MejorTorrent.cs:line 108\n   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97", "When": "2020-10-08T11:09:54.2950603+02:00"}

**Comment by garfield69** [comment]
Jackett 0.16.1664
