### ISSUE TITLE
newpct: improve rss/empty search

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9785]
NewPCT removed the "latest releases" page => https://pctmix.com/ultimas-descargas/
I don't know if it's temporary or not. By now, we have a hack to get latest movies => #9786

PD: They have a new site with different layout. We should wait to see if they deploy this layout in all domains. https://pctfenix.com

**Comment by ilike2burnthing** [comment]
https://pctreload.com/ultimas-descargas/ is back up, mix's is still down

**Comment by ilike2burnthing** [comment]
https://pctreload.com/ultimas-descargas/ and https://pctmix.com/ultimas-descargas/ both working again

**Comment by garfield69** [comment]
Jackett 0.16.1709
