### ISSUE TITLE
[REQ] T411

### ISSUE THREAD

**Issue by foux** [Jackett/Jackett#98]
Hello,

I saw that T411 was previously present, but has been removed. Can we know the reasons?

Thanks in advance

**Comment by raspdealer** [comment]
No more public trackers are supported :(

**Comment by djdmd** [comment]
t411  is not public we have to login before donwload

**Comment by piluc88** [comment]
Please add t411 please i need this tracker

**Comment by piluc88** [comment]
yes it's not a public tracker we have a ratio

**Comment by WhatFox** [comment]
Public sign up and ratio doesn't make it private

**Comment by jrozelle** [comment]
So what's the problem with that ?

**Comment by jrozelle** [comment]
We are a lot of french user who want to use T411 with jackett.
The job is already done, why remove T411??

**Comment by JigSawFr** [comment]
We know that, but it's decision from Jackett owner to remove all (not only french) public trackers, so final solution for you is to fork and implement T411 as a new provider, you can take a look at the old provider.

**Comment by jrozelle** [comment]
:(
