### ISSUE TITLE
[req] Add new Tracker funreleases.me

### ISSUE THREAD

**Issue by Rafaelrico7** [Jackett/Jackett#9812]
funreleases.me is a private german tracker and it would be nice if it could be added to jackett. 
I could borrow my account for development access if needed.

**Comment by garfield69** [comment]
If you send credentials for temporary access for  the site to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.

**Comment by garfield69** [comment]
Can't find rules or FAQ about H&R. is there a minimum seed time (24hours 48, 72, whatever) ?
or is it 1:1 ratio for all downloads? 
I think the minimum ratio is 0.5, under which penalties begin to apply. can you confirm?

**Comment by Rafaelrico7** [comment]
There is no specific minimum seed time, but they have stated in the FAQ, that one should let the torrent seeding after the download finishes. So I think 48 hours is ok, as it is pretty standard on german trackers and they had not made a specific statement to that topic. . 
Minimum ratio of 0.5 is correct, below that your download capabilitys will get disabled.

**Comment by Rafaelrico7** [comment]
Thank you very much!

**Comment by garfield69** [comment]
Jackett 0.16.1724

**Comment by ilike2burnthing** [comment]
https://funreleases.me/ - Error 521 - Web server is down
