### ISSUE TITLE
[hd-only] request to migrate from C# to yaml

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#9814]
hd-only is currently using the Gazelle abstract, but this provides fairly basic results.
![image](https://user-images.githubusercontent.com/6933240/95704522-972b3980-0cad-11eb-9fbe-aaa15cc34f07.png)
notice missing categories, detail-less titles and no posters.

@foXaCe has requested if we could migrate to a yaml based indexer so that we can support replacing multi as per #9544 
it was suggested that the hd-forever yaml indexer could be used as a template, and while this indexer is similar (also a gazelle flavour), converting for hd-only will require quite some work as hd-only's gazelle implementation does not support categories, nor has it freeleech slots, among the many differences.

However, I think we can improve on the results presented by the current C# indexer, including adding banners and freeleech searching, and an attempt to use the sites release-type tagging as a pseudo category, at least for results.

I'll give it a go and see what comes of it.

**Comment by foXaCe** [comment]
good thank you

**Comment by garfield69** [comment]
example of new indexer
![image](https://user-images.githubusercontent.com/6933240/95707219-6ea73d80-0cb5-11eb-97fe-6a1bd78e2008.png)

**Comment by garfield69** [comment]
Jackett 0.16.1684

**Comment by foXaCe** [comment]
in radarr it gives zero result
did I omit something?
hdf same problem

Categories 2000

**Comment by foXaCe** [comment]
log radarr
2020-10-12 18:46:33.9|Info|DownloadDecisionMaker|No results found

**Comment by garfield69** [comment]
I did not test hdf and hdo with radarr. if you provide access again I can research.
which version of radarr are you on, v2 or v3beta?

**Comment by foXaCe** [comment]
v3beta?

**Comment by foXaCe** [comment]
I restored your access with the same password

**Comment by garfield69** [comment]
>v3beta?

just access your radarr app , click on the system tag, and scroll down the version and report that please thanks.

**Comment by foXaCe** [comment]
Version
3.0.0.3918

**Comment by garfield69** [comment]
Radarr is generating queries for movie titles with the year included, and it looks like the hd-only web site does not support this.
e.g. `driver 1978`
no results: https://hd-only.org/torrents.php?groupname=Driver+1978&order_by=time&order_way=desc&action=advanced&searchsubmit=1&freetorrent=
results: https://hd-only.org/torrents.php?groupname=Driver&order_by=time&order_way=desc&action=advanced&searchsubmit=1&freetorrent=

simple enough to strip the year from titles in the indexer before the search query is sent to the web site.
I suspect hd-f is the same.

**Comment by foXaCe** [comment]
this option ?

![image](https://user-images.githubusercontent.com/290678/95781528-4b3cbc80-0cce-11eb-9683-2cd0f36c6621.png)

**Comment by garfield69** [comment]
yes that works too.
