### ISSUE TITLE
Handling apostrophes (') in search strings

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#982]
Some trackers handle apostrophes accurately, whereas others do not. This has to do with the trackers themselves, not Jackett.

E.g. Some trackers will return accurate results whether (Sophie's Choice) or (Sophies Choice) is entered as a search string. For others, you must search using the 2nd (i.e. without an apostrophe) for the tracker to be able to return the correct results.

Can apostrophes be replaced by a wildcard for all search strings in all trackers so that Jackett would automatically search for both (Sophie's Choice) AND (Sophies Choice) to return all possible results?

**Comment by kaso17** [comment]
It needs to be solved on a per-tracker basis.

I had a problem with one tracker (can't remember which) where I had to include the ' in the search (without/with wildcard instead didn't work).

Please post trackers where it needs to be replaced.

**Comment by armani316** [comment]
@kaso17 If it needs to be done on a per-tracker basis, let me close it for now and revisit when I get the chance to test a few trackers.

**Comment by flightlevel** [comment]
@armani316 Thanks for all your help
Would you like access to close and label issues for Jackett

**Comment by armani316** [comment]
@flightlevel Thank you very much. Yes, please. I would very much appreciate access to close and label issues for Jackett. I'm not a developer/coder, but I use Jackett quite often, so I'll try my best to help out. Thanks again.

**Comment by flightlevel** [comment]
Great
Can you send an email to jackettapp AT gmail DOT com so I can send an invite

**Comment by armani316** [comment]
@flightlevel I believe you have already sent an invite to my existing email. I just accepted. and everything is working fine now. Thank you for this opportunity.
