### ISSUE TITLE
vsttorrents: unrelated results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9824]
I'm getting only 10 results and most of them are unrelated.
Query: flac

**Comment by garfield69** [comment]
its not a music site for mp3 flac albums vinyl or CDs.

Its a specialised site for audio apps and plugins and loop samples site for musicians/DJ 

i'm not going to spend any time trying to improve it b ymultiplying the requests per search by 5 to fetch 50
the server is probably on a budget and will probably fall over. ;-D
