### ISSUE TITLE
[req] add wOOt a German private tracker https://mywoot.biz/

### ISSUE THREAD

**Issue by Rafaelrico7** [Jackett/Jackett#9828]
wOOt is a private German tracker and it would be nice if it could be added to jackett.
I can provide an Account for temporary Access to the site.
Minimal Seeding Time after Download finished: 48 Hours
Minimal Ratio: 0.7

**Comment by garfield69** [comment]
If you send an invite (or temp credentials) to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by garfield69** [comment]
Jackett 0.16.1724

**Comment by ilike2burnthing** [comment]
Thanks. We'll monitor https://mywoot.biz/ for the usual 30 days and remove it if there's no signs of life before that point.

**Comment by garfield69** [comment]
@Rafaelrico7  do you have any info on wOOt, is the site gone, just broken, or moved to a new domain?

**Comment by garfield69** [comment]
v0.20.3593
