### ISSUE TITLE
[req] add new private german tracker borgzelle.borg

### ISSUE THREAD

**Issue by Rafaelrico7** [Jackett/Jackett#9855]
borgzelle.borg is a german private tracker that is based on the software gazelle.
Borgzelle is also a tracker which don't uses public DNS or a public signed CA / TLS Certificates. So you have to add the IP's to your host file and accept the unsigned (not secure) CA. I don't know if you add a tracker like this to jackett but if you do:
I can provide temporary development access credentials to the tracker.
Minimal Seeding Time after download finishes: 72h
Minimal Seeding Ratio: 0.7

**Comment by garfield69** [comment]
what is the ip address for the site?

**Comment by Rafaelrico7** [comment]
Hi they are 4 of them:

178.175.129.82 borgspeak.borg
178.175.129.82 borgradio.borg
178.175.129.82 borgzelle.borg
178.175.129.82 announce.borg

**Comment by garfield69** [comment]
if I use the ip address on a browser (and ignore the self signed cert) I get a blank screen.
what is the login page subdomain? eg: `https://123.123.123.123/login.php`

**Comment by Rafaelrico7** [comment]
I think you have to add the IP's to your /etc/hosts or %windir%\system32\drivers\etc/HOSTS File or it wont work otherwise because of SNI (Server Name Identifier). Login Page Subdomain is: borgzelle.borg/login.php

**Comment by garfield69** [comment]
@ngosang  Do you think that we should support a web site that does not have a public DNS and would require an info note in the config explaining how to add the ip address to the local hosts file in order to use the indexer?
Or maybe, given that they clearly value their privacy, we should not add an indexer for this site?

**Comment by garfield69** [comment]
or maybe just an info note that says "if https://borgzelle.borg" does not resolve for you then you are not an authorised user" ;-)

**Comment by Rafaelrico7** [comment]
I would prefer this second solution. Because every borg user knows this IP's and also knows how to add those to the host file. They couldn't otherwise login. So I think that would be a really nice solution :)

**Comment by ngosang** [comment]
>  "if https://borgzelle.borg" does not resolve for you then you are not an authorised user"

I agree

**Comment by garfield69** [comment]
Jackett 0.16.1783

**Comment by GeenHorn** [comment]
Hello, I am Borg clock stone of the second hour. Although I have my breaks from time to time, I always come back and would like to remain part of the collective now.

I missed the last IP change and so I am missing the current IP.

I cannot reach anyone via other channels either. Forum gone, TS off, IRC not available and no one answers under the old mail addresses that I have.

can someone give me the new IP? I can do the rest.
Thank you

**Comment by virusperfect** [comment]
I'm getting "503 Service Unavailable" even though i have the DNS entries.
