### ISSUE TITLE
[orpheus.network] add support for api tokens

### ISSUE THREAD

**Issue by itismadness** [Jackett/Jackett#9860]
Similar to #8898 

Requesting support for orpheus.network for usage with API tokens. Documentation for our API is located at https://github.com/OPSnet/Gazelle/wiki/JSON-API-Documentation. Usage compared to RED is mostly the same, with the principal difference in that we specify a type (`token`) in our authorization header.

**Comment by seeyabye** [comment]
API for RED is currently on hold due to a core bug related `User-Agent`. If Orpheus.Network allows spoofed `User-Agent`, I will implement this, otherwise, it will need to wait until https://github.com/Jackett/Jackett/pull/8431 is resolved/merged.

**Comment by itismadness** [comment]
I do not care about `User-Agent` when utilizing the API or the site regularly, beyond that we use it to get a picture of browsers people use and to know how many people might be affected as we incorporate new JS features into our codebase.

**Comment by seeyabye** [comment]
Since orpheus agrees, then I will have this implemented. While I would like that Jackett sticks with the principle of "good web citizen", it's something that was fundamentally decided a long time ago and the change is rather difficult until we nail down functional tests so that Jackett doesn't break.

**Comment by itismadness** [comment]
To give a slight update to you folks, we are rolling out a patch in the next few days to allow usage of our API with the same authorization format (`Authorization: ${api_token}`) as RED, though we would prefer people to use the `Authorization: token ${api_token}` format to adhere to general W3C recommendations on that front.
