### ISSUE TITLE
[AwesomeHD] Exception (AwesomeHD): Invalid URI: The format of the URI could not be determined.: Parse error (Test)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#9861]
### Environment

**OS**: Windows 10 Pro 64-bit 

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.16.1740.0

**Last Working Jackett Version**: Not sure

**Are you using a proxy or VPN?** No

### Description

I am unable to configure AHD

### Logged Error Messages

`Exception (AwesomeHD): Invalid URI: The format of the URI could not be determined.: Parse error (Test)`

### Screenshots
Not needed

@ngosang Looks like something changed from AHD's side? I imagine it's the same for you, which is why I have not posted the error log.

**Comment by Motophan** [comment]
latest update fixed this for me

**Comment by garfield69** [comment]
the last time the awesomehd indexer was updates was 25 days ago.
the indexer on 0.16.1757 is not working for me , returning the same error as reported in the first post.

**Comment by RoloSoze** [comment]
> 
> 
> latest update fixed this for me

I am using Jackett's latest version [0.16.1757.0] but I still have this issue, as @garfield69 said. Hopefully @ngosang gets to it when he has time.

**Comment by garfield69** [comment]
Jackett 0.16.1771

**Comment by RoloSoze** [comment]
@seeyabye Works well. Thank you!
