### ISSUE TITLE
[REQ]gtorrent.org

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#9868]
Russian mix public torrent sites.
Search engine and torrent links is working
Torrent is seed.

link: https://gtorrent.org/

**Comment by garfield69** [comment]
Jackett 0.16.1819

**Comment by ilike2burnthing** [comment]
Changed to a browser game site???

**Comment by garfield69** [comment]
v0.18.444

**Comment by entrider** [comment]
Please add [gtorrent.club](https://gtorrent.club/) back.

**Comment by garfield69** [comment]
Moved to #11255
