### ISSUE TITLE
[New Tracker REQ] HDHome

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#987]
**Indexer Name**
HDHome (HDH)

**Type**
Movies & TV shows in HD, Audio, Other

**Indexer URL**
https://hdhome.org/

**Indexer Language**
Mandarin, some English

**Invite**
HDHome is currently open for signups (for a very limited time to celebrate the Chinese New Year): 
https://hdhome.org/signup.php

**Note**
As with most Chinese trackers, there's an assessment that you need to pass within 30 days of signing up in order to keep your account. You'll find the assessment details on your homepage once you sign in.

**Comment by armani316** [comment]
@kaso17 Any plans of signing up at HDH before registration closes? It's actually a decent Chinese HD tracker with around 10K torrents.

**Comment by kaso17** [comment]
added with cca2785e848f09fa3d1779ba470e09741f89a904

**Comment by RoloSoze** [comment]
@kaso17 HDHome just came back up after maintenance was done, and now the tracker cannot be configured in Jackett due to the changes/updates they made.

**Comment by kaso17** [comment]
fixed with b3dca67d0aafb0f7c5245f91a55cabcfc5d8c865

**Comment by RoloSoze** [comment]
@kaso17 HDH's management decided to revert to the old design after users complained. Now the tracker can't be configured in Jackett. I guess we need the old configuration back :)

**Comment by kaso17** [comment]
done with 2d4d27175b776b80ab1015c5ae99f095f2e9dea0

**Comment by RoloSoze** [comment]
@garfield69 HDHome uses HTTPS. Site Link needs to be changed.

**Comment by garfield69** [comment]
this was changed from https to http because of #6460
are you saying that they have switched back?
have you tested?

**Comment by RoloSoze** [comment]
@garfield69 It may have been a temporary issue at the time, but I tested it with HTTPS today and it works fine.

**Comment by garfield69** [comment]
okely dokely.

**Comment by garfield69** [comment]
https://hdhome.org/ returns Bad gateway Error code 502

**Comment by ilike2burnthing** [comment]
back up
