### ISSUE TITLE
[REQ] WatchSoMuch

### ISSUE THREAD

**Issue by nofences** [Jackett/Jackett#9876]
https://watchsomuch.org/

Public Site

Thank You.

**Comment by ilike2burnthing** [comment]
Proxies:
https://watchsomuch.unblockit.lat/
https://wsm.unblocked.rest/

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing

**Comment by hbednar** [comment]
Would it be possible to do RSS only and when running a search use cached entries from the RSS feed.

Another proxy:
watchsomuchproxy.com
