### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s).

### ISSUE THREAD

**Issue by koala784** [Jackett/Jackett#9883]
### Environment

**OS**: UnRAID 6.8.3

**Jackett Version**: 0.16.1783.0 (latest)

**Last Working Jackett Version**: 0.16.1771.0 (not a version issue I think)

**Are you using a proxy or VPN?** [yes/no] Yes, NordVPN (but only with Deluge, using OpenVPN-HyDeSa), so it doesn't impact Jackett in this case.

### Description

Exception (yggtorrent): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s).

Got this error with YggTorrent AND Yggcookie.

So it seems like #9882 and #9880, but the suggestion to use the YGGCookie indexer instead doesn't work (same error).

Jackett is up-to-date, I have already restarted it.

### Logged Error Messages

Exception (yggtorrent): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s).

![YGGCookie](https://user-images.githubusercontent.com/24566850/96367206-a6e2cc00-114c-11eb-862e-403afc5a8ae7.png)

![YGGtorrent](https://user-images.githubusercontent.com/24566850/96367207-a77b6280-114c-11eb-8ea4-531461c7bb49.png)

EDIT : Also reported on the YggTorrent forum : 

https://www2.yggtorrent.si/forum/index.php?threads/jackett-clearance-failed-after-30-attempt-s.43161/

**Comment by koala784** [comment]
So it seems like #9882 and #9880, but the suggestion to use the YGGCookie indexer instead doesn't work (same error).

**Comment by Bastien42** [comment]
Cloudflare is back

**Comment by koala784** [comment]
Does Jackett need an update ? 
It's still doesn't work for me.

**Comment by Bastien42** [comment]
> Does Jackett need an update ?
> It's still doesn't work for me.

it's a known issue with cloudflare the dev already said that they will not fix these errors as they are fixed every time cloudflare patches it so lets hope YGG disable it like last time

**Comment by garfield69** [comment]
With Jackett 0.16.1922 you should be able to make use of the YGGTorrent indexer again ... until the next DDoS event.
