### ISSUE TITLE
Cleanup of update files

### ISSUE THREAD

**Issue by Stanzilla** [Jackett/Jackett#989]
Jackett version:  0.7.876.0
Mono version (if not using Windows):  4.6.2

-------------------------------

Jacket does not clean up its update files like for example Sonarr does, it keeps filling the temp folder with it. Imo keeping the last 1? 2? should be enough and the updater should delete all the older folders.

**Comment by kaso17** [comment]
dupe #298
please update to the most recent version

**Comment by Nightraider89** [comment]
Is this a returning issue? since i have it for quite some tim on my readynas, runs latest version, keeps on updating to newer ones, but fails to delete the temporary setup files, causing my root drive to choke .
