### ISSUE TITLE
Feature to send Cached releases as RSS Feed to Sonarr

### ISSUE THREAD

**Issue by gamer-taken** [Jackett/Jackett#990]
The new releases from The piratebay are filled with Porn category and have zero seeds. Sonarr never downloads episodes automatically. 
If the list of cached releases is fed to Sonarr it is likely that the autodownload function will work with the piratebay.

**Comment by kaso17** [comment]
Caching doesn't seem to be the issue.
The core problem seems to be that the seeds are not very often updated leading the first few pages of recent torrents results always having 0 seeds.
For me the proper fix would be to fix it on the Sonarr side (add an option to accept torrents with 0 seeds).

A hack would to to always set the seeds to 1, you can edit the pirate bay definition file and change the seeders part to the following:
```
      seeders:
        text: 1
```

**Comment by armani316** [comment]
@gamer-taken Is this still an issue?

**Comment by gamer-taken** [comment]
@kaso17 's solution worked. It does add torrents automatically now.
