### ISSUE TITLE
[New Tracker REQ] InPeril

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#991]
**Indexer Name**
InPeril

**Type**
Has a fairly large database of Movies, TV, Audio, PC, Games, Anime, XXX

**Indexer URL**
https://www.inperil.net/

**Indexer Language**
Latvian, English, Russian

**Invite**
Signup is now open for a limited time:
https://www.inperil.net/signup.php

**Note**
Confirmation email might end up in your Spam/Junk folder

**Comment by kaso17** [comment]
added with 098caee07531aa85676142d01ef29e7530f40432

**Comment by dimqua** [comment]
The tracker is dead.

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/87232035-09228700-c410-11ea-953e-4169b6af2f77.png)
