### ISSUE TITLE
[Enhancement] Mark trackers as 'Public', 'Semi-Private', and 'Private'

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#992]
Now that Jackett supports public trackers as well as private and semi-private, may I suggest marking/labeling trackers according to the following definitions:

- **Public:** For trackers that do not require registration (e.g. The Pirate Bay, KAT, Sky Torrents, etc.)
- **Semi-Private:** For trackers that require registration, but for which registration is always open to the public (e.g. 7tor, RuTracker, etc.)
- **Private:** All other trackers that are usually closed, and require an invite 

The labeling should ideally apply to all trackers in both the 'Configured' and 'Non-configured' lists. It could be done via color coding, or a tag/label added next to each tracker, etc.

I think this would make it easier for users to conveniently distinguish among the 3 types, and make a decision as to whether or not to configure the tracker in Jackett.

**Comment by kaso17** [comment]
In the add tracker view we could simply add a new column.
For the configured view I would prefer a more subtle marking (if we should make them at all).
I'll work something out.

**Comment by armani316** [comment]
@kaso17 Works for me. Anyway to distinguish among these 3 categories would be very helpful. Thanks!

**Comment by kaso17** [comment]
added with 50c3a5fb3ac22d0954daaaf5ed3b41e8c4fb5209
Let me know if you notice any wrong tracker categories or have a better suggestion for icons. I'm using unicode lock icons (🔐︎🔒︎🔓︎) for now.

**Comment by armani316** [comment]
@kaso17 I'll check it out in the next update. First impressions: Great idea, but it seems that semi-private and public might be hard to distinguish - both locks look too similar? I'll be able to form a better judgement with the new release. Thanks a lot!

**Comment by kaso17** [comment]
v0.7.947 (pre-release) contains the changes

**Comment by armani316** [comment]
@kaso17 The new icons look great! To the point, and easy to distinguish! Thank you! A few corrections/additions:

- AvistaZ - [No icon] Should be private
- NetHD & TorrentBytes - [Private] Should be semi-private (everyone can sign up anytime)
- Freaks Tracking System & Tspate - [No icon] Not sure what they should be since I'm not on either one, and both are down at the moment so I can't check. I'll update this when they're back up

**Comment by kaso17** [comment]
fixed the types with 8a149ebe479f89a5c055b91dcd44019660f7d202
FTS and tspate have been removed a while ago, will delete them with the next update (85bb2dba344c3a7d1481959f24936afc1627ff31)
