### ISSUE TITLE
[abnormal] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by fana13** [Jackett/Jackett#9936]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Debian Buster

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:  Jackett Version 0.16.1844.0 

**Last Working Jackett Version**: no idea

**Are you using a proxy or VPN?** [yes/no] Yes

### Description

When test in indexers jackett
Check config of this indexer, config it's ok 
But when I want to click Okay button I've got this :
"Object reference not set to an instance of an object."
 

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
No one on the team has an account on Abnormal, so unless you have in invite we cannot investigate independently.
If you don't have an invite (or choose not to provide one, that's ok no problem) then perhaps an **enhanced** log with the extra debug and HTML will hopefully provide enough info to investigate further.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details

**Comment by fana13** [comment]
Thanks, 
After check log, it's only a ban ip, not a jackett's issue.
