### ISSUE TITLE
Trezzor tracker - wrong name of item in search results

### ISSUE THREAD

**Issue by kratochj** [Jackett/Jackett#9943]
While searching the result contains `View details:` in the name of the item in search results. 

### Environment

**OS**: Docker (`linuxserver` project)

**Jackett Version**:  0.16.1851.0

**Are you using a proxy or VPN?** no

### Screenshots

![image](https://user-images.githubusercontent.com/402281/96885779-3658e980-1483-11eb-8870-be4f41e1e407.png)

**Comment by garfield69** [comment]
No one on the team has an account on Trezzor, so unless you have in invite we cannot investigate independently.
If you don't have an invite (or choose not to provide one, that's ok no problem) then perhaps an **enhanced** log with the extra debug and HTML will hopefully provide enough info to investigate further.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details
Thanks.

**Comment by garfield69** [comment]
looking at the indexer, it appear it already has code to strip `Zobrazit detaily: ` from the title, so it likely that you are using the English language setting in your profile, and the indexer author did not think to add code to strip the `View details:` back when the indexer was written. Or perhaps multi-language support was introduced at the web site after the indexer was written.
