### ISSUE TITLE
[rarbg] Could not find releases from this URL (Config)

### ISSUE THREAD

**Issue by silentArtifact** [Jackett/Jackett#9950]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker/Synology

**.Net Runtime**: Uncertain

**.Net Version**: Uncertain

**Jackett Version**: 0.16.1859.0

**Last Working Jackett Version**: Uncertain

**Are you using a proxy or VPN?** No

### Description

Just updated my container to 0.16.1859.0

### Logged Error Messages

```
An error occurred while configuring this indexer
Could not find releases from this URL
```

**Comment by garfield69** [comment]
This is an intermittent issue at the RARBG API server.
There is nothing can be done about it at the Jackett side.
After a failure, retrying the search works most of the time, until the next time it does not.
