### ISSUE TITLE
[req]  Xtreme Bytes

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#9951]
~~TorrentSurf Private for movies tv general http://torrentsurf.net/~~

[edit] now  Xtreme Bytes at https://xtremebytes.net/
MR 0.8

**Comment by garfield69** [comment]
Jackett 0.16.1896

**Comment by ilike2burnthing** [comment]
https://torrentsurf.net/ - redirects to https://xwt.instatus.com/ - down because server is in Russia, new one is being set up

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://torrentsurf.net/ - Error 522 - Connection timed out

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
Torrent Surf is now retired. ALL user accounts and torrents have been imported to Xtreme Bytes.
XB is a sister site to XWT

rename indexer and amend for new layout.

**Comment by garfield69** [comment]
v0.20.2186
