### ISSUE TITLE
Add indexer list empty

### ISSUE THREAD

**Issue by jasperrooduijn** [Jackett/Jackett#996]
I'm running Jacket on the latest pre release version (0.7.952.0) but since the update the "Add indexers" modal box is empty. No indexers are shown to select. See screenshot.

![screen shot 2017-01-28 at 20 27 47](https://cloud.githubusercontent.com/assets/1854745/22399216/67a406dc-e598-11e6-81bf-76443bd8c7ae.png)

**Comment by flightlevel** [comment]
Working here
Can you try clearing your cache and also try a different browser
If that still doesn't work, please provide a full log https://github.com/Jackett/Jackett#troubleshooting and the contents of your browsers console https://developers.google.com/web/tools/chrome-devtools/console/

**Comment by armani316** [comment]
@jasperrooduijn Is this still an issue? If yes, could you please follow @flightlevel's instructions?

**Comment by rockymontana** [comment]
I had that problem too, and I get a full list when I open it in a porntab. Thanks for the tip!
