### ISSUE TITLE
YGGTorrent - Login failed

### ISSUE THREAD

**Issue by waredsystems** [Jackett/Jackett#9960]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker (Ubuntu)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.1873.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

Unable to connect to YGG tracker

### Logged Error Messages

An error occurred while updating this indexer
Login failed: No form found on https://www.yggtorrent.si/ using form selector #user-login

### Screenshots

![Capture](https://user-images.githubusercontent.com/11072379/97097947-87313380-1677-11eb-8a46-518e1edcd227.PNG)

**Comment by garfield69** [comment]
ATM, the YGGTorrent web site have a temporary redirect page in place which interferes with the Jackett indexer's ability to use the web site's login page.
Until YGG remove this http 307 response, the only way to use Jackett for this web site is with the YGGCookie indexer.

**Comment by ChrysMacZ** [comment]
Hi, thank for answer, but I don't know really where I found my cookie and the user-agent code, can you please just write what is it ? thank youuuu ! ! ! ;-)

**Comment by garfield69** [comment]
@ChrysMacZ  no I can't just write what it is, the cookie is unique to each users session and changes when it expires.
instructions for getting the cookie and useragent are in the config of the YGGCookie indexer.

**Comment by garfield69** [comment]
With Jackett 0.16.1922 you should be able to make use of the YGGTorrent indexer again ... until the next DDoS event.

**Comment by ChrysMacZ** [comment]
OK thank you I will try again ;-)
