### ISSUE TITLE
[REQ]otorrents.com

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#9965]
Public movie share torrent sites.
link: https://otorrents.com/

Search engine and magnet links working.

İt has big movie database.

**Comment by garfield69** [comment]
the torrent details page contains one or more torrent links
this will need a C# indexer.

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
