### ISSUE TITLE
TorznabController does not have a default constructor

### ISSUE THREAD

**Issue by dreazin** [Jackett/Jackett#997]
Jackett version:  v0.7.952
Mono version (if not using Windows):  Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)

-------------------------------

Trying to open any Jackett page or do any search results in the following crash. The page fails to load, or the search fails to return. Older versions seem to work fine. This issue started after Jackett automatically updated, but even reinstalling manually the issue remains. Older versions still work.

http://pastebin.com/RVfejZMp

**Comment by kaso17** [comment]
Please update mono to the latest version, mono 3 is probably the cause why the autofac dependency injection doesn't work.

**Comment by dreazin** [comment]
That worked, thanks!
