### ISSUE TITLE
[prostylex] Clearance failed after 10 attempt(s). (Config)

### ISSUE THREAD

**Issue by dramirvf** [Jackett/Jackett#9972]
I use the correct username/pass for this indexer (prostylex). It always gives the following error:
![image](https://user-images.githubusercontent.com/40552131/97129632-a3ef6900-1754-11eb-9474-b61b030f1f18.png)

**Comment by garfield69** [comment]
the web site has enabled the cloudflare DDoS protection because it has been under attack by nasty botnets.
there is not automated challenge solver library available for Jackett to use at this time.
so until the site lifts the protection you cannot use this Jackett indexer.
