### ISSUE TITLE
[req] BootyTape a semi-private 3x site https://ssl.bootytape.com/

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#9979]
BootyTape a semi-private 3x site https://ssl.bootytape.com/
MR 0.5

**Comment by ilike2burnthing** [comment]
https://ssl.bootytape.com/ - Error 521 - Web server is down

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
while you can login to the site https://ssl.bootytape.com/ without problems, accessing the torrent page results in the following error message:
`Lost connection to MySQL server during query`
and navigating to inbox or other pages generates
```
Warning: mysqli_connect(): (HY000/2002): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) in /home/bootyxxx/public_html/include/sqli_torrent.php on line 117
The server load is very high at the moment. Retrying, please wait...
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://ssl.bootytape.com/ returns 521

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://ssl.bootytape.com/login.php
Warning: mysqli_connect(): (HY000/2002): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) in /home/bootyxxx/public_html/include/sqli_torrent.php on line 117 Too many users. Please press the Refresh button in your browser to retry.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://ssl.bootytape.com/ > Warning: mysqli_connect(): (HY000/2002): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111) in /home/bootyxxx/public_html/include/sqli_torrent.php on line 117 The server load is very high at the moment. Retrying, please wait...

**Comment by garfield69** [comment]
online
