### ISSUE TITLE
[New Tracker REQ] GFXPeers

### ISSUE THREAD

**Issue by ShahadatRD** [Jackett/Jackett#998]
**Indexer Name**>> GFXPeers (GFXP)

**Type**>> Graphics/Misc

**Indexer URL**>> https://gfxpeers.net

**Tracker Language**>> English

**Invite**>> open signups is currently enabled at>> https://gfxpeers.net/register.php

**Comment by kaso17** [comment]
registered

**Comment by kaso17** [comment]
added with dfb2052c5c52406b4b6ba82e29ee84c682f07660
