### ISSUE TITLE
[REQ]tracker.minglong.org

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#9987]
Public anime share torrent site.
This site dont have search engine main page only group pages.
Link: http://tracker.minglong.org:8080/
Search engine working

İmg: https://ibb.co/2qyShyd
https://ibb.co/LxmZKcw

**Comment by garfield69** [comment]
this site is not suitable for support by Jackett.
the list of groups just takes you to different sites that may or may not have a search engine.
