### ISSUE TITLE
[REQmixtapetorrent.com(Music)

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#9988]
Public music share torrent site.
Search engine and torrent links working

Link: http://www.mixtapetorrent.com/

**Comment by garfield69** [comment]
Jackett 0.16.1933

**Comment by ilike2burnthing** [comment]
http://www.mixtapetorrent.com/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://www.mixtapetorrent.com/ returning This site can’t be reached

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://www.mixtapetorrent.com/ returning This site can’t be reached

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
Hmm, my cloudflare DNS is still reporting DNS_PROBE_FINISHED_NXDOMAIN

**Comment by garfield69** [comment]
Ah. if I drop the www. prefix it works

**Comment by garfield69** [comment]
http://mixtapetorrent.com/ returns 
![image](https://user-images.githubusercontent.com/6933240/172097440-f5d493a5-2f75-4490-87bd-938183fbe50c.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
http://mixtapetorrent.com/ Unable to select database

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
Hmm. I still see
![image](https://github.com/Jackett/Jackett/assets/6933240/60c22b60-9fcf-4859-ba57-c12677b16e84)
Just me then?

**Comment by ilike2burnthing** [comment]
Ah, that wouldn't show as a checkpoint failure for Uptrends then. Mark it as down again, could be an issue for others.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/9988#issuecomment-1882408294

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
http://mixtapetorrent.com/ > DNS Lookup Error

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
http://mixtapetorrent.com/ > Unable to select database

**Comment by ilike2burnthing** [comment]
back up
