### ISSUE TITLE
[BUG] 'Jackett.Controllers.AdminController' does not have a default constructor

### ISSUE THREAD

**Issue by rossdargan** [Jackett/Jackett#999]
Jackett version:   0.7.952.0 (impacts all versions after v0.7.923)
Environment version: 4.0.30319.17020 (/usr/lib/mono/4.5)
OS version: Unix 2.6.32.42 (64bit OS) (64bit process)
mono version: 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
-------------------------------
I'm following the install instructions here, but I doubt that has anything to do with this issue: http://www.htpcguides.com/install-jackett-on-ubuntu-14-x-for-custom-torrents-in-sonarr/

Every version of Jackett after V0.7.9.23 Gives an error stating "System.ArgumentException: Type 'Jackett.Controllers.AdminController' does not have a default constructor"

I honestly can't see any changes between V0.7.923 -> V0.7.932.0 that would mess with dependency injection.

I've attached debug logs for version .932. Let me know if there is anything else I can provide to help.

[logs.txt](https://github.com/Jackett/Jackett/files/737840/logs.txt)

**Comment by dreazin** [comment]
You have to update mono to version 4+. Had this same issue last night

**Comment by kaso17** [comment]
dupe #997
