### ISSUE TITLE
[REQ]pandacd.io

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#9990]
Public music sahre torrent site.
Link: https://pandacd.io/

Search engine and torrent links working.
İt has big database.

**Comment by garfield69** [comment]
one poster leads to many torrents.
indexer cannot be coded as yaml.
indexer requires C# support.

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing

**Comment by garfield69** [comment]
Site has Torznab API.

**Comment by garfield69** [comment]
v0.24.1601
