### ISSUE TITLE
[REQ]coalgirls.wakku.to

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#9996]
Anime fansub site.
Site is no active now but it has much anime.
Link: https://coalgirls.wakku.to

Search engine and torrent links working.

**Comment by garfield69** [comment]
while it has a torrents list page, its not tied to a search engine.
using search you get one-title-many-torrents.
not suitable for yml indexer
this WordPress engine site will need C# support.

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
