### ISSUE TITLE
[REQ]emtrek.org

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#9999]
Russian public mix content share torrent site.
Link: http://emtrek.org

Search engine and torrent link working.
it has big content.

**Comment by garfield69** [comment]
Jackett 0.16.1933

**Comment by garfield69** [comment]
http://emtrek.org/ returning `Could not connect to redis server`

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://emtrek.org/ returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.18.444
